### ISSUE TITLE
[flex] Flex resize smaller

### ISSUE THREAD

**Issue by keodime** [ag-grid/ag-grid#1011]
The grid resize smaller to bigger without problem, but bigger to smaller won't work when using flex.

Exemple:
https://plnkr.co/edit/VpT974rDcfoDFpEBaJpv?p=preview

**Comment by sstorie** [comment]
I created a similar issue: https://github.com/ceolter/ag-grid/issues/628#issuecomment-228136959

I don't have a good resolution though. I also get strange behavior when embedding two grids on one page. The latest thing I'm seeing is as I refresh the data the grid width slowly grows and won't shrink back down.

I think there's a requirement to have a correct flexbox design around the grid itself...but I don't know exactly what that is yet. I'm not a CSS guru though, so I've been battling a number of strange issues with flexbox that sometimes take me a while to figure out.

**Comment by keodime** [comment]
I do have the same probleme than you. I also have a bad redimension when going back to smaller screen, the grid will slowly swrink back to normal. 

I did find a part of the reason why, it seams to be in the ag-grid core in the doLayout function. When the grid compute his layout it doesn't get the good size of the window. I didn't push further. 

For now, I solve the problem by computing the size of the grid in my own javascript,  but it's not clean at all.

**Comment by sstorie** [comment]
FWIW, I cannot get my plunker to behave correctly, but in my production apps I've repeatedly found the issue is using flexbox without using `min-width: 0` and `min-height: 0` appropriately to prevent content from increasing the size of the flex'd container. 

I'm trying to use this grid in a single-page app so I'm working hard to constrain scrolling and overflow content using flexbox. You need to ensure the elements acting as a flex container have min heights and widths though, or things just don't work across all modern browsers.

**Comment by seanlandsman** [comment]
tracked by AG-130
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceastwood** [comment]
ag-grid@9.1.0
ag-grid-angular@9.1.0 (but should work outside angular)
lightly customized material theme
---

I believe I ran into this issue as well (grid will grow but not properly shrink when inside of flex); I was debugging through before coming across this issue and might have found a half-decent h4x/workaround. . I thought it may help someone to try it and or use it while AG-130 is backlogged but also please note that I have not done any thorough testing outside of my own application/environment so YMMV.

It looks like something in the ag-grid will set a style directly on the element with the class 'ag-bl-center-row' which updates on grow but does not change on shrink. If we unset the direct style the grid will resize as expected. I use the grid in some decently complex layouts and it works just fine. I'm sure there is a cleaner way but for now I've just attached to the root element of my applications onResize event and if we are shrinking I then locate any elements with the class 'ag-bl-center-row' and remove the direct style.

`
const agFlexSelector:string = 'ag-bl-center-row';
let elems = document.getElementsByClassName('ag-bl-center-row');
for (var index = 0; index < elems.length; index++) {
    var element: any = elems[index];
    element.style = '';
}
`

**Comment by AlanCrevon** [comment]
Hi all.

I have the same problem with Ag-Grid 12. @ceastwood 's fix works here but it feels a bit odd on Angular to access DOM through document.*.

An official fix would be verry much appreciated.

Cheers.
alan

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by petyosi** [comment]
Hi everyone, 

I think we found a solution for the problem you describe with the redesign of the website. The main demo now lives in a flexbox with vertical direction. The solution seems to be to set `overflow: hidden` to the container which hosts the grid. Notice that it looks like the grid element does not seem to like `display: flex` directly, though.

For your reference, I created an [updated version](https://plnkr.co/edit/hnhZBCiI3HZUH65Ad2wq?p=preview) of the original plunker in this issue.

Please test that and let us know how it works in your cases. Thank you.

**Comment by petyosi** [comment]
Update: [here is a version](https://plnkr.co/edit/GVi4f9hlKNvPw6fQpnZO?p=preview) which  also resizes the columns of the grid and seems to deal better with resizing in general.
