### ISSUE TITLE
[column] When moving column groups with drag&drop, hidden columns re-appear

### ISSUE THREAD

**Issue by mgabetta** [ag-grid/ag-grid#1054]
It looks like all columns that were visible in the column definition are shown again (also if the user hid them manually).

You can repeat this bug (?) in the online demo:
- hide Country and Language
- drag and drop Participant group somewhere
- Country and Language are shown again

This does not happen if you move Name column directly.

**Comment by ceolter** [comment]
yes i'm aware of this - your not the first to point out - but it's not a major problem for most people. it's not easy to fix - as the grid is not aware of what started the drag - as you can drag in from the toolPanel (in enterprise), in which case, you do want all the columns to show. given it's not trivial to fix and it's low priority, i wont be fixing it soon.

**Comment by seanlandsman** [comment]
tracked by AG-135
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by rmc-software** [comment]
Hi,

Just to update you that AG-135 has now been resolved and will be included in the next release.

Thanks
