### ISSUE TITLE
[filtering] Allow filtering of group rows

### ISSUE THREAD

**Issue by sfescape** [ag-grid/ag-grid#110]
Reflect groups hierarchically in the filter.

**Comment by ceolter** [comment]
Can you suggest what you mean by that please?

**Comment by sfescape** [comment]
When I use the grouping function, the individual rows show up in the filter drop down and can be added/removed from filtering. The group itself though can not be selected. In order to filter out an entire group I have to figure out which items are in the group and de-select each one. Once they are all de-selected the group becomes hidden.

For example:

group1
  row1
  row2
group2
  row3
  row4

Filtering allows me to deselect row1, 2, 3, 4 but not group1, 2. If I deselect row3, 4 then group2 becomes hidden. I would like to see group1, 2 in the filter dropdown so I can filter at the group level.

**Comment by ceolter** [comment]
Thanks for the explanation, that makes sense to me.

**Comment by gerlstar** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/3219706/22027918/66541766-dca3-11e6-8917-6c0a40ffb571.png)
This functionality would be great. It would be great if I can filter 'computer" and have the main parent row be displayed. See https://jsfiddle.net/efs3hycs/7/

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-43

**Comment by PTC-JoshuaMatthews** [comment]
@ceolter  Will the fix for this apply to tree formatted data? For instance right now filtering is narrowing the leaf nodes by removing ones that don't match. I need to implement a type of filter to allow searching for non leaf nodes by name and see matching nodes with all of its children even if the children do not match the filter. Is this possible?

**Comment by jrmoser** [comment]
@gerlstar I modified your jsfiddle with an [externalFilter](https://www.ag-grid.com/javascript-grid-filter-external/?framework=angular#gsc.tab=0). I believe this is will suit your needs until this enhancement gets added:

https://jsfiddle.net/efs3hycs/16/

**Comment by adrianromanko** [comment]
@ceolter Which release is the AG-23 feature planned for? There's currently no workaround in my case as only the leaf nodes get passed to the custom filter callbacks.

**Comment by PTC-JoshuaMatthews** [comment]
@adrianromanko  The workaround is to add data to each leaf node as it is being parses in the getNodeChildDetails function. That way when searching "just the leaf nodes" you can do a find on that extra data that encompasses every node up to the parent. Hope this helps.

**Comment by ceolter** [comment]
just finished rewriting how tree data works. next release has new implementation that includes delta updates and also searching at all levels (groups and leafs). the down side is that it's an enterprise feature (it reuses the grouping logic which is an enterprise modules). the old tree data is still included, however the good stuff is with the new tree data now. we plan to release in the coming days.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
