### ISSUE TITLE
[paste] Paste fails randomly with some browsers

### ISSUE THREAD

**Issue by mariusju** [ag-grid/ag-grid#1122]
Hello,

There is a bug about pasting content to grid cells.
Paste functionality sometimes fails on some specific browsers/os'es
This can be reproduced in the demo page of ag-grid.

How to reproduce:
Copy some text into clipboard and then repeat the following at least 10 times:
1. Select a cell
2. Press cmd+v or ctrl+v
3. move to the next cell of the same column using keyboard or mouse
4. Go to action 2

When I do this pasting loop some cells do not receive the pasted content.
It was tested on different browsers and operating systems, here are the results:

|  | Chrome | Firefox | Safari | IE |
| --- | --- | --- | --- | --- |
| OSX | Fails randomly | Works fine | Fails always |  |
| Linux | Works fine | Fails rarely |  |  |
| Windows | Works fine | Works fine |  | Works fine |

**Comment by ceolter** [comment]
regards safari support, see our docs ```Copy to clipboard is not supported in Safari. This is because the Safari browser does not implement the required API that ag-Grid uses, further details are described here. ag-Grid does not plan to support Safari clipboard as Safari is not generally used in corporate environments where the target audience for this feature resides.```, so until safari supports the API, we don't support it. we are comfortable with this, as heave business users are rarely on safari, they are typically on Chrome / Firefox and Windows (the OS of businesss!)

however it should work on Chrome and Firefox on OSX and Linux, , , , but given it's working on the same browser in different OS'es, it does feel like Browser issue (in that, the code works).

do you have any information on why it fails????

next step: i work on a Windows laptop, Sean is on OS and Linux - Sean, can you test this on Mac and Linux, verify and troubleshoot?

**Comment by seanlandsman** [comment]
I can reproduce this on my mac in chrome - it looks like the target cell sometimes loses focus, which is the cause of the paste no longer working.

We'll investigate further and see what we can find

**Comment by mariusju** [comment]
This is how I understand the current system works:
Grid listens to Cmd+V keydown event and than tries to create and focus a hidden text area before the browser (or system) paste handler kicks in. Am I right?

If so, then I guess there is a race condition between the grid creating and focusing the hidden textarea and the browser paste event.

If the browser handler is first, the browser is not able to paste a text to a currently focused field (cell div) and everything halts.
If the hidden textarea is focused first, then browser is able and pastes the contents to that area.

This possibly explains why that pasting is inconsistent.

**Comment by ceolter** [comment]
```Grid listens to Cmd+V keydown event and than tries to create and focus a hidden text area before the browser (or system) paste handler kicks in. Am I right?```
-> yes that's right. however it shouldn't be a race condition, as the paste part is all done in the same thread. the second thread (the timeout) is collecting the pasted data.

if you think it is a race condition, i guess the timeout could be given a few milliseconds to see if waiting for a while fixes it??

the timeout is in method executeOnTempElement, inside clipboardService.ts, if someone wants to experiment.

**Comment by xwb1989** [comment]
I got the very same problem with Chrome on OS X. 
Actually, it's not just pasting. Copying 'selected range' could also result in losing focus of the cell.

I have tried hacking the method @ceolter mentioned by increasing the timeout to 10ms, it seems to work. Here is my change:

```
import { ClipboardService } from 'ag-grid-enterprise/main';

/**
 * This is a hack unless 
 * https://github.com/ceolter/ag-grid/issues/1122
 * got fixed.
 */
(<any>ClipboardService).prototype.executeOnTempElement = function (callbackNow, callbackAfter) {
  var eTempInput = document.createElement('textarea');
  eTempInput.style.width = '1px';
  eTempInput.style.height = '1px';
  eTempInput.style.top = '0px';
  eTempInput.style.left = '0px';
  eTempInput.style.position = 'absolute';
  eTempInput.style.opacity = '0.0';
  var guiRoot = this.gridCore.getRootGui();
  guiRoot.appendChild(eTempInput);
  try {
    var result = callbackNow(eTempInput);
    this.logger.log('Clipboard operation result: ' + result);
  }
  catch (err) {
    this.logger.log('Browser doesn\t support document.execComment(\'copy\') for clipboard operations');
  }
  if (callbackAfter) {
    setTimeout(function () {
      callbackAfter(eTempInput);
      guiRoot.removeChild(eTempInput);
    }, 10);
  }
  else {
    guiRoot.removeChild(eTempInput);
  }
};
```
This also fixes the focus loss when copying 'selected range'

Hope this is helpful.

**Comment by seanlandsman** [comment]
tracked by AG-138
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
We haven't heard about this in a long time, and we can't reproduce this anymore, so closing it
