### ISSUE TITLE
[typings] Typescript definition for callback event parameters. 

### ISSUE THREAD

**Issue by daric81** [ag-grid/ag-grid#1132]
Hi
Was wondering if there are any plans to further thrash out ag-grid's type definitions.  Where possible I'm extending ag-grid's interfaces to suit my needs and get new interface member as ag-grid grows.  However there aren't types for event callbacks.

i.e  **onCellDoubleClicked?(event?: any): void** from gridOptions.d.ts.

The params object is created via **RenderedCell.prototype.createParams** so it could in be typed.

**Comment by ceolter** [comment]
we are always adding types as we go, out goal would be to type everything. i was going to just add a type for you for this instance, however it's an event, i need to spend some time and come up with a strategy for typing the events.

**Comment by seanlandsman** [comment]
tracked by AG-139
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
You should find all the documentation for the events here now.

**Comment by makinggoodsoftware** [comment]
https://www.ag-grid.com/javascript-grid-events/?framework=javascript#gsc.tab=0
