### ISSUE TITLE
[virtual paginatoin] getRows() called many times with VirtualScrolling

### ISSUE THREAD

**Issue by don-bluelinegrid** [ag-grid/ag-grid#1151]
@ceolter 

I've implemented a grid with remote data and virtual scrolling, in an Aurelia project.  For the most part it is working, functionally, however I'm see some odd behavior regarding calls to getRows().

When I initialize the grid, I use this code:

```
    let gridOptions = {
        columnDefs: this.gridColumns,
        // rowData: this.selectedCommunityMembers,
        rowSelection: 'multiple',
      //  rowHeight: 25,
        // pageSize: this.pageSize,
        paginationPageSize: this.pageSize,
        enableServerSideSorting: true,
        enableServerSideFilter: true,
        enableColResize: true,
        debug: false,
        rowModelType: 'virtual',
        virtualPaging: true,
        datasource: this.gridDataSource,
        getRowNodeId: function(item) {
          return item.memberId.toString();
        }

- - - -

  setGridDataSource(me) {
        me.gridDataSource = {
            /** If you know up front how many rows are in the dataset, set it here. Otherwise leave blank.*/
            rowCount: null,
            paginationPageSize: me.pageSize,
            //  paginationOverflowSize: 1,
             maxConcurrentDatasourceRequests: 2,
            //  maxPagesInPaginationCache: 2,
            loading: false,

            /** Callback the grid calls that you implement to fetch rows from the server. See below for params.*/
            getRows: function(params: ag.IGetRowsParams) {
               me.gridOptions.api.showLoadingOverlay();
              if(!this.loading) {
                console.debug("..... Loading Grid row | startIndex: " + params.startRow);
                this.loading = true;
                me.membersPromise = me.dataService.getCommunity(me.selectedCmty, params.startRow, me.pageSize);
                me.membersPromise.then(response => response.json())
                  .then(data => {
                    if(me.gridDataSource.rowCount === null) {
                      me.gridDataSource.rowCount = data.totalCount;
                    }
                    params.successCallback(data.responseCollection, data.totalCount-1);
                    me.gridOptions.api.hideOverlay();
                    this.loading = false;
                });
              }
            }
        }
        me.gridOptions.api.setDatasource(me.gridDataSource);
        me.gridOptions.api.sizeColumnsToFit();
  }
```

What I am seeing, is that if I have a dataset with 3000 rows, and pageSize set to 50, and then I quickly drag the scroller from the initial position at the top all the way down to the bottom of the scrollbar, I am getting many calls to getRows() queued up.  This makes for a bad user experience, and causes the loading overlay to flicker on and of with each call.  See the log output below:

```
community-detail.ts:176 ..... Loading Grid row | startIndex: 50
dataService.ts:45 Requesting GET https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=50&page_size=50
dataService.ts:49 Received 200 https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=50&page_size=50
community-detail.ts:176 ..... Loading Grid row | startIndex: 3200
dataService.ts:45 Requesting GET https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=3200&page_size=50
dataService.ts:49 Received 200 https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=3200&page_size=50
community-detail.ts:176 ..... Loading Grid row | startIndex: 3150
dataService.ts:45 Requesting GET https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=3150&page_size=50
dataService.ts:49 Received 200 https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=3150&page_size=50
community-detail.ts:176 ..... Loading Grid row | startIndex: 2950
dataService.ts:45 Requesting GET https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=2950&page_size=50
dataService.ts:49 Received 200 https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=2950&page_size=50
community-detail.ts:176 ..... Loading Grid row | startIndex: 2900
dataService.ts:45 Requesting GET https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=2900&page_size=50
dataService.ts:49 Received 200 https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=2900&page_size=50
community-detail.ts:176 ..... Loading Grid row | startIndex: 150
dataService.ts:45 Requesting GET https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=150&page_size=50
dataService.ts:49 Received 200 https://scig-dev.bluelinegrid.com/v1/communities/44097103-af18-42b0-af1a-624a4b13ca6e/members?start_index=150&page_size=50
```

I would have expected that getRows() would be called only when scrolling ends - either the user stops scrolling for some interval or releases the mouse.  this way, the data call is made only for the data that would need to be visible.  But, from what I'm seeing there are additional intermediate calls being made, before scrolling ends.

If you take a look at my code, I've also put in some checks to set a 'loading' boolean state variable, to prevent calls to getRows() from executing before a previous call has resolved.

Can you provide some explanation for what I'm seeing, and let me know if this is behavior as designed?  If so, can you provide some advice about how to achieve a desirable user experience for this case?

Thanks,
Don

**Comment by don-bluelinegrid** [comment]
Also, I am seeing this while scrolling through the grid using a mouse wheel (Mac touch scrolling):

```
Handling of 'mousewheel' input event was delayed for 197 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.
```

**Comment by don-bluelinegrid** [comment]
@ceolter 

Niall -

Any thoughts on this one?

This is in the virtual scrolling, and it causes a user experience that looks like a loop/cycle of queued events, and the suer doesn't know what's happening or why the grid rows are empty.

Thanks,
Don

**Comment by ceolter** [comment]
i understand. i've added this to my list of things to fix. but it will be a few weeks as i'm not going to be available for the next three weeks approx (my wedding, honeymoomn, and then a conference).

in the mean time, you can set maxPagesInCache=2, this will limit the number of pages it tries to load. so if you scroll down, it will end up loading the last two and non others.

**Comment by don-bluelinegrid** [comment]
@ceolter 

Niall,

Thank for the response.

In the meantime since filing the issue, I had actually already added ```maxPagesInCache: 2```.  With this though, it helps, but I still see three requests being made at the end of scrolling - not just two.  That may be something to take a look at also.

Good luck with your events!

Don

**Comment by ceolter** [comment]
good your not stuck, lowers the priority. but i do want to fix it, it's not good.

**Comment by Wingie** [comment]
+1

**Comment by hassandad** [comment]
+1

**Comment by ceolter** [comment]
tracked by AG-142
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by riteshwaghela** [comment]
Any update on this? Not only during scroll, but if you have server side sorting in place that time also it makes multiple requests.

**Comment by paritosh64ce** [comment]
@riteshwaghela +1
it has been almost a year!

>  if I have a dataset with 3000 rows, and pageSize set to 50, and then I quickly drag the scroller from the initial position at the top all the way down to the bottom of the scrollbar, I am getting many calls to getRows() queued up
Can we somehow intercept the scroll event and make it load after 500 ms or something like that as `debounceTime` in rxjs

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by jayrungta** [comment]
Any update on this?

**Comment by erickbrenesLT** [comment]
Looks like this is still in the backlog - any updates on when we can expect this to be fixed!

**Comment by burgalon** [comment]
for me the problem was domLayout="autoHeight"

**Comment by Vishnu407** [comment]
Any update on this issue???
I am facing the same issue in Infinite scrolling. getRows is getting called 3 times, so the column fields from params are getting updated for the third time. 

for example:
the first and the second time the field is: chk_id
the third time the field is updated as chk_id_1

Any workaround for this?

**Comment by mdama** [comment]
Any update?

I am facing the problem of infinite calls of getRows method for the grid https://www.ag-grid.com/javascript-grid-infinite-scrolling/#example-sorting-filtering-and-selection.

**Comment by alexbrtsv** [comment]
faced with the same problem
fixed using **[rowBuffer]="0"**
maybe it will help someone)

example

<ag-grid-angular
        style="width: 100%; height: 100%"
        class="ag-theme-alpine"
        [rowBuffer]="0"
        [columnDefs]="columnDefs"
        [animateRows]="animateRows"
        [paginationAutoPageSize]="true"
        [rowModelType]="rowModelType"
        [multiSortKey]="multiSortKey"
        [cacheBlockSize]="cacheBlockSize"
        (gridReady)="onGridReady($event)"
        (cellClicked)="onCellAction($event)"
        (cellKeyDown)="onCellAction($event)"
        (sortChanged)="onSortChanged($event)">
</ag-grid-angular>

**Comment by isurujayasighe** [comment]
add cacheBlockSize = 100

**Comment by boldwade** [comment]
> I have server side pagination and on sort change the 'getRows' method is called twice. Would like to hear anything about the progress on this issue

@ryzom2008, I have the exact same issue... were you able to find out how to fix it?
