### ISSUE TITLE
[popup] Close Filter Panel

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1195]
I've a custom Filter Panel, is there a posibility to close the Filter Panel via a Button Click in my custom filter panel?

**Comment by ceolter** [comment]
no, no way to do this. it's part of the menu, and the filter doesn't have access to the menu.

i'll add an api for closing the menu - it's on my list.

**Comment by jogibear9988** [comment]
any news?

**Comment by ceolter** [comment]
afraid not, haven't gotten to it.

**Comment by jogibear9988** [comment]
Would it be okay if I create a pull request for this?

**Comment by ceolter** [comment]
tracked by AG-144
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by SlimenTN** [comment]
Hi !
any updates about this topic ?!
I can't find a way to close the filter panel by clicking on a button.
