### ISSUE TITLE
[touch] Cell doubleclick does not work on iphone/ipad

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1201]
On IPhone/IPad a doubleclick zooms in and does invoke the doubleclick callback.

**Comment by harishgadiya** [comment]
By default mobile Safari does not support the javascript doubleclick event. It's interpreted by Safari as a "zoom".

```
var agent = navigator.userAgent.toLowerCase();
if(agent.indexOf('iphone') >= 0 || agent.indexOf('ipad') >= 0){
       // implement double-tap
} else{
       // implement double click
}
```

And you can also add viewport meta tag in your html file inside the head tag. It will prevent user to zoom in or out the page
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">

**Comment by jogibear9988** [comment]
the meta tag does not work. and i want a cell doubleclick, so i think it needs to be implemented in aggrid?

**Comment by ceolter** [comment]
thanks, i've added this to my list for next time i do a pass on touch devices. i see what you mean, you can't enter edit mode.

**Comment by ceolter** [comment]
tracked by AG-146
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by Keki91** [comment]
Don't suppose there's an estimated release date for this feature?

**Comment by R4DIC4L** [comment]
This issue doesn't appear in the pipeline anymore. Has it been dropped?

**Comment by makinggoodsoftware** [comment]
Released in v15.0

**Comment by GeorgeKnap** [comment]
Double tap doesn't work on iPhone in version 19. Why is this closed as resolved?

**Comment by ratheeps** [comment]
Row double tap doesn't work on iPod in Safari, Please reopen this issue.

**Comment by codemonkey047** [comment]
Row double tap was not working, so I switched to cell double tap. It had all of the event information I needed, but it would be great to fix the row double tap as well.
