### ISSUE TITLE
[component header] headerCellTemplate memory leak and loss of state when using React component

### ISSUE THREAD

**Issue by edoloughlin** [ag-grid/ag-grid#1208]
I'm using a React component as a headerCellTemplate to manage custom sorting and filtering. If I scroll right/left and then back, then
- ag-grid creates new React components for the headers that were out of view (_constructor_ and _componentWillMount_ are called).
- The existing components aren't unmounted or destroyed.

The effect of this is:
- Any custom filter/sort on headers that have scrolled out of view is lost. The grid data doesn't change but the headers 'forget' what's applied.
- The page leaks memory, as the old components are still in the DOM.

**Comment by ceolter** [comment]
we don't directly support components inside the headers - this is a gap in our features that we plan to address before 2016 runs out. when we get this fixed, then we will be supporting React (and Angular and Aurelia) components in the header, which will support the full lifecycle and allow you to dispose of your component.

**Comment by ceolter** [comment]
tracked by AG-147
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
