### ISSUE TITLE
[scroll pagination] Feature Request: Scroll to top on page change

### ISSUE THREAD

**Issue by OverloadScorpion** [ag-grid/ag-grid#1218]
The grid should scroll first row into view when the page is changed in pagination row model type. This will not only allow clarity to the end user, but provide an assurance regarding the grid's functioning as well.

**Comment by ceolter** [comment]
fair point. noted. have taken note and will implement when we refactor the pagination - which we plan to do in the coming weeks.

**Comment by ceolter** [comment]
tracked by AG-149
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by minipai** [comment]
👍

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
