### ISSUE TITLE
[select editor] allow providing keys and values to selectCellEditor

### ISSUE THREAD

**Issue by feloy** [ag-grid/ag-grid#1228]
When using a 'select' cellEditor, we have to pass the values this way:

```
colDef.cellEditor = 'select';
colDef.cellEditorParams = {
    values: ['English', 'Spanish']
}
```

and select is written:

```
<select>
<option value="English">English</option>
<option value="Spanish">Spanish</option>
</select>
```

It could be useful to be able to pass values this way:

```
colDef.cellEditor = 'select';
colDef.cellEditorParams = {
    valuesKeys:  { valueKey: 'id', contentKey: 'name' },
    values: [{ id: 1, name: 'English' }, { id: 2, name: 'Spanish' } ]
}
```

to get:

```
<select>
<option value="1">English</option>
<option value="2">Spanish</option>
</select>
```

and that the callback 'onCellValueChanged' pass the value 1 or 2 as newValue (instead of the text value).

**Comment by ceolter** [comment]
have you looked at the rich select? (or are you not using ag-Grid Enterprise?)

**Comment by actimeo** [comment]
We are trying to use ag-grid for an open-source project (https://github.com/actimeo/simmage-ui) and so cannot use Enterprise functionalities.

**Comment by ceolter** [comment]
will leave as a request, but cannot give ETA at the moment, as our work stack is full right now.

**Comment by actimeo** [comment]
Thanks. Could it help if we provide a PR?

**Comment by ceolter** [comment]
i like to think these things properly through, so a PR won't move things much quicker.

i have added it just now to my external list, so it is on my work stack, ETA is approx 4 weeks (just an estimate, not a guarantee)

**Comment by ceolter** [comment]
tracked by AG-152
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by linuradu** [comment]
Hello, is this feature already implemented or is still on the waiting list?

**Comment by linuradu** [comment]
Does anyone why `cellRenderer` inside `cellEditorParams` or 
`cellRendererParams` does not work for `cellEditor: 'select'`?

I'm using ag-grid free version.
Is this a known bug? 

@ceolter  Do you have any idea?

**Comment by linuradu** [comment]
Hi again,

Finally I found a a workaround to get `'select'` working with `key` and `value`.

```
          var colorsNames : string[] = [];
          colors.forEach(color=> {
            colorsNames.push(color.name);
          })

          {
            headerName: "Color",
            field: "colorId",
            width: 150,
            editable: true,
            cellEditor: 'select',
            cellRenderer: function (data: any) {
              var color = colors.find(color => color.id == data.value || color.name == data.value);
              return color.name;
            },
            onCellValueChanged: function (data: any) {
              /**
               * because 'select' does not offer us the possibility to use 'key-value' as traditional,
               * we will use only values in 'select' and changed to 'id' when will be saved.
               */
              var serviceTypeName = data.data.serviceTypeId;
              data.data.serviceTypeId = serviceTypes.find(serviceType => serviceType.name == serviceTypeName).id;
            },
            cellEditorParams: {
              values: colorsNames
            }
          },
```

The idea is that inside 'select params' we will give only strings and we will try to find the 'id' of object based on the 'name'. Important is that we agreed that 'name' is unique field.

**Comment by mouradmamassi** [comment]
I found a solution in https://www.ag-grid.com/javascript-grid-reference-data/?framework=angular#gsc.tab=0

i create my array:

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by slorion** [comment]
For anyone finding this issue because this simple problem does not yet have a simple answer, here is a generic solution that allows specifying the mappings in the column definition:

```javascript
{
    headerName: "Language", 
    field: "cultureCode", 
    cellEditor: "agSelectCellEditor", 
    mappings: { 
        "en": "English",
        "fr": "French" 
    }
}
```

```javascript
gridOptions.columnDefs.forEach(
    column => {
        if (column.mappings) {
            column.cellEditorParams = {
	        values: Object.keys(column.mappings)
            };
            column.refData = column.mappings;
        }
    });
```

**Comment by invious** [comment]
Is this still not implemented?

**Comment by namrastanov** [comment]
Could be used [custom cellEditor components](https://www.ag-grid.com/javascript-grid-cell-editing/#example-datepicker-cell-editing)

**Comment by Florinstruct** [comment]
8 years later it's probably safe to say they are not gonna implement this for free users.

**Comment by supernyv** [comment]
Any news on this issue please?

**Comment by supernyv** [comment]
> tracked by AG-152 https://www.ag-grid.com/ag-grid-pipeline/

Hi @ceolter, I was unable to find AG-152 on the directed page.

Notheless, while looking for a solution, I came across this section of documentation that seems to deal with the issue but it uses a random function (extractKeys) that is not defined anywhere: https://www.ag-grid.com/javascript-data-grid/reference-data/#using-the-refdata-property

Could you please elaborate on it? I'm using Dash Ag Grid (Python)

**Comment by supernyv** [comment]
Never mind, the solution was right there, the custom function is exactly what it is, a custom function. So I defined one.
For anyone in the same situation, here is the code:

```py3
completions_map = {1:"wellcompletion X", 2:"wellcompletion Y", 3:"wellcompletion Z"}

def extract_keys(input_dict):
    return list(input_dict.keys())

grid_cols = [
    {
        "headerName": "Wellcompletion",
        "field": "id_wellcompletion",
        "cellEditor": "agSelectCellEditor",
        "cellEditorParams": {
            "values": extract_keys(completions_map)
            },
            "refData": completions_map
    }
]
