### ISSUE TITLE
[misc] Excel like Edit features

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1257]
Are some Excel like Editing features planned? like in https://handsontable.com

**Comment by ceolter** [comment]
can you be more specific? we already allow editing like excel (and handson table) i thought

**Comment by jogibear9988** [comment]
In Excel (and Handson Table), you can pull a row in the lower right corner, to overwrite values from other cells.

And maybe introduce a new row, to add data to the grid (with a callback, cause it should also work with virtual rows)

**Comment by ceolter** [comment]
insert and remove rows from the context menu? that's interesting.

```you can pull a row in the lower right corner, to overwrite values from other cells```
i never knew that. that would be tricky to implement, which makes me wonder, is it worth the effort. ie how many people would actually use this, if it takes use 2 weeks to implement, i'm thinking we would be better off implementing something else.

btw - you can copy down using ctrl+d. if we also implemented ctrl+r for copy right, then you would have everything you need right?

**Comment by SoyYoRafa** [comment]
> i never knew that. that would be tricky to implement, which makes me wonder, is it worth the effort. ie how many people would actually use this, if it takes use 2 weeks to implement, i'm thinking we would be better off implementing something else.

My team's users would be very interested in this but I agree that there is better things to do in 2 weeks. As an enterprise client, and sorry for the pivot, I would like to see more stability via unit tests. It's impressive the growth this year but the growth is concerning without any automated/regression testing.

**Comment by ceolter** [comment]
noted re unit tests.

**Comment by ceolter** [comment]
tracked by AG-155
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
