### ISSUE TITLE
[navigation] Suggestion: Allow any key for navigation (not just tab)

### ISSUE THREAD

**Issue by buddyp450** [ag-grid/ag-grid#1288]
Currently it seems as though there's a lot of cohesion between the enter key press and tab key press to the lifecycle of the cellEditors/cellRenderers. It would be nice if those keys could be subbed out for other keys easily.

**Comment by ceolter** [comment]
can you give example? do you mean, you could potentially want 'x' key to move to the next or previous cell?

btw, we've just implemented api.tabToNextCell() and api.tabToPreviousCell(), so you could call these if you want (these will be in next release)

**Comment by buddyp450** [comment]
Precisely, 'x' to move to next cell - or previous cell if shift is held similar to tab.

The issue with the api calls is still the issue I posted on SO about not being able to plug into those events without the existing renderedCell navigation usurping the events from inside the editors.

**Comment by ceolter** [comment]
so if i add option to 'suppressTabNavigation' and 'suppressKeyboardNavigation' then what you want will work?

**Comment by elondon** [comment]
+1 for suppressTabNavigation - that would be useful for me as well. Is there any way to disable tab navigation in the current release? I have kind of an odd requirement where I have a cell and an edit triggers a data update from the server and adjacent cells may be updated. I don't want the user to tab into the editor of the next cell before the update is applied. With enter and up/down arrow, the cell is committed and edit mode ends. That is ideal for me.

**Comment by buddyp450** [comment]
@elondon https://github.com/buddyp450/ag-grid/tree/enter-key-press

**Comment by elondon** [comment]
@buddyp450 Thanks for this. I was able to achieve what I needed.

@ceolter I think suppressTabNavigation would be useful to a lot of us - or perhaps a way to override or define your own behavior for the built in navigation keys. In Excel, tab commits a cell and moves to the adjacent cell but does not enter the editor.

**Comment by ceolter** [comment]
these methods might help:

api.tabToNextCell();
api.tabToPreviousCell();

**Comment by ceolter** [comment]
tracked by AG-159
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by nikolasleblanc** [comment]
`suppressKeyboardNavigation` and `suppressTabNavigation` would both be very valuable. More valuable would be a way to override ag-grid's default keypress/keydown responses to enable the grid keyboard navigation options described here: https://www.w3.org/TR/2009/WD-wai-aria-practices-20090224/#grid.

According to this document, "End" should select the cell at the end of the row, "Home" should select the cell at the beginning of the row, and "Tab" should have no cell-navigation concerns at all, it should just move a user from a cell in the grid into the next tab-able element in the dom outline.

If we could override the default behaviour of these events, or suppress them entirely, we could setup keyboard nav according to whatever spec we're following. For those trying to do the same, I've found a way to override ag-grid's default behaviour - warning, it's not pretty:

```
document.documentElement.addEventListener(
  'keydown',
  (e: KeyboardEvent) => {
    if (this.el.nativeElement.contains(e.target)) {
      if (e.key === 'Tab' || e.key === 'Home' || e.key === 'End') {
        e.stopImmediatePropagation();
        e.stopPropagation();
      }
      if (e.key === 'Home' || e.key === 'End') {
        // we don't want to prevent the default tab behaviour
        e.preventDefault();
      }
    }
  },
  true
);
```

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
