### ISSUE TITLE
[editing floating] api.startEditingCell() does not allow for targeting cells in floating rows

### ISSUE THREAD

**Issue by jkuhs** [ag-grid/ag-grid#1326]
There doesn't seem to be a way to programmatically start editing a cell in a floating row. I would expect `api.startEditingCell()` to take a parameter to allow for that. 

Maybe add a `floating` field to `StartEditingCellParams` and handle it in the same way as for `setFocusedCell(rowIndex, colKey, floating)`?

Or is there another way?

**Comment by ceolter** [comment]
noted. will add this to our list. thanks.

**Comment by jkuhs** [comment]
Is there a workaround for this by any chance?

**Comment by hpeikari** [comment]
@jkuhs @ceolter @majoshi1
Looks like there is a bug in ag-grid library.
Take a look at GridApi.prototype.startEditingCell() in file dist/lib/gridApi.js
"floating" is hardcoded to null !!  
var gridCellDef = { rowIndex: params.rowIndex, floating: null, column: column };

![bug](https://user-images.githubusercontent.com/25368501/32744644-39a4abc8-c87e-11e7-9ca9-0d75cf670228.PNG)

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
