### ISSUE TITLE
[model new] Allow API call to purge/refresh SPECIFIC virtual page

### ISSUE THREAD

**Issue by nkoterba** [ag-grid/ag-grid#1347]
The current API has two method calls to "manage" the virtual page cache:

> • API refreshVirtualPageCache()
> 
> Marks all the currently loaded page caches for reload. If you have 10 pages in the cache, all 10 will
> be marked for reload. The old data will continue to be displayed until the new data is loaded.
> 
> • API purgeVirtualPageCache()
> 
> Purges the cache. The grid is then told to refresh. Only the pages required to display the current 
> data on screen are fetched (typically no more than two). The grid will display nothing while the 
> new pages are loaded. Use this to immediately remove the old data from the user.

In our custom Datasource/`getRows` function we need to invalidate only **one** page of our virtual cache, not the entire cache.  It would be nice to pass a *row number* into a method and if that page is loaded, it's either marked dirty for re-fetch or possibly removed completely so it will be fetched anew the next time the Javascript requests that page.

**Comment by nkoterba** [comment]
As a follow-up this is especially useful if a single page request fails.  If you call `failCallback()` the page is marked as failed and is never re-fetched unless the developer calls one of the two API methods above.  But why invalidate all my caches if only one page fails?

Currently, it appears the `checkPageToLoad` in the `VirtualPageCache` only finds pages to load that are marked "dirty", not "dirty" or "failed".

**Comment by ceolter** [comment]
noted. thanks. 

we do plan a revamp of this area, so will consider this along with a few other changes when doing so.

in the mean time, you could hack it (not supported obviously, at your own risk),

```
// set the page dirty (page 0 in the example)
gridOptions.api.virtualPageRowModel.virtualPageCache.pages[0].setDirty();

// get the grid to reload dirty pages
gridOptions.api.virtualPageRowModel.virtualPageCache.checkPageToLoad();
}
```

if using typescript, these methods are hidden in private variables, so will need to cast to 'any' to access

**Comment by ceolter** [comment]
tracked by AG-161
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by blemaire** [comment]
Not perfect but the below behavew fairly well in most cases:
```js
grid.api.addEventListener('viewportChanged', function (event) {
    var cache = event.api.infinitePageRowModel.infiniteCache;
    
    ['firstRow', 'lastRow'].forEach(function (rowField) {
        // This is extracted directly from the source code and may need adjusting overtime
        var blockId = Math.floor(event[rowField] / cache.cacheParams.blockSize);

        // The block should always exist as the event is fired at the end of the viewport change
        var block = cache.getBlock(blockId);

        if (block.state === 'failed') {
            block.load();
        }
    });
});
```
