### ISSUE TITLE
[scrolling] Scrolling in Pinned Area isn't propagated to body

### ISSUE THREAD

**Issue by jrmoser** [ag-grid/ag-grid#1349]
When scrolling on a pinned area and reaching either the top of the rows or the bottom, I would expect the scroll to then be propagated to the parent. This is the behavior when in the rest of the area of the grid but not when in a pinned area of the grid. This can be viewed on any ag-grid examples on the main website.

**Comment by ceolter** [comment]
cannot reproduce - when i pin (left and right) the main demo in Chrome, i can scroll the pinned areas. either using the scroll bar (right pinned only) or the mouse wheel (both).

**Comment by jrmoser** [comment]
Perhaps you misunderstand. On your documentation sure you have some pages that have a paragraph then a grid then another paragraph. If my mouse is in the pinned area of the grid and I have scrolled to the bottom rows of the grid, it will not propagate the scroll action the the HTML page to scroll to the following paragraph. However if the mouse is in a non pinned area it will.

**Comment by ceolter** [comment]
ok i understand now. when the grid is fully scrolled down, then the event should be allowed propagate to the body. reopening.

**Comment by ceolter** [comment]
tracked by AG-163

**Comment by makinggoodsoftware** [comment]
Can't reproduce in our end anymore so we assume it has been fixed
