### ISSUE TITLE
[clipboard] Copy selected range cannot properly handle text with quotes

### ISSUE THREAD

**Issue by xwb1989** [ag-grid/ag-grid#1354]
Copy a cell with the text:
```
"John Doe"
```

and paste to another cell, result:
```
John Doe
```

Copy a cell with the text:
```
"John " Doe
```

and paste to another cell, result:
```
John
```

etc.

**Comment by ceolter** [comment]
noted. thanks.

**Comment by ceolter** [comment]
tracked by AG-164
https://ag-grid.atlassian.net/browse/AG-164

**Comment by voyti** [comment]
Also stumbled upon this. It seems to be a problem with the RegExp used to parse CSV data upon paste: https://regex101.com/r/auWzYs/1 
Maybe a simple pre-processing should be performed before parse to determine if the data is a candidate to be in CSV format at all

**Comment by makinggoodsoftware** [comment]
Rejected
