### ISSUE TITLE
[client testing] Jest snapshot testing is not supported

### ISSUE THREAD

**Issue by nyccyn** [ag-grid/ag-grid#1356]
Hi,
I'm trying to test a React's component containing ag-grid using Jest snapshot testing and it gives me 'Uncaught Invariant Violation: getNodeFromInstance: Invalid argument.'
I find out that it is probably caused because ag-grid is using ReactDOM.findDOMNode(this).
https://github.com/facebook/react/issues/7371

**Comment by ceolter** [comment]
this should really be in ag-grid-react project

**Comment by ceolter** [comment]
tracked by AG-165
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by ssilve1989** [comment]
@ceolter I don't see AG-165 in the pipeline. Has it been completed?
