### ISSUE TITLE
[component pagination] Material design is not applied to Pagination buttons

### ISSUE THREAD

**Issue by naveenballa** [ag-grid/ag-grid#1370]
Hi,
When i apply material theme to the ag-grid, the pagination buttons appear to be default not as per material design.
Reference link: https://material.angular.io/components/component/button

**Comment by ceolter** [comment]
thanks for raising. added to our list. however we also have a refactor of the pagination panel planned where we will be looking to allow full customisation of the pagination panel.

**Comment by ceolter** [comment]
tracked by AG-167
https://ag-grid.atlassian.net/browse/AG-167

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
