### ISSUE TITLE
[misc] Undo functionality

### ISSUE THREAD

**Issue by mbacon-edocs** [ag-grid/ag-grid#1381]
Undo/redo (some sort of action history management) would be a great addition to this library. While it shouldn't be too big a job for us to write a custom implementation when we get around to wanting it, I think most people will expect it when trying out this grid.

**Comment by ceolter** [comment]
tracked by AG-169
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by cjtafoya** [comment]
+1 fwiw :)

**Comment by KrKandula** [comment]
Any estimation date on when this might be available ? Thank you.

**Comment by valerieferrer** [comment]
Could you please tell me if the undo feature is planned for the next or a future version of AG-Grid? 
If present in your backlog, could you please tell me when it will be available and if not, could you provide some inputs on how to implement it?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by Agendra** [comment]
Has the Undo/Reset changes feature added to this library ??

**Comment by PaulPCIO** [comment]
It seems like undo has been removed, did a search for 'undoCellEditing' with no hits, also see that the docs page has been removed;
![image](https://user-images.githubusercontent.com/39598117/69785448-5d963080-11b8-11ea-9747-d1f7472c9c57.png)
![image](https://user-images.githubusercontent.com/39598117/69785461-66870200-11b8-11ea-9422-dc1a25e1a138.png)
@makinggoodsoftware can you maybe confirm any of this? is there any other functionality that replaced this?
