### ISSUE TITLE
[sort] setSortMode() calls sort changed event on init phase

### ISSUE THREAD

**Issue by doganmurat** [ag-grid/ag-grid#1389]
Hi,

While initializing if you call api.setFilterModel() this will not call filter modified event.
But if you call api.setSortMode() it calls sort changed event.

Calling change event causes re-render which should not be.

I am using React. Here is the code.

```
  onGridReady(params) {
    this.api = params.api;
    this.api.sizeColumnsToFit();
    this.api.setFilterModel(this.props.grid.dataFilter);
    if (this.props.grid.dataOrder && this.props.grid.dataOrder.length > 0)
      this.api.setSortModel(this.props.grid.dataOrder);
    }
```

**Comment by ceolter** [comment]
tracked by AG-170
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Won't do, adds too much complexity
