### ISSUE TITLE
[header template] DOMException when unpinning a column

### ISSUE THREAD

**Issue by ocrlopez** [ag-grid/ag-grid#1423]
When using custom headers by specifying a headerCellTemplate in a colDef, if you pin a column and then unpin it by dragging it out of the pinned area, the following occurs:

> headerRowComp.js:59 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

However, this doesn't occur when using gridOptions.getHeaderCellTemplate.

It is reproducible in the example ag-grid-react project using the default header cell template provided in the documentation:
```html
<div class="ag-header-cell">
    <div id="agResizeBar" class="ag-header-cell-resize"></div>
    <span id="agMenu" class="ag-header-icon ag-header-cell-menu-button"></span>
    <div id="agHeaderCellLabel" class="ag-header-cell-label">
        <span id="agSortAsc" class="ag-header-icon ag-sort-ascending-icon"></span>
        <span id="agSortDesc" class="ag-header-icon ag-sort-descending-icon"></span>
        <span id="agNoSort" class="ag-header-icon ag-sort-none-icon"></span>
        <span id="agFilter" class="ag-header-icon ag-filter-icon"></span>
        <span id="agText" class="ag-header-cell-text"></span>
    </div>
</div>
```

**Comment by ceolter** [comment]
tracked by AG-174
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
This seems to be fixed now
