### ISSUE TITLE
Backlog (ag-grid-pipeline) is showing Feature requests for clear bugs

### ISSUE THREAD

**Issue by AmitMY** [ag-grid/ag-grid#1438]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When viewing the backlog on https://www.ag-grid.com/ag-grid-pipeline/, everything is listed as features, while some items seem like actual bugs.

Example for items that look like bugs:
AG-178, 111. 109, 95, 89, 88, 87, 85, 84, 82, 73, 72?, 67. 66 etc...

EDIT: 111, 85, 67, 66

Note:
69 seems to include 81, so it may be a single feature? not sure.

**Expected behavior**
For it to say "BUG"

**What is the motivation / use case for changing the behavior?**
Before reporting a bug a user can look at the backlog and see if it's already there.

* Note - It is pretty funny that the ag-grid website shows a normal table, and not an ag-grid table. Would be nice to be able to filter/sort columns (basically to separate features from bugs, and update/creation dates sorting)

**Comment by ceolter** [comment]
Baby steps Amit, this is still work in progress!!!

**Comment by AmitMY** [comment]
Yeah I know, just wanted to save you doing stuff twice...

**Comment by AmitMY** [comment]
Also, mobile support - 
![image](https://cloud.githubusercontent.com/assets/5757359/22396359/4cce1a1a-e560-11e6-9b40-6d6b44afd666.png)

**Comment by AmitMY** [comment]
Status for this issue? It seems to be partially changed (some of the stated features were changed to bugs), but not fully.

**Comment by makinggoodsoftware** [comment]
This should be fixed now in the new pipeline

**Comment by AmitMY** [comment]
@makinggoodsoftware Not really, no
