### ISSUE TITLE
refreshCells on Floating Rows

### ISSUE THREAD

**Issue by randdusing** [ag-grid/ag-grid#1440]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Calling api.refreshCells() on a floating row doesn't trigger the floatingCellRenderer.

**Expected behavior**
floatingCellRenderer should be called again.

**Minimal reproduction of the problem with instructions**
var rowNode = api.getFloatingBottomRow(0);
api.refreshCells([rowNode], ['selection']);

* **ag-Grid version:** latest

I believe the error is due to iterating this.renderedRows in RowRenderer.prototype.refreshCells(). The floating row isn't in the rendererRows array.

**Comment by seanlandsman** [comment]
Thanks for the feedback - item added to our backlog (https://www.ag-grid.com/ag-grid-pipeline/) as AG-192

**Comment by ceolter** [comment]
i fixed this about two months ago, you will see the latest is now working.
