### ISSUE TITLE
[Feature] Excel look & feel

### ISSUE THREAD

**Issue by AmitMY** [ag-grid/ag-grid#1455]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

In a future release, I would love to see several things:
- an option to add a left-pinned, header-styled column, showing the number of a row (currently achievable using the API and some CSS, but a build in solution would be better)
- an Excel style theme.
- a column selection (currently you can only select rows, not columns)

Both the left-pinned numbers, and the styling, you can see here: https://handsontable.com/examples.html?headers

(Note: the left-pinned thing should of course be available for all themes)

**What is the motivation / use case for changing the behavior?**
Savvy users are already used to how Excel feels, and Microsoft probably already invested all the time & money to perfect it's design to users.

Thoughts?

**Comment by ceolter** [comment]
feature requests accepted. tracked by AG-227 AG-228 AG-229

**Comment by michaelbridge** [comment]
+1 I've implemented a lot of interaction that's consistent with excel.  For instance:

- Control + Arrow moves to end of grid in applicable direction
- Delete key deletes the contents of a cell without entering edit mode
- Tab key advances to next cell without entering edit mode

I recognize these won't be included in the default implementation but just wanted to indicate that others are customizing for Excel-like behavior.

**Comment by chadbr** [comment]
Looking forward to this one -- specifically AG-227 (row numbers / gutters)

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
