### ISSUE TITLE
how to disable the Timezone conversion

### ISSUE THREAD

**Issue by rajgopalk** [ag-grid/ag-grid#1458]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
hi,
   is there any way to stop the timezone conversion.i have checked all the grid properties. but i couldn't found.

**Comment by willhalling** [comment]
Hi rajgopalk, just to clarify, is the timezone conversion in regards to date filters?

**Comment by seanlandsman** [comment]
@rajgopalk - can you please confirm that you're talking about date filters - thanks

**Comment by rajgopalk** [comment]
timezone conversion in my scenario is , if my application is opened in another timezone, it will automatically converted to their timezone. the date time in the grids will vary. normally we are using date method for date related functionalities in column level.
this is my code...
cellRenderer: function (params) {
                var dString = new Date(params.value);
                return '<span>' + dString.toLocaleDateString() + " " + dString.toLocaleTimeString() + '</span>';
}
to overcome that , iam using string [substr(,)] operations like this.
cellRenderer: function (params) {
var input = params.value.toString();
var AuditDTString = input.replace(/[T]/, ' ').replace('-', '/').replace('-', '/');
                var time = AuditDTString.substr(AuditDTString.indexOf(" ") + 1);
                var hours = time.substr(0, 2);
                var minutes = time.substr(3, 2);
                var ampm = hours >= 12 ? 'PM' : 'AM';
                hours = hours % 12;
                hours = hours ? hours : 12; // the hour '0' should be '12'
                minutes = minutes < 10 && minutes != 0 && minutes.length==1? '0' + minutes : minutes;
                var strTime = hours + ':' + minutes + ' ' + ampm;
                return '<span>' + date + '  ' + strTime + '</span>';
}
dont mind about this link, for getting better understanding purpose i put this link,
http://www.telerik.com/forums/disable-automatic-timezone-conversion

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
