### ISSUE TITLE
Sorting: Comparator is not provided with the sort column

### ISSUE THREAD

**Issue by andrewtytula** [ag-grid/ag-grid#1463]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The sort comparator takes in both values, the nodes that they exist in and if the sort is inverted. But I don't know what column was selected.

**Expected behavior**
The sort column is provided to the comparator

**What is the motivation / use case for changing the behavior?**
My table is completely data driven, and the cell values are rendered combining the cell value and column as well as other data in the row. The cell renderer provides all this info so rendering works, but the sort comparator excludes column and the node doesn't contain it. So I don't know how to translate my value for comparison. I looked at getting the sortModel but if multiple columns are sorting, I won't know which is the one I am comparing right now.

* **ag-Grid version:** X.X.X
8.0.0

* **Browser:**
Chrome

* **Language:** Javascript

Looking at the code in ag-grid-enterprise.js there is a one line change that can be done on line 23683 to add the sortOption.column to the comparator function.

**Comment by AmitMY** [comment]
Please note, that if this is a problem with ag-grid-enterprise it is more suited to be opened here: https://github.com/ceolter/ag-grid-enterprise/

You mentioned you were using the cell rendered, which is no real value for a cell. Does your columns have a "field" or a "valueGetter" as well?

**Comment by andrewtytula** [comment]
I can move it to the enterprise github project if that is best but the feature is in the free version too so I figured it might be useful here. The overall issue isn't related to cell rendering. I was just pointing out that cell rendering had all the information I needed, but it is missing in the sort comparator.

The reason I used a cell renderer was because some cells have enumerations. So the value is 1-5 where 1: ValueA 2: ValueB .... Some values also have icons associated to them. The issue though is I need to sort based on ValueA, ValueB, .... not 1-5 which is what the comparator is given. Without knowing what column I am comparing on, I won't know which enumeration to do the lookup on.

**Comment by AmitMY** [comment]
Fair enough.

I am far from sure the following is gonna work, but you should try if you are stuck.
Try using a `valueGetter`. You can inject parameters into the grid, or globally, and do something like:
`valueGetter: "enumeration1[data.value]"`
Where enumeration1 is:
```
{
    1: "val1",
    2: "val1",
    ....
}
```

The reason to use `valueGetter` is that the value you will get will be the result of the getter, and not the 1-5
Doc: https://www.ag-grid.com/javascript-grid-value-getters/#gsc.tab=0

**Comment by andrewtytula** [comment]
Unfortunately the enumerations are't as linear. Each row belongs to a class of data and using a type_id field I can figure out where to go for the enumerations. the valueGetter didn't look like it would take in a function (maybe it does and that would work) which is why I steered away from it. I also need the value in the row to be the raw value so I can use it to do subqueries. The enumeration lookup is solely for the user's benefit. Does the valueGetter change the raw value or is it like columns that can have a headerValue and a field?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
