### ISSUE TITLE
Property to figure out whether the horizontal scrollbar is shown

### ISSUE THREAD

**Issue by maxpfandl** [ag-grid/ag-grid#1466]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a grid with a fexible height and dynamic columns, set through angular2 (no direct jquery, dom-manipulation). If the grid is empty, the "nodata" overlay is shown and the grid gets a fixed size, otherwise the height of the table is set dynamically according to rows up to a maximum.

If the table now has ie. 2 rows, this works fine: but if there is also a horizontal scrollbar shown, I need to adjust the height accordingly: so either one datarow is cut or if there is no horizontal scrollbar, the height of the table doesnt fit the rows shown.

**Expected behavior**
I would like to have a way of telling whether the horizontal scrollbar is shown without manipulating the dom or using jquery direcly (angular2) so I can adjust the height of the table to fit.

**Minimal reproduction of the problem with instructions**
see current behaviour

**What is the motivation / use case for changing the behavior?**
Adjusting the table-height according to the rows shown

**Please tell us about your environment:**
Win10 x64, Visual Studio Code, npm, angular-cli

* **ag-Grid version:** X.X.X
8.0.1

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.5, ES6

**Comment by jathri** [comment]
Perhaps something like gridOptions.api.isHorizontalScrollbarPresent and gridOptions.api.isVerticalScrollbarPresent? Both true or false.
I would also like to have gridOptions.api.getAvailableWidth and gridOptions.api.getAvailableHeight. Which would take into account scrollbar (if present). Like getWidthForSizeColsToFit:
`http://stackoverflow.com/questions/42414625/getting-value-from-getwidthforsizecolstofit`

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
