### ISSUE TITLE
HeaderComponents fail to scroll rows to the correct position

### ISSUE THREAD

**Issue by seanlandsman** [ag-grid/ag-grid#1471]
** Moved from ag-grid-ng2 repo** 

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you're using the new headerComponentFramework and include an input in it, tabbing through the headers doesn't scroll the rows properly and sometimes even fails to render parts of the rows completely.

**Expected behavior**
Tabbing through headers behaves the same as tabbing through a row by scrolling correctly.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/FLmZTqvBI9d8o5OT7jAr?p=preview
Open this plunker, click in the input of the first header and tab twice. The focus should be in the input of the 3rd header but the row didn't scroll. Clicking back into the first header also doesn't scroll the headers back.

**What is the motivation / use case for changing the behavior?**
I'm adding a switch to the grid that enables a configuration mode. By default drag and drop and co are disabled. Enabling this mode enables column drag and drop, changing the width and changing the column headers by swapping them with inputs (or rather changing the header component from default to my custom one) and binding these to the headerName property.

**Please tell us about your environment:**

Windows 7, VSCode 1.9.1, NPM 3.10.6

* **ag-grid-ng2 version:** 8.0.0

* **ag-Grid/ag-Grid-Enterprise version:**8.0.1

* **Angular version:** 2.4.1

* **Browser:** all

* **Language:** TypeScript 2.1.6

**Comment by seanlandsman** [comment]
Moved from ag-grid-ng2 repo - original issue here: https://github.com/ceolter/ag-grid-ng2/issues/127

**Comment by vanslly** [comment]
I am having the same issue. I have a custom header with inputs, and tabbing through them maligns the header with the rest of the grid when setting ` [suppressColumnVirtualisation]="true"` on the grid. When using `[suppressColumnVirtualisation]="false"` you can only tab to the last visible input.

@seanlandsman did you manage to find a workaround?

**Comment by vanslly** [comment]
As an imperfect workaround what I managed to do was to handle <kbd>tab</kbd> and <kbd>shift</kbd> + <kbd>tab</kbd> and for the respective event handlers:

```TypeScript
public onTab() {
    const colIndex = (this.api as any).columnController.gridColumns.indexOf(this.params.column);
    const nextColumn = (this.api as any).columnController.gridColumns[colIndex + 1];

    if (nextColumn) {
        this.api.ensureColumnVisible(nextColumn);
    }
}

public onShiftTab() {
    const colIndex = (this.api as any).columnController.gridColumns.indexOf(this.params.column);
    const prevColumn = (this.api as any).columnController.gridColumns[colIndex - 1];

    if (prevColumn) {
        this.api.ensureColumnVisible(prevColumn);
    }
}
```

This causes the body to scroll when tabbing through the inputs in the custom header component, however the body and header are not perfectly aligned.

**Comment by makinggoodsoftware** [comment]
This should be fixed now
