### ISSUE TITLE
[Feature Request] isPopup support for header components

### ISSUE THREAD

**Issue by seanlandsman** [ag-grid/ag-grid#1472]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**
isPopup has it's drawbacks but it's required to properly show custom components that extend outside of a cell (in this case a typeahead with a potentially long list of options). This same is obviously true for header components. Currently my typeahead in the header gets cut of by the overflow settings of the grid and isPopup would solve that, including other problems/use cases.

* **ag-grid-ng2 version:** 8.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 8.0.1

* **Angular version:** 2.4.1

* **Browser:** [all]

* **Language:** [all]

**Comment by seanlandsman** [comment]
Moved from ng2 repo - original issue here: https://github.com/ceolter/ag-grid-ng2/issues/128

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
