### ISSUE TITLE
Header Checkbox Not Able To Prevent Row Selection

### ISSUE THREAD

**Issue by evangboucher** [ag-grid/ag-grid#1503]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

1. When header checkbox selection is enabled. The row(s) do not have a checkbox selection enabled (IE. via the checkboxSelection: function returning false). No other form of selection (row click) is enabled.

1. Clicking the header checkbox selects all rows including those that do not have a checkbox (IE. cannot normally be selected via a checkbox or mouse click).

**Expected behavior**
When a row does not have checkboxSelection or any form of selection enabled (IE. row click is disabled), then the row should not be selected with the header checkbox. 

This also means that the header checkbox's state should be based on only selectable rows.

**Minimal reproduction of the problem with instructions**
I have created a jsFiddle to demonstrate the issue. [Ag-Grid V8.1.1_Header_Checkbox_Fiddle](https://jsfiddle.net/erzxzg8g/)

1. Notice that the first three rows do not have a checkbox nor any way to select them.

1. Click the header checkbox in the `Athlete` column

1. Notice that all 5 existing rows are now selected, even though there is no way for the user to select or deselect the first 3 rows individually. IE. The first three rows are not selectable.

**What is the motivation / use case for changing the behavior?**
In our application we are displaying thousands of rows, some that are selectable and others that are not. We need a way to select everything (select only filtered in our particular case) without selecting the rows which cannot normally be selected. We also need the state of the header checkbox button to properly display the status. 

**Please tell us about your environment:**
We run on the latest version of mac os x & Ubuntu. packaging the application with `Webpack`. Using the `ag-grid-react` & `ag-grid-enterprise` modules. We also use `Redux.js` for state management.

* **ag-Grid version:** 8.1.1
Latest ag-grid version

* **Browser:**
We currently only test against Chrome (V54 and up). The fiddle above shows this in your local version of Chrome.

* **Language:** ES6 - Babel transpiled

**Things I have tried as workarounds**

1. I have tried to implement a smart form of `onSelectionChanged()` event to simply deselect rows that cannot be selected. However, there is no way to control the header checkbox state. By unselecting a single row, the next click tells the table to reselect all rows. 

1. We have implemented our own checkbox header, which led to state confusion since we are not able to initialize ag-grid's state for row selection. I believe I could make this work if it came down to it, but I would really like ag-grid's feature to work as it is more performant than a React renderer.

I will add more as I continue to hunt down a work around. :) Thanks for the hard work and let me know if I can provide any more details.

**Comment by seanlandsman** [comment]
This issue has been raised as AG-309. You can track its progress in our pipeline (https://www.ag-grid.com/ag-grid-pipeline/) but we’ll also update this thread when actioned.

thanks

**Comment by safeerk** [comment]
Any update on the above.... 
Hopefully it will rectify the below stuff also.

If i have a grid something like this 
![image](https://cloud.githubusercontent.com/assets/22815639/23900461/72b5f666-08ca-11e7-93bb-654013880c90.png)

Where the header checkbox need to select only the checkboxes not the rows... Is there any alternative ways or anything...
Thanks....

**Comment by seanlandsman** [comment]
The only alternative I can suggest is to create a "pseudo" column with a bespoke checkbox cell renderer that does what you need I'm afraid

There is no update on the issue above at this stage

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
