### ISSUE TITLE
Keyboard navigation bug in wide columns

### ISSUE THREAD

**Issue by jathri** [ag-grid/ag-grid#1509]
**I'm submitting a bug report**

**Current behavior**
When I use up and down navigation keys in very wide columns this behaviour occurs: when I press down key for the first time right side (end) of below column is aligned and I cannot see left side (beginning) of column where string starts. Then I press down again and left end is aligned in grid, then I press down again and right end is aligned (as I described above) etc. etc. etc.

**Expected behavior**
Left end of cell (column) is aligned all the time.

**Minimal reproduction of the problem with instructions**
Use gridOptions.columnApi.autoSizeColumn and repeat steps from above.

**Please tell us about your environment:**
W7, Firefox 51.0.1., ag-grid v8.1.0

**Comment by seanlandsman** [comment]
This issue has been raised as AG-311. You can track its progress in our pipeline (https://www.ag-grid.com/ag-grid-pipeline/) but we’ll also update this thread when actioned.

thanks

**Comment by ceolter** [comment]
just fixed this, will be in next release.

**Comment by JohnMasterson** [comment]
Just to confirm that this was included in version 14.0.0 which is now available.

Regards, 

John
