### ISSUE TITLE
Ag-grid row having selectors For each selector autocomplete feature needed....!!!!!

### ISSUE THREAD

**Issue by desamsandeep** [ag-grid/ag-grid#1511]
Hi Folks,

I am using ag_grid for my project .First of all I would like to thank you the ag_grid team for this great features it providing.I have one small question that I have a selector drop down in  the each  row  for some columns.In that I need a search option for each selector and at the same time I need auto complete feature can anyone please anyone help me on this.I got  struck here.

Thanks in advance.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by rkpendyala** [comment]
hi any update on this issue?

**Comment by rush2sankar** [comment]
Hi team....whether this feature is release??
