### ISSUE TITLE
TypeScript - IFilterParams is incorrect

### ISSUE THREAD

**Issue by sbublava** [ag-grid/ag-grid#1519]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

https://www.ag-grid.com/javascript-grid-filtering/ says:

> If you want the user to hit an 'Apply' button before the filter is actioned, 
> add apply=true to the filter parameters. 

This property is missing from IFilterParams (ag-grid/dist/lib/interfaces/iFilter.d.ts).

Ag-Grid 8.2 seems to have added clearButton and applyButton, which are not mentioned in the documentation.

It is also strange / disappointing that ColDef defines filterParams as any instead of IFilterParams.

**Expected behavior**

Documentation and TypeScript interfaces should be in sync.

**Please tell us about your environment:**

WIndows

* **ag-Grid version:** 8.2.0

* **Browser:** IE 11, Firefox 51

* **Language:** TypeScript 2.1.5

**Comment by seanlandsman** [comment]
Hi - I've raised issue AG-322 our side for these, but we'll also update this thread with updated

**Comment by sbublava** [comment]
It seems that the API for "Apply" buttons is inconsistent. Set filters need:

{
    applyButton: true
}

All other filters need:

{
    apply: true
}

**Comment by makinggoodsoftware** [comment]
This should be fixed now
