### ISSUE TITLE
Missing ag-grid in https://www.webcomponents.org/

### ISSUE THREAD

**Issue by AlphaWong** [ag-grid/ag-grid#1520]
Dear Sir,

I am your big fans. Currently, customelements.io has been redirected to webcomponents.org. I cannot search your components any more.

Please add ag-grid to https://www.webcomponents.org/.

Best,
Alpha

**Comment by makinggoodsoftware** [comment]
Thanks for the heads up!

And sorry for the big delay replying, this is now added.

Happy to hear from a fan

;)
