### ISSUE TITLE
Floating filter on master detail grid not working

### ISSUE THREAD

**Issue by jindalit** [ag-grid/ag-grid#1529]
Floating filter on master detail grid not working

**Comment by seanlandsman** [comment]
Raised issue for this our side AG-336, but we'll need to verify first

thanks

**Comment by jindalit** [comment]
Hi seanlandsman ,

Is there any update from your side.
Are your guys able to reproduce this issue.
Please help on same ASAP.

regards,
Mayank Jindal

**Comment by jindalit** [comment]
#1529

Please reproduce

**Comment by makinggoodsoftware** [comment]
This should be fixed now
