### ISSUE TITLE
VirtualPagingRowModel inconsistent and problematic request behavior

### ISSUE THREAD

**Issue by don-bluelinegrid** [ag-grid/ag-grid#1543]
![screen shot 2017-03-22 at 12 03 24 pm](https://cloud.githubusercontent.com/assets/19780097/24207565/9690f008-0ef7-11e7-873a-ca555d83148e.png)
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report 
```

**Current behavior**
With grid rowModelType set to ```virtual``` and with ```paginationPageSize``` set to a value greater than the actual dataset size, grid is making many server requests.  Each time the the grid is scrolled past the viewport boundary, a new request is being generated, even though the complete dataset should have been retrieved in the initial request.  In addition, I frequently see the grid getting into an endless loop of requests and never ending the load process with data displayed.  (See https://github.com/ceolter/ag-grid/issues/554)

**Expected behavior**
With grid rowModelType set to ```virtual``` and with ```paginationPageSize``` set to a value greater than the actual dataset size, the expected behavior would be that the grid makes one initial request for a page that contains all rows of the dataset, with no subsequent requests - since the entire dataset should have been retrieved in the initial server data request.  So, for example, with a viewport that displays 40 rows, and a server request that returns 1000 rows, we would expect to see one request, and then the ability to scroll through viewport "pages" in memory, without any further server requests needed.

**Minimal reproduction of the problem with instructions**

-  Set grid with ```virtual``` rowModelType, ```max-pages-in-cache``` set to zero, and with ```paginationPageSize``` set to a large value, greater than the actual dataset - for example set to ```200,000```.
- After the grid is initialized and is displaying the initial view of data, scroll the viewport; observe that a new server request is generated when the grid is scrolled past the viewport boundary.

**What is the motivation / use case for changing the behavior?**

Avoid making unnecessary and unexpected server data requests.

Also related to AG-142.

**Please tell us about your environment:**
MacOS, Webpack, Typescript, Aurelia.

* **ag-Grid version:** X.X.X
8.1.1

* **Browser:**
Any browser.

* **Language:** TypeScript 2 

[Attachment shows example of multiple/endless loop of server requests.]

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting - issue AG-354 raised our side for this. We'll update this thread with updates as soon as we have any

**Comment by don-bluelinegrid** [comment]
@seanlandsman 

Thanks for the update.

After investigating more on my side, I have some more information.  I was basically reporting two problems above:
1. Setting a large pageSize value, greater than the total resultset size, seemed to have unexpected results and continued to make data requests.

2. Setting certain pageSize values seemed to cause the grid to go into a loop of repeated requests.

Issue 1. was due to developer error.  I was in the midst of a major application refactor, and it turned out that the pageSize value was not being bound as I thought to the Grid element.  Once I resolved that, I did see the expected behavior.

For Issue 2., that seems to be a definite problem, and has been reported previously as I noted above.  Essentially, since my binding wasn't working, the Grid was using its default, which seem to be ```pageSize: 100```, and with that the Grid was going into an infinite loop of making requests with pageSize of 100 and startIndex incrementing by 100, as documented in my screen shot.

Thanks,
Don

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
