### ISSUE TITLE
AutoGroupColumn doesn't support cell renderer framework

### ISSUE THREAD

**Issue by bondib** [ag-grid/ag-grid#1545]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, if I use aurelia ag-grid (or any other framework!) and using my own cell render template for a column which I want to group - when I group the column - it displayed the original data (plain text) instead of using the column's cell template.
(This BTW, is because the groupCellRenderer code only checks if a cellRenderer was deined on the column, instead of looking AS WELL if a cellRendererFramework was defined - before returning the plain data.)

**Expected behavior**
That grouped columns cell renders will correctly display the framework template I defined for that column.

**Minimal reproduction of the problem with instructions**
Define an ag-aurelia grid (or any other framework grid) with a column that has its own cell template (e.g. with red background) and group it.
You will see that when grouped - the plain text data is presented - and not with the red background.

**What is the motivation / use case for changing the behavior?**
THIS IS A BUG.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** 8.2.0

YES - I'm suing latest version.

* **Browser:**
All

* **Language:**
all | TypeScript X.X | ES6/7 | ES5

**Comment by seanlandsman** [comment]
Hi

I've confirmed that this is an issue. I've raised AG-380 our side for this - we'll update this thread as soon as we have any updates

thanks

**Comment by bondib** [comment]
We have a workaround with the pull request I've submitted - which works well - so not very urgent for us.

It would be just nice to have it merged (or a more formal fix) to the main branch instead of us using a fork.

Thanks!

________________________________

**Comment by bondib** [comment]
Any update on this?

**Comment by bondib** [comment]
Auto grouping column (group cell renderer) - still doesn't have a way to work with the framework cell renderer. So this issue (although somewhat fixed in v13.0) - is still open!

Please take a look (again) at https://github.com/ag-grid/ag-grid/pull/1546/commits/368b5b297927d2195b25c4ab0c185cc0787e6d29#diff-295873b31b0cac107a41aebf20739c19

This is what is missing in the code!

**Comment by bondib** [comment]
Never mind :-)
Found what i needed is to use innerRendererFramework in cellRendrereParams....
That works...

**Comment by bondib** [comment]
Yes, it works.
Found it by looking at the group cellrenderer code
________________________________

**Comment by makinggoodsoftware** [comment]
This should be fixed now

**Comment by cimbis** [comment]
What about refresh method of my renderer component? 

When not setting the `cellRenderer: 'agGroupCellRenderer'` and not providing `cellRendererParams` the cells display pure, untouched, raw values. And my custom functionality, of course, is not taken into account.
 
However, when the following is set
```typescript
cellRenderer: 'agGroupCellRenderer',
cellRendererParams: {
    innerRendererFramework: MyRendererComponent
}
```

It doesn't seem to call `refresh()` on my cells renderer, when data is updated on grouped table data. When checking dev tools I can only see `agInit()` being triggered when new data comes in - this, however, is not the case with non-grouped rows.

Any comments regarding this matter? Quite sad that after purchasing license and setting the row grouping one of the core features of my app isn't working.
