### ISSUE TITLE
[Feature request] Custom sort and filter on same popup

### ISSUE THREAD

**Issue by R0hitYadav** [ag-grid/ag-grid#1560]
[Feature request]

I'm trying to implement is a popup (invoked upon clicking column header) with options to sort and filter as well. I did try the API but unfortunately it would only allow me to customize the sort and filter individually.

As a workaround, I've implemented a React component housing both, the sort and filter component. However, the implementation makes it a part of the column header and dragging anywhere on the popup starts moving the column as well. Is there a way to restrict the dragging to the column itself? Or a way to implement the functionality using the API itself

Here's a mockup of the implementation
<img width="324" alt="screen shot 2017-03-30 at 5 04 44 pm" src="https://cloud.githubusercontent.com/assets/2400635/24502714/8fdf3b22-156c-11e7-8b53-b4f890e25cdd.png">

```

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
