### ISSUE TITLE
[FR] Allow to get and set the expand/collapse state of the groups; Keep them in the grid state.

### ISSUE THREAD

**Issue by tomepejo** [ag-grid/ag-grid#1564]
This is a feature request.

Currently there is only event (onRowGroupOpened) when some group is expanded/collapsed. Also the state of the groups is not in the api state object (gridOptions.columnApi.getColumnState()).

It would be great if the expand/collapse state of the groups can be part of the grid state, for better user experience.

**Comment by daxiachonger** [comment]
Agree. I also facing this issue. I create a TreeNode object for each RowNode.data. In TreeNode, it has "open" variable which is the expand/collapse status of each row group specified by ag-grid doc. When expand/collapse row group, the open var in TreeNode is not set automatically. I manually set it to track the expand/collapse status.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by DominicTobias** [comment]
It would be nice if AG stopped hiding state internally entirely. This causes a huge amount of issues such as loosing state across row updates and page changes such as loss of row selection and expansion state. A modern proper grid would be controlled, i.e. the grid says "hey the user wants me to exapand" and the app decides whether to update the state which is passed into the grid. This is called "controlled components" and how any decent modern component is built.

**Comment by csicky** [comment]
@makinggoodsoftware

I understand that you are offering two products, I use the enterprise version of ag grid. However, any problems I have with any component, not just ag grid, I search on Google.
I so much hate it when I find this generic answer and no solution to the problem I search for. All the issues here, as soon as you see enterprise feature you stop updating it with info. All I get is only getting angry on ag grid but no answer how to solve the problem.

> Thanks for your understanding.
ag-Grid Team.

Understanding but not liking the way you deal with this.

I still don't know where in the huge grid api object is the collapsed / expanded state :(

**Comment by apuntovanini** [comment]
Any news on this?

**Comment by spyro2000** [comment]
Seems like `RowGroupOpenedEvent` is not fired, when I open a column group...
