### ISSUE TITLE
Add ability to copy displayed values

### ISSUE THREAD

**Issue by mbacon-edocs** [ag-grid/ag-grid#1566]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Copying a selected range that involves columns with custom cell renderers and pasting into Excel will paste the original value (e.g. when having a foreign key column, you show the name, not the id used in the background)

**Expected behavior**
Sometimes you want to copy the value behind (such as within the grid, or for an export etc), but it would be nice to have the ability to add a 'Copy displayed values' context menu option and/or an API call so we can call it from within our own method/menu option and/or grid option to make that the default behaviour.

**Minimal reproduction of the problem with instructions**
Copying a selected range that involves columns with custom cell renderers and pasting into Excel will paste the original value

**What is the motivation / use case for changing the behavior?**
Makes it awkward to make a simple copy/paste export of subsets of data to create custom reports in Excel

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
v8.0.1

* **Browser:**
N/A

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by v-i-n-y-a** [comment]
Hi, 

It's 2019, is it possible to add this feature or at least possibility to disable default ag-grid copy paste behaviour?

**Comment by KiruthikaRaja** [comment]
> Hi,
> 
> It's 2019, is it possible to add this feature or at least possibility to disable default ag-grid copy paste behaviour?

Try  enableCellTextSelection={true}.
