### ISSUE TITLE
Feature request: Server side search, no way to set page on results for pagination

### ISSUE THREAD

**Issue by gregbown** [ag-grid/ag-grid#1567]
The new pagination options and methods are great, however; there still is no way to set the page that the server side search result produced. Please see [https://github.com/ceolter/ag-grid/issues/1495](url) Feb 27. If your row is on page 2 (25 rows per page) of 10,000 pages, there should be a way to set the current page or row without performing a second server request.  Perhaps an optional flag on paginationGoToPage(Number(value), false); for set page but do NOT trigger getRows?

Please let me know if there is a work around that allows setting the page, in such a way, that I have not seen.

Thank you
Greg

**Current behavior**
My current work around for keeping the pagination in sync is to do one of the following, however; it is not ideal since it triggers requesting the exact data that was just received in the prior search.
```
          /** The search result page we received is not page 0 that ag-grid thinks */
          // Could do this.
          this.gridOptions.api.paginationGoToPage(this._pageNumber - 1);
          // or this
          // this.gridOptions.paginationStartPage = (this._pageNumber - 1);
          // this.gridOptions.api.onSortChanged();
          return; //<- need to recurs so pagination can render on second request.
```
**Desired behavior**
A method to set the page OR current startRow and endRow

**Minimal reproduction of the problem with instructions**
Any server side search grid that has page rank or overall rank.

**What is the motivation / use case for changing the behavior?**
Having to perform multiple queries just to keep pagination in sync is not practical.

**Environment:**
Windows 10, Angular 4+, ag-Grid 9, Webpack 2+, TypeScript 2+,

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
