### ISSUE TITLE
FloatingFilterComponentFramework

### ISSUE THREAD

**Issue by jindalmayank** [ag-grid/ag-grid#1569]
Hi Team,

I am not able to use FloatingFilterComponentFramework in my application for custome floating filter in my angular 2 project.
Kindly update the documentation  with working example of custom floating filter in angular 2

regards,

**Comment by seanlandsman** [comment]
Hi - I've raised AG-381 for this and I'll update this thread when it's been done

thanks

**Comment by makinggoodsoftware** [comment]
This should be fixed now
