### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gregbown** [ag-grid/ag-grid#1571]
**Feature request**
Add an options object to column configuration allowing n amount of parameters to be passed into each column header.

Similar to the way you can pass an object as row data because a row cell may have to display a range graphic or multiple values in a cell such as a string and a number; the ability to have a custom header component goes only part way as you can only pass in one value for the header name.  Even the ability to pass in something like an icon via headerComponentParams is limited to a static value.  If the header configuration had an options object, n amount of key value pairs could be passed in, or if the headerComponentParams accepted a getter function that might be another way to retrieve n amount of parameters for a given header.  This need came about because our UI design called for two lines of text in some column headers and the sort controls to always be aligned with the bottom line of text.  Because the line break would never be constant and there is no ability to inject html into the header name I had to find a work around.

Currently I am able to hack a solution into the column configuration by adding an options object and then accessing it in the agInit of the Header Component via string access of private variables to get around the compilation error.

**In column config**
```
  public columns: ColumnConfig[] = [
    { field: 'top_score', headerName: 'Top Match Score', options: {topText: 'Top Match', bottomText: 'Score'}, minWidth: 125, maxWidth: 140,  suppressMenu: true },
    { field: 'top_kills', headerName: 'Top 10 Finish Rate', options: {topText: 'Top 10', bottomText: 'Finish Rate'}, minWidth: 115, maxWidth: 125, suppressMenu: true },
  ]
```

**In agInit of header component**
```
  public agInit( params: CustomParams ):void {
    /* Using strings to get around private variable compile time error */
    this.bottomText = params['column']['colDef'].options.bottomText;
    if (typeof params['column']['colDef'].options.topText !== 'undefined') {
     this.topText = params['column']['colDef'].options.topText;
    }
}
```
Thank you
Greg

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
