### ISSUE TITLE
[Feature Request] Allow showing groups without child elements

### ISSUE THREAD

**Issue by DmitriyKhomych** [ag-grid/ag-grid#1572]
**I'm submitting a feature request** 

Currently when we use quickfilter for filtering groups, group rows which have no child elements in result are hidden. In cases when grouping is used for displaying **tree hierarchy** such behavior is not expected.
So we need some equivalent of `groupRemoveSingleChildren` setting but for **no children case** to avoid some parts of tree being hidden.

Tree example:
![image](https://cloud.githubusercontent.com/assets/4457724/24693937/9750611c-19e8-11e7-9f67-9ce8f4a4681c.png)

Thanks,
Dmytro

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
