### ISSUE TITLE
Master / slave column sorting and filtering not propagating

### ISSUE THREAD

**Issue by oliyh** [ag-grid/ag-grid#1574]
Feature request

Hi,

We are using Master / Slave grid functionality to give us a totals row as described in #45.

We have two identical grids, slaved to each other, and features like scrolling, column resizing, reordering and pinning columns all work, propagating from the origin grid to the slave grid.

However, two features that don’t work, and would be really useful to us, are column sorting and column filtering. The events just don’t seem to propagate to the slave grid.

Could we please request this feature? Without it our totals row does not show the correct total of the values in the grid when we filter, and without sorting we cannot put our totals row at the top.

Many thanks

**Comment by asdkalluri** [comment]
https://github.com/ceolter/ag-grid/issues/1324

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
