### ISSUE TITLE
Row selection on mousedown

### ISSUE THREAD

**Issue by httpdigest** [ag-grid/ag-grid#1575]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Selecting a row with the mouse currently only happens via the 'click' event.
This can make the application feel a little "slow" because the row will only get selected when the user releases the mouse button when 'click' is fired.

**Expected behavior**
I'd like to propose the option to use the 'mousedown' event for row selection.
Currently, I just added another case `case 'mousedown': this.onRowClick(mouseEvent); break;` to the function 'onMouseEvent()' in src/ts/rendering/renderedRow.ts below the 'click' case.
That seems to do the job just fine but I am unsure whether there are other side-effects not accounted for and how to make that configurable.

**What is the motivation / use case for changing the behavior?**
The motivation is to allow the grid/table to feel more responsive, giving the user quicker feedback of row selections.

* **ag-Grid version:** X.X.X
Git commit ce3a03ed0dd9a4f6d394a0692f2e1ada6cb455ff

* **Browser:**
Chrome 57.

**Comment by celestale** [comment]
Hello @makinggoodsoftware, is this onMouseDown event going to be implemented?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by MatthieuCoelho** [comment]
@makinggoodsoftware 
Is this feature "Row selection on mousedown" implemented in Enterprise version ?

**Comment by htelferAptiv** [comment]
This can be achieved by using a cell's click handler to select it's row (see https://www.ag-grid.com/javascript-grid-selection/#node-selection-api for more info on programmatically selecting a row):
`onCellMouseDown={(e)=>{
                        e.node.setSelected(true,true)
                    }}`

**Comment by MatthieuCoelho** [comment]
The goal is to left click on a cell, drag the mouse(without releasing the left click) and select all nodes.
onCellMouseDown will only be trigger on the first left click, but not when we drag.

**Comment by YoeriPostma** [comment]
Sorry  bit late to the party. I requested this functionality from ag grid support.

Although we have a workaround by "abusing" the rangeselection as we have no further use for that functionality at the moment...works quite ok.


onRangeSelectionChanged(event) {
if(this.ctrllsHold II this.shiftlsHold) {
return;
constcellRange = this.gridApi.getCeIIRanges();
conststartRange =
Math.min(cellRange[0].startRow!.rowlndex,
cellRange[0].endRow!.rowlndex);
constendRange =
Math.max(cellRange[0].startRow!.rowlndex,
cellRange[0].endRow!.rowlndex);
this.gridApi.forEachNode((node)
if (node.rowlndex >= startRange &&
node.rowlndex <= endRange) {
node.setSeIected(true)
} else {
node.setSeIected(false)
