### ISSUE TITLE
Recomputing width does not work together with CSS Grid

### ISSUE THREAD

**Issue by httpdigest** [ag-grid/ag-grid#1584]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using the ag-Grid together with the CSS Grid Layout, and putting the ag-Grid component inside a '1fr' CSS Grid cell, then the ag-Grid won't recompute its width when relayouting of CSS Grid happened.
Currently, I have the following simple CSS Grid layout of a container div:
```CSS
display: grid;
grid-template-rows: 1fr max-content;
grid-template-columns: 1fr max-content;
```
Now, when putting the ag-Grid component inside the top-left CSS Grid cell, using:
```CSS
grid-row: 1/1;
grid-column: 1/1;
```
and toggling the display of content inside of the 'max-content' cells, the ag-Grid component will correctly update its height, but not its width. That means, when the component in CSS Grid cell (row:1, col:2) gets displayed and CSS Grid determines that it needs 200px and therefore the '1fr'-sized ag-Grid now should have 200 pixels less width, the ag-Grid still insists of using the full width instead of 200px less.

I've dug into this issue and it seems that exactly [this line inside borderLayout.ts](https://github.com/ceolter/ag-grid/blob/master/src/ts/layout/borderLayout.ts#L271) is causing the problem. It sets the width of the ag-Grid container, but probably it will not get noticed whenever CSS Grid Layout performed a relayouting of the page.
Commenting out this exact line resolved the issue, since a fix width was not necessary anymore because CSS Grid Layout was used.

**Expected behavior**
The ag-Grid should update its width based on the CSS Grid Layouting when the ag-Grid is used inside of a flexible size ('1fr') CSS Grid cell.

**Minimal reproduction of the problem with instructions**
1. define a CSS Grid container with the above mentioned CSS properties.
2. style the ag-Grid using the above mentioned CSS properties to make it part of a flexible-sized ('1fr') CSS Grid cell
3. dynamically put a fixed-sized HTML block element inside the 'max-content' CSS Grid cell to the right of the ag-Grid cell
4. observe that the ag-Grid still wants its full width

**What is the motivation / use case for changing the behavior?**
Allow to use the ag-Grid as part of a CSS Grid Layout.
The CSS Grid Layout is gaining more and more attraction as a means to design form-based enterprise applications with two-dimensional layout constraints, which Flexbox does not suit well.

**Please tell us about your environment:**
Windows 7 x64, NPM 4.5.0, Angular 4.0.1

* **ag-Grid version:** 9.0.0

* **Browser:**
Chrome 57.0.2987.133 (64-bit)

* **Language:**
TypeScript 2.2.2 with Angular 4.0.1

**Comment by seanlandsman** [comment]
Hi

I've raised issue AG-426 for this our side - we'll update this thread with updates as soon as we have any.

thanks

**Comment by PranKe01** [comment]
We got the same problem here. In this line ( https://github.com/ag-grid/ag-grid/blob/16b95d668bd1f489eb8ca2417d8d6e69bfc90b73/src/ts/layout/borderLayout.ts#L292 ) the grid gets resized all the time. Where can we find the status of the AG-426 issue?

**Comment by PranKe01** [comment]
Any changes here? We updated to AG-Grid 14, but the error still occurs :(

**Comment by makinggoodsoftware** [comment]
Hi,

We are changing the process and closing all issues with a ticket number since they can be tracked from our pipeline https://www.ag-grid.com/ag-grid-pipeline/

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by petyosi** [comment]
Hi guys, 

I am currently investigating how to make the pre-flexbox / css grid implementation to coexist better with the modern implementations. Something like this seems to work reasonably well:

https://plnkr.co/edit/leffOSa6BvvyVfoH21XH?p=preview

Notice that the grid itself is not directly part of the grid parent / child layout. Also, its wrapper should have `overflow: hidden`. 

Please let me know if this works for your deployments. we will update the docs accordingly. Thank you beforehand.
