### ISSUE TITLE
Allow translating the labels of the aggregation functions (internationalization)

### ISSUE THREAD

**Issue by clamonsch** [ag-grid/ag-grid#1598]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
AG grid provides the possibility for internationalization of almost every label. However for the aggregation functions this is - only in some cases - not working. Translating of the entries in the aggregation menu is working fine. On the other hand the same labels in column headers and in the values section of the tools area are not translated before rendering (see screenshot). In my opinion every label should be translatable which is why this issue is flagged as bug.

![aggrid-missing-internationalization](https://cloud.githubusercontent.com/assets/11771812/25140012/342de0d8-245f-11e7-9f5e-e928ebf38647.png)

**Expected behavior**
Translate the labels before rendering them by using the existing internationalization mechanism. 

**Minimal reproduction of the problem with instructions**
- Provide a "localeTextFunc" as described in https://www.ag-grid.com/javascript-grid-internationalisation which returns a label for key "avg".

**What is the motivation / use case for changing the behavior?**
We have to translate the whole grid into different languages.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
Latest version.

* **Browser:**
Different browsers.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
This should be fixed now
