### ISSUE TITLE
Keyboard Navigation issue

### ISSUE THREAD

**Issue by EIZENHORN91** [ag-grid/ag-grid#1612]
I'm submitting a
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
In large table (with many columns and horizontal scroll), after focusing first cell (for exmple) click End button, the last line is highlighted, as expect, (!) but also table scrolling to right and leave focus, then all key navigation not working while we not focus any cell again.
Similar behavior when the Home button is clicked when we select the rightmost cell of the table.

**Expected behavior**
In large table (with many columns and horizontal scroll), after focusing first cell (for exmple) click End button and table must select last row, and after click other buttons (key up, Home, Page Up) expect changing selection depending on the pressed key.

**What is the motivation / use case for changing the behavior?**
Use corrected key navigation without focus leaving

**Please tell us about your environment:**

* **ag-Grid version:** 8.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

* **Language:** TypeScript 2.1.1 (Angular 2.3)

P.S. Sorry for bad english :\

**Comment by EIZENHORN91** [comment]
Hello! Are there any progress? :)

**Comment by seanlandsman** [comment]
Hi,

No, I'm afraid not - this issue is still open our side and yet to be picked for development I'm afraid

**Comment by EIZENHORN91** [comment]
Good! Thx! Now we update and test this :)
