### ISSUE TITLE
miss update the set-filter on add new row

### ISSUE THREAD

**Issue by Julzk** [ag-grid/ag-grid#1617]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

the set filter doesn't update on add a row with a new cell-value

**Expected behavior**

the set filter update on add a row with a new cell-value

**Minimal reproduction of the problem with instructions**

can reproduce it in the exampleInsertRemoveGroups:
generate no item with 'Celica' on load and add a button who add a 'Celica'.
The set-filter doesn't contains a checkbox with 'Celica' :(
after click on 'Select All', the checkbox is shown.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 9.1.0

* **Browser:** Chrome 57

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

I've just tried this but cannot reproduce it I'm afraid - perhaps I'm missing a step.

Can you elaborate on what you're doing, step by step?

thanks

**Comment by Julzk** [comment]
https://ag-grid.com/javascript-grid-insert-remove/exampleInsertRemoveGroups.html
1. remove all rows except one row
2. open the set-filter (first time after load the page) in the group-column (only one checkbox)
3. insert some new rows
4. open the set-filter -> only one checkbox is visible.

my workaround on add new row:
`let tagFilterComponent = this.cfGrid.getGridOptions().api.getFilterInstance('myColumn');
        let filters = [];
        if (!tagFilterComponent.isEverythingSelected()) {
          for (let i = 0; i < tagFilterComponent.getUniqueValueCount(); i++) {
            if (tagFilterComponent.isValueSelected(tagFilterComponent.getUniqueValue(i)))
              filters.push(tagFilterComponent.getUniqueValue(i));
          }
        }
        this.cfGrid.getGridOptions().api.destroyFilter('logTag');
        if (filters.length > 0) {
          tagFilterComponent = this.cfGrid.getGridOptions().api.getFilterInstance('myColumn');
          tagFilterComponent.selectNothing();
          filters.map(filter => {
            tagFilterComponent.selectValue(filter);
          });
          tagFilterComponent.onFilterChanged();
        }`

**Comment by makinggoodsoftware** [comment]
Hi,

This is now documented in the docs
