### ISSUE TITLE
Page up/down navigation is too aggressive

### ISSUE THREAD

**Issue by jathri** [ag-grid/ag-grid#1620]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
First row is focused. Lets say the last is row 15. When I press page down, row 17 is shown as first row on the next page. So row 16 is completely missed.

**Expected behavior**
Row 15 is shown as first on next page for me to be sure that I did not miss anything.

**System**
W7 home, Firefox 52.0.1. (64 bit), ag-Grid v9.0.0, just javascript

**Comment by jathri** [comment]
I edited text few days ago. So it should be much clearer now.
Can you please look into this issues? It is really annoying...

**Comment by jathri** [comment]
Tried to use getLastRenderedRow() and ensureIndexVisible(index), but getLastRenderedRow does not retrieve correct numbers. It says 26 when I have only 16 fully visible rows. What could please be the reason?
I also think ensureIndexVisible is not what I need. Can ensureIndexFirstRow or something like this be added?
I have had success adjsuting arrow navigation to my needs using navigateToNextCell lately (https://www.ag-grid.com/javascript-grid-selection/?framework=javascript#selectionArrowKeys). But I miss something like navigateToNextPage to adjust Page up/down navigation as above. Could you please look into this too?

**Comment by jathri** [comment]
Current page up/down navigation also does not recognize if horizontal scrollbar is present. It just takes text under it as visible. Hope you can get to this soon...

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
