### ISSUE TITLE
progressSort() doesn't clear other column sorts, whereas setSort() does. Docs suggest both are viable options

### ISSUE THREAD

**Issue by oller** [ag-grid/ag-grid#1622]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

_not sure if it's a bug or intended feature, docs unclear._

**Current behavior**
https://www.ag-grid.com/javascript-grid-header-rendering/#sorting 
The grid-header component docs state you have 2 options when looking to programatically change the sort of a col.  `setSort()` to manually specify a sort order, or `progressSort()` to move to the next sort state.

**Expected behavior**
`setSort()` will clear the sort state of the other columns, `progressSort()` leaves them in tact, which can lead to rather complicated undesirable states as this is effectively forcing mutli-col sort without the user having to hold shift to opt-in to such a feature.

**Minimal reproduction of the problem with instructions**
https://www.ag-grid.com/javascript-grid-header-rendering/exampleHeaderComponent.html
edit the following function.

```js
MyHeaderComponent.prototype.onSortRequested = function ( /*order,*/ event) { 
    // this.agParams.setSort(order, event.shiftKey);
    this.agParams.progressSort(event);

};
```
- remove order param from function call
- swap out `this.agParams` function call, to use `progressSort(event);` instead

**What is the motivation / use case for changing the behavior?**
Trying to implement a sort style with repeated clicks of cols toggle through the 3 states: `asc`, `desc` and `null`, as opposed to 3 separate icons in the demo.  Using `progressSort()` to leverage the automation of progressing to the next sort state, however this doesn't reset the sorts of other cols, unlike `setSort()`

* **ag-Grid version:** 9.1.0

* **Browser:** "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36"

**Comment by oller** [comment]
Bump, any news or thoughts on this?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
