### ISSUE TITLE
"this.floatingFilterComp.onParentModelChanged is not a function" when pinning column

### ISSUE THREAD

**Issue by rdu** [ag-grid/ag-grid#1623]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The following exception is thrown:

this.floatingFilterComp.onParentModelChanged is not a function

**Expected behavior**

no exception

**Minimal reproduction of the problem with instructions**

- using angular2
- simple grid with 2 columns or more
- provide floatingFilterComponentFramework with a custom filter component (interface implemented)
- everything works fine until you try to pin the column with the floating-filter. Then the exception is thrown.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 9.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by rdu** [comment]
Some additions:

- the exception is thrown as well when I apply the filter in the column  filter menu.
- it works flawless if I avoid the angular component and do it in plain javascript

**Comment by saurabhraja** [comment]
Hello! Have any update on this issue?

**Comment by rdu** [comment]
No, it is still not working.
Until it is fixed I used a workaround and implemented the plain javascript interface and created the angular component via ComponentFactoryResolver by myself. I know it is somewhat a hack, but I hope the problem will be fixed soon.

**Comment by rdu** [comment]
I created a plunker for this issue:

https://plnkr.co/edit/lCEf1L6gDEo1wESvM6QN

For some reasons the error occours already on startup (see console output)  this is different to the behavior without plunkr.

**Comment by rdu** [comment]
I just realized I used the wrong version in the plunker. Changed it from 9.0.3 to 9.1.0.

Now the grid initializes correctly. Because pinning columns is a enterprise feature you can reproduce this error (free version in the plunker) when clicking the filter button and type any value into the input field.

**Comment by seanlandsman** [comment]
Hi

Thank you for reporting this - I've raised a high priority issue for this our side (AG-457)

We'll update you on the progress of this issue on this thread too

thanks

**Comment by burnnat** [comment]
I'm encountering this same error but with React rather than Angular, hopefully the fix will encompass both frameworks.

**Comment by makinggoodsoftware** [comment]
This should be fixed now
