### ISSUE TITLE
Use context-appropriate filter descriptions for date filter types

### ISSUE THREAD

**Issue by jakeboone02** [ag-grid/ag-grid#1625]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Date filter types use the same labels as Number filters, being both Scalar types.

**Expected behavior**
The Date filters should reflect the normal language used to compare dates, e.g. "After" and "Before" instead of "Greater than" and "Less than".

```
Current:        Suggested:
Equals          Same as
Greater than    After
Less than       Before
Not equal       Not same as
In range        Between
```

**Minimal reproduction of the problem with instructions**
Add `filter: "date"` to a column definition.

**What is the motivation / use case for changing the behavior?**
The average user thinks of dates as a timeline, travelling to the right.  They do not think of one date as being "greater than" another, just happening at a different time.

**Please tell us about your environment:**
all

* **ag-Grid version:** X.X.X
9.1.0

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by Flashwit** [comment]
Agreed. It would probably be ideal to be able to set the operator text for each style of filter, not just Date. It's more rare for other types, but I could conceive of situations where different text would make more sense in certain contexts.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
