### ISSUE TITLE
Group Selection Will Select Filtered Out Nodes

### ISSUE THREAD

**Issue by PlantPorridge** [ag-grid/ag-grid#1627]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Setup: Tree like setup with at least 3 levels with groups, check boxes, multiple selections, groupSelectsChildren and groupSelectsFiltered enabled.

If you apply a filter so not all the 'leaf' rows are displayed and check the top level checkbox, then all rows, even those hidden by the filter, will be selected. If you were to check a row one level up from the leaf level then it will only select those visible by the filter.

**Expected behavior**
Checking a checkbox at at level will only select those visible by the filter.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/9lUpx2MqDQ7eA9k8HzDs?p=preview

**What is the motivation / use case for changing the behavior?**
Inconsistent behaviour by making selections at different levels makes it unclear to users what is actually being selected. If only visible rows are selected then it would improve confidence.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, Angular 

* **ag-Grid version:** X.X.X
9.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.3 ES6

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - I've raised issue AG-459 our side to track this. We'll update this thread with updates as soon as we have any

thanks

**Comment by seanlandsman** [comment]
Hi

Actually, I stand corrected - there is a setting to change this behaviour: groupSelectsFiltered

Please see  https://www.ag-grid.com/javascript-grid-selection/ for more information about this

**Comment by PlantPorridge** [comment]
@seanlandsman Thanks for getting back to me. Unfortunately groupSelectsFiltered is set to true in the Plunker example I gave above.

**Comment by seanlandsman** [comment]
Hi @PlantPorridge 

Yep, I missed that - issue re-opened

thanks

**Comment by PlantPorridge** [comment]
@seanlandsman I've implemented a potential fix and raised a pull request. I hope it can be accepted or points you guys to a right area.

**Comment by seanlandsman** [comment]
@PlantPorridge thanks very much - we're planning on going though the backlog of feature request and PRs next week

I'll start from the top so yours will be looked at first

Thanks for providing this

**Comment by JohnMasterson** [comment]
Our recent update to Tree Data in version 14 corrects this.

Regards, 

John
