### ISSUE TITLE
Visual order of rows doesn't match DOM elements - impossible to style selected/hovered rows in certain ways

### ISSUE THREAD

**Issue by luanped** [ag-grid/ag-grid#1632]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This is very similar to issue 1583 - the ordering of rows in the DOM doesn't match the visual rows. This doesn't cause issues for ag-grid itself because the rows are all placed as absolute elements with a fixed top offset and tabbing is handled by JS code. 

However if we want to give a border top and bottom (e.g. 1px) for selected rows (and hovered rows), there is no way of collapsing the borders of 2 visually together rows; leading to the case of getting something like: 1px border [row] 2px border [row] 1 pixel border

**Expected behavior**
The DOM should match the visual data. Or an optional way to toggle this behaviour by sacrificing some performance.

**Minimal reproduction of the problem with instructions**
```
ag-body-container {
    border-collapse:collapse;
}

.ag-row {
    display:table-row;

    .ag-cell {
        display: table-cell;
        border-top: 1px solid transparent;
        border-bottom: 1px solid transparent;
    }
}
.ag-row.ag-row-selected,
.ag-row.ag-row-hover {
    .ag-cell {
        border-top: 1px solid red;
        border-bottom: 1px solid red;
    }
}

```
**What is the motivation / use case for changing the behavior?**
More UX possibilities

**Please tell us about your environment:**
irrelevant

* **ag-Grid version:** X.X.X
9.1.0

* **Browser:**
all

* **Language:** [all]

**Comment by leilabl** [comment]
Are there any updates in this issue?

My use case is different. I'm trying to print the full grid by setting `domLayout: "forPrint"`. Printing needs to include user's changes to the grid such as sorting rows and reordering columns. When print is called, the data in the DOM is what gets printed. Issues include incorrect row order and mismatch between headers and columns. I tried setting `gridOptions.ensureDomOrder = true` but that doesn't seem to have any effect.

Is reconciling the DOM and UI in your pipeline?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
