### ISSUE TITLE
Show tooltip when value is truncated

### ISSUE THREAD

**Issue by 1mr3yn** [ag-grid/ag-grid#1638]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

Is there a better way to only show the tooltip once the value is truncated? Currently, I'm using html canvas to calculate the value's width in pixel and comparing it to the cell width. But I think this is not the accurate solution to this issue.

``` 
      var canvas = document.createElement('canvas');
      var ctx = canvas.getContext("2d");
      ctx.font = "14px Roboto"; 
      var valWidth = (ctx.measureText(val).width);
      cellWidth = grid_settings.columnApi.getColumnState()[0].width
      if (valWidth >= cellWidth ) {
        //show css bootstrap tooltip   
     }
``` 
Does ag-grid has event listener for this?

* **ag-Grid version:** ag-grid-enterprise v8.0.1

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
