### ISSUE TITLE
Master Details for multiple column keys

### ISSUE THREAD

**Issue by nupin** [ag-grid/ag-grid#1644]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently in the Master-Detail , detail is based out of one column value . Expand action is for one column .

**Expected behavior**
I have a requirement like showing different detail for different columns of same row 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Trying to use ag-grid master details to my database view where I have multiple FK details to be showed upon

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular2/Typescript

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
