### ISSUE TITLE
Header Component has showColumnMenu method but no matching hideColumnMenu to toggle visibility of column menu

### ISSUE THREAD

**Issue by oller** [ag-grid/ag-grid#1660]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the header component example, click on menu button to show columnMenu, click on menu button again, nothing happens.

**Expected behavior**
Users expect clicking menu button toggles visibility of column menu. There's a `showColumnMenu` method, but no matching `hideColumnMenu` method or `isColumnMenuVisible` flag to implement this in a header component. (or if there is it's not mentioned in the docs)

**What is the motivation / use case for changing the behavior?**
User clicks on a menu icon expecting to toggle visibility, however when menu visible, menu button does nothing, user has to click off elsewhere to hide, or sort a col - unnecessary actions.

* **ag-Grid version:** 9.1.0

* **Browser:** "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
