### ISSUE TITLE
Redundant scrollbar appearing when zooming (and in some OS/browser combinations)

### ISSUE THREAD

**Issue by hunthunthunt** [ag-grid/ag-grid#1669]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Description**
When browser is zoomed (also triggered on Win8 Chrome when not zoomed), a redundant scrollbar appears on  the`#borderLayout_eGridPanel` div element (`.ag-bl-full-height`) 

For example, please see the image below, the scrollbar is added to the `div.ag-bl-full-height` due to incorrect rounding when measuring the `totalWidth` in `BorderLayout.prototype.layoutWidth` ([borderLayout.js](https://github.com/ceolter/ag-grid/blob/master/dist/lib/layout/borderLayout.js#L178)).

In this example below,`div#center` has been explicitly set to width: 513px, however the `div#borderLayout_eRootPanel` actually has a width of 512.67px, which is the cause of the issue.

**Cause**
The [utility method](https://github.com/ceolter/ag-grid/blob/master/dist/lib/utils.js#L473)`Utils.offsetWidth` uses `element.clientWidth` to determine an elements width, which only ever returns (rounded) integers. When the browser is zoomed and in some other scenarios element dimensions are not integers.

**Suggested Fix**
May I suggest you use `element.getBoundingClientRect().width` to determine an elements width - which should return non integer values when applicable.

**Further reading**
https://stackoverflow.com/questions/12604754/is-there-a-way-to-detect-if-the-browser-has-subpixel-precision

![image](https://cloud.githubusercontent.com/assets/226283/26451194/e28d4438-4152-11e7-949f-7c1ca270230e.png)

**Expected behavior**

Scrollbar is not triggered when zooming (or using WIn 8, Chrome)

**Minimal reproduction of the problem with instructions**

Zoom the browser:
In chrome, click Options, then zoom + 
Repeatedly click + till the issue appears

**What is the motivation / use case for changing the behavior?**

User should not see redundant scrollbar when zooming or using certain OS, browser combinations 

**Please tell us about your environment:**

OSX El Captain, Chrome  58.0.3029.110 (64-bit)

* **ag-Grid version:** X.X.X

9.1.0

* **Browser:**

Chrome  58.0.3029.110 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

**Comment by hunthunthunt** [comment]
Additional steps to reproduce:

This is for mac/chrome 58 but assume it will trigger the issue in most browser/OS combinations 

1. Go to:
https://www.ag-grid.com/example-angular-...#gsc.tab=0

2. In the browser console Elements tab, manually change the page column width from 800px to 800.6px
(you can find this just above the page h1 heading - 'Dynamic Angular Component Example')

3. Zoom the browser (+) till the redundant scrollbar appears

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
