### ISSUE TITLE
Multi-select Drop-down Rendering inside Ag-grid (Angular 2) issue   

### ISSUE THREAD

**Issue by ravidevkhile** [ag-grid/ag-grid#1671]
Hi, I am trying to integrate Multi-select drop down in Ag-grid (Angular 2) but it drop down options are hiding behind the subsequent row inside an Ag-grid (I have tried with different multi-select packages, but the problem remain same) do we have any solution for multi-select drop-down inside Angular 2 Ag-grid

**Comment by RoshanRoyal** [comment]
+1

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by saurabhraja** [comment]
Hi,

Any update on this issue?

Thanks.

**Comment by anshuman13** [comment]
+1

Facing the  same issue when setting the attribute for select as multiple.
<img width="111" alt="desk" src="https://user-images.githubusercontent.com/10692115/36293471-19a047ca-1300-11e8-80ca-3cba89c35b63.PNG">

All the value seems to render in the same cell rather than poping out as a dropdown.

<img width="109" alt="res" src="https://user-images.githubusercontent.com/10692115/36293521-659c9e26-1300-11e8-9c7b-c5c440e26aa6.PNG">
Expecting a behavior similar to single select.

**Comment by ranjeethkrao** [comment]
Cannot see the issue tracked in the pipeline though.. Awaiting the fix..!

**Comment by panchaln0110** [comment]
Hello I am developing dropdown menu, i need to create checkbox in dropdown so i can select multiple items. I am using ag-grid and angular. Please guide me

**Comment by pchoudhary-drg** [comment]
No update on it yet ?

**Comment by himanshuvicesoftware** [comment]
Is there any update to implement this using cellRenderer

**Comment by joshcse** [comment]
Please let me know is there any update Multi-select Drop-down Rendering inside Ag-grid

**Comment by VijaySutariaJCD** [comment]
Guys you should really do something for this as this is very old issue and its open since long.... please give some solution of this

**Comment by AhmetFiratKeler** [comment]
I'll make it simple. It took me 2 days to make one with plain javascript. 

Include

<script type="text/javascript" src="/assets/themes/frt/vendors/custom/bootstrap-multiselect/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="/assets/themes/frt/vendors/custom/bootstrap-multiselect/css/bootstrap-multiselect.css" type="text/css"/>

Style

<style>
    #commentSelection {
        width: 100%;
    }

    .input-widget-popup {
        width: 250px;
        height: 100px;
    }

    table {
        width: 100%;
        height: 100%;
    }

    td, th {
        text-align: center;
        padding: 8px;
    }
</style>

Components

    var selectedComments = [];

    class CommentCellRenderer {
        init(params) {
            this.eGui = document.createElement('span');
            if (params.value !== "" && params.value !== undefined && params.value !== null) {
                this.eGui.innerHTML = params.value;
            }
        }

        getGui() {
            return this.eGui;
        }
    }

    class CommentPopupCellEditor {
        init(params) {
            this.container = document.createElement('div');
            this.container.setAttribute('class', 'input-widget-popup');
            this._createTable(params);
            this.params = params;

            var commentUids = '';
            var commentNames = '';
            var rowSelectedComments = selectedComments.filter(comment => comment.rowId === params.node.id);
            for (var i = 0; i < rowSelectedComments.length; i++) {
                if (i > 0) {
                    commentUids += ',';
                    commentNames += ',';
                }
                commentUids += rowSelectedComments[i].uid;
                commentNames += rowSelectedComments[i].name;
            }
            this.selectComment(commentUids, commentNames);
        }

        selectComment(commentUids, commentNames) {
            this.commentList = commentNames;

            var rowNode = gridOptions.api.getRowNode(this.params.node.id);
            rowNode.setDataValue('comment_uid', commentUids);
            rowNode.setDataValue('comment_name', commentNames);
            setTimeout(() => {
                App.autoSizeAll(gridOptions);
            }, 1000);
        }

        getGui() {
            return this.container;
        }

        afterGuiAttached() {
            var that = this;
            $('#commentSelection').multiselect({
                buttonWidth: '100%',
                onChange: function(element, checked) {
                    var x = element[0];
                    var commentUid = $(x).val().toString();
                    var commentName = $(x).text().toString();

                    if (checked) {
                        var index = selectedComments.filter(comment => comment.rowId === that.params.node.id).map(function(e) { return e.uid; }).indexOf(commentUid);
                        if (index === -1) {
                            selectedComments.push({
                                rowId: that.params.node.id,
                                uid: commentUid,
                                name: commentName
                            });
                        }
                    }
                    else {
                        selectedComments = selectedComments.filter(comment => comment.rowId !== that.params.node.id || comment.uid !== commentUid);
                    }

                    var commentUids = '';
                    var commentNames = '';
                    var rowSelectedComments = selectedComments.filter(comment => comment.rowId === that.params.node.id);
                    for (var i = 0; i < rowSelectedComments.length; i++) {
                        if (i > 0) {
                            commentUids += ',';
                            commentNames += ',';
                        }
                        commentUids += rowSelectedComments[i].uid;
                        commentNames += rowSelectedComments[i].name;
                    }
                    that.selectComment(commentUids, commentNames);
                }
            });
            this.container.focus();
        }

        getValue() {
            return this.commentList;
        }

        isPopup() {
            return true;
        }

        _createTable(params) {
            this.container.innerHTML = `
      <table>
        <tr>
            <th><?php echo COMMENTS; ?></th>
        </tr>
        <tr>
            <td>
                <select id="commentSelection" multiple="multiple">
                </select>
            </td>
        </tr>
      </table>
    `;
            this.commentDropdown = this.container.querySelector('#commentSelection');
            for (let i = 0; i < comments.length; i++) {
                const option = document.createElement('option');
                option.setAttribute('value', comments[i].uid.toString());
                var index = selectedComments.filter(comment => comment.rowId === params.node.id).map(function(e) { return e.uid; }).indexOf(comments[i].uid);
                if (index !== -1) {
                    option.selected = true;
                }
                option.innerText = comments[i].name;
                this.commentDropdown.appendChild(option);
            }
        }
    }

Column

{headerName: '<?php echo COMMENT; ?>', field: 'comment_name', editable: true, cellEditor: 'commentPopupCellEditor', cellRenderer: 'commentCellRenderer'},

GridOption

        components: {
            commentCellRenderer: CommentCellRenderer,
            commentPopupCellEditor: CommentPopupCellEditor,
        },

**Comment by gandhis1** [comment]
For anyone who came across this issue recently, this appears to be back-log item in their pipeline:

> AG-8955 [Cell Editing] Add support for multi-select in agRichSelectCellEditor
