### ISSUE TITLE
AgGrid: add/remove rows, in Grid already having grouping/sorting/filtering applied

### ISSUE THREAD

**Issue by deepak-upman** [ag-grid/ag-grid#1672]
To be able to add/remove rows, in a grid which has already applied grouping/sorting/filtering, without reapplying the grouping/sorting/filtering on this row add/remove. It is that user can work on a group, updating some new values/adding new record which may still not belong to same group of grouping is reapplied, but we do not want to reapply grouping as user input will get scattered in grid, and hard to review for user.

1. What we tried with ("ag-grid": "^10.0.0", "ag-grid-enterprise": "^10.0.0", "ag-grid-react": "^10.0.0",)
2. Add a new row on some event/ btn click, in an already rendered grid with some data on startup, using the below(Skipping the refresh):
`
Let newItems = [];
   let newItem=  {
        id: 'SomethingNewId'+Math.random(),
        qty: 300,
        owner:"Deepak Kumar SHarma",
        isUpdated: true
    };
    newItems.push(newItem); this.gridOptions.api.insertItemsAtIndex(4, newItems, true); // Saying do not refresh the grid
`

3. After, above step, I see by iterating that a rowNode has been added, but row was not visible in grid. Then tried to refresh this newly added row only, so that it is visible in grid, expecting it to be without reapply this filter/sorting/filtering:

`let nodes = [];
this.gridOptions.api.forEachNode( (node, index) => {
if (node.data!==null && node.data!==undefined && node.data.isUpdated===true) {
      nodes.push(node);
   }
});
this. gridOptions.api.refreshRows(nodes);`

4. But still do not see the newly added row in grid.

5. If I just change the sorting/filtering/grouping manually again to some new setting, I see the new row in grid.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understa

**Comment by audioscavenger** [comment]
i have solution! very easy!

1. gridOptions:
```
var gridOptions = {
  onCellValueChanged: onCellValueChanged,
  ...
```

2. functions needed:
```
function onCellValueChanged(event) {
  if (event.column.rowGroupActive) { reloadGrid() }
}
function reloadGrid() {
  saveJsonDb()
  loadJsonDb()
}
```
saveJsonDb and loadJsonDb are just parsing and saving/loading params.data to/from a file.json (`gridOptions.api.setRowData(data)`)

and voila
