### ISSUE TITLE
onFloatingFilterChanged in react

### ISSUE THREAD

**Issue by re5ive** [ag-grid/ag-grid#1673]
Hi,

how to use onFloatingFilterChanged in reactJs? there is no doc for react :(

Thanks

**Comment by Ajaybhardwaj7** [comment]
I  am using the version v10 but still I am getting the error `Uncaught TypeError: this.floatingFilterComp.onParentModelChanged is not a function`

**Comment by makinggoodsoftware** [comment]
This should be fixed now
