### ISSUE TITLE
Need an example on ag-grid with angular 2 for master/detail grid where detail data is retrieved from server

### ISSUE THREAD

**Issue by learningongit** [ag-grid/ag-grid#1677]
It is not an issue but a general guidance question.

I have tried few options but not able to setup master/detail ag-grid where detail data is retrieved from server.
Trying with ag-grid in angular 2 project with observable pattern.
Please guide.

**Comment by elineopsommer** [comment]
There is an example provided: https://plnkr.co/edit/bpJgdo?p=info

**Comment by makinggoodsoftware** [comment]
Hi,

Have a look at the new master/detail

It has been revamped
