### ISSUE TITLE
Add detail about how selection changed in `selectionChanged`

### ISSUE THREAD

**Issue by grovesNL** [ag-grid/ag-grid#1682]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`selectionChanged` does not provide information about  _how_ the selection changed (whether "selection mode" is active -- basically whether `multiSelectKeyPressed || shiftKeyPressed`). Because of this, I can't tell the difference between a user clicking on a row versus adding a row to an existing selection.

**Expected behavior**
Provide information about the nature of the selection - whether it was triggered by some kind of multi-selection (i.e. `multiSelectKeyPressed` or `shiftKeyPressed`) or a regular click.

**What is the motivation / use case for changing the behavior?**
I am trying to understand how a user ends up with a single row selected. For example, if there was an initial selection of  five rows, I'd like to know whether:

- the user deselected rows by holding Ctrl/Meta and deselecting four rows, ending up with a single selected row
- the user clicked on a single row, triggering the other four to be deselected, leaving a single selected row

These are treated as two distinct workflows in my application. Imagine the user is in "selection mode" (holding Ctrl/Meta), then the user decides to discard the selection. The user does this by releasing Ctrl/Meta and clicking on a row. I want to treat that event separately than if the user had manually deselected rows to end up with one row selected.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
