### ISSUE TITLE
node.setSelected(true/false) freezes browser when working with thousands of nodes

### ISSUE THREAD

**Issue by jathri** [ag-grid/ag-grid#1683]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This code freezes browser when working with (tens of) thousands of nodes:
```
gridOptions.api.forEachNodeAfterFilterAndSort(function(node, index) {
	if (index >= start && index <= end) {
		if (something == 'true') {
			node.setSelected(false);
		} else {
			node.setSelected(true);
		}
	}
})
```

**Expected behavior**
Smooth processing. This is a question of adding few more lines, perhaps. If so, please help.

**Please tell us about your environment:**
W7 64bit, Firefox 52.0.1, ag-grid v9.0.0, plain javascript

**Comment by sousarka** [comment]
For every setSelected call there is a callback to refresh the ui and that takes time when called for lot of rows. Here's what you can try:
For all nodes, set selected attribute if rownode to true/false and push the rownode to an array. 

After the loop, update all the rownodes in the array by calling gridoptions.api.refreshRows(rownodes)

**Comment by jathri** [comment]
I am affraid I do not understand first part:  For all nodes, set selected attribute if rownode to true/false.
Can you please elaborate a bit?

**Comment by jathri** [comment]
@sousarka Gave this a second try and you probably meant something like this:
```
var rownodes = [];
gridOptions.api.forEachNodeAfterFilterAndSort(function(node, index) {
if (condition is met) {
node.selected = false;
} else {
node.selected = true;
}
rownodes.push(node);
})
gridoptions.api.refreshRows(rownodes)
```
It is truly possible to select nodes very fast this way, but it does not update select all header checkbox and does not fire onselectionchanged. I suppose there is no way around this, right?

@ag-grid developers Can you please look into this problem? Perhaps consider some batch selection API?

**Comment by jzav** [comment]
What about adding third (optional) parameter to node.setSelected() method? Something like redrawRow?
node.setSelected(true, false, false) would then select row without redrawing it...

**Comment by makinggoodsoftware** [comment]
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
