### ISSUE TITLE
Firefox auto attach .xlsx to excel file when export from aggrid

### ISSUE THREAD

**Issue by anangus** [ag-grid/ag-grid#1684]
**I'm submitting a bug**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm using "ag-grid-enterprise": "7.2.2",. When I export ag grid data to excel file, it works perfectly in IE and Chrome, only in Firefox, if I select "save as", it will export and open correctly, but if I select "Open As", firefox will automatically attach .xlsx to the end of excel file, so for example, if report name is report.xls, it will become report.xls.xlsx, then MS-Excel will say can't open it because file might be corrupted.

**Expected behavior**
In FireFox, Don't attach another file extension so MS Excel can open it correctly

**Minimal reproduction of the problem with instructions**
I'm using "ag-grid-enterprise": "7.2.2",. When I export ag grid data to excel file, it works perfectly in IE and Chrome, only in Firefox, if I select "save as", it will export and open correctly, but if I select "Open As", firefox will automatically attach .xlsx to the end of excel file, so for example, if report name is report.xls, it will become report.xls.xlsx, then MS-Excel will say can't open it because file might be corrupted.

**What is the motivation / use case for changing the behavior?**
In FireFox, Don't attach another file extension so MS Excel can open it correctly

**Please tell us about your environment:**
Windows 7

* **ag-Grid version:** X.X.X
7.2.2

* **Browser:**
Firefox 45.5.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by danielseligmann** [comment]
this is still an issue.
I can confirm this problem in later versions of Firefox and later versions of ag-grid.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
