### ISSUE TITLE
Keyboard Navigation left/right fires onRowEditingStopped

### ISSUE THREAD

**Issue by Nathan-Schutz** [ag-grid/ag-grid#1685]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

While using the editType of 'fullRow'
When using the left/right key to leave a cell into another on the same row, editing stops and the OnRowEditingStopped fires.

**Expected behavior**

When navigating within the row using the arrow keys, OnRowEditingStopped should not fire. 
While still on the same row, user should still be in the row edit state, as it does when clicking into the cell or using the 'tab' navigation.

**Minimal reproduction of the problem with instructions**

Can be seen on the demo Row Editing example.
https://www.ag-grid.com/javascript-grid-cell-editing/exampleFullRowEditing.html
Click on the price column to start editing, use arrow key right or left. Row Editing ends, and the console has the log calls from OnRowValueChanged (with the OnCellValueChanged for each item)

**What is the motivation / use case for changing the behavior?**

If actions need to happen only on changes to the row as a whole, (eg saving a row record to a database) we should be able to do so even with users using arrow key navigation between row cells.

**Please tell us about your environment:**

* **ag-Grid version:** 10.0.0

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

---------------------------
For others experiencing the problem, it is possible to add a keydown listener in your cell editor to check for the left/right key codes, and then use api.tabToPreviousCell() or api.tabToNextCell() with event.stopPropagation() to handle the 'while editing' keyboard navigation.

**Comment by sjain-mi9** [comment]
Not sure how we can add event Listener to stop onRowEditingStopped. I'm trying to avoid the default behavior of Enter key. Can you please provide an example on how it can be achieved,

**Comment by Nathan-Schutz** [comment]
For the Left/Right key capture, I have the following in my custom element init, hooked up after creating the element. You should be able to start from this to add custom handling of the enter key (13) for your custom element.  

```
_this.eElement.addEventListener('keydown', function (event) {
  //If navigating via arrow keys, call tab to next cell. - otherwise the 'onRowEditingStopped' fires early
  event = event || window.event;
  var keyCode = (typeof event.which == "undefined") ? event.keyCode : event.which;
  
  //left - 37, right - 39
  if (keyCode === 37) {
    params.api.tabToPreviousCell();
    event.stopPropagation();
    event.preventDefault();
  } else if (keyCode === 39) {
    params.api.tabToNextCell();
    event.stopPropagation();
    event.preventDefault();
  }
});
```

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as designed, so it is a feature request:

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline. Note that bugs raised in github will only be processed if they include a plunkr with a reproducible scenario.

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
