### ISSUE TITLE
Context not passed in Enterprise Row Model Request

### ISSUE THREAD

**Issue by jordanberry** [ag-grid/ag-grid#1686]
**I'm submitting a ...**  (check one with "x")
```
[  ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
First of all, Kudos on the Enterprise Row Model - Very Impressive. 

**Current behavior**
It looks like the EnterpriseDatasource getRows() doesn't pass along context in params like in the other row models. I use the context to apply certain styling in my cell renderers and currently can't access it . I could possibly access the context through gridOptions separately to get it but would be nice if it was passed along with the getRows() method. 

**Expected behavior**
The getRows() params should pass context so it can be used with the Enterprise Row Model.

**Minimal reproduction of the problem with instructions**
Example of Context being passed in rowModel: Infinite:

<img width="519" alt="screen shot 2017-06-01 at 4 41 29 pm" src="https://cloud.githubusercontent.com/assets/6355633/26702520/fa5dbe1a-46ea-11e7-81ed-b20c8ef8cafc.png">

Example of Context not being passed in Enterprise Row Model

<img width="506" alt="screen shot 2017-06-01 at 4 42 02 pm" src="https://cloud.githubusercontent.com/assets/6355633/26702541/0d43fb16-46eb-11e7-9fca-f3fb5a10fcb9.png">

**What is the motivation / use case for changing the behavior?**
Ability to access the context within the request allows for styling and other updates to the renderers.

**Please tell us about your environment:**
MacbookPro, macOs Sierra 10.12.4 Version 58.0.3029.110

* **ag-Grid version:**

10.0.0

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
