### ISSUE TITLE
Can not change default paginationPageSize (100)

### ISSUE THREAD

**Issue by duyth93** [ag-grid/ag-grid#1687]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The bug happened when Im upgrade version of ag-grid to 9.1.0. I can't change the `paginationPageSize` default value. It's always 100 no matter what I did. So value of `params.endRow` and `params.startRow` are not what I want too.

**Expected behavior**

The number of rows displayed per page should change to the value assigned to the DataSource object's paginationPageSize

**Minimal reproduction of the problem with instructions**
I set properties of grid like below:
```
$ctrl.gridOptions = {
        enableServerSideSorting: true,
        enableColResize: true,
        angularCompileRows: true,
        rowModelType: 'infinite',
        rowSelection: 'multiple',
        paginationPageSize: 60,
        infiniteInitialRowCount: 60
        cacheOverflowSize: 2,
        rowHeight: 28,
        getContextMenuItems: function (params) {
          return [
            {
              name: 'Reset Table State',
              action: resetGridState
            },
            'separator',
            'copy',
            'copyWithHeaders'
          ];
        },
        enableRangeSelection: true,
        suppressMenuFilterPanel: true,
        suppressMenuMainPanel: true,
        suppressMenuColumnPanel: true,
        processCellForClipboard: formatClipboard,
        onSelectionChanged: onSelectionChanged,
        onColumnResized: saveGridState,
        onColumnMoved: saveGridState        
      };
```
But it seems not change anything even in case setting dynamically
```
$ctrl.gridOptions.api.paginationSetPageSize(60)
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:** Linux x86_64

* **ag-Grid version:** 9.1.0

* **Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36

* **Language:** ES6

**Comment by Keki91** [comment]
**Minimal reproduction of the problem with instructions**


```
public gridOptions: GridOptions = <GridOptions>{
    enableServerSideSorting: true,
    enableServerSideFilter: true,
    enableColResize: true,
    paginationPageSize: 25,
    columnDefs: this.createColumnDefs(),
    rowModelType: 'infinite',
    rowSelection: 'single',
    suppressCellSelection: false,
    animateRows: true,
    rowHeight: 60
}
```


**What is the motivation / use case for changing the behavior?**


**Please tell us about your environment:**


* **ag-grid version:** 10.0.1
* **ag-grid-angular version:** 10.0.0 

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

* **Language:** TypeScript: 2.3.2
* **IDE:** Visual Studio Code

**Comment by duyth93** [comment]
@Keki91 Ow, thank you very much. it works like a charm. I wonder if there is any document containing these changes ?

**Comment by Keki91** [comment]
I winged it from the breaking changes from here (however for v10):

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0

> Breaking Changes:
> 
> The cache in 'infinite row model' now deals with blocks of rows, not pages of rows. To avoid terminology confusion (with pagination feature) the following name changes were made:
> Property maxPagesInCache renamed to maxBlocksInCache
> Property infiniteBlockSize renamed to cacheBlockSize
> Property paginationOverflowSize renamed to cacheOverflowSize
> API refreshInfinitePageCache renamed to refreshInfiniteCache
> API purgeInfinitePageCache renamed to purgeInfiniteCache
> API getInfinitePageState renamed to getBlockCacheState

**Comment by carlosdelangel** [comment]
Had been looking for this since the example in the page still uses the wrong names for the page size, thanks!

**Comment by kiwi1342** [comment]
+1. please fix the documentation.

**Comment by IonelLupu** [comment]
+1 oh man. I just spent some hours on this.... @makinggoodsoftware links in this PR are broken. Why are there two properties for the same thing???
