### ISSUE TITLE
Asynchronuous cell value commit

### ISSUE THREAD

**Issue by catahoc** [ag-grid/ag-grid#1694]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
CellEditorFramework.getValue is blocking call - I cannot provide async value (for example, perform async validation, or async value resolve after user input some text)

**Expected behavior**
Some way to commit value asynchronuously with possibility to reject it. So if user try to end editing, we can highlight value with red and don't close editor: user should either rollback his change with Esc or enter valid value. For example:
`
// resolve: provide value to commit synchronuously
// reject: prevent stop editing and highlight editor with red
CellEditorFramework.getValueAsync(): Promise<any>
`

**What is the motivation / use case for changing the behavior?**

User enters date in our application. We should validate this date asynchronuously against server. Currently we implement it by 2-state cell: after user enters value, cell comes into 'RESOLVING' state and starts validating. After it's validated, it comes to usual state

**Please tell us about your environment:**
Not needed here

* **ag-Grid version:** X.X.X
8.2.0 
AFAIK it's not implemented in most recent ag-Grid (14.*)

* **Browser:**
Not neede here

* **Language:**
typescript 2.3.2

**Comment by catahoc** [comment]
P.S. another option: prevent stop editing in some cases

`CellEditorFramework.preventGetValue` 
callback - if it returns true, then it's not allowed for user to proceed end editing with commit

**Comment by andrea-spotsoftware** [comment]
@catahoc i'm in the same situation..have you found any workaround?

**Comment by catahoc** [comment]
@andrea-spotsoftware nope, I doubt there are working workaround for this issue. You can in some way "lock" grid before start async operation and "unlock" it after

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by anatolyzolotar** [comment]
@makinggoodsoftware , thanks. But do you know any workaround for this problem? As I understand, I can either 
- use component's inner handling for stopping of editing (default submitting or cancelling behavior) with some kind of async 'getValue' method (not implemented in ag-grid)
- or at least I can use stopEditing() after my async action (saving data to backend, for example), but I'm not sure how can I handle stopping of editing properly (distinguish submitting from cancellation).

Do you have any idea how can I manually track completion of editing caused by default ag-grid events (see "Stop/End Editing" here https://www.ag-grid.com/javascript-grid-cell-editing/#gsc.tab=0)?

**Comment by catahoc** [comment]
@makinggoodsoftware , hi, can you provide AG-XXX number of this issue? I tried to find it on https://www.ag-grid.com/ag-grid-pipeline/, but failed

**Comment by Tim-Erwin** [comment]
Found it: AG-1639
