### ISSUE TITLE
Delta updates re-creating all cell components, even if delta is 0

### ISSUE THREAD

**Issue by iblocks-Xander** [ag-grid/ag-grid#1699]
**I m submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Calling api.setRowData with delta updates enabled still re-creates all the components in a grid, even if the delta is 0.
If the interaction is re-written as an explicit transaction, only the changed components are re-created.

**Expected behavior**
The Delta functionality should be consistent with a similar transaction.

**Minimal reproduction of the problem with instructions**
[plunkr link](https://plnkr.co/edit/pe0r0a52JOsDG4btV7sd)

Click on setRowData and check the console output. Each of the ratio components is being re-created.
If you click on update with transaction, there is only 1 component that is recreated.

**What is the motivation / use case for changing the behavior?**
In larger grids with expensive cell creation, this will cause slow down.

**Please tell us about your environment:**
Angular online plunkr  (started from an example)

**ag-Grid version:** 
10.1.0

**Browser:**
Tested in Chrome 59

**Comment by seanlandsman** [comment]
Hi,

Thanks for reporting - I've raised issue AG-524 for this our side. We'll update this thread with updates as soon as we have any.

It has been marked as a high priority issue

thanks

**Comment by iblocks-Xander** [comment]
@ceolter I see, so if the refresh function is defined, it calls it rather than the init method. I can see the comment in the documentation now, but perhaps it's worth highlighting the link?

Thanks for the quick reply.

**Comment by makinggoodsoftware** [comment]
Hi,

This should be fixed now

Thanks
