### ISSUE TITLE
Allowing doesDataFlower in Infinite Scrolling Model

### ISSUE THREAD

**Issue by iblocks-Xander** [ag-grid/ag-grid#1703]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the current Infinite Scrolling model, grouping is disallowed, as the grid can't load all the data, which is understandable.
However, the support for "doesDataFlower" is also removed, which feels like feature regression, as in ag-grid 8.x, "flowering" data was possible in the paginated model.

**What is the motivation / use case for changing the behavior?**
As "doesDataFlower" doesn't require any extra data to be loaded into the grid, is it possible to allow grouping in that case?
Our current use case is loading a subgrid in the full width renderer, doing it's own separate data request from the parent grid.
I think I can create a workaround in the short term, but it would essentially be re-creating the group cell renderer and pushing a fake row of data, which doesn't feel particularly nice.

**Please tell us about your environment:**

* **ag-Grid version:** 10.1.0

* **Browser:**
Chrome 59

* **Language:** all

**Comment by brphelps** [comment]
Did this workaround work for you? I'm currently interested in similar functionality :( .

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
