### ISSUE TITLE
Can't multi select using <shift> when row model type is 'infinite'

### ISSUE THREAD

**Issue by louwie17** [ag-grid/ag-grid#1705]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When the row model type is set to 'infinite' selecting one row, and selecting another role while holding shift just selects the latter row, and not everything in-between. Having rowSelection set to 'multiple'. Yet using 'command' allows us to multi select rows.

**Expected behavior**
When selecting the second row holding down 'shift', it should select everything in-between.

**Minimal reproduction of the problem with instructions**
Set row model type to 'infinite' and row selection to 'multiple', then try to select one row and another row while holding down 'shift'.

**What is the motivation / use case for changing the behavior?**
Keeping the selection functionality the same across all row model types, especially since it worked fine previously with pagination, but doesn't work as pagination has been changed to infinite scroll.
This seems to be the line at fault: https://github.com/ceolter/ag-grid/blob/9c700640c1cf111105a6a00d321fe3c9f97681c8/src/ts/entities/rowNode.ts#L416
 so I assume it was done for a reason, maybe an exception can be added when pagination is true.

**Please tell us about your environment:**

* **ag-Grid version:** 10.1.0

* **Browser:**
any

* **Language:** all

**Comment by taxibox-leigh** [comment]
Experiencing the same issue with ag-Grid 11.0.0, thanks for raising!

**Comment by dmarginian** [comment]
A short description of why this was done:
https://github.com/ceolter/ag-grid/issues/369

I don't quite understand the explanation it seems this should be supported in infinite scrolling as you can't select unless you have scrolled...

**Comment by taxibox-leigh** [comment]
Hey, I've gone ahead and knocked up a minimal example to illustrate the issue based on code in the ag-grid tutorials. I'm not fully fluent on ag-grid yet, so I apologise if I've made a rookie error here, but I think this shows what the issue is.

[http://jsbin.com/nuketujewo/1/edit?js,output](Example on jsbin.com)

**Comment by daric81** [comment]
I'm having the same issue described.

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as designed, so it would be considered a feature request, and right now we are only taking feature requests/support that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
