### ISSUE TITLE
InMemoryNodeManager runtime type checking could be improved

### ISSUE THREAD

**Issue by instantaphex** [ag-grid/ag-grid#1706]
**I'm submitting a ...**  (check one with "x")
```
[ x ] feature request
```

**Current behavior**
If anything other than an array is passed into the grid as it's data source, the grid will not function properly.  This is correct behaviour, however, the code seems to be only checking if rowData is a string and warning if it is.

https://github.com/ceolter/ag-grid/blob/master/src/ts/rowModels/inMemory/inMemoryNodeManager.ts#L178

**Expected behavior**
I would expect that the code would check if rowData is an array, and if not it should warn.  What if rowData is an object?  Then you end up with an error that rowData.forEach isn't a function.  Now of course multiple if statements could be added checking each type (number, object, boolean, undefined) but it seems like it would be better to simply check if it's an array and warn if it isn't.

**Minimal reproduction of the problem with instructions**
create a a grid and pass an object as the data source

**What is the motivation / use case for changing the behavior?**
Easier debugging

**Please tell us about your environment:**
All environments

* **ag-Grid version:** X.X.X
8.2.0 (not sure if this is the latest, but the problem exists in the master branch as shown above)

* **Browser:**
all

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
