### ISSUE TITLE
Pinned column scrolling (IE)

### ISSUE THREAD

**Issue by kespeart** [ag-grid/ag-grid#1710]
**Can we change the scroll element?**

This issue is related to another [issue](https://github.com/ceolter/ag-grid-enterprise/issues/38) which was closed pending recommendations from the developer community. 

As a possible solution, I would like to propose that we change the scroll element from "ag-body-viewport" to "ag-body". This will allow for both pinned and unpinned columns to be scrolled together, therefore, requiring no logic to adjust the pinned container to match the unpinned container.

![dom-image](https://user-images.githubusercontent.com/9921620/27185759-52104b36-51b4-11e7-9513-9b2ce3f265ee.png)

This change will have some impact on the virtual scroll; therefore, I have created a [plunker](https://plnkr.co/edit/ZLZ0ksnjwK0nmVKXQI1s?p=preview) which demonstrates how we can approach virtual scrolling after the above changes have been implemented.

* **ag-Grid version:** 10.1.0

**Comment by britvik** [comment]
Could devs look into this please? We are considering buying the enterprise edition but it's a nogo because of scroll lags in IE which we have to support :(.

**Comment by srishti0212** [comment]
Same fo us, we are considering buying enterprise edition but scrolling issues are holding us back.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
