### ISSUE TITLE
Column Filter get cleared after call ajax server side

### ISSUE THREAD

**Issue by lneninger** [ag-grid/ag-grid#1712]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I actived server side filter using using   enableServerSideFilter: true
After filter I get the matching values using ajax call I call function params.successCallback(data.results, data.inlineCount) inside at datasource.getRows to repopulate grid. That works fine but the filter is cleared.

**Expected behavior**

The column search term need to remind without changes  into column filter's content menu.

**Minimal reproduction of the problem with instructions**
1. Configure filter in server: enableServerSideFilter: true
2. In datasource.getRows call params.successCallback(data.results, data.inlineCount) after success ajax.

**What is the motivation / use case for changing the behavior?**

Unknow behavior

**Please tell us about your environment:**

Windows 7 Enterprise

* **ag-Grid version:** X.X.X

"ag-grid": "^9.0.3",
"ag-grid-angular": "^9.0.3",

* **Browser:**

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.6

**Comment by harikrishnan-u01** [comment]
I am also facing the same issue. The filter is getting cleared after the Ajax call.

**Comment by harikrishnan-u01** [comment]
Hi @ceolter ,

Any work around for this issue? Its kind of a blocker for me.

Thanks,
Hari

**Comment by harikrishnan-u01** [comment]
Hi Team,

I got the solution for this issue. In the columnDefs, add the following parameter.

filterParams: { newRowsAction : 'keep' }

Thanks,
Hari

**Comment by makinggoodsoftware** [comment]
This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
