### ISSUE TITLE
Define "rowNodeId" in grid properties

### ISSUE THREAD

**Issue by tpoindex** [ag-grid/ag-grid#1715]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Row Node Ids are currently generated via a callback function, getRowNodeId().  As per documentation sample: exampleGetRowNode.js
```
var gridOptions = {
   getRowNodeId: function(data) { return data.id; }
}
var rowData = [
    {id: 'aa', make: "Toyota", model: "Celica", price: 35000}
}
```

**Expected behavior**
Define the row data property that contains a unique Id to be used as the row Node Id:
```
var gridOptions = {
   rowNodeId: "id"
}
```

**Minimal reproduction of the problem with instructions**
See documentation example:  exampleGetRowNode.js.

**What is the motivation / use case for changing the behavior?**
Column definitions already include "colId" and "groupId" for defining column attributes.  RowNodeId as part of gridOptions would be another shorthand way of identifying a unique row id, without have to define a callback function, and presumable result in less overhead than use of a callback function.

**Please tell us about your environment:**
No specific environment.

* **ag-Grid version:** 10.1.0

* **Browser:**
Not browser specific

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
