### ISSUE TITLE
cellRendererParams seem to be missing innerRendererFramework

### ISSUE THREAD

**Issue by pupeno** [ag-grid/ag-grid#1716]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There's a grid option called groupRowInnerRendererFramework that allows you to specify how to render the inner part of a group cell by using the JavaScript framework. 

When you are defining a group column by using the column definitions and the cellRenderer "group", there's an option innerRenderer but there doesn't seem to be an equivalent innerRendererFramework. 

I couldn't find any way, in that case, to define the inner cell by using my Javascript framework. 

**Expected behavior**
I would have expected innerRendererFramework to exist or some other way of specifying the inner cell with my Javascript Framework. 

* **ag-Grid version:** 10.1.0
* **Language:** ClojureScript

**Comment by makinggoodsoftware** [comment]
This should be fixed now
