### ISSUE TITLE
Row group layout improvement when groupUseEntireRow set to true

### ISSUE THREAD

**Issue by R4DIC4L** [ag-grid/ag-grid#1719]
**I'm submitting a ...**  (check one with "x")
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

**Current behavior**
When groupUseEntireRow is set to true, the grid lines below the group disappear. Furthermore, when the row height is bigger than the text, it is not centered like in the rest of the cells.
Below is a screenshot of a material themed grid with a row height of 48, a row group by a column and groupUseEntireRow=true.
![ag-grid-row_group](https://user-images.githubusercontent.com/7274664/27425011-adb4eb3c-573f-11e7-8a9b-fa562a18fb7b.PNG)

**Expected behavior**
The text should be centered in the group row and the grid line should be shown (or an option for that should be available).
![ag-grid-row_group_expected](https://user-images.githubusercontent.com/7274664/27425981-d73e6f34-5742-11e7-8200-a536e94629c1.png)

**What is the motivation / use case for changing the behavior?**
The grid would look better if the text would be centered in the group row and the grid line would be visible.

* **ag-Grid version:** 10.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

* **Language:** Javascript ES6, React

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
