### ISSUE TITLE
full-width rows - apply style to entire row group

### ISSUE THREAD

**Issue by don-bluelinegrid** [ag-grid/ag-grid#1720]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a working implementation of full-width rows, shown in the screen shot, such that there are two top-level groups of rows with classes like `row-level-0` and `row-level-1`.  This grid is used as the "master" component of a master-detail view, where we select an item in the grid to display a corresponding detail view.  After selecting the grid row, we should be able to visually indicate the selected state of that row.  There seems to be no way to apply a "selected" class to the entire row group, because the group is composed of components split across the two top-level DIVs.  Only the item in `row-level-0` has an 'ag-row-focus' class applied on selection.

**Expected behavior**
We should be able to use CSS to visually indicate the selected state of an entire full-width row group.  For example, in the attachment, the second full-width row is selected.
![screen shot 2017-06-22 at 12 48 03 pm](https://user-images.githubusercontent.com/19780097/27445786-1dafd998-5749-11e7-9d41-244b3e4d4ecb.png)

**Minimal reproduction of the problem with instructions**
See attachment.

**What is the motivation / use case for changing the behavior?**
We should be able to use CSS to visually indicate the selected state of an entire full-width row group.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
9.1.0

* **Browser:**
All

* **Language:** TypeScript

**Comment by don-bluelinegrid** [comment]
@ceolter 

Niall,

Just checking on this.

This one is really somewhere between a bug and a feature request.  It is related to identifying the selected/focus state of a grid row when using fullWidth.  This is currently impossible, and makes setting a visual selected state of a complete fullWidth row impossible.

The root cause is that the fullWidth row is split into two completely separate parts of the DOM tree, for the main and child row.  The main row is marked with an `ag-row-focus` CSS class, but the child row is not marked with the same class.  Since they are in disconnected parts of the DOM tree, there is no way through CSS to visually set both the main and child row of a fullWidth pair to be visually selected.

Main row:
```
<div role="row" class="ag-row ag-row-no-animation ag-row-level-0 ag-row-even ag-row-focus" row="4" style="top: 160px; height: 30px;"><div role="gridcell" class="ag-cell-no-focus ag-cell ag-cell-not-inline-editing ag-cell-value" tabindex="-1" colid="0" style="width: 30px; left: 0px;">
```

Child row:
```
<div role="row" class="ag-row ag-row-no-focus ag-row-no-animation ag-row-level-1 ag-full-width-row ag-row-odd" row="5" style="top: 190px; height: 50px;">
```

Can something be done in the grid to apply the `ag-row-focus` to both parent and child pairs of rows when in fullWidth mode?  Or, can you suggest a solution?

Thanks,
Don

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
