### ISSUE TITLE
Cannot change overlayNoRowsTemplate after grid loaded

### ISSUE THREAD

**Issue by Mage111** [ag-grid/ag-grid#1724]
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

update `overlayNoRowsTemplate` after grid loaded

In my app there are two different situations where there are no rows to display. (when there is no data to show, and when there is no row for spesific filter)
I want to change the template each time depending on the situation. I updating the `overlayNoRowsTemplate` but the template cannot replaced after the grid has been loaded. 
refreshing the grid doesn't refresh the `overlayNoRowsTemplate`

**ag-Grid** version:  10.0.0

Thanks.

**Comment by Chali-Anne** [comment]
+1

**Comment by RamiSh** [comment]
Any new updates on this? @Mage111

**Comment by Mage111** [comment]
We didn't succeed to do that.

**Comment by otkalenko** [comment]
Reproduced also on ag-Grid version: 13.2.0 and 14.2.0

Thanks

**Comment by anildiv** [comment]
Plunker https://plnkr.co/edit/pKsMg7ZnwoZrI7KPqOk4?p=preview

**Comment by makinggoodsoftware** [comment]
This now should be working

**Comment by Ash1994** [comment]
Any new updates on this? @Mage111
Is it working now?
