### ISSUE TITLE
On Infinite scrolling the exporting doesn't work.

### ISSUE THREAD

**Issue by Vahanhakobyan85** [ag-grid/ag-grid#1725]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have setup infinite scrolling mechanism, on each scrolling additional 200 rows are got from DB.
But when I'm trying to export the grid data by gridOption.api.exportAsCsv(params)  grid exports this symbol only 'ï»¿'. 
Besides that when we have 580 rows in the grid, at the moment when I want to export girdOption has rowData.length set to 200. How can I export the whole data on the grid?
**Expected behavior**

User should be able to export the whole data which currently exist and visible on the grid.
**Minimal reproduction of the problem with instructions**

Here is my function:
setRowData = (firstChunkOfData) => {
    var dataSource = {
        rowCount: this.totalRowCount,
        getNewDataChank: this.props.getDrillDownGridDataChank,
        gridApi: this.gridOptions.api,
        handleReceivedData: this.handleReceivedData,
        getRows: function (params) {
            if(this.rowCount == 0) return;

            console.log('Grid: asking for ' + params.startRow + ' to ' + params.endRow + ' of ' +this.rowCount);
            this.gridApi.showLoadingOverlay();
            if(params.endRow > firstChunkOfData.length) {
              this.getNewDataChank(params.startRow, params.endRow - params.startRow).then((responce) =>{
                if(responce != null && responce.data != null){
                  this.handleReceivedData(params, this.gridApi, this.rowCount, responce.data);
                }
              })
            } else {
              let currentPageRows = firstChunkOfData.slice(params.startRow, params.endRow);
              this.handleReceivedData(params, this.gridApi, this.rowCount, currentPageRows);
            }
        }
    };

    this.gridOptions.api.setDatasource(dataSource);
  }
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by edsoubsoub** [comment]
Hello,

I'm having the same problem an enterprise rowModel.

Thx for helping us.

**Comment by Vahanhakobyan85** [comment]
https://stackoverflow.com/questions/44910531/how-can-i-export-aggrid-data-in-case-of-infinite-row-model-infinite-scrolling/44911670#44911670

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by pixelpax** [comment]
Is there a solution for this problem now, or still 'will not fix'?
