### ISSUE TITLE
Export of grouped header loses some cells

### ISSUE THREAD

**Issue by tagmaks** [ag-grid/ag-grid#1726]
Hi,
When I export the grid with grouped columns, output excel loses some header of the second level group row, see the picture 

![ag-grid export issue](https://user-images.githubusercontent.com/8607231/27575058-268bc7b2-5b21-11e7-915d-6cfd974c3b69.png)

As you can see everything work ok on UI. 
To define colDef is used function "setColumnDefs".

version: "ag-grid": "~10.1.0", enterprise

How to solve the issue?
Thanks.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
