### ISSUE TITLE
[Feature Request] async expand of row using flower nodes

### ISSUE THREAD

**Issue by GAndriyS** [ag-grid/ag-grid#1733]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After click on expand row element ([+] by default) grid in synchronous way starting re-rendering and trying to get data for flower node.

**Expected behavior**
After click on expand row element ([+] by default) user send request for additional data and grid waits for this request to resolve and then starts re-rendering and so on.

**What is the motivation / use case for changing the behavior?**
In my curr project we can't fetch all data for grid at once, and now I forced to stop propagation of click event, wait for request to resolve and then emulate mouse click.

* **ag-Grid version:** 11.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

* **Language:** 
TypeScript 2.3.4 / Angular 4+

**Comment by GAndriyS** [comment]
please, consider this feature request

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
