### ISSUE TITLE
[Row selection]: being able to select the group row

### ISSUE THREAD

**Issue by jlame** [ag-grid/ag-grid#1738]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I don't know whether this should be a bug or a feature request. The issue we have is that it's not possible to select a group row (this was done on purpose) because of the below code in rowClick function : 
                // we do not allow selecting groups by clicking (as the click here expands the group)
	        // so return if it's a group row
	        if (this.rowNode.group) {
	            return;
	        }

We don't use the default mechanism (group expansion on row click) and are using a custom button to expand so what's describe in the comment isn't an issue to us.
But we need to be able to select a group row which isn't possible for the moment, this has forced us to create a fork to comment this code.

**Expected behavior**
Will it be possible to add a flag in the grid configuration to enable the selection of group row ?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 10.1.x

* **Browser:** Chrome

* **Language:** all

**Comment by stephanjust** [comment]
There are multiple posts about this (#946 #1058 and some more). I'm not sure why this is the default behavior but one of the previous posts (that I can't find anymore) mentioned to just handle the selection yourself:

```
onRowClicked: (params: { node: RowNode, event: MouseEvent }) => {
    if (params.node.allChildrenCount > 0) {
        var select = true;
        var clearSelection = true;
        if (params.event.ctrlKey) {
            select = !params.node.isSelected();
            clearSelection = false;
        }
        params.node.setSelected(select, clearSelection);
    }
}
```

**Comment by jlame** [comment]
Saw the workaround which is handling the selection but this overrides the whole selection behaviour (which manages multi selection with ctrl and shift etc ...) which works really well. Would be a shame to rewrite it ...

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
