### ISSUE TITLE
Pressing tab while dragging selection results in uncaught js error

### ISSUE THREAD

**Issue by tystol** [ag-grid/ag-grid#1740]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On the first demo grid at: https://www.ag-grid.com
1. Drag to highlight a selection of cells.
2. While still dragging, press tab.
3. Continue dragging - every cell change during the drag now throws an unhandled error: `Uncaught TypeError: Cannot read property 'end' of null`

**Expected behavior**
For errors to not be thrown.

**What is the motivation / use case for changing the behavior?**
For ag-grid to not fill our js error reporting service with noise. No idea why our users are doing this particular sequence of actions - or they may be doing something else entirely, but this is how we have managed to reproduce it.

**ag-Grid version:** X.X.X
Our app is still on ag-grid 9.1, but reproducible on latest)

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

* **Language:** [all]

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this -  I've raised issue AG-589 our side to track this, but we'll update this thread with updates as soon as we have any

**Comment by voyti** [comment]
Same thing happens for me when I drag a cell selection and (while dragging) use calls:
```   
    this.gridOptions.api.clearRangeSelection();
    this.gridOptions.api.clearFocusedCell();
```
The problem seems to be with attempting to access members of `activeRange` field of `rangeController`, while `activeRange` is null-ed by above calls.

**Comment by makinggoodsoftware** [comment]
This should be fixed now

**Comment by JohnMasterson** [comment]
Just to confirm this was included in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
