### ISSUE TITLE
Cannot navigate through fullwidth cell via keyboard arrow keys

### ISSUE THREAD

**Issue by catahoc** [ag-grid/ag-grid#1747]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Imagine I have 3 rows
- row 1 - usual row
- row 2 - full width row
- row 3 - usual row

I have some cell in 'row 1' focused and I want to navigate to same cell in 'row 3' - so I press Down. But focus neither moves somewhere else, nor even remain in row 1. Row 1 cell looks focused, but it really don't - if you press Enter, editing won't start. 
As a result, user can't navigate outside of space between 2 full width rows using keyboard

**Expected behavior**
After I press Down on row 1, I expect one of two results:
- full width row is focused
- same cell of row 3 is focused

**Minimal reproduction of the problem with instructions**
You can reproduce this defect in documentation (https://www.ag-grid.com/javascript-grid-full-width-rows). User is stuck between 2 full width rows if he uses keyboard navigation

**Comment by dbVaspo** [comment]
+1

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
