### ISSUE TITLE
Slow rendering of detail grid (reopened #1754)

### ISSUE THREAD

**Issue by elineopsommer** [ag-grid/ag-grid#1762]
Original issue: #1754

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Slow rendering of the detail rows

**Expected behavior**
Should be the same speed as the master grid

**Minimal reproduction of the problem with instructions**
Plunker: https://plnkr.co/B0fXvdiaAXCdskmxwZdo

**What is the motivation / use case for changing the behavior?**
The grid is not usable anymore as it is slow in use.
I can't set the detail grid to be smaller as it is not user friendly to have a scrollbar inside a scrollbar. This is a major blocker.

**Please tell us about your environment:**
Does not apply as it is shown in the plunker

* **ag-Grid version:** 11.0.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

* **Language:** [TypeScript 2.1.1]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by elineopsommer** [comment]
@makinggoodsoftware I can't find this issue back in the pipeline and this is really a blocking issue, more important than add a new feature imo.
Can this issue be included in the pipeline?
