### ISSUE TITLE
Using updateRowData to add a new row does not update gridOptions.rowData.

### ISSUE THREAD

**Issue by berto168** [ag-grid/ag-grid#1768]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using gridOptions.api.updateRowData to add a new row, it does not add the new row as part of gridOptions.rowData. Instead the nodes are under gridOptions.api.rowModel.rowsToDisplay.

**Expected behavior**
I expected it to add the new rows to the actual rowData.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Makes the changes permanent to the grid's data.

**Please tell us about your environment:**
Windows 7, using webpack to package code and serve

* **ag-Grid version:** 11.0.0

* **Browser:**
Chrome Version 59.0.3071.104 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
AngularJS 1.5

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
