### ISSUE TITLE
Resize to fit only if there is free space on the grid

### ISSUE THREAD

**Issue by edriang** [ag-grid/ag-grid#1772]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I couldn't find an API that tells me if the grid has available space to fill (i.e. with sizeColumnsToFit()).
So, if I always call sizeColumnsToFit() then consider the following scenarios:
- If there was initially empty space then columns will be resized to fit the grid.
- If there isn't empty space, the columns will shrink until all are visible in grid.

This second scenario is sometimes not the best approach.

**Expected behavior**

I want to decide whether to call or not sizeColumnsToFit() based on available space. 
If there is available space, I want to resize. If not, I'm ok with horizontal scroll.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Consider this example. I have 10 columns shown and there is some free space. I can call sizeColumnsToFit() and because I'm on a large screen it is shown ok.
But if I'm on a smaller screen and call sizeColumnsToFit() then columns will be shrunk and size too small. In this case I prefer to show a horizontal scrollbar.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

11.0.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by edriang** [comment]
I leave my current workaround. It seems to work as expected:

```
autosizeColumnsIfNeeded(){
        let panel = this.grid['gridPanel'];
        let availableWidth = this.grid['gridPanel'].getWidthForSizeColsToFit();
        let columns = this.grid['gridPanel']['columnController'].getAllDisplayedColumns();
        let usedWidth = this.grid['gridPanel']['columnController'].getWidthOfColsInList(columns);

        if(usedWidth < availableWidth){
            this.grid.sizeColumnsToFit();
        }
    }
```
But I would like to have an "out of the box" solution for this, because gridPanel and columnController aren't exposed in typescript definitions.

**Comment by sguilly** [comment]
Work fine !

Pay attention to set grid according your configuration : 

```
let grid = this.gridOptions.api

let panel = grid['gridPanel'];
let availableWidth = grid['gridPanel'].getWidthForSizeColsToFit();
let columns = grid['gridPanel']['columnController'].getAllDisplayedColumns();
let usedWidth = grid['gridPanel']['columnController'].getWidthOfColsInList(columns);

 if (usedWidth < availableWidth) {
     grid.sizeColumnsToFit();
}
```

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by totszwai** [comment]
You can also do this to avoid using the private properties of AgGrid

    @ViewChild('agGrid', { read: ElementRef }) agGridElement: ElementRef;
    public columnApi: ColumnApi;
    ...

    const availableWidth = this.agGridElement.nativeElement.clientWidth;
    // getAllDisplayedColumns takes column ordering into consideration
    const displayedColumns = this.columnApi.getAllDisplayedColumns();
    const usedWidth = _.sumBy(displayedColumns, 'actualWidth');

**Comment by CodeguruEdison** [comment]
> You can also do this to avoid using the private properties of AgGrid
> 
> 
> 
>     @ViewChild('agGrid', { read: ElementRef }) agGridElement: ElementRef;
> 
>     public columnApi: ColumnApi;
> 
>     ...
> 
> 
> 
>     const availableWidth = this.agGridElement.nativeElement.clientWidth;
> 
>     const displayedColumns = this.columnApi.getAllDisplayedColumns();
> 
>     const usedWidth = _.sumBy(displayedColumns, 'actualWidth');
> 
> 

Do we have a react version for this?
