### ISSUE TITLE
getNodeChildDetails not being called after updating a rowNode data

### ISSUE THREAD

**Issue by danikenan** [ag-grid/ag-grid#1774]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After changing a row data using either `rowNode.setData` or `gridApi.updateRowData`  the `gridOptions.getNodeChildDetails` callback is not being called, so the new children are not being rendered.

Since we use the same gridOptions code in other 'data cases' too, I know for sure the the callback is being called when using `gridApi.setRowData` and for `gridOptions.rowData` that is set when configuration the grid for the first time.

**Expected behavior**
The `gridOptions.getNodeChildDetails` should have been called since the children might have changed.

**Minimal reproduction of the problem with instructions**

``` js
// somewhere in your code
var existingData = node.data
var newData = angular.extend({}, existingData, {__children: children});
node.setData(newData);
//or
gridOptions.api.updateRowData({update: [newData})

// __NOT__ being called
gridOptions.getNodeChildDetails = function(rowItem) {
            if(rowItem.__loadingFacade || rowItem.__isChild) {
                return null;
            }
            return {
                group: true,
                expanded: !!rowItem.__children,
                children: rowItem.__children || [{__loadingFacade: 1}],
                key: rowItem.row_id
            };
        }
```
**What is the motivation / use case for changing the behavior?**
We are using `setRawData` to lazy load children.

**Please tell us about your environment:**
angularjs, nothing special.

* **ag-Grid version:** 11.0.0

* **Browser:** "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

* **Language:** ES5

**Comment by ksnyder** [comment]
Have you found a solution?  This problem still exists in for me in version 13.1.  getNodeChildDetails() gets called when first rendering the grid, but not after updating the rowData and calling api.refreshCells().  All changes to cell data in the main row work fine, there's just no refresh of the its child nodes.

**Comment by ksnyder** [comment]
Thinking that the children may be handled like row grouping, I tried calling api.refreshInMemoryRowModel('group') as described at https://www.ag-grid.com/javascript-grid-data-update/?framework=react#gsc.tab=0  but it didn't solve the problem.

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-758 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by seanlandsman** [comment]
Hi

Apologies - I misread more into this issue than there is.

If using getNodechildDetails() the only way to update the 'tree structure' is to set the row nodes again (ie setRowData() ) - it won't be called again with data refreshes,

thanks

**Comment by ksnyder** [comment]
Hi -- I believe the original poster tried that (he mentions calling setRawData which I believe is a typo for setRowData).  In my case, I am using React and setting a new value of rowData with each render() call per the docs at https://www.ag-grid.com/javascript-grid-data-update/#gsc.tab=0, which I understand is the React equivalent of setRowData().

I am also setting deltaRowDataMode={true} and it works to get updates to the main rows, but not child rows, and I've verified that getNodeChildDetails doesn't get called except upon the original population of rowData.  If it helps, this code worked in version 10, but I haven't tested versions in between -- now on 13.1.  Thanks!

**Comment by seanlandsman** [comment]
Hi @ksnyder - do you have a repo of this problem? I've just tried this in our master/detail example which has getNodeChildDetails and is bound to rowData.

I added a button that refreshed the rowData and both the parent & child rows were refreshed as expected

**Comment by ksnyder** [comment]
Hi -- Not having seen your experiment with master/detail, I wonder if it matters whether one is modifying a child that already exists, or adding a new child (as in my case).  There is a repo illustrating this problem at https://github.com/ksnyder/ag-grid-demo/commits/nonet

Here are the steps:

1. change to the branch 'nonet'
2. npm run build && npm run serve
3. load app at localhost:3000
4. click on 'Grid' in upper right
5. notice that tenders that already have a bid display correctly -- click anywhere on the bid column to open the child
6. select the first tender that doesn't already have a bid (should be id 64), then click the button 'Enter/edit bids'
7. put some data in the form (don't have to complete all fields) and click 'Create Bid'
8. the console will log the new rowData as '==== rendering Grid with rowData', and there will be a separate log of tender 64, with the 'bids' property including the data you just created (new bid id of 1000), but no change in the grid is evident
9. the first problem is the leftmost column of the tender you bid on is not refreshed until you click on it (this calculation is done in the file grid.es6 colDef calling value getter function 'gridGetBidDisplay'
10.  the other problem is getNodeChildDetails is not called after this rowData change, so there is no way to expand the tender and see the new bid -- search the log for '==== getNodeChildDetails for record 64' and there will only be one match.  (Note that if you expand this log line after creating the bid, it will show the current state of the object as containing the bid)

Thanks for looking!

**Comment by seanlandsman** [comment]
Hi @ksnyder 

I'll be taking a look at this later in the week - I'll update as soon as I can

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Sorry for the late reply...

You should find that master/detail is going to get fully revamped in v14.2 coming up next week, you should find that in the new master/detail you don't have this issue...

I would suggest you wait until then..

Hope this helps
