### ISSUE TITLE
paginationChanged event works but webpack shows an error

### ISSUE THREAD

**Issue by Quentin-Rouquette** [ag-grid/ag-grid#1777]
**I'm submitting a : **
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Setting the "onPaginationChanged" event in GridOptions shows the error "Property 'onPaginationChanged' does not exist on type 'GridOptions'." but the callback is executed when pagination changes so the event exists. I guess it's missing from /dist/lib/entities/gridOptions.d.ts

Event is described here : https://www.ag-grid.com/javascript-grid-pagination/
but not here : https://www.ag-grid.com/javascript-grid-events/

**Expected behavior**

Webpack shouldn't show any error

**Minimal reproduction of the problem with instructions**

Just setting onPaginationChanged in GridOptions 

**Please tell us about your environment:**

Webstorm on Ubuntu 16.04, npm

* **ag-Grid version:** X.X.X

v 11.0.0

**Comment by seanlandsman** [comment]
Hi

I've taken a look and can see what you mean. I've raised AG-638 our side to track this - we'll update this thread with updates as soon as we have any

thanks

**Comment by rmc-software** [comment]
AG-638 has been fixed in v13.
