### ISSUE TITLE
One character missing from printable characters

### ISSUE THREAD

**Issue by salmanm** [ag-grid/ag-grid#1779]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The check implemented [here](https://github.com/ceolter/ag-grid/blob/627793f950380b0513cdfe32a08f6be85e020088/src/ts/utils.ts#L44) has a tiny tiny bug. One back slash is missing.

**Expected behavior**
It should have one more back slash `\` at 129th col. Otherwise cell editing doesn't start when user starts to type with `\` as the first character.

**Minimal reproduction of the problem with instructions**
Open the grid in some old browser which doesn't support `event.key`. Type `\` on a cell, it won't go into edit mode.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

I've taken a look and can see what you mean. I've raised AG-637 our side to track this - we'll update this thread with updates as soon as we have any

thanks

**Comment by ceolter** [comment]
i have put this in - but i can't test, as my browser doesn't use the code path. the code path is:

```
    static isEventFromPrintableCharacter(event: KeyboardEvent): boolean {
        let pressedChar = String.fromCharCode(event.charCode);
        if (_.exists(event.key)) {
            // modern browser will implement key, so we return if key is length 1, eg if it is 'a' for the
            // a key, or '2' for the '2' key. non-printable characters have names, eg 'Enter' or 'Backspace'.
            return event.key.length === 1;
        } else {
            // otherwise, for older browsers, we test against a list of characters, which doesn't include
            // accents for non-English, but don't care much, as most users are on modern browsers
            return Utils.PRINTABLE_CHARACTERS.indexOf(pressedChar) >= 0
        }
    }
```

anyway, what you say makes sense, so i've checked it in.

**Comment by JohnMasterson** [comment]
Just to confirm this was included in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
