### ISSUE TITLE
forEachNode - Inifnite Scroll 

### ISSUE THREAD

**Issue by diegoa1989** [ag-grid/ag-grid#1781]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I see in your documentation this part: 

forEachNode(callback) | Iterates through each node (row) in the grid and calls the callback for each node. This works similar to the 'forEach' method on a Javascript array. This is called for every node, ignoring any filtering or sorting applied within the grid. If pagination, then gets called for the currently loaded page. If using infinite row model, then gets called for each page loaded in the page cache.

**Expected behavior**
I am very interesting in the final part "If pagination, then gets called for the currently loaded page. If using infinite row model, then gets called for each page loaded in the page cache." I want to know How I gets called for each page loaded in the page cache, I follow your example "Example 2: Equal Pagination Page Size and Large Infinite Block Size". Thanks  

**Minimal reproduction of the problem with instructions**
I don't have example.  

**What is the motivation / use case for changing the behavior?**
Because When I use the forEachNode with a RowMemory it works very well but right now i need to change all the grid to Server Side and everything is work but the select node automatic no. 

**Please tell us about your environment:**
Windows 10. 

* **ag-Grid version:** 11.0.0

* **Language:** [ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
