### ISSUE TITLE
Add support for initial table state (columns, filters, sorting) in grid properties

### ISSUE THREAD

**Issue by danielpgross** [ag-grid/ag-grid#1785]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, it's not possible to pass initial state to the grid. By "initial state", I mean:
1. Column state (visibility, pinning, etc.)
2. Filter state
3. Sort state

Instead, this state must be set using the `setColumnState`, `setFilterModel`, and `setSortModel` methods on the grid API. When using a server-side row model, this results in unnecessary extra network requests and load time.

**Desired behavior**
It would be great to be able to pass in these state objects as grid properties when initializing the grid and have them be included in the initial grid rendering.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
Improve grid loading time and server load.

**Please tell us about your environment:**
Any

* **ag-Grid version:** 10.0.0

* **Browser:**
All

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by Arikael** [comment]
We needed the same functionality. Every grid had a dropdown and according to what the user chose (or not if initial) the grid loaded with different columns, sorting and filter. Additionally we translate all the columns.

Here's what I came up with (using angular and typescript). All of it is an GridService. The only drawback I faced so far was that I have to return `GridOptions` and not `Observable<GridOptions>`. 
My plan was to get the template first and upon receiving it return the GridOptions as an Observable. Unfortunately this did not work because ag-grids initialization was already finished before and so my 
onGridReady Event was never called. But since I can only access the api (to set filter etc.) from within this event I need this event.

We use `IDatasource` as a datasource

I left out our column translations. But if somebody is interested in it, I'll gladly insert it here.
```javascript
// method in our grid-service
 initGrid(options: {
    columnDefs: any,
    datasource: IDatasource,
    templateChooser?: OnGridTemplateChanged | GetGridTemplateChanged
  }, gridOptions?: GridOptions, onReadyEvent?: (params: GridReadyEvent) => void): GridOptions {

/* we have defined some default grid options which are used for every grid. 
They are merged together with the supplied options. 
It is important that you don't provide a datasource in the options. 
Otherwise you'll suffer from additional api calls. */
let mergedOptions = this.mergeWithDefaultGridOptions(gridOptions);
    
/* template chooser is just an interface which provides an Observable<GridTemplateSettings>. 
This holds the filtermodel, sortmodel and columnDefs and gets read from an http api. 
To mitigate users' waiting time the template settings are read as soon as possible 
and our Observable<GridTemplateSettings> is in fact a ReplaySubject so our service 
gets the current value no matter when it subscribes (pay attention to angulars DI here) */
    const getTemplateSettings = typeof options.templateChooser === 'function'
      ? options.templateChooser() : options.templateChooser;

    mergedOptions.onGridReady = (params: any) => {

      if (getTemplateSettings) {
        getTemplateSettings.onGridTemplateChanged.subscribe((gridTemplateSettings: GridTemplateSettings) => {
         /* this line is important if you change your grid template. 
For initialization (if you have not yet provided a datasource) you could leave it. 
As soon as you have provided a valid datasource every call to setColumnState, setFilterModel,
setSortModel will cause a call to datasource.getrows (and subsequently to your api) */
          params.api.setDatasource(null);

          if (!gridTemplateSettings) {
            params.api.sizeColumnsToFit();
          }
          else {
            params.columnApi.setColumnState(gridTemplateSettings.columnDefs);

            if (gridTemplateSettings.filterModel) {
              params.api.setFilterModel(gridTemplateSettings.filterModel);
            }

            if (gridTemplateSettings.sortModel) {
              params.api.setSortModel(gridTemplateSettings.sortModel);
            }
          }

          params.api.setDatasource(datasource);
        });
      }
    };

    return mergedOptions;
  }
```

Disclaimer: I haven't thoroughly tested it yet but it works so far. If you know a better way tell me :)

**Comment by vkuzel** [comment]
My hacky solution is based on swallowing get rows endpoint calls.

Idea is that, methods `setServerSideDataSource`, `setFilterModel` and `setSortModel` cause one call of get rows endpoint. So everything I have to do is ignore some of those calls.

```typescript
@Component(...)
export class AgGridComponent implements OnInit, AfterViewInit {

    @ViewChild('agGrid')
    private agGrid: AgGridAngular;
    private service: AgGridService;

    constructor(private httpClient: HttpClient) {
    }

    ngOnInit() {
        this.service = new AgGridService(this.agGrid, this.entityClassName, this.httpClient);
    }

    ngAfterViewInit() {
        this.service.initGrid();
    }

    selectLayout(gridLayout: GridLayout) {
        this.service.selectLayout(gridLayout);
    }
}

class AgGridService implements IServerSideDatasource {

    private requestsToIgnore = 0;

    constructor(private agGrid: AgGridAngular, private httpClient: HttpClient) {
    }

    initGrid(): void {
        this.httpClient.get('get-grid-config').subscribe((gridConfig: GridConfig) => {
            // We have grid configuration so let's set it up. Methods setServerSideDatasource,
            // setFilterModel and setSortModel cause get-rows endpoint to be called, so we have
            // to ignore two of those three calls.
            this.requestsToIgnore = 2;
            const gridOptions = this.agGrid.gridOptions;
            gridOptions.api.setColumnDefs(gridConfig.columnDefs);
            // Method setServerSideDatasource resets any filter or sort models so it has to be
            // called first.
            gridOptions.api.setServerSideDatasource(this);
            gridOptions.columnApi.setColumnState(gridConfig.defaultGridLayout.columnState);
            gridOptions.api.setFilterModel(gridConfig.defaultGridLayout.filterModel);
            gridOptions.api.setSortModel(gridConfig.defaultGridLayout.sortModel);
        });
    }

    selectLayout(gridLayout: GridLayout): void {
        // In this case we have to ignore only two calls.
        this.requestsToIgnore = 1;
        const gridOptions = this.agGrid.gridOptions;
        gridOptions.columnApi.setColumnState(gridLayout.columnState);
        gridOptions.api.setFilterModel(gridLayout.filterModel);
        gridOptions.api.setSortModel(gridLayout.sortModel);
    }

    getRows(params: IServerSideGetRowsParams): void {
        if (this.requestsToIgnore-- > 0) {
            params.failCallback();
        } else {
            this.httpClient.post('get-rows', params.request).subscribe(
                (rows: any) => params.successCallback(rows.data, rows.lastRow),
                () => params.failCallback()
            );
        }
    }

    destroy(): void {
    }
}

interface GridConfig {
    columnDefs: (ColDef | ColGroupDef)[]
    defaultGridLayout: GridLayout,
    gridLayouts: GridLayout[]
}

interface GridLayout {
    columnState: any,
    filterModel: any,
    sortModel: any
}
```

**Comment by Fiorello** [comment]
it would be convenient to have a method that simultaneously set sorts and filters so as not to make two queries

**Comment by hughanderson4** [comment]
Here's how I do it.

1. create a flag for `pauseRequests`.  if it is true then don't hit the server during `getRows()` callback.
2. restore state
3. clear the `pauseRequests` flag to permit fetching.
4. call `gridApi.refreshInfiniteCache()` and it will call my `getRows()`

```typescript
import { Component } from '@angular/core';
import { GridApi, GridReadyEvent, IGetRowsParams } from 'ag-grid-community';
import { DataGridPersistence } from './datagrid-persistence';

@Component({
    selector: 'ace-datagrid',
    templateUrl: './datagrid.component.html',
    styleUrls: ['./datagrid.component.scss'],
    host: { class: 'd-flex flex-column h-100' }
})
export class DataGridComponent {
    public gridApi: GridApi;

    private persistence: DataGridPersistence;

    getRows(params: IGetRowsParams): void {
        if (this.persistence.pauseRequests) {
            params.failCallback();
            return;
        }

        // call endpoint to get data
        // ...
        // .then((result: IDataResponse) => {
        //     params.successCallback(result.models, result.recordCount);
    }

    onGridReady(params: GridReadyEvent) {
        this.gridApi = params.api;
        this.persistence = new DataGridPersistence(params.api, params.columnApi);
        this.gridApi.setDatasource(this);
        this.persistence.restoreState();
    }
}
```
Here's the separate class I use for persistence concerns:

```typescript
import { ColumnState } from 'ag-grid-community/dist/lib/columnController/columnController';
import { GridApi, ColumnApi } from 'ag-grid-community';

export interface PersistedGridState {
    columnState: ColumnState[];
    filterModel: any;
    sortModel: {
        colId: string;
        sort: string;
    }[];
    rowCount: number;
};

export class DataGridPersistence {
    pauseRequests = true;

    constructor(private _gridApi: GridApi,
        private _gridColumnApi: ColumnApi) {
    }

    restoreState() {
        let state: PersistedGridState = this.getSavedGridState();

        this._gridApi.setFilterModel(state.filterModel || {});
        if (state.columnState) {
            this._gridColumnApi.setColumnState(state.columnState);
        }
        if (state.sortModel) {
            this._gridApi.setSortModel(state.sortModel);
        }
        if (state.rowCount) {
            this._gridApi.setInfiniteRowCount(state.rowCount);
        }

        setTimeout(() => {
            this.pauseRequests = false;
            // this is gonna make it do initial fetch with filtering and sorting
            this._gridApi.refreshInfiniteCache();
        }, 0);
    }
}
```

**Comment by acaravia** [comment]
I'm currently experiencing this issue since upgrading from v20 to v23. Didn't have an issue setting an initial filter in v20 but since upgrading to v23 I get a double hit. On top of that if you clear the filter and filter again on the same column it double hits again. Only on the same column as the initial filter was setup on. I'm initializing the filter by adding the following in the onGridReady function:

 ```
                let filterComponent = params.api.getFilterInstance("currentNumber");
                filterComponent.setModel({
                    type: "greaterThan",
                    filter: 0
                });
                params.api.onFilterChanged();
```

I  haven't attempted any of the workarounds yet but seems like this would be pretty standard request.

**Comment by adamkundrat** [comment]
> I'm currently experiencing this issue since upgrading from v20 to v23. Didn't have an issue setting an initial filter in v20 but since upgrading to v23 I get a double hit. On top of that if you clear the filter and filter again on the same column it double hits again. Only on the same column as the initial filter was setup on. I'm initializing the filter by adding the following in the onGridReady function:
> 
> ```
>                let filterComponent = params.api.getFilterInstance("currentNumber");
>                filterComponent.setModel({
>                    type: "greaterThan",
>                    filter: 0
>                });
>                params.api.onFilterChanged();
> ```
> 
> I haven't attempted any of the workarounds yet but seems like this would be pretty standard request.

have you solved this? we're experiencing exactly same issue

**Comment by acgrama** [comment]
Any new ideas about how to deal with this problem? Having to manage request state in the server-side datasource seems like a terribly fragile hack...

**Comment by domhaas** [comment]
Issue is still present in current v28.2.1
I'm currently avoiding it also with a hack to dismiss the first call to the getRows() function. Any update on this?

**Comment by rangyia** [comment]
Is this still not a feature?

**Comment by knovu** [comment]
Why is this closed?  Seems there are too many fragile solutions still for this.

**Comment by knovu** [comment]
**@zoheil-ag, we use the enterprise version, and we're wondering when/if this will be supported?** 

The current solution we have is semi-hacky, where we debounce all table calls, to allow for initial column state to be fired in an event in onGridReady.

I understand AG-Grid is "Performance First" so not introducing default column state like sorting/filtering etc makes sense.

**Comment by gandhis1** [comment]
I am also an enterprise subscriber, and I too think this is an essential feature. I would broaden this issue - what I would like to do is be able to save and load all grid state - this includes columns, column groups, pivot mode, sorting, filtering, aggregations, row group state, etc. - through some standard mechanism. From the perspective of the user, they should be able to close a tab, and open it back up, and see the exact same grid they saw before. The actual persistence mechanism is likely out of the scope of Ag-Grid, but the API to enable this shouldn't be.

Right now this is all possible, but only through a lot of boiler-plate code that hooks into certain grid events to save the state, and other grid events to load the state. This boiler-plate code can be error-prone, so having an official way to do it would be far better.

**Comment by zoheil-ag** [comment]
Hi @knovu and @gandhis1,

Thank you for your comments.

This is indeed something that is already on our radar. Apologies no corresponding label had been assigned to it, I updated that yesterday.

As mentioned, this Github issue itself is quite old and there have been numerous developments and changes to the grid since this was first discussed. At this point we can't commit to any timeframes or deadlines with regards to feature request simply due to structure of our work, however, if you are enterprise users I'd recommend using the [private ticketing](https://ag-grid.zendesk.com/) system to get direct support with any concerns you have.

Kind regards,
Zoheil
