### ISSUE TITLE
[Paste]Pasting Excel Data into Grid - Appending Rows

### ISSUE THREAD

**Issue by KrisWyb** [ag-grid/ag-grid#1786]
I'm submitting a feature request.

When pasting clipboard/Excel data into AG-Grid, how do I get the data to append to the current rows?
If my table currently has a single row and I'm trying to paste 10 rows into the table, Ag-Grid only overwrites the single row instead of appending the extra 9 rows. 
Can I use a grid Option or is this possible?

**Please tell us about your environment:**
 Windows7,8,8.1,10

* **ag-Grid version:** 
12.0.1 

* **Browser:**
 IE8+, Chrome 

* **Language:**
 [ES5,ES6]

**Comment by kvanlaan** [comment]
Thanks for posting @KrisWyb. I have encountered this problem as well.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
