### ISSUE TITLE
setPinnedBottomRowData() doesn't work with pivot

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1790]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When pivoting, setPinnedBottomRowData() doesn't pick up the generated pivot columnId (e.g. pivot_2).

**Expected behavior**
When pivoting and looping through gridOptions.columnApi.getAllGridColumns() to create the pinnedBottomRowData, I should be able to call setPinnedBottomRowData ([{pivot_2:100,...}]). 

**Minimal reproduction of the problem with instructions**
Try to setPinnedBottomRowData() on any pivoted grid

**Please tell us about your environment:**
All

* **ag-Grid version:** X.X.X
12.0.2

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Hi,

I see what you mean - I've created AG-654 our side to track this.

You can still set the actual underlying colId (not the generated one), but this would set it for all of these columns, not just the specific one you're trying.

We'll update this thread with updates as soon as we have any.

thanks

**Comment by rmc-software** [comment]
Hi,

Pinned rows now works with pivot columns in v13 due early next week.

You now specify the pivot column id rather than the field when using pivot columns (only):

`gridOptions.api.setPinnedBottomRowData([
        {
            'pivot_1': '1000',
            'pivot_2': '2000',
            'pivot_3': '3000',

            'pivot_5': '4000',
            'pivot_6': '5000',
            'pivot_7': '6000'
        }
    ]);`

Here is an easy way to show a footer containing the sum of all pivot columns:

`var rootNode = gridOptions.api.getDisplayedRowAtIndex(0).parent;
    gridOptions.api.setPinnedBottomRowData([rootNode.aggData]);`
