### ISSUE TITLE
Retrieve full state from agGrid / restoring an agGrid instance from state

### ISSUE THREAD

**Issue by erfangc** [ag-grid/ag-grid#1792]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no (obvious) Api to clone an instance of agGrid via a `RowModel` retrieved from another agGrid instance

**Expected behavior**
A property in `GridOption`, call it `fromExistingRowModel` that accepts a row model, effectively restoring state

Use case here:
Use show an instance of agGrid,
User navigate away (say via `react-router` - so the grid unmounts)
The user navigates **Back** and expects all of his RowGroup choices, column arrangements, sorts etc ... to be restored, and that we don't just instantiate a new grid

(If I am not mistaken, the `RowModel` object stores everything there is about the state of the Grid? If not ... what is the most comprehensive representation of state in agGrid? Apologizes if there are either simple or not well-formed questions

**Alternate Approach**

Right now in `AgGridReact.ts:49` you are instantiating the grid like so and throwing away the return value:
`new AgGrid.Grid(this.eGridDiv, this.gridOptions, gridParams);`

Can we somehow restore a previously instantiated state by getting this `AgGrid.Grid` instance in a callback ... so we can store them away somewhere and somehow revive the Grid in all of its glory even if the original component has been unmounted and a new component mounted in its place

**Minimal reproduction of the problem with instructions**
```typescript
class MyGridWraper extends React.Component {
  render() {
    const options = ...
    options.fromExistingRowModel = this.props.fromExistingRowModel || undefined
    <AgGridReact {...options}/>
  }
}
```

**What is the motivation / use case for changing the behavior?**
Use show an instance of agGrid,
User navigate away (say via `react-router` - so the grid unmounts)
The user navigates **Back** and expects all of his RowGroup choices, column arrangements, sorts etc ... to be restored, and that we don't just instantiate a new grid

**Please tell us about your environment:**
typescript, react

* **ag-Grid version:** X.X.X
12.0.2

* **Browser:**
all

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
