### ISSUE TITLE
Calculation of width for parent with non-integer size

### ISSUE THREAD

**Issue by fhurta** [ag-grid/ag-grid#1793]
**I'm submitting a ...**

    [X] bug report
    [ ] feature request
    [ ] support request

**Current behavior**
I'm trying to layout ag-grid into an element with flexbox layout. I noticed there is missing right border of the grid.

In Chrome developer tools I can see the size of my element is 975.531 x 336.813.

The injected grid's element (the one with css class "ag-bl-center ag-bl-full-height-center") has style="margin-left: 0px;width: 976px;".

**Expected behavior**
The calculation of width in ag-grid should be rather 975px.

**Please tell us about your environment:**

* **ag-Grid version:** 12.0.2

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

**Comment by seanlandsman** [comment]
Hi

Do you have an example of this? Looking at our examples I can see whole integers, but that's probably not an exhaustive test

thanks

**Comment by fhurta** [comment]
Hi, here's the [example](https://codepen.io/exavier/full/pryzOZ/).

It seems I got the fractional number by using `padding: 1.1em`. It is not in my code though, it comes from ngDialog component. 

Anyway, it could happen and perhaps the size calculation could be smart enough to cover such a situation?

Thanks!

**Comment by makinggoodsoftware** [comment]
This is tracked by AG-130 Check our pipeline https://www.ag-grid.com/ag-grid-pipeline/ for more information, thanks
