### ISSUE TITLE
[events] allow overriding of keyboard events

### ISSUE THREAD

**Issue by ceolter** [ag-grid/ag-grid#180]
allow overriding of keyboard events - eg if use doesn't want space to select, but do something else.

"This would be much more useful if there was a callback that happened on keyboard events, so that way we can get the behaviour we want. For example, maybe we don't want "space" to select, but rather if the user holds down the Shift key, that will automatically select. For things like this, it would be very useful to just provide a rich set of event hooks (such as OnKeyboardPress) that returns the same information as a regular keyboard event, and let people decide the actual user behaviour."

**Comment by erwin-beckers** [comment]
It would be great if mouse/keyboard selection works like the way you would expect it (by default)
and that we could override the behaviour by catching the keyboard event callbacks

MOUSE:
click = deselect all rows and select the current row
CTRL+click = select or deselect current row
shift + click = add all rows from previous selected row to current row to selection

KEYBOARD
HOME = goto first row
END = goto last row
cursor up/down = deselect all rows and select the current row
shift+cursor up = add previous row to selection
shift+cursor down = add next row to selection
SPACE = select or deselect current row
CTRL+SHIFT+HOME = select all rows from current position to top
CTRL+SHIFT+END = select all rows from current position to end

**Comment by idautocfator** [comment]
To accomplish accessibility in our app I would like to be able to tab into the grid and have any subsequent tab press blur the grid (on to the next priority element in view).

**Comment by stephanjust** [comment]
Going to bump this here due to the inconsistency between mouse and keyboard selection.

Clicking a cell selects the corresponding row. CTRL+clicking a cell toggles the rows selection state (multiselect). However, pressing space for any focused cell behaves like CTRL+clicking, meaning it toggles the state instead of deselecting other rows. I'd like space to behave just like clicks.

Considering people use these features already it's not feasible to change them, but allowing to override this behavior would be very useful.

**Comment by andrea-vega** [comment]
+1 for this.  I'd like to see behavior similar to google drive, and to be able to implement it without custom cellRenderers on each column definition.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-45

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by jordangotbaum** [comment]
Any updates on this? I see it's still in the backlog, but it's really important for allowing excel-like functionality. Would love to be able to use this feature.

**Comment by shrutikapoor08** [comment]
+1.
