### ISSUE TITLE
AG Grid writes to console "not supported"

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1801]
ag grid itself calls to InfiniteRowModel.prototype.isRowPresent wich displays this console message.

see callstack:
<img width="1880" alt="bildschirmfoto 2017-08-02 um 22 53 17" src="https://user-images.githubusercontent.com/364896/28894596-98592d78-77d5-11e7-822d-ab9e2b9952bd.png">

**Comment by seanlandsman** [comment]
Do you have a repo that demonstrates this problem?

**Comment by jogibear9988** [comment]
I use the Infinite Row Model and use the SetRowCount Method

**Comment by jogibear9988** [comment]
How can i create a sample? The Plunker Template from your "New Issue template" does not include aggrid!

**Comment by seanlandsman** [comment]
The new issue template is a template that people should follow when raising issues generally - ie a format they should use. As far as I'm aware there is no plunker template on it, unless we're talking about different things?

Either way, this plunker should serve as a good simple starting point: https://plnkr.co/edit/369YrrgCVrnPjD528OtT?p=info

thanks

**Comment by jogibear9988** [comment]
Look in the Raw Source: https://raw.githubusercontent.com/ag-grid/ag-grid/master/.github/ISSUE_TEMPLATE.md

**Comment by seanlandsman** [comment]
@jogibear9988 - that looks like a copy and paste bug! I'll update that - thanks for highlighting it

In fact I'll update all our github repos to have a valid/appropriate plunker link

**Comment by jogibear9988** [comment]
Demo of the issue: https://plnkr.co/edit/DO96MHCuZWIDRSCGKeGh?p=preview
Scroll in the grid and look at the console, the message should pop up at some time

**Comment by jogibear9988** [comment]
for me it happens if i click in grid, and scroll via mouse

**Comment by seanlandsman** [comment]
Thanks for raising this. I've raised AG-667 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by ceolter** [comment]
fixed. will be in next release.
