### ISSUE TITLE
GroupCellRenderer have no 'refresh' method implemented

### ISSUE THREAD

**Issue by catahoc** [ag-grid/ag-grid#1805]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When user invoke gridApi.refreshCells(), GroupCellRenderer is fully redrawn (removed and inserted back). It's overkill, because its state rarely changes on refresh. It takes 5ms to re-create this cell and this may be huge load on CPU when grid is refreshed frequently and other user cells have 'refresh' implemented

**Expected behavior**
GroupCellRenderer have 'refresh' method (and this method returns 'true' in v12+)

**Minimal reproduction of the problem with instructions**
Make grid with 50 rows and 20 columns (one of them is Grouping column). Start refreshing Grid each 50-200ms and profile resulting performance. You will see, that most time is taken by GroupCellRenderer.init 

**What is the motivation / use case for changing the behavior?**
For frequently updated grids with grouping enabled, GroupCellRenderer became performance bottleneck.

**Please tell us about your environment:**
Windows, Chrome 56+, angular 4

* **ag-Grid version:** 10.0.1
This is still an issue in 12+, but API changed - now GroupCellRenderer.refresh returns false

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

* **Language:** TypeScript 2.3.2

**Comment by catahoc** [comment]
I have also found, that refreshing cells without cellRenderer leads to cell recreation:
* remove previous cell content
* append new content 
* apply ColDef.cellStyles
* apply ColDef.cellClass
* apply ColDef.cellClassRules

I bet that it will be faster to perform some aka 'refresh' mechanism for those cells 
* don't re-create internal elements, just change their text content
* don't apply cellClass/cellStyle - as done for cellRenderers with 'refresh'

**Comment by catahoc** [comment]
I'm not sure my workarounds will work for all or most cases, but they work for me

Workaround for GroupCellRenderer:
```
// performance hack: support fast refresh for GroupCellRenderer
GroupCellRenderer.prototype.refresh = x => true;
```

Workaround for cells without renderer - don't use columns without renderer, use StubComponent where possible:
```
@Component({
    selector: 'stub-cell',
    template: '{{field}}',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class StubComponent implements AgRendererComponent {
    field: any;

    constructor(private readonly changeDetector: ChangeDetectorRef) {
    }

    agInit(params: ICellRendererParams) {
        this.refresh(params);
    }

    refresh(params: ICellRendererParams) {
        this.field = params.valueFormatted || params.value;
        this.changeDetector.markForCheck();
    }
}

```

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid this will only work if you don't have an innerRenderer, if this works for you, it's fine, but in our case I am afraid that we need to cater for more edge scenarios so that's why we have decided not to implement the method and let the group always be created.

We take the feedback on board though and we will make a not to try to implement this method so that it works in all the edge cases since as you say will improve performance, but at this time I am afraid we are going to close this issue since we are not going to put any immediate effort into looking at this.

Thanks
