### ISSUE TITLE
Add gridOption for supressing column menu

### ISSUE THREAD

**Issue by Amerzel** [ag-grid/ag-grid#1806]
I'm submitting a
[x] feature request

I'd like to turn off the grid column menu. I could previously do that by setting suppressMenuFilterPanel, suppressMenuMainPanel, and suppressMenuColumnPanel. In order to turn this feature off completely I now have to set the menuTabs property on every individual column. This is a lot less convenient than just being able to turn the feature off completely.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
