### ISSUE TITLE
Method for autoSizing columns based on header and cell contents

### ISSUE THREAD

**Issue by kvanlaan** [ag-grid/ag-grid#1808]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The autoSizeColumns() method only autosizes columns based on their cell contents. This is a problem because if the columns header is longer than its cell content, it will overflow. 

Setting a minWidth is not the solution because it requires you to know the length of your longest label. I am working with a lot of grids whose labels are loaded dynamically, and may be translated into different languages.
**Expected behavior**

I would like a way to autosize the columns based on header and cell contents.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I need to autosize columns smoothly.
**Please tell us about your environment:**

VsCode
* **ag-Grid version:** X.X.X

ag-grid-enterprise@^12.0.0:

* **Browser:**

All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

All

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
