### ISSUE TITLE
Tree data expands but does not collapse last row

### ISSUE THREAD

**Issue by jonfreedman** [ag-grid/ag-grid#1809]
I'm submitting a bug report.

**Current behavior**
We are using AgGridReact to display an array of objects which contain an `id` property.  The `getNodeChildDetails` function for data with children returns an array of objects each with an `id` property with the same value as the parent.  We also have a `getRowNodeId` function which returns the value of this `id` property.
If I set both the following properties on gridOptions the last item in our grid can expand to display the child rows but attempting to hide them leaves them visible.  Other rows with child data expand and collapse fine.
```
            getRowNodeId: this.getRowNodeId,
            getNodeChildDetails: this.getNodeChildDetails,
```
If I comment out the getRowNodeId function, or do not set the id property on the child rows, this last data row will also collapse.

**Expected behavior**
Grid should behave the same with or without getRowNodeId function set.

**Minimal reproduction of the problem with instructions**
[Modified source for Simple Tree Data Example](https://github.com/ceolter/ag-grid/files/1199728/exampleTree.txt) - comment out line 34 to see change in behavior.

* **ag-Grid version:** 12.0.2

* **Browser:** 
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET CLR 1.1.4322; .NET4.0E; MS-RTC LM 8; rv:11.0) like Gecko

**Comment by seanlandsman** [comment]
getRowNodeId needs to provide a unique id per row - as it stands in your example the id isn't unique

Changing it to return a unique id will fix your issue:

```
function getRowNodeId(rowItem) {
    return rowItem.group + rowItem.id;
}
```
