### ISSUE TITLE
Wrong typescript definition for valueGetter (does not allow expression)

### ISSUE THREAD

**Issue by dzonatan** [ag-grid/ag-grid#1810]
**I'm submitting a ...**
```
[X] bug report
```

The latest `ColDef` interface does not allow to use expression for [valueGetter](https://github.com/ag-grid/ag-grid/blob/master/src/ts/entities/colDef.ts#L84), expects only a function. Though documentation tells that you can use expression here.

* **ag-Grid version:** 12.0.2
* **Language:** [TypeScript 2.3.3]

**Comment by rmc-software** [comment]
Expressions are still allowed, although the interface is ambiguous.

I've changed it to:

 `/** Expression or function to get the cells value. */
    valueGetter?: ((params: ValueGetterParams) => any) | string;

    /** If not using a field, then this puts the value into the cell */
    valueSetter?: ((params: ValueSetterParams) => boolean) | string;`

This will be available in the next release.
