### ISSUE TITLE
Unable to edit row node when using master/details

### ISSUE THREAD

**Issue by barriber** [ag-grid/ag-grid#1811]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We are using ag-grid with react and immutable.js
When trying to inline edit the updateRowData of InMemoryNodeManager it doesn't reflect changes due to isRowsAlreadyGrouped witch returns true for grouped row

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
As per the issue template please provide a reproducible example for issues, as well as completing the other fields

As this is for react, can you please raise any react related issues here: https://github.com/ag-grid/ag-grid-react
