### ISSUE TITLE
Lack of items added/removed event for UpdateRowData method

### ISSUE THREAD

**Issue by dzonatan** [ag-grid/ag-grid#1812]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

Since `addItems` and `removeItems` methods were deprecated in favor `updateRowData` the `itemsAdded` and `itemsRemoved` events are not broadcasted anymore. Neither `rowDataChanged` so it's hard to keep track of whats changed in grid.

* **ag-Grid version:** 12.0.2

**Comment by seanlandsman** [comment]
Hi,

updateRowData will return whats changed - you should be able to use this return value to determine whats changed within the grid

**Comment by dzonatan** [comment]
But.. what if I need to know what is changed without knowing anything about who is doing that?
Lets say we have two components that both have a reference to the grid:
But those components don't know about each other. 
First one keeps track of whats changed.
Second one changes the data.


Simple real case scenario is "actions column" where you can delete a row. And you still want to know what is deleted from the page.

**Comment by dzonatan** [comment]
@seanlandsman any comments on this?

**Comment by mspoerer** [comment]
@dzonatan I am running in the same problem -  

>>> Simple real case scenario is "actions column" where you can delete a row (but you're doing that internally in grid). And you still want to know what is deleted from the component you use that grid. <<<

Have you found a solution?
