### ISSUE TITLE
Number filter 'lessThanOrEqual' behaves like 'lessThan'

### ISSUE THREAD

**Issue by phaniallamsetty** [ag-grid/ag-grid#1814]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
'lessThanOrEqual' and 'greaterThanOrEqual' filters behave like 'lessThan' and 'greaterThan' respectively

**Expected behavior**
'lessThanOrEqual': If the filter value is 5, the records should be less than or equal to 5
'greaterThanOrEqual': If the filter value is 5, the records should be greater than or equal to 5

**Minimal reproduction of the problem with instructions**
1. Open the filter dropdown of a number filter which has 'lessThanOrEqual' as one of the filter parameters
2. Select 'Less than or equals' and enter a filter value

**Please tell us about your environment:**

Windows 10, Visual Studio

* **ag-Grid version:** 3.3.3

* **Browser:**
Chrome

* **Language:** Javascript

**Comment by phaniallamsetty** [comment]
The coldef for that column is: 

{
    headerName: '<h2>Rating</h2>', 
    field: 'Rating', 
    filter: 'number',
    onCellClicked: RateItPopUp,
    cellRenderer: function (params) {
               return RatingRenderer(params);
     }
}

**Comment by seanlandsman** [comment]
I'm afraid I cant reproduce this on our side - taking https://www.ag-grid.com/javascript-grid-filtering#filter-and-events-example as an example I can filter on the medal columns (bronze etc) as expected

If you can provide a reproducible example for this I'm happy to take a look and reopen if necessary

thanks
