### ISSUE TITLE
Grid not loading in IE 11 with compatibility set to IE 10

### ISSUE THREAD

**Issue by nlvraghavendra** [ag-grid/ag-grid#1815]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ag-grid component is not working in IE 11 when compatibility mode is set to IE 10 using the below tag - 

`<meta http-equiv="X-UA-Compatible" content="IE=10">`

Couple of things that are not working - 

1. Filter by field
2. Creating a grid with header groups

**Expected behavior**

ag-grid to load properly in IE 11 with compatibility mode set to IE 10

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
I'm using ag-grid inside SharePoint 2013 pages. Windows 10 is the operating system.

* **ag-Grid version:** 12.0.2

* **Browser:**
"Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; InfoPath.3)"

* **Language:** JavaScript

**Comment by nlvraghavendra** [comment]
I tried debugging the code and found that __proto__ is not supported in < IE 11. Any clues related to this?

**Comment by nlvraghavendra** [comment]
I just realized that 11.0.0 is working fine without any issues. I've attached a screenshot of the issue in IE dev toolbar with stacktrace.

My observations - 

1. When a new object is created I don't see `__proto__` getting created
2. Tracking the stack trace I see that in `Component.prototype.wireQuerySelectors` method `thisProto` is `null` because of point 1 above and the method exits without doing anything

![ag-grid-ie-11](https://user-images.githubusercontent.com/309293/29125196-1952f2ac-7ce9-11e7-9c81-98f20a34b711.jpg)

**Comment by rmc-software** [comment]
Thank you for reporting this, we have created AG-688 to track this and assigned it highest priority.

**Comment by pk910** [comment]
just dropping this here...

```
(function(Object, Function) {
    //* IE10 environment feature upgrade
    // i don't know who the hell on ag-grid side thought it would be a good idea to rely on Object.prototype.__proto__
    // __proto__ has ALWAYS been a very very VERY VERY VERY.... BAD CODE STYLE! 
    // the DEV implemented that should be fired INSTANTLY because he/she has no idea of javascript (and especially javascript performance) at all!
    // not only the official documentations show BIG RED WARNINGS of using __proto__: 
    //   https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto
    // there are better supported alternatives like Object.prototype.getPrototypeOf:
    //   https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf
    //
    // i know my hack is a very dirty modification to the IE<=10 environment...
    // thank you ag-grid for that shit and all the side effects coming out of it! i wish you burn in hell -.-
    //
    // same applies to Function.prototype.name  (which is not even supported on IE>10 - did you completely drop IE support???)
    //
    var propdef;
    
    // Object.prototype.__proto__
    if(!('__proto__' in Object.prototype)) {
        propdef = {
            configurable: false,
            enumerable: false,
            get: function() {
                //console.log("called getter for Object.prototype.__proto__");
                return Object.getPrototypeOf(this);
            }
        };
        if(typeof Object.setPrototypeOf !== "undefined") {
            propdef.writable = true;
            propdef.set = function(value) {
                return Object.setPrototypeOf(this, value);
            };
        }
        Object.defineProperty(Object.prototype, '__proto__', propdef);
    }

    // Function.prototype.name
    if(!('name' in Function.prototype)) {
        propdef = {
            configurable: false,
            enumerable: false,
            get: function() {
                var fn = this;
                //console.log("called getter for Function.prototype.name");
                if(typeof fn.__name !== "undefined")
                    return ;
                var match = ("" + fn).match(/^\s*function\s+([^\(\s]*)\s*/);
                fn.__name = match ? match[1] : "";
                return fn.__name;
            }
        };
        Object.defineProperty(Function.prototype, 'name', propdef);
    }
        
})(window.Object, window.Function);
```

**Comment by rmc-software** [comment]
AG-688 has now been fixed and will be in v13 due early next week.

**Comment by anatolyg** [comment]
@pk910 thanks for posting this. I had an issue w/ exactly the same issue, using `constructor.name` in IE11 yielded undefined, and it just happened to work in a bunch of places by luck. I've verified that the fix above fixes IE11 issues w/ v13 of AG-GRID
