### ISSUE TITLE
responsive column hide - ag-Grid-Enterprise

### ISSUE THREAD

**Issue by 1453alabanda** [ag-grid/ag-grid#1816]
merhabalar, Ag-grid kolonları üzerinde bootstrap hidden-xs, hidden-sm gibi css sınıflarını kullanamıyor muyuz? mobil cihazlarda bazı kolonların gizlenmesini istiyorum. ingilizcem yetersiz olduğu için, çeviri üzerinden yazıyorum. teşekkürler

Hello, do we not use css classes like bootstrap hidden-xs, hidden-sm on Ag-grid columns? I want some columns hidden on mobile devices. I write over translation because english is insufficient. Thank you

**Comment by seanlandsman** [comment]
You'll need to hide/show columns yourself depending on screensize

Have a look at https://www.ag-grid.com/javascript-grid-responsiveness/
for example of this - it would have to be something you do programatically I'm afraid

**Comment by 1453alabanda** [comment]
Thank you, I studied the example you gave. But that's not exactly what I want.

Teşekkür ederim, verdiğiniz örneği inceledim. fakat tam istediğim bu değil.

**Comment by seanlandsman** [comment]
Hi - if you're an enterprise customer can you please post in our members forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

We'll be able to assist you further there. If you don't have access please register on the forum and then contact accounts@ag-grid.com who will grant you access.
