### ISSUE TITLE
Export to excel as .xlsx not .xls as default

### ISSUE THREAD

**Issue by jonfreedman** [ag-grid/ag-grid#1818]
**I'm submitting a feature request**

**Current behavior**
When exporting to Excel the file format produced is .xls

**Expected behavior**
When exporting to Excel the file format should be .xlsx

**What is the motivation / use case for changing the behavior?**
As well as the issue mentioned in [the documentation](https://www.ag-grid.com/javascript-grid-excel/?framework=react#exportToXlsx) there is also a data security implication in producing .xls files.  .xlsx is guaranteed to not contain any macro code so can be safely opened while the same is not true for .xls (see https://www.realdata.com/blog/file-types-in-excel-2007/)

**Comment by seanlandsman** [comment]
Hi

I'm afraid we won't be adding support for XLSX anytime soon, primarily doing is much more complicated than XLS. 

We don't rely on any third party libraries but you could use existing ones that support XLSX and use them yourself in order to provide this support

thanks
