### ISSUE TITLE
Ag-Grid should dynamically add rows to accommodate paste from clipboard

### ISSUE THREAD

**Issue by kvanlaan** [ag-grid/ag-grid#1820]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If one pastes data from excel into a grid, and the number of rows exceeds those available in the grid, the grid will not add rows to accommodate. 
**Expected behavior**

The grid should automatically add rows based on the length of the clipboard data. Ideally this would option could be turned on via a field on the gridOptions.

**Minimal reproduction of the problem with instructions**

Try to paste data that is longer than the number of rows available in the grid. Either in total, or remaining from the point where paste begins.

**What is the motivation / use case for changing the behavior?**

Users will not need to make sure to have the exact number of available rows when pasting from excel.
**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Roh-codeur** [comment]
I would like this feature too, any updates on when and if this will be available

**Comment by bernarddk** [comment]
Also require this feature

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by tomSny** [comment]
+1 needed feature.

**Comment by drewe** [comment]
Would love to see this!

**Comment by toomanyjoes** [comment]
+1

**Comment by kristian2x** [comment]
+1 from an enterprise user

**Comment by bhushanon** [comment]
+10 from an enterprise user

**Comment by asherrna** [comment]
keep in mind this could be more complicated than what you need because I need to be able to detect what columns I'm pasting into

```ts
    const processDataFromClipboard = (params: ProcessDataFromClipboardParams) => {
        if (!gridOptions.api || !gridOptions.columnApi) return null;
        const numRows = gridOptions.api.getDisplayedRowCount();
        const selectedColumn = gridOptions.api.getCellRanges()[0].columns[0];
        const selectedRowIndex = gridOptions.api.getCellRanges()[0].startRow!.rowIndex;
        const selectedColIndex = gridOptions.columnApi?.getAllColumns().findIndex(c => c.getColId() === selectedColumn.getColId());
        const relevantColumns = gridOptions.columnApi?.getAllColumns().slice(selectedColIndex);

        // if we have more than 1 row on our clipboard, then we'll have a new line at the end that we need to trim off
        if (params.data.length > 1) params.data.pop();
        const inputRows = params.data;

        // build an add transaction to set add the appropriate number of blank rows
        // add one additional row so that there's always room to paste again
        // do not use Array.fill() because it gives each filled row the same object by reference
        if (selectedRowIndex + inputRows.length >= numRows) {
            const arr = new Array<{}>();
            for (let i = 0; i < selectedRowIndex + inputRows.length + 1 - numRows; i++) {
                arr.push({});
            }
            const addTransaction = {
                add: arr,
            };
            gridOptions.api.updateRowData(addTransaction);
        }

        // now that we know we have enough rows, build an update transaction that will replace relevant rowData
        // this can't be combined into the same transaction because when combined, the update happens first
        let startColumn = "";
        let endColumn = "";
        const rowsToUpdate: Array<{}> = [];
        gridOptions.api.forEachNode((rowNode, i) => {
            if (i >= selectedRowIndex && i <= selectedRowIndex + inputRows.length - 1) {
                const data = rowNode.data;
                const inputRow = inputRows[i - selectedRowIndex];
                inputRow.forEach((value, colIndex) => {
                    if (relevantColumns[colIndex]) {
                        const field = relevantColumns[colIndex].getColId();
                        if (!startColumn) startColumn = field;
                        endColumn = field;
                        data[field] = value;
                    }
                });
                rowsToUpdate.push(data);
            }
        });
        const updateTransaction = {
            update: rowsToUpdate,
        };
        gridOptions.api.updateRowData(updateTransaction);

        // because we aren't using the built in paste functionality then we need to manually reselect the pasted range
        gridOptions.api.clearRangeSelection();
        gridOptions.api.addCellRange({
            rowStartIndex: selectedRowIndex,
            rowEndIndex: selectedRowIndex + inputRows.length - 1,
            columnStart: startColumn,
            columnEnd: endColumn,
        });

        // return null to ignore the built in paste functionality
        return null;
    };
```

**Comment by michelalbers** [comment]
+1 from here too :)

**Comment by crotten** [comment]
+1 from an enterprise user

**Comment by KeshavGeek** [comment]
+1 from an enterprise user

**Comment by ChinW** [comment]
+1 from (an enterprise user)

**Comment by kiril-matev** [comment]
Hello @kvanlaan!

Thank you for bringing this up with us. 

Clipboard support is functionality only available in AG Grid Enterprise which requires a license. As a licensed AG Grid Enterprise user, you can sign up for our support portal and submit questions there - please see our website for more information.

The functionality you described wasn't part of the requirements when we built this feature. However, you can implement this in user code by handling the AG Grid event to process the pasted data and adding new rows to the grid as needed to fit the extra pasted rows. Please use the approach shown here:
https://plnkr.co/edit/Enc1n9j19H6BonDO 

We agree this will be useful to have as a built-in capability. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-1685 [Clipboard] Allow adding new rows dynamically if needed to fit all the pasted rows**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by toomanyjoes** [comment]
@kvanlaan is dead. RIP circa late Aug 2021. It is rumored her last words were "I waited 4 years and they never added dynamic rows to Ag-grid nor so much as replied to me". Tragic, but I'm sure she would be happy to know you guys are almost sorta kinda thinking about doing this 5 years later.
