### ISSUE TITLE
clarify if the colDef type is unknown

### ISSUE THREAD

**Issue by dimitropoulos** [ag-grid/ag-grid#1821]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

make a column definition with 
```
{
  type: 'text'
}
```
but don't define any `columnTypes` on gridOptions

**Expected behavior**

an error that tells you the columnType `text` was not found, and it definitely shouldn't take that to crash the grid (which, it did in my case)

**Minimal reproduction of the problem with instructions**

see the above, you get an error like

```
Uncaught (in promise) TypeError: Cannot read property 'text' of undefined
```

**What is the motivation / use case for changing the behavior?**

I spent way more time that I would have liked to to track this simple typo down.  In my case, the column def was from before types were even implemented, so I know this was just me trying to write `filter: 'text'`.  upon upgrading the grid, it crashed and I couldn't figure out why: this was the problem.

**Please tell us about your environment:**

* **ag-Grid version:**

12

* **Browser:**

chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Flow

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-679 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by deathmoves** [comment]
Improved error handling when Column Types are not correctly configured has been included along with support for an array of ColumnType keys, i.e. string[] as part of AG-695 and AG-679.

These enhancements will be included in our next release v13 expected early next week.

**Comment by rmc-software** [comment]
Improved error handling when Column Types are not correctly configured has been included along with support for an array of ColumnType keys, i.e. string[] as part of AG-695 and AG-679.

These enhancements will be included in our next release v13 expected early next week.

**Comment by dimitropoulos** [comment]
thanks!
