### ISSUE TITLE
Display value instead of grouping on null

### ISSUE THREAD

**Issue by tejashande** [ag-grid/ag-grid#1823]
Show value instead of grouping on null in ag-grid.

I want to display the value instead of grouping those in null.
**
For eg:
>Level 1 
               >doc 
                >Level 2
                                >doc
                                >Level 3
                                                >doc
                                                > level 4
                                                                >doc
                                                                >doc

**
I can't see any option to implement this in ag-gird.

Please let me know if anyone came across similar thing.

Thanks in Advance!!!

**Comment by seanlandsman** [comment]
As per the issue template, please dont use github for support.

Either post your query on stackoverflow, or if you're an enterprise customer on our members forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

thanks
