### ISSUE TITLE
React CellRenderer is being destroyed and recreated instead of firing it's refresh method.

### ISSUE THREAD

**Issue by Kelnor277** [ag-grid/ag-grid#1827]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
React CellRenderer is being destroyed and recreated instead of firing it's refresh method.

**Expected behavior**
Expected ChartCellTest.refresh() to get called instead of the component being destroyed and recreated.
Using chrome dev tools the ChartCellTest constructor is called on every refresh.

From documentation 
"You have the option of handling refresh or not by either providing a refresh() method on your React component or not. If not present, then the grid will destroy your component and create a new one if it tries to refresh the cell. If you do implement it, then it's up to your React components refresh() method to update the state of your component."

**Minimal reproduction of the problem with instructions**

The CellRenderer component:
```
class ChartCellTest extends React.Component{
    constructor(props, context) {
        super(props, context);
        // this.boundResize = this.resizeOrScroll.bind(this);
        this.dataChanged = false;
    }
    refresh(params){
        return true;
    }
    render(){
        return(<div key="chart-div" ref="chart" className={"chart-div"}/>)
    }
}
```

Table component:

```
class Table extends React.Component{
    constructor(props, context){
        super(props, context);
        this.defaultColumns = [
            {
                headerName: 'Check Information',
                headerGroupComponentFramework: HeaderComponent,
                groupId: 'checkInfo',
                marryChildren: true,
                children:[
                    {headerName: 'Matched Trends', valueGetter: Table.seriesGetter, cellRendererFramework: ChartCellTest, width: 650},
                    {headerName: 'Failed Trends', valueGetter: Table.seriesGetter, cellRendererFramework: ChartCellTest, width: 650}
                ]
            }
        ];
        this.state = {
            columns: this.defaultColumns,
        };
    }

    static seriesGetter(params){
        return {series: [[]], jobs: [], modified: []}
    }

    render(){
        return(
            <div className="ag-fresh">
                <label htmlFor="dateSorted">Sort Jobs By Date</label>
                <div style={{height: 'calc(100vh - 310px)'}}>
                    <AgGridReact
                        key="grid"
                        suppressCellSelection={true}
                        suppressDragLeaveHidesColumns={true}
                        enableFilter={true}
                        rowHeight={200}
                        enableColResize={true}
                        enableSorting={true}
                        columnDefs={this.state.columns}
                        rowData={this.props.data}
                        suppressScrollOnNewData={true}
                    />
                </div>
            </div>
        )
    }
}
```
A parent component pulls and formats some data and then passes it to Table as a prop "props.data"
Every time this data object changes the grid creates a new ChartCellTest instead of calling ChartCellTest.refresh().

It's possible I'm not implementing the refresh method properly?

**Please tell us about your environment:**
MacOS Chrome

* **ag-Grid version:** X.X.X
    "ag-grid": "^12.0.2",
    "ag-grid-react": "^12.0.0",

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by seanlandsman** [comment]
Hi,

I can see the confusion here - the refresh method is utilised when individual row or cells are updates via the API for example (using api.refreshCells for example).

When you use api.setRowData or the equivalent here (rowData={this.props.data}) then the entire data set is replaced.

Having taken a look at the documentation I don't believe that this is clear enough, so will update it to reflect this, which is especially relevant for frameworks that support binding (like react, or angular) in this way.

I suggest you take a look at the docs here around data updating: https://www.ag-grid.com/javascript-grid-data-update#delta-row-data

I think this option would be of most help in your scenario.

Again, I think it's worth us (ag-grid) highlighting this in the docs - I'll add a jira to do so over the next week or so

thanks

**Comment by Kelnor277** [comment]
Ah thanks, that makes sense. I'll see if I can use the method you posted.

One point though. If I understand React's paradigm correctly. It bases its updates on prop passing, immutability and reference equality. Ie. You need to make sure the rowData: this.props.data is a different object to cause React to push an update, but you can keep the children of the data object the same as previous iterations to keep other child components from updating unnecessarily. It seems like it might be worth letting rowData be updated but still keep child components around and let them decide if they need to update based on the prop (in this case params from the Ag-Grid framework) changes?

**Comment by Kelnor277** [comment]
Ok I understand, was just wondering if it was worth making the React version conform to what a React dev would expect. I understand if it's not.
