### ISSUE TITLE
Minimum Length on Filters

### ISSUE THREAD

**Issue by Keki91** [ag-grid/ag-grid#1828]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**
I'd like the ability to be able to add a minimum length to a filter prior to it submitting a HTTP request. One of our queries is fairly heavy regarding users and searches over all potential fields on their name in AD, if we send through a letter "A" as a filter, it brings back thousands of potentials. 

Right now we're preventing it server side but this isn't ideal and we'd prefer to skip the post complete.

`filterParams: {
          minLength: 5
        }`

**What is the motivation / use case for changing the behavior?**
Allow better client side filtering rules prior to sending HTTP requests.

* **ag-Grid version:** 12.0.2

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
