### ISSUE TITLE
How set render all row one time

### ISSUE THREAD

**Issue by Aofhero** [ag-grid/ag-grid#1829]
I need load All row or all data once time
currently i'm scrolling and display slowly 
I don't want sort col or order data and no change data model
My max row is 200 row

Thanks.

**Comment by seanlandsman** [comment]
Hi

As per the issue template please dont post support requests here. Either use stackoverflow or our members forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) for support queries.

By default the entire dataset should appear in the grid. If the grid is smaller than the number of rows you will need to scroll. If you're using anything other than the default row model then more steps may be required to display the full data set
