### ISSUE TITLE
'No Rows To Show' overlay not showing when no data in Infinite Scrolling Row Model

### ISSUE THREAD

**Issue by cliffsun91** [ag-grid/ag-grid#1830]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request => 
```

**Current behavior**
When using the infinite scrolling row model, if the datasource returns no rows ([]), i.e. the successCallback is called with an empty array, then the grid doesn't show any rows (expected) but it also doesn't show the 'No Rows To Show' overlay.

**Expected behavior**
We expect that the 'No Rows To Show' overlay to be shown when there is no data return from the datasource.
I understand that with the infinite scrolling row model has the concept of a cache and that the cache can contain 1 or more blocks. But I think if the first block request (where this.blockNumber == 0 in RowNodeBlock) returns no data then we can assume that there are no rows for that request and we can show the overlay.

**Minimal reproduction of the problem with instructions**
Setup a grid with the infinite scroll model (we're using it with pagination but believe the issue isn't related to pagination specifically). In your datasource getRows method just call the successCallback with empty array and 0: `params.successCallback([], 0)`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Doing it via the React wrapper

* **ag-Grid version:** X.X.X
Version 12.0.2 

* **Browser:**
Currently tested in Chrome only

* **Language:** ES6

**Comment by cliffsun91** [comment]
In addition, I've found that when using the Infinite Scrolling Row Model with pagination that the loading overlay doesn't show when traversing pages, instead we get a blank grid whilst the data is being fetched from the server. This doesn't look as good as it used to.

**Comment by seanlandsman** [comment]
For the second part, as Niall says you can use this:

```
        cellRenderer: function(params) {
            if (params.value !== undefined) {
                return params.value;
            } else {
                return '<img src="../images/loading.gif">'
            }
        }
```

For the first item (and in fact as an alternative for the second) you can use the overlay API to display the overlay when there is no data (or when loading) - please see https://www.ag-grid.com/javascript-grid-overlays/ for more information

I have raised AG-690 in the meantime to ensure the overlay behaviour is consistent across row models

**Comment by cliffsun91** [comment]
Thanks - I've used the workaround to explicitly call the showNoRowsOverlay() when our fetching returns 0 rows. Getting the loading overlay to show is possible but requires more effort (I would have to know when the next block/page is being requested - ideally after pressing the pagination controls). 

Having consistent overlay behaviour across row models would be great - especially when pagination is used in the infinite scrolling model.

**Comment by jtkDvlp** [comment]
Same here, please fix it

**Comment by jtkDvlp** [comment]
loading overlay also does not seem to work

**Comment by ceolter** [comment]
i've looked into this, and the behaviour is consistent. this is because the filtering is done on the server side in infinite row model.

in the In Memory Row Model, when you have rows, and you then filter to remove all rows, no overlay is displayed.

in Infinite row model, this is what is modelled to be consistent. a 'no rows' result goes down the path as 'all results are filtered out' (which may or may not be true, but the grid doesn't know that).

here is a plunker showing how to achieve this behaviour:
https://plnkr.co/edit/geLmjDtJK1GOJW891nw9?p=preview

**Comment by FortinFred** [comment]
@ceolter 
I'm quite new to ag-grid but stumbled on the same issue and find it counter intuiative.

My first expectation was that a user would get a showNoRowsOverlay (both from server-side or memory datasource) when filtering out all data.

Perhaps there's a distinction to be made between no rows found and no row matching filters.

Something in the line of a `showNoMatchOverlay`

**Comment by fuguelike** [comment]
@ceolter  
I agree, the divergence in behavior between SSRM and CSRM is misleading, as are the docs about this feature. And it is cumbersome to have to manually call API methods to achieve this.

There may be a technical distinction between no rows supplied to the grid, and no rows as a result of filtering, but wouldn't the no rows overlay be appropriate for end users in either case?
