### ISSUE TITLE
Missed export int main.d.ts (SerializedTextFilter)

### ISSUE THREAD

**Issue by azakrytnoi** [ag-grid/ag-grid#1831]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

SerializedTextFilter is not exported in main.d.ts

**Expected behavior**

SerializedTextFilter is exported, similar to SerializedNumberFilter

**Minimal reproduction of the problem with instructions**

Implementing custom cell header, got compile error:
`
Alekseys-MacBook-Pro:library-sel alex$ npm start

> library@0.2.2 start /Users/alex/work/library-sel
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: cd2cb5b637981454168b                                                               
Time: 13835ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 178 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 40.8 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 72.8 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.74 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in /Users/alex/work/library-sel/src/app/filter/action-filter.component.ts (3,10): Module '"/Users/alex/work/library-sel/node_modules/ag-grid/main"' has no exported member 'SerializedTextFilter'.
webpack: Failed to compile.
`
**What is the motivation / use case for changing the behavior?**

Just wiling to use floating filter.

**Please tell us about your environment:**

Irrelevant, export statement missed in main.d.ts, 
After adding export statement as last line - all complied well.

* **ag-Grid version:** 12.0.2

* **Browser:**

Irrelevant, compilation error.

* **Language:** [TypeScript 2.4 ]

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - I've added it to the exports. It'll be available in the next version

thanks
