### ISSUE TITLE
Allow to apply formatter in text filter on falsy values

### ISSUE THREAD

**Issue by sclassen** [ag-grid/ag-grid#1835]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I use the colDef.valueFormatter to influence the displaying of values. Some of the transformations I do:
- null => "No Value"
- 0 => "SAP-Code 0: Bill Monthly"

Now I wanted to use text column filters on these formatted values. This is currently not possible because the text filter is applied to the unformatted value.
I then tried to add a filterParams.textFormatter with the same transformation logic. Unfortunately for falsy values it gets never called.

**Expected behavior**
The filterParams.textFormatter (or alternatively the colDef.valueFormatter) gets applied to all values not just the ones that are javascript truthy.
For me the most convenient solution would be a flag to enable applying the colDef.valueFormatter to the value before it is filtered

**Minimal reproduction of the problem with instructions**
The simplest way to reproduce the issue is to add a column filter of type text to a column containing numbers. When trying to filter for the text "0" (zero) all rows are filtered away. I would expect the ones which actually contain a zero to stay.

**What is the motivation / use case for changing the behavior?**
The user of the grid should be able to filter for the text he sees in the column independent of the fact, that the underlying data may contain values which are falsy.

**Please tell us about your environment:**
This is purely related to ag-grid and can be reproduced in any environment

* **ag-Grid version:** 
12.0.0

* **Browser:**
all

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
