### ISSUE TITLE
api.updateRowData() doesn't effect rowData

### ISSUE THREAD

**Issue by kopagana** [ag-grid/ag-grid#1837]
**I'm submitting a ...** 
bug report

**Current behavior**
After using `api.updateRowData()` for inserting or removing rows the `gridOption.rowData` stays as if untouched while in the view I can see all the changes.

Edit: new observation.
I set my `rowData` with `gridOptions.rowData = table`.
when I'm using the `api.updateRowData()` it changes the view but no the `table` variable nor the `dataRow` property.  

**Expected behavior**
set the `gridOption.rowData` to match the view

**Please tell us about your environment:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

* **ag-Grid version:**
12.0.2

* **Language:** 
TypeScript

**Comment by seanlandsman** [comment]
gridOptions.rowData is read once but not again - the grid will maintain its own copy of data with updates etc

If you want to see the latest data you'll need to use one of the api.forEachXXX methods

**Comment by kopagana** [comment]
thanks.
