### ISSUE TITLE
The right-click menu is not available under reaction

### ISSUE THREAD

**Issue by bwqdxxg** [ag-grid/ag-grid#1838]
No problem with configuration
The browser popup still appears on the right
Is there a lack of configuration?
The official website does not give a case of the react configuration context

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
