### ISSUE TITLE
typescript definition for ag-grid-vue

### ISSUE THREAD

**Issue by sbant** [ag-grid/ag-grid#1840]
**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior**
When use with Vue, there is no .d.ts for ag-grid-vue

**Comment by seanlandsman** [comment]
Our vue offering does not include typescript support I'm afraid

**Comment by a688** [comment]
Have you thought about adding Typescript support anytime soon to help those who want to use vue and typescript?

**Comment by angrax** [comment]
funny part is the whole ag grid is in typescript :S

**Comment by antsteyer** [comment]
So sad to not have this in 2018
