### ISSUE TITLE
Printing all columns / Printing columns not visible

### ISSUE THREAD

**Issue by jaetea** [ag-grid/ag-grid#1843]
**I'm submitting a ...**  (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

**Current behavior**
Printing print all rows but does not print all columns if the grid horizontally scrolls. Even if you scroll to the other columns it doesn't print those columns

**Expected behavior**
Print should print all rows AND columns either onto another page or size them down to fit

**Minimal reproduction of the problem with instructions**
https://www.ag-grid.com/javascript-grid-for-print/exampleForPrintComplex.html

If you print this screen you will only get up to column O in landscape in chrome. Even if you scroll the grid to the right it will still only print the columns up to column O. Currently there is no way to print the other columns.

![image](https://user-images.githubusercontent.com/3731879/29716368-1f27fca8-8979-11e7-96a0-d25dbb9a7275.png)

**Comment by eddiechihyi** [comment]
You can achieve that by open up "More settings" and change scale to 50%

**Comment by MarceloFonseca** [comment]
Hello, 

I'm facing the same issue, and allow-me to disagree from @eddiechihyi answer, but if you do have quite many columns, changing the scale to 50% will only make print results unreadable.

A better solution would be to have page-break management, when printing, splitting the result across multiple pages automatically.
