### ISSUE TITLE
v13 doesn't use gridOptions.icons

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1844]
Check out your example: https://www.ag-grid.com/javascript-grid-icons/#gsc.tab=0

**Comment by szilarddavid** [comment]
I can confirm that at least 'menu', 'sortAscending' and 'sortDescending' icons can't be provided using gridOptions.icons. In the example grid provided by @ataft the font-awesome icons are ignored and the icons from ag-fresh theme are being loaded (through css).

Also the 'menu' icon which in v12 and earlier controls the menu icon (hamburger) now seems to control  the first tabs's icon (fa-bath) in the filter popup.

**Comment by killyosaur** [comment]
I can confirm this bug, it is an issue just for the menu, sorts and filter. The rest seem to be working as expected. I could not find where ag-icon-menu, ag-icon-filter, ag-icon-asc, or ag-icon-desc are being used in the actual grid source.

**Comment by ceolter** [comment]
thanks for raising, looking into it now.

**Comment by petyosi** [comment]
Thank you. The issue should be fixed in 13.0.1, about to be released today.

**Comment by alexagranov7** [comment]
How do  you override the menu icon in code when setting up column definition?
