### ISSUE TITLE
grid not drawing rows after update to v13 (with bugfix)

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1846]
i got the following error after V13 update:

    TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at CellComp.attachCellRendererAfterCreate (ag-grid.noStyle.js:15326)
    at CellComp.afterAttached (ag-grid.noStyle.js:14834)
    at ag-grid.noStyle.js:18477
    at Array.forEach (<anonymous>)
    at RowComp.callAfterRowAttachedOnCells (ag-grid.noStyle.js:18475)
    at ag-grid.noStyle.js:17803
    at ag-grid.noStyle.js:29365
    at Array.forEach (<anonymous>)
    at RowContainerComponent.flushRowTemplates (ag-grid.noStyle.js:29365)
    at ag-grid.noStyle.js:10677

**Comment by jogibear9988** [comment]
<img width="1656" alt="bildschirmfoto 2017-08-27 um 09 48 48" src="https://user-images.githubusercontent.com/364896/29748028-dfc1c2de-8b0c-11e7-9f38-b335ce4a5618.png">

**Comment by jogibear9988** [comment]
Problem is, this.cellRendererGui is a object with the function "addZero"

**Comment by jogibear9988** [comment]
Bugfix:

Change line 15307 of ag-grid.noStyle.js from

                 if (typeof eCell == 'object') {

to

                 if (typeof eCell == 'object' && eCell.nodeType > 0) {

and change line 15324 from

    if (utils_1._.exists(this.cellRendererGui) && typeof this.cellRendererGui === 'object') {

to

     if (utils_1._.exists(this.cellRendererGui) && typeof this.cellRendererGui === 'object' && this.cellRendererGui.nodeType > 0) {

**Comment by jogibear9988** [comment]
maybe here is better Code to detect if a object is a DomElement: https://stackoverflow.com/a/384380
I used the one from comment 3

**Comment by ceolter** [comment]
thanks for raising. looking into it.

**Comment by ceolter** [comment]
@jogibear9988 what did you have in your examples that was different? all our examples are working, so maybe you are doing something particular in your cell renderer?

**Comment by ceolter** [comment]
ok fixed. jira 706.

basically the code was:

```
if (typeof cell === 'object') {
  // assume it was DOM Element or Node
} else {
  // assume it was string template
}
```

now it's

```
if (typeof cell === 'string') {
  // assume it was string template
} else {
  // assume it was DOM Element or Node
}
```

if you give your use case (provide a simple example of the cellRenderer that was broken) then we can test before we release later today, otherwise closing.

**Comment by jgordor** [comment]
Hi @ceolter I had the same issue with the default cellEditor (simple editable:true on a column def), the proposed fix solved the issue.

Waiting for the fix release, Thanks!

**Comment by jogibear9988** [comment]
I've found a issue:

for Example my CellRenderer returned a "Date" object instead of a "string".

Should this be allowed?

Maybe check if object is a Node before append?

**Comment by katjaso** [comment]
Hi @ceolter,

I had the same problem and thererfore updated to version 13.0.1 - but I still get this error in my cellRenderer if the returned value is a number - until now this worked without any problems. 

Will this be fixed?

**Comment by Q-Man** [comment]
I have the same problem in 13.0.2

**Comment by jogibear9988** [comment]
reopen?

**Comment by Q-Man** [comment]
I dove in a bit more and found out the combination making AG grid throwing the error in my case:

- I have a cellRenderer-Function that's returning an empty string for null values
- editing a cell with this cellRenderer that had a null value before throws the error, no matter if the new value is a string or a number

This behaviour is new since my update to AG-Grid 13, was still working in AG-Grid 10. As a workaround I made my cellRenderer return a space instead of an empty string for null values. This fixed the problem for me.

**Comment by jogibear9988** [comment]
@ceolter should this be reopened, our is new behavior expected?

**Comment by tystol** [comment]
I have a repro plunkr here: https://embed.plnkr.co/0w9LXUCpjerSH7rRcRon/

Note this is based on one of your samples, but with a cell renderer copied from our code that was working fine in previous versions.

**Comment by jogibear9988** [comment]
I'm not sure if the ag-grid team reads the closed tickets, so maybe we should create a new one with the example, and link to this?

**Comment by crumhorn** [comment]
This bug happens in 13.1 for me if I do the following for a row number column (which I've done since forever):

```
 cellRenderer: (params) => {
                    return params.rowIndex + 1;
                },
```

whereas this works (string return):

```
 cellRenderer: (params) => {
                    return ""+ (params.rowIndex + 1);
                },
```

I believe this bug should be reopened.

**Comment by jogibear9988** [comment]
seems to be solved in 13.1.1

**Comment by Q-Man** [comment]
No, I still have the same problem with 13.1.1

**Comment by Q-Man** [comment]
Seems to be fixed, works for me now in 13.3.1

**Comment by jingtra** [comment]
This is still a issue, if you don't return a string in cellRenderer.

**Comment by sandguardian** [comment]
I used `cellRendererFramework` instead of `cellRenderer` and it fixed the issue.
