### ISSUE TITLE
Editing empty cell values does not work anymore

### ISSUE THREAD

**Issue by jo75** [ag-grid/ag-grid#1849]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Changing an empty value in Cell-Editor and leaving cell throws an error, value is not updated.

Error on console:

```
ag-grid-enterprise.js?ignore=notused50:13725 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at CellComp.stopEditing (ag-grid-enterprise.js?ignore=notused50:13725)
    at RowRenderer.moveEditToNextCell (ag-grid-enterprise.js?ignore=notused50:9617)
    at RowRenderer.moveToCellAfter (ag-grid-enterprise.js?ignore=notused50:9604)
    at RowRenderer.onTabKeyDown (ag-grid-enterprise.js?ignore=notused50:9570)
    at CellComp.onTabKeyDown (ag-grid-enterprise.js?ignore=notused50:13418)
    at CellComp.onKeyDown (ag-grid-enterprise.js?ignore=notused50:13387)
    at GridPanel.processKeyboardEvent (ag-grid-enterprise.js?ignore=notused50:10171)
```

**Expected behavior**

Editing an empty cell value should work.

**Minimal reproduction of the problem with instructions**

Try to change any of the empty "Age" cells at :
[https://www.ag-grid.com/javascript-grid-cell-editing/exampleCellEditing.html](https://www.ag-grid.com/javascript-grid-cell-editing/exampleCellEditing.html)
It will work on non-empty cells.

Changing this line will fix it on my local environment:
[https://github.com/ag-grid/ag-grid/blob/master/src/ts/rendering/cellComp.ts#L1443](https://github.com/ag-grid/ag-grid/blob/master/src/ts/rendering/cellComp.ts#L1443):
```
	if (eCell !== null) {
		this.getGui().appendChild(eCell);
	}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 13.0.0

(error didn't occur on Version 11.0.0)

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:46.0) Gecko/20100101 Firefox/46.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ceolter** [comment]
thanks. fixing now.

**Comment by ceolter** [comment]
fixed. will be in today's patch release v13.0.1.

**Comment by jo75** [comment]
Great.
Thanks a lot!
