### ISSUE TITLE
Column header icon positioning is off

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1851]
From the demo page (bootstrap theme), you can see that the column header icon position is off when the column text doesn't have enough horizontal space:
![image](https://user-images.githubusercontent.com/11670864/29790722-962a4b44-8bef-11e7-8ed8-4d923e3fe344.png)

In other themes, if there isn't enough space for the column text, then the icon doesn't show up at all.

**Comment by petyosi** [comment]
Thank you, related to #1850

**Comment by petyosi** [comment]
The issue should be fixed in 13.0.1, about to be released today.
