### ISSUE TITLE
AngularCompileRows for Angular 1.x doesn't work

### ISSUE THREAD

**Issue by killyosaur** [ag-grid/ag-grid#1854]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Rows with angular bindings or directives do not compile as expected

**Expected behavior**

angular cells will display with the compiled data

**Minimal reproduction of the problem with instructions**
This is shown in your example for a simple bind here https://www.ag-grid.com/best-angularjs-data-grid/#gsc.tab=0 (note the missing Athlete, Country, and age in the button).

**What is the motivation / use case for changing the behavior?**

I have a grid with a column that still has an angular 1.x directive in it.

**Please tell us about your environment:**

All Browsers, windows 10, visual studio 2017

* **ag-Grid version:** 13.0.0

* **Browser:**

Able to reproduce this in IE and Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5 (probably all for all I know)

**Comment by seanlandsman** [comment]
Hi - thanks for reporting. This has been fixed and will be available as 13.0.1 soon

thanks
