### ISSUE TITLE
Viewport data source not working right on 13.0.1, icons not working right on 13.0.0

### ISSUE THREAD

**Issue by amirburbea** [ag-grid/ag-grid#1855]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I use the view port data source in my code.  My server sends lots of updates, I update my array of data, slap a proxy handler over it and in my viewport data source call `params.setRowData(data);` many times.

In ag-grid 12.02 or 13.0.0 this works and the grid updates accordingly, but in 13.0.1 only my top row remains visible and the rest of the rows end up with no data.

I downgraded to 13.0.0, but specifying custom icons in the gridOptions object as below seems broken in the 13.0.0 realm.  I was forced to downgrade to 12.0.2

```ts
const gridOptions = {
/*other stuff*/
icons: {
        menuValue: 'V',
        columnMovePin: '<i class="fa fa-hand-grab-o"/>',
        columnMoveAdd: '<i class="fa fa-plus-square-o"/>',
        columnMoveHide: '<i class="fa fa-remove"/>',
        columnMoveMove: '<i class="fa fa-chain"/>',
        columnMoveLeft: '<i class="fa fa-arrow-left"/>',
        columnMoveRight: '<i class="fa fa-arrow-right"/>',
        columnMoveGroup: '<i class="fa fa-group"/>',
        rowGroupPanel: '<i class="fa fa-bank"/>',
        pivotPanel: '<i class="fa fa-magic"/>',
        valuePanel: '<i class="fa fa-magnet"/>',
        filter: `<i class="${icons.icon} ${icons.iconFilter}" style="font-size: 12px" />`,
        sortAscending: `<i class="${icons.icon} ${icons.iconCaretUp}"/>`,
        sortDescending: `<i class="${icons.icon} ${icons.iconCaretDown}"/>`,
        checkboxChecked: `<i class="${icons.icon} ${icons.iconCheck}"/>`,
        checkboxUnchecked: `<i class="${icons.icon} ${icons.iconClose}"/>`,
        menu: `<i class="${icons.icon} ${icons.iconChevronDown}"/>`,
        menuAddRowGroup: `<i class="${icons.icon} ${icons.iconPlus}"/>`,
        menuRemoveRowGroup: `<i class="${icons.icon} ${icons.iconMinus}"/>`,
        groupContracted: `<i class="${icons.icon} ${icons.iconPlus}"/>`,
        groupExpanded: `<i class="${icons.icon} ${icons.iconMinus}"/>`,
        menuPin: `<i class="${icons.icon} ${icons.iconPushPin}"/>`,
      },
```
* **ag-Grid version:** 13.0.1

* **Browser:**
Chrome 60 or OpenFin

* **Language:** TypeScript 2.4.2

**Comment by ceolter** [comment]
we had some issues with icons in 13.0.0, please update to 13.0.1 and try again.

if still broken, then need more info, as the examples on our website are working, you are doing something particular that we need to reproduce. how can we reproduce?
https://www.ag-grid.com/javascript-grid-viewport/

**Comment by amirburbea** [comment]
It took me almost a full day to write a demo because I basically had to write half my application code for this to be "apples to apples"

Clone the repo here: https://gitlab.com/doubledown/ag-grid-issue/tree/master

In the root, there's a file "./config.json", it has a field `license` that needs to be set with an ag-grid-enterprise license key (one that will work with both 12 & 13).

To run, simply specify a port and license in config.json, and then run `npm start` (assuming you already `yarn`ed the dependencies/devdependencies).  Open Chrome to the url displayed in the console.

This program has a position generator on the server that will send them to the client (but it's set to only generate positions while at least one client is connected).   Also on a different schedule, positions prices are updated.  Server side sorting/filtering is supported in the demo.

There's some minor bug in this particular demo where occasionally rows are duplicated but it doesn't matter because that doesn't affect the end result of what I'm trying to demonstrate here.

Because the server could theoretically generate many positions, the viewport datasource is used.  The problem with the viewport normally is the difficulty of updates.  Imagine I had your `{ [rowNumber:string]: object }` and now I get a new row that goes in the middle.  All rows beneath that need to have their key updated - it's kind of terribly inefficient.  Enter the ES6 proxy.  I have a proxy handler that takes an array and a start index.  I can simply splice into the array at will and the `ownKeys`,`get`,`has`,`getOwnPropertyDescriptor`,`enumerate` methods tell ag-grid it has the keys needed.



This demo works on ag-grid@12.0.2, ag-grid-enterprise@12.0.2, ag-grid-react@12.0.0

This demo is completely broken on ag-grid@13,ag-grid-enterprise@13,ag-grid-react@13.

**Comment by amirburbea** [comment]
FYI - For typescript purposes, in "./src/global.d.ts" I declared LicenseManager for ag-grid-enterprise because it's not there in 12's declarations, but before running this demo after upgrading to ag-grid-enterprise 13, please comment that section out as it is there in ag-grid-enterprise 13.0.1+

**Comment by amirburbea** [comment]
Did you get a chance to look at the demo @seanlandsman?

**Comment by seanlandsman** [comment]
Hi @amirburbea - no, not yet - I'll try get to this tomorrow

tanks

**Comment by amirburbea** [comment]
If you need help with something related to the demo not working for you, I am happy to dive in - work is kind of light at the moment

**Comment by amirburbea** [comment]
Any luck? Or is this perhaps already fixed with some newer version of ag-grid?

**Comment by seanlandsman** [comment]
@amirburbea apologies for the delay in this - I'll pick it up as soon as I can, but this week for sure.

thanks

**Comment by rmc-software** [comment]
Hi,

We are currently investigating this and will aim to get back to you on Monday.

Thanks

**Comment by seanlandsman** [comment]
Hi @amirburbea 

I've cloned the repo and started it up - I can see the app and the grid updates with changes.

I cannot see you setting icons anywhere - is the latest code in the repo? Should I add something manually?

thanks

**Comment by amirburbea** [comment]
This demo wasn't about the icons. The viewport code I was using wasn't
working in 13.0.1. It would error out a lot. It worked fine in 12. It might
work in newer builds of 13 - I've already released to my end users using 12
since then

**Comment by seanlandsman** [comment]
hi - I can see what you mean once I update the dependencies. I'll take a look again at this tomorrow

thanks

**Comment by seanlandsman** [comment]
@amirburbea 

An update on this - the initial errors I got where down to other dependency problems, not the grids, so I've updated the yarn.lock to upgrade the ag-grid deps to 13.3.1

With this the app starts and slowly fills up with data.

Based on this I dont think I'm seeing what you're seeing (only the top row).

**Comment by makinggoodsoftware** [comment]
Based on the feedback from @seanlandsman I am going to close this issue, feel free to let us know if you think it should be reopened

**Comment by viratpatil** [comment]
Seem to be timing issue so just calling setData in a setTimeout with no timeout would solve issue
