### ISSUE TITLE
Dynamic HeaderCellRenderer

### ISSUE THREAD

**Issue by scottkunkel** [ag-grid/ag-grid#1856]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Dynamically changing header styles requires complete implementation of header component. I understand that I can change css classed but I'd like to do this for a single table while having multiple tables on the screen.

**Expected behavior**
Provide header Cell Renderer comparable to cellRenderer

**Minimal reproduction of the problem with instructions**
I'd like to change the format of the header dynamically and can only do this by implementing the complete headerComponent. 

**What is the motivation / use case for changing the behavior?**
Don't want to replicate sorting/ filter/ menu handling.

* **ag-Grid version:** 12.0.2

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Reactjs

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by scottkunkel** [comment]
Is this resolved?
