### ISSUE TITLE
Defect - Sorting Numbers on the header disappear when the Grid View is re-sized.

### ISSUE THREAD

**Issue by prinks17** [ag-grid/ag-grid#1857]
On Applying sorting on multiple columns, The column headers show sorting number along with the header name to indicate which order of sorting is applied on the Grid, apart from up/down arrow indicator for ascending/descending Order indicator,
refer to the screenshot below, (sorting is applied to 4 columns here.) 
SORTING order priority Col11, Col12, Col6, Col1
![columnswithsortnumbers](https://user-images.githubusercontent.com/26967548/29859319-2949aa38-8d7f-11e7-81bc-03ed803f071c.png)

On resizing the Grid View(making the window small, and restoring back to bigger window)
The arrow indicators are there in the column header(to indicate ascending/descending order), but the number indicating the order of sorting disappear until the Grid is reloaded again.
SORTING order priority Col11, Col12, Col6, Col1(The number indicator not visible for col11 & col12)
![column11and12_sortingnumberdisappeared](https://user-images.githubusercontent.com/26967548/29859364-5e82984a-8d7f-11e7-819c-d1e1d5406e64.png)

Plz raise a Defect.

**Comment by seanlandsman** [comment]
I'm afraid I cant reproduce this on our demo here: https://www.ag-grid.com/example.php

As per our issue template please provide more information in order for us to investigate further.
