### ISSUE TITLE
dispatchEvent is not working properly

### ISSUE THREAD

**Issue by sklyarov-ivan** [ag-grid/ag-grid#1858]
**I'm submitting a ...** 
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
api.dispatchEvent('filterModified');
```
doesn't emit event

**Expected behavior**
should be caught by
```
api.addEventListener('filterModified', this.onApplyFilters);
``` 

**Minimal reproduction of the problem with instructions**
it worked on previous version (i.e. 12.x) it stopped working once I've updated ag-grid version to 13.x

* **ag-Grid version:** 13.0.1

* **Browser:**

* **Language:** [React | ES6/7]

**Comment by rmc-software** [comment]
Hi,

I have created AG-727 to track this. We'll update this post when we have any updates.

Thanks

**Comment by ceolter** [comment]
the method takes an event object, not an event string, should be:

```
        var event = {
            type: 'filterModified'
        };
        api.dispatchEvent(event);
```

**Comment by sklyarov-ivan** [comment]
thanks! just documentation wasn't updated
