### ISSUE TITLE
Expand all row prompting alert in FF and Edge " web page is making slow your browser" and recover webpage respectively.

### ISSUE THREAD

**Issue by alokkarma** [ag-grid/ag-grid#1859]
I have created button to expand all the rows in grid maximum 150 rows are there in the grid. It is working fine in chrome but it is prompting alert in FF and Edge saying web page is making slow your browser. Could you please assist me what is the issue with this code or any better approach to expand all the row:

`<button (click)="expandAll(expand)">Expand/Collapse</button>`
```
public expandAll(value:boolean) {
        if(value) {
            this.gridOptions.api.forEachNode(function(node) {
                node.setExpanded(true);
            });
            
        } else {
            this.gridOptions.api.forEachNode(function(node) {
                node.setExpanded(false);
            });
        }
    }
```

**Comment by seanlandsman** [comment]
I've just tried this in our example and cannot reproduce this https://ag-grid.com/javascript-grid-aggregation/exampleGroupRowAggNodes.html

If you can provide a repro of this problem I'll be happy to take a look

thanks

**Comment by alokkarma** [comment]
As per the documentation : 
Calling node.setExpanded() causes the grid to get redrawn. If you have many nodes you want to expand, then it is best to set node.expanded=true directly, and then call api.onGroupExpandedOrCollapsed() when finished to get the grid to redraw the grid again just once. So i modified my code like below:

this.gridOptions.api.forEachNode(node =>{
  node.expanded= true;
 });
 this.gridOptions.api.onGroupExpandedOrCollapsed();
