### ISSUE TITLE
Custom rendered - eGridCell is undefined in v13

### ISSUE THREAD

**Issue by jurafa** [ag-grid/ag-grid#1860]
**I'm submitting a ...**
```
[x ] bug report
```

**Current behavior**
I upgraded from ag-grid v12.0.2 to ag-grid v13.0.1. I have a custom cell renderer. In this renderer I used to use the *cellRenderer Params*.eGridCell to listen to *onkeypress* event like this:

```
export class CellRenderer {

  constructor() { }

  agInit(params: any): void {
      this.params.eGridCell.onkeypress = (event: KeyboardEvent) => {
...
      });
    }
}
```
It was working fine in version v12 but in version v13 the eGridCell property is undefined.

**Expected behavior**
eGridCell should contain a reference to the DOM element representing the grid cell that your component will live inside. Useful if you want to add event listeners or classes at this level. This is the DOM element that gets browser focus when selecting cells. (taken from https://www.ag-grid.com/javascript-grid-cell-rendering-components/)

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/9wdUqW
In this plunker is a fork of a plunker with a demo of dynamically rendered cells. ChildMessageComponent in agInit function logs to console the value of params.eGridCell. It is always undefined.

**Please tell us about your environment:**
Windows 10, angular 4, Google Chrome

* **ag-Grid version:** X.X.X
ag-grid 13.0.1
ag-grid-angular: 13.0.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-728 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by ceolter** [comment]
my apologies, this change missed the change log.

as part of making the grid go faster in version 13, we made a small change to the ICellRenderer interface.

now there is a method afterGuiAttached(params) which gets the eGridCell. 

your component can have both init() and afterGuiAttached(). the first gets called before the component is put into the dom. the second is called after the component is put into the dom and is provided the dom references.

this was necessary due to the different rendering engine we now have where the DOM is built after init() is called (so the dom items are not available at this stage).

**Comment by jurafa** [comment]
If I am correct then afterGuiAttached() is available for basic Javascript class implementation but not for integration with Angular (based on this https://www.ag-grid.com/javascript-grid-cell-editor/). Note please that I am not trying to use the custom editor. I want to use custom renderer and listen to the keypress event on the cell. In the link above there is being said that I should use *AfterViewInit*. So I tried that but ngAfterViewInit does not get the reference to the eGridCell either.

Then, I tried to bind the listener to the native element inside the ngAfterViewInit as it is in the example in the link above. The listener is never called, however.

Finally, I tried to use the angular binding from the template using *(keypress)="onKeyPress()"*. That did not work either.

I am out of ideas.

Should I create another bug report with different plunkers?
