### ISSUE TITLE
Event for "Reset Columns" menu item

### ISSUE THREAD

**Issue by mfd12** [ag-grid/ag-grid#1861]
I'm using ag-Grid (enterprise version) with ReactJS and I cannot find an event that is triggered while resetting columns from header menu. Tried already to find it with addGlobalListener(), but could'n find one. 

Here is what I'm trying to do: currently I keep a copy of columns definitions in Redux state and I want to be able to clear the state when the "Reset Columns" button is pressed from header menu. Can you please help me with a solution?

Thank you,
Marius

**Comment by seanlandsman** [comment]
Hi,

If you're an enterprise customer can you please raise this in the Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

If you need access please register on the forum and let accounts@ag-grid.com know your chosen username along with your license key - they'll grant you access.

thanks
