### ISSUE TITLE
cellEditingStopped should send any relevant keyPress info

### ISSUE THREAD

**Issue by armuell** [ag-grid/ag-grid#1863]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As far as I can tell, no keyPress info is passed along in the event when the onCellEditingStopped event is fired (please correct me if I am wrong). 

**Expected behavior**
If a user presses the escape key or enter key (or any key that would trigger stopEditing), that info is passed along in the event object of the onCellEditingStopped event

**Minimal reproduction of the problem with instructions**
I console.log'd the even object passed to the onCellEditingStopped event and searched for a keyPress but couldn't find one

**What is the motivation / use case for changing the behavior?**
If a request needs to be sent to the server when editing is stopped for a specific keyPress

* **ag-Grid version:** 13.0.1

* **Language:** [all]

**Comment by armuell** [comment]
Any consideration on this request?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
