### ISSUE TITLE
Unable to Change the Alignment of the Header Text for the Columns in the Grid to Center in Ag-grid v13.0.0 (Bug)

### ISSUE THREAD

**Issue by nd48804** [ag-grid/ag-grid#1864]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Prior to Ag-Grid v13.0.0; the Header Text for the Columns in the Grid were Center Align. In Ag-Grid v13.0.0; the Header Text for the Columns in the Grid are Left Align. I have changed the Style for .ag-header-cell-label and .ag-header-cell-text; but it is not aligning the Header Text to Center. Please fix this Issue.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 13.0.1

* **Browser:** Edge

* **Language:** Angular JS

**Comment by nd48804** [comment]
I figure out a way to fix this Issue.

**Comment by pycraft114** [comment]
@nd48804 How did u solve it?

**Comment by mohmoniem281** [comment]
I am having the same problem. Can you please share your solution?

**Comment by nd48804** [comment]
Here is the Solution to this Issue:

Please add the following Styles in your HTML Page:

.ag-fresh .ag-header-cell-label .ag-header-cell-text 
{
    display: inline-block;
    text-align: center;
}

.ag-fresh .ag-header-cell-label .ag-header-icon 
{
    vertical-align: top;
}

.ag-fresh .ag-header-cell-label > span 
{
    float: none;
}

This will make the Alignment of the Header Text for the Columns in the Grid to Center.

**Comment by cbossi** [comment]
@thearabbit I suspect i can't help you... Just the following two remarks:
- Of course the parent element (`ag-header-cell-label`) has to have `display: flex`. But this is given by ag-grid itself (maybe it depends on the template, i use `ag-theme-bootstrap`)

- I also have to mention that I disabled sorting and filtering. Maybe those Icons in the header change the way the header is constructed in a way that above fix does not work...

**Comment by thearabbit** [comment]
thanks for your reply.
I base on `ag-theme-balham`.

**Comment by thearabbit** [comment]
But work fine for this
```
cellStyle: { 'text-align': 'center' }
```

**Comment by thearabbit** [comment]
Now word fine
```js
// Override
.ag-theme-balham .ag-header-cell-label {
  display: inline !important;
}
.ag-theme-balham .ag-header-cell-label > span {
  float: none !important;
}
---
text-center {
   text-align: center
}
```

**Comment by sunilbehera91** [comment]
Unable to Change the Alignment of the Header Text for the Columns in the Grid to Center in Ag-grid in angular 5

**Comment by wdalrymple** [comment]
None of these css solutions work for me in Angular 6+

**Comment by phamcong** [comment]
The group header is centering by default, by changing as follow, the group header is now at the left.
.ag-header-group-cell-label {
  display: block;
}

**Comment by binDongKim** [comment]
https://stackoverflow.com/a/46495997/7289627
This answer helped me through the issue.

**Comment by TobTechnologies** [comment]
::ng-deep .ag-header-group-cell-label {
  justify-content: center !important;
}

::ng-deep .ag-header-cell-label {
  justify-content: center !important;
}
