### ISSUE TITLE
Accessibility - Row and Column Order example grid - invalid enforceRowDomOrder setting instead of ensureDomOrder

### ISSUE THREAD

**Issue by szilarddavid** [ag-grid/ag-grid#1869]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In the documentation related to Accesibility - Row and Column Order (https://www.ag-grid.com/javascript-grid-accessibility/#dom-order&gsc.tab=0) it is stated that 

_To force row and column order set gridOptions.ensureDomOrder=true._

But in the JavaScript code of the example grid this setting is not used and instead there is a _enforceRowDomOrder_ setting which seems to be invalid or has been removed in the latest version (v13.0.1)

**Expected behavior**

The JavaScript example should use the correct setting: _ensureDomOrder_.

**Minimal reproduction of the problem with instructions**

The issue can be seen in the documentation: https://www.ag-grid.com/javascript-grid-accessibility/#dom-order&gsc.tab=0

The _ensureDomOrder_ seems to work properly only if _suppressColumnVirtualisation_ is also set to _true_

**What is the motivation / use case for changing the behavior?**

I have custom CSS styling applied in my grid for the first column and if the DOM order is not ensured, the styling doesn't work.

**Please tell us about your environment:**

Environment is not relevant here. Providing just in case: Windows 10, Visual Studio Code, npm, Angular 4

* **ag-Grid version:** X.X.X

13.0.1

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by rmc-software** [comment]
Hi,

Initially we only forced row order, now we force both row and column order hence the property rename.

The updated property name was missed from the example.

Thanks for reporting this. Example has been updated and will be included in the next release.
