### ISSUE TITLE
Circular dependency preventing bundled deployment

### ISSUE THREAD

**Issue by davismj** [ag-grid/ag-grid#1870]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is a circular dependency preventing ag-grid from being bundled with systemjs v0.19.

**Expected behavior**
There should be no circular dependencies.

**Minimal reproduction of the problem with instructions**
See information below.

**What is the motivation / use case for changing the behavior?**
I'd like to bundle ag-grid for production builds.

**Please tell us about your environment:** 

* **IDE:** visual studio 2017, sublime text 3

* **ag-Grid version:** 13.0.2

* **Browser:** all

* **Language:** all

*entities/column.ts* loads *eventService.ts*: 
https://github.com/ag-grid/ag-grid/blob/master/src/ts/entities/column.ts#L4

*eventService.ts* loads *logger.ts*:
https://github.com/ag-grid/ag-grid/blob/master/src/ts/eventService.ts#L2

*logger.ts* loads *gridOptionsWrapper.ts*:
https://github.com/ag-grid/ag-grid/blob/master/src/ts/logger.ts#L1

*gridOptionsWrapper.ts* loads *eventService.ts*
https://github.com/ag-grid/ag-grid/blob/master/src/ts/gridOptionsWrapper.ts#L12

Note that I've used `entities/column.ts` as the entry point because it is the source of the error since it is loaded first in *main.js* in the root.

**Comment by seanlandsman** [comment]
hi - this is a known issue and something we're actively looking at.

We'll be looking at this as part of our work to support rollup (tracked by ticket AG-305 - you can see its progress here: https://www.ag-grid.com/ag-grid-pipeline/)

**Comment by davismj** [comment]
Is there anything we can do in the mean time? We're using Aurelia and we saw there was an ag-grid.min, but it didn't seem to work.

**Comment by davismj** [comment]
@seanlandsman any ideas here? Would it help to open up a new issue?

**Comment by seanlandsman** [comment]
@davismj sorry, I've not workaround for you here. When you say it's stopping you from bundling though, can you provide an example of this? I have a working example of bundling using systemjs and systemjs-builder for our angular project

I know this is however an issue for tools like rollup

**Comment by davismj** [comment]
@seanlandsman I mean when I bundle ag-grid with systemjs/builder and then try to load the bundle, eventService is undefined in gridOptionsWrapper and I get an error in my console. 

I'd love to see what you're doing if possible.

**Comment by davismj** [comment]
@seanlandsman any chance you have an example I could review?

**Comment by seanlandsman** [comment]
Hi @davismj 

Apologies for not responding earlier. Please take a look at https://github.com/ag-grid/ag-grid-angular-example/tree/master/systemjs_aot

We use SystemJS Builder here to demonstrate the aot / bundling side of things

thanks

**Comment by Toxicable** [comment]
Did this ever get fixed? It looks to be the cause of this issue here
https://github.com/ag-grid/ag-grid-angular/issues/112#issuecomment-504720708
