### ISSUE TITLE
Feature Request: Suppress Hide feature for columns

### ISSUE THREAD

**Issue by killyosaur** [ag-grid/ag-grid#1871]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently there is no way to prevent a user from removing a column from the grid when said column is movable.

**Expected behavior**
a new property on the column definitions (suppress hide or what have you) that would allow me to prevent a user from hiding a column intentionally or unintentionally that I don't want them to be able to.

This should be reflected in the tool panel and other menus as well by disabling the ability to hide the column.

I realize that I can do this in a custom fashion, but figured it may not be a bad idea to have this baked into the grid.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
