### ISSUE TITLE
Feature Request: Add "limitResize" to autoSizeColumns()

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1872]
Add an option to the autoSizeColumns(key, limitResize) to allow for a column to only resize larger or smaller. The use case for this is after expanding groups, it would automatically grow to fit the content, but when the groups are collapsed, don't shrink back down. Ideally, it would never autoSize below the original width, but not sure how this would be done. Maybe there's a better way to implement this, but I tried the code below and really like the behavior, as I was getting annoyed with expanding a group and then manually resizing the column, but also don't like it to autoSize to something smaller than the original...

```
ColumnApi.prototype.autoSizeColumn = function (key, limitResize) ...
ColumnApi.prototype.autoSizeColumns = function (keys, limitResize)...

...
ColumnController.prototype.autoSizeColumns = function (keys, expandOnly) {
...
            var preferredWidth = _this.autoWidthCalculator.getPreferredWidthForColumn(column);
            if( (limitResize==='expand'&&column.actualWidth>=preferredWidth) || (limitResize==='contract'&&column.actualWidth<=preferredWidth) ) {
                return;
            }
...
```

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
