### ISSUE TITLE
AgGrid get selected Cell

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#1873]
How can I get the SelectedCell of the Grid? I only find API to get the selcted Wor!

Also the SelectionChanged event is triggert when I click on a Cell. The rowClicked event is not triggert!

**Comment by makinggoodsoftware** [comment]
This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
