### ISSUE TITLE
InnerRendererFramework does not use react to render leaf nodes

### ISSUE THREAD

**Issue by lauracurley** [ag-grid/ag-grid#1875]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The innerRendererFramework properly renders a specified react component for group nodes, but **leaf nodes are not rendered as react components**. Therefore there is no way to use a cell renderer framework to get detailed control of the leaf node cells when the cellRenderer is 'group'.

**Expected behavior**

The innerRendererFramework should render all cells in a group column as react components, and leave the logic of what to display in group vs leaf nodes up to the react component implementation.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

When using ag-grid with react, all cells should be renderable as react components to allow maximum control of the grid state, routing and styling.

**Please tell us about your environment:**

no applicable

* **ag-Grid version:** 13.1.0

* **Browser:**

Not browser specific, issue exists on all browsers.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by makinggoodsoftware** [comment]
Hi,

You should be able to customise the rendering in both the group nodes and the leaf nodes... Can you share with us an example of your columns and gridOptions?

Have you tried also setting cellRendererFramework?

**Comment by lauracurley** [comment]
Your code only renders react components if the node is a group node OR the
params include innerRenderer. With the new implementation of
innerRendererFramework, your code must also check for
innerRendererFramework but that logic is missing.

If ability to customise should be there then my request is a bug, not a
feature request.

**Comment by lauracurley** [comment]
Also, cellRendererFramework does not work when the type of cellRenderer
used is 'group'. When group is used, the only option is to use the new
innerRendererFramework in the params.

We need to use innerRendererFramework, not cellRendererFramework.

**Comment by lauracurley** [comment]
Here is the relevant column definition.
```
this.columnDefs = [{
            headerName: 'Name', showRowGroup: true, field: 'label',
            cellRenderer: 'group',  // shows built-in tree grid
            cellRendererParams: {
                suppressCount: true,
                checkbox: false,
                padding: tempPadding,
                innerRendererFramework: FileNameCellRenderer,
            }
        }, ...
```
We are not using any grid options that affect cell rendering.

Here is the relevant code in your groupCellRenderer.ts **including the changes we've made in our fork** of ag-grid to temporarily address this issue:
```
private addValueElement(): void {
        let params = this.params;
        let rowNode = this.displayedGroup;
        if (rowNode.footer) {
            this.createFooterCell();
        } else if (rowNode.group ||
                   _.get(params.colDef, 'cellRendererParams.innerRenderer', null) ||
                   _.get(params.colDef, 'cellRendererParams.innerRendererFramework', null) // OUR CODE TO FIX THIS BUG
        ) {
            this.createGroupCell();
            if (rowNode.group){
                this.addChildCount();
            }
        } else {
            this.createLeafCell();
        }
    }
```

**Comment by R4DIC4L** [comment]
Could these changes be included? Providing an inner renderer framework is useful for all those using JavaScript frameworks with ag-grid and at the moment you cannot provide one otherwise (one that uses framework-specific language - other than plain js).

**Comment by makinggoodsoftware** [comment]
This should be working now
