### ISSUE TITLE
sometime the gridOptions.api will be null?

### ISSUE THREAD

**Issue by Itherma** [ag-grid/ag-grid#1880]
## When a new component is created, then I close the component and open the component again. At this point, the gridOptions.api of the ag-grid is null and why the two instances of the gird should be the same.
![qq 20170904172205](https://user-images.githubusercontent.com/24877853/30020347-13328a9c-9196-11e7-9433-47ce4a50422b.png)

**Comment by ShankzPatil** [comment]
hi,

what is the solution for above error.
plz share.
