### ISSUE TITLE
Expand/Collapse all doesn't work for Enterprise Row Model

### ISSUE THREAD

**Issue by shpser** [ag-grid/ag-grid#1883]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
An error appears when I try to Expand/Collapse all groups.

**Expected behavior**
No errors. All groups are expanded/collapsed.

**Minimal reproduction of the problem with instructions**
Steps to reproduce:
- Open an example with Enterprise Row Model. For instance https://www.ag-grid.com/javascript-grid-enterprise-model/exampleEnterpriseSimple.html
- Open a column menu and click Expand All or Collapse All.
- Nothing happens. An error appears in browser console: Cannot read property 'expandOrCollapseAll' of undefined.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

* **Language:** all

**Comment by rmc-software** [comment]
Hi,

Thanks for reporting this. I have created AG-737 to track this and it will be fixed in the next release.
