### ISSUE TITLE
Aligned Grids example does not work with Firefox

### ISSUE THREAD

**Issue by shirosaki** [ag-grid/ag-grid#1884]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Open Aligned Grids example in Firefox ESR 52.3.0.
https://www.ag-grid.com/javascript-grid-aligned-grids/
https://www.ag-grid.com/javascript-grid-aligned-grids/exampleAlignedGrids.html

Grids are not aligned.
Firefox console shows errors `ReferenceError: event is not defined`.

**Expected behavior**
Grids are aligned.

**Minimal reproduction of the problem with instructions**
Open the following URL in Firefox.
https://www.ag-grid.com/javascript-grid-aligned-grids/
https://www.ag-grid.com/javascript-grid-aligned-grids/exampleAlignedGrids.html

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 13.1.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-743 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by shirosaki** [comment]
Now column width and column order change works fine with Firefox.
But  group open/close does not work as expected with Firefox.
JavaScript error `ReferenceError: event is not defined` is shown in console.

**Comment by makinggoodsoftware** [comment]
This should be done now

**Comment by shirosaki** [comment]
Group open does not work as expected with Firefox.
When I open Group 1 of first grid, Group 1 of second grid remains closed.

![2](https://user-images.githubusercontent.com/170831/34242377-9085ae26-e65e-11e7-94d1-234167ce1367.png)
