### ISSUE TITLE
Feature Request : Dynamic change grid styling after a cell value is updated

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [ag-grid/ag-grid#1885]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[X] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

I am trying to create feature where When user edit any column value,
1 ) Changed value is showing up highlighted with red color and bolder font.
2 ) changed value row will be shown as the light read color.

**Current behavior**
For changing ag-grid styling you need to refresh row modal. And if I will do that either changed value is highlighted or the only row can be showing with light background

**Expected behavior**
I need to display row highlighted as well as value changed for multiple row.

**Please tell us about your environment:**
Ubuntu14.04 OS, WebStorm, NPM package manager, angular-cli, Angular 4.3

* **ag-Grid version:** 12.0.2

* **Browser:**
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"

* **Language:** [ TypeScript ]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
