### ISSUE TITLE
On load of grid the class ag-row-focus is still being added to non-focused rows

### ISSUE THREAD

**Issue by panicst8** [ag-grid/ag-grid#1886]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The ag-row-focus class seems to be applied to all rows as grid loads, as well as ag-row-no-focus.
Opening an new issue as the last issue I opened on this **#1865** as closed with out the complete fix i provided in this pull request **#1867** being applied.  In 13.1.0 the current release, the row which adds the un-necessary ag-row-no-focus class was removed, but the ternary wasn't fixed, which contains the backwards logic.

Including solution again at bottom of bug report.

**Expected behavior**
When the grid is loaded no rows should be focused, having this class: ag-row-no-focus

**Minimal reproduction of the problem with instructions**
1. Set a style on ag-row-focus ( grid will load with style applied to all rows. )
2. click on a row to focus
3. use arrows to change focus up and down
4. You can see that the actual change of focus removes the class properly and then applies it properly just not on load.

https://plnkr.co/edit/iEvz7cqwMDWjUUT6YHIB?p=preview

**What is the motivation / use case for changing the behavior?**

Being able to highlight the focused row.

**Please tell us about your environment:**

Operating System: Windows 10 
IDE: VS Code 
Package Manager: yarn 
HTTP Server: IIS Express

* **ag-Grid version:** 13.1.0

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

* **Language:** [all]

* **Suggested Fix:**

**Just removing:** `classes.push('ag-row-no-focus');` doesn't solve the issue you need the other line i changed in my pull request . which swaps the ternary logic, currently it says if the row is focused use `'ag-row-no-focus'` . and if not focused use `'ag-row-focus'`.

**Current**:  823: `classes.push(this.rowFocused ? 'ag-row-no-focus' : 'ag-row-focus');`

**Fix**:  823: `classes.push(this.rowFocused ? 'ag-row-focus' : 'ag-row-no-focus’);`

**Comment by makinggoodsoftware** [comment]
Hi!

Sorry about that, good catch! Fixed, will be in the next release, we are hoping it will be available by the end of the week, or early next week

Sorry for all the trouble
