### ISSUE TITLE
Grid blanking out when used with golden layout

### ISSUE THREAD

**Issue by srishti0212** [ag-grid/ag-grid#1888]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We have 5 grids in an app with golden layout. The grids can be dragged around and placed wherever the user wants. Sometimes after dragging and placing the grid in a new position, it blanks out completely. The data starts to show up again when the user scrolls down in the grid. 

**Expected behavior**

When the grids are moved around, they should not blank out.
![gridingoldenlayout](https://user-images.githubusercontent.com/18292788/30081091-d6d39dac-9253-11e7-8379-9ad53bfe1781.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

golden layout lets user place widgets or views according to their wishes, if they move grids around and they blank out , it doesn't look good. Please refer to the attached image.

**Please tell us about your environment:**

Visual Studio code, windows

* **ag-Grid version:** X.X.X

Yes it is a problem with latest 13.0.0.

* **Browser:**

Chrome.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by seanlandsman** [comment]
Hi

We don't have much knowledge or experience with golden layout so will probably be able to assist here, especially without a repo
