### ISSUE TITLE
Row group pinning does not pin the group

### ISSUE THREAD

**Issue by xjdesigns** [ag-grid/ag-grid#1890]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using row grouping feature on Enterprise version and applying pinning to the row being grouped, the group does not pin. Pinning is only possible using the column menu.

**Expected behavior**

When setting a row to be grouped and pinning the row, the row group should be pinned along with the data being set by the columnDef.

**Minimal reproduction of the problem with instructions**

Steps to reproduce:
Create a new grid using enterprise. Set up row grouping with either rowGroup: true or rowGroupIndex: 0(any index), set pinning to left or right. The columnDef field pins but the group does not. You can group with the menu but I would argue that the group and row it's data should be pinned together when setting the columnDef.

**What is the motivation / use case for changing the behavior?**

This just feels like a bug as you can pin the column group from the menu but not from options.

**Please tell us about your environment:**

MacOS, Macbook Pro Retina

* **ag-Grid version:** X.X.X

8.2.0 but is present in 13.0.0

* **Browser:**

Chrome, Safari, Firefox, IE11, Edge
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5/Angular 1.5.8

**Comment by makinggoodsoftware** [comment]
Hi,

Sorry about that, it was a regression that is already fixed in our latest branch and that we hope to release soon, hopefully this week

Thanks for raising this though!

**Comment by bryannjones** [comment]
I'm running ag-grid-enterprise v13.3.1 and I seem to be running into this same issue.
Was this fix already merged into this 13.3.1 version?  Thanks! Bryan

**Comment by gavinwyf** [comment]
I'm running ag-grid-enterprise v22.0.3 and I seem to be running into this same issue.
Was this fix?

**Comment by wub** [comment]
@makinggoodsoftware Hi Alberto, I'm getting this issue on v29.

**Comment by StephenCooper** [comment]
> @makinggoodsoftware Hi Alberto, I'm getting this issue on v29.

@wub Could you please raise a new issue with a reproduction of the error with v29 please.
