### ISSUE TITLE
Modal show up multiple time when click button in grid

### ISSUE THREAD

**Issue by a2nmous** [ag-grid/ag-grid#1895]
I have ag-grid, a column with delete button inside. when click delete button then a modal dialog display, all nomal, but when I resize grid by bootrap from "col-md-12" to "col-md-8" and pull horizontal bar after change grid from "col-md-8" to "col-md-12" and click button delete, the dialog display two time.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have ag-grid, a column with delete button inside. when click delete button then a modal dialog display, all nomal, but when I resize grid by bootrap from "col-md-12" to "col-md-8" and pull horizontal bar after change grid from "col-md-8" to "col-md-12" and click button delete, the dialog display two time.

**Expected behavior**
I want when click delete button, dialog show one time.

**Please tell us about your environment:**
Operating system: window 10 pro
IDE: Visual studio 2015

* **ag-Grid version:** 5.0.1

* **Browser:**
FireFox 55.0.3

* **Language:** [ TypeScript 2.4 | ES5]

**Comment by seanlandsman** [comment]
If you can provide a repo of this issue we'll be happy to take a look
