### ISSUE TITLE
Add "DateTime" and "Boolean" to ExcelDataType supported values

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [ag-grid/ag-grid#1898]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The Excel export feature only supports String and Number, and it overrides anything else. I'm using the processCellCallback to format date values in a way Excel understands, but because the data type comes out as String, Excel treats the value as a string regardless of the numberFormat setting or the format of the data.

If I open the exported file in a text editor, find one of the date values, and change ss:Type="String" to ss:Type="DateTime", then open the file in Excel, it recognizes it as a date.

**Expected behavior**

ExcelDataType should support "DateTime" and "Boolean" along with "String" and "Number". I don't care if it auto-detects these (default of String is fine). I just want to be able to specify them myself.

If there's another way to get Excel to recognize the data type, great, but I haven't found one yet.

**Minimal reproduction of the problem with instructions**

Create a new ExcelStyle with dataType="DateTime", it renders (exports) as "String".

**What is the motivation / use case for changing the behavior?**

According to the Office XML format document you have linked from the ag-Grid Excel Export docs, Excel supports "String", "Number", "DateTime" and "Boolean".  Obviously it's on the developer to format the data correctly, but having those two extra types not be overridden by ag-Grid's code would be best.

**Please tell us about your environment:**

Excel version is 2016 for Windows.

* **ag-Grid version:** 13.1.0

* **Browser:** Chrome 60.0.3112.113 (Official Build) (64-bit)

* **Language:** TypeScript 2.3.4

**Comment by rellis-of-rhindleton** [comment]
Attaching an example of an exported file with two rows - one as originally exported, one tweaked by hand to use the DateTime and Boolean data types.  The difference is obvious when opened in Excel.

(github made me rename from .xls to .txt)

[example-export.txt](https://github.com/ag-grid/ag-grid/files/1288295/example-export.txt)

**Comment by makinggoodsoftware** [comment]
These types are now supported
