### ISSUE TITLE
fullRow edit broken on horizontal scroll

### ISSUE THREAD

**Issue by britvik** [ag-grid/ag-grid#1899]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When row is in edit mode and you use horizontal scroll to show new columns, they stay in readonly mode.

**Expected behavior**
Columns should be editable after scroll.

**Minimal reproduction of the problem with instructions**
https://codepen.io/britvia/pen/prXLev
1. Double click on any cell
2. Scroll to the right
3. Newly shown columns are readonly, but they should be editable.

**What is the motivation / use case for changing the behavior?**
I expect it to work ;)

**Please tell us about your environment:**

* **ag-Grid version:** 13.1.0
Also issue in 13.0.0
Works in 12.0.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - this has now been fixed
