### ISSUE TITLE
removeEventListener not removing the listener

### ISSUE THREAD

**Issue by voliva** [ag-grid/ag-grid#1900]
As seen in https://ag-grid.com/forum/showthread.php?tid=4945, calling removeEventListener won't remove the listener created with addEventListener

This is because `addEventListener` uses `gridOptionsWrapper.useAsyncEvents()` (can be true or false) to append the listener to a specific list of events, and then `removeEventListener` always asumes that value to be false.

**Comment by seanlandsman** [comment]
As per the issue template please provide a repo or similar that we can use to investigate

thanks

**Comment by voliva** [comment]
@seanlandsman Here you have a plunkr: https://plnkr.co/edit/ijAFWwxbY8K17SduNxuj?p=preview

Should I open a new issue?

**Comment by devamir** [comment]
@seanlandsman Me too is facing this issue. I am using ag-grid v23.2.1
I am adding a listener like this
`gridApi.api.addEventListener('sortChanged', onSortChanged)`

and then removing it like this 
`gridApi.api.removeEventListener('sortChanged', onSortChanged)`

On some inspection i found that the ag-grid is adding the listener to `Set()` and then call `add/delete` methods.
Addition is working fine but on calling `delete` its returning `false`.

**Comment by seanlandsman** [comment]
Thanks for reporting this - I'll investigate and come back with what we find.

**Comment by ceolter** [comment]
cannot reproduce

here is a plunker
https://plnkr.co/edit/C9tnpCeGPnI8rdU5

**Comment by seanlandsman** [comment]
@devamir it looks like this was an issue in the past (ie 23.x) but has since been fixed - I suggest you upgrade to the latest version and retry

thanks
