### ISSUE TITLE
Ignoring fontName property for Excel Export

### ISSUE THREAD

**Issue by benschenker** [ag-grid/ag-grid#1901]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When modifying the font in excelStyles, ag-grid ignores the fontName property.

**Expected behavior**

ag-grid should set the fontName property when it is specified in excelStyles.  See: https://www.ag-grid.com/javascript-grid-excel/ `Export with Styles`
**Minimal reproduction of the problem with instructions**

Hard to make a plunkr to demonstrate an Enterprise feature.  But modify the basic excel export demo with the following excelStyles
```
excelStyles: [
      {
        id: "header", // this auto applies to header row
        font: { color: "#000000", fontName: "Helvetica"},
      }
    ]
```
and then download the excel exported file.
In the output file (can view if you open up in a text editor), notice a lack of `ss:FontName="Helvetica"` from https://msdn.microsoft.com/en-us/library/aa140066(v=office.10).aspx#odc_xmlss_ss:font
```
<Font ss:Bold="1" ss:Color="#000000" ss:Size="12"/>
```
**What is the motivation / use case for changing the behavior?**

The docs clearly state that ag-grid respects this property and propagates it to excel even though that is not happening.
**Please tell us about your environment:**

OSX Sierra, VS-Code, NPM, Express
* **ag-Grid version:** 13.1.1

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3208.0 Safari/537.36
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.1

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for raising this, this will be available in the next release of ag-grid.

Thanks
