### ISSUE TITLE
Filtration in nested json not work

### ISSUE THREAD

**Issue by Radzhab** [ag-grid/ag-grid#1903]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i want filter nested json its not working. Column **possible_position**
**UPDATED** and filtration by **treatment_date** not working too

**Expected behavior**
It will be filtered correctly
**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/3ws7XJs6T5U7PUn8B3h8?p=preview
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

KDE neon LTS User Edition 5.8, Rubymine IDE, Puma Server
* **ag-Grid version:** X.X.X

Version 13.1
* **Browser:**

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by makinggoodsoftware** [comment]
If you use compex data, the cellRenderer doesnt really explain to the grid how the underlying data should be interpreted,

I thikn in this case, you want to change your cellRenderer for a valueGetter like this:

valueGetter: function (params) {
                     var x =params.data.possible_positions.map(elem => elem.display_name).join(";");
                     return x;
                },

**Comment by Radzhab** [comment]
@makinggoodsoftware  thx for answer. Its work for **possible_position**. And what about **treatment_date** field? Its no filtering by date
