### ISSUE TITLE
Unable to set sheetname in the exportDataAsExcel()

### ISSUE THREAD

**Issue by Bhimisetty** [ag-grid/ag-grid#1905]
**I'm submitting a new issue here **
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Unable to set the sheet name in the export to excel method. There is no option available in definitions.

**Expected behavior**
There need to be option to set sheet name.

**Minimal reproduction of the problem with instructions**
Always

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 13.1.2

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

If you believe there is an issue please provide a repo or similar - we'll be happy to investigate

**Comment by Bhimisetty** [comment]
This is not the query i am asking, issue with your definition files. In the docs you provided the option to set the sheet name where as in the definitions it is not there to set the sheet name. Please look into that one.

**Comment by anil1712** [comment]
Yes, Its also not working for me. I am following the same what mentioned here
https://www.ag-grid.com/javascript-grid-excel/#gsc.tab=0
Trying to set the `sheetName` but its not working anymore. 

FYI: I am using the `ag-grid-react`
Thanks

**Comment by seanlandsman** [comment]
@Bhimisetty @anil1712 if you're enterprise users can you please raise a request on our forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

We'll try assist you further there

thanks
