### ISSUE TITLE
Aligned Grid Horizontal scrollbar bug

### ISSUE THREAD

**Issue by hoangdoantrung** [ag-grid/ag-grid#1906]
**I'm submitting a bug report here**

[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the example: "Aligned Grid as Footer" at https://www.ag-grid.com/javascript-grid-aligned-grids/#gsc.tab=0
When I scroll the horizontal scrollbar to the middle of the grid, the grid shakes non-stop so we could not see any thing. Everything returns to normal state if we scroll till the end.
I've got the same issue when implementing aligned grid as footer in my project. 

**Expected behavior**
The grid should just scroll to the correct position.

**Minimal reproduction of the problem with instructions**
Navigate to "Aligned Grid as Footer" example at https://www.ag-grid.com/javascript-grid-aligned-grids/#gsc.tab=0
then scroll the horizontal scrollbar to the middle of the grid.

**What is the motivation / use case for changing the behavior?**
Implement Aligned grid as footer.

**Please tell us about your environment:**
Any

* **ag-Grid version:** X.X.X
ag-grid version 13.1


* **Browser:**
Google Chrome

* **Language:** TypeScript 2.3

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-784 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by hoangdoantrung** [comment]
Hi,

Thanks for your feedback. I could not find AG-784 in the backlog. Do you plan to put it in the backlog later ?

Thanks,

**Comment by ceolter** [comment]
cannot reproduce this one. however this sounds like something i fixed a few weeks ago and is already released. please take a look at latest (or what's on our website now) and retest, should see it's gone.
