### ISSUE TITLE
tree data pagination

### ISSUE THREAD

**Issue by sklyarov-ivan** [ag-grid/ag-grid#1910]
**I'm submitting a ...
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I want to use tree data structure like https://www.ag-grid.com/javascript-grid-tree/#gsc.tab=0 with pagination.
for example grid show 25 items per page. (client side pagination)
1) I want to display nested rows for last row for ag-row-level-0. it shows nothing as far limit of items per page already reached (25)
2) I want to display nested rows for some other rows on that page for ag-row-level-0 (for example first one). In that case nested rows expanded BUT latest rows on page becomes hidden as far limit of items per page (ag-row-level-0 + ag-row-level-1) reached 25

**Expected behavior**
1) display rows on level-0 and level-1
2) display rows on level-0 and level-1
I expect to see pagination just by rows on level-0

**Please tell us about your environment:**
Sublime, ZF2, Webpack, React

* **ag-Grid version:** 13.0.1

* **Browser:**
Version 61.0.3163.79 (Official Build) (64-bit)

* **Language:** [React | ES6/7]

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by sklyarov-ivan** [comment]
@seanlandsman , are you sure that it isn't a bug ?
