### ISSUE TITLE
Scroll 2 grid vertically Synchronously

### ISSUE THREAD

**Issue by anandSep90** [ag-grid/ag-grid#1911]
I need to scroll 2 **grids(grid1, grid2)** synchronously because **grid2** is  next **grid1** <br>

got scroll bar position of the **grid1** by the below code

`this.gridOptions.api.getVerticalPixelRange()`

The output will be like `{top:20, bottom :90}`

found no api in ag-grid documentation. How to apply the position to **grid2** scroll bar.

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
