### ISSUE TITLE
EPERM : operation not permitted, unlick

### ISSUE THREAD

**Issue by ssashok10** [ag-grid/ag-grid#1912]
I am getting the similar error when I tried to install with Angular 4.2.4 [ npm i ag-grid --save ]. My node version is 8.4.0 and npm version is 5.4.1. The installation is conflicting something with "fsevents"...I even tried to use the command "npm cache clean --force"...Here is the error,

npm ERR! path I:\git\AngularAppSample\node_modules
fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'I:\git\AngularAppSample\node_modules\fsevents\node_modules\abbrev\package.j
son'
npm ERR! { Error: EPERM: operation not permitted, unlink 'I:\git\AngularAppSamplenode_modules\fsevents\node_modules\abbrev\packag
e.json'
npm ERR! stack: 'Error: EPERM: operation not permitted, unlink 'I:\git\AngularAppSample\node_modules\fsevents\node_modul
es\abbrev\package.json'',
npm ERR! errno: -4048,
npm ERR! code: 'EPERM',
npm ERR! syscall: 'unlink',
npm ERR! path: 'I:\git\AngularAppSample\nod
e_modules\fsevents\node_modules\abbrev\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\sath\AppData\Roaming\npm-cache_logs\2017-09-12T21_37_0
9_061Z-debug.log

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
