### ISSUE TITLE
Code weight

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid#1914]
I installed base version of ag-grid for Angular 4 and saw my build weight increased by ~700kb (minified code). It is more then whole Angular 4 with libraries. Is it OK? Maybe I can exclude some parts of grid?

ngx-datatable weights less then 100kb, all primeng components - 500kb

* **ag-Grid version:** 13.1.2

**Comment by seanlandsman** [comment]
Hi,

I'm afraid you can't exclude part of the library. It's worth noting that ag-Grid may not be small, but has no external dependencies, so the size you see is the whole picture.

**Comment by tamtakoe** [comment]
@seanlandsman It is too much for the such project. It looks like a lot of repeated or legacy code or excess abstractions in the ag-grid. Maybe it is OK for admin panels, but for customers it is too heavy.

I hope, you make more modular structure and more elegant code and investigate what is the heaviest thing (generally it is infinity scroll, drag & drop or the same stuff which can be optional). It will be good if your project will be more useful for enterprise after a year!
