### ISSUE TITLE
Unable to suppress browser context menu as of 10.0.0

### ISSUE THREAD

**Issue by Yoranium238** [ag-grid/ag-grid#1915]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As of ag-grid 10.0.0, we are no longer able to suppress the default context menu.  Prior to this (in 9.1.0), we were able to handle this suppression in the onCellContextMenu grid option.  Here, we used the event's preventDefault method to handle this and display a different context menu (non-ag-grid).

As a result, the default browser context menu displays upon right-click.  A second click displays our custom context menu.

gridOptions.suppressContextMenu=true does not prevent this either.

**We are using angular (4.2.4) as a development framework.**

**Expected behavior**
Selecting right-click for the context menu should display our context menu as it did previously without displaying the browser's default menu.

**Minimal reproduction of the problem with instructions**
This is an example.  We actually show our (non ag-grid) context menu here.  The effect is the same.

`
this.gridOptions.suppressContextMenu = true;

this.gridOptions.onCellContextMenu = (event: any) => {
      event.event.cancelBubble = true;
      event.event.preventDefault();
      alert("I should see only this");
};
`

**What is the motivation / use case for changing the behavior?**
It appears to be a bug.  The result is an unusable user experience.

**Please tell us about your environment:**
Windows, IntelliJ, NodeJS, NPM, Angular (4.2.4), Tomcat, PrimeNg 

* **ag-Grid version:** 13.1.2 (ag-grid-angular: 13.1.1)

* **Browser:**
Chrome, IE, Edge, Firefox

* **Language:** [all | TypeScript 2.3.4 ]

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-787 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi guys,

We are going to close this one.

Have a look at postProcessPopup(params) | Allows user to process popups after they are created. Applications can use this if they want to, for example, reposition the popup.
-- | --

You should be able to hide the popup from there and do your own thing.

**Comment by adriantoczydlowski** [comment]
@Yoranium238 
Setting **suppressAsyncEvents** to true will solve the problem.

**Comment by jjuszczec** [comment]
Is postProcessPopup available in the free version of ag-grid?
