### ISSUE TITLE
Clear button doesn't clear filters or fire `FilterChanged` changed event

### ISSUE THREAD

**Issue by hyyan** [ag-grid/ag-grid#1916]
**I'm submitting a ...** 
```
[x ] bug report
```

**Current behavior**
The filter's clear button does not clear the applied filter or fire `FilterChanged` event

**Expected behavior**
When the clear button is clicked the filter will be removed and the event will be fired

**Minimal reproduction of the problem with instructions**
[MINIMAL DEMO](https://plnkr.co/edit/kHZ499DhcVJ87Ane4UPy)

**Please tell us about your environment:**
Win10 , VScode, bower

* **ag-Grid version:** 13.1.2

* **Browser:** Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
The text is perhaps misleading here - the clear filter only clears the value in the filter box. You still need to apply the change for it to take effect

**Comment by yehudahkay** [comment]
Thanks for the framework! This behavior is a little unexpected
