### ISSUE TITLE
Material theme is missing a background color override 

### ISSUE THREAD

**Issue by DefunctExodus** [ag-grid/ag-grid#1917]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using material theme with custom color overrides.

**Expected behavior**

I would expect the[ `.ag-tool-panel`](https://github.com/ag-grid/ag-grid/blob/master/src/styles/ag-theme-material.scss#L541) background color to have an override variable or
inherit from `$ag-mat-panel-background`

**Minimal reproduction of the problem with instructions**

N/A

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 13.1.2

* **Browser: All

* **Language:** [scss]

**Comment by petyosi** [comment]
Hi, 

thank you for the report - I have pushed a fix for it. The change might not make it in the next release, due this week, but it will be available in the subsequent ones.
