### ISSUE TITLE
Grid Cell Receives Focus (and outline) when suppressCellSelection is set to true

### ISSUE THREAD

**Issue by nrgonzalez777** [ag-grid/ag-grid#1918]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When clicking on a grid cell in **Chrome**, the focus style (with a default blue border) is applied to indicate that the cell has been clicked on when the suppressCellSelection flag in grid options is set to true. While this behavior is present in the current version (13.1.2) it appears that this first broke in 13.0.0.

**Expected behavior**

When the flag is set to true, the focus style should not be applied because focus should not be set.

**Minimal reproduction of the problem with instructions**

Plunker of previous behavior:
https://plnkr.co/edit/yqQ68TqxF5KPjwH6PXS7

Plunker of current (broken) behavior:
https://plnkr.co/edit/aUj5d3nxdj1TjJHlhacZ

Make sure to view in Chrome.

**What is the motivation / use case for changing the behavior?**

Behavior regression

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

13.1.2

* **Browser:**

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-828 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by abhinavkareer** [comment]
hi I faced the same issue and solved it by this fix :)
Cheers


.ag-cell:focus{
    border:none !important;
    outline: none !important;
}

**Comment by LittleBreak** [comment]
thanks for your sharing, it works @abhinavkareer

**Comment by ceolter** [comment]
the solution above is correct, it's a CSS issue with browser focus, not a grid issue.

the grid has it's own internal focus mechanism, where it puts a CSS border on the cell.

however chrome also puts a blue border on focused cells, which is something at the browser level and we cannot prevent.

to stop the default browser focus border, apply the CSS as described above.

**Comment by Tsimon-Dorokh** [comment]
The browser focus appears because tabindex attribute for the cell is set. The solution might be not to set tabindex unless it is set for a purpose.

**Comment by jcrosetto** [comment]
As @Tsimon-Dorokh said the cell still gets focus because the tabindex attribute is set. If I put an input in the cell, this causes the cell to get focus instead of the input inside it when tabbing.

**Comment by KD1024** [comment]
An addition for what @Tsimon-Dorokh and @jcrosetto point out here, I want to use tab to focus on my input/buttons inside the cell, hide the css focus does not do the trick, the focus is still there, just cannot see it. The temporary solution I found is to create an empty tabToNextCell function, like this:
`tabToNextCell = function tabToNextCell(params) {
  };`
and in ag-grid, add that attribute:
<ag-grid-angular *ngIf="rowData"
    [rowData]="rowData"
    [columnDefs]="columnDefs"
    [defaultColDef]="defaultColDef"
    ...
    ...
    **_[tabToNextCell]="tabToNextCell"_**
    (gridReady)="onGridReady($event)">
</ag-grid-angular>

This works for me that tab can works on the buttons and other elements within the cells.

**Comment by workplaceninja** [comment]
.ag-cell-focus,.ag-cell-no-focus{
border:none !important;
}
.ag-cell:focus{
border:none !important;
outline: none;
}


This code makes all focusing on all columns not work.  If you want it on one column, you can target it by name (or other means):

.ag-cell-focus[col-id=thumbpath], .ag-cell-no-focus[col-id=thumbpath] {
	border:1px solid rgba(0,0,0,0) !important;
}
.ag-cell:focus[col-id=thumbpath] {
	border:1px solid rgba(0,0,0,0) !important;
	outline:none;
}

**Comment by aarondr77** [comment]
Although the css aspect is part of the problem, I'm particularly interested in supressing the cellFocussedEvent from being fired, which I believe the ```suppressCellSelection``` is supposed to do according to [this](https://www.ag-grid.com/javascript-grid-properties/#reference-selection). 

For context, I'm looking to make an Excel-like experience where a user, while using my custom cell editor, is able to click on another cell without leaving causing the cell editor to close. According to the [editing](https://www.ag-grid.com/javascript-grid-cell-editing/#stop-end-editing) documentation, the cell editor should close when another cell is focused on. So having the suppressCellSelection event actually suppress the CellFocussedEvent is important to my use case.

**Comment by babarkh7** [comment]
Is there any update on this issue ?
I am facing the same issue in ag-grid. If you are in editing a row and you click on any other row in the grid then it stop editing of the row and set focus to the other row. I don't want to stop editing if the user click on any other row in the grid.
**This is not the CSS issue. It is something related to event firing**. As per my analysis, if you click any other row in the grid then it trigger the cellFocus event and on that it stop the editing of the existing row.
What i want is to prevent the cell focus event to stop editing of the existing row (if there is some row in edit mode).
I have tried all of these provided suppress input properties (i.e suppressCellSelection, etc) but non of them is providing the functionality we wants.

**Comment by zeekay18** [comment]
I think you might want to check **_suppressCellFocus_** option
