### ISSUE TITLE
Use case for doesRowPassOtherFilter 

### ISSUE THREAD

**Issue by prilutskiy** [ag-grid/ag-grid#1920]
What’s the use case for doesRowPassOtherFilter? Found nothing in docs, except for function description. Can anyone provide at least simple example? Interested in react usage in particular, but would appreciate anything useful though. 
“

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
