### ISSUE TITLE
Arrow up key won’t move selection one row up

### ISSUE THREAD

**Issue by jzav** [ag-grid/ag-grid#1923]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Please, download video from https://ln.sync.com/dl/54cbe5a00/kq8mdjmt-2mtgajn9-27vwr2r8-gx4uq8q6.

As you can see, I run a query that populates grid.

Then I click alt + left, that is registered via document.addEventListener('keydown', ...):
```
// alt + left
	if (e.altKey && e.keyCode == 37) {
		var x = gridOptions.columnApi.getAllColumns();
		var col = gridOptions.api.getFocusedCell();
		var rowN;
		if (!col) {
			rowN = 0;	
		} else {
			rowN = col.rowIndex;
		}
		gridOptions.api.ensureIndexVisible(rowN);
		gridOptions.api.ensureColumnVisible(x[1].colId);
		gridOptions.api.setFocusedCell(rowN, x[1].colId);
	} 
```

And then I click end, that is registered via params.eGridCell.addEventListener('keydown', ...):
```
// end
	if (e.keyCode == 35) {
		e.stopPropagation();
		e.preventDefault();
		var col = gridOptions.api.getFocusedCell();
		var rowCount = gridOptions.api.getModel().getRowCount();
		gridOptions.api.ensureIndexVisible(rowCount - 1);
		gridOptions.api.setFocusedCell(rowCount - 1, col.column.colId);
	}
```
Then I click arrow up and grid starts to scroll up as when I wheel mouse up.

**Expected behavior**
Selection is just moved one row up.
 
**Please tell us about your environment:**
W7 Home Premium SP1, Firefox 55.0.3 (64-bit), ag-grid v13.1.2, plain javascript, my project: https://addons.mozilla.org/en-US/firefox/addon/at-your-command/

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by jzav** [comment]
Thank you for your answer. But I do not consider this support query. This is a bug that do not happen when using ag-grid version 11 (I downgraded back to it). It has to be something with the new rendering engine (I do not know what). Faster rendering engine is also the reason I would like this issue to be solved (since it prevents me from upgrading to the latest version of ag-grid). Is there something I can do to help isolate this issue?

**Comment by jzav** [comment]
Just tried v 13.2. and issue still persists. Please, help.
