### ISSUE TITLE
Arrow up key moves selection to a completeley different column

### ISSUE THREAD

**Issue by jzav** [ag-grid/ag-grid#1924]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Please, download video from https://ln.sync.com/dl/a77feb6f0/hb9dq62y-haz4qwsj-gs9x5d8z-7e2ejp97.

As you can see, I click/focus cell with value [drag rows]...

Then I click alt + w, that is registered via params.eGridCell.addEventListener('keydown', ...):
// alt + w	
	if (e.altKey && e.keyCode == 87 && !e.ctrlKey) {
		e.stopPropagation();
		e.preventDefault();	
		var col = gridOptions.api.getFocusedCell();
		gridOptions.columnApi.autoSizeColumn(col.column.colId);
	}

And then I click alt + right, that is registered via document.addEventListener('keydown', ...):
// alt + right
	if (e.altKey && e.keyCode == 39) {
		var x = gridOptions.columnApi.getAllColumns();
		var col = gridOptions.api.getFocusedCell();
		var rowN;
		if (!col) {
			rowN = 0;	
		} else {
			rowN = col.rowIndex;
		}
		gridOptions.api.ensureIndexVisible(rowN);
		gridOptions.api.ensureColumnVisible(x[x.length - 1].colId);
		gridOptions.api.setFocusedCell(rowN, x[x.length - 1].colId);
	} 

Then I click arrow up and grid moves selection to a completely different column.

**Expected behavior**
Selection is just moved one row up. This issue is perhaps somewhat related to https://github.com/ag-grid/ag-grid/issues/1509.

**Please tell us about your environment:**
W7 Home Premium SP1, Firefox 55.0.3 (64-bit), ag-grid v13.1.2, plain javascript, my project: https://addons.mozilla.org/en-US/firefox/addon/at-your-command/

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by jzav** [comment]
Thank you for your answer. But I do not consider this support query. This is a bug that do not happen when using ag-grid version 11 (I downgraded back to it). It has to be something with the new rendering engine (I do not know what). Faster rendering engine is also the reason I would like this issue to be solved (since it prevents me from upgrading to the latest version of ag-grid). Is there something I can do to help isolate this issue?

**Comment by jzav** [comment]
Just tried v 13.2. and issue still persists. Please, help.
