### ISSUE TITLE
Api for refreshing row css / accessing row html

### ISSUE THREAD

**Issue by britvik** [ag-grid/ag-grid#1925]
**I'm submitting a ...**
```
[X] feature request
```

**Current behavior**
getRowClass is only called when row is fully rerendered

**Expected behavior**
Have API for changing only css without redrawing content.
Or provide access to api.rowRenderer.rowCompsByIndex or perhaps RowNode could hold a reference to RowComp so we could access html directly?

**What is the motivation / use case for changing the behavior?**
1. I have editable row and I want to change class of row to "invalid" when user inputs invalid value. But I can't refresh entire row, because I would lose focus inside input field.
2. I want to focus first editable input when editing of entire row started.

Right now I'm accessing private properties and I really don't like that :(.

**Please tell us about your environment:**

* **ag-Grid version:** 13.1.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
