### ISSUE TITLE
Infinity scroll doesn't work with pagination mode

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid#1926]
I want to use infinity scroll with pagination. Unfortunately it doesn't work. If I set pagination=true, infinity scroll becomes disabled and I can get new data only by pagination buttons

* **ag-Grid version:** 13.1.2
* **Angular:** 4.0.0

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
