### ISSUE TITLE
Add callback for keypress

### ISSUE THREAD

**Issue by britvik** [ag-grid/ag-grid#1927]
**I'm submitting a ...**
```
[X] feature request
```

**Current behavior**
When I press enter (or other key that starts edit) I don't have enough control over what's happening.

**Expected behavior**
I would like to be able to stop this event, or call my own logic (api for editing).

I think the function processKeyboardEvent in gridPanel.ts would be the right place for this. Just call user defined function with eventName and keyboardEvent as parameters and check return value to know if it should continue or not.

**What is the motivation / use case for changing the behavior?**
I have a button for starting edit mode and I would like to call same logic when I press enter (or other keys) AND I would like to stop key event when row should not be editable.

I'm using **onRowEditingStarted** and **isCancelBeforeStart** right now, but in some cases they are not suitable as the former can't stop the editing and latter is called too late.

**Please tell us about your environment:**
* **ag-Grid version:** 13.1.2

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
