### ISSUE TITLE
How to get/set first row position when infinity scroll

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid#1928]
There is no way to set scroll to show the row in the top position. `ensureIndexVisible` set it on top/bottom or do nothing if row is already on the screen. Also you can't know what row in the first position during the scroll. And of course you don't know how many rows are actually on the screen. Just you know about viewport, but this information doesn't help you. Fix it, please.

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by angularDevd** [comment]
+1
