### ISSUE TITLE
Make cell editable based on value change in value of another cell

### ISSUE THREAD

**Issue by RoshanRoyal** [ag-grid/ag-grid#1929]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
editable attribute is boolean or function that takes values or resolves value on existing data.

**Expected behavior**
editable can have function that can detect value change in another cell to make it editable or non-editable.
  

**What is the motivation / use case for changing the behavior?**

want to make a field editable dynamically  based on another value selection from dropdown in grid.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

This is already possible by hooking into events and using the api - please refer to ag-grid.com for details on how either can be used

thanks
