### ISSUE TITLE
AgGrid issue with IE11 and Aurelia

### ISSUE THREAD

**Issue by cchapin08** [ag-grid/ag-grid#1930]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using the ag-grid inside an Aurelia based app. It works great except in IE. I created a extremely simplified example: https://plnkr.co/edit/FxSJhzrj3d5pqBGXgUz5

When loading the app in IE, the ag-grid hits a null reference when trying to set up the group expand icons of the column group header. 

**Expected behavior**
The ag-grid should work as designed in IE11 inside an Aurelia app.

**Minimal reproduction of the problem with instructions**
See plunker example linked above

**What is the motivation / use case for changing the behavior?**
Using ag-grid in IE with Aurelia

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-825 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by cchapin08** [comment]
Hello Sean,

Any chance for a resolution or workaround for this issue? We are building a new Aurelia app and are evaluating the ag-grid component.  It is our leading candidate right now by far, but this IE issue may be a showstopper. 

In the non-bundled version there is no issue, but when bundled with the systemJS builder component errors occur, possibly due to circular references. I haven't looked into it enough to be sure. So instead of bundling ourselves we opted to use the pre-bundled version, but now we are facing this issue in IE. 

For this application we must support IE11 and I would love a resolution as I feel this grid component is far superior to the alternatives.

Thank you,
Chris

**Comment by makinggoodsoftware** [comment]
Hi

Sorry for the late reply, if you are still evaluating and this is still an issue for your, I would suggest you contact info@ag-grid.com to request access to the customers forum, then we will take it from there

Thanks
