### ISSUE TITLE
autoGroupColumnDef doesn't set empty headerName

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid#1935]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```js
autoGroupColumnDef:{
    headerName:'',
}
```
set header name by default (f.e. Group)

**Expected behavior**
This code has to set empty header name

* **ag-Grid version:** 13.2.0

* **Browser:**
last Chrome

* **Language:** [TypeScript]

**Comment by makinggoodsoftware** [comment]
HI,

If you try this headerName:' ' it should work.

You just need to add a blank space, I have raised AG-857 in our end to track this

**Comment by makinggoodsoftware** [comment]
This now should be working

**Comment by JohnMasterson** [comment]
Just to confirm this was include in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
