### ISSUE TITLE
valueFormatter doesn't work with autoGroupColumnDef

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid#1936]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```js
autoGroupColumnDef:{
    valueFormatter(params) {
          return 'CUSTOM';
    }
}
```
Do nothing

**Expected behavior**

Set 'CUSTOM' text for each cell

* **ag-Grid version:** 13.2.0

* **Browser:**
last Chrome

* **Language:** [TypeScript]

**Comment by petyosi** [comment]
Thank you, confirming the bug ([repro](https://plnkr.co/edit/bkj7rCnvfPmLCOu6xkMr?p=preview)).

**Comment by makinggoodsoftware** [comment]
You should be able to get the formatter to work if you add it to the original column ie.. Add it to the year or country

**Comment by Mykhailo-Seniutovych** [comment]
> You should be able to get the formatter to work if you add it to the original column ie.. Add it to the year or country

What if I want to have different formatting for the auto group column and the corresponding column in the grid? Is there a way to do it?
