### ISSUE TITLE
Infinite scrolling with pagination and customize pager info

### ISSUE THREAD

**Issue by fxvits** [ag-grid/ag-grid#1937]
[ ] bug report 
[ ] feature request
[ X] support request 

Hi guys,

Thank you for your great job. Ag-grid is awesome.

I'm using the last version of the ag-grid and I transformed my old pagination way by the recommended one (Infinite scrolling + pagination) and it works fine. But I would like to know if the last button of the pager could not be enabled (because on server side I know the total records count and thus the page count) and replace the word "more" by the real page and records count ?

Thank
FX

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
