### ISSUE TITLE
There is no merge cells?

### ISSUE THREAD

**Issue by DennisDeng920525** [ag-grid/ag-grid#1938]
In ag-grid, I can find the function "column spanning" from [https://www.ag-grid.com/javascript-grid-column-spanning/?framework=angular#gsc.tab=0](url) 
 But i can not find row spanning like this:
![image](https://user-images.githubusercontent.com/28853489/30800904-1bd91114-a214-11e7-9bde-4395eff2a4b9.png)
What can I do in order to achieve this effect? Thx!

**Comment by seanlandsman** [comment]
Please refer to the documentation here: https://www.ag-grid.com/javascript-grid-column-spanning/#gsc.tab=0

**Comment by DennisDeng920525** [comment]
Sorry! You may have misunderstood my meaning. Can you watch my question again? I know you say and have used it in my project. But I need a vertical merger.  Can you help me again?  Thank you very much!

**Comment by mistrykaran91** [comment]
@DennisDeng920525, Is there any solution or workaround for this ?

**Comment by DennisDeng920525** [comment]
yes I have already implemented it in my system. But need you buy me a coffee i have tell you. It's long as follows
![tim 20180312162435](https://user-images.githubusercontent.com/28853489/37272549-e21adcbe-2611-11e8-84dc-0289bb97d4c9.png)

**Comment by endlesskid** [comment]
@DennisDeng920525 can you show me how to justified-content the display text in merged rows? I've tried but it wasn't work at all, thanks in advance!
