### ISSUE TITLE
Scroll for merged columns

### ISSUE THREAD

**Issue by sarvanbose** [ag-grid/ag-grid#1940]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When merge the cells(colspan) more than 100 and scroll to view the end of the cell. It lost the css property 

**Expected behavior**
The grid should display css property for the merged cell

**Please tell us about your environment:**
Any

* **ag-Grid version:** X.X.X
ag-grid version 13.1

* **Browser:**
Google Chrome

* **Language:**  TypeScript 2.3

**Comment by seanlandsman** [comment]
Please follow the issue template when raising new issues. Specifically, please provide a repo of the issue that we can use as a baseline to investigate.

thanks
