### ISSUE TITLE
Overlay template (loading and no rows) supports only HTML

### ISSUE THREAD

**Issue by guybensh** [ag-grid/ag-grid#1942]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently the 'overlayNoRowsTemplate' and 'overlayLoadingTemplate' only works with HTML plain.

**Expected behavior**
As a React developer it will be very useful if those overlay templates will also support a React component. 

**What is the motivation / use case for changing the behavior?**
External modules (like material-ui) can be used for loading.
Also, complex template can be wrapped in React component.

* **Browser:**
all

* **Language:**
all

Thanks,
Guy

**Comment by rmc-software** [comment]
Hi,

Thank you for this enhancement request. I have created AG-886 to track this. We'll provide update when we have more details.

Thanks

**Comment by milleraundra** [comment]
+1 for Angular too!

**Comment by makinggoodsoftware** [comment]
This is now available

**Comment by mariopeixoto** [comment]
Any docs on how to use this functionality?
