### ISSUE TITLE
How to use autoSizeColumns in ag-grid?

### ISSUE THREAD

**Issue by suspatamil** [ag-grid/ag-grid#1943]
I'm used  
onGridSizeChanged: () => {
        this.gridOptions.api.sizeColumnsToFit();
    }  
But i want resize autoSizeColumns in ag-grid.
Anyone help me...

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
