### ISSUE TITLE
ensureIndexVisible works incorrect with row groups

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid#1947]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have infinity table with expanded row group (enterprise row model) and do `ensureIndexVisible(lastRowIndex)` it will show row with `lastRowIndex` minus `grouppedRowsCount` (or something like this). You never ensure last index visible in this case

**Expected behavior**

`ensureIndexVisible(index)` has to ensure index visible in any case

* **ag-Grid version:** 13.2.0

* **Browser:**
last Chrome

* **Language:** [TypeScript]

**Comment by rmc-software** [comment]
This sounds like a configuration issue. 

Please could you use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
