### ISSUE TITLE
css being cut out when editing top pinned row.

### ISSUE THREAD

**Issue by pycraft114** [ag-grid/ag-grid#1948]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ v ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**When editing unpinned row.**
<img width="937" alt="2017-09-28 2 28 12" src="https://user-images.githubusercontent.com/24728657/30950702-89a4d81c-a459-11e7-982c-b61179fef9b7.png">

**When editing top pinned row**
<img width="946" alt="2017-09-28 2 28 24" src="https://user-images.githubusercontent.com/24728657/30950714-9cc0485a-a459-11e7-9955-46fdaa3aeb63.png">

**Used theme : ag-theme-material**
As seen above when editing top pinned row, the css of input is cut out unlikely when editing unpinned row.

**Expected behavior**

It would be nice to show the whole input css even though when editing pinned row.  

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Im using a top pinned row for a row creation form layout.

**Please tell us about your environment: Webstorm**

* **ag-Grid version:** 12.0.2

* **Browser: Chrome**

* **Language:** [all]

**Comment by rmc-software** [comment]
Hi,

Thanks for reporting this. I have created AG-887 to track this. We'll update this issue when we have further information.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

This should be fixed now

Thans
