### ISSUE TITLE
Wrong padding for leafs, when setting the padding of the nodes

### ISSUE THREAD

**Issue by PranKe01** [ag-grid/ag-grid#1949]
**I'm submitting a ...**
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I got a tree and I want to align it. I am using padding in the colRendererParams. I set it to 18. But the tree is misaligned, because leafs are aligned with a padding of 10.

**Expected behavior**
https://github.com/ag-grid/ag-grid/blob/22ea28d9d8487197aea5c89efc621f5829a11b76/dist/lib/rendering/cellRenderers/groupCellRenderer.js#L111
Here the padding is fix! It should take the same padding value. For example, if you set the padding to 50, the function this.gridOptionsWrapper.getLeafNodePaddingAddition() shall return 50, too!

**Minimal reproduction of the problem with instructions**
Create a tree and set the padding to 50. You will see, that the function getLeafNodePaddingAddition() still returns 10 as a padding, which is wrong.

**What is the motivation / use case for changing the behavior?**
The motivation is, that with the fix value of 10, the tree is not aligned correctly.

**Please tell us about your environment:**
Independend from environment.

* **ag-Grid version:** 10.0.0 & 13.2.0

* **Browser:**
Google Chrome - but the bug is browser independend

* **Language:** all

**Comment by rmc-software** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
