### ISSUE TITLE
Importing ag-Grid Sass files using @import throws errors

### ISSUE THREAD

**Issue by n3ps** [ag-grid/ag-grid#1950]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Importing the ag-Grid Sass files in an angular-cli, sass-based project results in Webpack errors.

**Expected behavior**
As per documentation, ag-Grid Sass files should be ready to use in a Webpack-configured project.

**Minimal reproduction of the problem with instructions**
1. ng new project --style=scss
2. npm i ag-grid
3. In styles.scss: `@import "~ag-grid/src/styles/ag-grid"`
4. ng serve

**What is the motivation / use case for changing the behavior?**
In projects that provide Sass files (i.e. Bootstrap) @import works fine OOTB

**Please tell us about your environment:**
Windows 10, node 6.11.1, npm 5.3.0

* **ag-Grid version:** 13.2.0

* **Browser:**
N/A. Compile-time error

* **Language:** [all]

**Comment by n3ps** [comment]
Looks like a bug in the icons path.

Possible workaround is declaring this prior to the import:
`$ag-icons-path: '~ag-grid/src/styles/icons/';`

**Comment by petyosi** [comment]
Hi, 

the workaround you suggest is actually [described in our documentation](https://www.ag-grid.com/javascript-grid-themes/material-theme.php?framework=all#gsc.tab=0) since this is a common pitfall in with Sass / Webpack. 

> The ag grid icons path should be re-adjusted when importing the scss file. This is a common problem, described in the Sass(scss) loader project. The theme exposes the $ag-mat-icons-path variable to address that. The example from above showcases how to override the variable.

**Comment by petyosi** [comment]
Another thing that might help you: We maintain a working sample project with angular-cli, angular material and the material theme [available in the ag-grid-material repo](https://github.com/ag-grid/ag-grid-material/).

**Comment by totszwai** [comment]
In v20 (and possibly newer version), `$ag-icons-path` is now `$icons-path`. Also the path is slightly different too. The following seem to work for me.
`$icons-path: '~ag-grid-community/src/styles/ag-theme-base/icons/';`
