### ISSUE TITLE
React Grid With Pivot Looks Very Weird

### ISSUE THREAD

**Issue by JimTheMan** [ag-grid/ag-grid#1951]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I set "pivotMode" on the React AgGrid it does not show data properly.

For some reason Github won't let me upload images here, but with "pivotMode" turned on my grid had one single column that says, "sum(Metric)" with a value "la(1)". There is also no column with a header "Groups" which is something that I wanted. 

It is very confusing to use this grid in a React project because there are literally ZERO examples in the docs that actually make use of the <AgGridReact> tag!

**Expected behavior**

I want the left header to say "Groups" with the label names under them, and a column labeled "Nums" with a cell under it showing the sum of nums with that label. I'm trying to use these arrays for the columns and rows:

```
columns: [
      {headerName: "Metric", field: "metric", width: 100},
      {headerName: "Currency", field: "currency", width: 120},
      {headerName: "discriminator", field: "discriminator"},
      {headerName: "label", field: "Label", minWidth: 50, width: 100, rowGroup: true, columnGroupShow:"open"},
      {headerName: "Nums", field: "numOfThings", width: 100, value:true, aggFunc:"sum"}
    ]

    rows: [{
      "numOfThings": 1,
      "discriminator": "foo",
      "Label": "la",
      "metric": "20",
      "currency": "EUR"
    }
```

Here how I am creating the grid:

 ```
<AgGridReact className={"grid-container"}
          columnDefs={this.props.columns}
          rowData={this.props.rows}
          groupUseEntireRow
          enableColResize
          pivotMode
          onSelectionChanged={this.onSelectionChanged}
          onCellClicked={this.onCellClicked}
          onClick={this.onCellClicked}
          onGridReady={this.onGridReady}>
        </AgGridReact>
```

It looks normal when I take off pivotMode.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 13.2.0

* **Browser:** Chrome

* **Language:** ES6

**Comment by rmc-software** [comment]
Hi,

This seems like expected behaviour and isn't related to React in anyway.

In this plain JS example enable the tool panel (right click on any cell to reveal context menu). Then remove the group column:

https://plnkr.co/edit/SsH0dXsv3pHsZavskthf?p=preview

**Comment by JimTheMan** [comment]
Thanks, I was able to fix it by removing _ autoSizeColumns_ when creating the Ag-Grid component.
