### ISSUE TITLE
Incorect BaseFilter interface realisation

### ISSUE THREAD

**Issue by futbolistua** [ag-grid/ag-grid#1952]
Hi I'm updated ag-grid to the latest version 13.2.0 and there is error
`node_modules\ag-grid\dist\lib\filter\baseFilter.d.ts
(21,31): error TS2420: Class 'BaseFilter<T, P, M>' incorrectly implements interface 'IFilterComp'.
  Types of property 'afterGuiAttached' are incompatible.
    Type '(params: IAfterGuiAttachedParams) => void' is not assignable to type '((params?: IFilterAfterGuiAttachedParams | undefined) => void) | undefined'.
      Type '(params: IAfterGuiAttachedParams) => void' is not assignable to type '(params?: IFilterAfterGuiAttachedParams | undefined) => void'.
        Types of parameters 'params' and 'params' are incompatible.
          Type 'IFilterAfterGuiAttachedParams | undefined' is not assignable to type 'IAfterGuiAttachedParams'.
            Type 'undefined' is not assignable to type 'IAfterGuiAttachedParams'.`

**Comment by futbolistua** [comment]
Are you going to fix it?

**Comment by rmc-software** [comment]
Hi,

This should have been fixed in 13.3.1

Thanks

**Comment by futbolistua** [comment]
Thanks

**Comment by chrumck** [comment]
I don't think it's fixed yet: #1889
