### ISSUE TITLE
AG-Grid Header Alignment not Working 

### ISSUE THREAD

**Issue by mohmoniem281** [ag-grid/ag-grid#1953]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I changed both ag-header-cell-label & ag-header-cell CSS parent classes to text-align:center however all text in grid header is still left aligned.

**Expected behavior**

To be able to change the text alignment in the grid header

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

change text align to centered in grid header

**Please tell us about your environment:**

ag react grid. mvc project

* **ag-Grid version:** X.X.X

ag-grid-enterprise v13.0.0

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by danharner** [comment]
Another workaround is to create a header component and use it on the columns whose header text you want to not align left. But that's a bit heavy-handed compared to simply setting cellStyle or cellClass for body cells you want to align differently.

**Comment by rmc-software** [comment]
I'm closing this as this is not a defect.

As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by sshiling** [comment]
The @teuf22 solution is great when we need the header cells been "center" aligned but I need some of them to be "flex-end" aligned. How can I do it?
