### ISSUE TITLE
second level nodes counts in pagination

### ISSUE THREAD

**Issue by amit034** [ag-grid/ag-grid#1955]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
**Current behavior**

when using pagination with grouping the child nodes counts as records  in the pagination when expanding a row. records from the first page jumps to the next. even child nodes that are exceeds the pagination page limit.
**Expected behavior**

exacted only top level records will count in the pagination results. and all child nodes will display in the current page. (this is very strange behavior that it jumps to the next page when using master details.  
**Minimal reproduction of the problem with instructions**
see simple example https://plnkr.co/edit/ueRUxEeVE8pzkIT5cZrs?p=preview

**What is the motivation / use case for changing the behavior?**
when using master details i would like to see the details of the last record in the same page

**Please tell us about your environment:**

relevant to all OS

* **ag-Grid version:** X.X.X

version : 12.0.2 (but it reproduce in the documentation examples 

* **Browser:**

All Browsers ES6
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by rmc-software** [comment]
This is not a defect. When you expand a node it increases the number of rows displayed. Rows that don't fit on the page will appear in the next page.

As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by amit034** [comment]
https://stackoverflow.com/questions/46811472/ag-grid-second-level-nodes-counts-in-pagination
