### ISSUE TITLE
removeEventListener not removing the listener

### ISSUE THREAD

**Issue by voliva** [ag-grid/ag-grid#1956]
**I'm submitting a ...** 
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As seen in https://ag-grid.com/forum/showthread.php?tid=4945, calling removeEventListener won't remove the listener created with addEventListener

**Expected behavior**
removeEventListener should remove the event listener. 
This is because addEventListener uses gridOptionsWrapper.useAsyncEvents() (can be true or false) to append the listener to a specific list of events, and then removeEventListener always asumes that value to be false.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/ijAFWwxbY8K17SduNxuj?p=preview
This plunkr starts a click listener on the table cells, and after 5 seconds it removes that listener.
When the listener is set up, every time you click you should see the log message "Cell Clicked". It shouldn't log more "Cell clicked" messages after the event listener has been removed.

**What is the motivation / use case for changing the behavior?**
This is a terrible behaviour bug and/or memory leak.

**Please tell us about your environment:**
* **ag-Grid version:**
13.1.2

* **Browser:**
Chrome 61.0.3163.100

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by rmc-software** [comment]
Hi,

Yes this does like an issue. Thanks for reporting it to us.

I have created AG-888 to track this and we'll provide updates here when we have them.

Thanks

**Comment by ceolter** [comment]
now fixed, will be in next release.

**Comment by samkumarblackbook** [comment]
In which release AG-888 is fixed? I am having a similar issue and would like to get the correct version please. Thanks

**Comment by JohnMasterson** [comment]
Just to confirm this was include in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
