### ISSUE TITLE
Select/deselect all columns in tools menu

### ISSUE THREAD

**Issue by Abrissirba** [ag-grid/ag-grid#1960]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request 
```

**Current behavior**
The user must deselect or select every column indvidually. 

**Expected behavior**
A select/deselect all button for columns in the tools menu

**What is the motivation / use case for changing the behavior?**
Make it easier to select columns when there are very many columns

**Comment by petyosi** [comment]
Thank you for the suggestion. I have logged it as AG-977 in our internal tracker. The dev team will review it.

**Comment by makinggoodsoftware** [comment]
Hi please check the progress of this item in our pipeline

https://www.ag-grid.com/ag-grid-pipeline/

Thanks
