### ISSUE TITLE
AG Grid does not sanitize data displayed on the grid!

### ISSUE THREAD

**Issue by killyosaur** [ag-grid/ag-grid#1961]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If a string value containing HTML comes into the grid, the grid just displays it without sanitizing the data, In some instances, this causes the grid to break

**Expected behavior**

**What is the motivation / use case for changing the behavior?**

Preventing the grid from breaking due to unsanitized data in the grid (per example)
prevent possible XSS issues

**Please tell us about your environment:**

OS: Win 10, IDE VS 2017, Bower

* **ag-Grid version:** X.X.X

13.2.0

* **Browser:**

Both IE and Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mattrichard** [comment]
I'm having the same/similar issue. Ever since 13.0.0, the grid is treating all Field data as HTML directly. This is both breaking things (by not displaying the data correctly) and is a security concern.

**Comment by dominikg** [comment]
This is a regression, i remember that some time ago the default cell renderer was changed from using e.innerHtml = val to e.textContent = val. The latter is documnted also here: https://www.ag-grid.com/javascript-grid-cell-rendering/#gsc.tab=0

**Comment by dominikg** [comment]
I also agree with mattrichard that this is a security issue as it enables code injection.

**Comment by ceolter** [comment]
just fixed. will be in next release.
