### ISSUE TITLE
No correct way to show row details (enterprise model)

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid#1965]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Master Detail grid example works with enterprise model if you use grouping only (Flower nodes work with inMemory row model only). It is incorrect way because you use more difficult and slow system to do simple thing.

**Expected behavior**
Add api for expand/collapse full-width children row for enterprise model. Infinity scroll has to work correct with expanded rows

**What is the motivation / use case for changing the behavior?**
It is common case if row has details but no grouping

* **ag-Grid version:** 13.3.0

* **Browser:** all

* **Language:** all

**Comment by rmc-software** [comment]
Master Detail should not be used in conjunction with the Enterprise Row Model.

Closing.

**Comment by tamtakoe** [comment]
Sorry, this is popular business task to use row details + infinty scroll and other features of enterprise model

**Comment by rmc-software** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by tamtakoe** [comment]
The same is on your forum: https://ag-grid.com/forum/showthread.php?tid=6350
This thread is about feature. Not about support. Don't ignore your users, please

**Comment by rmc-software** [comment]
We don't ignore our users. You can keep an eye on that post if you like and follow the guidance we provide.
