### ISSUE TITLE
ColId in SortModel - Incremented when using same field multiple times.

### ISSUE THREAD

**Issue by Keki91** [ag-grid/ag-grid#1967]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
_This is purely a repro-step - not actual functionality we use. It's affecting us in a more complex way_

`{headerName: 'Team1', field: 'TeamName'},
 {headerName: 'Team2', field: 'TeamName'}`

Sends a sort model with 
`"sortModel": [
    {
      "colId": "TeamName_1",
      "sort": "desc"
    }
  ],`

**Expected behavior**
Sort model should be the same colId (when sent to server) for sorting on both Team1 and Team2, sending an incremented number means we have to deal with the _1 on the end on the server side as we can't cleanse the data before being sent from client.

**Minimal reproduction of the problem with instructions**
Have two columns with same name when using server side sorting (or filtering).

**What is the motivation / use case for changing the behavior?**
We have the same field behind two columns off our grid - which both require sorting and filtering.

**Please tell us about your environment:**
Angular 4.4

* **ag-Grid version:** X.X.X
13.1.0

**Comment by makinggoodsoftware** [comment]
Hi, 

This is working as working as designed so we consider this a feature request.

At this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
