### ISSUE TITLE
Best way to switch column and rows of table 

### ISSUE THREAD

**Issue by KrisWyb** [ag-grid/ag-grid#1969]
I'm submitting a support request.

Usually records are rendered row by row. Sometimes if there are too many columns, but the number of records (rows) are very less, people might want to rotate the table.

 I'm wondering, whether aggrid supports swap/rotate column and rows with checkbox selected by column function?

Any hints are highly appreciated.

**Comment by AmitMY** [comment]
Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

**Comment by seanlandsman** [comment]
thanks @AmitMY 

As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by hi2u** [comment]
@AmitMY @seanlandsman 

It would be handy to just get a yes/no as to whether this feature exists or not?  As this is one of the first Google results when looking for whether this exists or not.

This would save people creating duplicate issues to ask exactly the same question, aside from writing "feature request" in the text.

Is there any community at all left for users of the open source version?  It seems the forum was closed with no replacement.  And I can't find any IRC/slack channels or anything like that.

I've tried posting questions to stackoverflow, but like most ag-grid questions on there they never get answered.  And it's not really a suitable platform for these types of "does feature x exist" questions anyway.

Also your README.md is still linking to the closed forum.

**Comment by AmitMY** [comment]
For "does this feature exist" you can either check the website or this grids comparison - https://github.com/AmitMY/grids

I haven't used ag-Grid for a while now, because I don't need any data tables, so I can't tell you by heart if something like this exists.
