### ISSUE TITLE
Unable to do custom sorting

### ISSUE THREAD

**Issue by kypradeep** [ag-grid/ag-grid#1972]
Hi, i am using ag grid for past 2 months,
i have requirement to sort data,filename and file size, i have added 3 columns with date, file name and file size, only file name is getting sorted properly, but i am unable to sort file size and date.
i also tried with comparator, but its get exceuted only once, when the grid is loaded.
How to write my own custom sort to sort file sizes, in this case?, please help me with this, as i am stuck for past 2 weeks.Here is the screen shot of my ag grid

![image](https://user-images.githubusercontent.com/32670548/31381110-2e32f8d4-add1-11e7-8ffc-9debebbf8acb.png)

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
