### ISSUE TITLE
BUG: getSelectedRows() return empty list when there are some rows selected

### ISSUE THREAD

**Issue by Vavoo** [ag-grid/ag-grid#1973]
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

**Current behavior**
call getSelectedRows() return empty list when there are some rows selected

**Expected behavior**
call getSelectedRows() return selected list when there are some rows selected

**Minimal reproduction of the problem with instructions**
go to this url:
https://www.ag-grid.com/example-runner/vanilla.php?section=javascript-grid-selection&example=header-checkbox

1. quick filter: anna
2. click select all in header button
3. quick filter : buli
4. click select all in header button
5. click select all in header button again to unselect
6. quick filter again: anna
7. run: gridOptions.api.getSelectedRows() you will get empty list but all 'anna' are still selected

**Please tell us about your environment:**
using your demo environment

* **ag-Grid version:** X.X.X
using your demo environment

* **Browser:**
chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by rellis-of-rhindleton** [comment]
This happens with getSelectedNodes as well:

api.selectAllFiltered();
(set quick filter text to filter some rows)
api.deselectAllFiltered();
(clear quick filter)

Rows that had been filtered out are still selected, but getSelectedNodes() and getSelectedRows() do not count them.

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-913 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by JohnMasterson** [comment]
Just to confirm that this was included in version 14.0.0 which is now available.

Regards, 

John

**Comment by ashwathmabiyan** [comment]
I do still observe this same issue in the community version v23.2.0

**Comment by rINAtvERESHAGIN** [comment]
any solutions ? same problem

**Comment by aaronjedwards** [comment]
I am also seeing this same issue in v 23.2.1.

**Comment by gittudemo** [comment]
Iam Facing the same issue with AG-grid, Iam not able to get the Selected Rows AG-grid , iam calling the api  
let rows = this.gridApi.getSelectedRows();
    console.log(rows)

and get Empty Array even if i have selected the rows using the checkbox.
using @ag-grid-community/angular": 28.1.0
@ag-grid-community/code" : 28.1.0

It would great help if i can sort out this issue

**Comment by LordZombi** [comment]
I also got this issue when using `headerCheckboxSelection: true` in SSRM using ag-grid@29.2.0

When I select all or deselect all using header checkbox

using `getSelectedRows` I got:
`getSelectedRows()` => `[]`
`getSelectedRows()` => `[]`

using `getServerSideSelectionState` I got:
`getServerSideSelectionState {selectAll: true, toggledNodes: Array(0)}`
`getServerSideSelectionState {selectAll: false, toggledNodes: Array(0)}`

which is better but why is toggledNodes empty when selectAll is true ? What I expect in `toggledNodes` is all nodes currently loaded and selected.

**Comment by LordZombi** [comment]
> Hi @LordZombi,
> 
> As documented here: https://ag-grid.com/javascript-data-grid/server-side-model-selection/#selection-api
> 
> `getSelectedRows` and `getSelectedNodes` are not advised when using the SSRM with `headerCheckboxSelection` or `groupSelectsChildren`. This is because the grid cannot accurately reflect which rows/nodes are selected by returning a flat list in these scenarios due to a lack of information. Instead we return this model including a `selectAll` status and a list of `toggledNodes`, this list consists of row ids which do not conform to the `selectAll` status.
> 
> The purpose of this is to enable you to share this state with your server, which can reconstruct the true list of selected rows, and apply bulk actions to that.
> 
> If your use case is simpler than this, you can work around this by simply iterating over every node loaded in the grid using `api.forEachNode` and checking its selection state.

Yep, did it that way, using `api.forEachNode`.
I was just wondering, from UX perspective if you select all in header you should have selected only all you can see, but your point also make sense but more from developer perspective :)

**Comment by aniov** [comment]
I'm looking for a solution for select All ( `getSelectedRows() => []` ) since we are using also pagination.
We just switch from 24.0.1 to 29.3.3 version and in the older version the getSelectedRows() an select all, returned the selected rows on current page. 

The way we used it was to navigate on different pages and select all or just some rows on that page - keeping the data from the selections in front end store and then using it to perform some actions.

But now on select all, all rows are selected when u navigate between pages.

Thanks in advance.

**Comment by fitsumd** [comment]
> I'm looking for a solution for select All ( `getSelectedRows() => []` or getServerSideSelectionState()} ) since we are using also pagination. We just switch from 24.0.1 to 29.3.3 version and in the older version the getSelectedRows() an select all, returned the selected rows on current page.
> 
> The way we used it was to navigate on different pages and select all or just some rows on that page - keeping the data from the selections in front end store and then using it to perform some actions.
> 
> But now on select all, all rows are selected when u navigate between pages.
> 
> Thanks in advance.

Hi Aniov, 
Did you get any help for your request? Currently i am in the same situation like you. Could you please share me some idea if you solve it on some way.

Thanks!

**Comment by aniov** [comment]
> Hi Aniov, Did you get any help for your request? Currently i am in the same situation like you. Could you please share me some idea if you solve it on some way.
> 
> Thanks!

> 

We had no choice but to create a custom headerComponent where we handle the logic for select / deselect all , check for indeterminate state, check for page change. (we used checkbox component from antd.)

 - created listeners for selection and pagination
```
useEffect(() => {
    if (headerCheckboxSelection) {
      api.addEventListener('selectionChanged', setCheckboxState);
      api.addEventListener('paginationChanged', setCheckboxState);

      return () => {
        api.removeEventListener('selectionChanged', setCheckboxState);
        api.removeEventListener('paginationChanged', setCheckboxState);
      };
    }
  }, [api, headerCheckboxSelection, setCheckboxState]);
```

- using our component state to handled those events

```
  const setCheckboxState = useCallback(() => {
    const selectedNodes = api?.getSelectedNodes();
    const renderedNodes = api?.getRenderedNodes();
    let currentRenderedSelectedNodeSize = 0;
    renderedNodes.forEach((renderedNode) => {
      const currentRenderedSelectedNodeFound = selectedNodes.find((selectedNode) => selectedNode.id === renderedNode.id);
      if (currentRenderedSelectedNodeFound) {
        currentRenderedSelectedNodeSize += 1;
      }
    });
    const allChecked = currentRenderedSelectedNodeSize > 0 && currentRenderedSelectedNodeSize === renderedNodes.length;
    const isNewSelectionIndeterminate = currentRenderedSelectedNodeSize > 0 && !allChecked;
    setIsChecked(allChecked);
    setIsIndeterminate(isNewSelectionIndeterminate);
  }, [api]);
```
- handle click on select all checkbox - using antd component

```
  const handleSelectAll = (e: CheckboxChangeEvent) => {
    const selectedState = e.target.checked;
    const renderedNodes = api.getRenderedNodes();

    let nodeSelected = 0;
    api.forEachNode((node) => {
      if (renderedNodes.find((renderedNode) => renderedNode.id === node.id)) {
        node.setSelected(selectedState);
        if (selectedState) {
          nodeSelected += 1;
        }
      }
    });

    if (nodeSelected === renderedNodes.length) {
      setIsChecked(true);
    } else if (nodeSelected > 0) {
      setIsIndeterminate(true);
    } else {
      setIsChecked(false);
    }
  };
```

II'm sure this the code can be improved, but I hope it's a start for you at least.

**Comment by Manasgupta840** [comment]
This works for me
````
const handleRowSelectionChange = useCallback(
    (params: any) => {
      if (params.source === "api") {
        return; // for avoiding repeated call
      }
      const { selectAll, toggledNodes } =
        (gridRef?.current?.api?.getServerSideSelectionState() as IServerSideSelectionState) ||
        {};

      const selectedNodes = gridRef?.current?.api?.getSelectedNodes();
      const nodesIds = selectedNodes?.map((node) => node.id ?? "");

      // for handling header checkbox action
      if (selectAll && !toggledNodes.length) {
        setSelectedRows(rows);
        const nodesToSelect: IRowNode<any>[] = [];
        gridRef?.current?.api.forEachNode((node) => {
          nodesToSelect.push(node);
        });
        gridRef?.current?.api.setNodesSelected({
          nodes: nodesToSelect,
          newValue: true,
        });
        gridRef?.current?.api?.setServerSideSelectionState({
          selectAll: true,
          toggledNodes: [],
        });
      } else {
        // for handling row checkbox action
        const selectedRows: AssignmentRow[] = [];
        selectedNodes?.forEach((node) => {
          selectedRows.push(node?.data);
        });
        setSelectedRows(selectedRows);
        if (selectedNodes?.length === rows.length) {
          gridRef?.current?.api?.setServerSideSelectionState({
            selectAll: true,
            toggledNodes: [],
          });
        } else {
          gridRef?.current?.api?.setServerSideSelectionState({
            selectAll: false,
            toggledNodes: nodesIds ?? [],
          });
        }
      }
    },
    [rows],
  );
````
