### ISSUE TITLE
[Improvement]: Merge column cells for full-width row group in Excel export

### ISSUE THREAD

**Issue by R4DIC4L** [ag-grid/ag-grid#1974]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When exporting a grid to excel with a full-width row, the text appears on the first cell of the grouping row.
_Grid layout_
![grid](https://user-images.githubusercontent.com/7274664/31428534-b88f0caa-ae73-11e7-9495-35ac5d4da1db.jpg)

_Excel export layout_
![export](https://user-images.githubusercontent.com/7274664/31428535-b8af3a34-ae73-11e7-9645-3bbf7b86e30d.PNG)

**Expected behavior**
The Excel data column cells could be merged so that the text in the full-width row group would appear in a line, like in the original grid.
_Proposed Excel export layout_
![export_desired](https://user-images.githubusercontent.com/7274664/31428532-b86cc99c-ae73-11e7-9f35-20da45bd6a35.png)

**What is the motivation / use case for changing the behavior?**
The exported data would look better and be similar to the way it appears in the grid. Also, it would fit a longer text in the full-width row group that wouldn't fit the first cell's width.

* **ag-Grid version:** 13.1.2

* **Browser:** any

* **Language:** all

**Comment by petyosi** [comment]
Thank you for the suggestion. I am logging it for a review from our dev team, the internal reference id is AG-972.

**Comment by makinggoodsoftware** [comment]
Hi,

Please feel free to track the item in the pipeline:

https://www.ag-grid.com/ag-grid-pipeline/
