### ISSUE TITLE
how disable edit  on pinned row ?

### ISSUE THREAD

**Issue by Leo-lay** [ag-grid/ag-grid#1975]
**I'm having  a doubt, how disable edit  on pinned row ?**  

In my case ,i want normal rows can editable and have a delete button , how disable edit and hide the delete button  on pinned row ? 

 **Here is the code for the cell**

```
getColumnCell(filed, name, isEdit = false) {
    return {
      editable: true,
      suppressResize: true,
      headerName: name,
      field: filed,
      width: 120,
      cellClass: 'ag-edit-border',
      cellRendererFramework: NumericRenderComponent,
      cellEditorFramework: NumericEditComponent,
      pinnedRowCellRendererFramework: CurrencyCellComponent,
      filter: 'number',
      type: 'numericColumn',
    };
  }
```
** And 
```
getDeleteCell(field = '', name) {
    return {
      headerName: name,
      field: field,
      width: 50,
      cellRendererFramework: DeleteCellComponent,
      pinnedRowCellRendererFramework: null,
      suppressResize: true,
      headerClass: 'text-center',
      cellClass: 'text-center',
      onCellClicked: (params) => {
        console.log(params);
        this.onDeleteClick(params);
      },
    };
  }
```
I read the documention but not fount a solutions, so can any one can help me ?

Thanks.

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by ksatish422** [comment]
do we have any solution for this? Me too facing the same issue. In my case, all the cells the number boxes and in pinnedrow I want to show the total which should not be editable.  can anyone please help?

**Comment by pbansode** [comment]
added a hack via CSS - "pointer-events": "none"

sample react code 

class sample extends Component {

  constructor(props) {
    super(props);

    this.state = {     
      defaultColDef: {
        initialWidth: 150,
        sortable: true,
        resizable: true,
        filter: true,
      },
      **getRowStyle: function (params) {
        if (params.node.rowPinned) {
          return { "font-weight": "bold","pointer-events": "none"};
        }
      },**
    };
  }

         <AgGridReact
            defaultColDef={this.state.defaultColDef}
            columnDefs={this.context.projectColumns}
            rowData={this.context.projectRows}
            onGridReady={this.onGridReady}
            onCellValueChanged={this.onCellValueChanged}
            **getRowStyle={this.state.getRowStyle}**
            pinnedBottomRowData={[this.addRowTotal(this.context.projectRows)]}          
          />

**Comment by steveschmitt** [comment]
The `editable` flag can be a boolean, or a _callback_ that returns a boolean.  So you can do something like: 
```js
this.defaultColDef.editable = (o) => !o.node.isRowPinned();
```
