### ISSUE TITLE
Allow to show group column header only

### ISSUE THREAD

**Issue by tamtakoe** [ag-grid/ag-grid#1978]
**I'm submitting a**
```
[X] feature request
```

Allow to hide headers of children columns and show only group header. Or allow to span column headers

**What is the motivation / use case for changing the behavior?**

1. When column contains data that is too small for separate header
<table>
  <tr>
    <th colspan="2">Place</th>
  </tr>
  <tr>
    <td><img src="https://www.ag-grid.com/images/flags/ie.png" width="15" height="10"></td>
    <td>Dublin</td>
  </tr>
  <tr>
    <td><img src="https://www.ag-grid.com/images/flags/es.png" width="15" height="10"></td>
    <td>Madrid</td>
  </tr>
  <tr>
    <td><img src="https://www.ag-grid.com/images/flags/de.png" width="15" height="10"></td>
    <td>Berlin</td>
  </tr>
</table>

<table>
  <tr>
    <th colspan="2">Person</th>
  </tr>
  <tr>
    <td>🛊</td>
    <td>Sara</td>
  </tr>
  <tr>
    <td>🛉</td>
    <td>Alex</td>
  </tr>
</table>

2. When column contains well-known group of values (dimensions, coordinates etc.) 
<table>
  <tr>
    <th colspan="3">Dimensions, L×W×H</th>
  </tr>
  <tr>
    <td>120</td>
    <td>60</td>
    <td>15</td>
  </tr>
  <tr>
    <td>400</td>
    <td>60</td>
    <td>25</td>
  </tr>
  <tr>
    <td>1000</td>
    <td>140</td>
    <td>70</td>
  </tr>
</table>

3. When column contains data that dosn't need separate header
<table>
  <tr>
    <th colspan="3">Medals</th>
  </tr>
  <tr>
    <td>🥇</td>
    <td>🥈🥈</td>
    <td>🥉🥉🥉🥉🥉</td>
  </tr>
  <tr>
    <td></td>
    <td>🥈</td>
    <td>🥉🥉</td>
  </tr>
  <tr>
    <td>🥇🥇</td>
    <td>🥈🥈🥈</td>
    <td></td>
  </tr>
</table>

* **ag-Grid version:** 13.3.1

**Comment by petyosi** [comment]
Thank you for the suggestion - I am logging this for a review ( AG-971 ).

**Comment by makinggoodsoftware** [comment]
Actually this is possible already...

Set these in your gridOptions.

groupHeaderHeight:x,
headerHeight: 0,

**Comment by tamtakoe** [comment]
@makinggoodsoftware your way is a little bit in indian style. It will work just for my local example, but not for whole table

<table>
  <tr>
    <th>Name</th>
    <th colspan="3">Medals</th>
  </tr>
  <tr>
    <td>Sara</td>
    <td>🥇</td>
    <td>🥈🥈</td>
    <td>🥉🥉🥉🥉🥉</td>
  </tr>
  <tr>
    <td>Alex</td>
    <td></td>
    <td>🥈</td>
    <td>🥉🥉</td>
  </tr>
  <tr>
    <td>Jigurda</td>
    <td>🥇🥇</td>
    <td>🥈🥈🥈</td>
    <td></td>
  </tr>
</table>

**Comment by lucatrioschi** [comment]
Sorry for posting on a more-than-a-year-ago closed discussion but....are there any news about this feature?
I would be very interested in it too...
@tamtakoe have you solved it in some way?

**Comment by ilius33** [comment]
Well to continue the 'hack' you can put each of your column in a group and give it a title of a group.

**Comment by lucatrioschi** [comment]
That's what I am currently doing (and hiding "group header" via css) but I think a standard built-in solution would be preferable.
