### ISSUE TITLE
Date filter uses HTML5 date input in Chrome, but not other browsers that support it

### ISSUE THREAD

**Issue by theodorejb** [ag-grid/ag-grid#1980]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Current behavior**
Date filter uses `<input type="date"/>` in Chrome, but not other browsers that support it.

**Expected behavior**
It should be possible to use date filters with the native date picker in all browsers that support it.

**Minimal reproduction of the problem with instructions**
1. Create a grid with date column and filter (add `filter: 'date'` to the column def.)
2. Open grid in Chrome and see that the date filter field has a calendar dropdown as expected
3. Open grid in Firefox 57+, see that clicking the date filter field unexpectedly doesn't open the native date picker.

I dug into the ag-Grid code, and it looks like this line causes the problem: https://github.com/ag-grid/ag-grid/blob/64700ac17c770e8ad43f01169843e474d6e5304c/src/ts/filter/dateFilter.ts#L189

**What is the motivation / use case for changing the behavior?**
ag-Grid should work as expected in other modern browsers besides Google's.

**Please tell us about your environment:**

* **ag-Grid version:** 8.2.0
Still seems to be an issue in the latest release, too.

* **Browser:**
"Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

* **Language:** TypeScript 2.3

**Comment by petyosi** [comment]
Thank you for the report, I raised AG-959 to track the progress of it.

**Comment by tiberiuzuld** [comment]
Hi @petyosi ,
What is the status of this issue?

I couldn't find AG-959 in the [Pipeline](https://www.ag-grid.com/ag-grid-pipeline/).
Browsers: Chrome, Firefox, Edge support input type date. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

Per spec if the browser is not supporting it will be treated as an input type text.

Thanks,

**Comment by tiberiuzuld** [comment]
Found a workaround:
```javascript
params.api
            .getFilterInstance('time')
            .eGui
            .querySelectorAll('input')
            .forEach(function (input) {
              input.type = 'date';
            });
}
```

**Comment by makinggoodsoftware** [comment]
Hi,

You should be able to track this from our pipeline too..

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by tiberiuzuld** [comment]
Hi @makinggoodsoftware ,
Yes now appears in the new UI pipeline.

Thanks

**Comment by yesimbrandon** [comment]
Hi @tiberiuzuld ,

I was trying to implement your suggested workaround but was seeing an issue. I'm fairly new to some of this so hopefully I explain it correctly. We are using react and in the tsx file for this part of the page I added your onGridReady function and am doing onGridReady={this.onGridReady} in the AgGrid in the render function.

In the page though, when I inspect the field it is still a text box. Would I do this any differently in react? I set a break point and I know it's at least calling the onGridReady function.

Thanks!

**Comment by tiberiuzuld** [comment]
Sorry for the late answer but some how I missed this notification.
Kinda happens sometimes since they changed the dashboard of notifications on https://github.com/

Wanted to check on the progress on the ticket. :)

I have no idea how ag-grid functions in react.

But make sure this part works:
```javascript
 params
            .api
            .getFilterInstance('time')
            .eGui
```
If you get the filter and the dom.

**Comment by AansariZaid** [comment]
Hi Team,

If you will open following link in Edge Browser (or known as Internet Explorer) Date Filter is not showing the calendar. because input type date is not supported by IE.

https://www.ag-grid.com/javascript-grid-filtering/#example-built-in-filters

I tried to implement above mentioned things but none of them is Working.

i am Using ag-grid-angular Version 13.3.0 with Enterprise License .

AG-959 Issue in Pipeline can be seen as Paused ,

*Can anyone Provide a Work Around to Use date floating filter in IE. ??*

**Comment by tiberiuzuld** [comment]
In Edge Browser input type date is supported:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

In the demo is not present because they made hardcoded to set input type="date" only in Chrome.
This issue is about removing that restriction.

My workaround is only to force the input type="date" in all browsers.

**Comment by AansariZaid** [comment]
HI @tiberiuzuld 

Thanks for your fast response on this but many Older browser doesn't supports input type = "date",

is there any other work around apart from creating custom Floating Filter.?

Any suggestions will be much appreciated.

**Comment by tiberiuzuld** [comment]
The only workaround for old browser which don't support input="date" is to implement a custom filter with a library date picker or do it yourself.
This page developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
has some examples on how to implement for browser which don't support it.
Some examples of libraries:
* js: https://github.com/qodesmith/datepicker
* Angular: https://www.npmjs.com/package/ng2-datepicker

**Comment by Supreetha-M-A** [comment]
Hi, Is this issue still faced when u use the enterprise version of ag-grid?

**Comment by tiberiuzuld** [comment]
In 17.1.0 there is option that will always use the browser date picker:
```js
 filterParams: {
   browserDatePicker: true
 }
```

**Comment by Shelly-Thakur1** [comment]
Hi,

The above fix works for Firefox and Edge, but does not work for Safari or Internet Explorer. Can someone help in that?

**Comment by ggmol** [comment]
> In 17.1.0 there is option that will always use the browser date picker:
> 
> ```js
>  filterParams: {
>    browserDatePicker: true
>  }
> ```



> In 17.1.0 there is option that will always use the browser date picker:
> 
> ```js
>  filterParams: {
>    browserDatePicker: true
>  }
> ```

Thanks man. It works!

**Comment by ggmol** [comment]
> In 17.1.0 there is option that will always use the browser date picker:
> 
> ```js
>  filterParams: {
>    browserDatePicker: true
>  }
> ```

Thanks man. It works!
