### ISSUE TITLE
Set hardcoded min_col_width to 4px

### ISSUE THREAD

**Issue by ChristianKohler** [ag-grid/ag-grid#1984]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Min col width is hardcoded to 10px. We would like to have a column with just 4px width with a background color based on a state.

**Expected behavior**
Do not force a min column width or set the column width to less then 10px. I guess the 10px are set to avoid any issues when a user sets the min col width to 1px or so. What would happen if we set the min width to 4px or make it possible to override it via options? I a user manually overwrites the min width, he should be aware of the side affects.

https://github.com/ag-grid/ag-grid/blob/master/src/ts/gridOptionsWrapper.ts

`private static MIN_COL_WIDTH = 10;`

```
public getColWidth() {
    if (typeof this.gridOptions.colWidth !== 'number' || this.gridOptions.colWidth < GridOptionsWrapper.MIN_COL_WIDTH) {
        return 200;
    } else {
        return this.gridOptions.colWidth;
    }
}
```

**Comment by petyosi** [comment]
Thank you, 

I logged the above for review from our dev team; the number of the task is AG-970.

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that we are not going to go ahead with this feature request.

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
