### ISSUE TITLE
checkbox is unchecked after scrolling fast with infinite scrolling

### ISSUE THREAD

**Issue by theFlyingCat04** [ag-grid/ag-grid#1986]
**I'm submitting a ...**  (check one with "x")
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

**Current behavior**

Having a column with checkboxes and rowModelType="infinite". Select at least one of the first rows. Scroll down until the selected rows are no longer in the cache. Grabbing the scrollbar and pulling it fast to the top: the rows are still selected (rows are highlighted) but the checkboxes are unchecked. (If you'd scroll up slowly with the mouse wheel, then the checkboxes are checked...)

**Expected behavior**

After scrolling up and down the checkboxes should still be checked.

**Minimal reproduction of the problem with instructions**

*Minimal Demo*
https://www.ag-grid.com/javascript-grid-infinite-scrolling/?framework=angular#example-made-up-data
*Steps to reproduce*
see Current behavior

**What is the motivation / use case for changing the behavior?**

Reviewing/checking before manipulating/deleting data

**Please tell us about your environment:**

Linux Mint 18.1, 64 bit,
angular-cli 1.0.1

* **ag-Grid version:** 9.1.0 (and whatever is used on Your docs page)

* **Browser:**

Chromium: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.79 Chrome/61.0.3163.79 Safari/537.36"
Firefox: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"

* **Language:** TypeScript 2.2 (and what is used on Your page)

**Comment by petyosi** [comment]
Thank you for the report, managed to reproduce the problem. I am logging AG-955 in the internal bug tracker. Our dev team will review it.

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by theFlyingCat04** [comment]
Thanks!

**Comment by JohnMasterson** [comment]
Just to confirm this was include in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
