### ISSUE TITLE
getNodeChildDetails doesnt support Checkbox CellRenderer

### ISSUE THREAD

**Issue by rchait** [ag-grid/ag-grid#1987]
**I'm submitting a bug/Feature request
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When we use getNodeChildDetails , cellrenderer - checkbox functionality is not working.
If we use groups and checkbox selection as in this link - 
https://www.ag-grid.com/javascript-grid-selection/#groupSelection&gsc.tab=0, 
group editing cannot be done.

**Expected behavior**

Group editing must be done on parent using groups
or 
getNodeChildDetails must be provided with checkbox
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Group editing and Checkbox together is required
**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

13.1.0

* **Browser:**

All browsers
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.1

**Comment by petyosi** [comment]
Hi, 

thanks for contacting us. Our next major iteration over tree data mode will support what you describe. Notice: the feature will be available in the enterprise version of the grid.
