### ISSUE TITLE
Issue removing event listeners

### ISSUE THREAD

**Issue by joeylgutierrez** [ag-grid/ag-grid#1988]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Event listeners can't be removed because it pulls from the synchronous list and we can't modify the async variable.
```
EventService.prototype.removeEventListener = function (eventType, listener, async) { if (async === void 0) { async = false; } var listenerList = this.getListenerList(eventType, async); utils_1.Utils.removeFromArray(listenerList, listener); };
that is called by
GridApi.prototype.removeEventListener = function (eventType, listener) { this.eventService.removeEventListener(eventType, listener); };
```
if i run it through the console with async === true, my listener is returned to the listenerList and everything would work.

**Expected behavior**

I expect to call api.removeEventListener(eventType, myFunction) and the eventListener should be removed.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I use typescript and basically have a class that calls grid.api.removeEventlistener('gridSizeChanged', afterPrint) to resize the screen so that printing looks nice.  I can't remove the listener.

**Please tell us about your environment:**

Mac 10.12.6, Yarn 1.0, Nginx

* **ag-Grid version:** X.X.X
13.3.1

I pulled the latest and reported this an issue back in version 10.1 and it's still an issue
https://github.com/ag-grid/ag-grid/issues/1502

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.5.2

**Comment by joeylgutierrez** [comment]
I believe this may be a duplicate of https://github.com/ag-grid/ag-grid/issues/1956

**Comment by petyosi** [comment]
Correct, closing this one - you can track #1956.
