### ISSUE TITLE
Ability for last column to take up 'rest' of grid width

### ISSUE THREAD

**Issue by ventralnet** [ag-grid/ag-grid#1991]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
**What is the motivation / use case for changing the behavior?**

The autoSizeColumns resize strategy works great however if you have few short columns you will be left with an awkward amount of unused space if there is left over grid width.  I wanted to propose a hybrid of the autoSizeColumns strategy and the sizeToFit strategy where autoSizeColumns works per usual, but makes last table column take up the 'rest' of the grid width

**Comment by petyosi** [comment]
Hey, 

you can use `suppressSizeToFit` to select which of the columns are going to be adjusted - won't this work for you?

**Comment by ventralnet** [comment]
@petyosi not sure, give me a little bit to setup a jsfiddle to see if it will do what I am proposing. Thanks!
