### ISSUE TITLE
How To Change color Of Sorting Arrow / Menu Hamburger Button

### ISSUE THREAD

**Issue by JimTheMan** [ag-grid/ag-grid#1992]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

By default the sorting arrow and hamburger menu icon button in the column headers are black. I can change the text color and background color of the header cells by overriding "ag-header-cell" css class. However, it seems there is no way to change the icons. 

**Expected behavior**

I cons should be able to have color changed. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

13.2.0

* **Browser:**

google chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by petyosi** [comment]
What you describe is possible. As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

**Comment by JimTheMan** [comment]
@petyosi thanks ass hole...

**Comment by nsankaranarayanan** [comment]
@petyosi I followed your documentation and provided a custom path with SVG icons and it still doesn't seem to work.  Basically the icons are still black.
https://www.ag-grid.com/javascript-grid-icons/

![image](https://user-images.githubusercontent.com/5003582/39087374-0820d08c-4555-11e8-9b91-e62303a20a41.png)

**Comment by sherodtaylor** [comment]
any thing on this ^
