### ISSUE TITLE
Mobile - Checkboxes in Column Menu - (columnsMenuTab) not working

### ISSUE THREAD

**Issue by srikanthmooli** [ag-grid/ag-grid#1993]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1.) On mobile devices Column Menu is selected
2.) when the column selection checkboxes are checked/unchecked, the grid doesn't refresh based on the selection made.

**Expected behavior**
1.) On mobile devices Column Menu is selected
2.) when the column selection checkboxes are checked/unchecked, the grid should refresh based on the columns selected/unselected.

**Minimal reproduction of the problem with instructions**
Steps to reproduce : 
(Screenshot attached)
1.) On mobile devices Column Menu is selected
2.) when the column selection checkboxes are checked/unchecked, the grid doesn't refresh based on the selection made.
3.) The grid in the below link has the explained issue.
https://www.ag-grid.com/javascript-grid-column-menu/#gsc.tab=0

**What is the motivation / use case for changing the behavior?**
Unable to modify the grid column list in Mobile devices

**Please tell us about your environment:**
Windows 7/10, Chrome, Visual Studio Code, NPM

* **ag-Grid version:** X.X.X
13.1.1

* **Browser:**
Mobile devices

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.5.3

![image](https://user-images.githubusercontent.com/32304087/31779489-d7287ba6-b4b8-11e7-94ff-407d471e332b.png)

**Comment by petyosi** [comment]
Hi, 

Thank you for the report. I have raised AG-958 for the item, our dev team will review it.

**Comment by makinggoodsoftware** [comment]
Hi,

Please feel free to check the progress of our item in our pipeline page:

https://www.ag-grid.com/ag-grid-pipeline/

Thanks

**Comment by JohnMasterson** [comment]
AG-958 was included in Version 16.

Regards, 

John
