### ISSUE TITLE
Ag-Grid Angular 4 + Bootstrap 4 Beta filter column

### ISSUE THREAD

**Issue by WebstaGit** [ag-grid/ag-grid#1999]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I updated my Angular 4 app to Bootstrap 4 beta I get 2 errors on clicking the filter-icon in a column header AG-Grid:

1.
`Error: Text element: <input class="ag-filter-filter" id="filterText" placeholder="Filter eingeben" type="text"> requires class: form-control`

2.
`Error: Select element: <select class="ag-filter-select" id="filterType"> requires class: form-control||custom-select`

ag-grid version: 13.3.1
ag-grid-angular version: 13.3.0

Tested in IE 11, Firefox & Chrome.

Is there a way to modify the filter menu to add these classes or has anyone another solution?

**Comment by seanlandsman** [comment]
Hi

This isn't a grid issue I'm afraid - I'd suggest trying stackoverflow or similar for this issue

thanks
