### ISSUE TITLE
add condition to GridApi.forEachNode

### ISSUE THREAD

**Issue by lilling** [ag-grid/ag-grid#2000]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request
```

**Current behavior**
`forEachNode(callback: (rowNode: RowNode) => void): void;`

**Expected behavior**
`forEachNode(callback: (rowNode: RowNode) => void, condition: boolean): void;`

**What is the motivation / use case for changing the behavior?**
in case of large amount of rows I would like it to stop If reached the desired node.

**Please tell us about your environment:**
win 10, vscode, npm

* **ag-Grid version:** 10.1.0

* **Language:** all

**Comment by petyosi** [comment]
Hey,

from what I gather, you are actually looking for a specific node - it this so? Because in that case, `findNode` API might be more appropriate. Let me know what you think.

**Comment by lilling** [comment]
where is this api? I didnt find it in the docs.

**Comment by petyosi** [comment]
Sorry for the confusion; such API method does not exist currently. I am proposing it as a potential enhancement we may look into, if it makes sense to you.

**Comment by lilling** [comment]
It will take to consideration that it might have multiple nodes answering the condition?

**Comment by petyosi** [comment]
In the multiple nodes case, how would you 
> I would like it to stop If reached the desired node.
?

**Comment by lilling** [comment]
yeah you're right scratch last comment. is there a PR on this or is this just on paper?

**Comment by petyosi** [comment]
There is no PR. I will log it as a backlog item in the internal tracker (AG-983).

**Comment by makinggoodsoftware** [comment]
Hi,

Please feel free to track this issue from our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/
