### ISSUE TITLE
ag-grid not rendering text in cells

### ISSUE THREAD

**Issue by bipinmangwani1** [ag-grid/ag-grid#2001]
![1](https://user-images.githubusercontent.com/33063395/31950244-16c91dce-b8d3-11e7-9aa3-cfb80dd7ebef.jpg)

![1](https://user-images.githubusercontent.com/33063395/31950224-0dc2acb8-b8d3-11e7-8296-7a26227b4895.jpg)

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I was using theme-fresh where everything was working fine. I recently changed to ag-theme-material in ag-grid/ag-grid-enterprise 13.3.1. I've set up the project to use ag-grid.scss and ag-theme-material.scss. After switching to material theme, the ag-grid tables are unable to render any text in the table cells. The cells instead just show some dots or underscores (basically some indescribable rubbish at subscript location of the line) indicating as if it tried to use very small font size.

**Expected behavior**
The table cells should have rendered the data as text in the view.

**Minimal reproduction of the problem with instructions**
I can't reproduce this in plnkr but some of my code is in styles.scss here
https://plnkr.co/edit/MEOFk1oCsb0gXfcwzzyu?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
angular 4.3.0, bootstrap 4.0.0-alpha.6, ag-grid/ag-grid-enterprise 13.3.1, ag-grid-angular 13.3.0

* **ag-Grid version:** 13.3.1

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36

* **Language:** TypeScript 2.5.2

**Comment by petyosi** [comment]
This does not seem like a known issue. We will need a reproduction of it in order to help you further.

**Comment by bipinmangwani1** [comment]
I can't reproduce it out of my project. If it helps - when I set $ag-mat-row-height to 20px the data renders correctly.

**Comment by dennispg** [comment]
I am seeing the same problem, I added this to resolve the issue:
```scss
.ag-material {
    .ag-cell-not-inline-editing {
        padding-top: 2px;
    }
}
```

Also, all the examples online say to use class="ag-material-theme".

**Comment by dennispg** [comment]
Actually, it looks like I was referencing the wrong theme file!

I changed from 
```scss
@import "~ag-grid/src/styles/theme-material";
```
to
```scss
@import "~ag-grid/src/styles/ag-theme-material";
```

And all is well now. I just had to make sure to use class="ag-material ag-theme-material"

**Comment by petyosi** [comment]
Hi @dennispg - I searched for `ag-material-theme` in our docs repository, could not find any place where we refer to it like this - can you point me to the wrong example so that I can fix it? Thank you.

Apart from that, you should use only `class="ag-theme-material"`.

**Comment by dennispg** [comment]
Am I referencing the correct scss file now, `ag-theme-material.scss`? That seems to be what fixed most of it, but some strange things still persist.

This is what I have in my scss:
```scss
$ag-mat-grid-size: 4px;
@import "~ag-grid/src/styles/ag-grid";
@import "~ag-grid/src/styles/ag-theme-material";
```
Including that `$ag-mat-grid-size` variable causes the `.ag-theme-material .ag-cell` line-height to be 22px. Without the variable set, the line-height is set to 46px.

What's more interesting than all of that though, is when I include  `class="ag-material ag-theme-material"` the `.ag-row` rows are set with a direct style attribute with height set to 25px, where as without it is set to 48px.

I'm guessing I am doing it wrong, but the combination of the variable `$ag-mat-grid-size: 4px;` and  `class="ag-material ag-theme-material"` produces the look I actually want. Omitting the variable and the .ag-material class I've discovered also makes it work (probably as designed), but with the taller 48px rows that I don't prefer. I don't know if I am just missing something..


https://www.ag-grid.com/javascript-grid-themes/material-theme.php?framework=aurelia#gsc.tab=0
^ I've discovered from that page that `.ag-material` is the legacy theme, and `.ag-theme-material` is the new one. So it makes more sense now why I see reference to both in various places.

Here is an example form the docs which still say to use `class="ag-material"`
https://github.com/ag-grid/ag-grid-docs/blob/master/src/example-angular-third-party/material-design/md-editor-two.component.html

**Comment by petyosi** [comment]
Hey,

can you check this sample repo: https://github.com/ag-grid/ag-grid-material/tree/master/custom-sizing - if I understand you correctly, it should address your query.

**Comment by dennispg** [comment]
Thanks for the sample. It looks like the rowHeight and headerHeight options were the key:

```javascript
gridOptions = { rowHeight: 24, headerHeight: 28 }
```

Now i can use simply `class="ag-theme-material' along with those options and it looks as I wanted.

I see now that this was actually in the same documentation I had been staring at all along. I think maybe the legacy samples I was running across threw me off. Anyways, I apologize for missing that, and thanks for working with me through it.


If you dont mind the suggestion, maybe this sentence on the docs page:

> However, In case you wish to change the sizing, you should do that both in the grid configuration and by overriding the `$ag-mat-grid-size` and `$ag-mat-icon-size`.

could be clarified with something like this:

> However, In case you wish to change the sizing, you should do that both by setting the `rowHeight` and `headerHeight` options in the grid configuration and by overriding the `$ag-mat-grid-size` and `$ag-mat-icon-size`.


Thanks again!

**Comment by petyosi** [comment]
Thank you! We are actually looking into simplifying this, so that the dimensions can be controlled only by setting the sass variables. Setting both is quite counter-intuitive.

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked by AG-1177, please follow this up from our pipeline.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks
