### ISSUE TITLE
Filter State is not working in Ag-Grid

### ISSUE THREAD

**Issue by srikant21** [ag-grid/ag-grid#2003]
**Current behavior**
Filter state is not restoring from local storage at the time of page load.

**Expected behavior**
Want to save state of column filter setting in local storage and retain the setting after refresh.
It is working fine for sorting column but not working for Filter

**Please tell us about your environment:**
Window 7/10,Visual Studio Code

* **ag-Grid version:** 13.3.x

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript-2.3.3

Plunker:-
https://plnkr.co/edit/xVqFFU3a0WKc3e3rEqtO?p=preview

**Comment by srikant21** [comment]
Please find the plunker for my AG-Grid Issue
https://plnkr.co/edit/xVqFFU3a0WKc3e3rEqtO?p=preview

**Comment by petyosi** [comment]
It looks like you are re-applying the filter storage before the data is set. You should try restoring it once the data is there; you can use the dataChanged event for that purpose.

**Comment by srikant21** [comment]
I am not able to find any dataChanged event in ag-grid.
Can u help me on this by implementing the event in my plunkr code?

**Comment by srikant21** [comment]
Hi Petyosi,
Thanks a lot. I found the event and implemented it. It is working fine.
