### ISSUE TITLE
no public access to the RenderedCell instance

### ISSUE THREAD

**Issue by pete-hotchkiss** [ag-grid/ag-grid#2006]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
No public access to RenderedCell 

**Expected behavior**
Access to the RenderedCell object for a given cell would be useful - for example to invoke the context menu through interactions other than a right-mouse click

**What is the motivation / use case for changing the behavior?**
Not hacking around private properties to get to the object

As part of some work to extend the capabilities of a custom cell renderer, we've got a scenario where we want an HTML element - in this case a button - to trigger a context menu. 

To be able to invoke the display of this we needed access to the RenderedCell instance for the cell in which the button click is happening. 

After some digging around this can be found in..

```
rowRenderer.renderedRows[rowIndex].renderedCells[colId]
````
now; many of these props are private - so typescript will rightly have a good moan if we try and get at them. To get round this we've used lodash, so have a method on our cell renderer
```
public get renderedCell(): RenderedCell {
    return _.get(this.api, `rowRenderer.renderedRows[${this.rowIndex}].renderedCells[${this.colId}]`) as RenderedCell;
}
```
whilst this works - it's a hack and i'm concerned it's brittle and likely to become unstable in future releases.

So, if there an alternative way to get at this - and if not, could we request something more stable and public be added to the API to provide this. Perhaps even a property on the params object passed to a cell renderers init() callback ?

* **ag-Grid version:** X.X.X

* **Language:** [all]

**Comment by rmc-software** [comment]
Hi,

This is not how we expect users to interact with the cellRenderer, i.e. to invoke the context menu.

It might be valid to add an API call to invoke the context menu for any cell but we are not convinced of the utility of this.

Thanks anyway and we'll consider in the future but at this point it would be disingenuous to raise a jira for a feature we're not likely to implement.
