### ISSUE TITLE
Wrong input cursor behaviour Internet Explorer

### ISSUE THREAD

**Issue by therealtomas** [ag-grid/ag-grid#2007]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When pressing a key in an input cell it focuses at place 0, either it should be on place 1 or replace value in cell. This only occurs in Internet Explorer. in Chrome it replaces the cell value.

When pressing a key in a cell in Internet Explorer the cursor is wrong.

**Expected behavior**
value should have correct cursor focus or replace value.

**Minimal reproduction of the problem with instructions**
When pressing at "1" two times in Internet Explorer (Invalid):
![screen shot 2017-10-26 at 14 34 08](https://user-images.githubusercontent.com/2316118/32053184-d6770932-ba5a-11e7-9f6e-f8e8527d6c6e.png)

When pressing at "1" two times in Chrome (Correct):
![screen shot 2017-10-26 at 14 34 04](https://user-images.githubusercontent.com/2316118/32053191-df62c130-ba5a-11e7-82a7-80900898dff1.png)

**What is the motivation / use case for changing the behavior?**
Its a fairly serious bug

**Please tell us about your environment:**
Windows 8.1 Internet explorer 11, 

* **ag-Grid version:** X.X.X
    "ag-grid-enterprise": "13.3.1",

* **Browser:**
Windows 8.1 Internet explorer 11, 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by rmc-software** [comment]
Hi,

We couldn't reproduce this on IE11. Does this occur for you on our demo page?

https://www.ag-grid.com/example.php
