### ISSUE TITLE
Ctrl-D overwrites values in cells that have suppressPaste = true

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [ag-grid/ag-grid#2010]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
"Copy down" (CTRL-D) sets values in cells for which the colDef has suppressPaste: true.

**Expected behavior**
If suppressPaste is true, Ctrl-D shouldn't do anything in that cell.

**Minimal reproduction of the problem with instructions**
Set up a colDef with editable:true and suppressPaste:false. Range select a few rows in that column and hit Ctrl-D.

Not sure I can set this up on plunkr since it's an Enterprise feature involving range selection.

**What is the motivation / use case for changing the behavior?**
I'm dealing with a column that needs to be edited using a custom editor component.  If suppressPaste is the only way to prevent bypassing the editor, then it needs to prevent bypassing via Ctrl-D as well.

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** 13.1.0 (both ag-grid and ag-grid-angular)

* **Browser:**
Chrome 61.0.3163.100 (Official Build) (64-bit)

* **Language:** TypeScript 2.3.4

**Comment by rmc-software** [comment]
This was fixed in v14 release yesterday. Closing as this issue has now been fixed.
