### ISSUE TITLE
New material theme set filter handles long string poorly

### ISSUE THREAD

**Issue by benschenker** [ag-grid/ag-grid#2011]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The Set filter does not handle long strings well with the new material theme, the text gets pushed on to the next line which often is out of the view
**Expected behavior**

a long string would show the first bunch of characters followed by `...`
**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/KNBmnyvL2mXZCEm0GQSe?p=preview click on the column filter and see the missing option (if you inspect, you can see it is there but just pushed too far down to see)
**What is the motivation / use case for changing the behavior?**

This does not look good
**Please tell us about your environment:**

OSX
* **ag-Grid version:** 13.3.1

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3241.0 Safari/537.36
* **Language:** TypeScript 2.2.1

**Comment by benschenker** [comment]
this may be a different bug, but also the container for the filters gets cut off at the bottom (needs another 2 pixels to show the whole bottom checkbox) and can be seen in the same plunker as above

**Comment by benschenker** [comment]
Current workaround is to set a keyCreator which truncates values at 25 characters

**Comment by petyosi** [comment]
Hi, 

we are aware of the issue (AG-849), it is already fixed and the fix will be part of our next release.
