### ISSUE TITLE
In range filter, upper range persists after removal

### ISSUE THREAD

**Issue by Shadrongowes** [ag-grid/ag-grid#2013]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The filter panel will still persist a value after removing in range filter.

**Expected behavior**
Upon removal of upper limit, if both limits are null, filter panel should be empty.

**Minimal reproduction of the problem with instructions**
1. open https://www.ag-grid.com/example.php
2. select *Total Winnings* number filter
3. select *In range*
4. enter lower limit, i.e. 45
5. enter upper limit i.e. 500,000
6. remove lower limit
7. remove upper limit
8. observe filter 

![image](https://user-images.githubusercontent.com/1544805/32107750-8a1d4f58-bafd-11e7-930f-7d8b5fb1480e.png)

**What is the motivation / use case for changing the behavior?**
When users are displaying solutions to our business, there is confusion that there is still a filter applied, when they feel it was removed.

**Please tell us about your environment:**
Bug can be replicated in https://www.ag-grid.com/example.php

* **ag-Grid version:** 13.3.1

* **Browser:**
Chrome Version 58.0.3029.96

* **Language:** [all]

**Comment by rmc-software** [comment]
Hi,

Thanks for raising this. I have created AG-1033 to track this issue. Updates to follow...

**Comment by JohnMasterson** [comment]
Just to confirm this was include in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
