### ISSUE TITLE
Latest version doesn't run when installed using bower

### ISSUE THREAD

**Issue by PhilDore11** [ag-grid/ag-grid#2014]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[  ] feature request
[  ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Able to install ag-grid 13.3.1 using bower

**Expected behavior**
Getting 'Uncaught Error: Cannot find module "./eventKeys"' when running my app with ag-grid installed using bower. This does not occur if I install using npm.

**Minimal reproduction of the problem with instructions**
- Install latest ag-grid using bower
- Include ag-grid in your project's dependencies
- Run the app

**What is the motivation / use case for changing the behavior?**
I have requirements to use bower for front-end libraries

**Please tell us about your environment:**
OSX, running an AngularJS application packaged using webpack

* **ag-Grid version:** X.X.X
13.3.1

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-989 our side to track this. I can see this file is missing for some reason in that release.

We'll ensure it works in the next release, currently scheduled for mid next week

thanks

**Comment by PhilDore11** [comment]
Thanks @seanlandsman 
Which version should I use in the meantime?

**Comment by seanlandsman** [comment]
13.2.0 looks like it should be ok (but I dont have a handy testbed to hand at the moment to confirm this)

**Comment by nishantgirbar** [comment]
Hi,
 
Yes by using 13.2.0 this issue is resolved but still I am getting below issue:

../src/assets/bower_components/ag-
grid/src/ts/rendering/cellComp.ts (666,9): Type 'IComponent<any, IAfterGuiAttach
edParams>' is not assignable to type 'ICellRendererComp'.
  Property 'refresh' is missing in type 'IComponent<any, IAfterGuiAttachedParams
>'.

Thanks,
Nishant Kumar

**Comment by rmc-software** [comment]
Hi,

AG-989 has now been fixed in v14.
