### ISSUE TITLE
Shouldn't the + sign below be a -  ?

### ISSUE THREAD

**Issue by cameronstubbs** [ag-grid/ag-grid#2016]
https://github.com/ag-grid/ag-grid/blob/64700ac17c770e8ad43f01169843e474d6e5304c/src/ts/gridPanel/gridPanel.ts#L963

**Comment by rmc-software** [comment]
I'm closing this unless you think there is a defect relating to this code?

If so could you please provide steps on how to reproduce issue.

Thanks

**Comment by cameronstubbs** [comment]
The line of code referenced is in the GridPanel.ensureIndexVisible routine where it handles 'middle'.  If you add about two thousand rows to the grid, and call ensureIndex as below, the row is visible, but not at the top, not the middle.

It could perhaps be my error, so here is the function I use to make that api call.

  _selectRow(rowId, context) {
    let rowNode = this.gridApi.getRowNode(rowId);
    if (rowNode !== undefined) {
      rowNode.setSelected(true, false, false);
      **this.gridApi.ensureIndexVisible(rowNode.rowIndex, 'middle');**
    }
  }
