### ISSUE TITLE
ag-Grid Polymer not render in firefox

### ISSUE THREAD

**Issue by londomloto** [ag-grid/ag-grid#2019]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Just opening example (https://www.ag-grid.com/example-polymer-rich-grid/?framework=polymer#gsc.tab=0) using firefox, grid not showing (my ff version: 56)

**Comment by seanlandsman** [comment]
Hi

This has been fixed and will be available in our next release

thanks
