### ISSUE TITLE
gridOptions.api.getModel() ts and actual types differ

### ISSUE THREAD

**Issue by benschenker** [ag-grid/ag-grid#2020]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

typescript types and actual types differ
**Expected behavior**

they should be the same
**Minimal reproduction of the problem with instructions**

1. In [Typescript types I see](https://github.com/ag-grid/ag-grid/blob/64700ac17c770e8ad43f01169843e474d6e5304c/dist/lib/gridApi.d.ts#L104) IRowModel
2. But in chrome devtools console:
this.gridOptions.api.getModel()
>>InMemoryRowModel

2 Seems to be correct.
**What is the motivation / use case for changing the behavior?**

get a compiler error when using the api correctly
**Please tell us about your environment:**

OSX
* **ag-Grid version:** 13.3.1

* **Browser:** `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3241.0 Safari/537.36`

* **Language:** TypeScript 2.2.1

**Comment by makinggoodsoftware** [comment]
In typescript we are using the Interface, the dev tools are giving you the implementation
