### ISSUE TITLE
External filter doesn't get applied to a parent group row if no child rows pass it in a tree structure

### ISSUE THREAD

**Issue by R4DIC4L** [ag-grid/ag-grid#2022]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a tree structure to group rows, if an external filter is present, the parent row is not validated against the filter unless at least a child row passes the filter. This makes it impossible to show a parent node for a certain condition that doesn't apply to its children.

**Expected behavior**
Based on a grid property, it should be configurable to apply the filter to a parent inclusively or exclusively related to its children. It could use a new property (best approach) or the existing _groupSelectsChildren_ property (on _true_ as it is, on _false_ call _doesExternalFilterPass_ on all nodes irrespective of their parent-child relationship).

**Minimal reproduction of the problem with instructions**
I have created a plunker to show this: https://plnkr.co/edit/k05fhmSKaDWjKM7vgnQJ?p=preview
In the given example, the _Ford Mondeo_ row is not shown as all its children don't satisfy the pricing filter (the filter method is not even called for that node) even though it passes the condition.

**What is the motivation / use case for changing the behavior?**
Sometimes, it is desired to apply a filter on each node independently of the parent-child relationship and display a parent node even if all its children don't pass the filter condition. This seems impossible, at the moment.

**Please tell us about your environment:**
* **ag-Grid version:** 13.3.0

* **Browser:** any

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
