### ISSUE TITLE
issue while sorting number with cell rendering.

### ISSUE THREAD

**Issue by ShankzPatil** [ag-grid/ag-grid#2023]
plz find column def 

 this.columnDefs.push({
                        headerName: columnName, field: "Column33",
                        unit: unit,
                        cellRenderer: this.cellRenderer,
                        headerTooltip: columnName
})

public cellRenderer(params) {

        return '<div class="cell-div-right">' +
            '<span style= "margin-bottom:2px; margin-right:1px;" >' +
            '<span class="value" >' + params.value + ' </span></span>' +
            '<span style="margin: 2px 0 0 2px;" >' +
            '<span class="unit">' + params.colDef.unit + '</span></span>' +
            '</div>';
    }

so my 
grid is

Current behaviour on sorting

Column33
    0.00 km
102.56 km
111.43 km
204.06 km
303.34 km
 33.56 km
 45.67 km

but i want on sorting

Column33
   0.00 km
 33.56 km
 45.67 km
102.56 km
111.43 km
204.06 km
303.34 km

**Comment by zlitteral** [comment]
I ran into the same issue, you have to use a comparator to get it to sort right. Inside the comparator you'll strip the numbers of their styling(remove km) convert them to floats and compare them

https://www.ag-grid.com/javascript-grid-sorting/#gsc.tab=0

**Comment by ShankzPatil** [comment]
thnx i did it.

**Comment by prudhvi37** [comment]
Hi ShankzPatil,
  Even I ran into same trouble, but I'm unable to resolve the issue. Can you please help me out with the code which you used. Thanks in advance

Example:

Values are : 
111.000
0.348
0.540

I want to sort it as 
0.348
0.540
111.000

**Comment by ShankzPatil** [comment]
Hi,

use  
```
this.columnDefs.push({
headerName: columnName, field: "Column33",
unit: unit,
cellRenderer: this.cellRenderer,
headerTooltip: columnName,
comparator: function (number1, number2) { 
    if (number1 === null && number2 === null) {
        return 0;
    }
   if (number1 === null) {
     return -1;
   }
  if (number2 === null) {
      return 1;
   }
 return number1 - number2;}
})
```

**Comment by prudhvi37** [comment]
Thanks for prompt reply ShankzPatil,
  But this is not working in my project.
I believe it is because the data is coming from the back-end and is getting stored as **params.value.**
and I don't know what should be given as number1 and number2.
and data is in integers and contains some strings as 'N/A' when there is no data to publish.
Please let me know if you can help me in getting out of the issue.
Thanks in advance.

**Comment by ShankzPatil** [comment]
You don't need to bother about number1 and number 2

While cell rendering and sorting it will compute your sorting order.
Just add comparator function as it is.

this.columnDefs.push({
headerName: columnName, field: "Column33",
unit: unit,
cellRenderer: this.cellRenderer,
headerTooltip: columnName,
comparator: function (number1, number2) { 
    if (number1 === null && number2 === null) {
        return 0;
    }
if(isNaN(number1)){ return -1}
if(isNaN(number2)){ return 1}
   if (number1 === null) {
     return -1;
   }
  if (number2 === null) {
      return 1;
   }
 return number1 - number2;}
})

**Comment by ShankzPatil** [comment]
If still facing issue please make plunkr or codepen i will surely help you.

**Comment by prudhvi37** [comment]
Hi @ShankzPatil,
 Sorry for delay response, 
Below is the code which was written in a service (Angular Application), please check and let me know if anything  I can do to make sorting work. Your help in fixing this is highly appreciated.

Thank you.

import { Injectable } from '@angular/core';
import { Component, ViewChild } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { SharedDataService } from '../services';

@Injectable()
export class TableParserService {
  constructor(private sharedDataService: SharedDataService) { }


  getGridOptions(report: any) {
    //console.log("getGridOptions report--",report)
    //console.log("getGridOptions report--",JSON.stringify(report));
    let gridOptions: any = {
      rowData: [],
      enableFilter: true,
      enableSorting: true,

      enableColResize: true,
      animateRows: true,
      pagination: true,
      paginationPageSize: 20,
      accentedSort: true,
      multiSortKey: 'ctrl',
      // toolPanel:'columns',
      // sideBar : true,
      //showtoolpanel:true,
      // enableRangeSelection:true,
      rowStyle: {
        fontSize: '14px',
        color: '#333333',
        fontFamily: 'BT Font Regular'
      }
    };

    let properties: any[] = report.response.reportConfiguration.configuration.properties.filter(item => item.display);
    let metrics: any[] = report.response.reportConfiguration.configuration.metrics;

    properties = properties.concat(metrics);
    //console.log("properties---",properties);

    gridOptions.columnDefs = properties.map((element, index) => {

      var column: any;
      if (index != 0) {
        if (element.name == "subelementName") {
          column = {
            headerName: element.displayName,
            field: element.name,
            hide: true,
            headerTooltip: element.displayName,
            suppressSizeToFit: true

          };
        }
        else if (report.response.userTemplateId == 'TopCoS' && element.name == "DIRECTION") {
          column = {
            headerName: element.displayName,
            field: element.name,
            hide: true,
            headerTooltip: element.displayName,
            minWidth: 70,
            suppressSizeToFit: true,
            valueFormatter : function (params) {
              if (typeof params.value == 'number') {
                return (params.value.toFixed(3));
              }
            },
            cellStyle: function (params) {
              if (params.colDef.field == "DEVICE_TYPE" ||
                params.colDef.field == "VPN" ||
                params.colDef.field == "SFN" ||
                params.colDef.field == "subelementName" ||
                params.colDef.field == "elementName" ||
                params.colDef.field == "ACCESS_TYPE" ||
                params.colDef.field == "CLOUD_SERVICE" ||
                params.colDef.field == "SERVICE_CONNECTION" ||
                params.colDef.field == "BT_DeviceType" ||
                params.colDef.field == "BT_QoSClassName"
              ) {
                return { 'text-align': 'left' };
              }
              else {
                return { 'text-align': 'right' };
              }
            }
          };
        }
        else {

          //console.log("element---",element);
          column = {
            headerName: element.displayName,
            field: element.name,
            headerTooltip: element.displayName,
            suppressSizeToFit: true,
            minWidth: 70,
            valueFormatter : function (params) {
              if (typeof params.value == 'number') {
                return (params.value.toFixed(3));
              }
            },
            cellStyle: function (params) {
              if (params.colDef.field == "DEVICE_TYPE" ||
                params.colDef.field == "VPN" ||
                params.colDef.field == "SFN" ||
                params.colDef.field == "subelementName" ||
                params.colDef.field == "elementName" ||
                params.colDef.field == "ACCESS_TYPE" ||
                params.colDef.field == "CLOUD_SERVICE" ||
                params.colDef.field == "SERVICE_CONNECTION" ||
                params.colDef.field == "BT_DeviceType" ||
                params.colDef.field == "BT_QoSClassName"
              ) {
                return { 'text-align': 'left' };
              }
              else {
                return { 'text-align': 'right' };
              }
            },
            tooltip: function (params) {
              return (params.valueFormatted ? params.valueFormatted : params.value);
            }
          };
        }

      } else if (index == 0) {
        column = {
          headerName: element.displayName,
          field: element.name,
          // width: 600, //This is for specific width
          suppressSizeToFit: true,
          headerTooltip: element.displayName,
          minWidth: 70,
          valueFormatter : function (params) {
            if (typeof params.value == 'number') {
              return (params.value.toFixed(3));
            }
          },
          tooltip: function (params) {
            return (params.valueFormatted ? params.valueFormatted : params.value);
          }
        };
      }

      //column.cellRenderer = 'CellLinkComponent';
      //if(report.response.reportConfiguration.configuration.name == "Site to Site Threshold Management Report") {  //report name
      if (index === 0 && !report.response.reportConfiguration.configuration.isLastLevel
        && (report.response.userTemplateId != 'PortAdminReport' &&
          report.response.userTemplateId != 'VpnAdminReport' &&
          report.response.userTemplateId != 'CoSAdminReport' &&
          report.response.userTemplateId != 'CPEAdminReport' &&
          report.response.userTemplateId != 'S2SAdminReport')) {
        column.cellRenderer = 'CellLinkComponent'
      }
      if (report.response.reportConfiguration.configuration.name == "Site to Site Threshold Management Report") {  //report name
        if ((index === 1 || index === 2) && !report.response.reportConfiguration.configuration.isLastLevel) {
          column.cellRenderer = function (params) {
            //console.log(params);
            return '<div id="editable_' + index + '"  title="Edit value" contenteditable=false" click-data="' + params.value + '">' + params.value + '</div>';
          }
        }
      }
      return column;
    });

    let events: any[] = report.response.response[0].events;
    //  let events: any[] = report.response.response;
    //   console.log("report.response.response[0].events--",report.response.response[0].events);
    //  console.log("report.response.response--",report.response.response);
    let eventsArray: any[] = report.response.response;
    let tempEvents = [];
    var count = 0
    //console.log("table---",events.length)
    if (events.length == 1) {
      for (let tempArr of eventsArray) {
        tempEvents[count] = tempArr.events[0];
        count++;
      }
    } else {
      tempEvents = events;
    }

    gridOptions.rowData = tempEvents.map(element => {
      let row: any = {};
      gridOptions.columnDefs.forEach(column => {
        // console.log('field value--',column.field + " : "+row[column.field])
        //  console.log('element value --',element[column.field])
        // (element[column.field] == null)?row[column.field] = "null" :
        isNaN(element[column.field]) ? row[column.field] = element[column.field] :
          row[column.field] = Math.round(element[column.field] * 1000) / 1000;

        // console.log('field value later-- ',column.field + " : "+row[column.field])
        //  console.log('----------');

        /* Bandwidth unit added here */
        // if (row.CURRENT_FLEX_BANDWIDTH) {
        //   if (row.CURRENT_FLEX_BANDWIDTH < 1024) {
        //     row[column.field] = row[column.field];
        //   }
        //   if (row.CURRENT_FLEX_BANDWIDTH > 1024 && row.CURRENT_FLEX_BANDWIDTH < 1000000) {
        //     var val = row.CURRENT_FLEX_BANDWIDTH / 1000;
        //     row[column.field] = val + 'K';
        //   }
        //   else if (row.CURRENT_FLEX_BANDWIDTH >= 1000000 && row.CURRENT_FLEX_BANDWIDTH < 1000000000) {
        //     var val = row.CURRENT_FLEX_BANDWIDTH / 1000000;
        //     row[column.field] = val + 'M';
        //   }
        //   else if (row.CURRENT_FLEX_BANDWIDTH >= 1000000000) {
        //     var val = row.CURRENT_FLEX_BANDWIDTH / 1000000000;
        //     row[column.field] = val + 'G';
        //   }
        //   else if (row.CURRENT_FLEX_BANDWIDTH == 1024) {
        //     var val = row.CURRENT_FLEX_BANDWIDTH / 1024;
        //     row[column.field] = val + 'K';
        //   }
        // }
        /* Bandwidth unit End here */
        if (row[column.field] === -1) {
          row[column.field] = '-';
        }
        // console.log('field value',row[column.field])
      });

      return row;
    });
    //console.log("gridOptions---------",gridOptions)

    return gridOptions;
  }

}

**Comment by AnkitSalian** [comment]
@ShankzPatil 
Does the datatype of your is string or number
For me if the value is number and have modified the cell with format value
then sorting is not working for me
