### ISSUE TITLE
Trigger set filter to open when clicking on floating input

### ISSUE THREAD

**Issue by Abrissirba** [ag-grid/ag-grid#2024]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have a set filter together with a floating filter the input field is disabled. Some users gets confused about this and tries to enter text into the input and gets frustrated when it doesn't work.  

**Expected behavior**
I would suggest that if the user clicks the disabled input it should trigger the set filter to open just as if you clicked on the filter icon.

**What is the motivation / use case for changing the behavior?**
Better usability

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by markoueis** [comment]
On the main demo on the website, it does exactly what @Abrissirba is asking for, namely the set filter opens when you click on the disabled input, and the cursor moves to the set filter to allow typing. On the other grids on the website in the docs it does not do this. How can we replicate that experience? @makinggoodsoftware how can we replicate this?
