### ISSUE TITLE
Row Selection highlight color hould overwrite the cellClassRules

### ISSUE THREAD

**Issue by jkjha** [ag-grid/ag-grid#2025]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

1. Use cellClassRules to paint the cell in different color. Exa. Red.
2. Now enable multiselection for the grid.
3. Select a row. 
Color of all the columns with cellClassRules doesn't change. 
**Expected behavior**

Since whole row gets selected, whole row should have same Highlighting color along with the columns with cellClassRules.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

v8.0.0

* **Browser:**

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
AngularJS

Plunkr: https://plnkr.co/edit/rWHoWCnJU6RubyyEoC7B?p=preview

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as designed, selection takes precedence over cell styling, this is a feature request and right now we are only taking feature requests/support that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
