### ISSUE TITLE
Stop editing on navigation key down

### ISSUE THREAD

**Issue by whiteblackkeys** [ag-grid/ag-grid#2031]
**I'm submitting a ...**  (check one with "x")
```
[x] support request 
```

**Current behavior**
[The documentation says](https://www.ag-grid.com/javascript-grid-cell-editing/#gsc.tab=0) that 

> The grid will stop editing when any of the following happen
[ ... ]
Navigation Key Down: Editing will stop, accepting changes, and editing will move to the next cell in the direction of the navigation key.

But even in the examples of the documentation page it doesn't happen: if I'm editing a cell and push the UP/DOWN key, it keeps editing the cell

 **Expected behavior**
I expect that pushing UP/DOWN keys, it accepts the changes and moves to the next cell in the direction of the navigation key.

* **ag-Grid version:** 13.3.1

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for raising this, we will update the docs to make it obviuos that the edit will only stop when using left and right arrow
