### ISSUE TITLE
autoSizeColumns not sizing columns when scrolled into view

### ISSUE THREAD

**Issue by jbarber2016** [ag-grid/ag-grid#2032]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I call autoSizeColumns with the full list of columns.  When the column isn't visible it doesn't resize the column, which is fine.  However, when I scroll and the column is visible it never is resized.

**Expected behavior**

When scrolling the columns the columns not in view should get resized.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/2TkEDHmEn40ajQZIU5MC

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 13.3.1, 14.0.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by rmc-software** [comment]
Hi,

I have updated your plunker: https://plnkr.co/edit/5pdKLf9AEejumj99sCiR?p=preview

This should be doing what you expect now.

Closing as it's not a defect.

**Comment by jbarber2016** [comment]
How is it not a defect?  The column never gets resized at all? what is the point of only resizing columns in view?
