### ISSUE TITLE
Mouse events triggering app-wide change detection in angular

### ISSUE THREAD

**Issue by instantaphex** [ag-grid/ag-grid#2034]
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Mouse events (mouseover, mouseenter, mouseout, etc...) registered in RowComp, GridPanel and others are triggering change detection in angular.  This is killing performance in IE11 when using the grid in along with angular.  Looking through the code, I don't think that this is something that can be fixed by changing the functionality of the ag-grid-angular wrapper.  

I was able to increase performance by quite a bit by simply removing 

**Expected behavior**
Moving the mouse over the grid should not constantly cause change detection to run.

**Minimal reproduction of the problem with instructions**
I originally created an issue here:

https://github.com/ag-grid/ag-grid-angular/issues/185

But I think that the problem needs to be solved in ag-grid itself.

Here is a plunker that reproduces the problem.  Open the console and mouse over the grid.

https://plnkr.co/edit/1kYVxw?p=preview

**What is the motivation / use case for changing the behavior?**
To increase performance (currently horrible in IE when there are a lot of bindings)

**Please tell us about your environment:**
Windows 10, IE11

* **ag-Grid version:** X.X.X
14.0.0

* **Browser:**
all

* **Language:** 
TypeScript

**Comment by milleraundra** [comment]
I am experiencing this same issue. Using the plnkr above, I ran a profile while moving my mouse in and out of the grid, never clicking. Notice the size and number of call stacks and the steady climb in the JS Heap.

This seems to be too much noise for such a small action, and it is compounded on larger apps.

![plnkr-performance-and-heap](https://user-images.githubusercontent.com/16562123/33086069-708241e6-ce9b-11e7-98c6-260e3a51a10d.PNG)

**Comment by instantaphex** [comment]
I was able to get a small improvement by bootstrapping my application inside a zone that blacklisted all undesired effects from running change detection, but that is really only half the problem.   As @milleraundra mentioned, the act of creating the events and executing the callbacks themselves starts dropping the frame rate even when no change detection is occurring (mostly only noticeable in IE11... which is what my users use).  

A few things:

1.) I'm really curious why ag-grid needs to add and remove 'ag-grid-hover' classes over and over.  Why not just use the :hover pseudo-class for styling?  This would be a step in the right direction in terms of IE performance.  

rowComp.js line 955 (v14.2):

```
RowComp.prototype.addHoverFunctionality = function (eRow) {
        var _this = this;
        // because we use animation frames to do this, it's possible the row no longer exists
        // by the time we get to add it
        if (!this.active) {
            return;
        }
        // because mouseenter and mouseleave do not propagate, we cannot listen on the gridPanel
        // like we do for all the other mouse events.
        // because of the pinning, we cannot simply add / remove the class based on the eRow. we
        // have to check all eRow's (body & pinned). so the trick is if any of the rows gets a
        // mouse hover, it sets such in the rowNode, and then all three reflect the change as
        // all are listening for event on the row node.
        // step 1 - add listener, to set flag on row node
        this.addDestroyableEventListener(eRow, 'mouseenter', function () { return _this.rowNode.onMouseEnter(); });
        this.addDestroyableEventListener(eRow, 'mouseleave', function () { return _this.rowNode.onMouseLeave(); });
        // step 2 - listen for changes on row node (which any eRow can trigger)
        this.addDestroyableEventListener(this.rowNode, rowNode_1.RowNode.EVENT_MOUSE_ENTER, function () {
            utils_1._.addCssClass(eRow, 'ag-row-hover');
        });
        this.addDestroyableEventListener(this.rowNode, rowNode_1.RowNode.EVENT_MOUSE_LEAVE, function () {
            utils_1._.removeCssClass(eRow, 'ag-row-hover');
        });
    };
```

Now, I'm not sure if adding and removing the ag-row-hover is for compatability reasons, but IE has had :hover for <a> elements since 4.0 and for all elements since 7.0. 

2.) Things like this could be opt-in:

gridPanel.js line 305 (v14.2)
```
GridPanel.prototype.addMouseListeners = function () {
        var _this = this;
        var eventNames = ['click', 'mousedown', 'dblclick', 'contextmenu', 'mouseover', 'mouseout'];
        eventNames.forEach(function (eventName) {
            var listener = _this.processMouseEvent.bind(_this, eventName);
            _this.eAllCellContainers.forEach(function (container) {
                return _this.addDestroyableEventListener(container, eventName, listener);
            });
        });
    };
```
I would assume that for most use cases, it's wholly unnecessary to create blanket event listeners for all of these and broadcast them out:

cellComp.js line 688 (v14.2)
```
CellComp.prototype.onMouseOut = function (mouseEvent) {
        var cellMouseOutEvent = this.createEvent(mouseEvent, events_1.Events.EVENT_CELL_MOUSE_OUT);
        this.beans.eventService.dispatchEvent(cellMouseOutEvent);
    };
    CellComp.prototype.onMouseOver = function (mouseEvent) {
        var cellMouseOverEvent = this.createEvent(mouseEvent, events_1.Events.EVENT_CELL_MOUSE_OVER);
        this.beans.eventService.dispatchEvent(cellMouseOverEvent);
    };
```
Maybe there is some functionality in ag grid that hinges on this to work properly.  Either way I saw performance gains by commenting this type of thing out locally.

**Comment by instantaphex** [comment]
So I've managed to get rid of the functionality, albeit in an awful way.  After seeing @catahoc solution in another github issue, I've created this ugly hack:

```
import { GridPanel, CellComp, RowComp } from 'ag-grid';

/* tslint:disable */
(function () {
  (GridPanel.prototype as any).addMouseListeners = function () {
    var _this = this;
    var eventNames = ['click', 'mousedown', 'dblclick', 'contextmenu'];
    eventNames.forEach(function (eventName) {
      var listener = _this.processMouseEvent.bind(_this, eventName);
      _this.eAllCellContainers.forEach(function (container) {
         return _this.addDestroyableEventListener(container, eventName, listener);
      });
    });
  };
  (CellComp.prototype as any).onMouseOut = function (mouseEvent) { };
  (CellComp.prototype as any).onMouseOver = function (mouseEvent) { };
  (RowComp.prototype as any).addHoverFunctionality = function (eRow) { };
})();
/* tslint:enable */
```

If you're not using TypeScript you won't need the ( as any) stuff.

**Comment by milleraundra** [comment]
@instantaphex where are you running this code?

**Comment by instantaphex** [comment]
Im running before the angular app bootstraps.  If you're not using angular
you can just run it before your ag-grid code.  Also im running my app in a
zone that blacklists ag-grid scroll events from running change detection.
That was also dropping my frame rate pretty badly.  I can post that on
Monday if you need it.

One other thing that made a HUGE difference for me in I was making sure
that the container housing the grid doesn't have a border radius on it.
That actually sped it up more than any single other thing I did.  It's
apparently a known bug in IE.

On Nov 22, 2017 1:43 PM, "Aundra Miller" <notifications@github.com> wrote:

@instantaphex <https://github.com/instantaphex> where are you running this
code?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ag-grid/ag-grid/issues/2034#issuecomment-346454677>,
or mute
the thread

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved
