### ISSUE TITLE
set hyperlink (ex: <a  class="disabled">` </a>`)dynamically to particular cell after an event occured (SetDataValue not working)

### ISSUE THREAD

**Issue by SanthoshReddyNagulapally** [ag-grid/ag-grid#2037]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by SanthoshReddyNagulapally** [comment]
Current behavior :  able to return hyperlink at frist time with below code 
  headerName: 'Export File', field: 'exportContent', 
                cellRenderer: function (params) {
                    return `<a data-action-type='exportContent'>`
                        +params.value+
                        `</a>`;
                }
Expected behaviour:

after adding new row to the grid 
this.rowData.push(success);
  
exportContent (onlyu that particular)cell shoud be disabled.like i have change other status column 

 this.gridOptions.api.getRowNode(updatedBulkJobId).setDataValue('status', res); //like this i need to change export conetent to disabled

envoronment : 
 "ag-grid": "^13.3.1",
    "ag-grid-angular": "^13.3.0",
  "typescript": "2.3.2",

browser : chrome

**Comment by makinggoodsoftware** [comment]
Hi to see examples on how to use renderers, please find the docs below:

https://www.ag-grid.com/javascript-grid-cell-rendering-components/
