### ISSUE TITLE
Setting floatingFilterComponentParams for column cause removing styles from header.

### ISSUE THREAD

**Issue by Mikasasasa** [ag-grid/ag-grid#2039]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I set floatingFilterComponentParams: { suppressFilterButton: true } for column, I want to show floating filter without additional menu, then column header loss its styling

**Expected behavior**
Menu shouldn't be displayed, but header should be displayed as before.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/CC9d0QI3SxiHqEMQA59z?p=preview for silver and bronze column it's visible.

**What is the motivation / use case for changing the behavior?**
I want to show only input without additional menu.

**Please tell us about your environment:**
Win 7, latest chrome

* **ag-Grid version:** 14.0.2

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.3.3, angular 4.2.4, angular-cli 1.4.6

**Comment by makinggoodsoftware** [comment]
Not sure what you are referring to, 

In the plunkr I can't see anything not working as expected, please have a look at the docs:

https://www.ag-grid.com/javascript-grid-floating-filter-component/

**Comment by Mikasasasa** [comment]
Thanks for the response, As I've described it above the issue is with styles. Here you can see the snip from attached plunkr:
![image](https://user-images.githubusercontent.com/3672095/32714943-66b5bafe-c850-11e7-8112-72b3d7fc85c0.png)
As you can see for Gold column filtering is well styled , and for Silver column it's not styled at all - it's just a regular input. I expect that it looks like in Gold but without this icon on the right.

I think it should be reopen.
