### ISSUE TITLE
Allowing suppressing adding classes to cells and rows on hover

### ISSUE THREAD

**Issue by instantaphex** [ag-grid/ag-grid#2040]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Any time a row or cell is hovered, classes are being added and removed from the dom.

**Expected behavior**
It would be really nice to allow for disabling these expensive operations.

**Minimal reproduction of the problem with instructions**
https://www.ag-grid.com/example.php
mouse over the grid while looking at the dom in the dev tools

**What is the motivation / use case for changing the behavior?**
Performance in IE11

**Please tell us about your environment:**
any

* **ag-Grid version:** X.X.X
14.0.1

* **Browser:**
any

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
