### ISSUE TITLE
unexpected behaviors upgrading from 9.0.3 to 14.1.0

### ISSUE THREAD

**Issue by MolallaComm** [ag-grid/ag-grid#2041]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

1. columnApi.autoSizeAllColumns() doesn't seem to work reliably anymore - it resizes some columns but not others - it worked perfectly in v9 - similar to 3 below I think it may be because the underlying data has newlines in it - i.e. the columns that don't get resized are ones that can optionally have multiple lines.

2. the set filter used to be case insensitve in v9 when matching but now appears to be case sensitive in v14 with no easy way I could figure out how to change it back to being insensitive - i checked and excel 2016 is case insensitive so I think you want to keep the old behavior.

3. the set filter appears to have paint problems in v14 - see attached - i think this may be related to the data having newlines in it - i'm guessing that that v9 ignored the newlines and maybe v14 handles them differently.

I observed duplicate behavior in chrome, firefox, and safari so think it is probably not browser specific.

![image](https://user-images.githubusercontent.com/1542219/32526045-456aa814-c3dc-11e7-9551-896f8700d892.png)

I can put together a sample project if that isn't enough to go on.

**Comment by makinggoodsoftware** [comment]
Hi,

I believe this got picked up already from zenDesk.

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
