### ISSUE TITLE
row group sorting in ag-grid-enterprise 8.2.0

### ISSUE THREAD

**Issue by HariBabuThubati** [ag-grid/ag-grid#2043]
@ceolter : I am using ag-grid-enterprise 8.1.0 , i am using rowgroup on one column andd also using valueGetter to add the currency symbol and format the decimal , when i am sorting the perticula column where i am using valueGetter ,getting an error "Cannot read property 'testname' of null"."  

i changed the valueGetter to cellRender, it's working  but when i am exporting to excel the symbol is not displaying in excel.

**Comment by seanlandsman** [comment]
@HariBabuThubati 

Hi,

If you are an Enterprise customer (or are Evaluating ag-Grid Enterprise) and wish to report a Bug or raise a new Feature Request please do so on our [Members Forum](https://ag-grid.com/forum/forumdisplay.php?fid=5).

To Sign Up:
Send an email to accounts@ag-grid.com with your license key

thanks
