### ISSUE TITLE
AG-Grid CellRenderer issue

### ISSUE THREAD

**Issue by innov-richa76** [ag-grid/ag-grid#2045]
**Current behavior**
On click of the cell the function test() is not getting called and hence no alert is being shown up.

**Expected behavior**
The function test() should be called on click of the cell of Test column and therefore the alert should be shown.

**Minimal reproduction of the problem with instructions**
Here is the plunker with the issue
https://plnkr.co/edit/ZzjtTJzQvtQ6LW8XJQOi?p=preview

**What is the motivation / use case for changing the behavior?**
N/A

* **ag-Grid version:** 13.0.X

* **Language:** [all | TypeScript 2.4]

**Comment by makinggoodsoftware** [comment]
Hi, I am afraid that the plunkr is not working
