### ISSUE TITLE
Number of selected rows

### ISSUE THREAD

**Issue by Leonzen** [ag-grid/ag-grid#2046]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no function which returns the number of selected Rows

**Expected behavior**
There should be a function which is able to return the number of selected Rows

**What is the motivation / use case for changing the behavior?**
The number of selected rows is an important information and therefor there should be a function which easiely returns that value. The only method to get this value was by calling:
`gridOptions.api.getSelectedRows().length`

**Please tell us about your environment:**
OS: Windows 10
IDE: Brackets
Package manager: NPM
Browser: Chrome, Firefox

* **ag-Grid version:** 14.0.1

* **Browser:**
_Chrome:_ Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
_Firefox:_ Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid we don't accept feature requests from github, we only accept feature requests through the customer forum..

https://www.ag-grid.com/forum/
