### ISSUE TITLE
Data getting overlapped when large amount of data loads

### ISSUE THREAD

**Issue by nilulande05** [ag-grid/ag-grid#2047]
We have used ag-grid v6.1.0 and facing issue of data overlapped. You need to scroll the data and sometimes it shows overlapped as per attached screenshot.

We are able to reproduce issue from all latest browsers. IE,Mozilla and Chrome
![data overlapped](https://user-images.githubusercontent.com/22637970/32649379-e1e82b40-c61f-11e7-97b0-8a5422549a1c.png)

**Comment by makinggoodsoftware** [comment]
Hi, can you provide us with a reproducible scenario? I can't reproduce this on my end
