### ISSUE TITLE
ColDef typings bug - headerComponentFramework

### ISSUE THREAD

**Issue by GeorgeKnap** [ag-grid/ag-grid#2050]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The typings for `headerComponentFramework` might be wrong. In 14.0.1 version it's 
```
 headerComponentFramework?: {
        new (): any;
    };
```
This creates typescript error if renderer component has a constructor parameter.
 `Cannot convert type {...}[] to type ColDef[]`

**Expected behavior**
I think the `headerComponentFramework` should be `any` type just like the  `cellRendererFramework`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
```
"@angular/animations": "5.0.1",
    "@angular/common": "5.0.1",
    "@angular/compiler": "5.0.1",
    "@angular/compiler-cli": "5.0.1",
    "@angular/core": "5.0.1",
    "@angular/forms": "5.0.1",
    "@angular/platform-browser": "5.0.1",
    "@angular/platform-browser-dynamic": "5.0.1",
    "@angular/router": "5.0.1",
    "ag-grid": "14.0.1",
    "ag-grid-angular": "14.0.0",
    "ag-grid-enterprise": "14.0.1",
```

* **ag-Grid version:** 14.0.1

* **Language:** 
Typescript 2.6.1

**Comment by makinggoodsoftware** [comment]
Hi,

I don't think that is the case, you are meant to use this property to specify your framework paramaterless constructor, so I think this typing is more adequate

**Comment by GeorgeKnap** [comment]
Hi
ok, let's say I have an Angular  header cell renderer component like this:
```
export class TranslateHeaderRenderer implements IHeaderAngularComp {
 constructor(private translateService: TranslateService){ }

...

}
```

How do I add this to column definition? This will produce type error:
```
{
field: 'foo'
headerComponentFramework: TranslateHeaderRenderer
} as ColDef
```
