### ISSUE TITLE
CellEditor of type 'select' doesn't works when it is bound to boolean field

### ISSUE THREAD

**Issue by Marjanca** [ag-grid/ag-grid#2052]
So, I used this property for the string values and it worked without problems, but when I wanted to apply cell editor of type select with the values "Yes" and "No" to correspond boolean values true/false, it behaved little bit strange.

This is the example: [Plunker](https://plnkr.co/edit/9B9qNEZVeQZCzU0CWUJX?p=preview)
In example.js there is part for "second hand" column.

Reproducing steps are:

- Expand cell on the second row and "second hand" column
- Change Yes to No
- Click again within the cell
- Value is retrieved to "Yes" again

In console within dev tools you can see an object with the properties new value and old value.

Any help would be useful or at least inputs how to use cell editor when we have boolean values and not strings.

Kind regards,
Marija

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
