### ISSUE TITLE
AG-Grid CellRenderer issue

### ISSUE THREAD

**Issue by innov-richa76** [ag-grid/ag-grid#2053]
**Current behavior**
On click of the cell the function test() is not getting called and hence no alert is being shown up.

**Expected behavior**
The function test() should be called on click of the cell of Test column and therefore the alert should be shown.

**Minimal reproduction of the problem with instructions**
Here is the plunker with the issue
https://plnkr.co/edit/ZzjtTJzQvtQ6LW8XJQOi?p=preview

**What is the motivation / use case for changing the behavior?**
N/A
**Please tell us about your environment:**
IDE:visual studio

* **ag-Grid version:** 13.0.X

* **Language:** [all | TypeScript 2.4]

**Comment by innov-richa76** [comment]
Can anyone provide some suggestions on it?

**Comment by instantaphex** [comment]
When you provide a cell renderer like this:

```
function testCellRenderer(){
  return '<button class="glyphicon glyphicon-edit" (click)="test()"></button>'
}
```
It basically is a way to create a simple template renderer for the cell.  You need to need to either make it an ag grid component and add an event listener for the click event using addEventListener or make it an angular component.  Here you're just providing a template with angular template syntax, but you aren't actually giving it to angular to compile.

Check out the documentation for the different types of cell renderers here:

https://www.ag-grid.com/javascript-grid-cell-rendering-components/#gsc.tab=0

**Comment by innov-richa76** [comment]
Thank you so much. It worked fine when I added a event listener for the click event. :)

**Comment by AGSTRANGER** [comment]
@instantaphex  what do you mean by "You need to need to either make it an ag grid component and add an event listener for the click event using addEventListener or make it an angular component."
