### ISSUE TITLE
Typescript types for "sortModel" and "filterModel" are unhelpful.

### ISSUE THREAD

**Issue by UselessPickles** [ag-grid/ag-grid#2054]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Typescript types for "sortModel" and "filterModel" throughout the code are unhelpful.

Most of the methods/interfaces that deal with "sortModel" and "filterModel" simply have the type as "any". This is unhelpful in Typescript.

Examples: 

in IEnterpriseGetRowsRequest, RowNodeCacheParams, IGetRowsParams:
```ts
    sortModel: any;
    filterModel: any;
```

in SortController:
```ts
    getSortModel(): { // WHY ISN'T THIS A WELL-DEFINED/REUSED INTERFACE?
        colId: string;
        sort: string;
    }[];
    setSortModel(sortModel: any): void;
```

in GridApi: 
```ts
    setSortModel(sortModel: any): void;
    getSortModel(): { // WHY ISN'T THIS A WELL-DEFINED/REUSED INTERFACE?
        colId: string;
        sort: string;
    }[];
    setFilterModel(model: any): void;
    getFilterModel(): any;
```
etc...

**Expected behavior**
There should be well-defined interfaces/types for sortModel and filterModel so that I get useful IDE assistance and compiler assistance to ensure I am using sortModels and filterModels correctly.

**Minimal reproduction of the problem with instructions**
Look at the code.

**What is the motivation / use case for changing the behavior?**
Improve type safety when developing in TypeScript.

**Please tell us about your environment:**
Irrelevant

* **ag-Grid version:** 
14.1.1

* **Browser:**
Irrelevant

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.6

**Comment by UselessPickles** [comment]
I created a pull request to fix the "sortModel" portion of this issue. The structure of a "filterModel" is less obvious to me right now, so I though it was best to tackle it separately later.

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for the Pull Request, I have created the ticket AG-1231 that you can track from our pipeline

https://www.ag-grid.com/ag-grid-pipeline/

Thanks

**Comment by UselessPickles** [comment]
@makinggoodsoftware I see that AG-1231 is currently in the "backlog" of "Complex Feature Requests"

That sounds to me like it may get ignored and not fixed for a very long time. Is there any way to make this a higher priority? At least for the "sortModel" portion, which seems like the more obvious/simpler of the two and already has a good starting point with my pull request.

The "Complex Feature Requests" categorization also baffles me. This is not really a feature request at all because it's not a request for any new behavior, and it's not really complex. The end result should be absolutely no change in executable/observable behavior. The only complexity is is getting the strict null typing correct, which goes along with AG-980.

**Comment by codeNoobie** [comment]
Is this still in the backlog?

**Comment by RobbinBaauw** [comment]
If anyone is looking for types, I made some (point your "ag-grid-community" to a file containing this in `tsconfig.compilerOptions.paths.ag-grid-community`):
```typescript
export interface ProvidedFilterModel {
    filterType: "text" | "date" | "number";
}

export interface ISimpleFilterModel extends ProvidedFilterModel {
    type: typeof possibleFilterTypes[number];
}

export interface ICombinedSimpleModel<M extends ISimpleFilterModel> extends ProvidedFilterModel {
    operator: "AND" | "OR";
    condition1: M;
    condition2: M;
}

export interface TextFilterModel extends ISimpleFilterModel {
    filterType: "text";
    type: typeof possibleTextFilterTypes[number];

    /**
     *  The text value associated with the filter.
     *  It's optional as custom filters may not have a text value
     */
    filter?: string;
}

export interface NumberFilterModel extends ISimpleFilterModel {
    filterType: "number";
    type: typeof possibleNumberFilterTypes[number];

    /**
     * The number value(s) associated with the filter.
     * - custom filters can have no values (hence both are optional).
     * - range filter has two values (from and to).
     */
    filter?: number;

    /**
     * @see filter
     */
    filterTo?: number;
}

export interface DateFilterModel extends ISimpleFilterModel {
    filterType: "date";
    type: typeof possibleDateFilterTypes[number];

    /**
     * The date value(s) associated with the filter.
     * The type is string and format is always YYYY-MM-DD e.g. 2019-05-24
     * - custom filters can have no values (hence both are optional).
     * - range filter has two values (from and to).
     */
    dateFrom?: string;
    dateTo?: string;
}

export type FilterModel =
    | TextFilterModel
    | NumberFilterModel
    | DateFilterModel
    | ICombinedSimpleModel<TextFilterModel>
    | ICombinedSimpleModel<NumberFilterModel>
    | ICombinedSimpleModel<DateFilterModel>;

export * from "ag-grid-community/main";
```

with a helper file

```typescript
/* Copied from simpleFilter.ts in ag-grid */

export const EMPTY = "empty";
export const EQUALS = "equals";
export const NOT_EQUAL = "notEqual";
export const LESS_THAN = "lessThan";
export const LESS_THAN_OR_EQUAL = "lessThanOrEqual";
export const GREATER_THAN = "greaterThan";
export const GREATER_THAN_OR_EQUAL = "greaterThanOrEqual";
export const IN_RANGE = "inRange";
export const CONTAINS = "contains";
export const NOT_CONTAINS = "notContains";
export const STARTS_WITH = "startsWith";
export const ENDS_WITH = "endsWith";

export const possibleFilterTypes = [
    EMPTY,
    EQUALS,
    NOT_EQUAL,
    LESS_THAN,
    LESS_THAN_OR_EQUAL,
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL,
    IN_RANGE,
    CONTAINS,
    NOT_CONTAINS,
    STARTS_WITH,
    ENDS_WITH
] as const;

export const possibleTextFilterTypes = [
    EMPTY,
    EQUALS,
    NOT_EQUAL,
    CONTAINS,
    NOT_CONTAINS,
    STARTS_WITH,
    ENDS_WITH
] as const;

export const possibleNumberFilterTypes = [
    EMPTY,
    EQUALS,
    NOT_EQUAL,
    LESS_THAN,
    LESS_THAN_OR_EQUAL,
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL,
    IN_RANGE
] as const;

export const possibleDateFilterTypes = [EMPTY, EQUALS, NOT_EQUAL, LESS_THAN, GREATER_THAN, IN_RANGE] as const;
```
