### ISSUE TITLE
How to stay the expand state of treeData,when adding a new column

### ISSUE THREAD

**Issue by GitHubForQiuKai** [ag-grid/ag-grid#2055]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

when adding a new column,the expand state of treeData is missing

**Expected behavior**

stay state
**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/l8iGsIMOEDL4AuGzD3EG?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version: 14.1.0

* **Browser:**chrome

* **Language:** [ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
