### ISSUE TITLE
"Equals" filtering with "nullComparator.equals: true" includes null values to the result

### ISSUE THREAD

**Issue by anatolyzolotar** [ag-grid/ag-grid#2056]
I'm not sure if it worked in the same way before or it's a bug.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently using of `columnDef.filterParams.nullComparator.equals: true` works fine for "Not equal" filtering since it includes null values to the result. However I'm convinced that using of this property with `true` breaks the logic of "Equal" filtering - null values are also included in the result.

**Expected behavior**
When we use `columnDef.filterParams.nullComparator.equals: true`
"Not equal" filtering with some entered value should include null values in the result
"Equal" filtering should not.

**Minimal reproduction of the problem with instructions**

You can reproduce it in documetation: 
https://www.ag-grid.com/javascript-grid-filtering/#example-null-filtering
1) Set "equals" radio button to "True"
2) Select "Not equal" filtering for "Age" column, enter "36" - the result will be the last two rows with null values **CORRECT**
3) Change filter type to "Equal"  for the same "Age" column, leave the previous "36" value - the result is first two rows with value "36" and last two rows with null **INCORRECT**

**What is the motivation / use case for changing the behavior?**

Confusing behavior. In terms of common sense null values are not equal to "36" value from the filter.

* **ag-Grid version:** 13.3.1

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

* **Language:** TypeScript 2,4

**Comment by anatolyzolotar** [comment]
Now I think it's a bug. Can anyone tell me is it supposed that filter should work this way?

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as designed, I see your point though so I have created this ticket in our pipeline AG-1230

Please track this item from there.

Thanks
