### ISSUE TITLE
Custom sort on multiple grids

### ISSUE THREAD

**Issue by cretupaul** [ag-grid/ag-grid#2057]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have three grids on a specific page and I want to make a sort syncronisation between those.
I want to mention that only one grid has a grid header and the other 2 are without grid header. How can i make the sort programatically? I`ve made the communication between those 3 grids, and when i press on the column, i receive the action "grid-sort", but i am kind of block in here because i do not know how can i "tell" to the other grids how to filter themselves.
**Expected behavior**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:**11

* **Browser:**

* **Language:** [all ]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
