### ISSUE TITLE
Changing filter type in infinite scroll triggers a redraw of the rows

### ISSUE THREAD

**Issue by adrienblin** [ag-grid/ag-grid#2060]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you go on the demo page of the infinite scroll : https://www.ag-grid.com/javascript-grid-infinite-scrolling/#example-block-larger-page , under 'Example - Sorting, Filtering and Selection', when you change the filter type of the 'Age' column (for instance 'Less than'), it redraws the rows, which is really not user friendly, and doesn't seem to be relevant.

**Expected behavior**
Changing the column filter type doesn't trigger a redraw of the rows.

**Minimal reproduction of the problem with instructions**
See on the ag-grid demo page.

**What is the motivation / use case for changing the behavior?**
When the grid is wide and you have to scroll to show a column, changing the filter type will send you back to the left of the grid, which is quite frustrating for the user, without mentioning that it feels like it's bugging.

**Please tell us about your environment:**
Not relevant.

* **ag-Grid version:** X.X.X
ag-grid's demo page.

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
