### ISSUE TITLE
getRowClass fails to apply class to element

### ISSUE THREAD

**Issue by IgorDraskovic** [ag-grid/ag-grid#2063]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
In my angular application I am trying to add a class to a row when it is expanded, and remove said class with it collapses.  However, when I fire the event handler, no class is added/removed.

The grid in my html looks as follows:
```
<ag-grid-angular #agGrid style="width: 100%; height:85vh" class="ag-material grid-Holdings" 
  [gridOptions]="gridOptions" 
  [rowData]="rowData"
  ... 
  (rowGroupOpened)="addRowClass($event)">
</ag-grid-angular>
```
My grid.component.ts has a method addRowClass() that looks as follows:

```
    addRowClass(params) {
        this.gridOptions.getRowClass = (params) => {
            if(params.node.expanded) {
                return 'my-class';
            }
        }
    }
```

**Comment by catahoc** [comment]
I think getRowClass got sealed after grid load (read to GridApi internals and never re-read again). Why don't you define getRowClass before grid load? E.g.
```
gridOptions = {...
   getRowClass: this.yourCallback()
}
```

Also, you can see, that your callback may apply multiple times (on each event fire) while its contents are never changed from time to time - this looks suspicious

**Comment by IgorDraskovic** [comment]
Right, you mean placed it in ngOnInit or the component's constructor?  The problem with this approach is that I cannot get a reference to the specific row that I am expanding.  

Specifically I tried this:

```
           this.gridOptions = {
               getRowClass: (params) => {
                 if (params.node.expanded) {
                         return 'my-class';
                 }
             }
          }
```
This did not work as expected in part because the `params.node` which points to rowNode does not seem to have the attribute `.expanded`

**Comment by catahoc** [comment]
Hi, if node.expanded is undefined, this means its not expandable, thus
definetely not expanded)

17 нояб. 2017 г. 5:00 PM пользователь "IgorDraskovic" <
notifications@github.com> написал:
