### ISSUE TITLE
Ag grid disabling cells using columns configuration

### ISSUE THREAD

**Issue by nicolae536** [ag-grid/ag-grid#2065]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Right now ag-grid does not support disabling cells but supports disabling an entire column.
**Expected behavior**

I would like to have a programatic api so I can decide which cells should be disabled.
For exemple to define a data mapping for each column to set disabled/enabled on specific cells for example in my case I would like to define in the column header a specific property which is true/false in the rows and if that is false then I'm editing the grid that cell is not editable also when I'm using keyboard navigation it should not be editable.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by catahoc** [comment]
Hi, Nicolae, doesn't "editable" callback on column definition fits your requirements?? You can use it in the following way:
```
    city: ColDef = {
        headerName: 'City',
        field: 'city',
        width: 100,
        cellEditorFramework: CityEditorComponent,
        cellClassRules: params.data.isCityEditable ? 'editable-cell-class' : 'readonly-cell-class',
        cellRendererFramework: CityComponent,
        editable: params => params.data.isCityEditable
    };
```

**Comment by nicolae536** [comment]
Thanks a lot it works, does this appear in documentation ? I used it only as boolean. I cannot find the reference for this property in documentation where it states that this can be a also function.

**Comment by catahoc** [comment]
https://www.ag-grid.com/javascript-grid-column-properties/#gsc.tab=0

> editable | Set to true if this col is editable, otherwise false. Can also be a function to have different rows editable.

**Comment by nicolae536** [comment]
Great thanks a lot. I don't how I missed those lines when I was looking to disable some cells

**Comment by nicolae536** [comment]
Actually is not just my mind was in other place when I was reading it :)) also a few of my collegues didn't find it :)) thanks a lot again
