### ISSUE TITLE
ag-grid is not working in angular 4 and electron ?

### ISSUE THREAD

**Issue by kowthalganesh** [ag-grid/ag-grid#2066]
If its working please share the documentation. its not throwing any errors in console window

**Comment by makinggoodsoftware** [comment]
I am afraid we don't have any examples but we have customers using it, so we believe it would be possible to work.

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
