### ISSUE TITLE
colDef.pivotKeys are converted to String datatype

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#2067]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
pivotKeys are always an array of string values, even when the data type is numeric. In the Plnkr below, the numeric Year colDef is converted to string (see the console log)...

**Expected behavior**
Data type of pivotKeys should remain the same as the type in the original data

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/phwe1VErUWobHyGc7ugt?p=preview

**ag-Grid version:** 14.2.0

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as designed, so this would be a feature request and right now we are only taking feature requests/support that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
