### ISSUE TITLE
Making infinity scrolling smoother

### ISSUE THREAD

**Issue by Tziv** [ag-grid/ag-grid#2068]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request
```
**Current behavior**
When using the infinite scrolling row model, every time a user scrolls down to the bottom of the list he has to wait until the new data is fetched.

**Expected behavior**
A much more User Experience oriented solution would be for me, the developer, to have a configurable parameter which represents some % of the grid's vertical scroll bar, and the grid would call getRows() if the vertical scroll bar has reached that % (default would the current situation which is 100%).

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/?p=preview

**What is the motivation / use case for changing the behavior?**
Letting the grid fetch more rows before the user scrolls to the bottom of the grid would make ag-grid a much nicer User Experience.

**Please tell us about your environment:**
ReactJS (React 16)

* **ag-Grid version:** 14.2.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
This has been already raised in the enterprise row model and is tracked by AG-1175

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
