### ISSUE TITLE
HeaderName with Points "." removes content of Column.

### ISSUE THREAD

**Issue by juanmi108** [ag-grid/ag-grid#2069]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Content of whole column missing.

**Expected behavior**
Content of column is not missing. 

**Minimal reproduction of the problem with instructions**
Set the header name of a column to anything contining a point. eg. "Name.With.Point"

**What is the motivation / use case for changing the behavior?**
Not restricting the use of point for users

**Please tell us about your environment:**
Running on Angular 1. Happens in All Browsers

* **ag-Grid version:** 14.2.0

* **Browser:** Chrome, FF, IE, EDGE

* **Language:** [ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Can't reproduce..

https://plnkr.co/edit/MS8RZSuaaySMrMqA8f9u?p=preview

**Comment by juanmi108** [comment]
Im sorry, I meant the 'field' of the Column definition and not the 'headerName' :)

**Comment by juanmi108** [comment]
e.g  if my source data looks like this: `{'field.with.point': 'value'} ` then Column 'field.with.point' wont be filled in the grid.

**Comment by juanmi108** [comment]
@makinggoodsoftware I modified your plunker to really felect the issue. 
https://plnkr.co/edit/EJOfQeFmPMkn1Wbq7PC5?p=preview

**Comment by juanmi108** [comment]
@SidaouiBilel I was made aware of a gridOptions property in #2514
