### ISSUE TITLE
How to extract the pivot table data in ag-Grid-Angular

### ISSUE THREAD

**Issue by nareshkore** [ag-grid/ag-grid#2070]
Hi,

Can anyone please suggest me, what method or class to be used to extract the pivot table data (transformed data like 2 or 3 dimensions in columns) which I will be using to plot the chart.

I have been using latest version of agGrid and angular4.

Please refer below plunk for more info.

https://plnkr.co/edit/bI2sZVmZ5AZuK0fd1rcX?p=preview

Please share any info related to that.

Thanks in advance,
Naresh

**Comment by makinggoodsoftware** [comment]
Hi this is a support request and right now we are only taking feature requests/support that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
