### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Ederagp** [ag-grid/ag-grid#2074]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Minimal reproduction of the problem with instructions**
1 .- install ag-grid `bower install ag-grid`
2.- Add scrip in the index.html file `<script src="bower_components/ag-grid/main.js"></script>`
3.- Add 'agGrid' to angular module `angular
        .module('reporteador1App', [
            'ngStorage',
            'ngCacheBuster',
            'ngFileUpload',
            'ui.bootstrap',
            'angular-loading-bar',
            'agGrid'
        ]);`
4.- Add in file html the directive with ` <div id="myGrid" ag-grid="vm.gridOptions" style="height: 100%;" class="ag-theme-fresh"></div>`
5.- Add in controller.js 
```
vm.gridOptions = {
            columnDefs : [
                {headerName: "Make", field: "make"},
                {headerName: "Model", field: "model"},
                {headerName: "Price", field: "price"}
            ],
            rowData : [
                {make: "Toyota", model: "Celica", price: 35000},
                {make: "Ford", model: "Mondeo", price: 32000},
                {make: "Porsche", model: "Boxter", price: 72000}
            ]
        }; 
```
6.- when running the application shows me this error in the browser console
![captura de pantalla 2017-11-22 a las 4 38 52 p m](https://user-images.githubusercontent.com/23706190/33154318-2c6f0f12-cfad-11e7-93f6-a3db57bc1f3c.png)

### **I have also added the scripts that are in the dist folder and the second error is sent by the jquery.js**
**Please tell us about your environment:**
Mac OS El capitan

* **ag-Grid version:** 14.2.0
ag-grid 14.2.0

* **Browser:**
chrome 61

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular 1.5.8

**Comment by makinggoodsoftware** [comment]
Hi,

This is a support query, and right now we are only taking support requests that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
