### ISSUE TITLE
Missing export in d.ts?

### ISSUE THREAD

**Issue by gama410** [ag-grid/ag-grid#2075]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
in typescript, a transpile error is thrown on the following line:
_import {RowDataTransaction} from 'ag-grid';_

**Expected behavior**
I would expect to be able to import this interface. It seems this interface is not exported in _main.d.ts_ whereas _RowNodeTransaction_ is exported.

**Minimal reproduction of the problem with instructions**
just add the mentioned import to a typescript file.

**What is the motivation / use case for changing the behavior?**
Avoid a typescript error

**Please tell us about your environment:**
VSCode, Windows 10

* **ag-Grid version:** X.X.X
14.2

* **Browser:**
irrelevant

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.6.1

**Comment by gama410** [comment]
@ceolter any idea?

**Comment by makinggoodsoftware** [comment]
Hi,

The way we see this file is as a minimum entry point of dependencies that we export, we actively try to export as less as possible.

If you want to use our internals at your own risk, then you can, but you will have a different sintax for the import ... 

ie 'dist/lib/...'

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by gama410** [comment]
Thank you for your feedback, @makinggoodsoftware . Although I don't really understand why this particular class (_RowDataTransaction_) is not exported. If I want to use the transaction update method (_updateRowData_), I have to pass a transaction object so I'd like to make sure it complies with _RowDataTransaction_'s interface.

**Comment by gama410** [comment]
I'm glad to see you ended up exporting this file!
