### ISSUE TITLE
ag-grid 2nd page rows data gets truncated with infinite rowModel (pagination) with dynamic row height

### ISSUE THREAD

**Issue by jkjha** [ag-grid/ag-grid#2077]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
I am trying to use pagination along with "infinite" rowModel. Along with this, I am trying to use dynamic rowHeight for each row. I know officially this is not supported (Having dynamic rowHeight with infinite row Model). So I have tried to create my own solution to have this. It works very fine on first page, but on 2nd page it creates problem. The initial few rows gets truncated and doesn't show on the grid, and instead it shows blank spaces at the bottom. For exa, if 1st page has data from 1-50, in 2nd page, data from 51-62 gets truncated and it shows data from 63-100 and instead after 100th element, it shows blank spaces. May be there are some miscalculation happening.

**Current behavior**
on 2nd page, partial rows are shown. Exa. rows from 51-62 gets truncated.

**Expected behavior**
It should show all the rows, as the rowTop value for each row is calculated perfectly.

**Minimal reproduction of the problem with instructions**
```
        $scope.ag_grid_options = {
            headerHeight: 50,
            rowModelType: 'infinite',
            pagination: true,
            infiniteInitialRowCount: 1,
            paginationPageSize: 50,
            cacheBlockSize: 50,
            enableServerSideSorting: true,
            enableSorting: false,
            enableColResize: true,
            angularCompileRows: true,
            rowBuffer: 9999,
            onGridSizeChanged: function () {
                $scope.ag_grid_options.api.doLayout();
                $scope.ag_grid_options.api.sizeColumnsToFit();
            },
            getRowHeight: function (params) {
                // Some calculations
                return 20 * 5;
            },
            columnDefs: grid_column_definitions
        };
        ==Major function to set Row height and determine row position.
        $scope.setRowGridHeight = function(){
            let gridHeight = 0;
            let startIndex = $scope.ag_grid_options.api.paginationProxy.topRowIndex;
            let endIndex = $scope.ag_grid_options.api.paginationProxy.bottomRowIndex;
            console.log(startIndex+ "=====>" +endIndex);
            for(var i = startIndex; i <= endIndex; i++){
                var rowNode = $scope.ag_grid_options.api.getDisplayedRowAtIndex(i);
                var rowHeight = $scope.ag_grid_options.getRowHeight(rowNode);
                rowNode.setRowHeight(rowHeight);
                rowNode.setRowTop(gridHeight);
                gridHeight += rowHeight;
            }
            var eGridDiv = document.querySelector('#ag_grid_table');
            eGridDiv.style.height = gridHeight;
            console.log(gridHeight);
            console.log($scope.ag_grid_options);
            $scope.ag_grid_options.api.doLayout();
            $scope.ag_grid_options.api.redrawRows();
        };

         ==DataSource
            $scope.ag_grid_options.api.setDatasource(
                {
                    rowCount: null,
                    cacheOverflowSize: $scope.ag_grid_options.paginationPageSize,
                    maxConcurrentDatasourceRequests: 3,
                    maxPagesInPaginationCache: 3,
                    getRows: function (params) {
                        $scope.is_data_loading = true;
                        myService.get_list().then(
                            function (response) {
                                raw_list = response.data;
                                total = raw_list.length;
                                params.successCallback(raw_list, total);
                                $scope.setRowGridHeight(); // calling this function to set the row height.
                                $scope.is_data_loading = false;
                            },
                            function (error) {

                            }
                        );
                    }
                }
            );
```

**What is the motivation / use case for changing the behavior?**
Workaround to have dynamic row height with infinite row model

**Please tell us about your environment:**
Linux, nginx and python backend

* **ag-Grid version:** X.X.X 
Latest: 14.2.0

**Comment by makinggoodsoftware** [comment]
Hi,

As you say we don't support this. so this would be a feature request and right now we are only taking feature requests that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
