### ISSUE TITLE
Field tooltip content isn't the same as CellRender custom generated content

### ISSUE THREAD

**Issue by samih-dev** [ag-grid/ag-grid#2082]
**I'm submitting a ...**  
[x] bug report

**Current behavior**
For a field, cell tooltip text is different(stay the default value) than text generated using cellRenderer option.

**Expected behavior**
For a field, cell tooltip text and text generated using cellRenderer option should be the same, as this is what intended for the end user to see.

**Minimal reproduction of the problem with instructions**
1. Use ag-grid latest version with Angular package
2. Populate grid with mock data which has long texts
3. Add custom cellRender to a field and verify you are changing the display text, but you keep it long
4. enable tooltip for the same field on #3 
5. Resize the browser if needed and check the tooltip text --> it has a different value from cell custom display content.

**What is the motivation / use case for changing the behavior?**
Expected content from UX side.

**Please tell us about your environment:**
Windows 10, VS CODE, NPM, CLI Default Web Server

* **ag-Grid version:** 
14.2.0 , in addition to ag-grid-angular package

* **Browser:**
Chrome
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

* **Language:** all 

Attaching a zip project file, which demonstrates the issue  - just run "npm install"
[sort-app.zip](https://github.com/ag-grid/ag-grid/files/1513839/sort-app.zip)

**Comment by catahoc** [comment]
Isn't it the same issue as https://github.com/ag-grid/ag-grid/issues/1822 ?

**Comment by samih-dev** [comment]
No, it is not related to refresh, its related to tooltip content not being rendered as the cell content, using custom renderer

**Comment by makinggoodsoftware** [comment]
Hi,

The tooltip does not work in sync with the renderers since renderers can be quite complicated, if you want you can use a valueGetter, but you will be limited to text content, note that this will work for the cell and the tooltip

Thanks

**Comment by samih-dev** [comment]
@makinggoodsoftware  thanks for the replay 

How can I use the valueGetter to change the tooltip text content, I tried it but isn't working

my code snippit: 

```
.........
{
        headerName: 'Name',
        // field: 'name',
        width: 150,
        sortingOrder: ['asc', 'desc'],
        // tooltipField: 'name',
        valueGetter: (params: ValueGetterParams) => {
          return (params.getValue('name') + '#######################################');
        },
.............

```

**Comment by samih-dev** [comment]
@makinggoodsoftware hi, any updates?

**Comment by samih-dev** [comment]
Hi @makinggoodsoftware
if you don't have a time for now, please reopen
