### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by sbrice** [ag-grid/ag-grid#2085]
> ..not longer used...

https://github.com/ag-grid/ag-grid/blob/3a9cae1cca740951b31eb0e20169416a76bf6696/src/ts/gridApi.ts#L409

It seems frequent, not sure if that's a local diction https://github.com/ag-grid/ag-grid/search?utf8=%E2%9C%93&q=%22not+longer%22&type=

**Comment by makinggoodsoftware** [comment]
I think is us typing a bit funny, thanks for raising this, we will fix the code
