### ISSUE TITLE
Tree data - can't update leaf position and key at once?

### ISSUE THREAD

**Issue by marcuswhit** [ag-grid/ag-grid#2086]
**I'm submitting a ...**
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When I update both the parent and item data path on a leaf node, the node is moved, but the group column title sourced from the node data path is not refreshed.  It is refreshed when performing other grid changes that force it.

**Expected behavior**
The node would be moved, and the group column title for it would also be updated.

**Minimal reproduction of the problem with instructions**
I have a tree-data grid using `deltaRowDataMode`, and have in turn implemented `getRowNodeId` (which returns the ID column), `treeData`, and `getDataPath` (which returns the hierarchy column).

The data is of the form:
```
[
   { id: 1, hierarchy: ['UK'], description: 'abc' },
   { id: 2, hierarchy: ['UK', 'London'], description: 'def' },
   { id: 3, hierarchy: ['UK', 'York'], description: 'ghi' },
   { id: 4, hierarchy: ['USA'], description: 'jkl' },
   { id: 5, hierarchy: ['USA', 'NY'], description: 'mno' },
]
```
Using Redux, I update (immutably) row ID 3, to be:
```
{ id: 3, hierarchy: ['USA', 'LA'], description: 'ghi' },
```
The node is correctly moved in the grid under the 'USA' node, but it still reads 'York'.  If I then update a row value, the node is updated and the group value then correctly reads 'LA'.

I tried creating a Plnkr for this but it doesn't look like it supports Enterprise features.

**What is the motivation / use case for changing the behavior?**
So it works as expected

**Please tell us about your environment:**
Both Mac/Windows.

* **ag-Grid version:** 
14.2.0 enterprise (trial)

* **Browser:**
Chrome v62

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7, React, Redux

**Comment by makinggoodsoftware** [comment]
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

This is tracked by AG-1223 Check our pipeline for more information, thanks
