### ISSUE TITLE
Unexpected character(s) are being inserted when editing text in cells.

### ISSUE THREAD

**Issue by appendlp** [ag-grid/ag-grid#2087]
**Unexpected character(s) are being inserted when editing text in cells.**

This can be recreated with the sample table in here under 'Cell Editing Example':
https://www.ag-grid.com/javascript-grid-cell-editing/#gsc.tab=0

**Recreation method:**
1) Select any cell under the First Name column.
2) Press Ctrl + Z (also happens with Ctrl + Y)
3) An unknown character will be inserted

**<Environment>**
Browser:Chrome (latest version)
OS: Windows10
System language: Japanese
ag-Grid version: 14.1.0

**Comment by makinggoodsoftware** [comment]
Hi, 

In my end I enter edit mode, and ctrl+z and ctrl+y seem to be working fine

When i do it in read mode I don't get any strange characters

**Comment by appendlp** [comment]
Hello.

It appears when you press ctrl+z or ctrl+y while selecting a cell from outside edit mode (before typing anything else or pressing enter key) here. 

ctrl+z and ctrl+y works fine when inside edit mode after enter key (or direct input).


Currently I am modifying this library as a base for a certain project I am doing. 

I would like to clarify this; when I press ctrl+z/ctrl+y from read mode, it enters edit mode before inputting the character.

Is it normal behavior for this library to press ctrl+z/y from read mode supposed to enter edit mode?
