### ISSUE TITLE
Row grouping breaks adding new rows by index

### ISSUE THREAD

**Issue by charlahcodes** [ag-grid/ag-grid#2089]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Adding "rowGroup: true" to a columnDef causes new rows to always be added to the bottom of the grid, regardless of specified addIndex of api.updateRowData. 

**Expected behavior**

New rows should be added at the index specified.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/RtnhXoCMMiUnCKqBIRNM?p=preview

1. Click "Add row".  An index of '0' is specified but the row is added to the bottom.
2. Remove "rowGroup: true" from the first column definition.  Click "Add row".  The row is correctly added to index '0'.

**What is the motivation / use case for changing the behavior?**

I need to add a blank row to the top of a grid with row grouping enabled.  In previous versions this worked with api.insertItemsAtIndex, but that isn't working anymore either.

**Please tell us about your environment:**

Windows

* **ag-Grid version:** X.X.X

14.2.0 enterprise

* **Browser:**

Chrome 62

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi we don't support this right now, addIndex was meant to work without grouping or sorting or filter applied, right now we are only taking feature requests that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by charlahcodes** [comment]
I used to be able to accomplish this in version 10.0.1: [](https://plnkr.co/edit/XE9ZNyCp2tmeaNQFHOFd?p=preview ).  This is preventing me from upgrading several grids.  I did report it via Zendesk; it was given ticket number AG-1174.

**Comment by EugenMaevskiy** [comment]
@makinggoodsoftware , maybe you have some changing with this functionality? I need it a lot
