### ISSUE TITLE
AgGridColumn component, cellRendererParams parameters on change problem ! (14.2.0v)

### ISSUE THREAD

**Issue by ahmetcaglayan** [ag-grid/ag-grid#2090]
Hi ceoalter,

v14.2.0

AgGridColumn component,  When the cellRendererParams parameter is changed, no new parameter information is passed to the cellRendererFramework component.

How does the cellRendererFramework parameter change the new parameter?

![image](https://user-images.githubusercontent.com/13018803/33473130-4446bc90-d686-11e7-938d-446dd7b32ec1.png)

openDeleteButon (true) props on change false when, AgGridColumn is not passing this information.

please cellRendererParams on change parameters example create document.

this.props.openDeleteButon (false) and this.props.openEditButon (false), Although it is changed to false, it is still rendered

**Comment by makinggoodsoftware** [comment]
Hi I am afraid this is how is designed to work, the param are passed on construction of your object, and when the renderer is refreshed, so this would be a fetaure request and right now we are only taking feature requests that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
