### ISSUE TITLE
How to get current Sortvalue whether it is in descending  order or ascending order  in ag grid in angular 2(asc or desc value)?

### ISSUE THREAD

**Issue by sakhamuri92** [ag-grid/ag-grid#2091]
How to get current Sortvalue whether it is in descending  order or ascending order that is asc or desc in ag-grid in angular 2 if user clicks on the one of the header cells?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
