### ISSUE TITLE
Changing the position of sorting and filter Icons 

### ISSUE THREAD

**Issue by varun-makhija** [ag-grid/ag-grid#2093]
**I'm submitting a ...**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am trying to swap the positions of the sorting arrow up and down icons before the filter icons appears, I am not able to achieve this.

**Expected behavior**
Using CSS i should be able to achieve this, but i think ag-grid adds dynamic css when filter is applied 

**What is the motivation / use case for changing the behavior?**
I have a requirement to change the position of the filter icon after the sort icons 

* **ag-Grid version:** 5

* **Browser:**

* **Language:** [ES5]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take issues from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by saranyagarimella1** [comment]
Is this feature added in ag-grid? I am also looking for a way to change the position of filter icon

**Comment by R0rt1z2** [comment]
Is this possible today? I'm also looking for a way to change the position of the sort icon. I have checked the documentation but have not found anything revealing.
