### ISSUE TITLE
Row Grouping Complex Objects with Keys example doesn't work in frameworks

### ISSUE THREAD

**Issue by phutchin** [ag-grid/ag-grid#2094]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Viewing the React and Angular examples of https://www.ag-grid.com/javascript-grid-grouping/#example-grouping-complex-objects shows no grouping

**Expected behavior**

The table should appear the same with "raw" JavaScript as with the frameworks.

**Minimal reproduction of the problem with instructions**

https://www.ag-grid.com/javascript-grid-grouping/#gsc.tab=0

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

Have tested it on Chrome, Firefox and Edge with similar 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

This is tracked by AG-1229 Check our pipeline for more information, thanks

**Comment by JohnMasterson** [comment]
Just to confirm this was included in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
