### ISSUE TITLE
The horizontal scroll bar of the grid moves content data first, then column headers in IE and Firefox.

### ISSUE THREAD

**Issue by CindySLiu** [ag-grid/ag-grid#2095]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The horizontal scroll bar of the grid moves content data first, then column headers in IE and Firefox.

**Expected behavior**
The horizontal scroll bar of the grid moves content data and column headers at the same time like what happens in Chrome.

**Minimal reproduction of the problem with instructions**
Go to ag-grid documentation - Accessing Data - https://www.ag-grid.com/javascript-grid-accessing-data/#gsc.tab=0
Then navigate to "Example Using For-Each Methods". Move the horizontal scrollbar and observe the behavior in IE, Firefox, and Chrome.

**What is the motivation / use case for changing the behavior?**
Want to have consistent behavior through all the browsers.

* **Browser:**
IE and Firefox.

**Comment by makinggoodsoftware** [comment]
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

This is tracked by AG-939 Check our pipeline for more information, thanks

**Comment by CindySLiu** [comment]
I'm not ag-Grid Enterprise Customer.

**Comment by shubhangi-asgola** [comment]
@CindySLiu Were you able to solve this issue? I am also facing the same issue but, it's hapenning in IE only.
