### ISSUE TITLE
Feature Request: API for visible rows

### ISSUE THREAD

**Issue by britvik** [ag-grid/ag-grid#2097]
**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**
There is no API for getting first (or all) visible row/node. The closest thing is getFirstRenderedRow() but if rowBuffer is > 0 it is not accurate (returned index is not visible on screen due to virtual scroll - which is ok according to docs).

**Expected behavior**
I would like to have an API for getting first (or all) visible row/node.

**What is the motivation / use case for changing the behavior?**
I have a button which changes row heights by their content. Initially rows have 28px height and when I hit the button, some rows change to 56px or 84px etc .... or they don't change height at all. The problem is, that if I'm scrolled somewhere in the middle, the rows get shifted. I would like to retain the position of the first row.

I got it working but with a nasty workaround :(.

```
private _stretchRows() {
        const toggleStretchAndEnsureFirstRowVisible = () => {
            const first = this.gridOptions.api.getFirstRenderedRow()
            this.gridOptions.api.resetRowHeights()
            this.gridOptions.api.ensureIndexVisible(this.browse.data.entities.length - 1)
            this.gridOptions.api.ensureIndexVisible(first)
        }
        const changeBufferTo = (bufferSize: number) => {
            this.gridOptions.rowBuffer = bufferSize
            this.gridOptions.api.refreshView()
        }

        if (this.state.isRowsStretched) {
            changeBufferTo(0)
            toggleStretchAndEnsureFirstRowVisible()
        } else {
            toggleStretchAndEnsureFirstRowVisible()
            changeBufferTo(gridConfig.virtualBuffer)
        }
    }
```

* **ag-Grid version:** 11.0.0

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take issues from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by jfstephe** [comment]
@britvik @makinggoodsoftware 
FYI I've got a licensed version and this has caused me pain before. I managed to get around it by setting the rowBuffer to 0 but I can no-longer do this (and I shouldn't need to anyway!).

I've raised a ZenDesk ticket # 5540 for this linking it to this GitHub issue.

Thanks for raising! Can we re-open this please?

**Comment by argarner** [comment]
For those that are stuck [here's a solution to obtaining the visible selected rows based on the current API](https://stackoverflow.com/questions/43542110/how-to-get-filtered-rows-in-ag-grid/59658591#59658591)

**Comment by sundargoku** [comment]
Any idea if this feature would ever be supported?

> For those that are stuck [here's a solution to obtaining the visible selected rows based on the current API](https://stackoverflow.com/questions/43542110/how-to-get-filtered-rows-in-ag-grid/59658591#59658591)

The above solution doesn't account for scroll/viewport?
