### ISSUE TITLE
Change of `floatingFilter` param does not appear to grid.

### ISSUE THREAD

**Issue by katasup** [ag-grid/ag-grid#2098]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Change of `floatingFilter` param does not appear to grid. And there is no way to redraw grid with new properties.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/SrMdj2mXMiL2TbQe4HXc?p=preview

**Comment by makinggoodsoftware** [comment]
Hi,

This is not a bug, this is how the grid is intended to work and right now we are only taking feature requests that come through Zendesk (see disclaimer below)

You will have to redraw the grid if you intend this to work

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by katasup** [comment]
But there no any way to redraw the grid. How i can do this?

**Comment by makinggoodsoftware** [comment]
Hi,

Have a look at our API, I think it will be helpful

**Comment by makinggoodsoftware** [comment]
This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
