### ISSUE TITLE
[DOCS] floatingCellRendererFramework is no longer availabe

### ISSUE THREAD

**Issue by vlio20** [ag-grid/ag-grid#2099]
Hi,
It seems there is a bug in your docs (https://www.ag-grid.com/javascript-grid-cell-rendering-components/#gsc.tab=0) there is no longer `floatingCellRenderer` configuration. I think that instead users should use pinnedRowCellRenderer. Correct?

Another issue, If I have the following configuration:
```
pinnedRowCellRendererFramework: null,
cellRendererFramework: CustomCellRendererComponent,
```

It seems that the `cellRendererFramework` is also called on the pinned row. Can it be changed? (I am using Angular version of ag-grid version:
```
"ag-grid": "14.2.0",
 "ag-grid-angular": "^14.2.0",
```

**Comment by makinggoodsoftware** [comment]
Yup, that is right the feature has been renamed the correct name is pinnedRowCellRendererFramework now

Thanks

**Comment by vlio20** [comment]
why the issue is closed? shouldn't it be changed in the docs?

@makinggoodsoftware , Did you see my question:

> Another issue, If I have the following configuration:
>
>pinnedRowCellRendererFramework: null,
>cellRendererFramework: CustomCellRendererComponent,
>It seems that the cellRendererFramework is also called on the pinned row. Can it be changed? (I >am using Angular version of ag-grid version:
>
>"ag-grid": "14.2.0",
> "ag-grid-angular": "^14.2.0",
