### ISSUE TITLE
[Bug] IHeaderCompParams is not available 

### ISSUE THREAD

**Issue by vlio20** [ag-grid/ag-grid#2101]
It seems like `IHeaderCompParams` is not available (can't be imported). Here are the docs link https://www.ag-grid.com/javascript-grid-header-rendering/#gsc.tab=0

**Comment by makinggoodsoftware** [comment]
This is tracked by AG-1267 Check our pipeline https://www.ag-grid.com/ag-grid-pipeline/ for more information, thanks

**Comment by nelsonni** [comment]
I can't find AG-1267 in the ag-grid-pipeline search tool. Similarly I still see references to the IHeaderCompParams interface in the documentation [here](https://www.ag-grid.com/javascript-grid-header-rendering/#react-header-rendering). The object itself which is passed to header react component as props looks pretty close to the IHeaderParams interfaces, so I assume they are related.
