### ISSUE TITLE
Cells can be marked as dirty as they are edited

### ISSUE THREAD

**Issue by amit1702** [ag-grid/ag-grid#2102]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

As we edit the cells one after another, there is no way to distinguish the dirty cell and style them.

**Expected behavior**

There can be a flag on the dirty cells, so that we can style them separately. Or this is will be solved if the whole row is passed to the cellStyle function. 

**Minimal reproduction of the problem with instructions**

Not required.

**What is the motivation / use case for changing the behavior?**

N/A

**Please tell us about your environment:**

N/A
* **ag-Grid version:** X.X.X

14.2
yes

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your und
