### ISSUE TITLE
onSortChanged is fired before sort is applied??

### ISSUE THREAD

**Issue by amirburbea** [ag-grid/ag-grid#2103]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
```

**Current behavior**

onSortChanged event fires, but within the event, gridApi.getSortModel() returns the prior sort model as the sort hasn't applied yet.

I currently use window.setTimeout with 100ms to get the sort model.  Arbitrary timeouts like this are obviously bad.  Older versions of the grid had a onAfterSortModelChanged event that seems to be gone.

**Expected behavior**

I expect gridApi.getSortModel() to return the sort model in an event about sorting (especially because I'm using server side sort).

* **ag-Grid version:** 14.2

* **Browser:** Chrome 63

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi, this is working as designed, and right now we are only taking feature requests/support that come through Zendesk (see disclaimer below)

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months. 

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
