### ISSUE TITLE
Grid Size Auto Height Grid example doesn't work when example version Angular chosen

### ISSUE THREAD

**Issue by IceBane** [ag-grid/ag-grid#2104]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On the Auto Height Grid example when Angular is chosen the Lorem Ipsum text is not in the correct place

**Expected behavior**
It should function like the Javascript version of the example (text follows grid)

**Minimal reproduction of the problem with instructions**
I found this using Version 63.0.3239.84 (Official Build) (64-bit) 
Navigate to [https://www.ag-grid.com/javascript-grid-width-and-height](url)
Scroll down to Auto Height grid

**What is the motivation / use case for changing the behavior?**
I'm having the same problem with my Angular project...

**Please tell us about your environment:**
Angular 5

* **ag-Grid version:** X.X.X
14.2.0

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for raising this, we will make sure to fix this for our next release

Thanks

**Comment by JohnMasterson** [comment]
This was included in Version 16.

Regards, 

John
