### ISSUE TITLE
Ag-grid event to identify changed rows/Values

### ISSUE THREAD

**Issue by koolhuman** [ag-grid/ag-grid#2105]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
rowValueChanged and cellValueChanged events will trigger after every change

**Expected behavior**
I am trying to find out a solution to implement save functionality after the values in the ag-grid is changed. I have an angular2 ag-grid with almost 100 columns but only 4 columns are editable. And on click of a save button on my web page i want to post only the changed values if any by the user, to the database. Is there any event which i can use to identify changed rows in the grid? Or any other suggestion to implement such scenario?I looked at rowValueChanged and cellValueChanged event, but these event will trigger after every change? I need to get the values only after the user hits save button.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 13.3.0

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by koolhuman** [comment]
@makinggoodsoftware,  Any chances to implement this feature this year?
