### ISSUE TITLE
Prevent cellClicked event to get called, when double clicking on cell to call cellDoubleClicked event.

### ISSUE THREAD

**Issue by SWGeekPD** [ag-grid/ag-grid#2112]
If I use cellClicked and cellDoubleClicked both the events , than whenever I am doing double click on any cell, it is calling cellClicked event 2 times and than cellDoubleClicked event.

**Comment by SWGeekPD** [comment]
Hi @ceolter , I want to call cellDoubleClicked event when I double click on any cell, not the cellClicked event.
I want to use both on single click cellClicked event and on double click cellDoubleClicked event. But it is always calling to cellClicked event only.
Please help

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by kartik2014** [comment]
How about a review of this particular issue which was closed without a solution?

**Comment by havardthom** [comment]
+1

Also have this issue, triggering two `onRowClicked` events when triggering `onRowDoubleClicked` is very problematic. Should definitely be an option to make these events mutually exclusive.

**Comment by ka-ramba** [comment]
> +1
> 
> Also have this issue, triggering two `onRowClicked` events when triggering `onRowDoubleClicked` is very problematic. Should definitely be an option to make these events mutually exclusive.
Probably not. What if you want to handle clicks on editable fields ? The a/m workaround works and is a good candidate including into the official code.
