### ISSUE TITLE
Adding rows in InMemoryRowModel always refreshs whole model

### ISSUE THREAD

**Issue by AlexLnz** [ag-grid/ag-grid#2115]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Following code to add a new row:

```
this.gridOptions.api.updateRowData( { add: [ obj ] } );
```

This code is awesome slow when called many times. The reason (I guess) is the call of refreshModel( STEP_EVERYTHING ) from within InMemoryRowModel.updateRowData() each time.

**Expected behavior**
Need to be able to suppress the automatic refresh of the model.

**Minimal reproduction of the problem with instructions**
see code above.

**What is the motivation / use case for changing the behavior?**
We get about several thousands of row inserts per second. They should be inserted into the table without refresh. We've got a table refresher which refreshs the table in time intervals. The inserts itself should be plain as in former versions of ag-grid (<10.1.0)

**Please tell us about your environment:**
--

* **ag-Grid version:** X.X.X
15.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.5.0

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as designed and seems to not cause any issues in our end since we use delta updates so even though it goes through all the motions it only should update the cells that require to be changed.

I would suggest you make sure that you use delta updates

Thanks

**Comment by AlexLnz** [comment]
Hi,

With previous ag-grid version we could insert rows into the data model without touching the view. Unfortunately we find no way to do this since 10.1.0

The logic which decides if a row entry is an insert or an update is already done on our side.
We would prefer to leave the production code which already is tested and certified as it is.
