### ISSUE TITLE
Inserting row without refresh is no more possible

### ISSUE THREAD

**Issue by AlexLnz** [ag-grid/ag-grid#2116]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Formerly in ag-grid version <10.1.0 a row could be added without refreshing the grid in this way:

    let model: IRowModel = this.gridOptions.api.getModel();
    const skipRefresh = true;

    model.addItems( [ obj ], skipRefresh );

Since ag-grid 10.1.0 the addItems() method is deprecated and has been removed completely. The documentation says to use updateRowData() instead:

    this.gridOptions.api.updateRowData( { add: [ obj ] } );

Unfortunately this is **no working alternative** to addItems() because the **skipRefresh-parameter is missing**.
The problem is that updateRowData() does always refresh the grid. That drags down the performance of our grid extremely. For example a bunch of 2000 inserts delivered from a server which took 2 seconds before, now take 29 seconds.

**Expected behavior**
Provide a method to add rows to the model without refreshing each time, as it was possible before v10.1.0

* **ag-Grid version:** 15.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.5.0

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
