### ISSUE TITLE
Grid auto height  does not work for Angular and React

### ISSUE THREAD

**Issue by Efecca** [ag-grid/ag-grid#2118]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I've tried "Auto Height Grid" example from https://www.ag-grid.com/javascript-grid-width-and-height/#gsc.tab=0 for Angular and it looks like this
![image](https://user-images.githubusercontent.com/34713002/34208349-35723dc0-e59f-11e7-9d88-f7a35982907b.png)
For Angular and React a grid has the same height for all row number variants.
And then "50 Rows" is selected, "text under grid" - disappeared.
![image](https://user-images.githubusercontent.com/34713002/34208562-e8f9e35c-e59f-11e7-9bc5-b3a47aa417b7.png)

**Expected behavior**
I suppose, that  Javascript  version works fine, and this is the expected behavior: 
![image](https://user-images.githubusercontent.com/34713002/34208270-d84447ba-e59e-11e7-9158-cc75b1aaa80a.png)

**Minimal reproduction of the problem with instructions**
Open https://www.ag-grid.com/javascript-grid-width-and-height/#gsc.tab=0
Find "Auto Height Grid" example.
Try different example versions.
It's also reproducible in a new tab.

* **Browser:**
Chrome  v. 62.0.3202.94

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for reporting this, it will get fixed in the next release

Thanks

**Comment by ertle** [comment]
any news?

**Comment by lorint** [comment]
### Something that worked for me:
Try setting your container (DIV or LI or whatever you're using) to **display: table-cell**, and _perhaps_ it will properly do auto-height.

**Comment by kerberosthedemon** [comment]
This never actually got fixed btw.

**Comment by dbrody** [comment]
Any updates? Still doesn't seem to work.
