### ISSUE TITLE
date filter configuration

### ISSUE THREAD

**Issue by hoangnguyen208** [ag-grid/ag-grid#2119]
Version: 15.0.0
I use ag-grid on my Angular 4 app to display a table. In the date column, I use default date filter `agDateColumnFilter` as in the documentation. The placeholder shown in the filter input is always `mm/dd/yyyy`. Is it possible to change it to `dd/mm/yyyy`? 

I tried something like `filter: { condition: 'agDateColumnFilter', placeholder: 'dd/mm/yyyy'}` , but it did not allow to assign the filter property as object or function.  I also tried `filter: 'agDateColumnFilter: "dd/mm/yyyy"'`, but date component not found.

**Comment by makinggoodsoftware** [comment]
This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by lk77** [comment]
Hello,

is there any solution to this ?
