### ISSUE TITLE
Add columnRangeSelection: 'single' option

### ISSUE THREAD

**Issue by mattpjohnson** [ag-grid/ag-grid#2120]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Cannot limit grid range selection to a single column at a time.

**Minimal reproduction of the problem with instructions**
View the range selection demo [here](https://www.ag-grid.com/javascript-grid-range-selection/#gsc.tab=0).

**What is the motivation / use case for changing the behavior?**
Limit the user to selecting only a single column when creating a range.

* **ag-Grid version:** v15.0.0 (Enterprise)

* **Browser:** All

* **Language:** All

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
