### ISSUE TITLE
Undescriptive pipeline

### ISSUE THREAD

**Issue by catahoc** [ag-grid/ag-grid#2122]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Issues on pipeline are not informative. User just see title and no description of "what problem is solved"
![image](https://user-images.githubusercontent.com/2704650/34339928-06b0e202-e98c-11e7-9ba5-fb8297e6d0a5.png)

**Expected behavior**
Make issue details transparent for external users

**What is the motivation / use case for changing the behavior?**
I'd like to see issue details for issues which are not self-descriptive by title.

**Comment by makinggoodsoftware** [comment]
That's a very good point and something that we have taken on board already you should see on the next few days improvements in the pipeline so it conveys the meaning of the tasks better
