### ISSUE TITLE
setFilterModel() unable to apply filter to async/callback set filter

### ISSUE THREAD

**Issue by Shadrongowes** [ag-grid/ag-grid#2124]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
**setFilterModel()** is unable to filter on a column when async/callback model is used for values, shown [ here ](https://www.ag-grid.com/javascript-grid-filter-set/#example-callback-async).
**setFilterModel()** initiates callback function in **values** attribute, but does not apply filter to column. Once callback is successful, **setFilterModel()** behaves as expected.

**Expected behavior**
Unopinionated filter applied to column's set filter.

or 

**setFilterModel()** initiates _values_ callback function, on success filter model is applied.

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE* Method 1
1. Open https://embed.plnkr.co/hhgPgNM2plVpIQbB5aGj/
2. Click Apply Filter using setFilterModel() button.
3. Observe (we expect the filter _'value 1'_ to be applied)
4. Wait 5s
5. Click Apply Filter using setFilterModel() button.
6. Observe (function behaves as expected)

*STEPS TO REPRODUCE* Method 2
1. Open https://embed.plnkr.co/hhgPgNM2plVpIQbB5aGj/
2. Select Filter icon on Set filter col column
3. Wait for Set Filter to populate
4. Click Apply Filter using setFilterModel() button.
5. Observe (function behaves as expected)

Only applies filter after callback success.

**What is the motivation / use case for changing the behavior?**

We leverage ag-grid's asynchronous set filters. These provide significant speed increases and lower transmission payloads for our clients, a very valuable feature. However, we also invoke .setFilterModel in onGridReady to load cached and saved filter configurations. These two features are unable to operate in tandem. 

**Please tell us about your environment:**

Linux Red Hat 7
Spring Boot 1.3.3
npm
(Behavior is likely not system dependent)

* **ag-Grid version:** 15.0.0

* **Browser:** Google Chrome Version 61.0.3163.100 (Official Build) (32-bit) 

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked by AG-1171, we are aiming to fix this in the next one/two releases, you can check the progress in our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by Shadrongowes** [comment]
Hi @makinggoodsoftware, using the upgraded version of ag-Grid 16.0.0, it seems the same issue persists. Even though it was marked complete in the https://www.ag-grid.com/ag-grid-pipeline/
I have recreated a new plunker with the upgraded version.

https://embed.plnkr.co/213Oa6iAZVzMlddfq9CD/

**Comment by Shadrongowes** [comment]
Opened  #2212

**Comment by bbohling** [comment]
another example of `setFilterModel` not working when using `async`: https://angular-438dcc.stackblitz.io

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
Hi guys,

Let me have a look at the scenarios provided, we will let you update you as soon as possible.

Thanks for all the feedback!

**Comment by makinggoodsoftware** [comment]
#2709 Duplicate
