### ISSUE TITLE
Sorting triggered twice when suppressMovableColumns is true (mobile devices)

### ISSUE THREAD

**Issue by jvalverde18** [ag-grid/ag-grid#2125]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using sortable grid with fixed columns (suppressMovableColumns = true) on mobile device (iPad, but Google Chrome's device emulation also), touching a column's header to change sorting triggers two consecutive sort actions instead of just one sort.   This is more noticeable when using server-side data source since the two consecutive requests can be seen.

[**No Sort**] > _touch_ > [ASC & **DESC**] > _touch_ > [No Sort & **ASC**] > _touch_ > [DESC & **No Sort**]

If the same application is used in desktop the sort works as expected.

**Expected behavior**

When using the same grid on mobile devices, touching a column's header to change sorting should change sort according to the sort configuration.

[No Sort] > _touch_ > [ASC] > _touch_ > [DESC] > _touch_ > [No Sort]

**Minimal reproduction of the problem with instructions**

In order for this bug to be reproduced the following needs to happen:
- Grid columns are sortable (enableSorting: true)
- Grid columns are fixed (suppressMovableColumns = true)
- Grid is used in mobile device (or Google Chrome's device emulator)
- Touch occurs inside div.ag-header-cell-label (which usually covers almost entire header area). If you touch the borders of the header (outside div.ag-header-cell-label) the sorting works correctly.

This Plnkr illustrates the configuration: https://plnkr.co/edit/y9FkPQ3Tjz3mm8BOOG3u?p=preview

**What is the motivation / use case for changing the behavior?**

I think this is a pretty common configuration (sortable and not movable columns) for a grid, then the current behavior in mobile is different from the behavior in other environments.

On server-side data source, the two consecutive requests are definitely an issue.

**Please tell us about your environment:**

Have tested it in Windows (using Google Chrome's device emulator) and iPad.

* **ag-Grid version:** 14.1.1 and 15.0.0

* **Browser:**

"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Mobile Safari/537.36"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

**Comment by rosostolato** [comment]
I still have this bug in version v28.2.1 and I'm not sure if v29 will solve this.

**Comment by StephenCooper** [comment]
Can you provide a reproduction for this. I have not been able to reproduce the issue following the steps above.

**Comment by rosostolato** [comment]
@StephenCooper I've been trying to create a stackblitz project to repro the bug but I'm having no success. Maybe the bug only happens when you have a big amount of data and too much complexity, idk... my guess is that `click` and `touchend` events are being fired and are triggering the sort function twice, that's the reason it's touch devices related only.

**Comment by ucin** [comment]
I recently encountered the same issue after updating to v29 of Ag-Grid React, which only occurs when using the InfiniteRowModelModule. The solution was to use useMemo for the defaultColDef.

From:
```html
                       <AgGridReact
                                rowSelection="single"
                                rowModelType="infinite"
                                onGridReady={onGridReady}
                                components={gridRenderer}
                                defaultColDef={{
                                    flex: 1,
                                    resizable: true,
                                    minWidth: 60,
                                    filter: null,
                                    sortable: true,
                                    sort: null
                                }}
                                modules={[InfiniteRowModelModule]}
                                columnDefs={columnDefinitions}
                            />
```

To:

```typescript
 const defaultColDef = useMemo(() => {
        return {
            flex: 1,
            resizable: true,
            minWidth: 60,
            filter: null,
            sortable: true,
            sort: null
        }
    }, []);
```

```html
                          <AgGridReact
                                rowSelection="single"
                                rowModelType="infinite"
                                onGridReady={onGridReady}
                                components={gridRenderer}
                                defaultColDef={defaultColDef}
                                modules={[InfiniteRowModelModule]}
                                columnDefs={columnDefinitions}
                            />
```
