### ISSUE TITLE
tool panel layout breaks when column name is long

### ISSUE THREAD

**Issue by mg1075** [ag-grid/ag-grid#2126]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a column name in the tool panel is "too long", the rest of the column names in the panel get messed up in appearance.

**Expected behavior**
There should not be any disjointed appearance in the column names in the tool panel.

**Minimal reproduction of the problem with instructions**
See this plunker example.
https://plnkr.co/edit/r1FyN8hZILiuocXTX2Bw?p=preview

**What is the motivation / use case for changing the behavior?**
Appearance of tool panel in this case is not acceptable.

**Please tell us about your environment:**
See the example as described on stackoverflow and in a plunkr.
https://stackoverflow.com/questions/48031357/ag-grid-tool-panel-layout-breaks-when-column-name-is-long

https://plnkr.co/edit/r1FyN8hZILiuocXTX2Bw?p=preview

* **Browser:**
Chrome

**Comment by Shadrongowes** [comment]
Hey @mg1075, I had similar issues. Overriding the .css class for the toolpanel with width:100% or hiding overflow and making the toolbar horizontally scrollable. I think the latter was the case before v15.0.0

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked with 

AG-1367

You can check the progress of this item in our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by Waqqars987** [comment]
I am still facing this issue in the latest version of Ag Grid. How do I make the Tools Panel horizontally scrollable when the column name does not fit in the given width of the panel?

Example: https://plnkr.co/edit/qVf6C8dsjU3o6KiB?open=index.jsx&preview

**Comment by AG-Zoheil** [comment]
Hi @Waqqars987,

The original bug reported here that was breaking the layout was fixed independently of a horizontal scrollbar.

However, we do have a feature request for a horizontal scrollbar in our backlog. It can be tracked with the following reference: AG-6006. We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Kind regards,
Zoheil
