### ISSUE TITLE
Show both loading and no data overlays at the same time

### ISSUE THREAD

**Issue by namnn** [ag-grid/ag-grid#2127]
I found that only one of loading and no data overlays can be shown at a time.

My situation is that at the beginning, I have no data and a loading observable. I subscribe to that observable and manually call the grid api to setup the loading but it was later replaced by no data overlay due to the grid.

Is there a way to have both running (I can then use css on the loading overlay to hide the no data)?

Thanks in advanced.

**Comment by makinggoodsoftware** [comment]
Note that we don't offer support through github, in any case note that you can create your own layout

I have set this ticket flagged as managed by the community

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by namnn** [comment]
Thanks for the info.

I was able to work around this by calling showLoadingOverlay() inside onRowDataChanged if the loading flag is true and empty data.
