### ISSUE TITLE
ag_grid-enterprise license key encryption.

### ISSUE THREAD

**Issue by SWGeekPD** [ag-grid/ag-grid#2128]
Hi @ceolter,
I am having  ag_grid-enterprise license key. How can we encrypt it for production version.
Is there any mechanism so it should not expose.

**Comment by SWGeekPD** [comment]
Also , even If I remove the License key from LicenseManager.setLicenseKey("your key");
the contextMenu works.
What is the logic. How it works without key.

**Comment by makinggoodsoftware** [comment]
Hi,

If you are a customer, you should post in zendesk.. Do you have an account set up for this?

I can help you with that otherwise.

**Comment by SWGeekPD** [comment]
@makinggoodsoftware  Yes I am having valid developer license key. Please suggest , how can I create account.

**Comment by SWGeekPD** [comment]
@ceolter @makinggoodsoftware can some please help me on this.

**Comment by makinggoodsoftware** [comment]
Sorry for this! Let me get someone from customer experience reach out to you!

**Comment by SWGeekPD** [comment]
@makinggoodsoftware , any update, This need to get solve. Else we have to move to some other grids. If enterprise version is not at all useful, and its enterprise features are available in free version also, why should we waste our money on license of ag-grid-enterprise.

**Comment by ceolter** [comment]
For license issues, please contact accounts@ag-grid.com

However to answer the question, yes we are aware the license key will be in plain text. If someone wants to steal your license key and effectively pirate ag-Grid then there is nothing we can do to stop that.

**Comment by domcrow** [comment]
Just a thought, but why don't you provide docs / tools for developers to create an electronic signature (using an asymmetric algorithm) for each domain the ag-grid is used on. DNS is pretty hard to spoof and `window.location` properties are effectively immutable (changing them triggers a redirect to the new URL anyway). openssl could be used as the tool to create the signature for example. The [Web Crypto](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) API can be used to verify the signature.

**Comment by lakshman53** [comment]
The answer of @ceolter is rather rude

**Comment by tonix-tuft** [comment]
@domcrow Could you describe the process more in detail?
