### ISSUE TITLE
rowGroup in ColDef and Sorting of data in the grid not working as expected.

### ISSUE THREAD

**Issue by satishtatavarty** [ag-grid/ag-grid#2131]
I am using rowGroup in columnDef to group the rows of data. It is working as expected and row groups are visible. But my problem is with Sorting. 
When i sort on other columns all my groups are also changing the positions. 

I wanted group rows to be in fixed position and sort should happen only with the rows of groups. Please suggest solution for same.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi, This would work if you sort your group AND then the other columns, you can do this holding shift
