### ISSUE TITLE
ag-grid-enterprise , How to call another function from getContextMenuItems action.

### ISSUE THREAD

**Issue by SWGeekPD** [ag-grid/ag-grid#2132]
this.getContextMenuItems = function getContextMenuItems(params) {
            var result = [
                {
                    name: "Alert breakoutData",
                    action: function () {
                  // I want to call function from here.like below.
                  this.myFunction();
                    },
                }];
            return result;
        }
But it is not able to find the function, Please suggest the way to achieve this.

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for raising this, we will fix it in our next release

Thanks

**Comment by SWGeekPD** [comment]
Well I solved this issue.
 this.getContextMenuItems = () => this.myFunction(event);

 myFunction(params) {
        var result = [
            {
                name: "BreakoutData",
                action: () => {
                    this.isDrillDownReport = false;
                    this.isBreakOutData = true;
                    this.breakOutColumnDefs = [{ headerName: "Make", field: "make", width: 300 },
                    { headerName: "Model", field: "model", width: 300 },
                    { headerName: "Price", field: "price", width: 300 }];

                    this.breakOutRowData = [
                        { make: "Toyota", model: "Celica", price: 35000 },
                        { make: "Ford", model: "Mondeo", price: 32000 },
                        { make: "Porsche", model: "Boxter", price: 72000 }
                    ];
                },
                cssClasses: ["redFont", "bold"]
            },
            "separator",
            "copy",
            "export"];
        return result;
    }

**Comment by rameshdhanapal** [comment]
Thanks SWGeekPD  . you solution worked  fine
