### ISSUE TITLE
Having trouble getting 'enableImmutable' mode to work.

### ISSUE THREAD

**Issue by mm2432** [ag-grid/ag-grid#2137]
Hi, 
I read about 'enableImmutableMode' on your site here [Using React-Redux](https://www.ag-grid.com/react-more-details/#react-delta-changes). I think this is great and would love to use this. I tried following the documentation but got the error 'enableImmutableMode' is not a property of GridOptions. I am having trouble finding a working example (the example referenced in the documentation is broken [Trader Dashboard](https://www.ag-grid.com/ag-grid-react-trader-dashboard/)). I also tried searching your git repo for 'enableImmutableMode' and couldn't find anything. If you could please point me toward a working example or how I can get started using this feature that would be great! Thanks!

* **ag-Grid version:** 14.0.1
* **ag-grid-enterprise:** 14.2.0
* **ag-grid-react**: 15.0.0

**Browser:**
chrome

 **Language:** React Typescript

**Comment by mehulshah1484** [comment]
@melmanko - just wanted to check if you have more details about this property - `enableImmutableMode` or maybe it might be just a typo as pointed out here - https://github.com/ag-grid/ag-grid-docs/issues/177 ?

thanks
