### ISSUE TITLE
Improper Ag-Grid Styling

### ISSUE THREAD

**Issue by nsankaranarayanan** [ag-grid/ag-grid#2143]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am currently using ngx-admin / nebular admin template for my application.
I have integrated ag-grid and the grid works with some functionalities like sorting.
I am using the  blue theme.
My grid is not showing up anything like what is being show in the examples. 
Some of the things that don't work as expected are the following
1. The grid layout. No borders, grid lines, etc
2. Sorting doesn't have the proper arrows as shown in the example.
3. Hamburger menu in the column header doesn't show up.

I have included the necessary theme CSS files in the angular-cli.json file. Irrespective of whether I use the fresh or blue theme, I don't see any change.

**Expected behavior**
I am expecting the integrated grid to function like the examples with blue theme, grid lines, etc.

**Minimal reproduction of the problem with instructions**
The sample project works fine and I have integrated the code from the sample project and have made the customizations. Not sure how you can reproduce this.

**What is the motivation / use case for changing the behavior?**
The use case is for me to display the grid with the style and behaviour shown in the examples.

**Please tell us about your environment:**
API: ASP.Net Web API
Client-Side: Angular 4.x

* **ag-Grid version:** 12.0.x

* **Browser:**
FireFox, Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript: 2.3.4

![image](https://user-images.githubusercontent.com/5003582/34914196-5e195f34-f8c2-11e7-81b1-6f517d2c02cc.png)

**Comment by nsankaranarayanan** [comment]
Just an update. I upgraded to ag-grid 15.0.0 and nothing has changed except the icon. But it is still not looking like the blue theme.

![image](https://user-images.githubusercontent.com/5003582/34920061-9461e304-f921-11e7-8b88-5fcc18a95668.png)

**Comment by nsankaranarayanan** [comment]
Figured out the problem. This is due to a missing script file.

**Comment by sl-cool** [comment]
Hello  nsankaranarayanan ,
I am experiencing same issue while integrating ag-grid with ngx-admin. Sample ag-grid table is displayed without borders, hamburger menu icon is visible,  but when I click on it, menu shows up all distorted and on top of information from the table, so text is all jumbled up. Could you please tell me how you fixed your problem? Thanks!

**Comment by mathuranubhav** [comment]
@nsankaranarayanan How did you fix this issue? I am currently facing the same!

**Comment by nsankaranarayanan** [comment]
@sl-cool and @mathuranubhav I did the following to resolve the issue.
1. Added the missing script file.
2. Override the theme properties.
I don't have the code with me right now but I can add that when I get home.
