### ISSUE TITLE
How to hide loading text row when using enterprise model?

### ISSUE THREAD

**Issue by namnn** [ag-grid/ag-grid#2154]
Hi,

How can i hide the loading text row for enterprise model? (or things similar to infinite scrolling)

For context, I want to fake a server on client side but don't want the loading row to show up.

Thanks in advance.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-1049 | Allow loading row/column component
-- | --
