### ISSUE TITLE
pinnedBottomRowData can break enableCellChangeFlash if it changes during updates

### ISSUE THREAD

**Issue by prndP** [ag-grid/ag-grid#2159]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Updating values in a row for pinnedBottomRowData can prevent enableCellChangeFlash from showing diffs in React. 

My suspicion is that the effects of `EVENT_PINNED_ROW_DATA_CHANGED` being fired immediately after `EVENT_ROW_DATA_UPDATED` may be redrawing the grid and somehow erasing the change animation before it can be seen.

**Expected behavior**
Expected behavior is that setting enableCellChangeFlash to true will cause affected cells to flash if data is changed regardless of what is set in the pinned data.

**Minimal reproduction of the problem with instructions**

I was able to reliably reproduce the issue by cloning the basic Immutable React example and adding a generated row for pinnedBottomRowData

Demo is provided here: https://plnkr.co/edit/ga3lT8ORu3hO9EJntEvd?p=preview

In `GridComponent.jsx`, I created a method `getPinnedRow()` which returns a row which simply supplies a random value. 

If you click on "Update Prices" button, the changed price cells are not flashing as expected.

Alternatively, hardcoding the values works as expected. Within `getPinnedRow()` If you comment out line 64 and uncomment line 63 instead, then click "Update Prices", then correct flashing behavior is observed.

**What is the motivation / use case for changing the behavior?**
I generate the values in bottom pinned rows to display summary level stats about the table data

**Please tell us about your environment:**
React 16 app built in node v9.4.0, OSX. Other details in user agent below. Reproducible generally on plunkr

* **ag-Grid version:** X.X.X
15.0.0

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by prndP** [comment]
Update: I'm able to work around this bug but achieve similar functionality that I wanted by taking a different approach shown in the [alignedGrids](https://www.ag-grid.com/javascript-grid-aligned-grids/#gsc.tab=0) example and constructing the footer row as an identical but separate aligned grid. This prevents footer refresh from affecting the other table, although it does feel slightly hacky to be maintaining two sets of circularly ref'ed gridOptions

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
