### ISSUE TITLE
ag-grid free and enterprise

### ISSUE THREAD

**Issue by Liaorio** [ag-grid/ag-grid#2160]
Hi Team,

Does the ag-grid free version not support copy and paste from excel to ag-grid form?

regards,

Ao

**Comment by petyosi** [comment]
Hi, 

yes, the clipboard is an enterprise feature. Consult [the docs](https://www.ag-grid.com/documentation-main/documentation.php#gsc.tab=0) for more details, the enterprise features have red marker in the menu.
