### ISSUE TITLE
Problem with no rows overlay when using data binding

### ISSUE THREAD

**Issue by nvierge** [ag-grid/ag-grid#2161]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i reload data, i empty the rowData before showing the loading overlay and loading the data.
If i use the setRowData method, everything is fine but if i use angular data binding, the no rows overlay appears and the call to showLoadingOverlay is not taken into account.

**Expected behavior**
I think we should be able to show the loading overlay when data binding is used and data is empty.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/cEQhOq9SWTcWbM6twsOx?p=preview

If you click on the reload button, you should see the no rows overlay whereas the loading overlay is excepted.

**What is the motivation / use case for changing the behavior?**
The behavior should be consistent when using setRowData or data binding.

* **ag-Grid version:** X.X.X
v15.0.0

**Comment by rajeshnair77** [comment]
Any solution for this , i am facing same issue,

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by aviram83** [comment]
Having the same issue with react

here is a plunker for example
https://plnkr.co/edit/hAmY7QY66imYCvdViydv?p=preview

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2440 - Overlay - Allow accepting promises to setRowData and show loading overlay automatically

**Comment by mas-iota** [comment]
having the same issue, why it's still in the backlog?
