### ISSUE TITLE
Loading overlay background missing from updated material theme

### ISSUE THREAD

**Issue by aciccarello** [ag-grid/ag-grid#2162]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The default loading overlay text "Loading..." appear without the half-opaque background in the updated material theme.

**Expected behavior**

The loading overlay should half a background and possibly a box around the text

**Minimal reproduction of the problem with instructions**

Apply the updated `ag-theme-material` theme to a grid and show the loading overlay. In the below plunker you can change the theme class in index.html to compare.
https://plnkr.co/edit/xoKAblslxZCh6QuGH6MH?p=preview

**What is the motivation / use case for changing the behavior?**

The current loading screen is illegible. Additionally, the functionality should be consistent across themes.

**Please tell us about your environment:**

* **ag-Grid version:** 13-15

* **Browser:** "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

* **Language:** all

**Comment by petyosi** [comment]
Thank you for reporting that. The fix will be in the next release, you can pick the necessary styling meanwhile.
