### ISSUE TITLE
cellClass is not working if it changed more than twice.

### ISSUE THREAD

**Issue by VijayAllagi** [ag-grid/ag-grid#2163]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`      {
        headerName: "Sport",
        field: "sport",
        cellClass: function(params) {
          return params.value === "Swimming" ? "rag-green" : "rag-amber";
        }`
Example code which is there in trail code
**Expected behavior**

![image](https://user-images.githubusercontent.com/8501551/35375744-2ff8c710-01ce-11e8-8082-cb9029abe7c5.png)
**Actual Result **
![image](https://user-images.githubusercontent.com/8501551/35376373-dadea9e0-01d0-11e8-8a49-399055f64821.png)

**Minimal reproduction of the problem with instructions**

1. Select on the option for column sport and then change the text there 
For ex: https://plnkr.co/edit/4OhQjxuuW81X8xgfoW97?p=preview which is same as example.

2. Then agian revert back to Same context Swimming 

3. Change back to Swimming text . The Css Class is not working as expected. Class color is not changed 

**What is the motivation / use case for changing the behavior?**

The Cssclass is required to change the dynamic text or dropdown.
**Please tell us about your environment:**

1. Windows

* **ag-Grid version:** X.X.X

1. Angular version : 4

* **Browser:**

Chrome :Version 63.0.3239.132 (Official Build) (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by nikhilpatteri** [comment]
@VijayAllagi did you find any work-around for this issue? I'm also facing same kind of issue.. I'm not able to apply styles dynamically in a modal window, but the same class styles are being applied in another component.

**Comment by VijayAllagi** [comment]
@nikhilpatteri I used the alternative of cellStyle instead of cellClass.

**Comment by theothings** [comment]
You can use cellClassRules instead until this is fixed

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks

**Comment by jmalStorm** [comment]
Was this fixed? because I have the same issue

**Comment by zackypick** [comment]
Not fixed yet. AG have the best grid unfortunately they completely don't pay attention to their users (even the paying ones)
