### ISSUE TITLE
no rows overlay component not working

### ISSUE THREAD

**Issue by idanhen** [ag-grid/ag-grid#2164]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
documentation shows react supports creating overlay component for no rows.
following the instructions, my component never runs, and I get the default text.

**Expected behavior**
NoRowsOverlay component framework should work and render

https://stackblitz.com/edit/react-aggrid-norowsoverlay

**Please tell us about your environment:**
react: 16.2.0
ag-grid: 15.0.0
ag-grid-react: 15.0.0 

* **Browser:**
Chrome latest

* **Language:**
ES6

**Comment by kiwi1342** [comment]
Is this been fixed in the latest version? I have the same issue but I am on v 14.0.2

thanks
