### ISSUE TITLE
[pagination] paging api - jump to page

### ISSUE THREAD

**Issue by ceolter** [ag-grid/ag-grid#217]
http://www.angulargrid.com/forum/showthread.php?tid=2308

**Comment by chiptus** [comment]
:+1:

**Comment by jovana** [comment]
+1

**Comment by dcioly** [comment]
+1

**Comment by russell-miller** [comment]
+1

**Comment by joseds** [comment]
+1

**Comment by kayue** [comment]
:+1:

**Comment by inclusiv1** [comment]
+1

**Comment by reevolt** [comment]
+1

**Comment by dephiros** [comment]
+1

**Comment by Matheo13** [comment]
+1

**Comment by Matheo13** [comment]
this.pagionationController = this.grid.context.beans.paginationController.beanInstance;
      this.pagionationController.currentPage = 3;
      this.pagionationController.loadPage();

**Comment by ceolter** [comment]
well if your going to hack it, this is better:

```
  this.paginationController = gridOptions.api.paginationController;
  this.paginationController.currentPage = 3;
  this.paginationController.loadPage();
```
i still intend refactoring the pagination (similar to how i refactored the virtual pagination and introduced an API to that about two weeks back).

**Comment by Matheo13** [comment]
Thank you. It would be nice to be able to set a custom template.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-47

**Comment by Weltmeister88** [comment]
+1

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
