### ISSUE TITLE
ag-grid-angular triggers a lot of change detections on mouse move

### ISSUE THREAD

**Issue by MrCelestis** [ag-grid/ag-grid#2170]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ag-grid gridPanel subscribes to mouse events (mouseover, mouseout), which in case of using it with angular 2+ will result in triggering a lot of NgZone destabilizations (and thus app-wide change detection runs due to AppRef.tick being done after it) when moving mouse over the grid, because zone patches all events globally. This may slow down large applications.

**Expected behavior**
It would be good to opt out from these events/related features using grid options. Proper fix looks too hard to be considered.

**Minimal reproduction of the problem with instructions**
Add ngZone.onUnstable handler in angular 2+ app and add logging. Move mouse across the grid. Notice that this method is called a lot of times.

**What is the motivation / use case for changing the behavior?**
Large angular 2+ apps may suffer performance issues when user just moves mouse over the grid.
As far as I understand it may be hard or even impossible to add workarounds for NgZone in core code (like adding NgZone.runOutsideAngular), so it would be good to at least have an option to disable these features (like setting hover css class, which is likely dependent on these events) using "suppressXXX" grid options.

**Please tell us about your environment:**
angular 5

* **ag-Grid version:** 15.0.0

* **Browser:**
any

* **Language:** all (using angular 2+)

**Comment by MrCelestis** [comment]
wrong area. found duplicate issue

**Comment by randdusing** [comment]
Where's the duplicate issue?

**Comment by MrCelestis** [comment]
> Where's the duplicate issue?

@randdusing, here it is: https://github.com/ag-grid/ag-grid-angular/issues/185

**Comment by giniedp** [comment]
this issue should not be closed, because the duplicate issue ag-grid/ag-grid-angular#185 is in an already deprecated repository. 

Our team faced the same issue. Luckily we have a custom ag-grid-angular binding which we can control. We changed it so ag-grid runs completely outside of the angular zone, but custom event listeners are still sent back to the angular zone.

I sketched an example on stackblitz
https://stackblitz.com/edit/issue-ag-grid-change-detection

This is with ag-grid Version 19. Implementation feels hacky, since some places have to be monkeypatched. If there is interest, i can improve the implementation and port it to recent ag-grid version.

**Comment by Yaowenjie** [comment]
any news on this issue?

**Comment by giniedp** [comment]
@Yaowenjie issue #185 has been closed with this last comment on it

> This issue has now been fixed. Please upgrade to at least version 22.

unfortunately they also disabled the issue section.

They fixed it partially. MouseMove does not trigger a change detection. However, scrolling and clicking still does. I have updated my example

https://stackblitz.com/edit/issue-ag-grid-change-detection

**Comment by Yaowenjie** [comment]
@giniedp Thanks for your info! That kind of solved our confusion.

**Comment by neozl24** [comment]
@giniedp  Hi, do you know which commit partially fix this problem - MouseMove trigger a change detection?

**Comment by giniedp** [comment]
@neozl24 no, i do not

**Comment by neozl24** [comment]
@giniedp  I found there is a pull request in ag-grid to solve this -- "AG-2465 Minimize the the amount of change detection events fired using Angular 2".

Among this AG-2465, I think there are several important commits:

- [ee1b58b](https://github.com/ag-grid/ag-grid/commit/ee1b58b)
- [67ce309](https://github.com/ag-grid/ag-grid/commit/67ce309)
- [ae255c6](https://github.com/ag-grid/ag-grid/commit/ae255c6)

During [67ce309](https://github.com/ag-grid/ag-grid/commit/67ce309), there is comment in file _packages/ag-grid-community/src/ts/interfaces/IFrameworkOverrides.ts_ to explain their idea:
`export interface IFrameworkOverrides {

    /** Because Angular 2+ uses Zones, you should not use setTimeout(). So to get around this, we allow the framework
     * to specify how to execute setTimeout. The default is to just call the browser setTimeout(). */
    setTimeout(action: any, timeout?: any): void;

    /** Again because Angular uses Zones, we allow adding some events outside of Zone JS so that we do not kick off
     * the Angular change detection. We do this for some events ONLY, and not all events, just events that get fired
     * a lot (eg mouse move), but we need to make sure in ag-Grid that we do NOT call any grid callbacks while processing
     * these events, as we will be outside of ZoneJS and hence Angular2 Change Detection won't work. However it's fine
     * for our code to result in ag-Grid events (and Angular application action on these) as these go through
     * Event Emitter's. */
    addEventListenerOutsizeZoneJS(element: HTMLElement, type: string, listener: EventListenerOrEventListenerObject): void;

}`

**Comment by shlomishe** [comment]
> > Where's the duplicate issue?
> 
> @randdusing, here it is: https://github.com/ag-grid/ag-grid-angular/issues/185

this link is unavailable

**Comment by shlomishe** [comment]
Does anybody know how to fix the issue?

**Comment by giniedp** [comment]
@shlomishe as far as i know, there is no further fix from ag-grid. We use a custom ag-grid angular integration successfully for years now which is essentially based on https://stackblitz.com/edit/issue-ag-grid-change-detection
