### ISSUE TITLE
Header checkbox not display with infinite scrolling

### ISSUE THREAD

**Issue by ltduc** [ag-grid/ag-grid#2171]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I use angular 5, i set grid-infinite-scrolling follow link https://www.ag-grid.com/javascript-grid-infinite-scrolling and i set header checkbox: 
headerCheckboxSelection: true
headerCheckboxSelectionFilteredOnly
checkboxSelection

Error: Header checkbox not display

**Expected behavior**
Header checkbox will display, working

**Mini Demo**
https://plnkr.co/edit/sIxD9UiupxLQupsQbrVO?p=preview

* **ag-Grid version:** 15.0.0

* **Language:** [all ]

**Comment by flmg** [comment]
@ltduc As you should see in your console, is is not supported:

https://github.com/ag-grid/ag-grid/blob/627793f950380b0513cdfe32a08f6be85e020088/src/ts/headerRendering/header/selectAllFeature.ts#L171

I use a custom header component in order to render the checkbox and manage the logic there.

**Comment by ltduc** [comment]
Thanks!

**Comment by EugeneRen** [comment]
> **I'm submitting a ...** (check one with "x")
> 
> ```
> [x] bug report => search github for a similar issue or PR before submitting
> [ ] feature request
> [ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
> ```
> 
> **Current behavior**
> I use angular 5, i set grid-infinite-scrolling follow link https://www.ag-grid.com/javascript-grid-infinite-scrolling and i set header checkbox:
> headerCheckboxSelection: true
> headerCheckboxSelectionFilteredOnly
> checkboxSelection
> 
> Error: Header checkbox not display
> 
> **Expected behavior**
> Header checkbox will display, working
> 
> **Mini Demo**
> https://plnkr.co/edit/sIxD9UiupxLQupsQbrVO?p=preview
> 
> * **ag-Grid version:** 15.0.0
> * **Language:** [all ]

hello

**Comment by ryzhak-a** [comment]
> @ltduc As you should see in your console, is not supported:
> 
> https://github.com/ag-grid/ag-grid/blob/627793f950380b0513cdfe32a08f6be85e020088/src/ts/headerRendering/header/selectAllFeature.ts#L171
> 
> I use a custom header component in order to render the checkbox and manage the logic there.

Could you please, share some examples of how you managed that?

**Comment by shahin1993123** [comment]
@ryzhak-a could you please provide example of custom header check box selection ?

**Comment by ryzhak-a** [comment]
> @ryzhak-a, could you please provide an example of custom header check box selection?

@shahin1993123 I am using Vue.js with TS

`MyHeaderCheckbox`
```
export default Vue.extend({
  components: {
    MyCustomCheckbox,
  },
  computed: {
    isChecked() {
      return this.params.isChecked();
    },
    hasIndeterminateState() {
      return this.params.hasIndeterminateState();
    },
    isLoading() {
      return this.params.isLoading();
    },
  },
  methods: {
    change(event) {
      this.params.onHeaderChecked(event);
    },
  },
  template: `
    <MyCustomCheckbox 
      :inputValue="isChecked"
      :indeterminate="hasIndeterminateState"
      :disabled="isLoading"
      @change="change"
    />
  `,
});
```

`Component with AgGrid table`

```
import MyHeaderCheckbox from '.../...'
import { AgGrid } from 'ag-grid-vue'

export default Vue.extend({
  data(): {
    return {
      frameworkComponents: {
        headerCheckboxComponent: MyHeaderCheckbox
      },
      columnCheckbox: {
         headerName: ' ',
         type: 'string',
         field: 'select',
         headerComponent: 'headerCheckboxComponent',
         headerComponentParams: {}
      },
      isLoading: false
    }
  },
  computed: {
    hasIndeterminateState() {
     // your logic here
    }
  },
  methods: {
    setupColumns() {
      this.columnCheckbox.headerComponentParams = {
        hasIndeterminateState: () => this.hasIndeterminateState,
        isLoading: () => this.isLoading
      }
    }
  },
  beforeMount() {
    this.setupColumns()
  },
  render(): {
    <AgGridVue frameworkComponents={this.frameworkComponents} />
  }
})
```

**Comment by parkhiCareCru** [comment]
Can we have an example to what the solution should look like with react and custom header component.
Thanks!
