### ISSUE TITLE
Example resource (stocks.json) for grids is missing or no longer valid

### ISSUE THREAD

**Issue by sonman1** [ag-grid/ag-grid#2173]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Service used in examples for Angular RxJS (and other examples) is missing. This is also affecting the example posted on the main website: https://www.ag-grid.com/example-angular-rxjs/

Service missing: https://rawgit.com/ag-grid/ag-grid-docs/master/src/stocks.json

**Expected behavior**
Link to example services should be valid.

**Minimal reproduction of the problem with instructions**
Screen shot

![image](https://user-images.githubusercontent.com/23555393/35511155-7a95b6da-04c0-11e8-9631-366e34b26024.png)

**Comment by petyosi** [comment]
👍 Thank you, addressed that. Rawgit seems to be caching the 404, but I guess it will restore the files soon.
