### ISSUE TITLE
Single selection in agSetColumnFilter 

### ISSUE THREAD

**Issue by nite** [ag-grid/ag-grid#2174]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
agSetColumnFilter only allows multi-select

**Expected behavior**
agSetColumnFilter provides single-select.

**Minimal reproduction of the problem with instructions**
Create an agSetColumnFilter with any of the simple examples in docs - there is no option for single-select on the set for filtering.

**What is the motivation / use case for changing the behavior?**
Our system only provides for single options in filtering in some cases.

**Please tell us about your environment:**
Any environment, but for reference - node 9. 

* **ag-Grid version:** 15.x
(Note separate issue issue with 16.x & typescript)

* **Browser:**
Any, but for reference: Chrome

* **Language:** TypeScript 2.6.1

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
