### ISSUE TITLE
Paginated/Infinite data request should be in terms of block number/size instead of start/end index.

### ISSUE THREAD

**Issue by UselessPickles** [ag-grid/ag-grid#2177]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a grid in paginated or infinite scrolling modes, the data source requests data in terms of a start index and end index.

**Expected behavior**

The data sources for paginated and infinitely scrolling grids should request data in terms of page number/size instead of start/end index to guarantee that it is safe to use with APIs that work in terms of page number/size. 

Anyone that needs to work with an API or other data source that works in terms of start/end indexes can easily calculate the start/edn index from this information.

For backwards compatibility, ag-grid could continue calculating and providing the start/end indexes, but clarify in documentation that it is for convenience and always guaranteed to be match the corresponding page number/size.

**What is the motivation / use case for changing the behavior?**
Most paginated data APIs require data to be requested in terms of page/block number and size, limiting its usage to requesting complete "pages" aligned at "page boundaries".

The current design of ag-grid in terms of start/end index implies that the grid *may* request data that does not neatly align with a complete page at a page boundary. The start/end index can be converted to a page number/size, but only if one *assumes* that the start/end index will always be perfectly aligned.

As far as I can tell, the current implementation of ag-grid *does* always request neatly aligned pages/blocks that can reliably be converted to a page size/number for API requests, but the design currently leaves open the possibility that a future update to ag-grid could implement some kind of optimization that requests partial or misaligned chunks of rows. If this ever happens, then all data source implementations that converted the start/end index to a page number/size will be broken, and it will be impossible to use ag-grid with APIs that work in terms of page number/size.

Requesting data in terms of page number/size will solidify a guarantee that ag-grid may safely be used with an API that provides data in terms of page number/size.

**Please tell us about your environment:**
Irrelevant

* **ag-Grid version:** 16.0.1

* **Browser:**
Irrelevant

* **Language:** Irrelevant

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
