### ISSUE TITLE
expandAll() function for Tree-Data

### ISSUE THREAD

**Issue by hitesh153** [ag-grid/ag-grid#2179]
Hello, I'm trying to implement ag-grid tree-data functionality and have secured the required licenses for same. I needed to have something like a expandAll() and collapseAll() functionalit for the same. Any heads-up for the same.
Thank you in advance

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
Enterprise Row Model | AG-1019 | All expand all and select all on Infinite and Server Side row models
-- | -- | --

**Comment by DominicTobias** [comment]
Hi, was this added? I can't see it in the backlog but equally see nothing in the docs about it - https://www.ag-grid.com/javascript-grid-tree-data/

**Comment by DominicTobias** [comment]
Nevermind can do it like this:

```js
onExpandAllClick = () => this.gridApi.forEachNode(node => node.setExpanded(true))

onCollapseAllClick = () => this.gridApi.forEachNode(node => node.setExpanded(false))
```

**Comment by ludeveloper** [comment]
Hi this was closed but doesn't solve the slowness on the client side. Imagine that too many data rows are loaded on the grid. Running through all the node and expend/collapse each of the node one by one is too old method, and need a easy way just like gridApi.expandAll() and gridApicollapseAll() methods of group.

**Comment by StephenCooper** [comment]
> Hi this was closed but doesn't solve the slowness on the client side. Imagine that too many data rows are loaded on the grid. Running through all the node and expend/collapse each of the node one by one is too old method, and need a easy way just like gridApi.expandAll() and gridApicollapseAll() methods of group.

The expand / collapse all functions work for tree data too as can be seen in this [example](https://plnkr.co/edit/41uNs5ETJn4EloVq?open=main.ts).
