### ISSUE TITLE
Feature Request: User Is Allowed to Control Height of a Row

### ISSUE THREAD

**Issue by zpappa** [ag-grid/ag-grid#2183]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
User is unable to control the height of a row using a mouse.

**Expected behavior**
User is able to use a mouse to dynamically change the height of a row.

**Description**
The user should be able to control the height of all rows. There should be bindings to control whether a specific row should be allowed to be resized, as well as whether or not the header rows can be changed.

Would be very helpful to have this feature as well as a built in event for when the user performs a height change on a row.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
