### ISSUE TITLE
[AngularJS] Cells not correctly compiled/rendered when using angularCompileRows and cellRenderer components

### ISSUE THREAD

**Issue by IgorAufricht** [ag-grid/ag-grid#2184]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using AngularJS compilation (with `angularCompileRows` active), sometimes the rows are not correctly rendered.

**Expected behavior**

The rows should be correctly rendered.

**Minimal reproduction of the problem with instructions**

Here's a plunker that shows the behaviour:
https://plnkr.co/edit/quBgQK17Ra4GcycuPUjs

Steps to reproduce:
* load the plunker (I tested in Chrome 63 on Windows 10)
* open the console
* run the plunker
* scroll the table (for me it is the easiest to reproduce when scrolling by dragging the scrollbar know)

Here's a screenshot showcasing the behaviour (notice the rows with no visible values and the order of the console logs):
![ag-grid-angularjs-late-rendering](https://user-images.githubusercontent.com/13379857/35740357-d5f61c96-0834-11e8-95a5-c79fc9aa70b9.png)

After some investigating, I found out that the $digest cycle (that is supposed to be called after the rows are rendered) is sometimes called before some cells are compiled with angular. In other words, the last $digest cycle is executed before the `init()` function of some cellRenderer components is called (and thus also before the angular compilation of said cells), which results in those cells not rendered correctly (the angular compilation is done, but the $digest cycle was not executed afterwards).

A workaround for this issue is to trigger $digest cycle after the compilation of the cells. For example adding the following code at the end of the `init()` method seems to help:
```
setTimeout(function () {
  params.$scope.$digest();
}, 0);
```
But this has a potentially negative effect on the performance.

**What is the motivation / use case for changing the behavior?**

The current behaviour makes it harder to use AngularJS compilation with ag-grid.

**Please tell us about your environment:**

Windows 10

* **ag-Grid version:** ag-grid 16.0.1 (if this would help - we just recently upgraded from 9.0.x, it was not an issue with that version)

* **Browser:** I was able to reproduce the issue in the following browsers:
  * Microsoft Edge (easy to reproduce): `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"`
  * Chrome 63 (easy to reproduce): `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"`
  * Firefox 57 (hard to reproduce): `"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"`

* **Language:** ES5

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
