### ISSUE TITLE
Equals column number filter does not cast strings to numbers

### ISSUE THREAD

**Issue by benschenker** [ag-grid/ag-grid#2185]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

For the number column filter, the equals option will not match numbers that are encoded as strings
**Expected behavior**

If my data contains a row with the string `"23"` and I filter for that column to `equal` `23`, it should match my column (as it does already with `greater than` etc)
**Minimal reproduction of the problem with instructions**

* https://plnkr.co/edit/WsbiDOvJa99UnphVKR5z?p=preview
* try to filter the age column for `equals` `23`
* only one row that contains 23 will show up
* If you try `greater than` `22` both will show up though

**What is the motivation / use case for changing the behavior?**

The functionality is inconsistent with regards to numbers that are encoded as strings

**Please tell us about your environment:**

OSX
* **ag-Grid version:** 16.0.1

* **Browser:**

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36`
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Hi,

Closing as answered in our official customer support system.

thanks
