### ISSUE TITLE
Circular dependency can cause issues at runtime

### ISSUE THREAD

**Issue by waterfoul** [ag-grid/ag-grid#2186]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
checkboxSelectionComponent.js:13 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (checkboxSelectionComponent.js:13)
    at checkboxSelectionComponent.js:38
    at Object.<anonymous> (checkboxSelectionComponent.js:37)
    at __webpack_require__ (bootstrap 85b92d09f5cd16601963:19)
    at Object.<anonymous> (cellComp.js:26)
    at __webpack_require__ (bootstrap 85b92d09f5cd16601963:19)
    at Object.<anonymous> (mouseEventService.js:22)
    at __webpack_require__ (bootstrap 85b92d09f5cd16601963:19)
    at Object.<anonymous> (gridPanel.js:45)
    at __webpack_require__ (bootstrap 85b92d09f5cd16601963:19)
    at Object.<anonymous> (rowRenderer.js:33)
    at __webpack_require__ (bootstrap 85b92d09f5cd16601963:19)
    at Object.<anonymous> (autoWidthCalculator.js:18)
    at __webpack_require__ (bootstrap 85b92d09f5cd16601963:19)
    at Object.<anonymous> (columnController.js:28)
__extends @ checkboxSelectionComponent.js:13
(anonymous) @ checkboxSelectionComponent.js:38
(anonymous) @ checkboxSelectionComponent.js:37
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ cellComp.js:26
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ mouseEventService.js:22
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ gridPanel.js:45
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ rowRenderer.js:33
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ autoWidthCalculator.js:18
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ columnController.js:28
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ gridSerializer.js:19
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ csvCreator.js:29
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ gridApi.js:18
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ gridOptionsWrapper.js:24
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ logger.js:21
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ eventService.js:21
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ beanStub.js:9
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ component.js:20
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ headerComp.js:28
__webpack_require__ @ bootstrap 85b92d09f5cd16601963:19
(anonymous) @ utils.ts:3
```

**Expected behavior**
No Exception

**Minimal reproduction of the problem with instructions**
Cause things to get loaded in just the wrong order. Circular deps just cause problems. The loop consists of
1. widgets/component
2. context/beanStub
3. eventService
4. logger
5. gridOptionsWrapper
6. gridApi
7. csvCreator
8. gridSerializer
9. columnController/columnController
10. rendering/autoWidthCalculator
11. rendering/rowRenderer
12. gridPanel/gridPanel
13. gridPanel/mouseEventService
14. rendering/cellComp
15. rendering/checkboxSelectionComponent
16. Back to widgets/component

**What is the motivation / use case for changing the behavior?**
Circular deps cause problems

**Please tell us about your environment:**
Windows Chrome

* **ag-Grid version:** 16.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

* **Language:** Typescript 2.7.1

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
