### ISSUE TITLE
Master Detail example - "Dynamically Specify Master Nodes" does not work

### ISSUE THREAD

**Issue by jmoore315** [ag-grid/ag-grid#2188]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The example for dynamically specifying master nodes in master-detail tables is either extremely confusing or not working. https://www.ag-grid.com/javascript-grid-master-detail/#example-dynamically-specify-master-nodes 

"The following example only shows detail rows when there are corresponding child records." and yet all rows are expandable, even those without children.

**Expected behavior**

Detail rows should only be shown when there is child data for the row.

**Minimal reproduction of the problem with instructions**

https://www.ag-grid.com/javascript-grid-master-detail/#example-dynamically-specify-master-nodes 

**What is the motivation / use case for changing the behavior?**

Docs are wrong 

**Please tell us about your environment:**

Whatever the docs site is using

* **ag-Grid version:** X.X.X
16

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

I believe this example is now fixed, please have a look and feel free to open a new ticket if you think this is still an issue.

Thanks
