### ISSUE TITLE
Confusing html-tags in code block in documentation

### ISSUE THREAD

**Issue by natashk** [ag-grid/ag-grid#2191]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

On the documentation page:
https://www.ag-grid.com/javascript-grid-date-component/
in the 2nd code block for interface IDateComp there are confusing html tags in the comment for "destroy" function:

    <span class="codeComment">// Gets called when the component is destroyed. If your custom component ne eds to do
    // any resource cleaning up, do it here.</span>
    destroy?(): void;
}

And also the word "needs" spelled as "ne eds".

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by petyosi** [comment]
Thank you, we cleaned that up.
