### ISSUE TITLE
Unexpected console.log in GridOptionsWrapper

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [ag-grid/ag-grid#2192]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Working with `columnApi.setColumnVisible()` produces an unexpected ammount of log output because the event name "" is logged to console on every call. The browser has lots of entries like this:

```
columnVisible
gridOptionsWrapper.js:585
columnVisible
gridOptionsWrapper.js:585
columnVisible
gridOptionsWrapper.js:585
columnVisible
gridOptionsWrapper.js:585
columnVisible
gridOptionsWrapper.js:585
columnVisible
gridOptionsWrapper.js:585
columnVisible
gridOptionsWrapper.js:585
columnVisible
gridOptionsWrapper.js:585
```

From gridOptionsWrapper.js:

```
    // responsible for calling the onXXX functions on gridOptions
    GridOptionsWrapper.prototype.globalEventHandler = function (eventName, event) {
        if (eventName === 'columnVisible') {
            console.log('columnVisible');
        }
        var callbackMethodName = componentUtil_1.ComponentUtil.getCallbackForEvent(eventName);
        if (typeof this.gridOptions[callbackMethodName] === 'function') {
            this.gridOptions[callbackMethodName](event);
        }
    };
```

**Expected behavior**
Same behaviour, but without the console logs.

**Please tell us about your environment:**
Windows 10, NodeJS 6.10.3

* **ag-Grid version:** 
16.0.1

* **Browser:**
Latest chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by centigrade-thomas-becker** [comment]
Current blob: https://github.com/ag-grid/ag-grid/blob/8f5196f24b303a39cd56bb5ff879f24dd448f16a/dist/lib/gridOptionsWrapper.js#L585

**Comment by petyosi** [comment]
Pushed a fix for that, will be addressed in the next release.
