### ISSUE TITLE
Selection issues because user-select: none (unprefixed) only works in Chrome (>= 62) when using ag-grid.scss

### ISSUE THREAD

**Issue by schlowmo** [ag-grid/ag-grid#2197]
**I'm submitting a ...**
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

I'm filing this bug on the ag-grid repository since the ag-grid-enterprise repository hasn't any styles included. The affected feature in my use case is the range selection, but I'm quite sure that non-enterprise features are affected too.

**Current behavior**

Range selection isn't working (exception: Chrome), since instead of selecting cells, text gets selected.

**Expected behavior**

Text selection should be supressed by css.

**Minimal reproduction of the problem with instructions**

Easiest way to reproduce (enterprise feature): 

1. Use table with status bar.
2. Try to do a range selection.

**Proposed solution**

Add prefixed versions of `user-select: none` to support all browsers again. Every occurence of `user-select: none` should be extended to

```
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
```
See https://caniuse.com/#feat=user-select-none for details.
* **ag-Grid version:** 16.0.1

* **Browser:** Every browser except Chrome ( >= 62) 

* **Language:** [SCSS]

**Comment by rmc-software** [comment]
Closing as this issue has now been fixed. Thanks.
