### ISSUE TITLE
Grid with pinned columns not propagating scroll events to the body

### ISSUE THREAD

**Issue by LucasAMello** [ag-grid/ag-grid#2200]
**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior**
Normally, when scrolling a grid with the mouse wheel, if we reach the bottom it will start scrolling the body. But if there are pinned columns (and the mouse is on non-pinned column), the grid will prevent the mouse wheel event from propagating.

**Expected behavior**
When reaching the top or bottom of the grid, the mouse wheel event should continue to scroll the body of the page.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/qmqN4yy5TXwuYD0USCRA
The first grid propagates scrolls just fine, the second one (with the pinned column) doesn't.

**What is the motivation / use case for changing the behavior?**
I have to move the mouse away from the grid for the scroll to work, which is not the default behavior.

* **ag-Grid version:** 16.0.1

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.
