### ISSUE TITLE
Add hover style to header menu.

### ISSUE THREAD

**Issue by lucklove** [ag-grid/ag-grid#2204]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```
**Current behavior**

The menu style can't be changed by my css when user hover the header menu. 
**Expected behavior**

I want use css to change the style of the header menu while mouseover.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

For example, I want to change the menu's background to red only when hovered.
```css
.myclass .ag-header-hover .ag-header-icon.ag-header-cell-menu-button {
  background: red;
}
```
However, I found there is no such ag-header-hover, when hovered, the menu style was changed by [writing dom style directly](https://github.com/ag-grid/ag-grid/blob/master/src/ts/headerRendering/header/headerComp.ts#L153).
Maybe It's better to archive this by adding/removing class names like ag-header-hover?
**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by petyosi** [comment]
Why don't you try using the `:hover` pseudoclass?

**Comment by lucklove** [comment]
:hover works
