### ISSUE TITLE
Enterprise Row Model datasource failCallback

### ISSUE THREAD

**Issue by alan-bio** [ag-grid/ag-grid#2206]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using the Enterprise Row Model, the failCallback in the datasource doesn't do anything. The loading spinner just stays spinning infinitely.

**Expected behavior**
I assume it is supposed to stop the spinner?

**Minimal reproduction of the problem with instructions**
You can see the issue happening here when I force it to call failCallback everytime in the datasource.
https://plnkr.co/edit/S7YEbrMr9hsx3MjvTuG6?p=preview

* **ag-Grid version:** X.X.X
16.0.1

**Comment by makinggoodsoftware** [comment]
Hi,

The plunker seems to not be working anymore, if you provide us a plunker that shows this in our latest version, we will have a look

Thanks!

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
Since this has been inactive for a while, going to close this thread, feel free to create a new ticket if you want to follow up.
