### ISSUE TITLE
Can't edit on "slow" double click

### ISSUE THREAD

**Issue by PranKe01** [ag-grid/ag-grid#2211]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We have a grid, whose cells shall behave like a windows folder. When we double click another action shall occur, than on a "slow" double click (2 clicks in more than 1s and less than 2s for example). Right now the cell only knows single click and double click for editing.

**Expected behavior**
When we slowly double click on a cell (for example with a timespan of 2 seconds), the cell shall be editable (like a windows folder, which opens on doubleclick and renames on slow doubleclick).

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/jj8ObQs4PkMGKVYqHaIE
Right now we can only use onCellDoubleClicked - it would be nice to have a onCellSlowDoubleClicked for the renaming, or another event in the params, which contains the information if it was single/double/slow click.

**What is the motivation / use case for changing the behavior?**
A expandable grid can behave like the windows explorer tree including renaming.

**Please tell us about your environment:**
Windows, Chrome.

* **ag-Grid version:** X.X.X
14.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
