### ISSUE TITLE
After calling sizeColumnsToFit, horizontal scrollbar jumps in along with vertical scrollbar

### ISSUE THREAD

**Issue by jeghers** [ag-grid/ag-grid#2213]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When sizeColumnsToFit is called with small or no data, the columns size fine.  But then, as bigger data is loaded and vertical scrolling kicks in, now the horizontal scrollbar is also coming in (likely because the vertical scrollbar width was not accounted for).

**Expected behavior**
Is there some way that the size-to-fit behavior could continue, at least up to the point a user manually resizes a column?

**Minimal reproduction of the problem with instructions**
1. Start with grid with no data, or small amount (1 or 2 rows)
2. Call sizeColumnsToFit()
3.  Put in more data requiring vertical scrolling

**What is the motivation / use case for changing the behavior?**
Horizontal scrollbar jumping in is ugly and looks less professional, especially when the intention was to have "size-to-fit".  Perhaps the new transparent overlayed style of scrollbar could help here?

**Please tell us about your environment:**
Windows 10, Chrome, IntelliJ, ReactJS, NodeJS/Express

* **ag-Grid version:** X.X.X
16.0.1

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"

* **Language:** JSX and ES6

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks

**Comment by marcelkooi** [comment]
Not the best solution, but had to add the following CSS:

```css
.ag-body-viewport {
  overflow-x: hidden;
}
```

**Comment by Suyashb5** [comment]
> @marcelkooi I think the issue has nothing to do with the horizintal scrollbar. So hiding it is not a proper solution. This horizontal scrollbar is appearing because of the width introduced for the horizontal scrollbar. we need to set the vertical scrollbar's overflow-y to overlay, to resolve this issue.
> 
> ```
> .ag-layout-normal > .ag-body-viewport.ag-layout-normal {
>      overflow-y: overlay;
> }
> ```
> 
> Please check my solution to remove the scrollbar on stackoverflow. https://stackoverflow.com/a/69523852/7302471

This works for me thanks @anurag1209
