### ISSUE TITLE
allow to get a style to highlight the current column (.ag-column-focus)

### ISSUE THREAD

**Issue by jare-talend** [ag-grid/ag-grid#2216]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Any class set by ag-grid on the focused column.

**Expected behavior**
I wish to get a visual on the focused column like this.
![ag-grid-column](https://user-images.githubusercontent.com/20772261/36369800-ec510a66-155c-11e8-8a6e-a20ffd78dd5c.png)

**What is the motivation / use case for changing the behavior?**
I can do it by adding some classes on the DOM when ag-grid triggers an event onCellFocused, onViewportChanged, onVirtualColumnsChanged but the method isn't a good pratice and it can be optimized if the core of ag-grid does it.

* **ag-Grid version:** X.X.X
Ag grid v16

* **Browser:**

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
