### ISSUE TITLE
Quick Filter doesn't catch every matched values

### ISSUE THREAD

**Issue by vbiarunp** [ag-grid/ag-grid#2217]
I have ag-grid with a data values and when I do quick filter for '0', some of the '0' data values are not filtered. 
Here is the demo - https://plnkr.co/edit/kXmNImib4sPTTImM0fUI?p=preview
When you enter 0 in the input field, the row which has 0 value in 'NUC' in 'Fuel Type' column in Consumption (Billion is not listed. Same for OTH in 'Fuel Type' column in Consumption (Billion 

**Current behavior**
Some of the rows which has 0 value is not displayed when quick filter done for 0 value 

**Expected behavior**
All the rows which has 0 value should be displayed when quick filter done for 0 value

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Plunker site

* **ag-Grid version:** 16.0.0

* **Browser:** All Browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2159
Quick filter misses some '0' values
