### ISSUE TITLE
How to horizontal scroll with pinned column in Ag-grid?

### ISSUE THREAD

**Issue by pzanella** [ag-grid/ag-grid#2218]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

No horizontal scroll with right pinned column, while vertical scrolling it's ok

**Expected behavior**

I want horizontal scrolling with right pinned column.

**Minimal reproduction of the problem with instructions**

    gridOptions: GridOptions = <GridOptions> {
             enableSorting: true,
             rowHeight: 48,
             columnDefs: [
                 { ...
                 },
            {
                cellRendererFramework: JMenuCell,
                width: 50,
                suppressFilter: true,
                pinned:"right"
            },
        ],
        suppressCellSelection: true,
        enableRangeSelection: true,
        floatingFilter: true,
        suppressRowClickSelection: true,
        enableColResize: true,
        enableFilter: true,
        enableServerSideFilter: true,
        enableServerSideSorting: true,
        onSortChanged: (event: SortChangedEvent) => {
            ....
        },
        onFilterChanged: (event: FilterChangedEvent) => {
            ....
        }
    }
             
**Please tell us about your environment:**

Operating system: Windows 10
IDE: Visual Studio Code version 1.20

* **ag-Grid version:** 16.0.0

* **Browser:**

Chrome version 63.0.3239.132 (64 bit)

* **Language:**
From package.json:
Angular 6.0.0-beta.1
Typescript 2.5.3

Thanks in advance!

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks

**Comment by JarvisCoder** [comment]
I still see this issue. Is there any doc that talks about enabling a horizontal scrollbar for pinned columns?

**Comment by gportela85** [comment]
@JarvisCoder The idea of pinned columns is to make them visible at all times. For that reason, the pinned containers do not have horizontal scrollbars.

**Comment by JarvisCoder** [comment]
I was wondering what happens when we have a really large dataset in which case there might be few columns we want to pin to the left. I believe what we are missing is a max-width property for pinned-left section that allows a scrollbar to appear for people with smaller screens.

**Comment by hstengard** [comment]
I experience problem that the scrollbar won't let the user scroll to the last column, when using the scrollbar. This is with a left pinned column and version 23.1.

If you scroll with the track pad with focus on a cell everything works fine.

**Comment by paragsaxena8** [comment]
Does anyone find any fix or workaround on that?

**Comment by max-phiri** [comment]
Can anyone help with a fix for this issue?
