### ISSUE TITLE
Row Clicks are firing the onDragStarted and onDragStopped events

### ISSUE THREAD

**Issue by Nkalidas** [ag-grid/ag-grid#2223]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The onDragStarted event is triggered on mouse click and onDragStopped is triggered on mouse release.
Looks like it is described as fixed in the changelog, https://www.ag-grid.com/change-log/changeLogIndex.php (AG-798) but it is not.

**Expected behavior**

Mouse events should not have any interference in the onDragStarted and onDragStopped events.

**Minimal reproduction of the problem with instructions**

        this.gridOptions.onDragStarted = function(){
            console.log('col drag started')
        }

        this.gridOptions.onColumnMoved = function() {
            console.log('column is moved')
        }

        this.gridOptions.onDragStopped = function() {
            console.log('col drag stopped')
        }

Include the above lines of code in your project and do cell clicks on the grid.

**What is the motivation / use case for changing the behavior?**

need to rearrange columns and persist the positions on the grid.

**Please tell us about your environment:** Windows 7 Professional

* **ag-Grid version:** 16.0.1

* **Browser:** Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by DavidIMcIntosh** [comment]
Read Niall's comment here:

https://www.ag-grid.com/forum/showthread.php?tid=6185&pid=20295#pid20295

Behaviour is expected - you need to filter on event.type === "headerCell".  We had same issue persisting column positions.

**Comment by ssilve1989** [comment]
Bump. As @DavidIMcIntosh pointed out, in v16, the `type` returned in dragStopped is just `dragStopped` it doesn't say anything about row,headerCell, etc.

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
