### ISSUE TITLE
Preventing row selection

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ag-grid/ag-grid#2224]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If a cellRenderer contains items that react on clicking, this event will be capture by ag-grid as well and make the row selection. This isn't always a desired behavior, for instance, cellRenderer could be a button with dropdown, that upon clicking would show a list of actions. Bringing the action dropdown shouldn't select the whole row, even if clicking anywhere else (in other columns), the row actually should be selected.  In theory, this can be achieved sometimes by a mix of event.stopImmediatePropagation, event.stopPropagation or event.preventDefault, but this is a very low level and messy approach - and even that doesn't work sometimes, if the event should be caught somewhere higher (as seems to be the case with Bootstrap 4 dropdowns). 

**Expected behavior**
Provide a way to programatically prevent next/current selection using Selection API. It could be used in this special cases, where something is clicked in cellRenderer, but user don't want this action to trigger selection.

**Minimal reproduction of the problem with instructions**
Allow for row selection in grid. Create a cellRenderer with Bootstrap 4 dropdown. Observe that, upon clicking the button, the row is actually selected (events firing, model changes, etc.). 

**What is the motivation / use case for changing the behavior?**
To provide better flexibility for selections.

**Please tell us about your environment:**
Irrelevant.

* **ag-Grid version:** 
16.0.0

* **Browser:**
Irrelevant.

* **Language:** 
Typescript 2.6 / Angular 5.2.x

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by sebastian-zarzycki-es** [comment]
In all fairness, I think this is pretty basic and common feature to have. Actually, for some might not be even considered a "feature", but actually - a bug.

**Comment by JabbyPanda** [comment]
Related task raised https://github.com/ag-grid/ag-grid/issues/1503 and the author had suggested the possible solution in forked version of ag-grid

**Comment by sebastian-zarzycki-es** [comment]
Where is the suggested solution exactly?

**Comment by JabbyPanda** [comment]
@sebastian-zarzycki-es here https://github.com/tomli/ag-grid-row-unselectable/commit/78890186045de0097f33db728f49b14a3269de28

**Comment by sebastian-zarzycki-es** [comment]
My own solution for now to prevent selection temporarily is to wrap cellrenderer into a div with special click action:

```
<div (click)="preventGridSelection()"></div>

preventGridSelection() {
    const previousValue = this.params.node.gridOptionsWrapper.gridOptions.suppressRowClickSelection;
    this.params.node.gridOptionsWrapper.gridOptions.suppressRowClickSelection = true;
    setTimeout(() => {
      this.params.node.gridOptionsWrapper.gridOptions.suppressRowClickSelection = previousValue;
    });
  }
```

**Comment by lk77** [comment]
Hello,

any news on this ?

the message of @makinggoodsoftware is irrelevant to me,
It's free but does it means that it shouldn't work like expected ?
And the paid version does not work either i'm sure, so what should we pay ?

it's pretty basic to me, if i say that a row can't be selected, then it can't be, no matter what.

**Comment by fcaballero** [comment]
I would like to bring to your attention this issue still ocurring. Unfortunately, the expected behavior of event.stopPropagation is not functioning as anticipated in this case, indicating a potential bug.

To address this matter promptly, I have already opened a ticket via the support channel. For your convenience, I've also created a [Plunker](https://plnkr.co/edit/poH0DwYG5cUtIGVP?open=index.tsx) that illustrates the issue

**Comment by AG-Zoheil** [comment]
Thanks @fcaballero, we appreciate your comment and the time you've taken to report this.

For future reference, as an enterprise user you do not need to report things on both platforms - the support portal will suffice. Your request will be dealt with via that channel.

Thanks again!

**Comment by elhamzaouiaymen** [comment]
Hello, any updates on this, this issue is occuring on the latest ag-grid version.

**Comment by aryanbhatt-clvt** [comment]
onMouseDownCapture didn't work for me but onClickCapture did, I did open a cell editor without selecting the row

```
cellRendererFramework: (params) => (
                <div
                    onClickCapture={(e) => {
                        e.stopPropagation();
                        params.api.startEditingCell({
                            rowIndex: params.rowIndex,
                            colKey: 'column_key',
                        });
                    }}
                >
                    {params.value}
                </div>
            )
```
