### ISSUE TITLE
Infinite scrolling should only call getRows when scrolling is stopped

### ISSUE THREAD

**Issue by jayrungta** [ag-grid/ag-grid#2225]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

While infinite scrolling in a long table, every uncached block I scroll through is requested by calling the getRows() function.

**Expected behavior**

Every uncached block should not call the getRows() function, the getRows() function should only be called when I stop scrolling at the desired position in the table (assuming the rows at that position have not been loaded).

**Minimal reproduction of the problem with instructions**

I think I have described how to reproduce the problem above, but if it is still unclear let me know.

**What is the motivation / use case for changing the behavior?**

To avoid sending a lot of unnecessary network requests.

**Please tell us about your environment:**

Windows 7, WebStorm IDE, running locally.

* **ag-Grid version:** Using the latest ag-grid-seed from git

* **Browser:** Chrome

* **Language:** Javascript

**Comment by jayrungta** [comment]
@makinggoodsoftware  any plans to address this?

**Comment by makinggoodsoftware** [comment]
This should have been addressed in our latest release v19
