### ISSUE TITLE
DateColumnFilter: include time

### ISSUE THREAD

**Issue by Arikael** [ag-grid/ag-grid#2233]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
the DateColumnFilter only filters by date and ignores the time portion.
this is handled in `https://github.com/ag-grid/ag-grid/blob/master/src/ts/filter/dateFilter.ts`

```
public serialize(): SerializedDateFilter {
        return {
            dateTo: Utils.serializeDateToYyyyMmDd(this.dateToComponent.getDate(), "-"),
            dateFrom: Utils.serializeDateToYyyyMmDd(this.dateFromComponent.getDate(), "-"),
            type: this.filter ? this.filter : this.defaultFilter,
            filterType: 'date'
        }
    }
```

**What is the motivation / use case for changing the behavior?**
Our customer wants to be able to filter by date and time.
For example he wants to enter `01.01.2018 15:00:00` in a text box. Providing a custom date component is no problem. This is described in the documentation but the default DateColumnFilter will strip the time out.

I can't use the standard text box because then I'd lose the date filters like GreaterThan or Range

It would be nice if a) the DateColumnFilter would include the time or b) there's seperate DateTimeColumnFilter.

The only current solution I see is to write a filter from scratch even if probably 90% of this filter would be identical to the DateColumnFilter.

**Comment by hajajamos** [comment]
Cool! Thanks!

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
Filters | AG-304 | [date filter] date filter to accept date and time
-- | -- | --

**Comment by srikant21** [comment]
Hi,
I need this feature too.
since one year it has been raised still the issue AG-304 is in parked slot.
Can you please tell when it will be completed?

**Comment by srikant21** [comment]
Hi Arikael,
I need your help.
Where should i put the above code?
Do i need to put in Ag-grid node module or some where else in our src folder??
Please help me on this??

**Comment by Arikael** [comment]
I added/imported it into our angulars `main.ts` file

**Comment by srikant21** [comment]
Hi Arikael,
Need one more help.
As per your instruction i added the code to my main.ts file.After i added i got the below issue:-
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'browserDatePicker' of undefined
TypeError: Cannot read property 'browserDatePicker' of undefined
    at DefaultDateComponent.init (dateFilter.js:174)

Then i change my filter properties agDateColumnFilter to Date/date/DateFilter/DateFloatingFilterComp and it is giving this message "Looking for component [DateFloatingFilterComp] but it wasn't found".

Do u have some plunker/stackblitz where you implement this code with full working.
Please help on this

**Comment by Arikael** [comment]
I can't remember having this error and I don't have a stackblitz or something at hand.
are you using somekind of datepicker (your error seems to indicate it)?

But if you use your own Filter Component you have to follow the steps here -> https://www.ag-grid.com/javascript-grid-floating-filter-component/#angular-floating-filters

**Comment by Arikael** [comment]
the code I provided above stopped working in v21.

We are currently investigating other ways

**Comment by khryshyn** [comment]
Hi Arikael,
Do you have a chance to take a look and find some other solution?

**Comment by KoreLewi** [comment]
> Hi,
> 
> Thank you for your email. We are aware of this issue and have a feature request in our backlog:
> 
> You can follow the status of feature requests, bugs and releases using our pipeline:
> https://www.ag-grid.com/ag-grid-pipeline/
> 
> If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact [info@ag-grid.com](mailto:info@ag-grid.com) for access. This is our primary channel for Support.
> 
> This is the reference and summary of the relevant issue:
> 
> Filters	AG-304	[date filter] date filter to accept date and time

Hi,

I've checked the https://www.ag-grid.com/ag-grid-pipeline/, but I didn't find it the AG-304  issue.  Maybe the dateTime filter will included in AG-3735-Allow custom date format to be specified when using a date filter issue?

**Comment by gama410** [comment]
It's been almost 3 years and the ticket is still in the backlog...
I didn't find any official solution to the problem from ag-grid so I suppose it won't be implemented in the near future. :(

**Comment by theredwillow** [comment]
This is an embarrassment for ag-grid. A datetime filter ought to be one of the first features to have been implemented in a library designed for working with grids. I'm commenting to increase visibility.

**Comment by gportela85** [comment]
well, the idea is that you can provide your own components and filter date and time as you like
https://plnkr.co/edit/3xR3W7dRyZHpcWx0?preview

**Comment by jharris711** [comment]
Reiterating the points of @theredwillow, @gama410, @KoreLewi, @khryshyn, @Arikael, @srikant21, @prabhat112, @hajajamos, and the others who came to this page and didn't find a satisfactory solution. I don't understand why this team is so unwilling and against implementing a feature that is ***clearly*** desired by its users. It's great that we can go through the pain and toil of creating custom components but if I see that someone is claiming their grid is the "Best JavaScript Grid in the World," I would absolutely expect that a DateTime filter comes as a default filter option for Vanilla, React, Vue, and Angular. If I wanted to do a bunch of extra work I would use React-Table or build my own. Please look into adding a DateTime Filter.

**Comment by jharris711** [comment]
If anyone is looking to add a DateTime filter to a React project, I've set up an [example here](https://stackblitz.com/edit/react-mekfhh?file=src/DTPicker.jsx) as to how you can do so. It uses [react-datetime-picker](https://github.com/wojtekmaj/react-datetime-picker) and is based on [this blog post](https://blog.ag-grid.com/next-level-cell-editing-in-ag-grid-with-crud-and-react-hooks/#date-picker) from AG-Grid's blog.

```javascript
import DateTimePicker from "react-datetime-picker";

export default forwardRef((props, ref) => {
  const [selectedDate, setSelectedDate] = useState(null);

  function handleDateChange(d) {
    if (d) {
      d = new Date(d);
      setSelectedDate(d);
    } else {
      setSelectedDate(null);
    }
  }

  // props.onDateChanged must be called after updating our component's internal state:
  useEffect(props.onDateChanged, [selectedDate]);

  // getDate and setDate are required by AG-Grid to sync ag-Grid's date 
  // filter value with that of our components:
  useImperativeHandle(ref, () => {
    return {
      getDate: () => {
        return selectedDate;
      },
      setDate: d => {
        handleDateChange(d);
      }
    };
  });

  return (
    <>
      <DateTimePicker
        onChange={handleDateChange}
        value={selectedDate}
        maxDetail="second"
        disableCalendar={true}
        disableClock={true}
      />
    </>
  );
});
```

**Comment by belfz** [comment]
Thanks for the example @jharris711 - the link to stackblitz seems to be not working (is it private?). Could you post a new link, please?

**Comment by jharris711** [comment]
@belfz Link updated!

**Comment by ldrozdowski** [comment]
Struggling without time precision on filter :(

**Comment by mansur777** [comment]
If anyone interested in datetime range picker for date filter in Ag-grid on Angular, take a look on [my implementation](https://plnkr.co/edit/Bsa33tK3mOVWOJpv?preview). It uses native datetime-local input for datetime picker.

**Comment by timesh123** [comment]
HI, has there been any progress on this fix?  I had heard one was being worked on.

**Comment by jpsla94** [comment]
Hello, any updates regarding this topic? Just want to know if this include in the version 31 of aggrid.

**Comment by DaltonMecklenburgTR** [comment]
Here's a version I got working AgGrid v25 w/ Angular. I'm sure it could be easily updated for newer versions.
```typescript
import {ChangeDetectionStrategy, ChangeDetectorRef, Component} from "@angular/core";
import {IDateAngularComp} from "ag-grid-angular";
import {IDateParams} from "ag-grid-community";

@Component({
    selector: "cc-date-time-filter",
    template: `
        <input #eInput
               class="ag-input-field-input ag-text-field-input"
               [(ngModel)]="picker"
               (ngModelChange)="onDateChanged($event)"
               type="datetime-local"
        />
    `,
    styles: [
        `
            :host {
                display: flex !important;
                flex: 1 1 auto !important;
            }
            ::ng-deep .ag-input-field-input[type=datetime-local] {
                width: 1px !important;
                flex: 1 1 auto !important;
            }
            ::ng-deep .ag-filter-body-wrapper .ag-input-field-input[type=datetime-local] {
                /* Setting a wider width breaks off-screen detection in ag-grid */
                min-width: 180px !important;
            }
        `,
    ],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DateTimeFilterComponent implements IDateAngularComp {
    picker: string;
    private date: Date;
    private params: IDateParams;

    constructor(
        private changeDetectorRef: ChangeDetectorRef,
    ) {
    }

    agInit(params: IDateParams): void {
        this.params = params;
    }

    onDateChanged(selectedDate: string) {
        this.date = selectedDate ? new Date(selectedDate) : null;
        this.params.onDateChanged();
    }

    getDate(): Date {
        return this.date ? new Date(this.date) : null;
    }

    setDate(date: Date): void {
        this.date = date || null;
        this.picker = date ? this.toLocalISOString(date) : null;
        this.changeDetectorRef.detectChanges();
    }

    private toLocalISOString(date: Date): string {
        const tzOffsetMs = date.getTimezoneOffset() * 60000;
        return new Date(date.getTime() - tzOffsetMs).toISOString().slice(0, 16);
    }
}
```

**Comment by alikleit** [comment]
hm, its 2025 - was very surprised that this is a 'feature request' not a bug or something that needs to be prioritized. since the date filter sends a 'date and time' formatted value while the time is not pickable.

we are currently on the latest version `33.2.4` and the workaround custom examples attached to the feature request are not working properly. 

Any plans for this soon?
