### ISSUE TITLE
aggrid - memeory leak when using angular compile row

### ISSUE THREAD

**Issue by OrtalLagziel** [ag-grid/ag-grid#2234]
Hi,
I am using aggrid version 2.3.1 and I have a memory leak when I set  angularcompilerow to true,
I see a reference to that problem https://github.com/ag-grid/ag-grid/issues/1234 and the solution suggested: 

RenderedRow.prototype.angular1Compile = function (element) {
	        if (this.scope) {
	            var compiledRow = this.$compile(element)(this.scope);
	            this.destroyFunctions.push(function() {
	                compiledRow.remove();
	            });
	        }
	    };
Instead of

RenderedRow.prototype.angular1Compile = function (element) {
	        if (this.scope) {
	            this.$compile(element)(this.scope);
	        }
	    };

This implementation was done for aggrid advanced version.
Can you suggest how can  I solve this issue using aggrid version 2.3.1

Thanks in advance :)

**Comment by makinggoodsoftware** [comment]
Based on 1234 closed, I am going to close this one too
