### ISSUE TITLE
v 17.0.0 adding "resetColumns" as build-in menu item causing javascript error

### ISSUE THREAD

**Issue by coopernyc** [ag-grid/ag-grid#2238]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

adding "resetColumn" Build-In Menu Item causing javascript error

TypeError: Cannot read property 'subMenu' of null
    at C:\_projects\CoreElectron\node_modules\ag-grid-enterprise\dist\lib\menu\menuItemMapper.js:33:23
    at Array.forEach (native)
    at MenuItemMapper.mapWithStockItems (C:\_projects\CoreElectron\node_modules\ag-grid-enterprise\dist\lib\menu\menuItemMapper.js:25:22)
    at EnterpriseMenu.createMainPanel (C:\_projects\CoreElectron\node_modules\ag-grid-enterprise\dist\lib\menu\enterpriseMenu.js:313:51)
    at EnterpriseMenu.createTab (C:\_projects\CoreElectron\node_modules\ag-grid-enterprise\dist\lib\menu\enterpriseMenu.js:179:39)
    at C:\_projects\CoreElectron\node_modules\ag-grid-enterprise\dist\lib\menu\enterpriseMenu.js:154:26
    at Array.map (native)
    at EnterpriseMenu.init (C:\_projects\CoreElectron\node_modules\ag-grid-enterprise\dist\lib\menu\enterpriseMenu.js:153:14)
    at C:\_projects\CoreElectron\node_modules\ag-grid\dist\lib\context\context.js:208:164
    at Array.forEach (native)
------- STACK TRACE ---------

**Expected behavior**
should work as build-in Menu Item 
[https://www.ag-grid.com/javascript-grid-column-menu/#built-in-menu-items](https://www.ag-grid.com/javascript-grid-column-menu/#built-in-menu-items)

**Minimal reproduction of the problem with instructions**
 'separator',
                'autoSizeAll',
                **'resetColumns',**
                'separator',
                'expandAll',
                'contractAll'

**What is the motivation / use case for changing the behavior?**
it was working at least in v.15

**Please tell us about your environment:**
Win, npm

* **ag-Grid version:** 17.0.0

* **Browser:**
Electron App, Chromium

* **Language:** [all | TypeScript 2.7.1 | ES6 | ES5]

**Comment by Prontsevich** [comment]
Had the same problem, and I found that there is no such menu item name in source code.  There is a switch statement with all options in menuItemMapper.ts  and menu item with text "Reset Columns" has 'destroyColumnComps' key. Try to replace 'resetColumns' with 'destroyColumnComps' :)

**Comment by jameswyse** [comment]
Thanks for the workaround @Prontsevich! I'll submit a support request so this gets fixed.

Reproduction: https://plnkr.co/edit/ope0hVLf1RXiRZJ6qk2t?p=preview

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
