### ISSUE TITLE
Type definition error in ColumnApi for v17.0.0

### ISSUE THREAD

**Issue by Teamop** [ag-grid/ag-grid#2240]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Seems in this version, add sourceEvent parameter to the api, but all the parameter is required, so when building, get error: `Expected 3 arguments, but got 2.`
For example, `setColumnVisible`, before, it was `setColumnsVisible(colKeys, visible)`, but now it's `setColumnsVisible(key: string | Column, visible: boolean, source: ColumnEventType)`, seems the third parameter should be optional.
Also this effects other APIs which also adds the sourceEvent parameter.

**Expected behavior**

build passes without adding another parameter.
**Minimal reproduction of the problem with instructions**

Just see the definition file under the dist
**What is the motivation / use case for changing the behavior?**

Affects the update to v17, but if it's intentional, should modify the document and also tag with breaking change
**Please tell us about your environment:**

* **ag-Grid version:** 17.0.0

* **Browser:**

* **Language:** TypeScript 2.6 | 2.7

**Comment by Teamop** [comment]
@petyosi Hi, could you take a  look at this issue? I think it's important.

**Comment by ceolter** [comment]
just pass in 'null' for now, the parameter only gets used when generating events, so when you listen to events you know what triggered it.

**Comment by Teamop** [comment]
thanks @ceolter , but if so, seems a breaking changes in this v17.0.0.

**Comment by DespotMagic** [comment]
Another one: "autoSizeColumns". Now he has required parameter "source"

**Comment by Amerzel** [comment]
It'd be nice if the ColumnEventType was exported. I assumed 'api' was the right type to pass in when making calls.

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
