### ISSUE TITLE
Data transfer between two grids using Drag/Drop feature

### ISSUE THREAD

**Issue by UIcode123** [ag-grid/ag-grid#2241]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**
How can I transfer data between two grids using drag/drop feature. Currently row drop is not allowed outside the grid.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:**
^16.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
* **Language:** [all | React ^16.2.0 | ES6/7 | ES5]

**Comment by AvishekNath** [comment]
I have a similar use case. How I can drag a row from one grid and drop it to another grid.  And then perform some action after that?

**Comment by PTC-JoshuaMatthews** [comment]
Any word on this? Is this feature in the roadmap?

**Comment by SimSonic** [comment]
I need this feature too. Now thinking about workaround...

**Comment by Valera1980** [comment]
I need too. I want make d&d between grids

**Comment by amirzoya** [comment]
+1

**Comment by ErosN** [comment]
Need this too!

**Comment by kevnk** [comment]
@makinggoodsoftware — Do you know if dragging rows between two separate grids is on the roadmap? Or have you seen anyone else implement this?

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-1708 | Row dragging: Allow dragging between grids
-- | --

**Comment by thanhcs** [comment]
Hi
Do we have any update on this?

**Comment by Valera1980** [comment]
No, I don't  track the issue anymore
