### ISSUE TITLE
remove "console.log(...)" from production release

### ISSUE THREAD

**Issue by desaroxx** [ag-grid/ag-grid#2242]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Console is cluttered with "console.log"s.

Like [here](https://github.com/ag-grid/ag-grid/blob/master/src/ts/gridOptionsWrapper.ts#L738):
```typescript
if (eventName==='columnVisible') {
  console.log('columnVisible');
}
```

<img width="1105" alt="screen shot 2018-03-09 at 15 20 30" src="https://user-images.githubusercontent.com/1498400/37211942-df32f52e-23ad-11e8-955e-80efbcfa8a6f.png">

**Expected behavior**
No console logs are shown, unless a debug or verbose setting is enable on the grid.

Like [here](https://github.com/ag-grid/ag-grid/blob/master/src/ts/grid.ts#L205):
```typescript
if (gridOptions.debug) {
  console.log('ag-Grid -> initialised successfully, enterprise = ' + enterprise);
}
```

**Minimal reproduction of the problem with instructions**

Execute this line: 
https://github.com/ag-grid/ag-grid/blob/master/src/ts/gridOptionsWrapper.ts#L738

**What is the motivation / use case for changing the behavior?**
Unclean, clutters console and makes development with ag grid hard.

**Please tell us about your environment:**
All envs are affected

* **ag-Grid version:** 16.0.1

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

All

**Comment by crumhorn** [comment]
Surprised this didn't get fixed from 16->17. These issue are related:

https://github.com/ag-grid/ag-grid/issues/2239
https://github.com/ag-grid/ag-grid/issues/2226
