### ISSUE TITLE
ColSpan and arrow key navigation

### ISSUE THREAD

**Issue by jkrth617** [ag-grid/ag-grid#2244]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a column is spanning columns, the arrow navigation does not work as expected.

**Expected behavior**

When i click on a cell that is spanning columns and press the right arrow key I would expect it to move to the cell next to it. Pressing left, up, and down work correctly. You can also not enter a cell that is spanning columns using the arrow keys when coming in from the right.

**Minimal reproduction of the problem with instructions**

[ColSpan documentation](https://www.ag-grid.com/javascript-grid-column-spanning/)
You can reproduce this on the colSpan documentation. Click on of the light blue cell to focus on a cell that is spanning multiple columns, ie United States in row 1. Press the right arrow key and the focus does not move to the cell next to United States. 
Likewise.
Click on a cell next to the United States and try to use the arrow key to enter the cell, ie click "gold" in row 1 and press the left arrow key. 

**What is the motivation / use case for changing the behavior?**

smoother graph navigation

**Please tell us about your environment:**

* **ag-Grid version:** 16.0.1

* **Browser:**Chrome

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by jkrth617** [comment]
also the up and down navigation does not work as expected. 
When in row 6 of the demo grid on the documentation link, the row with athlete: Alicia Coutts.
If you are in the cell in the year column and try to press up or down the navigation is blocked.

I would have expected it to focus the cell above or below it, but because that cell in the year column is being "spanned" over it does not navigate properly.

**Comment by jkrth617** [comment]
I still think this is an issue but I implemented a work around in case anyone else is stuck on this. I found that the api call "tabToPreviousCell" and "tabToNextCell" work through the colSpans when navigating horizontally. I did some simple custom grid navigation to use with this instance.

```typescript
private navigateToNextCell(params) {
	const buttonKey = params.key;
	//if (!params.nextCellDef) return null;//used for the up and down navigation when dealing with upper and lower limit
	switch(buttonKey) {
		case ArrowButtons.KeyLeft:
			this.gridOptions.api.tabToPreviousCell();
			break;
		case ArrowButtons.KeyRight:
			this.gridOptions.api.tabToNextCell();
			break;
		case ArrowButtons.KeyUp:
		case ArrowButtons.KeyDown:
			//to deal with this i used a combination of the api call "getDisplayedRowAtIndex" and the columnApi "getColumn" to determine where to navigate to.
			//this had logic specific to my code base so i didnt think it would be too helpful to post
		default:
			//wont ever be thrown
			throw new Error(`${params.event.key} used to navigate`)
	}
}
```

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2045 | Keyboard navigation - Cannot navigate to/from spanned columns in multiple directions | IN PROGRESS
-- | -- | --
