### ISSUE TITLE
Additional Properties in ColumnDefinition.

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#2245]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you add new Properties to the ColumnDefinition, you get the following warning in the Browser: 
<img width="623" alt="bildschirmfoto 2018-03-10 um 12 51 04" src="https://user-images.githubusercontent.com/364896/37241966-be6fcd6c-2461-11e8-992a-31a350809360.png">

**Expected behavior**
Don't throw a warning.

Maybe you can add a Property "externalData" wich can be set and does not throw a error

**Comment by makinggoodsoftware** [comment]
Hi,

From our docs:

https://www.ag-grid.com/javascript-grid-properties/

suppressPropertyNamesCheck | Disables showing a warning message in the console if using a gridOptions or colDef property that doesn't exist.
-- | --

Hope this helps
