### ISSUE TITLE
Improve example for localeText

### ISSUE THREAD

**Issue by abenhamdine** [ag-grid/ag-grid#2246]
**I'm submitting a ...**
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The internalization example miss some important properties, and have some duplicated keys : https://www.ag-grid.com/javascript-grid-internationalisation/#using-localetext

**Expected behavior**
Better example, especially including properties : 
```js
notEqual: 'différent de',
notContains: 'ne contient pas'
```

No duplicate keys first and last

**Minimal reproduction of the problem with instructions**
see  https://www.ag-grid.com/javascript-grid-internationalisation/#using-localetext

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid we are not sure which keys are missing or duplicated, I am going to close this issue, but please feel free to open another issue if you think this still an issue

If you think that is the case, please include which keys are actually duplicated/missing

Thanks

**Comment by abenhamdine** [comment]
> If you think that is the case, please include which keys are actually duplicated/missing

It's exactly what I've done : 

>Better example, especially including properties :

>notEqual: 'différent de',
>notContains: 'ne contient pas'
>No duplicated keys first and last

**Comment by makinggoodsoftware** [comment]
Hi,

I can see now what you meant! 😮 

Sorry, I have just reopened the issue

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2164 - Website - Add missing keys on the i18n example

**Comment by bradschafer** [comment]
Note: the docs: https://www.ag-grid.com/javascript-grid-internationalisation/
Still have:    notEquals:
Should be:  notEqual:
