### ISSUE TITLE
Full width rows misplaced when focused

### ISSUE THREAD

**Issue by piobeny** [ag-grid/ag-grid#2249]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Whole .ag-full-width-container element is misplaced when focused on element currently not visible.

**Expected behavior**
Scroll whole body to focused row, not only .ag-full-width-container.

**Minimal reproduction of the problem with instructions**
1. Go to https://plnkr.co/edit/JzNnrPt0qUY1Azlmc6NY?p=preview
2. click any A or B button
3. click tab until view breaks

Example based on Detailed Full Width Example from documentation.
EDIT:
It is possible to generate this on docs example, just click button, close alert and tab until it breaks.

**Please tell us about your environment:**
Tried on 
Linux: Chrome, Firefox
Windows: IE, Edge, Chrome
* **ag-Grid version:**
17.0.0

**Comment by krzysztofbuszewicz-railwaymen** [comment]
The same issue spotted in version 16.0.0.

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as expected, the buttons A and B are custom buttons, so it will be up to you to manage the tab out, and call setCellFocus when appropiate

I am going to flag this issue as managed by the commnutiy
