### ISSUE TITLE
Row editing UI in Material Theme has transparent background and overlaps with row below

### ISSUE THREAD

**Issue by varunrramani** [ag-grid/ag-grid#2250]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Please find the image showing the current behavior on 17.0.0 at the following URL: [Current behavior](https://imgur.com/a/YfNvt)

**Expected behavior**
Please find the image showing the expected behavior which works with 16.0.1 at the following URL: [Expected behavior](https://imgur.com/a/Ul4V4)

**Minimal reproduction of the problem with instructions**

Create a grid with Material theme and enter the row editing mode

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows, npm server along with Angular 5 and using npm for package manager

* **ag-Grid version:** X.X.X
Issue found on 17.0.0

* **Browser:**
Runnig on Chrome with user agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Working on Angular 5 with Typescript 2.5.3 and ag-grid-angular

**Comment by sanderson751** [comment]
The same happens with the version in react.

**Comment by petyosi** [comment]
Thanks for the report - the fix is quite simple, you can add the rule from 08093e5 to your styles as a temporary measure.
