### ISSUE TITLE
ag-Grid Dart Package (Wrapper)

### ISSUE THREAD

**Issue by RaduGrama** [ag-grid/ag-grid#2252]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is currently no official Dart Package for ag-Grid.

**Expected behavior**
An official ag-Grid Dart Package that defines the correct and complete JavaScript interop between Dart and ag-Grid, similar to the one ag-Grid provides for TypeScript.

**What is the motivation / use case for changing the behavior?**
AngularDart is being promoted by Google quite a bit (and Dart in general is being promoted via Flutter). AngularDart provides a set of Material components (angular_components) that is far from being on par with the Material components provided for Angular (Angular Material), and in particular lacks a data grid. In addition, based on multiple statements, there appear to be no immediate plans to provide a data grid, and ag-Grid would fill that space quite nicely, especially used with the Material theme. To facilitate that, and considering that the Dart to JavaScript interop is slightly cumbersome and light on documentation, an official ag-Grid Dart Package would be very helpful and also make sense from an adoption prospective. Dart has a tool (js_facade_gen) to generate a JavaScript facade for a generic *.D.TS TypeScript library, but that is failing on the ag-Grid one.

**Please tell us about your environment:**

* **ag-Grid version:** 17.0.0

* **Browser:** all

* **Language:** Dart

**Comment by Vasanthkesavan** [comment]
Would be nice to have an official ag-grid package for the dart.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
