### ISSUE TITLE
frameworkComponents don't accept props

### ISSUE THREAD

**Issue by nightCapLounge** [ag-grid/ag-grid#2253]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I cannot pass a React component to the GridOptions.frameworkComponents attribute.  My component accepts props, while the data definition states that props cannot be accepted. 

**Expected behavior**

My React component should be able to accept props in its constructor.

**Minimal reproduction of the problem with instructions**

            <AgGridReact
                onGridReady={this.on_grid_ready}
                rowSelection="multiple"
                rowData={this.props.get_rows()}
                enableColResize
                frameworkComponents={{
                    derivative_cell_renderer: MyComponentWithProps
                }}
                gridOptions={{...this.gridOptions, columnDefs: this.props.get_columns()}}>

            </AgGridReact>

**What is the motivation / use case for changing the behavior?**

I would like to provide a custom Cell Renderer React Component

**Please tell us about your environment:**

Developing in Debian 8 virtualbox

* **ag-Grid version:** X.X.X

17.0.0

* **Browser:**

Chrome is the browser.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript.

THE FIX:

frameworkComponent definition looks like this:
`
    frameworkComponents?: {
        [p: string]: {
            new (): any;
        };
    };
`

And I would like it to look like this:
`
    frameworkComponents?: {
        [p: string]: {
            new (): any;
        } | {
            new (props: any): any 
        };
    };
`

**Comment by nightCapLounge** [comment]
Alrighty so I've been combing through Ag-grid docs as I get to know the framework better, and in a performance article, it notes that React components should be avoided in cell renderers in general.  This makes wonderful sense for performance, but then how would I get the props with data about the cell/row/state and also access my redux state?  Any tips in this direction?

**Comment by acaravia** [comment]
I'm trying to do something similar as I'm trying to use an existing grid as a detail/child grid in Master/Detail setup and just passing props so I can handle data retrieval and other various attributes properly.

**Comment by BizH** [comment]
I changed the type definition file that declares frameworkComponents as @nightCapLounge indicated and was able to use cellRenderer successfully. I can access the props as show in the example here: https://www.ag-grid.com/javascript-grid-cell-rendering-components/

```
frameworkComponents?: { [p: string]: { new (): any; } | { new (props: any): any }; };
```

**Comment by nightCapLounge** [comment]
Also note that reinstalling the module will erase the edited types, as well as installing types for other modules. Personally, I use a vagrant setup, so I just swap the files on provision with an npm script:

`    
"update-types": "sudo cp /vagrant/provision/gridOptions.d.ts /vagrant/node_modules/ag-grid/dist/lib/entities/gridOptions.d.ts"
`
and I run the same script after installing. The first file are my edited types.

**Comment by acaravia** [comment]
I'm doing this in ReactJS and doing it for Master/Detail setup. Will this work for detailCellRenderer?

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Comment by capaneus** [comment]
Actually I have the similar question regarding this as well.
I'm using ag grid with angular. I built a ICellEditorAngularComp, where it would be best to inject some service in this component to receive data from other data source. But when I use
`constructor( my_service: MyService) {}` it shows compile fail as seems the component can only be 
`new () => any`
which doesn't allow and angular service injection...

**Comment by capaneus** [comment]
Update: 
I have tried to change \node_modules\ag-grid-community\dist\lib\entities\gridOptions.d.ts
to 
`    frameworkComponents?: {
        [p: string]:
            | {
                  new (): any;
              }
            | { new (...args: any[]): any };
    };`

seems all works fine, compiled and service injected properly

**Comment by darylknowles** [comment]
I also ran into this while converting an agGrid app to use TypeScript.  Editing \node_modules\ag-grid-community\dist\entities\gridOptions.d.ts to change the definition for frameworkComponents as @nightCapLounge suggested works perfectly for me. 

Changed to:  frameworkComponents?: { [p: string]: { new (): any; } | { new (props: any): any }; };

All passed in properties work as expected.

**Comment by makinggoodsoftware** [comment]
Hi guys, just to let you know that in our next release ETA 1/2 weeks, we are changing the typings to allow these assignations.

I would advise to wait until then and test again, if you guys think there is still an issue, please let us know

Thanks for the patience and the feedback :)

**Comment by MaxMillington** [comment]
Are there docs for this update?

**Comment by CraigMeng** [comment]
> Are there docs for this update?

It seems that they just allow 'any'

https://github.com/ag-grid/ag-grid/blob/12efbfd1b84281c6d4722d9125b802160a1bf589/dist/lib/entities/gridOptions.d.ts#L272

**Comment by aviataravindhdotme** [comment]
Hi, @MaxMillington were you able to find the docs? I am using AG-Grid React and trying to pass props to a custom Framework component. Thanks

**Comment by rcketscientist** [comment]
I don't see that `any` option any longer.  Is there a better pattern for a custom cell renderer?

**Comment by Avi-Aravindh** [comment]
> I don't see that `any` option any longer. Is there a better pattern for a custom cell renderer?

If you are trying to pass params to a Custom Cell renderer, try using cellRendererParams in the colDef
