### ISSUE TITLE
Official Demo page not working in IE

### ISSUE THREAD

**Issue by phhbr** [ag-grid/ag-grid#2254]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I open up https://www.ag-grid.com/best-angular-2-data-grid/  in IE11, not one example gets rendered.

**Expected behavior**
When I open up https://www.ag-grid.com/best-angular-2-data-grid/  in IE11, I want to see the examples like I see them in Firefox and Chrome

**Minimal reproduction of the problem with instructions**
1. Open up IE (yea, seriously)
2. Go to https://www.ag-grid.com/best-angular-2-data-grid/ 
3. Wait
4. ??

**What is the motivation / use case for changing the behavior?**
Is Internet Explorer really supported by ag-grid?

**Please tell us about your environment:**
Internet Explorer

* **ag-Grid version:** 17.0.0

* **Browser:**
IE11: "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko"

* **Language:** [all]

**Comment by JabbyPanda** [comment]
Ag-grid is supported in IE11, it is just sample web-site is not working in IE1 due to CORS error from platform.twitter.com

![image](https://user-images.githubusercontent.com/255913/37590007-3844d8f6-2b67-11e8-8b08-2885edab28c2.png)

**Comment by petyosi** [comment]
ag-Grid itself works as expected in IE 11. The particular demo does not, due some weird combination of Angular, `base href` and template loading - SystemJS is suspected as well. 

As you may guess, pinpointing the exact problem is somewhat hard. Most  of the documentation should work in IE 11, but the complex angular examples like this one suffer from that issue.

**Comment by Axay001** [comment]
I have started with ag-grid with following documentation, But didn't get output in IE. I started with the first simple grid. I am getting proper output in chrome. 
https://www.ag-grid.com/angular-getting-started/

Also, I am not getting any error. 
Any solution to work this in IE?
