### ISSUE TITLE
Empty AgGridColumn errors in TypeScript

### ISSUE THREAD

**Issue by jonrimmer** [ag-grid/ag-grid#2255]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using React and TypeScript (with strict checking), `<AgGridColumn>` gives a type error about a missing `children` property if it is left empty. E.g. the following will error:

```jsx
<AgGridColumn field="name"></AgGridColumn>
```

```
TS2322: Type '{ field: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridColumn> & Readonly<{ children?: ReactNode; }...'.
  Type '{ field: string; }' is not assignable to type 'Readonly<AgGridColumnProps>'.
    Property 'children' is missing in type '{ field: string; }'.
```

**Expected behavior**

It should be possible to leave `<AgGridColumn>` empty, as per the React examples in the documentation.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/react-ts-zcezez?file=index.tsx

**What is the motivation / use case for changing the behavior?**

Correctness.

**Please tell us about your environment:**

macOS
VSCode
Yarn
webpack-dev-server

* **ag-Grid version:** 17.0.0

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:50.0) Gecko/20100101 Firefox/50.0"

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"

* **Language:** TypeScript 2.7.2

**Comment by k3flo** [comment]
Still not fixed?

**Comment by seanlandsman** [comment]
See also: https://github.com/ag-grid/ag-grid-react/issues/118

**Comment by ssilve1989** [comment]
What's the status on this?

**Comment by seanlandsman** [comment]
Hi - this will be fixed in ag-grid-react 19

thanks for reporting this
