### ISSUE TITLE
Shift+Enter shortcut

### ISSUE THREAD

**Issue by jafetbjarkar** [ag-grid/ag-grid#2257]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

Implement Shift+Enter

**Expected behaviour**
Depends on cell state:
• When cell is selected and you press Shift+Enter, ignore the shift button and focus the cell like normal.
• When cell is focused and you press Shift+Enter move the cell selection one up, instead of one down.

**What is the motivation / use case for changing the behavior?**
This is a handy shortcut for faster cell navigation after you finish editing. Both Excel and Google Spreadsheets have Shift+Enter shortcut so most people are used to this behaviour. 

* **ag-Grid version:** 
17.0.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

* **Language:**
All

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
