### ISSUE TITLE
Shallow and Deep Cell Focus

### ISSUE THREAD

**Issue by jafetbjarkar** [ag-grid/ag-grid#2258]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

* **Shallow Focus**: Arrow keys will move the selected cell
* **Deep Focus**: Arrow keys will move the text cursor inside the cell

**Current behaviour**
AG-Grid only has deep focus so users can't navigate cells with arrow buttons when cell is focused.

**Expected behaviour**
* Select Cell + Printable Key Pressed -> Shallow Focus
* Mouse Double Click -> Deep Focus
* Press Enter or F2 -> Deep Focus

**What is the motivation / use case for changing the behaviour?**
* Users can edit cells and use arrow keys to navigate cells.
* Better user experience
* Faster cell editing
* Both Excel and Google Spreadsheets have shallow and deep focus so users are familiar the functionality

**Excel vs. Google Spreadsheets:**
Both platforms make use of shallow and deep focus. The difference is how the Enter button is implemented. Excel will move the selected cell one down but Spreadsheets will enter deep focus. The latter is convenient because you don't have to use the mouse to enter deep focus.

• **ag-Grid version:** 17.0.0

• **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

• **Language:** All

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
