### ISSUE TITLE
[max row count] Not able to see all rows on IE11

### ISSUE THREAD

**Issue by gjdev** [ag-grid/ag-grid#226]
This is reprodable on the test-drive/example page. When you go to http://angulargrid.com/example.html and choose to show 100000 rows via the dropdown, the scrolling stops around row 61378. Additionally, the last rows shown are not correct: row 61378 partly overlaps row 61356, the rows that should be shown just before row 61378 are missing..
We're testing on IE and Chrome. In Chrome this all works as expected.

**Comment by gjdev** [comment]
Also reproducable on IE9

**Comment by ceolter** [comment]
i've noticed on my IE, that the grid scrolls are not been used, instead the browser is doing the scrolling and the grid scrolls are not working. can you confirm this is the same for you? (ie the grid should only render one 'scroll viewable window', but it's actually rendering the entire grid for me)

**Comment by gjdev** [comment]
If I use the example grid from your site with 100000 rows and scroll to the bottom, the ag-body-container div contains only the rows 61309-61358. Does that answer your question?
To me that seems to indicate that it does render only the viewable rows, not the entire grid.

Scrolling on IE is a lot slower than on chrome though. Almost unusable.

**Comment by ceolter** [comment]
"61309-61358" . . . . . yes that's what is supposed to happen. i just noticed today in work it's broken, although i tested it at home - must be just my version of IE in work.

i'll have to check this at home, i'm getting different results in work.

**Comment by ceolter** [comment]
i have checked this at home. and yes it's as you describe. looks like a limit on the height of the underlying div (where i place the cells). i agree this is a problem, and i'll leave the issue open, but i won't be treating it as high severity as, well in my opinion, someone won't be reading down through 65000+ rows on a screen. it's more probable they will load the data into the grid, then filter or sort to find the data that they are interested in.

regarding scrolling, i agree, the scrolling makes the grid frustrating to use'in IE. i find that the mouse wheel scrolls smoother than the scrollbars. my take on this is the grid supports IE, in that it works, so if people mush use it they can, however we try to move our customers over to another browser for a better HTML 5 overall experience.

**Comment by ceolter** [comment]
i've changed my mind on this. i'll look into making it faster. there are some tricks i know about i haven't applied yet, i'll get them done, should speed it up.
also someone said it's an issue with Chrome (they must be on a slow machine)
https://github.com/ceolter/angular-grid/issues/231#issuecomment-112379738

**Comment by elaijuh** [comment]
@ceolter , well not that slow machine i guess, i5 CPU@2.6GHz with 16G RAM and SSD, chrome 35

**Comment by AvishekNath** [comment]
Can u please suggest me, how to show a loader when we do vertical scrolling to avoid blank space that is appearing in IE11 mostly.

**Comment by ceolter** [comment]
nothing comes to mind. i'm working on performance improvements at the moment, will see if still an issue after this weekends relese.

**Comment by maroy1986** [comment]
Has any work been done on this since the last post of this issue? We have the same behavior here on IE11 with a lot of data. It is worst with pinned columns, both "section" doesn't follow each others when scrolling on IE11. It's working fine in any other browser but we need it to work on IE (business requirement)...

Can you give us an update on this?

**Comment by neawasthi** [comment]
I cam across this tip somewhere - not vast improvement but better than before. use this in gridoptions.
isScrollLag: function() { return false; },

**Comment by maroy1986** [comment]
Already had the `isScrollLag` gridOptions enabled but it doesn't change anything, still lagging.

**Comment by ceolter** [comment]
no update on this :( busy with other items, sorry.

**Comment by maroy1986** [comment]
Alright, I understand as I said in the other issue. Keep up the good work 👍

**Comment by loknar777** [comment]
Have the same issue on IE 11.0.9600.18524. Works fine in Chrome.
Vertical scrollbar completely unusable and scrolling of 1000 rows and less than 10 columns in painful.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-48

**Comment by IceOnFire** [comment]
Hi, are there any news on this issue?

**Comment by srishti0212** [comment]
Hi Is there any update on this issue ?

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked by AG-1317, you can see the progress of this ticket in our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/
