### ISSUE TITLE
TypeScript signature of GridApi.setColumnState is incorrect

### ISSUE THREAD

**Issue by UselessPickles** [ag-grid/ag-grid#2260]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`GridApi.setColumnState()` unnecessarily requires a second `source` parameter as of v17.0.0

**Expected behavior**
When calling `GridApi.setColumnState()`, I should not have to explicitly pass in a value of `"api"` as a second param to tell AgGrid that `setColumnState` is being called from the API. 

There should be no `source` parameter at all for `GridApi.setColumnState()`. Its implementation should pass a hard-coded value of `"api"` to `this.columnController.setColumnState`

**Minimal reproduction of the problem with instructions**
Obvious

**Please tell us about your environment:**

* **ag-Grid version:** 17.0.0

* **Browser:**
Irrelevant

* **Language:** 
Typescript 2.7.2

**Comment by Pradeepg21** [comment]
yes same issue I am also facing

**Comment by gportela85** [comment]
AG-1693 - Fixed by https://github.com/ag-grid/ag-grid/commit/7bd6005ee255e2d081c2b6aa7b94d7687997822f#diff-dbc9cf8b6942b3a156a61b45369dd99b
