### ISSUE TITLE
No method getCellRendererInstances in gridApi.d.ts in ag-grid 11.0.0

### ISSUE THREAD

**Issue by rammohan201** [ag-grid/ag-grid#2264]
I am using Ag Grid angular 11.0.0. I checked gridApi.d.ts file, there is no getCellRendererInstances method.
is this method added in a different ag grid version?

**Comment by makinggoodsoftware** [comment]
Hi,

We would suggest to move to our last version, in this case v19.0.0

Otherwise you can check our changelog and pipeline

https://www.ag-grid.com/ag-grid-changelog/
https://www.ag-grid.com/ag-grid-pipeline/

Hope this helps
