### ISSUE TITLE
How to disable tool panel (enterprise)

### ISSUE THREAD

**Issue by DominicTobias** [ag-grid/ag-grid#2270]
On v17 you have this nice looking ToolPanel that I don't want. I tried to remove it with `showToolPanel` but that doesn't work.

Can't see anything in the docs about it here: https://www.ag-grid.com/javascript-grid-tool-panel/

I will `display: none` for now but seems a waste of resources to render it in the first place.

Thanks

**Comment by SimonSch** [comment]
Try 
`toolPanelSuppressSideButtons = true;`

**Comment by DominicTobias** [comment]
Thanks that worked

**Comment by anatoly314** [comment]
I just curious why it isn't mentioned in official documentation? I couldn't find it there.
