### ISSUE TITLE
gridApi.getDataAsExcel issues with leading zeros and string containing only numbers.

### ISSUE THREAD

**Issue by yparenteau** [ag-grid/ag-grid#2272]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When invoking gridApi.getDataAsExcel some strings got exported as Number in Excel. 

Which leads to:
"007007" to be converted to 7007
"123456789000" to be converted to 1.23457E+11

The reason of this it located in ExcelGridSerializingSession.onNewBodyColumn.
`const type: ExcelDataType = Utils.isNumeric(valueForCell) ? 'Number' : 'String';`

Unfortunatly ` Utils.isNumeric("007007")` will return true....

Why not using the javascript type instead?
` const type: ExcelDataType = typeof valueForCell === 'number' ? 'Number' : 'String';`

**Comment by rmc-software** [comment]
Closing this as you should set the data type of the column, see: 

https://www.ag-grid.com/javascript-grid-excel/#excel-style-definition
