### ISSUE TITLE
Grid ID in GridOptions, (auto alloted, or user alloted)

### ISSUE THREAD

**Issue by srikanthj09** [ag-grid/ag-grid#2274]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

 If we get Grid ID in GridOptions events( either by Auto assigned or user assigned). 
It will helps to play-around for dynamic grid creation.
And also if we get hidden additional reference-able attribute or value for grid.

**Please tell us about your environment:**

visual Code, windows 7
* **ag-Grid version:** X.X.X

ag-Grid 17.0.0 with enterprises

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
