### ISSUE TITLE
Setting domLayout="autoHeight" causes the column toolbar panel on the right to be very small

### ISSUE THREAD

**Issue by hoff121324** [ag-grid/ag-grid#2276]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When setting domLayout="autoHeight", the toolbar on the right becomes too small to properly use.

**Expected behavior**

The tool panel should be the same height as the grid, or at least have a reasonable minimum height.

**Minimal reproduction of the problem with instructions**

This can be seen broken on the example page: https://www.ag-grid.com/javascript-grid-width-and-height/ on the "Auto Height" example.  Notice how the 'columns' button looks and behaves incorrectly.

**What is the motivation / use case for changing the behavior?**

I would like to be able to use autoheight and still have a useful tool panel.

* **ag-Grid version:** X.X.X
ag-grid and ag-grid react 17.0.0

* **Browser:**
Google Chrome

**Comment by petyosi** [comment]
Thanks for the report, we addressed that in https://github.com/ag-grid/ag-grid/commit/40a76f5c3a7dbf5913c886a22979c21701a3d98e - should be fixed in the next release.
