### ISSUE TITLE
Ag Grid ReactJS not updating after cellStyle change

### ISSUE THREAD

**Issue by scottkunkel** [ag-grid/ag-grid#2278]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using AgGrid 17 with Reactjs 16.2
`<AgGridReact 
                    rowData={this.props.rowData}
                    columnDefs={this.createColumnDefs(this.props.config)} 
/>`
changing the cellstyle of the columnDefs (italic font-style) works fine the first time, after trying to change it back to normal, italic stays. React is not recognizing the change and not rerendering.
cellStyle is a function inside columnDefinition

`
 createColumnDefs(config){
    var col = {}
    col.cellStyle = function(params){
      return {
        'font-style': config.italic ? 'italic' : 'normal'
      }
   }
   return [col];
}
`

which evaluates a variable config from closure. The cellStyle is evaluated correctly the first time, but at runtime, if config.italic changes, it is not evaluated.
I understand that AG-Grid is looking for value changes but how would I deal with the change in the config? This worked in previous version (12).

**Expected behavior**
Rerendering cells on change of evaluations or indicating cellstyle eval has changed

**What is the motivation / use case for changing the behavior?**
Dynamically changing styles of ag-grid cells

**Please tell us about your environment:**
windows, webpack, reactjs

* **ag-Grid version:** X.X.X
17.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES2015

**Comment by klteograss** [comment]
FYI, this issue also happened in angular component.

**Comment by scottkunkel** [comment]
using Cellrenderer Class instead of function resolved the issue.
