### ISSUE TITLE
Reset Columns Menu item does not raise event

### ISSUE THREAD

**Issue by scottkunkel** [ag-grid/ag-grid#2279]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

using Default Menu Item Reset Columns does not trigger any event

**Expected behavior**

Resetting columns (size and visibility) should trigger an event

**Minimal reproduction of the problem with instructions**

Hide a column
click Reset Columns
no event triggered

**What is the motivation / use case for changing the behavior?**

Saving Table State

**Please tell us about your environment:**

Windows
Webpack

* **ag-Grid version:** X.X.X

17.0.0

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES2015

**Comment by anil1712** [comment]
also, can we add HTML type support for MenuItemDef "name" property, right now it is supporting only string type I wanted to show some HTML styled component there. 

```
export interface MenuItemDef {
    name: string; // Can we enhance support here to support JSX or HTMLElement too
    disabled?: boolean;
    shortcut?: string;
    action?: ()=>void;
    checked?: boolean;
    icon?: HTMLElement|string;
    subMenu?: (MenuItemDef|string)[];
    cssClasses?: string[];
    tooltip?: string;
}
```

**Comment by scottkunkel** [comment]
Any ideas on how to work this out? I added 
        setTimeout(()=>{
            if (this.gridApi){
                this.gridApi.redrawRows({force:true});
                this.gridApi.expandAll(); 
                console.log("Force redraw")
            }
        }, 100); //HACK and not happy 
to the parent component componentDidUpdate but that does not seem to get the wanted result.

**Comment by scottkunkel** [comment]
using the class instead of the function resolves the issue

**Comment by colonelpopcorn** [comment]
This is something we would like as well, currently we have server side column definitions that we would like to restore with an API call. Is this something that is on the roadmap for the future?

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-2099 | Columns - Add reset columns as a source for displayedColumnsChanged
-- | --

**Comment by Irina-Sass** [comment]
Hi!

I have the same problem. I've tried to find the feature request number AG-2099, but it hasn't exist in your backlog.

Could you give actual link or feature request number?

**Comment by StephenCooper** [comment]
https://plnkr.co/edit/ju0YUYy8nndgiPww?open=main.ts

When clicking Reset Columns one of the events fired is `columnEverythingChanged` as can be seen here. 

https://plnkr.co/edit/ju0YUYy8nndgiPww?open=main.ts
