### ISSUE TITLE
DateTime cellRenderer  as value breaks grid

### ISSUE THREAD

**Issue by scottkunkel** [ag-grid/ag-grid#2287]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

for cellrenderer on a column, when the datatype is Date, the grid breaks with 
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at CellComp.afterCellRendererCreated (cellComp.js:589)
    at Promise.then (utils.js:1601)
    at CellComp.createCellRendererInstance (cellComp.js:571)
    at CellComp.attachCellRenderer (cellComp.js:596)
    at CellComp.afterAttached (cellComp.js:107)
    at eval (rowComp.js:971)
    at Array.forEach (<anonymous>)
    at RowComp.callAfterRowAttachedOnCells (rowComp.js:969)
    at eval (rowComp.js:219)
    at eval (rowContainerComponent.js:85)

String and Numbers work fine

**Expected behavior**

cellRenderer for dates work
workaround: return params.value.toString() if datatype is Date

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/MylwafUwNdToSRsHeJsF?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
webpack, windows

* **ag-Grid version:** X.X.X
17.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by petyosi** [comment]
Hi, 

the posted plunker seems unfinished and does not result in the error you refer to. Any chance you did not save it?

**Comment by scottkunkel** [comment]
Please try again. I wasn't signed in when saving.

**Comment by petyosi** [comment]
Thank you. The behavior is expected - you can't return dates from a cell renderer. This is described in the [cell renderer documentation section](https://www.ag-grid.com/javascript-grid-cell-rendering/).

**Comment by scottkunkel** [comment]
Thank you for clarifying. That works
