### ISSUE TITLE
cellrenderer, when using rowModelType, is called before getRows() is executed and and the  param.data property is undefined

### ISSUE THREAD

**Issue by jszejner** [ag-grid/ag-grid#2288]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

cellrenderer, when using rowModelType, is called before getRows() with the and the  param.data property is undefined.
**Expected behavior**

cellrenderer function should only be called after data has been returned from getRows
**Minimal reproduction of the problem with instructions**

Forked from https://www.ag-grid.com/javascript-grid-infinite-scrolling/ "Example 2: Equal Pagination Page Size and Large Infinite Block Size"
https://plnkr.co/edit/ksGoJERrvskAc9WnBRBU?p=preview
See error written to console when params.data is undefined.

**What is the motivation / use case for changing the behavior?**

Breaks when migrating existing application to use ag grid's version of server side paging. params.data won't be undefined without a Datasource. Once a data source is used cellRenderers are called more often than needed with empty data property.
**Please tell us about your environment:**

Windows, Visual Studio 2017, none, IIS
* **ag-Grid version:** 17.0.0

* **Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

From our knowledge base (only accessible to customers so far)

The infinite wor model scroll will show rows that haven't loaded yet. Value handler routines attached to these rows will be presented with null values while the rows load.

Our documentation shows how to supply the user with a spinner whilst rows are being loaded:

Loading Spinner
The examples on this page use a loading spinner to show if the row is waiting for its data to be loaded. The grid does not provide this, rather it is a simple rendering technique used in the examples. If the data is loading, then the rowNode will have no id. So if you use the id as the value, the cell will get refreshed when the id is set.

loadingSpinnerColumn = {

    // use a value getter to have the node id as this columns value
    valueGetter: 'node.id',

    // then a custom cellRenderer
    cellRenderer: function(params) {
        if (params.value === undefined) {
            // when no node id, display the spinner image
            return '<img src="loading.gif">'
        } else {
            // otherwise just display node id (or whatever you wish for this column)
            return params.value;
        }
    }
}
https://www.ag-grid.com/javascript-grid-infinite-scrolling/#loading-spinner
