### ISSUE TITLE
Navigation Key Down won't end editing and move to the next cell.

### ISSUE THREAD

**Issue by sks83** [ag-grid/ag-grid#2289]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When i hit Navigation Down Key on a cell in edit mode it does nothing.

**Expected behavior**

As per documentation:
      Navigation Key Down: Editing will stop, accepting changes, and editing will move to the next cell in the direction of the navigation key.
https://www.ag-grid.com/javascript-grid-cell-editing/

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

This is not how it is supposed to work, note that you can create your own editor and override this.

I am going to flag this issue as managed by the community

**Comment by warheartvik** [comment]
Hello @makinggoodsoftware  how are you. Is this solved?
ag-grid docs still remain as:

Navigation Key Down: Editing will stop, accepting changes, and editing will move to the next cell in the direction of the navigation key.

But this feature still not working as espected, without any of the navigation keys ( in #2031 you mentioned it will work using left and right arrow, but it's not)

I made a github repo https://github.com/warheartvik/nuxt-ag-grid Maybe you can check it out and point if I missing something. 

Also, if you have an example of a custom cell editor which can make this feature possible, please advise!

Best regards!

**Comment by BartokW** [comment]
I'm also running into this issue. None of the navigation keys are ending the editing.  When running the angular version of ag-grid v20.1.0 all four directions of navigation keys would end the editing, but with version 21.0.1 none of the directions work.
