### ISSUE TITLE
Arrow keys navigation not working inside the ag-grid

### ISSUE THREAD

**Issue by srited** [ag-grid/ag-grid#2291]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
 After editing a cell arrow keys doesn't work to move forward or backward between the cells.

**Expected behavior**
cell navigation to happen on arrow key press(left and right)

**Minimal reproduction of the problem with instructions**
 After editing a cell arrow keys doesn't work to move forward or backward between the cells.

 

* **ag-Grid version:** X.X.X
 

* **Browser:**
 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that this is not how this feature is meant to work OOB when you enter edit mode.

Note that you can create your own editor and do as you like with the arrows when you receive them

I am going to flag this ticket as managed by the community
