### ISSUE TITLE
Ability to Pin / Make Sticky a Row Group / Or Add a Stand alone aggregation row that can be pinned

### ISSUE THREAD

**Issue by jcgertig** [ag-grid/ag-grid#2292]
**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [x] feature request
- [ ] support request

**Current behavior**

When you have a row group open and scroll the group row scrolls up as well.

**Expected behavior**

When you have a row group open and scroll the group row stays above the grouped rows.
This is especially useful when aggregation functions are turned on.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/FTXcm0bdMgNEUBMQm2Qf?p=preview

**What is the motivation / use case for changing the behavior?**

This is especially useful when aggregation functions are turned on so you can have a persistent aggregation row with out having to handle aggregation your self in a pinned row, handling things like filter to re aggregate.

**Please tell us about your environment:**

OSX and Windows, VS Code, yarn

* **ag-Grid version:** X.X.X

16.X

* **Browser:**

Chrome Newest

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript Newest

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-463 | [sticky groups] have opened group rows float
-- | --
