### ISSUE TITLE
refreshHeader() initializes new floating filter components instead of re-rendering

### ISSUE THREAD

**Issue by mantas-janulionis** [ag-grid/ag-grid#2293]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Calling `api.refreshHeader()` duplicates floating filter components

**Expected behavior**

Calling `api.refreshHeader()` does not initialize a new instance of floating component

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/ILUyBhNGbjU9sPpGEUxt?p=preview
modify filter value and see output in the console
NumberFloatingFilter.prototype.init() method is called every time after `api.refreshHeader()` is called.

**What is the motivation / use case for changing the behavior?**
I think it's a memory leak and causes unexpected outcome. Working with complex floating filters, it is difficult to manage the state.
It also affects framework components (tested with React - component constructor get called multiple times)

**Please tell us about your environment:**
mac OS 10.13.3, chrome (latest)

* **ag-Grid version:** 17.0.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Upon further investigation,

I can see that you have this on your code

onGridReady: (params) => params.api.addEventListener('modelUpdated', e => e.api.refreshHeader()),

Even though I agree this is recreating the floating filters, it look like the root cause here might be different.

Would you be able to summarise what are you trying to achieve with this code?

Thanks

**Comment by makinggoodsoftware** [comment]
Since this has been inactive for a while, going to close this thread, feel free to create a new ticket if you want to follow up.
