### ISSUE TITLE
custom rowGroupRenderer failing with version 17.0.0

### ISSUE THREAD

**Issue by codeBYdivy** [ag-grid/ag-grid#2300]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have created a custom groupRowRenderer Component, 
I was using it with version: 9.1.0 previously.
but now when I upgraded the system to 17.0.0, it starts breaking.

**Expected behavior**

I think it should work fine as the documentation says the same about groupRowRenderer 

**Minimal reproduction of the problem with instructions**

I'm sharing the plunker highlighting the concern

**WORKING** 
Plunker using version 9.1.0 https://plnkr.co/edit/w6K5DvruhLxBSpKhgfNp?p=preview

**NOT WORKING** 
Plunker using version 17.0.0 https://plnkr.co/edit/wipZ3Sp2I9lMKSCLE8RA?p=preview

**What is the motivation / use case for changing the behavior?**

I'm just following the documentaion 
https://www.ag-grid.com/javascript-grid-grouping/#full-width-groups-rendering
I want my custom groupRow

**Please tell us about your environment:**

OS: Windows
IDE: Webstrom
package manager: node/npm

* **ag-Grid version:**  17.0.0

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.4.2 
 Angular 5.1.3
all

**Comment by seanlandsman** [comment]
Thanks for reporting this - this will be fixed in our next release.
