### ISSUE TITLE
Provide which filter caused filterChanged event

### ISSUE THREAD

**Issue by ssilve1989** [ag-grid/ag-grid#2301]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Adding an event listener to `filterChanged` returns an object with a `type: 'filterChanged'` property.

**Expected behavior**

I'd expect the type to be one of `quickFilter`, `advancedFilter`, etc. Something to distinguish between which filter this event was caused by.

**Minimal reproduction of the problem with instructions**

`gridApi.addEventListener('filterChanged', ({ type }) => console.log(type));`

**What is the motivation / use case for changing the behavior?**

Specifically, I hook into this event to persist the filterModel when the filterChanged event triggers, but I don't care if it's a quickFilter, I only want to persist the advanced filter. Therefore, quickFilters end up triggering my save action since I cant distinguish them.

**Please tell us about your environment:**

OSX, VSCode, yarn, express

* **ag-Grid version:** X.X.X

v16.0.1

* **Browser:**

Latest Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by lvanderbijl** [comment]
Yes please - we are an enterprise customer and also need this functionality, not only for filters but for sort changes as well

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2151
filterChanged event - parameters 'type' field should describe the source of filter change

**Comment by MarkusAbtion** [comment]
How is this going?
