### ISSUE TITLE
Row height auto

### ISSUE THREAD

**Issue by CSantosM** [ag-grid/ag-grid#2302]
It is not possible set the row height like "auto", only with a fix height
The correct behaviour would be can select the height like auto, and this height must change if I resize de column width. All the information should be availabe to be readed

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It is not possible set the row height like "auto", only with a fix height

**Expected behavior**
 The correct behaviour would be can select the height like auto, and this height must change if I resize de column width. All the information should be availabe to be readed

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 14.1.0

* **Browser:**
All

* **Language:** [all | TypeScript 2.4.0 | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

There is now auto height in the grid

Hope this helps
