### ISSUE TITLE
Filter menu doesn't close in older version of chrome

### ISSUE THREAD

**Issue by mlhummon** [ag-grid/ag-grid#2306]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In Chrome 36 & 37, the filter menu won't close after clicking outside of the menu. Instead, this error is thrown, 'Uncaught TypeError: undefined is not a function' (thrown from [here](https://github.com/ag-grid/ag-grid/blob/17.0.0/src/ts/utils.ts):1130) It appears to happen because Event.path in older versions of chrome returns a NodeList instead of an array. Adding the snippet below appears to fix the issue.

			NodeList.prototype.indexOf = function(element) {
				for(var i = 0; i < this.length; i++) {
					if (this.item(i) === element) return i ;
				}
			}

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Visit this demo, [https://www.ag-grid.com/example-runner/vanilla.php](https://www.ag-grid.com/example-runner/vanilla.php?section=javascript-grid-filter-component&example=custom-filter&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Anull%7D), open one of the filter menu's then click anywhere in the grid. The menu does not close and an error pops up in the console (Uncaught TypeError: undefined is not a function).

**What is the motivation / use case for changing the behavior?**

Filter menu closes when clicking outside of it.

**Please tell us about your environment:**

* **ag-Grid version: 

v17.0.0

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/ Safari/537.36

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that we don't support browsers as old as Chrome 36 and Chrome 37
