### ISSUE TITLE
Using cell style for change tracking requires a style be returned to undo the change exists style

### ISSUE THREAD

**Issue by consultwithmike** [ag-grid/ag-grid#2313]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Right now, if I return a cell style that indicates a change exists (e.g. yellow background), and then return `null` later for that same cell because the value was reverted, it doesn't **reset** the style.

**Expected behavior**

Returning `null` should **reset** the style.

**Minimal reproduction of the problem with instructions**

Consider a `getCellStyle` function like this:

    getCellStyle(params) {
      const { originalSummaryData } = this.state;
      if (!originalSummaryData) {
        return null;
      }

      const { colDef, data } = params;
      const { field } = colDef;

      const originalData = find(originalSummaryData, { id: data.id });
      if (!originalData) {
        return null;
      }

      if (originalData[field] === data[field]) {
        // returning null here does not RESET the CSS
        // if the cell had previously been styled.
        return {
          backgroundColor: 'inherit'
        };
      }

      return {
        backgroundColor: '#FFFFB9'
      };
    }

Right now, where I'm returning `backgroundColor: 'inherit'`, I feel like returning `null` is more intuitive.

**What is the motivation / use case for changing the behavior?**

I personally just think it's more intuitive - especially because of the example in the docs where *if it's not Police* it returns `null`. It's possible this was the planned behavior and just got missed honestly.

**Please tell us about your environment:**

Windows 10 Pro, React, npm, Webpack, .NET WebDev server

* **ag-Grid version:** X.X.X

17.1.0

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
