### ISSUE TITLE
Setting total pages in the grid for pagination

### ISSUE THREAD

**Issue by tom-riddle** [ag-grid/ag-grid#2314]
There should be an API to set total number of pages in pagination in ag-grid.

This becomes important when requesting large data through REST.

**Comment by makinggoodsoftware** [comment]
Hi,

To specify how many pages, you need to do so by leveraging the getRows callback from your datasouce.

ie

https://www.ag-grid.com/javascript-grid-infinite-scrolling/#setting-last-row-index

**Comment by zeesulehria** [comment]
I am able to set the total count of pages in ag-grid community version. Please see this answer:

https://stackoverflow.com/a/61916873/5535003
