### ISSUE TITLE
Feature: Possibility to set total amount of pages.

### ISSUE THREAD

**Issue by baruchvlz** [ag-grid/ag-grid#2315]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

There is no method in the pagination API that allows the user to manually set the amount of pages in the pagination toolbar.

**Expected behavior**

An API that would allow the user to manually set the amount of total pages in the pagination. With this method there should be another method added to set the current page as well.

**What is the motivation / use case for changing the behavior?**

We use a GQL server that allows us to return paginated data, this paginated data also contains the total amount of data collected from that query.

Example data:

```
var gqlPaginatedData = {
  results: [
    {make: "Toyota", model: "Celica", price: 35000},
    {make: "Ford", model: "Mondeo", price: 32000},
    {make: "Porsche", model: "Boxter", price: 72000}
  ],
  count: 1000,
}
```

We would like to be able to set the amount of pages available as `gqlPaginatedData.count / gridOptions.paginationPageSize`. As I said, this would require another method to be added to update the current page number.

Every time the `paginationChanged` event is emitted, our function would fetch the data for the next page in GQL, updated the `rowData` and change the current page number.

**Please tell us about your environment:**
Mac OS 10.13.3
VSCode
NPM
Angular 5+

* **ag-Grid version:** ^17.0.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/65.0.3325.181 Safari/537.3

* **Language:** TypeScript 2.5.3

Related to: #2314 but I figured I'd open my own issue instead of taking over the other user's issue.

**Comment by andr3i4o** [comment]
Plus one - that would be a great option as well as the the option to set the total records count.

**Comment by makinggoodsoftware** [comment]
Hi,

To specify how many pages, you need to do so by leveraging the getRows callback from your datasouce.

ie

https://www.ag-grid.com/javascript-grid-infinite-scrolling/#setting-last-row-index

**Comment by epavan** [comment]
Hey guys, after setting last row index, should the table refresh on its own or should I refresh it manually calling some API?

**Comment by zeesulehria** [comment]
I am able to set the total count of pages in ag-grid community version. Please see this answer:

https://stackoverflow.com/a/61916873/5535003
