### ISSUE TITLE
forPrint warning always prompt

### ISSUE THREAD

**Issue by namnn** [ag-grid/ag-grid#2316]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After setting domLayout to 'autoHeight', 'forPrint' warning still prompts as it happens before the check.
```
console.warn("ag-grid: Since v17.1.0 domLayout: 'forPrint' has been deprecated. Please use instead auto height: https://www.ag-grid.com/javascript-grid-width-and-height/#autoHeight");
return this.gridOptions.domLayout === 'forPrint';
```

**Expected behavior**
No console warning after setting domLayout to 'autoHeight' or leave it as undefined

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.0

* **Browser:**
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by crumhorn** [comment]
I'm really amazed this bug passed any sort of testing as it would print this out constantly no matter what. It literally grinds our app to a halt with all the log statements.

A very temporary workaround is to set a new method without the console.warn:

```
GridOptionsWrapper.prototype.isForPrint = function () {
            return this.gridOptions.domLayout === 'forPrint';
};
```

Just do that wherever the entrypoint in your app is, for example app.module.ts for Angular2.
