### ISSUE TITLE
cellRendererSelector not working with angular componenets

### ISSUE THREAD

**Issue by jkrth617** [ag-grid/ag-grid#2321]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am working with ag-grid 16.0.1 and angular5.
I have several custom cell renderers which implement "AgRendererComponent". I want to use the property "cellRendererSelector". It doesn't seem like the cellRendererSelector works with angular Components. It requires different functions(init instead of agInit and getGui). I was not able to get my angular component cell renderers working with the cellRendererSelector Property. It seemed that the component that is returned in the cellRendererSelector needs to be a vanilla js/ts class.
(I am also guessing this is the same with the editorSelector)

**Expected behavior**

I have registered several components in the module so that ag grid is aware of the custom renderers. I would expect the cellRendererSelector to be a function that could return an object with a component property which is an implementation of AgRendererComponent and is a registered angular component. 

Or is there a work around/way I can use the cellRendererSelector inside the angular framework?

**Minimal reproduction of the problem with instructions**

1.  get ag-grid working in a angular application.
2.  register 2 components that are cell renderers(i have have them hooked up to various columns using the cellRendererFramework property) 
3.  try to conditionally use one of the renderers using the cellRendererSelector property.

**What is the motivation / use case for changing the behavior?**

I have a complex grid where each row could mean multiple things. When a row satisfies a certain criteria I want to use different cellRenderers for cells in that same column

**Please tell us about your environment:**

windows 7 Enterprise

* **ag-Grid version:** 
    "ag-grid": "16.0.1",
    "ag-grid-angular": "16.0.0",
    "ag-grid-enterprise": "16.0.1"

* **Browser:**

"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"

* **Language:** TypeScript 2.5

**Comment by gssjr** [comment]
+1

**Comment by ilius33** [comment]
+1

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks

**Comment by dicbrus** [comment]
I confirm that in v. 20.0.0 issue resolved.

**Comment by vks-financial-com** [comment]
> I confirm that in v. 20.0.0 issue resolved.

Where is this documented? I have a similar issue, but with Vue. If I return `{ component: 'MyRegisteredFrameworkRenderer'` }, or  `{ component: MyRegisteredFrameworkRenderer` } the ag-grid throws an obscure error.
