### ISSUE TITLE
Header Cell Labels are truncated too soon when enableFilter: false

### ISSUE THREAD

**Issue by runsie** [ag-grid/ag-grid#2328]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Header Cell Labels are truncated too soon when enableFilter: false

The width is always calculated by subtracting the icon-size, even when enableFilter: false

This wastes a lot of space and we can't read the header labels. We have a dense grid and need the space.

From _ag-theme-common.scss :

    .ag-header-cell-label {
        display: flex;
        float: left;
        height: 100%;
        width: calc(100% - #{$icon-size});

**Expected behavior**

Header Cell Labels would be visible at a smaller width

**Minimal reproduction of the problem with instructions**

Please see the Plunker:
https://plnkr.co/edit/c9LAMlE0e7U3XV0ko262?p=preview

**What is the motivation / use case for changing the behavior?**

See the Plunker.  We rarely use enableFilter, and have large grids so need the space.  The labels are unreadable even though the space is there.

**Please tell us about your environment:**

Win 7

* **ag-Grid version:** X.X.X

17.0.0

* **Browser:**

Chrome, IE11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Plain JavaScript

**Comment by makinggoodsoftware** [comment]
Hi,

We don't think this is a bug, is up to you to configure the styling provide your own header component so that you can have full control on the space and how it is used there.

I am going to flag this issue as managed by the community
