### ISSUE TITLE
gridOptions.rowClass doesnt get assigned on first oncellchanged event.

### ISSUE THREAD

**Issue by koolhuman** [ag-grid/ag-grid#2332]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

I am trying to set the rowClass for each row which has been edited. I am trying to set this class in oncellChanged event. Surprisingly this works only after you make the second edit. When you edit the cell for the very first time the class is not being assigned.

**Minimal reproduction of the problem with instructions**
The second column in the grid is editable.
https://plnkr.co/edit/Wsje4CfmzfLDXebxlEUc?p=preview

* **ag-Grid version:** 17.1.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

The approach there seems to be a bit convoluted, I would suggest that you tried to achieve this by plainly specifying the rowClass on the gridOptions, not after the cell updated event,

In any case this would be a support request, so I am going to flag this as managed by the community

**Comment by koolhuman** [comment]
I am trying to set the rowClass for each row which has been edited, how can i achieve this by just plainly specifying the rowClass on the gridOptions? Any help would be appreciated. thank you!!

**Comment by makinggoodsoftware** [comment]
The key here is for you to use metadata for this, every time you update a row, update some metadata behind the scenes, and do so with our API

https://www.ag-grid.com/javascript-grid-data-update/

Then in you rowClass style the row based on the metadata.

Hope this helps
