### ISSUE TITLE
Copy cell functionality doesn't work for single item

### ISSUE THREAD

**Issue by DominicTobias** [ag-grid/ag-grid#2347]
Hi,

I've tested this on v14 and v17:

When trying to a copy a single cell (most common action), it copies the whole row. Only if I have `enableRangeSelection` and highlight more than one row does it produce desirable results.

How can I just copy the value of one cell? Thanks

**Comment by DominicTobias** [comment]
For now I've solved it like this:

```js
processCellForClipboard = (params) => {
    const rangeSelections = this.gridApi.getRangeSelections();

    // When there's only 1 cell highlighted, AG-Grid will copy the whole row
    // which is undesirable.
    if (rangeSelections.length === 1) {
      const rangeSelection = rangeSelections[0];

      if (
        rangeSelection.start.rowIndex === rangeSelection.end.rowIndex &&
        rangeSelection.start.column.colId === rangeSelection.end.column.colId &&
        params.column.colId !== rangeSelection.start.column.colId
      ) {
        return '';
      }
    }

    return params.value;
  }
```

**Comment by DominicTobias** [comment]
In the end I had to also override `sendToClipboard` to do a trim. And since ag-grid-enterprise doesn't export it's modules properly (requires `ag-grid/main` rather than `ag-grid`) I couldn't use ClipboardService but I have a better function for that which works better on mobile devices anyway:

```js
sendToClipboard = ({ data }) => {
  copyToClipboard(data.trim());
}
```

**Comment by rabindra-jpmc** [comment]
I am new to Angular. I have to implement some custom functionality on top of ClipboardService. Can anyone explain, how to override methods of ClipboardService?

**Comment by LordZombi** [comment]
You should also use `suppressRowClickSelection: true` to NOT select whole row but single cell.
Works like a charm.

**Comment by idlebrain2000** [comment]
Is this resolve in the latest ag-grid versions?

**Comment by ramakrim** [comment]
@joshmun thanks a lot, you gave me the final solution after several trials... Once again thank you...

**Comment by KrishKashiwala** [comment]
> Hi, you can override Ag-Grid's default functionality to copy the row to only copying selected range or cell by setting `suppressCopyRowsToClipboard = {true}` on the AgGrid Table component. Here's the documentation referring to this solution: https://www.ag-grid.com/javascript-grid-clipboard/#clipboard-example

great fix!!.
