### ISSUE TITLE
"exportDataAsCsv" not working with multiple Grid

### ISSUE THREAD

**Issue by djdu** [ag-grid/ag-grid#2350]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I have multiple Ag-Grid on the same page and exporting to CSV file, Ag-Grid only exporting last grid data.

**Expected behavior**

Ag-Grid should export the data that user clicked for.

**Minimal reproduction of the problem with instructions**

Place multiple Ag-Grid on the same page. All the grid should be able to export to CSV. Try to export the data from one of the grid, it will always export last grid's data.

**What is the motivation / use case for changing the behavior?**

I'm using multiple grids in the same page and all the grids are able to export to CSV file.

**Please tell us about your environment:**

Visual Studio 2017

* **ag-Grid version:** 17.1.0

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ReactJS 16.3.2 | TypeScript 2.6.2

**Comment by djdu** [comment]
It's not a bug. I figured it out.

**Comment by jitutest** [comment]
@djdu What is the fix can you explain , I want to do excel export for Multiple grid , Is there any way

**Comment by gurpreetsinghhora** [comment]
@djdu Can you help with the fix ?

**Comment by mrmaan4u** [comment]
You are call `onGridReady($event)` for all grids, and setting `this.gridApi = params.api;`
in result `this.gridApi` is set to last grid in your code, you need to set different variables than using `this.gridApi` for all grids.

**Comment by karthi-siva** [comment]
@djdu I am facing the same issue. What is the solution?
@mrmaan4u Thats fine different grids should have different gridapi variables but that will not have the solution. Can anyone explain or provide the working code?

**Comment by marciocamello** [comment]
I'm solve this problem with this

const gridInfo = {
    id: gridID,
    api: params.api,
    columnApi: params.columnApi,
};

params.api.addDetailGridInfo(gridID, gridInfo);

if(formBuilderExport?.formId === formId) {
    gridApi.getDetailGridInfo(gridID).api.exportDataAsExcel();
}

if(formBuilderExport?.formId === formId) {
    gridApi.getDetailGridInfo(gridID).api.exportDataAsCsv();
}
