### ISSUE TITLE
Cannot scroll vertically on firefox for grids with only pinned columns

### ISSUE THREAD

**Issue by stonecrafter** [ag-grid/ag-grid#2356]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Can't scroll vertically when grid has _only_ pinned columns, on the latest firefox. It works on chrome and safari, though.

**Expected behavior**
Should be able to scroll vertically on firefox too - or, at the least, the behaviour should be consistent.

**Minimal reproduction of the problem with instructions**
I just modified the example from [the docs](https://www.ag-grid.com/javascript-grid-pinning/#example-column-pinning), removed the extra functionality and made all the columns pinned.
https://plnkr.co/edit/iguphDmGCcuw1qgVRA8m?p=preview

If the grid columns are resized a bit such that there is some of the `ag-body-viewport` showing (its width is not 0), then scrolling works, but not if pinned columns cover the entire grid area.

**What is the motivation / use case for changing the behavior?**
Behaviour should be consistent across browsers.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** 17.1.1

* **Browser:**
Bug seen in: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0`
Bug not seen in: `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"`

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2150
Firefox - Can't scroll vertically when grid has only pinned columns
