### ISSUE TITLE
Tool Panel wrapper doesn't work well with domLayout="autoHeight"

### ISSUE THREAD

**Issue by kolevmarjan** [ag-grid/ag-grid#2364]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When `domLayout` is set to `autoHeight` the div with a class `ag-bl-east` which is a wrapper of the `ag-tool-panel` gets height depends on the height of the grid. Setting the height of `ag-bl-east` div enters in a loop and the height grows continuously. The bug is mostly reproducible on a big screen >1400px.

**Expected behavior**

Height should not grows continuously when `domLayout` is set to `autoHeight`

**Minimal reproduction of the problem with instructions**

I am resizing the screen in behind.
https://www.dropbox.com/s/guu63m9ouv0tpfm/Developer%20Tools%20-%20http___localhost_8080_%205_8_2018%2011_01_48%20AM.mp4?dl=0

* **Environment:** Angular 4.3

* **ag-Grid version:** 17.1.1

* **Browser:** Chrome

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

This whole feature got revamped in v19

https://www.ag-grid.com/javascript-grid-tool-panel/

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
