### ISSUE TITLE
Suppress Tool Panel

### ISSUE THREAD

**Issue by kolevmarjan** [ag-grid/ag-grid#2365]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

You can suppress only parts of the Tool Panel but not the whole Tool Panel. Even if you suppress all components inside Tool Panel, tool panel div still exists in the DOM and taking space.
```
toolPanelSuppressRowGroups
toolPanelSuppressValues
toolPanelSuppressPivots
toolPanelSuppressPivotMode
toolPanelSuppressSideButtons
toolPanelSuppressColumnFilter
toolPanelSuppressColumnSelectAll
toolPanelSuppressColumnExpandAll
```

**Expected behavior**

Single parameter for suppress the tool panel

**What is the motivation / use case for changing the behavior?**

Remove tool panel completely from the DOM

* **Environment:** Angular 4.3

* **ag-Grid version:** 17.1.1

* **Language:** TypeScript

**Comment by kolevmarjan** [comment]
Yes I know that. But the element still exists in the DOM. CSS is a solution but not the best one in this case.

**Comment by mikeszczygiel** [comment]
How to completely disable the tool panel from column, context menus & sidebar buttons?

Why is this enabled by default?

**Comment by makinggoodsoftware** [comment]
Hi,

This whole feature got revamped in v19

https://www.ag-grid.com/javascript-grid-tool-panel/

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
