### ISSUE TITLE
Can't edit and expand a single cell

### ISSUE THREAD

**Issue by PranKe01** [ag-grid/ag-grid#2366]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using cellRenderer group and editable true, the cell is not editable.

**Expected behavior**
When setting both, the cell shall be editable AND expandable.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/5O3TcID0ky603d0BqhMS
Try editing the first column. The children are editable and the root cells are not.

**What is the motivation / use case for changing the behavior?**
We need to edit the root nodes.

**Please tell us about your environment:**
Chrome.

* **ag-Grid version:** 14.1.1

Does not work on 17.0.0 :( Same problem here.

* **Browser:**
Browser independent!

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2130 | Editing - allow cellEditors to group rows | BACKLOG
-- | -- | --
