### ISSUE TITLE
groupSelectsFiltered bug in RowNode.selectChildNodes

### ISSUE THREAD

**Issue by jessicashin** [ag-grid/ag-grid#2373]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Selecting a group after filtering with `[groupSelectsChildren]="true"` and `[groupSelectsFiltered]="true"` selects child rows that are filtered out.

**Expected behavior**

Selecting a group should select only filtered rows when `[groupSelectsFiltered]="true"`

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/3Ll0gMwYpnMwfvmY0sDl?p=preview
Click "Filter Only Swimming" and then click the first checkbox for "United States". The selected row count is 899, which does not match the count of filtered rows for United States (145).

**What is the motivation / use case for changing the behavior?**

`groupSelectsFiltered` should only select filtered rows.

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.1

**Comment by makinggoodsoftware** [comment]
This was actually fixed in v18.1. Thanks.
