### ISSUE TITLE
API function that manually toggles context menu [on left-click]

### ISSUE THREAD

**Issue by namnn** [ag-grid/ag-grid#2376]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Context menu can only be triggered via right-click.

**Expected behavior**

GridApi to have a function to toggle context menu. Context menu can be opened on left-click

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

For designs with a special cell of toggling context menu on left-click, this is a missing hole. Also, for mobile view, this is a critical feature.

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
Context menu | AG-769 | [context menu] Allow the context menu to be invoked from GridApi
-- | -- | --
