### ISSUE TITLE
Need Floating Icon in Header Row

### ISSUE THREAD

**Issue by nsankaranarayanan** [ag-grid/ag-grid#2387]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have an ag-grid where I want to display a floating icon on top of the header row (possibly on the right hand side corner). The objective of this icon is for the user to be able to click and display a modal where they can customize the columns.
I am not expecting you to provide a column customization feature though it would be nice if you can provide that as well. I am looking for a way to display an icon on the right hand side corner of the header row.

**Expected behavior**
The current grid doesn't look like it supports this functionality.

**Minimal reproduction of the problem with instructions**
Use any regular ag-grid.

**What is the motivation / use case for changing the behavior?**
There may be multiple grids in a page and the floating icon on the header makes perfect sense.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, Node 9.3.0, NPM 6.0.0, Angular 4.x

* **ag-Grid version:** 17.1.0

* **Browser:**
Chrome, FireFox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.6

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
