### ISSUE TITLE
Increasing gap between search options in filter menu tab

### ISSUE THREAD

**Issue by DavidShusterman** [ag-grid/ag-grid#2389]
I'm using Ag-grid-enterprise and I'm troubling with increasing the gap between menu items in the search tab. for example :

![image](https://user-images.githubusercontent.com/16805596/40122768-3afd6a6a-592d-11e8-8706-4a0a0ac9f8bb.png)

The default gap between those items is 20px, and I want to override this and create something more like this :

proper gap
![image](https://user-images.githubusercontent.com/16805596/40122799-4cbf9e94-592d-11e8-9bbe-53e44657dbe5.png)

How do I achieve this? which classes I need to override? or any other solution.

Thanks for the help

**Comment by makinggoodsoftware** [comment]
Hi,

I would recommend you to create your own themes...

https://www.ag-grid.com/javascript-grid-styling/

In any case, Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, you should be able to find more information in the following links:

https://www.ag-grid.com/javascript-grid-value-handlers/

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
