### ISSUE TITLE
valueFormatter function is not getting called/applied for aggregated values 

### ISSUE THREAD

**Issue by praveenn-vbi** [ag-grid/ag-grid#2396]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Aggregated value is not getting formatted

**Expected behavior**

Aggregated values also get formatted using valueFormatter function

**What is the motivation / use case for changing the behavior?**

I am using default aggregation function  "sum" , the value are get aggregated but the aggregated value is not getting formatted.

**Please tell us about your environment:**

Not specific to environment
* **ag-Grid version:** 17.1.1

* **Browser:** Chrome

* **Language:** all

**Comment by fmarvez** [comment]
We're also running into this issue. We've tried to approach it from a few different angles such as creating our own aggregate functions but ran into the issue of not knowing the parameters of the custom formatting as we give our users a few options for the formatting of columns.

Is there any recommended way of using the valueFormatter function for the aggregated cells?

**Comment by makinggoodsoftware** [comment]
Hi,

I have just tried this on my end, and it seems to be working fine now

ie:
        valueFormatter: (params) => 'a ' + params.value

Please create a new issue if you don't think this is the case

Thanks

**Comment by tafia** [comment]
On my side, somehow it works for all `aggFun` but not for `avg`.
I am using version 20.2. I've tried using `valueFormatter` and `cellRenderer` but it didn't work.

**Comment by tafia** [comment]
Looks like the `value` is not a number but an object (at least in case of `avg`).
Using `Number(params.value)` looks to be working as expected.
