### ISSUE TITLE
Community issues completely ignored?

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#2400]
I got the feeling that community issues are now completely ignored? No reaction, answer, ...

**Comment by lvpro** [comment]
I miss the open and active forums.  I routinely found answers to questions that way.  If a new bug was discovered in a release, a fellow community member would usually post a workaround pretty quickly.  StackOverflow doesn't get near the action the old forums did.

**Comment by makinggoodsoftware** [comment]
Hi there,

This is Alberto from ag-grid... For a while we were overwhelmed giving support to customers so we couldn't really afford to also support github, but, we have build up the capacity to start also giving support here.

Note that this is happening as of roughly one week ago, and that we are actually trying to clean all the issues built up in the backlog

Hope this helps.

You should see us replying on Github from now

**Comment by makinggoodsoftware** [comment]
Hi guys,

I hope is obvious that we are now looking at issues here, I am going to close this one, but feel free to open a new one if you want to discuss further how we engage the community

Thanks
