### ISSUE TITLE
resetRowHeights() does not wort in autoGroupColumns

### ISSUE THREAD

**Issue by alexeykap** [ag-grid/ag-grid#2403]
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

**Current behavior**
When I set in autoGroupColumnDefs autoHeight=true and on event columnResized call api method resetRowHeights() rows height does not changed.

**Expected behavior**
row height changed to content height
**Minimal reproduction of the problem with instructions**
I have changed this Tree example https://plnkr.co/edit/ge3LDyUTUycyQKJJ0Wh5?p=preview that we can resize the columns, and rows resize by content height. If resize "Job Title" rows would be resize but if resize "Organization hierarchy" rows would not resize.
Here is demo: https://plnkr.co/edit/MoQymMy1xWFcGeQB3SwV?p=preview

**What is the motivation / use case for changing the behavior?**
Resize behaivior must be the same/

* **ag-Grid version:** 17.1

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2140 Auto height is not recalculated for the autogroupcolumn
