### ISSUE TITLE
how to show hide tool panel by button click from outside of  grid

### ISSUE THREAD

**Issue by sagarloona4180** [ag-grid/ag-grid#2408]
* **ag-Grid version:** 17.1.1

* **Browser:**
chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

![image](https://user-images.githubusercontent.com/29095795/40562902-816b4f30-6080-11e8-8e9a-850326f80307.png)

**Comment by makinggoodsoftware** [comment]
Hi,

Have a look at our new docs

https://www.ag-grid.com/javascript-grid-side-bar/#example-api

Also, if you are a customer, feel free to contact us directly via zendesk

Thanks
