### ISSUE TITLE
Ag-grid default filter is set to text filter

### ISSUE THREAD

**Issue by innov-richa76** [ag-grid/ag-grid#2409]
**I'm submitting an Issue regarding the default filters of Ag-grid**  (check one with "x")

**Current behavior**
All the AG-Grid filters are set as default filter as Text and we are unable to see the checkbox filters.

**Expected behavior**
It should be set to the checkbox filter

**Please tell us about your environment:**
IDE-VS Code

* **ag-Grid version:** X.X.X
enterprise version-13.0.x

* **Browser:**
Chrome, IE

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript:2.4.2

**Comment by maximusk** [comment]
If you're using an enterprise version, please create a support ticket in Zendesk

**Comment by makinggoodsoftware** [comment]
Hi,

I dont think you are using the enterprise version correctly, if you were, the default filter would be the set filter...

As Max, mention, feel free to follow up through zendesk

Thanks
