### ISSUE TITLE
Wrong/unformatted aggregated values getting displayed for sum.

### ISSUE THREAD

**Issue by RajendraDave** [ag-grid/ag-grid#2410]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Sum of numbers with two decimal digits is showing more than two digits after decimal.
![issue](https://user-images.githubusercontent.com/32572729/40622155-a5fe4134-628f-11e8-8f47-0e71d00d3591.png)

**Expected behavior**
Sum of numbers with two decimal digits should be number with two decimal digit.

**Minimal reproduction of the problem with instructions**
Steps to reproduce bug:
Go to plunker: [https://plnkr.co/edit/dnes1hImTOkSqJAFxD0w?p=preview](url)
Go to Columns and Drag Country to Row Groups and Gold to Values.
Check the value of sum for Country **India**.

**Please tell us about your environment:**
* **Operating System:** Windows: 8

* **ag-Grid version:** 17.1.1

* **Browser:** Firefox 47.0.2

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that this is a browser issue, if you open your console and type this 1.11 + 1.25, you will see:
1.11 + 1.25
2.3600000000000003

You can however add a formater to that column to guarantee that you always round numbers

https://www.ag-grid.com/javascript-grid-value-getters/

Thanks
