### ISSUE TITLE
Floating row data in grid when removing and adding rows through batchUpdateRowData api.

### ISSUE THREAD

**Issue by geekeng** [ag-grid/ag-grid#2414]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When all rows are removed and a few selected (among the removed ones) rows are consequently added through the batchUpdateRowData api function, the added rows are floating. More specifically they are drawn at their original location in the grid, before removing all the rows. I believe this may have something to do with the keepRenderedRows parameter in agGrid.

**Expected behavior**

All rows should always align to the top of the grid.

**Minimal reproduction of the problem with instructions**

To trigger the bug click the 'Remove all, then randomly add few' button in the following example: https://plnkr.co/edit/zELe8NVdPzciGFfhjOCN?p=preview

**What is the motivation / use case for changing the behavior?**

We have integrated ag-grid with our collection class in backbone. Adding and removing row data is done one by one in this class. When we fetch new data for example through a search, existing rows are removed one by one through the batchUpdateRowData api and then the search results are added one by one again through the batchUpdateRowData api. We encounter the bug when some of the data within the search results already existed in the grid before the search.

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.1

* **Browser:** Firefox

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2170. BatchUpdateRowData - Removing and re-adding rows with same id issue
