### ISSUE TITLE
Infinite scroll data source SHOULD implement data updaters

### ISSUE THREAD

**Issue by hparadiz** [ag-grid/ag-grid#2417]
**I'm submitting a ...** 
```
[x] feature request
```

**Current behavior**
![image](https://user-images.githubusercontent.com/195216/40803271-3df30b66-64e6-11e8-8370-ae0123154274.png)

Pretend this is a delete button onclick:
```js
IncentFitGrid.prototype.delete = function() {
    
    var gridOptions = this.gridOptions,
        selectedData = gridOptions.api.getSelectedRows(),
        ctx = this;

    
    if(selectedData.length<1) {
        alert('Please make a selection first.');
        return;
    }

    if(confirm('Are you sure you want to delete the selected record?')) {        
        var x;
        for(var i in selectedData) { /* todo: turn this into a promise that returns when all are done */ 
            x = ctx.store.delete(selectedData[i]);
            x.then(function(response) {
                ctx.refresh();
            });
        }
    }
}
```

```js
IncentFitDataSource.prototype.delete = function(row) {
    var requestParams = {
        action: 'delete',
        body: row
    }, ctx = this;
    return new Promise(function(resolve, reject) {
        ctx.UnifyAPI.Request(ctx.service, requestParams, null, 'POST').then(function (response) {
            return resolve(response);
        });
    });
}
```

```js
IncentFitGrid.prototype.refresh = function() {
    this.gridOptions.api.setDatasource(this.store);
}
```
So here after my custom coded delete method fires on the DataSource object I have to force a manual refresh. The manual refresh only works by resetting the data source object on the entire grid.

Why is this bad? Well for one what if I deleted something on page 500? It should not need to force a refresh at all.

**Expected behavior**
Delete or update on an infinite scroll data source should remove or update the row currently being deleted / updated. Optionally it should fire datasource.getRows() on the current page.

**What is the motivation / use case for changing the behavior?**
My mind is blown that I have to write this boiler plate stuff custom. This is basic functionality that ExtJS has been able to do since 2011.

I'm seriously regretting choosing ag-grid for this project because of this.

* **ag-Grid version:** X.X.X
Most recent.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
