### ISSUE TITLE
Disable/Enable autoheight programmatically

### ISSUE THREAD

**Issue by giniedp** [ag-grid/ag-grid#2418]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We can enable autoheight for a column at design time by specifying it in the `columnDefs`. However the columnApi provides no companion function to disable or enable that feature at runtime.

Hidden columns with active autoheight are not ignored and affect the total row height.

**Expected behavior**
columnApi should have a function to enable / disable the autoheight feature at runtime. Or hidden columns (with autoheight) should not affect the total row height.

**What is the motivation / use case for changing the behavior?**
Having some columns that can be toggled on and off by the user i'd like the hidden columns to not affect the total row height. I can do that by using custom getRowHeight function. But i am forced to full row height when using autoheight feature.

* **ag-Grid version:** 17.1.1

**Comment by sivakanda** [comment]
Any updates on this issue. I'm facing the same issue. Hidden column affecting the row height.

**Comment by sivakanda** [comment]
Fixed this issue temporarily myself, by "nullifying the Column Field Data which we intent to HIDE (OR we can remove the field itself from the Grid Data), and assign the data back to that field, when we intent to show the same column back. 

Grid seem to adjust the row height based on the data in this case.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-1591 | Allow delta changes to columns | IN PROGRESS |   |  
-- | -- | -- | -- | --

**Comment by giniedp** [comment]
@makinggoodsoftware what is the current status of this issue? I cant find it at the ag-grid-pipeline.

**Comment by giniedp** [comment]
This is still unresolved in 20.0.0

https://stackblitz.com/edit/issues-ag-grid-autoheight
