### ISSUE TITLE
Grouped row displays wrong value for aggregation function

### ISSUE THREAD

**Issue by joshchambers94** [ag-grid/ag-grid#2419]
**I'm submitting a ...** 
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When grouping data and displaying grouped rows, using the first aggregation method to display the value in the grouped row is incorrect when any columns are sorted to either ascending or descending order.

**Expected behavior**

When column sorting is applied the value that is displayed on the grouped row should be updated to display the value of the node of the first child row.

**Minimal reproduction of the problem with instructions**
You can experience the same issue by following the steps below using the ag-grid demo (https://www.ag-grid.com/example.php) by:
1)	Filter to show only Swedish language
2)	Group by Language column by dragging to top
3)	Aggregation function for Rating is average
4)	Aggregation function for Total Winnings is first
     a.	See that the first ungrouped row reads the same as the grouped row above
5)	Sort Bank balance to ascending
     a.	See that the first ungrouped row no longer matches the grouped row

**What is the motivation / use case for changing the behavior?**

Require the values displayed in the grouped row to be consistent with the ordering of the data in the rows below.

* **ag-Grid version:** 17.0.0

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-1870 - Aggregation - Grouped row displays wrong value for aggregation 1st function
