### ISSUE TITLE
Balham-dark theme icons not changing color - provided workarounds aren't successful

### ISSUE THREAD

**Issue by geoffhuntoon** [ag-grid/ag-grid#2422]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using the balham-dark theme with Sass, the icons are black and their color cannot be changed. Similar issues have been posted, but the workarounds/solutions in them have not been successful (for me, at least). Changing $icon-color does not work, and neither does overriding the .ag-icon class using a CSS filter as mentioned in a comment in #2151.

**Expected behavior**

Changing $icon-color or overriding .ag-icon should change the color of the icons.

**Minimal reproduction of the problem with instructions**

`/* ag-grid variable overrides */
// These are fine and reference other variables
$ag-icons-path: '../node_modules/ag-grid/src/styles/balham-icons/';
$background-color: $dark-button;
$header-background-color: $dark-background;
$odd-row-background-color: $input-background;
$secondary-foreground-color: $small-text;

// Neither of these work
$icon-color: $other-variable;
.ag-icon {
  // Hue-rotate 180deg from black is white?
  filter: hue-rotate(180deg) !important;
}

@import '~ag-grid/src/styles/ag-grid';
@import '~ag-grid/src/styles/ag-theme-balham-dark';
`

**Please tell us about your environment:**

- Windows 10
- NPM 6.1.0

* **ag-Grid version:** X.X.X

- ag-grid 17.1.1
- ag-grid-angular 17.1.0

* **Browser:**

I'm only developing for Chrome at the moment, and it's happening in Version 66.0.3359.181.

**Comment by geoffhuntoon** [comment]
I just customized the SVG icons manually and that works for me.

**Comment by 0rvar** [comment]
Please do not close an issue just because you found a manual workaround - this is still a very real issue and should work out of the box

**Comment by geoffhuntoon** [comment]
My apologies - customizing the SVG icons manually was one of the described workarounds in another issue, and I believe that issue had been resolved. I will reopen as I would like the default icon colors to change!

**Comment by rfestag** [comment]
I'm having the same issue as well. When I use the ag-theme-balham-dark.css from the dist directory, I see that the icons are data URLs. However, when I use SASS instead, I get a URL straight to the SVG, which does not go through a color transform. I'm curious how the css files in the dist directory are generated, and whether there is a way to emulate that behavior.

On a potentially related note, I'm finding that not all variables from the theme are actually being honored. For instance, I have to manually set the $border-color variable to the same value that *should* be defaulted ag-theme-balham-dark.scss

In my case a subset of the relevant SASS is:

```scss
//My variables
$button-inactive-color: #545d62;
$button-hover-color: #b6c0c3;
$accent-color: orange;
$menu-bar-bg: #13191c;
$banner-bg: #29353b;
$split-bg:#13191c;
$split-size: 8px;
$split-border: #29353b;

//AG-Grid variables
$icons-path: "~ag-grid/src/styles/balham-icons/";
$border-color: #424242; //This shouldn't be necessary, but somehow is. Beware of the generic name 

//Bootstrap overrides
$body-bg: #0f1416;
$body-color: #bcc6c9;
$enable-rounded: false;
$component-active-color: $accent-color;
$secondary: #13191c;
$active: $accent-color;
$nav-tabs-link-active-color:  #13191c;
$nav-tabs-link-active-bg: $accent-color;
$nav-tabs-link-hover-border-color: $accent-color;
$nav-tabs-link-active-border-color: $accent-color;
$nav-tabs-link-hover-color: #29353b;

@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "ag-grid/src/styles/ag-grid.scss";
@import "ag-grid/src/styles/ag-theme-balham-dark.scss";
```

**Comment by cwhaught** [comment]
I am seeing a similar issue.

As soon as I start importing the scss files, as opposed to the css files, the $accent-color is ignored for svg icons.

**Comment by cwhaught** [comment]
I did some further investigation into the issue for my project and the example Angular Material project appears to work but is a but disingenuous in my opinion.

That project located at https://github.com/ag-grid/ag-grid-material defines a column and checkbox renderer in order to use Angular Material's theme variables in order to override the icon color, not ag's variables. 

This obviously severely limits how to use the grid api as publish as the developer now has to handle all rendering of icons, instead of depending on ag-grid to do that for me as the documentation indicates.

**Comment by Eiarzate1** [comment]
Finally figured out a way to override your the theme SVG icon's color without having to create a whole new set of SVG icons. You don't have to create a brand new theme as well.
By the way a lot of the themes have this $icon-color parameter, but this parameter is not being used at all by the svg implementations. Therefore don't try it.

Sample scss file would like this.

```
//overwrite all the variables you want.. etc etc...

//The order you import the theme is very important
//Import the themes first
@import '~ag-grid/src/styles/ag-theme-bootstrap.scss';
@import '~ag-grid/src/styles/ag-grid.scss';

//Then overwrite the icon-background mixin like such:
@mixin icon-background( $icon) {
  -webkit-mask: url("#{$icons-path}#{$icon}.svg") no-repeat center;
  mask: url("#{$icons-path}#{$icon}.svg") no-repeat center;
  -webkit-mask-size: contain;
  mask-size: contain;
  background-color: white;
  background: white;
  background-size: 14px 14px;
  display: inline-block;
}

/* icons are used outside of the grid root (in the ghost) */
$icons: aggregation arrows asc checkbox-checked-readonly checkbox-checked checkbox-indeterminate-readonly checkbox-indeterminate checkbox-unchecked-readonly checkbox-unchecked
  column columns contracted copy cut desc expanded eye-slash eye filter group indeterminate left loading menu minus none not-allowed paste pin pivot plus right small-left
  small-right small-up small-down tick cross tree-open tree-closed tree-indeterminate;

@each $icon in $icons {
  //replace .ag-theme-bootstrap with target theme.
  .ag-theme-bootstrap .ag-icon-#{$icon} {
      @include icon-background("#{$icon}");
  }
}
```

I also posted the solution on [https://github.com/ag-grid/ag-grid/issues/1982](url)

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you very much for that solution! We are going to close the issue now.

Note that we are hoping to revamp the themes in the next 2/3 releases and make its configuration and documentation easier and better

Thanks for your help

**Comment by aryanisml** [comment]
> Finally figured out a way to override the theme SVG icon's color without having to create a whole new set of SVG icons. You don't have to create a brand new theme as well.
> By the way a lot of the themes have this $icon-color parameter, but this parameter is not being used at all by the svg implementations. Therefore don't try it.
> 
> Sample scss file would like this.
> 
> ```
> //overwrite all the variables you want.. etc etc...
> 
> //The order you import the theme is very important
> //Import the themes first
> @import '~ag-grid/src/styles/ag-theme-bootstrap.scss';
> @import '~ag-grid/src/styles/ag-grid.scss';
> 
> //Then overwrite the icon-background mixin like such:
> @mixin icon-background( $icon) {
>   -webkit-mask: url("#{$icons-path}#{$icon}.svg") no-repeat center;
>   mask: url("#{$icons-path}#{$icon}.svg") no-repeat center;
>   -webkit-mask-size: contain;
>   mask-size: contain;
>   background-color: white;
>   background: white;
>   background-size: 14px 14px;
>   display: inline-block;
> }
> 
> /* icons are used outside of the grid root (in the ghost) */
> $icons: aggregation arrows asc checkbox-checked-readonly checkbox-checked checkbox-indeterminate-readonly checkbox-indeterminate checkbox-unchecked-readonly checkbox-unchecked
>   column columns contracted copy cut desc expanded eye-slash eye filter group indeterminate left loading menu minus none not-allowed paste pin pivot plus right small-left
>   small-right small-up small-down tick cross tree-open tree-closed tree-indeterminate;
> 
> @each $icon in $icons {
>   //replace .ag-theme-bootstrap with target theme.
>   .ag-theme-bootstrap .ag-icon-#{$icon} {
>       @include icon-background("#{$icon}");
>   }
> }
> ```
> I also posted the solution on [https://github.com/ag-grid/ag-grid/issues/1982](url)

Icons changes only with chrome browser it not worked with edge or IE browser.

**Comment by sleeplesseditor** [comment]
> Finally figured out a way to override the theme SVG icon's color without having to create a whole new set of SVG icons. You don't have to create a brand new theme as well.
> By the way a lot of the themes have this $icon-color parameter, but this parameter is not being used at all by the svg implementations. Therefore don't try it.
> 
> Sample scss file would like this.
> 
> ```
> //overwrite all the variables you want.. etc etc...
> 
> //The order you import the theme is very important
> //Import the themes first
> @import '~ag-grid/src/styles/ag-theme-bootstrap.scss';
> @import '~ag-grid/src/styles/ag-grid.scss';
> 
> //Then overwrite the icon-background mixin like such:
> @mixin icon-background( $icon) {
>   -webkit-mask: url("#{$icons-path}#{$icon}.svg") no-repeat center;
>   mask: url("#{$icons-path}#{$icon}.svg") no-repeat center;
>   -webkit-mask-size: contain;
>   mask-size: contain;
>   background-color: white;
>   background: white;
>   background-size: 14px 14px;
>   display: inline-block;
> }
> 
> /* icons are used outside of the grid root (in the ghost) */
> $icons: aggregation arrows asc checkbox-checked-readonly checkbox-checked checkbox-indeterminate-readonly checkbox-indeterminate checkbox-unchecked-readonly checkbox-unchecked
>   column columns contracted copy cut desc expanded eye-slash eye filter group indeterminate left loading menu minus none not-allowed paste pin pivot plus right small-left
>   small-right small-up small-down tick cross tree-open tree-closed tree-indeterminate;
> 
> @each $icon in $icons {
>   //replace .ag-theme-bootstrap with target theme.
>   .ag-theme-bootstrap .ag-icon-#{$icon} {
>       @include icon-background("#{$icon}");
>   }
> }
> ```
> 
> I also posted the solution on [https://github.com/ag-grid/ag-grid/issues/1982](url)

It is not working on version of IE11
