### ISSUE TITLE
Multiple selection mode and ctrl+click deselect

### ISSUE THREAD

**Issue by badpunman** [ag-grid/ag-grid#2426]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ctrl+click on selected row does nothing.

**Expected behavior**
ctrl+click in select multiple mode deselects the row if it's selected

**Minimal reproduction of the problem with instructions**
https://www.ag-grid.com/javascript-grid-selection/

**What is the motivation / use case for changing the behavior?**
it's quite standard.

**Please tell us about your environment:**
chrome etc.

* **ag-Grid version:** X.X.X
17

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by rars** [comment]
There's a `rowDeselection` property that can be set to `true` that enables this behaviour:

> rowDeselection: Set to true to allow rows to be deselected if you hold down Ctrl and click the row. By default the grid disallows deselection of rows (i.e. once a row is selected, it remains selected until another row is selected in its place).

[documentation](https://www.ag-grid.com/javascript-grid-selection/)
