### ISSUE TITLE
Apply button does not ignore debounceMs

### ISSUE THREAD

**Issue by knock-in** [ag-grid/ag-grid#2427]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When enabling the apply button with the apply filter parameter the default debounce time of 500ms is used. So if you write something and press the apply button before the 500ms have passed the change won't be noticed by the filter component.

**Expected behavior**
The debounce time should be ignored if the apply button is activated, which was intended as you can see at line 340 inside baseFilter.ts but there are two problems with the current check.
1.) applyButton seems to be an old parameter which is nowhere mentioned in the current documentation so it'll always be null. For backwards compatibility the basefilter should use the applyActive parameter to check if the apply button is enabled.
See line 109 inside the same file.
2.)  If debounceMs was not set by the user it'll be undefined and in this case the expression `filterParams.applyButton && filterParams.debounceMs` cannot ever be true.

**Minimal reproduction of the problem with instructions**
1. Enable apply button on a text filter
2. Type something into the filter input field and press Apply immediately
3. As you can see the filter didn't notice the change

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 17.1.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

* **Language:** all

**Comment by rmc-software** [comment]
This issue has now been fixed. Thanks.

**Comment by rmc-software** [comment]
This issue has now been fixed thanks.

**Comment by knock-in** [comment]
Yeah.. It totally has not been fixed yet

**Comment by rmc-software** [comment]
Reopening to investigate further if issue has been resolved.

**Comment by rmc-software** [comment]
Reopened to investigate	further. Thanks.

**Comment by makinggoodsoftware** [comment]
Hi,

In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.

Could you update the ag-grid version in your end and try again?

Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved

Thanks
