### ISSUE TITLE
No rows overlay position bug

### ISSUE THREAD

**Issue by chertkovalex** [ag-grid/ag-grid#2429]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

"No rows to show" overlay message is positioned incorrectly. It's above a column headers. When choosing theme **ag-theme-material** on ag-grid. 
It's centered by height on the whole grid (including headers). That's why, when headers' height is changed, the overlay message appears above headers.

**Expected behavior**
Overlay message should be positioned correctly on the empty space below the table headers. 
It should be centered by height on the empty line.

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE*
https://plnkr.co/edit/Ohdt0BTEloDcyzdKwfgQ?p=preview

- In index.jsx:
`<div
          id="myGrid"
          style={{
            boxSizing: "border-box",
            height: "100%",
            width: "100%"
          }}
          className="ag-theme-material"
        >`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 18.0.0

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"

* **Language:** [[ES6/7/React]]

**Comment by saidoze** [comment]
+1 I'm having the same issue.

**Comment by makinggoodsoftware** [comment]
Hi,

This is how we think this feature should work. note that you can create your own overlays

Feel free to open a new issue if you think we are being unfair by closing this one, thanks

**Comment by undeadborn** [comment]
Same issue here, but i'm facing it on IE11. Chrome displays the overlay in the correct way.
Creating custom row overlay didn't help.

**Comment by harikrishnan-u01** [comment]
I am also facing the same issue in IE 11. Chrome and Firefox is displaying the No rows overlay in the center of the grid. But IE 11 is displaying the No rows overlay on top of the grid header. 

Why is this issue closed?

Is there any work around?

**Comment by ostar0816** [comment]
@harikrishnan-u01 I had a same problem today. I believe this will be fixed with other IE 11 issues in the next release but please try with my temporary solution in the meantime:
`.ag-overlay {
  .ag-overlay-panel {
    .ag-overlay-wrapper {
      display: flex;
      height: 100%;
      align-items: center;
      justify-content: center;
    }
  }
}
`

**Comment by RubeenaBegum** [comment]
:host >>> .ag-overlay-no-rows-wrapper {
  padding-top: 5em;
}
