### ISSUE TITLE
valueFormatter breakes if enableRowGroup set to true

### ISSUE THREAD

**Issue by cMeIIIHo** [ag-grid/ag-grid#2430]
Example code:
https://plnkr.co/edit/OVVJPKQTMK5sypbVx5Tf?p=preview

Steps to reproduce:
1. Drag 1st column header to "Drag here to set row groups"
2. You will see that "Formatted" column has wrong values.
http://prntscr.com/julacu

**Comment by makinggoodsoftware** [comment]
Hi,

I have just tried the plunker on my end, and I did not get any error, can you please try again in your end?

I am going to close this issue now, but if you think this is still not working, please feel free to create a new issue
