### ISSUE TITLE
[Feature request] GridPanel and toolPanelComp access methods

### ISSUE THREAD

**Issue by choisel** [ag-grid/ag-grid#2433]
Hello everyone,

While working on a project where we had these feature requests
- Save a load the grid columns configuration (width, visibility)
- Resize columns to fit only if the columns width is less than the grid panel width
- Display the toolpanel in edit mode, and hide it in view mode.

I had to use the gridPanel private property to be able to access the getWidthForSizeColsToFit (this way I don't have to make the math between the grid width, the toolpanel width (opened or not), the vertical scroll bar width) to fulfill the 2nd requirement.
I also had to access the private toolPanelComp to have the setVisible method to fulfill the 3rd requirement.

This issue is a feature request to have the following methods.
- isColumnsFitContent(), which will return false if the displayed columns don't fit the gridPanel
- show/hideToolPanel, to show and hide the tool panel comp.

Sorry if this is not the way to request a feature.

**Comment by raneshu** [comment]
You might want to have a look at this: https://github.com/ag-grid/ag-grid/issues/1188

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
