### ISSUE TITLE
Replacement for onGridSizeChanged / GridSizeChangedEvent in ag-grid 18

### ISSUE THREAD

**Issue by philly-vanilly** [ag-grid/ag-grid#2440]
In Ag-Grid 18, onGridSizeChanged became deprecated with no further notice how to get the old functionality now:

>     // deprecated
>     onGridSizeChanged?(event: any): void;

onGridSizeChanged was very useful for calling the size-to-fit-method and saving the column state so you can quickly initialize the grid again, when you switch from another view:

>     if (this.gridOptions) {
>       this.gridOptions.api.sizeColumnsToFit();
>       const columnStatesAtWidth: ColumnStatesAtWidth = {
>         columnStates: this.gridOptions.columnApi.getColumnState(),
>         width: window.innerWidth
>       };
>       this.saveColumnState$.emit(columnStatesAtWidth);
>     }

Do I have to subscribe to native DOM-element resize events now to get this functionality back?  Why was the method removed?

**Comment by pshurygin** [comment]
As a workaround for this i'm now using css-elements-queries library to detect grid size changes like described in this answer:
https://stackoverflow.com/questions/6492683/how-to-detect-divs-dimension-changed

**Comment by GiacomoVoss** [comment]
I am also having this problem, and I can't even use the window.resize event since I'm developing a browser-based desktop layout with windows. When the window inside the browser tab gets resized, I want the grid to fit the columns. What do I do now?..

**Comment by whiteblackkeys** [comment]
Keep the version 17

**Comment by makinggoodsoftware** [comment]
Hi,

This has been reintroduced in v19, so you should be able to upgrade now

Hope this helps

**Comment by bjnst6** [comment]
I can confirm this is true; I have just upgraded from 18.0.0 to 18.1.0 and the functionality is back.

**Comment by jpike88** [comment]
@makinggoodsoftware the typescript definitions still show onGridSizeChanged as a deprecated function.

**Comment by j-a-h-i-r** [comment]
@jpike88 I can confirm this too. The typescript definitions in ag-grid 23.2.1 shows it is depreceated.

**Comment by jlokiec** [comment]
In ag-grid-community v24.1.0 it is still marked as deprecated. Also, the event type is `any` despite the fact that there is an appropriate type for it (`GridSizeChangedEvent`).
Are you planning to fix this soon?
