### ISSUE TITLE
ag-grid 18.0.1 appears blank on iPhone Safari

### ISSUE THREAD

**Issue by mikeszczygiel** [ag-grid/ag-grid#2441]
When upgrading from 17.1.1 -> 18.0.1, ag-grid does not appear on iPhone iOS 10.2

Example:
17.1.1: https://9canada.com/ag-grid-17-1-1
18.0.1: https://9canada.com/ag-grid-18-0-1

**Comment by haithemT** [comment]
this issue is related to the migration to flexbox.
if you upgrade to ios 11 it will work without issues.

**Comment by makinggoodsoftware** [comment]
Hi,

That is correct, with the new Safari it all should work fine

Thanks

**Comment by TanujKumarReddyD** [comment]
I have imported free version of ag-grid in my project, but it is not loading in ag grid. can someone help with this?

Safari version 12
"ag-grid": "^18.1.1",
"ag-grid-angular": "^18.1.0"

angular cli version is 5

**Comment by MrWeb** [comment]
> I have imported free version of ag-grid in my project, but it is not loading in safari. can someone help with this?
> 
> Safari version 12
> "ag-grid": "^18.1.1",
> "ag-grid-angular": "^18.1.0"
> 
> angular cli version is 5

Did you solve it?

**Comment by bburns** [comment]
Make sure all the elements containing the ag-grid have height: 100% - if some are controlled with flexbox the grid might not show on iOS. I added height: 100% to a flexbox div and it works now.
