### ISSUE TITLE
Overriding the checkbox icons for selected rows does not change the corresponding header icon.

### ISSUE THREAD

**Issue by BrianHVB** [ag-grid/ag-grid#2442]
There does not appear to be any way to easily override or change the style of the select/unselect all checkbox that appears in the header when the `headerCheckboxSelection` column option is enabled. This means that the style of the checkbox will be at odds with the checkbox style for the individual rows if that style is customized.

Here is an example column configuration that replaces the row checkboxes with an alternative from Font Awesome:

```javascript
			{
				headerName: '', field: 'checkbox',
				width: 35,
				headerCheckboxSelection: true,
				checkboxSelection: true,
				suppressMenu: true, suppressFilter: true, suppressNavigable: true,
				icons: {
				 	checkboxChecked: '<i class="fa fa-check-square-o"/>',
				 	checkboxUnchecked: '<i class="fa fa-square-o"/>',
				 	checkboxIndeterminate: '<i class="fa fa-square-o"/>',
				}
			},

```

This problem also occurs to a lesser extent even when using the default checkbox style for rows. On the `bootstrap` theme, for instance, the header checkbox is visually different than the row checkboxes. (image attached)

![checkbox_screenshot](https://user-images.githubusercontent.com/17414903/41563415-bf71eade-730c-11e8-8495-228177a4075c.png)

The [documentation](https://www.ag-grid.com/javascript-grid-icons/) on customizing icons does not list the header checkbox as one of the items that can be modified.

It seems that it would be possible to change the icon style using a custom HeaderComponent, but then all of the functionality of the check/uncheck all would have to be recreated by hand.

**Comment by BrianHVB** [comment]
added image

**Comment by BrianHVB** [comment]
As a workaround, I used jQuery to manually replace the HTML for the header checkbox states. If anyone is interested, here is the code I used:

Manually changing the DOM in a managed component is bad in any framework, especially React, but this seems the simplest solution.

Interestingly, I also found in the documentation a [code sample](https://www.ag-grid.com/example-runner/react.php?section=javascript-grid-icons&example=icons&fontawesome=1&enterprise=1&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Atrue%7D) which did use the icon property to change the checkbox icons to ones from Font Awesome. The sample shows the header checkboxes being overridden, but it used column groups and not just regular columns.

```javascript
checkboxIcons = {
	checked: '<i class="fa fa-check-square-o"/>',
	unchecked: '<i class="fa fa-square-o"/>',
	inteterminate: '<i class="fa fa-minus-square-o"/>',
};
...
ColumnDefinitions: [
		{
			field: 'checkbox',
			width: 40,
			headerClass: ['header-check'],
			headerCheckboxSelection: true,
			checkboxSelection: true,
			cellClass: ['cell-check'],
			suppressMenu: true, suppressFilter: true, suppressNavigable: true,
			icons: {
				checkboxChecked: this.checkboxIcons.checked,
				checkboxUnchecked: this.checkboxIcons.unchecked,
				checkboxIndeterminate: this.checkboxIcons.inteterminate,
			}
		},
]

...

componentDidMount() {
	// replace header checkbox
	$(".ag-header-select-all .ag-checkbox-checked").html(this.checkboxIcons.checked);
	$(".ag-header-select-all .ag-checkbox-unchecked").html(this.checkboxIcons.unchecked);
	$(".ag-header-select-all .ag-checkbox-indeterminate").html(this.checkboxIcons.inteterminate);


```

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
