### ISSUE TITLE
Custom filter on first time click on the menu  overflowing out of the grid

### ISSUE THREAD

**Issue by Nithinds10388** [ag-grid/ag-grid#2443]
Click on last column the custom filter overflow out of the Grid. second time it stays inside the grid.

When checked first time click left: 1200 px some thing, second time it is 1100px.

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template it is going to be closed, but feel free to open another one following the template.

Thanks
