### ISSUE TITLE
Footer with aggregations

### ISSUE THREAD

**Issue by snuuve** [ag-grid/ag-grid#2444]
Please tell me how to make grid footer with aggregations? I can't find this option. Only saw `pinnedBottomRowData `.

Ps. We pay so much money and there is no typical Support for Ag-grids from your side :/ On stackoverflow noone is answering our questions...

https://stackoverflow.com/questions/50908433/ag-grid-footer-aggreations
https://stackoverflow.com/questions/50908956/ag-grid-fit-columns-to-content-and-wrap-headers-text

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
