### ISSUE TITLE
How to get Header checkbox selection Event 

### ISSUE THREAD

**Issue by virenderk91** [ag-grid/ag-grid#2448]
How to get Header checkbox selection Event in ag-grid table. I want to perform some action if I am select the header checkbox if there is any solution please help

**Comment by deepender87** [comment]
you can place your custom checkbox on header and clicking on that can perform any logic. All you need is CSS help.

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks

**Comment by JabbyPanda** [comment]
Just listen to `selectionChanged` [event](https://www.ag-grid.com/javascript-grid-events/ ) at grid level to apply some action per selection changed by column header checkbox

**Comment by cb03037** [comment]
I created a ticket for this:
https://ag-grid.zendesk.com/hc/en-us/requests/6537
