### ISSUE TITLE
ServerSide DataSource - SortModel `colId` is actually `field`.

### ISSUE THREAD

**Issue by MetaFight** [ag-grid/ag-grid#2449]
When using a ServerSide DataSource and handling a `getRows` call, the `request.sortModel` field is an array of `{ colId: string, sort: string}`.

One would expect `colId` here to match the one in Column Definitions, but it doesn't.  It is, instead, the `field` value of the corresponding Column Definition.

Please fix.

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template it is going to be closed, but feel free to open another one following the template.

Thanks
