### ISSUE TITLE
Updating Data in Another Grid Doesn't Reflect on the Original 

### ISSUE THREAD

**Issue by NeilLister** [ag-grid/ag-grid#2451]
I have a very unique page where I am using two tabs to display data. While the data in both grids is slightly different, the data in grid #2 is very similar to the data in grid #1. I have a scenario where I am updating a record in grid #1, which causes the record to be moved into grid #2, but then when I update that same record again in grid #2, the values in my edit columns aren't being reflected in grid #1. 

This only happens when I update the same record twice.

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template it is going to be closed, but feel free to open another one following the template.

Thanks
