### ISSUE TITLE
AutoHeight + 1000 rows + Large Number of Columns

### ISSUE THREAD

**Issue by sfug** [ag-grid/ag-grid#2453]
I have a grid with 20+ columns that is populated with 1000+ rows. It's required to use autoHeight. Performance is acceptable when scrolling vertically, but when scrolling horizontally it takes up to 10 seconds to get the columns rendered due to column virtualisation.

I've disabled column virtualisation and this does improve the overall experience when scrolling horizontally. The grid, however, is laggy.

I'm opening this issue to get some advice on how to proceed in scenarios like these - where using autoHeight is mandatory due to requirements. I do understand there's a warning in the documentation's Grid Size page stating that there's not much that can be done.

There's a feature request in [#2343](https://github.com/ag-grid/ag-grid/issues/2343) which, if implemented, would be helpful. The idea would be to use the window as the viewport. I tried to do it myself but ran into all sorts of errors. If anyone has ever tried to implement this, please share some advice.

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template it is going to be closed, but feel free to open another one following the template.

Thanks
