### ISSUE TITLE
v18 event gridSizeChanged no longer exists

### ISSUE THREAD

**Issue by jjurczewsky** [ag-grid/ag-grid#2455]
What happened to this event?  Is there a replacement to this event?

I use this event extensively to dynamically manipulate columns.  I don't understand why this event would be removed.

**Comment by MetaFight** [comment]
My guess is the switch to CSS Flex layout rendered the event obsolete.  (See first item in v18 [release notes](https://github.com/ag-grid/ag-grid/releases/tag/18.0.0))

**Comment by whiteblackkeys** [comment]
I used it too to call sizeColumnsToFit.

`  onGridSizeChanged: event => {
    event.api.sizeColumnsToFit();
  },
`

**Comment by whiteblackkeys** [comment]
Duplicates of #https://github.com/ag-grid/ag-grid/issues/2440

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template it is going to be closed, but feel free to open another one following the template.

Thanks
