### ISSUE TITLE
Feature request: rotated table, i.e. each record shown vertically as a column (rather than a horizontal row)

### ISSUE THREAD

**Issue by hi2u** [ag-grid/ag-grid#2456]
Currently a rowNode is always displayed horizontally, i.e. each "record" is one row, and the columns are the fields.  

In situations where there are many fields, but not many records, this layout is unusable.  Take for example:

* Product comparison tables: https://media.nngroup.com/media/editor/2017/02/24/keurig.png
* Pricing/plan tables: https://www.cloudflare.com/plans/#compare-features ...there are only 4 records (plans), but there's about 60 fields (ignore the fact than you need to expand each section first, not relevant to this)

Of course for static data (and simple situations like above) you can just rearrange your data before passing it to ag-grid, but it is troublesome when you need to update one or more fields in a single record... because ag-grid will always updates the entire horizontal row regardless of your actual data model.  i.e. If all the fields in one record change, this means the entire grid needs to refresh every row one at a time, regardless of only one column needing to change.  

It also means that it's hard to make use of valueGetters/formatters etc that access data from other fields within the record... because as-is `params.data` isn't a single record in this case, its a single field and the values of that field alone for all of the records.  Not to mention, many of the other great features of ag-grid basically become unusable for these types of grids.  

And you can't easily add a new record to the grid dynamically, you instead need to loop through all the rowNodes and instead create a new "field" (for what is actually a record).

It would be great if there were an option to still be able to treat each record as a single rowNode object, each with a single `data` object, but just have the display of table rotated sideways so that each record appears as a column instead of a row.

Just to clarify, this has nothing to do with any kind of aggregation.  I'm just talking about the appearance of the actual records.

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
