### ISSUE TITLE
Question: making only certain cells editable, not the whole column, how?

### ISSUE THREAD

**Issue by luminescent** [ag-grid/ag-grid#2458]
Hi 

First of all thank you for the `ag-grid`, it's fantastic 👍.  

I have a situation where only certain cells from a column need to be editable, the rest have to be read only. To complicate matters further, the read only status depends on values from other columns. Is there a way to mark just certain cells as editable instead of the whole column?

FYI, currently I have achieved that by basically hacking together a solution with a controlled crash. I mark the whole column as editable, and I am using the `cellEditorSelector` event handler and returning a non existent component for the read only cells, and a proper component ( `agTextCellEditor`) when the cells in the column allow changes. This behaves as desired at run time - obviously the crash is visible in Developer Tools, but non technical users won't know about it. Hopefully there is a proper way to achieve that?

Thank you

**Comment by thirtydot** [comment]
You should be able to figure it out from this:
https://stackoverflow.com/a/47464480/405015

Let me know if you need more help.

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
