### ISSUE TITLE
Only get first cell data on onGridReady of Detail

### ISSUE THREAD

**Issue by giraud-d** [ag-grid/ag-grid#2459]
**Current behavior**

On this exemple of documentation : https://www.ag-grid.com/javascript-grid-master-detail/#example-simple-master-detail

onGridReady event only get the first data cell of the row

![aggrid-ongridready-only-first-item](https://user-images.githubusercontent.com/15327857/41784134-137f5fa0-763f-11e8-9558-103043d3784d.PNG)

My problem is that I want to `autoSizeColumns(allColumnIds)`.
Thus only first cell is correctly auto-size.

**Expected behavior**

I would like to be able to get all data rows to auto size correctly all my cells.
Or to be able to auto size my cells on another way.

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template it is going to be closed, but feel free to open another one following the template.

Thanks
