### ISSUE TITLE
AgFilterComponent onNewRowsLoaded never called

### ISSUE THREAD

**Issue by dragouf** [ag-grid/ag-grid#2462]
I made a component filter in angular 6 with ag-grid 18.0.1 and I want it to reload each time data are loaded (filter display a list based on data). Unfortunately onNewRowsLoaded is never fired. 

Is there a thing to do to activate it's call ?

**Comment by LiamDotPro** [comment]
I believe you can trigger this using the gridApi, though a simpler approach may be to just call `this.gridApi.purgeEnterpriseCache();` Which will reload all of the available items. You could of course use a service injected in angular 6 that uses a behavior subject that all of your components listen to for actions though this can be quite costly if you have a lot of components. You could also refresh the cell or row if you setup methods that take the row index and then go and deal with each individually. If you provide a MCVE I could get back to you with some help.

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
