### ISSUE TITLE
Not working on old browsers

### ISSUE THREAD

**Issue by flupine** [ag-grid/ag-grid#2464]
Hello, 

When i try to load ag grid on old browsers like IE 11 i obtain a blank page but not on latest version of firefox, chrome, opera etc....

**Comment by LiamDotPro** [comment]
Why version of the grid are you using? If your using Angular, React or Vue some features of the grid will not work.

**Comment by flupine** [comment]
I have fixed it by adding a lib for compatibility (the error is due to fetch function not supported by browser).
