### ISSUE TITLE
Custom formatted tooltip not displayed correctly since v17

### ISSUE THREAD

**Issue by azold** [ag-grid/ag-grid#2465]
Hi,

When I want to display a custom formatted tooltip its not displayed correctly since version 17 as its partially covered by the next rows. 
With v16 the tooltip displayed correctly, but with v17 or abouve it looks like something went wrong.

Here is a sample to reproduce: https://plnkr.co/edit/sAYCMYmK04DNMIRXvonf?p=preview
The code use ag-grid v18, but I leave there the src for v17 and v16 if you would like to check that versions too.

Here is how it looks like with v18:
![image](https://user-images.githubusercontent.com/37046575/41855287-888b368e-7892-11e8-957a-9b85aa12224d.png)

And with v16:
![image](https://user-images.githubusercontent.com/37046575/41855521-258d26f4-7893-11e8-9f5a-adc213fbe228.png)

**Expected behaviour**
Display the custom formatted tooltip with its full width and height and all the text within as in v16.

**Comment by biliktamas79** [comment]
+1

**Comment by RodSmithAG** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-1754 | Rendering - tooltip element showing behind the grid

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
