### ISSUE TITLE
Quick Fix?: border missing on pinned cells

### ISSUE THREAD

**Issue by dimitropoulos** [ag-grid/ag-grid#2466]
Problem: borders around a pin boundary are not showing in any theme.

here is an example of a selected cell in a column pinned on the left (demonstrating the bug):
![image](https://user-images.githubusercontent.com/15232461/41859112-6f3c8b7a-7869-11e8-8ca7-a4ab9ead1f39.png)

here is an example of the same selected cell in an unpinned column (which looks as you would expect with a right border):
![image](https://user-images.githubusercontent.com/15232461/41859274-dd4873fe-7869-11e8-8b02-cf65ba9c16fa.png)

steps to reproduce:
1. go to https://www.ag-grid.com/example.php#/
2. pin any column to the left
3. select a cell in that column

note:

- if you pin more than one column only the one touching the "pin boundary" will exhibit this bug.
- both left and right pinning have this problem.
- it is much more pronounced/noticeable in a dark theme.

**Comment by ceolter** [comment]
fixed, will be in next relase

**Comment by dimitropoulos** [comment]
wow! that was fast! thanks! :)

**Comment by harsha521** [comment]
I have few columns on left and few columns with no pinned and few columns on right border not coming for right pinned
