### ISSUE TITLE
doesFilterPass not being triggered in onFIlterChanged customfilter

### ISSUE THREAD

**Issue by dexterslabaratory** [ag-grid/ag-grid#2469]
In AngularJS, have a customFilter  (using `infinite` rowmodeltype
) with default floating custom filter by implementing getModelAsString.

When ever the text changes (change, paste, events) I am triggerring the onFilterChanged and onFilterModified

But doesFilterPass()/setModel() is not getting called.

Also every other mandatory IFilterComp are getting called. and doesFilterAppy is true.

Any samples with both customFilter and default floating filter

**Comment by LiamDotPro** [comment]
Can you make a small reproduce able example? plunker stackblitz etc you can use an example from the ag grid website to start from.

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
