### ISSUE TITLE
Ag-grid with Vuex

### ISSUE THREAD

**Issue by cLupus** [ag-grid/ag-grid#2470]
Hi,
While using ag-grid with Vue, I run in to a problem when using a cell renderer / editing a cell.
When I change a value in the grid, ag-grid tries to change the value directly in my vex store, which causes an error, and makes it hard to ensure that all the data in the SPA is consistent.

Is there a way to tell ag-grid to dispatch an action instead of changing the data directly?

**Comment by LiamDotPro** [comment]
If your instance of ag grid is instantiated directly in your state then this will always happen, if you want it to call a method you can either register a custom component with it's own set of actions or use a value setter with a callback. Could you provide a MCVE and I could try to narrow down something to help you :-)

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
