### ISSUE TITLE
If all records loaded use client side sort

### ISSUE THREAD

**Issue by yehudahkay** [ag-grid/ag-grid#2471]
Hi, thanks for the amazing grid!

We are using the server side grid. Once all records are loaded could the grid use client side sorting 
 (and filtering) rather than server side? It would be faster and help our server load.

**Comment by LiamDotPro** [comment]
The sorting is done on the clientside for a couple of the different models, for instance if your using just pagination or the standard model you will have clientside sorting and filtering be default. In the enterprise row model or rather as it's called now the serverSide model is supposed to be used with pagination via either infinite scroll or with pagination. Both of which generally require further calls to the server for more information when the amount of items set are less than the set of available items.

Essentially why you don't want client sorting is the following scenario:

I Initially load 30 items of an available 300 items, there ordered by id. Now when I sort by id I'm expecting to find record 300 as this has the furthest away index and I know this as my gird is telling me how many items it can load using the count.

but in your scenario your just flipping the 30 available items which is unexpected behavior.

**Comment by yehudahkay** [comment]
In your example, once you've loaded all 300 rows, then there is no need to return to the server for sorting and filtering. That's what I would like the grid to do. Currently it continues to return to the server.

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
