### ISSUE TITLE
Ag-init for cell renderer not updating the data

### ISSUE THREAD

**Issue by deepender87** [ag-grid/ag-grid#2472]
I am facing a very strange issue with cell-renderer.

I have a cell-renderer for my grid component. I am opening this component as a modal popup.

There are two ways to open this popup.

1) On Div item click. 
2) On dragging this div item to some xyz position and dropping it.

In both ways the popup is getting opened. The only issue is whenever i am using the 2) option the data is not getting updated in the cell renderer.(this cell renderer is a drop-down). If i further click anywhere on the popup the data appears.

Further i debug and found when i use the 1) option (means click and open the popup) agInit fires twice for that cell-renderer, but when I use the 2) option (Means dragging and dropping) agInit fires only once and when i click anywhere on the popup agInit fires one more time, resulting to show the data.

I am not able to understand this behaviour, please help me out.

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
