### ISSUE TITLE
New rows are inserting at end of the grid by using 'updateRowData' irrespective of given index specified.

### ISSUE THREAD

**Issue by munigopalkummara** [ag-grid/ag-grid#2473]
Environment : "ag-grid": "12.0.0"   @angular: 4.1.2
* I tried to add a new row to the grid at particular index. by using below code
   var res = this.gridOptions.api.updateRowData({
                    add: [newRow],
                    addIndex: 5
                });
* Result : New row is added at end of all rows.
* Expected : Need to add at given index
   for example if i had 10 rows, I want to add a new row at 5th position. But it added at 11th position.

can you please suggest any idea.

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks

**Comment by bburns** [comment]
This might be relevant - https://github.com/ag-grid/ag-grid/issues/2089
