### ISSUE TITLE
feat: Vuex support

### ISSUE THREAD

**Issue by cLupus** [ag-grid/ag-grid#2474]
Hi,
Is there a plan at add an example (as was [done with redux for React](https://www.ag-grid.com/react-redux-integration/)), or support for using `Immutable Store` with [Vuex](https://vuex.vuejs.org), as part of your [Vue.js](https://vuejs.org) support?

**Comment by jcgalindo** [comment]
+1

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
