### ISSUE TITLE
SelectAll checkbox behavior

### ISSUE THREAD

**Issue by LittleHendrix** [ag-grid/ag-grid#2475]
Currently, the `headerCheckboxSelection` allows the user to select/deselect all rows, and if individual rows have already been selected clicking on the 'select all' will first select all rows and then deselect them. 

My question is with individual rows selected initially, by clicking on the 'select all' checkbox, can I *deselect* the existing rows (like how g-mail works)? Rather than selecting all the remaining rows and then deselect them all on 2nd click. 

Thank you!

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
