### ISSUE TITLE
Infinite scroll load 10 (e.x.) Rows instead of 100?

### ISSUE THREAD

**Issue by Vvaltz** [ag-grid/ag-grid#2476]
Hi, I'm a completely dumbfounded, could anyone please point me to the right direction?
I follow the example: https://www.ag-grid.com/javascript-grid-infinite-scrolling/#simple-example-no-sorting-or-filtering 
It works ok
I change the only thing - "paginationPageSize: 100" -> "paginationPageSize: x". x = anything, doesn't matter, doesn't work, e.x. (x = 25): https://plnkr.co/edit/U0o5WRBPphQr7bae5fx1?p=preview

a) Did I misunderstand paginationPageSize ?
b) Is it possible via a simple config line to change infinite scroll loading to e.x. 25, 200, etc?
c) if "paginationPageSize" does not work with infinite scroll, please remove from example? Wasted a lot of time
d) I've tried looking into getRows(params) params ->  params.endRow seems always to be 100, maybe there is a time where I could set this ?

Sorry if duplicate, have a nice day

**Comment by Vvaltz** [comment]
Welp I never found how the limit stuff works, but as I work with React, I did this In my constructor:

`this.state = {
	getRows: function(params){
		params.endRow = pageLimit;
	}
}`

and then when redefining getRows in my datasource it seems to have my desired effect.

**Comment by ranjithartler** [comment]
What is the correct approach to resolve this issue? I'm also facing the [issue](https://stackoverflow.com/questions/55162091/ag-grid-infinite-scrolling-paginationpagesize-not-working-in-reactjs)
