### ISSUE TITLE
[Row grouping]: Disable other groups' child checkboxes when some group's children are selected (or entire group)

### ISSUE THREAD

**Issue by viaches** [ag-grid/ag-grid#2478]
Hi guys,

So the desired behavior I want to have is the next one:

Suppose we selected some (or all) items in the first group. Is it possible to have red-pointed checkboxes (leafs) as disabled and green-pointed checkboxes (leafs) still enabled (to have the possibility to change the group selection)
![ag_example](https://user-images.githubusercontent.com/7974405/42094708-4856c036-7bb9-11e8-9aa4-7aefccd2f1e5.jpg)

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
