### ISSUE TITLE
Ag-Grid- Master/Detail - Detail row data on the last row always moves to the next page if using pagination - Master/Detail to display additional information for certain rows.

### ISSUE THREAD

**Issue by CopaMundial2018** [ag-grid/ag-grid#2480]
**Issue** - If pagination is turned on, the last detail section/child data row moves to the next page instead of being displayed with the parent row in the same page.
I have tried other methods of displaying additional data using "FlowerNodes" or "Group nodes", but all produce the same display as above. It seems Ag-Grid is considering the child row/detail row a separate row instead of being part of the parent row.

**Expected Behavior**
Ag Grid should render the detail section within the same page as the master section.

**Code snippet -**

` <div>
        {this.state.transactionUpload.fileUploadLog != undefined && transactionUpload !== undefined &&
          <div>
          {this.renderDataExportButton(transactionUpload !== undefined)}  

          <FileUploadLogData {...this.state.transactionUpload} />

            <div style={{ height: 800 }} className="ag-fresh">
              {this.state.isLoading && <Spinner />}
            <AgGridReact
              masterDetail={true}
              detailRowHeight={20}
              detailCellRendererParams={this.state.detailCellRendererParams}
              //detailCellRendererFramework={ErrorDetail}
             
                columnDefs={this.state.columnDefs}
                columnTypes={(columnTypes as any) as IndexableColDef}
                animateRows
                rowData={transactionUpload.transactions}
               
                paginationPageSize={20}
                getRowHeight={this.getRowHeight}
               
                onGridReady={this.onGridReady}
                
                pagination
                enableColResize
                enableFilter
                enableSorting
                suppressMovableColumns/>
            </div>
          </div>
        }
      </div>

interface ITransactionsState {
  isLoading: boolean
  transactionUpload: IUploadLogResult
  importStatusPerRecord: IImportStatusPerRecord[]
  columnDefs: Readonly<ColDef>[]
  detailCellRendererParams: GridOptions
}

export function getDetailGridOptionsForErrors(records: UploadTransaction[]): GridOptions {
  {
    let ret: GridOptions =
      {
        columnDefs: [{ field: "errorMessage" }],
        onGridReady:function (event: GridReadyEvent) {
          event.api.sizeColumnsToFit();
        },
        rowData: records,
      
      };
    return ret;
  }
}
`

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, you should be able to find more information in the following links:

https://ag-grid.zendesk.com/hc/en-us/articles/360005065952-Pagination-FAQ

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
