### ISSUE TITLE
gridApi.forEachNode typing is missing index argument

### ISSUE THREAD

**Issue by cytrowski** [ag-grid/ag-grid#2481]
I see that rowModel.forEachNode can accept 2 args: rowNode and index. I believe it would be good idea to add it into the gridApi interface since it is missing:

```typescript
    public forEachNode(callback: (rowNode: RowNode)=>void ) {
        this.rowModel.forEachNode(callback);
    }
```

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
