### ISSUE TITLE
How to make a general comparator in Angular/Typescript.

### ISSUE THREAD

**Issue by koreem** [ag-grid/ag-grid#2482]
I want to make a general comparator that I can use in different grids in different angular components. 
How can I achieve this? I used the example below to use a date comparator. As you can see, this comparator is declared outside the MyComponent class. I tried to declare this comparator in a service and inject the service inside this component, but then I always get a error that the **monthToComparableNumber** function is not declared. Why can't I declare my comparator functions inside the class it self?

```
import { Component } from '@angular/core';

@Component({
//component info
})

export class MyComponent {
  private columnDefs = [
    {
      headerName: 'aHeader',
      field: 'aField',
      comparator: dateComparator,

    }];
  constructor() {}
}

function dateComparator(date1, date2): number {
  const date1Number = monthToComparableNumber(date1);
  const date2Number = monthToComparableNumber(date2);
  if (date1Number === null && date2Number === null) {
    return 0;
  }
  if (date1Number === null) {
    return -1;
  }
  if (date2Number === null) {
    return 1;
  }
  return date1Number - date2Number;
}

function monthToComparableNumber(date): number {
  if (date === undefined || date === null || date.length !== 10) {
    return null;
  }
  const yearNumber = date.substring(6, 10);
  const monthNumber = date.substring(3, 5);
  const dayNumber = date.substring(0, 2);
  const result = yearNumber * 10000 + monthNumber * 100 + dayNumber;
  return result;
}


```

**Comment by mike-packetwerk** [comment]
@koreem what happens if you declare `monthToComparableNumber` inside `dateComparator`? maybe it will work.

**Comment by koreem** [comment]
@mike-packetwerk Thanks, this works. Now I can even put it in a service. Still not very clean, but it's something.
