### ISSUE TITLE
How to make inner cell renderer in Angular/Typescript?

### ISSUE THREAD

**Issue by denniske** [ag-grid/ag-grid#2483]
I am trying to make a `CellRenderer` in angular that takes an `innerCellRenderer` as parameter and uses it like the `GroupCellRenderer`:
https://stackoverflow.com/questions/51154897/ag-grid-angular-cell-renderer-inject-cellrendererservice

How can I do this?

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
