### ISSUE TITLE
Row borders disappear on MS Edge when hovering over

### ISSUE THREAD

**Issue by ghost** [ag-grid/ag-grid#2485]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When hovering from bottom to top on Edge the borders on the rows hovered over seem to vanish. A scroll or click will bring them back. This has been previously mentioned here: https://github.com/ag-grid/ag-grid/issues/1186

**Expected behavior**

The borders should not vanish when hovering the mouse from bottom to top. 

**Minimal reproduction of the problem with instructions**

This can be re-produced on the ag-grid demo website https://www.ag-grid.com/javascript-grid-styling/ on the Structure Example section.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows, Edge browser

* **ag-Grid version:** 17.1.1

(However not sure what version the demo website is running but I assume it would be the latest one)

* **Browser:** Edge/16.16299

* **Language:** ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2137
When hovering from bottom to top on Edge the borders on the rows hovered over vanish

**Comment by makinggoodsoftware** [comment]
Hi,

This looks like a MS issue

 https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7119159/

We are going to close it from our end
