### ISSUE TITLE
AgGridReact  - (params) argument in colDef/cellEditorParams function not having context property

### ISSUE THREAD

**Issue by raneshu** [ag-grid/ag-grid#2488]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

context is passed as a prop to AgGridReact like so( `<AgGridReact context={{name: 'sampleName'}} .... />`
But context is not showing in params argument of cellEditorParams for any col definitions.

Eg: 
```
...
cellEditorParams: function(params) {
            console.log(params.context) // undefined
            ...
          }
```

I want to access context like so: `params.context `(but context is undefined)
However a hack like this seems to work: `params.api.gridOptionsWrapper.getContext()` 

The hack doesn't look very clean and I'd rather not use it.

**Expected behavior**

If context is passed in as a prop to AgGridReact , the params argument in the cellEditorParams function should contain the context property
**Minimal reproduction of the problem with instructions**
1. Look at this plunkr: https://plnkr.co/edit/5XLEct9TBcRP3xUugxLn?p=preview
2. Open console
3. Click on any cell in city column
4. You will see 'undefined' in console (whereas 'sampleName' is expected because we passed context={{name: 'sampleName'}} prop into the AgGridReact component)

**What is the motivation / use case for changing the behavior?**

I need to access to the context object from params.
A hack like so: params.api.gridOptionsWrapper.getContext() seesm to work
But I don't want to use gridOptionsWrapper because, as I understand, it's an internal method and probably prone to frequent change. Also the hack doesn't look clean.

**Please tell us about your environment:**
IDE: VSCode
Package manager: npm

* **ag-Grid version:** 18.1.0, 17.X.X, and prior

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript/ES 2017

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2135
Ensure we correctly merge all params (including context) when a user supplies a params callback
