### ISSUE TITLE
React numeric cell editor not inputting correct values.

### ISSUE THREAD

**Issue by Iysoni** [ag-grid/ag-grid#2493]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When inputting a new value, previous cell value is not cleared  so the number gets appended to the end. Backspace and delete keys do not work so there is no way to input a correct value.

**Expected behavior**
Inputting a new value should replace the previous value. Backspace and delete keys should work.

**Minimal reproduction of the problem with instructions**
Bug reproduced with the example editor from this link.
https://www.ag-grid.com/javascript-grid-cell-editor/#example-cell-editing-using-react-components

**Please tell us about your environment:**

Win10 

* **ag-Grid version:** Latest.

* **Browser:** Chrome 67

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2136 Fix bug on React numeric cell editor in docs
