### ISSUE TITLE
Master Detail ag-grid example with get or post service call in Angular 5

### ISSUE THREAD

**Issue by kummohan** [ag-grid/ag-grid#2495]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have tried to use below link to understand Master Detail grid functionality for lazy load in ag-grid (enterprise version 17.1.1) but couldn't succeeded with service call.
https://www.ag-grid.com/javascript-grid-master-detail/#lazy-load-detail-rows

Exactly what i want to acheive:
If i will click on expand button then data should come from service through http.post method and render into the grid.

**Expected behavior**
Need a proper example with http.get or http.post service call to render the child grid.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
To load data lazy way.

**Please tell us about your environment:**
We are using Angular 5 with NPM.

* **ag-Grid version:** X.X.X
17.1.1 Enterprise version

* **Browser:**
Chrome

* **Language:** ES6

**Comment by RodSmithAG** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, you should be able to find more information in the following links:

https://www.ag-grid.com/javascript-grid-master-detail/

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
