### ISSUE TITLE
Treedata on columns

### ISSUE THREAD

**Issue by derblitz** [ag-grid/ag-grid#2496]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently it seems only to be possible to use treedata on rows but not on columns.

**Expected behavior**
It should be possible to use a hierarchy with nodes that have different depths and put them in the columns of the grid. This already works for rows.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
I want to put one or more dimensions of a multidimensional cube into the rows and columns of the grid. The dimensions very often have parent-child hierarchies which means they don't have a fixed number of levels.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
18.1.1

* **Browser:**
N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
