### ISSUE TITLE
Error occurs setting sortModel prior to calling setServerSideDataSource when rowModelType='serverSide'

### ISSUE THREAD

**Issue by antmdvs** [ag-grid/ag-grid#2497]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Calling `setSortModel` prior to `setServerSideDataSource` causes the following error:

> ag-Grid.Context: >> ag-Application Context ready - component is alive
ag-grid.js:7939 ag-Grid.BalancedColumnTreeBuilder: Number of levels for grouped columns is 0
ag-grid.js:26438 ag-Grid -> initialised successfully, enterprise = true
**serverSideRowModel.js:120 Uncaught TypeError: Cannot read property 'sortModel' of undefined**
    at ServerSideRowModel.onSortChanged (serverSideRowModel.js:120)
    at eval (ag-grid.js:3111)
    at Array.forEach (<anonymous>)
    at Function.Utils.forEachSnapshotFirst (ag-grid.js:1495)
    at EventService.dispatchToListeners (ag-grid.js:3106)
    at EventService.dispatchEvent (ag-grid.js:3089)
    at SortController.dispatchSortChangedEvents (ag-grid.js:12158)
    at SortController.setSortModel (ag-grid.js:12245)
    at GridApi.setSortModel (ag-grid.js:6068)
    at GridExample.onGridReady (index.jsx:67)

Possibly related to #793?

**Expected behavior**
No errors.

**Minimal reproduction of the problem with instructions**

Using the *React* Plunk found in the docs here https://www.ag-grid.com/javascript-grid-server-side-model/#example-simple, ADD the following statement on line 66 of index.jsx (immediately following `this.gridColumnApi = params.columnApi`):

```javascript
    this.gridApi.setSortModel([{ colId: 'age', sort: 'asc' }])
```

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** 18.1.1

* **Browser:**

  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
  - Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; wbx 1.0.0; rv:11.0) like Gecko
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

* **Language:** ES6

**Comment by antmdvs** [comment]
Bug confirmed:
AG-1942 - Error when setting sortModel before server side datasource is set

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-1942 - Error when setting sortModel before server side datasource is set

It is estimated for our next release

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by Maximaximum** [comment]
I'm facing this issue right now. Seems like a regression.

```
    "@ag-grid-community/all-modules": "^25.2.0",
    "@ag-grid-community/angular": "^25.2.0",
    "@ag-grid-enterprise/all-modules": "^25.2.0",
```
