### ISSUE TITLE
 How do I create a new row when copying & pasting from an ag grid?

### ISSUE THREAD

**Issue by kowooho** [ag-grid/ag-grid#2501]
I want to create a new line instead of the selected cell when I try to copy and paste the clipboard function.

Is there an option to do this?
Please let me know how:

Please understand that even if the sentence is not smooth because of Google translation.

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
