### ISSUE TITLE
[Bug] Tooltip is not getting displayed for boolean value 'false' and number value '0'

### ISSUE THREAD

**Issue by paritosh64ce** [ag-grid/ag-grid#2505]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Tooltip is not getting displayed for boolean value `false` and integer value `0`

**Expected behavior**

As we have provided `tooltipField: 'boolVal'` or `price`, and as it is getting displayed for `price` value other than `0` and `boolVal` other than `false`, it should also work for them.

Check the code in the plunk I have provided:

in `ColDef`
    {headerName: "Price", field: "price", **tooltipField: 'price'**},
    {headerName: "Boolean", field: "boolVal", **tooltipField: 'boolVal'**}

And in `data`
    {make: "Toyota", model: "Celica", **price: 0, boolVal: false**}

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/IztgFrso17uNooFN5Skn?p=preview

1. Open preview.
2. Hover over the fields of `Price` and `Boolean` column.
3. Values `32000`, `74000`, `true` are having the tooltip, while `0` and `false` are not.

**What is the motivation / use case for changing the behavior?**

I think this is a bug

**Please tell us about your environment:**: Windows 7, VSCode, npm, IIS

* **ag-Grid version:** 17.1.0, issue is also there in v18.1.1

* **Browser:**: Chrome & IE11

  - Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36  
  - Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; wbx 1.0.0; rv:11.0) like Gecko

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by paritosh64ce** [comment]
Do check the PR I've submitted.

**Comment by gportela85** [comment]
fixed by https://github.com/ag-grid/ag-grid/commit/96ca828ae9c03f6332398fd98fd5357d253e052f

**Comment by evalaidc** [comment]
Has this been resolved? I am trying to use it with a custom tooltipComponent (tooltipComponentParams:....) but agInit isn't running when the params.value is "false" or '0'.
