### ISSUE TITLE
server side row model - how to set columnDefs when using successCallback?

### ISSUE THREAD

**Issue by raptoria** [ag-grid/ag-grid#2507]
I am using the server side row model with ag-grid. 
My data endpoint is designed in such a way that when getRows is called, I will always receive the new rows, the last row and new columnDefs. Unfortunately, there doesn't seem to be a way to pass these new columnDefs along with the successCallback. The way I'm handling it now means the grid will re-render twice, which I'd like to avoid. When getRows() is called, it makes a fetch to my endpoint which calls successCallback with the data and lastRow (this causes one render). Then, I have to pass the new columnDefs I get from a request as props to my GridContainer. This causes another render. Ideally, I'd like to only have one render. Is there a way to pass my new columnDefs along with the successCallback or an alternative better way of doing this? 

thanks!

AG Grid V 18.1.1

**Comment by RodSmithAG** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks

**Comment by anatoly314** [comment]
@raptoria have you solved your issue? I have the same problem as you and looking for a realible solution. Thank you.

**Comment by raptoria** [comment]
Unfortunately I couldn't find an elegant solution other than creating a side effect when I know new columnDefs are about to be returned from the latest grid interaction. This side effect re-renders the grid with the new columnDef props and then calls getData manually to get the latest data. I had some use cases where I wanted to intercept getData because it was called when I didn't want/need it so I handled this by running some special logic before the successCallback.

**Comment by anatoly314** [comment]
I'd have a similar solution except that when I called `setColumnDef` it causes to fetch getRows once again and I entered an infinite loop. I solved it by using `suppressEnterpriseResetOnNewColumns`. I turn it on before calling  `setColumnDef` from within `getRows` and turn it off after as advised in this thread https://stackoverflow.com/questions/52321185/ag-grid-server-side-row-model-infinite-getrows-loop-in-angularjs-1-x
