### ISSUE TITLE
[feature request] Ability to customize tool panel

### ISSUE THREAD

**Issue by raptoria** [ag-grid/ag-grid#2508]
It would be nice if I had the ability to customize the tool panel, ie. supply a custom tool panel renderer

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-1885 | Tool Panel - allow the user to provide their own components for the tool panel | BACKLOG

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
