### ISSUE TITLE
ColumnDefs with a point in the header

### ISSUE THREAD

**Issue by SidaouiBilel** [ag-grid/ag-grid#2511]
Hi

Imagine I have a list of headers. exemple: [name,age,country,etc....]

Now imagine one of those headers is "age.country" (focus on the point in the header) 

the grid will never show the data realated to the header "age.country". It will show any thing except when the headerName has a point in it.

Please I need a solution asap

**Comment by pranshu1995** [comment]
Use _suppressFieldDotNotation_ property in your gridOptions.
https://www.ag-grid.com/javascript-grid-properties/

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
