### ISSUE TITLE
Cell Drag Down Feature

### ISSUE THREAD

**Issue by pahaz** [ag-grid/ag-grid#2512]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**

What about an easy way to update multiple cells by dragging from the drag handle of an editable cell. It is a very user-friendly feature for users with excel experience.

Example from `react-data-grid`: http://adazzle.github.io/react-data-grid/#/examples/cell-drag-down

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
