### ISSUE TITLE
Unable to set height of container for detail grid

### ISSUE THREAD

**Issue by KristopherTadlock** [ag-grid/ag-grid#2516]
**I'm submitting a ...**  (check one with "x")
[X] feature request

**Current behavior**
When using the master/detail grid features, there is no method for setting the height of the container that holds the detail grid. It is always a fixed height. There is nothing in the master/detail documentation that provides for a method to set the height of a detail grid. 

**Expected behavior**
The height of the detail grid should be set relative to its contents or to a fixed height supplied by the detail grid options. 

1) fixed height. The detail grid will fill the space and provide a vertical scrollbar if required.
2) Size to fit. The detail grid will be given as much room as it needs to display its full contents without scrolling. 
3) Size for page. The detail grid will be given enough room to display a full page worth of data and a pagination. 

**What is the motivation / use case for changing the behavior?**
I have a need to display detail rows for a complex dataset. The detail grid has multiple layers of column groupings. It is possible to have several layers of similar detail grids. With the current sizing, I am unable to display more than two rows of data in the provided space. 

* **Language:** 
Angular

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, you should be able to find more information in the following links:

https://www.ag-grid.com/javascript-grid-master-detail/#detail-row-height

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
