### ISSUE TITLE
Unique IDs for Grid rows

### ISSUE THREAD

**Issue by pranshu1995** [ag-grid/ag-grid#2517]
**I'm submitting a ...**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Hi Team. 
I am working on an application and all my workflows are dependent on the dynamic data filled in the AG-Grid. 
To test my application, I am using Record and Playback testing using this tool : https://testcafe.devexpress.com/
Now the problem is that when selecting the row(s) from AG-Grid during playback the tool couldn't recognise the HTML element since there is no particular ID for the selected row(s). 
As mentioned in this blog : https://testsigma.com/blog/why-is-record-and-playback-not-suitable-for-enterprise-class-test-automation/
For Record and Playback test cases, the a Unique Attribute is needed for identification, otherwise it'll use the X-path ( which is not reliable).
The X-path generated for the selected row is quite long and complex : 

`body > div:nth(0) > div:nth(2) > div:nth(0) > div:nth(0) > div:nth(8) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(1) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(1) > div:nth(1) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(2) > div:nth(0) > div:nth(0) > div:nth(0) > span:nth(0) > span:nth(1) > span:nth(0)`

Due to which, many a times the tool fails to recognise it and the test fails.

**Expected behavior**

If some Unique attribute like ID can be associated with each row, then it'll be easy for the tool to identify them and the tests will pass.
Maybe the ID can be passed by user as a parameter of gridOptions or Parent div's ID can be used like :
 **Parent ID** : Grid1
**Row ID** : Grid1-1, Grid1-2, etc

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Workflow testing fails as the Grid elements are not found even when they are present.

**Please tell us about your environment:**

* **ag-Grid version:** 15.0.0

* **Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

* **Language:** All

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
