### ISSUE TITLE
AngularJS Programatically selecting rows and getSelectedRows is empty

### ISSUE THREAD

**Issue by W4775** [ag-grid/ag-grid#2518]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using isSelectable and making a row uncheckable with a checkbox but programatically selecting that record and getting selected row count shows up as empty. 

**Expected behavior**
Selecting a row programatically with the isSelectable set to false should still increment the selectedRow count.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/vKXd6IfDSl80ClUGO64m?p=preview

Set up checkbox selection/header selection. Make a single row or multiple rows as unselectable via the isSelectable gridOption.

Programatically select the unselectable option. 

Check the selectedRow array.

**What is the motivation / use case for changing the behavior?**
Use case is to have a row that is always checked and unselectable

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
v18

* **Browser:**
Chrome, IE

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by W4775** [comment]
Just as an update. I updated the plunkr with what I am currently using to determine what is selected. I have to run a ForEachNode loop and check for if the row is selected. Not the best solution but it works in the meantime.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

After some investigation, we suggest that if  do not want a checkbox, but yet still want the row to be selectable, then they should use the function variant of the coldef property checkboxSelection

So instead of:
```
gridOptions.isRowSelectable = function(rowNode) {
  return rowNode.data ? rowNode.data.id != 1 : false;
}
```

Should be:
```
colDef.checkboxSelection = function(params) {
  return params.data ? params.data.id != 1 : false;
}

Note that we are going to close this issue now, if you want to follow up, please create a new issue in github, thanks
