### ISSUE TITLE
[ADA Accessibility] Using arrow keys to navigate between column headers and down through body cells

### ISSUE THREAD

**Issue by mattography** [ag-grid/ag-grid#2522]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A visually impaired user is unable to navigate between column header cells with arrow keys. Along with this, the user is unable to use the up and down arrow keys to move between the column header cells and body cells. 

**Expected behavior**

A visually impaired user of the grid should be able to navigate between the column header cells with the left and right arrow keys, as well as from the header column cells to the body cells. This added feature will add to AG-Grid compliance with ADA accessibility, and make it even more attractive to other Enterprise License customers as well. 

**Minimal reproduction of the problem with instructions**
As an example of navigating through header cells and body cells with arrow keys:
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/grid/dataGrids.html#ex2_label

**What is the motivation / use case for changing the behavior?**
I work for a large financial institution which is in the process of upgrading a number of its trading applications to comply with ADA Accessibility requirements. We are using the Enterprise License version of AG-Grid in React and a user will be unable to navigate between the column headers using the arrow keys.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
14.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React 16.4

**Comment by ajkandy** [comment]
Just to add a vote for this: We're evaluating several different frameworks for data grids and not having ADA-compliant keyboard navigation as described in @mattography's ticket is a bit of a deal breaker for clients that require it. Tab navigation also does not let you enter the grid; I expected to enter the data cells after tabbing through the header cells, but it jumps to the sidebar area, and then back to the page nav. Hope to see this rectified soon.

**Comment by mattography** [comment]
Following up on this, is there a time frame to implement the basic keyboard navigation features to make the grid actually accessible for ADA compliance? Every feature that would do so is currently in the backlog:
![screen shot 2018-08-09 at 1 04 44 pm](https://user-images.githubusercontent.com/435919/43914131-f905182a-9bd4-11e8-9fea-6c6682e17288.png)

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
