### ISSUE TITLE
Add an attribute for showing/hiding a MenuItem given a condition

### ISSUE THREAD

**Issue by envynoiz** [ag-grid/ag-grid#2526]
**I'm submitting a ... (check one with "x")**
```
[x ] feature request
```

**Current behavior**
Currently the MenuItem only has the following options:
```
MenuItem {
    name: string, // name of menu item
    disabled?: boolean, // if item should be enabled / disabled
    shortcut?: string, // shortcut (just display text, saying the shortcut here does nothing)
    action?: ()=>void, // function that gets executed when item is chosen
    checked?: boolean, // set to true to provide a check beside the option
    icon?: HTMLElement|string, // the icon to display beside the icon, either a DOM element or HTML string
    subMenu?: MenuItemDef[] // if this menu is a sub menu, contains a list of sub menu item definitions
}
```
And it is necessary to perform the conditions in a separate way in order to return a list of the desired menu items to show when the menu appears.

**Expected behavior**
When a MenuItem is added either to the ContextMenu or ColumnMenu, I would like an attribute for showing or hiding the element given a condition.

For instance: 
MenuItem
```
{
  name: "Alert " + params.value,
  action: function() {
    window.alert("Alerting about " + params.value);
  },
  shown: true // -> an attribute like this!
}
```

**What is the motivation / use case for changing the behavior?**
In case that we only need to display the menu item according a condition in our apps, the selected row and so on.

**Please tell us about your environment:**

- O.S: macOs High Sierra version: 10.13.5
- ag-Grid version: 18.1.1
- Language: all

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
