### ISSUE TITLE
Get cell value in edit type full row

### ISSUE THREAD

**Issue by silpa-kanthan** [ag-grid/ag-grid#2527]
Hi,
I m using ag grid in angular. The editing type mode is 'fullRow'. For the editing type full row, the onCellEditingStopped, onCellEditingStared, onCellValueChanged method not triggering for individual cell. Its triggering when it leaves the last cell of the row.

Is there any event for get values of  individual cell after giving tab in edit type mode 'fullRow'

Thanks

**Comment by Sampath-Lokuge** [comment]
Have you found the solution for this?

**Comment by silpa-kanthan** [comment]
@Sampath-Lokuge, not yet

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks

**Comment by NewBo1234** [comment]
I do wish that someone could address this.

I'm using fullRow editing as well, and I need to grab the new values (i.e. the values in the controls being shown in the edited row), and I can't get them for the life of me.

**Comment by guruprasadmishra** [comment]
facing the same issue

**Comment by guruprasadmishra** [comment]
I  found few ways to access the current value 

**1. directly form dom**
**this.params.rowIndex** will give us the index of the row   in the current cell then ->

        let intialQuerSelctorString = `div.ag-row[row-index='${this.params.rowIndex.toString()}']` ; //index of row dom
        let editedSymbol  =  document.querySelectorAll(intialQuerSelctorString)[1].querySelectorAll("div.ag-cell")[0].getElementsByTagName("input")[0].value;  //value of previous cell/column in my case 1st column


**2. set the previous cell update value to rowNode  while tabbing out on focus out event**

 we can use a  custom  cellEditor component and onChange/focusOut of input field or dropdown of the firstcell

   this.params.node.setData(dummyData); //the updated data

then if we will try to access we can access the update value in a new cell in any event
