### ISSUE TITLE
onColumnResized not called if we resize the column to the minimum

### ISSUE THREAD

**Issue by EloHailwidis** [ag-grid/ag-grid#2528]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
onColumnResized not called if we resize the column to the minimum

**Expected behavior**
onColumnResized should be called

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/QF1OOoyMOr9G6fZNOTKx?p=preview
1. Open the console
2. Resize any column to half the initial size
3. "resize !" is printed  --> params.finished is true
4. Resize any column to the minimum size
5. "resize !" is not printed --> params.finished is still false

**What is the motivation / use case for changing the behavior?**
I need to know when the column is resized, even if it's at the minimum

**Please tell us about your environment:**
Windows 10
VSCode

* **ag-Grid version:** 18.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

* **Language:**
AngularJS 1.7.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,



After some investigation, we found that this issue is actually fixed in our latest version of ag-grid, could you try to update it on your end and try again?



Note that we are going to close this issue now, if you want to follow up, please create a new issue in github, thanks
