### ISSUE TITLE
Tab editing a pinned row does not correctly evalutate editability conditions

### ISSUE THREAD

**Issue by pfosser** [ag-grid/ag-grid#2529]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A grid with some conditionally editable fields.
When tab editing a pinned row, the conditions are not evaluated on it, but on a row not pinned. So, if a condition checks row content, cells are not navigated in the expected way, e.g. skipping an editable cell.

**Expected behavior**
While cellediting, tab navigation should open all editable fields.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/G6o5E72E41yxrdFU4wFJ
The sample has a pinned row (the one filled with #).
1) Open celleditor on the first cell.
2) Hit tab.
You'll see that editing jumps to the third cell, while it should open the editor on the second one.
You can also set a breakpoint (in devtools) in the isEditable() function, clearly seeing that it receives the first non-pinned row.

**What is the motivation / use case for changing the behavior?**
If editing is allowed on pinned rows, editability conditions should be correctly evaluated on them

**Please tell us about your environment:**
Ubuntu 18.04
VSCode
npm

* **ag-Grid version:** 18.1.1

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2128 - Pinned rows - Wrong row nodes passed to the isEditable callback when using pinned rows
