### ISSUE TITLE
Apply Styling to autoGroupColumnDef

### ISSUE THREAD

**Issue by ziyenl** [ag-grid/ag-grid#2530]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Right now there doesn't seem to be a way to apply styling upon the autoGroupColumnDef

**Expected behavior**
I would like to apply styling on the autoGroupColumnDef

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I will need it for my current project

**Please tell us about your environment:**

Windows 10

* **ag-Grid version:** X.X.X

a-Grid version latest

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React

**Comment by ddankwerth** [comment]
on the gridOptions you can defined autoGroupColumnDef and add in it some class
      autoGroupColumnDef: {
        cellClass: 'myGroupCellClass'
}

in theory you can put cellStyle too, but that's giving me odd results

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, you should be able to find more information in the following links:

https://www.ag-grid.com/javascript-grid-cell-styles/

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
