### ISSUE TITLE
React Grid not visible in Chrome 44

### ISSUE THREAD

**Issue by CodeJjang** [ag-grid/ag-grid#2531]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Tried using ag-grid v18 with react (v16.4.0) on chrome 44, using the [official docs](https://www.ag-grid.com/react-more-details/), however the grid is not visible. It is visible though in more recent versions of chrome.  
Also, no error is shown so I can't really figure out what's broken.  
I see that the DOM elements are rendered but yet they are not visible.

**Expected behavior**
Should work in old chrome versions, or at least state that it either doesn't support it or output some error we can try to handle.

**Minimal reproduction of the problem with instructions**
Just try to run the demo code in Chrome 44.

**What is the motivation / use case for changing the behavior?**
Not all clients has the most recent Chrome version.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
v18.0.0

* **Browser:**
Chrome 44

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS v2.7.2

**Comment by uvtzxpm** [comment]
Chrome 44 is ancient, from 2015. Nobody should be using a version that old, which is riddled with bugs and security problems which have been fixed in newer versions.

There won't be any interest in this getting fixed, you would have to do it yourself.

**Comment by CodeJjang** [comment]
You're absolutely right, but I don't have a choice here.
Do you have any idea where to start given the fact there's not a single error?

**Comment by uvtzxpm** [comment]
Honestly, I would tell your client to get stuffed. It's just not worth it.

Maybe when they keep hearing "no, that's not possible" they will upgrade their junk. Are they stuck on Windows XP or something?

In an effort to be helpful...

- Try it without React. It's plausible that React itself won't work properly in ancient Chrome. Try https://www.ag-grid.com/example.php for a raw example.
- Use Chrome's developer tools. The answer is in there somewhere. It's probably going to be one small thing. Some unsupported feature, etc.
- You could try older versions of ag-grid. I would start with a very old version (ideally one that was around at the time of Chrome 44), and see if that works. If it doesn't, you're fucked. If it does, keep incrementing the version until you find one that doesn't work. Try to work out what the breaking change is. Of course, then you're stuck on an old version of ag-grid.
- Use a different grid. https://datatables.net/ maybe.

If it's really that important, hire an expert.

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
