### ISSUE TITLE
Custom cell renderer containing a textbox loses focus when value in the textbox is changed

### ISSUE THREAD

**Issue by jcrosetto** [ag-grid/ag-grid#2532]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Create a custom cell renderer that renders a textbox.
Update the row node with the new value coming from the textbox the user is typing into.
The textbox loses focus after each change to the value in the textbox

**Expected behavior**

The textbox remains focused

**Minimal reproduction of the problem with instructions**

See a demo of it here: https://plnkr.co/edit/Pz2LTB3xzkSAMkZhAulr?p=preview
Type into any of the textboxes to see the issue.

**What is the motivation / use case for changing the behavior?**

I would like to create a custom cell renderer that allows user input into a textbox. I would like to customize the functionality of the input, that is why I am not using the built in edit functionality.

**Please tell us about your environment:**

OSX

* **ag-Grid version:** X.X.X

18.1.1

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, this is not a bug. You should be using a cell editor. Please see the docs here

[https://www.ag-grid.com/javascript-grid-cell-editor/#react-cell-editing](https://www.ag-grid.com/javascript-grid-cell-editor/#react-cell-editing)

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by hashmatmuqbil** [comment]
> **I'm submitting a ...** (check one with "x")
> 
> ```
> [ x] bug report => search github for a similar issue or PR before submitting
> [ ] feature request
> [ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
> ```
> 
> **Current behavior**
> 
> Create a custom cell renderer that renders a textbox. Update the row node with the new value coming from the textbox the user is typing into. The textbox loses focus after each change to the value in the textbox
> 
> **Expected behavior**
> 
> The textbox remains focused
> 
> **Minimal reproduction of the problem with instructions**
> 
> See a demo of it here: https://plnkr.co/edit/Pz2LTB3xzkSAMkZhAulr?p=preview Type into any of the textboxes to see the issue.
> 
> **What is the motivation / use case for changing the behavior?**
> 
> I would like to create a custom cell renderer that allows user input into a textbox. I would like to customize the functionality of the input, that is why I am not using the built in edit functionality.
> 
> **Please tell us about your environment:**
> 
> OSX
> 
> * **ag-Grid version:** X.X.X
> 
> 18.1.1
> 
> * **Browser:**
> 
> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
> 
> * **Language:** [all | TypeScript X.X | ES6/7 | ES5]
>   Typescript

Hi,
Have you solved this issue?

**Comment by BradWells** [comment]
For anyone who found this from Google: I believe this was solved (its been over 5 years since this issue was created), but you need to make sure that the row component is not deleted and re-made. For me, that was happening because I did not have a getRowId() function. My data always has an id property from the backend, so it was as simple as adding:

```
  <AgGridReact
      getRowId={(params) => params.data.id} />
```

If you are using inputs inside cell renderers because you do not like AgGrid's click to edit default functionality (or it doesn't play nicely with your component framework), I would also look into suppressing keyboard events from being captured by AgGrid. This changes the AgGrid behavior of moving left or right one tab back to the browser default of moving to the next input on the page.

```
function suppressKeyboardEvent({ event }: SuppressKeyboardEventParams<any>) {
  const { key, shiftKey, ctrlKey } = event;
  const isTabForward = key === 'Tab' && shiftKey === false;
  const isTabBackward = key === 'Tab' && shiftKey === true;
  const isPaste = key === 'v' && ctrlKey === true;
  let suppressEvent = isTabForward || isTabBackward || isPaste;
  return suppressEvent;
}
// ...

<AgGridReact
  defaultColDef={{ suppressKeyboardEvent: suppressKeyboardEvent }} />
```

**Comment by anjantalatam** [comment]
You might want to solve [Navigation keys are not working inside cellrenderer input boxes in ag grid](https://stackoverflow.com/questions/59101206/navigation-keys-are-not-working-inside-cellrenderer-input-boxes-in-ag-grid)
