### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#2536]
AG Grid stays in Memory

<img width="1669" alt="bildschirmfoto 2018-07-29 um 14 13 03" src="https://user-images.githubusercontent.com/364896/43366174-a0d67a5c-9339-11e8-8df8-e14001662516.png">

**Comment by robindenton-ag-grid** [comment]
Hi,

In order to be as efficient as possible solving the issues in github, please refer to the template when creating your issue. Since this issue is not following the template is going to be closed, but feel free to open another one following the template.

Thanks
