### ISSUE TITLE
ag-grid sorting is not working with another third party plugin

### ISSUE THREAD

**Issue by ShankzPatil** [ag-grid/ag-grid#2537]
**Current behavior**

after adding third party Stimulsoft report.js for report tool then not able to sort.

**Expected behavior**

Should sort ag-grid.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/U8UrxUzwIpLob5olfBq7?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

version 13.0.1

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angularjs and typescript

**Comment by thirtydot** [comment]
This can be closed, it's been answered elsewhere:

https://stackoverflow.com/a/51633865/405015

It was nothing to do with ag-grid.
