### ISSUE TITLE
How to do Sort Priority ?

### ISSUE THREAD

**Issue by ananddc1989** [ag-grid/ag-grid#2538]
https://www.ag-grid.com/javascript-grid-sorting/

we can do all multiple column sorting with Sort Model, when we set sort Model i don't find any property for sort priority 

please advice

**Comment by ddankwerth** [comment]
Order of the sort model is the priority
so if sort model is [ { columnA , order}, {columnB , order}] this grid will be sorted first by columnA and then by columnB
