### ISSUE TITLE
How to use the ag-grid-vue in the es5 way?

### ISSUE THREAD

**Issue by WillWei1983** [ag-grid/ag-grid#2539]
I am using the vue by its cdn js, not a es6 project
when using the ag-grid, I would like to use the ag-grid-vue but not the javascript, cause I would like using the vue component to be the cell renderer but not the javascript component
but I don't know how to include it in a es5 way. Can anybody tell how to use it with the es5 way?

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
