### ISSUE TITLE
Add dropdown to change paginationPageSize

### ISSUE THREAD

**Issue by nikodem911** [ag-grid/ag-grid#2540]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently in order to change `paginationPageSize ` property a custom component need to be created (e.g. select). It also requires implementing the handler in the class using the grid and calling `paginationSetPageSize()` inside. It requires repetitive work if the application uses the grid in multiple places.

**Expected behavior**
Ideally if the control to change the page size was added to the grid's the paging panel and was supported by the grid itself.

**Minimal reproduction of the problem with instructions**
- Create AG grid with pagination = true

**What is the motivation / use case for changing the behavior?**
This is a common requirement to allow the user to change default paging size.
Currently it requires implementing it whenever it's needed (either by repeating the code or by wrapping the grid with custom grid).

**Please tell us about your environment:**
- Angular 6 

* **ag-Grid version:** 17.0.0

* **Browser:**
Any

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Any

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by nikodem911** [comment]
Thank you. The process of acquiring the license for AG Grid for my company is in progress. Once we have a license I'll raise the ticket via zendesk.
