### ISSUE TITLE
Condition template not translated

### ISSUE THREAD

**Issue by gama410** [ag-grid/ag-grid#2542]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[* ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The condition template (in the filters) is not translated. For instance, when you enter a filter text, the filter box will add a couple of radio "And / Or" with a new filter under it.
These radios seem to be hardcoded so they can't be translated as can be seen in the following method:

 ```
   private createConditionTemplate (type:FilterConditionType): string{
        return `<div class="ag-filter-condition">
            <input id="andId" type="radio" class="and" name="booleanLogic" value="AND" checked="checked" /><label style="display: inline" for="andId">AND</label>
            <input id="orId" type="radio" class="or" name="booleanLogic" value="OR" /><label style="display: inline" for="orId">OR</label>
            <div>${this.createConditionBody(type)}</div>
        </div>`;
}
```

**Expected behavior**
I would expect  the label values to make use of the translation system. Thanks!

**Minimal reproduction of the problem with instructions**

Just use any filter

**What is the motivation / use case for changing the behavior?**

Our application is targeted for different languages

**Please tell us about your environment:**

irrelevant

* **ag-Grid version:** X.X.X

18.0.1

* **Browser:**

irrelevant

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
irrelevant

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by gama410** [comment]
Hello,

I understand. Although this is not really a feature request as much as a bug to fix, in my opinion.

I would be willing to try to submit a PR for this if you want. Would that be ok?

**Comment by gama410** [comment]
Just for information, this is easily fixed by executing the following code :
`(BaseFilter.prototype as any).createConditionTemplate = function(type:FilterConditionType): string{
        return `<div class="ag-filter-condition">
            <input id="andId" type="radio" class="and" name="booleanLogic" value="AND" checked="checked" /><label style="display: inline" for="andId">${this.translate('and')}</label>
            <input id="orId" type="radio" class="or" name="booleanLogic" value="OR" /><label style="display: inline" for="orId">${this.translate('or')}</label>
            <div>${this.createConditionBody(type)}</div>
        </div>`;
    }`

As I don't want to modify ag-grid directly (I still want to be able to upgrade later on), I just replaced the method in the prototype but for a definite fix, you could just replace the method content by mine.
