### ISSUE TITLE
Single row in Tree Data can't be pinned

### ISSUE THREAD

**Issue by Shtokins** [ag-grid/ag-grid#2544]
**I'm submitting a ...** 
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In Tree Data table last row ('Total') is not grouped. I put it in pinnedBottomRowData, it shows, but first cell ('Total' word) doesn't appears, I tried it with [value] and with simple value but result is the same.  
![44 2018-08-02 16-44-38](https://user-images.githubusercontent.com/30378485/43588061-5b4f73a6-9674-11e8-9c02-1e9dec17b611.png)

* **ag-Grid version:** 18.1.1

* **Browser:**
 Chrome 67.0

* **Language:** [ ES6/7 | ES5]

**Comment by Shtokins** [comment]
Tree data grid changing first column's field. autoGroupColumnDef helped me

**Comment by dibell** [comment]
@Shtokins Hi. Sorry to bring this up so long after it's closed, but, I have exactly that problem and wondered how you used autoGroupColumnDef to fix it?

**Comment by Shtokins** [comment]
Hi!
Sorry for a late answer
> @Shtokins Hi. Sorry to bring this up so long after it's closed, but, I have exactly that problem and wondered how you used autoGroupColumnDef to fix it?
1. in constructor/class:
this.state/state={...,
      autoGroupColumnDef: {
        headerName: columns[0], //here you should point to your "Total" row header
        field: columns[0], //the same
        width: 225,
        pinned: "left",
        suppressMenu: true,
        cellRendererParams: {
          suppressCount: true
        }
      }
   }
2. in render():
   <AgGridReact
     ...={...}
     ...={...}
     autoGroupColumnDef={this.state.autoGroupColumnDef}
/>

**Comment by dibell** [comment]
@Shtokins Sorry for the late Thank You!

**Comment by Regestrac** [comment]
I have a top pinned row which shows the total for some fields and I want to give the text as 'Total Count' in the pinned row, how do I do it?  Or is there a way to show a row exactly same as total footer on top also?

**Comment by Shtokins** [comment]
@Regestrac if you mean, that the first column of top pinned row should have "Total Count', you can either hardcode it like
`pinnedTopRowData[0]?.[firstColumnField]="TotalCount" `
or set "Total Count" as a value for the first column in function where you create pinnedTopRowData

> Or is there a way to show a row exactly same as total footer on top also?

`pinnedTopRowData={pinnedBottomRowData}`
`pinnedBottomRowData={pinnedBottomRowData}`
