### ISSUE TITLE
Passing parameters to column config from redux state

### ISSUE THREAD

**Issue by habibtariq** [ag-grid/ag-grid#2545]
I am using AgGridReact along with redux. So i have a custom floating filter component, and i want to pass it some parameters from my state via floatingFilterComponentParams.
The issue is that every time my state (responsible for the floating filter component) changes, it resets the grid to default column config. For example if someone has resized the columns or changed their order, when the state changes it resets to default setting. 
So how can i pass parameters to my custom floating filter component without the grid resetting to its default config. 

example code

<AgGridReact
  columnDefs={[
    {
      headerName: 'col1',
      field: 'name',
      floatingFilterComponent: 'twChangeFilter',
      floatingFilterComponentParams: {
        isVisible: this.props.isFilterVisible,
      },
    },
    {
      headerName: 'col2',
      field: 'age',
      floatingFilterComponent: 'twChangeFilter', //custom filter component
      floatingFilterComponentParams: {
        isVisible: this.props.isFilterVisible, //coming via redux state
      },
    },
  ]}
/>;

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
