### ISSUE TITLE
AG Grid Set Quick filter

### ISSUE THREAD

**Issue by silpa-kanthan** [ag-grid/ag-grid#2548]
Hi,
I m using AG Grid set quick filter. In my ag grid, i m having 10 columns. In this i have set hide property to true for 3 columns. By using set quick filter option for global search, the search applying for the columns which are in hide. I don't want to search the columns which are in hide true. Please help

Thanks.

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
