### ISSUE TITLE
Edit cell values of a row from a modal/popup

### ISSUE THREAD

**Issue by JVH31** [ag-grid/ag-grid#2549]
**I'm submitting a feature request
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have an ag-grid. When I click on a cell, I can edit it.

**Expected behavior**
Now I want to click on cell, a modal appears with all the cells of the row. These celles should be editable

**Minimal reproduction of the problem with instructions**
Use any regular ag-grid.

**What is the motivation / use case for changing the behavior?**
Needs to deliver abetter UX to clients

**Please tell us about your environment:**
Windows 10, Visual Studio Code, Node 9.3.0, NPM 6.0.0, Angular 4.x

* **ag-Grid version:** X.X.X

^18.1.1

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
2.5.3

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
