### ISSUE TITLE
API endpoint to force rowClassRules update?

### ISSUE THREAD

**Issue by orochi235** [ag-grid/ag-grid#2552]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There doesn't seem to be any way to force rowClassRules to recompute on a given row (or all rows) without forcing a much heavier full row refresh.

**Expected behavior**
A method added to the API to only recompute class rules on a given row.

**What is the motivation / use case for changing the behavior?**
We use rowClassRules to express a couple of parallel concepts of selection behavior in our grid, and there are times when the selection state of a row changes, but the underlying data doesn't. The full row refresh API call is really heavy, and all I care about at that point is updating CSS classes on the row.

It's doable with `querySelectorAll` and some attribute selectors, of course, but I already have enough to be ashamed of in my life and would very much appreciate a cleaner solution to this problem if possible. :)

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
