### ISSUE TITLE
API to prevent row drop outside the grid

### ISSUE THREAD

**Issue by sachinshettigar** [ag-grid/ag-grid#2554]
I'm submitting a ... (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

Current behavior
There doesn't seem to be any way to stop the row that is dragged from leaving the grid or reverting row back it its original position.

Expected behavior
If this property is enabled and row is tried to be dragged outside the grid , either we shouldn't be able to drag row outside the grid or the row should be reverted back to its original position.

What is the motivation / use case for changing the behavior?
We have a use case where last row of the grid shouldn't be movable. This can be done by passing a function to rowDrag of Coldef;
The last row is not draggable but when a draggable row is dropped outside the grid it drops into last position in which case i want to revert row back to its original position.

https://plnkr.co/edit/Z8xmMekrA7VPnEhHNc93?p=preview

**Comment by robindenton-ag-grid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via github)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by guidogast** [comment]
@sachinshettigar Have you got a workaround for this? Since, this feature hasn't been implemented.
