### ISSUE TITLE
Support multiple headers id's to change style on XLS 

### ISSUE THREAD

**Issue by rafael-andrade** [ag-grid/ag-grid#2555]
I want to change the style of header based on information that I have. I will use the exported XLS to import some data to back-end. Only some columns will be editable and I want to change the style of the headers only for these rows. 

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
![image](https://user-images.githubusercontent.com/11963164/43787451-63eb01f8-9a41-11e8-8958-5e4d9a7f360a.png)

**Expected behavior**
Change StyleID for some columns

**Minimal reproduction of the problem with instructions**
All headers have the same StyleID

**What is the motivation / use case for changing the behavior?**
I do not want to remove header and insert again using customHeader to change the style of these headers. 

**Please tell us about your environment:**
 --

* **ag-Grid version:** 17.1.1

* **Browser:**
Chrome and Firefox - Latest versions

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via github)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by rafael-andrade** [comment]
Ok, thanks!
I will contact my team leader to get the access
