### ISSUE TITLE
Expand headerTooltip to allow callbacks and/or headerName

### ISSUE THREAD

**Issue by djensenrsdc** [ag-grid/ag-grid#2556]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It appears any value entered for headerTooltip is taken as a string with no support for callbacks, and no easy way I've noticed to include the headerName as the tooltip.

**Expected behavior**
I would like to see this brought in line with tooltip to allow a callback function, or at least an optional flag to allow it to display the headerName. 

**What is the motivation / use case for changing the behavior?**
My project is trying to cram enough data into a horizontally-limited grid that some fairly long column headers get truncated, and it would be very useful to have the headers appear in tooltips programmatically instead of hardcoding strings for each, much like what one can easily do with tooltips in the body of the grid.

* **ag-Grid version:** X.X.X
17.1.1, additionally tested with 18.1.2.

* **Browser:**
Chrome/Firefox, latest

* **Language:** 
ES6, AngularJS

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via github)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
