### ISSUE TITLE
Grid header no longer appears with ag-grid version 18

### ISSUE THREAD

**Issue by lobo78** [ag-grid/ag-grid#2557]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As of ag-grid 18, the header row no longer appears.

**Expected behavior**
The header row should appear as normal as with previous versions of ag-grid.

**Minimal reproduction of the problem with instructions**

The issue can be reproduced with a simple ag-grid on stackblitz. 

https://stackblitz.com/edit/angular-ag-grid-angular-amzjgo?file=app%2Fmy-grid-application%2Fmy-grid-application.component.html

You will notice a simple grid with a header row. Now open the dependencies in the left sidebar. You will notice it is using ag-grid version 16. Delete both ag-grid and ag-grid-angular from the dependencies. Then, in the input box at the bottom of the dependencies list, enter ag-grid. It will load the latest version of ag-grid (v.18). Also add ag-grid-angular. 

Once it reloads, you will notice that the grid on the right no longer shows the header.

**What is the motivation / use case for changing the behavior?**
This is a regression.

**Please tell us about your environment:**
OSX, IntelliJ, Yarn, Tomcat

* **ag-Grid version:** X.X.X
I have verified that the header row appears correctly in version 16 and 17. It only disappears in v18.

* **Browser:**
Browsers: IE, Chrome, Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular 6
TypeScript 2.6.2

**Comment by gportela85** [comment]
Don't forget to update the CSS when you update to ag-Grid v18.
See: https://stackblitz.com/edit/angular-ag-grid-angular-swvqfu
