### ISSUE TITLE
Dead space in checkbox column in Chrome/IE11

### ISSUE THREAD

**Issue by antmdvs** [ag-grid/ag-grid#2559]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Clicking in the space immediately to the right of the checkbox image in a column having `checkboxSelection: true` does not have any affect.

**Expected behavior**
Clicking anywhere in a checkbox selection cell (so long as `suppressRowClickSelection` is `false`) should check/clear the checkbox accordingly and select/deselect the corresponding row.

**Minimal reproduction of the problem with instructions**

Using the React Plunk found in the docs here https://www.ag-grid.com/javascript-grid-selection/#example-multi-select-single-click, ADD the following on line 14 of index.jsx (immediately before `field: 'athlete'`):

    checkboxSelection: true,

Clicking in the area highlighted below does not check the box nor select the row.

![image](https://user-images.githubusercontent.com/17127310/43880435-6bbe1d44-9b76-11e8-8f4c-df032fb0981e.png)

> Note that by removing the theme (`className` prop), the problem goes away.

> Also, this doesn't seem to be reproducible in Edge.

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** 18.1.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; wbx 1.0.0; rv:11.0) like Gecko

**Comment by makinggoodsoftware** [comment]
Hi,

We are closing this ticket as this looks like a duplicate from a zendesk ticket, if that is not the case, please reply we will reopen it.

Thanks
