### ISSUE TITLE
gridAutoHeight seems do not working on Angular 5+

### ISSUE THREAD

**Issue by clabnet** [ag-grid/ag-grid#2560]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
gridAutoHeight option seems not working

**Expected behavior**
We expect to resize the grid panel for containing all rows

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-ag-grid-gridautoheight

If the current behavior is a bug or you can illustrate your feature request better with an example,
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use this template as a starting point: https://plnkr.co/edit/369YrrgCVrnPjD528OtT).
-->

**What is the motivation / use case for changing the behavior?**
We have small tables with few rows, (1.. 10 max) 
we expect to have the grid height dynamically resizesd for containing all rows

**Please tell us about your environment:**
WIN 10, Angular 5.2.6

* **ag-Grid version:** 17.1.1
I cannot upgrade to latest version because this is the last version for Angular 5+

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.6.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Try 

domLayout:"autoHeight"


https://stackblitz.com/edit/angular-ag-grid-gridautoheight-n2ifgd?file=app/my-grid-application/my-grid-application.component.ts

**Comment by clabnet** [comment]
It worked. Thanks.

**Comment by angelayanpan** [comment]
[](https://www.ag-grid.com/javascript-grid-width-and-height/#auto-height)
The example code/documentation for 18.X mistakenly made the setDomLayout part of gridApi.  Which it's not. It's not a valid method. 

And further more, this solution to domLayout:"autoHeight" in gridOptions still leaves a vertical scroll bar that can be moved a little bit. It does show all the data. But the vertical scroll bar can be moved up or down by 3px.
