### ISSUE TITLE
pinning column animations - switcher

### ISSUE THREAD

**Issue by ArekSliwa** [ag-grid/ag-grid#2561]
**I'm submitting a ...**  (check one with "x")
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
there is no option to put off animation on pinning columns. 

**Expected behavior**
I would like to have a flag in options to switch column pinning animation. It will be nice also if I can configure it separately for pin and unpin. Because for example I would like to have animation on pin, but no animation on unpin. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
It seems that there is no easy way to do it. For example for column moving - there is suppressColumnMoveAnimation property. Why not add something like that for pin/unpin or show/hide column animations?

**Please tell us about your environment:**
 macOS High Sierra, Webstorm

* **ag-Grid version:** 
We are using angular 6 and this is info from package.json:
"ag-grid": "^18.1.2",
"ag-grid-angular": "^18.1.0",

* **Browser:**
this feature is not related to browser.
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3516.0 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.7.2

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via github)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

Thanks for your understanding.

ag-Grid Team.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
