### ISSUE TITLE
Firefox: Aligned Grids feature not working on Column Groups open/close

### ISSUE THREAD

**Issue by hoelle666** [ag-grid/ag-grid#2563]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In Firefox 61 the "Aligned Grids" feature as presented on the homepage [here](https://www.ag-grid.com/javascript-grid-aligned-grids/) is not working for the column group open/close event. It is working for me in IE11 or Chrome.

**Expected behavior**
Column groups in aligned grids expand/collapse in all grids.

**Minimal reproduction of the problem with instructions**
see [here](https://www.ag-grid.com/javascript-grid-aligned-grids/) on the ag-grid homepage.

**What is the motivation / use case for changing the behavior?**

N/A

**Please tell us about your environment:** N/A

* **ag-Grid version:** 18.1.2

* **Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

* **Language:** N/A

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

cmte: AG-2122 - Aligned grids - column group open/close event not working on Firefox
