### ISSUE TITLE
Update a parameter with a button

### ISSUE THREAD

**Issue by PierBJX** [ag-grid/ag-grid#2565]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using ag-grid I am doing a basic table. 
I set all the option that I wanted like this:
```
    <ag-grid-angular 
      #agGrid 
      style="width: 100%; height: 100%;"
      id="myGrid" 
      [rowData]="rowData"
      class="ag-theme-balham" 
      [columnDefs]="columnDefs"
      [enableSorting]="true"
      [enableRangeSelection]="true"
      [enableFilter]="true"
      [enableColResize]="true"
      [paginationAutoPageSize]="autoPageSize"
      [pagination]="true"
      [animateRows]="true" 
      [floatingFilter]="true" 
      (gridReady)="onGridReady($event)">
    </ag-grid-angular>

```
Then I created a button to change the parameter _autoPageSize_ with a function that I call when clicking.
`<button class="btn btn-primary" (click)="autoSize()">All rows</button>`

The function is very basic:
```
  autoSize() {
    this.autoPageSize = !this.autoPageSize;
  }
```

**Expected behavior**
This does not work whereas the variable autoPageSize is updated.
What do I miss ?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via github)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

Thanks for your understanding.

ag-Grid Team.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
