### ISSUE TITLE
IE crashes when using ag-grid 18.1.2 (ag-grid-angular 18.1.0) .

### ISSUE THREAD

**Issue by DeemaMarwan** [ag-grid/ag-grid#2566]
Currently using angular 6 along with ng-bootstrap and ag-grid latest version (on the time of writing this issue) and i am facing the below issue.
IE crashes when opening the page that contains the ag-grid component and i cannot debug the issue.

**Comment by makinggoodsoftware** [comment]
Hi Paritosh,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-1966 | Ag-grid-angular crashes on Firefox/IE/Edge/safari if ng-bootstrap dropdown is clicked | IN PROGRESS |  

It is estimated for our next release

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by dredwolff** [comment]
Huh, supposedly 18.1.2 HAS the fix for AG-1966: https://www.ag-grid.com/ag-grid-changelog/
