### ISSUE TITLE
Detect the end of drag position

### ISSUE THREAD

**Issue by shiloDrot** [ag-grid/ag-grid#2571]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

RowDragEnd event is call only when the dragging end inside the grid, and there is no way to detect weither the drag finished inside the grid or outside.

**Expected behavior**

To be able to detect weither the drag finished inside the grid or outside.

**Minimal reproduction of the problem with instructions**

See documentation [here](https://www.ag-grid.com/javascript-grid-row-dragging/#row-drag-events). 

**What is the motivation / use case for changing the behavior?**

To change the behavior of the application when the drag end outside the grid.

* **ag-Grid version:** 18.1.2

* **Browser:** all

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via github)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

Thanks for your understanding.

ag-Grid Team.
