### ISSUE TITLE
AG-Grid "Not contains" filter option filtering the blank value

### ISSUE THREAD

**Issue by srikant21** [ag-grid/ag-grid#2572]
**Current behavior**
When we select "Not contains" filter option on a particular column and type some value it is filtering the empty cells.

**Expected behavior**
It should not filter out empty cells for "Not contains" filter option.

* **ag-Grid version:**18.1.1

Language: [all | TypeScript X.X | ES6/7 | ES5]
TypeScript-2.3.3

Plunker:-
https://next.plnkr.co/edit/mCv4ZqInmUKIreNW

**Comment by srikant21** [comment]
Can any one please reply on this?I am not whether it is a bug or I am doing something wrong.

**Comment by makinggoodsoftware** [comment]
Hi,

I would suggest using a custom text comparator for the text filter:

https://www.ag-grid.com/javascript-grid-filter-text/#text-custom-comparator

Hope this helps
