### ISSUE TITLE
AG-Grid csv export downloaded file with first column as blank

### ISSUE THREAD

**Issue by srikant21** [ag-grid/ag-grid#2573]
**Current behavior**
I have a grid with check box row selection on first row.When i am trying to do export as csv,It is creating the csv file with the first column as blank.

**Expected behavior**
The downloaded csv file should not have first column as blank.

ag-Grid version: 18.1.1
Language: [all | TypeScript X.X | ES6/7 | ES5]
TypeScript-2.3.3

Plunker:-
https://next.plnkr.co/edit/kGDtoQbvRuxMALU0ZdtD?p=preview&preview

**Comment by BasavarajShivagaddagi** [comment]
Since user does not require to know whether checkbox is checked or not checked in csv file. So my suggestion is to remove the empty column completely(in this example first column).

**Comment by srikant21** [comment]
Can any one please reply on this?I am not whether it is a bug or I am doing something wrong.

**Comment by makinggoodsoftware** [comment]
Hi,

I would just exclude that column from the export... From the docs..

https://www.ag-grid.com/javascript-grid-export/#cellClassRules 
columnKeys: Provide a list (an array) of column keys if you want to export specific columns.

Hope this helps

**Comment by vdsheryarshirazi** [comment]
@makinggoodsoftware how this could be possible using cellClassRules by providing columnKeys?
can you share any example?

link is also outdated

**Comment by Feluzia** [comment]
@makinggoodsoftware  Still the same for me. Please reopen. Using columnKeys might be possible but it will cost a huge workaround. I would prefer to either exclude the checkboxes (in general or via property, because usually there is no need for them in an excel file) or to have the opportunity to exclude columnKeys as well.
