### ISSUE TITLE
columnBuffer | enhancement 

### ISSUE THREAD

**Issue by seeden** [ag-grid/ag-grid#2574]
In current ag-grid we have just rowBuffer. It is great for vertical scroll because user see filled cells.
I am looking for something like columnBuffer. It will be very useful when user is using horizontal scroll. 
Currently I see empty cells when using horizontal scroll and I need to wait for render. It does not look good because I am using react cells and rendering is slow

rowBuffer is for rows
columnBuffer will be for columns

**Comment by robindenton-ag-grid** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
