### ISSUE TITLE
ag-grid-react doesn't support new React (16.3) Context API

### ISSUE THREAD

**Issue by urrri** [ag-grid/ag-grid#2578]
I'm submitting a ...

[x] bug report

Current behavior
Context consumer doesn't receive context in a cell renderer if context provider declared above the grid.
Because unstable_rendersubtreeintocontainer doesn't work with new Context API

Expected behavior
new Context API should work.
There is Portal API (ReactDOM.createPortal), which supports all new APIs and replaces deprecated unstable_rendersubtreeintocontainer.
https://codesandbox.io/s/kw4pro8k27 - sample, how golden-layout managed exactly the same problem with very similar behavior of non-react component

What is the motivation / use case for changing the behavior?

Please tell us about your environment:

ag-grid-react version: 18.1.X
ag-Grid/ag-Grid-Enterprise version: 18.1.X
React version: 16.4.X
Browser: [Chrome 68 ]
Language: [ ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
I'd suggest to try the reactNext option - it uses portals and should work with the new context:

https://www.ag-grid.com/react-more-details/#react-portals

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by seanlandsman** [comment]
Hi,

Please refer to the documentation here on how you can use the context api withing ag-grid components

https://www.ag-grid.com/react-more-details/#context-api

thanks

**Comment by dbrelovsky** [comment]
The new context API still does not work. 
See  #https://github.com/ag-grid/ag-grid-react-example/issues/40

**Comment by hrgui** [comment]
Same here, providing reactNext to the `<AgGridReact />` does nothing. It seems I have to stuff things to `this.props.context` for it to listen correctly

**Comment by rob2d** [comment]
same; this seems to be because the CellRenderer creates components completely outside of the component hierarchy. Could be fixed via portals or just making CellRenderer a child of the AgGrid parent class.

**Comment by TroyAlford** [comment]
This is a pretty major/serious issue. Can we please get an update as to when it will be fixed? Should we open a new ticket at this point?

**Comment by spawnia** [comment]
The context is correctly passed as of version `22.0.0`.

**Comment by b-ff** [comment]
> The context is correctly passed as of version `22.0.0`.

That saved my day! Thanks a lot!
