### ISSUE TITLE
React components mounted to root instead of parent in Virtual DOM

### ISSUE THREAD

**Issue by ashrafhadden** [ag-grid/ag-grid#2587]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

<img width="1280" alt="screen shot 2018-08-22 at 2 17 32 am" src="https://user-images.githubusercontent.com/32565770/44446097-99a01600-a5b1-11e8-9cd8-81206c97070c.png">

[Image Source](https://www.ag-grid.com/example-runner/react.php?section=javascript-grid-cell-rendering-components&example=dynamic-components&fontawesome=1&bootstrap=1&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Afalse%7D)

React `cellRendererFramework` components and `frameworkComponents` (not sure about others) always get rendered to the root of the React Virtual DOM tree even though they are being called from `<AgGridReact/>`. I am using the official `react-devtools` Chrome extension to see this. The official ag-grid-react examples from https://www.ag-grid.com/ all display the same behavior.

This is seeming to subsequently break basic React component hierarchy/inheritance and cause the component not to re-render on receiving new props, a very crucial pattern in React. The props are clearly not being properly bound because of this. Not to mention how messy and confusing it makes things.

**Expected behavior**

<img width="688" alt="shouldrenderhere" src="https://user-images.githubusercontent.com/32565770/44445614-a0c62480-a5af-11e8-8c57-7de7b4be91e1.png">

[Image Source](https://www.ag-grid.com/example-runner/react.php?section=javascript-grid-cell-rendering-components&example=dynamic-components&fontawesome=1&bootstrap=1&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Afalse%7D)

_I would expect the components to get rendered as children of the `<AgGridReact/>` component, right where `<div></div>` is highlighted_

AgGrid React `frameworkComponents` and `cellRendererFramework` components would get virtually mounted to their calling parent (usually `<AgGridReact/>`) as normal in the React Virtual DOM tree. So if `cellRendererFramework: myReactCellRendererComponent` were defined on one of my columns then I should find those components nested as children under the `<AgGridReact/>` node in my React DevTools Virtual DOM panel.

**Minimal reproduction of the problem with instructions**

[Official Ag-Grid 'React Cell Rendering' Example](https://www.ag-grid.com/example-runner/react.php?section=javascript-grid-cell-rendering-components&example=dynamic-components&fontawesome=1&bootstrap=1&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Afalse%7D) | [Plunkr](https://www.ag-grid.com/javascript-grid-cell-rendering-components/#)
 Open up React DevTools panel and checkout the virtual DOM tree. This is where I got the screenshots from.

**What is the motivation / use case for changing the behavior?**

This seems to break all component inheritance and keep the ag-grid-react components from re-rendering like they should on receiving new props. Maybe because the props are being passed artificially through ag-grid only when ag-grid is mounting that component and not binding in a natural React way? This also seems to disallow usage of the new [Context API](https://reactjs.org/docs/context.html) as mentioned in Issue #2578  As a side note, when I hook up the React `frameworkComponents` to Redux they re-render on new props just fine.

More evidence of related issues: https://github.com/ag-grid/ag-grid/issues/2431

**Please tell us about your environment:**

Since this occurs on the official online examples I'm thinking it probably happens everywhere else too unless it's just my browser and mac. It happens on my own local projects as well.

<img width="257" alt="screen shot 2018-08-22 at 1 50 10 am" src="https://user-images.githubusercontent.com/32565770/44445227-2a74f280-a5ae-11e8-96e2-a5a31ae35104.png">

* **IDE:** 18.1.0VSCode 1.26.1 Stable

* **package.json:**
```
"ag-grid": "^18.1.2",
"ag-grid-react": "^18.1.0",
"react": "^16.4.2",
"react-dom": "^16.4.2",
"react-dom-factories": "^1.0.2",
```

* **ag-grid-react version:** 18.1.0

* **React version:** 16.4.2

* **Browser:** [Chrome 68.0.3440.106]

* **Language:** [Javascript | ES6/7 | ES5]

**Possible Solution**
Maybe [React Portals](https://reactjs.org/docs/portals.html) would be a solution if somehow ag-grid-react is unable to properly render React components as children.

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2114 - React Components are rendered to the root of the DOM tree 

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by ashrafhadden** [comment]
@makinggoodsoftware Awesome, thank you!

Small fix, you should replace `DOM tree` in your pipeline issue title with `Virtual DOM tree`. Big difference between dom tree and virtual dom tree.
