### ISSUE TITLE
Cannot define default column types?

### ISSUE THREAD

**Issue by martixy** [ag-grid/ag-grid#2593]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```
Not sure if bug report, or feature request, as it might come off as a pointless level of indirection, but IMO it's a nice method of grouping/naming a bunch of functionality.

In any case, defining a default column type does not currently work as expected.
Here's a random plunk:
https://plnkr.co/edit/XHYCFisZhwW22JUHcvf3
(First two columns do not explicitly define a type, so should be inheriting the default column type. It isn't happening at the moment.)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We agree that what you highlight is correct, but upon discussion with the dev team, we have decided not to create a feature request for this.

Note that we need to make sure that we add the right amount of complexity in the grid so, in the long run, we can deliver more features that are useful to as much customer as possible.

You can, however, set the type of the column individually to your colDefs.

Thanks
