### ISSUE TITLE
Line break followed by spaces in template causes TypeError

### ISSUE THREAD

**Issue by vilyus** [ag-grid/ag-grid#2595]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Set the template in the headerComponentParams to have `'\n   '` character sequence
- See cryptic TypeError in console
- Plunkr: https://plnkr.co/edit/hL3NB1Sbs5dchjZZruGE

**Current behavior**
`[unpkg.com/ag-grid@18.1.2/dist/ag-grid.js:6994] Uncaught TypeError: _this.eGui.querySelector is not a function`

**Expected behavior**
Should work as if it was written in one line.

**Please tell us about your environment:**
Reproduced even in planker

* **ag-Grid version:** 18.1.2

* **Browser:**
Chrome `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36`

* **Language:** ES5, ES6/7

**Comment by vilyus** [comment]
Seems to be reproducible with every template that starts with whitespace (checked `\n` and ` `)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2115 - headerComponentParams template with line breaks followed by spaces ('\n ') causes TypeError

You can follow the status of feature requests, bugs and releases using our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
