### ISSUE TITLE
Column sorting not working in chrome 44

### ISSUE THREAD

**Issue by NivNavick** [ag-grid/ag-grid#2598]
Tried using ag-grid v17 on chrome 44, however the grid is not sorting columns(when clicking on columns header) from ASC to DESC and invert. It's working though in more recent versions of chrome.

**Current behavior**
Columns not sorted when click on columns header

**Expected behavior**
Grid will sort columns

* **ag-Grid version:**
 V17

* **Browser:**
Chrome 44
* **Language:** 
[ ES6]

**Comment by uvtzxpm** [comment]
Chrome 44 is ancient:

https://github.com/ag-grid/ag-grid/issues/2531#issuecomment-408540115

Not very helpful, I know. You'll have to fix it yourself if it really matters.

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that we only support recent browser versions, especially for Chrome

Thanks
