### ISSUE TITLE
Server side pagination with virtual scrolling

### ISSUE THREAD

**Issue by mikila85** [ag-grid/ag-grid#2599]
Hi, 
Is it possible in ag-grid to do Server side pagination with virtual scrolling?

Example:
[Demo](http://swimlane.github.io/ngx-datatable/#virtual-paging)

**Comment by mikila85** [comment]
After seeing most of the closed issues i see you take us (customers in the "free" version ) very lightly even though some of the customers are developers from large companies that are considering purchase the OEM version but seeing this make me look to other places, good luck in the future.

**Comment by uvtzxpm** [comment]
> but seeing this make me look to other places

Most of the other grids are not good, you'll be back.

The problem with your question is that you put zero effort in to it.

You should look at the documentation:
- https://www.ag-grid.com/javascript-grid-row-models/
- https://www.ag-grid.com/javascript-grid-pagination/

If you've already looked, you should explain why none of the available options work for you.

**Comment by mikila85** [comment]
@uvtzxpm 
I tried it in your plnkr demos and it seems to not working:

[My Try](https://plnkr.co/edit/XdrNSH?p=preview)

on virtual scroll it wont update the currentPage (on top) and when you add pagination:true, to the options you only see the first 20 of every page and the virtual scroll stops working..

**Comment by mikila85** [comment]
just saying.. your communication here is amazing!..
thx alot we bought a different grid.

**Comment by makinggoodsoftware** [comment]
Hi

Sorry to see that you felt let down, unfortunately, we have a very large customer base and we prioritize that.

Note that we are now actively monitoring github, so hopefully in the future, we won't have any more cases like this.

Also, feel free to reach out to us if you need/want more information

In any case whichever grid you choose we hope that it fits your business needs.

Thanks and sorry for the inconvenience
