### ISSUE TITLE
[component] stop using id's in the html

### ISSUE THREAD

**Issue by greglockwood** [ag-grid/ag-grid#260]
As I'm sure you're aware, `id` properties are meant to be unique for an entire page. Not only are `centerRow` and `south` common words that could easily conflict with an existing ID, but by being IDs, they guarantee only being able to use one grid per page.

I recommend changing to `ag-`prefixed classes instead, to minimize the chance of conflicts.

**Comment by ceolter** [comment]
Thanks for raising. I was lazy. I'll get this sorted. Can you advise, what is this actually stopping? Working myself, I find if I use fully qualified CSS selectors (ie id's are unique within the scope of their parents) then I can select anything???

**Comment by greglockwood** [comment]
I don't have a concrete problem the use of id's is causing, I am just
pointing out a potential cause of problems for other people in the future.

For example, what if I did "document.getElementById("south")", expecting to
get my own bottom layout div for the whole page? Because it is after your
grid in the markup, your div would be returned instead.

A similar problem could occur if I had a CSS selector of "#south" to style
some div on my page, but which ended up breaking your grid.

Of course, since this is not actually causing any problems at present for
me, and probably others, you can put it near the bottom of your backlog.

**Comment by ceolter** [comment]
cool. i plan on doing some major rework around the layout in about 4 weeks from now (might be longer), to make some performance improvements. i will change it all then, if not already done before.

**Comment by togakangaroo** [comment]
Did this ever end up happening? Not certain if it did and maybe I have an old version...

**Comment by ceolter** [comment]
nope, i'm still using id's. none of the browsers have any issues with using the same id more than once, and nobody has reported a problem, just people reporting that they see what i'm doing and i say "yes i know, i've not problem with it, do you?" and the answer is always no, nobody has a problem.

**Comment by Thom1729** [comment]
I am having this problem in a real application. The site CSS includes styling for '#center' and others, which is breaking the grid layout badly. The non-uniqueness of the IDs isn't the problem but rather the use of non-prefixed IDs that are likely to conflict with other IDs on the page. Changing the IDs to "ag-center" and the like would fix the problem for me, although of course it would be better to use classes.

It is perhaps true that "center" is not a very good ID for our page, being presentational in nature rather than semantic, but that decision was made a long time ago by persons unknown, and it's not in the budget to overhaul the page layout. As long as the auto-generated IDs are causing collisions, I don't see how I can use ag-grid on our site, which is a shame because we all really hate jqxGrid.

**Comment by togakangaroo** [comment]
@Thom1729 can you can qualify your css? something like 

      :not(.ag-grid) #center

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-54

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
