### ISSUE TITLE
Manage footer rows height

### ISSUE THREAD

**Issue by PedramMarandi** [ag-grid/ag-grid#2603]
**I'm submitting a ...**
[x] support request 
________________________________
I have a total footer for each of my groups. I want to manage the heights and I tried various solutions and none of them actually worked.

<img width="1036" alt="screen shot 2018-08-30 at 10 24 11 am" src="https://user-images.githubusercontent.com/7813872/44841976-fc677080-ac87-11e8-8491-1fe29ca15abc.png">

I tried the below gridOption, and it does not work:

` getRowHeight={(params) =>{
           if (params.node.footer) {
              return 80;
           }
           return 43;
        }`

But when I increase the height of my group row -- W/C .... -- the footer height increases too.

Any idea how can I control group total rows? or if there is not, any idea how can I inject a row to each group?

**Comment by PedramMarandi** [comment]
Any solution to this problem?

**Comment by makinggoodsoftware** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, you should be able to find more information in the following links:

https://www.ag-grid.com/javascript-grid-styling/

You should be able to customize your own theme to achieve this.

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
