### ISSUE TITLE
Automatic 'Tabbing into the grid' when using floating filters and movable columns

### ISSUE THREAD

**Issue by sushitommy** [ag-grid/ag-grid#2605]
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
Right now, if you use floating filters it is really hard to enable 'Tabbing into the grid' [as described here](https://www.ag-grid.com/javascript-grid-keyboard-navigation/#tabbing-into-the-grid), especially with moving columns. The last element that has focus before the grid will be the floating filter element of the last column. You have to manually find that last focusable element (which could change when the user moves columns) and listen for its TAB keydown event to properly set the focus to the grid.

**Expected behavior**
When using floating filters, you're sure the last element will always be an AG-grid element. Therefore, I'd expect the tabbing to work automatically as AG-grid can figure out when to tab into the grid and add the event handler automatically.

**Please tell us about your environment:**
WinX64, IntelliJ, NPM, Tomcat

* **ag-Grid version:** 18.1.2

* **Browser:**
All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES7 transpiled with Babel

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-1334 | Allow tab key follow the correct order when tabbing in and out of floating filters
-- | --
