### ISSUE TITLE
Export to xlsx Functionality with style not provided 

### ISSUE THREAD

**Issue by dheerendrasingh5191445** [ag-grid/ag-grid#2607]
hi ag-grid,

i am creating this issue because i m stuck i m not able add style while exporting grid to xlsx as there no example provided to export with style in .xlsx category please provide anyway to do this.
the example of exporting to .xlsx without style is given in your documentation but with style its not there and in my project i want to add the style to excel in .xlsx format.

thanks,
dheerendra singh

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
CSV/Excel Export | AG-726 | Export to XLSX
-- | -- | --

**Comment by MatthewHerbst** [comment]
@makinggoodsoftware There is no reference to "AG-726" or to "XLSX" in the pipeline when searching for those terms. Has the issue been completed? I don't see any examples of how to pass styles to XLSX in the [docs](https://www.ag-grid.com/javascript-grid-excel/). All it says now is:

> Note that this example doesnt't [sic] import the styles to xls. To add styling to the xlsx, the logic could be extended to read the XML styling information received from `gridOptions.api.getDataAsExcel(params)`, and it could thn [sic] be passed into SheetJs through the object returned by `XLSX.read(content, {type: 'binary'})`.

Would updating those docs to show that be possible please? Or just tell us how to do it here for now?

I am in a trial mode looking to go paid Enterprise, but that won't happen if we can't get these and other features working.

**Comment by MatthewHerbst** [comment]
Should note that this issue is a duplicate of https://github.com/ag-grid/ag-grid/issues/2208

**Comment by MatthewHerbst** [comment]
From poking around in the [XLSX code](https://github.com/SheetJS/js-xlsx/blob/9866dfc010338394e4cfcd33a9fbc15dae017ee5/types/index.d.ts#L111), for my purposes at least (basic number formatting, trivial styles), it was as simple as doing:

```javascript
const workbook = XLSX.read(
  content,
  {
    cellNF: true,
    cellStyles: true,
    type: 'binary',
  }
);
```

**Comment by MatthewHerbst** [comment]
This can be closed, woot, thank you! https://github.com/ag-grid/ag-grid/releases

**Comment by im-mohan** [comment]
Hi @makinggoodsoftware  ... I have a requirement to export an excel with "**freezed header**" . Does Ag-grid enterprise version has any option to set the  header as freezed . I did not find anything on the site.
