### ISSUE TITLE
 ag-grid getColumnState() never return groups

### ISSUE THREAD

**Issue by Pradeepg21** [ag-grid/ag-grid#2615]
Hi,
getColumnState() is only returning the children columns state but expectation is to return the columns including the groups for ag-grid
**example**: Below scenario
**_saved state is:    Array(14)
					0:
						children:Array(13)
						0:{headerName: "Unit1", field: "Unit1", enableRowGroup: true, enablePivot: true, hide: false}
						1:{headerName: "Unit2", field: "Sub Business Unit2", enableRowGroup: true, enablePivot: true, hide: false}
						...
						...
						2
						__proto__:Array(0)
						headerName:"Main Header"
						__proto__:Object
					1:{headerName: "Header2", children: Array(4)}
					2:{headerName: "Product1", children: Array(24)}
					3:{headerName: "Product2", children: Array(41)}
					...
					..._**
so if I change the unit1 with unit2, I should get the whole output as above with grouping and only change in uint1 and unit2.
I tried below methods also, but no help:
getColumnGroupState()
getAllDisplayedColumns() etc

Please check and let us know if any other method is there to get the proper result i.e children columns with header groups.
Thanks,

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as designed, you need to call different methods to obtain different information, I am afraid that at this time we don't have any plans to revamp the API on this area either

Thanks
