### ISSUE TITLE
grid does not look into frameworkComponents for named component

### ISSUE THREAD

**Issue by martixy** [ag-grid/ag-grid#2616]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
See here:
https://www.ag-grid.com/javascript-grid-filter-component/#example-vue-filter
(I'd provide a plunker, but the example on that page can't be forked)

See how the column definition is given the actual component.

**Current behavior**
If that component is, instead put in the "frameworkComponents" and the column definition is only provided the relevant name, the component is not initialized properly.
It does look inside if the column definition defines the name as a regular component (e.g. `filter` not `filterFramework`).
Either the documentation needs fixing or the behaviour of the program.

Minor case in point: [Here](https://www.ag-grid.com/javascript-grid-components/) it says that all examples use registration by name, while this is clearly not true in the example above I linked.

**Expected behavior**
Components defined in `<componentName>Framework` in column definitions should look in `frameworkComponents` for the same name.
Components defined in `<componentName>` in column definitions should look in `components` for the same name.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** 18.1.2

* **Browser:** N/A

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that this is working as designed, is there any scenario that you can think of where this approach will cause issues?

Thanks
