### ISSUE TITLE
cellContextMenu Event does not Trigger for Headers

### ISSUE THREAD

**Issue by nsankaranarayanan** [ag-grid/ag-grid#2621]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When you right click on the header the cellContextMenu event does not fire though it fires for in the data rows.

**Expected behavior**
Event should fire irrespective of header or rows indicating where it was clicked.

**Please tell us about your environment:**
* **OS:** Windows 10
* **Browser:** Chrome
* **ag-Grid version:** 17.1.1

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2101 - Events- cellContextMenu event does not trigger on column header

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
