### ISSUE TITLE
Select/Deselect All in tool panel gets delay of 10-15 seconds in rendering columns

### ISSUE THREAD

**Issue by sush154** [ag-grid/ag-grid#2622]
**I'm submitting a support request  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Currently, we are displaying more than 160 columns (need to display) in ag-grid. When we try to select/deselect all columns from tool panel it takes around 15-20 seconds to render the columns. When we checked the demo by ag-grid by providing 100 cols and 10000 rows, we were able to see the delay. We tried to provide loading spinner, but, there is no way to intercept select/deselect all checkbox event.

**Expected behavior**
Either it should load under 2-3 seconds or can we intercept select/deselect all checkbox event

**Please tell us about your environment:**
**Operating System:** windows
**Package Manager:** npm 3.10.10

* **ag-Grid version:** 17.1.0

* **Browser:** Internet Explorer, Chrome

* **Language:** [Angular 5.1.3 | TypeScript 2.4.2 | ES6]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-1591 | Allow delta changes to columns
-- | --

**Comment by huzan123** [comment]
Hi was there any update to this?  I'm using the headerCheckboxSelection : true in my column, but on clicking the checkbox it takes around 10 seconds for all the rows to get selected and highlighted.  Not only that, it also causes my entire web page to freeze!
I tried with ag-grid enterprise v..21 and 23 but no luck.  Any help would be really appreciated.
Many thanks.
