### ISSUE TITLE
Filters sidebar not shown with Server-side row model

### ISSUE THREAD

**Issue by ngocketit** [ag-grid/ag-grid#2623]
Hi,

I'm trying out this example of server-side row model with Spark https://www.ag-grid.com/spark-server-side-operations/. However, the Filters sidebar doesn't show up even when I set: `sideBar=true`. Any ideas what's gone wrong?

Thanks!

**Comment by makinggoodsoftware** [comment]
The sidebar was introduced in v19 of ag-grid, if you update the example you should see it
