### ISSUE TITLE
AG-Grid Custom Date Component issues on filter button

### ISSUE THREAD

**Issue by srikant21** [ag-grid/ag-grid#2625]
**Current behavior:-**
AG-Grid Custom Date Component is creating 2 issues:-
1) On clicking the filter button and then clicking on the filter input box, the custom calendar date picker pops up. But when I am changing the month from calendar [or clicking on any other calendar field], the filter drop-down box is getting closed.This is my first issue.
2)From the filter box I have selected "In range" option. When I fill the first date filter text it should not close the filter drop-down box because I have not filled the 2nd date filter box. But it is getting closed.

**Expected Behavior:-**
1)Filter drop-down should not close until I finish my selection from my calendar date picker.
2)Filter drop-down should not close until I fill the two filter text box for "In range" option.

**System specification**
ag-Grid version: 18.1.1
Language: [all | TypeScript X.X | ES6/7 | ES5]
TypeScript-2.3.3

stackblitz:-
https://stackblitz.com/edit/angular-yox3bv?file=src%2Fapp%2Fapp.component.css

**Comment by srikant21** [comment]
Can any one please reply on this?I am not whether it is a bug or I am doing something wrong.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-1891 | Filters - Add a mechanism for keeping the filter menu open
-- | --

**Comment by altsanz** [comment]
Hi, I cannot see issue AG-1891 on pipeline. What is its status?

**Comment by hughanderson4** [comment]
There is not 1891 in pipeline and there is not documentation how to keep filter open.
Please provide proper hyperlink how to achieve it.  My custom date picker always close before I can finish date selection.

**Comment by crhk** [comment]
Hello,
I know this issue is closed but like @hughanderson4 I can't find the doc on how to keep the filter open.
Any news ?
Thanks

**Comment by PTC-JoshuaMatthews** [comment]
Also doesn't seem to be working for me on v23, says it was fixed in v20. Any way to get an update on this @gportela85
