### ISSUE TITLE
Dropdown in Cell

### ISSUE THREAD

**Issue by sliceofbytes** [ag-grid/ag-grid#2640]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

I'm attempting to have an `Action` cell with a dropdown button within a cell.  This worked in 17.x but no longer works in the current version.

**Providing a Reproducible Scenario**
- Create a component with a dropdown menu and render it in a cell using cellRendererFramework.
- Example: https://stackblitz.com/edit/ng2-ag-grid

**Current behavior**
Regardless of cell styling dropdown menu will be hidden behind other rows.

**Expected behavior**
Setting the sell to a class which includes `overflow:visible` should allow the overflowed content to be visible (Not hidden behind other rows).

* **ag-Grid version:** 18.1.2

* **Browser:**
Chrome, Firefox etc..

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36

* **Language:** All

**Comment by sliceofbytes** [comment]
I've found one possible solution but I don't like it. I shouldn't need to rely on row focus to allow a dropdown menu to be visible.

`.ag-row {
  z-index:0;
  &.ag-row-focus {
    z-index:1;
  }
}
`

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:


AG-1617 | Allow complex tooltip/renderer components in ag-grid to stick to the row as the user scrolls
-- | --


It is estimated for our next release

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by kopach** [comment]
Hi. With current implementation of ag-grid I’ve found only possibility to show[ tooltip on mouse hover](https://www.ag-grid.com/javascript-grid-tooltip-component/) and possibility to show [context menu on right mouse click](https://www.ag-grid.com/javascript-grid-context-menu/). But it's still not clear how to show context menu or dropdown menu on button click in cell (as per example in description of this ticket) with native ag-grid API. Could anyone adwise me with this?

**Comment by sudhirkaushk** [comment]
> AG-1617	Allow complex tooltip/renderer components in ag-grid to stick to the row as the user scrolls
> You can follow the status of feature requests, bugs and releases using our pipeline:
> https://www.ag-grid.com/ag-grid-pipeline/
> 

No such issue found in Pipeline as on 4 august 2019

![ag grid 1617](https://user-images.githubusercontent.com/8871502/64243935-d3765d00-cf25-11e9-80ac-3849f69691f6.PNG)

**Comment by smurugavels** [comment]
I started with a ICellRendererAngularComp to display an inline dropdown but understood, ag-grid has dropdown item display issue. So while googling for a resolution from community, I came across these dropdown issues. This may not be all but wanted to let this team know about them.

https://github.com/ag-grid/ag-grid/issues/1228
AG-824
AG-2660
AG-2495
AG-1754

@ceolter @makinggoodsoftware  Please consider providing fixes on these problems.

**Comment by rogoja** [comment]
Someone found a solution?

**Comment by smurugavels** [comment]
A html select worked in my case.
Also we were using PrimeNg's dropdown component. It had an **appendTo** property that can attach the overlay panel element (which is the pull down layer of a PrimeNg's drop down) to html's body.
This could be of help to someone.

**Comment by hectorloboenee** [comment]
> I've found one possible solution but I don't like it. I shouldn't need to rely on row focus to allow a dropdown menu to be visible.
> 
> ```
> .ag-row {
>   z-index:0;
>   &.ag-row-focus {
>     z-index:1;
>   }
> }
> ```

this worked for me.
