### ISSUE TITLE
CellRenderer Components Are Not Instantiated With Parent

### ISSUE THREAD

**Issue by tundebabzy** [ag-grid/ag-grid#2641]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

According to examples given on how to [define custom `CellRenderer`](https://www.ag-grid.com/javascript-grid-cell-rendering-components/#vuejs-cell-rendering), you might have something like this:
```
components: {
   SomeCellRenderer: {
      <template>: '<em>Yes sir</em>'
   }
}
```

However, if you import a Single File Component (SFC) for use as the `CellRenderer`, the SFC's `$parent` attribute is undefined.

To reproduce this:
- create a simple SFC component
- In the `created` hook, add `console.log(this.$parent)`
- Import the SFC into your grid and use it as the `CellRenderer`

`this.$parent` will be `undefined`

I traced this to the `createAndMountComponent` method
```
static createAndMountComponent(params, componentType) {
        let details = {
            data: {
                params: Object.freeze(params)
            }
        };

        let component = new componentType(details);
        component.$mount();
        return component;
    }
```

**Expected behavior**

I expect that `this.$parent` should not be `undefined`.

I can send a fix which will utilize the parent which is already available to the `VueComponentFactory` class as `this.parent`

**Please tell us about your environment:**

Ubuntu 18

* **ag-Grid version:** X.X.X

19.0.0

* **Browser:**

"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0" 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by makinggoodsoftware** [comment]
Hi

I believe this issue is now fixed in your end, I am going to close this issue

Thanks
