### ISSUE TITLE
Edit mode lost on grid updates

### ISSUE THREAD

**Issue by benitogf** [ag-grid/ag-grid#2648]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://next.plnkr.co/edit/Q4WoiTy5nXq9MGCx

Current behaviour.
Edit mode is lost when new elements are added to the grid or the sorting changes the order

Expected behaviour.
It should keep on edit mode after updates

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by benitogf** [comment]
alright :100:  thanks, have a nice day

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2103 - Allow editing cell focus to retain when new rows are added or the sorting changes the order 

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
