### ISSUE TITLE
Utils.isBrowserSafari Check causing namespace error

### ISSUE THREAD

**Issue by soorajshankar** [ag-grid/ag-grid#2649]
I'm submitting a issue which is happening inconsistently especially when i use it with amchart export plugin.
Bug Report 
**Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
    at eval (utils.js?211a:919)
    at Function.Utils.isBrowserSafari (utils.js?211a:920)
    at HeaderGroupComp.setupLabel (headerGroupComp.js?696e:95)
    at HeaderGroupComp.init (headerGroupComp.js?696e:43)
    at ComponentResolver.initialiseComponent (componentResolver.js?9a28:290)
    at ComponentResolver.createAgGridComponent (componentResolver.js?9a28:241)
    at ComponentRecipes.newHeaderGroupComponent (componentRecipes.js?10e5:52)
    at HeaderGroupWrapperComp.appendHeaderGroupComp (headerGroupWrapperComp.js?ffd5:108)
    at HeaderGroupWrapperComp.postConstruct (headerGroupWrapperComp.js?ffd5:58)
    at eval (context.js?450d:215)
(anonymous) @ utils.js?211a:919
Utils.isBrowserSafari @ utils.js?211a:920
HeaderGroupComp.setupLabel @ headerGroupComp.js?696e:95
HeaderGroupComp.init @ headerGroupComp.js?696e:43
ComponentResolver.initialiseComponent @ componentResolver.js?9a28:290
ComponentResolver.createAgGridComponent @ componentResolver.js?9a28:241
ComponentRecipes.newHeaderGroupComponent @ componentRecipes.js?10e5:52
HeaderGroupWrapperComp.appendHeaderGroupComp @ headerGroupWrapperComp.js?ffd5:108
HeaderGroupWrapperComp.postConstruct @ headerGroupWrapperComp.js?ffd5:58
(anonymous) @ context.js?450d:215
(anonymous) @ context.js?450d:215
Context.postConstruct @ context.js?450d:212
Context.wireBeans @ context.js?450d:75
Context.wireBean @ context.js?450d:69
HeaderRowComp.createHeaderComp @ headerRowComp.js?beeb:207
(anonymous) @ headerRowComp.js?beeb:178
HeaderRowComp.onVirtualColumnsChanged @ headerRowComp.js?beeb:154
HeaderRowComp.onDisplayedColumnsChanged @ headerRowComp.js?beeb:143
(anonymous) @ eventService.js?939b:139
Utils.forEachSnapshotFirst @ utils.js?211a:1003
EventService.dispatchToListeners @ eventService.js?939b:134
EventService.dispatchEvent @ eventService.js?939b:117
ColumnController.updateGroupsAndDisplayedColumns @ columnController.js?efb9:1684
ColumnController.updateDisplayedColumns @ columnController.js?efb9:1547
ColumnController.setColumnDefs @ columnController.js?efb9:1330
Grid.setColumnsAndData @ grid.js?e5e9:163
Grid @ grid.js?e5e9:137
AgGridReact.componentDidMount @ agGridReact.js?4fcc:61
proxiedComponentDidMount @ createPrototypeProxy.js?6ea8:66
(anonymous) @ ReactCompositeComponent.js?063f:264
measureLifeCyclePerf @ ReactCompositeComponent.js?063f:75
(anonymous) @ ReactCompositeComponent.js?063f:263
notifyAll @ CallbackQueue.js?7abf:76
close @ ReactReconcileTransaction.js?2d36:80
closeAll @ Transaction.js?91bc:209
perform @ Transaction.js?91bc:156
perform @ Transaction.js?91bc:143
perform @ ReactUpdates.js?be0d:89
flushBatchedUpdates @ ReactUpdates.js?be0d:172
closeAll @ Transaction.js?91bc:209
perform @ Transaction.js?91bc:156
batchedUpdates @ ReactDefaultBatchingStrategy.js?bdd7:62
batchedUpdates @ ReactUpdates.js?be0d:97
reactionScheduler @ mobx.module.js?cbdf:3191
runReactions @ mobx.module.js?cbdf:3167
endBatch @ mobx.module.js?cbdf:2715
endAction @ mobx.module.js?cbdf:947
executeAction @ mobx.module.js?cbdf:914
res @ mobx.module.js?cbdf:902
(anonymous) @ UIFunctions.js?8631:816
Promise.then (async)
switchChart @ UIFunctions.js?8631:803
(anonymous) @ ChartFooter.js?71c9:178
Promise.then (async)
(anonymous) @ ChartFooter.js?71c9:156
Promise.then (async)
handleCategoryChange @ ChartFooter.js?71c9:146
setLoggedIn @ createPrototypeProxy.js?6ea8:44
fireChange @ Select.js?feca:899
onMenuSelect @ Select.js?feca:401
onClick @ Menu.js?6dfb:155
onClick @ MenuItem.js?1ca1:137
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js?8875:69
executeDispatch @ EventPluginUtils.js?5685:85
executeDispatchesInOrder @ EventPluginUtils.js?5685:108
executeDispatchesAndRelease @ EventPluginHub.js?3c44:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js?3c44:54
forEachAccumulated @ forEachAccumulated.js?2859:24
processEventQueue @ EventPluginHub.js?3c44:254
runEventQueueInBatch @ ReactEventEmitterMixin.js?9870:17
handleTopLevel @ ReactEventEmitterMixin.js?9870:27
handleTopLevelImpl @ ReactEventListener.js?e4aa:72
perform @ Transaction.js?91bc:143
batchedUpdates @ ReactDefaultBatchingStrategy.js?bdd7:62
batchedUpdates @ ReactUpdates.js?be0d:97
dispatchEvent @ ReactEventListener.js?e4aa:147**
 
I found this is because of the file utils.js and Utils.isBrowserSafari method. 
https://github.com/ag-grid/ag-grid/blob/master/dist/lib/utils.js#L1003
can be changed to 
                    return p?p.toString() === "[object SafariRemoteNotification]":false;

Please fix Asap...

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but we will reopen it if we are provided with a reproduction scenario as specified above

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
