### ISSUE TITLE
ColDef.sortingOrder expects null value but doesn't allow them in its type definition

### ISSUE THREAD

**Issue by madakk** [ag-grid/ag-grid#2653]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The current type definition of `ColDef.sortingOrder` is `string[]`, yet the values it expects are either `'asc'`, `'desc'`, or `null`. This leads to a TypeScript error if supplying null as a value. A better type definition would be `('asc' | 'desc' | null)[]` or `(string | null)[]`.

**Please tell us about your environment:**

* **ag-Grid version:** 19.0.0

* **Browser:** Chrome

* **Language:** TypeScript 3.0

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2102 - Typescript - Improve typescript typings

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:
