### ISSUE TITLE
Make refreshInfiniteCache observable or with callback parameter

### ISSUE THREAD

**Issue by mblataric** [ag-grid/ag-grid#2658]
**I'm submitting a ...**  
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Hi, 

I am testing out free version of ag-grid in infinite row model and I have trouble with refreshInfiniteCache function. 
It seems it works in async mode because my code below refreshInfiniteCache is executed before grid actually refreshes (I am trying to find newly added record, but get always null because refresh process is not finished yet).  
I tried using setTimeout just to confirm and it works, but hard-coding setTimeout wait period is a bad idea. 

A better solution would be making refreshInfiniteCache observable or allow callback parameter so we can execute code once refresh procedure is completed. 

Regards,
Mario

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by Dimitri-Habruk** [comment]
Where is the answer?
