### ISSUE TITLE
TypeScript: `agInit` should not be required for React custom cell renderer components

### ISSUE THREAD

**Issue by antmdvs** [ag-grid/ag-grid#2659]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I implement my custom React Cell Renderers in TypeScript like this:
https://github.com/antmdvs/ag-grid-19-react-custom-renderer-ts-issue/blob/master/src/MyCellRenderer.tsx#L5-L6

As the code comments describe, as of ag-Grid 19.0.0, this results in a TypeScript error:

> src/MyCellRenderer.tsx:5:14 - error TS2420: Class 'MyCellRenderer' incorrectly implements interface 'ICellRendererReactComp'.
>  **Property 'agInit' is missing in type 'MyCellRenderer'.**

Repro steps:
1. Clone the repository https://github.com/antmdvs/ag-grid-19-react-custom-renderer-ts-issue
2. `npm install`
3. `npx tsc`

**Expected behavior**
No error, since `agInit` is not required for React components:
https://www.ag-grid.com/javascript-grid-cell-rendering-components/#react-methods-lifecycle

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:**
19.0.0

* **Browser:**
n/a

* **Language:**
TypeScript 2/3

**Comment by giniedp** [comment]
same applies to angular components. For side panel components `agInit` is not needed, because dependencies can be resolved via dependency injection in the constructor.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-2092 | Frameworks - typeScript agInit should not be required for React custom cell renderers
-- | --


It is estimated for our next release

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
