### ISSUE TITLE
Internationalization for the "AND" and "OR" words of the filter

### ISSUE THREAD

**Issue by SlimenTN** [ag-grid/ag-grid#2660]
from your [Internationalization page](https://www.ag-grid.com/javascript-grid-internationalisation/)  can't find how to change the `AND ` and `OR ` words of the filter !!
Check this [image](https://i.stack.imgur.com/DsiJf.png) please.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2104 - Filters - Add the ability to Internationalise the "AND" and "OR" words of the filter

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
