### ISSUE TITLE
Using unescaped '#' characters in a data URI body is deprecated

### ISSUE THREAD

**Issue by cancan101** [ag-grid/ag-grid#2664]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
I see the following warning in console:
```
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

(anonymous) | @ | tabbedLayout.js:42
-- | -- | --
  | e.getMinWidth | @ | tabbedLayout.js:35
  | t.getMinWidth | @ | enterpriseMenu.js:142
  | (anonymous) | @ | enterpriseMenu.js:60
  | e.showMenu | @ | enterpriseMenu.js:79
  | e.showMenuAfterButtonClick | @ | enterpriseMenu.js:52
```

**Current behavior**

I open the context menu:
![image](https://user-images.githubusercontent.com/51059/46214105-564f6a80-c308-11e8-9026-498766c68627.png)

**Expected behavior**

No warnings in console.
**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

```
    "ag-grid": "^18.1.2",
    "ag-grid-enterprise": "^18.1.1",
    "ag-grid-react": "^18.1.0",
```
* **Browser:**

`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"`
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
`ES6`

**Comment by cancan101** [comment]
There is an unanswered SO post on this: https://stackoverflow.com/questions/51199244/using-unescaped-characters-on-ag-grid-enterprise-react-on-context-menu

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-1789 | Column Menu - Remove '[Deprecation] Using unescaped '#' characters in a data...' message
-- | --
