### ISSUE TITLE
bring back finished property on ColumnMovedEvent

### ISSUE THREAD

**Issue by scottkunkel** [ag-grid/ag-grid#2668]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

ColumnMovedEvent lost finished property. As a result, dragstopped has to be queried to figure out if the move is complete. Unfortunately dragstopped is also called for other events (dragging into toolpanel), making event handling and refreshes tough.

**Expected behavior**

Bring back finished property on ColumnMovedEvent

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

18.1.2

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 3.0.3

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by scottkunkel** [comment]
19.0.1 seems to bring back the finished event. However, it seems to be set to true when the column 'snaps' into a different position. The mouse is still 'holding' the column and moving it.
I would expect finished only to be true when the mouse lets go of the column.

**Comment by makinggoodsoftware** [comment]
Hi,

Is it possible that you are confusing ColumnMovedEvent with ColumnResizedEvent, the first one never had this property, while the second one does...

Note that we are going to close this issue now, if you want to follow up, please create a new issue in github, thanks
