### ISSUE TITLE
Auto Height Dom Layout Rendering Vertical Scroll Bar with Tiny Travel 

### ISSUE THREAD

**Issue by andystroz** [ag-grid/ag-grid#2671]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Setting `this.gridOptions.domLayout = 'autoHeight';` properly sizes my css component to the size of the grid with all rows displayed. However, it does not remove the vertical scroll bar completely and gives it a very small travel. The [grid auto height example](https://www.ag-grid.com/javascript-grid-width-and-height/) on your website has the same problem as well.

**Expected behavior**

I would like to option to completely remove the vertical scroll bar or a way to edit it in its current state to disable using that scrollbar / hiding it.

**Please tell us about your environment:**
I am using ag-grid community 19.0.0 

* **ag-Grid version:** 19.0.0

and ag-grid angular 19.0.0 in Angular 6.

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

* **Language:** [ Angular 6 | ES7 ]

* **Scenario:**

The issue can be seen [here](https://plnkr.co/edit/BkkKEB8Qi8Xl51nzq97t?p=preview). As seen in the sample on your website the vertical scroll bar takes up almost all of the space leaving a small travel. Is it supposed to be this way or is there a way to remove it?

I am not sure if this is a bug report or a feature request because it seems as though the scroll bar should be removed using the auto height feature.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by paulfleifleh** [comment]
For anyone looking for a temp quick fix, either remove the  overflow-x  on .ag-body-viewport.ag-layout-auto-height or remove the margin-bottom: -2px;  on .ag-body-container

**Comment by 6apc1k** [comment]
Hi, 
Could you, please, advise if this is the  ticket and if it's going to the next release:
AG-2145 | domLayout='autoHeight' adds a vertical scrollbar
Thank you

**Comment by makinggoodsoftware** [comment]
Hi,

Sorry for the late reply, I can confirm that is the ticket and that it was release in 19.1

**Comment by alexisagos** [comment]
Hi,
I still have this problem in 19.1.4, has this been fixed ?
