### ISSUE TITLE
suppressMultiRangeSelection does not seem to work

### ISSUE THREAD

**Issue by b3f3** [ag-grid/ag-grid#2674]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Hi,
It seems that "suppressMultiRangeSelection" does not work.
This is the case on the dedicated documentation page :
https://www.ag-grid.com/javascript-grid-range-selection/#range-selection-example-suppress-multi
Thanks
Benjamin

**Comment by makinggoodsoftware** [comment]
Hi,

I have just tried this and it seemed to work in my end, if you think this is still an issue, feel free to open another issue, but please include more evidence, screen captures.. gifs.. etc

Thanks
