### ISSUE TITLE
Unable to add styling to the export to excel (XLSX)

### ISSUE THREAD

**Issue by ruthwik1117** [ag-grid/ag-grid#2678]
Please let us know how we can apply styles to while exporting grid to xlsx. In ag-grid documentation they didn't provide anything related to styles to .xlsx.
We are using ag-grid enterprise version(19.0.0) does this feature available for this version or not ?

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

CSV/Excel Export | AG-726 | Export to XLSX | BACKLOG |   |  
-- | -- | -- | -- | -- | --
