### ISSUE TITLE
Need ag-Grid free version column filter in Enterprise

### ISSUE THREAD

**Issue by harshabada** [ag-grid/ag-grid#2679]
**Customer of ag-Grid**
Yes

Current behaviour:
Column filter showing differently after upgrade to Enterprise grid

Expected behaviour:
Need free version column filter behaviour 

Used with Angular 5.1 (TypeScript)
* **ag-Grid version:** ----	"ag-grid-enterprise": "~17.1.0",

**Comment by makinggoodsoftware** [comment]
Hi

It sounds like you are a customer, would you mind following up on the official zendesk support channel?

Do you know how to access it?

Thanks

**Comment by makinggoodsoftware** [comment]
Closing this as we assume this is not an issue anymore
