### ISSUE TITLE
column header is not aligned with the rest of the grid when RTL mode is enabled on android

### ISSUE THREAD

**Issue by HyperComplex** [ag-grid/ag-grid#2680]
**I'm submitting a bug**
```
[x] bug report => see 'Providing a Reproducible Scenario'
```
**Requesting Community Support**

**Providing a Reproducible Scenario**
- Visit the RTL page https://www.ag-grid.com/javascript-grid-rtl/  first demo or second demo from android using google chrome in landscape mode  and try to scroll horizontally.

**Current behavior**
- When you try to scroll horizontally the grid header is not aligned with the lower part of the grid, when you scroll horizontally to the right column header goes to left and vice versa.

**Expected behavior**
The column header must be aligned with the lower part of the grid

**Please tell us about your environment:**
Operating system : android 4.4.2

* **ag-Grid version:** 
- 18 in angular 5 project (my project).
- The used version in the grid website.

* **Browser:**
Browser: google chrome latest version 69.0.3497.100

Thank you.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2198 - Columns - column header is not aligned with the rest of the grid when RTL mode is enabled on android

**Comment by mtalebian** [comment]
Hi, 
congratulate for your great product.
It seems AG-2198 is rolled back in version 20. It is about browser detection in utils.ts
