### ISSUE TITLE
CellEditor -Popup Editor: adapt editor width to the width of the column

### ISSUE THREAD

**Issue by misterpinedita** [ag-grid/ag-grid#2691]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```
Is it possible to build a component Popup (isPopup() = true) and resize its width , so that its width is the same than the width of the column? When I am defining the component as Popup the width of the component is too small. Any idea?

![2018-10-09_12h17_22](https://user-images.githubusercontent.com/43685880/46663050-5f202600-cbbd-11e8-97f6-735296156f54.png)

**Comment by teuf22** [comment]
I had a similar need and solved in this way:

add in custom editor template:
```
 [style.width]="cellWidth"
````

then:
```
cellWidth:string;

agInit(params) {
    this.cellWidth = params.column.actualWidth + 'px';
```

I am new to ag-grid, not sure if this is the best way.

**Comment by misterpinedita** [comment]
Thank you, it works. I am new to ag-grid and angular. For me it is a work around. I don't understand why popup cell editors cannot be configured as they have the same width than the column width.

**Comment by nmz787-intel** [comment]
Here's how I adjusted the `width` of my custom editor, as well as the `left` based on it's parent cell (I'm using jQuery to help out, but it shouldn't be impossible to adapt to pure JS or some other helper library):

```
class MyCustomEditor {
  init(params){
    this.eGui = document.createElement('div');
    this.parents_left_padding = parseInt($(".ag-cell").css("padding-left"));  // later I realized I needed to adjust the left property in afterGuiAttached, so I could probably move all the width adjustment there too, to get the actual parent's left instead of using the CSS class value
    let colWidth = params.column.actualWidth - (1.5*this.parents_left_padding);
    this.eGui.style.width = colWidth + "px";
    // do other custom HTML/JS
  }
  getGui() {
    return this.eGui;
  }
  afterGuiAttached() {
    //this.eGui.focus();
    let parent_left = parseInt($(this.eGui).parent().css('left'));
    let newLeft = (parent_left + (this.parents_left_padding/2)) + "px";
    $(this.eGui).parent().css('left', newLeft);
  }
}
```
