### ISSUE TITLE
[scrolling] Scrolling doesn't behave natively, and sometimes scrolls the browser window

### ISSUE THREAD

**Issue by dceddia** [ag-grid/ag-grid#27]
Playing around with the demos on angulargrid.com, I noticed that the mouse wheel scroll behavior is odd. I'm on a Mac using Chrome 41.0.2272.104 and a Magic Mouse. The built-in browser (OS?) scrolling behavior includes acceleration and deceleration, but those don't happen inside the grid.

The other problem (possibly related) is that scrolling with the mouse wheel inside the grid works for a short time, and then the entire browser window scrolls, and I have to scroll back up to see the grid.

Edit: It looks like this is called "inertial scrolling" or "momentum scrolling". Some links that might help:
http://stackoverflow.com/questions/4339196/how-to-detect-disable-inertial-scrolling-in-mac-safari
http://www.hnldesign.nl/work/code/momentum-scrolling-using-jquery/ (jquery, but maybe still informative)

**Comment by pauljoey** [comment]
Simple fix:

```css
.ag-body-viewport {
  -webkit-overflow-scrolling: touch;
}
```

This should probably be added to the code base. It will provide native inertial scrolling on "most" browsers without unwanted side-effects. JS-emulation inertial scrolling is almost impossible to get right and is prone to side-effects and I would thus recommend against it.

**Comment by ceolter** [comment]
Excellent. Thanks for the heads up.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-39

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
