### ISSUE TITLE
Still an issue: setFilterModel() in async/callback set filter

### ISSUE THREAD

**Issue by bbohling** [ag-grid/ag-grid#2709]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I believe this issue is the same issue as reported here: https://github.com/ag-grid/ag-grid/issues/2212. 

**Current behavior**

`setFilterModel()` is unable to filter on a column when async/callback model is used for values, shown [here](https://www.ag-grid.com/javascript-grid-filter-set/#example-callback-async).

**Expected behavior**

When passing a filter model to `setFilterModel()` on `gridReady` event that the filter is applied, which it does _unless the grid is populated via async_.

**Minimal reproduction of the problem with instructions**

1. Go to https://stackblitz.com/edit/angular-438dcc
1. Note `sorting` is price, but there is no filter set, though being explicitly set on Line 40 in app.components.ts
1. On app.component.html, change the rowData to `[rowData]="rowData" for a synchronous example that works.

So sync works, but async does not.

**Please tell us about your environment:**

Should not matter since I provide a link above that demonstrates this issue using Stackblitz, but to be thorough:

* macOS v10.14
* angular/-cli v6.1.2
* ag-grid-angular v19.0.0
* ag-grid-community v19.0.0

* **Browser:**

* Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Safari Version 12.0 (14606.1.36.1.9)
* Firefox 62.0.3 (64-bit)

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
I can see that this is now in a few places... In any case, let us have a look and come back tomorrow with an update.

We are likely though to just leave one issue opened, if we were to do so, we will update all the other threads though

Thanks for the feedback!

**Comment by makinggoodsoftware** [comment]
Hi,

You are setting the data twice, but only setting the filter once...

You need to listen to a better event, have a look at this plunker


https://stackblitz.com/edit/angular-k3peg5?file=src%2Fapp%2Fapp.component.html


Hope this helps

**Comment by bbohling** [comment]
@makinggoodsoftware that using `firstDataRendered` instead of `gridReady` indeed fixed my issue. bad on me for not reading through the events more closely.

**Comment by svanetten1976** [comment]
@makinggoodsoftware I'm pretty sure that there is still an issue here, at least in ag-grid v. 20.2.0 with React 16.6.3. We have some dynamic grids that get populated based on incoming props that are constantly changing both data and column headers (and often are configured as master-detail grids). When the rowData changes, I am doing like so:

`  componentDidUpdate(prevProps, prevState) {
    if (!plainDeepEqual(prevProps.grid, this.props.grid) && this.gridApi) {
      setTimeout(() => {
        this.gridApi.setFilterModel(null)
        this.gridApi.onFilterChanged()
      }, 0)
    }
}
`
When this condition is met, in the console, I get a warning from the frameworkComponentWrapper.js (/ag-grid-community/dist/lib/components/framework/frameworkComponentWrapper.js) that reads:
"Framework component is missing the method setModel()"

And obviously, calling the setFilterModel() method has had no effect. All I am trying to do is remove the filters that were set on columns when the grid gets reloaded. Certainly seems like a bug to me, especially being that I'm calling the required method and getting a warning from ag-grid about a missing method. Any ideas? -- Steve

**Comment by dsgriffin** [comment]
@svanetten1976 did you manage to resolve this? having a similar issue when trying to populate the sort order via redux once a table has loaded but noticing a ton of issues when trying to use `setSortModel` inside either `onFirstDataRendered` or `onGridReady`

**Comment by svanetten1976** [comment]
@dsgriffin no we ended up just suspending that particular issue in our application because we deemed it to be a bug in ag-grid. In our case, luckily it was a pretty minor edge-case thing, but yeah it seems to still be an unresolved issue to me. Sorry I can't be of any help there

**Comment by wgallop99** [comment]
> Hi,
> 
> You are setting the data twice, but only setting the filter once...
> 
> You need to listen to a better event, have a look at this plunker
> 
> https://stackblitz.com/edit/angular-k3peg5?file=src%2Fapp%2Fapp.component.html
> 
> Hope this helps

This fixed my issue, even though the comment within in the code says it doesn't work, this bug seems to have been fixed.

The event that you need to use is the firstDataRendered event.
