### ISSUE TITLE
[Vuejs] Setting popupParent option doesn't correctly position columnMenus/contextMenus/popup editors on small grids

### ISSUE THREAD

**Issue by mwojtul** [ag-grid/ag-grid#2711]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When setting the popupParent option and using the AgGridVue component, popup menus/editors are correctly rendered inside the specified element, but their position is not correctly calculated on small grids (they float above the grid).

**Expected behavior**
Popup menus/editors will have their position correctly calculated as seen in the docs: https://www.ag-grid.com/javascript-grid-context-menu/#popup-parent.

**Minimal reproduction of the problem with instructions**
Create a new grid using the AgGridVue component with the minimum required configuration and give the grid a height of 100px. Then set the popupParent to `<body>`. Click the columnMenu and notice that it will float in space above the grid despite having set popupParent. The same applies to popup editors, and contextMenus seem to be slightly mispositioned as well.

Here's a demo: https://codesandbox.io/s/k0601zl8zv

**Please tell us about your environment:**

* **ag-Grid version:** ag-Grid Enterprise 19.0.0, ag-Grid Vue 19.0.0

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

* **Language:** ES6/7

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2203 -  Vue - popupParent option doesn't correctly position columnMenus/contextMenus/popup editors on small grids

**Comment by mwojtul** [comment]
@makinggoodsoftware thanks for the update. Following up that I've found the scope of the bug to be a bit larger than just small grids. Any grid set to `domLayout="autoHeight"` will have mispositioned popup elements, whether there's 5 rows or 100 rows.

**Comment by makinggoodsoftware** [comment]
Hi,



We have just released v19.1.3 (for ag-grid-community and ag-grid-enterprise), the framework libraries have not been updated (It wasn't necessary)



Could you please check if with this new version your popup issue is gone?



You might need to change your dependencies to something like this:



"ag-grid-YOURFW": "^19.1.x",

"ag-grid-community": "^19.1.x",

"ag-grid-enterprise": "^19.1.x",



Also, note that if you had any workaround applied to fix this. you should remove it to test it.



Looking forward to hearing from you.

**Comment by makinggoodsoftware** [comment]
I believe this is solved now

**Comment by mwojtul** [comment]
Works great, thanks 👍
