### ISSUE TITLE
setFilterModel doesnt perform filtering if filter is {type: 'equals' and filter: ''}

### ISSUE THREAD

**Issue by SERGEES** [ag-grid/ag-grid#2712]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I am truing to use:
`gridOptions.api.setFilterModel(filterModel);`
with 
`var filterModel = {
        country: {
          type: 'equals',
          filter: ''
        }
};`

So i expect grid will return all rows with empty ''country'', but it looks like grid ignores passed filter with `filter: ''`
I also tried  [null] as a values:
`filterModel = {
        country: {
          type: 'equals',
          filter: [null]
        }
    };`

in this case i see filter indicator near colunm header but rows is the same

maybe i missed something in documentation...

here is example
https://plnkr.co/edit/aA7D4At58yg7AqwD1qxc?p=preview

**Current behavior**

grid doesnt perform filtering on empty values 

**Expected behavior**

grid shows rows with empty values for specified column

**Please tell us about your environment:**Windows 10
* **ag-Grid version:** 19.0.0

* **Browser:** Chrome 69.0.3497.100

* **Language:** [ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

This is indeed something that at the moment is not possible with ag-grid, but it is on our backlogs

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-1475 | Allow searching for blanks not blanks while filtering
-- | --
