### ISSUE TITLE
When store data is passed to the setRowData(), cell values modification from the ag-grid throws error.

### ISSUE THREAD

**Issue by bndivya** [ag-grid/ag-grid#2713]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Below is the plunker link to reproduce the issue.
https://plnkr.co/edit/CtyD97ipowBbKjdRuwVk?p=preview

**Current behavior**
Cell editing from the ag-grid, when store value is passed to the setRowData api, throws error as below.
![image](https://user-images.githubusercontent.com/13798642/47152842-7668bd00-d2fb-11e8-93f5-c7c8cdd1e3ae.png)

**Expected behavior**
According to docs, if we are using store pattern in our application, we can update our row data using deltaRowDataMode=true flag, and by defining the function getRowNodeId() callback. If these 2 are set correctly, we can pass the immutable store to the setRowData api and ag-grid will handle the rows data update.
But this will not handle the values edited directly from the UI, (columns which have the columnDef property editable set to true), as storefreeze will avoid direct mutation of the state.
Store freeze is a feature from npm package ngrx-store-freeze, which throws an error to the user if store is directly mutated.
Ag-grid should be able to update the cell value, when store is passed to the setRowData api.
But it is not possible unless we clone the data before setting the row data.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
"ag-grid": "~17.1.1",
"ag-grid-angular": "~17.1.0"

* **Browser:**
Chrome/69.0.3497.100

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "~2.6.2", ES5

**Comment by bndivya** [comment]
For some reason plunker is removing my css files!

Please add 2 empty files: app/app.component.css and app/grid.component.css
to my plunker to make it work.

**Comment by makinggoodsoftware** [comment]
Hi,

I understand that you are having issues setting up your plunker, unfortunately all we can do without it is to flag the ticket as managed by the community.

I am going to let the ag-grid-engaged for a few days, if you, or someone else provide with a simplified plunker of this issue, then we will have a look

Thanks

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by bndivya** [comment]
Please could you check this below link? 
https://plnkr.co/edit/S1o8lys6II82EUIIoeE3?p=preview

When sample app loads, click on "Add Sample data" and try to edit any cell value. Then we get the above mentioned console error.

**Comment by makinggoodsoftware** [comment]
Hi guys

Let me share with you this example:

Have a look at this plunker, this should give you a possible implementation on how to use redux + editing (custom popup)

https://next.plnkr.co/edit/jqNNuvAIyv6EvrSi

As you can see here you have a possible approach

Would this help?

**Comment by makinggoodsoftware** [comment]
Since this has been inactive for a while, going to close this thread, feel free to create a new ticket if you want to follow up.
