### ISSUE TITLE
IToolPanel not enforce using agInit(): void 

### ISSUE THREAD

**Issue by ofirrifo** [ag-grid/ag-grid#2716]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```
I'm using ag-grid-community version 19.0.0 with TypeScript
and I wanted to add custom Tool Panel Component just like your [example](https://www.ag-grid.com/javascript-grid-tool-panel-component/#example-custom-stats-tool-panel-component)
I use `export class CustomStatsToolPanel implements IToolPanel` but I get exception that agInit is not a function.
I found out that IToolPanel does not enforce using agInit(): void 

as you can see in [ag-grid github ](https://github.com/ag-grid/ag-grid/blob/master/dist/lib/interfaces/iToolPanel.d.ts)

Anyway, I want to say thanks for your best grid ever :)

**Comment by makinggoodsoftware** [comment]
Hi,

Happy to hear that you are enjoying using ag-grid.

:)

Note that you should get the typings ensured, if you implement IToolPanelAngularComp

https://github.com/ag-grid/ag-grid/blob/f065d96ee682d4c43a7275f35935d122d9faeee6/packages/ag-grid-angular/dist/interfaces.d.ts


Hope this helps
