### ISSUE TITLE
Documentation: Row node

### ISSUE THREAD

**Issue by teuf22** [ag-grid/ag-grid#2718]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I need to retrieve a row index from a node, and I'm using the rowIndex field. This is however undocumented. Is the documentation up-to-date ?
https://www.ag-grid.com/javascript-grid-row-node/

note it contains duplicate definitions for firstChild, lastChild, childIndex

**Comment by makinggoodsoftware** [comment]
Hi,
Thank you for your email. We are aware of this issue and have a feature request in our backlog:
You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/
If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-2207
Documentation - Revamp document node docs - Missing attributes (ie rowIndex)
