### ISSUE TITLE
Flow type defs

### ISSUE THREAD

**Issue by sgb-io** [ag-grid/ag-grid#2719]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

I was unable to find any Flow definitions for the library.

**Comment by makinggoodsoftware** [comment]
Hi, I am afraid that we don't have any official typings for Flow, going to leave this ticket as flagged as managed by the community to see if anyone can help though
