### ISSUE TITLE
Ag-grid issue when searching in tools panel

### ISSUE THREAD

**Issue by aciurea** [ag-grid/ag-grid#2723]
Hello, 

I have the enterprise version of ag-grid and I find it harder to go to private ticketing so I am creating an "issue" here.
I have this scenario when I search in the right Tool Panel:
Continents: 
          -> Europe: Countries -> England, France, etc.
           -> Asia: Countries -> China, Japan, etc.

If I search for Countries I want the tree underneath to be visible (checkbox for England, France and so on).

Is this possible? Is there any configuration that I might missed?

Thank you!

**Comment by makinggoodsoftware** [comment]
Since this has been inactive for a while, going to close this thread, feel free to create a new ticket if you want to follow up.
