### ISSUE TITLE
Errors thrown inside custom cell renderers do not unmount ag-grid table component in React

### ISSUE THREAD

**Issue by michaelohm** [ag-grid/ag-grid#2727]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Using ag-grid-react and ag-grid-enterprise, when a Javascript error is thrown inside custom cell renderer, the table component does not unmount as expected of React components as of React 16. Furthermore, the ag-grid table is not passing any error information to React's componentDidCatch().

**Expected behavior**
A Javascript error in React should unmount the component instead of showing a broken component. Parent component of the ag-grid table should also be passed errors to React's lifecycle method componentDidCatch which is not happening.

Described here: https://reactjs.org/docs/error-boundaries.html

**Please tell us about your environment:**
Operating system: MacOS High Sierra 10.13.6, NPM

* **React version:** 
16.6.0

* **ag-Grid version:** 
ag-grid-react 19.0.0
ag-grid-community 19.0.0
ag-grid-enterprise 19.0.0

* **Browser:**
All browsers

* **Language:**
ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
