### ISSUE TITLE
Copy Down in a non-contiguous range

### ISSUE THREAD

**Issue by ross-aitken** [ag-grid/ag-grid#2729]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```
Hi
We're investigating ag-grid to see if it meets our needs for an in-house project. If it does, we will certainly become enterprise customers. Please also note that I'm a UX designer, not a developer so please forgive me if I don't understand the technicalities as well as I could!

I want to be able to hold Ctrl and use the mouse to select a non-contiguous range in a column (e.g. the cells in rows 1, 2, 5 & 10 of the same column), and then set those cells to all the same value. I imagined I could use Ctrl+D to copy down from the first selected cell to the others. When I use the Demo on the ag-grid site, that doesn't seem to work and I think that's because when I do that, it's actually creating lots of independent ranges with one cell in each.

Is there a way to support what I want to do? Either by setting a mode where all the cells are added to the same range, or some other way to set the cells in the separate ranges to the same value?

Thanks
Ross

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
