### ISSUE TITLE
processDataFromClipboard not fired on angular 6

### ISSUE THREAD

**Issue by enhuizhu** [ag-grid/ag-grid#2730]
reproduce steps:
1. set up basic configuration of ag-grid

<ag-grid-angular 
  style="width: 100%; height: 500px;" 
  class="ag-theme-balham"
  [rowData]="rowData"
  [enableSorting]="true"
  [enableFilter]="true"
  [enableColResize]="true"
  [suppressMakeColumnVisibleAfterUnGroup]="false"
  [suppressClipboardPaste]="false"
  [rowGroupPanelShow]="'always'"
  rowSelection="multiple"
  (cellClicked)="onCellClicked($event)"
  (cellValueChanged)="onCellValueChanged($event)"
  (cellEditingStarted)="onCellEditingStarted($event)"
  [enableRangeSelection]="true"
  [groupSelectsChildren]="true"
  (pasteStart)="pasteStart($event)"
  (processDataFromClipboard)="processDataFromClipboard($event)"
  (processCellForClipboard)="processCellForClipboard($event)"
  (processHeaderForClipboard)="processHeaderForClipboard($event)"
  (sendToClipboard)="sendToClipboard($event)"
  editType="fullRow"
  #agGrid
>
<ag-grid-column>
</ag-grid-column>
.....
</ag-grid-angular>

2. copy data from excel.
3. you can see data can be pasted to grid, but processDataFromClipboard never fired.

expect behaviour:
processDataFromClipboard should be fired.

**Comment by seanlandsman** [comment]
The callback is processCellFromClipboard

**Comment by gregdbqn** [comment]
No, there is also processDataFromClipboard. I have the same problem, this callback doesn't launch, same for pasteStart and pasteEnd. cellValueChanged does work however. Using Angular 4.4.x
https://www.ag-grid.com/javascript-grid-clipboard/#processing-whole-paste-operation

**Comment by getsurenka** [comment]
2022 and still not fixed
