### ISSUE TITLE
Autoheight calculation does not take rowClass into account

### ISSUE THREAD

**Issue by BenniG82** [ag-grid/ag-grid#2731]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Plnkr: https://plnkr.co/edit/o82QpGnGL6iOmWUUOHP0?p=preview

**Current behavior**
Css-Definitions defined in the (custom) rowClass in gridOptions are not taken into account for calculating the cell height. In this plnkr the font-size is set to a ridiculous large value to demonstrate this issue

**Expected behavior**
The rowClass should also be applied when calculating the row height for autoHeight.

**Please tell us about your environment:**
See plnkr.

**ag-Grid version:** 
19.0.0

**Browser:**
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"

**Language:**
Typescript, probably all

**Comment by makinggoodsoftware** [comment]
Hi,

Can you clarify what is in that plunker that is not working as expected?

Thanks

**Comment by BenniG82** [comment]
The height of the rows is not calculated correctly. This plunkr is based on the ag-grid example for auto row height: https://www.ag-grid.com/javascript-grid-row-height/#auto-row-height

The height of the rows in the provided plunkr does not take the large font-size (overridden through rowClass="not-applied-for-height-calculation" in app.component.ts) into account but still calculates the row height based on the standard font-size. If you remove the class "not-applied-for-height-calculation" everything works as expected.
If you enlarge the column-width you can see that more and more text appears.
In app.component.ts you can see that autoHeight is true for all columns.
You can also set the font-size of the css class "not-applied-for-height-calculation" to 9px (smaller than usual). Now the row height is too high.

I hope this makes things clearer.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2314
Take rowClass into consideration when using autoheight
