### ISSUE TITLE
Previous context menu still remains using an iPad 

### ISSUE THREAD

**Issue by holzapfelnet** [ag-grid/ag-grid#2732]
I'm submitting a bug report. I created an Angular 6 application using the current version of AG Grid. 

When I open a context menu (tap and hold) on an iPad, the context menu will still remain in case I open another context menu (see screenshot). 

![image](https://user-images.githubusercontent.com/11599235/47616909-e547d200-dac2-11e8-9cdb-121dbc24de83.png)

An example can be found here:

https://plnkr.co/edit/uq8QN666gn9el8ZGu84v?p=preview

Current behavior
The previous context menu still remains using an iPad.

Expected behavior
The previous context menu will disappear using an iPad.

ag-Grid version: 19.0.0
Browser: Safari mobile on iPad (iOS 11.2.5)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2281 On iPad context menu remains open and never dissappears
