### ISSUE TITLE
BUG: horizontal scrollbar and "setPinnedBottomRowData" 

### ISSUE THREAD

**Issue by MobileAppVault** [ag-grid/ag-grid#2734]
Hi,

have the following issue on ag-grid react and setPinnedBottomRowData method.

Plunker Sample ( Simple ): https://embed.plnkr.co/e4OdMw4FIs22mqDp6SaK/

**Current behavior**
Add 'this.gridApi.setPinnedBottomRowData' on grids with an horizontal scrollbar will add the pinned row under the horizontal scroll bar.

![image](https://user-images.githubusercontent.com/1671192/47712899-3974c280-dc39-11e8-958a-5baa175c1d80.png)

**Expected behavior**
Add the scrollbar under the pinned row

Many thanks for any help.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2072 | Pinned row - Position pinnedBottomRowData above the scrollbar (windows)
-- | --
