### ISSUE TITLE
Bug in configuring The Aggregation Panel

### ISSUE THREAD

**Issue by ajkaushik** [ag-grid/ag-grid#2735]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```
**Current behavior**
Configuring AggregationPanel in status bar does not work if any other status panel is enabled. This is visible in plunker used in documentation as well in section configuring aggregation panel. I have created another plunker showing the issue:

https://plnkr.co/edit/mgq5WFZH37UNZ31Y1Gbc?p=preview

As per below config, only sum func should be enabled; but its not the case and all funcs are enabled.

`statusBar: {
        statusPanels: [
          { statusPanel: 'agTotalRowCountComponent', align: 'left', key: 'totalRowComponent' },
          {
            statusPanel: "agAggregationComponent",
            statusPanelParams: {
              aggFuncs: ["sum"]
            }
          }
        ]
      },
`

**Expected behavior**
AggergationPanel should only show the configured aggFuncs even if any other status panel is enabled.

**Please tell us about your environment:**
WINDOWS 10
Chrome latest build

* **ag-Grid version:** 19.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2264 | Configuring AggregationPanel in status bar does not work if any other status panel is enabled
-- | --
