### ISSUE TITLE
Request: Add CombinedFilter to community main.d.ts

### ISSUE THREAD

**Issue by baruchvlz** [ag-grid/ag-grid#2736]
When creating a custom number filter, we must do 

```typescript
onParentModelChanged(parentModel: CombinedFilter<SerializedSetFilter>) => void;
``` 

In order to have a proper type definition. This requires the import to be 

```typescript
import { CombinedFilter } from 'ag-grid-community/dist/lib/filter/baseFilter';
```

My request is to add `CombinedFilter` to the community `main.d.ts` in order to have a better import. In the case of what we're trying to do it would look like so

```typescript
import {
  SerializedSetFilter,
  IFloatingFilterParams,
  IFloatingFilter,
  CombinedFilter,
} from 'ag-grid-community';
```

**Comment by makinggoodsoftware** [comment]
Hi,

ag-grid staff does not provide support through github. If you are a customer please contact us through our official support channel. 

However I am pasting here for you the contents of an article that we have in our knowledge base (that at the moment is only accessible for customers), hope this helps


If you want to use our own internal classes in typescript, you might find that some of them are not exported such that you can use them directly:

 

ie (THIS WON'T WORK):

import {CellClassParams} from "ag-grid-community";

 

as opposed to (THIS WORKS AS OF V19.0)

import {CellClassParams} from "ag-grid-community/dist/lib/entities/colDef"; 

 

The reason to export only a subset of them is that we ourself use some of them in the ag-grid-enterprise project, and these are the ones that are included in the exports.

 

Note that if you find yourself importing these classes, you are going to be responsible for changing the paths if we were to move/rename a file

 

We are aware that it would be better to export all the classes so users would ever need to import from "ag-grid-community", that is why we have an item in our pipeline to change our build so we automatically export everything

https://www.ag-grid.com/ag-grid-pipeline/  

Project structure improvements	AG-1267	Automatically export all classes and interfaces to main.ts / main.js
 

Note that at this time, we don't have an ETA for this, and is up to the users to do the import by providing the path to the class. If you do struggle to find the path for a class, you are more than welcomed to raise this through support and we will help you find the correct path.

 

To see all the classes that can be imported by just referencing "ag-grid-community" check this file

 

https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/main.ts
Thanks
