### ISSUE TITLE
Any way to not specify AgGrid container size?

### ISSUE THREAD

**Issue by mellis481** [ag-grid/ag-grid#2744]
In all the documentation I've read, AgGrid will assume the height of its container, requiring you to specify a static height.  eg:

    <div style={{ height: '400px', width: '100%' }}">
        <AgGridReact {...this.props} />
    </div>

This is undesirable for every use case in my application.  Is is possible to have AgGrid take up whatever height it needs to based on the rows, etc. displayed?

**Comment by zapacila89** [comment]
[Grid autoHeight](https://www.ag-grid.com/javascript-grid-width-and-height/#auto-height)

You're basically looking for domLayout='autoHeight', see above link

**Comment by mellis481** [comment]
@zapacila89 Thanks!
