### ISSUE TITLE
Enterprise: side-bar and status-bar have 1px border even when not being used

### ISSUE THREAD

**Issue by MatthewHerbst** [ag-grid/ag-grid#2746]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

(We are currently on a trial Enterprise license, with likely plans on purchasing a license for production use.)

**Providing a Reproducible Scenario**
Any AgGridReact with enterprise installed that does NOT use the side-bar or the status-bar. By not use I mean that the `sideBar` and `statusBar` grid properties are not set on the grid.

**Current behavior**
A `div` with the class `.ag-side-bar` is rendered with a 1px border.
A `div` with the class `.ag-status-bar` is rendered with a 1px border.

**Expected behavior**
I would expect both `div`s mentioned above to also have the `.ag-hidden` class similar to how the paging panel `div` (class `.ag-paging-panel`) has when it's not being used.

Ideally actually, you wouldn't even render the `div`s at all, since why put empty DOM nodes on the page?

**Please tell us about your environment:**

* **ag-Grid version:** 19.1.1

* **Browser:** `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`

* **Language:** ES5 through ES2018 transpiled to ES5 via Babel and built with Webpack

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2313

Remove DOM elements from the side bar is the side bar is hidden
