### ISSUE TITLE
ag-grid does not work with flex layout

### ISSUE THREAD

**Issue by IIFE** [ag-grid/ag-grid#2748]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Following stackblitz shows the issue I'm facing:
https://stackblitz.com/edit/angular-zwpdhl

**Current behavior**
ag-grid does not take available height when putting ag-grid-angular under a flex layout. The ag-grid seems to collapse to a horizontal bar, with no height at all.

**Expected behavior**
I would expect the ag-grid to take the remaining height in the flex layout. The only workaround is to explicitly set a fixed height to the ag-grid, however that defeats the point of using flex layout, so setting a fixed height is not suitable for my scenario.

The ag-grid needs to also behave correctly when other elements are in the flex column/row. So setting position to absolute would not work as it makes the ag-grid overlap the other elements in the flexbox.

Are there any solutions/workarounds for this, which still work with flex layout?

Kind regards.

**Comment by zapacila89** [comment]
I've tried your example and it works using:

```html
<mat-sidenav-content>
      <div fxLayout="column" fxFlexFill fxLayoutGap="5px">
         <div>Toolbar</div>
         <div fxFlex="100">
            <ag-grid-angular class="ag-theme-balham" style="height: 100%; width: 100%;" [rowData]="rowData" [columnDefs]="columnDefs">
            </ag-grid-angular>
          </div>
       </div>
</mat-sidenav-content>
```

I forked you example [here](https://stackblitz.com/edit/angular-maq8vx?file=src/app/app.component.html)

Also checkout docs related to a responsive ag-Grid with Flexbox/Css Grid [here](https://www.ag-grid.com/javascript-grid-responsiveness/)

**Comment by IIFE** [comment]
> <

Thanks for your reply. After playing around more with the example it does appear to be an error on my part with the way I layed out the HTML. I needed to set the parents of the grid to have a height of 100%.

The new code on the stackblitz example shows the new version of app.component.html.
https://stackblitz.com/edit/angular-zwpdhl

Much appreciated.
