### ISSUE TITLE
Why is the support for Angular so minimal?

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ag-grid/ag-grid#2749]
- Many types are not even exported to be used for Typescript externally (i.e. ValueFormatterParams)
- There's no support to directly use pipes as value formatters
- There's no support to use inline templates as cell renderers

Using ag-grid in Angular requires so much verbosity of specifying cell renderer component for almost any use case that isn't just directly outputting a string. I understand that there are always more important things to fix and do, but I find it rather disappointing, that ag-grid is so powerful tool to use and so clunky to use at the same time.

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
Hi Sebastian,

Those all are good improvements to be made to ag-grid for Angular, I can't really give you a better answer than we are trying our hard to be honest.

Bear in mind that we support all the major frameworks natively and that all the features that we have work for all of them

https://www.ag-grid.com/javascript-grid-getting-started/

That being said, this doesn't mean that we are not saying that we will never get them done is just that we always find other things to prioritize

https://www.ag-grid.com/ag-grid-pipeline/

Actually, if we go to the details of the items you mentioned:

1.- Many types are not even exported to be used for Typescript externally (i.e. ValueFormatterParams)

This is already in our pipeline:

Project structure improvements | AG-1267 | Automatically export all classes and interfaces to main.ts / main.js
-- | -- | --

2.- There's no support to directly use pipes as value formatters
3.- There's no support to use inline templates as cell renderers

Agreed, we will look into incorporating this in our pipeline.

We will update this thread if we have any more updates

**Comment by sebastian-zarzycki-es** [comment]
Thanks. I've noticed that recent release (19.1.1) indeed added missing types (ValueFormatterParams), so that's a start.

The gist of my problem is that a lot of ag-grid usecases is to display data in a certain way in a row, that:
- is not just regular string
- is often simple enough, that it's hard to justify the overhead of creating and using whole new renderer component for it
- is not just a regular function returning string, as this way you lose all the power of angular templating

I've asked about it here - https://stackoverflow.com/questions/48954875/using-ng-template-as-cellrenderer-in-ag-grid-angular-5/ - but noone knew of any solution.

I'd say this is about 80% of cases in my projects. The end result, currently, is dozens of custom cellrenderers in a project. A lot of this cases could be handled by providing just angular template (or reference to such, defined in the same html as where the ag-grid resides, using the power of ng-template) or a pipe evaluation.

The best grid for AngularJS (http://ui-grid.info/) had this (http://ui-grid.info/docs/#!/api/ui.grid.class:GridOptions.columnDef#properties_cellclass) - you could specify either the class of the renderer to instatiate (cellClass), the filter (old name for pipe) evaluation to use (cellFilter) or the template reference (cellTemplate).

**Comment by makinggoodsoftware** [comment]
Hi Sebastian, 

I think for these cases we would suggest that you use an es6 closure, you can pass a function in the renderer and inline some logic there...

Would this work for you?

**Comment by sebastian-zarzycki-es** [comment]
That's what I'm currently doing in order to kind of fit the usage of Angular's pipes, but it's far from ideal. And it still does not solve the main issue of not being able to provide an actual angular template (with, say, `row` and `value` properties bound), without the overhead of creating a whole new component. 

Without the support for pipes and inline templating, ag-grid in Angular feels a bit like a forced addition. It's agnostic, but because of that it's also alien enough. The usage pattern is very clunky, because it doesn't take advantage of many things that are common in Angular environment - and while there are workarounds, they bring a significant overhead with them, that (I feel) could be avoided.

**Comment by makinggoodsoftware** [comment]
Hi Sebastian

We have decided to raise this in our backlog

AG-2307 | Angular 2+: Add support for pipes
-- | --

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by sebastian-zarzycki-es** [comment]
Thank you, that's very promising! Any chance for inline templating / template references in the future?

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that we have also included this in our pipeline:


AG-2415 | Frameworks - Allow integrating native template strings
-- | --


You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi Sebastien,

I am going to close this ticket now, I believe that we should cover a lot of ground with these two tickets.

Feel free to create a new ticket if you want to follow up

Thanks for all the feedback!

**Comment by sebastian-zarzycki-es** [comment]
Thank you! I appreciate it a lot. I feel this will significantly improve ag-grid for Angular!
