### ISSUE TITLE
There's no straight forward way to reload the datasource with current filters, pagination and sort applied

### ISSUE THREAD

**Issue by tauqeer-qbatch** [ag-grid/ag-grid#2750]
**Current behavior**

Let suppose you have an action button in rows, you click on the row and it opens external side bar ( not related to ag-grid ) and you update something there and click on save button, sidebar is closed and then you want to see updated data in grid. There's no way to simply recall getRows() of grid datasource.

**Expected behavior**

 Grid should reload the data with same filters, sorts and pagination applied to it so that same rows are displayed to the user but with updated data. So, there should be a method to recall datasource.getRows(params) [+ a method to get current filters, sorts and pagination applied to the grid (params -> passed to getRows()) ]

**Comment by wordythebyrd** [comment]
Have you tried [View Refresh](https://www.ag-grid.com/javascript-grid-refresh/)?

**Comment by tauqeer-qbatch** [comment]
> Have you tried [View Refresh](https://www.ag-grid.com/javascript-grid-refresh/)?

Yes I tried View Refresh, but it didn't work. I am using serverSideModel (with DataSource) and datasource is responsible for getting rows. When I call api.refreshCells() or even pass it `force: true;` it still doesn't work.

**Comment by tauqeer-qbatch** [comment]
When we call `api.refreshCells()` or `api.redrawRows()`, do they force datasource to fetch new rows with update data? This is actually what I want it to do but it doesn't seem to work for me.

**Comment by wordythebyrd** [comment]
You could also try [refreshInfiniteCache()](https://www.ag-grid.com/javascript-grid-infinite-scrolling/).

**Comment by tauqeer-qbatch** [comment]
> You could also try [refreshInfiniteCache()](https://www.ag-grid.com/javascript-grid-infinite-scrolling/).

I just tried it but it didn't work because I am using model `serverSide` whereas `refreshInfiniteCache()` only works for model `infinite`. When I tried it warned with message

> ag-Grid: api.refreshInfiniteCache is only available when rowModelType='infinite'.

**Comment by tauqeer-qbatch** [comment]
@zapacila89 yes exactly. I am also doing this by purging ServerSideCache. But it's not maybe a good way to do that. 
And to keep all the filters, sorts and pagination options, I am saving `params` passed to `getRows()` of datasource to my component state. So when I purge cache, I recall getRows() manually and pass down previously saved `params` and its working as expected. But it's not the good solution so far.

**Comment by zapacila89** [comment]
@tauqeer-qbatch I feel your pain, anything related to pagination in ag-Grid is a complete mess.
Try setting the current page.. it's impossible without first loading the first page.
There is also a infinite loop issue I've opened [here](https://github.com/ag-grid/ag-grid/issues/2745). Embarrassing..

Anyway, I would have expected that purgeCache would call GetRows with current filters and sorts.

**Comment by tauqeer-qbatch** [comment]
@zapacila89 It takes so long to find a work around for even simple tasks. Now I am reading doc to find something that could help me find changed/updated rows so that I could update data in database but it's almost 1 hour of reading and nothing found.

**Comment by zapacila89** [comment]
@tauqeer-qbatch Your best bet is to handle [cellEditingStopped or rowEditingStopped](https://www.ag-grid.com/javascript-grid-cell-editing/#editing-api) and save them somewhere for when you're ready to send them to the server.

**Comment by tauqeer-qbatch** [comment]
@zapacila89 Thanks for the hint. I am already on it :)

**Comment by makinggoodsoftware** [comment]
Hi guys,

Let me share with you an article that we have in the knowledge base for enterprise customers

Updating SSRM nodes locally
The following example demonstrates CRUD operations by looping over loaded row nodes, using api.forEachNode(), and updating the data using: rowNode.setData(data)

'Update Selected Rows’ - here we just locate the selected row nodes and update the data on them directly.

'Delete Selected Rows’ - deletion is achieved by iteratively swapping the data into the previously found row to delete. Note that this will leave blank rows when the number of rows is less than the block size.

'Add Row After Selected’ - this follows a similar approach to deletion were we are swapping data between into existing row nodes to achieve the appearance of addition. 

It’s important to note that setting row data will NOT change the row node ID - so if using getRowNodeId() and the data changes such that the ID will be different, the rowNode will not have it's ID updated!

The example also include some mock server endpoints to update / delete / add data on the server once the grid has been updated.

You can observe the results by invoking 'Purge Caches'

Note that the group viewport won't resize until the user purges the cache, so this example has limitations but show a possible way to accomplish this

http://plnkr.co/edit/3qqkQQ6dtqBxcB4MgQMj?p=preview



Note also that if you are customers, you might want to contact us through support, we will be happy to assist you with any issues that you have

Hope this helps

**Comment by reft** [comment]
What's going on here, no solution?

**Comment by caal-15** [comment]
I would also really like a solution here... it's dumb that it works for the Infinite model, but not for the server side row model.

**Comment by jshearer** [comment]
I'm trying to delete rows in place using the serverside data model. Is this just...  not supported? I can't find a good way to do it.

**Comment by zipper01** [comment]
I was directed here by Google and I am shocked the problem is not solved. It is a typical/basic scenario that we need to redraw a table, not just part of them in a SPA: user clicks a nav button and XHR-retrieves another table data from server-side which is relevant to the current showing table; then there should be a simple way to refresh the data source or re-draw the whole grid conveniently, in whatever model. ----and... and... there isn't. Again, this is a very basic and typical scenario that the ag-gride does not support. Frustrated.

**Comment by maxsize** [comment]
Hey guys, I am facing the same issue here, and I am amazed that this issue was closed without any solution, it is so embarrassing.
Anyways I have found a workaround for this situation, in your data source when ag-grid is calling the "getRows" function internally, you can just cache the params it brings with, so that let's say after you get new rows from server-side somewhere in your code, you can just call cachedParams.successCallback to refresh the grid.
`
getRows: (params: IServerSideGetRowsParams) => {
  this._cachedRowParams = params;
}
// got new rows
if (this._cachedRowParams) {
  this._cachedRowParams.successCallback(items, page.totalElements);
}
`

**Comment by sushmitg** [comment]
> Hey guys, I am facing the same issue here, and I am amazed that this issue was closed without any solution, it is so embarrassing.
> Anyways I have found a workaround for this situation, in your data source when ag-grid is calling the "getRows" function internally, you can just cache the params it brings with, so that let's say after you get new rows from server-side somewhere in your code, you can just call cachedParams.successCallback to refresh the grid.
> `getRows: (params: IServerSideGetRowsParams) => { this._cachedRowParams = params; } // got new rows if (this._cachedRowParams) { this._cachedRowParams.successCallback(items, page.totalElements); }`


Here's my code for server data source:

```
import Api from "./api";
import { DEFAULT_ERROR_CALLBACK } from "./app-util";
import Bro from "brototype";
import PubSub from "pubsub-js";
import AppConstants from "./app-constants";

const ServerDataSource = {
  instance({ size, url, defaultFilter, deepFilter }) {
    return {
      getRows(params) {
        const page =
          (Bro(params).iCanHaz("request.endRow") || 0) / (size || 1) - 1;

        const filters =
          defaultFilter || Bro(params).iCanHaz("request.filterModel") || {};

        const obj = {
          deepFilter,
          page,
          size,
          filterModel: filters,
          sortModel: (Bro(params).iCanHaz("request.sortModel") || []).map(
            aSort => {
              return {
                sort: aSort.sort.toUpperCase(),
                colId: aSort.colId
              };
            }
          )
        };
        Api.post(`${url}/search`, obj).subscribe(
          resp => {
            const { content, ...pageProps } =
              Bro(resp).iCanHaz("data.data") || {};
            PubSub.publish(AppConstants.TOPIC.PAGINATION_CHANGED, pageProps);
            params.successCallback(content, pageProps.totalElements);
          },
          err => {
            params.failCallback();
            errorNotificationToas(err);
          }
        );
      }
    };
  }
};

export default ServerDataSource;

```

just like you mentioned this is using params.successCallback() but still it resets the pagination, any idea what am i doing wrong here?

**Comment by lingaiahdanda** [comment]
Hello guys , can anyone know how to refresh the client-side row model?

**Comment by pojusoi** [comment]
In our project - we have exactly same problem. Must add here a note that it is not acceptable to close incident like this without actions.

Is there anyway we can make a call to get support to our problem?

Can we re-open the ticket, or shall we create a ticket from each project having the same problem?

**Comment by Klinton90** [comment]
My solution (please note, I have large custom logic for `getRows()`, but I post code with important things, hope that makes sense):
```
private getRows(params: IGetRowsParams): void {
    this.api.hideOverlay();
    ...
    const newParams: IGetRowsParams = cloneDeep(params);
    ...
    let request: Observable<any> = this.$gridOptions.context.resource.findAgByGenericFilters(newParams);
    ...
    request.subscribe({
      next: (response: RestResponseModel) => {
        ...
        const data: ListResponseModel = response.data;
        if (data.totalElements) {
          params.successCallback(data.content, data.totalElements);
        } else {
          params.successCallback([this.$gridOptions.context.newItemConstructor()], 1);
          this.api.showNoRowsOverlay();
        }
        this.api.redrawRows();
        this.ref.detectChanges();
      }
    });
}
```

**Comment by amar-kumar-yadav** [comment]
this.gridOptions.api.refreshServerSide({ purge: true });


this worked for me.

**Comment by reinhardt1053** [comment]
https://www.ag-grid.com/javascript-data-grid/server-side-model-updating-refresh/
