### ISSUE TITLE
Get page number with infinite scrolling

### ISSUE THREAD

**Issue by IIFE** [ag-grid/ag-grid#2757]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

Hi,

I'm using the infinite scrolling row model in Angular, by following the example from:
[Here](https://www.ag-grid.com/example-runner/angular.php?section=javascript-grid-infinite-scrolling&example=server-side&enterprise=1&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3A1%7D)

When running the above example, I can see in the developer tools that the page number gets logged out. However I cannot seem to find a way to get the page number in my code. I've tried `paginationGetCurrentPage()`, however that doesn't appear to work with the infinite scrolling row model.

Is there any way to get the page number being requested when the `getRows` functions is fired? My api expects a page number to retrieve data, rather than a start and end row number.

Thanks

**Comment by IIFE** [comment]
One way I found to solve this issue is to divide the startRow by the page size, and then add one to get the actual page number. Not sure if the grid API has this functionality. I'm happy to create a PR to add this simply functionality to the grid API.

Example code:
`const pageNumber = (params.startRow / this.pageSize) + 1;`

Thanks.

**Comment by makinggoodsoftware** [comment]
Thanks IIFE that sounds sensible :)
