### ISSUE TITLE
Typescript Errors in ag-grid-community 19.x.x

### ISSUE THREAD

**Issue by premranderia** [ag-grid/ag-grid#2758]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Ts Errors while compiling
```
src/ts/gridPanel/rowDragFeature.ts:138:13 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

138             this.movingIntervalId = setInterval(this.moveInterval.bind(this), 100);
                ~~~~~~~~~~~~~~~~~~~~~

src/ts/headerRendering/moveColumnController.ts:345:13 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

345             this.movingIntervalId = setInterval(this.moveInterval.bind(this), 100);
```
**Expected behavior**
 No ts errors

**Please tell us about your environment:**

Mac OS
* **ag-Grid version:** 

  "ag-grid-community": "^19.1.1",
    "ag-grid-enterprise": "^19.0.0",

* **Browser:**

n/a
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript: 3.0.3/Angular 6.x.x

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2296	Change the type definition of setTimeout, setInterval, clearInterval so we avoid ambiguity on the signature
