### ISSUE TITLE
floatingFilterComponent does not accept string like in example

### ISSUE THREAD

**Issue by JayceeZ** [ag-grid/ag-grid#2760]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

In files:
node_modules/ag-grid/src/ts/entities/colDef.ts
node_modules/ag-grid-community/src/ts/entities/colDef.ts

**Current behavior**
ColDef.floatingFilterComponent? typing is {new(): IFloatingFilterComp<any, any, any>}

**Expected behavior**
ColDef.floatingFilterComponent? typing should be with | string as per the ag-grid examples

**ag-Grid version:** ag-grid 17.1.1 --> ag-grid-community 19.1.1
Verified not fix since then an afterwards (ag-grid-community 19.1.1)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2324

Add string to the floatingFilterComponent typing
