### ISSUE TITLE
ag-grid-angular toolPanelVisibleChanged does not work

### ISSUE THREAD

**Issue by IIFE** [ag-grid/ag-grid#2763]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/Nh7EzRdDD11oiIRcVZbD?p=preview

**Current behavior**
Setting the `toolPanelVisibleChanged` event on ag-grid-angular does not appear to capture the event.

I've logged out the event object to the console, but nothing appears when the panel is shown/hidden.

The template has:
`(toolPanelVisibleChanged)="onToolPanelVisible($event)"`

And the template class has:
`onToolPanelVisible(event) {
    console.log(event);
  }`

However nothing is logged out to the console.

**Expected behavior**
To be able to listen to the `toolPanelVisibleChanged` event.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-2234	onToolPanelVisibleChanged not triggered

**Comment by klaffi3** [comment]
Still not working for me with (enterprise) version 21.0.1
