### ISSUE TITLE
Using valueCache and filterValueGetter leads to incorrect values in cache

### ISSUE THREAD

**Issue by dgsmith2** [ag-grid/ag-grid#2764]
**I'm submitting a ...**
```
[x] bug report
```

**Reproducible Scenario**
https://next.plnkr.co/edit/PJzZYttfzzvIDIU2?preview

**Current behavior**
When value caching is enable and a filter value getter is provided, cell data is not rendered correctly.  In my Plunker you can enter the name of the sport in the filter.  As you soon as you set `[valueCache]="false"` rendering is fine.

Best I can tell, the problem is the fact that the value cache is updated with the filter value when filtering and ends up being passed to the renderer.  Thus the renderer receives one form/value of data when not filtering and another when filtered

**Expected behavior**
Pass the same data to the renderer even when filtered.

* **ag-Grid version:** 19.1.1

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2326

Value Cache with filterValueGetter leads to incorrect values in cache
