### ISSUE TITLE
ag-grid-angular interfaces not compatible with noUnusedLocals

### ISSUE THREAD

**Issue by GeorgeKnap** [ag-grid/ag-grid#2765]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`ag-grid-angular/src/interfaces.ts` file imports `IToolPanel` interface which is unused in the file. This is not compatible with `tsconfig`'s rule `noUnusedLocals` and throws typescript build error

**Expected behavior**
remove the IToolPanel from import to prevent the build error.

**Minimal reproduction of the problem with instructions**
file `ag-grid-angular/src/interfaces.ts` imports:
![ag-interfaces](https://user-images.githubusercontent.com/11920691/48336242-27931680-e660-11e8-8a68-ea922fd5fd70.PNG)

run the `ng serve` with `noUnusedLocals` proerty turned on in tsconfig, you get this error:
![ag-error](https://user-images.githubusercontent.com/11920691/48336245-2b269d80-e660-11e8-9f79-31fa81b7ce8a.PNG)

**What is the motivation / use case for changing the behavior?**
fix error

**Please tell us about your environment:**
Windows 10, latest vscode, angular cli 7.0.3

* **ag-grid-angular version:** 19.1

this issue is there since v 19.0

* **Angular version:** 7.0.3

* **Browser:**  not related

* **Language:**  Typescript 3

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi this should be fixed in our next release before the end of year (20.x)

**Comment by GeorgeKnap** [comment]
@makinggoodsoftware 
this was promised to be fixed in v20 but isn't.

```
 in c:\Development\solar-log\core-ui-v1\enerest\node_modules\@angular\material\_theming.scss (line 1293, column 34)ERROR in node_modules/ag-grid-angular/src/interfaces.ts(20,5): error TS6133: 'IToolPanel' is declared but its value is never read.
```
