### ISSUE TITLE
ag-grid-community package is bolated with unused files

### ISSUE THREAD

**Issue by Teamop** [ag-grid/ag-grid#2768]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Right now, with the latest version ag-grid-community lib is bloated with many unused files.
![image](https://user-images.githubusercontent.com/8519685/48354188-02d48880-e6cc-11e8-8d29-8161867b2a46.png)

Can check from [here](https://npm.runkit.com/ag-grid-community)
**Expected behavior**

Should just include the needed files
* **ag-Grid version:** 19.1.2

* **Language:** [all]

**Comment by JabbyPanda** [comment]
Using `npm pack` and `.npmignore` file shall help

**Comment by JabbyPanda** [comment]
Related issue #1459
