### ISSUE TITLE
Can I use ag-grid-community and build my own grouping feature on top of it?

### ISSUE THREAD

**Issue by artfuldev** [ag-grid/ag-grid#2769]
Since ag-grid-community is MIT licensed, could I build my own grouping feature on top of it (and release it with MIT license as well)?

**Comment by ceolter** [comment]
Legally we cannot stop you, however we would think it's bad taste if you did, as you are then working against the ag-Grid core team. ag-Grid Enterprise is what funds the ag-Grid Community project and pays our salaries. If you find ag-Grid Community useful, then we ask that you support us and appreciate we need to pay our mortgages and send our kids to school just like anyone else.

**Comment by artfuldev** [comment]
I never had doubts on the legality of it; I just wanted to know how you felt about this as a team. I understand and appreciate the complexity of the situation; it makes sense not to pursue this. Thank you!

A little backstory: I tried to get the pricing for ag-grid-enterprise as part of a team but it was completely out of proportion in terms of the value it provided us. You have a fine product, and we would've just needed grouping on top of what the community edition provides.

You've built something amazing, I thank the team again.

**Comment by 13322211021** [comment]
`A little backstory: I tried to get the pricing for ag-grid-enterprise as part of a team but it was completely out of proportion with the value it provided us. You have a fine product, and we would've just needed grouping on top of what the community edition provides.`
Same pain. It would be great if AG could price based on functional modules
