### ISSUE TITLE
setColumnDefs does not repaint the grid

### ISSUE THREAD

**Issue by namnn** [ag-grid/ag-grid#2771]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

We are having a grid with dynamic group (i.e. rowGroup can be programmatically changed). To do that, we used `setColumDefs` to rebuild the grid.

In version 19.0.0 everything works fine.

**Current behavior**

`setColumnDefs` doesn't repaint the grid (or maybe it does, but not applying the new columnDefs to the view)

**Expected behavior**

`setColumnDefs` repaints the grid with new columnDefs

**Please tell us about your environment:** Windows, npm

* **ag-Grid version:** 19.1.2

* **Browser:** Chrome

* **Language:** [TypeScript]

**Comment by DespotMagic** [comment]
I have a similar behavior when using property bindings (columnDefs variable) in an Angular application.

A workaround that works (but definitely not good):
```
this.columnDefs = null;
this.changeDetectionRef.detectChanges();

this.columnDefs = this.createColumnDefs();
this.changeDetectionRef.detectChanges();
```
After update to ag-Grid version: 19.1.2. Before that, everything worked.

**Comment by iwangbowen** [comment]
I encounter the same issue. Version 19.0.0 works fine after calling setColumnDefs, but all later versions fail. But 19.0.0 has problem showing paging panel span element text color with ag-theme-blue. So I have to manually change the style in order to work around.

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
Hi guys,

This is to do with a change with delta columns introduced in 19.1

From v19.1.0 delta columns are available, this means that now you can change the column definitions dynamically without causing the grid to reset.

Note that this feature is still being polished and we are thinking about possibly changing the way it works, but for the time being the key points are:

 

1- If you want to update some existing columns, DON'T do it through setColumnDefs. Instead get a reference to that column, change it any way you want and then call refreshHeader

https://www.ag-grid.com/javascript-grid-column-definitions/#changing-column-headers

 

2.- If you want to add or remove columns, then you need to call setColumnDefs, note that changes to already existing columns passed here are not going to be picked up, but new or removed columns will be deleted from the grid

https://www.ag-grid.com/javascript-grid-column-definitions/#column-changes

 

As mentioned above, we are considering consolidating the setColumnDefs as the golden source of truth, the investigation that we are carrying for this is tracked with this issue:

 

AG-2289
Delta Columns - Investigate if it we should consider setColumnDefs as the golden source for delta columns.

**Comment by makinggoodsoftware** [comment]
By 20.x (ETA before end of year) we should have a clear strategy to set delta columns.

**Comment by IT-CASADO** [comment]
I noticed this week the same breaking change.

[Set new column definition by setColumnDefs doesn't work anymore](https://github.com/ag-grid/ag-grid/issues/2771)

This change should be reverted or at least provide a parameter for the method setColumnDefs(onlyDelta = false).

**Comment by makinggoodsoftware** [comment]
Hi,

Sorry for that, as mentioned above, you should find a final solution in our v20.x release (eta 4/5 weeks)

Thanks

**Comment by Troyd-Destin** [comment]
I guess the best thing to do is run 19.0, until 20.x is out?

**Comment by makinggoodsoftware** [comment]
Hi guys,

Just to let you know that this is going to be released in v20.1 ETA 4/5 weeks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2289 | Delta Columns - Allow for delta columns based on the state provided by a store
-- | --

**Comment by gustavomick** [comment]
@makinggoodsoftware noticed that this ticket is closed but i have a similar issue using "ag-grid-enterprise": "^20.1.0" basically if i reorder the columns using 
```
   this.agGrid.api.setColumnDefs(this.colDefs);
   this.agGrid.api.setServerSideDatasource(this.datasource);

```
is not changing grid order, if i do 
```
   this.agGrid.api.setColumnDefs([]);
   this.agGrid.api.setColumnDefs(this.colDefs);
   this.agGrid.api.setServerSideDatasource(this.datasource);

```
is indeed ordering colunns as i expect, but is also calling getRows 3 times, and hitting 3 times server. could you give me any tip  related to this. thanks

**Comment by boris-meerovich-sp** [comment]
> @makinggoodsoftware noticed that this ticket is closed but I have a similar issue using "ag-grid-enterprise": "^20.1.0" basically if I reorder the columns using
> 
> ```
>    this.agGrid.api.setColumnDefs(this.colDefs);
>    this.agGrid.api.setServerSideDatasource(this.datasource);
> ```
> is not changing grid column order, if I do
> 
> ```
>    this.agGrid.api.setColumnDefs([]);
>    this.agGrid.api.setColumnDefs(this.colDefs);
>    this.agGrid.api.setServerSideDatasource(this.datasource);
> ```
> is indeed ordering columns as I expect, but is also calling getRows 3 times, thus hitting 3 times server. could you give me any tip related to this. thanks

Same with version 20.2.0....

**Comment by iiiok** [comment]
this.agGrid.api.setColumnDefs([]);
this.agGrid.api.setColumnDefs(this.colDefs);

That is the answer! 
setColumnDefs doesn't detect the changes of some Column Properties, like "hide", "rowGroupIndex"...
refreshCells()... are not the answer, just empty the whole array before update it.
thanks @gustavomick

**Comment by greenArrow1** [comment]
Hi, I have recently updated ag-grid in project from verison 19.0 to 21.0.1.
I was saving user's preference of col order and on deletion on all of them resets the grid to original order which is defined in coldef array in my component.
Now after introduction of delta columns, when I delete all of the save preferences and then passing the new column definition to [coldef]  the grid is not re-setting to this column order.
After enabling deltaColumnMode=true the work is done but new thing came up, that is the filters are also getting saved till user refreshes the page. How can i avoid this behaviour?
Hope I am clear with my question.

**Comment by jcmorris** [comment]
If you're only looking to hide/show columns, you can use `setColumnVisible`/`setColumnsVisible` instead of emptying the columnDefs array:  `columnApi.setColumnVisible('field_name', false);`

**Comment by cdelgadob** [comment]
> this.agGrid.api.setColumnDefs([]);
> this.agGrid.api.setColumnDefs(this.colDefs);
> 
> That is the answer!
> setColumnDefs doesn't detect the changes of some Column Properties, like "hide", "rowGroupIndex"...
> refreshCells()... are not the answer, just empty the whole array before update it.
> thanks @gustavomick

You are so right, thanks for your answer!
This seems the only way to trigger are-evaluation of the conditions in the `columnDefs` array.
No other change detection mechanism seems to work.

**Comment by whittssg** [comment]
Maybe not the same issue but similar:

I want to remove grouping dynamicallly:
```
   this.gridOptionsHome.api.getColumnDef("_source.indexName").headerName = "Group Removed Header";
   this.gridOptionsHome.api.getColumnDef("_source.indexName").rowGroup = false;
   this.gridOptionsHome.api.refreshHeader();
```

The header name changes but the is still there. Maybe Im not refreshing the good part of the grid?

Thanks (sorry if this is completely unreleated but it sounded close)

**Comment by JabbyPanda** [comment]
In order for `ag-grid` to pick up column order and column pinned status changes in the runtime please set `deltaColumnMode` API for your grid.

If you are on ag-grid >23.1.1 or newr `deltaColumnMode' API was renamed to  `immutableColumns`

https://github.com/ag-grid/ag-grid/commit/ae1854ad736473a3d2a05752ca3fed0df78c79b1

**Comment by demiro** [comment]
well, I am doing this:
```
const defs: any[] = this.gridOptions.columnDefs;
defs[0].columnDefscheckboxSelection = true;  // my id column
this.gridOptions.api.setColumnDefs([]);  // with this or without - not working
this.gridOptions.api.setColumnDefs(defs);
```

So I want to be able to add checkbox on the column programatically (just the flow we need)... and unless I do another grid with just that, it is not working as wanted

**Comment by deexidee** [comment]
better way is to 
let columnState = gridOptions.columnApi.getColumnState();
// change the state (hide, sort, etc)
gridOptions.columnApi.applyColumnState({ state: changedState });
