### ISSUE TITLE
Documentation version switching

### ISSUE THREAD

**Issue by lobo78** [ag-grid/ag-grid#2775]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
[X] documentation request'
```

**Providing a Reproducible Scenario**
Documented ag-Grid features do not specify which version of the library for which the feature became available. Many users will not immediately upgrade to the latest version, and may often be running several versions behind the latest release. Reading the docs for these users can be confusing and lead to wasted effort in trying to implement a feature in a version for which it does not exist. Please allow viewing documentation for different versions of the library such as is done with the Angular documentation (https://angular.io/docs) or the LoDash library (https://lodash.com/docs/)

There is already a way to view documentation for older versions as mentioned in [https://github.com/ag-grid/ag-grid/issues/449#issuecomment-143568462](https://github.com/ag-grid/ag-grid/issues/449#issuecomment-143568462), now just add a dropdown to the main documentation page (https://www.ag-grid.com/documentation-main/documentation.php) to switch between them.

**Comment by makinggoodsoftware** [comment]
Hi,

Even though this is one that is easy to agree with, I am afraid that it will be very difficult for us to do a this stage.

Just to not let people have false hopes I am going to close it down for the time beins since, as I said, it is very unlikely that we will be able to provide with this functionality.

In any case, thanks for the feedback

**Comment by anatoly314** [comment]
@makinggoodsoftware, you guys have done one of the most advanced grid on the Internet but add an option to switch between various versions of docs is difficult? I feel that there's another reason? Cause users to use latest version maybe?

**Comment by toomanyjoes** [comment]
@makinggoodsoftware yes this is pretty infuriating. We spent $1000 for this software and now that we're finally getting to implementation the online docs are useless to us. How am I supposed to know what functions are available in the version I spent $1000 on?

**Comment by JabbyPanda** [comment]
Please use https://www.ag-grid.com/archive/ for time being for obtain documentation for previous released versions of `ag-grid`

**Comment by Constaline** [comment]
how to preview previous documents in local environment ?

**Comment by gportela85** [comment]
@Constaline Hey Akai...to preview the docs in the local environment, you would need to build the grid in your local environment and then run `npm run docs`. Unfortunately, we can't provide any help with that process.

**Comment by Constaline** [comment]
> @Constaline Hey Akai...to preview the docs in the local environment, you would need to build the grid in your local environment and then run `npm run docs`. Unfortunately, we can't provide any help with that process.

emm…  it is getting error to build docs in local environment, but using archive file is fine. thanks.
