### ISSUE TITLE
Cell using stateless components are not updated when setting deltaRowDataMode: true.

### ISSUE THREAD

**Issue by raybooysen** [ag-grid/ag-grid#2776]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Cell using stateless components are not updated when setting deltaRowDataMode: true.
https://plnkr.co/edit/lcBnco5HhcgYc3HPJmxN

**Expected behavior**
Cell using stateless components should be updated when setting deltaRowDataMode: true.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
19.1.2

* **Browser:**
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by raybooysen** [comment]
I thought this was fixed in #2562 but I can reproduce in 19.1.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi ,

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2369 - Stateless react components don't work with delta row data

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket- 

Regards

Rod‍

**Comment by raybooysen** [comment]
thanks
