### ISSUE TITLE
Export to Excel in Pivot Mode

### ISSUE THREAD

**Issue by fgruchala** [ag-grid/ag-grid#2777]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Hi, when I'm in mode Pivot in this configuration :

```
{
        colId: 'labelOffer',
        headerName: 'Offer',
        field: 'labelOffer',
        pinned: 'left',
        enablePivot: true,
},
{
        colId: 'labelStore',
        headerName: 'Store',
        field: 'labelStore',
        pinned: 'left',
        enableRowGroup: true,
},
...
```

I have this UI representation :
<img width="599" alt="capture d ecran 2018-11-16 a 14 05 08" src="https://user-images.githubusercontent.com/12196721/48623153-2f78f080-e9a9-11e8-9472-1b18fd1abfa8.png">

The problem is when I want to export it in Excel and I have this issue in the console :
<img width="891" alt="capture d ecran 2018-11-16 a 14 10 07" src="https://user-images.githubusercontent.com/12196721/48623436-ebd2b680-e9a9-11e8-9205-a4a4c48c857b.png">

And after analysing, it seems that the top left cell generate a null value at the index 0 :
<img width="312" alt="capture d ecran 2018-11-16 a 14 12 07" src="https://user-images.githubusercontent.com/12196721/48623472-06a52b00-e9aa-11e8-80f1-9ec796baa48c.png">

**Expected behavior**
Export a pivot table in Excel.

**Environment:**
macOS Mojave 10.14.1
WebStorm 2018.2.3
NPM 6.4.1

**ag-Grid version:**
19.1.2

**Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Language:** 
ES6/7

**Comment by gportela85** [comment]
this issue has been patched for the next release
