### ISSUE TITLE
ag-grid (onCellValueChanged) event changes oldValue from number to string

### ISSUE THREAD

**Issue by igpeev** [ag-grid/ag-grid#2781]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
**Current behavior**

1. Go to any number (e.g. 33) in the column with numbers. 

2. Edit it to any other, e.g. 77.

3. Click on any other cell (to stimulate onCellValueChanged event firing)

4. The (onCellValueChanged)="myCallBack($event) fires and in the event object the property .oldValue is flipped from number to string, i.e. 33 is shown as "33"

 

- A stackblitz: 
[HERE](https://stackblitz.com/edit/zaggi-angular-ag-grid-bugs)

**Expected behavior**
When the value in .oldValue was a number, it remains a number (a number, i.e. 33, not "33")

**Please tell us about your environment:**
Angular

* **ag-Grid version:** X.X.X
    "@angular/common": "^7.0.1",
    "@angular/compiler": "^7.0.1",
    "@angular/compiler-cli": ">=2.1.x",
    "@angular/core": "^7.0.1",
    "@angular/forms": "^7.0.1",
    "@angular/platform-browser": "^7.0.1",
    "@angular/platform-browser-dynamic": "^7.0.1",
    "@angular/router": "^7.0.1",
    "ag-grid": "^18.1.2",
    "ag-grid-angular": "^19.1.2",
    "ag-grid-community": "^19.1.2",
    "ag-grid-enterprise": "^19.1.2",
    "core-js": "^2.5.7",
    "rxjs": "^6.3.3",
    "typescript": ">=3.1.1 <3.2",
    "zone.js": "^0.8.26"

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Our consultants have put together the following example for you

You need to use a valueSetter even if using colDef.type = 'numeric' the reason being that we will always treat everything as a string

This can be seen in the following stackblitz

https://stackblitz.com/edit/zaggi-angular-ag-grid-bugs-qpkcrm?file=src/app/app.component.ts

Can you please have a look and see if it make sense?

Hope this helps.
