### ISSUE TITLE
Data change flash animation timeout should be configurable.

### ISSUE THREAD

**Issue by ranjeethkrao** [ag-grid/ag-grid#2782]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
According to [this ](https://www.ag-grid.com/javascript-grid-data-update/#how-flashing-works) documentation, 

> Each time the call value is changed, the grid adds the CSS class ag-cell-data-changed for 500ms, and then then CSS class ag-cell-data-changed-animation for 1,000ms

However I need a much more prolonged highlighting of the row. I tried to override the class `ag-cell-data-changed-animation`  as follows:

```
.ag-dark .ag-cell-data-changed {
    background-color: white !important;
    color: black;
}
.ag-dark .ag-cell-data-changed-animation {  
    background-color: transparent;  
    color: #ccc;
    transition: background-color 5s !important;  
    -webkit-transition: background-color 5s !important;  
    -moz-transition: background-color 5s !important;  
    -o-transition: background-color 5s !important;  
}  
```

However since this class is applied only for a fixed 1000ms, the animation is not rendered as desired (for 5 seconds, in this case)

**Current behavior**
There is no way to modify the time duration until which the CSS class `ag-cell-data-changed-animation` is applied.

**Expected behavior**
There should be means to configure this parameter, so that the row flashing animations can be customized.

* **ag-Grid version:** 18.1.1

* **Browser:**
Tried on Chrome, Mozilla Firefox and Safari, The behavior is consistent.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
