### ISSUE TITLE
Indeterminate checkbox icon not displayed in header selection checkbox

### ISSUE THREAD

**Issue by boris-meerovich-sp** [ag-grid/ag-grid#2784]
**I'm submitting a bug report
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Scenario:
- Select one row
- Examinate header checkbox state
Expected: 
Actual: header checkbox is empty
Plunker: [https://plnkr.co/edit/18wgofqaWyCDwBa7W4bS?p=preview](url)

**Current behavior**
header checkbox is empty

**Expected behavior**
indeterminate checkbox icon should be displayed

**Please tell us about your environment:**
The plunker is created from [ducumentation section](https://www.ag-grid.com/javascript-grid-selection/#header-checkbox-selection)

* **ag-Grid version:** 19.1.2

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2351	Allow three states for header column row selection (ALL, SOME, NONE) simmilar to set filter

**Comment by boris-meerovich-sp** [comment]
Thanks for pushing it to the pipeline.
I'm wondering why it's a feature request? This "feature" worked in previous versions (until 19.1.0).
It looks like a regression bug...

**Comment by jamespero** [comment]
@makinggoodsoftware I have to agree with @boris-meerovich-sp on this one. It was working in previous versions.

**Comment by jamespero** [comment]
@makinggoodsoftware This was already a working feature in the enterprise angular package and is now broken in the newer versions. I see a plunker on zendesk that demos it in 19.1.4 (latest as of today) but from my understanding the angular package is still only on 19.1.2

**Comment by lPaths** [comment]
i'm using ag-grid-react 19.1.2 and getting the same bugs, is there any fixes?

**Comment by boris-meerovich-sp** [comment]
I'm using angular 20.2.0 and the bug is fixed

**Comment by lPaths** [comment]
> I'm using angular 20.2.0 and the bug is fixed

ag-grid-react 20.2.0 is same, bug still there
