### ISSUE TITLE
Tooltips (Bootstrap) when cell is rendered

### ISSUE THREAD

**Issue by nea** [ag-grid/ag-grid#2785]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'
```

* **ag-Grid version:** 19.1
* **Language:** [ES5]

**Requesting Community Support**
Hi everyone

I am looking to trigger a specific Javascript on a cell as soon as it is rendered (Bootstrap tooltip to be specific). The table has >30 columns and >500 rows. I auto size the columns.

I trigger the tooltip init `onVirtualColumnsChanged` and `onViewportChanged` as well as `onGridReady` (just to be sure ^^'). But autosize does not seem to trigger any of these. The columns which come into view after autosize do not have tooltips accordingly. Even if I trigger tooltips at the end of autosizing.

Does anybody have any idea what would be the best to have Bootstrap tooltips inited on potentially each cell as soon as it is rendered?

Thanks a lot in advance

**Comment by zapacila89** [comment]
What about event "columnResized"? Have you also tried that? And you can also try to redraw the rows.

**Comment by nea** [comment]
Hey @zapacila89 

Haven't tried "columnResized" as I did not think it would trigger as I am not resizing anything.

I figured out that "onVirtualColumnsChanged" fits well but I have to timeout for some minimal milliseconds before triggering the tooltips. That works fine.


Thanks
