### ISSUE TITLE
How to remove extra space at the bottom when pagination is enabled

### ISSUE THREAD

**Issue by brendonco** [ag-grid/ag-grid#2786]
When only few items are shown from the table and pagination is enabled, how do I remove extra space at the bottom?

<img width="416" alt="remove-extra-space-pagination" src="https://user-images.githubusercontent.com/6521691/48817203-468c5980-ed80-11e8-8023-2f83783e65c6.PNG">

**Comment by zapacila89** [comment]
[domLayout='autoHeight'](https://www.ag-grid.com/javascript-grid-width-and-height/#auto-height)

**Comment by brendonco** [comment]
Ok, domLayout='autoHeight' doesnt work if dynamic pagination is enabled.
