### ISSUE TITLE
Updating Viewport datasource doesn't refresh AgGrid content

### ISSUE THREAD

**Issue by ATrogolo** [ag-grid/ag-grid#2792]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

**Here the Plunkr with a live example: [Example Code](https://plnkr.co/edit/EGQczTTxI74iooT1nH0w)**

**Current behavior**
I'm using AgGrid Enterprise edition with `Viewport` DataSource. I've found a bug while setting a new datasource to an instance of AgGrid. 
If the datasource provides data with the same size (setting it in `setRowCount()`) the grid doesn't refresh data: it doesn't call `setViewportRange()` method.  
What happens is that old rows are deleted, but the grid remains empty. 

**Expected behavior**
I'd like to see new data fetched from the new setted datasource. 

**Please tell us about your environment:**
**OS:** Windows 10
**IDE:** VSCode v.1.29.0 
**Web Framework:** React 
**Package manager:** Npm 
**Bundler:** Webpack v.4.19

* **ag-Grid version:** 19.0.0

* **Browser:**
**Chrome:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Firefox:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**MS Edge:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

* **Language:** [TypeScript 3.14]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2390

Viewport row model - Data not updating if setting datasource and amount of records matches previous datasource

**Comment by ATrogolo** [comment]
Hi @makinggoodsoftware,
I can't find the item in the pipeline. 
This issue in which release of ag-grid has been fixed? 

Thanks,
Andrea
