### ISSUE TITLE
Custom React cell renderer + selection on column - component not visible

### ISSUE THREAD

**Issue by photusenigma** [ag-grid/ag-grid#2793]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I believe related to #2299 
Plunkr from #2299 which demo's our issue: https://plnkr.co/edit/nEfbFhbPoIcul0Z28BkP?p=preview
Plunkr forked from above showing work-around: https://plnkr.co/edit/j4PoBBONrUuQhEftEQEx?p=preview

Work around is simply to not use custom renderer in same column as the one used to select the row.  The two don't mix well.

If reporting a bug make sure to state.

Current behaviour.

Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
If you attempt to use a React custom renderer via `cellRendererFramework` prop on columnDef for same column being used for row selection checkbox (firstColumn in our case), the custom component will render to the DOM, but won't be visible.

**Expected behavior**
Using a React custom renderer via `cellRendererFramework` prop in columnDef for the same column being used for the row selection checkbox will render both checkbox and the custom component as expected.

**Please tell us about your environment:**
MacOS 10.13.6, VisualStudio Code, yarn, 

* **ag-Grid version:** X.X.X

* **Browser:**
```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36```
```Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0```

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Attempted and experienced same issue in projects done in both Typescript 3.1.6 and also plain ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

This is not a bug, it is actually how the grid is meant to work.

Thanks

**Comment by jakwuh** [comment]
@makinggoodsoftware could you please explain why it is not an issue and how to use custom React cell renderer + selection on that column?

**Comment by jimioh** [comment]
@makinggoodsoftware Very unhelpful support. Will be following up via enterprise channels as we are experiencing the same and this 'functionality' as you describe it doesn't make sense.

**Comment by kw-at-oocl** [comment]
Has any workaround been found for this?  In version 20.2.0 this worked fine (combining a custom renderer with checkBoxSelection) but on upgrading to 25.1.0 we see the custom renderer is no longer working for a checkBoxSelection column.
