### ISSUE TITLE
Filtering agDateColumnFilter by ascending and descending

### ISSUE THREAD

**Issue by naziz0822** [ag-grid/ag-grid#2795]
Hello guys,

Running into unexpected behavior for columns filtered by ```agDateColumnFilter```.
Any help or insight would be appreciated.

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducing the behavior**
1. Navigate to 
``https://www.ag-grid.com/javascript-grid-column-definitions/#column-changes`` or
``https://www.ag-grid.com/javascript-grid-column-definitions/#group-changes``
2. Test out the Ascending and Descending filter where the data is a Date Type.

**Current behavior**
Does not filter in ascending and descending order properly, neglects to account for the year.

**Expected behavior**
When sorting in descending order :arrow_down: I expect dates with the year 2006 to be before 2010.
The opposite behavior is expected in ascending order :arrow_up:

**Please tell us about your environment:**
Windows 10, Visual Studio Code, NPM

* **ag-Grid version:** X.X.X
ag-grid: ^17.1.1
ag-grid-vid: ^17.1.0

* **Language:** [Vue.JS]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by naziz0822** [comment]
Thanks @makinggoodsoftware , appreciate the help!

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2395

Docs - Date column in the column header examples is not sorting by date
