### ISSUE TITLE
Column's width become more and more narrow when showing/hiding.

### ISSUE THREAD

**Issue by hunfatal** [ag-grid/ag-grid#2799]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behaviour**
If I hide a column, then show it, then hide it multiple times, the column became narrow each time when it shows (columns are sized to fit).

**Expected behaviour**
The columns width should be the same each time when it shows.

Here is a stackblitz example:
[https://stackblitz.com/edit/angular-ag-grid-19-column-show-hide-size-issue](https://stackblitz.com/edit/angular-ag-grid-19-column-show-hide-size-issue)

Just press the hide/show button multiple times, and you can see that the 'value' column will be more narrow each time, until the header text is not visible at all.

**Please tell us about your environment:**

Doesn't matter, but Windows 8.1, npm, angular and IntelliJ IDEA or Visual Studio Code

* **ag-Grid version:**

ag-grid-community: 19.1.4
ag-grid-angular: 19.1.2

* **Browser:**

Latest Firefox Developer, latest Chrome or IE11.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript, didn't try other.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by hunfatal** [comment]
Hi,

Thank you.

**Comment by makinggoodsoftware** [comment]
Hi ,

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2385 -  Columns - Hiding and showing the same column in succession causes the column to decrease in width 

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket- 

Regards

Rod‍

**Comment by hunfatal** [comment]
Hi,

Thank you!

**Comment by hunfatal** [comment]
@makinggoodsoftware 
Is there any ETA for this issue to get resolved?
