### ISSUE TITLE
Date Filter: In Range condition - both dates should be interchangeable

### ISSUE THREAD

**Issue by cdawi** [ag-grid/ag-grid#2803]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Any AG-grid, take the example grid shown below:
https://www.ag-grid.com/javascript-grid-date-component/#gsc.tab=0
For the date column, if you select in range condition, and enter
23-08-2008
25-08-2008
you will get filtered results. But if you swap the dates around e.g.:
25-08-2008
23-08-2008
you will get no results when there should have been

**Current behavior**
When using inRange condition of date filter, swapping (dateFrom and dateTo) dates around does not give the same filtering result

**Expected behavior**
InRange should only care about the range, not the order of the dates. Whether I put the earliest date first or last shouldn't matter

* **ag-Grid version:** 19.1.4
* **Browser:** [all]
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
