### ISSUE TITLE
Ag-Grid with Angular Material Design Components as Cell Editors(Selection problem)

### ISSUE THREAD

**Issue by reyzenkind** [ag-grid/ag-grid#2804]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Some of the components from Angular Material Design used as Cell Editor in Popup Mode do not work as expected. For example Select Component. You can "select" any option from dropdown menu, but the value in the edited cell is not updated. The same problem with Datepicker and Autocomplete components.

You can reproduce it online (ag-Grid with Material Design Components - Set 1):
https://www.ag-grid.com/example-angular-material-design/

Try to change any of "vegetable" cells.

**Expected behavior**
 Angular Material Design Components used as Cell Editor in Popup Mode should work as expected

* **ag-Grid version:** 19.1.X
* **Angular:** 7.0.X

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-2359 | Material Examples - The custom renderers for material have issues with some of the editors
-- | --

**Comment by KrzysztofKarol** [comment]
Hi @makinggoodsoftware,

I cannot find this issue in https://www.ag-grid.com/ag-grid-pipeline/

How I can find it? What is the status of it?
