### ISSUE TITLE
Typeerror: cannot read property 'subMenu' of undefined

### ISSUE THREAD

**Issue by ndce06** [ag-grid/ag-grid#2808]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- When you pass 'toolPanel' as the getContextMenuItems - call back it's throws the error cannot read property 'subMenu' of undefined.

- A plunker - https://plnkr.co/edit/LuQ5XnqHY4dUmKOI1TwP?p=preview 

- I'm using ag-grid v19.1.1. Also the document mentioned that 'toolPanel' is in build menuItem. 
https://www.ag-grid.com/javascript-grid-context-menu/ - I have used the same plunkr available on this page - Just add 'toolPanel' - to the getContextMenuItems - it will break.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. This is has been raised before, and we are currently tracking already in our pipeline with the following number and description.


AG-2352 - Context menu - Tool panel default item not working anymore

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket- 

Regards

Rod‍
