### ISSUE TITLE
No load indicator when fetching uncached records from datasource

### ISSUE THREAD

**Issue by ronyf** [ag-grid/ag-grid#2811]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/5aN0sC3Wu9V4dZtUltp9?p=preview
(forked from [here](https://www.ag-grid.com/javascript-grid-server-side-model-pagination/))

**Current behavior**
When I move to the third page (that is beyond to what was already cached), there's no loading icon.. only blank lines that are later filled with data.

**Expected behavior**
Loading indicator when the data is being fetched drom the datasource.

**Please tell us about your environment:**
Same as the one in the example I forked from

* **ag-Grid version:** 19.1.4
Same as the one in the example I forked from

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

* **Language:** 
Same as the one in the example I forked from

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

If you change your code to:

this.components = {
  loadingRenderer: function(params) {
    if (params.value !== undefined) {
      return params.value;
    } else {
      return '<img src="../images/loading.gif">';
    }
  }
};

It should work

Here our plunker with pagination:

https://plnkr.co/edit/26GrzP6r8S7zeYwRzrkm?p=preview

**Comment by ronyf** [comment]
Hi @makinggoodsoftware 

I applied the change on my plunker
https://plnkr.co/edit/2Na9dulYDRwIOcx5Um57?p=preview

and it didn't do anything

**Comment by ronyf** [comment]
@makinggoodsoftware can you please reopen the issue? it's not resolved
