### ISSUE TITLE
ag-row-odd class is applied to even rows, not odd ones.

### ISSUE THREAD

**Issue by dflock** [ag-grid/ag-grid#2818]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Inspect any instance of ag-grid and look at the classes that get applied to the rows.

**Current behavior**
Even numbered rows in the grid (2nd row, 4th row, etc...) get the `.ag-row-odd` class applied to them, odd rows do not.

**Expected behavior**
I would expect `.ag-row-odd` to be applied to odd rows, i.e. 1st row, 3rd row, etc...

**Please tell us about your environment:**

* **ag-Grid version:** 19.1.4

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for this ticket, I can also see that you have another very similar ticket, I am going to close this one and continue the conversation from the other one

Thanks
