### ISSUE TITLE
Material theme is missing the column resizer

### ISSUE THREAD

**Issue by vially** [ag-grid/ag-grid#2821]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Example page where the bug manifests: https://www.ag-grid.com/example.php#/

**Current behavior**

Open the example page linked above and select the Material theme. The column resizer is not visible (e.g.: the small vertical line). Although hovering over it with the mouse changes the cursor and allows for column resizing.

**Expected behavior**

The column resizer should be visible for the material theme. This used to work in version 18. The commit that broke it is 539874a05cb0fcfca6dfb8454721e61b50c28306. That commit removed the CSS rule that displayed the column resizing indicator. Looking at the CSS seems to suggest the resize indicator might still be there for a RTL grid, but I haven't tested that.

**Please tell us about your environment:**

Linux

* **ag-Grid version:** X.X.X

19.1.4

* **Browser:**

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36`

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

N/A

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2420

Material theme is missing the column resizer

**Comment by saideekshith66** [comment]
Not able to find issue by key AG-2420 on https://www.ag-grid.com/ag-grid-pipeline/

Could anyone please share the status.
