### ISSUE TITLE
Ag-Grid Headers not Displaying when changing menu icon in grid options Still broken for at least 2 themes

### ISSUE THREAD

**Issue by killyosaur** [ag-grid/ag-grid#2822]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
https://plnkr.co/edit/w4LOxXahQ0nnnTG312We?p=preview
(ag-themed-belham works but that is not the theme I am using)

**Expected behavior**
I should still see the menu text when I use a custom function or string value for the icons in the grid
This worked in previous versions of the grid

**Please tell us about your environment:**
OS: Windows, IDE Visual Studio 2017, bower, IIS

* **ag-Grid version:** X.X.X
found in 19.1.4
using theme **ag-theme-fresh** and **ag-theme-dark**

not sure if the below still happens, but if you haven't removed these themes, you should check to be sure they work correctly:
When using the old theme-fresh, this does not happen (although the menu does get blocked by the row if the row or a cell in the row is selected)

* **Browser:**
Browsers: IE, Chrome, Fire Fox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Because the $icon-size of ag-theme-balham is different (16px) while the size of the icon on ag-theme-dark is 12px.
The size of the text is calculated with calc(100% - $icon-size) and the customer is putting an icon wider than 12px there.

To get this to work, limit the size of the icon with CSS changes as I showed in the plunker, or they should customize their own themes extending ag-theme-dark and replacing the $icon-size variable.

https://plnkr.co/edit/A4Bb2haRObnXlBQevlWx?p=preview

**Comment by killyosaur** [comment]
kind of confused as to why the css hack is the fix for this. if custom icons are allowed in existing themes, shouldn't you have the themed override of your defaults handle that? especially considering it is your class that you are overriding...

**Comment by gportela85** [comment]
@killyosaur this restriction has been removed, you can add custom icons without using the `calc()` mentioned above.
