### ISSUE TITLE
`sortingOrder` is not included in Column.properties documentation

### ISSUE THREAD

**Issue by shea-parkes** [ag-grid/ag-grid#2824]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
[x] documentation fix request
```

The `sortingOrder` option is listed in the [Grid Properties API](https://www.ag-grid.com/javascript-grid-properties/) but not in the [Column Properties API](https://www.ag-grid.com/javascript-grid-column-properties/).  The example in the [Grid Sorting Example page](https://www.ag-grid.com/javascript-grid-sorting/#example-sorting-order-and-animation) shows that the option works as a column property however.

The [Column Properties API](https://www.ag-grid.com/javascript-grid-column-properties/) should be updated to include this option.

Bonus points for being explicit if the `null` option should be a string literal (i.e. `"null"`) or a true null (i.e. `null`).

I'm not a paying customer yet, but I just requested a trial.  I would personally think you'd want to fix this.  I searched the Column Properties API first for this functionality and was quite flummoxed when I couldn't find anything to set the sort cycle for a column...

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2438 - website - sortingOrder is not included in Column Properties documentation

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
