### ISSUE TITLE
groupSuppressBlankHeader property is not used

### ISSUE THREAD

**Issue by cobisimo** [ag-grid/ag-grid#2826]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
`groupSuppressBlankHeader` don't have any influence on header/footer aggregate data visibility when `groupIncludeFooter` is enabled. I checked ag-grid source code and it looks like method isGroupSuppressBlankHeader that is related to this property is not used anywhere.

**Expected behavior**
`groupSuppressBlankHeader` per documentation: If true, and showing footer, aggregate data will be displayed at both the header and footer levels always.

**Please tell us about your environment:**
Any, this issue is independent from environment.

* **ag-Grid version:** 17.1.1
I checked latest version 19.1.4, same issue.

* **Browser:** any
I use latest Firefox, but this issue is unrelated to browser.

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2445
Property 'groupSuppressBlankHeader' not getting used


You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
