### ISSUE TITLE
agGrid fails to show cellValues, when data object key has 'dot' in name. e.g 'S.No' 

### ISSUE THREAD

**Issue by sajus** [ag-grid/ag-grid#2828]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- You need data object which has key name having a 'dot' like.
 let data = {[
'S.no': 1,
'Name': A
],
[
'S.no': 2,
'Name': B
]
}
- https://next.plnkr.co/edit/O0H6PhUtqYsy0oh2

**Current behavior**
Cell values are not displayed, check the age column in plnkr 

**Expected behavior**
Cell values should  displayed, even when the object key has 'dot' in the name.

**Please tell us about your environment:**
NA

* **ag-Grid version:** X.X.X
NA

* **Browser:**
NA

* **Language:** 
NA

**Comment by makinggoodsoftware** [comment]
Hi,

Check the following plunker

https://next.plnkr.co/edit/oDVuKussGLavDjep

Hope this helps
