### ISSUE TITLE
Issue Populating Filter Value for AG Grid agSetColumnFilter

### ISSUE THREAD

**Issue by juminoz** [ag-grid/ag-grid#2829]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**
I'm an enterprise customer, but still waiting for ZenDesk login.

**Providing a Reproducible Scenario**
Not able to populate filter value for the filter. The example on Plunkr is a modification of the example provided by AG Grid. Open up console and you will see an error when clicking Athletes filter.

https://plnkr.co/edit/GURQHP0KKFpJ9kwaU83M?p=preview

If reporting a bug make sure to state.

Current behaviour.
Filters are populated asynchronously through provided function set in values param

**Current behavior**
Get this error when clicking on the filter.

Uncaught TypeError: Cannot read property 'onFilterValuesReady' of undefined
    at t.setFilterValues (ag-grid-enterprise.min.js:555)
    at e.modelUpdatedFunc (ag-grid-enterprise.min.js:555)
    at e.onAsyncValuesLoaded (ag-grid-enterprise.min.js:555)
    at values (main.js:22)
    at e.createAllUniqueValues (ag-grid-enterprise.min.js:555)
    at new e (ag-grid-enterprise.min.js:555)
    at t.initialiseFilterBodyUi (ag-grid-enterprise.min.js:555)
    at t.init (ag-grid-enterprise.min.js:327)
    at e.initialiseComponent (ag-grid-enterprise.min.js:159)
    at e.createAgGridComponent (ag-grid-enterprise.min.js:159)

**Expected behavior**
Filters are populated as expected.

**Please tell us about your environment:**
MacOS Latest Version

* **ag-Grid version:** X.X.X
AG Grid Enterprise 19.1.4

* **Browser:**
Test on latest version of Chrome and Safari

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Have a look at the following plunker..

https://plnkr.co/edit/1Ft6NrxfkqtbZ0TIWK23?p=preview

Hope this help

**Comment by i-amn** [comment]
@makinggoodsoftware why this is closed? it is still having same behaviour, and it is still the same issue
