### ISSUE TITLE
onSortChanged - stop the datasource request

### ISSUE THREAD

**Issue by ilmagowalter** [ag-grid/ag-grid#2837]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

I used ag-grid with rowModelType: 'infinite'

When I made a request of the sort, filter, or change page, the system runs the getRows of dataSource correctly.

I need to check the sort request ( or filter ) before run getRows and stop the execution.

```
onSortChanged: () => {
  if (something) {
    // continue with sort and execute getRows ...
  } else {
    // stop with sort and NOT execute getRows...
  }
};
```

is possible?

**Comment by ilmagowalter** [comment]
anyone ?

**Comment by steinitz** [comment]
Reopening.  I believe the original poster would like a way to abort the sort on certain conditions.  We also have a need for this.
