### ISSUE TITLE
reactNext / Portals implementation does not work with React 16.3 Context

### ISSUE THREAD

**Issue by hrgui** [ag-grid/ag-grid#2838]
This is the same as #2578, but it was closed; unfortunately the issue is still persisting in the latest ag-grid version. 

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
https://codesandbox.io/s/x74wn4mmow

**Current behavior**
- MakeCell returns `{}` from MakeContext.Consumer

**Expected behavior**
- MakeCell prints `{green: true}` from MakeContext.Consumer

* **ag-Grid version:** 19.1.4, ag-grid-react 19.1.2 
* **Language:** all

--- 

Investigation / Potential Fix
---

![screen shot 2018-12-15 at 11 38 06 pm](https://user-images.githubusercontent.com/5001432/50051212-00968d00-00c3-11e9-95ba-8553b68bd8b2.png)

I have created a PR with a possible fix in #2839 - but I don't know if there's missing test cases that I need to look out for - e.g. async as an example.

https://codesandbox.io/s/xo22qp6yl4 demonstrates that the fixes are working, and the expected behavior is showing
![screen shot 2018-12-16 at 12 18 19 am](https://user-images.githubusercontent.com/5001432/50051499-23777000-00c8-11e9-833a-956e4d36b815.png)

![screen shot 2018-12-16 at 12 14 31 am](https://user-images.githubusercontent.com/5001432/50051462-992f0c00-00c7-11e9-85cb-5f256a5d1851.png)
_This shows that it is possible to put all the portals in the same tree even though AgGrid has the full control of the DOM (due to ShouldComponentUpdate => false)_ 

React-Redux v6 and Legacy React Context
----

Since React-Redux now uses Context, passing down store as a prop is no longer allowed. With this fix, take out the `store={store}` prop and it should fix the issue.

See example here: https://plnkr.co/edit/IRuM34IDxZH6yUUHPOWO?p=preview

Legacy context also no longer needs `store={store}` prop as well.

**Comment by seanlandsman** [comment]
@hrgui thanks very much for both this issue and the PR you created - it'll definitely help

This is great timing as I'm literally looking at this side of things at the moment!

I'm close both this PR and the issue but will be incorporating the ideas manually as I have other changes in play at the moment.

Thanks again, this will def accelerate the final solution implemented. Once done feedback would be great too once done.

**Comment by spawnia** [comment]
The context is correctly passed as of version `22.0.0`.
