### ISSUE TITLE
Angular examples in https://www.ag-grid.com/ are all not working

### ISSUE THREAD

**Issue by tom10271** [ag-grid/ag-grid#2843]
Examples are the best way to understand how things work. Please fix

**Comment by tom10271** [comment]
The main cause is `https://unpkg.com/zone.js@0.8.17/index.js?main=browser` returns 404

**Comment by tom10271** [comment]
https://unpkg.com/zone.js@0.8.17/index.js?main=browser
https://unpkg.com/zone.js@0.8.17/dist/zone.js

**Comment by seanlandsman** [comment]
@tom10271 - can you please provide an example that doesn't work? What browser are you trying it on?

**Comment by tom10271** [comment]
![screen shot 2018-12-20 at 6 39 17 pm](https://user-images.githubusercontent.com/5089629/50280119-a1e85f00-0486-11e9-992c-fd325a63d3e0.png)

All dead for all examples Chrome Version 71.0.3578.98 (Official Build) (64-bit) with macOS 10.12.6

**Comment by tom10271** [comment]
Replacing `https://unpkg.com/zone.js@0.8.17/index.js?main=browser` with `https://unpkg.com/zone.js@0.8.17/dist/zone.js` fixes any plunker example

**Comment by seanlandsman** [comment]
I'm afraid I cannot reproduce this: https://plnkr.co/edit/N9yzTEswCmRecJsuWldt?p=preview

This URL works fine in the browser too, returning a valid file: https://unpkg.com/zone.js@0.8.17?main=browser

**Comment by tom10271** [comment]
https://www.webpagetest.org/result/181221_9C_3e0c6337365f9e797bac028c3c366b50/1/details/#waterfall_view_step1

It is not working in Hong Kong at least

**Comment by tom10271** [comment]
I have tested the connections of the JS worldwide using https://dotcom-tools.com

Here is the report, there are a few cities cannot access this file:
https://www.dotcom-tools.com/website-speed-test.aspx#DC46F4ADDF2347EEAF19AD78477B4989

**Comment by tom10271** [comment]
This report is testing the Zone.js file that works for me:

https://www.dotcom-tools.com/website-speed-test.aspx#76DDF08BD0404081B13F2E91B300C222
https://www.dotcom-tools.com/website-speed-test.aspx#994563571FCC484B840BD7340D343F44

**Comment by seanlandsman** [comment]
ok thanks - I'll update the file. Thanks for reporting this

Weird error!

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.


This is the reference and summary of the relevant issue:

AG-2462: Add ?main=browser to our plunker CDN urls to that they can be fetched in all geographical locations
