### ISSUE TITLE
Typescript type definition can be more strict if a field has certain acceptable options supported only

### ISSUE THREAD

**Issue by tom10271** [ag-grid/ag-grid#2844]
https://github.com/ag-grid/ag-grid/blob/master/dist/lib/entities/colDef.d.ts#L217

For example, the type definition I write will be

```ts
    /** one of the built in filter names: [set, number, text], or a filter function*/
    filter?: 'set' | 'number' | 'text' | {
        new (): IFilterComp;
    };
```

but not

```ts
    /** one of the built in filter names: [set, number, text], or a filter function*/
    filter?: string | {
        new (): IFilterComp;
    };
```

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by tom10271** [comment]
Does this mean GitHub issue will be closed after 14 days without reply? If so please include it in your copy and pasted comment. I am a bit confused.
