### ISSUE TITLE
Calling setColumnDefs with an existing column increments its ColId

### ISSUE THREAD

**Issue by saif003** [ag-grid/ag-grid#2846]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Upgrading to Ag-grid 19.1.2 from 19.0.0 has introduced an issue where calling `setColumnDefs`, with same column definition as previously or already present in the grid, increments its colId. This issue was not present in 19.0.0, and can be observed [here](https://stackblitz.com/edit/ag-grid-19-0-0-colid-not-being-incremented?file=src/app/app.component.ts), As a result calling methods `getFilterModel` or `getSortModel` returns incremented column names, like 'athlete_1' instead of 'athlete' and hence breaking all such functionalities.

I did some digging around the issue and found how colIds are [generated](https://github.com/ag-grid/ag-grid/issues/385#issuecomment-132232326), and that this [method](https://github.com/ag-grid/ag-grid/blob/a1f1fa8c028b61ebac605016d6ccda2d121d5239/dist/lib/columnController/balancedColumnTreeBuilder.js#L163-L170) is responsible for generating columns, which uses below method to generate colIds,

`var colId = columnKeyCreator.getUniqueKey(colDefMerged.colId, colDefMerged.field);`

looking at the definition of `columnKeyCreator.getUniqueKey`, it seems there were some recent changes in `columnKeyCreator` after which it has started incrementing colIds.

**I understand that `colId` can and should be incremented when two columns have same field property at the same time, but in cases like updating `colDef` this shouldn't be happening.**

**Current behavior**

Kindly consult [this](https://stackblitz.com/edit/ag-grid-19-1-2-colid-being-incremented) stackBlitz for reproduction, calling setColumnDefs generates new incremented ColId.

![19 1 4](https://user-images.githubusercontent.com/36731927/50287264-f0e0c500-0483-11e9-881d-16fe336758da.gif)

**Expected behavior**

ColIds shouldn't be incremented and should stay same. [Stackblitz](https://stackblitz.com/edit/ag-grid-19-0-0-colid-not-being-incremented?file=src/app/app.component.ts)

![19 0 0](https://user-images.githubusercontent.com/36731927/50287241-dc043180-0483-11e9-95d6-e776cb92b599.gif)

**Temporary Workaround**

for now i am using `gridApi.getColumnDef(colId)` to ensure both sorting and filtering runs smoothly, but I am not sure as this may or may not break some other grid functionalities.

```
const filterModel = gridApi.getFilterModel();
for (const colId in filterModel) {
        if (filterModel.hasOwnProperty(colId)) {
          const col = gridApi.getColumnDef(colId);
          // use col.field to map to columns instead of colId
        }
      }
```

**Please tell us about your environment:**

* **ag-Grid-community version:** 19.1.4
* **ag-Grid-angular version:** 19.1.2

* **Browser:**
Chrome 71.0.3578.98

* **Language:**
TypeScript 2.6.2

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-2289 | Delta Columns - Investigate if it we should consider setColumnDefs as the golden source for delta columns. | BACKLOG |   |   | More Info
  | AG-1559 | Allow delta updates to column definitions, this should include all CRUD operations | BACKLOG

**Comment by michaelchiowong** [comment]
Hi, AG Grid team,

this issue is still in version 21.1.0. Do you plan to fix it?

Thanks!
