### ISSUE TITLE
Popup editor for last row doesn't display correctly when using with material theme and domLayout

### ISSUE THREAD

**Issue by Teamop** [ag-grid/ag-grid#2850]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Here I just use the [demo](https://www.ag-grid.com/javascript-grid-themes/material-theme.php) from the material theme, then I just added the `[domLayout]="'autoHeight'"` and remove the `height: 100%`, then just jump to see the pop-up editor for the last row, the pop-up editor isn't displayed correctly, just a part of it.
![image](https://user-images.githubusercontent.com/8519685/50445389-6c8db680-0949-11e9-8a94-573b0d4cb414.png)

- A plunker (https://plnkr.co/edit/0pRCPmodXYzT6Bk6JCZE?p=preview)

**Current behavior**

The pop-up editor for the last row isn't displayed correctly.
**Expected behavior**

It can be displayed correctly.

**Please tell us about your environment:**

* **ag-Grid version:** 19.1.4

* **Browser:** Chrome 71

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2494 - Themes - Allow material theme to have some air at the bottom of the grid to allow for material editing in the last row

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
