### ISSUE TITLE
Detail always refresh with deltaRowDataMode

### ISSUE THREAD

**Issue by Ddiddinne** [ag-grid/ag-grid#2851]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**

I'm using the option deltaRowDataMode of ag-grid. My data is refreshed every seconde. When I extend a row to see the detail, the data of the detail is refreshed every second (going to the function "agInit") even if the row doesn't change.
It's since version 19.0.0

Here is a plunker: https://plnkr.co/edit/Lpah9QwNtFQv9It6LYcT?p=preview

**Current behavior**
The detail is always refreshed even if the data of the row doesn't change.

**Expected behavior**
I expected that the detail doesn't need to be recreated because the row doesn't change.

**Please tell us about your environment:**

* **ag-Grid version:** 19.1.4

* **Browser:** Chrome 71, Firefox 64

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2277 | Init method of full width rows gets called every time that the underlying data changes
-- | --
