### ISSUE TITLE
Special Characters are being converted into an HTML code in filter section of the side panel

### ISSUE THREAD

**Issue by ansarisufiyan777** [ag-grid/ag-grid#2857]
Hi,

**Current behavior**
On the right side filters panel Column header like **S&P**,  **Company's** are being converted into an HTML code **<&amp ;>** , <&#39 ;> respectively. 

**Expected behavior**
It would be great if these codes will be converted into an expected symbol

Minimal reproduction of the problem with instructions

I have attached the screenshot and **plunkr** of the bug, Is there anything I am missing from the dependency I am currently using **"devextreme": "^18.1.7"** in Angular 7.

[https://plnkr.co/edit/Ppiq8VtbbJ41Ntkg335Z?p=preview](url)

**Please tell us about your environment:**
Not needed

**ag-Grid-Enterprise version**: 18.1.7

![image](https://user-images.githubusercontent.com/16426709/50562845-c1607100-0d3d-11e9-8de5-0bcf19548823.png)

**Comment by ansarisufiyan777** [comment]
This might help the support team.

I dig down into the **ag-grid-enterprise** I found out the below lines in `/node_modules/ag-grid-enterprise/dist/lib/sideBar/providedPanels/filters/toolPanelFilterComp.js`

`
var displayName = this.columnController.getDisplayNameForColumn(this.params.column, 'header', false);
var displayNameSanitised = ag_grid_community_1._.escape(displayName);
this.eFilterName.innerText = displayNameSanitised; // This line is converting the special character into an HTML code.        
`

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2592 - Sidebar - Special Characters are being converted into an HTML code in filter section of the side panel 

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by joshuacalloway** [comment]
any update on this?  has this been fixed

**Comment by akramSahbi** [comment]
any update on this? has this been fixed

**Comment by jfaquinojr** [comment]
any update on this? has this been fixed

**Comment by kovalenkoiryna15** [comment]
any update on this?

**Comment by Paveltrof86** [comment]
Hello!
The same
v28.1.0

![2023-02-16_15h41_03](https://user-images.githubusercontent.com/19744837/219380842-c8e6286f-13fa-49cf-820f-4db3b187c501.jpg)

**Comment by StephenCooper** [comment]
@Paveltrof86 I assume these values are coming from the `localeText` property?

If so can you share those?

**Comment by Paveltrof86** [comment]
ok
So, we use simple .xls file for translations. Read from file and cache it.
![2023-02-16_19h16_54](https://user-images.githubusercontent.com/19744837/219439472-0de59d3d-b135-42ea-9584-a7d3eb054832.jpg)

And put it .js file in runtime
![2023-02-16_19h19_04](https://user-images.githubusercontent.com/19744837/219440077-0cadfcd1-2694-407a-a5ca-831823eb85a3.jpg)

After that put it in localeText.

As you can see, I`ve added only one line in .xls file with key 'Area'.
But, I have this when use Ag Grid.

![2023-02-16_19h22_19](https://user-images.githubusercontent.com/19744837/219440707-2ef2189a-0f9a-45c2-8644-a175fa0d52f4.jpg)

![2023-02-16_19h23_09](https://user-images.githubusercontent.com/19744837/219441255-aff5e27e-9815-4c25-b6a9-bb51078728ac.jpg)

**Comment by StephenCooper** [comment]
I am struggling to reproduce this. Can you update the following to show your error?
https://plnkr.co/edit/lHhTir2zvjrcfMAI?open=main.js

**Comment by Paveltrof86** [comment]
trying...but no result - works as expected (

Maybe it helps you/us.
Generated data:
![2023-02-16_19h56_45](https://user-images.githubusercontent.com/19744837/219449284-3af30433-46ff-4c3e-a438-927275c3731a.jpg)

![2023-02-16_19h56_56](https://user-images.githubusercontent.com/19744837/219449290-97ec59a8-a082-4a65-ba6c-0c9defbbc7f0.jpg)

![2023-02-16_19h58_20](https://user-images.githubusercontent.com/19744837/219449297-6f0d02f1-2bbe-4b3f-9f90-78e0637eab13.jpg)

**Comment by Paveltrof86** [comment]
Morning!
I`ve fixed Unicode issue from my side, but still have this:

![Uploading 2023-02-17_11h41_24.jpg…]()
![2023-02-17_11h41_34](https://user-images.githubusercontent.com/19744837/219609631-e4427441-0e70-4baa-8c63-0699dfb8fd23.jpg)

**Comment by Paveltrof86** [comment]
Sorry for not posting - I forgot.
Since in these places Ag Grid did not allow the browser to correctly display characters - I add this data as it should look in the final version without html code.

Thank you!
