### ISSUE TITLE
Warning 'grid zero width' when using ag-Grid's sizeColumnsToFit() on two separate ag-Grids, displayed by a tab menu

### ISSUE THREAD

**Issue by rune007** [ag-grid/ag-grid#2858]
My ag-grid issue is the same as other users have previously had, displayed in the issue below:

sizeColumnsToFit breaks if multiple ag-grids exist on different tabs [#1293](https://github.com/ag-grid/ag-grid/issues/1293)
That issue has been closed, but the issue was never satisfactory resolved.

When I use ag-Grid's sizeColumnsToFit() method on two separate ag-Grids, displayed by a tab menu, I get the warning below:

> ag-Grid: tried to call sizeColumnsToFit() but the grid is coming back with zero width, maybe the grid is not visible yet on the screen?

I have reproduced the situation in a Stackblitz:

[https://angular-jpmxjy.stackblitz.io/](https://angular-jpmxjy.stackblitz.io/)

Here is the composition of the test app:
- PrimeNG p-tabMenu at the component: header.component
- ag-Grid at the components: delleverancer.component and leverancer.component.

You will see the warning error in chrome dev tools, when you resize the grid and switch between tabMenu 'Leverancer' and 'Delleverancer'.

You can see the code here:

[https://stackblitz.com/edit/angular-jpmxjy](https://stackblitz.com/edit/angular-jpmxjy)

How do I remove this unwanted warning error?

![grid-zero-width-original](https://user-images.githubusercontent.com/5253939/50724982-e61a6700-10f6-11e9-97fa-3b5faec71626.png)

**Comment by rune007** [comment]
I have come across a solution to above problem:
[https://stackoverflow.com/questions/54038024/warning-grid-zero-width-when-using-ag-grids-sizecolumnstofit-on-two-separat ](https://stackoverflow.com/questions/54038024/warning-grid-zero-width-when-using-ag-grids-sizecolumnstofit-on-two-separat )

**Comment by 1shkelzeni** [comment]
Hey how did you solve this, I have the same issues, 
I have grid inside tabs and I am getting this warning

**Comment by NguyenKyThinh94** [comment]
I use React  and have same isuess. If one tab have content and one tag have nothing. When we change betwen tabs, My app can be stoped work, and show erorrs.
