### ISSUE TITLE
columpApi.setColumnState(...) doesn't work properly with alignedGrids (e.g. visibility is broken)

### ISSUE THREAD

**Issue by MaKCbIMKo** [ag-grid/ag-grid#2862]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I have 2+ 'aligned' grids.
If I'm calling `setColumnState` method for one grid (e.g. I would like to hide/show some columns) - these changes aren't properly propagated to all other 'aligned' grids.
Seems like it can only hide columns from the aligned grids, but now show them. (IMHO, the problem is that `setColumnState` raises visibility change event with wrong parameters in `raiseColumnVisibleEvent`)
[See plunker](https://plnkr.co/edit/06IxOjAqGpUpBKSQ36ak?p=preview)

**Expected behavior**

When I'm calling `setColumnState` method on one grid - changes should be properly propagated to all other tables or if I call `setColumnState` on all grid at once - it should handle such case as well.

**Please tell us about your environment:**
Windows 10, VS Code, Angular, Angular-cli, Typescript version 3.2.2

* **ag-Grid version:** X.X.X
"ag-grid-community": "^19.0.0"

* **Browser:** N/A

* **Language:** TypeScript  3.2.2

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
