### ISSUE TITLE
Disable HTML sanitising in headers

### ISSUE THREAD

**Issue by yesdevnull** [ag-grid/ag-grid#2866]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use GitHub for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

### Current behavior
[AG-2071](https://github.com/ag-grid/ag-grid/commit/3293b322a08e18a0fca148941a6b5610fe6a41df) introduced sanitising of HTML in headers.  There appears to be no way to customise or disable this functionality.

**Example:** in our application one of the column headers in an ag-Grid table is `∑` which in the source code is `&sum;`.  Prior to ag-Grid 19.1.1 `∑` would appear in the column header but now `&sum;` shows up instead.  Using the [Font Awesome icons](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use) (like `<span class="fas fa-grid"></span>` ) in headers too now displays the HTML verbatim rather than showing the icon.

Our current workaround is to lock ag-Grid to `19.0.0`.

[Plunker example](https://next.plnkr.co/edit/TP058xKNz7lw96BH?preview)

### Expected behavior
Ideally have an option to disable this on a per-column basis in `columnDefs` or across the board in `defaultColDef`.

**Please tell us about your environment:**
* **ag-Grid version:** 19.1.1 onwards
* **Browser:** all
* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
