### ISSUE TITLE
Layout with 0 rows and domLayout autoHeight is broken

### ISSUE THREAD

**Issue by MinhThienDX** [ag-grid/ag-grid#2868]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1. Go to https://www.ag-grid.com/javascript-grid-width-and-height/#auto-height
2. Scroll to second example
3. Click button "0 Rows"

**Current behavior**
The text "No Rows To Show" is overlapped with the header row.
The grid has no body, just 2 headers and 1 horizontal scrollbar.

**Expected behavior**
The grid have 2 headers, 1 body and 1 horizontal scrollbar.
"No Rows To Show" should appear in the middle of the gird's body.

**Please tell us about your environment:**
Not needed since it is reproducible in your example.

* **ag-Grid version:** 20.0.0
However this bug is also reproducible in version 19.1.4

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

* **Language:** [ES6/7]

**Comment by gportela85** [comment]
Thanks for reporting, issue has been fixed by https://github.com/ag-grid/ag-grid/commit/10390c9964fcb3864f5960cb89d26726ce0dc695

**Comment by MinhThienDX** [comment]
@gportela85 May I ask when will the fix go live?
