### ISSUE TITLE
Material theme is missing the column resizer: Fix for AG-2420 has been removed by fix for AG-2235

### ISSUE THREAD

**Issue by benoitbzl** [ag-grid/ag-grid#2871]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Example page where the bug manifests: https://www.ag-grid.com/example.php#/

**Current behavior**
Open the example page linked above and select the Material theme. The column resizer is not visible (e.g.: the small vertical line). Although hovering over it with the mouse changes the cursor and allows for column resizing. The Ag-Grid 20.0 version change log indicates that it should be fixed, but the commit was removed.

**Expected behavior**
The column resizer should be visible for the material theme. This used to work in version 18. A fix for this issue (as tracked as AG-2420) has been committed last december, but the fix was removed some days after by the commit for AG-2235.

**Please tell us about your environment:**
Windows 10, Angular 6.x with CLI, Chrome 71.0.3578.98 

* **ag-Grid version:** 20.0.0

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular 6.x

**Comment by gportela85** [comment]
That is correct, the column resizer was added and then removed to follow this guideline: https://material.io/design/components/data-tables.html#behavior
The only division present is between pinned columns and not pinned columns.

To help with the resizing, when you hover a header cell, it will be highlighted to make it easier to find the edges.
