### ISSUE TITLE
Column order broken if columns are re-used (v19 regression)

### ISSUE THREAD

**Issue by DominicTobias** [ag-grid/ag-grid#2874]
Hi,

This used to work fine. Now if we compose columns of reusable objects and then change the order on the fly, the order is broken (jumbled up and not according to the order in the array).

The only way to fix it is to call a function which spreads the column defs to new objects:

```js
() => ([
  { ...strike },
  { ...size },
  { ...exerciseStyle },
  { ...optionType },
  { ...expiryDate },
])
```

For columns with `children` we have to do a deep merge or it's still broken:

```js
() => ([
  merge({}, groupColumnWithChildren),
])
```

My guess is that you're holding the column order in internal state according to the object reference, which sounds crazy but it's the only thing I can think of! Thanks.

**Comment by DominicTobias** [comment]
Here's the order in code (note ISIN and AMC Currency are the FIRST and SECOND items in the column):

![bad-order-code](https://user-images.githubusercontent.com/760314/51324621-210b8b80-1a63-11e9-96da-4e7242a89e24.jpg)

Now look how they appear when rendered. Exactly the same code was working in v18:

![bad-order](https://user-images.githubusercontent.com/760314/51324663-3385c500-1a63-11e9-9380-59add4c5bb38.jpg)

**Comment by makinggoodsoftware** [comment]
Hi guys,

Coming 20.1 you will be able to pass column definitions as you would in a react app normally, just by passing new columns we will calculate the deltas

This will be done on the back of this item


AG-2289 | Delta Columns - Allow for delta columns based on the state provided by a store
-- | --



Keep an eye in our pipeline
https://www.ag-grid.com/ag-grid-pipeline/
