### ISSUE TITLE
Ag-grid crashes in IE 11 when using core-js

### ISSUE THREAD

**Issue by mjhoffm2** [ag-grid/ag-grid#2876]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I created a fairly minimal repo which reproduces this issue: https://github.com/mjhoffm2/ag-grid-error-demo

Currently, you will see that this demo works fine in google chrome, but in IE 11 it will crash during the initial render (white screen).  This is the error that I see in IE 11:

![error 1](https://github.com/mjhoffm2/ag-grid-error-demo/raw/master/error1.png)

![error 2](https://github.com/mjhoffm2/ag-grid-error-demo/raw/master/error2.png)

This demo is using ag-grid version 20, but I also saw this issue when using ag-grid version 19.  The demo is also using ag-grid-react and ag-grid enterprise.

If you remove the `import "core-js"` line in `boot-client.tsx` in the demo and do a hard refresh in IE, then it will work fine.  I am aware that ag-grid does not actually require any polyfills from core-js, but I have other dependencies that do and I would like everything to be able to function side-by-side.  

* **Browser:** IE 11

* **Language:** [TypeScript 3.2]

**Comment by makinggoodsoftware** [comment]
Hi,

We are closing this ticket as this looks like a duplicate from a zendesk ticket, if that is not the case, please reply we will reopen it.

Thanks

**Comment by boydy12** [comment]
What was the resolution for this? Also having this issue, we require core.js for other dependencies.

**Comment by mjhoffm2** [comment]
@boydy12 Unfortunately the resolution was that ag-grid is not compatible with core-js and I needed to polyfill the things I needed individually.  The Ag-Grid team insisted that the incompatibility lied with React and not with ag-grid, but it is pretty obvious that is not the case.

**Comment by boydy12** [comment]
I found that if I loaded core.js before ag-grid-community the this issue didn’t occur. The other way round I get this issue.
