### ISSUE TITLE
How do I set up a custom column menu panels?

### ISSUE THREAD

**Issue by caitao-ct** [ag-grid/ag-grid#2878]
I need to customize the column menu panel,
I used version 17.1.1, According to the documentation, I can only set 
```
menuTabs: ['generalMenuTab', 'filterMenuTab','columnsMenuTab']
```
So, How do I set up a custom column menu panels? thank you

* **ag-Grid version:** 17.1.1 Enterprise

* **Browser:** Chrome

* **Language:** [all]

**Comment by SonyStone** [comment]
Did you find how to customize the column menu panel in ag-Grid Enterprise version?
