### ISSUE TITLE
Drag and Drop - payload bug

### ISSUE THREAD

**Issue by EgoziTrax** [ag-grid/ag-grid#2887]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Drag and Drop - payload bug**
When drag payload is too long, no payload is shown at all.
This is the plnkr:
https://next.plnkr.co/edit/2bLMsr2VgPAjLpGf
Just drag any row with "athelete" named "DRAG ME!"

**Current behavior**
When you drag a row with a really long content, the dragged payload does not show at all.

**Expected behavior**
I'd expect to see a shortened version of the row followed by ellipsis while dragging.

**Please tell us about your environment:**
Linux mint

* **ag-Grid version:**
20.0.0

* **Browser:**
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
his is in our backlog now and we are tracking it with the following reference and description.

AG-2585 - When label for column with drag holder is too long, the ghost row shown for drawing has no label

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by kiril-matev** [comment]
Hi @EgoziTrax,

I was reviewing this item and found that it's been fixed by changes we made to AG Grid.

Please see this working as expected in the latest version:
1. Open
https://plnkr.co/edit/YCvy5zSJ1RavFswD?open=main.js
2. Click the drag handle in the top row and drag it down
**Actual & Expected**: Dragged row value is displayed normally in the ghost popup

We will close AG-2585 which was originally submitted about this.
