### ISSUE TITLE
Column IDs incorrect after dynamic columnDefs update (v19 regression)

### ISSUE THREAD

**Issue by DominicTobias** [ag-grid/ag-grid#2889]
Using latest of all packages (19.1.x), dynamic column defs are really broken compared to v18. I believe this is related to the order also breaking - https://github.com/ag-grid/ag-grid/issues/2874

If we have two sets of defs which share some columns like this:

```js
const simpleGrid = [
  status,
  columnDefs.causeAction,
  isin,
  ...
];

const richGrid = [
  status,
  isin,
  ...
];

export default function gridConfig(isRichView) {
  return isRichView ? richGrid : simpleGrid;
}

<AgGridReact
  columnDefs={gridConfig(hasRichGridConfig)}
  ...
/>
```

If we toggle these defs
(a) Sometimes the order completely breaks unless we deep copy to new refs (see #2874)
(b) `col-id` becomes incorrect due to appending `_1` and breaks QA tests. Seems like AG is keeping the previous column internally and considers this a copy...?

![duplicate-columns](https://user-images.githubusercontent.com/760314/51324152-dd645200-1a61-11e9-9921-d491dfc50568.jpg)
![duplicate-columns-2](https://user-images.githubusercontent.com/760314/51324153-dd645200-1a61-11e9-980c-e88052d8c708.jpg)

**Comment by DominicTobias** [comment]
This is definitely related to the other issue, the only way I can fix it is to make new references to the columns. Seems like a major regression in AG I would suggest writing some tests which tests for `col-id` and ordering when dynamically changing column defs:

```js
const copyDefs = defs => defs.map(def => {
  if (def.children) {
    return merge({}, def); // deep merge
  }

  return { ...def };
});
```

```js
export default function gridConfig(isRichView) {
  return isRichView ? copyDefs(richGrid) : copyDefs(simpleGrid);
}
```

**Comment by saif003** [comment]
@DominicTobias I opened a similar issue #2846 , turns out this started appearing from 19.1.1 or 19.1.2, I believe at the time when I did some digging around this I found that this started appearing after AG-1591.
basically Providing a new column with the same name but different ref as of before makes the grid think this is a new column and tries to generate a new unique incremented colId for the column.

this is the response I got,

> We are aware of this issue and have a feature request in our backlog

AG-2289 | Delta Columns - Investigate if it we should consider setColumnDefs as the golden source for delta columns. | BACKLOG |   |   | More Info
  | AG-1559 | Allow delta updates to column definitions, this should include all CRUD operations | BACKLOG

AG-2289 appears to be part of next release and I'm unable to track AG-1559 neither in the pipeline nor in the change log.

**Comment by DominicTobias** [comment]
Thanks for the info @saif003 glad it’s not just me or something weird I did!

**Comment by makinggoodsoftware** [comment]
Hi guys,

Coming 20.1 you will be able to pass column definitions as you would in a react app normally, just by passing new columns we will calculate the deltas

This will be done on the back of this item

AG-2289	Delta Columns - Allow for delta columns based on the state provided by a store

Keep an eye in our pipeline
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by Manbearpixel** [comment]
I am currently encountering this issue. Using React + AG-Grid (v20.0.0). We're connecting it for server side rendering and when the url changes we force it (via Datasource) to fetch new rows by triggering a filter change. During this time it appends `_1` to the columns. This breaks the grid view as we've also incorporated persistent column settings via localstorage, so the column defs are refreshed from a stored setting.

**Comment by DominicTobias** [comment]
You either need to fix to v19.0.0 or upgrade to 20.1.0 and above

**Comment by sevensilvers** [comment]
20.2.0 this still happens when you first have certain columns

What Happen:
First:
setColumnDefs [id="columnAge"] 

after some while you added dynamically a column id = "columnBirthDate"

Second:
setColumnDefs [id="columnBirthDate", id="columnAge_1"]

**Comment by DominicTobias** [comment]
Edit: I've upgraded to the latest 20.2.0 and amazingly the bug is still not fixed - order becomes broken when changing columnDefs if the defs are shared (i.e. reference doesn't change). I've had to do a deep merge when switching definitions with lodash `merge([], defs)`. Now I have to go through 60 grids and see where else this is breaking or revert back to 19.0.0. So annoying!

**Comment by martincarles** [comment]
Having the same issue with v20.1.0 & Vue, '_1' being added to columnIDs which is really annoying.

**Comment by DominicTobias** [comment]
This bug is still present in v21.0.1. I'm amazed more people aren't reporting it, I guess people aren't dynamically changing columns much. We have come across it in multiple apps.

**Comment by leoclc** [comment]
I have the same problem on an angular app using the grid's version 21.0.1. I am saving the state of the columns and when I call "gridOptions.columnApi.getColumnState()" it gives me columns with "_1" appended to the colId which I am using as a reference

**Comment by DominicTobias** [comment]
It's also a bummer for exporting certain columns to CSV/XLS as they get `_1` appended to them so we need to export those too incase AG messes them up

**Comment by Earthwormzim** [comment]
I was also having the same problem. I solved it by adding "colId" to the column definition.
i.e.:
`{ headerName: 'My Awesome Column', field: 'myColumnId', colId: 'myColumnId' }`

**Comment by Manbearpixel** [comment]
@Earthwormzim That can work in some instances! Glad it solved your problem

**Comment by michaelchiowong** [comment]
Hi, AG Grid Team,

I am using the latest AG Grid, and figure out this issue is still in the latest version 21.1.0. When I set a new columnDefs with same field id, the field id is appended with _1. 

This affects our filtering and sorting functions. 

So, this bug is not closed. Please give us hint on how to deal with it.

Thanks!

**Comment by sahilvicesoftware** [comment]
Hi, AG Grid Team,

I am also facing the same issue mentioned by @michaelchiowong

**Comment by leoclc** [comment]
> Hi, AG Grid Team,
> 
> I am using the latest AG Grid, and figure out this issue is still in the latest version 21.1.0. When I set a new columnDefs with same field id, the field id is appended with _1.
> 
> This affects our filtering and sorting functions.
> 
> So, this bug is not closed. Please give us hint on how to deal with it.
> 
> Thanks!

This has been here for very long... I handled it by replacing the "_1" every time I send column defs or filters to the backend.

**Comment by jameswyse** [comment]
@leoclc I’ve had to do the same thing.

**Comment by LittleBreak** [comment]
Having the same issue with v19.1.4 & react

**Comment by LittleBreak** [comment]
the issue still exist in v21.2.1 & react

**Comment by BobrImperator** [comment]
> Hi, AG Grid Team,
> 
> I am using the latest AG Grid, and figure out this issue is still in the latest version 21.1.0. When I set a new columnDefs with same field id, the field id is appended with _1.
> 
> This affects our filtering and sorting functions.
> 
> So, this bug is not closed. Please give us hint on how to deal with it.
> 
> Thanks!

I personally handle this by resetting columnDefs completely, before I apply dynamically loaded colDefs, I clear the definitions first by giving empty array to `setColumnDefs`.
I do that only if list reference is different than the old one, which is saved under `gridOptions.columnApi.colDefs` key.

**Comment by JabbyPanda** [comment]
I think `ag-grid` can do better about signalling that supplicated column definition object is missing `colId` value

I can see the following means that can be undertaken to improve the current state of the things:

1.   `colId` field in Typescript `ColDef` type definition file shall be marked as mandatory, not as [optional](https://github.com/ag-grid/ag-grid/blob/master/dist/lib/entities/colDef.d.ts#L71)

![image](https://user-images.githubusercontent.com/255913/67202093-250c7580-f408-11e9-9f78-248f166d095f.png)

2. ag-grid could issue a warning in the browser console using `console.warn` level when one of the following column operation ( column resize, reorder, sort, filter, pinning, aggregation) occurs, but column definition does not have unique `colId` provided.

3. ag-grid shall be capable to use `field` data as fallback if no `colId` value is defined at `ColDef`, if `colId` will remain optional in `ColDef` object definition.

**Comment by smile2014** [comment]
this.gridApi.setColumnDefs([]);
this.gridApi.setColumnDefs(this.columnDefs);

**Comment by Vishwas-93** [comment]
> @BobrImperator apart from performance hit this will also clear any column resize, reorder, sort, filter, pinning, aggregation, row group or pivots applied by the user. and frankly that won't translate into a great user experience.
> 
> Also Ag-grid's documentation for [column definition](https://www.ag-grid.com/javascript-grid-column-definitions/) states,
> 
> > If you are updating the columns (not replacing the entire set) then you must either provide column ID's or reuse the column definition object instances. Otherwise the grid will not know that the columns are in fact the same columns.
> 
> The right fix here as mentioned in the docs is to assign unqiue `colId` to columns, I have verified in the latest version; providing distinct `colId` when passing columns to `setColumnDefs` method, fixes this. I guess they could have highlighted this more.

Well done. This solution is the best one and prescribed by AG Grid. But unfortunately, doesn't help some cases. 
Like, 
1. If the colId is being referenced by the application somewhere and cannot be changed. 
In my case, I am using columnState (for ordering, width, etc.) and columnDefs (for HeaderNames, groups etc.)

Solution that worked, 

gridApi.setColumnDefs([])
gridApi.setColumnDefs(newColumnDefs/updateColumnDefs)

You can prove this to yourself by just 
"gridApi.setColumnDefs(newColumnDefs/updateColumnDefs)"
console.log(columnApi.getColumnState()) -> Returns colIds with _1 appended a

"gridApi.setColumnDefs([])
gridApi.setColumnDefs(newColumnDefs/updateColumnDefs)" and then 
"console.log(columnApi.getColumnState())" to see the difference

Also, sometimes (I do it all the time) we may have to repaint the grid if trying to add new columns dynamically.
If using alignedGrids, we probably need to refresh the gridOptions using the updated Column Definitions as well.

**Comment by ahmdsamir91** [comment]
yes colId fixed the _1 issue but the grid the group by breaks if you added rowGroup with colId to col definition.

**Comment by flashnoob** [comment]
> this.gridApi.setColumnDefs([]);
> this.gridApi.setColumnDefs(this.columnDefs);

bruh this worked for me in ag-grid angular 21.1.0. 
thanks

**Comment by davidsayyescactus** [comment]
> this.gridApi.setColumnDefs([]); this.gridApi.setColumnDefs(this.columnDefs);

This works for me. Thank youuu!!!!!!!

**Comment by evgeniyefimov** [comment]
The issue is still there (ag-grid-angular 28.2.0). @smile2014 solution helped to fix it.
