### ISSUE TITLE
Number format for Excel export is exported with backslash

### ISSUE THREAD

**Issue by lorenzulrich** [ag-grid/ag-grid#2890]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Scenario**
I have a grid with a configured Excel export having currency columns

I'm using the `excelStyles` options to provide a `numberFormat` for Swiss currency as defined in Excel:

```
excelStyles: [
{
  id: "currencyField",
  numberFormat: {
	format: "Fr. #'##0.00;Fr. -#'##0.00"
  }
}
]
```

The style is applied using `cellClass`:

```
cellClass: 'currencyField',
```

**Current behaviour**

In general, the Excel export works and the style is applied. However, it gets "escaped" with backslashes, meaning the `r`s and single quotes have a leading backslash. This leads to a broken output of currency fields:

![image](https://user-images.githubusercontent.com/1816023/51330859-af3e3c80-1a78-11e9-923b-0a912de5e232.png)

**Expected behaviour**

The correct behaviour would be to export the `numberFormat` exactly as configured, leading to the proper display of currencies:

![image](https://user-images.githubusercontent.com/1816023/51330930-dac12700-1a78-11e9-9339-f8dea03a5f81.png)

**ag-Grid version:** 19.1.4

**Browser:** any

**Comment by gportela85** [comment]
Can you try
```
excelStyles: [{
    id: "currencyField",
    numberFormat: {
        format: "[$Fr.] #,##0.00"
    }
}]

**Comment by lorenzulrich** [comment]
This makes `Fr.` work, very good and thank you very much!

Is there also a solution to make the thousands separator (in my case a single quote `'`) optional? Currently, in the same configuration as mentioned above, the thousands separator is always displayed - even if the amount is smaller than 1000. 

Examples:

* `Fr. '0.00`
* `Fr. '96.05`
* `Fr. '672.00`

Is it correct though for amounts > 1000:

* `Fr. 67'254.00`
* `Fr. 2'283.90`

**Comment by lorenzulrich** [comment]
Indeed :wink:. Thanks a lot!
