### ISSUE TITLE
Server-side row model fail to render row if there is no data

### ISSUE THREAD

**Issue by fenixil** [ag-grid/ag-grid#2891]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
We use **cellClass** function in columnDef and **Server-side Row Model**. 
If **successCallback** is called with no results Ag-Grid reports an error:
https://plnkr.co/edit/FDlazAW110AU7cwbjfd4?p=preview

<img width="1436" alt="screen shot 2019-01-17 at 3 48 35 pm" src="https://user-images.githubusercontent.com/10786072/51349222-b9f5d300-1a72-11e9-8e7f-e6335e55685b.png">

**Current behavior**
cellClass and other callbacks/frameworkComponents in colDef are invoked as if some row is being rendered.

**Expected behavior**
no callbacks are invoked if there is no data to render

* **ag-Grid version:** 20.0.0, 19.X.X
* **Browser:** 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

* **Language:** [ES6]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Upon further investigation, we have realised this is not a bug... Note this:

When the SSRM invokes getRows() it's in a 'loading' state. While in this this state the grid introduces a temporary row node which shows 'loading'.

When params.successCallback([], 0) is invoked this node is removed.

So it's during this intermediate state that the cellClass callback is invoked on the temporary row node. If this is an issue add some defensive programming like so:
cellClass : function(params) {
 return params.data ? params.data.value : '';
}
https://plnkr.co/edit/tcN5K9Oyty35ZUJpyzT5?p=preview


Hope this helps

**Comment by lwouis** [comment]
Thanks @makinggoodsoftware! I think your latest comment is really valuable information that is missing in the docs currently. Generally the behavior of the grid when there are 0 row coming back from the server-side is not documented at all, as far as my research showed.

I would suggest you add a paragraph of text to [this section here](https://www.ag-grid.com/javascript-grid-server-side-model-datasource/) to explain that scenario 👍
