### ISSUE TITLE
suppressHorizontalScroll not used in docs, not working

### ISSUE THREAD

**Issue by zivich** [ag-grid/ag-grid#2896]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

1. The [Footer example in the alignedGrids doc](https://www.ag-grid.com/javascript-grid-aligned-grids/#aligned-grid-as-footer) claims to use the 'suppressHorizontalScroll' option on the top table, but does not. 

2. When the 'suppressHorizontalScroll' option is used on line 30 of [this forked example](https://next.plnkr.co/edit/2wsAWQlXWgiw4BWe), and the viewport is sufficiently narrow, the horizontal scrollbar can still be seen when you scroll to the bottom of the top table. 

**Expected behavior**

1. The [Footer example in the alignedGrids doc](https://www.ag-grid.com/javascript-grid-aligned-grids/#aligned-grid-as-footer) should include the 'suppressHorizontalScroll: true' option. 

2. The 'suppressHorizontalScroll: true' option should hide/remove the horizontal scrollbar at the bottom of the top table.

**Please tell us about your environment:**
- MacOX Mojave Version 10.14.2 | Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Fedora Linux 26 | Chrome 71

**ag-Grid version:** 20.0.0

**Browser:**
- "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
- "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36"

**Comment by zivich** [comment]
Oh, sorry! I forgot to mention that I was looking at the React version of that example. It does not include the `suppressHorizontalScroll` option. 

It seems you were able to recreate the 2nd part of this issue, is it intended functionality for the horizontal scrollbar to render at the bottom of the top table, as shown in your screenshot?

In my browser, the scrollbar appears to cover most of the last row in the top table.

![screen shot 2019-01-18 at 4 32 18 pm](https://user-images.githubusercontent.com/24485612/51413966-a9129380-1b3e-11e9-96d7-ec08a25c47b8.png)

**Comment by gportela85** [comment]
Yes, having the scrollbar at the bottom is the intended target, so only one grid has the scrollbar and the other "aligned grid" follows.

But thanks for reporting the issue with the frameworks examples.

**Comment by zivich** [comment]
There are currently 2 horizontal scrollbars showing (one anchored to the bottom of the aligned tables, another at the bottom of the vertical scroll of the 'top body' table. 

Shouldn't there only be a single horizontal scrollbar at the bottom of the aligned tables which controls the scroll of both aligned tables?

**Comment by gportela85** [comment]
Yes, only one scrollbar should be displayed and this is what happens with the `Javascript` example. The code is not working on Framework (Angular / React) examples at the moment but will be fixed.

**Comment by MylesGearon** [comment]
I'm able to get two scrollbars showing when using the Javascript example as well. The second scrollbar only appears when the top table is scrolled all the way to the bottom. It's covering the bottom row of the table too.

![ag-grid-2-scrollbars](https://user-images.githubusercontent.com/8154900/51490517-86b88a00-1d79-11e9-97df-bf31813a710e.png)

**Comment by gportela85** [comment]
@MylesGearon Thanks. Will add to the list of related issues

**Comment by gportela85** [comment]
Fixed the examples with all frameworks and the problem with the scrollbar showing up when you scroll al the way to the bottom. Will be included in the next release.

**Comment by dima716** [comment]
Still able to replicate this issue using the example on ag-grid docs [page](https://www.ag-grid.com/javascript-grid-aligned-grids/)

<img width="1337" alt="Screen Shot 2019-04-12 at 2 09 52 AM" src="https://user-images.githubusercontent.com/8137279/55998726-26761c00-5cc8-11e9-8da2-c869759d11d8.png">

**Comment by gportela85** [comment]
@dima716 This happens only on MacOS when the system settings are set to show scroll only when scrolling.
That's because MacOS adds a fake scroller that doesn't technically exist in the DOM structure. The only way to prevent this from happening would to the same thing that was done in version 18.0.0 (see: https://www.ag-grid.com/archive/18.0.0/javascript-grid-aligned-grids/) that is to set the overflow-x to hidden. The side effect of doing that is not being able to scroll the top grid horizontally with a trackpad.

**Comment by olu1987** [comment]
My workaround for this issue on mac was to use a minus margin on the top of the parent element of the footer grid so that it overlaps the upper scrollbar. Not ideal but it worked good enough in my case
