### ISSUE TITLE
rowDragEnd does not fire outside of ag-grid

### ISSUE THREAD

**Issue by Paul6552** [ag-grid/ag-grid#2902]
**I'm submitting a ..
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

**Providing a Reproducible Scenario**
https://plnkr.co/edit/OZvLMk3aDXy8jPC2Lw9F?p=preview

**Current behavior**
Take the plunker above, open the console.
If you move one row and you release the button you will get the message "rowDragEnd".
If you take a row and you move the mouse outside of the main body of ag-grid (do NOT release the mouse button) you get the message "rowDragLeave". If you release now the mouse button OUTSIDE of the main body of ag-grid you don`t get the message "rowDragEnd". The event does not fire outside of the ag-grid main body.

**Expected behavior**
I would expect that the event "rowDragEnd" does also fire outside of the main body of ag-grid, because with the message "rowDragLeave" you do not get the message if the user released the mouse button or not. "RowDragEnd has to fire inside and outside of ag-grid.

I have already found this issue ticket:
https://github.com/ag-grid/ag-grid/issues/2571
But I am not requesting a feature-request. I think this is a wrong behaviour of ag-grid

OS: Windows 10
NPM 6.6.0

* **ag-Grid version:**20.0.0
* **Browser:**
Chrome version 71

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-1708 | Row dragging: Allow dragging between grids or between the grid and a external element
-- | --

**Comment by Paul6552** [comment]
I have seen that this ticket AG-1708 shoud be fixed in version 21.1.0.

Maybe it is working but not with react.

The function `onRowDragEnd` is not fired outside of ag-grid.

    "ag-grid-community": "^22.0.0",
    "ag-grid-react": "^22.0.0",

![dragAndDrop](https://user-images.githubusercontent.com/25934591/69539499-e88ee500-0f84-11ea-8ea9-fc66023a7623.gif)

**Comment by makis-x** [comment]
This is still broken in enterprise?! 2022. Need to reach out to support I guess

**Comment by StephenCooper** [comment]
Hi @makis-x,

Feel free to reach out to support with your use case but please be aware that this event is for when dragging finishes over the grid, as stated in our [docs](https://build.ag-grid.com/javascript-data-grid/row-dragging/#row-drag-events). So we would not consider this to be broken.

> There are four grid events associated with row dragging which are:
> **rowDragEnter**: A drag has started, or dragging already started and the mouse has re-entered the grid having previously left the grid.
> **rowDragMove**: The mouse has moved while dragging.
> **rowDragLeave**: The mouse has left the grid while dragging.
> **rowDragEnd**: The drag has finished over the grid.

**Comment by makis-x** [comment]
@StephenCooper Thanks for the reply! The problem ("broken?") is that rows get rearranged by the grid with no way of knowing what's happened or that the user has decided to stop dragging as there is no "end" event.

This is a pretty basic use case just looking for some ideas how others deal with this.

Cheers!

**Comment by StephenCooper** [comment]
You might want to take a look at this approach which combines row dragging with the grid generic drag event. Might be a good starting point for you.

https://plnkr.co/edit/HhaAZ6PvC0ar6bij

**Comment by Paul6552** [comment]
> This is a pretty basic use case just looking for some ideas how others deal with this.

Use react-table from tanstack. That is the solution

**Comment by makis-x** [comment]
Thanks all so moral of the story is its not that straight forward. I would think a rows changed event, filter rows needed and get the row index might be easier... oh mama what one even will do
