### ISSUE TITLE
Ag-grid printing feature not working in IE11

### ISSUE THREAD

**Issue by EagleShare** [ag-grid/ag-grid#2903]
I'm trying to implement ag grid print feature for Internet explorer 11 which doesn't seem to be working. Changing of domlayout to autoHeight and print doesn't work for IE

https://www.ag-grid.com/javascript-grid-for-print/

Even the sample they provided is not working in IE 11. When printed in chrome it is printing all the page without any problem.In IE 11 it prints the first page alone.i.e, it makes the grid to a fixed height and shows as a scrollable. Could anyone help me with this regard?

**Comment by gportela85** [comment]
Thanks for reporting, fixed by https://github.com/ag-grid/ag-grid/commit/72944c3aea3e683b7d899c558dce1284ee6a01da

**Comment by EagleShare** [comment]
The version I'm using is stated below. 
"ag-grid": "^18.1.2",
"ag-grid-react": "^17.1.0",

The change u suggested doesn't seem to be available in the following style sheet
import "ag-grid/dist/styles/ag-grid.css";
import "ag-grid/dist/styles/ag-theme-material.css";

Also, setDomLayout is invalid in my ag grid component so I'm using
api.setGridAutoHeight(true);

The above property set the grid as autoHeight. This works for me in IE also. While loading it  sets autoHeight but while printing it automatically reduces the height to a fixed value as shown in the attached image

![image](https://user-images.githubusercontent.com/36268143/51610753-84a22700-1f43-11e9-9ff0-68ea0d241309.png)

Could you please help me on this regard?
