### ISSUE TITLE
Inline editing not supported when using deltaRowDataMode

### ISSUE THREAD

**Issue by frankwallis** [ag-grid/ag-grid#2904]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
When using `deltaRowDataMode` and inline editing, ag-grid should not mutate the row data items, they should be treated as immutable objects.

Currently ag-grid attempts to mutate the objects (in `ValueService.setValue` method). If the object is frozen this will throw an error and the mutation will fail

Reproduced example: https://plnkr.co/edit/taJrHvxN4fOfKQZY52H5?p=preview
(try updating the 'Price' column)

**Expected behavior**
ag-grid should not mutate the objects in place, instead it should raise events to notify the caller that an update has occurred. (in react parlance the editors should be 'uncontrolled' components)

**Please tell us about your environment:**
* Windows, VSCode, NPM, React, webpack-dev-server

* **ag-Grid version:** X.X.X
20.0.0

* **Browser:**
Chrome
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by andresinostroza** [comment]
Hey @frankwallis, I know is a bit late but I have solved this issue passing the context to the child and then in the chid you will be able to get the value as `this.params.node.data.yourColField`
