### ISSUE TITLE
domLayout='autoHeight' does not add min-height to body 

### ISSUE THREAD

**Issue by twkatadin** [ag-grid/ag-grid#2909]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

As described in the documentation for the grid height setting domLayout='autoHeight' is supposed to set a min-height of 50px on the grid body so that the "No Rows" overlay is not displayed on top of the header row when there is no data.

Currently that is not happening, as can be seen on the example for the autoheight property on the documentation page: https://www.ag-grid.com/javascript-grid-width-and-height/

ag-grid v20.0.0
Language: ES5
Windows 10, Ruby, Tomcat, downloaded package, plain javascript
Chrome, Firefox

domLayout='autoHeight'
Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Comment by gportela85** [comment]
This issue has been fixed already, will be available in the next release.

**Comment by twkatadin** [comment]
Thanks, I didn't see it listed in any of the bugs here or on the ag-grid pipeline page.

**Comment by gportela85** [comment]
@twkatadin it was fixed by AG-2519, it will show up in the pipeline soon
