### ISSUE TITLE
 grid is scrolled up automatically on selecting pinned top row

### ISSUE THREAD

**Issue by shirosaki** [ag-grid/ag-grid#2915]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- https://plnkr.co/edit/Llw6bajYjK20ibRdcDUD?p=preview

Scroll down the grid rows manually at first.

**Current behavior**

While I select cells in pinned top row, the grid is scrolled up automatically.

**Expected behavior**

While I select cells in pinned top row, the grid is not scrolled.

* **ag-Grid version:** X.X.X
20.0.0

* **Browser:**
Firefox ESR 60.4.0

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2636 - Pinned row - Grid scrolls up when range selecting the pinned top cells

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
