### ISSUE TITLE
autoHeight does not work in IE11

### ISSUE THREAD

**Issue by gforceg** [ag-grid/ag-grid#2917]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I recently switched from ag-grid to ag-grid-community and now the autoHeight feature is not working in IE11.

Steps:
1. Navigate to to https://www.ag-grid.com/javascript-grid-width-and-height/#autoHeight in IE11.
2. Toggle between normal height and autoheight

**Current behavior**
The grid body has a height of 0px when domLayout='autoHeight'.
![enable-continuous-deployment](https://user-images.githubusercontent.com/14267747/51864408-ef1ae480-2300-11e9-88a2-86fcae4d585c.gif)

**Expected behavior**
The height of the grid should fit the number of rows and there should be no vertical scrolling.

**Please tell us about your environment:**
Operations System: Windows 10
IDE: VS Code
Package Manager: npm
HTTP Server: IIS

* **ag-Grid version:** ag-grid-community@20.0.0

* **Browser:**
IE11 version 11.2724.14393.0

* **Language:** babel ES6 => ES5

**Comment by gportela85** [comment]
issue has been fixed and will be patched in the next release

**Comment by gforceg** [comment]
Great! Which commit is it? I'd like to patch my app.
Thanks.

**Comment by gforceg** [comment]
nevermind I think I found it.
https://github.com/ag-grid/ag-grid/commit/6bd222946c0d26a7a42a40f38bf4dff94bb3b30d
thanks
