### ISSUE TITLE
Tab keyboard navigation is not working using android devices

### ISSUE THREAD

**Issue by HyperComplex** [ag-grid/ag-grid#2918]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```
**Requesting Community Support**

**Providing a Reproducible Scenario**
- Visit ag-grid website from any android device.
- Go to the demo page or any page that contains a grid that you can edit the cells.
- Double touch the cell to start editing.
- Now hit the tab key in your android keyboard.
![tabkey](https://user-images.githubusercontent.com/20186660/51898212-1df49180-23b9-11e9-87a7-8889b01c1c28.PNG)

**Current behavior**
When you click the tab key in android keyboard it will stop editing the cell, it does not move to the next cell (it works like enter key not tab key).

**Expected behavior**
the tab key should navigate to the next cell.

**Please tell us about your environment:**

* **ag-Grid version:**
My web app grid version:
ag-grid-angular 19.1.2.
ag-grid-community 19.1.4.
and the current version in the official website.

* **Browser:**
Chrome android latest version: 71.0.3578.99
Firefox android latest version: 64.0.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We haven't found a stock keyboard that has the tab key for android, we are going to close this issue as it looks to us as this down to a custom key.

Feel free to open a new issue if you think our assessment is wrong

Thanks
