### ISSUE TITLE
Styling Header Cells in Excel Export

### ISSUE THREAD

**Issue by katye610** [ag-grid/ag-grid#2919]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

I am trying to add some styling to the header row when exporting to Excel (.xls). My project uses Angular 6 and v18.0.1 of ag-grid enterprise. I followed the documentation for how to define excelStyles, and my custom header's styling is behaving as expected.

However, I want just the column header cells of my aggrid to have light styling in the Excel sheet (different font color and background color) in order to better visually distinguish them from their contents. How do I do this? Adding headerClass to the columnDef works if I define a corresponding css class, but it doesn't work when I define an excelStyle with that id.

Additionally, headerRowHeight does not seem to work either, when passed in as a property of the exportParams passed into the exportDataAsExcel function. Any help would be greatly appreciated!

**Comment by katye610** [comment]
Realized that the excel style id that described the grid headers has to always be 'header'.

**Comment by avirupThinkbridge** [comment]
I am facing same problem.

**Comment by harika-c** [comment]
Im also facing same problem , need to style headers differently in excel export
