### ISSUE TITLE
Header check box selection not working for indeterminate state @v20

### ISSUE THREAD

**Issue by BMK91** [ag-grid/ag-grid#2924]
Hi,

https://www.ag-grid.com/javascript-grid-selection/#header-checkbox-selection

In v20 header check box doesn't update for indeterminate state in any language.
Working fine in v19.

Hope to fix it early.
Thanks.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by lunanigra** [comment]
Hello, not sure if the is exactly the same case. In my case the bug is that the checkbox in the header row doesn't get de-selected when un-checking a single row.

I will verify again when this issue is fixed and the demo site got updated.

Thanks!

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2645 - Selection - Indeterminate state for mixed selection of rows with group header selection is not working

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
