### ISSUE TITLE
why every new version css classes must be changed ?

### ISSUE THREAD

**Issue by felek000** [ag-grid/ag-grid#2925]
Im working on grid and often i want override some options visual or add features like fixed header fixed horizontal scroll. I use css class to find those elements. Why every update it has to be changed ?

example: ag-body-viewport ->  .ag-body-horizontal-scroll-viewport

**Comment by gportela85** [comment]
Scrolling is a big part of a grid functionality and moving DOM containers around are required sometimes to enhance how scrollers are sync.
Note that changes like this only happen across major versions and the release notes warn about this as `Breaking Changes`.
