### ISSUE TITLE
ag-grid still not passing context properly

### ISSUE THREAD

**Issue by mellis481** [ag-grid/ag-grid#2927]
I'm using the form library Formik in my app and using its `Field` component to render an input in my AgGrid instance.  AgGrid is not passing the Formik context data through properly.  I was hoping the 20.0.x upgrade would resolve this, but alas.

Here is a [CodeSandbox][1] that illustrates the issue.  When I inspect `this.props.formik` which should be my Formik bag, it's an empty object.  This is the same object I see when I put my break point in the `Field`'s `render` function.  When I inspect this object for instances of my `Field` outside of agGrid, it is the fully populated Formik bag including `initialValue` props, `registerField` function, etc.

**Why is Formik not properly retrieving the Formik bag `form` object when my `Field` is nested in an AgGrid table cell and how can I address this issue?**

  [1]: https://codesandbox.io/s/0w97oqjjl

**Comment by rob2d** [comment]
also having this issue with Cell Renderers. Seems it's not including them within the AgGrid tree or passing via a portal properly.

**Comment by rob2d** [comment]
@mellis481 figured it out :slightly_smiling_face:  If you pass `reactNext` property to your `AgGrid` component, it will enable the "experimental" mode for React 16 to use Portals for keeping components in the tree.

**Comment by awaisaly** [comment]
This issue is fixed in the following thread:
[Fixed Issue Thread](https://github.com/jaredpalmer/formik/issues/1269)

You can also check the example on Sandbox i.e. 
[Sandbox Example Code](https://codesandbox.io/s/formik-with-aggrid-example-no-context-pdl54)
