### ISSUE TITLE
Cell tooltip gets extra escaping

### ISSUE THREAD

**Issue by shirosaki** [ag-grid/ag-grid#2928]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Define tooltip function to colDef.
```
tooltip: function (params) {
   return params.value;
}
```
Set node value by `setDataValue` API.
```
node.setDataValue(colId, '<');
```

**Current behavior**

Tooltip is shown as `&lt;`.

**Expected behavior**

Tooltip is shown as `<`.

**Please tell us about your environment:**

* **ag-Grid version:** 18.0.1

* **Browser:**
Firefox ESR 60.5.0

Here is a patch.

HTML escape would not be needed for`setAttribute`.

https://stackoverflow.com/questions/50140983/does-setattribute-automatically-escape-html-characters

```diff
diff --git a/packages/ag-grid-community/src/ts/rendering/cellComp.ts b/packages/ag-grid-community/src/ts/rendering/cellComp.ts
index 1343192f7..01fa5f589 100644
--- a/packages/ag-grid-community/src/ts/rendering/cellComp.ts
+++ b/packages/ag-grid-community/src/ts/rendering/cellComp.ts
@@ -604,8 +604,7 @@ export class CellComp extends Component {
         if (this.tooltip !== newTooltip) {
             this.tooltip = newTooltip;
             if (_.exists(newTooltip)) {
-                let tooltipSanitised = _.escape(this.tooltip);
-                this.eParentOfValue.setAttribute('title', tooltipSanitised);
+                this.eParentOfValue.setAttribute('title', this.tooltip);
             } else {
                 this.eParentOfValue.removeAttribute('title');
             }
```

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog that should fix this as part of rewriting the tooltips logic:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-1617	Allow complex tooltip / popup / renderer components in ag-grid to stick to the row/column as the user scrolls or the viewport is resized

**Comment by spyro2000** [comment]
Having the same problem, even single quotes are escaped to html entities. Can't either find AG-1617 in issue tracker.

**Comment by mistic100** [comment]
@makinggoodsoftware same as @spyro2000  
how can I know if this has been fixed and in which version ?

Currently using 25.3.0 and I have the problem. But cannot reproduce on plunkr so I guess it has be fixed but is it on the 25 or 26 mains version ?

**Comment by mistic100** [comment]
found it in the changelog for v20 https://www.ag-grid.com/ag-grid-changelog/
so I don't know what's going on

**Comment by spyro2000** [comment]
AG-1617 is about custom tooltip components, about about the double-escaping of characters like quotes...

**Comment by mistic100** [comment]
Yes your are right, I saw the difference after.

 Well 1617 has been fixed in v20 by the changelog page. I suggest you open another ticket if the bug reappeared in newer versions.
