### ISSUE TITLE
cellRendererParams are not passed to refresh

### ISSUE THREAD

**Issue by nzacca** [ag-grid/ag-grid#2929]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When refreshing a custom cell renderer, the `cellRendererParams` are not passed to `refresh`.

**Expected behavior**
Expect to have access to the params defined in `cellRendererParams` on refresh.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** 20.0.0

* **Browser:**
N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

Hello!

This appears to be an issue here: https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/rendering/cellComp.ts#L605

The `createCellRendererParams` method does not include the custom params. Here's an example where the params are included: https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/components/framework/componentResolver.ts#L286

Please see the following plunker for a demo of the issue: https://next.plnkr.co/edit/3EtrykSoiuCEEKF5

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
his is in our backlog now and we are tracking it with the following reference and description.

AG-2642 - When refreshing a custom cell renderer, the `cellRendererParams` are not passed to `refresh`.

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by JabbyPanda** [comment]
Fix is coming https://github.com/ag-grid/ag-grid/commit/ace3c2b92821c495de20e463be78578aa998369d to 20.2.0 version of `ag-grid`
