### ISSUE TITLE
Options needed to filter records by empty values in Date filter

### ISSUE THREAD

**Issue by gauravbrills** [ag-grid/ag-grid#2937]
We are using ag grid server side model but currently there is no way to allow users to be able to filter by null or blank records . AS we need to pass null values to the backend in case they want to filter by blank rows .
 
It would be great if Ag grid exposes a functionality to allow users to input null or blank when applying the date filter . 

**Version Info**
"ag-grid-enterprise": "19.0.0",

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2166	Filters - Allow creating custom filter options and new ones like: is null, is not null

**Comment by gauravbrills** [comment]
Thanks we will contact then @makinggoodsoftware  . But is there a workaround for this issue  as it is like a blocker for us right now ?
