### ISSUE TITLE
ag-grid-react multi-sort by default prop [Community Support]

### ISSUE THREAD

**Issue by cinnabarcaracal** [ag-grid/ag-grid#2939]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Some users are not familiar with using keyboard shortcuts inside the browser, I think it would be useful to have a declarative way to enable/disable whether multisort is active. This would let us either make it the default, or control the current sort type with an on-screen component.

I would be happy to submit a pull request myself, but I'm not sure of the best name/behaviour for this prop/feature.

If multiselect has been turned on using a prop, should the ctrl (or other configured key) click do a standard sort?

some ideas:
```
<AgGridReact
  multiSortActive={true|false}
  defaultSortType={"multi" | "standard"}
  multiSortByDefault={true|false}
...
/>
```

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
