### ISSUE TITLE
expandAll and collapseAll does not work on Master Details grid

### ISSUE THREAD

**Issue by DominicTobias** [ag-grid/ag-grid#2940]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

On behalf of an enterprise customer.

**Providing a Reproducible Scenario**

https://plnkr.co/edit/dL6w5FFCSNyT5Akystv6?p=preview

Forked from: https://www.ag-grid.com/javascript-grid-master-detail/

- Click expandAll or collapseAll
- Expected: expands or collapses the rows
- Actual: does nothing

**Please tell us about your environment:**
Windows 7, Chrome 71

* **ag-Grid version:** X.X.X
Version 20.0.0

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
