### ISSUE TITLE
Add column "Default value" for documentation

### ISSUE THREAD

**Issue by peteichuk** [ag-grid/ag-grid#2941]
**Add column "Default value" for documentation**

Add a default values.
[url to documentation](https://www.ag-grid.com/javascript-grid-column-properties/)

For example :
![screenshot](https://user-images.githubusercontent.com/13536343/52414880-2b62f780-2aee-11e9-8716-512a221e2193.jpg)
Or
![screenshot2](https://user-images.githubusercontent.com/13536343/52415209-0c189a00-2aef-11e9-8c9c-41dbbacaef3b.jpg)

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by peteichuk** [comment]
> Hi,
> 
> Thank you for raising this issue for us.
> 
> As I am sure you are aware, we offer two products:
> 
> ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
> ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)
> 
> If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.
> 
> If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact [info@ag-grid.com](mailto:info@ag-grid.com) for access. This is our primary channel for Support.

Thanks!
