### ISSUE TITLE
Double call for data when datasource changed

### ISSUE THREAD

**Issue by AGLearning** [ag-grid/ag-grid#2944]
I'm submitting a bug

Plunker:

https://plnkr.co/edit/YnE0NU1RoTn9KOQ1DMgX?p=preview

Current behavior
When I set datasource after grid initialization there are two calls for data

Expected behavior
One call for data

Versions:
"ag-grid-angular": "^20.0.0",
"ag-grid-community": "^20.0.0",

I believe that problem is here (ag-grid/dist/lib/components/componentUtil.js):
line 131
if (changes.datasource) {
   api.setDatasource(changes.datasource.currentValue);
}
and doubled in line 158
if (changes.datasource) {
   api.setDatasource(changes.datasource.currentValue);
}

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by tannerlyons** [comment]
@makinggoodsoftware I believe this is a bug in the community edition and should be reopened.
I see this issue as well and can confirm there are two requests sent when changing a datasource.

The affected file in the distribution bundle is `node_modules/ag-grid-community/dist/lib/components/componentUtil.js`, though the line numbers have changed now:

https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/components/componentUtil.ts#L168
https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/components/componentUtil.ts#L204

**Comment by tannerlyons** [comment]
@makinggoodsoftware any updates here? This is a bug that would affect enterprise customers as well!

**Comment by draviddotproduct** [comment]
Any updates here ?
