### ISSUE TITLE
Screen reader not reading column headings correctly/consistently for ADA compliance

### ISSUE THREAD

**Issue by dcohen613** [ag-grid/ag-grid#2951]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Using a screen reader such as NVDA, incorrect column headers may be read as a user navigates the grid with the arrow keys on the keyboard

**Expected behavior**
Screen reader/assistive technology should read the correct column heading.

**Actual behavior**
Somehow the column name gets out of sync while navigating the grid. This is evident using NVDA, even on the demo: https://www.ag-grid.com/javascript-grid-sorting/.
This issue appears to be intermittent.

**Please tell us about your environment:**
Windows 10, Webstorm, NVDA, Chrome

* **ag-Grid version:** X.X.X
Latest, check https://www.ag-grid.com/javascript-grid-sorting/

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by dcohen613** [comment]
Why was this closed? This is a bug in the community version, and the issue was reported via GitHub.

Here is a screenshot from this plunkr that you control (on the page linked in the above defect):

https://i.imgur.com/UuY9v6F.png
