### ISSUE TITLE
enterMovesDown / enterMovesDownAfterEdit fails to work correctly in Internet Explorer

### ISSUE THREAD

**Issue by Aceofspades25** [ag-grid/ag-grid#2952]
**I'm submitting a bug report**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

This issue appears to happen in Internet Explorer 11 and all earlier versions of IE where ag-grid is supported. It does not happen in Microsoft Edge or Google Chrome. 

Summary:
Pressing "Enter" will move the selected cell down a level but that newly selected cell will not be ready to accept input from the keyboard.

Details:
If you click a cell with your mouse, you can start typing and the cell will immediately go into edit mode and accept what you are typing as input - but if you press enter to move to the next cell down and start typing, the selected cell will move down one position as expected but if you start typing now it will not go into edit mode and it will not accept input from the keyboard.

**Providing a Reproducible Scenario**

This Plunker is one of ag-grid's own samples:
[https://plnkr.co/edit/H3w02Q4qpUifrDenuo1b?p=preview](https://plnkr.co/edit/H3w02Q4qpUifrDenuo1b?p=preview)

You can also find that sample here:
[https://www.ag-grid.com/javascript-grid-cell-editing/#enter-key-down](https://www.ag-grid.com/javascript-grid-cell-editing/#enter-key-down)

**Current behavior**
In Internet Explorer 11: When using "Enter" to move down a cell, the newly selected cell is not immediately ready to accept input from the keyboard. Any typing will be ignored after pressing "Enter". You have to click a cell with your mouse before it will actually be ready to start accepting input.

**Expected behavior**
When using "Enter" to move down a cell, the newly selected cell should be immediately ready to accept input from the keyboard.

**Please tell us about your environment:**
Internet Explorer 11

* **ag-Grid version:**
This issue has been tested and reproduced on versions 20.0.0 and 19.1.2

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; rv:11.0) like Gecko"

* **Language:**
All: Javascript, Angular, React, Vue

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG‌-2611 - ie11 - Enter Key Navigation not working

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
