### ISSUE TITLE
Copy to clipboard does not work properly with enterprise server side row model

### ISSUE THREAD

**Issue by luanped** [ag-grid/ag-grid#2953]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
This can be seen with enterprise Server side infinite scroll demo found at https://www.ag-grid.com/javascript-grid-server-side-model-infinite/

Scroll down the page, to the only example in that page. Select the first row, press control C, see the cell flash. empty the clipboard with something else. select back again the first row, now scroll to the bottom of the screen, press control C, notice that it doesn't copy. Right clicking on context menu and selecting copy from there do work however.

More info: select row 0 or 1, if you scroll to around row 150 and press control c, you can see that the copy still works
However if you scroll to row ~400 it won't anymore

**Expected behavior**
It should copy the cell / row

**Please tell us about your environment:**
Windows 10, Chrome 71 

* **ag-Grid version:** 20.0.0

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by makinggoodsoftware** [comment]
Based on this:

now scroll to the bottom of the screen, press control C, n

You are removing the row from the loaded rows in view, this is working as expected, if you are a customer, I would suggest to follow up over zendesk

Thanks
