### ISSUE TITLE
Context Menu doesn't work on empty table space like in version 19.x

### ISSUE THREAD

**Issue by windischb** [ag-grid/ag-grid#2954]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behaviour.**
Context menu not triggert on empty space in table.

**Expected behavior**
As in Version 19.x context menu also works on empty table space!
I need this to have a Menu entry for creating new Items

* **ag-Grid version:** 20.0.0

* **Browser:** Chrome

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-1046
Allow opening context menu from an empty area of the grid
