### ISSUE TITLE
setFilterModel is not working after applying new columns by metod setColumnDefs

### ISSUE THREAD

**Issue by felek000** [ag-grid/ag-grid#2955]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

Plunker:
[https://plnkr.co/edit/mDUVqCTIABkYl80xPEFj?p=preview](https://plnkr.co/edit/mDUVqCTIABkYl80xPEFj?p=preview)

press hardcoded Filter results warning

Current behaviour.
When changing columns by `gridOptions.api.setColumnDefs` and apply filter `gridOptions.api.setFilterModel(filter)`
filter is not working and returns Warning `no column found for colId`

**Expected behavior**
Filter will applay

* **ag-Grid version:** 
20 vanilla Enterprise

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Our consultants have put together the following example for you

https://next.plnkr.co/edit/17yyIpMdZJjSKunn?preview

The solution is to add colId’s to each colDef, otherwise they will alternate between e.g. ‘athlete’ and ‘athlete_1’

Can you please have a look and see if it make sense?

Hope this helps.

**Comment by felek000** [comment]
I'm sorry for late reply. Still example provided not illustrate problem. Error is like in link
[](https://plnkr.co/edit/mDUVqCTIABkYl80xPEFj?p=preview).

When data is change (api calls on update and reload data in database). Then filters broke.

**Comment by kupchic** [comment]
Still actual issue
