### ISSUE TITLE
paginationAutoPageSize option breaks ag-grid wrapped with any block element

### ISSUE THREAD

**Issue by jgood044** [ag-grid/ag-grid#2959]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Wrap ag-grid with any block element (i.e. div, section, etc.)
- Enable the paginationAutoPageSize option

Plunker: https://plnkr.co/edit/UCnIcLTwsSiBgAPFMVXm?p=preview

_Note: the only difference between the above Plunker and the one found in the [official ag-grid documentation](https://www.ag-grid.com/javascript-grid-pagination/#auto-page-size) is the wrapping div element._

**Current behavior**
Grid height is continuously adjusted/calculated causing persistent rendering issues.

**Expected behavior**
Grid height calculation/rendering only occurs when page size is adjusted (i.e. when grid is not wrapped with a block element like in official demo).

* **ag-Grid version:** 20.0.0

* **Browser:** Chrome

* **Language:** TypeScript

**Comment by JLuitjens** [comment]
> Note: the only difference between the above Plunker and the one found in the [official ag-grid documentation](https://www.ag-grid.com/javascript-grid-pagination/#auto-page-size) is the wrapping div element.

Actually, official ag-grid documentation parent div has height 98% and the ag-grid has a height of 100%, try that out and you will see it working

**Comment by jgood044** [comment]
Looks like adding a height to the parent div resolves the issue. Thanks @JLuitjens!
