### ISSUE TITLE
Need an example for Date range floating filter

### ISSUE THREAD

**Issue by sirisha0707** [ag-grid/ag-grid#2961]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```
Hi There,

Could you please provide us on example for ```Date range floating filter```

**Comment by sirisha0707** [comment]
Hi,

I am able to doing by following the document. Thank you. 
Closing the request now.

**Comment by mangukiya12** [comment]
Can you share the references that you had taken
