### ISSUE TITLE
Horizontal Scrollbar not rendering properly on mac

### ISSUE THREAD

**Issue by baveryt** [ag-grid/ag-grid#2962]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
- View the example at : https://www.ag-grid.com/javascript-grid-width-and-height/#changing-width-and-height 
- Select fill 60% to force horizontal scrolling
- On a windows platform the horizontal scrollbar will remain visible no matter where you are in the vertical sense.
- On a mac you only can see the horizontal scrollbar once you have scrolled to the max in the vertical sense

**Expected behavior**
- The horizontal scroll bar should always be visible on a mac as it is on a windows platform.

**Please tell us about your environment:**
- Comparing Mac OSx Mojave vs Windows 10

* **ag-Grid version:** 20.0.0

* **Browser:** Firefox 65 and Chrome 72

* **Language:** [all]

I have traced the issue down to the utils:getScrollbarWidth. The function does not properly calculate the scrollbar width on macs causing the eHorizontalScrollBody to have a height of 0 rather than the scrollbar width.

**Comment by envynoiz** [comment]
I noticed this issue today, in previous versions, the scroll bar is rendered as expected but now with the latest one (20.0.0), I'm unable to see it. 

S.O: MacOs Mojave 10.14

**Comment by EddieBenji** [comment]
Same happens on Linux

O.S.: Ubuntu 18.04.02 LTS, with gnome  3.28.3

**Comment by billdwhite** [comment]
same issue here

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We've investigated this issue and things seem to be working fine on our end.
Perhaps your mac is configured to not always show the scrollbar. This can be changed in:
systemPreferences/general/showScrollBars: ‘always’

Best regards,

**Comment by baveryt** [comment]
You're right in that my mac is not configured to always show the scroll bar and adjusting the setting does resolve the issue. However, it's not reasonable for me to force or expect users to adjust system level settings forcing showing of the scroll bar.

**Comment by MakcStudio** [comment]
+1

On Windows also does not work. Had to put 19 version of

**Comment by gportela85** [comment]
@MakcStudio Windows should always display the scrollbar. If you are seeing an issue there, is probably not related to this.

**Comment by tonjohn** [comment]
Scrolling in both directions is broken in my Angular 7 project when upgrading to v20.x. I was able to resolve it by downgrading to v19.

I'm testing on Chrome Version 74.0.3729.131 (Official Build) (64-bit) & Edge Version 75.0.131.0 (Official build) dev (64-bit)

**Comment by nandithakw** [comment]
solution by @tonjohn  worked .I had was the same css issue.

**Comment by tamasc** [comment]
@tonjohn 's solution worked for me as well. Thanks

**Comment by Goldbeener** [comment]
> Hi,
> 
> We've investigated this issue and things seem to be working fine on our end.
> Perhaps your mac is configured to not always show the scrollbar. This can be changed in:
> systemPreferences/general/showScrollBars: ‘always’
> 
> Best regards,

Hi, 
I met the same case with @baveryt.
I'm confused that why the demos in official show correctly without config systemPreferences, while my project does not in the same machine.
Thanks for your answer.

**Comment by cdussud** [comment]
Note this is still an issue. None of the documentation examples show a horizontal scrollbar on a Mac until the user has scrolled to the bottom of the rows.

Pick any example: https://www.ag-grid.com/javascript-grid-column-definitions/#column-ids

When scrolled to the top, no horizontal scrollbar is visible. When scrolled to the bottom, the horizontal scrollbar is visible again.

**Comment by triadiprabowo** [comment]
I can confirmed, as @cdussud mentioned, this is still an issue. 
I am using ag-grid-enterprise 23.0.2

The scenario:
1. I have set isExternalFilterPresent => true and doesExternalFilterPass(): boolean
2. I've loaded data from server (e.g. total 20 data with filter = false), so default view will not show any data unless I click certain button (in my UI) to trigger onFilterChanged()
3. 20 data now visible in grid but horizontal scrollbar not show unless we scroll to very bottom

Using scrollbarWidth=15 (macos) default width for scrollbar works fine for me.

OSX (Chrome, Safari, Firefox) - 15px. Windows XP (IE7, Chrome, Firefox) - 17px. Windows 7 (IE10, IE11, Chrome, Firefox) - 17px. Windows 8.1 (IE11, Chrome, Firefox) - 17px.

**Comment by MalaPatil** [comment]
@tonjohn i tried yours solution its not working in my case ,i'm using angular 13 with ag-grid 27.3.0
when i used @import "~ag-grid/dist/styles/ag-grid.css" im getting the below error 

./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss - Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find 'ag-grid/dist/styles/ag-grid.css'
  in
![image](https://user-images.githubusercontent.com/103051193/178429250-eef811f7-f44e-49af-8e8b-ef3a4e6d0000.png)
