### ISSUE TITLE
Screen reader not reading column headings correctly/consistently for ADA compliance

### ISSUE THREAD

**Issue by dcohen613** [ag-grid/ag-grid#2963]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Using a screen reader such as NVDA, incorrect column headers may be read as a user navigates the grid with the arrow keys on the keyboard

**Expected behavior**
Screen reader/assistive technology should read the correct column heading.

**Actual behavior**
Somehow the column name gets out of sync while navigating the grid. This is evident using NVDA, even on the demo: https://www.ag-grid.com/javascript-grid-sorting/.
This issue appears to be intermittent.

**Please tell us about your environment:**
Windows 10, Webstorm, NVDA, Chrome

* **ag-Grid version:** X.X.X
Latest, check https://www.ag-grid.com/javascript-grid-sorting/

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

* **Language:** [all]

> **Please do not simply close this bug without addressing the issue.  The [previous report](https://github.com/ag-grid/ag-grid/issues/2951) was closed for no reason. This is a bug in the community version.**
> 
> Here is a screenshot from this plunkr that you control (on the page linked in the above defect):
> 
> https://i.imgur.com/UuY9v6F.png

**Comment by dcohen613** [comment]
Any update on this?

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2016
Improve Accessibility across the grid - ARIA, ADA...

**Comment by agenaille** [comment]
This is a super high priority issue for us, as our client takes 508 compliance very seriously and this one is pretty much a show stopper for a blind person being able to navigate this grid effectively. We are going to open another defect for this with our support account.

**Comment by kiril-matev** [comment]
Hi @agenaille ,

Thanks for reaching out.

Please see the test case below:
1. Open
https://plnkr.co/edit/DO3F4vp0FV6FqTcV?open=main.js
2. Open console
3. Use the element inspector button in the console 
4. Click the top-left grid cell (Michael Phelps)
**Actual & Expected**: DOM element related to the Michael Phelps cell is shown in console and it has property aria-colindex=1
5. Reorder columns - drag AGE column left to make it the first column
Click the top-left grid cell (23)
**Actual & Expected**: DOM element related to the 23 cell is shown in console and it has property aria-colindex=1

As you can see, AG Grid is correctly setting the cell's aria-colindex property. However, see the NVDA announcements listed below:
NVDA announcement after step (4) in test case above - Michael Phelps row 2 athlete column 1 (as expected)
NVDA announcement after step (6) in test case above - 23 row 2 age column 3 (incorrect)

As you can see, NVDA is not announcing the aria-colindex value for the cell correctly. Specifically the NVDA announcement after step (6):
**Actual**: 23 row 2 age column 3
**Expected**: 23 row 2 age column 1

Please file this issue with NVDA so it can be addressed.

Thank you for bringing this up.
