### ISSUE TITLE
exportDataAsExcel with customHeader only works if at least two columns are available

### ISSUE THREAD

**Issue by tschulte** [ag-grid/ag-grid#2964]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

We are a paying customer of AG-Grid. But I still do put this here.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

See https://next.plnkr.co/edit/EYrtEqxdS3S85t5Z

This example tries to export to excel including a customHeader.

**Current behavior**

Excel Export is only possible if at least two columns are exported. You can select which columns to include in the plunker. When not selecting any column, there is one exception in the console, when selecting only one column, there is a different exception in the console. In both cases no excel file is exported. 

The checkbox "Export in €" is for bug #2965.

**Expected behavior**

In both cases there should be an excel file with at least the customHeader (plus the one column, if one column was selected)

**Please tell us about your environment:**

Linux + Windows, Excel + Libre-Office

* **ag-Grid version:** 20.0.0

* **Browser:**

Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
See plunker

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2682 - Excel Export with customHeader only works if at least two columns are exported

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by joeythomaschaske** [comment]
Where is `customHeader` in the documentation? https://www.ag-grid.com/javascript-data-grid/excel-export-api/#excelexportparams
