### ISSUE TITLE
exportDataAsExcel doesn't allow umlauts in customHeader and sheetName

### ISSUE THREAD

**Issue by tschulte** [ag-grid/ag-grid#2965]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

We are a paying customer of AG-Grid. But I still do put this here.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

See https://next.plnkr.co/edit/EYrtEqxdS3S85t5Z

This example tries to export to excel including a customHeader.

**Current behavior**

See #2964: Check both checkboxes "Export athlete" and "Export age".

Check "Export in €" and try to export to Excel. The Excel is not complete, all cells before the header with the € sign are exported, but everything starting with that cell is not. It seems that only ascii chars like A-Z, 0-9 $, etc. can be exported, but non ascii chars like umlauts (üöä), accented chars (éè, etc) and others (€§»«, etc.) can not be exported. When these chars are part of the table, it works.

When trying to set the sheetName to something with umlauts or containing the € sign, the excel is corrupt.

I have not tested with customFooter.

**Expected behavior**

Umlauts and other chars should work in both customHeader/customFooter and sheetName.

**Please tell us about your environment:**

Linux + Windows, Excel + Libre-Office

* **ag-Grid version:** 20.0.0

* **Browser:**

Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
See plunker

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2582 - Export - Special characters not supported in excel export

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
