### ISSUE TITLE
cellKeyDown and cellKeyPress do not function in Firefox

### ISSUE THREAD

**Issue by dcohen613** [ag-grid/ag-grid#2975]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
[https://www.ag-grid.com/javascript-grid-keyboard-navigation/](https://www.ag-grid.com/javascript-grid-keyboard-navigation/)
When demoing the **Keyboard Events**, the console reports an error:
`ERROR ReferenceError: "event is not defined"`

**Expected behavior**
Keyboard events should be captured

**Please tell us about your environment:**

* **ag-Grid version:** 20.1.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

* **Language:** [TypeScript ~2.9.0]

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG‌-2695 - cellKeyDown and cellKeyPress throw exception in Firefox

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
