### ISSUE TITLE
Exception after updating version to 20.1.0

### ISSUE THREAD

**Issue by shafaqkazmi** [ag-grid/ag-grid#2976]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**

After the version update from 19.1.1 to 20.1.0, below exceptions came:

```
ERROR in /node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts (133,46): Type expected.

ERROR in /node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts (133,53): Parameter declaration expected.

ERROR in /node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts (133,72): ';' expected.

ERROR in /node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts (133,73): Unexpected token. A constructor, method, accessor, or property was expected.

ERROR in /node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts (133,101): ';' expected.

ERROR in /node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts (133,103): Unexpected token. A constructor, method, accessor, or property was expected.
```

**Expected behavior**

Everything should work fine after version update

**Please tell us about your environment:**

* **ag-Grid version:** 20.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "2.3",

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by mbrookson** [comment]
Also seeing this issue (or a very similar one) with .d.ts definitions.

I have just installed ag-grid and have the following in my `package.json`

```
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "ag-grid-angular": "^20.1.0",
    "ag-grid-community": "^20.1.0",
```

I am seeing the following errors:

```
ERROR in node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts(133,52): error TS1005: ',' expected.
node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts(133,73): error TS1144: '{' or ';' expected.
node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts(133,101): error TS1005: ';' expected.
node_modules/ag-grid-community/dist/lib/gridOptionsWrapper.d.ts(133,103): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
```

**Comment by mbrookson** [comment]
Turns out this is a compatibility issue with TypeScript. I've upgraded my project to Angular 7 and TypeScript 3.2.4 and it's working as expected now 👍

**Comment by nightullr** [comment]
I had the same issue with the same error this morning in Angular 5. I can't upgrade my project to Angular 7 yet just for this, but reverting ag-grid-community to v20.0.0 fixed it for me.

**Comment by gforceg** [comment]
Using Angular 6 here. Upgrading to typescript 2.9 fixed this issue for me

**Comment by mbrookson** [comment]
Yeah, seems like it was likely a TypeScript version issue rather than Angular. There must have been a breaking change in the .d.ts definitions as the TypeScript version for Angular 6 is relatively old now.

**Comment by yatharthmishra95** [comment]
I am using angular 6 and also getting the same errors while updating from ag-grid version 18.1.0 to 20.1.0 ,also getting the same error with ag grid version 20.0.0 Can some one please tell the fix
package.json
`{
  "name": "trackerui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --bh /trackerui/",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.2",
    "@angular/cdk": "^6.3.2",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.3.2",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "ag-grid": "^18.1.2",
    "ag-grid-community": "^20.0.0",
    "ag-grid-enterprise": "^20.0.0",
    "angular-calendar": "^0.26.6",
    "angular-tree-component": "^7.2.1",
    "bootstrap": "^3.4.1",
    "core-js": "^2.6.5",
    "date-fns": "^1.30.1",
    "file-saver": "1.3.8",
    "jquery": "^3.3.1",
    "jquery-ui": "^1.12.1",
    "ng2-file-upload": "^1.3.0",
    "npm": "^6.9.0",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "to": "^0.2.9",
    "update": "^0.7.4",
    "xlsx": "0.12.13",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.3",
    "@angular/cli": "~6.0.3",
    "@angular/compiler-cli": "^6.0.2",
    "@angular/language-service": "^6.0.2",
    "@types/jasmine": "^2.8.16",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.2.5",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}
`

**Comment by mbrookson** [comment]
@yatharthmishra95 I'm not 100% sure which exact version is needed by try upgrading your TypeScript version. 


> Turns out this is a compatibility issue with TypeScript. I've upgraded my project to Angular 7 and TypeScript 3.2.4 and it's working as expected now 👍
