### ISSUE TITLE
Number Filter issue "equals and equals " 

### ISSUE THREAD

**Issue by srjkrl20011991** [ag-grid/ag-grid#2978]
Plinker: 
https://plnkr.co/edit/aA7D4At58yg7AqwD1qxc?p=preview

I am new to ag-grid. I am trying to apply numbercolumnfilter to ag-grid on age column
select equals 23 AND again select equals 27

Result: empty grid
Expected result: both row need to show

Can I able to achieve this type of scenario OR not?

**Comment by gportela85** [comment]
Turns out, you had the solution already `OR`.

![screenshot 2019-02-27 at 11 03 14](https://user-images.githubusercontent.com/7908562/53485897-556d6100-3a7f-11e9-9c8c-88c7cd173ec5.png)

**Comment by srjkrl20011991** [comment]
But we AND means combine result of two filters 
is my assumption right ?

**Comment by gportela85** [comment]
No, `AND` means that you want a number to 23 and 27 at the same time which is impossible.
Think of it as 
`let myResult = array.filter(val => val === 23 && val === 27)`
it's never going to be true.

**Comment by srjkrl20011991** [comment]
Thanks @gportela85
