### ISSUE TITLE
is it possible to add nullComparator only for not equal value

### ISSUE THREAD

**Issue by srjkrl20011991** [ag-grid/ag-grid#2981]
Can we add nullComparator only for notEqual?
We need only null value rows in result when we select notEqual filter with some vaue.

is it possible?
Like =>
 nullComparator: {
                notEqual: true
            }

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
