### ISSUE TITLE
Doc property formatting for grouping is incorrect

### ISSUE THREAD

**Issue by revelThis** [ag-grid/ag-grid#2982]
https://www.ag-grid.com/javascript-grid-grouping/#showRowGroup 

In the example it shows, 

   ` {headerName: "Country - group", showRowGroup='country', width: 120, cellRenderer:'agGroupCellRenderer'},`

where showRowGroup should be a colon and not an equal sign, 
`showRowGroup:'country'`

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2702 - Docs fix example typo for showRowGroup

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
