### ISSUE TITLE
Row grouping when hide open parents, first column disappear after second group expand

### ISSUE THREAD

**Issue by iblader** [ag-grid/ag-grid#2987]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
![2019-03-01 01_47_20-grouping by row_ core feature of our datagrid](https://user-images.githubusercontent.com/2498986/53587047-5b208f00-3bc4-11e9-8fc2-5993a740a9e7.png)

**Please tell us about your environment:**

* **ag-Grid version:**
20.1.0

* **Browser:**
Chrome 72
* **Language:** [all | TypeScript 3.3.3]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by iblader** [comment]
Thanks and looking forward to the updates.

> 
> 
> Hi,
> 
> Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)
> 
> We will carry on there with the investigation and we will update you as soon as possible.
> 
> Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-2711	groupHideOpenParents is not working as expected in 20.1.0
