### ISSUE TITLE
Vue component has no method getModelAsString in prototype

### ISSUE THREAD

**Issue by NikitaIT** [ag-grid/ag-grid#2992]
https://github.com/ag-grid/ag-grid/blob/855e7422a3721e72ede9054f0472259dff8675df/packages/ag-grid-community/src/ts/components/framework/componentRecipes.ts#L165

I have already corrected it recently elsewhere, but here I can not say exactly how best
I have: 
```
 Vue.component(
...
methods: {
  getModelAsString(model) {
      debugger;
      return model.value.toLocaleString();
    }
 }
);
```
And I have: 
![image](https://user-images.githubusercontent.com/16810067/53688253-20e4f800-3d52-11e9-965f-8840a760e71e.png)

**Comment by NikitaIT** [comment]
same problem
https://github.com/ag-grid/ag-grid/issues/2309

**Comment by NikitaIT** [comment]
I think it's time to remove all such places with the test prototype, because it is constantly causing problems

**Comment by NikitaIT** [comment]
temporary solution in place
`Vue.prototype.getModelAsString = () => ''`

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Would it be possible to provide us an example that isolates this issue? The one provided that has .Net has too much going on to be able to diagnose this issue.

Could you provide one that is plain JS/Vue?

You can fork from our doc examples

https://www.ag-grid.com/javascript-grid-filter-component/#vueFiltering

Thanks

**Comment by NikitaIT** [comment]
@makinggoodsoftware 
ok i will do it after a while, the documentation describes this problem, I learned it from reading the Doc about two months ago and added a similar fix in
https://github.com/ag-grid/ag-grid/pull/2942

**Comment by NikitaIT** [comment]
@makinggoodsoftware example that isolates this issue: https://next.plnkr.co/edit/UkU7nW7NeJsbUtSp
much time has passed but I met it again in a new project
![image](https://user-images.githubusercontent.com/16810067/61403135-55121d00-a8dd-11e9-88ca-4a1184159de3.png)
