### ISSUE TITLE
suppressMenu is true but the header still reserve space

### ISSUE THREAD

**Issue by leduykhanh** [ag-grid/ag-grid#2995]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Use enterprise version.

**Current behavior**
Grid Options: `menuTabs: ['columnsMenuTab']`
ColumnDef: `suppressMenu: true.`
But it still reserve a space as big as menu button

**Expected behavior**
Remove that space.

* **ag-Grid version:** X.X.X
    "ag-grid": "^18.1.2",
    "ag-grid-angular": "^20.1.0",
    "ag-grid-community": "^20.1.0",
    "ag-grid-enterprise": "20.1.0",

* **Browser:**
Google chrome

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
