### ISSUE TITLE
When using master/details, rows from the details grid are not exported

### ISSUE THREAD

**Issue by adamwinn** [ag-grid/ag-grid#3001]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
https://next.plnkr.co/edit/cVUZpnTVhppNBbRQ?preview
When using master/details, only the rows from the master grid are exported.

**Expected behavior**
The entire grid, including the details data, should be exported

* **ag-Grid version:** v20.1.0

* **Language:** [JS]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-332	[excel] export does not process Master/Detail correct
