### ISSUE TITLE
Over scrolling causes whole table temporary "unscollable"

### ISSUE THREAD

**Issue by chaosuperDK** [ag-grid/ag-grid#3003]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/?p=preview

**Current behavior**
1. Use mouse wheel scroll table to the top or bottom
2. Then keep scrolling wheel several times, and scroll to opposite immediately  
3. The table is temporary "unscrollable"
4. It will back to normal after stop scrolling

**Expected behavior**
Table scrolling should work with mouse wheel properly

**Please tell us about your environment:**
Vue 2.5.10
Chrome, v72

* **ag-Grid version:** X.X.X
ag-grid: 18.1.2
ag-grid-community: 20.1.0
ag-grid-vue: 20.1.0

* **Browser:**
Chrome, v72

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6, ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
