### ISSUE TITLE
DateComponent + reactNext={true} Cannot read property 'getDate' of undefined

### ISSUE THREAD

**Issue by v-i-n-y-a** [ag-grid/ag-grid#3004]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
I've fork your plunker and added reactNext={true} and got the same error that I see in my project:
Date Filter  couldn't get a date value from custom date input component.

ag-grid-community.js:21160 Uncaught TypeError: Cannot read property 'getDate' of undefined
    at DateFilter.serialize (VM279 ag-grid-community.js:21160)
    at DateFilter.BaseFilter.getNullableModel (VM279 ag-grid-community.js:21571)
    at eval (VM279 ag-grid-community.js:30764)
    at Promise.resolveNow (VM279 ag-grid-community.js:4562)
    at DateFloatingFilterComp.currentParentModel (VM279 ag-grid-community.js:30762)
    at DateFloatingFilterComp.onDateChanged (VM279 ag-grid-community.js:22358)
    at eval (VM279 ag-grid-community.js:41

https://plnkr.co/edit/QHioLM19ITLhdMfJ7Ibl?p=preview

**Expected behavior**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

    "ag-grid-community": "^20.1.0",
    "ag-grid-enterprise": "^20.1.0",
    "ag-grid-react": "^20.1.1",

* **Browser:**
Chrome, FF

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. This is has been raised before, and we are currently tracking already in our pipeline with the following number and description.


 AG-2749    Floating Date Filter Throws Exception with reactNext



You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket- 

Regards

Alberto‍
