### ISSUE TITLE
custom tooltip does not display in Angular Ag-grid 

### ISSUE THREAD

**Issue by liuren78** [ag-grid/ag-grid#3007]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
- A plunker
https://plnkr.co/edit/lcyzWffXHZMaIGzxaV8H?p=preview

**Current behavior**
Custom tooltips are not displayed when there are custom cellrenders and custom tooltips in ag-grid.
Remove the custom cellrenderer and display normal。

**Please tell us about your environment:**
node v10.15.2
npm 6.4.1
angular 7.2.0

* **ag-Grid version:** X.X.X
    "ag-grid-angular": "^20.1.0",
    "ag-grid-community": "^20.1.0",

* **Browser:**
chrome:72.0.3626.119

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 TypeScript 3.2.2
ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-2845 - Custom tooltips are not displayed when there are custom cellrenders and custom tooltips in ag-grid.

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket- 

Regards

Davis‍

**Comment by angelayanpan** [comment]
is this resolved or still in backlog? @makinggoodsoftware
