### ISSUE TITLE
Proposal: Add unmanaged row dragging with server side data source

### ISSUE THREAD

**Issue by NikitaIT** [ag-grid/ag-grid#3010]
# what?
need only event and control 
# why?
to do such as dragging from server side table to client side table

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2446 | Add support for unmananged row drag and drop in SSRM/Infinite row models
-- | --

**Comment by strongme** [comment]
hi, any update of row dragging in server mode?

**Comment by cnacode** [comment]
hi we need this feature too, enterprise user

**Comment by jgrayleap** [comment]
+1 LFG
