### ISSUE TITLE
"ReferenceError: event is not defined" exception on key press

### ISSUE THREAD

**Issue by RostYanevych** [ag-grid/ag-grid#3018]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
I have custom editor component. Pressing a key in the grid shows the editor. After this, the error in the console appears: `"ReferenceError: event is not defined"`.
The exception is in the line 32224 of ag-grid-community.js:
`var cellKeyDownEvent = cellComp.createEvent(event, events_1.Events.EVENT_CELL_KEY_DOWN);`
I believe, the variable name here should be the `keyboardEvent`, not the `event`

Looks like not related to this exception, but keys pressed in the popup editor do not come to the `suppressKeyboardEvent` handler, set in the `defaultColDef`. In the version 20.0.0 I was able to trap the keyboard events in that callback and check `params.editing` to know if the editing is active.

**Expected behavior**
Should be no exception.

* **ag-Grid version:** 20.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0"

* **Language:** [ES5]

**Comment by gportela85** [comment]
fixed in the latest branch by https://github.com/ag-grid/ag-grid/commit/5f51969556fc653c351350ded63a9802024de6c8
