### ISSUE TITLE
[header] Add support for cellStyle and cellClass for headers and header groups

### ISSUE THREAD

**Issue by surjikal** [ag-grid/ag-grid#302]
It would be helpful to have the ability to apply cell styles and cell classes to headers and header groups. Exactly like the `cellStyles` and `cellClass` colDef properties.

Main use case for me is, I want to color code header groups.

Properties could be:
- `headerCellStyle`
- `headerCellClass`
- `headerGroupCellStyle`
- `headerGroupCellClass`

**Comment by scotthovestadt** [comment]
+1

**Comment by randdusing** [comment]
I'm trying to hide the filter icon for certain columns and don't know how to do this without custom styles. This would be very handy.

**Comment by ceolter** [comment]
really this should be part of the future 'header component' plan

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-56

**Comment by futbolistua** [comment]
What is the progress оа this issue?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
