### ISSUE TITLE
Mistake in documentation "isAnimationFrameQueueEmpty()"

### ISSUE THREAD

**Issue by anton6** [ag-grid/ag-grid#3021]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

https://www.ag-grid.com/javascript-grid-api/

Can someone please check the documentation link above and let me know if this is a mistake:

> isAnimationFrameQueueEmpty() - Returns true if the grid has animation frames to execute.

Surely it should say: "Returns **false** if the grid has animation frames to execute." OR "Returns true if the grid has **no** animation frames to execute."

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2898 - DOCS- Misleading documentation around isAnimationFrameQueueEmpty

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
