### ISSUE TITLE
PHP error on example page

### ISSUE THREAD

**Issue by Christilut** [ag-grid/ag-grid#3022]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
There seems to a PHP error on the example on this page: https://www.ag-grid.com/javascript-grid-tree/

**Comment by makinggoodsoftware** [comment]
Hi,

We can't reproduce this, this might have been temporary, please report again if you find this issue again

Thanks
