### ISSUE TITLE
Cannot get edited values in fullRow editing without unselecting and reselecting same row

### ISSUE THREAD

**Issue by NewBo1234** [ag-grid/ag-grid#3026]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

I have a grid with fullRow editing.  I select a row, edit the data, but I cannot get the edited data without moving the selection around (firing the change events) and then selecting it again.

For example:

With the original data:
{"field1":"foo", "field2":"bar"}

I change the data to the following:
{"field1":"baz", "field2":"bat"}

I use the params.node.data and get:
{"field1":"foo", "field2":"bar"}

**Expected behavior**

I would expect some way to loop through the edited fields to get the data (going through ALL the editors) or for another field to show the new values.
**Please tell us about your environment:**

Linux, Firefox, ag-grid 20.0.0 using plain javascript

* **ag-Grid version:** X.X.X

20.0.0
* **Browser:**

Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Javascript

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
