### ISSUE TITLE
defaultColDef.type properties as a columnTypes template

### ISSUE THREAD

**Issue by Kramy** [ag-grid/ag-grid#3030]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
Currently, when i try to set a default column type, the template asociated in columnTypes with it is not getting applyed. In the documentation you says that in columnTypes property ["can specify any of the column properties available on a column"](https://www.ag-grid.com/javascript-grid-column-definitions/#default-column-definitions), so i suppose that it should work the same way it does as a normal column definition.

**Expected behavior**
Be able to fill a defaultColDef propertie through a type template.

For example:
```typescript
...
defaultColDef: {
   type: 'text'
},
columnTypes: {
    text: {
        cellRenderer: 'defaultTextRenderer',
    }
},
...
```
Result:
```typescript
...
colDef: {
    type: 'text'
    cellRenderer: 'defaultTextRenderer',
}
...
```

**Reproducible Scenario**
https://next.plnkr.co/edit/HmQz3qtd3lNXxmjo
"API E" column is not getting "agAnimateShowChangeCellRenderer" as a default renderer but type 'show'.

**Please tell us about your environment:**
Linux Mint 19.1
Visual Studio Code
NPM

* **ag-Grid version:** X.X.X
ag-grid-angular 20.0.0
ag-grid-enterprise 20.0.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.2.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2896 - columnTypes set in defaultColDef are not applied

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
