### ISSUE TITLE
Layout Thrashing by Utils.getScollbarWidth on Chome

### ISSUE THREAD

**Issue by giakki** [ag-grid/ag-grid#3033]
**I'm submitting a ...** 
```
[x] bug report
[] feature request
[] support request
```

**Current behavior**

When a grid is initialized, the function `Utils.getScrollbarWidth` is called multiple times, each time causing a forced reflow of the layout.

![ag-grid-layout-thrashing](https://user-images.githubusercontent.com/1017761/54983734-b0767300-4fad-11e9-89c0-dc484a5179ed.png)

In this Plunker forked from [the docs page](https://www.ag-grid.com/javascript-grid-resizing/) on column resizing, [https://next.plnkr.co/edit/viq4AhjKA7mI2Tkk](https://next.plnkr.co/edit/viq4AhjKA7mI2Tkk), as you press the "Show grid" button, you can see that the function is called three times.

You can see how this can become a problem as the layout complexity increases. In our application we see upwards of 1 seconds of unresponsiveness each time a grid is created.

Please note that this behavior occurs only on Chrome, while Firefox does not appear to have the same issues.

**Expected behavior**
Since the scrollbar width rarely ever changes, it would seem possible to either cache the calculated width, or let the user specify its own calculation function (see #3032, unrelated but offers the same solution).

**Please tell us about your environment:**
- Windows 10, npm, angular-cli

* **ag-Grid version:** **20.2.0**
Older versions seem to have the same issue.

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.28 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

* **Language:** TypeScript 3.2.4 | ES6/7

**Comment by smithk58** [comment]
It's not as convenient as passing your own function to them, but they do let you specify scrollbarWidth for them as a grid option. If you calculate it yourself and always pass it in as a grid option to them they probably wouldn't call their auto calculation function.

**Comment by giakki** [comment]
Thank you, you're right, I missed that option.

Unfortunately however, it looks like the function is still called by the MaxDivHeightScaler lifecycle methods: https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/rendering/maxDivHeightScaler.ts#L46, which in turn I presume is constructed each time a Grid is constructed.

**Comment by gportela85** [comment]
this issue has been fixed in the latest branch, thanks for reporting it

**Comment by giakki** [comment]
Thank you for your swift response, @gportela85.

Without opening a new issue, if it is of any help, I found the same issue in `Utils.getMaxDivHeight`: https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/utils.ts#L1208 (and `is{Vertical,Horizontal}ScrollShowing` when the scrollbars are visible, but that's just being nitpicky 😉

**Comment by gportela85** [comment]
@giakki `getMaxDivHeight` should be called just once during the gridPanel creation. If you are getting multiple calls to that method, that is probably a BUG.
We will need a new issue report and a test scenario.
