### ISSUE TITLE
Doesn't auto-scroll while selecting ranges when domLayout="autoHeight"

### ISSUE THREAD

**Issue by mbs-zanas-stundys** [ag-grid/ag-grid#3037]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
https://www.ag-grid.com/example-runner/angular.php?section=javascript-grid-width-and-height&example=auto-height&enterprise=1&noStyle=1&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A1%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3A1%7D

**Current behavior**
When setting autoHeight mode, selecting ranges that extend to the far right doesn't auto scroll.

**Expected behavior**
Should work exactly like fixed height mode.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2892 - When using autoHeight the range selection is limited to the columns in the viewport, the horizontal scroll doesn't move.

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
