### ISSUE TITLE
Table scrolls excessively with too many rows

### ISSUE THREAD

**Issue by gkjohnson** [ag-grid/ag-grid#3044]
**I'm submitting a ...** 
```
[X] bug report
[] feature request
[] support request
```

**Tested In**
Latest Chrome, Firefox
ag-grid v20.2.0
ES6

**Current behaviour**
When there are lots of rows (1,000,000+) the infinite scroll behavior does not behave as expected. Instead it scrolls many more rows than is reasonable. This seems due to numeric precision issue with the CSS-applied height of the scroll element. The issue seems worse in Firefox than it does in Chrome. Firefox seems to have precision for up to `160,000` rows while Chrome up to `1,280,000`.

**Expected behaviour**
The scroll behavior is not differentiable from a small amount of rows.

**Code Repro**
Here's a JSFiddle that shows the difference in scroll behavior between a smaller amount of rows (100,000) and a large amount of rows (75,000,000):

https://jsfiddle.net/e0ruocw4/6/

**Comment by gkjohnson** [comment]
Also I see that #1819 seems to have reported the same issue which got moved to the ag-grid issue pipeline. However I'm unable to find ticket `AG-601` so it's unclear if there was any resolution.

**Comment by gportela85** [comment]
@gkjohnson This is not a bug. The div has a height limitation that changes for each browser. For example Chrome has a limit of `33554400px` which means it could only support a scrollbar large enough for 1 million records (give or take).

For this reason, once the scroller reaches a certain height we implement a `scaler` where the scroll offsets the div a more than it normally would (this is calculated based on the number of records it contains).
So it's not erratic, but it does get more "sensitive" as you add more records.

**Comment by gkjohnson** [comment]
Hey @gportela85! Thanks for your response.

> So it's not erratic, but it does get more "sensitive" as you add more records.

You're right that wording is more correct.

I understand the reason why the issue is occurring but the current state doesn't seem like usable behavior. In my example the table scrolls 200+ rows in chrome and 1800+ in firefox when barely scrolling the mouse wheel which makes the table unusable. To the user, at least, it definitely looks like a bug.

Maybe I should rephrase my issue. The problem is specifically when using the mouse wheel to scroll. The behavior when moving the slider is acceptable because I don't think there could be any expectation of fine positioning with so many rows but it would be great if the the rows scroll a consistent amount when the mouse wheel is used regardless of quantity.

I'm less familiar with the codebase but it seems like one solution would be to maintain the scroll position with a Javascript variable and set the container scroll based on that field when it changes. If the scroll bar is used (or the scroll is changed by some other means) then the Javascript variable can be modified based on the scroll of the container. This way fine scrolling can be maintained as needed with a high precision variable but the scroll bar can still be used for coarse positioning.

Thanks again!

**Comment by gportela85** [comment]
@gkjohnson I'll reopen this and see if we get suggestions.

**Comment by gkjohnson** [comment]
@gportela85 Thanks I appreciate it.

For the moment I've added a fix that hijacks the viewport scroll event to adjust the scroll of the element in the way I've described. Here's a [fiddle demonstrating the fix](https://jsfiddle.net/m4u23yvh/) and I'll paste the general solution below. I've tested it in both Firefox and Chrome.

It's still not ideal because at 75,000,000 rows the granularity that the css height affords for scrolling is pretty coarse but it's the best I think I can do for the moment without modifying the library. With a single scroll event it's only scrolling the viewport `1 px` in order to get as close to scrolling four rows as possible. I think a more ideal solution would be positioning the rows with `translateY` based on the virtual scroll position relative to the viewport instead of relying on the browser scroll. The container spanning the total needed height would only exist for the sake of the scroll bar.

If someone can point me to the right place in the codebase to start understanding how the scroll behavior is currently working I might be able to contribute this back to the codebase. Any other suggestions would be helpful!

Here's my hack I'm using for now inside of `onGridReady`:

```js
onGridReady(grid) {
    
    // ...

    // Excessive scroll behavior fix
    var gridEl = document.getElementById('myGrid');
    var scrollEl = gridEl.querySelector('.ag-body-viewport');
    var rowsList = scrollEl.querySelector('.ag-center-cols-viewport');

    var virtualScrollAmount = 0;
    var suppressNextScrollAdjustment = false;
    scrollEl.addEventListener('scroll', function(e) {

        // back out the proper virtual scroll position if the element has been
        // scrolled manually either by a `scrollTop` adjustment or scroll bar drag
        if (suppressNextScrollAdjustment) {
        
            suppressNextScrollAdjustment = false;
        
        } else {

            var maxVirtualScroll = grid.api.rowModel.rowHeight * grid.api.rowModel.getVirtualRowCount() - scrollEl.offsetHeight;
            var scrollRatio = scrollEl.scrollTop / scrollEl.scrollHeight;
            virtualScrollAmount = maxVirtualScroll * scrollRatio;

        }

    });

    scrollEl.addEventListener('wheel', function(e) {

        // prevent the default scroll behavior from the browser
        e.preventDefault();

        // Normalize the scroll wheel speed across browsers
        var wheelDirection = e.deltaY > 0 ? 1 : -1;
        var wheelDelta = wheelDirection * 100;

        // Figure out how much scroll height there should be based on how many rows their are and what the
        // current table viewport is then scroll from there.
        var maxVirtualScroll = grid.api.rowModel.rowHeight * grid.api.rowModel.getVirtualRowCount() - scrollEl.offsetHeight;
        virtualScrollAmount = Math.min(maxVirtualScroll, virtualScrollAmount + wheelDelta);
        virtualScrollAmount = Math.max(virtualScrollAmount, 0);

        // map the new scroll position to the actual scroll height of the element.
        var scrollRatio = virtualScrollAmount / maxVirtualScroll;
        var targetElScroll = rowsList.scrollHeight * scrollRatio;
        var delta = targetElScroll - scrollEl.scrollTop;

        // ensure at least one pixel is scrolled so we don't wind up with a case of the table not
        // scrolling at all.
        var absTruncatedScrollDelta = Math.abs(Math.trunc(delta));
        var normalizedScrollDelta = Math.sign(delta) * Math.max(absTruncatedScrollDelta, 1);

        // check if we can scroll at all and if we can then adjust the elements scroll position
        // and make sure we don't adjust the virtual scroll position when the following event fires.
        var newScrollPosition = Math.min(scrollEl.scrollTop + normalizedScrollDelta, scrollEl.scrollHeight);
        if (newScrollPosition !== scrollEl.scrollTop) {

            scrollEl.scrollTop = newScrollPosition;
            suppressNextScrollAdjustment = true;
        
        }
        
    });

    // ...

}
```

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by gkjohnson** [comment]
Hi @makinggoodsoftware!

Great! Thanks for picking this up. Please feel free to reach out if you need more information on our use case or what the ideal behavior might look like. I'm happy to talk about possible implementation solutions to solve the problem, as well.

Thanks  again!

**Comment by michaelchiowong** [comment]
Hi,

I actually have a similar issue using Ag grid viewport row model. The Ag grid in browser keeps receiving updates from websocket on total row counts and new data. So, you can think that I have code as below:

params.setRowCount(newCount);
params.setRowData(newData);

This works fine. However, when the newCount reaches 1280000, the scroll bar starts jumping to around next 2000 rows. For example, if in current viewport, the firstDisplayedRow is 25000, when I call setRowCount(1300000), the firstDisplayedRow will jump to around 26500.  But this is not the behavior before 1280000, which when set new row count, the scroll bar does not move or jump by itself, and the scroll bar is still growing, and users can feel that new data is coming, and makes them very exciting and happy.

What I want is just to fix the scroll bar when I call setRowCount with number larger than 1280000. Do you have any suggestion that I can work around with it ? My version of Ag grid is version 18.1.

Thanks!

Michael.

**Comment by gkjohnson** [comment]
Here's an updated fiddle which smooths the scroll out even further by offsetting the row viewport using "position: relative" to make up coarse built-in scrolling: https://jsfiddle.net/c5mq3Ldy/3/.

**Comment by makinggoodsoftware** [comment]
This is has been raised before, and we are currently tracking already in our pipeline with the following number and description.

AG-2607
Server side row model. When trying to scroll to a particular row far away given a large number of records (<1M) the scroll movement is not precise



You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by mazinaffan** [comment]
Hi @makinggoodsoftware @gkjohnson 

has this issue been resolved?
I am currently facing this issue after upgrading from v25.3.0 to v26.2.0
