### ISSUE TITLE
processHeaderForClipboard not firing when single cell is selected

### ISSUE THREAD

**Issue by materad** [ag-grid/ag-grid#3048]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.

When grid has custom header processing for clipboard configured and single cell selection enabled, then processHeaderForClipboard event is not fired when selecting Copy With Headers from context menu for a **single cell**. When many cells are selected, it works as described in the docs. Reproduced on plnkr from [this ag-grid page](https://www.ag-grid.com/javascript-grid-clipboard/#processing-clipboard-data) (remove rowSelection attribute to enable single cell selection mode).
Expected behaviour.

processHeaderForClipboard should be fired for single cell selection in the grid.

* **ag-Grid version:** 20.20.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2900 - processHeaderForClipboard not firing when a single cell is selected when copying with headers


You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
