### ISSUE TITLE
[toolpanel] allow to 'not show' specific columns in toolpanel

### ISSUE THREAD

**Issue by ceolter** [ag-grid/ag-grid#305]
http://www.angulargrid.com/forum/showthread.php?tid=2465

**Comment by cp2587** [comment]
+1

**Comment by francescjimenez** [comment]
+1

**Comment by germatpreis** [comment]
+1

**Comment by ceolter** [comment]
+1 . . . . . i want to go nuts on the tool panel, will get to it . . . .

**Comment by hank7444** [comment]
+1

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-57

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
