### ISSUE TITLE
ToolTipField and tooltipComponentParams not displaying boolean values 'false' and number = '0'

### ISSUE THREAD

**Issue by evalaidc** [ag-grid/ag-grid#3050]
I'm submitting a ... (check one with "x")

[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
Current behavior

Tooltip is not getting displayed for boolean value false and integer value 0

Expected behavior

As we have provided tooltipField: 'seed' or price, and as it is getting displayed for price value other than 0 and "seed" other than false, it should also work for them.

Check the code in the plunk I have provided:

in ColDef
{headerName: "Price", field: "price", 
 tooltipField: 'price'},
{headerName: "Boolean", field: "seed", tooltipField: 'seed'}

And in data
{name: "Mango", type: "Fruit", price: 0, seed: false}

Open preview.
Hover over the fields of Price and Boolean column.
Values $32000, 74000, true are having the tooltip, while 0 and false are not.
What is the motivation / use case for changing the behavior?

Bug that affects all false/null values when using tooltips. The tooltip won't even initiate in agInit (in angular custom tooltip component) if the params.value of the cell is false/0/null.

Please tell us about your environment:: Windows 10 enterprise, VSCode, npm, IIS

ag-Grid version: 20.2.0, latest version, also use version 20.2.0 of ag-grid-enterprise
Browser:: Chrome & IE11
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; wbx 1.0.0; rv:11.0) like Gecko
Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by evalaidc** [comment]
A similar issue addressed in https://github.com/ag-grid/ag-grid/issues/2505 with a fix was provided, but the error is still present in the new latest version ag-grid v20.2.0.

**Comment by gportela85** [comment]
fixed in latest by https://github.com/ag-grid/ag-grid/commit/bc4a7509c12468f6677956dbc2a85445e8a89a46#diff-79f8f7ac1aa3ecbbe03cba1bf238a87c
