### ISSUE TITLE
Refused to apply inline style because it violates the following Content Security Policy

### ISSUE THREAD

**Issue by jbosse** [ag-grid/ag-grid#3056]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'
```
**Current behavior**
1. Follow the instructions on https://www.ag-grid.com/vue-getting-started/.
1. Run the sample with your CSP set to not allow inline-styles.
1. Notice 18 CSP violations in Chrome Development tools
```
utils.js:590 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('XXX'), or a nonce ('nonce-...') is required to enable inline execution.
```

**Expected behavior**
1. Follow the instructions on https://www.ag-grid.com/vue-getting-started/.
1. Run the sample with your CSP set to not allow inline-styles.
1. Notice no CSP violations in Chrome Development tools

**Please tell us about your environment:**
RoR with webpack using Vue.js

* **ag-Grid version:**
"ag-grid-community": "^20.2.0",
"ag-grid-vue": "^20.2.0",

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

* **Language:** 
ES6

The issue is code that generates DOM elements using style attributes such as `style="width: 200px; left: 0px;  "`. The proper way to set styles with CSP enabled is to set the `style` attributes in javascript `style.width = '200px'`.

**Comment by rickbergfalk** [comment]
@jbosse curious why this was closed? We're hitting this same issue trying to implement CSP and use ag-grid.

**Comment by jbosse** [comment]
Oy. It was so long ago I am not sure. My guess based on how my messed up brain works is that I thought it would be better to try to fix it and submit a PR rather than just file and issue. Then I got sidetracked by other work priorities and never fixed it.

**Comment by jbosse** [comment]
Note to future self. Always add a comment when you close and issue. 😞

**Comment by rickbergfalk** [comment]
Thanks for the quick response! I'm potentially about to go down the same path...

@rmc-software any plans to handle CSP in the future?

**Comment by jbosse** [comment]
Depending on your resources it might be easier to modify the CSP for pages containing the grids if you can accept it. Inline styles are pretty low down on the threat model for most sites.

**Comment by Sefriol** [comment]
I guess this is related to documentation: https://www.ag-grid.com/javascript-grid-security/#style-src

I wonder how big of an issue this is to fix? Some applications like Chrome WebApps have very strict CSP rules.

Personally I would get some people off my back if this was solved. ^^

Any idea @jbosse ?

**Comment by jbosse** [comment]
@Sefriol I'm sorry to say I have none. ¯\_(ツ)_/¯ Your best bet would be to fork the code and fix it yourself. In our case we simply skipped CSP on the pages we needed. They were internal admin pages so the path of least resistance won.
