### ISSUE TITLE
column groups do not expand or collapse on mobile

### ISSUE THREAD

**Issue by anishpateluk** [ag-grid/ag-grid#3057]
**I'm submitting a ...**
```
[x] bug report => see 'steps to reproduce'
```

**Steps to reproduce**
- Visit this [example](https://www.ag-grid.com/example-runner/vanilla.php?section=javascript-grid-grouping-headers&example=basic-grouping&generated=1&grid=%7B%22theme%22%3A%22ag-theme-balham%22%2C%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Anull%7D), from the ag-grid documentation, either on a mobile or with mobile emulator in chrome on your desktop 
- try to tap, on mobile, or click, in emulator, on the "sports results" column group to expand or collapse the group
- the column will not expand

**Current behavior**
The column group can be expanded or collapsed by clicking on the column group heading on a desktop browser. However, this behaviour is not possible on mobile.

**Expected behavior**
The column group should be expanded or collapsed by tapping on the column group header on mobile.

* **ag-Grid version:** 20.2.0

**Browser:**
- Chrome for Android on OnePlus 3T 
- Chrome browser, running mobile emulation in the chrome dev tools, on a macbook pro

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2851	Column group expand does not work on touch devices.
