### ISSUE TITLE
Select all checkbox is not working with filter search

### ISSUE THREAD

**Issue by sathishkanda123** [ag-grid/ag-grid#3059]
Hi ,

We recently purchased an ag-grid enterprise version for some filtering options,
We are looking for the solution in filter select all with search 
Input 
........
we need to filter the values with a search filter 

![select-all wih filter search optio](https://user-images.githubusercontent.com/17405782/55613166-a4599500-57a7-11e9-9b5e-7f8464d04617.jpeg)

Expecting Behaviour
................................
we are expecting it will filter only the searched item, with select all option.

Can you please help me, how to get this one in ag-grid

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
