### ISSUE TITLE
ng build --prod issue in new version 20.2.0

### ISSUE THREAD

**Issue by seenivasan097** [ag-grid/ag-grid#3060]
ng build --prod issue in new version 20.2.0

I am using ag grid 20.2.0 angular cli latest release. it's working fine while using command ng build.
If i use ng build --prod command it will displaying below mentioned issues. Please help me asap.

ERROR in ./node_modules/ag-grid-community/dist/lib/headerRendering/header/headerWrapperComp.js
Module not found: Error: Can't resolve '../../components/framework/componentRecipes' in 'D:\test\node_modules\ag-grid-community\dist\lib\headerRendering\header'
ERROR in ./node_modules/ag-grid-community/dist/lib/headerRendering/headerGroup/headerGroupWrapperComp.js
Module not found: Error: Can't resolve '../../components/framework/componentRecipes' in 'D:\test\node_modules\ag-grid-community\dist\lib\headerRendering\headerGroup'
ERROR in ./node_modules/ag-grid-community/dist/lib/rendering/cellRenderers/groupCellRenderer.js
Module not found: Error: Can't resolve '../cellRendererService' in 'D:\test\node_modules\ag-grid-community\dist\lib\rendering\cellRenderers'
ERROR in ./node_modules/ag-grid-community/dist/lib/filter/dateFilter.js
Module not found: Error: Can't resolve '../components/framework/componentRecipes' in 'D:\test\node_modules\ag-grid-community\dist\lib\filter'
ERROR in ./node_modules/ag-grid-community/dist/lib/gridPanel/gridPanel.js
Module not found: Error: Can't resolve '../components/framework/componentRecipes' in 'D:\test\node_modules\ag-grid-community\dist\lib\gridPanel'
ERROR in ./node_modules/ag-grid-community/dist/lib/headerRendering/headerRowComp.js
Module not found: Error: Can't resolve '../components/framework/componentRecipes' in 'D:\test\node_modules\ag-grid-community\dist\lib\headerRendering'
ERROR in ./node_modules/ag-grid-community/dist/lib/filter/filterManager.js
Module not found: Error: Can't resolve '../components/framework/componentResolver' in 'D:\test\node_modules\ag-grid-community\dist\lib\filter'
ERROR in ./node_modules/ag-grid-community/dist/lib/rendering/beans.js
Module not found: Error: Can't resolve '../components/framework/componentResolver' in 'D:\test\node_modules\ag-grid-community\dist\lib\rendering'
ERROR in ./node_modules/ag-grid-community/dist/lib/gridPanel/gridPanel.js
Module not found: Error: Can't resolve '../rendering/heightScaler' in 'D:\test\node_modules\ag-grid-community\dist\lib\gridPanel'
ERROR in ./node_modules/ag-grid-angular/dist/aggrid.module.js
Module not found: Error: Can't resolve './baseComponentFactory' in 'D:\test\node_modules\ag-grid-angular\dist'
ERROR in ./node_modules/ag-grid-angular/dist/ng2FrameworkFactory.js
Module not found: Error: Can't resolve './baseComponentFactory' in 'D:\test\node_modules\ag-grid-angular\dist'
ERROR in ./node_modules/ag-grid-community/dist/lib/rendering/beans.js
Module not found: Error: Can't resolve './cellEditorFactory' in 'D:\test\node_modules\ag-grid-community\dist\lib\rendering'
ERROR in ./node_modules/ag-grid-community/dist/lib/rendering/beans.js
Module not found: Error: Can't resolve './cellRendererService' in 'D:\test\node_modules\ag-grid-community\dist\lib\rendering'
ERROR in ./node_modules/ag-grid-community/dist/lib/grid.js
Module not found: Error: Can't resolve './components/framework/componentProvider' in 'D:\test\node_modules\ag-grid-community\dist\lib'
ERROR in ./node_modules/ag-grid-community/dist/lib/grid.js
Module not found: Error: Can't resolve './components/framework/componentRecipes' in 'D:\test\node_modules\ag-grid-community\dist\lib'
ERROR in ./node_modules/ag-grid-community/dist/lib/grid.js
Module not found: Error: Can't resolve './components/framework/componentResolver' in 'D:\test\node_modules\ag-grid-community\dist\lib'
ERROR in ./node_modules/ag-grid-community/main.js
Module not found: Error: Can't resolve './dist/lib/components/framework/componentProvider' in 'D:\test\node_modules\ag-grid-community'
ERROR in ./node_modules/ag-grid-community/main.js
Module not found: Error: Can't resolve './dist/lib/components/framework/componentResolver' in 'D:\test\node_modules\ag-grid-community'
ERROR in ./node_modules/ag-grid-enterprise/main.js
Module not found: Error: Can't resolve './dist/lib/pivotCompFactory' in 'D:\test\node_modules\ag-grid-enterprise'
ERROR in ./node_modules/ag-grid-community/main.js
Module not found: Error: Can't resolve './dist/lib/rendering/cellEditorFactory' in 'D:\test\node_modules\ag-grid-community'
ERROR in ./node_modules/ag-grid-community/main.js
Module not found: Error: Can't resolve './dist/lib/rendering/cellRendererService' in 'D:\test\node_modules\ag-grid-community'
ERROR in ./node_modules/ag-grid-enterprise/main.js
Module not found: Error: Can't resolve './dist/lib/rowGroupCompFactory' in 'D:\test\node_modules\ag-grid-enterprise'
ERROR in ./node_modules/ag-grid-community/dist/lib/rendering/rowRenderer.js
Module not found: Error: Can't resolve './heightScaler' in 'D:\test\node_modules\ag-grid-community\dist\lib\rendering'
ERROR in ./node_modules/ag-grid-community/dist/lib/rendering/beans.js
Module not found: Error: Can't resolve './heightScaler' in 'D:\test\node_modules\ag-grid-community\dist\lib\rendering'
ERROR in ./node_modules/ag-grid-angular/dist/aggrid.module.js
Module not found: Error: Can't resolve './ng2ComponentFactory' in 'D:\test\node_modules\ag-grid-angular\dist'
ERROR in ./node_modules/ag-grid-community/dist/lib/gridApi.js
Module not found: Error: Can't resolve './rendering/cellEditorFactory' in 'D:\test\node_modules\ag-grid-community\dist\lib'
ERROR in ./node_modules/ag-grid-community/dist/lib/grid.js
Module not found: Error: Can't resolve './rendering/cellEditorFactory' in 'D:\test\node_modules\ag-grid-community\dist\lib'
ERROR in ./node_modules/ag-grid-community/dist/lib/grid.js
Module not found: Error: Can't resolve './rendering/cellRendererService' in 'D:\test\node_modules\ag-grid-community\dist\lib'
ERROR in ./node_modules/ag-grid-community/dist/lib/grid.js
Module not found: Error: Can't resolve './rendering/heightScaler' in 'D:\test\node_modules\ag-grid-community\dist\lib'

**Comment by seanlandsman** [comment]
If you use https://github.com/ag-grid/ag-grid-angular-cli-example and the "build" command will run with --prod

Do you have a repro of this issue that we can use to investigate?

**Comment by seenivasan097** [comment]
Uninstall old ag-grid npm modules packages and install new version it will work:):):)

**Comment by sandeep-chintala** [comment]
Still issue exists. Does ag-grid 21.0.1 version supports angular 6?
When I run application using 'ng serve', it is working fine. but when I run command 'ng build --prod -c prod', I am getting above issue

**Comment by hubdncajh** [comment]
[#8063 ]  in next js build. not solved this issue
