### ISSUE TITLE
suppressMenuHide with custom headerComponentParams.template crashes grid. - Uncaught TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by eddieferrer** [ag-grid/ag-grid#3063]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
If grid option suppressMenuHide: true, and a column has a headerComponentParams.template which does not include the ref eMenu, the grid refuses to load. 

Plunker with Error: 
https://plnkr.co/edit/9Ez9eON7YAfDkA6mmSIJ?p=preview

Plunker that works: 
https://plnkr.co/edit/ZMUx2f93RXbWpTYykjHq?p=preview

**Expected behavior**
gridOption suppressMenuHide: true should allow for headerComponentParam templates that do not include a ref to the eMenu. 

* **ag-Grid version:** X.X.X
ag-grid-community@20.2.0
ag-grid-enterprise@20.1.0

* **Browser:**
Chrome 73.0.3683.86

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-2901 - suppressMenuHide: true and custom headerComponentParams.template without the ref eMenu causes the grid to crash


You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
