### ISSUE TITLE
Shift+Tab key not working properly for Floating Filter Input

### ISSUE THREAD

**Issue by hassannaseem** [ag-grid/ag-grid#3068]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Enable the floatingFilter for the Ag-Grid
- Make sure you have enough columns in the table to have horizontal scroll.
- Focus in one of the Floating Filter input field and start pressing tab key. This works fine and scroll automatically moves with the new column created on the fly.
- Now start pressing the shift+tab key this doesn't make the horizontal scroll to scroll back and the focus is lost.

**Current behavior**
Focus is lost on shift+tab key.

**Expected behavior**
The focus should go to the previous floating filter input and the scroll should move.

**Please tell us about your environment:**
Window 10

* **ag-Grid version:** 20.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
Filters | AG-1334 | Allow tab key follow the correct order when tabbing in and out of floating filters
-- | -- | --
