### ISSUE TITLE
Export to Excel - Crash with 10k+ rows

### ISSUE THREAD

**Issue by mjfee** [ag-grid/ag-grid#3076]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
App crashes when exporting 18000 rows to excel. Both when calling _exportDataAsExcel() or getData() and packageFile() sequentially. Export mode is xlsx.

**Expected behavior**
Xlsx created without issues.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, Electron.

* **ag-Grid version:** X.X.X
20.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

                        data = this.currentGrid.options.api.excelCreator.getData(excelParams);
                        data = this.currentGrid.options.api.excelCreator.packageFile(data);   

OR
                        this.currentGrid.options.api.exportDataAsExcel(excelParams);

**Comment by gportela85** [comment]
There is a browser limitation on how much data you can process before it crashes.
If you go to www.ag-grid.com, load the DEMO, set it to 50k rows with 22 columns, open your browser's console and type `gridOptions.api.exportDataAsExcel()` it should work fine.

If you do do the same in your project and the browser crashes with the "Out of memory" error. I'm afraid you will have to resort to exporting to Excel using a backend solution.

**Comment by mjfee** [comment]
So then rows is not the limiting factor. The upgrade to v 20 was advertised as fixing our previously seen performance issue, and it has not. 

What metric can we use for determining what is too much for the api functions to handle? Is there an attribute on the grid we can check?

**Comment by hopeng** [comment]
I ended up using [xlsx-js-style](https://github.com/gitbrent/xlsx-js-style) to create excel file by transforming ag-grid's filtered node data. And it also supports styling. I'm able to do 50k rows with 90MB file size without crashing. 

Maybe ag-grid can see where it can be improved with export? why a free 3rd party lib can do it better?
