### ISSUE TITLE
Dragging columns off grid shows disabled icon when suppressDragLeaveHidesColumns set to true

### ISSUE THREAD

**Issue by kerbs17** [ag-grid/ag-grid#3080]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Create a grid with the following grid option: `suppressDragLeaveHidesColumns: true`
- Example Plunker: https://plnkr.co/edit/1BFHGY4QLnWL4TnGTQFH?p=preview

**Current behavior**
When you drag a column outside of the grid, the column title shows with disable icon.

**Expected behavior**
When the column is dragged outside of the grid, just the title of the column should show since we have suppressed the features to hide the column if we drag outside the grid.

**Please tell us about your environment:**
Reproducible on multiple browsers and Operating Systems

* **ag-Grid version:** 20.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2956 - When using suppressDragLeaveHidesColumns and dragging a column outside the viewport, don't show the hide icon on the ghost as it is missleading
