### ISSUE TITLE
cellRendererSelector does not refresh after cell edit changes when used in dynamic situations

### ISSUE THREAD

**Issue by JLuitjens** [ag-grid/ag-grid#3086]
Based on these examples,

https://next.plnkr.co/edit/ZYoSeMKb5VfxCfMy
https://www.ag-grid.com/javascript-grid-cell-rendering/  

Setting Type column to editable and changing value, how does one refresh cellRendererSelector appropriately, figured it would be triggered after any cellEdits/even updateRow ? Unless I'm missing something from the documentation, not sure other than creating a different component to handle these scenarios.

1. Modify a rows type to another
2. The cellRendererSelector used does not reflect this change
https://next.plnkr.co/edit/LjdlGupWkbWvdl7L  

**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**
cellRendererSelector does not refresh after agGrid row modifications  
1. Edit Type
2. cellRendererSelector component not updated

**Expected behavior**
cellRendererSelector should refresh its logic after cell editing.  
1. Edit Type
2. cellRendererSelector component updates to reflect proper component required by type change

* **ag-Grid version:** 20.2.0 @ plunkr

**Comment by jiangyh1024** [comment]
@JLuitjens  you can call event.api.redrawRows({ rowNodes: [yourNode] })

**Comment by JLuitjens** [comment]
@jiangyh1024 of course... thanks, must of been tired as I was using refreshCells 🗡
