### ISSUE TITLE
0 rowBuffer key navigation exception

### ISSUE THREAD

**Issue by jackbromley** [ag-grid/ag-grid#3087]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
Where rowBuffer is set to 0, use of keyboard navigation will cause an exception.

In order to reproduce:
1. Goto https://plnkr.co/edit/Xiu335ICU2euktwUdMxd?p=preview
2. Click on a cell.
3. Press and hold down until the grid starts to scroll down.
4. Press and hold up.

**Expected behavior**
It should not throw.

* **ag-Grid version:** 20.2.0

**Comment by gportela85** [comment]
Fixed in the latest branch. Thanks for reporting the issue
