### ISSUE TITLE
Please stop releasing breaking changes in minor versions

### ISSUE THREAD

**Issue by MatthewHerbst** [ag-grid/ag-grid#3093]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

We are a paying Enterprise customer of ag-grid.

**Current behavior**
The ag-grid team releases breaking changes while only changing the semver minor version.

**Expected behavior**
The ag-grid team only releases breaking changes when publishing a new semver major version.

At the very least, if no change will be made, documentation should be added to very clearly state that the package does not follow semver. The release notes are not good enough - not everyone will read them.

**Comment by mbaranovski** [comment]
Could not agree more.

**Comment by makinggoodsoftware** [comment]
Hi,

We do our best to minimize breaking changes on minor versions, I would suggest if you are an enterprise customer to raise each issue you find in zendesk so we can help you with it.

If you are not a customer, you can always raise your issues here, note that we process github only from time to time and we require very concise cases with reproducible scenarios in github.

That being said, is there anything in particular that has caused any major breaking changes in a minor release?

Above all, sorry for any inconvenience, if this has happened, as I said the best thing to do is to come to us for help in these cases

Thanks

**Comment by MatthewHerbst** [comment]
@makinggoodsoftware There should be **NO** breaking changes in semver minor versions, _ever_.

When you `npm install --save ag-grid-community ag-grid-enterprise ag-grid-react` it gives the following entries in `package.json`:

```json
"ag-grid-community": "^20.2.0",
"ag-grid-enterprise": "^20.2.0",
"ag-grid-react": "^20.2.0",
```

The `^` means that you should accept any `20.x.x` version that is greater than or equal to `20.2.0`. So, if if you release version `20.3.0` and I re-run `npm install`, my installer will install `20.3.0`, not `20.2.0`.

I should be able to blindly accept non-breaking semver versions without even having to read the patch notes (of course I do, but the whole point of semver is that I shouldn't have to).

For your reference, [here at the semver docs](https://semver.org/). The first thing stated is:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by makinggoodsoftware** [comment]
Hi,

We do understand how semver works, and as I said, we try to not introduce breaking changes in minor releases, but sometimes we do unintentionally.

I'll close this ticket as I think we are going in circles, note that we understand your frustation if it just so happens that you were affected by this, but note that you can always reach out to us for help, specially if you are a pyaing customer, and we will do everything in our hand to help.

Hope this makes sense.

Please feel free to contact us thought if you would still like to discuss this issue with us, I would recommend you to use our customer portal though

https://ag-grid.zendesk.com/

Thanks
