### ISSUE TITLE
Cell editors using Hooks

### ISSUE THREAD

**Issue by ludvigeriksson** [ag-grid/ag-grid#3094]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

How do I use a Cell Editor written with Hooks? The documentation states that the class component should have a method `getValue`. What is the equivalent of this if the editor is a function component, not a class component?

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2917 | SPIKE - Investigate extending ag-grid-react to support hooks with editors/filters etc
-- | --
