### ISSUE TITLE
[Bug] minWidth, maxWidth column props don't work.

### ISSUE THREAD

**Issue by rkhramiankou** [ag-grid/ag-grid#3099]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Here a simple forked plunker. I've tried to set width and min width, only min width.
https://plnkr.co/edit/Z8eByiprVG8vQf6VQ0jL?p=preview
Looks like initial width calculation doesn't treat colDef props and look at global gridOptions.minColWidth or constant value;
https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/columnController/columnUtils.ts#L16

**Current behavior**
No min and max column width applied.

**Expected behavior**
Should check min width on initialization and preset from column definition; Not sure but may be also set up css styles;

**Please tell us about your environment:**
Win 10, VS Code

* **ag-Grid version:** X.X.X
ag-grid-community 20.2.0 + ag-grid-enterprise 20.2.0

* **Browser:**
Latest Google Chrome

* **Language:** [TypeScript 3.4]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by mbokil** [comment]
Tested this issue on macOS with Firefox and Chrome. ag-grid-community 20.2.0. maxWidth, minWidth fails to set width on columns.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2960 - When minWidth > width show warning in console and increase width to minWidth
