### ISSUE TITLE
Using "sizeColumnsToFit" with infinite scroll row model

### ISSUE THREAD

**Issue by chat-du-cheshire** [ag-grid/ag-grid#3100]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[*] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
Hi, may be somebody know how to use api.sizeColumnsToFit() with infinite rows model? I tried to debug this method, it looks like working properly, but when I use it in (gridReady) or (firstDataRendered) events rows still not in DOM, so that method counts column sizes without possible vertical scroll bar what leads to unnecessary horizontal scroll bar.

**Providing a Reproducible Scenario**
The [repo](https://github.com/chat-du-cheshire/ngx-grid-test) with scenario.
`npm i`
`npm backend`
`npm start`
After all [page](http://localhost:4201/movies/ag-grid)

**Current behavior**
Current behaviour is horizontal scroll after "sizeColumnsToFit".

**Expected behavior**
No horizontal scroll

* **ag-Grid version:**
"ag-grid-angular": "^20.2.0",
"ag-grid-community": "^20.2.0",

* **Browser:**
Chrome

* **Language:** TypeScript 3.1.1

Thanks in advance for support

**Comment by chat-du-cheshire** [comment]
I found workaround. Call sizeColumnsToFit in getRows after params.successCallback function, but maybe better solution exists

**Comment by jiangyh1024** [comment]
@chat-du-cheshire

hi, I encountered this problem too, you solution did solve the problem, but the demo doesn't have the problem. Don't know why
https://www.ag-grid.com/example-runner/grid-react.php?section=javascript-grid-infinite-scrolling&example=simple&generated=1&infinite=1&grid=%7B%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Anull%7D

**Comment by chat-du-cheshire** [comment]
@jiangyh1024 hi, unfortunately I didn't find the answer on this question =)
