### ISSUE TITLE
Floating rows move when there is a large amount of rows

### ISSUE THREAD

**Issue by steven509** [ag-grid/ag-grid#3106]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/fHb3xxuzY97obwWi8rtF?p=preview

**Current behavior**
1. Create grid with floating row (top or bottom)
2. Create a datasource (any type), and return the row count as a high number. Over 2 million in Chrome or over 150k in Firefox.
3. Scroll in the grid and the content of the floating row will scroll.

**Expected behavior**
1. Content of the floating rows should not scroll when the grid is scrolled

I've tracked down the issue to only happen once scaling becomes enabled. 

* **ag-Grid version:** 20.1.0

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email.

Given your description, we would suggest that you take the following approach.

We have modified your plunker:

https://plnkr.co/edit/jMZqmFsXww8ydwJYCmTb?p=preview

Hope this helps

**Comment by steven509** [comment]
Thank you for your response, this is the solution we ended up going with.

There is a slight error in your plunker though, on line 53 you have 
`params.successCallback(rowsThisPage, 1000);`
when it should be
`params.successCallback(rowsThisPage, lastRow);`
