### ISSUE TITLE
cannot tab through a column with span > 1

### ISSUE THREAD

**Issue by gforceg** [ag-grid/ag-grid#3110]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

If the selected cell has a colspan > 1, it is not possible to tab to the next cell.

You can reproduce this on [the Official ag-grid col span example](https://www.ag-grid.com/javascript-grid-column-spanning/#column-spanning-simple-example)

The user cannot tab to the next cell from the Country column, but they can shift + tab to the previous cell.

![no-tab-in-col-span-ag-grid](https://user-images.githubusercontent.com/14267747/56980015-7eba7400-6b38-11e9-9d2b-247a55241ad9.gif)

**Expected behavior**

The tab functionality should be identical to cells that have a colspan of 1

**Please tell us about your environment:**

Windows 10
VS Code
npm
* **ag-Grid version:** 20.2.0

* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"

* **Language:** ES6

**Comment by gforceg** [comment]
Maybe it's in here somewhere: https://github.com/ag-grid/ag-grid/blob/714ced17a4e62f52d319792670d4e0240afe1145/packages/ag-grid-community/src/ts/cellNavigationService.ts#L259

**Comment by gforceg** [comment]
Could reuse this bit of code to fix the issue: https://github.com/ag-grid/ag-grid/blob/714ced17a4e62f52d319792670d4e0240afe1145/packages/ag-grid-community/src/ts/rendering/rowRenderer.ts#L994

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by gforceg** [comment]
@makinggoodsoftware I am using a custom version of ag-grid-community that includes PR #3112 for the time being. (508 compliance is important to my org) It works as expected. Feel free to merge if the changes are up to your quality standards.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2957 - Tab doesn't work when combined with colSpan
