### ISSUE TITLE
React hooks icw property callbacks are caching values

### ISSUE THREAD

**Issue by BartJanvanAssen** [ag-grid/ag-grid#3114]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Isolated Sandbox:  https://codesandbox.io/embed/oooj0v1o0q
Bug: with using react hooks, with the useState hook we encounter a cached value bug.
Steps to repoduce:
1. open sandbox
2. click 5 times on the button [see the number go to 5]
3. double click a cell to inline edit + change the text + press enter
4. [BUG] we see state is been reset to 1, which is the state from the callback +1. 

Our guess is that the state is been cached too strong in an outer scope. So whenever the callback prop, "onCellValueChanged" form the columnDefs changes, by a up following render, the construction value of that callback / defs is being used. that causes the state to be 0.

**Current behavior**
The state gets updated with an value that is cached inside the callback

**Expected behavior**
the callback should have updated (carrying the new state value) by a follow up render (setstate by the button click) 

**Please tell us about your environment:**
React SPA

* **ag-Grid version:** X.X.X
newest

* **Browser:**
chrome

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by BartJanvanAssen** [comment]
any suggestions yet? takes quite long... our company is awaiting :) @makinggoodsoftware

**Comment by makinggoodsoftware** [comment]
Our consultants have put together the following example for you
https://codesandbox.io/embed/znjv5ly4xl?fontsize=14


Hope this helps.

**Comment by BartJanvanAssen** [comment]
works thanks 👍

**Comment by pradhumn17** [comment]
But again the question is why we need to use previous state to update the value. Why it does not update directly?
Is there any concept we are missing. Please let me know. It would be a great help.
