### ISSUE TITLE
Feature: Possibility to set total amount of pages, related to #2315

### ISSUE THREAD

**Issue by xiaomutoun123** [ag-grid/ag-grid#3132]
Hello, 

It's a feature request related to #2315. In fact, I found the answer not pertinent. 

The answer in the end is: 

"""
To specify how many pages, you need to do so by leveraging the getRows callback from your datasouce.
ie
https://www.ag-grid.com/javascript-grid-infinite-scrolling/#setting-last-row-index
"""

But in my notice of ag-grid, it says: 
ag-Grid: you can only use a datasource when gridOptions.rowModelType is 'infinite'

So, in the case when I am not using an infinite row model, I can't specify the total row count.

The ag-grid version I am using is "ag-grid-enterprise": "^14.2.0".

Please look at this issue, thanks in advance.

**Comment by ZiedHf** [comment]
Hi,
Well, I don't know if this would help you.
But I was able to change the total number of rows using rowModelType as _serverSide_ with the onGridReady method :

onGridReady = params => {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    const that = this;
    setTimeout(() => {
      const datasource = {
        getRows(params) {
          params.successCallback(that.state.data, that.state.total);
        }
      };
      this.gridApi.setServerSideDatasource(datasource);
    }, 1000);
  };

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
