### ISSUE TITLE
BUG: this.gridApi.paginationSetPageSize broken using 'infinite' row model

### ISSUE THREAD

**Issue by jpike88** [ag-grid/ag-grid#3140]
**I'm submitting a ...**  (check one with "x")
- [x] bug report

I'm not an enterprise customer, but I don't intend on ever being one with a bug like this present. It's got to be either a bug, or poor design/documentation.

After days of painful struggle, I've realised that the examples you provide in your own documentation don't work as expected.

**Current behavior**
Your documentation mentions how page size can be changed here:
https://www.ag-grid.com/javascript-grid-pagination/#customising-pagination

You have two examples for pagination with infinite scrolling here:
https://www.ag-grid.com/javascript-grid-infinite-scrolling/#example-1-auto-pagination-page-size-large-infinite-block-size
https://www.ag-grid.com/javascript-grid-infinite-scrolling/#example-2-equal-pagination-page-size-and-large-infinite-block-si

I took the two examples of infinite + pagination, and simply added this code to plunkers of the above two examples, which came from the top link about page size:

html
```
<div class="test-header">
        Page Size:
        <select (change)="onPageSizeChanged()" id="page-size">
          <option value="10" selected="">10</option>
          <option value="100">100</option>
          <option value="500">500</option>
          <option value="1000">1000</option>
        </select>
      </div>
```

js
```
  onPageSizeChanged(newPageSize) {
    var value = document.getElementById("page-size").value;
    this.gridApi.paginationSetPageSize(Number(value));
  }
```

I have plunkers forked of the two example above, with the above code in it.
https://next.plnkr.co/edit/Z9jb3sKmrKWaju6P
https://next.plnkr.co/edit/o8BDNHcEMtrZoenl

In both examples paginationPageSize has been initialised as 10. Therefore, I expect 10 results per page, and want only 10 to be loaded at any given time. My rows contain a lot of data per row on download, and I don't want to cache more than I have to.

In both examples, changing the pagination selector results in strange behaviour.
https://next.plnkr.co/edit/Z9jb3sKmrKWaju6P
^ setting page size to 100/500 etc doesn't do anything. I still see '1 to 19' at the bottom.

https://next.plnkr.co/edit/o8BDNHcEMtrZoenl
^ setting page size to 100/500 just breaks the hell out of the page.

https://next.plnkr.co/edit/ogsPlj9Fk2DWf35f
^ this is closest I can get it to what SHOULD work, I've tweaked values on lines 163, 165 and 166, and modified my onPageSizeChanged method to attempt to reset the cacheBlockSize.

```
  onPageSizeChanged(newPageSize) {
    var value = document.getElementById("page-size").value;
    this.cacheBlockSize = Number(value);
    this.gridApi.paginationSetPageSize(Number(value));
  }
```

So a clear issue here: cacheBlockSize does NOT change when I attempt to set it on this, so the binding is either broken or ignored after initialisation. Yet there doesn't appear to be a way to set it on this.gridApi.

Please don't close the issue just because I'm not an enterprise customer, this looks like a pretty serious issue, and I need to resolve it somehow to even use this library.

If for some reason this is all working as designed (hopefully not), I need a CLEAR example in your documentation on how to use infinite scrolling with conservative caching to proceed. The API is complex and not straightforward, I feel like I have to pull some magic combination of levers here.

**Please tell us about your environment:**
macOS

* **ag-Grid version:** X.X.X
Whatever your examples use

* **Browser:**
Any

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG‌-2225 Allow changing cacheBlockSize dynamically (either via API or making it a reactive property)

**Comment by Maximaximum** [comment]
For some reason, AG‌-2225 is marked as a React issue, but it is relevant for Angular as well (and the OP's issue seems to be using Angular)

**Comment by teverestek** [comment]
Hi,
May i know the status of AG‌-2225?

**Comment by gzamann** [comment]
@teverestek It is still under backlog
