### ISSUE TITLE
filter doesn't work with server side row model

### ISSUE THREAD

**Issue by wangran** [ag-grid/ag-grid#3149]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
when rowModelType="serverSide", the filter doesn't work well. whatever filter is added, the filter component will be reset to blank

**Expected behavior**
the filter under server side row model should behave the same as client row model

**Please tell us about your environment:**

* **ag-Grid version:** 20.2.0

* **Browser:**
chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by keenjus** [comment]
'serverSide' rowModel means that the server should filter/sort the data...

I found that this helps for the filter resetting itself (most likely a text filter), 
```
filterParams: {
  newRowsAction: 'keep',
}
```

**Comment by wangran** [comment]
> 'serverSide' rowModel means that the server should filter/sort the data...
> 
> I found that this helps for the filter resetting itself (most likely a text filter),
> 
> ```
> filterParams: {
>   newRowsAction: 'keep',
> }
> ```

Thanks a lot! It's exactly what I need. And it applies to other filter types as well.
