### ISSUE TITLE
Unable to move group column when hiding columns

### ISSUE THREAD

**Issue by Lirons10** [ag-grid/ag-grid#3150]
**I'm submitting a bug report => see 'Providing a Reproducible Scenario'

I'm using ag-grid with group columns. I have problem to manually move group columns when there is a hidden column in one of the groups.

Here's a plunker demo with full example: 
https://plnkr.co/edit/jjeDCsswWT0BnPwGGtjU?p=preview

**Current behaviour**
In the example, the Athlete column is hidden. After dragging the "Athlete Results" group column to the right, it's not possible to drag the "Sports Results" group column to the right. Once removing the hide = true from the Athlete column it works fine.

**Expected behavior**
When one of the columns are hidden all group columns can be moved.

* **ag-Grid version:** X.X.X
18.0.1

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Javascript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:




AG-3014 - Unable to move column group that contains a hidden column
