### ISSUE TITLE
Data reverting to initial in React component with refresh method in reactNext mode

### ISSUE THREAD

**Issue by BenGladman** [ag-grid/ag-grid#3154]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[ ] support request => see 'Requesting Community Support'
```

**Current behavior**

Reproduction case: https://plnkr.co/edit/RuRij5A2gGLWff3Fk8zJ?p=preview
Or: https://codepen.io/BenGladman/pen/VOBxyN?editors=0010

The bug manifests in the following situation:
- `reactNext` is set on grid component
- using `deltaRowDataMode`
- the cell framework component has a `refresh` method defined
- there is a reasonably large amount of data in grid
- a new row is inserted at start
- data on inserted row is changed
- a second new row is inserted at start

When the first new row is moved down, the data on the row reverts to what it was initially

On the reproduction case, you can see the issue by:
- click the 'add new' button (grid shows new row 101 at top)
- then clicking 'change row 101' (data on row 101 changes to 'New Data 101*')
- then click 'add new' button again (grid shows new row 102 at top, data on row 101 loses the '*' at end) 

**Expected behavior**

the data on the initial inserted row should not revert

**Please tell us about your environment:**

Windows; vscode; npm; webpack-dev-server

* **ag-Grid version:** 20.2.0

* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-3082 - When using reactNext and functional renderers. The renderers stop working
