### ISSUE TITLE
AgGrid 20.2.0 + Angular 8.0.0 + Ivy renderer fails for production builds

### ISSUE THREAD

**Issue by rdunce** [ag-grid/ag-grid#3159]
**I'm submitting a ...**  
```
[x] bug report
[] feature request
[] support request
```

**Current behavior**
Using Ag Grid in Angular 8 with Ivy renderer turned on causes a production (--prod) build to fail. Dev builds are fine.

```
Time: 40713ms
chunk {0} runtime-es5.741402d1d47331ce975c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es5.4af9b61479361f268d39.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills-es5.827748167125a43ef247.js (polyfills) 68 kB [initial] [rendered]
chunk {3} styles.6d5b4213f05568ced35c.css (styles) 291 kB [initial] [rendered]

ERROR in There is no format with import statements in 'C:/[app root]/node_mod
ules/ag-grid-angular' entry-point.

```
**Reproduce**
Check out the ag-grid-angular-cli-example.
It will build fine until you add this to tsconfig.app.json
```
  "angularCompilerOptions": {
    "enableIvy": true
  },

```
It will fail with the same error as in our app.

```
Time: 28681ms
chunk {0} runtime-es5.741402d1d47331ce975c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es5.4af9b61479361f268d39.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills-es5.827748167125a43ef247.js (polyfills) 68 kB [initial][rendered]
chunk {3} styles.804a4c792796df7bf914.css (styles) 263 kB [initial] [rendered]

ERROR in There is no format with import statements in 'C:/[snip]/ag-grid-angular-cli-example-master/node_modules/ag-grid-angular' entry-point.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ag-grid-angular-cli-example@20.2.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ag-grid-angular-cli-example@20.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Please tell us about your environment:**
Windows 10, Angular 8.0.0 + Ivy Renderer, Node 10.15.3, NPM 6.9.0

* **ag-Grid version:** 20.2.0

* **Language:** TypeScript 3.4.5

**Comment by MicMicMon** [comment]
Don't know if it's relevant here, but I saw on update.angular.io that they request nodejs version >= 12. Do you have the same behaviour with node 12?

**Comment by MicMicMon** [comment]
I confirm, same error for me.

**Comment by MicMicMon** [comment]
Seems to solved soon at `compiler-cli` level here : https://github.com/angular/angular/issues/29564

**Comment by rdunce** [comment]
Ahh, excellent news that it is being fixed upstream. Thanks @MicMicMon. I

**Comment by MicMicMon** [comment]
I think the issue should stay open until the fix is confirmed, what do you think? That may still require some adjustement on the ag-grid side.

**Comment by jack1232** [comment]
As discussed in [angular/angular#29564](https://github.com/angular/angular/issues/29564), the author of AgGrid needs to re-package AgGrid using [ng-packagr](https://github.com/ng-packagr/ng-packagr), so it can be compatible to Angular 8 Ivy.

**Comment by rdunce** [comment]
The problem appears to be fixed upstream in angular/core next. Tested with ag-grid-angular-cli-example with angular next (ng update @angular/core --next) and it compiles.

The example throws an exception at runtime but that's a separate issue.

**Comment by gtamas** [comment]
Well I have stable Angular 8 and it doesn't work with ag-grid-angular 20.1.0. I'm getting the error mentioned above. 

I have Angular 8.0.1 and CLI 8.0.3.

Should I upgrade to ag-grid 21??

**Comment by Bogdan0205** [comment]
> Well I have stable Angular 8 and it doesn't work with ag-grid-angular 20.1.0. I'm getting the error mentioned above.
> 
> I have Angular 8.0.1 and CLI 8.0.3.
> 
> Should I upgrade to ag-grid 21??

Still not fixed in 21.0.1

**Comment by fishgills** [comment]
We're an enterprise customer... could use this! It's the only thing preventing us from trying out Ivy in our product.

**Comment by seanlandsman** [comment]
This is an issue on the Angular side - see this comment from the related Angular CLI issue: https://github.com/angular/angular/issues/29564#issuecomment-486957461

If you want to try Ivy with ag-Grid you'll need to reference `@angular/compiler-cli@next`
