### ISSUE TITLE
row autoHeight doesn't work when using a Cell Renderer

### ISSUE THREAD

**Issue by areisle** [ag-grid/ag-grid#3160]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
if you comment out  `cellRenderer` on the column definition, autoHeight works as excepted
https://embed.plnkr.co/d0dELGfRax8UPEJ8ujTu/

**Current behavior**
autoHeight seems to be ignored when the cell renderer is set

**Expected behavior**
autoHeight to be applied

**Please tell us about your environment:**

* Operating system: CentoOS Linux 7

* **ag-Grid version:** 20.2.0

* **Browser:** Chrome 72

* **Language:** all

**Comment by CorreyL** [comment]
From @areisle's plunker:

https://embed.plnkr.co/d0dELGfRax8UPEJ8ujTu/

## When `cellRenderer` is defined in `columnDefs[0]`:

![image](https://user-images.githubusercontent.com/16601729/58583939-f8ae4d80-8209-11e9-8f01-d7f5d7b1bd65.png)

## When `cellRenderer` is not defined in `columnDefs[0]` (i.e. commented out, per the suggestion):
![image](https://user-images.githubusercontent.com/16601729/58584028-30b59080-820a-11e9-8760-6e9018876fb7.png)

Notice how in the second screenshot, the remainder of the text in the first row is no longer obscured, as it is in the first screenshot.

**Comment by thielmal** [comment]
I'm having the same problem. The autoHeight calculation seems to never use the cellRenderer when creating the dummy elements to measure height.

**Comment by heianqishizhisuiyuan** [comment]
you call use api.resetRowHeights() to reset the table of height

**Comment by areisle** [comment]
@heianqishizhisuiyuan that only works if I call it every time I update the any of the data in the table which is not ideal. I've made a fork of the plnkr illustrating this https://next.plnkr.co/plunk/jqJ8pzU1rMrRl7vh

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3068 | cellRenderer + autoHeight not working in the latest version

**Comment by MattKunze** [comment]
This seems to be fixed in the latest release (21.1.0) if you are using `cellRenderer` as described above. However, we're using `cellRendererFramework` to render things with React and it's not auto sizing the content in that case.

**Comment by areisle** [comment]
I saw the ticket was added to the v21 release so I updated the dependencies in the plunkr and unfortunately it seems whatever was changed didn't fix this issue as this still isn't working in v21.1.0 https://embed.plnkr.co/rFy43whVrSIguf4Taaac/

**Comment by aaronhudon** [comment]
I am using 21.2.2 and the behavior is inconsistent.
Some cells will make the row the correct height, while other rows stay at a default height clipping the cell content.

**Comment by DarkKnight1992** [comment]
not sure if you guy are aware of this but it doesn't work on v22, i created a plunker to demonstrate this

https://next.plnkr.co/edit/iSfcgJH7oIxqd1QY

![image](https://user-images.githubusercontent.com/15063261/69481052-ad30d100-0e33-11ea-88f7-6571709d3564.png)


the second one has custom rendered but it won't use autoheight at ll

**Comment by JDilleen** [comment]
@makinggoodsoftware - Is there any update on this? Having this issue and need to rely heavily on cellRenderer's throughout my teams use of the grid.

**Comment by omnibrain** [comment]
Facing the same problem. Worked with v21

**Comment by AmareshB** [comment]
@areisle and others, any workarounds for this?

**Comment by omnibrain** [comment]
I had to downgrade to v21, which has other problems 😕

**Comment by Redemin** [comment]
> @areisle and others, any workarounds for this?

I managed  to make it work by adding this code and calling the `setHeightOfVisibleRows()` method inside the ag-grid events that changed the rows of the grid. This was done with AngularJS but it shouldn't be a problem converting it to the language you are currently using.
I started using this from v19 of ag-grid and I'm currently using v21.0.1 but since autoHeight never seemed to work for me I kept using the following code.
```
$scope.grid = {
	...,


	visibleMaxRowHeightMap: new Map(),
	visibleRows: [],
	restoreDefaultSettings: function () {
		$scope.grid.visibleMaxRowHeightMap.clear();
	},
	resetDone: false,
	setHeightOfVisibleRows: function () {
                // I added a timeout to ensure the grid rows were rendered
		$timeout(function() {
			const self = $scope.grid;

			self.restoreDefaultSettings();

			const agGridRows = document.getElementsByClassName("ag-row");
			const visibleRows = [];
			for (let i = 0; i < agGridRows.length; i++) {
				if (agGridRows[i].children.length === self.headers.length) {
					visibleRows.push(agGridRows[i]);
				}
			}

			for (let i = 0; i < visibleRows.length; i++) {
				const agRow = visibleRows[i];
				let maxRowHeight = 50;
				for (let j = 0; j < self.headers.length; j++) {
					const agRowCell = agRow.children[j];
					if ( agRowCell.firstElementChild != null && maxRowHeight < agRowCell.firstElementChild.offsetHeight) {
						maxRowHeight = agRowCell.firstElementChild.offsetHeight + 10;
					}
				}

				self.visibleMaxRowHeightMap.set(parseInt(agRow.attributes["row-index"].value), maxRowHeight);
			}

			self.gridOptions.api.resetRowHeights();
			self.resetDone = true;
			self.gridOptions.api.redrawRows();
		}, 100);
	},

	
	...,
	gridOptions: {
                ...,

                // Getting rowHeight from map calculated before
		getRowHeight: function(params) {
			const result = $scope.grid.visibleMaxRowHeightMap.get(params.node.rowIndex);
			if (angular.isDefined(result)) {
				return result;
			} else {
				return 50; // Default angular material theme height
			}
		},
                // You need to add setHeightOfVisibleRows() in each event that changes the grid rows
                // For example, I'm calling in the following event but also on onPaginationChanged, onSortChanged and onFilterChanged
		onGridSizeChanged: function() {
			$scope.grid.setHeightOfVisibleRows();

			this.api.sizeColumnsToFit();
		},

                ...
	}
}
```
Feel free to ask me questions if it doesn't work for you. This was done some time ago so I hope I haven't forgotten some parts.

**Comment by areisle** [comment]
@AmareshB I ended up not using the built in autoHeight at all and manage all my row heights myself via a React.context I wrap the grid in. it's not my favourite solution, but I was hoping it would be temporary. I can post more details if you're interested in the particulars. For most of my columns I still didn't use the autoHeight work around and instead did something like the latin text example in the docs to estimate the height cause the autoHeight wasn't very performant anyway

**Comment by AmareshB** [comment]
@omnibrain @Redemin @areisle I set reactNext = {false} and interestingly, row heights are adjusted accordingly .

**Comment by Paul6552** [comment]
Any news on this?
react with cellRendererFramework and auto height is not working, but this issue-ticket is closed X)

**Comment by csit-intern-james** [comment]
Hey @Paul6552 @AmareshB, I think we have the same problems. I opened a [PR](https://github.com/ag-grid/ag-grid/pull/3701) that _may_ fix the issue. Could you give this a shot and see if it fixes your problem?

No guarantees :sweat_smile:

**Comment by efeminella** [comment]
I am curious as to why this issue has been closed? I am having the same problems and we're now on v25. Auto-height with custom cell renderers and infinite row models does not appear to work in any release I have tested with spanning from v21.x.x through v25.x.x.x).

Any workarounds available for this?

**Comment by Paul6552** [comment]
@efeminella 
If it wasn't so sad I would have laughed a lot now.

I'm only looking for a version where I don't have a serious bug. Right now for me version 23.1.1 is working, but the side effect of this version is a huge CSS bug. That means that this version will manipulate your css if you are using material-ui.

If you are looking for a pure react-table, I recommend react-table from tannerlinsley. Side effect there: typescript support is very weak, but it is working. [Link to the table](https://github.com/tannerlinsley/react-table)

Good luck

**Comment by FinderFees** [comment]
Just posting to once again verify that this is still an issue. :( We just noticed the problem after upgrading React from v15 in a custom WebPart in our SharePoint environment.

> I am using 21.2.2 and the behavior is inconsistent.

We are also seeing the inconsistency with the same version where a row on page 2 will appear correctly, but filtering and bringing up that same row on page one will have it be too small.

>  I set reactNext = {false} and interestingly, row heights are adjusted accordingly. Doesn't work in v22.0.0 though :(

This doesn't seem to work in v21.2.2 either.

> Right now for me version 23.1.1 is working

Unfortunately upgrading to this version didn't fix it for us.

If anyone has been able to find a good React solution, I'd love to hear it. :)

**Comment by vipdanek** [comment]
Hello , why closed this theme? 
It's actually theme for my project actually,  because I use v25 ag-grid , and not work this:
-----
autoHeight=true 
wrapText=true 
-----
I created project on react

**Comment by JoseCadenas** [comment]
Hello,

I am still experiencing a similar issue with Vue3. My framework cell renderers are not taking full advantage of the autoHeight. I run into a UX issue when trying to enter the cell editor with a double click as the entire cell does not react to this input. In the screenshots below you'll see only half of the right cell is selected (double clicking below that selected area wont trigger the cell editor)... as for the left cell it's displayed on two lines and the selection indicator is around the entire cell:
![Screen Shot 2021-11-30 at 8 58 13 AM](https://user-images.githubusercontent.com/50152606/144092729-5f942fbe-f858-42b0-934d-fa4947f59037.png)
![Screen Shot 2021-11-30 at 8 58 28 AM](https://user-images.githubusercontent.com/50152606/144092733-7e5bcaaa-0baa-49e6-b6dd-859bc93830b6.png)

Both are actually using the same vue cell render but with computed properties and conditional vue rendering based on the column field and defaultColDef of autoHeight = true. Any suggestions to fix this issue?

Any help is much appreciated!

-Jose
