### ISSUE TITLE
loadingCellRendererFramework not working with infinite scroll model

### ISSUE THREAD

**Issue by chat-du-cheshire** [ag-grid/ag-grid#3162]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**

- A plunker
https://plnkr.co/edit/fQ7M3BjTJWECfNK2c55K?p=preview

**Current behavior**
When im setting CustomLoading in loadingCellRendererFramework property component not showing

**Expected behavior**
Sowing loader component

Maybe there is a special property which activate it, but I have't found this

**Comment by jiangyh1024** [comment]
@chat-du-cheshire  https://next.plnkr.co/edit/5iweclPTmfQzg8Wd
I have updated your plunker, it is working
