### ISSUE TITLE
Customise Theme question

### ISSUE THREAD

**Issue by jiangyh1024** [ag-grid/ag-grid#3166]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

<img width="783" alt="image" src="https://user-images.githubusercontent.com/34930870/58703867-ac673700-83dc-11e9-9ba6-3711628f7512.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/34930870/58703903-c4d75180-83dc-11e9-8920-3c36613b0641.png">

as you can see, the bg color of check icon is not the same as before (should be the same as row bg color) don't know why

**Expected behavior**

checkbox icon color should be the same as before

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/58770251-83af8f00-85e0-11e9-8774-61b0b2f825f2.png)

I think the problem is the background url. see above.

customised theme generate bg url like this, but  non-customised theme generate bg url using base64 string

![image](https://user-images.githubusercontent.com/34930870/58770286-c2dde000-85e0-11e9-9219-7d534c46caf1.png)

do you know why ??

**Comment by jiangyh1024** [comment]
Oh, I found the repo you provided, and I tried to integrate with ng, but it does not work. Can u please provide a ng version repo ?

**Comment by gportela85** [comment]
@jiangyh1024 the reason why custom themes are not encoding your URLs is that the angular CLI isn't adding `url-loader` to the process when importing scss files.

I left a question on Stackoverflow a while ago, but nobody answered https://stackoverflow.com/questions/54163581/how-to-use-url-loader-with-angular-cli-compiler

**Comment by jiangyh1024** [comment]
@gportela85 I tried 'ngx-build-plus' and 'angular-builders' , no need to eject webpack.config.js. But I still could not make it. I don't know which procedure got wrong.

**Comment by jiangyh1024** [comment]
https://github.com/meltedspark/angular-builders
https://github.com/manfredsteyer/ngx-build-plus

**Comment by jiangyh1024** [comment]
I think the problem might be the custom webpack configuration. I only added this
![image](https://user-images.githubusercontent.com/34930870/58843918-495cf500-86a7-11e9-9f3e-4779cc230f1f.png)

**Comment by gportela85** [comment]
@jiangyh1024 with the launch of v21 today. The way to customize icons / themes has changed. Please, make sure you check this repo - https://github.com/ag-grid/ag-grid-customise-theme

It has a version of custom themes + coloring icons with angular as well.

**Comment by jiangyh1024** [comment]
@gpotela85    thx!!
