### ISSUE TITLE
Angular cell renderer function: is it allowed (documentation)

### ISSUE THREAD

**Issue by teuf22** [ag-grid/ag-grid#3169]
Are Cell renderer functions allowed with Angular ? The documentation has inconsistent information:

This [page](https://www.ag-grid.com/javascript-grid-cell-rendering-components/#cell-renderer-function) states "If using a framework such as React or Angular for your cell renderers then you must provide a cell renderer component. There is no function equivalent for the frameworks such as React and Angular."

While this [page](https://www.ag-grid.com/angular-more-details/#cell-rendering-cell-editing-using-angular) states "The grid will happily work with both Angular and non-Angular portions (eg cellRenderers in Angular or normal JavaScript)."

**Comment by jiangyh1024** [comment]
@teuf22 see https://www.ag-grid.com/javascript-grid-cell-rendering-components/#angular-cell-render-components

you should create a component extending ICellRendererAngularComp and implment the refresh method and other logic

**Comment by teuf22** [comment]
Thank you. I have used both Angular components (as you described) and function renderers and both seem to work with Angular. Function renderers are nice for simple cases where you don't want to complicate your code with separate components. However, the documentation is unclear about function renderers in Angular. That's what my question was about.
