### ISSUE TITLE
Floating filter displays 'undefined' on custom filter option

### ISSUE THREAD

**Issue by dusski** [ag-grid/ag-grid#3170]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[] feature request 
[] support request 
```

**Providing a Reproducible Scenario**
Reproducible Scenario:
Enable floating filters
Add a custom filter option that hides the input filed
https://next.plnkr.co/edit/lbrsAb9HmaZIIrgZ

**Current behavior**
With the floating filters enabled, when you select a custom filter option (in this case "* Empty *" on the 'athletes' column) that hides the input filed, the floating filter input shows 'undiefined'. 

**Expected behavior**
Input should be also hidden or there shouldn't be 'undefined'.

**Please tell us about your environment:**
Windows 10, VS Code, npm, Angular 6

* **ag-Grid version:** 20.2.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"

* **Language:** TypeScript 2.9

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

Note this is in our next release.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
