### ISSUE TITLE
Does agGrid support infinite columns, just like the infinite rowModel?

### ISSUE THREAD

**Issue by yurychika** [ag-grid/ag-grid#3171]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Comment by yurychika** [comment]
We have a scenario that we need to support infinite columns when we do horizontal scrolling.

I wonder if that is supported? or how I could manage to do that?

If it's supported, we are very willing to purchase the enterprise version:)

**Comment by ceolter** [comment]
All columns need to be defined up front. You can add and remove columns (as per the docs) but linking this to horizontal scroll position is not something we specifically support.

**Comment by softwareguy74** [comment]
What's the use case for this?  Never in my 20+ years of building enterprise systems that rely heavily on a grid have I ever had a need for something like this.

**Comment by yurychika** [comment]
Our grid has orientation, which means rows could be changed to column, and column could be changed to rows. We are a trading group of an investment bank, and we have to deal with huge amount of data.
