### ISSUE TITLE
How to change style of edited cell?

### ISSUE THREAD

**Issue by anilljoshi** [ag-grid/ag-grid#3172]
Hello, I would like to change my default cell style once cell value has been changed. 'agAnimateShowChangeCellRenderer' animation is working fine but I want to update background-color and text color of cell permanently till refresh. Please help
Thanks

**Comment by jiangyh1024** [comment]
@anilljoshi cell cellClassRules, after value has been changed,  set a flag and refresh current node. Do logic in cellClassRules callback
