### ISSUE TITLE
After filter, grouped rows with same agg values not updated

### ISSUE THREAD

**Issue by apollolux** [ag-grid/ag-grid#3175]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
*Note: I can't use Plunkr because I'm behind work firewall.*

Hello! In my ag-grid I have grouped rows and some columns use 'sum' (or more specifically a version I wrote that logs NaNs for me) for aggregation. These columns also have a valueFormatter on their colDef such that if filtering is present it wraps the displayed value as `(… VALUE …)` . I have an interesting scenario where one of those groups has the column sum to 10 through 5+5 and when filtering by that column using `VALUE = 5` because the value doesn't change it seems to be using a cached format for it instead of wrapping it or unwrapping it as filter state changes.

*Note: this is different from #1577 , where that one couldn't update regardless but this one (way after that fix) can't update when the value is the same.*

Reproduction:
* Grid options include suppressAggFuncInHeader, groupHideOpenParents, groupMultiAutoColumn, floatingFilter
* defaultColDef options include enableRowGroup, filter, sortable (if that matters)
* Data are normal grid of values, e.g. name / amount / etc grouped by name, and two rows that get grouped have same amount value, e.g. 5
* Amount column filter is 'agNumberColumnFilter' and aggFunc is 'sum' or my slightly custom version, but really any filter that results in the value obtained by grouped rows not changing
* The valueFormatter for pretty much every colDef is return the value if !params.api.isColumnFilterPresent(), else return `(… VALUE …)`
* Start by leaving the grouped row closed so the aggregate value displays, e.g. 10
* Filter by something, easiest is by the amount column with `VALUE = 5`, the value will not be wrapped in ( )
* (optional) Expand the grouped row, then close and the aggregate value will be correctly formatted (i.e. wrapped in ( )  ); right after this, remove the filter and the formatted value displayed will not change (i.e. will stay wrapped in ( ) rather than revert to unwrapped); expanding and closing the grouped row here will refresh the displayed value to the correct formatting (i.e. unwrapped)

One thing to note is that valueFormatter will still return the correctly formatted string (at least from what logs show me), but I have a feeling that because the value (from valueGetter/filterValueGetter) doesn't change then the grid uses a cached string.

**Current behavior**
The *displayed* formatted aggregate value of that column does not change to reflect a change in filter state when an aggregate value does not change as a result of the filtering.

**Expected behavior**
The *displayed* formatted aggregate value *should* change to reflect the filtered state even if the value is the same based on its column's valueFormatter, *especially* if a custom valueFormatter is present in that colDef.

**Please tell us about your environment:**
Windows 7 (because work), VS Code 1.34, Node.js 8.11.2, Angular 7.2.14, 

* **ag-Grid version:** 20.2.0 (I'll have to check with boss to see if we have enterprise license or not)

* **Browser:** Chrome 73
(Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36)

* **Language:** TypeScript 3.2.4

I know this is an uncommon use case, but using sample values it should almost certainly be reproducible. Another example could be data of ages of people in some 3rd grade class, aggregated possibly by avg and grouped by homeroom, then filtering for `AGE = 8` and the data in one homeroom not changing.

**Comment by ceolter** [comment]
because no plunker, i cannot be 100% sure (if plunker is blocked in work, then you should re-create the problem at home).

this sounds like the change detection mechanism in ag-Grid working against you. in change detection, if the value of the cell hasn't changed, then the cell is up refreshed.

two ways to get around this:

1) after the filter is applied, call 
```api.refreshCells({force:true});```
This will get all cells to refresh, including all cells where the value has not changed.

-or-

2) create a custom aggFunc for the column in question. have it NOT return a number. instead have it return an object (eg {theSum: value}). each time the aggFunc is called, it should create a new instance result. then the cell will think it's a new value as it compares object instances when the value is an object. the cellFormatter just needs to be aware it's an object and not a simple number type when formatting.

**Comment by apollolux** [comment]
Hello again! Looks like adding the refreshCells force in onFilterChange did the trick, though there is a noticeable one frame blink where the text is refreshing itself. That may or may not be related to ag-grid by itself, so I'll hold off on filing that one for now.

Next time I'll be sure to get a plunkr made at home, but thank you again for the working resolutions!
