### ISSUE TITLE
GridCell class is removed ????

### ISSUE THREAD

**Issue by jiangyh1024** [ag-grid/ag-grid#3176]
I've upgraded to version 21.0.0 and found that 'GridCell' class is removed? 
when I call event.api.getFocusedCell(), it returns CellPosition type without 'floating' property.

what should I pass when calling  event.api.setFocusedCell(rowindex, column, floating);

should I pass NULL to the third parameter or ignore it?

In previous version, 
![image](https://user-images.githubusercontent.com/34930870/58923297-a624e200-8771-11e9-8af7-a063a9214414.png)

**Comment by ceolter** [comment]
The GridCell was replaced with CellPosition which has:

```
interface CellPosition {
  rowIndex: number;
  column: Column,
  rowPinned: string;
}
```

the field for floating is rowPinned (we renamed row floating to row pinning a long time ago, to avoid confusing with floating filters).

see below, getting the focused cell for firstly normal cell, then a row pinned cell.

![image](https://user-images.githubusercontent.com/6539563/59028317-3c7d0480-8853-11e9-9178-c8cf4d377faf.png)

do not get confused with pinned columns - to check that you inspect the column attribute column.getPinned()
