### ISSUE TITLE
Undocumented Angular breaking change with 21.0.0

### ISSUE THREAD

**Issue by MicMicMon** [ag-grid/ag-grid#3179]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I could not find documented in the changelog that in Angular, the component name `AgGridNg2` becomes `AgGridAngular` in version 21.

**Comment by totszwai** [comment]
Why is this closed? This a breaking change
