### ISSUE TITLE
Console.log in rowComp.ts on line 294

### ISSUE THREAD

**Issue by jahumes** [ag-grid/ag-grid#3182]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/rendering/rowComp.ts#L294

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
There is a console.log outputting information for every row rendered.

**Expected behavior**
No console.log in production code. This should be able to be fixed by using a linter or a git hook to check for console.log in the code. Since this isn't the first time this has happened, it would be nice to get some feedback as to why this continues to happen. We are unable to release updates because of this oversight.

**Please tell us about your environment:**
Every browser/operating system

* **ag-Grid version:** 21.0.0

* **Browser:**
All

* **Language:** [all]

**Comment by seanlandsman** [comment]
Hi

Both of these will be fixed in a patch release due in the next day or two

thanks
