### ISSUE TITLE
AngularJS rowNode no longer available on scope for cell renderer

### ISSUE THREAD

**Issue by jahumes** [ag-grid/ag-grid#3183]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

This appears to have happened in this commit. https://github.com/ag-grid/ag-grid/commit/c6b75349df2969729eb8f3cf8f9fd2560da72404
This is the same commit that caused the console.log error from my other ticket https://github.com/ag-grid/ag-grid/issues/3182
It is frustrating that a bug done in March was not caught for a release that happened in June.

**Current behavior**
Cell renderer templates in AngularJS do not have access to the rowNode anymore.

**Expected behavior**
When a cell renderer in AngularJS is called, it should have access to the rowNode property to allow access to the rowNode. See an example below:
```javascript
function _checkboxCellRenderer(params) {
      params.$scope.toggleRowSelection = _toggleRowSelection;
      return '<span class="row-checkbox" ng-click="toggleRowSelection(rowNode, $event)">' +
           '<i ng-if="rowNode.selected" class="fa fa-check-square-o"></i>' +
           '<i ng-if="!rowNode.selected" class="fa fa-square-o"></i>' +
      '</span>';
}
```

**Please tell us about your environment:**
All

* **ag-Grid version:** 21.0.0

* **Browser:**
All

* **Language:** [all]

**Comment by seanlandsman** [comment]
Hi

Both of these will be fixed in a patch release due in the next day or two

thanks
