### ISSUE TITLE
RowContainerComponent.setHeight(null) doesn't clear eWrapper height

### ISSUE THREAD

**Issue by pomack** [ag-grid/ag-grid#3184]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
http://plnkr.co/edit/SNK9WCMAki1sx7XO8R9Q?p=preview

**Current behavior**

https://github.com/ag-grid/ag-grid/blob/v21.0.0/packages/ag-grid-community/src/ts/rendering/rowContainerComponent.ts#L81
sets `eWrapper` height to be same as `eContainer`. If this is called with `setRowData([])`, then result is `1px` height for both.

https://github.com/ag-grid/ag-grid/blob/v21.0.0/packages/ag-grid-community/src/ts/rendering/rowContainerComponent.ts#L75
When switching to print mode, this is called with `null`, so height style attribute of `eContainer` is removed, but `eWrapper` will stay the same.

If you later call `setRowData([...])` with more rows, you won't see them in print view.

**Expected behavior**

Switching to print mode shouldn't mean `setRowData(...)` can't be called to see all data.

When `RowContainerComponent.setHeight(null)` is called, it should remove the `eWrapper` height style attribute.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** 21.0.0

* **Browser:**
Chrome and Safari

* **Language:** all

**Comment by gportela85** [comment]
Hi @pomack, 

Check how the height/width is dealt with in our examples: https://www.ag-grid.com/javascript-grid-for-print/

I've updated your plunker to match the example code flow: http://plnkr.co/edit/Zs4RNQkTHYkKaUDNP5tp?p=preview

Note: It also helps to set the data before changing the Layout.

**Comment by pomack** [comment]
I updated your plnkr to show a different problem. If you have a `normal` view and switch to `print` view. Then if you ever add more rows, it won't show up:

http://plnkr.co/edit/PZraN7?p=preview

I want to make sure the expectation isn't that `setDomLayout(null) `must be called before calling `setRowData()` if dom layout is set to 'print'.
