### ISSUE TITLE
Tree data expand/collapse callback

### ISSUE THREAD

**Issue by AnhLy** [ag-grid/ag-grid#3188]
Hi ag-grid,
I have a feature to remember the expand/collapse of auto group column of the tree view data in clientside model grid. The problem is that I can not find out the expand/collapse callback to handle save that position status. Have can I solve these issues?

**Comment by AnhLy** [comment]
I used rowGroupOpened and it works.

**Comment by msurendra4** [comment]
@AnhLy  Hey can you please provide sample code . Have give a callback for rowGroupOpened but its not working when i expand GroupRow

**Comment by AnhLy** [comment]
I just use this and have "onRowGroupOpened" function in component, and it work well when I expand/collapse the node
`  <ag-grid-angular
    #agGrid
  (rowGroupOpened)="onRowGroupOpened($event)"
 >  </ag-grid-angular>
`
