### ISSUE TITLE
ComboBox in Aggrid Cell

### ISSUE THREAD

**Issue by lgowrinadh** [ag-grid/ag-grid#3193]
Hi,

Please help us in integrating Angular 6 Combo-box or Kendo-Combo-box in Ng-Grid cell with List of Elements. We have tried a lot but didnt got enough results in google. Please help on this.

**Comment by jiangyh1024** [comment]
@Igowrinadh
Hi do you mean this?
```

import { Component, ViewChild } from '@angular/core';
import { ComboBoxComponent } from '@progress/kendo-angular-dropdowns';
import { ICellEditorAngularComp } from 'ag-grid-angular';

@Component({
  selector: 'app-select-cell-editor',
  template: `<kendo-combobox #kendoCombobox (valueChange)="onValueChange()"
  [clearButton]="clearButton" style="width:100%" [data]="dropdownData"
  textField="text" [popupSettings]="{'width': '150px'}" valueField="value" [valuePrimitive]="true" [(ngModel)]="value"></kendo-combobox>`
})
export class SelectEditorComponent implements ICellEditorAngularComp {

  //#region Properties

  public dropdownData: any;
  public value: any;
  public clearButton: boolean;

  @ViewChild('kendoCombobox')
  private kendoCombobox: ComboBoxComponent;

  private params: any;

  //#endregion

  //#region Events

  public agInit(params: any): void {
    this.params = params;
    this.value = params.value;
    this.dropdownData = params.values;
    this.clearButton = !!params.clearButton;

    // open it
    this.kendoCombobox.toggle(true);
  }

  public onValueChange(): void {
    this.params.api.stopEditing();
  }

  public getValue(): any {
    return this.value;
  }

  //#endregion
}
```

and use it in aggrid
![image](https://user-images.githubusercontent.com/34930870/59238655-7e31f480-8c31-11e9-9967-9dab5b704224.png)
![image](https://user-images.githubusercontent.com/34930870/59238675-8853f300-8c31-11e9-8ee0-75c82f295eb7.png)
![image](https://user-images.githubusercontent.com/34930870/59238698-943fb500-8c31-11e9-8256-b832c00dfcc8.png)

**Comment by lgowrinadh** [comment]
Hi , 

I am getting Exception like " can not read property toggle of undefined" while i am using the temple like this and it is because of it is kendo not initializing i guess. could you please help on it.




<ng-template kendoGridEditTemplate let-dataItem="dataItem" let-rowIndex="rowIndex">
  <kendo-combobox [data]="dropdownData | orderByAsc"
                  [allowCustom]="true"
                  [filterable]="true"
                  [valuePrimitive]="true"
                  style="width: 150px;color: #000 !important;"
                  [popupSettings]="{ popupClass: 'custom-dropdownlist'}"
                  name="descriptiontankDescriptionTypes"
                  (filterChange)="descriptionFilterChange($event)"
                  (valueChange)="valueChange($event, rowIndex)"
                  [(ngModel)]="dataItem.description">
  </kendo-combobox>
</ng-template>

**Comment by lgowrinadh** [comment]
<ng-template kendoGridEditTemplate let-dataItem="dataItem" let-rowIndex="rowIndex">
  <kendo-combobox [data]="dropdownData | orderByAsc"
                  [allowCustom]="true"
                  [filterable]="true"
                  [valuePrimitive]="true"
                  style="width: 150px;color: #000 !important;"
                  [popupSettings]="{ popupClass: 'custom-dropdownlist'}"
                  name="descriptiontankDescriptionTypes"
                  (filterChange)="descriptionFilterChange($event)"
                  (valueChange)="valueChange($event, rowIndex)"
                  [(ngModel)]="dataItem.description">
  </kendo-combobox>
</ng-template>

**Comment by jiangyh1024** [comment]
you mean Viewchild did not get the instance of kendo  combobox？？ that's weird.

**Comment by lgowrinadh** [comment]
yes

**Comment by lgowrinadh** [comment]
If i place kendo-combo box inside "<ng-template kendoGridEditTemplate let-dataItem="dataItem" let-rowIndex="rowIndex">" then problem coming otherwise working fine

**Comment by jiangyh1024** [comment]
can u post your  code？

**Comment by lgowrinadh** [comment]
if i place kendo-combobox inside ng-template for getting rownumber then this problem coming otherwise it working fine

**Comment by lgowrinadh** [comment]
![image](https://user-images.githubusercontent.com/10380968/59278532-c841c700-8c7f-11e9-9085-455389471c42.png)

![image](https://user-images.githubusercontent.com/10380968/59278621-f6bfa200-8c7f-11e9-9982-723e0b6d0c76.png)
![image](https://user-images.githubusercontent.com/10380968/59278669-0b9c3580-8c80-11e9-9c7e-8efaf13d68bb.png)
![image](https://user-images.githubusercontent.com/10380968/59278705-22db2300-8c80-11e9-9fcf-61cdefb5f0e6.png)

**Comment by jiangyh1024** [comment]
I am confused. why u use kendogridedittemplate directive？ if you want to pass rowindex to the select editor.  pass it through params. see cellRenderSelector,

**Comment by lgowrinadh** [comment]
![image](https://user-images.githubusercontent.com/10380968/59279525-b3663300-8c81-11e9-88c0-6a75036e3424.png)

**Comment by jiangyh1024** [comment]
return {component: 'selectEditorComponent',
 params:{
rowIndex: this can be get from CellEditorSelecor
}}

**Comment by jiangyh1024** [comment]
yes, just add rowindex below values property and get it from params  you can console.log(params)  to find the rowindex

**Comment by jiangyh1024** [comment]
and in your selectEditorComponent, in agInit function ， you can get rowindex by calling  params.rowindex

**Comment by jiangyh1024** [comment]
or you even do not need to pass rowindex. because you can get it directly from params in aginit function, just print it and see

**Comment by madhuinwiter** [comment]
@jiangyh1024 
When I use kendo combo box as you suggested above it's rendering. But  I am facing below issue

Let's say you have 4 columns and you have combo box in coulmn 3 and rest are inputs
Entered value in col 1 and clicked tab it moved col 2 and I am able to enter value directly
Entered value in col 2 and clicked tab it moved col 3 it's focused but 
**I am unable to enter value directly and when click tab it's not moving to col 4**

Do you have any solution for this?

**Comment by jiangyh1024** [comment]
@madhuinwiter  do you use cell renderer or cell editor ?

**Comment by jiangyh1024** [comment]
I found that it is something related to tabindex on others component

**Comment by madhuinwiter** [comment]
@jiangyh1024 
What about the value that enter in combo box is getting erased when I press TAB?

**Comment by jiangyh1024** [comment]
@madhuinwiter  if u want to keep the custom select value, then put it to your dropdown datasource
when exiting edit mode 'getValue()' method will be called, just add it to you dropdown datasource and return the value you input

**Comment by MalleswaraoBandi** [comment]
Here I have given custom value in kendo combo box and pressed tab the custom entered data got erased.
![Kendo-combobox-customValue](https://user-images.githubusercontent.com/30398704/60877842-387e4100-a25c-11e9-8e01-8a588eae65cf.JPG)
Here the custom entered value got erased.
![image](https://user-images.githubusercontent.com/30398704/60877945-695e7600-a25c-11e9-90b2-2288ac8a1525.png)
![image](https://user-images.githubusercontent.com/30398704/60878315-1e912e00-a25d-11e9-9f72-2ed3d9e47416.png)


![image](https://user-images.githubusercontent.com/30398704/60878463-61eb9c80-a25d-11e9-84a7-490c52f16a3f.png)
![image](https://user-images.githubusercontent.com/30398704/60878511-7c257a80-a25d-11e9-997b-0f7155136683.png)

**Comment by jiangyh1024** [comment]
...Your dropdown data source is not updated ?

**Comment by MalleswaraoBandi** [comment]
How to updated the data source with custom value and I am loosing the selected value on tab click.

**Comment by biels** [comment]
What is the standard way of putting a combobox / dropdown / typeahead cell editor in ag-grid in 2020? Not even the enterprise version of the select cell editor has search sunctionality at the moment.

**Comment by gportela85** [comment]
@biels The agRichSelect will search for values as you type, but it doesn't have a textfield with the typeahead functionality built-in. If you need something more elaborate for your project the advice is to go with your own custom components.

You can check the agRichSelect by going to the main demo: https://www.ag-grid.com/example.php and editing a cell in the country column.

**Comment by biels** [comment]
Okay, thanks for your reply. Do you have have any reference to an implementation or how to implement such custom control?
