### ISSUE TITLE
Certain browsers don't render table

### ISSUE THREAD

**Issue by lalli-oni** [ag-grid/ag-grid#3196]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

The table does not render.
In Safari `.ag-root-wrapper-body` height is `0`.

**Expected behavior**

The table should render.

**Please tell us about your environment:**

NPM packages:
    "ag-grid-community": "^21.0.1",
    "ag-grid-vue": "^21.0.1",

Tests using BrowserStack, newest versions of OS and hardware.

No console outputs (no warning/info/error...)

* **ag-Grid version:** 21.0.1

* **Browser:**

| OS | Browser | Pass/Fail |
| -- | ------- | --------- |
| Windows | Chrome | ✔️ |
| Windows | Firefox | ✔️|
| macOS | Chrome | ✔️|
| macOS | Firefox | ✔️|
| macOS | Opera | ✔️|
| macOS | Safari | ❗️ |
| iOS | Safari | ❗️ |
| iOS | Chrome | ❗️ |
| Android | Chrome | ✔️ |
| Android | Samsung browser | ❗️ |
| Android | UC browser | ❗️ |

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by jiangyh1024** [comment]
https://www.ag-grid.com/javascript-grid-supported-browsers/

**Comment by lalli-oni** [comment]
> https://www.ag-grid.com/javascript-grid-supported-browsers/

Yes, as you can see there are 3 fail cases that are listed as supported. I just included the extra browsers since we don't have much information to go on.

**Comment by lalli-oni** [comment]
Bug on our end. Hybrid implementation of height 100% and flex-box doesn't play well with all browsers.
