### ISSUE TITLE
Reset Columns doesn't take "lockPosition: true" into account

### ISSUE THREAD

**Issue by maieutiquer** [ag-grid/ag-grid#3197]
**I'm submitting a ...**
```
[X] bug report
```

**Reproducible Scenario**
1. In the Suppress Movable & Lock Position Example plunkr, switch from using ag-grid-community to ag-grid-enterprise
https://www.ag-grid.com/javascript-grid-column-moving/#suppress-movable-lock-position-example
2. Open any Column Menu and click Reset Columns
**Current behavior**
The column with "lockPosition: true" is moved according to its position in the columnDefs array
**Expected behavior**
The column with "lockPosition: true" should stay on the first position

**A plunker**

* https://next.plnkr.co/edit/ZZPKTgnIPBr8u0Yi
Run the example, open the Column menu and click Reset Columns
**Current behavior**
Reset Columns *doesn't* take "lockPosition: true" into account
**Expected behavior**
Reset Columns *must* take "lockPosition: true" into account

**Please tell us about your environment:**
Tested on:
OS: Win7, Win10, Linux
IDE: Webstorm, VS Code, Plunkr
Package manager: npm, unpkg
HTTP server: apache, tomcat
Framework: all (JS, React, Angular, Vue)

* **ag-Grid version:** 21.0.1 (also found in  21.0.0, 20.2.0 and probably older versions as well)

* **Browser:** all latest 
  * Chrome "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36",
  * Firefox "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0",
  * Edge "Mozilla/5.0 (Windows NT 10.0; Win64; x64; ServiceUI 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362"

* **Language:** all (tested with ES6+ and TS)

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3038 | Reset Columns doesn't take "lockPosition: true" into account
