### ISSUE TITLE
[Enterprise] Issue with full with groups renderer contains input. Column def missed.

### ISSUE THREAD

**Issue by rkhramiankou** [ag-grid/ag-grid#3201]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://github.com/ag-grid/ag-grid/blob/fe50182e5542b4616d2ef41a03a38836a83daeae/dist/lib/rendering/cellRenderers/groupCellRenderer.js#L356

Seems like column definition missed for full width group renderer.
I've prepared forked plunker example to reproduce the issue:
https://plnkr.co/edit/IZRbW9xUvMVBsvV0Elt7?p=preview
1) focus on any input element even without value
2) press 'Enter' key

**Current behavior**
Console errors "Cannot read property 'isCellEditable' of undefined"

**Expected behavior**
No errors.

**Please tell us about your environment:**
Win 10

* **ag-Grid version:** X.X.X
ag-grid-enterprise": "21.0.1"

* **Browser:**
Google Chrome Version 74.0.3729.131

* **Language:**
TypeScript 3.4.3

Similar issue was before https://github.com/ag-grid/ag-grid/issues/1700.

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3108 - Full-width renderer + custom inner renderer + input box. When the user presses enter in the input box, the grid throws an exception
