### ISSUE TITLE
Feature Request - Allow access to lastSelectedNode from gridApi

### ISSUE THREAD

**Issue by Eiarzate1** [ag-grid/ag-grid#3203]
**I'm submitting a Feature Request** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Extend the Selection API within : [Selection Doc](https://www.ag-grid.com/javascript-grid-api/#selection)

Currently gridApi does not have a method to access the last selected node from SelectionController.
Feature request is to add a public function to access `getLastSelectedNode` from [SelectionController](https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/selectionController.ts)

Expected result is to call `gridApi.getLastSelectedNode()`.
This function call should retrieve the last RowNode that was selected by an end user.

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
