### ISSUE TITLE
Search option in agRichSelectCellEditor component

### ISSUE THREAD

**Issue by mahecomsci** [ag-grid/ag-grid#3208]
Do we have an option to search in the select option component (agRichSelectCellEditor ) provided in the ag-grid. Or can this be achievable with some other way.

We have a requirement to show more items in the select box, so we require a search option for this.

Thanks for your help in providing the answers.

**Comment by jiangyh1024** [comment]
@mahecomsci  you can use other select component such as ng-select and integrate it into ag-grid using 'frameworks' property on gridOptions

**Comment by jiangyh1024** [comment]
```
import { Component, ViewChild } from '@angular/core';
import { ComboBoxComponent } from '@progress/kendo-angular-dropdowns';
import { ICellEditorAngularComp } from 'ag-grid-angular';

@Component({
  selector: 'app-select-cell-editor',
  template: `<kendo-combobox #kendoCombobox (valueChange)="onValueChange()"
  [clearButton]="clearButton" style="width:100%" [data]="dropdownData"
  textField="text" [popupSettings]="{'width': '150px'}" valueField="value" [valuePrimitive]="true" [(ngModel)]="value"></kendo-combobox>`
})
export class SelectEditorComponent implements ICellEditorAngularComp {

  //#region Properties

  public dropdownData: any;
  public value: any;
  public clearButton: boolean;

  @ViewChild('kendoCombobox')
  private kendoCombobox: ComboBoxComponent;

  private params: any;

  //#endregion

  //#region Events

  public agInit(params: any): void {
    this.params = params;
    this.value = params.value;
    this.dropdownData = params.values;
    this.clearButton = !!params.clearButton;

    // open it
    this.kendoCombobox.toggle(true);
  }

  public onValueChange(): void {
    this.params.api.stopEditing();
  }

  public getValue(): any {
    return this.value;
  }

  //#endregion
}
```

use it
![image](https://user-images.githubusercontent.com/34930870/59811534-f341b000-933c-11e9-9dc8-03e8b951f3d0.png)
![image](https://user-images.githubusercontent.com/34930870/59811544-f9d02780-933c-11e9-9748-d25513a701d8.png)

![image](https://user-images.githubusercontent.com/34930870/59811569-0b193400-933d-11e9-97df-7982f64fbf2a.png)

you can pass your own params and get it in aginit function

**Comment by mahecomsci** [comment]
@jiangyh1024 : Thank you so much for your help. Much appreciated! 👍

**Comment by catherinekennedy** [comment]
@jiangyh1024 However, when using custom components as cell editors, enterMovesDownAfterEdit doesn't work as expected — unlike with the built-in agRichSelectCellEditor, where it functions correctly.
is there any solution to achieve it?
