### ISSUE TITLE
cellClass from column definition's type is overwritten by cellClass on individual column definitions

### ISSUE THREAD

**Issue by bamblack** [ag-grid/ag-grid#3213]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/Tc44CfiB6pNY5UCRoRmM?p=preview

**Current behavior**
Any `cellClass` provided on a column definition's `type` is overwritten by a `cellClass` on the column definition itself.

**Expected behavior**
`cellClass` from a column definition's `type` is merged with `cellClass` on the column definition itself.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
20.0.0

* **Browser:**
N/A

* **Language:**
All

**Comment by apollolux** [comment]
I just came across pretty much the same thing yesterday: had a `cellClass` on `GridOptions.defaultColDef` and it was getting completely overwritten by per-column colDef's `cellClass` instead of merged like you suggest. My solution was to add the extra default cell classes programmatically to all the colDefs, but this is certainly not ideal.

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2430	Add a new way to style cells, similar to cellClass, but applying the classes absolutely ie cellClassAbsolute
