### ISSUE TITLE
Expand last row when pagination active.

### ISSUE THREAD

**Issue by kiranyadav17** [ag-grid/ag-grid#3218]
[X] bug report
[] feature request
[] support request
ag-grid version : 20.1.0
angular version : 6
**Providing a Reproducible Scenario**
Make a group column(by 'Athlete' for example) in the [official doucment](https://www.ag-grid.com/javascript-grid-pagination/) of agGrid pagination and try to expand the last row.

**Current behavior**
When set pagination=true in the agGrid options and group the grid with a column, expand icon is shown beside the last row but does not apply.

I'm facing the same issue can any one help me to resolve it on priority.?

**Comment by kiranyadav17** [comment]
@makinggoodsoftware  can you help me regarding this?

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2762 | Master/Detail + Pagination: Allow pagination to only count master rows as rows that count towards the page limit

**Comment by subodhsgod** [comment]
I also faced same issue, what I experienced was -
- Upon expanding last row, child row was not visible on that page
- Then when user navigates to next page, that child row was visible there but momentarily
- When all rows on next page were loaded successfully, that child row used to disappear, leaving while space at top

However, I found a workaround, and it seemed to work in my case -
- Setting "cacheBlockSize" higher than "paginationPageSize" worked in my case
- E.g.
      paginationPageSize: 10
      cacheBlockSize: 11
