### ISSUE TITLE
Cannot read property '...' of undefined with reactNext

### ISSUE THREAD

**Issue by alkorr37** [ag-grid/ag-grid#3219]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/laTfrADSbHxQm5LC8R9L?p=preview
Only one change to https://www.ag-grid.com/javascript-grid-header-rendering/#example-header-component - adding reactNext to index.jsx

**Current behavior**
Custom component that use props.reactContainer to define smth (i.e class) with enabled reactNext produce an error like "Cannot read property '...' of undefined"

* **ag-Grid version:** 21.0.1
* **ag-grid-react version:** 21.0.1

**Comment by alkorr37** [comment]
[fix](https://github.com/ag-grid/ag-grid/pull/3220)

**Comment by seanlandsman** [comment]
Thanks for reporting this, as well as the PR

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3111 - ReactNext doesn't work when used with custom headers

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
