### ISSUE TITLE
[virtual model] Add events for loading & rendering virtual pages

### ISSUE THREAD

**Issue by erwin-beckers** [ag-grid/ag-grid#322]
Add callback events when the grid has updated/refreshed/rendered itself
and when it has loaded (virtual) page

This way we can use the events for updating the selected nodes for example.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-58

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
