### ISSUE TITLE
Docs - Properties Missing from Grid Properties Docs

### ISSUE THREAD

**Issue by kjrocker** [ag-grid/ag-grid#3223]
Pretty self-explanatory, the `columnTypes` gridOption is missing from the docs on https://www.ag-grid.com/javascript-grid-properties/

The `gridOptions` property is also missing, I didn't realize I could provide it to set default values until I looked at the underlying code.

On a related note, is there a repo where I can submit pull requests to the docs for this sort of thing?

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3106 - GridOptions reference page is missing the documentation for columnTypes

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
