### ISSUE TITLE
Docs - Outdated column def properties

### ISSUE THREAD

**Issue by Benalink** [ag-grid/ag-grid#3231]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
[Column properties docs](https://www.ag-grid.com/javascript-grid-column-properties/) list `headerGroupTooltip` as a property of ColGroupDef.

**Expected behavior**
`headerTooltip` is shown instead. I believe this property changed with this [commit](https://github.com/ag-grid/ag-grid/commit/825b106a568d28b31ded14d22da61b6b6df8980f)

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3107 - headerGroupTooltip is not working anymore

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
