### ISSUE TITLE
Disable editing of next cell on tab click in Ag Grid

### ISSUE THREAD

**Issue by ErVishalM** [ag-grid/ag-grid#3232]
Hi,

I m using Ag Grid. I want to disable editing on the click of tab. For now you can see in this [link](https://embed.plnkr.co/1NZVLBgVLlRMrJaaRtOb/) when i click on first column and click "Tab" then next cell automatically goes in editable mode. I want to disable that.

Please suggest
Thank you.

**Comment by jiangyh1024** [comment]
@ErVishalM  maybe you can do it in 'suppressKeyboardEvent' callback

**Comment by ErVishalM** [comment]
Thank you so much @jiangyh1024 . It really helped. I did not think this. Thank you so much. Can you help me on this also. [link](https://github.com/ag-grid/ag-grid/issues/3233)
