### ISSUE TITLE
getGui method is not calling in aggrid. Because of that when i double click on textbox then value does not select automatically

### ISSUE THREAD

**Issue by ErVishalM** [ag-grid/ag-grid#3233]
Hi,

I am using Ag-Grid. In that When i make one column editable via double click and go on text column via tab then **Numeric** column goes editable but not auto select the value in it because of that i have to manually clear the textbox value. You can check in this link [link](https://plnkr.co/edit/IIAqaphJScoma3NOONnl?p=preview).
It should work like this [link](https://plnkr.co/edit/dxS2V2kFYNP523QZZTMP?p=preview)

Please suggest
Thank You!

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/60409941-4ac30400-9bf8-11e9-90e2-9a3dcd7a2156.png)

@ErVishalM  you should see document carefully. if u use frameworks, 'afterGuiAttached', 'getGui' are not used. 'afterGuiAttached', 'getGui'  are used in plain javascript. I've updated your plunker, just add 'this.input.element.nativeElement.select();' in ngafterviewinit

https://plnkr.co/edit/TSBIbiIJ4XkPdl3kHTQG?p=preview

**Comment by ErVishalM** [comment]
How noob i am in this. Well Thank you so much @jiangyh1024.
