### ISSUE TITLE
React container is undefined in custom tooltip component when using reactNext flag

### ISSUE THREAD

**Issue by marcingajda** [ag-grid/ag-grid#3239]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[  ] feature request
[  ] support request
```

**Current behavior**
AG Grid is crashing on showing a custom tooltip when the `reactNext` flag is set to `true` and you try to access `this.props.reactContainer` inside the tooltip component. It's because `this.props.reactContainer` is undefined after setting the mentioned flag to `true`.

**Expected behavior**
The `this.props.reactContainer` should always have a reference to the wrapper component despite the value of `reactNext` setting.

**Minimal reproduction of the problem with instructions**
- Create an example AG Grid table
- In grid config set `reactNext={true}`
- Add tooltip and define custom tooltip component
- Try to set the wrapper class in `componentDidMount`
```
this.props.reactContainer.className = 'my-class';
```
- Run the project and try to display the tooltip

**Demo**
I forked the Plunkr from [here](https://www.ag-grid.com/javascript-grid-tooltip-component/#example-custom-tooltip) and only set the `reactNext` to true. Now when you  hover the mouse over name column for few seconds the grid will crash.

https://next.plnkr.co/edit/fEm8cCmGQTC6lRrn 

**Please tell us about your environment:**
macOS Mojave, Node v10.15.0, React Scripts 3.0.1

* **ag-grid-react version:** 21.0.1

* **ag-Grid/ag-Grid-Enterprise version:** 21.0.1

* **React version:** 16.8.6

* **Browser:** Chrome 75, Safari 12.1, probably all

* **Language:** TypeScript 3.5.2

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-3119 - React div container not available when using reactNext
