### ISSUE TITLE
Removal of right click/context menu only in Detail grid.

### ISSUE THREAD

**Issue by Joyfred** [ag-grid/ag-grid#3243]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

I created a custom detail cell renderer as provided here :
https://www.ag-grid.com/javascript-grid-master-detail/#example-custom-detail-cell-renderer-with-a-form

I want to remove the the context menu only within the detailGrid not from the entire grid, because I have a custom-made context menu for the grid to be rendered. Is it possible?

**Comment by jessorlisa** [comment]
Just set `suppressContextMenu` to true in the `detailGridOptions`.

**Comment by Joyfred** [comment]
Sorry for the late reply. But it is not working. Please look into line 27(index.jsx) of the attached plunker link, right-click within the form, still getting the default context menu with "Export" option.

Link: https://plnkr.co/edit/hb2QbTKduafq5ITEEaq5?p=preview

**Comment by brianpooe** [comment]
Why is this issue closed, the detailGridOption is not working. i am on version 31.3.2  
@Joyfred did you manage to get it working?

**Comment by brianpooe** [comment]
Anybody who comes across this issue this is how you can resolve the problem:

` getContextMenuItems (params) { 
    const isDetailRow = params.node.detail === true; 
    console.log(`getContextMenuItems`, isDetailRow, params.node) 
    return isDetailRow? []: params.defaultItems; 
  }`

`<ag-grid-angular
    style="width: 100%; height: 100%;"
    [masterDetail]="true"
    [detailCellRenderer]="detailCellRenderer"
    [rowData]="rowData"
    [getContextMenuItems]="getContextMenuItems"
    (gridReady)="onGridReady($event)"
  />`
