### ISSUE TITLE
Ag Grid Material select not working via mouse click in latest version 21 but it was working in previous version.

### ISSUE THREAD

**Issue by ErVishalM** [ag-grid/ag-grid#3245]
Hi,

I am using Ag Grid. I used material select but now in latest version 21 material select is not working via mouse click but it was working in previous version. Which i was using i updated my version and it stopped working via mouse click. You can check in this Ag Grid Example.
Check it was working in 20.2.0 [link](https://plnkr.co/edit/fHkAiSTfnO18EqhgL16T?p=preview)
But it is not working in 21.0.1 [link](https://plnkr.co/edit/TmgIuDEi8B7dXcZnMQun?p=preview)

Please suggest
Thanks.

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by ErVishalM** [comment]
@davis4acca Thanks for quick reply. Don't mind but can you tell me how much time it can take approximately. If it'll take much time then I'll downgrade grid to 20.2.0.

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-3123
DOCS: links to plunkers in angular material designs page aren't working

**Comment by ErVishalM** [comment]
Not able to find the AG-3123 in pipeline. Can you please tell me how can i trance it. Its not here. [link](https://www.ag-grid.com/ag-grid-pipeline/
![No bug Found from this AG-3123](https://user-images.githubusercontent.com/43669644/61445699-80434d80-a96b-11e9-8e72-ac1b62bb122d.PNG)
)

**Comment by ErVishalM** [comment]
@davis4acca Please can you help me trace it. Not able to trace it in the pipeline.

**Comment by BenJohnThird** [comment]
I am also encountering this issue. I am looking forward for a quick fix on this one.

**Comment by ErVishalM** [comment]
Now it's working on latest version.

**Comment by BenJohnThird** [comment]
I am using version 21.2.0 to be exact but whenever I am selecting a value, it returns nothing in the component. 
`<mat-select #select (selectionChange)="onSelectChange($event)" [(ngModel)]="value" [style.width]="columnWidth" class="mat_input">
    <mat-option *ngFor="let item of values" [value]="item">
      {{ item }}
    </mat-option>
</mat-select>

`

**Comment by ErVishalM** [comment]
Please update to 21.2.2 and check otherwise please update your code here or somewhere where we can check.

**Comment by BenJohnThird** [comment]
May i see some snippet of your html and ts?

**Comment by ErVishalM** [comment]
Did you add this class in mat-select
`panelClass="ag-custom-component-popup"` or you can check
[Ag grid given example](https://www.ag-grid.com/example-angular-material-design/)

**Comment by Jainam13** [comment]
@ErVishalM Was this issue resolved? I am using v24 and I am facing the similar issue.
