### ISSUE TITLE
Column sorting not working when column headerName is empty

### ISSUE THREAD

**Issue by zweeen** [ag-grid/ag-grid#3247]
**I'm submitting a** 
```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**

*Framework used to reproduce the bug: *

Vanilla javascript: https://plnkr.co/edit/lETGlaOzgc8GlHD727aQ?p=preview

Vuejs: https://plnkr.co/edit/As7icQqe9v5557DmMEwL?p=preview

React: https://plnkr.co/edit/azEy7GD3gYymL5rKVECU?p=preview

Angular: https://plnkr.co/edit/lNXBTyBBvFoqpcPkAmPu?p=preview

**Current behavior**
When setting headerName of column A to empty string it disable sorting for this column A. Even by setting the sortable column definition attribute to true (sortable: true).

**Expected behavior**
Setting column headerName empty string should'nt disabled sorting.

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** 21.0.1 and  21.0.0

* **Browser:**

   Chrome: 
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
    
    Firefox:
    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

    Edge:
    Mozilla/5.0 (Windows NT 10.0; Win64; x64; ServiceUI 13.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

* **Language:** [ES6/7 | ES5]

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by zweeen** [comment]
Thank you @AhmedAGadir for your responsiveness :)
Ag grid rocks you are doing a very good job guys.

A big thanks from the community 👍

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3136  Column sorting not working when column headerName is empty

**Comment by zweeen** [comment]
@davis4acca thank you :) 

The issue has been fixed in Ag Grid  21.2.0 version

See [AG-3136](https://www.ag-grid.com/ag-grid-changelog/?fixVersion=21.2.1) 👍

**Comment by marklbarlow** [comment]
This issue seems to be occurring again in the latest version of ag-grid (28.1.1).  Has there been a regression?
