### ISSUE TITLE
duplicate node id 'undefined' detected from getRowNodeId callback

### ISSUE THREAD

**Issue by rubyfin** [ag-grid/ag-grid#3251]
Very new to both Angular and Ag-grid, would appreciate some help here.

**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
I am trying to use the Delta Row Data method of updating rowData on the grid. I made the proper changes, I believe: 

1. set `[deltaRowDataMode]="true"`
2. implemented a getRowNodeId() callback:
```
this.gridOptions = {
      headerHeight: 35,
      rowSelection: 'multiple',
      sortingOrder: ['desc', 'asc', null],
      getRowNodeId: function(data) {return data.id}
    };
```

Yet when I try to run the app, I get this error:

> clientSideNodeManager.js:275 ag-grid: duplicate node id 'undefined' detected from getRowNodeId callback, this could cause issues in your grid.

It looks like the grid cannot get  columns, but I am not sure why.

Here are my ngOnInit(), onGridReady() and GetNewData() methods:

  ```
onGridReady(params) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    setInterval(() => this.GetNewData(), 30000);
  }

  GetNewData() {
    fetch('http://0.0.0:4200/my-shiny-data')
      .then(result => result.json())
      //.then(rowData => this.rowData = rowData);
      .then(rowData => this.gridApi.setRowData(rowData));
  }

  ngOnInit() {
    this.GetNewData();
  }
```

**Expected behavior**
I expect the grid to get column Ids via the callback, figure out what data changed, and replace the rows that changed with new data, as per https://www.ag-grid.com/javascript-grid-data-update/#delta-row-data

What am I doing wrong? 

**Please tell us about your environment:**
OS:      RedHat 7.5
Kernel:  3.10.0-862.el7.x86_64

* **ag-Grid version:** 21.0.1

* **Browser:**
latest Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular 8.1.0

**Comment by rubyfin** [comment]
I was able to figure out the issue after some debugging. The issue was in getRowNodeId() returning 'undefined' for some json opbjects, because some Json objects were missing the id returned by getRowNodeId().

**Comment by jairo-ab** [comment]
> Consegui descobrir o problema depois de algumas depurações. O problema estava em getRowNodeId() retornando 'undefined' para alguns json opbjects, porque alguns objetos Json estavam faltando o id retornado por getRowNodeId().

Could you show an example of how to solve it?

**Comment by jairo-ab** [comment]
> > Consegui descobrir o problema depois de algumas depurações. O problema estava em getRowNodeId() retornando 'undefined' para alguns json opbjects, porque alguns objetos Json estavam faltando o id retornado por getRowNodeId().
> 
> Could you show an example of how to solve it?

Resolved ✅
