### ISSUE TITLE
Not able to select text from grid once column is pinned

### ISSUE THREAD

**Issue by vladimanaev** [ag-grid/ag-grid#3253]
Not able to select text from grid once column is pinned
```
[x] bug report
```

How to reproduce:
1. Pin a column (https://www.ag-grid.com/javascript-grid-pinning/)
2. Enable **enableCellTextSelection**
3. Try select text from the pinned column. 

Bug: not able to select text from pinned column.

Current behaviour: Not able to select text once column is pinned.
Expected behaviour. Would be great to be able to select text even on pinned columns.

**Environment:**

* **ag-Grid version:** 20.2.0

* **Browser:** Seems an issue in all browsers

* **Language:** [ES6/7]

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

Note this is coming in our next release.


If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
