### ISSUE TITLE
Enterprise version: How to set a group header name for an autogroupcolumndef?

### ISSUE THREAD

**Issue by tyler-dunkel** [ag-grid/ag-grid#3255]
I am attempting to add a custom group header name (in space above headerName) to the autoGroupColumnDef column that is generated. What would be the easiest way to do this?

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email.

We think you should be able to find this in our docs, please have a look at the following resources:

https://www.ag-grid.com/javascript-grid-grouping/#configuring-auto-column

Please take a look at this pages and come back on the ticket if you have further questions.

Thanks
