### ISSUE TITLE
Float in agAnimateShowChangeCellRenderer

### ISSUE THREAD

**Issue by NikitaIT** [ag-grid/ag-grid#3256]
![image](https://user-images.githubusercontent.com/16810067/60990528-4e216280-a351-11e9-9f65-4c34c3d9904e.png)
![image](https://media.tenor.com/images/2fb17890d05e9521a30d3970264c2fe6/tenor.png)

fixed with
```
  valueFormatter(params) {
    return Math.round(params.value * 100000) / 100000;
  },
```
but its awful

**Comment by AhmedAGadir** [comment]
This is not an ag-grid issue, is just floating point maths.

https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript

**Comment by NikitaIT** [comment]
@AhmedAGadir  I would not trust you to write a calculator, because driving 1.12 + 1.11 = 2.2300000000000004 into it, you would say `This is not an calculator issue, is just floating point maths.`

Old joke:
— How many programmers does it take to change a light bulb?
— None, it's a problem on the hardware side.

**Comment by vc8bp** [comment]
you could use toFixed() or if the value indicated price the Intl.NumberFormat
