### ISSUE TITLE
gridOptions cell class properties do not apply

### ISSUE THREAD

**Issue by Blackbaud-ErikaMcVey** [ag-grid/ag-grid#3261]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
The cellClass, cellStyle, and cellClassRules properties documented in grid properties do not apply to the cells and are not included in the typescript definitions. 
https://www.ag-grid.com/javascript-grid-properties/#rendering-styling

**Providing a Reproducible Scenario**
https://next.plnkr.co/edit/cikubjz1klVFaWaN

**Current behavior**

Only the column with a `cellClass` property of `rag-amber` is rendered as the `lightsalmon` color. 

**Expected behavior**

`cellClass` is set to `rag-amber` on the gridOptions. All cells should have the class, so all should render as `lightsalmon`.
The property is listed [here](https://www.ag-grid.com/javascript-grid-properties/#rendering-styling), which states "all of these grid properties are available through the GridOptions interface".

**Please tell us about your environment:**

MacOS Mojave

* **ag-Grid version:** 21.0.1

* **Browser:**

* **Language:** TypeScript 3.2.4, Angular 7

**Comment by jiangyh1024** [comment]
@Blackbaud-ErikaMcVey  oh my god, GridOptions does not have a property called 'cellclass' if you want to apply 'rag-amber' to all cells. set it in 'defaultColDef'

you can import 'GridOptions' class
and write code like this
![image](https://user-images.githubusercontent.com/34930870/61267806-f610b300-a7cb-11e9-845b-8202ca82c063.png)

if you set 'cellClass' on gridoption, error will occur as there is no 'cellclass' on gridoptions.
It is a property of type 'ColDef'

**Comment by Blackbaud-ErikaMcVey** [comment]
Thanks for the response. 

If cellClass, cellStyle, and cellClassRules are not supposed to be properties of GridOptions, I would suggest removing them from the list of properties [here](https://www.ag-grid.com/javascript-grid-properties/#rendering-styling) to avoid future confusion. When those properties were listed in both the grid and column properties sections of the documentation, I expected them to be present on both.

I don't think using the defaultColDef will work for me. I would like to add classes to every cell regardless if that cell's columnDef provides its own value for the cellClass property. [This plunker](https://next.plnkr.co/edit/W4wpsx5phWONEtOg) and [the documentation](https://www.ag-grid.com/javascript-grid-column-definitions/#default-column-definitions/) show that if a columnDef provides its own value for something defined in the default, that value is used instead of the default, as I would expect.

**Comment by Blackbaud-ErikaMcVey** [comment]
The "absolute" cellClass mentioned in https://github.com/ag-grid/ag-grid/issues/3213 (AG-2430) would do what I am looking for
