### ISSUE TITLE
Some events are missing from export

### ISSUE THREAD

**Issue by fidian** [ag-grid/ag-grid#3265]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I can't `import { CellKeyPressEvent } from 'ag-grid-community';`, but I can import different events.

**Expected behavior**

I can import the event.

**Please tell us about your environment:**

Linux, vim, npm, a few HTTP servers. I don't think any of this is relevant to the bug.

* **ag-Grid version:** master branch

* **Browser:**

Does not make it to the browser.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 3.4.x

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

In our knowledge base, we have some examples that I think are relevant. Can you have a look at this section

https://ag-grid.zendesk.com/hc/en-us/articles/360017496292-Why-some-exports-are-missing-

We believe this should get you kickstarted, but if you don't think this covers your use case, please feel free to follow up on this thread.

**Comment by fidian** [comment]
I can not access the page. It is behind a login page and I don't have
credentials.

**Comment by AhmedAGadir** [comment]
Hi,

Here is the contents of the article:


If you want to use our own internal classes in typescript, you might find that some of them are not exported such that you can use them directly:

 

ie (THIS WON'T WORK):

import {CellClassParams} from "ag-grid-community";

 

as opposed to (THIS WORKS AS OF V19.0)

import {CellClassParams} from "ag-grid-community/dist/lib/entities/colDef"; 

 

The reason to export only a subset of them is that we ourself use some of them in the ag-grid-enterprise project, and these are the ones that are included in the exports.

 

Note that if you find yourself importing these classes, you are going to be responsible for changing the paths if we were to move/rename a file

 

We are aware that it would be better to export all the classes so users would ever need to import from "ag-grid-community", that is why we have an item in our pipeline to change our build so we automatically export everything

https://www.ag-grid.com/ag-grid-pipeline/  

Project structure improvements	AG-1267	Automatically export all classes and interfaces to main.ts / main.js
 

Note that at this time, we don't have an ETA for this, and is up to the users to do the import by providing the path to the class. If you do struggle to find the path for a class, you are more than welcomed to raise this through support and we will help you find the correct path.

 

To see all the classes that can be imported by just referencing "ag-grid-community" check this file

 

https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-community/src/ts/main.ts

**Comment by fidian** [comment]
It sounds as though the exports should be there but are not yet done because those exports are lower on the priority list.

When trying to look up AG-1267, I do not see it at the site you referenced, https://www.ag-grid.com/ag-grid-pipeline/ - is that the right location to check?

Since this is a design decision, would it be possible to get a comment added to the file to explain why imports are missing so future bug reports are not submitted?

**Comment by spiko-md** [comment]
This is still an issue

**Comment by JabbyPanda** [comment]
https://ag-grid.zendesk.com/hc/en-us/articles/360016497631-Typescript-typings-this-event-is-missing-or-the-signature-is-not-as-accurate-as-possible-why-
