### ISSUE TITLE
[ColumnState] Columns not present in column state are displayed first

### ISSUE THREAD

**Issue by Jiiieeef** [ag-grid/ag-grid#3266]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Hello,
I have an app where it's possible to save many configs, which correspond to the current state of the grid (getColumnState, getColumnGroupState, getSortModel and getFilterModel).
Another feature of my app, is to be able to add columns to the grid.
If i save a config, create a column and then, load a config where this new column isn't present, it will be placed first.

To reproduce this: https://stackblitz.com/edit/angular-t8nkmj
* Hide column 2;
* Save the column state;
* Add a new column, "[added] column 4" will be added to the grid;
* Restore the column state;
* Display column 4;
=> it will be placed first while it should be placed last.

How to prevent to display columns not present is column state at first ? Should I open a bug to the Zendesk support ?

* **ag-Grid version:** 21.0.0

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

* **Language:** all

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

This is working as expected.

Have a look at this example: https://next.plnkr.co/edit/aOYhCer3F3FcuKK7

You will need to use deltaColumnMode

Regards,
Davis
