### ISSUE TITLE
v21.1.0 Dynamic Charting Labels Along X-Axis Ingeligible

### ISSUE THREAD

**Issue by sam-araiza** [ag-grid/ag-grid#3270]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
After (v21.1.0): https://cl.ly/ec9ebd03ff89
Happens when using the Chart Range feature after selecting multiple rows.

**Expected behavior**

Before (v21.0.1): https://cl.ly/d5cd08528ee0
Labels along the x-axis should be legible

**Please tell us about your environment:**

Node, Mongo, Vue 2.6.10

* **ag-Grid version:** 21.1.0

v21.1.0

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6 and Vue 2.6.10

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by deathmoves** [comment]
Hi,

The xAxis label rotation can be changed via xAxis.labelRotation property. See:

https://www.ag-grid.com/javascript-grid-charts-customisation-bar/#example-custom-bar-chart

**Comment by sam-araiza** [comment]
@deathmoves It's good to know we can manually set them, but does this mean that they will no longer be auto-rotated the way it was before as seen here?  https://cl.ly/ec9ebd03ff89

Thanks.

**Comment by sam-araiza** [comment]
* Seen here: https://cl.ly/d5cd08528ee0

**Comment by sam-araiza** [comment]
Well, I added ```xAxis.labelRotation = 45```, which the documentation claims is already the default, and that fixes the xAxis. However, this also changes the yAxis label rotation to 45 degs...
I tried doing both the above and ```yAxis.labelRotation = 0```, but that didn't do anything. At least it's better than what I had before, but still not quite the solution I'm hoping for. Hopefully we can look into this. Thanks! Also, as a paid partner, where should our team be submitting our bugs and feature requests?

**Comment by davis4acca** [comment]
Hi,

We have investigated this issue and determined that this is not a defect. The xAxis label rotation can be changed via xAxis.labelRotation property. Please see: https://www.ag-grid.com/javascript-grid-charts-customisation-bar/#example-custom-bar-chart

Regards,
Davis
