### ISSUE TITLE
The grid, when given less than the initial count, puts in empty rows.

### ISSUE THREAD

**Issue by happilymarrieddad** [ag-grid/ag-grid#3272]
![Selection_451](https://user-images.githubusercontent.com/6416323/61569585-375fc780-aa45-11e9-8e04-928d34873594.png)
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
The grid, when given less than the initial count, puts in empty rows.

**Expected behavior**
I'm sure there is just a setting for this but I've spent several hours on the docs and googling and I can't seem to get rid of the extra rows.

**Please tell us about your environment:**
Linux Mint, ag-grid community, Vue

* **ag-Grid version:** 21.1.0

* **Browser:**
google chrome

* **Language:** 
Vue

**Comment by kmanikandanmca2008** [comment]
@happilymarrieddad  Hi, Did you find the solution for your problem? I need the same behavior.
