### ISSUE TITLE
custom cellRenderer redux connected component not working after upgrading react-redux to 6.0 version

### ISSUE THREAD

**Issue by amitgaikwad02bright** [ag-grid/ag-grid#3283]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using redux connected functional component as cell render with react-redux package version 6+, cellRenderer is not working &  following error is getting logged

> Uncaught Invariant Violation: Could not find "store" in the context of "Connect(CountryCellRenderer)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(CountryCellRenderer) in connect options.
 
I have tried using **reactNext true**, but it seems to work with connected component is _class component_. for _functional component_ "ref can not be used" error get logged

**Expected behavior**

redux connected functional component should work fine & props should get passed to cell renderer.
 
**Minimal reproduction of the problem with instructions**

react-redux@6+ failing example
code sandbox example with react-redux@6  https://codesandbox.io/s/withered-haze-rfy5b?fontsize=14

**What is the motivation / use case for changing the behavior?**

using redux connected component as cell renderer to pass application state directly inside cell renderer

**Please tell us about your environment:**

React-redxu@6+ 

* **ag-grid-react version:** 21.1.0

* **ag-Grid/ag-Grid-Community version:**   21.1.0

* **React version:**  16.8.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by spautz** [comment]
We ran into this as well -- here's how we fixed it:
* Wrap the cellRenderer component in a `React.forwardRef` and pass the ref down to an element. Docs for that are at https://reactjs.org/docs/forwarding-refs.html
* If the cellRenderer component is connected to redux, you have to pass a _fourth_ argument to its `connect()`, to set a `forwardRef: true` option. Docs for the options are at https://github.com/reduxjs/react-redux/blob/master/docs/api/connect.md#options-object

We had to do this for other components we were passing to ag-grid-react as well -- specifically noRowsOverlayComponent and agColumnHeader.

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

There was a bug around this a while back, but reactNext + react 16 should fix it for class-based components

There is an outstanding bug for functional components that we are hoping to fix for the next release - once done it should work for functional components too.

Regards,

Ahmed

**Comment by deanp70** [comment]
Hi, thanks for creating this awesome package. I'm trying to create a custom filter which is connected to redux. I can make the filter work properly (i.e. filter the row data as intended) but can't manage to get ag-grid to recognize getModel, setModel, isFilterActive.

Are there any working examples for a connected filter I can refer to? Thanks!

**Comment by deanp70** [comment]
Hey @davis4acca, do you know if this is an open issue? Or are there any examples? Thanks in advance!
