### ISSUE TITLE
refreshCells doesn't refresh aggregation rows

### ISSUE THREAD

**Issue by doroshko** [ag-grid/ag-grid#3284]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
I'm using **ag-grid enterprise**.

**Reproducible Scenario**
I created a plunker that demonstrates the current behavior.
Group row shows sum of it's rows = 150 (10 + 20 + 30 + 40 + 50).
Click "Update One Value" button, it will change 1st row value and trigger refresh cells. Modified value will be displayed in 1st row, but agg row with sum will still remain the same.

https://plnkr.co/edit/JLaqb0rHfqiKzMUFgYVN?p=preview

**Current behavior**
While updating row model directly (not via `rowNode.setDataValue(colKey, value)`), and then calling `api.refreshCells({force: true});`, it updates only row was modified, but doesn't update agg sum row.

**Expected behavior**
`api.refreshCells({force: true});` should update aggregation group row with sum value too.

* **ag-Grid version:** 21.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

* **Language:** all

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

We have investigated this issue and determined that this is not a bug.

`rowData[0].a = randomValue;`

We would don't mutate the row data directly and use one of our recommended methods. Please see https://www.ag-grid.com/javascript-grid-data-update/
