### ISSUE TITLE
resetFilterValues method ?

### ISSUE THREAD

**Issue by jiangyh1024** [ag-grid/ag-grid#3287]
![image](https://user-images.githubusercontent.com/34930870/62098354-8830b500-b2bc-11e9-95c9-8189fcf793e3.png)

I used it, but the method is not on the object

![image](https://user-images.githubusercontent.com/34930870/62098376-9a125800-b2bc-11e9-91b6-d61558699ba2.png)

![image](https://user-images.githubusercontent.com/34930870/62098377-9da5df00-b2bc-11e9-8998-a52fa6c3c497.png)

version 21.1.0

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/62099020-47866b00-b2bf-11e9-9f2b-32da4084ad86.png)

regard it as any type works

**Comment by ReinisV** [comment]
This is still an issue and casting to `any` is a workaround, not a fix. This issue should be reopened and the interface should be updated.
