### ISSUE TITLE
Angular: autoSizeColumn(...) does not work with serverSide & datasource 

### ISSUE THREAD

**Issue by acgrama** [ag-grid/ag-grid#3289]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behaviour:** 
I am reproducing here a problem I have in my application (built using Angular 6 and ag-grid v21.0.1) with server side row model & datasource: no matter where I call columnApi.autoSizeColumn(...) - onGridReady(), onFirstDataRendered(), onRowDataChanged(), etc., the column is never resized, probably because it is called before the datasource getRows() has finished.

After the rows have been rendered, if I use the column menu's "autosize this column' option, this works ok. It also works correctly if I call autoSizeColumn() artificially when the rows are guaranteed to have been rendered, for instance from a custom context menu action.

**Expected behaviour:** 
I want to be able to auto resize columns after the data has been rendered from a datasource.

**Reproducing plunker example:**
I have built a toy application that reproduces this problem in this Plunker:
[https://next.plnkr.co/edit/TgI1gZVnKfppJ3F5?preview](https://next.plnkr.co/edit/TgI1gZVnKfppJ3F5?preview)

It is based on ag-grid docs examples listing athlete data. I modified it to return a hardcoded array of data from the datasource. One of the athletes has an artificially long name ("Michael Phelps with a really long name").
Despite calling autoSizeColumn() in both onGridReady() and onFirstDataRendered(), the column is not resized:

```
  onFirstDataRendered(params) {
    this.gridColumnApi.autoSizeColumn('athlete');
  }

  onGridReady(params) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    this.gridApi.setColumnDefs(this.columnDefs);
    this.gridApi.setServerSideDatasource(this.datasource);
    this.gridColumnApi.autoSizeColumn('athlete');
  }
```

![table](https://user-images.githubusercontent.com/1415729/62119270-7ac8fa00-b2bf-11e9-9d82-fead17c9fe2a.JPG)

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue: AG-3211 Add server side event for onFirstDataLoaded

Note you can workaround this by seeing if block state pageStatus is loaded and then call autosize.

https://www.ag-grid.com/javascript-grid-server-side-model-grouping/#example-purge

**Comment by miguelg1583** [comment]
I make a worka

> Hi,
> 
> Thank you for your email. We are aware of this issue and have a feature request in our backlog:
> 
> You can follow the status of feature requests, bugs and releases using our pipeline:
> https://www.ag-grid.com/ag-grid-pipeline/
> 
> If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact [info@ag-grid.com](mailto:info@ag-grid.com) for access. This is our primary channel for Support.
> 
> This is the reference and summary of the relevant issue: AG-3211 Add server side event for onFirstDataLoaded
> 
> Note you can workaround this by seeing if block state pageStatus is loaded and then call autosize.
> 
> https://www.ag-grid.com/javascript-grid-server-side-model-grouping/#example-purge

I cant find that, but make a workaround using (rowDataChanged) event. Thanks
