### ISSUE TITLE
React updating columnDefinitions causes open/closed state to be forgotten

### ISSUE THREAD

**Issue by SevereOverfl0w** [ag-grid/ag-grid#3293]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

http://plnkr.co/edit/6dqPANjVuGXQ8TUMgkUR?p=preview

**Current behavior**

When a column group is expanded, when adding a new column the expanded column group is closed

**Expected behavior**

ag-grid will keep the column group expanded as it was before the column was added.

* **ag-Grid version:** 21.1.0

* **Browser:** "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0", (also Chrome 74, but I cannot get the userAgent out of that machine)

* **Language:** all

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

We have investigated this issue and determined that this is not a bug. If you would like to keep the state of expanded/collapsed column groups we would recommend that you listen to the columnGroupOpened event and save the column group state. 

After adding a column you can then restore this state through the column API. 

Hope this helps,

Ahmed
ag-Grid Support
