### ISSUE TITLE
Middle mouse click does not trigger rowClicked event

### ISSUE THREAD

**Issue by thielmal** [ag-grid/ag-grid#3295]
**I'm submitting a bug report**

https://next.plnkr.co/edit/eQSmQC7Dai0JbSbs

**Current behavior**
Middle mouse clicks don't trigger a "rowClicked" event.

**Expected behavior**
The documentation of "suppressMiddleClickScrolls" suggests that setting the option to true should result in "rowClicked" events being sent when a row is clicked with the middle mouse button: https://www.ag-grid.com/javascript-grid-properties/#miscellaneous

The issue is caused by modern browsers not triggering a "click" event but an "auxclick" event on middle mouse clicks which the grid does not listen for and does not consider in the triggering of the "rowClicked" event.

Use-Case: I want to open items in a new tab on middle mouse click compared to opening it in the same tab on a left-click.

* **ag-Grid version:** 21.1.0

* **Browser:**
Chrome, Edge, Firefox

* **Language:** all

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

This is working as expected. 
Note that Firefox and chrome does not fire middle click event natively.

You can workaround this by listening to mouse down and up events and firing your own click event.

Hope this helps.

**Comment by thielmal** [comment]
@davis4acca They do however fire the "auxclick" event.

Listening to the mouse events manually requires a big overhead to manage the listeners manually ( The grid does, for example, not expose through the "onMouseUp" event) and to determine which row or cell the event was fired on. As far as I see, there is no API available to determine a row by on screen position.

I think  the additional options "onRowAuxclicked" and "onCellAuxclicked" would be in line with the existing functions "on[...]Clicked", "on[...]DoubleClicked", and "onCellContextMenu" and, looking at the code, shouldn't be too hard to implement.

**Comment by Ruud-cb** [comment]
@davis4acca Could you perhaps reply to @thielmal latest comment? I think this should be added although it is more of a feature request then a bug. A previous feature request has been made at the enterprise repository: https://github.com/ag-grid/ag-grid-enterprise/issues/17 but I cannot find AG-183 in the ag-grid pipeline.

Perhaps good to reconsider? Opening in new tab is what I am aiming for with the middle mouse button, so far there is no way to do this.

**Comment by nitoloz** [comment]
Have the same problem as @Ruud-cb and can't neither find AG-183 nor gte it working with ` "ag-grid-angular": "25.1.0"`. @davis4acca could you please help finding out if there is any solution for this problem?
