### ISSUE TITLE
enhance agselect cell editor

### ISSUE THREAD

**Issue by jiangyh1024** [ag-grid/ag-grid#3296]
pass array object
[
{ displayName: 'Country1', value: 1 },
{ displayName: 'Country2', value: 2 },
{ displayName: 'Country3', value: 2 },
{ displayName: 'Country4', value: 3 },
]

after editing, the underlying value should be the value field. (we can use cellrenderer to show the displayName).

Because in database, we should save countryId instead of countryName

and in this way, we no longer need to implement custom select editor by using thrid party library

Don't know if it is possible to add this functionality

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Could you please give us some more information regarding this?

Could you please crate a plunker with your current progress and send us a description of:

1. Expected behavior
2. Actual behavior

Regards,
Davis

**Comment by jiangyh1024** [comment]
currently I have to implement custom cell select editor using kendo-combobox

![image](https://user-images.githubusercontent.com/34930870/63065748-dc34ce00-bf39-11e9-9f32-af8db3217e1d.png)
![image](https://user-images.githubusercontent.com/34930870/63065760-e5be3600-bf39-11e9-8610-e80871d819c7.png)

the getValue() method will return the 
![image](https://user-images.githubusercontent.com/34930870/63065783-f8d10600-bf39-11e9-91e7-58e7115f9cfd.png)
value field

I use it like this
![image](https://user-images.githubusercontent.com/34930870/63065851-3df53800-bf3a-11e9-9753-08b9ec43e3e0.png)

this dsReport data is from back-end and the field is 'reportId' 

dsReport data and grid data are from different apis

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
