### ISSUE TITLE
www.ag-grid.com is down

### ISSUE THREAD

**Issue by cnrudd** [ag-grid/ag-grid#3297]
https://www.ag-grid.com/  does not load.

Chrome Output:

This site can’t be reached www.ag-grid.com took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_TIMED_OUT

**Comment by rmc-software** [comment]
We are working with our hosting service to remedy this ASAP.

Apologies for the inconvenience this may be causing.

**Comment by balazssoltesz** [comment]
Is there any link to download latest documentation? Especially about the charting feature. I have a deadline tomorrow so it's quite important for me. Any help appreciated.

**Comment by rmc-software** [comment]
While this issue is being resolved we will provide an alternative link to the ag-grid shortly.

**Comment by megulo25** [comment]
Here's a snapshot of their site from July 12, 2019. Javascript items will not render though.

https://web.archive.org/web/20190712103717/https://www.ag-grid.com/

**Comment by rmc-software** [comment]
As a temporary measure please use this link instead: http://34.240.64.39/

**Comment by balazssoltesz** [comment]
> As a temporary measure please use this link instead: http://34.240.64.39/

wow. thank you very much! it's perfect for this time.

**Comment by rmc-software** [comment]
While we are continuing to resolve this issue with our hosting service we have created instance

**Comment by rmc-software** [comment]
While we continue to try and resolve this issue with our hosting service our website can be reached at: www.ag-grid.co.uk

**Comment by lyinghill** [comment]
hey bro, Not fixed yet？http://34.240.64.39/ can not connect just now; 
any other way?

**Comment by alyalin** [comment]
www.ag-grid.co.uk also not working.

**Comment by rmc-software** [comment]
The issue hasn't been completely resolved but you www.ag-grid.com should now redirect to www.ag-grid.co.uk. Are you still having issues?

**Comment by alyalin** [comment]
http://www.ag-grid.co.uk/ is now working for me, thanks!

**Comment by uvtzxpm** [comment]
The changelog doesn't work for me:
https://www.ag-grid.co.uk/ag-grid-changelog/

**Comment by rmc-software** [comment]
To minimize disruption we are postponing further changes until the weekend. Once complete there will be no need for the redirect to .co.uk and should allow all parts of the site to work as normal, such as the changelog. 

Apologies for the inconvenience this is causing.

**Comment by BirdyUK** [comment]
Just a heads up, you are leaking sensitive server data on ag-grid.com through a php include error.

![Screenshot_2019-08-03 ag-Grid](https://user-images.githubusercontent.com/25714822/62408241-5de13f00-b5bd-11e9-884c-1e1700ec83fe.png)

**Comment by rmc-software** [comment]
Thanks for the heads up.
