### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by Neskews** [ag-grid/ag-grid#3300]
You have a typo in the pagination documentation:
https://www.ag-grid.com/javascript-grid-pagination/#customising-pagination

> 0 based, so he 5th page

Should be: 

> 0 based, so the 5th page

![Bildschirmfoto 2019-08-05 um 14 16 03](https://user-images.githubusercontent.com/29442471/62464104-05ac6780-b78c-11e9-9451-403133066011.png)

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for letting us know, we will be sure to fix this.

Regards,

Ahmed 
ag-Grid Support

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3217 Typo in documentation : https://www.ag-grid.com/javascript-grid-pagination/#customising-pagination


You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket- 


Regards

Davis‍
