### ISSUE TITLE
rangeSelectionChanged event.finished is only true at initial change, but false on the final change

### ISSUE THREAD

**Issue by robtaussig** [ag-grid/ag-grid#3309]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Current behavior**
I created a custom header component in React and want it to change its state based on whether it is within the current selectionRange (between columnStart and columnEnd). For performance purposes, I only want to check for this at the end of the selectionRange change event -- and using the finished property would be perfect for this. Unfortunately, the finished property is only true on the initial selectionRange change, and then is false for every change thereafter.

**Expected behavior**
For the finished property to be true only on the last change of the selection event.

**Please tell us about your environment:**
Windows 7, React ag-grid

* **ag-Grid version:** 21.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 OpenFin/12.69.43.21 Safari/537.36"

* **Language:** [all]

`

    export default class ColumnHeader extends React.Component {
        state = {
            focused: false,
        }

        constructor(props) {
            super(props);
            this.handleRangeSelectionChange = this.handleRangeSelectionChange.bind(this);
            props.api.addEventListener('rangeSelectionChanged', this.handleRangeSelectionChange);
        }

        handleRangeSelectionChange(event) {
            //event.finished is initially true, but then false for all events for the same rangeSelectionChange
        }

        render() {
            return (<div>{this.props.column.colId}</div>)
        }
    }

`

**Comment by gportela85** [comment]
The issue has been fixed in the latest branch and will be patched in the next release

**Comment by bez4pieci** [comment]
This problem still exists in v22.0.0 using Angular
