### ISSUE TITLE
ag-grid tree view - add temp row to a group

### ISSUE THREAD

**Issue by arielshad** [ag-grid/ag-grid#3310]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'
```

I'm looking to add temporary row to a group in a tree view (row model type: server side) is it possible?

what I'm looking to do it to temporary add a row, inline edit it and then send it to the server to actually create/save it

**Comment by davis4acca** [comment]
Hi,

Note that ag-grid doesn't provide support through GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

In any case, you should be able to find more information in the following links:

https://www.ag-grid.com/javascript-grid-value-handlers/

This ticket is flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
