### ISSUE TITLE
ag-grid community license 

### ISSUE THREAD

**Issue by krishnapsarthi** [ag-grid/ag-grid#3312]
I am using the MIT licensed package: ag-grid-community for a public website, to be deployed on cloud. Going through **https://www.ag-grid.com/license-pricing.php** page, I noticed Deployment license for cloud based applications. Do I need to get a deployment license or a community license would suffice as my website is a public website.

Thanks,

**Comment by davis4acca** [comment]
Hi,

if you using the community version, no license is needed. Only if you wish to use the enterprise features will you need a valid license. The MIT licence will suffice for your website if you are using the community version of the grid.

Regards,
Davis
