### ISSUE TITLE
Copy to clipboard - different behaviour with one or multiple cells.

### ISSUE THREAD

**Issue by jfstephe** [ag-grid/ag-grid#3313]
Different behaviour is seen is you copy a cell or a number of cells. This is because in the [first scenario](https://github.com/ag-grid/ag-grid/blob/d0e4b19a0e5489a89f65c6777b793c8869a359e6/packages/ag-grid-enterprise/src/clipboardService.ts#L478
) 'toString()' is NOT called on the value but in the [second scenario](https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-enterprise/src/clipboardService.ts#L529) it is.

I think it should probably call the valueFormatter on the column and use that value as, for example, if the value is a moment() object then we don't control the toString() behaviour.

**Comment by davis4acca** [comment]
Hi,

We will follow this up on zendesk.

Regards,
Davis
