### ISSUE TITLE
Resetting set filters slows down the grid filtering

### ISSUE THREAD

**Issue by koolhuman** [ag-grid/ag-grid#3314]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
This is an issue in ag-grid where the grid becomes slow when you reset the 'set filter' for a grid which has 39+ columns. Please refer to the below link in the documents, it mentions that you have to reset the set filters manually when new data is loaded in the grid via transaction updates. And also refer to AG-3059 which states that you have to reset the set filters because the transaction updates in the grid was not working well with "Select All" option in the set filter (This defect was fixed in the latest version of ag-grid 21.1.0)

https://www.ag-grid.com/javascript-grid-filter-set/#refresh-after-edit-or-transcation-update 
AG-3059 - Select all in filter does not tick newly added/edited values when (Select All) is pressed

I just tried replicating that with 39+ columns. I tried to create a plunker in this plunker I am loading new data to make it simple for you to understand.

Plunker - https://next.plnkr.co/edit/PoZhTfuPAeNX42TL

**Providing a Reproducible Scenario**
Steps to reproduce

1) Check the athlete column1 filter is working as expected. 
2) Filter athlete column1 with some values (filtering is fast as expected) 
3) Click on Load New Data Button 
4) Filter athlete column1 with some values (filtering is fast as expected) 
5) Click "Reset Filters" button 
6) Check the athlete column1 filter again, the rows loads after a considerable amount of delay now. (Filtering becomes slow)

Load New Data button - fetches new data from a json file. In plunker i am just loading the same data set but in ideal world this data would be changing based on what is returned by web Api backend. And since the data is changed via transaction updates i have to reset the set filters to overcome the "Select All" issue (AG 3059). Which i have tried to demonstrate by creating a separate button.

Reset Filters Button - Checks for any set filters which are active, calls resetFilterValues() function on that filter and sets the model back after resetting that filter.

After you click on Reset Filters Button, the grid filtering becomes very slow.

I am using ag-grid-angular
* **ag-Grid version:** 21.1.0

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks,

Davis

**Comment by AhmedAGadir** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-3306 - Investigate improving the performance of calling resetFilterValues when calling it for all columns in the screen

Note that this is parked as of this time, just because of its complexity, which means that even though we are aware of this issue, we don't have any easy solution as of this time

For the time being, all we can suggest is to follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by sharatbaradia** [comment]
Hello, I do see the below request will be complete when the release 23.1.0 comes out. Could you please let us know if this was just to investigate or there is an actual solution to this issue?

AG-3306 | Investigate improving the performance of calling resetFilterValues when calling it for all columns in the screen

Thank you!
