### ISSUE TITLE
Excel Export string type not working

### ISSUE THREAD

**Issue by jenb34** [ag-grid/ag-grid#3320]
Export to Excel string type is not working, issue can be seen in your example:
https://www.ag-grid.com/javascript-grid-excel/#example-2-export-with-styles

Silver column is not exported as string with leading zeros.

I can also replicate locally (from v18 onwards).

**Comment by davis4acca** [comment]
Hi,

This works as expected.

Have a look at this example: https://next.plnkr.co/edit/48tviZIzf9Lpil77?preview

Regards,
Davisx
