### ISSUE TITLE
Hiding colums via Column menu hides menu when scrolled horizontal

### ISSUE THREAD

**Issue by sdir456** [ag-grid/ag-grid#3324]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

1. goto https://www.ag-grid.com/example.php#/
2. scroll horizontal to the right end
3. open column menu
4. click on colum management tab
5. hide some columns

**Current behavior**
The column menu closes when hiding columns. 
![column_menu_closes](https://user-images.githubusercontent.com/6534142/63344835-a0db3a80-c351-11e9-9b3d-eea7e174c9bc.gif)

**Expected behavior**
The column menu should stay opened. You can see the expected behaviour when you omit Step 2 (see above).
![column_menu_stays_open](https://user-images.githubusercontent.com/6534142/63344872-bbadaf00-c351-11e9-9ea5-e4dae9a89a74.gif)

* **ag-Grid version:** 21.1.0

* **Browser:**
	- Chrome 76 on Windows 1803
	- Firefox 68 on Windows 1803
	- IE 11 on Windows 1803
	- Safari 11.1.1 on MacOS 10.13.5

**Comment by davis4acca** [comment]
Hi,

This works as expected.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
