### ISSUE TITLE
React: Updating sort property in columnDef is ignored by ColumnFactory.createColumn if colId is set.

### ISSUE THREAD

**Issue by davewthompson** [ag-grid/ag-grid#3325]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproduction**
https://github.com/davewthompson/aggrid-sandpit
1. Click Clear.
2. Click Set Sorted Columns. Nothing changes.

Aggrid Helpdesk ticket: https://ag-grid.zendesk.com/hc/en-us/requests/8454

**Current behavior**
Column sort properties are not set in the grid's columns if columns have a colId.

**Expected behavior**
The sort properties are successfully set in the target column.

**Investigation**
When you don't supply colIds, a new column is created inside the ColumnFactory; findExistingColumn returns null and a new column is created - the constructor sets the sort property of the column from the supplied colDef.

However, if an existing column is found (you supply a colDef) then the new colDef is set using the column's setColDef function. However, *the sort property of the column is not modified*.

**Please tell us about your environment:**
CreateReactApp, macOS.

**ag-Grid version:** 
21.1.0

**Browser:**
Chrome 76 / macOS

**Language:** 
React ES6

**Comment by davis4acca** [comment]
Hi,

We will continue to answer in zendesk.

Aggrid Helpdesk ticket: https://ag-grid.zendesk.com/hc/en-us/requests/8454

Kind Regards,
Davis
