### ISSUE TITLE
Master/Detail cant't custom detail cell renderer

### ISSUE THREAD

**Issue by lyinghill** [ag-grid/ag-grid#3326]
hello,I want custom detail cell renderer, but it does’t work, The browser error log is as follows：
![image](https://user-images.githubusercontent.com/36785468/63399025-cd4e8f80-c401-11e9-86a5-65c0326c0c72.png)

I write following the example below：
[example-custom-detail-cell-renderer-with-a-form](https://www.ag-grid.com/javascript-grid-master-detail/#example-custom-detail-cell-renderer-with-a-form)

ag-Grid version:
21.1.1（the ag-grid-vue version is 21.1.0）

Browser:
Chrome 75 / macOS

Language:
vue

**Comment by lyinghill** [comment]
resolved

**Comment by Montai** [comment]
How?

**Comment by FrankyFrankFrank** [comment]
How?
