### ISSUE TITLE
Column Pinning Style Bug

### ISSUE THREAD

**Issue by DLCnow** [ag-grid/ag-grid#3327]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
I am working with ag-grid-react and ag-grid-community in a react application.
I found a bug(maybe) about the column pinning.
And I got the same behaviour in your official website.

**Current behavior**
When I clicked a pinned column it would be focused like this:
![image](https://user-images.githubusercontent.com/24190152/63425519-52a66400-c443-11e9-9842-368c9b1c4208.png)
But when a click a blank space where not in table's body , the clicked cell will lost it's side border like this:
![image](https://user-images.githubusercontent.com/24190152/63425798-f4c64c00-c443-11e9-82f1-cb382566cf95.png)
BTW, if I keep my focus in table all the time, the cell's border shows normal.

**Expected behavior**
Is it a bug in here or it shoulds be the case. 
look forward to your reply ^_^

**Please tell us about your environment:**
macOS Mojave 10.14.x
node 12.x.x
vscode 1.37.x
yarn 1.17.x

* **ag-Grid version:** X.X.X
ag-grid-react 20.2.0
ag-grid-community 20.2.0

* **Browser:**
Chrome Version 76.0.3809.100

* **Language:** [JavaScripts X.X | ES6/7 | ES5]

**Comment by davis4acca** [comment]
Hi,

This has been fixed in the newer version. Please update to fix this issue.

Kind Regards,
Davis
