### ISSUE TITLE
Online documentation for v19.1.4 is not available 

### ISSUE THREAD

**Issue by imaynotbereal** [ag-grid/ag-grid#3329]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I am trying to view documentation for v19.1.4 but I get the below error:
```
Not Found
The requested URL /archive/19.1.4/documentation-main/documentation.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

**Expected behavior**
For other older version of ag-grid, for example 18.1.0, I am able to view the documentation online
https://www.ag-grid.com/archive/18.1.0/documentation-main/documentation.php

* **ag-Grid version:** 19.1.4

* **Browser:**
N.A.

* **Language:** 
N.A.

**Comment by anatoly314** [comment]
Same issue for `v18.1.1`, error 404
https://www.ag-grid.com/archive/18.1.1/documentation-main/documentation.php

**Comment by davis4acca** [comment]
Hi,

Currently the older versions are available here as .zip files: https://www.ag-grid.com/archive/

We will make them available again in the next few weeks.

Kind Regards,
Davis
