### ISSUE TITLE
Website: React page tells you to install angular

### ISSUE THREAD

**Issue by gricey432** [ag-grid/ag-grid#3332]
Couldn't see a repo for the website, this seems like the closest place. On the page https://www.ag-grid.com/best-react-data-grid/ the large code box at the top of the page says to install ag grid angular into your react project.

<img width="790" alt="get-started" src="https://user-images.githubusercontent.com/1611345/63672429-46484f80-c825-11e9-8a2b-97232749fba7.png">

**Comment by seanlandsman** [comment]
Thanks for reporting this - this will be fixed in our next release (in the next day or two)
