### ISSUE TITLE
Wronte "text" mouse cursor on grouping drop zone (IE)

### ISSUE THREAD

**Issue by sdir456** [ag-grid/ag-grid#3333]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1. Open Internet Explorer
2. Goto https://www.ag-grid.com/example.php
3. Move the mouse over the grouping drop zone "Drag here to set row groups"
4. Mouse cursor changes to "text" insted of "default"

**Current behaviour.**
The "text" cursor should only be applied on elements that allow the user to select or input text.
The placeholder text "Drag here to set row groups" cannot be selected.
![cursor](https://user-images.githubusercontent.com/6534142/63679671-1c296a00-c7f2-11e9-8045-599226f47e97.gif)

**Expected behavior**
The cursor should be "default".

**Please tell us about your environment:**
Internet Explorer 11 on Windows 1803

* **ag-Grid version:** 21.1.0

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request / BUG  in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue: 

AG-3305 
Wrong "text" mouse cursor on grouping drop zone in IE
