### ISSUE TITLE
Row selection behavior and documentation inconsistent

### ISSUE THREAD

**Issue by AmyBlankenship** [ag-grid/ag-grid#3336]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
The documentation for Row Selection starts with 
`Select a row by clicking on it. Selecting a row will remove previous selection unless you hold down ctrl while clicking. `
This implies that you can deselect a row by left-clicking on it, which is not the case.
The rowDeselection property documentation says 
`rowDeselection: Set to true or false. If true, then rows will be deselected if you hold down ctrl + click the row. Normal behaviour with the grid disallows deselection of nodes (ie once a node is selected, it remains selected until another row is selected in its place).`
This accurately describes the behavior that happens.

However, in a single-select scenario, especially when not using check box selection, a more consistent experience is for a left-click to select the row and a second left-click to deselect it, without having to depress the ctrl key. However, the grid code prevents any possible workaround, because cellClicked and rowClicked events don't process until after the selection has already changed. This means that you can get deselection to work properly (if you first select with a check box), but selection by clicking on a row results in immediate deselection, because your code to deselect a selected row on cell or row click will fire when the row is first clicked as well as when it is clicked again to deselect, like so

`handleRowClick (event) {
        // Ag-Grid wants a ctrl-click for deselect, we want to react to click only
        const node = event.node;
        if (invoke(node, 'isSelected')) {
            node.setSelected(false);
            this.props.onRowDeselect();
        }
    }`

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We will have a look at clearing up any misconceptions in our documentation.

Please note if you would like to deselect a row with a click you can gridOptions.rowMultiSelectWithClick=true. See https://www.ag-grid.com/javascript-grid-selection/#multi-select-single-click

Hope this helps,

Ahmed
