### ISSUE TITLE
Pinned columns and non pinned columns / rows get out of sync.

### ISSUE THREAD

**Issue by vivvea** [ag-grid/ag-grid#3337]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

On Ag-grid [demo](https://www.ag-grid.com/example.php#/)

1. Choose Theme Material
2. Scroll all the way to the bottom of the data
3. Pin language column to the left.
4. Double click the Game of Choice cell editable on the last row

**Current behavior**
The Pinned column rows and non pinnend rows go out of sync.

**Expected behavior**
Rows stay synced

**Please tell us about your environment:**
Windows 10, Chrome
![ag-grid](https://user-images.githubusercontent.com/54615503/63829956-91707880-c973-11e9-971e-85e94617a86b.png)

* **ag-Grid version:** 21.1.1
This has been introduced in some of the 21xx versions

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. 
As a workaround, you could use a custom editor that does not increase the cell in size when in edit mode. Please see https://www.ag-grid.com/javascript-grid-cell-editor/

Hope this helps,

Ahmed
