### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getColSpanningList' of null

### ISSUE THREAD

**Issue by antoinebrault** [ag-grid/ag-grid#3339]
From https://github.com/ag-grid/ag-grid/issues/3134

> When initiating start editing cell, get the above error. The error occurs only when the grid has horizontal scroll. The function in which the error occurs is getRenderedCellForColumn (
> 
> https://github.com/ag-grid/ag-grid/blob/714ced17a4e62f52d319792670d4e0240afe1145/packages/ag-grid-community/src/ts/rendering/rowComp.ts#L1408
> 
> ).
> It seems that the cells which are not visible have the cell component reference as null.
> Here is the stack trace:
> rowComp.js:1186 Uncaught TypeError: Cannot read property 'getColSpanningList' of null
> at rowComp.js:1186
> at Array.filter ()
> at t.getRenderedCellForColumn (rowComp.js:1186)
> at t.getComponentForCell (rowRenderer.js:886)
> at t.startEditingCell (rowRenderer.js:865)
> at e.startEditingCell (gridApi.js:814)
> at listgrid.tsx:327
> at Array.forEach ()
> at Object.updrow [as handler] (listgrid.tsx:325)
> at HTMLSpanElement. (listgrid.tsx:261)

https://plnkr.co/edit/aEJKx9POpuNOhc8eA9F2?p=info

**Comment by gportela85** [comment]
Thanks for reporting, this issue has been fixed in the latest branch.
