### ISSUE TITLE
agGridReact.ts still references componentWillReceiveProps()

### ISSUE THREAD

**Issue by sljidexcel** [ag-grid/ag-grid#3343]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Running our webapp with React **16.9** yields the following console warning:

```
react-dom.development.js:15292 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AgGridReact
```

This seems strange considering this commit on 5 April:
https://github.com/ag-grid/ag-grid/pull/3081/commits/7ce87018aa3a6c46c40e9d86adc1f7a68cf7d429

And this pull request on 20 July:
https://github.com/ag-grid/ag-grid/pull/3214

Did this somehow fall through the cracks?  Are there any plans to address this?  Many thanks in advance for any/all responses.

**Expected behavior**
`src/agGridReact.ts` gets rewritten to not reference the deprecated function, otherwise we have to revert back to React **16.8**.

**Please tell us about your environment:**
* MacOS, VSCode, NPM, Node.Js

* **ag-Grid version:**
21.1.0

* **Browser:**
All

* **Language:**
ES6

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by sljidexcel** [comment]
Greetings,

Issue resubmitted with Plunker link:

https://github.com/ag-grid/ag-grid/issues/3366

http://next.plnkr.co/edit/MSfA1biU4UzgssJ3?open=Hello.js&deferRun=1

Thank you very much.

Vr | Shade L. Jenifer

**Comment by austincondiff** [comment]
I am getting this issue as well 

```Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AgGridReact```

**Comment by khryshyn** [comment]
The issue still exist

**Comment by ksrb** [comment]
Seeing this issue with:
```json
    "@ag-grid-community/all-modules": "22.0.0",
    "@ag-grid-community/react": "22.0.0",
```

**Comment by seanlandsman** [comment]
@ksrb can you provide an example of this issue occurring with 22 ?

**Comment by ksrb** [comment]
Sorry nvm it was on my side 😅 .
