### ISSUE TITLE
[proposal] Make api ts types better

### ISSUE THREAD

**Issue by NikitaIT** [ag-grid/ag-grid#3346]
There are several types that are needed in most projects
```
type ExcludedByFrameworkMethods =
  | "afterGuiAttached"
  | "destroy"
  | "getFrameworkComponentInstance"
  | "getGui"
  | "init";
export type IFrameworkFilterComp = Omit<IFilterComp, ExcludedByFrameworkMethods>;
// ... etc IFrameworkXXXX
```
And with ColDef wrapper, types like:
```
export interface BaseColDefParams<TData = any, TContext = any> {
    node: RowNode;
    data: TData;
    colDef: ColDef<TData, TContext>;
    column: Column<TData, TContext>;
    api: GridApi | null | undefined;
    columnApi: ColumnApi | null | undefined;
    context: TContext;
}
```

May be I can contribute via merge request to improve typing by separating interfaces, adding helper types to the component framework, and adding generic types?

Doing explicit casting and any everywhere becomes a headache.

And now I have usefull extensions:
```
declare module "ag-grid-community" {
  interface ColDef {
    // main ag-grid feature for me - batch edit
    manyCellEditor?: any;
    manyCellEditorParams?: any;
    // define the rules for the transport of value is better where it is declared
    exportToExcel?(params: ProcessCellForExportParams): string;
    exportToCsv?(params: ProcessCellForExportParams): string;
    exportToClipboard?(params: ProcessCellForExportParams): string;
  }
}
```

And i think send `params!: ICellEditorParams;` with data patch - bad idea, because of this, I constantly write code like this, or I clone components, or add mixins. 

```
<template lang="pug">
  VTCheckbox(:params="params" :value="value" @input="setValue")
</template>

<script lang="ts">
type TValue = boolean | null; // exported
@Component({ components: { AdPlatformButtons } })
class VTCheckboxCellEditor extends Vue implements IFrameworkCellEditorComp<TValue>  {
  params!: ICellEditorParams; // used for DI Editor Settings and GlobalContext
  value: TValue = null;
  setValue(value: TValue) {
    this.value = value;
  }
  getValue(): TValue {
    return this.value;
  }
  created() {
    this.setValue(this.params.value);
  }
}
export default VTCheckboxCellEditor;
</script>
```

but i want params as props:
```
cellEditorFramework: VTCheckbox// :params="params" :value="getValue()" @input="setValue"
```
I have never had cases where params in data would really be needed.

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3279    Allow for stronger typing of main classes in ag-grid
