### ISSUE TITLE
Bubble Chart marker not sizing based on weighting / 3 dimension

### ISSUE THREAD

**Issue by mattspeller** [ag-grid/ag-grid#3349]
[X] bug report

**Providing a Reproducible Scenario**
https://next.plnkr.co/edit/0eP0K2qsFkPhBauH

**Current behavior**
All bubbles are the same size
**Expected behavior**
all bubble markers should be sized based on series value

**Please tell us about your environment:**
see plunker

* **ag-Grid version:** 21.2.0

* **Browser:**
chrome

* **Language:** 
react/js

**Comment by yay** [comment]
In your case, you have the category `Country` column  selected. This is where x-values are coming from, and every other column contains the y-values. There are 3 such columns, so you get 3 series.
If you want to plot a bubble chart, you need 3 numeric columns.

The first will correspond to the x-value.
The second, to the y-value.
The third, to the radius value.

**Comment by mattspeller** [comment]
that makes sense - thank you.

However surely it makes sense to also allow data labels to be specified for each tool tip using a dimension column too? I shouldn't have to format the tool tip for each data point if I specify a dimension column. removing the country shows the bubble chart as expected, however the series reads Gold vs Silver when each point should be a Country.

Also, it probably is wise to update the Scatter Plot documentation page to show this 3d array in action or more useful have a separate page for bubble chart with the plunkr example working. (multiple onGridReady functions and bindings on the scatterplot documentation example)
