### ISSUE TITLE
Bubble Chart does not provide Dimension Label to describe points / Providing a Dimension Column to Bubble Chart shows Scatterplot instead

### ISSUE THREAD

**Issue by mattspeller** [ag-grid/ag-grid#3351]
[X] bug report

https://next.plnkr.co/edit/vpbThQ9VwGcFRZQI

**Current behavior**

providing a dimension column along with three series columns does not show the name of the series on the data points. Unable to tell which data row the bubble relates to. Instead the dimension column included with three series columns changes the display type to a scatter plot.

**Expected behavior**

Hovering over the bubble should be able to use a Dimension column to describe the bubble. In the case attached, it should be possible to provide a country to the bubble cellRange and the dimension column used to describe the row that displays as a bubble. (see comments in code) I would expect at very least the inclusion of a Dimension column to not change a Bubble chart into a scatter plot. (I provided three series columns and set the chart type to bubble)

**Please tell us about your environment:**
see plunkr

* **ag-Grid version:** 21.2.0

* **Browser:** chrome

* **Language:** react / JS

**Comment by deathmoves** [comment]
Looks a problem in your tooltipRenderer. I've removed it and updated your plunker and it displays tooltips correctly.

https://next.plnkr.co/edit/Ho5CtA4qZUgKwUqU

**Comment by mattspeller** [comment]
@deathmoves - thanks for the help but you miss the point. There is no way to show the bubble is related to a particular country. I was simply showing how it could work in the tooltip renderer but there is no concept of groupLabel or showing the related dimension for a set of series. For example, hovering over the top left bubble should be able to tell me that is United Kingdom related data.

**Comment by yay** [comment]
@mattspeller  How do you envision this to work? The `Country` data is not in the selection, so the chart is not aware of it. And why the `Country` column in particular? It could the `A` or `B` column or some column with string data other than Country. What if you have two bubble series plotted, in which case you'll be using 6 numeric columns, should you have access to the column data used by other series from the tooltip renderer of the current series?

I see what you are trying to accomplish in your specific case, but how would you like it to work in general?

![Screen Shot 2019-09-04 at 09 50 59](https://user-images.githubusercontent.com/1799756/64240259-89778200-cef9-11e9-8b9d-5146cb6b3d8a.png)

**Comment by mattspeller** [comment]
@yay - all good questions. The simplest solution would be to provide the full data row in the datum parameter to the tooltip to allow customisation on hover. However, this has a draw back of needing to write a tooltip renderer function per chart type, as there would be different needs and outcomes depending on the visualisation. The datum inclusion of all data would be the most generic I guess.

Excel does offer the ability to add a column for the data labels on a bubble, see the below.

![image](https://user-images.githubusercontent.com/31129130/64242709-ed9c4500-cefd-11e9-8599-c91ee3e5a10a.png)

right click on a bubble,
click add data labels,
then right click again,
choose format data labels, 
choose value from cells
provide column range

Using this analogy, I think the bubble for multiple series would work the same as a single series. If a dimension column is provided then this value is shown as the data label and the tooltip title.

If the bubble chart accepted a dimension column (and didn't change to a scatter plot) and used this dimension column when formatting and also provided the full data row in the Datum when rendering labels and tooltips then I think any scenario could be covered.

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3291  Charts - Add access to all row data for tooltips
