### ISSUE TITLE
TypeScript - missing various gridOptions

### ISSUE THREAD

**Issue by qualton** [ag-grid/ag-grid#3356]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

Various typings appear to be missing from GridOptions.  This may fall under "AG-2102 Typescript - Improve typescript typings" but I am simply reporting a few specifics that may be addressed directly before more elaborate automated processes can be implemented.

https://www.ag-grid.com/javascript-grid-events/
componentStateChanged ==> onComponentStateChanged

https://www.ag-grid.com/javascript-grid-overlay-component/
gridOptions.noRowsOverlayComponentParams
gridOptions.loadingOverlayComponentParams

**Providing Reproducible Scenario**
https://codesandbox.io/s/compassionate-curran-url0l?fontsize=14

Note the typing errors on AgGridReact instance in index.tsx

**Current behavior**

TypeScript type checking errors

**Expected behavior**

no type errors

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
19.1.4

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We have included your findings into "AG-2102 Typescript - Improve typescript typings".

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by AlokBisht** [comment]
In the change log I can see the issue fixed under 19.1.1 but it was reported under 19.1.4. did it got miss?
Also I'm checking in the version 22.**.** but the typing for the onComponentStateChanged is still not available.
