### ISSUE TITLE
Issue in pagination with server-side row model

### ISSUE THREAD

**Issue by pulkitguptaIN** [ag-grid/ag-grid#3358]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using pagination with server-side row model ag-grid throws this error
```
TypeError: Cannot read property 'rowIndex' of undefined
    at ServerSideCache.getTopLevelRowDisplayedIndex
```
see Plunker: https://next.plnkr.co/edit/MLcPhj4wXtDIm478?preview

**Expected behavior**
Pagination should work with server-side row model

**Please tell us about your environment:**
* **Operating System:** Windows 10
* **ag-Grid version:** 21.2.0
* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
* **Language:**
Angular 5.1.3

**Comment by oleg088097** [comment]
Same with 21.2.1, AngularJS 1.6

**Comment by hervedevos** [comment]
Same issue here (Angular 8)

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2659 - If cache block size is larger than the number of rows added to the DOM, or grid size is less than cacheBlockSize, calling setRowHeight has unexpected effects
