### ISSUE TITLE
Pinned row checkboxes

### ISSUE THREAD

**Issue by Instinctlol** [ag-grid/ag-grid#3365]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When using checkbox columns, there's currently no checkbox shown on pinned rows, at least by default. See [example on plunker](https://plnkr.co/edit/X221vVOXilrpudHKy7UH?p=preview).

**Expected behavior**

I would expect a checkbox to also show on pinned rows by default or a setting to make it work.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
* Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/76.0.3809.132 Chrome/76.0.3809.132 Safari/537.36

* **Language:** [all]

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by jtillwickEA** [comment]
As an enterprise customer, is there a way to get this feature prioritized?

**Comment by AG-Zoheil** [comment]
Hi @jtillwickEA,

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil

**Comment by jtillwickEA** [comment]
Too much work.  I found a better way using postSortRows anyway.

**Comment by SamChilversCyara** [comment]
Sorry, why is this logged as a Feature Request in your pipeline (AG-2339)? That implies new functionality. This is a degradation of existing functionality that used to work in versions pervious to 32.2. This will stop me from implementing fixes for deprecated features and will mean my application will display deprecation warnings to my customers in the console. Will this actually be addressed?
