### ISSUE TITLE
ag-theme-dark has overlapping "select all" checkbox in list - 21.2.1

### ISSUE THREAD

**Issue by crumhorn** [ag-grid/ag-grid#3368]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Plunkr showing issue: 

https://plnkr.co/edit/x7mUmhrNL0mrY0GORVg5?p=preview

This Plunkr copies the plunkr from https://www.ag-grid.com/javascript-grid-filter-set/ and all it does is change the theme to "ag-theme-dark" rather than belham in "app.component.ts" at the top.

It's probable this bug is the same as https://github.com/ag-grid/ag-grid/issues/1989 - but that one was never followed up on and never showed a Plunkr.

**Current behavior**
Run the Plunkr. Open the "Athlete" column's column menu (hamburger) and go to the filter section (in the middle tab). You will see that "Select All" overlaps the first item in the checkbox list (Barack Obama).

**Expected behavior**
"Select All" should be on the left of the search field (if there is one) or on its own line, as it is on normal column filters. See the "Sport" column where it seems to be fine.

**Please tell us about your environment:**
Windows 7

* **ag-Grid version:** X.X.X
21.2.1

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.5.3

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. This has been raised before, and we are currently tracking already in our pipeline with the following number and description.

AG-3295 - 'Select All' option in Set Filter is misaligned in ag-theme-fresh, ag-theme-dark, ag-theme-blue, and ag-theme-bootstrap

Note that there isn't a workaround at the moment, but this is high on our priority list

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

Regards

Ahmed‍

**Comment by AG-Zoheil** [comment]
Hi @SrikanthChebrolu,

The pipeline is for upcoming changes. **AG-3295** was fixed in `v22.`
