### ISSUE TITLE
translation file miss spell

### ISSUE THREAD

**Issue by gmareater** [ag-grid/ag-grid#3373]
hi
in your website with this address:
https://www.ag-grid.com/javascript-grid-internationalisation/

the provided template has a miss spell for "not equal"
it should be "notEqual", but currently has an extra "S" at the end "notEquals" (and i dont know which one is grammatically right, English is not my main language)

**Comment by gmareater** [comment]
it should not get stale, it should get fixed :)

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks
