### ISSUE TITLE
Server-side Datasource failCallback is not working

### ISSUE THREAD

**Issue by zibra** [ag-grid/ag-grid#3380]
Calling failCallback in Server-side Datasource solution seems to do nothing. Nothing change on the grid in such scenario (loading spinner is still presented to the user.

More details here: https://stackoverflow.com/questions/50973325/ag-grid-serverside-row-model-params-failcallback

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-3005 | Server Side Row Model - Allow failCallback to provide with a mechanism to retry fetching data (ie allow configuring a timeout)

**Comment by acgrama** [comment]
Still a problem in April 2021...why have the callback at all if it doesn't do anything? :D

**Comment by hasanmuzak** [comment]
Still continues :( Any update=

**Comment by ten-jpw** [comment]
Any update?

**Comment by StephenCooper** [comment]
> Still continues :( Any update=

Please open a new issue along with a reproduction on the latest version if this is still an issue.
