### ISSUE TITLE
All webfont icons are blank in Angular 8 when importing styles in component level instead of in global level

### ISSUE THREAD

**Issue by junxie6** [ag-grid/ag-grid#3381]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Steps to reproduce**

Edit src/app/app.component.scss to import the styles in component level instead of in global level (src/styles.scss):

```
:host ::ng-deep {
    @import "~ag-grid-community/src/styles/ag-grid";
    @import "~ag-grid-community/src/styles/ag-theme-balham/sass/ag-theme-balham";
}
```

**Current behavior**

SCSS generated the font-face as:

```
@font-face {
  -shadowcsshost-no-combinator ::ng-deep {
    font-family: "agGridBalham";
    src: url("data:application/x-font-ttf;charset=utf-8;base64,....=") format("truetype");
    font-weight: normal;
    font-style: normal;
  }
}
```

**Expected behavior**

Note: I think it may be a better idea to let the users import the webfont separately. Otherwise, it will generate a redundant @font-face { ... } block (considering the base64 encoded font size is 11.5 KB).

```
@font-face {
  font-family: "agGridBalham";
  src: url("data:application/x-font-ttf;charset=utf-8;base64,...") format("truetype");
  font-weight: normal;
  font-style: normal;
}
```

**Please tell us about your environment:** Ubuntu 18.04.3 LTS

* **ag-Grid version:** 21.2.1

* **Browser:** Chrome Version 76.0.3809.132 (Official Build) (64-bit)

* **Language:** [TypeScript 3.5.3 - Angular 8.2.5]

**Comment by yveslange** [comment]
#3376

**Comment by junftnt** [comment]
Importing the styles within the `:host ::ng-deep { ... }` block of a Angular component will also cause the following warning message when doing the production build `ng build --prod`:

> WARNING in Invalid property name '' at 2187:2. Ignoring.

The issue can be solved by adding a $disable-icon-font flag in the ag-grid-community/src/styles/ag-theme-base/sass/_ag-theme-base.scss:

From:

```
@if $icon-font-family == 'agGridBalham' or
    $icon-font-family == 'agGridMaterial' or
    $icon-font-family == 'agGridClassic' {
```

To:

```
@if $disable-icon-font == false and ($icon-font-family == 'agGridBalham' or
    $icon-font-family == 'agGridMaterial' or
    $icon-font-family == 'agGridClassic') {
```

So that the user can disable the icon font and import it manually:

src/app/app.component.scss:

```
:host ::ng-deep {
  $disable-icon-font: true;

  @import "~ag-grid-community/src/styles/ag-grid";
  @import "~ag-grid-community/src/styles/ag-theme-balham/sass/ag-theme-balham";
}
```

src/styles.scss:

`@import "~ag-grid-community/src/styles/webfont/agGridBalhamFont";`

**Comment by Prontsevich** [comment]
I have the same issue when trying to customize my app. I'm using Angular material on my project. I created 2 custom themes for material and want to customize ag-grid according to selected theme.
Everything work except icons.

my theme.scss: 
```scss
@import '~@angular/material/theming';

@include mat-core();

.dark-orange {
  @import 'colors/dark-orange';
  @include angular-material-theme($orange-dark-theme);

  @import '~ag-grid-community/src/styles/ag-grid.scss';
  @import '~ag-grid-community/src/styles/ag-theme-balham-dark/sass/ag-theme-balham-dark.scss';
}

.light-orange {
  @import 'colors/light-orange';
  @include angular-material-theme($orange-light-theme);

  @import '~ag-grid-community/src/styles/ag-grid.scss';
  @import '~ag-grid-community/src/styles/ag-theme-balham/sass/ag-theme-balham.scss';
}
```
