### ISSUE TITLE
ag-unselectable doesnt allow me to select my component

### ISSUE THREAD

**Issue by ross2711** [ag-grid/ag-grid#3390]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

Here is a working [**Stackblitz** ](https://stackblitz.com/edit/angu1ar)example.

[**stackoverflow**](https://stackoverflow.com/questions/58005418/ag-unselectable-doesnt-allow-me-to-select-my-dropdown) 

**Current behavior**
It appears ag-unselectable is added by ag-grid but I'm unsure how to override it or turn it off. Everytime I select the scrollbar on the dropdown component, the component then disappears or is 'unselectable'.

**Expected behavior**
The dropdown component should not disappear when the scrollbar is selected.

**Please tell us about your environment:**
Windows

* **ag-Grid version:** X.X.X
ag-grid-angular: "^21.0.1"

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript: "~3.4.3"
Framework, Angular: "~8.0.3"

**Comment by gustawdaniel** [comment]
this should not be closed. I have the sam problem.

**Comment by gustawdaniel** [comment]
I solved by reading docs:

https://www.ag-grid.com/javascript-grid-selection-overview/

and StackOverflow

https://stackoverflow.com/questions/51863331/copy-and-select-the-text-from-ag-grid

Finally only `stackoverflow` contains answer how to allow for selecting content.

**Comment by audetto** [comment]
What is lacking in the doc is the thinking behind.

Why would I not want it to be selectable?
