### ISSUE TITLE
ag-grid work well in IE 11,but crashed in IE 10

### ISSUE THREAD

**Issue by Perity2015** [ag-grid/ag-grid#3391]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

import "core-js/stable";
import "regenerator-runtime/runtime";

[
"@babel/preset-env",
{
"targets": "> 0.25%, not dead",
"useBuiltIns": "entry",
"corejs": 3
}
]

Using the above configuration, ag-grid works normally on IE 11.

When I used ie10, the browser crashed and reported the following error.

ag-Grid: unable to find bean reference paginationProxy while initialising beans
ag-Grid: unable to find bean reference rowRenderer while initialising beans
ag-Grid: unable to find bean reference columnHoverService while initialising beans
ag-Grid: unable to find bean reference maxDivHeightScaler while initialising beans
ag-Grid: unable to find bean reference paginationProxy while initialising changeDetectionService
......

Unhandled rejection TypeError: 无法获取未定义或 null 引用的属性“apply”

**Expected behavior**

**It also works well in IE 10**

**Please tell us about your environment:**

* **ag-Grid version:** 20.2.0

* **Browser:**[IE 10 ]

* **Language:** [TypeScript 3.5.3]

**Comment by seanlandsman** [comment]
As per this link here https://www.ag-grid.com/javascript-grid-supported-browsers/ , I'm afraid we only support down to IE11

thanks

**Comment by Perity2015** [comment]
thanks.
