### ISSUE TITLE
column definition with link to open ngx-bootstrap modal

### ISSUE THREAD

**Issue by aguskianto** [ag-grid/ag-grid#3395]
columnDefs = [
    {
      headerName: 'MS Name',
      headerClass: 'ms_name',
      field: 'name',
      lockPinned: true,
      pinned: 'left',
      cellClass: 'lock-pinned',
      width: 110,
      cellRenderer(params) {
        return params.value ? '<a (click)=\"openModal(template)\">' + params.value + '</a>' : '';
      }
    }
];

I am creating a link that open ngx-bootstrap modal. I try to openModal directly from HTML and it works but when passing the link as part of column definition, it just doesn't work.

Is there a way to trigger a modal from a link defined in column definition?

**Comment by mwingler** [comment]
Hello @aguskianto ,
did you find any solution for this? :)
