### ISSUE TITLE
autoHeight rendering all the rows to calculate height

### ISSUE THREAD

**Issue by iscopettaRiverbed** [ag-grid/ag-grid#3398]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
I managed to visibly reproduce the issue here, without autoHeight in both the table and the column, it will only print in console 100 statements about the element having been rendered,
with autoHeight in both it will show in console that it's rendering elements for all the data, and it will be much slower to load
https://plnkr.co/edit/gC8fGcsKLqTTJsM7nDTl?p=preview

**Current behavior**

It is rendering all the rows to calculate the height when autoHeight is used on both the table and one of the columns, both at initial load and if calling resetRowHeights

**Expected behavior**

It should calculate height by rendering only the components in the visible page (lazy).

* **ag-Grid version:** 21.2.1

**Comment by shuheb** [comment]
Hi,

Thank you for your message.

This is not a problem with ag-grid, it is a limitation on browsers on how much data they can easily display on one web page, for this reason we recommend users to not use Grid Auto Height when displaying a large number of rows.

If showing large amounts of data, it is not advisable to use Grid Auto Height. Instead use the grid as normal and the grid's row virtualisation will take care of this problem for you.

You can read more about this here: https://www.ag-grid.com/javascript-grid-width-and-height/#auto-height

Hope this helps.

Kind Regards,
Shuheb

**Comment by iscopettaRiverbed** [comment]
Hi Shureb,
did you check my plunkr?
This is not about the grid autoheight, but the one in the column definition.
I am paginating, so only a subset is visible and everything is working fine and as expected with domLayout='autoHeight', only the rows of the current visible page are rendered to determine the grid height.

Once I use autoHeight in one of the columns (you can check that in the plunkr by commenting/commenting that line and seeing the difference in speed and the console messages) all the rows, even non visible ones, are rendered (the console output in the plunkr makes it really obvious).

I am opening a bug because this was supposedly fixed with:
AG-2646 |   | 20.2.0 | Hidden columns are used to calculate height when using autoHeight
Witch means it was both acknowledged as a bug, and considered fixed, but in the plunkr I provided a scenario where the bug still reproduces, all the non visible columns are rendered unnecessarily to calculate the current page height.
