### ISSUE TITLE
Framework component is missing the method getValue()

### ISSUE THREAD

**Issue by Paul6552** [ag-grid/ag-grid#3402]
I'm submitting a ...
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'

**Requesting Community Support**

**Providing a Reproducible Scenario**
[https://stackoverflow.com/questions/58062993/ag-grid-framework-component-is-missing-the-method-getvalue](https://stackoverflow.com/questions/58062993/ag-grid-framework-component-is-missing-the-method-getvalue)

**Please tell us about your environment:**
react 19.9.0
typescript 3.5.3
ES5

* **ag-Grid version:** 
21.2.1

* **Browser:**
chrome version 74

**Comment by seanlandsman** [comment]
Answered - thanks

**Comment by bluSCALE4** [comment]
@seanlandsman can you provide the details to your answer?
