### ISSUE TITLE
Clear filter model after push x in filter string (Edge)

### ISSUE THREAD

**Issue by NikitaRomanetz** [ag-grid/ag-grid#3407]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Nothing happens in Edge

Expected behavior
After push the button clear in search string([x] in edge, ie11), ag-grid must clear filter model.

**Please tell us about your environment:**
ag-Grid version:
21.2.2

Browser:
Edge 42.17134.1.0 , Microsoft EdgeHTML 17.17134

Language: [all | TypeScript X.X | ES6/7 | ES5]
All

example how it worck in edge
![edge](https://user-images.githubusercontent.com/12935255/65764761-2e2b5f00-e148-11e9-9018-2765faba4608.gif)
example how it worck in ie11
![ie11](https://user-images.githubusercontent.com/12935255/65764762-2e2b5f00-e148-11e9-9450-32d0a6e23424.gif)

**Comment by cmunteanu** [comment]
I have the same problem. When pressing the "x" button in Edge, the text is cleared (ok), but the filter does not reset. The data in the grid remain filtered and there is no way to reset the filter, other that writing something in the textbox and after that deleting it using the backspace key.

**Comment by olsn** [comment]
Still persists in Microsoft Edge 18.
