### ISSUE TITLE
unable to find bean reference frameworkOverrides while initialising BeanStub

### ISSUE THREAD

**Issue by Impress221** [ag-grid/ag-grid#3410]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

Current behaviour.
agGrid throws error:  unable to find bean reference frameworkOverrides while initialising BeanStub

Expected behaviour. 
no errors

**Current behavior**
I have custom hierarchy and it created with autoGroupColumnDef;
As i need to change autoGroupColumnDef data on fly and after changing this data, agGrid doesnt updates, im destroying this component and rerender, by using key property.
So,when i do autoGroupColumnDef, then i do gridKey++,component rerenders i got this error.If i use setTimeout(100ms), i have no error, but i don't want to use it. Also, i'm using enterprise version on my project.

**Expected behavior**
No errors.

**Please tell us about your environment:**
Linux

* **ag-Grid version:** X.X.X
    "ag-grid": "^18.1.2",
    "ag-grid-community": "^21.2.1",
    "ag-grid-enterprise": "^21.2.1",
    "ag-grid-react": "^21.2.1"

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7 React.js

**Comment by seanlandsman** [comment]
Hi

You need to remove ag-grid from your list of dependencies - ag-grid-community replaces ag-grid.

thanks

**Comment by Impress221** [comment]
Very nice answer. I'm not using this dependency, it's old string from package.json and this package is not imported.

**Comment by Amiryy** [comment]
I am having the same issue, any chance to get real assistance here?
In my case, I am using the treeData feature on my grid with incrementing `key` on the parent element (div) containing my `AgGridReact` component to refresh when column definitions change.

**Comment by Impress221** [comment]
> assistance

No, I think developers think, that it's normal.

**Comment by jpodpro** [comment]
just noticed this pop up for me also.

**Comment by weihong1028** [comment]
> I am having the same issue, any chance to get real assistance here?
> In my case, I am using the treeData feature on my grid with incrementing `key` on the parent element (div) containing my `AgGridReact` component to refresh when column definitions change.

you need to set cacheBlockSize value which is bigger then the child rowData's length.

**Comment by divisha-ensemble** [comment]
> I am having the same issue, any chance to get real assistance here?
> In my case, I am using the treeData feature on my grid with incrementing `key` on the parent element (div) containing my `AgGridReact` component to refresh when column definitions change.

Did you find a solution

**Comment by bseiryk** [comment]
In my case, the root cause of this error was that I am trying to use the API of grid which has been unmounted.
And my solution was whenever grid is remounted again API object has to replaced.
`onGridReady(params) { this.gridApi = params.api; }`

**Comment by PjotrB** [comment]
After upgrading from 24.1.0 to 25.3.0, these errors magically disappeared for us.

Commands I did:
`npm install ag-grid-community@latest`
`npm install ag-grid-react@latest`

So far nothing seems broken as a result of this, but YMMV...
