### ISSUE TITLE
Cell text selection bleeds into other cells when double-clicking text while column is set to not editable

### ISSUE THREAD

**Issue by Cinema180** [ag-grid/ag-grid#3411]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1) Set `enableCellTextSelection: true` and `defaultColDef: { editable: false }`
2) Double-click on the text within a cell
Result: The highlighted selection bleeds into other cells

I have been able to reproduce this behaviour in the example grid at https://www.ag-grid.com/javascript-grid-clipboard/#using-enablecelltextselection (you first need to set `defaultColDef: { editable: false }` in Plunker), as can be seen in this screenshot where I double-clicked on the text "United" in the Country column cell:

![image](https://user-images.githubusercontent.com/45290956/65879807-8c468500-e388-11e9-9c3d-7f2a9bc7c22c.png)

**Current behavior**
When `enableCellTextSelection: true` and `defaultColDef: { editable: false }` double-clicking on the text in a cell causes the highlighted selection to bleed over into other cells. 

**Expected behavior**
Only the text that is double-clicked on in the cell is selected (i.e. "United" in the above example).

**Please tell us about your environment:**

* **ag-Grid community:** 21.1.1

* **Browser:**
Chrome

* **Language:** [TypeScript 3.5.3 | ES6/7 | ES5]

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3517
Cell text selection bleeds into other cells when double-clicking text while column is set to not

**Comment by MarkHansenOC** [comment]
Hello davis4acca,

the problem is still there but the Problem AG-3517 no longer exists in the pipeline: https://www.ag-grid.com/ag-grid-pipeline/  

Will there be no solution?

**Comment by gportela85** [comment]
@MarkHansenOC This problem has been fixed and is no longer reproducible with the latest version of the grid. https://plnkr.co/edit/4BFyIZ1YklXAyimh

**Comment by MarkHansenOC** [comment]
Thanks for the hint
