### ISSUE TITLE
cellClassRules callback params do not include columnApi, when exporting excel

### ISSUE THREAD

**Issue by Vikciux** [ag-grid/ag-grid#3414]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Here is the modified example on plunker:
https://plnkr.co/edit/etB5wq4qlRW6futnaoCd?p=preview

**Current behavior**
params.columnApi is not available in cellClassRules callbacks. If you try to export excel from the provided plunker, then you will get an alert and exception.

**Expected behavior**
params.columnApi should be provided to cellClassRules callbacks. The problem is in ExcelCreator.styleLinker call to this.stylingService.processAllCellClasses.

* **ag-Grid version:** 21.2.2

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-3495 - columnApi not available in cellClassRules callback when exporting 

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
