### ISSUE TITLE
rowDrag not working with function

### ISSUE THREAD

**Issue by sachinshettigar** [ag-grid/ag-grid#3423]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Description**
if function returning true is passed to rowDrag property of column, then setSuppressRowDrag(false) does not unhide the rowDrag icon

**Plunker**: https://plnkr.co/edit/2cY77IG9R0vmPmFUF81B?p=preview

**Current behavior**
if function returning true is passed to rowDrag property of column, then setSuppressRowDrag(false) does not unhide the rowDrag icon

**Expected behavior**
When rowDrag property of column is set to true or a function returning true. it should unhide rowDrag icon when setSuppressRowDrag(false) is called

* **ag-Grid version:**21.2.1

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-3496 - calling setSuppressRowDrag(false) does not work when column definition defines row drag with a function 

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
