### ISSUE TITLE
ServerSide Row Model with pagination does not work 

### ISSUE THREAD

**Issue by klajd** [ag-grid/ag-grid#3427]
```
[x] bug report
[] feature request
[] support request
```

I was trying to use the serverSide model with pagination with our custom datasource.
The grid loads the first chunk of element and then it does not load the other chunks of data.

My setup is the following:
- grid-enterprise `v21.2.1`
- rowModelType `serverSide`
- dataSource Custom
- cacheBlockSize `100`
- paginationPageSize `20`

Actions:
- Try to go after page 4 and the ag-grid does not load the next 100 rows

Checkout the example I have changed to simulate the bug:  
https://plnkr.co/edit/hEXhQPbOoPQL9uqbANf5?p=preview

**Comment by rdunce** [comment]
Paging with serverside row model was rather borked in 21.1.1, Your plunker works with 21.2.2.

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


Regression 21.2.0- Server side row model + pagination + infinite scrolling does not work anymore for simple cases

Fixed version: 21.2.2
