### ISSUE TITLE
How to access Column API inside Custom Tool Panel

### ISSUE THREAD

**Issue by usman-anwar-techverx** [ag-grid/ag-grid#3428]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

I have added a custom tool panel in Ag Grid, I want to access **Ag Grid's Column Api** inside my custom tool panel component, to perform certain tasks such as getting column, filter, sort, group, pivot state as json. I can't access Column Api through `params: IToolPanelParams`.

Any help is appreciated. Thanks

* **ag-Grid version:** 21.0.x

* **Language:** [TypeScript 3.2.2]

**Comment by W4775** [comment]
I'm running into the same issue. Trying to add custom panel to allow saving column states but cant seem to access ColumnAPI through the IToolPanelParams.
