### ISSUE TITLE
Popup Editor closes with Mat-Datepicker/Mat-Select before value Change can be detected

### ISSUE THREAD

**Issue by alinamx** [ag-grid/ag-grid#3438]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Since the Update from Version 20 to Version 21 the Popup editors do not work correctly with Material components within them. I have an ag-grid with popup-editors that have the select-, datepicker- and an autocomplete-component of Angular Material in them.
I created a Plunker that has a datepicker editor in the third column.
[Plunker example](https://plnkr.co/edit/4NMb8eKu3WwNP6vWUaMr?p=preview)
When a new Date is chosen the console should print 'DATE: ' + the new chosen date
This does not happen on V21.
However if u change the version of ag-grid (provided in the index.html file as a comment) the output will appear when a date is chosen by click.

**Current behaviour.**
When I open the Datepicker and click on a date of the datepicker, no change event happens and the editor just closes. It works if i navigate with the keyboard, but not on mouse clicks.

**Expected behavior**
I would expect, that there is a change event before the editor popup closes.
As mentioned this happens with the Datepicker and the Dropdown-list.

**Please tell us about your environment:**
Windows, IntelliJ, Angular Frontend with yarn as a packet manager.

* **ag-Grid version:** 21.2.2
The error appears on all versions > 21.0.0 and didnt appear on smaller ones.

* **Browser:**
CHROME: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
FIREFOX: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

* **Language:** [Angular 8.3.8 | Material 8.2.2 | Ag-grid 21.2.2 | TypeScript 3.5.3 | ES5]

**Comment by SERGEES** [comment]
@alinamx i think in your case you can add panelClass="ag-custom-component-popup"to material datepicker.
`<mat-datepicker panelClass="ag-custom-component-popup" #picker></mat-datepicker>`
Unfortunately in my case I have to use ag-grid:19
and it looks like it doesnt work for the vercion...
