### ISSUE TITLE
React - invariant violation 170 with cellRenderers OR duplicate overlays with portals

### ISSUE THREAD

**Issue by qualton** [ag-grid/ag-grid#3450]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/TwvcwCcQF2yU7CgWyZjE?p=preview

Click the "Toggle Grid" button in the scenario (use reactNext=false) -- open browser console and see Error

Click the "Toggle Grid" button in the scenario (use reactNext=true) -- see other errors in console and note that there are duplicate no rows overlays created as portals

**Current behavior**
Create a custom cellRenderer component and register with grid.  
Unmount the grid while the grid is rendering (this might happen by a user going to another screen within an app)
Note that an error is generated in the browser console:

https://reactjs.org/docs/error-decoder.html/?invariant=170

> Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue.

Note that there is a previous related issue:
https://github.com/ag-grid/ag-grid-react/issues/120

and now with react 16+ we should use the 'reactNext={true}' property but if you do you will still receive an error:  "React Component 'YourCellRenderer' not created within 1000ms"

Also note that with reactNext={true} it is possible to get multiple instances of overlays via portals

**Expected behavior**
No error -- the ag-grid react component properly cleans up after itself and its async tasks

There should only be 1 overlay and the grid should ensure this happens regardless of how you call the gridApi.showNoRowsOverlay()

https://www.ag-grid.com/javascript-grid-overlays/#overlay-api
"you cannot show more than one overlay at any given time"

* **ag-Grid version:**
21.0.1
with react 16.8.6

* **Browser:**
any

* **Language:**
all

**Comment by qualton** [comment]
#3222

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Thank you for your email. This has been raised before, and was fixed in version 22.

AG-3585 - React - multiple invocations of showNoRowsOverlay result in multiple overlays

You can follow the status of fixes using our changelog: 

https://www.ag-grid.com/ag-grid-changelog/

Regards

Ahmed‍
