### ISSUE TITLE
Export csv : file name contains '.' makes export flow drop .csv extension

### ISSUE THREAD

**Issue by ArnonAfriat** [ag-grid/ag-grid#3451]
This is a bug in the 'export as csv' feature. Issue can be easily reproduced on ag-grid feature example in the following:
https://www.ag-grid.com/javascript-grid-export/

Reproduction steps in the url example above, in **any** language:
1. Scroll down to the export csv example in https://www.ag-grid.com/javascript-grid-export/.
2. Type in the File Name field - "foo".
3. Click on "export to CSV" button. Notice the downloaded file name is "foo.csv" - as expected.
4. Change the string in the File Name field to "foo.bar"
5. Click on "export to CSV" button. Notice the downloaded file name is "foo.bar" **without** the ".csv" extension, making the OS unable to recognize application relates to file etc.

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request / bug in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.





This is the reference and summary of the relevant issue:

AG-3586  CSV Export - If fileName contains ‘.' the grid doesn’t add .csv extension

**Comment by ArnonAfriat** [comment]
Hi Davis,

Yes, I am an ag-Grid Enterprise Customer, I am a developer for Nova
Measuring instruments Ltd (arnon-a@novami.com).
I'm not sure I understand the request to raise this issue in your Zendesk,
I thought this issue was already brought to their attention.

BR,
Arnon

‫בתאריך יום ב׳, 18 בנוב׳ 2019 ב-18:24 מאת ‪Davis Jaunbruns‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by shuheb** [comment]
Hi Arnon,

Thank you for your message.

We've investigated this issue and have found that this is not a bug.

This is the desired behaviour of the grid, that when you add a dot to the file name you will need to provide the extension yourself. 

Hope that helps.

Kind Regards,
Shuheb

**Comment by ArnonAfriat** [comment]
Is it mentioned in the documentation?

BR,
Arnon

בתאריך יום ג׳, 26 בנוב׳ 2019, 17:17, מאת Shuheb Ahmed ‏<
notifications@github.com>:

**Comment by afzal-qavi** [comment]
If file name contains "/" it's replacing it with "_"

for example if File Name is "DD/MM/YYYY" then the dowloaded file "DD_MM_YYYY"
