### ISSUE TITLE
onSelectionChanged has strange behaviour, if you select in onFilterChanged

### ISSUE THREAD

**Issue by woorsty** [ag-grid/ag-grid#3452]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I modified the plunker of Column Filter: Example Simple Filters 
https://plnkr.co/edit/0YXJ9qnFSykoisSmxnsl?p=preview

I just added these two methods:

```  
onFilterChanged = params => { 
    this.gridApi.forEachNode(row => {
      if (row.rowIndex === 0) {
        console.log('select');
        row.setSelected(true);
        return;
      }
    });
  };

  onSelectionChanged = params => {
    console.log('selection changed');
  }; 
```
and added them as events for Ag-Grid
```
< AgGridReact columnDefs = { this.state.columnDefs }
      defaultColDef = { this.state.defaultColDef }
      rowData = { this.state.rowData }
      onGridReady = { this.onGridReady }
      onFilterChanged = { this.onFilterChanged }
      onSelectionChanged = { this.onSelectionChanged }
      />
```

**Current behavior**

If i open a filter (for example for "Athlete") and type the name of the first athlete the 'selection changed' will be called once. That's fine. But if I start to write a filter-string, that not fits with the first value, the 'selection changed' will be called twice. If I continue to write again a diffrent name 'selection changed' will be called three times. And this increases everytime the selction changed.

To test this, just open the plunker, open the console and write in the "athelete"-filter 'missy schwen' and you will see, that everytime the selection changed, the event will be called once more.

**Expected behavior**

The onSelectionChanged method should allways be called once.
**Please tell us about your environment:**

Windows 10, Plunker
* **ag-Grid version:** 
I don't know, which version you use in your examples, but I guess it's the newest?

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

* **Language:** 
all

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

We have investigated this issue and determined that this is not a bug.

We would recommend that instead of using the rowIndex for selection, that you use api.getRowNode() and configure id's for your rows in gridOptions.getRowNodeId.

Regards,

Ahmed

**Comment by woorsty** [comment]
Thank you, that helped me.
