### ISSUE TITLE
Custom popup editor closes when element inside is clicked

### ISSUE THREAD

**Issue by yannickvandervleuten** [ag-grid/ag-grid#3453]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Continued from https://github.com/ag-grid/ag-grid/issues/3212. Custom editor closes unexpectedly when clicking on a select inside the editor. I have tried using both (click)="$event.stopPropagation()" and ag-custom-component-popup. But neither seems to work. I've tried placing them on multiple different elements but it doesn't affect it.

https://angular-wvc3vv.stackblitz.io
See stackblitz for example of project with event.stopPropagation().

What did work however was this https://github.com/ag-grid/ag-grid/issues/3212#issuecomment-506346192 dirty fix. Which I rewrote a bit to fit the new version. 

**Current behavior**
When clicking on an `<option>` in a `<select>` element the parent custom ag-grid popup editor closes. 

**Expected behavior**
The custom ag-grid popup editor stays open when an element is clicked inside of it. 

**Please tell us about your environment:**
* **ag-Grid version:** X.X.X
    "ag-grid-angular": "~21.2.1",
    "ag-grid-community": "~21.2.1",

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

* **Language:** Tested in typescript, presumably all

**Comment by cm0s** [comment]
I encounter the exact same problem. Any chance this bug will be fixed?

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3587 - Docs - Materials examples not working in v22 

Note that there isn't a workaround at the moment, but this is high in our priority list

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

Regards

Ahmed‍

**Comment by yannickvandervleuten** [comment]
Seems like it was marked as `Done`. Awaiting the release to mark this issue as done.

**Comment by AhmedAGadir** [comment]
Hi, 

Thank you for your email. Our consultants have prepared the following example for you:

https://stackblitz.com/edit/angular-neduxw

Regards,

Ahmed

**Comment by yannickvandervleuten** [comment]
It works. Closing this issue.

**Comment by developer-cormatix** [comment]
same issue arise with 

    "@ag-grid-community/angular": "^22.1.2",
    "@ag-grid-enterprise/all-modules": "^22.1.2",

and flag set to  stopEditingWhenGridLosesFocus: true,
