### ISSUE TITLE
Drag and Drop Bug [tested on ag-grid.com example page] 

### ISSUE THREAD

**Issue by inkbk** [ag-grid/ag-grid#3454]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Only cells on the first Row are seen when dragged. Safari affected
Tested here -> https://www.ag-grid.com/javascript-grid-drag-and-drop/
Recording of Bug -> https://imgur.com/a/f6DWHzO

**Expected behavior**

All of the cells should be visible while being dragged

**Please tell us about your environment:**

Reproducible on two machines
MacOS Mojave
version 10.14.15 (18F132) with Safari Version 12.1.1 (14607.2.6.1.1)

MacOS Catalina
version 10.15 with Safari Version 13.0.2 (15608.2.30.1.1) 

* **ag-Grid version:**   the version on this page https://www.ag-grid.com/javascript-grid-drag-and-drop/

* **Language:** The examples using Javascript/React/Angular and View all have this issue

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. This seems to be working on our end. 

Please see the attached GIF.

![Large GIF (896x592)](https://user-images.githubusercontent.com/33138421/69046931-f7f4b800-09f1-11ea-86de-187fbd519e9a.gif)

**Comment by inkbk** [comment]
> Hi,
> 
> Thank you for your email. This seems to be working on our end.
> 
> Please see the attached GIF.
> 
> ![Large GIF (896x592)](https://user-images.githubusercontent.com/33138421/69046931-f7f4b800-09f1-11ea-86de-187fbd519e9a.gif)

what version of safari was this? My issue has not gone away
