### ISSUE TITLE
Bar Chart Values on All Pivot Grids Wrong

### ISSUE THREAD

**Issue by rcbyrne** [ag-grid/ag-grid#3455]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
All bar charts on a pivot grids are wrong. The values are mismatched against the labels. This can be reproduced in the ag-grid demo page. 

https://www.ag-grid.com/example.php#/

- Click Pivot Mode
- Select Name
- Select Bank Balance
- Highlight and create bar chart
- Values are in incorrect order.

**Current behavior**
Labels are listed top to bottom, while the values are listed bottom to top.

**Expected behavior**
Labels and values match up

![image](https://user-images.githubusercontent.com/964609/67093176-f3e23a00-f1a8-11e9-8c01-5fbb5f3457ec.png)

**Comment by davis4acca** [comment]
Hi,

This should work in v22. If this is not the case please recreate the ticket.

Regards,
Davis
