### ISSUE TITLE
IsColumnFuncParams export missing in main.d.ts

### ISSUE THREAD

**Issue by omanoel** [ag-grid/ag-grid#3460]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
in typescript, a transpile error is thrown on the following line:
import { IsColumnFuncParams } from 'ag-grid';

due to this interface not being exported in main.d.ts

**Expected behavior**
I would expect it to be exported in the same way ColDef is.

**Please tell us about your environment:**

* **ag-Grid version:** 19.1

* **Browser:** N/A

* **Language:** [ TypeScript 3.2.2]

**Comment by davis4acca** [comment]
Hi,

This should be working in v22. Could you upgrade and if this issue persists, please recreate this issue.

Regards,
Davis

**Comment by Iamheathsmith** [comment]
Having the same issue with IsColumnFuncParams. we are using AG Grid version 22.1.1 and we are using the **@ag-grid-enterprise/all-modules** and all my imports are coming from that. This one is the only one that is causing issues. I am running 

- ag-Grid version: 22.1.1

- Browser: N/A

- Language: [ TypeScript 3.5.1]
