### ISSUE TITLE
Column header frozen when drug out of grid on iOS

### ISSUE THREAD

**Issue by JosNun** [ag-grid/ag-grid#3461]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Seems to happen on any grid where you can drag columns to pin them or remove them from the grid. Includes the main demo, and demos in the docs. Drag column header out of grid (either to pin it, or remove it).

**Current behavior**
On iOS (tested on 13.1.2), when dragging a column out of the grid to hide it, or dragging a column to one of the edges to pin it, the drag label freezes when the column is removed, and the column is "dropped" (It can't be drug back into the grid). The frozen labels also don't disappear until the page is reloaded.

![image](https://user-images.githubusercontent.com/7729878/67432718-c1737b00-f5b4-11e9-9351-a6f4540c4a7e.png)

**Expected behavior**
The column's drag label should disappear when the column is released. Also, the drag shouldn't be terminated until the column is released.

**Please tell us about your environment:**
iOS 13.1.2
	- Safari 13.0.1
    - Chrome 78

* **ag-Grid version:** X.X.X
21.2.2

* **Browser:**
- Mozilla/5.0 (iPad; CPU OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1
- Mozilla/5.0 (iPad; CPU OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/78.0.3904.67 Mobile/15E148 Safari/604.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi,

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3461 - column headers freeze when dragged on iPad

Note that we have raised this as likely to be picked up in the next 2/3 releases, feel free to follow up in a week or so for more details

You can follow the status of feature requests, bugs and releases using our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Regards

Bam‍

**Comment by JosNun** [comment]
Correction: The issue is labeled `AG-3581 column headers freeze when dragged on iPad` in the pipeline.

**Comment by Kushi171987** [comment]
Hi,

I am using the ag-grid in my react.js application with the following version.
"ag-grid-react": "20.0.0", getting the same issue on iPhone with a 13.x version. 

It seems to be fixed, I have tested the demo on iPhone and the bug was fixed.
On which version this bug was fixed ? so that I will update my application to that version.

Thank you,
Kushal Kumar
