### ISSUE TITLE
Types are broken with ts3.7

### ISSUE THREAD

**Issue by deser** [ag-grid/ag-grid#3467]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

With typescript 3.7.1-rc ag-grid fails:
node_modules/ag-grid-community/dist/lib/filter/provided/date/dateFilter.d.ts:5:10 - error TS2440: Import declaration conflicts with local declaration of 'IDateComparatorFunc'.

**Please tell us about your environment:**
"ag-grid-community": "21.2.2",
"ag-grid-react": "21.2.2",

* **ag-Grid version:** 21.2.2

**Comment by deser** [comment]
@ceolter ?

**Comment by mjadczak** [comment]
This issue is still present with the released version of 3.7 (3.7.2).

**Comment by seanlandsman** [comment]
This issue will be fixed in our next release, due out Monday

thanks

**Comment by FirstVertex** [comment]
You can suppress this error by adding this to your tsconfig under `compilerOptions`

```json
"skipLibCheck": true
```
