### ISSUE TITLE
Autosizing with resetRowHeights not working with reactNext={true}

### ISSUE THREAD

**Issue by leroydev** [ag-grid/ag-grid#3477]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using `reactNext={true}` combined with `resetRowHeights`, even with a timeout as mentioned in https://github.com/ag-grid/ag-grid/issues/3264#issuecomment-528820259, it won't autosize the row heights.

**Expected behavior**
It should autosize the row heights.

-----

Plunkr with `reactNext={true}`, where autosizing doesn't work: https://next.plnkr.co/edit/FxlxfTtKl0atY1Ux
Plunkr without, so autosizing works: https://next.plnkr.co/edit/y0PuWZ29f1WuWqd7

-----

* **ag-Grid version:** 21.2.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

* **Language:** all

**Comment by qualton** [comment]
I would also like to echo this issue

Here is an alternate plunkr showing the issue in an interactive fashion:
https://next.plnkr.co/edit/e3JHElrU1hZjdOgE?preview

Note that when reactNext is set and resetRowHeights is called then the custom cell renderer with red border will get clipped as its size is ignored during the measurements

**Comment by bsara** [comment]
Experiencing this issue as well, this creates a very poor user experience and could use a fix or work around ASAP.

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

In our knowledge base, we have some examples that I think are relevant. Can you have a look at the example below:

https://next.plnkr.co/edit/AILhmSvs68S5qnYy?preview

Furthermore, we have the following bug in our pipeline: 

AG-3275 - Docs should mention that when using cellRenderer+React+autoHeight that resetRowHeight() should be called within a timeout for it to work

You can follow the status of feature requests, bugs and releases using our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by leroydev** [comment]
@AhmedAGadir 
> When using reactNext={true} combined with resetRowHeights, **even with a timeout as mentioned in #3264 (comment)**, it won't autosize the row heights.

If I add `reactNext={true}` to the plunkr you sent, it won't autoSize anymore. See this plunkr:
https://next.plnkr.co/edit/RishtMo2uV7XFmQy?preview

So the issue is still relevant in my opinion. It's even more relevant in the newer version of AgGrid, where `reactNext={true}` is the default.

**Comment by leroydev** [comment]
@AhmedAGadir Please check my previous comment :)

**Comment by leroydev** [comment]
@AhmedAGadir This issue is still present, even in AgGrid 22.1.1. Can you reopen the issue please?

**Comment by leroydev** [comment]
@AhmedAGadir ping
