### ISSUE TITLE
Add "How Triggered Means" Property to Cell Value Change Detection

### ISSUE THREAD

**Issue by matthewstick** [ag-grid/ag-grid#3481]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
This is a feature request.

Currently, you have three ways of triggering a change as documented here:
https://www.ag-grid.com/javascript-grid-change-detection/

More specifically, here is your documentation: 
"The following operations will automatically trigger change detection on all visible cells:
1) Editing any value via the grid UI (e.g. double clicking a cell and entering a new value).
2) Using the rowNode.setDataValue(col,value) Row Node method.
3) Using the api.updateRowData(transaction) API method."

I then listen to cell value changes via "onCellValueChanged"

However, the event that gets passed to onCellValueChanged just tells me WHAT changed.  It doesn't tell me HOW the change event got triggered.  

What I'd love is a new property in the event that gets passed to onCellValueChanged.  

You could call it "means" (or whatever you see fit).  It could have one of three values (or whatever you see fit):
means: "user"
means: "setDataValue"
means: "updateRowData"

This would greatly help, because I need to do certain actions in the onCellValueChanged callback based on if this was a user triggered cell value change, or an API triggered cell value change.

Many thanks!

**Comment by davis4acca** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
