### ISSUE TITLE
componentWillReceiveProps is no longer recommended and has been renamed

### ISSUE THREAD

**Issue by stevenhankin** [ag-grid/ag-grid#3482]
Some older lifecycle methods have been deprecated and will not be available in React 17+, as per notice: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Ag Grid React is throwing warnings during testing with Jest and is reproducible with this Plunkr; http://next.plnkr.co/plunk/e2CudNG0u58U3zSP (run it and check the console output)

Suggested replacements are discussed here: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

See the deprecated lifecycle in code here: https://github.com/ag-grid/ag-grid/blob/efe2523660ca63ccd2014efa90695aa1a34523ad/packages/ag-grid-react/lib/agGridReact.js#L154

The full warning message is as follows:
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AgGridReact
```

**Comment by stephjang** [comment]
Agreed -- would appreciate a fix for this issue as well!

**Comment by stevenhankin** [comment]
Hi @stephjang, I'm tempted to try a fix but there is quite a lot of side-effecting going on (one curious situation is the tests seem to occasionally fail).  I've had a go at replacing componentWillReceiveProps() with getDerivedStateFromProps() and componentDidUpdate(), but encountered state problems during testing.  Would it be acceptable to rewrite as a functional component using effects?  Or maybe as a new agGridReact.16.8.ts?

**Comment by seanlandsman** [comment]
This has been fixed and will be available in our next release, due out Monday

thanks
