### ISSUE TITLE
isRowMaster() doesn't get called/updated when data changes in Master/Detail grid

### ISSUE THREAD

**Issue by crumhorn** [ag-grid/ag-grid#3484]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using a Master/Detail grid (where nodes are expandable only if there's details data to show), the expand/collapse arrow is never updated when data changes (and by change I mean no row is added/deleted, but the data itself is literally changed on a sub-property level. In this case, the property that determine if there is a details grid or not).

Here's a plunkr showing the issue, which re-uses the Ag-Grid example "Example - Dynamically Specify Master Nodes" from here: https://www.ag-grid.com/javascript-grid-master-detail/#example-dynamically-specify-master-nodes

**Plunkr:**
https://plnkr.co/edit/GoUYbLVmLxZs8asHNyPI?p=preview

**Steps to reproduce:**
1. Press the first button at the top. The code removes the sub-node data for "Mila Smith" and tells the grid to update all rows. We even tell it to refresh all cells. The grid still shows the expand/collapse button after the change. It should have gone away.

2. Press the second button. Now the code calls .setRowData() with the changed data. The change is now reflected. This however, is not a good "workaround", as setRowData() is far too heavy for us as all "state" is lost.

**Expected behavior**
When data is updated, the grid should check and update if it's possible to expand/collapse the details based on the new data.

**Please tell us about your environment:**
Windows 7

* **ag-Grid version:** X.X.X
21.2.2

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.5.3

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3589 - FR to allow for dynamically changing master rows into leaf nodes

Note that we have raised this as likely to be picked up in the next 2/3 releases, feel free to follow up in a week or so for more details

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-
