### ISSUE TITLE
Allow for date ranges in custom DateFilterComponent

### ISSUE THREAD

**Issue by Cody0913** [ag-grid/ag-grid#3491]
```
[] bug report
[X] feature request
[] support request
```

**Providing a Reproducible Scenario**
Setting up a filter like the one provided in the ag-grid docs for providing a [date filter](https://www.ag-grid.com/javascript-grid-date-component/)

**Current behavior**
Currently the get/set date methods in providing a custom date picker does not give the ability to use date ranges. This sets the `type` always to `equal` and only proved the model with a dateFrom value.

**Expected behavior**
The user should be able to tune the getter/setters to their choosing as it is currently stuck as a static `equal` type and does not allow for setting both the dateTo or changing the type to give the end-user a more granular search. Searching day by day is not an ideal way to filter results.

**Please tell us about your environment:**

All environments.

* **ag-Grid version:** 21.2.2

* **Browser:** All

* **Language:** [all]

I gave it a bit of thought and narrowed it down to two approaches I think would satisfy the requirements to get this up and running without affecting any previous implementations.

**Current Code**
```javascript
private onDateChanged(): void {

    const filterValueDate: Date = this.dateComp.getDate();
    const filterValueText: string = _.serializeDateToYyyyMmDd(filterValueDate, "-");

    this.params.parentFilterInstance(filterInstance => {
        if (filterInstance) {
            const simpleFilter = filterInstance as SimpleFilter<ISimpleFilterModel>;
            simpleFilter.onFloatingFilterChanged(this.getLastType(), filterValueText);
        }
    });
}

// and 

protected setValueFromFloatingFilter(value: string): void {
    if (value != null) {
        const dateFrom = _.parseYyyyMmDdToDate(value, "-");
        this.dateCompFrom1.setDate(dateFrom);
    } else {
        this.dateCompFrom1.setDate(null);
    }

    this.dateCompTo1.setDate(null);
    this.dateCompFrom2.setDate(null);
    this.dateCompTo2.setDate(null);
}
```

**My First Thought To Approaching This**

// I would first add a getType() method to the dateFilterComponent

```javascript
private onDateChanged(): void {

    const filterValueDate: Date | [Date, Date] = this.dateComp.getDate();
    const filterValueText: string | [string | string] = Array.isArray(filterValueDate)
        ? filterValueDate.map(date => _.serializeDateToYyyyMmDd(date, "-"))
        : _.serializeDateToYyyyMmDd(filterValueDate, "-") ;

    this.params.parentFilterInstance(filterInstance => {
        if (filterInstance) {
            const simpleFilter = filterInstance as SimpleFilter<ISimpleFilterModel>;
            simpleFilter.onFloatingFilterChanged(this.dateComp.getType() || this.getLastType(), filterValueText);
        }
    });
}

// and

protected setValueFromFloatingFilter(value: string | [string | string]): void {
    if(!Array.isArray(value)) {
        if (value != null) {
            const dateFrom = _.parseYyyyMmDdToDate(value, "-");
            this.dateCompFrom1.setDate(dateFrom);
        } else {
            this.dateCompFrom1.setDate(null);
        }
        this.dateCompTo1.setDate(null);
    } else {
        const newValues = value.map((val: string) => val != null
          ? _.parseYyyyMmDdToDate(val, "-")
          : null
        );
        this.dateCompFrom1.setDate(newValues[0]);
        this.dateCompTo1.setDate(newValues[1]);
    }
    this.dateCompFrom2.setDate(null);
    this.dateCompTo2.setDate(null);
}
```

My second approach was to allow for a new method to be created
`getModel`
to where the user can provide their own logic and conditions to set the filterModel. 

I'm sure it could be cleaner and more permormant by removing the usages of array mapping.
Just my initial thoughts.

I think it would be beneficial and allow for further extension of the dateFilter component drastically.

I am aware that github isn't used much for feature requests. Given that I might be able to contribute and make the changes under guidance to get it into review I was hoping this would be an exception.

I know there is a ticket for updating the custom dateFilter docs as well: AG-3328

What does everyone think about the feasibility of adding this?

**Comment by Cody0913** [comment]
I have tried to work around this by access the gridApi similarly to the setFilter.
I see that it exists in the `this.props.agGridReact` as `api`, but it's value is null.

**Comment by davis4acca** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by rajeshtbabu** [comment]
Facing same issues how to resolve this?
**Ag-grid version: 26.2.1**
