### ISSUE TITLE
IDateComparatorFunc conflict in dateFilter (TypeScript 3.7.2)

### ISSUE THREAD

**Issue by KaiVolland** [ag-grid/ag-grid#3492]
**I'm submitting a Bug Report**

The [declaration file of the dateFilter](https://github.com/ag-grid/ag-grid/blob/master/dist/lib/filter/provided/date/dateFilter.d.ts) is invalid:

```typescript
import { IDateComparatorFunc } from "./dateFilter";
import { Comparator, IScalarFilterParams, ScalerFilter } from "../scalerFilter";
export interface DateFilterModel extends ISimpleFilterModel {
    dateFrom: string;
    dateTo: string;
}
export interface IDateFilterParams extends IScalarFilterParams {
    comparator?: IDateComparatorFunc;
    browserDatePicker?: boolean;
}
export interface IDateComparatorFunc {
    (filterLocalDateAtMidnight: Date, cellValue: any): number;
}
```

The [import](https://github.com/ag-grid/ag-grid/blob/master/dist/lib/filter/provided/date/dateFilter.d.ts#L5) of `IDateComparatorFunc` conflicts with the [export](https://github.com/ag-grid/ag-grid/blob/master/dist/lib/filter/provided/date/dateFilter.d.ts#L15)  of an interface with the same name `IDateComparatorFunc`.

**Current behavior**
There are two expressions with the same name: `IDateComparatorFunc`.

**Expected behavior**
Option 1: Use the exported Interface for the comparator property and remove the import.
Option 2: Use `import { IDateComparatorFunc as IDateCompartorFuncIMPORTED } from "./dateFilter";` (or similar).

* **ag-Grid version:** X.X.X
ag-grid-community: "21.2.2",
ag-grid-react: "21.2.2",

* **Language:**
TypeScript Version 3.7.2

**Comment by itjstagame** [comment]
The same issue just started up for us as well.  We've been using 21.2.1 ag-grid-community for 2 months now without issue, but last 2 days this build error started showing up:
ERROR in [at-loader] ./node_modules/ag-grid-community/dist/lib/filter/provided/date/dateFilter.d.ts:5:10 
    TS2440: Import declaration conflicts with local declaration of 'IDateComparatorFunc'.

It seems specific to typescript@3.7.2, for now we've limited to patch changes back to ~3.6.4 and building without issue.

**Comment by KaiVolland** [comment]
Seems to be fixed with v 22.0.0. :+1:

**Comment by seanlandsman** [comment]
@KaiVolland yes indeed :-) 

thanks for reporting

**Comment by mkmehtamca** [comment]
After update v 22.0.0 , i am facing rowHeight issue. After setting value this.gridOptions.rowHeight = 46; it worked but i want proper solution so that it will work for all grid which is used in whole project.
![gridrowheight_issue](https://user-images.githubusercontent.com/52462739/84246173-d725b880-ab23-11ea-8112-bb52be9dccd7.PNG)

**Comment by FirstVertex** [comment]
You can suppress this error by adding this to your tsconfig under `compilerOptions`

```json
"skipLibCheck": true
```
