### ISSUE TITLE
Missing properties in GridOptions type

### ISSUE THREAD

**Issue by mistic100** [ag-grid/ag-grid#3495]
**I'm submitting a bug report**

The following options are available in grid options but are not listed in the `GridOptions` type. It works anyway by annotating my code with `// @ts-ignore`.

- noRowsOverlayComponentParams
- loadingOverlayComponentParams

These options are not listed on https://www.ag-grid.com/javascript-grid-properties, only on https://www.ag-grid.com/javascript-grid-overlay-component/#example-custom-overlay-components

**ag-Grid version:** 21.2.2

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3583 - missing properties in gridOptions.ts & docs + DOCS

Note that we have raised this as likely to be picked up and fixed soon. 

You can follow the status of feature requests, bugs and releases using our pipeline:

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Regards,
