### ISSUE TITLE
Documentation  Typo in Column Api

### ISSUE THREAD

**Issue by AlokTakshak** [ag-grid/ag-grid#3500]
Actual-  first by trying to use the field if it is unique, otherwise it will generate and ID
Expected- first by trying to use the field if it is unique, otherwise it will generate an ID

https://github.com/ag-grid/ag-grid/blob/501b8f3a154f39f625488b360135585aa9426a7d/packages/ag-grid-docs/src/javascript-grid-column-api/index.php#L21

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-3574  DOCS Typo in column API section
