### ISSUE TITLE
Documentation wrong after new Modularization in 22.0.0 release

### ISSUE THREAD

**Issue by lukepierotti** [ag-grid/ag-grid#3503]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Hi ag-grid team. After the release today of version 22.0.0 and above the documentation is now inaccurate for project setup and installing ag-grid into an Angular project. As a result of the modularization of the `ag-grid-community` and `ag-grid-enterprise` packages, modules must now be passed to the `ag-grid-angular` component. This is not reflected [here](https://www.ag-grid.com/angular-grid/?utm_source=ag-grid-readme&utm_medium=repository&utm_campaign=github#add-ag-grid-to-your-project) in the documentation (also not reflected in React or Vue setup instructions). The instructions are provided [here](https://www.ag-grid.com/javascript-grid-modules/) but are hard to find, and now that there is a new major version introducing breaking changes all these changes should be clearly stated in the setup page for each framework.

When `AllCommunityModules` is not passed to the 'ag-grid-angular' component the grid does not render and only throws an error stating `ag-Grid: Row Model “Client Side” not found. Please ensure the ClientSideRowModelModule is loaded using: import ‘@ag-grid-community/client-side-row-model’;`. This is not descriptive or helpful if unaware that modules has to be passed to the `ag-grid-angular` component.

**Expected behavior**

The documentation should reflect the new setup needed to correctly import ag-grid packages and provide modules to the `ag-grid` components (Angular, React, Vue). Or at least please add an alert to the top of each documentation page ([Angular](https://www.ag-grid.com/angular-grid/), [React](https://www.ag-grid.com/react-grid/), [Vue](https://www.ag-grid.com/vuejs-grid/)) linking to the Modularization [page](https://www.ag-grid.com/javascript-grid-modules/) so that users adding the new version wont run into setup issues like I have. 

Also please consider updating the error message shown in the console when no modules have been passed to a `ag-grid-angular` component. It should probably alert that no modules have been passed to the grid rather than just saying a generic statement that `@ag-grid-community/client-side-row-model` should be imported. Thanks!

* **ag-Grid version:** >=22.0.0

**Comment by seanlandsman** [comment]
Thanks for reporting this - I'll get the docs updated

**Comment by crumhorn** [comment]
Agree with OP.

Additionally, [from the documentation](https://www.ag-grid.com/javascript-grid-modules/#modules) it looks the Angular module is part of @ag-grid-community/all-modules, which is part of @ag-grid-enterprise/all-modules. Apparently the angular one has to be imported separately regardless of what you use. This should probably be made clearer.

**Comment by seanlandsman** [comment]
@crumhorn none of the frameworks are part of the "all-modules" packages - I'll make this clearer

thanks for the feedback

**Comment by seanlandsman** [comment]
The docs around this will be updated today

**Comment by seanlandsman** [comment]
@crumhorn @lukepierotti 

I've updated the docs - thanks for the feedback, we appreciate it
