### ISSUE TITLE
How to expand row group without additional server request in Ag-grid server side model

### ISSUE THREAD

**Issue by sshiling** [ag-grid/ag-grid#3507]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

As described in docs. Get row groups. Send extra request to get group inner data. It's not a bug for server-side row model. But at the same time I need infinite scroll, pagination, server side filtering and sorting and no extra requests to get row group inner data.

**Expected behavior**

Get rows from the server with row groups enabled and expand it on the client without extra request to the server. I understand how it can be useful to get group data separately but I have another, common in my opinion, task. I had a lot of groups with small data inside, so I don't want to send an extra request to get inner data. I can't use the client-side model because of the infinite scroll, pagination, server-side filtering and sorting for row groups.

**Environment**

* **ag-Grid version:** 20.2.0

* **Language:** ES6/7

**Comment by Excelautomation** [comment]
@sshiling did you ever find a solution for this? It seems to me, if I'm using serverside model, I'm obligated to request the server for the nested data, however, I would like to, to get this data in my initial request. But I can't get it to work, did you find any solution?

**Comment by sshiling** [comment]
@Excelautomation I found the solution for our case but I don't think it is good one. Here it is:
In my dataSource object:
` this.dataSource = {
    getRows: (params) => {
         let requestData = {
             filters: getFiltersConfig(params),
             sort: this.getSortData(),
             pagination: this.withPagination ? this.getPaginationData() : null,
             **group: params.request.groupKeys[0]**
        };
        ...
    }
}`
So whenever I need to update data I have the **group** id or undefined when there are no groupKeys.

1. On the first GET table data request there are no groups so I send the request.
2. After request success I save data to the client storage (vuex in my case).
3. On the group opening ag-grid trigger next update but I see that I have data with groups already, so I don't send request.
4. Then I find group by id in my storage and return group nested elements in successCallback.

It doesn't look pretty but does the job.

**Comment by Excelautomation** [comment]
OK I understand, so you basically just cache the data to avoid additional requests. 

Working with serverside data, I realize that loose some features, like for instance "expand all groups/close all", which is in my use case really essential. I don't think your solution works with this, does it? - I suppose I have to make some h4x-solution for that aswell... A shame.

**Comment by sshiling** [comment]
You can expand all or hide all. 
My solution:

`gridApi.forEachNode(node => {
                            if (node.data && node.data.is_group && node.data.is_expanded) {
                                node.setExpanded(true);
                            }
                        });`

node.data.is_group && node.data.is_expanded are my additional params from server for specific data manipulation on server. **forEachNode** method is the solution to expand all or (as in my case) specific ones.
