### ISSUE TITLE
[Bug] "ag-grid-vue@22" requires deprecated "ag-grid-community" as peer dependency

### ISSUE THREAD

**Issue by ThomasKientz** [ag-grid/ag-grid#3510]
I have updated to v22.

```
package.json

"dependencies": {
  "@ag-grid-enterprise/all-modules": "^22.0.0",
  "ag-grid-vue": "^22.0.0",
  ...
}
```

But I got the error : 

> This dependency was not found:
> 
> * ag-grid-community in ./node_modules/ag-grid-vue/lib/AgGridVue.js, ./node_modules/ag-grid-vue/lib/Utils.js and 2 others
> 

`ag-grid-vue` requests `ag-grid-community` as a peer dependency but `ag-grid-community` is [deprecated](https://www.ag-grid.com/javascript-grid-modules/#migrating-to-modules)  from v22.

**Comment by Stejnar** [comment]
I have a similar error about peerDependencies but with @ag-grid-community/all-modules.
I don't want to install all modules to get rid of the error, there is no need! 


Also `vue-property-decorator` should not be a peer dependency. It should be up to the developer to use this and doesn't make sense for none typescript projects.

```
@ag-grid-community/vue package.json:

"devDependencies": {
    "@ag-grid-community/core": "~22.0.0",
    "@vue/cli-plugin-typescript": "^3.11.0",
    "@vue/cli-plugin-unit-jest": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "gulp": "^4.0.0",
    "gulp-typescript": "^5.0.0",
    "typescript": "^3.6.0",
    "vue": "2.6.10",
    "vue-class-component": "^7.0.0",
    "vue-property-decorator": "^8.2.0",
    "vue-template-compiler": "^2.6.10"
  },
  "peerDependencies": {
    "@ag-grid-community/all-modules": "~22.0.0",
    "vue": ">= 2.2 <= 2.5.17 || >= 2.5.20",
    "vue-property-decorator": "^7.2.0 || ^8.0.0"
  },
```

**Comment by seanlandsman** [comment]
@ThomasKientz `@ag-grid-community/vue` requires `@ag-grid-community/all-modules` and `ag-grid-vue` (also deprecated) requires `ag-grid-community`, so this looks correct to me.

If you're using `@ag-grid-community/vue` then specify `@ag-grid-community/all-modules`, and if you're using `ag-grid-vue` you'll need to specify`ag-grid-community`.

All `ag-grid-xxx` packages are now deprecated in favour of the new `@ag-grid-community/xxx` packages.

@Stejnar the `vue-property-decorator` is required at runtime by the ag-Grid vue component, regardless of whether you us TS or not.

thanks

**Comment by ThomasKientz** [comment]
Solution :
```
  "dependencies": {
    "@ag-grid-community/vue": "^22.0.0",
    "@ag-grid-enterprise/all-modules": "^22.0.0",
```
@seanlandsman this doc needs an update https://www.ag-grid.com/vue-getting-started/

Thanks !

**Comment by seanlandsman** [comment]
@ThomasKientz that's great, thanks for the feedback

The correct page is https://ag-grid.com/vuejs-grid/

The page you've referenced should have been removed as part of the release - we'll get it updated now.

thanks!

**Comment by ThomasKientz** [comment]
@seanlandsman I have noticed, on https://ag-grid.com/vuejs-grid/ , the button "Open in StackBlitz" links to an outdated project 
 : https://stackblitz.com/edit/ag-grid-vue-hello-world.

:)

**Comment by seanlandsman** [comment]
Yeah, we know! It turns out stackblitz can take several days to get new dependencies, so we can't update the examples until stackblitz is updated :-)

thanks again

**Comment by mhldtna** [comment]
(https://ag-grid.com/vuejs-grid/) redirects to (https://ag-grid.com/documentation/vue/getting-started/). In the middle of the page it says:

`npm install --save ag-grid-community ag-grid-vue vue-property-decorator`

... which references the old package names.
