### ISSUE TITLE
Unable to get up and running with vue

### ISSUE THREAD

**Issue by psuplat** [ag-grid/ag-grid#3511]
I have been trying to get up and running with the ag-grid (community version) for vue, sadly with no luck.

I even got to the point where I followed the official tutorial step-by-step from here: https://www.ag-grid.com/vuejs-grid/ but I always end up getting the same errors in the console:

```
ag-Grid: could not find matching row model for rowModelType clientSide
ag-Grid: Row Model "Client Side" not found. Please ensure the ClientSideRowModelModule is loaded using: import '@ag-grid-community/client-side-row-model';
```

![image](https://user-images.githubusercontent.com/14207860/68777702-fdd14e80-0629-11ea-8c70-58186efea6e8.png)

Is the documentation incorrect or is this some kind of bug?

**Comment by seanlandsman** [comment]
Have you supplied `AllCommunityModules` to `ag-grid-vue` ?

**Comment by psuplat** [comment]
@seanlandsman like I said I followed the tutorial step by step, so:

```
import {AgGridVue} from "@ag-grid-community/vue";
import {AllCommunityModules} from '@ag-grid-community/all-modules';
```

and then:
```
data() {
    return {
        columnDefs: null,
        rowData: null,
        modules: [AllCommunityModules]
    }
},
components: {
    AgGridVue
},
```

is there some other way I am supposed to do it?

**Comment by seanlandsman** [comment]
I see the problem - replace:

`        modules: [AllCommunityModules]`

with 

`        modules: AllCommunityModules`

I'll get the docs updated

**Comment by psuplat** [comment]
Perfect, all working now :)

**Comment by StefanFeederle** [comment]
Can you please add the module names to the table in the docs?
Based on the package name '@ag-grid-enterprise/row-grouping' one might assume it's import { RowGrouping } from ...

**Comment by seanlandsman** [comment]
@StefanFeederle that's a fair point - I'll add this for our next release 

thanks

**Comment by Scozzi** [comment]
@seanlandsman I have tried everything and am still seeing this trying to work with vue3.. is this still the approach for vue3?  also posted on this issue:

I still have not been able to get the grid to ever load.  
https://github.com/ag-grid/ag-grid/issues/4147

**Comment by seanlandsman** [comment]
@Scozzi take a look at this repo: https://github.com/ag-grid/ag-grid-vue3-example

Does this help? If not are you able to supply a repo that I can look at?

**Comment by seanlandsman** [comment]
There is also a repo for packages: https://github.com/ag-grid/ag-grid-vue3-package-example

**Comment by Scozzi** [comment]
well I've tried bost approaches..
do you mind having a look? unfortunately there isnt actually any data without a scrape first? want me to hardcode some data?
https://github.com/Scozzi/guild-discovery @seanlandsman

**Comment by Scozzi** [comment]
@seanlandsman it actually seems like it potentially should be working now but I get this warning and no errors on load:

[Vue warn]: Component is missing template or render function. 
  at <AgGridVue class="ag-theme-alpine" columnDefs= (11) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] rowData=null  ... > 
  at <GuildDiscovery> 
  at <App>

**Comment by seanlandsman** [comment]
@Scozzi you need to extract the actual `AgGridVue` component from the import:

`import {AgGridVue} from "@ag-grid-community/vue3";`

As an aside you don't need all the module dependencies you have in your package.json - either use all-modules if you want everything, or select the modules you want (and supply them to the grid). It doesn't hurt having them in package.json but it isn't necessary

**Comment by Scozzi** [comment]
@seanlandsman Yup! that did it, thanks so much for the assistance.. so I should be able to just remove all but All-Modules from the package.json?

**Comment by seanlandsman** [comment]
@Scozzi Yes, that's correct - glad it's all working for you now

**Comment by Scozzi** [comment]
@seanlandsman yup all set!  you wouldn't happen to know how to deal with gridApi not binding to component data would you?  I think its because of lodash arrow functions, but not sure.

this.gridOptions.api.setFilterModel(hardcodedFilter) 
results in :
GuildDiscovery.vue?0e88:109 Uncaught TypeError: Cannot read property 'gridOptions' of undefined
trying to update filter via api..

**Comment by Scozzi** [comment]
Full Method:
```
onMemberRangeFilter: _.debounce((event) => {
      console.log(event.target.value)
      var hardcodedFilter = {
        guildID: {
          type: 'greaterThan',
          filter: event.target.value
        }
      }
      this.gridOptions.api.setFilterModel(hardcodedFilter)
    }, 
    1000),
```

and it has been pushed to github

**Comment by seanlandsman** [comment]
Change `onMemberRangeFilter` to:

`onMemberRangeFilter: _.debounce(function (event) {`

and it should work as expected

thanks,
S
