### ISSUE TITLE
Doesn't work getContextMenuItems after upgrating

### ISSUE THREAD

**Issue by Lertis** [ag-grid/ag-grid#3512]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Scenario:**
I had ag-Grid v21.2.2 with the next code

*ag.grid.component.html
```html
    <ag-grid-angular #agGrid class="ag-theme-balham ag-grid-main"
      [gridOptions]="gridOptions"
      [rowData]="rowData | async"
      (gridReady)="onGridReady()"
      [frameworkComponents]="frameworkComponents"
      [suppressRowClickSelection]="true"
      [rowHeight]="rowHeight"
      (selectionChanged)="onSelectionChanged($event)"
      [popupParent]="popupParent"
      [getContextMenuItems]="getContextMenuItems">
    </ag-grid-angular>
```

*app,module.ts
```javascript
...
// Ag Grid
import { AgGridModule } from 'ag-grid-angular'
import 'ag-grid-enterprise'
...
```

*Imports 
```javascript
// AgGrid
import { GridOptions } from 'ag-grid-community'
```

After upgrating to v 22.0.0 ag-grid-angular component and other imports was upgrated.

*ag.grid.component.html
```html
    <ag-grid-angular #agGrid class="ag-theme-balham ag-grid-main"
      [gridOptions]="gridOptions"
      [rowData]="rowData | async"
      (gridReady)="onGridReady()"
      [frameworkComponents]="frameworkComponents"
      [suppressRowClickSelection]="true"
      [rowHeight]="rowHeight"
      (selectionChanged)="onSelectionChanged($event)"
      [popupParent]="popupParent"
      [getContextMenuItems]="getContextMenuItems"
      [modules]="modules">
    </ag-grid-angular>
```

*ag.grid.component.ts
```javascript
import {
  GridOptions,
  Module,
  ClientSideRowModelModule
} from '@ag-grid-community/all-modules'
...
modules: Module[] = [ClientSideRowModelModule]
```

I tried to change the import from ```@ag-grid-community/all-modules``` to  ```@ag-grid-enterprise/all-modules ```, but without success.

*app,module.ts
```javascript
...
// Ag Grid
import { AgGridModule } from '@ag-grid-community/angular'
import '@ag-grid-enterprise/all-modules'
...
```

**Current behavior with v21.2.2**
When the right mouse key pressed on the expected cell field the custom context menu **was shown**.

**Expected behavior v21.2.2**
Everything work as expected.

**Current behavior with v22.0.0**
When the right mouse key pressed on the expected cell field the custom context menu **doesn't** show.

**Expected behavior v22.0.0**
The same scenario as with v.21.2.2

**Feel free to ask me to provide more info about project such as ```package.json```,  ```app.module.ts``` config etc.**

**Environment:**

* **ag-Grid version:** [21.2.2 | 22.0.0]

* **Node.js:** [v10.16.0]

* **Angular:** [8.2.13]

* **Angular CLI:** [8.3.18]

* **OS:** [OS: win32 x64]

**Comment by Lertis** [comment]
```javascript
import { GridOptions, Module } from '@ag-grid-community/all-modules'
import { AllModules } from '@ag-grid-enterprise/all-modules';
```

```javascript
modules: Module[] = AllModules
```

I add this to ag.grid.component.ts and it works !

**Comment by seanlandsman** [comment]
@Lertis note that if you're using `'@ag-grid-enterprise/all-modules';` you don't need `'@ag-grid-community-/all-modules';`

`@ag-grid-enterprise/all-modules;` contains everything in Community

So you can do this: 

`import { GridOptions, Module, AllModules } from '@ag-grid-enterprise/all-modules'`

**Comment by Lertis** [comment]
@seanlandsman Thanks, It works!

**Comment by oakstreetrec** [comment]
Does anyone know how to make this work without importing all modules?

The documentation would make it seem that you can use :

import {MenuModule} from @ag-grid-enterprise/menu

.... but, that doesn't work. The context menu shows only 'MenuItem' entries in the getContextMenuItems list, but 'string' entries in the list ( i.e. 'copy', 'separator', etc...) are ignored.

**Comment by oakstreetrec** [comment]
For anyone else who stumbles on this, I solved my own problem, you also need to import the ClipboardModule:

import { ClipboardModule } from "@ag-grid-enterprise/clipboard";
