### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by nachocs** [ag-grid/ag-grid#3515]
Hello
In your documentation, https://www.ag-grid.com/javascript-grid-tool-panel-columns/
says:
"To remove a particular column from the tool panel, set the column property suppressColumnsToolPanel to true."
After investigation, the correct property for this is 
suppressToolPanel in the column definition
Just to let you know.

**Comment by rmc-software** [comment]
'suppressToolPanel' has now been deprecated in favour of: 'suppressColumnsToolPanel' and 'suppressFiltersToolPanel'

Note in the following example 'suppressColumnsToolPanel' is used to remove the date column from the Columns Tool Panel using:
` {field: "date", width: 110, suppressColumnsToolPanel: true},`

https://plnkr.co/edit/4qvnHaxkGZ27vPcUqU9d?p=preview

**Comment by Padilipu** [comment]
suppressColumnsToolPanel is not working
