### ISSUE TITLE
Cant select header row elements by keyboard (for sorting etc..)

### ISSUE THREAD

**Issue by bigbasti** [ag-grid/ag-grid#3521]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Basically any grid with sortable column headers like https://www.ag-grid.com/javascript-grid-keyboard-navigation/#example-custom-navigation

**Current behaviour.**
There is no way to access the title (header) row by using only the keyboard. So Blind users have no chance to sort the grid or execute column filtering.
The Docs (https://www.ag-grid.com/javascript-grid-keyboard-navigation/#navigation) do not mention any way to access the header.

**Expected behaviour.** 
There should be a keyboard short cut to access the header row or a way to tab/navigate into it.
Alternatively there should be an article in the docs describing how this could be achieved through code.

* **ag-Grid version:** 
current version as displayed on your homepage

**Comment by icedjello** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog.

This is the reference and summary of the relevant issue:

Improve Accessibility across the grid - ARIA, ADA... | AG-3257 | Add colcount & colindex to cells & headers

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by bigbasti** [comment]
Just in case anyone else comes here through google:

Since it is mandatory in our project for the user to be able to sort the grid by using just the keyboard i solved this issue the following way:

In the template:
```
<ag-grid-angular
  [...]
  [gridOptions]="gridOptions"
  [rowData]="gridObjects"
  (keydown.control.alt.arrowUp)="changeColSort('asc')"
  (keydown.control.alt.arrowDown)="changeColSort('desc')"
>
```
in the component:
```
/**
 * If focus is inside one of the grid's cols - change the sorting direction as provided in the parameter
 * @param newSortDirection asc|desc
 */
changeColSort(newSortDirection: string) {
  const currentSortDirection = this.gridApi.getFocusedCell().column.getSort();
  // first, reset all currently set sort models
  this.gridColumnApi.getAllColumns().forEach((c: Column) => {
    c.setSort(null);
  });
  // reset sorting if user orders same order direction (allow to remove sorting from column)
  if (currentSortDirection !== newSortDirection) {
    this.gridApi.getFocusedCell().column.setSort(newSortDirection);
  }
  this.gridApi.onSortChanged();
}
```

When the user navigates through the grid, it is now possible to sort the current column by hitting [CRTL]+[ALT]+[UP]/[DOWN] to sort the current column asc or desc.
