### ISSUE TITLE
[Angular] Mouse events on a cell prevented/not propagated when preventDefaultOnContextMenu enabled

### ISSUE THREAD

**Issue by zburkhardt-zz** [ag-grid/ag-grid#3523]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Cell does not become focused (selected) when you click on it if preventDefaultOnContextMenu is set to true. Clicked and focus events are still triggered and the row itself becomes selected, however the actual focus/select never occurs for the specific cell. If I remove this setting then cell selection works as expected.

Another interesting behavior I have noticed regarding this is that if I double click to edit a cell and then hit ESC or click elsewhere to close the edit popup the cell now has focus and I can click other cells to focus them, use the keyboard, etc. But once I click outside of my table I can no longer click on the table to gain focus again unless I double click a cell to begin editing it.

Also, when preventDefaultOnContextMenu is true if you also have the enableCellTextSelection set to true you will not be able to click/drag to select any text in a cell. It seems that these browser events are not propagating whenever preventDefaultOnContextMenu is enabled.

**Expected behavior**

Cell should become focused upon clicking on it. The cell should be outlined so that you can see that it is focused and you should be able to interact with the cell/table via the keyboard (e.g. arrowing between cells, deleting the contents of a cell, entering edit mode for a cell, etc.)

**Reproducible Scenario**
Here is the plunker that reproduces the issue using one of the angular examples from the documentation. https://plnkr.co/edit/BcuP1g38MBafcYfvqLlx?p=preview

All I had to do to reproduce the issue is add preventDefaultOnContextMenu="true" to the ag-grid-angular element in the app.component.ts template.

After adding the above configuration I can no longer click on a cell to give it focus. The row still gets selected but the specific cell never gets selected. From my understanding, preventDefaultOnContextMenu should disable the default context menu that comes up when right clicking, but all other table/cell interactions should continue to work as expected.

From my investigation, the cell still receives the click events. However, the cell never receives focus. This has many potential negative impacts, but one being that you cannot use the keyboard to begin editing in a cell since the cell is never focused.

**What is the motivation / use case for changing the behavior?**
Without being able to select cells the user is unable to use any keyboard keys to navigate, delete, edit cells. Also, visually you cannot see which cell is active.

**Please tell us about your environment:**

MacOS Mojave 10.14.6, IntelliJ, npm 6.10.1,

* **ag-Grid version:** 22.0.0

* **ag-grid-angular version:** 22.0.0

* **Browser:** all

* **Language:** all

**Comment by icedjello** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-3592 - REGRESSION: preventDefaultOnContextMenu + suppressContextMenu prevent cell selection

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)
