### ISSUE TITLE
[documentation] Javascript grid responsiveness page renders empty

### ISSUE THREAD

**Issue by JabbyPanda** [ag-grid/ag-grid#3524]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
[X] documentation request
```

https://www.ag-grid.com/javascript-grid-responsiveness/ renders as empty page

Older version of the page renders OK 
https://www.ag-grid.com/archive/19.0.0/javascript-grid-responsiveness

**Comment by icedjello** [comment]
This is in our backlog now and we are tracking it with the following reference and description.

AG-3590 - DOCS: responsiveness page renders empty 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-
