### ISSUE TITLE
Configure ag-grid to show on the last page empty dummy rows

### ISSUE THREAD

**Issue by JakubOzogPsi** [ag-grid/ag-grid#3527]
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
Prerequisite:
- ag-grid with set height and enabled pagination
- on the last page there are not enough data rows to fill the whole grid's page

There is blank space between the last data row and the footer with pagination.

**Expected behavior**
Prerequisite:
- ag-grid with set height and enabled pagination
- on the last page there are not enough data rows to fill the whole grid's page

The blank space between the last data row and the footer with pagination should be filled with empty rows (only as visual element)

* **ag-Grid version:** 
"ag-grid-angular": "^21.2.2",
"ag-grid-community": "^21.2.2",

* **Browser:** Google Chrome v.78

* **Language:** TypeScript ~3.5.3

**Comment by davis4acca** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
