### ISSUE TITLE
Add Vue composition Api support.

### ISSUE THREAD

**Issue by NikitaIT** [ag-grid/ag-grid#3531]
In Vue composition Api `createComponent()` return object, not a Vue.
In Vue composition Api `Vue.extend` not mounted with render in setup. Use `Vue.bind(null, vueComponent)`.

define:
```ts
function createAgVueComponent(vueComponentData: any) {
  return function createVue(data: any) {
    const vueComponent = { ...vueComponentData, parent: data.parent };
    const params = {
      default: () => data.data.params
    };
    if (vueComponent.props as any) {
      (vueComponent.props as any).params = params
    } else {
      vueComponent.props = { params };
    }
    const vue = Vue.bind(null, vueComponent);
    return new vue;
  }
}
```
use:
```ts
columnDefs: [{
        headerComponentFramework: createAgVueComponent(HeaderRenderer),
      }]
```

**Comment by davis4acca** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
