### ISSUE TITLE
The grid doesn't render the pinned rows when the print layout is used

### ISSUE THREAD

**Issue by FlorDonadio** [ag-grid/ag-grid#3533]
**I'm submitting a  bug report **

**Providing a Reproducible Scenario**

- To reproduce the bug you only need to set a new row calling setPinnedBottomRowData, and then set the layout as print. Then you will see that the space is been calculated but the data is not rendered. Then if you change the layout to autoHeight, the pinned row is going to render. I saved a plnkr with the error, based in a demo from the website.

![image](https://user-images.githubusercontent.com/58052088/69378662-95b7e380-0c8d-11ea-81b7-92b7acd81e07.png)

- https://plnkr.co/edit/7DwFf1Pfc1tJeuiMrbZ6?p=preview

**Current behavior**

When the print layout is set, the pinned rows at the bottom aren't rendered.

**Expected behavior**

When the print layout is set, all grid is rendered.

**Please tell us about your environment:**

* **ag-Grid version:** 22.0.0

* **Browser:** Chrome.

* **Language:** Coffescript / Angularjs / Javascript

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-3679 - DOCS: Row Pinning: add domLayout='print' to 'Non Supported Items'

**Comment by FlorDonadio** [comment]
Thanks for the reply.  I will wait for the updates. For now i m using the autoHeight layout as alternative.

**Comment by uvcreation** [comment]
@FlorDonadio, 
**Workaround to achieve print of pinned bottom row.**

Before print call this function and pass the "add" transaction type it will add your pinned row into actual grid data.

After print again call this function and pass the "remove" so it will remove the added row data from actual grid data.

  private printPinnedRowData(transactionType: string) {
    switch (transactionType) {
      case 'add':
          this.gridApi.updateRowData({add: rowData});
          break;
      case 'remove':
        this.gridApi.updateRowData({remove: rowData});
        break;
      default:
        console.log('No such transaction exists!');
        break;
    }
  }



FYI,
@icedjello , @davis4acca
