### ISSUE TITLE
Your website e.g. Documentation is broken in Chrome

### ISSUE THREAD

**Issue by JuliusKoronci** [ag-grid/ag-grid#3536]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Website freezes when scrolling, when using the scrollbar, in general it dies in 90% of cases in chrome while browsing trough documentation

**Expected behavior**
website works

**Please tell us about your environment:**
Windows 10

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi @JuliusKoronci , 

We have tested this given your settings (Windows 10 & Chrome). 

So far, we have been unable to find any instance of the website freezing hen scrolling or when using the scrollbar. 

Can you please provide us with some more information of when and where this is happening? 

Thanks,

**Comment by icedjello** [comment]
Hi, 

I will be closing this now. 

My recommendation if you are still experiencing issues is to try clearing the cache. 

For us to investigate this further, we would require some more information such as a screen-cap. 

Thanks,
