### ISSUE TITLE
ag-grid enterprise v22.0.0 Typings broken

### ISSUE THREAD

**Issue by troywweber7** [ag-grid/ag-grid#3537]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Types are not working so type completion fails.

**Expected behavior**

Types would work and completion succeeds.

**Please tell us about your environment:**

Linux, Webstorm, Yarn/NPM

* **ag-Grid version:** 22.0.0

* **Browser:** N/A

* **Language:** Typescript 3.4.5, 3.6.4, 3.5.3, 3.7.2

I believe the issue is that a lot of the `package.json` fields are missing the `"types": "./path/to.d.ts"` field.

**Comment by Bazman** [comment]
Same with ag-grid community.

**Comment by troywweber7** [comment]
The solution to this is really easy (except when doing it manually). They just need to add the following to most of their `package.json`s: `{ "types": ".dist/es6/main.d.ts" }`. I added these myself and restarted my IDE and all the typings work after that. But it should be done in this repository. Apparently they were working before this version, so I'm not sure why they changed it around.

**Comment by troywweber7** [comment]
Please note that as a paid user, I have also submitted a ticket on their ZenDesk. But since this affects community as well, hopefully it will be resolved in both places.

**Comment by troywweber7** [comment]
I received a response from them:

"This issue has been fixed and will be available in our next release (ETA 4-6 weeks)."

**Comment by lvpro** [comment]
I assume this is the same issue .... 22.0-22.1 we receive:

node_modules/ag-grid-enterprise/main.d.ts:4:32 - error TS7016: Could not find a declaration file for module './dist/ag-grid-enterprise.cjs.js'. '/home/clint/code/blaze/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js' implicitly has an 'any' type.
