### ISSUE TITLE
onCellDoubleClicked triggers twice

### ISSUE THREAD

**Issue by mschindlerMM** [ag-grid/ag-grid#3542]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

AgGrid seems to trigger the `onCellDoubleClicked` event twice instead of once. The Plunker shows that on a cell-doubleclick the `console.log` in the eventListener happens twice.

https://plnkr.co/edit/mhICNUerMwdj10rCf5OT?p=preview

**Current behavior**
`onCellDoubleClicked` triggered **twice**

**Expected behavior**
Should only trigger once.

**Please tell us about your environment:**

* **ag-Grid version:** 22.0.0
Not an issue with the prior used version 21.1.1

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

* **Language:** ES5/6

**Comment by gportela85** [comment]
@mschindlerMM this issue has been fixed in the latest branch. Thanks for reporting it.
