### ISSUE TITLE
Filter popup disappers when vertical scrollbar visibility toggles

### ISSUE THREAD

**Issue by IndProgo** [ag-grid/ag-grid#3545]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://www.ag-grid.com/javascript-grid-filter-component/#custom-filter-example
Grid should have vertical and horizontal scrollbar visible

**Current behavior**
Scroll the grid horizontally to the very right side. Open column filter popup for column "Sport" and type 1 in the filter input. When all rows are filtered, the filter popup box suddenly disappears. Because width changes, when right side scrollbar disappears, which fires scroll event and closes filter popup

**Expected behavior**
Filter popup stays open when filtering data 

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** X.X.X
ag-Grid 22.0.0

* **Browser:**
Firefox, Chrome, IE11, Edge

* **Language:** 
all

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog.

This is the reference and summary of the relevant issue:

AG-3705 - Filter popup disappears when vertical scrollbar visibility toggles

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
