### ISSUE TITLE
rangeSelectionChanged.finished is true for both first and last event while making selection

### ISSUE THREAD

**Issue by bez4pieci** [ag-grid/ag-grid#3547]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Ag-grid Angular implementation:
```HTML
<ag-grid-angular
    (rangeSelectionChanged)="selectionChanged($event)">
</ag-grid-angular>
```

Listener
```TypeScript
selectionChanged(event: RangeSelectionChangedEvent) {
    console.log(event.started + ', ' + event.finished);
}
```

Produces the following logs in the console, when the user is making a new selection by dragging over several cells diagonally:

```
false, true   // mouse down, start drag
true, false
true, false
...
true, false
false, true   // end drag, mouse up
```

As seen above, the first event confusingly has `true` for `finished`. 

**Current behavior**
First event has value `true` for key `finished` and `false` for `started`.

**Expected behavior**
First event should have value `false` for key `finished` and `true` for `started`.
Only the last event should have `true` for key `finished` and `false` for `started`.

**Please tell us about your environment:**
OSX (latest), Chrome (latest), Angular 8.2.2

* **ag-Grid version:** 22.0.0

* **Browser:** `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"`

* **Language:** TypeScript 3.5.3

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3707

rangeSelectionChanged event.finished / started flags are not as expected
