### ISSUE TITLE
AgGridVue does not work with Nuxt JS out of the box.

### ISSUE THREAD

**Issue by garrensweet** [ag-grid/ag-grid#3551]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. create a nuxtjs application
2. add ag-grid-vue (and other ag-grid dependencies)
3. create a component that imports { AgGridVue } from 'ag-grid-vue'
4. you get `unexpected token {` thrown from `lib/AgGridVue.js`

**Expected behavior**
The page loads and the ag-grid-vue component mounts

**Minimal reproduction of the problem with instructions**
see above

**What is the motivation / use case for changing the behavior?**
To fix ag-grid-vue so it can correctly work with Nuxt.

**Please tell us about your environment:**
Not Applicable

* **ag-grid-vue version:** 2.0.X
21.0.0 (definitely with all previous versions, too)

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
21.0.0 (definitely with all previous versions too)

* **VueJS version:** 2.0.X
2.x.x and above 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Babel or Babel + TS transpiling to CommonJS/ES5/ES(6/7)/ESNext

The reason this doesn't work in Nuxt is because the CJS file that is generated has `import {}` statements in it, which CJS doesn't recognize. So this has to be transpiled. You can force nuxt to do that in your `nuxt.config.(js/ts)` file:

```
build: {
    transpile: [
      'ag-grid-vue',
    ]
}
```

Your next hurdle is that your environment doesn't natively transform exports in CJS. So you'll need to add:

```
@babel/plugin-transform-modules-commonjs
```

And then add that to your plugins in your `.babelrc`.

**Comment by mhinton** [comment]
The need to transpile ag-grid-vue in a Nuxt project with SSR should be added to the documentation.
