### ISSUE TITLE
Need a column with fix data

### ISSUE THREAD

**Issue by yogesh-mali44** [ag-grid/ag-grid#3564]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Ag-Grid does not have an option to freeze data in a particular column

**Expected behavior**
Need to have a column e.g Sr.No which is static and fixed and does not change on any grid activity like sorting, pinning, dragging.

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** X.X.X
"ag-grid-enterprise": "^21.0.1",

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular 7

**Comment by davis4acca** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
