### ISSUE TITLE
Grid is not providing any way to change the column headers row background color or other styles on column header row hover

### ISSUE THREAD

**Issue by aliry** [ag-grid/ag-grid#3565]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Currently the grid only add "ag-column-hover" on a single column header when the column is hovered by mouse and there is no hover behavior for the column headers row

**Expected behavior**
Similar to data row containers which they get"ag-row-hover" class on hover, It would be helpful to have the column headers row container get a class (ex. "ag-column-row-hover") on column headers row being hovered.
This would help developers to easily customize the row column style on hover state.

**Please tell us about your environment:**
Any environment

* **ag-Grid version:** 22.1.0

* **Browser:**
Any browser

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Any Language

**Comment by davis4acca** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
