### ISSUE TITLE
Chart Hamburger Not Working with Custom Theme Name

### ISSUE THREAD

**Issue by jcmoore0** [ag-grid/ag-grid#3566]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Click Chart Hamburger 
Get error "Cannot read property of undefined"
```
line 116 community-modules/core/src/ts/environment.ts
return HARD_CODED_SIZES[this.getTheme().themeFamily].chartMenuPanelWidth;
```
**Expected behavior**
Chart Hamburger Opens chartMenu

**ag-Grid version:**  **v22.1.0**

** Comments **
The hard HARD_CODED_SIZES expect exact naming of themes:
ag-material-theme
ag-material-theme-dark
```
line 143 community-modules/core/src/ts/environment.ts
return { theme, el, themeFamily: theme.replace(/-dark$/, '') };
```

My custom themes were named:
ag-theme-custom-light
ag-theme-custom-dark

I changed my custom themes to the default provided theme names to enable it to work.
The docs say you can make your own theme using the convention 'ag-theme-<theme-name>'

It is not urgent priority, but suggest changing the docs until this is supported.
Thanks!

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-3693

Charts - Charts Panel does not work with custom theme
