### ISSUE TITLE
ag-grid example table is not rendering properly with Angular 7

### ISSUE THREAD

**Issue by vishalbhardwaj26** [ag-grid/ag-grid#3571]
Using ag-grid-community 22 version, table is not rendering properly, surprisingly all information rendered into one column. Table is not taking complete width

"ag-grid-angular": "^22.1.0",
 "ag-grid-community": "^22.1.0",

To Reproduce : Just followed ag-grid-angular example
![ag-grid-Capture](https://user-images.githubusercontent.com/15126782/70858524-6e210780-1f29-11ea-946c-61add2002793.PNG)

**Comment by seanlandsman** [comment]
It looks like you've not include the CSS - try something like this:

@import "~ag-grid-community/dist/styles/ag-grid.css";
@import "~ag-grid-community/dist/styles/ag-theme-balham.css";

https://www.ag-grid.com/angular-grid/ documents how to get started from the ground up

**Comment by pkErbynn** [comment]
At the root of your project folder, import the grid styles into your `styles.scss` link this:
```
@import 'ag-grid-community/styles/ag-grid.css';
@import 'ag-grid-community/styles/ag-theme-alpine.css';
```
or with relative path
```
@import '../node_modules/ag-grid-community/styles/ag-grid.css';
@import '../node_modules/ag-grid-community/styles/ag-theme-alpine.css';
```
or with CDN
```
@import url('https://unpkg.com/ag-grid-community@28.2.0/styles/ag-grid.css');
@import url('https://unpkg.com/ag-grid-community@28.2.0/styles/ag-theme-alpine.css');
```

When integrated, don't forget to re-run the server `npm run ng serve`, the table grid should render correctly with style as expected.

**Comment by Project121227** [comment]
In your component.ts file in the @component decorator after adding selector,template url and style add this line 
  encapsulation: ViewEncapsulation.None
you are good to go. This should work
