### ISSUE TITLE
cell style right alignment not working for enableCellTextSelection = true settings

### ISSUE THREAD

**Issue by ronisaha** [ag-grid/ag-grid#3574]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A plunker [https://next.plnkr.co/edit/QzuM03CzazUTnyCY](https://next.plnkr.co/edit/QzuM03CzazUTnyCY)

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
The columnDef with `type: "numericColumn"` or `cellStyle: {'text-align': 'right'}` content not showing in right alignment if we use `enableCellTextSelection: true,`

**Expected behavior**
The columnDef with `type: "numericColumn"` or `cellStyle: {'text-align': 'right'}` should show content in right alignment regardless of `enableCellTextSelection` settings. It was working till version  [22.0.0](https://next.plnkr.co/edit/brFuwUKTSShhFDKm)

**Please tell us about your environment:**
**MAMP Stack**

* **ag-Grid version:** 
 **>=22.1.0**

* **Browser:**
**Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by RemyGratwohl** [comment]
Noticed this as well after upgrading from 21.2.2 to 22.1.0

**Comment by gportela85** [comment]
This is a side-effect of a cellWrapper not working with text-align, it's a known issue that will be fixed in the next release.

For the time being use this CSS workaround

```
<style>
.ag-theme-balham .ag-numeric-cell .ag-cell-wrapper {
    flex-direction: row-reverse;
}
</style>
```

**Comment by ronisaha** [comment]
@gportela85 Thanks for the workaround. But sadly this is not working for 

```javascript
columnDefs: [
        // ...
        { cellStyle: {'text-align': 'right'}},
      //...
]
```
http://next.plnkr.co/edit/31oGgf07BD3gR6nf

**Comment by gportela85** [comment]
@ronisaha While we work on this, please use: 
```javascript
columnDefs: [
        // ...
        { cellStyle: {'direction': 'rtl'}},
      //...
]
```
