### ISSUE TITLE
Could not find component with name of... Is it in Vue.components?

### ISSUE THREAD

**Issue by evgencode** [ag-grid/ag-grid#3575]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I get an error: Could not find component with name of CellTest. Is it in Vue.components?

**Expected behavior**
component is working fine

**Please tell us about your environment:**
Windows 10, Webstorm

* **ag-Grid version:** 
21.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

* **Language:**
ES6/7

I really can’t understand how to work with vue components. It is very irrational to look for components strictly in the parent component.

Why can't I just specify the imported component object in the cellRendererFramework?
Try placing the grid on a coarser nesting or in a slot. You will get an error:  _Could not find component with name of ****. Is it in Vue.components?_

I use documentation: https://www.ag-grid.com/vue-components/

For example:

Test.js:

```
import { AgGridVue } from 'ag-grid-vue';
import styles from './style.scss?module';
import { CellTest } from './cells';
import { getRowData, getColumnDefs, ComponentWrap } from './helper';

export default {
  name: 'Test',
  components: {
    AgGridVue,
    CellTest
  },
  data() {
    return {
      gridOptions: {
        pagination: false,
        enableColResize: true,
        enableSorting: true,
        rowSelection: 'single',
        headerHeight: 42,
        floatingFiltersHeight: 42,
        rowHeight: 36,
        context: {
          componentParent: this
        }
      },
      rowData: getRowData(),
      columnDefs: getColumnDefs()
    };
  },
  methods: {},
  render(h) {
    const props = {
      gridOptions: this.gridOptions,
      rowData: this.rowData,
      columnDefs: this.columnDefs
    };

    return (
      <div class={styles.root}>
        <ComponentWrap>
          <AgGridVue {...{ props }} style={{ height: '100%' }} />
        </ComponentWrap>
      </div>
    );
  }
};
```

helper.js

```
export const getRowData = () => [
  {
    range_end: '22',
    range_start: '11',
    vendor: 'Slim Fast',
    suffix: 'TT'
  },
  {
    range_end: '335',
    range_start: '330',
    vendor: 'BlaBla',
    suffix: 'HH'
  }
];

export const getColumnDefs = () => [
  {
    headerName: 'ID',
    field: 'request_id',
    colId: 'params',
    cellRendererFramework: 'CellTest'
  },
  {
    headerName: 'RangeStart',
    field: 'range_start'
  },
  {
    headerName: 'Vendor',
    field: 'vendor'
  },
  {
    headerName: 'Suffix',
    field: 'suffix'
  }
];

export const ComponentWrap = {
  render(h) {
    return <div style={{ height: '100%' }}>{this.$slots.default}</div>;
  }
};
```

CellTest.js

```
export default {
  name: 'CellTest',
  render(h) {
    const data = this.params.data;
    return (
      <div>
        <span>Cell Test: {JSON.stringify(data)}</span>
      </div>
    );
  }
};
```

**I get an error: Could not find component with name of CellTest. Is it in Vue.components?**

What's wrong?

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by evgencode** [comment]
Thank you.
I've investigated this issue.
It works if implemented like this. But I think it is not documented.
We should use Vue.extend in cellRendererFramework property.

helper.js

```
import { CellTest } from './cells';

export const getRowData = () => [
  {
    range_end: '22',
    range_start: '11',
    vendor: 'Slim Fast',
    suffix: 'TT'
  },
  {
    range_end: '335',
    range_start: '330',
    vendor: 'BlaBla',
    suffix: 'HH'
  }
];

export const getColumnDefs = () => [
  {
    headerName: 'ID',
    field: 'request_id',
    colId: 'params',
    **cellRendererFramework: Vue.extend(CellTest )**
  },
  {
    headerName: 'RangeStart',
    field: 'range_start'
  },
  {
    headerName: 'Vendor',
    field: 'vendor'
  },
  {
    headerName: 'Suffix',
    field: 'suffix'
  }
];

export const ComponentWrap = {
  render(h) {
    return <div style={{ height: '100%' }}>{this.$slots.default}</div>;
  }
};
```

Also, we may not specify the component in componetns property in "Test"

**Comment by shuheb** [comment]
Hi,

Thank you for your message. Our consultants have provided the following example for you:

https://next.plnkr.co/edit/eMxyqjuWiY3vh6ea?preview

Hope this helps

Shuheb‍
