### ISSUE TITLE
React: ag-grid filterParams newRowsAction keep does not keep filter search text

### ISSUE THREAD

**Issue by benlesh** [ag-grid/ag-grid#3576]
I'm working with a paid corporate license. I'm not sure if there is a better channel to file this bug that would get a faster response.

When updating rows passed to agGrid with streaming data, and you have a column definition with `filterParams: { newRowsAction: 'keep' }`, and on the grid `deltaRowDataMode={true}`, it will indeed "keep" the filters themselves, but if you happen to be searching for a column to filter by using the provided text box in the filter component, the textbox is cleared on new rows.

Honestly, I can't even get AgGrid working in a codesandbox to show you anything helpful. Sorry.  Something like this ought to do it:

```tsx 

function App() {
  const [rows, setRows] = useState([
    { value: 0 },
    { value: 1 },
    { value: 2 },
    { value: 3 },
  ]);

  useEffect(() => {
    let i = 0;
    // constantly add new rows.
    const id = setInterval(() => {
      setRows(rows => [...rows, { value: i++ % 4 }])
    }, 1000);
    return () => clearInterval(id);
  }, []);

  return (
    <div className="App">
      <AgGrid
        headerHeight={24}
        rowHeight={20}
        rowData={rows}
        deltaRowDataMode={true}
        columnDefs={[
          {
            field: 'value',
            enableFiltering: true,
            filterParams: {
              newRowsAction: 'keep'
            }
          }
        ]}
      />
    </div>
  );
}
```

Given the above, if you open the column filter drop down and start typing in the provided search textbox, when the new rows come in, the textbox will be cleared even as you're typing.

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

ag-Grid staff does not provide support through GitHub. If you are a customer please contact us through our official support channel. 

However it looks like you're not configuring getRowNodeId when using deltaRowDataMode. Doing so seems to make this example work. Please see the following example https://next.plnkr.co/edit/xVkgGeT2z24X2vX5

We will now mark this ticket at managed-by-the-community.

Thanks
