### ISSUE TITLE
IsColumnFuncParams not coming from the @ag-grid-enterprise/all-modules like the rest of the import types

### ISSUE THREAD

**Issue by Iamheathsmith** [ag-grid/ag-grid#3582]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

This was talked about in this closed issue but not sure if it was fixed. 
https://github.com/ag-grid/ag-grid/issues?q=is%3Aissue+IsColumnFuncParams+is%3Aclosed
IsColumnFuncParams is wanting to come from a package that causing errors and more. we are using AG Grid version 22.1.1 and we are using the **@ag-grid-enterprise/all-modules** and all my imports are coming from that. This one is the only one that is causing issues. 

**Expected behavior**

i expect that this type of **IsColumnFuncParams** to come from the  **@ag-grid-enterprise/all-modules** like the rest of my imports.

* **ag-Grid version:** X.X.X

ag-Grid version: 22.1.1
* **Browser:**

Browser: N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Language: [ TypeScript 3.5.1]

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - this will be included in our next release, due January

thanks
