### ISSUE TITLE
Feature Request : Decouple Sidebar from Grid

### ISSUE THREAD

**Issue by vick-subbu** [ag-grid/ag-grid#3584]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The SideBar accepts only "right" and "left" positions

**Expected behavior**
The Sidebar Can be moved out of the grid or some positions like "top" or "bottom" of the grid can be supported for customers who want to move the grid out of the grid

* **ag-Grid version:** X.X.X
21.2.2

**Comment by shuheb** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
