### ISSUE TITLE
Cannot writeText to clipboard in Firefox 71.0 (64 bit)

### ISSUE THREAD

**Issue by ksrb** [ag-grid/ag-grid#3595]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/zUe18KPX899hEJA2TQ7g?p=preview

**Current behavior**
Clicking on any row in Firefox 71 causes a exception to be thrown:
```
uncaught exception: undefined
````

**Expected behavior**
Clicking on any row should write the following into the clipboard:
```
Congrats your clipboard has text :D
```

**Please tell us about your environment:**
* OS: MacOS Mojave
* Version: 10.14.6
* **ag-Grid version:** latest

**Additional information**
In **Chrome** the exception usually corresponds to:
```
Uncaught (in promise) DOMException: Document is not focused.
```
But that might be a red herring.

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
After investigating this further, we have concluded that this is not an issue inherent with the grid. 

Unfortunately, this issue is caused by external factors thus we are unable to provide a workaround. 

However, we found this during our investigation which may offer some help: https://bugzilla.mozilla.org/show_bug.cgi?id=1560373

Many thanks,
