### ISSUE TITLE
sass warning since ag-grid upgrade

### ISSUE THREAD

**Issue by lk77** [ag-grid/ag-grid#3597]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Hello,

when building my app i have deprecation warnings :

```
DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-secondary-font-weight: null` at the root of the
stylesheet.

    ╷
211 │     $ag-secondary-font-weight: $secondary-font-weight !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 211:5        @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-material/vars/_ag-theme-material-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-material/vars/_ag-theme-material-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-material/sass/ag-theme-material.scss 1:9                      @import
    stdin 28:9
```

it seems that you need to update your scss files to be compatible with the future sass 2.0.

thanks.

**Comment by shuheb** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Since it is impossible to use in this case any web based tool to provide with a reproducible scenario, I would suggest that you send us whatever is that you can so you can investigate further. Some suggestions are:

- github
- zip files
- code fragments

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

Thanks

**Comment by lk77** [comment]
Hello,

there is no need for a reproductible scenario.

**Comment by slavoroi** [comment]
The same for me,
After upgrading to:
```
"@ag-grid-community/all-modules": "22.1.1",
  "@ag-grid-enterprise/all-modules": "22.1.2"
```
We get:
EPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-border-color: null` at the root of the
stylesheet.

   ╷
19 │     $ag-border-color: $border-color !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 19:5     @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-cell-horizontal-border: null` at the root of the
stylesheet.

   ╷
31 │     $ag-cell-horizontal-border: $cell-horizontal-border !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 31:5     @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-font-family: null` at the root of the
stylesheet.

   ╷
91 │     $ag-font-family: $font-family !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 91:5     @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-font-size: null` at the root of the
stylesheet.

   ╷
95 │     $ag-font-size: $font-size !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 95:5     @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-foreground-color: null` at the root of the
stylesheet.

    ╷
103 │     $ag-foreground-color: $foreground-color !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 103:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-foreground-opacity: null` at the root of the
stylesheet.

    ╷
107 │     $ag-foreground-opacity: $foreground-opacity !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 107:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-header-background-color: null` at the root of the
stylesheet.

    ╷
127 │     $ag-header-background-color: $header-background-color !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 127:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-header-height: null` at the root of the
stylesheet.

    ╷
139 │     $ag-header-height: $header-height !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 139:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-row-border-width: null` at the root of the
stylesheet.

    ╷
187 │     $ag-row-border-width: $row-border-width !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 187:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-row-height: null` at the root of the
stylesheet.

    ╷
195 │     $ag-row-height: $row-height !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 195:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-secondary-font-family: null` at the root of the
stylesheet.

    ╷
203 │     $ag-secondary-font-family: $secondary-font-family !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 203:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-secondary-font-size: null` at the root of the
stylesheet.

    ╷
207 │     $ag-secondary-font-size: $secondary-font-size !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 207:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-secondary-font-weight: null` at the root of the
stylesheet.

    ╷
211 │     $ag-secondary-font-weight: $secondary-font-weight !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 211:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-secondary-foreground-color-opacity: null` at the root of the
stylesheet.

    ╷
215 │     $ag-secondary-foreground-color-opacity: $secondary-foreground-color-opacity !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-base/vars/_ag-theme-base-import-legacy-vars.scss 215:5    @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                      @import
    stdin 23:9                                                                                                                 root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-hover-color: null` at the root of the
stylesheet.

   ╷
48 │     $ag-hover-color: $hover-color !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 48:5  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                 @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                       @import
    stdin 23:9                                                                                                                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-odd-row-background-color: null` at the root of the
stylesheet.

   ╷
52 │     $ag-odd-row-background-color: $odd-row-background-color !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 52:5  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                 @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                       @import
    stdin 23:9                                                                                                                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-selected-color: null` at the root of the
stylesheet.

   ╷
80 │     $ag-selected-color: $selected-color !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-import-legacy-vars.scss 80:5  @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/vars/_ag-theme-balham-vars.scss 1:9                 @import
    node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss 1:9                       @import
    stdin 23:9                                                                                                                  root stylesheet

This deprecation warnings, please fix them.

**Comment by RAllner** [comment]
We get the same warnings like slavoroi and lk77 since we upgraded to 22.1.1. Any news on this or a link to the new issue/fix?

```
EPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-border-color: null` at the root of the
stylesheet.

   ╷
19 │     $ag-border-color: $border-color !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\ag-grid-community\dist\styles\ag-theme-base\vars\_ag-theme-base-import-legacy-vars.scss 19:5     @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-vars.scss 1:9                @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\sass\ag-theme-balham.scss 1:9    
                  @import
    stdin 12:9
                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-font-family: null` at the root of the
stylesheet.

   ╷
91 │     $ag-font-family: $font-family !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\ag-grid-community\dist\styles\ag-theme-base\vars\_ag-theme-base-import-legacy-vars.scss 91:5     @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-vars.scss 1:9                @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\sass\ag-theme-balham.scss 1:9    
                  @import
    stdin 12:9
                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-header-background-color: null` at the root of the   
stylesheet.

    ╷
127 │     $ag-header-background-color: $header-background-color !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\ag-grid-community\dist\styles\ag-theme-base\vars\_ag-theme-base-import-legacy-vars.scss 127:5    @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-vars.scss 1:9                @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\sass\ag-theme-balham.scss 1:9    
                  @import
    stdin 12:9
                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-header-height: null` at the root of the
stylesheet.

    ╷
139 │     $ag-header-height: $header-height !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\ag-grid-community\dist\styles\ag-theme-base\vars\_ag-theme-base-import-legacy-vars.scss 139:5    @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-vars.scss 1:9                @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\sass\ag-theme-balham.scss 1:9    
                  @import
    stdin 12:9
                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-input-border-color: null` at the root of the        
stylesheet.

    ╷
163 │     $ag-input-border-color: $input-border-color !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\ag-grid-community\dist\styles\ag-theme-base\vars\_ag-theme-base-import-legacy-vars.scss 163:5    @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-vars.scss 1:9                @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\sass\ag-theme-balham.scss 1:9    
                  @import
    stdin 12:9
                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-tooltip-border-radius: null` at the root of the     
stylesheet.

    ╷
235 │     $ag-tooltip-border-radius: $tooltip-border-radius !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\ag-grid-community\dist\styles\ag-theme-base\vars\_ag-theme-base-import-legacy-vars.scss 235:5    @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-import-legacy-vars.scss 3:9  @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-vars.scss 1:9                @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\sass\ag-theme-balham.scss 1:9    
                  @import
    stdin 12:9
                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$ag-border-radius: null` at the root of the
stylesheet.

   ╷
16 │     $ag-border-radius: $border-radius !global;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-import-legacy-vars.scss 16:5  @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\vars\_ag-theme-balham-vars.scss 1:9                 @import
    node_modules\ag-grid-community\dist\styles\ag-theme-balham\sass\ag-theme-balham.scss 1:9    
                   @import
    stdin 12:9
                   root stylesheet
```

**Comment by sonsina** [comment]
hi.
same here.
is this being handled? 

I'd appreciate an update.

**Comment by mkresse** [comment]
As mentioned by @dpraul in https://github.com/ag-grid/ag-grid/issues/3623#issuecomment-577237456, the legacy theme variable import seems to cause the problem. It can be deactivated via `$ag-suppress-legacy-var-import: true;`.

**Comment by lk77** [comment]
You can suppress the legacy var import to suppress the warning, but don't forget to prepend 'ag-' to every legacy var you are still using.

**Comment by slavoroi** [comment]
$ag-suppress-legacy-var-import: true; ruined our css, why do you use '!global'?

**Comment by lk77** [comment]
yes, it can ruin your css if you are using legacy var import, just prepend every sass var with 'ag-' and you should be fine.

**Comment by klemenoslaj** [comment]
This issue is closed, but is it actually resolved?

I get 2 warnings:
```
121 │ $-ag-allow-color-param-access-with-ag-param: true !global;
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
220 │     $ag-grid-size: $grid-size !global;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by wegry** [comment]
When using `sass@1.26.3` and the alpine theme and sass modules,

```scss
@use '@ag-grid-community/core/dist/styles/ag-theme-alpine/sass/_ag-theme-alpine-mixin'
    as alpine with
    (
      $ag-suppress-legacy-var-import: true,
    );
```

We're getting

```
SassError: This variable was not declared with !default in the @used module.
   ╷
12 │       $ag-suppress-legacy-var-import: true,
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  ../ag-grid/styles/ag-theme-project-mixin.scss 12:7  @forward
  ../ag-grid/styles/index.scss 4:1                      @forward
  ../ag-grid/theme.scss 1:1                             @use
```
