### ISSUE TITLE
ag-grid-vue: column order changes when definition udpated

### ISSUE THREAD

**Issue by WillMLumere** [ag-grid/ag-grid#3599]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible scenario**:

https://stackblitz.com/edit/ag-grid-vue-columnorder

**Current behavior**

When updating a column definition in a live grid, that column moves to the right end of the table
**Expected behavior**

Columns remain in the order specified by columnDefs after update
**Please tell us about your environment:**

StackBlitz 
* **ag-Grid version:** 22.0.0

* **Browser:** multiple

* **Language:** ES6/7, ES5

I reviewed similar issue #2874 which was closed with a comment that it would be resolved in v20.1

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

We would recommend that you use delta column mode when updating column definitions. Please see https://www.ag-grid.com/javascript-grid-column-definitions/#delta-columns.

This ticket will now be marked as managed-by-community.

Thanks

**Comment by manju-bwd** [comment]
having the same issue with react. is there any solution to this?
