### ISSUE TITLE
Sidebar keyboard accessibility

### ISSUE THREAD

**Issue by hannahbennett27** [ag-grid/ag-grid#3608]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Sidebar is not keyboard accessible. 
The vertical tabs are selectable by keyboard, but offer no UI indication that they are focused when tabbing. 

**Current behaviour (& Reproducible Scenario)**
_Using ag-Grid demo (https://www.ag-grid.com/example.php)_
- Mouse select 'Columns' in the sidebar
- Press `tab` and `return/enter`
- See that the 'Filters' sidebar is now selected/open, but no focus state was given to the vertical tab

**Expected behavior**
UI focus state on tab-able buttons/tabs

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
Using version 22.0.0

* **Browser:**
ag-Grid demo tested using Chrome & Firefox

* **Language:**
TypeScript

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognise this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-3253 | Accessibility / navigation Allow to navigate with keyboard though the context menu/column headers/sidebar/tool panel
