### ISSUE TITLE
If 'enableRangeSelection' is true it's possible to paste a value into a non editable field

### ISSUE THREAD

**Issue by MrFritmand** [ag-grid/ag-grid#3611]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
It can be tested in your example of range selection(The one where the cells are not editable):
https://www.ag-grid.com/javascript-grid-range-selection/#example-range-selection
Just copy any cell or cells and paste into another cell.

**Current behavior**
If a user selects one or more cells and pastes any value into them the cell('s) changes to the value('s) even when the cell is not set to be editable.

**Expected behavior**
Well, I expect that it should not be possible to paste any value into a non-editable.

**Please tell us about your environment:**
I'm not sure if it matters in this scenario but I have tested it on Windows 10 Enterprise (1903) and Mac OS 10.15.1 in Chrome (79.0.3945.117) and Firefox (72.0.1).
And the bug seems to exist in Chrome and Firefox.

* **ag-Grid version:** 22.1.1

* **Browser:** Chrome (79.0.3945.117) and Firefox (72.0.1)

* **Language:** All but on Mac it does not seem to happen in React and Vue.

**Comment by MrFritmand** [comment]
Also even with 'suppressClipboardPaste' set to true it's still possible to paste

**Comment by MrFritmand** [comment]
Moved to issue to ag grid enterprise:
https://github.com/ag-grid/ag-grid-enterprise/issues/242

**Comment by MrFritmand** [comment]
Reopening sins others may have the same problem

**Comment by shuheb** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:
AG-3752 - When enableRangeSelection=true it's possible to paste a value into a non editable field
