### ISSUE TITLE
How to mix the custom getContextMenuItems with the default allowed by ag-Grid?

### ISSUE THREAD

**Issue by Lertis** [ag-grid/ag-grid#3615]
**I'm submitting a
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

I'm requesting for a support with the question about getContextMenuItems. 

What I've tried to do before:
1. Use ag-Grid in my Angular project.
2. Update app.module.ts file by adding  ```import 'ag-grid-enterprise';``` to be able to use default getContextMenuItems.  Example here: https://www.ag-grid.com/javascript-grid-clipboard/
3. Everything works perfectly, but I want to use only "Copy with headers" and plus some custom functionality. For example: "Copy with headers", "Copy cell", "Open in new window" etc.

StackBlitz link with the simpliest example with the default handler for the mouse right click: https://stackblitz.com/edit/angular-smtbyw

StackBlitz link with the custom mouse right click hander: 
https://stackblitz.com/edit/angular-27aacd

**Current behavior**
Can't mix the default and custom handlers for getContextMenuItems

**Expected behavior**
Be able to use "Copy with Headers" and plus custom handers for getContextMenuItems

**Please tell us about your environment:**
Visual Studio Code

* **ag-Grid version:** 21.2.2

* **Browser:**
Google Chrome

* **Language:** Angular 8, TypeScript 3+, ES6

**Comment by Lertis** [comment]
I found the way. Let me leave it here for another one who will be looking for the same feature.
What you should do:
1. *.html file
```
<ag-grid-angular
     ....
    [getContextMenuItems]="getContextMenuItems"
     ....
</ag-grid-angular>
```

2. *.ts file
  ```
getContextMenuItems(params) {
    return [
      {
        name: 'Open in a new tab',
        action: () => {
           window.open(params.node.data.link);
        },
      },
      'copyWithHeaders'
    ];
  }
```

This will you to mix the custom handlers with the default provided by ag-Grid.

**Comment by kanta-mir** [comment]
@Lertis This is very good solution, it worked. But the others the default ones, dont even show up. How to get their functionality. Thanks
