### ISSUE TITLE
Deselect of row possible although it shouldn`t

### ISSUE THREAD

**Issue by Paul6552** [ag-grid/ag-grid#3618]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Although I have these gridOptions with rowDeselection -> false and supressCellSelection true I can still deselect the row with the space button

```
<AgGridReact
	rowHeight={50}
	rowSelection={'single'}
	onSelectionChanged={rowClicked}
	rowDeselection={false}
	suppressCellSelection={true}
	getRowNodeId={getRowNodeId}
	columnDefs={columnsTaenzeAGGrid}
	onFirstDataRendered={firstdataRenderer}
	rowData={props.tabledata}
	getRowStyle={changeRowColor}
	onGridReady={onGridReady}
	onRowDataChanged={onRowDataChanged}>
</AgGridReact>
```

Plunker as well: [Example with plunker](https://plnkr.co/edit/zjXWLZ8mqjiPGFQIhgGt?p=preview)
Try to deselect the row with click (it is not working, perfect) BUT it is still possible with the space button.

Current behaviour.
It is possible to unselect the row with the **space** button. 

With click or shift click it isn`t working (that is correct)

**Expected behavior**
It should not be possible to unselect the row, also not with the space button

**Please tell us about your environment:**
react 16.12.0, node 12.14.1

* **ag-Grid version:** 22.1.1

* **Browser:**
Chrome as Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
react
typescript 3.7.4, ES5

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

Thank you for your message.

This is the intended behaviour of the grid.

You can look into suppressKeyboardEvent to achieve this effect:

https://www.ag-grid.com/javascript-grid-keyboard-navigation/#suppressKeyboardEvents

Hope this helps.

Kind Regards,
Shuheb
