### ISSUE TITLE
Column selection doesn't work on all columns if one is hidden (column panel in sidebar)

### ISSUE THREAD

**Issue by ArnaudFlaesch** [ag-grid/ag-grid#3620]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Plunker : https://plnkr.co/edit/rIlMSK2uXJhA7SGTjYXw?p=preview

![icon_bug](https://user-images.githubusercontent.com/9250759/72475872-d594d600-37b9-11ea-8fd6-218dc64226e7.png)

**Current behavior**

If one of the column is hidden at first, then the master checkbox (left of the search bar in the column panel) doesn't work. It is only activated when the checkbox associated with the hidden column is checked.

**Expected behavior**

When a column is hidden and its checkbox unchecked, clicking on the master checkbox should check all checkboxes the first time and then uncheck them all the second time.

**Please tell us about your environment:**

AG Grid 22.1.2
Chrome 79
Windows 10
Angular 8
TypeScript 3.5.3

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-3751 | Select All checkbox in sidebar does not select hidden columns

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
