### ISSUE TITLE
getFrameworkComponentInstance is not defined on ICellRendererComp

### ISSUE THREAD

**Issue by krzysiekpiasecki** [ag-grid/ag-grid#3621]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Here is an example of source code from original documentation under "Accessing Cell Renderer Instances".

> // example - get cell renderer for first row and column 'gold'
var firstRowNode = gridOptions.api.getDisplayedRowAtIndex(0);
var params = { columns: ['gold'], rowNodes: [firstRowNode]};
var instances = gridOptions.api.getCellRendererInstances(params);
if (instances.length > 0) {
    // got it, user must be scrolled so that it exists
    var wrapperInstance = instances[0];
    var frameworkInstance = wrapperInstance.getFrameworkComponentInstance();
}

According to types definition ```instances``` is the array of ```ICellRendererComp```, so method ```getFrameworkComponentInstance``` is not defined on array elements. In consequences the compilation of Angular application (type script support) is not possible. Under the hood ```frameworkInstance``` is a wrapper instance, which has this method (invastigate with dev tools).

This is the question and "dirty" workaround.
https://stackoverflow.com/questions/59721659/property-getframeworkcomponentinstance-does-not-exist-on-type-icellrendererco

**Comment by krzysiekpiasecki** [comment]
Closing because casting to any solves the problem.

**Comment by ashish-xactlycorp** [comment]
What if we are not using typescript. I am trying this in react

**Comment by StephenCooper** [comment]
**From v27 of AG Grid**

You no longer need to use the method `getFrameworkComponentInstance()`, as your framework components will be returned directly from `getCellRendererInstances()`. So you can loop through the components and call their methods directly. 

```ts
const instances = this.gridApi.getCellRendererInstances(params) as MyComponent[];

instances.forEach((instance) => {
  instance.myComponentFunction();
});

```
See updated documentation here: [Component Cell Renderer][1]

  [1]: https://ag-grid.com/angular-data-grid/component-cell-renderer/#accessing-cell-renderer-instances
