### ISSUE TITLE
User defined column types overwritten by defaultColumnTypes

### ISSUE THREAD

**Issue by lunarmoon26** [ag-grid/ag-grid#3622]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
1. Re-define `numericColumn` in gridOptions.columnTypes, for example
```
numericColumn: {
  headerClass: "my-numeric-header",
  cellClass: "my-numeric-cell"
  filter: 'agNumberColumnFilter',
  enablePivot: false
}
```
2. Use the type in one of the ColDef
3. The re-defined numericColumn was overwritten by the default one, i.e. 
```
   numericColumn: {
        headerClass: "ag-numeric-header",
        cellClass: "ag-numeric-cell"
    }
```

**Expected behavior**
User defined default type (`numericColumn`, etc.) overwrites the original default type.

On the line:
https://github.com/ag-grid/ag-grid/blob/996ffcdcb828ffa3448d57fa919feb9eb465df15/community-modules/core/src/ts/columnController/columnFactory.ts#L343

lodash merges the object from right to left, that essentially makes DefaultColumnTypes overwrite the user defined types regardless (shallow copy)

Suggest change:
```
 const allColumnTypes = _.assign({}, DefaultColumnTypes, this.gridOptionsWrapper.getColumnTypes()); 

```

**Please tell us about your environment:**
OS: Windows
IDE: VS Code
Package Manager: NPM
Angular: 8.1.2
TS Config:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

* **ag-Grid version:** 21.2.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

* **Language:** 
Typescript 3.4.3

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
HI,

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3779: When trying to override a default column Type the grid shows no warnings

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

For more information on when can you expect your ticket to be fixed please check:

https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket- 

Regards

Ahmed‍
