### ISSUE TITLE
AgGridReact: autoHeight does not work on a cell using cellRendererFramework

### ISSUE THREAD

**Issue by gigerdo** [ag-grid/ag-grid#3625]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
The error can be seen in this plunker: https://plnkr.co/edit/wIB5yi0K0bwj9PC8VFSx?p=preview

Each row should have a height of ~60px. I have provided the same also as a simple cellRenderer. There the behaviour is as expected. For the react component in cellRendererFramework the height ist not calculated correctly.

**Current behavior**
The autoHeight flag has no effect when using cellRendererFramework. The row height is always at the minimum height.

**Expected behavior**
The height of the row is exactly the total height of the React cell renderer component.

* **ag-Grid version:** 22.1.1

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"

* **Language:** all

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-3275 | cellRenderer+React+autoHeight not calculating height correctly - setTimeout(api.resetRowHeights()) is a workaround

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by JakeNam** [comment]
cellRendererFramework: (params) => {
                const ipList = params.value
                params.node.setRowHeight(25*ipList.length)
                const listItem = ipList.map((ip, index) => <Box key={index}>{ip}</Box>)
                return (
                    <React.Fragment>
                        {listItem}
                    </React.Fragment>
                );
            }

**Comment by BenLorantfy** [comment]
@AhmedAGadir why close this issue if it's not fixed?  Can this be re-opened?
