### ISSUE TITLE
Turn on/off pagination dynamically 

### ISSUE THREAD

**Issue by MrFritmand** [ag-grid/ag-grid#3638]
This is related to this issue: #3624 but the question is if it's possible to turn pagination on/off dynamically without having to reload the page.

**Scenario 1:** The user wants to turn on pagination to concentrate on a smaller amount of data.
**Scenario 2:** The user wants to turn off pagination for a better overview of the data.

**Current behavior**
```
gridoptions.pagination = true; //pagination does get set to the value but nothing else happens.
```
**Expected behavior**
The grid turns on/off pagination

* **ag-Grid version:** v22.1.1

**Comment by icedjello** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog.

This is the reference and summary of the relevant issue:

AG-1731 | Pagination panel to be turned on and off

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by gfilomena** [comment]
my workaroud was to put the logic outside and add @Input field in the component where is located the ag-grid table and passing a different value for the pagination true/false. works for me.

**Comment by darkangel081195** [comment]
@gfilomena Can u kindly give a draft solution of what u did, i have the same issue and it would be helpful

**Comment by AndrejGajdos** [comment]
@icedjello there are no results for AG-1731.

<img width="1230" alt="Screenshot 2021-05-27 at 11 03 46" src="https://user-images.githubusercontent.com/1593758/119798312-4e8e5c80-bedb-11eb-890e-e727265c955b.png">

**Comment by torrobinson** [comment]
This issue still hasn't been fixed 👀

**Comment by joshkarges** [comment]
The documentation mentions a `setPagination` function, but it is nowhere to be found. https://www.ag-grid.com/react-data-grid/row-pagination/#reference-pagination-setPagination

**Comment by StephenCooper** [comment]
> The documentation mentions a `setPagination` function, but it is nowhere to be found. https://www.ag-grid.com/react-data-grid/row-pagination/#reference-pagination-setPagination

This was added in v29 so I suspect you are using an older version of the grid?

**Comment by joshkarges** [comment]
Turns out you can still do it in v27 with `_.invoke(gridApi, 'api.gridOptionsService.set', 'pagination', trueOrFalse)`
