### ISSUE TITLE
please consider making theme changeable without reload

### ISSUE THREAD

**Issue by MolallaComm** [ag-grid/ag-grid#3640]
Users being able to toggle between light and dark mode in dapps/spas is all the rage - it would be nice if ag-grid properly supported it without recreating the grid and jumping thru hoops.  You might also consider adding support for @media (prefers-color-scheme) at the same time so as to pick up the users global preference if set.

This guy has a workable approach almost complete - i just don't want to take the time to go thru and figure out what vars are missing - hence the feature request.

https://stackblitz.com/edit/ag-grid-scss-themes?embed=1&file=src/styles.scss

**Comment by icedjello** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
