### ISSUE TITLE
Add an origin attribute to grid events such as onRowSelected

### ISSUE THREAD

**Issue by alexwileyy** [ag-grid/ag-grid#3641]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The `onRowSelected` event on the ag-grid component is triggered in multiple scenarios. The two scenarios for the context of this issue are when a user manually selects a row on the grid and when a row is selected via the grid API.

The grid event that gets returned look like the example below:
```
api: GridApi {…}
columnApi: ColumnApi {...}
context: undefined
data: {...}
node: RowNode {...}
rowIndex: 0
rowPinned: undefined
type: "rowSelected"
```

**Expected behavior**
Behaviour works as expected, an event is fired for both the user click event and the grid api event **however,** it would be extremely useful if the event were to differentiate over the origin of where the click came from.

For example, on the retuned event it would be great if there was an additional attribute which gave information on whether the selection event came from
- A user click (manually interacting with the UI)
- An API triggered event (executed via the grid API)

Example:
```
{
    ...other event info,
    origin: 'click',
}
```

The frustration behind this being that currently, I have the `onRowSelected` listener attached to the grid. The event handler is called whenever a row is selected, which is great. However, I do not want the behaviour of the function to be executed when the selection event originates from the `gridApi`. With the current event format, it is not possible to distinguish between an event that originated from a user click vs an event which originated from the API.

* **ag-Grid version:** 21.2.1

* **Browser:**
Brave (Chromium based)

* **Language:** React however affects all

**Comment by icedjello** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by alexwileyy** [comment]
@icedjello I fail to see how your response is relevant to the above feature request? Surly a feature request such as this belongs here?
