### ISSUE TITLE
Paste into a non editable cell should not update cell value

### ISSUE THREAD

**Issue by antoinebrault** [ag-grid/ag-grid#3642]
https://github.com/ag-grid/ag-grid/blob/master/enterprise-modules/clipboard/src/clipboard/clipboardService.ts#L359

This line should be 
```!column.isCellEditable(rowNode) ||```
instead of 
```!column.isCellEditable ||```

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/L6YWMTxuhuYrEQqPWdd7?p=preview
Paste into non editable column Athlete 

* **ag-Grid version:**
22.1.1

**Comment by gportela85** [comment]
@antoinebrault thanks for reporting, issue fixed in `latest`.
