### ISSUE TITLE
404 Link in docs on page titled Redux Integration - Part 1

### ISSUE THREAD

**Issue by rastalamm** [ag-grid/ag-grid#3646]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

On the [Redux Integration - Part 1 page](https://www.ag-grid.com/react-redux-integration-pt1/) in the docs, there is a 404'ing url. The text is "React/Redux More Details" which points to https://www.ag-grid.com/react-more-details/react-15#react-redux-hoc

**Expected behavior**

url to redirect to correct place

**Please tell us about your environment:**

chrome
* **ag-Grid version:** X.X.X

master
* **Browser:**

n/a
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

n/a

**Comment by seanlandsman** [comment]
Hi - thanks for reporting this. I've just corrected this locally and it'll be updated when we do our next release.

If you're interested, the correct link should be: https://www.ag-grid.com/react-apis/#react-redux-hoc

thanks,
