### ISSUE TITLE
enableCellTextSelection does not exist on 'GridOptions'

### ISSUE THREAD

**Issue by attilaaf** [ag-grid/ag-grid#3656]
I cannot get `enableCellTextSelection` to work. It is not defined in GridOptions and it does not work.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
enableCellTextSelection does not exist on 'GridOptions' for 19.0

**Expected behavior**
Expect that enableCellTextSelection is an option and text selection of cells is possible
https://www.ag-grid.com/javascript-grid-clipboard/#using-enablecelltextselection

**Please tell us about your environment:**
OSX, Chrome (latest)

* **ag-Grid version:** X.X.X
19.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by shuheb** [comment]
Hi,

The functionality you're looking for is not available in the 19.0 version of ag-grid you're using. You need to upgrade to the latest version of ag-grid to use enableCellTextSelection according to the documentation link you pasted above.

We are going to close this ticket. If you are a customer please contact us through our official support channel.
