### ISSUE TITLE
Custom Filter Position issue

### ISSUE THREAD

**Issue by onlyreddy** [ag-grid/ag-grid#3659]
**I'm submitting a issue in custom filter. Custom filter components that are opened near the edge of the screen are rendered such that they are off screen the first time they are opened. Subsequent openings position them so the entire component fits on screen **  (check one with "x")
```
[] bug report => Create a simple custom filter and open it at edge of the screen then it's moving out of the screen.
[] feature request => Fix the position issue.
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Create a simple custom filter and open it at the edge of the screen and for the first time it's moving right side of the screen instead of left side of the screen.
- Second time it's opening to right of the screen. 
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

https://plnkr.co/edit/paL91WJaP99nuwSrLckl?p=preview

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. It should auto fit to screen.

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **ag-Grid version:** 22.1.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
![image](https://user-images.githubusercontent.com/16205943/74210237-dc2b4600-4cb0-11ea-9882-22359012eeda.png)

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-3857

Custom Filter Component + React: Filter Component renders incorrectly when opened for the first time in the last column
