### ISSUE TITLE
ag-grid-enteprise with noImplicitAny: Could not find a declaration file for module 

### ISSUE THREAD

**Issue by Liero** [ag-grid/ag-grid#3661]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Description**

When noImplicitAny is enabled in tsconfig:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```
typescript compiler throws error:

> Could not find a declaration file for module './dist/ag-grid-enterprise.cjs.js'. 'C:/Projects/Liero/ag-grid-noimplicitany/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js' implicitly has an 'any' type.
> 
> 4 export { LicenseManager } from "./dist/ag-grid-enterprise.cjs.js";

**Customers of ag-Grid**

I don't know what the channel is, I'm a developer and I don't know who purchased the license from me

**Providing a Reproducible Scenario**

Download this project https://stackblitz.com/edit/ag-grid-autocolumn-formatting
and run:
```
npm install
npm run build
```

**Current behavior**
```
> tsc

node_modules/ag-grid-enterprise/main.d.ts:4:32 - error TS7016: Could not find a declaration file for module './dist/ag-grid-enterprise.cjs.js'. 'C:/Projects/Liero/ag-grid-noimplicitany/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js' implicitly has an 'any' type.

4 export { LicenseManager } from "./dist/ag-grid-enterprise.cjs.js";
```

**Please tell us about your environment:**

* **ag-Grid version:**  "22.1.1"
* **Language:** TypeScript

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3714 Add types ag-grid-enterprise
