### ISSUE TITLE
tool panel performance issue in IE 11

### ISSUE THREAD

**Issue by WinfredMa** [ag-grid/ag-grid#3665]
**I'm submitting a bug report**  (check one with "x")
```
[x] bug report => see 'http://plnkr.co/edit/BjcMcWcUCBLUGnXWuKoP?p=preview'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
It blocks page rendering for several seconds. Please refer to: http://plnkr.co/edit/BjcMcWcUCBLUGnXWuKoP?p=preview

**Expected behavior**
Tool panel has a better performance and is not a bottle neck in IE 11. 
Please optimize tool panel, are following solution feasible?
1. only render columns which in current window view. 
2. delay render columns unless sidebar is opened. 

**environment**
Operating system: Windows 10

**ag-Grid version** 
22.1.1

**Browser:**
IE 11

**Language**
[ES6/7 | ES5]

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue: 
AG-3877 Sidebar with many columns slows down the grids initialisation time in IE

**Comment by WinfredMa** [comment]
@LouisMoore-agGrid Thanks a lot.
