### ISSUE TITLE
Full width row and Tree data feature

### ISSUE THREAD

**Issue by AnandarajT** [ag-grid/ag-grid#3681]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Plunker Demo link**: https://plnkr.co/edit/IIri9gOdLQ3W75iGDXBr?p=preview

**Providing a Reproducible Scenario**
1. Open the plunker link and see the output

The group column disappears so not able to expand/collapse the child items

**Current behaviour**
The expand/collapsing of parent items not available. 

**Expected behaviour**
The parent row content should appear along with expand/collapse icons

**Please tell us about your environment:**
Windows 10 OS, Visual Studio Code IDE, Google Chrome browser

* **ag-Grid version:**  22.1.1

* **Browser:** All

* **Language:** All

I am very much satisfied with AG-Grid and its feature. This small bug is not allowing me to work on one of our most wanted feature. It would be very helpful if you guys help me out in solving this

Please let me know if you need more details

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. This has been raised before, and we are currently tracking already in our pipeline with the following number and description.

AG-3242

Allow Tree Data to be compatible with full width group rows / master/detail


Note that we don't have a timeline for this at the moment.

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

Regards

Ahmed‍

**Comment by MykolaGolubyev** [comment]
Hello, is there a way to vote for this issue?
