### ISSUE TITLE
SearchOoo does not translate

### ISSUE THREAD

**Issue by EvgeniyKonstantinov** [ag-grid/ag-grid#3687]
LocaleText -> searchOoo not translate.
https://www.ag-grid.com/javascript-grid-internationalisation/
in example we have variable searchOoo and translate 'daSearch...'

![image](https://user-images.githubusercontent.com/30512287/75222191-af008c80-57b4-11ea-9ede-0b06bced438a.png)

**Comment by gportela85** [comment]
This has been fixed in the latest branch. Thanks for reporting it.
