### ISSUE TITLE
Tooltip not showing when using groupUseEntireRow

### ISSUE THREAD

**Issue by djordjes** [ag-grid/ag-grid#3691]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**
When using groupUseEntireRow, tooltip is not showing on group rows. If I set groupUseEntireRow to false, then tooltip is shown, and it works as expected.
Plunker Url to check:
https://next.plnkr.co/edit/cBvdtBs2I5xQTHYv?preview

**Expected behavior**
Tooltip should be displayed on rows.

* **ag-Grid version:** X.X.X
22.1.1
* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
﻿
* **Language:** [all]

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3902: allow using tooltips with group nodes when using groupUseEntireRow

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

Regards

Ahmed‍
