### ISSUE TITLE
customPinnedRowRender styling not working in Javascript (functional with Angular & Vue)

### ISSUE THREAD

**Issue by mcarroll316** [ag-grid/ag-grid#3694]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
I've been attempting to create the similar functionality (format pinned rows differently than rest of grid) in my project as described on the following page (ie. blue for one cell, italics on another, etc):

https://www.ag-grid.com/javascript-grid-row-pinning/

This has been unsuccesful - come to find out, the behavior on the page (in link above) isn't working for Javascript, which may explain why my efforts have also been futile; their site does render the styles correctly for Angular & Vue.

Seems something is missing from the JS framework.

**Comment by seanlandsman** [comment]
Thanks for reporting this - I'll get our example fixed in our next release

For now I've modified the JS example here to show you a working example: https://next.plnkr.co/edit/kvMZQ0RQG3MvBKns
