### ISSUE TITLE
How to get ag-grid-angular working with @ag-grid-enterprise/all-modules?

### ISSUE THREAD

**Issue by demiro** [ag-grid/ag-grid#3696]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

So, we are updating ag-grid-enterprise to @ag-grid-enterprise/all-modules";
how to use ag-grid-angular with this version?

when I try to use it I am asked by the community version, and the components by the ag-grid-enterprise even though I have @ag-grid-enterprise

**Comment by seanlandsman** [comment]
Hi - there are two types of published artefacts: packages & modules

packages have the `ag-grid-xxx` prefix and modules have the `@ag-grid-xxx` prefix

So if you're using modules you need to use `@ag-grid-community/angular` module

https://www.ag-grid.com/javascript-grid-packages/

thanks
