### ISSUE TITLE
External filtering grid with server side row model

### ISSUE THREAD

**Issue by adnetv** [ag-grid/ag-grid#3700]
**I'm submitting a ...**  
```
[x] bug report
```

**Current behavior**
OnFilterChanged and IsExternalFilterPresent are both being triggered, but doesExternalFilterPass does not. I tried playing around with binding the functions and even forcing a trigger. Also tried getting the IsExternalFilterPresent to always return true, it still doesn't work. The main difference from the documentation example and my project is that I'm using server side data. If it is not supposed to work, maybe you guys need to update the documentation, in nowhere does it state that it's only client side (unlike Quick Filter which is clearly specified).

**Info about project/environment:**
* React/node app
* Mac-OS, Visual Studio Code, yarn

* **ag-Grid version:** 22.0.0

* **Language:** [Javascript]

**Comment by AhmedAGadir** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by adnetv** [comment]
@AhmedAGadir Why would you close the issue? You haven't even answered any of my questions. If you've just read what I wrote, it's the same example plunker from the documentation, the external filter of the ages, but I'm not using client side row model.

**Comment by acgrama** [comment]
Expanding on the Plunker from https://www.ag-grid.com/javascript-grid-server-side-model-infinite/, where we have a serverSide grid, I have created this fork: https://plnkr.co/edit/izIveNmQW5OiaRX8BmIj?p=preview

I have added in the gridOptions:

`        [isExternalFilterPresent]="isExternalFilterPresent"
        [doesExternalFilterPass]="doesExternalFilterPass"      `

These functions are defined as 
```
  isExternalFilterPresent() {
    return true;
  }

  doesExternalFilterPass(node) {
    return false;
  }
```

And yet all rows in the grid are shown.

**Comment by adnetv** [comment]
@acgrama I saw someone mentioning on stackoverflow saving the callback for isExternalFilter present to update it with the filter change. But I'm not really sure how to do this. !

**Comment by arunsimon2007** [comment]
@adnetv , @acgrama any of you were able to fix this issue ? am struck with the same problem

**Comment by acgrama** [comment]
@arunsimon2007 Sorry, we didn't - if I recall correctly, we just changed our concept and did not pursue this path anymore.

**Comment by kiril-matev** [comment]
Hi all,

You're describing a case where ag-grid is used with the server-side row model, which means that data is loaded in pages as is needed. The server-side row model is used for large data sources (more than 30,000 rows) to allow for quick loading times and a smaller memory footprint on the client. However, when using the server-side row model the grid doesn't have all the data - the server has it. This is why when using the server-side row model a number of data operations need to be performed on the server - sorting/grouping/filtering/etc. 

This is why when the user is filtering, filtering the data needs to be done on the server as only the server has all the data and can return rows which match the filter condition which may not have been loaded by the client yet. This is why filtering when using the ag-grid server-side row model is performed remotely and cannot be performed locally using a call to doesExternalFilterPass().

@adnetv: You're correct - we should clarify on the external filtering page that this works only for client-side row model for the reason I described above.

However, if you're using the external filtering functionality as a way to set the filter condition using UI external to ag-Grid itself, you can easily implement that when using the server-side row model as follows. When the user is using your external filtering UI, build a FilterModel object to reflect the filtering conditions and then fire the OnFilterChanged event, thus causing ag-Grid to send a data request with the filter model in the parameters. Your dataset will then get filtered on the server and the appropriate rows will be returned and displayed in the grid.

I've implemented the approach here:
https://plnkr.co/edit/adJDDFY7RqAZ1gA9

In this plunker you have an ag-grid using the server-side row model, and two buttons above it, setting filtering conditions for age>30 or age<30. After you click any of the buttons, a filter model with a corresponding filter condition is created, and the onFilterChanged event is fired. This causes the grid to send a request to the server with the filtering condition and gets the filtered data back.

You can see the full information on how to get/set filter models here:
https://www.ag-grid.com/javascript-grid-filter-api/#get-set-all-filter-models

**Comment by acgrama** [comment]
@kiril-matev Thank you for the detailed answer! 
@arunsimon2007 This is pretty much what we ended up implementing back then.

**Comment by idanhaviv** [comment]
hey @kiril-matev,

what about implementing this behaviour on the infinite row model?
is it the same as the solution you suggested to the server row model?

**Comment by kiril-matev** [comment]
Hi @idanhaviv,

Yes - the approach to implement this is the same when you're using the AG Grid infinite row model.

See this implemented here:
https://plnkr.co/edit/p6TuDVouypuBMYXI

**Comment by idanhaviv** [comment]
@kiril-matev thanks!

I'm having this issue even on client side row model, i found a bug with the External Filter on React:

my grid options: 
`const gridOptions = {
    isExternalFilterPresent: () => true,
    doesExternalFilterPass: (node: RowNode) => {
      console.log('factorTypeFilters in doesExternalFilterPass: ', factorTypeFilters);
      return true
    },
  };`

my doesExternalFilterPass depends on a prop 'factorTypeFilters'.

I update the grid api on filter change when that prop changes:
`useEffect(() => {
    gridApi?.onFilterChanged()
  }, [factorTypeFilters])`

nevertheless, after updating factorTypeFilters prop, it's value inside the component has changed but not in  doesExternalFilterPass function

**Comment by pallavi-zemoso** [comment]
> @kiril-matev thanks!
> 
> I'm having this issue even on client side row model, i found a bug with the External Filter on React:
> 
> my grid options:
> `const gridOptions = { isExternalFilterPresent: () => true, doesExternalFilterPass: (node: RowNode) => { console.log('factorTypeFilters in doesExternalFilterPass: ', factorTypeFilters); return true }, };`
> 
> my doesExternalFilterPass depends on a prop 'factorTypeFilters'.
> 
> I update the grid api on filter change when that prop changes:
> `useEffect(() => { gridApi?.onFilterChanged() }, [factorTypeFilters])`
> 
> nevertheless, after updating factorTypeFilters prop, it's value inside the component has changed but not in doesExternalFilterPass function

@idanhaviv.....I am also facing the same issue. Any luck with the issue? Thanks in advance

**Comment by kiril-matev** [comment]
@idanhaviv , @pallavi-zemoso 

This issue was originally opened for external filtering AG Grid when using the server-side row model. 

In order to make it easier for us to track issues and for other users to find this issue. please submit a new GitHub issue about this potential bug. 

Please as part of this submission include a plunker sample, a list of steps to reproduce, and a description of the expected/actual behavior.

We're keen to investigate this further.
