### ISSUE TITLE
Properties not updating in noRowsOverlayComponentFramework

### ISSUE THREAD

**Issue by Paul6552** [ag-grid/ag-grid#3704]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
I have the following code:
```
<div
	className="ag-theme-balham"
	style={{
		height: '74vh',
		width: '100%',
	}}
>
	<AgGridReact
		rowHeight={50}
		columnDefs={columns}
		rowData={props.tabledata}
		noRowsOverlayComponentFramework={CustomOverlay}
		// @ts-ignore
		noRowsOverlayComponentParams={{
			printOut: props.printOut
		}}
		onGridReady={onGridReadyTaenze}>
	</AgGridReact>
```
My custom overlay:
```
import React from 'react';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-balham.css';

interface Props {
    printOut: string;
}

const CustomOverlay: React.FC<Props> = (props) => {

    return (
        <>
            <div className="ag-overlay-loading-center" style={{backgroundColor: 'lightcoral', height: '9%'}}>
                <i className="far fa-frown"> {props.printOut}</i>
            </div>
        </>
    );
};

export default CustomOverlay;
```

**Current behavior**
Several problems:
1. Typescript is complaining that "`noRowsOverlayComponentParams`" is missing. In every example I have found (for example here [Custom overlay](https://www.ag-grid.com/javascript-grid-overlay-component/#example-custom-overlay-components)) I have the property "`noRowsOverlayComponentParams`".

Workaround: If I disable Typescript with //ts-ignore it is working.

2. If the property props.printOut is changing, the customOverlay does not update. After ag-grid is loaded, it isn`t possible to update the componentParams anymore.

Sadly, I could not get the plunker to work:
[Plunker not working example](https://plnkr.co/edit/CCLRDVguFcSHrlxDmN0o?p=preview)

**Expected behavior**
The custom overlay should change if the value changes in the "`noRowsOverlayComponentParams`"

**Please tell us about your environment:**
react: 16.12.0
ag-grid: 22.1.1
Typescript: 3.7.4
Chrome latest version

**Comment by icedjello** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Since it is impossible to use in this case any web based tool to provide with a reproducible scenario, I would suggest that you send us whatever is that you can so you can investigate further. Some suggestions are:

- github

- zip files

- code fragments

**Comment by Paul6552** [comment]
In the meantime I could fix the problem by myself. 

The table does not update the params by itself. After the property "printOut" has changed, you have to call "api.showNoRowsOverlay()" again, to publish the new information

**Comment by shrutisinha** [comment]
Was able to reproduce similar scenario in one of the example codes..
In place of date, a random number will be shown in No Rows overlay.
From console outputs, we can see that the random number being shown in overlay text is the last updated number (and not the latest one)

code link: [https://plnkr.co/edit/tgCbkgORVpsMIUs8](https://plnkr.co/edit/tgCbkgORVpsMIUs8)

console logs:
In aggrid 0
In noRowsOverlay:  0
In aggrid 0.14963732911534322
In noRowsOverlay:  0
In aggrid 0.4734200682078593
In noRowsOverlay:  0.14963732911534322
