### ISSUE TITLE
Custom tooltip doesn't disappear on mouse out

### ISSUE THREAD

**Issue by shlau** [ag-grid/ag-grid#3706]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**

In Athlete Col 2, hover over Natalie Coughlin. As soon as the tooltip appears quickly hover over Aleksey Nemov. Hover over Natalie Coughlin as soon as the tooltip appears for Aleksey Nemov. Repeat this alternating a few times (about 20-30 times). Notice that after a while of alternating the tooltip remains stuck on the grid and does not disappear.
https://plnkr.co/edit/BVlmGSpHUBkMNhW8FONL?p=preview

**Expected behavior**

The custom tooltip should disappear on mouse out.
**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

22.1.1
* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
* **Language:** [all]

**Comment by icedjello** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-3917-Custom Tooltip doesn't disappear on mouse out

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by MarceloFonseca** [comment]
Hello,

Where can I find the status of AG-3917? Nothing can be found in the pipeline if we filter by the issue Key.

Thanks!

**Comment by gportela85** [comment]
@MarceloFonseca Usually when you can't see a ticket in the pipeline check https://www.ag-grid.com/ag-grid-changelog/
