### ISSUE TITLE
ResizeObserver callback runs outside of the angular zone

### ISSUE THREAD

**Issue by ChristianKohler** [ag-grid/ag-grid#3709]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**

It's really hard to reproduce. I couldn't put it in a plunker or stackblitz and make it reproducible. Sometimes it works, sometimes not.

**Current behavior**
Cell component agInit runs outside of the angular zone

**Expected behavior**
Cell component agInit runs inside the angular zone

**What I found out**
1. I noticed that if it is outside the zone its called by Utils.debounce (stacktrace: https://www.diffchecker.com/e54rZEsC)
2. Then i check where ag grid calls it. In around 6 places. One of them was in a ResizeObserver callback
3. Angular zone monkeypatches setTimeout, but not ResizeObserver
4. I could toggle between ResizeObserver and a polyfill (which relies on setTimeout) by using suppressBrowserResizeObserverin the gridSettings
5. I wrote an automation to refresh the browser in an endless loop and stop when the error happens
6. I could always with max 10 refresh reproduce the error with ResizeObserver enabled
7. I could never reproduce the error using the polyfill

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
"ag-grid-angular": "^22.1.1",
 "ag-grid-community": "^22.1.1",

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"

* **Language:** 
TypeScript ~3.5.3, Angular 8

* **Additional resources**
I've opened a stackoverflow issue while figuring out the bug: https://stackoverflow.com/questions/60523260/aggrid-cell-component-aginit-runs-sometimes-outside-of-the-zone/60532058#60532058

**Comment by ChristianKohler** [comment]
Related bug: https://github.com/ag-grid/ag-grid/issues/3130

**Comment by ChristianKohler** [comment]
I don't think ag grid should fix it. But what would be nice is to use to document it that Angular users should import `zone-patch-resize-observer`.

**Comment by icedjello** [comment]
Hi,

We cannot engage with this ticket until we get a solid and reliable reproducible scenario. 

Since it is impossible to use in this case any web based tool to provide with a reproducible scenario, I would suggest that you send us whatever is that you can so you can investigate further. Some suggestions are:

- github
- zip files
- code fragments

We will keep an eye on this ticket until a repro has been provided. Until then, we can't proceed any further here.

**Comment by seanlandsman** [comment]
@ChristianKohler thanks for raising this - I'll investigate and update our docs if necessary

thanks

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-3972

ResizeObserver callback runs outside of the angular zone
