### ISSUE TITLE
Ag-grid Quick Filter to allow some actions like. I want functionality where i want to filter data which doenot match criteria

### ISSUE THREAD

**Issue by sumanthitha** [ag-grid/ag-grid#3710]
Here is plunker for that. https://plnkr.co/edit/NaDAQYvXoo2P6vxdvPVB?p=preview

Quick Filter is only supporting contains. Is there a quick way to do such Not Contains and startswith or endswith based on user value entered like !ab/ab*,*ab etc

html

<!DOCTYPE html>
<html lang="en">
<head>
<script> var __basePath = ''; </script>
<style> html, body { margin: 0; padding: 0; height: 100%; } </style>
    <script src="https://unpkg.com/ag-grid@17.0.0/dist/ag-grid.min.js"></script></head>
<body>

<div style="height: 100%; padding-top: 35px; box-sizing: border-box;">
    <div id="myGrid" style="height: 100%;" class="ag-theme-balham"></div>
</div>
<div style="position: absolute; padding-top: 4px; top: 0px; left: 0px;">
    <input type="text" id="filter-text-box" placeholder="Filter..." oninput="onFilterTextBoxChanged()"/>
    <button style="margin-left: 20px;" onclick="onPrintQuickFilterTexts()">Print Quick Filter Texts</button>
    <span style="margin-left: 50px">
        <label>
            <input type="radio" onchange="onQuickFilterTypeChanged()" id="cbNormal" checked name="cache" />
            Normal Quick Filter
        </label>
        <label>
            <input type="radio" onchange="onQuickFilterTypeChanged()" id="cbCache" name="cache"/>
            Cache Quick Filter
        </label>
    </span>
</div>

    <script src="main.js"></script>
</body>
</html>```

JS
gridOptions.api.setQuickFilter(document.getElementById('filter-text-box').value);

[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Supports only contains logic 

**Expected behavior**
Should be supporting not contains and starts with for custom filter

**Please tell us about your environment:**
<!-- Operating system, IDE, package manager, HTTP server, ... -->

* **ag-Grid version:** 21.1.1
<!-- Check whether this is still an issue in the most recent ag-Grid version -->

* **Browser:**
Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by icedjello** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
