### ISSUE TITLE
Fill Handle Brokes if value of string starts with number

### ISSUE THREAD

**Issue by mohammadhamrah** [ag-grid/ag-grid#3718]
I'm submitting a ... (check one with "x")

[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

See this demo:
https://www.ag-grid.com/javascript-grid-range-selection-fill-handle/#example-custom-fill-operation

try to edit first country to "1test", then try to fill down the cells using the fill handle

Current behavior
`NaN` value are copied to the filled cells.

Expected behavior
the current cell value should be copied to the filled cells.

Browser:
Chrome,

Language: [all]

Suggestion:
It seems, ag-grid incorrectly detect the cell value is number ( because of first character ) and tries to parse it  in order to increment it.

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-3865  FillHandler doesn't handle strings which start with a number.
