### ISSUE TITLE
 EDGE browser Full Row Editing cell clicking disables / enables editing while caret are blinking

### ISSUE THREAD

**Issue by 192kb** [ag-grid/ag-grid#3720]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1) Load in EDGE browser ag-grid example for full row editing https://www.ag-grid.com/javascript-grid-cell-editing/#fullRowEdit
2) Dbl-click editable text/number cell => Selected text appears and editable
2) Click to reset selection => Caret appears and NOT editable
3) Click again same cell => Now editable
3a) Click again same cell => Now not editable

https://192kb.ru/uploads/597da4db11656a13b74d8ec9f7c6d56a.gif

**Current behavior**
Clicking editable cell in full row edit mode is broken for EDGE browser as its presents in 2 modes visually looking same, but not allowing editing in half of cases. 

**Expected behavior**
Editing should not depend on count of clicks and should not switch modes.

**Please tell us about your environment:**
Windows 10

* **ag-Grid version:** 
ag-grid-enterprise v21.2.2 and older including 22.1.2

* **Browser:**
**Important!** MS Edge browser

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763

* **Language:** all

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-3968 Clicking on an editor disables editing in Edge browser

**Comment by 192kb** [comment]
@davis4acca 
Thank you for the information, while my office is contacting yours, can you approximately estimate the window when the bug is fixed and release happens? What can I answer my boss?
