### ISSUE TITLE
BUG : Clipboard toggle off not working

### ISSUE THREAD

**Issue by uguryilmaz** [ag-grid/ag-grid#3721]
we are using the last versiyon of ag-grid-enterprise (v22.1.1). the clipboard feature is working as expeted but we can not toggle it off. it is not working even in you plunker example.

her it is your clipboard example page : 
https://www.ag-grid.com/javascript-grid-clipboard/#clipboard-example

to see the issue : 
1) select a text from anywhere with (Ctrl & C)
2) paste it to a cell, value change as expected
3) Hit toggle Paste Off button
4) paste it to another cell. Value of the cell changed. this is not expected. 

we can paste data to a cell even if we toggle off the paste feature.

ag-grid versiyon : v22.1.1
browser : Chrome
Language : angular

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3755  It is possible to paste into non-editable cells when 'suppressClipboardPaste=true'


Note that this is part of our next release.
