### ISSUE TITLE
Getting "api.setDataSource is not a function" error message.

### ISSUE THREAD

**Issue by javierxbrenes1** [ag-grid/ag-grid#3726]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
I am following this documentation: https://www.ag-grid.com/javascript-grid-infinite-scrolling/ on my Vue application, but I am getting this error: `params.api.setDataSource is not a function`  when I try to set my dataSource.
My function looks like: 
`onReady(params) {
      const dataSource = {
        rowCount: null,
        getRows: getParams => {
          const newData = this.createDemoData(getParams.startRow, getParams.endRow);
          getParams.successCallback(newData, getParams.endRow + 100);
        }
      };
      params.api.setDataSource(dataSource);
    }`

If I log the params.api, this is what I get:

`{type: "gridReady", api: GridApi, columnApi: ColumnApi}
type: "gridReady"
api: GridApi
detailGridInfoMap: (...)
immutableService: (...)
csvCreator: (...)
excelCreator: (...)
rowRenderer: (...)
filterManager: (...)
columnController: (...)
selectionController: (...)
gridOptionsWrapper: (...)
valueService: (...)
alignedGridsService: (...)
eventService: (...)
pinnedRowModel: (...)
context: (...)
rowModel: (...)
sortController: (...)
paginationProxy: (...)
focusController: (...)
rangeController: (...)
clipboardService: (...)
aggFuncService: (...)
menuFactory: (...)
contextMenuFactory: (...)
cellRendererFactory: (...)
valueCache: (...)
animationFrameService: (...)
statusBarService: (...)
chartService: (...)
undoRedoService: (...)
infiniteRowModel: (...)
headerRootComp: (...)
gridPanel: (...)
gridCore: (...)`

setDataSource is not part of the API object.

**Expected behavior**
be able to set my data source.

**Please tell us about your environment:**

Operating system: Windows 10 64bits.
IDE: VsCode
package manager: npm
VueJs, .netCore

* **ag-Grid version:** X.X.X

@ag-grid-community/all-modules= ^23.0.0
@ag-grid-community/vue= ^23.0.0

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
[all | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
The method is `setDatasource` - you can find our API documented [here](http://www.ag-grid.com/javascript-grid-api/#data)
