### ISSUE TITLE
Unable to use "Group Cell Renderer"

### ISSUE THREAD

**Issue by andysim88** [ag-grid/ag-grid#3728]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

I am unable to make use of "Group Cell Renderer". It is not stated that is an enterprise feature. 
![Ag-Grid_GroupCellRenderer](https://user-images.githubusercontent.com/10025445/77066523-4a84c600-6a1e-11ea-87ee-2335c668d668.PNG)

**Comment by JosNun** [comment]
The grouping feature as a whole requires enterprise ([See here])(https://www.ag-grid.com/javascript-grid-grouping/). Since grouping requires enterprise, there's no way to get grouped cells.
