### ISSUE TITLE
ag-grid webside

### ISSUE THREAD

**Issue by msarav** [ag-grid/ag-grid#3730]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**

Description:

-- Go to the page: https://www.ag-grid.com/javascript-grid-sorting/
-- Click on "Code" under Example: Custom-Sorting
-- It keeps showing "Loading" and doesn't open the code at all

![Annotation 2020-03-19 171353](https://user-images.githubusercontent.com/14319713/77115684-22d53400-6a05-11ea-994e-2ffe59089722.png)

**Current behavior**

-- URL not working ( "https://www.ag-grid.com/javascript-grid-sorting/custom-sorting/_gen/angular/app/app.component.ts")

-- Not able to view example code/plunker

**Expected behavior**

-- should be able to view example code/plunker

**Please tell us about your environment:** Windows 10, VS Code

* **ag-Grid version:** 22.1.1

* **Browser:** Google Chrome

* **Language:** [all]

**Comment by seanlandsman** [comment]
Can you please try force refresh your browser - this is what that example should look like 

![Screenshot 2020-03-20 at 07 23 12](https://user-images.githubusercontent.com/1329081/77143652-b9dcd300-6a7b-11ea-9d1b-6654c18986f8.png)
