### ISSUE TITLE
Filter bug - "AND" and "OR" both selected

### ISSUE THREAD

**Issue by majugurci** [ag-grid/ag-grid#3732]
Hi,

in current version (23.0.0) there is a bug when you switch filter from AND to OR. Both options are then selected. It is visible in your showcase also.
Bug is manifested in column header filter popup as well as in side bar filter panel.

![image](https://user-images.githubusercontent.com/481077/77156271-59f82380-6a9f-11ea-8a15-c7554726eb61.png)

![image](https://user-images.githubusercontent.com/481077/77156337-801dc380-6a9f-11ea-8a5f-708d494a8b9d.png)

**Comment by alowdon** [comment]
Hi @majugurci, many thanks for letting us know about this. We are working on a fix (AG-3994) and hope to release a patch next week.

**Comment by rmc-software** [comment]
Thanks for raising this with us. This has now been fixed in our latest patch v23.0.2.
