### ISSUE TITLE
add new info to BodyScrollEvent

### ISSUE THREAD

**Issue by bboydflo** [ag-grid/ag-grid#3733]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

Current behaviour.
`bodyScroll` event listener's first argument is of type `BodyScrollEvent` and has a key called `direction` on it which I think it can be either `vertical` or `horizontal`. I think it's not enough info and I would like to suggest at least one new key to describe if the user scrolled up, down, left or right.

**Expected behavior**
`BodyScrollEvent` has a key called `scrollDirection` on it which can be either up, down, left or right.

**Comment by shuheb** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
