### ISSUE TITLE
problem style of drop down  in  chart  setting menu when chart with chart Container

### ISSUE THREAD

**Issue by mahdiporkar** [ag-grid/ag-grid#3739]
I'm having trouble displaying the drop down button in  chart setting  menu  when chart option with chart container but chart in popup mode working well .
![image](https://user-images.githubusercontent.com/17072984/77424966-9acda080-6def-11ea-914d-f7504938995f.png)

[https://plnkr.co/edit/fHjWNZKXwhFeWR5n](url)
thanks a lot

**Comment by rmc-software** [comment]
Hi - thanks for raising this. You will need to set the `popupParent: document.body `

As shown in this plunker:

http://plnkr.co/edit/aT6ybw0vcIP7Wb3t

We will update our docs and examples accordingly.

**Comment by mahdiporkar** [comment]
thanks a lot , but when parent container display flex and height fixed not good show , actually
when drop down opened because page scrolling,this problem not appear in previous version

**Comment by rmc-software** [comment]
Ok thanks - we've created 'AG-4011 - agSelect scrolls the page when expanded' to track this issue

**Comment by mahdiporkar** [comment]
i solving this problem by this way 
gridOptions.api.setPopupParent(  $(params.chartContainer).parent()[0]);
but with popupParent: document.body,the page has  scroll
