### ISSUE TITLE
need re Draw chart after changing chart type in setting menu 

### ISSUE THREAD

**Issue by mahdiporkar** [ag-grid/ag-grid#3740]
I'm having trouble displaying the chart when the chart type is changed in the settings,  actually   when the menu is closed, we can see that the graph is displayed without any expand .this problem not appear in pop up mode
![giftaggrid](https://user-images.githubusercontent.com/17072984/77516219-9d83d080-6e97-11ea-8b19-cbc31e9f841d.gif)

https://plnkr.co/edit/B1v7T2vmzUpkiLvq?preview

**Comment by rmc-software** [comment]
Thanks for raising this with us. We have created an internal jira to track this: AG-4016.

See our pipeline for progress updates.

https://www.ag-grid.com/ag-grid-pipeline/

A fix is scheduled for our next release v23.1 due in 4/5 weeks.
