### ISSUE TITLE
problem style Input range with  firefox browser

### ISSUE THREAD

**Issue by mahdiporkar** [ag-grid/ag-grid#3742]
style of input range in setting chart has problem with firefox browser

![image](https://user-images.githubusercontent.com/17072984/77524537-1e959480-6ea5-11ea-81bc-7504bf8e1bdc.png)

**Comment by mahdiporkar** [comment]
i solved by this way
.ag-theme-balham input[type="range"] {
    -webkit-appearance: none;
    **-moz-appearance: scale-horizontal;**
}

**Comment by rmc-software** [comment]
Thanks for raising this with us. We have created an internal jira to track this: AG-4019.

See our pipeline for progress updates.

https://www.ag-grid.com/ag-grid-pipeline/

A fix is scheduled for our next release v23.1 due in 4/5 weeks.
