### ISSUE TITLE
Small omission in the "customize the theme look" portion of docs prevents finishing that section if following along

### ISSUE THREAD

**Issue by goepi** [ag-grid/ag-grid#3744]
I'm reporting a small issue in the docs that prevented me from following the React Get Started section to the end.

In the final section, [customize the theme look](ag-grid.com/react-grid/), to get it to work you also need to change the `className` in the `div` that is wrapping the `AgGridReact`. That className up to that point in the docs was `ag-theme-balham`, but needs to be changed in this section to `ag-theme-alpine`.

In which repository are the docs actually? Would it be possible for me to submit a PR to fix that part of the docs?

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-4045 - Docs: Tell users to change the className when customising the theme in Getting Started pages

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
