### ISSUE TITLE
Error of  Uncaught TypeError: Object prototype may only be an Object or null: undefined when import ag-grid-enterprise

### ISSUE THREAD

**Issue by lmayai** [ag-grid/ag-grid#3745]
[X] bug report => see 'Providing a Reproducible Scenario'
|
**Providing a Reproducible Scenario**
I'm trying to use the enterprise-mode of ag-grid in an angular project

I installed the packege with 
`npm install --save ag-grid-enterprise`

Later I imported in app.module.ts this:
`import 'ag-grid-enterprise';`

**Current behavior**
The program compile correctly, but in the inspector of the browser I get this:

ag-grid-enterprise.cjs.js:31132 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at extendStatics (ag-grid-enterprise.cjs.js:31132)
    at push../node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js.__extends$1_ (ag-grid-enterprise.cjs.js:31135)
    at ag-grid-enterprise.cjs.js:31147
    at Object../node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js (ag-grid-enterprise.cjs.js:31462)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/app.module.ts (app.init.service.ts:8)
    at __webpack_require__ (bootstrap:83)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:83)

**Expected behavior**
It must show the lack of license based on getting Started page on angular. 

**Please tell us about your environment:**
Angular 8

* **ag-Grid version:** 
"ag-grid-angular": "^22.1.1",
    "ag-grid-community": "^22.1.1",
    "ag-grid-enterprise": "^23.0.2",

* **Browser:**
Chrome

**Comment by seanlandsman** [comment]
You need to ensure all versions of agGrid are the same - at the very least the major and minor versions

Try: 

"ag-grid-angular": "^23.0.2",
"ag-grid-community": "^23.0.2",
"ag-grid-enterprise": "^23.0.2",

**Comment by lmayai** [comment]
> You need to ensure all versions of agGrid are the same - at the very least the major and minor versions
> 
> Try:
> 
> "ag-grid-angular": "^23.0.2",
> "ag-grid-community": "^23.0.2",
> "ag-grid-enterprise": "^23.0.2",

It's true! Now it works! All versions need to be the same.

Thanks @seanlandsman !
