### ISSUE TITLE
setColumnsVisible "sometimes" not working [react]

### ISSUE THREAD

**Issue by Paul6552** [ag-grid/ag-grid#3753]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
columnApi.setColumnsVisible is not working.
Unfortunately I have not found out why it sometimes works and sometimes not.

Below is an example of where it doesn't work.
[Codesanbox example](https://codesandbox.io/s/react-functional-component-b5103)

**Please tell us about your environment:**
IntelliJ (latest), npm(latest), node(latest)

* **ag-Grid version:** 
ag-grid-community and ag-grid-react: 22.1.1

* **Browser:**
Chrome, Mozilla Firefox

* **Language:**
Typescript 3.7.4

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

You must invoke the test function (see index.js line 44). 
Changing `test` to `test()` fixes this issue.

Regards,

Ahmed

**Comment by Paul6552** [comment]
Although this fixed this example, I have situations where columns cannot set visible depending on "cellRendererParams". Sadly I can`t reproduce this on codesandbox, therefore you can close this issue. Maybe on another day I can provide an example. Thank you very much for your time
