### ISSUE TITLE
Click event is triggered on the host element after dragging the column (in custom column header)

### ISSUE THREAD

**Issue by enheit** [ag-grid/ag-grid#3754]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Step to reproduce:
1) Create custom column header component in Angular
2) Provide custom header component to the ag-grid colDef (e.g. `const colDef = { headerComponentFramework: CustomHeaderComponent }`)
3) Add click event listener to the host or to the div element inside CustomHeaderComponent
4) After dragging the column the `click` event is triggered

As you can see on the gif below, the click listener is attached to the host element of the custom header component (provided in `headerComponentFramework`). After dragging the column, the click event is triggered and therefore sorting is applied. The sorting should not be applied after dragging the column.

![columns](https://user-images.githubusercontent.com/8645216/77909194-9690ff80-7295-11ea-8a2c-c6ccfcf240a9.gif)

P.S. The issue is not reproducible on the previous versions (for example 22.1.1 everything works okay)

**Expected behavior**
The `click` event of the custom column header should not be triggered after releasing column during drag and drop.

**Please tell us about your environment:**

* **ag-Grid version:** 23.0.2
```
"@angular/core": "~9.0.2"
"@ag-grid-community/angular": "^23.0.2",
"@ag-grid-community/client-side-row-model": "^23.0.2",
"@ag-grid-enterprise/core": "^23.0.2",
"@ag-grid-enterprise/master-detail": "^23.0.2",
"@ag-grid-enterprise/menu": "^23.0.2",
```

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) app/0.8.0 Chrome/80.0.3987.141 Electron/8.1.1 Safari/537.36"

* **Language:** [TypeScript 3.7.5 | ES5]

**Comment by enheit** [comment]
I was able to fix this issue by replacing `click` event with `mouseup` in conjunction of `params.column.isMoving()`. When column has been dragged the `mouseup` event is triggered and `params.column.isMoving()` is `true` at the moment. 

I don't think this is a good solution for the issue, but it works.

Looking forward to your suggestions

**Comment by AhmedAGadir** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-4067: [Regression] Moving column with custom header sorts the column now

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
