### ISSUE TITLE
CellRendererFramework doesn't work in IE

### ISSUE THREAD

**Issue by alkorr37** [ag-grid/ag-grid#3763]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
[Plunker](https://plnkr.co/plunk/rZ669SNEJ97HxrK1)

**Current behavior**
Using cellRendererFramework(React) parameter from columnDefinition object https://www.ag-grid.com/javascript-grid-cell-rendering/ in IE produces doubled result.

**Expected behavior**
Should work in all browsers :)

**Please tell us about your environment:**
Win10

* **ag-Grid version:** 23.0.2
  **ag-grid-react version:** 23.0.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; rv:11.0) like Gecko

* **Language:** [all]

**Comment by icedjello** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog.

This is the reference and summary of the relevant issue:

AG-4020 - [React] Duplicate cell contents when using framework components in IE11

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by seanlandsman** [comment]
@alkorr37 23.0.3 of the react component has been released which fixes the above issue

thanks

**Comment by alkorr37** [comment]
[Plunker](https://plnkr.co/edit/rZ669SNEJ97HxrK1)
I think new problem continues this one. 
Quick description.. When user quickly toggles sort button - duplicate renderers stay visible
