### ISSUE TITLE
Range Selection with Mouse Drag doesn't work in a web component (Shadow Dom)

### ISSUE THREAD

**Issue by etcircle** [ag-grid/ag-grid#3766]
Hi Guys,

I have been evaluating whether an ag-Grid can be used in my work. It needs to work in shadow dom to be used for my scenario. Please find a simple example where it can be reproduced in the link below.

"Mouse Drag range selection" doesn't work. However, Crl + Click and Shift + Click seems to work.

http://jsfiddle.net/t1wjheak/

Regards,
Emiliyan

**Comment by niveditaisrani** [comment]
+1

**Comment by hdoublerz** [comment]
+1 lol
