### ISSUE TITLE
How to dynamically add a background color to a cell

### ISSUE THREAD

**Issue by BenchWidth** [ag-grid/ag-grid#3770]
I want to add background color to list cells dynamically

**Comment by TKul6** [comment]
What is the trigger to change the background dynamically?

Is this sufficient?
https://www.ag-grid.com/javascript-grid-cell-styles/

**Comment by TokyoPiglet** [comment]
Can I ask a related question? How can I animate (transition) the change in background-color, based on cellClassRules?

**Comment by chaitanya1248** [comment]
I've used `cell.column.colDef.cellStyle` to set styles dynamically but those get applied when cell loses focus. Is there a way to apply styles while cell is still being in focus and user is editing?

**Comment by Tanishka-Bansal** [comment]
@chaitanya1248 Did you get any answer or any alernative??

**Comment by sudofix** [comment]
Any update regarding this? i'm also trying to update styles dynamically while editing, especially other cells not the one being edited
