### ISSUE TITLE
Drag and drop column from column tool panel to grid

### ISSUE THREAD

**Issue by nunch** [ag-grid/ag-grid#3771]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Hello,

I just upgraded my version of ag grid enterprise.
I'm using angular 9 and the bug also exists on the demo of ag grid.
It used to work on the previous version (20.0.0).
I'm trying to drag and drop a column from the Column too panel to the grid using the drag handle but it doesn't seem to work.

Regards,
Yoann

**Comment by rmc-software** [comment]
Here's the grid option you're looking for: 

`allowDragFromColumnsToolPanel`: Allow reordering and pinning columns by dragging columns from the columns tool panel to the grid.Default: false
