### ISSUE TITLE
Angular HTTP examples broken - MyJson.com mocked APIs offline indefinitely. 

### ISSUE THREAD

**Issue by JamesKnippel** [ag-grid/ag-grid#3775]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Myjson.com has gone offline for the indefinite future - thus, all mocked API's for the Angular examples are dead and need to be replaced. 

[https://www.ag-grid.com/angular-grid/#fetch-remote-data](url)
[https://www.ag-grid.com/angular-grid/](url)

**Expected behavior**
I expect to receive my data from these endpoints:
'https://api.myjson.com/bins/15psn9'
'https://api.myjson.com/bins/ly7d1'

Following will not work in Angular or Browser: 
```
ngOnInit() {
     this.rowData = this.http.get('https://api.myjson.com/bins/15psn9');
      this.rowData = this.http.get('https://api.myjson.com/bins/ly7d1');
}
```

**Comment by seanlandsman** [comment]
Thanks for letting us know @JamesKnippel - I'll look at fixing this today

**Comment by JamesKnippel** [comment]
> Thanks for letting us know @JamesKnippel - I'll look at fixing this today

No problem!
I just saw the fix! 
Closing this.
