### ISSUE TITLE
Floating Filter Showing Null in Select Option

### ISSUE THREAD

**Issue by pertrai1** [ag-grid/ag-grid#3776]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**

When using the floating filters, if I type one or more characters into the floating filter, and then click on the filter icon, I see `null` in the 2nd select drop down. This is IE11 behavior. 

**Expected behavior**

I would not see `null`.

![filter-grid-null](https://user-images.githubusercontent.com/442374/79161368-65dabb00-7da9-11ea-9efa-2a811f47364e.png)

* **ag-Grid version:** X.X.X

23.0.2

* **Browser:**

IE11

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are now aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-4112

Regression: IE 11 - Floating Filter Text Filter shows 'null'
