### ISSUE TITLE
Multiple checkbox selection while pressing shift or ctrl key is taking more time

### ISSUE THREAD

**Issue by mmariyuva** [ag-grid/ag-grid#3778]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Select checkbox while pressing Shift or Ctrl keys for multiple selection
- Checkbox selection & getting the Selected count are taking more time 

**Facing this issue after ag grid upgrade to latest version (from 22.1.1 to 23.0.2)**. Previous version(ag-grid 22.1.1) checkbox selection is working while pressing Ctrl or Shift key.

**Stackblitz demo for both ag-grid versions**
**ag-grid 23.0.2** - https://stackblitz.com/edit/angular-aggrid-23-rowselection
**ag-grid 22.1.1** - https://stackblitz.com/edit/angular-aggrid-22-rowselection

**Current behavior**
While pressing Ctrl or Shift key, checkbox selection is taking more time

**Expected behavior**
Able to select checkbox, while pressing Ctrl or Shift keys

**Please tell us about your environment:**
IntelliJ (latest), npm(latest), node(latest)

**ag-Grid version:**
ag-grid-community: 23.0.2 + Angular 9

**Browser:**
Chrome 80

**Language:**
Typescript 3.8.3

**Comment by KirtiVishwakarmaUI** [comment]
Hi All,

I need urgent help on ag-grid. Find the details below


Following functionality should be there 
on entering the search text , it should group the table content and the respective checkboxes should be checked.

As I am new to ag-grid as well as Angular. I have less time to finish this.
Thanks in advance  
![filter-groupping](https://user-images.githubusercontent.com/11458967/79235783-af023c00-7e89-11ea-88ed-e0dde88a1529.png)

**Comment by davis4acca** [comment]
@mmariyuva 

Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
@mmariyuva

Hi,

After having a look at your examples, the multiple checkbox selection feature doesn't seem to have a performance issue on our end, please see the attached gif and images.
<img width="392" alt="Screenshot 2020-04-20 at 09 56 07" src="https://user-images.githubusercontent.com/56586582/79772035-836ad000-8327-11ea-84b3-bef067cef9d0.png">
<img width="395" alt="Screenshot 2020-04-20 at 09 55 49" src="https://user-images.githubusercontent.com/56586582/79772040-84036680-8327-11ea-99d0-31a625b1c1d9.png">
![checkbox regression investigation](https://user-images.githubusercontent.com/56586582/79772099-967da000-8327-11ea-897d-fcc681480708.gif)

This ticket is going to be flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

**Comment by mmariyuva** [comment]
Hi @LouisMoore-agGrid,

I think you just pressed shift & release while mouse click. The main issue is "While pressing Shift or Ctrl key, checkbox selection is taking more time". **The checkbox selection delay is related to the amount of time keyboard key pressed**. Mouse click event is waiting upto completion of keydown event in latest version.

Could you please do testing like this: **Press shift key(not released upto some time<5sec>) + mouse click** in both 23.0.2 & 22.1.1 version. Previous version (22.1.1) it is working very well.

Stackblitz demo for both ag-grid versions
ag-grid 23.0.2 - https://stackblitz.com/edit/angular-aggrid-23-rowselection
ag-grid 22.1.1 - https://stackblitz.com/edit/angular-aggrid-22-rowselection

Current behavior
While pressing Ctrl or Shift key, checkbox selection is taking more time

Expected behavior
Able to select checkbox, while pressing Ctrl or Shift keys

Please solve this issue.

**Comment by mmariyuva** [comment]
Hi @LouisMoore-agGrid,

This issue has not fixed, Could you please test as per this above comment https://github.com/ag-grid/ag-grid/issues/3778#issuecomment-616972011 and solve this issue.

**Comment by stefanomiccoli** [comment]
found the issue after updating form v22 to v24.
