### ISSUE TITLE
columnApi.resetColumnState breaks aggFunc configured as a function

### ISSUE THREAD

**Issue by a-ignatov-parc** [ag-grid/ag-grid#3784]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/Zb01RZtUAGSfAhsB?preview

**Current behavior**
If the custom `aggFunc` is configured as a function in `columnDefs`, the aggregation of values ​​stops working after clicking the Reset Grid button in the presented example, which uses `columnApi.resetColumnState`.

```js
const aggFunc = () => '123'

var columnDefs = [
  { 
    field: 'gold',
    rowGroup: true,
    aggFunc, // will not work after reset
  },
];

var gridOptions = {
  columnDefs: columnDefs,
};
```

However, if `aggFunc` is configured as `string`, the reset works as expected.

```js
const aggFunc = () => '123'

var columnDefs = [
  { 
    field: 'gold',
    rowGroup: true,
    aggFunc: 'aggFunc', // will work after reset
  },
];

var gridOptions = {
  columnDefs: columnDefs,
  aggFuncs: {
    aggFunc,
  }
};
```

**Expected behavior**
The custom `aggFunc` configured as functions should work correctly after using` columnApi.resetColumnState`.

**Please tell us about your environment:** doesn't matter

* **ag-Grid version:** 23.0.2

* **Browser:** all

* **Language:** all

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-4122 | Resetting column state does not work when colDef.aggFunc takes a Direct Function

Kind Regards,
Shuheb

**Comment by GutierrezSamuel** [comment]
Hello.
I have the same issue with no way to retrieve my own aggFunc after a resetColumnState callback.
Many thanks for your help.
Sam

**Comment by AG-Zoheil** [comment]
Hi,

This was solved in `29.3.0` via **AG-8141**. If you are still having issues on versions after this, please raise a new issue on GitHub and we'd be more than happy to look into it.

**Comment by GutierrezSamuel** [comment]
Hello ! 
I have still the same issue. I have updated dash-ag-grid today.
This is part of my code:
```
defaultColDef = {
    "marryChildren": True,
    "editable": True,
    "sortable": True,
    "resizable": True,
    "filter": True,
    "enableRowGroup": True,
    "suppressMovable": False,
    "cellRenderer": "agAnimateShowChangeCellRenderer",
    "headerTooltip": "To hide a column, drag it off the grid",
    "aggFunc": {"function": "countDistinctLeaves(params)"},
    "width": 10,
}
```
with: 
```
dagfuncs.countDistinctLeaves = function(params) {
  let distinctLeaves = new Set();

  params.values.forEach(value => {
    if (Array.isArray(value)) {
      const subDistinctLeaves = dagfuncs.countDistinctLeaves({ values: value });
      subDistinctLeaves.forEach(subValue => distinctLeaves.add(subValue));
    } else {
      distinctLeaves.add(value);
    }
  });

  return Array.from(distinctLeaves);
}
```
When I reset StateColumns, the aggFunc do not work anymore: 
```
@callback(
    Output("ag-grid", "resetColumnState"),
    Input("reset-btn", "n_clicks"),
    prevent_initial_call=True,
)
def reset_column_state(_):
    return True
```

Do you have an idea how to solve that ?

Many thanks for your help

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue from **more than three years ago**.

The grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil
