### ISSUE TITLE
Space key doesn't deselect the selected row

### ISSUE THREAD

**Issue by MehdiSaeedifar** [ag-grid/ag-grid#3792]
Space key selects the row, but wont deselect the selected row.

Please check [Row Selection page](https://www.ag-grid.com/javascript-grid-selection/) for reproduce this bug.

**Comment by MehdiSaeedifar** [comment]
This issue still exists in 23.1.0 version.

**Comment by gportela85** [comment]
For this to work you need `rowDeselection: true` - https://plnkr.co/edit/7XmN5FIy043C92vw
