### ISSUE TITLE
Column Moving Bug With Unbalanced Groups

### ISSUE THREAD

**Issue by rcbyrne** [ag-grid/ag-grid#3793]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/mOQ29C7xdR0JdwtP

**Current behavior**
The group labelled "DRAG ME" is wont move. Looking at the console for my local dev I see errors of ag-grid trying to insert this group into the wrong location, unsure exactly what is going on. This pattern of group & children seems to break the dragging in a consistent manner. 

If you close that group using the chevron then it can be moved.

**Expected behavior**
Group should be able to move like the others

**Please tell us about your environment:**

* **OS:** Windows
* **ag-Grid version:** 23.0.0
* **Browser:** Chrome 
* **Language:** Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-4184 [Column Groups] Column group can be dragged by not dropped between two columns
