### ISSUE TITLE
columnDefs: Why specifying the column definitions is required?

### ISSUE THREAD

**Issue by demiro** [ag-grid/ag-grid#3795]
Sure it is convenient and where AG Grid shines... but they should be
an option, where it would just get default properties from the data array

there is plenty of times I need to show the data table for reference, has 20+ columns... and just want to display what is there...

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog.

This is the reference and summary of the relevant issue:


AG-1214 | Allow automatically guessing column defs without needing to provide any configuration at all. Handy for simple grids
-- | --




You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
