### ISSUE TITLE
Themes: cell-horizontal-border

### ISSUE THREAD

**Issue by 1-0-1** [ag-grid/ag-grid#3798]
[X] bug report

**Customers of ag-Grid**
(I'm a licensed customer, but the license contact is somewhere in the corporate structure and I don't know the login for support/zendesk or even if one has been created.  I also don't see a way to create an account there.)

Current behaviour.
Setting cell-horizontal-border in theme params will affect the vertical borders.
There is no param for cell-vertical-border.

ag-grid-community\styles\ag-theme-base\sass\parts\_grid-borders.scss
.ag-cell {
    @include ag-theme-rtl(( **border-right**: ag-param(**cell-horizontal-border**) ));
    @include ag-theme-rtl(( border-right-width: 1px ));
}

Expected behavior
Setting cell-horizontal-border in theme params will not affect the vertical borders.
There should be a param for cell-vertical-border.

* **ag-Grid version:** X.X.X
ag-grid-angular: 23.0.3
ag-grid-community: 23.0.2
ag-grid-enterprise: 23.0.2

**Comment by makinggoodsoftware** [comment]
Hi,

I would suggest emailing info@ag-grid.com, if you identify yourself they should be able to help you finding your login access

Hope this helps!
