### ISSUE TITLE
Initiating a textarea celleditor with the enter key is applying a premature edit to the data

### ISSUE THREAD

**Issue by rburkhart** [ag-grid/ag-grid#3808]
**I'm submitting a ...**  (check one with "x")
[x] bug report => see 'Providing a Reproducible Scenario'

**Providing a Reproducible Scenario**
There is a plnkr from the aggrid website examples at https://www.ag-grid.com/javascript-grid-cell-editor/#example-vanilla-editor-component that you can use to demonstrate the error.

**Current behavior**
If you begin editing an agLargeTextCellEditor (or a textarea in a custom cell editor) when initiating the edit by hitting the enter button it adds an extra return character to the end of the text in the text area control.  

In the provided plnkr select a cell in the address field column.
Press enter to begin editing the cell data.
Without entering any additional text hit enter to apply the text.
Repeat several times and you will keep adding carriage return characters.

I  created my own celleditor to attempt to view/modify the data getting set and the carriage return is getting added to the text area after the cell editors afterGuiAttached event is getting fired.

**Expected behavior**
I would expect that when navigating the grid with the keyboard, when you hit enter to initiate editing the cell it should load initiate the textarea with the text from the data with no modification.

**Please tell us about your environment:**
Just using a static set of html/javascript files because I am evaluating agGrid for use for a upcoming project that is very reliant on a grid.
Node/npm/Webpack for builds
VSCode as an editor

* **ag-Grid version:** X.X.X
v23.0.2

* **Browser:**
Verified in Chrome: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

Verified in IE Edge: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6 compiled to ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4181 [Editor] agLargeTextCellEditor adds extra new line each time user hits ENTER to edit cell

**Comment by ChaitanyaTeja150688** [comment]
@makinggoodsoftware Key-down event does not work in aglargetextcelleditor inputs, Any support
