### ISSUE TITLE
Fill handle disappears from cell after edit

### ISSUE THREAD

**Issue by matthewwoodruff** [ag-grid/ag-grid#3809]
**I'm submitting a ...**  
```
[X] bug report 
```

**Reproducible Scenario**
1. Visit the example [here](https://www.ag-grid.com/javascript-grid-range-selection-fill-handle/#example-custom-fill-operation)
2. Double click one of the days of the week cells and enter a new value
3. Press return to commit the new value

**Current behavior**
The fill handle is no longer present on the cell
To use the fill handle again, focus has to be moved away and back to the cell

**Expected behavior**
The fill handle should be present on a cell after an edit

**Please tell us about your environment:**
MacOSX 10.15.4

* **ag-Grid version:**
I've tried versions 22.1.1 and 23.0.2 locally although the issue exists [here](https://www.ag-grid.com/javascript-grid-range-selection-fill-handle/#example-custom-fill-operation) 

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4183 [Fill Handle] Fill Handle disappears after cell editing with ENTER key
