### ISSUE TITLE
Ag-grid Date Column filter placeholder

### ISSUE THREAD

**Issue by rt2304** [ag-grid/ag-grid#3812]
In React, I am using agColumnFilter to filter a date column in the ag grid. The placeholder shown in the filter input is always mm/dd/yyyy. Is it possible to change it to dd/mm/yyyy?

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-3735 | Allow custom date format to be specified when using a date filter
-- | --

**Comment by yashwanth2714** [comment]
It looks like this is still not available. Is there any alternate way to achieve this?

**Comment by aspergillusOryzae** [comment]
A workaround is to enable localeText in gridOptions, and set browserDatePicker to false in your column definition. See the bottom example of this stackblitz:
https://stackblitz.com/edit/ag-grid-angular-datefilterlocale-qv56xa?file=src/app/app.component.ts

It removes the placeholder text in the floating filter, but is shown in the filed when you use the filter popup.
![Screen Shot 2023-02-10 at 5 31 12 PM](https://user-images.githubusercontent.com/10411175/218231603-36e93129-f805-41c5-b12a-89e211eed7f5.jpg)

**Comment by saqi3492** [comment]
is any update on this? or is there any other way to do this?

**Comment by PedroBraude** [comment]
> is any update on this? or is there any other way to do this?


I wonder the same

**Comment by AG-Zoheil** [comment]
Hello,

Whilst the specific feature request is still in our backlog, please do have a look at the following change we've made since that may suffice for your use case/requirements: https://ag-grid.com/javascript-data-grid/cell-data-types/#date-as-string.

Thank you!
Zoheil

**Comment by andreiaasp** [comment]
Is there any solution for this already? I had to create a cell Renderer, cell Editor and now will also probably need to create a custom filter and also for floating filter just to be sure it's in a certain format, is there an easier way to change the format in all of these for the date type?
