### ISSUE TITLE
Causing Warnings: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by simkessy** [ag-grid/ag-grid#3813]
On the latest version I get this error when rendering material UI components in a row. Not using SSR. 

![image](https://user-images.githubusercontent.com/5871660/80641955-7f6f3a00-8a1a-11ea-8612-8d1c146c6c79.png)

**Comment by seanlandsman** [comment]
Will be fixed in our next release (due out this week) - thanks
