### ISSUE TITLE
Regression: array cell value formatting ignored

### ISSUE THREAD

**Issue by cmolodo** [ag-grid/ag-grid#3815]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Reproducible Scenario**

1. Create a column definition with an array value, and a value formatter function that returns any string except a simple `value.join(", ")` call.
2. Display the table with data in at least one row.  The array value column will display as `value.join(", ")` instead of using the result of the provided formatter function.

For example:
```
export class RowData {
  arrayValue: number[];
}

const colDef = {
  field: "arrayValue",
  valueFormatter: (value) => "Display this value instead",
};
```

**Current behavior**
In the column definition, if the the cell value is an array, the formatted result provided by the value formatter function is ignored and replaced with a simple value.join(", ") call.

This appears to be due to a mistake in the ValueFormatterService function formatValue() that generates the formatted value:
```
// if we don't do this, then arrays get displayed as 1,2,3, but we want 1, 2, 3 (ie with spaces)
if (result != null && Array.isArray(value)) {
  result = value.join(', ');
}
return result;
```
Probably this should say `result == null`, **not** `result != null`.

**Expected behavior**
The formatted value returned by the formatter function should be displayed.

**Please tell us about your environment:**
OS: Windows 10
IDE: Intellij IDEA Ultimate
Angular 9

* **ag-Grid version:** 23.1.0
This is a regression bug in the most recent ag-grid-community v23.1.0 release, it works correctly in v23.0.2.

* **Browser:** all

* **Language:** Typescript 3.7.5

**Comment by bradyolson** [comment]
I am seeing the same issue. The `valueFormatter` on the supplied column definition gets invoked, but does not affect the rendered result.

309e281065480c5baffd27dde172530f246d9690 is the commit that introduced this

**Comment by borglin** [comment]
Rolling back to 23.0.0

**Comment by alowdon** [comment]
Hi @cmolodo, many thanks for raising this and for the detailed report - we're looking at it now under AG-4187 and it will be fixed in the next patch release.

**Comment by Ge6ben** [comment]
I have same issue!
`valueFormatter` and `valueGetter` didn't works! for array

**Comment by AG-Zoheil** [comment]
Hi,

I would highly recommend upgrading the version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made.

Also, I'd recommend to upgrade the AG-Grid version sooner rather than later to avoid having even more changes to make as part of the upgrade process.

Kind regards,
Zoheil
