### ISSUE TITLE
Couldn't find preset "react-app. Issues after update from 21.1.2 to 23.1.0

### ISSUE THREAD

**Issue by DonikaV** [ag-grid/ag-grid#3816]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

After the update, I have errors while building. 

 ERROR in ./node_modules/ag-grid-react/main.js
18:31:35  Module build failed: Error: Couldn't find preset "react-app" relative to directory "/home/jenkins/workspace/MY_BRANCH/node_modules/ag-grid-react"

Before that was another error 
ModuleNotFoundError: Module not found: Error: Can't resolve 'ag-grid-community/main' in '/home/jenkins/workspace/MY_BRANCH/src/grid'

I thought it is because  of this import 

`import { RowNode } from 'ag-grid-community/main';`

after I changed to 

`import { RowNode } from 'ag-grid-community';`

Now I have this error about preset... 
With version 21.* was working well

**Comment by DonikaV** [comment]
Even if i will comment this import and usage I have errors 

ERROR in ./node_modules/ag-grid-react/main.js
Module build failed: Error: Couldn't find preset "react-app" relative to directory "/Users/vdonika/MY_APP/node_modules/ag-grid-react"

**Comment by seanlandsman** [comment]
@DonikaV do you have a repo I can take a look at for this?

**Comment by DonikaV** [comment]
No, this is private repo.

**Comment by DonikaV** [comment]
I have a license. I don't know, with license do I have a support help? or not? Because it is a block for me for now.

**Comment by seanlandsman** [comment]
Yes you do have support help: If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by DonikaV** [comment]
I sent email.

**Comment by akashagrawal121204** [comment]
Hey @makinggoodsoftware what was the solution for this issue. Was it fixed in next release version. I am also facing the same issue in 27.0.1 version

**Comment by prathinielsen** [comment]
Same, issue still present
