### ISSUE TITLE
Unable to paste single-cell values with range selection disabled

### ISSUE THREAD

**Issue by mbs-zanas-stundys** [ag-grid/ag-grid#3818]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
  
**Current behavior**

Pasting single-cell values into editable cells is not possible for given configuration:
```
enableRangeSelection=false
suppressCopyRowsToClipboard=true
```

https://plnkr.co/edit/N08mMclABkbRK6Hk?preview

**Expected behavior**
It should be possible to paste single-cell copied values, just like with `enableRangeSelection=true`.

**Please tell us about your environment:**
Operating system: MacOS Catalina
IDE: VS Code

* **ag-Grid version:** 23.1.0

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.


This is the reference and summary of the relevant issue:  AG-1950: Clipboard - copy paste current cell if no range selection is enabled
