### ISSUE TITLE
Grid disappears in print preview or when page is saved as pdf

### ISSUE THREAD

**Issue by jbojcic1** [ag-grid/ag-grid#3824]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In versions >= 23.0.0 table disappears from the page when you open print preview or save it as pdf while in versions 22.x.x the header disappears.

**Expected behavior**
Grid should be shown normally like it was showing before in version 21.2.2

Examples:
v21.2.2:
[codesandbox example](https://codesandbox.io/s/dazzling-satoshi-0n6d2)

<img width="1664" alt="Screen Shot 2020-05-08 at 8 06 15 PM" src="https://user-images.githubusercontent.com/10374826/81435024-704d6200-9167-11ea-8ed6-cfa83a70cb56.png">

v22.1.1: 
[codesandbox example](https://codesandbox.io/s/happy-almeida-1sl3i)

<img width="1669" alt="Screen Shot 2020-05-08 at 8 09 08 PM" src="https://user-images.githubusercontent.com/10374826/81435248-d639e980-9167-11ea-8bae-2b76382b01c0.png">

v23.1.0:
[codesandbox example](https://codesandbox.io/s/jolly-sinoussi-fkqww)

<img width="1650" alt="Screen Shot 2020-05-08 at 8 10 06 PM" src="https://user-images.githubusercontent.com/10374826/81435315-efdb3100-9167-11ea-8dbd-bebea9f8eaca.png">

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that we cannot classify this as a bug as unfortunately the behavior seen through different releases can't be guaranteeed.

Note that if you are looking to print the grid, you should look into 

https://www.ag-grid.com/javascript-grid-for-print/

Hope this makes sense

**Comment by lidaguang1989** [comment]
any idea about this issue

**Comment by lidaguang1989** [comment]
I found a temporary solution:
before call print() method, exec the flowing code, replace “ag-header”, "ag-header-viewport" with your own classname.

```
  const agHeaderList = Array.from(document.getElementsByClassName('ag-header'))
  const agHeaderViewportList = Array.from(document.getElementsByClassName('ag-header-viewport'))

  if (agHeaderList && agHeaderList.length > 0) {
    agHeaderList.forEach(item => {
      item.classList.replace('ag-header', 'ag-header-self')
    })
  }

  if (agHeaderViewportList && agHeaderViewportList.length > 0) {
    agHeaderViewportList.forEach(item => {
      item.classList.replace('ag-header-viewport', 'ag-header-viewport-self')
    })
  }
```
