### ISSUE TITLE
Error when using multiple cssclasses in CSSClassRules property after upgrade to 23.1.0

### ISSUE THREAD

**Issue by sharatbaradia** [ag-grid/ag-grid#3825]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Plunker - https://plnkr.co/edit/Zn4xGJuz5qr4YZyb

**Current behavior**
ERROR DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided ('rag-green abc') contains HTML space characters, which are not valid in tokens.
at Object.removeCssClass (https://unpkg.com/@ag-grid-community/all-modules@23.1.0/dist/ag-grid-community.cjs.js:1011:27)

**Expected behavior**
Should be able to use multiple CSS classes in cssClassRules property of the grid column.

**Please tell us about your environment:**
Angular 7.2.3

* **ag-Grid version:** X.X.X
23.1.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

After upgrading to 23.1.0 from 21.2.1, I am seeing below error. Looks like I can no longer use multiple CSS class under cellClassRules property. I have created a plunker to show that issue.

**Error shows in the console when you click on "Reload Data" button.**

ERROR DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided ('rag-green abc') contains HTML space characters, which are not valid in tokens.
at Object.removeCssClass (https://unpkg.com/@ag-grid-community/all-modules@23.1.0/dist/ag-grid-community.cjs.js:1011:27)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-4210 - regression: CellClassRules - applying two classes in the same condition throws a DOMException
