### ISSUE TITLE
popup cell editor getPopupPosition function not working after upgrade to 23.1.0

### ISSUE THREAD

**Issue by RihabRea** [ag-grid/ag-grid#3827]
In my typeahead component cell editor, the cellEditor display under the editable cell, and I want to display it over the cell; I used the getPopupPosition function, but it is not working in ag-grid cell editor last release. (isPopup function return true, and getPopupPosition() return over but it is not working. The bug is in the second image, and what I need it is in the first image.
the bug : when I click the cell in first row, the editor open under the cell ( in second row)

![over-cell-editor](https://user-images.githubusercontent.com/65167695/81558271-1088ce00-9396-11ea-909f-59d58cfde8f0.PNG)
![under-cell-editor](https://user-images.githubusercontent.com/65167695/81558278-1383be80-9396-11ea-8d41-7eae6e105c1a.PNG)

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4200 | getPopupPosition returns the wrong position
-- | --
