### ISSUE TITLE
Memory leak when using modules

### ISSUE THREAD

**Issue by tiberiuzuld** [ag-grid/ag-grid#3830]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

I added a plunker with an example where the ag-grid using modules after pressing the destroy button the memory tab you still find RowNode's.
Currently in my application having a memory leak regarding the `rowClassRules` with callback.
But in the plunker I didn't got to that one seems to be a memory leak regarding :
setFixedHeight()@5769481 -> VM6065 ag-grid-community.cjs.js:1310

https://plnkr.co/edit/FtrEhKAtLDT8OyZy

**Current behavior**
After destruction of ag-grid the table objects are still in memory

**Expected behavior**
To not have memory leaks :)

**Please tell us about your environment:**
Windows, Linux

* **ag-Grid version:** 23.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.0.0 Safari/537.36"

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Thank you for the context you provided - this really helps us understand your requirements.

We have added this to our backlog and we are tracking it with the following reference and description:

AG-4241 | [Framework] Memory leak when using RowClassRules in Angular

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
