### ISSUE TITLE
grid.showOverlay issue 

### ISSUE THREAD

**Issue by mikezharov** [ag-grid/ag-grid#3837]
Hello guys, here to submit a small issue;

**I'm submitting a ...**  (check one with "x")
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

**Requesting Community Support**

**Providing a Reproducible Scenario**
a console written exception coming from attributes.optional "bean instance"

"ag-Grid: unable to find bean reference frameworkOverrides while initialising BeanStub"

this happens after we call GridApi.showLoadingOverlay after creating, populating a grid's rowData and then disposing o 

my html is as follows:

///////////////// 
<ag-grid-angular id="grid"
                           #grid style="width: 100%; height: 200px;" class="ag-theme-alpine"
                           [rowData]="data" [columnDefs]="columnDefs"
                           [rowSelection]="single" (rowClicked)="onSelectionChanged($event)" (gridReady)="onGridReady($event)">
</ag-grid-angular>
///////////////////

Full Error Stack Trace:
////////////////// 
ag-Grid: unable to find bean reference frameworkOverrides while initialising BeanStub
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.lookupBeanInstance	@	ag-grid-community.cjs.js:3192
(anonymous)	@	ag-grid-community.cjs.js:3126
(anonymous)	@	ag-grid-community.cjs.js:3125
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.forEachMetaDataInHierarchy	@	ag-grid-community.cjs.js:3154
(anonymous)	@	ag-grid-community.cjs.js:3120
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.autoWireBeans	@	ag-grid-community.cjs.js:3119
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.wireBeans	@	ag-grid-community.cjs.js:3068
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.wireBean	@	ag-grid-community.cjs.js:3065
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.UserComponentFactory.initComponent	@	ag-grid-community.cjs.js:13655
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.UserComponentFactory.createAndInitUserComponent	@	ag-grid-community.cjs.js:13406
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.UserComponentFactory.newLoadingOverlayComponent	@	ag-grid-community.cjs.js:13348
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.OverlayWrapperComponent.showLoadingOverlay	@	ag-grid-community.cjs.js:33011
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridPanel.showLoadingOverlay	@	ag-grid-community.cjs.js:26037
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridApi.showLoadingOverlay	@	ag-grid-community.cjs.js:27077
.........
///////////////////

Current behaviour:
prints uncatchable console error, when the grid. ShowLoadingOverlay is called. Expected behaviour.:

**Current behavior**

when setting the Grid.ShowOverlay on a grid that is loaded then destroyed
you encounter a console error

**Expected behavior**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

yes

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript (.ts)

Hopefully that helps. Feel free to contact me if you would require more information about this.
Email: deuxexe@gmail.com
Sincerely,

**Comment by juliusfriedman** [comment]
Per a similar issue here:

https://github.com/ag-grid/ag-grid/issues/1778

A possible work around is as follows:

```
//@ts-ignore destroyed is private...  
if (false === gridApi.gridCore.destroyed) {
              gridApi.showLoadingOverlay();
}
```
