### ISSUE TITLE
Export to excel/csv not showing column groups

### ISSUE THREAD

**Issue by A30001399** [ag-grid/ag-grid#3842]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```
I'm facing an issue while exporting the grid to excel/csv. The grid has column groups, but is not appearing on export to excel or csv. Only the children columns are getting exported to excel.

**Grid Screenshot**
![image](https://user-images.githubusercontent.com/49664679/82162927-41638880-98eb-11ea-9252-cfda4872cc86.png)

**Excel Screenshot**
![image](https://user-images.githubusercontent.com/49664679/82163303-a6b87900-98ed-11ea-873f-b51b2a6b13cd.png)

**Current code for export**
  onBtnExportDataAsExcel() {
    const params = this.getExportParams();
    this.gridApi.exportDataAsExcel(params);
  }

  onBtnExportDataAsCsv() {
    const params = this.getExportParams();
    this.gridApi.exportDataAsCsv(params);
  }

  getExportParams() {
    return {
      columnGroups: true
    };
  }

**Current behavior**
The grid column groups (USA & AUSTRALIA as per the above screenshot) are not shown on excel or csv export. The 'columngroup: true' is passed in as params to export function.

**Expected behavior**
The column groups should be shown on excel or csv export. ( as per documentation - https://www.ag-grid.com/javascript-grid-export/ )

**Please tell us about your environment:**
angular v8.2.14

* **ag-Grid version:** 
"ag-grid-angular": "^22.1.1",
"ag-grid-community": "^22.1.1",
"ag-grid-enterprise": "^22.1.1",

* **Browser:**
Chrome - Version 80.0.3987.12

* **Language:**
 TypeScript  - v3.5.3

**Comment by kpratik2015** [comment]
This should really be better documented. It was a very painful find in a little note here: [CSV Export](https://www.ag-grid.com/javascript-grid/csv-export/) stating `Note that column groups are not exported by default, you must pass columnGroups=true.` Although this holds true for Excel Export feature as well.

I really don't know the reasoning behind not defaulting it to `true`. Had to explicitly pass `columnGroups: true` in `defaultExportParams` to get the exported excel show the column group headers in first row. The name doesn't gives a sense of it being a boolean either.

**Comment by Marooned-MB** [comment]
@kpratik2015 unfortunately, `columnGroups: true` is not enough when you want to exclude some columns. In that case one would use `columnKeys` but when doing that, I was unable to find a way to include autoGroupColumnDef in the excel file.

**Comment by dwn-phoenixpan** [comment]
Got the same issue, `columnKeys` won't include autoGroupColumnDef
