### ISSUE TITLE
Column flex and maxWidth result in column headers not rendering properly until a column is resized

### ISSUE THREAD

**Issue by craigsh** [ag-grid/ag-grid#3845]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

When defining columns in a grid using flex and maxWidth some of the column headers don't render correctly until a column is resized.

e.g.
columnDefs = [
        {field: 'make', flex: 1, maxWidth: 500, resizable: true },
        {field: 'model', flex: 1, maxWidth: 500, resizable: true },
        {field: 'price'}
    ];

Removing the maxWidth fixes the issue - though some smaller values of maxWidth work.

I have created a reproducer using StackBlitz here:

https://ag-grid-angular-hello-world-ysezjr.stackblitz.io

This only reproduces when opening the StackBlitz in a new browser window. (Direct link to the external browser window is: https://ag-grid-angular-hello-world-ysezjr.stackblitz.io/)

Current behaviour:

Using the canonical example of the car models with Make, Model and Price columns, the Price column's header isn't visible until one of the columns is resized.

Expected behaviour:

All columns will render their headers correctly without having to resize a column.

**Please tell us about your environment:**
OS: Windows 10 Professional
IDE: Visual Studio Code
Package manager: NPM

* **ag-Grid version:** 23.1.1

* **Browser:**
Chrome: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
Edge: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.72"
Firefox: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for your message. We have added this to our backlog and we are tracking it with the following reference and description:

AG-4243: [Column Flex] When using column flex and maxWidth, last column header text isn't shown

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Thanks
