### ISSUE TITLE
ag-grid-react noRowsOverlay shown instead of the loadingOverlay

### ISSUE THREAD

**Issue by croraf** [ag-grid/ag-grid#3849]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://plnkr.co/edit/zrFfVfwHJpuhl72F
- initialize ag-grid react component
- let the initial data be null/undefined
- this shows loadingOverlay correctly 
![image](https://user-images.githubusercontent.com/19698636/82435612-d48bf200-9a94-11ea-8bc7-7be338221570.png)
- after the data is fetched and set to the actual data, the overlay is removed and the data is shown
- put data again to null/undefined on the same ag-grid table instance (re-fetching of data)

**Current behavior**
- the table now shows noRowsOverlay
![image](https://user-images.githubusercontent.com/19698636/82435636-db1a6980-9a94-11ea-964b-57ffc29ec193.png)

**Expected behavior**
- the table should again show loadingOverlay
![image](https://user-images.githubusercontent.com/19698636/82435612-d48bf200-9a94-11ea-8bc7-7be338221570.png)

**Please tell us about your environment:**

* **OS:** Ubuntu 

* **ag-Grid version:** 22.1.1

* **Browser:** Chrome

* **Language:** all

**Comment by ferdikoomen** [comment]
This is fixed here: https://github.com/ag-grid/ag-grid/commit/a85b88a94664e16633817a04d5ae53eac4526480#diff-1aea837b0459feebe8f83952471bad47L65 (works on 23.x), would be nice if this can be back ported to 22.x

**Comment by NuclleaR** [comment]
Still doesn't work
I used v23.2.1

**Comment by croraf** [comment]
@NuclleaR I'm currently using this useEffect and api methods mechanism on v22 as a workaround. 

But this issue was related to the overlay presentation only with respect to data provided to AgGridReact **without using the useEffect** (if data provided is undefined show LoadingOverlay, if it is empty array show NoRowsOverlay).

So perhaps this comment of yours is unrelated and should be a different issue.

**Comment by NuclleaR** [comment]
@croraf maybe you are right

**Comment by croraf** [comment]
Yes, this still does not work in version `24.1.0`. The example can be seen here https://plnkr.co/edit/dSItpmVpgvW39nji . If someone from maintainers can reopen the issue @makinggoodsoftware .

**Comment by choudharyhimanshu** [comment]
I am facing the same issue with version `25.1.0`. As a workaround, wrapping the showLoadingOverlay call inside a setTimeout did the trick

```
setTimeout(() => {
      gridApi?.showLoadingOverlay();
});
```

**Comment by riwu** [comment]
Refetching data is a fairly common use case and I can't believe this enterprise-grade library doesn't even handle it...

**Comment by croraf** [comment]
I'm the OP. Actually it is handled. There is a problem if you also simultaneously set data to empty array. You shouldn't do this need just leave the data as is:

You should have the following snippet:

```
  useEffect(() => {
    if (api) {
      if (loading) {
        api.showLoadingOverlay();
      } else {
        if (data && data.length === 0) {
          api.showNoRowsOverlay();
        } else {
          api.hideOverlay();
        }
      }
    }
  }, [loading, data, api]); 
```

During the fetch start just set the `loading` to true, and after the fetch simultaneously set the `data` to fetched data and `loading` to false.

Although it is kind of sad there is no "declarative" way to set the loading. Like "loading" property on the table itself.

**Comment by riwu** [comment]
@croraf could you show me how you would fix https://codesandbox.io/s/pensive-bush-p5mof?file=/src/App.js without removing the `setData(null)` (behavior of Apollo GraphQL client)?

**Comment by croraf** [comment]
I dont know if it is possible. Setting data to null messes up ag-grid.

**Comment by riwu** [comment]
That's unfortunately the behavior of Apollo client API, unless perhaps I set `rowData` to https://www.apollographql.com/docs/react/api/react/hooks/#previousdata when loading...will just stick with the `setTimeout` hack for now.

**Comment by patrickDouglas** [comment]
I'm also experiencing exactly what @riwu is mentioning.  I can't get the `setTimeout` to work though. What have other done?
```js
useEffect(() => {
  if (gridApi) {
    if (loading) {
      gridApi.showLoadingOverlay();
    } else if (rows && rows.length === 0) {
      gridApi.showNoRowsOverlay();
    } else {
      gridApi.hideOverlay();
    }
  }
}, [gridApi, loading, rows]);
```

**Comment by bboydflo** [comment]
> I am facing the same issue with version `25.1.0`. As a workaround, wrapping the showLoadingOverlay call inside a setTimeout did the trick
> 
> ```
> setTimeout(() => {
>       gridApi?.showLoadingOverlay();
> });
> ```

did the trick for me (using ag-grid with angular)

**Comment by finnhvman** [comment]
Came across this issue as well. I worked around it by a conditional `overlayNoRowsTemplate`. Whenever my row data length is 0, I make it render `'No Rows to Show'`, other wise it says something like `'Loading'`. You could of course use the component option as well.

https://www.ag-grid.com/react-data-grid/overlays/#custom-templates

**Comment by kennylam91** [comment]
> I am facing the same issue with version `25.1.0`. As a workaround, wrapping the showLoadingOverlay call inside a setTimeout did the trick
> 
> ```
> setTimeout(() => {
>       gridApi?.showLoadingOverlay();
> });
> ```

you saved my day, thks a lot

**Comment by ankur-at-everstage** [comment]
> I am facing the same issue with version `25.1.0`. As a workaround, wrapping the showLoadingOverlay call inside a setTimeout did the trick
> 
> ```
> setTimeout(() => {
>       gridApi?.showLoadingOverlay();
> });
> ```

this has worked for me

**Comment by blume0F** [comment]
why does wrapping the overlay around setTimeout works?

setTimeout(() => {
      this.gridApi.showLoadingOverlay();
});

**Comment by phoenixxd** [comment]
This issue is still lingering in version `26.0.0`. The following hack did the trick for me as well. Hoping this gets fixed in the upcoming versions.

> I am facing the same issue with version `25.1.0`. As a workaround, wrapping the showLoadingOverlay call inside a setTimeout did the trick
> 
> ```
> setTimeout(() => {
>       gridApi?.showLoadingOverlay();
> });
> ```
