### ISSUE TITLE
(docs) Broken code/snippet highlighting

### ISSUE THREAD

**Issue by FrankiePo** [ag-grid/ag-grid#3850]
**I'm submitting a snippet bug in documentation**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Snippets doesn't work in https://www.ag-grid.com/graphql-server-side-operations/
There is no code highlighting in the whole page.

Images:
![image](https://user-images.githubusercontent.com/5219218/82444678-46bc0100-9aac-11ea-8ac3-ce9dff2e5537.png)
![image](https://user-images.githubusercontent.com/5219218/82444790-6eab6480-9aac-11ea-8205-183dd585cca9.png)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

AG-4237 | Docs - Code snippet formatting missing in SSRM GraphQL page

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
