### ISSUE TITLE
Angular Material Theme Quick Filter - One Result Inline Editing Cutting Off

### ISSUE THREAD

**Issue by weilinzung** [ag-grid/ag-grid#3854]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

Angular Material Theme with quick filter, when there is one result also enable inline editing. The editing box would cut off(overflow issue). See screenshot

![Screen Shot 2020-05-23 at 4 15 23 PM](https://user-images.githubusercontent.com/7368063/82739863-73bd1d80-9d11-11ea-9769-bcd9e9974b80.png)

If reporting a bug make sure to state.

Current behaviour.

The inline editor is cutting off when only one result with a quick filter on, also it could be cut off as well when there is only one row.

Expected behaviour. If possible back this up with our docs/examples if possible

Should not be cut off.

**Please tell us about your environment:**

macOS Catalina

* **ag-Grid version:** X.X.X

    "ag-grid-angular": "^23.1.1",
    "ag-grid-community": "^23.1.1",

* **Browser:**

Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "~3.4.3",
 "lib": ["es2018", "dom"],

**Comment by makinggoodsoftware** [comment]
Hi,

This was released as part of release 23.2.0

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

And released items in our changelog:
https://www.ag-grid.com/ag-grid-changelog/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
