### ISSUE TITLE
The header is wrong position when zooming

### ISSUE THREAD

**Issue by baonguyen93** [ag-grid/ag-grid#3857]
I'm submitting a bug report. The problem i had is when i zoom from 100 to 80%, the header is wrong position. This problem is only happend in **Chrome and Opera (resolution: 1920x1080)**, not Firefox.
Please see the belowed images.

![op1](https://user-images.githubusercontent.com/49013423/82972826-276b2980-a000-11ea-830c-bb7916e2ec04.png)
![op2](https://user-images.githubusercontent.com/49013423/82972831-2934ed00-a000-11ea-8365-e659c9ed4930.png)
![op3](https://user-images.githubusercontent.com/49013423/82972833-2934ed00-a000-11ea-87e7-44da5fb8d11c.png)

I debugged and found a problem in file ag-grid-community\dist\lib\gridPanel\gridPanel.js

> GridPanel.prototype.onBodyHorizontalScroll = function (eSource) {
> var _a = this.eCenterViewport, scrollWidth = _a.scrollWidth, clientWidth = _a.clientWidth;`
> // in chrome, fractions can be in the scroll left, eg 250.342234 - which messes up our` 'scrollWentPastBounds'`
>  // formula. so we floor it to allow the formula to work.`
> var scrollLeft = Math.floor(utils_1._.getScrollLeft(eSource, this.enableRtl));
> // touch devices allow elastic scroll - which temporally scrolls the panel outside of the viewport
> // (eg user uses touch to go to the left of the grid, but drags past the left, the rows will actually
> // scroll past the left until the user releases the mouse). when this happens, we want ignore the scroll,
> // as otherwise it was causing the rows and header to flicker.
> console.debug('[scrollLeft, clientWidth, scrollLeft + clientWidth, scrollWidth] 111111111: ', scrollLeft, clientWidth, scrollLeft + clientWidth, scrollWidth); <------- (I added this line to debug)
> var scrollWentPastBounds = scrollLeft < 0 \|\| (scrollLeft + clientWidth > scrollWidth);
> if (scrollWentPastBounds) {
> return;
> }
> this.doHorizontalScroll(scrollLeft);
> this.resetLastHorizontalScrollElementDebounce();
> };

The value of clientWidth > scrollWidth when i zoom to 80% (the scrollbar is disappeared)
Please see the belowed image

![op4](https://user-images.githubusercontent.com/49013423/82974138-74043400-a003-11ea-9e69-921dbed54815.png)

Beacause the value **clientWidth = 1554** and **scrollWidth = 1553**, so **scrollWentPastBounds = true**. And the program not execute 2 lines **this.doHorizontalScroll(scrollLeft);** and **this.resetLastHorizontalScrollElementDebounce();**

A same error in function "horizontallyScrollHeaderCenterAndFloatingCenter" in file gridPanel.js.

**Please tell us about your environment:**

* **ag-Grid-community version:** 20.1.0

* **Browser:** Chrome (lastest version)

So thanks for reading. I hope to the answer soon. Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:


AG-2550 | Rendering - Support Zoom in/out of the browser
-- | --
