### ISSUE TITLE
Reopen custom filter view, scroll position is reset.

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [ag-grid/ag-grid#3858]
**I'm submitting a bug report**  

**Current behavior**

when i open grid filter and scroll it, click anywhere else, filter dismissed. Then open the filter again, the scrolled filter list view scroll top has been reset.

**Expected behavior**

Can we keep the filter list scroll position when reopen it?

Because I create a custom filter, and I use 'react-virtualized', If the scroll top reset when reopened, the list view will be wrong.

**Please tell us about your environment: win10/VS code/NPM/**

**ag-Grid version:**  "^18.1.2",

**Browser:**  Chrome/81.0.4044.138

* **Language:**  ES6/7

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-824 | Maintain popup editor positions when scrolling
-- | --
