### ISSUE TITLE
Set filter not working when trying to explicitly configure it for ag-grid community version in vue js

### ISSUE THREAD

**Issue by kaustubh77** [ag-grid/ag-grid#3862]
This is the code that I am using to set filter option on one of my table's columns. However on clicking the button shown on the header, no dropdown opens up (Not even the default one which is available in ag-grid community which opens up when we set filter: true). Is there something that I am missing? Sorry if this questions is too
```
this.defaultColDef = {
    floatingFilter: true
};
this.columnDefs = [
    { headerName: 'id', field: 'id', hide: false, resizable: true, filter: 'agSetColumnFilter' },
    { headerName: 'timestamp', field: 'timestamp', hide: false, resizable: true, filter: true },
];
```
![image](https://user-images.githubusercontent.com/24550834/83153210-51b20980-a11c-11ea-9874-30f1b54389cb.png)
Nothing happens on clicking the above button

**Comment by seanlandsman** [comment]
Set Filter is a feature of ag-Grid Enterprise and is therefore not available to ag-Grid Community
