### ISSUE TITLE
Theme: error when trying to change foreground-color

### ISSUE THREAD

**Issue by Prontsevich** [ag-grid/ag-grid#3874]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Here is the [link](https://stackblitz.com/edit/ag-grid-theme-spr) with demo on stackblitz.
I wasn't able to create a demo in plunker, it was too hard to understand what I need to change in your example.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
I got an error when was customizing Balham theme. I used example from you documentation.
Error occurs only when I'm trying to change foreground-color variable. 
`Error in ag-grid-community/src/styles/mixins/_ag-theme-params.scss (339:9)
Expected argument to $mix to be a 2-item array [color, number] but got [string, number]: foreground-color 10%`

**Expected behavior**
No error, new color applied

**Please tell us about your environment:**
Windows 10, VS Code, npm, Angular 9

* **ag-Grid version:** 23.1.1

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

We have investigated this issue and this seems to be working on our end.

Please see the attached example:

[ag-grid-customise-theme-master.zip](https://github.com/ag-grid/ag-grid/files/4779556/ag-grid-customise-theme-master.zip)

We are not experiencing any issues when customising the foreground-color variable in ag-theme-balham.

Regards,

Ahmed

**Comment by Prontsevich** [comment]
Hi,

I used css variable in my example, and you used 'magenta' color in your. If you change your example to use css varible it will crashed too.

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for this catch. This is now in our backlog:

AG-4306 - Balham Theme doesn't allow foreground-color to be a CSS variable

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
