### ISSUE TITLE
Tooltip still display forever when hold press Enter key

### ISSUE THREAD

**Issue by quangpl** [ag-grid/ag-grid#3875]
- [x] bug report => see 'Providing a Reproducible Scenario'
- [ ] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
- [ ] support request => see 'Requesting Community Support'

**Current behavior**

- Open  https://www.ag-grid.com/javascript-grid-tooltip-component/#mouse-tracking
- Focus any cell (has data) in table and hold `Enter` key
- Move mouse around focus cell while you are holding `Enter` key
- Many tooltips will display and still display forever
Screenshot : 
![image](https://user-images.githubusercontent.com/36843088/83829922-3774be80-a70e-11ea-82d7-ee4f4068c45e.png)

**Expected behavior**
- Tooltip will hide as normal behavior

**Environment:**

- Window 10
- VS Code
- ReactJS

* **ag-Grid version:** 23.1.0
 
* **Browser:**
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Mobile Safari/537.36

* **Language:**  TypeScript 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by quangpl** [comment]
Thanks for advanced ! :D

**Comment by shuheb** [comment]
Hello!

Thank you for the context you provided - this really helps us understand your requirements. 

We have added this to our backlog and we are tracking it with the following reference and description:

AG-4290 | Tooltip Mouse Tracking does not work when holding enter on a cell

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Thanks again for bringing this up with us.

Regards,

Shuheb‍
Developer | ag-Grid

Get the latest ag-Grid updates and resources:
Follow us: @ag-Grid
Subscribe: ag-Grid YouTube channel
Blog: ag-Grid Blog

**Comment by quangpl** [comment]
Nice ! Thanks for your support ! 

Have a nice day,,
Quang

**Comment by kiril-matev** [comment]
Hi @darshanasohale12,

Thank you for reporting this.

The tooltip rendering issue reported above and logged as AG-4290 was fixed in AG Grid 24.0.

If you're seeing this behavior in a later version of AG Grid, please open a new issue about this following the bug report template. 

Specifically, as part of the bug report please provide:
1/ A sample which reproduces the issue 
2/ A list of steps to follow to reproduce it.

Thanks for using AG Grid.
