### ISSUE TITLE
Toolpanel in a popup

### ISSUE THREAD

**Issue by ravinaparab1** [ag-grid/ag-grid#3877]
**I'm submitting a 
[x] bug report => When the height of the grid is small and user opens sidebar, the sidebar gets clipped as the grid's height cannot accomodate the sidebar
[x] feature request => allow the toolpanel to open in a popup or increase the z-index of sidebar panel so it can overflow the grid and does not get clipped.
 The bug screenshot link is https://ibb.co/Bw3qZSZ.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
