### ISSUE TITLE
Flickering of headers on columnDefs change if React component is used

### ISSUE THREAD

**Issue by Norserium** [ag-grid/ag-grid#3879]
**I'm submitting a bug report**

**Current behavior**

Headers are flickering on change `columnDefs` if React component is used. I assume that the reason of this flickering is disabled static markup for header cells [here](https://github.com/ag-grid/ag-grid/blob/066683a1cd707906435b03178178522020bfa2a9/grid-packages/ag-grid-react/src/reactComponent.ts#L158). It may lead to such problems according [the documentation](https://www.ag-grid.com/react-fine-tuning/#react-cell-rendering).

There is [codesandbox ](https://codesandbox.io/s/ag-grid-flickering-headers-0j2xk) that illustrates the problem.

**Expected behavior**

Headers should not be flickering on change.

**Please tell us about your environment:**

* **ag-Grid version:** 23.2.0

* **Browser:** Chrome 83.0.4103.61

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by etyp** [comment]
@makinggoodsoftware this issue is affecting us quite badly - what's the best way to track the status of the Zendesk ticket?

We're stuck in a position where we can't revert to previous version.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3180 Prevent grid from flickering when updating columns + autoSize or sizeToFit
