### ISSUE TITLE
Column filter

### ISSUE THREAD

**Issue by vickyksingh** [ag-grid/ag-grid#3882]
Hi everyone,

i'm using ag-grid-vue in my project but the column filter is not as per the required

i require filter is 
<img width="182" alt="expected" src="https://user-images.githubusercontent.com/45713418/84021944-209aca00-a9a3-11ea-91ff-e2547b381bf4.PNG">
but i'm getting is 
<img width="147" alt="getting" src="https://user-images.githubusercontent.com/45713418/84022072-55a71c80-a9a3-11ea-80b3-226f49a1799e.PNG">

Can someone help me.

**Comment by gportela85** [comment]
Hi @vickyksingh the menu you said you need is the `enterprise` menu. For that, you will need a license.
