### ISSUE TITLE
[Ag-grid in React] Header popups are placed incorrectly

### ISSUE THREAD

**Issue by LynxUA** [ag-grid/ag-grid#3884]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Reproducible scenario:
https://plnkr.co/edit/zNzzBnnUW0TIhQQ7
It is also present in documentation:
https://ag-grid.com/javascript-grid-filter-component/#example-filtering-using-react-components

**Current behavior**
The first click on a column menu causes the table to resize.
<img width="691" alt="Снимок экрана 2020-06-09 в 17 00 08" src="https://user-images.githubusercontent.com/3246141/84156854-afc2e300-aa72-11ea-9f2b-ac3c2267e60e.png">

**Expected behavior**
The first representation of popup should be the same as the second (first popup invocation shouldn't resize the table).
<img width="683" alt="Снимок экрана 2020-06-09 в 17 00 38" src="https://user-images.githubusercontent.com/3246141/84156906-c0735900-aa72-11ea-98d0-73522ffb7bc3.png">

* **ag-Grid version:** 23.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4321 Opening column menu with React filtering component shouldn't resize column header

**Comment by Throttle** [comment]
@makinggoodsoftware, I can't find the issue AG-4321 here https://www.ag-grid.com/ag-grid-pipeline/.
Could you please clarify?
