### ISSUE TITLE
Drag and drop icon persists on the screen after dragging a row on iPad 

### ISSUE THREAD

**Issue by sarakarim** [ag-grid/ag-grid#3888]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
Device: iPad 5th Gen 
Browser: Safari
Steps to reproduce:
-Open Ag-grid on a Safari browser on iPad
-Drag and drop any row and observe the icon that persists on the screen
![table](https://user-images.githubusercontent.com/22002341/84356083-5a024e00-abcc-11ea-8f8b-2fa5d30aa7a9.png)

If reporting a bug make sure to state.

Current behaviour: The drag and drop icon will persist
Expected behaviour. The drag and drop icon should be dismissed 

**Please tell us about your environment:**
Device: iPad 5th Gen OS 13.5.1
Browser: Safari 13

* **ag-Grid version: Latest

* **Browser:**
Browser: Safari 13

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi,

Thank you for submitting this ticket.
We tried testing this on Xcode + the following example from our docs:

https://www.ag-grid.com/javascript-grid-row-dragging/#example-simple-managed

We were unable to observe the effect you showed us.
Would you be able to provide us with an example plunker where this can be observed?

Thanks,

*note that this ticket will now be closed, if you are able to provide an example where this occurs, please create a new ticket.
