### ISSUE TITLE
Scrollbars Always Visible Issue

### ISSUE THREAD

**Issue by DmitrySobolevski** [ag-grid/ag-grid#3889]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Please take a look at documentation example using macOS 
https://www.ag-grid.com/javascript-grid-scrolling-scenarios/

I got the same issue with scrollbars at my project.

Any workaround? It will be cool to have the opportunity to set a scrollbar visibility strategy through agGrid settings.

**Current behavior.**
'Scrollbars always visible' solution doesn't work for macOS Catalina with any browser, but perfectly works for other platforms (Windows and Linux).

**Expected behavior.**
'Scrollbars always visible' solution works at any platform.

**Please tell us about your environment:**
macOS Catalina

**ag-Grid version:** 
version at your documentation 

**Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-4269 | [Docs] Add DOCS sample showing how to implement mac+trackpad scrollbar behavior
-- | --
