### ISSUE TITLE
Ag-grid filter formate

### ISSUE THREAD

**Issue by vickyksingh** [ag-grid/ag-grid#3897]
Hi team,

i'm getting my date in mm/dd/yyyy format and i want my date filter to in mm/dd/yyyy format but i'm getting below dd-mm-yyyy.

<img width="188" alt="filter" src="https://user-images.githubusercontent.com/45713418/84680595-8f05fc00-af50-11ea-8e82-1a67548fd45d.PNG">

Please help me.
Thank You.

**Comment by btrangcasestack** [comment]
Did you take a look at this yet 
https://stackoverflow.com/questions/52802951/how-to-configure-date-render-format-in-ag-grid
