### ISSUE TITLE
Horizontal scrollbar covers bottom row after sizeColumnsToFit()

### ISSUE THREAD

**Issue by adamerose** [ag-grid/ag-grid#3906]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Calling `sizeColumnsToFit()` will size the table such that the horizontal scrollbar appears and covers the bottom row. 

Manually resizing the table or any column to be 1 pixel wider or narrower temporarily fixes it.

This happens even on the docs page
https://www.ag-grid.com/javascript-grid-resizing/#sizing-columns-by-default

![image](https://user-images.githubusercontent.com/10884874/85043258-27230180-b15a-11ea-948c-740011b6a665.png)

* **ag-Grid version:** 23.2.0

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4257 | Horizontal scrollbar rendered over last record
-- | --

**Comment by wilbsy** [comment]
Has this been fixed?

**Comment by devilaria** [comment]
Adding the below code to my css fixed it for me.
```
.dx-datagrid-rowsview .dx-scrollable-content {  
  padding-bottom: 5px;  
}  
```
