### ISSUE TITLE
Installing using NPM missing Alpine theme

### ISSUE THREAD

**Issue by f1nch** [ag-grid/ag-grid#3914]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Requesting Community Support**
If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
- run `npm i ag-grid-community` 
- The package does not include the Alpine theme CSS files even though when I download the master manually from Github it does include the correct files.

**Current behavior**
node_modules/ag-grid-community/dist/styles only includes the balham, balham-dark, blue, bootstrap, dark, fresh, material themes.

**Expected behavior**
node_modules/ag-grid-community/dist/styles should includes all themes 

**Please tell us about your environment:**

- windows 10
- visual studio code
- npm version 6.9.0
- angular project

* **ag-Grid version:** X.X.X

- ag-grid-angular version 21.1.0
- ag-grid-community version 21.1.0

* **Browser:**

- Chrome Version 83.0.4103.97

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- All

**Comment by gportela85** [comment]
Theme alpine was added on version 23.
