### ISSUE TITLE
Is it possible to do nested expand of row like in the image?

### ISSUE THREAD

**Issue by Tabris841** [ag-grid/ag-grid#3924]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```
Hello,

I want to if it is possible to create layout and behavior from the image with ag-grid, where AVL and Quantity columns can
expanded or collapse by the user ? And if it is possible what feature should be used (I don't think it is possible with tree data mode) ?

![image](https://user-images.githubusercontent.com/12796958/85834100-75a84f80-b79b-11ea-8765-07b3e72e17bd.png)

**Comment by flux711** [comment]
Hey Tabris,
I came across the same problem and also looking for an answer. If you found an answer to your question I would appreciate it if you could share any information with me.

Is there even a possibility of at least one of the two columns you mentioned can expand?

**Comment by Tabris841** [comment]
@flux711 
> Is there even a possibility of at least one of the two columns you mentioned can expand?

yes you can do that with https://www.ag-grid.com/javascript-grid-tree-data/

**Comment by flux711** [comment]
@Tabris841 
I have seen that too, but as far as I understood it you can only group the elements to the left and not, for example, in one of the middle columns as you mentioned in your issue
