### ISSUE TITLE
Full row edit mode, the last row is not saved when you tab away

### ISSUE THREAD

**Issue by 3vil4aron** [ag-grid/ag-grid#3926]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
1. Create an angular ag-grid using fullRow editing.
2. Data only has one row.
3. Double click to edit row
4. Tab to next cell and continue
5. Leave the row.

Plunker:
https://plnkr.co/edit/I364AIHGOh82VADZ

**Current behavior**
When editing a in row mode the last row is not saved when you tab away. If there is only one row data is not saved.

**Expected behavior**
Data is saved.

**Please tell us about your environment:**
Azure blob.

* **ag-Grid version:** X.X.X
"@ag-grid-community/all-modules": "^23.1.1",
"@ag-grid-community/angular": "^23.1.1",

* **Browser:**
Chrome.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript / JavaScript
es5 es2015

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4409 Changes in last row not saved when you TAB away from full-row edit mode
