### ISSUE TITLE
No update of RowDrag Text after changing value of a cell

### ISSUE THREAD

**Issue by KristinaB162** [ag-grid/ag-grid#3930]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

**Providing a Reproducible Scenario**

1. Create angular ag-grid
2. Set rowDrag: true and editable: true in ColDef
3. Change value of a cell in the first column
4. Drag -> The label of the dragged item is the old value and not the new one

https://plnkr.co/edit/7l2m2101yOUC7GUx?preview

**Current behavior**
Old value of draggable item:  ID = 100
New value of draggable item:  ID = 99
The rowDrag Text (showed when dragging) of the dragged item is the old value. (100)

**Expected behavior**
Old value of draggable item: ID = 100
New value of draggable item: ID = 99
The rowDrag Text (showed when dragging) of the dragged item is the new value. (99)

**Please tell us about your environment:**

 ag-grid-angular: "^22.1.1",
 ag-grid-community: "^22.1.1",

* **Browser:**
Firefox
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript / JavaScript
es5 es2015

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4408 Ghost dragging element does not update after updating cell value
