### ISSUE TITLE
[scrolling] Grid cells does not scroll when performing browser search on Column Header

### ISSUE THREAD

**Issue by sudeep494** [ag-grid/ag-grid#394]
When you search in browser for a header column text that is in the scrollable area but not in currently visible, the header div scrolls to viewable area but not the data columns. This causes headers to not align   properly with the cells. For example: In the grid shown in http://angulargrid.com, search the header text 'address'.

**Comment by toymachiner62** [comment]
:+1:

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-60

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
