### ISSUE TITLE
Checkbox row Selection not work

### ISSUE THREAD

**Issue by halilpolathalil** [ag-grid/ag-grid#3943]
![1](https://user-images.githubusercontent.com/43744978/86596714-5c757f00-bfa3-11ea-8924-b35943b26f67.jpg)

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I want checkbox for row selection. It works in version 21.2.2. But I upgrade to latest version and checkbox selection  does not work anymore. when I click checkbox not select row.

**Expected behavior**
checkbox row selection

**Please tell us about your environment:**
angular-cli 8.1.2

* **ag-Grid version:** 23.2.0

* **Browser:** Opera

* **Language:** [all | TypeScript 3.4.5| ES6/7 | ES5]

HERE IS MY HTML CODE

`<ag-grid-angular style="width: 100%; height: 400px;" class="ag-theme-material" [rowData]="pagedItems"
        [columnDefs]="columnDefs" [(gridOptions)]="gridOptions" (cellClicked)="onCellClicked($event)"
        [rowSelection]="rowSelection" (rowSelected)="onRowSelected($event)" [rowMultiSelectWithClick]="true">
    </ag-grid-angular>`

HERE IS TS CODE

`  public hasSelectedRows = new EventEmitter<boolean>();
    bsModalRef: BsModalRef;

    // pager object
    pager: any = {};
    pagedItems: any[];

    //Aggrid Object
    gridOptions: GridOptions;
    columnDefs: any[];
    rowSelection = "multiple";

    selectedModel: Message;
    selectedRows: Message[] = [];
    rowData: Message[];
    rowDataCopy: Message[];

    constructor(
        private modalService: BsModalService,
        private pagerService: PagerService,
        private commonRenderer: CommonRenderer,
        private commonStyle: CommonStyle,
        public notificationService: NotificationService,
        public globalFunctions: GlobalFunctions,
        public messageService: MessageService
    ) {
        // this.globalFunctions.showLoader.emit(true);
        this.messageService.getRowData().subscribe(res => {
            this.rowData = JSON.parse(JSON.stringify(res));
            this.rowDataCopy = JSON.parse(JSON.stringify(res));
            this.globalFunctions.showLoader.emit(false);
            this.setPage(1);
        })
        this.gridOptions = {

            headerHeight: 50,
            context: {
                thisComponent: this
            },
            localeTextFunc: this.globalFunctions.aggridLocaleTextFunc(),
            suppressPropertyNamesCheck: true
        };

    }

    ngOnInit() {
        this.createColumnDefs();
    }
    createColumnDefs() {

        this.columnDefs = [

            {
                headerName: '',
                width: 100,
                checkboxSelection: true,
                headerCheckboxSelection: true,
                pinned: 'left',
            },
          
            {
                headerName: "MAILINBOX.FROM",
                field: "fromPersonId",
                width: 150,
                headerClass: "cell-wrap-text",
                cellRenderer: this.commonRenderer.counseleeNameSurnameRenderer(),
                headerComponentFramework: HeaderComponent,

            },
            {
                headerName: "MAILINBOX.SUBJECT",
                field: "subject",
                width: 300,
                headerClass: "cell-wrap-text",
                headerComponentFramework: HeaderComponent,

            },
            {
                headerName: "MAILINBOX.MESSAGETYPE",
                field: "messageType",
                width: 150,
                headerClass: "cell-wrap-text",
                headerComponentFramework: HeaderComponent,

            },
            {
                headerName: "MAILINBOX.DATE",
                field: "date",
                width: 150,
                headerClass: "cell-wrap-text",
                headerComponentFramework: HeaderComponent,

            },
        ]
    }
    setPage(page: number) {
        // get pager object from service
        this.pager = this.pagerService.getPager(this.rowData.length, page);

        // get current page of items
        this.pagedItems = this.rowData.slice(this.pager.startIndex, this.pager.endIndex + 1);
    }

    onCellClicked($event) {
        setTimeout(() => {
            if ($event.colDef.headerName == "operationColumn") {
                this.selectedRows = [];
                this.gridOptions.api.deselectAll();
                this.selectedModel = $event.data;
            }

        }, 50);
    }
    onRowSelected($event) {
        this.selectedRows = this.gridOptions.api.getSelectedRows();
        if (this.selectedRows != null && this.selectedRows != undefined && this.selectedRows.length > 0) {
            this.hasSelectedRows.emit(true);
        } else {
            this.hasSelectedRows.emit(false);
        }
    }`

**Comment by imanechkikar** [comment]
Hi,
After migration to version 23,  I have the same problem.
Ps: I use Material Theme and single row selection.

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by cbpi** [comment]
did you solve this problem?

**Comment by halilpolathalil** [comment]
> did you solve this problem?

No, I am not. I solve by using cellrendererFramwork and headerRendererFrameWork. I create a template that have checkbox and indetemine checkbox. It is changes by selectedRows. İt is temporary solution until I got update to fix it

**Comment by Vladimir-Romanets** [comment]
I had the same issue. The reason was styles from project for checkboxes. All checkboxes in the project had style:
`input[type='checkbox'] {
    display: none;
}`
as a result element not clickable in the grid. Probably somebody has the same issue.

**Comment by abhi45ram** [comment]
Yes , The problem is in Global CSS(style.css). You can remove the global CSS (*) then check it will work fine
