### ISSUE TITLE
ag-grid-community.cjs.js:3574 ag-Grid: unable to find bean reference frameworkOverrides while initialising BeanStub

### ISSUE THREAD

**Issue by rduman** [ag-grid/ag-grid#3944]
Hi,
I upgrade ag-grid to 23.2.1. Everything works fine. But when I filter ag-grid then leave page, I got an error like that.
This error just appear when I use ag-grid filter and left the page. When I leave page, I destroyed RxJS.  There isn't any solve for that problem.
```

[] support request => see 'ag-grid-community.cjs.js:3574 ag-Grid: unable to find bean reference frameworkOverrides while initialising BeanStub'

  ngOnDestroy() {
    this.destroyed$.next(true);
    this.destroyed$.complete();
  }
```

**Comment by agenaille** [comment]
Possibly related to this: https://github.com/ag-grid/ag-grid/issues/3932

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4386 | Bean reference error thrown when set filter is open and grid is destroyed
-- | --

**Comment by crumhorn** [comment]
Really hope AG-4386 makes it into the next release, it's pretty much a showstopper
