### ISSUE TITLE
ag-grid Angular with headerHeight 0 is showing a top line of 1px 

### ISSUE THREAD

**Issue by carlosra85** [ag-grid/ag-grid#3945]
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

Grids with header height of 0 to hide headers is applying a min-height and height of 1px leading to a weird border in top.

https://stackblitz.com/edit/ag-grid-angular-hello-world-9av4di

This started happening in 23.0, in previous versions height and min-height was 0px.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by carlosra85** [comment]
Hi,

This is not a feature request. It is a cosmetic issue.

Thanks for the information.
