### ISSUE TITLE
First row is shown empty after moving to next or last page

### ISSUE THREAD

**Issue by gpalsingh** [ag-grid/ag-grid#3949]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
Plunker link: https://plnkr.co/edit/JlAo05cz5DYF4zAJ

**Current behavior**
After navigating to the last page, the first row shows empty. The rows shown are correct but there is that extra empty row at the top.

**Expected behavior**
The last page does not show the empty row, just like other pages

**Please tell us about your environment:**
Framework: Angular

* **ag-Grid version:** 22.1.1
Also checked with 23.2.1

* **Browser:**
Chrome/83.0.4103.116

* **Language:** TypeScript 3.2.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for your email. We have reproduced this issue and entered in our backlog:
AG-4427 Calling ResetRowHeight when using column flex, paging and row auto-height blanks out the top row on every page

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

However, there's a way to address this issue for the time being using the workaround illustrated here, removing the call to api.resetRowHeights() in onColumnResized:
https://plnkr.co/edit/32Px7Xfk9lNDnzFv

Thank you.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4427 Calling ResetRowHeight when using column flex, paging and row auto-height blanks out the top row on every page
