### ISSUE TITLE
Tooltip does not disappear from edited cell

### ISSUE THREAD

**Issue by bholdt** [ag-grid/ag-grid#3956]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behaviour**
- Edit any cell that has a tooltip defined
- While in edit mode, hover over the cell
- The tooltip is displayed
- Press Enter to confirm the edit
- The tooltip does not disappear

**Expected behaviour**
- The tooltip should disappear once you finished editing and mouse is not hovering over it anymore

**Current environment**
* **ag-Grid version:** 23.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

* **Language:** es6

![edit-tooltip](https://user-images.githubusercontent.com/1607579/87272807-ad90f000-c51a-11ea-882a-dbda82d97cf0.gif)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:
AG-4422 Custom tooltip doesn't disappear when pressing ENTER to finish editing the cell
