### ISSUE TITLE
select list display issues with aligned grids in recent updates

### ISSUE THREAD

**Issue by faintpixel** [ag-grid/ag-grid#3958]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I've noticed that recent updates seem to have caused issues with agSelectCellEditor and agRichSelectCellEditor displaying with aligned grids.

In a scenario where you have two grids, one acting as a footer and the main grid containing one of those two dropdown editors:

**Expected behavior:** The options should display over top of the footer grid like this:
![image](https://user-images.githubusercontent.com/1030687/87337576-e58b3980-c500-11ea-9ea0-f9c036c50b19.png)

(note this is how it behaves with version 22.1.0 on angular 8 - [see this stackblitz for example](https://stackblitz.com/edit/aggrid-olderversiontest))

**Current behavior:** The bottom grid is displaying over top of the select options like this:
![image](https://user-images.githubusercontent.com/1030687/87337290-73b2f000-c500-11ea-9417-2310d312cc38.png)

This is happening in version 23.2.1 on angular 10. [Example stackblitz here.](https://stackblitz.com/edit/aggrid-angular10-alignedgridoverlap)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue: 

AG-3614 - Popups are clipped by the grid.

In the meantime, it is possible to workaround this issue using the popup parent grid option, more information about this can be found in our docs, [here](https://www.ag-grid.com/javascript-grid-context-menu/#popup-parent)
