### ISSUE TITLE
ag-grid is not compartible to TypeScript 3.9 (build error)

### ISSUE THREAD

**Issue by DOrlov77** [ag-grid/ag-grid#3966]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I switch my project to use Typescript v3.9.6 after v3.7.3
At the start of TS 3.9 all [properties of CSSStyleDeclaration like msUserSelect were "unprefixed"](https://github.com/microsoft/TypeScript/pull/37616/files#diff-46fd87925e4552c166ec188712741c3fL3055)

Any idea of workaround for this issue?!?

**Current behavior**
compilation fails with set of errors like:
```
ERROR in ../node_modules/ag-grid-community/src/ts/headerRendering/horizontalResizeService.ts:58:52 - error TS2551: Property 'msUserSelect' does not exist on type 'CSSStyleDeclarati
on'. Did you mean 'userSelect'?

58         this.oldMsUserSelect = this.eGridDiv.style.msUserSelect;
                                                      ~~~~~~~~~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:3057:5
    3057     userSelect: string;
             ~~~~~~~~~~
    'userSelect' is declared here.
```

**Expected behavior**
compilation is OK!

**Please tell us about your environment:**
Windows 10
IntelliJ

* **ag-Grid version:**
all versions

* **Browser:**
no matter

* **Language:**
TypeScript 3.9

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by DOrlov77** [comment]
In case it could help to somebody, my workaround is here:
https://stackoverflow.com/a/62988875/2838615

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3390 - although this ticket is still open the actual issue the user is having has been resolved
