### ISSUE TITLE
row hover action

### ISSUE THREAD

**Issue by sangse0911** [ag-grid/ag-grid#3971]
Hi everyone.
I have problem with ag-grid, i want get hover row when mouseover in vue but i can't find method which do it. In document, i find method getFocusedCell but it does't working until click to row and always return it.

**Comment by sankita15** [comment]
I also want the same hover part on ag grid table rows, i did it using css.
There is a class in ag-grid **ag-row-hover** using which i added the hover on the row

`.ag-row-hover 
  {
    background-color: rgba(221, 0, 49, 0.05);
  }`

**Comment by sangse0911** [comment]
thank you
