### ISSUE TITLE
Column header menu button missing in iPad 

### ISSUE THREAD

**Issue by rki-financial-com** [ag-grid/ag-grid#3984]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://plnkr.co/edit/qAoNUuL22XxPxgDg?preview

The Column menu button is missing in Ipad (safari and chrome) but works in desktop devices. 
_screenshot - Ipad safari_
![eMenu-1](https://user-images.githubusercontent.com/65542211/88542557-3c7e2c00-d034-11ea-93a8-e35683f1e422.PNG)

**Expected behavior**
Column menu should be accessible in Ipad
_screenshot - mac safari_
![eMenu-desktop](https://user-images.githubusercontent.com/65542211/88542674-6cc5ca80-d034-11ea-8e0c-4c8ad213da6f.PNG)

**Please tell us about your environment:**
Ipad pro 2018, IpadOS

* **ag-Grid version:** X.X.X
ag-grid-vue@23.2.0

* **Browser:**
Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by gportela85** [comment]
menu can be open on iPad by using `longpress` or by setting `suppressMenuHide: true` in the gridOptions.
see: https://www.ag-grid.com/javascript-grid-properties/
