### ISSUE TITLE
Using a function with cellClass does not update properly when filters are applied

### ISSUE THREAD

**Issue by benlesh** [ag-grid/ag-grid#3985]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

### Current behavior

If you use a function for `cellClass` on a `ColDef` passed to `columnDefs`, and the user changes a filter, not all of the cells update, and therefor their CSS classes do not update.

This means if you want to change the background of a cell based off of whether or not it was in a filtered column, you cannot do so reliably, as only a few of the cells will actually have their CSS classes updated.

[See reproduction here](https://codesandbox.io/s/aggrid-cellclass-broken-x4ogn-x4ogn?file=/src/App.tsx)

![ag-grid-borked](https://user-images.githubusercontent.com/1540597/88575211-1db67000-d009-11ea-9b4e-0b60dce2a7b3.png)

AFAICT, this is in any usage of ag-grid and not just with React.

### Expected behavior

If a function is used for `cellClass`, the cellClass function must be recalculated when filters change and all of the relevant cells must be updated.

* **ag-Grid version:** 23.2.1 and lower

**FWIW**: I work for an agGrid customer, but I don't have the Zendesk information, and this seems more like something that should be taken care of in public, as it will affect all users of ag-grid (I like open source).

**Comment by benlesh** [comment]
The goal of what I was doing was to highlight filtered columns, as our users sometimes miss the small icon, unfortunately, I can't get this to work. Workarounds are appreciated.

**Comment by LouisMoore-agGrid** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for your contacting us.

We looked into this scenario and built a sample to help you implement the desired behavior - just redraw the rows in onFilterChanged as shown below:
https://codesandbox.io/s/aggrid-cellclass-broken-x4ogn-ll528

Please use the sample above to implement this and let me know if you have any questions.

Regards,
Kiril
