### ISSUE TITLE
Lacking reliable way to get SetFilter values for custom floating filters

### ISSUE THREAD

**Issue by fgblomqvist** [ag-grid/ag-grid#3988]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
As can be seen here: https://www.ag-grid.com/javascript-grid-floating-filter-component/
IFloatingFilterParams does not provide the values for the parent SetFilter (assuming one is dealing with SetFilters). Since they're not passed in as a prop, the only way to get them is to query the parent filter through e.g.
```ts
parentFilterInstance((instance: IFilterComp) => {
  setOptions((instance as SetFilter).getValues());
});
```
The issue with this approach is that you obviously can't know when the values have been populated (e.g. if you're using an async function in `ColDef.filterParams.values` to specify the available values). Therefore, you're left doing it a bit randomly, or very on-demand, to ensure that your custom filter has the up-to-date values (just to clarify, I am not talking about the selected values, but rather the complete list of available options).

**Expected behavior**
The best way by far to solve this is to pass the values as a prop, e.g. as a part of IFloatingFilterParams. That will ensure that any custom floating filters always has the up-to-date list and that they won't have to re-render or do logic in unnecessarily. This is not a feature, but rather a fix, since this is very important in order to properly create a custom floating filter for SetFilters.

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
