### ISSUE TITLE
Cell renderer unit tests are failing in vue after upgrade to version 23.2

### ISSUE THREAD

**Issue by jijojames18** [ag-grid/ag-grid#3996]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
We are using ag-grid as part of our Vue project. Recently we upgraded from version `20.2` to` 23.2` and from then onwards, the cell renderer unit tests are failing. We use jest for unit testing.
Upon analysis, it seems that the cell renderers are not being created and mounted in the test environment, and in its place, an empty string is being rendered.

We created a sample application with a test as described in the documentation of ag-grid which can be found at repository [ag-grid-test](https://github.com/jijojames18/ag-grid-test). The `master` branch has version `23.2` and the only other branch `ag-grid-version-20.2` has ag-grid version` 20.2`. Switch between the branches and try running the unit test after executing npm i

**Current behavior**
The same test fails in the latest version even though the test and code are the same because the cell renderers are not being created and mounted in the test environment,

**Expected behavior**
The test should pass in all versions

**Please tell us about your environment:**
Node: v10.14.2
All other dependencies can be found at [package.json](https://github.com/jijojames18/ag-grid-test/blob/master/package.json)

**ag-Grid version:**
23.2.1

**Browser:**
N.A

**Language:**
all

**Comment by jijojames18** [comment]
Reopening https://github.com/ag-grid/ag-grid/issues/3954

**Comment by jijojames18** [comment]
In that ticket, the person responsible had specified to create a `plunkr` from the official documentation. Since this issue is from a unit testing perspective, I was unable to find any viable plunks from the documentation containing jest.

**Comment by jijojames18** [comment]
To reiterate to make it absolutely clear, we are using ag-grid community in Vue to generate a grid with a cell renderer.
The code for the grid and cell renderer is shown below.
```
<template>
  <div>
    <ag-grid-vue
      style="width: 100%; height: 400px;"
      class="ag-theme-alpine"
      id="myGrid"
      :gridOptions="gridOptions"
      :columnDefs="columnDefs"
      :rowData="rowData"
      :context="context"
      :frameworkComponents="frameworkComponents"
      :defaultColDef="defaultColDef"
    ></ag-grid-vue>
  </div>
</template>

<script>
import Vue from "vue";
import { AgGridVue } from "ag-grid-vue";
import SquareRenderer from "./SquareRenderer";
export default {
  name: "App",
  data() {
    return {
      gridOptions: null,
      gridApi: null,
      columnApi: null,
      columnDefs: null,
      rowData: null,
      context: null,
      frameworkComponents: null,
      defaultColDef: null,
    };
  },
  components: { AgGridVue },
  beforeMount() {
    this.gridOptions = {};
    this.columnDefs = [
      {
        headerName: "Square",
        field: "value",
        cellRenderer: "squareRenderer",
        editable: true,
        colId: "square",
        width: 150,
      },
    ];
    this.rowData = (() => {
      var rowData = [];
      for (var i = 0; i < 5; i++) {
        rowData.push({
          row: "Row " + i,
          value: i,
          currency: i + Number(Math.random().toFixed(2)),
        });
      }
      return rowData;
    })();
    this.context = { componentParent: this };
    this.frameworkComponents = {
      squareRenderer: Vue.extend(SquareRenderer),
    };
    this.defaultColDef = {
      editable: true,
      sortable: true,
      flex: 1,
      minWidth: 100,
      filter: true,
      resizable: true,
    };
  },
  mounted() {
    this.gridApi = this.gridOptions.api;
    this.gridColumnApi = this.gridOptions.columnApi;
  },
  methods: {},
};
</script>
```
The cell renderer

```
<template>
  <div>
    <span class="test">{{ value }}</span>
  </div>
</template>

<script>
export default {
  data: function() {
    return {
      value: null,
    };
  },
  beforeMount() {},
  mounted() {
    this.value = this.valueSquared();
  },
  methods: {
    valueSquared() {
      return this.params.value * this.params.value;
    },
  },
};
</script>
```

**Comment by jijojames18** [comment]
And the unit test written is jest
```
import { mount } from "@vue/test-utils";
import App from "../../src/App.vue";

describe('APP.vue', () => {
  it('Test cell renderers', async () => {
    let wrapper = mount(App);
    await wrapper.vm.$nextTick();
    expect(wrapper.find(".ag-header-cell").exists()).toBeTruthy();
    const cells = wrapper.findAll('.ag-cell-value');
    expect(cells.at(1).text()).toEqual("1");
  })
})
```

The dependencies we are using is
```
"dependencies": {
    "ag-grid-community": "^23.2.1",
    "ag-grid-vue": "^23.2.1",
    "babel-core": "^7.0.0-bridge.0",
    "core-js": "^3.6.5",
    "jest-canvas-mock": "^2.2.0",
    "jest-environment-jsdom": "^26.1.0",
    "jest-serializer-vue": "^2.0.2",
    "jest-transform-stub": "^2.0.0",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-property-decorator": "^9.0.0"
  }
```

**Comment by jijojames18** [comment]
The unit tests run in version `20.2` and not in `23.2`

**Comment by LouisMoore-agGrid** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

We've looked at the issue you've raised and have created a repository here:

https://github.com/LouisMoore-agGrid/vueJS-Jest-ag-Grid-cell-renderer-testing

This shows how we can work around this issue. The reason it occurs is due to the grids animation frames, so suppressing this using the suppressAnimationFrame grid option solves the issue, alternatively, we can add a short setTimeout (10 ms) to the test to allow it to run when the cell renderer has rendered the value.

Hope this helps.
