### ISSUE TITLE
Allow cellRenderer to define tooltip

### ISSUE THREAD

**Issue by jpike88** [ag-grid/ag-grid#3999]
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'

My cellRenderer contains logic on init, which generates the tooltip contents.

Having to set the tooltip as a separate property doesn't make sense

**Comment by jiangyh1024** [comment]
as far as i'm concerned, you can create a cellrenderer component and pass your tooltip to the renderer component
like 
```
cellrendereSelector: params => {
  return  {
   component: "your cell renderer",
params: {  tooltip: "your tooltip"  }
 }
}

```
and in your cell renderer component, apply the tooltip

**Comment by jpike88** [comment]
Yep I think that's the only way. It's a shame because I'm moving to cellRenderer from angular components and they had everything nice and tidy including tooltip logic in one place.

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
