### ISSUE TITLE
Uncaught TypeError with unmanaged dragging between grids

### ISSUE THREAD

**Issue by spencercw** [ag-grid/ag-grid#4000]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When dragging between grids using unmanaged dragging, the following error occurs when a row is dragged over the target grid:

```
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at n.onDragEnter (ag-grid-community.cjs.js:26688)
    at n.enterDragTargetIfExists (ag-grid-community.cjs.js:17397)
    at n.onDragging (ag-grid-community.cjs.js:17383)
    at t.onCommonMove (ag-grid-community.cjs.js:31133)
    at t.onMouseMove (ag-grid-community.cjs.js:31150)
    at HTMLDocument.listener (ag-grid-community.cjs.js:31073)
```

Which maps to [this line](https://github.com/ag-grid/ag-grid/blob/066683a1cd707906435b03178178522020bfa2a9/community-modules/core/src/ts/gridPanel/rowDragFeature.ts#L144). `getRowNodes` is returning `draggingEvent.dragItem.rowNodes` which is undefined. As far as I can tell, `rowNodes` is usually populated [here](https://github.com/ag-grid/ag-grid/blob/066683a1cd707906435b03178178522020bfa2a9/community-modules/core/src/ts/gridPanel/rowDragFeature.ts#L195), but this is obviously not invoked for unmanaged dragging.

This behaviour can be reproduced with [this example](https://www.ag-grid.com/javascript-grid-row-dragging-to-grid/#example-two-grids-with-drop-position) by removing `rowManagedDrag: true` from the source grid.

**Expected behavior**

Error should not occur.

**Please tell us about your environment:**

Windows 10. IntelliJ. React. npm. Tomcat.

* **ag-Grid version:** 23.2.1

* **Browser:** Chrome 84: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"

* **Language:** TypeScript 3.7.2

**Comment by spencercw** [comment]
Possibly related to this issue in the pipeline, I can't see the details though:
AG-4442 Unmanaged RowDragging with SSRM throws exceptions in console

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:  
AG-4222 -  [Drag & Drop] Allow drag and drop between Grids to work with Unmanaged Drag

**Comment by spencercw** [comment]
Great, thank you.
