### ISSUE TITLE
Pivot chart (line) does not show correct labels when using server-side model

### ISSUE THREAD

**Issue by BarCatFigaro** [ag-grid/ag-grid#4010]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Steps to reproduce**

See: https://plnkr.co/edit/iF967bbKMFmV7vv8

1. Expand one or more groups
2. Bring up the context menu (by right clicking on a cell)
3. Select 'Pivot Chart' and 'Line' chart type

**Current behavior**
When using the server-side model, notice the category axis labels overflow into each other and the pivot lines are incorrectly labeled without the pivot groups (also shown in the legend).

![ag_pivot](https://user-images.githubusercontent.com/22532640/89667560-588e9280-d8aa-11ea-8d11-98b6869c252b.PNG)

**Expected behavior**
Should correctly display the labels, similar to when using the client-side model. See: https://www.ag-grid.com/javascript-grid-charts-integrated-pivot-chart/pivot-chart.gif for reference.

* **ag-Grid version:** 23.2.1

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

* **Language:** [all]

**Comment by LouisMoore-agGrid** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-3559: [Charts] Allow rotating the group labels
