### ISSUE TITLE
`data` is missing from props

### ISSUE THREAD

**Issue by areisle** [ag-grid/ag-grid#4027]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
on first render, the `data` prop is missing from `ICellRendererParams` if `field` doesn't match a key in data
https://plnkr.co/edit/ZIQjjidQP6xpD6MH?preview

**Expected behavior**
that the `data` props is always there

**Please tell us about your environment:**

* **ag-Grid version:** 23.2.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0

* **Language:** all

**Comment by LouisMoore-agGrid** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for your message. We are aware of this issue and have it stored in our backlog.

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-4532: On first render, the data prop is missing from ICellRendererParams if field doesn't match a key in data

**Comment by areisle** [comment]
I tried looking up AG-4532 in https://www.ag-grid.com/ag-grid-pipeline/ but I didn't get any results. is it possible that's the wrong issue key?
