### ISSUE TITLE
Blazor Support

### ISSUE THREAD

**Issue by manthena** [ag-grid/ag-grid#4029]
Are there any plans to release a wrapper for [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)? Its very similar to Angular and React frameworks. It would be very helpful to Microsoft developer community if ag-grid supports Blazor!

**Comment by LouisMoore-agGrid** [comment]
Hi,

We don't currently have any plans to add a wrapper for Blazor. However, we may reconsider this in the future depending on the popularity of this framework.
