### ISSUE TITLE
AgGridReact: Unable to use containerStyle property in Typescript

### ISSUE THREAD

**Issue by nicodeslandes** [ag-grid/ag-grid#4032]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I'm having issue using `AgGridReact` in Typescript. I'm attempting to use the `containerStyle` property of the `AgGridReact` component, in order to remove the `{height: 100%}` style on the enclosing div of the grid:

```jsx
<div className="ag-theme-balham">
    <AgGridReact
        rowSelection={'single'}
        columnDefs={this.columnDefs}
        rowData={this.state.items}
        domLayout='autoHeight'
        containerStyle={{height: 'auto'}}>
    </AgGridReact>
</div>
```
 
(here's a working plunkr for the JS version: https://embed.plnkr.co/plunk/4FXvqJ8ZuhMs7XLw, showing that indeed this `containerStyle` property does exist and work as expected)

**Expected result:** The code above should compile
**Actual result:** The compilation fails with the following error:
```
      TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<AgGridReactProps>): AgGridReact', gave the following error.
    Type '{ children: never[]; rowSelection: string; enableCellTextSelection: true; suppressCellSelection: true; columnDefs: ColDef[]; rowData: Commission[]; onRowSelected: (event: RowSelectedEvent) => void; frameworkComponents: { ...; }; domLayout: string; componentWrappingElement: string; containerStyle: { ...; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridReact> & Readonly<AgGridReactProps> & Readonly<...>'.
      Property 'containerStyle' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridReact> & Readonly<AgGridReactProps> & Readonly<...>'.
  Overload 2 of 2, '(props: AgGridReactProps, context?: any): AgGridReact', gave the following error.
    Type '{ children: never[]; rowSelection: string; enableCellTextSelection: true; suppressCellSelection: true; columnDefs: ColDef[]; rowData: Commission[]; onRowSelected: (event: RowSelectedEvent) => void; frameworkComponents: { ...; }; domLayout: string; componentWrappingElement: string; containerStyle: { ...; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridReact> & Readonly<AgGridReactProps> & Readonly<...>'.
      Property 'containerStyle' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridReact> & Readonly<AgGridReactProps> & Readonly<...>'.
```

The problem is that the `containerStyle` property is missing from the `GridOption` interface in the type definition file for it.

Here's a StackBlitz example that shows the typescript error (on line 60):
https://stackblitz.com/edit/react-typescript-start-emge29?file=index.tsx

* **ag-Grid version:** 23.2.1

* **Language:** Typescript (any version, but I'm using 3.9.7)

**Comment by nicodeslandes** [comment]
For those hitting this problem, here's a workaround until the type definition file can be updated:

Add the following declaration at the top of you typescript file:

```ts
import { AgGridReactProps } from 'ag-grid-react';

declare class AgGridReact extends React.Component<AgGridReactProps & {containerStyle: any}, {}> {}
```

You can then use the missing `containerStyle` property:

```tsx
<div className="ag-theme-balham">
    <AgGridReact
        rowSelection={'single'}
        columnDefs={this.columnDefs}
        rowData={this.state.items}
        domLayout='autoHeight'
        containerStyle={{height: 'auto'}}>
    </AgGridReact>
</div>
```

**Comment by seanlandsman** [comment]
Thanks for raising this - I've added the missing property and this change will be available in our next release, currently scheduled for sometime next week.

thanks

**Comment by nicodeslandes** [comment]
> I've added the missing property and this change will be available in our next release

That's great, thanks for the quick turnaround!
