### ISSUE TITLE
Property 'rowModel' is private and only accessible within class 'GridApi'.

### ISSUE THREAD

**Issue by andrejm7** [ag-grid/ag-grid#4038]
Property 'rowModel' is private and only accessible within class 'GridApi'.

this.agGrid.api.rowModel.rowsToDisplay.forEach(e => {

please update rowModel for public...

**Comment by LouisMoore-agGrid** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Please use the public method getModel(), more details on this method can be found here:
https://www.ag-grid.com/javascript-grid-api/
