### ISSUE TITLE
Dynamic tooltip will not show if it is initially blank

### ISSUE THREAD

**Issue by 2wheels4** [ag-grid/ag-grid#4039]
When a new cell component is being created, the managed bean for the tooltip will only be created if the cell has a tooltip. I am using a tooltipValueGetter that returns a different value depending on the value in the cell to show edits or error messages after a cell has been edited. When the table is first loaded, the cells will have blank tooltips. I think the below line should be changed so a manged tooltip bean is created if there is a tooltip or tooltipValueGetter is set on the column definition.

https://github.com/ag-grid/ag-grid/blob/066683a1cd707906435b03178178522020bfa2a9/community-modules/core/src/ts/rendering/cellComp.ts#L221

**Comment by 2wheels4** [comment]
Proposed solution in https://github.com/ag-grid/ag-grid/pull/4040

**Comment by lbwexler** [comment]
+1

**Comment by gportela85** [comment]
@2wheels4 this issue has been fixed in the latest branch, thanks for reporting it.
