### ISSUE TITLE
Bug/Regression v.23.2.1 with Filter Api: error unable to find bean reference frameworkOverrides while initialising BeanStub

### ISSUE THREAD

**Issue by AlixRoyere** [ag-grid/ag-grid#4054]
**I'm submitting a ...** 
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

This concerns an aggrid enterprise feature.

**Providing a Reproducible Scenario**
Live example:
[https://stackblitz.com/edit/ag-grid-angular-issue-frameworkoverrides-while-initialising-etc](https://stackblitz.com/edit/ag-grid-angular-issue-frameworkoverrides-while-initialising-etc)

Steps:
- Open the browser console
- Ignore error due to invalid enterprise license or put yours in main.ts
- Filter the grid with custom filter (achieved in the example by clicking on the button)
- Root to another page (achieved in the example by clicking on the link)
- See "ag-Grid: unable to find bean reference frameworkOverrides while initialising BeanStub" in the console

**Current behavior**
Error "ag-Grid: unable to find bean reference frameworkOverrides while initialising BeanStub" showing in console when using custom filtering and leaving the grid, in aggrid version 23.2.1

**Expected behavior**
No error in console, as in aggrid version 23.0.0

**Please tell us about your environment:**

* **ag-Grid version:** 23.2.1 (this works fine in 23.0.0)

* **Browser:**
Firefox, Chrome

* Angular 10

EDIT: that works fine in 23.1.0 too

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hello!

Thank you for the context you provided so far - this really helps us understand your requirements.

This has been raised before, and we are already tracking it in our pipeline with the following reference and description:

AG-4386 | Bean reference error thrown when set filter is open and grid is destroyed

Note that this is part of the next release and it is scheduled in the next 2 weeks.

You can check whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Thanks again for bringing this up with us.

Regards,
Shuheb‍
Developer | ag-Grid
