### ISSUE TITLE
PR Review?

### ISSUE THREAD

**Issue by pdemro** [ag-grid/ag-grid#4064]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
[x] question
```

I have opened a few PRs but they have been stuck in "stale" for months now.  Is this the proper channel to open PRs for AG-Grid?  One is a simple documentation update.

**Comment by makinggoodsoftware** [comment]
Hi,

Apologies for that! Let me raise this, we will let you know as soon as possible!

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

The PRs are now being considered for merging. they are tracked by:


You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-4607 [Docs] Update NPMJS installation instructions to point to ag-grid-community
AG-4608 Add ascii_only flag for terser options to support UTF-8 restrictions
