### ISSUE TITLE
Providing default filterParams causes per column filterParams to be shared for all columns

### ISSUE THREAD

**Issue by miiihi** [ag-grid/ag-grid#4066]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://plnkr.co/edit/HKd9D6cDaFLHRimM

Only added `filterParams: {}` to the `defaultColDef`, causing both columns to have same filter values...

**Current behavior**

If one provides filterParams in the defaultColDef and then provides additional filterParams config per column, these additional filterParams get shared/applied to all columns. Observable with agSetFilter. (possibly also with others?)

**Expected behavior**

filterParams config per column should not get shared/applied to all columns.

**Please tell us about your environment:**

* **ag-Grid version:** 24.0.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ceolter** [comment]
Thanks for raising. Looking into this now. I've create a JIRA to track, AG-4597

You can follow the status of feature requests, bugs and releases here:
https://www.ag-grid.com/ag-grid-pipeline/
(Note that newly raised issues can take up to 2 hours to appear)

As this is now tracked internally, closing this Github issue.

**Comment by miiihi** [comment]
On a deeper inspection, fix is simple:
'filterParams' has to be added to the COL_DEF_PARAM_OBJECTS array in community-modules/core/src/ts/entities/colDef.ts

Hopping for a quick fix and release, as I see this as critical bug!
