### ISSUE TITLE
aggrid vertical scroll issue in rtl

### ISSUE THREAD

**Issue by reza3vi** [ag-grid/ag-grid#4067]
when CSSOM View Scroll Coordinates is enabled in chrome

**Comment by gportela85** [comment]
@reza3vi Please, when describing an issue, also provide an example and details on how to reproduce the issue.

Even though ag-Grid doesn't support Chrome Experimental Flags, I did enable the `CSSOM View Scroll Coordinates` tried the demo: www.ag-grid.com/example.php?rtl=true

Everything worked fine as far as I could tell..

**Comment by reza3vi** [comment]
> @reza3vi Please, when describing an issue, also provide an example and details on how to reproduce the issue.
> 
> Even though ag-Grid doesn't support Chrome Experimental Flags, I did enable the `CSSOM View Scroll Coordinates` tried the demo: [www.ag-grid.com/example.php?rtl=true](http://www.ag-grid.com/example.php?rtl=true)
> 
> Everything worked fine as far as I could tell..

https://github.com/ag-grid/ag-grid/issues/2914
