### ISSUE TITLE
Grid does not respect column order

### ISSUE THREAD

**Issue by sdbrannum** [ag-grid/ag-grid#4070]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/p8K3XpaQbqT4qUpt

1. Toggle between Include/Exclude age column
2. "t" column is out of order

Reproduction is direct copy from [this example](https://www.ag-grid.com/javascript-grid-column-updating-definitions/) with an added valueGetter column.

**Current behavior**

Grid does not respect column position when setting columns through `gridApi.setColumnDefs`.

**Expected behavior**

Grid respects column position

* **ag-Grid version:** 24.0.0

* **Browser:** All browsers

* **User Agent:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"

* **Language:** all

**Comment by ceolter** [comment]
thanks for raising, on my list to check out.

**Comment by ceolter** [comment]
you need an ID for the column.

see this plunker
https://plnkr.co/edit/WRIe3Rx2k71tttGI

when you only have a value getter, the column cannot be matched, so the grid doesn't realise it's a difference column

see
https://www.ag-grid.com/javascript-grid-column-updating-definitions/#matching-columns
