### ISSUE TITLE
Docs have incorrect examples around applyColumnState for default

### ISSUE THREAD

**Issue by benjaffe** [ag-grid/ag-grid#4075]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

From https://www.ag-grid.com/javascript-grid-column-state/#applying-partial-state , when I copy examples with defaultState, the types seem wrong. According to the type definitions, defaultState is _not_ an array, it's a single object. So:

```
// Clear sorting on all columns, leave all other attributes untouched
columnApi.applyColumnState({
    defaultState: [
        {
            // important to say 'null' as undefined means 'do nothing'
            sort: null
        }
    ]
});
```

is incorrect according to the types... this is what seems to work, and what the docs should probably be updated to reflect:

```
// Clear sorting on all columns, leave all other attributes untouched
columnApi.applyColumnState({
    defaultState: {
        // important to say 'null' as undefined means 'do nothing'
        sort: null
    }
});
```

Note that multiple examples on the linked page have this issue. I haven't audited other docs pages looking for this.

Thank you all for an incredible piece of software. <3

**Comment by ceolter** [comment]
thanks for raising, on my list to check out.

**Comment by ceolter** [comment]
fixed
https://github.com/ag-grid/ag-grid/commit/25177dd78eb071fe181eee040e68a9c8f9d1c7a4

**Comment by ceolter** [comment]
website will update on next release
