### ISSUE TITLE
Missing onComponentStateChanged Typings in ag-grid-react

### ISSUE THREAD

**Issue by utsavkapoor** [ag-grid/ag-grid#4084]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
Typings are missing for onComponentStateChanged from GridOptions

https://www.ag-grid.com/javascript-grid-events/
componentStateChanged ==> onComponentStateChanged

https://codesandbox.io/s/ag-grid-missing-typings-lipd7

**Current behavior**
Typescript error when adding onComponentStateChanged in AgGridReact

**Expected behavior**
No Typescript Errors

* **ag-Grid version:** 23.2.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for this!

This will be manually merged in the next release.
