### ISSUE TITLE
[popup] Filter is hidden when wrapping div is smaller than its height

### ISSUE THREAD

**Issue by chiptus** [ag-grid/ag-grid#409]
As you can see in the screenshot when the wrapping div of the grid is smaller than the height of the filter, some of it disappears. Probably something with css...
![image](https://cloud.githubusercontent.com/assets/1381655/9568728/f89a87cc-4f5a-11e5-84bb-30932d2a9677.png)

**Comment by chiptus** [comment]
changing .ag-filter-list-viewport height did help, but I wonder if there's a way to make it appear outside of the box, or otherwise have a height relative to the grid height and not fixed (200px)

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-62

**Comment by britvik** [comment]
Any progress on this? It's quite an issue in smaller grids.

Also adding a reference to duplicate issue, so you can close 2 issues when you fix this (isn't that worth it? :-) ) https://github.com/ag-grid/ag-grid/issues/1448

As inspiration you can look at angular material select component, which appends its options list to body and sets absolute position to it. Same approach should be used here as well.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
