### ISSUE TITLE
How to know when rendering has finished?

### ISSUE THREAD

**Issue by goloroden** [ag-grid/ag-grid#4090]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

Basically, I have a pretty trivial question: I know that I can use the `gridReady` event to wait for the API to become ready (alternatively, I can write a function that polls for this, as [suggested here](https://www.ag-grid.com/javascript-grid-testing-react/#waiting-for-the-grid-to-be-initialised)).

Now, my question is similar to this, but it's not about the API itself: Supposed I make a change that leads to re-rendering – how do I know when the grid has been rendered? Apparently, there is no event for that, and there is also not a callback or a promise available I can use. Is there any way to solve this in an elegant way (with *elegant* I do not mean something such as *use setTimeout to wait for X ms, then rendering will probably have happened*).

Any thoughts on this? Am I missing something here?

PS: The reason I'm asking is because I would like to write a test that does some things such as setting a filter, and then check the DOM whether it has been updated correctly. AFAICS this is not possible without waiting, however, the question is how long you have to wait?

**Comment by devdeepdive** [comment]
There are tons of events fired by ag-grid (almost too many lol). When you say you "make a change," what kind of change are you making specifically? There's modelUpdated, rowDataChanged, and more. I assume you've looked through https://www.ag-grid.com/javascript-grid-events/. There are some events not documented there but mentioned elsewhere in the documentation. You could look through https://github.com/ag-grid/ag-grid/blob/master/dist/lib/entities/gridOptions.d.ts for a more complete list.
Since you mentioned filtering, there are onFilterChanged and onFilterModified.

**Comment by GerryLau** [comment]
Same here, it seems like ag grid does not have that after so many years the product went live.  I wanted to update my total row after the grid completed adding my new rowData but I could not find a callback to do that.

**Comment by GerryLau** [comment]
@ahbirdbby I found that onRowDataUpdated could solve my problem.  Hope it helps you too!

**Comment by JackLeEmmerdeur** [comment]
@GerryLau Thanks. That seems to be the only solution. I thought it would be onFirstDataRendered, but that event seems to not fire at all. With onRowDataUpdated a boolean flag is needed for making it the only fire one time:

```
let ready = false;

let gridOptions = {
	onRowDataUpdated: () => {
		if (!ready) {
				ready = true;
		}
	}
};
```

**Comment by magmaliang** [comment]
Here is a solution for serverSide model(well , a lot of time to read the code and doc):
```js
// api is agGrid api
Api.addEventListener("storeUpdated", (e) => {console.log(e)})
```

`storeUpdated` event triggered after every block of data turns to rowNodes.  Origin code as following:
```js
PartialStore.prototype.onBlockLoaded = function (block, params) {
        this.logger.log("onPageLoaded: page = " + block.getId() + ", lastRow = " + params.rowCount);
        if (params.storeInfo) {
            _.assign(this.info, params.storeInfo);
        }
        if (!params.rowData) {
            var message_1 = 'AG Grid: "params.rowData" is missing from Server-Side Row Model success() callback. Please use the "rowData" attribute. If no data is returned, set an empty list.';
            _.doOnce(function () { return console.warn(message_1, params); }, 'InfiniteStore.noData');
        }
        var finalRowCount = params.rowCount != null && params.rowCount >= 0 ? params.rowCount : undefined;
        // if we are not active, then we ignore all events, otherwise we could end up getting the
        // grid to refresh even though we are no longer the active cache
        if (!this.isAlive()) {
            return;
        }
        this.checkRowCount(block, finalRowCount);
        block.setData(params.rowData);
        // if the virtualRowCount is shortened, then it's possible blocks exist that are no longer
        // in the valid range. so we must remove these. this can happen if the datasource returns a
        // result and sets lastRow to something less than virtualRowCount (can happen if user scrolls
        // down, server reduces dataset size).
        this.destroyAllBlocksPastVirtualRowCount();
        this.fireCacheUpdatedEvent();
    };
```

**Comment by yq756530939** [comment]
I want to know how to realize too？

**Comment by StephenCooper** [comment]
Adding a note here about the `firstDataRendered` event for those that come across this ticket.

https://ag-grid.com/javascript-data-grid/grid-events/#reference-miscellaneous-firstDataRendered
