### ISSUE TITLE
agLargeTextCellEditor does not work

### ISSUE THREAD

**Issue by wanmifam** [ag-grid/ag-grid#4094]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
agLargeTextCellEditor  works on below ag-Grid version: 23.2.1
agLargeTextCellEditor doesn't work on ag-Grid version: 24.0.0
Accepted reproducible scenarios are
```javascript
{
        field: "address",
        editable: true,
        cellEditor: 'agLargeTextCellEditor',
        cellEditorParams: {
            maxLength: '300',   // override the editor defaults
            cols: '50',
            rows: '6'
        }
    }
```
- A plunker
https://www.ag-grid.com/example-runner/grid-vanilla.php?section=javascript-grid-cell-editor&example=vanilla-editor-component&enterprise=1&grid=%7B%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Atrue%7D

* **ag-Grid version:** 24.0.0

* **Browser:** Google Chrome Version 85.0.4183.121

* **Language:** all

**Comment by gportela85** [comment]
this issue has been fixed in the latest branch
