### ISSUE TITLE
Aggrid min-height set in 24.0.0

### ISSUE THREAD

**Issue by ykns** [ag-grid/ag-grid#4095]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

Current behaviour:
Found that when upgrading to v24.0.0 the min-height has now been set to 150px as demonstrated in this [sandbox](https://codesandbox.io/s/ag-grid-v2400-min-height150px-m0fuc). ![aggrid_v24 0 0](https://user-images.githubusercontent.com/1862925/94255142-af662f00-ff1f-11ea-823d-b961650e21c4.png)
Expected behaviour:
Where as in v23.2.0 there is no such min-height, shown in this [sandbox](https://codesandbox.io/s/ag-grid-v2320-no-min-height-053g9). ![aggrid_v23 2 0](https://user-images.githubusercontent.com/1862925/94255139-ae350200-ff1f-11ea-87ea-0dfe53aad867.png)

Note: Both sandboxes use the same code, only version of ag-grid was changed.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email. 

This seems to be working on our end. 

https://plnkr.co/edit/83CHKq4DgwcukSqO

As you can see there is no min-height for the grid in v24.

Please fork and reproduce the issue on your end so that we can investigate further.

Thanks

**Comment by ykns** [comment]
I left two sandbox links to demonstrate the issue, please have a look at them. I have just checked them and the issue is still present.

**Comment by nigelrmtaylor** [comment]
Hi Just to confirm, I upgraded to 24.0 yesterday and see the same issue.

It's causing problems on grids that are printed when the number of lines in the grid is small (ie. one line)

A bit of digging shows this in ag-grid.css line 220:

.ag-layout-auto-height .ag-center-cols-clipper, .ag-layout-auto-height .ag-center-cols-container, .ag-layout-print .ag-center-cols-clipper, .ag-layout-print .ag-center-cols-container {
  min-height: 150px; }

Could this be the reason?



Nigel

**Comment by nigelrmtaylor** [comment]
as a workaround, I overrode the style to be:

.ag-layout-auto-height .ag-center-cols-clipper,
.ag-layout-auto-height .ag-center-cols-container,
.ag-layout-print .ag-center-cols-clipper,
.ag-layout-print .ag-center-cols-container {
  min-height: 0px;
}

in the vue template and it seems to be ok now.

not perfect but ok as a temporary bodge

Nigel

**Comment by gportela85** [comment]
The minHeigh was always there, but it had a lesser value before. The min-height had to be increased so the "no row" / "loading overlays" would look correct with the new Alpine theme.

**Comment by ykns** [comment]
I do not see how changing the `minHeight` for one style, should impact all others. This is a very opinionated approach and effectively means we have to add extra CSS to undo it, as demonstrated by @nigelrmtaylor, and this is less than ideal.

**Comment by slawomir-brzezinski-at-clarksons** [comment]
@gportela85 

> The minHeigh was always there, but it had a lesser value before. The min-height had to be increased so the "no row" / "loading overlays" would look correct with the new Alpine theme.

Ditto @ykns . This is a regression breaking other themes (wasting a lot of real estate by pushing trailing content down and leaving a big empty square). If this is an Alpine-specific setting, wouldn't it be better to introduce in Alpine-specific CSS?

**Comment by gportela85** [comment]
@slawomir-brzezinski-at-clarksons The change was also done to accommodate other themes with higher spacing (eg. Material). And is also a one liner CSS change if you need to override it.

But you can always file a bug report with support using Zendesk.

**Comment by ykns** [comment]
@gportela85 It still doesn’t make sense to impact all other styles to solve a problem for a subset of styles. Especially, when you have means of applying CSS tweaks to these specific themes. Effectively you have just pushed the problem to our code.

**Comment by deepikagupta31** [comment]
Causing problem in existing row heights of the table after upgrading.
Had to fix it using in angular

#tableId :: ng-deep .ag-center-cols-viewport {
      min-height: 70px !important;
}
