### ISSUE TITLE
Invocation of refresh(...) method does not pass Complementary Arguments for Custom Header Component

### ISSUE THREAD

**Issue by tomwanzek** [ag-grid/ag-grid#4099]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Reproducible Scenario**

* Create an ag Grid with an  Angular header component in accordance
with https://www.ag-grid.com/javascript-grid-header-rendering/#header-component

* The parameters for this custom header component should include custom header parameter(s) which will be added to the corresponding column definition using `headerComponentParams` as per https://www.ag-grid.com/javascript-grid-header-rendering/#complementing-params.

E.g. with the following:

```typescript
export interface AdditionalParams {
  alternativeLabel: string;
}

export type CustomColumnHeaderParams = IHeaderParams & AdditionalParams;
```

we would have `headerComponentParams` of type `AdditionalParams`.

* Use the custom header in the ag Grid with the a set of initial Column Definitions including the `headerComponentParams` as per standard ag Grid Doc

* Add a means/some facility to the code that allows the column definitions to be changed, such that the column with the custom header continues to exist and its `refresh(...)` method gets invoked as a result. For extra differentiation, change the value of the `alternativeLabel` parameter in the updated column definition.

**Current behavior**

When the custom header is initialized with `agInit(..)`, the method gets is called with `params: CustomColumnHeaderParams` as documented and expected.

When the `refresh(...)` method is invoked it is called with `params: IHeaderParams`, i.e. the `AdditionalParams` are not included in the passed parameter. The only way to access them is to retrieve them indirectly through `params.column.getColDef().headerComponentParams as AdditionalParams`

**Expected behavior**

The `refresh(...)` method should be called with the same parameter data structure as `agInit(...)`. I.e. in our example above it should be called with the current `CustomColumnHeaderParams`, not just `IHeaderParams`

**Please tell us about your environment:**

MacOS Catalina 10.15.6

ag Grid used in Angular front end:
Angular CLI: 10.0.4
Node: 12.18.3
OS: darwin x64

Angular: 10.0.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cdk                      8.2.3
@angular/cli                      10.0.4
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.5.4
typescript                        3.9.7
webpack                           4.43.0

* **ag-Grid version:** 24.0.0

* **Browser:**

Issue is not browser dependent.

* **Language:** [TypeScript 3.9.7]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this issue.


We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-4666 CustomHeader refresh(...) method incorrectly called with IHeaderParams instead of the current CustomColumnHeaderParams**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

I would recommend signing up for automatic release notifications. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

For more information on when can you expect your ticket to be fixed please check:
https://ag-grid.zendesk.com/hc/en-us/articles/360002213531-Where-Is-My-Ticket-

Thanks again for bringing this up with us.

Regards,
