### ISSUE TITLE
[touch] Add cellTouched Method for Columns

### ISSUE THREAD

**Issue by leocaseiro** [ag-grid/ag-grid#410]
I'm currently using the cellDoubleClicked event, however it doesn't work on Mobile, sou I'd like to use the [ngTouch](https://docs.angularjs.org/api/ngTouch) in my mobile version.

I Know if I set only ColumnClicked, it'll work in both devices, however, I want to keep using the double click for desktop, so it seems more like a software.

I'd like to know if somebody else agree with this new feature, I'd be very happy to send a pull request.

**Comment by ceolter** [comment]
are you asking on a switch, to use cellClicked on mobile, and cellDoubleClicked on desktop?

**Comment by leocaseiro** [comment]
Yeah. I've done an if here, so might work for the time being, but it would be nice if Mobile could be click and desktop double.

Thanks.

**Comment by ceolter** [comment]
are you talking about clicking the header, ie for bringing up the filter menu?

or are you talking about clicking the cells, for editing?

**Comment by leocaseiro** [comment]
I'm talking about clicking the cells for editing. In my case, I'm calling a ngModel every Cell dbClick.

**Comment by ceolter** [comment]
so are you doing this in your app? (and looking to have the grid do this logic for you)
```
gridOptions.cellClicked = function() {
  if (onMobileDevice()) {
    doTheAction();
  }
}

gridOptions.cellDoubleClicked = function() {
  if (!onMobileDevice()) {
    doTheAction();
  }
}
```

what are you doing with the click actually? are you using the grid editing feature? or maybe you are adding a different feature (not using grid built in editors)?

**Comment by leocaseiro** [comment]
Hi @ceolter, thank you for your help.

Yeah, I'm doing pretty much like yours:

    angular.forEach($scope.columns, function(column) {
        if ( isMobile() ) {
            column.cellClicked = doAction;
        } else {
            column.cellDoubleClicked = doAction;
        }
    });

    $scope.gridOptions.columnDefs = $scope.columns;

**Comment by ceolter** [comment]
understood. will stick this on the list.

**Comment by leocaseiro** [comment]
Thanks. For the time being is working pretty well.

**Comment by leocaseiro** [comment]
For who is interested in my script:
```javascript
function isTouchDevice() {
    return (('ontouchstart' in window) || (navigator.MaxTouchPoints > 0) || (navigator.msMaxTouchPoints > 0));
}

angular.forEach($scope.columns, function(column) {
    if ( isTouchDevice() ) {
        column.cellClicked = doAction;
    } else {
        column.cellDoubleClicked = doAction;
    }
});
```

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-63

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
