### ISSUE TITLE
agLargeTextCellEditor produces <input> instead of <textarea>

### ISSUE THREAD

**Issue by robertmarshii** [ag-grid/ag-grid#4100]
When using cellEditor = "agLargeTextCellEditor" Ag-Grid creates an input with type="textarea" rather than <textarea>

v23.2.1
**<textarea** ref="eInput" class="ag-input-field-input ag-text-area-input" id="ag-input-id-1254" maxlength="200" cols="60" rows="10" spellcheck="false"></textarea> 

v24.0.0
<input ref="eInput" class="ag-input-field-input ag-text-area-input" **type="textarea"** id="ag-1254-input" maxlength="200" aria-label="Input Editor">

**Comment by gportela85** [comment]
This issue has been fixed in the latest branch. Thanks for reporting it

**Comment by adamkundrat** [comment]
When are you planning to release it? Thank you!

**Comment by jackdh** [comment]
Bump still happening on v24

**Comment by gportela85** [comment]
@jackdh did you update to 24.1? If yes, can you post a plunkr of the issue?
