### ISSUE TITLE
firstDataRendered is fired before successCallback call for infinite rowModel

### ISSUE THREAD

**Issue by Romanow88** [ag-grid/ag-grid#4108]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
- Set up a AG-grid instance to use infinite rowModel
- Set up a event handler for `firstDataRendered`
- Add console log to the event handler and a console log just before calling successCallback

See https://plnkr.co/edit/L2ae0ZBeZZK9UpqR

**Current behavior**
The `firstDataRendered` is called before the datasource calls `successCallback`

**Expected behavior**
The `firstDataRendered` should be called *after* the dataSource has called the `successCallback` for the first time.

**Please tell us about your environment:**
Win 10, Angular-cli, Angular 9

* **ag-Grid version:** 24.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

* **Language:** [all]

**Comment by Romanow88** [comment]
I found AG-3211 which relates to the server side data, maybe infinite rowmodel can be included there as well?

**Comment by makinggoodsoftware** [comment]
Hi,

The FR you mention will include this

-----

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3211 | Add server side event for onFirstDataLoaded
-- | --
