### ISSUE TITLE
Docs have typo in one of the applyColumnState code snippets

### ISSUE THREAD

**Issue by ajess33** [ag-grid/ag-grid#4109]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I noticed in the documentation for Column State there seems to be a typo in the `applyColumnState` method of the top most code snippet. [https://www.ag-grid.com/javascript-grid-column-state/](https://www.ag-grid.com/javascript-grid-column-state/)

```
// save the columns state
let savedState = columnApi.getColumnState();

// restore the column state
columnApi.applyColumnsState({ state: savedState });
```

In the second method there is an added "s" at the end of column that I don't believe should be there. Spent awhile trying to get it to work but as soon as I checked out a few more examples I noticed the working ones were using `columnApi.applyColumnState({ state: savedState });` I looked through the rest of the page and didn't see the typo in any other areas. 

Hopefully that's enough info for you!

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for pointing this! We have fixed this now in the docs, it will be fixed in our next release!

Thanks!
