### ISSUE TITLE
agsetfilter does not respond with mouse clicks

### ISSUE THREAD

**Issue by bholdt** [ag-grid/ag-grid#4117]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

using ag-grid v24. When a column has agsetfilter, clicking with the mouse on any of the items in the list of the set filter, does not check / uncheck the item and the grid is not filtered. 
Using the keyboard however (with space and tabs) does make the selection and the grid is filtered accordingly.
![setfilter](https://user-images.githubusercontent.com/1607579/95147174-5457f600-07c3-11eb-9745-b39be27646f4.gif)

**Expected behavior**

When clicking on the items in the set filter list, the checkbox is unchecked / checked and the grid is filtered

**Please tell us about your environment:**

Windows 10

* **ag-Grid version:** X.X.X

v24.0.0

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by AlixRoyere** [comment]
Hello,
Could you please provide a reproducible scenario in plunker?
I'm experiencing the same issue in 24.0.0 (and not previously) but i'm not able to reproduce it oustide my apps yet.
Thanks

**Comment by AlixRoyere** [comment]
Hello it's me again, for me it seems to be a css issue. Try to uprade your css to a 24.0.0 version. See here [https://www.ag-grid.com/javascript-grid-themes-provided/]( https://www.ag-grid.com/javascript-grid-themes-provided/)
But use href="https://unpkg.com/@ag-grid-community/all-modules@**24.0.0**/dist/styles/ag-grid.css" 
Or similarly, depending on the way you import css
Does it fix your issue?

**Comment by bholdt** [comment]
Brilliant, that is exactly what it was. Thanks for letting me know.
