### ISSUE TITLE
Column type overrides configured ColDef properties

### ISSUE THREAD

**Issue by mbs-zanas-stundys** [ag-grid/ag-grid#4118]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[ ] support request => see 'Requesting Community Support'
```
 
**Current behavior**
https://plnkr.co/edit/QzzhuJKszJMkyBDc
If column type defines `floatingComponentParams`, notice that even though the params are different for "Gold", "Silver", "Bronze", "Total" column definitions - only latter params of "Total" are provided to the floating filter component for ALL columns. Looks like removing `floatingComponentParams` from the `medal` column type fixes the issue. This is a bug, since column types override column definitions.

**Expected behavior**
Column types should allow to reuse common properties without conflicting with actual column definitions.

**Please tell us about your environment:**
OS: MacOS Catalina
IDE: VSCode 

* **ag-Grid version:** 24.0.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

* **Language:** all

**Comment by hadassegal** [comment]
This happened to me as well yesterday when I upgraded to version 24.0.0.
Specifically when I tried adding these filterParams to a specific column:

```
 filterParams: {
  defaultJoinOperator: 'OR'
}
```

the result was that the defaultColDef received this property as well, and it affected all the columns.
I mentioned my issue on the comment of [#4107](https://github.com/ag-grid/ag-grid/issues/4107)

**Comment by apexbryan** [comment]
I just ran into this as well.

I have a handful of columns with custom filterParam comparators. I have default filterParam buttons in my colDefs. When those defaults are active, the custom comparator on some columns gets applied to ALL columns, not just the ones it's defined on. Disabling the defaults fixes it and the comparators only apply to the columns they're defined on as intended.

```js
gridOptions = {
	...,
	defaultColDef: {
		resizable: true,
		enableRowGroup: true,
		enableValue: true,
		sortable: true,
		filter: true,
		floatingFilter: true,
		// Commenting out filterParams fixes it
		filterParams: {
			buttons: ["reset", "apply"]
		}
	},
}

columnDefs = [
	{
		headerName: "Column A",
		field: "column_a",
		filter: "agDateColumnFilter",
		// Default filterParams cause this to be applied to all columns
		filterParams: {
			comparator: filterDate,
		}
	},
	{
		headerName: "Column B",
		field: "column_b",
		filter: "agSetColumnFilter",
	},
	{
		headerName: "Column C",
		field: "column_c",
		filter: "agSetColumnFilter",
	}
]
```

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by apexbryan** [comment]
Just confirmed that 24.1 has fixed the issue for me. Thank you!
