### ISSUE TITLE
cellClass and cellClassRules doesn't updates

### ISSUE THREAD

**Issue by avalenti89** [ag-grid/ag-grid#4119]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I have a grid with some custom columns that had to change its values based on some calculation that looks on all rows.

Because my columnDefs is huge, I moved the definitions into another file inside a function (I need to have some props).
On mount/update/special conditions, I store the defs on my component's state, and I use it in my render,

I try to log every steps that I can (my update functions, colDefs function, etc...) and I noticed that ag-grid does not recall neither cellClass or cellClassRules, even if I try to force refresh cells using grid api.

Steps:
1. on mount fetch data and calculate a value from fetched data.
2. get colDefs from external function passing the calculated value and using it to elaborate cellClass (or cellClassRules) and store the array into component's state.
3. render the grid.
4. update the calculated value and update the colDefs.
5. force refresh cells.

NB:
- Use arrow function.

**Expected behaviour**
The grid should refresh and call cellClass/cellClassRules to update column's state and classNames

**Current behaviour**
No changes on grid.

* **ag-Grid version:** 
"ag-grid-community": "^24.0.0",
"ag-grid-react": "^24.0.0",

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.9.7
React 16.13.1
ES6/7 -> target ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks
