### ISSUE TITLE
Plans for Vue JS 3 support

### ISSUE THREAD

**Issue by csicky** [ag-grid/ag-grid#4122]
What title says, is there an estimation on when will the Vue version work with Vue 3?

**Comment by Paul6552** [comment]
Because I have seen it lately in the ag-grid pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Next release: AG-4650

**Comment by makinggoodsoftware** [comment]
Hi,

This should be now supported with v24.1.0! Can you guys have a look and see if all works on your end?

Thanks

**Comment by csicky** [comment]
This is very good news! Unfortunately I can't test yet, but being able to mark this as checked, now I only have to wait for bootstrap-vue and then I can move to Vue 3! 
Thank you🥇

**Comment by cyberb** [comment]
It requires vue-class-component which does not support Vue v3 yet

**Comment by kiril-matev** [comment]
Hi csicky!

ag-Grid supports Vue 3, as described in our documentation here:
https://www.ag-grid.com/documentation/vue/getting-started/

If you have any specific issues with Vue 3 support, please raise a Github issue and we will investigate them.

Thank you for raising this.

**Comment by csicky** [comment]
@kiril-matev I received this answer already last year and I closed this issue. We can't move to Vue 3 yet anyway because we are waiting for BootstrapVue and VueMultiselect.

**Comment by MLaurenzo** [comment]
Using version 8.0.0-beta.3 of vue-class-component library solved my issue.
