### ISSUE TITLE
React cellRenderers are unmounted and mounted on every redraw

### ISSUE THREAD

**Issue by biels** [ag-grid/ag-grid#4124]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The grid unmounts and remounts react components used as cell renderers by using the cellRendererFramework in the column definition. It does so on every redraw, causing flicker that can be very distracting to the user.

**Expected behavior**
The grid keeps cell renderers mounted and passes new props to them (cell renderer params), letting react do the diff and make updates where needed. 
Is there a way to currently achieve this? (Passing a specific key? Using some param in gridOptions?)
I am not providing a reproduction, because you probably know that the grid is currently operating in this manner. I can provide one if it is needed.

* **ag-Grid version:** 24.0.0

* **Browser:** all

* **Language:** all

**Comment by jiangyh1024** [comment]
this is the default behavior as ag-grid has virtualization feature, invisible rows will be destroyed.

I suggest that you use js to create cellrenderer instead of using cellRendererFramework as indicated
https://www.ag-grid.com/javascript-grid-performance/

![image](https://user-images.githubusercontent.com/34930870/95642715-d5253380-0adc-11eb-80fb-52e2424d648c.png)

**Comment by biels** [comment]
Thanks a lot @jiangyh1024, this makes a lot of sense and I appreciate your answer a lot. I still think that it should be possible to implement this for react cell renderers. Sure we can achieve the same with vanilla JS renderers but it would be nice to be able to do it. It is technically possible, react is not that slow. The problem is the unmounting/remounting. 
Probably it can even be implemented in userspace on top of a vanilla cell renderer that using ReactDOM?

**Comment by HerbiePorter** [comment]
I think we're seeing this happen as well.  We're using the infinite scroll model and when ever a new set of data is loaded into the grid all the React cells flicker even though the data being loaded is offscreen.   The cells without React renderers are fine.  

@biels Have you tried v23.0.0?  We don't observe it on the older version and I'm hoping v.25.0.0 which should be out any day now fixes the issue.

**Comment by selimbat** [comment]
Encountering this issue as well

**Comment by StephenCooper** [comment]
@selimbat  Could you please open a new issue with a minimum reproduction of the issue you are facing. The original ticket is against our legacy react rendering. 

I am working on improvements to our current react component setup so a reproduction of your issue and what you expect to be correct behaviour will serve as a useful test case for me.

**Comment by selimbat** [comment]
Turns out I had faulty dependency in my `useMemo`. My bad
