### ISSUE TITLE
Screen Reader (NVDA) is reading wrong header names for data cells.

### ISSUE THREAD

**Issue by amashar** [ag-grid/ag-grid#4128]
hi,
Screen Reader ( NVDA in my case) is reading wrong column header names in ag-grid.

it is reading column header which is 2 places earlier. 

thanks.

**Comment by makinggoodsoftware** [comment]
Hi,

We are closing this ticket as this looks like a duplicate from a zendesk ticket, if that is not the case, please reply we will reopen it.

Thanks
