### ISSUE TITLE
aggFunc is sometimes null in getRows request's rowGroupCols

### ISSUE THREAD

**Issue by fgblomqvist** [ag-grid/ag-grid#4129]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
If you group by a column without specifying an agg func, the IServerSideGetRowsRequest.rowGroupCols will contain a column that has an `aggFunc` of `null`. However, according to the `ColumnVO` type, `aggFunc` has to be a string.

**Expected behavior**
Either the type of `ColumnVO` should be updated, or the request assembler should sanitize the data when converting.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi There!

Thanks for raising this!

We just updated the typing for this:

While passing, we also noticed 'field' is also an attribute that can be missing, as the user could be using valueGetter instead.

So  ColumnVO.aggFunc and ColumnVO.field optional attributes now.

Thanks!
