### ISSUE TITLE
Cacheblocksize - should allow user to change it

### ISSUE THREAD

**Issue by jiangyh1024** [ag-grid/ag-grid#4130]
![image](https://user-images.githubusercontent.com/34930870/95567084-08bc7b00-0a55-11eb-856a-21ed85783236.png)

I have a feature that allows user to change pageSize

![image](https://user-images.githubusercontent.com/34930870/95567150-1ffb6880-0a55-11eb-80d2-955da4eb328b.png)

the pagination panel is customised by myself

currently, there is only a hack way to do this as gridOptionsWrapper is private and should also reset datasource

![image](https://user-images.githubusercontent.com/34930870/95567255-415c5480-0a55-11eb-9f23-799331058935.png)

![image](https://user-images.githubusercontent.com/34930870/95567271-49b48f80-0a55-11eb-8d11-14b6d92ee90a.png)

cacheBlockSize should be equal to paginationPageSize in order to get grid working correctly

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-2225 | [SSRM] Allow changing cacheBlockSize dynamically (either via API or making it a reactive property)
-- | --
