### ISSUE TITLE
broken RTL scroller on Chrome

### ISSUE THREAD

**Issue by MRezaHa** [ag-grid/ag-grid#4148]
I'm submitting a  bug report

horizontall scroll doesn't work with rtl mode in chrome browser
 
this bug still exist in ag-grid version 24.1.0 and you can see the problem in ag-grid samples too : https://www.ag-grid.com/javascript-grid-rtl/

* **ag-Grid version:** 24.1.0

* **Browser:** chrome

* **Angular Framework**

**Comment by gportela85** [comment]
@MRezaHa Just tried this on Chrome Version 86.0.4240.80 (Official Build) (x86_64) for MacOS and Version 86.0.4240.75 (Official Build) (64-bit) for Windows 10.

![ezgif-3-f841ba2bd523](https://user-images.githubusercontent.com/7908562/96338292-d4644280-1084-11eb-8dae-e46f15a24f0b.gif)

We will need more details
