### ISSUE TITLE
multiple selection not work with agAggregationComponent

### ISSUE THREAD

**Issue by sinna94** [ag-grid/ag-grid#4150]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When using agAggregationComponent with multiple selection, selecting the last row displayed then multiple selection doesn't work, only range selection works.

![out](https://user-images.githubusercontent.com/16590482/96416270-c3edcc80-122a-11eb-96c5-d2fc595ed8bc.gif)

https://plnkr.co/edit/nNQv00F8uDNkr07y?preview

**Expected behavior**

When using agAggregationComponent with multiple selection, I want multiple selection and range selection to work when selecting the last row displayed.

**Please tell us about your environment:**

macOs 10.15.7 / WebStorm 2020.2.3

* **ag-Grid version:**
"@ag-grid-community/react": "^23.2.1",
 "@ag-grid-enterprise/all-modules": "^23.2.1",

* **Browser:**

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
* **Language:** TypeScript 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as it seems you have both, range and row selection enabled and the system is designed to give preference to range selection when both are used.

Note that we don’t have the capacity to take feature requests as we have a full pipeline.https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by sinna94** [comment]
@makinggoodsoftware 
I have one more question

The selection problem only occurs when selecting the last row displayed.

When selecting the rows above it, multi-selection and range selection work well. Is this normal?
