### ISSUE TITLE
treeData flag after grid has been initialized doesn't work

### ISSUE THREAD

**Issue by zigasinko** [ag-grid/ag-grid#4155]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

About to become a customer, right now we're testing the grid system - implementing features locally.

**Providing a Reproducible Scenario**
Not a problem to reproduce, just try to change `gridOptions.treeData` property after grid has be initialized. It won't reflect the change in the grid, even with any or all refresh functions.
Plunker to try it out: [https://plnkr.co/edit/1WyRgd4jSmfeMN3e](https://plnkr.co/edit/1WyRgd4jSmfeMN3e)

**Current behavior**
`treeData` flag in gridOptions isn't reactive. Even if I call any of refresh methods, grid mode is still the same as it was on grid initialization. To work around it I must now unmount the grid and mount a new one with new gridOptions.

**Expected behavior**
I'd expect that the grid layout would change in accordance with `treeData` flag.

**Please tell us about your environment:**
Windows 10, create-react-app

* **ag-Grid version:** X.X.X
24.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this propery was never meant to be reactive

Note that we don’t have the capacity to take feature requests as we have a full pipeline.https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by zigasinko** [comment]
Thanks for feedback. It doesn't have to be reactive, a "refresh treeData" function would suffice (or if any of existing ones were extended to include treeData change).
