### ISSUE TITLE
Translation is not working for toolPanel button

### ISSUE THREAD

**Issue by randomUser222** [ag-grid/ag-grid#4156]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
- I reproduced the behaviour on stackblitz, I hope it is not a problem.
- [Demo page](https://stackblitz.com/edit/ag-grid-translations?file=src/app/app.component.ts)
- Steps to reproduce on stackblitz demo:
      1. Open the column header menu by clicking on the hidden menu icon in right upper corner of ID column header.
      2. Check that the button has english text.
      3. Change language to Czech.
      4. Repeat step 1 and see that the button does not get translated.
      5. Refresh the page.
      6. Change language to Czech.
      7. Repeat step 1 and see that the button get translated now.

**Current behavior**
The toolPanel buttons does not get translated, not even after calling 'refreshToolPanel' function. The translation tokens get changed correctly, but the change is not reflected. The translation change gets only reflected before you firstly open the toolPanel.

**Expected behavior**
The toolPanel buttons should get translated after calling 'refreshToolPanel' function after translation.

**Please tell us about your environment:**
 Win10

* **ag-Grid version:** 
 23.2.1

* **Browser:**
 Chrome/86.0.4240.111

* **Language:** 
 Typescript 3.9.7

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as transaltions were never meant to be reactive.

If you want to change the translations dynamically, you will have to create and destroy the grid

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
