### ISSUE TITLE
There is no specific event handler for header check box click.

### ISSUE THREAD

**Issue by jithendramani** [ag-grid/ag-grid#4158]
Ag-grid header check box toggles between check all/ uncheck all status. But it triggers as many number of 'OnSelectChanged' event as the number of items in the grid. Ideally, there should be only one event handler for select all/unselect all event. This inefficiency gives considerable performance issue with this grid. Unfortunately we purchased this grid without knowing this limitation. Is there anything can be done?

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
