### ISSUE TITLE
cellRenderer not updating when the grid runs on a popup while the main window is not active

### ISSUE THREAD

**Issue by rmallols** [ag-grid/ag-grid#4159]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Demo: https://ag-grid-refresh-issue.vercel.app
Source code: https://github.com/rmallols/ag-grid-refresh-issue/blob/master/src/App.js)

**Current behavior**
`cellRenderer`  is not being invoked when the data model changes if the grid runs in a popup window  while the main window is not active, getting as a result empty cells. The problem doesn't affect other formatter methods like `valueFormatter`.

Steps to reproduce (on the demo above)
_If using Mac, please ensure the browser doesn't run maximised, as otherwise it will create new tabs instead of new floating windows._
1. In Chrome, click on the first button (`Show grids in new window (Some filter changes won't work if the main window is not active)`.
2. Open a new tab.
3. Select the newly opened window with the grid on it and update the filter. The first column (formatted by`cellRenderer`) displays empty results (NOK), while the second one (formatted by `valueFormatter`) works as expected.
4. Return to the original tab of step 1.
5. Select the grid window again and update the filter again. Now the data is correctly updated.

The problem seems to be related to `requestAnimationFrame`. If the main window is not active, (some) changes are not propagated to the popup one. The example above incorporates a customised `requestAnimationFrame` function that broadcasts changes to the second popup as a workaround. Simply run the steps above clicking on the second button (`Show grids in new windows (All filter changes will work if the main window is not active)`) to get it working.

**Expected behavior**
Data on the first column of step 3 should be updated even if the main window is not active, without any external workarounds.

**Please tell us about your environment:**
* **ag-Grid version:** 24.1.0 (can be also reproduced on older versions)
* **Browser:** Tested on Windows and Mac:
    * Chrome: Data is not refreshed until the main window becomes active
    * Firefox : Data is refreshed after some delay

* **Language:** Tested on both TS and JS projects

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi 
Thanks for the code and the context. 

unfortunately, we're still not 100% sure what the issue is here. 

I've attached a GIF if what we're looking at. Could you please help us by providing us with an expected vs actual outcome and some more information? 

As far as we can see (in the gif), it seems to be working as expected.

![Oct-30-2020 16-49-15](https://user-images.githubusercontent.com/11807157/97733606-ff608480-1acf-11eb-9487-3b9f5b544ab8.gif)

**Comment by rmallols** [comment]
Hi,

The gif represents the expected behaviour, but it cannot be achieved in some particular circumstances.

After clicking on the first button, did you change the active tab by e.g. opening a new one, so the main one runs in the background?

Thank you in advance.
