### ISSUE TITLE
Selected items not cleared on node removal or cache purge

### ISSUE THREAD

**Issue by Romanow88** [ag-grid/ag-grid#4161]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Plunkr: https://plnkr.co/edit/xTrjwzvWSMBtO49k

**Current behavior**
Create a grid with server side data
Select a row (for the plunkr - 4-th)
Click get selected count (returns 1)
Click delete rows
Click get get selected count(returns 1) <-- We get the row node for the removed 4-th item 
Click purge infinite cache
Click get selected count (returns 1) <-- We still get the row node for the removed 4-th item

**Expected behavior**
Selected items should not include data removed from the grid.

**Please tell us about your environment:**
WIN10, Idea 2020.2

* **ag-Grid version:** X.X.X
24.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 3.8

**Comment by Romanow88** [comment]
I would assume this is the feature where the selection is persisted if we have a row identity function. 

The problem is that there is no way to clear the selection when the row was actually deleted on the backed (e.g. context menu -> delete).

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as the infinite row model does not support delta updates:

`removeItem(start, limit) {
    allOfTheData.splice(start, limit);
    this.gridApi.refreshInfiniteCache();
  }`

Note that we don’t have the capacity to take feature requests as we have a full pipeline.https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by Romanow88** [comment]
@makinggoodsoftware The issue here is that the front end does not know about data updates from a different source except the AgGrid datasource. We cannot use the delta updates as we do not have a separate update channel for the data.

We have noticed this in a scenario where the items that were not selected were affected by actions that were using `getSelected` grid API methods.

Is there a way to make this work with just a single data channel?
