### ISSUE TITLE
Column resize gets stuck when mouse goes outside the grid on the left size

### ISSUE THREAD

**Issue by Romanow88** [ag-grid/ag-grid#4168]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Plunker: https://plnkr.co/edit/w5BBZmAC9di4n1Fo

**Current behavior**
Open plunker in a new window or configure the grid to take up all horizontal space on screen
Click and hold the first column divider 
Drag to the right to give it enough width
*Quickly* drag to the left until the end of the screen 
Check the column width (it's not minimal)

**Expected behavior**
The column width should be minimal

**Please tell us about your environment:**
WIN10 20H2, IDEA

* **ag-Grid version:** X.X.X
24.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this might be opinionated

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by Romanow88** [comment]
@makinggoodsoftware could you please elaborate which opinions were considered?

**Comment by YakinRojinegro** [comment]
Having the same issue on react distro (^24.0.0) when setting suppressColumnVirtualisation={true} and then resizing browser window and scrolling to the right side of the grid data.
Example taken from https://www.ag-grid.com/javascript-grid-resizing/#resizing-example 
On plunker -> Functional React

![image](https://user-images.githubusercontent.com/42383944/102655266-a314fb00-4137-11eb-9ca8-8d5fee523e8a.png)

**Comment by YakinRojinegro** [comment]
> Having the same issue on react distro...

#4231  Sorry, did not know that there is already an open issue for this. Keeping track on that
