### ISSUE TITLE
how to use "main": "./dist/ag-grid-community.esm.js", in package.json

### ISSUE THREAD

**Issue by zezhongmiao** [ag-grid/ag-grid#4170]
I use VIte and vue3 ;   it use es module  ; the package 'ag-grid-vue3'  cant use; I change the  package.json  main   cjs to esm; 
I dont know the right way....
蹩脚的英文，， 用 ag-grid-vue3   改了  ag-grid-community 包的 入口文件 怎么才是正确的 使用方式

**Comment by Firestorm01** [comment]
Try to modify optimizeDeps in vite.config.ts like this

optimizeDeps: {
    include: [
      '@ag-grid-community/vue3/lib/AgGridVue',
    ],
  },

and package.json like this

  "dependencies": {
    "@ag-grid-community/all-modules": "^24.1.0",
    "@ag-grid-community/vue3": "^24.1.1",
...

**Comment by bthulu** [comment]
is this works? and how to set in react?
