### ISSUE TITLE
[touch] cannot use touch to scroll left pinned columns

### ISSUE THREAD

**Issue by elmccd** [ag-grid/ag-grid#418]
Related to #14 but on mobile

On latest 1.14.0 version dragging pinned columns vertically/horizontally is not possible.

In case where pinned columns are wider than screen it makes rest of the table completely inaccessible.

Mouse scrolling works fine.

**Comment by ceolter** [comment]
> On latest 1.14.0 version dragging pinned columns vertically/horizontally is not possible.

what do you mean? i am able to re-size the widths of the pinned cols by dragging. what other dragging are you expecting?

yes i know the grid becomes unusable if the pinned cols are wider than the screen, but that's what pinned cols are, they are pinned, if you make them fill the screen, well they stay pinned!

**Comment by elmccd** [comment]
I'm talking about scrolling table grid by swiping on pinned elements. 
I can scroll up/down by swiping up and down on not pinned columns, but not on pinned.

After changes in 1.14.0 I can use mouse scroll to do this - great. But on mobile I can't the very same thing.

Swiping horizontally - you are right that how pinning should work.

![jchq7ju](https://cloud.githubusercontent.com/assets/2963340/9680921/9bad1dba-52fa-11e5-8575-0720051691b2.gif)

**Comment by ceolter** [comment]
thanks for that movie. i understand. i didn't test on touch device, i was only trying to fix the mouse wheel!!

**Comment by Ruud-cb** [comment]
+1 o this. It is still an issue. Could it get fixed? As well as resizing columns on touch devices?

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-65

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
