### ISSUE TITLE
cell style 'text align' not working for enableCellTextSelection = true settings

### ISSUE THREAD

**Issue by natz92** [ag-grid/ag-grid#4184]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- This issue has yet to be resolved. ( #3574 )
- https://plnkr.co/edit/v0zXOchrnYeuz8dG?preview
```html
        <div style="height: 100%">
            <ag-grid-vue
                style="width: 100%; height: 100%;"
                class="ag-theme-alpine"
                id="myGrid"
                :gridOptions="gridOptions"
                @grid-ready="onGridReady"
                :columnDefs="columnDefs"
                :defaultColDef="defaultColDef"
                :modules="modules"
                :enableCellTextSelection="true"
                :rowData="rowData"></ag-grid-vue>
        </div>
```
- age (not working)
  ```javascript
  cellStyle: { textAlign: 'center' }
  ```
- year (not working)
  ```javascript
  cellStyle: { textAlign: 'right' }
  ```
- year (not working)
  ```javascript
  cellStyle: { textAlign: 'right' }
  ```
- date (not working)
  ```javascript
  cellStyle: { backgroundColor: '#aaffaa', textAlign: 'right' }
  ```
- gold (**working**)
  ```javscript
  cellStyle: { backgroundColor: '#aaffaa', direction: 'rtl' }
  ```
- silver (not working)
  ```javascript
  cellStyle:  { justifyContent: 'flex-end' }
  ```
- bronze (not working)
  ```javascript
  cellStyle:  { float: 'right' }
  ```

**Current behavior**
- text align not working.

**Expected behavior**

**Please tell us about your environment:**
- webStorm
- vue.js 2.6.11

* **ag-Grid version:** X.X.X
* 24.1.0 (lastest)
*No problem with version 21.0.1

* **Browser:**
```
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
```

* **Language:**
- ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

Note that your styles are being applied, but you should be applying different styles to achieve your desired outcome

Note that we don’t have the capacity to provide support though github as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
