### ISSUE TITLE
Unable to select checkboxes in Multi Filter

### ISSUE THREAD

**Issue by jeremypeters** [ag-grid/ag-grid#4186]
I'm just evaluating the enterprise version. I have setup the multi filter - however the set filter checkboxes are all unselectable. 

I just want to check if this may possibly be a limitation of not having a license.

Thanks.

**Comment by makinggoodsoftware** [comment]
Hi,

Not having a license should never cause a limitation of functionality, it would just be a breach of usage, but everything should work as normal.

If you are evaluating, I would suggest getting in contact with us via zendesk, contact info@ag-grid.com if you need access.

**Comment by jeremypeters** [comment]
@makinggoodsoftware Thanks for the clarification.
