### ISSUE TITLE
feature: Add ranged deselection

### ISSUE THREAD

**Issue by wjaspers** [ag-grid/ag-grid#4187]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

See #4126 

**Customers of ag-Grid**

**Requesting Community Support**

**Current behavior**
Click, then shift click always adds rows to the current selection. It has no effect if the first and last row in the range were deselected in the same manner.

**Expected behavior**
Click to select a row.
Then shift click to select a range of rows.
Then click to deselect a row.
Then shift click to deselect a range of rows; even if it is within the current selection.

**Please tell us about your environment:**

* **ag-Grid version:** 24.1.0

* **Browser:** Chrome / any

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Not sure I can trace this to your ticket in zendesk, could you share your zendesk ticket URL over here? (It's username/password protected so it should be safe)

Thanks

**Comment by wjaspers** [comment]
> Hi,
> 
> Not sure I can trace this to your ticket in zendesk, could you share your zendesk ticket URL over here? (It's username/password protected so it should be safe)
> 
> Thanks

There was a miscommunication on our end; apparently a Zendesk ticket has not yet been created.
My apologies for the confusion.

**Comment by makinggoodsoftware** [comment]
Hi,

No worries, I think you will find it much more efficient if you raise this via zendesk... If you need help with your access, you can contact info@ag-grid.com

You can try to log into ag-grid.zendesk.com

I will close this in the meantime
