### ISSUE TITLE
Pivoting

### ISSUE THREAD

**Issue by adityasethi06** [ag-grid/ag-grid#4188]
Is there a way to programatically set the pivot?

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
