### ISSUE TITLE
cellRenderers are not working with functional React

### ISSUE THREAD

**Issue by Spark3000** [ag-grid/ag-grid#4189]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**

Using functional react and the AgGridReact and AgGridColumn components fails when using React components in cells. 

Component:
![Screenshot 2020-11-08 at 18 04 43](https://user-images.githubusercontent.com/4939629/98470234-046ab580-21ed-11eb-8dab-19c8fb2e42c1.png)

Declaring framework components:
![Screenshot 2020-11-08 at 18 04 55](https://user-images.githubusercontent.com/4939629/98470254-1c423980-21ed-11eb-9060-331584e474c4.png)

Applying component to AgGridColumn:
![Screenshot 2020-11-08 at 18 05 06](https://user-images.githubusercontent.com/4939629/98470268-35e38100-21ed-11eb-92f0-0ef4a514b7ab.png)

Error:
<img width="880" alt="Screenshot 2020-11-08 at 18 05 13@2x" src="https://user-images.githubusercontent.com/4939629/98470272-3e3bbc00-21ed-11eb-9996-6707e06bd40c.png">

**Expected behavior**
Render the React component in the cell

**Please tell us about your environment:**
Webstorm IDE, Yarn, Create-React-App dev server, Mac OS

* **ag-Grid version:** 
Most Recent 24

* **Browser:**
Chrome 

* **Language:** 
ES6

**Comment by seanlandsman** [comment]
I am unable to reproduce this - take a look at: https://plnkr.co/edit/KynT4z1sGxNWkoWm

Do you have a repro of the issue I can take a look at?

**Comment by Paul6552** [comment]
@Spark3000 I am working with react functional components as well, but this is working. I checked it with version 24.1 and 24.0
But where does your error happen? Your code does not show the faulty code where the error happens.

**Comment by Spark3000** [comment]
Hi @Paul6552 and @seanlandsman Thanks for the replies. This is the full error and my datasource. I'm using this with `serverSide` data and ag-grid enterprise. 

Everything has been working find up to now. 

<img width="1083" alt="Screenshot 2020-11-09 at 15 03 17@2x" src="https://user-images.githubusercontent.com/4939629/98544680-012f0280-229d-11eb-98a0-6fbd9fb81c35.png">


![Screenshot 2020-11-09 at 15 03 07](https://user-images.githubusercontent.com/4939629/98544689-04c28980-229d-11eb-9d0d-e10938cf6c3a.png)

**Comment by Spark3000** [comment]
I can get this working with the fake datasource: https://codesandbox.io/s/purple-wave-7hin1?file=/src/index.js:344-372

But not with mine.

**Comment by Paul6552** [comment]
@Spark3000 
This doesn't seem to be a bug from ag-grid to me, but your implementation of how the data is retrieved. 
I assume you are returning data for ag-grid in your function "params.successPayload" but not in "params.failCallback".
Therefore you are returning "nothing" to ag-grid. Try to return mock-data in both of your situations If(response.payload) is true and false. Please consider to open a "community-issue" instead of a bug-ticket next time.

**Comment by Spark3000** [comment]
The `failCallback()` takes no arguments.
[https://www.ag-grid.com/javascript-grid-server-side-model-datasource/](Server Side Model Docs)

```
interface IServerSideGetRowsParams {
    // details for the request, simple object, can be converted to JSON
    request: IServerSideGetRowsRequest;

    // the parent row node. is the RootNode (level -1) if request is top level.
    // this is NOT part of the request as it cannot be serialised to JSON (a rowNode has methods)
    parentNode: RowNode;

    // success callback, pass the rows back the grid asked for.
    // if the total row count is known, provide it via lastRow, so the
    // grid can adjust the scrollbar accordingly.
    successCallback(rowsThisPage: any[], lastRow: number): void;

    // fail callback, tell the grid the call failed so it can adjust its state
    failCallback(): void;

    // grid API
    api: GridApi;

    // column API
    columnApi: ColumnApi;
}
```

**Comment by Paul6552** [comment]
Can you create a sandbox example. Otherwise it is hard to help. As I said, try to step through with the debugger.

**Comment by Paul6552** [comment]
Steph through with the debugger. 
Do you have data in response? Temporary replace the function "getLastRowIndex(params.request, response.payload)" with 1.
Your error says "Undefined". What is undefined? params?
Try to replace
```
const response = await dispatch(
         getOrdersPaginated(params.request)
       );
```
with mock-data.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by Spark3000** [comment]
Fixed.
The ag-grid-react package was on 22.x and the community and enterprise were on 24.x 🙄

**Comment by Spark3000** [comment]
As an aside... Would it not be a better pattern to, by default, make every child of the `AgGridReact` component into a frameworkComponent, without having to declare it first, and without having to pass it to the `AgGridColumn` cellRenderer prop? Just give it all the `AgGridColumn` props including the `params` as a prop and then render that components' JSX return?

**Comment by Spark3000** [comment]
Sorry - another aside... I've seen quite a few issues that ended up being this mismatched version issue. Is there not a way to build in a console warning for it.
