### ISSUE TITLE
[scroll] Left/right scroll on pinned columns scrolls up/down

### ISSUE THREAD

**Issue by ScottTrenda** [ag-grid/ag-grid#419]
If you scroll horizontally on a pinned column (particularly on a trackpad), the grid will scroll vertically in response to it.

**Comment by ScottTrenda** [comment]
Also, vertical and horizontal scrolling on the grid headers do nothing.

**Comment by ceolter** [comment]
dammit trackpads!!!!! i develop on a computer with a mouse and a keyborad, so all this stuff doesn't get noticed by me!!!!

seriously though, thanks for raising. i'll try and get my hands on a laptop and fix this :)

is it on a mac or pc? is it a two finger drag gesture?

**Comment by S-YOU** [comment]
@ceolter, There is another approach than mousewheel / DOMMouseScroll / Touch events is to listen on normal "scroll" event like main grid, and set same scrollTop on main grid back and vice versa.

just some idea, you can check that approach in my lib demo - http://rawgit.com/S-YOU/doTA/master/examples/virtual-scroll/index.html

**Comment by ceolter** [comment]
thanks @S-YOU, i'll take a close look at your example when i come back to this.

btw - you demo - do you actually generate data for 1,000,000 x 1,000,000 into the browser? or is the data just fabricated as you scroll? i'm asking as i was having issues with memory on chrome for that that large, so am guessing you are fabricating, but if not, i want to know how you did it!!

**Comment by S-YOU** [comment]
Its generating on the fly. 
previously i tested with 1M fixed rows and 10k columns, javascript and chrome can handle, but 200M memory, GC sometimes make UI lag. so, I generate both rows and columns on the fly now.

**Comment by ceolter** [comment]
i'd be interested if someone knows how to handle 'large' data in chrome (or any browser). it would be great that there was a way, in the office environment (so we can control the browser) to load millions of record into the browser and slice and dice the data.

**Comment by S-YOU** [comment]
I normally use chrome "Take Heap Snapshot" to check memory usage

![2015-09-07 19 45 14](https://cloud.githubusercontent.com/assets/1001175/9715194/0df30bb4-5599-11e5-94b3-094a133f9f50.png)

For instance, if I generate fixed 1M array, 1M objects count and memory usage is around 80M.
![2015-09-07 19 45 20](https://cloud.githubusercontent.com/assets/1001175/9715201/1f8b436e-5599-11e5-87f7-3e3c06466597.png)

Browser are very sensitive on creating small objects, GCing those are expensive process.
So, if you have a lot of object, keep an eye on object count and size on Heap Snapshots.

**Comment by ScottTrenda** [comment]
@ceolter: This is on a Mac, using the two-finger gesture for scrolling. You can probably just look at the deltaX/deltaY properties on the mousewheel event object, and scroll left/right or up/down based on those values.

**Comment by ceolter** [comment]
@ScottTrenda thanks for the info

**Comment by Elecash** [comment]
I'm interested to fix this. I'll try to find a solution and commit a PR.

Any suggestion on where can I start digging on this?

**Comment by Elecash** [comment]
I've created a PR to fix this.

https://github.com/ceolter/ag-grid/pull/733

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-66

**Comment by makinggoodsoftware** [comment]
should be fixed now @Elecash  thanks!

I owe you a beer
