### ISSUE TITLE
First row which is rowDrag: false is moving down by other draggable rows.

### ISSUE THREAD

**Issue by spider58** [ag-grid/ag-grid#4190]
Hi.

First row is set **rowDrag:false**

other rows are set **rowDrag: true;**

First row which is rowDrag: false is moving down by other draggable rows. This is a bug i think. 

I want to keep first row as first row always. How can i do that? 

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
