### ISSUE TITLE
problem with valueFormatter in pivot mode

### ISSUE THREAD

**Issue by mahdiporkar** [ag-grid/ag-grid#4192]
I have problem with value formatter in pivot mode all mode work well ,but when switch to pivot mode 
inside valueformatter function params.value is undefined

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
