### ISSUE TITLE
sortedAt documentation

### ISSUE THREAD

**Issue by rezi-elton** [ag-grid/ag-grid#4195]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
The deprecated comment for sortedAt in colDef.d.ts appears to be wrong, should mention sortIndex instead of sortOrder
 
/** @deprecated since v24 - use sortOrder instead*/
 sortedAt?: number;

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Good spot! Thanks for this, this has now been fixed, it will be part of our next release!

Thanks
