### ISSUE TITLE
Middle mouse scroll does not support both horizontal and vertical scroll

### ISSUE THREAD

**Issue by Romanow88** [ag-grid/ag-grid#4196]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
E.g.: https://www.ag-grid.com/example.php

**Current behavior**
Open a big enough grid where both vertical and horizontal scroll lines appear.
Press and hold middle mouse button.
Horizontal scroll is possible, vertical scroll is not possible. 
De-select columns so that the horizontal scroll is not visible.
Press and hold middle mouse button.
Vertical scroll is possible. 

**Expected behavior**
When both vertical and horizontal scroll bars are present, both vertical and horizontal scroll should be possible. 

**Please tell us about your environment:**
IDEA 2020.2, NPM, Windows 10 20h2

**ag-Grid version:** 24.1

**Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
