### ISSUE TITLE
Documentation labels some gridEvents incorrectly

### ISSUE THREAD

**Issue by Spark3000** [ag-grid/ag-grid#4199]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**

The documentation [here](https://www.ag-grid.com/javascript-grid-events/#properties-and-hierarchy) calls the selection changed event `selectionChanged` but that doesn't work with (at least) the functional React version. The event is actually called `onSelectionChanged` which is unnecessarily confusing. 

![Screenshot 2020-11-15 at 18 06 09](https://user-images.githubusercontent.com/4939629/99190115-68e9bf80-276d-11eb-9194-7896910e186d.png)

**Expected behavior**
Show correct gridEvent names in documentation.

**Please tell us about your environment:**
Mac OS, JetBrains Webstorm, Yarn, Create React App hot reload dev server

* **ag-Grid version:** X.X.X
24.1

* **Browser:**
Chrome

* **Language:** 
ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Note that we have this at the top for the docs section:

Grid Events
This is a list of the events that the grid raises. You can register callbacks for these events through the GridOptions interface.

https://ag-grid.com/javascript-grid-events/ 
The name of the callback is constructed by prefixing the event name with on. For example, the callback for the cellClicked event is gridOptions.onCellClicked.
