### ISSUE TITLE
Ag-Grid should dynamically add rows to accommodate paste from clipboard

### ISSUE THREAD

**Issue by Akshay9790** [ag-grid/ag-grid#4204]
Current behavior

If one pastes data from excel into a grid, and the number of rows exceeds those available in the grid, the grid will not add rows to accommodate.
Expected behavior

The grid should automatically add rows based on the length of the clipboard data. Ideally this would option could be turned on via a field on the gridOptions.

Minimal reproduction of the problem with instructions

Try to paste data that is longer than the number of rows available in the grid. Either in total, or remaining from the point where paste begins.

What is the motivation / use case for changing the behavior?

Users will not need to make sure to have the exact number of available rows when pasting from excel.
Please tell us about your environment:

ag-Grid version: X.X.X
Browser:
Language: [all | TypeScript X.X | ES6/7 | ES5]

This is same as issue 1820 already raised before. https://github.com/ag-grid/ag-grid/issues/1820
Could you please include this in your enterprise module.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

In any case, we appreciate the feedback, note that this is going to get flagged with the label good suggestion. We are going to close this issue but having this issue being flagged with good suggestion means that it will be potentially be considered for development.

Please keep an eye on our pipeline as this might appear there.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks for your feedback

____

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
