### ISSUE TITLE
gridReady event not triggered when loading grid in a component via ComponentFactoryResolver

### ISSUE THREAD

**Issue by ppaulis** [ag-grid/ag-grid#4205]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request 
```

**Current behavior**
I described the behaviour in this post:
https://stackoverflow.com/questions/64771587/ag-grid-gridready-event-not-triggered-when-loading-grid-in-a-component-via-com

**Expected behavior**
I expected the gridReady event to be fired when AG Grid is loaded in a component through the componentFactoryResolver, not only when it is triggered through a direct action, but also on `ngOnInit()`. I'm not a 100% sure if this is a bug or a misunderstanding. So, any advice is much appreciated here!

**Please tell us about your environment:**
Ubuntu 20.10
```
ppaulis@ppaulis-desktop:~$ nvm list
->     v14.14.0
```

* **ag-Grid version:** 24.1.0

* **Browser:** Firefox 82

* **Language:** TypeScript 3.9.7 / Angular 10

Any help is appreciated!
Thanks,
Pascal

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, you should use other events, like onFirstDataRendered

Note that we don’t have the capacity to take feature requests as we have a full pipeline.https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
