### ISSUE TITLE
Documentation fault

### ISSUE THREAD

**Issue by craigsh** [ag-grid/ag-grid#4212]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

There's an issue with your documentation: https://www.ag-grid.com/javascript-grid-selection/

The "Example: Selection with Keyboard Arrow Keys" code is wrong.  The code refers to **previousCellDef** and **nextCellDef** when it should refer to **previousCellPosition** and **nextCellPosition** respectively.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Code snippet and example, both fixed now! This should be ready in our next release v25 ETA 2/3 weeks from now!

Thanks for the feedback!
