### ISSUE TITLE
Ag-grid-vue testing with jest throwing Syntax Error

### ISSUE THREAD

**Issue by somalee-ee** [ag-grid/ag-grid#4216]
I am trying to test a basic table with Aggrid using jest. This is throwing the below error:

C:\Users\Somalee.Gupta\Desktop\EnergyExemplarProjects\Data.Web\source\EnergyExemplar.Data.Web\node_modules\@ag-grid-community\vue\lib\AgGridVue.js:20
    import { Component, Prop, Vue } from 'vue-property-decorator';    ^^^^^^

    SyntaxError: Cannot use import statement outside a module     

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@ag-grid-community/vue/main.js:6:10)

I tried solutions given on this issue:  https://github.com/ag-grid/ag-grid/issues/3046
But nothing seems to work.
Here are my config files : 

Package.json

{
  "name": "ee-data-web",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "author": "Energy Exemplar",
  "scripts": {
    "build": "vue-cli-service build --mode development --watch",
    "lint": "vue-cli-service lint",
    "build-prod": "vue-cli-service build --mode production",
    "build-report": "vue-cli-service build --report",
    "test": "jest --verbose",
    "tsc": "tsc -project tsconfig.json",
    "vue-serve": "vue-cli-service serve"
  },
  "main": "site.js",
  "files": [
    "./VueApp/**/*.ts"
  ],
  "dependencies": {
    "@ag-grid-community/all-modules": "^24.1.0",
    "@ag-grid-community/vue": "^24.1.1",
    "@aspnet/signalr": "1.1.4",
    "@mdi/font": "^5.5.55",
    "@vue/test-utils": "^1.0.0-beta.30",
    "ag-grid-enterprise": "^24.1.0",
    "axios": "0.19.0",
    "classy-vuex": "^1.8.7",
    "clsx": "^1.1.1",
    "ee.web.components": "0.0.89",
    "rxjs": "6.5.4",
    "svgstore": "^3.0.0-2",
    "vee-validate": "^3.4.5",
    "vue": "2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-inject": "^2.1.1",
    "vue-loader": "15.7.1",
    "vue-property-decorator": "^8.4.1",
    "vue-router": "3.0.6",
    "vuelidate": "^0.7.5",
    "vuelidate-property-decorators": "^1.0.28",
    "vuetify": "2.2.8",
    "vuex": "3.1.1",
    "vuex-class": "^0.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-typescript": "^7.3.3",
    "@types/jest": "^24.0.19",
    "@typescript-eslint/eslint-plugin": "^2.20.0",
    "@typescript-eslint/parser": "^2.20.0",
    "@vue/babel-preset-jsx": "^1.1.2",
    "@vue/cli-plugin-babel": "^4.1.0",
    "@vue/cli-plugin-eslint": "^4.1.0",
    "@vue/cli-plugin-typescript": "^4.3.1",
    "@vue/cli-plugin-unit-jest": "^4.1.0",
    "@vue/cli-service": "^3.9.3",
    "@vue/eslint-config-standard": "^4.0.0",
    "@vue/eslint-config-typescript": "^5.0.1",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-jest": "^24.8.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "core-js": "^3.6.5",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-import-resolver-webpack": "^0.12.1",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jest": "^23.8.0",
    "eslint-plugin-vue": "^6.2.1",
    "husky": "^4.2.3",
    "jest": "^24.9.0",
    "jest-transform-stub": "^2.0.0",
    "lint-staged": "^10.0.8",
    "node-sass": "^4.13.1",
    "sass": "^1.24.2",
    "sass-loader": "^7.3.1",
    "svg-inline-loader": "^0.8.2",
    "svgo": "^1.1.0",
    "svgo-loader": "^2.1.0",
    "ts-jest": "^24.3.0",
    "typescript": "~3.8.3",
    "vue-cli-plugin-svg-sprite": "~1.0.0",
    "vue-cli-plugin-vuetify": "^0.6.3",
    "vue-cli-plugin-webpack-bundle-analyzer": "^2.0.0",
    "vue-eslint-parser": "^7.0.0",
    "vue-jest": "^3.0.4",
    "vue-template-compiler": "2.6.11",
    "vuetify-loader": "1.3.0",
    "webpack": "4.37.0",
    "webpack-cli": "3.3.6"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npx lint-staged"
    }
  },
  "license": "ISC",
  "lint-staged": {
    "*.{js,ts,jsx,tsx,vue}": [
      "./node_modules/.bin/eslint"
    ]
  }
}

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

jest.config.json:

module.exports = {
    moduleFileExtensions: [
        'js',
        'jsx',
        'json',
        'vue',
        'ts',
        'tsx',
    ],

    collectCoverageFrom: [
        'VueApp/**/*.(vue|ts)',
        '!VueApp/__test__/**',
        '!VueApp/*.(js|ts)',
    ],

    transform: {
        '.*\\.vue$': '<rootDir>/node_modules/vue-jest',
        '^.+\\.tsx?$': '<rootDir>/node_modules/ts-jest',
        '^.+\\.(js|jsx)?$': '<rootDir>/node_modules/babel-jest',
    },

    transformIgnorePatterns: [
        '<rootDir>/node_modules/(?!vuetify)',
        '<rootDir>/node_modules/(?!(@ag-grid-community)/)',
        '<rootDir>/node_modules/(?!(@ag-grid-vue)/)',
    ],

    moduleNameMapper: {
        '^vue$': 'vue/dist/vue.common.js',
        '@/(.*)$': '<rootDir>/VueApp/$1',
    },

    testMatch: [
        '**/__test__/(*.)+(spec|test).(js|ts|tsx)',
    ],

    preset: '@vue/cli-plugin-unit-jest/presets/typescript-and-babel',
};

^^^^^^^^^^^^^^^^^^^^^^^^^^^^

babel.config.js

module.exports = {
    presets: [
        ['@babel/preset-env',
            {
                corejs: 3,
                useBuiltIns: 'usage',
            },

        ],
        ['@babel/preset-typescript', {
            isTSX: true,
            allExtensions: true,
        }],
        '@vue/babel-preset-jsx',
    ],
    env: {
        test: {
            plugins: ['transform-es2015-modules-commonjs'],
        },
    },
};

I work for Energy Exemplar and we have an enterprise license for one of our products, though I am experimenting on community version for another of our product.

**Comment by somalee-ee** [comment]
Hi Please find the repo link below to reproduce the issue:

https://github.com/somalee-ee/AgGridVueDemo/tree/master

The code is in master branch.

**Comment by q974740928** [comment]
我没有这个jest.config.js，但是也报了相同的错误，请问是为什么

**Comment by q974740928** [comment]
I don't have this jest.config.js, but I also reported the same mistake. why
