### ISSUE TITLE
Non ExcelMode is still acting as ExcelMode

### ISSUE THREAD

**Issue by randyltolentino** [ag-grid/ag-grid#4219]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
From columnDefs with filterParams: { excelMode: 'windows'}

when resetting columnDefs;
example:
//My current columnDefs definition is:
[
 {
   colId: "my_column",
   filter: true,
   filterParams: {
    type: "agSetColumnFilter",
    excelMode: "windows", //turned on ExcelMode to windows behaviour
    values: ["A". "A1", "B", "B1", "C", "C1"]
   },
   headerName: "My Column"
  }
];

/** Now given I have a function (onFilterReset) to do
 *resetting columnDefs to remove excelMode
 *where @param params is the gridOptions (param) */
onFilterReset(params){
 const newColDef = [
  {
   colId: "my_column",
   filter: true,
   filterParams: {
    type: "agSetColumnFilter",
    //excelMode: "windows" /* excelMode is now removed in new columnDefs*/
   },
   headerName: "My Column"
  }
 ];

 params.api.columDefs = [];
 params.api.setColumnDefs(newColDef);
}

Performing onFilterReset function is still acting Excel Mode:
Steps:
1. Perform Column Filter to My Column
2. Filter 'A' (using miniFilter)
3. Clear miniFilter
4. Filter 'B' 
Bug: Filtering 'B' overrides my current filter ('A')

**Expected behavior**
Where, if you do this in Default Filtering Mode (without excelMode) - tested from older AG Grid Version (can't remember though)
Steps:
1. Perform Column Filter to My Column
2. Filter 'A' (using miniFilter)
3. Clear miniFilter
4. Filter 'B'
5. Deselect All Selections
6. Now only check 'B1'
Expected Behavior: Filtering 'B1' should append the current filter 'A'

**Please tell us about your environment:**

I'm using Windows 10, VSCodium, running only localhost with NPM

* **ag-Grid version:** X.X.X

24.1.0

* **Browser:**

Chrome / Brave

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this property is not reactive, ie does not change after it has been initialised:

https://ag-grid.com/javascript-grid-column-state/#column-state

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
