### ISSUE TITLE
Floating Filter doesn't appear if enabled programmatically later.

### ISSUE THREAD

**Issue by shubanker** [ag-grid/ag-grid#4220]
**I'm submitting a ...** 
```
[x] bug report
[] feature request 
[] support request
```

**Reproducible Scenario**

Set floating filter as `false` initially in `defaultColDef`
```
defaultColDef: {
    floatingFilter: false, //if enabled initially it works fine.
    filter: "agNumberColumnFilter",
  },
```
then enable it later(after grid ready).
```
gridOptions.defaultColDef.floatingFilter=true;
gridOptions.api.refreshHeader();
```
Plunker [Link](https://plnkr.co/edit/OXWCxjllMFlkDZZY)

**Current behavior**
If Floating filters are disable initially and enabled later the inputs fields aren't visible, however if they are enabled initially then disabled then re-enabled it works fine.

**Expected behavior**
The floating filter should appear even if they were disabled initially.

**Environment:**
Initially faced this issue with Angular 10/11 on Windows 10, but is reproducible with Vanilla JS.

* **ag-Grid version:** 24.1.0

* **Browser:**
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36`

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this property is not reactive, ie does not change after it has been initialised:

https://ag-grid.com/javascript-grid-column-state/#column-state

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by shubanker** [comment]
> Hi,
> 
> Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.
> 
> In our opinion, this would be a feature request as this property is not reactive, ie does not change after it has been initialised:
> 
> https://ag-grid.com/javascript-grid-column-state/#column-state
> 
> Note that we don’t have the capacity to take feature requests as we have a full pipeline.
> https://www.ag-grid.com/ag-grid-pipeline/
> 
> If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.
> 
> If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact [info@ag-grid.com](mailto:info@ag-grid.com) for access. This is our primary channel for Support.

It seems this issue got introduced in version 23.1, possibly when `floatingFilter` in `gridOptions` was deprecated and moved inside `colDef`, [here](https://plnkr.co/edit/0HQY9QG9qvyIDwUS) is a similar plunker with working example using older version (23.0.2).

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

We have created the following example.

https://plnkr.co/edit/p9WsE0t6mQV9d14E

To dynamically update the visibility of the floating filter, you can update the floatingFilter property on each column and then set the column definitions using the grids API.

Kind Regards,
