### ISSUE TITLE
Change language in runtime on Angular 11

### ISSUE THREAD

**Issue by jgomesmv** [ag-grid/ag-grid#4228]
Has stated in the documentation if we need to change the language in runtime the grid needs to be destroyed and recreated. I have tried this example on top of angular 11 but it doesn't seems work: https://ag-grid.zendesk.com/hc/en-us/articles/360016033371-Create-and-destroy-grids

Current behavior: grid is destroyed and not recreated 
Expected behavior. grid should be destroyed and recreated

* **Angular version:** 11.0.2

* **ag-Grid version:** @ag-grid-community/all-modules": "^24.1.0",
    "@ag-grid-community/angular": "^24.1.0",
    "@ag-grid-enterprise/all-modules": "^24.1.0"

Can you guys help?
Thanks :)

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as you need to create/destroy the grid for the translations to take effect

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by jgomesmv** [comment]
Hi,

Thanks for the response.
I have tried the example provided by the ag-grid zendesk to destroy and recreate the grid using a ngIf as a container element of the gird, but it didn't work as expected.
We plan to buy an enterprise license but we are still trying it out so see if it covers all our requirements.
Since the provided workaround doesn't seem to work can you please help?

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
