### ISSUE TITLE
How can i deal with the white space when drag columns?

### ISSUE THREAD

**Issue by nightost** [ag-grid/ag-grid#4229]
**Current behavior**
![image](https://user-images.githubusercontent.com/3621908/101125949-6922ff80-3635-11eb-88ac-590fdf4c81e5.png)

**Expected behavior**
last column can't be drag or be flexable

**Please tell us about your environment:**
mac 
* **ag-Grid version:** X.X.X
21.2.1

* **Browser:**
chrome 87.0.4280.88

demo:
https://www.ag-grid.com/javascript-grid-pinning/

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
