### ISSUE TITLE
Horizontal scrolling bug

### ISSUE THREAD

**Issue by Akaprog** [ag-grid/ag-grid#4231]
**I'm submitting a bug report**
```
[x] bug report => see 'Providing a Reproducible Scenario'

```

**Providing a Reproducible Scenario**
Steps to reproduce:
1) https://ag-grid.com/javascript-grid-resizing/ or https://plnkr.co/edit/lNVUKSTmKTuBXAXR
2) scroll horizontal bar to right
3) scroll horizontal bar to left

May depend on screen resolution and/or window size (to reproduce you need that when scrolling right more than 2 columns become hidden)

**Current behavior**

Table not scrolled when scrolling back to the left

**Expected behavior**

Table scrolling

**Environment**
* **Any framework**

* **ag-Grid version:** 24.1.0

* **Browser:** Chrome or Edge @latest

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.52"

**Screenshot**
![image](https://user-images.githubusercontent.com/2947779/101217534-9225ad80-3692-11eb-9da7-d545d647163c.png)

**Comment by Akaprog** [comment]
For my case it could be fixed by adding 2-3 pinned columns, but I found this issue annoying and blocking for implementation of any relatively large table using ag-grid.

**Comment by makinggoodsoftware** [comment]
Hi,

Note that this will be fixed in v25 which should be ready within days now.

I will keep this open so we can follow up

Thanks for reporting this!

**Comment by venkatesh-lr** [comment]
> Hi,
> 
> Note that this will be fixed in v25 which should be ready within days now.
> 
> I will keep this open so we can follow up
> 
> Thanks for reporting this!

I face the same bug. Does it fixed in V25 ?
Any idea when is the release date ?

**Comment by Akaprog** [comment]
@venkatesh-lr AFAIK, Next Release Target: 8th Jan (v25.0.0) is https://www.ag-grid.com/ag-grid-pipeline/

(But it could change, I've been watching for release with this issue since next release target was 11th Dec)

**Comment by makinggoodsoftware** [comment]
Hi guys,

v25 Was released yesterday, could you check if this works as expected?

Thanks

**Comment by Akaprog** [comment]
@makinggoodsoftware 
Hi Alberto, 

the issue seems to be fixed in v25, 

at least I cannot reproduce it anymore in demo and in my environment.

Thanks

**Comment by venkatesh-lr** [comment]
I have taking updated to V25. The bug is resolved. Thanks for bug Fix on Time.
