### ISSUE TITLE
Highlight row on right click with ag-grid

### ISSUE THREAD

**Issue by NicholasK13** [ag-grid/ag-grid#4234]
Is it possible to highlight an ag-grid row on right click? The expected functionality is that the row should get selected/highlighted on right click the same way it does for left click. 

I've tried using the `getContextMenuItems()` and at max I could set focus to the selected row. Is there a way to achieve this?

ag-Grid enterprise version:
21.2.2

Browser:
Chrome

Language: 
Typescript/Angular

Let me know if any more details are needed.

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
