### ISSUE TITLE
Link to GitHub on your website goes to facebook

### ISSUE THREAD

**Issue by luke-feeney** [ag-grid/ag-grid#4237]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'

The link to GitHub on your website goes to facebook. Very disconcerting. Image attached. 

![image](https://user-images.githubusercontent.com/53231019/101650090-7a07b280-3a33-11eb-9ab8-e7c468ad16bb.png)

**Comment by luke-feeney** [comment]
![image](https://user-images.githubusercontent.com/53231019/101650513-eaaecf00-3a33-11eb-90e7-1e7616c0d832.png)

**Comment by makinggoodsoftware** [comment]
Hi!

Thanks for pointing out! Let me check this! We will fix it as soon as possible!

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Apologies for the long delay getting back to you! We had some issues updating the themes in our blog plattform and we had to migrate the whole thing

So, long story short, now we have a flexible blog plattform where we can make these changes easily.

Thanks for the heads up, now this is fixed

**Comment by luke-feeney** [comment]
Great work - thanks for coming back to the issue
