### ISSUE TITLE
date filter cannot be resetted in chromium browsers

### ISSUE THREAD

**Issue by VILLAN3LL3** [ag-grid/ag-grid#4238]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Navigate to https://www.ag-grid.com/javascript-grid-filter-date/ -> Example Date Filter. Select Angular. Set date filter. Reopen filter.
Firefox:
![grafik](https://user-images.githubusercontent.com/39371377/101810129-b3661e00-3b18-11eb-9d22-203afbff2c5c.png)
Edge:
![grafik](https://user-images.githubusercontent.com/39371377/101810164-bcef8600-3b18-11eb-84b7-90aba94b7b2f.png)

--> In edge and chrome the entered date cannot be removed. Only the datepicker icon is shown, not the delete icon as in firefox.

**Expected behavior**
It should behave like in Firefox so that you can delete the date / reset the filter properly.

**Please tell us about your environment:**
Windows NT 10.0

* **ag-Grid version:** X.X.X
n/a

* **Browser:**
Correct behavior:
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0

Wrong behavior:
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.57
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
n/a

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this is a feature provided by the browser we are not creating that 'X' but IE does automatically

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by VILLAN3LL3** [comment]
@makinggoodsoftware thanks for your reply. If this is not a bug in your opinion - what is the procedure to remove a date filter that has been set?

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
