### ISSUE TITLE
Angular 10 'ag-grid-angular' is not a known element

### ISSUE THREAD

**Issue by panKt** [ag-grid/ag-grid#4241]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
`ng serve` fails with
```
'ag-grid-angular' is not a known element
```

* **ag-Grid version:** 24.1.0

-----

I followed the documentation and it works as expected when `<ag-grid-angular>` used in **app.component.html** but fails if I use it in any other module

**Comment by shubanker** [comment]
You need to import  AgGridModule into the module in which you are using it, not just the app module.

**Comment by panKt** [comment]
Thanks for your answer @shubanker, I do have it imported in both app and other module. My guess is that there has something to be changed in special way in routing module. Is there any example with routing and AgGridModule imported in any modules withing the routes?

**Comment by lillyanka** [comment]
Having the exact same issue. @panKt did you manage to figure out what the issue was?

**Comment by pepeandrew777** [comment]
I have same problem however i can not solve the problem import en the modules AgGridModule , i use the 25 version of ag-grid and angular 11

**Comment by rtcullen** [comment]
Same issue here: Angular 11.0.9, ag-grid 25.  No progress made, but basically the same code base works in Angular 8 / ag-grid 19, just upgrading.

**Comment by makinggoodsoftware** [comment]
Hi guys,

Please find here the compatibility chart:

https://www.ag-grid.com/documentation/angular/getting-started/#ag-grid--angular-compatibility-chart

If you do find something that should be compatible according to the chart and is giving you issues, please feel free to open. new issue in github with a repro

Thanks!

**Comment by HatemTemimi** [comment]
having the same problem with angular 12, it works fine when added to the app module but fails in any other module, any news ?

**Comment by eureka-gh** [comment]
Not sure if anyone still need help on this issue. If it works for your app.component but not working in your new component, remember to add your new component in the Module file (where you declare @ngModule with a list of components and services).

**Comment by Dhanush9952** [comment]
@makinggoodsoftware 
It works but there is alignment problem. I'm not getting table. It shows only letters vertically.

**Comment by semko2m** [comment]
Any update on this. 
I use lazy-loaded modules with routing and ngrx. 
Not possible to work even I have done as documentation writes ?!

**Comment by StephenCooper** [comment]
@semko2m can you provide a reproduction for us to work off or possible to share the code? I have previously looked into this and struggled to reproduce the issue.
