### ISSUE TITLE
getNodeChildDetails is deprecated in version 24

### ISSUE THREAD

**Issue by vishnu-teja** [ag-grid/ag-grid#4244]
**Current behavior**
we were using `getNodeChildDetails` (grid Property) in generating tree (enterprise feature) in Ag-grid -version 21.  we are upgrading the ag-grid version to 24 and apparently this property is deprecated in the latest version.  so the grid is broken now. I checked the documentation and didn't find any alternative.

**Expected behavior**
Grid should be rendered properly.

**Please tell us about your environment:**

1. we are using ag-grid enterprise edition. (v24)
2. Angular v10

* **ag-Grid version:**  24

* **Browser:**
Chrome

* **Language:** [TypeScript 4 | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by makinggoodsoftware** [comment]
Note that you should be likely looking at tree data

https://www.ag-grid.com/javascript-grid-tree-data/

If you contact us through zendesk, we should be able to help you migrating.

**Comment by vishnu-teja** [comment]
sure @makinggoodsoftware.  i'll connect on zendesk. thank you.
