### ISSUE TITLE
Small mistake in the Modules documentation

### ISSUE THREAD

**Issue by lwouis** [ag-grid/ag-grid#4245]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
[x] mistake in the official documentation
```

Hi!

I migrated our project to Modules, following the [official documentation](https://www.ag-grid.com/javascript-grid-modules/). In [the "CSS/SCSS paths" section at the bottom](https://www.ag-grid.com/javascript-grid-modules/#css-scss-paths), there is a snippet on how to add SCSS with modules:

```scss
// SCSS Community
@import "./node_modules/@ag-grid-community/core/dist/styles/ag-grid.scss";
@import "./node_modules/@ag-grid-community/core/dist/styles/ag-theme-alpine/sass/ag-theme-alpine-mixin.scss";
```

I believe the last line has a mistake, and should be:

```scss
// SCSS Community
@import "./node_modules/@ag-grid-community/core/dist/styles/ag-grid.scss";
@import "./node_modules/@ag-grid-community/core/dist/styles/ag-theme-alpine/sass/ag-theme-alpine.scss";
```

I hope this helps you fix the documentation, and improve everyone's experience.

Thank you very much for this library. It is a piece of art!

Louis

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for raising this! We have fixed this now and will be available in our next release!

Thanks again!
