### ISSUE TITLE
AgGrid doesn't cancel obsolete server requests when the filter model is changed in quick succession

### ISSUE THREAD

**Issue by lwouis** [ag-grid/ag-grid#4246]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Version**: AgGrid v24.

I'm using the server-side row model. When filtering a column, let's say with a set filter. If I check and uncheck an option quickly, and inspect network traffic, I see that ag-grid makes 1 request per change, and these requests are not cancelled as a new one is made.

I thought that this would be controller by `maxConcurrentDatasourceRequests`, but I'm now thinking that this settings is for other cases like infini-scroll.

I would like for ag-grid to cancel previous requests. Indeed they are obsolete as soon as the user changes the filter again. Only the latest query is relevant.

ag-grid is smart enough not to refresh the grid on every query finishing. Instead it ignores the response, and waits for the latest query to finish to display the data from that query. That's nice UX for the user. However, it's unnecessary load on the backend since the response is discard for all previous queries, and it means the user is also waiting for useless queries to finish, until the latest one goes through, delaying results.

Is there an option I'm missing, or is this just an improvement that could be added to ag-grid?

Thank you!

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
