### ISSUE TITLE
Custom tooltip params value contains HTML special characters

### ISSUE THREAD

**Issue by tania-mel** [ag-grid/ag-grid#4247]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I create a custom tooltip and use tooltipValueGetter for it. tooltipValueGetter returns value with, for example, symbol '>'. In agInit method of my custom tooltip component in params.value I see '\&gt;\' instead. Its easy to reproduce this behavior in ag-grid documentation on Example: Custom Tooltip plunker, just add tooltipValueGetter which returns '>' and use params.value in the template. 

**Expected behavior**

I expect to see '>' symbol in params.value.

**Please tell us about your environment:**

Windows server 2016, WebStorm 2020.3

* **ag-Grid version:** 23.2.1

* **Browser:** Chrome 87.0.4280.88, Firefox 84.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.8.3

**Comment by Paul6552** [comment]
I don`t know which framework you use, but in react it is working.
Create a plunker example

**Comment by tania-mel** [comment]
Ahh, sorry, it's Angular. And pluncker example from ag-grid documentation I changed was also for Angular. Ok, I'll prepare a separate plunker.

**Comment by tania-mel** [comment]
Here it is:
https://plnkr.co/edit/ml7xBVZPyZeZhZL2

**Comment by lylebuchanan** [comment]
It's an issue of html encoding and special characters. Not really an ag-grid specific issue. Here is one way to handle it.

https://plnkr.co/edit/Pn7vvJ8CVPqXyJEG?preview

**Comment by tania-mel** [comment]
@lylebuchanan  - thank you! I'm using another workaround at the moment, but your idea looks cleaner.
