### ISSUE TITLE
How can I put the scroll bar and paging component on the same line?

### ISSUE THREAD

**Issue by haoxiao-beep** [ag-grid/ag-grid#4248]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
I used other paging components and wanted to put horizontal scrollbars on the same line as pagination to reduce the vertical footprint. I try to fix the width of the 'left-spacer' so that the horizontal scroll bar is on the right, and then position the paging component on the 'left-spacer'.When I tried to slide the scroll bar to the right, there was a problem. The title and content could not correspond. The CSS style code is as follows:
<style>
.ag-grid-table {
  .ag-horizontal-left-spacer {
    min-width: 650px !important;
    width: 650px !important;
    max-width: 650px !important;
    overflow-x: hidden !important;
    background-color: #fff;
    border-right: none!important;
  }

  .ag-body-horizontal-scroll {
    border-top: 1px solid #d3dce6;
    height: 37px !important;
    min-height: 37px !important;
    max-height: 37px !important;
  }
  .ag-body-horizontal-scroll-viewport {
    top: 3px;
  }
  .ag-body-horizontal-scroll-viewport::-webkit-scrollbar {
    width: 17px;
    height: 10px;
    background-color: rgba(245, 245, 245, 0.47);
  }
  .ag-body-horizontal-scroll-viewport::-webkit-scrollbar-track {
    border-radius: 10px;
  }
  .ag-body-horizontal-scroll-viewport::-webkit-scrollbar-thumb {
    height: 10px !important;
    border-radius: 10px;
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
  }
}
</style>

**Expected behavior**
I expect to fix the width of the left spacer, and when I scroll to the far right, the title corresponds to the content.Or is there any other way to put the scroll bar and paging component on the same line?

**Environment:**
 Operating system:Windows10
 IDE:Visual Studio Code1.52.1
 package manager:NPM
 Vue3.9.1

* **ag-Grid version:** 24.1.1(Vue)

* **Browser:**
Chrome 87.0.4280.88

![1608256040](https://user-images.githubusercontent.com/76190353/102565014-941e5080-4117-11eb-9562-f07042897ea9.png)
![1608256518](https://user-images.githubusercontent.com/76190353/102565046-a0a2a900-4117-11eb-91c4-66cdc7539a7a.jpg)

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as it would change how we think the scrollbars should work

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by haoxiao-beep** [comment]
> Hi,
> 
> Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.
> 
> In our opinion, this would be a feature request as it would change how we think the scrollbars should work
> 
> Note that we don’t have the capacity to take feature requests as we have a full pipeline.
> https://www.ag-grid.com/ag-grid-pipeline/
> 
> If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.
> 
> If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact [info@ag-grid.com](mailto:info@ag-grid.com) for access. This is our primary channel for Support.
> 
> We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

Thank you for your reply. I compared the source code of Ag grid community v21.0.1 and found that the code has made some adjustments. For some reason, the processing of scrollWentPastBounds has been deleted in the new version.Will it be added in later versions？Or is there any way to solve this problem indirectly？
The source code before the adjustment is like this:
GridPanel.prototype.horizontallyScrollHeaderCenterAndFloatingCenter = function (scrollLeft) {
        if (scrollLeft === undefined) {
            scrollLeft = this.getCenterViewportScrollLeft();
        }
        var offset = this.enableRtl ? scrollLeft : -scrollLeft;
        var _a = this.eCenterViewport, clientWidth = _a.clientWidth, scrollWidth = _a.scrollWidth;
        ------------------delete part begin---------------------------
        **var scrollWentPastBounds = Math.abs(offset) + clientWidth > scrollWidth;
        if (scrollWentPastBounds ||
            (this.enableRtl && offset < 0) ||
            (!this.enableRtl && offset > 0)) {
            return;
        }**
        ------------------delete part end-----------------------------
        this.headerRootComp.setHorizontalScroll(offset);
        this.eBottomContainer.style.transform = "translateX(" + offset + "px)";
        this.eTopContainer.style.transform = "translateX(" + offset + "px)";
        var partner = this.lastHorizontalScrollElement === this.eCenterViewport ? this.eBodyHorizontalScrollViewport : this.eCenterViewport;
        utils_1._.setScrollLeft(partner, scrollLeft, this.enableRtl);
    };

![image](https://user-images.githubusercontent.com/76190353/104086273-4cf82b00-5291-11eb-9fc6-e829fa44a202.png)

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
