### ISSUE TITLE
[scroll] Scrolling is not prevented during virtual row loading

### ISSUE THREAD

**Issue by ScottTrenda** [ag-grid/ag-grid#425]
If you quickly scroll down a grid that has enough rows for them to be virtualized, the scroll action is not prevented while the next set of rows is loading. This causes the rest of the page to scroll down as a result of the scroll action during this time, even though the grid allows further scrolling down after the virtualized rows are loaded. This causes an inconsistent user experience in the end.

To reproduce (easiest on a trackpad): Swipe-scroll down quickly on a grid with a virtualized row set, so that the scroll motion continues after the bottom of the row set is reached. The rest of the page will continue scrolling down during this time. Desired behavior is that these scroll ([mouse]wheel) events are prevented while the grid loads the virtualized rows, so that the user sees the virtualized rowset as a span of rows that responds the same as if they all existed as a continuous set in the grid to begin with.

**Comment by scotthovestadt** [comment]
+1 I've run into the same issue.

**Comment by ScottTrenda** [comment]
For comparison, the scrolling _is_ prevented under the same circumstances in ui-grid. UX is noticeably more consistent as a result.

**Comment by PhilBroadbent** [comment]
+1
Was there a fix or a workaround for this? I'm on 3.2.2.

**Comment by Wingie** [comment]
+1

**Comment by ceolter** [comment]
@Wingie see the section on overlays to show the loading overlay. you don't need a trigger, your datasource is called.

**Comment by Webjin** [comment]
+1

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-67

**Comment by makinggoodsoftware** [comment]
This should be fixed now
