### ISSUE TITLE
Allow agLargeTextCellEditor to be readonly

### ISSUE THREAD

**Issue by vdurante** [ag-grid/ag-grid#4250]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I have a column with a long text string and ag-grid truncates the text to fit the screen.

![image](https://user-images.githubusercontent.com/5401232/102644113-09e9e280-413f-11eb-9fba-d15e005be3af.png)

Since the cell is non-editable, I can't open the cell editor to read the field. I wanted a feature where I can make agLargeTextCellEditor readonly so I can open the editor even though it is readonly:

![image](https://user-images.githubusercontent.com/5401232/102644203-2c7bfb80-413f-11eb-99c4-c3c52b92f16d.png)

**Comment by gportela85** [comment]
O ag-Grid disponibiliza alguns editores por padrão, mas voce pode simplesmente criar um fazendo o que voce precisa com poucas linha de código.
Eu criei esse plunkr com um exemplo: https://plnkr.co/edit/vsIEFQLQvjfzXP3K (Coluna Address).
