### ISSUE TITLE
Vue 2 + TypeScript + ag-grid -> errors when building the project

### ISSUE THREAD

**Issue by Mikilll94** [ag-grid/ag-grid#4251]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I have the following errors when running Vue 2 + TypeScript app which uses ag-grid.

```
No overload matches this call.
  The last overload gave the following error.
    Type 'typeof AgGridVue' is not assignable to type 'VueConstructor<Vue> | FunctionalComponentOptions<any, PropsDefinition<any>> | ComponentOptions<never, any, any, any, any, Record<...>> | AsyncComponentPromise<...> | AsyncComponentFactory<...>'.
      Type 'typeof AgGridVue' is missing the following properties from type 'VueConstructor<Vue>': extend, nextTick, set, delete, and 9 more.
    15 | export default Vue.extend({
    16 |   components: {
  > 17 |     AgGridVue: AgGridVue
       |                ^
    18 |   },
    19 |   data() {
    20 |     return {
ERROR in /Users/miwasnie/Desktop/ag-grid-test/src/App.vue(26,10):
26:10 Property 'columnDefs' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>'.
    24 |   },
    25 |   created() {
  > 26 |     this.columnDefs = [
       |          ^
    27 |       { headerName: "Make", field: "make" },
    28 |       { headerName: "Model", field: "model" },
    29 |       { headerName: "Price", field: "price" },
ERROR in /Users/miwasnie/Desktop/ag-grid-test/src/App.vue(31,10):
31:10 Property 'rowData' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>'.
    29 |       { headerName: "Price", field: "price" },
    30 |     ];
  > 31 |     this.rowData = [
       |          ^
    32 |       { make: "Toyota", model: "Celica", price: 35000 },
    33 |       { make: "Ford", model: "Mondeo", price: 32000 },
    34 |       { make: "Porsche", model: "Boxter", price: 72000 },
```

I have done everything like on "Get Started" page with the exception that I am not using the class component syntax.
https://www.ag-grid.com/vuejs-grid/

Here is the repro project
[ag-grid-test.zip](https://github.com/ag-grid/ag-grid/files/5718231/ag-grid-test.zip)

**Current behavior**
Project fails to build.

**Expected behavior**
There should no errors when building the project.

**Please tell us about your environment:**
macOS Big Sur 11.0.1
Visual Studio Code: Version: 1.52.1

* **ag-Grid version:** X.X.X
ag-grid-community: 24.1.0
ag-grid-vue: 24.1.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript: 3.9.3

**Comment by seanlandsman** [comment]
I see that you've raised a more recent issue regarding tests - the sample provided there works as expected so I assume that you've managed to resolve this issue.

We recommend using the component syntax (as you've done on your latest ticket) as using the alternative isn't well supported - see this thread for similar problems: https://github.com/vuejs/vue/issues/8721
