### ISSUE TITLE
ag-grid default css does not display checkbox when checkboxSelection=true is set

### ISSUE THREAD

**Issue by TechieQian** [ag-grid/ag-grid#4256]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour:
See codesandbox : https://codesandbox.io/s/sad-maxwell-h7zz3 
Taking a basic snippet from React's getting started, and adding `rowSelection="multiple"` to the grid and `checkboxSelection={true}` to the columnDef, you will see that the checkbox is hidden. However, when you simply apply the `ag-theme-alpine.css` theme (by uncommenting it in the sandbox), you will see the checkbox showing.

This seems to be intended behavior. Because even in the demo here: https://www.ag-grid.com/example.php?theme=ag-theme-alpine, by changing the theme to none, the checkbox disappears. Do we have to roll our own CSS for this?

Expected behaviour.
I expected the default css (ag-grid-community/dist-styles/ag-grid.css) would provide a basic functioning style out of the box without having to tweak. 

OS: Windows 10. Yarn. (but bug is reproducible on codesandbox as shown). 
ag-Grid community version: 24.1.0
ag-Grid react version: 24.1.1

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

The checkboxes in ag-Grid are actually icons which are provided by whatever theme is being imported.

If you would like to have styled icons and nothing else you could customise one of our themes or create your own.

Please see https://www.ag-grid.com/documentation/react/themes-customising/

Thanks
