### ISSUE TITLE
Problems with groupHideOpenParents of Ag Grid 24.1 in Angular 11

### ISSUE THREAD

**Issue by bigadolfo** [ag-grid/ag-grid#4259]
Hi!

The problem is very simple. I am using groupHideOpenParents and it works well in normal scenarios.  But when I change its value (for example from true to false) by code (so the user can choose it) the program does not change appearance

**This is the case (Height and theme works well):** 
 (this.gridApi as any).myObsrvr = new BehaviorSubject(null);
    (this.gridApi as any).myObsrvr.subscribe(value => {
      if (value != undefined) {
        
        let {formato, tema} =value;
        this.classTheme = tema;
        this.rowHeight = (tema =='ag-theme-balham'? 22:30)
        this.setHeight(this.rowHeight); 
        this.groupHideOpenParents = (formato == 'Moderno' ? 'false' : 'true')

        console.warn(formato, this.groupHideOpenParents );
        //alert(formato);
      }

Thanks in advance,
Adolfo

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
