### ISSUE TITLE
Vue unit tests - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Mikilll94** [ag-grid/ag-grid#4261]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I have a basic Vue app. When I am running unit tests I receive the following error:

```
 FAIL  tests/unit/example.spec.ts
  ● Test suite failed to run

    /Users/xyz/Desktop/ag-grid-test/node_modules/ag-grid-vue/lib/AgGridVue.js:20
    import { Component, Prop, Vue } from 'vue-property-decorator';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/ag-grid-vue/main.js:6:10)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.184s
```

To reproduce this bug:
1. Download and open this project.
[ag-grid-test.zip](https://github.com/ag-grid/ag-grid/files/5762111/ag-grid-test.2.zip)
2. Run `npm install`
3. Run `npm run test:unit`
4. The error pops up.

**Current behavior**
The error pops up.

**Expected behavior**
There should be no error.

**Please tell us about your environment:**
macOS 11.1

* **ag-Grid version:** X.X.X
ag-grid-community: 24.1.0
ag-grid-vue: 24.1.1

**Comment by seanlandsman** [comment]
Update your jest config to have the following:

`module.exports = {
  preset: '@vue/cli-plugin-unit-jest/presets/typescript-and-babel',
  transformIgnorePatterns: ["/node_modules/(?!ag-grid-vue)"],
}
`

This will exclude the `ag-grid-vue` component from being parsed by jest

**Comment by Mikilll94** [comment]
@seanlandsman 
Thanks. This is working. However, this should be mentioned in the docs here:
https://www.ag-grid.com/javascript-grid-testing-vue/
