### ISSUE TITLE
Documentation issue with the proper versioning

### ISSUE THREAD

**Issue by ashanperera201** [ag-grid/ag-grid#4262]
```
we have a paid version, we had a requirement in Filteration event change which is user keypress event in text filteration. we have gone through entire documentation we couldn't find the proper way to solve it. 
```

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
