### ISSUE TITLE
Testing Vue.js - typos in docs

### ISSUE THREAD

**Issue by Mikilll94** [ag-grid/ag-grid#4263]
This documentation page contains some typos:
https://www.ag-grid.com/javascript-grid-testing-vue/

![Screenshot 2021-01-04 at 21 47 38](https://user-images.githubusercontent.com/17653648/103578227-7a7e5680-4ed6-11eb-8a64-32e6e3e84079.png)

Should be: "Due to the asynchronous nature of **Vue**"

![Screenshot 2021-01-04 at 21 49 57](https://user-images.githubusercontent.com/17653648/103578411-ccbf7780-4ed6-11eb-9bf3-15fe33ee35d4.png)

Should be: "We can **now** use this utility method before each test or in the beforeEach to ensure the Grid is fully ready before continuing with **our** test:"

**Comment by seanlandsman** [comment]
Hi - thanks for the feedback - I've made the necessary change and this will be reflected on ag-grid.com when we do our next release (scheduled tomorrow)
