### ISSUE TITLE
Row Grouping - How to stop ag-grid from expanding rows when columns are hidden?

### ISSUE THREAD

**Issue by mkuznetsov-eagle** [ag-grid/ag-grid#4264]
**I'm submitting a.. **
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I created an example here: https://plnkr.co/edit/9dHAvzbRCoeoFxP8

In the example, all the columns are marked with `hide=true` and we are grouping the columns by Country and Year. We can expand under Year, but there is nothing to show because all the columns are hidden, so we just a huge empty space in place of all the rows.

**Expected behavior**

There should be some way of not having the row groups expand when there is nothing to show. The way this would look is that when the user tries to expand the row groups, nothing will happen.

Is there a workaround to achieve the same?

**Environment:**
Operating system: Mac, 
IDE: VS Code
package manager: NPM
Angular 8

* **ag-Grid version:** 24.1.0

* **Browser:Chrome/87.0.4280.88 **

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
