### ISSUE TITLE
ag-grid cell editing

### ISSUE THREAD

**Issue by josephkuruvilla** [ag-grid/ag-grid#4266]
I have a custom cell editor and i have a clear icon inside the editor. When clicking the clear icon, it needs to be clear the input field. When keydown event fires for the clear icon the cell editor is being stopped? How to stop this.

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
