### ISSUE TITLE
How to show table view horizontal

### ISSUE THREAD

**Issue by anandadake** [ag-grid/ag-grid#4270]
![ag grid table horizontallyjpg](https://user-images.githubusercontent.com/40342091/103754655-a44c9000-5032-11eb-8fe8-c52024e44d74.jpg)

**Comment by anandadake** [comment]
Is there any way to do this?

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
