### ISSUE TITLE
NG build prod fail during sourcemaps phase

### ISSUE THREAD

**Issue by jeandat** [ag-grid/ag-grid#4271]
**I'm submitting a ...**  (check one with "x")
```
[?] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

**Current behavior**
When compiling my app in production mode with Angular 11, ag-grid (19) fail. I was previously on angular 10.

```
Error: ./node_modules/ag-grid-angular/__ivy_ngcc__/dist/agGridColumn.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/xxx/Developer/xxx/liveaction/project-eyelo-ng2/node_modules/ag-grid-angular/__ivy_ngcc__/dist/agGridColumn.js: Column must be greater than or equal to 0, got -6
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] 
    ...
```

**Expected behavior**
Compilation should be ok.

**Please tell us about your environment:**

```
Angular CLI: 11.0.5
Node: 12.18.3
OS: darwin x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.3
```

* **ag-Grid version:** 19.0.0
I can't test right now with a more recent version cause it is quite a task since my predecessors added a lot of custom code.

* **Language:** TypeScript 4.0.3

**Comment by seanlandsman** [comment]
Please see the Angular Compatibility Chart here: https://www.ag-grid.com/documentation/angular/getting-started/#ag-grid--angular-compatibility-chart

For Angular 11 you need ag-Grid 24+ I'm afraid

**Comment by jeandat** [comment]
Ok thx, unfortunately I'm already using "skipLibCheck".
Regarding the migration path, except from this https://www.ag-grid.com/ag-grid-changelog/?fixVersion=25.0.0, is there something like an upgrade guide like angular do?
I noticed when trying a naive upgrade that some classes doesn't exists anymore and finding their new name is quite tedious.
