### ISSUE TITLE
Ag-Grid: Copy, Paste, and Context menu doesn't work in my angular project

### ISSUE THREAD

**Issue by abdelrhman1410** [ag-grid/ag-grid#4272]
Hi there!

I'm working on an Angular project that uses ag-grid, I'm trying to use copy & paste features of the grid but it didn't work for me 

I was reading the documentation in the following link and performed all instructions but I still stuck in there (nothing work at all).
Also, I noticed that the context menu doesn't appear with the right-click.

copy & paste docs: https://www.ag-grid.com/documentation/angular/clipboard/#toggle-paste-on--off

Angular Version: Angular CLI: 8.0.6

"ag-grid-angular": "^22.0.0",
"ag-grid-community": "^22.0.0",
"ag-grid-enterprise": "^22.0.0",

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
