### ISSUE TITLE
Unable to install latest version of ag-grid-enterprise/all-modules@latest

### ISSUE THREAD

**Issue by manojdcoder** [ag-grid/ag-grid#4273]
```
npm i @ag-grid-enterprise/all-modules@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ag-grid-enterprise/date-time-cell-editor@~25.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@ag-grid-enterprise/all-modules'
npm ERR! notarget 

```

**Comment by ErVishalM** [comment]
Same error is coming when i'm updating.

**Comment by seanlandsman** [comment]
Apologies for this - this has now been resolved.

Thank you for reporting this.

**Comment by seanlandsman** [comment]
> Same error is coming when i'm updating.
> ![Screenshot 2021-01-07 125249](https://user-images.githubusercontent.com/43669644/103863900-a7ee1e80-50e7-11eb-96b7-d4773ba4390a.jpg)

btw, you don't need @ag-grid-community/all-modules if you're installing @ag-grid-enterprise/all-modules - @ag-grid-enterprise/all-modules includes @ag-grid-community/all-modules

**Comment by ErVishalM** [comment]
@seanlandsman Thank you so much for this and what about 
`@ag-grid-community/angular` is this necessary? If I'm installing `@ag-grid-enterprise/all-modules`.

**Comment by seanlandsman** [comment]
yes, the framework modules are separate from the "core" grid modules - you still need to specify the appropriate fw module _if_ you're using a framework

**Comment by ErVishalM** [comment]
@seanlandsman Why this 3rdpartylicenses.txt file space has increased now (When I build my application in prod mode.)
Previous it was-
![image](https://user-images.githubusercontent.com/43669644/103877061-919d8e00-50fa-11eb-846c-6e003cc4c683.png)
Now it is-
![image](https://user-images.githubusercontent.com/43669644/103877170-b134b680-50fa-11eb-9634-2ff0051ce135.png)

Can you help me in this?

**Comment by seanlandsman** [comment]
I'd imagine that the licenses have changed (ie gotten bigger) from the version you were on to the new version and this is why the resulting licenses file is larger.

If you don't care about this file you can disable it's creation with `--extract-licenses=false`

**Comment by ErVishalM** [comment]
@seanlandsman extractLicenses i have used in angular.json. But i was thinking why license has been increased to 1mb but its ok. I just disablt it now! Thank you for helping me 😄
