### ISSUE TITLE
Ag-Grid: 「input \n in cell but get \\n」is this a bug or feature?

### ISSUE THREAD

**Issue by LynnWonder** [ag-grid/ag-grid#4278]
Hi there,
 I input ``\n`` in ag-grid bug got ``\\n`` in my database. It can be recalled in [my Plunker](https://plnkr.co/edit/sPvGxPLwl2wz5mxh):
- input ``this is a test\ntest``
- in the console you can see ``====> {"firstName":"Bob","lastName":"thisisa\\nsdf","gender":"Male","address":"1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763","mood":"Happy","country":"Ireland"}``

Plus, the code are copied from https://www.ag-grid.com/documentation/javascript/cell-editing/#example-cell-editing

The cell has changed consumer's data and I do not think it's a good feature. Maybe you have a consideration about how to display escape character,  However consumers can convert their escape character to their expected data and show it in cell.

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
