### ISSUE TITLE
To Show the filter type with floating filter

### ISSUE THREAD

**Issue by nitu023** [ag-grid/ag-grid#4284]
[x] support request =>
I am working on an application in which React is the FE technology. I am using AG grid to display the content from the server side. I setup floating filters in the ag grid as per the documentation. Client has included a requirement for showing the the type of filter being used (equal to, starts with, ends with etc). I checked the AG grid documentation but couldn't find an option to show the filter type. Please let me know if we can do customisation to show the filter type. 
```

**Current behaviour**
Please refer to this image.
https://user-images.githubusercontent.com/53781745/104281099-efebb780-54d2-11eb-81b3-63532869b347.png

**Expected behaviour**
To show filter type with floating filter. please refer to below image.
https://user-images.githubusercontent.com/53781745/104281137-fed26a00-54d2-11eb-86cd-67872cd1eb22.png

**Please tell us about your environment:**
 Ubuntu : 20.04.1 LTS,
Running on chrome browser

* **ag-Grid version:** X.X.X
 ag-grid-react : 23.2.1,
 Using MIT licenced ag grid

* **Browser:**
Chrome Browser

* **Language:** JavaScript, react js

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
