### ISSUE TITLE
Angular Documentation for Webpack 3 incorrect

### ISSUE THREAD

**Issue by W4775** [ag-grid/ag-grid#4287]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
Documentation on (https://www.ag-grid.com/documentation/angular/webpack-3/)

**Current behavior**
Documentation shows Enterprise dependency as:

// or, if using Enterprise features
npm i --save @ag-grid-community/all-modules @ag-grid-community/angular

**Expected behavior**
Should be:

// or, if using Enterprise features
npm i --save @ag-grid-enterprise/all-modules @ag-grid-community/angular

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for this, we have fixed this and will be available in our next release

https://github.com/ag-grid/ag-grid/commit/588e150d6923bb695ffd53a875b68d733c4e085e

Thanks!
