### ISSUE TITLE
How to make cells interact in editing state

### ISSUE THREAD

**Issue by wangyfax** [ag-grid/ag-grid#4289]
When a whole row is in editing state, how to change a cell to refresh the current row, or how to make other cells interact when changing a cell

![image](https://user-images.githubusercontent.com/48970114/104557599-7ee80380-567c-11eb-889e-734fe316014f.png)

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
