### ISSUE TITLE
There will be a error "ERROR Error: Virtual list has not been created." when I use the 25.0.0 version

### ISSUE THREAD

**Issue by MengChuilu** [ag-grid/ag-grid#4290]
**I'm submitting a bug report** 

**Providing a Reproducible Scenario**
I upgrad the newst version of ag-grid(25.0.0).  Everything works, except there be a error in console, I use 23.2.0 before.
The error is 
```
ERROR Error: Virtual list has not been created.
    at SetFilter.push../node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js.SetFilter.refresh (ag-grid-enterprise.cjs.js:43334)
    at ag-grid-enterprise.cjs.js:43162
    at ag-grid-community.cjs.js:9825
    at new AgPromise (ag-grid-community.cjs.js:9800)
    at AgPromise.push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.AgPromise.then (ag-grid-community.cjs.js:9823)
    at ag-grid-enterprise.cjs.js:43162
    at ZoneDelegate.invokeTask (zone.js:431)
    at Object.onInvokeTask (core.js:26247)
    at ZoneDelegate.invokeTask (zone.js:430)
    at Zone.runTask (zone.js:198)
```

**Current behavior**
a error in console. but every thing works.

**Expected behavior**
No error

**Please tell us about your environment:**
windows10

* **ag-Grid version:** X.X.X
25.0.0

* **Browser:**
edge 87.0.664.75
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by MengChuilu** [comment]
Thanks， I'll try that.

**Comment by aaronfessler** [comment]
In 25.0, changing:

`this.gridApi.setFilterModel([]);`

to 

`this.gridApi.setFilterModel(null);`

Fixed this issue for me.
