### ISSUE TITLE
ag-dnd-ghost element hidden when fullscreen is on

### ISSUE THREAD

**Issue by jogoertzen-stantec** [ag-grid/ag-grid#4292]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

The 'ghost' element (see screenshot below) does not appear when dragging a column header in an ag-grid that is a descendent of an element that (1) is a descendent of the document body, and (2) has had the [`requestFullscreen()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen) function called on itself.

**Expected behavior**

The 'ghost' element (ie. the box that says 'Athlete' in the screenshot below) should appear and follow the mouse cursor when dragging a column header.

![image](https://user-images.githubusercontent.com/41205049/104508049-e599ee00-55a4-11eb-8444-718010e73248.png)

**Minimal reproduction of the problem with instructions**

- Browse [here](https://www.ag-grid.com/documentation/examples/grouping/keep-columns-visible/modules/angular/index.html) in Chrome.
- Open dev tools.
- Paste the following command into the console.

```
document.querySelector('div#app').requestFullscreen()
```

- Drag a column header
- Observe the 'ghost' element is not visible.

**What is the motivation / use case for changing the behavior?**

Retain full ag-grid functionality when it is a descendent of a 'fullscreen' element other than the document body or any of its ancestors.

**Please tell us about your environment:**

* **Operating system:** Microsoft Windows 10 Enterprise 10.0.18363 Build 18363

* **ag-Grid-Enterprise version:** 25.0.0

* **Browser:** Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by gportela85** [comment]
this problem was fixed by https://github.com/ag-grid/ag-grid/commit/db58429015327937987298459fffcc8b0d56d660
