### ISSUE TITLE
"Shift" Column resize has weird behavior when resizing pinned columns on the right

### ISSUE THREAD

**Issue by EdgeTechnologiesInc** [ag-grid/ag-grid#4294]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Hold down "shift" while trying to resize right pinned columns in your own demos.
- `colResizeDefault = "shift"` (which is what we use) will always give awkward resizing behavior with pinned columns.

What happens is that the other side of the column that you are NOT grappling will resize creating an awkward UX experience.

**Current behavior**
When `colResizeDefault = "shift"` you get weird column sizing behavior on right pinned columns.  Especially if you're just trying to give the pinned columns more or less space by dragging the divider.  You can see this behavior on your own demos just by holding down shift while interacting with pinned columns on the right.  The other side of the column that you are trying to resize will move, not the grappled side.

**Expected behavior**
I believe that if you are trying to drag the pinned columns divider it should always resize without the "shift" behavior even if that's on by default.  There's no reason to have the behavior of the other side of the column resizing.

**Please tell us about your environment:**
MacOS, Angular 9, Webstorm 

* **ag-Grid version:** 24.1.0

* **Browser:** All browsers.

* **Language:** [Typescript 3.7.5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request.

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
