### ISSUE TITLE
SSRM Tree Data - Documentation incorrect

### ISSUE THREAD

**Issue by ATrogolo** [ag-grid/ag-grid#4296]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**
This [page of the docs](https://www.ag-grid.com/documentation/react/server-side-model-tree-data/) uses method *purgeServerSideCache*. 
Isn't it deprecated in favour of *refreshServerSideStore* as documented in your [changeLog](https://www.ag-grid.com/ag-grid-changelog)? 
Can I create a PR for that document? 
Where's the repo? 

* **ag-Grid version:** 25.0.0

Best regards,
Andrea

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We have updated the docs accordingly. This will be available in our next release

Thanks!
