### ISSUE TITLE
Customise the Theme Look - invalid SCSS syntax in the example

### ISSUE THREAD

**Issue by Mikilll94** [ag-grid/ag-grid#4298]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://www.ag-grid.com/documentation/vue/getting-started/#customise-the-theme-look-2

The code used in "Customise the Theme Look" is not working. This is not a valid SCSS syntax.

![Screenshot 2021-01-15 at 20 46 44](https://user-images.githubusercontent.com/17653648/104771766-e08a9980-5772-11eb-8a9b-0adac8df8482.png)

![Screenshot 2021-01-15 at 20 50 38](https://user-images.githubusercontent.com/17653648/104772189-542ca680-5773-11eb-8335-421f14a6d0b0.png)

**Expected behavior**
The example should work.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thahks for the heads up, we will path this, the correct test should be:

I'll patch this, the correct text should be

<style lang="scss">
  @import "../node_modules/ag-grid-community/src/styles/ag-grid.scss"; 
  @import "../node_modules/ag-grid-community/src/styles/ag-theme-alpine/sass/ag-theme-alpine-mixin.scss"; 

  @include ag-theme-alpine((
    add-row-background-color: #ACE
  ));
</style>
