### ISSUE TITLE
Can't process data filled by Fill Handle.

### ISSUE THREAD

**Issue by abdelrhman1410** [ag-grid/ag-grid#4299]
Hi there!

I'm working on an Angular project using ag-grid.
I enabled the Fill Handle feature to allow the user to fill cells easily

but I need to do some processing on the date he entered by this feature, so like the Clipboard (copy & paste) feature; Are there any ways to process the data filled by Fill Handle? 

Fill Handle docs: https://www.ag-grid.com/documentation/angular/range-selection-fill-handle/

Angular Version: Angular CLI: 8.0.6
"ag-grid-angular": "^23.0.0",
"ag-grid-community": "^23.0.0",

**Comment by gportela85** [comment]
In the docs posted, there is a section called "Using Custom User Functions", you can see it in action on the "Day of the Week" column.
https://www.ag-grid.com/documentation/angular/range-selection-fill-handle/#example-using-custom-user-functions
