### ISSUE TITLE
syntax error on js bundle ag-grid-enterprise v25

### ISSUE THREAD

**Issue by mahdiporkar** [ag-grid/ag-grid#4300]
Dear All
I have syntax error in  ag-grid-enterprise.js file at  line 96549, column 15 and some another line 
thanks 
best regards

**Comment by zz9pa** [comment]
Here too - and in v25.0.1

**Comment by makinggoodsoftware** [comment]
Hi,

Can you check if this still happens in v25.0.1. if so, could you provide us with a repro?

Thanks

**Comment by zz9pa** [comment]
Yes - its in v25 and v25.0.1
If you grab : 
https://raw.githubusercontent.com/ag-grid/ag-grid/master/enterprise-modules/all-modules/dist/ag-grid-enterprise.js

I get an error on line 90591

        var childFilterComps = _ag_grid_community_core__WEBPACK_IMPORTED_MODULE_0__["_"].flatten(this.recursivelyAddComps(columnGroup.getChildren(), newDepth));
        if (columnGroup.isPadding())
            return childFilterComps;
        }


Looks to be missing a "{" after the if (columnGroup.isPadding()) ? 
If I add that - I get an error on line 96556

        return {
            id: this.prefixId(this.getId()),
            state: {
                blockNumber: this.getId(),
                startRow: this.startRow,
                endRow: this.startRow + this.storeParams.cacheBlockSize,
                pageStatus: this.getState()
            }
            else if (rowNode.group) { <<-----


Which just doesnt look right at all..

**Comment by mahdiporkar** [comment]
this link is good and has not any syntax error 

https://unpkg.com/@ag-grid-enterprise/all-modules@25.0.1/dist/ag-grid-enterprise.js

**Comment by makinggoodsoftware** [comment]
Hi, @mahdiporkar thanks for pointing that!

Going to close this, but feel free to open a new issue if this persist.

Note that we don't monitor closed issues

Thanks
