### ISSUE TITLE
Changelog version 24.0.0 has typos

### ISSUE THREAD

**Issue by raukouski** [ag-grid/ag-grid#4301]
https://github.com/ag-grid/ag-grid/blob/53059eb7f771d8c7268a4cd7e070694e8a2a34d9/grid-packages/ag-grid-docs/src/ag-grid-changelog/versionReleaseNotes.php#L171

Needs to bechanged to <li>Grid Column API 'setColumnState()' is replaced with 'applyColumnState()'. The new method is similar but more powerful / flexible.</li>

Should be Grid Column API, not Grid API.
Should be setColumnState, not setColumn**s**State

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We just fixed this!

Thanks

**Comment by raukouski** [comment]
Hi @makinggoodsoftware !
As I can see there is one more thing to fix:
![image](https://user-images.githubusercontent.com/19466678/105510188-68c2ee80-5cdf-11eb-9ae4-946cb20c5688.png)
I mentioned it in the issue but unfortunately, it was ignored.
