### ISSUE TITLE
Usual Rows can be full-width

### ISSUE THREAD

**Issue by abadakhshan** [ag-grid/ag-grid#4302]
**I'm submitting a 
```
[] bug report 
[x] feature request 
[] support request 
```

**Current behavior**

the rows' width equals sum of columns' width and there is an empty space after last column.

![2222](https://user-images.githubusercontent.com/16729513/104814734-c78ef080-5825-11eb-902e-10cb17bc2965.png)

**Expected behavior**

It would be nice if there is a option that rows would be full-width. In this situation if sum of columns' width is less than available space, row should fill available space exactly like header row does currently.

![111](https://user-images.githubusercontent.com/16729513/104814738-ccec3b00-5825-11eb-9b29-8c68c315ac9c.png)

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
