### ISSUE TITLE
Property enableBrowserTooltips not working for grid tables headers.

### ISSUE THREAD

**Issue by gloammer** [ag-grid/ag-grid#4304]
If enableBrowserTooltips = true, default browser tooltip should be used.
Now this property works for grid items, but not work for headers.

This behavior is probably due to the fact that postConstruct in the wrapper is called before the base class postConstruct. And as a result this setting is not applied to the header.
Pay attention to Component,postConstructOnComponent, HeaderWrapperComp.postConstruct (call of setupTooltip).

**Comment by nathanpower** [comment]
Same issue here, all tests with assertions on browser tooltips for headers failing for v25

**Comment by nathanpower** [comment]
`title` attribute is missing from the relevant example here: https://www.ag-grid.com/documentation/examples/component-tooltip/default-tooltip/modules/vanilla/index.html

**Comment by gportela85** [comment]
@gloammer Thanks for reporting. Fixed by https://github.com/ag-grid/ag-grid/commit/502b3afa2c03d733c710b6d790fbbc2e240bf192
