### ISSUE TITLE
Mat-Datepicker fail to change date value

### ISSUE THREAD

**Issue by andreachirico11** [ag-grid/ag-grid#4305]
I'm submitting a ...
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'

Providing a Reproducible Scenario:
[LInk To Sample](https://stackblitz.com/edit/ag-grid-angular-hello-world-jzuexj?file=src%2Fapp%2Fapp.component.html)

Current Behaviour:
The calendar closes without changing the data because of the suppress option:
`[stopEditingWhenGridLosesFocus]="true" `

Requested Behaviour:
We need to use the MatPicker with the suppress option activated.

Please tell us about your environment:
Browser: Chrome 87.0.4280.141
angular/core: 10.1.1,
ag-grid-angular: 24.1.0
ag-grid-community": 24.1.0

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks

**Comment by Piyushchoudhary** [comment]
Any resolution on the above ticket ? It was closed but the issue still persists.
