### ISSUE TITLE
Possibility to order columns by date in pivot mode

### ISSUE THREAD

**Issue by ikhudo** [ag-grid/ag-grid#4308]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://codesandbox.io/s/bold-cdn-f2r5q?file=/src/Grid.tsx

**Current behavior**
Columns in pivot mode are automatically ordered alphabetically
ex. Apr 2020, Aug 2020, Dec 2020, Feb 2020, ...

**Expected behavior**
To have possibility to order columns by date 
ex. Dec 2020, Nov 2020, Oct 2020, ...

**Please tell us about your environment:**
https://codesandbox.io/s/bold-cdn-f2r5q?file=/src/Grid.tsx

* **ag-Grid version:** 25.0.1

* **Browser:**
Google Chrome

* **Language:** all

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by ernestkkb** [comment]
Hi @ikhudo , I am currently facing this issue and I was wondering if you managed to find any resolution? Thank you! :)
