### ISSUE TITLE
New row inserted on random position when using transaction on a sorted table

### ISSUE THREAD

**Issue by hectorAmaral** [ag-grid/ag-grid#4312]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I'm using the applyTransaction method to add a new row in a specific index, 
I'm seeing some weird behavior when the table is sorted by a different order than the default.

The row is being added to a random position

**Steps to reproduce**

The issue can be reproduced in the following Plunker that I created:
[https://plnkr.co/edit/6vxAkMCGhSmzdYt8](https://plnkr.co/edit/6vxAkMCGhSmzdYt8)

1. Click the "Add Items addIndex=2" button
2. Notice the new "Honda 1" row has been added between the Ford and Porche rows (at index 2)
3. Refresh the Plunker live preview to start fresh
4. Sort the table by "Clothes" column in ascending order
5. Click the "Add Items addIndex=2" button
6. Notice the new "Honda 1" row has been added before Toyota at the beginning of the list (at index 0) which is wrong, it should've been added between Porche and Ford (at index 2).

**Expected behavior**
The added row should be placed in the expected index based on the current sorting order.

**Please tell us about your environment:**

I created a Plunker based on one of the official examples:
[https://plnkr.co/edit/6vxAkMCGhSmzdYt8](https://plnkr.co/edit/6vxAkMCGhSmzdYt8)

* **ag-Grid version:** 25.0.1

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

* **Language:** TypeScript

**Comment by EdTech101** [comment]
I'm having the same issue.

**Comment by maxzamarripa** [comment]
I have the same issue

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by hectorAmaral** [comment]
Great, thanks @makinggoodsoftware 👍🏼

**Comment by AhmedAGadir** [comment]
Hi, 

Thank you for your email. We have looked into this and determined that this is expected behaviour:

see GIF

![Large GIF (796x324)](https://user-images.githubusercontent.com/33138421/105727073-9cda2180-5f22-11eb-8123-790d4d98708b.gif)

- apply sort
- click button
- remove sort

the row has is added at the specified index.

If you would like the row to added at a specific index while sorting is applied  we would recommend using post-sort. see https://www.ag-grid.com/documentation/javascript/row-sorting/#post-sort
