### ISSUE TITLE
Grid does not respect columns order

### ISSUE THREAD

**Issue by aailyin** [ag-grid/ag-grid#4314]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Plunker: https://plnkr.co/edit/EhmX1ZsHbg6eJPA2

Accepted reproducible scenarios are:
- Load plunker
- Click on **Exclude Medal Columns** button
- Click on **Include Medal Columns** button

This is a copy of [this example](https://www.ag-grid.com/documentation/javascript/column-updating-definitions/#adding--removing-columns) with changed order of **Gold** column.

**Current behavior**
**Gold** column is displayed after **Date** column.

**Expected behavior**
Based on the statement 

> Columns are positioned in the grid according to the order the Column Definitions are specified in the Grid Options.

 from [this page](https://www.ag-grid.com/documentation/javascript/column-definitions/?framework=angular) **Gold** column should be displayed after **Country** column like in the array of column definitions.

Environment:
* **ag-Grid version:** 25.0.0

* **Browser:** User Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"

* **Language:** all

**Comment by tr1stan** [comment]
Looks like if you're dynamically setting the column definitions and you care about the order of the columns, you need to use the `applyColumnDefOrder=true` property.

> If the desired behaviour is that Columns should be ordered to match the new set of Column Definitions, set the grid property applyColumnDefOrder=true.

https://www.ag-grid.com/documentation/angular/column-updating-definitions/#applying-column-order

**Comment by aailyin** [comment]
@tr1stan Yes, you're right. The guide is pretty unclear about this case. Thank you!

**Comment by JohnRDOrazio** [comment]
Thanks for that @tr1stan , I had to add this property when updating from node 14 to node 16, and AG Grid from 25.1 to 25.3. For some reason it didn't seem necessary when using node 14 and ag-grid 25.1 ...
