### ISSUE TITLE
sizeColumnsToFit() with relative column sizes depending on content

### ISSUE THREAD

**Issue by DDoerner** [ag-grid/ag-grid#4317]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'
```

We would like to define a table that fills the whole width of its container (thus using `api.sizeColumnsToFit()`) but resizes the columns based on their content, dividing extra space accordingly. The default behavior is that each row is given the average column width, independent of what content they hold. It seems that this should be possible using flex attributes, but the column definitions / apis do not provide any way to do it. 

Am I missing something or do I have to try to write my own column resizer?

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
