### ISSUE TITLE
Cell text selected when both rowSelection='multiple' and enableCellTextSelection='true' are set

### ISSUE THREAD

**Issue by zabibabar** [ag-grid/ag-grid#4322]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

To reproduce the bug, add enableCellTextSelection=true to the plunker in this [example ](https://www.ag-grid.com/documentation/angular/row-selection/#example-multiple-row-selection)found in the docs. 

I have done this on my own: https://plnkr.co/edit/w7Xnjk1TkY4waFKx

In my plunker above, if you select the first row, and then Shift+click the 4th row, you will see that cell text is selected. 
![Capture](https://user-images.githubusercontent.com/20039068/106174878-76ef8f80-6163-11eb-9190-02ea605d1b3c.PNG)

**Current behavior**
When rowSelection='multiple' and enableCellTextSelection='true' are both set, selecting multiple rows using shift causes all the cells between the last selected row and the currently selected row to get highlighted.

**Expected behavior**
When rowSelection='multiple' and enableCellTextSelection=true are both set, Shift+Click should only select rows not cell text. 

**Please tell us about your environment:**
Windows 10, Node 14.15.1

* **ag-Grid version:** X.X.X
@ag-grid-community/angular v25.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
* **Language:** TypeScript 4.0.5

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this is just the default browser behavior for selecting text

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by zabibabar** [comment]
Appreciate the response! Yes, I would love to hear any workarounds for this if anyone in the community has dealt with this issue

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
