### ISSUE TITLE
Bug Report: TooltipMouseTrack causes endless growth in width for custom tooltips

### ISSUE THREAD

**Issue by gueste** [ag-grid/ag-grid#4324]
**I'm submitting a Bug Report**

**Current behavior**
Width of custom tooltips grows endlessly when using tooltipMouseTrack along with the custom tooltip and moving the mouse while the tooltip is open.

**Expected behavior**
Tooltip width should not grow endlessly when moving the mouse while the tooltip is open.

**Environment:**
Windows 10, Chrome 88

**ag-Grid version:** 25.0.1

**Demo:**
https://plnkr.co/edit/5esbSFfFJoeNzZNT?preview

**Comment by gueste** [comment]
It happens when the custom tooltip class has padding or border.

**Comment by gportela85** [comment]
@gueste set your custom tooltip with box-sizing border-box. It's a quick way to make borders and padding not get in the way of calculating size.
https://plnkr.co/edit/GIfCBQc5APdikqDX

**Comment by gueste** [comment]
Thanks for the hint!
