### ISSUE TITLE
Horizontal scroll bar that shouldn't be there in React

### ISSUE THREAD

**Issue by Vampiro** [ag-grid/ag-grid#4325]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behaviour**
When following the React Getting Started Guide, if you click the "Open in StackBlitz" button, a grid will come up with a horizontal scrollbar that isn't very useful.

https://www.ag-grid.com/documentation/react/getting-started/
https://stackblitz.com/edit/ag-grid-react-hello-world

**Expected behavior**
Scrollbar doesn't appear.

**Please tell us about your environment:**
Windows

* **ag-Grid version:** 25.0.1

* **Browser:** Chrome and Firefox

![image](https://user-images.githubusercontent.com/7528160/106390114-d7294000-63b4-11eb-9c93-7f4ee06fbe37.png)

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

Note that you have many options to manage the width of the columns:
https://www.ag-grid.com/documentation/angular/column-sizing/ 

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
