### ISSUE TITLE
Is it possible to use cellRendererSelector and SSRS Row Grouping in one table?

### ISSUE THREAD

**Issue by katarzynam1405** [ag-grid/ag-grid#4327]
[x] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

Hi,

I would like to use 'cellRenderer' and 'SSRM Row Grouping' functionality at the same time, but it's cause following error: 
**Error: ag-grid: you can't specify both, the selector and the component of ag-grid for : cellRenderer.**

My implementation looks similar to this e.g.: 
```
        <AgGridReact
            rowModelType="serverSide"
            onGridReady={onGridReady}
           ...
            defaultColDef={{
                editable: true,
                sortable: true,
                enableRowGroup: true,
                ...
                cellRendererSelector: (params) => {
                
                      const someXYZDetails = {
                         component: 'xyzCellRenderer'
                      };

                      const someABCDetails = {
                        component: 'abcCellRenderer',
                     };

                    if (params.data.type === 'XYZ') {
                          return someXYZDetails;
                    }
          
                   if (params.data.type === 'ABC') {
                       return someABCDetails;
                   }
                 }

            }}
        />
```
I using @ag-grid-community/react v. 24.0.0, @ag-grid-enterprise/all-modules v. 24.0.0 modules.
I'm not sure if there is a problem with my implementation or those functionality are not supported, yet.

Thank you in advance for your response.

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
