### ISSUE TITLE
partial store and grouping

### ISSUE THREAD

**Issue by eyallibarak** [ag-grid/ag-grid#4328]
Bug - very few rows show when using partial store and grouping.

I use 'partial' (serverSide). Rows load fine (first bunch). I then group a column - the request and response from server has all the correct values - but only the first 2 values from that column show on the table.
When turning partial off, grouping works fine.

See attached screenshots.

![aggrid-partial-grouping-bug-1](https://user-images.githubusercontent.com/78151143/106581764-e7275800-654b-11eb-873a-871a072340fb.png)

![aggrid-partial-grouping-bug-2](https://user-images.githubusercontent.com/78151143/106581755-e5f62b00-654b-11eb-9d48-dd2b4e87be01.png)

![aggrid-partial-grouping-bug-3](https://user-images.githubusercontent.com/78151143/106581762-e68ec180-654b-11eb-9297-b83703a0e4f2.png)

ag-grid enterprise v25.0.0

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by eyallibarak** [comment]
Our support license has long expired, and this is a new system in early development we build with newer version of ag-grid and different technologies. And it looks like a bug rather then something wrong I'm doing in my code.
