### ISSUE TITLE
Columns Tool Panel not showing hidden columns in aligned grid

### ISSUE THREAD

**Issue by dylan0d** [ag-grid/ag-grid#4330]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Expected behaviour: columns tool panel hides and shows columns on both aligned grids
Actual behaviour: tool panel can hide columns but doesn't show them

Our website has two aligned grids, one of which features a columns tool panel. We recently upgraded to v24.1.0 and noticed that while the grids are still synchronised for horizontal scrolling and collapsing column groups, using the tool panel to hide and show columns now only works for hiding columns. Attempting to show a hidden column via the tool panel will show it on the top grid but not the bottom panel. The linked plunker shows this behaviour using a modified example from the ag grid docs 
[https://plnkr.co/edit/j7CpVlYOZFrCtyDY](https://plnkr.co/edit/j7CpVlYOZFrCtyDY)

Looking at the console logs on this plunker you can see that there's a variable being set to undefined somewhere along the line which I imagine is causing the problem, but having never contributed to ag grid before I'm not sure where to go looking at the code myself to get to the bottom of this.

Note as well that setting the version back to 24.0.0 in the index.html makes things work as expected, so whatever is causing this was likely introduced after that. The issue is also present in the most recent version of ag-grid, although we discovered it targeting 24.1.0

**Comment by makinggoodsoftware** [comment]
Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks
