### ISSUE TITLE
There is  some problem in source

### ISSUE THREAD

**Issue by abadakhshan** [ag-grid/ag-grid#4331]
It seems there is a merging issue in ag-grid source

check this 

https://github.com/ag-grid/ag-grid/blob/845cd53c7869b6d56be47394b1a13a37f9b54ae1/community-modules/core/src/ts/gridApi.ts#L1319

**Comment by seanlandsman** [comment]
Thank you for reporting this - I can confirm that there is indeed a merge issue here.

This will be resolved in our next release.

**Comment by abadakhshan** [comment]
Thank you @seanlandsman 
I think there are more compilation errors on your source.

For example:

"ServerSideTransaction" is used **[here](https://github.com/ag-grid/ag-grid/blob/845cd53c7869b6d56be47394b1a13a37f9b54ae1/community-modules/core/src/ts/entities/gridOptions.ts#L626)**

but there is no import for this type in that file.

"./interfaces/serverSideTransaction" is used in many places. but there is no file named "./interfaces/serverSideTransaction"

Where can I find a valid source to create a PR?

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for this, you can create a PR from latest branch, note though that we don't merge this automatically, but we will take them into consideration.

Alternatively, you can list them here too

Thanks for your help!
