### ISSUE TITLE
Snap the right edge of the last column to grid's right side

### ISSUE THREAD

**Issue by duxard** [ag-grid/ag-grid#4335]
**I'm submitting a ...**  
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
HI Team, a have a simple data grid, there are 4 columns, all of them are resizable. (grid's total width is 100%).
I noticed that if I resize (squish) any of the columns, all other ones get pushed to the left - as a result I see this blank rectangle:

![issue1](https://user-images.githubusercontent.com/18247015/107022165-0e13a300-6773-11eb-9c4b-d6e80806aee5.JPG)

**Expected behavior**
Is there a way to circumvent appearing of this blank space? (Kind of pin the **right edge of the last** column, and at the same time still allow other columns to get resized?

**Please tell us about your environment:**
Windows OS

* **ag-Grid version:** 
"ag-grid-angular": "24.1.0"
"ag-grid-community": "24.1.0"

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"

* **Language:** 
 TypeScript 3.7.5 | ES6/7

**Comment by florianJacques** [comment]
Use "flex: 1" column property for the last row ?

**Comment by duxard** [comment]
> Use "flex: 1" column property for the last one ?

Hi Jacques,
thank you for reply!

I tried the following configuration (where "color" is the last column):
```
{ 
 field: 'color',
 resizable: true, 
 flex: 1
}
```
Unfortunately  it did not make the trick :(

**Comment by florianJacques** [comment]
As tu essayer avec toute les autre colonne avec le config "flex: 0" ?

**Comment by duxard** [comment]
Yeah, I tried this option as well - it did not help either

**Comment by florianJacques** [comment]
https://www.ag-grid.com/documentation/react/column-sizing/#column-flex
You can read the documentation

**Comment by duxard** [comment]
Thanks for assistance! It really helped me
