### ISSUE TITLE
Persistent rectangle above the vertical scrollbar

### ISSUE THREAD

**Issue by duxard** [ag-grid/ag-grid#4336]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```
**Current behavior**
Hi Team, I noticed that there is a blank rectangle above the vertical scrollbar (in "headers" section):
![issue2](https://user-images.githubusercontent.com/18247015/107022988-056f9c80-6774-11eb-81c0-04e446849a70.JPG)

That is ok, but what I would like to achieve is to have it persistently in place while scrolling horizontally.
For the moment being, if I scroll horizontally, it vanishes:
![issue3](https://user-images.githubusercontent.com/18247015/107023402-93e41e00-6774-11eb-885c-053e868694f7.JPG)

**Expected behavior**
Is there a way to have a persistent rectangle above the vertical scrollbar when scrolling horizontally?

**Please tell us about your environment:**
Windows OS

* **ag-Grid version:** X.X.X
"ag-grid-angular": "24.1.0"
"ag-grid-community": "24.1.0"

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"

* **Language:** 
TypeScript 3.7.5 | ES6/7

**Comment by duxard** [comment]
Hi Team,
I have created a demo example on stackblitz to reproduce the issue:

https://stackblitz.com/edit/angular-ag-grid-angular-pcsg6r

You can resize the grid to see the problem (just to remind you - i've been wondering if it's possible to have a blank rectangle above a scrollbar during horizontal scroll):

![image](https://user-images.githubusercontent.com/18247015/107639240-9c3dcc80-6c3e-11eb-967e-d7426e0b49d8.png)

Thanks, 
Aleksandr

**Comment by kudasai20** [comment]
@duxard You can try this, but it's a hacky solution, it also access internal properties of the grid to get the size of the scrollbar, but it does what you want.

https://stackblitz.com/edit/angular-ag-grid-angular-aypvq5

There is this block in the styles.css file

```css
.my-custom-spacer {
  position: absolute;
  top: 0;
  height: 100%;
  right: 0;
  background-color: grey;
}
```

And this will add the rectangle inside every header `my-grid-application/my-grid-application.component`

```js
const scrollWidth = params.api.gridPanel.scrollWidth;

document.querySelectorAll('.ag-header').forEach((header) => {
    const mySpacer = document.createElement('div');
    mySpacer.classList.add('my-custom-spacer');
    mySpacer.style.width = scrollWidth + 'px';
    header.appendChild(mySpacer);
});
```

**Comment by duxard** [comment]
Thank you, **kudasai20**,  for looking into the problem!
I will try out your solution!
