### ISSUE TITLE
$(div).load(html),and html with "ag-grid-enterprise.js",throw js error(ag-Grid V25.0.0-V25.0.1)

### ISSUE THREAD

**Issue by yangyuanlife** [ag-grid/ag-grid#4337]
in my project,i use the jquery to load the html page,and the html page with the "ag-grid-enterprise.js",
like this:
![ag1](https://user-images.githubusercontent.com/40287241/107138948-b764bf80-6952-11eb-9ad4-e357f838f1ba.png)
* **ag-Grid version:** V24.0.0-V24.1.0
everything is OK;
* **ag-Grid version:** V25.0.0-V25.0.1
throw js error like this:
![ag2](https://user-images.githubusercontent.com/40287241/107139634-b4b89900-6957-11eb-8691-b6c931b903d2.png)

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
