### ISSUE TITLE
  In react i am using material ui DataGrid and with checkboxSelection api but when i select checkbox it will not select but when I click on any other row it selects the checkbox. I used disableClickEventBubbling: true for disabling the <select> when clicking row but clicking checkbox itself is  not working

### ISSUE THREAD

**Issue by sumitduwal** [ag-grid/ag-grid#4338]
const columns = [
  { field: 'id', headerName:  'Created on', width: 150 ,
  disableClickEventBubbling: true,

},]

<DataGrid rows={rows}
  columns={columns}
  pageSize={10}
  paginationMode='server'
 
  showColumnRightBorder
   hideFooterPagination
   showToolbar
   autoHeight

   onSelectionChange={({rowIds}) => setSelectedRecords(rowIds)}
  // onSelectionChange={selectedRecords}
  //  onClick={()=>console.log("data after the click" , selectedRecords)}
   checkboxSelection
   />

**Comment by makinggoodsoftware** [comment]
Hi,

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

Thanks

**Comment by ashishsid99** [comment]
how to checboxselection color?
