### ISSUE TITLE
Pivot Mode and domLayout="autoHeight" are incompatible

### ISSUE THREAD

**Issue by daniel-kleinstein** [ag-grid/ag-grid#4339]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The bug reproduces easily - use AgGridReact, set domLayout="autoHeight" and try to enable pivot mode - the columns will not appear - seemingly the height of the div isn't set correctly. I hacked a solution for this - I have a `onColumnPivotModeChanged` callback that tracks whether pivot mode is enabled or not, and if it's being enabled then I manually set the height to a height that works.. But this is hacky and bound to break in the future (I explicitly reference `$(".ag-column-select-list .ag-column-select-virtual-list-container .ag-virtual-list-item")`)

This is with `domLayout="autoHeight"`: 

![image](https://user-images.githubusercontent.com/1128381/107148719-6f976580-695d-11eb-81cb-d5b2adae5362.png)

And this is without, with manually set width and height:

![image](https://user-images.githubusercontent.com/1128381/107148770-aff6e380-695d-11eb-8e63-217102e4b8de.png)

**Expected behavior**

Columns are visible in pivot mode

**Please tell us about your environment:**
Standard - WSL, React-based ag-grid

* **ag-Grid version:** 25.0.1 

* **Browser:** Chrome 86

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by daniel-kleinstein** [comment]
Hi! This wasn't a support question - I actually mentioned how I solved the problem on my own - this was a bug report to help you guys out :)
