### ISSUE TITLE
ag-grid documentation lists an event “animationQueueEmpty”. Does it not exist anymore?

### ISSUE THREAD

**Issue by innovation16** [ag-grid/ag-grid#4344]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

I am using loki tests (https://loki.js.org/) for my react component that renders an ag-grid. There is a timing issue between grid's render and when loki takes the screenshot making the tests flaky. 
I was hoping to use "animationQueueEmpty" event to tell loki when to take the screenshot but it doe not seem exist in version "24.0.0". 
Is this correct?
Are there any other events triggered by ag-grid that suit my use case.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi, 

I've checked the animationQueueEmpty to see if it works in both the latest version and version 24 - both work as expected. Please see the following sample: https://plnkr.co/edit/TCiUaHKkwVUYOySJ?preview

Note that the name of the callback is constructed by prefixing the event name with `on`. This is documented at the top of the Grid Event page: https://www.ag-grid.com/documentation/javascript/grid-events/

So the event animationQueueEmpty will be `onAnimationQueueEmpty`.

Hope this helps - I will close this ticket, feel free to reopen if the issue persists in your end.

Thanks

**Comment by innovation16** [comment]
Hi Shuheb,
Thanks for getting back to me. You are right, is is working. 
The issue is that its not being published in types somehow.

**Comment by michaelyu-aspentech** [comment]
Hello,

My Angular application used to work with this event "animationQueueEmpty", however after I upgrade ag-grid to 26.1.0, this event never triggered, and I also cannot find this event in online document. 
Is this event removed from 26.1.0 version? any replacement event introduced?

**Comment by shuheb** [comment]
Hi @michaelyu-aspentech 

Please see the breaking changes for v26 in our [changelog](https://www.ag-grid.com/changelog/?fixVersion=26.0.0 )

`AG-5534 - The AnimationQueueEmptyEvent has been removed, the grid API method isAnimationFrameQueueEmpty() can be used instead.`

**Comment by michaelyu-aspentech** [comment]
HI @shuheb,

thanks for your update. Before I ask I search long time in Ag Grid changelog page and google as well, but got nothing. It will greatly help us doing upgrade in our applications, if we can search correct results from changelog.
