### ISSUE TITLE
Multiple custom input cell-editors, renderers with stopEditingWhenGridLosesFocus and single fullRow edit type

### ISSUE THREAD

**Issue by sergePSE** [ag-grid/ag-grid#4347]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

**Providing a Reproducible Scenario**
https://stackblitz.com/edit/angular-ivy-u4p3gc

The problem in the nutshell
There is implemented custom renderer and editor. Editor has \<input\> element. Ag-grid consumes custom framework components with Ag(Editor/Renderer)Component interface. Ag-grid config contains such properties as stopEditingWhenGridLosesFocus, editType: 'fullRow', rowSelection: 'single'. Table contains >= 3 columns with that custom editor and renderer. When \<input\> html element is focused and another one selected from different row, there are 2 focusout events called: on focusout from the current element and then focusout for the none (deselect full row). At the same time ag grid replaces editor with renderer (and visa versa). In the middle of the processing editor becomes null and all its properties, function become undefined.

**Current behavior**
Use Chrome (V8) browser.
Double click on any edit cell to focus inside <input> tag. Then, select at the same way another row. On stackblitz the browser is going to be frozen. Locally produces "Cannot read property 'stopEditing' of undefined"

**Expected behavior**
Double click on any edit cell to focus inside <input> tag. Then, select at the same way any another row. Expected the previous row to be deselected and entered to renderer mode, the clicked row to enter to editor mode without exceptions.

**Please tell us about your environment:**
Node.js v12.16.1
Angular v10.1.0

* **ag-Grid version:** 25.0.1

* **Browser:**
Chrome 88.0 (V8) browser. Not Firefox (not reproducable).

* **Language:** [TypeScript 4.0.2 | ES6/7]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
