### ISSUE TITLE
State update doesn't cellRenderer params

### ISSUE THREAD

**Issue by sk1794** [ag-grid/ag-grid#4348]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

I am using react,
I have used the cellRenderer to use custom cell, and passing state in cellRendererParams, when the state is updated, the param which i have sent didn't get updated as per the state

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by JaniPM** [comment]
I have this same issue with ag-grid-react 25.1.0. It used to work fine in v23 at least. Would be nice to know why the cellRendererParams are not updated anymore.

**Comment by nishanthgurung** [comment]
I see similar issue. Any update on why it is happening so or if there is a plan to fix this issue in future releases of ag-grid ?

**Comment by rpoconn** [comment]
It looks like ag-grid copies params that are passed to the renderer for some reason.
I passed a getter function in the params.   Inside the renderer I just call the getter, and it will get the original object.
Pass something like this on the column definition:  

cellRendererParams: {
    objectGetter:  () => myDynamicObject  
}

// Inside the renderer:
const myDynamicObject  = params.objectGetter()

Seems like a bug in ag-grid, but this workaround does fix the problem.

**Comment by StephenDunneIRE** [comment]
@rpoconn thank you for providing a work-around! This issue was bugging me for hours & never considered passing an object-getter myself!

**Comment by onurbekiroglu** [comment]
> 

This workaround doesn't work on 26.2.0.

**Comment by lm93547** [comment]
> > 
> 
> This workaround doesn't work on 26.2.0.
> 
> Edit: I bypassed this issue using ref

what did you do  for this?

**Comment by paulinosantos** [comment]
If you are using React.JS make sure you are not passing columnDefs within gridOptions. The agGrid [documentation ](https://www.ag-grid.com/react-data-grid/grid-interface/)states

> Note the if using Grid Options, the grid will not react to property changes. For example gridOptions.rowData will only get used once when the grid is initialised, not if you change gridOptions.rowData after the grid is initialised. For this reason, while using React, it's best only use Grid Options for properties that do not change.

I had a similar issue were 'props' wasn't being updated as I was expecting within a `valueFormatter ` function I was defining within `columnDefs` that I was passing in `gridOptions`

Moving `columnDefs `out of `gridOptions `fixed my issue

```
 <AgGridReact
          onGridReady={onGridReady}
          gridOptions={gridOptions}
          columnDefs={getColumnDefs()}
          >
        </AgGridReact>
```

**Comment by eliaharris** [comment]
https://github.com/ag-grid/ag-grid/issues/4858#issuecomment-1185578378

**Comment by Nikoobox** [comment]
> Solution described here:
> 
> [#4858 (comment)](https://github.com/ag-grid/ag-grid/issues/4858#issuecomment-1185578378)

this is NOT a solution
