### ISSUE TITLE
Auto size not working on column group

### ISSUE THREAD

**Issue by Prithivraj200** [ag-grid/ag-grid#4350]
Hi,

In Pivot mode, I am using column group as Country. I have given width as 80px. Some user wants to see the full country name. So I have added autoSizeColumn. But it's not working.

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
