### ISSUE TITLE
Why the change detection is not made ALSO on the entire row?

### ISSUE THREAD

**Issue by highfield** [ag-grid/ag-grid#4351]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

Mine is rather a question, than a bug report.

Why the change detection is not made *ALSO* on the entire row, and relies only on the fields' values?

I mean for React (and immutable mode), where I can replace the entire rows set all at once. If replace a single row of the input array, I'd expect the change detector should trigger the refresh of *ALL* the cells in that row. By the way, the cell renderers have their own embedded change detection, so that wouldn't impact much on the actual DOM manipulation.

Instead, I must define a valid field name in the column definition, otherwise the cell won't be refreshed (check the "dummy" in the first column definition). However, that could be a problem where the cell itself should render as an aggregation/composition of many fields.

The only solution I've found, is to define a custom object for that kind of cells. To me, it seems a bit complicated for a so easy (and common) task.

Here is a sandbox where the problem is clear: https://codesandbox.io/s/ag-grid-update-test-j9f3f?file=/src/App.tsx

Well, assuming all that is by design, I'd like to hear from you what are the reasons to avoid a trivial change detection at row-level.

Thank you in advance.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
