### ISSUE TITLE
Custom column definition

### ISSUE THREAD

**Issue by florianJacques** [ag-grid/ag-grid#4352]
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Hello, have you thought of a feature to add custom parameters for the definition of columns?

Example:
```
{
  headerName: 'Test',
  headerTooltip: 'is a test',
  field: 'test',
  colId: 'test',
  custom: {
      hasFooterValue: true,
      footerType: 'average',
      type: 'fixedNumber',
      .....,
  },
}
```

This would make it easier to create factories to declare cell renderer and cell formatter for csv export for example.

**Comment by makinggoodsoftware** [comment]
Hi,

We have this:

https://www.ag-grid.com/documentation/react/column-definitions/#custom-column-types

Also note that you can set any property that you want, ag-grid will show you a warning, but that is only to warn you that these properties are not recognised

**Comment by florianJacques** [comment]
Thx, if is juste a warning, good for me :')

**Comment by sebammon** [comment]
@makinggoodsoftware Is it possible to opt out of the warnings, since they are showing up in production? Perhaps if they only show in the development environment?

**Comment by StephenCooper** [comment]
> @makinggoodsoftware Is it possible to opt out of the warnings, since they are showing up in production? Perhaps if they only show in the development environment?

You can use the following property to opt out of these warnings. 
https://ag-grid.com/javascript-data-grid/grid-options/#reference-miscellaneous-suppressPropertyNamesCheck
