### ISSUE TITLE
Is column's "hide" property suppose to not render column at all or make it invisible?

### ISSUE THREAD

**Issue by desprit** [ag-grid/ag-grid#4356]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

https://www.ag-grid.com/documentation/javascript/column-properties/#reference-columnsOnly
I tried "hide" property expecting to hide one of my columns from end-user but still be able to see the code in the markup. However, the column is not rendered at all. Is this an expected behavior?

**Providing a Reproducible Scenario**
http://plnkr.co/edit/PBnPwvinGJLsLnGU?preview

**Current behavior**
Column is not rendered.

**Expected behavior**
Column is rendered but hidden.

**ag-Grid version:** X.X.X
23.0.2

**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
