### ISSUE TITLE
getRowHeight not used with infinite scroll

### ISSUE THREAD

**Issue by olivier-gravwell** [ag-grid/ag-grid#4357]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I'm using the AG-Grid component and it seems getRowHeight is never called when using the infinite scroll.

**Expected behavior**

Use the getRowHeight in the options when the getRows of the datasource is called.

**Please tell us about your environment:**

Ubuntu. Angular 9

* **ag-Grid version:** X.X.X

```
		"ag-grid-angular": "^25.0.1",
		"ag-grid-community": "^25.0.1",
```

* **Browser:**
Chromium 88.0.4324.150

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this is not supported for the infinite row model

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
