### ISSUE TITLE
Make text inside rowData bold

### ISSUE THREAD

**Issue by mhalesto** [ag-grid/ag-grid#4358]
Is it possible to make text inside rowData bold reading it from an array?

**Comment by Paul6552** [comment]
It would be more appropriate to ask this on stackoverflow. Github is an issue tracker. 
If you entered "ag-grid formatting" on google you would come across value formatters and cell renderers.
You are searching for cell renderer:
[Cell renderer](https://www.ag-grid.com/documentation/vue/component-cell-renderer/)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
