### ISSUE TITLE
Why ag-grid lose focus after scroll with InfiniteRowModel?

### ISSUE THREAD

**Issue by aamanunin** [ag-grid/ag-grid#4359]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
I use ag grid with infinite row model, suppressCellSelection = true, and use navigateToNextCell for custom navigation. This work good, but if i scroll by mouse, grid called gridApiMethod and my grid loses focus(document.activeElement === body). After lose focus navigateToNextCell and other event with keyboard not work, and i need click in grid after scroll.

As far as I understand, the focus is on the cell, but with a virtual scroll, the cell is removed from the DOM and the focus is lost.
How i can fix it?

**Expected behavior**
After scroll grid dont lose focus

**Please tell us about your environment:**
Windows 10, Angular 11

* **ag-Grid version:** X.X.X
    "@ag-grid-enterprise/all-modules": "25.0.1",

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"

* **Language:** [TypeScript 4.1]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
