### ISSUE TITLE
How to test `onGridSizeChanged` logic?

### ISSUE THREAD

**Issue by rcketscientist** [ag-grid/ag-grid#4361]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

I've followed the documentation for testing in React (https://www.ag-grid.com/documentation/react/testing/).  I can test general shape of data and various data model aspects.  

I've now implemented a dynamic width feature similar to (https://www.ag-grid.com/documentation/react/grid-size/#dynamic-resizing-without-horizontal-scroll).  I'd like to test it, but `onGridSizeChanged` does not fire in tests.  Is there some way I can coax that to fire in the test, or is that a limitation of the testing harness?  (I've confirmed the feature does work in a browser).

* **ag-Grid version:** 24.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
