### ISSUE TITLE
ag-grid polluting the DOM

### ISSUE THREAD

**Issue by codeStryke** [ag-grid/ag-grid#4362]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

If reporting a bug make sure to state.

**Current behavior**
When using ag-grid inside a shadowRoot I've noticed that the grid creates empty `div` elements on the `body` and doesn't clean it up. This is because the cleanup is not handled in [this line of code](https://github.com/ag-grid/ag-grid/blob/01e0497b34644a1e40a407600b3fe953c3040999/community-modules/core/dist/es6/utils/browser.js#L123)

**Expected behavior**
ag-grid should not pollute the DOM

**Please tell us about your environment:**
using ag-grid in a web component. Initializing the grid in `connectedCallback` so the grid is ready before the DOM.

* **ag-Grid version:** 25.1.0

* **Browser:**
latest chrome

* **Language:** [all]

**Comment by gportela85** [comment]
@codeStryke Thanks for reporting this. I've created a ticket and will be fixed soon.

**Comment by ravi-fe** [comment]
Found the same problem with focus/tabbing while ag-grid is part of shadow dom.
http://jsfiddle.net/8yxz0qc7/2/
Click on the first cell of data. (Toyota current)
Expected: move focus to End of the header.
Current: Stuck/out of focus.
