### ISSUE TITLE
设置许可证无效  请问Vue如何设置license key

### ISSUE THREAD

**Issue by CuiYuXi** [ag-grid/ag-grid#4363]
import 'ag-grid-enterprise';
import { LicenseManager } from "@ag-grid-enterprise/core";
LicenseManager.setLicenseKey("My Key");

**Comment by CuiYuXi** [comment]
我是在main.js 里面设置的

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
