### ISSUE TITLE
suppressKeyboardEvent and suppressHeaderKeyboardEvent

### ISSUE THREAD

**Issue by paulburz** [ag-grid/ag-grid#4364]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**
onCellKeydown is triggered even though suppressKeyboardEvent and suppressHeaderKeyboardEvent are set to true.

**Expected behavior**
onCellKeydown should not trigger if I suppress the events....(this was working)

**Please tell us about your environment:**
Windows 10, VsCode, NPM

* **ag-Grid version:** X.X.X
^24.0.0

* **Browser:**
Chrome
![o2eLRi9eNR](https://user-images.githubusercontent.com/11335844/108702409-e31aa480-7511-11eb-9923-bfe66dc82c7c.png)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
