### ISSUE TITLE
onCellValueChanged is being triggered when the cell did not changed (giving undefined as newValue).

### ISSUE THREAD

**Issue by sFerreiraDev** [ag-grid/ag-grid#4365]
I am not a paid customer of ag-grid. This was something that was found while developing e2e tests. It might be, or not, of interest to the ag-grid team to fix it. I'm just pointing it out because it goes against the documentation and would like to know if there will be something done about this. Thank you a lot for your time!

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
A stackblitz forked from the documentation(https://stackblitz.com/edit/ag-grid-angular-hello-world): https://stackblitz.com/edit/ag-grid-angular-hello-world-1buekb?file=src/app/app.component.ts

**Documentation:**
"After a cell **has been changed** with default editing (i.e. not your own custom cell renderer) the cellValueChanged event is fired".

**Current behaviour**
When opening an **empty** cell and pressing enter key, the onCellChanged event is triggered and gives undefined as the "newValue".
According to the quoted documentation above, the cell didn't change so it shouldn't be triggered.

**Expected behaviour**
When opening an empty cell and hit enter key, the onCellChanged should not be triggered (Like it happens when the cell has a value already). 

**Please tell us about your environment:**
Ubunutu 20.04

* **ag-Grid version:** X.X.X
Bug found on version 24.1.0
Given stackblitz is 25.0.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript (Angular 11 as the main frameWork)

Might be useful information:
When opening an **empty** cell, typing anything, then clear it (so it's empty again) and pressing enter key, the onCellChanged event is **NOT** triggered.

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, it works correctly as it is impossible to tell for every app if the value entered should be considered different thant the current one, so we always fire it, you receive then both value, so you can decide to ignore the event

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by sFerreiraDev** [comment]
Thanks for your brief reply! Even though I find it unnatural that the event is triggered in that situation, I totally understand your position on this and that was the main thing I was looking forward to knowing, so we could decide on how to address this in our application.

Closing this as it fulfilled its purpose.

**Comment by JanHuege** [comment]
For me even with chaning a value, which was undefined beforehand, the onCellValueChanged Event does not contain the newValue. Only a second edit changes the value. There seems to be some kind of racecondition/order of execution preventing the onCellValueChanged Event to see the value dispatched by the default celleditor

Version 30.2.1

**Comment by kaciakmaciak** [comment]
This also happens for the dates. If date editor is open, and date is unchanged the event is fired. Could the `equals` fn (from the column definition) be used to check if the previous and new value match?

Cheers.
