### ISSUE TITLE
Aligned-Grid should synch up row grouping and sort order of columns between grids.

### ISSUE THREAD

**Issue by Pankaj262** [ag-grid/ag-grid#4366]
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

Current behavior
currently ag grid out of the box aligned grid synch up , horizontal scroll , column width , column order, col grouping  between two grids.

Expected behavior
API should expose some configuration so that column sort and row grouping should also get aligned between grids . We might achieve this by playing with API with custom logic but it would be better if we don't mix up out of box functionality with custom logic to achieve synching of column between two grids for row group and sort.

Minimal reproduction of the problem with instructions
Open the following URL in Chrome, Latest Edge
1) https://www.ag-grid.com/documentation/react/aligned-grids/
2) Sort First grid based on any column, only first grid is sorted  , second grid sort is unchanged .
3) Same applies for row grouping, for that we need to enable row grouping to drag columns to row group ribbon.  

What is the motivation / use case for changing the behavior?
When we talk about align grid , it gives a impression that all columns are aligned b/t grids . Row grouping visually change the overall appearance of columns so it would be better if we synch up both the grids for row groups , same applied for sort behavior.

Please tell us about your environment:

ag-Grid version: 24.0.0 (react) 
Browser: Chrome , Version 88.0.4324.182 (Official Build) (64-bit)
Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

In any case, we appreciate the feedback, note that this is going to get flagged with the label good suggestion. We are going to close this issue but having this issue being flagged with good suggestion means that it will be potentially be considered for development.

Please keep an eye on our pipeline as this might appear there.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks for your feedback

**Comment by makinggoodsoftware** [comment]
Hi,

I raised this, but the changes and risks associated with changing the code to accomplish this would be far too great.

 I am afraid that we won't be able to raise anything for this in our pipeline.

Thanks
