### ISSUE TITLE
chart Toolbar not present in cross filtered charts

### ISSUE THREAD

**Issue by shreyanshparakh** [ag-grid/ag-grid#4369]
[] bug report => see 'Providing a Reproducible Scenario'
[

Current behaviour: No chart toolbar present in cross filtered charts.
Expected behaviour. Chart toolbar to present in the cross filter charts.

* **ag-Grid version:** 25.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
