### ISSUE TITLE
Unable to edit tooltips of bar in crossFiltered charts

### ISSUE THREAD

**Issue by shreyanshparakh** [ag-grid/ag-grid#4370]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'

```
Plunkr: https://plnkr.co/edit/XK0MS6l5rl13sran

Current behaviour: Unable to edit tooltip of bar chart in integrated cross filtered charts.
Expected behaviour. To remove decimal points of tooltip. A quick fix is highly required.

* **ag-Grid version:** 25.1.0

**Comment by shreyanshparakh** [comment]
am I the only one facing this issue?

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

Thanks for your feedback

____


If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
