### ISSUE TITLE
Registering Cell Editor Component when not using a Vue JS builder

### ISSUE THREAD

**Issue by coder832** [ag-grid/ag-grid#4372]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hi, I am working on a development involving the use of ag-grid with VueJS. However, due to the project setup, I am not using the standard VueJS builder setup, instead using the approach found here: https://github.com/riodw/ag-grid-vue-cdn. I am defining a VueJS instance for the page and binding it to a DOM element.   

Now the issue comes with trying to create custom cell editor components as I am not able to follow the examples provided on the ag-grid website like this one https://plnkr.co/edit/?p=preview&preview as I am using Vue without a builder. Is there any work around to achieve this for my setup?   

I have tried registering a component within the script section of the example linked however each of my attempts has resulted in the error `Could not find component _____, did you forget to configure this component?` when trying to use the cell editor.  

Any advice into this would be much appreciated, as I have been unable to find any examples of using vue components with ag grid for a setup that does not use a builder.

**Comment by seanlandsman** [comment]
Does this help?

https://plnkr.co/edit/xX3Skfo8xiye87PF

**Comment by coder832** [comment]
> Does this help?
> 
> https://plnkr.co/edit/xX3Skfo8xiye87PF

Many thanks, that was a really helpful example, managed to get everything up and running.
