### ISSUE TITLE
Ability to edit predeined context menu options

### ISSUE THREAD

**Issue by Mshardul** [ag-grid/ag-grid#4374]
I am submitting a

```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**

Adding 'copy' / 'paste' / 'export' or any other predefined options in the context menu is very easy. However, for now they are not at all customizable.

**Expected behavior**

The predefined custom-menu options should be customizable eg. changing the 'copy' icon, or the name displayed etc.

* **AG Grid version:** 25.1.0

* **Browser:** Google Chrome, Mozilla Firefox, Safari

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

In any case, we appreciate the feedback, note that this is going to get flagged with the label good suggestion. We are going to close this issue but having this issue being flagged with good suggestion means that it will be potentially be considered for development.

Please keep an eye on our pipeline as this might appear there.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks for your feedback

____


If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
