### ISSUE TITLE
Cannot re-arrange value columns in pivot mode

### ISSUE THREAD

**Issue by dflatman8** [ag-grid/ag-grid#4375]
**Current behavior**
Steps to reproduce:
https://www.ag-grid.com/documentation/javascript/column-state/#column-events
Press: Pivot On, Agg Func On, Reverse Medal Order
The medal order does not rearrange

**Expected behavior**
In pivot mode, I would expect to be able to rearrange the value columns by calling columnApi.applyColumnState() with applyOrder = true and state defining the order of columns by their colIds.

* **AG Grid version:**
25.1.0

* **Browser:**
Microsoft Edge 88.0.705.63

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
