### ISSUE TITLE
Indicating required columns using cellstyles, row selection issue

### ISSUE THREAD

**Issue by coder832** [ag-grid/ag-grid#4376]
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'

ag-grid-vue

Hi, I am working on a project involving ag grid. I have several columns that are required to be filled in. To indicate this I am using cellStyle to set the background colour to red when empty and white when the user has entered a value in the cell. My issue now is when selecting rows, having changed the background colour to white, the cell does not show the standard light blue colour that all the other cells in the selected row show. 

I have made a Plunker demonstrating this: https://plnkr.co/edit/jhNjl4xx3T88dHsi.

As can be seen in the "Required Column", when you enter a value the cell background changes to white. However, when you now select the row, the cell background remains white as opposed to blue like the other two cells in the row selection. 

Is there a simple way of correcting this that I have missed in the documentation. As an aside, I was also wondering if there is any way of changing the cell background colours from within cell renderer components, preventing the need for the use of cellStyle.

Many Thanks!

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
