### ISSUE TITLE
The backspace key navigate to the previous page when i am using a cell editor on Firefox-Angular

### ISSUE THREAD

**Issue by CherifKods** [ag-grid/ag-grid#4378]
I have reported this bug 4 months ago but the issue was closed #4217 

I noticed that the examples was changed also, there is now a difference between the javascript framework and the angular framework examples ..

I am facing a bug with costume cell editor and using backspace key when I am using **firefox** instead of just entering in edit mode with an **angular** project 

**The scenario**
1-Select a cell of the numeric column
2- Press « backspace » button to delete the value and enter in edit mode

**The current behaviour**
Pressing on backspace key makes the navigator go backwards to a previous page

**The expected behaviour**
Pressing on backspace key and we delete the value and enter in edit mode

An example that confirms this behaviour : [https://www.ag-grid.com/documentation/angular/component-cell-editor/#simple-cell-editor-example](https://www.ag-grid.com/documentation/angular/component-cell-editor/#simple-cell-editor-example)

A video that demonstrates the bug and the scenario :  
![cell-editor-firefox-bug](https://user-images.githubusercontent.com/9007445/109633717-b5081680-7b48-11eb-8f77-0df2e7539510.gif)

Development environment:

Operating system : Windows 10
IDE : Visual studio code
package manager : npm

The bug exists with angular 8 and 11

**ag-Grid version:** 24.0.0 and 25.1.0
**Angular version :** 8.3.19 and 11.2.1
**typescript:** 3.5.3 and 4.0.7

**Browser:** 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this is just the default behaviour for firefox when pressing backspace

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
