### ISSUE TITLE
Customer HeaderTemplate not showing in parent column group

### ISSUE THREAD

**Issue by nodruob13** [ag-grid/ag-grid#4379]
**I'm submitting an issue when applying custom header template on parent column group**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Custom header template html code **not applied to the grid**. As you can see in this **codePen** : https://codepen.io/nodruob13-the-bold/pen/bGBMMrz

**Expected behavior**
Custom header template html code should be showing in the grid. In the codePen example : Parent header column should have the ** prefix. **Only children have it**.

* **AG Grid version:** 25.1.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as column groups dont take column templates

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
