### ISSUE TITLE
Having issue with refreshing on a page > 2, but the results of page 1 are not re-queried (i.e. they are the same results of the page I refreshed on.

### ISSUE THREAD

**Issue by JimmyBlundell** [ag-grid/ag-grid#4380]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
We are using query params to keep track of searchText, searchCol, page, etc. Let's say I navigate over to page 3 on the table. I then refresh the page. While my params are saved on the reload (searchText, searchCol, and page), and while I do indeed reload back onto page 3, if I navigate to page 1, it does not refire any query and it shows the same results as page 3 (or whatever page I may have refreshed on).

**Expected behavior**
Ideally, I would be able to refresh and keep all the current filters as it already does. However, if I navigate to page 1, it, too, should fire off a query to return results that would otherwise be stored in page 1. It's not doing that, however, and treats page 1 the same as whatever page I refreshed on.

**Please tell us about your environment:**
Linux, working on Chrome (or anything other than Internet Explorer, really)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
