### ISSUE TITLE
AG-4878 marked as fixed in 25.1.0 change log but the bug is still there

### ISSUE THREAD

**Issue by endan715** [ag-grid/ag-grid#4381]
According to the change log https://www.ag-grid.com/ag-grid-changelog/, AG-4878 should be fixed in 25.1.0. However it is still not working.

This is the original bug report:

https://github.com/ag-grid/ag-grid/issues/4213

This is the new plunker demo shows that the bug is still in 25.1.0, row drag handle is still not showing:

https://plnkr.co/edit/SFmYViT5NPA05MtW

**Comment by gportela85** [comment]
@endan715 Whenever you change the ColDefs, the cells are not updated, so you will need to manually call `refreshCells({ force: true })`. The bug reported by AG-4878 is that even when that method was called, the rowDragger wasn't showing.

See the docs here: https://www.ag-grid.com/documentation/angular/column-updating-definitions/#changing-column-definition

See the updated plunker here: https://plnkr.co/edit/YaLIvAq4pKRetcwc
