### ISSUE TITLE
[Column Sizing] Add API for resetting the column sizing to the default

### ISSUE THREAD

**Issue by croraf** [ag-grid/ag-grid#4383]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

ag-grid sizes columns very nicely according to my column definitions. The user has the option to resize some columns if needed.
I would like to have an api method that resets the column sizing when called (resizing all columns to default size and clearing any flags that indicate that flex columns have been touched).

Is there an API method for that, and if not can it be added?

**Please tell us about your environment:** all

* **AG Grid version:** 25.1.0

* **Browser:**
all

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
