### ISSUE TITLE
SSRM Tree Data - Documentation incorrect

### ISSUE THREAD

**Issue by ATrogolo** [ag-grid/ag-grid#4384]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Current behavior:

The sentence in the [sorting section of SSRM TreeData](https://www.ag-grid.com/documentation/react/server-side-model-tree-data/#sorting): "Sorting works in the same way when using Tree Data as when not using Tree Data with one exception." makes no sense.

How can I create a PR for the document?
Where's the repo?

ag-Grid version: 25.1.0

Best regards,
Andrea

**Comment by makinggoodsoftware** [comment]
Hi,

At the moment we don’t have a safe mechanism to automatically merge PRs so is actually best to just report them like this.

I will raise this with our product team

Thanks for letting us know!

**Comment by kiril-matev** [comment]
Hello @ATrogolo!

Thank you for reporting this - much appreciated!

We've added a work item to expand on the documentation in this section with additional details. 

However, I can clarify the documentation on our website today:

When using Tree Data with server-side row model with full store, sorting will be performed without a data refresh from the server. Sorting will be performed on the client as all the data for any expanded levels is already available on the client.

When using Tree Data with server-side row model with partial store, sorting will require a data refresh from the server. Sorting will be performed on the server, as the client only has a subset of the rows at any one level.

Please see the difference between the two types of data stores here:
https://www.ag-grid.com/javascript-grid/server-side-model-row-stores/

Please use the appropriate data store to deliver the optimal user experience for your users.
