### ISSUE TITLE
reset and restore state of column in group and pivot not working

### ISSUE THREAD

**Issue by mahdiporkar** [ag-grid/ag-grid#4385]
Hello Dear
reset and restore state of column not working in pivot and row group 
[https://www.ag-grid.com/documentation/javascript/column-state/](url)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
