### ISSUE TITLE
Subtotal is not getting calculated in ag-grid with groupMultiAutoColumn ?

### ISSUE THREAD

**Issue by sachinmishra-gep** [ag-grid/ag-grid#4386]
Could someone from ag-grid will help to fix this issue ?

https://stackoverflow.com/questions/66518396/subtotal-is-not-getting-calculated-in-ag-grid-with-groupmultiautocolumn

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
