### ISSUE TITLE
The basic ag-Grid UI is broken on after updating Chrome to v89

### ISSUE THREAD

**Issue by eyalella** [ag-grid/ag-grid#4387]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
Reporting a bug: The basic ag-Grid UI is broken on after updating Chrome to v89.
1. Update Chrome to `89.0.4389.82`
2. Go to [ag-grid.com/example](https://www.ag-grid.com/example.php)
3. See broken UI
![image](https://user-images.githubusercontent.com/3458336/110290677-b5def380-7ff3-11eb-888f-02040e8ac450.png)

**Current behavior**
UI breaks (side menu text and icons not aligned)

**Expected behavior**
UI doesn't break (side menu text and icons are aligned)

* **Browser:**
Chrome (`89.0.4389.82`)

**Comment by gportela85** [comment]
Thanks for reporting, we already have a ticket tracking this: AG-5142

**Comment by gportela85** [comment]
@eyalella This was filed as a BUG in Chrome and has been fixed already - https://bugs.chromium.org/p/chromium/issues/detail?id=1189046

You can temporarily fix this on your app by adding: 
```css
.ag-side-button-label {
    width: fit-content;
}
```

**Comment by gportela85** [comment]
@eyalella Just an updated that the new version of Chrome is out and they have fixed the issue.

![Screen Shot 2021-05-01 at 10 01 04 AM](https://user-images.githubusercontent.com/7908562/116777107-7a492e80-aa64-11eb-89c4-9ff7f6cdaedd.png)
