### ISSUE TITLE
Cannot read property 'EnterpriseCoreModule' of undefined

### ISSUE THREAD

**Issue by varunsree** [ag-grid/ag-grid#4390]
Trying to convert ag-grid to the enterprise version I got the error like "Cannot read property 'EnterpriseCoreModule' of undefined"

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
