### ISSUE TITLE
CellEditor does not work with fullRowEdit

### ISSUE THREAD

**Issue by rashmipyrumas** [ag-grid/ag-grid#4396]
I am using ag grid community edition for one of my react editable table.
I want to update my table with the new feature called "oncellvaluechanged" which is available only in the enterprise edition. 
so thought of switching to enterprise edition. 
I installed trial version of enterprise edition.

Facing below issue.

When adding the new row and trying to change any dropdown value update event is calling automatically and getting a warning in console saying
"AG Grid: popup cellEditor does not work with fullRowEdit - you cannot use them both - either turn off fullRowEdit, or stop using popup editors."

Along with this when my prop values changed "cellEditorParams" options are not updating on the fly.

Current behavior: cb
Expected behavior: eb

cb:
-> When add new row to table and start editing cell options automatically it is calling update event.

eb:
-> When editing the row need to edit cell value also (when i choose one dropdown value another dropdown options need to update with new options) 

cb:
-> After the table loaded completely trying to update dropdown options with the new prop which is not happening,

eb:
-> when editing the row if my prop changes should be able to update my dropdown options.

Kindly help me with the same
Thanks in advance.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

In any case, we appreciate the feedback.

Please keep an eye on our pipeline as this might appear there.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks for your feedback

____


If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by rashmipyrumas** [comment]
@makinggoodsoftware,

Thanks for the update. As per your comment can i consider the above mentioned features not available in ag grid community and enterprise edition ?

Thanks in advance.
