### ISSUE TITLE
Updating data and column defs affects the order of columns if some of the columns have the same names

### ISSUE THREAD

**Issue by daedalius** [ag-grid/ag-grid#4399]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Updating column definitions with other ones with some common "Header Names" place those columns before the others.
https://plnkr.co/edit/JzIlfIlliz8J8a2E

**Current behavior**
F.e. we have common "Price" column definitions. In both cases, they are the last columns. But when it comes to updating, this column becomes the first.

**Expected behavior**
Updating column defs and data doesn't affect the order. In the example column "Price" should be the last column in both cases.

**Please tell us about your environment:**
* **Operating system**: Windows
* **AG Grid version:** 25.1.0
* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
* **Language:** JS

**Comment by dstj** [comment]
I have the same kind issue of issue with column ordering being different than the one in the `columnDefs` array after recreating the array.

In my case, I toggle the first column's "existence" and it gets recreated as the last column instead of as the first like the array says.

Here's my reproduction: https://stackblitz.com/edit/angular-ivy-adjd1u?file=src/app/app.component.ts.

* AG Grid version: 24.1.0 (same w/ 25.1.0)
* Angular 9 (same w/ 11)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hello!

We've had a look at both of the repros provided and investigated them. This is not a bug, please see the following link for an explanation: https://www.ag-grid.com/javascript-grid/column-updating-definitions/#applying-column-order 

In short, to achieve the result you are looking for, add the property applyColumnDefOrder=true.

I've forked both examples below showing these now working as expected with the property added:

@daedalius - https://plnkr.co/edit/o56SjiH80Xte3XfD
@dstj - https://stackblitz.com/edit/angular-ivy-invjgd?file=src%2Fapp%2Fapp.component.html 

We will mark this issue as closed, please feel free to reopen if the issue does persist.

Thanks,
Shuheb
