### ISSUE TITLE
Extra line appears above the column header when multiple <AgGridColumn> are wrapped by <React.Fragment> or <>

### ISSUE THREAD

**Issue by trellis-dshrestha** [ag-grid/ag-grid#4403]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When multiple <AgGridColumn> are wrapped by <React.Fragment> or <> , an extra header appears above the column header.
Here is the link to plunker
https://plnkr.co/edit/0Tzd2zuFwwXHcXDh

**Expected behavior**
The extra line above the header shouldn't appear.
We might want to change the columns dynamically and to do that it has to be passed in props/variables where the columns need to be wrapped by <React.Fragment> or <>. 

**Please tell us about your environment:**
MacOS, Express

* **AG Grid version:** X.X.X
"ag-grid-community": "^25.0.1

* **Browser:**
Chrome

* **Language:**
Javascript, React

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hi @trellis-dshrestha,

Thanks for submitting this.

We looked into this and need additional information about your scenario.

Are you trying to update column properties dynamically by binding them to React props? This is supported and you can implement it as shown here:
https://plnkr.co/edit/AiyVg41ECBB3DlCg?preview

Are you trying to dynamically set columns in the grid via React state? This is supported and you can implement it as shown here:
https://plnkr.co/edit/nEiIwHUpK1HFbYdh

Please use the approaches above, and if your use case is different, please let me know the specifics.
