### ISSUE TITLE
sizeColumnsToFit() results in all columns having the same width, ignoring former widths

### ISSUE THREAD

**Issue by aHereitani** [ag-grid/ag-grid#4404]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

plunker:
https://plnkr.co/edit/It58ZZwPjvzIjdDZ

**Current behavior**
Calling Auto-Size All and then Size to Fit results in all columns having the *same* width.

**Expected behavior**
Calling Auto-Size All and then Size to Fit results in all columns having *different* widths depending on former widths of the columns.

Also, I can refer to @ceolter that this should be working :)
https://github.com/ag-grid/ag-grid/issues/723#issuecomment-185624338

**Please tell us about your environment:**
Not depending on environment

* **AG Grid version:** 25.1.0
I was able to track down this issue to 23.2.0. You can change to 23.1.0 in the html to see the expected beaviour. 

* **Browser:**
Not depending on browser
"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We raised this with the dev team, note that the behavior of this method is not anymore as described in the ticket that you point out

I am afraid that this working as expected.

I will flag this ticket as managed by the community to see if someone can help you with this.

Hope this makes sense

**Comment by aHereitani** [comment]
Hi,

thank you very much for the response!

I do not think, that this is a good decision for the product ag-grid, as my requirement is very simple and might be very common:
No horizontal scrolling **and** size the columns "as good as possible" to fit the contents. Calling autoSize and then sizeToFit was a proper solution for that till 23.2.0.

Let's see, if anyone has an idea.

**Comment by makinggoodsoftware** [comment]
ag-Grid
Support 2018






Share


gitHub responses
+2
Created by Alberto Gutierrez
Last updated Apr 07, 20219 min read8 people viewed8 people viewed
Closing after a while
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
