### ISSUE TITLE
getRows is not run when use applyColumnState along with infinite row model

### ISSUE THREAD

**Issue by raukouski** [ag-grid/ag-grid#4406]
It looks like there were some changes in scope of **AG-4755** ticket:
`this.addManagedListener(this.eventService, Events.EVENT_COLUMN_EVERYTHING_CHANGED, this.onColumnEverything.bind(this));`
was removed in **infiniteRowModel.ts** file but
`this.addManagedListener(this.eventService, Events.EVENT_NEW_COLUMNS_LOADED, this.onColumnEverything.bind(this));`
was added.
But `ColumnController.prototype.applyColumnState` function still runs `this.dispatchEverythingChanged(source);` under the hood so the `getRows` function is not run when use `applyColumnState` along with the Infinite row model.

**Comment by raukouski** [comment]
You can test it here: https://plnkr.co/edit/cHZfroLkzM8ShgV5
I found out that we use `suppressColumnStateEvents: true` setting and when it's `true` the issue is reproducible.
There is no such issue in ag-grid version 24 so we started to get this issue only when we upgraded the version to 25.
As I mentioned in the description there were some changes for the events:

![image](https://user-images.githubusercontent.com/19466678/113046615-f07a1d00-91a8-11eb-9c68-6ae1ed989080.png)

but `ColumnController.prototype.applyColumnState` is still emits `Events.EVENT_COLUMN_EVERYTHING_CHANGED` event type.

I also noticed someone removed `suppressColumnStateEvents` from the documentation: https://www.ag-grid.com/angular-grid/grid-properties/

Could you please take a look and let me know how `suppressColumnStateEvents` works now and why it worked differently in version 24? Thank you!

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Note that as of v25 that method is not supported, but you can update the state of your column as described here:

https://www.ag-grid.com/javascript-grid/column-updating-definitions/ 

Hope this helps
