### ISSUE TITLE
AgGrid React: floatingFilter disappear after modifying columns

### ISSUE THREAD

**Issue by allanpaiste** [ag-grid/ag-grid#4407]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'
```

**Description**

There seems to be an issue with filters not being re-rendered properly when columns get updated for a React-wrapped AgGrid.

**Steps**

(pre-configured scenario that allows skipping directly to step 6: https://plnkr.co/edit/rWnrmZqRoBCWrXAi)

1. Open the React example for changing columns: https://www.ag-grid.com/react-grid/column-updating-definitions#adding--removing-columns
1. Open the example in a new window that allows you the edit the source code (it'll be opening in plnkr.co)
1. Open Project > index.jsx
1. Edit first column definiton of the **colDefsMedalsIncluded** to be: `{ field: 'athlete', filter: 'agTextColumnFilter'}`
1. Locate the **\<AgGridReact\>** usage, and add a new prop:`floatingFilter={true}`
1. Run the project by clicking on the Run icon on the right-hand panel of the whole plnkr.co view
1. Wait for the React component to render
1. Take a note that the text filter is rendered for Athlete column
1. Click on the "Exclude Medal Columns"
1. Click on the "Include Medal Columns"

**Current behavior**

The filter under Athlete column does not get re-rendered as floatingFilter (rather it falls back to be rendered as non-floating).

**Expected behavior**

The filter under Athlete column does get re-rendered as floatingFilter (the same way it does for the pure Javascript version of this example).

**Additional remarks**

There's a way to get around this bug currently through adding `floatingFilter: true` to the `athlete` column.

Example: https://plnkr.co/edit/98x6V4adHMDq3Suy

**Please tell us about your environment:**

Using Example provided by the authors of the extension.

* **AG Grid version:**

Whatever is used for rendering the example, which at the time of reporting this: 25.1.0

* **Browser:**

Chrome: 89.0.4389.82
Safari: 14.0.3 (16610.4.3.1.4)
Brave: 1.21.77 Chromium 89.0.4389.990

* **Language:**

ES6/7

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by allanpaiste** [comment]
Saw now that in the sources, the component property that this issue refers to has been deprecated and people are instead encouraged to use the flag through colDef - which does work as expected.

```
    /** @deprecated Use floatingFilter on the colDef instead */
    floatingFilter?: boolean;
```

So I guess the issue report is invalid.

One could probably ask for a console.warning to be emitted on someone still using the flag as the issue will still be prevalent when someone fails to upgrade their AgGrid library and their usage while also updating the props configuration correctly.

**Comment by AhmedAGadir** [comment]
Hi,

There is a warning in the console when defining floating filter on the grid options.

`ag-grid-community.cjs.js:17345 AG Grid: since v23.1, floatingFilter on the gridOptions is deprecated. Please use floatingFilter on the colDef instead.
`
The solution is to define floatingFilter on the column definitions as mentioned above:

see https://plnkr.co/edit/1BsJq3jPdjhJDwgA
