### ISSUE TITLE
possible caching issue when refreshing the page after paginating?

### ISSUE THREAD

**Issue by JimmyBlundell** [ag-grid/ag-grid#4409]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Let's say I have a large dataset and only take 10 rows per page. I then paginate over to page 3 of the grid. I am keeping filters applied to the grid using queryParams, for example page #, start and end date if applicable, etc. When I refresh my web page, I am brought back to page 3 as expected. However, if I paginate over to page 1, it shows the same results as page 3. All other pages will have the appropriate data, but page 1 of the grid always displays the same results as the page I refreshed on.

**Expected behavior**
If I refresh while paginated over to page 2, 3, etc., I should be able to go back to page 1 after the refresh and get the appropriate results. 

**Please tell us about your environment:**
Google Chrome, Linux/Ubuntu

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
