### ISSUE TITLE
Exception thrown when using CustomHeader along with SSRM and Drag n Drop enabled

### ISSUE THREAD

**Issue by harryjoy** [ag-grid/ag-grid#4412]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Custom header component example for React: https://www.ag-grid.com/react-grid/component-header/
- If you use same example, but with SSRM and dnd enabled, you will see below error.
![Screenshot 2021-03-22 at 12 01 56 PM](https://user-images.githubusercontent.com/648312/111949275-6a096f80-8b06-11eb-93a4-321720148e63.png)

When debugged found that the mentioned method is executed 2 times, first time it does not have the element its supposed to add listener on to, while the second time (when api data is available) the element is there but since the error that came first time was not handled the page crashes eventually.

If we disable dnd by `suppressMovable` flag, either for all columns or even only for the column with custom header, it works well. Also, using client side model, does not cause the issue.
Downgrading to 24.1.0 work well but there is another bug of pagination which is solved in 25.1.0 so need to use this.

**Current behavior**
Error thrown while using CustomHeader component with SSRM.

**Expected behavior**
It should not throw any error.

**Please tell us about your environment:**
Mac OS 10.15.7

* **AG Grid version:**
AG-GRID Version - 25.1.0

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.0.3

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

This seems to be working on our end. Please see the example below:

https://plnkr.co/edit/5NyEEzWNbaYo8rmx

The example uses React + Custom Header Component + Server Side Row Model + Drag and Drop enabled

Could you please fork the example above and reproduce your issue so that we can continue investigating?

Thanks
