### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'filter' of null for restoring filter after deleting item from grid.

### ISSUE THREAD

**Issue by hrshtpnt** [ag-grid/ag-grid#4413]
setFilterModel is throwing this error, after calliing an API to restore the grid filters. **setColumnState setGroupState setSortModel are working fine.** Only **gridApi.setfilterModel is not working.**

Urgent help needed.

Language - Typescipt and React JS

![image](https://user-images.githubusercontent.com/22808323/111978748-47894d80-8b2a-11eb-8083-071d5f7b61b0.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
