### ISSUE TITLE
custom cellRenderer doesn't work. getting error- Cannot read property 'wrap' of null

### ISSUE THREAD

**Issue by tarushreeS** [ag-grid/ag-grid#4417]
**I'm submitting a 
```
[] support request => see 'Requesting Community Support'
```
I am creating a custom cell renderer class called MedalCellRenderer.ts. This is a angular component. Mapping the same in my app.component.ts as follows:
export class AppComponent implements OnInit{
  gridApi;
  gridColumnApi;
  columnDefs;
  frameworkComponents;
  rowData= [];
  autoGrp;
  getDataPath;
  gridOptions = <GridOptions>{};
  
  constructor(http: HttpClient) {
    this.autoGrp ={
      headerName: 'Company',
      cellRenderer: 'medalCellRenderer'
    };
    this.columnDefs = [
      {
        headerName: 'Office',
        field: 'office',
        cellRenderer: 'agGridStringRenderer'
      }
    ];
    this.frameworkComponents = {
      medalCellRenderer: MedalCellRenderer
    };
    this.rowData=[
      {"company":["XX"], "office":"Pune"},
      {"company":["XX","XX.x"], "office":"PCMC"},
      {"company":["YY"], "office":"PCMC"},
      {"company":["YY","YY.y"], "office":"Pune"},
      {"company":["YY","YY.yy"], "office":"PCMC"}
  ];

  this.getDataPath= data => {
    return data.company;
}
  }
  ngOnInit(): void {
    this.gridOptions={
      columnDefs:this.columnDefs,
    autoGroupColumnDef:this.autoGrp,
    getDataPath:this.getDataPath,
    frameworkComponents:this.frameworkComponents,
    rowData:this.rowData,
    treeData:true
    }
    var eGridDiv: HTMLElement = <HTMLElement>document.querySelector('#myGrid');
    new Grid(eGridDiv, this.gridOptions);
  }

}

I am getting the following error on console:
ERROR TypeError: Cannot read property 'wrap' of null
    at UserComponentFactory.push.Lrxb.UserComponentFactory.createComponentInstance (userComponentFactory.js:359)
    at UserComponentFactory.push.Lrxb.UserComponentFactory.createAndInitUserComponent (userComponentFactory.js:116)
    at UserComponentFactory.push.Lrxb.UserComponentFactory.newCellRenderer (userComponentFactory.js:62)
    at createCellRendererFunc (cellComp.js:722)
    at AnimationFrameService.push.tjar.AnimationFrameService.executeFrame (animationFrameService.js:128)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28497)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at invokeTask (zone-evergreen.js:480

The same code works fine when i create the grid using <ag-grid-angular> tag in html (as shown in original example) instead of using new Grid(eGridDiv, this.gridOptions);

Plunkr- https://plnkr.co/edit/wqc9vjLIfFzPLlyX

**Comment by seanlandsman** [comment]
You cannot instantiate an angular grid with:

`var eGridDiv: HTMLElement = document.querySelector('#myGrid');
new Grid(eGridDiv, this.gridOptions);`

I'd suggest you go through the docs, starting with the angular tutorial here: https://www.ag-grid.com/angular-grid/getting-started/

**Comment by tarushreeS** [comment]
> You cannot instantiate an angular grid with:
> 
> ```
> var eGridDiv: HTMLElement = document.querySelector('#myGrid');
> new Grid(eGridDiv, this.gridOptions);
> ```
> 
> I'd suggest you go through the docs, starting with the angular tutorial here: https://www.ag-grid.com/angular-grid/getting-started/

Thanks for the quick reply.
I am new to ag-grid and angular in general. Can you please guide me on how can the grid be instantiated in .ts file instead of the template file.
