### ISSUE TITLE
Row Virtualization with autoHeight

### ISSUE THREAD

**Issue by marcog83** [ag-grid/ag-grid#4418]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

I read from documentation that Row Virtualization is done by default by AG-grid
https://www.ag-grid.com/javascript-grid/dom-virtualisation/

But I have a enterprise react ag-grid (25.0.1) in our project with these configuration, and when we load our data, 
it seems the Virtualization is not applied. I figure out that virtualization is not applied when `autoHeight` property is set.

we are using autoHeight to avoid double scrollbars
![image](https://user-images.githubusercontent.com/4071265/112329131-37eb3f80-8cb7-11eb-98b0-2c0ab41fb74d.png)
![image](https://user-images.githubusercontent.com/4071265/112329211-4afe0f80-8cb7-11eb-84cb-dca100cc7d14.png)

Is there a way to apply autoHeight and row virtualization?

![image](https://user-images.githubusercontent.com/4071265/112299549-32cac800-8c98-11eb-8c9e-7957c96b368d.png)

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as explained here

https://www.ag-grid.com/angular-grid/grid-size/#grid-auto-height 

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
