### ISSUE TITLE
successCallback should fail or warn if lastRow is a numeric string

### ISSUE THREAD

**Issue by ericmartinezr** [ag-grid/ag-grid#4420]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/tqtlmldqGVCCJjWY

**Current behavior**
According to the [docs](https://www.ag-grid.com/javascript-grid/infinite-scrolling/#setting-last-row-index) `lastRow` should be `undefined`, `null` or `-1`  to make it infinite scrolling or paginating. But if you mistakenly pass a numeric string, like it happened to me (the value came from the backend so typings didn't catch it) you'll still get infinite paginating.

See in the example that I passed "10" to `lastRow` parameter and it's behaving as if it was `undefined`, `null` or `-1` which is not the case. 

**Expected behavior**
It should be failing or warning at runtime if possible. I understand this was my mistake, but the framework could do something about it, maybe?.

**Please tell us about your environment:**
Windows, npm, angular 12

* **AG Grid version:** X.X.X
25.1.0

* **Browser:**
Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular, ES5, TS 4.0.3

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this can take any number, not the three values that you mention, this is explained here:

 **If the last row is known, then this should be the index of the last row**. If the last row is unknown, then leave blank (undefined, null or -1).

https://www.ag-grid.com/javascript-grid/infinite-scrolling/#setting-last-row-index 

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
