### ISSUE TITLE
hideOverlay doesn't work anymore when model is updated or pagination changed

### ISSUE THREAD

**Issue by ericmartinezr** [ag-grid/ag-grid#4421]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/vsnOP2OkB9ksoCC1 (using Ag Grid 24). Navigate using the pagination bar.
https://plnkr.co/edit/dL1KquojIStyHEjS (using Ag Grid 25). Navigate using the pagination bar.

**Current behavior**
I made two plnkrs. The one using Ag Grid 24 is working fine. Navigate as I mentioned and each time you'll see a "Loading..." overlay that'll hide when it loads the next page. But if you do the same using Ag Grid 25 the pagination occurs but the "Loading..." overlay stays there making it impossible to interact with the rows (this can be solved using `setTimeout` but it's just a workaround).

Note: the showLoadingOverlay is called inside the datasource and it's hidden in the paginationChanged method.

**Expected behavior**
If this is a breaking change it should be mentioned somewhere. I looked over here https://www.ag-grid.com/ag-grid-changelog/ but I found nothing and it's super slow to search for anything.

The overlay should dissapear once the pagination occurs.

**Please tell us about your environment:**
Windows, VS Code

* **AG Grid version:** X.X.X
25.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular, TS 4.0.3, ES5

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, we had a look at your code, and in our opinion this would not be a regression as the logic really was very dependant on a racing condition.

We have this example though

https://plnkr.co/edit/CQ5ER6VGnAPK9vIi 


Would this approach be an option?

**Comment by ericmartinezr** [comment]
Hey  @makinggoodsoftware , in the end it's up you guys. I just thought this would be worth to report but if it's not a bug nor anything you're free to close it :+1:

**Comment by makinggoodsoftware** [comment]
Hi!

Thanks for the feedback @ericmartinezr 

Let us know if you have any more issues

Thanks
