### ISSUE TITLE
Looking for API to set selectedRows which is stored. 

### ISSUE THREAD

**Issue by TMinh25** [ag-grid/ag-grid#4424]
**I'm submitting a support request**

**Current behavior**
I'm looking for an API of Grid to set the selected rows. I saw the gridApi.getSelectedRows() of the gridApi, I assume that there is a api to achieve what I wanted. But I didn't find any result.

**Please tell us about your environment:**

* **OS:** window 10,
* **IDE:** Visual Studio Code,
* **package manager:** npm, yarn,
* **Framework:** ReactJS,

* **AG Grid version:** 25.1.0

* **Browser:**

* **Language:** ES6/7

**Comment by ericmartinezr** [comment]
I would guess you can achieve this with a combination of [forEachNode](https://www.ag-grid.com/javascript-grid/grid-api/#reference-rowNodes) and [setSelected](https://www.ag-grid.com/javascript-grid/row-object/#reference-rowNodeMethods).

**Comment by TMinh25** [comment]
Thanks @ericmartinezr, nice guess.

_setSelected(newValue: boolean, clearSelection: boolean)_ 

```
  gridApi.forEachNode((rowNode) => {
    if (_condition_) {
      rowNode.setSelected(true, false);
    } else {
      rowNode.setSelected(false, false);
    }
  });
```
