### ISSUE TITLE
isServerSideGroupOpenByDefault is not working with partial store

### ISSUE THREAD

**Issue by jackmoran1992** [ag-grid/ag-grid#4428]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

The callback is not triggered unless the store type is "full" however the [docs don't specify](https://www.ag-grid.com/javascript-grid/server-side-model-grouping/#open-by-default) it should only work with full store.

Your example plunkr from docs has been modified to have store type set as [partial here](https://plnkr.co/edit/I5fTI4vDERHcW3mX).

**Expected behavior**

The callback should trigger with "partial" stores too.

**Please tell us about your environment:**

* **AG Grid version:** 25.1.0

* **Browser:** Chrome

* **Language:** all

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
