### ISSUE TITLE
Filter not working on server side data

### ISSUE THREAD

**Issue by abdelrhman1410** [ag-grid/ag-grid#4431]
Hi,
I have an angular project integrated with ag-grid, I'm using the server-side data model which provides the grid with data grouped as in the screenshot attached.

I want to use filter property to filter the data in the grid according to every applied column filter as in the client-side data model

I gave every column definition the type of filter I want, and I gave them the property > filter = true.

As in the screenshot nothing in the filter box and I can't apply any filtration on any column.

please let me know what to do to achieve such functionality?

I use:
Angular : 8
ag-grid: 23

screenshot: https://drive.google.com/file/d/1RAJrUg9NwoHu7YonDLQ-XwqXOOeoj4bk/view?usp=sharing

**Comment by abdelrhman1410** [comment]
@makinggoodsoftware  could you please help?

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
