### ISSUE TITLE
Resource Query Language

### ISSUE THREAD

**Issue by lapd-viosoft** [ag-grid/ag-grid#4433]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
Hi,
We have all our database that can be query using [Resource Query Language](https://github.com/persvr/rql). We are trying to use ag-grid on frontend and we found there is a filter api at https://www.ag-grid.com/javascript-grid/filter-api/

The filter model looks like:
```js
{
    athlete: {
        filterType: 'text',
        type: 'startsWith',
        filter: 'mich'
    },
    age: {
        filterType: 'number',
        type: 'lessThan',
        filter: 30
    }
}
```
Do you know, Is there any work/possible to convert this filter to RQL query ?
Thank

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
