### ISSUE TITLE
groupSelectsChildren property doesn't work with server side checkbox selection

### ISSUE THREAD

**Issue by abdelrhman1410** [ag-grid/ag-grid#4434]
Hi, 

I'm using ag-grid with angular, I use server-side data model for a specific page and client-model for another.
I'm trying to use checkbox row selection with row-groups, in the client model I can use the property "groupSelectsChildren" and the row group checkbox will select his children when checked when collapsed, expanded, etc

I'm trying to implement the same functionality in the server-side page but I can't, can you provide me with some information? 

I use:

Angular 8
ag-grid 23

Thanks,

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
