### ISSUE TITLE
Corrupted xlsx file when exporting aggrid content with an STX ASCII caracter

### ISSUE THREAD

**Issue by ES-Six** [ag-grid/ag-grid#4437]
**I'm submitting a bug report**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior** : When i insert a special caracter of type STX (standard caracter of value 02 in decimal in the ascii table) between two words in a cell value (no matter if I insert the caracter using javascript or copy paste it in an editable cell), and when I export the aggrid content with the .xlsx export type, I get a corrupted Excel file, here are pictures illustrating the process using the aggrid demo page :

![image](https://user-images.githubusercontent.com/13310075/113742584-0a64b400-9703-11eb-8d27-847d363c5604.png)
![image](https://user-images.githubusercontent.com/13310075/113742660-210b0b00-9703-11eb-9ab3-72d386a5f078.png)

**Here is the corrupted doc** : 
[export.xlsx](https://github.com/ag-grid/ag-grid/files/6266061/export.xlsx)

**Reproducible scenario of how to reproduce the bug :**
1) Copy paste this caracter in an aggrid editable cell or insert the caracter using javascript (eg : in the aggrid demo), here is a capture of this caracter in the ascii table :
![image](https://user-images.githubusercontent.com/13310075/113743863-6bd95280-9704-11eb-86b9-19d00426ed33.png)
![image](https://user-images.githubusercontent.com/13310075/113742584-0a64b400-9703-11eb-8d27-847d363c5604.png)

2) Export to excel using the native export to excel function in aggrid (with the native default context menu, or with the demo aggrid context menu) :
![image](https://user-images.githubusercontent.com/13310075/113742660-210b0b00-9703-11eb-9ab3-72d386a5f078.png)

3) Open the xlsx file with Microsoft Excel :
![image](https://user-images.githubusercontent.com/13310075/113745554-a98aab00-9705-11eb-88a2-074e33f62d72.png)

**Expected behavior** : the excel file generated by the aggrid xlsx export type should not be corrupted because of this caracter in a column value (an STX caracter, value 02 in decimal in the ascii table). Other exports types (xml and csv) works just fine without corruption.

* **Environment :** I tested Aggrid with the Angular 11 Framework, Webstorm, Google Chrome, Windows 10, latest npm, latest version of Microsoft Excel, everything is nominal. I also reproduced the bug using the demo page on the aggrid's website here : https://www.ag-grid.com/example.php

* **AG Grid version:** 25.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"

* **Language:** TypeScript 4.1.5

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by aszenz** [comment]
@makinggoodsoftware Just faced this issue on latest ag-grid, this is not a support request but a bug in the software.

**Comment by AG-Zoheil** [comment]
Hi @aszenz,

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue from almost three years ago.

The grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
