### ISSUE TITLE
Not able to disable/enable top axes label for polar charts, version 25.0.0

### ISSUE THREAD

**Issue by ulugbekbuyuk** [ag-grid/ag-grid#4439]
![Chart-01](https://user-images.githubusercontent.com/73280131/114127725-3a36d600-9914-11eb-9c24-84f914852db3.JPG)

For polar charts, I am able to disable/enable "title", "subtitle", "labels" and more from chart toolbar or programmatically. But As it is shown above picture example that I couldn't do it for "Spread %" top-label.
As per my investigation from official ag-grid docs, it looks axes title or axes label, but I tried several approach to hide this label, I mean programmatically. From this link, https://www.ag-grid.com/angular-charts/axes/, it says "Axes are only supported in cartesian charts, not polar. For example, you can't use axes with pie series.". Does it mean I am not able to manage axis for polar charts, even for the top-label that I have mentioned.
Could you please provide some info if I can disable that top-label or create take it as new issue if it is considered new feature for upcoming versions.

Thank you.

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
