### ISSUE TITLE
exportDataAsExcel: Failed to construct 'MouseEvent': member view is not of type Window. 

### ISSUE THREAD

**Issue by spaceBin** [ag-grid/ag-grid#4444]
I get an error when I use the api exportDataAsExcel. 
This error is: Failed to construct 'MouseEvent': member view is not of type Window. 
Error location: at Downloader.download.

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by spaceBin** [comment]
Thanks you!

**Comment by spaceBin** [comment]
> HI,
> 
> This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.
> 
> You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/
> 
> If that is not the case, or you are having trouble, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) where they will be able to assist you with your access.
> 
> Thanks

Thank you！
