### ISSUE TITLE
AgGridReact 20.1.0 imports ag-grid-community instead of enterprise

### ISSUE THREAD

**Issue by Mishurin** [ag-grid/ag-grid#4445]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

Hey, guys. 
I will try to describe my problem however I cannot give a full example of it because it is hard to repeat reproducible example of my infrastruture due to its complexity. First of all I am using ag-grid 20.1.0 and currently I don't have an option to upgrade it to the latest version. We are using requirejs, and typescript is compiling using `"module": "amd"`. I hope that somebody faced similar kind of problem and can help with an advice.

I create react component using imports as follows (https://www.ag-grid.com/archive/20.1.0/javascript-grid-grouping/#example-auto-column-group);
`
import React = require('react');
import { AgGridReact } from 'ag-grid-react';
import { LicenseManager } from 'ag-grid-enterprise';
import 'ag-grid-enterprise';

`

In run-time I am getting
![image](https://user-images.githubusercontent.com/5419132/114847802-c6e70580-9de6-11eb-89d1-612902489519.png)

I started looking at code base (https://github.com/ag-grid/ag-grid/blob/b20.1.0/packages/ag-grid-react/src/agGridReact.ts) and noticed that AgGridReact internally imports "ag-grid-community" and use it for instantiating:
`
import * as AgGrid from "ag-grid-community";

....
componentDidMount() {
        new AgGrid.Grid(this.eGridDiv, this.gridOptions, gridParams);
}
...
`

We are using the following bundles from node_modules:
"ag-grid": "<#=node_modules#>/ag-grid-community/dist/ag-grid-community.noStyle",
"ag-grid-react": "<#=node_modules#>/ag-grid-react/umd/ag-grid-react.min",
"ag-grid-enterprise": "<#=node_modules#>/ag-grid-enterprise/dist/ag-grid-enterprise.noStyle"

Judging by the code there is no way for AgGridReact to use ag-grid-enterprise. And it doesn't matter that import of AgGridReact is followed by `import 'ag-grid-enterprise'. At least in my understanding.

**Questions**:
 - By declaring `import 'ag-grid-enterprise';`,  is it expected that AgGridReact will use enterprise version instead of community one?
 - Can 'ag-grid-community' and 'ag-grid-enterprise' colflict with each other if some component use 'ag-grid-community' and my component uses 'ag-grid-enterprise'? Can they be used simultaneosly in the same bundle?
 - Is there any way to pass ag-grid-enterprise class to AgGridReact to allow it to instantiate a component using ag-grid-enterprise class?

**Environment**

Package manager: NPM, Bundler: Grunt+Gulp. Modules: requirejs

* **AG Grid version:** 20.1.0

* **Browser:** All (Chrome Latest)

* **Language:** [TypeScript 3.8.3]

Thank you in advance for any help!

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
