### ISSUE TITLE
Pasting a range of cells from Excel on Windows incorrectly inserts an additional cell

### ISSUE THREAD

**Issue by jaekwak02** [ag-grid/ag-grid#4446]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Our organization is a customer of ag-grid but I am having trouble gaining access to a support account.

**Current behavior**
- Enable editing in multiple columns as well as `enableRangeSelection` on the grid.
- Copy and paste a group of cells from EXCEL on WINDOWS (specifically excel and windows, cannot verify browser has a role in this) into ag-grid. Does not matter if you select one cell when you paste or select a range.
- A single additional blank cell is copied beneath the bottom left cell of the pasted group.
- Try on https://www.ag-grid.com/example.php

**Expected behavior**
That additional blank cell should not be pasted into the grid.

**Please tell us about your environment:** 

* **OS:** Windows 10 Business version 1909 (OS build 18363.1440)

* **AG Grid version:** 25.1.0

* **Browser:** Chrome Version 89.0.4389.90 (Official Build) (64-bit), unable to get browser.userAgent at the moment

* **Language:** ES6 React

**Comment by gportela85** [comment]
@jaekwak02 Check the `suppressLastEmptyLineOnPaste` property here: https://www.ag-grid.com/javascript-grid/grid-properties/

**Comment by jaekwak02** [comment]
Cool! Thank you! Why does this default to false? Are there any other implications to setting this to true?
