### ISSUE TITLE
NotFoundError exception with integrated charts

### ISSUE THREAD

**Issue by Pablo-Chacra-42** [ag-grid/ag-grid#4451]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I am testing to integrate AG Grid into a Vaadin Flow application, everything is working ok, but I have a problem with charts.

When I try to generate a chart, I receive the following exception:
_NotFoundError: Failed to execute 'insertBefore' on 'Node': 
The node before which the new node is to be inserted is not a child of this node._

The problem is in line:
`document.head.insertBefore(styleElement, document.head.querySelector('style'));`

I don't understand why it fails, document.head has several 'style' elements.
If I query with another name like 'script' or 'custom-style' it works, but not with 'style'.
Does anybody know why?
JavaScript is not my area of expertise!

**Please tell us about your environment:**
OSX, IntelliJ, Jetty

* **AG Grid version:** 25.1.0

* **Browser:**
Checked with Chrome and Safari

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
