### ISSUE TITLE
Sort property is omitted from the column state in Ag grid

### ISSUE THREAD

**Issue by akhilnbr** [ag-grid/ag-grid#4453]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
I was trying to get the column state whenever onSortChanged handler is called. 
I am using an ag-grid-enterprise-21.2.1 edition where I am seeing something missing when I debugged. I am not sure I did it wrong if yes please correct me.
I have debugged my version and a community version. I will list out what I found here
Debugging enterprise edition:
![image](https://user-images.githubusercontent.com/26479291/115355858-b5cc3900-a1d8-11eb-8c1c-fa7679201dce.png)
Debugging community edition
![image](https://user-images.githubusercontent.com/26479291/115356058-e90ec800-a1d8-11eb-80e3-bde347da524d.png)

If you see both there are some notable differences between community and my enterprise edition. Some of the properties of column state have been omitted from my version of Ag-grid. Not sure what would be the reason behind it. Please let me what can do to resolve this.
**Current behavior**

I am not seeing the sort,sortIndex when I do columnApi.getColumnState().
**Expected behavior**

I should see the properties which are mentioned here:  [https://www.ag-grid.com/javascript-grid/column-state/](url)

**Please tell us about your environment:** Windows 10,Vs code
* **AG Grid version:** ag-grid-enterprise-21.2.1

* **Browser:**
Google Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
