### ISSUE TITLE
 columnApi.getAllDisplayedColumnGroups() does not return ColumnGroup[] type for TypeScript

### ISSUE THREAD

**Issue by vny-cg** [ag-grid/ag-grid#4454]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Currently getAllDisplayedColumnGroups returns ColumnGroupChild[] type. This makes further actions with methods such as columnApi.getDisplayNameForColumnGroup() incompatible as this method expects type ColumnGroup

**Expected behavior**
getAllDisplayedColumnGroups() should return ColumnGroup[] type or columnGroup functions should expect ColumnGroupChild type

**Please tell us about your environment:**
Mac OS Catalina 10.15.7
VSCode
NPM: 
    "ag-grid-community": "^25.1.0",
    "ag-grid-vue": "^25.1.0",

* **Language:** TypeScript 3.92

**Comment by makinggoodsoftware** [comment]
Hi,

We have flagged this as a good_suggestion

This means that this is a candidate to be in a future release.

At this moment we don’t have a ticket number for this that you can use to track in our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

But we should be updating this ticket with this information as soon as we process the good suggestions, as we do these in batches. Note also that at this stage we can’t guarantee that we will deliver this, but we will take it into consideration

Thanks for your feedback!

**Comment by ceolter** [comment]
The return type (ColumnGroupChild) is correct. Both Column and ColumnGroup implement this interface. What this method returns is the very first row of the header. So if you are grouping the columns, it will return the first level of Column Groups. If you are not using column grouping, it will return back the Columns (which will be the first row if no column groups).
