### ISSUE TITLE
Ctrl + v is pasting empty value / ctrl +c copying empty value

### ISSUE THREAD

**Issue by akhilnbr** [ag-grid/ag-grid#4456]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Attaching the plunker from the docs
[Click here to open the link](https://plnkr.co/edit/QTHg2Fc2JGF0PtMS)

**Current behavior**
Ctrl + v is making the cell empty. If I copy a value from the cell and paste it,then the cell is getting blank

**Expected behavior**
The user should be able to copy and paste values seamlessly

**Please tell us about your environment:**
Windows 10

* **AG Grid version:** 25.1.0

* **Browser:**
Using chrome

* **Language:** JS

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
