### ISSUE TITLE
Click event handler not triggering in react v17

### ISSUE THREAD

**Issue by sag-tobias-frey** [ag-grid/ag-grid#4457]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Click event handlers are not triggered anymore in the newest react version. I have tracked the following two errors in the react project. The first one containing an example including ag-grid-community. The second one is only using react and portals. In my opinion, this is a react issue; however the react team seems not keen on fixing this issue.

-> https://github.com/facebook/react/issues/20848
-> https://github.com/facebook/react/issues/20901

**Expected behavior**
Click event handlers should be triggered correctly.

**Please tell us about your environment:**
Windows

* **AG Grid version:** X.X.X
ag-grid-community: 25.0.1
ag-grid-react: 25.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36 Edg/90.0.818.42

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all (react)

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 

Thanks for raising this with us. 

I had a look at your code in the following StackBlitz: 
https://stackblitz.com/edit/ag-grid-react-hello-world-8vrumq?devtoolsheight=33&file=index.js 

I noted that the way you were using `onCellClicked` was not how we'd recommend using it in our documentation: 
https://www.ag-grid.com/react-grid/grid-events/ 

I fixed this and tested your case in one StackBlitz with the version of React from your original example (17.0.1) and one from a previous version (16.11.0):

V17: https://stackblitz.com/edit/t2t-4505-17?file=package.json 
V16: https://stackblitz.com/edit/t2t-4505-16?file=package.json 

Between the two, I am unable to see any difference in functionality. Thus I cannot confirm that this is an issue at present. 

Thanks,

**Comment by sag-tobias-frey** [comment]
@icedjello You have missed one important point. The problem is the event.stopPropagation() on the outter div. If I add that to your example, it is no longer working in v17.

V17: https://stackblitz.com/edit/t2t-4505-17-5pwi4n?file=index.js [ no longer working with event.stopPropagation() ]
V16: https://stackblitz.com/edit/t2t-4505-16-syuu8a?file=index.js [ still working with event.stopPropagation() ]
