### ISSUE TITLE
Ag-grid with pinned columns you cannot click and drag the vertical scroll bar while using Safari

### ISSUE THREAD

**Issue by pdjenera-varicent** [ag-grid/ag-grid#4458]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
When trying to grab the scroll bar on Safari 14.0.2 and using AgGrid 25.1.0 enterprise with pinned columns, you cannot scroll down the grid

https://user-images.githubusercontent.com/66630094/116151767-0947f680-a6b3-11eb-9cb4-042ef08b577e.mov

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

This defect is reproducible on the ag-grid website here ->https://www.ag-grid.com/react-grid/column-pinning/

Try to click and drag the vertical scroll bar of the first grid while using Safari 14.0.2 you'll notice that you cannot drag the scroll bar down. 

This is not reproducible on Firefox or Chrome

**Expected behavior**

When you click and drag a vertical scroll bar on a grid using pinned columns it should grad as intended. Like in chrome.

https://user-images.githubusercontent.com/66630094/116152171-91c69700-a6b3-11eb-9f2d-368091152a70.mov

**Please tell us about your environment:**
Mac OS 11.1

* **AG Grid version:** 25.1.0

* **Browser:**
Safari 14.0.2

* **Language:** 
Typescript 4.2.3

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 
Thank you for raising this. I ran a test with the example you provided and the latest version of Safari: 

https://user-images.githubusercontent.com/11807157/116544850-8eb3ec80-a8e7-11eb-8051-689fc0c7f7a4.mp4

As you can see, it seems to be working as expected on our end. 

Could you please ensure that you are using the latest version of Safari and try again? 

Thanks,
