### ISSUE TITLE
SSRM datasource getRows(): any way to hook into the event of getRows() executing failCallback()?

### ISSUE THREAD

**Issue by acgrama** [ag-grid/ag-grid#4459]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
I want to define custom functionality to be executed when the SSRM datasource has executed the failCallback(). At the moment, nothing happens when the datasource executes failCallback() instead of successCallback() - the spinner keeps running. I can't find any grid callback that could be used for this purpose.

Are there any updates regarding issue **AG-3005** | [SSRM] Allow failCallback to provide with a strategy to retry/stop loading data ?

Or: are there any acceptable, recommended work-around mechanisms to be used until this issue has been fixed?

**ag-grid**: 23.2.1
**Angular**: 10.1.4

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
