### ISSUE TITLE
Wrong types in AgGridReact if loaded using modules 

### ISSUE THREAD

**Issue by alippai** [ag-grid/ag-grid#4460]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Based on the Typescript docs the `.api` member should be on `.props` however in real life it's on the component. I observed this behavior only when using modules, not packages.

Example: https://stackblitz.com/edit/react-ts-wgu62h 

**Expected behavior**
Working types

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email.

Could you please tell us more about your use case?

If you are trying to access the grid API, we would recommend you use _params.api_ in the onGridReady callback, or that you save the API on your react component as shown in our getting started guide.

See https://www.ag-grid.com/react-grid/getting-started/

> Based on the Typescript docs the .api member should be on .props

Could you also clarify which page on the documentation you are refering to?

Kind regards,

**Comment by alippai** [comment]
@AhmedAGadir I'm passing the AgGrid reference between react components. I filed the example in the initial request and flagged where the typing is wrong. Functionality is OK, but typescript and autocomplete is wrong - I have to cast to "any" to work around the issue.

I'm referring to these lines:
```
const onButtonClick = e => {
+      const selectedNodes = gridRef.current.api.getSelectedNodes()
+
```
If you use this example in typescript and import it via module (not package like in the Getting started) it doesn't compile.

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that we don't support this approach to sharing the api across your components, one alternative is to grap the API from the params as @AhmedAGadir mentioned

Or you can store the api on the onGridReady as we do on our docs

Note that we are going to be closing this issue as we don't think this is an ag-grid issue

**Comment by alippai** [comment]
@makinggoodsoftware @AhmedAGadir I added the stackblitz, showing the very same thing you are doing in the docs.
The only difference is that it's using the module loader and TypeScript.

The example you have in docs _*works*_, the example in my stackblitz _*works*_, only the Typescript compiler throws error (and the autocomplete fails in VSCode). The d.ts file you generate for the react _*module*_ is wrong.

There must be a misunderstanding as this is definitely an ag-grid bug. Let me know if you need a different example, screenshots. If anyone from the QA team starts the example in the docs with typescript and loaded as module, I'm 100% they will see the error.

**Comment by alippai** [comment]
@makinggoodsoftware @AhmedAGadir this is still an issue. The type `AgGridReact` is a React `Component` according to the TS definitions, however in reality the `.api` is on the `AgGridReact` type not on the `AgGridReact.props` like the .d.ts files suggest it.

**Comment by alippai** [comment]
https://stackoverflow.com/a/61990755/785232 here I found the solution I have to use `AgGridReactType`, can't use the component:

```js
import { AgGridReact } from 'ag-grid-react'
import { AgGridReact as AgGridReactType } from 'ag-grid-react/lib/agGridReact'
```
