### ISSUE TITLE
Presence of empty 1st row when data loads in Server Side Row Model

### ISSUE THREAD

**Issue by kdutta25** [ag-grid/ag-grid#4461]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Framework - React JS
Link: https://www.ag-grid.com/examples/infinite-scrolling/block-equal-page/packages/reactFunctional/index.html

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

- When the data loads, there is a presence of an empty 1st row until the data finishes loading.
- It is observed through the borders of the 1st row.
- Issue is present in all `React Grid: Infinite Row Model` examples in the official AG Grid documentation.

**Expected behavior**

- There should not be presence of an empty 1st row while the data is loading in the grid.

**Please tell us about your environment:**

macOS Catalina/Version 10.15.6 (19G73), Visual Studio - Version: 1.45.1, NPM Version - 6.14.4, NODE Version - 12.16.3
* **AG Grid version:** X.X.X

Yes, in V25.1.0
* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.3
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as it was designed to look like there is a single row loading at the top

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by kiril-matev** [comment]
Hi @kdutta25,

Thanks for reaching out about this.

When the grid is loading data, the grid displays a loading row by default. This allows you to provide your user a message indicating that data is being loaded, and you can provide your own component for the purpose as shown here:
https://www.ag-grid.com/javascript-data-grid/component-loading-cell-renderer/

This is why this isn't a bug, it's expected behavior.

If you want to hide this loading row, you can do so like this:
https://plnkr.co/edit/1Jtm4W7ScZV4iYSq?open=main.js

I hope this helps.

**Comment by StNekroman** [comment]
Stupid solution.
If I want loading indicator - I will just use https://www.ag-grid.com/javascript-data-grid/component-loading-cell-renderer/
Empty row is a bug, not feature.
Admit it.

P.S. I use custom Angular components as cell renderers. Why each component should check if data is present and provide some "empty renderer"?
Definitely bug

**Comment by pesiWeisblum** [comment]
It solved the problem:
in grid options:
 getRowStyle: params => {
        if (params.data === undefined) {
          return {opacity: 0};
        }
        return {};
      },

**Comment by nikriaz** [comment]
This class shows hides row content behind and loader icon at the center of the row.

```
.ag-empty-row {
    position: relative;
}

    .ag-empty-row:before {
        content: '';
        position: absolute;
        width: 100%;
        height: 100%;
        display: block;
        background-color: white; /* White with transparency */
        z-index: 1;
    }

    .ag-empty-row:after {
        content: '';
        position: absolute;
        width: 100%;
        height: 100%;
        display: block;
        background: url('../images/loader.gif');
        background-repeat: no-repeat;
        background-position: center;
        z-index: 2;
    } 
```

Usage:
```
            getRowClass: params => {
                if (params.data === undefined) {
                    return 'ag-empty-row';
                }
            },
```
