### ISSUE TITLE
[DOC] Add to doc suppressFinishActions parameter of RowNode.setSelected

### ISSUE THREAD

**Issue by ThomasKientz** [ag-grid/ag-grid#4462]
If one listen to the `onSelectionChanged` event to trigger action when user manually select rows, it is very difficult to "disable" this event when programaticaly selecting rows.

The parameter `suppressFinishActions` is very useful in this kind of scenario.

> `RowNode.prototype.setSelected = function (newValue, clearSelection, suppressFinishActions)`

Usage : 

```js
gridApi.forEachNode(node => {
  node.setSelected(true, false, true) // will not trigger onSelectionChanged event
})
```

With the number of issues and stackoverflow discussions, I think it can benefit a lot of user to add it to the doc.

**Comment by makinggoodsoftware** [comment]
Hi,

We have flagged this as a good_suggestion

This means that this is a candidate to be in a future release.

At this moment we don’t have a ticket number for this that you can use to track in our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

But we should be updating this ticket with this information as soon as we process the good suggestions, as we do these in batches. Note also that at this stage we can’t guarantee that we will deliver this, but we will take it into consideration

Thanks for your feedback!

**Comment by ceolter** [comment]
Thanks for offering this suggestion.

We don't want clients passing 'true' for the third parameter. This is a mistake in our interface to be exposing such.

When the third parameter is false, then the following is missing:
1) Event not fired.
2) Row Groups are not updated (eg if you unselect a row, then it's parent won't get updated)
3) Last selected row is not recorded (eg for Shift+Select, it won't select the right range)
4) Currently selected nodes not unselected (assuming second param is true, or only single-select is configured)

There are some parts of our code internally which passes true for the third parameter (two places to be precise) but they both consider all of these scenarios.

If we documented, and clients started passing true in the third param, then all the above 4 points would start causing issues for people.

Sorry for this, it's one of the very first parts of the API that got written, and as such I wasn't as experienced with APIs at the time, so it's badly written :(

**Comment by ThomasKientz** [comment]
@ceolter The whole point of my suggestion is to have a way to disable events. Can you suggest me an alternative for my scenario (selecting very large number of rows). Thanks
