### ISSUE TITLE
InfiniteRowmodel updateRowData deprecated- Alternative?

### ISSUE THREAD

**Issue by raunokaasik** [ag-grid/ag-grid#4463]
Hi,

Im using the infiniteRowModel and for inserting a row is use:

```
   onBtnAdd()
        {
            this.gridApi= this.$refs.table;           
            const newData = {deviceId:this.deviceId,newOrModified:"new"};
            this.gridApi.gridApi!.updateRowData({add:[newData],addIndex:0});
            this.gridApi.gridApi.setFocusedCell(0, "column1");
            this.gridApi.gridApi.startEditingCell({rowIndex: 0});
        };
```

`AG Grid: updateRowData() only works with ClientSideRowModel. Working with InfiniteRowModel was deprecated in v23.1 and removed in v24.1`

I know that the **updateRowData** was deprecated, but what's the alternative for this now in the latest verison of aggrid and infiniterowmodel ? 

BR,
Rauno

**Comment by patriceo** [comment]
Hi I'm facing same issue, I have checked the online documentation which says that with infinite model we can perform "Add only" operations through the Transaction API

https://www.ag-grid.com/angular-grid/row-models/

And I updated my code (which insert a row at index 0 just like yours) to

```
 api.applyTransaction({
            add: [myNewRowData],
            addIndex: 0
        });
```
and I get the same issue

```
AG Grid: updateRowData() only works with ClientSideRowModel. Working with InfiniteRowModel was deprecated in v23.1 and removed in v24.1
  | push.f7ga.GridApi.applyTransaction | @ | ag-grid-community.cjs.js:31200
-- | -- | -- | --
```

For now I guess I have to go back to version 23 :(

**Comment by makinggoodsoftware** [comment]
Hi guys,

This should be relevant:

https://www.ag-grid.com/angular-grid/infinite-scrolling/#example-using-cache-api-methods

See that in there it shows how to do CRUD operations in the grid.

Hope this helps

**Comment by patriceo** [comment]
Thanks for the link. I will try to use that, however the example code looks a bit ugly ?

Instead of having a clean API you need to manipulate cache then to modify the datasource data. :(

**Comment by raunokaasik** [comment]
> Thanks for the link. I will try to use that. However the example code of inserting a row with the infinite model looks a bit ugly ?
> 
> Instead of having a clean API you need to manipulate a cache API then "hack" the datasource data :(

its not neat indeed  :( .

**Comment by makinggoodsoftware** [comment]
Hi guys

I appreciate that this might be not as neat as it could be, but at the moment is the current approach, note that we might revisit this in the future, but at the moment we don't have anything in the pipeline

Closing this down for the time being, feel free to open a new issue otherwise!

**Comment by demc** [comment]
I similarly need to be able to update specific rows in infinite scroll mode. In my particular case, we have live data streaming from the server that needs to update some rows. Without `applyTransaction` available, how am I able to revise the block cache?
