### ISSUE TITLE
Focus is not being set for custom filter dialogs preventing disabled users from accessing the filter.

### ISSUE THREAD

**Issue by patrickclancy** [ag-grid/ag-grid#4464]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

We're found an accessibility problem. When navigating the grid using only the keyboard. 
  

**Current behavior**
Currently if you navigate using the TAB key to a column's header that has a custom filter. Then press and hold the (CONTROL or COMMAND) key and press the RETURN key. That will open the custom filter dialog. But the focus is not being set to the custom filter. It remains on the header. Making the custom filter inaccessible to keyboard only users and screen readers. Also without transferring focus the filter can't be closed with the ESC key.

Here is an example from the ag-grid docs page on custom filters. 
https://embed.plnkr.co/plunk/jhQwePXVXektrDD4

After this example loads if you TAB to focus on the Athlete column header. Then press and hold the CONTROL key plus the RETURN key. That will open the custom filter dialog. But focus will remain on the Athlete column header. Making the custom filter inaccessible to keyboard only users and screen readers.

**Expected behavior**
The expected behavior would be that when the filter dialog opened the focus would be set on the filter. So that the user could modify the filter inputs then close the filter with the escape key. 

**Please tell us about your environment:**
Apple MacBook Pro.
macOS Big Sur 11.2.3

* **AG Grid version:** X.X.X
ag-grid-community 25.1.0
ag-grid-react 25.1.0

* **Browser:**
Chrome Version 90.0.4430.85 (Official Build) (x86_64)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36

Firefox  88.0 (64-bit)
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0"

* **Language:** 
 [All]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by frastlin** [comment]
I can confirm this behavior. Athlete and  Year do not change focus when ctrl+enter is pressed on Windows 10 with Chrome Version 90.0.4430.93 (Official Build) (64-bit).

**Comment by icedjello** [comment]
Hi, 

Thanks for raising this. I compared the functionality of this filter with that of one of our _default_ filters and noticed that with the AG Grid defaults, focus is acquired when the filter is opened. This functionality allows users to use the filters without the use of a mouse. 
You can see an example of this in the following plunker from our documentation: https://www.ag-grid.com/javascript-grid/filtering/#example-provided-simple 
When creating custom filtering components like the one you shared, you have total control over how the component works. That means that the aforementioned functionality must be built. For example, you could use the `afterGuiAttached()` method to give focus to the input field when the filter is attached. Thus users can then type straight into the filter and press 'esc' to exit it. 
I've altered your example to show how this could work: 
https://plnkr.co/edit/thOjZql74bDWssW6

**Comment by frastlin** [comment]
This focus functionality should be default, or at least mentioned at the top of the documentation, otherwise everyone who is not a keyboard user will leave this out. The only reason why I noticed was because I couldn't focus my filter being a keyboard user. Defaults are critical for making a tool like AG Grid accessible to everyone.
