### ISSUE TITLE
[DOC] Missing section for onGridReady in React, Getting Started

### ISSUE THREAD

**Issue by Leeoku** [ag-grid/ag-grid#4466]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

There is a documentation error here [https://www.ag-grid.com/react-grid/getting-started/](url)

**Expected behavior**

Under the `Enable Selection`, the steps don't add these code pieces which are present in the full code at the top

```js
const onGridReady = params => {
        setGridApi(params.api);
        setGridColumnApi(params.columnApi);
    }
```
Also in the AgGridReact component `onGridReady={onGridReady}`

**Please tell us about your environment:** W10

* **AG Grid version:** 25.1

* **Browser:** Any browser

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We have raised this but we don't think is necessary as this no longer applies - there is only one reference to gridReady on that page now and it's a note

Thanks for your feedback though!
