### ISSUE TITLE
Custom cell renderer | cell rendering before data can be passed to it, not re-rendering

### ISSUE THREAD

**Issue by rrundle** [ag-grid/ag-grid#4467]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Custom cellRenderer component is rendering before row data is rendered in column cells so data passed to a cellRenderer component is `undefined`. However, in version 24 the cellRenderer component would re-render with the data passed to it as a prop. 

**Expected behavior**

Data passed to a cellRenderer component would have defined row data. Or (less ideally) if it was initially `undefined` would re-render with the data. It seems in many cases the cell is rendering before the row data has been rendered into the cells. 

**Please tell us about your environment:**

macOS Catalina 10.15.7
installed via npm
Browser: Any browser
Language: [all | TypeScript X.X | ES6/7 | ES5]
React

* **AG Grid version:** 

25.2.0

ag-grid-community: 25.2.0
ag-grid-react: 25.2.0

This is an issue in 25+. Did not exist in 24.

**Comment by seanlandsman** [comment]
Are you able to provide a repo of this issue that we can take a look at?

**Comment by rrundle** [comment]
yes i will, sorry been a busy week.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
