### ISSUE TITLE
Fill handle fails to fill small numbers (<= 1e-7) across more than one columns/rows

### ISSUE THREAD

**Issue by vivvea** [ag-grid/ag-grid#4470]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When you use the fill handle to fill a small number <= 1e-7 across more than one columns / rows it fails to fill the value after the first col. You will get an console error

`Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.l [as findLineByLeastSquares] (ag-grid-enterprise.min.js:8)
    at t.processValues (ag-grid-enterprise.min.js:8)
    at m (ag-grid-enterprise.min.js:8)
    at ag-grid-enterprise.min.js:8
    at Array.forEach (<a
![ag](https://user-images.githubusercontent.com/54615503/117136723-734a5500-adb1-11eb-8a49-84e8af7ada99.png)
nonymous>)
    at f (ag-grid-enterprise.min.js:8)
    at f (ag-grid-enterprise.min.js:8)
    at t.handleValueChanged (ag-grid-enterprise.min.js:8)
    at t.onDragEnd (ag-grid-enterprise.min.js:8)
    at Object.onDragStop (ag-grid-enterprise.min.js:8)`

It seems that the findByleastSquares fails to get maxDecimals due to number.toString() does not contain a decimal dot in case of a small number.

`maxDecimals = Math.max(maxDecimals, **value.toString().split('.')**[1].length);`

**Expected behavior**
Fill handle should be able to fill the value also after the first filled col/row

**Please tell us about your environment:**
Windows 10 

* **AG Grid version:**
Latest

* **Browser:**
Atleast chrome and firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
