### ISSUE TITLE
Sidebar not clickable

### ISSUE THREAD

**Issue by VictorAlagwu** [ag-grid/ag-grid#4476]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behaviour**
Currently clicking the columns or filters tab does nothing, no modal is being displayed, and there is no error in the console for that click event
<img width="635" alt="Screenshot 2021-05-11 at 9 39 01 AM" src="https://user-images.githubusercontent.com/15857679/117785985-fc8fda80-b23c-11eb-9b2c-ff14876711f8.png">
<img width="462" alt="Screenshot 2021-05-11 at 9 43 11 AM" src="https://user-images.githubusercontent.com/15857679/117786398-5d1f1780-b23d-11eb-8b17-19fc6e1e1a86.png">

**Expected behaviour**
I expected the sidebar to display the pivot modal when any of the listed tabs are clicked
e.g
<img width="950" alt="Screenshot 2021-05-11 at 9 34 20 AM" src="https://user-images.githubusercontent.com/15857679/117785333-6360c400-b23c-11eb-9cf1-4a10e7396673.png">

**Please tell us about your environment:**
npm - v6.14.12
node - v14.16.1

* **AG Grid version:** 
 ```v25.2.0  (ag-grid-enterprise)```

* **Browser:**
```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36```

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
