### ISSUE TITLE
Text not aligning when i am using numberColumn and cellClass

### ISSUE THREAD

**Issue by fedorovvldmr** [ag-grid/ag-grid#4478]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
[plunker](https://plnkr.co/edit/8aTTVaMoPymigdjG)
Same field with 3 different styling

**Current behavior**
NumberColumn fields with cellClass doesn't contain class ag-right-aligned-cell

**Expected behavior**
NumberColumn fields with cellClass contains class ag-right-aligned-cell

**Please tell us about your environment:**
Mint 20, PhpsStorm, npm, webpack 4, Apache 2

**AG Grid version:** 25.1.0
Same thing in last version 25.2.0

**Browser:**
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0

**Language:** ES9, Vue 2

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug

In our opinion, this would be a supprt request as you are providing two different hints to style the cell

Note that we don’t have the capacity to take feature requests/support as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
