### ISSUE TITLE
Ag-Grid display toolbar in standalone chart

### ISSUE THREAD

**Issue by mdmusaib** [ag-grid/ag-grid#4481]
I'm new to Ag-Grid chart, can you tell me how to implement a toolbar for changing dynamically different chart like bar, line, stacked etc by clicking on the toolbar, how to implement that in Ag-Grid standalone chart .,

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
