### ISSUE TITLE
From context menu how can I mark as link for the editing cell

### ISSUE THREAD

**Issue by mdmusaib** [ag-grid/ag-grid#4482]
Hi,
Using Ag-Grid context menu I have created a option in context menu like mark as link, if the user click on that option I want to make that cell text to became a link tag with href, how can I achieve this feature can you help me by providing some sort for fix,

Thanks you for giving such a great library

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
