### ISSUE TITLE
Edit multiple cells at the same time - user input

### ISSUE THREAD

**Issue by Talch87** [ag-grid/ag-grid#4483]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

I'm using Ag-Grid with ReactJs.
How can I edit multiple cells at once? 

example: 

- I have column A and B

- User edits cell B1

- I want to copy the same value to all the cells in B where AX = A1

Thanks for any help

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
