### ISSUE TITLE
how to use selection in detail grid , the selection  in  detail grid will linkage with main table? 

### ISSUE THREAD

**Issue by Mxxxxrk** [ag-grid/ag-grid#4484]
**I'm submitting a  surport

Current behaviour.
 a grid with detail grid and this  detail grid has cell renderer . this cell renderer is inclued  ag-grid.  in another ways, this is a ag-gird with three layer nesting

**Expected behavior**
how to use selection  in that grid to selected a row or group will have the impact of selecting all its children in detail grid and cell renderer

* **AG Grid version:**
ag-grid-vue | ag-grid-enterprices

* **Language:** [ vue | ES6/]

**Comment by Mxxxxrk** [comment]
and how to use gridevent in detailgrid? eg：selectionChange , rowSelected .....

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
