### ISSUE TITLE
Improve typings for sortModel and filterModel in IGetRowsParams

### ISSUE THREAD

**Issue by apieceofbart** [ag-grid/ag-grid#4485]
`sortModel` and `filterModel` are types as `any` , is there a way to improve that? Can I help?
They are described here:
https://github.com/ag-grid/ag-grid/blob/latest/community-modules/core/src/ts/interfaces/iDatasource.ts

**Comment by makinggoodsoftware** [comment]
Hi,

We have flagged this as a good_suggestion

This means that this is a candidate to be in a future release.

At this moment we don’t have a ticket number for this that you can use to track in our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

But we should be updating this ticket with this information as soon as we process the good suggestions, as we do these in batches. Note also that at this stage we can’t guarantee that we will deliver this, but we will take it into consideration

Thanks for your feedback!

**Comment by apieceofbart** [comment]
I had go at this, so if anyone's interested here are types for Simple Column Filters
```
type Operator = 'AND' | 'OR'

type NumberFilterType =
  | 'equals'
  | 'notEqual'
  | 'lessThan'
  | 'lessThanOrEqual'
  | 'greaterThan'
  | 'greaterThanOrEqual'
  | 'inRange'

type TextFilterType =
  | 'equals'
  | 'notEqual'
  | 'contains'
  | 'notContains'
  | 'startsWith' 
  | 'endsWith' 
  | 'empty' 

type DateFilterType = 'equals' | 'notEqual' | 'lessThan' | 'greaterThan' | 'inRange' | 'empty' 

type DateFilter = {
  filterType: 'date'
  dateFrom: string
  dateTo: string | null
  type: DateFilterType
}

type TextFilter = {
  filterType: 'text'
  filter: string
  filterTo?: string
  type: TextFilterType
}

type NumberFilter = {
  filterType: 'number'
  filter: string
  filterTo?: string
  type: NumberFilterType
}

type SingleConditionFilter = DateFilter | TextFilter | NumberFilter

type ConditionWithoutFilterType<T extends SingleConditionFilter> = Omit<T, 'filterType'>

type TwoConditionsFilter = (
  | {
      condition1: ConditionWithoutFilterType<DateFilter>
      condition2: ConditionWithoutFilterType<DateFilter>
      filterType: 'date'
    }
  | {
      condition1: ConditionWithoutFilterType<TextFilter>
      condition2: ConditionWithoutFilterType<TextFilter>
      filterType: 'text'
    }
  | {
      condition1: ConditionWithoutFilterType<NumberFilter>
      condition2: ConditionWithoutFilterType<NumberFilter>
      filterType: 'number'
    }
) & {
  operator: Operator
}

type FilterModel = {
  [colId: string]: SingleConditionFilter | TwoConditionsFilter
}

type SortEntry = {
    sort: 'asc' | 'desc'
    colId: string
  }
  
type SortModel = SortEntry[]
```

**Comment by kiril-matev** [comment]
Hello,

Thank you for using AG Grid and for your feedback.

We already export NumberFilter, INumberFilterParams, NumberFilterModel, etc so you can use these already.

We do not type gridApi.setFilterModel() as the filter can be a custom filter, for which we don't (can't) have typings for, so the model MUST be any. For specific filters we provide, then the interface needs to be referenced independently (eg use NumberFilterModel for Number Filter).

With regards the type (lessThan, greaterThan etc) again the application can provide custom types, which blocks us for making this an enum.

We agree with you that we need to provide types for gridApi.getSortModel and gridApi.setSortModel. We've recorded this in this feature request:
**AG-3944 [Typing] Add missing types to grid interfaces**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See the next release date and whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using the instructions here. This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on the changelog page.

Thanks again for bringing this up with us.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
