### ISSUE TITLE
`gridCore` object is not available in v25.1.0 or higher

### ISSUE THREAD

**Issue by johngnapp** [ag-grid/ag-grid#4487]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
In v25.0.1 I was using `api.gridCore.getRootGui()` to get the HTML element that wraps the AG Grid. This wrapper element has some CSS variables set on it as part of an external theme. In my code I was querying these variables and using them to calculate the row height via the `getRowHeight()` function.

This plunkr shows a basic example of what I'm trying to do in v25.0.1 (the row height is set correctly based on the CSS variables): https://plnkr.co/plunk/K13DZuzHZrLkie64 

After upgrading to v25.2.0, the gridCore object comes back as undefined, so I can no longer access the HTML wrapper. I couldn't find anything in the changelog to say that this had been deprecated, or that there was now an alternate way of getting the HTML wrapper element.

This plunkr shows that the accessing the HTML wrapper via the `gridCore` object no longer works, so the row heights fall back to the default value of 20px set in my `getRowHeight()` function: https://plnkr.co/plunk/fU2pMj29I3oI3xz5

**Expected behavior**
I'd expect the API data structure to stay the same between minor versions, as this feels like a breaking change. If not, is there an alternate way to access the grid's HTML wrapper?

**Please tell us about your environment:**
Windows 10 / Webstorm / AG Grid Enterprise

* **AG Grid version:** X.X.X
Fine in 25.0.1. Broken in 25.1.0 and 25.2.0.

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

* **Language:**
React 16.9.0
Typescript 4.2.4
ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as you were using an undocumented area of the grid at your own risk

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by johngnapp** [comment]
Thanks for this @makinggoodsoftware . So am I right in thinking that if something isn't in the API docs, then it's just for internal use so we probably shouldn't be using it?

**Comment by makinggoodsoftware** [comment]
Hi,

I think as in most libraries, you can only rely on not having breaking changes if you stick to the official docs, AG Grid is very flexible and has lots of potentials if you play with it, but you have to be careful then and make sure that as you update the customizations keep working

Hope this makes sense

**Comment by rostyslav-vasyliuk** [comment]
Hi @johngnapp,

have you found the workaround to access the HTML wrapper in v25.1.0+?

**Comment by SteveSchreiner** [comment]
This was the reply from support a couple of weeks ago when I ran into the same issue:

--------------------------------------------------------------
In v25.3.0 you can access the grid div using the gridCompController api property, the following example prints the grid div to the dev console when the button above the grid is clicked:

https://plnkr.co/edit/Dv799rTu3He3Zimy

**Comment by rostyslav-vasyliuk** [comment]
@SteveSchreiner thanks a lot for the solution 😉

**Comment by johngnapp** [comment]
@rostyslav-vasyliuk - I used `document.querySelector()` in the end to access the grid's wrapper; it's less specific, but it worked in my use case as I knew I'd only have a single instance of the grid wrapper.
