### ISSUE TITLE
Fill handle fails to fill small numbers (<= 1e-7) across more than one columns/rows

### ISSUE THREAD

**Issue by vivvea** [ag-grid/ag-grid#4488]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**REPRO STEPS:**

1. Enter a number 0.000000001 in a numeric column
2. Use fill handle to fill the value to two numerical columns to the right or two rows below

**Current behavior**
When you use the fill handle to fill a small number <= 1e-7 across more than one columns / rows it fails to fill the value after the first col/row. You will get an console error

`Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.l [as findLineByLeastSquares] (ag-grid-enterprise.min.js:8)
    at t.processValues (ag-grid-enterprise.min.js:8)
    at m (ag-grid-enterprise.min.js:8)
    at ag-grid-enterprise.min.js:8
    at Array.forEach (<a
![ag](https://user-images.githubusercontent.com/54615503/117136723-734a5500-adb1-11eb-8a49-84e8af7ada99.png)
nonymous>)
    at f (ag-grid-enterprise.min.js:8)
    at f (ag-grid-enterprise.min.js:8)
    at t.handleValueChanged (ag-grid-enterprise.min.js:8)
    at t.onDragEnd (ag-grid-enterprise.min.js:8)
    at Object.onDragStop (ag-grid-enterprise.min.js:8)`

It seems that the findByleastSquares fails to get maxDecimals due to number.toString() does not contain a decimal dot in case of a small number.

`maxDecimals = Math.max(maxDecimals, **value.toString().split('.')**[1].length);`

**Expected behavior**
Fill handle should be able to fill the value also after the first filled col/row

**Please tell us about your environment:**
Windows 10 

* **AG Grid version:**
Latest

* **Browser:**
Atleast chrome and firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
