### ISSUE TITLE
Cell renderer value turned as string if grouped

### ISSUE THREAD

**Issue by vingeek-dev** [ag-grid/ag-grid#4489]
**I'm submitting a ...** 
```
[x] bug report
[] feature request
[] support request
```

**Steps to reproduce**

Angular - https://plnkr.co/edit/gLa2wvDbPKv5eUEC

- Open plunker link;
- Open console (to see logs);
- Add a row group of 'Days of Air Frost' column;
- You can see that the grouped row shows an incorrect value;
- In the console you can see the value returned by the cell before and after the group;

**Current behavior**

If a column specifies a cell renderer when grouped, it loses the correct type value and is transformed into a string. This could break the renderer component.

**Expected behavior**

The grouped row return the correct value and shows the cell with the correct renderer.

**Code Reference**

https://github.com/ag-grid/ag-grid/blob/27ef98b7f80e68e5f1f920644b657fda82c55f26/community-modules/core/src/ts/valueService/valueService.ts#L299

AG Grid version: **25.2.0**
Browser: **Chrome**
Language: **Typescript 2.3.2**

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
