### ISSUE TITLE
add Header Components throw Cannot read property 'addEventListener' of undefined     at DragService2.addDragSource

### ISSUE THREAD

**Issue by yang8807** [ag-grid/ag-grid#4491]
![image](https://user-images.githubusercontent.com/10320021/119430974-4c45ca00-bd44-11eb-84c6-9bf563f74cb7.png)

above imges is error, when i used default Header Components nothing error , although my Header Components is empty,

`import React from 'react';

export const TestHeaderRender: React.FC = () => {
    return <div>hello</div>;
};`

` frameworkComponents={{
                        FieldCellEditor,
                        // FieldColumnHeader,
                        TestHeaderRender,
                        FieldCellRender,
                        TableCustomerAction,
                    }}`

**Comment by yusufkayaer** [comment]
> ![image](https://user-images.githubusercontent.com/10320021/119430974-4c45ca00-bd44-11eb-84c6-9bf563f74cb7.png)
> 
> above imges is error, when i used default Header Components nothing error , although my Header Components is empty,
> 
> `import React from 'react';
> 
> export const TestHeaderRender: React.FC = () => {
> return
> 
> hello
> ;
> };`
> ` frameworkComponents={{ FieldCellEditor, // FieldColumnHeader, TestHeaderRender, FieldCellRender, TableCustomerAction, }}`

Hi @yang8807 ;

Is any plunker example or somethink like?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
