### ISSUE TITLE
Sass warning with sass 1.34 relative to / operator

### ISSUE THREAD

**Issue by lk77** [ag-grid/ag-grid#4495]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Sass warning with sass 1.34
```
    ╷
255 │         margin-bottom: ag-param(grid-size) / 2;
    │                        ^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@ag-grid-community/core/dist/styles/ag-theme-base/sass/parts/_widgets.scss 255:24             ag-theme-base-part-widgets()
    node_modules/@ag-grid-community/core/dist/styles/ag-theme-base/sass/_ag-theme-base-mixin.scss 39:5         ag-theme-base()
    node_modules/@ag-grid-community/core/dist/styles/ag-theme-material/sass/_ag-theme-material-mixin.scss 8:5  ag-theme-material()
    resources/sass/style.scss 15:3                                         root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(ag-param(grid-size), 2)

More info and automated migrator: https://sass-lang.com/d/slash-div
```

**Expected behavior**

No warning is showing

running `sass-migrator division node_modules/@ag-grid*/**/*.scss` fixes the issue temporarily.

Tested on 23.3.0

thanks.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by lk77** [comment]
i don't understand why you closed it

**Comment by josh-bkfs** [comment]
Please reopen this bug. It is affecting us as well, and is making the output of, for example, the Karma test runner extremely verbose. Would you at least take a PR?

**Comment by ShaneK** [comment]
Because I'm limited to using an older version of ag-grid because of my license, we "fixed" (read: worked around) this issue by adding `npx sass-migrator division node_modules/ag-grid*/**/*.scss` to our postinstall script, after installing the `sass-migrator` package.

Just in case anyone else finds themselves in a similar situation.

**Comment by ShaneK** [comment]
@josh-bkfs: https://github.com/ag-grid/ag-grid/issues/4543#issuecomment-872915469
