### ISSUE TITLE
Resize columns doesn't work with vue-window-portal

### ISSUE THREAD

**Issue by Patrick64** [ag-grid/ag-grid#4496]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**

I'm using [vue-window-portal](https://www.npmjs.com/package/vue-window-portal/v/1.0.0) which is a Vue component to render content in a new window. When rendering `ag-grid-vue` in this new window it doesn't allow you to resize the columns, probably because it's getting the mouse position from the main window and not the window opened by `vue-window-portal`.

See demo here [https://codesandbox.io/s/ag-grid-vue-example-forked-ld2jr?file=/src/App.vue](https://codesandbox.io/s/ag-grid-vue-example-forked-ld2jr?file=/src/App.vue)

**Current behavior**
Resizing the column widths not working in  `vue-window-portal`

**Expected behavior**
Able to resize column widths in a separate window

**Please tell us about your environment:**
Using vue 2 on windows.

* **AG Grid version:** X.X.X
"ag-grid-community": "^25.3.0",
"ag-grid-vue": "^25.3.0",

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

* **Language:** 
Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

We had a look at this, but there is nothing that we can find suspicious on our end I am afraid, is there any chance you could reproduce this without a 3rd party framework?

Otherwise all I can think is to contact support for vue-window-portal

Will leave this open with the label waiting-for-repro

**Comment by Patrick64** [comment]
@makinggoodsoftware  Thanks for looking into it. I'm not sure how to recreate it without vue. I suspect the only round this is for there to be a way to pass the reference to the window into the `ag-grid-vue` component which grid would then use instead of the global window.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
