### ISSUE TITLE
[React] Custom headers are destroyed and re-created after setting column definition instead of getting re-rendered

### ISSUE THREAD

**Issue by udinkar** [ag-grid/ag-grid#4497]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Reproducible Scenario**
In ag-grid-react, every time column definition is set, custom headers are destroyed and re-created instead of getting re-rendered after receiving new props. As a result, the state preserved inside the headers is lost.

**Current behavior**
Every time column defintion is set, I believe react-portal inside ag-grid is destroyed and a new one is created.
As a result, the header components inside that portal are also destroyed and recreated.
This makes it hard to work with stateful headers and clicking on headers gets flakey.

**Expected behavior**
Headers get new props and re-render after column definition is set. They are NOT destroyed and re-created.

**Environment:**
React

**AG Grid version:**
24.0.0

**Browser:**
Chrome (doesn't matter)

**Language:**
TypeScript | ES6/7 (doesn't matter)

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by udinkar** [comment]
Hello,

Thank you for responding back to me.
Please note that the system does not work as expected.

Let's say a user clicks on a column header, and in parallel, column definition is set, this will cause the header to be re-created. Because the header got destroyed, the click handlers also went away. Therefore the click event will result in nothing. Such race conditions are caused by the current implementation of custom headers in ag-grid-react.

I did try few different approaches and none of the workarounds worked. Hence the bug report.

Thank you!

**Comment by makinggoodsoftware** [comment]
Hi,

We have never seen behaviour like the one that you describe, would you be able to provide us with a reproducible scenario?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by brandonmcconnell** [comment]
I'm experiencing the same issue
