### ISSUE TITLE
Ag Grid in SSRM with Pagination configuration > current page does not reset to page 1 when filter applied

### ISSUE THREAD

**Issue by kdutta25** [ag-grid/ag-grid#4498]
**I'm submitting a Bug** 
```
[x] bug report => 'Current page does not reset to page 1 when filter is applied in SSRM with rowModelType: 'serverSide', serverSideStoreType: 'partial' configuration '.
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Server Side Row Model with the following configurations with rowModelType: 'serverSide', serverSideStoreType: 'partial' and pagination setup
- Framework: React

**Current behavior**
- Have set up a Plunker example for the following AG Grid versions:
- Configuration same as described above
- AG Grid v25.1.0: https://plnkr.co/edit/u3B6W2SUuqrtS2MR
- AG Grid v25.2.0: https://plnkr.co/edit/OHU39qClHjiRMbIY
- AG Grid v25.3.0: https://plnkr.co/edit/yM5bQucWQq21Z0HL

- For all the above Plunker examples, if I move to page 5 (any page apart from 1st) and search with a value of '2004' in 'year' columnDef then observation is as below:
Grid stays to the **5th page** when it should have moved to the **1st page**

**Expected behavior**
- Have set up a Plunker example in AG Grid v24.1.0 with the following configurations.
https://plnkr.co/plunk/CMoYRo8wnABkzmtb
- Configuration same as described above 
- If I move to page 5 (any page apart from 1st) and search with a value of '2004' in 'year' columnDef then the expected observations:
Grid moves to the **1st page** and response is as expected in the console.log.

**Please tell us about your environment:**
MAC OS Catalina - v10.15.6 / Visual Studio Version: 1.45.1 / Node version: v12.16.3

* **AG Grid version:** 
The issue started appearing from AG Grid v25.1.0 and is present in v25.2.0 and v25.3.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

* **Language:** [react-16.14.0]

**Comment by makinggoodsoftware** [comment]
Hi,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by kdutta25** [comment]
Quick question, why has this ticket marked as closed.

Isn't this an issue as shown in Plunker Examples for AG Grid Versions: 25.1.0/25.2.0 and 25.3.0 while it worked as expected in AG Grid version: 24.1.0
