### ISSUE TITLE
Missing null check returns false positive.

### ISSUE THREAD

**Issue by blghns** [ag-grid/ag-grid#4503]
Missing null check on initialIndex
https://github.com/ag-grid/ag-grid/blob/437c5b942a8c25468a6a75f07022cd48f22519d0/community-modules/core/src/ts/columns/columnModel.ts#L2722

if initialIndex is null, then null >= 0 returns true.

The issue can be reproed by setting initialRowGroupIndex or initialPivotIndex to null.

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion this properties should not ever initialised to null

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by blghns** [comment]
I think not initializing to null makes sense. Only wish that was explicitly stated in the docs like here https://www.ag-grid.com/javascript-grid/column-properties/#reference-columnsOnly
