### ISSUE TITLE
Adding custom event handlers in the buttons on the sidebar

### ISSUE THREAD

**Issue by iamfarazbaig** [ag-grid/ag-grid#4507]
Hi,

I was looking at adding my own event handler for the buttons on the sidebar that toggle the Toolbar. I am looking at adding the "mouseover" event to open when the user hovers over the button and then to close it when the user hovers away from the toolbar.

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
