### ISSUE TITLE
Did not find solution for editing grouped columns

### ISSUE THREAD

**Issue by SairaAR** [ag-grid/ag-grid#4509]
I am using the Enterprise Ag-grid component, using a feature of row editing on click of a button and save/cancel.
There are a group of columns when I close any group editing gets disable and the entire row converted into view mode.
Can you help me to get editing while we group/ungroup columns?

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
