### ISSUE TITLE
VUE3: Accessing root client context inside Cell Renderer/Editor [Quasar2]

### ISSUE THREAD

**Issue by TuringJest** [ag-grid/ag-grid#4510]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Trying to use a quasar2 component inside AG-Grids renderer throws an error as the quasar component will try to access the $q Object on the quasar instance which is not available inside the cell renderer.  

Is there any workaround for this? 
Can we make the quasar instance available in ag-grid/ cell renderer?

* **AG Grid version:** ag-grid-vue3 25.0.3

* **Browser:**

* **Language:** [TypeScript 4.2.2 | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
