### ISSUE TITLE
ag-theme-dark has overlapping "select all" checkbox in list

### ISSUE THREAD

**Issue by mahimaverma24** [ag-grid/ag-grid#4511]
**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** 25.2.2 

* **Browser:**

* **Language:** [all | TypeScript 4.25 | ES6/7 | ES5]
![image](https://user-images.githubusercontent.com/82210286/121348261-c467de80-c945-11eb-94ce-6e7629e083e8.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
