### ISSUE TITLE
Row selection -> Select Just Filtered Bug

### ISSUE THREAD

**Issue by kaiwang-aviatrix** [ag-grid/ag-grid#4513]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.
**Requesting Community Support**
If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.
**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

Link: https://plnkr.co/edit/?p=preview&preview 

**Current behavior**
This is from the example of 'Just Filtered'
1. Click on the left select all checkbox from the header of 'Athlete' column.
2. In the 'quick filter' filter type something
3. uncheck the 'select all' filter and then check 'select all' filter again.
After quick filter filtered and after uncheck, select all should only select the filtered content.

**Expected behavior**

In the describtion it says: The checkbox works on filtered rows only. That means if you filter first, then hit the checkbox to select or un-select, then only the filtered rows are affected.

'Select all' after 'unselect all' clicked should always select filtered things only.
After 'quick filter' filtered and after unselect all, select all should only select the filtered content.

**Please tell us about your environment:**
It will always happened

* **AG Grid version:** X.X.X
The example I've attached is the example from AG-grid official website, so should be the latest version.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All language

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as the quick filter does not participate in the selection

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
