### ISSUE TITLE
[ag-grid-react] Potential issue in code

### ISSUE THREAD

**Issue by croraf** [ag-grid/ag-grid#4515]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

The potential problem I'm noticing is theoretical, an illogical thing noticed when going through the code.

**Providing a Reproducible Scenario**
-

**Current behavior**

This line seems wrong: 
https://github.com/ag-grid/ag-grid/blob/b25.3.0/grid-packages/ag-grid-react/src/agGridReact.ts#L307

**Expected behavior**

Should be:
`delete asyncChanges[synchronousChangeProperty];`

* **AG Grid version:** 

branch b25.3.0

* **Browser:**

* **Language:**

**Comment by seanlandsman** [comment]
Thanks for reporting this - this is indeed a bug and has now been fixed

thanks!
