### ISSUE TITLE
Header Checkbox select all / unselect all

### ISSUE THREAD

**Issue by arias9306** [ag-grid/ag-grid#4516]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Is there any possibility to change the behavior of the checkbox in the header so that instead of selecting all when there are selected rows, it deselects them? as you can see from the expected behavior

Currently, if there are selected rows and by clicking on the header checkbox all elements are selected, I want to customize it to make the opposite action. 

Thanks in advanced

**Current behavior**

![ag-grid](https://user-images.githubusercontent.com/6402598/121581485-81644480-c9f3-11eb-85de-ae5dbbb0e8c6.gif)

**Expected behavior**

![gmail_edit_0](https://user-images.githubusercontent.com/6402598/121581539-8cb77000-c9f3-11eb-875c-8fe4412d35e3.gif)

* **AG Grid version:** Angular 25.0.1

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
