### ISSUE TITLE
ag-grid-vue3 was introduced in the VUE3 framework. When the rowData data was changed, the ag-grid-vue3component could not render the latest data

### ISSUE THREAD

**Issue by huntJs** [ag-grid/ag-grid#4517]
ag-grid-vue3 was introduced in the VUE3 framework. When the rowData data was changed, the ag-grid-vue3component could not render the latest data, such as when i click a button ,push a data to rowData, the component  does not render, But the data is rendered and updated elsewhere on the page

**Comment by seanlandsman** [comment]
@huntJs 25.3.1 of ag-grid-vue3 has been released - do you want to try this and see if it solves your problem?

**Comment by seanlandsman** [comment]
and @ag-grid-community/vue3 I should add

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
