### ISSUE TITLE
Aggregate/Sub-total values skewing axis data for ag-grid cross-filter and range charts

### ISSUE THREAD

**Issue by cjfitzgerald11** [ag-grid/ag-grid#4519]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
Due to grouping of grid, the series axes of multiple cross-filtered and standard range charts are skewed due to extraneous data points. As shown in the screenshots below, the group sub-totals are included in the cell range used by the charts. Because the cell range properties include only the ability to define a rowStartIndex and a rowEndIndex, I've been unable to skip the sub-total rows and have thus ended up with skewed chart axis scales. This results in one data point rendering an entire chart useless due to a massive data discrepancy. As detailed below, these large data points are not associated with a specific group by which we aim to filter but are instead the sum total of each group. In the pie and column charts pictured below, these are the largest elements in the chart and are not associated with a specific label, and in the area chart, these are the large data points that are not associated with a date. Additionally, because these large data points are not associated with a specific group within a grouping column, any attempt to use the clicking function of a cross-filtering chart on that area will break the other charts.

<img width="457" alt="Screen Shot 2021-06-11 at 3 58 37 PM" src="https://user-images.githubusercontent.com/37812637/121753825-6287b000-cad0-11eb-8add-affc0e9d80d4.png">
<img width="1178" alt="Screen Shot 2021-06-11 at 3 58 55 PM" src="https://user-images.githubusercontent.com/37812637/121753847-703d3580-cad0-11eb-8753-8e3ee254861f.png">
<img width="432" alt="Screen Shot 2021-06-11 at 3 59 08 PM" src="https://user-images.githubusercontent.com/37812637/121753855-7501e980-cad0-11eb-8fe6-f41848fdbf82.png">

**Expected behavior**
In the properties for the cellRange parameter of chart creation, the ability to define a set of columns is allowed. Ideally, the ability to do the same with a range of rows would be possible. 

**Please tell us about your environment:**
macOS Big Sur (11.4), Atom/Terminal, Yarn

* **AG Grid version:** 25.3.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 OPR/76.0.4017.177"

* **Language:** ES6

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by mingfang** [comment]
why was this closed. this is still a (huge)problem
