### ISSUE TITLE
[scroll] support page up/ down, home and end keys

### ISSUE THREAD

**Issue by erwin-beckers** [ag-grid/ag-grid#452]
Goto this page : http://ag-grid.com/angular-grid-virtual-paging/index.php
scroll down a bit to the first table
Select row #3 with a mouse click
press page down 3 times. between keypresses allow the grid to refresh
after the 2nd time the grid seems to lose its focus and you have to select it again with the mouse before you can do page down/pageup again

**Comment by ceolter** [comment]
happens on any grid, not just infinite scrolling. i tested it also on the test drive. i presume this is the grid cell with the focus been ripped out (row virtualisation), and then the page-down is not part of the grid anymore. i'll see about moving the focused cell down one page also - however not sure if this is easy.

what do the other grids do, does anybody know?

**Comment by erwin-beckers** [comment]
In my opinion the focus should be moved to the row 1 page below ?
(And for when pressing page up, move the focus to the row 1 page up)
While you are at it.. would it be possible to add support for the HOME/END keys also ;-)

**Comment by ceolter** [comment]
> While you are at it.. would it be possible to add support for the HOME/END keys also ;-)

lol, your funny. yea will stick this all on the to-do list.

**Comment by fkoulba** [comment]
+1 on this.

It seems that grid loses focus on loading data, virtual row removed or something about that.

**Comment by fkoulba** [comment]
As a temporary solution to losing focus problem I am using focus() on focused cell:

grid.querySelector('.ag-cell-focus').focus();

**Comment by fkoulba** [comment]
After some investigation I see that focus (checking through document.activeElement) is moving from focused cell to body when cell's row removed (virtualRowRemoved event) when scrolling in virtual paging mode.

**Comment by ceolter** [comment]
@fkoulba tnks for feedback

**Comment by jare-talend** [comment]
#1074 I made a PR to set a default focus when the grid lost the focus. This is workaroud by waiting a better solution which will be set the focus on the first cell of the next/prev page and manage the HOME/END keys. I began to study this but that require more time to determine the number of visible rows on the view port and how integrate it in the library.

**Comment by AswinkumarRA** [comment]
for this issue better you try the code

eventHandler(event) {
        const el = document.querySelector('.ag-body-viewport');
        const h = el.offsetHeight;
        console.log(event, h);
        if (event.keyCode == 33 && h) {
            el.scrollTop -= h;
        }

        if (event.keyCode == 34 && h) {
            el.scrollTop += h;
        }
    }

**Comment by ceolter** [comment]
@AswinkumarRA thanks for the suggestion - i've made a note to come back to his and do similar in the grid.

**Comment by chenzhiyuanthu** [comment]
any progress on this? @ceolter .

**Comment by ceolter** [comment]
no, still on the list, but work not scheduled.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-69

**Comment by caffeinum** [comment]
Hi! Any progress on the issue? Somehow page-down page-up scrolling doesn't work at my project even with the last lib version, but it works perfectly at the demo:

[https://www.ag-grid.com/javascript-grid-infinite-scrolling/#gsc.tab=0](https://www.ag-grid.com/javascript-grid-infinite-scrolling/#gsc.tab=0)

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
