### ISSUE TITLE
Browser back button causing grid to be duplicated

### ISSUE THREAD

**Issue by masonoise** [ag-grid/ag-grid#4521]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have a simple Grid defined in the normal way:

```
const gridOptions = {
  columnDefs: columnDefs,
};

const eGridDiv = document.querySelector('#myGrid');

new agGrid.Grid(eGridDiv, gridOptions);

agGrid.simpleHttpRequest({url: '/my/data'})
  .then(data => {
    gridOptions.api.setRowData(data);
  });
```
This works as expected, except that when I click away and use the browser back button, I end up with two Grids, one below the other inside the same DIV. Inspecting the page shows two DIVs with `ref="eRootWrapper"`, one for each Grid. 

**Expected behavior**
I would want the `new agGrid.Grid(eGridDiv, gridOptions)` call to notice that there is already a grid attached to the specified DIV, and not create another Grid.

I tried working around it by wrapping the Grid creation:
```
if ($(".ag-root-wrapper").length == 0) {
  new agGrid.Grid(eGridDiv, gridOptions);
}
```
This does prevent the double-creation, but leads to a different error because something's not getting initialized:
```
Uncaught TypeError: Cannot read property 'setRowData' of undefined
    at VM458 dashboard-60e49b1a434eed114835.js:145
    at ag-grid-community.min.noStyle.js:8
    at ag-grid-community.min.noStyle.js:8
    at P (ag-grid-community.min.noStyle.js:8)
    at t.onDone (ag-grid-community.min.noStyle.js:8)
    at ag-grid-community.min.noStyle.js:8
    at XMLHttpRequest.n.a.o.onreadystatechange (ag-grid-community.min.noStyle.js:8)
```

**Please tell us about your environment:**
Currently I'm just prototyping something so this is running on a MacBook Pro, macOS Catalina, 10.15.7.
jQuery 3.6.0, running in a Rails 6.0 app using Turbo. The way Turbo does partial page rendering is the underlying cause of this, I'm sure, since the back button isn't re-rendering the page fully.

* **AG Grid version:** X.X.X
I'm pulling this in with
`https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js`
which is currently v25.3.0.

* **Browser:**
`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"`

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
