### ISSUE TITLE
Suppress rowSelected event while programatically selecting a row node

### ISSUE THREAD

**Issue by m3niza** [ag-grid/ag-grid#4522]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
I am consuming ag-grid in Angular with:

`<ag-grid
...
(rowSelected)="rowSelected($event)"
...
</ag-grid>`

When I am manually selecting a row using the mouse, it is fine to call the *rowSelected()* function. However, when I am selecting a row using *rowNode.selectThisNode()*, it is still triggering the *rowSelected()* function. I have also tried various combination values in the parameters in *rowNode.setSelected(newValue, clearSelection, suppressFinishActions)* as well as through *gridApi.selectNode(rowNode, tryMulti, suppressEvents)*. I am still unable to suppress triggering of *rowSelected()* function on programmatically triggering a row selection.

**Expected behavior**
Is there any way to programmatically select a row node without triggering the (rowSelected) event?

**Please tell us about your environment:**
Windows 10, IntelliJ IDE, Angular, npm

* **AG Grid version:** 25.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

* **Language:** [TypeScript 3.9.5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
