### ISSUE TITLE
BUG: ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/server' in '/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/ag-grid-react/lib'

### ISSUE THREAD

**Issue by abhatia1994** [ag-grid/ag-grid#4524]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```
**Providing a Reproducible Scenario**
- Using ag-grid-react: ^25.3.0
- Using ag-grid-community: ^25.3.0
- React verion in my app: ^16.12.0
- react-dom version: ^16.12.0
- Getting `ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/server' in '/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/ag-grid-react/lib' `error on running `npm build` in React application.

Here is the full stack:
`
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/server' in '/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/ag-grid-react/lib'
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/webpack/lib/Compilation.js:925:10
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/neo-async/async.js:2830:7
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/neo-async/async.js:6877:13
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
resolve 'react-dom/server' in '/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/ag-grid-react/lib'
  Parsed request is a module
  using description file: /Users/abhatia/Documents/aura2/packages/aura-web/node_modules/ag-grid-react/package.json (relative path: ./lib)
    aliased with mapping 'react-dom': '/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/react-dom/index.js' to '/Users/abhatia/Documents/aura2/packages/aura-web/node_modules/react-dom/index.js/server'`

**Current behavior**
App is not building and i get above mentioned stack trace in the error.

**Expected behavior**
App builds successfuly

**Please tell us about your environment:**
OS: Mac

* **AG Grid version:** 25.3.0

* **Language:** TypeScript@3.9.3

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
