### ISSUE TITLE
How to properly update language when Browser refreshes?

### ISSUE THREAD

**Issue by matthjes** [ag-grid/ag-grid#4527]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hi,
We're currently having a hard time figuring out how to properly update the language for AG Grid tables when the user changes it. 
We have a dropdown menu with the language selection. When the user select an entry, the language is updated in the backend and the browser performs a reload:
```
public selectLanguage(code: string) {
  this.userService.setLanguage(code)
    .subscribe(() => {
      this.windowRef.nativeWindow.location.reload(true);
    });
}
```
Then, in the constructor of `app.component.ts`, the default language get set and the language for the user is requested from the background:
```
constructor(private readonly errorService: ErrorService,
            private readonly translate: TranslateService,
            private readonly userService: UserService) {
  errorService.subscribe(new ErrorToConsole());

  translate.addLangs(['EN', 'DE']);
  translate.setDefaultLang('DE');
  translate.use('DE');

  userService.getCurrentUser().subscribe(user => {
    translate.use(user.langKey);
  });
}
```
Now the problem ist that the other components (and AG Grid) get initialized before the request for the language finishes, so the default language is show. We've tried using the `TranslateService.onLangChange` callback, but we didn't manage to find a AG Grid method that forces the grid to reload and thus translate the e.g. headers with the the updated language.

In general, what would be the best way to do this? I.e. wait for the language to load and then (re)draw the AG Grid. E.g. for the header we already use the translate service when defining the columns:
```
columnDefs: ColDef[] = [
  {
    colId: 'COLUMN1',
    valueGetter: params => this.tableService.translate(params.data.name),
    headerValueGetter: () => this.tableService.translate('TRANSLATE_KEY_1'),
    initialSort: 'asc',
    sortable: false,
    flex: 1
  },
  {
    colId: 'COLUMN2',
    valueGetter: params => this.tableService.toYesOrNoString(params.data.skipForAssignedEeks),
    headerValueGetter: () => this.tableService.translate('TRANSLATE_KEY_2'),
    sortable: false,
    flex: 1
  },
];
```
But we did not find a way yet to force the grid to reevaluate the headers.

**Please tell us about your environment:**
* OS: Windows 10
* IDE: IntelliJ
* Browser: Chrome
* Framework: Angular

* **AG Grid version:** 24.0.0

* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"

* **Language:** TypeScript 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 
In any case, we just recently published this blogbost that might help:

https://blog.ag-grid.com/switching-the-localization-language-in-ag-grid/ 

Thanks
