### ISSUE TITLE
change rowHeight on rowModelType="infinite"

### ISSUE THREAD

**Issue by oscar-joar** [ag-grid/ag-grid#4528]
**I'm submitting a ...**

[x] bug report

Current behaviour.

When using rowModelType="infinite", the attribute getRowHeight does not work at all.

I am trying to change the row height. Therefore I tried other alternatives like using:
rowStyle = {'height': '30px !important'} //30 is the wished height
which works only for the first row, because of this css property 'transform': 'translateY(0px)'

For the rest ones, the height is 30px, (though the row-height looks bigger) but the 'transform' property values are:

(row 0 'transform': 'translateY(0px)' )
row 1 'transform': 'translateY(41px)' <--- because the default height is 41 (I didn't set it)
row 2 'transform': 'translateY(82px)
row 3 'transform': 'translateY(123px)'
row 4 'transform': 'translateY(164px)'
...

Expected behaviour. 

The translation should be applied by using the parameter 30 instead.

row 0 'transform': 'translateY(0px)'
row 1 'transform': 'translateY(30px)'
row 2 'transform': 'translateY(60px)
row 3 'transform': 'translateY(90px)'
row 4 'transform': 'translateY(120px)'
...

**Please tell us about your environment:**
Windows 10
IDE: Visual Studio Code

* **AG Grid version:** 25.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

* **Language:** TypeScript 4.0.5 ES6

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
