### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cloneNode' of null

### ISSUE THREAD

**Issue by khanhpv** [ag-grid/ag-grid#4532]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
1. A grid running with at least 1 initial group, bound data
2. Have 1 column spans across more than next 4 columns; there are rows with span and not span
3. Click column menu on the column next to spanned column.
4. Menu does not open, but browser throw error
![image](https://user-images.githubusercontent.com/3120540/122969599-074e9b00-d3b7-11eb-9ae2-a166a7fc576f.png)

![image](https://user-images.githubusercontent.com/3120540/122969666-16cde400-d3b7-11eb-9c50-7dc4727764a5.png)

**Expected behavior**

the column must open to filter rows not spanned
**Please tell us about your environment:**

* **AG Grid version:** X.X.X

25.2
* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
