### ISSUE TITLE
Text under row group is not rendering for pinned row

### ISSUE THREAD

**Issue by ursNj** [ag-grid/ag-grid#4533]
**Current behavior**
Text under row group is not rendering for pinned row

**Expected behavior**
Text under row group should render for pinned row

**Please tell us about your environment:**
Mac

* **AG Grid version:** X.X.X
angular-ag-grid- 20.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript. : 2.4

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
