### ISSUE TITLE
group header display unexpected with both valueGetter and aggFunc

### ISSUE THREAD

**Issue by kaala** [ag-grid/ag-grid#4534]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
![图片](https://user-images.githubusercontent.com/246542/123074607-09ae0500-d44a-11eb-9dd0-020b986b6f13.png)

**Expected behavior**
aggregate result should only show in footer and not header
the row header should be empty, and not use the result of valueGetter

**Minimal reproduction of the problem with instructions**
```
grid.groupIncludeFooter = true
grid.groupDefaultExpanded = -1
grid.groupSuppressBlankHeader = false

grid.rowData = [
  { pdt: 'A', month: 'Jan' },
  { pdt: 'B', month: 'Jan' },
  { pdt: 'C', month: 'Jan' },
  { pdt: 'A', month: 'Feb' },
  { pdt: 'B', month: 'Feb' },
  { pdt: 'C', month: 'Feb' },
]

grid.columnDefs = [
  { field: 'pdt', rowGroup: true },
  { field: 'month', },
  {
    field: 'calc',
    valueGetter: function (arg) {
      return 1
    },
    aggFunc: function (arg) {
      return 2
    }
  }
]
```

**What is the motivation / use case for changing the behavior?**
above code is a simplified sample to reproduce the problem.
all the value are stored in external variable and have complicate calculate function, so valueGetter is required.
and the aggregate result should only show in footer, not in header, so groupSuppressBlankHeader = true is not viable

**Please tell us about your environment:**
aggrid enterprise 25.2.0

I have to workaround this problem by explicit identify the group header in valueGetter and return null for every columns
But is there a better way to work with this?

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

Note that valueGetters take precedence over aggregations

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
