### ISSUE TITLE
Ag-grid-vue3 doesn't work fine 

### ISSUE THREAD

**Issue by beocaca** [ag-grid/ag-grid#4536]
i have problem with vue 3 quasar 2 and ag-grid-vue3
I don't know which one is not working well,
In your opinion, should I use vue2 or vue 3?
vue 3 should and is appropriate at this time of porting,
I'm really confused, when vue 2 can make it smooth without any bugs 

i can not use :
import {useQuasar} from "quasar";
 mounted() {
    console.error(useQuasar())
  }
in childrend Componet when i create cellRendererFramework, everything work, but with out Quasar "this.$q"

![image](https://user-images.githubusercontent.com/51392704/123221534-3ff68d80-d4f9-11eb-9f3b-586984e9b12c.png)

![image](https://user-images.githubusercontent.com/51392704/123220747-7089f780-d4f8-11eb-893a-a4286ee182e2.png)
![image](https://user-images.githubusercontent.com/51392704/123220767-77186f00-d4f8-11eb-85c5-0d82838f09f7.png)

**Comment by seanlandsman** [comment]
We've discovered a couple of issues in ag-grid-vue3 that are severe - these have now been fixed and will be available in the next release.

I can't say for sure if your issue is related to this or to quasar 2 - if you can provide a repro I'd be happy to take a look

**Comment by beocaca** [comment]
![image](https://user-images.githubusercontent.com/51392704/123256124-cbcce180-d51a-11eb-8066-222d4c2cce15.png)

you can see, that work , but dont know this.$q
be flow that i cant use alot of component of quasar 
the icon WARNING work!! , can not see any problem with call component parent/children of quasar,
![image](https://user-images.githubusercontent.com/51392704/123256262-f9198f80-d51a-11eb-807d-7d315b682843.png)

i have try to use the ag-grid-vue (not 3) and quasar 1 (vue 2), it work nice
i think the way of Ag-grid call and render cell of cellrenderer function, does it destroy everythings,call from where,... it's accident with ag-grid-vue3 , 
please take a look with me !!! 
https://github.com/beocaca/app123
.../src/main.vue
thank you very much!!

**Comment by beocaca** [comment]
> We've discovered a couple of issues in ag-grid-vue3 that are severe - these have now been fixed and will be available in the next release.
> 
> I can't say for sure if your issue is related to this or to quasar 2 - if you can provide a repro I'd be happy to take a look
