### ISSUE TITLE
Changing order of columnDefs is not recognized

### ISSUE THREAD

**Issue by githubuser234** [ag-grid/ag-grid#4537]
**I'm submitting a ...** 
```
[x] bug report
```

Changing order of column definitions during runtime is not recognized by ag grid.

**Providing a Reproducible Scenario**
https://plnkr.co/edit/dKMWLA954k6sdxHQ

Click "Swap column order" button.

![grafik](https://user-images.githubusercontent.com/83961121/123262492-391b4b00-d4f8-11eb-9ade-0c1478122f4d.png)

**Current behavior**
Nothing happens if order of columnDefs is changed.

**Expected behavior**
The new order defined in the new columnDefs array should be applied.

**Please tell us about your environment:**

* **AG Grid version:** 25.3.0

* **Browser:**
Firefox, Chrome

* **OS:**
Windows 10

**Comment by makinggoodsoftware** [comment]
Hi,

Please find information about this here:

https://www.ag-grid.com/react-grid/column-updating-definitions/#applying-column-order

Thank
