### ISSUE TITLE
Ag-grid-vue3 doesn't work fine

### ISSUE THREAD

**Issue by beocaca** [ag-grid/ag-grid#4538]
i have problem with vue 3 quasar 2 and ag-grid-vue3
I don't know which one is not working well,
In your opinion, should I use vue2 or vue 3?
vue 3 should and is appropriate at this time of porting,
I'm really confused, when vue 2 can make it smooth without any bugs

i can not use :
import {useQuasar} from "quasar";
mounted() {
console.error(useQuasar())
}
in childrend Componet when i create cellRendererFramework, everything work, but with out Quasar "this.$q"

![image](https://user-images.githubusercontent.com/51392704/123267782-95499380-d527-11eb-8882-1b32232e602d.png)

@seanlandsman

you can see, that work , but dont know this.$q
be flow that i cant use alot of component of quasar
the icon WARNING work!! , can not see any problem with call component parent/children of quasar,
![image](https://user-images.githubusercontent.com/51392704/123267820-9e3a6500-d527-11eb-9850-ac6a8ebd8f62.png)
i have try to use the ag-grid-vue (not 3) and quasar 1 (vue 2), it work nice
i think the way of Ag-grid call and render cell of cellrenderer function, does it destroy everythings,call from where,... it's accident with ag-grid-vue3 ,
please take a look with me !!!
https://github.com/beocaca/app1231

thank you very much!!

**Comment by seanlandsman** [comment]
25.3.1 of ag-grid-vue3 has been released - do you want to try this and see if it solves your problem?

**Comment by beocaca** [comment]
yes, how can i try that sir ?

**Comment by beocaca** [comment]
@seanlandsman  i tried 25.3.1 ag-grid-vue3 , had same problem, no thing change

**Comment by seanlandsman** [comment]
Ok thanks - I'll take a look at your repo today and see what I can find

**Comment by hawkeye64** [comment]
It looks to me like you are mixing Options API with Composition Api.
```js
// Composition API
import {useQuasar} from "quasar";
```
and
```js
// Options API
mounted() {
```

You should use one or the other.

**Comment by beocaca** [comment]
No,
I try, still same problems

Vào 20:04, Th 2, 28 thg 6, 2021 Jeff Galbraith ***@***.***>
đã viết:

**Comment by exninja** [comment]
I've noticed a few things with the demo repo:

1. Ag-grid's **params** is also unavailable.
2. **params** are available in the cellRendererFramework component if the test page/component are copied into a vue-3 only repo (no Quasar)  so Vue-3 + Ag-grid-vue3 works fine without Quasar 2.
3. The problem still presents itself regardless of whether component is added by name or by reference (https://www.ag-grid.com/vue-grid/components/)
4. Injecting Quasar $q object doesn't fix this - in fact _q_ not found error is thrown.

My hunch is that Quasar 2 might be the problem here and not ag-grid.

**Comment by beocaca** [comment]
![image](https://user-images.githubusercontent.com/51392704/123732447-202de380-d8c4-11eb-9c12-9ec51f943d26.png)
thanks everyone for the help, but still can't find the error ^^,
params still works,no mater witch use option api or composition api,
but reactivity seems to have a problem

**Comment by seanlandsman** [comment]
Looking at this repo I get a number of errors when starting (lint related, so I disabled that)

I now get this:

App • Chaining "UI" Webpack config
App •  WAIT  • Compiling of "UI" in progress...
App •  DONE  • "UI" compiled with errors • 9014ms
App •  ERROR  •  UI  in ./.quasar/client-entry.js

Module not found: Can't resolve imported dependency "boot/NewComponent"
Did you forget to install it? You can run: yarn add boot/NewComponent

App •  COMPILATION FAILED  • Please check the log above for details.

It's also not clear to me how to actually serve this content - after running `quasar dev` what do I do next?  I'm not familiar with quasar

**Comment by beocaca** [comment]
> Looking at this repo I get a number of errors when starting (lint related, so I disabled that)
> 
> I now get this:
> 
> App • Chaining "UI" Webpack config
> App • WAIT • Compiling of "UI" in progress...
> App • DONE • "UI" compiled with errors • 9014ms
> App • ERROR • UI in ./.quasar/client-entry.js
> 
> Module not found: Can't resolve imported dependency "boot/NewComponent"
> Did you forget to install it? You can run: yarn add boot/NewComponent
> 
> App • COMPILATION FAILED • Please check the log above for details.
> 
> It's also not clear to me how to actually serve this content - after running `quasar dev` what do I do next? I'm not familiar with quasar

ohh, i think you saw it the other day, 
i tried to provide a global component to quasar, but same problems
i just updated it, please check it
You can add
`<q-icon name='warning'></q-icon>`
to test

**Comment by exninja** [comment]
@beocaca 

I'm finding Params was only available in the renderer component because `<ag-cell></ag-cell>` was also rendered on your main test page. If you remove `<ag-cell></ag-cell>` from the test page then params is unavailable when ag-cell is used as the cellRendererFrameworkComponent.

The repo has changed so I recreated the index and component in Vue 3.
Does this help?

```
<!-- src/pages/Index.vue -->
<template>
  <q-page class="row items-center justify-evenly">
    <ag-grid-vue 
      style='width: 600px; height: 500px;'
      class='ag-theme-alpine'
      :columnDefs='columnDefs'
      :rowData='rowData'>
    </ag-grid-vue>
  </q-page>
</template>

<script>
import { AgGridVue } from 'ag-grid-vue3';
import TestAgCell from 'components/TestAgCell.vue';

export default {
  name: 'Main',
  components: {
    AgGridVue
  },
  setup () {

    const columnDefs = [
      {
        field: 'make',
        cellRendererFramework: TestAgCell
      },
      { field: 'model' },
      { field: 'price' }
    ]

    const rowData = [
      { make: 'Toyota', model: 'Celica', price: 35000 },
      { make: 'Ford', model: 'Mondeo', price: 32000 },
      { make: 'Porsche', model: 'Boxter', price: 72000 }
    ]

    return {
      columnDefs,
      rowData
    }

  }
};
</script>

```

```
<!-- src/components/TestAgCell.vue -->
<template>
  <div>
    <div>Hi you</div>
    <div>{{ params.value }}</div>
    <q-icon size='50px' color='red' name='warning'></q-icon>
  </div>
</template>

<script>
import { useQuasar } from 'quasar'
// import { toRef } from 'vue'

export default {
  name: 'AgCell',
  // error ag-grid params is already declared in props - so don't redeclare
  // props: {
  //   params: { type: Object }
  // },
  // setup (props) {
  setup () {
    const $q = useQuasar()

    // cannot access params in cellRendererFramework component
    // const params = toRef(props, 'params')

    console.error('Ag-Cell:');
    console.error($q); // undefined
    console.error(params); // undefined
    console.error(params.value); // uncaught reference error
  }
};
</script>

```

**Comment by beocaca** [comment]
@exninja 
thank you very much, but not that problem,
your code is the same as mine, it doesn't even work :(
I think it's better to use Vue2 in combination with an Enterprise, temporarily will wait

**Comment by seanlandsman** [comment]
Just an update from me - I am looking at this area in general at the moment - I think there might be an issue with dynamically created Vue 3 components.

I am investigating and will update this issue once I have more information.  If continuing with Vue 2 is an option for now then that's what I'd recommend too.

thanks

**Comment by seanlandsman** [comment]
@beocaca I have tracked down the issue - this will be fixed in our next release, currently scheduled for in about 3 weeks time

**Comment by seanlandsman** [comment]
I should add - thanks for the repo too, it helped verify the fix
