### ISSUE TITLE
The first letter is always written in English.

### ISSUE THREAD

**Issue by raviota04** [ag-grid/ag-grid#4539]
"ag-grid-react": "^25.2.0"
The first letter is always written in the alphabet.
You have set suppressClickEdit.
However, if you set it to Hangul and write a text, the first letter is unconditionally displayed in the alphabet, and the second letter is displayed in Korean.
I want the first letter to appear in Korean, but it doesn't work as I want.
What should I do?

![11](https://user-images.githubusercontent.com/72431774/123396486-5295c300-d5dc-11eb-81b8-ca2189bbd469.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
