### ISSUE TITLE
Does Community edition support Infinite Scroll

### ISSUE THREAD

**Issue by pauloneill** [ag-grid/ag-grid#4540]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
I have configured an ag-grid-angular component with Infinite Scroll as follows:
```html
<ag-grid-angular
    style="width: 100%; height: 800px;"
    class="ag-theme-balham"

    [columnDefs]="columnDefs"
    [rowSelection]="rowSelection"
    [rowBuffer]=0
    [rowModelType]="infinite"
    [paginationPageSize]=25
    [infiniteInitialRowCount]=500
    [maxBlocksInCache]=20

    [frameworkComponents]="frameworkComponents"

    (gridReady)="onGridReady($event)"
    (selectionChanged)="onSelectionChanged()"
>
</ag-grid-angular>
```
and in the onGridReady() event, I do this:
```javascript
    // Configure Infinite Scroll callback
    var dataSource: IDatasource = {
      getRows: function (params: IGetRowsParams) {
        // Can we even do this? console.log(params.startRow, params.endRow - params.startRow + 1, this.filter, this.search);

        this.apiClient.getWithPagination(params.startRow, 
                                        params.endRow - params.startRow + 1,
                                        this.filter, this.search).subscribe(response => {
                                            params.successCallback(
                                              response.data, response.totalRecords
                                            );
                                        })
      }
    }

    this.gridApi.rowModelType = 'infinite'; // Get an error here :( PON:25Jun2021
    this.gridApi.setDatasource(dataSource);
```
When this runs, I get this error in the Chrome Console:
```
AG Grid: you can only use a datasource when gridOptions.rowModelType is 'infinite'
  | push.f7ga.GridApi.setDatasource | @ | ag-grid-community.cjs.js:30301
  | onGridReady | @ | payslips.component.ts:278
  | PayslipsComponent_Template_ag_grid_angular_gridReady_20_listener | @ | payslips.component.html:65
```
(the last line is my code)

**Expected behavior**
I'm expecting to see a hint that I have correctly enabled Infinite Scroll

**Please tell us about your environment:**
Windows 10, VSCode, NPM, dotNet Core 5

* **AG Grid version:** X.X.X
ag-grid-community 25.1.0
ag-grid-angular 25.1.0

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 4.0.2 (NPM package)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by pauloneill** [comment]
I did manage to get this working so if anyone else if having problems, please feel free to message me.
If I can add to this ticket even though it's closed, I will endeavour to do so...

**Comment by pauloneill** [comment]
So my <ag-grid> definition became:
```
    <!-- Data grid -->
    <ag-grid-angular
        style="width: 100%; height: 800px;"
        class="ag-theme-balham"
    
        [columnDefs]="columnDefs"
        [components]="components"
        [rowSelection]="rowSelection"
        [rowBuffer]=0
        [rowModelType]="rowModelType"
        [pagination]="true"
        [paginationPageSize]=pageSize
        [infiniteInitialRowCount]=pageSize
        [maxBlocksInCache]=1
    
        [frameworkComponents]="frameworkComponents"
    
        (gridReady)="onGridReady($event)"
        (selectionChanged)="onSelectionChanged()"
    >
    </ag-grid-angular>
```
and then I needed an Infinite Scroll callback like this:
```
      // Configure Infinite Scroll callback
      dataSource: IDatasource = {
            getRows: (params: IGetRowsParams) => {    // "Arrow function lets us access the parent properties"
                  // According to 
                  // https://stackoverflow.com/questions/55562231/ag-grid-server-side-infinite-scrolling-accessing-props
                  // ^^ how we define this is super critical!!! PON:28Jun2021
                this.pageServer.getPaginatedInvoices(params, this.pageSize, this.filter, this.search).subscribe(
                        response => {
                          console.log(response);
                          params.successCallback(
                                // Assume more items to come until hasNextPage is false
                                response.items, response.hasNextPage ? null : response.totalCount
                           );
                });
            }
      }
```

which gets call initially from my onGridReady() event:
```
     // #region Grid Events
      onGridReady(params) {
        //debugger;
        
        this.gridApi = params.api;
        this.gridColumnApi = params.columnApi;
        
        this.gridApi.setDatasource(this.dataSource);
    }
```
This is part of an Angular 10 frontend to a dotNet Core/C# backend using @jasontaylordev 's Clean Architecture template.

Hopefully, this will help someone who gets stuck...
