### ISSUE TITLE
ag-charts-angular breaks install with Angular 12 and npm 7

### ISSUE THREAD

**Issue by StoyanStAtanasov** [ag-grid/ag-grid#4542]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
use ag-charts-angular@"^3.3.0" with angular 12 and npm 7

**Current behavior**
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^8.2.14" from ag-charts-angular@3.3.0
npm ERR! node_modules/ag-charts-angular
npm ERR!   ag-charts-angular@"^3.3.0" from the root project

**Expected behavior**
no error

**Please tell us about your environment:**
Windows 10, node v16.4.0, npm 7.18.1

* **AG Grid version:** X.X.X
ag-charts-angular 3.3

* **Browser:**
does not apply

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
