### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by dangrussell** [ag-grid/ag-grid#4543]
.scss files use "/" for division. Should be changed to use math.div()

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(ag-param(grid-size), 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
246 │         margin: ag-param(grid-size) / 2 0;
    │                 ^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\parts\_widgets.scss 246:17         ag-theme-base-part-widgets()    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\_ag-theme-base-mixin.scss 39:5     ag-theme-base()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\_ag-theme-alpine-mixin.scss 8:5  ag-theme-alpine()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\ag-theme-alpine.scss 7:5         @import

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(ag-param(grid-size), 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
255 │         margin-bottom: ag-param(grid-size) / 2;
    │                        ^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\parts\_widgets.scss 255:24         ag-theme-base-part-widgets()    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\_ag-theme-base-mixin.scss 39:5     ag-theme-base()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\_ag-theme-alpine-mixin.scss 8:5  ag-theme-alpine()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\ag-theme-alpine.scss 7:5         @import

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(ag-param(widget-container-vertical-padding), 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
493 │         padding: (ag-param(widget-container-vertical-padding) / 2) 0px;
    │                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\parts\_widgets.scss 493:19         ag-theme-base-part-widgets()    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\_ag-theme-base-mixin.scss 39:5     ag-theme-base()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\_ag-theme-alpine-mixin.scss 8:5  ag-theme-alpine()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\ag-theme-alpine.scss 7:5         @import

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(ag-param(grid-size), 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
25 │         margin-top: ag-param(grid-size) / 2;
   │                     ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\parts\_filter-tool-panel.scss 25:21  ag-theme-base-part-filter-tool-panel()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\_ag-theme-base-mixin.scss 44:5       ag-theme-base()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\_ag-theme-alpine-mixin.scss 8:5    ag-theme-alpine()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\ag-theme-alpine.scss 7:5           @import

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(ag-param(grid-size), 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
26 │         margin-bottom: ag-param(grid-size) / 2;
   │                        ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\parts\_filter-tool-panel.scss 26:24  ag-theme-base-part-filter-tool-panel()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-base\sass\_ag-theme-base-mixin.scss 44:5       ag-theme-base()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\_ag-theme-alpine-mixin.scss 8:5    ag-theme-alpine()
    node_modules\@ag-grid-enterprise\all-modules\dist\styles\ag-theme-alpine\sass\ag-theme-alpine.scss 7:5           @import

```

**Comment by sgtsquiggs** [comment]
Everywhere that is `X / 2` can be replaced with `X * 0.5` without having to import `sass:math`

**Comment by dangrussell** [comment]
> Everywhere that is `X / 2` can be replaced with `X * 0.5` without having to import `sass:math`
> 
> 
> 
> This can be automated via
> 
> ```
> 
> $ npm install -g sass-migrator
> 
> $ sass-migrator division **/*.scss
> 
> ```

I was just regurgitating the recommended solution in the error message -- your way is cleaner & clever-er!

**Comment by lk77** [comment]
yeah i already made an issue :

https://github.com/ag-grid/ag-grid/issues/4495

**Comment by lounsbrough** [comment]
I put a PR up to resolve, I don't know if maintainers will merge, we'll see!

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
@lounsbrough Thanks for the PR, I have also processed that, now this has been raised to the dev team, please let us have a look, we will get back to you as soon as possible

Thanks!

**Comment by lounsbrough** [comment]
Sounds good, thanks!

**Comment by gportela85** [comment]
Thanks for reporting. This issue will be patched in the next release.
Commits: 
https://github.com/ag-grid/ag-grid/commit/d5b8f53110684afded9f701fa82d14f74ab84557
https://github.com/ag-grid/ag-grid/commit/91747f44d0de217e66b063aeb8b30fe101a65764

**Comment by fgblomqvist** [comment]
@gportela85 @makinggoodsoftware Are we gonna see a release of this anytime soon?

**Comment by VladBozhinovski** [comment]
Any update on this matter?

**Comment by dprensha** [comment]
I think the commit mentioned above was released as part of 26.0.0. However, now I'm seeing other deprecation warnings 😬

**Comment by KES777** [comment]
@sgtsquiggs : 
>Everywhere that is X / 2 can be replaced with X * 0.5 without having to import sass:math
How can I workaround this?

$rfs-base-value: $rfs-base-value / ($rfs-base-value * 0 + 1 / $rfs-rem-value)

**Comment by HERBOD7** [comment]
if you used node-sass and sass-loader,
please downgrade the packages to:
`node-sass: "^4.14.1",
 sass-loader: "^10.1.0"
`

**Comment by yamoonz** [comment]
isnt there any solution to this problem?

**Comment by ShaneK** [comment]
@yamoonz the problem is fixed in current AG-Grid. If you're not subscribed and can't upgrade, you'll need to do a workaround like running the SASS migration script in post install or something.

**Comment by vanishree165** [comment]
> Everywhere that is `X / 2` can be replaced with `X * 0.5` without having to import `sass:math`
> 
> This can be automated via
> 
> ```
> $ npm install -g sass-migrator
> $ sass-migrator division **/*.scss
> ```



> Everywhere that is `X / 2` can be replaced with `X * 0.5` without having to import `sass:math`
> 
> This can be automated via
> 
> ```
> $ npm install -g sass-migrator
> $ sass-migrator division **/*.scss
> ```

This helps me a lot . Thanks @sgtsquiggs 😀

**Comment by vishvaCodesatva** [comment]
thanks. this 

> Everywhere that is `X / 2` can be replaced with `X * 0.5` without having to import `sass:math`
> 
> This can be automated via
> 
> ```
> $ npm install -g sass-migrator
> $ sass-migrator division **/*.scss
> ```

Thanks, this solution worked

**Comment by vishvaCodesatva** [comment]
> Everywhere that is `X / 2` can be replaced with `X * 0.5` without having to import `sass:math`
> 
> This can be automated via
> 
> ```
> $ npm install -g sass-migrator
> $ sass-migrator division **/*.scss
> ```

Thanks. This solved my issue

**Comment by HCDestroyer** [comment]
> Everywhere that is `X / 2` can be replaced with `X * 0.5` without having to import `sass:math`
> 
> This can be automated via
> 
> ```
> $ npm install -g sass-migrator
> $ sass-migrator division **/*.scss
> ```

helped my ass 😜

**Comment by chiragDesaiPantherCodx** [comment]
⠼ Generating browser application bundles (phase: building)...WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(1, $rfs-rem-value)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │     ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │                                ^^^^^^^^^^^^^^^^^^
   ╵
    src/assets/scss/bootstrap/vendor/_rfs.scss 49:32  @import
    src/assets/scss/bootstrap/_mixins.scss 6:9        @import
    src/assets/scss/argon.scss 20:9                   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-base-font-size, $rfs-base-font-size * 0 + 1 / $rfs-rem-value)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
48 │     $rfs-base-font-size: $rfs-base-font-size /
   │ ┌────────────────────────^
49 │ │     ($rfs-base-font-size * 0 + 1 / $rfs-rem-value);
   │ └──────────────────────────────────────────────────^
   ╵
    src/assets/scss/bootstrap/vendor/_rfs.scss 48:24  @import
    src/assets/scss/bootstrap/_mixins.scss 6:9        @import
    src/assets/scss/argon.scss 20:9                   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rfs-breakpoint, $rfs-breakpoint * 0 + 1)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
57 │   $rfs-breakpoint: $rfs-breakpoint / ($rfs-breakpoint * 0 + 1);
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src/assets/scss/bootstrap/vendor/_rfs.scss 57:20  @import
    src/assets/scss/bootstrap/_mixins.scss 6:9        @import
    src/assets/scss/argon.scss 20:9                   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
397 │ $headings-margin-bottom: ($spacer / 2);
    │                           ^^^^^^^^^^^
    ╵
    src/assets/scss/custom/_variables.scss 397:27  @import
    src/assets/scss/argon.scss 24:9                root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($r * 299 + $g * 587 + $b * 114, 1000)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
62 │   $yiq: (($r * 299) + ($g * 587) + ($b * 114)) / 1000;
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src/assets/scss/bootstrap/_functions.scss 62:9  color-yiq()
    src/assets/scss/custom/_variables.scss 716:31   @import
    src/assets/scss/argon.scss 24:9                 root stylesheet

DEPRECATION WARNING: $null: Passing a unit other than deg (25%) is deprecated.

To preserve current behavior: $null / 1%

See https://sass-lang.com/d/color-units

   ╷
19 │       adjust-hue($color, 25%) 100%
   │       ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src/assets/scss/core/mixins/_background-variant.scss 19:7  bg-gradient-variant()
    src/assets/scss/core/utilities/_backgrounds.scss 10:3      @import
    src/assets/scss/custom/_utilities.scss 5:9                 @import
    src/assets/scss/argon.scss 66:9                            root stylesheet

WARNING: 68 repetitive deprecation warnings omitted.
