### ISSUE TITLE
Could not find component KeywordFilter, did you forget to configure this component?

### ISSUE THREAD

**Issue by CrayZhang** [ag-grid/ag-grid#4544]
I came across an error when I tried to add a filter component:
I used 'ag-grid-vue3'

![error](https://user-images.githubusercontent.com/85570261/123470562-97146500-d5c2-11eb-9245-8a5aae9a3d29.png)

![Screen Shot 2021-06-25 at 3 01 44 PM](https://user-images.githubusercontent.com/85570261/123473250-4e5eab00-d5c6-11eb-8b9d-be95cf7313e4.png)

![Screen Shot 2021-06-25 at 2 45 04 PM](https://user-images.githubusercontent.com/85570261/123471580-fd4db780-d5c3-11eb-9a02-5d35cf98267c.png)

**Comment by Alainx277** [comment]
Filter components must be registered in the `frameworkComponents` attribute on the grid. See the [custom filter example](https://www.ag-grid.com/vue-grid/component-filter/#custom-filter-example) .
