### ISSUE TITLE
When using the rowSpan and Column Filter at the same time.

### ISSUE THREAD

**Issue by zhangfangbiao** [ag-grid/ag-grid#4546]
https://plnkr.co/edit/Gi4PG24wNnvITFAV
![image](https://user-images.githubusercontent.com/49065946/123587499-f5d31c00-d818-11eb-9c5e-1b99312a717c.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
