### ISSUE TITLE
Whats the replacement key for childContainers

### ISSUE THREAD

**Issue by nani554** [ag-grid/ag-grid#4547]
I want to access headerRowComps key of childContainers.
ag-grid version: 21.1.0
```
protected gridApi: GridApi;
const api = this.gridApi as any;
const headerRowComps = api.gridPanel.headerRootComp.childContainers[0].headerRowComps;

```
but in ag-grid 25.1.0 childContainers key is removed, so my functionality is broken, there has to some replacement right, could you please provide me a right solution

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
