### ISSUE TITLE
DropDowns are having bad behaviour when inside of custom Master Detail

### ISSUE THREAD

**Issue by cripsito** [ag-grid/ag-grid#4553]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Changin between options on a select element that is inside a custom master-detail is not behaving as expected on internet explorer 11.

Open this plunker using ie11
plunker: https://plnkr.co/edit/Y8aH5NlFXlH86zZo

**Expected behavior**
changing between dropdown options should work when changing using mouse click

**Please tell us about your environment:**

* **AG Grid version:** 25.3.0

* **Browser:** Internet Explorer 11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
