### ISSUE TITLE
The focus of cell is lost when the nested option of the context menu is selected

### ISSUE THREAD

**Issue by Sadragiel** [ag-grid/ag-grid#4557]
**I'm submitting a ...**  
```
[x] bug report
[] feature request
[] support request 
```

**Steps to reproduce**
- Right click on any cell of the grid
- Select any options of context menu on the level of nesting bigger than first one

**Current behavior**
- The clicked cell is NOT focused
- 'document.activeElement' is body

**Expected behavior**
- The behaviour should be the same as if the user clicked on element of context menu from the first levels of nesting
- The clicked cell **is** focused
- 'document.activeElement' is clicked cell

**Environment:**
The issue is reproducible on DEMO env: https://www.ag-grid.com/example.php
* **AG Grid version:** 18.1.2

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Thank you for your email and for the context you’ve provided.

We were able to reproduce your issue in the current grid version 25.3.

In grid 18.1 cell focus after context menu was not implemented.
However, if you are trying to access the focused cell there is a grid method.
Would this be helpful for you?  :

https://plnkr.co/edit/0sLY2YQetegfyUx2
1. open the link
2. open the console
3. right-click to open context menu 
4. select country/Ireland/dublin

Would this help?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
