### ISSUE TITLE
How to buy AG Grid Enterprise for whole company

### ISSUE THREAD

**Issue by sunnyke** [ag-grid/ag-grid#4558]
Hi，everybody, our team(ShenZhen, China, multi project, multi developer) want to buy AG Grid Enterprise for whole company, who can tell me **how to buy**, tks.

Contact which one???

https://www.ag-grid.com/license-pricing.php

![image](https://user-images.githubusercontent.com/9361776/124246263-58972100-db53-11eb-9b23-6f8045980289.png)

**Comment by beocaca** [comment]
you can send email to AG team

**Comment by makinggoodsoftware** [comment]
Hi,

@beocaca thanks for the help!

As mentioned there, you can contact info@ag-grid.com if you need a bespoke deal
