### ISSUE TITLE
Error While setting showNoRowsOverlay in gridApi of ag-grid-angular

### ISSUE THREAD

**Issue by devraz12** [ag-grid/ag-grid#4565]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I am using ag-grid angular. I am calling an API in ngOnInit and received the API response before gridReady event of ag-grid.  I have used showNoRowsOverlay method of gridApi in the subscribe of API call. Since the API response is received even  before gridReady event, gridApi is returned null. So I get the following error.

`ERROR TypeError: Cannot read property 'showNoRowsOverlay' of undefined`

Do I need to check if gridApi is null every time I use it.?

**Please tell us about your environment:**
Windows 10.

* **AG Grid version:** 23.1.1

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
