### ISSUE TITLE
Bug with focussing custom cell editor on fullRow edit mode

### ISSUE THREAD

**Issue by ChristopheHertigers** [ag-grid/ag-grid#4568]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/rrJqXmG1x0yNAI8z

**Current behavior**
- Double-clicking on the first column (non-custom cell editor) to enter edit mode places the focus on the second column (custom cell editor)
- Double-clicking on the third column (custom cell editor) to enter edit mode also places the focus on the second column
- When in edit mode with focus on the first column, tab navigation to the second column does not work

**Expected behavior**
- Double-clicking on the first column (non-custom cell editor) to enter edit mode => should focus the first column cell editor
- Double-clicking on the third column (custom cell editor) to enter edit mode => should focus the third column cell editor
- When in edit mode with focus on the first column, tab navigation => should move the focus to the second column cell editor

**Please tell us about your environment:**
tested on Windows 10 (Windows NT: 10.0.19042)
I've tested this with the react version, hooks implementation for the custom cell editors.

* **AG Grid version:** 25.3.0
"ag-grid-community": "25.3.0"
"ag-grid-enterprise": "25.3.0"
"ag-grid-react": "25.3.0"

* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

* **Language:** ES6

**Comment by ChristopheHertigers** [comment]
An important note I forgot to mention is that this only occurs when enabling fullRow edit mode on the grid.
The exact same implementation of the cell renderers work without issue in single cell edit mode.
Also the supplied cell editors do not have this behaviour in fullRow edit mode, only the custom cell editors.

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that this example is too complex to be accepted as a bug, do you think you could submit a simplified version of this issue?

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
