### ISSUE TITLE
[React] onGridReady callback not reactive

### ISSUE THREAD

**Issue by fgblomqvist** [ag-grid/ag-grid#4570]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The callback `onGridReady` does not seem to be reactive.
Repro: https://plnkr.co/edit/Hf6eq3o7SeAaeP1f
Open the debug console and hit the play button in the Plunker. You will see this:
![Screen Shot 2021-07-07 at 11 22 21 AM](https://user-images.githubusercontent.com/649260/124786311-9b6f4500-df15-11eb-91ed-448a65c5dc40.png)

As you can see, despite that `foo` was set to `true` before the `onGridReady` handler fired, it was seen as `false`. This is (I'm guessing) because the `onGridReady` that ag-grid calls is the very first one, which naturally has a closure where `foo` is `false`.

**Expected behavior**
Any and all callbacks should be reactive. This was achieved for most callbacks with v25.2.0, however, seems like this one was left out perhaps?

I have not been able to find the code that controls this, but I am stumped as to why `onGridReady` was left out of this page:
https://github.com/ag-grid/ag-grid/blob/ce78f09f6e7fd17811c8742c082ce4ada4037381/grid-packages/ag-grid-docs/documentation/doc-pages/grid-callbacks/callbacks.json

* **AG Grid version:** 25.3.0

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as most of our callbacks are not reactive, only the rowData and column defs can be cofigured to be reactive I am afraid

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
