### ISSUE TITLE
 ag-grid-react from a CDN

### ISSUE THREAD

**Issue by giorgitus** [ag-grid/ag-grid#4572]
[x] support request 

Is there a way to load ag-grid-react from a CDN? Any clue?

Trying like this (full HTML file contents):

<script src="https://unpkg.com/react@16.5.2/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@16.5.2/umd/react-dom.production.min.js"></script>
<script src="https://unpkg.com/ag-grid-community@19.0.0/dist/ag-grid-community.min.js"></script>
<script src="https://unpkg.com/ag-grid-react@19.0.0/umd/ag-grid-react.min.js"></script>

But ag-grid-react doesn't load:

Uncaught TypeError: Cannot read property 'ColDefUtil' of undefined

Any idea?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
