### ISSUE TITLE
row collapse without master detail

### ISSUE THREAD

**Issue by panospcm** [ag-grid/ag-grid#4576]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
I am having an angular material ag grid and would like to have an accordion column, which when clicked will expand the row with a new details renderer. I would like to be able to toggle the accordion. The functionality exists in master detail but I would like a different approach, if possible.

If reporting a bug make sure to state.

**Current behavior**
Cannot find a way to create a row expansion (accordion) without master detail. The full width row doesn't provide enough functionality for this ( as far as the examples in the documentation go)

**Expected behavior**
Being able to expand each row using a column accordion, without using the master detail feature.

**Please tell us about your environment:**
Windows, VSCode, Angular

* **AG Grid version:** 24.0.0

* **Browser:**
* Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
