### ISSUE TITLE
valueFormatter does not work for pivot headers

### ISSUE THREAD

**Issue by jaymalik217** [ag-grid/ag-grid#4577]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/pIHa32y3xEgOa7uh?preview

**Current behavior**
valueFormatter on a column does not format the value in Pivot Headers

**Expected behavior**
valueFormatter on a column should format the value in Pivot Headers

**Please tell us about your environment:**
MacOs, Intellij, npm, Angular

* **AG Grid version:** 25.3.0
*
* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.0

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
