### ISSUE TITLE
Apply dynamic styling like color, link in export to excel 

### ISSUE THREAD

**Issue by mdmusaib** [ag-grid/ag-grid#4578]
Hi team, 
I'm having a requirements like I'm generation ag-grid dynamically based on the json, also I'm changing the color of cell, and applying link to cell value on the flow, and finally on click of export to excel, I need the same styling to be applied and come in the excel file, how to achieve this feature is it feasible to achieve using ag-grid, please let me know the solution, looking forward to hear from you...

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
