### ISSUE TITLE
Header Selection Checkbox not getting updated automatically on Row Selection by code

### ISSUE THREAD

**Issue by m3niza** [ag-grid/ag-grid#4582]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[] feature request
[] support request
```

**Current behavior**
Steps:
1. Clicking on the row selection checkbox using the mouse or keyboard to select/unselect any row
2. The header checkbox automatically gets updated.
This is the correct behavior.

Steps:
1. Select/unselect a row using code rowNode.setSelected(true, false, true) or node.setSelected(false, false, true)
2. The header checkbox does not get updated.
Here, in the setSelected() function, the **clearSelectionFlag must be false** so that the old selections are not cleared and the **suppressFinishActions flag must be true** so that selection/deselection through code does not re-trigger the (selectionChanged) event.

Example:
https://stackblitz.com/edit/ag-grid-header-checkbox-update-issue
Type a first name and click on the Change Selection button to select the rows in the table.

**Expected behavior**
When we perform a selection/unselection action through code or rowNode.setSelected, the header checkbox should also get updated automatically like in the case of selection/unselection by mouse/keyboard.

**Please tell us about your environment:**
Windows 10, nodejs v14.17.3, npm

* **AG Grid version:** 25.0.0
Issue still exists in 25.3.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

* **Language:** [TypeScript 3.9.5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as the third parameter you are using is not meant to be used externally, from our docs:



setSelected(newValue: boolean, clearSelection: boolean) | Select (or deselect) the node. newValue=true for selection, newValue=false for deselection. If selecting, then passing true for clearSelection will select the node exclusively (i.e. NOT do multi select). If doing deselection, clearSelection has no impact.
-- | --




https://www.ag-grid.com/react-grid/row-object/#reference-rowNodeMethods 

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
