### ISSUE TITLE
cell style right alignment not working when also there's a cellClass definition

### ISSUE THREAD

**Issue by tlarrain** [ag-grid/ag-grid#4584]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When you have a column definition with type: 'rightAligned' and also cellClass: 'my-class', the items are aligned to the left. If you remove cellClass, the items do actually align to the right.

**Expected behavior**
alignment using the type key should work separately from the cellClass variable, except maybe if the cell class is overriding the text alignment. My class, for example, only changes the background color of the cell.

**Please tell us about your environment:**
Windows 10, React/Typescript project running locally for now using Webpack.

* **AG Grid version:** 25.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

* **Language:** TypeScript 4.2 | ES6

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by JustasJankauskasPersonal** [comment]
- AG grid version: 28.2.1
- Browser any
- Framework any


Issue is still there. When `cellClass` is applied, then `type` property definition gets ignored. So if I have `type: "rightAligned"` and `cellClass` in one colDef, the `type` definition for some reason is not applied.
Pasting a screenshot where it can be seen in action:
![image](https://github.com/user-attachments/assets/2ce80dab-2771-48fb-9bcb-08ea16501c62)

Do not have stackblitz, but it is a 1 minute work to reproduce, I have highlighted the code in screenshot which will help to reproduce the issue.
