### ISSUE TITLE
when onCellEditingStopped invoke the oldValue and newValue awlays

### ISSUE THREAD

**Issue by yang8807** [ag-grid/ag-grid#4585]
version :25.2.0

![image](https://user-images.githubusercontent.com/10320021/125586206-fb57cf05-8d59-4ee4-baf8-cb45d7e1c574.png)

the oldValue i can't get ,that same with newValue

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
