### ISSUE TITLE
If ag-charts-react supports react 17 (like ag-grid-react) it is missing from package.json peer deps

### ISSUE THREAD

**Issue by at-cf** [ag-grid/ag-grid#4586]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
npm install in ag-grid / ag-charts react 17 project gives error:
```
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from ag-charts-react@3.3.0
npm ERR! node_modules/ag-charts-react
npm ERR!   ag-charts-react@"^3.3.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution
```
Using --force bypasses it and it charts seem to display fine (at first glance).

**Expected behavior**
npm install succeeds without having to use --force flag, or document the required version of React. Started using ag-grid on React 17 (supported) only to find that ag-charts on react may / may not support React 17, it's unclear.

**Please tell us about your environment:**
npm 7.18.1, node 16.4 Windows 10_64

* **AG Grid version:** 
 "@ag-grid-community/core": "25.3.0",
 "ag-charts-react": "^3.3.0",

* **Browser:** N/A

* **Language:** all

**Comment by seanlandsman** [comment]
It does support it - this is just an omission in package.json - you can install it with --force for now

This will be corrected in our next release

Thanks for raising this

**Comment by seanlandsman** [comment]
There is an issue for this this already: AG-5502

You can track it's progress here: https://www.ag-grid.com/ag-grid-pipeline/

**Comment by at-cf** [comment]
Good stuff
