### ISSUE TITLE
Allow jump to last page of server side data

### ISSUE THREAD

**Issue by yehudahkay** [ag-grid/ag-grid#4587]
![image](https://user-images.githubusercontent.com/9964988/125631664-f09f34da-41ed-43a9-a49c-79fa6d0f8d51.png)

Hi, thanks for the great framework! When using the server side model would it be possible to pass the total number of rows to ag grid to enable jumping to the last page? 

Thanks!

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
