### ISSUE TITLE
Exporting to csv with 'allColumns: true' ignores column order

### ISSUE THREAD

**Issue by StanZGenchev** [ag-grid/ag-grid#4592]
**I'm submitting a:
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
If you change the order of the columns and export or get the contents to CSV, with the `allColumns` option set to `true`, the new column order is ignored and old one is preserved.
I have tested this in browser with both the community and enterprise editions.

**Expected behavior**
When exporting or getting grid contents as CSV, current column order should be preserved.

* **AG Grid version:** 25.3.0

* **Browser:**
Firefox
```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0"
```
and Google Chrome
```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
```

* **Language:** [ES6/7]

Here is a very short example page, showing the bug:
```html
<!DOCTYPE html>
<html ng-app="example" lang="en">
<head>
  <meta charset="utf-8" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ag-grid/Docs-25.3.0-20210714/ag-grid-community.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.8.2/angular.min.js"></script>
</head>
<body ng-controller="exampleCtrl">
  <button type="button" ng-click="printCsv()">Print CSV</button>
  <div ag-grid="gridOptions" class="ag-grid-editor ag-theme-alpine" style="height: 200px;"></div>
  <script>
    agGrid.initialiseAgGridWithAngular1(angular);
    var module = angular.module("example", ["agGrid"]);
    module.controller("exampleCtrl", function ($scope) {
      $scope.printCsv = function (event) {
        console.log($scope.gridOptions.api.getDataAsCsv({
          allColumns: true
        }));
      };
      $scope.gridOptions = {
        columnDefs: [{ field: "first" }, { field: "second" }],
        rowData: [{ first: "first", second: "second" }],
        onGridReady: function (params) {
          params.api.sizeColumnsToFit();
        }
      };
    });
  </script>
</body>
</html>
```

**Comment by shuheb** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by LouisMoore-agGrid** [comment]
Hi,

We've looked into this issue and have found the behaviour to be working as expected, the allColumns property will export the columns in the order of the column definition, if the column definitions aren't updated after moving the column positions using the UI then the order the columns are exported in won't reflect the new positions of the columns.

A workaround for the issue you're having would be to set the new column definitions using the api.setColumnDefs() method before exporting to csv. The following example shows this approach:
https://plnkr.co/edit/EH3mZFJfE8oJ91Jl


Hope this helps
