### ISSUE TITLE
Override tabToNextHeader to focus on filter

### ISSUE THREAD

**Issue by js-daniel** [ag-grid/ag-grid#4597]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
https://www.ag-grid.com/react-grid/keyboard-navigation/#tabtonextheader
when we tab on headers, it only moves focus between header columns

**Current behavior**

when we tab on headers, it only moves focus between header columns

**Expected behavior**

is it possible to make a tab to focus on the filter inside the header column?
**Please tell us about your environment:**

Windows 10, yarn, local
* **AG Grid version:** X.X.X

~24.1.0
* **Browser:**

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
tsx, ES6

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
