### ISSUE TITLE
Vue3 reactivity not working after initial mount (25.3.1)

### ISSUE THREAD

**Issue by tommaybe** [ag-grid/ag-grid#4602]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
- Repro
Create a new vue component with Options or Composition API. Add ag-grid component and set :rowData to a data property (`rows`). Add a method `add: () => this.rows.push({...})` and dynamically add a row (through button click or similar) after initial mount => Ag-Grid is not showing the row.

- Plunker Vue3: Here is a Vue3 Plunker with the code reproducing the error. Unfortunately it throws an error on vue-class-component in StackBlitz? https://stackblitz.com/edit/vue-vrj5xr?file=src%2Fcomponents%2FGrid.vue
- Plunker Vue2 (desired behavior): Heres a Vue2 Plunker showing desired behavior: https://stackblitz.com/edit/ag-grid-vue-hello-world-m2ugja?file=app.js

**Current behavior**
When adding elements to a data property array set to rowData, ag-grid does not refresh the grid accordingly. (simple v-for does). This used to work on Vue2. I tried both Composition and Options API, Typescript and ES.

**Expected behavior**
When adding elements to data property array, ag-grid refreshes and shows them.

**Please tell us about your environment:** Win10, VSCode, Vite, Yarn

* **AG Grid version:** 25.3.1

* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"

* **Language:** TS4.3.2 & ES

**Comment by seanlandsman** [comment]
Thanks for reporting this - I can verify that this is indeed an issue and will be investigating it today

**Comment by seanlandsman** [comment]
Thanks for raising this - this has now been fixed and will be available in our next release

**Comment by klongmitre** [comment]
@seanlandsman - Awesome! When can we expect the release?

**Comment by klongmitre** [comment]
@tommaybe - Do you have a workaround for this? It seems (at least for me) that calling `redrawRows()` or `refreshCells()` doesn't force a redraw with the new data. Interestingly, when selecting a row, it provides the correct data.

**Comment by seanlandsman** [comment]
@tommaybe example actually provides a pointer to a workaround - instead of using `reactive` use a `ref` instead

For example:

```
const rows = ref([{ text: "Initial Row" }]);

// then to update it
rows.value = [...rows.value, { text: "Additional Row" }];
```

Doing it this way should be reflected in the grid

**Comment by uaru** [comment]
I am using version 29.3.5 with vue 3.3.4 and it seems the problem still persists. 

```
<ag-grid-vue
　　:grid-options='someOptions'
　　class='ag-theme-alpine'
　　:column-defs='columnDefinitions'
　　 :row-data='rowData'
>
</ag-grid-vue>
```

Initially, in `created()` the initial value of `rowData` is set, and it is displayed properly. 
However, later, when the` rowData` is updated, nothing happens.

**Comment by uaru** [comment]
Three instances of` `av-grid-vue` sharing the same configuration
object actually share the model data as well. 
It means, all three were set to the data, which was written last to any of them.
Finding it took a lot of time, so maybe at least manuals should be adapted. Should I open a new ticket?
