### ISSUE TITLE
Preload data contained in SSRM Row Groups before expanding 

### ISSUE THREAD

**Issue by AdrianSoovary8234** [ag-grid/ag-grid#4605]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I'm displaying multiple RowGroups that contain product data. Within these groups there can be hundreds of variations that should be displayed in the grid. Currently I'm making one request for product data and when the request is successful the row groups with different products gets displayed. If I open a row group with a product, a second request is being made which fetches the variation data. If I want to fire the the variation data request as soon as the first request is successful, the only way I found so far is to open all row groups and close them immediately. This seems super hacky to me and causes several rerenders in React. I didn't find a method in the API through which I can fire the method that is fired when expanding the grid.

**Expected behavior**
I'd appreciate to have a method with which I can basically trigger what happens when opening a row group, just without actually expanding the UI element. And I would absolutely be in love if this behavior could be configured using a prop, where you can either specify that all group data should be preloaded, or groupKeys for certain groups can be provided.

**Please tell us about your environment:**
Mac OS X Big Sur, VSCode, GraphQL

* **AG Grid version:** X.X.X
25.3.0

* **Browser:**
Chrome 92

Typescript, React

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
