### ISSUE TITLE
Freeze/Pin Grid Header in Exported Excel 

### ISSUE THREAD

**Issue by AhmedFay** [ag-grid/ag-grid#4606]
is there a way to freeze/pin grid header in exported excel 

![image](https://user-images.githubusercontent.com/34749560/127782112-8d99c0dd-86e2-44ae-80ce-a5423b4b97f1.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
