### ISSUE TITLE
I'm submitting an issue with Vue3 Composition API CellRender not receiving params

### ISSUE THREAD

**Issue by enguyen807** [ag-grid/ag-grid#4608]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
How do I pass params to my CellEditorComponent? I'm able to render my celleditorcomponent and change the value of the cell but when editing the cell I would expect the current cell value to be passed to the cell editor component. 

I have created a repo with how I'm implementing the CellEditorComponent using SFCs. 
[https://github.com/enguyen807/aggrid-vue3](https://github.com/enguyen807/aggrid-vue3)

* **AG Grid version:** 25.3.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript : 4.1.5
Vue: 3.0.0

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 

I have created an example project which should show how you can pass params to a Vue3 SFC-component, please find this attached.

I hope this helps, 

[test-project.zip](https://github.com/ag-grid/ag-grid/files/6960290/test-project.zip)

**Comment by seanlandsman** [comment]
@enguyen807 there was a bug around setup where `params` wasn't being supplied to `props` - I'd suggest upgrading to 26.0.1 of the Vue 3 component and retrying. 

You should find that `props.params` has all the information you require
