### ISSUE TITLE
Not able to get params.api

### ISSUE THREAD

**Issue by Muzaeed** [ag-grid/ag-grid#4609]
**Current behavior**

`<div *ngFor="let eachLeaf of allLeafs">
    <div>{{eachLeaf.userName}}</div>
    <ag-grid [rowData]="eachLeaf.wireInfo" [columnDefs]="columnDefs" [gridOptions]="gridOptions" 
    (onGridReady)="onGridReady($event, eachLeaf.wireInfo)></ag-grid>
</div>

TS
gridApi: any;
onGridReady(params, data) {
    this.gridApi = params.api;
    this.gridApi.setRowData(data);
}
// somewhere in the code 

getSelectedWiresToProcess() {
    // TODO this is returning empty array
    let selectedWireList = this.selectedWire();
}

get selectedWire() {
    wiresArr: Array<RowNode> = [];
    this.gridApi.getSelectedNodes().forEach((node) => {
        wiresArr.push(node);
    })
    return wireArr;
}
`

**Expected behavior**

selectedWireList = this.selectedWire(); is always  empty array even if we have selected rows from checkbox or row selection.
NOTE: When I am adding the condition to display GRID for first index it's returning the selectedWiresArr with values.
Can anyone please help me out with this problem even if I am getting multiple grid instances.

**Please tell us about your environment:**

Windows 10

* **AG Grid version:** X.X.X

v25.1.x

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6
typescript: ~3.2.2

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
