### ISSUE TITLE
Horizontal scrollbar not visible in MAC OS  with version 25.3.0

### ISSUE THREAD

**Issue by kiransiluveru777** [ag-grid/ag-grid#4610]
**Horizontal scrollbar not visible in MAC OS  with version 25.3.0**

**Description:** 
Horizontal scroll is not scrollable in mac I am checking with the official documentation example in below URL
[https://ag-grid.com/react-grid/full-width-rows/](https://ag-grid.com/react-grid/full-width-rows/
)

Even I have tried used scrollbarWidth: 15 property not worked in my local

**Providing a Reproducible Scenario**
Open the below URL in mac OS

[https://ag-grid.com/examples/full-width-rows/basic-full-width/packages/reactFunctional/index.html](https://ag-grid.com/examples/full-width-rows/basic-full-width/packages/reactFunctional/index.html)

on bottom of the ag grid table scrollbar not visible

**Current behavior:** Horizontal scrollbar not visible and not scrollable using the cursor.
**Expected behavior:** scrollbar should be visible and when I move the scrollbar using the cursor content should scroll.

**environment:**
"ag-grid-community": "^25.3.0"
"ag-grid-react": "^25.3.0"
OS: Mac

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

After some investigation, we have found that this is just the default behaviour for when you have the default scroll options on your Mac...

I would suggest changing your options, or otherwise, if you think this is not relevant, please feel free to follow up

**Comment by kiransiluveru777** [comment]
@makinggoodsoftware changing the default scroll options makes horizontal scrollbar visible 
Thank you...
