### ISSUE TITLE
ag-grid checkbox render error

### ISSUE THREAD

**Issue by tosyue** [ag-grid/ag-grid#4611]
Hi,
Our team is using ag-grid one of our projects. We are facing an issue with select all checkbox functionality.
Normally, the page is displayed properly，checkbox show ok，like this
![image](https://user-images.githubusercontent.com/16470666/127945055-38252e65-6a45-40b8-ac00-60650bb886fb.png)

But sometimes，checkbox display an error,like this
![image](https://user-images.githubusercontent.com/16470666/127944657-ac0fc036-243b-4ba5-80c4-09650f00b5d1.png)

Would you like to know how to solve this problem. Thank you！

ag-Grid version: free

Browser:
"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
