### ISSUE TITLE
Ag-Grid floating filter not taking blank space (using spacebar) in input box. How can fix this issue?

### ISSUE THREAD

**Issue by mahesh7502** [ag-grid/ag-grid#4614]
I have used floating filter in my application. However, Its not taking blank space in input text box. Whenever i provided blank space it will shift in previous place. Attached screenshot for your reference.

![blank-space-issue](https://user-images.githubusercontent.com/14970613/128015437-e69fb68a-4f8d-4a95-81b2-9d5ed39ec3ad.PNG)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
