### ISSUE TITLE
Broken combination of 'Infinite Row Model' and 'Full Width Cell'

### ISSUE THREAD

**Issue by MaKCbIMKo** [ag-grid/ag-grid#4617]
*I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario:**
I use 'Infinite Row Model'. I also provide 'getRowNodeId' function to use my data id as a row node id.

Till the data being loaded from datasource, table displays one empty row without data (that's according your design). I also using 'Full Width Cell' functionality: if 'rowNode.id does not exist' -> I display 'fullWidthCell' component (to say it's loading).

**Current behavior:**
Once data is loaded it renders the data, but the first row (that was displayed initially without data) is still displayed as 'fullWidthCell'

**Expected behavior:**
Once data is loaded, all rows rendered properly

**Additional Information:**
* With pagination it becomes even worse: initially it has only one empty row, but if I know total number of rows (after first data loading), going to different page will start displaying all rows as empty (e.g. as 'fullWidthCell')
* seems like a regression (after updating from AG Grid V 23.2.1)
* after some research I found event 'modelUpdated' is slightly different: in V23.2.1 it states `keepRenderedRows: false`, but in V25.3.0 it states `keepRenderedRows:true` -> and that seems like comes to function `isFullWidthCell(...)` is not getting called after data is loaded
* I also found this commit (https://github.com/ag-grid/ag-grid/commit/401429a8a73b29225c0e953824a7d88fc71a5f74) that might be the reason for this broken behavior
* I didn't find any way to configure that or make it work as before: manually calling `api.redrawRows()` feels too much and it creates a glitch for short period of time when I have rows with new loaded data and 'fullWidthCell'.

**Environment Information:**

* **AG Grid version:** 25.3.0
* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
* **Language:** TypeScript 4.1.5
* **Framework:** Angular 11.2.14

**Comment by MaKCbIMKo** [comment]
Additional things I found:
* I tried different versions of AG Grid and it seems to appear at V25.2.0
* I downgraded to V25.1.0 and it was 'partially' working; 'partially' - I mean that at first data load it worked fine, but going to next page (for instance, via grid api 'paginationGoToPage') new data is loaded, but all rows displayed as 'full width' and 'modelUpdated' event is missing
* I tried that once again with V25.3.0 - 'modelUpdated' invent seems to be back on 'go to page', but 'full width' issue is still there.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 

Thank you for raising this however, I haven't been able to recreate this use case on our end. Could you please fork one of the example plunkers from our documentation (https://www.ag-grid.com/javascript-grid/) and show us what you mean? 

Alternatively, feel free to provide a .zip file or github link with instructions. 

Thanks,

**Comment by MaKCbIMKo** [comment]
Here is simple repro: https://plnkr.co/edit/cUFVK8yUWBqYYTVA

As I can see - even this simple case is broken.

**Comment by icedjello** [comment]
Hi, 

After looking into your use-case, I think there has been a misunderstanding in how Full Width Rows work.
As you can see in the following example, there is no issue when combining Infinite Row Model and FWRs. 
https://plnkr.co/edit/xjlUhCnbZYnFoaM1 

The issues with your example are: 
- You are trying to hint to the grid that a row/cell is in a loading state based on a side-effect.
- You are conflating fullWidthRowRenderers and loadingCellRenderers.

Neither of these approaches is recommended or supported. Due to this, I will be marking this post as "managed-by-community". 
Please refer to AG-Grid's documentation for further information. 

Thanks

**Comment by MaKCbIMKo** [comment]
Hi,

I just checked your example and there issue is still there:

![image](https://user-images.githubusercontent.com/9148665/131690623-bb86a963-4925-4fba-8bf2-1ba47a2e0d7e.png)

Example says that if `sport === 'swimming'` - then it should be FWR. But as you can see at the picture above - it's not for first row. And if you scroll down and up again - it will re-render first row with FWR. I can say that if you will enable pagination - it will be not only for the first row.

It looks like when the data is loaded - it doesn't check against FWR. (but in previous versions it was working just fine).


Answering to issues in my example:
- yes, I am trying to have FWR indicator that item is being loaded. What's another way rather than FWR?
- 'loadingCellRenderer' seems like working only with SSRM (enterprise model)

**Comment by MaKCbIMKo** [comment]
Please re-open this.
