### ISSUE TITLE
React cellEditor does not work with React component without registering

### ISSUE THREAD

**Issue by riwu** [ag-grid/ag-grid#4622]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://plnkr.co/edit/l7pEjuHlM2G3k07B
When trying to edit the cell, it throws an error `Could not find component function MyClass`.

**Expected behavior**
It should accept a Class component as stated on https://www.ag-grid.com/react-grid/cell-editing/

* **AG Grid version:** 25.3.0

* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36"

* **Language:** all

**Comment by seanlandsman** [comment]
When using a framework you need to specify `cellEditorFramework` as documented here: https://www.ag-grid.com/react-grid/components/#component-usage-2
