### ISSUE TITLE
ServerSideRowModel with React-Query

### ISSUE THREAD

**Issue by jvutukur** [ag-grid/ag-grid#4627]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Expected behavior**
With ServerSide rowModel and pagination enabled. Can we use react-query library to cache data. I did not a way to use react-query with ServerSide rowModel

Is there a way to use react-query with ServerSideRowModel of Ag-Grid
```
rowModelType: 'ServerSide'
```

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
