### ISSUE TITLE
I want half header in Excel export with different style and half with different style.

### ISSUE THREAD

**Issue by NitishaSrivastav** [ag-grid/ag-grid#4628]
I have a grid with 13 columns . 1st column is pinned. While exporting I want my pinned header to be left aligned and non-pinned headers to be right aligned. The problem I am facing is that I am not able to set different styles for header based on classes.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
