### ISSUE TITLE
OnCellMouseOut doesn't fire when leaving the table

### ISSUE THREAD

**Issue by mhiatt150** [ag-grid/ag-grid#4630]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When you leave the last or first row, the onCellMouseOut doesn't fire. Basically when you leave the table. 

**Expected behavior**
onCellMouseOut should fire, even when you leave the table

* **AG Grid version:** X.X.X
 v25.3.0 aggrid

* **Browser:**
Latest Chrome

Example: https://plnkr.co/edit/YsBmkgJFALw4kBAM
In the example I change the getRowColor properties based on if the row is "hovered" or not. So the row changes to red if the mouse is over it. When I leave the grid, the color remains.

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by AhmedAGadir** [comment]
Hi,

Thank you for your email.

This seems to be working on our end.

Please see the example and GIF below:

https://plnkr.co/edit/205kry8mAOCUZCYF

![Large GIF (832x512)](https://user-images.githubusercontent.com/33138421/131660961-d6ede50c-802b-4481-a1e5-d3aa969b754e.gif)

As you can see the onCellMouseOut event fires when exiting the grid from the first and last nodes.

I will now close this ticket.
