### ISSUE TITLE
Apply filter on key enter

### ISSUE THREAD

**Issue by Kromas07** [ag-grid/ag-grid#4636]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**

If I press enter after typing anything in a text filter there is no event fired

**Expected behavior**

I would like "Apply filter" when the user press Enter

* **AG Grid version:** 23.2.0

* **Browser:** Chrome

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
