### ISSUE TITLE
Dropdowns within the grid now open up behind sub grids

### ISSUE THREAD

**Issue by mmangin1967** [ag-grid/ag-grid#4637]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Dropdowns within the grid now open up behind sub grids (after version 25.1.0)
![AGGridDropdownIssue](https://user-images.githubusercontent.com/89478289/130665565-e1b93557-8c54-4302-af5c-7bf24a2e7c50.JPG)

**Expected behavior**
Dropdowns should open in front of the sub grids
![AGGridDropdownNoIssue](https://user-images.githubusercontent.com/89478289/130665584-e34ab958-4255-4eaa-9d11-7e077c606ba9.JPG)

**Please tell us about your environment:**
Windows, Visual Studio Code, npm, IIS

* **AG Grid version:**
25.1.0 is good. All versions after that seem to have the problem.

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.67"

* **Language:** 
Typescript 4.3.5

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
