### ISSUE TITLE
 onCellEditingStarted event - keyboard button pressed for a long time

### ISSUE THREAD

**Issue by pedro-severo** [ag-grid/ag-grid#4638]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

### Current behavior

**onCellEditingStarted event**

I'm building a aggrid table with editable fields opening by "Enter" key. But when user keeps pressed "Enter" for a long time, the editable mode of fields are changing from non editable to editable (and vice versa) frantically. Examples below:

![aggrid-textfield](https://user-images.githubusercontent.com/53839013/130683898-d2882be1-5a92-468f-a902-531cb3f5d86e.gif)

![aggrid-switch](https://user-images.githubusercontent.com/53839013/130683904-5bfd98f3-8cb2-4406-9956-eb9f9aabe4d9.gif)

### Expected behavior

When user keeps pressed "Enter" for a long time, the editable mode should open just when user stop press. In other words, rather than event `onCellEditingStarted` be called by `keydown` of HTML, it should be called by `keyup`. 

<br>
<br>

* **AG Grid version:** ag-grid-react: 24.1.1

* **Browser:** Chrome

* **Language:** Typescript: 3.8.3

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
