### ISSUE TITLE
Can we add more condition under text filter model?

### ISSUE THREAD

**Issue by mahesh7502** [ag-grid/ag-grid#4640]
I need to add one more text box with condition under text filter modal. Is it possible? If yes, can you please provide solution for this. I have attached screenshot for reference.

![image](https://user-images.githubusercontent.com/14970613/130736647-35114c48-69e2-40e4-989a-eeeaf42a18da.png)
#

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
