### ISSUE TITLE
[pagination] Implement client side pagination, and then allow filtering and sorting and selection

### ISSUE THREAD

**Issue by thomas-p-wilson** [ag-grid/ag-grid#465]
In the case where a client-side dataset is paged, permit filtering and sorting across the entire dataset rather than just on the visible page.

**Comment by ceolter** [comment]
this doesn't really make sense. the grid doesn't have 'client side pagination'. or are you asking for client side pagination to be included, and then this as a feature on top of that?

in my examples, the data is all in the client, but as far as the grid is concerned, it's getting it one page at a time form the datasource, which is outside of the grid. the datasource can in turn do filtering / sorting here if it wishes, but again, that's out side of the grid.

**Comment by thomas-p-wilson** [comment]
Right, sorry. I did not notice that both examples were using datasources. The problem with handling filtering/sorting outside the grid (in the datasource) is that, while it applies across the entire dataset, selections don't seem to stick around. My thought then was that if we could virtually paginate a local dataset (i.e. without the datasource) that we could then keep selections around. Or is my line of reasoning incorrect?

**Comment by ceolter** [comment]
Correct, selections don't stick, as the grid has no business key to identify the rows.

Any reason you need to paginate? Ie if all rows loaded, just display in grid as normal??

**Comment by thomas-p-wilson** [comment]
Ideally, I'd rather not display hundreds or thousands of rows at any given time. So pagination, in this case, is for display purposes more than anything. My current setup allows the user to select the number of rows they want visible at a given time. I just need a way to get selection to stick around. I very nearly came up with a way to get selections to stick while using a datasource for filtering/sorting, but it was very dirty and very frustrating.

I suspect, going back to your first question, that if we implement client-side pagination in the first place, where the dataset is merely a collection of row data, that selections would end up being sticky anyways. Does that seem right?

**Comment by ceolter** [comment]
> I suspect, going back to your first question, that if we implement client-side pagination in the first place, where the dataset is merely a collection of row data, that selections would end up being sticky anyways. Does that seem right?

yea that would be right. although i haven't implemented it yet, it makes sense!!

**Comment by ceolter** [comment]
for myself, i'm going to change the title of this to 'client side pagination'. what you ask for also makes sense in particular for mobile, where you want the user to view 'one page size' at a time, ie no scrolls at all. then the filtering / sorting comes after that.

ps this is a large amount of work, so i don't expect to get it done this year (i'm taking november and december off for holidays as this year has been particularly busy for me and i need to check myself into a long holiday!!)

**Comment by psivaprasanth** [comment]
Myself also having same requirement badly. Did any one implement filtering on a client side paginated grid. I see current filtering confined to that particular grid page only.

**Comment by kiransmk** [comment]
I have same requirement. 
For filter I used search with angular filter and set it as data source, instead of api.setQuickFilter.

    $scope.onFilterChanged = function () {
      $scope.gridItems = $filter('filter')($scope.masterData, $scope.searchFilter);
      $scope.gridOptions.api.setRowData($scope.gridItems);
      $scope.createNewDatasource();
//      console.log($scope.items);
//      $scope.gridOptions.api.setQuickFilter($scope.searchFilter);
    }

Still need to look to sorting.

Hope this would help some.

**Comment by tochoromero** [comment]
This is a requirement I also have. My company has some strict UI guidelines and pagination is one of them, they don't allow us to show hundreds of rows they want us to paginate the table showing 10 items at a time, and then allow the user to select how many items he wants to see per page.

**Comment by tannerlinsley** [comment]
#587 Related or duplicate

**Comment by derekperkins** [comment]
This is a huge issue for us too @ceolter. We have a full width ag-grid on our dashboard, but with thousands of rows, you can't scroll past the table without first scrolling through thousands of rows. Not being able to paginate / sort on that data makes our app significantly less usable.

**Comment by ceolter** [comment]
@derekperkins noted

**Comment by sasivarnan** [comment]
+1
We are also having this issue, and it is the only issue stopping us to proceed. :disappointed:

**Comment by 4mgad** [comment]
+1
Any update on this topic?
I'm currently researching several grids and I found most of the features I want in ag-grid except client side pagination, please let us know if this feature will be implemented any time soon. Thanks.

**Comment by tannerlinsley** [comment]
I currently have a workaround. I'll post it soon

**Comment by malreynolds** [comment]
+1

**Comment by dojchek** [comment]
Any updates on this one??
I desperately need client side pagination :(

**Comment by tannerlinsley** [comment]
Are you using react?

**Comment by tannerlinsley** [comment]
It was this very issue that drove me to build react-table. Obviously it has
client side pagination as one of its main features.
https://github.com/tannerlinsley/react-table

**Comment by dojchek** [comment]
Nope.. I'm using Angular 2, not React.. 
I also went with my own implementation in the end. I simply couldn't find a decent grid control with all the features I need. This one was the best fit, except for the client side pagination.

Thank you Tanner

**Comment by tochoromero** [comment]
Give Smart Table a try, that is what I use for Angular https://github.com/lorenzofox3/Smart-Table

**Comment by ALFRED-Guillaume** [comment]
I'm also trying to implement client side pagination with filter on the entire dataset using Angular 2.

Is there some examples available ?

Thanks in advance,

**Comment by dojchek** [comment]
My advice is to use this table [bootstrap-table](http://bootstrap-table.wenzhixin.net.cn/)
It's a jQuery table, just wrap it with angular 2 component and you are good to go.

It has tons of features.

**Comment by ALFRED-Guillaume** [comment]
Thank you very much @dojchek but I have already implemented everything I needed using Ag Grid except for this feature..

**Comment by dojchek** [comment]
@ALFRED-Guillaume 
Lack of client-side pagination was the reason why I switched to another datatable lib. I needed that feature asap and ag grid just didn't support it.

**Comment by ALFRED-Guillaume** [comment]
I have find an example somewhere, I just changed couple of things to make it more generic. I post it in case it could be usefull for someone : 
sortAndFilter( sortModel, filterModel ) {
	return this.sortData( sortModel, this.filterData( filterModel, this.allOfTheData ) )
}

sortData( sortModel, data ) {
	let sortPresent = sortModel && sortModel.length > 0;
	if ( !sortPresent ) {
	    return data;
	}
	let resultOfSort = data.slice();

	resultOfSort.sort( function( a, b ) {
	    for ( let k = 0; k < sortModel.length; k++ ) {
		let sortColModel = sortModel[k];
		let valueA = a[sortColModel.colId];
		let valueB = b[sortColModel.colId];

		// this filter didn't find a difference, move onto the next one
		if ( valueA == valueB ) {
		    continue;
		}

		let sortDirection = sortColModel.sort === 'asc' ? 1 : -1;

		// Excluse null values from sort
		if ( valueA === null ) {
		    return 1;
		}
		if ( valueB === null ) {
		    return -1;
		}

		if ( valueA > valueB ) {
		    return sortDirection;
		} else {
		    return sortDirection * -1;
		}
	    }
	    // no filters found a difference
	    return 0;
	});

	return resultOfSort;
}

filterData( filterModel, data ) {
	let filterPresent = filterModel && Object.keys( filterModel ).length > 0;
	if ( !filterPresent ) {
	    return data;
	}

	let resultOfFilter = [];

	for ( let i = 0; i < data.length; i++ ) {
	    let item = data[i];
	    let addToResult: Boolean = true;

	    // Loop over all filters
	    for ( let filterName in filterModel ) {
		if ( !item[filterName] ) {
		    // si null, on exclu du filtre
		    addToResult = false;
		} else {
		    let valueItem = item[filterName].toString(); // Get value of item
		    let valueFilter = filterModel[filterName].filter; // Get value of filter
		    let typeFilter = filterModel[filterName].type; // Get Type of filter (contains, equals, etc..)
		    
		    if ( typeFilter == 'contains' ) {
		        if ( valueItem.indexOf( valueFilter.toString() ) < 0 ) {
		            addToResult = false;
		        }
		    }

		    if ( typeFilter == 'startsWith' ) {
		        if ( !valueItem.startsWith( valueFilter ) ) {
		            addToResult = false;
		        }
		    }

		    if ( typeFilter == 'endsWith' ) {
		        if ( !valueItem.endsWith( valueFilter ) ) {
		            addToResult = false;
		        }
		    }

		    if ( typeFilter == 'equals' ) {
		        console.log('valueItem', valueItem);
		        console.log('valueFilter', valueFilter);
		        if ( valueItem != valueFilter ) {
		            addToResult = false;
		        }
		    }

		    if ( typeFilter == 'notEquals' || typeFilter == 'notEqual' ) {
		        if ( valueItem == valueFilter ) {
		            addToResult = false;
		        }
		    }

		    if ( typeFilter == 'lessThan' ) {
		        if ( valueItem >= valueFilter ) {
		            addToResult = false;
		        }
		    }

		    if ( typeFilter == 'lessThanOrEqual' ) {
		        if ( valueItem > valueFilter ) {
		            addToResult = false;
		        }
		    }

		    if ( typeFilter == 'greaterThan' ) {
		        if ( valueItem <= valueFilter ) {
		            addToResult = false;
		        }
		    }

		    if ( typeFilter == 'greaterThanOrEqual' ) {
		        if ( valueItem < valueFilter ) {
		            addToResult = false;
		        }
		    }
		}
	    }

	    if ( addToResult ) {
		resultOfFilter.push( item );
	    }
	}

	return resultOfFilter;
}
---
createNewDatasource(): void {
	if ( !this.allOfTheData ) return;

	let dataSource = {
	    getRows: ( params: any ) => {
		this.sortedAndFilteredData = this.sortAndFilter( params.sortModel, params.filterModel );
		let rowsThisPage = this.sortedAndFilteredData.slice( params.startRow, params.endRow );
		params.successCallback( rowsThisPage, this.sortedAndFilteredData.length );
	    }
	};

	this.gridOptions.api.setDatasource( dataSource );
}
setRowData( rowData ): void {
	this.allOfTheData = rowData;
	this.createNewDatasource();
}

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-71

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
