### ISSUE TITLE
Vue3 provide / inject API for ag-grid-vue3

### ISSUE THREAD

**Issue by zhiyuanzmj** [ag-grid/ag-grid#4650]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
In vue2 ,I can use provide/inject API for cellRendererFramework.
but when I upgrade to  ag-grid-vue3 provide/inject API is disabled.
I need the provide/inject API to provide Typescript support.

* **AG Grid version:**  
v26.0.0

* **Browser:**
 Chrome/92.0.4515.159

* **Language:**
TypeScript 4.0

**Comment by seanlandsman** [comment]
I've published 26.0.1-beta.0 of both @ag-grid-community/vue3 and ag-grid-vue3

Let me know if this fixes the above issue for you!

thanks

**Comment by zhiyuanzmj** [comment]
Not yet

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks
