### ISSUE TITLE
suppressSizeToFit not working for pinnedBottomRowData

### ISSUE THREAD

**Issue by tanmaya-git** [ag-grid/ag-grid#4653]
Hi, 

I am calling the sizeColumnsToFit() on the gridApi. all the columns are correctly suppressed to fit the container width but when I have a pinnedBottomRowData using setPinnedBottomRowData function, the pinned row has a horizontal scrollbar and it does not suppress width of columns as per container.

I am using the following version 25.3.0

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
