### ISSUE TITLE
Excel export corrupts when using rtl (or utf8 characters) author name

### ISSUE THREAD

**Issue by Viper-Bit** [ag-grid/ag-grid#4658]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- when author name is english export works fine but when i use persian exported file gets corrupted (maybe a utf8 problem)
- https://plnkr.co/plunk/RP86eXtD3Fbd7kPb

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior** export file gets corrupted

**Expected behavior** export file with persian author name

**Please tell us about your environment:**

* **AG Grid version:** 26.0.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84

* **Language:** ES5

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
