### ISSUE TITLE
Focus is lost after redrawRows call

### ISSUE THREAD

**Issue by tania-mel** [ag-grid/ag-grid#4661]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I'm using `redrawRows` to reapply `rowClassRules` after changes. After `redrawRows` call focus gets lost from the cell. 
Example is in plunker, from View Refresh (Angular) page. Focus some row in the grid and click Enter - focus will disappear. 

https://plnkr.co/edit/xyCWsufDA2oPHx43

**Expected behavior**
I didn't find in docs if it's an expected behavior, I'd say focus should stay in this case.

**Please tell us about your environment:**
Windows, WebStorm

* **AG Grid version:** X.X.X
26.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

https://www.ag-grid.com/javascript-data-grid/view-refresh/#redraw-rows
As mentioned in our documentation, redraw rows does the following: 
Remove a row from the DOM and recreate it again from scratch


So after the call to redrawRows, the previously focused element is no longer in the DOM, it’s gone, and in its place there’s a new one. As you are calling redrawRows, you need to manage focus.

A possible solution is to store the selected cell row and column index values, and focus it later on after the call to redrawRows, as shown below:
https://plnkr.co/edit/a3WqZhIemRfz7LzM?preview

Note that pressing Enter key in a cell refreshes the row and it sets focused back on the same cell.


Shuheb‍
Developer | AG Grid

**Comment by tania-mel** [comment]
Hi, thanks for response! 

Yes, I added something like you described, to return focus back after redraw.  Right now plunker page doesn't open (error 522), hopefully it'll repair soon - it would be good to take a look at your solution, maybe it's cleaner than mine.

**Comment by tania-mel** [comment]
Plunker works today - yes, I'm using pretty the same approach as in plunker. Duplicating it here, maybe it'll be helpful to someone.

```
private redrawRows(event: CellValueChangedEvent): void {
	const focusedCell = event.api.getFocusedCell();
	event.api.redrawRows({rowNodes: [event.node]});
	if (focusedCell) {
		event.api.setFocusedCell(focusedCell.rowIndex, focusedCell.column);
	}
}
```
