### ISSUE TITLE
"scrollbarWidth" cannot be changed dynamically

### ISSUE THREAD

**Issue by 5te1n** [ag-grid/ag-grid#4664]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/fbS1LgTD7wCPozDj

**Current behavior**
Dynamic changes to the "scrollbarWidth" property are not reflected in the UI. It looks like you can set this property only initially. The "scrollbarWidth" property affects the vertical line for pinned columns. The offset of this line should be changed if the property has changed. Click the button at the top to dynamically change the "scrollbarWidth" property.

**Expected behavior**
Dynamic changes to the "scrollbarWidth"-property should be reflected in the UI (vertical line offset of Pinned collumns).

**Please tell us about your environment:**

* **AG Grid version:** 26.0.0

* **Browser:**
 Chrome, Firefox, Angular 12

* **Language:**
Angular 12

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as the width of the scrollbar is not meant to be dynamic

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
