### ISSUE TITLE
Server side row model grid is not emiting events with high number of total rows

### ISSUE THREAD

**Issue by tomas-richter** [ag-grid/ag-grid#4668]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
For server side row model (both full and partial) with large amount of total rows (sweetspot seems to be 399458 rows and more) grid stops emiting rowClicked event for rows with high row indexes (for lower indexes event is still emited). Also for these rows mouse hover effects doesn't work and possiby other events.
The border between emiting and not emiting rows is dependant on total rows count (for example with totalRows === 1000000 row with index 524286 is still emiting event while row 524286 doesn't; for totalRows === 399458 only last row is not emiting event). Tested with partial row store, but it's behaving the same with full row store.
This problem can be reproduced on Chromium browsers (Chrome, Edge). On Firefox and Safari every row emits events correctly.

**Expected behavior**
Events are emited for every row.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/ZkHqflEjcziqqTmg

**Please tell us about your environment:**
Plunker

* **ag-Grid-Enterprise version:** 26.0.0 Angular

* **Browser:**  Chrome 93.0.4577.63, Edge 92.0.902.84, 

* **Language:** all

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
