### ISSUE TITLE
Additional undefined chart column for grouped rows

### ISSUE THREAD

**Issue by kaczor6418** [ag-grid/ag-grid#4677]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

## Problem description

I want to group my records by some characteristic(in this example, this will be `'make'`). I expected to see 3 chart columns (one for `Toyota`, `Ford` and `Honda`). 

On the beginning with `hide` field set to `true` I can see columns for every record + 3 columns which contains sum of each group. I think I should get only 3 columns, one for each group.  

After some time, I spot that if I remove `hide` field, then I am getting 3 columns each for one group. In this example, I am also getting one additional column which shows the sum of all my records, and I think this should not be here.

What's more, there is no issue if I use API for creating normal range chart instead of cross-filtering chart. In the below example, all the code is the same, the only one difference is that I am using `.createRangeChart` instead of `.createCrossFilterChart`. I think if the chart definition and grid definition is the same, the API for creating normal and cross chart should give an output with the same chart.
_**[Plunker - ag-grid good chart but without cross-filter](https://plnkr.co/edit/Ir0pxqztE3dvkm46?open=lib%2Fscript.js&preview)**_

## Reproducible Scenario

Under the following link, you can find an example with minimal code needed to reproduce this issue:
_**[Plunker - ag-grid undefined column bug](https://plnkr.co/edit/IzKgMdtStGvnbJKJ?open=lib%2Fscript.js)**_

## Current behavior
Chart with 12 columns, one for each record + additional 3 columns for each group sum

## Expected behavior
Chart with 3 columns, one for  `Toyota`, `Ford` and `Honda`. Chart should allow cross filtering. 

## Environment:
 - **OS**: Windows 10
 - **Web-Browser**: Microsoft Edge (Version 93.0.961.52 (Official build) (64-bit))
 - **server**: [http-server](https://www.npmjs.com/package/http-server)
 - **AG Grid version:** 26.0.1
 - **Browser:**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52
 - **Language:** [ES 6]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
