### ISSUE TITLE
disable export csv not work 

### ISSUE THREAD

**Issue by mahdiporkar** [ag-grid/ag-grid#4685]
Dear
I try suppressCsvExport = false in gridoptions but by this config export csv still enabled  on right click menu
Thanks

[https://plnkr.co/edit/MxlpuU1GXOnSG9rx](url)

**Comment by StephenCooper** [comment]
Try `suppressCsvExport=true`

**Comment by mahdiporkar** [comment]
oh sorry thanks

**Comment by StephenCooper** [comment]
No worries! 🙂
