### ISSUE TITLE
Multi filter(Text filter and Set Filter) on a column in Server-side row model with partial store is not working

### ISSUE THREAD

**Issue by Uvrocks93** [ag-grid/ag-grid#4688]
**Current behavior**
AG-Grid : I am using Server side model with partial store. I want to apply multi filter(Text filter and Set Filter) on a column by passing values to Set Column filter asynchronously. But it is not working.

**Error**: ag-Grid: Set Filter cannot initialise because you are using a row model that does not contain all rows in the browser. Either use a different filter type, or configure Set Filter such that you provide it with values

Please see this below Plnkr example. 
https://plnkr.co/edit/rt7pBAtrwMuz12eF

**Expected behavior**
Multi filter should work and values should be loaded for Set column filter.

**Please tell us about your environment:**

* **AG Grid version:** 24.0.0

* **Browser:**

* **Language:** [all | TypeScript 4.13 | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
