### ISSUE TITLE
Module not found: Error: Can't resolve 'react-dom/server' in 'C:\Users\***\node_modules\ag-grid-react\lib'

### ISSUE THREAD

**Issue by banesrdjevic** [ag-grid/ag-grid#4690]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Installing ag-grid-react throws a dependency error in newReactComponent.js and legacyReactComponent.js. Prevents our app from loading.

require("react-dom/server)" cannot be resolved. Replacing with require("react-dom") fixes the issue. However this gets overwritten during the npm install step of our pipeline deployment.

**Expected behavior**
Expected behavior is what happens when you replace require("react-dom/server") with require("react-dom"). This allows the dependency to be resolved. which allows for the grid to load and the Module not found error to not appear.

**Please tell us about your environment:**

Windows 10, VS Code, npm, npm start

* **AG Grid version:** X.X.X
   "@ag-grid-community/react": "~26.0.0",
    "@ag-grid-enterprise/all-modules": "~26.0.0",
    "react-dom": "17.0.2",

* **Browser:**
All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React with "typescript": "3.7.5"

**Comment by ibilichenko** [comment]
I am facing the same issue. It is related to the React version, but I cannot get it in an isolated environment.

@banesrdjevic how did you fix this?
