### ISSUE TITLE
Is there a way to disable horizontal scrolling when the column menu  is open? 

### ISSUE THREAD

**Issue by nanandn** [ag-grid/ag-grid#4708]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

* **AG Grid version:** X.X.X
"ag-grid-community": "26.0.0",

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36'

Is there a way to disable horizontal scrolling when the column menu  is open? Right now, when the menu is open, I can scroll the grid horizontally and the menu moves with the column. When there are pinned columns and the column for the menu is scrolled, the menu appears on top of the pinned column. 

![Screen Shot 2021-10-08 at 9 34 57 AM](https://user-images.githubusercontent.com/1680655/136592312-b8f53e5a-d4d3-4d08-85fd-14efa4119a25.png)

Thanks
Anand

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
