### ISSUE TITLE
[virtual model] have virtual scrolling 'not' load data as soon as the scroll is hit

### ISSUE THREAD

**Issue by ceolter** [ag-grid/ag-grid#472]
should be possible for virtual scrolling to not eager fetch unless the user scrolls a certain amount.
http://ag-grid.com/forum/showthread.php?tid=2880

**Comment by scotthovestadt** [comment]
+1 I really need this feature

**Comment by S-YOU** [comment]
debounce(setTimeout) looks good on performance side, but it also make grid blank while you scrolling though.

**Comment by scotthovestadt** [comment]
This is the trouble scenario:
* I have virtual scrolling enabled with a remote datasource
* I have 1,000,000 rows (this is my actual use-case)

The user takes the scroll handle and quickly scrolls down from the top to the middle. In this time, it will trigger the maximum number of AJAX requests to fetch data and the user will have to wait 30~ seconds to see any data.

**Comment by scotthovestadt** [comment]
Enabling the paint debounce somewhat fixes the issue, but I want the grid to paint, I just don't want it to wait a little bit to fetch data.

The other issue is that scroll velocity plays a part, too. If the user is very slowly scrolling I'd like to request data, but in the case I describe above I want it to wait until he's scrolling slow enough to see the data.

I'm planning to work on adding this feature to the grid this month.

**Comment by S-YOU** [comment]
you are right. with ajax request inside scroll event, definitely need debounce.

**Comment by S-YOU** [comment]
paint debounce you mean, requestAnimationFrame? it is somewhat slower than synchronous rendering on firefox when I experiment before.

**Comment by scotthovestadt** [comment]
Actually, I mean suppressScrollLag. It debounces painting the grid as you scroll.

http://www.ag-grid.com/javascript-grid-properties/index.php

**Comment by ceolter** [comment]
interesting use of 'suppresScrollLag'. wasn't my plan, but makes perfect sense here.

**Comment by TFrascaroli** [comment]
Sorry, jumping in here. Maybe you can benefit from this:
My pen showing its usage: http://codepen.io/tfrascaroli/pen/gaWrVb
Original work I derived mine from: http://stackoverflow.com/a/27842148/1420614 (but I changed it a lot actually) 
A few (completely unorthodox) tests show that both firefox and chrome give < 100 for "I'm reading every other line" speed. explorer goes crazy and its scroll is extremely fast, but we really should let IE die!
Anyway, if you're draggin the scrollbar and you actualy want to read al the rows (like you're searching for something), it doesn't go > 30. Give it a try!

**Comment by scotthovestadt** [comment]
@TFrascaroli Incredibly useful. I'm going to try and implement it using that as a base. Thank you!

**Comment by TFrascaroli** [comment]
Glad to help :smile:

**Comment by Pedrozena** [comment]
Hi, jumping in here too.
I don't get how you solved this issue. I'm almost in the same condition of @scotthovestadt except that I'm using websocket.
With this numbers (1M+ rows) a fast scrolling cause a lot of white rows displayed. 
I need somehow to debounce scrolling action in order to reduce scrolling frequency.
my problem is better described [here](http://stackoverflow.com/questions/35225835/how-to-load-raw-row-data-into-ag-grid). 
p.s. sorry for asking for help here but the ag-grid forum don't allow me to register with any mail address I give.

**Comment by ceolter** [comment]
@Pedrozena what problem do you get on the forum? what email are you trying to use? i have very few emails banned, just two which were used for posting spam.

**Comment by Pedrozena** [comment]
@ceolter mi nickname with a dot between o and z, followed by @gmail.com

**Comment by ceolter** [comment]
@Pedrozena i don't konw why that's a problem, it should be fine.

**Comment by Pedrozena** [comment]
Just tryed with another e-mail address and nothing changed. I can't get my activation code.

**Comment by Pedrozena** [comment]
I eventually received the activation code in spam folder (using @live.com).
With gmail the activation email is completely ignored, without passing through spam folder

**Comment by gnespolino** [comment]
I also think this is a key feature any grid with virtual paging need to implement.
Basically, in giant dataset, when user quickly scrolls the grid to reach the last row, it happens that all intermediate rows are loaded regardless of any settings.
I would like to reach this use-case:
- grid loads the first page and display it
- user scrolls the grid to reach the last rows
- the grid only loads the last page (depending on scroll speed, lag settings, debounce timeout and so on)

I tried implementing this inside my own getRows implementations, but it's not possible because I would simply need to debounce the scrolling event.
Infact since getRows gets invoked with different params each time (page, startrow etc.) I cannot debounce that inside getRows.

**Comment by ceolter** [comment]
the grid, if configured correctly, will not load every row.

if you ensure the following are set to reasonable values:
maxPagesInCache
maxConcurrentRequests

if maxPagesInCache = 2, and maxConcurrentRequests = 1, and paginationPageSize = 100, and 20 rows displayed in the grid, then if you start at position 0, then page 1 is loaded, then scroll to position 2000, page 2 is loaded, but when it comes back, the last two pages in cache to be loaded are 19 and 20, so pages 19 and 20 get loaded only, nothing in between, as the LRU will have ejected the intermediary pages from the cache before they had a chance to load.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-72

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by jayrungta** [comment]
@ceolter any plans to reopen this request? Doesn't look like its been addressed yet...
