### ISSUE TITLE
GetMainMenuItemsParams.defaultItems has type string[], but it's use-case requires object

### ISSUE THREAD

**Issue by Jlll1** [ag-grid/ag-grid#4740]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

1. Go to https://www.ag-grid.com/angular-data-grid/column-menu/
2. Preview ``app.component.ts`` code from the first example ``Example Column Menu``
3. Provided implementation of getMainMenuItems won't work in typescript, since you can't push ``object`` to a ``string[]``

**Current behavior**
defaultItems has type ``string[]``

**Expected behavior**
defaultItems should either be of type ``any``, or have some menuItem interface associated to it.
Or the documentation example should not use it like ``any[]``

* **Language:** [TypeScript]

**Comment by AhmedAGadir** [comment]
Hello !

Thank you for your email and for the context you’ve provided.

We looked into your scenario and built a sample to help you implement this behavior:

https://codesandbox.io/s/github/ag-grid/examples/tree/main/projects/t2t-5490?file=/src/app/app.component.ts

`case 'country':
        var countryMenuItems: (string | MenuItemDef)[] = [];
        var itemsToExclude = ['separator', 'pinSubMenu', 'valueAggSubMenu'];
        params.defaultItems.forEach(function (item: string | MenuItemDef) {
          if (itemsToExclude.indexOf(item as string) < 0) {
            countryMenuItems.push((item));
          }
        });
        return countryMenuItems;`

Please use the sample above.

I will now close this ticket.

Thanks
