### ISSUE TITLE
Jest and React Testing Library for React codebase

### ISSUE THREAD

**Issue by aymanapatel** [ag-grid/ag-grid#4741]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

* **AG Grid version:** `"ag-grid-community": "^25.2.1",`
* **React** ` : React with Hooks

We are trying to test `gridApi` and some editing events through Jest and RTL. We are unable to find `gridApi` and events (`CellEditingStoppedEvent`) to be exported from `ag-grid-react` package for spying.

Is there a way to test Aggrid React codebase without using enzyme?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
