### ISSUE TITLE
React grid editing changes state incorrectly when it shouldn't

### ISSUE THREAD

**Issue by AmrineA** [ag-grid/ag-grid#4742]
**I'm reopening because only one concerns was addressed in the response.**

Original issue: https://github.com/ag-grid/ag-grid/issues/4723

The additional concern not addressed: https://github.com/ag-grid/ag-grid/issues/4723#issuecomment-949548556

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
https://stackblitz.com/edit/ag-grid-react-hello-world-scmn1f?file=index.js

**Current behavior**
**With reactUi** It appears that it's not properly evaluating this function when it should and the onCellValueChanged function is essentially locked down based on what the state is when the grid is initially rendered.

**Without reactUi** It appears that the state object is being updated directly without me having called the state setter function.

**Expected behavior**
I would expect the `data` value to reflect the current state of what is in `data` and not the initialized value or the changed value. The grid should never update the data value directly, but only when I specifically tell state to be updated through the state setter functions.

**Please tell us about your environment:**
I'm running Windows, but you can see it happen in StackBlitz.

* **AG Grid version:** 26.1.0 and 26.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

* **Language:** React/JavaScript

**Comment by shuheb** [comment]
Hi @AmrineA 

We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG-5982 [React] When using reactUi=true and providing rowData via a state variable, editing a cell causes stale state and resets the rowData to empty

In the meantime, I would recommend setting reactUi=false and implement the workaround shown in #4723 

Thanks
