### ISSUE TITLE
When I click the refresh data button, the table appears blank first, and then the new data is rendered. How can I avoid this phenomenon?

### ISSUE THREAD

**Issue by wangtangsheng** [ag-grid/ag-grid#4744]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Framework: react

Example: https://plnkr.co/edit/ONnLsqILeHCV7fyX

**Current behavior**
Prerequisite: set the column property cellrendererframework.
```
field: colName,
cellRendererFramework: CellRender,
```
When I click the refresh data button, the table appears blank first, and then the new data is rendered. 

**Expected behavior**
The table does not appear blank and directly displays the latest data

**Please tell us about your environment:**
windows10

* **AG Grid version:** 26.1.0

* **Browser:**
all

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
