### ISSUE TITLE
Focus first cell on tab / do not focus headers when tabbing out of the first cell (Skip header focus completly)

### ISSUE THREAD

**Issue by alexanderfink** [ag-grid/ag-grid#4745]
**I'm submitting a ...**  
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When tabbing in the grid (ex. from an input) it is first focusing the table headers. Skipping this behavior is only possible when manually focusing the first cell on tab as described in this example on your website [Example: Tabbing into the Grid](https://www.ag-grid.com/angular-data-grid/keyboard-navigation/#example-tabbing-into-the-grid).

1. I do not want to add a keydown Listener to every input/element before a table
2. When tabbing out of the grid with `Shift + Tab` I will still be in the headers.

**Expected behavior**
__I want to completely skip headers / it should be possible to skip headers in tab navigation.__ Currently they have `tabindex="-1"` but it seems like the focus is managed manually by the grid. 

**What I have done so far**
I currently added the `tabToNextHeader` callback to the header. Unfortunately this is only called, when a header is already focused.  In conclusion this means, that I need to focus at least one header before archiving the expected behavior.  

* **AG Grid version:** 26.0.0

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by HeyItsJs** [comment]
Can we please reopen this issue? This is a valid issue which even I am facing.
