### ISSUE TITLE
For ag-grid-vue, any plan on updating vue-property-decorator to at least ^9.0.0?

### ISSUE THREAD

**Issue by tlyau62** [ag-grid/ag-grid#4747]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

As our team finds out several severe bugs on vue-property-decorator@8.5.1, It would be nice to upgrade vue-property-decorator to at least ^9.0.0 or make it not peerDependencies. Such that our application can be upgraded to version 9 or above 

Thank you.

![image](https://user-images.githubusercontent.com/24647774/139238214-8f6e2b21-93d2-4e1b-b278-75e11d0e57d8.png)

**Comment by seanlandsman** [comment]
@tlyau62 I'll take a look and this - see if it's something we can accept without causing downstream issues for other users

**Comment by seanlandsman** [comment]
Thanks for the suggestion and PR - I've merged into our development branch. This will be available in our next release (scheduled for the next couple of weeks)

**Comment by tlyau62** [comment]
Thanks for the support ❣️

**Comment by rjbgaspar** [comment]
Hi, 

I’ve just checked version 27.2.1 of ag-grid-vue and still no support for vue-property-decorator version ^9.0.0

Do you think it will possible to upgrade the peer dependency?

Thank you.

**Comment by seanlandsman** [comment]
@rjbgaspar I see that the PR covered @ag-grid-community/vue, but not ag-grid-vue and unfortunately I hadn't spotted this at the time

I've not updated the peer deps for ag-grid-vue and this will be released in the next 2/3 weeks

thanks
