### ISSUE TITLE
Narrator is announcing incorrect grouping for check boxes in expanded "column" pop up present on the column headers of the detail grid

### ISSUE THREAD

**Issue by shkaranam** [ag-grid/ag-grid#4751]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Providing a Reproducible Scenario
Plunker : https://plnkr.co/edit/j60jRKhMSh51A82s?preview
![image](https://user-images.githubusercontent.com/93401182/139484760-91a8f8d0-2fe0-4fb2-b822-37e7125e9732.png)

Current behavior
Narrator is not announcing the correct grouping for check boxes Header-1,Switch code, Number, Duration, Header-2 etc  present in detail grid child column options in Hamburger menu. Narrator is announcing "Header-1 as 1 of 12, Switch code as 2 of 12" which is incorrect.

Expected behavior
Narrator should announce Header-1 as 1 of 3 ,Switch code as 1 of 1, Number as 2 of 1 and so on.

Please tell us about your environment:
Operating System: Windows 10
IDE: Visual Studio Code
Screen Reader : Narrator, NVDA(2021.1)

AG Grid version:
24.1.0

Browser:
Chromium Edge Version: 92.0.902.78 (Official build) (64-bit)
Chrome Version: 88.0.4324.150 Official Build) (64-bit)

Language: [TypeScript 3.8.2]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you contacting us about this.

Just a note - you've said you're reporting this for v24.1 and the example you've used is from that version. However, the announcements you're reporting are emitted when using AG Grid 26.1. This is why I've used AG Grid 26.1 when testing. Please when submitting any bug reports use the latest version of AG Grid to avoid confusion.

I built a sample to test this with AG Grid 26.1:
https://plnkr.co/edit/KAngQ4byPnUlI4XY

I was able to confirm the behavior you described. Currently, the columns at a specific level are not considered their own separate list at this level. They are treated as a flat list of columns and all are included in the total count. This announcement is governed by these two ARIA labels:
aria-posinset
aria-setsize

Here's the WAI-ARIA standard specification for these labels:
https://www.w3.org/TR/wai-aria-1.1/#aria-posinset
https://www.w3.org/TR/wai-aria-1.1/#aria-setsize

As you can see, the WAI-ARIA specification there's no requirement to set these values according to the size and position inside each individual subgroup, which is your suggested behavior. 

There's a good reason for this - the current behavior in AG Grid where these two labels are set based on the size and position inside the entire set without taking levels into account allows the correct identification of columns in the entire set. This is important in cases where you have a column with the same name appearing in multiple groups at the same level as shown below (note columns B and C appear in both top level groups):

A (level 1)
|----B (level 2)
|----C (level 2)
D (level 1)
|----B (level 2)
|----C (level 2)

Using your suggested mode, both columns called 'B' would generate the same announcement "B, 1 of 2", which is confusing. This is why I believe the current behavior with the global indexing of columns produces a better user experience and avoids confusion.

I hope this helps.

Thank you once again for your time in bringing this up.

Best,
