### ISSUE TITLE
Showing normal columns with grouped columns

### ISSUE THREAD

**Issue by tqdo** [ag-grid/ag-grid#4753]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Plnkr: [https://plnkr.co/edit/KZVEZa4r0HjWlEi1](https://plnkr.co/edit/KZVEZa4r0HjWlEi1)

**Current behavior**
The ungrouped column headers appear on the 2nd row, the row of children of grouped columns

**Expected behavior**
The ungrouped columns should only has 1 cell which spans 2 rows (1 for main header and 1 for children)

**Please tell us about your environment:**
Mac OS

* **AG Grid version:** X.X.X
26.1.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as this is how it was designed to work

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
