### ISSUE TITLE
ag-grid localization - how to translate ag-grd header date filter using ngx-translate in Angular

### ISSUE THREAD

**Issue by mdufoud1214** [ag-grid/ag-grid#4754]
Am able to translate ag-grid in-built text by following documentation https://www.ag-grid.com/angular-data-grid/localisation/#creating-a-locale

But unable to translate date in the ag-grid header filter.  please find the below image

![image](https://user-images.githubusercontent.com/47215098/140038275-f46e079f-2724-4d31-a749-696d649d924c.png)

Able to translate cell date values. For translating this, I created cellEditorFramework and used date pipe set locale.
` cellEditorFramework: agCustomDateComponent`

**ag-custom-date-component.ts**
```
export class agCustomDateComponent implements OnInit {
   constructor( private dateAdapter: DateAdapter<Date>) {
    }

  ngOnInit() {
            this.dateAdapter.setLocale(this.params.context.translateService.currentLang);
    }
}
```

The issue is, I want to translate the ag-grid header filter date. How can I get this date?

Am using Angular 10,Typescript, ag-grid(22.0.0),ngx translate

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
