### ISSUE TITLE
agGrid.simpleHttpRequest() is not documented

### ISSUE THREAD

**Issue by pbb72** [ag-grid/ag-grid#4756]
Several examples in the ag-grid documentation (including two under Getting Started) use the `agGrid.simpleHttpRequest()` function:

- https://www.ag-grid.com/javascript-data-grid/getting-started/#fetch-remote-data
- https://www.ag-grid.com/javascript-data-grid/getting-started/#grouping
- https://www.ag-grid.com/javascript-data-grid/row-sorting/#example-custom-sorting
- https://www.ag-grid.com/javascript-data-grid/excel-export/#default-excel-export
- https://www.ag-grid.com/javascript-data-grid/aggregation/#example-1---built-in-functions
- etc...

However, there is no documentation for this function. I had to do a websearch to find out this function was not very well implemented: https://borngeek.com/2021/8/4/ag-grids-simplehttprequest/

**Comment by pbb72** [comment]
Interestingly enough, the documentation with that first example says "Notice that the actual data fetching is performed outside of the grid component - we are using the HTML5 fetch API", while the code is actually using the grid component to fetch data...

**Comment by makinggoodsoftware** [comment]
Hi,

There are several parts of our APIs that are not documented, which means that they are not intended to be reused but that we might use them internally

This is an example of such thing, it basically fetches data from an endpoint

**Comment by seanlandsman** [comment]
@pbb72 We'll be removing all references of this from our documentation in the next release - it's a legacy item was really only meant to demonstrate fetching data across all browsers, including IE11, hence a bespoke lightweight mechanism.

It was never intended to be used by end users.

thanks

**Comment by pbb72** [comment]
If this part of the API is not intended to be reused, then it should not appear in the documentation examples, especially not in the Getting Started section.

Note that the documentation text and example on the first link are in conflict, where the text refers the fetch API but the example uses simpleHttpRequest.
