### ISSUE TITLE
ag-grid-enterprise v26.1 Multi filter in Server-side model with partial store is not working

### ISSUE THREAD

**Issue by Tom-Ge** [ag-grid/ag-grid#4757]
**Current behavior**
I'm a customers of AG Grid. When I add “Multi filter” function to the grid ，I find that the function is not working . The detail issue just like below link. Is it the wrong way to use it? 

https://giters.com/ag-grid/ag-grid/issues/4688

* **AG Grid version:** v26.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Tom-Ge** [comment]
Please help,thanks!

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by Tom-Ge** [comment]
> HI,
> 
> This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.
> 
> You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/
> 
> If that is not the case, or you are having trouble, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) where they will be able to assist you with your access.
> 
> Thanks

Ok. Thanks!
