### ISSUE TITLE
Is there way to suppress all console messages in Ag grid library, Seeing lot of warnings while using AG grid.

### ISSUE THREAD

**Issue by SainadhSai** [ag-grid/ag-grid#4758]
![image](https://user-images.githubusercontent.com/84911617/140724282-48f2c125-5911-4877-8080-525df461ff98.png)

**Comment by makinggoodsoftware** [comment]
Hi,

We have flagged this as a good_suggestion

This means that this is a candidate to be in a future release.

At this moment we don’t have a ticket number for this that you can use to track in our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

But we should be updating this ticket with this information as soon as we process the good suggestions, as we do these in batches. Note also that at this stage we can’t guarantee that we will deliver this, but we will take it into consideration

Thanks for your feedback!

**Comment by kiril-matev** [comment]
Hello @SainadhSai !

Thank you for using AG Grid!

There's no way to suppress console warnings in AG Grid. These console warnings are important and are only displayed when absolutely necessary to warn you of the effects of API calls for the state that AG Grid is in at the time. 

In the case you've listed above, this console message is warning you that you are calling API methods after the AG Grid instance is destroyed. This highlights an issue in your code and also is there to help you avoid the resulting memory leak of keeping a reference to a destroyed instance of the grid.

As the console message recommends, please remove the API reference to the grid after destroying it.

Thanks for bringing this up!
