### ISSUE TITLE
Read-only ag-cells are not styled like disabled elements in material theme

### ISSUE THREAD

**Issue by mbwgh** [ag-grid/ag-grid#4759]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The `ag-grid-material` theme is [described](https://www.ag-grid.com/angular-data-grid/themes-provided/) as *"A theme designed according to the Google Material Language Specs."*.

These [specs](https://material.io/design/interaction/states.html#disabled) indicate however: *"A disabled state communicates when a component or element isn’t interactive, and should be deemphasized in a UI. Disabled states are displayed at 38% opacity of the enabled state."*.

Thus I believe that ag-cells that have `editable: false` applied to them, should be greyed out accordingly.

**Current behavior**

Editable cells look the same as non-editable cells.

**Expected behavior**

Non-editable cells should appear at 38% opacity, like the Google Material Language Specs say.

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request 

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
