### ISSUE TITLE
No way to specify desired "max-width" of Columns while exporting excel

### ISSUE THREAD

**Issue by hvsharma** [ag-grid/ag-grid#4763]
Hi,

My use case is this:

1) Auto-size the column width according to the column contents.
2) Provide a max-width parameter with Autosize.

I didn't find any way to do it for now. 

**Example:** 

A table has short-short cell contents (1-40 characters). But then there is a particular column for which the contents are like 100 characters+.

**Desired Functionality:**

I pass a max-width parameter:

"excelExportParams.maxColumnWidth=50" 

With this, all the small columns are auto-sized, but for the large columns, the width will not exceed 50 in the excel sheet.

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
