### ISSUE TITLE
How to get which column dragged in dragStopped event?

### ISSUE THREAD

**Issue by udhayaas97** [ag-grid/ag-grid#4764]
**I'm submitting a ...**  support request

```
<ag-grid-angular
  [rowData]="rowData"
  [columnDefs]="columnDefs"
  [defaultColDef]="defaultColDef"
  (dragStopped)="onDragStopped($event)"
>
</ag-grid-angular>

onDragStopped(value:dragStoppedEvent) {
     // Want to know which column is draged
}

```

**Expected behavior**

- dragStopped event should emit the value, which was dragged. As of now is giving only HTML elements as the target. But I couldn't read the target from typescript

**AG Grid version:** 23.2.1

**Browser:** Chrome

**Language:**  TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by MudulOzan** [comment]
I am also curious how to achieve this?
