### ISSUE TITLE
Tooltip component showing  when is empty array

### ISSUE THREAD

**Issue by weilinzung** [ag-grid/ag-grid#4769]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
 
```

**Current behavior**

**According to the doc:**

> The first three rows have athlete values of undefined, null and '' (empty string).

However, is not working properly if the data is an empty array 

```
data: {
  athlete: []
}
```

**Expected behavior:**

It should not be showing if any data is falsy or empty. 

**Browser: Chrome**

**Language: TypeScript**

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
