### ISSUE TITLE
Tooltip component click to show or hide

### ISSUE THREAD

**Issue by weilinzung** [ag-grid/ag-grid#4770]
**I'm submitting a ...**  (check one with "x")
```

[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
Only hover to show tooltip compoent

**Expected behavior**

- Add an option to be able to click to show the tooltip.
- Only show one tooltip at once, the previous one should be auto close.
- Or click anywhere outside of the target tooltip cell, then hide the previous tooltip.

 
**Please tell us about your environment:**
npm

* **AG Grid version:** X.X.X
26.1.0

* **Browser:**
*  Chrome

* **Language:**  
* TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by lillyqian** [comment]
@makinggoodsoftware: Is this feature already implemented? if so how to use it?

**Comment by Vatsov** [comment]
> @makinggoodsoftware: Is this feature already implemented? if so how to use it?

Try with:

```
const gridOptions = {
    tooltipInteraction: true,

    // other grid options ...
}
```
