### ISSUE TITLE
Angular Grid - table not rendering without width/height styles

### ISSUE THREAD

**Issue by HenonoaH** [ag-grid/ag-grid#4773]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
 I have made the demo code in [Stackblitz](https://stackblitz.com/edit/angular-ivy-sm7ke6)

**Current behavior**
Currently, the table is rendered only when providing width and height styles by custom. This makes the user experience a bit odd.

**Expected behavior**
It could be great if the table is rendered responsively by the number of rows and columns regardless of any custom CSS 

**Please tell us about your environment:**
Operating system: Mac
IDE: VS code
Package manager: Yarn/NPM

* **AG Grid version:** 26.1.0

* **Browser:** Chrome

* **Language:** TypeScript 4.0.2

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi,  

As per the documentation, this is standard and expected behaviour. If you would like to make it so a height or width aren't required you could try setting the domLayout to `autoHeight` as shown in the example below: 

https://stackblitz.com/edit/angular-ivy-k8ykca?file=src/app/app.component.html 

I hope this helps,
