### ISSUE TITLE
Ability to change how quickfilter matches

### ISSUE THREAD

**Issue by edokan** [ag-grid/ag-grid#4774]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'
```

**Current behavior**
Currently, the quick filter works by using `string.indexOf` to filter.

**Expected behavior**
I want to be able to use some other matching engine like [fuzzysort](https://www.npmjs.com/package/fuzzysort) to filter.

**Please tell us about your environment:**
Windows
WebStorm 2021.2.3
npm

* **AG Grid version:** 25.3.0

* **Browser:**
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4700.0 Safari/537.36

* **Language:** all

**Comment by StephenCooper** [comment]
If you set up an [external filter](https://ag-grid.com/javascript-data-grid/filter-external/), you should be able to use the fuzzysort package yourself to determine if a row matches or not.

**Comment by StephenCooper** [comment]
Here is a plunkr showing filtering via fuzzysort. Have also added a column that displays the match score for each row which helps show how the filtering works based off the score. Works quite nicely :)

https://plnkr.co/edit/PBD0sLlemYp8XJEs
