### ISSUE TITLE
Typing package

### ISSUE THREAD

**Issue by rootux** [ag-grid/ag-grid#4775]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I'm looking for an external typing package.
I'm wrapping ag-grid in our own component library.
And then when I use it in an external project - I don't want to import ag-grid but instead only the typing.
Is that possible?
Do you have a typing-only package?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
