### ISSUE TITLE
Vue 3 - Clarification on need for vue-class-component as peer dependency

### ISSUE THREAD

**Issue by wtykirby** [ag-grid/ag-grid#4776]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

In the README for the `ag-grid-vue3` package it specifies that you must install `vue-class-component@next` as a dependency. I was wondering if you could clarify why this package needs to be installed as a peer dependency even though the majority of Vue 3 project s will not be using the `@Component` decorator with class based components. Could this not be made a direct dependency of the `ag-grid-vue3` package instead?

On another note it appears that this package is no longer being actively maintained and the latest release that will be installed is `8.0.0.rc-1` which is a release candidate that was published a year ago and never resulted in a full release.
Also, see this comment which states that `vue-class-component` is no longer a recommended option for Vue 3: https://github.com/vuejs/vue-next/issues/4744#issuecomment-937369062

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by seanlandsman** [comment]
@wtykirby I've removed this dependency from our vue3 component - it'll no longer be required in the next release (27.x)

thanks

**Comment by wtykirby** [comment]
@seanlandsman thanks! Much appreciated
