### ISSUE TITLE
ColumnController is missed from '@ag-grid-community/core'

### ISSUE THREAD

**Issue by Lertis** [ag-grid/ag-grid#4782]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

My code:
`import { ..., ColumnController, ... } from "@ag-grid-community/core";`

and in *.ts code 
`const myFunc = {
     columnsMatch: (<any>ColumnController).prototype.columnsMatch,
     ...
}`

OS: Windows 10, Browser: Google Chrome, IDE: VS Code.

Current behaviour
ag-Grid v.25.3.0 + Angular 12 (Typescript v4.2.4)  - works fine

Expected behavior. If possible back this up with our docs/examples if possible
ag-Grid v.26.2.0 +Angular 12 (Typescript v4.2.4) - throw an error that ColumnController couldn't be found from '@ag-grid-community/core'.

Where it could be found or to what should be replaced?

**Comment by tronixcoder** [comment]
columnModel has same methods. But it will be good of this can be clearly mentioned in change log

**Comment by Lertis** [comment]
@tronixcoder did you find any info about that? Also have the same troubles?

**Comment by makinggoodsoftware** [comment]
Hi guys,

Do you think you could add a repro to this thread so that we could have a look?

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by shilpa85** [comment]
I used columnModel. That worked for me.
