### ISSUE TITLE
'Apply' button does not work when set filter mini filter is populated

### ISSUE THREAD

**Issue by chxu-br** [ag-grid/ag-grid#4785]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When using a set filter with an 'apply' button configured, if the user populates the mini filter inside the filter and clicks 'apply', the column is not filtered (ie. nothing happens). The expected behavior is only triggered by pressing the enter key.

https://plnkr.co/edit/4DAJ8sgN0eX8hz8S?preview
To reproduce, go to the above plunkr and type anything into the mini filter (ie. 'J'), then try filtering the column by clicking 'Apply.'

**Expected behavior**

The user should be able to filter the column by clicking the apply button.

**Please tell us about your environment:**

IntelliJ

* **AG Grid version:** 26.2.0

* **Browser:**

Chrome

* **Language:** [**all** | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

The set filter behavior you described isn't a bug - it's standard behavior for the default column filtering mode.

You can get the specific filtering behavior you described by activating excelMode='windows'. You can do this by setting excelMode='windows' in the filterParams, as shown in the sample below:
1. Open
https://plnkr.co/edit/iZQa3eeJu807zlj3
2. Open floating filter
3. Type 'jj' in the search box
4. Click APPLY button

**Actual & Expected**: Grid records are filtered

Please learn about column filtering with Excel mode and how this is different from the default column filtering behavior here:
https://www.ag-grid.com/javascript-data-grid/filter-set-excel-mode/#enabling-excel-mode

Also, as you're using AG Grid Enterprise functionality (set filter), please use your license to sign up for an account on our support system and submit support tickets there.

Thank you for using AG Grid!

**Comment by chxu-br** [comment]
That works perfectly, thanks so much!

**Comment by chxu-br** [comment]
Just a suggestion, but it would be extremely helpful to mention in the documentation that the 'Apply' button doesn't work with a set filter unless excelMode is set to 'windows.' This might prevent future confusion, as the case without excelMode configured is still bug-like.

**Comment by kiril-matev** [comment]
Hi @chxu-br,

Thanks for your response.

Just to clarify - the Apply button works fine with a set filter in all filtering modes - whether or not excelMode is set or not. 

This behavior is documented in the 4th row (**Apply the filter when the Apply button is clicked**) in the filter modes comparison table:
https://www.ag-grid.com/javascript-data-grid/filter-set-excel-mode/#differences-between-modes

Please verify this here:
1. Open
https://plnkr.co/edit/hmHrNyHtOq7puqCx
2. In the filter panel on the right, expand the default item
3. Un-check Antelope, Elephant, Giraffe
4. Click the APPLY button below
**Actual & Expected**: Grid is filtered and records Antelope, Elephant, Giraffe are no longer displayed

I hope this helps clarify the filtering behavior.

Thanks for your time in bringing this up!

**Comment by chxu-br** [comment]
Sorry, should have specified - the Apply button doesn't work with a set filter **when the mini-filter is populated** and excelMode is not set. You can verify this through the plnkr link in my original comment.

**Comment by kiril-matev** [comment]
Hi @chxu-br 

This is expected behavior because the APPLY button applies the selection in the set filter list depending on which items are checked.

What's important here is that in the default set filter mode, typing in the mini-filter filters the list of items displayed below but doesn't de-select the items that are not matching the filter. In other words, typing in the mini-filter doesn't change the selected items in the list below, it only filters them. This is why typing in the mini-filter and clicking the APPLY button doesn't filter the grid. 

If you want to type in the mini-filter and click the APPLY button to filter on the currently filtered items in the list, please set excelMode=windows, as I showed above.

In the default filter mode, if you've typed in the mini-filter and want to apply the filter immediately, you can press the ENTER key.

You can test this mini-filter behavior when you type in the top-most (Default) filter in the sample here:
https://plnkr.co/edit/hmHrNyHtOq7puqCx

Please carefully review the comparison table of the filtering modes here:
https://www.ag-grid.com/javascript-data-grid/filter-set-excel-mode/#differences-between-modes

This will help you understand how each of the modes work and you'll be able to choose the best one for you.
