### ISSUE TITLE
[BUG] Row height calculation error

### ISSUE THREAD

**Issue by kszmetena** [ag-grid/ag-grid#4787]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
If you have configured an autoHeight column, the rowHeight of node always be equal with the max of auto cols height, even if it less than default row height, so a row can be unreadable.

[EDIT]
api.resetRowHeights() api call also will break the a row height, it wont check the height of autoHeight cols.
[Plunker](https://plnkr.co/edit/czuPbvCrZg0MG4FZ)

**Reproduction**
https://plnkr.co/edit/gAT7y0XKb4azjNal

**Expected behavior**

The height of row shouldn't be less than the default height or height of non auto cols.
In prevoius major version auto height was minimized: [src](https://github.com/ag-grid/ag-grid/blob/056bc538a05b24ded95700b72464f134fd05f196/community-modules/core/src/ts/gridOptionsWrapper.ts#L1761)

* **AG Grid version:** 26.X.X

* **Browser:** -

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kszmetena** [comment]
Issue updated

**Comment by kszmetena** [comment]
Hi,
I have created a more specific scenario, this is what we use in our application.
[Plunker](https://plnkr.co/edit/dFmClNHQslK1XJVj)

We have an autoHeight column, the value of it can be a multi-line or empty text. The user can choose how many lines would like to see in this cell. I use [webkit-line-clamp](https://css-tricks.com/almanac/properties/l/line-clamp/) css feature to achive this feature.

_Ag-Grid 25.x.x_
In Ag-Grid previous version, this has been worked properly. In this version the row size of an autoHeight column could not be less than the default or provided rowHeight. [(src)](https://github.com/ag-grid/ag-grid/blob/056bc538a05b24ded95700b72464f134fd05f196/community-modules/core/src/ts/gridOptionsWrapper.ts#L1761) When the user changed the "max-line", I had to call gridApi.resetRowHeights to notify the grid about the new size, after that every row had the perfect size.

_Ag-Grid 26.x.x_
In recent version, the row size of an autoHeight column could be less than the default or provided rowHeight. (In our case if the value is empty.) The "max-line" changes working properly because of the recently used ResizeObserver, so I don't have to call gridApi.resetRowHeights after these changes. 
I though that, I have a rendering or timing issue because of the too small rows, so I try to fix this with gridApi.resetRowHeights call. After that, the too small row was fixed, but size of others, which has a non empty value in autoHeght column, is broken.

All-In-All I have two issues with the recent version:
- row height could be less than the default/provided value, when we use autoHeight column
- resetRowHeights api call doesn't take into account the height of an autoHeight column

Thanks,
Kristof

**Comment by AhmedAGadir** [comment]
Hi,

This issue has been fixed for next release:

AG-6143 [Regression] When a column has autoHeight: true and rendering a null/undefined/empty cell value, the default cell renderer has no height and cannot be clicked

You can see it working here:
https://plnkr.co/edit/lGPLsdVyuqK4s0kR?preview

Here is a link to our pipeline where you can follow updates:

https://www.ag-grid.com/ag-grid-pipeline/

I will now close this ticket.

Regards

ag-grid Support
