### ISSUE TITLE
Not able to specify columnHoverHighlight on the column level.

### ISSUE THREAD

**Issue by gberes01** [ag-grid/ag-grid#4788]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Version 26.2.0

I need to specify columnHoverHighlight property for just a set of columns in my grid, not all of them. Unfortunately, it's not possible to define this on the column level.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
