### ISSUE TITLE
Endless timeout call loops on autoHeight columns table

### ISSUE THREAD

**Issue by yosefclinch** [ag-grid/ag-grid#4790]
**I'm submitting a bug report**

**Reproducible Scenario**
1. set `autoHeight:true` to table column
2. render the table

**Current behavior**
The function `measureheights` at `community-modules/core/src/ts/rendering/cell/cellCtrl.ts` keep repeating forever and take browser sources

**Expected behavior**
The function above suppose to run up to 5 times, then rest.

**Fix suggestion**
https://github.com/ag-grid/ag-grid/pull/4789

**Environment:**
OP: windows
IDE: PHPStorm
Package Manager: yarn

* **AG Grid version:** 26.1.0-26.2.0

* **Browser:**
e.g. Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
