### ISSUE TITLE
Display custom message when after filtering nothing found

### ISSUE THREAD

**Issue by bmarvinb** [ag-grid/ag-grid#4791]
Hi, I'm looking for a solution, if user typed something in the filter, and then nothing is found, how to display this to the user? Also I have a paid subscription for ag-grid enterprise maybe it's important

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
