### ISSUE TITLE
Scrolling past 2^24px breaks scrolling and interaction

### ISSUE THREAD

**Issue by phlmn** [ag-grid/ag-grid#4793]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

* go to the massive row count example (https://www.ag-grid.com/react-data-grid/massive-row-count/)
* scroll down to 16777216px (with Dev-Tools select `.ag-body-viewport` and run `$0.scrollTop=16777216`)
* try to scroll
* try to click a row

**Current behavior**

* on a large table scrolling past 2^24px (16,777,216px) breaks functionality
* it is not possible to select rows anymore
* hover effect is not working anymore
* scrolling starts to "stick" (on a Macbook every ~3rd scroll attempt is working)

**Expected behavior**

* interaction works like further up the table

**Please tell us about your environment:**

* macOS Big Sur 11.6
* 32 GB RAM
* Google Chrome 96.0.4664.55

* **AG Grid version:** 26.1.0

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

**Comment by makinggoodsoftware** [comment]
Hi,

Would you mind providing a use case where this would become an issue?

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by phlmn** [comment]
@makinggoodsoftware It's sad that this gets closed even when it is reproducible in the examples...

**Comment by phlmn** [comment]
Maybe this wasn't clear: This does break when scrolling to **any** position larger than 2^24px. So this can also be reproduced by just dragging the scroll bar way down in the example.

**Comment by gportela85** [comment]
@phlmn This looks like a Chrome BUG, not Ag Grid's. I'll file a bug report with Chromium as Firefox and Safari work fine.

Thanks for reporting

**Comment by gportela85** [comment]
hi @phlmn 
here is the Chromium ticket if you want to follow it: https://bugs.chromium.org/p/chromium/issues/detail?id=1282946#c5

Would also help if you and people from your organization "starred" the ticket.
