### ISSUE TITLE
Cell Editors - exceeding the boundaries of the grid

### ISSUE THREAD

**Issue by BahKoo** [ag-grid/ag-grid#4797]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Using the standard popup cell editors, the popups cannot exceed the boundaries of the grid. This is a limitation for grids with limited height. In this reproduction, the left column is using a standard cell editor and the right column is using a custom cell editor:
https://plnkr.co/edit/HvnhDuPOB52kND0G

The only way I can get a cell editor to exceed the boundaries of the grid is by doing the following:
 - set the grid property `[suppressRowTransform]="true"`
 - override the ag-grid CSS with `.ag-center-cols-clipper { transform: unset }`
 - use a custom cell editor with fixed positioning popups

It seems risky to be overriding the `.ag-center-cols-clipper` transform style. Is there a recommended way to achieve editors that exceed the grid boundaries?

**Expected behavior**
 - 

* **Please tell us about your environment:** Windows 10

* **AG Grid version:** 26.2.0

* **Browsers:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

* **Language:** all

**Comment by gportela85** [comment]
To solve this use the `popupParent` config - https://plnkr.co/edit/3vsqohPkpbVKjB7K
