### ISSUE TITLE
AgGrid React issue with reactUi true

### ISSUE THREAD

**Issue by nkabir1986** [ag-grid/ag-grid#4803]
when set **reactUI={true} and enableRtl={true}** throw blow exception but when enableRtl={false} work good.

**TypeError: Cannot read properties of undefined (reading 'getCenterViewportScrollLeft')**

GridBodyScrollFeature.horizontallyScrollHeaderCenterAndFloatingCenter
D:/Projects/Current Projects/charity-pwa/node_modules/ag-grid-community/dist/ag-grid-community.cjs.js:29727

 29724 | };
  29725 | GridBodyScrollFeature.prototype.horizontallyScrollHeaderCenterAndFloatingCenter = function (scrollLeft) {
  29726 |     if (scrollLeft === undefined) {
> 29727 |         scrollLeft = this.centerRowContainerCon.getCenterViewportScrollLeft();
        | ^  29728 |     }
  29729 |     var offset = this.enableRtl ? scrollLeft : -scrollLeft;
  29730 |     var topCenterContainer = this.ctrlsService.getTopCenterRowContainerCtrl();

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
