### ISSUE TITLE
CellRenderParams parameters set through api are undefined

### ISSUE THREAD

**Issue by gianlop3z** [ag-grid/ag-grid#4807]
I'm using the following component to render inside the cells of a column called "status". The component HTML is a simple [Bootstrap switch](https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches).
```
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from 'ag-grid-angular';

@Component({
  selector: 'app-status-switcher',
  templateUrl: './status-switcher.component.html',
  styleUrls: ['./status-switcher.component.scss']
})
export class StatusSwitcherComponent implements ICellRendererAngularComp {

  private params!: any;

  agInit(params: any): void {
    this.params = params;
  }

  // this function get executed on switch change event
  switchHandler(): void {
    this.params.onSwitch(this.params.data); // here is the error
  }

  refresh(): boolean {
    return true;
  }

}
```

In other file, where i define the colDefs for AG GRID table, as you can see I'm adding the **cellRendererFramework** configuration.
```
import { ColDef } from 'ag-grid-community';
import { StatusSwitcherComponent } from '../../components/status-switcher/status-switcher.component';

export const colDefs: ColDef[] = [
  {
    headerName: '#',
    initialWidth: 75,
    resizable: true,
    valueGetter: (param) => <number>param.node?.rowIndex + 1,
    cellClass: 'id',
  },
  { headerName: 'Nombre', field: 'name' },
  { headerName: 'Rol', field: 'role' },
  { headerName: 'Correo', field: 'email' },
  {
    headerName: 'Estado',
    field: 'status',
    cellRendererFramework: StatusSwitcherComponent, // here is the component
    suppressMovable: true,
  },
];
```
Then, in the component where is the table, i listen for the grid to be ready and set the **cellRendererParams** column property.
```
import { Component, OnInit } from '@angular/core';
import { GridReadyEvent } from 'ag-grid-community';
import { colDefs } from './roles.column-def';

@Component({
  selector: 'app-roles',
  templateUrl: './roles.component.html',
  styleUrls: ['./roles.component.scss']
})
export class RolesComponent implements OnInit {

  colDefs = colDefs;
  data = [] // this array contains some data

  constructor() {}

  ngOnInit(): void {}

  onGridReady(e: GridReadyEvent): void {
    let col = e.api.getColumnDef('status');
    if (col) {
      col.cellRendererParams = {
        onSwitch: console.log
      };
    }
  }

}
```
Then in the app, when i toggle the switch, the following error is raised:

![5](https://user-images.githubusercontent.com/63388127/143658625-355543a3-91f6-469b-97d7-89682cccd191.PNG)

That's really weird because i have another component that uses a different component as a cellRendererFramework too and that one is working perfectly, i debugged the **params** object getting the following output:

![7](https://user-images.githubusercontent.com/63388127/143658805-d5a25865-c095-40da-a854-0298adff7c02.PNG)

Inside the output, i realize is a key called **colDef** and that one contains the params  (including the onSwitch function), that's crazy.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
