### ISSUE TITLE
cellStyle: { backgroundColor: '#98fb98' } ... header definitions override rowSelection colors

### ISSUE THREAD

**Issue by kodecharlie** [ag-grid/ag-grid#4809]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Current behaviour:  rowSelection colors do not surface, whether or not styles for rowSelection are explicitly declared or not.
Expected behaviour:  rowSelection colors should surface if gridOptions has specified support for rowSelections.  In my case, rowSelection colors do not surface at all.

**Current behavior**
When I configure `columnDefs` with custom background colors, we lose rowSelection colors.  I explain my setup below.

Versions:
```
ag-grid-community:  26.1.0
ag-grid-vue3:  26.1.2
Chrome:  95.0.4638.69 (Official Build) (x86_64)
vueJS:  3.0.0
```

ag-grid-vue:
```
  <ag-grid-vue
    class="ag-theme-alpine"
    :frameworkComponents="frameworkComponents"
    :columnDefs="columnDefs"
    :rowData="getRowData"
    rowSelection="multiple"
    domLayout="autoHeight"
    editType="fullRow"
    suppressRowClickSelection="false"
    @grid-ready="onGridReady">
  </ag-grid-vue>
```
columnDefs:
```
  { headerName: "Sample ID", field: "sampleId", sortable: true, editable: () => isEditable(),
    cellStyle: () => getPageStatus(), flex: 1, resizable: true },
  ...
  { headerName: "Pending", field: "pending", sortable: true, editable: true,
    cellStyle: () => getPageStatus(), cellRenderer: 'checkboxRenderer', flex: 1,
    valueGetter: params => params ? null : null },
```
frameworkComponents:
```
{
  checkboxRenderer: CheckboxRenderer
}
```
Functions:
```
  const getPageStatus = () => {
    if (this.status == this.myStatus.APPROVED) {
      return { backgroundColor: '#98fb98' };
    } else if ( ... ) {
      return { backgroundColor: '#a1caf1' };
    }
    return { backgroundColor: '#fffe71' };
  }
  const isEditable = () => {
    return this.status == this.myStatus.NOT_APPROVED;
  }
```
As well, I set up styles to override ag-grid defaults for rowSelelection:
```
.ag-theme-alpine .ag-row-selected {
  background-color: #4abbff;
}
```
But this style has no affect.

**Expected behavior**
I suspect your rendering cycle for grid cells is such that custom backgrounds (Eg, as specified in `cellStyle`) override whatever default color scheme is in place for rowSelections.  I personally don't believe this is right.  Rather, rowSelection should trump custom cell colors because rowSelection says something more global about the state of the grid; that is, I advocate for this priority scheme for coloring rows:

- an unselected row that does not contain the cursor (ie, no mouse-hover) should should cellStyle, or if that's not specified, then whatever default is in place for cell background color.
- an unselected row that does contain the cursor (ie, has mouse-hover) should show the hover-color (presently this works).
- a selected row that does not contain the cursor should show the rowSelection color, and any custom cellStyle should be aborted.
- a selected row that does contain the cursor should show the hover color (my guess is that this works, but I can't tell for certain).

I have not worked through are the selection-scenarios, but I think you probably get the idea, and it hopefully transposes well to those scenarios, too.

**Please tell us about your environment:**
See above `Versions`.

* **AG Grid version:** 
See above `Versions`.

* **Browser:**
See above `Versions`.

* **Language:**
See above `Versions`.  I'm coding in vueJS 3.0.0.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
