### ISSUE TITLE
Vue3 - Reactivity Not Working with rowData array

### ISSUE THREAD

**Issue by sama12386** [ag-grid/ag-grid#4814]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I have a simple array (defined in setup() of my component)
```
const arrayTest = [{title: "33"}, {title: "xx"}]
```
that I pass into rowData

```
<ag-grid-vue style="width: 100%; height: 500px;"
                 class="ag-theme-alpine"
                 :columnDefs="columnDefs"
                 :rowData="arrayTest"
                 @grid-ready="onGridReady">
</ag-grid-vue>
```
When I modify the title property of an array element the first time, the grid UI updates accordingly. Upon subsequent modifications, the grid does not update. I have tried using ref() with arrayTest, but to no avail. Am I missing something, or is this unexpected behavior?

* **AG Grid version:** 26.2.0
* **Vue version:** 3.1.5
* **Language:** TypeScript 4.1.5
* **Platform:** Electron 13.0.0

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

Have a look at this documentation here, this should explain how to update the data for your use case

https://www.ag-grid.com/vue-data-grid/immutable-data/ 

Hope this helps

**Comment by japentaca** [comment]
I have the same problem with almost same version of Vue and Ag-grid

AG-grid  updates cell content just once. 
Any further changes to data array are not reflected

**Comment by TheAustinG** [comment]
I'm having the same issue as well.

Vue: 3.2.33
ag-grid-vue3: 27.0.0
ag-grid-community: 27.0.1

When I use the Vue DevTools to inspect the grid, I can see that my new data has been added to 'rowData' but the grid itself does not update/refresh to show the new row. 

This seemed to start happening all of a sudden and I'm sure there is some code elsewhere that is causing this, but I wanted to comment here since it's the same situation.

**Comment by playinglife** [comment]
Hi,
I'm having the exact same issue as TheAustinG.
