### ISSUE TITLE
Multi rows select with shift and arrow keys- AG Grid React

### ISSUE THREAD

**Issue by chethan2patil** [ag-grid/ag-grid#4815]
I'm submitting a issue for multi rows select with shift and arrow keys- AG Grid React

[] bug report => When we select multiple keys at a time ex: Shift with Arrow keys

Customers of AG Grid
Yes we are a Customer of AG GRID Enterprise
CompanyName=Huron Consulting Group Inc 

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

Current behavior

when we select just arrow keys selection is working fine but multiple selection is not working 
https://stackoverflow.com/questions/64550952/navigate-select-ag-grid-table-row-with-arrow-keys 
Expected behavior

my Scenario need to select with Shift+up/down arrow keys. How would I make this work
Please tell us about your environment
React, Visual Studio
AG Grid version:
 "version": "25.3.0",
 
Browser: Chrome

React ES6

**Comment by chethan2patil** [comment]
@ceolter - could you please help out

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
