### ISSUE TITLE
AgGrid React issue with reactUi true Version 26.2.0

### ISSUE THREAD

**Issue by adul-mo** [ag-grid/ag-grid#4817]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at AgGridReactUi

When add custom **frameworkComponents**

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
