### ISSUE TITLE
Context menu should not auto close when have real-time update in ag-grid 25, 26

### ISSUE THREAD

**Issue by 13120608736** [ag-grid/ag-grid#4819]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
My team build a real-time update application and new data need to display on the top of grid,  recently we update ag-grid from 23.2.1 to 25.2.0, when there is a real-time update(new data), then the context menu will auto close. ifreal-time update are very frequent, user can't use context menu at all.

**Current behavior**
when there is a real-time update(new data), then the context menu will auto close. if real-time update are very frequent, user can't use context menu at all

**Expected behavior**
when real-time update(new data), context menu should not auto close; context menu position should not auto changed and the context menu params should not changed

**Please tell us about your environment:**

* **AG Grid version:** 25.2.0

* **Browser:** 96.0.4664.45

* **Angular:** 10.2.5

* **Language:** 4.0.8

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
