### ISSUE TITLE
使用 react-activation/babel, ag-grid ，在控制台中显示警告信息

### ISSUE THREAD

**Issue by 763139102** [ag-grid/ag-grid#4825]
"ag-grid-community": "^25.1.0",
  "ag-grid-react": "^25.1.0",

![1639367836982](https://user-images.githubusercontent.com/25519902/145750652-1ad10b51-737b-468f-8465-0666a468f2a1.jpg)
![ag-err](https://user-images.githubusercontent.com/25519902/145750655-94690ffb-34dd-4626-b2f0-325f483ef3c0.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
