### ISSUE TITLE
multi users updating same row

### ISSUE THREAD

**Issue by pedrocr83** [ag-grid/ag-grid#4826]
I'm submitting a  support request.

Current behaviour:

Multiple users are using the same table and (without refreshing the table) updating the same rows. This means that the changes/add-ins made by the user submitting them first will be lost.

Any way to prevent this behaviour without having users refreshing the page (in the Community or Paid versions)?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
