### ISSUE TITLE
unable to use refreshServerSideStore with serverSideStoreType = "partial".

### ISSUE THREAD

**Issue by hassnkhalid** [ag-grid/ag-grid#4827]
**I'm submitting a support request**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**
I update a value in a cell which save it in database and the get the data again from server and after I reload data in the grid using refreshServerSideStore with below params
gridOptions.api.refreshServerSideStore({
        purge: false,
        route: null,
        });
as I am sending purge false, it still destroys all the children and state of open row group is lost.

my current grid options are as below
    this.gridOptions.rowModelType = "serverSide";
    this.gridOptions.rowSelection = "single";
    this.serverSideStoreType = "partial";

i know its mentioned in the documents that it only works with serverSideStoreType = "full" but that's not an option for me as the amount of data is huge.

**Expected behavior**
since the purge option is false i want to keep the state of row grouping and update the grid data with the new data from server seamlessly. but currently the only available option is to use this.serverSideStoreType = "full"; and thats not an option for me. can i achieve the same in any other way.

i was following [This Thread](https://github.com/ag-grid/ag-grid/issues/2750) which is three years old and was closed without giving any solution.

any help would be greatly appreciated.

* **AG Grid version:**
"ag-grid-angular": "^25.3.0"

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
