### ISSUE TITLE
How To Add A Unique Custom HTML Header

### ISSUE THREAD

**Issue by HVinceH** [ag-grid/ag-grid#4828]
**I'm submitting a support request**  
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

I'm trying to set the headerName of a column header as HTML in AG-Grid but the HTML is being escaped and a string is being set instead.

I'm aware that you can add a template under headerComponentParams in defaultColDef, however, this would be applied as a default to the whole table rather than just the individual header of a specific column. Following: https://www.ag-grid.com/javascript-data-grid/column-headers/

Code example on stackoverflow: https://stackoverflow.com/questions/70156226/how-to-display-custom-html-inside-ag-grid-column-headers 

**Expected behavior**

I would like to be able to un-escape the HTML I'm trying to add as the headerName.

**Please tell us about your environment:**

IntelliJ 2021.2.3

* **AG Grid version:** 24.0.0

* **Browser:** All

* **Language:** All

**Comment by gportela85** [comment]
check https://www.ag-grid.com/javascript-data-grid/component-header/

**Comment by codernani** [comment]
> check https://www.ag-grid.com/javascript-data-grid/component-header/

@gportela85  the above link still doesn't answer the main question

@HVinceH  Could you let us know if you found a solution for this? I have a requirement similar to yours but as you said template in headerParameters is being applied to whole table rather than one column. My requirement is I need to add an icon to column headers based on a condition.
Any help would greatly be appreciated.

**Comment by gportela85** [comment]
@codernani The header component that is shipped with Ag Grid will always parse the strings to avoid XSS attacks. If you want to be able to render HTML strings in the header, you will need to use a Custom Header Component, as described in https://www.ag-grid.com/javascript-data-grid/component-header/
