### ISSUE TITLE
Auto Row Height problems with multiple auto-height columns

### ISSUE THREAD

**Issue by spamacon** [ag-grid/ag-grid#4829]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Starting in v.26.2.0, if there are multiple auto-height columns in a table, the smaller auto-height cells don't fill the entire row.  Trying to correct this with a style `.ag-cell {height: 100%}` results in a resize loop that slowly shrinks all of the rows to a small size, then resets them and starts the shrinking process.  
 
I forked the [Auto Row Height](https://www.ag-grid.com/angular-data-grid/row-height/#auto-row-height) example to show the problem, as shown in this plunkr: https://plnkr.co/edit/ammNYTQcKoeeJbvK  

I added right borders so you can more easily see the individual cell height, and changed column B to be auto-height.  The border for some of the cells doesn't extend all the way to the bottom of the row.  Additionally, if you uncomment the `height: 100%` in the style.css, you'll see the grid start the resizing loop.

(Here is a StackBlitz showing the same problem, since I couldn't figure out how to set the plunker to use an exact version of the ag-grid package: https://stackblitz.com/edit/angular-ivy-khahfh?file=src%2Fstyles.css)

**Expected behavior**
In v26.1.0, the cells were correctly sized, as shown in this StackBlitz (sorry): https://stackblitz.com/edit/angular-ivy-pd5ke1?file=src%2Fstyles.css

You'll see the cell size is correct, and there is no resize loop even with `height: 100%` (which I need for some custom controls I'm using).

**Please tell us about your environment:**

* **AG Grid version:** 26.2.0

* **Browser:**
Chrome (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36)
Firefox (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0)

* **Language:** TypeScript

**Comment by gportela85** [comment]
This issue has been fixed in the latest branch and can be tracked in the Pipeline as AG-6143.

Thanks for reporting.
