### ISSUE TITLE
When using MacOS and only showing the scroll bar when scrolling, a phantom scroll bar appears that is not draggable

### ISSUE THREAD

**Issue by sea-dhassouni** [ag-grid/ag-grid#4830]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

On a mac, you can set your preferences for scrollbars to be 
1) Automatically based on mouse or trackpad
2) When scrolling
3) Always
A very common configuration is to set scrollbars only when scrolling.  However, in this mode, I see a horizontal scroll bar there al the time. It is a little thinner than the scrollbar that appears if I had the OS set to "always" show the scrollbar. The thinner scrollbar in "when scrolling" mode is not draggable. It just sits there. I can perform a horizontal scroll with a laptop trackpad, but I cannot click and drag the scrollbar with my mouse. I can "trick" it into letting me click it by starting to scroll with my trackpad, then using my mouse to click and drag once the actual scroll has been activated. 

I am able to reproduce this issue on the first grid on this page, for example. https://www.ag-grid.com/react-data-grid/column-sizing/

I think this issue is likely related to AG-5676 (“When using MacOS and only showing the scroll bar when scrolling, cells appearing under the scrollbar are visible but not clickable”) which was addressed in v26.1. Because now, the cells beneath that scroll bar are clickable, but it seems as though the scroll bar that I see is not clickable. 

**Expected behavior**

With this popular MacOS scroll setting, there should either be: 1) no horizontal scrollbar visible until a scroll is initiated, or 2) at least make the visible scrollbar draggable.

**Please tell us about your environment:**

Operating System: MacOS 11.6 (BigSur). 
None of the other info in this section is relevant since the bug is reproducible in one of the examples in the documentation.
IDE: VSCode  
Package Manager: yarn

* **AG Grid version:** 26.2.0

* **Browser:**
Google Chrome 96.0.4664.55 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
We use Typescript 3.8.3, React 17.0.2, etc. But again, this is an example on your page that displays the same behavior
<img width="1470" alt="Screen Shot 2021-12-14 at 4 24 34 PM" src="https://user-images.githubusercontent.com/53801354/146081903-3604f7d3-8c23-41aa-b272-22396e50b3d6.png">
.

**Comment by gportela85** [comment]
Looks like this is a BUG with Chrome. I have filed an issue here there https://bugs.chromium.org/p/chromium/issues/detail?id=1280013

The more people "starring" the issue, the faster it will be fixed.

To avoid this problem for the time being, add the following to your application:

```css
.ag-body-horizontal-scroll.ag-scrollbar-invisible {
    pointer-events: all !important;
} 
```

**Comment by sea-dhassouni** [comment]
@gportela85 Thank you for the quick turn-around on this temporary solution. It worked well. And thank you for filing a bug with Chrome.

**Comment by donovangini-RL** [comment]
> ```css
> .ag-body-horizontal-scroll.ag-scrollbar-invisible {
>     pointer-events: all !important;
> } 
> ```

Hi there! I wanted to point out that in our app the above workaround successfully hid the scrollbar, but prevented clicking anything behind it (in our case, an editable cell), so only the top half of the cell in the bottom row is clickable.

We are considering using a `display: none` instead to remove it completely
