### ISSUE TITLE
ag-grid-angular 22.1.1 Problems with the scrollbar of the grid on mozilla

### ISSUE THREAD

**Issue by mastdrak** [ag-grid/ag-grid#4831]
Hello everyone. A strange moment was discovered in the operation of the scrollbar in grids

Spec:
Angular: 9.1.3
Ag-grid: 22.1.1
Mozilla: 75+ version

Chrome - everything is ok. The scroll is located at the bottom of the grid area, available for scrolling. No problem
![image](https://user-images.githubusercontent.com/96184996/146191060-3ba5507e-b4dd-4733-9479-55f61f62e9b7.png)

Mozilla - the scroll is located immediately after the last entry in the grid, and is not attached to the lower border of the grid
![image](https://user-images.githubusercontent.com/96184996/146191318-5844e0b0-76f5-44e2-9b6d-9e8656594857.png)

in addition, the grid scroll block (ag-body-horizontal-scroll class) has a height of 0px. I.e. the scroll itself is not even tied to this area. Chrome's scroll is just in this area, and everything works correctly

Mozilla
![image](https://user-images.githubusercontent.com/96184996/146191485-49f577c5-45f0-4fa7-9943-0d279e05422b.png)

Chrome
![image](https://user-images.githubusercontent.com/96184996/146191695-26c97c08-19e9-444f-86e0-789619dc42fd.png)

Do you have any ideas? I would appreciate your help.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
