### ISSUE TITLE
React Custom Tooltip examples still use getReactContainerClasses

### ISSUE THREAD

**Issue by sea-dhassouni** [ag-grid/ag-grid#4834]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
For the [ReactUi](https://www.ag-grid.com/react-data-grid/reactui/) project, the documentation provides a list of "good breaking changes". Two of the four "good breaching changes" talk about no longer needing `getReactContainerClasses`. However, the examples for custom tooltip components still use that function inside of the useImperativeHandle hook. What would a proper example of custom styling for custom tooltip component look like if we were to adhere to the removal of  `getReactContainerClasses`? 
`   useImperativeHandle(ref, () => {
       return {
           getReactContainerClasses() {
               return ['custom-tooltip'];
           }
       }
   });`

I was able to put "custom-tooltip" directly in the wrapping div of my custom component and remove `  getReactContainerClasses()` from my code and it still worked (though position: absolute had to be removed from my style sheet). However, I still needed useImperativeHandle for the tooltip to render properly, which did not make a lot of sense to me since it wasn't doing anything. Is `useImperativeHandle` still needed? Is there a simpler way now? 

**Please tell us about your environment:**
Operating System: MacOS 11.6 (BigSur).

* **AG Grid version:** 26.2.0

* **Browser:** Google Chrome 96.0.4664.55

* **Language:** Typescript 3.8.3, ES 6/7, ES 5

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by Maratatasan** [comment]
Hello GitHub,


When **reactUi=true**

You can use react components **without** **useImperativeHandle** or **getReactContainerClasses**.

Just make a component and pass it to the tooltip. 

Please see the plunker example:  [ag-Grid ReactUi Tooltip Component example](https://plnkr.co/edit/ZR0o36ogQZEgIAA0)

**Comment by lalithyainukurthi** [comment]
I am encountering an issue with my completely customized tooltip component. Currently, I am unable to get it to work with the tooltipComponent. Instead of just customizing the content of the tooltip, I would like to use my customized tooltip component as a replacement. 
kindly request assistance and guidance in resolving this compatibility issue between my customized tooltip component and the tooltipComponent prop.
