### ISSUE TITLE
SSRM master details cell not updating after applyServerSideTransaction

### ISSUE THREAD

**Issue by galr52** [ag-grid/ag-grid#4835]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
way to reproduce: 
1. open 'Mila Smith' details cell
2. click on 'change Mila Smith calls'

https://plnkr.co/edit/FWQwF0ckBPmbOk4j

the detail cell should update and re render after apply server side transaction

Current behaviour.
the detail cell should update and re render after apply server side transaction

Expected behaviour. 
details cell re render with new data

**Current behavior**
the detail cell should update and re render after apply server side transaction

**Expected behavior**
details cell re render with new data

* **AG Grid version:** 26.2.0

* **Browser:**
google chrome Version 96.0.4664.55 (Official Build) (x86_64)
Brave Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (x86_64)

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
