### ISSUE TITLE
Two Horizontal Scrollbars Appear when there are Pinned Rows (MacOS)

### ISSUE THREAD

**Issue by sea-dhassouni** [ag-grid/ag-grid#4837]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
Here is a plunker: https://plnkr.co/edit/0NioNpvBwNFOaOQc
Compress the width of your browser such that it introduces a need to horizontally scroll the grid.
Scroll horizontally and notice that there are 2 horizontal scrolled bars. One beneath the main table data and one beneath the pinned row. 

If reporting a bug make sure to state.

**Current behavior**
Currently, when you scroll horizontally, you will see two scroll bars. One beneath the last row of the main table data, and one beneath the bottom pinned row.

**Expected behavior**
There should only be one scrollbar. I believe there should only be a scrollbar at the bottom of the table beneath the pinned row, but my understanding is that this has been discussed before in other tickets. I believe that was the consensus, but either way, I think it is clear there should only be one horizontal scrollbar.

**Please tell us about your environment:**
MacOS 11.6 (Big Sur)

* **AG Grid version:** 26.2.0

* **Browser:**
I have tested this in both Google Chrome Version 96.0.4664.55 (Official Build) (x86_64) and in Firefox 95.0.1 (64-bit). It was in issue in both browsers.

* **Language:** We use Typescript 3.8.3 in house and ES6/7. However, since this plunker is based off an ag-grid example, that isn't relevant.

**Comment by gportela85** [comment]
This is the same issue as https://github.com/ag-grid/ag-grid/issues/4830

**Comment by sea-dhassouni** [comment]
@gportela85 Can you expand upon how this is the same? I could believe it is related, but this manifests itself in a totally different way. In #4830, you were kind enough to provide a CSS stopgap. But these two issues manifest themselves in entirely different ways. In 4830, there was a "phantom" scroll bar that could not be dragged. It was just visible. In this one, there is no such "fake" scroll bar. Instead, once I initiate a horizontal scroll there are two scroll bars that each allow me to drag. 

Of note, in #4830, you said it was a bug with chromium. However, I reported in this issue that this problem shows up in both Chrome and Firefox... That sort of negates the possibility of this just being a bug with chromium?  

Thank you for any insight and clarity you can provide here.

**Comment by gportela85** [comment]
Sorry, my bad, I overlooked the fact that you had custom CSS applied to the grid
remove this block:
```
.ag-body-viewport {
  overflow-y: scroll !important;
}
```

and add `alwaysShowVerticalScroll={true}` to the grid

**Comment by sea-dhassouni** [comment]
Hi @gportela85 -- To be honest, I had overlooked that CSS as well. As I said, I pulled this plunker from an ag-grid example in the docs. However, your plunker still exhibits this issue for me, as seen in this screenshot. I don't understand why changing settings around vertical scroll would cause this issue with the two horizontal scrollbars. It is not as though the amount of horizontal scroll is only the width of of the vertical scrollbar. In any event, I've included a screenshot of your plunker on my browser (tried again on both Firefox and Chrome)

<img width="1113" alt="Screen Shot 2021-12-17 at 10 51 57 PM" src="https://user-images.githubusercontent.com/53801354/146628154-87666b72-d8d1-42e7-afbb-a694e8563f47.png">

I know this might not be the most pressing issue so I don't expect an immediate fix by any stretch -- but I also do not believe this issue should be closed. It still seems like an issue based on what I am experiencing. 

Thanks again for having a look.

**Comment by gportela85** [comment]
@sea-dhassouni This one I cannot reproduce at all. I have both Firefox and Chrome side by side. I suggest that if you are a paying customer, please file an issue through Zendesk so the support team can take a look at it. Screenshot below: 

![Screen Shot 2021-12-18 at 8 16 13 AM](https://user-images.githubusercontent.com/7908562/146648035-32ece700-2724-49d4-af1a-7d7af4975df6.png)

**Comment by Jacobus52999** [comment]
@gportela85 @sea-dhassouni Apologies for commenting on a closed issue however would it possible to take a look at this again or share some details if a ticket was ever logged in Zendesk for this? It seems to only occur when a particular setting is enabled on MacOS: Scroll Bars > When Scrolling (similiar to #4830 ). I was able to replicate it in the included Plunkers.

**Comment by makis-spy** [comment]
Mac. 2 scrollbars appear

**Comment by makis-spy** [comment]
Not sure iof I should be doing this: 
.ag-scrollbar-invisible {
  display: none !important;
}

**Comment by gportela85** [comment]
@makis-spy If you do this, you will not be able to scroll the grid horizontally (by dragging the scrollbar) if you also have a vertical scroller. It's not a big deal for most users, since everyone with these settings use the touchpad.

@sea-dhassouni @john-shipp @Jacobus52999 I have a temporary fix for the issue that can be used until I'm able to patch this. See: https://plnkr.co/edit/pKlGVwNxrKPw3TB3?preview

Notice that for this to work, the pinnedRowData has to be applied **via API** by using `setPinnedBottomRowData`, this is needed so the `onPinnedRowDataChanged` event is fired. The workaround is inside the `onPinnedRowDataChanged` method.

**Comment by gportela85** [comment]
fixed: https://github.com/ag-grid/ag-grid/commit/e8997c22df14e6dace82c99092b9084cde17777a

**Comment by Randywang888** [comment]
@gportela85 I have the same issues in Mac OS. OS is Monterey, Chrome and Firefox. I saw 2 horizental scrollbar in Chrome and Firefox. Is there any way to fix this? Any help will be appriciated. Thanks
**alwaysShowHorizontalScroll={true}** whatever set this or not. It doesn't work.

**Comment by gportela85** [comment]
@Randywang888 I left a workaround here - https://github.com/ag-grid/ag-grid/issues/4837#issuecomment-1178951996 - You can either use the workaround or upgrade to a version where the issue has been fixed.
