### ISSUE TITLE
ag-grid-community package size issue

### ISSUE THREAD

**Issue by sebthiertant** [ag-grid/ag-grid#4838]
I'm submitting a support request

**Requesting Community Support**

I'm currently trying to implement ag-grid into a vue2 project. I'm currently pretty surprise that the ag-grid-community package is 32Mo in my node_modules as it seems to be estimate around 1Mo here : https://bundlephobia.com/package/ag-grid-community@26.2.0

It's mentionned as 32Mo here : https://www.npmjs.com/package/ag-grid-community

I want to use the ag-grid-community@26.2.0 and the ag-grid-vue@26.2 in the future, but I can't really handle a so huge package. 

What is a so huge difference between the size of the packages ? What is the real size of the vue2 and ag-grid-commutity packages I have to implement ?

Thank you for you help.

* **AG Grid version:** 26.2.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36'

* **Language:** [vue2.6.12]

**Comment by Vecxinnt** [comment]
I would like to know as well. 32Mo is going to kill my project.

**Comment by StephenCooper** [comment]
Can I ask why you are concerned with the 32Mb unpackaged size in node_modules? As far as I am aware it is very common for unpackaged sizes to be very large for many packages. 

When included as a dependency to your application its size will be around the 1Mb /  212.5kB (compressed) as reported on the bundle phobia link you also shared.

**Comment by sebthiertant** [comment]
I'm concerned by the size because of the nature of the application i'm working on. 
I was just surprise that nobody was mentionning size issues before. 

After implementation, he soze of the dependency is more than 6MB.
Do you have any clue why I can't be closer to the 1Mb you were mentionning ? 

![aggrid_size](https://user-images.githubusercontent.com/75473312/147092976-47150018-9c6a-4b84-a560-cd84e2d7c8a5.PNG)

**Comment by StephenCooper** [comment]
Looks like that is not using the minified version which would explain that size. Not sure how your app is setup but look to change to the `ag-grid-community.min.js`.

**Comment by sebthiertant** [comment]
After some webpack configuration, the dependency was minified until around 500kB. It looks way better than the first time I implemented it. Thank you for your supports !

Merry Christmas, and happy new year 😉

**Comment by StephenCooper** [comment]
Fantastic! That's more like it. 

Merry Christmas!
