### ISSUE TITLE
Change detection does not work in custom angular header

### ISSUE THREAD

**Issue by CherkashinEvgeny** [ag-grid/ag-grid#4840]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
See: [stackblitz](https://stackblitz.com/github/CherkashinEvgeny/table)

**Current behavior**
Change detection does not work for columns, that has been created on onCenterViewportResized event. If you open browser console, you will see, that first 5 columns has been created immediately, and 2 columns has been created with some delay. If you hover your mouse over one of the first columns, you will see a tooltip. And if you hover mouse on column with name 'column-5', you will see empty rectangle. That happens, because angular does not trigger change detection on 'column-5'.

**Expected behavior**
Change detection should work for all columns.

* **AG Grid version:** 26.2.0

* **Browser:** Chrome/96

* **Language:** Angular 13, TypeScript 4.4.3

Many thanks.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by Maratatasan** [comment]
Hello GitHub,

Thank you for the example provided.

We are **not sure** what exactly is happening as the grid seems to be working with the built-in tooltips so it might be something to do with Material Ui.

Our recommendation for the solution in the example provided is to turn off column virtualization.

This seemed to work on our end.

Thanks

**Comment by CherkashinEvgeny** [comment]
Thank you for your answer. Disabling column virtualization solved my problem. 
But i am not sure, that problem was in Materil UI. **Change detection mechanism is broken in all angular components, when column virtualization is enabled.** I think, that problem lies in angular integration into ag-grid.
Many thanks.
