### ISSUE TITLE
External DropZone - how drop to dynamic elements

### ISSUE THREAD

**Issue by wtcodeai** [ag-grid/ag-grid#4841]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
**Please tell us about your environment:**
MacOS Monterey 12.0.1, Vue3

* **AG Grid version:** 26.1.2

* **Browser:**
Safari 15.1

* **Language:** ES7

So, we have example https://www.ag-grid.com/vue-data-grid/row-dragging-to-external-dropzone/ for dropping rows to external dropzone, but dropzone is static element

What the best way to drop rows (multiple) to dynamic external array which not an ag-grid instance as childrens of existing array element for example? How to get dynamic element to which dragged files was dropped?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
