### ISSUE TITLE
Export to Excel Tree structure data format

### ISSUE THREAD

**Issue by AnkitKamdar** [ag-grid/ag-grid#4845]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I need to export a tree structure data format to Excel using ag-grid API `exportDataAsExcel`. While exporting the data using above API, exported data are not showing correct hierarchy format.

Below format is exported using ag-grid API.
![IMG_20211222_121158](https://user-images.githubusercontent.com/1697587/147049287-e9ec3a72-7e72-4327-951d-3796de78bc99.jpg)

We need to export the structure as per the below tree format where it is showing the correct hierarchy structure.

![IMG_20211222_121209](https://user-images.githubusercontent.com/1697587/147049286-3a2f999c-153b-45d4-8ef0-4efa3066b73f.jpg)

* **AG Grid version:** Latest

* **Browser:**
Chromw

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | React]

Can you please suggest the best approach to achieve the given export format.

**Comment by ibrahimgabsi** [comment]
You may want to achieve that using the combination of `autoGroupColumnDef.cellClass` and `processRowGroupCallback` as documented here: [Styling row groups](https://www.ag-grid.com/react-data-grid/excel-export-styles/#example-styling-row-groups).
This worked fine for me but i'm trying to improve it by having the outline levels which permit to filter displayed row groups or navigate throught it as shown here:
 
![Capture](https://user-images.githubusercontent.com/3437008/147077797-7b611ebd-b85c-4f67-8c41-c5984d4b4167.PNG)

Does anybody knows how to manage it?

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
