### ISSUE TITLE
ChildNode component is not expanding when React Ag-grid table is filtered. 

### ISSUE THREAD

**Issue by aradhanasinghmcscet** [ag-grid/ag-grid#4849]
**Customers of AG Grid**

I am using Enterprise version of React-AgGrid . I'm facing an issue in my react ag-grid functionality Grouping with filtering. So I have treeView table whether child node is another component(Table) coming from different api call back. In general when i'm expanding the row it's expanding and showing the child component data. However when there is filter text in quickFilter it is not showing anything in child component. Basically it's not making request to child api at all with filtered data. 

If reporting a bug make sure to state.

**Current behavior**
Expand is not showing child component only icon is changing with filtered data. 
When filter cleared it's working. 

**Expected behavior**
Grouping should work with filtered data as well. It should expand the child node component on filtered data as well.

**Please tell us about your environment:**
Development environment.

* **AG Grid version:** X.X.X
23.2.1

* **Browser:**
all the browser

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

This is my agGrid common component. Child component is also using same component to represent agGrid data.
<AgGridReact
				enableCellChangeFlash
				defaultColDef={defaultColDef}
				columnDefs={columnDefsExtended}
				rowData={rowData}
				onGridReady={gridReadyCallback}
				pagination={pagination}
				paginationAutoPageSize
				rowSelection={multiRowSelectable ? "multiple" : null}
				rowMultiSelectWithClick
				rowDeselection
				// groupSelectsFiltered={groupSelectsFiltered}
				excludeChildrenWhenTreeDataFiltering={
					excludeChildrenWhenTreeDataFiltering
				}
				suppressColumnVirtualisation={__AG_SUPPRESS_COLUMN_VIRTUALISATION__}
				onFilterChanged={onFilterChanged}
				modules={[
					ClientSideRowModelModule,
					ClipboardModule,
					MenuModule,
					ColumnsToolPanelModule,
					CsvExportModule,
					ExcelExportModule,
				]}
				{...props}
			/>

This is my filter ui code- 
	<div className={s.gridActions}>
					<div>Grid Actions :</div>
					&nbsp;
					<input
						type="text"
						placeholder="Filter.."
						id="filterTextBox"
						onChange={onFilterTextBoxChanged}
					/>
					<ButtonGroup>
						<Button className="btn-xs" onClick={clearAllFilterCallback}>
							Clear filters
						</Button>
						{extraActions}
					</ButtonGroup>
					{stats}
				</div>

And this is filter function- 
	const onFilterTextBoxChanged = (e) => {
		gridApi.setQuickFilter(
			document
				.getElementById("filterTextBox")
				.value(gridApi.setQuickFilter(e.target.value)),
		);
	};

**Comment by aradhanasinghmcscet** [comment]
I found componentDidMount doesn't trigger for child component api with filtered data. Can someone help me please ?

**Comment by aradhanasinghmcscet** [comment]
I'm using ag-grid 23.2.1. Can someone suggest on this ?

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
