### ISSUE TITLE
[v26 regression] when autoHeight, the cellStyle not applied to cell content but to the parent

### ISSUE THREAD

**Issue by croraf** [ag-grid/ag-grid#4853]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**

**This is a regression issue / Breaking change** not described in 26 breaking changes, if it got introduced at 26 migration. In 25.3.0 you could use `cellStyle` to apply style to the cell content. For example I used 
```
'display': '-webkit-box',
"-webkit-line-clamp": '6',
'-webkit-box-orient': 'vertical',
```

Why this seems to work is  because a number of styles get inherited by the children (like color), so the issue is not noticed always.

Even thought this might be the intended behavior, it is a breaking change, and should be described as such and provide a recommended way to recreate previous behavior.

**Current behavior**

The style is applied to the parent's parent.
https://plnkr.co/edit/UqYWvR5APVFMXxHr (v.26.2.1)

**Expected behavior**

The style should be applied to the cell's content element (<span>).
https://plnkr.co/edit/GL0SfsZLnTxHg9CF (v.25.3.0)

**Please tell us about your environment:**

* **AG Grid version:** 

    "ag-grid-community": "^26.2.1",
    "ag-grid-react": "^26.2.0",

* **Browser:**

'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36'

* **Language:** [all]

**Comment by croraf** [comment]
I must add that removing:

```
const onColumnResized = (params) => {
    params.api.resetRowHeights();
  }
```

in the new version seems to solve the issue and works properly.
But, am not sure if it has some other consequences. 

Anyways should be described in breaking changes if this is expected.

**Comment by kiril-matev** [comment]
Hi @croraf,

Thanks for pointing this out.

Our next release - AG Grid v27 is currently planned for the first half of February.

**Comment by kiril-matev** [comment]
@croraf, 

We've looked into this with the product team.

Instead of using CSS to implement this behavior, please use Cell Class with settings that trickle down, such as demonstrated here:
https://plnkr.co/edit/EH1QcDf7x7kZMrz5 

In cases where it’s dynamic (where params.data.reversal is used) please use different CSS classes for different scenarios.

As you can implement this behavior using the approach described above, we've closed this bug rejected.
