### ISSUE TITLE
Customize ColumnDrag header text

### ISSUE THREAD

**Issue by Superkarl** [ag-grid/ag-grid#4862]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
I would like to display the formatted header (**Athlete) in the placholder when dragging and dropping.
![image](https://user-images.githubusercontent.com/25085331/148747700-5e50ff65-c1bc-418f-8b94-0f08463aed22.png)

**Providing a Reproducible Scenario**
https://plnkr.co/edit/wP3LucZVUlcLGDPz

**Current behavior**
Only the headerName is displayed per drag&drop.

**Expected behavior**
I would like to display the formatted header (**Athlete) in the placholder when dragging and dropping.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by Superkarl** [comment]
Is there any solution about the problem?
