### ISSUE TITLE
autoSize and fit apis not working

### ISSUE THREAD

**Issue by barbarossusuz** [ag-grid/ag-grid#4864]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
In ssm ag-grid when trying to auto size columns in onFirstDataRendered event, it is not working. 
However when i wrap logic with setTimeout( 1000 sec) it is working.
I guess api is not ready for 500-600 ms after render 

I reproduce. example with this example:  https://www.ag-grid.com/javascript-data-grid/server-side-model-datasource/#example-simple

- **here reproduced example**: https://plnkr.co/edit/y92PTkMzZD4mGIj7

**Current behavior**
fit and size apis not working

**Expected behavior**
There was no such problem in version 23, it broke when upgraded to version 26

* **AG Grid version:** 26.2.0

* **Browser:**
Chrome/90.0.4430.93 
Safari/537.36

* **Language:** React / ES6

**Comment by fahrigoktuna** [comment]
Are there any progress related of this issue?

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Apologies for the late reply, we had a look at this issue and we were not able to spot any obvious issues with it, however this being an enterprise feature and It sounds like you have an ag-grid license/evaluating.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
