### ISSUE TITLE
Pressing Ctrl-left arrow jumps to pinned first column but doesn't scroll grid to left

### ISSUE THREAD

**Issue by pjm17971** [ag-grid/ag-grid#4866]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

If you pin a column, then scroll to the right, then try to use the keyboard shortcut ctrl-← to jump back to the first cell, the focus will shift to the first column correctly, but because it is pinned, the grid itself will not scroll back across. In my actual use case there's over 100 columns and the user needs to be able to scroll back fully left.

Here is one of the [AgGrid examples](https://www.ag-grid.com/javascript-data-grid/keyboard-navigation/#example) behaving this way:

https://user-images.githubusercontent.com/1288813/148844274-ddc72e8d-d558-433e-ab81-13919bb2d214.mov

When I press ctrl-←  it jumps to "Swimming" but the grid itself didn't scroll back. The first non-pinned column "Athlete" remains hidden until I manually scroll back.

**Expected behavior**

When you hit ctrl-← the grid will scroll fully left and focus will go to the first column.

**Please tell us about your environment:**
OS-X

* **AG Grid version:** X.X.X
25.1

* **Browser:**
Chrome/97.0.4692.71

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as we think is best not to scroll the area where the user is located when moving to the pinned area

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
