### ISSUE TITLE
Ag-Grid does not use passive event listeners for scrolling events

### ISSUE THREAD

**Issue by stefnedelchev** [ag-grid/ag-grid#4869]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

If you try to do a performance diagnostics of an app that uses ag-grid with Google's Lighthouse, you'll see the following section among the results:

**Does not use passive listeners to improve scrolling performance**
*Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance.*

followed by links to the JS files where this is found. If you use a non production build (or source maps), clicking one link leads you to this part of the ag-grid community core package:
![source info](https://i.ibb.co/nPgR9q9/ag-grid-event-listener.png)
It seems to be from the following source `community-modules/core/src/ts/utils/event.ts` but of course, not necessarily the problem. The reason why Lighthouse is complaining is because a non-passive event handler is being attached to a scoll event - something which is considered a performance drawback.

**Please tell us about your environment:**
Windows 10 x64, VSCode, NPM v6

* **AG Grid version:** 26.2.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

* **Language:** TypeScript 4.4.4

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
