### ISSUE TITLE
FilterData setModel not working

### ISSUE THREAD

**Issue by LJolon** [ag-grid/ag-grid#4870]
I want filter some Data use setModel and onFilterChanged function,but it's not working.
how to do some thing to make it working? 
 code:
```
    var countryFilterComponent = gridApi.getFilterInstance('fieldA');
          const model = countryFilterComponent.getModel();
          countryFilterComponent.setModel({
            filterType: 'text',
            type: 'contains',
            filter: value,
          });
            gridApi.onFilterChanged();
```

* **AG Grid  React version:** 
26.2.0

* **Browser:**
Google 81

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React typeScript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
