### ISSUE TITLE
Floating filter in the number column returns NaN if  non-numeric values are entered

### ISSUE THREAD

**Issue by adrianpikul** [ag-grid/ag-grid#4875]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Current behavior**
Entering a non-numeric value in the floating filter in a column with numbers returns NaN. 

tested on : https://www.ag-grid.com/react-data-grid/floating-filters/
![image](https://user-images.githubusercontent.com/74068555/149897185-4fb1d69c-285f-4ab9-bdf0-46619b3bfd30.png)

**Expected behavior**
If the column is of type number, filtering should only allow positive and negative numbers with a - sign.

**Please tell us about your environment:**
Win10

* **AG Grid version:** X.X.X
version placed in the documentation at the link
https://www.ag-grid.com/react-data-grid/floating-filters/

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by adrianpikul** [comment]
Is there any way I can control the value in the floating filter field?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by ivanprotasau** [comment]
Hi @makinggoodsoftware! Bug still reproducible. Are you plan to fix it? Are any workarounds not show this ugly NaN to users? Thanks!
