### ISSUE TITLE
In React ui mode, when i force refresh cells by call grid api, the custom cell render component's refresh not invoked

### ISSUE THREAD

**Issue by luox12** [ag-grid/ag-grid#4876]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

https://plnkr.co/edit/Y9oAAdSekumVIxTF

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

In React ui mode, when i force refresh cells by call grid api, the custom cell render component's refresh not invoked:
https://plnkr.co/edit/Y9oAAdSekumVIxTF
when comments the "reactUi=true", its work fine!

**Expected behavior**

seems it is a bug

**Please tell us about your environment:**

* **AG Grid version:** 26.2

yes

* **Browser:**

electtron

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 4

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hello!
 
Thank you for your email.
 
This is not a bug with AG Grid. Before AG Grid React UI, it was tricky to manage wasted React renders, as the grid wasn't participating as part of the React application. Now that the grid is written in React, it participates fully in the React rendering. 
 
This means that when you call refreshCells on a cell which has a cellRenderer, the render method for that component will be called. So you can execute your refresh logic in the render method of the class component.
 
You can verify this in the following example here:
 
https://plnkr.co/edit/9UkzEyPNBMTiX0N1 
 
Note how the counter is incremented, showing how many times the component has been rendered. 
 
We're looking forward to your feedback.
 
Regards,
 
Shuheb‍
Developer | AG Grid

**Comment by luox12** [comment]
> Hello!
> 
> Thank you for your email.
> 
> This is not a bug with AG Grid. Before AG Grid React UI, it was tricky to manage wasted React renders, as the grid wasn't participating as part of the React application. Now that the grid is written in React, it participates fully in the React rendering.
> 
> This means that when you call refreshCells on a cell which has a cellRenderer, the render method for that component will be called. So you can execute your refresh logic in the render method of the class component.
> 
> You can verify this in the following example here:
> 
> https://plnkr.co/edit/9UkzEyPNBMTiX0N1
> 
> Notice in the above example how the counter is incremented, showing how many times the component has been rendered.
> 
> Note that I will be closing this issue as it's not a bug.
> 
> Regards,
> 
> Shuheb‍ Developer | AG Grid

Thanks for reply, i got it, but i think this is a break changes, and should update the docs.
