### ISSUE TITLE
Loses focus after calling refreshHeader() method

### ISSUE THREAD

**Issue by nemeek2017** [ag-grid/ag-grid#4877]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I'm using a floating filter (text filter) defined as:
![image](https://user-images.githubusercontent.com/30801269/149916060-e3cf65df-a6e4-4460-b874-1670025a139e.png)
I write something in the filter and it works as expected, but after filtering, I need to refresh the header calling the method refreshHeader from API.
![image](https://user-images.githubusercontent.com/30801269/149916361-c18809bb-0fde-4995-82d0-9db5435d03ae.png)
Then, when I call this method, I lose focus on the filter and I need to click in the text area again to get the focus.

**Current behavior**
After calling refreshHeader() method from API, it loses the focus.

**Expected behavior**
After calling refreshHeader() method from API, it must be to keep the focus.

**Please tell us about your environment:**
Windows 10 Pro
VS Code
Node 14.15.5
Npm 6.14.11
Angular 13.1.0
ag-grid-angular 26.2.0
ag-grid-community 26.2.1

* **AG Grid version:** 26.2.X

* **Browser:**
All browsers

* **Language:** TypeScript ^4.5.3

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by tim-phillips** [comment]
To solve this I had to maintain state outside of the grid and pass it in via `context`. I set the focus state using `onFocus` and `onBlur` and cursor position using `onChange` and `event.target.selectionStart`. In the floating filter inside `useImperativeHandle` I leveraged the `afterGuiAttached` method to restore the input state:

```js
afterGuiAttached() {
  const { isSearchFilterFocused, searchFilterSelectionStart } =
    filterParams.context ?? {};
  if (isSearchFilterFocused) {
    inputRef?.current?.focus();
    if (searchFilterSelectionStart >= 0) {
      // wait for the next event cycle when the input is focused
      setTimeout(() => {
        inputRef?.current?.setSelectionRange(
          searchFilterSelectionStart,
          searchFilterSelectionStart
        );
      });
    }
  }
}
```

It's not ideal, but it's the best user experience we could get.

**Comment by a688** [comment]
Here is a repo https://plnkr.co/plunk/osrEWs3SptlGK51i . Just filter by any column. Once refreshHeader() is called, the filter will close instead of remain open.

**Comment by AG-Zoheil** [comment]
Hi @a688,

Thank you for responding and providing a reproducible scenario.

However this isn’t a bug, calling `refreshHeader` replaces the `headerElement` with a different one, causing the filter to be left without a parent, which then, destroys it. This is expected behaviour and cannot be changed by us.

I hope that clarifies the issue.

Kind regards,
Zoheil

**Comment by a688** [comment]
Thanks for the reply. We are trying to update the style for a column header (to change its color to tell the user that the column has a filter applied). Is there a better way to do this or is this not really a supported scenario?

**Comment by AG-Zoheil** [comment]
You can achieve this using some css. 

```
.ag-header-cell.ag-header-cell-filtered {
                background-color: khaki;
            }
```

See this in action here:
https://plnkr.co/edit/QUgWTrenSBfScbZ6

**Comment by a688** [comment]
Just what we needed! Thanks.
