### ISSUE TITLE
How sorting put null value to the top

### ISSUE THREAD

**Issue by gotzsys** [ag-grid/ag-grid#4878]
Sorting of the grid put null value on the top.
How I can place the values allways at the end of the grid?
I tryed this example but didn't work, my column is a numericColumn

https://stackoverflow.com/questions/66456829/ag-grid-how-to-sort-column-to-show-all-null-values-as-last

**Comment by gotzsys** [comment]
I think i found a solution

`comparator: (valueA, valueB, nodeA, nodeB, isInverted) => {
        if (valueA === null && valueB === null) {
            return 0;
        }
        if (valueA === null) {
            return isInverted ? -1 : 1;
        }
        if (valueB === null) {
            return isInverted ? 1 : -1;
        }

        return valueA - valueB;
    }`

**Comment by gportela85** [comment]
Glad to see you found a solution. Just don't do `valueA - valueB`. The comparator expects -1 , 0 and 1 as return. Any other value will produce weird results.

**Comment by elpddev** [comment]
Is this ag grid bug? in any sort algorithm wont it be sufficient to return 1 or -1 for null argument based on the infinity direction we want to pin it?

**Comment by elpddev** [comment]
I came here thinking it was ag-grid bug. It seems that if the comparator is not transitive, some sorting implementations can fail

https://stackoverflow.com/questions/40198079/how-does-array-sort-behave-if-comparison-function-is-not-transitive
