### ISSUE TITLE
Error when call onFilterChanged with some column def's filter is false

### ISSUE THREAD

**Issue by luox12** [ag-grid/ag-grid#4879]
I have a table with some column defs which filter property is false.
for example:
{
    field: 'xxx',
    filter: false
}

Then i called the grid api's onFilterChanged, error occurs, the console info is:

TypeError: Cannot read properties of null (reading 'resolveNow')
  28908 |     return filter.isFilterActive();
  28909 | };
  28910 | this.allAdvancedFilters.forEach(function (filterWrapper) {
> 28911 |     if (filterWrapper.filterPromise.resolveNow(false, isFilterActive)) {
        | ^  28912 |         var resolvedPromise = filterWrapper.filterPromise.resolveNow(null, function (filter) { return filter; });
  28913 |         _this.activeAdvancedFilters.push(resolvedPromise);
  28914 |     }

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by luox12** [comment]
i cannot reproduce this error, but after update to v27.0.1, the error dispeared.
