### ISSUE TITLE
@ag-grid-community/react 26.2.0 fails in production when build with Vite

### ISSUE THREAD

**Issue by MADronov** [ag-grid/ag-grid#4885]
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Requesting Community Support**

**Current behavior**

When building for production with @vitejs/plugin-react attempt to use AG Grid fails with 
`ReferenceError: React is not defined` in // @ag-grid-community/react v26.2.0 newReactComponent.js

**Expected behavior**
Stable build for production

**Quickfix**
I did not research why it happens, but replacing require with import fixes issue:

`var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};`
`
var react_1 = __importStar(require("react"));
`

instead of
`
var react_1 = require("react");
`

**Please tell us about your environment:**
ViteJS + React

* **AG Grid version:** 26.2.0

**Comment by skalidindi** [comment]
Also facing this issue

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by Manubi** [comment]
Hi,
same issue.

There is not much of a repro needed I think. It's only vitejs with react and ag-grid. 
cheers

**Comment by Manubi** [comment]
@skalidindi Where you able to fix it with your solution?
<img width="658" alt="CleanShot 2022-03-11 at 11 52 51@2x" src="https://user-images.githubusercontent.com/20935138/157853631-0aa5c45f-129f-4307-827f-a5c1699d585b.png">

I am  also not sure how to combine the browserify alias with your solution. Thanks for your help!

**Comment by skalidindi** [comment]
Vite has web pack to do aliasing which is what I used i.e https://vitejs.dev/config/#resolve-alias.
I have not looked into this issue much anymore though as I have moved away from ag-grid to https://reactdatagrid.io/

**Comment by underfisk** [comment]
@skalidindi Your workaround seems to work but there's definitely something wrong with the ESM build.

Is there any known ag-grid backlog issue to review the ESM config?

**Comment by flying3615** [comment]
For ag-grid V27, the folder changed and the target should be like
```
{
          find: "ag-grid-react",
          replacement: path.resolve(__dirname, "./node_modules/ag-grid-react/bundles/ag-grid-react.min.js"),
        },
```
