### ISSUE TITLE
Problem with grid size in first load

### ISSUE THREAD

**Issue by MykolaTitov** [ag-grid/ag-grid#4887]
Hi, I have a problem with grid size in the first load. When the grid gets data, it displed for half of the screen but after a few seconds resize to full screen. But in the configuration of columns, I set flex 1.

**Current behavior**
Grid change size in the first load

**Expected behavior**
Grid load in full size without resizing

* **AG Grid version:**
    "ag-grid-community": "^24.1.0",
    "ag-grid-react": "^24.1.1",

* **Browser:**
All

* **Language:** TypeScript 4.5.4

**Comment by microcipcip** [comment]
@MykolaTitov I've fixed this very issue, I was returning `null` when there was no data (before CSS loaded) but changed that to `opacity: 0;` instead, which fixed the issue.
