### ISSUE TITLE
Pasting multiple rows from excel into AG Grid clears out an extra cell. 

### ISSUE THREAD

**Issue by pbagioli** [ag-grid/ag-grid#4888]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Pasting multiple rows from excel into AG grid will clear out an extra cell on the subsequent row.

https://plnkr.co/edit/FOXcZ7vbQGTeFLMa?preview

If reporting a bug make sure to state.

Current behaviour.
First row that was not pasted over will have its first cell cleared out.

Expected behaviour.
First row that not pasted over will have its cell unchanged

See attachments. My Plunkr is just a copy from official documentation. Pasting in multiple rows from excel does not work.

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

You can see more information here:



suppressLastEmptyLineOnPasteboolean | Set to true to work around a bug with Excel (Windows) that adds an extra empty line at the end of ranges copied to the clipboard.Default: false
-- | --


[](https://www.ag-grid.com/react-data-grid/grid-properties/#reference-clipboard-suppressLastEmptyLineOnPaste)suppressLastEmptyLineOnPaste
boolean
Set to true to work around a bug with Excel (Windows) that adds an extra empty line at the end of ranges copied to the clipboard.
Default: false
https://www.ag-grid.com/react-data-grid/grid-properties/#reference-clipboard 

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
