### ISSUE TITLE
[gridOptions] Allow setting default gridOptions globally, for all grid instances

### ISSUE THREAD

**Issue by mike-ward** [ag-grid/ag-grid#489]
ngDialog has this and it's darn handy.

ngDialog example:

``` js
app.config(['ngDialogProvider', ngDialogConfig]);

function ngDialogConfig(ngDialogProvider) {
  ngDialogProvider.setDefaults({
    plain: true,
    showClose: true,
    closeByEscape: true,
    closeByDocument: true,
    disableAnimation: true,
    className: 'ngdialog-theme-plain'
  });
```

**Comment by ceolter** [comment]
you want to specify defaults for the Col Defs ??

**Comment by daric81** [comment]
I was looking for something like this too where i can set the default values for grid options that will apply to every instance, ie suppressColumnVirtualisation = true.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-74

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
