### ISSUE TITLE
Wrong date showing in different time zone

### ISSUE THREAD

**Issue by logeshdev** [ag-grid/ag-grid#4890]
When  we open ag-grid report in different time zone (PST in our case), It is showing wrong date, It's showing 4 days back date from actual date.  

Example:
Actual time is 2022-08-04 but it's showing 2022-07-30.

Kindly address  

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
