### ISSUE TITLE
WebSQL/IndexedDb storage for large dataset

### ISSUE THREAD

**Issue by emdadgar2** [ag-grid/ag-grid#4892]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hi,

Can you use WebSQL or IndexedDb local storage to store data in browser instead of ram for better memory managment in large dataset (>1M)?

Thanks for your great product

[https://www.w3.org/TR/webdatabase/](https://www.w3.org/TR/webdatabase/)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by emdadgar2** [comment]
Hi @makinggoodsoftware 

Has this request been rejected now or something else?

**Comment by mke21** [comment]
I would like this feature as well, but I'm not sure what the status here is.

**Comment by StephenCooper** [comment]
Hi @mke21,

There are no plans to implement this feature currently.

**Comment by mke21** [comment]
@StephenCooper clear, thanks.
