### ISSUE TITLE
Watermark is not display even if I used ag-grid-enterprise 

### ISSUE THREAD

**Issue by vikanirav** [ag-grid/ag-grid#4899]
Hello,

I used following ag grid enterprise feature and set empty license key. But as per ag-grid documentation, it is not showing watermark in grid for a few seconds. License validation is display in console only.
  - ClientSideRowModelModule
  - MenuModule
  - ExcelExportModule

Can anyone help here? why it is not showing watermark with ag grid enterprise feature.

Code:
`import React, { useState } from "react";
import { AgGridReact } from "@ag-grid-community/react";

import { ModuleRegistry } from "@ag-grid-community/core";
import { ClientSideRowModelModule } from "@ag-grid-community/client-side-row-model";
import { MenuModule } from "@ag-grid-enterprise/menu";
import { ExcelExportModule } from "@ag-grid-enterprise/excel-export";

import {LicenseManager} from '@ag-grid-enterprise/core';

import "@ag-grid-community/core/dist/styles/ag-grid.css";
import "@ag-grid-community/core/dist/styles/ag-theme-alpine.css";

ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  MenuModule,
  ExcelExportModule,
]);

LicenseManager.setLicenseKey('');

function App() {
    const [columnDefs, setColumnDefs] = useState([
    { headerName: "Make", field: "make" },
    { headerName: "Model", field: "model" },
    { headerName: "Price", field: "price" },
  ]);

  const [rowData, setRowData] = useState([
    { make: "Toyota", model: "Celica", price: 35000 },
    { make: "Ford", model: "Mondeo", price: 32000 },
    { make: "Porsche", model: "Boxter", price: 72000 },
    { make: "Porsche", model: "Boxter", price: 72000 },
    { make: "Porsche", model: "Boxter", price: 72000 },
    { make: "Porsche", model: "Boxter", price: 72000 },
    { make: "Porsche", model: "Boxter", price: 72000 },
    { make: "Porsche", model: "Boxter", price: 72000 },
  ]);

  return (
    <div className="ag-theme-alpine" style={{ height: 400, width: 600 }}>
      <AgGridReact
        columnDefs={columnDefs}
        rowData={rowData}
        onGridReady={(params) => params.api.sizeColumnsToFit()}
      ></AgGridReact>
    </div>
  );
}

export default App;`

**Comment by gportela85** [comment]
Are you testing this on localhost? The license watermark is not displayed on `localhost` as it is treated as dev environment.

**Comment by vikanirav** [comment]
Thank you! @gportela85. I am testing on localhost.
