### ISSUE TITLE
server side operations graphql sample running issue

### ISSUE THREAD

**Issue by rajapandiyan172** [ag-grid/ag-grid#4901]
**I'm submitting a support request** 

Hi Team,

I have followed the below article to perform server-side operations with GraphQL,

https://ag-grid.com/javascript-data-grid/server-side-operations-graphql/

I have successfully created the database (sample_data) and connected the table (olympic_winners.sql).

While running the sample, the data does not load to the Grid. it throws a script error. How can i resolve this.

<img width="834" alt="ag_Grid_error1" src="https://user-images.githubusercontent.com/76764789/152097038-c9eaa9e7-bf0a-4728-b3e7-380999e4a0c5.PNG">

<img width="850" alt="ag_Grid_error2" src="https://user-images.githubusercontent.com/76764789/152097189-23f9a607-5a22-4e86-948b-63e295c8e8b4.PNG">

Regards,
Rajapandiyan S

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
