### ISSUE TITLE
Ag-grid enterprise not returning row on selecting (Blank) value from filter for agSetColumnFilter

### ISSUE THREAD

**Issue by shwetavaibhavveta** [ag-grid/ag-grid#4902]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
URL - https://plnkr.co/edit/0kqRFdV8d6DnqWy3
![image](https://user-images.githubusercontent.com/98953086/152344593-636878a7-e8f5-4252-87a8-a6ad46e87446.png)

Rows with blank value is not populating on selecting (Blank) option from filter

**Expected behavior**
Rows with blank value should populate on selecting (Blank) option from filter

**Please tell us about your environment:**

* **AG Grid version:** 26.1.0

Yes issue is exist in latest version also. It was not there in 23.2.1. We are facing this after upgrading to 26.1.0

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36'

* **Language:** TypeScript X.X

**Comment by Affiction** [comment]
I faced a similar problem in AG Grid version 26.2.0

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi!

This was raised as a bug and was fixed for v27.

See the change log for more details:

https://www.ag-grid.com/changelog/ 

> AG-6046 [Regression] When de-selecting any non-blank set filter item, blank values also get filtered out from the grid even though the (blanks) set filter item is selected
> 
> More Information:
> Until this is addressed, you can use a workaround which applies in cases you don't have identical values with different case:
> https://plnkr.co/edit/nHr4Zx7pvWJesVAB
> 
> If you do have the same values with different case, you'll have separate set filter items for each value (as the filter is now case-sensitive) as in COL1 in this example. However, if you don't have the same values with different case (as in COL2), this workaround helps.

I recommend updating to v27, as it is working now as expected: https://plnkr.co/edit/sbKsJNQP0H3byemM

Hope this helps, note that we will shortly be closing this ticket.

Thanks

**Comment by Affiction** [comment]
@shuheb perfect, thanks!
