### ISSUE TITLE
Row height is chainging on applying filters

### ISSUE THREAD

**Issue by Varshamathukumalli** [ag-grid/ag-grid#4905]
Hi Team,

We are using a server side row model to display data. When filter is applied on any column, it is trying to increase/decrease the row height based on the rows available before filtering. Is there any way to maintain the same row height irrespective of filters.
Below is the plunger link. On applying a filter on country Row height is increased to fit the total height when we had all rows displayed.

https://plnkr.co/edit/ZLd75BACP77c0lL8

Able to reproduce the issue in ag-grid 26.2.0 version with angular 13.

**Comment by hamuk** [comment]
I'm updating from 25.3.0 today and encountered the same issue using React. I've downgraded to 26.1.0 and that version doesn't seem to have the row height problem.

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks

**Comment by formatkaka** [comment]
> Any information on this? I'm facing similar issue.
> 
> So after some investigation it turned out this is a bug introduced in 26.2.0, so degrading to 26.1.0 or upgrading to 27.0.0 solves the issue.

thanks a ton. this helped 🚀
