### ISSUE TITLE
Frame of the selected autoHeight and wrapText cell does not cover all cell if AgGrid have 2 or more such cells

### ISSUE THREAD

**Issue by EvilMax** [ag-grid/ag-grid#4907]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- To reproduce scenario there is requirement to have 2 or more columns with **autoHeight** and **wrapText** set. The simplest way is to get official documantation example from here ( https://www.ag-grid.com/react-data-grid/row-height/ ) and add the 2nd column with wrapText and autoHeight. Funny thing: it looks like official example in docs has text generation code for 'autoC' column, but there is no that column in definition. Suggestion: that was working but broken some time, so developers decided to hide 2rd auto-column and don't show the broken scenario to users? :-)

- A plunker is there: https://plnkr.co/edit/6KV5cUs8EPPGkcYS   This is completely the example from the docs with the only difference: added third column 'autoC' to the definitions. Other code is untouched.

**Current behavior**
If AgGrid has 2 columns with **autoHeight** and **wrapText** while selecting the cells that has text content lesser than row height, frame covers only real content, not all cell. That is not an issue for non-autoHeight rows.
Clicking inside the cell, but not on the content does not select cell.

**Expected behavior**
When selecting any cell, selection frame should cover complete cell, not the only content. Clicking inside cell should select it even if clicked on empty cell area.

**Please tell us about your environment:**
Windows, react-17.0.2, react-dom-17.0.2, ag-grid-react-26.2.1, ag-grid-community-26.2.0, Chrome  97.0.4692.99 64-bit

Tested also with plunkr copied from official docs. react-16.13.1, react-dom-16.13.1, ag-grid-community-26.2.0, Chrome  97.0.4692.99 64-bit, Firefox 96.0.3 (64 bit).
Also tested JavaScript version (got from official docs and added 3rd column: autoC that is autoHeight and wrapText).

* **AG Grid version:** 26.2.0
This is currently the latest released version.

* **Browser:**
Issue reproduced with Chrome  97.0.4692.99 64-bit and Firefox 96.0.3 (64 bit).

* **Language:** all
![cellframe](https://user-images.githubusercontent.com/7696561/152581491-5e3c53b0-bb7a-4b15-b5fb-081c2b829815.png)

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as each cell has it own height

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.
