### ISSUE TITLE
Error in localisation locale.en.js

### ISSUE THREAD

**Issue by Shaent** [ag-grid/ag-grid#4909]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Providing a Reproducible Scenario**

1. Go to https://www.ag-grid.com/examples/localisation/localisation/locale.en.js
2. Copy the contents into your IDE of choice.
3. IDE should raise an error that the key "ariaLabelColumnMenu" is a duplicate.
```
Hi, I would like to submit an error I found in the documentation.

Regarding the [localisation ](https://www.ag-grid.com/angular-data-grid/localisation/) of the grid you provide this file: [https://www.ag-grid.com/examples/localisation/localisation/locale.en.js](https://www.ag-grid.com/examples/localisation/localisation/locale.en.js) but it has an error.

Line 277 and 283 have a duplicate key ("ariaLabelColumnMenu").

**Comment by gportela85** [comment]
@Shaent this has been patched in the last release. Thanks for reporting it.
