### ISSUE TITLE
Check className to not be empty before calling toggle

### ISSUE THREAD

**Issue by csicky** [ag-grid/ag-grid#4931]
Hi all,

after upgrading to version 27, I noticed that I can't give to `cellClass` and `headerClass` such strings anymore containing multiple css classes separated by space char. No problem, I refactored all our code to have array of classes. ` class-1 class-2` became `['class-1', 'class-2']`. After this big, time consuming change I get another error. Now it complains that it is empty. 
In my opinion I should be allowed to both provide a string containing spaces if I want to add multiple classes at once in string and also an empty array or empty string if this will be dynamically populated at a later time based on some logic. It shouldn't fail on such reasons. It was working without error for many years until now. 
Now that I removed all the strings with spaces in them, pls, could you just do a check and prevent this from failing if className is empty? Just put an if there. THX

![image](https://user-images.githubusercontent.com/3931907/155013452-84e80d02-9341-421f-9970-d119ddb689e6.png)

**Comment by gportela85** [comment]
Hi @csicky notice that empty style classes not being is a JS restriction, not AG-Grids. We used to have some utils that would ignore empty strings, and then this was removed in v27. In any case I have re-added this defensive code to our Utils to prevent errors when passing empty strings. This will be patched in the next release.
See: https://github.com/ag-grid/ag-grid/commit/ff7720fd8b566beb5babfa97a6fff4fa6a2193e3

**Comment by csicky** [comment]
Thank you. I understand that it comes from JS, but for me at least, it was a breaking change in a quite big project. I work on a Vue.js project and there it is normal to have variables evaluate to css class string, string with multiple classes delimited by space, object evaluating to a class based on an expression, array with class strings, or empty string, empty array, null, undefined, anything :)
Vue.js is so permissive and we are used to that. THX again for the fix.
