### ISSUE TITLE
The exported file is very large, but after saving it as a file, it becomes smaller.

### ISSUE THREAD

**Issue by qzhly1234567** [ag-grid/ag-grid#4933]
I'm submitting

Export the excel file in ag-grid, then save it in other office software (wps; Microsoft Excel) and the file size will become smaller.

Looking forward to the reply
before:
![before](https://s4.ax1x.com/2022/02/22/HxjpZt.jpg)
after:
![after](https://s4.ax1x.com/2022/02/22/HxjKoV.jpg)

Current behavior
The exported file is very large, but the file becomes smaller after saving it as a separate file.

Expected behavior
The file size exported from ag-grid is the same as the file size saved by other office software

WIN 10

AG Grid version: 26.1.0

Browser: Latest Google Chrome

Language: TS

**Comment by gportela85** [comment]
@qzhly1234567 When a file is exported using AG Grid, we create the XLSX file as a binary generated from plain text. Microsoft Excel implements an extra step that compresses the file. Implementing a compressing algorithm for Zip/Excel Files in Javascript is out of scope for Ag Grid at the moment. If you are a paying customer, feel free to file a Feature Request through the support channel.

**Comment by qzhly1234567** [comment]
Great! Thank you very much for your reply!
