### ISSUE TITLE
Unable to move columns

### ISSUE THREAD

**Issue by noook** [ag-grid/ag-grid#4934]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

We are not yet for this version, we are trying out to then purchase a licence

**Providing a Reproducible Scenario**

Here is the repository that creates the scenario:

https://github.com/noook/repro-ag-grid-column-move

**Current behavior**

We used an older version of AG Grid (23.0.1) and we wanted to see if we were able to upgrade to 27.0.1 to then repurchase another licence. A feature we were using a lot was reordering columns by dragging the headers.

Here we are unable to move columns. The ghost header moves but it doesn't reorder

**Expected behavior**

When dragging a column from the header, the columns will then reorder and fire the `onColumnMoved` event

**Please tell us about your environment:**
OS: MacOS 12.2 (21D49)
Package manager: yarn
Framework used: Vue.js 2 with Nuxt

* **AG Grid version:** 27.0.1
This is the most recent

* **Browser:**
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0"
  - 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36'

* **Language:** [vue | TypeScript 4.2.4 | ES6/7]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by noook** [comment]
With further investigation, it seems that the reason why columns can't move is linked to [this function](https://github.com/noook/repro-ag-grid-column-move/blob/master/composable/useAgGrid.ts#L218-L225)

Is there something we shouldn't do here ?

**Comment by Maratatasan** [comment]
Hello Github, 

We had a look at your code.

It appears that you were using `lockPasition: true ` in column definitions. This locks columns to their initial positions and columns can not be dragged.

please see in ag-grid.ts line 30

link to docs:  [https://www.ag-grid.com/javascript-data-grid/column-moving/#lock-position](https://www.ag-grid.com/javascript-data-grid/column-moving/#lock-position)

**Comment by noook** [comment]
> It appears that you were using `lockPasition: true ` in column definitions. This locks columns to their initial positions and columns can not be dragged.
> please see in ag-grid.ts line 30

Yes, I am aware of that, it is voluntary. However this concerns only two columns that are meant to be fixed. All the others shouldn't be.

**Comment by Maratatasan** [comment]
Hello, we are not sure what your code is doing.
But, when you lock multiple column positions the locked columns go to the left of the grid.

Please see the example: [https://plnkr.co/edit/YoL2ZsOYEP7p7ey8](https://plnkr.co/edit/YoL2ZsOYEP7p7ey8)

**Comment by noook** [comment]
Here are the column definitions generations.

See my latest commit to check how I load data in our real app. We use the `GridApi` class to set columns and row data once the grid is ready.

https://github.com/noook/repro-ag-grid-column-move/commit/a6c93fe1a45772703c3483a9f71ba37f3eb26550

Maybe it's related to `.setColumnDefs()`

```ts
function getColumnDefs (view: any): ColDef[] {
  return [
    rowNumberColDef, // This is locked
    ...hiddenIdColumnDefs, // Not locked but hidden anyway
    ...generateColumnDefsFromView(view), // Those aren't locked, and I can't move them
    CTAColumnDef // This is locked, but positioned at the right (out of flow)
  ]
}
```
