### ISSUE TITLE
Add custom menu Tab to Column Menu in addition to the default Menu tab

### ISSUE THREAD

**Issue by shan117** [ag-grid/ag-grid#4935]
I want to add custom Menu tab to column menu in addition to the default column menu tab. Is there a way to achieve this.

Currently this is a way to show default menu tabs :

menuTabs: ['filterMenuTab', 'generalMenuTab', 'columnsMenuTab'],

Is there a way to add custom menu tabs ?

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
