### ISSUE TITLE
Unable to highlight matching text when using quick filter with cellRendererFrameWork 

### ISSUE THREAD

**Issue by nithishj** [ag-grid/ag-grid#4937]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Customers of AG Grid**

**Current behavior**
Highlight matching text with quick filter works fine with CellRenderer.
There is no way to highlight matching text when using cellRendererFramework with quick filter

**Expected behavior**
Should Support a way to highlight text(with background color) when  using cellRendererFramework with quick filter

**Please tell us about your environment:**MAC OS

* **AG Grid version:** 24.0.0

* **Browser:** chrome

* **Language:** Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
