### ISSUE TITLE
implementing callback [getRowClass] results in failure

### ISSUE THREAD

**Issue by LorenzoBono** [ag-grid/ag-grid#4941]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Sample code  https://stackblitz.com/edit/ag-grid-angular-hello-world-6ozkz7

  public rowClass = (params: RowClassParams) => {
if (params?.rowIndex % 2 == 0) {
      return 'drill-down';
    } else {
      return '';
    }
  };

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

implementing callback [getRowClass] results in failure
Please check sample code on  https://stackblitz.com/edit/ag-grid-angular-hello-world-6ozkz7
`
Error in /turbo_modules/ag-grid-community@27.0.0/dist/ag-grid-community.cjs.js (25120:19)AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace. 
[Edit](https://issues.pnet.ch/secure/EditComment!default.jspa?id=690346&commentId=1043159)
[Delete](https://issues.pnet.ch/secure/DeleteComment!default.jspa?id=690346&commentId=1043159)
`

**Expected behavior**

**Please tell us about your environment:**
 https://stackblitz.com/edit/ag-grid-angular-hello-world-6ozkz7

* **AG Grid version:** X.X.X

    "ag-grid-angular": "^27.0.0",
    "ag-grid-community": "^27.0.1",

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "2.7.2",

**Comment by gportela85** [comment]
This problem has been patched in the dev branch and will be fixed in the next release. But you shouldn't really return empty strings to be used as styles. The following code should be enough.

```
if (params?.rowIndex % 2 == 0) {
    return 'drill-down';
}
```
