### ISSUE TITLE
[27.0.1] type numericColumn and rightAligned not working if enableCellTextSelection is set to true

### ISSUE THREAD

**Issue by jeremydawson** [ag-grid/ag-grid#4944]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
Similar to [4917](https://github.com/ag-grid/ag-grid/issues/4917) (AG-6405)
When we use type numericColumn or rightAligned, and if the enableCellTextSelection is set to true for the grid, the content of the cell do not align to the right. Please check the stackblitz example below. In version 26.2.0 it is working perfectly. The link to running example is also provided

Existing behaviour: columns are not right aligned. 
https://stackblitz.com/edit/ag-grid-react-hello-world-gxvu2p?file=index.js

Current behaviour.
[works fine in version 26.2.0](https://stackblitz.com/edit/ag-grid-react-hello-world-phpfmb?file=index.js)

* **AG Grid version:** 27.0.1

* **Browser:**
all

* **Language:** all

**Comment by gportela85** [comment]
@jeremydawson This issue has been patched in the dev branch and will be fixed in the next release. Thanks for reporting

**Comment by AlexWirthAAU** [comment]
Is this already published? What's the version this is fixed?

**Comment by jeremydawson** [comment]
> Is this already published? What's the version this is fixed?

It was fixed in version 27.1.0
