### ISSUE TITLE
autosizeAllColumns and sizeColumnsToFit does not work well with colSpan

### ISSUE THREAD

**Issue by HeyItsJs** [ag-grid/ag-grid#4945]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I am currently using `autoSizeAllColumns` and `sizeColumnsToFit` together with `suppressSizeToFit` in some columns for sizing the columns with best widths possible without having to mention any widths. Its working perfectly fine. Example - https://plnkr.co/edit/MY5cLwS5cdq7Smh4

However when I add `colSpan` to one of the columns, sizing dont work as expected.  Example -  https://plnkr.co/edit/yzqHIRkM0oRKW7Rc

As you can see, the `age` and `country` columns are taking more space in the second example as compared to the first.

**Expected behavior**
`age` and `country` coumns should take same space in the second example as in the first one

* **AG Grid version:** ag-grid-react:27.0.1

**Comment by icedjello** [comment]
Hi, 

Thank you for raising this. We will investigate and get back to you with our findings as soon as possible. 

Thanks again.

**Comment by HeyItsJs** [comment]
Hey @chefnoname, @makinggoodsoftware

Using any values for width, minWidth or maxWidth is not an option for me, since the columns in my application are dynamic. 

Can we please reopen this issue if it can be fixed in the ag grid codebase itself?
