### ISSUE TITLE
fullWidthCellRenderer not rerendering on context update

### ISSUE THREAD

**Issue by HeyItsJs** [ag-grid/ag-grid#4946]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Normal cellRenderers are called again when grid `context` is updated. However `fullWidthCellRenderer` does not gets called whenever `context` is called. 

* **AG Grid version:** ag-grid-react 27.0.1

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
