### ISSUE TITLE
In scan mode, pinned columns are associated with incorrect headers.

### ISSUE THREAD

**Issue by sofisa16** [ag-grid/ag-grid#4952]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
1. When using NVDA version 2021.3.3  (https://www.nvaccess.org/download/) with the  Tools>Speech Viewer option, the pinned column and others have a wrong column name or row number or information.
![image](https://user-images.githubusercontent.com/14502698/156247055-ac1a332b-cab3-4651-aed9-95fc1a4d40a3.png)

**Expected behavior**
1. When using NVDA version 2021.3.3  (https://www.nvaccess.org/download/) with the  Tools>Speech Viewer option, the pinned column and others should speak and write something helpful for the user. I do not know in which format and order, but something that is true to what we see.

**Please tell us about your environment:**
_This bug can be reproducible in https://stackblitz.com/edit/ag-grid-react-hello-world-pgtfgd?file=package.json_

* **AG Grid version:** 24.1.0
_You can check the package.json of the example for more info, but here it is
"ag-grid-community": "24.1.0",
"ag-grid-react": "24.1.0",_

* **Browser:**
_'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36'_

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React. but you can check the package.json.

**Comment by gportela85** [comment]
@sofisa16 This issue has already been reported to NVDA. Apparently the attributes aria-colindex and aria-rowindex are being ignored. When the elements in the dom are out of order, the screen reader should use these attributes to make sense of its position, but it doesn't do that.
I have filed a ticket for a similar scenario, related to Column Groups but no one has answered so far - https://github.com/FreedomScientific/VFO-standards-support/issues/401
