### ISSUE TITLE
Whole tree view button is closed using 'esc' key instead of closing 'pin column' pop-up.

### ISSUE THREAD

**Issue by sofisa16** [ag-grid/ag-grid#4953]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
1. Click on the hamburger button in the header or 'Ahift+Ctrl+Enter key'.
2. Go to Pin Column, then go through the options but not press anything else.
![image](https://user-images.githubusercontent.com/14502698/156264209-8c83dde7-1e98-4469-b560-6fae34eda5a0.png)
4. Press 'ESC' key.
5. Verify that the 'Pin Column' pop-up is closed using 'ESC' key or the whole tree view button is closed.

**Expected behavior**
1. Instead of closing all the tree view button, just the 'Pin Column' pop-up should be closed.

**Please tell us about your environment:**
_I tested the bug in https://www.ag-grid.com/react-data-grid/column-headers/_

* **AG Grid version:** X.X.X
_I tested the bug in https://www.ag-grid.com/react-data-grid/column-headers/_

* **Browser:**
_'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36'_

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React.

**Comment by gportela85** [comment]
@sofisa16 This isn't how floating menus work. Check any Operating System's context menu by right clicking the Desktop background, navigate the menu and press `ESC`, the whole menu closes. To close a submenu, simply press the `left arrow` key.
