### ISSUE TITLE
Does Version19.1.4 support for Excel Export - Formulas?

### ISSUE THREAD

**Issue by lujuliang** [ag-grid/ag-grid#4954]
Dear team, 
Now our angular application have two dependencies :
    "ag-grid-community": "^19.1.0",
    "ag-grid-enterprise": "19.1.4",
I set the returned value as '=DATE(2022,2,2)' in processCellCallback function, but got =DATE(2022,2,2) in exported excel cell.
I tried dataType='Formula' and autoConvertFormulas=true , both failed.
Could anyone kindly help me to check  whether this version supports for Formulas?
Thank you.

**Comment by gportela85** [comment]
No, if you check https://www.ag-grid.com/changelog/ you will see that Formulas export was only added in v25.2.0 by AG-2303
