### ISSUE TITLE
When will you publish AG-6393?

### ISSUE THREAD

**Issue by csicky** [ag-grid/ag-grid#4957]
Hi, I am waiting for this fix **AG-6393** in order to be able to publish our code using version 27, but it doesn't seem to want to move from the pipeline into the change log.
Would it be possible in the pipeline page to have a bit of info about when will the publishing happen?

THX

**Comment by gportela85** [comment]
It will move from the pipeline to the changelog in the next release, the ticket has already been fixed in the dev version.

**Comment by csicky** [comment]
> It will move from the pipeline to the changelog in the next release, the ticket has already been fixed in the dev version.

I know it was fixed. I know it is in pipeline. I want to know when will be in the changelog. When will the release happen? In a day, week, month?

**Comment by StephenCooper** [comment]
The next version of AG Grid which will address this issue is currently scheduled for release before March 18th.
