### ISSUE TITLE
Columns header groups should group when they share the same name

### ISSUE THREAD

**Issue by noook** [ag-grid/ag-grid#4958]
**I'm submitting a ...**
```
[x] bug report
[?] feature request
[] support request
```

**Providing a Reproducible Scenario**

Plunker link: <https://plnkr.co/edit/RvFWP0DKtG5TOXFp>

**Current behavior**

When using Column Groups, if a column group is splitted in 2 groups with the same name, with another between them, and that we move the oclumns back to the original group, they are not merged

**Expected behavior**

If I create 3 groups, whose 2 of them share the same name they should merge into the same on the rendering.

If I create 3 groups, and the first and third have the same name, if I move the columns from the last group to the first group by drag and dropping them, they should group

**Please tell us about your environment:**

Not relevant, but MacOS, Firefox, Yarn

* **AG Grid version:** X.X.X
`27.0.1`

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0"

* **Language:** [vue | TypeScript 4.2 | ES6/7]

**Comment by noook** [comment]
After thoughts, I guess this must be a feature and not a bug, but I believe the merging strategy is maybe a little bot *too* naive. I mean, that if I have several columns that belong to the same group, but one of them has a very specific position in the columns list, but if we reorder them it won't be merged.

I guess the only workaround for now is to rebuild the groups every time the columns are dragged to change the column orders.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
