### ISSUE TITLE
How to use `RichSelectModule` with `masterDetail`

### ISSUE THREAD

**Issue by nicodes** [ag-grid/ag-grid#4959]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

### Package versions
```
"ag-grid-community": "^27.0.1",
"ag-grid-enterprise": "^27.0.1",
"ag-grid-react": "^27.0.1",
```

### Description
Is there a similar feature to `RichSelectModule` when using `masterDetail`? I am trying to implement the select logic from this [example](https://www.ag-grid.com/react-data-grid/reactui/#advanced-grid-features) but I am using `masterDetail` instead of `grouping`. Specifically I would like the functionality of a parent row checkbox being able to toggle all child checkboxes within it's `masterDetail`. Does the `RichSelectModule` module support non-grouped `masterDetail` selection handling? Or is there another module that does?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
