### ISSUE TITLE
Select all checkbox also selects rows without checkbox

### ISSUE THREAD

**Issue by Katrijne** [ag-grid/ag-grid#4962]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I created a grid in which the first column is a checkbox column: 
Column defs for this column:
            {
                headerName: '',
                checkboxSelection: this.hasCheckbox,
                field: '',
                sortable: true,
                width: 10,
                headerCheckboxSelection: true,
                headerCheckboxSelectionFilteredOnly: true,
            },

this.hasCheckbox is a function that returns true/false depending on some other value in the object used to populate the according row.
This results in a table where some rows have a checkbox and some don't.
As headerCheckboxSelection is true, there is a 'select all' checkbox in the header of the checkbox column.
When I click this 'select all' I get all rows (with and without checkbox) in the selectionChanged event.
I would expect only the rows with a checkbox are returned.

**Versions**
    "ag-grid-angular": "^23.2.1",
    "@angular/core": "^8.2.14",

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
