### ISSUE TITLE
How to Use Ag-Grid-React in a React CDN App

### ISSUE THREAD

**Issue by oosharma** [ag-grid/ag-grid#4965]
[x] support request 
 
**Requesting Community Support**
 
**Providing a Reproducible Scenario** 
CodePen: https://codepen.io/oosharma/pen/OJzLBKg
Plunker: https://plnkr.co/edit/MAdOgmz2f5fMtnNG?open=lib%2Fscript.js

**Description** 
I want to use Ag Grid React as a CDN, and I have the following setup on codepen as a sample to what's in my local project: https://codepen.io/oosharma/pen/OJzLBKg

When trying to load a basic <AgGridReact.AgGridReact> component, I am getting the error at ag-grid-react.min.js:1 - Uncaught TypeError: Cannot read properties of undefined (reading 'bool')

Here is the Plunkr code copied here-

 ```
// HTML 
<script src="[https://unpkg.com/react@17/umd/react.development.js"></script](https://unpkg.com/react@17/umd/react.development.js%22%3E%3C/script)>
<script src="[https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script](https://unpkg.com/react-dom@17/umd/react-dom.development.js%22%3E%3C/script)>
<script src="[https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.24.0/babel.js"></script](https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.24.0/babel.js%22%3E%3C/script)>
<script src="[https://cdnjs.cloudflare.com/ajax/libs/ag-grid/Docs-27.0.1-20220211/ag-grid-community.min.js"></script](https://cdnjs.cloudflare.com/ajax/libs/ag-grid/Docs-27.0.1-20220211/ag-grid-community.min.js%22%3E%3C/script)>
<script src=" [https://unpkg.com/ag-grid-react@23.0.0/umd/ag-grid-react.min.js"></script](https://unpkg.com/ag-grid-react@23.0.0/umd/ag-grid-react.min.js%22%3E%3C/script)>

<div id='root'></div>
```
```
// JSX
const App = () => {
const [rowData] = [
{ make: "Toyota", model: "Celica", price: 35000 },
{ make: "Ford", model: "Mondeo", price: 32000 },
{ make: "Porsche", model: "Boxter", price: 72000 }
];

return (
<div className="ag-theme-alpine" style={{ height: 400, width: 600 }}>
<AgGridReact.AgGridReact rowData={rowData}>
<AgGridReact.AgGridColumn field="make"></AgGridReact.AgGridColumn>
<AgGridReact.AgGridColumn field="model"></AgGridReact.AgGridColumn>
<AgGridReact.AgGridColumn field="price"></AgGridReact.AgGridColumn>
</AgGridReact.AgGridReact>
</div>
);
};

let domContainer = document.querySelector("#root");
ReactDOM.render(<App />, domContainer);
 
```
**Please tell us about your environment:**
CodePen: https://codepen.io/oosharma/pen/OJzLBKg

* **AG Grid version:**  
27.0.1  
* **Language:** 
ES6

**Comment by oosharma** [comment]
Thanks so much, this worked!

**Comment by ShivanandPrajapati** [comment]
I am updating my Ag Grid with the latest CDN of the Ag Grid 33.0.2 version but getting error, Please guide me

**Comment by sabahang** [comment]
@ShivanandPrajapati please submit a new issue with complete information about the error you are getting. Thanks
