### ISSUE TITLE
[ReactUI] -  v27.0.1 - CellEditor is broken when `enableCellTextSelection` is set to true

### ISSUE THREAD

**Issue by wangJacker** [ag-grid/ag-grid#4972]
This is a screenshot of the document! 
![image](https://user-images.githubusercontent.com/33062942/158289525-2fda192e-10dc-4367-92d1-13e1b5d44e37.png)
https://www.ag-grid.com/react-data-grid/clipboard/?#example-cellTextSelection

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by spyro2000** [comment]
WTF. Why is this closed? This ist just broken right now (at least in v27).
**enableCellTextSelection should be defaulted to FALSE** according to [documentation](https://www.ag-grid.com/angular-data-grid/grid-options/#reference-selection-enableCellTextSelection).

**In fact, it is set to TRUE.** This results in several bugs:

- Cell selection is behaving weird, interferes with browser selection of text elements
- CTRL+C is not working for selected cells (despite it being displayed as alternative in context menu)

You have to explicitly set `enableCellTextSelection: false` in each grid options  to fix this, despite this should be the default.

**Comment by wangJacker** [comment]
Thank you very much for your reply!

**Comment by rmc-software** [comment]
AG-6982 has been picked up and will be included in our next release v28.1 (3 Aug)
