### ISSUE TITLE
Change date filter placeholder react

### ISSUE THREAD

**Issue by manuTro** [ag-grid/ag-grid#4974]
Is it possible to change the date filter placeholder from `dd/mm/yyyy` to `yyyy-mm-dd` (React)?

Thx
![Screen Shot 2022-03-15 at 09 31 21](https://user-images.githubusercontent.com/25326470/158337796-a8fd2ae6-cca1-4740-bc6c-4abccc0d2435.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by AG-Zoheil** [comment]
Hi @jfstephe,

Thank you for your comment.

You can edit the placeholder text if that's all your after. See this example: https://plnkr.co/edit/QRwCc2lZ7N0LuqzW?open=main.js.

However the input will not work with your defined format and for that we do indeed have a FR in our backlog already with the following reference: **AG-3735**.

I have now added the label to this issue for visibility.

Kind regards,
Zoheil
