### ISSUE TITLE
gridCell.column.isPinned is not a function

### ISSUE THREAD

**Issue by zohre1023** [ag-grid/ag-grid#4977]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hi I am using ag-grid in my project and I have and sometimes in inline add, I have this Error in console
Uncaught TypeError: gridCell.column.isPinned is not a function

* **AG Grid version:**26.2.0

* **Browser:** All browser

* **Language:** [javascript | react 17.0.1 | ES6]

#managed-by-the-community

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
