### ISSUE TITLE
Angular : In dark theme checkbox is not visible.

### ISSUE THREAD

**Issue by pancham0** [ag-grid/ag-grid#4994]
We are using  - @ag-grid-community/angular": "^24.0.0",

When we switch to dark mode, we're not able to view the checkbox properly. The checkbox is not getting displayed clearly, hence giving an accessibility issue. Please check and resolve the query as soon as possible. Thanks in advance.

![Inkedss_LI](https://user-images.githubusercontent.com/102021037/159231342-ad8d1d44-389a-4270-a9d2-f0f64cc3a1db.jpg)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
