### ISSUE TITLE
Vue - autoSizeColumns is not working for every column

### ISSUE THREAD

**Issue by lukasmuller10** [ag-grid/ag-grid#4999]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I used the example shown in https://www.ag-grid.com/vue-data-grid/column-sizing/, where a function to autosize columns is created.

```
autoSizeAll(skipHeader) {
      const allColumnIds = [] as any;
      this.gridColumnApi.getAllColumns().forEach((column) => {
        allColumnIds.push(column.getId());
      });
      this.gridColumnApi.autoSizeColumns(allColumnIds, skipHeader);
    },
```
But only the first 13 columns are being impacted with this function, and not all of then(in my grid there are 16 columns). If i change the order of one of the last columns to be in the first 13th, if becomes autosizable.

**Expected behavior**
All columns should be autosizable.

* **AG Grid version:** "ag-grid-vue": "^25.3.0"

* **Browser:**
Chrome

* **Language:** TypeScript

**Comment by jgomesmv** [comment]
I was faced with this problem and I would like to kindly ask if this would be possible as an improvement:

1. We could set a grid property to autosize the column widths based on it's content eg: `autosizeColumns: true`
2. When user horizontally scrolls that event should be handled by aggrid and should automatically trigger the remaining columns to autozise
3. Only the columns not autosized yet should be changed. The ones previously changed by the autosize logic or by user with manual drag should be ignored
4. It should only apply autosize in the first dataset / rows rendered

For `sizeToFit` a grid option could also be available.

This would keep all the benefits of virtualization and a nice UX as the user would see the first rows rendered with nice column sizes

**Comment by xiaokunhou** [comment]
Since the auto height is supported now, what would be the expected behavior when auto height + autosizeColumns?

Would be 
1. Calculate a general good width with the displayed rows.
2. Auto height when scrolling up and down?
