### ISSUE TITLE
After updating to v27, setFilterModel not working for server side filtering

### ISSUE THREAD

**Issue by ankitav14** [ag-grid/ag-grid#5000]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => After updating to v27, setFilterModel not working for server side filtering
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

For server side filtering, onFilterChange function, setting the filter using setFilterModel
But No API call is being made when filter is changed after updating the aggrid to v27. 

We then added serverSideStoreType="partial" property to grid and filtering started working
but now if we the filter is default set to a page, grid shows correct filtered list based on api result but on clearing this default set filter does not call api and hence does not show updated list. the grid just retains data from the original default set filter

**Expected behavior**
filtering should work normally if the filter was set by default when user first lands on page

**Please tell us about your environment:**
MacOS, Visual Studio, react, aggrid v27, https

* **AG Grid version:** 
* version 27.0.1

* **Browser:**
* Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
