### ISSUE TITLE
 Make sure than one component's selector can match a given element

### ISSUE THREAD

**Issue by Jaswanth451** [ag-grid/ag-grid#5006]
while trying to call ag grid component getting the following error
More than one component is matched on this element
 Make sure than one component's selector can match a given element.
Component conflicts is happening for aggridangular ...

**Comment by StephenCooper** [comment]
Could you share some code or a reproduction to help us understand the issue?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
