### ISSUE TITLE
Angular: Extend the typing for the event componentStateChanged

### ISSUE THREAD

**Issue by simonljus** [ag-grid/ag-grid#5007]
**I'm submitting a...
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Path: /projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
The event is of type `ComponentStateChangedEvent` but  is missing `SimpleChanges` object from `ngOnChanges`

**Expected behavior**
The event could be of type
``` TypeScript
ComponentStateChangedEvent & SimpleChanges
```
**Please tell us about your environment:**

* **AG Grid version:** 27.1.0
* **Language:** Angular & Typescript

**Comment by StephenCooper** [comment]
I can see that there is room for improvement on this events typing. However, as this is a shared event across all frameworks it is unlikely at this point in time that we can use the Angular SimpleChanges interface. 

Your best bet is to apply the typing  `ComponentStateChangedEvent & SimpleChanges` to your event handler. This compiles and gives the required typing support that I believe you are after?

```ts
  onCompChange(event: ComponentStateChangedEvent & SimpleChanges){
    event['propertyName'].isFirstChange();
  }
```
