### ISSUE TITLE
React: Floating filter not updated with selections when set filter values are provided asynchronously and setFilterModel is called on grid ready 

### ISSUE THREAD

**Issue by 4xemme** [ag-grid/ag-grid#5012]
I have some columns having a multifilter with textColumnFilter and setColumnFilter
The values for the setColumnFilter are retrieved asynchronously through an api call
On grid ready I'm trying to restore a previously cached filter model using setFilterModel
The filter is applied correctly and I see the api call for retrieving all unique filter values fired
But the floating filter is not updated reflecting the list of selected items (it stays empty)
I noticed everything is set correctly if I rebate the setFilterModel after the api has fetched the filter values

The filter stays empty

[
![image](https://user-images.githubusercontent.com/24910111/159754956-1cd4fd44-41c4-4f80-8371-bdbf5289bb64.png)
](url)

After rebating setFilterModel once the items has been loaded it reflects the selection

[
![image](https://user-images.githubusercontent.com/24910111/159754575-4fd9061d-2f51-479a-9c4e-dbacbcfe6588.png)
](url)

I'm using the server side model

I'm on version 26.1.0
Browser Edge & Chrome

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
