### ISSUE TITLE
Nested Grid inside a single cell

### ISSUE THREAD

**Issue by tarushreeS** [ag-grid/ag-grid#5013]
**I'm submitting a ...*support request*  (check one with "x")
```
**Requesting Community Support**

I need to understand if there is a way to have a nested grid inside a single cell using ag-grid angular.
If yes, what would be the cost associated with it?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
