### ISSUE TITLE
[Request] allow row dragging even when sorting is applied.

### ISSUE THREAD

**Issue by rosostolato** [ag-grid/ag-grid#5015]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I manually do sorting in my app. All of my colDefs have `comparator: () => 0`, so I listen for sort event, sort my data array and provide it back for ag-grid to render. In this case, dragging will work even when sorting is applied.

My request is to have an option to not hide the drag handler icon. I know I can override it with CSS, but when I do that, all other dragging animations continue disabled.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

In any case, we appreciate the feedback.

Please keep an eye on our pipeline as this might appear there.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks for your feedback

____


If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
