### ISSUE TITLE
HeaderName is "." ，column  is blank!!

### ISSUE THREAD

**Issue by WangTopSoft** [ag-grid/ag-grid#5017]
Current behaviour.
I found that if the HeaderName is ".", Column is blank. If it is other special characters, such as "* @", there is no problem. Are there any other solutions?
![image](https://user-images.githubusercontent.com/38515049/160046313-cf4af501-a9dc-43b5-9f8b-2bb0efa88f8d.png)
![image](https://user-images.githubusercontent.com/38515049/160046357-954af70a-3b21-4174-876c-a1b087ed7869.png)

"."  is  blank,,"#" is ok!

**Expected behavior**
The special character "." is expected to be supported

**Please tell us about your environment:**
os: windows
ag-grid: 27.1.0
browser: google
Language: es5 ,react

**Comment by supervitas** [comment]
More over, columns with dot, also blank.
Like `testing.dot-column` would not display any data for this column

**Comment by StephenCooper** [comment]
I think you need to set the `suppressFieldDotNotation`  on your grid options to stop `.` being interpreted as deep references.

https://ag-grid.com/javascript-data-grid/grid-properties/#reference-columns-suppressFieldDotNotation

**Comment by WangTopSoft** [comment]
ok , thank you !
