### ISSUE TITLE
Why should we use useMemo, useState for static objects

### ISSUE THREAD

**Issue by fzkirablackwhy** [ag-grid/ag-grid#5018]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello! 
I'm very interested, why do you recommend to use useMemo and useState for static objects.
https://www.ag-grid.com/react-data-grid/react-hooks/#object-properties-vs-simple-properties
Can I just use closure, like this?
<img width="992" alt="image" src="https://user-images.githubusercontent.com/15785413/160092134-a6772166-1ff7-4cca-ba70-c9d083873383.png">

**Comment by tbjerknes** [comment]
Declaring your component object outside of the Table component should work find I would guess, as it is only created once
