### ISSUE TITLE
ColDefs with flex attributes cause resize flashing

### ISSUE THREAD

**Issue by TuringJest** [ag-grid/ag-grid#5022]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

https://plnkr.co/edit/tNvJaFKFKP5CPqsD?preview

**Current behavior**
Column widths with a flex setting are calculated by the grid after initial render, which causes layout flashes.
As fas as I can tell this happens in the Vue, React, Angular and Js version.

**Expected behavior**
The grid should calculate widths of cols in view before the columns are rendered, or at least do this if col virtualisation is turned off as a first step.

* **AG Grid version:** 27.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by TuringJest** [comment]
I can only say that it doesn't look good. Especially, when we switch between pages/tabs with different tables/ content. 

We have looked at the following solutions but they are not very viable:
1. Use a loader to cover the table for a certain duration. Very unclean and especially annoying for us as we have layouts with a table in a tab which is kept alive to avoid any reloading when switching tabs. 
2. Don't use the flex attribute. That's what we do now, we calculate col widths based on the table width beforehand. Might be similar to what the grid is doing, but if we set the width ourselves it will conflict with other features of ag-grid.

**Comment by Akrion** [comment]
@makinggoodsoftware any chance you could elaborate on "note that we don’t think this is a bug, as the system works as expected in this area."? 

We are enterprise customer and I guess I can go over to the Zendesk channel but this is the first thing that pops up in Google and it would be nice to know the argumentation vs dealing with Zendesk IMO.

**Comment by alex20044** [comment]
This is definitely an issue, hoping to get a fix for this soon.

**Comment by StephenCooper** [comment]
Thanks for bumping this ticket as we have been actively working in this area of the grid and believe that we should have this resolved / greatly improved for our next release of 29.3.

I have tested the above plunker against our test environment and there is no visible flicker with it anymore. We just need to ensure our changes don't have any other unwanted side effects before fully committing to 29.3.

**Comment by mildrenben** [comment]
Just adding to agree this is a really ugly issue

**Comment by StephenCooper** [comment]
> Just adding to agree this is a really ugly issue

Yep we are aiming to resolve this in 29.3.

**Comment by JohnKis** [comment]
Can I ask whether the improvements have been released with 29.3? I tried it in our app and while it's better (e.g.: the scroll position is restored at the end) there's still a flicker when the list of the columns change.

**Comment by JohnKis** [comment]
Thanks for the quick reply!

As suggested, I'll open a separate ticket.

**Comment by bswan0002** [comment]
I posted a nice fix for `ag-grid-react` users here: https://github.com/ag-grid/ag-grid/issues/9959#issuecomment-2899349254

**Comment by robdodson** [comment]
I was hitting this issue in 33.3.2 when I used `initialState` to try to set the `sortModel` for my grid. I found that I was able to work around it by not using `initialState` but instead using a helper on my column definitions.

```tsx
// Column Definitions: Defines & controls grid columns.
// Helper function to create a column with initial sort
const createColumn = (config: Omit<ColDef, 'sort'>): ColDef => ({
  ...config,
  // initialSort is calculated earlier by the component when it grabs the URL SearchParams
  sort: initialSort?.colId === config.field ? initialSort!.sort : undefined,
})

const [colDefs] = React.useState<Array<ColDef>>([
  createColumn({
    field: 'accountName',
    headerName: 'Account',
    cellRenderer: (params) => params.value,
  }),
  //...
])

// Apply settings across all columns
const defaultColDef = React.useMemo<ColDef>(() => {
  return {
    flex: 1,
  }
}, [])
```
