### ISSUE TITLE
In ag-grid How to add an attribute for showing/hiding a MenuItem given a condition?

### ISSUE THREAD

**Issue by ramaeon3** [ag-grid/ag-grid#5033]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

When a MenuItem is added either to the ContextMenu or ColumnMenu, I would like an attribute for showing or hiding the element given a condition. Expected behavior: For instance: MenuItem

{
name: "Alert " + params.value,
shown: true // an attribute like this!
disabled:false;
action: function() {
window.alert("Alerting about " + params.value);
},
}

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
