### ISSUE TITLE
Is there a way to exit grid programmatically?

### ISSUE THREAD

**Issue by EvilMax** [ag-grid/ag-grid#5045]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

Dear Ag-Grid community. Is there a way to exit Ag-Grid programmatically? In other words, I need to make it unfocused. And I don't have inputs in markup to focus them - jsut need to deactivate my grid, blur it. However AgGrid **has no blur() method**. I need that for activating custom menu in the floating block outside the div and navigate there by keyboard. Currently when I navigate that menu I see grid cells navigation in parallel - want to prevent it while that menu is active.

I tried to use **clearFocusedCell()** function from a grid API (see https://www.ag-grid.com/react-data-grid/grid-api/#reference-navigation)
It clears selection from the current cell, but grid still remains active and reacts on keybaord events and navigates over cells. So after pressing navigation key focus returns - that is witness of grid remaining active.

Now I'm thinking about work-around related to temporarily suppressing keyboard navigation then enabling but that also problematic: don't know how to check if we already entered a grid or exit and any events on it - in some moment we may require to return to the grid and continue navigation.

Is there solution that allows to exit the grid?

**Please tell us about your environment:**

Windows 10 Pro, IDEA, npm, nginx

* **AG Grid version:** 26.2.1 community + ag-grid-react 26.2.0

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
