### ISSUE TITLE
[test] Automate running the manual regression tests

### ISSUE THREAD

**Issue by S-YOU** [ag-grid/ag-grid#506]
Not really a issue, but do you need automatic builds test like travis?
https://travis-ci.org/S-YOU/ag-grid/builds

if so, I could submit PR or you could grab the file here.
https://github.com/S-YOU/ag-grid/blob/travis/.travis.yml

one limitation, DefinitelyTyped repo is so hot and always triggered github's rate limit when travis CI accessed, so `gulp tsd` cannot able to run and you need to put typings folder in the repository too.

**Comment by ceolter** [comment]
maybe!! i'll leave this issue open to come back to it, but for now i don't have the time to look into it :(

however, for the build breaking, i'd expect someone to test what they write at least once themselves manually, i do the build and test it in a browser. so build issues should be caught as part of that process.

**Comment by S-YOU** [comment]
> maybe!! i'll leave this issue open to come back to it, but for now i don't have the time to look into it :(

ok, sure. I am also still doing some experiments too.

**Comment by ceolter** [comment]
what's the best way to chat to you offline @S-YOU? are you on the ag-Grid forum? if so, what's your username?

**Comment by S-YOU** [comment]
in forum, i am *YOU*, or send me email at `stackexchange.you@gmail.com` (I will remove this email once you read this)

**Comment by S-YOU** [comment]
I am at forum with handle `YOU`. or you can send me email stackexchange dot you at gmail dot com. my timezone UTC+9, may be other side of the world.

**Comment by S-YOU** [comment]
did you got my msg here? I posted my email and post looks gone?

**Comment by AkosLukacs** [comment]
Definitely :+1: this, as for example at line https://github.com/ceolter/ag-grid/blob/master/src/ts/gridApi.ts#L15 the missing `{  }` actually breaks my build (using typescript)
(fixed at the v.3.4 branch, do you have an ETA about 3.4?)

I guess you don't have any code that checks the type of exactly that parameter, so wouldn't matter in this case, but would be a start & safety net....

**Comment by ceolter** [comment]
@AkosLukacs release of 3.4 will hopefully be monday next week - assuming all goes to plan, so much stuff to tie up as it's a big release.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-75

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
