### ISSUE TITLE
setup can't get props.params

### ISSUE THREAD

**Issue by linkaiqiyi** [ag-grid/ag-grid#5060]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I use vue2 with compositionApi. I cannot get `props.params` in the `setup` (cellRenderer).
```
export default Vue.extend({
     setup(props) {
        console.log(props.params) // This is undefined
    }
})
```

**Please tell us about your environment:**

* **AG Grid version:** 25.0.0

* **Vue Version:** 2.5.17

* **composition-api Version:** ^1.4.4

* **Language:** ES6

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
