### ISSUE TITLE
Header checkbox selection used while filtering doesn't work as expected if filter is removed

### ISSUE THREAD

**Issue by ahmadi3d** [ag-grid/ag-grid#5064]
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

Current behaviour.
Header **select all checkbox** doesn't select only the filtered items but all the items

**Current behavior**
1- set headerCheckboxSelection and filter to true for column def
2- choose a column and filter the rows
3- use the header checkbox selection to select all the filtered rows
4- remove the filter
you can see that all the items are selected even the ones outside the filter

**Expected behavior**
I expected that upon removing the filter only the items inside the filtered version remain selected, not all the items

* **AG Grid version:** X.X.X
AG Grid 27.0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React JS 16.4

**Comment by ahmadi3d** [comment]
Here is a reproducible example showing this bug
go to the example, filter on 'A1' then use select all, now remove the filter, you can see 'A2' is also selected!
https://codesandbox.io/s/aggridfilterbugexample-uwbqjv?file=/src/App.js

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 

The behaviour you are after is already documented here: 

https://www.ag-grid.com/javascript-data-grid/row-selection/#example-just-filtered 

I've forked and altered your example to illustrate how you can achieve this effect: 

https://codesandbox.io/s/aggridfilterbugexample-forked-fv8pg0?file=/src/App.js 

I hope this helps,

**Comment by Jungho-Cheon** [comment]
Here's a link for people using older versions.

https://www.ag-grid.com/archive/26.2.0/react-data-grid/row-selection/#select-everything-or-just-filtered
