### ISSUE TITLE
Ag grid custom pagination option is missing

### ISSUE THREAD

**Issue by sajuravindran** [ag-grid/ag-grid#5074]
In the application I have been working need to have a customize pagination option , so that the user can select how many records / page he want to display in the grid. Currently the ag community version has the option to place a dropdown to change the page size dynamically is available. This makes a call to paginationSetPageSize(newPageSize). So do we have any option available to display the custom pagination option along with the autopagination controls coming in the grid footer?. Please help.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
