### ISSUE TITLE
CellRendererFramework not honoring state updates of local variables

### ISSUE THREAD

**Issue by njain9104** [ag-grid/ag-grid#5092]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

1. Create a CellRenderer, which renders different cells based on different fields.
2. Add a local state which is used as a dependency in the cell renderer.
3. Trigger an event which causes the cell update and refresh the cells.

Cell Renderer is not honoring the latest local state and view is rendered based on older state

**Expected behavior**
Cell Renderer should honor the latest local state value

Reproducible Link:
https://codesandbox.io/s/distracted-http-con5xv?file=/src/App.js

Steps to Reproduce
1. Click the button which toggles the state value of readOnly from true to false and false to true
2. Once it updates, api.refreshCells is called, which triggers the CellRenderer
3. Notice the value of readOnly
Added console.logs to show the state locally and in CellRenderer

**Please tell us about your environment:**
OS: Windows, IDE: VS Code, Package Manager: npm

* **AG Grid version:** 27.1.0

* **Browser:**
Google Chrome

* **Language:** [all]

**Comment by seanlandsman** [comment]
For your use case you could remove the `useEffect` and replace the `columnDefs` with a `useMemo`: https://codesandbox.io/s/adoring-frost-e28e39?file=/src/App.js

**Comment by njain9104** [comment]
Hey @seanlandsman  I will try to replace with useEffect with useMemo, but is there any reason why useEffect does not work and useMemo works?

**Comment by makinggoodsoftware** [comment]
Hi,

The reason to need useMemo its explained here:

https://www.ag-grid.com/react-data-grid/react-hooks/

Hope this helps!

**Comment by njain9104** [comment]
Hey @makinggoodsoftware I went through the above documentation, 

Quoting from the same it says that _It makes sense to use useState if your application intends changing Column Definitions and to use useMemo if your application does not change Column Definitions._

In the attached codesandbox: https://codesandbox.io/s/distracted-http-con5xv?file=/src/App.js, we are using setState and update columnDefs and we are refeshing cells too. But this doesn't update the cell value. 

I Request you to look into this again as we won't be able to use useMemo in the above use case

Thanks
Regards
Ajay
