### ISSUE TITLE
@ag-grid-community/client-side-row-model Sourcemap link is broken

### ISSUE THREAD

**Issue by omerman** [ag-grid/ag-grid#5100]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6780529/163873577-1548f3cf-8ce7-48be-8f42-3257d2786c79.png">

The npm package (Version - 27.1.0) does not export the path selected `../../../src/main.ts`
Therefor I get the following error on my React project:

```
WARNING in ./node_modules/@ag-grid-community/client-side-row-model/dist/esm/es5/main.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/.../node_modules/@ag-grid-community/client-side-row-model/src/main.ts' file: Error: ENOENT: no such file or directory, open '/Users/.../node_modules/@ag-grid-community/client-side-row-model/src/main.ts'
```

Attached full file structure of the npm package:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/6780529/163874296-92e3534a-5aa0-4cb6-b1ba-5feccee13581.png">

Thanks in advance :)

**Comment by StephenCooper** [comment]
Thanks for reporting. Linking to existing issue https://github.com/ag-grid/ag-grid/issues/5039
