### ISSUE TITLE
Homepage Link in Packages is Insecure

### ISSUE THREAD

**Issue by FlorianWendelborn** [ag-grid/ag-grid#5123]
**I'm submitting a ...**
```
[x] bug report
```

**Providing a Reproducible Scenario**

1. See <https://github.com/ag-grid/ag-grid/blob/d13097e7e26632f617a111bf5c7e0a42d8a2f059/community-modules/core/package.json#L54>
2. Notice that the URL doesn’t use HTTPS

**Current behavior**

All `package.json` links to the homepage are using HTTP and are therefore insecure.

**Expected behavior**

All `package.json` links to the homepage are using HTTPS and are therefore more secure.

* **Please tell us about your environment:** N/A

* **AG Grid version:** 27.2.1

* **Browser:** N/A

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that we made this change, and that this will be reflected in our next release

Thank you for raising this with us!
