### ISSUE TITLE
Rendering empty list with buttons

### ISSUE THREAD

**Issue by Dhaxor** [ag-grid/ag-grid#5134]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
I have just one item but it is showing a long list of cell rendered buttons
![image](https://user-images.githubusercontent.com/46064597/166175356-8d8df2fd-4ce8-4e4a-b9ea-659b350a24fb.png)

**Expected behavior**
 It should just show one item in the table.

**Please tell us about your environment:**
Operating system - Ubuntu
IDE - vscode
package manager -npm

* **AG Grid version:** X.X.X
ag-grid-vue : "^26.2.0",

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* Typescript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
