### ISSUE TITLE
Server-Side Row Model aggregate grouped columns

### ISSUE THREAD

**Issue by jgomesmv** [ag-grid/ag-grid#5137]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
I would like to know if it's possible to apply aggregate functions on top of grouped columns.
The end result should be:
1. Group by a column
2. Apply an aggregated function on the same column

I'm able to do the server side request correctly. But I'm not able to correctly pass the row data with group and aggregation values in order to display them. 

Example: https://plnkr.co/edit/g1HIe00kKKBiqwzO?open=app%2Fapp.component.ts

* **AG Grid version:** 27.1.0

* **Language:** TypeScript 4.6.3

**Comment by jgomesmv** [comment]
@vamshiqapita unfortunately no. The documentation lacks a proper example to handle this operation

**Comment by vamshiqapita** [comment]
Oh, I see! Please comment if you got to know approach, will do the same from my end, thanks!
