### ISSUE TITLE
Range Paste on Windows Clears Cell Underneath Row That Was Pasted Into

### ISSUE THREAD

**Issue by cro-magnon** [ag-grid/ag-grid#5140]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When using a Windows machine, pasting a range of cells into a row in a grid ends up with the pasted cells clearing a cell in the row below the one that was pasted into.

**Expected behavior**
The cell that was below the row that was pasted into should not be cleared.

**Please tell us about your environment:**
This was happening in my team's enterprise app with Windows users, but not for Mac users. Currently, it seems the issue is reproducible on the ag-grid demo page https://www.ag-grid.com/example.php

* **AG Grid version:** X.X.X
The version we use in our enterprise app is 25.3.0, but I assume the demo page is 27.2.1. The issue occurs both places when using a Windows machine.

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React 16 with node v16.13.0

**Comment by cro-magnon** [comment]
To clarify, this happens when pasting from excel (just normal cells, no fancy formatting etc) into ag grid. The cleared cell even happens in the event where a single cell is copied and pasted into the grid.

**Comment by makinggoodsoftware** [comment]
Hi, 

We have this gridOption:

https://www.ag-grid.com/angular-data-grid/grid-options/ 

suppressLastEmptyLineOnPasteboolean | Set to true to work around a bug with Excel (Windows) that adds an extra empty line at the end of ranges copied to the clipboard.Default: false
-- | --



Would this help?

**Comment by cro-magnon** [comment]
@makinggoodsoftware that sounds promising, I tried looking around the web for range paste excel, etc with ag-grid and did not come across this (couldn't really find anything worthwhile in fact). Thank you for pointing this out. I will try this in our product and close this if it works properly.

On a side note - is it actually a "bug" in Windows excel, or is it some sort of difference between how the system clipboard handles copying with excel? Windows Excel paste is used basically anywhere and everywhere, it would be weird if Excel never addressed that bug.

**Comment by cro-magnon** [comment]
@makinggoodsoftware just had some windows user verify this works correctly (and it still works correctly on Mac too). Thank you for pointing this property out, I was not able to find this on the ag-grid site when searching, but now I know.
Closing this issue.
