### ISSUE TITLE
Incorrect movement behavior of the drag ghost widget when using the grid in a dialog

### ISSUE THREAD

**Issue by carroe** [ag-grid/ag-grid#5142]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

No

**Requesting Community Support**

Yes

**Providing a Reproducible Scenario**
Reproducible at Stackblitz: https://stackblitz.com/edit/react-msvor2

**Current behavior**
When using AG Grid embedded in a dialog like MUI Dialog (see Stackblitz example) the drag ghost widget does not work as expected when beginning to drag a grid cell. It appears in the wrong place (above the grid) and cannot be moved freely.

* Open the sample on Stackblitz
* Click the 'Open' button
* A dialog opens containing an AG Grid
* Drag one of the rows
* The widget appears in the wrong place and cannot be moved freely on the Y-axis

We found an unsatisfactory workaround which can be seen by pressing the 'Open and Expand' button. 
The height of the parent div and thus the page body is set in such a way that it encompasses the dimensions of the dialog.

**Expected behavior**
Same behavior as when using without dialog.

**Please tell us about your environment:**

* **AG Grid version:**
* ag-grid-community 27.2.1
* ag-grid-react 27.2.1

* **Browser:**
* Tested: Chrome and Safari (newest versions)

* **Language:**
* Tested: JavaScript

**Comment by gportela85** [comment]
This happens because the body of the page contains the wrong size. You have a div rendered in the body of the page but outside of the "visible" part of the body.

Add a CSS rule to see it work correctly.
```
body {
    height: 100vh;
    width: 100vw;
}
```

see: https://stackblitz.com/edit/react-giacya?file=public%2Findex.html
