### ISSUE TITLE
row displayed when using gridApi.setQuickFilter

### ISSUE THREAD

**Issue by DimitriLib** [ag-grid/ag-grid#5163]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Hello,
I am using ag-grid for angular v27 and not able to figure out how to get number of row displayed in ag-grid when applying quick filter with gridApi.setQuickFilter('some filter'). api.getDisplayedRowCount() seems not getting changed when quick filter entered.
Filter works but not getting number of records, what i am doing wrong?

Please advice

Thank you

**Comment by StephenCooper** [comment]
Can you share some code or a reproduction based off the following example.

https://www.ag-grid.com/angular-data-grid/filter-quick/#example-quick-filter

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
