### ISSUE TITLE
Feature: only allow "OR" as a join operator on filters.

### ISSUE THREAD

**Issue by mke21** [ag-grid/ag-grid#5166]
It would be great if we could sometimes remove the option to chose the join operator in filters, so f.i. only allow an 'or' joint so that the user cannot change that.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

In any case, we appreciate the feedback.

Please keep an eye on our pipeline as this might appear there.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks for your feedback

____


If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
