### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'addEventListenerOutsideAngular')

### ISSUE THREAD

**Issue by sakshamPandeyJS** [ag-grid/ag-grid#5169]
even if latest version same error is repro and UI is getting crashed.
can someone can guide who fixed this issue ?
that would be great help.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
