### ISSUE TITLE
Performance issue with Angular 13 on Chromium based browsers

### ISSUE THREAD

**Issue by tmjwid** [ag-grid/ag-grid#5170]
**I'm submitting a ...**  
```
[X] bug report 
```

Reproducible Scenario
When using Chromium based browsers, I am seeing a substantial increase in the time for the grid to initialise. 

Chrome:
![chrome-perforance](https://user-images.githubusercontent.com/3685703/168585762-217c5a61-aed7-492a-8db3-8d4a59fa4168.png)

Firefox:
![firefox-perforance](https://user-images.githubusercontent.com/3685703/168585805-b4122b4b-342b-4858-b891-0db094712c12.png)

These metrics we based from [the first demo](https://www.ag-grid.com/angular-data-grid/data-update-row-data/)

I've attached performance profiles from both browsers:
[Firefox](https://github.com/ag-grid/ag-grid/files/8699752/Firefox.2022-05-16.12.26.profile.json.1.gz)
[Chrome](https://github.com/ag-grid/ag-grid/files/8699769/chrome-performance.zip)

**Current behaviour**
On chromium based browsers, the init of a grid is taking a lot longer than in none chromium based browsers. 1 grid doesn't really add a lot of latency, but we have modals that contain multiple grids, causing major delay on rendering over multiple seconds. 

**Expected behavior**
Performance in line with Firefox

**Please tell us about your environment:**
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
16gb Ram
Win 10 21H1, Lastest chrome, latest Firefox, latest Angular. 

* **AG Grid version:** 
27.2.1

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36'

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks
