### ISSUE TITLE
enableCellTextSelection is not working

### ISSUE THREAD

**Issue by HeyItsJs** [ag-grid/ag-grid#5202]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I am setting `enableCellTextSelection` to true in grid options. However when I perform ctrl + c on a cell, the value of the cell is not copied

* **AG Grid version:** X.X.X
version: ag-grid-react@27.3.0

Plunker link:
https://plnkr.co/edit/B8IcGGE0dpqCrBQa

The ag grid version in this plunker is an older one than what I am currently using. But the problem still persists

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

**Comment by gportela85** [comment]
You are not using ag-grid 27.3.0, the `ag-grid` package has been deprecated a long time ago. You should be using `ag-grid-community` or `ag-grid-enterprise` if you have a license. The theme is also called `ag-theme-fresh`, theme without the `ag-theme` prefix have also been deprecated many versions ago.

See: https://plnkr.co/edit/hS0dYjp8zH12O5P0
