### ISSUE TITLE
Angular ag-grid lockPosition

### ISSUE THREAD

**Issue by DimitriLib** [ag-grid/ag-grid#5206]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Ag grid angular documentation has lockPosition has possible values left, right, true in documentation: 
https://www.ag-grid.com/angular-data-grid/column-moving/#lock-position

But definition of the object in colDef.d.ts
    /** Set to `true` to always have this column displayed first. Default: `false` */
    lockPosition?: boolean;

Really need this functionality to work. Some disconnect between documentation and reality. :)

I am using: 
    "ag-grid-angular": "27.3.0",
    "ag-grid-community": "27.3.0",

Please advise

Thank you

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by DimitriLib** [comment]
Anybody please help?

**Comment by StephenCooper** [comment]
Is the feature not working for you? In 27.3 the type is as specified in the docs with boolean | 'left | 'right'. Where are you seeing the incorrect type information?

**Comment by DimitriLib** [comment]
Hi Stephen,
Thank you for response.  It works, it seems i did not have latest version installed
