### ISSUE TITLE
How To control getContextMenuItems Use chartRange content

### ISSUE THREAD

**Issue by MruHuang** [ag-grid/ag-grid#5212]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I hope that when I use getContextMenuItemsData to set the chartRange, I can further set the content of the chart in the chartRange. I only want two or three kinds for users to choose (currently I hope to open Column.Grouped and LINE mode)
I can't find the relevant setting method in the official document

```
var getContextMenuItems = [
    'copy',
    'separator',
    'chartRange',
];

 this.gridOptions = {
                defaultColDef: {
                    sortable: true,
                    resizable: true,
                    enableRowGroup: true,
                    enablePivot: true,
                    enableValue: true,
                    suppressMenu: true,
                },
                rowSelection: 'multiple',
                columnDefs: this.columnDefs,
                rowData: this.rowData,
                enableRangeSelection: true,
                allowContextMenuWithControlKey: true,
                getContextMenuItems: this.getContextMenuItems ,
                chartThemes: [ 'ag-vivid'],
                groupDisplayType: 'multipleColumns',
                groupDefaultExpanded: -1,
                pivotMode: true,
                suppressAggFuncInHeader: true,
                suppressExpandablePivotGroups: true,
                columnHoverHighlight: true,
            };
```

Please tell us about your environment:

WebStorm
Windows
js-data-grid
AG Grid version: 27.3.0
Browser:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
Language: all

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
