### ISSUE TITLE
rowDragEntireRow does not update in React

### ISSUE THREAD

**Issue by diannasoreil** [ag-grid/ag-grid#5215]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using AG Grid React, setting the `rowDragEntireRow` attribute of the grid to a dynamically set value, such as a `useState` value, it does not set/unset the behavior, instead defaulting to whichever value was set first.

An example can be found in this Plunkr: https://plnkr.co/edit/o9QvYG0O7LfW94yL?open=index.jsx

**Expected behavior**
The entire row drag behavior should be set/unset according to the truthy/falsy value passed into the grid attribute.

**Please tell us about your environment:**
n/a

* **AG Grid version:** 27.3.0, both `community` and `react`.

* **Browser:**
Plunkr

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
