### ISSUE TITLE
chrome39无法加载表头和数据行，只有空白布局

### ISSUE THREAD

**Issue by peak1216** [ag-grid/ag-grid#5223]
**Please tell us about your environment:**
https://www.itxst.com/package/ag-grid/ag-grid-community.js
IDE：vscode
age：https://debug.itxst.com/js/ag-grid

* **AG Grid version:** X.X.X
ag-grid-community.js

* **Browser:**
chrome39

* **Language:** javascript

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
