### ISSUE TITLE
Set Filter when applying an Model with values that are not in the column the values are not showing up in the filter list

### ISSUE THREAD

**Issue by b-dreissigacker** [ag-grid/ag-grid#5224]
**I'm submitting a ...**

[x] bug report
[] feature request
[] support request

We are offering our users to save Filter for later use.
When applying a saved Filter after the list content has changed and a value we are filtering for was removed
I noticed that Set Filter does apply the Filter but there is no way for the user to uncheck the removed value from the Filter.

Here is an example of the bug, press the "API: filter for value not in list" button to trigger the bug.
https://plnkr.co/edit/dGWMODHn4Ve83yS3?open=app%2Fapp.component.ts

**Current behavior**
The Filter is successfully applied, the Filter symbol is in the column header and Toolbar.
But the value we filtered for is not showing up in the Toolbar so the user can not change the filter setting and if we read the Model the value we are filtering for is not in the Model.

**Expected behavior**
I would expect that when a Filter Model with additional values is applyed that the additional values show up in the Filter list and Filter Model.

* **AG Grid version:** 
27.3.0

* **Browser:**
Chrome/101.0.4951.64

* **Language:**
typescript 4.2.4

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 

Thank you for your message and the example you presented.
I understand your expectation in this case, however, this is an edge-case. The default set-filter is designed to account for values _from the dataset._ Whilst the API gives you the ability to filter for values not present, in this case you will have to supply the values yourself. 
You can find out more about this here: 
https://www.ag-grid.com/javascript-data-grid/filter-set-filter-list/#supplying-filter-values
