### ISSUE TITLE
showPopupMenu API

### ISSUE THREAD

**Issue by luigigargioni** [ag-grid/ag-grid#5231]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behaviour**
There is no possibility to open the header popup menu programmatically.
You can do something only by a [workaround](https://stackoverflow.com/questions/68182058/show-popupmenu-in-ag-grid), but in some case it is tricky.

**Expected behavior**
Providing an API `showPopupMenu` to open the menu as there is for `hidePopupMenu`

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

Note that we don’t take feature requests from Github, we only do this for registered customers via our dedicated support portal.

In any case, we appreciate the feedback.

Please keep an eye on our pipeline as this might appear there.

https://www.ag-grid.com/ag-grid-pipeline/

Thanks for your feedback

____


If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
