### ISSUE TITLE
Issue on Tab focus on empty floating filter triggers onFilterChanged

### ISSUE THREAD

**Issue by ABUdhay** [ag-grid/ag-grid#5236]
https://github.com/ag-grid/ag-grid/blob/bf5a9960e6e139d592367cc7b2662260b0600682/packages/ag-grid-community/dist/lib/filter/floatingFilter.js#L84

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
