### ISSUE TITLE
Filter notContains and notEqual not working on treeData

### ISSUE THREAD

**Issue by dorianAladel** [ag-grid/ag-grid#5239]
I'm trying to fix an agGrid bug on treeData element. When I filter with contains, startsWith, endsWith, equals then it works as expected but when I filter with notContains and notEqual, nothing is filtered : parent as child elements whatever.

Have you any idea ? I looked on issues page but I didn't find anything.

Here is a plunkr page that presents the bug : https://embed.plnkr.co/plunk/JQV8LqyzPG039epA

Thanks for your help,

Environment: AngularJS, ag-grid-community et ag-grid-enterprise "^26.1.0" with npm

**Comment by icedjello** [comment]
Hi, 

That's not a bug, tree data filtering is explained here: https://www.ag-grid.com/javascript-data-grid/tree-data/#tree-data-filtering 

> As Tree Data has parent / child relationships, by default all child nodes will be included when a parent passes a filter, and as filtering is performed across all group levels, a group will be included if:
> a. it has any children that pass the filter, or
> b. its data passes the filter

You just need to add `excludeChildrenWhenTreeDataFiltering` as shown here. 

https://plnkr.co/edit/vqDo19ICQvjoCyNV

**Comment by dorianAladel** [comment]
Hi,

Oh well, I didn't realize it worked like that. Thanks a lot it works like a charm, sorry for the inconvenience.
