### ISSUE TITLE
Scrolling Choppiness in Chrome (MacOS and Windows)

### ISSUE THREAD

**Issue by ekrapfl** [ag-grid/ag-grid#5243]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Reproducible Scenario**
- Use Chrome on MacOS or Windows
- Go to https://www.ag-grid.com
- Vertically scroll Integrated Charting demo grid

**Current behavior**
- Vertically scrolling the grid will result in smooth scrolling only up to the visible rows plus the `rowBuffer`, then scrolling will stop until you either move the mouse, or stop and start scrolling again.
- Particularly bad when using a track pad and trying to "fling" to scroll.  It only flings up to the buffer, then you have to do it again.
- Results in very choppy looking scrolling.
- Using a scroll wheel to continuously scroll does not work at all.  If I keep the mouse pointer still and keep scrolling, it will eventually stop until I either move the mouse pointer, or stop and restart using the scroll wheel.

**Expected behavior**
- Vertically scrolling the grid in Chrome should be smooth, even beyond the visible rows plus the `rowBuffer`, just like it is in Edge and Safari.

**Please tell us about your environment:**
- Using Chrome on MacOS and Windows.
- Using the Integrated Charting demo grid on https://www.ag-grid.com
- Using `rowModelType: "serverSide"` and `serverSideStoreType: "partial"`

* **AG Grid version:** 27.3.0 (originally discovered using this)
   - Reproducible with whatever is current on https://www.ag-grid.com

* **Browser:**
   - Windows: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53`
   - MacOS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36`

* **Language:** TypeScript 4.1

**Comment by liuzhiguo630** [comment]
+1

**Comment by StephenCooper** [comment]
Thanks for reporting this. It is in-fact a Chrome bug that we have reported. Could you please star the below issue to help raise its urgency. 

https://bugs.chromium.org/p/chromium/issues/detail?id=1330045

**Comment by qiujie8092916** [comment]
+1

**Comment by Aeogor** [comment]
+1

**Comment by ROTGP** [comment]
Just FYI - if you place your cursor over the scrollbar - and then use your trackpad to scroll - the problem goes away. Not useful, but interesting.

**Comment by gportela85** [comment]
@ROTGP that happens because the overlay with `pointer-events: null` doesn't cover the scrollbar. Remember to "star" the Chrome issue above to make sure the Chromium team fixes this as soon as possible.

**Comment by ekrapfl** [comment]
Fyi, the Chrome bug has not been completed yet, but it looks like it has been fixed in v104.0.5108.0+
I tested in Canary on my own machine, and that appears to be working fine now <3
https://bugs.chromium.org/p/chromium/issues/detail?id=1330045
