### ISSUE TITLE
Please don't remove Vue direct reference component registration

### ISSUE THREAD

**Issue by stellR42** [ag-grid/ag-grid#5245]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I am not a paying customer, but I hope that you don't ignore this issue. I see in the Vue documentation (https://www.ag-grid.com/vue-data-grid/components/) that while it is currently supported to register custom components directly, that feature is deprecated and will soon be removed. The documentation also provided several explanations as to why registering by name is the preferred method.

As a Vue user, none of the provided explanations are true for me. On the other hand, I'd like to give some reasons why registering by name doesn't work for me:
1. This can't work using the new `script setup` syntax in Vue 3. Name registration relies on using the `components` property in an SFC, but `script setup` doesn't have component registration and rather allows any component that has been imported to be used in the template.
2. This doesn't work if I want to create a wrapper component for the grid and pass in the column definitions to the wrapper as a prop. If the column definitions contain a custom component, I can easily register it by direct reference in the column definitions. However, if I am forced to register it by name, that means that any custom components need to be registered within the wrapper's `components` property, which highly cripples the use of a generic wrapper component.
3.  This is a more minor gripe, but it doesn't look clean at all to have components registered that aren't in use in my template, and in fact, my linter gives an error for these cases.

I hope that you will take these concerns into consideration.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by StephenCooper** [comment]
I am going to close this ticket for now, to maintain a clean issue board, but please rest assured we are still working through these considerations and helpful suggestions internally. We will update the ticket in due course.

**Comment by Yumozhi** [comment]
I found a workaround to solve this problem. Register a render component R as cellRenderer, pass a custom component X to cellRendererParams and render X in R dynamically.

here is the example.
[ag-grid-component-render](https://codesandbox.io/s/ag-grid-component-render-cll8en?file=/src/App.vue)

**Comment by destradafilm** [comment]
> **I'm submitting a ...** (check one with "x")
> 
> ```
> [] bug report => see 'Providing a Reproducible Scenario'
> [x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
> [] support request => see 'Requesting Community Support'
> ```
> 
> I am not a paying customer, but I hope that you don't ignore this issue. I see in the Vue documentation (https://www.ag-grid.com/vue-data-grid/components/) that while it is currently supported to register custom components directly, that feature is deprecated and will soon be removed. The documentation also provided several explanations as to why registering by name is the preferred method.
> 
> As a Vue user, none of the provided explanations are true for me. On the other hand, I'd like to give some reasons why registering by name doesn't work for me:
> 
> 1. This can't work using the new `script setup` syntax in Vue 3. Name registration relies on using the `components` property in an SFC, but `script setup` doesn't have component registration and rather allows any component that has been imported to be used in the template.
> 2. This doesn't work if I want to create a wrapper component for the grid and pass in the column definitions to the wrapper as a prop. If the column definitions contain a custom component, I can easily register it by direct reference in the column definitions. However, if I am forced to register it by name, that means that any custom components need to be registered within the wrapper's `components` property, which highly cripples the use of a generic wrapper component.
> 3. This is a more minor gripe, but it doesn't look clean at all to have components registered that aren't in use in my template, and in fact, my linter gives an error for these cases.
> 
> I hope that you will take these concerns into consideration.

I came across this same issue with a wrapper component for the grid in a monorepo as a separate package. We have an enterprise license and really need this feature to continue or another workaround that is not hacky.

**Comment by sabahang** [comment]
We are aware of the work needed to fully support composition API with Vue 3

You can track it with this reference:
**AG-11585 Re-write Vue 3 wrappers primarily to fully support Composition API**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up
