### ISSUE TITLE
how to use defaultToNothingSelected in angular 7 with ag-grid version 20.2.0

### ISSUE THREAD

**Issue by MalaPatil** [ag-grid/ag-grid#5248]
can anyone please help me 

how to use  "defaultToNothingSelected" Parameter  in Angular 7 with ag-grid version 20.2.0

**Comment by sganayon** [comment]
Hi, 
I have the same problem : I want to use defaultToNothingSelected with my agSetColumnFilter like this :  
filter: 'agSetColumnFilter',
filterParams: {defaultToNothingSelected: true}

But it doesn't work and I can't find the version required to use this feature. 
Currently using Angular 8.1.1 and ag-grid-enterprise 22.1.2

**Comment by MalaPatil** [comment]
You should upgrade the angular and ag-grid enterprises version.It works for me when I use these version
Angular 13 version
Ag-grid 27 version

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
