### ISSUE TITLE
Cell rendering can not detect row heights of different size

### ISSUE THREAD

**Issue by MaryamByt7** [ag-grid/ag-grid#5254]
I used the Infinite Row Model and I want to show an array in one cell but cell rendering can not detect row heights of different sizes, Is there a solution to this problem?

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
