### ISSUE TITLE
Ag grid Excel export - style headers differently

### ISSUE THREAD

**Issue by harika-c** [ag-grid/ag-grid#5267]
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'

Request Description : I have 3 headers in colDefs and when i do an excel export, i want to style one header to leftAligned and one more header to rightAligned . As per the official Ag grid docs the styling is working by inserting id:"header" on excelStyles[] and this gets applied to all the headers . I want to apply styles to headers individually .

Sample code i used to change the headers styling is : 

```
const excelStyles: ExcelStyle[] = [
    {
      id: 'greenBackground',
      alignment: {
        horizontal: 'Right'
      },
      font: {
        color: '#006cfa'
      }
    },
     {
       id: `header`,
       alignment: {
          horizontal: 'Right'
       },
       font: {
        color: '#006cfa'
     }
     }
  ];
```
Expected : With the above code im able to rightAlign selective rows to right side by adding id:"greenBackground"  and i also want to rightAlign only few columns headers and not all . 

Actual : when i give id:"header" all the headers change to rightAlign and it works as per what the Ag-gid official Docs says  .I want only id with (id:"greenBackground") headers to rightAlign. Or only headers belong to certain columns to rightAlign . How can we achieve this ?

Followed the Doc:  https://www.ag-grid.com/angular-data-grid/excel-export-styles/

version of Ag-grid used : 
  "ag-grid-community": "26.1.0",
    "ag-grid-enterprise": "26.1.0",
Language : 
 "typescript": "4.7.2",
 "react": "^17.0.2",

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
