### ISSUE TITLE
Invalid CSS after "    @return math": expected expression (e.g. 1px, bold), was ".div($lhs, $rhs);"

### ISSUE THREAD

**Issue by Aman-Vijaywargi** [ag-grid/ag-grid#5273]
While working with styling of ag-grid, I found this error if I was using "ag-grid-community/dist/styles/ag-theme-alpine/sass/ag-theme-alpine.scss" for the styling of my table.

How do I resolve this issue as this is giving me error as

`Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

    @return math.div($lhs, $rhs);
               ^
      Invalid CSS after "    @return math": expected expression (e.g. 1px, bold), was ".div($lhs, $rhs);"
`

**Comment by gportela85** [comment]
Are you using `node-sass`? If yes, this package has been deprecated, see: https://www.npmjs.com/package/node-sass
Use `sass` instead.
