### ISSUE TITLE
api.resetRowHeights() does not work with row model type infinite

### ISSUE THREAD

**Issue by destradafilm** [ag-grid/ag-grid#5284]
**I'm submitting a BUG **
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Current behavior**
api.resetRowHeights() does not work with `row-model-type: infinite` 
looks like this is only for the ClientSideRowModel? 

I didn't see any information on this in the documentation. There is a console warning if you use auto height but no feedback or documentation if you use a different row model type. Is this a bug? and if not then why would it would be suppressed?

![Screen Shot 2022-06-16 at 1 53 45 PM](https://user-images.githubusercontent.com/6043499/174153279-20736e59-7373-41d9-9960-45845a5302d3.jpg)

**Expected behavior**
Expected behaviour. If possible back this up with our docs/examples if possible
Allow you to resize row heights for other row model types other than Client Model

* **AG Grid version:** 
    "ag-grid-community": "^27.2.0",
    "ag-grid-vue": "^27.2.0",

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'

* **Language:** 
Typescript: 4.4.3

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for your feedback, note that we don’t think this is a bug, as the system works as expected in this area.

In our opinion, this would be a feature request as is not meant to work outside of the client side row mode

Note that we don’t have the capacity to take feature requests as we have a full pipeline.
https://www.ag-grid.com/ag-grid-pipeline/

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

---

We are going to label this as managed-by-the-community as it is probably there are some ways to mitigate this and hopefully someone from the community can help you with a workaround/fix.

**Comment by destradafilm** [comment]
ok thanks for the response. Any way we can have the documentation say that it's not available with the other row model types? We dont even get any console warnings or feedback, it just doesn't response and I had to debug to figure this out

I've been exploring this library with the community version for now but I am planning to move to enterprise soon

Thanks!

**Comment by destradafilm** [comment]
I tried to alternatively use `setRowHeight` to all nodes but this does seem like an actual bug for row model 'infinite' since this partly applies the row height for the actual rows but the `translateY` doesn't get updated

here's an example:
https://plnkr.co/edit/Na6cpXqic8YxDaDE?open=main.js&preview

https://user-images.githubusercontent.com/6043499/175383677-23abafd0-fe31-4acc-a90c-78be184b4631.mp4
