### ISSUE TITLE
Params.rowIndex is not reactive when I provide getRowId prop 

### ISSUE THREAD

**Issue by zhiyuanzmj** [ag-grid/ag-grid#5288]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The params.rowIndex is not update  when I provide getRowId prop.
[https://plnkr.co/edit/90J6b85G9dQ0bjLZ](https://plnkr.co/edit/90J6b85G9dQ0bjLZ)

**Expected behavior**
I hope in cellRenderer, params.rowIndex is reactive. 

* **AG Grid version:** 
latest

**Comment by chefnoname** [comment]
Hello zhiyuanzmj!

Thank you for your email and for the context you’ve provided.

We looked into your scenario and built a sample to help you implement this behavior:

**[https://plnkr.co/edit/V4wblFleJPqG8VxL](url)**

Leveraging a **valueGetter** will help you achieve your desired behaviour

Please use the sample above to implement this and let me know if you have any questions.

Regards,
chefnoname

**Comment by xhxhxhxh** [comment]
same problem, row index not reactive
https://plnkr.co/edit/z7IrX2DdHPK2s5JE?open=main.js
I change the vue version from 3.2.29 to 3.2.41, v3.2.29 behaving normally.
