### ISSUE TITLE
[rendering] Multi-line cell support with ellipsis on the last line (line-clamping)

### ISSUE THREAD

**Issue by DrCool** [ag-grid/ag-grid#529]
I'd like to see multi-line support in the cells with ellipsis appearing on the last line (line clamping https://css-tricks.com/line-clampin/).  I had hoped there was an easy CSS way to do this but after spending the morning Googling, I now realize there isn't.  It would be better to have it in the component where it will be more efficient and could have better support than a CSS-only alternative.

I know there would be a performance hit for this feature, but at times it would be really useful and I would be happy to accept that trade-off on certain uses of ag-grid.

Thanks for your consideration!  I love the grid, by the way.

**Comment by DrCool** [comment]
By the way, out of the various methods I've learned about today for line clamping, this was the most elegant and seems like the simplest way to do with code.  It also achieves much better results than the CSS-only methods I've seen.

http://codepen.io/Merri/pen/Dsuim

Basically, the code will analyze the width of the text and figure out where to line-break it.  It creates a <span> element for each line.  The final line is actually the remainder of the text in another <span> but this span element has a CSS "text-overflow: ellipsis" set on it so it truncates normally.  Bada-boom... multi-line ellipsis.

And for others who may read this, here's what I also learned today:  currently, non-Webkit browsers don't support ellipsis overflow on multiple lines.  It's only for single lines of text ('whitespace: nowrap').  Even the Webkit CSS is a bit wonky (padding screws it up).

**Comment by ceolter** [comment]
interesting. will take me a while to look into this, but i'll get to it in time. thanks for the suggestion.

**Comment by DrCool** [comment]
When you work on this (no hurry), could you also please create a way for my code to know if the text has been truncated because it's too long?  This way, I have the option of displaying a tooltip over the cell to show all of the cell text.  Sometimes, the user needs to be able to see all the text.  We need ways of detecting when text is truncated so we can provide an alternative to the user.

Thanks!

**Comment by DrCool** [comment]
I was able to hack something together using a custom CellRenderer, a subroutine to calculate text widths that I found on stackoverflow, and using the grid's onColumnResized event.

This plunker shows a grid with a column of text that is too long to be displayed.  By default, the code will render two lines of text and the last line will be truncated with ellipses.  You can easily specify how many lines of text to display in each cell.

You can resize the column and see the text word-breaking and adjusting on the fly.

http://plnkr.co/edit/YjsTu330aA7t6UdOV6NV?p=preview

I hope this helps someone else!

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-79

**Comment by glinkot** [comment]
Hi,

I don't seem to have access to the atlassian tracker.  Is this now available?  Really I was hoping for a multiline 'memo' type field with scrolling.  I imagine I can implement it as a custom renderer but if there is an out of the box feature, I will use it :)

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by EloHailwidis** [comment]
Hi @makinggoodsoftware ,

Sorry to comment on this old issue. I can't find the linked ticket in the pipeline. AG-79 seems to be something else.

Thanks

**Comment by Nicba1010** [comment]
Is the ticket publicly visible? I can't seem to open it. If not, has there been any progress on this?

**Comment by AG-Zoheil** [comment]
Hi @Nicba1010,

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue from almost **seven years ago**.

The grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
