### ISSUE TITLE
Upgrading ag-charts-community and ag-charts-react to 5.3 causes a build issue with create react app

### ISSUE THREAD

**Issue by ekdev2** [ag-grid/ag-grid#5293]
**I'm submitting a ...**  (check one with "x")
```
x bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The latest ag chart packages produce a bad build in the create react app package. At the root of the application, the console errors is saying: Uncaught ReferenceError: exports is not defined. We are using create react app and react 17. The app worked when we used the ag-charts 3.3

**Expected behavior**
the build to work with the latest ag chart packages

**Please tell us about your environment:**
static build from create react app

* **AG Grid version:** 5.3.0

* **Browser:**
Chrome

* **Language:** TypeScript 4.0.3

**Comment by ekdev2** [comment]
Additional Info
"react-scripts": "4.0.1"
"react": "^17.0.1"

**Comment by ekdev2** [comment]
I just did some more testing and it looks like the issue is in the ag-charts-react package. When I upgrade ag-charts-community to 5.3 and leave ag-charts-react at 3.3 it works.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
