### ISSUE TITLE
Does Ag Gird support set filter option groups?

### ISSUE THREAD

**Issue by ivan006** [ag-grid/ag-grid#5295]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Like a bunch of set filter options (checkboxes) listed under a parent option that if I click the parent it select all the children related.

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
