### ISSUE TITLE
[pagination] Allow customer pagination panel template

### ISSUE THREAD

**Issue by kyrylkov** [ag-grid/ag-grid#530]
Could the default pagination visual style be updated to something along the lines of http://bramus.github.io/ws2-sws-course-materials/assets/06/pagination-good-flickr.png

The current one is quite archaic (looks like 10 year old JSP component).

**Comment by ceolter** [comment]
+1 . . . . will get to it in time

**Comment by Vayvala** [comment]
+1

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-80

**Comment by ALFRED-Guillaume** [comment]
Hi,

Is there a workaround for that ? I'm using ag-grid-ng2 but I can't find a way to change the pagination.

- I'd like to add a pagesize select
- I'd like to add the type of resultats after the record count

.. but I struggle to do it. Any advice/help is welcome :)

Thanks in advance.

**Comment by papabear** [comment]
Is this coming any time soon? I'm unable to access https://ag-grid.atlassian.net/browse/AG-80 to check the status.

**Comment by mmameko** [comment]
Guys, could anybody say when this feature plan to be released?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
