### ISSUE TITLE
docs: Show child to parent communication example in vue using the composition api

### ISSUE THREAD

**Issue by ryan-buckman** [ag-grid/ag-grid#5322]
Could the docs be updated to demonstrate how to do child to parent communication in vue using the composition api? Currently the [vue data-grid getting started](https://ag-grid.com/vue-data-grid/getting-started/) example shows a simple example of setting up a grid using the composition api - unfortunately the [component communication](https://ag-grid.com/vue-data-grid/component-communication/) example for vue only shows an example using the options api. This is making following the docs and examples confusing at times.

**Comment by StephenCooper** [comment]
Does the following example not include the variation that shows this? 
https://ag-grid.com/vue-data-grid/component-cell-renderer/#example-dynamic-components

**Comment by ryan-buckman** [comment]
https://ag-grid.com/vue-data-grid/component-cell-renderer/#example-dynamic-components is using the `Options Api`
https://ag-grid.com/vue-data-grid/getting-started/#copy-in-application-code-3 is using the `Composition Api`

You can see the differences in `setup()` vs  `data: function () ` and how properties are being handled with `reactive` and `refs` etc.

**Comment by delebash** [comment]
For composition you can just pass your function.

Parent component:

Add  :context="context" to your 

```
 <ag-grid-vue  
 :context="context" 
other options ....   
>
  </ag-grid-vue>
```

```
onBeforeMount(() =>{
  context = { componentParent: deletePost };
})
```

function deletePost(){
  console.log('test')
}

Child:  see function deletePost you could probably pass an object with many functions and other vars if you want.

```
<template>
<span>
  <router-link v-if="can('post-edit')"
               :to="{ name: 'posts.edit', params: { id: id } }"
               class="badge bg-primary">Edit
  </router-link>
  <a href="#" v-if="can('post-edit')" @click.prevent="deletePost(id)" class="ms-2 badge bg-danger">Delete</a>
</span>
</template>
<script setup>
import {useAbility} from '@casl/vue';
const {can} = useAbility();

const props = defineProps({})

function deletePost(id){
  props.params.context.componentParent(id)
}
const id = props.params.value

</script>
<style scoped>

</style>

```
