### ISSUE TITLE
TypeScript: add generic support to event interfaces

### ISSUE THREAD

**Issue by stefnedelchev** [ag-grid/ag-grid#5323]
**I'm submitting a ...**  (check one with "x")
```
[] bug report
[x] feature request
[] support request
```

**Current behavior**
When using any event interfac that includes the row data  (for exmple `CellValueChangedEvent`), `data` property is always with type `any` which forces us to use type assertion that matches our model (and satisfy typescript strict support).

**Expected behavior**
It would be good if these interfaces accept generics: for exmple `CellValueChangedEvent<MyType>` would result in an interface that has `data: MyType` Property. This can be improved even further with 2 generics for value events - one generic for the row data and another for the `value` type. The generics can have `any` as default which won't break any current behavior.

**Please tell us about your environment:**
Windows 10 x64, NPM  6

* **AG Grid version:** 27.3.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

* **Language:** TypeScript 4.6

**Comment by StephenCooper** [comment]
Yes, I am planning on doing this but it requires careful audit of each event under all different grid configurations. So it is likely in this initial release we will be more cautious with this approach and default to including undefined in the type as that is less dangerous to users then to have us incorrectly say that row data will definitely be defined.

CellValueChangedEvent is probably a good candidate as you suggest for this.
