### ISSUE TITLE
Vue 3 cell editor strange behaviour on first edit

### ISSUE THREAD

**Issue by Schewns** [ag-grid/ag-grid#5327]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

I am a customer of AG grid but unfortunately I don't have the credentials to submit a request to zendesk atm

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- using ag-grid for vue3 I have built a table with a few columns. each column has a cellEditor generally described like:
`{
cellEditor: 'SomeCellEditor',
cellEditorParams: ()=>{ someParams},
editable:true,
}`

Current behavior.
- first time I double-click the cell to edit, cellEditor opens and closes. debugging the code I can see that ag-grid/VueComponentFactory throws an error stating he didn't find the component. this happens once per grid load, the second time I try to edit the table cellEditor is loaded correctly.
- 
Expected behavior:
- cell editor works fine every time and not just after a first failed attempt to load the cell editor

* **AG Grid version:** 27.3.0

* **Browser:**
Chrome

**Comment by sjacq** [comment]
I had exactly the same issue with a simple cell editor. It won't appear the first time I edit or create a row. Second and all subsequent calls, it works fine.

It looks like ag-grid is not creating the component on the initial row edit. The only solution I found is to put the same component (hidden) above the grid. Then, it works immediately during the first row edit (or create)

Note: Happens only since the update to 27.3

**Comment by Schewns** [comment]
> I had exactly the same issue with a simple cell editor. It won't appear the first time I edit or create a row. Second and all subsequent calls, it works fine.
> 
> It looks like ag-grid is not creating the component on the initial row edit. The only solution I found is to put the same component (hidden) above the grid. Then, it works immediately during the first row edit (or create)
> 
> Note: Happens only since the update to 27.3

thank u for the reply, i will try it and ocme back

**Comment by Schewns** [comment]
Unfortunately didn't solve, the problem is that the first time I double click the cell editor. Trying to solve the problem

**Comment by StephenCooper** [comment]
We cannot reproduce this. Are you able to update this Plunker to reproduce the issue that you are seeing. Its on the latest version 28.1.

https://plnkr.co/edit/m0XuxjTYOHdmaOlp?open=main.js
