### ISSUE TITLE
No support for drag drop between Tree view and simple grid

### ISSUE THREAD

**Issue by jane-taleika** [ag-grid/ag-grid#5328]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
I am a customer of AG grid but unfortunately I don't have the credentials to submit a request to zendesk

**Providing a Reproducible Scenario**
Using angular ag-grid version 27.3.0 it's not possible to use drag'n'drop features from simple grid to tree data grid. 
Is there any reason it's not supported? I haven't found any issues in roadmap.

**Current behavior**
Drag from grid to tree data grid isn't working

**Expected behavior**
Drag from grid to tree data grid is supported

* **AG Grid version:** X.X.X
 27.3.0

* **Browser:**
Chrome

**Comment by makinggoodsoftware** [comment]
HI,

This seems like a support question and It sounds like you have an ag-grid license/evaluating. Note that github is not our main channel for support for customers.

You should contact us through zendesk, you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at info@ag-grid.com where they will be able to assist you with your access.

Thanks
