### ISSUE TITLE
Custom header component is missing props

### ISSUE THREAD

**Issue by jtuchel** [ag-grid/ag-grid#5331]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**

*Reproduction with Plunker*

Taken from [Example: Custom Header Component](https://www.ag-grid.com/vue-data-grid/component-header/#example-custom-header-component), I modified the files *customHeaderVue.js*  and *main.js*

https://plnkr.co/edit/OoOD0I8W5NgYX45u

---

*Reproduction without Plunker*

Setup a new Vue 3 project and create a custom component with the following content

```html
<script setup lang="ts">
const props = defineProps<{
  foo: string;
}>();
</script>
```

Define a new `ColDef` and use it

```ts
const colDef: ColDef = {
  field: 'objectKey',
  headerComponent: ColumnHeader, // my custom component
  headerComponentParams: {
    foo: 'bar'
  },
}
```

You should get the following error

> [Vue warn]: Missing required prop: "foo" ...

---

**Current behavior**
The component props are undefined so you can't access them.

**Expected behavior**
The props are defined so you can access them.

**Please tell us about your environment:**
OS: Linux pop-os 5.17.15-76051715-generic #202206141358165591911622.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux

IDE: Webstorm

Package Manager: npm 8.13.1

**AG Grid version:** 
27.3.0

**Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

**Language:**
all

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 

In this case `agColumnHeader` is provided by AG Grid and therefore, does not conform to standard prop-passing as other components would. In this case to access properties passed via `headerComponentParams`, you will need to use `this.params.{[propert name]}` to access the values required. 
You can see this in the example below: 
https://plnkr.co/edit/JTJ1IUX1Ae7mMHLR?open=main.js 
I hope this helps
