### ISSUE TITLE
Sticky Groups not working with fullWidthCellRenderer

### ISSUE THREAD

**Issue by shadoworion** [ag-grid/ag-grid#5334]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

When groupRowsSticky is true and group rows isFullWidthCell - when open you can't close group, when scroll it breaks all grid

* **AG Grid version:** 28.0.0

* **Language:** TypeScript, React, Vite

**Comment by chefnoname** [comment]
Hi shadoworion,

Thanks for your email.

We've built an example in an effort to reproduce the effect you've mentioned however, we aren't seeing the same behaviour:

https://codesandbox.io/s/github/ag-grid/examples/tree/main/projects/t2t-6846?file=/src/index.js 

We have groupRowsSticky and cells which take fullWidth yet we are able to open and close groups

To help us continue investigating, please fork and modify the example above to reproduce the issue, so we can see it on our end.

We're looking forward to your response, so we can get started!

Regards,
