### ISSUE TITLE
Header Template broken since 28.0.0

### ISSUE THREAD

**Issue by smorandi** [ag-grid/ag-grid#5340]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The Header Template functionality does not work anymore. See your own page: 
https://ag-grid.com/angular-data-grid/column-headers/#example-simple-header-templates

**Comment by StephenCooper** [comment]
Hi @smorandi ,

We do not see any issues with this example. Can you show us what is broken for you? 

This is what I see for this example. 
![Screenshot 2022-07-08 at 14 05 02](https://user-images.githubusercontent.com/20125490/177997805-dd87f105-151b-4f12-b60e-bb128ad70d8c.png)

**Comment by smorandi** [comment]
the whole customization of the sortindicator does not work, since the whole thing has changed due to i guess the changes inteoduced for row geoup sorting.

**Comment by StephenCooper** [comment]
Thank you for the extra details. We can now reproduce the issue and will investigate further.

**Comment by smorandi** [comment]
you are welcome, i should have described the issue in more detail from the start, sorry about this 🙂

my workaround for now is using css directly to reorder the items within the sort-indicator to put them in different order. since the container for the sort-indicator is using „flex“ i can rearrange by using the css order property for now anyway.

**Comment by rmc-software** [comment]
We have added the following defect to our backlog:

AG-6973 - [Templates] Custom header templates no longer show sort indicators

See pipeline page: https://www.ag-grid.com/ag-grid-pipeline/

This will be fixed in our next release.

Thank you for reporting this.

**Comment by oodavid** [comment]
I came to log this same issue, here's my demo:

https://plnkr.co/edit/UmxdhfKTPeipiH1c?open=main.js

And video:

https://www.loom.com/share/07a3ba241a8f44a2833672bda55e682c
