### ISSUE TITLE
Feature request: Get data in sorted format (as displayed in the grid) not just sorting directions.

### ISSUE THREAD

**Issue by Jagrutiti** [ag-grid/ag-grid#5343]
## Feature request

I use PDFMake to export data to pdf (please do let me know if AG Grid is planning to provide pdf export feature soon).

So I need both, sorted data and filtered data from the API. I use `gridOptions.api.getFilterModel()` to get the [filtered data](https://www.ag-grid.com/javascript-data-grid/filter-api/#reference-filter-getFilterModel). 

But I cannot get a similar API to get sort data. I found get [getSort](https://www.ag-grid.com/javascript-data-grid/column-object/#reference-methods-getSort) that only returns the sorting direction but not the data.

Is there any way to get data in sorted format from AG Grid itself? Along with filtered data?

**Comment by StephenCooper** [comment]
Hi,

We are not planning on providing pdf export anytime soon.

You may want to look at the grid api method `forEachNodeAfterFilterAndSort`. Using this you could loop through the filtered and sorted data to extract what you are looking for.

https://ag-grid.com/javascript-data-grid/grid-api/#reference-rowNodes-forEachNodeAfterFilterAndSort
