### ISSUE TITLE
How to batch select rows in ag-grid

### ISSUE THREAD

**Issue by minteliuwm** [ag-grid/ag-grid#5350]
Is there a way to batch select rows in ag-grid?

Specifically, when I first load data into my grid, I also get from the server a list of rows that should be initially selected. Right now, the only way I know of to select them is to:

```
this.state.gridApi.forEachNode((node) => {
  if (isInitiallySelected(node.data) {
    node.setSelected(true);
  }
});
```

However, this fires an onSelectionChange event for each iteration.

Is there a way to tell the grid on initial load which rows should be selected?

If not, is there a way via the API to batch-select rows?

If not, is there a way to conditionally silence the onSelectionChange event when doing a node.setSelected() call?

**Comment by scottg521** [comment]
node.setSelected() has two optional parameters, the first to clear other selections and the second to prevent onSelectionChange. So you would want 

```node.setSelected(true, false, true);```

https://www.ag-grid.com/javascript-data-grid/row-object/#reference-rowNodeMethods
