### ISSUE TITLE
(False Alarm) Wrong default of gridOptions.enableCellTextSelection, causing issues

### ISSUE THREAD

**Issue by spyro2000** [ag-grid/ag-grid#5352]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproduction**

- Create any grid with default options
- Select a cell (but not the value inside)
- Press CTRL+C

**Current behaviour**
Cell value is not copied to the clipboard

**Expected behaviour**
Cell value is copied to the clipboard

**Background**

In gridOptions: `enableCellTextSelection` **should be defaulted to FALSE** according to [documentation](https://www.ag-grid.com/angular-data-grid/grid-options/#reference-selection-enableCellTextSelection).

**In fact, it is set to TRUE**. This results in several issues:

- Cell selection is behaving weird, interferes with browser selection of text elements
- CTRL+C is not working for selected cells (despite it being displayed as alternative in context menu)
- You have to explicitly set enableCellTextSelection: false in each grid options to fix this, despite this should be the default.

**Please tell us about your environment:**

Win10x64 Professional, Angular 13,

* **AG Grid version:**  Ag-Grid 27.0.3

* **Browser:**
Chrome

* **Language:**
All

**Comment by gportela85** [comment]
@spyro2000 Here is a grid with default options, and without setting `enableCellTextSelection` to false -https://plnkr.co/edit/s49138eo6x1MX5Te
Seems fine

**Comment by spyro2000** [comment]
Hello @gportela85,

your sample is not using GridOptions. I will try to provide a plunker myself today, thanks nevertheless.
