### ISSUE TITLE
Cell loses focus after tabulation with react 18, chrome and `stopEditingWhenCellsLoseFocus=true`

### ISSUE THREAD

**Issue by daniel-seoane** [ag-grid/ag-grid#5353]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

With `stopEditingWhenCellsLoseFocus=true` you edit a cell, press tab and the next cell loses focus and you cannot edit it.

It seems to happen:

- In Chrome, not Firefox
- With react 18, not react 17

The problem can be seen here:

[https://codesandbox.io/s/stoic-feather-1tc2p9](https://codesandbox.io/s/stoic-feather-1tc2p9)

**Expected behavior**

You edit a cell, press tab and edit the next cell without losing focus, as in the example in the documentation, which uses react 17:

[https://www.ag-grid.com/react-data-grid/cell-editing-start-stop/#example-stop-edit-when-grid-loses-focus](https://www.ag-grid.com/react-data-grid/cell-editing-start-stop/#example-stop-edit-when-grid-loses-focus)

* **Please tell us about your environment:**
`react 18.2.0`
`react-dom 18.2.0`

* **AG Grid version:** 
`ag-grid-react 28.0.0`
`ag-grid-community 28.0.2`

* **Browser:**
Chrome `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks
