### ISSUE TITLE
Column Moving not working properly for ag-grid-vue ( vue version v2.0)

### ISSUE THREAD

**Issue by ahmedsakri** [ag-grid/ag-grid#5358]
Column Moving not working properly for ag-grid-vue ( vue version v2.0) an not-allowed eye symbol is shown while trying to drag the column

**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

- A Screencast:

https://user-images.githubusercontent.com/60789760/179152455-9f20bd3e-f7e8-4a1e-af52-a65b1e55e751.mov

**Current behavior**
An not-allowed eye symbol is shown when trying to drag the column and change it's position. 

**Expected behavior**
User should be able to drag and change the columnn position in the table.

* **AG Grid version:** 28.0.0
Checked in the recent ag-grid-vue v28.0.0 itself.

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'

* **Language:** [ Vue | ES6/7 | ES5]

**Comment by rmc-software** [comment]
We can't reproduce this issue. Seems to be working fine in all of the Vue2 examples on the website.

Can you reproduce the issue by modifying the following plunker: 

**https://plnkr.co/edit/ZiFQtQD26qN8Otgy?open=main.js**

**Comment by ahmedsakri** [comment]
@rmc-software Can you please let me know, why am i seeing `not-allowed` eye symbol when i try to drag and change the column Positions?

**Comment by ahmedsakri** [comment]
Also, i am using `ag-grid-vue` alongside `quasar` inside a web-component. where my vue.config.js file includes the below:

`module.exports = {
  pluginOptions: {
    quasar: {
      importStrategy: 'manual',
      rtlSupport: false
    }
  },
  transpileDependencies: [
    'quasar'
  ]
}`

Do i need to make changes here?

**Comment by seanlandsman** [comment]
Do you have a repo of this issue we can take a look at? As it stands I'm afraid we don't have enough information to be able to diagnose what you're seeing.

**Comment by ahmedsakri** [comment]
> Do you have a repo of this issue we can take a look at? As it stands I'm afraid we don't have enough information to be able to diagnose what you're seeing.

I'll create one and share it...

**Comment by ahmedsakri** [comment]
@seanlandsman @rmc-software I'm attaching a reproducable github repo url: https://github.com/ahmedsakri/ag-grid-rc

**Comment by seanlandsman** [comment]
I've taken a look at this all works as expected if you change `HelloWorld.vue` to have the following 

```
import DemoWc from "@/components/DemoWc";

export default {
    name: "HelloWorld",
    components: {
        'demo-wc': DemoWc
    },
```

I'm afraid I'm not familiar with your particular setup - including the dynamic bespoke loading you're doing - to be able to offer a solution to what you're seeing.

The grid works as expected which indicates that the problem is related to the way you're loading script dynamically - perhaps some sort of sequencing issue, but regardless this is outside the scope of normal grid support Im afraid.

**Comment by yashwanth2714** [comment]
I have the same issue. It doesn't work  when you create a web component. @ahmedsakri **HelloWorld.vue** code is correct for reproducing this issue.

**Comment by ahmedsakri** [comment]
@yashwanth2714 Did you solved this? or do you have any alternate ways of fixing this?

**Comment by yashwanth2714** [comment]
@ahmedsakri No. I don't have any workarounds as of now.

**Comment by yashwanth2714** [comment]
Can someone from the ag-grid team look into this issue?

This is still open. I am not sure why the status was changed to Closed.

@seanlandsman

**Comment by VitaliiK91** [comment]
I am having the same issue. I wrap AG grid in Lit Element web component. My guess it might be related to shadow dom. I can't move columns at all if `suppressDragLeaveHidesColumns` is set to `true`.

**Comment by aleksiko28** [comment]
> I am having the same issue. I wrap AG grid in Lit Element web component. My guess it might be related to shadow dom. I can't move columns at all if `suppressDragLeaveHidesColumns` is set to `true`.

Having the same exact issue, in LitElement was well. For now I just set the `suppressMovableColumns` to `true` as I could not find a way to fix the issue.

**Comment by VitaliiK91** [comment]
@aleksiko28 I tried to mess with some DragAndDropService prototype methods and was able to make it work in very simple setup, but it breaks once you have nested shadow dom components. Basically fixing one issues creates another 2. I would really appreciate if AG added native Web Component framework.

**Comment by ReinisV** [comment]
The issue, as with most components 3rd party components, is that the logic for it is written assuming that the component is being rendered in the light dom and that its contents are accessible by global apis like `document.querySelector`, `document.activeElement` etc, etc

The difference though to most 3rd party components, is that ag-grid exposes a property that allows you to inject your own document instance for them to use rather than using the global one, and thank god for that.

https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-miscellaneous-getDocument

the fix then is to create a "mock" document instance that reimplements all of the `document` fields that ag-grid needs and pass it as a return value for this function.

```html
<AgGridVue
                class="ag-theme-alpine"
                columnDefs={this.calculatedColumnDefs}
               [...]
                getDocument={() => getMockDocumentFromShadowRoot(this)}
            />
```

```javascript
export function getShadowRoot($this: Omit<Vue, '$emit'>): ShadowRoot {
    return ($this.$root.$options as any).shadowRoot as ShadowRoot;
}

type MockDocumentForShadowRoot = {
    addEventListener: Document['addEventListener'],
    removeEventListener: Document['removeEventListener'],
    contains: Document['contains'],
    querySelector: Document['querySelector'],
    elementsFromPoint: Document['elementsFromPoint'],
    documentElement: {
        scrollTop: Document['documentElement']['scrollTop'],
        scrollLeft: Document['documentElement']['scrollLeft'],
    }
};

export function getMockDocumentFromShadowRoot($this: Omit<Vue, '$emit'>): MockDocumentForShadowRoot {
    const shadowRoot = getShadowRoot($this);

    const mockDoc: MockDocumentForShadowRoot = {
        // @ts-ignore
        addEventListener: (...data) => { return shadowRoot.addEventListener(...data); },
        // @ts-ignore
        removeEventListener: (...data) => { return shadowRoot.removeEventListener(...data); },
        // @ts-ignore
        contains: (...data) => { return shadowRoot.contains(...data); },
        // @ts-ignore
        querySelector: (...data) => {
            if (data[0] as string === 'body') {
                return shadowRoot;
            }
            // @ts-ignore
            return shadowRoot.querySelector(...data);
        },
        elementsFromPoint: (...data) => { return shadowRoot.elementsFromPoint(...data); },
        documentElement: {
            get scrollTop() { return document.documentElement.scrollTop; },
            get scrollLeft() { return document.documentElement.scrollLeft; }
        }
    };

    return mockDoc;
}
```  
this is tsx + typescript, but you can convert it to work with SFCs and JS easily.

the methods I've found that it uses are the ones listed above in the `MockDocumentForShadowRoot` type, but I am not 100% sure that those are all of them.

@devs would be awesome if there was a list of methods of `document` that are being used by ag-grid somewhere in the docs close to `getDocument` method description.

**Comment by VitaliiK91** [comment]
@ReinisV I tried this approach, but as you mentioned document fragment by default is missing some of the document properties. I was able to fix the issue for my case altering the `DragAndDropService.prototype.findCurrentDropTarget` method. The problem I found was the `elementsFromPoint` called on document was only returning the host elements. In the original AG
