### ISSUE TITLE
Full-row-width cell editing

### ISSUE THREAD

**Issue by SortaASoraous** [ag-grid/ag-grid#5366]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
Does AG Grid support the ability to expand a cell to fit an entire row while it is being edited? and then when the cell is un-focused, it returns to its original size?

**Comment by rmc-software** [comment]
See: https://ag-grid.com/javascript-data-grid/component-cell-editor/
