### ISSUE TITLE
When I change the column width, the row height changes. Then I scroll up and down the table, and the page gets stuck. 

### ISSUE THREAD

**Issue by mynamedan1** [ag-grid/ag-grid#5367]
I set the attribute wrapText: true,autoHeight: true。
When I change the column width, the row height changes. Then I scroll up and down the table, and the page gets stuck. The case of the official website also has this problem.
https://plnkr.co/edit/?open=main.js&preview

AG Grid version:v27.3.0
Browser:Google Chrome 103.0.5060.66
Language: JavaScript

**Comment by rmc-software** [comment]
I think you forgot to save the plunker before pasting it.

**Comment by mynamedan1** [comment]
https://plnkr.co/edit/zk7hOeBekZ3xN8YQ?open=main.js

**Comment by rmc-software** [comment]
Thank you for reporting this defect.

**AG-6997 - [Regression] Scrolling breaks in Auto Row Height when columns are resized**

See pipeline page: https://www.ag-grid.com/ag-grid-pipeline/

This will be fixed in our next release.
