### ISSUE TITLE
Style Imports fail after update Angular13 to 14

### ISSUE THREAD

**Issue by musheghz** [ag-grid/ag-grid#5381]
./node_modules/@ag-grid-community/all-modules/dist/styles/ag-grid.css:6:72 - Error: Module parse failed: Unexpected token (6:72)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  ****************************
| */
> ag-grid, ag-grid-angular, ag-grid-ng2, ag-grid-polymer, ag-grid-aurelia {
|   display: block;
| }

./node_modules/@ag-grid-community/all-modules/dist/styles/ag-theme-alpine.css:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .ag-theme-alpine {
|   -webkit-font-smoothing: antialiased;
|   color: #181d1f;

./node_modules/ag-grid-community/dist/styles/ag-grid.css:6:72 - Error: Module parse failed: Unexpected token (6:72)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  ****************************
| */
> ag-grid, ag-grid-angular, ag-grid-ng2, ag-grid-polymer, ag-grid-aurelia {
|   display: block;
| }

**Comment by StephenCooper** [comment]
Can you provide more information about all the versions you are using. i.e a package.json file.

Also does this error persist after a clean npm install.  i.e deleting node_modules and reinstalling the new versions from scratch.

**Comment by bloodyraoul** [comment]
same issue here

**Comment by bloodyraoul** [comment]
here is my package.json
```

{
  "name": "test",
  "version": "1.0.1",
  "description": "Ucass IS Hub (use angular latest, ngrx, fontawesome pro, angular material design)",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build-minify": "ng build --target=production --environment=prod",
    "build-stats": "ng build -- --configuration production --stats-json --extra-webpack-config webpack.extra.js",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "stats": "webpack-bundle-analyzer dist/stats-es2015.json",
    "test-CI": "ng test --karmaConfig=karma.conf.ci.js  --watch=false --code-coverage --browsers=ChromeHeadless --reporters=progress,junit"
  },
  "private": true,
  "dependencies": {
    "@ag-grid-community/all-modules": "^27.3.0",
    "@ag-grid-community/angular": "^27.3.0",
    "@ag-grid-enterprise/all-modules": "^27.3.0",
    "@angular/animations": "^14.1.0",
    "@angular/cdk": "^14.1.0",
    "@angular/common": "^14.1.0",
    "@angular/compiler": "^14.1.0",
    "@angular/core": "^14.1.0",
    "@angular/flex-layout": "^14.0.0-beta.40",
    "@angular/forms": "^14.1.0",
    "@angular/material": "^14.1.0",
    "@angular/material-moment-adapter": "^14.1.0",
    "@angular/platform-browser": "^14.1.0",
    "@angular/platform-browser-dynamic": "^14.1.0",
    "@angular/router": "^14.1.0",
    "@fortawesome/angular-fontawesome": "^0.10.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@handsontable/angular": "^12.1.2",
    "@microsoft/signalr": "^3.1.27",
    "@ngrx/data": "^14.0.2",
    "@ngrx/effects": "^14.0.2",
    "@ngrx/entity": "^14.0.2",
    "@ngrx/store": "^14.0.2",
    "@ngrx/store-devtools": "^14.0.2",
    "@swimlane/ngx-charts": "^16.0.0",
    "@types/jwt-decode": "^2.2.1",
    "@types/lodash": "^4.14.182",
    "ag-grid-angular": "^27.3.0",
    "ag-grid-community": "^27.3.0",
    "ag-grid-enterprise": "^27.3.0",
    "ang-jsoneditor": "^1.10.5",
    "angular-split": "^5.0.0",
    "core-js": "^3.23.5",
    "date-fns": "^2.28.0",
    "exceljs": "^4.3.0",
    "file-saver": "^2.0.5",
    "handsontable": "^12.1.2",
    "http-method-enum": "^1.0.0",
    "jsoneditor": "^9.9.0",
    "jspdf": "^2.5.1",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "ngx-build-plus": "^14.0.0",
    "ngx-cookie-service": "^14.0.1",
    "npm": "^8.14.0",
    "pako": "^1.0.11",
    "rxjs": "^6.5.5",
    "terser": "^5.14.2",
    "tslib": "^2.0.0",
    "xlsx": "^0.18.5",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.1.0",
    "@angular-eslint/builder": "14.0.2",
    "@angular-eslint/eslint-plugin": "14.0.2",
    "@angular-eslint/eslint-plugin-template": "14.0.2",
    "@angular-eslint/schematics": "14.0.2",
    "@angular-eslint/template-parser": "14.0.2",
    "@angular/cli": "^14.1.0",
    "@angular/compiler-cli": "^14.1.0",
    "@angular/language-service": "^14.1.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "^2.0.10",
    "@types/node": "^13.13.52",
    "@typescript-eslint/eslint-plugin": "5.29.0",
    "@typescript-eslint/parser": "5.29.0",
    "eslint": "^8.18.0",
    "flag-icon-css": "^3.5.0",
    "jasmine-core": "^3.99.1",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "^4.0.2",
    "karma-jasmine-html-reporter": "^1.7.0",
    "karma-junit-reporter": "^2.0.1",
    "protractor": "^7.0.0",
    "puppeteer": "^15.4.0",
    "ts-node": "~8.8.1",
    "typescript": "^4.6.4",
    "webpack-bundle-analyzer": "^4.5.0"
  }
}

```

**Comment by bloodyraoul** [comment]
after reworking my code to use pakckages and no more modules, i still have the issue

**Comment by StephenCooper** [comment]
As this is throwing in the styles can you share the code where you import the grid styles? Are you using CSS or SCSS or something else?

Trying to find the difference between our successful testing with Angular 14 and your app setup.

**Comment by bloodyraoul** [comment]
we are using SCSS

@import "~ag-grid-enterprise/dist/styles/ag-grid.css";

import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-alpine.css';

**Comment by StephenCooper** [comment]
Ok I can reproduce the error and it is caused by having the following lines as part of your Typescript component file. This doesn't error in v13 but does in v14. 

```ts
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-alpine.css';

@Component({...})
export class AppComponent {
```

If you move these to `styles.scss` and update to the `@import` syntax then your app should compile.

```
@import 'ag-grid-community/dist/styles/ag-grid.css';
@import 'ag-grid-community/dist/styles/ag-theme-alpine.css';
```

**Comment by bloodyraoul** [comment]
thank you so much !!! it works

**Comment by StephenCooper** [comment]
I understand that the Angular examples in our documentation import styles in the component so we will look to update these to avoid this issue for others in the future.

(Our example runner has a css loader which supports this approach unlike the default Angular CLI behaviour.)

**Comment by StephenCooper** [comment]
For reference https://github.com/angular/angular-cli/issues/23273

**Comment by rkromesh** [comment]
Hi Team,

 Migrating ag-grid from  24 version to 28 version and getting below error:

./node_modules/ag-grid-community/dist/styles/ag-grid.css?ngGlobalStyle:6:72 - Error: Module parse failed: Unexpected token (6:72)
****You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file**. See**** https://webpack.js.org/concepts#loaders
|  ****************************
| */
> ag-grid, ag-grid-angular, ag-grid-ng2, ag-grid-polymer, ag-grid-aurelia {
|   display: block;
| }

./node_modules/ag-grid-community/dist/styles/ag-theme-alpine.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
**![Ag-grid-Angular_Migration from 24 to 28 version](https://user-images.githubusercontent.com/59644995/220308897-5a9dfec3-f5be-467c-b0c2-c53a5c791840.jpg)** See https://webpack.js.org/concepts#loaders
> .ag-theme-alpine {
|   -webkit-font-smoothing: antialiased;
|   color: #181d1f;

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


"dependencies": {
    "@angular/animations": "^15.0.4",
    "@angular/cdk": "^15.0.3",
    "@angular/common": "^15.0.4",
    "@angular/compiler": "^15.0.4",
    "@angular/core": "^15.0.4",
    "@angular/flex-layout": "^14.0.0-beta.40",
    "@angular/forms": "^15.0.4",
    "@angular/localize": "^15.0.4",
    "@angular/material": "^15.0.3",
    "@angular/platform-browser": "^15.0.4",
    "@angular/platform-browser-dynamic": "^15.0.4",
    "@angular/router": "^15.0.4",
    "@ngrx/effects": "^12.0.0",
    "@ngrx/store": "^12.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@ruf/fis-ux-assets": "^4.25.0",
    "@ruf/material": "^16.3.0",
    "@ruf/moment-adapter": "^2.0.0",
    "@ruf/ngx-datatable": "^6.0.0",
    "@ruf/pipes": "^1.0.0-rc.0",
    "@ruf/prebuilt-themes": "5.9.1",
    "@ruf/query-builder": "^4.0.0",
    "@ruf/shell": "5.9.1",
    "@ruf/theming": "5.9.1",
    "@ruf/widgets": "^18.2.1",
    "@swimlane/ngx-charts": "^20.1.0",
    "ag-grid-angular": "^28.0.0",
    "ag-grid-community": "^28.0.0",
    "ag-grid-enterprise": "^28.0.0",
    "css-loader": "^6.7.3",
    "highcharts": "^9.3.3",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "ngx-cookie-service": "^12.0.0",
    "rxjs": "^7.4.0",
    "sass-loader": "^13.2.0",
    "style-loader": "^3.3.1",
    "tslib": "^2.0.0",
    "underscore": "^1.13.1",
    "webpack-cli": "^5.0.1",
    "webpack-dev-server": "^4.11.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.4",
    "@angular-devkit/core": "^15.0.4",
    "@angular/cli": "^15.0.4",
    "@angular/compiler-cli": "^15.0.4",
    "@nrwl/schematics": "^8.12.11",
    "@ruf/build-ruf": "^3.2.0",
    "@ruf/schematics": "~5.9.0",
    "@types/jasmine": "~3.6.0",
    "@types/jest": "^29.2.5",
    "@types/node": "^12.11.1",
    "@types/underscore": "^1.11.3",
    "codelyzer": "^6.0.0",
    "eslint": "^7.29.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-standard": "^5.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.8.4"
  },



Thanks
Ramesh

**Comment by sjmohideen** [comment]
Hi,
 I am also having same Problem. It was working till angular 14 when i try to upgrade to angular 15 then showing below error.
![image](https://github.com/ag-grid/ag-grid/assets/2750734/55763723-98ec-4764-b538-f4843ef1d3f5)

**Comment by jeevad** [comment]
Move the .css file from component to style.css. It works for me
