### ISSUE TITLE
Grid is not created when created on a Nodejs server

### ISSUE THREAD

**Issue by JoeVanGundy** [ag-grid/ag-grid#5392]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
I'm using Nodejs and Puppeteer to take a screenshot of the table for report usage.
All other parts of my app work properly, but the ag-grid is simply not created.

**Expected behavior**
The table should be ready and be rendered, but it's not.
Is there a flag or something that I to pass to allow something like this to work?
I have fixed heights and widths, and the div around ag-grid is rendered correctly with the right size.

Not sure if maybe I'm getting a screenshot somehow before the grid is loaded?
But that doesn't really track with how all of my other features are working.

Any help would be super appreciated!

**Please tell us about your environment:**
Mac, Nodejs, Chromium, npm, 

* **AG Grid version:** X.X.X
28.0.0

* **Browser:**
Chromium

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Javascript/React

**Comment by seanlandsman** [comment]
Do you have a repo we can look at to reproduce what you're seeing? It's worth noting that ag-grid requires a browser environment to work - it's not designed to work in a headless/server only environment which probably explains the behaviour you're seeing
