### ISSUE TITLE
`AG Grid: duplicate node id 'NodeId'`  after node was removed.

### ISSUE THREAD

**Issue by Overrided** [ag-grid/ag-grid#5393]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

I'm using grid as a `tree-view` with `ssrm`.
And case is, I need to REMOVE WHOLE TREE, and insert new data.
New data can have same nodes (same data) that old data had.

To remove data already loaded in grid I use:
```
for(const nodeRoute of nodes) {  // `nodes` are list of group nodes
            this.gridApi.applyServerSideTransaction({
                route: nodeRoute, // route to particular group node in a tree
                remove: childNodes // child nodes that belong to that particular group
            });
}
```
When all nodes are removed - at list when AgGrid instance UI becomes empty and displays no nodes - I try to force it to load new data using:
```
this.gridApi.refreshServerSideStore({
            purge: true
});
```
which triggers `serverSideDatasource` to load new data.

Once I'm trying to add new data after old data was removed - `AgGrid` spits tonns of warnings like  `AG Grid: duplicate node id NodeId_Goes_Here` , logs those duplicate nodes ans UI becomes messed up.

**Expected behavior**

Expected behaviour is to not have any duplicates as I've removed those starting from very leafs of tree, and UI should't be broken?
Maube there's some workaround this? 

**Please tell us about your environment:**

Windows 11 Pro, Visual Studio Code, npm, NodeJS

* **AG Grid version:** X.X.X
`27.0.0` - unfortunatelly, I can't upgrade version.

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.0.2 / Angular 11.2.9

**Comment by StephenCooper** [comment]
We would require a reproduction to provide further assistance on this issue as I cannot quickly reproduce the errors that you are seeing.

Also we would recommend raising this through our Zendesk support system as it looks like you are an Enterprise Customer. 

<hr/>

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact [info@ag-grid.com](mailto:info@ag-grid.com) for access. This is our primary channel for Support.

**Comment by Overrided** [comment]
Thanks for response!
Can't reproduce this now. Looks like a bug in my code.
