### ISSUE TITLE
First cell in header receives focus but navigateToNextHeader is not called

### ISSUE THREAD

**Issue by wein2011** [ag-grid/ag-grid#5400]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Navigating left from first column of header does not call navigateToNextHeader

1) Click the first cell in the header
2) Click the left arrow key

Navigating right from last column of header also does not call navigateToNextHeader

All other types of navigation work as expected.

**Current behavior**
First cell in header receives focus but navigateToNextHeader is not called

**Expected behavior**
navigateToNextHeader should have been called

**Please tell us about your environment:**
Windows 11

* **AG Grid version:** 28.0.2

* **Browser:**
Edge: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71'
Chrome: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
Firefox: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript: 4.7.4

**Comment by StephenCooper** [comment]
Hi @wein2011,

I have raised this in our internal Zendesk system for further investigation as I see there is different behaviour with up arrow on the top header as opposed to left arrow on the left most column.

https://plnkr.co/edit/3fHbrzJivntowwBQ?open=main.ts
