### ISSUE TITLE
Incorrect type for "rowPinned" property of "rowNode"

### ISSUE THREAD

**Issue by JohannCooper** [ag-grid/ag-grid#5406]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The current type for the `rowPinned` property of the `rowNode` type is defined as follows in `community-modules/core/src/ts/entities/rowNode.ts`:
```ts
/** Either 'top' or 'bottom' if row pinned, otherwise `undefined` or `null`. */
public rowPinned: string;
```
Not only is this type incorrect (excludes the `undefined` and `null` cases), it is also not as narrow as it could be.

**Expected behavior**
I would suggest changing the type to the following:
```ts
/** Either 'top' or 'bottom' if row pinned, otherwise `undefined` or `null`. */
public rowPinned: "top" | "bottom" | undefined | null;
```

**Please tell us about your environment:**

* **AG Grid version:** 28.0.0

* **Browser:** Any

* **Language:** TypeScript

**Comment by gportela85** [comment]
this should be addressed by this PR - https://github.com/ag-grid/ag-grid/pull/5407

Thanks for reporting
