### ISSUE TITLE
Demos broken for Vue

### ISSUE THREAD

**Issue by cworkschris** [ag-grid/ag-grid#5411]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker
Following your blog:
https://blog.ag-grid.com/adding-hyperlinks-to-the-grid/
"Again, the example below was created using vanilla JS but we have also prepared examples using [React](https://plnkr.co/edit/CRwrgPzn81HKYI3g), [Angular](https://plnkr.co/edit/zGbXbfvu9bngBIHd), and [Vue](https://plnkr.co/edit/AndP3G7ux53DiAoG)."

Click the Vue link:
https://plnkr.co/edit/AndP3G7ux53DiAoG

Within plnkr, click "Click to run" on the right
And it will display "Loading Vue example..." indefinitely

It might be your example was done in Vue2 but the cdn reference is not version pinned.

* **Browser:**

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

**Comment by seanlandsman** [comment]
Thanks for reporting this - I'll get the blog updated.

For now you can use this plunker as reference on how to use hyperlinks in cells with Vue: https://plnkr.co/edit/H2wj4T9mtnzpgAYw

**Comment by seanlandsman** [comment]
We've updated both Vue examples on that blog - thanks very much for reporting this.
