### ISSUE TITLE
Integrated charts does not show object values created with valueGetter

### ISSUE THREAD

**Issue by jagoral** [ag-grid/ag-grid#5424]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I tried to create an integrated chart for a multi-column aggregated column from this [example](https://www.ag-grid.com/react-data-grid/aggregation-custom-functions/#multi-column-aggregation), but unfortunately the values are not present on the chart. Probably it's related to the way how the aggregation is handled - in column an object is stored with `toString` method which is not invoked in the chart, but this is only my hypothesis. 

I'm a "wannabe" customer of ag-grid.

**Reproducible Scenario**
1. Open [plunker](https://plnkr.co/edit/wvqEeZS8GBxwZ6Wl?open=index.tsx&preview)
2. Focus on any cell in the grid
3. Select all data (for example with ctrl/command + a)
4. Right click and generate a chart, for example: Pivot Chart -> Line

**Current behavior**
Ratio values are not included on the chart

**Expected behavior**
Ratio values are included on the chart.

**Please tell us about your environment:**
macOs Big Sur

* **AG Grid version:** 28.0.0

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'

* **Language:** all

Additional question (offtop): even if this will work, it seems that the chart does not respect `valueFormatter` option in the column. I want to have the yAxis labels formatted with the `valueFormatter`, but the plain column value is taken. Does anyone know how to change it?

**Comment by rmc-software** [comment]
Hi,

Thank you for reporting this issue. This should be fixed in our latest version (v28.1).

I have updated your plunker to point to v28.1: 

https://plnkr.co/edit/cG3mqJlBJoDQee5H?open=index.tsx

Thanks
