### ISSUE TITLE
header is not aligning after resize and scroll to end

### ISSUE THREAD

**Issue by devonoccasion** [ag-grid/ag-grid#5425]
**I'm submitting a ...**
```
[x] bug report
```

**Providing a Reproducible Scenario**
Plunker:
https://plnkr.co/edit/bHNaxq80oERrwKX8?open=main.js
Description:

1. Open Plunker
2. Zoom in with your browser to 200%
3. Scroll to the maximum right
4. Select the first row in the last column (Total)
5. Compare the cell border with the header border, they are not aligned anymore

![image](https://user-images.githubusercontent.com/5937471/182119166-33fbb7b0-304f-486c-ac60-7bf46bbe2f6a.png)

**Current behavior**
the cell and header do not align if you resize the page and scroll to the end.

**Expected behavior**
the cell and header should align every time

**Please tell us about your environment:**
Windows 10

* **AG Grid version:** 28.0.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'

* **Language:** 
all

I have noticed that if I move the horizontal scrollbar with css the bug will not happen anymore but this creates a new bug, where the last column is not fully displayed if there is a vertical scrollbar
`.ag-horizontal-right-spacer.ag-scroller-corner {
    display: none;
  }`

**Comment by StephenCooper** [comment]
I followed your instructions but could not reproduce what you are seeing. 

Zoomed 200%, scrolled to right and then selected the total column

On a windows machine using Chrome 104.

![headeraligned](https://user-images.githubusercontent.com/20125490/183672596-393b5a9c-cdf0-47da-bb70-82470e62d073.png)

**Comment by devonoccasion** [comment]
Have you tried scrolling with the mouse or keyboard? If I use the keyboard it works as expected. With mouse scroll, all of my colleagues are able to reproduce it. Is the "Total" column already visible on your screen? Maybe your preview screen shows more columns initially. My Plunker preview screen has a width of  ~1000px and the last two columns are not rendered in the DOM because of column virtualisation. Hope I can help top reproduce it.

**Comment by rmc-software** [comment]
Hi Devonoccasion,

We still can't reproduce it however we do accept that there can be issues in browsers calculating border sizes with border zoom - sometimes row borders won't be displayed or extra pixels may appear. Due to this we don't support browser zoom because the behavior is too different for different monitors and that's probably why you are seeing an issue and we don't.
