### ISSUE TITLE
invalid-aria-prop warning

### ISSUE THREAD

**Issue by nicolasrios-rl** [ag-grid/ag-grid#5426]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Low priority. React is throwing an invalid-aria-prop warning: 
"Warning: Invalid aria prop 'aria-description' on div tag."
Aria-description does not exist in the Web Accessibility Initiative (WAI) Accessible Rich Internet Application (ARIA) [specification](https://www.w3.org/TR/wai-aria-1.1/).

I believe this only affects two files ->
[grid-packages/ag-grid-react/src/reactUi/header/headerCellComp.tsx](https://github.com/ag-grid/ag-grid/blob/11a655733045e51e50ed5a9c37d4771d96d8c0b9/grid-packages/ag-grid-react/src/reactUi/header/headerCellComp.tsx)
[community-modules/react/src/reactUi/header/headerCellComp.tsx](https://github.com/ag-grid/ag-grid/blob/11a655733045e51e50ed5a9c37d4771d96d8c0b9/community-modules/react/src/reactUi/header/headerCellComp.tsx)

This could be replaced by aria-labelledby (concise) or aria-describedby (more verbose).

**Comment by gportela85** [comment]
@nicolasrios-rl This is actually a bug with React trying to validate aria props, they have fixed the issue. 
This is a React issue, see: https://github.com/facebook/react/issues/21035

This has also been reported here by:

https://github.com/ag-grid/ag-grid/issues/5211
https://github.com/ag-grid/ag-grid/issues/5200
https://github.com/ag-grid/ag-grid/issues/5258
