### ISSUE TITLE
cellRender that returns a html string no longer renders HTML (since ag-grid-react@6.2.0)

### ISSUE THREAD

**Issue by PablocFonseca** [ag-grid/ag-grid#5427]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello, 

I'm using ag-grid in streamlit-aggrid wrapper and I noticed that versions after ag-grid-react@6.2.0 no longer renders HTML in cells  with cellRenderer specified as a function that returns an 'HTML String', as the documentation stated [here](https://www.ag-grid.com/javascript-data-grid/component-cell-renderer/#cell-renderer-function). It renders the string itself instead. 

The plunker with a reproductible scenario is here: https://plnkr.co/edit/vnQTtGG9k4oMR1Fm?open=index.jsx
on this plunker if you change line 36 of index.html from: 
```html
                "@ag-grid-community/react": "https://unpkg.com/@ag-grid-community/react@28.0.0/",
``` 
to:
```html
                "@ag-grid-community/react": "https://unpkg.com/@ag-grid-community/react@26.2.0/",
````
the example has the expected behaviour: It renders the number of medals in the third column in <b>BOLD</b>.

Having the old behaviour is essential for my [Project](https://github.com/PablocFonseca/streamlit-aggrid), because I need to convert text strings that come from Python side into JS Code on Ag-grid side and this is the core of designing custom cellRenderers in Python.

Any suggestions on how to do it on ag-grid-react versions higher than 26.3.0?

**Comment by seanlandsman** [comment]
`ag-grid-react` no longer supports either javascript functions or functions that return html strings from 27 onwards.

You can return jsx (ie instead of `return "<div>Hello</div>";` return `return <div>Hello</div>;' instead.

You can see all changes in the release notes here: https://www.ag-grid.com/changelog/?fixVersion=27.0.0

**Comment by ecal99** [comment]
I'm running into the same problem as Sean, and I am sure many others will as well. Is there an "easy" way to turn a hyperlink as a string into something AG Grid will allow to be rendered as a hyperlink?

Thanks!
Ed

**Comment by fplanque** [comment]
@seanlandsman why did you decide to stop supporting HTML strings? (besides code purity)

Some of us use AGGrid wrapped in Python. To my knowledge there is no way for us to generate JSX in Python :'(

**Comment by StephenCooper** [comment]
Please see comment on linked ticket. 

https://github.com/PablocFonseca/streamlit-aggrid/issues/198#issuecomment-1465728051
