### ISSUE TITLE
Issue with resizing after column is removed from table using setColumnVisible 

### ISSUE THREAD

**Issue by nagarjuna5808** [ag-grid/ag-grid#5432]
**I'm submitting a support request for resizing the table for react application**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Once AG grid table is loaded,  we are hiding column with  setColumnVisible method, by passing column headerName and true/false flag.
After hiding or showing the column table is not getting resized. 

We are using gridColumnApi.sizeColumnsToFit(); in useEffect with table rowdata as dependency. 
But no resize is happening to table. 

We need solution to resize columns in table after this functionality. 

**Current behavior**
After hiding or showing the column using setColumnVisible, table is not getting resized. 

**Expected behavior**

We need solution to resize columns in table after removing column. 

**Please tell us about your environment:**

Windows OS, Visuals Studio code IDE

* **AG Grid version:** "ag-grid-react": "^27.3.0"

* **Browser:**

All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React 17.0.1, Javascript

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!
