### ISSUE TITLE
Builds are failing using Vue3, Vite and Typescript

### ISSUE THREAD

**Issue by CiaranPearse** [ag-grid/ag-grid#5435]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Using Vue3, Vite & Typescript everything is fine on dev but builds are failing with the following error

Tests are also failing with same error
```
[commonjs--resolver] Identifier 'watch' has already been declared
file: C:/Users/xxxxxxx/code-app/node_modules/ag-grid-vue3/lib/AgGridVue.js
var DATA_MODEL_ATTR_NAME = 'onUpdate:modelValue'; // emit name would be update:ModelValue
var DATA_MODEL_EMIT_NAME = 'update:modelValue';
var _a = getAgGridProperties(), props = _a[0], watch = _a[1];
    ^
export var AgGridVue = defineComponent({
 render: function () {
error during build:
Error: Identifier 'watch' has already been declared
    at error (file:///C:/Users/xxxxxxx/code-app/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///C:/Users/xxxxxxx/code-app/node_modules/rollup/dist/es/shared/rollup.js:12411:16)
    at Module.tryParse (file:///C:/Users/xxxxxxx/code-app/node_modules/rollup/dist/es/shared/rollup.js:12788:25)
    at Module.setSource (file:///C:/Users/xxxxxxx/code-app/node_modules/rollup/dist/es/shared/rollup.js:12693:24)
    at ModuleLoader.addModuleSource (file:///C:/Users/xxxxxxx/code-app/node_modules/rollup/dist/es/shared/rollup.js:22135:20)
error Command failed with exit code 1.
```

Changing 'watch' to 'watcher' like below seems to fix the issue, but I really don't want to have to change the package code.
![image](https://user-images.githubusercontent.com/630810/182646603-13518323-680a-4a0f-a0c0-0e323a321c7d.png)

**Expected behavior**
Build would not fail.

**Please tell us about your environment:**
Win, Chrome

* **AG Grid version:** X.X.X
28.0.2

* **Browser:**
N/A - issue is on build and test

**Comment by StephenCooper** [comment]
hi @CiaranPearse,

Thanks for reporting this, we will investigate this further as from first appearance it does look like a bug that can be avoided.

**Comment by CiaranPearse** [comment]
@StephenCooper 
`const [props, watch] = getAgGridProperties();`

also fixes it.

**Comment by StephenCooper** [comment]
> @StephenCooper `const [props, watch] = getAgGridProperties();`
> 
> also fixes it.

Isn't this what the existing code is?

https://github.com/ag-grid/ag-grid/blob/55b387e0b1da28862bd4793e3076fc8ba2e531c9/community-modules/vue3/src/AgGridVue.ts#L14

**Comment by StephenCooper** [comment]
I have tried to reproduce the error myself with the following repo but I am not able to. 

https://github.com/StephenCooper/vite-vue3-template

Are you able to either update my repo above so that it will fail the build as you see or provide another sample that we can use to validate the fix?

**Comment by CiaranPearse** [comment]
> I have tried to reproduce the error myself with the following repo but I am not able to.
> 
> https://github.com/StephenCooper/vite-vue3-template
> 
> Are you able to either update my repo above so that it will fail the build as you see or provide another sample that we can use to validate the fix?

I can build fine but cannot build storybook (sorry - I thought I clarified that in my initial post)

**Comment by CiaranPearse** [comment]
> > @StephenCooper `const [props, watch] = getAgGridProperties();`
> > also fixes it.
> 
> Isn't this what the existing code is?
> 
> https://github.com/ag-grid/ag-grid/blob/55b387e0b1da28862bd4793e3076fc8ba2e531c9/community-modules/vue3/src/AgGridVue.ts#L14

For me the code in AgGridVue.js (28.1.0) is
```var _a = getAgGridProperties(), props = _a[0], watch = _a[1];```

![image](https://user-images.githubusercontent.com/630810/184911889-babb94cc-d9b2-43ec-bbba-7cbe14016f3f.png)

**Comment by CiaranPearse** [comment]
Also failing causing an issue in tests
![image](https://user-images.githubusercontent.com/630810/185084367-56ad6631-c2ab-48d7-a0a7-c1ae23fcadd6.png)

**Comment by StephenCooper** [comment]
> > I have tried to reproduce the error myself with the following repo but I am not able to.
> > https://github.com/StephenCooper/vite-vue3-template
> > Are you able to either update my repo above so that it will fail the build as you see or provide another sample that we can use to validate the fix?
> 
> I can build fine **but** cannot build storybook (sorry - I thought I clarified that in my initial post)

Ok, if possible can you set up a small reproduction using Storybook or with tests. I am afraid that we won't be able to prioritise this issue without a way of testing it ourselves.

**Comment by CiaranPearse** [comment]
@StephenCooper repo below which is breaking on the following cmds:
yarn build
yarn test

https://github.com/CiaranPearse/aggrid-breaking

You'll note that the line thats causing the issue *should* be 
`const [props, watch] = getAgGridProperties();`
but instead is
`var _a = getAgGridProperties(), props = _a[0], watch = _a[1];`

**Comment by seanlandsman** [comment]
Thank you @CiaranPearse  - I'll take a look at this issue over the next week and update this thread accordingly

thanks

**Comment by seanlandsman** [comment]
I've tracked the cause of this issue down and have applied a fix for it - this will be available in our next release (currently scheduled for the end of the month).

Thank you for raising this as well as the reproducible example which allowed me to verify the fix.

**Comment by seanlandsman** [comment]
Please note that you can get around this issue for now by switching to [modules](https://www.ag-grid.com/vue-data-grid/modules/) instead - in other words use `@ag-grid-community/vue3` instead of `ag-grid-vue3`
