### ISSUE TITLE
Horizontal Scrollbar Does Not Appear On Hover

### ISSUE THREAD

**Issue by benshope** [ag-grid/ag-grid#5436]
**I'm submitting a:** 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

I am a customer of ag-grid  but I don't know our corporate account.

**Current behavior**
The horizontal scrollbar does not appear when hovering over the grid.

The bug is easily visible on your docs: https://www.ag-grid.com/react-data-grid/scrolling-scenarios/

I think this regression happened between ag-grid 26 and ag-grid 27.

**Expected behavior**
The horizontal scrollbar should appear when hovering over the grid.

**Please tell us about your environment:**
16" Macbook Pro

**AG Grid version:** 28.0.0

**Browser:** 
Chrome
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

 **Language:** [all]

**Comment by rmc-software** [comment]
Hi Benshope,

We don't see any differences between v26 and v28.1:

v26 - https://www.ag-grid.com/archive/26.0.0/react-data-grid/scrolling-scenarios/
v28.1 - https://www.ag-grid.com/react-data-grid/scrolling-scenarios/

We tested the examples above with scrollbars to 'always show' and 'only show when scrolling' using the MacOS system preferences.

Note that scrollbars don't show by hovering the grid, only when scrolling.

Based on this analysis we are going to close this issue.

**Comment by benshope** [comment]
@rmc-software okay just be aware that there is some difference. Here are snapshots on our grid for 26.2 vs 28.  Note the persistent horizontal scrollbar on 26. Our users have said something about the change.

26.2:
<img width="1397" alt="Screen Shot 2022-08-09 at 11 27 50 PM" src="https://user-images.githubusercontent.com/3506088/183807698-04820eaa-b7fc-4924-a164-bc136139f8a6.png">

28:
<img width="1395" alt="Screen Shot 2022-08-09 at 11 27 59 PM" src="https://user-images.githubusercontent.com/3506088/183807722-fc3db49b-fc4f-4e10-a8c2-29c7eb113b0a.png">

**Comment by gportela85** [comment]
@benshope That was actually a bug, "invisible" scrollbars are only meant to be displayed for a few seconds and then disappear. The issue you see on 26.2 cause the scrollbar to block half of the last row of the grid, sometimes making it hard to click/edit the cells "behind" it.

**Comment by benshope** [comment]
@gportela85 thanks for the explanation! I agree that hiding the scrollbars is best
