### ISSUE TITLE
cellRendererSelector doesnt work

### ISSUE THREAD

**Issue by loremru** [ag-grid/ag-grid#5441]
resolveComponent can only be used in render() or setup().
` 
 "ag-grid-community": "28.1.0",
    "ag-grid-enterprise": "28.1.0",
    "ag-grid-vue3": "28.1.0",
 `
![image](https://user-images.githubusercontent.com/66596500/182821206-03ff8cff-e955-4ea4-abc3-ecc9a37b9db0.png)
![image](https://user-images.githubusercontent.com/66596500/182821325-d6f5756a-f441-47f2-9928-f1cb3a98969a.png)

**Comment by seanlandsman** [comment]
HI,

This seems like a support question and it sounds like you have an ag-grid license or are evaluating AG Grid Enterprise. Note that github is not our main channel for support for customers (i.e. users of `ag-grid-enterprise`).

You should contact us through zendesk - you should have access already at https://ag-grid.zendesk.com/

If that is not the case, or you are having trouble, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) where they will be able to assist you with your access.

Thanks

**Comment by loremru** [comment]
> HI,
> 
> This seems like a support question and it sounds like you have an ag-grid license or are evaluating AG Grid Enterprise. Note that github is not our main channel for support for customers (i.e. users of `ag-grid-enterprise`).
> 
> You should contact us through zendesk - you should have access already at https://ag-grid.zendesk.com/
> 
> If that is not the case, or you are having trouble, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) where they will be able to assist you with your access.
> 
> Thanks

I havent license yet and you recommend me to buy broken table for getting help with bug ?)

**Comment by StephenCooper** [comment]
Hi @loremru,

Could you please provide a reproduction that will enable us to investigate this issue further? At the moment we do not have enough information to be able to help you out.

We have examples that show working examples of `cellRendererSelector`, for example [here](https://plnkr.co/edit/rqUtPKJHR9CaCP66?open=main.js) taken from our [docs](https://ag-grid.com/vue-data-grid/cell-rendering/#many-renderers-one-column). These do not run into the reported issue above.

**Comment by loremru** [comment]
that was vue/vite bug

project needed to update this packages to last versions
