### ISSUE TITLE
ag-grid 24.0.0 (Angular) requires Peer Dependency of Angular 14 packages

### ISSUE THREAD

**Issue by Alex0u** [ag-grid/ag-grid#5445]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Similar to : [ag-grid/issues/4110](https://github.com/ag-grid/ag-grid/issues/4110)

**Providing a Reproducible Scenario**
- Make a new angular application and specify ag-grid v24 dependencies :
`
"@angular/animations": "^14.1.0",
  "@angular/cdk": "^14.1.0",
  "@angular/common": "14.1.0",
  "@angular/compiler": "^14.1.0",
  "@angular/core": "^14.1.0",
  "@angular/material": "^14.1.0",
  "@angular/router": "^14.1.0",
  "ag-grid-angular": "24.0.0",
  "ag-grid-community": "24.0.0",
  "ag-grid-enterprise": "24.0.0",
`
then npm install

**Current behavior**
npm install failed with peer dependency : 
- peer @angular/common@"^9.0.0" from ag-grid-angular@24.0.0

**Expected behavior**
Expect that v24.0.0 can be installed in an Angular 14 project without a Peer Dependency error.

[Docs](https://www.ag-grid.com/angular-data-grid/angular-compatibility/) indicate that Angular 14 is supported by v24

**Please tell us about your environment:**
Installed in linux red hat using npm 8.11.0, node 16.15.1. Angular 14.1.0 project.

* **AG Grid version:** 24.0.0 which is not a problem anymore in recent versions but my license is valid only for 24.0.0

* **Browser:**
N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

**Comment by StephenCooper** [comment]
Hi @Alex0u,

Thanks for pointing this out. After inspecting the package.json files for `ag-grid-angular` I will be updating the table to the following in the next release as this table was incorrect. Apologies for the confusion.

v24 is only officially support up to Angular 11. While it is not officially supported I expect that it will still work. 

 | Angular | AG Grid   | AG Grid Legacy      |
 | --------| --------- | --------------------|
 | 10 - 11 | 24 - 27   | 28+                 |
 | 12+     | 25 - 28+  | 28+ (not recommend) |

If you want to use v24 with Angular 14 you will need to use the `--force` option when doing your install.
