### ISSUE TITLE
cellEditorPopup misbehaves in agRichSelectCellEditor

### ISSUE THREAD

**Issue by dalexander-trc** [ag-grid/ag-grid#5450]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Editor appears in a popup on cell double click. Popup is only closeable **if** the user:
1. clicks on an option in the popup
2. clicks on another non-header row in the grid
3. hits the ESC key

**Expected behavior**
The editor popup should close with **any** outside mouse click, per the [docs](https://www.ag-grid.com/angular-data-grid/cell-editors/#popup).

> The popup will behave like a menu in that any mouse interaction outside of the popup will close the popup.

**Reproducible Scenario**
This behavior is visible in the cell editor samples within the documentation. All frameworks display the same problem. I've included a basic column def here for searching.
https://www.ag-grid.com/examples/provided-cell-editors/editors/packages/angular/index.html

```
columnDefs: [
    {
        cellEditor: 'agRichSelectCellEditor',
        cellEditorPopup: true,
        cellEditorParams: {
            values: ['English', 'Spanish', 'French', 'Portuguese']
        },
        filter: 'agSetColumnFilter',
        filterParams: {
            values: ['English', 'Spanish', 'French', 'Portuguese']
        }
    }
]
```

**Please tell us about your environment:**

* **AG Grid version:** 27.3.0, 28.1.0

* **Browser:** Chrome 103.0.5060.134, Firefox 103.0.1

* **Language:** All

**Comment by StephenCooper** [comment]
hi @dalexander-trc ,

This behaviour is configurable for the rich select with the gridOptions [property](https://ag-grid.com/javascript-data-grid/grid-options/#reference-editing-stopEditingWhenCellsLoseFocus) `stopEditingWhenCellLoseFocus`

You can see this in action in the following plunker. Note how now the dropdown closes with any click outside the cell.

https://plnkr.co/edit/bxkB15rdehlUYKUf?open=main.ts

I can understand that our docs do not make this clear and so we will take a look at improving those. I will close this ticket now as I believe this should unblock you.

**Comment by dalexander-trc** [comment]
@StephenCooper Thank you for the quick response! 

Yes the `cellEditorPopup` property states that it should close with any outside mouse click and the `stopEditingWhenCellLoseFocus` property specifically says that it is for **non-popup** types. 

The plnkr sample does work as you've described though, so the problem seems to be with the documentation!
