### ISSUE TITLE
Server-Side doesn't support transaction API as informed by the features site

### ISSUE THREAD

**Issue by gustavomick** [ag-grid/ag-grid#5453]
Current Row Model Comparisons documentation implies Server-Side mode supports transactions API, but is not correct, it only supports it when store is full mode, but that mode currently has lot of limitations which in practice makes it not usable on production systems.

If this assumption is valid should be important to update site documentation to avoid client misinformation.

Please provide confirmation and if possible a reference to the actual way to add rows to a SS without workaround thru datasource ad-hoc row. 

couple references:
- If SS mode is serverSideStoreType = "partial",  transaction will reject with message due`Store is type Partial, which doesn't accept transactions`, also this message is hidden to the client.  https://github.com/ag-grid/ag-grid/blob/46d93715975768bf780ce01d54b5cd1307d21621/community-modules/core/src/ts/interfaces/serverSideTransaction.ts#L52, 
- if SS mode is serverSideStoreType = "full" transaction can be applied but then basic features like paging, sort, seems not working.

![image](https://user-images.githubusercontent.com/4327429/183301730-bcebc30d-2139-4e31-8490-f96cc1ba3424.png)

https://www.ag-grid.com/javascript-data-grid/row-models/#row-model-comparisons
https://www.ag-grid.com/angular-data-grid/server-side-model-transactions/

Thanks!

**Comment by StephenCooper** [comment]
Hi @gustavomick, 

Thanks for bringing this to our attention and providing such clear details. I have raised this in our support system for further investigation / fix.

**Comment by rmc-software** [comment]
Hi Gustavomick,

Apologies for the confusion around SSRM transactions. We do cover this at the start of the ["Updating Data"](https://ag-grid.com/javascript-data-grid/server-side-model-updating/) section:

![Screen Shot 2022-08-11 at 11 21 20 PM](https://user-images.githubusercontent.com/28864741/184252404-c084c39e-5797-420c-9c3d-2260166b8ee1.png)

However we agree we should also make it clearer on the [Row Models Comparisons](https://ag-grid.com/javascript-data-grid/row-models/#row-model-comparisons) matrix. This note will appear on our next website update:

![Screen Shot 2022-08-11 at 11 18 14 PM](https://user-images.githubusercontent.com/28864741/184252631-6c21936c-6a52-4193-92ec-cbc57739f9d1.png)

Thanks again for bringing this to our attention.

Rob

**Comment by gustavomick** [comment]
@rmc-software I don't think that your answer is correct, It only works in full store mode which is the basic mode for SS which is the one with fewer features. 

Basically in order to make it work is needed to disable primary SS features like lazy loading. 
If not the case please provide an example so we can use it and make it clear for us.

Thanks!!

**Comment by gustavomick** [comment]
@StephenCooper may be you can bring me some clarity to this, seems to me ticket was closed but with incorrect response.

Can we have lazy load (SS) + Transactions?

 thanks!

**Comment by StephenCooper** [comment]
Hi @gustavomick, 

> Can we have lazy load (SS) + Transactions?

Short answer no. 

Rob is correct in what he said in that transactions are only supported when infinite scrolling is disabled. This is the terminology of v28. Previous versions of the documentation talked about Full and Partial stores which I believe is what you are referring to. 

If you look at v27 archive you will see the following section also mention that transactions are only supported in the full store which as you correctly point out does not work in an infinite scroll manner. 
 
https://www.ag-grid.com/archive/27.0.0/javascript-data-grid/server-side-model-row-stores/#partial-store-restrictions

I hope this brings some clarity but if not let me know and will try and explain it further.

**Comment by gustavomick** [comment]
@StephenCooper thanks for the clarification!

**Comment by ldbmcs** [comment]
Maybe, Should add some additional information in [SSRM Transactions](https://www.ag-grid.com/react-data-grid/server-side-model-updating-transactions/), i don't know why `applyServerSideTransaction` is not working if don't know row stores.
