### ISSUE TITLE
Maximum call stack size exceeded error thrown when reducing the page width and when passing same gridOptions to two grids

### ISSUE THREAD

**Issue by robrichardson27** [ag-grid/ag-grid#5454]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

[New Recording - 08_08_2022, 09_30_48.webm](https://user-images.githubusercontent.com/24434733/183375162-7be55625-7257-4e87-83cb-ab59f956d4cf.webm)

**Providing a Reproducible Scenario**

1. Create two grids that share the same `gridOptions` object (see [stackblitz](https://stackblitz.com/edit/angular-ivy-uccbk7?file=src%2Fapp%2Fapp.component.html))
2. Reduce and then expand the window width
3. Maximum call stack size exceeded error thrown

**Current behavior**
Maximum call stack size exceeded error thrown

**Expected behavior**
No error thrown

**Please tell us about your environment:**

* **AG Grid version:** 28.1.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

* **Language:** all

**Comment by StephenCooper** [comment]
Hi @robrichardson27,

We do not support passing the same gridOptions to multiple grids. I see you have the work around of creating a new gridOptions instance in your demo to resolve the issue. 

If you are looking to have two grids kept in sync then I would recommend using the [Aligned Grids](https://www.ag-grid.com/angular-data-grid/aligned-grids/) feature instead.
