### ISSUE TITLE
Some rows lose their border after more than about 1 million rows

### ISSUE THREAD

**Issue by RTcyan** [ag-grid/ag-grid#5456]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
See: [StackBlitz](https://stackblitz.com/edit/ag-grid-angular-hello-world-xrg8cd?file=src/app/app.component.ts)

**Current behavior**
If we scroll to more than 1 million rows, some rows will start to lose their borders.

![image](https://user-images.githubusercontent.com/49360876/183409927-d87c3a60-3b7d-4c18-b18c-bc0a0fc7957e.png)

**Expected behavior**
All rows should have borders.

* **AG Grid version:** 28.1.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

* **Language:** Angular 14, TypeScript 4.7.2

Many thanks.

**Comment by gportela85** [comment]
@RTcyan This could be caused by a couple of different reasons:
1 - Usually you will have problems with borders disappearing like this when you have the browser zoom set to a value other than 100%.

2 - Chrome has had some issues reported when scrollbar is below a certain point in tall containers, see: https://github.com/ag-grid/ag-grid/issues/4793

**Comment by kiril-matev** [comment]
Hello @RTcyan,

Thank you for reporting this.

We were able to reproduce this behavior using the steps below:
1. Open (reduced example)
https://stackblitz.com/edit/ag-grid-angular-hello-world-y4vcne?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts
2. Set browser zoom to 110%
3. Scroll down to the bottom
**Actual**: Borders between some rows are not displayed
**Expected**: Borders between all rows are not displayed

![CPT2208081746-392x611](https://user-images.githubusercontent.com/60937283/183470376-db92e74e-a8ba-4292-8b8f-dcbfa0819da6.gif)

We've confirmed that this issue cannot be reproduced when using browser zoom=100%. At this time, please keep the browser level to 100% to avoid this issue.
