### ISSUE TITLE
OnRowClicked event with Ctrl + Click does not open the new tab in the background

### ISSUE THREAD

**Issue by tiberiuzuld** [ag-grid/ag-grid#5457]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/f3bp8Gesep2pb0m5?open=main.js

**Current behavior**
When the user presses Ctrl + Left Click on a row **does not** open the new tab in the background (without focus)

**Expected behavior**
When the user presses Ctrl + Left Click on a row **does** open the new tab in the background (without focus)
In the plunker example I included a normal button when used it will open the new tab

**Please tell us about your environment:**
Windows 10

* **AG Grid version:** X.X.X
28.1.0

* **Browser:**
Chrome 104

* **Language:**
All

**Comment by StephenCooper** [comment]
I have not been able to reproduce this. On a windows machine when I do Ctrl + Left click I get the same behaviour from the grid and the external button in your plunker. Also using Chrome 104.

**Comment by foxed66** [comment]
Hello, I have exactly the same problem. 
I'd like to have the same behavior as when you click the button (see the plunker example). 
On the Ctrl+click of the grid, I don't have this behavior. 
I welcome any information that would allow me to correct this problem. 
Thank you

**Comment by AG-Zoheil** [comment]
Hi @foxed66,

We are unable to reproduce the issue you are describing on both Windows & Apple devices. Can you please check there is nothing system specific preventing you from opening tabs in the background or using keyboard controls like CTRL.

I'm afraid as we are not able to reproduce it with the example provided, we are not able to provide any further guidance.

Thanks!

**Comment by foxed66** [comment]
Thanks for the info. 
I want it to work on firefox. May be a problem with chrome.
Too bad, I'm going to keep looking.
