### ISSUE TITLE
Cannot pass colgroupdef to .setColumnDefs()

### ISSUE THREAD

**Issue by jackdh** [ag-grid/ag-grid#5467]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

Passing (coldef | coldefGroup)[] to api.setColumnDefs throws a error.

- A plunker

https://plnkr.co/edit/5nbKTk8CRbO5PuNI?open=index.tsx

**Current behavior**
`Uncaught TypeError: this.column.getColDef is not a function`

**Expected behavior**

To set the column Defs

**Please tell us about your environment:**
React V28.1

* **AG Grid version:** X.X.X

28.1

* **Browser:**
Edge

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by StephenCooper** [comment]
Hi @jackdh,

Unfortunately I cannot reproduce this error from the plunker that you provided. Also we have examples on our docs showing setting col defs that include column groups which do not fail.

Could you confirm that your plunker does reproduce the error that you have reported.

**Comment by jackdh** [comment]
Strange, seems to be working now. Please ignore!
