### ISSUE TITLE
Where can we find an ag-charts migration guide from 5.x -> 6?

### ISSUE THREAD

**Issue by at-cf** [ag-grid/ag-grid#5471]
I cannot find any information on breaking changes specific to ag-charts. How do I know what ag-grids release it was under (as I cannot see ag-charts release version history separately)? Thanks.

**Comment by juliancarrivick** [comment]
I've personally intuited that 5 is equivalent to grid release 27 and 6 -> 28 when investigating #5475 and seeing an issue which matches the regression I observed in the [changelog](https://www.ag-grid.com/changelog)

**Comment by StephenCooper** [comment]
Thanks for highlighting this to us. We agree we can make some improvements here. 

We will work to update our Changelog to make it clearer for chart related issues. We will list the Grid version and the chart version that the change relates to. 

Thanks again!
