### ISSUE TITLE
React Cell Renderer not rerendering even when not memoised

### ISSUE THREAD

**Issue by nwrahnema** [ag-grid/ag-grid#5474]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The example provided in this section of the docs does not work as described. 
https://www.ag-grid.com/react-data-grid/reactui/#example-wasted-render

**Current behavior**
The counter does not increment when moving columns and selecting ranges

**Expected behavior**
The counter should increment

* **Browser:**
Firefox, Chrome

**Comment by AndrewGlazier** [comment]
Thanks for reporting this.

Due to performance improvements in the grid, we are no longer able to demonstrate the reduced rendering in that manner.
We'll update our docs in the coming release.
