### ISSUE TITLE
Vue-3 Dropdown menu

### ISSUE THREAD

**Issue by lkotan** [ag-grid/ag-grid#5485]
Dropdown menu stays under ag-grid. I tried z-index but it didn't work. Can you help with the solution?
![ag-grid-menu-error](https://user-images.githubusercontent.com/63057933/185060071-6fa98e64-1e0c-4cad-b0e1-2d376571a755.PNG)

**Comment by StephenCooper** [comment]
You may want to take a look at setting the `popupParent` element as explained in this [section](https://ag-grid.com/vue-data-grid/context-menu/#popup-parent) of the docs.

**Comment by lkotan** [comment]
As you can see in the pictures popupParent didn't work for me
![image-1](https://user-images.githubusercontent.com/63057933/186390540-3b26fac8-ae2c-4ab7-8a2a-1b8f5d689f53.PNG)
![image-2](https://user-images.githubusercontent.com/63057933/186390546-c1c159be-8b4a-4a0a-a713-2d457c3b2d0f.PNG)
