### ISSUE TITLE
Google Chrome's Lighthouse accessibility assessment throws observations on AG Grid example

### ISSUE THREAD

**Issue by coconitri** [ag-grid/ag-grid#5491]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When running Google Chrome's Lighthouse accessibility assessment, the accessibility score throws 86, with the following observations:
1. [aria-*] attributes are not valid or misspelled
![image](https://user-images.githubusercontent.com/98900964/185261217-6c8d4db1-b23b-44ed-be4a-00c03f736b55.png)

2. Form elements do not have associated labels
![image](https://user-images.githubusercontent.com/98900964/185261252-ea0cf5d4-aa11-4825-afdd-54ef4d282bf7.png)

**Expected behavior**
High accessibility score without observations
Can someone help me understand which attributes are not valid?

**Please tell us about your environment:**
AGS Keyboard Navigation example: https://www.ag-grid.com/examples/keyboard-navigation/grid-keyboard-navigation/packages/reactFunctional/index.html

* **AG Grid version:** X.X.X
Don't know

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kiril-matev** [comment]
Hello @coconitri!

Thank you for using AG Grid and for reporting this.

Responding to your first question- **[aria-*] attributes are not valid or misspelled**.

In the HTML code that Lighthouse is flagging as containing invalid aria attributes, there are the following aria attributes - aria-colindex, aria-sort and aria-description. 

The aria-description attribute is a valid attribute and is part of WAI-ARIA 1.3:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description

However, WAI-ARIA 1.3 was only published on August 4th, 2022 and is still in draft stage. This is why WAI-ARIA 1.3 is not officially yet adopted as the current latest version of the WAI-ARIA guideline, and the aria-description attribute is flagged as an invalid name by Lighthouse. 

However, screen readers already support the aria-description attribute and read the values provided in the aria-description label correctly - you can test this with any screen reader. Lighthouse is flagging this as an issue even though in practice it works correctly with screen readers and will be officially in the WAI-ARIA guideline as soon as 1.3 is fully adopted.

Please disregard this specific error as one without real impact on accessibility and one that will not be flagged anymore in the future once WAI-ARIA 1.3 becomes the current version of the accessibility guideline and the Lighthouse tool is updated to use WAI-ARIA 1.3.
