### ISSUE TITLE
'AgGridReact' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Zmhan-github** [ag-grid/ag-grid#5496]
<img width="755" alt="Снимок экрана 2022-08-19 в 14 11 19" src="https://user-images.githubusercontent.com/23366404/185606467-d9b4ba0c-4e46-4f83-999d-e9a7c9c8bb9a.png">

```
"@types/react": "^18.0.17"
"ag-grid-community": "^26.2.1",
"ag-grid-react": "^26.2.0",
```

**Comment by StephenCooper** [comment]
Could you try upgrading your AG Grid versions to match our compatibility table below. i.e 26 does not support v18 of React.

https://ag-grid.com/react-data-grid/getting-started/#ag-grid--react-compatibility-chart

| React Version | AG Grid Versions |
| ------------- | ---------------- |
| 15.x          | 18 - 21.2.0      |
| 16.3+ / 17+   | 22+              |
| 18+           | 27.2.0+          |

**Comment by casamia918** [comment]
@StephenCooper I'm using react v17. But I got the same error message.

```json
 "react": "17.0.2",
 "@types/react": "17.0.2",
 "@ag-grid-community/react": "^26.1.0",
 "@ag-grid-community/core": "^26.1.0",
```
