### ISSUE TITLE
Missing Indentation when groupRow in Server Side Model

### ISSUE THREAD

**Issue by aurelien-gaillard** [ag-grid/ag-grid#5499]
**I'm submitting a ...** 
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I took existing example from the doc and added line 91 `groupDisplayType={'groupRows'}`
[https://plnkr.co/edit/H4mokbfXEhRxBBRE?open=index.tsx](https://plnkr.co/edit/H4mokbfXEhRxBBRE?open=index.tsx)

Current behaviour.
When `groupDisplayType={'groupRows'}` in server side model, there is no indentation inside the first column for the leaf.

**Current behavior**
Missing indentation:
<img width="520" alt="Screenshot 2022-08-23 at 9 10 49" src="https://user-images.githubusercontent.com/66209993/186094262-147a7d5d-27f5-4eb3-95de-520343b2fd7b.png">

**Expected behavior**
Indentation, as we can see for client side model or using different groupDisplayType
<img width="541" alt="Screenshot 2022-08-23 at 9 13 01" src="https://user-images.githubusercontent.com/66209993/186094580-76e004ac-f1b7-4d3e-a9c8-966e5ed3c2a7.png">

* **AG Grid version:** 28.1.0

**Comment by StephenCooper** [comment]
Hi @aurelien-gaillard, 

I would say this is the expected behaviour for `groupRows`. If you look at the row group [example](https://ag-grid.com/react-data-grid/grouping-group-rows/#example-enabling-group-rows) there is a custom cellRenderer which gives the indentation that you are seeing.

So you would need to do something similar when working with the SSRM.

```ts
const [columnDefs, setColumnDefs] = useState<ColDef[]>([
    { field: 'country', rowGroup: true, hide: true },
    { field: 'year', rowGroup: true, hide: true },
    {
      field: 'athlete',
      minWidth: 250,
      cellRenderer: (params: ICellRendererParams) => {
        return <span style={{ marginLeft: 60 }}>{params.value}</span>;
      },
    },
    { field: 'sport', minWidth: 200 },
  ]);
```

**Comment by aurelien-gaillard** [comment]
Thanks for answering. Your proposal doesn't help with checkboxes.
Best solution I found so far is to add in the css:
```css
.ag-row-level-1 > .ag-cell {
    padding-left: 60px;
  }
  .ag-row-level-2 > .ag-cell {
    padding-left: 100px;
  }
```
