### ISSUE TITLE
Unexpected behaviours in the dragEvent parameters when using drag&drop

### ISSUE THREAD

**Issue by Minskyy** [ag-grid/ag-grid#5503]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Plunker - https://plnkr.co/edit/FpI6gF0ok57XplmU?open=main.js (This plunker is exactly the same as shown in the docs [here](https://www.ag-grid.com/javascript-data-grid/row-dragging-to-external-dropzone/#example-two-grids)) with just some more data inserted in the tables, and some console.logs
- Open the console and drag any node over the other grid. The faulty parameters are being logged. Notice the data and ID's of the overNode. These ID's belong to the grid which is the source of the drag, not the target.
- For the scrolling issue, scroll down one of the grids, and drag an item from this grid to the other, notice the y value being logged has now a shift corresponding to the source grid scroll Y value 

Current behaviour - When dragging an entry from a table to another, some params we get on the drag events (in this case "onDragging" seem to not match their description on the [docs](https://www.ag-grid.com/javascript-data-grid/row-dragging/#row-drag-events), namely the **overNode** **overIndex**, and **y**

**Current behavior**

**overNode** - We are being returned the node on the **source grid** which matches the position we are hovering, 
**overIndex** - We are being returned the index of the misscalculated overNode
**y** - If our **source grid** is scrolled down, the Y value of the scroll position is added to this value.

**Expected behavior**

**overNode** - The overnode returned should be the one on the **target grid** (the one we are hovering).
**overIndex** - The index of the correctly calculated overNode
**y** - The **target grid** scroll position Y value should be added 

**Please tell us about your environment:**
Provided plunker

* **AG Grid version:** 28.1.1

* **Browser:**
Chrome, FireFox

**Comment by StephenCooper** [comment]
Hi @Minskyy,

We have taken a look at this issue and believe that its just a confusion across the different parts of the documentation. In the example that you have linked we are showing how its possible to treat a second Grid as a generic drop target. In this use case the properties that you mentioned are not valid. The [External DropZone](https://ag-grid.com/javascript-data-grid/row-dragging-to-external-dropzone/#dragging-between-grids) page states:

> It is possible to use a generic DropZone to Drag and Drop rows from one grid to another. However, this approach will treat the target grid as a generic HTMLElement and adding the rows should be handled by the onDragStop callback. If you wish the grid to manage the Drag and Drop across grids and also handle where the record should be dropped, take a look at [Row Dragging - Grid to Grid](https://ag-grid.com/javascript-data-grid/row-dragging-to-grid/)

Please refer to the [Grid to Grid](https://ag-grid.com/javascript-data-grid/row-dragging-to-grid/) doc page that has a similar example but will work as you expect with overnodes and positions.

Sorry for the confusion over this.

**Comment by Minskyy** [comment]
Thank you for the answer @StephenCooper 

I was using the Grid to Grid approach, but I want to prevent the drag events from adding/removing entries from the grids (I only want to emit events), but it seems that ag grid is doing that automatically in this case. Whereas in the grid to external zone, it behaves like I want it, in which the entries are only updated when I call gridApi.applyTransaction(...).

Is there a way to configure the grid to grid approach to do this? The best solution I had was to reverse the transaction immediately, but I would prefer a cleaner one.

**Comment by UshanFernando** [comment]
> Thank you for the answer @StephenCooper
> 
> I was using the Grid to Grid approach, but I want to prevent the drag events from adding/removing entries from the grids (I only want to emit events), but it seems that ag grid is doing that automatically in this case. Whereas in the grid to external zone, it behaves like I want it, in which the entries are only updated when I call gridApi.applyTransaction(...).
> 
> Is there a way to configure the grid to grid approach to do this? The best solution I had was to reverse the transaction immediately, but I would prefer a cleaner one.

How did you reverse the transaction?
