### ISSUE TITLE
rowDataUpdated is not behaving same as rowDataChanged. Need a way to know dynamic row heights are set

### ISSUE THREAD

**Issue by chit1-kaur** [ag-grid/ag-grid#5507]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
We are using ag grid with autoHeight/text wrapping feature similar to this :
https://www.ag-grid.com/javascript-data-grid/row-height/#text-wrapping

However, **once the row data is updated and ag grid has finished rendering the data and assigning dynamic heights to the rows**, I wanted to update the over all grid height if required. For that, I wanted an event. 
Earlier in old ag grid version, we were using _rowDataChanged_ and it used to be trigged when row heights have been set after data update and now that it is deprecated, we are using _rowDataUpdated_. However, behavior of _rowDataUpdated_ is not exactly same.  It is triggered on data set and after that the rows' height is being set.  

**Expected behavior**
As _rowDataUpdated_  has replaced _rowDataChanged_ , it should behave the exact same way. It should be triggered once the dynamic row heights have been set as well not just after setting data. Else, requesting an alternative solution for that.

**Reproducing plunker example:**
https://plnkr.co/edit/RlEXmkSeOvfDROHF?open=main.js
As you can see in the plunker, I have added an alert under _rowDataUpdated_   but it is being called before dynamic height is being set for the rows

**Please tell us about your environment:**

* **AG Grid version:** ^28.0.2 (ag-grid-enterprise)

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by chit1-kaur** [comment]
Hello tab
Any update on this?

**Comment by StephenCooper** [comment]
Hi @chit1-kaur, we have added this to our review process for issues to evaluate if this version has introduced a regression.

**Comment by rmc-software** [comment]
Hi @chit1-kaur,

You should use the ModelUpdatedEvent however we have noticed that this is being raised too often, so we have also added the following defect to our backlog that is prioritised for our next version, v28.2.

We are tracking it with the following reference and description:
**AG-7218 - [Rendering] ModelUpdatedEvent is raised to often - raised per row change**

Thanks again for bringing this up with us.
