### ISSUE TITLE
[wiki] "Preserving Group State" link does not exist

### ISSUE THREAD

**Issue by nwrahnema** [ag-grid/ag-grid#5508]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The "Preserving Group State" link here: https://www.ag-grid.com/react-data-grid/server-side-model-tree-data/#example-tree-data does not exist.

It points to this link: https://www.ag-grid.com/react-data-grid/server-side-model-grouping/#preserving-group-state, whose section is not on the page.

**Comment by StephenCooper** [comment]
Thanks for reporting this, we will validate this section of the docs and resolve the issue.
