### ISSUE TITLE
includeBlanksInEquals filter option records not working for "Not Equal" filter operation AgGrid

### ISSUE THREAD

**Issue by VrushakKTR** [ag-grid/ag-grid#5512]
**I'm submitting a **  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
"includeBlanksInEquals" filter option preserve blank records while doing "equal" filtering for a column. If filter on a column is changed to "**Not Equal**" option, empty/null records are being excluded and they are not displayed in the grid.

**Expected behavior**
Ideally when Not Equal filter option is applied to a column, the records which are matching the filter condition value should be excluded and still blank values should be preserved.
Suppose, Assume there is a date column and few records can have empty values for this column. So when Not Equal filter is applied, dates which are matching the filter value only should get removed and blank records should be  still displayed in the grid 

Plunker to reproduce the issue
https://plnkr.co/edit/YT122ZinXd9uJyTQ?open=main.js

* **AG Grid version:** 22.1.1

* **Browser:**
All browsers 

* **Language:** [all | Angular 9| TypeScript | JavaScript | ES6/7 | ES5]

Is there any work around option for this issue?

**Comment by StephenCooper** [comment]
This was fixed in v23 so please upgrade your grid version to at least that version if not a more recent version.

https://plnkr.co/edit/5087PVxo8xcxu1To?open=main.js

**Comment by VrushakKTR** [comment]
Hi,

Thanks for looking into this!. I have one question with regards to the null filtering.

Is there any way we can get the Ag grid to include blank values only for “Not Equal” filter option and not for “Equal” Filter option?

Please let me know if there is any possible solution.

Regards,
Vrushak

From: Stephen Cooper ***@***.***>
Sent: Friday, September 2, 2022 4:04 AM
To: ag-grid/ag-grid ***@***.***>
Cc: K, Vrushak (TR Technology) ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [ag-grid/ag-grid] includeBlanksInEquals filter option records not working for "Not Equal" filter operation AgGrid (Issue #5512)

External Email: Use caution with links and attachments.


This was fixed in v23 so please upgrade your grid version to at least that version if not a more recent version.

https://plnkr.co/edit/5087PVxo8xcxu1To?open=main.js<https://urldefense.com/v3/__https:/plnkr.co/edit/5087PVxo8xcxu1To?open=main.js__;!!GFN0sa3rsbfR8OLyAw!cJy3pCzsctOP0qO1qFUPphCYQdnfvO_RQoEOSQLLBV5JG98usWaxYPtquv53AL2eB1SoMrKOJTCE_huGWb-dMsF-lt7Nq5M$>

**Comment by StephenCooper** [comment]
If you want to customise the behaviour like that then you will need to implement a custom filter as described on this page. 

https://ag-grid.com/angular-data-grid/component-filter/
