### ISSUE TITLE
Where is columnApi?

### ISSUE THREAD

**Issue by csicky** [ag-grid/ag-grid#5515]
There was this path `gridApi.columnModel.columnApi....` I find it that after upgrading from **28.0.2** to **28.1.1** now the path changed to  `gridApi.columnModel....` **without** `columnApi`. 

For example `params.api.columnModel.columnApi.getColumnState()` became `params.api.columnModel.getColumnState()`

Since this was not announced anywhere, can I trust to migrate all the code relying to read from `columnApi` to the new path? Or will you change it again next week?

**Comment by csicky** [comment]
In a cell event, the columnApi is still there:
![image](https://user-images.githubusercontent.com/3931907/187215028-66c2ac17-6fe4-42ea-b65e-a6e4374db07a.png)

**Comment by StephenCooper** [comment]
Yes please access the `columnApi` directly from the top level params. The columnModel is not a public property so should be avoided.

https://ag-grid.com/javascript-data-grid/grid-events/#reference-selection-cellClicked

You can see the available properties at the above link.
