### ISSUE TITLE
Need a Callback/Event after framework cellRenderer loads

### ISSUE THREAD

**Issue by psr323** [ag-grid/ag-grid#5516]
Hi,
I am currently using Ag-grid version 25.3.0. I would like to know if there's any grid callback after the custom cellRenderer framework components complete the rendering. I tried `onRowDataChanged`, but it gets fired before the cellRenderers finishes the execution.

**Comment by StephenCooper** [comment]
You could try one of these events, (not tried myself)

https://ag-grid.com/javascript-data-grid/grid-events/#reference-components-componentStateChanged
https://ag-grid.com/javascript-data-grid/grid-events/#reference-miscellaneous-modelUpdated

We do not have an event for this currently so would have to be a new feature request via our support system. As a result I am going to close this issue for now.
