### ISSUE TITLE
cellRendererSelector - How to include multiple cell renderer in grid

### ISSUE THREAD

**Issue by erYasar** [ag-grid/ag-grid#5518]
I have a custom cell renderer for example i am converting the cell to link.

But i also need to additional capabilities like to include checkbox by ag grid out of the box.
```

cellRenderer: 'agGroupCellRenderer',
        cellRendererParams: {
            checkbox: true
        }
```

How can i include both custom renderer and ooo ag grid check into it?

I don;t have idea on cellRendererSelector but i am not sure it will work or not.

**Comment by StephenCooper** [comment]
Take a look at this example as it should be a good starting point for you https://ag-grid.com/javascript-data-grid/group-cell-renderer/#example-group-renderer
