### ISSUE TITLE
Scrolling horizontally while the cursor is over the title row

### ISSUE THREAD

**Issue by Ariane-B** [ag-grid/ag-grid#5520]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

This is right in between of a bug and a feature request. Not sure how to classify this UI issue.

**Current behaviour**

- Requires a mouse that can scroll horizontally. For example, on my Logitech MX Anywhere 3, I can scroll while holding one of the previous/next buttons, and it'll scroll horizontally 
- In the docs, see [this example](https://www.ag-grid.com/vue-data-grid/column-definitions/#example-column-definition)
- Shrink your browser/viewport until there's a horizontal scrollbar
- Put your mouse cursor over a column title
- Scroll to the right
- It does not scroll

**Expected (ideal) behaviour**

- It scrolls exactly as if I had my cursor over the table body.

**Please tell us about your environment:**
* **AG Grid version:** 27.2.1 & 28.1.1

* **Browser:**
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
    - (Likely all browsers)

* **Language:** Not sure. All?

**Comment by StephenCooper** [comment]
hi @Ariane-B, 

This is a feature request, but it is also one that we have had before and is not something that we are going to implement. There are many internal details that mean this is not a simple feature. 

As a result I will be closing this issue.
