### ISSUE TITLE
It is strongly recommended that custom components can be directly JSX

### ISSUE THREAD

**Issue by guohuihot** [ag-grid/ag-grid#5524]
It is strongly recommended that custom components can be directly JSX, in Vue mode
ag-grid-vue
```js
{
  headerName: 'name',
  field: 'name',
  width: 120,
  cellRender: ({row, value}) => {
     // jsx
     return <div>{row.name}</div>
  }
},
```

**Comment by StephenCooper** [comment]
Hi @guohuihot,

If you are an enterprise customer please submit this feature request via ZenDesk as that is where we prioritise work for our customers. 

As it stands this would be unlikely to be implemented anytime soon. As a result I am going to close this issue.

**Comment by guohuihot** [comment]
。。。
