### ISSUE TITLE
Can't Restore NPM Packages

### ISSUE THREAD

**Issue by Eddie-Hartman** [ag-grid/ag-grid#5526]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Please tell us about your environment:**

Windows 10. Visual Studio 2022. Npm

* **AG Grid version:** X.X.X

25.1.0

AG-grid is unable to resolve dependencies in NPM:

```
npm ERR! While resolving: @ag-grid-community/vue@25.1.0
npm ERR! Found: vue-property-decorator@9.1.2
npm ERR! node_modules/vue-property-decorator
npm ERR!   vue-property-decorator@"9.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue-property-decorator@"^7.2.0 || ^8.0.0" from @ag-grid-community/vue@25.1.0
npm ERR! node_modules/@ag-grid-community/vue
npm ERR!   @ag-grid-community/vue@"25.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue-property-decorator@8.5.1
npm ERR! node_modules/vue-property-decorator
npm ERR!   peer vue-property-decorator@"^7.2.0 || ^8.0.0" from @ag-grid-community/vue@25.1.0
npm ERR!   node_modules/@ag-grid-community/vue
npm ERR!     @ag-grid-community/vue@"25.1.0" from the root project
```

**Comment by StephenCooper** [comment]
Hi, this is expected as for that version of AG Grid the peer deps are as follows.

```
"peerDependencies": {
--
 "@ag-grid-community/core": "~25.1.0",
 "vue": ">= 2.2 <= 2.5.17 \|\| >= 2.5.20",
 "vue-property-decorator": "^7.2.0 \|\| ^8.0.0"
 },
```
If you do not want to respect these then use `npm i --force` to ignore the peer dep warning.

**Comment by Eddie-Hartman** [comment]
Thank you for your prompt response!

Off topic, but just looking for general guidance:
Do you happen to know how or why an npm install would have work previously? I don't believe I would have forced the install and this npm dependency in our packages.config hasn't been updated in months.

I'm generally not understanding how the rest of the team is able to install packages, but not have it error out when this clearly didn't work for me starting today.

**Comment by StephenCooper** [comment]
Have you made any changes such as updating npm version? Or maybe this is a clean install whereas previously one package was added after the other, hence not triggering the validation.

**Comment by Eddie-Hartman** [comment]
This was essentially a clean install for me.

The strange part to me is that the initial commit contained both ag-grid AND the decency that was causing issues, so I would have expected the issue to come up the next time a dev tried to install packages. But I'm guessing that validation only happens on the first totally clean install?

Thanks for your help with this. Npm isn't something I'm totally familiar with as you can tell.

As far as I'm concerned, you've helped me resolve this issue and I've propagated the change out to the rest of the team so this discussion is just icing and me trying to understand what happened better.
