### ISSUE TITLE
Dragging rows with 3 hierarchy levels doesn't work for collapsed items

### ISSUE THREAD

**Issue by romansimeiz** [ag-grid/ag-grid#5528]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- create a grid with tree data with three hierarchy levels, configured drag-n-drop behaviour
- collapse 3rd level and try to change order for 2nd level from top to bottom
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/88105256/188149035-9cfb7e7d-fff0-4044-8837-9b80e95ce67f.png">

**Current behavior**
 If you expand all levels, order changing works but if 2nd level is collapsed you can reorder items only from bottom to top

**Expected behavior**
You can reorder collapsed items from top to bottom and from bottom to top

**Please tell us about your environment:**
* **AG Grid version:** 26.2.0

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36'

* **Language:** ES6/7

**Comment by lolochka** [comment]
I have faced with the same problem(

**Comment by margarytaviter** [comment]
Got the same issue :( any suggestions on how to fix the issues would be very appreciated

**Comment by StephenCooper** [comment]
First point to note is that for Tree Data you need to use the unmanaged row dragging. If that is the case then please provide a reproducible example for us to work from.
