### ISSUE TITLE
Selectable Rows with Checkbox - Cannot select row below or above checkbox

### ISSUE THREAD

**Issue by StefanTirea** [ag-grid/ag-grid#5529]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://www.ag-grid.com/angular-data-grid/row-selection/#example-selectable-rows-with-header-checkbox
In the example linked above, checkbox and row selection is enabled. But if I try to select the row just above or below the checkbox, selection is not happening:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/19685364/188399756-d48c95dd-df4f-4db3-9e22-61ee67e18168.png">
If I remove the height of `ag-selection-checkbox` the row can be selected.

**Current behavior**
Clicking above or below the checkbox, the row does not get selected.

**Expected behavior**
Even clicking just below or above the checkbox, the row should get selected.

**Please tell us about your environment:**

* **AG Grid version:** 27.3.0 (our version); Version of the deployed documentation also has the same problem;
Before we used version ag-grid-community `27.0.1` and it did not have this problem. So the problem occured between 27.0.1 - 27.3.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'

**Comment by StefanTirea** [comment]
Hi, it is probably related to Issue #4918. It also aligns with the reported version.

**Comment by AndrewGlazier** [comment]
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-7244 - Clicking above or below checkbox does not select row

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

Thanks for reporting this.
