### ISSUE TITLE
Impossible to toggle column grouping

### ISSUE THREAD

**Issue by aurelien-gaillard** [ag-grid/ag-grid#5530]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/sfGXdT2oKWZgaJhN?open=index.tsx

**Current behavior**
The columns country and year have `enableRowGroup: true`
After clicking on `Group by Year` from the column menu, the columns Year disappears. 
The bug is that there is no possibility to ungroup the column Year, as the column disappeared

**Expected behavior**
This bug arrived after v 28.1.1
The column after grouping should not disappear, so there is a possibility to click again on the column menu and on `Un-Group by year`

* **AG Grid version:** X.X.X
28.1.1

**Comment by StephenCooper** [comment]
You may want to use the flag `suppressRowGroupHidesColumns={true}`. This prevents the column being hidden when the group is applied.

See more info [here](https://www.ag-grid.com/javascript-data-grid/grouping-group-panel/#keeping-columns-visible)

**Comment by aurelien-gaillard** [comment]
thank you for your help, I missed this flag on the docs

**Comment by StephenCooper** [comment]
Also just an FYI, as an enterprise user you get access to our support queue in ZenDesk which is the prefered route for support issues like this one. There are SLA's on response times which do not apply to Github Issues (I know in this case you got a quick answer but we may not always respond as quickly on Github.)
