### ISSUE TITLE
React - setRowData doesn't always work and refresh grid

### ISSUE THREAD

**Issue by kevinfairclough** [ag-grid/ag-grid#5535]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

- https://plnkr.co/edit/lgiefNzEbwpILWvJ?open=index.jsx

**Current behavior**
Cell values seem to be stale, grid doesn't display correct data.
We are having strange issues where the grid seems to have differing internal data this is just one example of weird behaviour when using setState value as a prop to AgGridReact

Latest ag-grid

**Comment by StephenCooper** [comment]
Hi @kevinfairclough,

We have been able to reproduce your issue and understand what is happening. I will spare you the full details and instead suggest a solution to this use case. If you implement the `getRowId` callback and provide this to the grid then it will work as expected.

https://plnkr.co/edit/M6sO5VfwG6PXn79T?open=index.jsx

```ts
  const getRowId = (params) => {
    return params.data.make + params.data.model;
  }
```

Providing row ids improves the updating experience in a number of ways and so we would recommend this, especially with editing. 

https://ag-grid.com/javascript-data-grid/data-update-row-data/

**Comment by kevinfairclough** [comment]
Hi and thanks for the reply.

I don't have an appropriate candidate field to use as an id and I don't want to have to manage a unique key value in my dataset just to make grid editing work.  We have been using ag-grid for a long time and have never had to do this before.  

Our dataset is a child array of objects.

Setting the rowData via the api.setRowData doesn't have the same problem

Thanks

**Comment by StephenCooper** [comment]
An alternative workaround is to use the undocumented prop `rowDataChangeDetectionStrategy` as used [here](https://plnkr.co/edit/n7SmkT9ivF0nQA6F?open=index.jsx). We have not documented this flag as we recommend the use of getRowId as the best approach.

```
rowDataChangeDetectionStrategy={'IdentityCheck'}
```
You may want to try this out to see if it makes the grid work as you expect.
