### ISSUE TITLE
Vue3 cellrenderer doesn't render nested components in production

### ISSUE THREAD

**Issue by sanyaches** [ag-grid/ag-grid#5544]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
Use custom component for `cellRenderer` in a column definition like `ExpandableMessage`:
`{ resizable: true, wrapText: true, autoHeight: true, width: 320, flex: 1, headerName: 'Message', cellRenderer: 'ExpandableMessage' },`
In this component, I register and use other custom components. Everything is great in development environment, in production I get such thing (should be buttons and icons with text on this picture).

![image](https://user-images.githubusercontent.com/22271980/189450459-7cbc651e-a8d2-4b97-a30b-9c4e67262554.png)

**Current behavior**
Whatever I use, `cellRenderer` for columns or `fullWidthCellRenderer` for a table, if I use other components inside passed components, they won't render at all. The rendering works perfectly in the development environment, but doesn't work in production.

**Expected behavior**
Every nested components should be rendered in production.

**Please tell us about your environment:**

* **AG Grid version:** 28.1.1
"ag-grid-community": "28.1.1",
"ag-grid-vue3": "28.1.1",

**Comment by sanyaches** [comment]
I think a problem can be here https://github.com/ag-grid/ag-grid/blob/latest/community-modules/vue3/src/VueComponentFactory.ts because I faced that Vue has different context structure depending on the environment (dev or production). Could someone check the logic there, please?

**Comment by sanyaches** [comment]
The problem was solved by upgrading packages and node.js to the latest versions.
Previous:
**Node.js: 16.16.0**
```json
"ag-grid-community": "27.3.0",
"ag-grid-vue3": "27.3.0",
"vue": "3.2.37",
```
Current (all works ok):
**Node.js: 16.17.0**
```json
"vue": "3.2.39",
"ag-grid-community": "28.1.1",
"ag-grid-vue3": "28.1.1",
```

**Comment by priiduneemre** [comment]
In our case, this was caused by the app's `package.json` vs. `@ag-grid-community/vue3`'s `package.json` pulling in two different versions of the Vue core packages.

Deduping the `yarn.lock` file to a single Vue version via `resolutions` fixed it.

**Comment by priiduneemre** [comment]
In our case, the problem was caused by the app's `package.json` vs. `@ag-grid-community/vue3`'s `package.json` pulling in two different versions of the Vue core packages.

Deduping the `yarn.lock` file to a single Vue version via `resolutions` fixed it.

**Comment by priiduneemre** [comment]
In our case, the problem was caused by the app's `package.json` vs. `@ag-grid-community/vue3`'s `package.json` pulling in two different versions of the Vue core packages.

Deduping the `yarn.lock` file to the intended Vue version via `resolutions` fixed it.
