### ISSUE TITLE
Bug Report: pivot with custom formatting problem

### ISSUE THREAD

**Issue by novotny1akub** [ag-grid/ag-grid#5553]
I'm submitting a bug report. Here is a [plunker ](https://plnkr.co/edit/Ck2slGqxzrEhMgUZ?open=main.js&preview) I created to show the bug. If you try to remove the `col1` from the `Column Labels` in the plunker, the grid does not seem to be working anymore (it is not responsive). It seems like this behaviour is caused by the custom formatting or at least when the formatting is removed, this problem is not occuring anymore.

![image](https://user-images.githubusercontent.com/39886440/189951430-9db3fc06-a072-42b8-9b6d-f26b7bfdb832.png)

**Comment by StephenCooper** [comment]
I think you need to add the `enablePivot=true` config to the column defs.

https://plnkr.co/edit/7u9RJjXtL1exXRVD?open=main.js

**Comment by novotny1akub** [comment]
@StephenCooper agreed that you may need `enablePivot=true`. But even with `enablePivot=true`, I am unable to have custom formatting `valueFormatter: params => params.value.toLocaleString('cs-CZ', { maximumFractionDigits: 0})` and pivoted `col1`. With the custom formatting, the pivot table strats behaving in a strange way. For example, I cannot remove the col1 from the Column Labels as indicated in the picture above. In my opinion, your example works only because you commented out the custom formatting.

**Comment by StephenCooper** [comment]
The params.value can sometimes be undefined when that valueFormatter is called. Here is an updated plunker that does not break. 
https://plnkr.co/edit/bL8eb2h9aJCug2fP?open=main.js
