### ISSUE TITLE
[bug] ag-grid-vue3 Sourcemap points to missing source file

### ISSUE THREAD

**Issue by lublak** [ag-grid/ag-grid#5555]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Steps:
- Use nuxt 3 + vue 3 + ag-grid-vue3
- add ag-grid-community (^28.1.1)
- add ag-grid-vue3 (^28.1.1)

**Current behavior**

![image](https://user-images.githubusercontent.com/44057030/190154694-bc5a4525-a582-485c-aefc-3924db33457f.png)

**Expected behavior**

No warnings / Add Sourcemap?

**Please tell us about your environment:**

Windows 10
VSCode
Yarn
Nuxt 3 RC.9
Vue 3.2.39

* **AG Grid version:** 28.1.1 (ag-grid-vue3: 28.1.1)

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33

* **Language:** TypeScript 4.8.3 / Vue

**Comment by seanlandsman** [comment]
Hi,

I've just taken a look and can see the the map files are both generated and published - see here for example: 

https://unpkg.com/browse/ag-grid-vue3@28.1.1/lib/

Doing a local npm install of `ag-grid-vue3` and looking at the resulting `node_modules` also shows that the source and maps are in the `ag-grid-vue3/lib` directory.

**Comment by lublak** [comment]
@seanlandsman so its more an nuxt issue?
I have several things in use and ag grid is the only one that throws these messages.

**Comment by seanlandsman** [comment]
I actually stand corrected - I misread the warning above. The message is complaining about missing `source files`, not the actual source maps.

Taking a look this is valid - we don't publish the source files hence this warning. 

I've raised an internal issue for this: "AG-7260 Don't publish/distribute source maps with @ag-grid-community/vue3 / ag-grid-vue3" and I'll ensure it's included in our next release - currently scheduled for the end of this month.

Thanks for raising this issue
