### ISSUE TITLE
updating suppress-drag-leave-hides-columns dynamically doesn't take affect

### ISSUE THREAD

**Issue by arielvol** [ag-grid/ag-grid#5563]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behavior.
Modifying the suppress-drag-leave-hides-columns dynamically doesn't  take affect.

Recreation of issue example:
[https://plnkr.co/edit/QZXGHBuTyFn6EFbl?open=main.js&preview](url)

Expected behavior:

When setting the parameter "suppressHideColumns" to "true" in the OnGridReady event, the user should not be able to drag columns out anymore.

Google Chrome: 105.0.5195.125

AG Grid version: V28.1.1

Language: [all | TypeScript X.X | ES6/7 | ES5]
ES6 | Vue2.0

**Comment by StephenCooper** [comment]
Hi @arielvol,

This is one of the grid properties that does not currently support reactivity. We have a major task to work across all the grid options and improve reactivity support. I have added a note about this property.

**Comment by arielvol** [comment]
Hi @StephenCooper ,
This property was reactive in version 25.3, but now when I upgraded to 28.1.1 it stopped being reactive. Is this a bug ? Are you aware of this change ?
