### ISSUE TITLE
applyTransaction dosen't works if getNodeChildDetails function is used

### ISSUE THREAD

**Issue by mdfaizan7** [ag-grid/ag-grid#5564]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Nothing happens if I use applyTransaction function from the gridApi if getNodeChildDetails function is used

**Expected behavior**
transactions should be applied if I use applyTransaction function

**Please tell us about your environment:**

OS - Mac OS Monteret 12.6

**AG Grid version:** 

ag-grid-community -  "^23.2.1"
ag-grid-react - "^23.2.1"

**Browser:**

Browser - Chrome 105 on macOS (Catalina)

**Language:** [all | TypeScript X.X | ES6/7 | ES5]
React with Typescript

**Comment by StephenCooper** [comment]
Hi @mdfaizan7,

Can you please provide a reproduction so that we can investigate this. Also please test if this works in our latest version as it seems to work in this example. (Although that method is no longer part of our current api.)

https://ag-grid.com/javascript-data-grid/tree-data/#example-file-browser

**Comment by mdfaizan7** [comment]
You can see the working example in the following [sandbox](https://codesandbox.io/s/elastic-bird-hk0ivd?file=/src/styles.scss).

notice that the `delete first row` button doesn't do anything. But if you comment out the line 142 on `App.js`, the button will not delete the first row.

I will not be able to use the latest version as `getNodeChildDetails` method is not available from ver 24 and my code depends upon this.

**Comment by StephenCooper** [comment]
I see your example logs the following.

```
ag-Grid: adding and removing rows is not supported when using nodeChildDetailsFunc, ie it is not supported for legacy tree data. Please see the docs on the new preferred way of providing tree data that works with delta updates. ```
```

So this feature will not work with that method. To enable transactions you will have to upgrade and also migrate your code to the new tree data approach. As a result I am going to close this ticket as we do not add features to older versions of AG Grid.
