### ISSUE TITLE
Custom pagination Server side not working  with method paginationGoToPage

### ISSUE THREAD

**Issue by duylinhdang1998** [ag-grid/ag-grid#5581]
I'm using server side data and I created a custom pagination.
So when I changed page, the method gridRef.current.api.paginationGoToPage(2) didn't work.
Version ag-grid: 28.1

**Comment by StephenCooper** [comment]
In React with a button this time. https://plnkr.co/edit/rTiBqt4kKGV2YQfA?open=index.tsx

Just be aware that if your not providing the total number of rows then you can only move forward or back one page at a time. To jump to specific pages the grid needs to know how many rows there are. 

https://ag-grid.com/react-data-grid/server-side-model-datasource/#success-callback
