### ISSUE TITLE
Missing AMD support in ag-grid-vue's UMD module

### ISSUE THREAD

**Issue by mariobuikhuizen** [ag-grid/ag-grid#5599]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Reproducible Scenario: https://github.com/mariobuikhuizen/ag-grid/pull/1/files

Steps to reproduce:
- Build the project
- Open `minimalExample.html`
- Note the error in the browser console

Steps to enable AMD support:
- Uncomment the commented lines in `grid-packages/ag-grid-vue/vue.config.js`
- Rebuild ag-grid-vue
- Open `minimalExample.html`
- Note the ag-grid in the page and no error in the console

**Current behavior**
The UMD module of ag-grid-vue is missing AMD support.

**Expected behavior**
AMD support in the UMD module of ag-grid-vue.

The root cause of this in my opinion is that it is missing in the vue-cli tool, see: vuejs/vue-cli#7302, but it might take a while before this is fixed in vue-cli and ag-grid-vue is using a fixed version.

**Comment by seanlandsman** [comment]
Hi,

This looks like a reasonable change - I'll test the changes and provided they're backwardly compatible (and I can't see why they wouldn't be) I'll merge your changes in and include them in our next release.

I've raised an internal ticket for this internally: AG-7305

Thanks for raising this and providing a PR (and reproducible example).

**Comment by seanlandsman** [comment]
This has now been done - it will be available in our next release, currently scheduled to be done within the next couple of weeks.

thanks
