### ISSUE TITLE
Performance 100,000 rows clone, remove

### ISSUE THREAD

**Issue by GOVYANSONG** [ag-grid/ag-grid#5602]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

As part of our volume testing effort, we loaded 100,000 rows into a detail info grid. when we tried to clone the entire content (all rows), it took very long around 22 seconds. the UI was non-responsive. We used api.applyTransaction() function. We would like to know if there is a way to speed up.

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

 too slow and non-responsive for a while

**Expected behavior**

we cloned 100,000 rows in open office in under 1.5 seconds. we would expect the same performance with ag grid.

**Please tell us about your environment:**

Windows 10

* **AG Grid version:** X.X.X

    "ag-grid-community": "^27.1.0",
    "ag-grid-react": "^27.1.0",

* **Browser:**

Edge and Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

JS, TS ES5

**Comment by GOVYANSONG** [comment]
currently, we do not specify getRowID(). just read about the slow performance impact. will experiment.

**Comment by GOVYANSONG** [comment]
implemented custom getRowID with a special property that needs to be maintained during CRUD operations. I can confirm that the performance drastically improved.

**Comment by StephenCooper** [comment]
Excellent! Thanks for updating the ticket with the solution 😊
