### ISSUE TITLE
Context Menu - Menu item Hover action

### ISSUE THREAD

**Issue by psr323** [ag-grid/ag-grid#5607]
I am using React Ag-grid version 25.3.0. I am trying add a context menu with an action on hovering over a menu option. I am able to add a contextMenu following the example from [here](https://www.ag-grid.com/react-data-grid/context-menu/). But we don't have any callback available for hover action. Neither does the context menu(MenuItemDef) accept a JSX component as a menu option to add listeners.

Hence, would like to know if there are other options to add a custom component to the options.

**Comment by StephenCooper** [comment]
Hi @psr323,

Unfortunately this is not a feature that we support in the context menu. You can only customise the text and icon. 

As an Enterprise user feel free to raise a feature request if this is something that is something that you would like us to consider. As for now though I am going to close this ticket.
