### ISSUE TITLE
Ag Grid Set Filter Item list not wrapping the data correctly

### ISSUE THREAD

**Issue by VrushakKTR** [ag-grid/ag-grid#5610]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I am using set filter in ag grid and seems to be like Filter list is not wrapping the data correctly. For multi line data, Filter list wraps incorrectly as shown in the below image

![image](https://user-images.githubusercontent.com/111048580/192714179-0d8ae33f-a916-4545-aa25-4580d533702f.png)

**Expected behavior**
Filter values should wrap data correctly in case of multi line data.

Plunker:
https://plnkr.co/edit/quGsEc9TBY9c9pom?open=app%2Fapp.component.ts

**Please tell us about your environment:**
Windows
* **AG Grid version:** 27.3.0

* **Browser:**
All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
It cannot be dynamic but you can set the height with the following config. 

```ts
    { field: 'athlete', filter: true, filterParams: {
      cellHeight: 35
    } },
```

https://plnkr.co/edit/OOIbFw17EMxJWY72?open=app%2Fapp.component.ts

**Comment by StephenCooper** [comment]
Screenshots did not get attached. However, there is no way to have auto sizing of the filter items. This component only supports a fixed height for every row. 

We suggest this approach to handle long items https://www.ag-grid.com/angular-data-grid/filter-set-filter-list/#filter-value-tooltips.

As it looks like you are an Enterprise user feel free to submit a feature request via your Zendesk account.
