### ISSUE TITLE
Last row cell clickable area does not include full cell height if domLayout="autoHeight"

### ISSUE THREAD

**Issue by Gloccck** [ag-grid/ag-grid#5611]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Plunker: https://plnkr.co/edit/ZRIJkWSqsJHEH2pr?open=index.jsx&preview

- Open Plunker
- Expand preview window so that table won't have a horizontal scrollbar
- Try to click on the bottom half of the last row cell
=> Cell is not clickable

If table has horizontal scrollbar then the issue does not appear.

**Current behavior**

Last row cell clickable area does not include full cell height if `domLayout="autoHeight"`. It is not possible to focus cell if clicking on a bottom part of the cell.

![image](https://user-images.githubusercontent.com/12834402/192745422-2d289b53-fffa-44da-b4be-b615a6f2c9d0.png)

**Expected behavior**
Last row cells should have correct clickable area (as if auto-height feature is off).

* **AG Grid version:** 28.1.1

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

* **Language:** all

**Comment by StephenCooper** [comment]
This sounds similar to this issue which has further details. https://github.com/ag-grid/ag-grid/issues/5534
