### ISSUE TITLE
Need Fix :: Breaking Change: Slash as Division

### ISSUE THREAD

**Issue by yogeshpaisodeGL** [ag-grid/ag-grid#5617]
Hello Team,

Can we have this fix in ag-Grid SCSS :: https://sass-lang.com/documentation/breaking-changes/slash-div

Thanks!

**Comment by StephenCooper** [comment]
This was fixed in v26 so please upgrade. 

https://github.com/ag-grid/ag-grid/issues/4682 
https://github.com/ag-grid/ag-grid/issues/4556
https://github.com/ag-grid/ag-grid/issues/4543
