### ISSUE TITLE
agSelectCellEditor bot saving selected data internally. and not able to conditionally style the column because of this

### ISSUE THREAD

**Issue by sachinjijojacob** [ag-grid/ag-grid#5622]
I'm submitting an issue with the ag grid agSelectCellEditor.
after loading simple valyes in the cellEditorParams. i am able to see the dropdown values after click.
Able to select also. selected value is visible. but unable to apply cellStyle conditionally vased on this column as selected value for this dropdown is coming as "" empty. value can be seen on the grid cell. 
ag grid react : 27.3.0
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
inline selection of dropdown cant be used to set the cell then conditionally style the column based on the selection as its not reflecting the change internally

* **AG Grid version:** 27.3.0
Yes issue persist

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi @sachinjijojacob,

Can you please use this plunker as a basis to show us the issue you are seeing. I am not clear on what your issue is or how to reproduce it. 

https://plnkr.co/edit/AHXZnhHMXf1zX7EG?open=main.ts
