### ISSUE TITLE
Yarn pnp React issue

### ISSUE THREAD

**Issue by aateeque** [ag-grid/ag-grid#5623]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I am using Yarn PnP & Yarn Workspaces in a monorepo. In the app that uses `ag-grid` I have in `package.json`:
```
"ag-grid-community": "^28.1.1",
    "ag-grid-enterprise": "^28.1.3",
    "ag-grid-react": "^28.1.1",
    
```

When I run this app I get the following error:

```
Compiled with problems:X

ERROR in ../../.yarn/cache/ag-grid-enterprise-npm-28.1.3-2d24192c38-6f79a6d8c9.zip/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.auto.esm.js 6:0-960

Module not found: Error: Can't resolve 'ag-grid-community' in '<workspaceRootDir>\.yarn\cache\ag-grid-enterprise-npm-28.1.3-2d24192c38-6f79a6d8c9.zip\node_modules\ag-grid-enterprise\dist'
```

**Expected behavior**

The `ag-grid-enterprise` package should resolve the `ag-grid-community` package automatically as it is installed as my packages' dependency.

**Temporary fix**

Installing the `ag-grid-community` package in the root workspace `package.json` resolves the issue and as expected everything works

**Please tell us about your environment:**

OS: Windows 11
Package manger: yarn@3.2.3
Node: 18.9.1

* **AG Grid version:** 
    "ag-grid-community": "^28.1.1",
    "ag-grid-enterprise": "^28.1.3",
    "ag-grid-react": "^28.1.1",
    

* **Browser:** 
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'

* **Language:** 
TypeScript: 4.8.3
ESNext

**Comment by StephenCooper** [comment]
It would be very helpful if you could create a minimal repository that replicates the behaviour you see. This will help us debug and then verify if we can fix the issue.

**Comment by aateeque** [comment]
Sure - aateeque/ag-yarn-pnp-issue-repro

**Comment by seanlandsman** [comment]
This is almost certainly due to this issue here: https://github.com/yarnpkg/berry/issues/638

You can find more information here: https://github.com/yarnpkg/berry/issues/1149

In any event this looks like a build tool issue rather than a grid one, so we'll be unable to assist you further with this.

I'd recommend trying some of the suggestions on either of these threads to get your application working with ESM modules.
