### ISSUE TITLE
How to turn off key navigation in whole table

### ISSUE THREAD

**Issue by Griffin23** [ag-grid/ag-grid#5624]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hey, guys, I noticed that there is an attribute of gridOptions, "suppressCellFocus", which can disable focus and key navigation in table cells. But it is not work for table header. So how to make the whole table not tabable. Thanks!

**Comment by StephenCooper** [comment]
Hi @Griffin23,

As the documentation says for that property is does not apply to the headers. Maybe take a look at the header callbacks for navigation and return null to prevent any navigation.

Please note that we use Github issues for bug reports and support / feature requests should come through our enterprise Zendesk system if you want explicit help.
