### ISSUE TITLE
More Excel like Feature With Arrow Keys

### ISSUE THREAD

**Issue by lawaldare** [ag-grid/ag-grid#5642]
I am happy with the fact that ag-grid is trying to impress the end-user to have an excel like feel with the `enterMovesDown` and `enterMovesDownAfterEdit` which is really cool. We also want more with the arrowKeys, so that when editing a cell, pressing any of the arrow Keys will stopEditing and also navigate.

**Comment by gportela85** [comment]
You can probably just leverage the suppressKeyboardEvent callback to do it - https://plnkr.co/edit/hNWv9dETO1hokIeR
To have it work exactly like excel, it will probably need to add mousedown listener to the editor itself, so whenever you click the editor, you know you should bypass the `suppressKeyboardEvent` special handling.

If this solution is not enough, you should submit a Feature Request via Zendesk.

**Comment by lawaldare** [comment]
Thank you so much, it works. But why should I add `mousedown` event to the editor?

**Comment by gportela85** [comment]
@lawaldare because that's how Excel works. If you start typing, then click on the editor, pressing arrows will navigate within the editor and not end the edit.

**Comment by lawaldare** [comment]
Oh exactly, you are absolutely correct. How should I now bypass the `suppressKeyboardEvent` from the editor... sorry if my questions are too much
