### ISSUE TITLE
Type for "menuTabs" property of "ColDef" is insufficiently narrow

### ISSUE THREAD

**Issue by JohannCooper** [ag-grid/ag-grid#5644]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The current type for the `menuTabs` property of the `ColDef` type is defined as follows in `community-modules/core/src/ts/entities/colDef.ts`:
```ts
/**
 * Set to an array containing zero, one or many of the following options: `'filterMenuTab' | 'generalMenuTab' | 'columnsMenuTab'`.
 * This is used to figure out which menu tabs are present and in which order the tabs are shown.
 */
menuTabs?: string[];
```
This type is not as narrow as it could be.

**Expected behavior**
I would suggest changing the type to the following (or some variant of this):
```ts
/**
 * Set to an array containing zero, one or many of the following options: `'filterMenuTab' | 'generalMenuTab' | 'columnsMenuTab'`.
 * This is used to figure out which menu tabs are present and in which order the tabs are shown.
 */
menuTabs?: ('filterMenuTab' | 'generalMenuTab' | 'columnsMenuTab')[];
```

**Please tell us about your environment:**

* **AG Grid version:** 28.2.0

* **Browser:** Any

* **Language:** TypeScript

**Comment by StephenCooper** [comment]
Hi @JohannCooper,

Thanks for pointing this out, appreciate the help in spotting types that can be improved. I will get this updated in the next release. Also appreciate the very clear issue!
