### ISSUE TITLE
copyGroupHeadersToClipboard/processGroupHeaderForClipboard in angular

### ISSUE THREAD

**Issue by getsurenka** [ag-grid/ag-grid#5655]
I was wondering why these functions are available in JavaScript but not in Angular? is there a workaround for angular?

**Comment by gportela85** [comment]
@getsurenka Both properties are working fine with angular, see: https://plnkr.co/edit/OYmBDzfkXTgptLlA

**Comment by getsurenka** [comment]
Thank you. Our project uses an old version, i didn’t realized that.
