### ISSUE TITLE
AgGridEvent<TData> should default to any like everywhere else

### ISSUE THREAD

**Issue by totszwai** [ag-grid/ag-grid#5658]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

![image](https://user-images.githubusercontent.com/4440365/194573471-ced9116e-8d9e-4847-9e29-4c91a9308e91.png)

This line:
https://github.com/ag-grid/ag-grid/blob/fe4742943d0c429b30c9e35e9c5151b6b8ef6ea0/community-modules/core/src/ts/events.ts#L47

Could you default them to `any` like every other ones you guys have in the code already?
```
export interface AgGridEvent<TData = any> extends AgGridCommon<TData>, AgEvent { }
```

**Comment by StephenCooper** [comment]
Sure we can do that as part of our next release. Thanks for pointing this out!

**Comment by totszwai** [comment]
@StephenCooper any chance to have this in the next patch release? `28.2.1`?
