### ISSUE TITLE
Documentation or Website isn't working!

### ISSUE THREAD

**Issue by vamshiqapita** [ag-grid/ag-grid#5663]
I am not able to see the documentation or any of the **ag-grid.com** domain related pages.

Is there any other source to watch the documentation unto it is up?

**Comment by cbullers** [comment]
Yea noticed the same, weird. Their DNS entries are just wiped. 
![image](https://user-images.githubusercontent.com/14268335/194921108-42ef618f-cf64-460c-814f-916bf47f9584.png)

**Comment by StephenCooper** [comment]
We are aware that our website is currently down. We are working with our provider to get it back up as soon as we can.

**Comment by uooq** [comment]
Any way to get to it with a static IP address or by using a local `/etc/hosts` ?

**Comment by uooq** [comment]
Looks like the docs are potentially buildable locally: However you have to get the whole monorepo then build the grid-packages/ag-grid-docs directory...  

Several hours in, I'm starting to think this is my best option-- would be nice to have ag-grid just put up a link to a temporary site or something... :)

**Comment by StephenCooper** [comment]
We are back live now.

**Comment by vamshiqapita** [comment]
It is working now, thanks @StephenCooper !

**Comment by StephenCooper** [comment]
We are hearing that some users are having DNS caching issues but they resolve in 5-10 minutes as the cache values propagate.
