### ISSUE TITLE
Export aligned grids in one sheet

### ISSUE THREAD

**Issue by vamshiqapita** [ag-grid/ag-grid#5664]
I have 3 grids one after the other. I am able to export them individually using client API. However, I am not sure how to combine these aligned grids into one sheet one after the other.

Is it possible to export aligned grid into one sheet?

**Comment by StephenCooper** [comment]
Follow this example for an example of how you can achieve this. 

https://ag-grid.com/javascript-data-grid/excel-export-multiple-sheets/#multiple-grids-to-multiple-sheets

**Comment by vamshiqapita** [comment]
This shows multiple sheets Stephen, but I am trying to achieve one sheet!

**Comment by StephenCooper** [comment]
That feature is not supported out the box with aligned grids. To raise it as a feature request or to ask for further help to see if it's possible with existing apis please raise a Zendesk ticket using your enterprise license.

**Comment by vamshiqapita** [comment]
I see, we are taking license next week, we will raise part of it then!

**Comment by vamshiqapita** [comment]
For the time being, we created a fake-grid, merging all the data together and exporting from it, let me know if there could be better way @StephenCooper
