### ISSUE TITLE
Grid with SSRM does not request a new data when grouping and filtering are applied

### ISSUE THREAD

**Issue by DavidSanek** [ag-grid/ag-grid#5670]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

Hi, I've created a grid with SSRM and `Country`, `Athlete`, `Sport` and `Year` columns. Grouping is applied to the `Country` column. In initial state none of the groups are expanded. When I try to filter the rows via the `Sport` column filter (e.g. `Swimming`), the grid **does not** request a new data from the `getRows` function in the Datasource.

When one of the groups is expanded, the grid calls `getRows` correctly and I return the filtered results for the expanded Group.

**Current behavior**
The grid **does not** ask for a new data when a filter is applied and all groups are collapsed.

**Expected behavior**
The grid **should** ask for a new data when a filter is applied and all groups are collapsed. In my case of using `Sport = Swimming` filter I would like to filter the data so the grid shows only Country groups that have at least one Athlete whose Sport is Swimming.

**Plunker Reproduction**
https://plnkr.co/edit/wWgtXLfIsfeoApm3 - I have adjusted an example code from SSRM Row Grouping docs page. Check the console to see when new rows are requested by the grid.

**Please tell us about your environment:**

* **AG Grid version:** 28.2.0
* **Browser:** Any
* **Language:** TypeScript

**Comment by AndrewGlazier** [comment]
Hi David,

By default the grid attempts to minimise the number of interactions with the server, as such it only requests data when it deems it relevant. This does have the side effect that you're describing, of not refreshing higher level groups when they have no matching children.

For this reason we introduced the property `serverSideFilterAllLevels` which instead triggers a purge refresh rather than targeting relevant groups.

This is documented here:
https://ag-grid.com/react-data-grid/server-side-model-filtering/#server-side-row-group-filtering

**Comment by DavidSanek** [comment]
Hi Andrew,
Thank you for the explanation. The grid works as expected now. At what version was the `serverSideFilterAllLevels` property introduced? I could not find anything in the change log. I believe it was a breaking change for the usecase above.

**Comment by AndrewGlazier** [comment]
Hi @DavidSanek, this change was introduced in v28.0.0, it's in the changelog under breaking changes under the following description:
AG-6848 - When using SSRM Infinite Scroll, filtering the grid selectively refreshes only the groups affected by the filters change. If using SSRM with tree data, filtering happens client-side. The old behavior was to purge all rows from the root level on filter change. The old behaviour of always purging all rows is available by enabling the grid option serverSideFilterAllLevels.
