### ISSUE TITLE
An issues with your style library after updated versions Ag-grid (React)

### ISSUE THREAD

**Issue by GuyHassan** [ag-grid/ag-grid#5672]
Hi guys.
 I Trying to run a package that was built by us over six months ago (this package wraps the Ag-grid table) and I came across your deprecated packages and was asked to update them.
![image](https://user-images.githubusercontent.com/33221427/195103528-33658691-700a-429f-a6bc-e5f723172db0.png)

I tried to change the package.json from this

"@ag-grid-community/react": "^26.2.0",
"@ag-grid-enterprise/all-modules": "^26.2.0",
"@ag-grid-enterprise/core": "^26.2.0",

to this
"ag-grid-community": "28.2.0",
"ag-grid-enterprise": "28.2.0",
"ag-grid-react": "28.2.0"

and changed the imports style from blue square to red square (inside the image) (I tried with ag-grid-community also nothing changed)
![image](https://user-images.githubusercontent.com/33221427/195105258-0ac42722-1c10-43fc-b0d0-bce66d8b0ce6.png)

it exists in the node-modules
![image](https://user-images.githubusercontent.com/33221427/195109213-eeffdbe4-b816-47b1-bf6a-8d51917a4acb.png)
and this are the first lines in the file "ag-grid.css" (The file is inside the node-modules)
![image](https://user-images.githubusercontent.com/33221427/195109495-3176ee78-a121-4738-bcfa-71fa2f5500fa.png)

import the license 
![image](https://user-images.githubusercontent.com/33221427/195105453-524a61c0-3a79-49cb-9893-fe75d645e922.png)

import the main table 
![image](https://user-images.githubusercontent.com/33221427/195105539-daf6930f-1648-4ee2-8150-19754703f735.png)

and also removed the all-modules package
import { AllModules } from '@ag-grid-enterprise/all-modules';
![image](https://user-images.githubusercontent.com/33221427/195108872-7279478c-aeed-4187-969f-c60ae714f4f3.png)

but still getting an error after I run the tests

![image](https://user-images.githubusercontent.com/33221427/195106158-d4b9cf0a-f9be-4bd9-b355-c4ddac560a49.png)

Can someone tell me what I'm doing wrong?

**Comment by StephenCooper** [comment]
For the styles you will need to following the instructions [here](https://ag-grid.com/javascript-data-grid/global-style-upgrading-to-v28/) about upgrading to v28.
