### ISSUE TITLE
"No data available to be charted" with server side when coming from no data to some data

### ISSUE THREAD

**Issue by Sisco21** [ag-grid/ag-grid#5677]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
We are now purchasing one licence.

**Providing a Reproducible Scenario**

We have data from server. the graph is drawn. Now filter -> no data we got no more graph and a message 'No data avaialble to be charted". All this previous is normal. But when removing the filter, grid draw back but not the graph. Still got the message "No data available to be charted".

**Current behavior**
No graph and a message with "No data available to be charted"

**Expected behavior**
Graph should be redrawn

**Please tell us about your environment:**
IIS WIndows 10 Pro

* **AG Grid version:** 28.1.3
* 

* **Browser:**
* 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by StephenCooper** [comment]
Hi @Sisco21,

Could you please confirm if this plunker shows the behaviour that you are seeing?

https://plnkr.co/edit/JoxHgEN2Ubi9mBfE?open=main.ts

**Comment by Sisco21** [comment]
Hi @StephenCooper thanks for your answer.

I've made this change, adding "chartDataType: 'series'" and now it's working.

Best regards
