### ISSUE TITLE
[floating] cellRenderer checkbox attribute creates a checkbox on floating rows when set to true.

### ISSUE THREAD

**Issue by BrandonNoad** [ag-grid/ag-grid#568]
In the column definitions, if you set `checkboxSelection: true`, the floating rows do not have checkboxes due to this line:

```
this.checkboxSelection = this.column.colDef.checkboxSelection && !node.floating;
```

The behaviour of the checkbox attribute for the cellRenderer should match (or there should be an option to suppress the checkbox on floating rows).

In the `groupCellRenderer()` function, we simply need to add a check for `!node.floating` to the following line:

```
var checkboxNeeded = params.colDef && params.colDef.cellRenderer && params.colDef.cellRenderer.checkbox && !node.footer;
```

In the current implementation, if the cellRenderer checkbox attribute is set to true, then the behaviour of the floating row checkboxes is buggy. For example, the floating row checkboxes seem to be "linked" to the checkboxes in the non-floating rows.

![foods_order_list](https://cloud.githubusercontent.com/assets/1979809/11187463/8050710a-8c54-11e5-9876-ffdd80ccac98.png)
![foods_order_list](https://cloud.githubusercontent.com/assets/1979809/11187560/eb0ea322-8c54-11e5-94b7-62e3cd8bd4d4.png)

I do not need checkboxes on the floating rows, so not having checkboxes on floating rows would solve the issues described in the above screenshots.

**Comment by ceolter** [comment]
Thanks for raising. Unfortunately I'm on holidays so won't be able to make code changes until back in the office in Jan.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-87

**Comment by ceolter** [comment]
this was fixed ages back, so please check the latest.
