### ISSUE TITLE
Version 28.2.0 of ag-grid-react breaks cell vertical alignment

### ISSUE THREAD

**Issue by JonoH-LINZ** [ag-grid/ag-grid#5688]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Cell data is rendered towards top of cell, not vertically centered as expected
https://stackblitz.com/edit/ag-grid-react-hello-world-ejwg6i
![image](https://user-images.githubusercontent.com/75228286/196079633-f5a73338-2ce8-4e80-9063-035dbcd08836.png)

**Expected behavior**
Cell data is rendered vertically centered by default
https://stackblitz.com/edit/ag-grid-react-hello-world
![image](https://user-images.githubusercontent.com/75228286/196079734-1915818a-074d-47a7-b23b-e90eff6c8eb9.png)

**Please tell us about your environment:**

* **AG Grid version:** 28.2.0

* **Browser:**
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42`

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by jpike88** [comment]
+1 to this, we have the same issue.

**Comment by AlbertoMontalesi** [comment]
Happens for us too, we are using ag-grid-angular
![image](https://user-images.githubusercontent.com/23130353/196129424-66f2a24c-b85d-493e-b652-eec385ed8d3b.png)

this is how it looked before

![image](https://user-images.githubusercontent.com/23130353/196129498-6cbc3af6-15e0-47a7-b13f-839810e6cba2.png)

**Comment by StephenCooper** [comment]
This is the result of using the now legacy styles instead of the new styles as provided in v28.

Please follow the instructions [here](https://ag-grid.com/javascript-data-grid/global-style-upgrading-to-v28/) to use the new styles which will resolve your issue. Also not that in v29 the legacy styles, those with a `dist` in the path will be removed so you will have to make these changes.

**Comment by JonoH-LINZ** [comment]
Thank you. Upgrading styles to support v28 solved this issue for us.
