### ISSUE TITLE
Dynamic Resizing without Horizontal Scroll doesn't respect checkbox selection

### ISSUE THREAD

**Issue by evgeniyefimov** [ag-grid/ag-grid#5692]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/587BSiPLxqX8hOOG?open=main.js&preview

**Current behavior**
There is a section in docs how to make Dynamic Resizing without Horizontal Scroll (https://www.ag-grid.com/javascript-data-grid/grid-size/#dynamic-resizing-without-horizontal-scroll). The thing is that if we add checkbox selection, then it doesn't respect this checkbox and our cell is truncated. See plnkr.
![image](https://user-images.githubusercontent.com/11611433/196147538-a8dd5ddb-8cc9-407f-9f83-4d973567a393.png)

**Expected behavior**
Cell shouldn't be truncated.

* **AG Grid version:** 28.2.0

**Comment by StephenCooper** [comment]
I believe you just need to make the minWidth larger. Here I have bumped it from 150 to 170 and it works as expected again.

https://plnkr.co/edit/tNu6Y83Gi2avJrr2?open=main.js
