### ISSUE TITLE
Refresh Server Side With Purge and in Pagination - Bugs and Crashes

### ISSUE THREAD

**Issue by Igor-Lira** [ag-grid/ag-grid#5696]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

- Check my Plunker: https://plnkr.co/edit/D8C6k3H8kKD4A021
- Click the button "refresh" to trigger `RefreshServerSide({ purge: true })`.
- Uncomment `{ field: 'age', autoHeight: true }` and remove `getRowsHeight` method to reproduce the other scenario.

**Customers of AG Grid**: I am using AgGrid Enterprise.

**Current behavior**

There are two behaviors that I think they are bugs:
- use `autoHeight = true` for at least one field, and call `RefreshServerSide({ purge: true })`, the table will be refreshed, but the table goes to first page. It does not remains in the current page.
- use `getRowHeight` and call `RefreshServerSide({purge: true})` and the table sometimes crashes (try to refresh in different pages). In those crashes scenarios, `getRows` is not trigged at all.

**Expected behavior**
refreshServerSide with purge may trigger `getRows`, `getRowsHeight` and remains in the current page after the refresh. And should not crashes the table.

More specifically, I'd like to refresh the page and remains in the same page after refresh using autoHeight, or setting height dinamically.

**Please tell us about your environment:**

* **AG Grid version:** 28.0.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Igor-Lira** [comment]
After some other tries, I realized that `RefreshServerSide({purge: true})` cashes in another scenario (`autoHeight` disable, `getRowsHeight` not defined, but using  `rowNode.setRowHeight()`). It usually occurs refreshing after page 3.

Basically, I can't find any way to change row height dinamically and use `RefreshServerSide({ purge: true })` without bugs.

**Comment by AndrewGlazier** [comment]
Hi Igor,

These are technical limitations between the two features of auto height and purge, when using row heights with infinite scroll we must cache row heights, but when we purge we reset the row state, and can no longer trust these cached row heights, as a work around for this the infinite store does reset to its initial state when purging.

I've opened a feature request to investigate if there's anything we can do to improve this interaction:
AG-7433 - [SSRM] Improve support for purge when using autoHeight with infiniteScroll
