### ISSUE TITLE
How is the AgGridAngular Component destroyed as long as it doesn't implement OnDestroy besides having an ngOnDestroy() method?

### ISSUE THREAD

**Issue by icapri** [ag-grid/ag-grid#5698]
Hi guys,

I was analyzing your AgGridAngular Component (before installing it) and realized that besides it contains methods like [`ngOnDestroy()` or `ngOnChanges()`](https://github.com/ag-grid/ag-grid/blob/latest/grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts#L248) it implements neither `OnChanges` nor `OnDestroy` and this gives me an impression that these two methods do nothing.

Thank you in advance for your explanation of this case!

Kind Regards

I. Kapri

**Comment by StephenCooper** [comment]
The component does implement those interfaces, they are just not included in the implements list. Angular just checks for the presence of the methods on the class and as they exist they are called. 

However, I see that this can be confusing and so will add them in for clarity. Thanks for raising!
