### ISSUE TITLE
Improved documentation Custom cells in new infinite scroll module

### ISSUE THREAD

**Issue by jpengelbrecht** [ag-grid/ag-grid#5699]
Can you please add documentation on how custom cells are supported in https://www.ag-grid.com/vue-data-grid/infinite-scrolling/
as with the addition of this new module we need the cell renderer to see if params are undefined,  it no longer accepts custom components.    

so for instance cellRenderer: 'myCustomCell' used to work.   now we need to use cell renderer like 
` cellRenderer: (params) => {
            if (params.value !== undefined) {
              return params.value;
            } else {
              return '<img src="https://www.ag-grid.com/example-assets/loading.gif">';
            }`
            
  returning 'myCustomCell'    in that function gets seen as text and referencing it directly gets an error.   so again,  documentation would be nice

**Comment by StephenCooper** [comment]
Hi,

We would expect this to work following the instructions under https://www.ag-grid.com/javascript-data-grid/components/#registering-custom-components. 

If this does not work for you then we will need a reproduction of the issue before we can investigate this further.
