### ISSUE TITLE
onColumnMoved should send `fromIndex`

### ISSUE THREAD

**Issue by SamiKamal** [ag-grid/ag-grid#5700]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

`onColumnMoved` event should send the `fromIndex` property along with the `toIndex`. I don't think it's that beneficial to only have the `toIndex`

**Comment by StephenCooper** [comment]
Thanks for the suggestion. The best way to get this feature request prioritised is to submit this request via our Enterprise support system. It is not quite such a simple task as there are some edge cases to be considered. Hence why it has not already been done. 

It would be possible to get this information by keeping track of the current column model and pulling out the old indexes from that before updating this local copy to match after a column has been moved.

I am going to close this issue now as there will be nothing more for me to add.
