### ISSUE TITLE
升级版本报错（v16.0.1 --> v27.0.0）环境 React

### ISSUE THREAD

**Issue by AI-fisher** [ag-grid/ag-grid#5702]
**I'm submitting a support**

**Requesting Community Support**

**Current behavior**
升级版本报错（v16.0.1 --> v27.0.0）后浏览器控制台报错：
Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect()

* **AG Grid version:** v27.0.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'

* **Language:** React 16.8.3

**Comment by StephenCooper** [comment]
I am afraid I am not 100% sure what the issue is that you are facing. Would it be possible to have it in a reproduction?
