### ISSUE TITLE
Tailwind CSS support?

### ISSUE THREAD

**Issue by mikebourbeauart** [ag-grid/ag-grid#5708]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
Has anyone had any success with getting tailwind to work with ag grid?

I was able to edit grid styling with tailwind by creating a utility layer in my tailwind app.css file like so:
```
@tailwind utilities;

@layer utilities {
    .ag-theme-alpine-dark 
        .ag-root-wrapper {
            --ag-header-background-color: transparent;
            ...
        }
        .ag-header-cell {
            border-right: 1px solid #111;
        }
}
```

I set the style in my typescript file like this:
```
 <div
          className="ag-theme-alpine dark:ag-theme-alpine-dark "
          style={{
            height: '100%',
            width: '100%',
          }}
        >
          <AgGridReact
            ref={gridRef} // Ref for accessing Grid's API
            ...
          />
</div>
```

I think this should work, but when I toggle between default and dark themes it just keeps my default theme. 
If I add something like `dark:bg-cyan-500` to the style it will correctly make the bg cyan in dark mode only. 
What am I missing here? Why doesn't the dark theme turn on when I enter dark mode?
Thanks in advance for any help!

**Comment by MuhammadKashifShamim** [comment]
@StephenCooper DId you figure out how to switch styles between light and dark using tailwind. I'm currently struggling with it. Would love to see how to managed it.

**Comment by zfan40** [comment]
you can use built in class [ag-theme-quartz-auto-dark](https://www.ag-grid.com/example?theme=ag-theme-quartz-auto-dark)  I don't know exactly why `dark:ag-theme-alpine-dark` doesn't work.
