### ISSUE TITLE
Passing objects to custom group cell renderer

### ISSUE THREAD

**Issue by iYadgar** [ag-grid/ag-grid#5709]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
Passing an object through the value getter/key creator as the value to the cell renderer will get there as string of '[object Object]'

**Expected behavior**
I would expect that the keyCreator will return a string/number (comparable entity to let the grid group correctly) and the value getter should be able to pass the actual object to the cell renderer. The only way I found to pass the whole object is to reassign the grid context and then the cell renderer component can consume it through `params.context` on `agOnInit`.

**Please tell us about your environment:**
Mac OS Monterey, Webstorm.

* **AG Grid version:** 22.1.1 (enterprise license)

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'

* **Language:** Typescript 4.7.4, angular 14

**Comment by StephenCooper** [comment]
Could you please create a reproduction of this issue. My expectation would be that this has very likely been fixed in a more recent version of AG Grid, if you can still reproduce this in v28 then we will look into this further. However, please note we do not apply fixes to old versions.
