### ISSUE TITLE
[search] Chrome's find-in-page for offscreen column breaks grid

### ISSUE THREAD

**Issue by greglockwood** [ag-grid/ag-grid#571]
### Description of the bug

Using Chrome's "find in page" functionality (Ctrl / Cmd + F, usually) to search for column heading text for a column that is offscreen to the right when the grid is horizontally scrollable causes the header row to be scrolled while the body is not scrolled to match. This causes the header row to be permanently out of alignment with the body, and it is not possible to fix manually.
### Screenshot

![image](https://cloud.githubusercontent.com/assets/75577/11227922/3798ae20-8ddd-11e5-9779-3dcb07b34351.png)
### How to reproduce
1. Open the [Test Drive page](http://ag-grid.com/example.php) in Chrome.
2. Press Ctrl-F (Windows) or Cmd+F (Mac)
3. Type "Oct" to search for the October column header
4. Notice that the heading cells are no longer lined up with the body cells.
### Browsers affected

Chrome (I was using version 46.0.2490.86 m)
Firefox does not appear to be affected. Not sure about other browsers.
### Cause

This appears to be because Chrome scrolls the header div to show the matching heading cell div in view. However, it does not know to scroll the body div the same amount.
### How to fix

You can attach a `scroll` event handler to the header row div. This handler will be triggered by Chrome when the "Oct" header cell is scrolled into view. The `scrollLeft` amount of the header div should be applied to the body div as well, so they are in sync.

The following code works in my devtools console to fix the issue. Apply it as you see fit in the actual code:

```
document.getElementsByClassName('ag-header')[0].addEventListener('scroll', function (event) {
    document.getElementsByClassName('ag-body-container')[0].style.left = (-1 * event.target.scrollLeft) + 'px';
});
```

**Comment by ceolter** [comment]
Thanks for raising. Will check when back from holiays.

**Comment by ceolter** [comment]
this will never work - as the chrome search will only search what is rendered in the dom. the solution would be for us to implement our own search for the grid.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-88

**Comment by ceolter** [comment]
tracked by AG-60 (88 was a dupe)

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by paklau** [comment]
I'm facing the same issue now. I cannot access https://ag-grid.atlassian.net/browse/AG-88 or AG-60 to see the updates on this. Have any features rolled out to achieve this?
