### ISSUE TITLE
AgGrid not honoring row height returned by getRowHeight in Infinite Scroll

### ISSUE THREAD

**Issue by totszwai** [ag-grid/ag-grid#5720]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**

`getRowHeight` gets called but the returned height is not honored by AgGrid.
https://plnkr.co/edit/8py04sDDVWa2k4rb?open=index.tsx

The plnkr is the exact same example from Infinite Scrolling, only added `getRowHeight` 

**Current behavior**

`getRowHeight` gets called but the returned height is not honored by AgGrid.

**Expected behavior**

Expected AgGrid to use the height returned by getRowHeight.
The documentation of `getRowHeight` did not state that it won't work for Infinite Scroll and the fact that it actually getting called multiple times shows that AgGrid uses it, but for some reason, it just doesn't care/take the returned value.

https://www.ag-grid.com/react-data-grid/row-height/#reference-styling-getRowHeight

Environment:

**AG Grid version:**

* 27.2.1
* 27.3.0
* 28 (latest, from plnkr)

**Browser:**

Chrome, Edge

**Language:** 

TypeScript, React

**Comment by AndrewGlazier** [comment]
Hi,

Dynamic row heights are not a supported feature of the infinite row model, this is documented in the table here: https://www.ag-grid.com/archive/28.2.1/javascript-data-grid/row-models/#row-model-comparisons

I will create a jira to clarify on the dynamic row heights page that this is not compatible.

Regards,
