### ISSUE TITLE
is it possible to set selected/unselected checkbox icon via gridOptions

### ISSUE THREAD

**Issue by Oterem** [ag-grid/ag-grid#5721]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I want to override the some icons. Some of the icons are the checkbox icons. 
So I have the icons object and I pass it to the <AgGridReact/> component:
const icons = {
        sortAscending: FuncReturningDomElement,
        sortDescending: FuncReturningDomElement,
      }
`

What is the key for the checked/uncheck checkbox icon? I can't find it. does the table support such thing? I don't want to change it via css. I checked this link:
https://github.com/ag-grid/ag-grid/blob/b63c9cc0bdc07b616339d461b75786be870ed607/grid-packages/ag-grid-docs/documentation/doc-pages/global-style-customisation-widgets/index.md#styling-checkboxes

but not sure what is the object key

**Comment by StephenCooper** [comment]
The full list of icons that are supported via GridOptions can be found here. https://ag-grid.com/javascript-data-grid/custom-icons/#set-the-icons-through-gridoptions-javascript

So as you can see checkbox icon is not supported with this approach meaning you will have to use CSS for this property. 

If you are an Enterprise user feel free to raise this as a Feature Request via Zendesk.
