### ISSUE TITLE
how to stop  local sort?

### ISSUE THREAD

**Issue by Valar103769** [ag-grid/ag-grid#5729]
1. when sort icon be cliked, i need fetch remote data, consequently i need stop  local sort, 
2. also when rowData is null, the loading show by automatic, but when sorting the loading doesnot show, and the showed is `no Rows to show`, i want  show loading when sort

how to to it please? 

```
import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model'
ModuleRegistry.registerModules([ClientSideRowModelModule])
```

**Comment by Valar103769** [comment]
```js
defaultColDef: {

    comparator: (a, b) => 0, // 禁用本地排序, 启用后端排序
  },
```
the above can work, but i think this is not a goog way

**Comment by StephenCooper** [comment]
I am afraid without a working reproduction it would be hard for us to give you an answer. In the meantime this might help you out. 

https://ag-grid.com/javascript-data-grid/overlays/

**Comment by Valar103769** [comment]
this is a feature not a bug, so it needless reproduction

**Comment by StephenCooper** [comment]
Ok. We use github issues for bug reports mainly and would request that feature requests come through our AG Grid Enterprise support queue: https://ag-grid.zendesk.com/. However, it seems like use of the overlay api would be your best optoin.
