### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a constructor or null     at eval (AgChartsVue.js?36f8:11:1)

### ISSUE THREAD

**Issue by yashwanth2714** [ag-grid/ag-grid#5741]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
* Project migration from Vue2 to Vue3.

**Current behavior**
We are getting the below error when using ag-charts-vue3

![ag-charts-vue3](https://user-images.githubusercontent.com/36370530/199407981-8745dac4-c488-4116-8951-0b27295d149c.png)

**Expected behavior**
There should not be any errors related to ag-charts-vue3

**Please tell us about your environment:**
O.S: Windows 10
IDE: VS Code
Package Manager: npm

* **AG Grid version:** 28.2.0

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'

* Vue: 3.2.37
* ag-grid-vue3: 28.2.0
* ag-charts-vue3: 6.2.0
* ag-charts-community: 6.2.0
* TypeScript: 3.7.3

**Comment by seanlandsman** [comment]
Can you please provide a repo of this issue? This stacktrace alone isn't enough for us to investigate I'm afraid.

**Comment by yashwanth2714** [comment]
We are working on it. Could you please tell us like in which scenarios it causes this error?

**Comment by yashwanth2714** [comment]
@seanlandsman - Here is the repo link to reproduce the issue.

[https://github.com/rangaraajv/Ag-Charts-Vue-3-TS](https://github.com/rangaraajv/Ag-Charts-Vue-3-TS)

Please run the serve cmd after installing the dependencies.

1. npm install
2. npm run serve

Open the localhost url and check the console to see the error.

**Comment by seanlandsman** [comment]
Please replace the `vue-class-component` dependency:

`"vue-class-component": "8.0.0-rc.1"`

thanks

**Comment by yashwanth2714** [comment]
It is working. Thank You!
