### ISSUE TITLE
Ag Grid giving warning messages when trying to restore old chart model

### ISSUE THREAD

**Issue by kunal-epsc** [ag-grid/ag-grid#5766]
I'm submitting a ...
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Current behavior**
   The charts saved using previous version of AG-Grid when restored on the new version of Ag Grid throws warning

Old chart model:
![old chart JSON structure](https://user-images.githubusercontent.com/99380988/201077374-79b4b186-a1bf-418a-ad38-b2f1084b4c12.png)

New chart model:
![new chart JSON structure](https://user-images.githubusercontent.com/99380988/201077369-015b5d99-c88e-4ef3-926c-a92764f1f58b.png)

Warning messages:
![warning messages](https://user-images.githubusercontent.com/99380988/201077377-2b23648a-8d4a-4e11-b4a9-5d173106a5dc.png)

    -> Older version of AG-Grid:
          "ag-charts-angular": "^5.0.0",
          "ag-charts-community": "^5.0.0",
          "ag-grid-angular": "27.0.0",
          "ag-grid-community": "27.0.1",
          "ag-grid-enterprise": "27.0.1",
    
    -> Newer version of Ag-Grid:
          "ag-charts-angular": "^6.1.1",
          "ag-charts-community": "^6.1.3",
          "ag-grid-angular": "28.1.1",
          "ag-grid-community": "28.1.1",
          "ag-grid-enterprise": "28.1.3",
  
    Warning message samples:
    -> AG Charts - unable to set [title.padding] in Caption - property is unknown
    -> AG Charts - unable to set [subtitle.padding] in Caption - property is unknown
    -> AG Charts - unable to set [axes[0].title.padding] in Caption - property is unknown

    To reproduce the warnings: 
    -> Create a chart model using the older version of AG Grid
    -> Use this chart model in the newer version 
   
**Expected behavior**
   Warning messages should not be displayed.

**Comment by StephenCooper** [comment]
Hi @kunal-epsc,

Thanks for reporting this pain point, we were made aware of this already so in 28.2 / 6.2 we added automated migration support. This should update your old model to match the new model and avoid the errors above. 

If after upgrading you still get errors then please let us know.

**Comment by kunal-epsc** [comment]
Hello @StephenCooper,

Thanks for the reply. I'll update the thread if i face any issues after Ag-Grid upgrade.
