### ISSUE TITLE
How can I hide 0's in a stacked bar chart when there is no value?

### ISSUE THREAD

**Issue by jackdh** [ag-grid/ag-grid#5769]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

![image](https://user-images.githubusercontent.com/1907451/201149192-f114cb5e-75b5-4d08-8822-3f0e2df8fc42.png)

As you can see there is a lot of 0 labels. Is there a way to hide them? This is with the standalone charts.

**Comment by AndrewGlazier** [comment]
Hello!

Thanks for reaching out.

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license;
https://ag-grid.zendesk.com/

**Comment by StephenCooper** [comment]
As a workaround if you do not provide a value for the property then nothing will be rendered. If you have a 0 in your data then the chart will show this. 

See this [example](https://plnkr.co/edit/T6flUurhUF06DtCb?open=main.js) in data.js where you can see the difference in not providing a value vs 0.
