### ISSUE TITLE
Hide columns with no data

### ISSUE THREAD

**Issue by jonluca** [ag-grid/ag-grid#5774]
I'd like to automatically hide columns where every row has empty data.

This would be somewhat easy if each column field mapped to the data directly - I could do something like:

```ts
 onRowDataUpdated={(e) => {
          const cols = e.columnApi.getColumns();
          if (!cols) {
            return;
          }
          const rowData: RowNode<any>[] = [];
          e.api.forEachNodeAfterFilter((node) => {
            rowData.push(node.data);
          });

          if (!rowData.length) {
            e.api.forEachNode((node) => {
              rowData.push(node.data);
            });
          }
          for (const c of cols) {
            const colDef = c.getColDef();
            if (!colDef.field) {
              continue;
            }
            if (!rowData.some((r) => r[colDef.field])) {
              e.columnApi.setColumnVisible(c, false);
            } else {
              e.columnApi.setColumnVisible(c, Boolean(colDef.initialHide));
            }
          }
        }}
```

However, most of my columns have `valueGetters`.

Is there a way to get all the rendered data for a grid, not the actual underlying data? Maybe using the valueCache?

**Comment by StephenCooper** [comment]
The getValue method on the GridApi sounds like it could be what you are looking for. This takes into account the valueGetter if it exists.

https://ag-grid.com/javascript-data-grid/grid-api/#reference-miscellaneous-getValue
