### ISSUE TITLE
Set Filter Ui breaks if data contains line breaks

### ISSUE THREAD

**Issue by FW22** [ag-grid/ag-grid#5780]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Here is a plunker:
- https://plnkr.co/edit/JxlMjM5vzTbQeBkL?preview

**Current behavior**
if the data contains line breaks ("\n") the filter ui renders these line breaks in the multiselect list. This breaks the list.
In my plunker example I have included line breaks in the Country-Column in the Ukraine-Dataset.

**Expected behavior**
I would expect the multiselect list in the set filter ui to ignore line breaks.
By the way: the ag grid table itself, does ignore these line breaks as it should.

**Please tell us about your environment:**
see plunker

* **AG Grid version:** X.X.X
see plunker

* **Browser:**
Chrome

* **Language:**
see plunker

![image](https://user-images.githubusercontent.com/56593428/201902491-e721f187-0078-496b-94b8-f47981b1eda6.png)

**Comment by kiril-matev** [comment]
Hello @FW22,

We've discussed this with our product team and found that this isn't an issue.

AG Grid cannot make assumptions about your data and clean invalid characters on its own before presentation. The application is responsible for clearing invalid data with the use of a valueFormatter. This is explained here:
https://www.ag-grid.com/javascript-data-grid/filter-set-filter-list/#value-formatter

See an example of how to use the filter valueFormatter to remove the new line characters from the values to be shown in the filter list:
https://plnkr.co/edit/AXX86tDwKVRvVD4A?open=main.js

As this can easily be resolved using built-in functionality, we've now closed AG-7548 as rejected. Please use the approach above to resolve this.

Thank you for your time - much appreciated!
