### ISSUE TITLE
When filtering Cross Filter charts, values are equated regardless of character case

### ISSUE THREAD

**Issue by addStephen** [ag-grid/ag-grid#5782]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have a pie chart based upon a column with multiple values that share the same characters but have different casing. If I select a lowercase pie slice that has no uppercase equivalent, the associated grid filters down correctly. However, if I select a slice that does have an equivalent (regardless of which one is selected), both slices of the pie chart are highlighted and the uppercase value is passed into the filter. 
See image below: I select the 'b' slice, yet the 'B' slice is also selected and 'B' is entered in the CRIT filter.

![image](https://user-images.githubusercontent.com/47248301/201915885-eb8781c8-6c7b-473c-988c-31ef21a6d2c0.png)

I created a custom value formatter, but the value was already capitalized when it reaches it.
I set a basic custom comparator but applying filters doesn't seem to trigger it.

**Expected behavior**
Chart Values filter should match the values displayed in the Legend, or should use the column's definition to determine if the filter is caseSensitive or not.

**Please tell us about your environment:**
Windows, Visual Studio Code, Composer, PHP HTTP server

* **AG Grid version:** 28.1

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.42'
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'

* **Language:** [all | JavaScript 1.5 | ES6/7 | ES5]

**Comment by AndrewGlazier** [comment]
Hi @addStephen,

The first thing we need to dig into this issue would be a reproducible scenario, could you please provide us with a plunker demonstrating this issue?
