### ISSUE TITLE
How to test AG Grid Row Events e. g. rowClicked, rowDoubleClicked, etc.?

### ISSUE THREAD

**Issue by icapri** [ag-grid/ag-grid#5783]
Hi Guys!

```
**I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] support request
```

**Current behavior**
I am writing Jest Tests regarding AG Grid Angular in my project and I have seen something weird regarding to events related to rows in AG Grid. For 'click' and 'dblclick' there is only one listener for a container div but not for the rows.

```typescript
it('should select/deselect vehicle when clicked on a row', () => {
    const firstRow = fixture.debugElement.query(By.css('.ag-center-cols-container .ag-row'));
    const rowClickedSpy = jest.spyOn(component.rowClicked, 'emit');
    firstRow.nativeElement.dispatchEvent(new MouseEvent('click')); // I have also tried `, { bubbles: true }`
    fixture.detectChanges();
    const firstRowData = { /* first row data object */ };
    expect(rowClickedSpy).toBeCalledWith(firstRowData);
});
```

**Expected behavior**
It should be possible to dispatch a click or dblclick event for rows in Jest.

* **AG Grid version:** 28.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

* **Language:** TypeScript

Thank you in advance!

**Comment by AndrewGlazier** [comment]
Hello!

Thanks for reaching out.

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license;
https://ag-grid.zendesk.com/

**Comment by StephenCooper** [comment]
Hi @icapri,

This is a feature of the grid that we do not have a workaround at this point of time as it is key to the performance of the grid as is explained in one of our old blogs.

> The grid needs to have mouse and keyboard listeners on all the cells so that the grid can fire events such as 'cellClicked' and so that the grid can perform grid operations such as selection, range selection, keyboard navigation etc. In all there are 8 events that the grid requires at the cell level which are click, dblclick, mousedown, contextmenu, mouseover, mouseout, mouseenter and mouseleave.

> Adding event listeners to the DOM results in a small performance hit. A grid would naturally add thousands of such listeners as even 20 visible columns and 50 visible rows means 20 (columns) x 50 (rows) x 8 (events) = 8,000 event listeners. As the user scrolls our row and column virtualisation kicks in and these listeners are getting constantly added and removed which adds a lag to scrolling.

> Solution - Event Propagation
> 6 of these 8 events propagate (the exceptions are mouseenter and mouseleave). So instead of adding listeners to each cell, we add each listener once to the container that contains the cells. That way the listeners are added once when the grid initialises and not to each individual cell.

Did you manage to write your tests against the container?
