### ISSUE TITLE
Horizontal scroll in macOS, 28+ version

### ISSUE THREAD

**Issue by d0r0sh** [ag-grid/ag-grid#5787]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
All examples up to version 28 have visible horizontal grid scroll by default if the sum of all column widths exceeds the width of the grid itself. See an example grid here: (https://www.ag-grid.com/archive/27.3.0/angular-data-grid/scrolling-performance/)

After the 28th version, the horizontal scroll disappeared and appears only when we do a touch or mouse event, see an example grid here:  (https://www.ag-grid.com/angular-data-grid/scrolling-performance/)

**Important information.** The scroll visibility setting on my computer was the same for both cases, screenshots below

<img width="533" alt="image" src="https://user-images.githubusercontent.com/46892003/202045907-95a6a3a4-227e-4b79-b0ea-31d338754671.png">

How can i get previous scroll logic in 28+ version?

**Current behavior**
the horizontal scroll disappeared and appears only when we do a touch or mouse event

**Expected behavior**
always visible when sum of all column width is greater than width of the grid itself

OS: macOS
AG Grid version: 28.1.1
Browser: Google Chrome 106.0.5249.119
Language: all

Thanks in advance!

**Comment by gportela85** [comment]
Note that this was a BUG, the horizontal scrollbar should behave the same way as the vertical scrollbar (only visible when scrolling).

If you like the odd behavior, you can use the following CSS in your app: 

```
.ag-scrollbar-invisible.ag-apple-scrollbar {
    display: inherit !important;
}
.ag-scrollbar-invisible {
    pointer-events: none;
}
.ag-scrollbar-invisible.ag-scrollbar-scrolling {
    pointer-events: all;
}
```

see: https://plnkr.co/edit/37l4qGTc0PMkCXJw?open=app%2Fapp.component.ts&preview
