### ISSUE TITLE
need functionality to update grid Options to change enableRangeHandle state on spescific colId when clicked

### ISSUE THREAD

**Issue by AwaisBinKaleem** [ag-grid/ag-grid#5790]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- steps to reproduce the behaviour is here.

```
const gridRef = useRef(null);

const onCellClicked = params => {
    let colId = params.colDef.colId;
    let cols = ['status', 'description', 'due_date', 'asignee', 'priority'];
    if (
      cols.find(item => {
        return item === colId;
      })
    ) {
      gridRef.current.gridOptions.enableRangeHandle = true;
    } else {
      gridRef.current.gridOptions.enableRangeHandle = false;
    }
  };

<div className="ag-theme-alpine" style={{ height: '100%', width: '100%' }}>
      <AgGridReact
        ref={gridRef}
        enableRangeHandle={false}
        onCellClicked={onCellClicked}
        rowData={allMarkups}
>

```
**Please tell us about your environment:**

* **AG Grid version:** 25.0.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
I have record this under our Reactivity project as an example of a user request for this property to be made reactive with reference AG-7863. 

I will close the ticket here as it is now recorded internally.
