### ISSUE TITLE
confusing context handling

### ISSUE THREAD

**Issue by kerosan** [ag-grid/ag-grid#5793]
context defined in gridOptions was cleared by context from props even if i not pass it to props

**Comment by StephenCooper** [comment]
Can you please give us a reproduction to help us investigate this? 

It is expected that context defined via props will override that on GridOptions as documented [here](https://ag-grid.com/react-data-grid/grid-interface/#grid-options-2)

**Comment by kerosan** [comment]
https://codesandbox.io/s/unruffled-noether-ukvmm6?file=/src/GridExample.js
without context as prop 
![image](https://user-images.githubusercontent.com/10149363/202698485-b4e2c789-dffc-4744-9c33-9ae393a2c083.png)
with context as prop (expected behaviour)
![image](https://user-images.githubusercontent.com/10149363/202698467-e3cff4b2-8377-4b36-9d7c-2d544d48d987.png)

**Comment by StephenCooper** [comment]
Ok, I understand what is happening here. The `gridOptions` prop is not currently reactive while every other property (which are all children of gridOptions) are reactive. 

This is a current limitation of our React component. We do have a project to look into our reactivity support and will make a note to evaluate this issue as part of that. 

I am going to close this ticket as it is now recorded in our backlog. Thanks for reporting!
