### ISSUE TITLE
Tension lines

### ISSUE THREAD

**Issue by DEV-LIMBURG** [ag-grid/ag-grid#5796]
Just created smooth tension lines for the line/area charts to the main js file. How can i add this feature to the source code to add enable tension end the tension level? (Using ag-grid enterprise for several years with license)

**Comment by StephenCooper** [comment]
Hi, 

Just to let you know we do not tend to accept major PRs to the core code so I would frame this as a feature request via ZenDesk. By all means create a PR with your changes to show what you feel would be required to support this. This would give this feature request the best chance of progressing but it would have to be verified and tested and prioritized by our Charts team.

We appreciate your effort in making this possible so please do share it with us. I will close this issue as I believe I have answered your question and pointed you to the approach that is most likely to result in this feature being supported.
