### ISSUE TITLE
Angular Data Grid: Clipboard :: Unable to paste data using [ Ctrl + V ] in cell when user tries for the first time.

### ISSUE THREAD

**Issue by yogeshpaisodeGL** [ag-grid/ag-grid#5798]
Hello Team,

Recently we upgraded to v28 from v23 and found that if we copy multiple cell data using ( Ctrl + V ) and if we try to paste it in another cell using ( Ctrl + V ) then it will not paste anything. If we click the cell again and then if we try to paste data using ( Ctrl + V ) then it will work. 

We are using ag-Grid v28 on Angular 13.

OS: Windows
Browser: Chrome, Edge

Please refer below step to reproduce the issue:

Here is the plunger for your reference: https://plnkr.co/edit/BJ6DOwbE7e604BYH?open=app%2Fapp.component.ts&preview

Step 1:  Copy row Data

![image](https://user-images.githubusercontent.com/105768857/202504939-58592eb5-b816-46ce-a4d8-8a27f4527642.png)

Step 2: Single-click in any cell and try to paste copied row data into the cell using ( Ctrl + V ). 
Observation Nothing will paste

![image](https://user-images.githubusercontent.com/105768857/202505835-821dc9e4-44f1-44b8-82a8-cd3aaa89981b.png)

Step 3: Click again on the same cell and try to paste data using ( Ctrl + V ).
Observation: data will be pasted

![image](https://user-images.githubusercontent.com/105768857/202506661-3b35a0d1-aa1e-475d-be59-bdeb90992b8e.png)

Expedition: We want data to be pasted immediately when the user clicks on the cell for the first time.  

Please do let us know how we can fix this issue:

Thanks!

**Comment by StephenCooper** [comment]
I cannot reproduce the behaviour you described given your plunker. This could be related to the Browser Clipboard Api not working as expected. Permissions are required for the Clipboard api.
 
You could try to set the following flag `suppressClipboardApi: true`
 
https://ag-grid.com/javascript-data-grid/grid-options/#reference-clipboard-suppressClipboardApi
 
We have a mechanism in place to automatically turn on legacy mode when the clipboard API is not working well but maybe this is not working as expected for you.

**Comment by yogeshpaisodeGL** [comment]
Hi @StephenCooper ,

May I know on which browser did you tried to reproduce this issue?

Thanks!
