### ISSUE TITLE
Excel Export of SSRM Grid with AutoGroupColumnDef exports the header name of grouped column as 'Group'

### ISSUE THREAD

**Issue by pmacha89** [ag-grid/ag-grid#5804]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Exporting a SSRM Grid to Excel that has AutoGroupColumnDef defined and some header name provided as below exports the grouped column with the Header name '**Group**' although the headername param has been assigned with the value '**Accounts**' as below:

const autoGroupColumnDef = useMemo(() => {
    return {
      headerName: 'Accounts',
      flex: 1,
      minWidth: 280,
    };
  }, []);

**Expected behavior**
The exported excel should contain the header name 'Accounts' for the Auto Group column instead of default header name 'Group'

* **AG Grid version:** X.X.X
version - 27.3.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'

* **Language:** 
React

**Comment by pmacha89** [comment]
AG Grid:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/96883087/202919566-1384378b-1977-4ec4-b8d7-30b4894281d3.png">

Exported Excel Screenshot:
<img width="785" alt="image" src="https://user-images.githubusercontent.com/96883087/202919617-fd621c4f-ce6f-42bf-9fc6-5ae600142ddf.png">

**Comment by StephenCooper** [comment]
Could you please help us investigate this by providing us with a plunker that reproduces the issue. I appreciate the screenshots show the issue but by providing a simple reproduction we will be able to resolve this quicker.
