### ISSUE TITLE
CSS Oddities in example code

### ISSUE THREAD

**Issue by awdorrin** [ag-grid/ag-grid#5808]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
On example page: https://www.ag-grid.com/angular-data-grid/cell-styles/#example-cell-styling
Although both cells/columns are defined to use the same CSS shade of green, the sport column is a different shade of green than every other green column.

**Current behavior**
Shades of green do not match

**Expected behavior**
Shades of green should match

* **Browser:**
Chrome/Firefox/Edge all look the same

**Comment by StephenCooper** [comment]
Hi @awdorrin,

This example is as expected. It all comes down to the fact that the hex value used in the cellStyle is different to the hex value for `lightGreen`

```css
cellStyle: {
      backgroundColor: '#aaffaa',
    }
```

If you change the cellStyle to use `lightGreen` instead of `#aaffaa` you will note that the colours for the columns then match up.
