### ISSUE TITLE
ag-Grid:: Angular Excel Export :: Unable to show options Excel Export (.xlsx)‎ & Excel Export (.xml)‎ in Context Menu

### ISSUE THREAD

**Issue by yogeshpaisodeGL** [ag-grid/ag-grid#5815]
Hi,

Recently we upgraded ag-Grid Angular from v23 to v27 and found that options Excel Export (.xlsx)‎  &  Excel Export (.xml)  are missing in Context Menu.

During v23 we were using _@ag-grid-enterprise/all-modules_  & it used to work perfectly fine.

I can see _@ag-grid-enterprise/all-modules_ is deprecated now. Hence we removed that and imported the required packages only.

I referred ag-Grid document and found two links.

**Reference 1:** https://www.ag-grid.com/archive/25.0.0/documentation/angular/excel-export/
https://plnkr.co/edit/WPbWEsBTMeMIFOdZ?preview

If we refer above plunker example which is taken from the **Reference 1:** link, then we can see both options appearing.

![image](https://user-images.githubusercontent.com/105768857/203560087-714b99a2-77a5-4c62-bb5f-d141e6a3b0b1.png)

**Reference 2:** https://www.ag-grid.com/angular-data-grid/excel-export/
https://plnkr.co/edit/aCugOcPUtVIejPAX?open=app%2Fapp.component.ts&preview

Now, If we refer above plunker example which is taken from **Reference 2:** link, then we can see both options are missing. 

![image](https://user-images.githubusercontent.com/105768857/203561059-8b2bd801-ec9d-4919-b7fa-40d60fe771d8.png)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I think the example from **Reference 1:** is using _@ag-grid-enterprise/all-modules_ which is deprecated now & **Reference 2:** is using _@ag-grid-enterprise/excel-export_ independent module.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Could you please suggest a solution on how we can bring back Excel Export (.xlsx) & Excel Export (.xml)  options in the Context Menu if we are using _@ag-grid-enterprise/excel-export_ independent module?

Thanks!

**Comment by StephenCooper** [comment]
hi @yogeshpaisodeGL,

We now only support .xlsx by default. The .xml format produced many security warnings as was not a fully supported Excel format. As a result we deprecated .xml and only return .xlsx by default.

Hope that explains the difference you are seeing.
