### ISSUE TITLE
Resize handle disappears when using enableRtl

### ISSUE THREAD

**Issue by yardenhod** [ag-grid/ag-grid#5816]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Resize handle disappears when using `enableRtl` property in material and alpine theme

before adding `enableRtl`:
![image](https://user-images.githubusercontent.com/53895521/203743253-caf1d68e-956e-4fdc-8741-da8ebd73e61a.png)

after adding `enableRtl`:
![image](https://user-images.githubusercontent.com/53895521/203743451-e3ce6ee9-ad84-4086-a820-f9b4a5821a81.png)

This bug also seen in the first example in this page:
https://www.ag-grid.com/react-data-grid/rtl/

**Expected behavior**
The resize handle will be appear like in ltr

**Please tell us about your environment:**

* **AG Grid version:** 28.2.1

* **Browser:** Checked on Chrome 78 and 107

* **Language:** React 18.2.0

**Comment by gportela85** [comment]
Hi, this has been fixed in the latest branched and will be released in v29.

Thanks for reporting.
