### ISSUE TITLE
Can I use a rich text editor in an ag-grid cell?

### ISSUE THREAD

**Issue by jiangweiatgithub** [ag-grid/ag-grid#5822]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
I want to use a rich text editor - like Quill - in a certain column. Can I?

**Comment by StephenCooper** [comment]
Sure, follow the documentation to add a custom cell editor. Within your custom cell editor you can use the Quill component and just implement the required wrapping within the custom cell editor.

https://ag-grid.com/javascript-data-grid/component-cell-editor/
