### ISSUE TITLE
Interaction of keyboard handling with popupParent

### ISSUE THREAD

**Issue by joshkel** [ag-grid/ag-grid#5833]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://codesandbox.io/s/ag-grid-keyboard-modal-3en34p?file=/src/MyDialog.tsx

**Current behavior**

If I want to show AG Grid within a modal dialog component (such as Material-UI's), then I set the grid's `popupParent` to the dialog's HTML element. (If I use `body`, then the grid's popups are covered up by the dialog's backdrop, which has a higher Z index. If I don't set `popupParent`, then popups are clipped, as described [here](https://www.ag-grid.com/react-data-grid/context-menu/#popup-parent).)

This works for display purposes, but handling of the Escape key don't work properly: the popup's keyboard handling is attached to the document, so the modal dialog sees the Escape key before the grid does, and it closes the dialog.

https://github.com/ag-grid/ag-grid/blob/eb2c26d7d9bef1864a44278f1305e6a85be1aaaf/community-modules/core/src/ts/widgets/popupService.ts#L481

**Expected behavior**

AG Grid sees the Escape key first, uses it to close the popup, and stops propagation so that it doesn't affect anything containing the popup parent.

Maybe popupService.ts should attach the keydown event to the popup parent or `.ag-popup` element instead of (or as well as?) the document.

**Please tell us about your environment:**

React

* **AG Grid version:** 28.2.1

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

* **Language:** [all]

**Comment by StephenCooper** [comment]
Hi @joshkel,

Thanks for reporting this. We do not believe that changing the location of the event listener will resolve this issue. Our suggestion would be to use `disableEscapeKeyDown` on your dialog as that enables you to close the AG Grid menu with Esc without also then closing the dialog. You may then have to implement your own logic on whether the dialog should close with Esc.

```    <Dialog disableEscapeKeyDown {...props}> ```

I am going to close this ticket as I do not believe there are changes required in AG Grid and if there is then this would really need to be made as a Feature Request via ZenDesk with an Enterprise account.

**Comment by StephenCooper** [comment]
Here is an example that my colleague put together that might help. 

https://codesandbox.io/s/ag-grid-keyboard-modal-forked-mj9q8r
