### ISSUE TITLE
agNumberColumnFilter cannot filter null or undefined value correctly when using "Not Equal" filter mode

### ISSUE THREAD

**Issue by peter1997546** [ag-grid/ag-grid#5834]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
1. Go to https://plnkr.co/edit/qVd4MS6V5FrQZvrR?open=index.tsx&preview
2. Click Filter button for "Age" Column
3. Change to "Not Equal"
5. Type 1 as the filtered value

Current behaviour. Only the row with Age 0 is shown after filtering
Expected behaviour. 
```
          rowData={rowData? [{...rowData[0],age:null},{...rowData[0],age:undefined},{...rowData[0],age:0},{...rowData[0],age:1}] :[]}
```
![image](https://user-images.githubusercontent.com/23149848/205001861-275784e2-2690-4b1f-8443-14d6093ea88f.png)

If you take a look on the line 79 in "index.tsx", you can see there's four records in total. Only the age of last one is equal to 1 so there should be three record (null, undefined, 0) shown after filtering.

OS: Windows 10
AG Grid version: 28.2.1
Browser: Google Chrome 107.0.5304.107
Language: all

**Comment by StephenCooper** [comment]
You need the following config to enable this.

```
    {
      field: 'age',
      filterParams: {
        includeBlanksInEquals: true,
      },
      filter: 'agNumberColumnFilter',
      maxWidth: 100,
    },
```

https://ag-grid.com/javascript-data-grid/filter-number/#reference-INumberFilterParams-includeBlanksInEquals
