### ISSUE TITLE
cancelBeforeStart doesn't work properly

### ISSUE THREAD

**Issue by kevinfairclough** [ag-grid/ag-grid#5836]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

[Example from website](https://www.ag-grid.com/examples/cell-editors/dynamic-editor-component/modules/reactFunctionalTs/index.html)
```

Current behaviour: 
Can type an invalid character into age.   Click age cell, tab to goto next cell and type "f".  "f" shouldn't be allowed 

Expected behaviour:
Only numerical characters should be able to be typed.

cancelBeforeStart seems to be called too late and the editor appears allowing typing of characters.
```
TIA 
Kevin

**Comment by gportela85** [comment]
This issue is being tracked as AG-7485, check the [pipeline](https://www.ag-grid.com/pipeline/)
