### ISSUE TITLE
enableCellTextSelection remove cellClass pseudo-selectors

### ISSUE THREAD

**Issue by d00rsfan** [ag-grid/ag-grid#5854]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
To reproduce:
    
1. Declare cellClass with pseudo-selector (::first-letter) in column definition.
f.e.
 `.cell-capitalize-first {
  text-transform: lowercase;
}
.cell-capitalize-first::first-letter {
  text-transform: uppercase;
}`
2. Set `enableCellTextSelection` option. Plain class is still applied, but not pseudo.
- A "Getting Started" with bug reproduction
[https://stackblitz.com/edit/ag-grid-react-hello-world-aasjzm?file=index.js,style.css](https://stackblitz.com/edit/ag-grid-react-hello-world-aasjzm?file=index.js,style.css)

**Current behavior**
All letters are in lower case.

**Expected behavior**
First letter must be capitalized due pseudo-selector ::first-letter

* **AG Grid version:** X.X.X
    "ag-grid-community": "^28.2.1",
    "ag-grid-react": "^28.2.1",

* **Browser:**
chromium family

* **Language:** [ES6/7]

**Comment by StephenCooper** [comment]
Thanks for the reproduction. I have raised this in our internal review process for issues.

**Comment by StephenCooper** [comment]
Turns out this is not a bug but just needs slightly updated css. The following css will do what you want.

```
.cell-capitalize-first {
  text-transform: lowercase;
}

.cell-capitalize-first::first-letter,
.cell-capitalize-first .ag-cell-value::first-letter {
  text-transform: uppercase;
}
```
