### ISSUE TITLE
Website Getting Started link broken

### ISSUE THREAD

**Issue by sjtrimble** [ag-grid/ag-grid#5855]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Not sure if opening an issue for this here is appropriate, but wanted to make you aware.

**Current behavior**
Website _Getting Started_ link in footer is broken and navigates to https://www.ag-grid.com/undefined-data-grid/getting-started/.

**Expected behavior**
Link should navigate to https://www.ag-grid.com/javascript-data-grid/getting-started/
![Screen Shot 2022-12-05 at 9 47 57 AM](https://user-images.githubusercontent.com/2958442/205680538-068ab5d5-8c91-437d-aeae-d673924cfea6.png)

**Please tell us about your environment:**
N/A

* **AG Grid version:** X.X.X
N/A

* **Browser:**
Chrome Version 107.0.5304.110

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

**Comment by StephenCooper** [comment]
Thank you very much for reporting! We will look into it.

**Comment by StephenCooper** [comment]
Have raised AG-7660, so that this will be fixed in our next release. Thanks again for letting us know!
