### ISSUE TITLE
colResizeDefault={'shift'} has no effect on column resizing functionality

### ISSUE THREAD

**Issue by alaney2** [ag-grid/ag-grid#5857]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In React, putting colResizeDefault={'shift'} in the <AgGridReact /> component doesn't making shift resizing the default behavior. Putting it in gridOptions doesn't do anything either.

**Expected behavior**
Shift resizing should be the default way of resizing a column. 

**Please tell us about your environment:**
macOS, VSCode

* **AG Grid version:** X.X.X
28.2.1

* **Browser:**
'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
JavaScript, React 18.2.0

**Comment by StephenCooper** [comment]
Can you provide a reproduction because this is working in our current version 28.2.1 as can be seen here.

https://plnkr.co/edit/uY5KOhoF3LYbzrKH?open=index.tsx

**Comment by peterolson** [comment]
@StephenCooper In the link you show it doesn't appear to be working. If I hold "Shift", it uses shift resizing behavior, but if I don't hold shift, it uses default resizing behavior.
