### ISSUE TITLE
[pagination] Client side sorting and filtering  works only on current page

### ISSUE THREAD

**Issue by pacificeyes** [ag-grid/ag-grid#587]
Client side sorting and filtering  works only on current page. 
Even the sort and filter is not preserved on the next page.

The server side filtering example doesn't give much insight on filterModel usage. As even after using that only one filter works at a time. 

The header should allow to add filterparams by fetching the master data from db.
It's not working because of async calls to service.

**Comment by pacificeyes** [comment]
Using your server side filtering, sorting and pagination example, I could come up with below example which is working fine. The header menu is now storing the unique values also.

var module = angular.module("example", ["agGrid"]);

module.controller("exampleCtrl", function ($scope, $http) {
    $scope.pageSize = '25';
    $scope.gridOptions = {
        columnDefs: [],
        rowData: null,
	rowSelection: 'single',
        enableServerSideSorting: true,
        enableServerSideFilter: true,
        onRowSelected: rowClicked,
        angularCompileFilters: true
    };

    var allOfTheData;
    PopulateData();

    function rowClicked(event) {
        console.log(event);
    }

    function PopulateData() {
        var columnDefs = [];
        var countries = [];
        var years = [];
        var athletes = [];
        var ages = [];
        var dates = [];
        var sports = [];

        $http.get("olympicWinners.json")
            .then(function (res) {
                allOfTheData = res.data;
                for (var i = 0; i < res.data.length; i++) {
                    if (athletes.indexOf(res.data[i].athlete) == -1) {
                        athletes.push(res.data[i].athlete);
                    }

                    if (ages.indexOf(res.data[i].age) == -1) {
                        ages.push(res.data[i].age);
                    }

                    if (countries.indexOf(res.data[i].country) == -1) {
                        countries.push(res.data[i].country);
                    }

                    if (years.indexOf(res.data[i].year) == -1) {
                        years.push(res.data[i].year);
                    }

                    if (dates.indexOf(res.data[i].date) == -1) {
                        dates.push(res.data[i].date);
                    }

                    if (sports.indexOf(res.data[i].sport) == -1) {
                        sports.push(res.data[i].sport);
                    }
                }
                columnDefs = [
                    {
                        headerName: "Athlete", field: "athlete", width: 150, filter: 'set', filterParams: {
                            values: athletes, newRowsAction: 'keep'
                        }
                    },
                    {
                        headerName: "Age", field: "age", width: 90, filter: 'set', filterParams: {
                            values: ages, newRowsAction: 'keep'
                        }
                    },
                    {
                        headerName: "Country", field: "country", width: 120, filter: 'set', filterParams: {
                            values: countries, newRowsAction: 'keep'
                        }
                    },
                    {
                        headerName: "Year", field: "year", width: 90, filter: 'set', filterParams: {
                            values: years, newRowsAction: 'keep'
                        }
                    },
                    {
                        headerName: "Date", field: "date", width: 110, filter: 'set', filterParams: {
                            values: dates, newRowsAction: 'keep'
                        }
                    },
                    {
                        headerName: "Sport", field: "sport", width: 110, filter: 'set', filterParams: {
                            values: sports, newRowsAction: 'keep'
                        }
                    },
                    { headerName: "Gold", field: "gold", width: 100, filter: 'number' },
                    { headerName: "Silver", field: "silver", width: 100, filter: 'number' },
                    { headerName: "Bronze", field: "bronze", width: 100, filter: 'number' },
                    { headerName: "Total", field: "total", width: 100, filter: 'number' }
                ];
                $scope.gridOptions.api.setColumnDefs(columnDefs);
                createNewDatasource();
            });
    }

    function createNewDatasource() {
        if (!allOfTheData) {
            // in case user selected 'onPageSizeChanged()' before the json was loaded
            return;
        }

        var dataSource = {
            //rowCount: ???, - not setting the row count, infinite paging will be used
            pageSize: parseInt($scope.pageSize), // changing to number, as scope keeps it as a string
            getRows: function (params) {
                // this code should contact the server for rows. however for the purposes of the demo,
                // the data is generated locally, a timer is used to give the experience of
                // an asynchronous call
                console.log('asking for ' + params.startRow + ' to ' + params.endRow);
                setTimeout(function () {
                    // take a chunk of the array, matching the start and finish times
                    //var rowsThisPage = allOfTheData.slice(params.startRow, params.endRow);
                    var dataAfterSortingAndFiltering = sortAndFilter(params.sortModel, params.filterModel);
                    var rowsThisPage = dataAfterSortingAndFiltering.slice(params.startRow, params.endRow);                    // see if we have come to the last page. if we have, set lastRow to
                    // the very last row of the last page. if you are getting data from
                    // a server, lastRow could be returned separately if the lastRow
                    // is not in the current page.
                    var lastRow = -1;
                    if (dataAfterSortingAndFiltering.length <= params.endRow) {
                        lastRow = dataAfterSortingAndFiltering.length;
                    }
                    params.successCallback(rowsThisPage, lastRow);
                    params.rowData = rowsThisPage;
                    $scope.gridOptions.api.selectIndex(0, false, false);
                }, 500);
            }
        };

        $scope.gridOptions.api.setDatasource(dataSource);
    }

    function sortAndFilter(sortModel, filterModel) {
        return sortData(sortModel, filterData(filterModel, allOfTheData))
    }

    function sortData(sortModel, data) {
        var sortPresent = sortModel && sortModel.length > 0;
        if (!sortPresent) {
            return data;
        }
        // do an in memory sort of the data, across all the fields
        var resultOfSort = data.slice();
        resultOfSort.sort(function (a, b) {
            for (var k = 0; k < sortModel.length; k++) {
                var sortColModel = sortModel[k];
                var valueA = a[sortColModel.colId];
                var valueB = b[sortColModel.colId];
                // this filter didn't find a difference, move onto the next one
                if (valueA == valueB) {
                    continue;
                }
                var sortDirection = sortColModel.sort === 'asc' ? 1 : -1;
                if (valueA > valueB) {
                    return sortDirection;
                } else {
                    return sortDirection * -1;
                }
            }
            // no filters found a difference
            return 0;
        });
        return resultOfSort;
    }

    function filterData(filterModel, data) {
        var filterPresent = filterModel && Object.keys(filterModel).length > 0;
        if (!filterPresent) {
            return data;
        }

        var resultOfFilter = [];
        for (var i = 0; i < data.length; i++) {
            var item = data[i];

            if (filterModel.athlete) {
                if (filterModel.athlete.indexOf(item.athlete) < 0) {
                    // year didn't match, so skip this record
                    continue;
                }
            }

            if (filterModel.age) {
                if (filterModel.age.indexOf(item.age) < 0) {
                    continue;
                }
            }

            if (filterModel.country) {
                if (filterModel.country.indexOf(item.country) < 0) {
                    // year didn't match, so skip this record
                    continue;
                }
            }

            if (filterModel.year) {
                if (filterModel.year.indexOf(item.year.toString()) < 0) {
                    // year didn't match, so skip this record
                    continue;
                }
            }            

            if (filterModel.date) {
                if (filterModel.date.indexOf(item.date) < 0) {
                    // year didn't match, so skip this record
                    continue;
                }
            }

            if (filterModel.sport) {
                if (filterModel.sport.indexOf(item.sport) < 0) {
                    // year didn't match, so skip this record
                    continue;
                }
            }

            resultOfFilter.push(item);
        }

        return resultOfFilter;
    }
});

**Comment by buremba** [comment]
+1. I expected `newRowsAction: 'keep' `to store all the unique values for that column and show in filter menu but it turns out that we still need to provide `values` parameter in order to get the desired behaviour. The client side problem seems to be fixed but the server-side filtering and sorting causes filter menu to show only selected items. When we unselect an item from the list, it's removed by ag-grid so that there's no way to select it again. See: https://jsfiddle.net/43x8mavj/ country column.

**Comment by tannerlinsley** [comment]
@ceolter It would be nice if we didn't have to go through all of that ^^^ just to get pagination for data that is already in memory.  Say you don't want your users to get scroll-trapped by a huge table, you go from 30 lines of code to 300+ almost instantly.  Is there a more succinct way of doing this instead of faking out ag-grid? It seems we should be able to ditch the `dataSource` if we have the data on hand.

**Comment by ceolter** [comment]
yes if you have all the data, then i agree, should just give all the data to the grid and let the grid sort it out. it's on my todo list.

**Comment by derekperkins** [comment]
@ceolter: Any idea on the timeline?

**Comment by ceolter** [comment]
sorry, can't commit. i'm full up getting the following two features in a) bid data view and b) enhanced editing.

**Comment by malreynolds** [comment]
@ceolter, any updates on this? Thanks!

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-91

**Comment by PTC-JoshuaMatthews** [comment]
Just want to add that my company is looking at purchasing the enterprise version, but this feature is holding me back for now. Would love to see this implemented.

**Comment by PTC-JoshuaMatthews** [comment]
Another idea that would make the workaround posted above easier to live with, but I'm not sure if possible, would be if there is a way to access the grid's internal filtering functionality through the api. If I could pass the entire dataset to the grid api along with a flterModel and sortModel and get back a filtered and sorted list that I can then page on, that would prevent needing to create a custom sort and filter function. Especially since the one in the example doesn't implement advanced filter functionality available when using the column data type.

**Comment by seanlandsman** [comment]
@PTC-JoshuaMatthews - you can track the progress on the pipeline page: https://www.ag-grid.com/ag-grid-pipeline/

**Comment by seanlandsman** [comment]
@PTC-JoshuaMatthews - it might help us prioritise this issue knowing this. I suggest you contact accounts@ag-grid.com in the first instance - from there the team can evaluate the issue and prioritise it accordingly. Hope this helps

**Comment by PTC-JoshuaMatthews** [comment]
@seanlandsman  Thanks I will let them know!

**Comment by jrmoser** [comment]
In case someone lands here again looking for an alternate solution, here is one that uses the Master/Slave option and the sorting/filtering inherent in the grid [jsfiddle](https://jsfiddle.net/aw9gxyn6/2/)

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by anupswarnkar** [comment]
@makinggoodsoftware was this feature added?
