### ISSUE TITLE
(bug) groupRows - filter an entire group don't maintain groupOrder.

### ISSUE THREAD

**Issue by eckelarsson** [ag-grid/ag-grid#5870]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Grouping rows with the displayType: 'groupRows' and with an initialGroupOrderComparator with the options
```
groupDisplayType: 'groupRows'
groupMaintainOrder: true,
groupSelectsChildren: true,
```

**Current behavior**
When you filter the Grouped row field, showing and then hiding, then showing it again the order is not maintained.

https://user-images.githubusercontent.com/2752093/206920158-b5d8d912-9bb5-4088-806f-7167cec10e98.mov

**Expected behavior**
The order of the grouped rows are maintained.

* **AG Grid version:** 28.2.1

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

* **Language:** [Vue]

**Comment by StephenCooper** [comment]
Could you please provide a reproduction that shows this behaviour in action as it seems like our examples show this working. Maybe extend this plunker to show your issue?

https://plnkr.co/edit/TBR8aNPMSkfNeUEO?open=main.js
