### ISSUE TITLE
drag will occasionally bug in ag-grid-vue

### ISSUE THREAD

**Issue by HFitchenjie** [ag-grid/ag-grid#5871]
![489c194412ea5520810d866a7211a4a](https://user-images.githubusercontent.com/52654879/206968918-abb5a86f-0749-4702-96fc-c44dd941ec5f.png)

![image](https://user-images.githubusercontent.com/52654879/206969321-4c024bba-9dec-4e48-bd1c-936aa0a91135.png)
![image](https://user-images.githubusercontent.com/52654879/206969388-a39835b4-4b28-4fb3-a7c7-9c054f989ce8.png)

Using the drag-and-drop function of ag-grid-vue in vue has the probability that the rowDragEnter event will fire twice,Above is the output of my log

**Comment by StephenCooper** [comment]
Hi @HFitchenjie,

Could you please provide a reproduction with steps on how you make it appear twice? Without this we are not going to be able to investigate this issue for you.
