### ISSUE TITLE
Grid freezing onResize when having 2 autoHeight columns with cellRenderers

### ISSUE THREAD

**Issue by asoov** [ag-grid/ag-grid#5873]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello, 

within a Vue application I have a Grid with 2 columns using autoHeight. These 2 columns each are using CellRenderers to display their content. When I'm resizing the columns back and forth and height gets recalculated this often leads to a total browser freeze and crashing the application. Is this expected and due to the performance issues when using autoHeight columns which are implied in the documentation? Or am I missing something as the autoHeight calculation seems to work just fine in the docs (although not with using CellRenderers).

Thanks in advance!

**Comment by StephenCooper** [comment]
Hi @asoov,

We would need a reproducible example to investigate this further. As you say it may be linked to cell renderers in the columns. If you could provided a plunker that shows this happening that would be very helpful.

**Comment by asoov** [comment]
I just tried to do so but wasn't able to make it work as neither Plunkr nor Codesandbox provide a working Vue + Typescript template :(

**Comment by StephenCooper** [comment]
The bug should still happen without Typescript if there is an underlying issue.

**Comment by asoov** [comment]
Also I noticed it's unfortunately not possible to show this without exposing meaningful parts of this application that is for a private client of mine. I'll check if I can think of a way to show a reproduction.
