### ISSUE TITLE
react ui is different from the official

### ISSUE THREAD

**Issue by hyzhen** [ag-grid/ag-grid#5880]
![Dec-14-2022 11-03-01](https://user-images.githubusercontent.com/9149187/207495192-1743a6a5-d2f2-40cc-a9dd-c34f829b6b52.gif)
![image](https://user-images.githubusercontent.com/9149187/207495261-7590f1fb-f890-4b58-93c4-f87119486a84.png)
![image](https://user-images.githubusercontent.com/9149187/207495294-c6aaea5b-6359-4610-aa05-848ff5986c53.png)
![image](https://user-images.githubusercontent.com/9149187/207495321-c5de885c-772f-426c-bcfb-7b376db1c77d.png)
[ag demo](https://www.ag-grid.com/react-data-grid/reactui/):
![image](https://user-images.githubusercontent.com/9149187/207495949-7099d9fa-9ed6-48e3-9f58-04bcecaf1972.png)
We use the same code and the latest version as the official, but we still can't achieve the official effect, please help us to check if I am using it correctly

**Comment by gportela85** [comment]
@hyzhen There is a difference in performance between the dev build and production build in React. Can you try generating a production build? 
Check the docs section here: https://www.ag-grid.com/react-data-grid/scrolling-performance/#react-dev-vs-prod-mode

**Comment by hyzhen** [comment]
@gportela85 Thank you, I upgraded react and tested it in production mode, it is exactly the same.
