### ISSUE TITLE
Column Visibility change with groupId crashes AG Grid (React)

### ISSUE THREAD

**Issue by PointSingularity** [ag-grid/ag-grid#5883]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Reproduction [Plnkr](https://plnkr.co/edit/vpAkRSWYx582dGyu?open=index.tsx&preview)

**Current behavior**
If a groupId is supplied, changing column visibility crashes the app.

Click on the toggle visibility, and it crashes, but if you comment out the line 28, and it works.

**Expected behavior**
Clicking on the button toggles the column visibility.

Some additional info:
I stumbled upon this when upgrading from version 28.1.1
I had a problem in that version, that every time the row data was changed, the group headers would flicker.
This was fixed in the current version, but the fix required giving each header an groupId.

The issue number for the fix is AG-7247.
![image](https://user-images.githubusercontent.com/56246797/207652440-bd391218-d69c-4208-be68-ba8bf49f2a5d.png)

The toggle with groupId works in version 28.1.1, but the flicker is present.

**Environment:**

* **AG Grid version:** 28.2.1

* **Browser:** Chrome - 108.0.0.0

* **React version:** 18.2.0

* **Language:** TS 4.9.3

**Comment by StephenCooper** [comment]
This issue has already been fixed in our latest nightly build and so the fix will be released as part of our next release v29. This is roughly scheduled for the start of next year.

**Comment by PointSingularity** [comment]
> This issue has already been fixed in our latest nightly build and so the fix will be released as part of our next release v29. This is roughly scheduled for the start of next year.

@StephenCooper That is great to hear, thank you!
