### ISSUE TITLE
cellRenderer  could not be updated  When I used  applyTransactionAsync

### ISSUE THREAD

**Issue by haomashroom** [ag-grid/ag-grid#5887]
First of all, thanks for checking out my question.
When I used  applyTransactionAsync  to update the data, I found that the contents of the custom render cellRenderer  could not be updated.
Please help solve it, thank you

* **Browser:**
Chrome

* **Language:**  TypeScript

**Comment by StephenCooper** [comment]
Please provide a reproduction so that we can investigate this further. It is hard for us to fully understand or provide a solution without an example of the behaviour you describe.

**Comment by haomashroom** [comment]
> 
Thanks, I have solved it, by using valueGetter in conjunction with the way.
