### ISSUE TITLE
paginationGoToPage not working with Server-Side Row Model / url query parameters

### ISSUE THREAD

**Issue by TrentHurlbut** [ag-grid/ag-grid#5891]
<!--
IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
We are trying to instruct our grid to go to a particular page of data through url params. We have managed to work out filtering and sorting, but pagination is still eluding us. Here is the block of code that provides the grid with instructions based on the query parameters (`initialParams`) fed to it by the url:

```
useEffect(() => {
    if (gridRef?.current.api) {
      gridRef.current.api.setServerSideDatasource(datasource)
    }
  }, [gridRef, datasource, watchedValues])

  const onGridReady = event => {
    const { api, columnApi } = event

    api.setServerSideDatasource(datasource)

    if (initialParams && initialParams.filterModel) {
      api.setFilterModel(initialParams.filterModel)
    }

    if (initialParams && initialParams.sortModel) {
      columnApi.applyColumnState({
        state: initialParams.sortModel,
        defaultState: { sort: null },
      })
    }

    if (initialParams && initialParams.startRow) {
      api.paginationGoToPage(Math.floor(initialParams.startRow / 50))
    }

    if (sizeToFit) {
      api.sizeColumnsToFit()
    }
  }
```

The current behavior is that nothing happens when `paginationGoToPage` is called. We've ensured that the function is being hit, but the grid remains on page one even when we have used hardcoded values as arguments.

**Expected behavior**
Expected behavior would be that the grid, onReady, would go to the page we're asking it to via `paginationGoToPage`.

* **AG Grid version:** X.X.X
28.2.0

* **Browser:**
Chrome

* **Language:**
Javascript

**Comment by TrentHurlbut** [comment]
Not sure my issue was saved:



**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**


**Expected behavior**


**Please tell us about your environment:**


* **AG Grid version:** X.X.X


* **Browser:**


* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by TrentHurlbut** [comment]
Not sure why the body of my issue didn't save...

**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

 am currently working on implementing Ag-Grid in React such that it is able to take in query parameters from a URL string and spit out specified filtering, sorting, and pagination behavior. Here is the code that takes in the query parameters and instructs Ag-Grid to display data based on those params:
```
useEffect(() => {
    if (gridRef?.current.api) {
      gridRef.current.api.setServerSideDatasource(datasource)
    }
  }, [gridRef, datasource, watchedValues])

  const onGridReady = event => {
    const { api, columnApi } = event

    api.setServerSideDatasource(datasource)

    if (initialParams && initialParams.filterModel) {
      api.setFilterModel(initialParams.filterModel)
    }

    if (initialParams && initialParams.sortModel) {
      columnApi.applyColumnState({
        state: initialParams.sortModel,
        defaultState: { sort: null },
      })
    }

    if (initialParams && initialParams.startRow) {
      api.paginationGoToPage(Math.floor(initialParams.startRow / 50))
    }

    if (sizeToFit) {
      api.sizeColumnsToFit()
    }
  }

```
Everything in this code block works beautifully EXCEPT for api.paginationGoToPage. We've even tried hardcoding values in just to see if we could make it go to ANY page, but to no avail. The rest of the api functions are working, why is this one not doing anything?

As mentioned above, we tried hardcoding values into the function just to see if we could get it to do anything. I have tried moving pagination handling into the server-side datasource function, but what ends up happening is that the grid will display the page we want, but the pagination will still show that we are at page one (and will be stuck on that page of data since we're using url params, which are not changing, to dictate what page we are on). The grid definitely seems to need to be instructed to go to a particular page if it is to sync up with its own pagination, but the method used to do that is simply not doing anything.

**Current behavior**
`paginationGoToPage` is being hit, but no change in the grid.

**Expected behavior**
I would expect the grid to go to the page we're feeding it via `paginationGoToPage`

* **AG Grid version:** X.X.X
28.2.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* Javascript/React

**Comment by StephenCooper** [comment]
Are you returning the `rowCount` property as part of your success callback?

https://ag-grid.com/react-data-grid/server-side-model-datasource/#success-callback

>The rowCount is also used when [Pagination](https://ag-grid.com/javascript-data-grid/server-side-model-pagination/) is enabled. The row count is used to determine the number of pages that are required and enables the grid to jump to the last page. If not provided users will only be able to step to the next page as the grid does not know how many pages are required.

**Comment by TrentHurlbut** [comment]
We are!

```
getterFunction(params.request)
          .then(response => {
            console.log(response)
            params.successCallback(
              response.data.rows,
              response.data.meta.rows_count
            )
          })
          .catch(error => {
            console.error(error)
            params.failCallback()
          })
```

Our api sends back the `rows_count` in a meta attribute alongside the data.

**Comment by StephenCooper** [comment]
You are using a deprecated method. Please try with the `success` callback which returns an object.

https://ag-grid.com/react-data-grid/server-side-model-datasource/#reference-IServerSideGetRowsParams-success
```
interface LoadSuccessParams {
  // Data retrieved from the server as requested by the grid. 
  rowData: any[];
  // The last row, if known, to help Infinite Scroll. 
  rowCount?: number;
  // Any extra information for the grid to associate with this load. 
  groupLevelInfo?: any;
}
```

**Comment by TrentHurlbut** [comment]
Ahhh... that makes sense. I really appreciate you pointing this out!

Forgive me, but I'm pretty new to this: How would this look in our current code? I'm not sure how to interact with the LoadSuccessParams interface. 😅

**Comment by TrentHurlbut** [comment]
Actually, sorry, ignore that. I just found an example in the docs (go figure).

**Comment by StephenCooper** [comment]
I have done a rough test and this feature seems to be working ok in our latest.

https://plnkr.co/edit/TCYisRR6VUAqjtOv?open=index.tsx

**Comment by TrentHurlbut** [comment]
Hmmm... I tried with `LoadSuccessParams` implemented, and it is still not going to a different page.

Here is our `onGridReady` code:

```
useEffect(() => {
    if (gridRef?.current.api) {
      gridRef.current.api.setServerSideDatasource(datasource)
    }
  }, [gridRef, datasource, watchedValues])

  const onGridReady = event => {
    const { api, columnApi } = event

    api.setServerSideDatasource(datasource)

    if (initialParams && initialParams.filterModel) {
      api.setFilterModel(initialParams.filterModel)
    }

    if (initialParams && initialParams.sortModel) {
      columnApi.applyColumnState({
        state: initialParams.sortModel,
        defaultState: { sort: null },
      })
    }

    if (initialParams && initialParams.startRow) {
      console.log("firing")
      api.paginationGoToPage(Math.floor(initialParams.startRow / 50))
    }

    if (sizeToFit) {
      api.sizeColumnsToFit()
    }
  }
```

I noticed you used a timeout for `paginationGoToPage`, is that maybe the issue?

**Comment by StephenCooper** [comment]
Potentially. Would need to ensure your data has loaded before trying to move the a different page.

**Comment by TrentHurlbut** [comment]
That was it! Thank you so much for your help!

One last question: do you know of a more elegant way to handle this rather than a timeout? Can you `await` `datasource` or something like that?

**Comment by StephenCooper** [comment]
This event might be what you are looking for.
https://www.ag-grid.com/javascript-data-grid/grid-events/#reference-miscellaneous-firstDataRendered
