### ISSUE TITLE
Error when importing Enterprise package

### ISSUE THREAD

**Issue by pxmal** [ag-grid/ag-grid#5892]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Using React 17 with Ag-grid version 28.2.0 for all 3 packages cause the following error, when importing the enterprise version:
Uncaught TypeError: Cannot read properties of undefined (reading 'concat’) at ag-grid-enterprise.auto.esm.js:65738:38

Removing the import statement of the enterprise package everything works as expected.

* **AG Grid version:** X.X.X

28.2.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React 17, TypeScript 4.7.4

**Comment by pxmal** [comment]
Error appears in all 28.+ versions. Does not appear in 27.+ versions.

**Comment by StephenCooper** [comment]
Can you provide a reproduction or at least the code where you are importing enterprise?

**Comment by pxmal** [comment]
import * as React from "react";
import {useState} from "react";
import 'ag-grid-enterprise';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import {AgGridReact} from "ag-grid-react";


const ReportPage = () => {

    const [rowData] = useState([
        {make: "Toyota", model: "Celica", price: 35000},
        {make: "Ford", model: "Mondeo", price: 32000},
        {make: "Porsche", model: "Boxster", price: 72000}
    ]);

    const [columnDefs] = useState([
        {field: 'make'},
        {field: 'model'},
        {field: 'price'}
    ])

    return (
        <div className="ag-theme-alpine" style={{height: 400, width: 600}}>
            <AgGridReact
                rowData={rowData}
                columnDefs={columnDefs}>
            </AgGridReact>
        </div>
    );


};

export default () => <ReportPage/>;

**Comment by pxmal** [comment]
Apologies for the formatting, not sure why it wont accept it

**Comment by StephenCooper** [comment]
Ok that all looks correct. 

We would need a reproduction of the error in a project that we can run to investigate this issue. Could you please provide one?

**Comment by pxmal** [comment]
I created a create-react-app project, and using the same react version 17 I actually don't experience the problem.
It could be related to esbuild on our project or something else. I will investigate further. Thank you

**Comment by jeffmbreis** [comment]
Solved adding this config on next.config.js

transpilePackages: [
    "ag-grid-enterprise",
    "ag-grid-community",
    "ag-grid-react",
  ],

**Comment by augustl** [comment]
The `transpilePackages` solved it for me! However, I also had to downgrade to `31.1.1 `, as the latest version (`31.3.1`) breaks with a compile error due to a mismatch where types between ag-grid-enterprise and ag-grid-community are incompatible

**Comment by Lovely-Ruby** [comment]
i also meet this question  in my vue2 project, my version is 

```javascript
"ag-grid-charts-enterprise": "^31.3.4",
"ag-grid-community": "^31.3.4",
"ag-grid-enterprise": "^31.3.4",
"ag-grid-vue": "^31.3.4",
```

![image](https://github.com/user-attachments/assets/14a46bf2-d957-40ba-9d6f-4e149db43b4b)


![image](https://github.com/user-attachments/assets/1880186b-c18d-4600-9ec2-4e9bbe3aa430)

**Comment by Lovely-Ruby** [comment]
i solve it
in vue.config.js, add this
```javascript
// vue.config.js
module.exports = {
  transpileDependencies: [
    "ag-grid-enterprise",
  ],
}
```
and change  babel config because when i run `npm run dev`, my project stop in there 
```
npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme 
```
that is babel things

```
// babel.config.js
  presets: [['@vue/app', { compact: false }]],
```

i also updown version to 
```
// package.json
"ag-grid-community": "^31.1.1",
"ag-grid-enterprise": "^31.1.1",
```

![image](https://github.com/user-attachments/assets/5a9f7864-5b86-43cb-afae-b4ce5f64979c)
