### ISSUE TITLE
Filter state not being maintained when column values switch back and forth

### ISSUE THREAD

**Issue by joao-vicente** [ag-grid/ag-grid#5894]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- [Example page](https://www.ag-grid.com/examples/filter-set-filter-list/refreshing-values/modules/angular/index.html)

Steps to reproduce:

1.  On the "Filters" right sidebar, under the "values Array" uncheck "Select all"
2. On the same place, check the "Lion" value
3. Click on the button "Use ['Elephant', 'Giraffe', 'Tiger']"
4. Click on the button "Use ['Elephant', 'Lion', 'Monkey']"

**Current behavior**

In the beginning, no filters are applied, so no filter icon is shown and all rows are visible with the default **['Elephant', 'Lion', 'Monkey']** data being used. When selecting only the "Lion" value to filter, the table displayed only the rows with "Lion". When clicking on the button "Use ['Elephant', 'Giraffe', 'Tiger']", since there's no "Lion" value, nothing is shown on the table or in the filters. Going back to the previous data set by clicking on the button "Use ['Elephant', 'Lion', 'Monkey']", nothing is shown on the table or in the filters and the filter icon is displayed.

**Expected behavior**

When doing step 4, since the dataset contains the previously selected filter "Lion" it should maintain the state and show the correct data on the table as well as select the "Lion" value on the filters.

**Environment:**

* **AG Grid version:** 28.1.1

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

* **Language:** TypeScript 4.7.4

**Comment by StephenCooper** [comment]
Hi @joao-vicente,

This is the expected behaviour as stated on our [docs](https://ag-grid.com/angular-data-grid/filter-set-filter-list/#refreshing-values).

> When you refresh the values, any values that were selected in the filter that still exist in the new values will stay selected, but any other selected values will be discarded.

If you wanted to maintain values that were selected you can achieve this through managing the filter state as part of your application. If you wanted help with that then feel free to use your Enterprise license to request support.
