### ISSUE TITLE
Ag-grid printing issue

### ISSUE THREAD

**Issue by kantmusk** [ag-grid/ag-grid#5899]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Hello! when printing a table, rows overlap each other.

**Current behavior**

![3ef86fa47f](https://user-images.githubusercontent.com/95129629/208232502-d3a8287f-c1bc-468a-a951-116c07ef44b6.jpg)

**Expected behavior**
Rows must not overlap

**Please tell us about your environment:**
Windows

* **AG Grid version:** X.X.X
"@ag-grid-community/client-side-row-model": "^28.1.1",
    "@ag-grid-community/core": "^28.1.1",
    "@ag-grid-community/csv-export": "^28.1.1",
    "@ag-grid-community/react": "^28.1.1",
    "@ag-grid-enterprise/clipboard": "^28.1.1",
    "@ag-grid-enterprise/column-tool-panel": "^28.1.1",
    "@ag-grid-enterprise/core": "^28.1.1",
    "@ag-grid-enterprise/excel-export": "^28.1.1",
    "@ag-grid-enterprise/filter-tool-panel": "^28.1.1",
    "@ag-grid-enterprise/master-detail": "^28.1.1",
    "@ag-grid-enterprise/menu": "^28.1.1",
    "@ag-grid-enterprise/range-selection": "^28.1.1",
    "@ag-grid-enterprise/row-grouping": "^28.1.1",
    "@ag-grid-enterprise/server-side-row-model": "^28.1.1",
    "@ag-grid-enterprise/set-filter": "^28.1.1",
    "@ag-grid-enterprise/side-bar": "^28.1.1",

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all | TypeScript X.X | ES6/7 | ES5

**Comment by StephenCooper** [comment]
Hi @kantmusk,

Can you please provide a reproduction of this issue so that we can then investigate this further?
