### ISSUE TITLE
Infinite scroll and Text wrap

### ISSUE THREAD

**Issue by amal-k-dev** [ag-grid/ag-grid#5902]
Hi!

I am using Ag-Grid community(Angular) with an infinite scroll row-model. I am trying to wrap text but not working.  There was a ticket 2 years before but it was closed and marked as 'wontwork'. Is there any fix or any workaround?. Can someone provide any information on this?

NB: I am not using any cell renderer.

Thanks
Amal K Dev

**Comment by StephenCooper** [comment]
Hi @amal-k-dev,

This is not a supported feature for infinite scroll row-model unfortunately. For reference this does work with Server Side Row Model as this example shows but this is part of our Enterprise offering which I assume is not so helpful for your use case.

https://plnkr.co/edit/lLJEUTxqCGH1zoY5?open=index.tsx
