### ISSUE TITLE
Cursor based pagination

### ISSUE THREAD

**Issue by domcoleman** [ag-grid/ag-grid#5903]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I'm currently evaluating the enterprise version for our use case, but I'm having trouble with using cursor based pagination.

I've got it working initially, by setting the grid context to a map, and getting cursors from that map when requested:
```typescript
  async (params: IServerSideGetRowsParams) => {
    const ctx = params.context as Map<string, string>;
    const blockSize = 100;
    const startRow = Math.max(params.request.startRow! - blockSize, 0);
    const endRow = startRow + blockSize;
    const prevPage = { ...params.request, startRow, endRow };
    const cursor = ctx.get(JSON.stringify(prevPage));

    const body = removeUndefined({
      ...otherParams,
      pagination: {
        pageSize: blockSize,
        pageToken: cursor,
      },
    });

    const res = await fetch("/api/dataset/query", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    }).then((r) => r.json());
    if ("error" in res) return params.fail();

    const totalRecords = res.pagination.totalRecords;
    const rowCount =
      totalRecords <= (params.request.endRow ?? 0) ? totalRecords : undefined;

    const key = JSON.stringify(params.request);
    ctx.set(key, res.pagination?.pageToken ?? "");

    params.success({ rowData: res.records, rowCount });
  };
```

I'm then resetting pagination whenever sort or filters are changed:
```typescript
export const gridOptions: GridOptions = {
  ...otherSettings
  onSortChanged: ({ api }) => {
    api.paginationGoToFirstPage();
    api.ensureIndexVisible(0, "top");
  },
  onFilterChanged: ({ api }) => {
    api.paginationGoToFirstPage();
    api.ensureIndexVisible(0, "top");
  },
};
```

Everything works here, and any initial page requests will only load after the previous page has loaded, as AG Grid doesn't know the total number of rows.
Once a page has been navigated to, if sort or filter options are changed AG Grid still knows there could be that many rows, so will allow the user to request them. As there is no cursor in the context for that requested page if navigated to too quickly it will request the first page, so my solution is no longer working.

Is there a way of purging the total known rows count `onSortChanged` or `onFilterChanged`, or another way of implementing cursor based pagination I'm not seeing?

**Comment by StephenCooper** [comment]
Hi @domcoleman,

I am afraid its not 100% clear what you are trying to achieve here without an example. Can you reproduce this in an example using this example as a template? https://plnkr.co/edit/CpswN6U91SEumbLA?open=main.ts

That would help us understand if there is an issue or alternative way of achieving your aim.

**Comment by domcoleman** [comment]
Hi @StephenCooper,

I've reproduced an example here: https://plnkr.co/edit/L7CXu8Y84a5DlojT?open=index.tsx
This is a very crude example of cursor based pagination, which is often used in GraphQL APIs, as well as products like Google BigQuery. The `cursor`s from the actual API will differ from the ones I've set in `fakeServer.js`, it's usually a base64 encoded string.

As I said in my first post pagination works fine when initially going to a page, but if you through a few pages, apply a sort, and then try to skip forward to the page you were on, you'll be able to but the results will be the same as the first page as there's no `cursor` available for the page requested yet.

**Comment by AndrewGlazier** [comment]
Hi @domcoleman,

We tend to advise that for cursor based pagination our viewport row model (https://ag-grid.com/react-data-grid/viewport/) makes more sense, as you can create your own cursor pagination wrapper around the basic functionality. There's less out of the box behaviour, however it gives a greater amount of control.

If however you're set on making the SSRM work with this behaviour, I'd suggest instead of ensuring index and paginating to the first page, to use `api.setDatasource(datasource)` as this will reset the SSRM back to its initial state, with only 1 placeholder loading row.

**Comment by PeturSteinn** [comment]
@AndrewGlazier can we get official docs on how to implement cursor based pagination? I'm using GraphQL relay (which uses cursor based pagination) and I'm not entirely sure how to hook it all up.

**Comment by nbran** [comment]
Commenting to emphasize support for this feature.
