### ISSUE TITLE
Row Drag and Drop is not working with tree data

### ISSUE THREAD

**Issue by yashwanth2714** [ag-grid/ag-grid#5907]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
When we try to swap documents and music in the below example, music is being moved into documents. They are supposed to reorder.

https://www.ag-grid.com/vue-data-grid/row-dragging/#example-dragging-with-tree-data

**Expected behavior**
You can reorder parent nodes.

**Please let us know if we are missing anything.**

**Comment by StephenCooper** [comment]
The example you linked does not have code to support changing the order. This would need to be added to support changing the order of items.

This would be part of your application logic to decide what should be done when a row is dropped. 

As there is no grid issue here I am going to close the ticket.
