### ISSUE TITLE
[virtual paging] Export as CSV when using Virtualisation

### ISSUE THREAD

**Issue by jogibear9988** [ag-grid/ag-grid#591]
This should be supported!

**Comment by ceolter** [comment]
this would end up with calling the server for the entire set of data, as you don't have the data to hand, right?

maybe the datasource would need a 'get all data' method, rather than pulling back a page at a time.

**Comment by jogibear9988** [comment]
yes, but it could be less then the whole data when it's filtered!

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-94

**Comment by pscanlon1** [comment]
Is there a workaround for this currently?

**Comment by Vahanhakobyan85** [comment]
Can't you just in case of virtual paging (infinite scrolling) export only the part of data that is available on the grid (omitting the part which remained on the server)?

**Comment by pscanlon1** [comment]
No, I wrote a plugin for exporting that can modify the page size of a request, creates a new regular grid, and then calls the export() function. I dont see a point to exporting the visible area for an infinite grid, because the whole point of the infinite grid is to appear as though you are viewing a ton of data.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by pscanlon1** [comment]
what's the number in the pipeline???
