### ISSUE TITLE
HeaderComponent could not be updated When I used custom header

### ISSUE THREAD

**Issue by haomashroom** [ag-grid/ag-grid#5913]
First of all, thanks for checking out my question.
When I use HeaderComponent render table header, there is a button that can modify the table header data, but I find that the table header is not refreshed, and the table header is not updated with headerComponentParams  passable parameter.
Please help solve it, thank you
![image](https://user-images.githubusercontent.com/14905047/208640585-9a9ee4b8-69ca-44f8-8f31-61123d5a554f.png)

Browser:
Chrome

Language: React && TypeScript

**Comment by StephenCooper** [comment]
Can you please provide a reproduction of your issue to help us investigate this for you?
