### ISSUE TITLE
Ag-charts canvas zoom bug

### ISSUE THREAD

**Issue by Wlidar** [ag-grid/ag-grid#5935]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'
```

I would like to comment on my problem in case someone has an idea of what it is due to or proposes an alternative solution.

Currently I have a large ag-charts graph that does not fit and it is always necessary to scroll to be able to see it in its entirety but when scrolling the axes are not maintained, so I resorted to the alternative of cloning the graph canvas twice to generate 2 new canvas clipped with "position:fixed" so that they always stay at the ends.

So far there is no problem except that if the browser zoom and/or the windows scale differs from 100%, it affects the cropping of said canvas in an inconsistent way. I was not able to get a rule of 3 to apply the correct zoom multiplier ( with ctx.drawImage() ) due to its inconsistency.

It should work with zoom like it does when the zoom level is 100%.

The error stops happening when you test it with a normal canvas that has not been generated by ag-charts

Here I have a very simple [Live Demo](https://plnkr.co/edit/z4RBcm7uatdRm83v) to test it.
PD: To reproduce the bug you need to have the zoom applied before the generation of the graph.

Environment: 
Windows, all browsers, ag-grid ^6.2.1, typescript ^3.7.7

**Comment by StephenCooper** [comment]
Hi @Wlidar,

We would suggest using the Navigator feature as that will enable the user to scroll the chart and have everything rendered correctly. https://ag-grid.com/angular-charts/navigator/

I think this is your best option and cleanest solution.
