### ISSUE TITLE
Ag-Grid is not reactive/does not trigger computed fields to re-evaluate

### ISSUE THREAD

**Issue by caveofjulian** [ag-grid/ag-grid#5938]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://codesandbox.io/s/6hrrjp
Here I have created an example with a checkbox cell renderer. Please note my comment there. I have a version that works (updating it through the store, not changing the array itself but merely the property of the item inside the array) and a version that doesn't work which is done by Ag-Grid (setDataNode seems broken).
Just replacing it by my comment will work. Please do note that setDataNode does change the value! If you look in the VueX Pluging you can clearly see it's updated, it just does not trigger the button to be disabled (if any is exchanged it will be enabled). The computed field does not retrigger using Ag-Grid's setDataNode.

**Expected behavior**
Retrigger computed field

**Please tell us about your environment:**
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 5.80 GB / 27.86 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vue: 3.2.45 => 3.2.45

* **AG Grid version:** X.X.X
Yes this only happens when upgrading! Might be a combi of upgrading Vue and Ag-Grid.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
JS

**Comment by StephenCooper** [comment]
I have taken a quick look at your sandbox and I think you need to update your mutation logic to provide a new reference to the row data and not just update them in place. 

When updating a cloned copy of the rows and making the update to that, and then providing that new reference back to the state the rows are re-triggered.

https://codesandbox.io/s/vuex-demo-vue-3-forked-53lj6q
