### ISSUE TITLE
AG-Grid Sparkline rendering bug 

### ISSUE THREAD

**Issue by geonyoon2** [ag-grid/ag-grid#5939]
**Current behavior**

```
When using Progress Bars in `agSparklineCellRenderer`  

1. When quickly lowering the mouse wheel within the grid
2. When operating the browser's zoom function quickly ( ctrl + mouse wheel)
```

**Expected behavior**

```
the graph renders strangely. The graph has two lines or is blank in the middle.
The expected behavior can also be seen in the link below.
```
## Ag-grid Example
https://www.ag-grid.com/react-data-grid/sparklines-bar-customisation/#example-bar-sparkline-progress-bars

## plnkr ( extend data )
https://plnkr.co/edit/vVWoFKyPghGZt7hw?open=index.jsx&preview

# 1.
![image](https://user-images.githubusercontent.com/69180520/210291416-1b37f730-fe15-42a0-b277-35c61bdcfc85.png)

# 2.
![image](https://user-images.githubusercontent.com/69180520/210291522-60b8716b-507f-4bd1-90df-c8c70dd75b53.png)

**Please tell us about your environment:**

* **AG Grid version:** 28.2.1 (Enterprise)

* **Browser:** **Chrome** 

* **Language:** [JS, ES6/7, React]

**Comment by StephenCooper** [comment]
Closing here as I see you have also raised a ticket via support. Please only raise via Zendesk to avoid us duplicating work.

**Comment by irwincollin** [comment]
Was there an official fix for this, or what came of this?
Just wondering as we ran into a similar problem, and we did find a workaround by tweaking the sizes of the bars.

**Comment by irwincollin** [comment]
We are on v28. I assume it is resolved then, but will open a new ticket if we run into it in v29 somehow. Thanks!!
