### ISSUE TITLE
[AG Charts - Vue3] Grouped property in Scatter series is not working

### ISSUE THREAD

**Issue by DivakarSS** [ag-grid/ag-grid#5944]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
* Project migration from Vue2 to Vue3.
**Current behavior**
We are getting the warnings like "AG Charts - unable to set [series[4].grouped] in [ScatterSeries]; nested error is: AG Charts - grouped: true is unsupported for series of type: scatter" when setting grouped property as true in scatter series in our Vue 3 project.

It is supported in ag-charts-vue for vue 2.
https://www.ag-grid.com/archive/25.0.0/documentation/javascript/charts-api/

**Expected behavior**
There should not be any warnings and grouped property must be accepted as true by scatter series.
 
**Please tell us about your environment:**
O.S: Windows 10
IDE: VS Code
Package Manager: npm
* **AG Grid version:** 28.2.1
* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'
* Vue: 3.2.13
* ag-grid-vue3: 28.2.1
* ag-charts-vue3: 6.2.1
* ag-charts-community: 6.2.1
* TypeScript: 4.5.5

**Comment by StephenCooper** [comment]
The `grouped` property is for Bar and Column Series and is not a valid option for Scatter series. It is likely that in upgrading you are getting better option validation which is now highlighting existing incorrect configuration. 

https://www.ag-grid.com/javascript-charts/bar-series/#bar-series

I am going to close this ticket as I believe there is no issue with AG Grid here. If you disagree then please provide a reproduction that shows this error for us to investigate.
