### ISSUE TITLE
ag-grid throwing warnings: State updates from the useState() and useReducer()

### ISSUE THREAD

**Issue by STEjovanovicFAN** [ag-grid/ag-grid#5966]
**I'm submitting a issue with ag-grid throwing state update warnings.**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Company I'm working for is a customer of AG Grid. Also requesting community support. Any and all help is appreciated.

**Current behavior**

Currently ag-grid is console.log'ing this state warning error in every grid in the application.

Here is the dump of some of the warnings thrown into the console logs:

Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().
    in GridComp (created by AgGridReactUi)
    in div (created by AgGridReactUi)
    in AgGridReactUi (created by AgGridReact)
    in AgGridReact (created by Grid)
    in div (created by Grid)
    in div (created by Spinner)
    in Spinner (created by Grid)
    in Grid (created by PortfolioGrid)
    in PortfolioGrid (created by InjectIntl(PortfolioGrid))
    in InjectIntl(PortfolioGrid) (created by Portfolios)
    in div (created by CardBody)
    in CardBody (created by Portfolios)
    in div (created by Card)
    in Card (created by Portfolios)
    in div (created by Portfolios)
    in div (created by Body)
    in Body (created by Portfolios)
    in div (created by Spinner)
    in Spinner (created by Pane)
    in Pane (created by Portfolios)
    in div (created by Body)
    in Body (created by Portfolios)
    in div (created by PageView)
    in PageView (created by Portfolios)
    in Portfolios (created by Context.Consumer)
    in Connect(Portfolios) (created by Context.Consumer)
    in ErrorBoundary (created by Context.Consumer)
    in Route (created by SecuredRoute)
    in SecuredRoute (created by PortfolioApplicationRoutes)
    in Switch (created by PortfolioApplicationRoutes)
    in PortfolioApplicationRoutes (created by PortfolioApplicationLayout)
    in div (created by Spinner)
    in Spinner (created by PortfolioApplicationLayout)
    in div (created by Layout)
    in Layout (created by PortfolioApplicationLayout)
    in PortfolioApplicationLayout (created by InjectIntl(PortfolioApplicationLayout))
    in InjectIntl(PortfolioApplicationLayout) (created by Context.Consumer)
    in Connect(InjectIntl(PortfolioApplicationLayout)) (created by Context.Consumer)
    in Route
    in Authentication (created by Context.Consumer)
    in Connect(Authentication) (created by Context.Consumer)
    in withRouter(Connect(Authentication))
    in Router
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Context.Consumer)
    in Connect(ConnectedRouterWithContext)
    in ServerStatus (created by Context.Consumer)
    in Connect(ServerStatus)
    in Provider
    in GlobalIntlProvider (created by InjectIntl(GlobalIntlProvider))
    in InjectIntl(GlobalIntlProvider)
    in ErrorBoundary
    in IntlProvider
overrideMethod @ react_devtools_backend.js:4012
warningWithoutStack @ react-dom.development.js:506
warning @ react-dom.development.js:2628
dispatchAction @ react-dom.development.js:13499
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.LayoutFeature.updateLayoutClasses @ ag-grid-community.cjs.js:20907
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.LayoutFeature.postConstruct @ ag-grid-community.cjs.js:20896
(anonymous) @ ag-grid-community.cjs.js:826
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.callLifeCycleMethodsOnBean @ ag-grid-community.cjs.js:826
(anonymous) @ ag-grid-community.cjs.js:809
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.callLifeCycleMethods @ ag-grid-community.cjs.js:809
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.wireBeans @ ag-grid-community.cjs.js:688
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.createBean @ ag-grid-community.cjs.js:676
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.BeanStub.createBean @ ag-grid-community.cjs.js:2815
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.BeanStub.createManagedBean @ ag-grid-community.cjs.js:2810
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridCtrl.setComp @ ag-grid-community.cjs.js:43632
(anonymous) @ gridComp.js:74
(anonymous) @ useEffectOnce.js:23
commitHookEffectList @ react-dom.development.js:17283
commitPassiveHookEffects @ react-dom.development.js:17307
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitPassiveEffects @ react-dom.development.js:18774
wrapped @ scheduler-tracing.development.js:207
flushPassiveEffects @ react-dom.development.js:18822
enqueueSetState @ react-dom.development.js:11167
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
(anonymous) @ Provider.js:53
dispatch @ redux.js:214
e @ VM647:1
(anonymous) @ middleware.js:66
(anonymous) @ index.js:11
(anonymous) @ middleware.js:26
(anonymous) @ errorHandling.tsx:96
dispatch @ redux.js:611
(anonymous) @ utils.js:250
(anonymous) @ proc.js:479
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:476
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
Promise.then (async)
resolvePromise @ proc.js:440
runCallEffect @ proc.js:507
runEffect @ proc.js:425
next @ proc.js:306
proc @ proc.js:261
resolveIterator @ proc.js:446
runEffect @ proc.js:422
next @ proc.js:306
currCb @ proc.js:378
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
(anonymous) @ index.js:11
(anonymous) @ middleware.js:26
(anonymous) @ errorHandling.tsx:96
(anonymous) @ redux.js:462
(anonymous) @ authentication.tsx:159
step @ authStorage.ts:87
(anonymous) @ authStorage.ts:87
fulfilled @ authStorage.ts:87
Promise.then (async)
step @ authStorage.ts:87
(anonymous) @ authStorage.ts:87
./src/views/shared/authentication/authentication.tsx.__awaiter @ authStorage.ts:87
./src/views/shared/authentication/authentication.tsx.Authentication.handleLogin @ authentication.tsx:150
(anonymous) @ ProvAuthService.ts:95
Promise.then (async)
./src/views/shared/authentication/authservice/ProvAuthService.ts.ProvAuthService.login @ ProvAuthService.ts:84
./src/views/shared/authentication/authentication.tsx.Authentication.login @ authentication.tsx:104
./src/views/shared/authentication/authentication.tsx.Authentication.componentDidMount @ authentication.tsx:91
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
enqueueSetState @ react-dom.development.js:11169
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
(anonymous) @ serverStatus.tsx:80
step @ errorBoundary.tsx:74
(anonymous) @ errorBoundary.tsx:74
fulfilled @ errorBoundary.tsx:74
Promise.then (async)
step @ errorBoundary.tsx:74
fulfilled @ errorBoundary.tsx:74
Promise.then (async)
step @ errorBoundary.tsx:74
(anonymous) @ errorBoundary.tsx:74
./src/views/error/serverStatus.tsx.__awaiter @ errorBoundary.tsx:74
./src/views/error/serverStatus.tsx.ServerStatus.pingServer @ serverStatus.tsx:49
./src/views/error/serverStatus.tsx.ServerStatus.componentDidMount @ serverStatus.tsx:46
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
render @ react-dom.development.js:21155
(anonymous) @ index.tsx:141
Promise.then (async)
./src/index.tsx @ index.tsx:117
__webpack_require__ @ bootstrap:63
0 @ widgetMetricsCommon.ts:55
__webpack_require__ @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ bootstrap:198

Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().
    in GridBodyComp (created by GridComp)
    in ForwardRef(TabGuardCompRef)
    in ForwardRef(TabGuardCompRef) (created by GridComp)
    in div (created by GridComp)
    in div (created by GridComp)
    in GridComp (created by AgGridReactUi)
    in div (created by AgGridReactUi)
    in AgGridReactUi (created by AgGridReact)
    in AgGridReact (created by Grid)
    in div (created by Grid)
    in div (created by Spinner)
    in Spinner (created by Grid)
    in Grid (created by PortfolioGrid)
    in PortfolioGrid (created by InjectIntl(PortfolioGrid))
    in InjectIntl(PortfolioGrid) (created by Portfolios)
    in div (created by CardBody)
    in CardBody (created by Portfolios)
    in div (created by Card)
    in Card (created by Portfolios)
    in div (created by Portfolios)
    in div (created by Body)
    in Body (created by Portfolios)
    in div (created by Spinner)
    in Spinner (created by Pane)
    in Pane (created by Portfolios)
    in div (created by Body)
    in Body (created by Portfolios)
    in div (created by PageView)
    in PageView (created by Portfolios)
    in Portfolios (created by Context.Consumer)
    in Connect(Portfolios) (created by Context.Consumer)
    in ErrorBoundary (created by Context.Consumer)
    in Route (created by SecuredRoute)
    in SecuredRoute (created by PortfolioApplicationRoutes)
    in Switch (created by PortfolioApplicationRoutes)
    in PortfolioApplicationRoutes (created by PortfolioApplicationLayout)
    in div (created by Spinner)
    in Spinner (created by PortfolioApplicationLayout)
    in div (created by Layout)
    in Layout (created by PortfolioApplicationLayout)
    in PortfolioApplicationLayout (created by InjectIntl(PortfolioApplicationLayout))
    in InjectIntl(PortfolioApplicationLayout) (created by Context.Consumer)
    in Connect(InjectIntl(PortfolioApplicationLayout)) (created by Context.Consumer)
    in Route
    in Authentication (created by Context.Consumer)
    in Connect(Authentication) (created by Context.Consumer)
    in withRouter(Connect(Authentication))
    in Router
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Context.Consumer)
    in Connect(ConnectedRouterWithContext)
    in ServerStatus (created by Context.Consumer)
    in Connect(ServerStatus)
    in Provider
    in GlobalIntlProvider (created by InjectIntl(GlobalIntlProvider))
    in InjectIntl(GlobalIntlProvider)
    in ErrorBoundary
    in IntlProvider
overrideMethod @ react_devtools_backend.js:4012
warningWithoutStack @ react-dom.development.js:506
warning @ react-dom.development.js:2628
dispatchAction @ react-dom.development.js:13499
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridBodyCtrl.setCellTextSelection @ ag-grid-community.cjs.js:22009
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridBodyCtrl.setComp @ ag-grid-community.cjs.js:21967
(anonymous) @ gridBodyComp.js:85
(anonymous) @ useEffectOnce.js:23
commitHookEffectList @ react-dom.development.js:17283
commitPassiveHookEffects @ react-dom.development.js:17307
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitPassiveEffects @ react-dom.development.js:18774
wrapped @ scheduler-tracing.development.js:207
flushPassiveEffects @ react-dom.development.js:18822
renderRoot @ react-dom.development.js:19365
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
commitPassiveEffects @ react-dom.development.js:18795
wrapped @ scheduler-tracing.development.js:207
flushPassiveEffects @ react-dom.development.js:18822
enqueueSetState @ react-dom.development.js:11167
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
(anonymous) @ Provider.js:53
dispatch @ redux.js:214
e @ VM647:1
(anonymous) @ middleware.js:66
(anonymous) @ index.js:11
(anonymous) @ middleware.js:26
(anonymous) @ errorHandling.tsx:96
dispatch @ redux.js:611
(anonymous) @ utils.js:250
(anonymous) @ proc.js:479
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:476
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
Promise.then (async)
resolvePromise @ proc.js:440
runCallEffect @ proc.js:507
runEffect @ proc.js:425
next @ proc.js:306
proc @ proc.js:261
resolveIterator @ proc.js:446
runEffect @ proc.js:422
next @ proc.js:306
currCb @ proc.js:378
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
(anonymous) @ index.js:11
(anonymous) @ middleware.js:26
(anonymous) @ errorHandling.tsx:96
(anonymous) @ redux.js:462
(anonymous) @ authentication.tsx:159
step @ authStorage.ts:87
(anonymous) @ authStorage.ts:87
fulfilled @ authStorage.ts:87
Promise.then (async)
step @ authStorage.ts:87
(anonymous) @ authStorage.ts:87
./src/views/shared/authentication/authentication.tsx.__awaiter @ authStorage.ts:87
./src/views/shared/authentication/authentication.tsx.Authentication.handleLogin @ authentication.tsx:150
(anonymous) @ ProvAuthService.ts:95
Promise.then (async)
./src/views/shared/authentication/authservice/ProvAuthService.ts.ProvAuthService.login @ ProvAuthService.ts:84
./src/views/shared/authentication/authentication.tsx.Authentication.login @ authentication.tsx:104
./src/views/shared/authentication/authentication.tsx.Authentication.componentDidMount @ authentication.tsx:91
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
enqueueSetState @ react-dom.development.js:11169
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
(anonymous) @ serverStatus.tsx:80
step @ errorBoundary.tsx:74
(anonymous) @ errorBoundary.tsx:74
fulfilled @ errorBoundary.tsx:74
Promise.then (async)
step @ errorBoundary.tsx:74
fulfilled @ errorBoundary.tsx:74
Promise.then (async)
step @ errorBoundary.tsx:74
(anonymous) @ errorBoundary.tsx:74
./src/views/error/serverStatus.tsx.__awaiter @ errorBoundary.tsx:74
./src/views/error/serverStatus.tsx.ServerStatus.pingServer @ serverStatus.tsx:49
./src/views/error/serverStatus.tsx.ServerStatus.componentDidMount @ serverStatus.tsx:46
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
render @ react-dom.development.js:21155
(anonymous) @ index.tsx:141
Promise.then (async)
./src/index.tsx @ index.tsx:117
__webpack_require__ @ bootstrap:63
0 @ widgetMetricsCommon.ts:55
__webpack_require__ @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ bootstrap:198

Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().
overrideMethod @ react_devtools_backend.js:4012
warningWithoutStack @ react-dom.development.js:506
warning @ react-dom.development.js:2628
dispatchAction @ react-dom.development.js:13499
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridBodyCtrl.isVerticalScrollShowing @ ag-grid-community.cjs.js:22084
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ViewportSizeFeature.updateScrollVisibleServiceImpl @ ag-grid-community.cjs.js:26018
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ViewportSizeFeature.updateScrollVisibleService @ ag-grid-community.cjs.js:26012
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ViewportSizeFeature.checkViewportAndScrolls @ ag-grid-community.cjs.js:25982
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ViewportSizeFeature.onCenterViewportResized @ ag-grid-community.cjs.js:25967
listener @ ag-grid-community.cjs.js:25956
(anonymous) @ ag-grid-community.cjs.js:566
setTimeout (async)
(anonymous) @ ag-grid-community.cjs.js:557
react_devtools_backend.js:4012 

Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().
overrideMethod @ react_devtools_backend.js:4012
warningWithoutStack @ react-dom.development.js:506
warning @ react-dom.development.js:2628
dispatchAction @ react-dom.development.js:13499
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridBodyCtrl.setColumnMovingCss @ ag-grid-community.cjs.js:22004
(anonymous) @ ag-grid-community.cjs.js:44198
(anonymous) @ ag-grid-community.cjs.js:44211
(anonymous) @ ag-grid-community.cjs.js:44211
setTimeout (async)
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ColumnAnimationService.flush @ ag-grid-community.cjs.js:44211
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ColumnAnimationService.finish @ ag-grid-community.cjs.js:44169
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ColumnModel.applyColumnState @ ag-grid-community.cjs.js:5316
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ColumnApi.applyColumnState @ ag-grid-community.cjs.js:42780
./shell/src/shell/components/grid/gridWrapper.tsx.Grid.setStoredGridSettings @ gridWrapper.tsx:1350
./shell/src/shell/components/grid/gridWrapper.tsx.Grid.agGridOnReady @ gridWrapper.tsx:863
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridOptionsWrapper.globalEventHandler @ ag-grid-community.cjs.js:20671
(anonymous) @ ag-grid-community.cjs.js:1073
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.VanillaFrameworkOverrides.dispatchEvent @ ag-grid-community.cjs.js:41846
(anonymous) @ ag-grid-community.cjs.js:1073
(anonymous) @ ag-grid-community.cjs.js:1109
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.EventService.flushAsyncQueue @ ag-grid-community.cjs.js:1109
setTimeout (async)
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.EventService.dispatchAsync @ ag-grid-community.cjs.js:1093
(anonymous) @ ag-grid-community.cjs.js:1073
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.EventService.dispatchToListeners @ ag-grid-community.cjs.js:1071
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.EventService.dispatchEvent @ ag-grid-community.cjs.js:1046
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridOptionsWrapper.getScrollbarWidth @ ag-grid-community.cjs.js:20447
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridOptionsWrapper.init @ ag-grid-community.cjs.js:19402
(anonymous) @ ag-grid-community.cjs.js:826
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.callLifeCycleMethodsOnBean @ ag-grid-community.cjs.js:826
(anonymous) @ ag-grid-community.cjs.js:809
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.callLifeCycleMethods @ ag-grid-community.cjs.js:809
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.wireBeans @ ag-grid-community.cjs.js:688
Context @ ag-grid-community.cjs.js:666
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridCoreCreator.create @ ag-grid-community.cjs.js:47144
./node_modules/ag-grid-react/lib/reactUi/agGridReactUi.js.AgGridReactUi.componentDidMount @ agGridReactUi.js:127
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
enqueueSetState @ react-dom.development.js:11169
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
(anonymous) @ Provider.js:53
dispatch @ redux.js:214
e @ VM647:1
(anonymous) @ middleware.js:66
(anonymous) @ index.js:11
(anonymous) @ middleware.js:26
(anonymous) @ errorHandling.tsx:96
dispatch @ redux.js:611
(anonymous) @ utils.js:250
(anonymous) @ proc.js:479
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:476
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
Promise.then (async)
resolvePromise @ proc.js:440
runCallEffect @ proc.js:507
runEffect @ proc.js:425
next @ proc.js:306
proc @ proc.js:261
resolveIterator @ proc.js:446
runEffect @ proc.js:422
next @ proc.js:306
currCb @ proc.js:378
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
(anonymous) @ index.js:11
(anonymous) @ middleware.js:26
(anonymous) @ errorHandling.tsx:96
(anonymous) @ redux.js:462
(anonymous) @ authentication.tsx:159
step @ authStorage.ts:87
(anonymous) @ authStorage.ts:87
fulfilled @ authStorage.ts:87
Promise.then (async)
step @ authStorage.ts:87
(anonymous) @ authStorage.ts:87
./src/views/shared/authentication/authentication.tsx.__awaiter @ authStorage.ts:87
./src/views/shared/authentication/authentication.tsx.Authentication.handleLogin @ authentication.tsx:150
(anonymous) @ ProvAuthService.ts:95
Promise.then (async)
./src/views/shared/authentication/authservice/ProvAuthService.ts.ProvAuthService.login @ ProvAuthService.ts:84
./src/views/shared/authentication/authentication.tsx.Authentication.login @ authentication.tsx:104
./src/views/shared/authentication/authentication.tsx.Authentication.componentDidMount @ authentication.tsx:91
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
enqueueSetState @ react-dom.development.js:11169
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
(anonymous) @ serverStatus.tsx:80
step @ errorBoundary.tsx:74
(anonymous) @ errorBoundary.tsx:74
fulfilled @ errorBoundary.tsx:74
Promise.then (async)
step @ errorBoundary.tsx:74
fulfilled @ errorBoundary.tsx:74
Promise.then (async)
step @ errorBoundary.tsx:74
(anonymous) @ errorBoundary.tsx:74
./src/views/error/serverStatus.tsx.__awaiter @ errorBoundary.tsx:74
./src/views/error/serverStatus.tsx.ServerStatus.pingServer @ serverStatus.tsx:49
./src/views/error/serverStatus.tsx.ServerStatus.componentDidMount @ serverStatus.tsx:46
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
render @ react-dom.development.js:21155
(anonymous) @ index.tsx:141
Promise.then (async)
./src/index.tsx @ index.tsx:117
__webpack_require__ @ bootstrap:63
0 @ widgetMetricsCommon.ts:55
__webpack_require__ @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ bootstrap:198
react_devtools_backend.js:4012 

Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().
overrideMethod @ react_devtools_backend.js:4012
warningWithoutStack @ react-dom.development.js:506
warning @ react-dom.development.js:2628
dispatchAction @ react-dom.development.js:13499
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridBodyCtrl.isVerticalScrollShowing @ ag-grid-community.cjs.js:22084
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ViewportSizeFeature.updateScrollVisibleServiceImpl @ ag-grid-community.cjs.js:26018
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ViewportSizeFeature.updateScrollVisibleService @ ag-grid-community.cjs.js:26012
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ViewportSizeFeature.checkViewportAndScrolls @ ag-grid-community.cjs.js:25982
./node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.ViewportSizeFeature.onCenterViewportResized @ ag-grid-community.cjs.js:25967
listener @ ag-grid-community.cjs.js:25956
(anonymous) @ ag-grid-community.cjs.js:566
setTimeout (async)
(anonymous) @ ag-grid-community.cjs.js:557
react_devtools_backend.js:4012 

**System and packages:**

Operating system: Windows

IDE: Visual studio code

package manager: npm

* **AG Grid version:** 27.2.0

* **Browser:**
Chrome 

* **Language:** [React: 16.8.3 | React-dom: 16.8.4| TypeScript: 4.6.3 | Webpack: 4.46.0 | ES6 | ES5]

**Comment by StephenCooper** [comment]
It seems that this error is from an incorrect usage of React hooks and not AG Grid. As such I am going to close this ticket. However, if you think I am wrong and this is a bug in our component then please provide a reproduction showing it so that we can investigate. Thanks!

**Comment by STEjovanovicFAN** [comment]
Here is reproducible link: 

https://stackblitz.com/edit/ag-grid-react-hello-world-qgxqtv?file=package.json

Also attached screenshot:
![image](https://user-images.githubusercontent.com/24360515/211409218-fd7fb7cf-6bf5-4663-96df-17b5772a64c6.png)

**Comment by StephenCooper** [comment]
I have just bumped your react version to 16.10.2 and the warning goes away. As this does not happen from that point on in terms of React versions our advice would be to upgrade React to avoid this issue.
