### ISSUE TITLE
Query related to web component support

### ISSUE THREAD

**Issue by deepakCTL** [ag-grid/ag-grid#5969]
Ag-grid used to have a web-component version of the grid. Is it not available now? 
Or is there a way we can achieve this?
Thank you in advance.

On a side note, I am really loving this grid. It rocks in all directions (performance, memory management, and easy integration).

**Comment by StephenCooper** [comment]
Hi @deepakCTL,

Yes, there used to be web-component version but this was shelved a long time ago as at the time the cost / benefit ratio of maintaining it was not high enough based on user demand. As can be seen in https://github.com/ag-grid/ag-grid/issues/5586 this may now be changing so may need to be re-evaluated. However, to fully support all grid features correctly will be a large project so I would not expect it anytime soon. 

As you may already know depending on your feature set AG Grid can work within a web component.

**Comment by deepakCTL** [comment]
Thank you @StephenCooper. Do we have any example of it being wrapped as a web component? :)

**Comment by StephenCooper** [comment]
Not officially from ourselves. There maybe community content available online but I have not investigated this.

**Comment by deepakCTL** [comment]
@StephenCooper  I have seen that we were still exporting a polymer custom element to some recent versions. Do we have some examples of the same somewhere? Thanks in advance.
