### ISSUE TITLE
'inRange' filter does not correctly handle leaving one field blank

### ISSUE THREAD

**Issue by smooth038** [ag-grid/ag-grid#5982]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

plunker: https://plnkr.co/edit/0PJpqWBvwD9pGjTJ?open=index.tsx

**Current behavior**

When applying an 'inRange' filter on a Date or Time column, and the filter has an 'Apply' button with the 'closeOnApply' option set to true, if the user enters a date/time value only for the 'From' or the 'To' field, leaves the other field untouched, and clicks on 'Apply', the filter panel closes but no filter gets applied.

If the user opens the filter panel again, he still can see the values previously entered, even though they do not reflect the true state of the filter.

**Expected behavior**

The reason a user would like to type in only one field, for example the 'From' field, would be to visualize all entries with date greater than or equal to a certain date. 

I would expect either of these 2 behaviors:
- When clicking on apply, the filter closes and applies the filter correctly (all dates greater than or equal to 'From' or all dates lesser than or equal to 'To')
- When clicking on apply, the filter does not close and shows an error in the form, telling the user he should enter both values. Or there should be some way of indicating that his inputs are incorrect.

I am aware that the filter also provides a 'less than or equals' and 'greater than or equals' option for doing exactly what I am describing. However, the current behavior of the 'inRange' filter does not seem correct to me, as it does accept the input, saves its state, and closes on apply as though everything worked correctly.

**Please tell us about your environment:**

See plunker: https://plnkr.co/edit/0PJpqWBvwD9pGjTJ?open=index.tsx&preview
 I used the example provided in the online documentation (https://www.ag-grid.com/react-data-grid/filter-date/) changing only a few lines to add the 'Apply' button and the filterOptions. 
* **AG Grid version:** 28.2.1

* **Browser:** Chrome 108.0.5359.98

* **Language:** TypeScript 3.7.7

**Comment by MiryksV** [comment]
Raised in AG Grid support too : https://ag-grid.zendesk.com/hc/en-us/requests/25608

**Comment by StephenCooper** [comment]
Closing as feature request has been made via ZenDesk
