### ISSUE TITLE
`ToolPanelFiltersCompParams` does not exist and toolPanelParams aren't applied to `agFiltersToolPanel`

### ISSUE THREAD

**Issue by julienfdev** [ag-grid/ag-grid#5984]
Hello there,

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
As per the documentation [Filters Tool Panel](https://www.ag-grid.com/react-data-grid/tool-panel-filters/), I should be able to use various suppressOptions provided by the `ToolPanelFiltersCompParams` interface

**Current behavior**
When using the following configuration : 
```
                {
                    id: 'filters',
                    labelKey: 'filters',
                    iconKey: 'filter',
                    toolPanel: 'agFiltersToolPanel',
                    toolPanelParams: {
                        suppressExpandAll: true,
                        suppressSyncLayoutWithGrid: true,
                        suppressFilterSearch: true,
                    },
                },
```
the filters expand anyway, the layout sync isn't suppressed and the filter is still present. What's weird is that even in the example provided and displayed in the documentation, it doesn't work either, maybe a regression ?

**Expected behavior**
The toolPanelParams should be properly applied to the `agFiltersToolPanel`

**Please tell us about your environment:**
Node 16 LTS, AG-Grid React 28.2.1

* **AG Grid version:** 28.2.1

* **Browser:**
All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 4.8

Cheers !

**Comment by julienfdev** [comment]
Awesome !
Thank you very much for this !

**Comment by StephenCooper** [comment]
As an fyi this works in 28.1 if you cannot wait or not able to immediately update to v29 when it comes out.
