### ISSUE TITLE
Grid doesn't preserve the columnState ordering while defaultColDef is reactive 

### ISSUE THREAD

**Issue by Elwazer007** [ag-grid/ag-grid#5990]
**I'm submitting a ...**  bug report for Ag grid column state consistency after upgrading to version `27.1.0`

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior** The grid doesn't preserve the applied column state order after a re-render is called for example changing the state here for a dump `temp` state i 've added (from docs example) , will reset the Grid columns state here's the steps to re-produce 
1 - click the `Show Medals Last` button  , ( the grid should change the column ordering after updating the column state) 
2- Click `Test` button 
The grid will revert the current state after re-rendering the component because the `defaultColDef` is reactive and reset the order state.

check the plunker link here : https://plnkr.co/edit/phsPMjVgUhX0z6JA

**Expected behavior**

The grid is expected to have consistency after a state update is triggered and `defaultColDef` shouldn't affer the state ordering

**Please tell us about your environment:**

* **AG Grid version:** 27.1.0

* **Browser:** Chrome

* **Language:**  react/js

**Comment by StephenCooper** [comment]
Hi @Elwazer007,

You will want to use the following grid property to avoid the columns being re-ordered. 

```
maintainColumnOrder={true}
```

However, I understand the confusion here as you are setting the default column def which does not impact and column ordering. As such I am going to spend a bit of time understanding this issue further.

**Comment by StephenCooper** [comment]
I have raised AG-7826 to record this issue as part of our bigger reactivity project. As such I am going to close this ticket here in Github.
