### ISSUE TITLE
Problem when trying to go to next column's custom floating filter using tab

### ISSUE THREAD

**Issue by 01shadowalker01** [ag-grid/ag-grid#5991]
**I'm submitting a ...** 
```
[] bug report
[] feature request
[x] support request
```

**Description**

I'm using the custom floating filter in **ag-grid** in Angular. I have an issue with tab behavior on the custom floating filter and it doesn't work (when I press tab, it doesn't go to the next column's floating filter).

**Current behavior**

It works on the [examples ](https://www.ag-grid.com/angular-data-grid/component-floating-filter/)on the ag-grid's website but doesn't work in my custom filter. I did some investigation and found out that the way it works inside ag-grid (roughly) is that there is a `focusService` and it has a `findFocusableElements` method which when a filter component is focused is called. the method finds the elements based on a constant called `FOCUSABLE_SELECTOR` and excludes elements in `FOCUSABLE_EXCLUDE`. The value of the constants:
```typescript
export const FOCUSABLE_SELECTOR = '[tabindex], input, select, button, textarea, [href]';
export const FOCUSABLE_EXCLUDE = '.ag-hidden, .ag-hidden *, [disabled], .ag-disabled, .ag-disabled *';
```

It seems that the reason it doesn't work for me is that as I mentioned `TextFloatingFilterComponent` in the follow-up, I'm using `f-textbox` which is a custom web component built with **stencil.js**, and its name is not in `FOCUSABLE_SELECTOR`. So when I press the tab key, it doesn't focus on my `f-textbox`.

**Providing a Reproducible Scenario**
```typescript
import { IFloatingFilter } from 'ag-grid-community';

@Component({
  template: `
    <f-textbox
      #editor
      [value]="value"
      Type="{{ params?.type || 'text' }}"
      (field-change)="valueChanged($event)"
    >
    </f-textbox>
  `
})
export class TextFloatingFilterComponent implements IFloatingFilter { 
  ...
}
```

**Expected behavior**
I want to be able to focus on any custom floating filter that I provide to ag-grid. I think if I could change the value of `FOCUSABLE_SELECTOR`, I could achieve my goal.

If there is another way of achieving the goal, I would be glad to know about it.

**Please tell us about your environment:**

* **AG Grid version:** 28.2.0

We are using `ag-grid-community` & `ag-grid-angular`

* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 

* **Language:** TypeScript 4.5.4

**Comment by StephenCooper** [comment]
In our latest release we added the following new example for custom keyboard navigation into custom components. 

https://ag-grid.com/angular-data-grid/component-header/#example-header-component-keyboard-navigation

It might be a good starting point to help you achieve what you want.
