### ISSUE TITLE
Grid API setColumnDefs not inferring ColDef generic type from declared AgGridAngular

### ISSUE THREAD

**Issue by KrazyTako** [ag-grid/ag-grid#5993]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
It seems that `setColumnDefs` does not infer the `ColDef` generic type based on the AgGridAngular generic. It always defaults to the non-generic type. The type inference works when defining the columnDefs using GridOptions<Type>, however due to the nature of our code we need to set the column defs outside of the GridOptions. So it would be nice for this type inference to persist on the GridApi.

```
interface Type {
    name: string;
}

agGrid: AgGridAngular<Type>

setUp() {
    this.agGrid.api.setColumnDefs([
        valueGetter: params => params.data.name // no type inference here
    ]);
    this.agGrid.api.getColumnDefs(); // has type inference: ColDef<Type>[]
}
```

**Expected behavior**
`setColumnDefs` should infer the generic `ColDef<>` type that was originally used when declaring the `AgGridAngular<Type>`

**Please tell us about your environment:**

* **AG Grid version:** 28.2.1

* **Language:** TypeScript 4.7.4

**Comment by StephenCooper** [comment]
Hi @KrazyTako,

Thanks for reporting this missing generic inference. I have raised  AG-7809 to investigate this but from initial inspection it does look like it is just missing. 

If it is just missing then I will get this added, most likely as part of v29.1 as it is too late to add it to v29 which is shortly going to be released.

**Comment by KrazyTako** [comment]
@StephenCooper I appreciate it, thanks.
