### ISSUE TITLE
How to disable loadingCellRenderer? 

### ISSUE THREAD

**Issue by maranmaran** [ag-grid/ag-grid#6000]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behaviour**
Using SSRM introduces default loadingCellRenderer component into the grid on row level. 

I wish to be able to disable it and have an empty grid as I'll use my own overlays to indicate loading is in progress.

**Expected behavior**
Being able to disable loadingCellRenderer

**Stack:**
Latest Angular 
Latest AG Grid at this time - Enterprise version

PS: Maybe I'm missing something simple so someone might be able to help me. 
I tried providing empty cell renderer but that doesn't satisfy me as it still includes it as component, has some other styles etc and it feels clunky.

**Comment by StephenCooper** [comment]
Hi @maranmaran,

There is no feature to completely disable the loading cell renderer at this point in time so the closet would be an empty cell renderer as you have said. I see this leaves an empty row in the data still though.

As an Enterprise customer you are free to raise a feature request via ZenDesk as that is how new features are requested.

**Comment by maranmaran** [comment]
@StephenCooper Hi, ok thanks. I will as soon as I get access, you're free to close this
