### ISSUE TITLE
Is it possible to unit test ag grid with server side pagination?

### ISSUE THREAD

**Issue by Sabrinovsky** [ag-grid/ag-grid#6001]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

I tried to create a unit test but the data source is never called. Is it possible to unit test it?

**Comment by StephenCooper** [comment]
It should be, assuming that your data source is accessible from your test code. Without further details I would guess that potentially your test is not waiting for the grids async behaviour to run, which would include requesting the server side data?
