### ISSUE TITLE
Cell Renderer throwing error for <script setup> Component in Vue 2.7 and Vite

### ISSUE THREAD

**Issue by marlokessler** [ag-grid/ag-grid#6003]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Hi there 👋🏽,

not quite sure whether this is a bug or whether I am doing something wrong.

**TL;DR**: I use AG Grid in my Vue 2 project and want to overwrite some cells. When overwriting cells with custom components built with the Vue Composition Script Setup api, [this error occures](#current_behavior).

**Current setup**
The `Child.vue` component looks like this:
```typescript
<template>
  <div>{{ text }}</div>
</template>

<script setup lang="ts">
withDefaults(defineProps<{ text: string }>(), {
  text: "Hello World",
});
</script>
```

The `Parent.vue` component looks like this:
```typescript
<template>
  <ag-grid-vue
    :column-defs="columnDefs"
    :row-data="items"
    :grid-options="gridOptions"
  />
</template>

<script setup lang="ts">
import { ColDef } from "ag-grid-community";
import Child from "./Child.vue";

const gridOptions:  ref<GridOptions>({
  …
  components: {
    Child,
  },
  …
});

const columnDefs = ref<ColDef[]>([
  { headerName: "Make", field: "make", cellRenderer: "Child" },
  { headerName: "Model", field: "model" },
  { headerName: "Price", field: "price" },
]);

const items = ref([
  { make: "Toyota", model: "Celica", price: 35000 },
  { make: "Ford", model: "Mondeo", price: 32000 },
  { make: "Porsche", model: "Boxster", price: 72000 },
  …
]);
</script>
```

**Current behavior**<a name="current_behavior"></a>
The `cellRenderer` property throws the following error:
```
Uncaught TypeError: componentType is not a constructor
    at VueComponentFactory2.createAndMountComponent (VueComponentFactory.js:31:25)
    at VueFrameworkComponentWrapper2.createComponent (VueFrameworkComponentWrapper.js:75:36)
    at DynamicComponent2.createComponent (VueFrameworkComponentWrapper.js:63:29)
    at VueComponent2.init (VueFrameworkComponentWrapper.js:117:31)
    at DynamicComponent2.init (VueFrameworkComponentWrapper.js:37:39)
    at UserComponentFactory2.initComponent (ag-grid-community.auto.esm.js:20621:26)
    at UserComponentFactory2.newAgStackInstance (ag-grid-community.auto.esm.js:20587:33)
    at Object.newAgStackInstance (ag-grid-community.auto.esm.js:20505:60)
    at createCellRendererFunc (ag-grid-community.auto.esm.js:29207:48)
    at AnimationFrameService2.executeFrame (ag-grid-community.auto.esm.js:36336:21)
```

**Expected behavior**
The custom component is rendered in the cell.

**Please tell us about your environment:**
I'm using the following dependencies:
```json
{
  "dependencies": {
    "vue": "^2.7.14",
    "ag-grid-community": "^28.2.1",
    "ag-grid-vue": "^28.2.1",
    …
  },
  "devDependencies": {
    "vite": "^3.2.5",
    "vite-plugin-vue2": "^2.0.2",
    "typescript": "^4.8.4",
    …
  },
}
```
I'm working on a M1 MacBook, Node v17.9.1.

* **AG Grid version:** 28.2.1
* **AG Grid Vue version:** 28.2.1

* **Browser:** Chrome

* **Language:** TypeScript 4.8.4

**Comment by seanlandsman** [comment]
Hi

This should work provided you register the components with the grid's `frameworkComponents` property
 
Please see this repo for an example of this: https://github.com/seanlandsman/ag-grid-vue3-setup

**Comment by marlokessler** [comment]
I tried it and it still throws the same error. I investigated a bit further and found that this is most probably related to the fact that I am using Vue 2.7 with the composition api. Even though Vue 2.7 supports the composition Api it does not support the `createApp` function to instantiate components. Thus, I found a workaround by wrapping them in an Options Api component which solved the issue:
```typescript
…
const gridOptions:  ref<GridOptions>({
  …
});


const ChildCellRenderer = Vue.extend({
  render(h) {
    return h(Child);
  },
});

const columnDefs = ref<ColDef[]>([
  { headerName: "Make", field: "make", cellRenderer: ChildCellRenderer },
  { headerName: "Model", field: "model" },
  { headerName: "Price", field: "price" },
]);
…
```

Nevertheless, imo it would be better if AG Grid handles this on it's own.
