### ISSUE TITLE
Ag Grid memory leak 

### ISSUE THREAD

**Issue by Elwazer007** [ag-grid/ag-grid#6005]
I'm submitting a  community request to help investigate why the grid has a memory leak !

**Current behavior**

I 've created this plnkr : https://plnkr.co/edit/MiRhkcG9sZTZO74P?preview 

**Current behaviour**
clicking on the `Toggle` button should unmount the grid component and then free up its resources from memory , however I inspected the memory tab in chrome devtools and I still see the `rowNode` objects are still there and many other objects from the grid

**Expected behavior**
I expect the grid to free up the memory resources after being un-mounted 

* **AG Grid version:** 27.0.0

* **Browser:**

* **Language:** javascript

**Comment by Elwazer007** [comment]
<img width="1504" alt="Screenshot 2023-01-13 at 2 49 03 PM" src="https://user-images.githubusercontent.com/28496859/212324034-8d13aec8-dfe2-445c-86f8-ccc098f12ca2.png">

**Comment by StephenCooper** [comment]
Hi @Elwazer007,

I think this is just a timing thing with when the browser runs garbage collection. For me I see the rowNodes cleaned up if I resize the browser a few times before taking the second snapshot after the grid has been toggled out of view.

**Comment by Elwazer007** [comment]
I 've tried to resize the browser window a few times and waited for many seconds and I still see the `rowNodes` and `gridAPI` in the second snapshot (after destroying the grid )

**Comment by ankitmehta22** [comment]
Was this ever resolved?
