### ISSUE TITLE
Internet Explorer 11 is freezing if the dropdown menu of the column filter is open 

### ISSUE THREAD

**Issue by irf4nmohd** [ag-grid/ag-grid#6009]
When I tried to use Ag-grid react in IE 11 to open the filter, the browser crashed.
 "ag-grid-community": "^28.0.2",
 "ag-grid-react": "^28.0.0",

please can any suggest to me how to fix it?

**Comment by StephenCooper** [comment]
Internet Explorer 11 is only officially supported up to [v26.2](https://ag-grid.com/archive/26.2.0/javascript-data-grid/supported-browsers/) of AG Grid.
 
So you will not be able to use v28.

**Comment by irf4nmohd** [comment]
> Internet Explorer 11 is only officially supported up to [v26.2](https://ag-grid.com/archive/26.2.0/javascript-data-grid/supported-browsers/) of AG Grid.
> 
> So you will not be able to use v28.

 thank you so much for responding I will try with  [v26.2](https://ag-grid.com/archive/26.2.0/javascript-data-grid/supported-browsers/)
