### ISSUE TITLE
Pressing Delete does not call agInit of custom Cell Editor

### ISSUE THREAD

**Issue by wein2011** [ag-grid/ag-grid#6011]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
This issue can be reproduced with the Angular Data Grid: Cell Editors example on the Ag Grid website:
https://www.ag-grid.com/examples/component-cell-editor/component-editor/packages/angular/index.html

Set a breakpoint in Chrome on the first line of the agInit function within the numeric-editor.component.ts

Select the first cell in the Numeric column and press Backspace. Chrome will break at the breakpoint. This is expected behavior.

**Current behavior**
Select the second cell in the Numeric column and press Delete. Chrome will NOT break at the breakpoint. This is the current incorrect behavior.

**Expected behavior**
In versions prior to 29, this behavior worked correctly by breaking at the breakpoint. In addition, the setInitialState function of the example does expect the Delete key to enter agInit.

**Please tell us about your environment:**
Chrome Version 109.0.5414.75 (Official Build) (64-bit)

* **AG Grid version:** 29.0
Only an issue with the first 29 version. Prior versions work as expected.

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi @wein2011,

Thanks for reporting this. I can see this behaviour actually changed in the 28.2 release. I have raised an internal ticket for further investigation.

Thanks for bring this to our attention!

**Comment by StephenCooper** [comment]
This is correct, pressing delete no longer starts an editor, it simply clears the value of the cell.

In previous versions this was incorrectly starting the editor and so was corrected in v28. 

The docs have been updated so that the delete key is no longer listed in the keys that [start editing](https://www.ag-grid.com/javascript-data-grid/cell-editing-start-stop/#start-editing). 

We will be updating our examples to remove the Delete key handling as this is misleading.

**Comment by wein2011** [comment]
Thank you for the clarification and updating of the example. The corrected behavior makes sense.
