### ISSUE TITLE
onCellClicked path undefined

### ISSUE THREAD

**Issue by marinawl** [ag-grid/ag-grid#6012]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hello 

I was using it well until a few days ago, but suddenly an error came up, so I'm inquiring.

I was writing the path value in the event of the onCellClick function, but for some reason, it appears as undefined only in Chrome from a week ago...

Other browsers except Chrome have confirmed that it works normally.

I'd like to know if there's something wrong with my code or if there's any change.

Below is the code I used.

```
const option = {
  onCellClicked(event) {
    const { path } = event.event;

    if (path[0].id === 'test1') {
      onTest1Click(event.data);
    } else if (path[0].id === 'test2') {
      onTest2Click(event.data);
    } else if (path[0].id === 'test3') {
      onTest3Click(event.data);
    }
  },
};
```

And this is an error that occurred.

```
  Uncaught TypeError: Cannot read properties of undefined (reading '1')
      at Object.onCellClicked 
      at e.globalEventHandler (ag-grid-community.cjs.js:10384:30)
      at ag-grid-community.cjs.js:3829:58
      at ag-grid-community.cjs.js:3865:52
      at Array.forEach (<anonymous>)
      at e.flushAsyncQueue (ag-grid-community.cjs.js:3865:19)
```

thank you

**Please tell us about your environment:**

* **AG Grid version:** 27.3.0

* **Browser:** Chrome 109.0.5414.75 64bit

* **Language:** React 18.2

**Comment by StephenCooper** [comment]
I tested this with Chrome 108 and I can see that the event had the `path` value set. 
Then upgraded to Chrome 109 and I no longer see the `path` value on the event. 

This is part of the 109 release as can be seen [here](https://chromestatus.com/feature/5726124632965120). 

However, for me the event.composedPath() function is returning an empty `[]` which is not equivalent. This may be a bug in Chrome 109.

**Comment by StephenCooper** [comment]
This issue looks to explain why `event.path` may have a value when `event.componsedPath()` returns an empty array.

https://bugs.chromium.org/p/chromium/issues/detail?id=1277431

> Chromium has a non-standard path attribute which returns an array of the EventTarget objects that the event's path, https://dom.spec.whatwg.org/#event-path.
It returns the same thing as the standard event.composedPath() method, but remains non-empty after event dispatch.
This was mentioned in [issue 924851](https://bugs.chromium.org/p/chromium/issues/detail?id=924851) but not removed as part of Shadow DOM v0 code.

**Comment by marinawl** [comment]
Thank you for your answer.

I used ```event.composedPath()``` as you replied, but I don't think I can use it because an empty ```[]``` came back.

Is there a reason why the empty ```[]``` comes back?

**Comment by StephenCooper** [comment]
I have validated our use cases of `composedPath` internally and it is returning the correct array of values. So I am not sure why this would be different in the above use case. 

I suggest you may have to take this to Chrome. 

Although did you say you are **writing** to the path variable yourself? You may need to use a different property that does not clash with chromes old property name. The other browsers did not support `path`.

I am going to close this ticket as I do not believe there is any further action for AG Grid.
