### ISSUE TITLE
redraw errors & general questions

### ISSUE THREAD

**Issue by omerp-explorium** [ag-grid/ag-grid#6013]
We experience issues eversince upgrading from 26.1.0 to 28.2.1.

The issue is 'AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows'...

I looked into the source code and it looks like there is a method `getLockOnRefresh`
it's called when 
1. scrolling
2. model updated

And then I thought about it, and actually the grid is updated a lot in the background in our usecase, and whenever that happens while we scroll, we get the above exception.
* Note that on version 26.1.0 we did not get that exception *

I wanted to understand why we throw an error here, can't ag-grid schedule a redraw without throwing this error?

Then I looked even further and I noticed

```
    this.dispatchToListeners(agEvent, true);
    this.dispatchToListeners(agEvent, false);
```

And If you comment out the sync dispatch, there will be no more redraw errors and the grid acts correctly.

Then I noticed the grid has `suppressAsyncEvents` and it's recommended to not suppress it..

So in conclution - 

1. Will the double dispatchToListeners be deprecated any time soon?
   1.1 And if so, can we add a suppressSyncEvents, which will solve our issues?
2. If I use 'debounceVerticalScrollbar' everything also works.. but it only delays the redraw, we don't really want to use it. Is there something We're missing?

Thank you in advance

**Comment by StephenCooper** [comment]
Often that error message points to a callback in your application that is triggering a change in the grid state before the current rendering has completed. 

In these situations the best work around is to place the api call within a `setTimeout` with 0 delay. This has the effect of letting the grid finish rendering before then reacting to the next api call. 

However, without any more context about your specific application logic it is hard to know what is really happening.

**Comment by omerman** [comment]
I will add a codesandbox example in the following days.

And just to add some more context before I put the sandbox together 

We use React.
And What happens is 

new props are applied to the Component that renders the grid >
rowData changes >
Grid redraws

And inbetween, user scrolls. 

No grid Api calls whatsoever

**Comment by StephenCooper** [comment]
I am going to close for now as we cannot do any further investigation without a reproduction.

**Comment by apxapob** [comment]
@omerman did you manage to create reproduction example? 
Or have you found a workaround?
We're having this bug too. And it's incredibly hard to reproduce.

**Comment by omerp-explorium** [comment]
@apxapob I added a workaround.. I couldn't find the strength to write a reproduction, I was lazy 😆 .

![image](https://user-images.githubusercontent.com/93073822/236815495-44e9850a-232f-4531-bb5b-b38727152026.png)

![image](https://user-images.githubusercontent.com/93073822/236815561-a7ea05b2-463a-4039-9381-178cbc6714c5.png)

Hope it helps.

**Comment by apxapob** [comment]
thanks, I'll try it.

**Comment by 123456789Dl** [comment]
Hello
@apxapob did you manage to solve this problem?
Or did you stop at the last workaround from @omerman and it worked for you?
In my case, unfortunately, it didn't work.
Thanks

**Comment by apxapob** [comment]
@123456789Dl the workaround didn't work for us either. We made several optimizations and decreased number of react component renderings. And it works fine now.

**Comment by MurphyHou123** [comment]
when rowData updated (eg. pagination update), and there is cellRenderer, the error throw: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.

**Comment by cmsommerville** [comment]
I have this error in a component when upgrading from v29 to v30. 

I am able to resolve two ways -- one of which is setting a timeout of zero like `setTimeout(() => gridApi.setRowData(data), 0)`. The other way is detailed below. I don't understand why this fixes the problem for me. 

Original (simplified) code: **throws error**
```
  useEffect(() => {
    if (!gridApi) return;
    if (!prodSubtypeId) return;
    if (!period) return;

    fetch(
      `/api/my-endpoint/?corporateproductsubtypeid=${prodSubtypeId}&periodEnding=${period}`, 
    )
      .then((res) => res.json())
      .then((data) => {
        if (data.length) {
          setTitle(data[0].corporateproductsubtype);
        }
        gridApi.setRowData(data);
      })
      .finally(() => {
        gridApi.hideOverlay();
      });
  }, [gridApi, prodSubtypeId, period]);
```

Modified code: **no more error**. Switching the order of the `gridApi.setRowData(data)` and the `setTitle(...)` fixed it for me. 
```
  useEffect(() => {
    if (!gridApi) return;
    if (!prodSubtypeId) return;
    if (!period) return;

    fetch(
      `/api/my-endpoint/?corporateproductsubtypeid=${prodSubtypeId}&periodEnding=${period}`, 
    )
      .then((res) => res.json())
      .then((data) => {
        gridApi.setRowData(data);
        if (data.length) {
          setTitle(data[0].corporateproductsubtype);
        }
      })
      .finally(() => {
        gridApi.hideOverlay();
      });
  }, [gridApi, prodSubtypeId, period]);
```
