### ISSUE TITLE
Can't find styles on modules version 29.0.0

### ISSUE THREAD

**Issue by rosostolato** [ag-grid/ag-grid#6016]
Can't find `styles` folder under `@ag-grid-community/core/dist/styles` after upgrading to v29.0.0. And it's not present in anywhere else, only in the package version under `ag-grid-community/styles/ag-grid`.

**Comment by StephenCooper** [comment]
The v29 Changelog describes why this has been deleted. 

To resolve please follow the instructions [here](https://www.ag-grid.com/javascript-data-grid/global-style-upgrading-to-v28/).

**Comment by rosostolato** [comment]
I had just found that answer and was going to close it, thank you for the link share.
