### ISSUE TITLE
CSS files links (unpkg.com) are broken

### ISSUE THREAD

**Issue by Yaniv-Or** [ag-grid/ag-grid#6017]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Using https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css has been working since version 29.0.0 - now it's broken. The link redirects to: https://unpkg.com/ag-grid-community@29.0.0/dist/styles/ag-grid.css which does not exist. I can see the folder structure has been changed on this version and now it's styles instead of dist/styles.

**Expected behavior**
The URL: https://unpkg.com/ag-grid-community@29.0.0/dist/styles/ag-grid.css should not be broken (404).

**Please tell us about your environment:**
Just a simple HTML file.

* **AG Grid version:** 29.0.0

**Comment by StephenCooper** [comment]
This is expected as noted in the changelog.

> In AG Grid v28, we ported our grid layout system to use CSS variables. AG Grid v27 and earlier used SASS. In order to ease the upgrade to AG Grid v28, we continued to include the legacy Sass API and CSS stylesheets at their old file paths. However, in AG Grid v29 SASS is now removed and you need to change the import paths for CSS and SASS (.scss) files. The v27 import paths are now invalid in v29 and the themes won't work. For more details see [Upgrading Styles to v28](https://ag-grid.com/archive/29.0.0/javascript-data-grid/global-style-upgrading-to-v28/).
