### ISSUE TITLE
CSS specificity problems for custom theme in 29.0.0

### ISSUE THREAD

**Issue by Eugeno** [ag-grid/ag-grid#6020]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
```
@use "@ag-grid-community/styles" as ag;
@include ag.grid-styles((
  theme: alpine-large,
  extend-theme: alpine,
  header-foreground-color: red,
));
```

**Current behavior**
__index.scss:69_
> .ag-theme-alpine-large {
>   ~~--ag-header-foreground-color: red;~~
> }

__css-content.scss:7025_
> [class*=ag-theme-] {
>   --ag-header-foreground-color: var(--ag-secondary-foreground-color);
> }

**Expected behavior**
`--ag-header-foreground-color: red;`

* **AG Grid version:** 29.0.0

So it worked fine with previous syntax, and now I'm trying to migrate using [guide](https://ag-grid.com/archive/29.0.0/javascript-data-grid/global-style-upgrading-to-v28-sass/).

**Comment by Eugeno** [comment]
Temporary solution:
```
my-selector {
  @include ag.grid-styles((
    //
  ));
}
```

**Comment by StephenCooper** [comment]
Hi @Eugeno,

This seems to be working ok in this [example](https://plnkr.co/edit/PYmvrQLO2mp4ym8Y?open=main.js). 

It could be because `ag-theme-alpine-large` is not a supported theme name. Is that a custom theme that you have?

**Comment by Eugeno** [comment]
@StephenCooper yep, it's a custom theme that extends `alpine`. I used [this part of the guide](https://ag-grid.com/archive/29.0.0/javascript-data-grid/global-style-upgrading-to-v28-sass/#:~:text=styles((-,theme%3A%20custom%2Dname%2C,-extend%2Dtheme%3A) as an example.

**Comment by alicia-stotz** [comment]
Hello,
I have the same problem in version `29.10.0`. When I try to use `extend-theme` like the example doc:
```scss
@include ag.grid-styles((
theme: my-custom-theme,
extend-theme: alpine
```

The alpine theme is not apply there are a selector `[class^=ag-]` and `[class^=ag-theme-]` which override all `ag-theme-alpine` selector

I write something wrong ?

Regards

**Comment by StephenCooper** [comment]
@Eugeno It is not possible to generate a theme within a nested setting. 

```
@include ag.grid-styles((
    // valid
));
```
```
.my-selector {
  @include ag.grid-styles((
    // not valid
  ));
}
```

`@include ag.grid-styles()` is meant to create standalone themes, so they should be independent of "selectors".
 
You can't have `.ag-theme-alpine {}` be one theme and `.foo .ag-theme-alpine {}` be a different theme.

@alicia-stotz is it possible that you are calling `@include ag.grid-styles` multiple times in the same enviroment?

**Comment by linsolas** [comment]
Hello @StephenCooper 

For information, I'm working with @alicia-stotz.

This is what we have in our code:

```scss
@use "ag-grid-29" as ag;

@include ag.grid-styles((
    theme: sg-bootstrap,
    extend-theme: alpine,
    grid-size: 6px,
    --ag-header-background-color: violet,
));
```

This is the result on our demonstration page:

![image](https://user-images.githubusercontent.com/623217/229766060-a482851d-be58-4e5f-a276-0252b86225be.png)

where the `--ag-header-background-color` is overriden:

![image](https://user-images.githubusercontent.com/623217/229766406-83056379-106b-4fa3-a3e5-5807cc069853.png)
![image](https://user-images.githubusercontent.com/623217/229766560-60d40d17-fead-411b-9920-a87c004567c9.png)


Our codebase is hosted on a private Enterprise Github, but it does not seem to be a problem to reproduce the problem.

**Comment by StephenCooper** [comment]
We tried to reproduce it with the following project but it seems to be working. 

[vanilla.zip](https://github.com/ag-grid/ag-grid/files/11198317/vanilla.zip)

**Comment by linsolas** [comment]
Hello @StephenCooper,

Thanks for your example. We finally found the issue.
In our example, we load the AgGrid Enterprise / Community bundle like this:

```html
<script src="https://unpkg.com/ag-grid-enterprise@29/dist/ag-grid-enterprise.min.js"></script>
````

With this approach, we encounter the issue explained above. If we use the `.noStyle` bundle, then it works!

```html
<script src="https://unpkg.com/ag-grid-enterprise@29/dist/ag-grid-enterprise.min.noStyle.js"></script>
````

I don't think there is a mention of this point in the documentation.

Thanks

**Comment by val1984** [comment]
Hi @StephenCooper,
What would be the equivalent of `ag-grid-enterprise.min.noStyle.js` for the [modular version of AG-Grid](https://www.ag-grid.com/react-data-grid/modules/)?
Thank you.

**Comment by StephenCooper** [comment]
> Hi @StephenCooper, What would be the equivalent of `ag-grid-enterprise.min.noStyle.js` for the [modular version of AG-Grid](https://www.ag-grid.com/react-data-grid/modules/)? Thank you.

In the modular version you have to pull in the styles manually, so I would not expect you to run into the same issue.

**Comment by pawelzysk** [comment]
Have the same problem. Any update on that?
