### ISSUE TITLE
Request for a general purpose size columns to fit

### ISSUE THREAD

**Issue by audetto** [ag-grid/ag-grid#6021]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

I am not a paying customer and requesting a community feature.

I have been using the grid for a while and the one thing I wish it handled better is column sizing.

I have read https://www.ag-grid.com/angular-data-grid/column-sizing/, and `suppressColumnVirtualisation` and I think there still is  a very important use case left out.

I would like to do the following

1. auto size columns to fit their content
2. uniformly `enlarge` the columns to fit the available horizontal space.

1 is covered by `autoSizeColumns`, but when I then call `sizeColumnsToFit` it intentionally ignores the new adapted sizes.

From the doc:

> Column default widths, rather than current widths, are used while calculating the new widths. This ensures the result is deterministic and does not depend on any Column resizing the user may have manually done.

For `general` data it is hard and lengthy to set `default` widths, the grid has already done a perfect job with `autoSizeColumns`, why throw it away?
And, I would like to fill the space, enlarging the grid. If the result of `autoSizeColumns` does not fit, there is no point in making them smaller, we will have to live with a horizontal scroll bar.

I am not saying this should be forced on anyone, but I think it would be a good `general purpose` sizing algorithm, not as good as a custom tuning, but free for users as all the data is already available to the grid.

So a couple of extra options to `sizeColumnsToFit` could help.

**Comment by StephenCooper** [comment]
Thanks for your feedback and description. 

I have linked this ticket to a similar feature request so that this can be taken into account. Reference AG-2068.

**Comment by audetto** [comment]
Has there been any change or new future plans for this feature?
