### ISSUE TITLE
When Sorting columns in Server Side Model, it moves to first page every time. Is there any way to stop it from moving to first page

### ISSUE THREAD

**Issue by syfekunal** [ag-grid/ag-grid#6031]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I am using Server Side model for ag-grid. But when I try to sort any column, the params in the getRow method are moved to first page everytime. Is there any way to stop the grid to move to first page everytime I try to sort any column ?

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
This [example](https://plnkr.co/edit/zzUs97pbUIvD83mP?open=app%2Fapp.component.ts) shows server side with pagination. When sorting the columns the page is preserved. 

Hopefully that example should give you an insight into how to achieve this. As it works in our latest version in the provided example I am going to close this issue.
