### ISSUE TITLE
When applying Filter with serverSide Row Model [Paginated], why do the grid moves to first page every time ?

### ISSUE THREAD

**Issue by syfekunal** [ag-grid/ag-grid#6043]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hi, 

I am using ag-Grid Enterprise bundle v23.1.0 and I have a paginated serverSide Grid setup with filter functionality enabled. But when I try to apply the filter on any column, the grid moves to the first page every time. 

I have the pageSize and cacheSize = 100, so I want my filter to apply to these 100 rows only on whichever page the filter is applied and not move to the first page. Is there any flag to enable or disable this feature.

**Comment by StephenCooper** [comment]
Hi @syfekunal,

As an fyi we do not provide support for old versions of AG Grid. I believe that this will be working in our latest version similar to your last ticket. https://github.com/ag-grid/ag-grid/issues/6031 

Also we use github issues for bug reports only, which would require a reproduction with the latest version of AG Grid.

If have an AG Grid Enterprise license you can raise a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
