### ISSUE TITLE
Cell Editor Popup not displaying in mobile view

### ISSUE THREAD

**Issue by will-nemo** [ag-grid/ag-grid#6045]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
This bug occurs after upgrading to version  in my ReactJS application.

To reproduce:
1. Make sure application is upgraded to listed version
2. Using the browser dev tools, enable the responsive - mobile view
3. Try to double click table cells that are editable to display the inline/pop up editing

Was also able to reproduce in the AG-Grid React guide. Following the same steps listed above shows the same issue for the example: "Stop Editing When Grid Loses Focus", linked below.

https://www.ag-grid.com/react-data-grid/cell-editing-start-stop/#stop-editing-when-grid-loses-focus

**Expected behavior**
The cell editor popup should display in mobile, same as desktop. The linked functionality above details/shows the edit functionality working until an example with the cell editor popup is implemented.

**Please tell us about your environment:**
- MacOS
- Intellij
- npm
- mobile/responsive view

**AG Grid version:**
28.2.0

**Browser:**
- Safari
- Chrome

**Language:**
- TypeScript 4.6.2

**Comment by StephenCooper** [comment]
> This bug occurs after upgrading to version in my ReactJS application.

Could you provided the details of what you upgraded? And just to confirm this has previously worked for you?

**Comment by will-nemo** [comment]
@StephenCooper 

I upgraded from 27.1.0 to 28.2.0 and yes it previously worked.

This was discovered in my deployed environment on a Safari OS browser, from a mobile phone. Maybe it's some overlay preventing the click events on my side, will look further into it.

Thank you for looking into my reported issue so quickly.
