### ISSUE TITLE
Forced reflows when destroying the Grid

### ISSUE THREAD

**Issue by denisgursky** [ag-grid/ag-grid#6056]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Steps:

- Render `AgGridReact`
- Unmount `AgGridReact`

**Current behavior**
We have a view with a lot of grids, about 80. This view freezes for ~30s when you navigate to another view.
Here's how it looks like in the Chrome profiler.

![image](https://user-images.githubusercontent.com/6468871/213766438-e5e7718c-e6fe-45c6-b294-4f085c0ff31c.png)

There's a lot of forced reflows at the bottom of it.
![image](https://user-images.githubusercontent.com/6468871/213766549-0595b6aa-e5cc-42c7-8fb6-2e212cc45778.png)

Those are caused by `GridBodyScrollFeature.prototype.getVScrollPosition`

![image](https://user-images.githubusercontent.com/6468871/213766776-07eb1942-2b83-4126-b40d-fc296230922a.png)

**Expected behavior**

No forced reflows when the grid is being destroyed.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

29.0.0

* **Browser:**
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
```

* **Language:** 
TypeScript 4.9.3

**Comment by StephenCooper** [comment]
Hi @denisgursky,

Could you please provide us with a reproducible example and the steps taken to show this issue so that we can investigate this further and have a benchmark to test against?

**Comment by denisgursky** [comment]
@StephenCooper 

https://codesandbox.io/s/ag-grid-force-reflow-uidpv5

Press the toggle button at the top. It freezes for about 6 seconds on my machine after the click.

**Comment by StephenCooper** [comment]
Thank you for the clear reproduction. 

One thing I notice is that by removing the enterprise import the grids are cleared without delay. This should help us track it down. Also means there is potentially a work around by switching to the module based approach and only including the enterprise features that you require. (Although that does depend on where this issue is coming from which we still need to track down.)

**Comment by bitgoAaron** [comment]
Hi @StephenCooper is AG-7920 still scheduled for fixing soon? I noticed it was marked as completed, but haven't seen it mentioned in release notes, closed PRs, etc. Still running into this problem, and using `suppressReactUi` is not an option for us

**Comment by StephenCooper** [comment]
@bitgoAaron yes this has been fixed and will be part of our v30 release due out in a week or two.

**Comment by bitgoAaron** [comment]
@StephenCooper is it possible to get a canary or pre-build? Or at least the PR that introduced the fix so we can verify if it will work when released?

**Comment by JessyBAER** [comment]
@kiril-matev FYI I have got the warning with this sample https://plnkr.co/edit/p7lQoQoFEHKrULmO

![image](https://github.com/ag-grid/ag-grid/assets/125954509/66043cd4-f08d-4fac-97c9-36c147e59906)
