### ISSUE TITLE
How to download or install the enterprise version?

### ISSUE THREAD

**Issue by Tony20221** [ag-grid/ag-grid#6059]
Where's the enterprise version? The README just mentions the community version. There's a download counter for the enterprise version yet I can't figure out how to download it.

There are no download links on ag-grid.com's home page. Every software company in the world needs to have an easy to find download link on the home page.
 I used search and used 'download' and nothing. I went to the getting started page and nothing about how to download. Isn't the first step to getting started for a piece software is to download and install it? 

Why is this basic information so hard to find!???

**Comment by StephenCooper** [comment]
Hi Tony,

Thanks for your feedback. I can see we can make this clearer on the getting started page. 

This is the link to use enterprise if you are not downloading from npm.

Just place this in your index.html file like in this [example](https://plnkr.co/edit/RnZDup9cnSm9weu3?open=main.js). 

```
<script src="https://cdn.jsdelivr.net/npm/ag-grid-enterprise@29.0.0/dist/ag-grid-enterprise.min.js">
		</script
```
