### ISSUE TITLE
valueFormatter for group cell receives string representation of value for non-string values

### ISSUE THREAD

**Issue by GideonMax** [ag-grid/ag-grid#6077]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/UZBmjTkkCbhlMLKm
this table has a boolean value called `someBoolean`, this value is also being used for row grouping.
But the value formatting for this boolean value isn't working for group cells.

**Current behavior**
valueFormatter receives a string instead of the actual value (in this case a boolean), when formatting for a group cell.

**Expected behavior**
valueFormatter should always receive the actual value, instead of its string representation

* **AG Grid version:** 29.0.0 (latest as of writing)

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

* **Language:** all

**Comment by StephenCooper** [comment]
Hi @GideonMax,

This is the way that grouping works, strings are used to compare values as you can see from the docs which talk about how to handle complex objects and returning string.

https://ag-grid.com/javascript-data-grid/grouping-complex-objects/#creating-group-keys-from-complex-objects

Feel free to raise as a feature request via your ZenDesk account.
