### ISSUE TITLE
ag-grid-vue3 headerComponent being duplicated onGridSizeChanged in newer versions of Vue3

### ISSUE THREAD

**Issue by CryHavok01** [ag-grid/ag-grid#6079]
ag-grid-vue3 Version: 27.3.0
Browser: Chrome Version 109.0.5414.87
Language: Javascript, Vue3

Our app is using ag-grid-vue3 to display a scheduling calendar.  Each date column has custom headerComponent, as can be seen in columnDefs here:
```
    const columnDefs = computed(() => {
      const columns = [
        {
          headerComponent: "CalendarNavigationCell",
          headerComponentParams: {
            date: firstVisibleDate.value,
            onNavigationCellDateSelected,
          },
          field: "name",
          pinned: "left",
          lockPosition: true,
          lockPinned: true,
          width: PRO_COLUMN_WIDTH,
          headerClass: "overflow-visible",
          cellRenderer: "CalendarProCell",
          cellStyle: {
            display: "flex ",
            "align-items": "center ",
          },
        },
      ];
      for (const date of dates.value) {
        const id = columnIdForDate(date);
        columns.push({
          colId: id,
          headerComponent: "CalendarDayHeader",
          headerComponentParams: {
            date,
            utilization: utilizationsByDateColumnId.value[id],
            forecast: forecasts.value[id] ? forecasts.value[id] : null,
          },
          field: id,
          lockPosition: true,
          width: dateColumnWidth.value,
          minWidth: MIN_DATE_COLUMN_WIDTH,
          maxWidth: MAX_DATE_COLUMN_WIDTH,
          cellRenderer: "CalendarDayCell",
          cellRendererParams: {
            onAddNewOptionClicked: (event) => emit("clickedAddNew", event),
          },
        });
      }
      return columns;
    });
```

We adjust the width of each column when the screen size changes so that there will generally be 5 columns visible at all times.  In vue versions 3.2.33 or lower, this works correctly, and the columns and headers adjust their sizes correctly.  However, in vue versions 3.2.34 and up, there is an issue where the headerComponent on each column is being duplicated every time the screen size changes.  This only effects the column headers, not the columns themselves.  This can easily be seen by inspecting the dom via Chrome's developer tools.  In lower vue versions, there are clearly an appropriate number of children elements in the `ag-header-row`.
<img width="1266" alt="Screenshot 2023-01-25 at 4 10 24 PM" src="https://user-images.githubusercontent.com/71348370/214691514-436ea483-f46c-40b2-a943-3a14d46d887c.png">
Scrolling the grid or changing the size of the window will alter which columns are shown, or the width of the columns, but it does not change the number of columns or children elements.  In versions of vue above 3.2.34, however, every time the column width changes, rather than replacing the existing `ag-header-cell` elements, ag-grid instead adds new `ag-header-cell` elements with updated widths.  This quickly results in dozens of overlapping children elements of `ag-header-row.`
<img width="1268" alt="Screenshot 2023-01-25 at 4 15 40 PM" src="https://user-images.githubusercontent.com/71348370/214692600-dfb2ea16-7ad0-4689-8df5-31f8cdba7e37.png">

Here are our gridOptions and onGridSizeChanged fuction:
```
    const gridOptions = computed(() => ({
      columnDefs: columnDefs.value,
      rowData: rowData.value,
      onGridReady,
      onGridColumnsChanged,
      onGridSizeChanged,
      onBodyScroll,
      headerHeight: 118,
      suppressRowHoverHighlight: true,
      suppressRowTransform: true,
      suppressCellFocus: true,
      suppressHorizontalScroll: true,
      getRowId,
      getRowHeight: (params) => getRowHeightFromEvents(params),
      noRowsOverlayComponent: NoResultsOverlay,
      noRowsOverlayComponentParams: {
        title: "No results found",
      },
    }));

    const onGridSizeChanged = async (event) => {
      const previousFirstVisibleColumnId =
        firstVisibleColumn.value?.colId ?? dateRangeCenterColumnId.value;

      dateColumnsTotalWidth.value = event.clientWidth - PRO_COLUMN_WIDTH;

      await nextTick();

      updateVisibleColumns();
      event.api.ensureColumnVisible(previousFirstVisibleColumnId, "start");
    };

    const updateVisibleColumns = () => {
      const virtualColumns =
        gridColumnApi.value.getAllDisplayedVirtualColumns();
      visibleColumns.value = virtualColumns.filter(
        (c) =>
          c.left + c.actualWidth >
            xScrollOffset + VISIBLE_COLUMN_PIXEL_BUFFER &&
          c.left <
            xScrollOffset +
              dateColumnsTotalWidth.value -
              VISIBLE_COLUMN_PIXEL_BUFFER
      );
      return visibleColumns.value;
    };

```

**Comment by StephenCooper** [comment]
Hi @CryHavok01,

As a first step can you please confirm if this is still an issue in AG Grid v29?

**Comment by CryHavok01** [comment]
Yes, this is still happening in ag-grid-vue 29.0.0

**Comment by seanlandsman** [comment]
@CryHavok01 can you please provide a reproducible example and I'll take a look - thanks

**Comment by StephenCooper** [comment]
Feel free to open with a reproduction.
