### ISSUE TITLE
Drag and drop rows between more than two Grids and Grids are dynamically remove-able and add-able

### ISSUE THREAD

**Issue by itpixelz** [ag-grid/ag-grid#6086]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
Here is an example of dragging/dropping rows between two Grids but I want a solution for more than 2 and the total number of Grids is in a dynamic Array.

**Expected behavior**
I am displaying multiple dynamically generated AG Grid tables on one component in Angular.
I want to drag/drop rows from one AgGrid to any of the other available Grids. 

**Please tell us about your environment:**
Angular

* **AG Grid version:** 28.1.1

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
I would expect that you could use this example as a basis for how to achieve this.

https://www.ag-grid.com/javascript-data-grid/drag-and-drop/#example-two-grids

You will need to manage the drag and drop yourself as the built in grid to grid is only for two grids.
