### ISSUE TITLE
AG-Grid not loading on iFrame

### ISSUE THREAD

**Issue by FrederikFricke** [ag-grid/ag-grid#6098]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
On first loading of the iFrame the AG-Grid throws an error which causes a blank page on a react app. If react app loads a site which doesn't include an AG-Grid and changes to the AG-Grid site without rebuilding the complete iFrame, it shows without any errors. 

![Bildschirm­foto 2023-01-30 um 08 17 12](https://user-images.githubusercontent.com/110379948/215454492-75bde5da-aa61-408f-819b-98a86102b40b.png)

**Expected behavior**
The AG-Grid loads normally without errors and the React-Page ist showing.

**Please tell us about your environment:**
OS: MacOS 13.0
VSCode was used for development

* **AG-Grid-Community version:** ^27.1.0
* **AG-Grid-React version:** ^27.1.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

* **Language:** [TypeScript ^4.2.4]

**Comment by StephenCooper** [comment]
Hi @FrederikFricke,

We would need a reproduction to work off before we can investigate this further. Could you please provide one?

**Comment by FrederikFricke** [comment]
On trying to reproduce this behaviour we weren't able to do so. After further investigation we managed to have a working solution. This issue can be closed.
