### ISSUE TITLE
Sass Styling API - Unable to override certain variables

### ISSUE THREAD

**Issue by AVelickovski** [ag-grid/ag-grid#6113]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
I am working on an Angular 15 project that uses ag-grid with Sass and recently upgraded to the latest version of ag-grid, v29.0.0.
I installed the `@ag-grid-community/styles` package as it is now required when using modules and followed the [documentation](https://www.ag-grid.com/angular-data-grid/global-style-customisation-sass/) to set it up with Sass. 

When I tried to override certain variables, like the `--ag-borders`, 
![image](https://user-images.githubusercontent.com/12114114/216073707-641c7497-c987-4048-8467-56b7f14b243b.png)

I am getting the following error in the terminal
![image](https://user-images.githubusercontent.com/12114114/216074130-7017c3c4-6401-48c6-902c-ba5ece04a6f5.png)

However, if I put `--ag-borders: solid 0px` then it works as it should. Worth mentioning is that `false` also does not work as a value, presumably because it is converted to `none` internally.

Another problem occurred when I tried to change the color of a variable, for example, the `--ag-foreground-color`, using a custom property
![image](https://user-images.githubusercontent.com/12114114/216077767-063441d4-a52d-499f-bca7-f668515dced6.png)

I am getting the following error in the terminal
![image](https://user-images.githubusercontent.com/12114114/216077990-fed52ed4-b1ec-4ade-b997-e3076b65374a.png)

This used to work on previous versions of ag-grid.

**Current behavior**
Getting an error if I override the `--ag-borders` with `none` as a value and if I use custom properties to override the color of a variable

**Expected behavior**
There should be no error and the variables should be overridden with the desired values

**Please tell us about your environment:**
Windows 11, Visual Studio Code, Yarn

**AG Grid version:** 
29.0.0

**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Language:** 
Angular 15, Typescript 4.9.5

**Comment by StephenCooper** [comment]
hi @AVelickovski,

The ag-borders issue is being handled already under AG-7878.

As for the `foreground-color: var(--color-on-background)` issue this is not how we expect Sass themes to be used. The Sass theme should just accept preset colors. As an alternative it might be worth trying to use css variables directly that we now support meaning the custom theme is not really required anymore. 

For example see how this [example](https://ag-grid.com/javascript-data-grid/global-style-customisation-colours/#example-colour-customisation) works.
