### ISSUE TITLE
tooltipComponent can‘t use ui library ? 

### ISSUE THREAD

**Issue by Valar103769** [ag-grid/ag-grid#6119]
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/36926073/216228356-e39c25b7-feb6-44fd-8e17-0eb89cd4af32.png">

```jsx
import {
  Text,
  Tooltip,
} from '@mantine/core'

  const defaultColDef = useMemo<ColDef>(
    () => ({
      sortable: true,
      resizable: true,
      tooltipComponent: (params) => {
        console.log('params', params)
        const { tooltipField, field } = params.colDef
        const row = params.data
        console.log('row[field]', row[field])

        return (
          <Tooltip label={row[tooltipField]}>
            <Text>{row[field]}</Text>
          </Tooltip>
        )
      },
      ..._defaultColDef,
    }),
    [_defaultColDef]
  )
```

**Comment by StephenCooper** [comment]
Hi @Valar103769,

Github Issues is not the right place to ask application related questions and queries. I would suggest using StackOverflow or getting yourself an Enterprise license to unlock access to help that way.

We do not have the capacity to answer support type questions here, as I have commented on a number of your previous tickets.  We use github issues for bug reports only. 

I am sorry we cannot offer help for all your issues but I hope you understand we have limited capacity.
