### ISSUE TITLE
Can't resolve  '~ag-grid-community/dist/styles/ag-grid.css'

### ISSUE THREAD

**Issue by changhuixu** [ag-grid/ag-grid#6124]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

```css
// in Angular styles.css file
@import '~ag-grid-community/dist/styles/ag-grid.css';
@import '~ag-grid-community/dist/styles/ag-theme-alpine.css';
```
The Angular project couldn't build due to not able to resolve the css file in ag-grid.
![image](https://user-images.githubusercontent.com/16184464/216845076-8209f62e-4eb2-4661-9526-4c1faddbc8f8.png)

**Expected behavior**

It should build as before.

**Please tell us about your environment:**

* **AG Grid version:** v29.0.0

**Comment by StephenCooper** [comment]
Please see the upgrade instructions at the following link to resolve this issue.

https://www.ag-grid.com/javascript-data-grid/global-style-upgrading-to-v28-css/

**Comment by changhuixu** [comment]
Thank you. So the path to css files are changed. The correct ones are as follows:

```css
@import '~ag-grid-community/styles/ag-grid.css';
@import '~ag-grid-community/styles/ag-theme-alpine.css';
```

After correcting the css file paths, the solution builds successfully.

**Comment by waratah** [comment]
I had to `npm i @ag-grid-community/styles@latest`

This installed the style sheets so they can then be included.

Just in case someone else ends up here, wondering like I did.

**Comment by umutsesen** [comment]
```
import '@ag-grid-community/styles/ag-grid.css';
import '@ag-grid-community/styles/ag-theme-alpine.css';
```

fixes the issue.

**Comment by HussainRaza97** [comment]
You can navigate into node Modules, 
paths has been changed in Ag-Grid ^29+ versions. 

`// old imports in Angular styles.css file
@import '~ag-grid-community/dist/styles/ag-grid.css';
@import '~ag-grid-community/dist/styles/ag-theme-alpine.css';`


just remove dist from path, it will work. 

``// New imports in Angular styles.css file
@import '~ag-grid-community/styles/ag-grid.css';
@import '~ag-grid-community/styles/ag-theme-alpine.css';``

**Comment by ShrikaranKanagaraj** [comment]
> I had to `npm i @ag-grid-community/styles@latest`
> 
> This installed the style sheets so they can then be included.
> 
> Just in case someone else ends up here, wondering like I did.

yeah, It worked for my case. 

React Version: 18.x.x
Ag Grid Version: 30.x.x

**Comment by ENate** [comment]
H there,
Does anyone know why the following theme 
```
//  1)  @import "~@ag-grid-community/core/dist/styles/ag-grid.css";
// 2)  @import "~@ag-grid-community/core/dist/styles/ag-theme-balham/sass/ag-theme-balham-mixin";
```
can no longer work? It seems replacing 1) with 3) below works. But the ``àg-theme-balham-mixin```does not exist anymore? I am migrating some old codes in Angular. Any help will be highly appreciated:

```
/* Core Data Grid CSS */
3)  @import 'ag-grid-community/styles/ag-grid.css';
```

Thanking.

**Comment by jiangtao69039** [comment]
> H there, Does anyone know why the following theme
> 
> ```
> //  1)  @import "~@ag-grid-community/core/dist/styles/ag-grid.css";
> // 2)  @import "~@ag-grid-community/core/dist/styles/ag-theme-balham/sass/ag-theme-balham-mixin";
> ```
> 
> can no longer work? It seems replacing 1) with 3) below works. But the ``àg-theme-balham-mixin```does not exist anymore? I am migrating some old codes in Angular. Any help will be highly appreciated:
> 
> ```
> /* Core Data Grid CSS */
> 3)  @import 'ag-grid-community/styles/ag-grid.css';
> ```
> 
> Thanking.

Did you solve this problem?

**Comment by ENate** [comment]
@jiangtao69039 Not yet. But I just used other themes for now.
