### ISSUE TITLE
Save/Restore chart: Official sample not working anymore

### ISSUE THREAD

**Issue by spyro2000** [ag-grid/ag-grid#6127]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

See https://www.ag-grid.com/angular-data-grid/integrated-charts-api-save-restore-charts/

**Current behavior**
Chart does not render

**Expected behavior**
Chart should render

**Please tell us about your environment:**
Chrome 109.0.5414.120

* **AG Grid version:** (not using local version)

**Comment by StephenCooper** [comment]
The way the example is setup at the moment is that a chart is not rendered by default. Instead you need to create a chart via selecting a range in the grid and right clicking to open the chart context menu.

I can see why this example looks broken so I am going to update it to have a chart created by default. This way you can immediately start making / saving changes.

Thanks for pointing this out.
