### ISSUE TITLE
Filter Popup: Reset button partially hidden

### ISSUE THREAD

**Issue by liluhe** [ag-grid/ag-grid#6131]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[] feature request 
[] support request 
```
**Providing a Reproducible Scenario**
- A plunker : 
   https://plnkr.co/edit/K0laONqgoimzS5sU?open=index.jsx

Current behaviour 
Testing with a grid with height <= 280 px aprox.
1.  Open a filter window (Make column)
2. Type values in first input (AND/OR section is shown, with another input is added to filter window)
3. Even if we scroll, "Reset" button is partially hidden.
 
Expected behaviour. 
"Reset" button should be completely visible. 

**Please tell us about your environment:**

* **AG Grid version:** 29.0.0
![FilterIssue](https://user-images.githubusercontent.com/41053301/217262713-944ab705-b0dc-450f-9b91-55834afa54e0.PNG)
* **Browser:**
Chrome Version 109.0.5414.120

**Comment by StephenCooper** [comment]
Please refer to this part of our documentation for the fix for this via `popupParent`

https://ag-grid.com/javascript-data-grid/context-menu/#popup-parent

```
  const popupParent = useMemo(() => {
    return document.querySelector('body');
  }, []);

  return (
    <div style={containerStyle}>
      <div style={gridStyle} className="ag-theme-alpine">
        <AgGridReact
          rowData={rowData}
          columnDefs={columnDefs}
          popupParent={popupParent}
        ></AgGridReact>
      </div>
```
