### ISSUE TITLE
[Question] License

### ISSUE THREAD

**Issue by YourWifeCallYou** [ag-grid/ag-grid#6135]
i have a paid subscription for AG Grid Enterprise , for single application.
What will be the implication, if the second application hop on and used that license?

Can my organization use AG Grid Enterprise and also AG Grid community at the same time, each for different application?

If an application uses AG Grid community license, possible for that application deployed within our organization, or does it need to be upgraded to AG Grid Enterprise?

Thank you.

**Comment by StephenCooper** [comment]
Please contact us on [info@ag-grid.com](mailto:info@ag-grid.com) and the correct team will be able to assist you with this.
