### ISSUE TITLE
Documentation for autoSizePadding has incorrect default

### ISSUE THREAD

**Issue by sersorrel** [ag-grid/ag-grid#6136]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

The [documentation](https://www.ag-grid.com/vue-data-grid/grid-options/#reference-columnSizing-autoSizePadding) states that the default value of `autoSizePadding` is `4`. (this assertion was added in 2021, cdc0bdc7dda979c630ab04e7b0592f2522096c67)

**Expected behavior**

[Currently](https://github.com/ag-grid/ag-grid/blob/d8dcba3fad4651d78208063ab9d4524a14c835ba/community-modules/core/src/ts/rendering/autoWidthCalculator.ts#L86) (maybe even since 4a8712748b2cd6aaa029b58565303dc13da0a6f7 in 2018?), the default value of `autoSizePadding` is `20`.

**Comment by StephenCooper** [comment]
Thank you very much for letting us know about this! I have made the correction now ready for our next release.
