### ISSUE TITLE
Changes to EventService.dispatchEvent function may cause loss of context value

### ISSUE THREAD

**Issue by JasonTheProgrammer** [ag-grid/ag-grid#6139]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The treatment of the `context` property has changed in event dispatching, such that it's no longer possible to set it in a `valueSetter` callback, and receive it in event handlers.

In v25.1.0, per [this Plunker](https://plnkr.co/edit/UkCT5IcwiQ1FRyrx?preview), I can set the value of `context` like this:

    valueSetter: (params) => {
      params.data[params.colDef.field] = params.newValue;
      params.context = 'context set by valueSetter';
    }

That context value will be present on the params passed to an `onCellValueChanged` event handler.

But in v29.0.0, per [this Plunker](https://plnkr.co/edit/qq5tmDCEz2iuEZVn), the context comes through to the event handler as `undefined`.

I believe it's [this commit](https://github.com/ag-grid/ag-grid/commit/4f6372be751b2df58159481938efca388c31935e) that has caused the change in behaviour, with a change to the `dispatchEvent` function in eventService.ts. It's explicitly setting `context` by taking it from `gridOptionsWrapper`, rather than using the value from the provided event, as was happening previously.

Instead of overriding the `context` property, perhaps this function could instead check whether the property is already defined, and only get it from `gridOptionsWrapper` if undefined / null. E.g. `context: event.context || this.gridOptionsWrapper.getContext()`. This would mean use cases of `context` that were viable in old versions would continue to work, but would still meet the desire of getting `context` from grid options if it's *not* been set otherwise.

For what it's worth, I worked around this change of behaviour by having my `valueSetter` take on some of the work that my `onCellValueChanged` event handler was responsible for.

**Current behavior**
A context value set in a column `valueSetter` function, doesn't flow through to an `onCellValueChanged` event handler.

**Expected behavior**
Context values set in a column `valueSetter` function should flow through to event handlers, including `onCellValueChanged`. In earlier versions, this *was* the behaviour.

* **AG Grid version:** 29.0.0 (but also some versions of 28.x)

**Comment by StephenCooper** [comment]
Hi @JasonTheProgrammer,

This is a novel use of this feature that is not what it was intended for. However, you can still achieve this behaviour with a few changes. See this updated [plunker](https://plnkr.co/edit/voUFIsX6v7pT1IqX).

Basically comes down to setting the context to an object and then making changes within that object. The reference is maintained enabling this to work.
