### ISSUE TITLE
Usages of RowNode<T> in ag-grid v29

### ISSUE THREAD

**Issue by isobel-cullen** [ag-grid/ag-grid#6144]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Not really a support request, just notifying the ag-grid team that my company makes use of the `childrenAfterAggFilter` property which is not on `IRowNode` and the `setSelectedParams` function on `RowNode` in one place in order to supply the `rangeSelect` parameter.

**Comment by StephenCooper** [comment]
Hi @isobel-cullen,

Thanks for letting us know. I think you can use alternative public apis.

The gridApi method `forEachNodeAfterFilter` internally uses `childrenAfterAggFilter `.
https://ag-grid.com/javascript-data-grid/grid-api/#reference-rowNodes-forEachNodeAfterFilter

In terms of `setSelectedParams` there is a corresponding `setSelected` method which should be equivalent.

**Comment by isobel-cullen** [comment]
@StephenCooper [setSelected](https://www.ag-grid.com/javascript-data-grid/row-object/#reference-rowNodeMethods-setSelected) has no way to pass in [rangeSelect](https://github.com/ag-grid/ag-grid/blob/latest/grid-community-modules/core/src/ts/interfaces/iRowNode.ts#L35) that I can see, nor is there any public api on `IRowNode<T>` that accepts a `SetSelectedParams`

**Comment by StephenCooper** [comment]
Yes you are correct. I will re-open this ticket as it looks like we may need to reconsider which methods we expose here as I can see you have lost `rangeSelect` from the public api.

In the meantime you will need to cast to `RowNode` to access the `setSelected` method that takes the params.

**Comment by StephenCooper** [comment]
Created an internal ticket AG-8076 so actually I am going to leave this closed, but will comment when we decide how we will resolve this.

**Comment by flex-boram** [comment]
@StephenCooper  This causes a type error, but it still works. When do you intend to fix this?
And I can't find the AG-8076.

**Comment by StephenCooper** [comment]
We will be updating this interface as part of v30 which is a few weeks away from being released.
