### ISSUE TITLE
solid-new.svg bad filename gets deleted immediately by git

### ISSUE THREAD

**Issue by matsondawson** [ag-grid/ag-grid#6147]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

There's a file with a bad filename in the repository called ag-grid/grid-packages/ag-grid-docs/documentation/src/images/fw-logos/solid-new.svg:Zone.Identifier

The :Zone.Identifier on the end causes windows github (at least) to delete the file immediately, which makes it hard to clone/create PR's on windows.

Can this be renamed?

**Current behavior**
Git clones, but deletes file.  There's no way to retain it.

```
C:\mygit\ag>git status
On branch latest
Your branch is up to date with 'origin/latest'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    grid-packages/ag-grid-docs/documentation/src/images/fw-logos/solid-new.svg:Zone.Identifier
```

**Expected behavior**
Git does not delete file because of bad filename.

**Please tell us about your environment:**
Windows 10 and 11.
Github desktop 3.1.2 and git 2.23.0.windows.1

* **AG Grid version:** X.X.X
Latest 29.0.0

* **Browser:**
Not relevant

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Not relevant

**Comment by StephenCooper** [comment]
I have deleted the file :)
