### ISSUE TITLE
agGroupCellRenderer crashes on expand solidjs 

### ISSUE THREAD

**Issue by Hen2609** [ag-grid/ag-grid#6153]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

**Current behavior**
I've tried to experiment with MasterData feature (trying out enterprise features) in solidjs, following the code example from here: 
https://www.ag-grid.com/react-data-grid/master-detail/ when I try to expand. the rows I get error thrown by solid mechanisem: 
**first error:** `Uncaught TypeError: Comp is not a function`, 
**second error:** `Uncaught Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.`
the only happens when I use `cellRenderer = 'agGroupCellRenderer'`
**detailGridOptions I used for testing the subgrid**
it never reaches the console log, the grid appears empty.
```
detailGridOptions: {
            columnDefs: [
                {field: 'test'}
            ]
        },
        getDetailRowData: (params) => {
            console.log('parms',params)
            return [
                {test: 'testing'}
            ]

        }
```
**Please tell us about your environment:**
macOs 13.2
node 16.17
"@ag-grid-enterprise/master-detail": "^29.0.0",
    "ag-grid-community": "^29.0.0",
    "ag-grid-enterprise": "^29.0.0",
    "ag-grid-solid": "^29.0.0",
    "solid-js": "^1.6.10"

* **Browser:**
brave brrowser: v1.48.158
* **Language:** [TypeScript 4.9 ]

**Comment by StephenCooper** [comment]
First thing to check is that you are not mixing modules and packages. You should not need to have the master detail module `"@ag-grid-enterprise/master-detail": "^29.0.0",` as well as the `ag-grid-enterprise` package.

The package already contains the master detail feature. That would be the first thing to check. 

Otherwise we would need a reproduction to file a bug report.

**Comment by Hen2609** [comment]
Hi, everything is working, Idk how I got there but I followed this: https://www.ag-grid.com/javascript-data-grid/modules/ to activate it 🤦.
just importing `ag-grid-enterprise` made everything work as expected
