### ISSUE TITLE
[Bug]: ColumnsToolPanelModule should be ColumnToolPanelModule

### ISSUE THREAD

**Issue by NikitaIT** [ag-grid/ag-grid#6155]
## Incorrect Warning

>    import { **Column**ToolPanelModule } from '@ag-grid-enterprise/**column**-tool-panel';

https://github.com/ag-grid/ag-grid/blob/93841bb029bbafe2600a7559e27ac393575152c8/enterprise-modules/column-tool-panel/src/main.ts#L1

## Warning

> AG Grid: unable to use Column Tool Panel as the ColumnToolPanelModule is not registered. Check if you have registered the module:
>           
>    import { ModuleRegistry } from '@ag-grid-community/core';
>    import { **Column**ToolPanelModule } from '@ag-grid-enterprise/**column**-tool-panel';
>    
>    ModuleRegistry.registerModules([ ColumnToolPanelModule ]);
>
> For more info see: https://www.ag-grid.com/javascript-grid/modules/

https://github.com/ag-grid/ag-grid/blob/f46340886c49f0513e6c2599d7a0d119d506c96a/community-modules/core/src/ts/modules/moduleRegistry.ts#L98

**Comment by StephenCooper** [comment]
Thank you for reporting this. I have raised AG-8019 to carefully correct this and validate all the other modules names used. 

As this is now tracked internally I am going to close this issue.
