### ISSUE TITLE
Horizontal scroll with pinned column

### ISSUE THREAD

**Issue by amal-k-dev** [ag-grid/ag-grid#6163]
Hi!

I am using Ag-Grid community(Angular) with an infinite scroll row-model. I got a scenario where I need horizontal scroll with left pinned column. I don't see any configuration. Is there any fix or any workaround?. Can someone provide any information on this?

NB: I am trying to make the grid just like Excel

**Dependencies**
angular : 9.1.12
ag-grid-angular-legacy : 28.0.0
ag-grid-community : 28.0.0

Thanks in advance!

**Comment by StephenCooper** [comment]
You do this with the following config in your column def.

```
{ field: 'athlete', pinned: true, minWidth: 150 },
```

https://plnkr.co/edit/nf5GjFRGTAbXpvHc?open=app%2Fapp.component.ts

**Comment by amal-k-dev** [comment]
Hi Stephen,

Thanks for your reply. Unfortunately this is not what I meant. I need
a scroll bar inside the pinned pane. I am trying to pin multiple
columns.
try this in your example

{ field: 'athlete', pinned: true, minWidth: 150 },
{ field: 'age', pinned: true },
{ field: 'country',  pinned: true, minWidth: 150 },
{ field: 'year', pinned: true },
{ field: 'date', pinned: true, minWidth: 150 }

The scroll bar will disappear. to solve this i need to set a max width
for pinned left pane and a scroll bar.

**Comment by StephenCooper** [comment]
Ah right ok. In that case this is an outstanding feature request which is tracked by the following ticket. 

**AG-3915 [Column Pinning] Allow setting maxWidth for pinned columns area (smaller than viewport) and horizontal scrolling inside the pinned column area if total pinned column width is greater than pinned area width**

**Comment by StepPointer** [comment]
Ye I found the Ticket but it not look like this... they did not implement it. They jsut create the solution to resize the columns and limit it by the pinned area width and recalculate width.

Ticket now look like this
AG-3915 [Column Pinning] Allow automatically unpinning/preventing the pinning of grid columns when total pinned width exceeds grid width

But solution to anaibling the scroll for pinned columns is still needed... Just escalated it to the menegment, hope in future releases they will add this functionality *fingers crossed*
