### ISSUE TITLE
Globale configuration for all application grids

### ISSUE THREAD

**Issue by Quentigus** [ag-grid/ag-grid#6170]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
We need to set same configuration, locale for example, on all ag-grid instances inside the application

**Expected behavior**
A way to provide a default configuration for all ag-grid instance inside the application (`AgGridModule.forRoot` or `InjectionToken`)

**Please tell us about your environment:**
* **AG Grid version:** 29 (Community)
* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
* **Application Framework:** Angular 12
* **Language:** TypeScript 4.3

**Comment by StephenCooper** [comment]
Hi @Quentigus,

We have this as an existing feature request under which has not been prioritised yet. I have linked this issue to that ticket.

 **AG-4892 [API] Add a statically-defined global Grid Options object to set a default configuration for all ag-grid instances** 

Current best workaround, which maybe you are already doing, would be to have a globally defined gridOptions object that you clone into local gridOptions configurations. 

```
// global.ts
const DEFAULT_GRID_OPTIONS: GridOptions = {}

//component.ts

const gridOptions: GridOptions = { ...DEFAULT_GRID_OPTIONS, /*. other local options*/}
<ag-grid-angular [gridOptions]="gridOptions">
```

**Comment by tw3** [comment]
This should be easy to implement guys...
