### ISSUE TITLE
Ag-grid throws errors when it is inside *ngIF

### ISSUE THREAD

**Issue by uthmanrahimi** [ag-grid/ag-grid#6177]
I am using `Ag-grid v 27.X` and sometimes I need to show and hide the grid based on a condition, for this I am using something like below:
```
<ng-container *ngIf="isLoaded">

      <ag-grid-angular [gridOptions]="gridOptions"  
                    (gridReady)="gridReady($event)" 
                   (selectionChange)="onSelectionChange($event)"
                   
                     [showCheckBoxSelection]="true"
                     ></ag-grid-angular>

    </ng-container>
```

based on some actions user does, the Grid is showing and hiding, the second time when the grid is showing, it throws below errors and grid retain previous data and not showing new data.

    maximum call stack size exceeded

and in component I have a InitGrid() which is called from ngOnInit.
```
initGrid() {
    this.gridOptions.columnDefs = [columns here]
}
```

When I removed the `*ngIf`, the grid is working fine and it does not showing the error. I searched and someone said in this way, the ag-grid creates a new instance each time, is there a way to destroy previous instances?

**Comment by StephenCooper** [comment]
Could you please provide a reproduction that mirrors your use case so that we can then investigate this for you.
