### ISSUE TITLE
Invoking onCellValueChanged() with argument of type NewValueParams in v28

### ISSUE THREAD

**Issue by Manish-Giri** [ag-grid/ag-grid#6178]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hi, I'm upgrading from version 20 to 28. In v20, the `onCellValueChanged` property of `ColDef` is just of type `Function` -

    /** Callbacks for editing.See editing section for further details. */
    onCellValueChanged?: Function;
   
There are several instances in my codebase where this function is being invoked manually, with various parameters of different types, such as `onCellValueChanged(id, params, change)`.

In the new version, `onCellValueChanged` has been changed to a function that expects an event of type `NewValueParams` explicitly. 

    /** Callback for after the value of a cell has changed, either due to editing or the application calling `api.setValue()`. */
    onCellValueChanged?: (event: NewValueParams<TData>) => void;
    
    
How can I implement this in the instances where `onCellValueChanged()` is being invoked manually, with the different parameters? Since it now expects only 1 argument of type `NewValueParams`. Would appreciate any help.
        
* **AG Grid version:** 28

**Comment by StephenCooper** [comment]
You will need to provide the parameters in the object form instead of individual arguments. The function still does the same thing under the hood.

**Comment by Manish-Giri** [comment]
@StephenCooper No matter what object I provide to the function, it keeps complaining about the missing parameters that are expected in type `NewValueParams`
```
is missing the following properties from type 'NewValueParams<any>': oldValue, node, data, column, and 4 more
```
Let's see the function was called originally (before v28) with `this.paramscolDef.onCellValueChanged(a, b, c);`

I tried something like
```typescript
const newValue = {a, b, c};
this.paramscolDef.onCellValueChanged(newValue);
```
and something like 
```typescript
const newValue: NewValueParams = {
  newValue: {a, b, c}
  };
this.paramscolDef.onCellValueChanged(newValue); // missing remaining types from NewValueParams  
```

**Comment by StephenCooper** [comment]
Can you show the type error in a code example for me to investigate?

**Comment by StephenCooper** [comment]
Just coming back to this ticket. You are not meant to be calling event handlers yourself. They should be used as follows

```
colDef: {
  onCellValueChanged: (params: NewValueParams) => {
     console.log("The new value is: ", params.newValue)
  }
}
```

Sorry I missed this when I originally responded.
