### ISSUE TITLE
jest tests fail due to jsdom bug

### ISSUE THREAD

**Issue by matttdawson** [ag-grid/ag-grid#6179]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When running jest tests ag-grid errors with:
```
TypeError: Cannot read properties of undefined (reading 'contains')
```
At: https://github.com/ag-grid/ag-grid/blob/a37508fb3fafeffe172ccb5ffafef5344fa02ff2/community-modules/core/src/ts/utils/dom.ts#L82

This is called from:
https://github.com/ag-grid/ag-grid/blob/4c26aa27dc4c0d1dce55db05ee842218f85e37a2/community-modules/core/src/ts/gridBodyComp/gridBodyCtrl.ts#L140-L143

Where relatedTarget:144 is cast as an HTMLElement, which _should_ be correct.
But, a bug in jsdom (https://github.com/jsdom/jsdom/issues/3509) is sending the relatedTarget as a document instead of HTMLElement, which has no classList thus causing the error.

It's unlikely that jsdom will be fixed quickly, or /even worse/ that the packages including jsdom will be updated quickly to include a fix. e.g. facebooks jest-environment-jsdom.
And, this is likely to be affecting other users who are using 28.0.0+ (It doesn't seem to affect 27.x)

A simple fix I've tested would be to add an optional ? to the line 82 of dom.ts / isElementOrClass.
```
if (element.classList?.contains(cls)) {
...
```

**Expected behavior**
Test does not throw exception due to relatedTarget being a document without a classList.

Technically I think this is not your fault, but without a fix upcoming in jsdom it would be appreciated if you could add the suggested change.

**Please tell us about your environment:**
Windows 10/11

* **AG Grid version:** X.X.X
28.x.x+

* **Browser:**
Running tests in node v16.15.1

* **Language:** [TypeScript 4.8.2 | ES6]

**Comment by StephenCooper** [comment]
Hi @matttdawson,

After looking into this we would be reluctant to update our code to work around the issue in Jsdom. Maybe there is another way that we can help you test what you are wanting to achieve?

**Comment by matttdawson** [comment]
I entirely understand, thanks for looking.

**Comment by swbartholomew** [comment]
Hi @matttdawson! 

What ended up being your solution to getting jests to pass? I think my team is experiencing this exact issue. Did you just stick to that simple fix in your post? Thanks so much.

**Comment by matttdawson** [comment]
Add this to your jest setupTests.tsx
```
beforeAll(() => {
  // @ts-ignore
  document.classList = { contains: () => false };
});
```
