### ISSUE TITLE
OHLC chart

### ISSUE THREAD

**Issue by jucasoft** [ag-grid/ag-grid#6199]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
I need to create a chart that is the composition of several charts, but in the ag-chart library I can't find one of the charts I need OHLC

**Providing a Reproducible Scenario**
I found in the ag-grid repository the source code for an OHLC chart, which has since been deleted:

https://github.com/ag-grid/ag-grid/commit/22263613e01522e5b744b20f5eebd933b469ba30#diff-8a87ee61b6b7df764b6a8c4be013fa7629ba058c2bed5733b978129913be98e5

was it removed because there is an undocumented alternative?

From this source code ono I was able to create a custom marker, but before continuing in the development I wanted to know if there is a ready-to-use component.

If I have to adopt another library, just to add a chart type, I don't see the point of keeping ag-chart charts.

I tried to grate a custom marker but I don't think it's good:
[angular-ag-grid-ohlc-chart](https://stackblitz.com/edit/angular-ag-grid-ohlc-chart?file=src/ohlc-marker.ts)

to create a new graph of type OHLC/CandleStick can you tell me which is the best direction?

**Current behavior**
typology of graphs incomplete, missing 2 important graphs in the financial area

**Expected behavior**
a new type of OHLC chart
[chart type documentation](https://datavizcatalogue.com/methods/OHLC_chart.html)

**Please tell us about your environment:**
angular 15
ag-grid 29 

* **AG Grid version:** 29@latest

* **Browser:**

* **Language:** TypeScript 4

**Comment by StephenCooper** [comment]
Hi @jucasoft,

Thanks for getting in touch and letting know what charts you would like in AG Charts. This is not currently supported. I have raised this with the charts team so that it will be on their roadmap to add but we cannot give a timeline as to when this will be implemented I am afraid. 

I am going to close the ticket now this is recorded internally.
