### ISSUE TITLE
[pagination] Make pagination panel extractable

### ISSUE THREAD

**Issue by juanrapoport** [ag-grid/ag-grid#62]
Hi!

It would be useful to make pagination panel extractable, that way you could place it anywhere in you app.

Thanks.

**Comment by ceolter** [comment]
Excellent idea.

**Comment by juanmav** [comment]
+1

**Comment by juanrapoport** [comment]
@ceolter The extractable panel was your idea, just copy & paste from your chat :smile: .

**Comment by ceolter** [comment]
Yea was trying to be funny!!

**Comment by JimmyBoh** [comment]
One point of consideration I'd like to bring up is the ability to internationalize/localize (all) the text built in to the grid. Is there any support for this? Maybe instead of extracting the panel just expose a paging API, then we can create our own UIs (with text) that just call in to the grid to change page, etc. (And still have an extractable panel, for simplicity/common use cases.)

**Comment by ceolter** [comment]
Re localisation, that's on my plan. Am surprised there hasn't been much chat requesting it!!!

**Comment by chiptus** [comment]
:+1:

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-42

**Comment by gregbown** [comment]
Typical requests from art or UI design have pagination above and below the data grid.  It would be nice to have the option of more than one.  Currently, I would have to modify source to implement this. Even if it wasn't external it would be nice to have pagination north and pagination south options. 
Thank you

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
