### ISSUE TITLE
Aggrid Accessibility issues

### ISSUE THREAD

**Issue by BhagyashriDhanak-web** [ag-grid/ag-grid#6200]
Hi Team,

I can not reproduce the accessibility issue on plunker, so I have reproduced that issue on html page.

Issue :
**When I was doing accessibility testing of AG Grid using Wave Tool then I found 8 issues in it.**

1.There are 8 Missing form label errors.

The issue of accessibility is being reproduced on this **aggrid_widthandmoredata1.html** page, but I have to host this page so where should I host it? so that you can see the accessibility issues.

please inform me as soon as possible where should I host this html page.

**Comment by jucasoft** [comment]
Hi,

I'm also trying to create an example page for accessibility issues
I'm using https://stackblitz.com/

do you need to load a static page?

let me know if you need help, I also have accessibility issues

**Comment by jucasoft** [comment]
> Hi Team,
> 
> I can not reproduce the accessibility issue on plunker, so I have reproduced that issue on html page.
> 
> Issue : **When I was doing accessibility testing of AG Grid using Wave Tool then I found 8 issues in it.**
> 
> 1.There are 8 Missing form label errors.
> 
> The issue of accessibility is being reproduced on this **aggrid_widthandmoredata1.html** page, but I have to host this page so where should I host it? so that you can see the accessibility issues.
> 
> please inform me as soon as possible where should I host this html page.

when you open a new issue, you will find instructions on how to share your code on plunker

**Comment by kiril-matev** [comment]
Hi @BhagyashriDhanak-web,

Thank you for using AG Grid.

In order to ensure any issues are processed quickly, please submit them following the AG Grid Github bug report template.

If you can't reproduce the issue in plunker, but you have an HTML file which shows the issue, simply attach it to a message in this thread by dragging it into the editor area. It'll be uploaded and attached to the thread.

We're looking forward to your response.

**Comment by BhagyashriDhanak-web** [comment]
When I am doing drag and drop the html page then I am getting this error:- **something went really wrong and we can't process that file**

**Comment by BhagyashriDhanak-web** [comment]
can you provide you mail id where I can attached my html page.

**Comment by kiril-matev** [comment]
Hi @BhagyashriDhanak-web.

Please upload it to your Dropbox, OneDrive or Google Drive and send a link to the file here.

**Comment by BhagyashriDhanak-web** [comment]
I can not share html page from my company laptop. I would prefer to set up one meeting with you regarding this issue.

**Comment by kiril-matev** [comment]
Hi @BhagyashriDhanak-web,

Please provide your email address and we'll contact you directly.
