### ISSUE TITLE
Nuxt 3 and Ag-grid

### ISSUE THREAD

**Issue by shaun-fitzgibbon** [ag-grid/ag-grid#6209]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
I have followed along with the Vue3  [getting-started page]( https://www.ag-grid.com/vue-data-grid/getting-started/) using Nuxt v3 framework instead of plain Vue 3

Install Nuxt 3 
yarn dev (Nuxt Site works)

yarn add ag-grid-community
yarn add ag-grid-vue3 (once this is installed nuxt no longer works, if uninstalled again Nuxt will work)
add and setup components as in the getting started guide
yarn dev (Nuxt site dosen't work)

Note that if ag-grid-vue3 is uninstalled Nuxt will work again just not with the Ag Grid as obviously it needs this to run.
also with ag-grid-vue3 installed the site will not work even if not using the AgGridVue component anywhere in the code yet.

**Current behavior**
As soon as I install ag-grid-vue3, Nuxt 3 displays below error,
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')                                                                                          11:01:00
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:76:16)  
  at callWithErrorHandling (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7176:29)  
  at setupComponent (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7131:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:450:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:16044:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./.nuxt/dev/index.mjs:16108:21

If I uninstall ag-grid-vue3 the site works again without the Ag Grid.

**Expected behavior**
The Site to work and display Ag Grid using Nuxt3 and Vue3

**Please tell us about your environment:**
macOS, Vscode, Yarn v3, Nuxt 3

* **AG Grid version:** X.X.X
29.1.0

* **Browser:**
Brave, Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by StephenCooper** [comment]
As a initial response does transpiling `ag-grid-vue3` as mentioned in the issue https://github.com/ag-grid/ag-grid/issues/3551 help resolve your issue?

**Comment by shaun-fitzgibbon** [comment]
@StephenCooper 
I added 
```js
 build: {
    transpile: ["ag-grid-vue"],
  },
```
to my nuxt config file but didn't seem to do anything, still getting the same error

**Comment by StephenCooper** [comment]
Thanks for trying that initially. I think the best next steps would be if
you can provide a minimal GitHub repo that shows the error that we can
clone and use to investigate.

Hopefully this shouldn't be too tricky based on your reproduction steps
above.

**Comment by shaun-fitzgibbon** [comment]
@StephenCooper thanks for trying to help.
In the process of making a minimal github repo It started working correctly, must be due to an update in code 
so Ive updated my project to the newer version and all is working now 

Thanks

**Comment by StephenCooper** [comment]
Thank you for letting me know as hopefully this will serve as a solution to others too.
