### ISSUE TITLE
Context menu popupParent property not working correctly when using Angular Material Dialog on top of another Angular Material Dialog

### ISSUE THREAD

**Issue by kunal-epsc** [ag-grid/ag-grid#6224]
I'm submitting a... 
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
................................................................................................................................................................................................................................................
**Providing a Reproducible Scenario**

  Basic Setup: 
  1) Create a button to lauch a matDialog box. 
  -> This dialog box should have an implementation of AG Grid. 
  -> popupParent: <HTMLElement>document.querySelector('mat-dialog-container')

  2) Add a button in this dialog box to launch another dialog box. (dialog on top of dialog) 
  -> This dialog box should have an implementation of AG Grid.
  -> Add a panelClass for identification,
          Example:    
          this.matDialog.open(SecondDialogComponent, {
              width: '250px',
              height: '160px',
              panelClass: 'popup-test'
          });
  -> popupParent: <HTMLElement>document.querySelector('popup-test')

  Note: We are adding panelClass because we can not use the 'mat-dialog-container' class for second dialog box

  Resource:
  1) https://material.angular.io/components/dialog/overview

..................................................................................................................................................................................................................................................
**Current behavior**
   
   1) Dialog One: Right click on the grid
    Observed: The context menu is positioned on top of the grid

![context-dialog-one](https://user-images.githubusercontent.com/99380988/221482407-7a80fe59-568b-4499-b182-6bf46fe7f4d2.png)

    2) Dialog Two: Right click ont the grid
    Observed: The context menu is contained within the grid

![context-dialog-two](https://user-images.githubusercontent.com/99380988/221485345-ee3499e5-3479-4b1d-a8cc-8e29113cce4a.png)

..................................................................................................................................................................................................................................................
**Expected behavior**
  
   The context menu styling should be consistent. This used to work in the following version of Ag-Grid
   "ag-grid-angular": "27.0.0",
    "ag-grid-community": "27.0.1",
    "ag-grid-enterprise": "27.0.1",

................................................................................................................................................................................................................................................
Environment:
  Windows, VSCode

................................................................................................................................................................................................................................................
AG Grid version:
 "ag-grid-angular": "28.1.1",
 "ag-grid-community": "28.1.1",
 "ag-grid-enterprise": "28.1.3",

................................................................................................................................................................................................................................................
Browser:
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'

................................................................................................................................................................................................................................................
Language: 
 Typescript

**Comment by StephenCooper** [comment]
Could you please provide a reproduction so that we can investigate this please?

**Comment by kunal-epsc** [comment]
[popupParentIssue.webm](https://user-images.githubusercontent.com/99380988/222057391-962c94f2-0a71-4c78-ae0b-38835671b4f3.webm)

Please let me know if any additional details are required.

**Comment by kunal-epsc** [comment]
Hello, any updates?

**Comment by StephenCooper** [comment]
Hi @kunal-epsc,

Your repo does not contain any uses of popupParent. Also please be aware that we do not offer support via Github and I cannot see that this is a bug with popupParent but maybe just an issue with selecting the correct parent in your application. 

If you want further support and help that will need to be requested via our enterprise support system. 
<hr>

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
