### ISSUE TITLE
Once the charts dialog is open and options are expanded, when closed, you cannot drag&drop columns anymore

### ISSUE THREAD

**Issue by danibasauri** [ag-grid/ag-grid#6231]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

We have an enterprise license, but do not have credentials to log in to Zendesk.

**Providing a Reproducible Scenario**
https://www.ag-grid.com/angular-data-grid/integrated-charts-range-chart/#example-defining-categories-and-series

https://user-images.githubusercontent.com/5106997/221917225-ebf3e9e4-6c99-4755-935e-26f0e2f06e0d.mov

**Current behavior**
Select some cells and right click to select the "Line" chart range. Once the chart dialog is open, click on the right arrow to expand the chart options. Once this is done, close the chart dialog and try to drag and drop a column to move it to another place. Just when this is done, the following error appears in the console and it won't be possible to drag and drop columns anymore:

`ERROR TypeError: Cannot read properties of undefined (reading 'getGui')
    at Object.getContainer (charts.cjs.min.js:11:550557)
    at t.getAllContainersFromDropTarget (core.cjs.min.js:206:121179)
    at t.isMouseOnDropTarget (core.cjs.min.js:206:121674)
    at eval (core.cjs.min.js:206:120540)
    at Array.filter (<anonymous>)
    at t.onDragging (core.cjs.min.js:206:120511)
    at o.onCommonMove (core.cjs.min.js:226:4058)
    at o.onMouseMove (core.cjs.min.js:226:4474)
    at HTMLDocument.listener (core.cjs.min.js:226:2959)
    at e.invokeTask (zone.min.js:13:7855)`

**Expected behavior**
The error should not occur, and you would still be able to drag and drop columns after closing the chart dialog.

* **AG Grid version:**  
28.2.1
29.0.0
29.1.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'

**Comment by StephenCooper** [comment]
Thank you for reporting this and providing a clear reproduction for us. I have raised this internally.

**Comment by StephenCooper** [comment]
AG-8124 [Integrated Charts] Chart Tool Panel is not destroyed correctly leading to exceptions being thrown

 
Note that this is part of the next release and it is scheduled in 4-6 weeks.
