### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not callable when running in jsdom

### ISSUE THREAD

**Issue by yrral86** [ag-grid/ag-grid#6245]
**I'm submitting a Bug Report**

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Code
```
import { JSDOM } from 'jsdom'
import * as vm from 'vm'
import { ColDef, Grid, GridOptions, ModuleRegistry, RowNode } from '@ag-grid-community/core'
import { ClientSideRowModelModule } from "@ag-grid-community/client-side-row-model"

ModuleRegistry.registerModules([
  ClientSideRowModelModule
])

export const agGridFactory = () => {
  const dom = new JSDOM('', { runScripts: "outside-only" })

  const rowData: any[] = []
  const gridOptions: GridOptions = {
    columnDefs: [],
    rowData
  }

  const context = dom.getInternalVMContext()
  context['Grid'] = Grid
  context['gridOptions'] = gridOptions

  const script = new vm.Script(`
    const div = document.createElement('div')
    if (div instanceof HTMLElement) {
      console.log('it works fine here')
    }
    new Grid(div, gridOptions)
    console.log('grid created')
  `)

  script.runInContext(context)
  return gridOptions.api
}

agGridFactory()
```

Output:
```
it works fine here
grid/node_modules/@ag-grid-community/core/dist/src/ts/context/beanStub.ts:100
        if (object instanceof HTMLElement) {
                  ^


TypeError: Right-hand side of 'instanceof' is not callable
    at ClientSideRowModel.BeanStub.addManagedListener (grid/node_modules/@ag-grid-community/core/dist/src/ts/context/beanStub.ts:100:19)
    at ClientSideRowModel.ClientSideRowModel.init (grid/node_modules/@ag-grid-community/client-side-row-model/src/clientSideRowModel/clientSideRowModel.ts:91:14)
    at <anonymous> (grid/node_modules/@ag-grid-community/core/dist/src/ts/context/context.ts:248:70)
    at Array.forEach (<anonymous>)
    at Context.Context.callLifeCycleMethodsOnBean (grid/node_modules/@ag-grid-community/core/dist/src/ts/context/context.ts:248:24)
    at <anonymous> (grid/node_modules/@ag-grid-community/core/dist/src/ts/context/context.ts:228:52)
    at Array.forEach (<anonymous>)
    at Context.Context.callLifeCycleMethods (grid/node_modules/@ag-grid-community/core/dist/src/ts/context/context.ts:228:23)
    at Context.Context.wireBeans (grid/node_modules/@ag-grid-community/core/dist/src/ts/context/context.ts:89:14)
    at Context (grid/node_modules/@ag-grid-community/core/dist/src/ts/context/context.ts:60:14)
```

Despite using the jsdom context, HTMLElement is not working correctly for instanceof checks within ag-grid.  If I create a global jsdom context and assign `global.HTMLElement = jsDom.window.HTMLElement`, then it gets past this and I can eventually get it to work by setting a few more globals.  However, jsdom [considers than an antipattern](https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global) (and I would prefer a clean context for each grid anyway to make it harder to leak memory).

As you can see from the first line of the output, the exact same check is working fine, but once it dives into the `new Grid` call, HTMLElement breaks.

**Expected behavior**
The grid would initialize correctly, as it does if I set the globals.

**Please tell us about your environment:**
OSX, Node v18.14.2, ag-grid 27.3.0, jsdom 21.1.0

* **AG Grid version:** 27.3.0
The problem persists with 29.1.0

* **Browser:**
N/A, nodejs + jsdom

* **Language:** TypeScript 4.9.5

**Comment by StephenCooper** [comment]
Hi @yrral86,

We do not officially support running AG Grid outside of the browser. It seems like this is what you are trying to do and so is likely to run into many issues beyond just this one. 

As such we are unlikely to address this issue I am afraid.

**Comment by ronfogel** [comment]
@yrral86 
I had the same issue. in order to solve it, I installed [jsdom](https://github.com/jsdom/jsdom)

And in the file of the test that us failing, I added these lines
```
import { JSDOM } from 'jsdom';

const { window } = new JSDOM('<!DOCTYPE html>');
global.document = window.document;
global.Node = window.Node;
```

Once I did that, my tests failed due to `ReferenceError: TextEncoder is not defined`
Which I solved by adding the lines below to `jest.setup.js` or `setupAfterEnv.js`

```
import { TextEncoder, TextDecoder } from 'util';

global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
```

@StephenCooper FYI
