### ISSUE TITLE
Docs top bar component style in Firefox

### ISSUE THREAD

**Issue by kian23kpt** [ag-grid/ag-grid#6259]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Top header component in Firefox hasn't any background and blur filter so with scrolling the page, content shows behind the header.

![Inkedfirefox](https://user-images.githubusercontent.com/48172978/222962385-e9d6a599-8cff-4b81-8267-2e0a7817a4b5.jpg)

**Expected behavior**

Like Chrome, styles should works for Firefox

![chrome](https://user-images.githubusercontent.com/48172978/222962668-16447525-dc04-4293-bd23-cc27f51fdf1d.PNG)

* **Browser:**

"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0"

**Comment by markdurrant** [comment]
@kian23kpt Thank you for making us aware. This Issue will be fixed when we deploy the next release.
