### ISSUE TITLE
Facing issue to write test case for the agGrid onGridSizeChanged in React using React testing library and jest.

### ISSUE THREAD

**Issue by supriya-kajana** [ag-grid/ag-grid#6264]
I am currently using the onGridSizeChanged event from the ag-grid react. It meets the functionality requirement in our application but unable to cover the method in unit test cases.

for writing unit test cases currently using: React testing library Jest

Functionality wise the onGridSizeChanged method is being called on first render. And the same is not happening with the unit test cases.

Sample component code: `const onGridSizeChanged =useCallback((params)=>{ // our requirement },[]) return (

 <div className='ag-theme-alpine'>
   <div calssName='gridStylings'>
     <AGGridReact
      rowData={rowData}
      columnDefs={columndef} 
      onGrdiRead={onGridReady}
      onGridSizeChanged={onGridSizeChanged}
    />

   </div>
 </div>
</div>
);

` I tried to fire the resize event through the test cases. Providing the samples used for the window resize event firing

Providing stackoverflow solution used for window resize [react testing library - test window.addEventListener('resize')](https://stackoverflow.com/questions/70987496/react-testing-library-test-window-addeventlistenerresize)

Can anyone help me to find out the solution/provide solution for the test case for onGridSizeChanged.

Thank you.

**Comment by StephenCooper** [comment]
Hi @supriya-kajana,

We use github issues for bug reports only. You've submitted a support question instead of an issue and we're happy to let the AG Grid community respond here. 

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.

**Comment by zoheil-ag** [comment]
Hi @supriya-kajana,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by bdwade100** [comment]
I used a modified solution provided by [Valery](https://stackoverflow.com/users/2528232/valery) on [stackoverflow](https://stackoverflow.com/questions/64558062/how-to-mock-resizeobserver-to-work-in-unit-tests-using-react-testing-library):

ResizeObserver.ts
```
// Based on: https://stackoverflow.com/questions/64558062/how-to-mock-resizeobserver-to-work-in-unit-tests-using-react-testing-library

type ObserverId = string;

let nextObserverId: ObserverId | undefined;
let nextObserverIdBase: ObserverId | undefined;
let nextObserverIdAutoIncrement = false;
let nextObserverIdAutoIncrementIndex: number;

export const setNextResizeObserverId = (observerId: ObserverId, autoIncrement = false) => {
    nextObserverId = observerId;
    nextObserverIdBase = observerId;
    nextObserverIdAutoIncrement = autoIncrement;
    nextObserverIdAutoIncrementIndex = 1;
};

const getNextResizeObserverId = (): void => {
    if (nextObserverIdAutoIncrement) {
        nextObserverId = `${nextObserverIdBase}_${nextObserverIdAutoIncrementIndex}`;
        nextObserverIdAutoIncrementIndex += 1;
    } else {
        nextObserverId = undefined;
    }
};

const subjects: Record<ObserverId, Element[]> = {};

export const resizeObserverInstances: Record<ObserverId, FakeResizeObserver> = {};

export const triggerResizeObserver = (observerId: ObserverId, subjects: Element[]) =>
    resizeObserverInstances[observerId].trigger(subjects);

export const getObserverIds = (): string[] => {
    return Object.keys(resizeObserverInstances);
};

export class FakeResizeObserver implements ResizeObserver {
    id: ObserverId;
    callback: ResizeObserverCallback;

    constructor(callback: ResizeObserverCallback) {
        if (typeof nextObserverId === "undefined") {
            throw new Error("Call setNextResizeObserverId before instantiating a FakeResizeObserver.");
        }

        this.id = nextObserverId;
        getNextResizeObserverId();
        this.callback = callback;
        resizeObserverInstances[this.id] = this;
    }

    trigger(subjects: Element[]) {
        this.callback(
            subjects.map(target => ({ target } as ResizeObserverEntry)),
            this
        );
    }

    observe(element: Element) {
        if (!subjects[this.id]) {
            subjects[this.id] = [];
        }
        subjects[this.id].push(element);
    }

    unobserve(element: Element) {
        delete subjects[this.id][subjects[this.id].indexOf(element)];
    }

    disconnect() {
        this.callback = () => undefined;
        delete subjects[this.id];
    }
}
```

Test code:
```
        const resizeObserver = global.ResizeObserver;
        global.ResizeObserver = FakeResizeObserver;

        // render component
        render();

        setNextResizeObserverId("agGrid", true);

        getObserverIds().forEach(observerId => {
            triggerResizeObserver(observerId, []);
        });

        // check conditions
        await waitFor(() => expect(onGridSizeChanged).toHaveBeenCalledTimes(1));

        global.ResizeObserver = resizeObserver;
```
