### ISSUE TITLE
When we enter valid/invalid string in 'Search' edit fields, Screen readers are not announcing displayed search results information.

### ISSUE THREAD

**Issue by msftedad** [ag-grid/ag-grid#6271]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Repro Steps
1.Open URL: https://codesandbox.io/s/react-functional-component-forked-o0tgbf and turn on Narrator.
2.Keyboard focus automatically moves on ‘index.js’ field.
4.Now Press ‘Ctrl+M' key then Navigate to Search edit fields by using Tab key.
5.Press Enter and Search valid/invalid information and Verify the screen reader announcing search result information or not.

**Current behavior**
When we enter valid/invalid string in 'Search' edit fields, Screen readers are not narrating displayed search results information.

Observation: JAWS/NVDA/Narrator is not narrating any information When we enter valid/invalid string.

**Expected behavior**
When we enter valid/invalid string in 'Search' edit fields, Screen readers should narrate displayed search results information.

Ex: 1.JAWS/NVDA/Narrator should narrate search results information as '2 Results returned' when we enter valid string.

2.JAWS/NVDA/Narrator should narrate search results information as 'No Matches' when we enter invaild string.

**Please tell us about your environment:**
OS Version: 22H2 OS Build 22621.674

* **AG Grid version:** 25.1.0
* **Browser:** Edge(Chromium) Version 109.0.1495.2 (Official build) dev (64-bit)
* **Language:** ES6

https://user-images.githubusercontent.com/93735775/223475006-1368f909-f6d5-467f-bbcb-84518893e8ef.mp4

**Comment by msftedad** [comment]
@kiril-matev Thank you for the update. We will get in touch with our engineering team on this and let you know if the added feature is fixing this issue.

**Comment by msftedad** [comment]
Hi @StephenCooper, This issue is not yet fixed and is still repro'ing. Can you please Reopen this issue. Thanks

**Comment by kiril-matev** [comment]
Hi @msftedad,

As I mentioned before we don't track issues in GitHub, but instead record them in our backlog. We've provided the backlog item number - AG-6541.

Note that the GitHub issues are not updated when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. This is why we close issues and we ask you to track the item on our pipeline using the index above.

Most importantly, I've already mentioned, this feature will be implemented as part of our next release in about 2 weeks time.

Thanks again for bringing this up with us - we appreciate your time!

**Comment by msftedad** [comment]
Hi @kiril-matev,
We verified the issue on
URL:[React Functional Component (forked) - CodeSandbox](https://codesandbox.io/p/sandbox/react-functional-component-forked-o0tgbf)
Issue is not fixed as screen reading is not announcing displayed search results.
Attaching video for the reference (Regressed video).

https://github.com/ag-grid/ag-grid/assets/93735775/b07b7085-be59-4eb5-970c-e5b9b0848503

**Comment by AG-Zoheil** [comment]
Hi @msftedad,

Thanks for your comment. Please note that the example you've linked runs on `v28` of AG Grid whilst **AG-6541** was implemented after `v31` of AG Grid.
With the above in mind, please upgrade your AG Grid version and verify the requirement thereafter.

Many thanks!
