### ISSUE TITLE
[Angular] non-passive event listener to a scroll-blocking 'wheel' event

### ISSUE THREAD

**Issue by stefnedelchevbrady** [ag-grid/ag-grid#6280]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
The issue can be reproduced **only with the Angular wrapper for AG Grid** and doesn't seem to require any specific grid configuration for reproducing. You can basically observe the error thrown in the console even on the Documentation examples like this one: https://ag-grid.com/archive/29.0.0/angular-data-grid/data-update-row-data/. I added a plunker as well: https://plnkr.co/plunk/fGGrFQHbaapjyp79. Since it's only reproduced with the Angular version of AG Grid and by looking at the stack trace my guess is that that zone.js patches an event listener that shouldn't be patched so initializing some stuff outside the Angular zone might be required.

**Current behavior**
There is a non-passive event listener attached to the 'wheel' event somewhere and Chrome logs this violation as a result:
```
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Z	@	zone.min.js:43
e.scheduleTask	@	zone.min.js:13
onScheduleTask	@	zone.min.js:13
e.scheduleTask	@	zone.min.js:13
t.scheduleTask	@	zone.min.js:13
t.scheduleEventTask	@	zone.min.js:13
(anonymous)	@	zone.min.js:43
AngularFrameworkOverrides.addEventListener	@	ag-grid-angular.js:50
Ne	@	ag-grid-community.cjs.min.js:77
e.addManagedListener	@	ag-grid-community.cjs.min.js:77
t.addBodyViewportListener	@	ag-grid-community.cjs.min.js:253
t.setComp	@	ag-grid-community.cjs.min.js:253
t.init	@	ag-grid-community.cjs.min.js:267
eval	@	ag-grid-community.cjs.min.js:38
e.callLifeCycleMethodsOnBean	@	ag-grid-community.cjs.min.js:38
eval	@	ag-grid-community.cjs.min.js:38
e.callLifeCycleMethods	@	ag-grid-community.cjs.min.js:38
e.wireBeans	@	ag-grid-community.cjs.min.js:38
e.createBean	@	ag-grid-community.cjs.min.js:38
e.createBean	@	ag-grid-community.cjs.min.js:77
t.createComponentFromElement	@	ag-grid-community.cjs.min.js:195
eval	@	ag-grid-community.cjs.min.js:195
t.createChildComponentsFromTags	@	ag-grid-community.cjs.min.js:195
eval	@	ag-grid-community.cjs.min.js:195
t.createChildComponentsFromTags	@	ag-grid-community.cjs.min.js:195
t.setTemplateFromElement	@	ag-grid-community.cjs.min.js:195
t.setTemplate	@	ag-grid-community.cjs.min.js:195
t.postConstruct	@	ag-grid-community.cjs.min.js:332
eval	@	ag-grid-community.cjs.min.js:38
e.callLifeCycleMethodsOnBean	@	ag-grid-community.cjs.min.js:38
eval	@	ag-grid-community.cjs.min.js:38
e.callLifeCycleMethods	@	ag-grid-community.cjs.min.js:38
e.wireBeans	@	ag-grid-community.cjs.min.js:38
e.createBean	@	ag-grid-community.cjs.min.js:38
eval	@	ag-grid-community.cjs.min.js:338
e.create	@	ag-grid-community.cjs.min.js:338
e	@	ag-grid-community.cjs.min.js:338
...........
```

I guess this could also be a potential performance issue. The stack trace leads me here:
![image](https://user-images.githubusercontent.com/88819267/223784724-eb8cf65a-a209-4ac5-842f-4ad147efba87.png)
and I maybe straight to the angular framework overrides of the event listeners: https://github.com/ag-grid/ag-grid/blob/latest/grid-community-modules/angular/projects/ag-grid-angular/src/lib/angularFrameworkOverrides.ts

**Expected behavior**
No errors or warnings related to AG Grid to be thrown on a correct minimal configuration.

**Please tell us about your environment:**
OS: Windows 10 x64
IDE: VSCode
Package manager: NPM
Framework: Angular v15.2.0

* **AG Grid version:** 29.1.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

* **Language:** TypeScript 4.8

**Comment by StephenCooper** [comment]
After further investigation we believe this is an Angular issue and not to do with AG Grid. Note that this error is not raised when using any other framework.

See that the warning is raised even with the simplest of examples even though the event is having `preventDefault()` called on it. 

https://stackblitz.com/edit/angular-hujj9r?file=src/main.ts

We call preventDefault on the wheel event currently so it would be incorrect to mark this event as passive. 

So I am going to close this as it really is an issue for Angular / zone.js to resolve.

**Comment by stefnedelchevbrady** [comment]
> 

I already mentioned that it's an issue only with the angular wrapper of AG Grid. By looking at your example - I can tell it's going to raise this warning even without running it because Angular creates event listeners as non-passive by default. Calling `preventDefault` inside the event listener should not have an effect because the problem lies in the creation of the event listener itself, not the call back of the event listener.
My last comment linked this file https://github.com/ag-grid/ag-grid/blob/latest/grid-community-modules/core/src/ts/vanillaFrameworkOverrides.ts where I don't see the `wheel` event neither inside the PASSIVE_EVENTS constant or the OUTSIDE_ANGULAR_EVENTS constant. I'm not 100% sure but could this be the reason why the wheel event listener is created as non-passive by the Angular wrapper for AG Grid?

**Comment by smohadjer** [comment]
Could it be that this is also the reason why angular docs which embed grid examples freeze temporarily during scrolling and scrolling is very jerky? When I open chrome devtools on such pages console warnings are all over the place! 

<img width="1271" alt="Screenshot 2024-01-06 at 17 35 05" src="https://github.com/ag-grid/ag-grid/assets/1375720/8cdeee70-2a4f-4789-91df-c99c6dc2a939">
