### ISSUE TITLE
agSetColumnFilter combined with floatingFilter hang if gridApi.setFilterModel is called in onGridReady

### ISSUE THREAD

**Issue by bcochranemax** [ag-grid/ag-grid#6284]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://plnkr.co/edit/nKkyDQyxScCvbDSg?open=index.jsx&preview
https://codesandbox.io/s/ecstatic-hopper-xsn55b?file=/src/App.tsx

**Current behavior**
In `ag-grid-react` & `ag-grid-enterprise` on version 29.1.0:

This bug is caused by a combination of 3 factors.
First: Add a columnDef to the table with `filter: agSetColumnFilter` and `floatingFilter: true`
Second: Use `onGridReady` to call `api.setFilterModel({ theSetFilterColumn: { ... anything }})`
Third: Do something to cause the `<AgGridReact />` component being passed these options to be unmounted.

Then observe that the table/page hang indefinitely

In my debugging experience, what appears to be happening is during clean up, the event to destroy/remove the floating filter triggers the same event to be sent to the parent filter which gets sent back to the floating filter, creating a cycle.

**Expected behavior**
Setting a filter model during `onGridReady` should not put the table in state where unmounting causes an infinite cycle.

**Please tell us about your environment:**
This is occurring on windows and macOS, chrome/firefox/safari.
Using react 18, both create-react-app and next.js experience this issue

* **AG Grid version:** X.X.X
29.1.0

* **Browser:**
 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0"
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"

As far as I can tell, this is reproducible in all browsers

**Language:**
All

**Comment by StephenCooper** [comment]
Hi @bcochranemax,

This is an issue in v29.1 that we have resolved and will be releasing a fix for in v29.2. This is scheduled to be released before the end of March. 

The issue is not present in v29.0 so we would suggest that as a potential work around in the short term.
