### ISSUE TITLE
Custom Filter For Sidebar

### ISSUE THREAD

**Issue by lawaldare** [ag-grid/ag-grid#6289]
I am trying to create a custom filter at the sidebar using my own component. I was able to create a component and add it to the sidebar. I wanna ask if it is possible to do stuffs like the default `filters` toolpanel at the sidebar inside a custom component?

**Comment by DerKleineGauss** [comment]
yes you can do, see [Docs](https://ag-grid.com/angular-data-grid/tool-panel/#custom-tool-panel-components)

The filter toolpanel itself can't be customized afaik.

**Comment by DerKleineGauss** [comment]
however you can provide custom filters for columns which will also render at the filters toolpanel. See [docs](https://www.ag-grid.com/vue-data-grid/component-filter/

You basically have to reference the custom component within your colDefs object
