### ISSUE TITLE
Header scrolls not in sync with body

### ISSUE THREAD

**Issue by joafeldmann** [ag-grid/ag-grid#6292]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
On horizontal scrolling the header scrolls kind of slower than the body. Depending on the number of columns or the width of the grid the effect is sometimes more, sometimes less.

https://user-images.githubusercontent.com/1437079/224522212-11e532ee-42e1-478e-9060-c47a485db14d.mov

The issue seems to be related with the `createRoot` api. When using the old `render` method, the problem does not occur (at least in this simple setup):

Reproduce/Repo:
https://stackblitz.com/edit/vitejs-vite-5t8kxa?file=src%2Fmain.tsx

**Expected behavior**
Header and body scrolling is in sync

**Please tell us about your environment:**
Apple M1 Max, macOS Ventura, Vitejs, React 18.2, Typescript

* **AG Grid version:** 29.0.0 and 29.1.0, modules and package version, community versions

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**Comment by andrzejbe** [comment]
@StephenCooper see also AG-7652

**Comment by joafeldmann** [comment]
I just tried to play with Chrome's  [scroll unification](https://bugs.chromium.org/p/chromium/issues/detail?id=1411534#c12) but the problem persists in my case.

> Depending on your application, i.e number of columns you have, you can see improved scroll linking by setting the flag supressColumnVirtualisation however, there are downsides to setting this flag in other areas of performance for the grid so this would not be actively recommended.

Disabling virtualisation is - like u've assumed - not an option, but even though I [tried](https://stackblitz.com/edit/vitejs-vite-vdzwq8?file=src%2Fmain.tsx), also without success.

Also reducing the number of cols/rows to a minimum does not help: https://stackblitz.com/edit/vitejs-vite-brbtgy?file=src%2Fmain.tsx

**Comment by StephenCooper** [comment]
I have raised AG-8193 which is now focussed specifically on the additional lagging introduced with `createRoot` so that we can resolve this issue separately.

**Comment by StephenCooper** [comment]
Please try upgrading to 29.2 as that contains a fix for AG-8193. Here is the updated version of your example which you can see is now scrolling better.

https://stackblitz.com/edit/vitejs-vite-iifcdc?file=package-lock.json
