### ISSUE TITLE
the apply and reset buttons don't work when i change the filter

### ISSUE THREAD

**Issue by phuongnam98pt** [ag-grid/ag-grid#6294]
here is my code: 
                    <AgGridReact
                        ref={gridRef}
                        rowData={rowData}
                        columnDefs={columnDefs}
                        defaultColDef={defaultColDef}
                        suppressRowClickSelection={true}
                        suppressRowTransform={true}
                        // onGridReady={onGridReady}
                        onFilterChanged={handleFilterChanged}
                    ></AgGridReact>
// handleFilterChanged
    const handleFilterChanged = (filters) => {
        // filter SaleInchargeItem
        var saleInchargeItem = gridRef.current!.api.getFilterInstance(
            'SaleInchargeItem'
        )!;
        var saleInchargeItemFilter = saleInchargeItem.getModel()
        if (saleInchargeItemFilter) {
            setSearchSaleInchargeItem(saleInchargeItemFilter.values)
            console.log("saleInchargeItemFilter " + saleInchargeItemFilter.values)
        }

        // filter DepartmentItem
        var departmentItem = gridRef.current!.api.getFilterInstance(
            'DepartmentItem'
        )!;
        var departmentItemFilter = departmentItem.getModel()
        if (departmentItemFilter) {
            setSearchDepartmentId(departmentItemFilter.values)
            console.log("departmentItemFilter " + departmentItemFilter.values)
        }
    }

**Comment by StephenCooper** [comment]
Could you please provide this code in a working sample so that we can investigate this issue. Just supplying the code above is not enough for us to go on.

**Comment by vmerino** [comment]
Hi @StephenCooper, I just ran into something similar. Not sure if the original poster is reporting what I ran into, but here is my repro info: 
- Repro Sandbox: https://codesandbox.io/s/ag-grid-playground-bfq2mi?file=/src/App.js
- Loom video with repro steps: https://www.loom.com/share/976ef186f71c47c79774d7d625bb3f3a

Please let me know if you'd like me to open this up under a different issue. Thanks.

**Comment by StephenCooper** [comment]
Hi @vmerino,

Appreciate the video! I believe you are after the following code that uses the `excelMode` param. This changes the behaviour of the set filter so that your repo then works in the way that you are expecting it too. 

You can read more about the different set filter modes at: https://ag-grid.com/javascript-data-grid/filter-set-excel-mode/

```ts
    {
      field: "make",
      filter: "agSetColumnFilter",
      filterParams: { buttons: ["apply", "clear"], excelMode: 'windows' }
    },
```
