### ISSUE TITLE
Column Header has incorrect ColumnGroup

### ISSUE THREAD

**Issue by 0biWanKenobi** [ag-grid/ag-grid#6296]
**I'm submitting a ...**
```
[x] bug report 
[] feature request 
[] support request
```

**Current behavior**

I have a problem where the parent `ColumnGroup` of a header appears to be reported incorrectly. See [repro here](https://stackblitz.com/edit/vue2-vue-cli-tzqfm8?file=src%2FApp.vue).
I have created a simple grid with VueJS and Ag-Grid, this is the header structure:
```json
[
   {
      "headerName":"superparent",
      "groupId":"d90cdda5-1c8e-46b1-82ab-30caa19ee06f",
      "children":[
         {
            "headerName":"parent",
            "groupId":"2b295010-7c73-49af-b3f0-687d0509f23b",
            "children":[
               {
                  "headerName":"one",
                  "field":"one",
                  "colId":"one"
               }
            ]
         },
         {
            "headerName":"two",
            "field":"two",
            "colId":"two"
         }
      ]
   }
]
```
Currently doing this
```javascript
     const col = params.columnApi.getColumn('two')
      console.log(col.getParent().getColGroupDef())
```

prints out an empty object.

**Expected behavior**

I would expect to get `superparent` as the `ColumnGroup`.

**Please tell us about your environment:**
* OS: win10
* IDE: VSCode
* package manager: yarn

* **AG Grid version:** 27.1.0 on StackBlitz, checked w/ 28.2.1 locally, still same issue

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.69'

* **Language:** javascript, VueJS

**Comment by StephenCooper** [comment]
Hi @0biWanKenobi,

There is no code bug here but a different expectation of what this method should do. What is happening is that this internal method is returning the padding group at the first level and then if you call parent on that padding group you will get the top level parent that you are looking for. 

```
col.getParent().getParent();
```

However, the `getParent()` method is an internal method for AG Grid which is why it is not part of our [documentation](https://ag-grid.com/javascript-data-grid/column-api/) and why it does not work as you might expect.

**Comment by 0biWanKenobi** [comment]
> Hi @0biWanKenobi,
> 
> There is no code bug here but a different expectation of what this method should do. What is happening is that this internal method is returning the padding group at the first level and then if you call parent on that padding group you will get the top level parent that you are looking for.
> 
> ```
> col.getParent().getParent();
> ```
> 
> However, the `getParent()` method is an internal method for AG Grid which is why it is not part of our [documentation](https://ag-grid.com/javascript-data-grid/column-api/) and why it does not work as you might expect.

Hi @StephenCooper, thanks for clarifying, I later noticed that internally ag-grid has a ColumnGroup in between my Column and the actual root. I am using internal methods to provide an UI that allows to define table structure at runtime, so that's why I use internals :)
