### ISSUE TITLE
Styles are changing by themselves after upgrading to v29.1

### ISSUE THREAD

**Issue by alagkonas** [ag-grid/ag-grid#6307]
**I'm submitting a 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
After upgrading to v29.1 from v28, the styles are changing by themselves. I am using the alpine theme, and css props like 
--ag-foreground
color
border
and so on, are overwritten by the [class*=ag-theme-]. So, styles are applied by this class instead of .ag-theme-alpine. There are no exact steps to reproduce, since this issue happened after migrating to v29.1 and it's totally random. It's happening when being idle for a few seconds, on first mount, on hovering outside the grid and sometimes after hard reload. I have even created my own styles using styled-component and passed the !important flag, but these issues keep happening.

**Expected behavior**

**Please tell us about your environment:**
React v16.13 with TS.

* **AG Grid version:** X.X.X
29.1.0

**Comment by StephenCooper** [comment]
Hi @alagkonas,

As you can imagine, with no exact steps to reproduce this is going to be very hard for us to investigate. As such I am going to add the label waiting for repo and leave this open to see if anyone else, or yourself, is able to consistently reproduce this.

**Comment by Paveltrof86** [comment]
Hi @alagkonas !

For experiment, could you please comment out this line of code in ag grid source file?
What is the result?

`function(){e.calculatedSizes={}/*,e.fireGridStylesChangedEvent()*/}`

![2023-04-06_10h35_51](https://user-images.githubusercontent.com/19744837/230307202-2855fece-d1ef-4d01-a3d6-ca5652356d56.jpg)
