### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'forEach') when updating hide property on child columns of groups

### ISSUE THREAD

**Issue by baurelien-la** [ag-grid/ag-grid#6312]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Bug description**

When updating our software to Ag Grid 28.2.1, an error was raised on AgGrid handling of grouped colDefs with updated *hide* properties.

If we update the hide property to *false* of a children column in a group where all childrens were hidden previously, then push the new ColGroupDef[] object to our aggrid component, we receive that error : 

> core.mjs:8405 ERROR TypeError: Cannot read properties of undefined (reading 'forEach')
>     at process (ag-grid-community.auto.esm.js:2554:19)
>     at ProvidedColumnGroup.findChildrenRemovingPadding (ag-grid-community.auto.esm.js:2565:9)
>     at ProvidedColumnGroup.setExpandable (ag-grid-community.auto.esm.js:2521:29)
>     at ProvidedColumnGroup.onColumnVisibilityChanged (ag-grid-community.auto.esm.js:2569:14)
>     at ag-grid-community.auto.esm.js:1073:17
>     at Set.forEach (<anonymous>)
>     at processEventListeners (ag-grid-community.auto.esm.js:1068:77)
>     at EventService.dispatchToListeners (ag-grid-community.auto.esm.js:1078:13)
>     at EventService.dispatchEvent (ag-grid-community.auto.esm.js:1057:14)
>     at Column.setVisible (ag-grid-community.auto.esm.js:1738:31)

That scenario occurs even if the group only has one child, and doesn't occur if we remove groups from our column definition.
It seems, only the *hide* property, raises an error, but we didn't test extensively.

**Reproducing the Scenario**

You can find a plunkr of the main scenario here : https://embed.plnkr.co/github/baurelien-la/aggrid-test/main

Github is available here with multiple branchs and examples : https://github.com/baurelien-la/aggrid-test

**Current behavior**
Updating hide properties directly for the children columns of a group returns an undefined error when updated on invisible before groups 

**Expected behavior**
We could update that property without issues up to version 28.2.0 : That property should be as updatable as the other ones, on groups or otherwise.

**Please tell us about your environment:**

- Operating system : Ubuntu OS
- IDE : Visual Studio Code
- Package manager : Yarn
- Framework : Angular 13

* **AG Grid version:** 28.2.1
* Issue is not resolved on 29.1.0
* Issue appeared on 28.2.1 (28.2.0 works fine)

* **Browser:**
Doesn't work on Chrome or Firefox. Did not test on other browsers

* **Language:** [all]

**Comment by StephenCooper** [comment]
I can reproduce the error on 28.2.1 as seen here with a slightly simplified example. 
https://plnkr.co/edit/SqesHgktmUe5YLXp?open=app%2Fapp.component.ts

However, when I upgrade to 29.0.0 or 29.1 the error is no longer raised as can be seen in this example. Only change is the version. https://plnkr.co/edit/u6gARS6zFV46wYeB?open=app%2Fapp.component.ts

Also in your repo provided upgrading as follows fixes the issue to so I am going to close this as resolved. 

```
    "ag-grid-angular": "29.1.0",
    "ag-grid-community": "29.1.0",
```

**Comment by krzysztof-grzybek** [comment]
For anyone who can't bump ag-grid, but need the fix now: it seems that this commit resolves the issue:
https://github.com/ag-grid/ag-grid/commit/d4a31685ae94063941e2269429905d40d3732898

You can use patch-package to fix it immediately.
