### ISSUE TITLE
Localization problem on the functionality in the grid filters operations

### ISSUE THREAD

**Issue by mervearsln** [ag-grid/ag-grid#6322]
There is a problem in the functionality behind the filter operations, it doesn't set the local language.

I set a new local language to my app. Ag-grid uses English for all operations. I can change the text messages, labels in the grid. 
But, values, comparisons in the filters running by using English.

** current behavior **
I am using the grid's filter top of the columns. 
Language is Turkish. My data contains Turkish names and Turkish alphabet. 
Some letters are different, for example ı and i are different.
i--> İ
ı--> I
Filters work to English alphabet.
I need something like toLocaleLowerCase("tr").

** expected behavior **
When a user change the local language, the grid operations should be updated via a property.

** environment: **
Operating system: Windows
IDE: VSCode
package manager: npm
Ag grid react
AG Grid version: 28.0.2
Language: TypeScript 4.7.2 

** browser **
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57

**Comment by StephenCooper** [comment]
Is it possible for you to provide a reproduction of your use case based of this [plunker](https://plnkr.co/edit/EAKwsUEjMo2sXLYI?open=main.ts)?

**Comment by StephenCooper** [comment]
Thank you for putting that together. I have raised this internally now.

**Comment by StephenCooper** [comment]
I have also added a `textFormatter` to your example and that seems to fix it. 

https://plnkr.co/edit/JIlDOlVCjM6M3270

```
  textFormatter: (value: string) =>
    value == null ? null : value.toString().toLocaleLowerCase('tr'),
```

**Comment by mervearsln** [comment]
Yes, this solution fixed it. Thank you.
