### ISSUE TITLE
Can I have one component for both cellEditor and cellRenderer purpose?

### ISSUE THREAD

**Issue by Marcinthedev** [ag-grid/ag-grid#6325]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

Not related

**Question**
Is there a possbility to have e.g. checkbox as a component that works as a cell renderer as well as cell editor?
I want to be able to click checkbox and change the state without opening another component (such as cell editor component).

**Comment by StephenCooper** [comment]
Hi @Marcinthedev,

This is not currently supported out the box. My suggestion would be to create a cell renderer and in your cell renderer use the grid api methods to perform updates to your data. However, I have not actually tried this myself just trying to give you a pointer.
