### ISSUE TITLE
Sub totals row 

### ISSUE THREAD

**Issue by rajesh276** [ag-grid/ag-grid#6335]
I want to show sub totals rows in ag-grid.

Following is the way that i need to show : 

 A--B--C--D
10   20  30  40
12   12  12  12
------------------------------------------------
22   32  42  52
-----------------------------------------------
15   25  35   45
  5     5    5    5
------------------------------------------------
20   30  40   50
------------------------------------------------

How can i achieve this?

**Comment by StephenCooper** [comment]
The following example in our docs implements something like this. 

https://www.ag-grid.com/react-data-grid/aligned-grids/#example-aligned-grid-as-footer
