### ISSUE TITLE
how to keep Tooltip not disappear?

### ISSUE THREAD

**Issue by vaynevayne** [ag-grid/ag-grid#6344]
https://www.ag-grid.com/examples/component-tooltip/custom-tooltip-component/modules/reactFunctional/index.html

**Comment by vaynevayne** [comment]
in other word , `tooltipHideDelay={Infinity}` is invalid

**Comment by vaynevayne** [comment]
Thank you. It's useful, but it's too complicated

**Comment by Surejmohan** [comment]
Hi @StephenCooper  
I am trying to use custom tooltip with ag-grid cell render not custom cell render. 
is it possible to fix this issue without using custom cell render?
custom cell render is creating scrolling issues.

**Comment by StephenCooper** [comment]
> Hi @StephenCooper I am trying to use custom tooltip with ag-grid cell render not custom cell render. is it possible to fix this issue without using custom cell render? custom cell render is creating scrolling issues. Can you pls help?? I am using REACT TypeScript

@Surejmohan please raise a new issue with a code reproduction of your issue.

**Comment by Surejmohan** [comment]
> > Hi @StephenCooper I am trying to use custom tooltip with ag-grid cell render not custom cell render. is it possible to fix this issue without using custom cell render? custom cell render is creating scrolling issues. Can you pls help?? I am using REACT TypeScript
> 
> @Surejmohan please raise a new issue with a code reproduction of your issue.

ya sure

**Comment by mrkevinham** [comment]
Hello. Was there ever a resolution to this?
Having the same issue myself.

**Comment by StephenCooper** [comment]
Please see this section of the docs with an example of an interactive tooltip.

https://www.ag-grid.com/javascript-data-grid/component-tooltip/#interactive-tooltips

**Comment by mrkevinham** [comment]
> Please see this section of the docs with an example of an interactive tooltip.
> 
> https://www.ag-grid.com/javascript-data-grid/component-tooltip/#interactive-tooltips

Awesome thank you. Do you know which version this was added? It appears I'll need to update mine.

**Comment by StephenCooper** [comment]
https://www.ag-grid.com/changelog/

It was added in 30.1

**Comment by LuckyAmanVerma** [comment]
Hi Team , 
I have to write the test case for ag grid tooltip using TooltipComponent , 
I am using tooltipShowDelay of 1000 ms and tooltipHideDelay of 3000 ms , 
Requirement is , TooltipComponent is any React Component , 
When I hover on column header of ag grid , tooltip is visible after 1000 ms and hide after 3000 ms , 

I try many thing , but not able to find the solution , 

This is my code , `import { fireEvent, render, screen, waitFor } from '@testing-library/react';

import userEvent from '@testing-library/user-event';
import { ColumnApi, GridApi } from 'ag-grid-community';
import { AgGridReact } from 'ag-grid-react';

import TooltipDescriptionComponent from '.';
import AudienceListing from '@/components/AudienceExplorer/AudienceListing';
import { CellRendererComponent } from 'ag-grid-community/dist/lib/components/framework/componentTypes';
import { getInstanceById } from 'echarts/lib/echarts';
const params: any = {
    location: 'header',
    column: {
        getUniqueId: () => 'audience_name',
    },
    value: 'Test Value',
    api: new GridApi(),
    columnApi: new ColumnApi(),
    context: undefined,
};
const MyGrid = () => {
    const colDefs = [
        {
            headerName: 'P&G Audience ID',
            headerTooltip: 'P&G Audience ID',
            field: 'audience_name',
            tooltip:"Aman Testing"

        },
    ];

    const defaultColDef: any = {
        tooltipComponent: TooltipDescriptionComponent,
    };

    return (

        <div className="ag-theme-alpine" style={{ height: 400, width: 600 }}>
            <AgGridReact
                columnDefs={colDefs}
                // defaultColDef={defaultColDef}
                onTooltipShow={(e)=>console.warn('Tooltip is visible',e)}
                 onTooltipHide={(e)=>console.warn('Tooltip is hidden',e)}
                // tooltipShowDelay={1000}
                // tooltipHideDelay={3000}
                // tooltipInteraction={true}
                tooltipTrigger="hover"
                
            />
        </div>
    );
};

describe('MyGrid', () => {
    it.only('shows and hides tooltip with delay', async () => {
        jest.useFakeTimers();
        const { getByRole,getByTestId } = render(<MyGrid />);
        let header: any;
        await waitFor(() => header = getByRole('columnheader'));
        fireEvent.mouseEnter(header);
        fireEvent.click(header);
        fireEvent.mouseOver(header);

        screen.debug(header);
        // screen.debug(getByTestId('tooltip-component'));
        jest.advanceTimersByTime(1000);
        expect(await screen.findByText('Aman Testing')).toBeInTheDocument();
        // expect(await screen.findByTestId('tooltip-component')).toBeInTheDocument();



        // Advance timers by 3 seconds to simulate tooltipHideDelay
        // jest.advanceTimersByTime(3000);
        // await userEvent.unhover(header);
        // expect(screen.queryByTestId('tooltip-component')).not.toBeInTheDocument();

        // Advance timers by 1 second to simulate tooltipShowDelay

        jest.useRealTimers();
    });

`

Please help me to find the solution
