### ISSUE TITLE
Any plans to bring ag-grid-aurelia up to date with latest ag-grid product

### ISSUE THREAD

**Issue by salminio** [ag-grid/ag-grid#6353]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- I am upgrading from from ag-grid-community and ag-grid-aurelia from 20.1.0 to latest as part of a node sass to dart upgrade. It looks like the aurelia part has not been touched since 21.1.0 (2019) and is 15K commits behind... I tried to mix and match using ag-grid-community 26+ (looks like where ag-grid adopted new Sass) but the aurelia component is failing to initialiaze frameworkComponentWrapper for the custom cell render - ag-cell-template. Just wondering if anyone is still maintaining the wrapper for aurelia?

If reporting a bug make sure to state.

Current behaviour.
Console throwing error with this.frameworkComponentWrapper is null

simple <ag-grid-column>...<ag-grid-template>html</ag-grid-template></ag-grid-column>

**Expected behavior**
grid to render

**Please tell us about your environment:**
Windows 10 - Chrome - WEB SPA

* **AG Grid version:** 26 -> 29.2
Still an issue with 29.2

* **Browser:**
Chrome 110

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by StephenCooper** [comment]
Hi @salminio,

I am afraid not no. There was not enough demand for this framework to justify to continued support and cost to us to maintain it.

Apologies for that.
