### ISSUE TITLE
React AG Grid doesn't respect web event bubbling behaviors

### ISSUE THREAD

**Issue by lifeiscontent** [ag-grid/ag-grid#6356]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

I would expect event delegation to work, it appears ag grid is either not respecting the browser event model, or is not taking the event priority in react 18 so that events bubble in the expected order.

if you click on the "country" cell it should have a default behavior prevented but it is showing that it is returning "false" in the console.

https://codesandbox.io/s/react-functional-component-forked-7o1qdo?file=/src/index.js

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

doesn't not make use of proper event bubbling

**Expected behavior**

uses proper event bubbling to opt out of default behaviors set in agGrid e.g. `onRowClicked() => { /* does something */ }` onRowClick would have some default behavior, and on a per column basis opt out of that behavior via onCellClicked() with `event.event.preventDefault()`

**Please tell us about your environment:**

* **AG Grid version:** 29.2.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi @lifeiscontent,

The grid events such as `onRowClicked` and `onCellClicked` are grid specific events and are not part of the browser event process. We include the original browser event on our grid event parameters as that is helpful in some use cases but it is not intended to behave like a browser event with respect to `preventDefault`.
