### ISSUE TITLE
custom compact is not work 

### ISSUE THREAD

**Issue by vaynevayne** [ag-grid/ag-grid#6364]
version: 28.2.1
 
your demo height is 21, my project ,the height is 42 ,  Drunk? What's the problem?

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/124666577/227093494-d9d6b50a-fbf4-4dbb-bf7a-d0775cf44056.png">

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/124666577/227093547-040a1a5e-f7a4-4cb9-9b9d-91ac0b090f97.png">

```jsx
@import '@ag-grid-community/styles/ag-grid.css';
@import '@ag-grid-community/styles/ag-theme-alpine.css';

.ag-theme-alpine,
.ag-theme-alpine-dark {
  font-variant: tabular-nums;
  /* --ag-cell-horizontal-padding: 0.875rem; */
}

.ag-theme-alpine.compact,
.ag-theme-alpine-dark.compact {
  --ag-grid-size: 3px;
  --ag-list-item-height: 20px;
}


```

```jsx
<AgGridReact    domLayout={'autoHeight'}  className={'ag-theme-alpine compact'} />
```

**Comment by StephenCooper** [comment]
Can you please provide a reproducible demo so that we can investigate this for you?

**Comment by vaynevayne** [comment]
hello, @StephenCooper 
https://stackblitz.com/edit/ag-grid-react-hello-world-zlkems?file=index.js

**Comment by vaynevayne** [comment]
well, add --ag-grid-size: 3px; it works, I have two questions

1. What are the virtual scrolling side effects of changing ag-grid-size? Is the content going to be missing or something, do I need to do something?
2. but has more vertical empty, how to fixed it ? 
```jsx
.ag-theme-alpine.compact,
.ag-theme-alpine-dark.compact {
  --ag-grid-size: 3px; // add 
  /* 11px */
  --ag-font-size: 0.6875rem;
  /* 14px */
  --ag-cell-horizontal-padding: 0.875rem;
  --ag-list-item-height: 20px;
}
```

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/124666577/228434666-445860c0-dfe2-46c6-bf3d-90a8111baa61.png">

**Comment by vaynevayne** [comment]
grid has minHeight, does i can remove it safely? 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/124666577/228435239-0e57808c-4f77-4e34-a696-509100d56739.png">
