### ISSUE TITLE
Add additional types for context menu icon & tooltips props

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#6365]
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'

**Current behavior**
Right now the types supported for icon & tooltip props of context menu are as follows:
![IMG_20230323_093833](https://user-images.githubusercontent.com/77911765/227101016-207f37f4-7495-40b2-bedb-ce53f3b3920e.jpg)
 

**Expected behavior**
Extend the type to include React Component

**Please tell us about your environment:**
Windows

* **AG Grid version:** X.X.X
29.1.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React + Typescript

**Comment by StephenCooper** [comment]
Hi @melon2504,

I have recorded this request under **AG-8276 Framework specific Types**. It is an idea we have in the pipeline but will require some larger changes as currently our types are shared across all frameworks, hence why they do not include framework specific types.

I understand the DX improvement this can bring to all our frameworks.
