### ISSUE TITLE
defaultColDef type error (Types of property 'menuTabs' are incompatible)

### ISSUE THREAD

**Issue by vonwao** [ag-grid/ag-grid#6377]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

gridOptions : {
 ...
 defaultColDef: {    // error on this line
        ...
        menuTabs: ['generalMenuTab'],
  }
}

The defaultColDef line is giving this error:

TS2322: Type '{ enableRowGroup: boolean; enablePivot: boolean; enableValue: boolean; width: number; resizable: boolean; sortable: boolean; filter: string; floatingFilter: boolean; menuTabs: string[]; keyCreator: (params: any) => any; }' is not assignable to type 'ColDef<any>'.
  Types of property 'menuTabs' are incompatible.
    Type 'string[]' is not assignable to type 'ColumnMenuTab[]'.
      Type 'string' is not assignable to type 'ColumnMenuTab'.
Version: typescript 4.5.4

This was working in version 25 but now is not working

**Please tell us about your environment:**
Mac, yarn

* **AG Grid version:** 29.1.0

* **Language:** TypeScript 4.5.4

<img width="1070" alt="Screenshot 2023-03-24 at 4 54 18 PM" src="https://user-images.githubusercontent.com/377000/227638325-33e32fa2-6016-4a73-a0c0-88ed9cf9dafb.png">

Note:  the documentation says:
https://www.ag-grid.com/react-data-grid/column-menu/
The property menuTabs is an array of strings. The valid values are: 'filterMenuTab', 'generalMenuTab' and 'columnsMenuTab'.
So the above code should work according to the docs

**Comment by StephenCooper** [comment]
I cannot reproduce this error. Here is a Typescript example that shows this working so I am not sure why you are seeing this issue.

https://plnkr.co/edit/pf12LYKVgp3q8Mem?open=main.ts
