### ISSUE TITLE
Can't you customize the data for table expansion/collapse

### ISSUE THREAD

**Issue by qiang-chen** [ag-grid/ag-grid#6380]
![image](https://user-images.githubusercontent.com/51185533/227878232-efe28dd0-45d0-465f-a305-94f15bd82f9d.png)

**Comment by StephenCooper** [comment]
Sorry there is not enough information in this ticket for me to understand what you are trying to achieve. 

My best guess would be this doc page on Group Cell Renderers.

https://ag-grid.com/javascript-data-grid/group-cell-renderer/
