### ISSUE TITLE
suppressDragLeaveHidesColumns does not work when set based on input property of Angular component

### ISSUE THREAD

**Issue by karishma-grover07** [ag-grid/ag-grid#6384]
`<ag-grid-angular #gridReference class="ag-theme-balham" fxFill fxFlex="1 0 auto" [columnDefs]="gridParams.colDefs"
                        [sideBar]="this.readonly ? '' : gridParams.sideBar" [rowData]="gridParams.rowData" [suppressDragLeaveHidesColumns]="readonly"
                        [gridOptions]="gridParams.gridOptions" [modules]="gridParams.modules" [domLayout]="'autoHeight'">
                    </ag-grid-angular>`

**Current behavior**
When we use **suppressDragLeaveHidesColumns** as input property to ag-grid-angular, and set its value based on an input property called **readonly**. If value of readonly property is changed from false to true at runtime, then still user is able to drag out the columns from the ag grid table.

**Expected behavior**
**suppressDragLeaveHidesColumns** should disable the dragging out of columns when the input property 'readonly' value is changed dynamically to true.

* **AG Grid version:** 28.1.1

* **Browser:**
Google Crome Version 110.0.5481.178 (Official Build) (64-bit)

* **Language:** [Angular: 15.0.4 | TypeScript 4.8.4 ]

**Comment by StephenCooper** [comment]
Duplicates https://github.com/ag-grid/ag-grid/issues/6385
