### ISSUE TITLE
Setting columnMovePin and some other Icons through gridOptions causes an error.

### ISSUE THREAD

**Issue by paulieDOTjs** [ag-grid/ag-grid#6388]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

In this Plunkr I set a custom svg for the columnMovePin icon and the app crashes.

https://plnkr.co/edit/Zxi6bg9ANN49idTt?open=index.jsx

**Expected behavior**

In this Plunkr I set a custom svg for the sortAscending icon and there are no issues.

https://plnkr.co/edit/Iev9hqlzS5P0IcKu?open=index.jsx&preview

**Please tell us about your environment:**

React

* **AG Grid version:** X.X.X

29.1.0

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by NsdHSO** [comment]
Hi @paulieDOTjs, could you tried like this ? 
`  const gridOptions = useMemo(() => ({ icons: { columnMovePin: '<div><svg focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" fill="currentColor" width="32" height="32" viewBox="0 0 32 32" aria-hidden="true"><path d="M18 13L16.59 14.41 19.17 17 10 17 10 19 19.17 19 16.59 21.59 18 23 23 18 18 13z"></path><path d="M11.1716,6l3.4142,3.4142L15.1716,10H28V26H4V6h7.1716m0-2H4A2,2,0,0,0,2,6V26a2,2,0,0,0,2,2H28a2,2,0,0,0,2-2V10a2,2,0,0,0-2-2H16L12.5858,4.5858A2,2,0,0,0,11.1716,4Z"></path><title>Folder move to</title></svg></div>',
 } }), []);`

**Comment by paulieDOTjs** [comment]
@NsdHSO That DOES fix it. But I would still consider it a bug that certain icons require them to be wrapped in a div or span to render properly while others don't. Additionally, nowhere in the documentation is that listed.

**Comment by zoheil-ag** [comment]
Hi @paulieDOTjs,

Apologies it's taken some time to get back to you, but just letting you know this was fixed in our last major release v30.
See here: https://plnkr.co/edit/EmvTGUx8xutIbYJq?open=index.jsx

Thank you for reporting this.

Kind regards,
