### ISSUE TITLE
how to set  suppressSizeToAutoSizeColumn? 

### ISSUE THREAD

**Issue by vaynevayne** [ag-grid/ag-grid#6389]
look like 

```suppressSizeToFit:true```

**Comment by NsdHSO** [comment]
Hi @vaynevayne  could you give us more info about your issue?  I think this doc will help [you](https://www.ag-grid.com/react-data-grid/column-sizing/#size-columns-to-fit)

**Comment by vaynevayne** [comment]
> 

 @NsdHSO  If you know what suspressSizeToFit does, you know what I'm asking.

**Comment by StephenCooper** [comment]
Hi @vaynevayne,

Could you please provide a code reproduction for us to show your exact issue?

**Comment by vaynevayne** [comment]
> 

this is a feature request
