### ISSUE TITLE
Bug in selected rows count

### ISSUE THREAD

**Issue by shadoworion** [ag-grid/ag-grid#6390]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**
On select row it increases the count of selected rows, on deselect nothing will happen - it keeps accumulating.

**Expected behavior**
On select row it increases the count of selected rows, on deselect it decreases.

**Please tell us about your environment:** MacOS 13.1

* **AG Grid version:** 29.2.0

* **Browser:** Edge 110.0.1587.41

* **Language:** React 18

**Comment by StephenCooper** [comment]
Hi @shadoworion,

Thanks for reporting this. We have raised **AG-8232 When selecting grid rows, status bar selection count doesn't take into account de-selected rows** and will be fixing this for our next release. 

The workaround for now will be to pin the version to 29.1 as this only impacts 29.2.
