### ISSUE TITLE
Does applyColumnState need used in setTimeout ? 

### ISSUE THREAD

**Issue by vaynevayne** [ag-grid/ag-grid#6392]
hello, If you don't add setTimeout, it won't work. Why?

```jsx
const applyState = (state) => {
    gridRef.current?.columnApi.applyColumnState({
      state: state,
      applyOrder: true,
    })
  }

  useEffect(() => {

    setTimeout(() => {
      applyState(latestUpdateConfig.columnState) 
    }, 1000)
  }, [caseConfig, gridRef.current])
```

**Comment by StephenCooper** [comment]
Can you provide this in a work reproduction so that we can investigate why it appears to be required?

**Comment by vaynevayne** [comment]
https://stackblitz.com/edit/vitejs-vite-vasozr?file=src/App.tsx  @StephenCooper

**Comment by vaynevayne** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/124666577/229010691-6d8fe9ad-59eb-446a-9480-50a4d9d40562.png">
ref is given a value, but it's not equal to gridReady, right? @StephenCooper
