### ISSUE TITLE
 AG Grid: React Component 'noRowsOverlayComponent' not created within 1000ms

### ISSUE THREAD

**Issue by vaynevayne** [ag-grid/ag-grid#6395]
28.2 was used before, which is normal. After upgrading to 29.2, this error occurs in the development environment

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/124666577/228493842-08f04cc5-30fd-4e70-829d-5633d2dcfd40.png">

**Comment by seanlandsman** [comment]
Hi,

I'm afraid this that isn't enough information for us to provide any assistance. If you can provide a reproducible example we can take a look.

**Comment by vaynevayne** [comment]
i can't guess reason  also  no idea  to reproduce  maybe  need  else brother  provide  demo

**Comment by vaynevayne** [comment]
I find this is a historical problem that has come up before
