### ISSUE TITLE
Typescript typings for GetRowIdParams<T> do not allow `number` when they should

### ISSUE THREAD

**Issue by k290** [ag-grid/ag-grid#6401]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
 ```
 type Row ={
    employeeId: number;
};

 public getRowId: GetRowIdFunc = (params: GetRowIdParams<Row>) => params.data.employeeId
``` 

 gives Typescript error "Type number is not assignable to type string. "
 
 A current workaround is to erase the type and cast it to a string:  `params.data.employeeId as unknown as string`

**Expected behavior**
Since `number` is indeed actually supported for rowId, the typings should be updated to support `string | number` or similar

**Please tell us about your environment:**
Windows 11, VS Code.

* **AG Grid version:** 15.2.3

* **Browser:**

* **Language:** [TypeScript 4.9.5]

**Comment by seppo498573908457** [comment]
My code base is filled with these comments:
`getRowId: (params) => <any>(<unknown>params.data.id), // GridOptions.getRowId (GetRowIdFunc<TData>) function return value is typed as a string.`
We use TypeScript because we want strict typing. This is something you should fix.
