### ISSUE TITLE
Get cell value after format from grid apis.

### ISSUE THREAD

**Issue by Planit-Scheduler-Solutions** [ag-grid/ag-grid#6405]
Hi,
I have a question has I some way to get ag-grid cell value after format from the ag-grid apis?
I don't use renderer.

**Comment by StephenCooper** [comment]
This is not something that we expose outside of cell renderers as it is a derived value based off your cell data and any formatter that you provide. 

You may just need to access the data and run it through your formatter as part of your retrieval logic.

**Comment by ScriptType** [comment]
There is definetly a usecase for accessing the "shown" cell value,

For example an Object having a Date it needs to be formatted to a human readable localized date in the formatter.
The Sorting should work with the original Date Object, but the filtering (quickFilterText) for example should work with what is shown in the Cell, sure you can format it there again but its pretty heavy computation for something that is already computed once.

**Comment by joelrb** [comment]
> There is definetly a usecase for accessing the "shown" cell value,
> 
> For example an Object having a Date it needs to be formatted to a human readable localized date in the formatter. The Sorting should work with the original Date Object, but the filtering (quickFilterText) for example should work with what is shown in the Cell, sure you can format it there again but its pretty heavy computation for something that is already computed once.

Agree. I am having difficulty with this.

On onRowDataUpdated or onRowDataChanged, it should be as easy as

`var totalColumn = gridRef.current.api.getColumn("totalPrice");
console.log(totalColumn.value); //get cell value`

Suggestions in stackoverflow points to iterating the rownode to get the value. Not good.

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this. We are tracking it with the following reference: **AG-3889**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by joelrb** [comment]
> Hello,
> 
> Thank you for the suggestion.
> 
> Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this. We are tracking it with the following reference: **AG-3889**
> 
> We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.
> 
> See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page: https://www.ag-grid.com/ag-grid-pipeline/
> 
> The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).
> 
> Thanks again for bringing this up with us.
> 
> Kind regards, Zoheil

Thank you for creating a feature request for this. As it is, AG-Grid is already great. Adding features that make for faster development is very much welcome. Thanks!
