### ISSUE TITLE
Filter option "maxNumConditions" not working

### ISSUE THREAD

**Issue by pashaMalyshev** [ag-grid/ag-grid#6407]
I want to increase the number of conditions for a numeric filter, but it doesn't work for me. All other options work. I'm using version 28.2.1

My code:
`filter: "agNumberColumnFilter",
 filterParams: {
   filterPlaceholder: "Filtering...",
   defaultJoinOperator: "AND",
   maxNumConditions: 2,
   numAlwaysVisibleConditions: 2,
},`

**Comment by pashaMalyshev** [comment]
I am trying to add increase the number of conditions for a numeric filter. The code for the column looks like this:
`filter: "agNumberColumnFilter"`
`filterParams: {
filterPlaceholder: "Filtering...",
defaultJoinOperator: "OR",
maxNumConditions: 10,
numAlwaysVisibleConditions: 2,
}`
![Example](https://user-images.githubusercontent.com/103384547/228875292-0b4308cd-4153-4111-9ad6-060501e5ef0f.png)

But the parameters "maxNumConditions" and "numAlwaysVisibleConditions" do not change and remain by default.

**Comment by StephenCooper** [comment]
This feature was added in 29.2 so you will need to upgrade your version of AG Grid. The documentation is always accurate for the latest version of the grid. If you want to see the docs for older version you will need to use the [archive](https://ag-grid.com/archive/).
