### ISSUE TITLE
Breaking Changes and Deprecations empty in AG Grid Changelog 

### ISSUE THREAD

**Issue by dasboe** [ag-grid/ag-grid#6409]
<img width="873" alt="Bildschirm­foto 2023-03-30 um 17 38 12" src="https://user-images.githubusercontent.com/119371/228889794-167ab3be-05b0-4590-94b1-3c62e98da02e.png">

**Comment by seanlandsman** [comment]
Hi,

You have to have either (or both) Feature Requests or Defects selected - after that you can then additionally filter by Deprecations or Breaking Changes.

thanks,
