### ISSUE TITLE
[selection] Add support for 'multiple-additive' as a selection mechanism

### ISSUE THREAD

**Issue by llkyull** [ag-grid/ag-grid#642]
Requesting to add multiple-additive selection mechanism for touchscreen support where ctrl/meta key is not available.

I'm new to github and not entirely sure how to continue this but I have a partial fix for this where I've modified the lib. The changes below were done at the ag-grid.js level and not the .ts level(Please let me know if a pull request is more appropriate)
1. modified in GridOptionsWrapper:
   GridOptionsWrapper.prototype.isRowSelection = function () { return this.gridOptions.rowSelection === "single" || this.gridOptions.rowSelection === "multiple"};
   to
   GridOptionsWrapper.prototype.isRowSelection = function () { return this.gridOptions.rowSelection === "single" || this.gridOptions.rowSelection === "multiple" || this.gridOptions.rowSelection === "multiple-additive"; };
2. added in  GridOptionsWrapper:
   "GridOptionsWrapper.prototype.getMultiAdditive = function () { return this.gridOptions.rowSelection === "multiple-additive"; };"
3. modified in RenderedRow.prototype.createRowContainer:
   added:
   var multiAdditive = this.gridOptionsWrapper.getMultiAdditive();
   modified:
   var multiSelectKeyPressed = event.ctrlKey || event.metaKey;
   to
   var multiSelectKeyPressed = event.ctrlKey || event.metaKey || multiAdditive;

Current issues with implementation:
1. after data has been loaded and rendered and when changing from single/multiple to multiple-additive as well as the reverse, need to gridOptions.api.refreshView() so that selection works properly

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-99

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
