### ISSUE TITLE
Tooltip getting disappear while mouseover to the tooltip data

### ISSUE THREAD

**Issue by Surejmohan** [ag-grid/ag-grid#6428]
Hi Team,

I am using custom tooltip (tooltipComponent), but we are facing an issue while hovering to tooltip data it is disappearing. Can we avoid this? While hover over to tooltip we required some click function on tooltip content, without using custom cellrender. 

we are using react typescript.

**Comment by StephenCooper** [comment]
Hi @Surejmohan,

We would need a reproduction to be able to investigate this further for you.

**Comment by danielmalaton** [comment]
When hovering on the first cell of `Athlete`, this tooltip appears. But when I hover over the data of the tooltip, the tooltip goes away.
https://github.com/ag-grid/ag-grid/assets/106505755/a4a324e8-d120-41bf-aacc-058d6bdb43c8

**Comment by zoheil-ag** [comment]
Thank you for your comment @danielmalaton, we have now allocated this issue to an item in our backlog AG-3523. Updates can be followed via our [pipeline](https://ag-grid.com/pipeline/).
