### ISSUE TITLE
 refreshServerSide make the table lost its columnState

### ISSUE THREAD

**Issue by minaairsupport** [ag-grid/ag-grid#6433]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Expected behavior**

I am using rowModel='server-side'
I saved my columnState in Redux state and in some cases I need to refresh the table but when I am firing `api?.refreshServerSide()` I lost my current columnState

normally I restore the column state like this way 
```
const onFirstDataRendered = useCallback((params: FirstDataRenderedEvent) => {
    if (columnState) {
      params.columnApi.applyColumnState({
        state: columnState,
        applyOrder: true,
      });
    }
  }, []);
```

normally we should not lost columnState when table refreshed or at least have a flag to retian the columnState

**Please tell us about your environment:**

* **AG Grid version:** 29.0.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

More info https://stackoverflow.com/questions/75943205/ag-grid-refreshserverside-make-the-table-lost-its-columnstate

**Comment by AndrewGlazier** [comment]
Hello!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (ideally using plunker) - you can extend a similar example found in our docs to demonstrate your issue.
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by minaairsupport** [comment]
this a the repo 

https://plnkr.co/edit/o6N49h9VPqOgboCI?open=index.tsx

steps to replicate the issue
1- resize or re-order the columns // it will be saved in local storage 
2- refresh the page 
  expected behavior to restore the old state 
  but what happens I got the initial column state.

 I got the initial column state as well when  `ColDef` changed (add or remove column)
 Thanks and please let me know if this make sense for you or you need any extra info

**Comment by StephenCooper** [comment]
I have now raised this internally. Please note you will get faster support if you use your Enterprise license to raise support tickets via ZenDesk.
