### ISSUE TITLE
Does rowDragEntireRow support show   blue mark line ?

### ISSUE THREAD

**Issue by vaynevayne** [ag-grid/ag-grid#6434]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/124666577/230268574-8011b045-4796-4940-b7ff-4a5cdc9d7d6b.png">

**Comment by StephenCooper** [comment]
Hi @vaynevayne,

We use Github issues for bug reports as we do not have the capacity to answer general questions here. Please take advantage of the AG Grid community on Stackoverflow with questions or access our support via an Enterprise account.

**Comment by vaynevayne** [comment]
> Hi @vaynevayne,
> 
> We use Github issues for bug reports as we do not have the capacity to answer general questions here. Please take advantage of the AG Grid community on Stackoverflow with questions or access our support via an Enterprise account.

hello  , can you open discuss panel?
