### ISSUE TITLE
ag-theme-alpine-dark.css does not exist

### ISSUE THREAD

**Issue by McCulloughRT** [ag-grid/ag-grid#6438]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I am attempting to use the Alpine Dark theme. Following the [documentation](https://ag-grid.com/react-data-grid/themes/).
Cannot resolve 'ag-grid-community/styles/ag-theme-alpine-dark.css'. I have confirmed the file does not exist in my node_modules, or in the ag-grid-community package (version 29.2.0) on NPM. It also does not exist on the [CDN](https://cdn.jsdelivr.net/npm/ag-grid-community@29.2.0/styles/ag-theme-alpine-dark.css) shown in the documentation. Examining prior versions on NPM, it appears the file has not existed since version 28.0.0 and was lost when the file structure changed from /dist/ to /styles/.

**Expected behavior**

I would expect the file to exist as shown in the documentation linked above. Correct/desired behavior can be seen in the canonical AG Grid demo when switching to "Alpine Dark" theme.

**Please tell us about your environment:**

Ubuntu 20.04 / VS Code / NPM / React / Typescript

* **AG Grid version:** 29.2.0

* **Browser:** Issue occurs at compile stage / browser not relevant.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] Typescript 4.4.4

**Comment by McCulloughRT** [comment]
My mistake, I discovered that the standard and dark themes are combined into the standard file and can be switched between using the theme class name on the containing div.

**Comment by Pawel-IT** [comment]
> My mistake, I discovered that the standard and dark themes are combined into the standard file and can be switched between using the theme class name on the containing div.

Can you give an example? The documentation is outdated and states to use a dark import of the theme and don't see any mention on how to set a parent div. Thanks!

**Comment by giladfuchs** [comment]
In my case (AG Grid v34) the dark theme didn’t apply because I had both of these imports:

`@import 'ag-grid-community/styles/ag-grid.css';`
`@import 'ag-grid-community/styles/ag-theme-quartz.css';`

This combination caused ag-theme-quartz-dark to do nothing.

so i remove the base import and keep only the theme:
`@import 'ag-grid-community/styles/ag-theme-quartz.css';`

After that, the dark theme toggle worked correctly.
