### ISSUE TITLE
Status Bar Panels is not working in agGrid version 26.

### ISSUE THREAD

**Issue by rafee11** [ag-grid/ag-grid#6439]
Status Bar Panels is not working in agGrid verion 26.1.0 and Angular v12. I have followed the steps mention on this document https://www.ag-grid.com/angular-data-grid/component-status-bar/

Do we have Status Bar Panels feature in version 26?

**Comment by StephenCooper** [comment]
Yes this was present in v26. You can find the documentation for v26 here which may unblock you.

https://www.ag-grid.com/archive/26.2.0/angular-data-grid/status-bar/

**Comment by rafee11** [comment]
@StephenCooper  Still i am not getting the status bar and also side bar, I can able to get pagination alone as below screenshot
![image](https://user-images.githubusercontent.com/23078836/231181190-4ed6c952-e311-4bf7-823f-873075d2cace.png)

Only difference is that I am populating the ag-grid table on the MatDialog (Popup modal) in Angular version 12

**Comment by rafee11** [comment]
@StephenCooper Do I need license to enable these features? 
![image](https://user-images.githubusercontent.com/23078836/231183446-f16bc768-ff32-40eb-950a-165492ed565b.png)

**Comment by StephenCooper** [comment]
Yes, you will need a license but it comes down to not importing the enterprise package. More recent versions of AG Grid would have given you a clear console warning telling you this.

**Comment by ZaBovv** [comment]
i have it seems the same problem, but i don't know how to fix it, i have the enterpraise. it load on other component but if i try to open my modal with the ag grid it show off the grid
