### ISSUE TITLE
using filter='agSetColumnFilter', click the input beside the filter icon, some Chrome browser input cannot trigger click

### ISSUE THREAD

**Issue by loveheavenlina** [ag-grid/ag-grid#6442]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
some versions of Chrome brower have compatibility issues.
using filter='agSetColumnFilter',  click the input beside the filter icon, some Chrome browser input cannot trigger click

**Expected behavior**
using filter='agSetColumnFilter',  click the input beside the filter icon, all Chrome browser input cannot trigger click

* **AG Grid version:** 
"ag-grid-community": "^28.1.1",
"ag-grid-enterprise": "^28.1.3",
"ag-grid-react": "^28.1.1"

* **Browser:**
Version 110.0.5481.78 (Official Build) (64-bit)

* **Language:**
"typescript": "^4.6.4"

**Comment by StephenCooper** [comment]
Please provide a reproducible example and details on chrome versions but please be aware that we only support the two last major versions as outline [here](https://ag-grid.com/javascript-data-grid/supported-browsers/).
