### ISSUE TITLE
Nesting Dynamic Height

### ISSUE THREAD

**Issue by dalexander-trc** [ag-grid/ag-grid#6443]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
Forked from [Nested Auto Height Grid](https://www.ag-grid.com/javascript-data-grid/master-detail-nesting/#example-auto-height) with code snippet from [Dynamic Height](https://www.ag-grid.com/javascript-data-grid/master-detail-height/#dynamic-height)
https://plnkr.co/edit/1M3XTcdy2D9XFktQ

**Current behavior**
![image](https://user-images.githubusercontent.com/37082684/230905707-d842b641-e101-4c1f-845b-f833590c776b.png)
A large empty space displays where the third nested grid records will be. This space is not big enough to fit all the records if level 2 is expanded. Note the scroll bars in the below record.

**Expected behavior**
![image](https://user-images.githubusercontent.com/37082684/230905957-e545c75d-691b-4b14-b466-af4aba022eae.png)
The second level grid is collapsed to it's minimum size. If level 2 is expanded, it will expand to show all of the records from level 3 and push the records below down.

**Please tell us about your environment:**

* **AG Grid version:** 27.3.0 - 29.2.0

* **Browser:** Chrome 111.0.5563.147

* **Language:** All

**Comment by StephenCooper** [comment]
I have raised this internally. Please note you would get faster support responses if you use your Enterprise license to request support.

**Comment by AndrewGlazier** [comment]
Hi,

This is caused as ag-grid has a minimum grid height, we document removing this height here:
https://www.ag-grid.com/javascript-data-grid/grid-size/#grid-auto-height

Note below the example we state:

> When using Auto Height, there is a minimum of 150px set to the grid rows section. This is to avoid an empty grid which would look weird. To remove this minimum height, add the following CSS:
>`.ag-center-cols-clipper {
    min-height: unset !important;
}`

By utilising this css snippet you should be able to remove the minimum row height from the grid and attain your desired result when used in conjunction with `detailRowAutoHeight: true`.

I've put together this example to demonstrate:
https://plnkr.co/edit/Bc9IpnjHOeRXjxRc?open=main.js

Regards,
