### ISSUE TITLE
SSRM filtering - filtering a string column through 'not equals' generates a wrong query

### ISSUE THREAD

**Issue by ConteClaudioSalvatore** [ag-grid/ag-grid#6453]
**I'm submitting a ...** 
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'

While i was navigating the documentation i found out that if you use a text filter, `not equals` will generate a wrong query 
infact this is an example from the documentation:

![image](https://user-images.githubusercontent.com/74454087/231461040-1ef2f638-403d-4357-8d8e-6c5e5f4dde69.png)

**Current behavior**
select the filter type `not equals`, type at least 1 character

the generated query will have a `'` character after the field to apply the filter on

**Expected behavior**
the 'query generator' should not place the `'` character there

**Please tell us about your environment:**
[where i first fount the error at](https://ag-grid.com/react-data-grid/server-side-model-selection/)

* **AG Grid version:** 29.2.0

* **Browser:** Microsoft edge 112.0.1722.39

* **Language:** all

**Comment by AndrewGlazier** [comment]
Hi,

Thanks for pointing this out.

We'll aim to have these doc examples fixed in our next release (v29.3.0)
