### ISSUE TITLE
[AG Grid Vue] params from `cellStyle` does not update immediately

### ISSUE THREAD

**Issue by danielmalaton** [ag-grid/ag-grid#6457]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Context**
I'm using `cellStyle` to format the cell. The snippet code is like this:
```Typescript
columnDefs = { field: 'Sport', cellStyle: getCellStyle }

const getCellStyle = (params) => {
  console.log(params);
 // return CSS object
}
```
**Current behaviour**
Let's say after the grid is initialized. I want to modify the grid (add more columns and row data) from the outside (not using AG-Grid API). After seeing the log, I think the `params` does not update immediately. It still contains the old data (not with the new columns and row data I have added). After logging all the old data, it updates with the new data

**Expected behaviour** 
The `params` must update immediately. Not contains the old data anymore

* **AG Grid version:** 29.2.0

* **Browser:**
Chorme

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript, Vue

**Comment by StephenCooper** [comment]
Can you provide a reproduction of this for us to see? It is not clear how you are updating the rows / columns without the api and if this is the cause of the issue.
