### ISSUE TITLE
How to know when rendering has finished for rows in ag-grid?

### ISSUE THREAD

**Issue by kanikabahri-repo** [ag-grid/ag-grid#6460]
<!--**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Requesting Community Support

Basically, I have a question which is similar to issue: https://github.com/ag-grid/ag-grid/issues/4090, which is closed but reading its comments have not resolved the issue.

We are using ag-grid, when we have records more than 1000 we use pagination, but while the first 1000 records are rendering, I dont have any callback or any property provided  which I can use to show loader so that user dont interact with UI. Currently when grid loads, data is fetched and set to grid gridReady is fired after that loader is stopped and user interacts with the grid, like user clicks on selectsAll for the grid which should select all the rows, but till now all the rows are not rendered on UI because of which it creates issues in calculation.

Any help in this issue will be appreciated.

**Comment by StephenCooper** [comment]
Does the `firstDataRendered` event not work for you? This sounds like the event you require?

https://ag-grid.com/javascript-data-grid/grid-events/#reference-miscellaneous-firstDataRendered

**Comment by kanikabahri-repo** [comment]
@StephenCooper : I tried using this but this event fires before the data is rendered into the ag-grid.

**Comment by kanikabahri-repo** [comment]
Yes, thats correct after user clicks on selectAll in header it should select all the rows i.e for this grid is 1000 for the first page but due to enormous size of the first page the grid takes time to load the rows.
I will add the reproduction of the same.
Thank you @StephenCooper .

**Comment by StephenCooper** [comment]
Closing for now. Feel free to re-open with your reproduction.
