### ISSUE TITLE
feature - set filter

### ISSUE THREAD

**Issue by Alkimay** [ag-grid/ag-grid#6477]
hey i would like to ask if its possible to make 3 things
1. for agSetFilter will be also floating filter. if the user want to type in the table it will put autocomplete floating 
2. if the user pressed enter to select all current filter values in the mini filter, then the text will be deleted so it can write more names and not press delete and the write more..
3. add also X on the end of the text so the user can click to reset the text in the minifilter. 
thanks
![image](https://user-images.githubusercontent.com/96352572/232540154-b66040d1-1b26-4807-900a-490394faa303.png)

**Comment by StephenCooper** [comment]
Hi @Alkimay,

We use github issues for bug reports only. To request additions to Enterprise features please submit via your AG Grid Enterprise license via https://ag-grid.zendesk.com/ as that is the best way to ensure this gets prioritised appropriately.
