### ISSUE TITLE
Upgrading to v28 - Missing "Beans" in RowNode constructor in unit tests

### ISSUE THREAD

**Issue by Manish-Giri** [ag-grid/ag-grid#6481]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I just upgraded from v20 to v28 in our Angular project, and now I'm facing several breaking changes with regards to types and definitions. One of them being the constructor of `RowNode()`.  

In my unit tests (spec.ts), I have new node created as follows -

```typescript
node = new RowNode();  // ERROR - TS2554: Expected 1 arguments, but got 0.
node.data = {};
```
Now, this is throwing an error -

![image](https://user-images.githubusercontent.com/11348778/232666136-a41b209c-6452-4ae9-86ea-dddd6db37ecc.png)

I couldn't find any documentation on what "Beans" is, or how I can create one for this particular use case -

![image](https://user-images.githubusercontent.com/11348778/232666296-4ad74554-a45f-450d-8d59-67b19ddeedc8.png)

**Current behavior**

After upgrading to v28, constructor for `RowNode()` expects an argument of type `Beans`. 

**Please tell us about your environment:**

* **AG Grid version:** 28

* **Browser:** Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi @Manish-Giri,

Beans refers to our internal dependency injection framework. In AG Grid all row nodes are created internally by the grid hence its use of this feature.

I am not sure what you are trying to test that requires you to manually create a RowNode but I think you may have to find an alternative approach.
