### ISSUE TITLE
[Bug] ag-grid-solid has unwanted border style and function class

### ISSUE THREAD

**Issue by namnguyen279** [ag-grid/ag-grid#6492]
**I'm submitting a Bug
[X] bug report

Current behaviour.
1. On js version, ag-header and ag-floating-bottom do not render extra borders in  .ag-header and  ag-floating-bottom. While using library ag-grid-solid produce extra border style in .ag-header and .ag-floating-bottom without horizontal scrollbar or content in it.
2.  Some className come with unwanted function () { [native code] } in it 

**Expected behavior**
1. It should produce has display:none like js version for consistency.
2. Remove these function string in it 

**Please tell us about your environment:** Macos
* **AG Grid version:** 29.3
* **Browser:** Chrome
* **Language:** [TypeScript 4+]
* I use Vite, sass plugin

**Comment by zoheil-ag** [comment]
Hi @namnguyen279 ,

Thank you for reporting this.

We'd be happy to look into this but the most efficient way for us to do this is to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by zoheil-ag** [comment]
Hi @namnguyen279,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by AlexErrant** [comment]
Reproduction in the above issue.
