### ISSUE TITLE
Changed cells are not highlighted when sorting is active

### ISSUE THREAD

**Issue by DavidSanek** [ag-grid/ag-grid#6493]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Reproducible Scenario**
See Plunker with an example:
https://plnkr.co/edit/yjXyQP7XLzFm4cGs

**Current behavior**
I have a grid with live update transactions. When the transactions are applied, changed cells should be highlighted. This works well when there are not many rows. But in my example I have 100 rows, sorted by the highest value. When some rows are updated, they get reordered correctly but only some of them are highlighted.

I think the cell is not highlighted when the row was outside the viewport before the update so the highlight classes are not applied to it.

**Expected behavior**
All cells should be highlighted on update, no matter where they are and how they are sorted.

* **AG Grid version:** 29.3.0

* **Browser:**
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

* **Language:** TypeScript

**Comment by AndrewGlazier** [comment]
Thanks for opening this, we've responded to your query in zendesk so will now be closing this ticket.

**Comment by DavidSanek** [comment]
For anyone with the same issue, it's now tracked as a bug in the pipeline:

**AG-8446 - When updating cells which are not rendered, they do not flash when moving into viewport**
https://www.ag-grid.com/pipeline/
