### ISSUE TITLE
Multiple flushSync warning after upgrading to the latest 29.3.2

### ISSUE THREAD

**Issue by staticdreams** [ag-grid/ag-grid#6504]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Upgrading from v 29.2.0 to 29.3.2

**Current behavior**
Upon rendering the table console generates a ton of warning messages (currently 9000+ for one single table and counting):

```
react_devtools_backend.js:2655 Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
    at RowContainerComp (http://localhost:3000/static/js/bundle.js:230891:25)
    at div
    at div
    at GridBodyComp (http://localhost:3000/static/js/bundle.js:228786:20)
    at TabGuardCompRef (http://localhost:3000/static/js/bundle.js:231066:24)
    at div
    at div
    at GridComp (http://localhost:3000/static/js/bundle.js:229094:20)
    at div
    at AgGridReactUi (http://localhost:3000/static/js/bundle.js:227320:24)
    at AgGridReact (http://localhost:3000/static/js/bundle.js:226657:43)
    at div
    at div
    at DataTable (http://localhost:3000/static/js/bundle.js:3151:5)
 ```

**Expected behavior**
Prior upgrading from 29.2.0 to 29.3.2 I did not experience any issues of this sort.

**Please tell us about your environment:**
Windows 10, node 18, react 18

* **AG Grid version:** X.X.X
All three versions (community, enterprise and react version upgraded to **29.3.2**)

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'

* **Language:** ES6/7

**Comment by yq756530939** [comment]
I also encountered this problem ！！！

**Comment by numofran6** [comment]
I am also experiencing this problem. Does it occur on the enterprise version also?

**Comment by numofran6** [comment]
issue resolved on my end after updating package

**Comment by staticdreams** [comment]
@StephenCooper thank you! That seem to have fixed the issue. Great support.
I'll close the ticket.

**Comment by conquer1357** [comment]
This warning still occurs when we use the setRowData API.

**Comment by conquer1357** [comment]
@StephenCooper This warning still occurs when we use the setRowData API.

**Comment by btmohit** [comment]
Error disappeared after installing latest packages in my Next app.

```
package.json

"ag-grid-community": "^29.3.3",
"ag-grid-enterprise": "^29.3.3",
"ag-grid-react": "^29.3.3",
```

**Comment by StephenCooper** [comment]
> @StephenCooper This warning still occurs when we use the setRowData API.

Could you provide a reproduction of this as when I try just using the api it does not log the warning.

**Comment by StephenCooper** [comment]
Could you share the code that is calling tue API method?

**Comment by janhartmann** [comment]
Something along this:

```ts
export const Table = ({ data }) => {
  const [gridApi, setGridApi] = React.useState<
    GridApi<Model> | undefined
  >(undefined);

  React.useEffect(() => {
    gridApi?.setRowData(data);
  }, [gridApi, data]);

  React.useEffect(() => {
    const subscription = createSubscription((entries) => {
      if (Object.keys(entries).length === 0) {
        return;
      }
      const rowDataTransaction = Object.entries(entries).reduce<
        RowDataTransaction<Model>
      >(
        (transaction, [id, extra]) => {
          const row = gridApi?.getRowNode(id);
          if (row && row.data?.entity) {
            transaction.update?.push({
              id,
              entity: row.data.entity,
              extra
            });
          }
          return transaction;
        },
        {
          add: [],
          update: [],
          remove: []
        }
      );

      gridApi?.applyTransactionAsync(rowDataTransaction);
    });

    return () => {
      subscription.unsubscribe();
    };
  }, [gridApi]);

  const handleGridReady = React.useCallback((grid: GridReadyEvent) => {
    grid.api.sizeColumnsToFit();
    setGridApi(grid.api);
  }, []);

  return (
    <AgGrid
      gridOptions={options}
      enableCellChangeFlash={true}
      onGridReady={handleGridReady}
    />
  );
};
```

**Comment by StephenCooper** [comment]
Thanks for sharing, your code, that will help me.

**In the meantime pinning to `29.3.0` will avoid the issue.**

**Comment by StephenCooper** [comment]
We have released a follow up patch of `29.3.4` which has further improvements into the `flushSync` logic which resolves all currently reported instances of this error. 

Once again, please let us know if even with `29.3.4` you still run into this error.

**Comment by staticdreams** [comment]
@StephenCooper thanks Stephen. I just upgraded to the latest version and I don't have any issues.
Feedback from others is also appreciated :)

**Comment by Kuchasz** [comment]
@StephenCooper I've just bumped ag-grid from 29.2.0 to 29.3.4. I also confirm that these "flushSync" issues are gone. Previously i couldn't use 29.3.x at all.

**Comment by janhartmann** [comment]
Confirm it worked.
