### ISSUE TITLE
Modules import missing Event types

### ISSUE THREAD

**Issue by destradafilm** [ag-grid/ag-grid#6506]
**I'm submitting a ...**  (check one with "x")
```
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
I'm using `@ag-grid-community/vue`

I switch from package import to a module import. But I can't find some types I was previously using

reference of Module import I'm taking about:
https://www.ag-grid.com/vue-data-grid/modules/

The problem is that the docs suggests finding which module we need by checking the Plunkr examples with the Modules dropdown. For the following I havent' found any docs that reference these types

I assumed the following were included in `@ag-grid-community/core` but I can't find them

I CAN'T FIND THE FOLLOWING
```
  BodyScrollEvent,
  GridReadyEvent
  SelectionChangedEvent
  RowClickedEvent
```

**Please tell us about your environment:**

* **AG Grid version:** 29.3.2
packages installed
    "@ag-grid-community/core": "^29.3.2",
    "@ag-grid-community/styles": "^29.3.2",
    "@ag-grid-community/vue": "^29.3.2",
    "@ag-grid-enterprise/server-side-row-model": "^29.3.2",
    "@ag-grid-enterprise/menu": "^29.3.2",
    "@ag-grid-enterprise/row-grouping": "^29.3.2",

**Comment by StephenCooper** [comment]
I have checked and all of those types are correctly exported from `@ag-grid-community/core` and I am able to import them into a Typescript project. 

Can you please provide a reproduction that shows these types missing as from what I can see they are there.
