### ISSUE TITLE
Since AG-8064 in 29.3.0 - domLayout 'autoheight' forced to 'normal' for 'serverSide' rowModelType

### ISSUE THREAD

**Issue by mattlgroff** [ag-grid/ag-grid#6507]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
We're using the 'serverSide' rowModelType and 'domLayout: 'autoHeight'

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Grid: domLayout='autoHeight' was ignored as it is only supported by the Client-Side row model.

**Expected behavior**
It was supported and working fine in 29.2.0. After the update, I have no way to use `autoHeight` as this warning also sets the domLayout to `normal` by force. Our client doesn't want to scroll inside the table and we don't want a static value. Some rows are different heights depending on the incoming data and we can't use the pageSize to estimate as the results might be less than the pageSize. Please don't enforce domLayout='normal' with the warning. 

**Please tell us about your environment:**

Ubuntu 23
VS Code
Npm 

* **AG Grid version:** 29.3.2

Yes, since 29.3.0

* **Browser:**
* 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.9.4

**Comment by AndrewGlazier** [comment]
Hi Matt,

Thanks for reporting this, we agree we missed a requirement when implementing this change.

The approach we've decided to take is to allow `domLayout="autoheight"` when pagination is enabled, and you should see this change from our next release.

You can track this with:
AG-8428 - [Regression] When using SSRM and pagination domLayout='autoHeight' is ignored

Regards,
