### ISSUE TITLE
has any method control zoom change

### ISSUE THREAD

**Issue by dxFlue** [ag-grid/ag-grid#6509]
We want to change table scale, just not through the browser. How can I initial the table zoom?

**Comment by StephenCooper** [comment]
Our documentation lists the possible style customisation points. This is the best part to check for the features that you require. There is not a single method that will automatically scale everything like a zoom change. 

https://ag-grid.com/javascript-data-grid/global-style-customisation/

I will leave the ticket open to see if anyone from the AG Grid community has any input they would like to add above our documentation.
