### ISSUE TITLE
headerClass: not working for aligning header text purpose

### ISSUE THREAD

**Issue by duzliang** [ag-grid/ag-grid#6514]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A plunker: [Example Code on plunker](https://plnkr.co/edit/o5ZzCrv7FOF4rDes?open=index.jsx)

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

```css
    text-right {
         justify-content: 'flex-end';
     }
```
```typescript
const [columnDefs, setColumnDefs] = useState([
    // group cell renderer needed for expand / collapse icons
    { field: 'name', cellRenderer: 'agGroupCellRenderer' },
    { field: 'account', headerClass: 'text-right' },
    { field: 'calls' },
    { field: 'minutes', valueFormatter: "x.toLocaleString() + 'm'" },
  ]);
```

**Current behavior**
use headerClass to set Header's text align to right or center is impossible

**Expected behavior**
can use `headerClass` to align header's text

**Please tell us about your environment:**
macOS 13.2.1

* **AG Grid version:** X.X.X
29.3.3

* **Browser:**
'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript, React

**Comment by StephenCooper** [comment]
You can achieve this with the following class.

```
    { field: 'account', headerClass: 'ag-right-aligned-header' },
```

https://plnkr.co/edit/okbP49FD2VfWTrK6?open=index.jsx

Taken from this part of the [docs](https://ag-grid.com/react-data-grid/column-definitions/#right-aligned-and-numeric-columns).

**Comment by duzliang** [comment]
Thanks for your help, I used  the headerClass in a wrong way:(
