### ISSUE TITLE
don't work with many grid

### ISSUE THREAD

**Issue by cc616** [ag-grid/ag-grid#6525]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

I need create many grid, but I use this demo not work, nothing render
https://plnkr.co/edit/?p=preview&preview

**Comment by StephenCooper** [comment]
You need to save the plunker before sharing as otherwise the link does not work.

**Comment by cc616** [comment]
> You need to save the plunker before sharing as otherwise the link does not work.

sorry, this link: https://plnkr.co/edit/NFUrlPiccZrxBCjo

**Comment by StephenCooper** [comment]
Not sure what the issue is but seem to be working fine from your link. 

![Screenshot 2023-04-27 at 12 02 33](https://user-images.githubusercontent.com/20125490/234843654-6e540d32-d76d-4d9a-9ee5-124231498510.png)

**Comment by StephenCooper** [comment]
Going to close as I do not believe there is an issue here with the Grid.
