### ISSUE TITLE
Master - Detail Grid - Row Grouping (Cut, Copy and Paste Range Selection Issue) 

### ISSUE THREAD

**Issue by VenkatSagi9** [ag-grid/ag-grid#6528]
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community _Support'_

**Current behavior**

I am using **ag-grid-enterprise** with **Mater Details Grid, Row Grouping, Cut, Copy and Paste** operations

I have a scenario like, I can **expand master grid rows or row groups** and perform **cut copy paste** operations on master grid rows. I need to restrict **cut copy paste** operations on **detailed/grouped rows**. When I am trying to select cell ranges on master grids rows and perform copy to clipboard which includes detailed/grouped rows to clipboard and after paste empty rows got added in between master grid rows. I tried to debug **onRangeSelectionChanged** event and found row index of grouped/detailed rows got included range selection.

**Expected behavior**

I want to perform **cut, copy, paste** operations on master grid rows and exclude **detailed/grouped row** in between master grid rows to perform **copy to clipboard or paste from clipboard.**

Please tell us about your environment:
React

AG Grid version: ^28.2.1

Browser:
Chrome

Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Please provide a reproduction so that we can investigate this for you.

**Comment by VenkatSagi9** [comment]
Please have a look on below example and try to do **range selection with multiple groups** and perform **cut copy paste** operations. 

[](https://plnkr.co/edit/9atsgsJkWM5vi6oQ?open=index.jsx&preview)

**Comment by VenkatSagi9** [comment]
@StephenCooper Any update on the ticket raised?

**Comment by StephenCooper** [comment]
@VenkatSagi9 if you want guaranteed responses please use your Zendesk account, especially as this is an Enterprise feature. We prioritise Zendesk tickets and work on those first. I have not looked into this issue yet.

**Comment by StephenCooper** [comment]
I believe you will be able to achieve what you want using the post processing methods as part of the clipboard. 

https://ag-grid.com/javascript-data-grid/clipboard/#processing-individual-cells

If you still require further assistance please contact us via your ZenDesk account.
