### ISSUE TITLE
Last row num show '?' after pageSize changed from 10 to 50 and recall the dataSource which has 95 records in total

### ISSUE THREAD

**Issue by sgkuki** [ag-grid/ag-grid#6537]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
v25.3.0
plunker link: https://plnkr.co/edit/pnyP9rjwBVWdk0Oy?open=lib%2Fapp.ts&deferRun=1

Current behaviour.
In pagination panel, last row num shows '?' after click the button and change pageSize from 10 to 59.
The issue will not happen if total records is lower than 10.

**Expected behavior**
last row num shows the actual num of rows.

**Please tell us about your environment:**
angular: 12.2.16
node: 14.21.3
ag-grid: 25.3.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

will in vacation next week, so may wont reply this case before May 5.

**Comment by StephenCooper** [comment]
Your plunker does not load unfortunately. When you are back please try with 29.3 as if there is an issue we fix going forward and don't patch older versions.
