### ISSUE TITLE
How can I allow change group order and prohibit change subheaders order (even inside in group)?. suppressMovable not working for group

### ISSUE THREAD

**Issue by KirillBabuak** [ag-grid/ag-grid#6539]
I use React component and have the follow columnDefs data structure:
`const columnDefs: (ColDef | ColGroupDef)[] = [
    {
      headerName: 'GroupA',
      groupId: 'groupA',
      marryChildren: true,
      suppressMovable: false,
      children: [
        {
          headerName: 'GroupdA_1',
          field: 'groupdA_1',
          minWidth: 240,
          suppressMovable: true
        },
       {
          headerName: 'GroupdA_2',
          field: 'groupdA_2',
          minWidth: 240,
          suppressMovable: true
        },
      ],
    },
    {
      headerName: 'GroupB',
      groupId: 'groupB',
      marryChildren: true,
      suppressMovable: false,
      children: [
        {
          headerName: 'GroupdB_1',
          field: 'groupdB_1',
          minWidth: 240,
          suppressMovable: true
        },
        {
          headerName: 'GroupdB_2',
          field: 'groupdB_2',
          minWidth: 240,
          suppressMovable: true
        },
      ],
    },
{
      headerName: 'GroupC',
      groupId: 'groupC',
      marryChildren: true,
      suppressMovable: false,
      children: [
        {
          headerName: 'GroupdC_1',
          field: 'groupdC_1',
          minWidth: 240,
          suppressMovable: true
        },
        {
          headerName: 'GroupdC_1',
          field: 'groupdC_1',
          minWidth: 240,
          suppressMovable: true
        },
      ],
    }]`

`<AgGrid
      groupHeaderHeight={46}
      rowData={rowData}
      columnDefs={columnDefs}
      defaultColDef={{
        menuTabs: ['columnsMenuTab'],
        cellRenderer: TableCell,
        cellStyle: {
          ...styles.cellStyle,
        } as ColDef['cellStyle'],
        autoHeight: true,
      }}
    />`

I need to prevent moving columns that in the children list, but I would like to have the possibility to change order groups using drag and drop. The issue is if we set suppressMovable: true for all children, groups aren't movable as well even if I add suppressMovable: false for groups.

I use "@ag-grid-community/react": "^27.1.0",

**Comment by StephenCooper** [comment]
Please provide a reproduction with your configuration for us to investigate. Feel free to Fork this https://plnkr.co/edit/LWenZ602U7Nj8ufe?open=index.tsx

**Comment by KirillBabuak** [comment]
@StephenCooper Thank you for the link. you can take a look at my configuration https://plnkr.co/edit/gw7i3Fm4d3Ac4VlC?open=index.tsx
As I wrote above, I need to be able to use drag and drop to change GroupA, GroupB, and GroupC, but GroupA_1, GroupA_2, GroupB_1, GroupB_2, GroupC_1, GroupC_2 should not be movable even in the group (as in my example). PS: subheader can be movable with the group, but in group, they should be static. Simply world, I need to move only groups. I hope I have described my problem clearly. Thank you in advance for the help

**Comment by StephenCooper** [comment]
Thanks for that. I have found that we have an existing feature request for this with reference 

**AG-2470 [Column Group] Allow suppressing column moving for column groups**

I have commented on that issue with this link to record another request for this feature. 

<hr>

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.
