### ISSUE TITLE
feat: support to define component of ag-grid  use <script setup> in vue

### ISSUE THREAD

**Issue by L1yp** [ag-grid/ag-grid#6541]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `ag-grid-vue3@29.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/ag-grid-vue3/lib/VueFrameworkComponentWrapper.js b/node_modules/ag-grid-vue3/lib/VueFrameworkComponentWrapper.js
index a142008..1fe9dd0 100644
--- a/node_modules/ag-grid-vue3/lib/VueFrameworkComponentWrapper.js
+++ b/node_modules/ag-grid-vue3/lib/VueFrameworkComponentWrapper.js
@@ -17,12 +17,21 @@ export class VueFrameworkComponentWrapper extends BaseComponentWrapper {
                 super.init(params);
             }
             hasMethod(name) {
-                return wrapper.getFrameworkComponentInstance()[name] != null;
+                const componentInstance = wrapper.getFrameworkComponentInstance()
+                if (!componentInstance[name]) {
+                    return componentInstance.$.setupState[name] !== null
+                } else {
+                    return true
+                }
             }
             callMethod(name, args) {
                 const componentInstance = this.getFrameworkComponentInstance();
                 const frameworkComponentInstance = wrapper.getFrameworkComponentInstance();
-                return frameworkComponentInstance[name].apply(componentInstance, args);
+                if (frameworkComponentInstance[name]) {
+                    return frameworkComponentInstance[name].apply(componentInstance, args);
+                } else {
+                    return frameworkComponentInstance.$.setupState[name]?.apply(componentInstance, args);
+                }
             }
             addMethod(name, callback) {
                 wrapper[name] = callback;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by StephenCooper** [comment]
Hello,

Thank you for bringing this up with us. 

You can track it with this reference:
AG-8274 Support Custom Vue 3 Components in <script setup>

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-8274) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by L1yp** [comment]
> Hello,
> 
> Thank you for bringing this up with us.
> 
> You can track it with this reference: AG-8274 Support Custom Vue 3 Components in <script setup>
> 
> You can follow the status of feature requests, bugs and releases using our pipeline: https://www.ag-grid.com/ag-grid-pipeline/
> 
> Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-8274) on the changelog page to see if it's resolved in that version: https://www.ag-grid.com/ag-grid-changelog/
> 
> Thanks again for bringing this up with us - we appreciate your time!

I am not found 8274

**Comment by oddcelot** [comment]
I also could not find the ticket anywhere.
@L1yp thank you for the patch 😻 

if someone else stumbles upon this issue in the meantime: 
here's a the working thing with the pnpm patch file

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/~/github.com/oddcelot/vue---ag-grid)
