### ISSUE TITLE
CSV changes to wrong dates upon save. for ex : when I enter 12-Oct-1945 , saving in 12-oct-45 format. when I tried to read that cell value it is showing as 12-oct-2045

### ISSUE THREAD

**Issue by neha1247** [ag-grid/ag-grid#6553]
[basicDetails.csv](https://github.com/ag-grid/ag-grid/files/11389970/basicDetails.csv)

Used service from this url . I tried to modify date cell with various modification like using moment(cell).format(dd-MMM-yyyy') and also using date pipe. But not working.
https://codeburst.io/export-objects-array-as-csv-using-typescript-643bf4f794d9

**Comment by StephenCooper** [comment]
I don't see what this has to do with AG Grid, so am going to close this issue.
