### ISSUE TITLE
Multi selection not working for infinite scrolling after upgrading it to v29.3.0

### ISSUE THREAD

**Issue by patel22111** [ag-grid/ag-grid#6554]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
multi selection not working for infinite scrolling. after selecting a row using checkbox, already selected row getting deselected.

**Expected behavior**
multi selection should work for infinite scrolling.

**Please tell us about your environment:**
windows

* **AG Grid version:** X.X.X
29.3.0

* **Browser:**
chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Please provide a code reproduction of this issue that will help us investigate and then test a fix if this is a bug.

**Comment by patel22111** [comment]
here is code reproduction https://jsfiddle.net/27Ld3efu/

**Comment by StephenCooper** [comment]
Looks like you are just missing `suppressRowClickSelection: true` config. https://ag-grid.com/javascript-data-grid/row-selection/#example-displaying-disabled-checkboxes

I cannot see the error you describe after these changes.

https://jsfiddle.net/6o9ghrdL/2/
