### ISSUE TITLE
table data not update when edit/change after first time

### ISSUE THREAD

**Issue by GitHub-Ronald** [ag-grid/ag-grid#6556]
version: "ag-grid-community": "^29.3.3",
               "ag-grid-vue3": "^29.3.3",

`<ag-grid-vue
      class="ag-theme-alpine"
      style="height: 500px"
      :columnDefs="columnDefs.value"
      :rowData="columnDefs.data"
    >
    </ag-grid-vue>

const columnDefs = reactive({
  value: [
    { field: 'make' },
    { field: 'model' },
    { field: 'price' }
  ],
  data: [
    { make: '2020-12-20 20:09:09', model: '202074927641', price: '20.89' },
    { make: '2020-12-20 20:09:09', model: '202074927642', price: '20.89' },
    { make: '2020-12-20 20:09:09', model: '202074927643', price: '20.89' },
    { make: '2020-12-20 20:09:09', model: '202074927644', price: '20.89' },
    { make: '2020-12-20 20:09:09', model: '202074927645', price: '20.89' },
    { make: '2020-12-20 20:09:09', model: '202074927646', price: '20.89' }
  ]
})

const handleClick = (row) => {
  columnDefs.data.forEach((item, index) => {
    if (index === row) item.make = 'new value'
  })
}
`
when I call **handleClick** first time, the table view update, but after first time,  the view not update

**Comment by StephenCooper** [comment]
Could you please provide this in a code example?

Also you may find the following page helpful. https://ag-grid.com/vue-data-grid/view-refresh/

**Comment by GitHub-Ronald** [comment]
here is the example [https://stackblitz.com/edit/vue-9l4wwz?file=src/App.vue](url)

**Comment by GitHub-Ronald** [comment]
> Could you please provide this in a code example?
> 
> Also you may find the following page helpful. https://ag-grid.com/vue-data-grid/view-refresh/

here is the example [https://stackblitz.com/edit/vue-9l4wwz?file=src/App.vue](url)

**Comment by zoheil-ag** [comment]
Hi GitHub-Ronald,

Thank you for proving the example and reporting this.

We would advise to avoid direct manipulation of row data - either use the grid APIs or set new row data:

```
 
    handleBtnClick(row) {
      const newData = [...this.data];
      newData.forEach((item, index) => {
        if (row === index) item.make = `new value${index}`;
      });
      this.data = newData;
    },
  },
 
```
You can see it working here:
https://stackblitz.com/edit/vue-uswsas?file=src%2FApp.vue

Kind regards,
