### ISSUE TITLE
Is Svelte supported?

### ISSUE THREAD

**Issue by githorse** [ag-grid/ag-grid#6568]
**I'm submitting a ...**  (check one with "x")
```
[] bug report
[x] feature request
[] support request
```

The docs have examples in vanilla JS, React, Angular, Vue, and Solid, but the query "Svelte" gets no hits. Is Svelte support on the roadmap at all? If not, could there perhaps be a page with some brief suggestions on making it work or some links to external resources?

**Comment by StephenCooper** [comment]
Hi @githorse,

We do not officially support Svelte and it is not currently on our roadmap. I see that there is a community wrapper available at https://github.com/MichaelKim/ag-grid-svelte.

I think you have a valid point about having a doc page that contains at least a mention / links.
