### ISSUE TITLE
Trouble locating button element with Playwright testing / automation

### ISSUE THREAD

**Issue by gotnoshoeson** [ag-grid/ag-grid#6571]
Working with a web app, I'm unable to locate elements that are within the "ag-grid-angular" parent element. There are some methods within Playwright to work with iframes and redirects, etc but I'm first trying to understand what I'm working with. How should I think about working with content that is returned within the ag-grid element?

**Comment by zoheil-ag** [comment]
Hi @gotnoshoeson,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
