### ISSUE TITLE
Bulk Update Rows by updating the value of single row

### ISSUE THREAD

**Issue by noobyogi0010** [ag-grid/ag-grid#6575]
## Description

I have a react ag-grid that displays certain amount of data. For simplicity consider the headers of my data be `id`, `name`, `subject`, `topic`, and `marks`.

All of these columns are editable and the data is grouped by `subject`.

Now, I want a functionality where when I update the value of `marks` from the grouped row for a `subject` it should update the `marks` column for all the rows with this `subject`.

**Comment by StephenCooper** [comment]
We use Github for bug reports only. Please either use our Enterprise support or take advantage of the community on StackOverflow.
