### ISSUE TITLE
[Chart] warning in console if using calloutLabel.formatter

### ISSUE THREAD

**Issue by YuerLee** [ag-grid/ag-grid#6580]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'
```

**Current behavior**
After ag-charts-community v6.2.1, if using `calloutLabel.formatter` like:

```js
calloutLabel: {
 formatter: ({ datum, calloutLabelKey, angleKey }) => {
   return `${datum[calloutLabelKey]}: ${datum[angleKey]}`;
  },
}
```

A warning would show on the console:

```
AG Charts - the use of { value } in the pie chart label formatter function is deprecated. Please use { datum, labelKey, ... } instead.
```

[Reproduced in stackblitz](
https://stackblitz.com/edit/web-platform-ayjmbm?devToolsHeight=33&file=main.js)

**Expected behavior**

Accroding to docs in https://www.ag-grid.com/javascript-charts/pie-series/#example-pie-labels , the usage should be okay.
![image](https://github.com/ag-grid/ag-grid/assets/2075566/b1c3c3b5-81a2-400b-bae4-da04574f3cf5)

**Please tell us about your environment:**

* **AG Charts version:** 6.2.1~7.30

* **Language:** ES6/7

**Comment by alantreadway** [comment]
@YuerLee thanks for reporting this.

We're busy working towards our next major release, and as part of that effort we have already removed this particular deprecation warning (and backwards compatibility for `value`), so we are considering the issue resolved. We're anticipating the next major release will be in the new few weeks.

Thanks,
Alan
