### ISSUE TITLE
When we enter valid/invalid string in 'Movie' edit field, Screen readers are not announcing displayed search results information.

### ISSUE THREAD

**Issue by msftedad** [ag-grid/ag-grid#6592]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1.Open URL: [gracious-jones-1gb0rh - CodeSandbox](https://codesandbox.io/s/1gb0rh?file=/demo.js)
2. Turn on screen reader (NVDA/Narrator/JAWS)
3.Focus lands on the code editor (demo.js) as soon as page gets opened
4. Press ESC key from keyboard then press shortcut key B to reach out to combo box control.i.e. 'Movie' edit field.
5.Invoke the combo box control by pressing ENTER, enter some valid / invalid data in edit field and capture the screen reader narration.
6.Verify whether screen reader is announcing displayed search results information or not.

**Current behavior**
When we enter valid/invalid string in edit field, Screen reader is not announcing displayed search results information.

**Expected behavior**
When we enter valid/invalid string in 'Movie' edit field, Screen readers should narrate displayed search results information.

Ex: 1.When we enter Valid search string, JAWS/NVDA/Narrator should narrate as example:
'2 results are returned' and if we press down arrow to navigate the search results, then NVDA/JAWS focus should move to first result, and it should narrate the name along with position of the list item.

2.When we enter invalid(@@), JAWS/NVDA/Narrator should narrate as 'No options are displayed'.

**Please tell us about your environment:**

Windows OS version 22H2 (OS build 22621.1702)
JAWS version 2023.2212.23 ILM
NVDA version 2023.1
Narrator

* **AG Grid version:** 25.1.0

* **Browser:**
Chrome browser Version 113.0.5672.93 (Official Build) (64-bit)

* **Language:** ES6

![Issue202165](https://github.com/ag-grid/ag-grid/assets/93735775/383186da-b602-48f6-8688-54340dd05e73)

https://github.com/ag-grid/ag-grid/assets/93735775/2677b291-9cd6-41c7-aee8-4c334da3a8e7

**Comment by StephenCooper** [comment]
We believe that this is an issue for MUI as it looks related to their component and not for AG Grid
