### ISSUE TITLE
Can I pass in pre-aggregated data?

### ISSUE THREAD

**Issue by githorse** [ag-grid/ag-grid#6601]
**I'm submitting a ...**  (check one with "x")
```
[] bug report
[] feature request
[x] support request
```

I can do [server-side row grouping](https://www.ag-grid.com/react-data-grid/server-side-model-grouping/#server-side-row-grouping). But can I do server-side *aggregation* and then pass the pre-aggregated data into the grid?

Why would I want to do this? I've done an informal [aggregation performance benchmark](https://codesandbox.io/p/sandbox/8t1722) across several grids. AG Grid is pretty fast -- but my simple custom group-and-aggregate code is still 10x faster. (Try the demo above at 100k+ records.) So in certain scenarios I would pay the price to do my own calculations (and maybe give up some of the dynamic grouping/pivoting options) in order to optimize performance.

**Comment by AndrewGlazier** [comment]
Hi,

When using the SSRM the grid does support server-side aggregations, (In SSRM it _only_ supports server-side aggregations).

Most of our SSRM grouping examples demonstrate server-side aggregations, however this pivoting example should hopefully provide a reasonably extensive demonstration:
https://www.ag-grid.com/react-data-grid/server-side-model-pivoting/#example-slice-and-dice
