### ISSUE TITLE
Looking for AG-Charts release information

### ISSUE THREAD

**Issue by grunci** [ag-grid/ag-grid#6605]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

Hi,
Where can I find the commit hashes/releases of ag-charts-community?
According to npmjs, I should find these in this repo, but I was unable to locate them.
Could you please help me out?

Regards,
Grunci

**Comment by seanlandsman** [comment]
If you navigate to "releases" on the right hand side you can then either download the entire release or navigate to the commit for that release.

Either way you can then navigate to `charts-community-modules/ag-charts-community/dist` for the published code for that given release

**Comment by grunci** [comment]
Hi @seanlandsman,
Thanks.
But how do I know which commit (release) is the ag-charts-community 6.2.1?
Is it documented somehow, or I have to check each and every ag-grid release whether the ag-charts-community is 6.2.1?

Regards,
Grunci

**Comment by seanlandsman** [comment]
That's a fair question - the minor releases of the grid and charts will always match.

grid 29.3.x has has charts  7.3.x, grid 29.2.x has has charts  7.2.x  and so on.
