### ISSUE TITLE
Browser tab freezes after calling gridApi.getColumnDefs

### ISSUE THREAD

**Issue by FSPinho** [ag-grid/ag-grid#6616]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The issue I'm reporting shouldn't happen normally, since you are very clear when saying the APIs shouldn't be called after the grid is destroyed. I'm reporting it anyways just in case you get more open issues related.

The problem happens when calling `gridApi.getColumnDefs()` right after the grid is unmounted. For instance:
```TSX
const unmountGrid = useCallback(() => {
    setRenderGrid(false);
    setTimeout(() => {
        gridApi?.getColumnDefs();
    });
}, [gridApi]);
``` 

In my case, I'm using React, and the issue only happens when using column definitions containing header groups. Right after calling `gridApi?.getColumnDefs()`, the grid seems to fall in a loop in the method `ColumnDefFactory.buildColumnDefs` under `grid-community-modules/core/src/ts/columns/columnDefFactory.ts`. After that, the browser tab freezes completely.

I hope it helps, thanks for your amazing work!

* **AG Grid version:** 29.3.5

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

* **Language:** TypeScript

**Comment by StephenCooper** [comment]
Thanks for reporting as this is another useful test case for me as I review the behaviour of destroyed grids.

**Comment by StephenCooper** [comment]
I have found the issue and this will be resolved as part of v30. 

It has also enabled us to think about how we can help users avoid calling into gridApi methods against a destroyed grid which could lead to other unexpected behaviours.

Thanks again for reporting!
