### ISSUE TITLE
In an ag-charts stacked column chart, label colors cannot be set for each series individually

### ISSUE THREAD

**Issue by cado1982** [ag-grid/ag-grid#6617]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In an ag-charts stacked column chart, label color cannot be individually set on a series level. Only the label color from the last series in the array is used.

https://plnkr.co/edit/fIvWcduL8K1k5ZCF?open=main.js&preview

Note that the label colors for each series are set but all the label colors are purple in the preview. Change the last series (Services) label color to another color for example 'white' and note that all label colors then change to white in the preview.

**Expected behavior**
It should be possible to choose a label color for each series to match the fill color for that series

**AG Grid version:** 
7.3.0

**Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'

**Language:** 
all

**Comment by alantreadway** [comment]
Thanks for reporting this, we are already tracking this internally with the following reference and description:
AG-7933 - [Charts] Cannot specify per-series options for multiple bar/column/area series

This is a longer-standing issue, which requires some non-trivial changes to the way we handle stackable series types, so we can't give a firm estimate on when we will be able to fix this. Theme-based configuration is the best workaround for managing the palette used by series.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Regards,
Alan

**Comment by cado1982** [comment]
Thanks @alantreadway for the confirmation.

Can you let me know please if it's possible using themes to choose an item from the palette for each series ahead of time? I think it's not from looking at the docs but I'm not 100% sure. It's important for my client to be able to set the background of each series to a specific color to correspond with their business rules. For example, in the plunker I linked, I'd always want the iPad series to be green.

If that's not possible we'll have to explore some other options.

Thanks again,
Chris.

**Comment by alantreadway** [comment]
Hi @cado1982 - perhaps take a look at a [Series Formatter](https://ag-grid.com/javascript-charts/formatters/#series-item-formatter) for fine-grained control in that scenario, whilst AG-7933 is outstanding?
