### ISSUE TITLE
Shift key combination does not work properly for deselecting multiple rows in AG Grid table

### ISSUE THREAD

**Issue by alpercun** [ag-grid/ag-grid#6619]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Selecting multiple rows in a table using `shift key` works properly. But the same operation does not work for deselecting multiple rows. For example, imagine a table with rows with multiple selections, I deselect the checkbox on any row from the top, then I want to deselect a selected checkbox 3-5 rows below using the `shift + mouse left` combination, including the selected checkboxes in between, but it does not work as desired.

https://github.com/ag-grid/ag-grid/assets/32914083/4897c68c-79d5-449a-bfd8-415ca0a89246

**Expected behavior**
After selecting more than one line with shift, I should be able to deselect the lines I want correctly by using shift again.

* **AG Grid version:** X.X.X
29.2.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by kiril-matev** [comment]
Hi @alpercun,

Thanks for reaching out.

I'd like to confirm the exact selection scenario you're referring to.

Please see the example below and let me know if it captures the use case you're referring to.

Steps to illustrate:
1. Open
https://plnkr.co/edit/fuaPpHzZJnPtr2XU
2. Click the header selection checkbox
3. Deselect record #1 (Michael Phelps, 23, ...)
4. Hold down SHIFT and deselect record #5 (Aleksey Nemov, 24...)

Actual: Records 1,5 are deselected but records #2, #3, #4 remain selected. 
Desired: All records 1-5 deselected.

Is this the selection you're looking for? Please send a list of steps using the sample above describing the actual and desired behavior.

Looking forward to your response.

**Comment by alpercun** [comment]
Hi @kiril-matev,
The steps are the same but we expect all the records 1-5 to be deselected.

**Comment by alpercun** [comment]
Thanks for your feedback. I will be looking forward to this feature. @kiril-matev
