### ISSUE TITLE
row spanning bug

### ISSUE THREAD

**Issue by maltsugar** [ag-grid/ag-grid#6626]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When the cross row exceeds 15 rows, an exception is displayed.
![](https://gitee.com/maltsugar/repo_imgs/raw/master/aggrid.gif)
gifurl
gitee.com/maltsugar/repo_imgs/raw/master/aggrid.gif

**Expected behavior**
Correct row merging

**Please tell us about your environment:**
macOS 13.3.1
node v19.8.1
"vue": "^2.6.14"

* **AG Grid version:** 
"ag-grid-community": "^29.3.5",
"ag-grid-vue": "^29.3.5",

* **Browser:**
Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 Edg/113.0.0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
es6

**Comment by StephenCooper** [comment]
Please could you provided a code reproduction that shows the exception for us to use as a test case?

**Comment by maltsugar** [comment]
for "vue": "^2.6.14"

<template>
  <div>
    <ag-grid-vue
      style="height: 500px"
      class="ag-theme-alpine"
      :suppressMovableColumns="true"
      :columnDefs="columnDefs"
      :rowData="rowData"
      :suppressRowTransform="true"
      :suppressRowHoverHighlight="true"
      :suppressCellFocus="true"
      :rowStyle="{
        background: '#fff',
      }"
    >
    </ag-grid-vue>
  </div>
</template>

<script>
import { AgGridVue } from "ag-grid-vue";
export default {
  name: "AGTablePage",
  data() {
    return {
      columnDefs: null,
      rowData: null,
    };
  },
  components: {
    AgGridVue,
  },
  beforeMount() {
    let idx = 0;
    const getProp = () => {
      return "" + idx++;
    };

    let tmp = [];
    for (let i = 0; i < 255; i++) {
      let col = {};
      if (i < 3) {
        col = {
          headerName: `f_${i}`,
          pinned: true,
          field: `name${i}`,
          width: 50,
          spanHeaderHeight: true,
        };

        if (i == 1) {
          col.rowSpan = this.rowSpan;
          col.cellClassRules = {
            "cell-span": (params) =>
              params.value?.slice(params.value?.length - 2) == "_0",
          };
        }
      } else {
        col = {
          headerName: `t1_${i}`,
          children: [
            {
              headerName: `t2_${i}`,
              children: [
                { field: getProp(), width: 50 },
                { field: getProp(), width: 50 },
              ],
            },
            {
              headerName: `t21_${i}`,
              columnGroupShow: "open",
              children: [
                { field: getProp(), width: 50 },
                { field: getProp(), width: 50 },
              ],
            },
          ],
        };
      }
      tmp.push(col);
    }
    this.columnDefs = tmp;

    let rowTmp = [];
    const sec = [15, 5, 2, 6, 4, 2, 6];
    for (const s of sec) {
      for (let i = 0; i < s; i++) {
        const row = {
          name0: `0.${s}_${i}`,
          name1: `1.${s}_${i}`,
          name2: `2.${s}_${i}`,
        };
        if (i == 0) {
          row.span = s;
        }

        rowTmp.push(row);
      }
    }
    this.rowData = rowTmp;
    console.log('rowTmp',rowTmp)
  },

  methods: {
    rowSpan(params) {
      // console.log("params.data.span", params.data.span);
      if (params.data.span) {
        return params.data.span;
      }
      return 1;
    },
  },
};
</script>

<style lang="scss" scoped>
@import "~ag-grid-community/styles/ag-grid.css";
@import "~ag-grid-community/styles/ag-theme-alpine.css";
::v-deep {
  .ag-cell-value,
  .ag-header-cell {
    padding: unset;
  }

  .ag-header-group-text,
  .ag-header-cell-text {
    font-size: 11px;
    font-weight: 400;
  }

  .ag-header-group-cell-label,
  .ag-header-cell-label {
    justify-content: center;
  }

  .cell-span {
    background: #f00;
    border-bottom: 1px solid #dde2eb;
    border-left: 1px solid #dde2eb;
    border-right: 1px solid #dde2eb;
    display: flex;
    align-items: center;
  }
  .ag-header-group-cell,
  .ag-center-cols-viewport .ag-cell-value,
  .ag-cell-label-container {
    border-right: 1px solid #dde2eb;
  }
}
</style>

**Comment by maltsugar** [comment]
This bug code is very simple, it is simply using the API provided by SDK, it is easy to reproduce

**Comment by kiril-matev** [comment]
Hi @maltsugar,

See below our documentation example for row spanning modified to span 20 rows:
https://plnkr.co/edit/dTszlsWNkflorrbA?open=main.js

As you can see scrolling down doesn't produce an exception.

Please provide a live reproduction example to allow us to look into this.

**Comment by maltsugar** [comment]
> 

Hello, the demo you provided has reproduced this bug when scroll down
[](https://gitee.com/maltsugar/repo_imgs/raw/master/Untitled1.gif)

**Comment by maltsugar** [comment]
> 

Hello, the demo you provided has reproduced this bug when scroll down
[gif](https://gitee.com/maltsugar/repo_imgs/raw/master/Untitled1.gif)

**Comment by maltsugar** [comment]
> Hi @maltsugar,
> 
> See below our documentation example for row spanning modified to span 20 rows: https://plnkr.co/edit/dTszlsWNkflorrbA?open=main.js
> 
> As you can see scrolling down doesn't produce an exception.
> 
> Please provide a live reproduction example to allow us to look into this.

Hello, the demo you provided has reproduced this bug when scroll down.
![demo](https://gitee.com/maltsugar/repo_imgs/raw/master/Untitled1.gif)

**Comment by maltsugar** [comment]
> > Hi @maltsugar,
> > See below our documentation example for row spanning modified to span 20 rows: https://plnkr.co/edit/dTszlsWNkflorrbA?open=main.js
> > As you can see scrolling down doesn't produce an exception.
> > Please provide a live reproduction example to allow us to look into this.
> 
> Hello, the demo you provided has reproduced this bug when scroll down. ![demo](https://camo.githubusercontent.com/3ee100de6f1ee4306d7132a1752cc243864df6e49bd9dd22b281760088fd0112/68747470733a2f2f67697465652e636f6d2f6d616c7473756761722f7265706f5f696d67732f7261772f6d61737465722f556e7469746c6564312e676966) [ ![demo](https://camo.githubusercontent.com/3ee100de6f1ee4306d7132a1752cc243864df6e49bd9dd22b281760088fd0112/68747470733a2f2f67697465652e636f6d2f6d616c7473756761722f7265706f5f696d67732f7261772f6d61737465722f556e7469746c6564312e676966) ](https://camo.githubusercontent.com/3ee100de6f1ee4306d7132a1752cc243864df6e49bd9dd22b281760088fd0112/68747470733a2f2f67697465652e636f6d2f6d616c7473756761722f7265706f5f696d67732f7261772f6d61737465722f556e7469746c6564312e676966) [ ](https://camo.githubusercontent.com/3ee100de6f1ee4306d7132a1752cc243864df6e49bd9dd22b281760088fd0112/68747470733a2f2f67697465652e636f6d2f6d616c7473756761722f7265706f5f696d67732f7261772f6d61737465722f556e7469746c6564312e676966)

gif url：  https://gitee.com/maltsugar/repo_imgs/raw/master/Untitled1.gif

**Comment by maltsugar** [comment]
> Hi @maltsugar,
> 
> See below our documentation example for row spanning modified to span 20 rows: https://plnkr.co/edit/dTszlsWNkflorrbA?open=main.js
> 
> As you can see scrolling down doesn't produce an exception.
> 
> Please provide a live reproduction example to allow us to look into this.

Hello, the demo you provided has reproduced this bug when scroll down.
![demo](https://raw.githubusercontent.com/maltsugar/repo_demoImgs/main/aggrid.gif)

**Comment by kiril-matev** [comment]
Hi @maltsugar,

Are you referring to the row span blue region **disappearing** when you scroll down? Is this the bug you're reporting?

In your original description you said there was an exception when the grid is scrolled. As you can see in the console, there's no exception in this example. This is what I meant when I said that the behavior you reported cannot be reproduced. Do you have an exception in your sample when you scroll the grid?

**Comment by maltsugar** [comment]
> Hi @maltsugar,
> 
> Are you referring to the row span blue region **disappearing** when you scroll down? Is this the bug you're reporting?
> 
> In your original description you said there was an exception when the grid is scrolled. As you can see in the console, there's no exception in this example. This is what I meant when I said that the behavior you reported cannot be reproduced. Do you have an exception in your sample when you scroll the grid?

Yes, I mean the merged cells disappear when scrolling, that is the blue merged regin above disappears. I am sorry that the previous description may have been ambiguous

**Comment by kiril-matev** [comment]
Hi @maltsugar,

Thank you for this.

We're tracking this with AG-2323. However, until this is reimplemented, please use the approach below to resolve this.

You can workaround this issue by setting the gridOptions **rowBuffer** property to a larger value to pre-render more rows to allow the row span to render correctly. The **rowBuffer** property is documented here:
https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-miscellaneous-rowBuffer

By default rowBuffer is 20, so if you have row spans with more than 20 rows, that will cause the issue. 

You can fix this by setting the rowBuffer property to a value equal or bigger than the number of rows in the largest row span you have. For example, so if your biggest row span is 100 rows, set rowBuffer to 100 to resolve this as shown here:
https://plnkr.co/edit/syUbfeLUnYFEXhxJ

Note that in this example the row span is correctly shown as you scroll down.

Please keep in mind that using a larger value for rowBuffer will increase the memory footprint, as it pre-renders a larger number of rows before they're scrolled into view.

**Comment by maltsugar** [comment]
ok, thanks for the reply
