### ISSUE TITLE
Ag grid react - columns auto size overwritten by default and causes blinking repeat renders

### ISSUE THREAD

**Issue by LinnaViljami** [ag-grid/ag-grid#6630]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using AgGridReact component columns can be resized with columnApi.autoSizeAllColumns() when data is rendered.

The docs tells (https://www.ag-grid.com/javascript-data-grid/column-sizing/#resizing-columns-when-data-is-rendered) that this function may be called when firstDataRendered event is fired. As follows:
```
<AgGridReact
	ref={gridRef}
	onFirstDataRendered={(e) => {
		e.columnApi.autoSizeAllColumns(true)
	}
	...
/>
```
However, this is not working. The grid is not ready or maybe is resized afterwards by default, thus overwriting the desired behaviour.

Problem can be solved by setting a timeout:
```
 setTimeout(() => {
 	e.columnApi.autoSizeAllColumns(true)
 }, 100)
```
Now columns are resized but, every time row data is updated, the grid columns are resized back to the default width. Also on first render, the columns are first rendered to the default width and then rescaled when the autoSizeAllColumns() event is called. This causes a table "blinking" between the renders.

Docs are also missing the information how the columns resizing should be done if row data is updated, or row data is refreshed (row data changed). Logical way to implement could be during the onRowDataUpdated event but this is not working. We face the similar problems as described previously. (resizing is overwrite by ag grid default behaviour, unless timeout function used. Timeout is hacky and causes table blinking between renders)

**Expected behavior**
- Columns auto size should not be overwritten by ag grid default behaviour, or ag grid default column sizing should be able to being modified.
- Column auto-sizing documentation should be updated and tested, so that it really describes a working solution
- Column auto-sizing documentation should cover the way to auto-resize columns on row data updated or reset.

**Please tell us about your environment:**
Ubuntu 18.03, React 18.0.27, typescript 5.0.4, ag-grid-community 29.2.0, ag-grid-react 29.2.0

* **AG Grid version:** 29.2.0

* **Browser:**
My current browser: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'
Same behaviour on Chrome, Firefox etc.

* **Language:** Typescript 5.0.4

**Comment by StephenCooper** [comment]
Hi @LinnaViljami,

I have come back to this ticket but I could really do with a reproduction that shows the flickering so I can fully understand what you are running into. 

Also can you please confirm if this is still happening in v30.

**Comment by Xavier59** [comment]
We have upgraded from `28.2.1` to `30.2.0` and are now facing a similar issue.

**Comment by AG-Zoheil** [comment]
Hi @Xavier59,

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is a closed issue that didn't have a replication of the reported problem.

If you are still having problems in newer versions, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
