### ISSUE TITLE
Using fill handle does not rerender cell

### ISSUE THREAD

**Issue by trin94** [ag-grid/ag-grid#6631]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
* Open https://www.ag-grid.com/example/?theme=ag-theme-material (theme doesn't matter)
* Use the fill handle on one of the cells in the "Bought" column and drag it downwards (see attached video)

https://github.com/ag-grid/ag-grid/assets/12988790/da7ae810-81b8-4279-911c-8065e502aaac

**Current behavior**
The value gets updated but it renders the old/wrong icon.

**Expected behavior**
The value gets updated and it renders the new/correct icon.

**Please tell us about your environment:**
Windows 10

* **AG Grid version:**
Tested on 19th of May 2023 - It's not my code so I don't know

* **Browser:**
* Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - the example has been fixed and the fix will be reflected on ag-grid.com when we do our next release, currently schedule for next week.

thanks,
Sean
