### ISSUE TITLE
Vue3 - Add new line to the grid only works once

### ISSUE THREAD

**Issue by lecaillon** [ag-grid/ag-grid#6636]
```
[x] bug report
```
### Steps to reproduce
Add a reactive array to the grid property `rowData`. It correctly displays the content.
Then push a new item to the array. The change is detected by the grid and it adds 1 line.
Finally push again a new item. No change is detected. No line is added.

If you want to test it, use the reproduction link below and click multiple times on the button

### Reproduction Link
https://stackblitz.com/edit/vue-wm4syf?file=src%2FApp.vue

### Expected Behavior
Each time I push an element to a reactive array binded to the `rowData` property, a new line should be added in the grid.

### Actual Behavior
A line is correctly added the first time. Never ever again after.

### Environment
**AG Grid version:** 29.3.5
**Vue Version:** 3.3.4
**Browsers:** Firefox 113.0
**OS:** Windows 10

**Comment by zoheil-ag** [comment]
Hi lecaillon,

Thank you for reporting this.

Direct manipulation of row data isn't advisable - you should use grid APIs or in this case set a new array:
 
```
    addRow() {
      this.data = [...this.data, {
        make: 'Porche',
        model: 'Carrera',
        price: '20.89',
      }];
    },
```

You can see it working here:
https://stackblitz.com/edit/vue-ebq78v?file=src%2FApp.vue,package.json

Kind regards,
