### ISSUE TITLE
[component] allow plugging in custom checkbox component

### ISSUE THREAD

**Issue by gabrielenosso** [ag-grid/ag-grid#664]
It would be great to have a way to customize the checkboxes (like a method that takes a boolean parameter and returns the checkbox based on it).

``` js
checkboxRenderer = (flag) => {
  if (flag) return 'X';
  return 'O';
}
```

**Comment by ceolter** [comment]
agreed.

in the mean time, you can implement your own cellRenderer for selection and use the selection api

**Comment by gabrielenosso** [comment]
Is there also a way to change the checkboxes for row groups then?

**Comment by ceolter** [comment]
no, just what is there now. to change that, you would need to create your own cellRenderer from scratch.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-101

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
