### ISSUE TITLE
Grouping Sorting and Filter Changes Into one Object  - Requesting Community Support

### ISSUE THREAD

**Issue by AhmedAbdelfaheem** [ag-grid/ag-grid#6641]
### Question 

I'm attempting to store the sorting and filtering data from the sortModel and filterModel in a useState object. Later, I plan to send this object to the backend when a button is clicked. I've explored different approaches, including using a custom header component, but I want to leverage the default features like column pinning, visibility, and filters.

The issue I'm facing is that the loading indicator is being triggered multiple times whenever there is a change in sorting or filtering, and it is displayed on all columns. My goal is to prevent this behavior and control the loading indicator using a button.

**Comment by zoheil-ag** [comment]
Hi @AhmedAbdelfaheem,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
