### ISSUE TITLE
After updating from 29.0.0 to 29.1.0, the icon is displayed differently.

### ISSUE THREAD

**Issue by yim-jj** [ag-grid/ag-grid#6645]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
After updating from 29.0.0 to 29.1.0, the icon is displayed differently.
As shown in the attached screenshot below, the menu and sorting icons are displayed differently.
![스크린샷 2023-05-23 오후 2 11 58](https://github.com/ag-grid/ag-grid/assets/76460116/6924a5a8-e7fe-4bc3-82aa-3db058c651e0)
![스크린샷 2023-05-23 오후 2 12 24](https://github.com/ag-grid/ag-grid/assets/76460116/1a2ad00e-dff6-42ec-ade3-b6222094c551)
![스크린샷 2023-05-23 오후 2 13 14](https://github.com/ag-grid/ag-grid/assets/76460116/66a0b23d-8e76-4162-81a7-5b3b206e4653)
After looking at the code, it seems that the cause is that ag-icon-font-code-*** has been changed.

https://github.com/ag-grid/ag-grid/commits/latest/grid-community-modules/styles/_icon-font-codes.scss

For example, the menu code was changed from f11d to f11e, and the desc code was changed from f10f to f110.

**Expected behavior**
You should see the same icon as the 29.0.0 version.

**Please tell us about your environment:**
macOS Ventura 13.3.1(a), NPM

* **AG Grid version:** X.X.X
29.0.0: No issues
From 29.1.0 to latest version: There is an issue

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by kiril-matev** [comment]
Hi @yim-jj,

See the sample below:
v29.0 https://plnkr.co/edit/XoOSH6h8il6iYrmt?open=main.js

Please point out where these icons appear - the sort icon and the menu icon. Please modify the plunker example if needed to illustrate this in action.

Looking forward to your response.

**Comment by yim-jj** [comment]
It's already been mentioned above, but if you look at git history, you can see what codes have been changed enough.

https://github.com/ag-grid/ag-grid/commits/latest/grid-community-modules/styles/_icon-font-codes.scss

To check out the changes, please refer to the screenshot below.
Left side is in 29.0.0 state, right side is _icon-font-codes.scss in 29.1.0 state.

![스크린샷 2023-06-23 오전 9 31 08](https://github.com/ag-grid/ag-grid/assets/76460116/dcbbf35a-8682-4934-bbd8-fe666eefad28)

**Comment by kiril-matev** [comment]
Hi @yim-jj,

The actual icons shown in the grid have not changed since we see the same icons for menus across all versions. 

However, the code for icons changed on v29.1.0 because we added new icons (see: AG-7915). This is expected.

Are you loading icons manually? Please let us know how you're loading icons.
