### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Miri121** [ag-grid/ag-grid#6649]
I use with examples:
https://www.ag-grid.com/react-data-grid/server-side-model-tree-data/
In part  "Selection with tree data".

I want that when I click the update button (which I created) all the cells that allow editing in the table will go into editing mode and I will be able to edit them... How I did it? please!.

**Comment by StephenCooper** [comment]
Closing as we use Github for bugs only. If you are an Enterprise user please contact us through ZenDesk.
