### ISSUE TITLE
Update localisation and documentation.

### ISSUE THREAD

**Issue by Paveltrof86** [ag-grid/ag-grid#6650]
Hello!

I`ve noticed that provided localisation and default have difference in:
https://www.ag-grid.com/examples/localisation/localisation/locale.en.js
 // Menu
....
collapseAll: 'Close All',
......

![2023-05-23_18h33_12](https://github.com/ag-grid/ag-grid/assets/19744837/e8f7a2ec-dd3f-4480-a20e-c02c55786bfb)
_________________

And with pinned row

![2023-05-23_18h35_19](https://github.com/ag-grid/ag-grid/assets/19744837/2401376e-e779-4c32-8624-4b1c6ee50672)

**Comment by StephenCooper** [comment]
Thanks, I have updated the pinned doc. The values for both Expand All and Collapse all are changing to Expand All Row Groups and Close All Row Groups in the next release.

**Comment by Paveltrof86** [comment]
> for both Expand All and **Collapse all** are changing to Expand All Row Groups and **Close All** Row Groups in the next release.

Hm....And we just thought it was inappropriate to change Collapse to Close.
Collapse All Row Groups is more suitable option.

Thanks!
