### ISSUE TITLE
addChildRow

### ISSUE THREAD

**Issue by Miri121** [ag-grid/ag-grid#6652]
I use with:
addChildRow: (route: string[], newRow: any) => {
const target = getDataAtRoute(route);
if (!target.children || target.children.length === 0) {
target.children = [newRow];
// update the parent row via transaction
gridApi.applyServerSideTransaction({
route: route.slice(0, route.length - 1),
update: [sanitizeRowForGrid(target)],
});
} else {
target.children.push(newRow);
// add the child row via transaction
gridApi.applyServerSideTransaction({
route,
add: [sanitizeRowForGrid(newRow)],
});
}

I want after the action of applyServerSideTransaction
Put the row added to the table into edit mode

I use with:

const rowNode = gridApi.api.getRowNode(1);
if (rowNode) {
const { rowIndex } = rowNode;
gridApi.api.startEditingCell({
rowIndex: rowIndex!,
colKey: 'goal',
});
}
But no working!

**Comment by StephenCooper** [comment]
We do not offer support via Github, we just accept bugs. As you are using an Enterprise feature I would encouraging you to use your Zendesk account if you need further help.
