### ISSUE TITLE
After hiding a column, the moveColumn api does not work as intended on the remaining visible columns

### ISSUE THREAD

**Issue by flex-bonggeun** [ag-grid/ag-grid#6672]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
There seems to be a bug when using the moveColumn(moveColumns) api in ag-grid.

After hiding certain columns, the remaining visible columns do not move to the intended index when I use the moveColumn api on them. It's as if the hidden columns are still affecting the visible columns. However, that column has already disappeared. 

I wonder if this is a bug you are aware of. Looking forward to a resolution.

**Expected behavior**
- After hiding a specific column, the moveColumn api still works as intended
  - Move to the intended `toIndex` when calling `moveColumn(columnKey, toIndex)`

**AG Grid version:** 29.3.4

**Comment by StephenCooper** [comment]
Can you please provide a reproduction showing your issue please. That will help us investigate.

**Comment by flex-bonggeun** [comment]
Let me show you some example code.

https://plnkr.co/edit/YnnXPtEG45kJeStt?open=index.tsx&preview

In the example, if you first press the "STEP1: Hide Age Column" button, and then press the "STEP2: Move Year Column To Index 4" button, the year column will move to index3 instead of index 4. This means that the hidden column (age column) still affects the second argument of the moveColumn api, toIndex. Normally, hidden columns are not taken into account when reordering columns, and this behavior makes it difficult to change the order of columns. First, I wonder if this is the intention. Even if it is the intention, it would be nice to have a proper way to do reordering with only visible columns.

Translated with www.DeepL.com/Translator (free version)

**Comment by kiril-matev** [comment]
Hello @flex-bonggeun,

The ordering of hidden columns is important - notably in the column menu and the sidebar. 

The moveColumn API therefore has to take these into account (they need to appear in the correct place if you then make them visible again). This is expected behaviour and not a bug.
 
Please use **columnApi.getAllGridColumns** and iterate through the columns to find the correct column index and provide it when calling the **columnApi.moveColumn** API method.

Thank you for your time!
