### ISSUE TITLE
`onColumnMoved` fires twice

### ISSUE THREAD

**Issue by githorse** [ag-grid/ag-grid#6673]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

When I click and hold a column to drag it into a different order, the `onColumnMoved` event fires each time the column jumps to a new positions (while I still have the mouse button held down), and then a second time when I release the mouse button. As far as I can tell the actual column state (i.e. what I get from `columnApi.getColumnState()`) is the same both times. 

Is this intentional? Why do I need the intermediate callbacks here -- don't I just want the final one, when the dragging is finalized? Is there a way to turn off the intermediate ones? If not, is there a way I can tell that this event is the intermediate one and I want to ignore it (and just pay attention to the final event when the state is settled)?

* **AG Grid version:** 29.3.5

* **Browser:**
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

* **Language:** TypeScript 4.6.4

**Comment by kiril-matev** [comment]
Hi @githorse,

The columnMoved is fired each time the dragged column is in a new position to allow you more flexibility in how you'd like to handle the column reorder.

You can easily ignore all the columnMoved events while dragging and only handle the last one when the column is dropped by checking the value of the **finished** property in the params object of the event:
https://www.ag-grid.com/javascript-data-grid/grid-events/#reference-columns-columnMoved

**Comment by githorse** [comment]
Thanks @kiril-matev -- that works. A related question -- what is the best way to get the new, updated list of columns (in the correct) order from the final finished event? I can probably figure it out from the `toIndex` but it would be handy just to get the new list of columns.

**Comment by kiril-matev** [comment]
Hi @githorse,

At any point you can get the updated list of columns using the columnApi.getColumnState() method:
1. Open
https://plnkr.co/edit/YgKUvFGXqCop4GJP?open=main.js
2. Open console
3. Drag ATHLETE column header to reorder it
4. See console
Actual & Expected: Console shows latest column order 

Please see the documentation and examples about column state here:
https://www.ag-grid.com/javascript-data-grid/column-state/#save-and-apply
