### ISSUE TITLE
suppressDragLeaveHidesColumns prop doesn't work

### ISSUE THREAD

**Issue by lesterfan** [ag-grid/ag-grid#6682]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/QFBoeAnVUNxsLyMi?open=index.jsx
Move the sport column up to the groupby; the column disappears but we expect it to remain since `suppressDragLeaveHidesColumns={true}`.

**Comment by kiril-matev** [comment]
Hello @lesterfan,

Thanks for this.

You're using the wrong property to implement this. Setting suppressDragLeaveHidesColumns=true keeps columns visible when they're dragged outside of the grid, not dragged inside the row group panel.

Please use instead **suppressRowGroupHidesColumns**:
https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-columnMoving-suppressRowGroupHidesColumns

As shown here:
https://plnkr.co/edit/VBLVcTYLsPKNDic8?open=index.jsx
