### ISSUE TITLE
DetailCellRenderer Component Not Keyboard Accessible from Master Detail

### ISSUE THREAD

**Issue by 91timo91** [ag-grid/ag-grid#6685]
**I'm submitting a** ...  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I will reference an example from your documentaion: [Example: Custom Detail Cell Renderer with Grid](https://www.ag-grid.com/javascript-data-grid/master-detail-custom-detail/#example-custom-detail-with-grid)

1. Focus on the header of the table.
2. Begin navigating down through the table using tab, or the directional arrows, to the first non-header row's first cell.
3. Press enter to expand the row.
4. Tab to the end of the row.
5. Tab again, which focuses the entire detail grid.
6. Tab once more.
7. Notice that you are focusing on the next top-level row, not the first row of the grid in the custom renderer.

**Expected behavior**
I will reference an example from your documentaion: [Example: Custom Detail Cell Renderer with Grid](https://www.ag-grid.com/javascript-data-grid/master-detail-custom-detail/#example-custom-detail-with-grid)

1. Focus on the header of the table.
2. Begin navigating down through the table using tab, or the directional arrows, to the first non-header row's first cell.
3. Press enter to expand the row.
4. Tab to the end of the row.
5. Tab again, which focuses the entire detail grid.
6. Tab once more.
7. Focus is now on the first row of the grid in the custom renderer.

**Please tell us about your environment:**
I tested in https://www.ag-grid.com/javascript-data-grid/master-detail-custom-detail/#example-custom-detail-with-grid
* **AG Grid version:** 27.3.0
* **Browser:** Chrome v113.0.5672.127
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Hint:**
A similar issue for the simple master detail without customn renderer component seems to be already fixed within AG-4223.
(https://github.com/ag-grid/ag-grid/issues/5040)
But the issue remains for the use-case with "DetailCellRenderer".

**Comment by StephenCooper** [comment]
I am not sure if there is an issue here apart from a misunderstanding about what different examples should be doing.

Keyboard navigation works for Detail Grids as in https://www.ag-grid.com/javascript-data-grid/master-detail-grids/#example-grid-options

It works for the custom detail example where we implement this: https://www.ag-grid.com/javascript-data-grid/master-detail-custom-detail/#keyboard-navigation

There is no expectation that it should work for custom details when this is not explicitly handled by the detail grid.

I am going to close as I do not think there is an underlying issue for us to fix in the grid.
