### ISSUE TITLE
(Angular): set rowHeight in setTimeout not working

### ISSUE THREAD

**Issue by GeorgeKnap** [ag-grid/ag-grid#6686]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[https://plnkr.co/edit/CIkE1Atn3FBMmMhF?open=app%2Fapp.component.ts](https://plnkr.co/edit/CIkE1Atn3FBMmMhF?open=app%2Fapp.component.ts)

**Current behavior**
in Agular Ag-Grid setting new rowHeight value in asynchronous way doesn't  do anything

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
29.3.5

* **Browser:**
chrome latest

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi,

The `rowHeight` property is not currently reactive. We do have an example of changing row heights which can show you how to do this.

https://ag-grid.com/angular-data-grid/row-height/#example-changing-row-height
