### ISSUE TITLE
How to Sign in to AG Grid Enterprise Support

### ISSUE THREAD

**Issue by hieudo** [ag-grid/ag-grid#6694]
I bought the license of AG Grid Enterprise but I don't know how to sign in to AG Grid Enterprise support. 
[https://ag-grid.zendesk.com/auth/v2/login/signin](url)
I cannot find the link to sign up for AG Grid Enterprise Support.

**Comment by hieudo** [comment]
[https://ag-grid.zendesk.com/auth/v2/login/signin](url)

**Comment by hieudo** [comment]
I bought the license of AG Grid Enterprise but I don't know how to sign in to AG Grid Enterprise support.
[https://ag-grid.zendesk.com/auth/v2/login/signin](url)
I cannot find the link to sign up for AG Grid Enterprise Support.

**Comment by StephenCooper** [comment]
If you get in touch with info@ag-grid.com they will be able to assist you.
