### ISSUE TITLE
Support async operations for `aggFunc`

### ISSUE THREAD

**Issue by kadiryazici** [ag-grid/ag-grid#6695]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

In our website we have big tables that contains thousands of rows and hunderds of columns. When it comes to aggregation, it starts to freeze our website because it keeps main thread busy for a long time. This causes browsers to not respond.

**Expected behavior**
We are thinking that if we pass our aggregation to a WebWorker we can keep the main thread available all the time and users can continue to use website like nothing happened.

We are thinking a scenario like the following:
```ts
const colDef = {
  async aggFunc(params) {
    return await ourWorkerBehindComlink.doAggregation(params);
  }
}
```

**Please tell us about your environment:**
   - Framework: Vue

* **AG Grid version:** X.X.X

    - 29.3.5

* **Browser:**

    - 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
   - all

**Comment by StephenCooper** [comment]
Is it possible to reproduce the slowness in a shareable code sample? Do you have custom aggregation logic?

We would suggest the use of Server side row model for very large data sets as that allows async aggregates. You may even be able to implement that in your webworker if holding all the data on the client side does not pose any other issues.

**Comment by kadiryazici** [comment]
In [Wope](https://github.com/wopehq/) we are fetching all the data from the server and then everything is up to frontend. We sometimes have 1 millions of lines of json and it equals to 100 thousands of rows for 100 columns.

The problem that causes this is our `aggFunc` functions. It tries to aggregate lots of data so keeps the main thread busy. We don't have a choice for server-side-row-model currently.
