### ISSUE TITLE
nest Master / Detail grids data jitter

### ISSUE THREAD

**Issue by LeoJiang1997** [ag-grid/ag-grid#6701]
When clicking on the embedded subtable, the page will have data jitter，and the jitter is very obvious
![issue](https://github.com/ag-grid/ag-grid/assets/54826369/a7870cd4-4f6e-4ec1-8a5b-0911f6f592eb)

**Comment by StephenCooper** [comment]
Please provide a reproduction that we can work with to investigate the underlying issue.

**Comment by LeoJiang1997** [comment]
The demo of the official website can be used to demonstrate. The specific link is as follows  [link](https://www.ag-grid.com/archive/26.0.0/angular-data-grid/master-detail-nesting/)

**Comment by LeoJiang1997** [comment]
When I click Expand, column B will flash to the right of column A

> Please provide a reproduction that we can work with to investigate the underlying issue.

**Comment by StephenCooper** [comment]
The link you provided is v26 are you also seeing the same behaviour in v30? I am not 100% sure what particular part of the rendering you are referring to as jittering.

**Comment by StephenCooper** [comment]
Closing as I cannot reproduce in v30 and we made fixes in relation to column flickering. 

https://ag-grid.com/angular-data-grid/master-detail-nesting/
