### ISSUE TITLE
Carriage return avoids fixed lines?

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#6705]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
`<ag-grid-angular
    [style.width]="'100%'"
    [style.height]="scrollY"
    [class]="agThemeClass"
    [rowData]="dataList"
    [columnDefs]="columnDefs"
    [defaultColDef]="defaultColDef"
    [localeText]="agGridLocaleText"
    [enterMovesDown]="true"
    [enterMovesDownAfterEdit]="true"
    (cellEditingStopped)="cellEditingStopped($event)"
    [pinnedBottomRowData]="rowDataBottom"
    [stopEditingWhenCellsLoseFocus]="true"
    (gridReady)="onGridReady($event)"
    [rowSelection]="'multiple'"
    [suppressRowClickSelection]="true"
    (selectionChanged)="onSelectionChanged($event)"
    (cellKeyPress)="onCellKeyPress($event)"
  >
  </ag-grid-angular>`

I used [enterMovesDown]="true" [enterMovesDownAfterEdit]="true" to reach the Enter newline, but will newline the last row of the table to a fixed row. How can I disable this?

* **AG Grid version:**   29.3.5

* **Browser: Google Chrome 113

**Comment by StephenCooper** [comment]
Please provide this code in a working reproduction so that we can try to reproduce your issue. It is not clear from your description exactly what the issue is.
