### ISSUE TITLE
is there any way to make the whole table uneditable, variable controlled?

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#6706]
https://www.ag-grid.com/angular-data-grid/value-setters/#read-only-edit 
I document Only found this link method "Read Only Edit", can give the user the impression that it is not editable. But the user can still type, enter, edit, etc., is there a variable control like IsEdit = false all edits are invalid and cannot be operated, isEdit = true can be operated

* **AG Grid version: 29.3.5

* **Browser: Google Chrome 113**

**Comment by StephenCooper** [comment]
Yes please control on the column level or via a defaultColDef using the editable flag.

https://build.ag-grid.com/vue-data-grid/column-properties/#reference-editing-editable

Readonly edit is for a different usecase where devs want to manage the edits outside of AG Grid and then pass the new data back to the grid.
