### ISSUE TITLE
Issue when trying to use setState in onSelectionChanged

### ISSUE THREAD

**Issue by kyrylolvov** [ag-grid/ag-grid#6708]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Description
I have declared a useState, which tracks selected rows in the table
```
const [selectedRows, setSelectedRows] = useState<any[]>([]);
```
From the documentation I found a function, which was used with onSelectionChanged in one of the examples and modified it
```
const handleUpdateSelectedRows = useCallback((event: SelectionChangedEvent) => {
    const selectedRows = event.api.getSelectedRows() ?? [];
    setSelectedRows(selectedRows);
}, []);
```
And then, pass it as props to the AgGridReact
```
onSelectionChanged={handleUpdateSelectedRows}
```

**Current behavior**
The checkboxes are "blinking", and the getSelectedRows returns only last selected object in array. However, if I remove the ```setSelectedRows(selectedRows);```, and put a ```console.log()```, the function start working as expected, not breaking the checkboxes and returning all selected rows in array.
https://github.com/ag-grid/ag-grid/assets/70720713/07da5688-5c17-4902-aaf7-5d78132b4a03

**Expected behavior**
Checkboxes don't "blink", ```setSelectedRows(selectedRows);``` returns an array of selected rows.

**Please tell us about your environment:**
MacOs Ventura 13.3.1

* **AG Grid version:** X.X.X
"ag-grid-community": "^29.3.5",
"ag-grid-react": "^29.3.5",

* **Browser:**
Google Chrome, Version 113.0.5672.126 (Official Build) (arm64)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript@5.0.2

**Comment by StephenCooper** [comment]
Can you provide a code reproduction as that will help me advise you. It sounds like you have state that is derived from the `selectedRows` that is causing the grid columns to be re-rendered.

**Comment by kyrylolvov** [comment]
> Can you provide a code reproduction as that will help me advise you. It sounds like you have state that is derived from the `selectedRows` that is causing the grid columns to be re-rendered.

Other than the code I provided, I pass the selectedRows to my custom ToolBar, but don't use it there at this point
```
<TableToolBar gridRef={gridRef} selectedRows={selectedRows} />
```
