### ISSUE TITLE
Total Footer not working for server side rendering

### ISSUE THREAD

**Issue by Chinmay-k96** [ag-grid/ag-grid#6711]
[https://github.com/ag-grid/ag-grid/issues/4009](url) - when will this issue get resolved, its' been three years since that issue was raised and still total footer doesn't work for server side rendering

**Comment by kiril-matev** [comment]
Hello!

AG Grid 30 adds support for group footer rows when using server-side row model as part of AG-687.
https://www.ag-grid.com/javascript-data-grid/server-side-model-grouping/#row-group-footers

Adding support for group total footer when using server-side row model is separated in a new requirement:
**AG-8439 [SSRM] Add support for group total footer when using server-side row model**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

There's an important question about this. When grouped footer rows are shown, they're showing the aggregated values on a per-group level which are provided by the server. The group footer row shows the same values that the group header row will show and these are returned by the server when returning the group row.

However, how will you be providing the data to show in the grand total footer row? Wouldn't this require scrolling to the last data row (to see the grand totals row), which means loading all the data for the entire grid from the server? Does your data source return the grand total row values as the first row in the response (as a top-level group)?

**Comment by zoheil-ag** [comment]
Hi @Chinmay-k96 ,

As there's been no interaction on this issue for a while, we'll be closing it. Do get back to us if you wish to provide any further information for AG-8439.

Thank you,
Zoheil

**Comment by morloy** [comment]
We looked into this as well and found [Row Pinning](https://www.ag-grid.com/react-data-grid/row-pinning/) a reasonable option. It requires to manually query the server and fetch the grand total aggregation. The result can be put into a pinned row and shown at the bottom of the grid.

**Comment by mingfang** [comment]
> Hi [@Chinmay-k96](https://github.com/Chinmay-k96) ,
> 
> As there's been no interaction on this issue for a while, we'll be closing it. Do get back to us if you wish to provide any further information for AG-8439.
> 
> Thank you, Zoheil
@AG-Zoheil 
How can I track the status of AG-8439?

**Comment by AG-Zoheil** [comment]
Hello 


You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Kind regards,
Zoheil
