### ISSUE TITLE
duplicate group keys for row data, keys should be unique

### ISSUE THREAD

**Issue by github15238484509** [ag-grid/ag-grid#6722]
当我使用 ：
> :treeData="true" ，

```javascript

let gridOptions = reactive({
    getDataPath: function (data) {
        return data.filePath
    },
    autoGroupColumnDef: {
        headerName: "name",
        field: 'name'
    }
})

let data = [{
    filePath: ["1"],
    name: "one",
}, {
    filePath: ["1,2"],
    name: "two",
}, {
    filePath: ["1,2"],
    name: "three",
}]
```
duplicate group keys for row data, keys should be unique, and only two pieces of data will be displayed, missing data

example:   [demo](https://plnkr.co/edit/XamNkiQiwq4nRoQ2?open=main.js&preview)

**Comment by StephenCooper** [comment]
The warning is accurate for your data. Tree data does not support having duplicated paths as it will not know which item to display.
