### ISSUE TITLE
Able to enter invalid date input in date floating filter

### ISSUE THREAD

**Issue by Berni3011** [ag-grid/ag-grid#6723]
I am using the vanilla ag-grid date floating filter.

When entering the date manually you can enter more than 4 numbers on the year. Might be a good idea to prevent users to enter more than 4 numbers.

![image](https://github.com/ag-grid/ag-grid/assets/132649531/2cb7c703-2657-4ef4-a09e-e1aa6b2cee19)

**Comment by kiril-matev** [comment]
Helllo @Berni3011,

Please set **filterParams.minValidYear** and **filterParams.maxValidYear** properties to limit the year values entered in the date filter.

See this shown in this example:
https://www.ag-grid.com/javascript-data-grid/filter-date/#example-date-filter
