### ISSUE TITLE
Documentation on tooltip components in react uses `useMemo` incorrectly

### ISSUE THREAD

**Issue by QuarkNerd** [ag-grid/ag-grid#6725]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
docs say `const data = useMemo(props.api.getDisplayedRowAtIndex(props.rowIndex).data, []);`

**Expected behavior**
docs say `const data = useMemo(() => props.api.getDisplayedRowAtIndex(props.rowIndex).data, []);`
or maybe `props` can be deconstructed to pass `api` to the dependency array to satisfy eslint (depending on if the api object changes)

https://www.ag-grid.com/react-data-grid/component-tooltip/

**Comment by StephenCooper** [comment]
Thanks for the correction of this doc snippet!
