### ISSUE TITLE
FilterModel not applied on ag-grid-enterprise but works with same code for ag-grid-community

### ISSUE THREAD

**Issue by imdavidmin** [ag-grid/ag-grid#6727]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Link to [Codepen](https://codepen.io/imdavidmin-the-flexboxer/pen/LYXYgyg?editors=1010)**

Current behaviour: Filter is not applied
Expected behaviour. Filter applied.

**Current behavior**
When using `gridOptions.api.setFilterModel()` for `ag-grid-enterprise` library, filter does not get applied, but does if using `ag-grid-community`

**Expected behavior**
Filter applied.

**Please tell us about your environment:**
Windows, 

* **AG Grid version:** X.X.X
29.2.0

* **Browser:**
Edge

* **Language:** 
JS

**Comment by max-justice** [comment]
had the same happen to us
@imdavidmin change the filter in your colDef.
ag-grid-enterprise has the setFilter as a default while ag-grid-community has textFilter

**Comment by imdavidmin** [comment]
> had the same happen to us @imdavidmin change the filter in your colDef. ag-grid-enterprise has the setFilter as a default while ag-grid-community has textFilter

Is this not already done in the code example? `filter: 'agTextFilter'` is already specified in colDef

**Comment by max-justice** [comment]
If I'm not mistaken it has to be `filter: 'agTextColumnFilter'` instead of `filter: 'agTextFilter'`
if I change your codepen it only shows one row :)
