### ISSUE TITLE
Status of AG-8305

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#6731]
I can't track the feature request with reference AG-8305 neither in pipeline nor in changelog.

https://github.com/ag-grid/ag-grid/issues/6354#issuecomment-1494183289

**Comment by kiril-matev** [comment]
Hello @melon2504,

Thanks for following up.

I've updated the tagging on AG-8305 and it will appear in the pipeline over the next 2 hours.
https://www.ag-grid.com/pipeline/

Thanks for bringing this up.
