### ISSUE TITLE
[Charts]  combined line with stacked bar changed from charts 7.2 to 7.3 - separate x -axis chart

### ISSUE THREAD

**Issue by kfaiczak** [ag-grid/ag-grid#6732]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Chrome 
Version 114.0.5735.106 (Official Build) (arm64)

when I updated to the latest ag-grid 29.3

├── ag-charts-community@7.3.0
├── ag-charts-react@7.3.0
├── ag-grid-community@29.3.5
├── ag-grid-react@29.3.5

<img width="989" alt="Screenshot 2023-06-08 at 12 23 47 AM" src="https://github.com/ag-grid/ag-grid/assets/63421082/4c46ef2f-19d7-4e12-bbcf-650ba6df33bf">

if I downgrade to (I get the original expected chart)
ag-charts-community@7.2.0
<img width="989" alt="Screenshot 2023-06-08 at 12 20 31 AM" src="https://github.com/ag-grid/ag-grid/assets/63421082/04bd8753-829f-4a42-a5a5-86947a51f613">

the data and code is the same in both cases (all I did was upgrade to 29.3 (not sure of previous version) then downgraded the charts to 7.2.0 which then fixes the issue ... so something different in 7.3.0 charts

Component props are pretty simple (functions here are just returning the data from the fetch/ react state variables)

<AgChartsReact
          options={{
            title: getTitle(),
            subtitle: getSubtitle(),
            series: getSeries(),
            data: getData(),
            height: expand ? winHeight - 35 * 4 : height,
            width: expand ? winWidth - 66 * 4 : width,
            legend: { position: "bottom" },
          }}
        />

 I don't see any reason why this change happened based on the release notes on 29.3 (29.2 or 29.1)
 ... the data seems reasonable and has worked in the 
past 9 months I've been working with ag-grid
only though AG-6926? (just since its related to joining multiple chart types together)

{
				"Title": {
					"text": "InvAssets \u0026 Value by Source"
				},
				"SubTitle": {
					"text": "Theodore"
				},
				"Series": [
					{
						"type": "line",
						"xKey": "age",
						"yKey": "InvAssets",
						"yName": "InvAssets##$",
						"title": "InvAssets"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "RRSP",
						"yName": "RRSP",
						"title": "RRSP"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Stock",
						"yName": "Stock",
						"title": "Stock"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Cash",
						"yName": "Cash",
						"title": "Cash"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "TFSA",
						"yName": "TFSA",
						"title": "TFSA"
					}
				],
				"Data": [
					{
						"Cash": 37500,
						"InvAssets": 330500,
						"RRSP": 13000,
						"Stock": 150000,
						"TFSA": 130000,
						"age": 40
					},
					{
						"Cash": 90053,
						"InvAssets": 403487,
						"RRSP": 18502,
						"Stock": 153403,
						"TFSA": 141529,
						"age": 41
					},
					{
						"Cash": 144836,
						"InvAssets": 479440,
						"RRSP": 24218,
						"Stock": 156883,
						"TFSA": 153503,
						"age": 42
					},
					{
						"Cash": 201916,
						"InvAssets": 558454,
						"RRSP": 30155,
						"Stock": 160442,
						"TFSA": 165941,
						"age": 43
					},
					{
						"Cash": 261262,
						"InvAssets": 640525,
						"RRSP": 36322,
						"Stock": 164082,
						"TFSA": 178859,
						"age": 44
					},
					{
						"Cash": 315251,
						"InvAssets": 726070,
						"RRSP": 43227,
						"Stock": 174815,
						"TFSA": 192777,
						"age": 45
					},
					{
						"Cash": 322818,
						"InvAssets": 815142,
						"RRSP": 50399,
						"Stock": 234692,
						"TFSA": 207233,
						"age": 46
					},
					{
						"Cash": 330565,
						"InvAssets": 908817,
						"RRSP": 57848,
						"Stock": 298156,
						"TFSA": 222248,
						"age": 47
					},
					{
						"Cash": 338499,
						"InvAssets": 1007507,
						"RRSP": 66086,
						"Stock": 364578,
						"TFSA": 238344,
						"age": 48
					},
					{
						"Cash": 346623,
						"InvAssets": 1111112,
						"RRSP": 74642,
						"Stock": 434785,
						"TFSA": 255062,
						"age": 49
					},
					{
						"Cash": 72211,
						"InvAssets": 873315,
						"RRSP": 83529,
						"Stock": 444648,
						"TFSA": 272927,
						"age": 50
					},
					{
						"Cash": 77884,
						"InvAssets": 981423,
						"RRSP": 92760,
						"Stock": 519296,
						"TFSA": 291483,
						"age": 51
					},
					{
						"Cash": 79753,
						"InvAssets": 1095268,
						"RRSP": 102847,
						"Stock": 601911,
						"TFSA": 310757,
						"age": 52
					},
					{
						"Cash": 81667,
						"InvAssets": 1214954,
						"RRSP": 113324,
						"Stock": 688687,
						"TFSA": 331276,
						"age": 53
					},
					{
						"Cash": 83627,
						"InvAssets": 1340633,
						"RRSP": 124207,
						"Stock": 780210,
						"TFSA": 352589,
						"age": 54
					},
					{
						"Cash": 85634,
						"InvAssets": 1472876,
						"RRSP": 136011,
						"Stock": 876004,
						"TFSA": 375227,
						"age": 55
					},
					{
						"Cash": 87690,
						"InvAssets": 1611744,
						"RRSP": 148272,
						"Stock": 977042,
						"TFSA": 398740,
						"age": 56
					},
					{
						"Cash": 89794,
						"InvAssets": 1757488,
						"RRSP": 161007,
						"Stock": 1083524,
						"TFSA": 423163,
						"age": 57
					},
					{
						"Cash": 91949,
						"InvAssets": 1910519,
						"RRSP": 174735,
						"Stock": 1194805,
						"TFSA": 449030,
						"age": 58
					},
					{
						"Cash": 94156,
						"InvAssets": 2071019,
						"RRSP": 188993,
						"Stock": 1311972,
						"TFSA": 475898,
						"age": 59
					},
					{
						"Cash": 96416,
						"InvAssets": 2191313,
						"RRSP": 204303,
						"Stock": 1386289,
						"TFSA": 504305,
						"age": 60
					},
					{
						"Cash": 98730,
						"InvAssets": 2255485,
						"RRSP": 211453,
						"Stock": 1418708,
						"TFSA": 526594,
						"age": 61
					},
					{
						"Cash": 98730,
						"InvAssets": 2317924,
						"RRSP": 207758,
						"Stock": 1450892,
						"TFSA": 560544,
						"age": 62
					},
					{
						"Cash": 98730,
						"InvAssets": 2383243,
						"RRSP": 205725,
						"Stock": 1483805,
						"TFSA": 594983,
						"age": 63
					},
					{
						"Cash": 98730,
						"InvAssets": 2451001,
						"RRSP": 203933,
						"Stock": 1517465,
						"TFSA": 630873,
						"age": 64
					},
					{
						"Cash": 98730,
						"InvAssets": 2522518,
						"RRSP": 205626,
						"Stock": 1551888,
						"TFSA": 666274,
						"age": 65
					},
					{
						"Cash": 98730,
						"InvAssets": 2597874,
						"RRSP": 208508,
						"Stock": 1587092,
						"TFSA": 703544,
						"age": 66
					},
					{
						"Cash": 95209,
						"InvAssets": 2645798,
						"RRSP": 196738,
						"Stock": 1623095,
						"TFSA": 730756,
						"age": 67
					},
					{
						"Cash": 92689,
						"InvAssets": 2693677,
						"RRSP": 182053,
						"Stock": 1659915,
						"TFSA": 759020,
						"age": 68
					},
					{
						"Cash": 87998,
						"InvAssets": 2743240,
						"RRSP": 169295,
						"Stock": 1697570,
						"TFSA": 788377,
						"age": 69
					},
					{
						"Cash": 87998,
						"InvAssets": 2812356,
						"RRSP": 167275,
						"Stock": 1736080,
						"TFSA": 821003,
						"age": 70
					},
					{
						"Cash": 87998,
						"InvAssets": 2894948,
						"RRSP": 151628,
						"Stock": 1775463,
						"TFSA": 879859,
						"age": 71
					},
					{
						"Cash": 87998,
						"InvAssets": 2978031,
						"RRSP": 137297,
						"Stock": 1815739,
						"TFSA": 936997,
						"age": 72
					},
					{
						"Cash": 87998,
						"InvAssets": 3062345,
						"RRSP": 122471,
						"Stock": 1856929,
						"TFSA": 994947,
						"age": 73
					},
					{
						"Cash": 87998,
						"InvAssets": 3149614,
						"RRSP": 105946,
						"Stock": 1899053,
						"TFSA": 1056617,
						"age": 74
					},
					{
						"Cash": 87998,
						"InvAssets": 3243059,
						"RRSP": 95180,
						"Stock": 1942133,
						"TFSA": 1117748,
						"age": 75
					},
					{
						"Cash": 89147,
						"InvAssets": 3344920,
						"RRSP": 94103,
						"Stock": 1986190,
						"TFSA": 1175480,
						"age": 76
					},
					{
						"Cash": 91551,
						"InvAssets": 3451518,
						"RRSP": 92774,
						"Stock": 2031247,
						"TFSA": 1235946,
						"age": 77
					},
					{
						"Cash": 97202,
						"InvAssets": 3565131,
						"RRSP": 91353,
						"Stock": 2077326,
						"TFSA": 1299250,
						"age": 78
					},
					{
						"Cash": 102218,
						"InvAssets": 3682006,
						"RRSP": 89836,
						"Stock": 2124450,
						"TFSA": 1365502,
						"age": 79
					},
					{
						"Cash": 107222,
						"InvAssets": 3802400,
						"RRSP": 88218,
						"Stock": 2172643,
						"TFSA": 1434317,
						"age": 80
					},
					{
						"Cash": 111900,
						"InvAssets": 3926620,
						"RRSP": 86497,
						"Stock": 2221930,
						"TFSA": 1506293,
						"age": 81
					},
					{
						"Cash": 116363,
						"InvAssets": 4054920,
						"RRSP": 84670,
						"Stock": 2272334,
						"TFSA": 1581553,
						"age": 82
					},
					{
						"Cash": 120566,
						"InvAssets": 4187393,
						"RRSP": 82721,
						"Stock": 2323882,
						"TFSA": 1660224,
						"age": 83
					},
					{
						"Cash": 124778,
						"InvAssets": 4324475,
						"RRSP": 80660,
						"Stock": 2376599,
						"TFSA": 1742438,
						"age": 84
					},
					{
						"Cash": 129279,
						"InvAssets": 4466096,
						"RRSP": 78473,
						"Stock": 2430512,
						"TFSA": 1827832,
						"age": 85
					},
					{
						"Cash": 133712,
						"InvAssets": 4612546,
						"RRSP": 76157,
						"Stock": 2485648,
						"TFSA": 1917029,
						"age": 86
					},
					{
						"Cash": 137998,
						"InvAssets": 4763921,
						"RRSP": 73712,
						"Stock": 2542035,
						"TFSA": 2010176,
						"age": 87
					},
					{
						"Cash": 142396,
						"InvAssets": 4920648,
						"RRSP": 71124,
						"Stock": 2599702,
						"TFSA": 2107426,
						"age": 88
					},
					{
						"Cash": 146685,
						"InvAssets": 5082691,
						"RRSP": 68392,
						"Stock": 2658677,
						"TFSA": 2208937,
						"age": 89
					},
					{
						"Cash": 150989,
						"InvAssets": 5250365,
						"RRSP": 65512,
						"Stock": 2718989,
						"TFSA": 2314875,
						"age": 90
					},
					{
						"Cash": 155354,
						"InvAssets": 5423904,
						"RRSP": 62471,
						"Stock": 2780669,
						"TFSA": 2425410,
						"age": 91
					},
					{
						"Cash": 159664,
						"InvAssets": 5603404,
						"RRSP": 59271,
						"Stock": 2843749,
						"TFSA": 2540720,
						"age": 92
					},
					{
						"Cash": 164033,
						"InvAssets": 5789186,
						"RRSP": 55904,
						"Stock": 2908259,
						"TFSA": 2660990,
						"age": 93
					},
					{
						"Cash": 168517,
						"InvAssets": 5981521,
						"RRSP": 52359,
						"Stock": 2974233,
						"TFSA": 2786412,
						"age": 94
					},
					{
						"Cash": 173094,
						"InvAssets": 6180611,
						"RRSP": 48630,
						"Stock": 3041703,
						"TFSA": 2917184,
						"age": 95
					}
				]
			}

**Comment by AG-DavidG** [comment]
Hi @kfaiczak 

Thanks for reporting this.

This is working in the latest version - 8.0.0

Thanks

David
