### ISSUE TITLE
When the data is loaded into the grid, the page indicator shows  "1 of ? of 3000".

### ISSUE THREAD

**Issue by thanigaise** [ag-grid/ag-grid#6736]
When I use Ag-Grid, the data is successfully loaded into the grid. However, there is an issue where the number of pages at the bottom of the grid appears as **"1 of ? of 4300"** randomly. Please investigate this issue as soon as possible.

**Comment by thanigaise** [comment]
![grid](https://github.com/ag-grid/ag-grid/assets/111515229/2a11332c-e43e-487d-be7a-e9c50d233325)

**Comment by kiril-matev** [comment]
Hello @thanigaise,

Thanks for this screenshot. However, as this isn't a live sample, we can't see which **AG Grid version** you're using, or how you've configured the grid.

Please send us a live sample with AG Grid which reproduces the issue. Please use our documentation examples as a basis for such an example to reproduce the issue you're reporting.

Looking forward to your response.

**Comment by thanigaise** [comment]
Here is the attached live sample as you asked. The issue arises randomly when the data is loaded into the grid. Please check it out and reply as soon as possible.


https://github.com/ag-grid/ag-grid/assets/111515229/1e874262-f304-4a13-a92c-940a5414153b

**Comment by kiril-matev** [comment]
Hi @thanigaise,

In your previous response you've sent a video, not a live sample. This shows there is an issue but it doesn't help see the version or the configuration of AG Grid, or to find out what series of steps cause the issue.

A live sample is a plunker or a stackblitz which uses AG Grid where we can reproduce this issue. 

**Please send us a reproduction example like this, so we can investigate this further.**

Looking forward to your response.
