### ISSUE TITLE
[colspan / rowspan] Allow colspan and rowspan for cells

### ISSUE THREAD

**Issue by JeffreyRoosendaal** [ag-grid/ag-grid#674]
First, great plugin!! My table rendering time went from almost 10 seconds (_very very bad ux_) to like than 0.1s. It's still hard to believe how extremely fast it is! Thanks :)

Second, I was wondering if there's some sort of Colspan like behaviour which can be used together with `api.sizeColumnsToFit()`.

The `api.sizeColumnsToFit()` function is really great (especially combined with `$(window).resize()` to make it responsive), but all my columns are of equal width. I've been playing around with `columnApi.autoSizeColumns()` and min/max column width, but it just doesn't behave/look the way I want/hope. When I'm able to set `colspan=2` on my first column (label), it makes it twice as wide as the other columns, and that's actually exaclty what I want to achieve.

There's probably a way to do so, but how can it be combined with `api.sizeColumnsToFit()`?

**Comment by ceolter** [comment]
thanks for positive feedback. 

there is no colspan feature in the grid. this is a css html <table> solution, which i have not tried to replicate.

**Comment by ceolter** [comment]
it's already on my external list, to put in colspan - suppose no harm in turning this feature request back on. there are about 250 issues now - most of which are minor feature requests i believe, so we don't take github to seriously, what we go to for work is our project plan, and that's internal to ag-Grid company.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-102

**Comment by makinggoodsoftware** [comment]
This should be done now

**Comment by Joebob12** [comment]
I've seen examples of the colspan on the site. Is there anywhere I can look at examples of the rowspan?

**Comment by ElVisPL** [comment]
+1

I guess row spanning is still not supported
