### ISSUE TITLE
Cannot export to CSV or Excel in AG-Grid-React

### ISSUE THREAD

**Issue by shaunnez** [ag-grid/ag-grid#6745]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
    "@ag-grid-community/client-side-row-model": "^28.2.1",
    "@ag-grid-community/core": "^28.2.1",
    "@ag-grid-community/react": "^28.2.1",
    "@ag-grid-enterprise/column-tool-panel": "^28.2.1",
    "@ag-grid-enterprise/excel-export": "^30.0.0",
    "@ag-grid-enterprise/filter-tool-panel": "^28.2.1",
    "@ag-grid-enterprise/menu": "^28.2.1",
    "@ag-grid-enterprise/row-grouping": "^28.2.1",
    "@ag-grid-enterprise/set-filter": "^28.2.1",
    "@ag-grid-enterprise/sparklines": "^28.2.1",

//Register License for AGGrid
LicenseManager.setLicenseKey(`${config.agGridLicense}`);

// Register the required feature modules with the Grid
ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  SetFilterModule,
  RowGroupingModule,
  MenuModule,
  SparklinesModule,
  CsvExportModule,
  ExcelExportModule,
]);

If reporting a bug make sure to state.

Current behaviour.
Trying to export the table as a CSV or Excel by using the gridRef or the gridApi directly causes an error.

          gridRef.current!.api.exportDataAsExcel();

       Uncaught TypeError: Cannot read properties of null (reading 'is') at ExcelCreator.isExportSuppressed (excelCreator.js:262:1)

      <AgGridReact
        ref={gridRef}
        domLayout={'autoHeight'}
        animateRows
        onGridReady={onGridReady}
        rowData={rowData}
        rowGroupPanelShow={'never'}
        groupDefaultExpanded={-1}
        columnDefs={columnDefs}
        suppressDragLeaveHidesColumns={true}
        suppressMakeColumnVisibleAfterUnGroup={true}
        suppressRowGroupHidesColumns={true}
        suppressAggFuncInHeader={true}
        sideBar={{
          toolPanels: ['columns', 'filters'],
          defaultToolPanel: 'columns',
          hiddenByDefault: false,
        }}
        defaultColDef={{
          sortable: true,
          filter: true,
          resizable: true,
        }}></AgGridReact>

**Expected behavior**
It should export to CSV or Excel.

**Please tell us about your environment:**
Windows - Chrome, Firefox, Brave

**Comment by StephenCooper** [comment]
You cannot mix versions of AG Grid. I suspect that this is the cause of your issues. Please use the same version across every module. I am going to close the ticket as this feature is working for us. Feel free to re-open if you still believe there is a bug when using all the same versions.

```
"@ag-grid-enterprise/column-tool-panel": "^28.2.1",
"@ag-grid-enterprise/excel-export": "^30.0.0",
```
