### ISSUE TITLE
[High Frequency] bug report issue, onCellClicked function no working when high frequency update item

### ISSUE THREAD

**Issue by chenhui996** [ag-grid/ag-grid#6746]
**I'm submitting a bug issue**

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/KHke0ATNizs2s4u5?open=Hello.js&deferRun=1

**Current behavior**
The onCellClicked function no working when high frequency update item

**Expected behavior**
The onCellClicked function works every time an item is updated（50ms）

**Please tell us about your environment:**

- AG Grid version: X.X.X
  - "ag-grid-community": "^29.3.5",
  - "ag-grid-react": "^29.3.5",

- Browser:
  - Chrome
 
- Language: 
  - "react": "^18.2.0",
  - "react-dom": "^18.2.0",
(use npx create-react-app)

**Comment by chenhui996** [comment]
Perhaps all row events are invalid.

**Comment by StephenCooper** [comment]
I have tried your plunker and clicking on a cell works every time so I am not sure what the issue is. I will close for now but feel free to come back with more details of what exactly is not working.

**Comment by chenhui996** [comment]
> I have tried your plunker and clicking on a cell works every time so I am not sure what the issue is. I will close for now but feel free to come back with more details of what exactly is not working.

My onCellClicked event is console a line of information.

However, when I look at the console, it doesn't always print out, so onCellClicked doesn't work every time you click.

（If I stop the high-speed push, onCellClicked will take effect every time）

**Comment by chenhui996** [comment]
Maybe it's my Computer performance?

M1 16g
