### ISSUE TITLE
SetFilter not working with complex values (id/name) in filter values and just id as column value

### ISSUE THREAD

**Issue by moodyVlad** [ag-grid/ag-grid#6747]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```
Current behaviour.
I want to use the agSetColumnFilter in the following scenario:
Complex objects id/name pairs as values in the filterParams object.
Just the id as the column value.
I have set the keyCreator function to return params.value.id 
I have set the valueFormatter function in filterParams to return params.value.name. 

**Current behavior**
The set filter list shows correct labels however filtering does not work.

**Expected behavior**
Have a way to tell the set filter which property int he complex value it should filter on seing that the column value is an id and the filter value contains a list of id/name objects.

**Please tell us about your environment:**
Irelevant

* **AG Grid version:** X.X.X
29.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES
* Typescript

**Comment by kiril-matev** [comment]
Hello @moodyVlad,

Please see a working example using the set filter with complex objects here:
https://www.ag-grid.com/javascript-data-grid/filter-set-filter-list/#complex-objects

Use the same approach to implement this on your side.

Also, I'd suggest upgrading to a later version of AG Grid.
