### ISSUE TITLE
applyTransaction flushSync Error use in "UseEffect"

### ISSUE THREAD

**Issue by bo-hyeon** [ag-grid/ag-grid#6751]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
I used 'applyTransaction' after 'forEachNodeAfterFilterAndSort' in useEffect to update several rows, but I get the following error.
```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
```

this is my code 
```
const itemsToUpdate = []
    gridRef.current.api.forEachNodeAfterFilterAndSort(function (
      rowNode,
      index,
    ) {
      const data = rowNode.data
      data.area1 = 123

      itemsToUpdate.push(data)
    })

    gridRef.current.api.applyTransaction({
      update: itemsToUpdate,
    })
```

**Expected behavior**
However, the grid results are as desired. Can I ignore this error?

**Please tell us about your environment:**

* **AG Grid version:** 30.0.0

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** React

**Comment by bo-hyeon** [comment]
solved, It was my code problem.

**Comment by cworsley4** [comment]
Could you expand a bit on what the issue was? I'm experiencing the same issue.
