### ISSUE TITLE
How do I update both the value of the edit input and the value of the current cell?

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#6753]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

![1686647106836](https://github.com/ag-grid/ag-grid/assets/57131579/661ebac6-3bfa-440f-9eee-13f860c2005f)
I'll use the Text Cell Editor and type in 998. Changed the 'productName' value using API assignment during editing.
` rowNode.setDataValue('productName', result.name);`

However, when the editing is finished, the value 998 is reassigned. Is it possible to update the value of 998 at the same time without using this.gridApi.stopEditing(), or is there a better way?

* **AG Grid version:** 29.3.5
* **Browser:**
Google Chrome  114.0.5735.110

**Comment by kiril-matev** [comment]
Hi @afr751116,

We need to see the exact scenario in order to advise.

Please send us a live example which shows you use case in action.

Looking forward to your response.
