### ISSUE TITLE
MouseMove fires angular change detection impacting profiling DX

### ISSUE THREAD

**Issue by athomas-scottlogic** [ag-grid/ag-grid#6767]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using Ag grid angular
MouseMove Events trigger angular change detection which hampers the ability to profile an angular application using ag grid

Launch Angular dev tools
Go to profiler and start it
Move mouse over grid and observe change detection cycles

**Expected behavior**
Change Detection does not fire for mousemove similar to mouseover and mouseout events.

This could be achieved by adding MouseMove is added to `OUTSIDE_ANGULAR_EVENTS` similar to mouseover and mouseout? Not sure if Ag Grid needs to be in the angular zone to handle this event correctly?

* **AG Grid version:** 29.3.5

* **Browser:** All

* **Language:** all

**Comment by scottfwalter** [comment]
Interesting change detect cycle is happening when you move the mouse within the header row.   For cells it seems to be fired when you move from one cell to another.

**Comment by athomas-scottlogic** [comment]
Fabulous, thank you so much

**Comment by scottfwalter** [comment]
The change detection cycles are still happening for the app even if you use the onPush.    The components with onPush just won't be part of the change detection cycle.   Angular is still kicking off tick() with simple mouse moves in the header of the ag-grid.

**Comment by StephenCooper** [comment]
Ok, I have made the changes for mousemove to run outside of Angular as suggested above and that does improve things. This should be part of the next release as long as we don't find any issues with this change.
