### ISSUE TITLE
Rich Select Editor doesn't collapse when clicking away from it

### ISSUE THREAD

**Issue by dmathisen** [ag-grid/ag-grid#6770]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/itccry7C3wB0DwVQ?open=index.jsx&preview

**Current behavior**
When opening the Rich Select Editor, you can't click away to collapse it.
![image](https://github.com/ag-grid/ag-grid/assets/684701/dcd88fce-85ae-425d-a752-c2d0a711dc84)

**Expected behavior**
I'd expect the Rich Select Editor popup to collapse/go away when clicking outside of the grid. The column menu works this way, as expected.
![image](https://github.com/ag-grid/ag-grid/assets/684701/034c8c59-2bf3-4f71-b50e-735a27fd2c85)

NOTE: It's unclear if it's because of `popupParent` or not, and it may be by design. That is unclear.

**Please tell us about your environment:**
Windows 10
All browsers

* **AG Grid version:** Tested in 30.0.0 and 29.3.5

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

* **Language:** Typescript 5.1.3

**Comment by StephenCooper** [comment]
https://ag-grid.com/react-data-grid/cell-editing-start-stop/#stop-editing-when-grid-loses-focus

https://plnkr.co/edit/ckQcXE7rCIw7xqR9?open=index.jsx
