### ISSUE TITLE
Latest version (30.0.1) causes application to fail

### ISSUE THREAD

**Issue by jmfolds** [ag-grid/ag-grid#6778]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Getting an error trying to use latest 30.0.1 build, see stackblitz here:

https://stackblitz.com/edit/stackblitz-starters-utptze

**Current behavior**
importing ag-grid-react throws `Class constructor BaseComponentWrapper cannot be invoked without 'new'`

**Expected behavior**
it doesn't blow up / renders a table

**Please tell us about your environment:**
stackblitz

* **AG Grid version:** X.X.X
30.0.1

* **Browser:**
chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

**Comment by seanlandsman** [comment]
Please try `ag-grid-react` 30.0.2 - I believe this should resolve this issue

**Comment by seanlandsman** [comment]
Note: the stackblitz example fails for a different reason now - but if you're using react-script it'll work.

I'll investigate the stackblitz issue next

**Comment by softy2k** [comment]
In **Vue 2.7.14**, **Chrome** and **FireFox**, after update from **30.0.0** to **30.0.1** I got error:

`[Vue warn]: Error in mounted hook: "TypeError: Class constructor BaseComponentWrapper cannot be invoked without 'new'"
found in
---> <AgGridVue>
       <LargeDataSetExample> at src/Test.vue
         <VApp>
           <App> at src/App.vue
             <Root>`


`TypeError: Class constructor BaseComponentWrapper cannot be invoked without 'new'
    at new VueFrameworkComponentWrapper (VueFrameworkComponentWrapper.js:27:1)
    at AgGridVue.mounted (AgGridVue.js:85:1)
    at invokeWithErrorHandling (vue.common.dev.js:3636:1)
    at callHook$1 (vue.common.dev.js:3052:1)
    at Object.insert (vue.common.dev.js:4858:1)
    at invokeInsertHook (vue.common.dev.js:6875:1)
    at VueComponent.patch [as __patch__] (vue.common.dev.js:7084:1)
    at Vue._update (vue.common.dev.js:2791:1)
    at VueComponent.updateComponent (vue.common.dev.js:2897:1)
    at Watcher.get (vue.common.dev.js:4117:1)
logError @ vue.common.dev.js:3668
globalHandleError @ vue.common.dev.js:3660
handleError @ vue.common.dev.js:3627
invokeWithErrorHandling @ vue.common.dev.js:3643
callHook$1 @ vue.common.dev.js:3052
insert @ vue.common.dev.js:4858
invokeInsertHook @ vue.common.dev.js:6875
patch @ vue.common.dev.js:7084
Vue._update @ vue.common.dev.js:2791
updateComponent @ vue.common.dev.js:2897
get @ vue.common.dev.js:4117
run @ vue.common.dev.js:4193
flushSchedulerQueue @ vue.common.dev.js:3142
eval @ vue.common.dev.js:3762
flushCallbacks @ vue.common.dev.js:3684
Promise.then (async)
timerFunc @ vue.common.dev.js:3709
nextTick @ vue.common.dev.js:3774
Vue.$nextTick @ vue.common.dev.js:2436
eval @ vue-router.esm.js:2404
step @ vue-router.esm.js:2084
step @ vue-router.esm.js:2091
runQueue @ vue-router.esm.js:2095
eval @ vue-router.esm.js:2397
step @ vue-router.esm.js:2084
eval @ vue-router.esm.js:2088
eval @ vue-router.esm.js:2384
eval @ vue-router.esm.js:2162
iterator @ vue-router.esm.js:2362
step @ vue-router.esm.js:2087
step @ vue-router.esm.js:2091
runQueue @ vue-router.esm.js:2095
confirmTransition @ vue-router.esm.js:2392
transitionTo @ vue-router.esm.js:2260
init @ vue-router.esm.js:2996
beforeCreate @ vue-router.esm.js:1298
invokeWithErrorHandling @ vue.common.dev.js:3636
callHook$1 @ vue.common.dev.js:3052
Vue._init @ vue.common.dev.js:4647
Vue @ vue.common.dev.js:5696
eval @ main.js:27
./src/main.js @ app.js:135
__webpack_require__ @ app.js:285
(anonymous) @ app.js:1407
__webpack_require__.O @ app.js:331
(anonymous) @ app.js:1408
(anonymous) @ app.js:1410`

**Comment by seanlandsman** [comment]
@softy2k please upgrade to `ag-grid-community` 30.0.2 - and you'll need to add the following to your vue config:

```
module.exports = defineConfig({
  configureWebpack: {
    resolve: {
      alias: {
        'ag-grid-community/styles': path.resolve(__dirname, 'node_modules/ag-grid-community/styles'),
        'ag-grid-community': path.resolve(__dirname, 'node_modules/ag-grid-community/dist/ag-grid-community.cjs.js'),
      }
    },
```
