### ISSUE TITLE
When 'applyTransaction' called, 'cellRenderer' does not have an update of the parameter.

### ISSUE THREAD

**Issue by bo-hyeon** [ag-grid/ag-grid#6788]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
When an update list is created using `forEachNodeAfterFilterAndSort` and grid data is updated using `applyTransaction`, the update response of the parameter 'CellRenderer' does not occur. But updates the data in the visible grid. 
And also `setDataValue` not updated, too. But `setData` is worked. However, it is difficult to handle many rows one by one.

Update function:
```
const itemsToUpdate = []
        gridApi.forEachNodeAfterFilterAndSort(function (rowNode) {
          const data = rowNode.data
          data.state = { ...data.state,  abcd: false }
          itemsToUpdate.push(data)
        })

        gridApi.applyTransaction({
          update: itemsToUpdate,
        })
```

CellRenderer:
```
const CustomRenderer = ({ data }) => {
 useEffect(()=>{
console.log('data changed'); // <---------------------------------not called
},[data])
})
```

field:
```
...
{
      field: 'price',
      headerName: 'prices',
      cellRenderer: CustomRenderer ,
      sortable: true,
      unSortIcon: true,
      resizable: true,
      width: 64,
    },
...
```

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** 30.0.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** React

**Comment by zoheil-ag** [comment]
Hi @bo-hyeon,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
