### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by uito-s** [ag-grid/ag-grid#6789]
I am using ag-grid-recat v30.0.2 with nextjs 13.0.2 and react 18.2.0, here is the error I get in terminal console:
```
error - /Users/me/Documents/Github/projectname/node_modules/ag-grid-react/lib/agGridReact.js:2
import React, { Component } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/me/Documents/Github/projectname/node_modules/ag-grid-react/main.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  page: '/jobs/view/[id]'
}
```

I only use the sample code from ag-grid website:
```
<AgGridReact
            rowData={rowData}
            columnDefs={columnDefs}
            defaultColDef={defaultColDef}
            enableFillHandle={true}
            enableRangeSelection={true}
            onGridReady={onGridReady}
></AgGridReact>
```

**Comment by kiril-matev** [comment]
Hello @uito-s,

Thank you for reporting this.

We've resolved exactly this issue in v30.0.2:
https://ag-grid.com/changelog/?fixVersion=30.0.2

Can you please clean/rebuild your project to ensure you're using AG Grid v30.0.2? 

If you can still reproduce this issue, send us a sample project we can reproduce this issue with.

We're looking forward to your response.

**Comment by goseivietnam** [comment]
It's same to me

**Comment by waseem196** [comment]
@goseivietnam try using the following versions of Ag grid:
    "ag-grid-community": "^29.3.5",
    "ag-grid-react": "^29.3.5",

It is now working for me.

**Comment by seanlandsman** [comment]
Please add the following to your next.config.js:

`transpilePackages: ['ag-grid-community', 'ag-grid-react'],`

**Comment by knightjdr** [comment]
> Please add the following to your next.config.js:
> 
> `transpilePackages: ['ag-grid-community', 'ag-grid-react'],`

This does not resolve the issue for me.

**Comment by bluefire2121** [comment]
Issue exists in Remix as well

**Comment by seanlandsman** [comment]
@knightjdr @bluefire2121 do you have a repo I can take a look at?

**Comment by ethras** [comment]
same issue here

**Comment by rdpascua** [comment]
same issue im encountering nextjs `13.4.7` using `ag-grid-react` `^30.0.2`

**Comment by seanlandsman** [comment]
If you're able to provide a repro to demonstrate this issue I'll be happy to take a look.
