### ISSUE TITLE
The action of rowSelection in fullWidthCellRender

### ISSUE THREAD

**Issue by bo-hyeon** [ag-grid/ag-grid#6790]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
Cannot click `html tag` of `fullWideCellRender` while `rowSelection` is `single`.
1. Open
https://plnkr.co/edit/7dAyrDLKhbeMjHlT?open=main.js
2. Click the FRENCH flag button
Actual & Expected: Alert popup shown
3. Click the French row to select it
4. Click the FRENCH flag button
**Actual**: Alert popup not displayed
**Expected**: Alert popup shown

Can try [https://ag-grid.com/react-data-grid/full-width-rows/#full-width-keyboard-navigation](url) code.
Setting `rowSelection={'single'}`, please.

**Expected behavior**
I would like to click on the element of `fullWideCellRender` while `rowSelection` is `single`.

**Please tell us about your environment:**

* **AG Grid version:** 30.0.0

* **Browser:**Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** React

**Comment by zoheil-ag** [comment]
Hi @bo-hyeon,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
