### ISSUE TITLE
Is sparkline feature available in v25.1.0

### ISSUE THREAD

**Issue by RavalikaP** [ag-grid/ag-grid#6792]
We have v25.1.0 of ag-grid is Sparkline feature is supported in this version?
https://www.ag-grid.com/javascript-data-grid/sparklines-bar-customisation/

**Comment by kiril-matev** [comment]
Hi @RavalikaP,

Sparklines were added in AG Grid Enterprise 26.1:
https://blog.ag-grid.com/whats-new-in-ag-grid-26-1/

Please upgrade to AG Grid v26.1 or later to use sparklines.
