### ISSUE TITLE
Not able to test ag-grid floating filter

### ISSUE THREAD

**Issue by nareshkumar7593** [ag-grid/ag-grid#6802]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

  _**
  
    fit('should filter by greater than value entered in input box', fakeAsync(() => {

    fixture.autoDetectChanges()
    flush();

    const gridApi = component?.gridOptions?.api;
    console.log('row count --->',gridApi?.getDisplayedRowCount());

     const inputElement = fixture.debugElement.query(By.css('.ag-floating-filter-input'));

    const newEve = new Event('input');
    console.log(inputElement)

    inputElement.nativeElement.value = 'hello';
    inputElement.nativeElement.dispatchEvent(new Event('input'));

    flush();
    expect(fixture.debugElement.query(By.css('.ag-floating-filter-input')).nativeElement.value).toBe('hello');
    expect(gridApi?.getDisplayedRowCount()).toBe(1);

    }));
  **_

Link to Testing with FakeAsync id Broken [https://www.ag-grid.com/angular-data-grid../testing-async/]

**Current behavior**
Displayed row count still shows the initialised row count 

**Expected behavior**
Grid should filter and display row based on filter criteria

**Please tell us about your environment:**
Angular15

* **AG Grid version:** X.X.X
    "ag-grid-angular": "^29.3.5",
    "ag-grid-community": "^29.3.5",

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by zoheil-ag** [comment]
Hi @nareshkumar7593,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
