### ISSUE TITLE
Make ag-grid scroll stick to the right

### ISSUE THREAD

**Issue by iamaliybi** [ag-grid/ag-grid#6808]
I'm using the "ltr" version of "ag-grid" but I want to scroll to the right with"api" method or something else. How it's possible?
Notice: I don't wanna use "rtl" version

`ag-grid react`
![image](https://github.com/ag-grid/ag-grid/assets/31594561/eac71b93-cad9-4626-9cb5-b3baec8fb358)

**Comment by zoheil-ag** [comment]
Hi @iamaliybi,

Thank you for submitting this on Github.

The following may meet your requirement: https://ag-grid.com/javascript-data-grid/grid-api/#reference-scrolling-ensureColumnVisible.

As this has been open without any further interaction for a while, I will be closing this issue soon.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
