### ISSUE TITLE
[Bug] AgGrid Infinite render when double scroll is on and cellRenderer is used

### ISSUE THREAD

**Issue by ATGroupFreelance** [ag-grid/ag-grid#6809]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

**Current behavior**
1- Change the width of browser in a way that there is horizontal  scroll
2- Change the height of the browser in a way that there is vertical scroll
3- Use cellRenderer in one of the columnDefs, this column must be out of screen
4- Use Material UI Button as the cellRenderer
5- scroll so you can see the button
6- Look at console log and you can see each time you move the scroll there is an error happening.
Please note if you are using something like codesandbox, you have to right click on the rendererd page and open the console log from there until you see the errors (the platform doesn't show the error)

Here is a very simple example that shows this bug, everything is made form scratch.
https://codesandbox.io/s/aggrid-scroll-cellrendererbug-svxz4j?file=/src/App.js

**Expected behavior**
I expect this bug to not happen.

**Please tell us about your environment:**

Os: Windows

* **AG Grid version:** 30.0.2
* This error also happens in version 29. but it doesn't happen in version 28

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ReactJS

**Comment by ATGroupFreelance** [comment]
HI @kiril-matev Thank you for following up on the problem.
Here is a local reproducible demo on my git repo:
https://github.com/ATGroupFreelance/aggrid-scroll-bug
**To see the problem:** 
1- open dev tools and go to console log
2- Scroll the grid vertically so you can see the button column at the end.
Finally I can guess why you couldn't reproduce it, there are a few condition needed for this problem to occur:
1- There must be enough rows so horizontal scroll is enabled.
2- Vertical scroll must be enabled
3- The button columns must be out of sight at the beginning so you can scroll to it
Thank you!
Here is an screen shot of the issue using the git repo : 
![image](https://github.com/ag-grid/ag-grid/assets/108724502/a0268b77-8da0-4ddb-805c-c25bd796e220)

**Comment by StephenCooper** [comment]
Hi @ATGroupFreelance,

We made a number of improvements to our React components in v30.1 that was released this morning. When using this version your demo project no longer throws any errors. 

Could you try upgrading to v30.1 and see if that resolves the issues for you?

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
