### ISSUE TITLE
I want to make "Cell Render Keyboard Navigation" into a arrow key

### ISSUE THREAD

**Issue by bo-hyeon** [ag-grid/ag-grid#6813]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
[This link](https://ag-grid.com/react-data-grid/component-cell-renderer/#cell-renderer-keyboard-navigation) enabled the implementation of cell renderer focus with the tab key. However, after applying the condition of the arrow key (keycode: 37-40), the grid scroll moves, not the cellrender focus.  I want to apply this function to the arrow key, is there a way?

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** 30.0.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** React

**Comment by amirsarfar** [comment]
Hi @bo-hyeon.
I think you need something like this:
The removed parts are in the documentation example too.
```javascript
const suppressKeyboardEvent = ({ event }) => {
...
  if(["ArrowLeft","ArrowRight"].includes(key)){
    const eGridCell = path.find((el) => {
      if (el.classList === undefined) return false;
      return el.classList.contains(GRID_CELL_CLASSNAME);
    });
    if (!eGridCell) {
      return false;
    }
    const focusableChildrenElements = getAllFocusableElementsOf(eGridCell);
    const currentFocus = focusableChildrenElements.findIndex((item)=>document.activeElement === item);
    console.log(currentFocus)
    const direction = key==="ArrowLeft"?-1:key==="ArrowRight"?1:0;
    const nextFocus = focusableChildrenElements[currentFocus+direction];
    console.log(nextFocus)
    if(nextFocus)nextFocus.focus();
    return !!nextFocus;
  }
...
}
```

**Comment by zoheil-ag** [comment]
Hi @bo-hyeon,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
