### ISSUE TITLE
Vue2 uses ag-grid-vue 30.0.2 to report an error

### ISSUE THREAD

**Issue by xu1223** [ag-grid/ag-grid#6814]
version number used
"vue": "^2.7.14",
"ag-grid-community": "~30.0.2",
"ag-grid-enterprise": "~30.0.2",
"ag-grid-vue": "~30.0.2",
![970ab53-cd8b-4d24-830c-0a4d2811c817](https://github.com/ag-grid/ag-grid/assets/58723067/d24cb993-4e78-4f68-9e7a-1a3b7b5d97e0)

After configuring vue.config.js according to [6778](https://github.com/ag-grid/ag-grid/issues/6778), an error is still reported

![企业微信截图_858f00ba-fd11-415b-87da-f459a04f03f1](https://github.com/ag-grid/ag-grid/assets/58723067/b54539a5-38a2-4ebf-acc0-3baa2640e770)

![企业微信截图_7ecde4e2-412d-4c4d-9b8a-ed051c6a5e5b](https://github.com/ag-grid/ag-grid/assets/58723067/6a399859-b9cf-40f6-8d6e-3d43b21f2c16)

**Comment by softy2k** [comment]
To fix this error, in file **vue.config.js** , in **alias** object, add this lines

`'ag-grid-community/styles': path.resolve(__dirname, 'node_modules/ag-grid-community/styles'),
 
'ag-grid-community': path.resolve(__dirname, 'node_modules/ag-grid-community/dist/ag-grid-community.cjs.js'),

 'ag-grid-enterprise/styles': path.resolve(__dirname, 'node_modules/ag-grid-enterprise/styles'),

'ag-grid-enterprise': path.resolve(__dirname, 'node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js'),`

**Comment by hongzen** [comment]
I'm using: 
  "vue": "^2.6.12",
  "ag-grid-community": "^30.0.2",
  "ag-grid-vue": "^30.0.2", 
  
and I have the "Class constructor BaseComponentWrapper cannot be invoked without 'new'" error too.

I added the following to vue.config.js  
    alias: {
        'ag-grid-community/styles': path.resolve(__dirname, 'node_modules/ag-grid-community/styles'),
        'ag-grid-community': path.resolve(__dirname, 'node_modules/ag-grid-community/dist/ag-grid-community.cjs.js'),
    }
but still have the same error.

**Comment by nanayaw-kirk** [comment]
I had this error in a Nuxt 2 application after changing some unrelated code to ag-grid and upgrading to vue 2.7.0
I solved it by transpiling it in the  nuxt.config as  a quick fix
`build: {
    transpile: ['ag-grid']
}` 
Maybe this could help anyone with an issue similar to mine.
Also open to a more elegant solution

**Comment by SanthoshBanavath** [comment]
I am using 
    ag-grid-community: ^30.0.3
    ag-grid-vue: ^30.0.3
    "vue": "^2.7.9"
And also added paths to aliases. Still seeing the same error. Followed the official documentation https://www.ag-grid.com/vue-data-grid/vue2/

**Comment by softy2k** [comment]
Using **Vue version: 2.7.14** is OK for me...

**Comment by seanlandsman** [comment]
Are you able to provide a reproducible example of this? Our testing doesn't show the errors reported above

thanks

**Comment by WalrusSoup** [comment]
I ran into this and was able to fix it with Vite and Vue 2 on an old repo we have.

`Cannot read properties of undefined (reading 'concat’)`

The main issue is that the community features cannot be imported (AllCommunityModules or something is undefined). Anyway, here is the fix inside of the `vite.config.js file` .

```js
  resolve: {
      alias: {
          vue: 'vue/dist/vue.esm.js',
          'ag-grid-community/styles': path.resolve(__dirname, 'node_modules/ag-grid-community/styles'),
          'ag-grid-community': path.resolve(__dirname, 'node_modules/ag-grid-community/dist/ag-grid-community.js')
      }
  }
```

With this, the import is correctly working so the concat is also working. Hope this helps anyone who comes across this.
