### ISSUE TITLE
Cell renderer params is not reactive when rowid are static

### ISSUE THREAD

**Issue by akkashk1** [ag-grid/ag-grid#6815]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Github demo link: https://github.com/akkashk1/ag-grid-demo

Packages required to run demo:
vue: 3.2.13
ag-grid-community: 30.0.2
ag-grid-vue3: 30.0.2
core-js: 3.8.3

Steps to run project:
- Clone the project from demo URL.
- Run 'npm install' inside project directory.
- Run 'npm run serve'.

**Current behavior**
When you click on refresh button in "Ag-grid Static Row ID" odd & even status will no get updated. But when you click on  refresh button in "Ag-grid Dynamic Row ID" odd & even status will be updated. Both refresh button will update count data and "odd or even" column will be update by cell renderer. But when you use static id then cell renderer will not update props data. On the other hand when you use dynamic id then it will updated props data. 

**Expected behavior**
Cell renderer params needs to be reactive when we are using static row id.

* **AG Grid version:** 30.0.2

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by prempopatia** [comment]
I also have same problem, did anyone find any solution? Really needed the solution as it is crucial part of development.

**Comment by prempopatia** [comment]
Is there any update on this issue or ticket? ag grid pipeline shows "scheduled" only. As vue 3 has came and its been quite a good time, script setup syntex is important format. Please do the needful as requested feature is basic and necessary feature used in ag grid.

**Comment by AG-Zoheil** [comment]
Hi @prempopatia,

Thank you for your comment.

AG-8274 is on our list of deliverables in Q4. We have already started our work on it.

We appreciate your patience.

Kind regards,

**Comment by akkashk1** [comment]
Hello,
I have checked that AG-8274 is shown as solved in changelog but issue is still remaning. I have checked with ag-grid version 31.0.0 and also with 31.0.1. Please check above git repository(https://github.com/akkashk1/ag-grid-demo).

**Comment by StephenCooper** [comment]
Hi,

In the static case the grid does not know that the values for the Odd or Even column have changed. You can force it to rerender by adding the following at the end of your refresh method.

```
  gridApi.value.refreshCells({ force: true })
```

The dynamic case works because by changing all the row Ids, this makes the grid re-draw all the rows as it considers them new.
