### ISSUE TITLE
[ag-grid-react:30.0.2] fails with vitest while 29 works fine

### ISSUE THREAD

**Issue by spamshaker** [ag-grid/ag-grid#6819]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

grid-packages/ag-grid-react seems to be wrongly exposed

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
here is a repo where on master after doing `npm i && npm run test` sample test fails
https://github.com/spamshaker/vitest-ag-grid-issue

with version 29 works fine
https://github.com/spamshaker/vitest-ag-grid-issue/pull/1/files

If reporting a bug make sure to state.

Current behaviour.

**Current behavior**
Syntax error while module resolution

```
SyntaxError: Cannot use import statement outside a module
 ❯ Object.<anonymous> node_modules/ag-grid-react/main.js:1:23

Module node_modules/ag-grid-react/lib/agGridReact.js:2 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "ag-grid-react" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "ag-grid-react"
      ]
    }
  }
}

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  07:13:17
   Duration  239ms (transform 27ms, setup 0ms, collect 0ms, tests 0ms, environment 68ms, prepare 50ms)
```

**Expected behavior**
Correct modules exposition

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 62.80 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v20.3.1/bin/npm
    pnpm: 8.6.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.58
    Safari: 16.5.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.0 => 4.0.1 
    ag-grid-react: ^30.0.2 => 30.0.2 
    typescript: ^5.0.2 => 5.1.5 
    vite: ^4.3.9 => 4.3.9 
    vitest: ^0.32.2 => 0.32.2

**Comment by seanlandsman** [comment]
Thanks for reporting this and thanks especially for the repro - this greatly assists in me finding a solution.

I believe I have a fix for this - I'll update this thread shortly

**Comment by spamshaker** [comment]
@seanlandsman 
no problem, thank you for taking care of it

**Comment by seanlandsman** [comment]
Release 30.0.3 has been released which should resolve this issue.

thanks

**Comment by spamshaker** [comment]
@seanlandsman, Works well, thank you!
