### ISSUE TITLE
Ag-Grid overlapping the child rows by parent row in Version 30.0.0.

### ISSUE THREAD

**Issue by DivakarSS** [ag-grid/ag-grid#6820]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
* Project migration from Vue2 to Vue3. and ag-grid version 29.x.x to 30.0.0 .

**Current behavior**
The grid is overlapping the child row by the parent row in version 30.0.0.
I am attaching the recordings of version 30.0.0 for reference.
[AG-Grid_New_Version_Overlapping_Issue.webm](https://github.com/ag-grid/ag-grid/assets/69146417/1bc05974-1cb2-4887-8dec-c6368ad5ea46)

**Expected behavior**
The grid should not overlap the child row by parent row.  It should be able to scroll smoothly like in the attached video.
I am attaching the recordings of version 29.1.0 for reference.
[AG-Grid_Version_29.webm](https://github.com/ag-grid/ag-grid/assets/69146417/6019f6c5-c8d0-479c-ae5b-6b89aee4fddc)
 

**Please tell us about your environment:**
O.S: Windows 10
IDE: VS Code
Package Manager: npm
* **AG Grid version:** 30.0.0
* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'
* Vue: 3.2.13
* ag-grid-vue3: 30.0.0
* ag-charts-vue3: 8.0.0
* ag-charts-community: 8.0.0
* TypeScript: 4.5.5

**Comment by kiril-matev** [comment]
Hi @DivakarSS,

Please when upgrading to a new version of AG Grid go through the release notes. In the release notes for v30 we've documented that group sticky rows are now enabled by default. 
https://ag-grid.com/changelog/?fixVersion=30.0.0

This is why the group header row remains shown at the top of the grid viewport while you're scrolling through its child rows as shown in the examples on this page:
https://ag-grid.com/javascript-data-grid/grouping-opening-groups/#opening-group-levels-by-default

You can disable sticky group rows as documented here:
https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-rowGrouping-suppressGroupRowsSticky

**Comment by DivakarSS** [comment]
Thank You @kiril-matev for you support. I think that I missed this in change logs.
