### ISSUE TITLE
ag-charts 8.0.0 breaks Jest tests with 'SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by spyro2000** [ag-grid/ag-grid#6823]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
- Setup sample npm project
- Add ag-charts 8.0.0 and jest 28 in package.json
- Add default setup for testing (e.g. Jest)
- Try to run any test which imports class refererencing ag-grid

**Current behavior**

Tests does fail to initialize because main.js is not transpiled to ES5/CommonJS but it using ES6 syntax not supported by node.

```` 
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
(...)

  Details:

    <project-path>\node_modules\ag-charts-community\dist\esm\es6\main.js:2
    export * from './chart/agChartOptions';
    ^^^^^^
````

**Expected behavior**

Tests behave the same like they did in previous version (I jused 6.9.2 before). 

**Please tell us about your environment:**

- Angular 14,
- Jest 28

* **AG Grid version:**
 29.3.5

* **Browser:**
(Headless chrome)

* **Language:** 
Typescript / ES5

**Comment by spiroka** [comment]
Default export has been updated to ES6 modules.
You probably use a transformer for jest that allows you to write tests in TypeScript using ES modules. If this is the case you probably have the node_modules folder ignore by the transformer. What you need is a transformer that can transform js modules written using ESM to CommonJS and ag charts as exception in transformIgnorePatterns in the jest config.
In my case the transformer is ts-jest and the ignore pattern looks like this: `'/node_modules/(?!(ag-charts-community)/)'`

**Comment by spyro2000** [comment]
Hello @spiroka, yes that's basically what I had to do, to get this to run again. As I understand this, it's basically a problem with Jest or Node still not working with ES6 modules. May I suggest to add this information to the setup guide or the troubleshooting/FAQ part?

**Comment by seanlandsman** [comment]
Can you please get the try the following:

Update jest.config.js to include the following:

module.exports = {
  resolver: '<rootDir>myResolver.js'}


then create a new file called myResolver.js in the root directory with the following contents:

module.exports = (request, options) => {
    return options.defaultResolver(request, {
        ...options,
        packageFilter: pkg => {
            const packageName = pkg.name;
            const agDependency = packageName.startsWith("ag-chart");
            return {
                ...pkg,
                // default to use the CommonJS ES5 entry point for Jest testing with AG Charts
                main: agDependency ? './dist/cjs/es5/main.js' : pkg.module || pkg.main,
            };
        },
    });
};
