### ISSUE TITLE
"Columns" Tool Panel content is not available when browser is zoomed in / small screens

### ISSUE THREAD

**Issue by hoovercj** [ag-grid/ag-grid#6827]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

https://plnkr.co/edit/xJhflo6z84GtnFpb
https://run.plnkr.co/preview/cljgw76nq00083n6zvt37tsnx/

**Current behavior**
* Open "Columns" tool panel
* Enable "Pivot"
* Screen will look like this, with 4 sections in the tool panel (search + columns list, row groups, values, and column labels) 
![image](https://github.com/ag-grid/ag-grid/assets/2957173/9a93e409-3afc-4257-a1e6-9dcb78f2df27)
* Zoom in browser to 300% OR use browser devtools to reduce window size to 320px wide by 256px tall
* Screen will look like this, with search + columns list not visible, and column labels off the page. The panel cannot properly be interacted with.
![image](https://github.com/ag-grid/ag-grid/assets/2957173/dffd117a-2956-4450-8aa0-4fcea75e732c)

**Expected behavior**

It is expected that at high zoom levels or small screen sizes, all content is available to interact with. For example, a scroll bar for the whole panel could replace the individual scrollbars for each section.

This expectation is based on [W3C/WCAG 2.1 Accessibility requirements](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) and EN 301 549.

This issue is a compliance blocker from us fully adopting the component.

* **AG Grid version:** All

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by zoheil-ag** [comment]
Hi @hoovercj ,

Thank you for the detailed description of this.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

This requirement is in our backlog and we are tracking it with the following reference and description:
**AG-2550 [Grid Rendering] Add support for scaling and zoom in/out of the browser**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
