### ISSUE TITLE
@ag-grid-community/* modules usage fails the test run with Jest in Angular based project

### ISSUE THREAD

**Issue by McSim182** [ag-grid/ag-grid#6828]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

A small repo to reproduce the issue on running test with Jest clone https://github.com/McSim182/ag-grid-jest 
install deps `$ npm install`
run test `$ npm test`

alternatively: 
1) generate new nx nrwl angular project 
2) install @ag-grid-community deps listed below 
```
"@ag-grid-community/angular": "^30.0.2",
"@ag-grid-community/client-side-row-model": "^30.0.2",
"@ag-grid-community/core": "^30.0.2",
"@ag-grid-community/styles": "^30.0.2",
```
3) add `<ag-grid-angular></ag-grid-angular>` component into app.component.html 
4) add `@ag-grid-community` to transformIgnorePatterns so they look similar to this 
`transformIgnorePatterns: ['node_modules/(?!(.*\\.mjs$)|@ag-grid-community)'],`
5) Adjust the test case 
```
import { AgGridModule } from '@ag-grid-community/angular';
import { TestBed } from '@angular/core/testing';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [AppComponent, AgGridModule],
    }).compileComponents();
  });

  test('should render title', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    expect(fixture.componentInstance).toBeTruthy();
  });
});
```
6) run `$ npm test`

**Current behavior**
Fails with error 
```
   TypeError: Class constructor VanillaFrameworkOverrides cannot be invoked without 'new'

      at new AngularFrameworkOverrides (node_modules/@ag-grid-community/angular/bundles/ag-grid-community-angular.umd.js:442:30)
      at NodeInjectorFactory.AngularFrameworkOverrides_Factory [as factory] (ng:/AngularFrameworkOverrides/ɵfac.js:5:10)
      at NodeInjectorFactory.AgGridAngular_Factory [as factory] (ng:/AgGridAngular/ɵfac.js:6:56)
```
Even though  `@ag-grid-community` packages are added to `transformIgnorePatterns`

**Expected behavior**
Tests should pass without an error 

**Please tell us about your environment:**
Tested on Win10 and MacOS with nodejs versions v16.17.1, v18.12.0

* **AG Grid version:** 30.0.2
```
"@ag-grid-community/angular": "^30.0.2",
"@ag-grid-community/client-side-row-model": "^30.0.2",
"@ag-grid-community/core": "^30.0.2",
"@ag-grid-community/styles": "^30.0.2",
```

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript versions 5.0.2, 5.1.3

Things tried already: 
- changing `target` in *.spec.json tsconfig to modern specs (ES6, ES2022)

**Comment by shaun-jacks** [comment]
I'm also running into this issue

**Comment by seanlandsman** [comment]
Thanks for the repo.

Can you please provide a repo _without AG Grid_ that passes?  I've tried removing AG Grid from the repo you provided and it fails with other errors.

I believe I have something that should fix this for you but wanted a baseline to work with.

thanks

**Comment by McSim182** [comment]
Worked like a charm, thank you very much 
here is latest progress for anyone who may face such issue https://github.com/McSim182/ag-grid-jest/tree/fix/custom-resolver

**Comment by 3vil4aron** [comment]
I have just tried this and it created a new issue "SyntaxError: Unexpected token 'export'".
