### ISSUE TITLE
Columns Tool Panel text doesn't ellipsize when overflowing

### ISSUE THREAD

**Issue by hoovercj** [ag-grid/ag-grid#6829]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
* Navigate to https://run.plnkr.co/preview/cljgw3qg600083n700bvhncsy/
* Make the "Columns" tool panel narrow so the text overflows off the right edge
![image](https://github.com/ag-grid/ag-grid/assets/2957173/68783f82-a7c2-4caa-8cd5-6681b77b0615)

**Expected behavior**
* The text should ellipsize to indicate that there is more text available by making the panel wider OR by hovering the text to see a tooltip
* There is CSS indicating that the text is intended to truncate, but it is not working
<img width="670" alt="image" src="https://github.com/ag-grid/ag-grid/assets/2957173/b04f4fb3-a322-46aa-b8fb-288428acf7c8">

* **AG Grid version:** 30.0.0, React

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51

**Comment by kiril-matev** [comment]
Hi @hoovercj,

You can add a style to truncate the long column names in the columns tool panel.

Please see this here:
https://plnkr.co/edit/ZBKTG91kXk8zZds4?open=main.js
