### ISSUE TITLE
Custom Context Menu opens on right click of empty space in the grid

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#6830]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**

- Right click on the empty space of the grid
https://plnkr.co/edit/gqh28ngSfqoEbHzM?open=index.jsx&preview

**Current behavior**
On right click of empty space of the grid, the custom context menu opens
![customcontext_menu](https://github.com/ag-grid/ag-grid/assets/77911765/807da1a9-673b-45e3-9726-07d536987e23)

**Expected behavior**
The custom context menu should open only on right click of grid cells and not empty space, similar to built-in context menu
![builtin_context_menu](https://github.com/ag-grid/ag-grid/assets/77911765/c78d154e-24e4-469b-9abd-e9f0d9317c5c)

**Please tell us about your environment:**
Windows

* **AG Grid version:** X.X.X
30.0.2

* **Browser:**
Any browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React + TypeScript

**Comment by kiril-matev** [comment]
Hello @melon2504,

This is expected behavior and not a bug.

If you'd like to show the default browser context menu when clicking the empty area below the grid rows, you need to return null in the **getContextMenuItems** callback.

See this shown here:
https://plnkr.co/edit/CM12J1Jgf4U9k6BA?open=index.jsx
