### ISSUE TITLE
[component] new props for renderers: loadingRenderer and innerRenderer (for groups)

### ISSUE THREAD

**Issue by gabrielenosso** [ag-grid/ag-grid#684]
Could it be possible to add a options like loadingRenderer and innerRenderer that would work like cellRenderer but respectively for the loading template and group rows?
(using the reactCellRendererFactory() method or a similar one)

**Comment by ceolter** [comment]
fair point. will add to list.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-105

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
