### ISSUE TITLE
agGridReact shared interfaces not exported 

### ISSUE THREAD

**Issue by morenyang** [ag-grid/ag-grid#6840]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When I import `AgGridReactProps` in `ag-grid-react`, an error occurred with description `TS2724: '"ag-grid-react"' has no exported member named 'AgGridReactProps'.`

```ts
import { AgGridReact, AgGridReactProps } from 'ag-grid-react';
```
I noticed that you added the export in commit https://github.com/ag-grid/ag-grid/commit/a9607fc2a6c2560d70773a54e8f0005c80a9b22e, but it seems like it hasn't been applied to the production build.

https://cdn.jsdelivr.net/npm/ag-grid-react@30.0.3/lib/main.d.ts
![image](https://github.com/ag-grid/ag-grid/assets/15653996/bdb20c05-368a-47d2-a7c2-fe2f9f159b90)

**Expected behavior**
I can import shared interfaces in `ag-grid-react`. 

**Please tell us about your environment:**

* **AG Grid version:** 30.0.3

* **Language:** typescript 4.9.5

**Comment by seanlandsman** [comment]
I'll issue a patch for this - thanks for reporting it
