### ISSUE TITLE
Documentation for 'virtualRowData'

### ISSUE THREAD

**Issue by Legenden84** [ag-grid/ag-grid#6844]
Hello,

I had trouble finding the equivalent for 'virtual-row-indices' in dash_table. It turns out that there is a property called 'virtualRowData' in AgGrid. Could you please highlight this property with an example in the documentation (in addition to the other examples)?

**Comment by StephenCooper** [comment]
Hi @Legenden84,

We at AG Grid are not responsible for the Dash AG Grid documentation. Please raise your request against https://github.com/plotly/dash-ag-grid/issues. 

Thanks!
