### ISSUE TITLE
ColDef 'tooltipComponent' Not Invoking 'agInit' of my Custom ToolTip Component

### ISSUE THREAD

**Issue by wahmd** [ag-grid/ag-grid#6858]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I've a ag-grid rendering totally fine with all cols and rowData. 
Now, I'm trying to use custom tooltip in ag-grid from [docs](https://www.ag-grid.com/javascript-data-grid/component-tooltip/#example-custom-tooltip)

Steps I've done: 
- added `tooltipField: 'description', tooltipComponent: TooltipCellRendererComponent` in `colDefs`
- created a new component `TooltipCellRendererComponent`.
- **exported it as declaration in ngModule of component.**

**Current behavior**

There's a `agInit` Method inside my `TooltipCellRendererComponent` which should be invoked when my screen refreshes or I hover over `description` column in my grid. However, the `agInit` is not being invoke(I've added a console inside) and I'm seeing native brower tooltip because of `tooltipField: 'description',`
![image](https://github.com/ag-grid/ag-grid/assets/74547936/2b488a79-7400-4e53-9e2c-ca6be9dd7ec0)

**Expected behavior**

   `agInit` inside `TooltipCellRendererComponent should be invoked, browser console should show logs and custom tooltip should be rendered instead of brower native one. 

**Component where I want to use:**
```
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { TooltipCellRendererComponent } from '@app/data-grid/cell-renderers';
import { ColDef } from 'ag-grid-community';
import { Subscription } from 'rxjs';

@Component({
    selector: 'XXXXXXXXXXXXXXXXX',
    templateUrl: './XXXXXXXXXXXXXXXXX',
    styleUrls: ['./XXXXXXXXXXXXXXXXX'],
})
export class XXXXXXXXXXXXXXXXXComponent {
    therapyMinutesCols: ColDef[] = [
        { field: 'no', headerName: 'No.', suppressMovable: true, width: 50 },
        {
            field: 'code',
            headerName: 'Code',
            suppressMovable: true,
            width: 90,
        },
        {
            field: 'description',
            headerName: 'Description',
            suppressMovable: true,
            tooltipField: 'description',
            tooltipComponent: TooltipCellRendererComponent,
        },
    ];

}
```

**My Custom tooltip component:** 
```
import { Component } from '@angular/core';
import { ITooltipAngularComp } from 'ag-grid-angular';
import { ITooltipParams } from 'ag-grid-community';

@Component({
    selector: 'app-tooltip-cell-renderer',
    templateUrl: './tooltip-cell-renderer.component.html',
    styleUrls: ['./tooltip-cell-renderer.component.scss'],
})
export class TooltipCellRendererComponent implements ITooltipAngularComp {
    private params!: ITooltipParams;
    public data!: any;
    public color!: string;

    constructor() {
        console.log('TooltipCellRendererComponent constructor');
    }

    agInit(params: ITooltipParams): void {
        console.log('invoked??', params);
        this.params = params;

        this.data = params.api!.getDisplayedRowAtIndex(params.rowIndex!)!.data;
        console.log('this.data: ', this.data);
    }
}

```

**Please tell us about your environment:**

windows 11, visual studio

* **AG Grid version:** X.X.X

I had 
- ag-grid-angular 27.2.0
- ag-grid-community 27.2.0

so, I upgraded my version to 30.0.3, but same issue. (had to do global style upgrading from [docs](https://www.ag-grid.com/angular-data-grid/global-style-upgrading-to-v28-sass/))

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS, angular 13

Please let me know if you see anything missing because from the [docs](https://www.ag-grid.com/angular-data-grid/component-tooltip/#example-custom-tooltip), it's looks alright.

**Comment by StephenCooper** [comment]
HI @wahmd,

I am not sure why this is the case in your app as it does work in our example. There is not obviously wrong in your code snippet.

https://plnkr.co/edit/3HG1iw3OaJZ9GyrP?open=app%2Fapp.component.ts

Without a reproduction there is not much more we can suggest.

**Comment by zoheil-ag** [comment]
Hi @wahmd,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
