### ISSUE TITLE
Angular ag-Grid : 30.0.2 : Clipboard :: Unable to paste data using [ Ctrl + V ] in cell when user tries for the first time.

### ISSUE THREAD

**Issue by yogeshpaisodeGL** [ag-grid/ag-grid#6861]
Hello Team,

Recently we upgraded to v30.0.2 from v28 and found that if we copy multiple cell data using ( Ctrl + V ) and if we try to paste it in another cell using ( Ctrl + V ) then it will not paste anything. If we click the cell again and then if we try to paste data using ( Ctrl + V ) then it will work. 

We are using ag-Grid v28 on Angular 13.

OS: Windows
Browser: Chrome, Edge

Please refer below step to reproduce the issue:

Here is the plunker for your reference: https://plnkr.co/edit/fpfoTmIzsmjgGFqR?open=app%2Fapp.component.ts&preview

Step 1:  Copy row Data

![image](https://user-images.githubusercontent.com/105768857/202504939-58592eb5-b816-46ce-a4d8-8a27f4527642.png)

Step 2: Single-click in any cell and try to paste copied row data into the cell using ( Ctrl + V ). 
Observation Nothing will paste

![image](https://user-images.githubusercontent.com/105768857/202505835-821dc9e4-44f1-44b8-82a8-cd3aaa89981b.png)

Step 3: Click again on the same cell and try to paste data using ( Ctrl + V ).
Observation: data will be pasted

![image](https://user-images.githubusercontent.com/105768857/202506661-3b35a0d1-aa1e-475d-be59-bdeb90992b8e.png)

Expedition: We want data to be pasted immediately when the user clicks on the cell for the first time.  

`Note: We already tried with https://ag-grid.com/javascript-data-grid/grid-options/#reference-clipboard-suppressClipboardApi`

Please do let us know how we can fix this issue:

Thanks!

**Comment by zoheil-ag** [comment]
Hi yogeshpaisodeGL,

Can you confirm if you are attempting the copy & paste function within the plunker preview? There are some restrictions on the plunker preview (you can see this explained in more detail in the console message when copying).

I am using your plunker and performing the action with the grid **opened in a separate window** and there are no issues.

Kind regards,

**Comment by zoheil-ag** [comment]
Hi @yogeshpaisodeGL,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
