### ISSUE TITLE
Group only rows that have some properties and others keep as single row in ag-grid

### ISSUE THREAD

**Issue by Janitha133** [ag-grid/ag-grid#6876]
I have a rowData like this

[
    {key: income, ...},
    {key: sumIncome, ...},
    {key: cost, ...},
    {key: sumCost, ...},
    {key: total, ...},
]
Here, I need to only group that has keys as income and cost. other rows should keep as single rows in that position.

for now, I use groupRemoveSingleChildren: true, property in the grid option and it is working only below the object array.

[
    {key: income, ...},
    {key: income, ...},
    {key: sumIncome, ...},
    {key: cost, ...},
    {key: cost, ...},
    {key: sumCost, ...},
    {key: total, ...},
]
So when I have one value for income and cost like the first array object, I can't get the behavior that I want. Any solution for this?

**Comment by AG-Zoheil** [comment]
Hi @Janitha133,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
