### ISSUE TITLE
AgGrid React adds watermark effect when exporting Excel 

### ISSUE THREAD

**Issue by Sy-sz** [ag-grid/ag-grid#6883]
AgGrid React adds watermark effect when exporting Excel 

Please tell us about your environment:
Windows 10, Visual Studio Code, npm

AG Grid version: 30.0.0

Browser:
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

Language: [all | TypeScript 4.5.5 | ES6/7 | ES5]

**Comment by zoheil-ag** [comment]
Hi @Sy-sz,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them. If you are on the community version of our grid, this would be why a watermark is getting added to your export.

You can read about getting started with both community or enterprise versions of our grid on [this page](https://ag-grid.com/javascript-data-grid/getting-started/). Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

Do let us know if you have any other questions.

Kind regards,

**Comment by zoheil-ag** [comment]
Hi @Sy-sz,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If my comment above clarified and solved the issue for you, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
