### ISSUE TITLE
Error evaluating function `min`: Cannot read properties of undefined (reading 'context')

### ISSUE THREAD

**Issue by NaveenkumarMD** [ag-grid/ag-grid#6884]
**I'm submitting a bug Report**

Error while importing ag -grid css file
``` js
import 'ag-grid-community/styles/ag-grid.css
```
**Error**
```
ERROR in ./node_modules/ag-grid-community/styles/ag-grid.css (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./node_modules/ag-grid-community/styles/ag-grid.css)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):


  --ag-internal-padded-row-height: calc(var(--ag-row-height) - var(--ag-row-border-width));
  height: min(var(--ag-internal-calculated-line-height), var(--ag-internal-padded-row-height));
        ^
Error evaluating function `min`: Cannot read properties of undefined (reading 'context')
      Error in /Users/naveenkumarmd/Desktop/my-product/webui/node_modules/ag-grid-community/styles/ag-grid.css (line 2400, column 10)
 @ ./node_modules/ag-grid-community/styles/ag-grid.css 2:26-111
 @ ./src/modules/apps/pages/app-list/components/app-list/data-table/data-table.jsx 10:0-46
 @ ./src/modules/apps/pages/app-list/app-list-page.jsx 19:0-98 196:56-65
 @ ./src/modules/apps/pages/app-list/index.js 1:0-42 1:0-42
 @ ./src/modules/apps/router.jsx 10:0-43 102:13-24
 @ ./src/modules/rootRouter.jsx 4:0-42 16:177-186
 @ ./react-app.js 3:0-48 7:38-48
 @ ./react-start.js 2:0-35 6:103-111
 @ ./index.js 18:0-23
```

**Current behavior**
Module build fails because of this error.    ❌

**Environment**

React version : 18
StrictMode 🔛 :On
node version : 18.14.3

* **AG Grid version:**  
```json
    "ag-grid-community": "^30.0.5",
    "ag-grid-react": "^30.0.5",
```

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** [Typescript]

**Comment by zoheil-ag** [comment]
Hi @NaveenkumarMD,

Thank you for reporting this. With the release of v28 we made some changes to our CSS files. You can read more about it [here](https://www.ag-grid.com/javascript-data-grid/global-style-upgrading-to-v28/).

Have you recently upgraded from an older version of the grid?

Kind regards,
Zoheil

**Comment by NaveenkumarMD** [comment]
Hi @zoheil-ag
We are trying to upgrade from v26 to the latest one

**Comment by NaveenkumarMD** [comment]
@zoheil-ag I have read the documentation for upgrading to the latest version.It just demands to change the import path.
And another thing to note is : we are using webpack 5.0

**Comment by NaveenkumarMD** [comment]
Thanks for your response @zoheil-ag . Closing this as the error occur due to a outdated package "less". After upgrading it to the latest version solves the issue.
