### ISSUE TITLE
ProcessCellForClipboard not working ag-grid Vue

### ISSUE THREAD

**Issue by destradafilm** [ag-grid/ag-grid#6886]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
PLUNKER:
https://plnkr.co/edit/jLUx6gAJXlcPnlMT?preview

**Current behavior**
the event is not triggered when you copy cell value to clipboard

**Expected behavior**
processCellForClipboard event should be called

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
    "@ag-grid-community/core": "^30.0.2",
    "@ag-grid-community/styles": "^30.0.2",
    "@ag-grid-community/vue": "^30.0.2",
    "@ag-grid-enterprise/menu": "^30.0.2",
    "@ag-grid-enterprise/row-grouping": "^30.0.2",
    "@ag-grid-enterprise/server-side-row-model": "^30.0.2",
    "@ag-grid-enterprise/range-selection": "^30.0.2",
    "@ag-grid-enterprise/clipboard": "^30.0.2",

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

**Comment by zoheil-ag** [comment]
Hi @destradafilm,

Thank you for getting in touch. We have managed to get the plunker working by making some small adjustments.
Please have a look here and see if this works for you: https://plnkr.co/edit/GyzsLUA1ll5jOeWq?preview

Kind regards,
Zoheil

**Comment by destradafilm** [comment]
@zoheil-ag  thank you so much! I guess I overlooked that it was a prop and not an event. I looked everywhere for an example online and in the docs but couldn't find one. I appreciate it!
