### ISSUE TITLE
Make ag-grid compatible with Trusted Types

### ISSUE THREAD

**Issue by rszczypka** [ag-grid/ag-grid#6888]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
There is a new browser API called Trusted Types that is meant to address common problems with preventing XSS attacks. You can read more about it https://github.com/w3c/trusted-types/wiki/FAQ

When ag-grid is used in an environment that enforces [Trusted Types](https://web.dev/trusted-types/), ag-grid raises Trusted Types violations due to its use of  `innerHTML` and other sinks that Trusted Types are meant to protect.

Here is a list of projects that have already started working on compatibility with Trusted Types: https://github.com/w3c/trusted-types/wiki/Integrations

**Current behavior**
`gridOptions.api.setColumnDefs`, `gridOptions.api.setDatasource` throws `This document requires 'TrustedHTML' assignment.` errors

**Expected behavior**
ag-grid apis are compatible with Trusted Types

**Comment by zoheil-ag** [comment]
Hello @rszczypka,

Thank you for the suggestion.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
**AG-8942 [Compatibility] Allow AG-Grid to be compatible with Trust Types API**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
