### ISSUE TITLE
"ag-grid-community.auto.esm.js:17269 AG Grid: Cannot select node until node id is known." when wanting to select row automatically

### ISSUE THREAD

**Issue by Lautaro-Aguilar** [ag-grid/ag-grid#6889]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I am making an ABM that obtains data from an API, my goal is to make it so that when the user returns from a section/page, the row that I previously selected to go to that page is automatically selected again (I am doing it with the id of the row saving it in the url).
The problem that is happening is that once I have all the rows loaded, I get the row id through the URL, I get the row that matches that id, when I want to select it with row.setSelected() it throws me the following error.
"ag-grid-community.auto.esm.js:17269 AG Grid: Cannot select node until node id is known."

**Expected behavior**
I want that once it gets the row that matches the id, it automatically selects it and goes to it using the infinite-row model.

**Please tell us about your environment:**
Windows 11
Visual Studio Code
YARN
localhost
React

* **AG Grid version:** ag-grid-react [29.2.0]

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** [JS | React | ES6/7 | ES5]

**Comment by zoheil-ag** [comment]
Hi @Lautaro-Aguilar,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by zoheil-ag** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for AG Grid or the wider community to support.

Kind regards,
Zoheil
