### ISSUE TITLE
How can I tell when the grid is done re-rendering to autosize columns?

### ISSUE THREAD

**Issue by SamReznikov** [ag-grid/ag-grid#6895]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

I am trying to automatically resize my columns to fit their contents using an autoSizeAll function I wrote. I want this to happen every time the grid's data is done rendering. This is because the user can click a 'get data' button that re-populates the grid with different data at any point in time. By this, I mean that a completely new grid can be rendered - new columns, new rows, new data, etc.

![image](https://github.com/ag-grid/ag-grid/assets/19536131/1d1a7e1b-86d8-4e0c-b30d-c753949bd5de)

**How can I know when the grid is done rendering?** From the research I've done so far, there is surprisingly no direct way to know, but perhaps there is a workaround I can use?

It's a really simple issue of calling my autosize function too early, resulting in weird/no column autosizing. 

I have tried...

- onGridReady event: triggers once when grid is initialized (might not even have data in it at this point)
- onFirstDataRendered event: works perfectly but only the first time the grid is rendered
- onDisplayedColumnsChanged event: updates constantly, even when the user simply scrolls horizontally, thus slowing the app down too much
- onRowDataUpdated event: it seems this event fires after the row data changes but _before_ the grid is done rendering, so calling autoSizeAll() on this event results in weird / no column autosizing
- useEffect with dependency on rowData+columnDefs: this has the same effect as onRowDataUpdated
- Using a setTimeout(): combining this with either of the two previous attempts works and is the closest thing to a solution I have gotten so far, but setting an arbitrary timeout is of course an unreliable solution. I don't feel comfortable depending on it to always work in my app.

```
// Resize columns when grid data changes
    useEffect(() => {
        if (rowData && rowData.length > 0)
            setTimeout(() => autoSizeAll(), 1)
    }, [rowData, columnDefs, autoSizeAll])
```

Here is my autosize function:

```
const autoSizeAll = useCallback(() => {
    const allColumnIds = [];
        gridRef.current.columnApi.getColumns().forEach((column) => {
            allColumnIds.push(column.colId);
        });
    
        gridRef.current.columnApi.autoSizeColumns(allColumnIds);

}, []);
```

I would really appreciate some help! I have been struggling with this simple issue for the longest time, I would not have expected automatic column autosizing to be this complicated haha.

**Comment by mc-paula** [comment]
After updating to version 30.0.5 (mind the minor version!) this works again in my code with onRowDataUpdated. Which version of ag-grid did you use?

**Comment by daric81** [comment]
We are having the same frustrations trying to autosize columns and also to use the api to set the selected row after we change row data state.  
@SamReznikov Did you try version 30.0.5? Can you confirm if this solves the issue.

We have a timeout at the moment and are not happy with that approach. Definitely feels like a bug or deficiency.

**Comment by StephenCooper** [comment]
Hi @fcaballero,

I have taken a look at your reproduction, and can isolate the issue being that  `rowData` is being provided to the grid before the column defs. 

I have made changes to the code example above to remove the `useEffect` based off rowData and instead just calculate the columns and set row data at the same time. With these changes the autoSize works as expected.

https://plnkr.co/edit/wCJ31VlXiFEGuL8T?open=index.tsx

With this change the `firstDataRendered` will match when the columns are rendered and not just the rows. We currently fire `firstDataRendered` when row components are rendered. If this is before the columns have been provided then auto sizing based off that event will not work.

There is potentially a new event that we might be able to add to address these types of cases in a more consistent approach especially when it comes to automatically resizing following data / column changes.
