### ISSUE TITLE
applyColumnState doesn't always work on gridReady for vue sdk

### ISSUE THREAD

**Issue by sk-tjdownes** [ag-grid/ag-grid#6902]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => see 'Providing a Reproducible Scenario'

**Requesting Community Support**
Please note, this is a duplicate of [6807](https://github.com/ag-grid/ag-grid/issues/6807). That was closed as fixed with the release of 30.0.5, but has not been fixed as can be shown using the sandbox below

**Providing a Reproducible Scenario**
https://codesandbox.io/s/aggrid-vue-applycolumnstate-rxxrvp?file=/src/App.vue:1747-1748

**Current behavior**
When applying column state, AG Grid will not apply the state on gridready. Instead, I have to use a setTimeout to wait ~1.5 seconds to apply the column settings.

**Expected behavior**
As per the docs, this should happen on gridready

**Please tell us about your environment:**
- Any OS including Windows 11 Pro 10.0.22621Build 22621
- Any browser including Chrome Version 114.0.5735.134 (Official Build) (64-bit)
- Vue 3.3.4
- Vite 4.3.9
- Node 18.x

**AG Grid version:** 30.0.5

**Language:** ES6/7

**Comment by sk-tjdownes** [comment]
Plunker doesn't seem to compile .vue files, so it seems I cannot create the example using plunker. I tried the sandbox this morning and it worked fine after a refresh, so maybe try that. I think it may be important in this case to use `<script setup>` to properly replicate the issue

**Comment by zoheil-ag** [comment]
Thanks @sk-tjdownes,

I have now raised this in our backlog with the following reference and name: **AG-8979 [Column State] When using Vue applyColumnState doesn't work**.

Somebody from our team will investigate this in more detail and we will get back to you.

Kind regards,
Zoheil

**Comment by nzscripps** [comment]
Following since we are also having issues with applyColumnState in v30.x

Rolling back to v29.3.5 resolved the issue; however, upgrading would be preferred.

**Comment by jwcaulfield** [comment]
Getting the same issue with version 31.1.1.  We're calling applyColumnState after the onGridReady event fires and find the columns end up in a weird state where some columns headers are missing and others stretch over the missing column header, spanning multiple columns.  If we wrap the call in a setTimeout then it works, but not ideal.  This was working fine in version 31.0.2 (well except for the bug about column widths not being applied, which is the reason we're upgrading).  Any ETA on the fix?

**Comment by AG-Zoheil** [comment]
Hi all,

We are looking to replicate this behaviour, however are unable to do so (and the codesandbox linked above does not work for us). If you are able to provide a reproducible scenario for us we'd be keen to look into this to try and include this in one of our upcoming releases.

Looking forward to hear back.

Kind regards,
Zoheil

**Comment by jwcaulfield** [comment]
Hi Zoheil,

I've managed to write a small React app that reproduces the problem.  Could you send me your email address to jwcaulfield@hotmail.com and I'll email it over to you?  Unfortunately, due to company policy I can't just post it here.

Thanks,

James

**Comment by AG-Zoheil** [comment]
Hi all,

Thanks for the comments.

Thank you @jwcaulfield for providing us with a reproducible scenario.

We've now been able to identify the issue and will work on a fix. Please note this will continue to be logged and tracked under **AG-8978**.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
