### ISSUE TITLE
The useValueFormatterForExport function doesn't work.

### ISSUE THREAD

**Issue by kimeuntae** [ag-grid/ag-grid#6903]
The useValueFormatterForExport function doesn't work.

=>https://www.ag-grid.com/vue-data-grid/value-formatters/#use-value-formatter-for-export

**Comment by xandoletti** [comment]
i encountered the same problem with AG-GRID 30.0.5 and on the Example Docu Page (linked above), just only for Excel Export. CSV Export and Clipboard Copy&Paste seems to work fine.

**Comment by zoheil-ag** [comment]
Thanks for reporting this @kimeuntae and @xandoletti.

I assume you are referencing the fact that the currency format is not exported when exporting via Excel.
This is explained just below the example in the bulleted list of conditions that are exemptions to the `useValueFormatterForExport` working.

**Note that if any of the following conditions are true, then `useValueFormatterForExport` is ignored for that feature and the value will be either the original value or that set in the custom handler:

- If the underlying value is a number when using Excel export.**

I do agree however that this section of our documentation can be a bit more cleaner and easier to understand so we will work on improving this example and its description.

Thanks again for bringing this up.

Kind regards,
Zoheil

**Comment by zoheil-ag** [comment]
Hello,

I'm hopeful the above explanation has resolved your issue. As we've not heard back in a while, we will be closing this issue.

If however, you are still in need of support feel free to comment or raise a new issue for AG Grid or the wider community to support.

Kind regards,
Zoheil

**Comment by mrcs-tylr** [comment]
In the code example shown in the documentation, the currency formatting is applied in the CSV export, but not the Excel export. Is this expected? I am seeing the same problem in my own implementation. 

I have checked the bulleted list of criteria which would prevent the formatting from being applied and ensured that none of the conditions are causing the problem.
