### ISSUE TITLE
rowIndex is not reactive when I provide getRowId prop

### ISSUE THREAD

**Issue by xhxhxhxh** [ag-grid/ag-grid#6904]
same as issues #5288.
example:
https://plnkr.co/edit/z7IrX2DdHPK2s5JE?open=main.js
I change the vue version from 3.2.29 to 3.2.41, v3.2.29 behaving normally.

**Comment by zoheil-ag** [comment]
Hi @xhxhxhxh,

Thank you for reporting this - much appreciated!

Based on your description we're currently looking to investigate the cause of the issue.

We have added this as an item to our backlog and we are tracking it with the following reference and description:
**AG-8978 Investigate why reactivity appears lost with animations between vue 3.2.37 and 3.2.38**

Thanks again for bringing this up with us.

Kind regards,
Zoheil
