### ISSUE TITLE
Using Vue3 script setup error: Framework component is missing the method getValue()

### ISSUE THREAD

**Issue by sfe-efficy** [ag-grid/ag-grid#6905]
Hi! When we use Vue3 with script setup for renderer cells, the exposed methods are ignored by the VueFrameworkComponentWrapper, when it's invoked the required method "getValue", we got the null value and the warning is displayed in console. 

"AG Grid: Framework component is missing the method getValue()".

Similar issue here https://github.com/ag-grid/ag-grid/issues/3402 but using React.

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Using script setup is exposing the methods in a different place that is waiting from getFrameworkComponentInstance (so, from the proxy generated from Vue3).

![image](https://github.com/ag-grid/ag-grid/assets/95854297/c2c02f92-ea70-4253-ab44-8c90d0f69d46)

But, in vue3 script setup, this information is provided here:

![image](https://github.com/ag-grid/ag-grid/assets/95854297/fdc36527-f5dd-43d2-9499-141e93b22ad1)

So, inside vNode.component, in the property called "exposed". This data is ignored, I guess the method createAndMountComponent should return also the exposed properties if exist, and using this information inside the wrapper to check if exist exposed methods and called it, or using the current method when people use Component API.

* **AG Grid version:** 
* 29.3.5

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

* **Language:**
TypeScript 4.9.5

**Comment by zoheil-ag** [comment]
Hi @sfe-efficy,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by sfe-efficy** [comment]
Hi @zoheil-ag , I was looking for an example using vue components (.vue files with script setup, or at least using Composition API), but I didn't find anything in www.ag-grid.com.

The nearest example is like [this one](https://codesandbox.io/s/ag-grid-vue-3-example-bvwik?file=/src/App.vue).

do you know if exists an example like this one https://plnkr.co/edit/?open=main.js&preview but working with vue components files instead of using pure js?

Our problem happens when we use https://vuejs.org/api/sfc-script-setup.html

Thanks in advances

**Comment by sfe-efficy** [comment]
Morning!
any feedback about this issue?

Regards

**Comment by zoheil-ag** [comment]
Good morning @sfe-efficy,

A few updates on this:

1) The plunker you have linked is actually empty - please remember to fork/save and then send any examples you want to share with us. If you need further help with this please, do let me know

2) We do have an item in our backlog which relates to this with the following reference and name: **AG-8274 Support Custom Vue 3 Components in <script setup>**

I have now linked your issue to that item in our backlog. Please note we will not be updating the Github issue once we release it, but you can see whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page: https://www.ag-grid.com/ag-grid-pipeline/.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-).

Thanks again for raising this with us.

Kind regards,
Zoheil

**Comment by XiaoBaiClassmate** [comment]
In version 31.0.2, the problem still exists.

**Comment by seanlandsman** [comment]
@XiaoBaiClassmate if you're able to provide a reproducible example we'll be happy to take a look at this

**Comment by wyndem** [comment]
```
<template>
  <input type="number" :value="value" @input="onInput" class="doubling-input" ref="inputRef" />
</template>

<script setup>
import { ref, onMounted, nextTick } from "vue";

// 使用 defineProps 来声明 props
const props = defineProps({
  params: Object
});

// 使用 ref 创建响应式的引用
const value = ref(props.params.value);
const inputRef = ref(null);

// 更新 value 值的方法
const onInput = event => {
  value.value = event.target.value;
};

// 编辑器的 getValue 方法
const getValue = () => {
  // 这个简单的编辑器将输入的值翻倍
  return value.value * 2;
};

// 编辑开始前的钩子，可以用来取消编辑
const isCancelBeforeStart = () => {
  return false;
};

// 编辑结束后的钩子，如果返回 true，则忽略编辑结果
const isCancelAfterEnd = () => {
  // 编辑器将拒绝任何大于 1000 的值
  return value.value > 1000;
};

// 暴露给 AG Grid 调用的方法
defineExpose({
  getValue,
  isCancelBeforeStart,
  isCancelAfterEnd
});

// 编辑开始时聚焦到输入框
onMounted(() => {
  nextTick(() => {
    inputRef.value.focus();
  });
});
</script>

```

然后注册这个组件：
```
 cellEditor: jsEditor,
```

把值输入好后，控制台出现警告： Grid: Framework component is missing the method getValue()

**Comment by XiaoBaiClassmate** [comment]
@seanlandsman I apologize for only replying now, I found out that it's not compatible with vite development environments, [such as this one](https://stackoverflow.com/questions/73032489/ag-grid-framework-component-is-missing-the-method-getvalue-in-production-buil). This problem has existed for a long time.

**Comment by joemaylor** [comment]
Just putting this here in case anyone stumbles across this issue.

If you are creating a custom cell editor component, in vue 3, using `<script setup>`, you need to explicitly expose functions like `getValue`, otherwise they won't work.

There's no mention of this in the Ag Grid docs that I could find, but it makes sense reading about `defineExpose` [in Vue 3 docs](https://vuejs.org/api/sfc-script-setup.html#defineexpose).

```vue
<script setup lang="ts">
import type { ICellEditorParams } from 'ag-grid-enterprise'

defineProps<{ params: ICellEditorParams }>()

const getValue = () => 'foo'
defineExpose({ getValue }) // this line
</script>

<template>
...
</template>
```
