### ISSUE TITLE
Version 30 Circular Reference Error When Using ColDef<Type>

### ISSUE THREAD

**Issue by KrazyTako** [ag-grid/ag-grid#6906]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When setting `ColDef<Type>` with a type that has a field of itself, we now get a TypeScript error regarding circular reference, TS2615. The error only seems to occur when defining the `field` property on the ColDef.

```
class Thing {
  name: String;
  thingy: Thing; // Property that references its type
}

const gridColumns: ColDef<Thing>[] = [
  {
    headerName: 'name',
    field: 'name' // Circular error message shows up here. It goes away if the "field" property is removed
  }
];

// TS2615: Type of property 'thingy' circularly references itself in mapped type '{ [TKey in "name" | "thingy"]: (Thing[TKey] extends any ? `${TKey}` : never) | NestedPath ; }'.
```

**Expected behavior**

The generic `ColDef` should allow Types that have properties that reference their own type, such was the case in prior versions of AG Grid.

**Please tell us about your environment:**

* **AG Grid version:** 30.0.5

* **Browser:** N/A - This is a compiler error

* **Language:** TypeScript 4.8+

**Comment by KrazyTako** [comment]
@StephenCooper thanks for the response and linking to that issue.

The provided work around does not seem to work. The same error is shown when using the `Duplicate<Thing>` type.

**Comment by StephenCooper** [comment]
I am looking to support Recursive Types with the following type structure. It limits the level of auto completion provided without restricting how deep you want to go. 

The depth restriction enables the type to support a recursively defined interface. Would appreciate any feedback if this type does not work for your situation. 

The playground below contains the new type setup and some examples that work for recursive types that did not previously work.

[Playground link](https://www.typescriptlang.org/play?ts=4.3.5#code/C4TwDgpgBAIglgczsKBeKBGKAfKAmHKAZkIBZCBWQgNkIHZCAOQgTgG4AoUSKAOQgAeweEhToA2hgA0+GURmkZFGdRl0ZAcgDKAFQDyABQ0BdTt2gBJAHYBjADw6AfGig6og4BCsATAM6xEZCgAfj4PEWRxHWMoAC4obX0jNigucGgtYAAnOCsEPSzeAFcAWwBpCBBfBz0AIwArZ3QAa0qAewAzVzr6qAAyKAAKX2zchEIrUtqILIBKM3SwkYhvAwBDYAALBwA1NYAbIogZAyyIDrgBdyEvPygRnLyZHT3DiH5l7wBhTbh972eMAgYC2TVSUAhrleR2unh8-jaDQgNmAHEh6JCUAABgASADep3OlwAvgA6fGuIEgzaw27+RKGDSYtZWEBxJaebwAMTgEH+6y21ReByOz2h7wgnx+fwBlOBoOJWLRGIh8SsEAAbjNOIIwG0sihzFAvm19kCOjy+d4HDANmsXCyQGKRdB0I6wTpbcB7R46VBHZiPpzLfyNpshV61s63jIMM41ZrtRxdfrDYsgysQ6swxG7Q7WdGYW6C3LqS4AAxgvHKiFRCps3JQTKPfKFUr13PexzGWI1jG4Qaeu11yoxX3wqEuzG4vE6euK9nqrVzPvo3AZ7NbG3DuejmQz3cgRWF45Qaz2T3yzaORycYniZtjArFcqVTtrbucDgcAD0ACo-zRP9XEWYA2n9BA1lyEZwT-H8OFyTwsg6NYbGgE0zXObdvXzJ1JzeXDnGrdELitYJ4gw80s2wqN8KOW8OGJb9EJmFC0LPAAlNoAHdIygYioCsNYSggeIHjGKRlTWBBRMEqYkwhGxfn+eILC43i81wSYSmmLI72-Gw2isGDDP2CjTXNFw8SgUiVI0R0tjGAB9AB1ZBNic3g2icnR0g0JjDOMlBTP8czMI6Ow1J4yNHHEGIJGVASIVs7x4nsmSNGVYlJIhH8f2NFlaR8f1-H2IzxjWfwQDaIooG4lkUETKwoDgLo1iKMCoEMkowH2CBgDgIz7jAsB-G4-VmjGRKUrSpSZVJOb-gW5TvGW+bFtWja1qWratqEkT-I4UxvxTA0WqsJC2MsSN1P4vs4FS4aWxyyERN8XxpNk8Snj7EYNiKXw0rOepkU5JlcA0M49QNFZwYSNYwDALI2i1bwNBkcFIQ2s4rFUm6eLiwgih8Il1W8fTApM01fCwMLzUi-HuNi+KoHERK+xmhJsa8TKIWy6beRUhIHsO47mIu1jUMsdTIywAT9q+0YfohT61XkvTlQ2+Ikq6laFbEpWEE4Pn9I4SngtNPA6fOKybMF1L7NZRy8lc9zPO83zIEO82uupghrYiqKNO9ONCYSiEdc59KIF5qB+YjqPdr14SY6Y0wgA)

**Comment by altso** [comment]
Thank you @StephenCooper.

Just to clarify, it's not only about limiting the level of auto completion provided, but type validation as well. The line below compiles just fine.

```ts
{field: 'child.child.child.child.child.child.child.ANY_FIELD'}
```

Looks good to me otherwise.

**Comment by StephenCooper** [comment]
Yes this is a trade off that we have to make. The only way to get the type checking would be to have the type recurse further but then that runs into limits in Typescript complexity. We do not want to limit the type so allow anything after a certain point. 

I have written more about this here. 

https://dev.to/scooperdev/supporting-circularly-referenced-mapped-types-in-typescript-4825

**Comment by KrazyTako** [comment]
@StephenCooper Great write up. Thank you for looking into this.
