### ISSUE TITLE
启动报错，源码报错（BaseComponentWrapper ）

### ISSUE THREAD

**Issue by Zhang-Chao-Dong** [ag-grid/ag-grid#6907]
[Vue warn]: Error in mounted hook: "TypeError: Class constructor BaseComponentWrapper cannot be invoked without 'new'"

ypeError: Class constructor BaseComponentWrapper cannot be invoked without 'new'

**Comment by zoheil-ag** [comment]
Hi @Zhang-Chao-Dong,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil
