### ISSUE TITLE
Theme customisation is not applied

### ISSUE THREAD

**Issue by ttlage** [ag-grid/ag-grid#6910]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello everyone,

I am new to Ag-Grid and facing some challenges while trying to customise the CSS of tables in my current Angular project. Initially, we were using `ng-deep`, but as we started using more tables, we encountered numerous CSS leaks, as expected.

To address this issue, I explored the [ag-grid-customise-theme](https://github.com/ag-grid/ag-grid-customise-theme) solution, which seemed promising. While I understand that implementing it will require considerable effort, I believe it will provide a long-term solution and eliminate concerns about CSS conflicts. To start, I commented out all the `ng-deep` to avoid any interference.

The documentation and demo indicate that I should be able to use the `style.scss` to call `ag.grid-styles()` and modify some table styles. In the demo project, I can achieve something like this:
```
@include ag.grid-styles(
  (
    theme: custom-angular,
    extend-theme: alpine,

    header-height: 200px,

    odd-row-background-color: red,
    row-border-color: transparent,
    row-hover-color: null,
    checkbox-checked-color: #2661ad,
    range-selection-border-color: #ff00b1,
    range-selection-background-color: #03305633,
    header-foreground-color: pink,
    header-background-color: gray,
    header-cell-hover-background-color: rgb(80, 40, 140),
    header-cell-moving-background-color: rgb(80, 40, 140),
  )
);

.ag-theme-custom-angular .ag-header {
  font-family: cursive;
}

.ag-theme-custom-angular .ag-header-group-cell {
  font-weight: normal;
  font-size: 22px;
}
.ag-theme-custom-angular .ag-header-cell {
  font-size: 18px;
}

.ag-theme-custom-angular .ag-menu-option-active {
  background-color: #2661ad;
  color: white;
}
```
and I can see the changes applied to the table:
<img width="1484" alt="image" src="https://github.com/ag-grid/ag-grid/assets/33501927/1046a2d8-6a29-412e-a37e-0c3e33c9c722">

However, when I try the same approach in my project, it doesn't seem to work. I can add styles to the `styles.scss`, but they do not affect the Ag-Grid theme.

My project works as a micro-frontend, meaning it will be called from other Angular projects, and we call the module for the specific view we want to show. To troubleshoot, I went to the component using the table and tried using `ag.grid-style()` in its `SCSS` file, but the changes didn't have the desired effect:
<img width="1443" alt="image" src="https://github.com/ag-grid/ag-grid/assets/33501927/dfefc0f2-d649-4421-a77c-15709741806d">

It's evident that some of the properties I added in ag.grid-styles (e.g., header-height: 200px) are not being applied to the table. I'm confident that I'm missing something, but I can't figure out what it is.

Additionally, I attempted to create a custom theme from scratch, but unfortunately, I encountered the same problem. Some of the CSS properties don't apply to the table.

My project runs Angular 14 with Ag-Grid version 28.1.1. I'd love to provide a Plunker to replicate the scenario, but I'm unable to do it.

If anyone could assist me in resolving this issue or provide insights into what I might be doing wrong, I would greatly appreciate it. Thank you!

**UPDATE**:
We've identified the problem! Since we are using micro-frontends and a shell that aggregates all of them, the shell's configurations take precedence over those of the micro-frontends. As a result, the 'style.scss' file considered is the one from the shell.

We can see the changes applied to the table if we do everything within the shell in the 'styles.scss' file. Now, I need to figure out how to import the ag-grid theme classes into my micro-frontend and make it use them.

**Comment by AG-Zoheil** [comment]
Hi @ttlage,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
