### ISSUE TITLE
When data overflows, obtain complete values by hovering the mouse

### ISSUE THREAD

**Issue by XiaoPengYouzzZ** [ag-grid/ag-grid#6918]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hello,I am using a ag-grid with "ag-grid-vue": "^30.0.5".

I want to achieve the following effect: If a cell's data overflows, I can use the hovering mouse to obtain its complete value. I tried using tooltipField in columnDefs, but I found that this method can lead to the following situation: if the data in the cell does not overflow, its complete value will still be displayed when the mouse hovers over it.

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by xzhdev** [comment]
Is there any good way to implement it? @XiaoPengYouzzZ

**Comment by XiaoPengYouzzZ** [comment]
@xzhdev 没有，我的单元格数据不会很多，最多不会超过5行，所以我让它全量展示了。
