### ISSUE TITLE
 "[object Object]" Displayed for 0 Value when using dataTypeDefinitions and inferring cell data type as object

### ISSUE THREAD

**Issue by Heriannan** [ag-grid/ag-grid#6921]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I would like to use the object as the cell data type and provide custom cell data types using `dataTypeDefinitions`. The cell is rendered as `[object Object]` when the value is 0, but if the value is a positive or negative number like `1` or `-1`, the cell will render properly.
![image](https://github.com/ag-grid/ag-grid/assets/64848508/9203b9b1-d1e7-4c09-a913-dcd00575e8a9)

Reproducible scenario: https://plnkr.co/edit/suuMm3pamYtdQsGJ?open=index.tsx

**Expected behavior**
Cell would be able to show 0, instead of `[object Object]`

**Please tell us about your environment:**

* **AG Grid version:** 30.0.6

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

* **Language:** React

**Comment by zoheil-ag** [comment]
Hi @Heriannan,

Thank you for raising this.

We've had a look and this is not a bug but related to the `dataTypeMatcher` you've defined.

You have written it as `!!value.countryCode` which means if `countryCode` is 0, this evaluates to false. We've changed it to `value.countryCode != null` instead. See it working here: https://plnkr.co/edit/TClf2j3yH1BOo3nV?open=index.tsx&preview.

I'm hoping this resolves your issue.

Kind regards,
Zoheil

**Comment by Heriannan** [comment]
The solution works. Thank you for promptly investigating and resolving the issue.
