### ISSUE TITLE
Styling Cells under column grouping

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#6928]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://run.plnkr.co/preview/clkuxqokc0006356xn6wu922g/

**Current behavior**
Is there any way to style **only** the cells under the column grouping
E.g. I have to achieve the following of adding **borders(red colored)** to the section of cells under column grouping inorder for a better separation visibility:

![image](https://github.com/ag-grid/ag-grid/assets/77911765/2876f0e0-dbe1-4606-84ac-a0500a59262e)

I could find a partially working solution from here https://stackoverflow.com/questions/51267006/how-to-style-column-groups
But styles wont be applicable once we reorder/move the columns within the group or when we collapse the group.
And lets say on either of the event(onColumnMoved or onColumnGroupOpened) we reapply the style (checking if its first column for border-left & last column for border-right) and update the column definition but this doesnt seem efficient since we are re rendering the columns & associated cells every time.

**Expected behavior**
Maybe a property on ColumnGroup which allows to style the whole section of cells and achieve the one posted as screenshot, or an efficient approach to make sure the first & last column of the group always has the border(regardless its expanded/collapsed and reordered)

* **AG Grid version:** X.X.X
30.0.6

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React + TypeScript

**Comment by zoheil-ag** [comment]
Hello @melon2504,

Thank you for the suggestion.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
**AG-2949 [Layout & Styling] Allow displaying uninterrupted vertical lines between columns across the entire grid height**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
