### ISSUE TITLE
Ag-Grid will create errors for Solid server-side-render 

### ISSUE THREAD

**Issue by xarthurx** [ag-grid/ag-grid#6929]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The bug has been fully documented (test repo attached), and replied by the solidjs developers. To fix the issue, it need some modification on the ag-grid source code side.

https://github.com/solidjs/solid/issues/1839#issuecomment-1664767115

**Comment by seanlandsman** [comment]
Unfortunately we (AG Grid) do not support SSR - we rely on certain browser specific elements to be present for the grid to function.

As per the linked issue you'll either have to disable SSR or only render the grid on the client side
