### ISSUE TITLE
AgGrid get params for cellEditorParams from async function

### ISSUE THREAD

**Issue by goldpvlv** [ag-grid/ag-grid#6932]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have a problem with the CellEditorSelector. When I call the cell editing mode, I need to call the cell renderer with the new parameters. I want to get some parameters from an async function. I try to do it, but there is no "values" in the parameters.

**Expected behavior**
I want to get the result of executing my asynchronous function getData in the DoublingEditor class in props.values

https://plnkr.co/edit/OAnhLwey0r7BDmBv?preview

**Please tell us about your environment:**
React, javascript

* **AG Grid version:** 30.0.6

* **Browser:** Google Chrome

**Comment by zoheil-ag** [comment]
Hi @goldpvlv,

Thank you for raising this issue.

Can you please clarify the following a bit further:

What are you trying to achieve with the async call? Are you trying to get a list of values to select from like in a drop down for example? 

Looking forward to hearing from you.

Kind regards,
Zoheil

**Comment by goldpvlv** [comment]
> Hi @goldpvlv,
> 
> Thank you for raising this issue.
> 
> Can you please clarify the following a bit further:
> 
> What are you trying to achieve with the async call? Are you trying to get a list of values to select from like in a drop down for example?
> 
> Looking forward to hearing from you.
> 
> Kind regards, Zoheil

Yes, I'm trying to get an object for my custom dropdown list. the async getData function creates this object, which I want to pass to cellEditorRenderer

**Comment by zoheil-ag** [comment]
Great, thank you for the clarification @goldpvlv.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we already have feature request for this.

We have this requirement in our backlog and we are tracking it with the following reference: **AG-2655**.

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
