### ISSUE TITLE
issue for updating detailCellRendererParams

### ISSUE THREAD

**Issue by amirakbr** [ag-grid/ag-grid#6936]
there is an issue with updating detailCellRendererParams with transaction api , 
if you are using detailCellRendererParams as detail table and u you want update it using transaction update method in ag-grid api 
it will not update and to see new data you have to collapse detail table and then open it again .

**Comment by zoheil-ag** [comment]
Hi @amirakbr,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by amirakbr** [comment]
Thank you so much for responding to me about the issue and I am sorry for
yesterday's issue that was a mistake and I completely forgot to remove that
. i will send you a live plunker demo to see the problem .
