### ISSUE TITLE
Clipboard example in documentation

### ISSUE THREAD

**Issue by aboveyunhai** [ag-grid/ag-grid#6938]
I read through the issue instruction but none of them fits my question, so I remove them all.

My question is regarding the official clipboard example for add new row into the bottom of table
Link: https://www.ag-grid.com/react-data-grid/clipboard/#pasting-new-rows-at-the-bottom-of-the-grid

the questionable function is copy paste from that official example, (Javascript, React, Vue, Angular are all using the same logic fwiw)

First, the code itself is working, but the few lines of code inside the for loop makes no sense, I just suspect the example would break somewhere else or there are some internal mechanism user don't know that causes the code working.

I added my comments here to those troublesome lines, all the questions are inside the add-new-row for loop. Everything else is exactly the same from the example.

```ts
 const processDataFromClipboard = useCallback(
    (params: ProcessDataFromClipboardParams): string[][] | null => {
      const data = [...params.data];

      const emptyLastRow =
        data[data.length - 1][0] === '' && data[data.length - 1].length === 1;
      if (emptyLastRow) {
        data.splice(data.length - 1, 1);
      }

      const lastIndex = gridRef.current!.api.getModel().getRowCount() - 1;
      const focusedCell = gridRef.current!.api.getFocusedCell();
      const focusedIndex = focusedCell!.rowIndex;

      if (focusedIndex + data.length - 1 > lastIndex) {
        const resultLastIndex = focusedIndex + (data.length - 1);
        const numRowsToAdd = resultLastIndex - lastIndex;
        const rowsToAdd: any[] = [];
   //>>>>>> everything above looks correct.

        for (let i = 0; i < numRowsToAdd; i++) { 
   //>>>>>> for loop here, I realized "i" is not using anywhere 
   //>>>>>> index is the same during each iteration
          const index = data.length - 1;
   //>>>>>> since slice() don't modify the data, "row" is the same during each iteration
   //>>>>>> always the last element of data
          const row = data.slice(index, index + 1)[0];

          // Create row object
          const rowObject: any = {};
          let currentColumn: any = focusedCell!.column;
          row.forEach((item) => {
            if (!currentColumn) {
              return;
            }
            rowObject[currentColumn.colDef.field] = item;
            currentColumn = gridRef.current!.columnApi.getDisplayedColAfter(
              currentColumn
            );
          });
  // >>>>>> after the for loop, each rowObject is different?
          rowsToAdd.push(rowObject);
        }
        gridRef.current!.api.applyTransaction({ add: rowsToAdd });
      }
      return data;
    },
    []
  );
```
I also extract all my comments out for better readability
```ts
// for loop here, I realized "i" is not using anywhere 
// index is the same during each iteration
// since slice() don't modify the data, "row" is the same during each iteration, always the last element of data
// after the for loop, each rowObject is different?
```
To further testing my doubt, I move the `index` and `row` outside of the for loop, it's working weirdly without duplicating the same last row
```ts

    const index = data.length - 1; 
    const row = data.slice(index, index + 1)[0]; 
    for (let i = 0; i < numRowsToAdd; i++) {  // same logic without the index and row inside }
```

At the end, I just remove those questionable lines and change it to the expected one, but I still don't understand why the original one is working.
that's my modification, this guarantees we grab the correct row during each iteration with `i`.
```diff
+ const startIdx = data.length - numRowsToAdd;
for (let i = 0; i < numRowsToAdd; i++) {
- const index = data.length - 1;
- const row = data.slice(index, index + 1)[0]; 
+const row = data[startIdx + i];
  // same logic below
 }

```

I highly suspect there are some concurrency issues in the worse case.

**Comment by zoheil-ag** [comment]
Hi @aboveyunhai,

Thank you for your input and suggestions. The code in some of our examples has not been optimised to work ideally on all occasions. At times it is just an attempt to showcase a certain part of the grid working.

We welcome any superior applications of the code in our users' own prejects.

We do have a longer-term plan of reviewing and optimising a lot of our examples, so once again thank you for bringing this to our attention.

Kind regards,
Zoheil
