### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by grantdaigh** [ag-grid/ag-grid#6942]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
run 'npx jest' with    
 "@ag-grid-community/client-side-row-model": "^30.0.6",
 "@ag-grid-community/core": "^30.0.6",
 "@ag-grid-community/styles": "^30.0.6",

● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.      

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:\repo\project\node_modules\@ag-grid-community\core\dist\esm\es6\main.mjs:15
    export { ColumnFactory } from "./columns/columnFactory.mjs";
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       5 |
       6 | import * as vscode from 'vscode';
    >  7 | import { GridOptions, Grid } from "@ag-grid-community/core";
         | ^

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1496:14)
      at Object.<anonymous> (src/test/unit/GridUtils.test.ts:7:1)

**Jest.config.js**

module.exports = {
  "transform": {
    '^.+\\.(ts|tsx|js|jsx|mjs)$': ['ts-jest',
    {
      diagnostics: false,
    },
   ],
  },
  transformIgnorePatterns: [
    '/node_modules/(?!(@ag-grid-community|@ag-grid-enterprise|ag-grid-react|ag-grid-enterprise|ag-grid-community)/)',
  ],
  testEnvironment: 'node',
  testRegex: '/src/test/unit/.*\\.(test|spec)?\\.(ts|tsx)$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node', 'mjs'],
  reporters: [
    'default',
    ['jest-junit', { outputName: 'unit-test-results.xml' }],
  ],
};

**Current behavior**
Fail to run jest unit 

**Expected behavior**
Error is not thrown, and component functionality works as indended.

**Please tell us about your environment:**

Windows 10, VSCode, NPM

* **AG Grid version:** X.X.X
30.0.6

* **Browser:**
VsCode WebWiew/IFrame

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript:5.1.6
ES6

**Comment by zoheil-ag** [comment]
Hi @grantdaigh,

Thank you for raising this.

It seems like you are using AG-Grid modules as opposed to packages. Please have a look at this [blog post](https://blog.ag-grid.com/ag-grid-es-modules-and-commonjs/) that explains the challenges encountered with ES6 Modules and testing tools and our solution that gives the user the choice of approach.

Do let us know if there are any further issues.

Kind regards,
Zoheil

**Comment by urbanfly** [comment]
@zoheil-ag The blog post linked above directs us to "the Testing section" if we want to continue using Modules. The steps on that testing page have been followed.

> Please refer to the [Testing](https://www.ag-grid.com/javascript-data-grid/testing?ref=blog.ag-grid.com) section of the documentation for more information about potential configuration changes required.

Is there any way to resolve this or must we switch to package references in order to use Jest?

(I work with the issue author)

**Comment by zoheil-ag** [comment]
Hi @grantdaigh and @urbanfly,

Thanks for clarifying that you've already followed the steps outlined in our documentation. Please allow us some time to look into this.

Kind regards,
Zoheil

**Comment by zoheil-ag** [comment]
Hello,

We've had a look at Jest with the configurations displayed on our documentation and there should be no issues. Can you please provide a mini-repo for us to be able to reproduce this? Please create a small self-contained sample (e.g. Github or zipfile) with the minimum amount of code needed to highlight the issue.

Once we have that we can look into this further.

Thank you,
Zoheil

**Comment by seanlandsman** [comment]
Please take a look at the answer here - does this help?  https://github.com/ag-grid/ag-grid/issues/6766#issuecomment-1678603954

**Comment by grantdaigh** [comment]
Hi Zoheil, Please see the attached sample project.
Thanks.
[SampleGridApp.zip](https://github.com/ag-grid/ag-grid/files/12374707/SampleGridApp.zip)

**Comment by seanlandsman** [comment]
Again - this should help: https://github.com/ag-grid/ag-grid/issues/6766#issuecomment-1678603954

**Comment by seanlandsman** [comment]
Please remove the `transformIgnorePatterns` - it isn't necessary with the custom resolver

**Comment by grantdaigh** [comment]
> Please remove the `transformIgnorePatterns` - it isn't necessary with the custom resolver

After removing the `transformIgnorePatterns`, it still yields the same error.

Thank you.

**Comment by leandertolksdorf** [comment]
@seanlandsman This issue is not resolved and it's blocking us from updating AGGrid to v30. Would there be a chance of further looking into it?

@grantdaigh Did you meanwhile have any success fixing this?

**Comment by seanlandsman** [comment]
@grantdaigh @leandertolksdorf 

Can you please try the following:

`jest.config.js`:

```
module.exports = {
    "transform": {
        "^.+\\.(ts|tsx|js|jsx|mjs)$": [
            "ts-jest"
        ]
    },
    resolver: '<rootDir>/myResolver.ts'
}
```

`myResolver.ts`:

```
const frameworks = ['angular', 'react', 'vue', 'vue3'];

module.exports = (request, options) => {
    return options.defaultResolver(request, {
        ...options,
        packageFilter: pkg => {
            const packageName = pkg.name;
            const agDependency = packageName.startsWith("@ag-grid") && !frameworks.some(framework => packageName.includes(framework));
            return {
                ...pkg,
                // default to use the CommonJS ES5 entry point for Jest testing with AG Grid
                main: agDependency ? './dist/cjs/es5/main.js' : pkg.module || pkg.main,
            };
        },
    });
};
```

**Comment by timuratctc** [comment]
This worked in an Angular monorepo using ag-grid v30.2.0 modules:

`<workspaceRoot>/jest.preset.js`:

```js
const nxPreset = require('@nx/jest/preset').default;

module.exports = {
  ...nxPreset,
  resolver: '../../jest.resolver.js',
};
```

`<workspaceRoot>/jest.resolver.js`:

```js
const nxResolver = require('@nx/jest/plugins/resolver');

module.exports = (request, options) => {
  try {
    return options.defaultResolver(request, {
      ...options,
      packageFilter: (pkg) => {
        const packageName = pkg.name;
        if (packageName === '@ag-grid-community/angular') {
          return {
            ...pkg,
          };
        }
        const agDependency = packageName.startsWith('@ag-grid');
        return {
          ...pkg,
          // default to use the CommonJS ES5 entry point for Jest testing with AG Grid
          main: agDependency
            ? './dist/cjs/es5/main.js'
            : pkg.module || pkg.main,
        };
      },
    });
  } catch (e) {
    return nxResolver(request, options);
  }
};
```

This can break tests of custom Nx plugins but can be fixed by placing a clone of the original `jest.preset.js` file in the Nx plugin's root directory (or create a global one in workspace root for multiple plugins) then updating the reference in `libs/my-nx-plugin/jest.config.ts`.

**Comment by alexandrenikolov** [comment]
The solution proposed by [seanlandsman](https://github.com/seanlandsman) does not work for React applications. 
The idea in the solution is that with custom Jest resolver we redirect the entry point for the module to a CJS version. But for the @ag-grid-community\react module there is no CJS version of the module provided. 
For other modules you have dist folder with cjs and esm subfolders that contain corresponding version of the module but for @ag-grid-community\react there is only lib folder containinf exm version of the module.

**Comment by leandertolksdorf** [comment]
@seanlandsman 
This solution generates the error from the beginning when trying to import `@ag-grid-community/react`.
```
SyntaxError: Unexpected token 'export'
```
Isn't the real issue here that `@ag-grid-community/react` doen't have the cjs versions?

**Comment by Hadarder** [comment]
hey,
as mentioned above, this solution does not work for React applications.
Is there any other way to use both jest and @ag-grid-community/react?

**Comment by seanlandsman** [comment]
If you're using CRA you can try the following in your package.json (the config above won't be picked up)

```
"test": "react-scripts test --transformIgnorePatterns \"/node_modules/(?!(@ag-grid-community|@ag-grid-enterprise)/)\"",
```

**Comment by arek-widelab** [comment]
As a community support I can tell you that mappings works for us:
jest.config.js
```js
 moduleNameMapper: {
    "@ag-grid-community/react":
      "<rootDir>/node_modules/@ag-grid-community/react/bundles/ag-grid-react.min.js",
    "@ag-grid-community/core":
      "<rootDir>/node_modules/@ag-grid-community/core/dist/cjs/es5/main.js",
    "@ag-grid-enterprise/core":
      "<rootDir>/node_modules/@ag-grid-enterprise/core/dist/cjs/es5/main.js",
    "@ag-grid-community/client-side-row-model":
      "<rootDir>/node_modules/@ag-grid-community/client-side-row-model/dist/cjs/es5/main.js",
  },
```

depends on your used modules list can be bigger

**Comment by leandertolksdorf** [comment]
@arek-widelab Thank you! Updating to v31 and using your moduleNameMapper solved the issue for us.

**Comment by Fitz-Simmons** [comment]
> As a community support I can tell you that mappings works for us in Ag grid 31.0.2
> 
> jest.config.js
> 
>  moduleNameMapper: {
>     "@ag-grid-community/react":
>       "<rootDir>/node_modules/@ag-grid-community/react/bundles/ag-grid-react.min.js",
>     "@ag-grid-community/core":
>       "<rootDir>/node_modules/@ag-grid-community/core/dist/cjs/es5/main.js",
>     "@ag-grid-enterprise/core":
>       "<rootDir>/node_modules/@ag-grid-enterprise/core/dist/cjs/es5/main.js",
>     "@ag-grid-community/client-side-row-model":
>       "<rootDir>/node_modules/@ag-grid-community/client-side-row-model/dist/cjs/es5/main.js",
>   },
> depends on your used modules list can be bigger

Hi @arek-widelab , this mapping solved my problem too, thank you!
Could you please tell me how you find this ?
