### ISSUE TITLE
StopEditingWhenCellsLoseFocus conflict with the select

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#6955]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
I customized a drop-down box and added ag-custom-component-popup, but it still didn't stop the mouse click from losing focus
Reference example：https://stackblitz.com/edit/angular-neduxw?file=src%2Fapp%2Fprop-editor%2Fprop-editor.component.ts
https://www.ag-grid.com/angular-data-grid/component-date/#example-custom-date
![image](https://github.com/ag-grid/ag-grid/assets/57131579/208682b5-3573-4925-be70-7f2cadeeb220)
![image](https://github.com/ag-grid/ag-grid/assets/57131579/7d5a95a3-10ab-44a8-a7a3-2d2878aa4f5c)
![image](https://github.com/ag-grid/ag-grid/assets/57131579/93f61866-39d2-4e3b-af82-d76572345856)
![image](https://github.com/ag-grid/ag-grid/assets/57131579/feacc3e6-4f76-4e86-b1cb-2f3925accd05)

`
<nz-select #nzSelect [(ngModel)]="singleValue" nzSize="small" [nzDisabled]="!isEdit"
  [nzDropdownMatchSelectWidth]="false" nzAllowClear nzShowSearch [nzFilterOption]="nzFilterOption" style="width: 100%"
  class="ag-custom-component-popup">
  <nz-option (click)="$event.stopPropagation()" nzCustomContent *ngFor="let _typeData of _typeData"
    [nzValue]="_typeData.id" [nzLabel]="_typeData.name">
    <span> {{ _typeData.id }} . {{ _typeData.name }} </span>
  </nz-option>
</nz-select>
`

* **AG Grid version:**30.0.6

* **Browser:**
Google Chrome 115.0.5790.171

**Comment by lcc3274312** [comment]
Hi, I've encountered the same issue. Have you found a solution?

**Comment by afr751116** [comment]
> Hi, I've encountered the same issue. Have you found a solution?

No solution, use official selector : https://www.ag-grid.com/angular-data-grid/provided-cell-editors/#select-cell-editor

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by alanma75** [comment]
hi I would like to ask if Ag grid support has any insight into this issue when any custom edit component is used where a div is positioned below edit as a selection (kendo select, kendo multi-select, the component mentioned above... etc), click on that triggers ag grid to close edit because it loses focus. any way to prevent that?
