### ISSUE TITLE
When a click event is triggered in a custom header and a stop is set in the event, the column is not virtualized as expected.

### ISSUE THREAD

**Issue by lin52025iq** [ag-grid/ag-grid#6957]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
plunker: https://plnkr.co/edit/9vbWoNLhd3JlQ2MF?open=main.js
**Current behavior**
Click the click stop button on the `athlete` column, then scroll the table to the right and observe that the `athlete` header in the console does not disappear

https://github.com/ag-grid/ag-grid/assets/87741822/25b9c9b6-fb1e-42b7-ba59-05c7c8833c69

**Expected behavior**
The athlete column disappears after scrolling the table to the right.

**Please tell us about your environment:** 

* **AG Grid version:** 30.0.6

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] all

**Comment by lin52025iq** [comment]
Is there any way to set it up so that virtualization is always performed.
The scenario I've encountered is that clicking the stop button creates a popper on the current header-cell that scrolls with the header; there are also buttons on the outside that create a popper on the header-cell when clicked; when the current column leaves the page, the popper created by clicking the button on the outside is deleted (via MutationObserver) because the header is virtualized, but not when clicking the stop button on the header-cell, because the column is not virtualized. When the column leaves the page, the popper created by clicking the external button will be deleted because the table header has been virtualized (via MutationObserver), while the stop button on the header-cell will not be deleted when clicked, because the column has not been virtualized.

**Comment by zoheil-ag** [comment]
Hi @lin52025iq,

So with the structure of the grid and how it works it wouldn't be possible to virtualize in this scenario. A focused cell prevents that column/row from being virtualized for various reason due to how the grid responds to certain commands and rendering.

However what I can suggest is to use `onGridBodyScroll` and to destroy poppers upon listening for that event. That could be a solution for you.

Kind regards,
Zoheil
