### ISSUE TITLE
stacked bars with pos + neg values don't show negative bars started in ag-charts-8.0.5 (worked previously up to 8.0.3)

### ISSUE THREAD

**Issue by kfaiczak** [ag-grid/ag-grid#6959]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

community version
Mac (M2) 13.4.1 (c)
chrome Version 115.0.5790.170 (Official Build) (arm64)
React version ├── react@18.2.0

seems in 8.0.5 (and 8.0.6) stack columns no longer show +/- values

in the pictures the blue at the bottom is the -vs value extending below 0 (8.0.3)
it seems it took that value away from the purple value at the bottom of the bar (in 8.0.5)

I don't specify anything in the chart about axis, I just leave those to be the default

Expected Behaviour
8.0.3
├── ag-charts-community@8.0.3
├── ag-charts-react@8.0.3
├── ag-grid-community@30.0.6
├── ag-grid-react@30.0.6

<img width="666" alt="Screenshot 2023-08-16 at 11 05 01 AM" src="https://github.com/ag-grid/ag-grid/assets/63421082/29b16e4d-0a86-41e6-8ae9-c1fb5b7d4491">

Current Behaviour
8.0.5 (8.0.6)
├── ag-charts-community@8.0.5
├── ag-charts-react@8.0.5
├── ag-grid-community@30.0.6
├── ag-grid-react@30.0.6

<img width="659" alt="Screenshot 2023-08-16 at 11 04 08 AM" src="https://github.com/ag-grid/ag-grid/assets/63421082/41b58ce3-61ee-4291-bbe0-e9b3def23d49">

Data looks like this (most of these are in the stack column, some unused, 1 is  a line)
					{
						"CPP*:Income": 16719,
						"Cash:Income": 2440,
						"Cost": 0,
						"Cumulative": 4198878,
						"Gross* Total": 109786,
						"Margin:Dividend": 26717,
						"OAS*:Income": 4141,
						"PensionTransfer*:PensionIncome": -12140,
						"RRSP:PensionIncome": 69433,
						"Stock:ReturnOfCapital": 2473,
						"age": 76
					},
					{
						"CPP*:Income": 16719,
						"Cash:Income": 2441,
						"Cost": 0,
						"Cumulative": 4310545,
						"Gross* Total": 111669,
						"Margin:Dividend": 27918,
						"OAS*:Income": 3858,
						"PensionTransfer*:PensionIncome": -12358,
						"RRSP:PensionIncome": 70674,
						"Stock:ReturnOfCapital": 2415,
						"age": 77
					},

grid info looks like
                    Title": {
					"text": "xxx"
				},
				
			
				"Series": [
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "CPP*:Income",
						"yName": "CPP*:Income"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "PensionTransfer*:PensionIncome",
						"yName": "PensionTransfer*:PensionIncome"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "OAS*:Income",
						"yName": "OAS*:Income"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Employment:Income",
						"yName": "Employment:Income"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Emp-MyOwnFP:Income",
						"yName": "Emp-MyOwnFP:Income"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "RRSP:Income",
						"yName": "RRSP:Income"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "RRSP:PensionIncome",
						"yName": "RRSP:PensionIncome"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Margin:Dividend",
						"yName": "Margin:Dividend"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Stock:ReturnOfCapital",
						"yName": "Stock:ReturnOfCapital"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Cash:Income",
						"yName": "Cash:Income"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Cash:ReturnOfCapital",
						"yName": "Cash:ReturnOfCapital"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Margin:CapitalGain",
						"yName": "Margin:CapitalGain"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Margin:ReturnOfCapital",
						"yName": "Margin:ReturnOfCapital"
					},
					{
						"type": "column",
						"stacked": true,
						"xKey": "age",
						"yKey": "Inheritance:TaxFree",
						"yName": "Inheritance:TaxFree"
					},
					{
						"type": "line",
						"xKey": "age",
						"yKey": "Gross* Total",
						"yName": "Gross* Total##$",
						"title": "Gross* Total"
					}
				],
				"Data": [ ....

**Comment by zoheil-ag** [comment]
Hi @kfaiczak,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by kfaiczak** [comment]
I have no real idea what you mean by a plunker  ... but I guessed this

https://plnkr.co/edit/B2eI6T1qfqxbPdmv?preview

I basically just copied the above into it to keep it as close as possible to my situation

Issues:
1.  you can see there should be a -ve value Y in each stack (PensionTransfer in this case)
2. you can also see the lowest bar on the stack show some value X 
       - (but if you hover over it its actually some larger value Z)
       - ie the hover when it changes to highlight is now a completely different size than what was shown
        - the size of of the bar X = the original value (Z) - the missing negative bar in the stack (Y)


what should happen of course (as in 8.0.3 and previous) 
is there should be a negative bar -Y below ZERO
and then of course the lowest postive bar should be its proper value Z

hopefully that helps

**Comment by kfaiczak** [comment]
Here is another variation I just saw where the -ve value is actually stacked on top of the +ve bars


here all the red bars on the top (every 2nd stack) is a -ve value but its at the top of the bars
(you can see that is why the sum line drops below the top of the bars (ie since there is a -ve value in those stacks)
if the first one I hightlight its yellow of course since thats the highlight colour but otherwise would be red as per the hover tooltip)

<img width="313" alt="Screenshot 2023-08-17 at 8 30 37 PM" src="https://github.com/ag-grid/ag-grid/assets/63421082/c173e3df-3a88-4d54-b71c-f39d3784970f">

**Comment by zoheil-ag** [comment]
Hello @kfaiczak,

Thank you for all the extra information - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-9157 [Charts] Stacked column not handling data with pos and neg values correctly - regression**

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
