### ISSUE TITLE
Questions about the agCheckboxCellRenderer component

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#6964]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
https://plnkr.co/edit/?open=main.js&preview
My reference example uses 'agCheckboxCellRenderer' and 'agCheckboxCellEditor'
`    {
      field: 'value2',
      headerName: 'With Checkbox Editor',
      cellRenderer: 'agCheckboxCellRenderer',
      cellEditor: 'agCheckboxCellEditor',
      editable: true,
      suppressKeyboardEvent: (params) => params.event.key === ' ',
    },`

Then I want the editor to be dynamic, but agCheckboxCellRenderer doesn't seem to accept dynamic display and closure, resulting in this.isEdit=true, not editable

`    {
      field: 'value2',
      headerName: 'With Checkbox Editor',
      cellRenderer: 'agCheckboxCellRenderer',
      cellRendererParams: params => {
        return {
          disabled: !this.isEdit
        };
      }
      cellEditor: 'agCheckboxCellEditor',
       editable: o => !o.node.isRowPinned() && this.isEdit,
      editable: true,
      suppressKeyboardEvent: (params) => params.event.key === ' ',
    },`

* **AG Grid version:**
  30.0.6

* **Browser:**
Google Chrome 115.0.5790.171

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
