### ISSUE TITLE
when you zoom out, some of the separators in the headers vanishes

### ISSUE THREAD

**Issue by sanket-bhalerao** [ag-grid/ag-grid#6966]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- open https://www.ag-grid.com/examples/data-update-high-frequency/async-transaction/packages/angular/index.html
- on laptop (1920 x 1080, 100% scale) zoom out browser to 33%
- observe the column header separators

![image](https://github.com/ag-grid/ag-grid/assets/9264813/687fb54b-137a-4c69-ace4-2e12aa5a02b1)

we have a license for AG-Grid

**Comment by zoheil-ag** [comment]
Hello @sanket-bhalerao,

Thank you for the suggestion.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We already have this requirement in our backlog and we are tracking it with the following reference and description:
**AG-2550 [Grid Rendering] Add support for scaling and zoom in/out of the browser**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
