### ISSUE TITLE
Long layouts in chrome performance captures while resizing window with sidebar enabled

### ISSUE THREAD

**Issue by yohosuff** [ag-grid/ag-grid#6970]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When the sidebar is enabled and the `ag-grid-angular` component is wrapped in a few flex divs like so...

![image](https://github.com/ag-grid/ag-grid/assets/3869624/47da50c4-7c4a-4739-b976-18dc6fcb3d7b)

...then there is a noticeable performance issue with high CPU when performing horizontal window resizing with the mouse:

![e402ab2c-81ea-4fe1-91c8-9e7a8520c902](https://github.com/ag-grid/ag-grid/assets/3869624/f3303bdb-4c8c-4f70-b973-d0f8de73ebcb)

A performance capture reveals long layout operations:

![image](https://github.com/ag-grid/ag-grid/assets/3869624/13db51b6-4746-405e-b584-f86e7b4e7dec)

Wrapping the `ag-grid-angular` in more and more levels results in worse and worse performance.

The issue can be reproduced with the project below (brand new angular 15 project with ag-grid added).

[long_layouts.zip](https://github.com/ag-grid/ag-grid/files/12384297/long_layouts.zip)

**Expected behavior**

However... if the sidebar is disabled then the issue disappears:

![86a9c1c1-8214-4e0a-8461-09f0f72bbec3](https://github.com/ag-grid/ag-grid/assets/3869624/4ab08d02-c8c9-46ef-96ac-50074b952584)

The performance capture also does not contain any long layout operations.

![image](https://github.com/ag-grid/ag-grid/assets/3869624/4b926f7e-f6e4-48d9-9a58-80e42907f0e4)

**Please tell us about your environment:**

Windows 10 WSL2 Ubuntu 22.04

* **AG Grid version:** 26.0.1 (Same problem exists in 30.0.6)

* **Browser:** 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36'

* **Language:** TypeScript 4.9.4

Thanks!

![image](https://github.com/ag-grid/ag-grid/assets/3869624/de18a0ac-43e8-498c-923e-b1fd4f598556)

![image](https://github.com/ag-grid/ag-grid/assets/3869624/e503df6d-2cdc-4350-a2e0-d5e8fb7aebb2)

**Comment by zoheil-ag** [comment]
Hello @yohosuff,

Thank you for your suggestions.

We have decided to investigate this in more detail and hence have added this as an item to our backlog. You can track it with the following reference and description:
**AG-9191 [Performance] Investigate enhancing performance when resizing window with sidebar enabled**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
