### ISSUE TITLE
AG grid is breaking the UI whenever sorting and groupby are applied

### ISSUE THREAD

**Issue by Himasagarika** [ag-grid/ag-grid#6971]
**I'm submitting a Bug report**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
While sorting the columns when the group by is applied , Sometimes the AG grid is breaking the UI and throwing the following error. (Cannot read properties of undefined (reading 'SetUiLevel')
This is reproducing only once in many trails with no particular pattern.

<img width="1722" alt="SetUIlevel error" src="https://github.com/ag-grid/ag-grid/assets/31796643/11fe559d-5f3f-40b8-812f-dd478c872b58">

**Expected behavior**
It should not break the UI and work correctly whenever groupby and sorting are applied. 

**Please tell us about your environment:**

Operating system - 13.5.1 
IDE - Visual Studio code

* **AG Grid version:** 29.3.5

* **Browser:**
Version 115.0.5790.170

* **Language:** [Javascript ES6]

**Comment by zoheil-ag** [comment]
Hi @Himasagarika,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue. Are you able to replicate this behaviour using the examples on our website?
You can use one of the examples from our website as a starting point to send us a live plunker sample which shows the issue. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
