### ISSUE TITLE
how can i get a drag and drop error when i'm using the pinned and drag-and-drop functions in the rowpinned rows, how do i fix it?

### ISSUE THREAD

**Issue by SiTV-CsharpReact** [ag-grid/ag-grid#6974]
<AgGridReact
    ref={gridRef}
    suppressDragLeaveHidesColumns={true}
    suppressCellFocus={true}
    rowHeight={25}
    overlayNoRowsTemplate={"Loadding..."}
    rowData={ListDataTable}
    pinnedTopRowData={DataPined}
    columnDefs={columnDefs}
    defaultColDef={defaultColDef}
    rowDragManaged={true}
    rowDragEntireRow={true}
    rowDragMultiRow={true}
    rowSelection={"multiple"}
    animateRows={true}
    gridOptions={gridOptions}
    rowMultiSelectWithClick={true}
    onGridReady={(params: any) => {
      params.api.sizeColumnsToFit(undefined, {
        suppressSizeToFit: false,
      });
    }} source code

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
