### ISSUE TITLE
Advanced filter documentation page is blank

### ISSUE THREAD

**Issue by glenkitchen** [ag-grid/ag-grid#6982]
The advanced filter documentation page is blank

**Url:**
https://www.ag-grid.com/javascript-data-grid/filter-advanced/ 

**Browser console error:** 
Error: Failed to find a property named includeHiddenColumnsInAdvancedFilter that we requested under section filter. Check if you passed the correct name or if the name appears in the source json file that you are using.
    at ApiDocumentation.tsx:394:23
    ...

**Comment by StephenCooper** [comment]
Could you try doing a hard refresh of the page? Unable to reproduce the issue with that page and it loads correctly.
