### ISSUE TITLE
Using gridColumnApi.getColumnState() in OnDestroy event

### ISSUE THREAD

**Issue by sayajirao-shinde28** [ag-grid/ag-grid#6983]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
Plunker - [Demo](https://plnkr.co/edit/SN7hjeDFK3NUhzNq?open=app%2Fapp.component.ts)

I'm trying to save the column state and re-apply it when the user revisits the page again. For this, I'm using the GridColumnApi.  Everything is working fine when we save the state on the button click, but I want to save it on the OnDestroy method. 

On the OnDestroy event, I'm getting an empty state all the time. Is it not possible to get the column state in the OnDestroy method? I could not find anything about this in the documentation.

Here I can get the state on **Save State** button click but not in the OnDestroy method.

**Current behavior**
`gridColumnApi.getColumnState()` returns an empty array when used in `ngOnDestroy` event

**Expected behavior**
Should get the current column state for grid.

**Comment by zoheil-ag** [comment]
Hello @sayajirao-shinde28,

Thank you for getting in touch.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We are tracking it in our backlog with the following reference and description:
**AG-684 [Events] Add a gridPreDestroyed event for the grid instance**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid by saving the column state upon any changes until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
