### ISSUE TITLE
applyColumnState and getColumnState are out of sync

### ISSUE THREAD

**Issue by IgorTurko** [ag-grid/ag-grid#6984]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
After upgrading ag-grid from 26 to 29, I started to have some problems with ColumnState. Could you explain what I am doing wrong or what changes have been applied to 29 so it won't work anymore?

**Current behavior**
Now when I call `applyColumnState` inside `onGridReady`, `getColumnState` still returns the old state from `onSortChanged`;

**Expected behavior**
I expect `getColumnState` to return the same as what we recently saved by calling `applyColumnState`.

**Example**
```
function useGridState(): {
     onGridReady: (param: GridReadyEvent) => void;
} => {

  const gridApi = useRef<GridApi | null>(null);
  const columnApi = useRef<ColumnApi | null>(null);

  const onGridReady = (params: GridReadyEvent) => {
    gridApi.current = params.api;
    columnApi.current = params.columnApi;

    const result = columnApi.current.applyColumnState({
      state: NEW_SORT_ORDER,
    });

    // SUCCESS: column state is exactly NEW_SORT_ORDER
    console.log("ready NEW_SORT_ORDER", columnApi.current.getColumnState())
  };

   return { onGridReady };
}

function MyGrid() {
   const { onGridReady } = useGridState();

   const handleSortModelChange = (event: SortChangedEvent) => {

     // FAILED: Here I am expecting the NEW_SORT_ORDER
     // which was saved onGridReady
     // but this state is empty
     console.log("newState", event.columnApi.getColumnState())
   };

   return (
      <Grid onGridReady={onGridReady} onSortChanged={handleSortModelChanged} />
   )
}
```

**Environment:**
Ubuntu 20.04 LTS;
React 18.2;
Node 18;

**AG Grid version:** 29.1.0

**Browser:** Version 115.0.5790.173 (Official Build) (64-bit)

**Language:** TypeScript 5.1.6

**Comment by zoheil-ag** [comment]
Hi @IgorTurko,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by MaximBalaganskiy** [comment]
Please reopen, we're having the same issue

**Comment by AG-Zoheil** [comment]
Hi @MaximBalaganskiy,

we'd be happy to help with this. Are you able to provide a reproducible scenario for us to look into this please?

Much appreciated!

Kind regards,
Zoheil
