### ISSUE TITLE
createRangeChart does not supoort "refData"

### ISSUE THREAD

**Issue by BeanCafe** [ag-grid/ag-grid#6985]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

You can use the follow code to review.
[https://plnkr.co/edit/c1DoPAMhjWGqpjlc?open=main.js&preview](url)

for example.
![WechatIMG19](https://github.com/ag-grid/ag-grid/assets/11352694/ff73defb-9f41-4775-88e7-07c9e4e5b1ea)
![image](https://github.com/ag-grid/ag-grid/assets/11352694/db3f2bf7-2a48-4c7d-b0f5-4a3fbb07bbb6)

**Comment by zoheil-ag** [comment]
Hello @BeanCafe,

Thank you for the suggestion.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
**AG-9208 [Integrated Charts] Allow range chart to support refdata mapping as a datasource for chart**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
