### ISSUE TITLE
Where can I find the code for the Demo Grid displayed on the site?

### ISSUE THREAD

**Issue by maxxims** [ag-grid/ag-grid#6986]
Hi,

Is the code for the demo grid displayed at https://www.ag-grid.com/example/ on github or anywhere else?

Thank you!

**Comment by zoheil-ag** [comment]
Hi @maxxims,

You can find the source code for our demo here: https://github.com/ag-grid/ag-grid/blob/latest/grid-packages/ag-grid-docs/documentation/src/mainPageDemo/Example.jsx.

I hope that helps.

Kind regards,
Zoheil
