### ISSUE TITLE
Broken call of grid methods in onRowDataUpdated (React 18)

### ISSUE THREAD

**Issue by adamzalesak** [ag-grid/ag-grid#6990]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
After updating React to version 18, when I call `setFocusedCell` or `startEditingCell` in the `onRowDataUpdated` event handler, these calls have no effect. I found a workaround by placing this calls at the end of the event loop (setTimeout).

**Expected behavior**
Calling grid methods works correctly in `onRowDataUpdated`.

**Please tell us about your environment:**

* **AG Grid version:** 30.1.0

* **Browser:** Google Chrome 116.0.5845.97

* **Language:** TypeScript 5.0.4 + React 18.2.0

**Comment by zoheil-ag** [comment]
Hi @adamzalesak,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
