### ISSUE TITLE
gridPanel is removed from gridApi in ag-grid version 25, what is the alternative?

### ISSUE THREAD

**Issue by Satish8798** [ag-grid/ag-grid#6992]
we use gridPanel type which used to be present in gridApi and we used properties like eBodyViewport, bodyHeight, ScrollWidth...
After upgrading to ag-grid version 25, gridPanel is missing in gridApi type definition file and this is not documented in release notes also, we are trying to get an alternative type for gridPanel that has all the properties as gridPanel

**Comment by achrefabdennebi** [comment]
@Satish8798 : Do you have an idea, what's the alternative ?

**Comment by Satish8798** [comment]
@achrefabdennebi hey! I used gridBodyComp in v25, used gridBodyCon in v26 and  gridBodyCtrl in v27 as alternatives but these also does not have all the properties and methods that gridPanel had. It depends on what properties and methods you use from gridPanel. give it a try!!
