### ISSUE TITLE
Column Grouping AggFunc not working in Production Build

### ISSUE THREAD

**Issue by rohith5429** [ag-grid/ag-grid#6994]
### When grouping the column the Agg Function Works fine in "local development server"
but not working in the **Production Build**.

```
      <ag-grid-angular
        class="ag-theme-alpine-dark"
        style="height: 1080px"
        [rowData]="rowData$ | async"
        [getRowId]="getRowIdAuto"
        [columnDefs]="colDefs"
        [rowSelection]="'multiple'"
        [sideBar]="sideBar"
        [rowGroupPanelShow]="rowGroupPanelShow"
        [pivotPanelShow]="pivotPanelShow"
        [animateRows]="true"
        [pagination]="true"
        [paginationPageSize]="50"
        [defaultColDef]="defaultColDef"
        (gridReady)="onGridReady($event)"
        (selectionChanged)="onSelectionChanged($event)"
        (cellValueChanged)="onCellValueChanged($event)"
        [allowContextMenuWithControlKey]="true"
        [getContextMenuItems]="getContextMenuItems"
        [frameworkComponents]="frameworkComponents"
        (firstDataRendered)="onFirstDataRendered($event)"
        (displayedColumnsChanged)="onChangeState($event)"
        [groupDefaultExpanded]="groupDefaultExpanded"
        [enableRangeSelection]="true"
        [groupDisplayType]="groupDisplayType"
        [groupRowRendererParams]="groupRowRendererParams"
        [columnTypes]="columnTypes"
        [gridOptions]="gridOptions"
        [statusBar]="statusBar"
        [animateRows]="true"
      >
      </ag-grid-angular>
      
   public groupRowRendererParams: any = {
    suppressCount: false,
    innerRenderer: GroupRowInnerRenderer,
  };

  colDefs: ColDef[] = [
    {
      headerName: "Country",
      field: "country",
      aggFunc: "sum",
    },
    ]
    
      defaultColDef: ColDef = {
    sortable: true,
    filter: true,
    resizable: true,
    enableRowGroup: true,
  };
```

### my local dev server console output: **(params.node.aggData)**

```
aggData: {
country: 60
flag: 60
}
```

**console output from my Production Build** 
`aggData: null`

i use ag-grid of versions:

> 
>     "ag-grid-angular": "^27.3.0",
>     "ag-grid-autocomplete-editor": "^3.0.1",
>     "ag-grid-community": "^28.0.2",
>     "ag-grid-enterprise": "^28.0.2",

my angular version

> Angular CLI: 8.3.29
> Angular: 8.2.14

**Comment by zoheil-ag** [comment]
Hi @rohith5429,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
