### ISSUE TITLE
navigateToNextCell not called with shift+arrowKey when enabledRangeSelection = true

### ISSUE THREAD

**Issue by destradafilm** [ag-grid/ag-grid#6995]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'

```

**Current behavior**
 if `enableRangeSelection = true`  then `navigateToNextCell` callback wont be fired when you shift + arrowKey 
Plunker: https://plnkr.co/edit/z4217yvu2vsAzFQg

**Expected behavior**
Documentation doesn't state this will be disabled if you have enableRangeSelection set to true

* **AG Grid version:** X.X.X
    "@ag-grid-community/core": "^30.0.2",
    "@ag-grid-community/styles": "^30.0.2",
    "@ag-grid-community/vue": "^30.0.2",
    "@ag-grid-enterprise/menu": "^30.0.2",
    "@ag-grid-enterprise/row-grouping": "^30.0.2",
    "@ag-grid-enterprise/server-side-row-model": "^30.0.2",
    "@ag-grid-enterprise/range-selection": "^30.0.2",
    "@ag-grid-enterprise/clipboard": "^30.0.2",

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by zoheil-ag** [comment]
Hi @destradafilm,

Thank you for submitting this and for providing a plunker.

Upon reviewing the described scenario the following clarification should be made:

`navigateToNextCell` does not trigger when using shift + arrow keys whilst `rangeSelection` is enabled as the actual focus of the cell does not move from the originally selected cell.

This can be demonstrated best with the following example:

1. Please go to your plunker and select the first United States cell in column Three
2. Shift + Arrow key three cells down
3. Now let go of Shift and just press the right or left arrow

Result: You'll notice that despite you going down three cells using shift, once you let go of shift and navigated solely with the arrow key the actual focus was still the first United States cell in column Three.

For this reason `navigateToNextCell` does not trigger when used during `rangeSelection`.

I hope the above clarifies the issue.

If you have a question or would like to comment further on this, please feel free to do so.

Kind regards,
Zoheil

**Comment by destradafilm** [comment]
Thanks for you reponse. That makes sense technically although it's not so obvious what cell is in 'focus'  to as a user of the grid. 

I looked at the docs some more and what I was really needing was the `cellKeyDown` event. 
https://www.ag-grid.com/vue-data-grid/keyboard-navigation/#keyboard-events

**Comment by AG-Zoheil** [comment]
Thanks @destradafilm, that is a fair comment.

We do have more general improvements planned to our selection mechanism. So this may be something we will tackle alongside those changes in due time.
