### ISSUE TITLE
rangeSelectionChanged - first event is started=true and finished=true

### ISSUE THREAD

**Issue by destradafilm** [ag-grid/ag-grid#6996]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
If selecting a range of 10 cells in a row, the user will click the first cell and drag to the last cell. The first event triggered is on mouse click and has `started=true` and `finished=true`

Plunker: https://plnkr.co/edit/o0vC2t7LNmcvsDjX?open=main.js&preview

**Expected behavior**
RangeSelectionChanged docs link: https://www.ag-grid.com/vue-data-grid/range-selection/#range-selection-changed-event

*..if selecting a range of 10 cells in a row, the user will click the first cell and drag to the last cell. The first event will have started=true, the last will have finished=true, and all the intermediary events will have both of these values as false

* **AG Grid version:** X.X.X
 "@ag-grid-community/core": "^30.0.2",
    "@ag-grid-community/styles": "^30.0.2",
    "@ag-grid-community/vue": "^30.0.2",
    "@ag-grid-enterprise/menu": "^30.0.2",
    "@ag-grid-enterprise/row-grouping": "^30.0.2",
    "@ag-grid-enterprise/server-side-row-model": "^30.0.2",
    "@ag-grid-enterprise/range-selection": "^30.0.2",
    "@ag-grid-enterprise/clipboard": "^30.0.2",

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

**Comment by AG-Zoheil** [comment]
Hi @destradafilm,

This is a valid observation.

The first and last cell in the range will cause **two events**. This is due to the first cell firing an event with `finished=true` upon `mousedown` and the last cell firing an event as soon as it is in the range and then again upon the end of range selection. All the intermediary events will have one event with both started and finished as false.

We will be looking to make our explanation in the documentation for this clearer.

Thanks for bringing this up with us.

Kind regards,
Zoheil

**Comment by destradafilm** [comment]
@AG-Zoheil Thanks for the explanation. I am working to get a Enterprise license through our company - we're just waiting for approval. Once that goes through how would I go about requesting a feature? It would be super helpful to expose the source of the event and the actual `mouse/keyboard` event associated with the `rangeSelectionChanged` event

**Comment by AG-Zoheil** [comment]
My pleasure @destradafilm.

That's great to hear. Once set up, the team should give you access to the [enterprise ticketing system](https://ag-grid.zendesk.com/).

Meanwhile, can you clarify the FR? What kind of "actual mouse/keyboard event data" would be expecting?

**Comment by destradafilm** [comment]
so to clarify the original issue I'm trying to work around is when a user selects a range then we want to select the rows with in the ranges. Since this isn't supported out of the box then I'm working with several events to manage this. 

If I were to use the 'rangeSelectionChanged' to handle all interactions related to selection then I would also want to know if a user has `ctrl + clicked` to open the context menu rather than listen to two events called`rangeSelectionChanged` and `cellContextMenu` 

That's just one example why it would be helpful

**Comment by AG-Zoheil** [comment]
Thank you for the clarification @destradafilm, I have added the label of the corresponding FR we already have in our backlog for your reference.

Kind regards,
Zoheil
