### ISSUE TITLE
How do I hide the browser's autocomplete box in the column filter?

### ISSUE THREAD

**Issue by goranmandiccrs** [ag-grid/ag-grid#6997]
[x] bug report => see 'Providing a Reproducible Scenario'' 
(it's possible that I've missed something in the docs)

**Providing a Reproducible Scenario**
The autocomplete suggestion box can be seen in the official example- I've provided an image. 
https://ag-grid.com/react-data-grid/filtering/

**Current behavior**
Currently, the text input in the column filter autocompletes based on previous inputs. I would like to hide the autocomplete suggestions.
<img width="709" alt="image" src="https://github.com/ag-grid/ag-grid/assets/43639874/12f912fa-748c-46e4-9766-361dc3a67e78">

**Expected behavior**
I would like to be able to hide the autocomplete suggestions.
**Please tell us about your environment:**
This happens in all browsers, on the AG Grid website example for column filters:
https://ag-grid.com/react-data-grid/filtering/

* **AG Grid version:** X.X.X
This is probably an issue on all AG Grid versions

* **Browser:**
All browsers

**Comment by zoheil-ag** [comment]
Hi @goranmandiccrs,

The following should help: https://ag-grid.com/javascript-data-grid/floating-filters/#controlling-autocomplete-on-floating-filters

Please note this feature was added to the grid in `30.1.0` and will not be available in older versions.

Kind regards,
Zoheil

**Comment by goranmandiccrs** [comment]
@zoheil-ag thank you, I suspected that there was already a way to do it, but must have missed it in the docs. Cheers

**Comment by goranmandiccrs** [comment]
@AG-Zoheil sorry to bring this up again, but can you please tell me what I'm doing wrong here? 
<img width="1127" alt="image" src="https://github.com/ag-grid/ag-grid/assets/43639874/0b445efd-f973-47e8-9b5c-ecf0ac5fc3ef">
As you can see, I provided the config with 
`floatingFilterComponentParams: {
      browserAutoComplete: false,
  },`
  and I'm still getting the autocomplete.
