### ISSUE TITLE
Server side model export all row data to excel with applied filtering ,grouping

### ISSUE THREAD

**Issue by srinath-varadan** [ag-grid/ag-grid#6999]
Since server side model is used the export displays what ever is rendered on the screen which is as expected. Is there any way to export all the data to excel with the applied sorting filtering grouping etc .

Design : ag grid uses server side row model and server side data source using fake server (ala sql) where data is queried from indexed db ( browser cache). For scenarios have thousands of records. This rendering is working as expected. But if the same is exported to excel is there anyway to display all the rows ( which would mimic data rendered after scrolling till the end ) with all the sorting grouping filtering intact

**Comment by AG-Zoheil** [comment]
Hello @srinath-varadan,

Thank you for the suggestion.

Currently there's no way to implement this behavior with AG Grid.

However, we agree this would be a valuable addition to the product and we already have a feature request for this in our backlog and we are tracking it with the following reference: **AG-1369**.

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by djErock** [comment]
We had this working in version 28 using this SO: https://stackoverflow.com/questions/48006710/export-data-to-csv-in-server-pagination-sorting-filtering-mode

It no longer works in version 30. Is there anyway to update the blocks for export in version 30?
