### ISSUE TITLE
[menu] Show filter icon if the menu is visible

### ISSUE THREAD

**Issue by buremba** [ag-grid/ag-grid#700]
Thanks for creating the grid component that I have been waiting for a long time. :)
When I click the filter icon `(ag-header-cell-menu-button)` and move the cursor to the menu `(ag-filter)`, ag-grid hides the button using `opacity` css attribute. I think it would be better UX to show the button if the menu is active and toggle the menu when the button is clicked.

**Comment by ceolter** [comment]
```
When I click the filter icon (ag-header-cell-menu-button) and move the cursor to the menu (ag-filter), ag-grid hides the button
```
i don't follow, the grid shows the button when you hover over the header (not hide), and it doesn't have anything to do with the icons. maybe i'm no understanding???

**Comment by buremba** [comment]
Sorry, it should be "When I hover the filter button". It would be nice if ag-grid displays the filter button `ag-header-cell-menu-button` when the filter menu is active. 
<img width="334" alt="screen shot 2016-02-09 at 13 25 34" src="https://cloud.githubusercontent.com/assets/82745/12915019/be2f40fe-cf30-11e5-8086-117f4aaa7e5a.png">

**Comment by ceolter** [comment]
ok i understand. this is a bit more work though, not a 1min change.

**Comment by buremba** [comment]
Sure, I actually tried to use CSS in order to solve this problem but it seems that the DOM element for the menu is positioned as absolute and not related to the header cell of the column. Therefore it's required to add a class to the header cell when the menu is active or toggle the button visibility manually in javascript.

**Comment by ceolter** [comment]
yup that's right. the popup has to be outside, otherwise it gets clipped.

**Comment by Matheo13** [comment]
A quick hack because I made it for me:
`    AgGrid.StandardMenuFactory.prototype.showPopup = function (column, positionCallback) {
        var filterWrapper = this.filterManager.getOrCreateFilterWrapper(column);
        var eMenu = document.createElement('div');
        utils_1.Utils.addCssClass(eMenu, 'ag-menu'); //you will need to import it or 2 make it yourself ($).
        eMenu.appendChild(filterWrapper.gui);
        // need to show filter before positioning, as only after filter
        // is visible can we find out what the width of it is
        var closedCallback = function(){
          //Do your stuff here
//(add a class on the click for the filter, remove it on the closeCallBack)
        };
        var hidePopup = this.popupService.addAsModalPopup(eMenu, true, closedCallback);

        positionCallback(eMenu);
        if (filterWrapper.filter.afterGuiAttached) {
            var params = {
                hidePopup: hidePopup
            };
            filterWrapper.filter.afterGuiAttached(params);
        }
    };`

**Comment by santosh-k1** [comment]
How to open Model Box on button click in ag-grid..

**Comment by ceolter** [comment]
this only impacts free version of ag-grid, as in ag-grid-entrprise, the popup menu appears on top of the icon, and the popup has an identical icon, so it appears as if the icon stays.

for free, to get it consistent, we could consider using the same menu popup (but it only has the filter panel, not the other two, as they are enterprise features).

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-107

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
