### ISSUE TITLE
agRichSelectCellEditor opens on all cells on start row edit

### ISSUE THREAD

**Issue by m-hicks-OH** [ag-grid/ag-grid#7002]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Whenever agRichSelectCellEditor  is used in combination with editType = 'fullrow', as soon as row edit begins, all dropdowns open on all cells.  Additionally, if those columns are off-screen, when you scroll to them, the dropdowns will be out of place.  Also, selecting any item from the dropdown will immediately cease row editing.

**Expected behavior**
Dropdowns would not open until the individual cell is clicked (this works with normal agSelectCellEditor).  Also, selecting an item from the list would keep row-edit going.

**Please tell us about your environment:**
Angular / Chrome / Edge

* **AG Grid version:** X.X.X
ag-grid-enterprise 28.2.1

* **Browser:**
Chrome 116.0.0.0
Edge 116.0.1938.6

TypeScrypt

This plunker can be used by changing the agSelectCellEditor to agRichSelectCellEditor and back (the plunker link is on the example in ag-grids documentation here https://www.ag-grid.com/javascript-data-grid/cell-editing-full-row/

**Comment by AG-Zoheil** [comment]
Hi @m-hicks-OH,

Thanks for raising this issue.

I'm afraid full row editors and pop ups/dropdowns are not compatible.

You can read more about it here: https://www.ag-grid.com/javascript-data-grid/cell-editing-full-row/#full-row-edit-and-popup-editors

Kind regards,
Zoheil
