### ISSUE TITLE
Type prop for Column Group Def

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7003]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Expected behavior**
Similar to type config in column definition which maps to columnTypes in grid option
Can we get a similar property for column group definition(ColGroupDef). This can be used set properties like common headerClass, other props.

* **AG Grid version:** X.X.X
30.1.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React + Typescript

**Comment by AG-Zoheil** [comment]
Hello @melon2504,

Thank you for the suggestion.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we have a feature request for this.

We already have this requirement in our backlog and we are tracking it with the following reference and description:
**AG-8804**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi @melon2504,

I stand corrected! Thanks for pointing that out.

I agree this would be a valuable addition to the product and have added a feature request for this.

It can be tracked with the following reference and description:
**AG-9284 [Column Group] Allow column types to work on column groups**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
