### ISSUE TITLE
Export to excel on a grid with pagination (infinite scroll)

### ISSUE THREAD

**Issue by Berni3011** [ag-grid/ag-grid#7004]
Is it possible to export all data to excel without the other data behind the pagination not being rendered in the grid yet?

**Comment by AG-Zoheil** [comment]
Hi @Berni3011,

Please have a look at this example that should demonstrate how to do this: https://plnkr.co/edit/UjasvRZy4GnSVuZZ?open=lib%2Fscript.js.

Kind regards,
