### ISSUE TITLE
applyServerSideTransaction abnormal

### ISSUE THREAD

**Issue by yundmb** [ag-grid/ag-grid#7006]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
rowModelType: "serverSide"
getRowId: Return value type integer
gridApi.applyServerSideTransaction({remove: [{id: x}]})

This parameter is used when the return value of getRowId is integer
GridApi applyServerSideTransaction delete data, can lead to abnormal data in tables, disappearance of actual data is not selected to delete data, when I will return the value type is set to a string, there is no this situation.

* **AG Grid version:** 
* 30.1.0
* 
* **Browser:**
Chrome

* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hi @yundmb,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi @yundmb,

Thank you for the plunker.

We noticed you are returning numeric ids from our getRowId func. You need to return Strings.

Note the change to line 56:
https://plnkr.co/edit/JELkVfG70SwneHDq?open=main.js

We appreciate you bringing this up with us and to make things clearer we will add a warning message to the console for this occurrence.

Kind regards,
Zoheil
