### ISSUE TITLE
How to get partially selected[-] row nodes?

### ISSUE THREAD

**Issue by alaywn** [ag-grid/ag-grid#7008]
Current behavior

For tree data, it is not possible to strictly distinguish between selected, unselected, and partially selected.

Expected behavior

I would like to know how to obtain partially selected rows/nodes.

My Environment

AG Grid version: 30.1.0
Browser:  google-chrome: 116.0.5845.140
Language: TypeScript 5.2.2

**Comment by joemaylor** [comment]
Hi,

This is the following from the type definition of `IRowNode.isSelected`

```ts
/** Returns:
 * - `true` if node is selected.
 * - `false` if the node isn't selected.
 * - `undefined` if it's partially selected (group where not all children are selected).
 */
isSelected(): boolean | undefined;
```

So you could have a function e.g.

```ts
function getPartiallySelectedNodes(api: GridApi) {
  const partiallySelectedNodes: IRowNode[] = []
  api.forEachNode(node => {
    if (node.isSelected() === undefined)
      partiallySelectedNodes.push(node)
  })
  return partiallySelectedNodes
}
```
