### ISSUE TITLE
"Push for Total" button under Cell renderer example table is not actionable through keyboard.

### ISSUE THREAD

**Issue by msftedad** [ag-grid/ag-grid#7011]
"Push for Total" button under Cell renderer example table is not actionable through keyboard.

**Providing a Reproducible Scenario**

1. Open URL: [React Data Grid: Cell Renderer (ag-grid.com)](https://www.ag-grid.com/react-data-grid/component-cell-renderer/)
2. Navigate to table under Cell Renderer Example
3. Navigate to Push for Total button and invoke it using keyboard.

**Current behavior**
"Push for total" button available in Cell renderer example table is not actionable using keyboard. With mouse status message appears but with keyboard no action is performed.

**Expected behavior**
Push for total button should be actionable using keyboard as well.

**Please tell us about your environment:**
OS: Windows 11
OS version: 22H2 (OS Build 22621.2134)
Edge Version: 116.0.1938.69 (Official build) (64-bit)

Attachments:

https://github.com/ag-grid/ag-grid/assets/93735775/94fb28a5-cf20-4f25-bad2-9011016533f8

**Comment by AG-Zoheil** [comment]
Hi @msftedad,

Thanks for raising this. Please have a look at the documentation on the bottom of the page: https://www.ag-grid.com/react-data-grid/component-cell-renderer/#cell-renderer-keyboard-navigation.

This should explain the workings of the specific scenario you've described and help you achieve your desired outcome.

Kind regards,
Zoheil

**Comment by msftedad** [comment]
Hi @AG-Zohei, we have received a comment from PO team- I looked at it, but it's not the same case. In the given case below, they put the button directly on the cell. Our buttons are inside an expanded cell, and there is no example for that in the given link. Can you please look into this? Thanks

**Comment by AG-Zoheil** [comment]
Hi @msftedad,

You can see the example you referred to in your initial post implemented here: https://plnkr.co/edit/tuzthoPIcP1y52RF?open=main.js.

Note you can navigate to the cell in question with the TAB key and activate it using ENTER.

I hope that helps.

Kind regards,
Zoheil
