### ISSUE TITLE
How to suppress auto sorting after cell edit

### ISSUE THREAD

**Issue by binishmp** [ag-grid/ag-grid#7012]
By default once we applied sort in cell while editing the cell value the table will auto sort based on the new value. 

How to prevent this behavior. I would like to keep the row in same index even if value has changed during edit. 

Is there any default option or method available to achieve this?

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
