### ISSUE TITLE
Square boxes are being displayed behind the ag grid icons

### ISSUE THREAD

**Issue by srinathmerugu** [ag-grid/ag-grid#7025]
**I'm submitting a issue where ag grid check boxes, sort and menu icons are displaying as squareboxes. I'm attaching my stackblitz example here:**
https://stackblitz.com/edit/angular-a2jib5?file=src%2Fapp%2Fapp.component.html

**Providing a Reproducible Scenario**
-> I'm using Angular v15.2.9 and ag-grid version v30.1.0, I'm trying to display data on the grid with some records. 
-> I don't want to use any of the ag-grid themes and my icons are displayed properly in ag grid v25, after upgrading to v30. I'm facing this square boxes issue behind every icon.
-> When i click on header sort, my icon is being displayed along with a square box and same with the column menus as well. 
-> My column menu dropdown is also not displaying properly, but the functionality is working as expected.

**Current behavior**
Check box, sort icon, drag icon, column menu and dropdown is not displaying properly and having square boxes. Attaching images below
![image](https://github.com/ag-grid/ag-grid/assets/62550907/aed3f49d-59d8-44ff-a024-931311e70841)
![image](https://github.com/ag-grid/ag-grid/assets/62550907/600a2278-77ed-485e-868e-d1ce5ddf1796)
![image](https://github.com/ag-grid/ag-grid/assets/62550907/c58db1b1-19d0-4d45-9885-499e462c39a5)

**Expected behavior**
Ag-Grid icons should display properly as displayed in ag grid docs examples

**Please tell us about your environment:**
Angular: 15.2.9
Ag grid: 30.1.0

* **AG Grid version:** 
30.1.0

* **Browser:**
Google Chrome

* **Language:**
Typescript: 4.9.5

**Comment by StephenCooper** [comment]
Hi @srinathmerugu,

I can reproduce the issue by not providing Icon fonts to the grid. So it looks like you will need to follow the steps for using custom icons as found here: https://ag-grid.com/angular-data-grid/custom-icons/

This has likely changed since v25 and so will need updating to the new approach.

**Comment by naushadidrisi** [comment]
If using custom theme and this issue of square boxes are coming , then just set this css to set off font css which come after new ag grid update.

.ag-theme-custom {
    --ag-icon-font-display: none;
}

This will fix the issue.
