### ISSUE TITLE
Pagination showing html in dom even if no pagination enabled

### ISSUE THREAD

**Issue by evaldas-kalasunas** [ag-grid/ag-grid#7026]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In our project we use AgGrid 29.3.5 version of grid, We have added our wrapper to the grid for some default options. 
However, we are not enabling pagination anywhere not in the grid, nor in the wrapper. Problem is, If you inspect the generated DOM tree, you can see some pagination section is still being generated (see image) although it's marked as unselectable & hidden. 

This is a problem because for example if we use snapshot's for some tests and use mount, it checks that pagination html, which sometimes re-generates some id and causes snapshot to fail. There is a workaround to use shallow for snapshot part, but that's workaround.

![image (1)](https://github.com/ag-grid/ag-grid/assets/20013928/6f215abe-ef8f-47e3-8b3d-0629f3991c17)

**Expected behavior**
I would expect no html to be generated for pagination part if we have that disabled, or rather if we aren't even touching pagination properties at all.

**Please tell us about your environment:**
N/A

* **AG Grid version:** X.X.X
29.3.5 - due to project specifics we may not be able to upgrade to newer version soon (especially not in a major version)

* **Browser:**
We only support chrome and it's seen there.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React with typescript.

**Comment by AG-Zoheil** [comment]
Hi @evaldas-kalasunas,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by evaldas-kalasunas** [comment]
Sure, you can see in here even for example:  <br>
Plunker taken directly from setFilter example: https://plnkr.co/edit/?open=index.jsx&preview <br>
https://ag-grid.com/archive/29.3.5/react-data-grid/filter-set/
(The very first sample)

If you inspect and navigate below AgGrid you can see there is  ag-paging-panel  when there is no pagination enabled.

Nothing was changed from the plunker.

![image](https://github.com/ag-grid/ag-grid/assets/20013928/534ba26c-611f-40f5-bd85-729f49af66df)

**Comment by AG-Zoheil** [comment]
Hello @evaldas-kalasunas,

Thank you for the suggestion.

Currently these elements get tagged as ag-hidden when not in use. However, we agree it would be a valuable addition to the product to actually remove them and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-2313**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by intelisofts** [comment]
Although rendering reasonable size of additional DOM shouldn't be big problem. However, element nesting is an issue which can cause accessibility issues. 
**Rendering div in a span**
<img width="1194" alt="Screenshot 2023-11-03 at 17 55 34" src="https://github.com/ag-grid/ag-grid/assets/18719950/f36fcdce-6183-49eb-9807-af7ab0405893">

should i submit additional issue for your consideration ?

**Comment by AG-Zoheil** [comment]
Hi @intelisofts,

Yes, please open a new issue with a plunker to replicate the error you are describing. This will help other users refer back to it upon resolution and allow us to process it more efficiently too.

Thank you!
