### ISSUE TITLE
Non-default sorting causes calling getRows twice

### ISSUE THREAD

**Issue by nikriaz** [ag-grid/ag-grid#7029]
Version 30.1, Community Edition, Infinite model.

When non-default sorting is enabled, calling `purgeInfiniteCache()` causes calling getRows twice. First call contains correct current sorting model, and the second call contains two models: first model is the same as in the first call, and second model is default sorting model. This, in turn, causes duplicated column names for the columns appeared in these two concurrent models.

Have no idea what is general purpose of having two sorting models in one call, so have no clue for a root cause. 

Sorry, no time for further investigation and building minimal repo now, todo item. Solved so far by defaulting sorting on `purgeInfiniteCache()` call. This is certainly is not nice as user loses chosen sorting. 

Maybe you have something in your mind to advise right away. 

_Originally posted by @nikriaz in https://github.com/ag-grid/ag-grid/issues/6274#issuecomment-1712826648_

**Comment by nikriaz** [comment]
Okay, solved by removing default sort what was set on non-index column. 

This default sort causes multiple issues with dataSource, not only on purging cache, also on initial scrolling etc. Removing default sort from columnDefs seems solved all problems.

**Comment by AG-Zoheil** [comment]
Hi @nikriaz,

Thank you for looking into this.

If you are still having issues we'd be happy to investigate this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by ishaiavrahami** [comment]
What was the solution to this?

**Comment by nikriaz** [comment]
> solved by removing default sort what was set on non-index column.

**Comment by dhruvp-dewsolutions** [comment]
Hi,

I’m facing the same issue with Infinite Row Model using pagination.

I have sortable columns (sortable: true) but no default sort on them.

Some column has sortable: true; others have no default sort.

Page size changed causes getRows to be called twice, resulting in duplicate API calls.
