### ISSUE TITLE
Set filter model on useEffect with animateRows settings causing app crush

### ISSUE THREAD

**Issue by yulianabaryskina** [ag-grid/ag-grid#7032]
Hi! I've encountered the error after updating to 30.1.0.
`Cannot read properties of null (reading 'toString')`
This error cause app crush.

I had a chance to reproduce it on one of the examples under this section:
https://www.ag-grid.com/react-data-grid/filter-api/#example-get--set-all-filter-models

1. Turn on the rows animation (add `animateRows` attribute to AgGridReact component).
2. Import `useEffect`
3. Add the following code:
```
useEffect(() => {
    if (!rowData || !gridRef.current.api) {
      return;
    }
    const hardcodedFilter = {
      country: {
        type: 'set',
        values: ['Australia'],
      },
    };
    gridRef.current.api.setFilterModel(hardcodedFilter);
  }, [rowData])
```
(as I need inside the app to set up saved filters for each user)

Interesting thing: if I turn off the animation - everything works. Or if I remove the useEffect, then it also works. But in combination it causes the error.

**Comment by StephenCooper** [comment]
Hi @yulianabaryskina ,

Thanks for reporting with a test case. I can confirm that we have resolved this issue and it will be released in our next release due before the end of the month. You are correct in that it is linked to animating of rows and was introduced in 30.1. 

<hr>

We have added this bug to our backlog and we are tracking it with the following reference: AG-9276
 
This item will be in the next release visible by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).
