### ISSUE TITLE
[30.1.0] ISelectCellEditorParams no longer extends ICellEditorParams

### ISSUE THREAD

**Issue by halljus** [ag-grid/ag-grid#7036]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

https://plnkr.co/edit/APM6IhCX5OEgbn6p?open=index.tsx (see `MySelectEditor` implementation)

**Current behavior**

The `ISelectCellEditorParams` interface (params passed to a custom select cell editor) no longer includes a `value` property, but the `value` property is present (observable at runtime). This behavior began in ag-grid v30.1.0 due to commit [60df5e5](https://github.com/ag-grid/ag-grid/commit/60df5e5b4fe0bc4b50aa30a15127f646a19c6828#diff-2dbf1a16dfbd84f8cd13972250929154b678c4a2dd70c603f3e89952ec8c49bd) for AG-2655 (cc @gportela85) changing the `ISelectCellEditorParams` interface so that it no longer extends the `ICellEditorParams` interface. Was this intentional?

**Expected behavior**

Types would be accurate, one way or the other - either include all valid properties in `ISelectCellEditorParams` or stop passing properties that aren't included in the type definition.

**Please tell us about your environment:**

* **AG Grid version:** 30.1.0

* **Browser:** N/A (all)

* **Language:** TypeScript 5.2

**Comment by AG-Zoheil** [comment]
Hi @halljus,

The `ISelectCellEditorParams` is about what params can go in the cellEditorParams config. During the construction of the editor, our users will receive a union of `ISelectCellEditorParams` & `ICellEditorParams`. 

This used to be a problem that we fixed because users thought they could override any properties of `ICellEditorParams` inside the cellEditorParams object and that wasn't true.

Kind regards,
Zoheil

**Comment by halljus** [comment]
> During the construction of the editor, our users will receive a union of `ISelectCellEditorParams` & `ICellEditorParams`.

This was the missing piece, thanks for clarifying. I might've missed it, but I didn't see anything in the documentation indicating this was the case.
