### ISSUE TITLE
Cells with non-interactive elements are in tabbing order and focusable

### ISSUE THREAD

**Issue by bw120** [ag-grid/ag-grid#7043]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.

Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When a user tabs through a grid, all the cells receive focus and not just the cells with interactive elements. Even the cells with only non-interactive contents like text receive focus. I tried using `suppressCellFocus`. However, that is a global option that makes it so that tabbing bypasses the table body all together including the interactive elements like links and checkboxes.

**Expected behavior**
Typically when trying to setup for ADA, only the interactive elements should receive focus. When the non-interactive elements receive focus it can confuse keyboard users and make them think that it is interactive.

When tabbing through the grid, the user should go through the links, buttons, checkboxes and other interactive elements only.

**Please tell us about your environment:**
MacOS, React 18.2.0, Node 18.17.0

* **AG Grid version:** X.X.X
"ag-grid-react": "30.1.0"

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 5.1.6

**Comment by AG-Zoheil** [comment]
Hi @bw120,

Thanks for bringing this to our attention.

The keyboard focus should not skip empty and/or non-interactive cells. The user should be able to use the tab/arrow keys to reach any cell in the table, whether the cell has content or not. 
 
The behavior you requested is not covered by the accessibility guidelines. As per the guidelines a user would expect to focus a grid cell even if it's empty and/or cannot be edited, copied, pasted into, etc. 
 
What I can suggest for your specific use case is this property: https://www.ag-grid.com/javascript-data-grid/keyboard-navigation/#reference-nav-tabToNextCell.

Kind regards,
Zoheil
