### ISSUE TITLE
Stacked column chart negative number issue (bug introduced in v8.0.5)

### ISSUE THREAD

**Issue by MattW92** [ag-grid/ag-grid#7048]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios (plunker)

Found the bug to have been introduced in v8.0.5 Downgrading to v8 makes it work as expected

v8 working plunker:
https://plnkr.co/edit/rLso5Uc5Gv7ToYIe?open=index.html&preview

v8.0.5 broken:
https://plnkr.co/edit/vwUHlt6phQjARbLq?open=index.html&preview

**Current behavior**
The negative number is stacked on top of the positive column (instead of displaying below it like it used to when we had yKeys
![image](https://github.com/ag-grid/ag-grid/assets/2569357/4478dcd9-3427-47eb-96a1-6e51aa69f4a9)

Going through the versions on plunker you can see the issue pops up between v8 and v8.0.5

**Expected behavior**
notice how the womenDelta is now at the bottom where it's negative as expected
![image](https://github.com/ag-grid/ag-grid/assets/2569357/a6b3940e-80b8-4786-aba4-d1a46ed5f80b)

**Please tell us about your environment:**
Windows, PyCharm, Yarn

* **AG Grid version:** 30.1.0

It's an issue that was introduced with the latest release, I'm downgrading now back to charts v8 to fix the issue

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hello @MattW92,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug. We have already identified this issue as a bug (reference: AG-9157) and worked on fixing it. It will be released in our next version of charts.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
