### ISSUE TITLE
Cell Renderer throwing error for <script setup> Component in Vue 3.2

### ISSUE THREAD

**Issue by heartcoreapex** [ag-grid/ag-grid#7049]

**Comment by AG-Zoheil** [comment]
Hi @heartcoreapex,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by heartcoreapex** [comment]
Hi @AG-Zoheil 

Is there a typescript base that I can use for plunker?
I attempted to do it myself it won't load at all

**Comment by AG-Zoheil** [comment]
Hi @heartcoreapex,

Yes of course. In our JS examples, if you click on the "Code" tab you will have an option to change from JavaScript to TypeScript at the bottom left.
