### ISSUE TITLE
Date filter has weird naming

### ISSUE THREAD

**Issue by tomerslice** [ag-grid/ag-grid#7050]
**I'm submitting a ...
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
You can take a look at the docs:
https://www.ag-grid.com/javascript-data-grid/filter-date/

**Current behavior**
When clicking on a filter of dates. The fields are numeric:
Equals
Greater than
Less than
Not equal
In range

**Expected behavior**
Equals → Is
Greater than → After
Less than → Before
Not equal → Is not
In range → Between

**Please tell us about your environment:**
Operating system: Mac
IDE: Visual studio, JetBrains
package manager: pnpm

* **AG Grid version:** 29.1.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

* **Language:** TypeScript 5.0.0 | ES7

**Comment by AG-Zoheil** [comment]
Hi @tomerslice,

Thanks for raising this. You can configure the naming to your preference via [Localisation](https://www.ag-grid.com/javascript-data-grid/localisation/).

Kind regards,
Zoheil
