### ISSUE TITLE
DetailRowAutoHeight is not working when a chrome extension is installed.

### ISSUE THREAD

**Issue by madhupprasad26** [ag-grid/ag-grid#7052]
I'm submitting a ...

[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

Current behavior:
**detailRowAutoHeight** is not working when [Demandbase (ABX)](https://chrome.google.com/webstore/detail/demandbase-abx-cloud/hnfijcggbbnhciandggikibemjjjpoaf/related) is installed

Expected behavior:
**detailRowAutoHeight** should work when [Demandbase (ABX)](https://chrome.google.com/webstore/detail/demandbase-abx-cloud/hnfijcggbbnhciandggikibemjjjpoaf/related) is installed

Providing a Reproducible Scenario:
Step 1: Install the extension.
Step 2: Open https://www.ag-grid.com/examples/master-detail-height/auto-height/packages/reactFunctional/index.html

AG Grid version: 27.1.0

Browser:
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'

Language: Javascript | React

**Comment by AG-Zoheil** [comment]
Hi @madhupprasad26,

Thank you for submitting this on GitHub.

The Demandbase extension is interfering with the page content, preventing AG Grid from rendering itself. This is an unintended side effect and an issue that needs to be raised with Demandbase, as they need to debug the plugin code and identify the change they need to make to resolve this.

Kind regards,
Zoheil
