### ISSUE TITLE
cellDataType: false ignored when overriding built in types in 30.1

### ISSUE THREAD

**Issue by nealeu** [ag-grid/ag-grid#7056]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
```
See https://plnkr.co/edit/X7HCwHo5zRNFa29k?open=main.js

The "Has Gold" column is boolean and we want all boolean columns formatted with a tick string, not a checkbox component.

- In 29.x this worked.
- In 30.x this should work by adding `cellDataType: false` which is present.
- The workaround that gives us the behaviour from 29.x is to add a null `valueGetter` (which incidentally isn't easy for nested paths e.g. `some.deeper.field` because there is no function available to access the original field value).

**Comment by AG-Zoheil** [comment]
Hi @nealeu,

Thanks for raising this. You need to set `cellDataType=false` in the either the **columnDefs** or **defaultColDef**.

See this example: https://plnkr.co/edit/WvkrqQ1Yb2AXoG7h?open=main.js

I hope that helps.

Kind regards,

**Comment by nealeu** [comment]
Hi @AG-Zoheil,

Setting it in `columnDefs` each time doesn't work for us as it we want this as a default for `boolean`.

If we set `cellDataType: false` in `defaultColDef`, then I understand that this would revert fully to the behaviour in 29.x.  This seems acceptable in the short term, but might become problematic later if we want to use that feature for other field types, and I suspect we'd have to enable it on a case by case basis in `columnDefs`.
Do you intend to support/fix setting `cellDataType` in `columnTypes`?

**Comment by AG-Zoheil** [comment]
Hi @nealeu,

My pleasure.

We don't have any plans to allow setting **cellDataType** in **columnTypes**, however there is another approach that should work just as well for you.

By utilizing and providing your [**custom cell data types**](https://ag-grid.com/javascript-data-grid/cell-data-types/#providing-custom-cell-data-types) you can use your desired boolean cellDataType in the columnTypes without having to set it individually in each of the columnDefs or the defaultColDef causing potential clashes with other columns.

See this example: https://plnkr.co/edit/Wme8PlsIXWaV9zgK?open=main.js

Kind regards,
Zoheil

**Comment by nealeu** [comment]
Thanks.  I'll check into that approach.

FYI. cellDataType is available in the Typescript, so this change would be helpful for people not accidentally using it:

```typescript
    columnTypes?: {
        [key: string]: Omit<ColDef<TData>, 'cellDataType'>;
    };
```
