### ISSUE TITLE
agRichSelectCellEditor displaying &nbsp; instead of blank option

### ISSUE THREAD

**Issue by labbedou** [ag-grid/ag-grid#7058]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When using the agRichSelectCellEditor with a value of empty string "" or a value of null,  the string literal "& nbsp;" is displayed for that option in the dropdown.

**Expected behavior**

When using the agRichSelectCellEditor with a value of empty string ("") a blank option is included in the dropdown.

**Please tell us about your environment:**

Windows 11 Enterprise
Chrome 116.0.5845.188

* **AG Grid version:** 30,1

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

Reproducible Scenario:

Create a column using the agRichSelectCellEditor, which includes empty string as a value.

```
{
  colId: "test",
  field: "test",
  cellEditor: "agRichSelectCellEditor",
  cellEditorParams: {
	  values: ["", "A", "B", "C", "D", "E"],
  },
  cellEditorPopup: true,
  editable: true,
  headerName: "Test",
  width: 145,
},
```
" & nbsp;" is displayed instead of a blank option in the dropdown. However clicking on the & nbsp; option, results in a blank/empty cell after the select is completed.

![image](https://github.com/ag-grid/ag-grid/assets/93353174/adbde916-786f-4e36-b338-af6c63f59041)

**Comment by AG-Zoheil** [comment]
Hi @labbedou,

Thank you for raising this.

As part of our next release (end of this month) we are making some enhancements to our `agRichSelectEditor`. I have checked the issue you've raised against those changes and they are fixed as part of them.

Therefore I'm pleased to let you know that the issue you are experiencing should be resolved with our next release (_30.2.0_).

The best way to track when the latest version gets released is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-).

Kind regards,
Zoheil
