### ISSUE TITLE
[Bug] Floating filter's `class` is `function () { [native code] }`

### ISSUE THREAD

**Issue by AlexErrant** [ag-grid/ag-grid#7059]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
In `ag-grid-solid`, floating filters have a class of `function () { [native code] }`. I believe it should be something like `ag-floating-filter-body`.

Minimal example: https://stackblitz.com/edit/solidjs-template-1in569?file=src%2FApp.tsx

![image](https://github.com/ag-grid/ag-grid/assets/109672176/b618d061-7db2-40b6-a96a-326ecf983335)

(In actuality all I want is a 100% width floating filter input. I'm believe this incorrect class is futzing things up; replacing `function () { [native code] }` with `ag-floating-filter-body` in the debug tools gets me the width I want.)

**Expected behavior**
Not a stringified function :)

* **AG Grid version:** 30.1.0

* **Browser:**  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

* **Language:** All

Related: https://github.com/ag-grid/ag-grid/issues/6492

**Comment by AlexErrant** [comment]
Uh, actually I'm seeing a lot of `function () { [native code] }` in the raw HTML in the above stackblitz:

![image](https://github.com/ag-grid/ag-grid/assets/109672176/90dabdc0-bec0-403f-a3ec-86d69c0d69b4)

Might be worth going through the CSS of the solid adapter and make sure that all the signals are called.

**Comment by AlexErrant** [comment]
Ah, this is why:

https://github.com/ag-grid/ag-grid/blob/e063a55431f33870571d09d32cda4316ac9deae0/grid-packages/ag-grid-solid/src/grid/header/headerFilterCellComp.tsx#L8

https://github.com/ag-grid/ag-grid/blob/e063a55431f33870571d09d32cda4316ac9deae0/grid-packages/ag-grid-solid/src/grid/header/headerFilterCellComp.tsx#L67-L72

You're calling `.toString()` on a signal, which is really a function. Try:

```diff
-    const getCssClassesString = createMemo( ()=> 'ag-header-cell ag-floating-filter ' + getCssClasses.toString() );
+    const getCssClassesString = createMemo( ()=> 'ag-header-cell ag-floating-filter ' + getCssClasses() );
```

**Comment by AlexErrant** [comment]
Also, IMO `createMemo` is unnecessary and actually _reduces_ perf (to a small degree).

To [quote Ryan](https://dev.to/ryansolid/thinking-granular-how-is-solidjs-so-performant-4g37):

> What if we just(notice we removed createMemo)... You guessed it. Effectively the same thing and we have one less computation. Now a computation means we don't re-create the string fullName unless firstName or lastName change but unless used elsewhere in another computation that has other dependencies it won't run again anyway. And even so, is creating that string that expensive? No.

In Solid, you only need to memorize _expensive_ operations. String creation is not expensive. (Solid doesn't rerender elements, so you don't need to memorize to avoid that.) The memo introduces additional complexity/memory that IMO is unnecessary. I don't know React, but gonna assume that you do, so here's [another blog](https://www.toptal.com/react/solidjs-vs-react):

> React depends on memoization for its applications to render quickly. In contrast, because of its optimized change tracking and DOM usage, SolidJS rarely requires explicit memoization. For extreme edge cases in which component prop changes do not entail a rendering update, SolidJS manages memoization through a single [method called createMemo](https://www.solidjs.com/tutorial/introduction_memos).

Not sure how much I trust this "Verified Expert in Engineering", but [the solid docs](https://docs.solidjs.com/references/api-reference/basic-reactivity/createMemo) imply this in their example:

> `const value = createMemo(() => computeExpensiveValue(a(), b()));`

So really, you could make

```diff
-    const getCssClassesString = createMemo( ()=> 'ag-header-cell ag-floating-filter ' + getCssClasses() );
+    const getCssClassesString = ()=> 'ag-header-cell ag-floating-filter ' + getCssClasses();
```

**Comment by AlexErrant** [comment]
I can PR these changes if you want... not sure how the legality of this kinda thing works but I don't really care. I relinquish all rights to my changes blah blah blah. Also, gonna vouch for this PR https://github.com/ag-grid/ag-grid/pull/7030 since David is a Community Manager for Solid.

**Comment by AlexErrant** [comment]
Oops - I just realized ` const [getCssClasses, setCssClasses] = createSignal<CssClasses>(new CssClasses()); ` is a _class_ which in turn has overridden `.toString()`. This... kinda renders my previous suggestions moot - I don't understand why `function () { [native code] }` is appearing. I will express uncertainty that passing a class to a signal preserves reactivity - I've not seen that done before. However, this doesn't really matter because Solid supports [`classList`](https://www.solidjs.com/docs/latest#classlist):

> the classList pseudo-attribute lets you specify an object, where each key is a class and the value is treated as a boolean representing whether to include that class.

This is basically the underlying object in `CssClasses`, so there's no need to abstract it away into a class. You can either create a classList object as a signal, or if you want better perf, as a [store](https://www.solidjs.com/docs/latest#createstore). This latter function will update _only_ the CSS class that changes, so the browser only sees the one CSS class change. Though maybe classList does diffing so a signal would also work - IDK.

**Comment by StephenCooper** [comment]
Hi Alex, 

Thanks for reporting this. I can see that the issue is not calling the signal, i.e missing `()`. I will do a sweep of the `ag-grid-solid` package to try and catch other instances of this.

**Comment by StephenCooper** [comment]
Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug and will fix in the next release. 

We have added this bug to our backlog and we are tracking it with the following reference:
AG-9347
