### ISSUE TITLE
Inconsistent column width values in ag-Grid with flex set to 1

### ISSUE THREAD

**Issue by ramshamushtaq** [ag-grid/ag-grid#7062]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Issue and reproducible scenario**
I'm trying to capture the width of a cell in a specific column in ag-grid, so that I can truncate the text (file name) within. This column has the property of flex set to 1. When I print the params object in cell renderer method I can see that the value of actualWidth is 396px **(this is the expected value),** however when I pass this value to a function or simply console it out I see 200px **(current behavior).** I also noticed that removing the flex property from the column returns 200px. But if I set a width property set to 396px then I get back 396px.

_For columns with the a width property I get back the correct actualWidth e.g. col 5 returns 150px_

My table has 8 columns with the following widths:
- col 0: width: width: 20
- col 1 (file name): flex: 1 // issue capturing the actual width
- col 2: width: 200px
- col 3: width: 200px
- col 4: flex: 1 // same issue
- col 5: width: 150px
- col 6: width: 150px
- col 7: width: 40px

Below are all the ways I tried to capture the width of the cell:

1. params.eGridCell.clientWidth;
2. params.column.actualWidth;
3. const fileName = document.querySelector('.file-name'); const width = fileName.offsetWidth;
4. const colWidth = document.getElementsByClassName('file-name');
5. const colWidth = document.querySelector("div[col-id='File Name']");
     colWidth.item(0);
     colWidth[0].clientWidth;
6. let fileName = document.querySelector('.file-name');
     let width = fileName.offsetWidth;

* **AG Grid version:** 28.0.0
* * **AG Grid enterprise:** 28.0.2
* * **AG Grid community:** 28.0.2

* **Browser:** Chrome

* **Language:** ES6/7

**Comment by AG-Zoheil** [comment]
Hi @ramshamushtaq,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by ramshamushtaq** [comment]
Hi @AG-Zoheil, here's a Plunker example for you to investigate:
[https://plnkr.co/edit/TTHE6OiC1oosPHSM?open=index.jsx](https://plnkr.co/edit/TTHE6OiC1oosPHSM?open=index.jsx)

One thing to note is that the bug only occurs on smaller screens. Please see the attached gif and images:

- Here's an example of inconsistent widths in Plunker: ![Screen Shot 2023-09-18 at 7 55 33 AM](https://github.com/ag-grid/ag-grid/assets/22181129/ea5fba77-e795-4659-b4a4-b08d83c2c05c)
- Below is a screen shot and gif from my actual code: 
<img width="1325" alt="Screen Shot 2023-09-14 at 6 32 48 AM" src="https://github.com/ag-grid/ag-grid/assets/22181129/7caef859-91ac-44b7-9a32-7c835b8fa7d8">


![Error_gif](https://github-production-user-asset-6210df.s3.amazonaws.com/22181129/268731803-a5908b68-6fc9-48c6-912d-07188e87ea21.gif)
