### ISSUE TITLE
WIth angular 14 and Ag Grid 28. Scroll bar is not visible on IPAD even after adding 		[alwaysShowHorizontalScroll]="true"     [alwaysShowVerticalScroll]="true"

### ISSUE THREAD

**Issue by zshah-antuit** [ag-grid/ag-grid#7063]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by zshah-antuit** [comment]
Tried the below as well, this fixes the mac browswer, but IPAD scroll is not visible. If from IPAD I open AG GRID DEMO the scroll bars are not visible there as well. Can you please help. We are a paid CLIENT

.ag-body-horizontal-scroll.ag-scrollbar-invisible.ag-apple-scrollbar {
	display: flex !important;
	overflow-x: visible!important;
    overflow-y: hidden!important;
	max-height: 20px !important;
    min-height: 15px !important;
    height: 15px !important;
}

.ag-body-horizontal-scroll.ag-apple-scrollbar {
    overflow-x: visible!important;
    overflow-y: hidden!important;
	max-height: 20px !important;
    min-height: 15px !important;
    height: 15px !important;
}

**Comment by AG-Zoheil** [comment]
Hi @zshah-antuit,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage to contact us via our [support portal](https://ag-grid.zendesk.com/) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Regarding your question above, can you please confirm what OS version you are using on the ipad? In newer versions there is a global OS setting "Show scrollbar" which would override AG Grid. You need to set this to always if you wish to show the scrollbar at all times.

Kind regards,
Zoheil

**Comment by zshah-antuit** [comment]
HI I am using IOS 16.3 on my iPad. I cannot find any place which lets me set the scrollbar to true.


[Logo  Description automatically generated]
Zubin Shah
UI Lead, COE
antuit.ai
Now part of Zebra Technologies

T: +1 7329086605
***@***.******@***.***>
www.zebra.com<http://www.zebra.com/>
www.antuit.ai<http://www.antuit.ai>



From: AG-Zoheil ***@***.***>
Date: Monday, September 18, 2023 at 5:29 AM
To: ag-grid/ag-grid ***@***.***>
Cc: Shah, Zubin ***@***.***>, Mention ***@***.***>
Subject: Re: [ag-grid/ag-grid] WIth angular 14 and Ag Grid 28. Scroll bar is not visible on IPAD even after adding [alwaysShowHorizontalScroll]="true" [alwaysShowVerticalScroll]="true" (Issue #7063)
Hi @zshah-antuit, Thank you for submitting this on Github. As you've mentioned you are an enterprise client I would encourage to contact us via our support portal for issues or suggestions. That would be the quickest and most efficient route
ZjQcmQRYFpfptBannerStart
External Sender
This message came from outside our organization. Please use caution before acting on the message.
ZjQcmQRYFpfptBannerEnd

Hi @zshah-antuit<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zshah-2Dantuit&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=tBDamHOIXTvN927lk5243GVsqnM64QGBPnQGZmlHY8A&m=fiDQpiiHKRqPJYgl4BT1CTZM9c4c2gQsHFqCmgL6vCL5ad_1dB5xmY8iLVaY1T3D&s=1r9Y7t6cYxxP8PQSCi5MXdEf-DSGEdNdJBbka-rbPos&e=>,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage to contact us via our support portal<https://urldefense.proofpoint.com/v2/url?u=https-3A__ag-2Dgrid.zendesk.com_&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=tBDamHOIXTvN927lk5243GVsqnM64QGBPnQGZmlHY8A&m=fiDQpiiHKRqPJYgl4BT1CTZM9c4c2gQsHFqCmgL6vCL5ad_1dB5xmY8iLVaY1T3D&s=xcMmIBK-A8rLLfV77UjlLvhQs7ZVxxsyBCh_cQgIhPg&e=> for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Regarding your question above, can you please confirm what OS version you are using on the ipad? In newer versions there is a global OS setting "Show scrollbar" which would override AG Grid. You need to set this to always if you wish to show the scrollbar at all times.

Kind regards,
Zoheil

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ag-2Dgrid_ag-2Dgrid_issues_7063-23issuecomment-2D1723052266&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=tBDamHOIXTvN927lk5243GVsqnM64QGBPnQGZmlHY8A&m=fiDQpiiHKRqPJYgl4BT1CTZM9c4c2gQsHFqCmgL6vCL5ad_1dB5xmY8iLVaY1T3D&s=DDAhDDRxIm9_QK2aCOvfMc9X4K0v0VhT883PCUcnaIg&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYQMCV273LX3QHYDZBKXP4LX3AH65ANCNFSM6AAAAAA42BXW4Y&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=tBDamHOIXTvN927lk5243GVsqnM64QGBPnQGZmlHY8A&m=fiDQpiiHKRqPJYgl4BT1CTZM9c4c2gQsHFqCmgL6vCL5ad_1dB5xmY8iLVaY1T3D&s=22QkMKULNsyFcG6dFEj7LC3uuYoJLM7jk34B7k_Kr1c&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


________________________________
- CONFIDENTIAL-

This email and any files transmitted with it are confidential, and may also be legally privileged. If you are not the intended recipient, you may not review, use, copy, or distribute this message. If you receive this email in error, please notify the sender immediately by reply email and then delete this email.
