### ISSUE TITLE
cellRenderer issue with Vue's defineAsyncComponent

### ISSUE THREAD

**Issue by nndnha** [ag-grid/ag-grid#7064]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```
Reproduce link: https://stackblitz.com/edit/vitejs-vite-i4dupe?file=src%2FApp.vue&terminal=dev

**Current behavior**

The Price column is not rendered when the page first loads

**Expected behavior**

 Price column should render normally, like the Model column.

**Comment by AG-Zoheil** [comment]
Hi @nndnha,

Thank you for submitting this on GitHub.

I'm afraid we don't support this - the component needs to be available to use up front.

Kind regards,
Zoheil

**Comment by nndnha** [comment]
@AG-Zoheil In a Vue app, defineAsyncComponent is used for code splitting to reduce the application bundle into multiple smaller chunks, and this is a very important function. Without the support of defineAsyncComponent, it becomes very difficult to use AG Grid in a Vue app. So sad to hear that.

**Comment by AG-Zoheil** [comment]
Thank you for the suggestion @nndnha.

As mentioned currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-9363**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
