### ISSUE TITLE
Row spanning is not working during scrolling

### ISSUE THREAD

**Issue by jasveer2601** [ag-grid/ag-grid#7065]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**

Current behavior : Row spanning doesn't work after scrolling beyond visible area of the grid  

Expected behavior : Scrolling should work properly

Please tell us about your environment:

AG Grid version: 30.1.0
Browser: Chrome
Language: [React]

Plunker URL : https://plnkr.co/edit/LeS4cOp9OnvhpkAh?open=index.jsx&preview

**Comment by AG-Zoheil** [comment]
Hi @jasveer2601,

Please have a look at the limitations section in our [Row Spanning documentation](https://ag-grid.com/javascript-data-grid/row-spanning/#constraints-with-row-spanning). Spanning beyond the last row can cause scrolling issues.

In addition to that if you are looking to set the row span to a larger number than 10, please have a look at [this documentation](https://ag-grid.com/javascript-data-grid/dom-virtualisation/#row-buffer) as the rowBuffer should be adjusted in that case too for an optimal scrolling experience.

We do have a feature request to improve this area of the grid. You can track it in our pipeline with the reference **AG-2323**.

Kind regards,
Zoheil
