### ISSUE TITLE
agSelectedRowCountComponent doesn't count selected rows after setServerSideSelectionState event

### ISSUE THREAD

**Issue by vendicto** [ag-grid/ag-grid#7066]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
https://plnkr.co/edit/F8u3jMmuCJjhHadU?open=index.tsx

**Current behavior**
Shows "?" instead of a number of selected rows.

**Expected behavior**
Should show a number of selected rows.

**Please tell us about your environment:**

* **AG Grid version:** 30.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @vendicto,

Thank you for submitting this on Github.

When you have `selectAll: true` on the server side row model ALL rows are being selected including leaf nodes. As the Grid is not loading these prior to expansion of the group rows it cannot determine the number of total rows and therefore displays a question mark.

Hence this is not a bug but naturally behaviour of the server side row model.

Kind regards,
Zoheil
