### ISSUE TITLE
[style] The header-column-separator and cell-horizontal-border are not aligned.

### ISSUE THREAD

**Issue by lin52025iq** [ag-grid/ag-grid#7070]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
https://plnkr.co/edit/lAdpbAPsO9Kl1gdY?open=main.js

**Current behaviour**
Header-column-separator and cell-horizontal-border are not aligned when the right pinned of the column is set.
![image](https://github.com/ag-grid/ag-grid/assets/87741822/8cfd5250-20a3-4071-9d0c-e1003c60912f)

**Expected behavior**

The header-column-separator and cell-horizontal-border are aligned.

* **AG Grid version:** 30.1.0

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hello @lin52025iq,

Thank you for the suggestion.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-2949**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
