### ISSUE TITLE
Server-Side Data don't work well. I need help.

### ISSUE THREAD

**Issue by shvezigor** [ag-grid/ag-grid#7071]
Hello.

I have some problems in the work of Ag-grid.

I'm trying to work with Server-Side Data.
I use ag-grid on Vue.

I'm interested in how the next call to the getRows function happens, because it's called only the first time. When I scroll, nothing happens.

In the examples, I saw that in the startRow and endRow parameters, the values are initialized, but in mine they are undefined

Thansk.

https://github.com/ag-grid/ag-grid/issues/7061

Tell me why this functionality works in version 27.3.0 and it does not work in versions 28.0.0 to 30.0.0?
Version 27.3.0. we have no right to use. It turns out that we bought a non-working version?

**Comment by AG-Zoheil** [comment]
Hi @shvezigor,

I have replied in your original post. Please refrain from opening identical issues.

Many thanks,
Zoheil
