### ISSUE TITLE
Sorting of Unbalanced Rows in AG Grid Grouppings

### ISSUE THREAD

**Issue by aliraza9996** [ag-grid/ag-grid#7072]
**I'm submitting a ...**  (check one with "x")

```
[x] support request => see 'Zendesk Customer'
```

**Zendesk Customer**
I am a customer of AG Grid, but I do not have access to Zendesk right now, my manager does. 

Current behavior.
Please use the following link to reference
https://www.ag-grid.com/react-data-grid/grouping-unbalanced-groups/

**Current behavior**
The AG grid by default places the unbalanced groups at the and or maybe at the top of the grid.
I want the implementation to sort grouped rows (Unbalanced) with ungrouped rows.
For example, in the link given above from AG Grid website, I want Dublin and New York to appear in chronological order not based on their group types. 
The data should be like this 
Cork (Ungrouped)
Dublin (Ungrouped)
London (Ungrouped)
Massachusetts (Grouped)
New York (Grouped)
Opera (Ungrouped) and so on

**Please tell us about your environment:**
I am using React JS with Nestjs backend. HTTP 1.2

* **AG Grid version:** 28.1.0

* **Browser:**
Chrome/Firefox 

* **Language:** [all]

**Comment by aliraza9996** [comment]
No, unfortunately it would not. I have gone through this on the site as well.
But it still does not mix grouped and ungrouped rows.
It always places grouped rows at the bottom and if i try to add a comparator, then grouped rows can be up and down but they would not mix up with all data.

I kind of need something like this;
Cork (Ungrouped)
Dublin (Ungrouped)
London (Ungrouped)
Massachusetts (Grouped)
New York (Grouped)
Opera (Ungrouped) and so on

Thanks

**Comment by AG-Zoheil** [comment]
Thanks @aliraza9996,

Can you use the cities from our example to explain your scenario please? Massachusetts and Opera are throwing me off haha.

Please have a look at this one - https://plnkr.co/edit/54Y0OckkNhTvRNOH?open=index.jsx. I've adjusted it to include Zurich.

So you now have a mix between group and ungrouped sorted alphabetically?

**Comment by aliraza9996** [comment]
Oh no problem about the cities,
![image](https://github.com/ag-grid/ag-grid/assets/43965776/b79ed26d-36b1-4b60-aa30-2826751bdb6a)

I just want the Zurich to appear after the groups. Since I want them in alphabetical order.

**Comment by AG-Zoheil** [comment]
Thanks.

Did you have a look at the last plunker I sent, if you sort it Zurich should be at the bottom?

**Comment by aliraza9996** [comment]
I want them in this order

California (Group)
Cork
Dublin
Galway
Liverpool
London
Manchester
New York (Group)
Zurich

**Comment by aliraza9996** [comment]
> Thanks.
> 
> Did you have a look at the last plunker I sent, if you sort it Zurich should be at the bottom?

No, its not working I have been trying for a few hours. 
Grouped rows are not mixing with ungrouped data.

**Comment by AG-Zoheil** [comment]
> I want them in this order
> 
> California (Group) Cork Dublin Galway Liverpool London Manchester New York (Group) Zurich

![image](https://github.com/ag-grid/ag-grid/assets/132376454/bf3a3bbe-3e50-4e7b-8f04-02f58c7ec2c6)

**Comment by aliraza9996** [comment]
Can you post the implementation?

**Comment by AG-Zoheil** [comment]
Yes I have, it's the last plunker I sent.

Here it is again: https://plnkr.co/edit/54Y0OckkNhTvRNOH?open=index.jsx

**Comment by aliraza9996** [comment]
Thanks, this is exactly what I want.
Can you let me know how can I achieve this behavior without have the "Sortable" property true.
I want them just to be default sorted and not allow users to sort.

**Comment by AG-Zoheil** [comment]
Great, glad to hear that works.

It's best to look at our documentation [here](https://build.ag-grid.com/react-data-grid/filter-api) and define filter models for your application.

As this pertains to further customisation of your application if you do need further support I'm afraid it will have to come via our enterprise support portal.

Kind regards,
Zoheil
