### ISSUE TITLE
Rich Select Cell Editor - Width does not resize to column width if cellEditorPopup is set to True

### ISSUE THREAD

**Issue by NehalDamania** [ag-grid/ag-grid#7073]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- In recent release of AG Grid, the rich Select Cell Editor was enhanced to always resize to the column width. This does not work if cellEditorPopup is set to true. CellEditorPopup is required when certain columns are more than 1 line height.
- A plunker
- [Plunker link](https://plnkr.co/edit/sRWbuOneN0PYy6NO?open=main.js&preview)

* **AG Grid version:** 30.1

**Comment by vinaykumarP16** [comment]
Even I'm facing the same issue with CellEditorPopup

**Comment by AG-Zoheil** [comment]
Hello.

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We already have added this requirement to our backlog and we are tracking it with the following reference: [AG-2037]

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Please note that meanwhile there is a workaround for this.

You can set a css height limit for .ag-rich-select and not use the cellEditorPopup.

See the following plunker: https://plnkr.co/edit/c3vvZogRXyb9Pl4e?open=main.js

**Comment by NehalDamania** [comment]
I am not able to find AG-2037 in https://www.ag-grid.com/ag-grid-pipeline/

**Comment by AG-Zoheil** [comment]
Hi @NehalDamania,

Thanks for bringing this to our attention. A label was added incorrectly, it should show for you now.

Kind regards,
Zoheil
