### ISSUE TITLE
suppressLastEmptyLineOnPaste option removes last empty cell if only 1 column is pasted

### ISSUE THREAD

**Issue by tim-boerner** [ag-grid/ag-grid#7074]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
We are using the option **suppressLastEmptyLineOnPaste** to prevent an extra empty cell to be pasted when copy/paste data from excel. It looks like this has the side effect that when the user wants to copy data from ag grid table and selects only one column with the range selection, it removes the last cell when its empty on paste.

Copy:
![image](https://github.com/ag-grid/ag-grid/assets/28528071/069dd307-07cc-4b54-8596-4b0525e3ed7e)

Paste:
![image](https://github.com/ag-grid/ag-grid/assets/28528071/8cf021ea-b324-4c6b-a2b9-70a6dbdca914)

Of course that could also be seen as an expected behavior but is there any workaround to get both use cases working?
* paste from excel without extra empty cell
* paste form copied ag grid range selection an keep also empty cells

**Please tell us about your environment:**

* **AG Grid version:** checked at 25.1.0 and 30.1.0

* **Browser:** checked at chrome but i guess all

* **Language:** checked at Angular but i guess all

**Comment by AG-Zoheil** [comment]
Hi @tim-boerner,

Thank you for submitting this on GitHub.

When set to true the `suppressLastEmptyLineOnPaste` property setting strips the last empty value from the copied set of values before it's pasted.

The reason we have this property is that different versions of Excel handle copying differently - Excel for Windows includes a new line at the end of the copied range, while Excel for MacOS and Excel for Office 365 don't. AG-Grid's internal copy-paste mechanism works like Excel for Office 365 - it doesn't include an extra blank line at the end of the copied cell range. 

This is why depending on which version of Excel your users use, you need to choose between the following 2 options:

1) `suppressLastEmptyLineOnPaste=true`
   1.1 Copy-paste from Excel for MacOS and Excel for Office 365 to AG-Grid works fine EXCEPT when the copied cell range ends in a blank cell. If that's the case that last copied blank cell doesn't get pasted.
   1.2. Copy-pasting from AG-Grid to AG-Grid strips out the last empty cell value (when you copy a cell range of 3 cells where the last cell is a blank cell value, only 2 cells get pasted as the last empty value gets trimmed) - **this is your case**.
   1.3. Copy-paste from Excel for Windows to AG-Grid works fine.

2) No setting (default)
   2.1. Copy-paste from Excel for MacOS and Excel for Office 365 to AG-Grid works as expected
   2.2 Copy-pasting from AG-Grid to AG-Grid works as expected (when you copy 3 blank cell values, all 3 get pasted)
   2.3. Copy-paste from Excel for Windows to AG-Grid pastes an extra blank cell (so if you've copied 3 cells, 4 cells in total get pasted into AG-Grid - an extra blank cell gets pasted in the cell below the paste range, and that cell gets cleared as a result) 

I hope this describes how there's no way to cover all cases when the last cell copied is a blank cell. I would suggest choosing the value of this property depending on your predominant use case so you support the most common scenario correctly.

Kind regards,
Zoheil
