### ISSUE TITLE
Forced change detection for custom Angular cell components

### ISSUE THREAD

**Issue by maechler** [ag-grid/ag-grid#7080]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
I created a plunker to illustrate the number of change detection calls for the custom cell component gender-renderer. Just open the example and the developer tools to see the `console.log` output. There are just two cells of this type, one at the top and one off-screen at the bottom of the table. There are two buttons to navigate to the top and bottom respectively.
The output is an object containing a mapping of the component instance id to the number of `ngDoCheck` calls in that component.

https://plnkr.co/edit/a5cobAFhqLFigpBd?open=app%2Fgender-renderer.component.ts&preview

**Current behavior**
While investigating a performance issue, we found that the change detection for custom components is forced in the init function: 

https://github.com/ag-grid/ag-grid/blob/1e274ebf6032ec6d964a0cc9ba7794be72dfa29f/grid-community-modules/angular/projects/ag-grid-angular/src/lib/angularFrameworkComponentWrapper.ts#L24

In the example provided above we notice that the custom cell is checked 8 times for the initial load and 12 times when scrolled to top or bottom.

**Expected behavior**
We were wondering if it was possible to change this to [`markForCheck()`](https://angular.io/api/core/ChangeDetectorRef#markforcheck) instead or remove it altogether, since usually change detection should be handled by Angular automatically. I am however not sure if there is an edge case that makes the call to `detectChanges()` necessary?

I know that regarding the total amount of change detections this is just a small improvement, but maybe still something worth to consider. It is especially an issue when scrolling a table and a lot of components get created and destroyed again.

**AG Grid version:** 30.1.0

**Comment by AG-Zoheil** [comment]
Hello @maechler,

Thank you for the suggestion and providing the extra insights from your investigation.

This is indeed already on our radar and we have a feature request for this in our backlog with the following reference: **AG-7887** 

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by StephenCooper** [comment]
Hi @maechler,

I have updated your plunker to use the latest release 31.0.2 which now shows less renders. 

https://plnkr.co/edit/Y5xMmxfX2h0BDDdn?open=app%2Fgender-renderer.component.ts

This is the first batch of Angular improvements. I am now investigating the need for the manual detectChanges and if it does actually have a performance implication.

**Comment by maechler** [comment]
@StephenCooper Thank you, it's great to see progress on this!
