### ISSUE TITLE
Moving columns problems

### ISSUE THREAD

**Issue by SolodkovAlexander** [ag-grid/ag-grid#7083]
**I'm submitting a bug report and a support request**.
What I have: 

1. `AgGridReact `with `onColumnMoved={onColumnMoved}`. 
```
const onColumnMoved = async (event: ColumnMovedEvent) => {
        if (!event.finished) {
            return;
        }
        const columnsBeforeMoveEvent: Array<Column> | null = event.columnApi.getColumns();
        if (!columnsBeforeMoveEvent) {
            return;
        }

        //Fill map: column index before start move column -> column index after finish column moving
        const visualIndeces: Map<number, number> = new Map();
        const columnsAfterMoveEvent: Array<Column> | null = event.columnApi.getAllDisplayedColumns();
        columnsBeforeMoveEvent.forEach((columnBeforeMoveEvent: Column, columnIndexBeforeMoveEvent: number) => {
            visualIndeces.set(columnIndexBeforeMoveEvent, columnsAfterMoveEvent.findIndex(
                (columnAfterMoveEvent: Column) => columnAfterMoveEvent.getColId() === columnBeforeMoveEvent.getColId()
            ));
        });

        //Some instructions for refresh all AgGrid. 
        //So after refresh AgGrid I have right visual of first column's cells's with overloaded render.
        //First column cells have exclusive render with left icon.
        //...
    };
```
2. I overload cell render in `AgGridReact ` by `StringRenderer` component:
part of `AgGridReact`: 
```
components={{
                renderColumn: { component: StringRenderer }
            }}
```
part of `StringRenderer` (first column in table must be with icon - how I do this):
```
export const StringRenderer = (params: any) => {
    const [needRenderIconFile, setNeedRenderIconFile] = useState(false);
    useEffect(() => {
        setNeedRenderIconFile(
            (((params.columnApi as ColumnApi)
                .getColumns() as Array<Column>)
                .findIndex((col) => col.getColId() === params.column.colId) === 0)
        );
    }, [params]);

    //...
}
```

Well, what is my Scenario?
**About bug:**
I have two ordered columns: `A`, `B`.  
I'm starting move column `A`. 
I move column `A` after column `B` and then I see columns in this order: `B`, `A`. Event `onColumnMoved` processed with `event.finished = false` - so I ignore it.
I didn't stop drag column.
I drag my column out of Grid and stop drag column. I released the mouse button. And there are no expected events `onColumnMoved` with `event.finished = true`. 
I want to do some async operations when user finish moving column operation by release the mouse button. I don't want to do async operations on every column's move.

**About support request**
1. I have an excusive render: first column's render has icon. When I move my first column, it moves with his render (with icon).
I want: in moving column process if first column changed need to rerender column/cells.
Example: initial state: columns `A`, `B`. When user moved `A` after `B` I need to rerender column `B` (because it is first now, so cells must be with icons) and rerender column `A` (because it is second column, not first - no icons). How I can do it? May be I do my exclusive render wrong (detecting that the column is first)?
2. In `onColumnMoved` callback I fill map with information: previous column position - current column position. Is this way correct?

**Please tell us about your environment:**
```
OS: OS Name	Microsoft Windows 11 Pro (Version 10.0.22621 Build 22621)
IDE: VS Code
Package manager: npm (8.1.0)
```

* **AG Grid version:** 29.3.0

* **Browser:**
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.36'
```
* **Language:** TypeScript
```

**Comment by AG-Zoheil** [comment]
Hi @SolodkovAlexander,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by SolodkovAlexander** [comment]
> Hi @SolodkovAlexander,
> 
> Thank you for reporting this.
> 
> We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.
> 
> Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.
> 
> We're looking forward to your response.
> 
> Kind regards, Zoheil

So, I have done that: 
[MY FIRST PLUNKER EXAMPLE](https://plnkr.co/plunk/HaByWSQG17SDbHvV)
I am first time with plunker.. I don't know how it works (I just do CTRL+C/CTRL+V from other plunker examples). 
It is with JS/JSX (no Typescript - I don't know how/where set settings for tsx-files, may be babel...I don't know(

So, I'm waiting for my response and I want some answers on my questions =)

P.S. Using settings with `System.config` is REALLY hard..

**Comment by AG-Zoheil** [comment]
Hi @SolodkovAlexander,

Thank you for providing the plunker.

I now understand what you've reported. Please see the info box on this page to explain why no further event is fired for `onColumnMoved` when dragging the column outside of the grid: https://www.ag-grid.com/javascript-data-grid/row-dragging/#row-drag-events.

In regards to your support question, please always open separate issues so the community is able to offer their tips without getting confused by different things being discussed in one issue. It is more likely you will receive help from the community if you raise your support question in a new isolated issue, so in light of this I will close this one.

Kind regards,
Zoheil
