### ISSUE TITLE
How to trigger a re-render when `cellEditorParams` changes

### ISSUE THREAD

**Issue by cbejensen** [ag-grid/ag-grid#7089]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I'm declaring a column definition with a custom cell editor in React. I am passing a list of employees to the that custom component. However, if the list of employees is updated, I am not sure how to let the custom component know, since it's not really in React-land yet when I declare the column definition. So if `cellEditorParams` changes, my component won't know about it. How do I fix this?

I do see that custom cell **renderers** receive a [`refreshCell` function](https://www.ag-grid.com/react-data-grid/component-cell-renderer/#component-refresh), which at least allows you to trigger a re-render from inside the component. However, custom cell **editors** do not have this, and even if they did, that only helps if the custom component _knows_ the props have changed, which of course is not always the case.

**Comment by joemaylor** [comment]
I ran into a similar issue at one point, and ended up not using `cellEditorParams`, but instead passing the data into the `cellEditor` by using the [grid context object](https://www.ag-grid.com/javascript-data-grid/context/) instead.

If you can find a way to do this, then you can use the context within your custom cell editor and watch for the changes there. I use Ag Grid with Vue, so I won't do a code example, but if you need one I'm happy to 👍

**Comment by cbejensen** [comment]
@joemaylor thanks for the tip! However, not clear how using `context` is any different than using `cellEditorParams` since updating `context` wouldn't trigger a re-render either, would it? Maybe a code example would help.

In the [docs example](https://www.ag-grid.com/react-data-grid/context/#context-object-example) they have to manually call `gridOptions.api.refreshCells()`, which isn't ideal, and you could do this with `cellEditorParams` too.

**Comment by joemaylor** [comment]
Okay so in Vue, we pass context into the grid where we render it with something like this:

```vue
<script setup lang='ts'>
const gridOptions = {
  columnDefs: [ ... ],
}

const myGridContext = ref({
  foo: 'bar',
  baz: 'where',
})
</script>

<template>
  <AgGrid
    :grid-options="gridOptions"
    :context="myGridContext"
  />
</template>
```

Then in my cell editor file:
```vue
<script setup lang='ts'>
const props = defineProps<{
  params: ICellEditorParams<DataInterface, ValueType, { foo: string; baz: string; }>
}>()

// suppose value of this cell is 'foo'
const value = props.params.value

// pull context.foo from the context object.
const contextThatICareAbout = computed(() => props.params.context[value])

watch(contextThatICareAbout, value => {
  console.log('context just changed for this cell editor!', value)

  // perform your required cell refresh here
  props.params.api.refreshCells()
})
</script>

<tempalte>
  <div>Your editor component goes here</div>
</template>
```

This is the wrong framework for you and it's a bit of a contrived example but maybe it will help 🤷‍♂️

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
