### ISSUE TITLE
Card styles went missing for (custom) popup editors

### ISSUE THREAD

**Issue by Bram-Zijp** [ag-grid/ag-grid#7092]
Noticed we were missing some styles for our custom popup editors in the latest version.
I think this should have a comma in between `.ag-popup-editor` and `.ag-large-text`;

`.ag-popup-editor, .ag-large-text, .ag-autocomplete-list-popup`

https://github.com/ag-grid/ag-grid/blob/8a0d4e0e66c8c90ae613795703fbdd534e2deb12/grid-community-modules/styles/src/internal/base/parts/_grid-layout.scss#L201C29-L201C29

**Comment by AG-Zoheil** [comment]
Hi @Bram-Zijp,

Can you please provide an example where this isn't working so we can make the CSS more generic?

If we change it to `.ag-popup-editor, .ag-large-text` some editors that shouldn't have this will end up with the card settings so that wouldn't be the right approach.

Looking forward to hearing from you.

Kind regards,
Zoheil

**Comment by Bram-Zijp** [comment]
I haven't dived into the `.ag-large-text` styles and where or why they need he card. I probably should have been more clear on the change in style we discovered;
We are using the `cellEditorPopup` parameter with a custom cell editor. Docs: https://www.ag-grid.com/javascript-data-grid/component-cell-editor/#configure-popup
Specifying this parameter used to add card styles to the custom editor. Our custom editor happens to have a semi-transparent background, hence I discovered the change in style with the latest version.

I see https://www.ag-grid.com/javascript-data-grid/provided-cell-editors/#large-text-cell-editor also has the cellEditorPopup set to true in the example. Perhaps this is why the styles changed. You're probably right that my suggested change will have unwanted side effects. Perhaps you could change it back to what it initially was;
`.ag-popup-editor, .ag-autocomplete-list-popup` but I leave that open for you to decide as it requires some visual testing. It could also be that the developers of ag-grid decided that custom cell editor popups should not have the card styles. In that case we will ensure our editors will not have a transparent background.
