### ISSUE TITLE
Bug: Unable To Retain Table State in Angular AG Grid 

### ISSUE THREAD

**Issue by scriptlord** [ag-grid/ag-grid#7093]
I want a stateful table. This means I want to Change the state of the table e.g. paginate, navigate away, and then return to this table so that the Table retains the state until the browser is closed.

I have had to use local storage but the value for the page reset to zero. I tried using a shared service and had the same issue. That means the table returns to page 1. This is not the behavior I want. 

How can i achieve the behaviour i mentioned above. Can I do this with the community or enterprise. Would prefer the community though, but which one works.

Here is my code:

Template:
              <ag-grid-angular
              [rowModelType]="rowModelType"
              [defaultColDef]="defaultColDef"
               class="ag-theme-alpine my-grid-class" 
                [columnDefs]="colDefs" 
                [gridOptions]="gridOptions" 
                [paginationPageSize]="paginationPageSize"
                [animateRows]="true" 
                [rowHeight]="rowHeight" 
                [alwaysShowHorizontalScroll]="false"
                (gridReady)="onGridReady($event)"
                 [frameworkComponents]="frameworkComponents"
                 >
              </ag-grid-angular>
              
  Typescript file:
   ngOnInit() {
    if (this.pageVisitService.isPageVisited('TransactionComponent')) {
      this.isNavigatingBack = true;
      console.log('this.isNavigatingBack = true;')
    } else {
      this.pageVisitService.markPageAsVisited('TransactionComponent');
      this.isNavigatingBack = false;
      console.log('this.isNavigatingBack = false;')
    }

    console.log('Component initialized');
    this.buildSearchForm();

    this.searchForm.controls['search'].valueChanges
      .pipe(debounceTime(2000))
      .subscribe(() => {
        this.search();
      });
  }
  
    onGridReady(params: any) {
    console.log("Grid is ready");
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;

    const datasource = this.createServerSideDatasource(this.pendingTransactionService);
    this.gridApi.setServerSideDatasource(datasource);
  }
  
  createServerSideDatasource(service: PendingTransactionService): IServerSideDatasource {
  return {
    getRows: (params: IServerSideGetRowsParams) => {
      
      if (this.isApiRequestInProgress) {
        console.log('Skipping API call since one is already in progress.');
        return;
      }

      this.isApiRequestInProgress = true; 
      
      let startRow: number;

      if (this.isNavigatingBack) {
        startRow = this.tableStateService.getStartRow();
        console.log(startRow, 'this.tableStateService.getStartRow()');
      } else {
        startRow = params.request.startRow || 0;
        console.log(startRow, 'params.request.startRow');
      }

      this.tableStateService.setStartRow(startRow);
      const pageIndex = Math.floor(startRow / this.pagination.pageSize) + 1;
      this.pagination = {
        ...this.pagination,
        pageIndex,
        pageSize: this.pagination.pageSize,
      };
      console.log(this.pagination, 'pagination');

      const getPendingTransactionSub = service.getAllPendingTransactions(this.pagination)
        .subscribe({
          next: (response) => {
            this.isApiRequestInProgress = false; 
            const totalRowCount = response?.data?.totalCount;
            const rows: LoadSuccessParams = {
              rowData: response?.data?.items || [],
              rowCount: totalRowCount 
            };

            params.success(rows);
          },
          error: (error) => {
            this.isApiRequestInProgress = false; 
            console.error(error);
            params.fail();
          }
        });

      this.unsubscribe.push(getPendingTransactionSub);
    }
  };
}
[transaction-approvals-form.component.md](https://github.com/ag-grid/ag-grid/files/12739056/transaction-approvals-form.component.md)

**Comment by StephenCooper** [comment]
Hi @scriptlord,

You may be very interested in the new Grid State feature we launched in v31 today. We have designed this to enable the use case of saving and then restoring the grid much easier. 

https://ag-grid.com/angular-data-grid/grid-state/
