### ISSUE TITLE
Are Advanced Filters feature complete or WIP?

### ISSUE THREAD

**Issue by cseickel** [ag-grid/ag-grid#7106]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Set `enableAdvancedFilter={true}`

**Current behavior**

I've notice some aspects of the new Advanced Filter that seem to be incomplete and I'd like to know if there are updates related to this on the roadmap in the next few releases. This will help me decide whether I should wait for that functionality or just implement my own filtering solution now.

Here are the issues I've found in my testing:

1. There does not appear to be any solution for filtering sets of information by selecting multiple items. You would have to type out `[Field] = "XYZ" OR [field = "YZX" OR ....` if you want to replicate that. This seems to be a step backwards in functionality as compared to the column filters.
2. The above would be a little easier if we could get completion on column values when doing string equals/not equals comparisons, is that planned?
3. It appears that you are not expected to use both the advanced filter and the column filters at the same time, which makes 1 and 2 bigger issues than they would be if the two could be used together.
4. However, you kinda can use both at the same time if you use the right hand sidebar filters, but the column filters get disabled when the advanced filters are enabled. Why this inconsistency?

**Expected behavior**
I had expected the advanced filters and column filters to be complimentary and work together. I also expected to be able to easily filter on category columns using the advanced filter.

**Please tell us about your environment:**
Linux, Vite in HMR and prod build

* **AG Grid version:** 
30.2.0

* **Browser:**
Google Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 5.0.2, ES6/7

**Comment by AG-Zoheil** [comment]
Hi @cseickel,

Thank you for getting in touch.

We're glad to see you are utilising our latest feature in form of the advanced filter.

We do have plans to make improvements and enhancements to this feature. However I'd like to clarify, for the sake of transparency, that no concrete timeline has been set at this point for any further developments. As you know our grid has a vast array of features and functionality and whilst we wanted to deliver the advanced filter in the last couple of releases, we do have many other projects going on at the same time.

Some of the enhancements that we have in our backlog and may be of relevance to you are:

AG-8950 [Column Filters] Add support for set filter in advanced filtering
AG-8977 [Column Filters] Allow switching between advanced/simple filters and transforming the applied filter model if possible

The best way to track delivery of these is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks a lot for your valuable feedback and suggestions!

Kind regards,
Zoheil

**Comment by cseickel** [comment]
Thanks for the quick reply @AG-Zoheil!
