### ISSUE TITLE
support to cellRenderer component of ag-grid use <script setup> in vue3.3,and get rowData from cellRenderer component

### ISSUE THREAD

**Issue by huajian123** [ag-grid/ag-grid#7110]
this is my code:
![image](https://github.com/ag-grid/ag-grid/assets/31737260/b7fe679a-0bec-485b-ad86-b905feb0ccf4)
![image](https://github.com/ag-grid/ag-grid/assets/31737260/9e7242b1-a04d-4047-bdd6-7446a63e53b7)
![image](https://github.com/ag-grid/ag-grid/assets/31737260/5194caf6-fc84-4026-9511-24c51ccf0a37)
![image](https://github.com/ag-grid/ag-grid/assets/31737260/7dccb83e-c65e-4e39-80f3-5fa889dc3f81)
I checked the documentation and found that I can use props.params.value to get rowData data, but I use <script setup> and there is no this or props. How should I solve this problem?

**Comment by huajian123** [comment]
Is there an example of using <script setup> syntax, using cellRenderer as a vue3 component to customize rendering, and obtaining rowdata in this vue3 component?

**Comment by joemaylor** [comment]
Hey @huajian123 - the documentation isn't great for this but it's pretty simple to do. You can certainly take in the props and use them in your cell renderer, if I've understood correctly. Here's the documentation example but translated to SFC `<script setup>`. Note that the particular Ag Grid package you import from might be different depending on if you're using packages vs modules.

```vue
<script setup lang='ts'>
import type { ICellRendererParams } from '@ag-grid-community/core'

const props = defineProps<{
  params: ICellRendererParams
}>()

const displayValue = new Array(parseInt(props.params.value))
  .fill('#')
  .join('')

</script>

<template>
<span>
  {{ displayValue }}
</span>
</template>
```

Hope that helps.

**Comment by huajian123** [comment]
@joemaylor thank you
