### ISSUE TITLE
how to show group parent as one cell (by combining first columns of children rows)

### ISSUE THREAD

**Issue by terlan4** [ag-grid/ag-grid#7111]
Hello, I would love to manage to see the parent cell as one united cell as i showed on the screenshot below. I couldn't find solution from theming, customization docs. Could you please tell me what is the proper way of achieving this? Thanks

 know row spanning, but i dont know how to merge child rows in parent cell like i showed.

![image](https://github.com/ag-grid/ag-grid/assets/138553763/d912fa30-f102-4a1e-8b4e-1d38ba500a52)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
