### ISSUE TITLE
licenses.txt file missing MIT license

### ISSUE THREAD

**Issue by ruwgu** [ag-grid/ag-grid#7116]
The licenses.txt file has some script written but its not a license.
The readme file says the license is MIT.
You should fix the licenses.txt file please.

**Comment by AG-Zoheil** [comment]
Hi @ruwgu,

Thanks for bringing this to our attention. We will investigate and fix this.

Meanwhile you can find our license info correctly displaying in the module txt files for example [here](https://github.com/ag-grid/ag-grid/blob/28.2/community-modules/core/LICENSE.txt).

Kind regards,
Zoheil
