### ISSUE TITLE
ag grid Enterprise version customizes the rendering filter, I hope the style is the same as the Community version

### ISSUE THREAD

**Issue by huajian123** [ag-grid/ag-grid#7122]
This is my code and page display effect. This is the Community version, not the Enterprise version. This is the effect I want to achieve.
<img width="1314" alt="image" src="https://github.com/ag-grid/ag-grid/assets/31737260/4ebaa6c5-c638-40ff-83c4-37043188ea4d">
When I add Enterprise key, the page effect becomes as shown below
<img width="620" alt="image" src="https://github.com/ag-grid/ag-grid/assets/31737260/913d648b-338c-48bf-bb3e-ea3dfd514e02">
I have to use the Enterprise version. My question is, on the premise that I use the Enterprise version, is there a way to make the display effect the same as the Community version. It is best to have a corresponding API instead of modifying CSS styles.
Since the Enterprise key is private, sorry, I cannot make the code public, I can only upload the Community version of the code, the address is here:
https://github.com/huajian123/ceshi26.0.0
Thank you very much for answering my question

**Comment by AG-Zoheil** [comment]
Hi @huajian123,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil
