### ISSUE TITLE
[Bug]: Issue with Re-Setting Custom Filters in ag-Grid

### ISSUE THREAD

**Issue by ravi-exiliensoft** [ag-grid/ag-grid#7124]
Dear ag-Grid Support Team,

I hope this message finds you well. We are currently facing a challenge related to re-setting and applying custom filters stored in a database when ag-Grid is reloaded. While the initial load of ag-Grid works seamlessly, we encounter difficulties when attempting to re-apply filters from the database after reloading.

Issue Description:

Upon the first load of ag-Grid, custom filters retrieved from our database are successfully applied and function as expected.
However, when we subsequently attempt to reset or reapply these filters after reloading ag-Grid, we experience issues in accurately setting the filter values.
Expected Behavior:

After reloading ag-Grid, we expect to retrieve the saved filter values from the database.
These retrieved filter values should be correctly re-applied to the respective ag-Grid columns, allowing us to maintain and modify filter settings as needed.
Current Behavior:

Despite successfully retrieving filter values from the database after reloading ag-Grid, we are encountering challenges in programmatically setting these values within the ag-Grid component.
As a result, the filters may not be applied correctly or consistently, leading to unexpected behavior.
Additional Information:

We have thoroughly reviewed our code implementation and confirmed that filter values are correctly retrieved from the database.
We are utilizing ag-Grid's custom filter functionality for this purpose.
The issue appears to be related to the process of re-initializing filters or handling events after reloading ag-Grid.
Request for Assistance:
We kindly request your expertise and guidance in addressing this issue. Any insights, recommendations, or best practices related to re-setting and applying custom filters in ag-Grid after a reload would be greatly appreciated.

If you require further details or code examples to better understand our implementation, please feel free to reach out. Your support in resolving this matter is highly valuable to us.

Thank you for your attention to this issue.

**Comment by AG-Zoheil** [comment]
Hi @ravi-exiliensoft,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello,

Thanks for providing the reproduction scenario. Please note the following changes we've made to the code:

**In the custom filter:**
```
setModel(model) {
    this.eFilterText.value = model == null ? null : model.value; 
}
```
**In the main code:**
`filterInstance2.setModel({ filterType: 'text', type: 'startsWith', filter: 'Michael' });`

The `setModel` implementation is expecting an object with a property called value. That's not what it's being called with.
 
Also, the `setModel` implementation is broken. It sets the value into the DOM element, but it doesn't set it into this.filterText which is what is actually being used for the filtering.
 
Here is a fixed implementation - https://plnkr.co/edit/X4up50c1AOmVEwEG?open=main.js.

I hope this helps. Please note we will also be making some changes to the implementation in our example for this in the AG Grid documentation.

Thanks again for raising this on GitHub.

Kind regards,
Zoheil
