### ISSUE TITLE
Incompatible Interface Typing for Viewport RowModel getRow

### ISSUE THREAD

**Issue by roysandrew** [ag-grid/ag-grid#7125]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**:
Implement the IViewportDatasource interface, call getRow, and examine the resulting types. Runtime will show RowNodes which have additional functions such as setDataAndId

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**:
The IViewportDatasource interface suggests that getRow returns IRowNode rather than, as it does in reality, returns a RowNode Entity as per RowModel.getRow.

https://github.com/ag-grid/ag-grid/blob/ab570bddfb31366be8092fbbd2bd40f8e5b0aac8/grid-community-modules/core/src/ts/interfaces/iViewportDatasource.ts#L21

https://github.com/ag-grid/ag-grid/blob/ab570bddfb31366be8092fbbd2bd40f8e5b0aac8/grid-community-modules/core/src/ts/interfaces/iRowModel.ts#L14

**Expected behavior**: IViewportDatasource should re-export the RowModel.getRow typing and not be inconsistent.

**Please tell us about your environment:** N/A

* **AG Grid version:** 30.2.0

* **Browser:** N/A

* **Language:** Typescript

**Comment by AndrewGlazier** [comment]
Hi,

Thanks for reporting this. The iRowNode interface is our correct public interface.

The iRowModel interface is incorrectly exposing more of our API than it should be.

We've raised an issue to address this inconsistency and update iRowModel to correctly match our public API. Thanks for reporting this.
