### ISSUE TITLE
Flickering when paginating with textWrap & autoHeight option enabled for rows.

### ISSUE THREAD

**Issue by AndrewN93** [ag-grid/ag-grid#7129]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- I'm trying to add autoheight behaviour to the table row depending on its content. I enabled `textWrap` & `autoHeight` options for row configuration. I have a pagination in my table. The behaviour of rows with all this configuration is weird and the height of the row changes rapidly on each page load for the first time.

[Please see repro example](https://stackblitz.com/edit/stackblitz-starters-hvouj5?file=src%2Fapp%2Fapp.component.ts)  

**Current behaviour**
Rows rapidly change their height on each page change

**Expected behavior**
Expected to behave like[ in this plunker from documentation](https://plnkr.co/edit/RiJztFlnyynYqEuL?preview).

**Please tell us about your environment:**
MacOS

* **AG Grid version:***
```
    "@ag-grid-community/angular": "28.1.1",
    "@ag-grid-community/client-side-row-model": "28.1.1",
    "@ag-grid-community/core": "~28.1.0",
    "@ag-grid-community/styles": "28"
```
* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "^4.9.5"

Am I missing something? Can someone advise how to fix that behaviour? Thanks.

**Comment by AG-Zoheil** [comment]
Hello @AndrewN93,

Thank you for bringing this to our attention.

We made some changes to `autoHeight` in v26. These changes did not extend scope to include enhancement/refactoring of the computation logic of `autoHeight`.

So currently there's no way to implement this behaviour with AG Grid. The plunker you've linked to runs on v24. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-6619**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AndrewN93** [comment]
@AG-Zoheil thank you for fast reply. I'm sorry but I cannot find the related task in product backlog with AG-6619 reference [here](https://www.ag-grid.com/pipeline/). 
<img width="1471" alt="image" src="https://github.com/ag-grid/ag-grid/assets/31307316/313b98dc-30b6-4451-aa81-26f7bc37d9da">

**Comment by AG-Zoheil** [comment]
Hi @AndrewN93,

Apologies, it had a label missing. Fixed now, you should be able to see it.

Kind regards,
