### ISSUE TITLE
[React] custom tooltip component not shown for empty value

### ISSUE THREAD

**Issue by sourdenis** [ag-grid/ag-grid#7133]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

* **Language:** [TypeScript 5.1.6 ]
* **Ag-Grid-enterprise:** [30.2.0]

When grid data has a value that is empty and the tooltip isn't shown in standard, I added tooltipValueGetter in column definitions (as default column definition) but it's not fired (the custom tooltip component params don't have the value included) and I don't get any tooltip for that empty value (I'm trying to show error message as tooltip).

I did according to the [documentation](https://www.ag-grid.com/react-data-grid/component-tooltip/#showing-blank-values)

Here are my column definitions functions.

```
const columnDefs: ColDef[] = useMemo(() => {
        if (data.length === 0) return [];
        return Object.keys(data[0]).map((colTitle) => ({
            field: colTitle,
            cellRenderer: 'cellRenderer',
            valueGetter: valueGetterForColumn,
            tooltipField: colTitle,
            tooltipComponentParams: { errors },
            cellRendererParams: { errors },
        }));
    }, [data]);
```

    const defaultColDef = useMemo(
        () => ({
            ...GridConf.props.defaultColDef,
            tooltipComponent: 'errorTooltipComponent',
            tooltipValueGetter: (params: any) => ({ value: 'random value' }),
        }),
        [GridConf.props.defaultColDef]
    );

Here is my AgGridReact component:

```
<AgGridReact<T>
    ref={gridRef}
    getRowId={rowId}
    columnDefs={columnDefs}
    components={components}
    onModelUpdated={() => {
        gridRef.current?.api.redrawRows();
    }}
    rowData={data}
    detailRowAutoHeight={true}
    getRowStyle={rowStyle}
    tooltipShowDelay={0}
    tooltipHideDelay={4000}
    {...GridConf.props}
    defaultColDef={defaultColDef}
    sideBar={null}
/>
```
Am I missingi something?

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
