### ISSUE TITLE
headerClass with suppressSpanHeaderHeight

### ISSUE THREAD

**Issue by danielmalaton** [ag-grid/ag-grid#7135]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I'm using `headerClass` and `suppressSpanHeaderHeight` like this:
```Typescript
columnDefs: [
  {
    headerName: 'Athlete Details',
      children: [{
        headerName: 'Test',
        children: [{ field: 'athlete' }, { field: 'country' }],
      }]
    },
    { 
      headerName: 'Total',
      headerClass: ['header-total'],
      children: [{
        field: 'age', width: 90, suppressSpanHeaderHeight: true,
      }]
    },
]

// in style
.header-total {
  background-color: yellow;
}
```
Sample plunker: https://plnkr.co/edit/wHOIHLHXUVRpVVBE?open=main.js
**Current behavior**
It does not paint the entire header with a yellow background
<img width="515" alt="Screenshot 2023-10-11 at 22 51 20" src="https://github.com/ag-grid/ag-grid/assets/106505755/e8079d50-be6a-4a81-95a2-554687c0721c">

**Expected behavior**
It would be a yellow `total` header entirely.
<img width="598" alt="Screenshot 2023-10-11 at 22 53 48" src="https://github.com/ag-grid/ag-grid/assets/106505755/9a9cf13e-6878-4468-8e69-1278549fcf79">

**Additional context**
I know we can add style for `.ag-header-group-cell-no-group` class. But can we do it in another way e.g use `headerClass`?

**Please tell us about your environment:**

* **AG Grid version:** 30.1.0

* **Browser:** Firefox

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
