### ISSUE TITLE
Documentation error: reference to non-existent ColDefGroup<TData>

### ISSUE THREAD

**Issue by danielbrauer** [ag-grid/ag-grid#7141]
(I couldn't find any docs repo, otherwise I'd be happy to fix this myself.)

There is an error on the following page of the API documentation:

https://www.ag-grid.com/react-data-grid/column-properties/

The second paragraph on this page begins with:

> Typescript supports a generic row data type via `ColDef<TData>` and `ColDefGroup<TData>`

whereas the correct name is **ColGroupDef**

**Comment by StephenCooper** [comment]
Thanks! I have corrected and this will be fixed with our next release.

**Comment by AG-Zoheil** [comment]
Hi @danielbrauer,

Thank you for bringing this to our attention. We will look to correct the incorrect naming.

Kind regards,
Zoheil
