### ISSUE TITLE
In react version, the native floating filter is not getting closed on outside click.  

### ISSUE THREAD

**Issue by theritikshah** [ag-grid/ag-grid#7148]
![image](https://github.com/ag-grid/ag-grid/assets/26920821/4628f8b0-6c9e-4532-9e9f-9f61b8bcca37)

**Comment by AG-Zoheil** [comment]
Hi @theritikshah,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by theritikshah** [comment]
### Found the Issue and fix for it.
If we add event.stopPropagation() to the parent div of ag-grid, then the filter popup doesn't close on document click. Included the screenshots of my solution to this. Please feel free to give more optimized solutions. Thanks! 
![image](https://github.com/ag-grid/ag-grid/assets/26920821/f77d75bc-cdb8-400c-b071-c84e9200ea63)
![image](https://github.com/ag-grid/ag-grid/assets/26920821/5a196416-e671-411f-87f7-b63e0aa34474)
