### ISSUE TITLE
Show only selected rows for a server side row model

### ISSUE THREAD

**Issue by Berni3011** [ag-grid/ag-grid#7151]
Hello ag-grid developers,

On our server side table we have a 'show only selected rows' button. My question is how I can update my rows by toggling this button on / off.

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
