### ISSUE TITLE
Use setExpanded multiple times in a row causes the table to freeze

### ISSUE THREAD

**Issue by CamboimGabriel** [ag-grid/ag-grid#7152]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I'm saving in localStorage all groups that are fold and unfold groups, so when the page refreshes and the data is loaded, I automatically expand those who are saved in localStorage, I'm using this block of code to do so:

```
gridRef.current?.api?.forEachNode((node) => {
     if (expandedGroups.includes(node.key)) 
           node.setExpanded(true);
     });
```

**Current behavior**
After page loads, when I try to scroll or interact with the table, everything freezes and after sometime the default browser error appears

**Expected behavior**
I expect to be able to use the setExpanded multiple times without crash

**Please tell us about your environment:**
MacOS, Chrome

* **AG Grid version:** 30.1.0

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'

* **Language:** Typescript

**Comment by AG-Zoheil** [comment]
Hi @CamboimGabriel,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by cjdreiss** [comment]
Hello, we are migrating from v29 to v31 and are running into this issue. On a grid with about 24k nodes, looping through them and trying to expand causes the grid to freeze and chrome will bring up a page not responding error till it’s finished. 

This was not a problem in v29. 

Using pretty much the same code, looping through all nodes, and if the level of that node is less than a given value we call node.setExpanded(true). 

I’ll work on a repo in 29 vs 31 in the next day or so.

**Comment by AG-Zoheil** [comment]
Thank you @cjdreiss - if you can provide a reproduction of the reported misbehaviour that would be much appreciated!

**Comment by cjdreiss** [comment]
> Thank you @cjdreiss - if you can provide a reproduction of the reported misbehaviour that would be much appreciated!

We have some security restrictions at work so I can’t easily put up a public one, but I have submitted a ticket in Zendesk and shared the reproduction there.
