### ISSUE TITLE
How to rearrange groups order

### ISSUE THREAD

**Issue by CamboimGabriel** [ag-grid/ag-grid#7153]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello, I'm using the row grouping feature and I have a column called "Group" on each row, I want to be able to drag groups to different order but for this I need to be able to manipulate my own rowData state. Since row data does not contains the group as an item, how can I rearrange them? I tried to move all nodes that are from the same group do another position but did not work, also I tried to search in the documentation but I found nothing...

**Please tell us about your environment:**
MacOS, Chrome

* **AG Grid version:** 30.1.0

* **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'

* **Language:** Typescript

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
