### ISSUE TITLE
setQuickFilter is with wrong behaviour

### ISSUE THREAD

**Issue by supermuka** [ag-grid/ag-grid#7157]
After updating the latest version of ag-grid, setQuickFilter is behaving incorrectly, which previously worked.

Does not search on grouped columns.

**Comment by supermuka** [comment]
See the video : https://sharing.clickup.com/clip/p/t3021842/9e5ee00a-4f64-4848-b75f-9f75bded9c69/screen-recording-2023-10-17-14:35.webm

dev.idss.com.br, first screen, old ag-grid version.
app.idss.com.br, second screen, last ag-grid version.

The code is the same in both version. See a piece about search field. We are using Angular:

```
      <div class="w-full md:w-max">
        <bl-pesquisar-input (onSearch)="onSearch($event)"></bl-pesquisar-input>
      </div>

```
```
  onSearch(value: string) {
    this.agGrid.api.setQuickFilter(value);
  }
```

**Comment by AG-Zoheil** [comment]
Hi @supermuka,

Thank you for the screenshot and for explaining this further.

As we are unable to reproduce this with our examples we will not be able to investigate this until you provide a live sample which shows the issue. You can use one of the examples I linked to in my comment above as a starting point. Alternatively you can pick any plunker/codesandbox from our website. Please replicate the behaviour you are experiencing and send it on to us to investigate.

Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil
