### ISSUE TITLE
Row Deselection with shift click does not work

### ISSUE THREAD

**Issue by jchristou** [ag-grid/ag-grid#7162]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

On a grid with the multiple row selection property set, a user can select multiple rows at a time with the Shift Key and clicking.
It should be possible for the user to deselect multiple rows by shift clicking too. 

However, if the user continues to shift click an already selected row, all rows below and including that row stay selected and are not deselected.

**Expected behavior**

The user should be able to deselect multiple rows using the Shift Key and clicking.

This problem is actually reproducible on the latest ag-grid docs, see here: https://www.ag-grid.com/javascript-data-grid/row-selection/#example-multiple-row-selection

This bug seems to have been introduced in version 27.3.0. The docs site for 27.2.0 has the expected behaviour. See here: https://www.ag-grid.com/archive/27.2.0/javascript-data-grid/row-selection/#example-multiple-row-selection

**Please tell us about your environment:**

* **AG Grid version:** 30.2.0

* **Browser:** all

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hello @jchristou,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-5343**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
