### ISSUE TITLE
numericColumn and rightAligned missing from GridColumnType

### ISSUE THREAD

**Issue by nealeu** [ag-grid/ag-grid#7164]
These are defined in DefaultColumnTypes and are in the documentation at https://ag-grid.com/angular-data-grid/column-definitions/#right-aligned-and-numeric-columns, but are not permitted by the Typescript because GridColumnType is defined as:

```typescript
export type GridColumnType =
    | 'string'
    | 'boolean'
    | 'number'
    | 'date'
    | 'dateInRange'
    | 'datetime'
    | 'shared'
    | 'time'
    | 'select';
```

This was previously raised verbosely as #3975, which got responded to as a support issue (probably because it was difficult to see what was wrong).

**Comment by StephenCooper** [comment]
I believe the issue comes down to these being two separate col Def properties. 

I would suggest using the newer `cellDataType` over the `type` to apply numerical defaults.

**Comment by nealeu** [comment]
How do you suggest that works for the Depreciation column using `cellDataType: 'percentageFloat'` in this fork of your example https://codesandbox.io/p/sandbox/ag-grid-angular-example-forked-jtdtw3?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A15%2C50 ?

Without `type: 'numericColumn'` it is left aligned

**Comment by StephenCooper** [comment]
I would just copy the values `numericColumn` has set into your `percentage` data type definitions. 
https://codesandbox.io/p/sandbox/ag-grid-angular-example-forked-jtdtw3?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A15%2C50

```ts
    percentage: {
        extendsDataType: 'number',
        baseDataType: 'number',
        valueFormatter: (params: any) => params.value == null
            ? ''
            : `${Math.round(params.value * 100)}%`,
        headerClass: 'ag-right-aligned-header',
        cellClass: 'ag-right-aligned-cell'
    },
```

This is how those are defined so you can just copy what they are doing.

```ts
export const DefaultColumnTypes: { [key: string]: ColDef } = {
    numericColumn: {
        headerClass: 'ag-right-aligned-header',
        cellClass: 'ag-right-aligned-cell'
    },
    rightAligned: {
        headerClass: 'ag-right-aligned-header',
        cellClass: 'ag-right-aligned-cell'
    }
};
```

**Comment by nealeu** [comment]
Works in a sandbox, but not in our app.
I think I'm going with `cellDataType: false` for now.  Every issue we've had with going from 29 -> 30 has been caused by the automatic behaviour where that really should have been the default.  We've had so many obscure bugs come up where despite trying to embrace the "new way" we're just having to disable it.
