### ISSUE TITLE
hiding Group Row

### ISSUE THREAD

**Issue by feyzullah-yildiz-ext-orion** [ag-grid/ag-grid#7166]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
Short quesiton, is there any way to hide GroupRow when groupping is enabled.
I already do to show the data;
Expand all groups by default. Group column is hidden.

* **Please tell us about your environment:**  Windows, vsCode
* **AG Grid version:** 30.1.0
* **Browser:** Chrome
* **Language:** TypeScript 4.9.5

![image](https://github.com/ag-grid/ag-grid/assets/113505529/8330100a-3ccf-4b2d-8f8a-9e420d71ecc2)

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
