### ISSUE TITLE
Pivot values as rows

### ISSUE THREAD

**Issue by themallisetty** [ag-grid/ag-grid#7167]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

Yes, we have a license for ag-grid-enterprise but I don't access to Zendesk.

**Current behavior**

When we do pivot, we get the aggregation as a columns. like as follows

![image](https://github.com/ag-grid/ag-grid/assets/24922189/f87b02cc-5115-40a7-8758-92e9ea80477a)

Following is the plnkr for our implementation.
https://plnkr.co/edit/1bSu5mEhpUp9YIfw?open=app%2Fapp.component.ts

**Expected behavior**

We would like to see the grid like below. 
![image](https://github.com/ag-grid/ag-grid/assets/24922189/36a4d626-7e78-4fd7-9450-e2d8446d2422)

Can we get some help in achieving this

**Please tell us about your environment:**

* **AG Grid version:** 25.1.0

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'

* **Language:** [Angular]

**Comment by themallisetty** [comment]
Thank for response. 

We are thinking of another approach. We can perform the aggregation and provide the object to the Grid.

By using the basic implementation, Grid will look like the following.

https://plnkr.co/edit/B7hMSZXqsbe1bbxE?open=app%2Fapp.component.ts
![image](https://github.com/ag-grid/ag-grid/assets/24922189/89775c54-dbf7-4903-8eb1-093dbc8c2f83)

With AG-Grid, Is it possible to transpose the Grid to achieve the following?

![image](https://github.com/ag-grid/ag-grid/assets/24922189/38e48ab1-58c5-4b7b-b13e-9436ea647900)

**Comment by AG-Zoheil** [comment]
Hi @themallisetty,

I'm afraid transposing is currently not possible in AG Grid. This is a often-requested feature so definitely on our radar. You can track it with reference: **AG-3142**.

Thanks!

**Comment by themallisetty** [comment]
Hi @AG-Zoheil , Is there any timeline to implement this feature?

**Comment by AG-Zoheil** [comment]
Hello,

At this point, we don't have a specific timeline for implementing this functionality.

In order to get the maximum output from our product development team, we very rarely work on feature requests from different areas in isolation. Instead, for a specific release we focus on an entire area of the grid and we tackle a number of issues/feature requests logged against that area.

Kind regards,
Zoheil

**Comment by chrisvander** [comment]
Hi, we have an enterprise license and we're curious if we can transpose on Excel export, as opposed to doing it inside the table. Is there a way to do that transformation?

**Comment by AG-Zoheil** [comment]
Hi @chrisvander,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Regarding the issue/question above, this is not currently possible. Although the ability to transpose is something we'd like to deliver it is a large and complex feature that we haven't managed to get to yet.

Kind regards,
Zoheil
