### ISSUE TITLE
ag-grid api remove event listener error

### ISSUE THREAD

**Issue by hat33** [ag-grid/ag-grid#7168]
When trying to move from a grid component to another screen, an error occurs in the status panel component.

Uncaught TypeError: Cannot read properties of undefined (reading 'useAsyncEvents') at GridApi.removeEventListener

export const TotalRowsGridStatusPanel = (props: IStatusPanelParams) => {

    const [countRows] = useCounterRows(props.api)

    return (<Box>Rows:<Space /><Box component={"span"}>{countRows}</Box></Box>)
}

export const useCounterRows = (gridApi: GridApi) => {
    const cleanupFunctionRef = useRef(false)
    const [countRows, setCountRows] = useState<number | null>(null)

    useEffect(() => {
        cleanupFunctionRef.current = false

        function setRows() {
            if (cleanupFunctionRef.current) return
            setCountRows(getValueOrNull(FinanceUtils.getRowCount(gridApi)))
        }

        gridApi.addEventListener('modelUpdated', setRows)

        return () => {
            cleanupFunctionRef.current = true
            if (!gridApi) return
            gridApi.removeEventListener('modelUpdated', setRows)

        }
    }, [gridApi])

    return [countRows]
}

**Comment by AG-Zoheil** [comment]
Hi @hat33.

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by hat33** [comment]
![image](https://github.com/ag-grid/ag-grid/assets/46162082/20770f83-b943-48c0-bbea-729278c633fb)
![image](https://github.com/ag-grid/ag-grid/assets/46162082/ea5b9570-b472-4458-94b7-7fa23d38a67b)


example reproducing: https://codesandbox.io/s/ag-grid-remove-event-listener-repo-yry25k

For some reason, the frequency of the error varies depending on the device.
The problem occurs either immediately when going to a page with a grid, or when going to another page.

**Comment by AG-Zoheil** [comment]
Hello @hat33,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-9482**

You'll be pleased to know that the work for this has already been completed and it will be part of our release next month.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
