### ISSUE TITLE
Get all the data of a column in vue.js

### ISSUE THREAD

**Issue by NunzioRash** [ag-grid/ag-grid#7173]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

Hi all, how can I get all the values of a column to use them externally to ag-grid? I need to use this data even after it has been filtered.
I use ag-grid in vue.js.
Can you help me? Thank you

**Comment by NunzioRash** [comment]
Thank you for your answer.
What I can't do is recover the data from the table after it is populated.
I recover the data via axios:

```
const risultati = ref(null);
onBeforeMount(()=>{
  const getDati = () =>{
              try{
                  axios.get(API_URL + '/URL-API' + id)
                  .then(({data})=>{
                      if(data.stato == 200){
                          risultati.value = data.data;
                      }
                  })
              }catch(error){
                  alert(error);
              }
          };
          getDati()
})
```

then I initialize grid.api
```
const onGridReady = (params) => {
      gridApi.value = params.api;
      gridColumnApi.value = params.columnApi;
    };
```
and then I try to recover the data
```
const getAllRows = () => {
        let RowData = [];
            gridApi.value.forEachNodeAfterFilter(node => RowData.push(node.data));
            return RowData;
    }
```
but I always get undefined as the result.
I use vue 3 composition api.

**Comment by joemaylor** [comment]
Your `getAllRows` function looks like it should work. Where exactly are you calling this? Are you able to make a codepen or plunker so I can take a look?

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
