### ISSUE TITLE
How to handle line breaks in a table where data is translated into a row

### ISSUE THREAD

**Issue by qianmoQ** [ag-grid/ag-grid#7175]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => see title

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

![image](https://github.com/ag-grid/ag-grid/assets/20521442/9f836c9c-d6fe-4918-b8df-7cef1237cd54)

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** `"ag-grid-community": "^29.3.5"`, `"ag-grid-vue3": "^29.3.5"`

* **Browser:**

* **Language:** Vue3 , Typescript

**Comment by AG-Zoheil** [comment]
Hi @qianmoQ,

Thank you for reporting this.

We'd be happy to look into this, but you have provided no description or steps to reproduce.
The most efficient way for us to look into this would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi @qianmoQ,

By default, HTML doesn't render line break characters. AG Grid works the same way. Just like with rendering any HTML, if you need a line break, you need to inject <br> in the HTML. 
 
This is why your custom cell renderer needs to be set up in the following way to replace new line characters with <br>'s before rendering the cell values.
 
Please see this here: https://plnkr.co/edit/o7eQi4wwCRi2crDo?open=main.js

Kind regards,
Zoheil
