### ISSUE TITLE
`ValueSetter` is ignored in setValue signature

### ISSUE THREAD

**Issue by Athelian** [ag-grid/ag-grid#7179]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

To export bool values to excel docs specify to use 0 or 1 (turns out this needs to be in `valueGetter`), so I am transforming my bool data value to 0 | 1 in `valueGetter`.
My `CellRenderer` (left) therefore receives 0 | 1 as it's TValue.
This means that `setValue` expects 0 | 1 as its parameter, but this doesn't make sense because it should be set as bool and then transformed to 0 | 1 by `valueGetter`

Am I doing something wrong?
![image](https://github.com/ag-grid/ag-grid/assets/67857298/838e8de6-cae1-449a-bacd-be6f21a51606)

**Expected behavior**

`setValue` should expect the input parameter of the corresponding column's `valueSetter`

**Please tell us about your environment:**

vscode

* **AG Grid version:**  30.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.9.5

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
