### ISSUE TITLE
AG Grid: Framework component is missing the method isFilterActive()

### ISSUE THREAD

**Issue by georginklv** [ag-grid/ag-grid#7181]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
I am using "ag-grid-community": "^29.3.3", "ag-grid-vue3": "^29.3.3", with vue 3 composition api. This is custom filter component which i am using to filter columns in table.When i check some of the options in the filter it pop up this warning and it doesnt show that there is filter in this column.
```
<template>
  <div>
    <div class="custom-filter-wrapper">
      <div class="custom-filter-body">
        <label
          v-for="option in params.values"
          :key="option.value"
          class="options"
        >
          <input
            type="checkbox"
            :value="option"
            v-model="filterState"
            @change="updateFilter(option)"
          />
          {{ option }}
        </label>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
  import { ref } from "@vue/reactivity"
  const { params } = defineProps();
  const { field } = params.colDef;
  const filterState = ref([]);

  const isFilterActive = () => {
    return true
  }
  const updateFilter = (value) => {
    params.filterChangedCallback();
  }
  const doesFilterPass = (params) => {
    return params.data[field] == filterState.value
  }
  const getModel = () => {
    if(filterState.value.length != 0){
      return undefined
    }
    return { state: filterState.value }
  }
  const setModel = (model) => {
    if(model == null) {
      updateFilter([])
    } else {
      updateFilter(model.state)
    }
  }
</script>
```

**Comment by georginklv** [comment]
Thats a bug with script setup tag for vue3 composition API

**Comment by AG-Zoheil** [comment]
Hello @georginklv,

Thank you for the clarification. You had tagged your original issue as "Support request".

We've looked into this now and can confirm there's currently no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We are tracking it with the following reference and description: AG-8274 Support Custom Vue 3 Components in <script setup>

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
