### ISSUE TITLE
Filtering and sorting from url

### ISSUE THREAD

**Issue by GenatHadri** [ag-grid/ag-grid#7182]
I'm submitting a:
[] bug report 
[] feature request 
[x] support request 

Hi everyone, 
I am working on a project with ag grid enterprise, and I have 2 questions in which I made some researches but didnt find the solution:
I have a general grid component which I use in more than 60 pages, where in each of them I have a query for data and send as a prop to that grid component. At those pages I also control the url for sorting or for filtering and send that to the server and get that response with all sorted or filtered data, and then send to the grid component.
My questions are:
1. For sorting: is there any way to know which column header I am clicking and set the url with that column name and his sorting order (asc or dsc). Do I need to set rowModelType="serverSide" or I can do without it?
2. For filtering: is there any way to get the 'builder' filters as json or something and set to the url.   Do I need to set rowModelType="serverSide" or I can do without it?

Thanks everyone

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
