### ISSUE TITLE
Unable to append column types to existing column definition 

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7184]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
I have a grid where I add a column type "rightAlignColumn" to one of the column definition which adds a cell class 'ag-right-aligned-cell' for right aligning cells.

I have also extended the cell data type number to include a column type of "highlightCell" which sets a background color to any number cell.

But only my column type defined in the column definition works(cell right aligns but does not apply cell style) even after using the property "**appendColumnTypes**: true" as per the docs.

Replication Example Link:
https://plnkr.co/edit/tUq4LTQUWyrdizcF?open=index.jsx

**Expected behavior**
I should be able to append and use all column types defined in column definition, data type definition or even default column definition.

* **AG Grid version:** X.X.X
30.2.0

* **Browser:**
All

* **Language:** 
* React

**Comment by AG-Zoheil** [comment]
Hi @melon2504,

Thanks for submitting this via Github.

This is not a bug. As per our docs - "If `true`, this data type will append any specified column types to those of the data type that this extends."
 
You're currently setting a column type against the column and a column type against the data type definition. The flag only works if one data type definition is overriding another.

I hope this helps.

Kind regards,
Zoheil
