### ISSUE TITLE
[Bug] During grid intialization the SortService -  sort method call - led to page crash because of method call against undefined 

### ISSUE THREAD

**Issue by YaroslavHapon** [ag-grid/ag-grid#7185]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
After login and during grid initialization, the page crashes, when calling a `sort` method inside the `SortSrvice` class
Because `this.columnModel.getAllGridColumns()` returns `undefined` and `Array.some` method is called against it

Here is some code reference that is being called

```tsx
class SortService extends BeanStub { 
  sort (e, t, n, r, o, i) {
   this.columnModel.getAllGridColumns().some((e=>e.isRowGroupActive()));
  }
}

TypeError:  this.columnModel.getAllGridColumns(). is undefined 
```
**Current behavior**
The page crashes because `getAllGridColumns` method returns an undefined 

**Expected behavior**
The page is not crashed, `this.columnModel.getAllGridColumns() `returns an empty array if columns are not available yet or don't call the `some` method on undefined

**Please tell us about your environment:**
Windows, Mac OS,

* **AG Grid version:** 30.0.6

* **Browser:**
 All browsers

* **Language:** TypeScript | React

**Comment by AG-Zoheil** [comment]
Hi @YaroslavHapon,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by YaroslavHapon** [comment]
I can't reproduce it in Plunker or any other sandbox, the only thing  that I know it happens when the grid is removed and added to the DOM again

Best regards,
Yarolsav

**Comment by YaroslavHapon** [comment]
I can provide you a screenshot with such console  information and stack trace

![Знімок екрана 2023-10-25 о 15 12 35](https://github.com/ag-grid/ag-grid/assets/10761657/e07e7d04-1ab3-469f-af13-4234ada288a8)

**Comment by YaroslavHapon** [comment]
JFYI 
I was able to get more stack trace and it said that the error happened inside AgGridReactUi

![Знімок екрана 2023-10-25 о 17 10 15](https://github.com/ag-grid/ag-grid/assets/10761657/3464df03-39ef-4f52-b7d5-a7fc144e0954)

**Comment by YaroslavHapon** [comment]
@AG-Zoheil  Hello 
Do you have any thoughts on what can cause that issue?

**Comment by AG-Zoheil** [comment]
Hi @YaroslavHapon,

We will have a look but it'll be difficult for us to debug/investigate without being able to reproduce the error.

**Comment by AG-Zoheil** [comment]
Hi @YaroslavHapon,

We've had a look and you'll be pleased to know we have already made improvements to this. Our changes will (a) stop the model from being refreshed before the columns are ready, and (b) prevent getAllGridColumns from returning undefined.

These changes will be released with our `v31` releases next month.

Thanks again!

**Comment by YaroslavHapon** [comment]
@AG-Zoheil That's awesome! Thank you for your quick help and support!

**Comment by YaroslavHapon** [comment]
Hello @AG-Zoheil 

Could you please provide rough estimates, of when the release `v31` can happen? 

Best regards,
Yaroslav

**Comment by AG-Zoheil** [comment]
`v31` is targeted to be released in the last week of November.

**Comment by YaroslavHapon** [comment]
Thank you! Have a nice day!
