### ISSUE TITLE
Show or Hide column based on row grouped level opened

### ISSUE THREAD

**Issue by soumyaa1804** [ag-grid/ag-grid#7189]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

We are using Ag grid enterprise and have row grouped based on some hierarchy and we are using SSRM, so when the user would click on any grouped row, an API call would be made to fetch its below hierarchy.

We have a requirement to add a column only when the user is able to view the data of a particular hierarchy and hide that column if the user can't see the data because they collapsed any of its parent row. 

For example: Let's suppose our Hierarchy is `Planet -> Continent -> Country -> State -> District`
So we need to add a column `Pin Code` only when any of the States are clicked and we can see all the District under it. Also we need to hide that column when the user collapse the row group from any of its parent (meaning, all the Districts would be closes if any of its parent `State`, `Country`, `Continent` or `Planet` is clicked.

Can someone please help here how I can achieve it?

**Please tell us about your environment:**

MacOS, VScode, npm

* **AG Grid version:** X.X.X

    "ag-grid-community": "^29.3.4",
    "ag-grid-enterprise": "^29.3.4",
    "ag-grid-react": "^29.3.5",

* **Browser:**

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @soumyaa1804,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil

**Comment by soumyaa1804** [comment]
Hi @AG-Zoheil, we got the licence. Can you please tell the process to connect to the Zendesk team? Which id and password we need to use?

**Comment by AG-Zoheil** [comment]
Please contact [info@ag-grid.com](mailto:info@ag-grid.com) and you'll be given guidance on how to get set up.
Thanks
