### ISSUE TITLE
Sidebar is reset when `rowModelType` is `serverSide` or `infinite`.

### ISSUE THREAD

**Issue by heeju** [ag-grid/ag-grid#7190]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

The behavior of the sidebar depends on its settings. The sidebar is initialized when new data is updated in the grid (for example, when calling `params.success` on datasource, or when updating values in `filterParams` with async).

https://github.com/ag-grid/ag-grid/assets/3131509/7298a204-4d31-48c1-8aa7-7a4131db5754
In the video, you can see that the sidebar is reset when updating the data in the grid.

This behavior depends on the sidebar param. Below is an abnormal behavior setting and a normal behavior setting.

```
  const getFilterValuesData = useCallback(
    colId => params => {
      getSsrmFilterValues(colId)
        .then(result => {
          params.success(result);
        })
        .catch(err => {});
    },
    []
  );

  const onGridReady = useCallback(({ api }: GridReadyEvent) => {
    api.setServerSideDatasource({
      getRows(params: IServerSideGetRowsParams) {
        const { request, context } = params;
        getRowsData({ request, context })
          .then(({ rows, totalRowCount }) => {
            params.success({
              rowData: rows,
              rowCount: totalRowCount
            });
          })
          .catch(err => {
            params.fail();
          });
      }
    });
  }, []);

return <AgGridReact
     defaultColDef={{
      resizable: true,
      sortable: true,
      minWidth: 100,
      flex: 1,
      filter: true,
      floatingFilter: true,
      wrapHeaderText: true,
      autoHeaderHeight: true
    }}
    columnDefs={[
    {
      field: 'athlete',
      filter: 'agTextColumnFilter',
      filterParams: {
        maxNumConditions: 1,
        filterOptions: ['contains']
      }
    },
    {
      field: 'country',
      filter: 'agSetColumnFilter',
      filterParams: {
        values: getFilterValuesData('country')
      }
    },
    {
      field: 'year',
      filter: 'agSetColumnFilter',
      filterParams: {
        values: getFilterValuesData('year')
      }
    },
    {
      field: 'sport',
      filter: 'agSetColumnFilter',
      filterParams: {
        values: getFilterValuesData('sport')
      }
    },
    {
      field: 'gold',
      filter: 'agNumberColumnFilter'
    },
    {
      field: 'silver',
      filter: 'agNumberColumnFilter'
    },
    {
      field: 'bronze',
      filter: 'agNumberColumnFilter'
    }
  ]}
   rowModelType="serverSide"
   cacheBlockSize={pageSize}
   maxBlocksInCache={10}
   onGridReady={onGridReady}
/>
```

abnormal case
```
sideBar={['columns', 'filters']} // even if there is only one array.
sideBar={{
  toolPanels: ['columns', 'filters'] // even if there is only one array.
}}
```

normal case
```
sideBar={true}
sideBar={'filters'}
```

**Expected behavior**

Regardless of the setting, sidebar behavior should be guaranteed.

**Please tell us about your environment:**

macOS, nextjs, intelliJ

* **AG Grid version:** 30.2.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @heeju,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by heeju** [comment]
I tried to reproduce the phenomenon in plunker, but was unsuccessful. 
Looking at my code more closely, I realized that the problem occurs when calling additional data. I use the `apollo client` `useLazyQuery` to get the data, and that's where the problem occurs.  
I don't know what's going on in `apollo client`, but it's a strange case where a particular combination of options in `useLazyQuery` and ag-grid `sideBar` option causes this to happen. I'll deep dive into my case.

**Comment by heeju** [comment]
I've been testing with different versions of ag-grid and the problem occurs since version 29.0.0. version 28 and bellow don't have this problem. I hope this helps you figure out the problem.

**Comment by AG-Zoheil** [comment]
Hi @heeju,

Thank you for the extra information.

So were you able to reproduce it on a v29 version and can you please provide the plunker if so?

Thanks

**Comment by heeju** [comment]
To reproduce, need to use `apollo client` I don't know if this can be implemented in plunker. This issue is caused by a specific combination of options in apollo client and sidebar, which should be taken into account.

**Comment by AndrewGlazier** [comment]
Hi Heeju,

The issue here is that you're not memoising your compared-by-reference values. When the grid receives a new value, it compares it to the old value to determine whether that value has changed. If it has, the grid takes steps to update it's internal state.

We document this phenomenon here: https://ag-grid.com/react-data-grid/react-hooks/#row-data

The apollo client hook is likely causing your component to re-render, causing new object and array instances to be passed to the grid, which in turn is causing ag-grid to try to update to match your new state. The best way to fix this is to use the React `useMemo` hook to prevent your references being needlessly recreated. You should ideally use this for any objects or arrays you pass into ag-grid. In your example this would be:
`defaultColDef`, `columnDefs`, and `sideBar`.

**Comment by heeju** [comment]
That's the part I missed. That was helpful. Thank you.
