### ISSUE TITLE
How to set the series attribute labels in the formatPanel in chartToolPanelsDef to be selected by default

### ISSUE THREAD

**Issue by awhlmycn** [ag-grid/ag-grid#7191]
1. How to set the series attribute labels in the formatPanel in chartToolPanelsDef to be selected by default

**Comment by AG-Zoheil** [comment]
Hi @awhlmycn,

Based on what I've understood from your question you'd like to display something like this: https://plnkr.co/edit/gncSdc9f62ubQM8e?open=main.ts.

If that's the case, you can achieve this by setting `defaultToolPanel: 'format'`. I hope this helps.

Kind regards,
Zoheil

**Comment by awhlmycn** [comment]
@AG-Zoheil I want to display values on the chart by default, but I don't know how to set enabled in labels to true

**Comment by AG-Zoheil** [comment]
Thanks @awhlmycn.

If you'd like to display labels by default you need to use `chartThemeOverrides`. Documentation [here](https://ag-grid.com/javascript-data-grid/integrated-charts-customisation/#overriding-existing-themes).
See this example: https://plnkr.co/edit/S2kNXppmSz2A1umj?open=main.js

**Comment by awhlmycn** [comment]
@AG-Zoheil  Thank you very much. It was a success
