### ISSUE TITLE
provide is expected to support updates and multiple instances.

### ISSUE THREAD

**Issue by jxh150535011** [ag-grid/ag-grid#7196]
https://github.com/ag-grid/ag-grid/blob/d363b90be8022562c6f41b46ccd59402780fb33c/grid-packages/ag-grid-vue3/src/VueFrameworkComponentWrapper.ts#L22C7-L24C10

The global singleton implementation of this code has encountered two problems during development:

1 Component destruction leads to the failure of updating the provide.
2 n the case of multiple instantiations, all components receive the same provide (from the first instantiated component).

For example, the pseudocode below:
```html
<CustomProvide  context={1}>
<AgGrid columnDefs=[AgGridChild] /> // AgGridChild get provide 1
<AgGrid>
</CustomProvide>
<CustomProvide context={2}>
<AgGrid columnDefs=[AgGridChild] /> // AgGridChild get provide 1
<AgGrid>
</CustomProvide>

// if update context and destroy component
<CustomProvide  context={3}>
<AgGrid columnDefs=[AgGridChild] /> // AgGridChild get provide 1
<AgGrid>
</CustomProvide>
<CustomProvide context={4}>
<AgGrid columnDefs=[AgGridChild] /> // AgGridChild get provide 1
<AgGrid>
</CustomProvide>
```

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: AG-10705

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
