### ISSUE TITLE
Value Formatter Replaced by Checkbox when updating From 29.2 to 30.2

### ISSUE THREAD

**Issue by awdorrin** [ag-grid/ag-grid#7208]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Expected behavior**

In V29 the following code, for a Boolean field produced the cell content 'Yes' or 'No'

    valueFormatter: (param) => {
          return (param.value) ? "Yes" : "No";
     }

**Current behavior**

A checkbox displays, either checked or unchecked

Angular 15, AG Grid 30.2.0

All I did today was upgrade from AG Grid Community/Angular 29.2.0, and value formatter was replaced by a checkbox.

**Comment by AG-Zoheil** [comment]
Hi @awdorrin,

Since `V30` we are inferring cell data types. You are able to set this to `false` if you wish. For more information please see: https://ag-grid.com/javascript-data-grid/cell-data-types/

Kind regards,
Zoheil

**Comment by awdorrin** [comment]
Ok, was this posted in release notes in a breaking changes section somewhere,  that I missed?
Thanks

**Comment by AG-Zoheil** [comment]
Yes. please see [release notes](https://ag-grid.com/changelog/?fixVersion=30.0.0) (particularly breaking changes section) and [blog post](https://blog.ag-grid.com/whats-new-in-ag-grid-30/) for v30.
