### ISSUE TITLE
[BUG] unexpected rendering(duplicate rowid + autoHeight: true)

### ISSUE THREAD

**Issue by arnoldczhang** [ag-grid/ag-grid#7209]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

you can see: https://codesandbox.io/s/ag-grid-packages-forked-ytpmtl?file=/main.js:265-275

<img width="1153" alt="image" src="https://github.com/ag-grid/ag-grid/assets/7811147/039b3ea1-6c65-4efe-b99b-fe3e18816e57">

**Expected behavior**

<img width="1136" alt="image" src="https://github.com/ag-grid/ag-grid/assets/7811147/1215a96f-403f-4d77-8123-d89270bc2a27">

**Please tell us about your environment:**

"ag-grid-community": "^30.2.0",
"ag-grid-enterprise": "^30.2.0"

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

ES7

**Comment by AG-Zoheil** [comment]
Hi @arnoldczhang,

the `node id` needs to be unique. Duplicates can cause issues. If you set them uniquely the grid will render properly - see here: https://plnkr.co/edit/IknJsHxs9nakVRkI?open=main.js. 

Kind regards,
