### ISSUE TITLE
Class constructor VanillaFrameworkOverrides cannot be invoked without 'new' TypeError: Class constructor VanillaFrameworkOverrides cannot be invoked without 'new'

### ISSUE THREAD

**Issue by dmytro-afonin** [ag-grid/ag-grid#7213]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Trying to upgrate from 29 to 30. 
In browser everything working fine. The issue appears during jest tests execution.
Got Class constructor VanillaFrameworkOverrides cannot be invoked without 'new' TypeError: Class constructor VanillaFrameworkOverrides cannot be invoked without 'new'
Environment:
`  
"dependencies": {

    "@ag-grid-community/angular": "~30.2.0",

    "@ag-grid-community/client-side-row-model": "~30.2.0",

    "@ag-grid-community/core": "~30.2.0",

    "@ag-grid-community/styles": "~30.2.0",

    "@ag-grid-enterprise/core": "~30.2.0",

    "@ag-grid-enterprise/excel-export": "~30.2.0",

    "@ag-grid-enterprise/master-detail": "~30.2.0",

    "@angular/animations": "16.2.11",

    "@angular/common": "16.2.11",

    "@angular/compiler": "16.2.11",

    "@angular/core": "16.2.11",

    "@angular/forms": "16.2.11",

    "@angular/platform-browser": "16.2.11",

    "@angular/platform-browser-dynamic": "16.2.11",

    "@angular/router": "16.2.11",

    "@angular/service-worker": "16.2.11",

    "rxjs": "^7.6.0",

    "tslib": "^2.6.0",

    "zone.js": "0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "16.2.8",

    "@angular-devkit/core": "16.2.8",

    "@angular-devkit/schematics": "16.2.8",

    "@angular-eslint/eslint-plugin": "16.2.0",

    "@angular-eslint/eslint-plugin-template": "16.2.0",

    "@angular-eslint/template-parser": "16.2.0",

    "@angular/cli": "~16.2.0",

    "@angular/compiler-cli": "16.2.11",

    "@angular/language-service": "16.2.11",

    "@ngrx/schematics": "16.3.0",

    "@nx/angular": "17.0.2",

    "@nx/cypress": "17.0.2",

    "@nx/eslint": "17.0.2",

    "@nx/eslint-plugin": "17.0.2",

    "@nx/jest": "17.0.2",

    "@nx/js": "17.0.2",

    "@nx/workspace": "17.0.2",

    "@schematics/angular": "16.2.8",

    "@swc-node/register": "~1.6.7",

    "@swc/core": "~1.3.85",

    "@types/jest": "29.5.3",

    "@types/node": "18.16.19",

    "@typescript-eslint/eslint-plugin": "5.62.0",

    "@typescript-eslint/parser": "5.62.0",

    "eslint": "8.46.0",

    "eslint-config-prettier": "9.0.0",

    "eslint-plugin-cypress": "2.15.1",

    "eslint-plugin-import": "latest",

    "eslint-plugin-jsdoc": "latest",

    "eslint-plugin-prefer-arrow": "latest",

    "jest": "29.6.1",

    "jest-environment-jsdom": "29.5.0",

    "jest-junit": "^16.0.0",

    "jest-preset-angular": "13.1.1",

    "jest-sonar": "^0.2.16",

    "jsonc-eslint-parser": "^2.1.0",

    "lite-server": "^2.6.1",

    "nx": "17.0.2",

    "postcss-import": "~15.1.0",

    "postcss-preset-env": "~9.0.0",

    "prettier": "3.0.0",

    "ts-jest": "29.1.1",

    "ts-node": "10.9.1",

    "typescript": "~5.1.6"
  },`

already tried different resolver strategies - didn't help. Switching back to ag-grid v29 is helping. Definitely something changed in v30

**Comment by AG-Zoheil** [comment]
Hi @dmytro-afonin,

You are right and there have been some changes since `v30`. Please have a look at the following blog post which should guide you through this: https://blog.ag-grid.com/ag-grid-es-modules-and-commonjs/.

I hope this helps.

Kind regards,
