### ISSUE TITLE
Pinned columns do not respect column flex

### ISSUE THREAD

**Issue by skykasko** [ag-grid/ag-grid#7217]
**I'm submitting a ...**

```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/atqctHSD0fTL5ajk?open=app%2Fapp.component.ts&preview

**Current behavior**
When columns are pinned (via `pinned: "left"` or `pinned: "right"`) and have a `flex` value set, the `flex` value is ignored / has no effect. 

In the Plunker example, note that column A has a fixed width despite its flex property, but that if the `pinned: "left"` line is removed, then column A's width expands as expected.

**Expected behavior**
Pinning a column does not affect its width, or at least does not stop flex sizing from working. I cannot find any mention in the [column flex](https://www.ag-grid.com/angular-data-grid/column-sizing/#column-flex) documentation or the [column pinning](https://www.ag-grid.com/angular-data-grid/column-pinning/) documentation of pinning and flex being incompatible.

**Please tell us about your environment:**

* **AG Grid version:** 30.2.0

* **Browser:**
  * Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
  * Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0

* **Angular version:** 16.2.11

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hello @skykasko,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-9705**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
