### ISSUE TITLE
sanitize ag-grid to prevent xss

### ISSUE THREAD

**Issue by Sudeepa1949** [ag-grid/ag-grid#7219]
I'm submitting a ... (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question

**Current behavior**

If a string value containing HTML comes into the grid, the grid just displays it without sanitizing the data, In some instances, this causes the grid to break

if added `<i onwheel=alert(244)> Scroll over me </i>` as data to table, onwheeling I am getting alert popup.
see [here](https://plnkr.co/plunk/zvi5J6L441OouiW8) for the issue
**Expected behavior**

**What is the motivation / use case for changing the behavior?**

Preventing the grid from breaking due to unsanitized data in the grid (per example)
prevent XSS issues

**Please tell us about your environment:**

**OS:** mac 14 , Bowser all

**ag-Grid version:**  29.3.3

**Browser:**
Both safari and Chrome

**Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @Sudeepa1949,

Thank you for raising this on GitHub.

HTML sanitisation of **custom cell renderers** will be the responsibility of the application developer. This isn't done by AG Grid.

Kind regards,
Zoheil
