### ISSUE TITLE
 Bug: When scrolling horizontally with a custom headerComponent, the vertical scrollbar returns to the top.

### ISSUE THREAD

**Issue by RichardMoonton** [ag-grid/ag-grid#7222]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hello everyone:
I encountered a scrolling problem when using AgGrid.  When using a custom headerComponent, if I scroll vertically for a distance first, and then scroll horizontally, the vertical scrollbar will return to the top.  This problem is always reproducible.  I hope someone can help me provide a solution, thank you!

* **AG Grid version:** 30.2.0
* **Browser:** Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @RichardMoonton,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
