### ISSUE TITLE
Filter Api is enterprise?

### ISSUE THREAD

**Issue by somuda86** [ag-grid/ag-grid#7223]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
Hello everyone:
I encountered that from Aggrid 28.x.x setFilterModel() api is not working for us. When I see documentation in https://www.ag-grid.com/javascript-data-grid/filter-api/ its not marked enterprise feature. But when we use it we observe that its not working and in console log we get a warning " AG Grid: setFilterModel() - unable to fully apply model, filtering disabled for colId: type". When we looked into it filter in gridOptions is always `false`. We tried making it `true` but its not happening. Any suggestions are welcome  thank you!

AG Grid version: 30.2.0
Browser: Chrome
Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @somuda86,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by somuda86** [comment]
@AG-Zoheil we just want to know the above is enterprise feature or not. We will try to give a plunkr for this but I dont see value in that.

**Comment by AG-Zoheil** [comment]
Hi @somuda86,

the API itself is not enterprise, however it depends what type of filter you are using.

For example see this example running on community: https://plnkr.co/edit/0YObH0x6e568vFzS?open=main.js

If you sort by "Sport ends with G" you will get a warning message that this specific filter type is not available outside of enterprise. But if you sort by "Age below 25" the filter works.

The set Filter is an enterprise feature as you can see [here](https://www.ag-grid.com/javascript-data-grid/filter-set/).

I hope this helps and answers your question.

Kind regards,
Zoheil.
