### ISSUE TITLE
so the vertical scroll bar is not going further down 

### ISSUE THREAD

**Issue by disismeg31** [ag-grid/ag-grid#7225]
I'm submitting a bug report  which i encountered currently with ag-grid
 
scenario description : like if there are 17 rows and there is an option for  viewing 10, 50 and 100 data  
 

Code referance:
 //the HTML code :
`
<ag-grid-angular style="width: 95%; height: 660px;" class="ag-theme-alpine" [gridOptions]="gridOptions"
            (gridReady)="onGridReady($event)" (cellClicked)="onCellClicked($event)"></ag-grid-angular>

`
//the ts code :

`
  gridOptions: GridOptions;
  pageSize = '10';

this.gridOptions = <GridOptions>{
      pagination: true,
      rowHeight: 50,
      maxRenderedRowCount: 1000,
      enableRangeSelection: true,
      wrapText: true,
      autoHeight: true,
      cellStyle: {"wordBreak": "normal"},
      columnDefs: [
        { field: 'sl_no', etc etc ..........................},
        { field: 'user',  etc etc ..........................},
        { field: 'receipt_url',  etc etc ..........................},
        { field: 'transaction_no', etc etc .......................... },
        { field: 'amount', etc etc ..........................},
        { field: 'date',  etc etc .......................... },
      ],
      rowData: [  ],
      paginationPageSize: 10
    };

onPageSizeChanged(value) {
    if (this.gridOptions.api) {
      this.gridOptions.api.paginationSetPageSize(Number(value));
       }
    }

`

Expected behaviour :  
the vertical scroll is supposed to scroll down till the 17th row 
 
Current behavior :
the when we select the option 50 ( which means viewing 50 data) - the vertical scroll bar is not going down after like 15th row
 
 About your environment :
 OS : Windows, IDE :  VS code, package manager : npm, framework : Angular 15

 AG Grid version : 
29.3.2 community edition

**Comment by AG-Zoheil** [comment]
Hi @disismeg31,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by disismeg31** [comment]
so i can only provide a small screenshort of the issue - due to privacy concerns

https://github.com/ag-grid/ag-grid/assets/106829716/b530437f-84b8-4495-a763-bf86dda35623

**Comment by AG-Zoheil** [comment]
Hi @disismeg31,

Thank you for the video. I'm afraid we need a reproducible scenario to be able to investigate it.

Are you able to replicate this behaviour on any of our examples. For example you can use this simple example and adjust the code to match your set up: https://plnkr.co/edit/jiD8ucdqi1SqEuHr?open=app%2Fapp.component.ts.

Thanks!

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
