### ISSUE TITLE
Is there a way to remove the number of rows being grouped?

### ISSUE THREAD

**Issue by goranmandiccrs** [ag-grid/ag-grid#7227]
The title sums it up, but the picture is more accurate: can I remove these numbers somehow?
![image](https://github.com/ag-grid/ag-grid/assets/43639874/1db9b904-7e2d-4e1f-b464-08e1e9696b49)

**Comment by AG-Zoheil** [comment]
Hi @goranmandiccrs,

Please see here: https://ag-grid.com/javascript-data-grid/grouping-single-group-column/#group-column-configuration.

Kind regards,
Zoheil

**Comment by goranmandiccrs** [comment]
@AG-Zoheil I suspected that there was a prop, but I just couldn't find it in the docs. Thank you very much!
