### ISSUE TITLE
How to print Server side master detail

### ISSUE THREAD

**Issue by Maxranderson** [ag-grid/ag-grid#7229]
**I'm submitting a ...**
```
[] bug report
[] feature request
[X] support request
```
Hello folks, I'm trying to print my Ag-grid table but I'm having issues with the master detail. I managed to make Ag-grid visible using these pieces of code.

```
@media print {

    body *{
      visibility: hidden;
    }

    .show-on-print {
      .ag-theme-alpine, .ag-theme-alpine * {
        visibility: visible;
      }
    }
    
  }
```
```
//Triggered by a button and 'element' contains the Ag-grid
element.classList.add('show-on-print');
  api.sizeColumnsToFit();
  api.setDomLayout("print");
```
When I try to print, the master detail is not visible. I tried to find the correct class to make it visible but no luck. So basically, my question is how can I make my master detail visible when printing? Which css class should I make visible? What am I missing?
I'm using the Server Side row model by the way.

**Please tell us about your environment:** Angular 15.1.0

* **AG Grid version:** 30.2.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

* **Language:** TypeScript 4.9.4

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
