### ISSUE TITLE
update from version 26 to 30 broke by cell editor react 

### ISSUE THREAD

**Issue by cristoferrao** [ag-grid/ag-grid#7230]
Hi, In aggrid I added Search using typeahead before in version 26 I used to search values in cell editor, had set typeahead to cell editor and then set values to cell  but after updating to  "ag-grid-react": "^30.2.1", and "react-bootstrap-typeahead": "^6.3.2", with react   "react": "^18.2.0", from 17 
 

now in the new version when i press enter I doesn't work onchange function in typeahead don't run so not getting value it stop the editing and returns empty

it works when doing onclick from mouse 
https://stackblitz.com/edit/stackblitz-starters-qzfo2x?file=src%2FApp.tsx

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
