### ISSUE TITLE
Row styles not suppporting text decoration properties like underline and strikethrough

### ISSUE THREAD

**Issue by siddhant928** [ag-grid/ag-grid#7232]
**I'm submitting a bug
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Row styles doesn't support text decoration

**Expected behavior**
Row styles should support text decoration properties like underline, strikethrough

Plunkr - 
https://plnkr.co/edit/XXeVOhKeIS9h6Tse

**Comment by AG-Zoheil** [comment]
Hi @siddhant928,

Thank you for submitting this via GitHub.

This is not a bug, you can customise text-decoration via css.

See here: https://plnkr.co/edit/gYUP4M0bKvXOwRLV?open=index.jsx

Kind regards,
Zoheil
