### ISSUE TITLE
AgGrid Custom Floating filter - agSetColumnFilter not setting filter model with setModel()

### ISSUE THREAD

**Issue by amitgandole** [ag-grid/ag-grid#7234]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I have implemented custom dropdown filter and treating it as floatingFilter.

    export class MultiSelectFilterComponent implements IFloatingFilterAngularComp, OnDestroy {}

I have method called applyFilter which does some logical calculation and at the end it sets model in ag-grid filter like below

    const filter = this.params.api.getFilterInstance(this.colId);
    const filterModel = this.filterData.filter(dropdownData => dropdownData.selected).map(value => value.value);
    const filterObjectValue = filterModel.length > 0 ? filterModel : [this.noneFilter.value];
    filter.setModel({
      values: filterObjectValue
    });
 
    this.params.api.onFilterChanged();

Here is question : 

When I get `filterObjectValue : [1,2,3,4,5]` it does not get set in appliedModel. But when I convert this to Array of strings like this `filterObjectValue : ["1","2","3","4","5"]` this gets set in appliedModel. 

How I get to know about appliedModel? When I print `filter` variable, I get know in appliedModelValues there.

I am debugging this weird bug like hell but not getting any solution. I read ag-grid library code and there was some condition where I found below code line

    existingFormattedKeys_1.get(formattedKey)

Here whoever written this line trying to fetch formattedKey (which is integer) from existingFormattedKeys_1 map (which is map of keys in string). Obviously it will return nothing and flag is undefined. Due to this, Filter is not getting set in model and code flow is breaking.

Anyone have idea about this?

**Current behavior**
Filter is not getting set in model.

**Expected behavior**
Filter should get applied.

* **AG Grid version:** 30.2.1

**Comment by eabris** [comment]
Having the same issue with custom filters, seems like setModel is not working properly.

**Comment by AG-Zoheil** [comment]
Hi @amitgandole and @eabris,

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by amitgandole** [comment]
Hello @AG-Zoheil ,

Hello Alberto, 

I have tried to reproduce issue here and it seems its not working on this plunkr too. 

Steps: 

1. Click on open filter
2. Try to apply any filter or multiple selection of filters.

Expectation here is, When I call setModel with filterValues, It should store array of numbers.
LINK : https://plnkr.co/edit/vKX3S1oMaGqeMcA8

Same thing is happening when I am trying to apply filter with single number also. I am trying to create plunkr for that too but due to data restrictions its taking time. 

Versions of project:

AgGrid:
    "@ag-grid-community/angular": "30.0.0",
    "@ag-grid-community/client-side-row-model": "30.0.0",
    "@ag-grid-community/core": "30.0.0",
    "@ag-grid-community/infinite-row-model": "30.0.0",
    "@ag-grid-community/styles": "30.0.0",
    "@ag-grid-enterprise/clipboard": "30.0.0",
    "@ag-grid-enterprise/core": "30.0.0",
    "@ag-grid-enterprise/filter-tool-panel": "30.0.0",
    "@ag-grid-enterprise/menu": "30.0.0",
    "@ag-grid-enterprise/set-filter": "30.0.0"

Angular: 
    "@angular/animations": "16.2.4",
    "@angular/cdk": "16.2.3",
    "@angular/common": "16.2.4",
    "@angular/compiler": "16.2.4",
    "@angular/core": "16.2.4",
    "@angular/forms": "16.2.4",
    "@angular/google-maps": "15.2.9",
    "@angular/platform-browser": "16.2.4",
    "@angular/platform-browser-dynamic": "16.2.4"

Please let me know if anything is required other than this.

**Comment by AG-Zoheil** [comment]
Hello,

Our team had a look and the example you've provided doesn't seem right. In the example you are trying to apply an array of arrays, and the Set Filter does not work like that.
 
However, the issue described in your question is not an issue, and is expected behaviour. Please read the following part of our docs: https://ag-grid.com/angular-data-grid/filter-set-filter-list/#filter-value-types.

> The Set Filter internally maintains the original type of the cell values, but always uses strings for the keys. E.g. if the cell contains a number, the Filter Model will contain those numbers converted to strings.

I hope this helps.

Kind regards,
Zoheil

**Comment by amitgandole** [comment]
Hello @AG-Zoheil ,

Surprised you marked this as closed without proper solution or reason. 
Even if this is array of array I would like to know more from your team how can I achieve filter in this scenario. I invested my time to create plunkr to reproduce the issue since you asked for it.

I have created another example in below plunkr.
https://plnkr.co/edit/cfutBpxvE1ZQ06Ns

Here you can see there is no "Array of Array" getting set in filter and its plain numeric values. 

1. When I am trying to set plain SINGLE DIGIT numeric value in filter model with "filter.setModel" method, You can clearly debug and hover over appliedModel of "filter" variable. You can see Array(0) there. Which is strange, Why its strange is explained in point no. 2.
2. When I convert same numeric value to "STRING" data type (Adding .toString method to value), "filter.setModel" works, Which means if you hover over "filter" variable in "applyFilter" method, You can see values and model is applied in appliedModel and my filter works. 

I am not sure in which version this bug got introduced, But we have initially built ag-grid wrapper on 27.3.0 version and upgraded it to 30.0.0. Initially this was not the case and all filters were working properly. Since from upgrade, I got bugs and issues raised with my 20 filters (Which was clearly working before). Even I tried to downgrade to 27.3.0 version and found out that both "STRING" and "Numeric" data type filters are not working. 

I have debugged this issue in ag-grid code base also which I have mentioned in above description too.
`existingFormattedKeys_1.get(formattedKey)`
This is mapping integer keys with string keys. 

> Here whoever written this line trying to fetch formattedKey (which is integer) from existingFormattedKeys_1 map (which is map of keys in string). Obviously it will return nothing and flag is undefined. Due to this, Filter is not getting set in model and code flow is breaking.

Which clearly means filterObjectValue : [1,2,3,4,5] will not work (Which was working previously) and filterObjectValue : ["1","2","3","4","5"] will work and we have to convert integers to string to make filter work.

I am seeking suggestion/solution/help for "Array of Array" filter too if your team can give any. 

Thank you for your attention, and I sincerely hope for a prompt and constructive resolution.

**Comment by AG-Zoheil** [comment]
Hi @amitgandole,

Thanks for getting back and also thank you for providing the plunkers.

Did you get a chance to look at the documentation I linked in my previous comment?

The below excerpt from the documentation should answer your question. Beyond that, I'm afraid, we do not provide custom support via GitHub and only investigate bugs.

The Set Filter internally maintains the original type of the cell values, **but always uses strings for the keys**. E.g. if the cell contains a number, the Filter Model will contain those numbers converted to strings, but if you specified a value formatter, that would use the values with type number. Note that in AG Grid versions **prior to 29.0**, the Filter Model values were converted to strings for everything. This behaviour can be replicated by setting filterParams.convertValuesToStrings = true, but the setting is deprecated.

Kind regards,
Zoheil
