### ISSUE TITLE
Bug: No way to designate row headers

### ISSUE THREAD

**Issue by frastlin** [ag-grid/ag-grid#7237]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Visit:
https://plnkr.co/edit/?open=index.jsx&preview

**Current behavior**

There is no th element or rowheader attribute around the athlete column, despite athlete being an important row header.

**Expected behavior**

There should be a th element around or rowheader attribute attached to row headers as described in the [table documentation for](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th) and the [rowheader documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowheader_role). Without the ability to designate rowheaders, most AG-Grid tables violate [Web Content Accessibility guidelines 1.3.1 level A](https://www.w3.org/TR/WCAG20-TECHS/F91.html).
This is a critical and breaking change that needs to be fixed, or no institution that needs to follow digital accessibility laws can use AG-Grid.
I see that in the [AG-Grid pipeline](https://www.ag-grid.com/pipeline/) this is marked as a feature request in the backlog number AG-5201. This is a bug and not a feature request and is high severity. We will need to stop using AG-Grid if this WCAG level a accessibility violation is not fixed in the next month.

* **Browser:**

Impacts all browsers.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Impacts all languages.

**Comment by AG-Zoheil** [comment]
Hi @frastlin,

Thank you for raising this on GitHub.

Firstly, there is currently an existing workaround to achieve the desired outcome which has been noted in the "More information" section of **AG-5201**.

Secondly, this has been logged as a feature request and not a defect because it is functionality that was not originally in scope of the product. So it's not classified as a bug as such but as a requirement that was added later on and a feature that we agree would be a valuable addition to our product.

In any case, I will add your support/interest to the item in our backlog and we are always keen to improve our product so that our users will be able to meet their necessary requirements.

Thanks again!

Kind regards,
Zoheil

**Comment by frastlin** [comment]
Hello Zoheil,
Can you please paste the work-around here, because I'm not seeing it in AG-5201. I see a similar bug request, but I'm not seeing a work-around.

A bug is an unexpected problem with software or hardware. Since the HTML specification explicitly calls for row headers, the fact I can't specify row headers is an unexpected problem. The fact it was not included in a particular scope just means that parts of the basic HTML specification were left out of the scope, I'm sure unintentionally, since  everything else seems to be included.

**Comment by AG-Zoheil** [comment]
Hello,

Of course. Please open the following plunker and use your screen reader: https://plnkr.co/edit/8k7taHfEL2AKyBML.

Whilst on the subject, could you please clarify your expectation of how this should work:

Would you expect to (1) explicitly set a column as the rowHeader column or (2) should the left-most one be automatically designated as rowHeader column (what if it's moved, hidden, or another column becomes left-most via pinning?)?

We appreciate your feedback.

**Comment by frastlin** [comment]
Thank you, this is very helpful!
In an ideal world, the developer sets the header column and header row to be whatever they want (it could be the very right row, although by default it should be the very left row, so number 1 above). In AG-Grid because users have freedom to hide and Reorganize columns, they should be able to designate a new row and column header. This is what Google Sheets, Excel, and Microsoft Word allow.
