### ISSUE TITLE
ag-charts-community github links points here and not at ag-charts repo

### ISSUE THREAD

**Issue by benlesh** [ag-grid/ag-grid#7239]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

If you go to the [npm page for ag-charts-community](https://www.npmjs.com/package/ag-charts-community), it points to the incorrect repository (this one):

![image](https://github.com/ag-grid/ag-grid/assets/1540597/1e57c503-0581-41e9-b78c-f7e2aabb1559)

**Expected behavior**

It should point to where the actual code is. I see you have issues disabled there, that's fine, just put something in the readme about reporting bugs here, but the repo should point at the code the npm package is built from.

[npm has pretty good documentation about what should be in the `repository` field](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository). I don't _think_ it's a violation of their TOS, but I wouldn't deviate if I was running a business around this.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

n/a

* **Browser:**

n/a

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
n/a

**Comment by StephenCooper** [comment]
Hi Ben,

Thanks for highlighting this! 

We will resolve in our next release which is also when we will migrate the issue reporting from ag-grid/ag-grid into the ag-charts repo for v31 due the end of this month.

https://github.com/ag-grid/ag-charts 

![Screenshot 2023-11-09 at 09 51 13](https://github.com/ag-grid/ag-grid/assets/20125490/cdb5a2db-d770-4f65-a4e8-ee9d9899df53)

Thanks!
