### ISSUE TITLE
No tree shaking with rollup

### ISSUE THREAD

**Issue by slax57** [ag-grid/ag-grid#7241]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Some context**
We are the maintainers of the [react-admin](https://github.com/marmelab/react-admin) framework.

As part of our Enterprise Edition, we provide a [package](https://marmelab.com/ra-enterprise/modules/ra-editable-datagrid#datagridag) that includes a React component, integrating our framework with **ag-grid**.

This package, however, includes other features as well, and we would like our customers to have **ag-grid** included in their JS bundle **only if they actually use ag-grid** in their code.

**Problem:** it seems like ag-grid is included in the bundle (at least by Rollup) regardless.

**Providing a Reproducible Scenario**
You can reproduce the issue with this [codesandbox](https://codesandbox.io/p/sandbox/wizardly-lena-cnjzt8?welcome=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clor1tyqo00072v6jtyanjt5y%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clor1tyqn00032v6joik4jitp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clor1tyqo00052v6jkf18bumn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clor1tyqo00062v6jkx1ta8lc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clor1tyqn00032v6joik4jitp%2522%253A%257B%2522id%2522%253A%2522clor1tyqn00032v6joik4jitp%2522%252C%2522activeTabId%2522%253A%2522clor2841001dx2v6j5i4p3kg3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clor1tyqn00022v6jknwpwis3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdist%252Fstats.html%2522%252C%2522id%2522%253A%2522clor1vrp700fu2v6j28hm1gwz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clor26wg600tt2v6jufoiphep%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clor2841001dx2v6j5i4p3kg3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clor1tyqo00062v6jkx1ta8lc%2522%253A%257B%2522id%2522%253A%2522clor1tyqo00062v6jkx1ta8lc%2522%252C%2522activeTabId%2522%253A%2522clor27gi501832v6jq4if160q%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clor1uvfa00ai2v6j0p0ukohi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Findex.html%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522clor27gi501832v6jq4if160q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fstats.html%2522%257D%255D%257D%252C%2522clor1tyqo00052v6jkf18bumn%2522%253A%257B%2522id%2522%253A%2522clor1tyqo00052v6jkf18bumn%2522%252C%2522activeTabId%2522%253A%2522clor1v1hc00d62v6jevykmd4g%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clor1tyqo00042v6j4zku6z3q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clor1tywv000peei32i1xe8np%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clor1utkn008w2v6jasw626sa%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clor1v1hc00d62v6jevykmd4g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clor1v1jc000veei35d8k11zb%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

In `src/grid`, the `index.ts` files exports 3 grid components:
- One using ag-grid
- One using MUI-X Datagrid
- One using simple html (called SimpleGrid)

Currently, `App.tsx` only uses and imports `SimpleGrid`.

**Current behavior**

If you run `npm run build` in the terminal, and then `npm run serve` (to serve the generated `stats.html` static file), then you will see in the rollup visualizer that **ag-grid** is included in the bundle, although it is not used in the app at all.

![image](https://github.com/ag-grid/ag-grid/assets/14542336/1ecf9187-54c2-4582-94e0-317db703808f)

**Expected behavior**

We would have expected **ag-grid** **not** to be included in the bundle, since it is not used.

In the same way, observe how MUI is **not** included in the bundle, although it is exported in the same way as the component using ag-grid. We would expect the same with ag-grid.

Thanks.

**Please tell us about your environment:**
Operating system: linux,
IDE: VSCode,
package manager: npm
bundler: vite (+ rollup)

* **AG Grid version:** 30.2.1

* **Browser:**
Chrome

* **Language:** TypeScript 5.0.2 | ES2020

**Comment by slax57** [comment]
I forgot to mention: I already tried switching to [modules instead of packages](https://ag-grid.com/react-data-grid/packages-modules/) (the sandbox uses modules), but it did not help.

**Comment by AG-Zoheil** [comment]
Hello @slax57,

Thank you for the suggestion.

We agree we can make some changes here and that this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-10032**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
