### ISSUE TITLE
`getMainMenuItems` has no effect on General Menu Tab

### ISSUE THREAD

**Issue by cristiano-belloni** [ag-grid/ag-grid#7244]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I want to only show `pinSubMenu` in the General Menu Tab menu. If I specify `getMainMenuItems` as option in my ag-grid **functional** React component like this:

```javascript
getMainMenuItems={() => ['pinSubMenu']}
```

The menu shows default General Menu Tab and `getMainMenuItems` is never called.

**Expected behavior**

`getMainMenuItems` is never called and the General Menu Tab in the column header should show only "Pin"

**Please tell us about your environment:**
Windows

* **AG Grid version:** 25.3.0
Unfortunately I can't check with the latest ag-grid, since I'm using Enterprise in a restricted environment.

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 4.5.2

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
