### ISSUE TITLE
How to store the grid API in order to access it from sibling components (redux?)

### ISSUE THREAD

**Issue by AnabelSalomone** [ag-grid/ag-grid#7247]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello, in my React project I'm trying to use some functionalities available from the Grid api from other components. For this I stored the API in the context. As my app grew wider I decided I should use Redux instead of the context api, so I migrated everything to a redux store. BUT the API is non-serializable so it shouldn't be stored there (and it will break the devtools too...). Does anyone know how can I store the API so it is accesible from other components? (mainly sibling components, not necessarily children) 

Thanks in advance

Using AG-grid 30.2.0

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
