### ISSUE TITLE
Could not find a declaration file for module 'ag-grid-solid'

### ISSUE THREAD

**Issue by wonrax** [ag-grid/ag-grid#7252]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Importing `ag-grid-solid` in Typescript Solid JSX results in import error.

```
Could not find a declaration file for module 'ag-grid-solid'.
  '/home/wonrax/code/qbitui/node_modules/ag-grid-solid/dist/esm/index.js'
  implicitly has an 'any' type.
There are types at
  '/home/wonrax/code/qbitui/node_modules/ag-grid-solid/dist/types/index.d.ts', but
  this result could not be resolved when respecting package.json "exports". The
  'ag-grid-solid' library may need to update its package.json or typings.ts(7016)
```

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "Bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}

```

**Expected behavior**

No import error and type hints and code completion available in the IDE.

**Please tell us about your environment:**
Fedora Linux 38
Node 20.3.1
NPM 9.6.7

* **AG Grid version:** 30.2.1

* **Language:** TypeScript 5.2.2

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by zjhken** [comment]
I got this issue in VS Code as well.
ag-grid-solid version is 31.1.1
The solution is to add one more exports to the pakcage.json of ag-grid-solid
I cannot find the repo for ag-grid-solid in Github, so I will paste the code here
```json
  "exports": {
    ".": {
      "import": "./dist/esm/index.js",
      "browser": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js",
      "node": "./dist/cjs/index.js",
      "types": "./dist/types/index.d.ts"
    }
  },
```
the added line is the `"types": "./dist/types/index.d.ts"`

**Comment by cossieB** [comment]
d

> I got this issue in VS Code as well. ag-grid-solid version is 31.1.1 The solution is to add one more exports to the pakcage.json of ag-grid-solid I cannot find the repo for ag-grid-solid in Github, hence I am not able to raise PR, So I will paste the code here
> 
> ```json
>   "exports": {
>     ".": {
>       "import": "./dist/esm/index.js",
>       "browser": "./dist/esm/index.js",
>       "require": "./dist/cjs/index.js",
>       "node": "./dist/cjs/index.js",
>       "types": "./dist/types/index.d.ts"
>     }
>   },
> ```
> 
> the added line is the `"types": "./dist/types/index.d.ts"`

This works. Thanks
