### ISSUE TITLE
<!--AG-FAKE-VERTICAL-SCROLL--> Issue

### ISSUE THREAD

**Issue by wmbutler** [ag-grid/ag-grid#7255]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behaviour**

When using expanding rows (master/detail), we are seeing the AG-FAKE-VERTICAL-SCROLL allocate a large amount if vertical space.

**Expected behaviour**

This issue was introduced with 23.2.0. In 28.2.1

**Please tell us about your environment:**
OS X, nodejs 18.17.2

* **AG Grid version:** X.X.X
23.2.0, 28.2.1

* **Browser:**
Chrome, latest

**Comment by Mavrin** [comment]
I recommend checking if the parent container of ag-grid does not have the `word-wrap` and `white-space` CSS properties set.

**Comment by wilbsy** [comment]
> I recommend checking if the parent container of ag-grid does not have the `word-wrap` and `white-space` CSS properties set.

Can you elaborate?

**Comment by Mavrin** [comment]
I had the such issue. Grid was render in div with next style
```css
  word-wrap: break-word;
  white-space: break-spaces;
```
I reseted these property to initial and it fixed issues with wrong scroll heigth
```css
  word-wrap: initial;
  white-space: initial;
```
![Screenshot 2023-11-07 at 18 36 33](https://github.com/ag-grid/ag-grid/assets/1193817/1cef254a-5f30-475a-bf40-1150c1a9bee9)

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
