### ISSUE TITLE
[Sparklines] Access row data from sparklines marker formatter

### ISSUE THREAD

**Issue by M0unir** [ag-grid/ag-grid#7256]
**I'm submitting a ...** 
```
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
This is about the Ag Grid Sparklines feature, more specifically about the Points of Interest section of the docs. I see that the supported points of interest that come with the **MarkerFormatterParams** are as follow:
- First and Last
- Minimum and Maximum
- Positive and Negative**

My use case needs more customized access to each data point which after testing I can access through the xValue property of the **MarkerFormatterParams**. Which returns the index number of the current data point we are trying to format.

However, I would like to format each data point (Green or Red for instance) based on external data (row data for example). From the docs, It doesn't seem like the **MarkerFormatterParams** has access to the current row data (params.data like other callbacks do).

Is there a way to pass the current row data to the sparkline marker formatter for more custom formatting of each data point?

**Here is a plunker example:**
[Sparklines Plunkr example](https://plnkr.co/edit/PsjByAIwDXUdmsAQ?open=index.jsx)

**Please tell us about your environment:**

* **AG Grid version:** 30.2.0 (Latest)

* **Browser:** Chrome

* **Language:** all

**Comment by M0unir** [comment]
It seems that the Sparklines Tooltips at least do support access to row data through the **context** object that holds the data as explained in ag grid docs here: [https://www.ag-grid.com/react-data-grid/sparklines-tooltips/#accessing-row-data](url)

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
