### ISSUE TITLE
FACING ISSUE WHILE TRYING DRAG AND SELECT CELLS FOR REAL TIME UPDATES IN THE GRID

### ISSUE THREAD

**Issue by Arj20** [ag-grid/ag-grid#7259]
I am using Lightstreamer along with aggrid to display data on the grid.
There is one requirement where we need to calculate average and total by selecting multiple cells by either dragging or selecting cells individually.

Aggrid provides certain apis to select these cells out of the box. I have tried using them but it isn’t working. This could happen because we are having the data change frequently in the cells.
**APIs provided by aggrid**
![image](https://github.com/ag-grid/ag-grid/assets/30536355/3e44924b-e34d-42af-b942-8ccb17795aa6)

CURRENT SCREEN TO BE DRAGGED AND SELECTED JUST LIKE IN EXCEL FOR TOTAL AND AVERAGE

![image](https://github.com/ag-grid/ag-grid/assets/30536355/bfaee3d1-124a-42f1-93d5-1a48539d1fcd)

Can someone please help me with this if they had faced similar kind situation

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
