### ISSUE TITLE
require() of ES Module in nextjs 13.4.1

### ISSUE THREAD

**Issue by diliptekwani** [ag-grid/ag-grid#7262]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
Hello there, I am trying to upgrade AG grid to new version which is from 28 to 30. And I am using nextjs 13.4.1 but having issue while bumping new version of ag grid to v30 in my project and getting require() of ES Module error.

![image](https://github.com/ag-grid/ag-grid/assets/87890029/a8b3efd7-8311-4986-ae40-e98d44313830)

**Please tell us about your environment:**

* **AG Grid version:** 30.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* Typescript: v5

**Comment by AG-Zoheil** [comment]
Hi @diliptekwani,

Please have a look at this blog post of ours - the guidance in there resolves your issue: https://blog.ag-grid.com/ag-grid-es-modules-and-commonjs/

Kind regards,
Zoheil
