### ISSUE TITLE
ag-grid-angular issue with jest for version 30

### ISSUE THREAD

**Issue by GeorgianStan** [ag-grid/ag-grid#7264]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[Repo link](https://github.com/GeorgianStan/angular-ag-grid) with the error. In this repo is a basic usage of the ag-grid with Angular.
Download the repo and run the following commands:
1. `npm i`
2. `npx nx serve angular-ag-grid` (This will open the app and the table will be visible. Here all works as expected.)
3. `npx nx test angular-ag-grid` (This will run the unit test with Jest and it will **crash**.).

**Current behavior**
After updating to the new major version +30, tests with Jest fail with the following error.

```bash
 TypeError: Class constructor VanillaFrameworkOverrides cannot be invoked without 'new'
```

**Expected behavior**
I expect to be able to run tests with Jest.

**Please tell us about your environment:**
I'm using Ag Grid Modules version `30.2.1`
```
"@ag-grid-community/angular": "^30.2.1",
"@ag-grid-community/client-side-row-model": "^30.2.1",
"@ag-grid-community/infinite-row-model": "^30.2.1",
"@ag-grid-community/styles": "^30.2.1"
```
Angular version `16.2.0` and Jest version `29.4.1`. 
Node version `18.10.0` and Windows 10.
The entire list of dependencies can be viewed here [here](https://github.com/GeorgianStan/angular-ag-grid/blob/master/package.json).

**Comment by StephenCooper** [comment]
Hi @GeorgianStan,

Could you try following the steps documented here : https://ag-grid.com/angular-data-grid/testing/

**Comment by StephenCooper** [comment]
Yes, the case of tsconfig.json paths not being handled is unfortunate. 

I know there is a workaround by including moduleNameMapper config which matches the paths. This enables Jest to mimic the tsconfig paths setting.

```ts
 moduleNameMapper: {
    "@nx-test/util-core": "<rootDir>/../util-core/src/index.ts",
  },
```

We will review this to see if there is anything else we can suggest.

**Comment by GeorgianStan** [comment]
Same problem as the one mentioned by @StephenCooper. I switched from Jest to Cypress Component Testing until this is fixed.

**Comment by SlavikSurminskiy** [comment]
> Hi @StephenCooper, thanks for the documentation.
> 
> In my case, adding the resolver is causing the paths defined in tsconfig.json to be ignored causing more issues. Is there any alternate way to configure the unit tests for ag-grid v30 to use the CommonJS ES5?

Hi @SandeepThomas , I'm facing the same problem. The answer provided by @StephenCooper can solve the problem. Definitely, we can define moduleNameMapper for all paths from the tsconfig file. I have a lot of items in 'paths'. Copypasting all those items from tsconfig.json to jest.config is not convenient. Take a look at this example of the resolver file. It works fine for me. The main idea is to use a resolver from nx for all paths except ag-grid.

`const nxResolver = require('@nx/jest/plugins/resolver');

module.exports = (path, options) => {
  const packageName = path.split('/')[0];

  const isAgGridDependency = packageName.startsWith('@ag-grid');

  if (!isAgGridDependency) {
    return nxResolver(path, options);
  }

  return options.defaultResolver(path, {
    ...options,
    packageFilter: (pkg) => {
      const packageName = pkg.name;
      if (packageName === '@ag-grid-community/angular') {
        return {
          ...pkg,
        };
      }
      return {
        ...pkg,
        // default to use the CommonJS ES5 entry point for Jest testing with AG Grid
        main: './dist/cjs/es5/main.js',
      };
    },
  });
};`

**Comment by AG-Zoheil** [comment]
Thank you all for your comments and contributions.

We will be closing this issue for now as the approach advocated by @StephenCooper solves the problem. Please note, this does not mean there will be no enhancements to this area of our grid in the future.

**Comment by rs-rauch** [comment]
Hey there.

For me it does not solve everything. Maybe I'm missing something important.
1. I'm not using NX, so it is not exactly the same scenario
2. Still on Angular 15 (this could be an issue!?), with AG Grid 30.0.5
3. I have also checked [Issue 6828](https://github.com/ag-grid/ag-grid/issues/6828) 
4. And tried to follow this [github.com/McSim182/ag-grid-jest](https://github.com/McSim182/ag-grid-jest/tree/fix/custom-resolver)

After adding the resolver the ` TypeError: Class constructor VanillaFrameworkOverrides cannot be invoked without 'new'` was gone but other libs caused the test fail.

resolver.js
```js
module.exports = (request, options) => {
	return options.defaultResolver(request, {
		...options,
		packageFilter: (pkg) => {
			const packageName = pkg.name;
			if (packageName === '@ag-grid-community/angular' || packageName === 'ag-grid-angular') {
				return {
					...pkg
				};
			}
			const agDependency = packageName.startsWith('@ag-grid') || packageName.startsWith('ag-grid');
			return {
				...pkg,
				// default to use the CommonJS ES5 entry point for Jest testing with AG Grid
				main: agDependency ? './dist/cjs/es5/main.js' : pkg.module || pkg.main
			};
		}
	});
};
```

The jest.config.js
```js
module.exports = {
	preset: 'jest-preset-angular',
	moduleNameMapper: {
		'@core/(.*)': '<rootDir>/src/app/core/$1',
		'date-fns': '<rootDir>/node_modules/date-fns/index.js',
		'ngx-currency': '<rootDir>/node_modules/ngx-currency/esm5/index.js',
		'@ag-grid-community/angular':
			'<rootDir>/node_modules/@ag-grid-community/angular/esm2015/ag-grid-community-angular.js'
	},
	setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
	coverageReporters: ['json', 'lcov', 'text', 'clover'],
	clearMocks: true,
	moduleFileExtensions: ['ts', 'html', 'js', 'json', 'mjs'],
	resolver: '<rootDir>/resolver.js',
	transformIgnorePatterns: [
		'<rootDir>/node_modules/(?!(.*\\.mjs)|@ag-grid-community|@angular/material-date-fns-adapter|date-fns|ngx-currency|@auth0/angular-jwt|@microsoft/signalr)'
	]
};
```

The error
```bash
 FAIL  src/app/ag-grid-table/cell-edit-datepicker/cell-edit-datepicker.component.spec.ts
  ● Test suite failed to run

    Cannot find module './add/index.js' from 'node_modules/date-fns/esm/index.js'

    Require stack:
      node_modules/date-fns/esm/index.js
      node_modules/@angular/material-date-fns-adapter/fesm2020/material-date-fns-adapter.mjs
      src/app/ag-grid-table/cell-edit-datepicker/cell-edit-datepicker.component.spec.ts

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (node_modules/date-fns/esm/index.js:2:1)
```

I don't know what else to try to fix it.

**Comment by vmaksym** [comment]
Same here.

I'm not using NX, I have Angular 16 with AG Grid 30.0.5

The proposed solution does not solve problem for me. I slightly modify resolver.js - removed `pkg.module` from line `main: agDependency ? './dist/cjs/es5/main.js' : pkg.module || pkg.main` , and it is start working 

```
module.exports = (request, options) => {
	return options.defaultResolver(request, {
		...options,
		packageFilter: (pkg) => {
			const packageName = pkg.name;
			if (packageName === '@ag-grid-community/angular' || packageName === 'ag-grid-angular') {
				return {
					...pkg
				};
			}
			const agDependency = packageName.startsWith('@ag-grid') || packageName.startsWith('ag-grid');
			return {
				...pkg,
				// default to use the CommonJS ES5 entry point for Jest testing with AG Grid
				main: agDependency ? './dist/cjs/es5/main.js' : pkg.main
			};
		}
	});
};
```
