### ISSUE TITLE
Best practice for defining `columnDefs`

### ISSUE THREAD

**Issue by IgorTurko** [ag-grid/ag-grid#7266]
In ag-grid documentation, you recommended using `useMemo` together with `columnsDefs` 

```
If you do NOT use useState or useMemo, then the grid will be provided with a new set of Column Definitions every time the parent component is rendered. This will result in unexpected behaviour in the grid, such as the column state (column order, width etc...) getting reset.
```

But what if I am calling `useMemo` with a list of dependencies?
```
const columnDefs = useMemo(
   () => {
   // map columns here
   },
   [gridApi, columnApi, dispatchAdd, dispatchRemove, dispatchUpdate]
)
```
Am I right that dependencies makes useMemo generate `columnDefs` several time?
Is it bad for ag-grid?

For me, there is a problem with this approach, for example in this scenario:
- load grid;
- change the sort order for the column;
- go to the next page;
-  sort order is restored to the default state because useMemo re-create `columnDefs`;

I know that it's not an issue, but where can I raise this question to get an answer on it?

**Comment by AG-Zoheil** [comment]
Hi @IgorTurko,

Thanks for getting in touch with us.

The GitHub forum is for our community users, predominantly for raising bugs, but also for requesting features (which can be accepted or rejected) and for asking the general AG Grid community for support.

Besides our [documentation](https://ag-grid.com/react-data-grid/column-definitions/) on this topic and further material on React best practices that you can find online we will not be able to dedicate the time to answer questions like these in more detail. We do offer more bespoke and customised help for enterprise users. Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

Thank you for understanding.

Kind regards,
Zoheil
