### ISSUE TITLE
Help with module federation, can't load css unless it's in the shell (host)

### ISSUE THREAD

**Issue by ttlage** [ag-grid/ag-grid#7268]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello everyone,

I've been grappling with an issue for the past week in my multi-frontend project that utilizes module federation. In my shell project, I'm importing a module from an Angular project, which incorporates ag-grid for a basic table with three rows and three columns. I've followed all the documentation instructions, including adding imports for styles (ag-grid.css and ag-theme-apline.css) in `src/styles.scss`. However, when I run the project, the table renders without the expected styles:

![image](https://github.com/ag-grid/ag-grid/assets/33501927/6e7f69f5-302e-4c9c-9ba9-958ea404475d)

It's evident that the styles are not applied as intended.

After some experimentation, I discovered that importing the ag-grid styles into the `shell src/styles.scss` resolves the issue:

![image](https://github.com/ag-grid/ag-grid/assets/33501927/aa48fd02-89df-45da-8cf9-78dffb8b6769)

While this would not be a problem if I were using standard ag-grid themes, I need to create a custom theme to incorporate my own styles. The current setup requires me to make changes in the shell project and deploy it every time I want to update the table.

You can find the code [here](https://github.com/ttlage/module-federation-plugin-example), and if you wish, you can clone it to try. To run it, simply execute `npm install` and `npm run start:all`, then click on `Flights` in the shell (http://localhost:5000/flights/flights-search).

Would love some help or advice on this. If you've faced a similar hiccup or have some ideas on making custom styles play nice with ag-grid in a module federation setup, hit me up! Thanks a bunch!

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
