### ISSUE TITLE
[header components] angularCompileHeaders does not work for headerCellTemplates

### ISSUE THREAD

**Issue by jonrimmer** [ag-grid/ag-grid#727]
See this example: https://plnkr.co/edit/PMOGFO6dJBSaea45EVio?p=preview

When angularCompileHeaders = true in gridOptions, Angular directives and expressions within a colDef's headerCellTemplate are not processed.

**Comment by noherczeg** [comment]
I think it is working for me with version 3.3.0. I'm returning a string in the function provided in gridOptions.headerCellRenderer. Said String contains a directive. In that directive I'm calling modals from the global scope, etc, and it works.

**Comment by jonrimmer** [comment]
@noherczeg headerCellTemplates, not headerCellRenderer.

**Comment by noherczeg** [comment]
@jonrimmer Just wanted to help out by noting that the other one works. Maybe it helps the debug process for @ceolter .

**Comment by ceolter** [comment]
correct, it doesn't work. i wasn't part of my plan.

**Comment by jb44** [comment]
Is there a workaround for this issue?  We're looking to include angular directives in the column headers

**Comment by olsn** [comment]
@jb44 you can use a headerCellRenderer as @noherczeg pointed out, this is how we do it: https://plnkr.co/edit/XpZRIo3Ki5Rfq9VITrn7?p=preview

**Comment by jb44** [comment]
@olsn thanks - that's helpful

**Comment by ceolter** [comment]
my plan is to have the headers more like the cellEditors / cellRenderers currently are - i did a lot of work with that design and they behave like components with init() and destroy() methods. you could then have angular compile and angular destroy in this methods. in the future, this pattern will be in all parts of the grid. just need time.....

**Comment by jb44** [comment]
No worries - we can work with what's there for now.  We just made the move from Kendo to ag-grid and we love it.  So much more flexible, and also faster.  Great work!

**Comment by ceolter** [comment]
@jb44  can you give me a quote for our testimonials page along those lines?

https://www.ag-grid.com/testimonials.php

email to accounts@ag-grid.com, thanks :)

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-109

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
