### ISSUE TITLE
Error with ensureNodeVisible when using autoHeight

### ISSUE THREAD

**Issue by pashaMalyshev** [ag-grid/ag-grid#7273]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
In my grid I use the autoHeight property for some columns. When I try to use ensureNodeVisible/ensureIndexVisible my grid does not scroll correctly.

The code I use: gridRef.current?.api.ensureNodeVisible(node, "middle");
I will attach the result in a screenshot:
![Screenshot_1](https://github.com/ag-grid/ag-grid/assets/103384547/8451937b-87cc-4bc7-b61f-2e6525a53a66)

* **AG Grid version:** 30.1.0

* **Browser:**
Chrome

* **Language:** [React | TypeScript 4.9.5 | ES6/7]

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by pashaMalyshev** [comment]
I can't reproduce the error in plunker. My error is related to the non-standard cell height. I use css styles to fit a large amount of text

**Comment by AG-Zoheil** [comment]
Hi @pashaMalyshev,

I'm afraid to be able to effectively help we'd need a reproducible sample. You can see `ensureIndexVisible` working [here](https://plnkr.co/edit/rRFaaREz2H5GNr5g?open=main.js) in our live example - if you are able to adjust this to match your code and reproduce the error we'd be happy to look into this for you.

**Comment by pashaMalyshev** [comment]
The bug appears when I add the white-space: pre-wrap property to a cell

**Comment by surecloud-malokaidi** [comment]
> Hi @pashaMalyshev,
> 
> I'm afraid to be able to effectively help we'd need a reproducible sample. You can see `ensureIndexVisible` working [here](https://plnkr.co/edit/rRFaaREz2H5GNr5g?open=main.js) in our live example - if you are able to adjust this to match your code and reproduce the error we'd be happy to look into this for you.

Hi @AG-Zoheil 
Please find the link reproducing the issue:

https://stackblitz.com/edit/ag-grid-angular-datefilterlocale-qv56xa-ewpr8m?file=src%2Fapp%2Fapp.component.ts

You can see the issue after clicking on `Add Row (Multi Line)` a few times
I even notice after adding a normal height row it bounces off the bottom a little bit after scrolling to the end.

**Comment by surecloud-malokaidi** [comment]
Hi @AG-Zoheil Is this something you can look at?

**Comment by AG-Zoheil** [comment]
Hi @surecloud-malokaidi,

Yes, thank you very much for providing the example.

We do actually already have feature request in our backlog to enhance the implementation of this. We are tracking it with the following reference: **AG-832**

Please view the "More information" section of the item by searching for it in our [pipeline](https://www.ag-grid.com/ag-grid-pipeline/) page for a workaround.

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
