### ISSUE TITLE
AG Grid Vue3: composition API Framework component is missing the method isFilterActive()

### ISSUE THREAD

**Issue by zhuzhuxia5875102** [ag-grid/ag-grid#7274]
I encountered the same problem as the following link. Due to project specifications, I need to use <script setup>. I found that it is normal in ag grid v26.0.0 version, but it cannot be called normally in higher versions, such as v26.2.1 version. Screening API, is there any solution? If necessary, I can provide the minimum implementation code.
https://stackoverflow.com/questions/77347991/ag-grid-framework-component-is-missing-the-method-isfilteractive

**Comment by huajian123** [comment]
I also have the same problem. It seems that ag grid is very unfriendly to vue3's <script setup>

**Comment by joemaylor** [comment]
Hey, this is a known issue (AG-8274) and is in the pipeline for the next major release https://ag-grid.com/pipeline/

So it will be usable from v31.0.0 onwards.

An Ag Grid component is no different from any other Vue component though - in order to access something defined in `<script setup>`, you will need to declare it as accessible via the `defineExpose` compiler macro.

As a stop-gap until this is released, I'm writing custom filter components and cell editors using the `setup()` function instead of `<script setup>`.

**Comment by huajian123** [comment]
@joemaylor Thank you for your answer. I went through the issues and found the solution: I created a patch. The code is as follows. You can refer to it.

diff --git a/lib/VueFrameworkComponentWrapper.js b/lib/VueFrameworkComponentWrapper.js
index 131b21219a610164e3406236384b6083265665c6..316c2c4e235ac1b0e45e95ef828ac5eed48b43e7 100644
--- a/lib/VueFrameworkComponentWrapper.js
+++ b/lib/VueFrameworkComponentWrapper.js
@@ -37,12 +37,24 @@ var VueFrameworkComponentWrapper = /** @class */ (function (_super) {
                 _super.prototype.init.call(this, params);
             };
             DynamicComponent.prototype.hasMethod = function (name) {
-                return wrapper.getFrameworkComponentInstance()[name] != null;
+                // return wrapper.getFrameworkComponentInstance()[name] != null;
+                var componentInstance = wrapper.getFrameworkComponentInstance();
+                if(!componentInstance[name]){
+                    return componentInstance.$.setupState[name] !== null;
+                }else{
+                    return true;
+                }
             };
             DynamicComponent.prototype.callMethod = function (name, args) {
                 var componentInstance = this.getFrameworkComponentInstance();
                 var frameworkComponentInstance = wrapper.getFrameworkComponentInstance();
-                return frameworkComponentInstance[name].apply(componentInstance, args);
+                // return frameworkComponentInstance[name].apply(componentInstance, args);
+                if(frameworkComponentInstance[name]){
+                    return frameworkComponentInstance[name].apply(componentInstance, args);
+                }else{
+                    return componentInstance.$.setupState[name]?.apply(componentInstance, args);
+                }
+
             };
             DynamicComponent.prototype.addMethod = function (name, callback) {
                 wrapper[name] = callback;

**Comment by huajian123** [comment]
@joemaylor  Thank you for your answer. I went through the issues and found the solution: I created a patch. The code is as follows. You can refer to it.
<img width="1307" alt="image" src="https://github.com/ag-grid/ag-grid/assets/31737260/d04f9c10-fffd-4921-956f-7473df5995f4">

**Comment by AG-Zoheil** [comment]
Please note **AG-8274** has now been released as part of V31.

Thank you for your patience.
