### ISSUE TITLE
Icons not being displayed on the grid (Angular)

### ISSUE THREAD

**Issue by jalu14** [ag-grid/ag-grid#7277]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Current behavior**
Any ag-grid icon is being displayed as a **square**, this has been an issue since we updated from 25.3.0 to 30.0.5 to accommodate a newer Angular version.

**Expected behavior**
Correct icons

**Please tell us about your environment:**
Angular: 16.1.5
Ag-grid: 30.0.5
Angular material: 16.1.5

**AG Grid version:**
30.0.5

**Browser:**
Chrome

**Language:**
Typescript

**styles.scss**
Our styles.scss hasn't changed with the update to 30.0.5, it correctly imports ag-grid but no theme.

```
@import 'ag-grid-community/styles/ag-grid.css';
```

May I find a fix or more information I will update this issue, thanks

**Comment by AG-Zoheil** [comment]
Hi @jalu14,

The below should help you with your styling issues when upgrading from versions <28 to versions 28+:

https://ag-grid.com/angular-data-grid/global-style-upgrading-to-v28/

If after following the above you still encounter problems, please do comment and let us know.

Kind regards,
Zoheil
