### ISSUE TITLE
Question about header height span.

### ISSUE THREAD

**Issue by marcoselopez** [ag-grid/ag-grid#7285]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

I have the following structure of headers in an excel file:
![image](https://github.com/ag-grid/ag-grid/assets/83432730/f16be609-fd91-4bbf-8ddd-82344f77e1c2)

But when I translate that into AG grid, I get this:
![image](https://github.com/ag-grid/ag-grid/assets/83432730/3f3dbf3b-266f-4121-8260-30af47a995dd)

As you can see, the header cells are spanning the total height of the "empty" cells they're finding (as expected behavior).
My question is, is there any way to make the header group cells to span the height instead of the header cells to match the structure on the excel file?

**Comment by AG-Zoheil** [comment]
Hi @marcoselopez,

It looks like `suppressSpanHeaderHeight: true` might be a helpful setting for you. You can see it used here: https://plnkr.co/edit/P7cS6wnJh0z5Hm1f?open=main.js

I hope this helps.

Kind regards,
Zoheil
