### ISSUE TITLE
AgGrid triggering Angular's Change Detection on almost every event

### ISSUE THREAD

**Issue by thekip** [ag-grid/ag-grid#7291]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Open an official example by [link](https://www.ag-grid.com/examples/data-update-row-data/simple-immutable-store/packages/angular/index.html ). I assume it uses latest version of AgGrid. 

* Open Chrome DevTools with installed [Angular Dev Tools](https://chromewebstore.google.com/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh). 
* Go to Angular Tab -> Profiler. Hit the record button. 
* Start moving a cursor over a grid or prepend rows and start to scroll. 

See the recording: https://take.ms/DFEhr

**Current behavior**
Angular running change detection on many events produced by Ag-Grid. If you inspect the profile, you will see different "Sources" of CD cycle. Such as `setTimeOut`, `mouseOver`, `mouseOut`, `wheel` etc.   

**Expected behavior**
Ag grid should not trigger Angular's change detection on internal events. That cause serious performance issue in big Angular apps. 

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
Latest

* **Browser:**
Chrome 119

**Comment by thekip** [comment]
I also dug deeper in the root cause, and it seems ngZone is triggered by the "global" events (i don't know what that exactly means in the ag-grid internals) 
<img width="932" alt="image" src="https://github.com/ag-grid/ag-grid/assets/1586852/5e588839-9d24-432a-a3d0-28302435caf8">


All these events bypassing the `this.isEmitterUsed(eventType)` check, because they are `global = true`

**Comment by AG-Zoheil** [comment]
Hello @thekip,

Thank you for the suggestion.

We agree this would be a valuable addition to the product and improve performance.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-10010**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by StephenCooper** [comment]
I have made a number of initial improvements under https://github.com/ag-grid/ag-grid/pull/7350 which removes a lot of the noise and wasted change detection cycles. 

However, as explained in the PR the final amount of cycles will depend on which callbacks are configured on the grid.
