### ISSUE TITLE
Heatmap example is not working

### ISSUE THREAD

**Issue by espenairmine** [ag-grid/ag-grid#7295]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Check out (searched for heatmap on google)
https://www.ag-grid.com/javascript-charts/heatmap-series/

The demo is blank, for all languages.
When searching for *heatmap* on https://www.ag-grid.com, I get not no response, feature no longer supported?
The demo seems to be looking for AG-grid 8.2.1

**Expected behavior**
Heatmaps can be tested in the demo

* **AG Grid version:** 30.2.0
No open issues, but closed issue on heatmap doc.

* **Browser:**
Tested on latest Chrome+Edge

**Comment by AG-DavidG** [comment]
Hi @espenairmine 

That feature was not yet released in version 8.2.1.

However it has now been released as part of AG Enterprise Charts version 9.0.0.
You can read more about it at https://charts.ag-grid.com/javascript/heatmap-series/ 

Thanks

David
