### ISSUE TITLE
Interacting with Number Filter with defined filterParams in ColDef and de-rendering grid will cause crash

### ISSUE THREAD

**Issue by Muhammad-I-Hasan** [ag-grid/ag-grid#7302]
[x] bug report => see 'Providing a Reproducible Scenario'

**Providing a Reproducible Scenario**
https://plnkr.co/edit/eXhHbEL4RQbkUIDc?open=index.tsx&preview
https://codesandbox.io/p/sandbox/ag-grid-modules-forked-lyzzzh?file=%2Fsrc%2Findex.tsx%3A55%2C21

To reproduce the bug, interact with the filter in the second column titled "broken filter", an interaction could be anything from typing in the filter box, opening the modal to see filter options, or clicking the hamburger icon for that column. The filter will function normally as it will for the other two columns. Now hide the grid by clicking the button 'click me'.

**Current behavior**
When you have defined a column with a number floating filter that contain filterParams in its definition, and you interact with said filter before unmounting the grid, the app will crash with a type error: "Uncaught TypeError: Cannot read properties of null (reading 'is')". The filters work while the grid is rendered but when the grid is no longer rendered, the application will crash.

**Expected behavior**
The grid should unmount and disappear without causing the application to crash.

**Please tell us about your environment:**
OS: Windows 11, IDE: VSCode, package manager: npm

* **AG Grid version:** X.X.X
versions: 
 - ag-grid-community: 30.2.1 - latest
 - ag-grid-react: 30.2.1 - latest

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0'
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'

* **Language:** [TypeScript 4.9.5]

**Comment by StephenCooper** [comment]
This has been fixed in our latest release v31.

See updated plunker. https://plnkr.co/edit/Oonte5rqpZYyvTzv?open=index.tsx
