### ISSUE TITLE
AgChartsReact histogram does not clear previous rendered data

### ISSUE THREAD

**Issue by leikerjp** [ag-grid/ag-grid#7303]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Plunker: https://plnkr.co/edit/cS6xeToMNciokscl?open=index.tsx

**Current behavior**
When using the histogram type of AGChartsReact, previous data rendered in the chart is not cleared and all future updates to the data overlap the existing data which remains stuck on the plot. The axis does change as expected. A Plunker reproducing the issue is: https://plnkr.co/edit/cS6xeToMNciokscl?open=index.tsx  To trigger the problem, click the 'toggle' button which switches between two sets of data. Notice that the second set gets added on top of the first, and neither ever go away.

**Expected behavior**
When using a histogram type chart and updating the data in the AgChartOptions, the new data should be rendered in the chart and old data removed. When using line/scatter types this issue was not present - only histogram.

**Please tell us about your environment:**
Plunker

**AG Grid version:**
ag-grid-community: 30.2.1 - latest
ag-grid-react: 30.2.1 - latest

**Browser:**
Chrome, Firefox

**Language:** TypeScript

**Comment by AG-DavidG** [comment]
Hi 

This has been fixed in AG Grid 31 / AG Charts 9.

I have updated your plunker to use the new version and it is working as expected.
https://plnkr.co/edit/cgwq12HloPQ7qvLO?open=index.tsx

This version has just been released today and is now available.

Thanks
