### ISSUE TITLE
No apply set value in cell on pivod mode

### ISSUE THREAD

**Issue by SenyaMur** [ag-grid/ag-grid#7309]
I try set new value in cell on pivot mode. After enter new value, it return old value.

See reproduced [example](https://codesandbox.io/p/sandbox/ag-grid-packages-forked-z8fjlw?file=%2Fnode_modules%2F.store%2Fag-grid-react%4031.0.0%2Fnode_modules%2Fag-grid-react%2Flib%2Fshared%2Finterfaces.d.ts&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpk6xlbn0006356kdi3s5muq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpk6xlbn0002356kadluuo6s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpk6xlbn0003356kxi37wecc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpk6xldt000i356k250zhsgd%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpk6xlbn0005356kik760a73%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpk6xldt000i356k250zhsgd%2522%253A%257B%2522id%2522%253A%2522clpk6xldt000i356k250zhsgd%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%252C%2522clpk6xlbn0002356kadluuo6s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpk6xlbm0001356k5itky3gd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpk6xlbn0002356kadluuo6s%2522%252C%2522activeTabId%2522%253A%2522clpk6xlbm0001356k5itky3gd%2522%257D%252C%2522clpk6xlbn0005356kik760a73%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpk6xlbn0004356kkhh1jefu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpk6xlbn0005356kik760a73%2522%252C%2522activeTabId%2522%253A%2522clpk6xlbn0004356kkhh1jefu%2522%257D%252C%2522clpk6xlbn0003356kxi37wecc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpk6xlbn0003356kxi37wecc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) on latest version ag-grid. 
Unfotenty this behaivour the same on: 29.3.5, 31.0 versions
In 27.1 version this case crash on stopEdit.

**Comment by AG-Zoheil** [comment]
Hi @SenyaMur,

Pivoted data is not editable at the moment. Note that a pivot table is just derived data, so if we were to let users edit, ultimately this would somehow need to update the underlying data. We do have a feature request in our backlog, you can track it with the following reference: **AG-3373**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
