### ISSUE TITLE
Row group column header name update issue

### ISSUE THREAD

**Issue by ppatliak** [ag-grid/ag-grid#7313]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hello everyone,

I`m facing an issue with updating row group column header name. After I call api.setColumnDefs([]), my flat columns are updated and row grouping one does not. Here is a plunker - https://plnkr.co/edit/1v66eFRu7IoTD9kX?open=index.jsx
Try to click buttons and check row group column header name. Could you please advice, how to update row group column header? Thanks a lot!

Scenario:
- prepare a coldefs where one column is rowGroup=true;
- try to update with button rowGroup column name

**Expected behavior**
Row group header name is updated

**Please tell us about your environment:**
Windows 10, VS Code

* **AG Grid version:** 30.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'

* **Language:** "typescript": "5.1.6"

**Comment by AG-Zoheil** [comment]
Hi @ppatliak,

Thank you for raising this. This is not a bug but expected behaviour. `gridApi.setColumnDefs` would not be expected to update the group column. You would need to make a separate call using `setAutoGroupColumnDef` for that.

Kind regards,
Zoheil

**Comment by ppatliak** [comment]
Hello @AG-Zoheil ,

Thanks for the answer! The issue is that I have multiple grouping columns (lets say 6). Each column should have header name updated. As far as I understood, setAutoGroupColumnDef will affect all grouping columns with one header name. Am I missing something?
Thanks in advance!

**Comment by AG-Zoheil** [comment]
No problem!

Row grouping is an enterprise feature. I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/) for issues or suggestions if you are an enterprise client as this would need further investigation for customisation. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil
