### ISSUE TITLE
gridApi.hidePopupMenu is doesn't work

### ISSUE THREAD

**Issue by marlai-hz** [ag-grid/ag-grid#7315]
`
onGridReady(params) {
      this.gridApi = params.api;
      //
      this.gridApi.hidePopupMenu();
      //
    },
`

click the right mouse button,  it still show the context menu. why?

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
