### ISSUE TITLE
how to hide console.logs of aggrid?

### ISSUE THREAD

**Issue by terlan4** [ag-grid/ag-grid#7323]
I haven't passed {debug: true} or anything to gridOptions, yet I am getting tons of logs in console. How can I hide them? Thanks
![image](https://github.com/ag-grid/ag-grid/assets/138553763/47cf9bde-a9b2-4ee9-afed-006761d62f4a)

**Comment by StephenCooper** [comment]
This logging is only triggered by the `debug` flag. I am going to close as without a repo showing how this logs without that flag being set there is nothing for us to go on.
