### ISSUE TITLE
After upgrading to 30.1.0 horizontal scroll scrolls too much to the right if vertical scroll is visible

### ISSUE THREAD

**Issue by mgmoonlight** [ag-grid/ag-grid#7330]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

If reporting a bug make sure to state.

Current behaviour.
When there's a *visible* vertical scroll bar in the grid, the horizontal one scrolls too much to the right.
I see that in your examples you have in addition to "ag-body-vertical-scroll" class also "ag-scrollbar-invisible" class, but we do not use this class, our scroll bars are visible (which is the desired behavior).
If you remove "ag-scrollbar-invisible" you can easily reproduce it.

**Current behavior**

![Uploading Screenshot 2023-12-08 at 7.22.57.png…]()

**Expected behavior**

![Uploading Screenshot 2023-12-08 at 7.21.28.png…]()

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
30.1.0 (not willing to upgrade to the latest version)

* **Browser:**
Chrome

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by mgmoonlight** [comment]
Attaching a screenshot. The left side is current behavior and the right side is expected behavior.

![Uploading Screenshot 2023-12-12 at 10.01.52.png…]()

**Comment by AG-Zoheil** [comment]
Hi @mgmoonlight,

Thank you for getting back.

For us to be able to best support we would need a reproducible scenario that shows the issue. A screenshot will help us see it visually, but we will need to be able to replicate your exact setting of the grid to be able to investigate and provide a solution.

Therefore we usually don't ask for screenshots but for you to send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point.

Kind regards,

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
