### ISSUE TITLE
AG Grid Modules - Cannot import properly TextMatcherParams interface

### ISSUE THREAD

**Issue by robby34** [ag-grid/ag-grid#7332]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hi,

I use to import Ag Grid via AG Grid Modules (and not AG Grid Packages).
Then when I have to import the interface `ITextFilterParams` for example, I do it via:
```typescript
import { ITextFilterParams } from '@ag-grid-community/core';
```
This interface is available from '@ag-grid-community/core' because it is exported in the main.ts file `https://github.com/ag-grid/ag-grid/blob/latest/grid-community-modules/core/src/ts/main.ts`:
```typescript
export { TextFilter, ITextFilterParams, TextFilterParams, TextFilterModel, TextFormatter } from "./filter/provided/text/textFilter";
```

On other place, I want to import the `TextMatcherParams` interface (which is defined in the same file as `ITextFilterParams`).
But, as we can see above, `TextMatcherParams` is not exported in the `main.ts` file, so I cannot import it from '@ag-grid-community/core'.

My question is: Why the `TextMatcherParams` interface is not exported from main.ts ?

Note: as it is not exported from main.ts, I have to import it directly from the nested dist path, that is not nice...:
```typescript
import { TextMatcherParams } from '@ag-grid-community/core/dist/esm/es6/filter/provided/text/textFilter';
```

**Comment by StephenCooper** [comment]
Hi @robby34,

Thanks for raising this omission. I will get this corrected so that in our next release `TextFilterParams` will be exported correctly.

**Comment by StephenCooper** [comment]
Yes, wrong comment but right in the commit at least :)

https://github.com/ag-grid/ag-grid/commit/aa2b1f872c0aaed4fd4a99921583ded0ba86bd19
