### ISSUE TITLE
How can I implement select all rows with checkbox in the grid header?

### ISSUE THREAD

**Issue by BHJerryChen** [ag-grid/ag-grid#7340]
Hi Team,

In Ag-Grid, I displayed a checkbox in each row to let customer to select the data. And I also have a checkbox the top-left corner of the grid. Customer can select that checkbox, then all the rows in current page will be selected. This will be easier for customers selecting all the rows. But my question is: I am using server-side mode, how can I implement this feature? do we have function for this in current Ag-Grid version?

Thanks.

Regards,
Jerry

**Comment by AG-Zoheil** [comment]
Hi @BHJerryChen,

Please view the following documentation: https://ag-grid.com/javascript-data-grid/server-side-model-selection/#header-checkbox-selection.

If this does not meet your requirement, please be sure to include a reproducible scenario (you can fork one of the plunkers from the examples in our documentation) to describe what you are after.

Many thanks!
