### ISSUE TITLE
ag-grid-vue3 30.2.1 - Excel export with Master Details

### ISSUE THREAD

**Issue by liranhr** [ag-grid/ag-grid#7345]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

I did a migrate from Vue2 to Vue3 and everything working well less than this issue.
When I'm trying to download a regular excel its download fine but after make a Master Detail it download the excel file with blank cells after the opening row.

*When I used Vue2 it was worked fine.

Maybe its bug that append because of the ag-grid upgrade?

**Providing a Reproducible Scenario**
I have insert to ag-grid-vue this row:
:defaultExcelExportParams="defaultExcelExportParams"

and define it in data inside the script:
defaultExcelExportParams: null

inside beforeMount writing this:
this.defaultExcelExportParams = {
      getCustomContentBelowRow: (params) => getCells(params),
      columnWidth: 120,
    };

the getCells function look like this:
var getCells = (params) => {
  var detailGrid = params.api.getDetailGridInfo("detail_" + params.node.id);
  if (typeof detailGrid != "undefined") {
    var detailRowNode = detailGrid.api.getRenderedNodes();
    if (detailRowNode.length) {
      const cells = [
        [
          cell(""),
          cell("Date", "header"),
          cell("Warehouse", "header"),
          cell("Location", "header"),
          cell("Lot", "header"),
          cell("Quantity", "header"),
          cell("Manufacturer Name", "header"),
        ],
      ].concat(
        detailRowNode.map(function (stock) {
          return [
            cell(""),
            cell(stock.data.date, "body"),
            cell(stock.data.warehouse, "body"),
            cell(stock.data.location, "body"),
            cell(stock.data.lot, "body"),
            cell(stock.data.quantity, "body"),
            cell(stock.data.manufacturer_name, "body"),
          ];
        }),
        [[]]
      );
      return cells;
    }
  }
};

I have added an excel file that example how its look like in vue2 and the problem in vue3
[Excel File Exemple.xlsx](https://github.com/ag-grid/ag-grid/files/13659890/Excel.File.Exemple.xlsx)

**Please tell us about your environment:**

* **AG Grid version:** 30.2.1

* **Browser:**
Chrome

* **Language:** Vue 3

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by liranhr** [comment]
The issue fixed... I did a mistake, there was changes between version 27 that worked with Vue2 and I'm using version 30 that worked with Vue3.

Sorry for that confusing :)
