### ISSUE TITLE
Prevent row selection in cell clicked handler

### ISSUE THREAD

**Issue by Tsyklop** [ag-grid/ag-grid#7348]
**I'm submitting a
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

How I can prevent row selection in cell clicked handler? 

Not working:
```
onCellClicked={event => {
          if ((event.event?.target as HTMLInputElement).type === 'checkbox') {
            event.event?.stopPropagation();
            event.event?.preventDefault();
            return;
          }
}}
 ```

I have checkbox in each row (default behavior select checkbox when row selected. I dont need this). And when I click on my own checkbox row also selected. How to prevent this?

**Please tell us about your environment:**
Windows 10, WebStorm, pnpm

* **AG Grid version:** 31.0.1

* **Browser:**
'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36'

* **Language:** TypeScript

**Comment by AG-Zoheil** [comment]
Hi @Tsyklop, if you could provide a reproducible scenario (like a plunker from our website) it would be easier to advise but it sounds like you are looking for something like [**this**](https://plnkr.co/edit/l9IM4mzgpc0d8xrt?open=main.js) using `suppressRowClickSelection`?

**Comment by AG-Zoheil** [comment]
Hi @Tsyklop,

For this requirement you can use our [checkbox cell renderer](https://ag-grid.com/javascript-data-grid/cell-rendering/#checkbox-cell-renderer).

See this implemented here: https://plnkr.co/edit/rFpLcdWunRvtHmjh?open=main.js

I hope this helps.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Sorry I didn't get the question - what's Mantine?

**Comment by AG-Zoheil** [comment]
Right!

You would need to use your own custom cell renderer instead of the provided one - see [here](https://ag-grid.com/javascript-data-grid/component-cell-renderer/). I'm afraid this is not something for which community support is provided.

**Comment by AG-Zoheil** [comment]
The plunker you've linked in the comment above works as per original requirement - "to be able to select the checkbox without selecting the row".
Which problem do you still see?

**Comment by AG-Zoheil** [comment]
Hey @Tsyklop,

Okay - the only other thing I can advise is to follow this approach: https://blog.ag-grid.com/binding-boolean-values-to-checkboxes-in-ag-grid/.

Hope this helps!
