### ISSUE TITLE
How to hide row id's in the tree data structure?

### ISSUE THREAD

**Issue by yashwanth2714** [ag-grid/ag-grid#7349]
Hello Team,

Can you please assist me in hiding these row IDs?

![image](https://github.com/ag-grid/ag-grid/assets/36370530/e281f14f-c000-4d56-a199-5dac265a9954)

The suppressCount property hides the child count, which is fine, but is there another property to hide the row id?

![image](https://github.com/ag-grid/ag-grid/assets/36370530/0b1cd654-c16f-4a31-8031-0af2f2e516de)

AG GRID version : 31.0.0
Vue version : 3
Browser : Chrome
Language : Javascript

**Comment by kayesn786** [comment]
@yashwanth2714 did you get any solution? I also have a similar use case where i need to toggle between tree view and normal view.

**Comment by yashwanth2714** [comment]
@kayesn786 The workaround for now is to use CSS.

.ag-group-value {
    display: none;
}
