### ISSUE TITLE
AG Grid Community - Isolated React Grid Component

### ISSUE THREAD

**Issue by mikevarela** [ag-grid/ag-grid#7351]
**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Hi, loving the grid. Have a slightly noob question. I’m in NextJS. Wanting to create a grid component and pass it columns and row data. All good there. Struggling a bit on how to pass a valueFormatter though. Currently I’m loading all my formatters in the grid component and I’m passing in a string with the name of my chosen formatted, running a switch statement and applying the correct formatter in the grid component. It’s working but I’m having typescript types issues all over, mostly around ColumnDef type. Is there a good way to do this without having to apply this in the parent component?

Thanks.

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
