### ISSUE TITLE
AG Grid Angular -  stateUpdated event not fired when empty data

### ISSUE THREAD

**Issue by CharlieZel** [ag-grid/ag-grid#7352]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hi,

I am currently using AG Grid 31.0.0

I fetch my rowData asynchronously, and when my grid is initialized, I have no data yet.
I use the `stateUpdated` event to save my state (eg. columnOrder and visibility). But when I try to trigger this event by moving a column for example while I don't have data yet, the event is not fired. As soon as some data are provided, when I try to move a column again, the event is fired.

My question is : Is it an expected behavior ?

**Comment by AG-Zoheil** [comment]
Hi @CharlieZel,

Thanks for getting in touch.

This is expected behaviour. We don’t emit any events until both columns and rows are loaded.
This is to prevent a large number of state updated events as the grid is initialising. However, we agree having this clearly stated in our documentation would be helpful and we will therefore make the necessary additions to it. I have raised a task in our backlog for this which can be tracked via reference **AG-10142**.

Kind regards,

**Comment by AG-Zoheil** [comment]
Hi @JeromeSivadier,

Thank you for your comment. We have reviewed this internally and agree that making an enhancement to the functionality is the right approach. Hence, we have adjusted the FR **AG-10142** from being a mere documentation change to instead address the actual issue.

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.
See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us!
