### ISSUE TITLE
ag-grid angular

### ISSUE THREAD

**Issue by Jaroslove** [ag-grid/ag-grid#7354]
Hi Team,

I've started to using ag-grid with angular.
I need a grid with pagination.

I installed (via npm) ag-grid-angular & ag-grid-community (both 31.0.1)

Next wrote a component like in an example from https://www.ag-grid.com/angular-data-grid/row-pagination/#mode-1-paginate-only-top-level-rows

In my scss:

@import '../../../node_modules/ag-grid-community/styles/ag-grid.css';
@import '../../../node_modules/ag-grid-community/styles/ag-theme-quartz.css';

.example-wrapper {
  display: flex;
  flex-direction: column;
  height: 750px;
}

My html is:

```
 <div class="example-wrapper">
   <ag-grid-angular
     style="width: 100%; height: 100%;"
     [columnDefs]="columnDefs"
     [defaultColDef]="defaultColDef"
     [rowSelection]="rowSelection"
     [paginationPageSize]="paginationPageSize"
     [pagination]="true"
     [paginationPageSizeSelector]="paginationPageSizeSelector"
     [suppressPaginationPanel]="true"
     [suppressScrollOnNewData]="true"
     [rowData]="rowData"
     [class]="themeClass"
     (paginationChanged)="onPaginationChanged($event)"
     (gridReady)="onGridReady($event)"
   ></ag-grid-angular>
 </div>
```

When I load my page I can see the grid with styles, but I cannot see a pagination panel at all, in html DOM it's presented.

Could you help me, please?

**Comment by StephenCooper** [comment]
I think you want to remove this line
```
[suppressPaginationPanel]="true"
```
This hides the grids controls if you wanted to provide your own.

https://ag-grid.com/angular-data-grid/row-pagination/#example-custom-pagination-controls
