### ISSUE TITLE
Multi-select issue

### ISSUE THREAD

**Issue by kopach** [ag-grid/ag-grid#7355]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

Multi-select (with shift hold) misbehaves (see demo below)

![2023-12-15 23 31 13](https://github.com/ag-grid/ag-grid/assets/8749624/266c955f-2001-4487-8fa0-3db65bdc1455)

Expected result - rows **between** current & last click are selected/deselected

Here is example of how it should work (note it's possible to de-select in between of selected items)

![2023-12-15 23 24 13](https://github.com/ag-grid/ag-grid/assets/8749624/57b57f0b-03c8-4d79-87d1-8da8dcf76e1f)

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for raising this on GitHub.

We are currently in the process of reviewing and revising our mechanism for de/selection (including bulk).

We have this requirement in our backlog and we are tracking it with the following reference: **AG-8599**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
