### ISSUE TITLE
Adding nulls last/nulls first specifier to sorting options

### ISSUE THREAD

**Issue by fingoldo** [ag-grid/ag-grid#7356]
I am not a paid customer, but I'll try posting a feature request here 'cause your paid customers will for sure also benefit from implementing it.

**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
Currently, a column can be defined in columnDefs with a keyword sort='desc' or sort='asc'. However, as widely known from working with SQL databases, rows with null (empty) values can occupy top places which can be far from expected behavior. It's possible to achieve desired output with a custom [comparator](https://github.com/ag-grid/ag-grid/issues/4878), however, it's cumbersome, errors-prone, requires additional time.
Why not adopt SQL standard sorting specifier **nulls last/nulls first**? Would be great to be able to set it on entire grid or column level.

**Expected behavior**
sort='desc nulls last' etc

Thanks!

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid besides using your own custom comparator. However, we do already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-4861**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
