### ISSUE TITLE
Show per-column aggregations in Ag-Grid Angular with 'groupRows' grouping

### ISSUE THREAD

**Issue by Pikkurthi** [ag-grid/ag-grid#7357]
I'm currently using Ag-Grid in my Angular project to group rows based on a specific column value. I've set the groupDisplayType to 'groupRows' for this purpose.

However, I'm facing an issue where I need to display aggregation values for each group per column in my Ag-Grid configuration. Essentially, I want to show the aggregation results in the group headers, as shown in the red numbers in the attached image.

Here's the code I'm working with: Plunker link
[https://plnkr.co/edit/XXr5Ys85QRGcRWBk?open=app%2Fapp.component.ts][1]

I would greatly appreciate any assistance in achieving this functionality. Thank you in advance!

[![enter image description here][2]][2]

Thank you.

  [1]: https://Code%20Link
  [2]: https://i.stack.imgur.com/0EIwr.png

**Comment by AG-Zoheil** [comment]
Hi @Pikkurthi,

Thank you for raising this on GitHub.

When you use "groupRows" as the `groupDisplayType`, you are basically taking over the rendering of the entire row, this means that no aggregations are going to be shown.
If you need to have aggregations, you will have to use a different type of grouping. If you are unable to switch to a different type and need to continue using "groupRows" you can add aggregations to your custom group rows, but will have to calculate them yourself.

Find out more information via this link: https://ag-grid.com/angular-data-grid/grouping-group-rows/#configuring-group-cell-renderer.

I hope this helps.

Kind regards,
Zoheil
