### ISSUE TITLE
sticky horizontal scroll bar at the bottom of the table (React)

### ISSUE THREAD

**Issue by delihiros** [ag-grid/ag-grid#7361]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

I want to know how I can/should control a scroll bar directly in AG Grid (React/Next.js).

Currently AG Grid table can have horizontal scroll bar at the bottom of the table by setting `alwaysShowVerticalScroll={true}`.
But in some cases table can be vertically long, making it impossible to see the scroll bar at the bottom.
This is a problem when someone wants to scroll horizontally but to do that with a mouse you first need to scroll to the bottom of the table to drag the scroll bar.

In some libraries, for example Ant Design, its Table component provides `scroll` property, and by setting this property a scroll bar will be shown at the bottom of the screen while the bottom of the table is not in the screen.

example of how Ant Design Table works
https://ant.design/components/table#components-table-demo-sticky
https://codesandbox.io/p/sandbox/fixed-header-and-scroll-bar-with-the-page-antd-5-12-3-fw6wfm?file=%2Fdemo.tsx

As far as I know, AG Grid does not provide a way to enable this kind of feature; the closest feature I find is probably aligned grids, but this does not provide a way to control a scroll bar.

aligned grids
https://www.ag-grid.com/javascript-data-grid/aligned-grids/

So my question is, does AG Grid provide any way achieving this? And if so, how can I achieve this?
If there are any workarounds I would love to know.

**Expected behavior**
https://codesandbox.io/p/sandbox/fixed-header-and-scroll-bar-with-the-page-antd-5-12-3-fw6wfm?file=%2Fdemo.tsx

The code will probably look like this if there are ways to access scroll bar ref directly.
https://codesandbox.io/p/sandbox/biao-xia-bu-gahua-mian-wai-demohua-mian-xia-bu-nibiao-nosukuroruba-njtzv?file=%2Fsrc%2FApp.tsx

* **AG Grid version:** v31.0.1

* **Browser:**

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by delihiros** [comment]
Can not see the detail but could this be the below which is rejected?

`AG-3875 - [Scrolling] Add support for sticky scroll bars`

**Comment by AG-Zoheil** [comment]
Hi @delihiros,

This is already possible. See this example here: https://plnkr.co/edit/3vj29O4V22nfKlqM?open=index.jsx.

If you are unable to see any of the scrollbars in the example above may I please direct you to the blue information box in this section of our documentation: https://ag-grid.com/react-data-grid/scrolling-scenarios/#make-scrollbars-always-visible.
Scrollbars also have operating system controls which may be overriding the AG Grid settings. Please make sure your OS is set at your preferred settings for scrollbars.

I hope this helps.

Kind regards.
Zoheil

**Comment by delihiros** [comment]
@AG-Zoheil 

thank you for the reply.
It seems like I have mistook what `alwaysShowVerticalScroll={true}` does, so thank you.
It looks fine in your example, but when I try to put the table into some `div` with size, scroll bar will appear at the bottom of that `div`.

example:
https://plnkr.co/edit/jNTVRJJCGB0gnZRf?open=index.jsx

how should I avoid this?

**Comment by AG-Zoheil** [comment]
Thanks for providing the example.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-5045**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by marsaldaffa** [comment]
Hi @AG-Zoheil are the feature now available? it's been a year. the issue what we having are we need the ag-grid table horizontal or vertical to be controlled by the browser scrollbar, because right now when user want to scroll the horizontal when lot of table are open, the user need to scroll down first then scroll the horizontal, it's there any way to put the horizontal bar sticky at the bottom of screen, detached from the table?
