### ISSUE TITLE
AgGrid v31 is not allowing to update alignedGrids option after initialization

### ISSUE THREAD

**Issue by thekip** [ag-grid/ag-grid#7369]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
We use `alignedGrid` feature for MasterDetails grids. So when master details row opened we need to set child grid to the `alignedGrid` property of a main one. 

Since v31 we should use `api.setGridOption();` to change GridOptions after initialization, and it shows a warning when I attempt to set `alignedGrids`:

`AG Grid: alignedGrids is an initial property and cannot be updated.`

However, all grids are bound together and aligning works, despite of the warning. 

**Expected behavior**
Consider `alignedGrids` option non-initial and allow changing it after initialization. 

* **AG Grid version:** 31.0.1

**Comment by AG-Zoheil** [comment]
Hi @thekip,

Thank you for reporting this on GitHub.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by thekip** [comment]
Well, don't know what exactly you want to see there, everethying is already written in the description and there nothing could be added. 

https://plnkr.co/edit/F5waWiBjXBetLbmx?open=main.ts

Open console, see the warning `AG Grid: alignedGrids is an initial property and cannot be updated.`
Scroll the grid's, it works despite of the warning

**Comment by AG-Zoheil** [comment]
Thanks @thekip,

as you know our grid can be defined and customised in countless ways. For us to be able to most efficiently investigate an issue and not waste time (ours and yours), it's easiest when a reproducible scenario is provided by the reporter. 

Thank you for providing this - we will investigate and get back to you.

Kind regards,
Zoheil

**Comment by StephenCooper** [comment]
Hi @thekip,

Thanks for the repoduction. I have updated it to use the callback configuration of the aligngGrids property so that you do not need to use the api. This avoids the warning and is the recommended approach.

https://plnkr.co/edit/4xh4hFFdQC5hs2vA?open=main.ts

```ts
const gridOptionsTop: GridOptions = {
  ...
  alignedGrids: () => [bottomApi]
};
```

**Comment by StephenCooper** [comment]
Thank you for the added context. I have raised a ticket for us to evaluate the status of this property. It does look like it can be updated so if I can validate that is the case then I will have the initial flag removed which will remove the warning.

We have added this requirement to our backlog and we are tracking it with the following reference:
AG-10229

You can get an update on the status of this item on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.
