### ISSUE TITLE
Incorrect Code Snippet in Official Documentation

### ISSUE THREAD

**Issue by Cooky1102** [ag-grid/ag-grid#7370]
### Describe the Issue:
There is a problem with the provided code snippet in one of the tutorial sections.

[custom-cell-components](https://www.ag-grid.com/react-data-grid/deep-dive/#custom-cell-components)

`
const CompanyLogoRenderer = ({ value }) => (
  <span style={...}>
    ...
    <p style={...}>{value}<p>
  </span>
);
`

the last `<p>` miss the corresponding closing tag.

**Comment by AG-Zoheil** [comment]
Hi @Cooky1102,

Thank you for making us aware of this typo. We will rectify this.

Kind regards,
Zoheil
