### ISSUE TITLE
'autosizeThiscolumn' Typo in Example Locale file

### ISSUE THREAD

**Issue by copiiinux** [ag-grid/ag-grid#7371]
**I'm submitting a ...**
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
On https://www.ag-grid.com/examples/localisation/localisation/locale.en.js, the example Locale file have an `autosizeThiscolumn` attribute.

**Expected behavior**
Following camelCase semantics, the `autosizeThiscolumn` attribute should have an uppercase `c` and become `autosizeThisColumn`.

**AG Grid version**
Current Example Locale file available at the URL posted above.

**Comment by AG-Zoheil** [comment]
Hi @copiiinux,

Thank you for making us aware of this typo. We will rectify this.

Kind regards,
Zoheil
