### ISSUE TITLE
tooltipValueGetter - to issue a tooltip only the value of the field does not fit in the column

### ISSUE THREAD

**Issue by GABuryan** [ag-grid/ag-grid#7372]
Tell me if it is possible to determine in the tooltipValueGetter whether the value of the field is placed in a column of the table or it is cropped to the width of the column. (All cells have standart class .ag-cell-value { overflow: hidden; text-overflow: ellipsis; } )

In one case - text truncated by css (text-overflow: ellipsis), I want to return the tooltip text

If the value is not truncated, then I want to return null.

**Comment by GABuryan** [comment]
Example field of model :
{
      field: 'Name',
      headerName: 'Full name',
      width: 100,
      
      tooltipValueGetter: (params) =>{ 
        if (....) return 'My Text'
        else return null 
      },
    }

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
