### ISSUE TITLE
Is there a right way to apply `columnState` without flickering

### ISSUE THREAD

**Issue by adguernier** [ag-grid/ag-grid#7373]
**I'm submitting a** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

Hello, I'm using `<AgGridReact>` and I would like to display the columns as the user left them previously.

My first attempt was to persist the `api.getColumnState()` result in `localStorage` to apply it with `api.applyColumnState(params)` by subscribing on `onGridReady` event. 

```tsx
const updateColumnState = useCallback(() => {
    if (!storeDisabled && gridRef.current.api) {
        gridRef.current.api.applyColumnState({
            state: storedColumns,
            applyOrder: true,
        });
    }
}, [gridRef, storeDisabled, storedColumns]);
```

It works well, but the grid renders first with the default column state, then updates a second later with the stored state and I would like to avoid this flickering.

So my second attempt was to persist the whole `gridState` in `localStorage` to apply it in the `initialState` prop of `<AgGridReact>`: 

```tsx
const onStateUpdated = useCallback(
    (params: StateUpdatedEvent) => {
        setStoredGridState(params.state);
    },
    [setStoredGridState]
);

<AgGridReact
    onStateUpdated={onStateUpdated}
    initialState={storedGridState}
/>
```

It works well too! But now I can't update the `gridState` programmatically as before because `initialState` is only read once when the grid is created.

Is there a right way to achieve this. I read the documentation extensively without finding anything but I may have missed it.

Any help will be appreciated :) Thanks

* **AG Grid version:** 31.0.0

* **Language:** [TypeScript 5.1]

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by jaaywags** [comment]
Well, I figured out a pretty good solution actually. I posted it [here on Medium](https://medium.com/@jwag/persisting-state-for-ag-grid-saving-column-order-filters-and-sort-options-e62f18332ebd) and made a [stack blitz demo here](https://stackblitz.com/edit/ag-grid-persist?file=README.md).
