### ISSUE TITLE
Custom date filter for advancedFilter

### ISSUE THREAD

**Issue by uni-vinay-p** [ag-grid/ag-grid#7375]
I am in v31.0.1, and I tried adding a custom date filter in vuejs with the following format.
`:components="{ agDateInput: CustomDateFilter }"`

It works when `enableAdvancedFilter: false` (i.e., in column filter) but it doesn't work when `enableAdvancedFilter: true` (i.e., in advanced filter) on checking the codebase I found out that advanced filter uses `AgInputDateField`. How to make this work?

**Comment by AG-Zoheil** [comment]
Hi @uni-vinay-p,

I'm afraid the advanced filter does not support custom date components.

Kind regards,
Zoheil
