### ISSUE TITLE
refreshHeader resets the header moving animation

### ISSUE THREAD

**Issue by Kreash** [ag-grid/ag-grid#7376]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I have a custom headerComponent and other columns with default header cells
I need to update the headerComponent  and move other  columns, but if I use refreshHeader() and moveColumns() together, the column moving animation doesn't work.

**Current behavior**
if use refreshHeader() and moveColumns() together, the column moving animation doesn't work.

**Expected behavior**
if use refreshHeader() and moveColumns() together, the column moving animation should work.

* **AG Grid version:** 29.3.3 (ag-grid-angular)

* **Browser:** Chrome 120.0.6099.129

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
