### ISSUE TITLE
When some not memoized props re-render in React, `Column Moving` is reset.

### ISSUE THREAD

**Issue by woochanleee** [ag-grid/ag-grid#7381]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Question**

As you can see below video, re-render after Column Moving, Column Moving status is reset. 

You can play demo in [CSB](https://codesandbox.io/p/sandbox/column-moving-is-reset-when-re-render-ag-grid-react-69hfm5) , of course.

https://github.com/ag-grid/ag-grid/assets/48552260/e837d17d-d5b0-452d-826f-158615c26c5c

After digging, i found that the following three props if not memoized, Column Moving is reset.

- `columnTypes`
- `columnDefs`
- `defaultColDef`

I'm not sure which props I should memoize more. Where can I find out about this?

**Please tell us about your environment:**

* **AG Grid version:** 31.0.1

* **Browser:**

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
* **Language:** all | TypeScript X.X | ES6/7 | ES5

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
