### ISSUE TITLE
children does not exist in type ColDef

### ISSUE THREAD

**Issue by smohadjer** [ag-grid/ag-grid#7390]
When I define column definition in my Angular component like this:
````
  colDefs: ColDef[] = [
    { field: "_id", filter: false  },
    {
      headerName: 'customer',
      children: [
          { field: 'gender' },
          { field: 'age' },
          { field: 'email' },
      ]
    }
]
````
I get this typescript error:

Object literal may only specify known properties, and 'children' does not exist in type 'ColDef<any, any>'.

**Comment by StephenCooper** [comment]
You need to use the combined type of `(ColDef | ColGroupDef)[]`.

Children is only supported on ColGroupDef.

**Comment by smohadjer** [comment]
Thanks, that worked. I wonder why children is not added as optional property to column type to avoid running into this error.

**Comment by StephenCooper** [comment]
It is good to have separate types and correct that ColDef doesn't have an optional children property.

However I have reopened as we maybe should consider providing the union type ourselves to avoid users like yourself having to write it.

**Comment by StephenCooper** [comment]
We have added this requirement to our backlog and we are tracking it with the following reference: AG-8054

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can get an update on the status of this item on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

**Comment by smohadjer** [comment]
Thanks @StephenCooper. I also think it would be helpful if your team uses TypeScript instead of JavaScript in your documentation for Angular. Not only TypeScript is default language of Angular, but then you had to specify the correct types in your examples which would help new users of your library to avoid typing errors. For example below page that shows how to use column groups in Angular misses any mention of required type when children are added to a column definition:

https://www.ag-grid.com/angular-data-grid/column-groups/

**Comment by StephenCooper** [comment]
Thanks for that feedback. Yes the snippets do not currently include the types and this is something we could look at improving.

We do provide the types in the example code.

So in the meantime view the code for the examples and that will show the types required.

![Screenshot 2024-01-04 at 11 47 24](https://github.com/ag-grid/ag-grid/assets/20125490/f5089eff-0a9a-401e-ba16-87f0e078be3e)

**Comment by smohadjer** [comment]
> Thanks for that feedback. Yes the snippets do not currently include the types and this is something we could look at improving.
> 
> We do provide the types in the example code.
> 
> So in the meantime view the code for the examples and that will show the types required.
> 
> ![Screenshot 2024-01-04 at 11 47 24](https://private-user-images.githubusercontent.com/20125490/294170193-f5089eff-0a9a-401e-ba16-87f0e078be3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODI3MDQsIm5iZiI6MTcwNDM4MjQwNCwicGF0aCI6Ii8yMDEyNTQ5MC8yOTQxNzAxOTMtZjUwODllZmYtMGE5YS00MDFlLWJhMTYtODdmMGUwNzhiZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYmRjYTM0YjNiYzgyYjdiNGM3MjQ2NmY4Y2ZkMzFkMDA0ZGI5NTExNDAzM2E4ZmI1ZDMyZWI5MWU2ZDgyNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pcKfm0mDkRwFV2FEV_LrdlMQJZp9dHAQYAZpSNtWLps)

Great tip. Thanks
