### ISSUE TITLE
 Class constructor BaseComponentWrapper cannot be invoked without 'new'

### ISSUE THREAD

**Issue by albacda** [ag-grid/ag-grid#7391]
**I'm submitting a ...** 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
I am getting next error when `<AgGridReact />` component from **ag-grid-react** is rendered after updating from version **30.0.2** to **30.0.6**:
<img width="661" alt="image" src="https://github.com/ag-grid/ag-grid/assets/117289133/e7d3a452-25f2-4181-bdd4-10c5994ea686">

* **AG Grid version:** 30.0.6
* **React version:** 17.0.2
* **Language:** Javascript

Thank you in advance for your support :)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by albacda** [comment]
I cannot replicate it a plunker. Here is the piece of code where code breaks:
<img width="677" alt="image" src="https://github.com/ag-grid/ag-grid/assets/117289133/295f4273-8a9c-4406-8f59-fca419a77187">

**Comment by AG-Zoheil** [comment]
Hi @albacda,

Thank you for your response.

Are you able to provide a mini-project isolating just this part of your code that can replicate the error? This would help us identify any potential issues.

Kind regards,
Zoheil
