### ISSUE TITLE
ag grid could not find row with id= 'x', data object was not found

### ISSUE THREAD

**Issue by AnikS0498** [ag-grid/ag-grid#7392]
example - 
{
"id": 4,
"group": "testGrp",
"dataId": 2,
"lang": "de",
"langType": "German",
}
 This id is present both in row.data.id as well as row.id.

**Current behavior**
even though I have the same id in row.data.id as well as row.id, with getRowId(params) => params.data.id. While deleting or editing a row, ag grid throws this error - 'ag grid could not find row with id= 'x', data object was not found'

**Expected behavior**
Since the id is present, I should be able to edit/delete the row.

AG Grid version: 29.2.0
Angular 16

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AnikS0498** [comment]
Closing the issue as the solution has been found
