### ISSUE TITLE
Ag-grid is not working aftre upgrading to v28 and angular v16

### ISSUE THREAD

**Issue by uthmanrahimi** [ag-grid/ag-grid#7393]
In my project I tried to update Angular to v16 and ag-grid to v 28.0.0, after upgrading angular, I updated ag-grid version and run `npm i --force`

I commented below code since not working in new version

```
ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  ServerSideRowModelModule,
  CsvExportModule,
  ExcelExportModule,
  MasterDetailModule,
  SideBarModule,
  StatusBarModule,
  ColumnsToolPanelModule,--
  FiltersToolPanelModule,--
  SetFilterModule,
  MenuModule,
  RowGroupingModule,
  InfiniteRowModelModule,
  RangeSelectionModule,
  ClipboardModule,
  RichSelectModule,
 MultiFilterModule
);
```
package.json fiel includes below

```
"dependencies": {
    "@ag-grid-community/all-modules": "27.2.1",
    "@ag-grid-community/angular": "28.0.0",
    "@ag-grid-enterprise/all-modules": "27.2.1",
    "@ag-grid-community/client-side-row-model": "28.0.0",
    "@ag-grid-enterprise/server-side-row-model": "28.0.0",
    "@ag-grid-community/csv-export": "28.0.0",
    "@ag-grid-enterprise/excel-export": "28.0.0",
    "@ag-grid-enterprise/master-detail": "28.0.0",
    "@ag-grid-enterprise/side-bar": "28.0.0",
    "@ag-grid-enterprise/status-bar": "28.0.0",
    "@ag-grid-enterprise/set-filter": "28.0.0",
    "@ag-grid-enterprise/menu": "28.0.0",
    "@ag-grid-enterprise/row-grouping": "28.0.0",
    "@ag-grid-community/infinite-row-model": "28.0.0",
    "@ag-grid-enterprise/range-selection": "28.0.0",
    "@ag-grid-enterprise/clipboard": "28.0.0",
    "@ag-grid-enterprise/rich-select": "28.0.0",
    "@ag-grid-enterprise/multi-filter": "28.0.0",
```

I am getting errors like below 

>  error NG8002: Can't bind to 'gridActions' since it isn't a known property of 'app-my-grid'.
> 1. If 'app-my-grid' is an Angular component and it has 'gridActions' input, then verify that it is part of this module.
> 2. If 'app-my-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 
> : Can't bind to 'rowHight' since it isn't a known property of 'app-my-grid'.

>  error NG8002: Can't bind to 'data' since it isn't a known property of 'app-cos-grid'.
> 1. If 'app-cos-grid' is an Angular component and it has 'data' input, then verify that it is part of this module.

![ag-grid](https://github.com/ag-grid/ag-grid/assets/45357615/ba8a4f5d-e3c6-44e8-8925-8a244933b261)

Should I do anything else? I tried updating other dependencies but nothing change.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

Please note the following section of our documentation: https://grid-staging.ag-grid.com/angular-data-grid/angular-compatibility/#migration-to-ag-grid-v28. 

If you've followed all guidelines in the documentation and are still facing issues we'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a mini-project reproducing the issue.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by uthmanrahimi** [comment]
@AG-Zoheil  Do I still need below package? because the lasted version is available for it is 27. I thought maybe this is the issue
```
  "@ag-grid-community/all-modules": "27.2.1",
    "@ag-grid-enterprise/all-modules": "27.2.1",
```

And also, Should I register all the module in Shared.Module? right now I am registering AgGridModule

**Comment by StephenCooper** [comment]
Hi @uthmanrahimi,

Please remove the all-modules packages as they are not supported anymore. 

The modules can be registered in the shared module as long as that will be loaded before any lazy loaded component containing AG Grid is loaded.

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
