### ISSUE TITLE
[React] Ag-Grid(31.0.1) crash on mount (Cannot read properties of null (reading 'getLeafColumns')

### ISSUE THREAD

**Issue by vitaliizharkov26** [ag-grid/ag-grid#7395]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
I'm not fully sure if it's a bug on the grid side or mine.
I'm updating the ag-grid from **v30.2.1 to 31.0.1** and when my grid is mounted I get a crash (also sometimes the grid is mounted and everything is ok), so it's occurring pretty randomly.
![image](https://github.com/ag-grid/ag-grid/assets/71453812/6bca5d97-baa8-418f-b134-00fa0189e114)
 
**On v30.2.1 everything is ok.** 
May I miss something important in the changelogs for v31?
(We are using all new methods/components based on the official documentation, no deprecated or removed methods)

I was trying to reproduce something in the official demo, but I don't know what causing this issue, it refers internal ag-grid component.

**Comment by StephenCooper** [comment]
Hi,

We have a fix for this which will be released as part of a patch in a week or so. Reference is AG-10098. 

Thank you for reporting.

**Comment by fitterfizzle** [comment]
Any news on when this is going to be released?

**Comment by StephenCooper** [comment]
Should be released this week.

**Comment by knovu** [comment]
> Same issue here, appeared after updating to v31.0.1 After some investigations, error disappears when all useEffects in file are removed (probably that's not related, just a funny fact)

@StephenCooper, we've also identified this as an issue on our end.  We have some external state (global state) that effects some filters within our table.

On the event external state changes, our tables that have "useEffects" all crash.

Thanks in advance for the update on release time.  Look forward to seeing this patch 🚀.
