### ISSUE TITLE
Support for Fresh Deno

### ISSUE THREAD

**Issue by hapaxlife** [ag-grid/ag-grid#7401]
I try to use AG Grid in Deno Fresh https://fresh.deno.dev/

Will you provide support for Fresh or examples linked to your web/React component ?

I explored 2 solutions without success
- use of web component
- use of react component linked to preact

**Comment by AG-Zoheil** [comment]
Hi @hapaxlife,

Thanks for getting in touch via GitHub.
This is not something we are currently looking to add support for. However this may change in the future.

Kind regards,
Zoheil
