### ISSUE TITLE
It says license key invalid.. (next.js 13 + ag-grid 31.0.1)

### ISSUE THREAD

**Issue by Brew-Brew** [ag-grid/ag-grid#7411]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

It says license key invalid.. when i check local it has not problem.. only production build error occurs.. and when i log at production it has valid license key..

+ i didn't mix loading mechanisms (only package)

import at root _app.tsx on next.js repo
```typecript
import { LicenseManager } from 'ag-grid-enterprise';
const licenseKey = process.env.AG_GRID_LICENSE_KEY;

LicenseManager.setLicenseKey(licenseKey as string);
```

I read all https://ag-grid.zendesk.com/hc/en-us/articles/360002455038-How-to-self-diagnose-your-license-key-issues article.. but don't know reaseon..
<img width="179" alt="스크린샷 2024-01-10 오전 1 05 26" src="https://github.com/ag-grid/ag-grid/assets/26598542/e1fcc65c-f3e4-4fe4-a49c-893bd136e02c">

**Expected behavior**

remove water mark (because i bought license for enterprise and deployment)

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

31.0.1
* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

**Comment by AG-Zoheil** [comment]
Hi @Brew-Brew,

Thank you for submitting this on GitHub.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

In this specific instance it would also protect your company's security & privacy as your query relates to licensing. With this in mind, I'll be closing this issue on GitHub.

Kind regards,
Zoheil
