### ISSUE TITLE
Where should I set licensekey on next.js with ssr? (key is invalid on only ssr)

### ISSUE THREAD

**Issue by Brew-Brew** [ag-grid/ag-grid#7413]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
It has no issue on next.js ssg environment on applying license key ( set license key on root _app.tsx file)
But only next.js ssr production environment has issue on inlitialize license key (it has no issue on local)

do you know why..?

next.js 12.3.1
ag-grid 31.0.1

inlitialize code on `_app.tsx`

```typescript
const licenseKey = process.env.AG_GRID_LICENSE_KEY;
LicenseManager.setLicenseKey(licenseKey as string);
```

**Expected behavior**

no issue on set license key

**Please tell us about your environment:**

next.js 12.3.1

* **AG Grid version:** X.X.X

ag-grid 31.0.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

typescirpt

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for submitting this on GitHub.

You've mentioned you are an enterprise client and I can see you have contacted us via our [support portal](https://ag-grid.zendesk.com/). That would be the quickest and most efficient route for you to get your question answered.

Therefore I will be closing this issue and we will continue discussions on there.

Kind regards,
Zoheil
