### ISSUE TITLE
Undefined sidebar getState after updating state for toolPanelParams

### ISSUE THREAD

**Issue by enricorobazza** [ag-grid/ag-grid#7419]
After updating from 30.03 to 31.0.1 my sidebar is not working anymore.

I have a custom component as sidebar panel, and share state with this component through toolPanelParams. Now in version 31, when the state is updated, an error message is thrown:

`Cannot read properties of undefined (reading 'getState')`

**Reproducible Scenario**

CustomStatsToolPanel is from the docs

```import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-quartz.css';
import React, { useState, useMemo } from 'react';
import { createRoot } from 'react-dom/client';
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/styles/ag-grid.css'; // Core CSS
import 'ag-grid-community/styles/ag-theme-quartz.css'; // Theme
import CustomStatsToolPanel from './components/SideBar/CustomStatsToolPanel';

// Create new GridExample component
const GridExample = () => {
  // Row Data: The data to be displayed.
  const [rowData, setRowData] = useState([
    {
      mission: 'Voyager',
      company: 'NASA',
      location: 'Cape Canaveral',
      date: '1977-09-05',
      rocket: 'Titan-Centaur ',
      price: 86580000,
      successful: true,
    },
    {
      mission: 'Apollo 13',
      company: 'NASA',
      location: 'Kennedy Space Center',
      date: '1970-04-11',
      rocket: 'Saturn V',
      price: 3750000,
      successful: false,
    },
    {
      mission: 'Falcon 9',
      company: 'SpaceX',
      location: 'Cape Canaveral',
      date: '2015-12-22',
      rocket: 'Falcon 9',
      price: 9750000,
      successful: true,
    },
  ]);

  const [count, setCount] = useState(0);

  // Column Definitions: Defines & controls grid columns.
  const [colDefs, setColDefs] = useState([
    { field: 'mission' },
    { field: 'company' },
    { field: 'location' },
    { field: 'date' },
    { field: 'price' },
    { field: 'successful' },
    { field: 'rocket' },
  ]);
  
  const filterSideBar = {
    id: 'filters',
    labelDefault: 'Filters',
    labelKey: 'filters',
    iconKey: 'filter',
    toolPanel: 'agFiltersToolPanel',
    toolPanelParams: {
      suppressSyncLayoutWithGrid: true,
    },
  };

  const columnSideBar = {
    id: 'columns',
    labelDefault: 'Columns',
    labelKey: 'columns',
    iconKey: 'columns',
    toolPanel: 'agColumnsToolPanel',
    toolPanelParams: {
      suppressPivotMode: true,
      suppressSyncLayoutWithGrid: true,
    },
  };

  const sideBar = useMemo(() => ({
    toolPanels: [
      columnSideBar,
      filterSideBar,
      {
        id: 'linkedWidgets',
        labelDefault: 'LinkedWidgets',
        labelKey: 'linkedWidgets',
        iconKey: 'linkedWidgets',
        width: 400,
        toolPanel: CustomStatsToolPanel,
        toolPanelParams: {
          count,
          suppressSyncLayoutWithGrid: true
        }
      },
    ],
  }), [count]);

  // Container: Defines the grid's theme & dimensions.
  return (
    <div
      className={
        "ag-theme-quartz"
      }
      style={{ width: '100%', height: '100%' }}
    >
        Count: {count}
        <button onClick={() => {
            setCount(count + 1)
        }}>Click ME</button>
      <AgGridReact sideBar={sideBar} rowGroupPanelShow={'always'} rowData={rowData} columnDefs={colDefs} />
    </div>
  );
};

export default GridExample;
```

**Current behavior**
Project breaks when state shared with the SideBar is updated

**Expected behavior**
SideBar is re-rendered with the updated state

**Please tell us about your environment:**
Windows, using pnpm

* **AG Grid version:** 
31.0.1

* **Browser:**
Chrome/120.0.0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by AG-Zoheil** [comment]
Hello @enricorobazza,

Thank you for reporting this - much appreciated!

We already have this bug in our backlog and with the following reference: **AG-10168**

A fix has been found and implemented. It will be released in our new version next week.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by zkAkshay** [comment]
What is the solution, your document do not mention things properly atall

**Comment by AG-Zoheil** [comment]
Hi 

Thank you for submitting this on Github.

**AG-10168** was fixed in version` 31.0.2`. Please upgrade to this version for the fix.

Kind regards,
Zoheil

**Comment by zkAkshay** [comment]
Sorry but looks like you had solved half the issue, i am facing another one, if my state that had been added on useMemo dependency changes quite a multiple time at some point the refresh(param) at ‘toolPanelWrapper.getToolPanelInstance().refresh(Params)’ is undefined and throws an error stating:

Cannot read properties of undefined(reading ‘refresh’) 
At eval (main.esm.mjs:22797:69)
At array.foreach ()
At sidebarcomp2.onsidebarupdated (main.esm.mjs:22778:58)
At eval (main.esm.mjs:1232:99)

Note: I am using enterprise version at my organisation and this issue is there in react version of ag grid

**Comment by AG-Zoheil** [comment]
Hi @zkAkshay,

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil

**Comment by zkAkshay** [comment]
Zoheil, its an organisation level license and login credentials are with org. I may not login to the support portal, but issue above is serious, when there is a quick change in the state sidebar is at some point looses the instance and throws up this error.

ex: if you have an API call and you are passing a state which changes based on the data that API is receiving then this fails with the above error.

**Comment by AG-Zoheil** [comment]
Hi @zkAkshay,

Please note that we do not provide support via GitHub.

Please get in touch with your account manager at your organisation to allow access to our enterprise support portal.

Many thanks!

**Comment by ykvarts** [comment]
Seeing exactly same problem as @zkAkshay mentioned with sidebarcomp update - is there a solution for this?
