### ISSUE TITLE
Got stuck after hiding all the table columns

### ISSUE THREAD

**Issue by MatteoBuffo** [ag-grid/ag-grid#7421]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello. I'm toying with [this simple example grid from your website](https://www.ag-grid.com/javascript-data-grid/column-definitions/#accessing-row-data-values).
- [CodeSandbox](https://codesandbox.io/p/sandbox/ag-grid-modules-2xcw63)
- [Preview](https://www.ag-grid.com/examples/column-definitions/column-fields/modules/vanilla/index.html)

**Current behavior**
As shown in the video below, I hide all the table columns. Once I hide the last one, I cannot do anything to make them visible (except controlling the columns visibility with an external component).

https://github.com/ag-grid/ag-grid/assets/56068232/ab861952-abdf-4633-a7dc-33485c7f807e

**Expected behavior**
I would like to know if there's a existing way to restore columns from their hidden state.

**Please tell us about your environment:**
Testing on your website.

* **AG Grid version:** 31.0.1 (your website runs the latest ag-grid version, I guess?)

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hi @MatteoBuffo,

The approach via our API may be something that would meet your requirements. Note the following example:

https://plnkr.co/edit/WwRGyxiyRYqOxN83?open=main.js&preview

- You can hide and unhide columns using the buttons at the top of the grid
- If you do hide the columns one by one using the drag functionality you can unhide them using the button at the top of the grid (you can define what columns you'd like to unhide based on your requirements)

I hope this helps.

Kind regards,
Zoheil
