### ISSUE TITLE
An error occurred with imports using @ag-grid-enterprise/core

### ISSUE THREAD

**Issue by yosuke0517** [ag-grid/ag-grid#7424]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
"I am using ag-grid-community, ag-grid-enterprise, and ag-grid-vue3 (version 28.2.1). As part of optimizing the bundle size, I changed the import method for LicenseManager as follows:
**before**: `import { LicenseManager } from 'ag-grid-enterprise'`
**after**: `import { LicenseManager } from '@ag-grid-enterprise/core'`

After making this change, an error started appearing in the console stating: 
```
'AG Grid: Row Model "Server Side" not found. Please ensure the AG Grid Enterprise Module @ag-grid-enterprise/server-side-row-model module is registered.' 
```

![スクリーンショット 2024-01-11 19 54 29](https://github.com/ag-grid/ag-grid/assets/39196956/e0e8a1f7-3e29-4f82-aa3c-7d74aeec9c64)

The likely cause of this error is the discrepancy in the registered modules since ag-grid-vue3 is using LicenseManager from ag-grid-enterprise. Looking at the latest source code of ag-grid-vue3, it seems that @ag-grid-enterprise/core is being used. Will this error be resolved if we update our license and upgrade to the latest version of ag-grid?"

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

An error like the one mentioned above occurs.

**Expected behavior**

No error like the one mentioned above occurs.

**Please tell us about your environment:**
- Operating system: macOS, 
- IDE: IntellijIdea
- package manager: yarn
- HTTP server: nodeJS

* **AG Grid version:** 28.2.1

* **Browser:**

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
```

* **Language:** [all | TypeScript 4.9.5 | ES6/7 ]

**Comment by AG-Zoheil** [comment]
Hi @yosuke0517,

You can find the answer to your questions on the following pages of our documentation:

General guide to Vue docs - https://ag-grid.com/vue-data-grid/modules/ 
When mixing modules and packages - https://ag-grid.com/vue-data-grid/modules/#mixing-packages-and-modules
Registering any modules you are using - https://ag-grid.com/vue-data-grid/modules/#registering-ag-grid-modules

When using modules, you need to replace all package imports with their corresponding module imports. Specifically for Vue 3, you need `@ag-grid-community/vue3`.

Kind regards,
Zoheil
