### ISSUE TITLE
CSP issue caused by new Function('...') on Advanced Filter

### ISSUE THREAD

**Issue by Archer03** [ag-grid/ag-grid#7428]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
have a CSP header without 'unsafe-eval'

**Current behavior**
Advanced Filter does not work, either by Apply button or Builder tool.

Uncaught Error: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not allowed

involved code:
https://github.com/ag-grid/ag-grid/blob/d64ae2da6a1dbb1c54fce1f3dc60aa2baddb523f/grid-enterprise-modules/advanced-filter/src/advancedFilter/advancedFilterService.ts#L184

* **AG Grid version:** 30.1.0

* **Browser:**
Chrome 120.0.6099.71 (Official Build)

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: AG-10306

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
