### ISSUE TITLE
ag-grid requirement to have a parent element explicitly carrying a 'height' ?

### ISSUE THREAD

**Issue by thebluemountain** [ag-grid/ag-grid#7434]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

issue:
when showing a grid in a modal dialog, the contained grid does not display if parent element 
does not explicitly carries 'height' value.

environment:
- js-only, no framework
- browsers: chromium (121.0.6153.0), firefox (121.0.1), safari (17.1.2)
- ag-grid: 31.0.1
- os: macos 14.1.2
- node: 21.2.0, npm: 10.2.3, vite: 5.0.10

reproduction:
in html with a dialog:
1- dialog is shown in modal flavor
2- grid is created and filled with data
3- issue: the grid does not display if parent element carries 'min-height' but not actual 'height'
     expected: the grid is expected to display in the parent element

i have attached a single html page that reproduce this issue and that allows to test the behavior of the 
ag-grid with and without a containing element explicitly carrying a 'height'

notes:
a- i have seen this ag-grid behaviour in the past ... on older versions of ag-grid, browsers and on linux as well
b- further looking at the state of the grid once dialog is displayed without grid with browser's inspector shows:
    - the element the grid was associated to (aka: container) has expected height
    - the internal ag-grid element (with class ag-root-wrapper) has height computed to 2px

Q: can we update the ag-grid documentation to explicitly list for this requirement, or change the ag-grid behavior to handle such use-case so that other developers will be aware of?

thank you,

you will find, attached a sample html file that highlights the issue
[grid.html.zip](https://github.com/ag-grid/ag-grid/files/13923184/grid.html.zip)

**Comment by AG-Zoheil** [comment]
Hey @thebluemountain,

thanks for raising this on GitHub.

I'm afraid, I've downloaded your zip but the html does not work as you've described. I can't get the modal to open (ie "Open" button does not perform any action) - can you please check your file and provide an updated version?

Many thanks!

**Comment by thebluemountain** [comment]
hi ag-zoheil,

you are correct ... as i don't reproduce it neither with this same setup.
my apologies for wasting your time and attention.

q: shall i close this ticket myself?
