### ISSUE TITLE
Column filter is not working, after using valueFormatter for numbers

### ISSUE THREAD

**Issue by srikanthuidev98** [ag-grid/ag-grid#7435]
** issue**
I'm formatting the data which is coming from my rest api using valueFormatter. So the actual data is 12345.7543, this is formatted to 12,345.75. Another scenario is actual data 0.7646, formatted to 76.46%. Here I'm using "agNumberColumnFilter" but it is not working.

** environment**
`
{
  "name": "ag",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "14.3.0",
    "@angular/common": "14.3.0",
    "@angular/compiler": "14.3.0",
    "@angular/core": "14.3.0",
    "@angular/platform-browser": "14.3.0",
    "@angular/platform-browser-dynamic": "~14.3.0",
    "@angular/router": "14.3.0",
    "ag-grid-angular": "^31.0.1",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "14.2.13",
    "@angular/cli": "14.2.13",
    "@angular/compiler-cli": "14.3.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.6.4"
  }
}

`

**ColDefs**

`
{
      field: "decimal",
      headerName: "Decimal",
      filter: 'agNumberColumnFilter',
      filterParams: {
      },
      valueFormatter: (params: ValueFormatterParams) => {
        return parseFloat(params?.value).toLocaleString(undefined, {
          minimumFractionDigits: 2,
          maximumFractionDigits: 2,
        });
      },
    },
{
      field: 'percentage',
      filter: 'agNumberColumnFilter',
      valueFormatter: (params) => {
        const percentageValue = params.value * 100;
        return percentageValue.toFixed(2) + '%';
      }
    }

`
**Browser**
chrome
**Current behavior**
if search on column filter, data is not returning. NO DATA is shown in the ui.

@adam-ag-grid @robindenton-ag-grid can you provide me the filter logic for above ColDefs. Thanks

**Comment by madhupprasad** [comment]
Hi @srikanthuidev98. The value formatter is only used for adding symbols or formatting stuff. The data used for filter will not be from the valueFormatter. It will actually be from the valueGetter. Thats why the filter wont work for data from formatter.

Example:

Actually the number below is only 7. But after valueFormatter it will be 700%. The filter will be applied for the value 7 only and not 700.

![Screenshot 2024-01-13 at 2 28 52 PM](https://github.com/ag-grid/ag-grid/assets/38370391/89da7c4b-1cc8-4781-86b0-bebaa28783d0)

**Comment by srikanthuppena98** [comment]
@madhupprasad ive tried with value getter as well, instead of value formatter. Still the column filter is not working

**Comment by madhupprasad** [comment]
```
var numberValueGetter = function (params: ValueGetterParams) {
  const percentageValue = params.data.sale * 100;
  return percentageValue;
};
```

```
valueFormatter: (params: ValueFormatterParams) => {
        return params.value + "%";
 },
```

**Comment by madhupprasad** [comment]
https://codesandbox.io/p/sandbox/ag-grid-packages-forked-mw9gdp?file=%2Fapp%2Fapp.component.ts%3A30%2C1-32%2C9 - this is the sandbox I tried.

**Comment by srikanthuidev98** [comment]
@madhupprasad I've seen your sandbox code and applied in my code, for some reason it is still not working, can you let me know if anything is wrong below code. Thanks 

` {
      field: 'percentage',
      filter: 'agNumberColumnFilter',
      valueGetter: (params: ValueGetterParams) => {
        return (params.data.percentage * 100).toFixed(2);
      },
      valueFormatter: (params) => {
        return params.value + "%";
      },
    }
`

**Comment by srikanthuidev98** [comment]
@madhupprasad now I understood, issue is with toFixed() method, if we remove this then it works. Even in your code If I add toFixed() then it is not filtering. Do you know how to handle this behavior.

**Comment by madhupprasad** [comment]
@srikanthuidev98. toFixed() will change the number to string. That should not be the return value for value getter as it expects number value. Instead you can add toFixed in valueFormatter()

**Comment by srikanthuidev98** [comment]
Ok, thanks for the clarification.

**Comment by suryamuppalla** [comment]
@madhupprasad Hi I had an issue with ag grid excel export, when data is null ag grid is adding 0 in the excel, instead of leaving them empty. I have created a codesandbox code sample, but unfortunately it is not reproducible here, if you try same code in vs code (Visual Studio Code) it is reproducible.

can you please let me know how to resolve this issue, thanks.

https://github.com/ag-grid/ag-grid/issues/7534

**Comment by srikanthuidev98** [comment]
Hi I had an issue with ag grid excel export, when data is null ag grid is adding 0 in the excel, instead of leaving them empty. I have created a codesandbox code sample, but unfortunately it is not reproducible here, if you try same code in vs code (Visual Studio Code) it is reproducible.

https://codesandbox.io/p/sandbox/ag-grid-modules-forked-rxmtk5?file=%2Fapp.component.ts

can you please let me know how to resolve this issue, thanks.
@madhupprasad

**Comment by Bond-Addict** [comment]
I had a similar issue so maybe this will help you out. This solution worked really well for me. This is Vue.js but it wouldn't be hard to apply to angular as well.

```javascript
<script setup lang="ts">
import { AgGridVue } from '@ag-grid-community/vue3';
import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
import { ColDef, GridApi, GridReadyEvent, ICellRendererParams, IProvidedFilterParams } from '@ag-grid-community/core';

import { DisplayColumn, TableParams } from '@/interfaces/table';
import { computed, PropType, shallowRef } from 'vue';
import { DataTableColumnSource } from 'vuestic-ui/web-components';
import { ActionType } from '@/interfaces/action-type';
import TableActions from './TableActions.vue';
import { useAgTableStore } from '@/stores/ag-table-store';
import { useRouter } from 'vue-router';

const props = defineProps({
	tableParams: { type: Object as PropType<TableParams>, required: true },
	state: { type: Object as PropType<any>, required: true },
	tableColumns: {
		type: Object as PropType<DataTableColumnSource<string>[]>,
		required: true,
	},
	itemEdit: {
		type: Function as PropType<(editItem?: any, actionType?: ActionType) => any>,
		required: true,
	},
});

const agTableStore = useAgTableStore();
const { beforeEach } = useRouter();

const gridApi = shallowRef<GridApi | null>(null);

const columnDefsRef = computed(() => {
	let columns = props.tableColumns.map<ColDef>((tc: DisplayColumn) => {
		return {
			field: tc?.key,
			...(tc?.displayFormatFn ? { valueFormatter: (data) => tc?.displayFormatFn(data.value) } : {}),
			...(tc?.canFilter !== false
				? {
						filter: true,
						filterParams: {
							buttons: ['reset'],
							textMatcher: ({ filterOption, value, filterText }) => {
								if (filterText == null) {
									return false;
								}
								const formattedFilterValue = (tc.displayFormatFn(value) as string).toLocaleLowerCase();
								const formattedFilterText = (filterText as string).toLocaleLowerCase();

								switch (filterOption) {
									case 'contains':
										return formattedFilterValue.includes(formattedFilterText);
									case 'notContains':
										return !formattedFilterValue.includes(formattedFilterText);
									case 'equals':
										return formattedFilterValue === formattedFilterText;
									case 'notEqual':
										return formattedFilterValue !== formattedFilterText;
									case 'startsWith':
										return formattedFilterValue.startsWith(formattedFilterText);
									case 'endsWith': {
										return formattedFilterValue.startsWith(formattedFilterText);
									}
									default:
										return false;
								}
							},
						} as IProvidedFilterParams,
					}
				: {}),
			sortable: tc?.sortable,
		};
	});

	columns = [
		...columns,
		{
			field: 'edit',
			headerName: '',
			cellRendererSelector: (rendererParams: ICellRendererParams) => {
				return {
					component: TableActions,
					params: {
						tableParams: props.tableParams,
						itemEdit: props.itemEdit,
						rowData: rendererParams.data,
					},
				};
			},
			cellClass: 'ag-right-aligned-cell',
		},
	];
	return columns;
});

const gridReady = (params: GridReadyEvent) => {
	gridApi.value = params.api;
	gridApi.value.setGridOption('domLayout', 'autoHeight');
	gridApi.value.updateGridOptions({
		domLayout: 'autoHeight',
	});
	gridApi.value.sizeColumnsToFit();

	const currentFilters = agTableStore.getFilters();
	if (currentFilters) gridApi.value.setFilterModel(currentFilters);
};

beforeEach((to, from) => {
	if (to !== from) agTableStore.clearFilters();
});
</script>
```

```html
<template>
	<ag-grid-vue
		class="dataTable ag-theme-vuestic ag-theme-vuestic--striped"
		:row-data="props.tableParams.tableItems"
		:column-defs="columnDefsRef"
		:modules="[ClientSideRowModelModule]"
		:pagination="true"
		:pagination-page-size="state.pageSize"
		:pagination-page-size-selector="state.options"
		@grid-ready="gridReady"
		@grid-size-changed="(e) => e.api.sizeColumnsToFit()"
		@filter-changed="() => agTableStore.setFilters(gridApi.getFilterModel())"
	/>
</template>
```

Quick breakdown how it works:

The basic structure what started off [Text Matcher](https://www.ag-grid.com/vue-data-grid/filter-text/#text-custom-matcher)

My page components pass a `tableParams` object already contains all my column definitions and also an table configuration items. One of those properties has an interface which contains `displayFormatFn?: (data: any) => any;`. When `displayFormatFn` is provided, it will automatically format the value to whatever I want. This important to me because I use it where I want to take the column value from being `{empId}` to `{empId}-{empName}`. 

`valueFormatter` does a great job of formatting the value in the table, but it doesn't include the full text value when filtering. It just uses the original `empId` only. That where `textMatcher` comes in. `textMatcher` gets called anytime a filter action is happening. All I do is figure out which column I'm in by checking `tc` which is the table column object then making sure to set them both to `toLocaleLowerCase()` before doing my comparison. This allows me to search for not only `empId` but also any part of `empName`. Each column has their own unique `displayFormatFn` and this works flawlessly for me.

Hopefully this helps someone out 😄
