### ISSUE TITLE
Render issue with the pinned columns

### ISSUE THREAD

**Issue by danielmalaton** [ag-grid/ag-grid#7436]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Plunker link: https://plnkr.co/edit/8uUh488RbOFxnx8I?open=main.js
It seems to happen when the grid size is small (small width)

**Current behavior**
`Athlete` column is displayed at the 3rd column

**Expected behavior**
`Athlete` column should be displayed at the 1st column

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @danielmalaton,

Thanks for raising this on GitHub.

Our current implementation unpins columns when the centre of the grid is less than 50px in width.
You can customise the logic of the unpinning order according to your preference - please see the link in this section of our documentation: https://ag-grid.com/javascript-data-grid/column-pinning/#resizing-pinned-sections.

Kind regards,
Zoheil

**Comment by danielmalaton** [comment]
When I set no columns to be unpinned technically:
```Typescript
  <ag-grid-vue
    :process-unpinned-columns="onProcessUnpinnedColumns"
  />

function onProcessUnpinnedColumns () {
  return [];
}
```
When I resize the grid width to be less or equal to the pinned area, the grid seems break or does not work fine.
