### ISSUE TITLE
When enter yyyy-mm-dd in a cell in the first row of a text editor, data disappears

### ISSUE THREAD

**Issue by tk2153** [ag-grid/ag-grid#7443]
initial data is as follows.
column data01 is used 'agLargeTextCellEditor'.
column data02 is normal editor.

![grid-data](https://github.com/ag-grid/ag-grid/assets/156865674/3ce8b108-f42c-4677-9469-0859bda3743a)

enter "1111-11-11" in the cell in first row of a text editor.

![case01-01](https://github.com/ag-grid/ag-grid/assets/156865674/76ebe722-7713-42be-b710-1a7adbcbceda)

then all data from the second line onwards disappear.

![case01-02](https://github.com/ag-grid/ag-grid/assets/156865674/71d7a578-8fb6-4cdb-8f6c-fd8c180fb4ac)

when start editting, text editor changes date editor.

![case01-03](https://github.com/ag-grid/ag-grid/assets/156865674/66bb04cf-6901-434a-b8be-c480da73fc39)

case column data01 is as follows.

![case02-01](https://github.com/ag-grid/ag-grid/assets/156865674/74fe9515-3844-42fd-ad11-c2846175e47f)

![case02-02](https://github.com/ag-grid/ag-grid/assets/156865674/d8c3652b-7a4f-4b36-b36b-6e39e3189f0a)

the data in cell in second row remains unchanged. but when end editting, data disappear.

![case02-03](https://github.com/ag-grid/ag-grid/assets/156865674/64c34dfa-47cf-425d-b30c-6942cb13b070)

[environment]
	React
	ag-grid-community 31.0.1
	ag-grid-react 31.0.1
	typescript 4.9.5

[code]

    const defaultColDefTest = {
        sortable: true,
        resizable: true,
        filter: true,
        editable: true,
        stopEditingWhenCellsLoseFocus: true,
    }

    const ColDefTest: ColDef[] = [
        {
            field: 'test_no',
            headerName: 'NO',
            headerTooltip: 'NO',
            width: 170,
        },
        {
            field: 'data01',
            headerName: 'data01',
            headerTooltip: 'data01',
            cellEditor: 'agLargeTextCellEditor',
            cellEditorPopup: true,
            width: 110,
        },
        {
            field: 'data02',
            headerName: 'data02',
            headerTooltip: 'data02',
            width: 200,
        },
    ]

    <div className='ag-theme-alpine  srch-grid-test' >
                            <AgGridReact
                                defaultColDef={defaultColDefTest}
                                columnDefs={ColDefTest}
                                rowData={testdata}
                                rowSelection={'single'}
                                rowHeight={26}
                                headerHeight={26}
                                pagination={false}

                            >
                            </AgGridReact>
    </div>

**Comment by tk2153** [comment]
Hi, Zoheil

I attach  code file. please check this.

[src-7443.zip](https://github.com/ag-grid/ag-grid/files/13984479/src-7443.zip)

**Comment by AG-Zoheil** [comment]
Hey @tk2153,

Thanks for this. Did you add the package.json file to the zip? I am unable to run it due to a missing file.

Please double check.

Kind regards,
Zoheil

**Comment by tk2153** [comment]
Hi, Zoheil

package.json file is this.

[package.json](https://github.com/ag-grid/ag-grid/files/14016808/package.json)

**Comment by AG-Zoheil** [comment]
Hi @tk2153,

Thanks, but still having issues:

```
Could not find a required file.
  Name: index.html
```

In any case, we've had a look at your code and can advise the following

1) Make sure you memoize your colDef as any action that triggers a re-render will cause things like [`cellDataTypes`](https://ag-grid.com/react-data-grid/cell-data-types/) to recalculate and therefore cause your columns to potentially change.

2) You can choose to turn `cellDataTypes` off for a specific column, this could prevent issues like this as the automatic inference would treat the column as datetype when you enter 1111-11-11.

I hope this helps.

Kind regards,
Zoheil

**Comment by tk2153** [comment]
Hi, Zoheil

Thank you for your helps. To turn cellDataTypes off worked.
It may not be necessary, but I add index.html.

[index.zip](https://github.com/ag-grid/ag-grid/files/14059064/index.zip)
