### ISSUE TITLE
Prevent sorting on edit

### ISSUE THREAD

**Issue by krjk333** [ag-grid/ag-grid#7444]
If any sorting (asc/desc) is enabled for a column and we are editing any cell of the column, then the edited row's position automatically changing based on the sorting. How to suppress this. any properties or any tricks please.

**Comment by AG-Zoheil** [comment]
Hi @krjk333,

Could you please provide a reproducible scenario that shows the behaviour you are reporting. You can use any of the examples from our documentation as a starting point. Alternatively, I have tried to reproduce what you are reporting in this plunker and I am unable to do so: https://plnkr.co/edit/iMOYWZr8L7akbkXw?open=main.js.

Feel free to fork it and adjust it so it showcases the issue you are facing.

Looking forward to your response.

Kind regards,
Zoheil

**Comment by krjk333** [comment]
@AG-Zoheil Thanks for your kind reply. yes, I also unable to reproduce the same here. It is a commercial project, so I can't share what exactly here . But, one thing is clear that my issue is not created by default. it is because of some other property may be. let me check it.

**Comment by krjk333** [comment]
@AG-Zoheil , 
I have to call the updateRowData() method in the value setter to set the value back to the object. That's what refreshing the grid sort. Any possible to use the same without refresh?

**Comment by AG-Zoheil** [comment]
Hi @krjk333,

Please view the following that should help with your query: https://ag-grid.com/javascript-data-grid/data-update-single-row-cell/#sort--filter--group-refresh

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
