### ISSUE TITLE
Allow to update initial state of Ag Grid

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7445]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://www.ag-grid.com/react-data-grid/grid-state/#saving-and-restoring-state

As of now state as a single object could be only applied to the AgGrid only when it's an initial state
What if we want to update the grid state after the grid has been initialized or we want to apply state after firstDataRendered event.

E.g. in the following example,
https://plnkr.co/edit/OvGOW7saXv4jfjxy?open=index.jsx&preview
After performing some sorting, filtering and reordering of columns, on onStateUpdated event callback I'm storing grid state as a single state in session storage

**Expected behavior**
On reload of browser, I want to update grid state which I fetch from the storage and sets in onFirstDataRendered event.
So either an API method that updates the grid state and save as a single object or making initial state as reactive so it can be updated whenever required.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
31.0.2

* **Browser:**
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* React + TypeScript

**Comment by AG-Zoheil** [comment]
Hi @melon2504,

Thanks for getting in touch via GitHub.

We won't be considering this feature request at this point in time. In reality, you can achieve your desired outcome using the current functionality within the grid. See our adjusted plunker here: https://plnkr.co/edit/JAj5Nd416UdppV9J?open=index.jsx.

If you are working in an asynchronous fashion, we would advise deferring loading the grid until initialState is ready.

Kind regards,
Zoheil
