### ISSUE TITLE
addEventLisener / removeEventListener have incompatible type for rxjs@7

### ISSUE THREAD

**Issue by thekip** [ag-grid/ag-grid#7449]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current types for `addEventLisener` / `removeEventListener` looks like following: 

```ts
class GridApi {
    addEventListener(eventType: string, listener: Function): void;
    removeEventListener(eventType: string, listener: Function): void;
}
```

Which is not particularly right.  The type `Function` for typescript is too wide, even class constructor satisfies a `Function` type. So usually `Function` is not recommended to use anyway. 

It wasn't a big issue for us as a consumers until now when we upgraded to rxjs@7 which has more stricter typings. The current signature of `addEventLisener / removeEventListener` is no longer compatible with any of the rxjs `fromEvent` overloads and make using this two together a bit cumbersome: 

```ts
const eventStream = fromEvent(gridApi, 'eventName'); // <--- now this is incompatible by types
```

This could be easily fixed by writing stricter type instead of `Function`:

```ts
class GridApi {
      addEventListener(eventType: string, listener: (...args: any[]) => void): void;
      removeEventListener(eventType: string, listener: (...args: any[]) => void): void;
}

I think this would be beneficial not only for rxjs compatibility but also for other other integrations since the signatures i wrote above is considered as `NodeCompatibleEventEmitter`

**Comment by StephenCooper** [comment]
Hi @thekip,

Thanks for highlighting this issue. We have plans to introduce the following type for this method but did not want to introduce it in a patch as it could technically be a breaking change.

I would be interested to know if this would actually also cause issues for your use case?

```ts
type AgEventListener<TData = any,TContext = any> = (event: AgGridEvent<TData, TContext>) => void;

class GridApi {
      addEventListener(eventType: string, listener: AgEventListener): void;
      removeEventListener(eventType: string, listener: AgEventListener): void;
}
```

**Comment by thekip** [comment]
Checked, it works. Since `(event: AgGridEvent<TData, TContext>) => void;` satisfies `(...args: any[]) => void` 

I'm wondering if you are already going to change these types, maybe consider adding a map with `eventName => eventType` as it's done for DOM events in typescript?

**Comment by thekip** [comment]
Something like this: 

```ts
  interface GridEventsMap {
    cellFocused: CellFocusedEvent,
    filterChanged: FilterChangedEvent,
  }
  
  interface GridApi {
    addEventListener<K extends keyof GridEventsMap>(type: K, listener: (ev: GridEventsMap[K]) => void): void;
  }
```

**Comment by StephenCooper** [comment]
Yes, we have plans to improve the typings sounding events.

Your suggested improvement for this specific method is nice I'm that it is completely isolated and only lives in Typescript. 

We would also like to take it further and discriminate within events based on their type  property. However, that requires more changes to our existing types.

**Comment by AG-Zoheil** [comment]
Hello 

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-10420**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
