### ISSUE TITLE
Column width is not properly restored when using applyColumnState

### ISSUE THREAD

**Issue by gerricom** [ag-grid/ag-grid#7450]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

**Current behavior**

Look at this Plunker: https://plnkr.co/edit/ElfNoSSoyfxqRBAf

Do the following:
- Change a width of a column
- Sort by a column of your choice
- click "Save State"
- Now change the width again, do some sorting etc.
- click "Restore State"

The sorting is set correctly, but the width of the columns is omitted.

**Expected behavior**
This worked in the latest 30.2.1 - take a look at this Plunker: https://plnkr.co/edit/b0O9TDWE5n6bUUNY
Do the steps from above. The width of a column is set correctly.

**Please tell us about your environment:**
Plain JavaScript/Typescript usage of AG Grid

* **AG Grid version:** 31.0.2

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0

* **Language:** all | TypeScript X.X | ES6/7 | ES5

**Comment by oleurud** [comment]
Great! Thank you for the quick fix

**Comment by ackerleytng** [comment]
It seems like this is still broken in 31.2.0: https://plnkr.co/edit/Z5FPgPqjMW7QzMb4

**Comment by AG-Zoheil** [comment]
Hi,

You were using 31.0.2 instead of 31.2.0.

See it working here (forked from your example and just updated versions): https://plnkr.co/edit/7Uy4ohR8ixvoYNbK

Thanks!

**Comment by ackerleytng** [comment]
Oops, my bad. Thanks!

**Comment by Dishank-Mobiux** [comment]
@AG-Zoheil Is it only resolved for community version?

**Comment by AG-Zoheil** [comment]
Hi @Dishank-Mobiux,

No, this is not enterprise/community related and should work for everyone.

If you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil
