### ISSUE TITLE
support calling  getMultipleSheetsAsExcel with exportparams:{data:[xml,xml,xml], filename} directly

### ISSUE THREAD

**Issue by lxx9824** [ag-grid/ag-grid#7452]
I use ag-grid-vue in my project and i want to export about 1000 sheets(100 sheets, 10 groups) at same time.(the browsers will crashed sometimes)

I stored the xml result returned from gridApi.getSheetDataForExcel(exportParams) in IndexedDB cache

the next time i want to export , i retrieve the xml data from indexedDB and call getMultipleSheetsAsExcel(params) directly.

Some errors occur!

I supposed the error occur beacause i doesn't register? 

===========================================
Here's the errors i met : 

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.getTemplate (http://127.0.0.1:3000/dist/vendors-node_modules_ag-grid-enterprise_dist_ag-grid-enterprise_auto_esm_js.build.js:62597:42)
    at Object.getTemplate (http://127.0.0.1:3000/dist/vendors-node_modules_ag-grid-enterprise_dist_ag-grid-enterprise_auto_esm_js.build.js:63237:50)
    at ExcelXlsxFactory.createStylesheet (http://127.0.0.1:3000/dist/vendors-node_modules_ag-grid-enterprise_dist_ag-grid-enterprise_auto_esm_js.build.js:63981:48)
    at getMultipleSheetsAsExcel (http://127.0.0.1:3000/dist/vendors-node_modules_ag-grid-enterprise_dist_ag-grid-enterprise_auto_esm_js.build.js:64250:107)
    at ExcelCreator.getMultipleSheetsAsExcel (http://127.0.0.1:3000/dist/vendors-node_modules_ag-grid-enterprise_dist_ag-grid-enterprise_auto_esm_js.build.js:64349:16)
    at GridApi.getMultipleSheetsAsExcel (http://127.0.0.1:3000/dist/vendors-node_modules_ag-grid-enterprise_dist_ag-grid-enterprise_auto_esm_js.build.js:20616:38)
    at Object.<anonymous> (http://127.0.0.1:3000/dist/home.build.js:1705:42)
    at Generator.next (<anonymous>)
    at fulfilled (http://127.0.0.1:3000/dist/home.build.js:1458:24)

**Comment by lxx9824** [comment]
I supposed the error occur beacause i doesn't register the grid by calling gridApi. getSheetDataForExcel

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by lxx9824** [comment]
> Hi
> 
> Thank you for reporting this.
> 
> We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.
> 
> Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.
> 
> We're looking forward to your response.
> 
> Kind regards, Zoheil

Hi, Zoheil! Thanks for your reply!
I prepared an simplify example about this issue.
Here is  the url:  https://plnkr.co/edit/QPDmCAoxCx5DR2z4?open=main.js
 
================================
Firstly,  click the ''init db'' button to initialize an indexedDB database .
Secondly, click the ''Export to excel"  button and some errors will occur!

In my project, I needs to export a lot of grids. sometimes the browser will out of memory and crash! 
So I have to store the xml type data return from the gridAPI.getSheetDadaForExcel() in indexedDB.  
and the next time i open the app, i retrieve the data from indexedDB and call gridAPI. getMultipleSheetsAsExcel( { data:[xml, xml], filename } ) to export.

But it seems that ag-grid doesn't support it!

I am looking forward to your response.

Kind regards,
Xiaoxin

**Comment by AG-Zoheil** [comment]
Thanks @lxx9824,

we've had a look and it seems like your not setting things up correctly. This guide here should direct you to the correct approach: https://www.ag-grid.com/vue-data-grid/excel-export-multiple-sheets/#how-it-works. Any support beyond that is outside of the remit of GitHub as Excel export is an enterprise feature.

As we do not provide support on GitHub but only take bug reports, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here.

Kind regards,
Zoheil
