### ISSUE TITLE
Infinite scrolling - How to put newlines/line breaks in CellRenderer

### ISSUE THREAD

**Issue by MatteoBuffo** [ag-grid/ag-grid#7453]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
Hi. In the [provided Plunker](https://plnkr.co/edit/iwDKgEA3BcNbJntZ?open=index.jsx) grid I added a CellRenderer to the Age column. In this renderer I would like to show different data in multiple lines.

**Providing a Reproducible Scenario**
[Plunker](https://plnkr.co/edit/iwDKgEA3BcNbJntZ?open=index.jsx)

**Current behavior**
The grid is not showing the whole lines of the renderer: only the first one is visible.

**Expected behavior**
I would like to see the whole of the lines from the renderer.

**Please tell us about your environment:**
Windows 10, React project (JS)

+ AG Grid version: ^31.0.1 (ag-grid-react)

+ Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

+ Language: JS

**Comment by AG-Zoheil** [comment]
Hi @MatteoBuffo,
 
Thanks for reaching out about this.
 
By default, HTML doesn't render line break characters. AG Grid works the same way - values containing new lines will not be displayed on multiple lines. Just like rendering any HTML content, if you need a line break, you need to inject <br> in the HTML.
 
This is why you need a custom cell renderer to replace new line characters with <br>'s before rendering the cell values.
 
Please see this example here using the LargeTextEditor: https://plnkr.co/edit/5xqimOURRaAMgT7x?open=main.js

I hope this helps.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi @MatteoBuffo,

Did you click Preview to view the grid? Top right.

**Comment by MatteoBuffo** [comment]
@AG-Zoheil whoops, didn't notice it. Your example works, but mine still doesn't (I edited the cellRenderer and added more fields to the col properties). Could it be that my table uses `datasource` (with `rowModelType={"infinite"}`) instead of `rowData`?

**Comment by AG-Zoheil** [comment]
No that shouldn't be a problem. See column Large Text Editor in this example which uses the infinite row model https://plnkr.co/edit/nwxqocE1F9xOTKyN?open=main.js.

**Comment by MatteoBuffo** [comment]
@AG-Zoheil this is your latest example. Am I missing something?
https://github.com/ag-grid/ag-grid/assets/56068232/fecb1e37-d4a3-41c3-b55e-eb53de508cc2

**Comment by AG-Zoheil** [comment]
Hi @MatteoBuffo,

So the `cellRenderer` actually works regardless of the `rowModelType`. You can see that when you inspect the DOM in the example I sent with the infinite row model (https://plnkr.co/edit/nwxqocE1F9xOTKyN?open=main.js). The `<br>` tags are present.

However, because `autoHeight` is not compatible with this type of row model you are unable to see this reflected in the rows of the grid. You could set your fixed row height to be a bit larger if you wish - that may solve this for you. See this implemented here: https://plnkr.co/edit/PQgbfRc80ogrSDD7?open=main.js.

I hope this helps.

**Comment by MatteoBuffo** [comment]
@AG-Zoheil yes! That did it, thank you for your patience.
