### ISSUE TITLE
Unable to scroll horizontally using trackpad on Mac when mouse is hovering header

### ISSUE THREAD

**Issue by demaMarcos** [ag-grid/ag-grid#7456]
**I'm submitting a ...**
```
[x] bug report 
[] feature request 
[] support request
```

**Providing a Reproducible Scenario**

1. Open this plunker: https://plnkr.co/edit/T3OQOEiop55q6Bv9?open=index.tsx
2. Make screen small so that there are columns overflowing horizontally
3. Try to scroll horizontally using trackpad (using corresponding gesture, for me it is two fingers to the side) when mouse is hovering the header

**Current behavior**
It is not possible to scroll horizontally using trackpad on Mac when hovering the header

Recording shows below the Plunker example and how I can scroll when mouse is on top of rows but not on top of header
https://github.com/ag-grid/ag-grid/assets/150044009/d00db036-8ee5-4b8d-b00d-d66de388aa80

**Expected behavior**
It should be possible to scroll horizontally. Checked on the [changelog](https://www.ag-grid.com/changelog/) and it was supposed to be solved in version 30.2.1. The issue was AG-9566. 

**Please tell us about your environment:**
MacBook Pro. MacOS 14.2.1

**AG Grid version:** 
31.0.2

**Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Language:** 
React

**Comment by AG-Zoheil** [comment]
Hello @demaMarcos,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-2065**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
