### ISSUE TITLE
Aggrid set filter not working in serverSide row model in react

### ISSUE THREAD

**Issue by PraneethKanamarlapudi9** [ag-grid/ag-grid#7460]
Hi 
I'm using aggrid in react enterprise, I have been using serverside rowmodel in v30.0.1, For the filter, I'm able to pass the values to the filterparams asynchronously, but when when handling checkbox selection/deselection, I'm getting this error. 

Note:
When I'm using v28.2.0, I'm able to set the filtervalues using set fillter and selection and deselection is working fine.
![Notes_240118_132254_17a](https://github.com/ag-grid/ag-grid/assets/101590386/31ebf4b2-8ae0-4849-9b92-fca5afd737d8)
![Notes_240118_132047_7ee](https://github.com/ag-grid/ag-grid/assets/101590386/bd84c1d4-48ba-4914-9bca-a73a76906b5f)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by PraneethKanamarlapudi9** [comment]
Na
