### ISSUE TITLE
is Vue3 `defineExpose` supported?

### ISSUE THREAD

**Issue by oleurud** [ag-grid/ag-grid#7476]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Using Vue3, I have a custom cell editor

```js
<template>
   ... whatever
</template>

<script lang="ts" setup>

function getValue () {
  return 'hello'
}

function isPopup () {
  return true
}

defineExpose({
  getValue,
  isPopup
})

</script>
```

In local, everything works fine. But when building it for production using `Vite`, it fails:

```
AG Grid: Framework component is missing the method getValue()
```

and also, it is not using the popup.

Am I missing something? Does the library work fine with `defineExpose`? If not, I guess I need to rewrite my editors using the setup method instead of `script setup`

Thank you

**Comment by oleurud** [comment]
It works using the setup method instead of `script setup`

```
<template>
   ... whatever
</template>

<script lang="ts">
export default {
  setup (props: Props) {
    function getValue () {
      return 'hello'
    }

    function isPopup () {
      return true
    }
  
  return {
    getValue,
    isPopup
  }
}
</script>
```

**Comment by oleurud** [comment]
I asked for community support, but it is not needed anymore. 

But I think a comment in the documentation would be great @AG-Zoheil in case `defineExpose` is not supported, since it is the default way of working with Vue3 for single file components and the new composition API (I guess most of the people will be using this more and more)

**Comment by AG-Zoheil** [comment]
Thanks @oleurud,

I'm not too familiar with Vue but `<script setup>` support was added via **AG-8274** in v31 of the grid. So therefore please confirm
1) Is that what you are after? If so it should work from v31 onwards
2) What version of AG Grid are you using
3) If you think there's still an issue, please provide a reproducible scenario that we can investigate

Many thanks!

**Comment by oleurud** [comment]
There are no issues with this, as you can see in my [second comment](https://github.com/ag-grid/ag-grid/issues/7476#issuecomment-1904327237), it is pretty easy to change the code to make it work. But a comment in the docs would be great.

Currently using the version `31.0.1`. 

More info about [script setup](https://vuejs.org/api/sfc-script-setup.html) just in case :) 

Thank you

**Comment by alaarihan** [comment]
When use <script setup> we still get this error `AG Grid: Framework component is missing the method getValue()` so while it's the default now to use <script setup> and defineExpose with Vue 3, I believe this is important to support now, so please reopen this issue

**Comment by AG-Zoheil** [comment]
Hello,

if you could please provide a reproducible example we'll be happy to take a look at this.

Thank you!
