### ISSUE TITLE
AG Grid React- Updating the data causes the custom cell renderers to unmount and then remount instead of just updating the props

### ISSUE THREAD

**Issue by aron51** [ag-grid/ag-grid#7482]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
I'm updating the AG Grid version in my React project from 28.2.1 to 31.0.2. My app polls the data from the server, and every time I get back the new data the state of the custom cell renderers reset. I think it's happening beacuse the components are unmounted and re-mounted, instead of just receiving the latest props. 
I have some logic the relies on previous props and state, so this all breaks as re-mounting the components resets them to undefined.
This all worked well in version 28.2.1, and I haven't changed anything in my code, other then the version update. Is there any new flags I should set, or something I should do differently in the newer version?

**Expected behavior**
Custom cell renderer components receive the latest props without re-mounting.

**Please tell us about your environment:**

* **AG Grid version:** 31.0.2.

* **Browser:**Chrome

* **Language:** TypeScript 5.2.2

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue. You've upgraded from several versions ago which is great, but it makes it harder to pin-point changes that could have affected your set up.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

Alternatively, this approach here might achieve what you are after: https://plnkr.co/edit/xz9n5b0qlDddwa4w?open=index.tsx&preview.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by aron51** [comment]
I created two examples from your link:

- This is based on the link you shared with me, in the console it can be seen that every time we poll the data, the custom cell renderer re-mounts: https://plnkr.co/edit/DMhGuBlKjUVUcxet?open=index.tsx&preview
- I created the same example, with version 28.2.1, and we can see in the console that the custom cell renderers don't re-mount: https://stackblitz.com/edit/react-starter-typescript-nahxeh?file=App.tsx

The code is the same, just the versions are different.

Thank you,
Aron

**Comment by AG-Zoheil** [comment]
Thanks @aron51,

Please use row IDs, otherwise the rows get destroyed and recreated - please follow the guideline provided here: https://ag-grid.com/react-data-grid/data-update-row-data/.

Thanks!

**Comment by aron51** [comment]
Thank you for your response.

I could find and fix the problem. I was already using row IDs, so it wasn't that, but I passed a `rowClassRules` object to the grid that wasn't memoized, so it changed with every render. Wrapping it in a `useMemo` and passing a stable reference seems to have fixed my problem.

Best regards,
Aron
