### ISSUE TITLE
Pagination page number set to initial value after state change 

### ISSUE THREAD

**Issue by MatteoBuffo** [ag-grid/ag-grid#7487]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

Hello. In the [provided Plunker](https://plnkr.co/edit/gvLkFuei3oItZnd9?open=index.jsx) I created an infinite row model grid with pagination.

**Providing a Reproducible Scenario**
[Plunker](https://plnkr.co/edit/gvLkFuei3oItZnd9?open=index.jsx)

**Current behavior**
When I'm in a page different from 1 and I click the `Toggle testValue` button to change the state variable testValue value, the grid page is always reset to 1. That's quite annoying. The fact that the rows go blank for a moment before showing up again is annoying as well.

**Expected behavior**
I would like the page value to be persisted across state changes.

**Please tell us about your environment:**
Windows 10, React project (JS)

AG Grid version: ^31.0.1 (ag-grid-react)

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

Language: JS

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
