### ISSUE TITLE
Excel export date format not ok in WPS Office

### ISSUE THREAD

**Issue by mandeep242** [ag-grid/ag-grid#7489]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

When we exporting to excel via this link from linux and opening in WPS date is always year 1905
https://www.ag-grid.com/javascript-data-grid/excel-export-data-types/

**Expected behavior**

Date in AG-Grid should be in WPS

**Please tell us about your environment:**

Ubuntu

* **AG Grid version:** X.X.X

Latest

* **Browser:**

Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @mandeep242,

Thanks for getting in touch via GitHub.

Could you please confirm if the date is displayed correctly when exporting to Microsoft Excel?

Thank you!

**Comment by mandeep242** [comment]
Yes it is displaying correctly in ms-excel and latest version of wps

**Comment by AG-Zoheil** [comment]
Right, glad to hear it is working in both Excel and latest version of WPS. It looks like this there is nothing actionable here for AG Grid and hence I'll be closing this issue.

Thank you!
