### ISSUE TITLE
Pivot Table not providing standard Totals Field Pivot support

### ISSUE THREAD

**Issue by lovgrandma** [ag-grid/ag-grid#7500]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
We are attempting to show totals in a final column in a pivot grid. It seems relatively complex to achieve this as the API doesn't show this use case. For example, in the screen shot we want to see in 2008 all entities (athletes) in this domain (country) had 4 units (gold). We want this to show in a final totals column.
<img width="983" alt="Screenshot 2024-01-24 at 1 26 43 PM" src="https://github.com/ag-grid/ag-grid/assets/32661318/ac43ee43-5953-4197-862d-865191005b91">

I have an idea to create a fake record with no values under the entity and then manually mapping through the row to get the total, but then it would also have to be under the same domain to be painted. This would immediately grow into a bigger problem since we are trying to have tabular functionality for multiple selections of domains, e.g Canada, America, Germany, Australia etc. That would become a hacky solution.

**Expected behavior**
API functionality to produce final "totals" column in pivot table

**Please tell us about your environment:**
React.js on Chrome Browser on Mac Machine, localhost

* **AG Grid version:** X.X.X
Managed internally 28.2.1 ag-grid-enterprise/dist

* **Browser:**
Mozilla/5.0(Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Javascript

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference : **AG-4242**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by Jumpis** [comment]
any update for this feature?
