### ISSUE TITLE
[React] v31.0.3 ColDef[] is not compatible with AgGridReact's columnDefs prop

### ISSUE THREAD

**Issue by tamasfilkor-lab49** [ag-grid/ag-grid#7504]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://codesandbox.io/p/sandbox/gracious-blackburn-qdtf8z?file=%2Fsrc%2FGrid.tsx%3A16%2C41

**Current behavior**
When using the code sample from the documentation's "Get started" section, the following errors are encountered:

1. When using the explicit ColDef[] type from "@ag-grid-community/core":
```
Type 'ColDef<any, any>[]' is not assignable to type '(ColDef<any, any> | ColGroupDef<any>)[]'
```
2. When using the inferred type:
```
Type '{ field: string; }[]' is not assignable to type '(ColDef<{ make: string; model: string; price: number; electric: boolean; }, any> | ColGroupDef<{ make: string; model: string; price: number; electric: boolean; }>)[]'
```

**Expected behavior**
The ColDef type should be assignable to the columnDefs prop of the AgGridReact component without any type compatibility errors. This behavior should align with the documentation/examples.

**Environment**
* **AG Grid version:** 31.0.3
* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
* **Language:** TypeScript 5.3.3, React 18.2.0

**Comment by StephenCooper** [comment]
Hi @tamasfilkor-lab49,

The issue with that sandbox is that you a mixing what we call Packages and Modules. Please see https://ag-grid.com/react-data-grid/modules/#mixing-packages-and-modules

So the imports should be:

```ts
import { AgGridReact } from "@ag-grid-community/react";
import { ColDef } from "@ag-grid-community/core";
```

You had
```ts
import { AgGridReact } from "ag-grid-react"; // Package version
import { ColDef } from "@ag-grid-community/core"; // Module version.
```

https://codesandbox.io/p/sandbox/epic-burnell-xz9tmq?file=%2Fsrc%2FGrid.tsx

Did you copy this from one of our examples?

**Comment by StephenCooper** [comment]
> I'm seeing a similar error when following the quick start example verbatim

Thanks for letting us know. 

I see that providing the type of `ColDef[]` resolves the issue. We will get this updated.

```
const [colDefs, setColDefs] = useState<ColDef[]>([
```

**Comment by gavacq** [comment]
Yup thanks!
