### ISSUE TITLE
Lack of Documentation and Improvement Suggestions for ag-Grid

### ISSUE THREAD

**Issue by indrajithvinodnair** [ag-grid/ag-grid#7508]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
The current state of ag-Grid documentation poses significant challenges for users, particularly in the areas of version management, organization, and clarity. I'd like to highlight a few critical issues that, if addressed, could significantly enhance the user experience and streamline the onboarding process.
1. Lack of Version-specific Documentation

    Issue: There is no apparent way to access or reference documentation for older versions of ag-Grid.
    Impact: Users working with specific versions may struggle to find relevant information, hindering development and troubleshooting efforts.
    Suggestion: Implement a version selector on the documentation site to allow users to easily navigate to documentation for their specific ag-Grid version.

2. Scattered Documentation

    Issue: Documentation is scattered across different locations, making it challenging for users to find comprehensive information.
    Impact: Users spend unnecessary time searching for relevant details, leading to frustration and a less productive development experience.
    Suggestion: Consolidate and organize documentation in a user-friendly manner, grouping related information together to improve accessibility.

3. Redundant npmjs Pages

    Issue: npmjs pages for ag-Grid packages lack specific details, such as package inclusion and use cases, causing confusion.
    Impact: New users may struggle to understand the differences between packages, such as ag-grid-angular and @ag-grid-community/angular.
    Suggestion: Enhance npmjs package pages with package-specific information, usage guidelines, and potential use cases to provide a clearer understanding.

4. Lack of Migration Guides for Deprecated Packages

    Issue: Migration guides for deprecated packages, like @ag-grid-community/all-modules, are non-existent.
    Impact: Users encounter challenges when transitioning from deprecated packages to newer versions without clear guidance.
    Suggestion: Provide comprehensive migration guides for deprecated packages, explaining the transition process and necessary steps.

5. Absence of Framework-specific Examples

    Issue: Documentation lacks framework-specific StackBlitz or CodeSandbox examples.
    Impact: Developers, especially those new to ag-Grid, face difficulties implementing solutions in specific frameworks.
    Suggestion: Include framework-specific examples in the documentation to showcase integration and usage within popular frameworks.

Offer of Assistance

I am eager to contribute to improving the ag-Grid documentation and addressing these issues. I believe that enhancing the documentation will greatly benefit the ag-Grid community, making it more accessible and user-friendly.

Thank you for considering these suggestions, and I look forward to collaborating on improving the ag-Grid documentation

**Comment by AG-Zoheil** [comment]
Hi @indrajithvinodnair,

Thank you for taking the time to raise this issue on GitHub.

We're always keen to make improvements to our documentation and feedback like this is very welcome.

In regards to your points specifically, please see my comments below:

**Lack of Version-specific Documentation**

1. You can find a link to our documentation archive in our footer. Here is the direct link which contains documentation for our previous releases: https://ag-grid.com/archive/
2. We've also recently added a "What's new section" which can be found at the top left of our documentation menu. This section will highlight the most important changes in recent releases and provide links for more details on them. Here is the direct link for this page: https://ag-grid.com/whats-new/

**Scattered Documentation**

This is an ongoing effort. As you can appreciate the grid has grown (and keeps on growing) over the years at different speeds and intensities. At times we've managed to cover all new features and functionalities well, and other times our efforts in documenting these has not been sufficiently matched with our effort on actually working on and releasing these features and functionalities. We will continue to make improvements as we go along and work on specific areas of the grid.

**Redundant npmjs Pages**

As part of our commitment to keep improving our documentation we have recently simplified and rewritten this section in our documentation. Here is a direct link to the installation guide, but please note the different sections in the left menu that you can navigate to: https://ag-grid.com/javascript-data-grid/npm/

**Lack of Migration Guides for Deprecated Packages**

We have also recently included a more direct and user-friendly section specifically for migration. This includes a codemode for major versions. You can find this section in the top left of the documentation menu. Here is the direct link for the latest guide (`v31`): https://ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-31/

**Absence of Framework-specific Examples**

We support examples for the following frameworks which can be adjusted from the top right of any documentation page: React, Vanilla JavaScript, Angular and Vue. Additionally where appropriate users can change between TypeScript vs JavaScript and modules vs packages directly in the examples themselves by clicking on "</> code". We currently support the following online code editors: plunker and codesandbox. All of our examples can be viewed in either of these by clicking their corresponding icons at the bottom right of the example.

**Getting started page**

Whilst on this topic, I'd like to add to your points above that we've also rewritten our Get Started guide which you can find here: https://ag-grid.com/javascript-data-grid/getting-started/.
We hope this will make the grid easier to learn and familiarise with for new users. Any feedback on this would also be highly appreciated.

I'll be closing this issue on GitHub as there is no immediate action to be taken by us however if you have any questions or comments on the above please feel free to share them with us. Once again, we appreciate your feedback and valuable views as a user.

Kind regards,
Zoheil
