### ISSUE TITLE
Support for event reasons as properties in stateUpdated event

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7525]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Similar to **filterChanged** Event having a property **afterDataChange** to indicate whether filter event was triggered due to data change.

**Expected behavior**
Putting a feature request to have a similar support of **sources** of events in **stateUpdated** event. This would give a flexibility to decide whether to do something only if the cause of event is an expected one e.g. here having cause as **afterdataChange** in stateUpdated event.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
31.0.3

* **Browser:**

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React

**Comment by AG-Zoheil** [comment]
Hi @melon2504,

Thanks for getting in touch. 

Can you clarify your requirement please? It seems like you'd like to know the type of source for a given `filterChanged` event - is that correct?

You can do this by utilizing the following: 

```
FilterChangedEventSourceType;
  // True if the filter was changed as a result of data changing
```

See the documentation here: https://ag-grid.com/react-data-grid/grid-events/#reference-filter-filterChanged.

I hope the above helps.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hello @melon2504,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-10598**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
