### ISSUE TITLE
valueFormatter does not work for boolean columns for any version after 29.3.5

### ISSUE THREAD

**Issue by a688** [ag-grid/ag-grid#7529]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/hVAa0bzuj7Q4i9Hk

**Current behavior**
Since v30, valueFormatters (for at least boolean columns) do not work properly. If you look at my sample link, you will see that I have 3 different versions of ag-grid linked in index.html. If you use version 30 or 31, the valueFormatter for the boolean column does NOT work and you end up with checkboxes instead of the text "Yes" or "No"

**Expected behavior**
If you comment out the v30 and v31 versions (and use v29.3.5) you will see the "IsDeleted" column correctly shows "Yes" or "No" for true/false.

* **AG Grid version:** 
30+

* **Language:** 
All? I noticed this in my plunker example AND in an Angular 17 project that I have.

**Comment by AG-Zoheil** [comment]
Hi @a688,

Please see our documentation regarding `cellDataTypes` which was introduce with `v30`: https://ag-grid.com/angular-data-grid/cell-data-types/

Kind regards,
Zoheil
