### ISSUE TITLE
Unable to dynamically resize grid vertically

### ISSUE THREAD

**Issue by perrottam** [ag-grid/ag-grid#7540]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
I have an angular electron app that uses AG grid to display a table with a list of files. I want the table to dynamically resize both horizontally and vertically, based on the electron window resizing. Currently, I can only get it to resize correctly horizontally by using `sizeColumnsToFit()` from the ColumnApi. It's possible I missed something when reading the documentation, however I was unable to find an example of auto resizing the table vertically.

**Expected behavior**
What I want to achieve is behavior similar to this demo: https://www.ag-grid.com/example/, where if we reduce the browser window height, the ag table also resizes (vertically) its height.

**Please tell us about your environment:**
OS: Windows 10
IDE: VS Code 1.84.2

* **AG Grid version:** X.X.X
ag-grid-community: 28.2.1
ag-grid-enterprise: 28.2.1
ag-grid-angular: 28.2.1

* **Browser:**
N/A, using electron framework for rendering.

* **Language:**
java 17
node 18.17.1
typescript: ^4.9.5
angular: ^15.1
electron: ^23.3.13

From looking at the documentation, I see examples for column (horizontal) resizing (https://www.ag-grid.com/angular-data-grid/column-sizing/), but nothing for row/vertical resizing. Am I missing something?

Perhaps you could point me to the code that's used for this demo? https://www.ag-grid.com/example/

Thank you so much in advance, any help would be much appreciated!

**Comment by AG-Zoheil** [comment]
Hi @perrottam,

Thanks for raising this on GitHub.

Our documentation [here](https://ag-grid.com/angular-data-grid/row-height/#auto-row-height) shows how to control row height/resizing.

You can also find the code for our demo page here: https://github.com/ag-grid/ag-grid/blob/latest/grid-packages/ag-grid-docs/documentation/src/mainPageDemo/Example.jsx.

I hope this helps.

Kind regards,
Zoheil
