### ISSUE TITLE
Rendering Issue in Microsoft Edge Beta Version(122.0.2385.8)

### ISSUE THREAD

**Issue by anuja-vendo** [ag-grid/ag-grid#7542]
#### Description:
We are encountering a rendering issue with ag-Grid Angular when using Microsoft Edge beta version 122.0.2385.8. The grid fails to render properly, and certain elements appear to be missing or misaligned.

#### Steps to Reproduce:
1. Utilize the ag-Grid Angular library in a project.
2. Open the project in Microsoft Edge beta version 122.0.2385.8.
3. Navigate to a page or component where the ag-Grid is implemented.
4. Observe the rendering issue.

### Note
The issue persists exclusively in Microsoft Edge beta version 122.0.2385.8. It's worth noting that ag-Grid Angular functions properly across all Chrome versions and Edge versions up to 121.0.2277.98.

#### Additional Information:
- Angular version: 12.2.0
- ag-Grid Community Version: 27.1.0
- ag-Grid Angular Version: 27.1.0
- Microsoft Edge beta version: 122.0.2385.8
- Operating System: Windows 11

**Screenshots:**
- ![Screenshot 1](https://github.com/ag-grid/ag-grid/assets/152368720/9d73455c-18b4-488f-8fb0-3002817eebea)
- ![Screenshot 2](https://github.com/ag-grid/ag-grid/assets/152368720/a39f0455-f0a4-4c8b-ab25-5fdf0a178ac9)
- ![Screenshot 3](https://github.com/ag-grid/ag-grid/assets/152368720/06b2b5f7-9266-405c-86a2-ca3fa45986d6)
- https://jam.dev/c/a7504590-e44f-45e6-ad03-044a31b56d95

We appreciate any assistance in resolving this matter. Thank you for your attention to this issue.

**Comment by AG-Zoheil** [comment]
Hi @anuja-vendo,

Thank you for raising this on GitHub.

Can we please ask you to open the following documentation on your Edge Beta version and report if you are seeing any rendering issues or if the example loads up fine? 

https://www.ag-grid.com/archive/27.1.0/angular-data-grid/row-sorting/#example-custom-sorting

Looking forward to hearing back from you.

Kind regards,
Zoheil

**Comment by rsrgithub** [comment]
@anuja-vendo 
This issue was NOT there in ag-grid ver 26.2.0 - [26.2.0](https://www.ag-grid.com/archive/26.2.0/angular-data-grid/row-sorting/#example-custom-sorting)
This issue existed in ag-grid version 27.0.0 - [27.0.0](https://www.ag-grid.com/archive/27.0.0/angular-data-grid/row-sorting/#example-custom-sorting)
Looks like this issue was fixed in version 28.1.0 - [28.1.0](https://www.ag-grid.com/archive/28.1.0/angular-data-grid/row-sorting/#example-custom-sorting)

**Comment by anuja-vendo** [comment]
Thank you for your response regarding the issue on GitHub.
