### ISSUE TITLE
filter not found

### ISSUE THREAD

**Issue by bkabhi** [ag-grid/ag-grid#7546]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

here [https://www.ag-grid.com/react-data-grid/filter-text/](url)

in this default case - filter not found
 console.warn('invalid filter type ' + filter);
 
```
const [columnDefs, setColumnDefs] = useState([
    {
        field: 'athlete',
        filter: 'agTextColumnFilter',
        filterParams: {
            textMatcher: ({ filterOption, value, filterText }) => {
                if (filterText == null) {
                    return false;
                }
                switch (filterOption) {
                    case 'contains':
                        return value.indexOf(filterText) >= 0;
                    case 'notContains':
                        return value.indexOf(filterText) < 0;
                    case 'equals':
                        return value === filterText;
                    case 'notEqual':
                        return value != filterText;
                    case 'startsWith':
                        return value.indexOf(filterText) === 0;
                    case 'endsWith':
                        const index = value.lastIndexOf(filterText);
                        return index >= 0 && index === (value.length - filterText.length);
                    default:
                        // should never happen
                        console.warn('invalid filter type ' + filter);
                        return false;
                }
            }
        }
    }
]);

<AgGridReact columnDefs={columnDefs} />
```

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
