### ISSUE TITLE
somtime the windows is crashing

### ISSUE THREAD

**Issue by Alkimay** [ag-grid/ag-grid#7550]
when i am loading ag grid, i am 1\20 times get crashed with this msg. even if there is an issue with my rendering i dont want the ag grid crash all the window...... just cancel this re render if it ovveride another one. why you crash my window/.

react-dom.production.min.js:216 Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.
    at t.getLockOnRefresh (ag-grid-community.auto.esm.js:37501:19)
    at t.redrawAfterModelUpdate (ag-grid-community.auto.esm.js:37449:14)
    at t.onPageLoaded (ag-grid-community.auto.esm.js:37352:14)
    at ag-grid-community.auto.esm.js:1254:17
    at Set.forEach (<anonymous>)
    at ag-grid-community.auto.esm.js:1249:77
    at e.dispatchToListeners (ag-grid-community.auto.esm.js:1260:13)
    at e.dispatchEvent (ag-grid-community.auto.esm.js:1230:14)
    at t.onModelUpdated (ag-grid-community.auto.esm.js:39066:27)
    at ag-grid-community.auto.esm.js:1254:17

**Comment by AG-Zoheil** [comment]
Hi @Alkimay,

Thanks for getting in touch.

Based on the limited information you've provided what seems to be happening here is that while you are asking the grid to perform an operation, the component it is being hosted by, decides that it needs to re-render, unfortunately the grid has no way to know how and when this will be completed, so it can only provide an error.
 
I would recommend inspecting the stack trace to identify what is causing this re-render, and see if there is any racing condition that could be prevented.

Kind regards,
Zoheil
