### ISSUE TITLE
Yarn install dependencies resolutions

### ISSUE THREAD

**Issue by ShiJuuRoku** [ag-grid/ag-grid#7553]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

- Want to use ag-grid with exact version 31.0.1
```
"@ag-grid-community/angular": "31.0.1",
"@ag-grid-community/client-side-row-model": "31.0.1",
"@ag-grid-community/core": "31.0.1",
 ```
`yarn install`

**Current behavior**
yarn resolve mulitple version of ag-grid, so it greatly increase the bundle size 
![image](https://github.com/ag-grid/ag-grid/assets/3122358/014acd4e-61ea-4639-80a9-055b83ec3908)

**Expected behavior**
Should resolve only the exact version wanted

**Please tell us about your environment:**
Angular 17
Yarn 4.1.0

* **AG Grid version:** 31.0.1

**Comment by ShiJuuRoku** [comment]
There is a workaround by specifying `resolutions` into the package.json

```
  "resolutions": {
    "@ag-grid-community/core": "31.0.1",
    "@ag-grid-enterprise/core": "31.0.1",
    "@ag-grid-community/csv-export": "31.0.1",
    "@ag-grid-enterprise/column-tool-panel": "31.0.1",
    "@ag-grid-enterprise/row-grouping": "31.0.1",
    "@ag-grid-enterprise/side-bar": "31.0.1"
  },
```

**Comment by AG-Zoheil** [comment]
Hi @ShiJuuRoku,

Thank you for submitting this on Github.

Using resolutions to force a specific version is the correct way to pin the versions. In our view this is in line with standard practices of libraries.

Kind regards,
Zoheil
