### ISSUE TITLE
event.key can be undefined

### ISSUE THREAD

**Issue by Tzvetomir-Kaydjiev** [ag-grid/ag-grid#7587]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hi,
by some reason selecting option from a list in a input tag with a mouse creates `keydown` event that doesn't contain `key` property.

```html
<div>
  <input type="string" list="input-id" onKeydown="console.log(event)"/>
  <datalist id="input-id">
    <option value=" --- empty --- "></option>
    <option value="Other">other</option>
  </datalist>
</div>
```

This causes an error

https://github.com/ag-grid/ag-grid/blob/c48f1313dc5dfa5cf4335d21822af546b93e160b/grid-community-modules/core/src/ts/utils/keyboard.ts#L23

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by Tzvetomir-Kaydjiev** [comment]
index.html
```html
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="render.css" />
    <script src="render.js"></script>
  </head>
  <body>
    <h1>Test</h1>
    <div id="test-div" style="height: 680px"></div>
  </body>
</html>
```
render.tsx
```tsx
import "ag-grid-community";
import "ag-grid-community/styles/ag-grid.css";
import { AgGridReact } from "ag-grid-react";
import React from "react";
import { createRoot } from "react-dom/client";

function TestCell() {
  return (
    <div>
      <input type="string" list="some-input-uuid" onKeyDown={console.log}/>
      <datalist id="some-input-uuid">
        <option value=" --- empty --- "></option>
        <option value="Other">other</option>
      </datalist>
    </div>
  );
}

function Test() {
  const [rowData, setRowData] = React.useState([{"name": "test"}]);

  const columnDefs = [
    {
      field: "name",
      cellEditor: TestCell,
      editable: true
    }
  ];

  return (
    <div style={{ width: "100%", height: "100%" }}>
      <AgGridReact
        rowData={rowData}
        columnDefs={columnDefs}
        reactiveCustomComponents
      />
    </div>
  );
}

function init() {
  const root = createRoot(document.getElementById("test-div")!);
  root.render(
    <React.StrictMode>
      <Test />
    </React.StrictMode>,
  );
}

window.onload = init;

```
build.sh
```sh
#!/bin/sh

case $1 in
    "clean")
        echo "cleaning..."
        rm -rf render.css render.js package-lock.json node_modules/
        ;;
    *)
        echo "building..."
        npx esbuild --bundle --jsx=transform --outdir=. render.tsx
        ;;
esac


```
package.json
```json
{
  "dependencies": {
    "ag-grid-community": "^31.0.2",
    "ag-grid-react": "^31.0.2",
    "esbuild": "^0.19.11",
    "http-server": "^14.1.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "prettier": "^3.2.4"
  }
}

```
To reproduce edit the test cell and select option from the dropdown.
 When creating this example I found out that the error occurs in Chrome and Electron, but it works in Firefox.

**Comment by AG-Zoheil** [comment]
Hi @Tzvetomir-Kaydjiev,

Thank you for your comment.

To enable us to efficiently look into your issue please fork the following plunker and adjust it to match your configuration to reproduce the issue you are reporting: https://plnkr.co/edit/JPo5B5G0bmdmkpch?open=main.js

Thank you!

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
