### ISSUE TITLE
[Question] Custom Row / Grouped Panel Row

### ISSUE THREAD

**Issue by sauravgaursmith** [ag-grid/ag-grid#7591]
How do I can display a complete row as a custom component ? I'm really sorry if being dumb here.

**Current behavior**
When I provided a custom group cell value component: This is rendered as a column cell value. 

**Expected behavior**
Custom component must span through a complete row. See the attached image:
![image](https://github.com/ag-grid/ag-grid/assets/25001992/bfd2625b-8f64-4e02-94a3-e567bf890208)

**Please tell us about your environment:**

* **AG Grid version:** 30.2.1

* **Browser:**: Chrome

* **Language:** Angular

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
