### ISSUE TITLE
[misc] Grid blinking two times after server sorting on header click

### ISSUE THREAD

**Issue by dhiegoatencio** [ag-grid/ag-grid#760]
Hello,

(Just for documentation, I'm copying the problem from the forum)

Grid configuration:

```
enableServerSideSorting: true,
angularCompileRows: true
```

and providing a datasource to do my sorting column on the server side.

The problem is, it is blinking my grid two times. The first time when I click (nothing is reordered because I'm doing server side sorting), and again when the data is returned by my server. I looked inside the grid source and founded this piece of code:

```
Grid.prototype.setDataSource = function (datasource) {
  ....
  else if (this.doingPagination) {
    ...
  }
  ....
  //because we just set the rowModel , need to update the gui
  this.rowRenderer.refreshView();
  ...
}
```

My code is entering inside this if and doing the refresh after that.
I mean, there is a way to do this server side sorting without this effect of blinking two times?

Thank you

**Comment by Raffahc** [comment]
Same problem here.

**Comment by ceolter** [comment]
which version of grid, can you confirm if this is happening with v4.x? i rewrote a LOT of code in v4

**Comment by Raffahc** [comment]
On the v4.0.2 the issues is still happening.
The columns that have a angular directive keep 'blinkning' when the header is clicked before doing the ordering.

**Comment by dhiegoatencio** [comment]
Hello @ceolter,  please see the issue bellow:
https://plnkr.co/edit/jVDT9I24pZCm12m4HK81?p=preview

On IE it's more expressive.

**Comment by ceolter** [comment]
isn't this an angular issue? i mean, it doesn't blink when not using angular, so it's to do with the angular compile cycle not working fast enough?

**Comment by harmjanluth** [comment]
When using a datasource with the pinning functionality (react grid) active (at lease one column pinned), after I click 'sort' the getRows gets called twice.. The more columns you pin the more the GetRows method is called (exponential).  Maybe that is related.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-111

**Comment by makinggoodsoftware** [comment]
Should be fixed now

**Comment by rajkamal-pits** [comment]
Hi, @ceolter
the same issue occurred while sorting with the limited no: of data and if the data is a huge set then no flickering(blinking effect) occurs.

Flicker issue refer link: https://output.jsbin.com/siqewuz

I couldn't create a jsbin for a large set of data.
I have used the same data which is referred to the below link. 
https://www.ag-grid.com/example-runner/vanilla.php?section=javascript-grid-sorting&example=sorting-api&generated=1&grid=%7B.

Please find the attached file for the large set of data. 
[Video_2017-12-19_151448.zip](https://github.com/ag-grid/ag-grid/files/1571123/Video_2017-12-19_151448.zip)

Thank You.!
