### ISSUE TITLE
Added .ag-checkbox-input-wrapper::before prevent from using checkbox component after b31.0.2

### ISSUE THREAD

**Issue by gustavomick** [ag-grid/ag-grid#7608]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
 
**Current behavior**
`suppressRowClickSelection = true`  in combination with `checkboxSelection = true` is adding a css 
`.ag-checkbox-input-wrapper::before` that is blocking checkbox clicking.

**Expected behavior**
same as in previous versions, allow to use ag checkbox

* **AG Grid version:** 31.0.3
```
    "ag-grid-angular": "^31.0.3",
    "ag-grid-community": "^31.0.3",
    "ag-grid-enterprise": "^31.0.3",
```

![image](https://github.com/ag-grid/ag-grid/assets/4327429/ce2ec284-a824-4927-8eb8-497762e7f38c)

**Comment by gustavomick** [comment]
@seanlandsman I did not have time to add an actual example but since seems you added the commit  may be you can chimein here? thanks!
https://github.com/ag-grid/ag-grid/blob/b3be0a3666055ee50e97b7be28b3cecdf15a3eab/grid-community-modules/all-modules/styles/_css-content.scss#L16313
fyi as temp workaround im forcing to `display:none` to this css but obviously not a healthy solution

**Comment by AG-Zoheil** [comment]
Hi @gustavomick,

I've attempted to reproduce your described behaviour of the checkbox being blocked from clicking but have been unable to do so.

Please view the below plunker, fork and adjust it to replicate the issue you are describing and send it back to us.

https://plnkr.co/edit/IBryDIzxwPCQXDQK?open=app.component.ts

Kind regards,
Zoheil

**Comment by gustavomick** [comment]
@AG-Zoheil sorry but i dont think i will have time for now to actually see why your case works are mine are not, likely a context issue. I just workarounded, if you think needs to be closed then is fine by me but just posting in case someone else can be affected with this, i assumed the originally developer could have seen this faster as is very specific addendum. in any case thanks have a good day.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
