### ISSUE TITLE
Have only first column with checkboxes and enable disabled checkboxes

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7609]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
We have a scenario where we want checkboxes for both cells and header to appear as part of only first column. For the same we have used logic of checking whether column is first in the callback of **headerCheckboxSelection** & **checkboxSelection** as per example in docs. But we also want few of the rows to be disabled as in checkboxes are disabled. We tried using **showDisabledCheckboxes:true** as per following e.g.

But issue occurs when we try to re-order the columns - where the checkboxes starts displaying for other columns

https://plnkr.co/edit/15cfuFMldhyWZOzE?open=index.jsx

**Expected behavior**
Have the disabled checkboxes appear only for first column i.e  a way where we can have both the feature of first column checkboxes and have them disabled based on some condition.

A suggestion, currently showDisabledCheckboxes is of type "boolean". We can have a callback function for showDisabledCheckboxes where the logic of isFirstColumn can be used.
e.g. 
![image](https://github.com/ag-grid/ag-grid/assets/77911765/24a036a3-82b3-4a47-8e2a-57e129f24735)

* **AG Grid version:** X.X.X
31.0.3

* **Browser:**
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React

**Comment by AG-Zoheil** [comment]
Hello @melon2504,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: AG-9484

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
