### ISSUE TITLE
automatic rowspan

### ISSUE THREAD

**Issue by casamia918** [ag-grid/ag-grid#7627]
<img width="1125" alt="스크린샷 2024-02-17 오전 10 45 24" src="https://github.com/ag-grid/ag-grid/assets/8295005/1e9cd8eb-7294-4e60-9c03-57252224d5ca">

https://github.com/casamia918/aggrid-rowspan

Please go to above repo page and read docs. 

I strongly recommend to clone the repo and run the code. 

-------

I don't know where to share & publish this repo. So I wrote this issue to share my repo.

At now, ag-grid support "rowspan" callback. But it's very restricted and hard to use at real application use cases.

So I made this.

**Comment by AG-Zoheil** [comment]
Thank you for sharing the above.

Please note we have this requirement in our backlog and we are tracking it with the following reference: **AG-4232**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

**Comment by jd-ffe-user01** [comment]
牛批
