### ISSUE TITLE
Customising AG Grid Cells with Multiple Properties and Icons

### ISSUE THREAD

**Issue by abindaz** [ag-grid/ag-grid#7629]
I am working on a project where we have a table similar to Google Spreadsheets using AG Grid. Each cell in the table receives multiple properties from the backend, as the values are validated on the server, resulting in either an error or a valid value.

**Requirements:**

Display cell values in red text if there's an error.

Place custom icon buttons on each cell for actions like retry, which will trigger API calls with the cell content.

**Example Data Structure:**
```
const rowData = [
  { property1: 'Value 1', property2: { status: 'SUCCESS', value: 'Some value', msg: 'Some message' }, /* ... other properties ... */ },
  // Add more rows as needed
];
```

**Current Implementation:**
```
const columnDefs = [
  { headerName: 'Property 1', field: 'property1' },
  {
    headerName: 'Property 2',
    field: 'property2',
    cellRenderer: 'customCellRenderer',
    valueSetter: customValueSetter,
  },
  // ... other columns ...
];

function customCellRenderer(params) {
  const { status, value, msg } = params.value;
  
    if (status === 'SUCCESS') {
        return `<input type="text" value="${value}" style="color: black;" data status="SUCCESS" />`;
      } else {
        return `<input type="text" value="${msg}" style="color: red; font-style: italic;" data-status="ERROR" />`;
  }
}

function customValueSetter(params) {
  // Handle value updates
  return true;
}
```

**Questions:**

How can I improve the cell rendering for error values, showing them in red text?

What's the best approach for adding custom icon buttons to cells, triggering API calls with cell content?

I appreciate any guidance or code examples on how to achieve these requirements efficiently. Thank you!

I have not even started with AG Grid. But I didn't even find any documentation that met my requirement.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
