### ISSUE TITLE
[export] Export to CSV all pages in Client side Pagination

### ISSUE THREAD

**Issue by scottsimock** [ag-grid/ag-grid#763]
I've implement the exportDataAsCsv function on a client side paginated grid. All rows are on the client but the csv only contains the rows in the current page. Is it possible to have a CsvExportParams property to export data beyond the current page. Ideal to retain filters and shown columns.

**Comment by ceolter** [comment]
that's not possible right now. maybe in the future.

**Comment by cinsin** [comment]
Client cached data should be able to export no matter it is in current page or not, please add this, thanks in advance!

**Comment by ceolter** [comment]
"Client cached data should be able to export no matter it is in current page or not" => for standard pagination, there is no client cache.

**Comment by mchlbrnd** [comment]
@ceolter any update whether and when this feature could land?

**Comment by ceolter** [comment]
nope, work not scheduled.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-112

**Comment by Elavarasanlee** [comment]
As a temporary Workaround:
We can set the pageSize of datasource to the `data.length`. This will allow the grid to display all the client side data in one go. Now export the data and reset the pageSize to it's original value. Set timeout of 100ms before resetting the pageSize, so as to retain all the data in the grid while export is still happening... 
**Note: I tested this workaround for 200+ odd data.**

**Comment by anangus** [comment]
Elavarasanlee, can you share that part of code? Thanks

**Comment by anangus** [comment]
I tried it and didn't work for me, can you share the code? Thanks

**Comment by mjurisic** [comment]
This has done the trick for me, HTH:

`let exportParams = {
    skipHeader: false,
    allColumns: true,
    fileName: 'export.csv'
};

this.gridOptions.api.setDatasource({
    getRows: (params) => {
        params.successCallback(this.rowData, this.rowData.length);
    }
});

let listener = () =>{
    this.gridOptions.api.exportDataAsCsv(exportParams);
    this.gridOptions.api.setDatasource(this.dataSource);
    this.gridOptions.api.removeEventListener('modelUpdated', listener)
};

this.gridOptions.api.addEventListener('modelUpdated', listener);`

**Comment by anangus** [comment]
Fantastic! Thank u so much.

**Comment by makinggoodsoftware** [comment]
Now If you are paginating and using the in memory row model, as is this case, it will export all the data, not just the current page

**Comment by ER-GAIBI** [comment]
I am applying a filter on ag-grid, the export csv file contains just filtered data, any way to export all data even a filter is applied ?
