### ISSUE TITLE
Tooltips on demo page broken

### ISSUE THREAD

**Issue by do-me** [ag-grid/ag-grid#7639]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The [tooltips on the demo page](https://www.ag-grid.com/javascript-data-grid/tooltips/?) are not working. Locally, they do work for me.

* **Browser:**
Chrome/Firefox. `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hi @do-me,

Thank you for raising this on GitHub. Can you please provide some more information as to what exactly isn't working for you?
Is it a specific example or is it all of them? I can see the tooltips from my side.

Please note we release version `31.1.0` today so you may need to clear your cache for the website to work without caching issues.

Looking forward to hearing back from you.

Kind regards,
Zoheil

**Comment by do-me** [comment]
Indeed, that seemed to fix it, sorry for the super short bug report and thanks for the immediate reply! Closing this issue. 

Also, as the tooltips take quite a while to pop up, I guess I was a little impatient. On my Chrome vesion linked above it takes like 2-3 seconds for the tooltip to display. Is this expected behavior?

**Comment by AG-Zoheil** [comment]
No problem!

Correct - the default is 2 seconds - see here in case you'd like to change this: https://www.ag-grid.com/javascript-data-grid/tooltips/?#tooltip-show-and-hide-delay
