### ISSUE TITLE
Applying a filter that results in no data returned and removing the filter results in the chart view still showing no data

### ISSUE THREAD

**Issue by igorkalezic** [ag-grid/ag-grid#7640]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- Have a grid whose data is supplied via RxJs Observables.
- Open chart view
- Apply a filter to those observables that results in no data returned
- Data in the chart disappears as expected
- Remove the filter to bring back data
- Chart is still empty. Expect the graphs to re-appear like the data in the grid re-appears

**Current behavior**
Chart graph doesn't re-appear when removing a filter that resulted in no data.

Investigation found that when no data is returned the data tool bar unchecks all the previous checked columns to display. When bringing the data back the columns are not re-checked. Workaround is to just open that data toolbar and re-check manually the columns you lost. Further investigation shows that the 'statusUpdated' event fires when the grid is filtered to no data. This doesn't seem intended since that event, theoretically, should only fire when grid status is changed, such as moving columns or sort behavior but not data changes.

**Expected behavior**
Chart returns just like the data in the actual grid returns

**Please tell us about your environment:**
Windows  using windows subsystem for linux, VSCode

* **AG Grid version:** X.X.X
31.0.0

* **Browser:**
Edge, Chrome, Firefox

Typescript ES6

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by ondrejkasik-inno** [comment]
Hi,
I face similar problem. Once I filter out all the rows shown in the grid, it is not possible to show any data after changing or removing the filter query, until i sort the grid - it solves the issue and relevant rows are visible again...

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
