### ISSUE TITLE
After registering setFilter module, ALL filters are automatically set to agSetColumnFilter regardless of column cell data type value

### ISSUE THREAD

**Issue by tkirda** [ag-grid/ag-grid#7641]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When using `AgGridSolid` all filters by default are inferred from column definition `cellDataType` property.

Grid is configured with following props:

```tsx
<AgGridSolid
    rowModelType="serverSide"
    defaultColDef={{
        filter: true
    }}
    // ... all other props has no relevance
/>
```

After registering setFilter module, ALL filters are automatically set to `agSetColumnFilter` regardless of column cell data type value.

```ts
import { SetFilterModule } from "@ag-grid-enterprise/set-filter";
import { ModuleRegistry } from "@ag-grid-community/core";

ModuleRegistry.registerModules([ServerSideRowModelModule, SetFilterModule]);
```

**Expected behavior**

Expected behavior is to apply `agSetColumnFilter` only when filter in column definition is explicitly set to `agSetColumnFilter`.

**Please tell us about your environment:**

* **Package manager:** NPM
* **Framework:** SolidJS
* **AG Grid version:** 31.1.0
* **Browser:** Can be reproduced in any supported browser.
* **Language:** TypeScript | ES6

**Comment by AG-Zoheil** [comment]
Hi @tkirda,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

If you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Regarding the issue/question above, the Set Filter is the default filter used in AG Grid Enterprise.
Please find more information here: https://ag-grid.com/javascript-data-grid/filter-set/#enabling-set-filters

Do let us know if you have any other questions.

Kind regards,
Zoheil
