### ISSUE TITLE
Deactivation of cell editing mode when changing the 'columnGroupShow' property.

### ISSUE THREAD

**Issue by ramiKang** [ag-grid/ag-grid#7643]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I have implemented a feature in AG Grid that utilizes the 'columnGroupShow' property for column grouping, allowing me to show or hide specific columns. However, I noticed that when editing a particular cell or an entire row, changing the 'columnGroupShow' property causes the edit mode to be deactivated.(Please refer to the video below for more information)

https://github.com/ag-grid/ag-grid/assets/108710196/1a4ae124-b8ac-454a-9437-10811e245a51

**Expected behavior**

Please make modifications so that changing the 'columnGroupShow' does not deactivate the edit mode for existing cells or rows.

**Please tell us about your environment:**

* **AG Grid version:** 31.0.2

* **Browser:** Chrome

* **Language:** [React| Javascript| ES6]

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-3848**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
