### ISSUE TITLE
The migration command to 31.1 is not working

### ISSUE THREAD

**Issue by sake12** [ag-grid/ag-grid#7646]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
The migration command from the docs does not work: `npx @ag-grid-community/cli@31.1 migrate`

**Current behavior**
```
npx @ag-grid-community/cli@31.1 migrate 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ag-grid-community/cli@31.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Expected behavior**
Migration to a new version should work on the day of release.

**Please tell us about your environment:**
npm 10.4 .0
os: windows

* **AG Grid version:** 31.1.0

* **Browser:**
n/a

* **Language:**
n/a

**Comment by AG-Zoheil** [comment]
Hi @sake12,

Thank you for raising this on GitHub.

We have not been able to get the codemod ready yet for the latest release. We anticipate this to be available at some point next week.

Apologies for the inconvenience.

Kind regards,
Zoheil
