### ISSUE TITLE
API Docs should indicate version when a method was introduced

### ISSUE THREAD

**Issue by awdorrin** [ag-grid/ag-grid#7650]
Not sure this is the right place to post this, but co-worker was trying to use the new getColumnFilterInstance method.
We are on 30.2.1, where this method does not exist.
Took way too long, searching through Github before we found this was introduced in v31.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-10830**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
