### ISSUE TITLE
How to hide row group on Ag-Grid after grouping data

### ISSUE THREAD

**Issue by pavelgronsky** [ag-grid/ag-grid#7654]
Hi. I use Ag grid for showing some data on table. 
So, we have **columnDef**

``` lang-js
const columnDef = [
        {
            field: 'colorName',
            rowGroup: true,
            hide: true,
            ....another props (renderer etc.)
        },
        {
            field: 'color',
            rowGroup: true,
            hide: true,
             ....another props (renderer etc.)
        },
        {
            field: 'titleName',
            rowGroup: true,
            hide: true,
             ....another props (renderer etc.)
        },
]

```
As you see, I try to group and hide the main 3 field in columnDefs.
We have some row data:

``` lang-js
const rowData = [
         {
        name: 'Name 1',
        titleName: 'Label',
        colorName: 'Color 1',
        color: '#FCE300',
    },
    {
        name: 'Name 1-1',
        titleName: 'Label',
        productName: 'Color 1',
        color: '#FCE300',
    },
    {
        name: 'Name 2',
        titleName: 'Label',
        colorName: 'Color 1',
        color: '#FFFFFF',
    },
    {
        name: 'Name 3',
        titleName: 'Label',
        colorName: 'Color 2',
        color: '#FFFFFF',
    },
]
```

The result is: 

![Screenshot 2024-02-23 at 17 22 53](https://github.com/ag-grid/ag-grid/assets/7213848/36e18d41-2ce1-48a4-8446-48e43f9adeae)

Question is: How I can leave **group data by this 3 fields** (colorName, color, titleName) but **hide one level group rows** from view. For example I need to hide **color** group row, but leave the grouping data by all 3 main fields.

* **AG Grid version:**26.2.0

* **Browser:**
Chrome (last version)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
