### ISSUE TITLE
AG Grid React Sparkline with Custom Point of Interest

### ISSUE THREAD

**Issue by nsaravanas** [ag-grid/ag-grid#7660]
I have been using ag-grid enterprise for a while, recently started exploring the sparkline feature with a point of interest.

Though its a great feature, it lacks one of my use cases, currently the point of interest supports highlighting min/max or negative/positive or first/last, but in my case I want to show a specific bar as an point of interest.

I had a look at the documentation below, the api doesn't support or provide a way to customize the point of interest.

`https://www.ag-grid.com/react-data-grid/sparklines-points-of-interest/`

any help would be greatly appreciated

Thanks

**Comment by AG-Zoheil** [comment]
Hi @nsaravanas,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered as this relates to an enterprise feature.

Kind regards,
Zoheil
