### ISSUE TITLE
The quick start example doesn't work with Next.js 14

### ISSUE THREAD

**Issue by w1z2g3** [ag-grid/ag-grid#7661]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The quick start example doesn't show the grid in a standard Next.js 14 app: https://www.ag-grid.com/react-data-grid/getting-started/

Just create a next.js app with default configurations and replace the page.tsx below can reproduce it. Please help to find the root cause and provide a solution. Want to use the latest Next.js with AG grid. Thank you!

**Expected behavior**
The grid will show.

**Please tell us about your environment:**
```
npx create-next-app@latest next-test

# page.tsx

"use client";

import { ColDef } from "ag-grid-community";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-quartz.css";
import { AgGridReact } from "ag-grid-react";
import React, { useState } from "react";
import { createRoot } from "react-dom/client";

// Row Data Interface
interface IRow {
  make: string;
  model: string;
  price: number;
  electric: boolean;
}

// Create new GridExample component
const GridExample = () => {
  // Row Data: The data to be displayed.
  const [rowData, setRowData] = useState<IRow[]>([
    { make: "Tesla", model: "Model Y", price: 64950, electric: true },
    { make: "Ford", model: "F-Series", price: 33850, electric: false },
    { make: "Toyota", model: "Corolla", price: 29600, electric: false },
    { make: "Mercedes", model: "EQA", price: 48890, electric: true },
    { make: "Fiat", model: "500", price: 15774, electric: false },
    { make: "Nissan", model: "Juke", price: 20675, electric: false },
  ]);

  // Column Definitions: Defines & controls grid columns.
  const [colDefs, setColDefs] = useState<ColDef<IRow>[]>([
    { field: "make" },
    { field: "model" },
    { field: "price" },
    { field: "electric" },
  ]);

  // Container: Defines the grid's theme & dimensions.
  return (
    <div
      className={"ag-theme-quartz"}
      style={{ width: "100%", height: "100%" }}
    >
      <AgGridReact rowData={rowData} columnDefs={colDefs} />
    </div>
  );
};

export default GridExample;
```

* **AG Grid version:**
^31.1.1

* **Browser:**

* **Language:** [TypeScript]

**Comment by AG-Zoheil** [comment]
Hi @w1z2g3,

Thank you for raising this on GitHub.

We have been unable to reproduce what you are reporting.

The current quick start works for us in a NextJS 14.1 project, with two minor tweaks:

- Need to add `use client` directive to the top of the page with the AG Grid component
- Need to replace the `document.createRoot` call with returning the grid component, e.g. export default `GridExample`

Both of these things are standard practices when using a React component in Next.

Kind regards,
Zoheil

**Comment by w1z2g3** [comment]
Thank you @AG-Zoheil for confirming it.

Just for the information of other frontend newbies, the problems is caused by:
```
style={{ width: "100%", height: "100%" }}
```

I replaced it with:
```
style={{ width: "800px", height: "600px" }}
```
and the grid shows up correctly.
