### ISSUE TITLE
v31.1 getModel() is deprecated but no replacement for getType() exists

### ISSUE THREAD

**Issue by nealeu** [ag-grid/ag-grid#7662]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

After upgrading to v31.1, we can see deprecations for `getModel()` but we cannot remove all references as no alternative exists for `getModel().getType()`, and there is no information about this in the [migration guide](https://ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-31-1/#grid-api)

**Comment by AG-Zoheil** [comment]
Hi @nealeu,

Thanks for raising this on GitHub.

We didn't provide an alternative in the migration guide as usually you would be the one providing the row model to the grid, so the expectation would be that you know if using CSRM, SSRM, etc. 
 
Anyway, it is possible you have a specific use case that may need this regardless.
For that we can suggest this approach:

As you know the type at the time the grid is created, you could do one of the following:

- Save it in an external store
- Set it into `context`
 
Alternatively, you can work it out from the various datasource properties:
```
if (api.getGridOption('datasource') != null) {
  return 'infinite';
} else if (api.getGridOption('serverSideDatasource') != null) {
  return 'serverSide';
} else if (api.getGridOption('viewportDatasource') != null) {
  return 'viewport';
} else {
  return 'clientSide';
}
```

I hope this helps.

Kind regards,
Zoheil

**Comment by nealeu** [comment]
Thanks.  That's great clarification for the whole community of users.

**Comment by AG-Zoheil** [comment]
Just to provide an update we have decided to add the below feature request into our backlog:

AG-11151 - [API] Add a new API method as a replacement for api.getModel().getType()
