### ISSUE TITLE
Add autoSizeToFit only to last column

### ISSUE THREAD

**Issue by ilzbergs** [ag-grid/ag-grid#7667]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

Hello. I'm using autoSizeColumns(), but after last column there is a "free" space, how to make that last column use all free space?
Can it be done something like : _last column uses sizeColumnsToFit() and rest columns autoSizeColumns()?_
![Capture](https://github.com/ag-grid/ag-grid/assets/85389433/7011d512-c568-4647-a2cd-1a9d6c09ae23)

**Comment by AG-Zoheil** [comment]
Hello,

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-9704**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
