### ISSUE TITLE
Chromium browser shrinks grid height after load when zoom is not 100%

### ISSUE THREAD

**Issue by melaniesavas** [ag-grid/ag-grid#7668]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.

I have a grid where the height is calculated using the viewport height to avoid scrolling.

The grid has 16 rows. OnGridReady calls this following method to avoid lots of whitespace when there are a small amount of row entries:

  setGridHeight() {   
    setTimeout(() => {
      if(this.totalPages < 2) {
        this.gridApi?.setDomLayout('autoHeight');
        (document.querySelector<HTMLElement>('#myGrid')! as any).style.height = '';
      }
      else {
        this.gridApi?.setDomLayout('normal');
      }
    }, 300); 
  }

Expected behaviour, the grid shrinks to the height of all my 16 rows which fit on 1 page, The grid is a 1 page grid.

**Current behavior**
If my browser is set to a zoom level OTHER THAN 100% (so 90%, 110% etc):
For a split second, the expected behaviour happens but then the grid is reduced further to 15 rows and the last row is pushed to a second page. If I put it on a smaller screen it will reduce the rows by a similar percentage.
This also happens if I have it at 100% (which shows all 16 rows as it behaves correctly) and then I select a different zoom.

**Expected behavior**
It should not be recalculated to 15 rows. There is plenty of space for 16 rows. Something the browser is doing is interfering with the grid after all my code has been executed, and recalculating it - but the problem happens if I go bigger OR smaller.

**Please tell us about your environment:**
This happens on Chromium (chrome and ie). 
It DOES not happen on Firefox. Firefox is fine.

I have tried setting the height to a % value on the grid as well as on the containing div too. Nothing works. 

* **AG Grid version:** X.X.X
Angular CLI: 16.2.8
Node: 18.19.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.8
@angular-devkit/build-angular   16.2.8
@angular-devkit/core            16.2.8
@angular-devkit/schematics      16.2.8
@angular/cdk                    16.2.10
@angular/cli                    16.2.8
@angular/material               16.2.10
@schematics/angular             16.2.8
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3

* **Browser:**
Chrome, ie

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for raising this on GitHub.

Currently scaling/zooming is not supported and there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-2550**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
