### ISSUE TITLE
Codemod not applying the changes for version 31.0

### ISSUE THREAD

**Issue by ibm-murthy** [ag-grid/ag-grid#7670]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
I'm using Ag Grid as a dependency in my react projects.
In the component library, I have updated ag grid packages to 31.0.0 and then ran the following command as per docs
npx @ag-grid-community/cli@31.0 migrate
https://www.ag-grid.com/react-data-grid/upgrading-to-ag-grid-31/#codemods

It processed all the files but didn't make any changes to files with Ag Grid code.
<img width="490" alt="ag-grid-issue" src="https://github.com/ag-grid/ag-grid/assets/161761739/8a688ad0-7ce0-4ebd-a3d0-a3d3fc88c2bf">

**Please tell us about your environment:**

* **AG Grid version: 31.0

* **Browser: n/a

* **Language:[all | TypeScript X.X | ES6/7 | ES5]
React 18.2.0 + TypeScript 5.0.4

**Comment by AG-Zoheil** [comment]
Hi @ibm-murthy,

Thanks for raising this on GitHub.

The codemod only transforms source files that use deprecated features from the [breaking changes in the v31 release](https://www.ag-grid.com/react-data-grid/upgrading-to-ag-grid-31/#breaking-changes), so if you aren't currently making use of any of those APIs your source code will be unaffected by the codemod.

If there is some source code that you would have expected to be transformed by the codemod, but it was not, please paste that specific section here and we can have a further look.

Kind regards,
Zoheil
