### ISSUE TITLE
Allow optionally excluding/including state properties

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#7679]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
For instance, I don't want to save/persist information related to the scroll position in state.
In the following example, I have added a condition  to save the state only if the source of the event is not `scroll`.  Unless I manually code and filter out only required state properties and exclude others, doing some other action would get the state containing scroll related info too.

https://plnkr.co/edit/KpWKO5nzjWlg7rvy?open=index.tsx

**Expected behavior**
It would be great if Ag Grid directly provides some kind of feature that handles optional inclusion & exclusion of required properties. 
Though there is something similar stated in the docs, I'm not sure whether this can be achieved directly.
https://www.ag-grid.com/react-data-grid/grid-state/#state-contents

![image](https://github.com/ag-grid/ag-grid/assets/77911765/0826212c-0001-4dce-bf97-8e8bf05b9df1)

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
31.1.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by AG-Zoheil** [comment]
Hi @melon2504,

Thank you for getting in touch.

You would need to include/exclude them via manipulating your code.
You can see an example of this based on excluding scroll here: https://plnkr.co/edit/Uqcydu2aTYMKL43c?open=main.js

We will not be looking to add any further properties to this at this point.

Kind regards,
Zoheil
