### ISSUE TITLE
Serverside loading with tanstack query Caching Data  

### ISSUE THREAD

**Issue by mohitEsb-github** [ag-grid/ag-grid#7684]
**Current Behavior**
 Currently I'm using tanstack query for caching data for ag-grid server side table with infinite scroll. I'm cache data according to the pages and i'll get cache data also in serverside data source but not able to hide the loader of table manually. I'm trying to hide loader using gridApi but its showing blank white screen and hide the loader.
 
 **Expected Behavior**
 Whenever I get cache data from query and set to params.success then wants to hide the loader or hide the loader manually while serverside api calling

**AG-Grid Version**
ag-grid: 30.2.0

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
