### ISSUE TITLE
My column is not resizing on first render using api.autoSizeColumns and api.sizeColumnsToFit

### ISSUE THREAD

**Issue by msetodev** [ag-grid/ag-grid#7690]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When I refresh my page after the code change or run npm start, the column I have specified to auto resize given how long the data is in that column on the row is not automatically resizing to fit the contents

**Expected behavior**
I expected the column to auto resize on first render depending on how long the data is

**Please tell us about your environment:**
VS Code running on Windows 11
Node v16.20.2
React 18.2.0
"@ag-grid-community/all-modules": "^27.3.0",
"@ag-grid-community/client-side-row-model": "~31.1.1",
"@ag-grid-community/core": "^31.1.1",
"@ag-grid-community/react": "^31.1.1",
"@ag-grid-community/styles": "^31.1.1",

* **AG Grid version:** 31.1.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

My code:

const gridOptions = {
    pagination: true,
    domLayout: 'autoHeight',
    defaultColDef: { resizable: true },
    getRowHeight: () => 40,
  };

  const onGridReady = (params) => {
    const api = params.api;
  
    // Auto resize the 'name' column to fit the content
    api.autoSizeColumns(['name']);
  
    // Resize columns to fit the grid width
    api.sizeColumnsToFit();
  };
      <div className={"ag-theme-quartz"} style={{ width: '100%', height: '100%', backgroundColor: 'transparent' }}>
        <AgGridReact
          rowData={users}
          columnDefs={columnDefs}
          gridOptions={gridOptions}
          onGridReady={onGridReady} // Attach the onGridReady callback
        />
      </div>

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by msetodev** [comment]
I got it working.

**Comment by ottosson** [comment]
@msetodev How did you solve it? Having similar issue...
