### ISSUE TITLE
Proposal to improve bundle size by using SWC minifier

### ISSUE THREAD

**Issue by SalvatorePreviti** [ag-grid/ag-grid#7694]
I noticed that currently the minifier used in the build step is based on esbuild, that is extremely fast but has some limitations in terms of minification.

Since the project is already using swc, would be extremely simple to add a step in the post build minification plugin defined in esbuild.config.cjs to use swc to minify the output further.
Swc minification is intended to be a faster replacement for terser (written in JS)
I did not try to run tests or the code and just wanted to check if there is an interest in this feature before eventually submitting a pull request.

Some results, in bytes:

ag-grid-react esm, esbuild: 48266, esbuild+swc: 47413
ag-grid-react cjs, esbuild: 63908, esbuild+swc: 50826 
main.cjs.min.js, esbuild: 1000576, esbuild+swc: 919345
main.esm.min.mjs, esbuild: 926430, esbuild+swc: 918879
column tool panel, esbuild: 51577, esbuild+swc: 46224
clipboard, esbuild: 17113, esbuild+swc: 16882
row-grouping esm, esbuild: 66159, esbuild+swc: 65485

Whilst the reduction is not extreme, I believe the simplicity of the change required justify the addition of SWC.

Possible changes in esbuild.config.cjs:
Note I am adding the option to inline the source map in esbuld so they can be read by swc.

```ts
const { minify } = require('@swc/core');

...

                if (outputFile.endsWith('.map')) return;

                writeState.get(outputFile)?.abort();
                const abortController = new AbortController();
                writeState.set(outputFile, abortController);

                const { signal } = abortController;

                const contents = await fs.readFile(path.resolve(outputFile), 'utf-8');

                if (signal.aborted) return;
                const minified = await esbuild.transform(contents, {
                    minify: true,
                    sourcemap: 'inline',
                });

                const { name, ext } = path.parse(outputFile);

                // Use SWC to minify further the code
                const swcMinified = await minify(minified.code, {
                    ecma: 2017,
                    module: true,
                    toplevel: true,
                    compress: true,
                    mangle: true,
                    sourceMap: true,
                });

                if (signal.aborted) return;
                const minifiedFile = path.resolve(path.dirname(outputFile), `${name}.min${ext}`);
                await Promise.all([
                    fs.writeFile(minifiedFile, swcMinified.code, { signal }),
                    fs.writeFile(`${minifiedFile}.map`, swcMinified.map, { signal }),
                ]);
```

**Comment by StephenCooper** [comment]
Hi @SalvatorePreviti,

Thank you for this suggestion. We are interested in this change especially if it reduces bundle size without additional effort via code changes.

I have linked to our existing tickets internal AG-8725, AG-8840 so that we can evaluate this further.
