### ISSUE TITLE
Pivot Chart API Cannot Format Combochart Series

### ISSUE THREAD

**Issue by nickcleveland** [ag-grid/ag-grid#7696]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Creating a pivot chart [via the API](https://www.ag-grid.com/react-data-grid/integrated-charts-api-pivot-chart/) does not allow you to pass a "seriesChartTypes" object, despite the fact that "customCombo" is a valid chart type. There is no way to format each series when using the "customCombo" chart type. Each series defaults to a line chart. The [range chart api](https://www.ag-grid.com/react-data-grid/integrated-charts-api-range-chart/#range-chart-api) by contrast, allows you to format each series in a combo chart.

**Expected behavior**
I can create a pivot chart via the api and pass a "seriesChartTypes" object to format each series on my chart rather than each series defaulting to line charts.

**Please tell us about your environment:**

OS: Windows
IDE: Pycharm
Package manager: NPM

* **AG Grid version:** 
"ag-grid-enterprise": "^31.1.1",
    "ag-grid-react": "^31.1.1"

* **Browser:**
Chrome

* **Language:** 
Typescript 5.3.3

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-8319**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
