### ISSUE TITLE
How to Group column and show data of child but not parent upon expand and not just empty lines.

### ISSUE THREAD

**Issue by praveenkumar91** [ag-grid/ag-grid#7697]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by praveenkumar91** [comment]
You can find the example what I am trying to do in **NonModal.txt** file.

[NonModal.txt](https://github.com/ag-grid/ag-grid/files/14516160/NonModal.txt)

When I use _groupDisplayType: 'groupRows',_ it make the group column as whole row rather than just column 
![image](https://github.com/ag-grid/ag-grid/assets/16646461/2ce3df2f-bb86-4f9d-985a-e97bcd8d9cc0)

and when use _groupDisplayType: 'custom',_  , then its correct but then its in separate column rather than below the expanded group
![image](https://github.com/ag-grid/ag-grid/assets/16646461/777cafef-19d8-43b1-96fa-fe8455d80383)

**Comment by AG-Zoheil** [comment]
Hi @praveenkumar91,

Thanks for getting in touch.

It looks like this example addresses the way you'd like to display your row groups: https://ag-grid.com/react-data-grid/grouping-custom-group-columns/#custom-grouping-hidden-parents.

I hope this helps.

Kind regards,
Zoheil

**Comment by praveenkumar91** [comment]
I tried with leaf node showing .

But this always put the autoGroupColumnDef in the front. I want to put it say at 5 position and dont allow it to moveable by using the suppressMovable: true,

**Comment by praveenkumar91** [comment]
To do so I use 

params.columnApi.moveColumn('ag-Grid-AutoColumn', props.autoGridColumnnIndex);

But this shows that the column is getting move when u open the ag grid in non modal window.
