### ISSUE TITLE
Hierarchy Data View From Bottom-To-Top In ag-Grid

### ISSUE THREAD

**Issue by Maddy-O** [ag-grid/ag-grid#7703]
Inquire about the hierarchical data view functionality in ag-Grid. Specifically, I am interested in whether ag-Grid supports a hierarchy data view from bottom to top.

Attached to this issue are two screenshots for reference. The first screenshot depicts our current hierarchy data view, which is structured from top to bottom. The second screenshot illustrates the desired hierarchy data view that we aim to achieve, organized from bottom to top.

SS1: Top-to-Bottom hierarchy
![top-to-bottom](https://github.com/ag-grid/ag-grid/assets/95930594/e7bc957f-08e5-4839-bf29-ba383ff1ac12)

SS2: Bottom-to-Top hierarchy
![bottom-to-top](https://github.com/ag-grid/ag-grid/assets/95930594/9b81dfb5-6e1a-4d24-8195-0f6c25216d49)

Could you please confirm whether ag-Grid supports such a hierarchical data view? If so, I would greatly appreciate any guidance or instructions on how to implement this feature effectively.

**Comment by AG-Zoheil** [comment]
Hello @Maddy-O,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-3791**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
