### ISSUE TITLE
Ag-grid not showing any data.

### ISSUE THREAD

**Issue by Atreya-112** [ag-grid/ag-grid#7708]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Steps to reproduce**
1.) Install angular on your device.
2.) Create a new angular app with "ng new App-Name --defaults" .
3.) Move into the app directory and do : "npm install ag-grid-angular"
4.) Put this in your app.component.ts :

import { Component } from '@angular/core';
import { AgGridAngular, ICellRendererAngularComp } from 'ag-grid-angular';
import {
  ColDef,
  ICellRendererParams,
  ValueGetterParams,
} from 'ag-grid-community';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-quartz.css';

// NOTE: Angular CLI does not support component CSS imports: angular-cli/issues/23273

@Component({
  standalone: true,
  template: `<button (click)="buttonClicked()">Push Me!</button>`,
})
export class CustomButtonComponent implements ICellRendererAngularComp {
  agInit(params: ICellRendererParams): void {}
  refresh(params: ICellRendererParams) {
    return true;
  }
  buttonClicked() {
    alert('clicked');
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AgGridAngular],
  template: ` <ag-grid-angular
    style="width: 100%; height: 100%;"
    [rowData]="rowData"
    [columnDefs]="columnDefs"
    [class]="themeClass"
  ></ag-grid-angular>`,
})
export class AppComponent {
  public rowData: any[] | null = [
    { make: 'Tesla', model: 'Model Y', price: 64950, electric: true },
    { make: 'Ford', model: 'F-Series', price: 33850, electric: false },
    { make: 'Toyota', model: 'Corolla', price: 29600, electric: false },
    { make: 'Mercedes', model: 'EQA', price: 48890, electric: true },
    { make: 'Fiat', model: '500', price: 15774, electric: false },
    { make: 'Nissan', model: 'Juke', price: 20675, electric: false },
  ];
  public columnDefs: ColDef[] = [
    {
      headerName: 'Make & Model',
      valueGetter: (p: ValueGetterParams) => p.data.make + ' ' + p.data.model,
      flex: 2,
    },
    {
      field: 'price',
      valueFormatter: (p) => '£' + Math.floor(p.value).toLocaleString(),
      flex: 1,
    },
    { field: 'electric', flex: 1 },
    { field: 'button', cellRenderer: CustomButtonComponent, flex: 1 },
  ];
  public themeClass: string = 'ag-theme-quartz';
}

const gridDiv = document.querySelector<HTMLElement>('#myGrid')!; 

**************************************************************************************

and add this in your main.ts :

import '@angular/compiler';
import { enableProdMode } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';

if ((window as any).ENABLE_PROD_MODE) {
  enableProdMode();
}

bootstrapApplication(AppComponent); 

5.) Save and do "npm run start".

**Current behavior**
No data is shown on the browser screen on any browser.

![ag-grid](https://github.com/ag-grid/ag-grid/assets/76204247/f16d6f9c-f872-48fc-bb9f-8222c7a87bb2)

**Expected behavior**
Should work and show the grid after opening browser. Like this :

![ag grid 2](https://github.com/ag-grid/ag-grid/assets/76204247/78d37cf7-0b02-4ce5-9e48-a4a25c73e801)

**Please tell us about your environment:**
Angular CLI: 17.1.0
Node: 20.11.0
Package Manager: npm 10.5.0
OS: win32 x64

* **AG Grid version:**  *

"ag-grid-angular": "^31.1.1",
"ag-grid-community": "^31.1.1",
"ag-grid-enterprise": "^31.1.1",

* **All code was inside app.component.ts and main.ts was taken from https://www.ag-grid.com/angular-data-grid/getting-started/#example** *

**Comment by kevinlee2198** [comment]
There was a similar problem in [this issue](https://github.com/ag-grid/ag-grid/issues/7661). Try changing `style="width: 100%; height: 100%;"` from percents to pixels - i.e. `style="width: 800px; height: 500px"` and see if that displays the grid.

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by JanDoeTian** [comment]
> Thank you for submitting this on Github.
> 
> As this has been open without any further interaction for a while, I will be closing this issue.
> 
> If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
> 
> Kind regards, Zoheil

Hi Zoheil,

Could you provide a reason as to why setting pixel height eg. 500px works, but percentage height eg. 100% does not work? This comes from the documentations on your website, and I'm really surprised to find out that 100% is not working....

**Comment by rfrancois** [comment]
Hi,

I just tried Ag Grid and I had the same issue. I just wanted to say the problem was still here, and I think I won't use this library because it seems really strange to me to set a random pixel height as a workaround.

**Comment by StephenCooper** [comment]
@rfrancois This behaviour is covered in our documentation here: https://ag-grid.com/angular-data-grid/grid-size/

> If using % for your height, then make sure the container you are putting the grid into also has height specified, as the browser will fit the div according to a percentage of the parent's height, and if the parent has no height, then this % will always be zero.

**Comment by AG-Zoheil** [comment]
To clarify further:

In HTML, if you create an element with 100% height, then it will be 100% of the height of its parent. If the parent doesn't have an explicit height set, that height will be zero. This is just how HTML works.

However we agree AG Grid can improve its handling of this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-15339**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
