### ISSUE TITLE
RowContainerComp's rowCtrlsOrdered value is error

### ISSUE THREAD

**Issue by Shen120** [ag-grid/ag-grid#7709]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

Current behaviour.
[souce code](https://github.com/ag-grid/ag-grid/blob/0511a4fcbd5cfaffce4dec03b66a1831a52df796/packages/ag-grid-react/src/reactUi/rows/rowContainerComp.tsx#L105)
![image](https://github.com/ag-grid/ag-grid/assets/33613409/387b9351-ca94-4aa9-8823-673510683cce)
rowCtrlsOrdered is supposed to be an array, but running it results in an Object, which causes a rendering error

**Current behavior**

**Expected behavior**
rowCtrlsOrdered's value shoud be a Array, and not a Object

**Please tell us about your environment:**

Windows 10@latest/ webpack v5@latest (not CRA) /react 17.0.2/

* **AG Grid version:** 31.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

* **Language:** ES6

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
