### ISSUE TITLE
How to enable default column filters and menu icon for filtering data when I use a custom header component?

### ISSUE THREAD

**Issue by AksheyThakur1496** [ag-grid/ag-grid#7711]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
