### ISSUE TITLE
Server-Side Row model: How to scroll to an index that not yet rendered with Row Grouping?

### ISSUE THREAD

**Issue by pavel-shermayster-sage** [ag-grid/ag-grid#7712]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
If is a way to scroll to an index that is not yet rendered/fetched by ag-grid? Without Row grouping it worked well, but with Row Grouping it print an error: `Invalid row index for ensureIndexVisible:`.
I put a demo here, you can enter an index and submit it should scroll to the index you entered.
[Plunker](https://plnkr.co/edit/Vd4T5V4VY4ZbY3nI?open=index.jsx)

**Comment by AG-Zoheil** [comment]
Hello,

The following documentation should provide guidance surrounding this: https://ag-grid.com/react-data-grid/server-side-model-configuration/#initial-scroll-position.

Please also see this example which has `rowGroup: true` and uses `ensureIndexVisible` to scroll to a specified position.
https://plnkr.co/edit/ENSUQHsFmcZOzidp?open=index.jsx

I hope this helps!

Kind regards,
Zoheil

**Comment by pavel-shermayster-sage** [comment]
@AG-Zoheil thank you for the response. Unfortunately, the problem is still exists in the example you provided. When you try to scroll to an index after initial scroll, ag grid will print an error. You can see recording here: https://share.zight.com/yAuBekP0
Planker based on your example: https://plnkr.co/edit/ztpMUIiPHEsIKCP1?open=index.jsx

**Comment by AG-Zoheil** [comment]
Hi @pavel-shermayster-sage,

We've had a look at this and the issue is that you're providing a string instead of a number.
See this working here: https://plnkr.co/edit/ZSfWbmqh8GI3JlTS?open=index.jsx

Kind regards,
Zoheil
