### ISSUE TITLE
Roll-up data when columns are hidden

### ISSUE THREAD

**Issue by hkutcher2** [ag-grid/ag-grid#7715]
Scenario: say you have the following table…
```
| Person          | Pet             |
-------------------------------------
| Gabe            | Snowball        |
| Gabe            | Snowflake       |
| Hanna           | Midnight        |
| Hanna           | Violet          |
-------------------------------------
```

If I hide or group by the Pet column, I would expect the person column to “roll-up”.
I want it to look like this.
```
| Person          |
-------------------
| Gabe            |
| Hanna           |
-------------------
```

But currently (in my prototype), it would look like this.
```
| Person          |
-------------------
| Gabe            |
| Gabe            |
| Hanna           |
| Hanna           |
-------------------
```

Can it be made to behave as desired?

Here's a CodeSandbox. https://5xq8m6.csb.app/

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
