### ISSUE TITLE
esLint - JS Implantation -  error 'agGrid' is not defined 

### ISSUE THREAD

**Issue by erickbrenes** [ag-grid/ag-grid#7721]
[x] bug report

**Providing a Reproducible Scenario**
Setup a AG-Grid JS implementation project with the started code: 
https://www.ag-grid.com/javascript-data-grid/getting-started/
https://plnkr.co/edit/HTHhMfJhSc6xq3zj?open=main.js&preview

Run eslint with defaults or at least `no-undef` on against the AG-Grid started code.

**Current behavior**
Causes an error of `'agGrid' is not defined`.  Without adding the `/* eslint-disable no-undef */ `around `gridApi = agGrid.createGrid(document.querySelector('#myGrid'), gridOptions); `

**Expected behavior**
No warnings - agGrid to be defined.

Might seem stupid, but is there a way to fix the warning with a **vanilla js** implementation.

![Screenshot 2024-05-20 at 12 37 04 PM](https://github.com/ag-grid/ag-grid/assets/16210538/9bcd80a4-2f8c-4b7a-bbf9-838a594076ba)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by erickbrenes** [comment]
@AG-Zoheil why is this closed?   There isn't any further information for me to supply or action.  I was hoping there would be a solution presented for the esLint error.

**Comment by AG-Zoheil** [comment]
Hi @erickbrenes,

Apologies, it must've been incorrectly tagged previously. I'll reopen now, however can you please make sure you **fork & save** your plunker example and share as the supplied plunker above is empty.

Many thanks!

**Comment by AG-Zoheil** [comment]
Hi @erickbrenes, reminder to please provide a plunker that has been **forked & saved** if you'd like us to look at this as the one supplied in your original comment is empty.

**Comment by erickbrenes** [comment]
@AG-Zoheil updated the initial comment to reflect the issue.  Basically if you take the started JS code on the AG grid site under quick start and use ESLint... you get the described error.

**Comment by StephenCooper** [comment]
Please see the globals configuration option for eslint which can be applied to `agGrid`

https://eslint.org/docs/latest/use/configure/language-options#specifying-globals
