### ISSUE TITLE
SSRM Refresh

### ISSUE THREAD

**Issue by jpsla94** [ag-grid/ag-grid#7737]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
When using server side refresh, is it possible to use refresh to refresh top level rows and child group rows all at the same time? This is not clear in documentation. I required this feature to update my grid without purging all the rows.

**Please tell us about your environment:**

* **AG Grid version:** 31.0.3

* **Browser:** chrome 122.0.6261.112

* **Language:** TypeScript 5.3.3

**Comment by AG-Zoheil** [comment]
Hi @jpsla94,

Thank you for submitting this on Github.

As SSRM is an enterprise feature I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions if you are an enterprise client. That would be the quickest and most efficient route for you to get your question answered.

If you are not an enterprise client what we can advise regarding the issue/question above is to use the following. This is based on the assumption that you'd like to do a recursive refresh of all rows.

```
gridApi.forEachNode(node => {
   if (node.group) {
      gridApi.refreshServerSide({ route: node.getRoute() });
   }
});

```
If you need more support with this please raise an issue via our support portal or email info@ag-grid.com if you'd like to discuss becoming an enterprise user. Find out more about AG Grid enterprise [here](https://ag-grid.com/angular-data-grid/licensing/).

Kind regards,
Zoheil

**Comment by jpsla94** [comment]
Hello @AG-Zoheil,

Thank you for your reply. But unfortunately your tip still does not allow me to refresh the grip correctly after I ungroup a child from the group. It does not the refresh the group to show the child removed. Just duplicates the row somehow. And then refresh the top level rows to show the ungrouped child. By the way, I am using server side transactions do this. Is this due to an supported grid operation? Because none of your demos shows such operation.
