### ISSUE TITLE
AG Grid - Sorting and pagination together

### ISSUE THREAD

**Issue by WebTerminator** [ag-grid/ag-grid#7741]
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using pagination and sorting together, if I select a page front the pagination selector and you sort one of the columns all of the data is sorted instead of just the items being visible in selected page and it looks really odd from a UX perspective. 

Example here => https://codesandbox.io/p/sandbox/ag-grid-packages-wn8slp?file=%2Findex.html

**Expected behavior**
Only visible items should be sorted

**Comment by AG-Zoheil** [comment]
Hi @WebTerminator,

Thanks for getting in touch via GitHub.

We are currently not considering feature requests via GitHub and we do not believe there is an underlying issue with this feature from a UX perspective.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
