### ISSUE TITLE
Set a max-height for the filter list, class being ag-set-filter-list 

### ISSUE THREAD

**Issue by cb911nr** [ag-grid/ag-grid#7742]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Setting a max height for the scroll bar of ag-set-filter-list?**

I am trying to somehow set the height to be a max-height of like 150px, so that when the set filter list is smaller than that, there's no scrollbar/a set height. It just looks better to have a max-height over the explicit height.

I am having difficulties trying to find out a way to do this, setting height: auto and max-height doesn't work.

Was hoping someone would know?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
