### ISSUE TITLE
How to maintain row editing when clicking on another cell or row.

### ISSUE THREAD

**Issue by andyFang94** [ag-grid/ag-grid#7752]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**config
```
editType: 'fullRow',
suppressClickEdit: false

Double-click to edit  cell or row.
```

**Current behavior**
The grid stops editing when the user clicks on another cell or row.

**Expected behavior**
The grid should continue editing even when the user clicks on another cell or row.

* **ag-grid-community ^31.0.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-3848**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
