### ISSUE TITLE
Ag-grid date filter format is considering the System/browser date format. Can we override it?

### ISSUE THREAD

**Issue by Lokeshsadala** [ag-grid/ag-grid#7753]
![ag-grid-date-format](https://github.com/ag-grid/ag-grid/assets/38320801/98efe996-2a53-4481-9d76-64d12135f113)

**Description of the Issue:**
When using the date filter in ag-Grid, the filter format appears to be influenced by the system or browser date format settings. This behavior is problematic, especially when the date format displayed in the column differs from the system date format.

**Expected Behavior:**
Ideally, the date filter format should be independent of the system or browser settings and should adhere to the format specified for the data displayed in the column.

**Request for Assistance:**
We kindly request your guidance on whether there is any way to override this behavior and enforce a consistent date filter format that aligns with the format specified for the column data. We understand that ag-Grid provides extensive customization options, and we would appreciate any insights or recommendations on how to achieve this.

---------------------------------------------------------------------------------------------------------------------------------------------------

_Additional Information:
We have explored options such as creating a custom date filter component and specifying a custom comparator function. While these approaches offer some level of customization, they do not fully address the issue of overriding the default behavior of the date filter format.

Our application heavily relies on ag-Grid for data presentation and filtering functionalities, and ensuring consistency in date formatting is crucial for a seamless user experience.

We are eager to hear your insights and recommendations on how to resolve this issue. Your assistance in addressing this matter would be greatly appreciated._

Thank you for your attention to this matter, and we look forward to your response.

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for the suggestion.

We agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-3735**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

**In the meantime** please view the following suggested workaround that may suit your requirement:

There is a workaround to use a custom date format, but to do so you will need to implement your own Date Component - https://ag-grid.com/archive/31.1.0/javascript-data-grid/component-date/ . There is an example shown on this page that uses the third-party flatpickr library, which allows for you to do this.
 
Here's a Plunker set up that way with a date format configured - https://plnkr.co/edit/Ja3l0EkYK9bOnLIe?open=app%2Fapp.component.ts. Note that you need to change both the dateFormatOoo in the locale text, as well as the dateFormat passed into the flatpickr component.

Thanks again for bringing this up with us.

Kind regards,
Zoheil
