### ISSUE TITLE
Bug: TypeError with minified client side row model 

### ISSUE THREAD

**Issue by KonradHoeffner** [ag-grid/ag-grid#7755]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Plunker: <https://plnkr.co/edit/asqDeOJ5oWxGM5xO>

**Current behavior**

When using the minified client side row model as follows I get an error.

### Import minfied

```
import { createGrid, ModuleRegistry } from "../node_modules/@ag-grid-community/core/dist/core.esm.min.js";
import { ClientSideRowModelModule } from "../node_modules/@ag-grid-community/client-side-row-model/dist/client-side-row-model.esm.min.js";
ModuleRegistry.registerModules([ClientSideRowModelModule]);
```

### Error

```
Uncaught (in promise) TypeError: class constructors must be invoked with 'new'
    t client-side-row-model.esm.min.js:18
    createBeans core.esm.min.js:11
    h core.esm.min.js:11
    createBeans core.esm.min.js:11
    t core.esm.min.js:11
    create core.esm.min.js:11
    Iy core.esm.min.js:11
    table table.js:114
    showPath index.js:38
    selectTarget index.js:93
    selectTarget index.js:92
    addIds index.js:123
    on event.js:54
    on event.js:42
    on EventTarget.js:49
    addIds index.js:123
    each Dom.js:89
    main index.js:20
    async* index.js:136
client-side-row-model.esm.min.js:18:7801
    h core.esm.min.js:11
    createBeans core.esm.min.js:11
    t core.esm.min.js:11
    create core.esm.min.js:11
    Iy core.esm.min.js:11
    table table.js:114
    AsyncFunctionNext self-hosted:852
    (Async: async)
    showPath index.js:38
    selectTarget index.js:93
    (Async: EventListener.handleEvent)
    selectTarget index.js:92
    addIds index.js:123
    (Async: EventListener.handleEvent)
    on event.js:54
    forEach self-hosted:203
    on event.js:42
    on EventTarget.js:49
    addIds index.js:123
    each Dom.js:89
    main index.js:20
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> index.js:136
```
### Complete MWE

Note that this is taken from <https://www.ag-grid.com/javascript-data-grid/esm-modules/> however I fixed one bug in the docs: There was an import of "Grid", which I corrected to "createGrid". Also I changed `client-side-row-model/dist/client-side-row-model.esm.js'` to `client-side-row-model/dist/client-side-row-model.esm.min.js`, otherwise the bug doesn't occur.
Note also that plunkr seems to already have everything installed into node_modules, so using a CDN or local npm install isn't needed for this example.

```
<!DOCTYPE html>
<html>
    <head>
        <link
            rel="stylesheet"
            href="./node_modules/@ag-grid-community/styles/ag-grid.css"
        />
        <link
            rel="stylesheet"
            href="./node_modules/@ag-grid-community/styles/ag-theme-quartz.css"
        />
        <script type="module">
            import { ClientSideRowModelModule } from './node_modules/@ag-grid-community/client-side-row-model/dist/client-side-row-model.esm.min.js';
            import {
                createGrid,
                ModuleRegistry,
            } from './node_modules/@ag-grid-community/core/dist/core.esm.js';

            ModuleRegistry.registerModules([ClientSideRowModelModule]);

            const columnDefs = [
                { field: 'make' },
                { field: 'model' },
                { field: 'price' },
            ];

            // specify the data
            const rowData = [
                { make: 'Toyota', model: `Corolla`, price: 35000 },
                { make: 'Ford', model: 'Mondeo', price: 32000 },
                { make: 'Porsche', model: 'Boxter', price: 72000 },
            ];

            // let the grid know which columns and what data to use
            const gridOptions = {
                columnDefs: columnDefs,
                rowData: rowData,
            };

            // setup the grid after the page has finished loading
            document.addEventListener('DOMContentLoaded', () => {
                const gridDiv = document.querySelector('#myGrid');
                const api = createGrid(gridDiv, gridOptions);
            });
        </script>
    </head>

    <body>
        <div
            id="myGrid"
            style="height: 200px; width: 500px"
            class="ag-theme-quartz"
        ></div>
    </body>
</html>
```

### Import non-minified works perfectly

```
import { createGrid, ModuleRegistry } from "../node_modules/@ag-grid-community/core/dist/core.esm.min.js";
import { ClientSideRowModelModule } from "../node_modules/@ag-grid-community/client-side-row-model/dist/client-side-row-model.esm.js";
ModuleRegistry.registerModules([ClientSideRowModelModule]);
```

Again: The only difference between the import blocks is `client-side-row-model.esm.js` vs `client-side-row-model.esm.min.js`.

**Expected behavior**

I expect the minified version to behave exactly the same as the non-minified version, only that the minified version uses less space and that the source code and maybe the error messages are less helpful. In particular if the non-minified version works perfectly fine, I expect there to be no errors with the minified version as well.

**Please tell us about your environment:**

* OS: Arch Linux with Gnome and pacman
* HTTP server: local "python -m http.server"

* **AG Grid version:** 31.1.1
 
* **Browser:**  Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0

* **Language:** ES6/7

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11091**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by kiril-matev** [comment]
Hello @KonradHoeffner,

We've looked into this issue and found that these modules do not exist anymore in later versions of AG Grid.

You can resolve this also by using packages as it's all in a single file.

As you can easily upgrade to a newer version or use packages to resolve this, we're not going to address this issue in the older version. This is why we've closed this bug as "won't do".

Thanks again for bringing this up with us.

**Comment by KonradHoeffner** [comment]
Glad to hear it's resolved in the current version, thanks for the response!
