### ISSUE TITLE
initialState does not work with Vue3 as described by the documentation

### ISSUE THREAD

**Issue by sk-tjdownes** [ag-grid/ag-grid#7761]
**I'm submitting a ...** 
- [x] bug report => see 'Providing a Reproducible Scenario'
- [ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
- [ ] support request => see 'Requesting Community Support'

`initialState` does not work in Vue as described.

> The initial state is provided via the grid option initialState. It is only read once when the grid is created.

Even if `initialState` is available when the grid is created, the state is not updated. The only reason the demo examples work is because the grid is being recreated after the grid and component lifecycles are complete. If you switch this example to use `<script setup>` and hydrate the `initialState` variable in the setup, the grid will not update state. Essentially you have to create the grid once, destroy it, and recreate it for the state to properly update. This isn't feasible in the `<script setup>` component lifecycle.

**Providing a Reproducible Scenario**
Switch the documentation example to use `<script setup>` and hydrate the `initialState` variable in the setup, the grid will not update state.

#### Current behaviour.
It is impossible to set the grid state before the parent component is fully created.

**Expected behavior**
It should be possible to set the data to the variable used by the `initialState` attribute before the grid is created, and expect the grid to set the state when it's fully instantiated. 

**Please tell us about your environment:**
* **AG Grid version:** 3.1.1

**Comment by sk-tjdownes** [comment]
I figured out how to make this work, albeit the docs are still wrong for Vue.

**Comment by NessterGit** [comment]
@sk-tjdownes Having the same problem here, were you able to get it to work using `<script setup>` ?

**Comment by sk-tjdownes** [comment]
> @sk-tjdownes Having the same problem here, were you able to get it to work using `<script setup>` ?

Yes, albeit it's hack IMO

I created this method
```
  const setGridInitialState = () => {
    setTimeout(() => {
      const idx = gridStates.value.findIndex((item) => item.gridId === gridId)

      initialState.value = gridStates.value?.[idx]?.gridState || {}
      gridVisible.value = true
    })
  }
 ```
 
 The grid needs to be initially hidden, or it will not work. You call this `onMounted`. I believe part of the process to make it work is to not modify the grid data or properties at all before you set the initial state. After the initial state is loaded, you can then make the call to get your data and set any grid props
 
 ```
 onMounted(async () => {
  setGridInitialState()
  const someData= await getSomeData()
})
```

**Comment by sk-tjdownes** [comment]
@NessterGit just to add some context to my code: `gridStates` is stored in localstorage and is a collection of grid states for various grids in our app. `gridId` is the id of the grid on the current view. `initialState` is bound to the same attribute on the ag grid. Hope this helps

**Comment by NessterGit** [comment]
@sk-tjdownes Oh I see, the visibility thing got to be about the only thing I didn't try. I'll be damned! Thanks for sharing your findings, cheers!
PS: I agree the docs could be improved on this feature, for Vue at least.

**Comment by sunnybak** [comment]
thanks! this fixed it. TLDR; make sure initial state is fully loaded before you render the grid.
