### ISSUE TITLE
Horizontal scrolling of ag-grid cannot be triggered.

### ISSUE THREAD

**Issue by JayClock** [ag-grid/ag-grid#7762]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

When I first enter a page with ag-grid, horizontal scrolling works fine, but when I navigate to other interfaces and then come back, the horizontal scrolling of ag-grid cannot be triggered.

**Current behavior**

https://github.com/ag-grid/ag-grid/assets/35857909/308901c1-6547-46d7-9c57-93e96e7c5e0f

**Expected behavior**

the horizontal scrolling of ag-grid can be triggered.

**Please tell us about your environment:**

xiaomi 14 

* **AG Grid version:** 31.1.1

* **Browser:**

Mozilla/5.0 (Linux; U; Android 14; zh-cn; 23127PN0CC Build/UKQ1.230804.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile Safari/537.36 XiaoMi/MiuiBrowser/18.1.110304 swan-mibrowser

**Comment by AG-Zoheil** [comment]
Hi @JayClock,

We haven't been able to reproduce this behaviour. In any case, we've just released `v31.2.0`. Please clear your cache and see if this issue still occurs for you. Please also try on a different device to ascertain the issue is not caused by your device.

Thank you!
