### ISSUE TITLE
Row grouping with master detail is not working

### ISSUE THREAD

**Issue by Hrishi1990** [ag-grid/ag-grid#7768]
Url: https://biturl.top/neeAze

Requirement: show data with the groups & last group should contain child/detail grid with different columns

**Current behavior**

- If we enable grouping with master & detail grid, the page gets hanged.

Is it possible to show data in groups & some groups with a details grid?
If not, can we have an alternative solution?

**Comment by AG-Zoheil** [comment]
Hi @Hrishi1990,

Please see this working here: https://plnkr.co/edit/2tH0tVRdGxq5zNL5?open=app.component.ts

Kind regards,
Zoheil
