### ISSUE TITLE
programatically selected rows are not getting exported when I use CSV Export onlySelected property

### ISSUE THREAD

**Issue by Balaji509** [ag-grid/ag-grid#7772]
**Current behavior**
In one of our applications, we utilize the export to CSV functionality for selected rows. It works flawlessly when I manually select the rows by clicking.

However, since we implement persistence (by storing the keys associated with the rows), when I navigate back to the page and programmatically select the rows using the **node.setSelected()** method, I see no rows getting downloaded in CSV file.

When I try to console event from rowSelectedEvent - **event.source = "rowClicked"** for externally clicking the row, **event.soruce="api"** for programatically selected rows.

**Expected behavior**
Ideally, irrespective of the event source (be it rowClicked or api) it should download the selected rows.

**Please tell us about your environment:**
windows, visual stuido code IDE

* **AG Grid version:** X.X.X
version: 30.0.5

* **Browser:**
Google Chrome and Micorsoft edge

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
*React Typescript 

![image](https://github.com/ag-grid/ag-grid/assets/45415400/af463e9c-57ea-4dd3-8525-054823a42778)
![image](https://github.com/ag-grid/ag-grid/assets/45415400/3c4bf5fb-3206-4642-93ef-78e181eeb0ae)
![image](https://github.com/ag-grid/ag-grid/assets/45415400/b068f4cb-befc-45c2-addd-cd8357cb76f6)

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by bogdanS-e** [comment]
The same issue here https://codesandbox.io/p/sandbox/csv-export-hidden-columns-forked-7ylgkn?file=%2Fsrc%2Findex.tsx%3A28%2C22
there is the code from your documentation. I just added 
```
defaultCsvExportParams={{
    onlySelected: true,
}
```

select a range then open the context menu and click export. You'll see only header names without any data
