### ISSUE TITLE
SSRM: getRows get into a loop when navigate to another page

### ISSUE THREAD

**Issue by miguelh-rebaseit** [ag-grid/ag-grid#7779]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**

I have a table of invoices with the next datasource config:

```
  const getServerSideDatasource = (): IServerSideDatasource => {
    return {
      getRows: async (params: any) => {
        const currentPage = params.api.paginationGetCurrentPage();

        const limit = 24;
        const skip = currentPage * limit;
        const data = await Invoices.getAll({}, skip, limit);

        const rowData = await rowDataMap(data);

        try {
          params.success({
            rowData,
            rowCount: data.total,
          });
        } catch (error) {
          console.error(error);
          params.fail();
        }
      },
    };
  };
```

This is how set the datasource:
```  
    const onGridReady = (params: any) => {
    params.api.setGridOption('serverSideDatasource', getServerSideDatasource());
  };
```

And the template looks like this:
```
          <AgGridReact
            columnDefs={colDefs}
            pagination={true}
            paginationPageSize={24}
            domLayout="autoHeight"
            rowModelType="serverSide"
            onGridReady={onGridReady}
            defaultColDef={{ filter: true, floatingFilter: true, sortable: true }}
            paginationPageSizeSelector={paginationPageSizeSelector}
            maxConcurrentDatasourceRequests={1}
          />
```
**Aclarations**
The method ``rowDataMap`` is a mapper to match with the table fields expect, this resolve into a ``Promise.all()`` because I need to consult another service with one property of the data of first request (the id of another entity)

**Current behavior**
In the first request when the component mounted everything is working as expected, the problem is when a try to navigate to another page (the next page or the last page, for example). When I do this the component gets into a loop, requesting to the service over and over with the same params until my service return error "Too many requests". If I see the network tab or log the data into the ``getRows`` method I can see that the service response good and the params are good too, but it seems like the component don't stop in the ``params.success()`` and do the request again.

**Expected behavior**
The expected behavior is the same when the first page loaded, when service response OK with data show it in the component and not doing multiples request in a loop

**Please tell us about your environment:**
Operating system: MacOS
IDE: Webstorm
Package manager: nmp
Node version: 18.19.0

* **AG Grid version:** 31.1.1

* **Browser:**
Firefox, Chrome

* **Language:**
TS 4.9.3, ES6

**Comment by AG-Zoheil** [comment]
Hi @miguelh-rebaseit,

Thank you for submitting this on Github.

SSRM is an enterprise feature. I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here.

Kind regards,
Zoheil
