### ISSUE TITLE
ag-grid Community [angular] not loading default overlayLoadingTemplate from url(https://ag-grid.com/images/ag-grid-loading-spinner.svg)

### ISSUE THREAD

**Issue by dyehia2** [ag-grid/ag-grid#7781]
Hello,

ag-grid Community [angular] is not loading the default overlayLoadingTemplate from url(https://ag-grid.com/images/ag-grid-loading-spinner.svg) even on your page/example:

https://www.ag-grid.com/examples/filter-conditions/simple-filter-options/modules/angular/

You can see an **empty** delay without a spinner for few seconds (as of today)

**Comment by AG-Zoheil** [comment]
Hi @dyehia2,

Thank you for raising this.

We've rectified the issue and the fix will be included in our next documentation update.

Kind regards,
Zoheil
