### ISSUE TITLE
Is there any way to only refresh cellClass or cellStyle of a cell?

### ISSUE THREAD

**Issue by danielmalaton** [ag-grid/ag-grid#7784]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
As the title says, is there any ways to refresh the `cellClass` or `cellStyle` of a cell? I see in the docs, we have `refreshCell`. But this API refresh trigger other options like `cellRenderer`.

**Please tell us about your environment:**

* **AG Grid version:** 31.1.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
