### ISSUE TITLE
wrapHeaderText and autoHeaderHeight not working in aggrid-vue

### ISSUE THREAD

**Issue by tuantuanzi-code** [ag-grid/ag-grid#7787]
Hi,
wrapHeaderText and autoHeaderHeight not working in my aggrid-vue.
part of my code:
this.columnDefs = [
{
field: 'customer',
headerName: 'Customer this is toooooo long',
filter: 'agSetColumnFilter',
},
{
field: 'change',
headerName: 'Change Demo shows',
enableRowGroup: true,
enablePivot: true,
filter: 'agSetColumnFilter',
cellRenderer(params) {
if (!params.data.change || params.data.change === 'NULL' || params.data.change === 'null') {
return '-';
}
return ${params.data.change};
},
},
];
this.defaultColDef = {
resizable: true,
sortable: true,
filter: true,
initialWidth: 100,
wrapHeaderText: true,
autoHeaderHeight: true,
};
however, my column header not wrapped. will cellRenderer exclusive with wrapText? not sure, but wrapText and autoHeight can work with flex:1 while wrapHeaderText and autoHeaderHeight still not working.
could you please help?
my AG-grid version is "ag-grid-vue": "^25.1.0"
Thanks!

example is https://plnkr.co/edit/5OeNraw2cX2Y942o?open=main.js

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-7427**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
