### ISSUE TITLE
Fill handle with filloperation provided uses formatted value instead of original value 

### ISSUE THREAD

**Issue by lucas-holm** [ag-grid/ag-grid#7795]
**I'm submitting a ...**
```
[x] bug report 
[] feature request
[] support request
```

**Current behavior**

After upgrading the ag-grid version from 27.3.0 to 31.2.0 i noticed a difference with using the fill handle.
I have 3 columns where the underlying data is of the object type and when using `fillHandle` with a `fillOperation` the copied values are the formatted values from the `valueFormatter` and not the underlying original value.

**Expected behavior**

When using the fill handle with a fillOperation provided to use the original values instead of the formatted ones as in earlier versions.
Documentation says:

```
Note that if any of the following conditions are true, then useValueFormatterForExport is ignored for that feature and the value will be either the original value or that set in the custom handler:

- If processCellForClipboard is provided when using copy/cut.
- If fillOperation is provided when using fill handle.
- If processCellForClipboard is provided when using copy range down.
- If processCellCallback is provided when using CSV export.
- If processCellCallback or [Excel Data Types](https://ag-grid.com/javascript-data-grid/excel-export-data-types) are provided when using Excel export.
- If the underlying value is a number when using Excel export. To export formatted number values to Excel, please use the [Excel Data Type](https://ag-grid.com/javascript-data-grid/excel-export-data-types/#strings-number-and-booleans) feature.
```

**Please tell us about your environment:**

- Windows 11
- Visual studio code
- npm
- Vue 3
- AgGridVue3

**AG Grid version:** 31.2.0

**Browser:**
Edge

**Language:**
Typescript 5.3

**Comment by lucas-holm** [comment]
Demo: https://plnkr.co/edit/V6JcTYkOr3YcvJk5?open=main.js

Use the fill handle and drag downwards. The new value will be the formatted string value which is not the case in earlier versions.

**Comment by AG-Zoheil** [comment]
Hi @lucas-holm,

Thank you for the demo.

We can see you've set `cellDataType = false`. However `useValueFormatterForExport` is now true by default, and is no longer linked to `cellDataType`. Setting `useValueFormatter = false` will give you the behaviour you are expecting.
 
If `fillOperation` is provided but returns false, then it falls back to the default grid behaviour (which is to use the value formatter unless `useValueFormatter = false`).

We will add a clarification to our documentation to make this part clearer.

I hope the above helps.

Kind regards,
Zoheil
