### ISSUE TITLE
When using `agMultiColumnFilter` on a date string, `agSetColumnFilter` cannot be applied.

### ISSUE THREAD

**Issue by XijueYZ** [ag-grid/ag-grid#7799]
When I use agMultiColumnFilter on a date string and set one of the filters to agSetColumnFilter, an error occurs. 
![image](https://github.com/ag-grid/ag-grid/assets/159006031/75032d5f-18d0-472a-8a9f-1d39d8f81ec7)

My data like:
![image](https://github.com/ag-grid/ag-grid/assets/159006031/5697101b-4cac-459e-b5a1-b8bd8fa82765)
But if I use `agSetColumnFilter` alone, this problem does not occur.

It seems that this piece of code has set `keyCreator`, but `valueFormatter` is not placed in the correct position, so `SetFilter` cannot access it.
![image](https://github.com/ag-grid/ag-grid/assets/159006031/caf4b3c2-01bd-499c-8409-b7dbe6cf7882)

**Comment by XijueYZ** [comment]
@AG-Zoheil You can reproduce the issue here: https://codesandbox.io/p/sandbox/floating-filters-forked-sythcc?file=%2Fsrc%2Findex.js%3A99%2C21

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-11608**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
