### ISSUE TITLE
I  get error  404 for the latest version of ag grid

### ISSUE THREAD

**Issue by mahdiporkar** [ag-grid/ag-grid#7800]
Hello Dear

Cannot find a valid ref in 
v31.2.0/grid-packages/ag-grid-enterprise/dist

**Comment by danshome** [comment]
Same, 

npm ERR! 404  '@ag-grid-community/angular@31.2.1' is not in this registry.

**Comment by AG-Zoheil** [comment]
Hi @mahdiporkar & @danshome,

Could you please provide more information for us to look into this? From where and how are you trying to download it?

Thanks

**Comment by mahdiporkar** [comment]
Dear , at this page  [https://www.ag-grid.com/javascript-data-grid/download/](url) when click on github repository 
**Download AG Grid Enterprise bundle** 
You can download AG Grid Enterprise from the dist folder of the AG Grid Enterprise [Github Repository](https://github.com/ag-grid/ag-grid/tree/v31.2.0/grid-packages/ag-grid-enterprise/dist).

**Comment by kiril-matev** [comment]
Hi @mahdiporkar,

Thank you for this response. This broken link in our documentation will be updated in our next release.

Thank you for using AG Grid Enterprise!
