### ISSUE TITLE
How do I merge columns by clicking

### ISSUE THREAD

**Issue by QC-Fan** [ag-grid/ag-grid#7801]
In one scenario, when the button in the third column is clicked, the first and second columns are merged and the input field is displayed

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
