### ISSUE TITLE
ag-grid-react 31.2.0 - Module not found: Error: Can't resolve 'react-dom/server' - Did you mean 'server.browser.js'?

### ISSUE THREAD

**Issue by mbzzt** [ag-grid/ag-grid#7803]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://github.com/mbzzt/ag-grid-bug

**Current behavior**
Similar issue than the one I reported a while back here https://github.com/ag-grid/ag-grid/issues/6853#issuecomment-1629194533 (that was fixed at that time)
Tried to upgrade to ag-grid-react 31.2.0, and I'm getting this error when running the app:

```
Module not found: Error: Can't resolve 'react-dom/server' in '/[REDACTED]/ag-grid-bug/node_modules/ag-grid-react/dist/package'
Did you mean 'server.browser.js'?
BREAKING CHANGE: The request 'react-dom/server' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
ERROR in ./node_modules/ag-grid-react/dist/package/index.esm.mjs 73:0-56
Module not found: Error: Can't resolve 'react-dom/server' in '/[REDACTED]/ag-grid-bug/node_modules/ag-grid-react/dist/package'
Did you mean 'server.browser.js'?
BREAKING CHANGE: The request 'react-dom/server' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 1 error
```

Some details about my environment:
- node v20.12.0
- App bootstrapped with CRA
- Relevant dependencies:
```"ag-grid-community": "31.2.0",
    "ag-grid-react": "31.2.0",
    "react": "17.0.2",
    "react-app-polyfill": "3.0.0",
    "react-dom": "17.0.2",
    "react-scripts": "5.0.1",
```

* **Browser:**
```'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'```

**Comment by mbzzt** [comment]
Thank you for your reply.
So this is the only way to use ag-grid along with Create React App going forward?
What was the change in 31.2.0 that caused this?
I could not find any mention of this in the change log nor in documentation. Can you please point me to any official documentation stating that overriding CRA config is the way to go for using ag-grid in a CRA-based application?
IMO, it's really hard to justify such config override just for upgrading ag-grid. And if there's really no other choice, please consider documenting this constraint, so everyone is aware about it.
Thanks.

**Comment by seanlandsman** [comment]
This is only an issue for **React 17** users that use CRA - non-CRA users or React 18+ users are unaffected.

This is an issue with how CRA consumes ESM modules.

This is a breaking change and should be documented as you say - this was an oversight on my part and documentation will be added shortly to highlight this change (and well as adding this to the changelog).

**Comment by mbzzt** [comment]
Got it. Thank you for your reply.

**Comment by sergioavazquez** [comment]
> This is only an issue for **React 17** users that use CRA - non-CRA users or React 18+ users are unaffected.
> 
> This is an issue with how CRA consumes ESM modules.
> 
> This is a breaking change and should be documented as you say - this was an oversight on my part and documentation will be added shortly to highlight this change (and well as adding this to the changelog).

@seanlandsman I'm having this same issue using CRA with React v18.2.0

**Comment by efhan-the-unorthodox** [comment]
> Hi @mbzzt,
> 
> Thanks for getting in touch.
> 
> Please use the following:
> 
> ```
> npm install react-app-rewired --save-dev
> 
> Create a file in the root of your project called config-overrides.js with the following contents:
> 
> module.exports = function override(config, env) {
>     config.resolve.alias["react-dom/server"] = "react-dom/server.js";
>     return config;
> }
> 
> replace the following scripts in your package.json:
> 
> "react-scripts start" -> "react-scripts start"
> "react-scripts build" -> "react-scripts build"
> ```
> 
> Kind regards, Zoheil

I tried this. Didn't work.

The following are my dependencies:
```
"@ag-grid-community/client-side-row-model": "^31.2.1",
    "@ag-grid-community/core": "^31.2.1",
    "@ag-grid-community/react": "^31.2.1",
    "@ag-grid-community/styles": "^31.2.1",
```

**Comment by prathinielsen** [comment]
ok
