### ISSUE TITLE
Why was 31.2 republished?

### ISSUE THREAD

**Issue by nzacca** [ag-grid/ag-grid#7808]
Greetings!

We updated to v31.2 two weeks ago (npm also [shows this here](https://www.npmjs.com/package/@ag-grid-community/core)) but the releases indicate 31.2 was re-released 6 hours ago.

Just wondering if this is a mistake? (ex. is this a patch that didn't get tagged properly?) 

If not, what is the difference between what was published two weeks and this new re-release?

Thank you kindly!

**Comment by AG-Zoheil** [comment]
Hi @nzacca,

Thank you for getting in touch.

We released v31.2 on npm 2 weeks ago but hadn't published the release on the GitHub releases page.

v31.2 is still the latest release. There's been no actual release yesterday, only an update to the release page to publish the 31.2 release from 2 weeks ago here https://github.com/ag-grid/ag-grid/releases/tag/v31.2.0.

Kind regards,
Zoheil

**Comment by nzacca** [comment]
Hi @AG-Zoheil ,

Perfect! Thank you very much for clarifying.

Cheers!
