### ISSUE TITLE
ag-grid-solid not updated to 31.2.0 or error in documentation ?

### ISSUE THREAD

**Issue by mthh** [ag-grid/ag-grid#7810]
In the documentation (here: https://www.ag-grid.com/react-data-grid/solidjs/) it says to use the package ag-grid-solid="~31.2.0" but the latest published version of `ag-grid-solid` is 31.1.1 (while `ag-grid-community`, `ag-grid-react`, etc. have all been updated to 31.2.0).

Is this normal? If so, perhaps the documentation should be updated to show the latest version number for solidjs, 31.1.1?
Otherwise maybe ag-grid-solid version 31.2.0 should be released if this is an omission.

Thanks in advance! (and thanks for the great work on ag-grid!)

**Comment by AG-Zoheil** [comment]
Hi @mthh,

Thank you for getting in touch about this.

AG Grid `v31.1` will be the last version to publish a SolidJS wrapper at this time as we have decided to suspend support for SolidJS from `v31.2` onwards.

We will update the references in the page you have linked.

Thanks for bringing this to our attention!

**Comment by mthh** [comment]
Thanks for your prompt reply :+1:

**Comment by davedbase** [comment]
> Hi @mthh,
> 
> Thank you for getting in touch about this.
> 
> AG Grid `v31.1` will be the last version to publish a SolidJS wrapper at this time as we have decided to suspend support for SolidJS from `v31.2` onwards.
> 
> We will update the references in the page you have linked.
> 
> Thanks for bringing this to our attention!

This is disappointing. There are several Solid community members who depend on this package. :(

**Comment by davedbase** [comment]
For anyone else reading this in the future, I've taken it upon myself to move the binding to a new package located in the SolidJS Community organization.

https://github.com/solidjs-community/solid-ag-grid

This doesn't support 31.2.0 yet, however, I'm working to bump the version. This version swaps out the rollup build and uses tsup and will see other improvements shortly.

**Comment by mthh** [comment]
What a great news, thanks for the initiative @davedbase!

I'll keep an eye on the repo to see if I can be of any help in the future (as I plan to use this community fork).

**Comment by davedbase** [comment]
Thanks. Someone had to do it. Couldn't let this get abandoned. Required so little effort (less than an hour) and I'll probably put another 2 hours into improving it. ✌️👍

**Comment by JamesSwinton** [comment]
Thanks @davedbase, we appreciate you picking this up! Just to let you know we'll be adding this to our new [Community Tools & Extensions](https://www.ag-grid.com/community/tools-extensions/) page so that other devs can find this version of the wrapper moving forward.
