### ISSUE TITLE
Pagination problem | pageLastRowUnknown

### ISSUE THREAD

**Issue by saeidi-dev** [ag-grid/ag-grid#7817]
In the footer grid, there is a problem in the pagination section where it displays, for example, from 1 to 50. that the phrase "?" displays.

**pageLastRowUnknown**

It can be seen here
https://plnkr.co/edit/?open=app.component.ts&preview

* **AG Grid version:** 31.2.0

**Comment by sergioorlov** [comment]
Also you can see this bug in your doc.
![image](https://github.com/ag-grid/ag-grid/assets/15910381/82dfd6b4-4023-44b5-8f98-89f46d77e1f9)

**Comment by sergioorlov** [comment]
@saeidi-dev do you have any updates ?

**Comment by nsivasankar-copperleaf** [comment]
According to the changelog, this issue was fixed as part of v31.3.1. However, I can't find any corresponding code changes in the repo associated with AG-11123. 

@AG-Zoheil Would you be able to indicate where the code change was made? Thanks!

**Comment by AG-Zoheil** [comment]
Hi @nsivasankar-copperleaf,

Apologies **AG-11123** was fixed as part of an internal code fix. The change can be seen [here](https://github.com/ag-grid/ag-grid/commit/af36af612f359201169c391f8b2fdb04b8553992).

Kind regards,
Zoheil
