### ISSUE TITLE
Table goes empty if filter options are not available after data update

### ISSUE THREAD

**Issue by danieldavidraj** [ag-grid/ag-grid#7819]
**I'm submitting a ...**
```
May be a bug report or a support request
```

I am using ```this.gridApi.setGridOption("rowData", data);``` to update the row data but if any of the options are not available after updating the rows, then the table becomes empty after another data update.

**Clear Explanation:**

These options are available for filtering for this data and I have selected **Down Switch**.

![image](https://github.com/ag-grid/ag-grid/assets/59305023/23826af0-9631-4281-ab5b-1428b5689258)

After updating the data, only these options are available for filtering and **Down Switch** is not available. When I update the data again, **Down Switch** becomes available but it's not being selected as it was not available previously, so the table goes empty:

![image](https://github.com/ag-grid/ag-grid/assets/59305023/d94ff069-c3b9-4393-bb02-693460c9c837)

**Please tell us about your environment:**
npm 10.2.4
node v20.11.1

* **AG Grid version:** 31.0.1

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'

* **Language:** [TypeScript 4.8.2]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by danieldavidraj** [comment]
Sure will do that.

**Comment by cgfitzgerald** [comment]
Hi! I have been experiencing the same issue. I noticed that this hasn't had any movement in 2 weeks so I created a repo on my github to replicate the issue with steps to follow for reproduction. Please let me know if you have any additional questions, look forward to hearing back, thanks!

**Repo here:** https://github.com/cgfitzgerald/ag-grid-filter-bug

![image](https://github.com/ag-grid/ag-grid/assets/10623032/4899317c-2b5c-48c2-b691-b72ab63aa157)
![2024-05-01_10-23-29](https://github.com/ag-grid/ag-grid/assets/10623032/49b5948c-25ca-464a-8df1-c1f461faf4c4)

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for getting in touch about this on GitHub and providing the project. We've looked into this and would like to provide an update:

Please note that this is the expected behaviour. The filter list will be updated reflecting the data change and previous selections will remain intact **as long as the filter value still exists after any transaction(s)**.

We will update our documentation to clarify and reflect the above.

Kind regards,
Zoheil
