### ISSUE TITLE
Chart theme overrides for the axes don't work when grid data is grouped

### ISSUE THREAD

**Issue by dominikkurenda** [ag-grid/ag-grid#7824]
I'm submitting a 
[x] bug report => see 'Providing a Reproducible Scenario'

On user created charts overrides for the axes don't work when data is grouped.

https://plnkr.co/edit/umFIG02kBe9j8lPs 

In this example when we create chart (by selecting data and choosing  range chart from context menu) in grouped grid we should excpect to get axes names transformed. It does not do that, also default rotate angle is weird.
![image](https://github.com/ag-grid/ag-grid/assets/49497440/4cb39933-06d6-413a-bfa6-a41886b2ab6c)

Formatting only occures when the grid is not grouped
![image](https://github.com/ag-grid/ag-grid/assets/49497440/f264408b-c314-4788-84df-00f733d65098)

**Comment by AG-DavidG** [comment]
Hi @dominikkurenda 

When creating a chart from a grouped grid, the axis used is a grouped category axis. 

This has a different label rotation to enable the different levels to be nested.

When using theme overrides for such a chart, you need to specify the `grouped-category` rather than the `category` axis type.

>       axes: {
>         'grouped-category': {
>           label: {
>             formatter: (item) => item.value + ' 69',
>           },
>         },
>       },

Thanks

David

**Comment by dominikkurenda** [comment]
Thank you @AG-DavidG for the help. Adding grouped-category worked :)

Could you please add this override here because i was looking for it a long time and it is not in AgChartThemeOverrides interface:
https://charts.ag-grid.com/themes-api/#reference-AgChartTheme-overrides
![image](https://github.com/ag-grid/ag-grid/assets/49497440/be135cf0-a3e4-4f15-bf8e-e3f145509d1f)

**Comment by AG-DavidG** [comment]
Yes, we will do that in the next update.
