### ISSUE TITLE
Loading Overlay is not shown on undefined rowData

### ISSUE THREAD

**Issue by Alexander-Ruedi** [ag-grid/ag-grid#7828]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- https://codesandbox.io/p/sandbox/overlays-forked-qln7kc?file=%2Fsrc%2Findex.tsx%3A59%2C24

Current behaviour.
The buttons for "Show data" and "Show no rows overlay" are working. The "Show loading overlay" button doesn't behave as expected.

Expected behaviour.
As documented here: https://ag-grid.com/react-data-grid/overlays/
The loading spinner should be displayed when rowData (or colDef) is set to undefined or null

**Please tell us about your environment:**
Linux, Chromium, AG Grid 31.2.0

* **AG Grid version:** 31.2.0

* **Browser:** 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'

* **Language:** all

### Additional information:
- We did set the overlay manually using the api. However that additional state is causing flickering. This is why I tried to use the implicit overlay handling.

**Comment by AG-Zoheil** [comment]
Hi @Alexander-Ruedi,

Thank you for getting in touch via GitHub.

This has been noted internally and fixed already. The working version will be available in our next release.
Thank you for your understanding!

Kind regards,
Zoheil
