### ISSUE TITLE
[scroll] add options to always show scrollbars

### ISSUE THREAD

**Issue by supersabillon** [ag-grid/ag-grid#783]
When a grid overflows with scrollable content, there's a ux concern that there's no indication that user needs to scroll to see more content. 

Having an option to always show the scrollbar would help tackle this problem.

**Comment by ceolter** [comment]
"When a grid overflows with scrollable content, there's a ux concern that there's no indication that user needs to scroll to see more content." -> but the scrollbar shows when you need to scroll, which is the indication to the user, maybe i misunderstand?

**Comment by supersabillon** [comment]
On Chrome and Firefox the scrollbars only shows when you start scrolling. There's no indication of scrollable content on initial load or on hover.

**Comment by ceolter** [comment]
i'm guessing you are looking for a css class to be set on the scrollable divs? can you advise what setting? thanks.

**Comment by ceolter** [comment]
setting css overflow to 'scroll' rather than 'auto' does this. also need to refactor the code so that we are using classes and not setting styles. maybe we have 'horizontally scrolling' as a class that we add / remove to the panels (pinned etc based on what has the scroll bar).

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-113

**Comment by schreyerpeter** [comment]
Are there any recent updates to this issue? Thanks.

**Comment by sdn2525** [comment]
@ceolter I tried changing` overflow: scroll` at multiple places but couldn't see the scroll bar visible always. Can you please specify the **exact name of class/classes**, where we need to change `overflow: scroll ` from `auto` so that we can see the scrollbar until this feature has been added to the next version

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by paritosh64ce** [comment]
https://stackoverflow.com/a/52775695/1417185

    .ag-body-viewport-wrapper.ag-layout-normal {
      overflow-x: scroll;
    }

**Comment by lukeaus** [comment]
https://stackoverflow.com/a/52884417/3003438

Solution that also covers macOS/WwebKit browsers

```
.ag-body-viewport-wrapper.ag-layout-normal {
  overflow-x: scroll;
  overflow-y: scroll;
}
::-webkit-scrollbar {
  -webkit-appearance: none;
  width: 8px;
  height: 8px;
}
::-webkit-scrollbar-thumb {
  border-radius: 4px;
  background-color: rgba(0,0,0,.5);
  box-shadow: 0 0 1px rgba(255,255,255,.5);
}

```
You also need to set property 'scrollbarWidth' on ag-Grid to the width/height number value above

`scrollbarWidth=8`

This way when you have more rows than fits on the screen, the last row will not be obscured by the scrollbar. This can happen when you have a summary row in ag-Grid.

Working Plunker [demo](https://next.plnkr.co/edit/FCgOocDM1ALJXPXd).

Thanks @paritosh64ce for providing the demo Plunker that I modified.

**Comment by cdussud** [comment]
Note this is still an issue. None of the documentation examples show a horizontal scrollbar on a Mac until the user has scrolled to the bottom of the rows. 

Pick any example: https://www.ag-grid.com/javascript-grid-column-definitions/#column-ids

When scrolled to the top, no horizontal scrollbar is visible. When scrolled to the bottom, the horizontal scrollbar is visible again.
