### ISSUE TITLE
Locked positions on ag-grid doesn't prevent moveable columns from entering locked space

### ISSUE THREAD

**Issue by chrisklay** [ag-grid/ag-grid#7830]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
For this official ag-grid example (https://ag-grid.com/examples/column-moving/advanced-lock/modules/typescript/)

1. Click the pin Athlete button to pin the Athlete column to the left position
2. Hold and drag the Country Column to the area where the Athlete column is pinned
3. The Country column enters the pinned space 

**Expected behavior**

1. The user should not be able to move columns into the pinned space correct?

**Please tell us about your environment:**

* **AG Grid version:** 31.2.0

* **Browser:**
Every browser where the official ag-grid example is being run.

* **Language:** Typescript

**Comment by AG-Zoheil** [comment]
Hi @chrisklay,

Thanks for getting in touch via GitHub.

The behaviour you have described is to be expected.

The only two columns which are locked and hence not movable in the provided example are the columns displaying rowID and "Action". Since you are pinning the "Athlete" column there is nothing preventing a user from moving more columns into this pinned section. This is irrelevant of the logic for the locked columns.

I hope the above clarifies the issue.

If you still have any questions or any other feedback do not hesitate to let us know.

Kind regards,
Zoheil

**Comment by chrisklay** [comment]
Hello @AG-Zoheil,

It seems that there is a way to modify the behavior using lockPinned property:
 https://www.ag-grid.com/javascript-data-grid/column-pinning/#lock-pinned
 
 This will prevent columns from being dragged into the pinned area, if the property is applied to it

**Comment by andyFang94** [comment]
> Since you are pinning the "Athlete" column there is nothing preventing a user from moving more columns into this pinned section

Adding a feature. Can the configuration "lockPinned?: boolean;" be changed to "lockPinned?: boolean | 'left' | 'right';" to preventing a user from moving more columns into this pinned section

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

We already have this requirement to our backlog and we are tracking it with the following reference: **AG-10071**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
