### ISSUE TITLE
Manual resizing doesn't work if grid is opened in Dialog (modal) window

### ISSUE THREAD

**Issue by GsDelly** [ag-grid/ag-grid#7838]
I'm submitting a ... (check one with "x")

[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Manual resizing doesn't work if grid is opened in Dialog (modal) window**

Bug is reproduced when ag-grid is used inside React-Modal component. Modal component isn't using any special properties.

```
<Modal>
   <AgGridReact
    ....
    />
</Modal>
```

![image](https://github.com/ag-grid/ag-grid/assets/10940246/546dccba-7cc4-485d-9540-d9871f1e3327)

Here's another issue which could be related but i've posted it in here just in case if it will be helpful for resolving / investigating main resizing issue :
**Step 1:**
Resizing doesn't work but cursor has _**pointer**_ style
![image](https://github.com/ag-grid/ag-grid/assets/10940246/7b2652ca-8f59-4de7-a85b-7605d65dec29)

**Step 2:**
Click on resizing area
![image](https://github.com/ag-grid/ag-grid/assets/10940246/f68f3f7c-0587-4f16-a417-e885fac41d1d)

**Step 3:**
Hover area inside grid component
![image](https://github.com/ag-grid/ag-grid/assets/10940246/a8df20d0-3be4-4318-9345-13dbdbdc7b84)
Expected Behaviour: Cursor has _**pointer**_ style when hovering any area inside grid except headers area
Actual Behaviour: Cursor has _**ew-resize**_ style when hovering any area inside grid

* **UI Library:** React 
* **AG Grid version:** 28.2.1

**Current behavior**
manual resizing doesn't work, onColumnResized is not triggered and the cursor works not as expected (described above)

**Expected behavior**
everything works like without Modal window

* **Language:** [TypeScript 4.8.4 | ES5]
* **Additional Sources** Same issue was discussed 3 month ago [in here on stackoverflow ](https://stackoverflow.com/questions/77684180/when-ag-grid-react-shows-in-dialog-columns-do-not-resize) and there was no answer.

**Comment by AG-Zoheil** [comment]
Hi @GsDelly,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by GsDelly** [comment]
I believe it should help you: 

https://codesandbox.io/p/sandbox/modal-gialog-resize-forked-w5m4m2?file=%2Fsrc%2Findex.tsx%3A8%2C14

Note: And I also forgot to mention that Fluent UI components are also used...

**Comment by AG-Zoheil** [comment]
Hi @GsDelly,

Thanks for raising this on GitHub.

We've had a look and this is not an AG Grid bug. This is an issue with your Fluent UI component and they have an official issue logged here: https://github.com/microsoft/fluentui/issues/20073 which seems to include a suggested workaround.

Please note that we do not usually provide support of this kind on GitHub, but we just wanted to clarify that this is not an AG Grid bug.

Kind regards,
Zoheil
