### ISSUE TITLE
Can not display data when scroll, the grid will be partly or totally blank

### ISSUE THREAD

**Issue by IrisChen7** [ag-grid/ag-grid#7843]
When I drag the scroll bar and use the mouse scroll wheel to scroll down after released the scroll bar, if I use the mouse scroll wheel too quickly, it will be whole blank, can be reproduced using the official demo.
![scroll bug](https://github.com/ag-grid/ag-grid/assets/163086466/e59e4040-17d1-42c8-9ebb-99e376e4be0c)

**Comment by AG-Zoheil** [comment]
Hi @IrisChen7,

Thank you for reporting this.

I haven't been able to reproduce this - can you please provide more information on your system and browser?

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by IrisChen7** [comment]
Hi, Zoheil

My system is windows 11 and browser is Chrome 123.0.6312.122.

It seems that there is a 500ms throttle when scroll, which may lead to this problem, and it will happen when I switch drag scroll bar to scroll wheel very quickly. It will be easier to reproduce this problem if you set rowBuffer to 0.

Sincerely,
Iris

**Comment by IrisChen7** [comment]
> Hi @IrisChen7,
> 
> Thank you for reporting this.
> 
> I haven't been able to reproduce this - can you please provide more information on your system and browser?
> 
> We're looking forward to your response.
> 
> Kind regards, Zoheil

Hi, Zoheil

My system is windows 11 and browser is Chrome 123.0.6312.122.

It seems that there is a 500ms throttle when scroll, which may lead to this problem, and it will happen when I switch drag scroll bar to scroll wheel very quickly. It will be easier to reproduce this problem if you set rowBuffer to 0.

Sincerely,
Iris

**Comment by AG-Zoheil** [comment]
Hi @IrisChen7,

Thank you for providing that extra information.

We have investigated the behaviour you have reported and would like to provide the following update:

This is a transient momentary behaviour that we were only able to reproduce with heavy CPU throttling. The main use cases of using either the scroll bar or the mouse wheel continue to perform as expected. It is also worthy to note that while CPU throttling is a useful tool for testing, it does not mirror a production-like environment one to one.

As we are committed to performance excellence, we will continue to monitor behaviours and continue to introduce gradual performance improvements to all areas of the grid as we see fit.

In light of the above I'll be closing this and would like to thank you for sharing your feedback with us.

Kind regards,
Zoheil
