### ISSUE TITLE
Incorrect warning with paginationPageSize / paginationPageSizeSelector

### ISSUE THREAD

**Issue by oleksandr-rybakov** [ag-grid/ag-grid#7844]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

If reporting a bug make sure to state.

**Current behaviour.**
![image](https://github.com/ag-grid/ag-grid/assets/124709789/df241699-5ebf-44d2-ac96-199556914363)
paginationPageSize={10}
paginationPageSizeSelector=[10, 20, 30]

**Expected behavior**
No warning as paginationPageSize grid option is set to a value that is in the list of page size options

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
