### ISSUE TITLE
Custom header Component with default header component template

### ISSUE THREAD

**Issue by AdeshCannou** [ag-grid/ag-grid#7847]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have a custom header component but I still want to use the default filter provided by the documentation : https://ag-grid.com/angular-data-grid/column-headers/#provided-component

You can see that the header of my sport column don't have the sort functionality like in the athlete column who has the default code with headerComponentParams and template.

https://plnkr.co/edit/uB0NtUoZXkB3r558?open=app.component.ts

**Expected behavior**

I want to use the default sort and filter in my custom header component

* **AG Grid version:** 30.2.1

* **Language:** [Angular | TypeScript 4.9 ]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by r20** [comment]
I'm surprised that ag-grid doesn't support this.  
@AdeshCannou  Did you ever find a solution?

**Comment by Althain** [comment]
I struggle with custom header too, I want to add a material icon after headerText showing a tooltip and I want to keep the rest.

Seems like this has been introduced to 33, but I can't update to it as seems not available in npmjs yet. https://www.ag-grid.com/angular-data-grid/column-headers/#inner-header-component .

**Comment by sabahang** [comment]
@Althain can you please clarify what's not available in npmjs? latest version should be all up and accessible

**Comment by Althain** [comment]
@sabahang Of course, so I tried to upgrade, but the 33 doesn't seem to be available for all the packages below: 
"@ag-grid-community/angular": "~32.3.3",
"@ag-grid-community/client-side-row-model": "~32.3.3",
"@ag-grid-community/styles": "~33.0.2",
"@ag-grid-community/theming": "~32.3.3"
And with the given packages and their version the innerHeader feature I gave link to doesn't work in my project.

**Comment by sabahang** [comment]
@Althain you need to be using `ag-grid-community` and/or `ag-grid-enterprise` instead of `@ag-grid-community/xxx` and `@ag-grid-enterprise/xxx` since ver 33. Please see the migration guide:
https://ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-33/#migrating-from-modules

Hope this helps

**Comment by Althain** [comment]
Thanks @sabahang my bad for not reading the migration guide, wasn't expecting change in dependencies though :)
