### ISSUE TITLE
Filters sidebar not shown with Server-side row

### ISSUE THREAD

**Issue by hieudgflintersvn** [ag-grid/ag-grid#7848]
```
ag-grid-vue3.js?v=0971cb0a:37280 
Uncaught TypeError: Cannot read properties of undefined (reading ‘add’)
    at _AgGroupComponent2.insertItem (ag-grid-vue3.js?v=0971cb0a:37280:18)
    at _AgGroupComponent2.addItem (ag-grid-vue3.js?v=0971cb0a:37275:10)
    at @ag-grid-enterprise_…s?v=0971cb0a:350:28
    at Array.forEach (<anonymous>)
    at _ToolPanelFilterGroupComp2.init (@ag-grid-enterprise_…s?v=0971cb0a:349:27)
    at ag-grid-vue3.js?v=0971cb0a:803:68
    at Array.forEach (<anonymous>)
    at Context.callLifeCycleMethodsOnBean (ag-grid-vue3.js?v=0971cb0a:803:20)
    at ag-grid-vue3.js?v=0971cb0a:788:50
    at Array.forEach (<anonymous>)
(anonymous)@AgGrid.vue:151

```

* **AG Grid version:** 31.2.1

* **Browser:**

* **Language:** [Vue3 | TypeScript 5.4 | ES6]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
