### ISSUE TITLE
Column header Menu popup is not closed with Escape key when ag grid is implement with Webcomponents/shadowDom

### ISSUE THREAD

**Issue by neelabhnagaich** [ag-grid/ag-grid#7858]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
when we implement ag grid using web components, closing of Column menu doesn't work with escape key press.

**Expected behavior**
We should be able to close the column header menu popup with the Escape button when ag grid is implement using web components.

**Please tell us about your environment:**

* **AG Grid version:** 31.2.1
Yes latest version also has this issue

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil
