### ISSUE TITLE
browser text selection only for fullwidth rows

### ISSUE THREAD

**Issue by deepikagupta31** [ag-grid/ag-grid#7859]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Enable browser's text selection only for fullWidth rows as they contain details more than a cell in the row.
We have an option `enableCellTextSelection` that does the purpose but is not restricted only to fullWidthRows it is also applicable to the non fullWidthRows.

Can we have a feature to add an option something like `enableFullWidthCellTextSelection`

**Comment by AG-Zoheil** [comment]
Hi @deepikagupta31,

Thanks for getting in touch via GitHub.

We are currently not considering feature requests via GitHub and we do not believe there is an underlying issue with this feature from a UX perspective.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
