### ISSUE TITLE
Attribute name assignment with decimal point failed

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#7860]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
The assignment failed when the column attribute name contains a decimal point

![U~3G3R`VX301`CZ7LWID$CW](https://github.com/ag-grid/ag-grid/assets/57131579/64a5b6ab-470f-4f04-96a8-24c10a99bf91)
![A$@R~8}$K6T}258Q0LPLBNT](https://github.com/ag-grid/ag-grid/assets/57131579/3c4f70ca-15b3-4400-b5ee-0bad0c577b80)

` this.gridApi.setRowData(this.data);`
![image](https://github.com/ag-grid/ag-grid/assets/57131579/913bbea5-d7e0-48a1-aa82-e9c30a3c92b1)

**Please tell us about your environment:** WIN2019   Visual Studio Code

* **AG Grid version:** 30.2.0

* **Browser:** Google Chrome 123.0

* **Language:** [ TypeScript 4.3.5 |  ES5]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by afr751116** [comment]
Hello, this is the sample address
https://plnkr.co/edit/J5qA7hgDagqbW08D?open=app.component.ts
![image](https://github.com/ag-grid/ag-grid/assets/57131579/85b94bf2-3995-4506-9c33-0d8ed72e528e)
In my code operation, I assign values through the following Api
`this.gridApi.setRowData(this.data);`
![image](https://github.com/ag-grid/ag-grid/assets/57131579/f75dccaf-7064-4269-bc5c-517d9d9a049a)

**Comment by afr751116** [comment]
Thanks for your answer
