### ISSUE TITLE
Scroll issue in the tree data view

### ISSUE THREAD

**Issue by cyanaryan** [ag-grid/ag-grid#7861]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Whenever I try to expand few rows in the tree data view, after some time there is very little space to scroll. Sometimes I am not able to expand the item for the below data. This is happening due to rows being pinned in  the tree data view. I saw that every examples in ag-grid is having row pinned (parents row is pinned and child row is getting scrolled) when we scroll. Below is the scenario I am facing
![Bug-Animation](https://github.com/ag-grid/ag-grid/assets/49512251/7447ca76-706d-42c7-9931-ab1dd6ab95f1)

Expected behaviour:
I want something like this
![Expected behaviour](https://github.com/ag-grid/ag-grid/assets/49512251/84b596a6-3d43-4f86-bf02-4dd642933468)
Below is the link for that
[https://stackblitz.com/edit/ag-grid-angular-hello-world-1gs4jx?file=src%2Fapp%2Fapp.component.ts](url)
This above url is using the version `"ag-grid-angular": "27.2.0",`

**Please tell us about your environment:**

* **AG Grid version:** `31.1.1`

* **Browser:** Google Chrome:121.0.6167.140 (Official Build) (64-bit)

**Comment by netnr** [comment]
vscode will only retain one or two levels when the visual height is small, and more levels will be retained when the visual height is large.

![GIF 2024-4-18 10-44-17](https://github.com/ag-grid/ag-grid/assets/10579621/52b3bd1e-f994-4da0-ace1-3a486e450e2b)

**Comment by cyanaryan** [comment]
Is there any solution, how we can fix that in the ag-grid?

**Comment by cyanaryan** [comment]
Is there any way we can solve this issue?
@netnr @AG-Zoheil

**Comment by AG-Zoheil** [comment]
Hi,

Please view this: https://ag-grid.com/javascript-data-grid/server-side-model-grouping/#suppressing-sticky-groups

Kind regards,
