### ISSUE TITLE
Row is inserted at random position when the filter is active.

### ISSUE THREAD

**Issue by zuzu-1412** [ag-grid/ag-grid#7868]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When I am doing an applyTransaction on a grid with no active filter ,the row is inserted just below the row which triggers applyTransaction but when a filter is active the new row gets inserted at random position.

**Expected behavior**
I want the new row to be inserted just below the row that triggers applyTransaction when the filter is in active state as well as non-active state. 

**Please tell us about your environment:**
Windows 12

* **AG Grid version:** 30.0.0

* **Browser:**
Chrome

* **Language:** [all]

**Comment by Atreya-112** [comment]
Hi Zoheil 
Right now I don't have a plunker sample with me for the issue but let me try to explain my problem in words :
Suppose I have a grid and a button outside .
The button when clicked, inserts a row in the grid.
Let's have a grid now with some rows .
If I click the button now the new row gets inserted at the bottom.
Now use a text filter on the row and you have some fewer rows .
If I click the button the row is inserted at some random point, either top or bottom or in between.
Is there a way I can insert / show it at a specific position.

Also I tried adding index property in the apply transaction function but that also breaks when sorting is applied.
Why is this happening ?

**Comment by tomasVizdal** [comment]
Hi,
I have similar issue. When I have an external filter and some rows are filtered out and I want to insert a new row at a certain position, let's say as 5th row, the new row is inserted as 5th row in the filtered grid, but my original intention was to set the new row as a 5th row in the overal grid (unfiltered one).

Is there a way to insert a row in a particular index into a grid while the grid is filtered?

I am setting the new row using `applyTransaction`, i.e. `this.gridOptions.api?.applyTransaction({add: [newGridRow], addIndex: 4});`

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
