### ISSUE TITLE
getLockOnRefresh sometimes triggers Error in my Application

### ISSUE THREAD

**Issue by Nikazoid** [ag-grid/ag-grid#7871]
https://github.com/ag-grid/ag-grid/blob/ee5e5d31d24f2a451b903ee4bf6d34b55beffa29/community-modules/core/src/rendering/rowRenderer.ts#L624

Hello, 

Is there a way to disable this error from being thrown, thus resulting in a blank page of my application ?
The application was developed on lesser version (26.2), after the increase of AG Grid version, blank pages due to this error getting called started to appear.

Additional Info:
application uses React AG-Grid Enterprise v.27.2.0

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
