### ISSUE TITLE
Loading Overlay does not appear when rowData is undefined or null as described in doc

### ISSUE THREAD

**Issue by ivankoleda** [ag-grid/ag-grid#7872]
**I'm submitting a bug**  

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Expected behavior**

> When using the Client-side Data the grid uses two overlays:
> 1. Loading Overlay: Displayed if rowData or columnDefs are set to `null` or `undefined`.
> 2. No Rows Overlay: Displayed if rowData is an empty list.

https://ag-grid.com/react-data-grid/overlays/

Based on the documentation I expect to see Loading Overlay when `rowData` is `null` or `undefined`.

**Current behavior**

Both v30 and v31 don't match behaviour described in the doc.

 v30:
If we pass non-empty `rowData` array and later pass `undefined` or `null` as rowData prop, ag-grid shows "No Rows Overlay" instead of "Loading Overlay".

https://stackblitz.com/edit/vitejs-vite-v5petk?file=src%2FApp.jsx

v31
If we pass non-empty `rowData` array and later pass `undefined` or `null` as rowData, ag-grid shows no overlay at all. It shows data that was passed before.
https://stackblitz.com/edit/vitejs-vite-rl7ffx?file=src%2FApp.jsx

Based on these observations there is currently no way to declaratively trigger loading overlay by passing different rowData value. It can only be done only imperatively, by calling gridApi methods.

**Comment by AG-Zoheil** [comment]
Hi @ivankoleda ,

Thank you for getting in touch via GitHub.

This has been noted internally and fixed already. The working version will be available in our next release.
Thank you for your understanding!

Kind regards,
Zoheil
