### ISSUE TITLE
Filters persistence after data updates

### ISSUE THREAD

**Issue by yankouskaya-d** [ag-grid/ag-grid#7875]
**Description**:
 
According to the ag-grid documentation regarding active filters, previous selections are expected to remain intact when the filter list is updated due to changes in the data. However, when a user applies filters to specific columns and subsequently updates the data using the `applyTransaction` method (for example, by removing and then adding rows with certain values that are applied in the filter), the filter model fails to retain the selected items.
 
**Relevant documentation**:
https://ag-grid.com/angular-data-grid/filter-set-data-updates/

> Filter Active: Before the update, 'some' values in the filter were selected (as the filter was active). The filter list will be updated reflecting the data change, however previous selections will remain intact. If the update resulted in a new filter value, the new filter value will not be selected.

**Environment**:
    ag-grid-angular: "31.2.1",
    ag-grid-community: "31.2.1",
    ag-grid-enterprise: "31.2.1",
    typescript: "4.9.5",

**Browser**:
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
 
**Steps to reproduce**:
https://codesandbox.io/p/sandbox/transaction-updates-forked-rrxxs5

1. Apply a column filter for the value 'B'.
2. Update the data using the `applyTransaction` method: Click the ‘Apply transaction 1’ button, which will result in the removal of the row containing the value 'B'.
3. Update the data again using the `applyTransaction` method: Click the ‘Apply transaction 2’ button, which will add a new row with the value 'B'.
 

**Current behavior**
The filter model does not retain any selected items after the data updates.
 
**Expected behavior**
The filter model should retain the selected colId 'B' even after the data undergoes updates using the `applyTransaction` method.
Retaining previous selections as described in the documentation ensures that users can rely on their filtering preferences persisting, even as the underlying data changes. This consistency enhances usability and reduces user frustration by maintaining a predictable interface.

**Comment by yankouskaya-d** [comment]
PS. The same issue is reproduced using `applyTransactionAsync` method

**Comment by AG-Zoheil** [comment]
Hi @yankouskaya-d,

Thank you for getting in touch about this on GitHub.

Please note that this is the expected behaviour. The filter list will be updated reflecting the data change and previous selections will remain intact **as long as the filter value still exists after any transaction(s)**.

We will update our documentation to clarify and reflect the above.

Kind regards,
Zoheil
