### ISSUE TITLE
Is there an api for editing to trigger immediately

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#7885]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
May I ask that I edit the input 123 in the cell, hoping that it will trigger three events, currently only found that 《onCellKeyDown》 can be achieved, but it is about the keyboard, is there any other api that can be achieved?

**Please tell us about your environment:** WIN2019 Visual Studio Code

* **AG Grid version:** 30.2.0

* **Browser:** Google Chrome 123.0

* **Language:** [ TypeScript 4.3.5 | ES5]

**Comment by AG-Zoheil** [comment]
Hello @afr751116,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-11606**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
