### ISSUE TITLE
Ag-Grid-Enterprise has not been imported issue

### ISSUE THREAD

**Issue by trevord1990** [ag-grid/ag-grid#7890]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I am attempting to implement the `aggFunc: "sum"` functionality to my grid. I am getting the following warning in the console.

```
AG Grid: unable to use aggFunc as package 'ag-grid-enterprise' has not been imported. Check that you have imported the package:
            
    import 'ag-grid-enterprise';
            
For more info see: https://www.ag-grid.com/javascript-grid/packages/
```

and 

```
AG Grid: aggFunc is only available when @ag-grid-enterprise/row-grouping is loaded.
```

I am not sure why I am getting the first warning as I have `import 'ag-grid-enterprise'` in my code. 

I can post more of the code if needed.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil

**Comment by trevord1990** [comment]
Hi @AG-Zoheil , I appreciate the response. 

While my organization does have the enterprise version of AG-grid, I do not have an account to make support requests. I'd appreciate it if we could leave this question open as it should be relatively straight forward to solve.

**Comment by AG-Zoheil** [comment]
Hi @trevord1990,

I'm afraid there isn't much we can comment on based on what you've shared. The warning message should only show when ag-grid-enterprise is not imported (or not imported properly).

Ideally, we'd recommend you get in touch with whoever at your organisation has access to our support as that is the best route going forward.

Kind regards,
Zoheil
