### ISSUE TITLE
About the popup window being closed

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#7892]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
`<div style="width: 550px; height: 300px" #inputArchives (click)="$event.stopPropagation()">
  <input
    nz-input
    #inputSearch
    type="text"
    nz-input
    [(ngModel)]="queryDto.filterText"
    (ngModelChange)="filterTextChange()"
    [placeholder]="l('SearchWithThreeDot')"
    (keydown)="onKeyDown($event)"
    nz-popover
    [nzPopoverVisible]="true"
    [nzPopoverContent]="table"
    nzPopoverPlacement="bottomLeft"
    [nzPopoverTrigger]="null"
  />

  <ng-template #table>
    <ag-grid-angular
      style="width: 550px; height: 300px"
      [class]="agThemeClass"
      [columnDefs]="columnDefs"
      [stopEditingWhenCellsLoseFocus]="true"
    >
    </ag-grid-angular>
  </ng-template>
</div>`

`    this.inputArchives.nativeElement.classList.add('ag-custom-component-popup');`

Enabled < stopEditingWhenCellsLoseFocus >, but added the < (click) = ". $event stopPropagation () "> and < ag - custom - component - the popup >, A mouse click on the pop-up window will still end the editing

![image](https://github.com/ag-grid/ag-grid/assets/57131579/a6a4485c-8d23-408e-a5ef-363ec5a6576a)

**Please tell us about your environment:** WIN2019 Visual Studio Code

* **AG Grid version:** 30.2.0

* **Browser:** Google Chrome 123.0

* **Language:** [ TypeScript 4.3.5 | ES5]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
