### ISSUE TITLE
refreshCells doesn't refresh aggregation rows [react]

### ISSUE THREAD

**Issue by csantos-nydig** [ag-grid/ag-grid#7894]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => see 'Providing a Reproducible Scenario'
- [ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
- [ ] support request => see 'Requesting Community Support'

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Go to https://codesandbox.io/p/sandbox/default-row-grouping-forked-cfwjxx?file=%2Fsrc%2Findex.tsx%3A53%2C1
- Click on "Swap B side"
- Notice the "B" leaf values changing from positive to negative and viceversa
- Notice the aggregated value DO NOT change ⚠️ 🤕  

**Current behavior**

Triggering `refreshCells` after modifying a value in ag-grid context only modifies the values on leaf nodes

https://github.com/ag-grid/ag-grid/assets/87080313/46fdf0e4-1f15-4115-a99e-81c939560759

**Expected behavior**

Triggering `refreshCells` after modifying a value in ag-grid context should modify leaf nodes **and** aggregated values and any other values that might be associated to them.

**Please tell us about your environment:**
irrelevant. running in codesanbox.

**AG Grid version:**

`31.2.1` but also seeing it in `28.2.1`

**Browser:**
Unrelated, but here it is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Language:**

irrelevant. running in codesanbox.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added this requirement to our backlog and we are tracking it with the following reference: **AG-11485**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by csantos-nydig** [comment]
Thanks @AG-Zoheil -

For what is worth; this was my workaround:

```ts
useEffect(() => {
  const grid = gridRef.current;

  if (grid) {
    // list all columns that depend on the side
    const columns = ['B', 'C'];

    grid.api?.refreshCells({ columns, force: true });

    // if there are row groups, refresh the row model to update the aggregate values for the updated columns
    if (grid.columnApi?.getRowGroupColumns().length ?? 0) {
      grid.api?.refreshClientSideRowModel('aggregate');
    }

    // if any of the updated columns are sorted, refresh the row model to update the sort order
    if (
      grid.columnApi?.getColumnState().some(({ colId, sort }) => sort && columns.includes(colId))
    ) {
      grid.api?.refreshClientSideRowModel('sort');
    }

    // if there are any filters applied to the updated columns, refresh the row model to update their filtered rows
    if (
      grid.api?.isQuickFilterPresent() ||
      Object.keys(grid.api?.getFilterModel() ?? {}).some((filteredColumn) =>
        columns.includes(filteredColumn)
      )
    ) {
      grid.api?.refreshClientSideRowModel('filter');
    }
  }
}, [clientSide]);
```
