### ISSUE TITLE
Failed to resolve import "@ag-grid-community/styles/ag-grid.css"

### ISSUE THREAD

**Issue by Infinity-chakra** [ag-grid/ag-grid#7897]
I've got the following error while using the version 31.2.1 of the `ag-grid-vue3` in Vue 3.
![image](https://github.com/ag-grid/ag-grid/assets/156979422/1b472dde-5bc0-4323-8d86-63a1e579b034)

I followed the instruction from the npm guideline.
```
npm install --save @ag-grid-community/core @ag-grid-community/vue3

import { AgGridVue } from "@ag-grid-community/vue3";
import "@ag-grid-community/styles/ag-grid.css";
import "@ag-grid-community/styles/ag-theme-quartz.css"; 
```
I'm using the unplugin-vue-components plugin in my project, wonder if this could be causing the issue.

**Comment by YSHgroup** [comment]
It seems you use the module type of ag-grid-vue3. If so, further installation would be required, like @ag-grid-community/client-side-row-model, @ag-grid-community/styles.
The installation of @ag-grid-community/styles will be resolve the error ` Failed to resolve import "@ag-grid-community/styles/ag-grid.css"` you faced.
And you may encounter another error, so, make sure to add the following lines.
```
import { ModuleRegistry } from '@ag-grid-community/core';
import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
ModuleRegistry.registerModules([ ClientSideRowModelModule ]);
```
Hope this would be help for you.
