### ISSUE TITLE
 Component <Anonymous>: setup function returned a promise, but no <Suspense> boundary was found in the parent component tree. A component with async setup() must be nested in a <Suspense> in order to be rendered. 

### ISSUE THREAD

**Issue by f754699** [ag-grid/ag-grid#7900]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

my Custom Components 
```
const indexComponent = defineNuxtComponent({
    name: "xuhaozujian",
    props: {
        params: {
            type: Object,
            default: {},
        },
    },
    setup(props) {
        const init = () => {
            console.log("序号组件的内容：", props.params)
        }
        process.client && init()
        return () => {
            return !Number.isNaN(props.params.index) && <span>{props.params.rowIndex + 1}</span>
        }
    },
})
```

```
 {
                headerName: "序号",
                show: true,
                field: 'id',
                cellRenderer: indexComponent,
            },
```

```
 Component <Anonymous>: setup function returned a promise, but no <Suspense> boundary was found in the parent component tree. A component with async setup() must be nested in a <Suspense> in order to be rendered. 
````

这是一个同步的组件，但不知道为什么渲染成了异步组件

**Expected behavior**
none

**Please tell us about your environment:**
win10，
"nuxt": "^3.10.3",
 "vue": "^3.4.21",
***.tsx

***AG网格版本：**
"ag-grid-vue3": "^31.2.1",

* **Browser:**
Microsoft Edge
版本 124.0.2478.67 (正式版本) (64 位)

﻿

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by f754699** [comment]
https://github.com/f754699/github-muvq7g

**Comment by AG-Zoheil** [comment]
Hello @f754699,

Thank you for the suggestion.

This needs to be investigated further by us.
We have added this requirement to our backlog and we are tracking it with the following reference: AG-11496

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
