### ISSUE TITLE
Empty changelog

### ISSUE THREAD

**Issue by Alexander-Ruedi** [ag-grid/ag-grid#7901]
I saw that two new version were released, but the changelogs are empty.

https://www.ag-grid.com/changelog/?fixVersion=31.3.1
https://www.ag-grid.com/changelog/?fixVersion=31.3.0

**Comment by AG-Zoheil** [comment]
Hi @Alexander-Ruedi,

Thanks for being so keen & quick to check out our latest versions. The changelog normally gets populated with a short delay after the release.

Our latest version that was released today is `31.3.1` and you can find all items that were actioned in this release in our changelog now.

Kind regards,
Zoheil
