### ISSUE TITLE
Master-Detail in community 

### ISSUE THREAD

**Issue by Disuny** [ag-grid/ag-grid#7905]
Would it be possible to have a "Master/Detail"
in the community version?
just to expand/collapse row

**Comment by AG-Zoheil** [comment]
Hi @Disuny,

Thank you for getting in touch via GitHub.

We are a proud member of the open source community and hence offer many fundamental data grid features under the MIT licence at no cost.
However certain features are only available in our enterprise plan which comes with several further benefits.

Master/Detail is one of the features that is only available under our enterprise plan. You can find the whole list of feature differences on our pricing page here: https://ag-grid.com/license-pricing/.

Kind regards,
Zoheil
