### ISSUE TITLE
Ag Grid Enterprise Edition - Date filter problems

### ISSUE THREAD

**Issue by mervearsln** [ag-grid/ag-grid#7906]
I want to write a date filter for some columns in Ag Grid Enterprise Edition. However, when I combined all the codes I found, there was no positive result. All data and features in the grid should appear in the same date format ("DD/MM/YYYY").
1. In the floating filter of the column, we want to enter the date as "DD/MM/YYYY" and the placeholder should also change.
2. Also, since the incoming data is in ISO format, is there a feature of the grid without having to format the data (like dateFormat prop)?
3.I also translated all the texts into the local language. However, the month information does not display the local language, it still display in English. How do I solve these problems?

Thanks.

**Comment by AG-Zoheil** [comment]
Hi @mervearsln,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Meanwhile I have tagged this issue with the item **AG-3735** from our backlog which is a feature request to allow a custom date format to be specified for date filters.

Kind regards,
Zoheil
