### ISSUE TITLE
how to create single secondary axis for two line chart in right and one groupedcolumn chart in right side in combination chart in ag grid react integration

### ISSUE THREAD

**Issue by sachinchaubey** [ag-grid/ag-grid#7908]
I'm Using ag grid 31.2 version and i'm facing problem in make single secondary axis for 2 line chart in right side and primary axis in left for groupcolumn . that i'm implementing customcombo chart type for integrating combination chart in ag grid react.
const [columnDefs, setColumnDefs] = useState([
    {
      field: "period",
      chartDataType: "category",
      headerName: "Financial Period",
      width: 150,
    },
    {
      field: "recurring",
      chartDataType: "series",
      headerName: "Recurring revenue",
    },
    {
      field: "individual",
      chartDataType: "series",
      headerName: "Individual sales",
    },
      {
      field: "abc",
      chartDataType: "series",
      headerName: "abc",
    },
  ]);
  const defaultColDef = useMemo(() => {
    return {
      flex: 1,
      minWidth: 100,
    };
  }, []);
  const popupParent = useMemo(() => {
    return document.body;
  }, []);
  const chartToolPanelsDef = useMemo(() => {
    return {
      defaultToolPanel: "settings",
    };
  }, []);

  const onGridReady = useCallback((params) => {
    

    getData().then((rowData) => params.api.setGridOption("rowData", rowData));
  }, []);

const chartThemeOverrides = useMemo(() => {
  return {
    common: {
      padding: {
        top: 45,
      },
      axes: {
        number: {
          left: {
            keys: ["recurring"],
            label: {
              formatter: (params) => {
                return params.value + "M";
              },
            },
            title: {
              enabled: true,
              text: "recurring",
            },
          },
          right: {
            keys: ["individual", "abc"], // include both series in the right axis keys
            label: {
              formatter: (params) => {
              return params.value;
              },
            },
            title: {
              enabled: true,
              text: "abc/individual",
            },
          },
        },
      },
    },
  };
}, []);

const onFirstDataRendered = useCallback((params) => {
  chartRef = params.api.createRangeChart({
    chartContainer: document.querySelector("#myChart"),
    cellRange: {
      columns: ["period", "recurring", "individual", "abc"],
    },
    seriesChartTypes: [
      { colId: "recurring", chartType: "groupedColumn", secondaryAxis: false },
      {
        colId: "lineSeries",
        chartType: "line",
        secondaryAxis: true,
        series: [
          { yKey: ["individual"] },
          { yKey: ["abc"] },
        ],
      },
    ],
    chartType: "customCombo",
  });
}, []);
this is my all code i wanted to make individual and abc that chart type is line should have singel secondary axis in right side and groupcolumn axis in left side that are already by default.

**Comment by sachinchaubey** [comment]
@AG-Zoheil @robindenton-ag-grid please help me

**Comment by AG-Zoheil** [comment]
Hi @sachinchaubey,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

Please also note that there is no need to tag people in your comments - all issues raised will be dealt with in due time.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by sachinchaubey** [comment]
Hyy @AG-Zoheil here is the plunker [link](https://plnkr.co/plunk/ZyZz8YzICk9aMcC4) of my code. (Open the url in tab the go to the edit on the top left corner so you will find the code with live example)

**My requiement**
- In this code in both line chart has there saperate secodary axis name pressure and temp in the right side. but i wanted only one secondary axis for both line chart in right side. so that both line chart denoted there axis on a single secondary axis on right side.
- From last 3 day's i'm try hard to make it but i'm failed please give me right path. 

thanks regard

**Comment by AG-Zoheil** [comment]
Hello @sachinchaubey,

Thank you for providing the example.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-6877**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
