### ISSUE TITLE
Is it possible to use a Firestore collection as a Server Side Row Model datasource?

### ISSUE THREAD

**Issue by bbaappss** [ag-grid/ag-grid#7920]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
I'm curious if it is possible to use a Firestore collection as a Server Side Row Model datasource and use the column header controls to control the query getting sent to Firebase.

**Comment by AG-Zoheil** [comment]
Hi @bbaappss,

Thanks for getting in touch via GitHub.

Please note that AG Grid is agnostic in regards to the backend implementation. 

However we don't have any specific examples or experience using Firestore in particular. In general, certain things (like grouping) will certainly be more difficult in a NoSQL set up, but this all depends on your requirements and the expertise of the team implementing it. I can only suggest enquiring with Firebase directly or doing some further research online to help with your decision making.

Kind regards,
Zoheil
