### ISSUE TITLE
How to update data in row pined top?

### ISSUE THREAD

**Issue by hungleip9** [ag-grid/ag-grid#7921]
I have the following problem, when I use pinnedTopRowData, I cannot use applyTransactionAsync to update the data of pinned rows. How can I update the data on pined rows and make them flash like normal rows?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
