### ISSUE TITLE
How to resolve this issue in console

### ISSUE THREAD

**Issue by ankitghanekar-hcl** [ag-grid/ag-grid#7924]
Hi 
I'm using ag grid in react application, I do have license for it, but while working with test cases, I saw couple of issues.
1. it is showing "If you want to hide the watermark, please email info@ag-grid.com for a trial license."
2.  ****************************************** License Key Not Found ***********************************************

please help me, I'm adding screenshot for the refernce.
Thanks

<img width="795" alt="Screenshot 2024-05-06 at 8 14 11 PM" src="https://github.com/ag-grid/ag-grid/assets/91264853/5a03992a-9282-42f1-81a1-8ef70960010a">

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered. We are unable to deal with license issues via GitHub.

Kind regards,
Zoheil
