### ISSUE TITLE
AG Grid: duplicate group keys for row data, keys should be unique

### ISSUE THREAD

**Issue by erYasar** [ag-grid/ag-grid#7927]
I am trying to show a tree data. 

Use cases here is we also get duplicate data as well.

Error: AG Grid: duplicate group keys for row data, keys should be unique

Reproduce : https://stackblitz.com/edit/angular-ag-grid-tree-data-ydz3by?file=src%2Fapp%2Fapp.component.ts

**Comment by AG-Zoheil** [comment]
Hi @erYasar,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

You can read about getting started with both community or enterprise versions of our grid on [this page](https://ag-grid.com/javascript-data-grid/getting-started/). Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

Do let us know if you have any other questions.

Kind regards,
Zoheil
