### ISSUE TITLE
Custom tooltip component is being clipped

### ISSUE THREAD

**Issue by angadbhat** [ag-grid/ag-grid#7933]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
I have a custom tooltip component like below with text coming as multiline

```
<div class="ag-tooltip">
    {{ tooltip }}
</div>
```

The scss file for this angular custom tooltip component look like this (breaks into multi line)
```
:host {
    display: flex;

    width: auto;
    height: auto;
}

.ag-tooltip {
    width: max-content;
    min-width: max-content;
    max-width: 500px;

    overflow: hidden;
    white-space: pre-line;
    overflow-wrap: break-word;
}
```
when the tooltip column is at the end the tooltip is going out of the screen to the right.

**Expected behavior**
The expected behaviour should be that tooltip should stay with in the bounds of the grid/screen.

**Please tell us about your environment:**

* **AG Grid version:** ~31.2.0

* **Browser:** desktop/open-fin/electron

* **Language:** angular

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil
