### ISSUE TITLE
double click cell, An error occurred: TypeError: Failed to construct 'FontFaceSetLoadEvent': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

### ISSUE THREAD

**Issue by huyongyong1992** [ag-grid/ag-grid#7936]
<ag-table
        ref="circulatePackageTable"
        :show-checkbox-column="true"
        :col-parallel-width="false"
        :datas="tableData"
        :loading="loading"
        toolbar
        flexible
        :columns-config="configHeader"
        :page-size="pageSize"
        :current-page="pageNum"
        :total-rows="total"
        ag-key="circulateOrderConfirm"
        @page-change="handleCurrentChange"
        @page-size-change="handlePageChange"
        @on-row-selected-change="onRowSelected"
      >
      </ag-table>

// configHeader like this
[ {
          field: 'obtainQty',
          headerName: this.$t('takeAwayQty'),
          editable: true,
 }]
when i double click cell, show Error
![image](https://github.com/ag-grid/ag-grid/assets/22605989/9f4fe08d-6f32-4644-b86e-f0da96ea3f60)

this cell is out of viewport, if this cell is in viewport, no this error

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
