### ISSUE TITLE
AG Grid-- How to use default column filters for heirarchial grid

### ISSUE THREAD

**Issue by srikanthgarimilla1996** [ag-grid/ag-grid#7943]
Hello AG GRID,
I am using hierarchical grid in angular. This consists of one level of expansion. When i apply filters for the first level, I am able to filter only the top level.
I wanted to filter the second level as well.
I am using the same fields for both child and parent.
I wanted to achieve this using the filters provided by ag-grid,but not using the custom filters

Here is the code sand box example:
https://codesandbox.io/p/devbox/hungry-burnell-27l8l5?

Any help for this issue would be appreciated!!
Thanks

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
