### ISSUE TITLE
Unable to pass data manually to createRangeChart in Integrated Charts

### ISSUE THREAD

**Issue by lucaspmarra** [ag-grid/ag-grid#7947]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

*We're currently testing and planning to buy, depending on whether we can achieve our desired functionality.*

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- [Code Sandbox workspace][1]
- Description:

 I'm initially passing raw data to ag-Grid without any processing to populate the grid, which works well. However, the raw data results in a chart with many randomly arranged ages (all data).

I need to sort and process the age data before passing it to my range chart to create a sorted chart, while keeping the grid data unsorted.

I'm making a simples javascript sort to get the data working:
```javascript
const sortedData = computed(() => {
  return data?.sort(
    (a, b) => a.salesOrders.customerAge - b.salesOrders.customerAge,
  );
});
```
So my `sortedData` has all the data sorted by customerAge, but I'm unable to get the chart to use it instead of the rowData from ag-Grid. How can I make the chart use sortedData?

I'm unable to use chartThemeOverrides to set the chart theme and create an option flag within the createRangeChart function itself.  
```javascript
const onFirstDataRendered = () => {
  console.log("Starting chart...");

  gridApi.value.createRangeChart({
    chartContainer: document.querySelector(`#my_first_chart`),
    cellRange: {
      columns: columnsToChart,
    },
    chartThemeName: "ag-material",
    suppressChartRanges: false,
    chartType: "column",
    aggFunc: "sum",
    unlinkChart: true,
    chartThemeOverrides: {
      bar: {
        series: {
          data: sortedData,
        },
      },
    },
  });
};
```

  [1]: https://codesandbox.io/p/devbox/vue-ag-grid-5d3sgl?file=%2Fsrc%2FApp.vue%3A97%2C33

**Current behavior**
Bar chart gets data from rowData 

**Expected behavior**
A field to pass data manually to Range Chart

**Please tell us about your environment:**
Windows, Cube GraphQL, WebStorm

* **AG Grid versions:** 
 "ag-charts-enterprise": "^9.3.1",
    "ag-charts-vue3": "^9.3.1",
    "ag-charts-community": "^9.3.1",
    "ag-grid-charts-enterprise": "^31.2.1",
    "ag-grid-enterprise": "~31.2.1",
    "ag-grid-vue3": "^31.2.1",

* **Language:** Quasar with Vue 3 with Typescript setup and Apollo GraphQL

**Comment by lucaspmarra** [comment]
There is no data property to be sent manually to the Range Chart in the API part!
https://www.ag-grid.com/vue-data-grid/integrated-charts-api-range-chart/#range-chart-api

**Comment by AG-Zoheil** [comment]
Hi @lucaspmarra,

Thank you for your comment - as I said we are happy you are evaluating our grid. It is also highly appreciated that you've provided a codesandbox example - many people do not! However please note that we do not provide support for enterprise features via GitHub.

If you'd like to supercharge your trial and get dedicated support for your questions please email [info@ag-grid.com](mailto:info@ag-grid.com). If our sales team have set you up with a trial licence already that's fantastic - they will also be able to set you up with a ZenDesk account so you can get the support you are after. If you do decide to purchase an AG Grid licence you will be eligible to receive dedicated support via ZenDesk anyway, so might as well get started with it now!

Kind regards,
Zoheil
