### ISSUE TITLE
EXCEL export can export WYSIWYG

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#7950]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
```
    this.gridApi.exportDataAsExcel(this.getParams());
  getParams: () => ExcelExportParams = () => {    
    return {
      columnKeys: this.columnKeys,
      prependContent: this.getRowsPrependContent(), 
      author: '', 
      sheetName: this.tabTitle,
      fileName: this.tabTitle, 
  
       processCellCallback: params => {
       }}}

```

Try EXCEL export, how can the same effect as Csv export, export table display, without the need for separate processing
Problems caused by not handling manually:
1. If leading zeros exist, zeros are deleted from EXCEL
2, similar to the following custom code does not take effect, exported the original code, rather than display the value
`      valueFormatter: params => {
        return !params.node?.isRowPinned() && params.value ? this.lookupValue(this.departmentMappings, params.value) : null;
      }`

**Please tell us about your environment:** WIN2019 Visual Studio Code

* **AG Grid version:** 30.2.0

* **Browser:** Google Chrome 123.0

* **Language:** [ TypeScript 4.3.5 | ES5]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
