### ISSUE TITLE
Data validation value getter

### ISSUE THREAD

**Issue by Jaescott9** [ag-grid/ag-grid#7955]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
In enterprise I have a table where users can input days of the week and times of the days (in separate columns). Is there a way to ensure users only input valid weekdays and times?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
