### ISSUE TITLE
Ag-grid filters unlimited options - Need Help

### ISSUE THREAD

**Issue by san22230165** [ag-grid/ag-grid#7958]
I am using ag-grid-community, version: 29.0.0

In the Angular <ag-grid> filter, like below, 
The filter/menus seems to limit to two entities with an “OR” condition. 
Do we have option to allow unlimited.

<img width="142" alt="Filters" src="https://github.com/ag-grid/ag-grid/assets/45997337/93c452c9-1f54-40f9-b1d4-678771bb713a">

This is one of my client requirement. Please help.

**Comment by AG-Zoheil** [comment]
Hi @san22230165,

Please see this: https://ag-grid.com/react-data-grid/filter-conditions/#number-of-conditions

Kind regards,
Zoheil
