### ISSUE TITLE
excel export check style name is valid 

### ISSUE THREAD

**Issue by jackarcher73** [ag-grid/ag-grid#7960]
https://github.com/ag-grid/ag-grid/blame/3ab9a9481d5582c0118e858e2286eeac5e2a04f6/enterprise-modules/excel-export/src/excelExport/assets/excelLegacyConvert.ts#L98

We should check if mappedName is not undefined in case passed in a invalid style name

**Comment by AG-Zoheil** [comment]
Hi,

Thanks for getting in touch via GitHub.

We are currently not considering suggestions via GitHub and we do not believe there is an underlying issue with this feature from a functional perspective.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
