### ISSUE TITLE
AG Grid: Expand row to top

### ISSUE THREAD

**Issue by clarissajunc** [ag-grid/ag-grid#7961]
Is there a way to enable expanding a row grouping to the top? Meaning the grouping row keeps its position and the child data stacks above, instead of below. 

Example:

The collapsed row group
![image (14)](https://github.com/ag-grid/ag-grid/assets/61449275/9203c173-c413-4d24-adf3-69eec12f7e6c)

The expanded row group
![image (13)](https://github.com/ag-grid/ag-grid/assets/61449275/53b09a99-efcc-4b42-9c02-65e547d48ec0)

Thanks

**Comment by AG-Zoheil** [comment]
Hi @clarissajunc,

Thanks for getting in touch via GitHub.

Currently it is not possible to implement this behaviour with AG Grid. 

At this time we are not considering feature requests via GitHub and we do not believe there is an underlying issue with this feature from a UX perspective.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
