### ISSUE TITLE
Cell editing

### ISSUE THREAD

**Issue by NikitaLukashuk1** [ag-grid/ag-grid#7962]
I'm trying to modify cell, regarding to docs , via valueSetter, but the data object from callback argument Is freezed and I can't modify the data.
that error I get in console
TypeError: Cannot assign to read only property 'extDealName' of object '#<Object>'

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by danieldayton33** [comment]
This worked for me 

```
 valueSetter: (params) => {
            if (params.newValue !== params.oldValue) {
                // set the new value and spread it in
                const dataCopy = { ...params.data, ['foo']: params.newValue };
                // set the new data
                params.node.setData(dataCopy);
                return true;
            }
            return false;
        },
```
