### ISSUE TITLE
Ag-Charts in Vue 3: Broken and Lacking Support

### ISSUE THREAD

**Issue by lucaspmarra** [ag-grid/ag-grid#7964]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- [CodeSandbox](https://codesandbox.io/p/devbox/vue-ag-grid-forked-dmwn7q?file=%2Fsrc%2FApp.vue%3A151%2C9)
- A description:

Ag-Charts in Vue 3 seems to be broken. When will this be fixed? Vue 3 was released in 2022, and it's already 2024, yet there's still no official support for it. We're stuck with Integrated Charts, which lack configuration and customization options.

When I tried using Ag-Charts in Vue 3 (by simply copying the code from the documentation), it didn't work. Here's an example:

```javascript
✘ [ERROR] Could not resolve "vue-class-component"

    node_modules/.pnpm/ag-charts-vue3@9.3.1_ag-charts-community@9.3.1_vue@3.4.15/node_modules/ag-charts-vue3/lib/AgChartsVue.js:9:29:
      9 │ import { Options, Vue } from 'vue-class-component';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "vue-class-component" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the
  bundle.

12:01:55 PM [vite] Pre-transform error: @vnode-* hooks in templates are no longer supported. Use the vue: prefix instead. For example, @vnode-mounted should be changed to @vue:mounted. @vnode-* hooks support has been removed in 3.4.
/workspaces/sandbox/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/ag-charts-vue3@9.3.1_ag-charts-community@9.3.1_vue@3.4.15/node_modules/ag-charts-vue3/lib/AgChartsVue.js:9:29: ERROR: Could not resolve "vue-class-component"
    at failureErrorWithLog (/workspaces/sandbox/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651:15)
    at /workspaces/sandbox/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1059:25
    at /workspaces/sandbox/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.9.0
```

This code works in the documentation, but not in my actual project. 

* **AG Grid versions:**
 "ag-charts-community": "9.3.1",
    "ag-charts-enterprise": "9.3.1",
    "ag-charts-vue3": "9.3.1",
    "ag-grid-charts-enterprise": "31.3.1",
    "ag-grid-enterprise": "31.3.1",
    "ag-grid-vue3": "31.3.1",
    "vue": "^3.4.15"

**Comment by AG-DavidG** [comment]
Hi @lucaspmarra 

AG-Charts supports Vue 3.

Please add "vue-class-component": "^8.0.0-beta.3" to your package.json file. This should make it work.

Thanks

David

**Comment by lucaspmarra** [comment]
Unfortunately, according to the new Sandbox, it still doesn't work.
[CodeSandbox](https://codesandbox.io/p/devbox/vue-ag-grid-forked-dmwn7q?file=%2Fsrc%2FApp.vue%3A10%2C16)

![image](https://github.com/ag-grid/ag-grid/assets/30451874/0883d5a0-3732-4cea-992a-94208d718c74)

New dependencies:
```json
 "dependencies": {
    "ag-charts-community": "9.3.1",
    "ag-charts-enterprise": "9.3.1",
    "ag-charts-vue3": "9.3.1",
    "ag-grid-charts-enterprise": "31.3.1",
    "ag-grid-enterprise": "31.3.1",
    "ag-grid-vue3": "31.3.1",
    "vue": "^3.4.15",
    "vue-class-component": "^8.0.0-beta.3"
  },
  ```

I'm using the same code as in the documentation, but it still doesn't work: https://charts.ag-grid.com/vue/quick-start/

**Comment by AG-Zoheil** [comment]
Hi @lucaspmarra,

Thanks for raising this on Github. Can I please direct you to my comment here: https://github.com/ag-grid/ag-grid/issues/7947#issuecomment-2107614997.

We will not be able to answer any further support questions via GitHub. Once you contact us via ZenDesk we'd be happy to help you with your evaluation.

Kind regards,

**Comment by lucaspmarra** [comment]
> Thanks for raising this on GitHub. Can I please direct you to my comment here: [#7947 (comment)](https://github.com/ag-grid/ag-grid/issues/7947#issuecomment-2107614997).

Hi!
This Issue is about Ag-Charts Community/Free, it is not related to AG-Enterprise (although it appears in the dependencies).
To demonstrate this, I completely removed the Enterprise dependencies from CodeSandbox.

I ask you to please reopen the Issue because it is not related to the issue https://github.com/ag-grid/ag-grid/issues/7947, which is about Ag-Grid Enterprise.
It's a bug related to Ag-Charts and Vue 3, only - we're not talking about Enterprise here, so it wouldn't be wise to close it and throw me into ZenDesk (not least because I don't have access).

**Comment by AG-Zoheil** [comment]
Hi,

I can see this discussion is being continued in our AG Charts repo so I will leave this closed.
