### ISSUE TITLE
Style injection and shadow DOM

### ISSUE THREAD

**Issue by Cuttsy27** [ag-grid/ag-grid#7968]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I don't think a repro is required here but let me know otherwise.

I am using AG-Charts installed as a node_module. I am creating a chart inside a custom element with shadow DOM using Lit. AG-Charts injects all styles into the document and therefore the chart inside the shadow DOM cannot load any of the styles. Is there a way to disable the default style injection and import the styles manually into the custom element? Any other solution / workaround when working with shadow DOM and custom elements?

**Comment by AG-DavidG** [comment]
Hi @Cuttsy27 

Thank you for reporting this.

AG Charts does not officially support shadow DOMs at this point, but we are in the process of making changes to where we put our elements. This will be available in the upcoming version 10 and should help in these scenarios.

We'd be happy to take your use case into consideration when doing this work, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
David

**Comment by AG-DavidG** [comment]
Hi @Cuttsy27 

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
David
