### ISSUE TITLE
Nested data for Tree data

### ISSUE THREAD

**Issue by sachh185** [ag-grid/ag-grid#7969]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello,
I have a data structure like this:

```
const rowData = [
  {
    location: "United States",
    gold: 200,
    silver: 100,
    children: [
      {
        location: "New York",
        gold: 80,
        silver: 40,
      },
      {
        location: "Chicago",
        gold: 120,
        silver: 60,
      },
    ],
  },
  {
    location: "Australia",
    gold: 150,
    silver: 80,
    children: [
      {
        location: "Sydney",
        gold: 100,
        silver: 60,
      },
      {
        location: "Melbourne",
        gold: 50,
        silver: 20,
      },
    ],
  },
];
```

Is this supported by tree data in ag-grid? Or does it only support flat arrays?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by praveenkumar91** [comment]
Hi team,

I also have the same requirement. Is this not supported by aggrid ?
