### ISSUE TITLE
The getValue() method can't be found when the custom component is deployed to the server, but it can be found when run locally

### ISSUE THREAD

**Issue by zhangruyang1** [ag-grid/ag-grid#7970]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by XiaoBaiClassmate** [comment]
@AG-Zoheil Hi, this has been a problem for a long time.  For example [#6905](https://github.com/ag-grid/ag-grid/issues/6905)

**Comment by XiaoBaiClassmate** [comment]
Appears in vue3+vite production environment.
[For example ](https://stackoverflow.com/questions/73032489/ag-grid-framework-component-is-missing-the-method-getvalue-in-production-buil)

**Comment by AG-Zoheil** [comment]
Hello @XiaoBaiClassmate,

In our next upcoming releases we will focus on Vue 3. Please track this issue with the following reference: **AG-10708**

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
