### ISSUE TITLE
Setting the Row height looses centering of the text

### ISSUE THREAD

**Issue by pfteter** [ag-grid/ag-grid#7973]
**I'm submitting a ...** ```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://www.ag-grid.com/angular-data-grid/row-height/#getrowheight-callback

all text in cells should be centered. see url / image. Because of line-height not being adjusted after setting the height the text is not centered


**Expected behavior**

The text should be centered  - it's done with line-height calculation but when getrowheight is specified the linheight is not adjusted so the cell height is 200px but the line-height that is usually used to center it is just 40px so it's not possible to center content when row-height is set without a custom cell renderer

should be possible to center the text if the row height is set


using  https://www.ag-grid.com/javascript-data-grid/global-style-customisation-compactness/ 

could work in some cases but it's not doing the same

**Please tell us about your environment:**


* **AG Grid version:** X.X.X
latest

* **Browser:**
chrome


![image](https://github.com/ag-grid/ag-grid/assets/167297126/25e9c95e-31e3-4771-a567-73d99fb7d92d)

**Comment by BernieSumption** [comment]
You can vertically align text in cells using CSS:

```css
.ag-cell-value {
  display: flex;
  align-items: center;
}
```

Here's a code sample (CSS has been added at the bottom of index.html): https://plnkr.co/edit/kQbNq6riZfKUazy3?open=app.component.ts&preview

**Comment by pfteter** [comment]
That braks text-overflow: ellipsis it's not acceptable since display: flex cannot be used with text-overflow ellipsis without the ellipsis content be wrapped into a container with for example display: block.

That needs a custom renderer or a special case where we for example activate autoHeight on the cell and ag grid will automatically add a wrapper in the cell (this is the workaround we are using now but that is a workaroud! )

**Comment by AG-Zoheil** [comment]
Hello @pfteter,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. Whilst we do not agree that this is a bug, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-11667**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by BernieSumption** [comment]
> I still think this is a bug, it should use CSS vars to calculate the line-height correctly.

Just to comment on this, the current behaviour is by design - the intention is that text in default height rows has the right amount of padding to make it appear vertically centred, but that if the row height becomes higher the text content is top aligned. Some applications rely on this behaviour to keep mixed-height content aligned. I agree it would be useful to have a feature to change the vertical alignment, I'm just explaining why this has to go through the feature request process rather than the bug fix process.

**Comment by itskando** [comment]
Is there a link to where we can upvote the vertical align center feature?
