### ISSUE TITLE
<ag-grid-angular> switch between [treedata]

### ISSUE THREAD

**Issue by san22230165** [ag-grid/ag-grid#7974]
Hi Team,

In angular <ag-grid-angular> i have requirement to show [TreeData] and normal grid data.
For this in a view, i have two <ag-grid-angular> on has [treeData]="true" , other has [treeData]="false",
At any point of time, i show only one grid conditionally(i have toggle button(checkbox) in UI).

Basically, is it possible to have only one <ag-grid-angular> where i can make [treeData] to be true (or) false conditionally.
I tried this, but switching from true/false, is not refreshing the UI. 

Please check if this is possible.

**Comment by AG-Zoheil** [comment]
Hi @san22230165,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

If you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil
