### ISSUE TITLE
Update a cell that is currently being edited [32314]

### ISSUE THREAD

**Issue by alexis-landrieu-avanade** [ag-grid/ag-grid#7975]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

How can we update a cell that is currently being edited? The issue at hand is that when users navigate using the tab key, the next cell retains the old value instead of updating to the new one (due to delayed changes).

My current workaround involves using api.stopEditing(); However, this causes a flickering effect and doesn't seem like an elegant solution...

Live example based on (https://ag-grid.zendesk.com/hc/en-us/articles/360024379131-Editing-circular-dependencies)
- https://stackblitz.com/edit/ag-grid-angular-hello-world-t9tuqf?file=src%2Fapp%2Fgrid-example.ts

**Expected behavior**

Cell value in the CellEditor must be updated.

**Please tell us about your environment:** 

* **AG Grid version:** 28.2.1 

* **Browser:** Chrome 122

* **Language:** Angular v16

**Comment by AG-Zoheil** [comment]
Hi,

You can see this implemented here: https://plnkr.co/edit/Szypr2ADRoMgQKvs?open=main.js

If you edit a value in the first column (Doubling) and press TAB the second column will reflect this.

I hope this helps.

Kind regards,
