### ISSUE TITLE
A bug occurred when the Paid Enterprise filter was searched remotely

### ISSUE THREAD

**Issue by crazy-wang** [ag-grid/ag-grid#7977]
I used the 18.0.0 enterprise paid version
When aggridvue performs filter remote full filtering, it listens for filter change events, triggers re-call to load data setRowData, and the result filter is reset. Normally, only the row data changes, and the filter of the table header remains in the filtered state.

![image](https://github.com/ag-grid/ag-grid/assets/24617035/434ccc01-a3c7-431b-8e6b-8a3321cb22ec)

![image](https://github.com/ag-grid/ag-grid/assets/24617035/01edca83-07c5-4f04-b9ae-1434cb3a5005)

![image](https://github.com/ag-grid/ag-grid/assets/24617035/62c86dcd-cc71-47df-87a3-b49222c29931)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by crazy-wang** [comment]
hi,
I uploaded a demo attachment. The ag-grid-vue plug-in and the elementui plug-in need to be introduced. The usage scenario is demonstrated in the demo:
The amount of data is relatively large, it will be processed by paging, the current page only shows 1000, so the filtering needs to be remote full data filtering.
Initially, the header filter is obtained through the backend service, and then manually set in.
Initialize the request server to render the data into the table. Listen for filter events. When the filter changed, the listening event was triggered to re-request the server data. When the data was returned and re-rendered into the table, something strange happened: the filter entry did not retain my previous filter state, but was reset. In normal cases, only table row data changes and filter is not reset。



Please replace the ajax requests in my code with your own









我爱%零零狗
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ag-grid/ag-grid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月17日(星期五) 晚上9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ag-grid/ag-grid] A bug occurred when the Paid Enterprise filter was searched remotely (Issue #7977)





 
Hi
 
Thank you for reporting this.
 
We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.
 
Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.
 
We're looking forward to your response.
 
Kind regards,
 Zoheil

**Comment by crazy-wang** [comment]
``
1. Using paging processing, a page display 1000; Bind the filterChanged event to the aggrid component
![image](https://github.com/ag-grid/ag-grid/assets/24617035/27274b41-fee4-4e81-a6c5-74ea189c6584)

**Comment by AG-Zoheil** [comment]
Hi @crazy-wang,

Thanks for getting back.

I'm afraid we will not be able to use screenshots as a starting point.

We appreciate you taking the time to report any potential issues, but if you'd like us to investigate this please use one of our examples as a starting point and fork & save a plunker that you can share with us.

Please also note that `v18` is now **six years old**. It is very likely that any issues reported for that version have already been fixed or are no longer relevant in newer versions of the grid. Therefore, please keep in mind that we only would fix issues that are present in the latest versions of the grid.

Many thanks!

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
