### ISSUE TITLE
Issue with the theme builder generated css file

### ISSUE THREAD

**Issue by lpachecocacib** [ag-grid/ag-grid#7978]
I'm submitting a
[x] bug report 

When using the [theme builder](https://www.ag-grid.com/theme-builder/), the generated css file (the core part of it) is not correct, the last attribute for selector is missing the semicolon, if there's only one attribute it's also missing.

Example : 

`.ag-list-item-hovered:after{
	background-color:var(--ag-range-selection-border-color);
	content:"";
	height:1px;
	left:0;
	position:absolute;
	right:0
}`

**Comment by BernieSumption** [comment]
According to the CSS spec, semi-colons are required *between* multiple property declarations within a rule, not after every rule. When you're writing CSS it is considered good practice to put semi colons at the end of each line for consistency and maintainability, and we do so in our source files, but the code you're looking at has been minified by [cssnano](https://cssnano.github.io/cssnano/) which only emits strictly necessary semi colons.

If this is causing issues for your setup or tooling, feel free to re-open the issue with details of the problems being caused and / or tools that are having issues.
