### ISSUE TITLE
Can a ag-grid cell has 3 or 4 functions?I mean that the cell has 3 or more click events,you can use these envet to do what you want to do .

### ISSUE THREAD

**Issue by codecodecookie** [ag-grid/ag-grid#7982]

**Comment by awdorrin** [comment]
Multiple click handlers can be implemented using a cellRenderer like this:

```
cellRenderer: (params) => {
  const span = document.createElement('span');
  span.innerHTML =
    `<span class='material-icons' id="click1-${params.colDef.field}-${params.rowIndex}">article</span>` +
    `<span class='material-icons' id="click2-${params.colDef.field}-${params.rowIndex}">article</span>`;

  span.querySelector(`#click1-${params.colDef.field}-${params.rowIndex}`)
    .addEventListener('click', this.click1Handler.bind(this, params.data));

  span.querySelector(`#click2-${params.colDef.field}-${params.rowIndex}`)
    .addEventListener('click', this.click2Handler.bind(this, params.data));

  return span;
},
```

NOTE: I am running into an issue after moving from 30.2.1 to 31.3.2 where an Angular MatDialog I am displaying from my click handlers is not rendering. Still investigating...

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
