### ISSUE TITLE
Ag-Grid, how to hide the group column

### ISSUE THREAD

**Issue by trevord1990** [ag-grid/ag-grid#7994]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I am using the  "ag-grid-react": "^31.3.1"

I am using the AG grid to display some data. Each data needs to have an expandable "child" row. There isn't really a hierarchy or logical column to group the data by so I want to hide the group by column.

I have tried adding `hide:true` to my defs:
```
                      autoGroupColumnDef={{
                        headerName: 'test',
                        field: 'soVRecordID',
                        hide: true,
                        cellRendererParams: {
                          suppressCount: true,
                        },
                        minWidth: 280,
                      }}
```

**Comment by sabahang** [comment]
@trevord1990 `groupDisplayType:'groupRows'` might be what you are looking for: 
https://ag-grid.com/javascript-data-grid/grouping-display-types/#group-rows

If not you could also fully customize group column using Custom Group Columns
https://ag-grid.com/javascript-data-grid/grouping-custom-group-columns/

Hope this helps

**Comment by devpedrorocha** [comment]
Someone has a update about this Issue? Some example to how to handle this situation, @trevord1990.

**Comment by TCB13** [comment]
> Someone has a update about this Issue? Some example to how to handle this situation, @trevord1990.

Custom Group Columns solves this issue indeed, just look at the example on the link above. Then you can can use `api.setColumnVisible('name', false)` in order to hide your custom groups. Adding a `colId` to the definition is helpful.
