### ISSUE TITLE
how to remove cell renderer in pinned row data

### ISSUE THREAD

**Issue by mithun2003** [ag-grid/ag-grid#8001]
I create a client-side row model table and add pinned row data at the bottom. In that table, I create a cell renderer to create a serial number but that serial number is showing for this pinned data too so how do I remove it?
In this image there it shows 1 before the 'Total'
![Screenshot 2024-05-22 101720](https://github.com/ag-grid/ag-grid/assets/63800900/79882067-a3dd-4561-8c96-6b2d7fa25181)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
