### ISSUE TITLE
onRowSelected event : (event?: Event | null) is always null while clicking checkbox for selecting row when setting rowModelType "serverSide"

### ISSUE THREAD

**Issue by XijueYZ** [ag-grid/ag-grid#8008]
I'm submitting a ...

[x] bug report => see 'Providing a Reproducible Scenario'

Current behaviour:
In onRowSelected event -> onRowSelected event : (event?: Event | null) is always null while clicking checkbox for selecting row when setting rowModelType "serverSide"

Expected behaviour:
In onRowSelected event -> when row is selected via checkbox click, (event?: Event | null) should be returning Event object.

Providing a Reproducible Scenario:  https://codesandbox.io/p/sandbox/click-selection-forked-sc7hfk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwk45keh00063b6ipqv5eyq2%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwk45keg00023b6iyng5bne4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwk45keg00033b6i1gsc1wix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwk45keg00053b6i987oadas%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwk45keg00023b6iyng5bne4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwk45keg00013b6ivdqfq8i2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwk45keg00023b6iyng5bne4%2522%252C%2522activeTabId%2522%253A%2522clwk45keg00013b6ivdqfq8i2%2522%257D%252C%2522clwk45keg00053b6i987oadas%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwk45keg00043b6iay118tno%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwk45keg00053b6i987oadas%2522%252C%2522activeTabId%2522%253A%2522clwk45keg00043b6iay118tno%2522%257D%252C%2522clwk45keg00033b6i1gsc1wix%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwk45keg00033b6i1gsc1wix%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
AG Grid version: 31.1.1
Language: Javascript | React

**Comment by sabahang** [comment]
Hi @XijueYZ 

In the example above when I set onRowSelected on the grid using `onRowSelected={(e) => console.log(e)}` I can see the event object being printed in console as expected. Here is a fork of your own example:

https://codesandbox.io/p/sandbox/click-selection-forked-ywnlzd

If this doesn't resolve your issue please provide a minimal live code sample with a screenshot showing actual vs expected behaviour so that we can investigate further

Thanks

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
