### ISSUE TITLE
Function("return true") coming from AG-8451 throws CSP violation (script-src)

### ISSUE THREAD

**Issue by yossiyedid** [ag-grid/ag-grid#8011]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

*Providing a Reproducible Scenario
have a CSP header without 'unsafe-eval'.
I have version 30.1.0, tried 30.2.1 as well.

Current behaviour.
throws "Content Security Policy of your site blocks the use of 'eval' in JavaScript`"  CSP violation
the error points to the `return new Function("return true")` line code added here AG-8451

Expected behaviour. - no violation without usage of 'unsafe-eval'

**Please tell us about your environment:**
using chrome 125.0.6422.113, mac. 

* **AG Grid version:** 30.1.0

**Comment by AG-DavidG** [comment]
Hi @yossiyedid 

I believe that you have also submitted this issue on our support system. We will respond to you there.

Thanks 

David

**Comment by spearmootz** [comment]
i would like to know the outcome of this as i also have the same message.

**Comment by AG-Zoheil** [comment]
You can follow the development of this issue in our [AG Charts pipeline ](https://charts.ag-grid.com/pipeline/) under item AG-11744.
