### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by Eugeno** [ag-grid/ag-grid#8013]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

https://www.ag-grid.com/angular-data-grid/value-cache/

> ...no concern for expiring the **Calue Cache**. This example introduces...

I assume it's supposed to be "Value Cache"

**Comment by StephenCooper** [comment]
Thanks, I saw this get fixed in a recent pr which is soon to be merged so will be fixed with the next release.
