### ISSUE TITLE
Framework component is missing the method getValue() in production build but not development

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [ag-grid/ag-grid#8026]
If you're currently deploying a production environment with vue3+vite and you're experiencing the following issues, maybe the following can help you.

[Solution 1
](https://stackoverflow.com/questions/73032489/ag-grid-framework-component-is-missing-the-method-getvalue-in-production-buil)

Solution 2
```
<script setup>
//Each time you update the text entered by the user, you need to update the
 window.$text = props.params.value
</script>
<script>
export default {
  methods: {
    getValue() {
      return window.$text;
    },
  },
};
</script>
```

**Comment by guirak** [comment]
Hello, 

I'm encoutering the same problem but in development. I have tested solution 1 and 2. None of them solve the problem. 


```vue
<script setup lang='ts'>
[...]
const getValue = () : FieldValue => {
  return selected.value?.fieldValue;
}

window.$text = selected.value?.fieldValue
</script>

<script lang="ts">
export default {
  methods: {
    getValue() {
      return window.$text;
    },
  },
};
</script>
```

I have always the following error : 

```
AG Grid: Framework component is missing the method getValue()
```

**Comment by XiaoBaiClassmate** [comment]
@guirak Can you share your examples? Perhaps not understanding what I meant when I provided the example

**Comment by guirak** [comment]
Hi @XiaoBaiClassmate, thank you for reply. 

I have just found my problem. I was using : 

```typescript
const DataGridCellEditorReference = defineAsyncComponent(() =>
    // @ts-ignore
    import(`@mmiErpUiFwk/components/grid/DataGridCellEditorReference.vue`)
  )
  
  [...]
  
```
for the component. 

Changing to a simple import solve my problem : 

```typescript
import DataGridCellEditorReference from '@mmiErpUiFwk/components/grid/DataGridCellEditorReference.vue'
```

Regards,

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
