### ISSUE TITLE
Minimum version that supports new format column menu

### ISSUE THREAD

**Issue by rajitha-bandara** [ag-grid/ag-grid#8031]
**I'm submitting a 
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I want to add the column menu feature to React Grid. I'm using the enterprise version. Could you please mention from which Ag Grid version this feature is available?

Thank you

**Comment by sabahang** [comment]
Hi

Column menu has been part of the AG-Grid for a long time. Do you mean the new format column menu?

If you are an enterprise customer please reach out on support with your specific use case and we'd be happy to help

Best

**Comment by rajitha-bandara** [comment]
> Hi
> 
> Column menu has been part of the AG-Grid for a long time. Do you mean the new format column menu?
> 
> If you are an enterprise customer please reach out on support with your specific use case and we'd be happy to help
> 
> Best

Yes. I mean the new format column menu. I'm really sorry for the confusion, and I have updated the question.

**Comment by sabahang** [comment]
Hi.

Thanks for your reply. 

New column menu is supported from version 31.1.0

Hope this helps
