### ISSUE TITLE
[ag-grid] Date picker in the header filter is not closing on selection

### ISSUE THREAD

**Issue by saikmadana** [ag-grid/ag-grid#8042]
Hi,

I am using ag-grid in our react application application. I am using the `date` field and `agDateColumnFilter` for one of the columns. When I open the filter from the header and select a date, it does not close on selection. I have to manually click outside to close it. 

Versions:
```
"react": "^18.2.0",
"ag-grid-community": "^31.0.1",
"ag-grid-enterprise": "^31.0.1",
"ag-grid-react": "^31.0.1",
```

ColDef:
```
{
    headerName: "Last Updated On",
    field: "last_updated",
    sortable: true,
    type: "leftAligned",
    filter: "agDateColumnFilter",
    valueGetter: (params: any) => {
        return formatDate(params.data.last_updated);
    },
    filterParams: {
        comparator: dateComparator,
        minValidYear: 1900,
        maxValidYear: 3000,
    },
},
```

Grid:
```
<AgGridReact
    columnDefs={coldefs}
    rowData={data}
    pagination={false}
    defaultColDef={{
        wrapText: true,
        autoHeight: true,
        resizable: false,
        menuTabs: ["filterMenuTab", "columnsMenuTab"],
    }}
/>
```

Output (I have selected the date. It is not closing):
<img width="291" alt="Screenshot 2024-06-03 at 8 46 36 PM" src="https://github.com/ag-grid/ag-grid/assets/17292167/f1911b11-e7af-402d-8c72-42cd2b15626c">

Could you please look into it and let me know if I am making any mistakes?

Thank you in advance.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by saikmadana** [comment]
Hi @AG-Zoheil , 
Thanks for your reply. I think this kind of behaviour is due to using Safari browser where it uses the native date picker.
