### ISSUE TITLE
when upgrading aggrid package to latest 31.3.2 getting ./node_modules/ag-grid-enterprise/dist/package/main.esm.mjs Can't import the named export 'ALWAYS_SYNC_GLOBAL_EVENTS' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Akshay123dev** [ag-grid/ag-grid#8046]
./node_modules/ag-grid-enterprise/dist/package/main.esm.mjs
Can't import the named export 'ALWAYS_SYNC_GLOBAL_EVENTS' from non EcmaScript module (only default export is available)

my package.json looks like

{
  "name": "business-administration-client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@azure/msal-browser": "^2.19.0",
    "@azure/msal-react": "^1.1.1",
    "@fluentui/react": "^8.2.1",
    "@fluentui/react-hooks": "^8.0.2",
    "@fluentui/react-icons": "^1.1.135",
    "@fluentui/react-icons-mdl2": "^1.1.6",
    "@microsoft/sp-office-ui-fabric-core": "^1.13.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.2.1",
    "@types/chart.js": "^2.9.7",
    "@types/jest": "^24.0.24",
    "@types/node": "^12.12.21",
    "@types/react": "^18.0.0",
    "@types/react-adal": "^0.4.2",
    "@types/react-dom": "^18.0.0",
    "@types/react-router-dom": "^5.1.3",
    "@types/react-select": "^3.0.8",
    "apexcharts": "^3.36.0",
    "axios": "^0.19.0",
    "bootstrap": "^4.4.1",
    "botframework-webchat": "^4.8.1",
    "chart.js": "^2.9.3",
    "env-cmd": "^10.1.0",
    "history": "^4.10.1",
    "html-react-parser": "^1.4.0",
    "jodit-react": "^1.3.32",
    "jquery": "^3.4.1",
    "jquery-ui": "^1.12.1",
    "moment": "^2.24.0",
    "office-ui-fabric-react": "^7.164.0",
    "react": "^18.0.0",
    "react-adal": "^0.5.0",
    "react-apexcharts": "^1.4.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-bootstrap-table-next": "^4.0.3",
    "react-bootstrap-table2-editor": "^1.4.0",
    "react-bootstrap-table2-filter": "^1.3.3",
    "react-bootstrap-table2-paginator": "^2.1.0",
    "react-datepicker": "^2.10.1",
    "react-dom": "^18.0.0",
    "react-dropdown-tree-select": "^2.8.0",
    "react-icons": "^4.2.0",
    "react-paginate": "^8.1.0",
    "react-quill": "^1.3.5",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "4.0.3",
    "react-select": "^3.0.8",
    "react-table": "^7.0.0-rc.15",
    "react-vis": "^1.11.7",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "typescript": "^3.7.3"
  },
  "scripts": {
    "start": "set HTTPS=true&&react-scripts start",
    "start:prod": "set HTTPS=true&&env-cmd -f .env.production react-scripts start",
    "start:dev": "set HTTPS=true&&env-cmd -f .env.development react-scripts start",
    "build": "react-scripts --max_old_space_size=4096 build",
    "build:dev": "env-cmd -f .env.development npm run build",
    "build:prod": "env-cmd -f .env.production react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@ag-grid-devtools/cli": "^31.3.0",
    "ag-grid-community": "^31.3.2",
    "ag-grid-enterprise": "^31.3.2",
    "ag-grid-react": "^31.3.2",
    "sass": "^1.49.7"
  }
}

<img width="626" alt="Screenshot 2024-06-04 172817" src="https://github.com/ag-grid/ag-grid/assets/171687601/5dc288a9-7fa3-4029-a9ce-d949c9d95f0c">

**Comment by ShrikaranKanagaraj** [comment]
For some reason my react-scripts version was 3.x.x and that was causing the problem. By upgrading `"react-scripts": "^5.0.1"` will solve your problem.

It may help, mate.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
