### ISSUE TITLE
Row duplication issue after server side refresh

### ISSUE THREAD

**Issue by jpsla94** [ag-grid/ag-grid#8047]
**I'm submitting a ...**
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support

**Current behavior**
After move row inside already existing group, row gets added to group but not removed from top level grid after refresh gets trigger.

**Expected behavior**
Refresh top level grid and group level grid. without duplicating lines in top level grid after row has been grouped.

* **AG Grid version:** 31.0.3

* **Browser:** chrome 125.0.0

* **Language:** [ES6]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
