### ISSUE TITLE
Enhance Flexibility for Pagination Page Size in AG Grid

### ISSUE THREAD

**Issue by minaairsupport** [ag-grid/ag-grid#8058]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
AG Grid strictly adheres to the page size set for pagination, which poses a challenge in scenarios where the number of rows per page needs to be dynamically adjusted based on additional rows like headers and footers for each location.

**Expected behavior**
Introduce an option to dynamically adjust the page size on the client side before rendering the data in the grid. This flexibility will allow for a dynamic number of rows per page, which can include additional rows like headers and footers.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
 30.0.0

* **Browser:**
125.0.6422.142 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.1

* ** Use Case:**
In our application, each page must include a header and a footer row for each unique location. This means the total number of rows per page can vary. For example, if we request 10 rows from the backend, we need to dynamically adjust the number of rows to 12 or 14, etc., to accommodate these additional header and footer rows.

* **Proposed Solution:**
Introduce an option to dynamically adjust the page size on the client side before rendering the data in the grid. This can be achieved by allowing developers to provide the total number of items for pagination while being able to adjust the rows per page dynamically.

* **Benefits:**

This feature will offer greater flexibility for developers to handle dynamic data scenarios.
It will enhance the usability of AG Grid in complex applications where the number of rows per page cannot be predetermined.
Workaround:
While it is possible to manually adjust the row data and manage pagination logic, having built-in support for this feature will simplify the implementation and reduce the potential for errors.

Thank you for considering this enhancement. AG Grid is an excellent tool, and this added flexibility will make it even more powerful and versatile for various use cases.

**Comment by AG-Zoheil** [comment]
Hi 

Thanks for getting in touch via GitHub.

We are currently not considering feature requests via GitHub and we do not believe there is an underlying issue with this feature from a UX perspective. This does not mean we will not consider improvements to this area of the grid in the future.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
