### ISSUE TITLE
Indentation issue for WPS spreadsheet and Google sheets For Exported to Excel file.

### ISSUE THREAD

**Issue by Pratik38237** [ag-grid/ag-grid#8061]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
![Example](https://github.com/ag-grid/ag-grid/assets/171224453/20152ec7-017c-43d4-b7d7-53d1b3997954)

Kindly refer to below attached example link.
[Plunker Example](https://plnkr.co/edit/4ImFJSkVQ2VhOJcY?open=app.component.ts)
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
While exporting to excel, and previewing on **WPS spreadsheet and Google sheets** user is unable to get the **indentation**
![Example(1)(1)](https://github.com/ag-grid/ag-grid/assets/171224453/4c84e6d1-8396-40af-b1ec-90520aabda04)

**Expected behavior**
While previewing on **WPS spreadsheet and Google sheets** user should be able to get the **indentation** the exported to excel file.

**Please tell us about your environment:**
OS: Windows
IDE: VSCode
Package Manager: NPM

* **AG Grid version:** 
* 31.1.1

* **Browser:**
* Chrome, Firefox, Edge

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* Typescript 5.2.2

**Comment by sabahang** [comment]
Hi Pratik

On my side using your Plnkr I'm able to open the exported file in Google Sheet and still see the indentation. Could you elaborate the issue a bit further or produce exact steps and ACTUAL vs EXPECTED behaviour 

![image](https://github.com/ag-grid/ag-grid/assets/2657540/e7bde696-0674-4c09-bd85-502991c8c486)

**Comment by Pratik38237** [comment]
Hi Sabahang,

I guess we are having some misunderstanding here, the indentation I am referring to as of now is shown in the image attached below,

And we are facing issue on WPS and Google Sheets, but not on MS Excel,
in the below image on right hand side MS Excel and on the left hand side WPS ( also same issue can be faced on Google sheets)

![image](https://github.com/ag-grid/ag-grid/assets/171224453/189ac029-c969-4fb6-84b2-6e0c92002ab1)

Thanks,
Pratik

**Comment by sabahang** [comment]
Thanks for reply.

We generate the exported file according to the Excel file format. It's up to other spreadsheets to support the format. If AG Grid exports a file, and Excel opens it correctly but WPS/Google Sheets doesn't, it's an issue in WPS/Google Sheets. Please contact their support regarding this matter

Best
