### ISSUE TITLE
word break on space

### ISSUE THREAD

**Issue by meghna786** [ag-grid/ag-grid#8065]
I am using the following two properties to text wrap element,

"wrapText": true,
"autoHeight": true

but the work break does not happen on space. Instead word is breaking anywhere in between- attaching screen shot for same.
I want the word to break on space only.

![text-wrap](https://github.com/ag-grid/ag-grid/assets/66870732/4e29473b-11d7-43ae-b3ab-5f597f2ea868)

**Comment by AG-Zoheil** [comment]
Hi @meghna786,

This is working on v31.3.1 as you can see here: https://plnkr.co/edit/MVE0jpn5glqC5ccN?open=main.js.

If you are still having issues, please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

Kind regards,
Zoheil
