### ISSUE TITLE
Client side javascript grid with rowSelection single allowing multiple selections

### ISSUE THREAD

**Issue by verdant-spark** [ag-grid/ag-grid#8079]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**
I have a grid with rowSelection: "single" in the gridOptions; there is no other declaration for row selection anywhere. When I select a row it is correctly highlighted and I get the callback with the row data, but when I select a different row the first row remains selected (I get the callback for the 2nd row). This is whether I use checkboxes or not - the first selected row does not deselect and I have to ctrl+click the row to deselect it. It still appears to be a single selection - the callback for the 2nd row only returns an array with 1 child, but the row presentation is selected.

**Expected behavior**
I'd expect it to behave as per the docs and example plunker - single row selection automatically deselectes any prior selected row.

**Please tell us about your environment:**
LAMP stack, with vanilla javascript.

* **AG Grid version:** 
31.3.2

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by verdant-spark** [comment]
Thank you, kind internet stranger, but it turns out I'm an idiot who forgot to change the reference to the row ID...
