### ISSUE TITLE
AgGridReact: Issue inserting row and then calling startEditingCell

### ISSUE THREAD

**Issue by adriangraham** [ag-grid/ag-grid#8086]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker: 

Here is a plunker reproducing the issue: https://plnkr.co/edit/fLc3ysUqwKTBO00f?open=index.jsx

If reporting a bug make sure to state.

Current behaviour.
- Click "Add Row"
- Observe row is added to bottom of table and scrolled into view expected, but first cell of new row is not in edit mode (even though startEditingCell has been called in the onRowDataUpdated callback) 

Expected behaviour. If possible back this up with our docs/examples if possible
- Click "Add Row"
- New row has been added at the bottom of the table, scrolled into view, and first cell in new row is in edit mode

Please Note: If there is only a small number of rows in the table (e.g. 3), this works as expected.

**Please tell us about your environment:**

* **AG Grid version:** 31.3.2

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Tested in ES6/7

**Comment by sabahang** [comment]
@adriangraham thanks for your question

Due to the async nature of how React works, the cell that `ensureIndexVisible` scrolls to is not immediately ready for cellEditing to work. We are aware of this and are looking for improvements but meanwhile you could wrap `startEditingCell` inside a `setTimeout `with delay of 0 to ensure it runs after cell is rendered.
