### ISSUE TITLE
How can we dynamically update the value of the number filter input to display letters in a specific format?

### ISSUE THREAD

**Issue by vandanaag09** [ag-grid/ag-grid#8087]
**I'm submitting a ...**  AG-Grid version 31.1.1
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
When a user types into a number filter input field, I need to ensure that both letters and digits are formatted in the EU style.

**Current behavior**
It is showing the digits as 2000.
![image](https://github.com/ag-grid/ag-grid/assets/172420226/f5a7653d-d881-478d-825e-ced90316cab3)

**Expected behavior**
 It should show digits as 2.000 as per EU format or 2,000 as per Indian format

On the grid column, i am able to show this format, same need to show on filter input

![image](https://github.com/ag-grid/ag-grid/assets/172420226/1612b972-ffb6-4dfe-b80c-c152efb40694)
**Please tell us about your environment:**

* **AG Grid version:** 31.1.1

* **Browser:**
All Browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by sabahang** [comment]
Hi @vandanaag09 

Thanks for your inquirey.

We use standard html input filters which do not support formatting - if you wish to format you would need to use your own filter component

https://ag-grid.com/javascript-data-grid/component-filter/
