### ISSUE TITLE
Issue with Pinning Columns in Tree Data View

### ISSUE THREAD

**Issue by Maddy-O** [ag-grid/ag-grid#8096]
I am encountering an issue with pinning a column to the left side in tree data view. As shown in the attached screenshot, I need to pin the "Gold" column to the left side of the grid, followed by the "Athlete" column. Both columns should remain pinned on the left side, with "Gold" first and "Athlete" second.

Please refer to the attached screenshot for clarification. How can I achieve this?

![column pinning position](https://github.com/ag-grid/ag-grid/assets/95930594/c580e561-9bf7-4172-815d-84aa67003e2c)

**Comment by sabahang** [comment]
@Maddy-O this is not possible with Auto Group Col out of the box but you could use a custom code like this:
https://plnkr.co/edit/qhX0dKBYFuOUy4vV?open=main.js

Hope this helps
