### ISSUE TITLE
SSRM ->Get all Downloaded data in TS file(Angular)

### ISSUE THREAD

**Issue by harshkoralwala** [ag-grid/ag-grid#8111]
For client-side filtering and sorting, there is a method like _forEachNodeAfterFilterAndSort_, which iterates on all rows irrespective of whether the row is on the current page or not.

But the same function does not work for SSRM (serverSideDatasource attribute of ag-grid), it iterates on only displayed records i,e 25 records only, same result with other iteration methods as well!

In my scenario, 1000 records are downloaded with SSRM and passed to the grid via **IServerSideDatasource** to ag-grid, and on a page size of 25, they are displayed(pagination)...

I want all of the data in the TS file(1000 records) to implement the next/previous row selection from external buttons.

How can I see all downloaded records? I.e 1000 records, not only current page data...

I searched a lot but I couldn't find any solution. Can anyone share how I can get all the data in the TS file? Any patch?

Thanks in advance.

_Note_:i know SSRM is lazy loaded...

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
