### ISSUE TITLE
How to set the height of the table based on the displayed data in ag-grid-vue3

### ISSUE THREAD

**Issue by YSHgroup** [ag-grid/ag-grid#8116]
And I have one more question regarding the ag-grid. Could you please let me know how I can customize the height of the table?

It seems the table has only initial height and immutable rely on the status.

```
<ag-grid-vue
        :defaultColDef='defaultColDef'
        style='width: 100%; height: 350px;'
        class='ag-theme-quartz
        :columnDefs='columnDefs'
        :rowData='rowData'
        rowSelection='multiple'
      >
```

But I need to customize the table so that the height depends on the displayed data.
Same question: https://stackoverflow.com/q/78422235/23055206

**Comment by AG-Zoheil** [comment]
Hi @YSHgroup,

Please see this page of our documentation: https://grid-staging.ag-grid.com/javascript-data-grid/grid-size/.

Kind regards,
Zoheil
