### ISSUE TITLE
How to prevent the delay in adjusting the width of grid ?

### ISSUE THREAD

**Issue by Manuvk11** [ag-grid/ag-grid#8117]
**Description of the Issue :**
The grid width is resizing automatically to fit the screen and it takes some time to revert back to the normal width. This delay in adjusting the width is causing issues in the user experience. I need to prevent this delay and have the width adjust immediately.

**Steps to Reproduce**
Initialize an ag-Grid instance with a set width.
Resize the browser window or the grid container to trigger the grid's width adjustment.
Observe the delay before the grid width returns to the normal state.

**Expected Behavior**
The grid should adjust its width immediately without any noticeable delay when the screen or grid container is resized.

**Actual Behavior**
There is a noticeable delay before the grid width reverts to the normal state after the screen or grid container is resized.

**Environment**
ag-grid-react version: 29.1.0
ag-grid-community version: 29.1.0
React version: 17.0.2

![aggridResize](https://github.com/ag-grid/ag-grid/assets/121529520/737d9b4f-259c-41ac-af37-7ee8427ed067)
![image](https://github.com/ag-grid/ag-grid/assets/121529520/4b2df549-f620-43d8-86a6-ce2dd14280fb)

As you can see the 1st picture the width is not immediately adjusted , in the second picture the width is adjusted according to the grid options

How to overcome this noticeable delay and have a smooth user experience ?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
