### ISSUE TITLE
Version 31.2 breaks Enterprise types in Angular

### ISSUE THREAD

**Issue by b4ux1t3** [ag-grid/ag-grid#8123]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

___

I will be following this up with a request for support on Zendesk.

**Providing a Reproducible Scenario**
Unable to reproduce outside of primary application due to Enterprise licensing.

**Current behavior**

When upgrading from 31.0.2, the angular compiler throws an error anywhere there is a shared type between AG Grid Community and AG Grid Enterprise: 
![image](https://github.com/ag-grid/ag-grid/assets/5150833/8ec362a8-cbe4-4a31-b84a-b08234882324)
![image](https://github.com/ag-grid/ag-grid/assets/5150833/9383259a-39cf-481e-acdc-d878bfef9de1)

**Expected behavior**

The angular compiler successfully compiles the application, as pictured below in 31.1.1.
![image](https://github.com/ag-grid/ag-grid/assets/5150833/682d02c1-3a66-474b-889e-13bdb6587f5b)

**Please tell us about your environment:**

Linux Mint 21.3, Kernel 5.15.0-107-generic, VS Code, NPM v10.7.0, Node.JS 22.2
* **AG Grid version:** 31.2.1, 31.3.2

* **Browser:** Not applicable, build does not complete.

* **Language:** TypeScript/Angular

**Comment by b4ux1t3** [comment]
I reviewed the release notes for 31.2, and it doesn't appear that there are any issues that would cause this.

If there's something I'm doing wrong here (I've been upgrading AG Grid in our app now for about four years with no issues) let me know.

**Comment by AnthonyMastrean** [comment]
@AG-Zoheil you need to have this conversation in public so that all of your paying customers can see what's happening.
