### ISSUE TITLE
Ability To Add Custom Section Inside Builtin Tool Panel 

### ISSUE THREAD

**Issue by sauravgaursmith** [ag-grid/ag-grid#8124]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
**Current behavior**
We can add custom tool panel. But our need is to add a custom tool panel section just below column tool panel. 

**Expected behavior**
We want to achieve following design. This design have builtin Column Tool Panel's show / hide feature along with custom section as well. See Red border section we want to display.
![image](https://github.com/ag-grid/ag-grid/assets/25001992/a5558027-9e12-4bc3-b797-399ec5c6d0a1)

**Note**: we are using enterprie version. 

**Please tell us about your environment:**

* **AG Grid version:** 30.2.1

* **Language:** Angular v16

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we already have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-4307**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
