### ISSUE TITLE
How to implement expand/collapse row for ag-grid-angular with community version?

### ISSUE THREAD

**Issue by prashantapple** [ag-grid/ag-grid#8127]
Please help me to write a code in angular to expand/ collapse a row using ag-grid community version not the enterprise version.

Have to implement ag-grid-angular row - expand/collapse like rowGroup of enterprise. Here also have to add checkboxes for parent and Child but for now its optional.

Using following configurations:
- Angular v13.3.0
- ag-grid 29.3.3
- Window 10

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
