### ISSUE TITLE
Checkbox moving issue

### ISSUE THREAD

**Issue by 1uv0cean** [ag-grid/ag-grid#8134]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
![image](https://github.com/ag-grid/ag-grid/assets/53146391/21d4c607-1899-4f7c-80c8-8682b19be750)

Current behavior
When trying to double-click a checkbox to edit it, the checkbox moves slightly upwards.

Expected behavior
The checkbox should remain in place without any movement when double-clicking to edit. Refer to the AG Grid documentation on cell editors and checkboxes for expected behavior: AG Grid Checkbox Editor

Steps to reproduce:

Render a grid with a column using the CHECKBOX_DEF cell renderer and editor.
Double-click a checkbox in the grid to edit it.
Observe the checkbox moving slightly upwards.
Please tell us about your environment:

Operating system: macOS Ventura 13.3

IDE: Visual Studio Code

Package manager: npm 9.6.6

HTTP server: Node.js 21.7.1

AG Grid version: 31.3.2

Browser:
Chrome 125.0.0.0

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by 1uv0cean** [comment]
Sorry It was our custom css issue🥲
Thank you for your comment. Have a good day.
