### ISSUE TITLE
Allow headerClass to be combined from multiple column types

### ISSUE THREAD

**Issue by unfortunately-react** [ag-grid/ag-grid#8139]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

If multiple column types specify `headerClass`, they will override each other instead of combining.

```js
columnTypes = {
    typeA: { headerClass: 'type-a' },
    typeB: { headerClass: 'type-b' },
];

columnDefs = [
    { field: 'value', type: ['typeA', 'typeB'] },
];
```

**Current behavior**
Only `.type-b` will be applied to the header.

**Expected behavior**
An option is provided such as `appendHeaderClass` to allow a column type to not override other types or the column's own `headerClass`.

* **AG Grid version:** 31.3.2

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
