### ISSUE TITLE
`onColumnMoved` event not having updated `getColumns` state

### ISSUE THREAD

**Issue by gombosg** [ag-grid/ag-grid#8140]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
👉🏽  [Plunker](https://plnkr.co/edit/dJIaEKIzbSsgjCUF?open=main.ts) based on this [AG Grid example](https://www.ag-grid.com/javascript-data-grid/column-state/#column-events).

- Drag some columns left/right
- Watch console

**Current behavior**
When `onDragStopped` and `onColumnMoved` (when `finished`) events are fired, `api.getColumns()` still contains the old column ordering (even in a `setTimeout` as the [docs](https://www.ag-grid.com/javascript-data-grid/column-interface/#column-events) suggest).

`api.getColumnState()` contains the new column ordering, so we could use that in the event handler as a workaround.

**Expected behavior**
After a `setTimeout`, `getColumns` should probably contain the reordered column state.
At least, this was the behavior in earlier AG Grid versions.

* **AG Grid version:** 31.3.2

* **Browser:**
Latest Firefox & Chrome

* **Language:** all - language-independent issue

**Comment by AG-Zoheil** [comment]
Hi @gombosg,

Thanks for getting in touch via GitHub.

Please note that `getColumns` does not return any ordering.

What you are looking for is [`getAllGridColumns`](https://ag-grid.com/javascript-data-grid//grid-api/#reference-columns-getAllGridColumns).

I hope this helps.

Kind regards,
Zoheil
