### ISSUE TITLE
Webpack bundling issues not including all css files from ag-grid library

### ISSUE THREAD

**Issue by STEjovanovicFAN** [ag-grid/ag-grid#8162]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
I've upgraded ag-grid from v27 to v28. This upgrade broke some css. I've fixed the css problems. The issue is when webpack bundles the project I can see it doesn't include all the css from ag-grid. Requesting support for webpack bundling with the ag-grid library.

**Current behavior**
Currently when I run the ag-grid library in my solution it works as expected. The problem comes when I bundle the project in webpack. Some icons from the column filters are missing and look like squares.

**Expected behavior**
When I bundle the project using webpack that all css is included and I can see the missing icons.

* **AG Grid version:** X.X.X
28.2.1

**Comment by AG-Zoheil** [comment]
Hello,

Please see the below which should provide the required guidance on this:

https://www.ag-grid.com/javascript-data-grid/global-style-upgrading-to-v28-css/

Kind regards,
Zoheil
