### ISSUE TITLE
Can I edit the row cell data in the sidebar or custom panel?

### ISSUE THREAD

**Issue by codecodecookie** [ag-grid/ag-grid#8172]
I want to implement the effect of modifying a row of data in the custom tool panel, you know, select a row and then the sidebar shows all the data for the changed row, modifying the data just like editing in the cell, including some custom cellRender functions. 
      But I can't get the api or colomnApi by using the sidebar CustomStatsToolPanel component. How can I implement my functionality? Is there any easier way? Please tell me how to deal with this scene，thank you very much!

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
