### ISSUE TITLE
OnFilterChanged after processing data using setDataRows redrawRows, refreshCells update view all invalid, layout disorder

### ISSUE THREAD

**Issue by yangyusha177** [ag-grid/ag-grid#8197]
If reporting a bug make sure to state.
**Current behavior**After filtering, I processed the data to update the page by listening for the onFilterChanged event, and the layout was messed up.
![img_v3_02c9_2526fcb3-7d1c-4eee-a94c-317c6d94204g](https://github.com/ag-grid/ag-grid/assets/40791574/25334517-5b1f-41ff-a7a7-3e33fc7bde9b)

**Expected behavior**
Expected figure
In my page, cells with identical ids are grouped together, the first identical data set rowSpan is merged, and other identical data set merged as merged.
The view is updated by recalculating rowSpan and merged after filtering. 
![img_v3_02c9_6cc0b8b4-75d2-4696-8c66-02e699f5d88g](https://github.com/ag-grid/ag-grid/assets/40791574/85cd9560-2750-4a51-9d72-b9f26152b4f0)

**Please tell us about your environment:window10

* **AG Grid version:** 28.2.0

* **Browser:**chrome edge126.0.2592.68

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
