### ISSUE TITLE
Enquiry on support for column menu "legacy" design in future

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#8224]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

Since v31.1.0 column menu has been redesigned (**new**) & its mentioned it would be set to default in future. 
https://www.ag-grid.com/react-data-grid/grid-options/#reference-accessories-columnMenu

Hence, in future would **legacy** design continue to exist & be supported or will it be deprecated sometime ?

* **AG Grid version:** 31.1.0

**Comment by AG-Zoheil** [comment]
Hi,

As of `v32` (released today) the new column menu has been made default. You can read the below on how the legacy design can still be set:
https://www.ag-grid.com/javascript-data-grid/column-menu/#legacy-tabbed-column-menu

Kind regards,
Zoheil
