### ISSUE TITLE
[Bug] Column filters are attached below grid after recreation

### ISSUE THREAD

**Issue by skuwka** [ag-grid/ag-grid#8236]
Something is wrong with restoring filters since v30 of community edition.
When I recreate a filterState, these filters are attached below grid and opened by default.
To be sure, I've reused code from documentation:

```
    reloadGrid(): void {
        const state = this.gridApi.getState();
        this.gridVisible = false;
        this.cdRef.detectChanges();
        this.initialState = state;
        this.rowData = undefined;
        setTimeout(() => {
            this.gridVisible = true;
            this.cdRef.detectChanges();
        });
    }
```

![image](https://github.com/ag-grid/ag-grid/assets/174417409/730cc6c7-daef-4328-8b93-288bc94f071d)

**Comment by AG-Zoheil** [comment]
Hi @skuwka,

Thanks for raising this via Github. This issue should have been rectified via **AG-11633** in our latest version `v32` that was released yesterday. If you are still having issues with this after upgrading to` v32` please do get back to us and we can investigate further.

Kind regards,
Zoheil

**Comment by skuwka** [comment]
OMG, last few days up to 1PM to fix it...
Finally you did this. Thanks!

JK

wt., 2 lip 2024 o 10:52 AG-Zoheil ***@***.***> napisał(a):
