### ISSUE TITLE
gridOptionService sometimes converted to null in Custom Floating Filter

### ISSUE THREAD

**Issue by charmingjae** [ag-grid/ag-grid#8237]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
1. Create custom floating filter
2. Create a datagrid on each of Page A and Page B and apply custom floating filter
3. Move A and B using a router
4. Error occurred

**Current behavior**

![image](https://github.com/ag-grid/ag-grid/assets/54883521/23d64229-af84-4a44-95ae-802d643e9ea4)
![image](https://github.com/ag-grid/ag-grid/assets/54883521/e1e1ec75-d5f8-4e0b-9979-53349b4a34f2)
![image](https://github.com/ag-grid/ag-grid/assets/54883521/431ca28b-53de-44fe-b981-5edab7478ebe)

```javascript
  const testFetch = useCallback(
    newValue => {
      try {
        if (typeof props?.onModelChange === 'function')
          props?.onModelChange?.(
            newValue === ''
              ? null
              : {
                  ...((props?.model && props?.model) || {
                    type: 'contains',
                  }),
                  filter: newValue,
                },
          );
        else {
          console.log('On model change is not a function');
        }
      } catch (error) {
        console.error('Error in onModelChange : ', error);
      }
    },
    [props?.onModelChange],
  );

  const fetch = useMemo(() => debounce(testFetch, 1000), [testFetch]);
```

**Expected behavior**

No errors are thrown

**Please tell us about your environment:**

* **AG Grid version:** 31.1.1

* **Browser:**

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
JS

**Comment by AG-Zoheil** [comment]
Hi @charmingjae,

Thanks for raising this on GitHub.

Please always supply a reproducible scenario when reporting an issue as it is difficult to configure the grid to match your test case.

I have attempted to reproduce this below but I am unable to do so. If this does not match your configuration please fork and adjust the plunker and then send it back to us.

https://plnkr.co/edit/r4vYemm4p12Tasco?open=main.js

Thanks!

**Comment by charmingjae** [comment]
Hello @AG-Zoheil ,

First, let me say that I am eternally grateful for your interest.

Thankfully you sent a link to the plnkr, but I'm not familiar with it, so I'm reproducing it via codesandbox.

Configure issued environment link (Code sandbox) : [Link](https://codesandbox.io/p/sandbox/ag-grid-custom-floating-filter-rmvt56)

#### Scenario
1. When you launch Preview, there is a header at the top that allows you to move between ```Page A``` and ```Page B```. 
2. If you navigate back and forth between Page A and B ```Multiple times```, you'll get an error on the screen.
    - Move to ```Page A``` and move to ```Page B```, and move to ```Page A``` again like this.

#### Mention
- The first time I wrote this, the error was related to the ```get``` method, and in this example, the error is related to the ```getGridId```. After checking, it seems that the issue is with the ```gridOption```.
- I'm trying to implement the filter being applied by giving it a delay via ```debounce```, and the error seems to be the same in the ```onModelChange``` function. I would be very grateful if you could confirm.
- The above is my speculation and I hope the AG-Grid team will consider this issue.
- We have purchased a license and if you need information about the license, please contact me. 


#### Error image

![image](https://github.com/ag-grid/ag-grid/assets/54883521/5d6de96a-a7ea-4cd4-9f2d-ee8116bfa27f)
![스크린샷 2024-07-02 201541](https://github.com/ag-grid/ag-grid/assets/54883521/f647fe1a-bce9-473d-94d1-014026fca813)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for getting back.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Regarding the issue/question above, the way you have implemented your custom floating filter means you are always updating the filter model when your floating filter is created, but doing it with a 400ms delay. If you switch pages during that 400ms, it's then calling `onModelChange` on a destroyed grid.
 
We will certainly improve our error handling to deal with this more gracefully, but the solution here is to wrap the debounced `onModelChange` call with an `if (!props.api.isDestroyed()) { ... onModelChange... }`.
 

Kind regards,
Zoheil

**Comment by charmingjae** [comment]
@AG-Zoheil 

Thank you so much for your attention to the issue. I'll try to implement your suggestions.
Thank you.
