### ISSUE TITLE
Reopen #8224

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#8238]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

Hi @AG-Zoheil ,
https://github.com/ag-grid/ag-grid/issues/8224

Thank you for your response.

What I meant to ask was will Ag-Grid ever **deprecate** or stop supporting the "legacy" design in **future** ?

We prefer to use the legacy design in production applications and we don't want to risk incase if it deprecates in future.

**Comment by AG-Zoheil** [comment]
Hi @melon2504,

Apologies I didn't make that clearer.

For now there are no plans to deprecate or remove the legacy menu and it will be kept as an option.

Kind regards,
Zoheil
