### ISSUE TITLE
Ag Grid: Only one Grid displayed if multiple grids are needed to display on the screen.

### ISSUE THREAD

**Issue by sauravgaursmith** [ag-grid/ag-grid#8239]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
Yes. I'm an enterprise user of Ag Grid.

**Current behavior**
I am trying to use Ag Grid - Angular to display two grids inside a dialog. Only one Ag Grid is displayed (or intanciated).

Please have look at the attached image below:
![image](https://github.com/ag-grid/ag-grid/assets/25001992/858e69df-49dd-44aa-b1ae-9a7b83588def)

**Expected behavior**
Both Grid must be displayed.

**Please tell us about your environment:**

* **AG Grid version:** 30.2.1

* **Browser:**

Chrome: Latest

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular: 16.

**Comment by AG-Zoheil** [comment]
Hi @sauravgaursmith,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil
