### ISSUE TITLE
BUG REPORT: Dynamically apply filter for custom filter on first time after grid loads shows filter panel at bottom of grid

### ISSUE THREAD

**Issue by nikhil1793** [ag-grid/ag-grid#8241]
```
Dynamically apply filter for custom filter on first time after grid loads shows filter panel at bottom of grid
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Dynamically apply filter for custom filter on first time shows filter panel at bottom of grid. Click on `Invoke Filter Instance Method ` after loading of grid in below plunker.
- On First time button click, its shows the custom filter panel at bottom of grid. 
- After this if we apply the filter by clicking on the filter icon on grid column header its goes away and works fine.
- So, this issue is only replicable only on first attempt after the grid loads
- [Plunker link](https://plnkr.co/edit/K3WlIgis3y4Xh90r?open=app.component.ts&preview)

Current behavior.
Expected behavior. If possible back this up with our docs/examples if possible

**Current behavior**
Dynamically apply filter for custom filter on first time after grid loads shows filter panel at bottom of grid

**Expected behavior**
Dynamically apply filter for custom filter on first time after grid loads should not show filter panel at bottom of grid

**Please tell us about your environment:**
 - Operating system: Windows  
 - IDE: VS Code 
 - package manager: NPM
 - HTTP server: Angular dev server
 
* **AG Grid version:** 31.3.2

* **Browser:** Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

https://github.com/ag-grid/ag-grid/assets/12994269/32cf4941-d955-44fc-9efb-05f629c1a693

**Comment by nikhil1793** [comment]
Hi @AG-Zoheil,

Just wanted to check — does AG Grid have a bounty or cash bonus program for community contributions? Many companies offer such incentives to encourage efforts that help improve their products.

For reference, I’ve reported a few issues already and plan to continue contributing:

[Functional Issue 2](https://github.com/ag-grid/ag-grid/issues/8226)

[Functional Issue 3](https://github.com/ag-grid/ag-grid/issues/10846)

Looking forward to your response!

**Comment by AG-Zoheil** [comment]
Hi @nikhil1793,

Thank you for your contributions. AG Grid currently does not have any such schemes.

Kind regards,
Zoheil
