### ISSUE TITLE
Is possible focus text input cell pressing Tab button only once?

### ISSUE THREAD

**Issue by ascazzola** [ag-grid/ag-grid#8242]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

I want to navigate using single tab instead of double tab is that possible? I'm trying with the example on the docs but to focus in the first element in the cell I need to press tab twice. 

**Providing a Reproducible Scenario**
https://codesandbox.io/s/cnnnhw (Docs example)
https://codesandbox.io/p/sandbox/cell-renderer-keyboard-navigation-forked-hhj94n (Version that I'm using to try with only one single input)
**Current behavior**
I need to press "Tab" button twice to focus an input in a cell
**Expected behavior**
I want to navigate pressing "Tab" or arrows buttons only twice

* **AG Grid version:** 3.2.0
I have the same issue with older versions too

* **Browser:**
Chromium

* **Language:** [Typescript]

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
