### ISSUE TITLE
ag-grid-vue use jsx,tsx, cellRender error, use setup

### ISSUE THREAD

**Issue by epver** [ag-grid/ag-grid#8243]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

* **AG Grid version:** 32.0.0

* **Browser:**

* **Language:** [ES5]

[CodeSandbox](https://codesandbox.io/p/devbox/ag-grid-bug-m4wd88?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly48muv00007356kjwdqce0x%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly48muuz0002356kopvxo32x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly48muv00004356kfn13iv4t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly48muv00006356k4zqlj2m6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly48muuz0002356kopvxo32x%2522%253A%257B%2522id%2522%253A%2522cly48muuz0002356kopvxo32x%2522%252C%2522activeTabId%2522%253A%2522cly499fnk00yx356k4fstgycn%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly48muuz0001356ke2umvdp9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A51%252C%2522endLineNumber%2522%253A51%252C%2522startColumn%2522%253A5%252C%2522endColumn%2522%253A5%257D%255D%252C%2522id%2522%253A%2522cly499fnk00yx356k4fstgycn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cly48muv00006356k4zqlj2m6%2522%253A%257B%2522id%2522%253A%2522cly48muv00006356k4zqlj2m6%2522%252C%2522activeTabId%2522%253A%2522cly54qv0b002k356jwp8wa36r%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522cly54qv0b002k356jwp8wa36r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cly48muv00004356kfn13iv4t%2522%253A%257B%2522id%2522%253A%2522cly48muv00004356kfn13iv4t%2522%252C%2522activeTabId%2522%253A%2522cly548qiw0059356jjcifrag3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522cly548qiw0059356jjcifrag3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
![image](https://github.com/ag-grid/ag-grid/assets/8299627/a887b091-623e-4a92-921d-0dbbca4f95d1)

```vue
<script setup lang="jsx">
import { ref } from "vue";
import { ClientSideRowModelModule } from "@ag-grid-community/client-side-row-model";
import { ModuleRegistry } from "@ag-grid-community/core";
import "@ag-grid-community/styles/ag-grid.css";
import "@ag-grid-community/styles/ag-theme-quartz.css";
import { AgGridVue } from "@ag-grid-community/vue3";
ModuleRegistry.registerModules([ClientSideRowModelModule]);

function ratingRenderer(props) {
  const { value, isFilterRenderer } = props;
  if (value === "(Select All)") {
    return value;
  } else if (isFilterRenderer && value === 0) {
    return "(No stars)";
  }

  return (
    <span>
      {[...Array(5)].map((x, i) => {
        return value > i ? (
          <img
            class="invert-100%"
            key={i}
            src="@/assets/images/star.svg"
            alt={`${value} stars`}
            width="12"
            height="12"
          />
        ) : null;
      })}
    </span>
  );
}
const rowData = ref([
  { make: "Tesla", model: "Model Y", price: 64950, electric: true, star: 1 },
  { make: "Ford", model: "F-Series", price: 33850, electric: false, star: 3 },
  { make: "Toyota", model: "Corolla", price: 29600, electric: false, star: 5 },
]);

// Column Definitions: Defines the columns to be displayed.
const colDefs = ref([
  { field: "make", width: 120 },
  { field: "model", width: 120 },
  { field: "price", width: 120 },
  { field: "electric", width: 120, editable: true },
  { field: "star", editable: true, cellRenderer: ratingRenderer },
]);
</script>

<template>
  <div style="height: 100vh">
    <ag-grid-vue
      class="ag-theme-quartz"
      style="height: 100%; width: 100%"
      :rowData="rowData"
      :columnDefs="colDefs"
    />
  </div>
</template>

<style>
html,
body {
  padding: 0;
  margin: 0;
}
</style>
```

**Comment by epver** [comment]
if i use defineComponent , it will be run.
```jsx
const RatingRendererDC = defineComponent({
  name: 'RatingRendererDC',

  setup({ params }) {
    const { value, isFilterRenderer } = params
    if (value === '(Select All)') {
      return () => h(<>(Select All)</>)
    }
    else if (isFilterRenderer && value === 0) {
      return () => h(<>(No stars)</>)
    }

    return () => h(
      <span>
        {
        [...Array(5)].map((x, i) => {
          return value > i
            ? <img className="invert-100%" key={i} src="/star.svg" alt={`${value} stars`} width="12" height="12" />
            : null
        })
      }
      </span>,
    )
  },
})
```

but i like , use jsx,render

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12247**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by epver** [comment]
Ooo，Thanks
> From: ***@***.***>
> Date:  Mon, Jul 15, 2024, 22:54
> Subject:  Re: [ag-grid/ag-grid] ag-grid-vue use jsx,tsx, cellRender error, use setup (Issue #8243)
> To: ***@***.***>
> Cc: ***@***.***>, ***@***.***>
> Hello
> Thank you for the suggestion.
> Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.
> We have added this requirement to our backlog and we are tracking it with the following reference: AG-12247
> We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.
> See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
> https://www.ag-grid.com/ag-grid-pipeline/
> The best way to track this is to sign up for AG Grid new release notifications using the instructions here<https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications->. This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on the changelog page<https://www.ag-grid.com/ag-grid-changelog/>.
> Thanks again for bringing this up with us.
> Kind regards,
> 
Zoheil

**Comment by epver** [comment]
```jsx
const avatarRenderer = defineComponent(
  ({ params }) => {
    const { value } = params
    return () => {
      return (
        <span class="imgSpanLogo">
          <img src={value} class="logo" />
        </span>
      )
    }
  },
  {
    props: ['params'],
  },
)

```

I found this can be running
