### ISSUE TITLE
onlySelected property ignoring pinnedRows on export

### ISSUE THREAD

**Issue by krjk333** [ag-grid/ag-grid#8247]
I have a requirement to do excel export only with selected rows along with Pinned Rows. I am setting programmatically setSelected true for the rows what ever I need to export . I am using exportDataAsExcel() method to export. I am setting onlySelected as true and skipPinnedTop as false, still the top pinned rows are not getting exported.

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
