### ISSUE TITLE
Using showColumnMenuAfterMouseClick to show context menu on column header disappears after appearing in v31

### ISSUE THREAD

**Issue by AnnamalaiK** [ag-grid/ag-grid#8255]
We have an icon in grid column header(custom header template), on clicking of the icon we call `GridApi` method "**_showColumnMenuAfterMouseClick_**" to show the context menu. It was working fine till v30 but after upgrading to v31, the context menu appears but disappears immediately. I have used _event.preventDefault()_ and _event.stopPropagation()_ but no luck.

Can someone help me with this.? Is this is an issue with new version or I should do it differently.?

**Current behavior**
Header context menu disappears immediately after appearing

**Expected behavior**
Header context menu should not disappear

**Please tell us about your environment:**
Angular 15, windows

* **AG Grid version:** 
v31.0.0

* **Browser:**
Chrome

* **Language:** 
Typescript

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
