### ISSUE TITLE
Question about rowIndex

### ISSUE THREAD

**Issue by oooah** [ag-grid/ag-grid#8257]
**Requesting Community Support**
I want the serial number of all the data in the table, including the data that is not displayed. What should I do? Because after filtering, rowIndex is the serial number when it is displayed, which causes an error when I calculate the serial number

![QQ_1720084162261](https://github.com/ag-grid/ag-grid/assets/16513587/89a39977-7928-45df-a877-b9c62dc57263)

If I sort before this.setGridOption('rowData', n), it will waste performance, so I want to calculate the sequence number when rendering. I hope there is an API to get the sequence number of the current row in all the data, rather than the sequence number when it is displayed.

* **AG Grid version:** 
32.0.0

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
