### ISSUE TITLE
Change configuration to groupDisplayType={"multipleColumns"} before export

### ISSUE THREAD

**Issue by saikmadana** [ag-grid/ag-grid#8258]
I am using ag-grid in my application. 

I have grouped data in the grid using the concept like below:
![image](https://github.com/ag-grid/ag-grid/assets/17292167/e071a77a-b964-4b21-8c27-711519aa84d7)

When I export, I am getting the exported file and the grouped columns under `Group` with arrows `->` like below: 
` -> a11111 -> BOB -> AMR -> aaaaaaa -> NA -> bbb1`

<img width="431" alt="Screenshot 2024-07-04 at 2 55 08 PM" src="https://github.com/ag-grid/ag-grid/assets/17292167/ba4b53bd-4704-4a7b-a061-23251269c805">

<br/><br/>

So, I want the Group to be divided into separate columns which can be yield using 
`groupDisplayType={"multipleColumns"}` in the code.

But, I don't want to change the grid in the browser. I want to only change the exported excel file like below:

<img width="593" alt="Screenshot 2024-07-04 at 2 58 22 PM" src="https://github.com/ag-grid/ag-grid/assets/17292167/b8437f04-f7fd-4b0b-9cb9-47d7e9f6a1ed">

<br/>

Could someone please let me know how can I change the grid config so that the file will be exported into multiple columns.

<br/><br/>

Please help me with this.

Thanks in advance.

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
