### ISSUE TITLE
AgGridReact Component is not found when updating from V31 to V32

### ISSUE THREAD

**Issue by sachinchaubey** [ag-grid/ag-grid#8267]
Hii
I'm working on ag-grid react for my personal experience and learning purposes.
And I'm using the CDN link of **ag-grid-react.min.js from bundle** in version 31. And everything is working fine here is [link](https://plnkr.co/edit/Sd5ldVoEkOfaVmqk?open=lib%2Fscript.js).

Now I'm updating my version to 32v and I'm not found **ag-grid-react.min.js from bundle** because you guys are compressing the bundle and now I'm facing AgGridComponet not found error here is the [link](https://plnkr.co/edit/lq7ABhIPYJEow4sC?open=lib%2Fscript.js&preview).

Please provide ag-grid-react.min.js alternative cdn so that my problem can be solved in 32v.

**Comment by sachinchaubey** [comment]
@AG-Zoheil

**Comment by StephenCooper** [comment]
Please see all the available files from the package here.

https://www.jsdelivr.com/package/npm/ag-grid-react?tab=files

From there you will be able to find the alternative as we did rename some of the files.

**Comment by sachinchaubey** [comment]
> Please see all the available files from the package here.
> 
> https://www.jsdelivr.com/package/npm/ag-grid-react?tab=files
> 
> From there you will be able to find the alternative as we did rename some of the files.

hii actually I'm tried all the cdn but it still give AgGridReact Component not defined error link[](https://plnkr.co/edit/lq7ABhIPYJEow4sC?open=lib%2Fscript.js) here is the link

**Comment by sachinchaubey** [comment]
And I'm using the CDN link of ag-grid-react.min.js from bundle in version 31. And everything is working fine here is [link](https://plnkr.co/edit/Sd5ldVoEkOfaVmqk?open=lib%2Fscript.js).

Now I'm updating my version to 32v and I'm not found ag-grid-react.min.js from bundle because you guys are compressing the bundle and now I'm facing AgGridComponet not found error here is the [link](https://plnkr.co/edit/lq7ABhIPYJEow4sC?open=lib%2Fscript.js&preview).

This is my Code that I wanted to upgrade in 32v
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone@7.24.7/babel.min.js"></script>
    <script src="https://unpkg.com/prop-types@15.8.1/prop-types.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/ag-grid-community@32.0.0/dist/ag-grid-community.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/ag-grid-react@32.0.0/dist/package/index.cjs.min.js"></script>
    <title>Document</title>
</head>
<body>
    <div id='root'></div>

    <script type="text/babel">
        const { useEffect, useRef } = React;
    // import { AgGridReact } from 'ag-grid-react';

        const App = () => {
          const rowData = [
            { make: "Toyota", model: "Celica", price: 35000 },
            { make: "Ford", model: "Mondeo", price: 32000 },
            { make: "Porsche", model: "Boxster", price: 72000 }
          ];

          const columnDefs = [
            { headerName: 'Make', field: 'make' },
            { headerName: 'Model', field: 'model' },
            { headerName: 'Price', field: 'price' }
          ];

          const gridRef = useRef();

          useEffect(() => {
            console.log(gridRef);
          }, []);

          function onFirstDataRendered(params) {
            console.log("Grid is rendered");
            params.api.sizeColumnsToFit();
          }

          const gridOptions = {
            onFirstDataRendered: onFirstDataRendered,
            flex:1
          };

          return (
            <div className="ag-theme-quartz" style={{ height: 'calc(100vh - 100px)', width: 'calc(100vw - 200px)' }}>

              <AgGridReact.AgGridReact
                gridOptions={gridOptions}
                ref={gridRef}
                rowData={rowData}
                columnDefs={columnDefs}
              />
            </div>
          );
        };

        const root = ReactDOM.createRoot(document.getElementById('root'));
        root.render(<App />);
    </script>
</body>
</html>`

And I'm now attaching my console error, AgGridReact not found or defined.
![Screenshot from 2024-07-05 06-15-13](https://github.com/ag-grid/ag-grid/assets/77170139/28653943-bff8-4151-84a1-87171bc7b641)

**Comment by sachinchaubey** [comment]
And I'm using the CDN link of ag-grid-react.min.js from bundle in version 31. And everything is working fine here is [link](https://plnkr.co/edit/Sd5ldVoEkOfaVmqk?open=lib%2Fscript.js).

Now I'm updating my version to 32v and I'm not found ag-grid-react.min.js from bundle because you guys are compressing the bundle and now I'm facing AgGridComponet not found error here is the [link](https://plnkr.co/edit/lq7ABhIPYJEow4sC?open=lib%2Fscript.js&preview).

This is my Code that I wanted to upgrade in 32v
`HTML
<script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone@7.24.7/babel.min.js"></script>
    <script src="https://unpkg.com/prop-types@15.8.1/prop-types.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/ag-grid-community@32.0.0/dist/ag-grid-community.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/ag-grid-react@32.0.0/dist/package/index.cjs.min.js"></script>
<div id="root"></div>`
` //JSX
   <script type="text/babel">
        const { useEffect, useRef } = React;
        const App = () => {
          const rowData = [
            { make: "Toyota", model: "Celica", price: 35000 },
            { make: "Ford", model: "Mondeo", price: 32000 },
            { make: "Porsche", model: "Boxster", price: 72000 }
          ];

          const columnDefs = [
            { headerName: 'Make', field: 'make' },
            { headerName: 'Model', field: 'model' },
            { headerName: 'Price', field: 'price' }
          ];

          const gridRef = useRef();

          useEffect(() => {
            console.log(gridRef);
          }, []);

          function onFirstDataRendered(params) {
            console.log("Grid is rendered");
            params.api.sizeColumnsToFit();
          }

          const gridOptions = {
            onFirstDataRendered: onFirstDataRendered,
            flex:1
          };

          return (
            <div className="ag-theme-quartz" style={{ height: 'calc(100vh - 100px)', width: 'calc(100vw - 200px)' }}>

              <AgGridReact.AgGridReact
                gridOptions={gridOptions}
                ref={gridRef}
                rowData={rowData}
                columnDefs={columnDefs}
              />
            </div>
          );
        };

        const root = ReactDOM.createRoot(document.getElementById('root'));
        root.render(<App />);
    </script>
`

And I'm now attaching my console error, AgGridReact not found or defined.
![Screenshot from 2024-07-05 06-15-13](https://github.com/ag-grid/ag-grid/assets/77170139/28653943-bff8-4151-84a1-87171bc7b641)

@StephenCooper

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12124**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
