### ISSUE TITLE
Need a way to provide date format to ag-input-date-field

### ISSUE THREAD

**Issue by OysteinAmundsen** [ag-grid/ag-grid#8269]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**

```typescript
import { format, isValid } from 'date-fns';
import { Component } from '@angular/core';
import { GridOptions } from '@ag-grid-community/core';
import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
import { AgGridAngular } from '@ag-grid-community/angular';

export function millisToDate(num?: number | Date): Date {
  if (num == null || num instanceof Date) return num as Date;
  return (num != null ? new Date(num) : num) as Date;
}

export function dateToMillis(date?: Date | number) {
  if (date == null || typeof date === 'number') return date as number;
  return (date instanceof Date ? date.getTime() : date) as number;
}

@Component({
  selector: 'app-main',
  template: `<ag-grid-angular [rowData]="rowData" [gridOptions]="gridOptions" [modules]="modules"/>`,
  standalone: true,
  imports: [AgGridAngular]
})
export class MainComponent  {
  modules = [ClientSideRowModelModule];
  gridOptions: GridOptions = {
    dataTypeDefinitions: {
      millis: {
        baseDataType: 'dateString',
        extendsDataType: 'dateString',
        // Validate or convert the value to a number
        valueParser: (params: any) =>
          typeof params.newValue === 'number' ? params.newValue : dateToMillis(params.newValue),
        // Convert to string for presentation
        valueFormatter: (params: any) => (params.value == null ? '' : format(millisToDate(params.value), 'dd.MM.yyyy')),
        // Convert to date for editing
        dateParser: (value: any) => (value == null ? null : millisToDate(value)),
        // Convert to millis for saving
        dateFormatter: (value: Date) => (value == null ? '' : dateToMillis(value)),
        // Make sure that values of this type are numbers and can convert to a valid date
        dataTypeMatcher: value => typeof value === 'number' && isValid(millisToDate(value)),
      }
    },
    columnDefs: [ { field: 'fromMs', editable: true, cellDataType: 'millis' } ],
  };
  rowData = [{fromMs: null}, {fromMs: 0}, {fromMs: 1720186362046}];
}
```

**Current behavior**
This example grid holds one column of dates in  millis from epoch, but the same issue holds if I had used `cellDataType: 'date'` or `cellDataType: 'dateString`.

It presents the dates in the given format (`dd.MM.yyyy`), but when editing the value the editor can only edit in the default format (`MM/dd/yyyy`). This causes an cognitive overhead and is often reported in as a bug by our users.

The problem is nicely illustrated in your own guide to change the date format: https://www.ag-grid.com/javascript-data-grid/cell-data-types/#overriding-the-pre-defined-cell-data-type-definitions
In this guide, you've changed from `MM/dd/yyyy` to `dd/MM/yyyy`, which fixes the presentation of the data
![2024-07-08 07_47_20-JavaScript Grid_ Cell Data Types _ AG Grid](https://github.com/ag-grid/ag-grid/assets/1263104/92520d14-1243-4072-a4a1-dba1efbf8b2d)
but when invoking the editor, the default format is presented again
![2024-07-08 07_47_45-JavaScript Grid_ Cell Data Types _ AG Grid](https://github.com/ag-grid/ag-grid/assets/1263104/e8a87810-23df-4d0f-9439-503e06ef20e4)

**Expected behavior**
I understand that the editor cannot infer the desired date format from the `valueFormatter` alone, so a good solution would be to allow for configuration of the date pattern to use. Something like:
```typescript
  gridOptions: GridOptions = {
    dataTypeDefinitions: {
      millis: {
        ...
        datePattern: 'dd.MM.yyyy'
      }
    }
  }
```
If implemented, both the default cell renderer and the editor could take advantage of this configuration and convert properly to and from a string in the given date format pattern, which would simplify the configuration if all the developer wants to do is to change the date format. 

**Please tell us about your environment:**
Windows, VSCode, npm, Vite (I think - whatever server angular uses). 

* **AG Grid version:** 32.0.0

```
    "@ag-grid-community/angular": "^32.0.0",
    "@ag-grid-community/client-side-row-model": "^32.0.0",
```

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
```
"typescript": "5.4.3"
```

**Comment by AG-Zoheil** [comment]
Hi @OysteinAmundsen,

Thank you for raising this on GitHub.

Please note that we use the browser's default date editor, which means that what you see is just each browser's default behaviour for date editing. To illustrate this please see what the same AG Grid example you have linked above looks like for me when editing: 

![image](https://github.com/ag-grid/ag-grid/assets/132376454/f9c9ed5e-c232-4dea-b1d6-60b895a7c5e9)

If needed, you can create your own date components.

Kind regards,
Zoheil

**Comment by OysteinAmundsen** [comment]
That means that if I force the presentation into one format, I just have to pray that the users locale has the same format? Which again means that the presentation format is only usable if I set the column to not be editable or roll my own editor. Right?

**Comment by AG-Zoheil** [comment]
To remove any potential of being overridden by the user's locale you would need to provide your own component.
