### ISSUE TITLE
Help wanted ( not a bug ) Zoom Function on Ag Charts Map

### ISSUE THREAD

**Issue by H2Alchemist** [ag-grid/ag-grid#8273]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

How can i add zoom to AG charts Map ? I am adding pointers to the map but the latitude is so specific that i want to enable zooming into the map so that i can view the area in a larger scope for places where the pointer and markers are heavily clustered

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-DavidG** [comment]
Hi @H2Alchemist 

You can do this by adding `zoom: {enabled: true}` to the chart options.

All the zoom options will work on maps - see https://charts.ag-grid.com/javascript/zoom/ for more details.

Thanks

David

**Comment by H2Alchemist** [comment]
this is my implementation, yet i cannot get the map to zoom in 

```
"use client";
import { useEffect, useState } from "react";
import { usTopology } from "@/app/(main)/map-stats/us-topology";
import "ag-charts-enterprise";
// import { AgChartOptions } from "@ag-grid-enterprise/charts-enterprise";
import { AgChartsReact } from "ag-charts-react";
import { AgChartOptions } from "@ag-grid-enterprise/charts";

const numberFormatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  useGrouping: true,
});

const UsersUsMap = () => {
  const data = [
    { lat: 40.73061, lon: -73.935242, count: 3 },
    { lat: 40.73061, lon: -80.935242, count: 3 },
    { lat: 38.73061, lon: -81.935242, count: 3 },
    { lat: 39.73061, lon: -82.935242, count: 3 },
    { lat: 38.73061, lon: -83.935242, count: 3 },
    { lat: 41.73061, lon: -84.935242, count: 3 },
    { lat: 35.73061, lon: -85.935242, count: 3 },
  ];

  const [options, setOptions] = useState<AgChartOptions>({
    title: {
      text: "Users by State",
    },
    data,
    zoom: {
      enabled: true,
    },
    navigator: {
      enabled: true,
    },
    // topology: usTopology,
    series: [
      {
        type: "map-shape-background",
        topology: usTopology,
      },
      {
        type: "map-marker",
        colorKey: "color",
        latitudeKey: "lat",
        longitudeKey: "lon",
        sizeKey: "count",
        sizeName: "Count",
        size: 1,
        maxSize: 1,
      },
    ],
    gradientLegend: {
      enabled: true,
      scale: {
        interval: {
          minSpacing: 1,
          // @ts-ignore
          values: [0, 1e6, 2e6, 3e6, 4e6],
        },
        label: {
          fontSize: 9,
          formatter: ({ value }) => `$${Math.floor(+value / 1e6)}M`,
        },
      },
    },
  });

  return <AgChartsReact options={options} module={[]} />;
};

export default UsersUsMap;
```

**Comment by AG-DavidG** [comment]
Hi @H2Alchemist 

This works when I try it. You don't need `navigator`, but with the above code, scrolling with the mousewheel over the map zooms it in and out.

If this does not work for you, please share exact details of the actual and expected behaviour, as well as your browser, OS and library environments and versions.

Thanks

David

**Comment by H2Alchemist** [comment]
With the new updated packages i am not able to get the navigation with the '+' & '-' buttons to zoom, but it does work with the mousewheel

**Comment by AG-DavidG** [comment]
Hi

Thank you for submitting this on Github.

Zoom and Maps are enterprise features. As we do not provide support on Github but only take bug reports, I would encourage you to raise this via our support portal if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support and do NOT have an active AG Grid Enterprise licence, you can choose to raise the issue again for the AG Grid community to support.

Kind regards,

David
