### ISSUE TITLE
Error: Untracked input files in migrate command

### ISSUE THREAD

**Issue by lucaspmarra** [ag-grid/ag-grid#8281]
**I'm submitting a ...** 
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```
**Current behaviour.**
This will update your project's source files to prepare for the new release.

By default the Codemod runner will locate all source files within the current directory. For projects with more specific requirements, pass a list of input files to the migrate command, or specify the --help argument to see more fine-grained usage instructions.

**Current behavior**
After the command ```npx @ag-grid-devtools/cli@32.0 migrate --from=31.2.1```, error message Error: Untracked input files stop the process of migration.
```
The following files are not tracked within the current git repository:

 .quasar\dev-spa\app.js
 .quasar\dev-spa\client-entry.js
 .quasar\dev-spa\client-prefetch.js
 .quasar\dev-spa\quasar-user-options.js
 .quasar\prod-spa\app.js
 .quasar\prod-spa\client-entry.js
 .quasar\prod-spa\client-prefetch.js
 .quasar\prod-spa\quasar-user-options.js
 dist\spa\assets\ErrorNotFound-XuSg6Zhl.js
 dist\spa\assets\IndexPage-CQTHuvmU.js
 dist\spa\assets\LoginPage-Dqq_TFdk.js
 dist\spa\assets\MainLayout-C29Y4CA7.js
 dist\spa\assets\QInnerLoading-CtslEW51.js
 dist\spa\assets\ag-theme-quartz-EoExq0ye.js
 dist\spa\assets\apollo-Ca3vgWy5.js
 dist\spa\assets\auth-store-BsdhQyyJ.js
 dist\spa\assets\axios-DAXgZTaF.js
 dist\spa\assets\axios-QRTakdF2.js
 dist\spa\assets\bus-CBhmh0b9.js
 dist\spa\assets\config-store-CsNnnd2z.js
 dist\spa\assets\global-components-B5Giie6r.js
 dist\spa\assets\i18n-CtDPTo11.js
 dist\spa\assets\i18n-DFbOZQmZ.js
 dist\spa\assets\index-DSDj74le.js
 dist\spa\assets\index-_Jp20j89.js
 dist\spa\assets\index-yxA1iudD.js
 dist\spa\assets\reports-store-DeYV0DCN.js
 dist\spa\assets\store-DLNUUEsY.js
 quasar.config.ts.temporary.compiled.1716550729271.mjs
 quasar.config.ts.temporary.compiled.1716554690725.mjs
 quasar.config.ts.temporary.compiled.1716554785829.mjs
 quasar.config.ts.temporary.compiled.1719327165019.mjs

To operate on untracked files, use the --allow-untracked option
```

Those are all auto-generated files and not recommend to touch, this CLI needs a way to ignore untracked files or some other action.

* **AG Grid version:** 32.0.0
* **Vue version:** 3.4.18
* **Quasar version:** 2.6.0

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12173**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
