### ISSUE TITLE
AG-12064 is in backlog...?? 32.0.0 feels prematurely released

### ISSUE THREAD

**Issue by jpike88** [ag-grid/ag-grid#8283]
AG-12064 is a serious bug, it breaks across all our table components. also, overlay behavior has changed and feels weird... this is the more unstable major release.

**Comment by AG-Zoheil** [comment]
Hi @jpike88,

Thank you for your feedback via GitHub.

Our teams spare no effort in continuing to deliver upgrades and fixes to the world's best JavaScript data grid. As you know, the world of software development has ups, downs, twists and turns. AG-12064 is one that we didn't catch but not to panic, a patch fixing this and several other issues will be released this week.

Thank you for your understanding!

Kind regards,
Zoheil

**Comment by eugeniobet** [comment]
Shame on you Ag-Grid.
