### ISSUE TITLE
Tooltip from cell renderer doesn't display line breaks

### ISSUE THREAD

**Issue by dominikkurenda** [ag-grid/ag-grid#8299]
[x] bug report

Tooltip from setTooltip in cellRenderer doesn't display break line symbols.
![image](https://github.com/ag-grid/ag-grid/assets/49497440/74315053-839c-49a6-a8a8-e4643876e4bb)

Link to plunker: https://plnkr.co/edit/HXDlAAaFn9rHKwsY?preview

Current behaviour.
Tooltip from setTooltip in cellRenderer doesn't display break line symbols.

Expected behavior:
It should display break line symbols.

Please tell us about your environment
Angular 18 - AG Grid version 31.3.2

**Comment by AG-Zoheil** [comment]
Hi @dominikkurenda,

Thanks for getting in touch via GitHub.

Please note that tooltips are escaped by default. Please use a custom tooltip to achieve your desired outcome: https://ag-grid.com/javascript-data-grid/tooltips/#custom-component.

Kind regards,
Zoheil
