### ISSUE TITLE
Preserve rowCollapsedState using Hide open parents and export to Excel

### ISSUE THREAD

**Issue by ppatliak** [ag-grid/ag-grid#8306]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello AgGrid team,

I'm facing an issue using groupHideOpenParents property and exporting to Excel. While exporting, I apply rowGroupExpandState: 'match' and groupHideOpenGroups on my grid. I hope to see collapsed rows group state in exported Excel file, but every time my Table in Excel is fully expanded. You can see the issue here - https://plnkr.co/edit/GbYhlNkf2ecW4ld1?open=main.ts . Just try to export it and check row group expand status. If I use groupHideOpenGroups ={false} everything works. Could you please support row group expand state when groupHideOpenGroups  is true? Thanks in advance! 

**Please tell us about your environment:**
Windows11, Visual Studio Code, yarn

* **AG Grid version:** 31.1.0+

* **Browser:**
Google Chrome
* **Language:** TypeScript 5.3

**Comment by AG-Zoheil** [comment]
Hi,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

You can read about getting started with both community or enterprise versions of our grid on [this page](https://ag-grid.com/javascript-data-grid/getting-started/). Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

Do let us know if you have any other questions.

Kind regards,
Zoheil

**Comment by ppatliak** [comment]
Hello Ag Grid team! 

Thank for your answer! We already using enterprise version and this still does not work. Thanks one more time.

**Comment by AG-Zoheil** [comment]
Hi @ppatliak,

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil
