### ISSUE TITLE
v31 to v32 migration: how to get `eGridDiv` from `onCellEditRequest` event

### ISSUE THREAD

**Issue by tagliala** [ag-grid/ag-grid#8310]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

> [!NOTE]
> I'm not a javascript developer

Hello,

during the migration from v31 to v32, I'm not able to understand from the changelog or the upgrading guide how to access the main grid element where I store some data options.

This was working on v31, but I can't find an alternative on v32.

```js
const cellEditRequest = function (event) {
  // ...
  const myKey = event.api.gos.eGridDiv.dataset.myKey
  // ..
```

**Current behavior**

```
TypeError: Cannot read properties of undefined (reading 'eGridDiv')
```

**Expected behavior**

Be able to access the `eGridDiv` somehow through `event` or `event.api`

I can see that now `gos` is private, and the `eGridDiv` is in something called `beans` but I cannot access that

![image](https://github.com/ag-grid/ag-grid/assets/556268/85f1e710-4496-4918-ac00-95047804dd5b)

**Please tell us about your environment:**

* **AG Grid version:** 32.0.1

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

* **Language:** 
ES6

**Comment by nikolastojanovictt** [comment]
Many features have been shifted to 'beans'. You can find eGridDiv in event.node.beans.eGridDiv.

**Comment by tagliala** [comment]
Thanks, that fixed my issue.

Are beans somehow documented?

**Comment by StephenCooper** [comment]
Beans are very much internal to the grid and in using them there is no guarantee that we will not change this each release. 

> Are beans somehow documented? Are they considered internal API?

I would recommend getting the div from the Dom via javascript as opposed to going through these private properties. In a future release all private properties will become unavailable.

**Comment by tagliala** [comment]
Thanks for your answer.

We can use other solutions, like moving the shared data to the row (will increase json size), but I can clarify the use case

> I would recommend getting the div from the Dom via javascript as opposed to going through these private properties. In a future release all private properties will become unavailable.

Getting the element from the DOM may not be ideal in our use case because we are using a [Stimulus](https://stimulus.hotwired.dev/), so we do not have an ID reference like `#ag-grid`, or we may have multiple references per page

We have something like:

```
<div data-controller="ag-grid"></div>
```

```js
  // Stimulus
  initialize () {
    this.agGrid = someInitCode(this.element)
  }

  disconnect () {
    this.agGrid.then((agGrid) => agGrid.destroy())
  }
```

It means that at the moment `cellEditRequest` is called, we rely on the `event` to get the exact grid the event has been fired to get some extra options from the element's `dataset`, without trying to guess by a search in the DOM

To avoid beans, I've switched to 

```
const eGridDiv = document.querySelector(`[grid-id="${event.api.getGridId()}"]`).closest('[data-controller*=ag-grid]')
```

but this can break if we rename the stimulus controller or if `ag-grid` changes `grid-id` to something else.

It would be helpful to have a public accessible reference to the DOM element, or maybe an alternative approach better than the one I've switched to

**Comment by danielmalaton** [comment]
How can we get the `beans` from `gridApi`. It seems to return a function if accessing `gridApi.beans`

**Comment by Bhanuprakash111** [comment]
Currently I am doing `params.node.beans.gos.gridOptions.rowData`, is there a better approach to get the `gridOptions.rowData` ?

**Comment by StephenCooper** [comment]
@Bhanuprakash111 yes there is a better way to access gridOptions

> Currently I am doing `params.node.beans.gos.gridOptions.rowData`, is there a better approach to get the `gridOptions.rowData` ? 

https://www.ag-grid.com/javascript-data-grid/grid-api/#reference-gridOptions-getGridOption
