### ISSUE TITLE
Is there a way to stop the row drag using an external event?

### ISSUE THREAD

**Issue by davidyang** [ag-grid/ag-grid#8313]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Is there a way to stop the row drag while it's in motion?  I'd like to emulate Notion's behavior where if you're dragging and hit Escape it cancels the drag.  I've tried rowNode.setDragging(false) on the active RowNode being dragged but I don't think that's what tells the grid to stop dragging.

Looking deeper it looks like the gridBodyCtrl.getRowDragFeature uses a dragAndDropService - but it doesn't feel right to be mucking around in the internals of ag-grid that way.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by weissale1** [comment]
Hey, has there been a solution to this question?
