### ISSUE TITLE
AG-Grid date filter localization

### ISSUE THREAD

**Issue by souravdey91** [ag-grid/ag-grid#8315]
Hello All,
I am trying to translate the calendar values in filter to the respective language. Currently I am using German language. I have added the config for the month and days in my translated json file.

**Current behavior**
Month name, days name not getting translated to German

![Screenshot (10)](https://github.com/ag-grid/ag-grid/assets/163119535/c42484ac-24eb-4cb6-a572-871fab43cd69)

![Screenshot (9)](https://github.com/ag-grid/ag-grid/assets/163119535/b5fc0232-3a76-44b0-8a72-3a013353196d)

**Expected behavior**
Month name, days name should be translated to German language.
For example : July should be displayed as Juli in German

**Please tell us about your environment:**

* **AG Grid version:** 31.0.0

* **Browser:** Google chrome

**Comment by antonGritsenko** [comment]
Same story.
Also setting  
```
// Date Filter
  dateFormatOoo: 'dd.mm.yyyy',
```
do nothing at all.

PS Worst localization engine I've ever seen actually.....

**Comment by antonGritsenko** [comment]
OK, it using date picker from the browser, so localization will depend on browser's language.
You must implement custom date picker to support localization matched to the current in the grid.
