### ISSUE TITLE
bug report paginationPageSize dropDown is not showing the number when custom paginationPageSize is given

### ISSUE THREAD

**Issue by siva1b3** [ag-grid/ag-grid#8333]
paginationPageSize dropDown is not showing the number when custom paginationPageSize is given 
example 
""
<AgGridReact
        rowData={HomePageGridData}
        columnDefs={columnDefinitionForHomePageGrid}
        pagination={true}
        rowSelection={"single"}
        paginationPageSize={15}
        onRowClicked={(event) => onRowClicked(event)}
        getRowId={getRowId}
      />
 ""
 i can't see 15 in my paginationPageSize drop down

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
