### ISSUE TITLE
column pinning not working when pinned column's width is more than viewport width

### ISSUE THREAD

**Issue by ashray17aman** [ag-grid/ag-grid#8335]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I noticed an anomaly where you have an ag grid table and have say 5 pinned columns [1,2,3,4,5] which stick to the left followed by 5 unpinned columns [6,7,8,9,10] which are scrollable,

If the width of the pinned columns is more than the available space for the grid. So in that case, ag grid automatically makes the first few columns of the pinned section unpinned and and pushed them at the end of the list of pinned columns. i.e. it’ll be something like this → pinned cols is [3,4,5], followed by [1,2,6,7,8,9,10]

A minimal example of which is on this url - https://plnkr.co/edit/ht8ck3RjR9kv4HEZ?open=main.ts

in the above example first 6 columns are pinned starting from ‘#’ to ‘date’ and since the width of the viewport isn’t sufficient to show all the pinned cols and some area to show the scrollable cols, it puts the first 2 columns at the start of scrollable cols and makes them scrollable.

Depending upon the available width, more columns are picked from the start of pinned cols and put at the end of it making them unpinned as the result of which the column order also get’s changed from what’s specified in column definition.

**Expected behavior**
The expected behaviour would be that instead of picking up ‘n’ number of cols from the start, it should pick up ‘n’ columns from the end of pinned cols and make them unpinned. In that case, the order of the columns won’t change. Just the number of pinned cols would be dynamically set if there isn’t enough space available to accommodate them in unpinned manner. 

if the viewport width was sufficient enough to capture all the pinned cols and show scrollable cols, it would have worked as expected.

**Please tell us about your environment:**
MacOs, chrome browser

* **AG Grid version:** 32.0.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

https://github.com/user-attachments/assets/0046e637-a065-48a8-9f53-8dde3070a63b

**Comment by AG-Zoheil** [comment]
Hi @ashray17aman,

This is the intended behaviour. Horizontal scrolling inside pinned areas is only needed when the total width of pinned columns exceeds the width of the viewport. AG Grid handles this case by automatically unpinning pinned columns starting from the left until the total width of pinned columns is less than the width of the viewport, thus allowing the display of unpinned columns.

You can use https://www.ag-grid.com/javascript-data-grid//grid-options/#reference-columnPinning-processUnpinnedColumns to adjust this based on your requirements.

Kind regards,

**Comment by ashray17aman** [comment]
@AG-Zoheil shouldn't the expected behavior be that the automatic unpinning of columns should happen from right edge of the pinned columns?
In the current approach, the order of the columns change unexpectedly which is quite undesirable. If some of the pinned columns from the end get unpinned when there's space crunch that would still be better than having the columns get shuffled.

**Comment by abxhr** [comment]
Do we have a fix for this coming soon? 😅
