### ISSUE TITLE
Default Header tooltip displayed when hovering over set filter values in Filter Tool Panel

### ISSUE THREAD

**Issue by melon2504** [ag-grid/ag-grid#8337]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In following example, custom tooltip component is used. And showTooltips is set to true for setFilter values.
But when hovering on filter values via Filter tool panel, the **default** header tooltip is also shown. Its shown everywhere when hovered inside the filter tool panel.

https://plnkr.co/edit/wczNM0LSoRYDPa5U?open=index.tsx&preview

![Gif](https://github.com/user-attachments/assets/1966b3b8-e107-48aa-a985-5824ca3f88c0)

**Expected behavior**

Header tooltip should be only shown when hovered over header and not other places.

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
32.0.2

* **Browser:**
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-11497**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
