### ISSUE TITLE
[Theme builder] Theme import has a wrong filter-tool indent class

### ISSUE THREAD

**Issue by Rlamotte** [ag-grid/ag-grid#8338]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
* Using AG Grid Theme builder, download the base theme
* Install the CSS files locally
* Run an AG Grid with Filter tool panel activated
* the expected padding left for filter's group is  broken by the `ag-filter-toolpanel-group-level-1-header` class, as shown below :
![image](https://github.com/user-attachments/assets/57be9c2c-139a-489b-bbf5-d0a137735af0)

**Current behavior**
The children appear without indent : 
![image](https://github.com/user-attachments/assets/085ace54-8595-4d74-9ec9-3d8af6cdd531)

**Expected behavior**
The children appear with the indentation-level multiplied by the ag-filter-tool-panel-group-indent variable (+ base grid size variable) : 
![image](https://github.com/user-attachments/assets/4633df51-129f-481c-820f-2782eed19d93)

**Please tell us about your environment:**
Angular App (v17) with Nx hosted on a WSL.

* **AG Grid version:** 32.0.1

* **Browser:**
* Chrome/126.0.0.0

* **Language:** [TypeScript 5.3.3]

**Comment by BernieSumption** [comment]
Hello,

Thanks for reporting this issue, we've reproduced it and will work on a fix. The ticket number is AG-12407 and you can check progress of the fix in the pipeline page (it should be on there within an hour) - https://www.ag-grid.com/pipeline/

In the mean time, as a workaround you can remove the rules targeting `.ag-filter-toolpanel-group-level-1-header` from the downloaded theme. The file is minified so to edit it without breaking things it may be easiest to just search and replace the two instances of the string `ag-filter-toolpanel-group-level-1-header ` with e.g. `xx-removed-incorrect-rule-xx`.
