### ISSUE TITLE
ValueGetter will break the RowGroup

### ISSUE THREAD

**Issue by Archer03** [ag-grid/ag-grid#8339]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**
ColumnDef:
{
  field: 'col1', rowGroup: true, valueGetter: params => params.data.col1 + '!'
}
this will break the UI
unless to check if data is undefined like: params.data?.col1

* **AG Grid version:** 31.3.1

**Comment by AG-Zoheil** [comment]
Hi @Archer03,

Thanks for getting in touch via GitHub.

That is the expected behaviour. See it documented here: https://ag-grid.com/javascript-data-grid//column-properties/#reference-columns-valueGetter

Kind regards,
Zoheil
