### ISSUE TITLE
onClick on selection of rows/ cells

### ISSUE THREAD

**Issue by meghna786** [ag-grid/ag-grid#8340]
Is there any way to add onClick event handler on selection of row or cells for master/ detail grid?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
