### ISSUE TITLE
How to get the DOM element of AG Grid?

### ISSUE THREAD

**Issue by skyming97** [ag-grid/ag-grid#8341]
**Description**：How to get the DOM element instance of the Grid in AG Grid React?
![image](https://github.com/user-attachments/assets/83ba278a-e4f8-41cb-a4b6-004caf167999)

**Reproduction URL**: https://codesandbox.io/p/sandbox/zen-bhabha-yp3vr3?file=%2Fsrc%2FGrid.tsx%3A74%2C1

Regards!

**Comment by ddaeyongee** [comment]
Using this, Setting Up the Ref
```
const gridRef = useRef(null);
```
You can accessing the DOM Element.

this is my prj, I hope this helps!
```
import React, { useEffect, useRef, useState } from 'react';
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';

const MembersInfoPage = () => {
    const apiRef = useRef(null);
    const gridRef = useRef(null);
    const [rowData, setRowData] = useState([]);
    const [currentPage, setCurrentPage] = useState(1);
    const [pageSize, setPageSize] = useState(10);
    const [gridHeight, setGridHeight] = useState(400);

    const fetchData = async () => {
        // Fetch data logic
    };

    useEffect(() => {
        fetchData();
    }, [currentPage, pageSize]);

    useEffect(() => {
        if (apiRef.current) {
            apiRef.current.autoSizeColumns();
        }
    }, [rowData]);

    useEffect(() => {
        if (gridRef.current) {
            // Access the DOM element
            const gridElement = gridRef.current;
            console.log(gridElement);

            // Example: Adding a class to the grid element
            gridElement.classList.add('custom-grid-class');
        }
    }, []);

    return (
        <div className="ag-theme-alpine" style={{ height: gridHeight + 'px' }}>
            <AgGridReact
                ref={gridRef}
                rowData={rowData}
                onGridReady={(params) => {
                    apiRef.current = params.api;
                }}
                columnDefs={[
                    {
                        field: 'select',
                        headerName: '',
                        width: 27,
                        checkboxSelection: true,
                        headerCheckboxSelection: true,
                        headerCheckboxSelectionFilteredOnly: true,
                        suppressMenu: true,
                        suppressSizeToFit: true,
                        suppressMovable: true,
                        suppressSorting: true,
                        suppressFilter: true,
                    },
                    { field: 'memberNo', headerName: 'M_NO', width: 100 },
                    // Other column definitions...
                ]}
            />
        </div>
    );
};

export default MembersInfoPage;
```

**Comment by rupeshdeotale97** [comment]
I'm facing same issue mentioned by @skyming97 any suggestions

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by jy14898** [comment]
ddaeyongee's solution doesn't work - there's no difference between the problem stated and their solution. In my version of ag-grid-react (30.1.0), the ref prop provides the grid api only, not the node. It's not clear to me what version is needed to fix this.

**Comment by ddaeyongee** [comment]
@jy14898 
I used version of ag-grid-react, 31.1.0.
[https://blog.ag-grid.com/tag/version-release/]
Refer to the above blog and think about how to access it using the grid ref.

**Comment by webbower** [comment]
I'm having the same problem. In `package.json`
```json
"ag-grid-community": "32.3.3",
"ag-grid-react": "32.3.3",
```

Using similar code to yours, the ref I get from `<AgGridReact ref={...} />` is an `AgGridReact` instance (screenshot from inside of a `useEffect()` hook):

```jsx
const ref = useRef(null);

return (<AgGridReact ref={ref} />);
```

<img width="299" height="269" alt="Image" src="https://github.com/user-attachments/assets/6074dc34-26fb-4b65-bfd3-f02a000d7c77" />

This aligns with the AG Grid docs https://www.ag-grid.com/react-data-grid/grid-interface/#grid-api

**Comment by webbower** [comment]
The solution/workaround I figured out was to find it using native DOM APIs and using `api.getGridId()` in the `onGridReady` handler:

```jsx
const gridRoot = useRef(null);

const onGridReady = ({ api }) => {
  gridRoot.current = document.querySelector(`.ag-root-wrapper[grid-id="${api.getGridI()}"]`);
};

return (<AgGridReact onGridReady={onGridReady} />);
