### ISSUE TITLE
Consider supporting prefixing all class names, including those dynamically generated in JavaScript. Similar to antd's ConfigProvider prefixCls property.

### ISSUE THREAD

**Issue by 521guyu** [ag-grid/ag-grid#8342]
Consider supporting prefixing all class names, including those dynamically generated in JavaScript. Similar to antd's ConfigProvider prefixCls property?
Or is there any other solution to prefix all class names with our own custom prefix?

My scenario is that when using qiankun to integrate micro applications, the sub-application uses a different version of ag-grid than the main application, which causes styling issues. Ant Design has prefixCls to solve this problem effectively. I searched the ag-grid documentation but couldn't find a similar property. If you have any ideas or better solutions, could you please provide some guidance?

**Comment by AG-Zoheil** [comment]
Thanks for getting in touch via GitHub.

We are currently not considering feature requests via GitHub and we do not believe there is an underlying issue with this feature from a UX perspective.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
