### ISSUE TITLE
No longer can access gridOptions on agGrid demos/docs

### ISSUE THREAD

**Issue by jrod567** [ag-grid/ag-grid#8347]
[x] support request => see 'Requesting Community Support'

Hi - I've been using the AgGrid examples to exercise the gridOptions api for a while now, however in recent weeks, this is no longer available.

For example, using angular tree-data mode example here:
* https://www.ag-grid.com/angular-data-grid/server-side-model-tree-data/

The ag-root-wrapper div element used to contain a __agComponent property that gave easy access to the api, here:
* 
![image](https://github.com/user-attachments/assets/50d6c07f-d4d9-4076-aaf4-6b38c5f6392b)

This is no longer available in recent weeks.  Is there another way we can access the gridoptions api through these demo's?  Any help is most appreciated!

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
