### ISSUE TITLE
In server side data mode, not supported groupHideOpenParents

### ISSUE THREAD

**Issue by Darkells** [ag-grid/ag-grid#8349]
**Requesting Community Support**
I'm not sure if groupHideOpenParents is supported in server side data mode，it is strongly requested to be able to support or achieve similar data display effects in server side data mode.

**Current behavior**
In server side data mode, not supported groupHideOpenParents and configuring it at the same time will cause the export of csv or excel to function abnormally

**Expected behavior**
I try to configure multipleColumns in server side data mode

**Please tell us about your environment:**
react

* **AG Grid version:** 
v32.0.2

* **Browser:**
Google

* **Language:**
Typescript

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-2389**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
