### ISSUE TITLE
How to specify a custom date format for the date filter

### ISSUE THREAD

**Issue by abhi747** [ag-grid/ag-grid#8350]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I'm using `agDateColumnFilter` to filter date strings. I have a custom comparator to filter the dates. The dates being displayed on the UI are with `yyyy-mm-dd` format. The `agDateColumnFilter` invokes browser's native date picker to filter date on the column. The placeholder on it as well as the for the selected filter date, the format is `dd-mm-yyyy`. Is there a way to specify a custom format for it, like `yyyy-mm-dd` to match the format of dates displayed in the rows?

<img width="318" alt="Screenshot 2024-07-16 at 8 41 12 PM" src="https://github.com/user-attachments/assets/49e316d5-f7ae-4ded-baa9-01ad8e8cd372">

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by bogdanS-e** [comment]
@AG-Zoheil  are you kidding us? You didn't reply to the answer. It's a real problem. How to change the date format in the picker?

**Comment by AG-Zoheil** [comment]
Hi,

Please note that we do not provide support on Github. AG Grid community users can post to help each other and tag the request as "Requesting community support" just like the original poster has done.

You can find out more about custom date filter components in our documentation here: https://www.ag-grid.com/react-data-grid/filter-date/#date-selection-component.

Additionally we have a FR for "Allow custom date format to be specified for the input when using a date filter" with the following reference: **AG-3735**

Kind regards,
Zoheil

**Comment by arjun1607** [comment]
@abhi747 did you find any workaround for this?

**Comment by lehoangnam1410** [comment]
@arjun1607 Do you have a solution for this problem?

**Comment by arjun1607** [comment]
@lehoangnam1410 yes i implemented custom date component using flatpickr. 
refer the answer to this -
https://stackoverflow.com/questions/79435192/how-to-change-date-format-in-date-filter/79437165#79437165
https://flatpickr.js.org/formatting/

when u initialize the flatpickr u can specify the date format 
```
this.picker = flatpickr(this.flatpickrEl.nativeElement, {
            onChange: this.onDateChanged.bind(this),
            dateFormat: 'd/m/Y',
            wrap: true,
        });
```
