### ISSUE TITLE
Multiline group header cells with auto height

### ISSUE THREAD

**Issue by vothanh306** [ag-grid/ag-grid#8353]
**I'm submitting a ...** 
```
[] bug report
[] feature request
[x] support request
```

**Current behavior**
The height of group header cells is fixed and can be changed with setGroupHeaderHeight, but there is no option to set it automatically depending on the text content. There are options: autoHeight=true for rows and autoHeaderHeight=true for header cells but not for group headers.

**Expected behavior**
I'd like to have group header cells with height set dynamically depending on the necessary space to display all the text.

**Please tell us about your environment:**
Window 11 Enterprise
VS Code
npm

* **AG Grid version:** 29.3.5

* **Browser:** All browsers

* **Language:** TypeScript 4.8.3

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
