### ISSUE TITLE
(Angular) HeaderComponent option with base template does not work

### ISSUE THREAD

**Issue by khaslinger-bp** [ag-grid/ag-grid#8355]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour:
Current docs suggest you can provide your own component and use the default ag-grid template with data-ref attributes to get the same behaviour:
https://www.ag-grid.com/angular-data-grid/column-headers/#provided-component

**Current behavior**
If you provide the template as a headerComponentParams -> template option, it does work as the example at https://www.ag-grid.com/angular-data-grid/column-headers/#provided-component also shows.
However, if you put the same template in it's own component, and provide that as a headerComponent to the column definition it does not work anymore.

No label is shown, no sorting buttons etc. Basically non of the `data-ref` work was described in the docs.

See this short demo which is a fork of the docs with the template option transferred onto a component:
https://codesandbox.io/s/header-template-forked-w98tpv?file=/app.component.ts:0-3771

**Expected behavior**
Putting the base template into it's own component should restore basic AG-Grid Header functionality f.e. showing the label, showing sorting icons etc. if `data-ref` is used as described in the docs.

**Please tell us about your environment:**
See plunker above

* **AG Grid version:** X.X.X

AG Grid Version: 32.0.0, Angular 18
Plunker uses AG Grid Version: 32.0.2, Angular 17, same issue

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by sabahang** [comment]
Hi @khaslinger-bp 

As per docs:
https://ag-grid.com/javascript-data-grid/column-headers/#reference-IHeaderParams-template

In the case of using an external custom component the value of `template` is undefined. data-refs are only used for internal grid templating (not external components) so they will only work if you are using only a custom template for internal templating (not an entirely external template)

Hope this helps

**Comment by sabahang** [comment]
The example here should cover all the basic functionalities. Have you tried this and ran into any issues?

**Comment by euge** [comment]
Im also having the same issue. It seems that if i provide a headerComponent, i have to implement handling for sorting as well as rendering sort icons, etc. Is this the case?

**Comment by raghavendra89** [comment]
One solution is you can use the [Inner Header Components](https://www.ag-grid.com/angular-data-grid/column-headers/#inner-header-component).

```
headerComponentParams : {
    innerHeaderComponent: MyInnerHeaderComponent,
    innerHeaderComponentParams: {
        currencySymbol: '£' // the pound symbol will be placed into params
    }
}
```

This will render your `MyInnerHeaderComponent` inside the `data-ref="eText"` element. You can also provide the `template` option to completely customize the rendered header HTML.
