### ISSUE TITLE
Copying Cell Ranges Error: From XLS to AgGrid

### ISSUE THREAD

**Issue by HubFer** [ag-grid/ag-grid#8357]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

1) Go to https://www.ag-grid.com/javascript-data-grid/clipboard/#copying-cell-ranges
2) Copy A1 and A2 (Ctr+C) from AgGrid:
      Michael Phelps
      Michael Phelps
3) Paste into a XLS file
4) Copy again from the XLS those two cells
5) Paste into A1 in AgGrid.
6) A3 is now deleted. The copied range for some reason includes an extra empty row at the end.

**Expected behavior**

It should paste the same information coming from the xls.

**Please tell us about your environment:**

Testing directly from the example at https://www.ag-grid.com/javascript-data-grid/clipboard/#copying-cell-ranges

* **AG Grid version:** X.X.X

Ag Grid 32.0.1

* **Browser:**

Edge and Chrome, same error.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for getting in touch via GitHub.

Please use this property: https://ag-grid.com/javascript-data-grid/grid-options/#reference-clipboard-suppressLastEmptyLineOnPaste

Kind regards,
Zoheil
