### ISSUE TITLE
ag-grid not support server-side pagination grouping？

### ISSUE THREAD

**Issue by webzqy** [ag-grid/ag-grid#8359]
**server-side has 10000 records**，I want pagination，ag-grid rendering 10 records。
eg: 
const [columnDefs, setColumnDefs] = useState([
    { field: "country", rowGroup: true, hide: true },
    { field: "sport"}
  ]);

What format of data does the server need to return？

The examples on the official website all return all data, I need to paginate and return them？？？

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
