### ISSUE TITLE
AG Grid Integrated Chart doesn't support X-axis label

### ISSUE THREAD

**Issue by JerryPan2718** [ag-grid/ag-grid#8361]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

In the demo examples [here](https://www.ag-grid.com/react-data-grid/integrated-charts-range-chart/#example-defining-categories-and-series), there are no supported x-axis label, i.e. age in this case. We're wondering whether x-axis label is supported and how to add in this option if it's supported. 

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

- We cannot find a way to support x-axis label.

**Expected behavior**

- We can support x-axis label.

**Please tell us about your environment:**

- Macbook M2 MacOS 13.2.1
- VS Code
- node v20.11.0

* **AG Grid version:** X.X.X

```
"@ag-grid-community/client-side-row-model": "^31.3.2",
    "@ag-grid-community/core": "^31.3.2",
    "@ag-grid-community/react": "^31.3.2",
    "@ag-grid-community/styles": "^31.3.2",
    "@ag-grid-enterprise/charts": "^32.0.1",
    "@ag-grid-enterprise/charts-enterprise": "^31.3.2",
    "@ag-grid-enterprise/row-grouping": "^31.3.2",
    "@ag-grid-enterprise/status-bar": "^31.3.2",
```

* **Browser:**

```
'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36'
```

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript:
```
tsc --version
Version 5.3.3
```

**Comment by adam-wang-uk** [comment]
Hi Jerry, 

You can enable the axis titles either from the Customisation panel -> Title -> Horizontal Axis Title, or via ThemeOverride. 

https://charts.ag-grid.com/themes-api/#reference-AgChartTheme-overrides-common-axes-category-title-enabled

Kind regards,
Adam
