### ISSUE TITLE
I have Nested  data structure for tree data . How to render tree with nested structure in ag grid?

### ISSUE THREAD

**Issue by vandanaag09** [ag-grid/ag-grid#8364]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Hi Team,

I have data structure like this.

data =[
  {
    "ProjectId": 1000,
    "OrganizationId": 1,
    "ProjectNumber": "Smart Plus",
    "ShortName": "MFH 11 WE",
    "ProjectDescription": "Mehrfamilienwohnhaus mit 11 WE \n90425 Haselmühle",
    "Children": [
      {
        "ProjectStadiumId": 1002,
        "ProjectStadiumNumber": "vdfce_1000",
        "ProjectStadiumTypeName": "Order",
        "ShortName": "MFH 11 WE 2 - Auftra",
        "CreatedDate": "2024-07-18T09:02:18.35",
        "StadiumTypeId": 2,
        "Comment": null,
        "IsPin": false,
        "CanDelete": true,
        "IsStadiumFreezed": false,
        "StadiumFreezedBy": null
      }
    ]
  },
  {
    "ProjectId": 1001,
    "OrganizationId": 1,
    "ProjectNumber": "Smart Plus 1",
    "ShortName": "MFH 11 WE 1",
    "ProjectDescription": "Mehrfamilienwohnhaus mit 11 WE \n90425 Haselmühle 1",
    "Children": [
      {
        "ProjectStadiumId": 1003,
        "ProjectStadiumNumber": "vdfce_0001",
        "ProjectStadiumTypeName": "Offer",
        "ShortName": "MFH 11 WE",
        "CreatedDate": "2024-07-18T09:02:18.317",
        "StadiumTypeId": 1,
        "Comment": null,
        "IsPin": false,
        "CanDelete": true,
        "IsStadiumFreezed": false,
        "StadiumFreezedBy": null
      }
    ]
  }
]
**Expected behavior**
How can i create tree data with this data ?

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

You can read about getting started with both community or enterprise versions of our grid on [this page](https://ag-grid.com/javascript-data-grid/getting-started/). Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

Do let us know if you have any other questions.

Kind regards,
Zoheil
