### ISSUE TITLE
onclick of expand icon of detail-master grid

### ISSUE THREAD

**Issue by meghna786** [ag-grid/ag-grid#8365]
Hi is there any way to attach a on click handler on the expand icon of master grid?
I did tried onClickCallback but it attaches handler on cells not on the icon

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
