### ISSUE TITLE
Integrated Ag Charts common series overrides property is missing

### ISSUE THREAD

**Issue by lucaspmarra** [ag-grid/ag-grid#8366]
**I'm submitting a ...**  
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The property `series` from the `common` `chartThemeOverrides` object in the `createRangeChart` (Integrated Charts) function is missing, and there is no mention of it in the changelog (or did I miss it?).

I am migrating from ag-Grid v31.x.x to v31.x.x and ag-Charts v9.x to v10.x. I am using the `GridOptions` interface in `shallowRef`, which allows me to check the implementations, but I cannot verify the correct usage of this theme override. It seems to have disappeared.

After the migration, I received the following error:
`Vue: Object literal may only specify known properties, and series does not exist in type AgCommonThemeableChartOptions`

* **AG Grid versions:** 
"ag-charts-community": "^10.0.0",
 "ag-charts-vue3": "^10.0.0",
"ag-grid-vue3": "^32.0.0",

* **Language:** Vue.js 3

**Comment by adam-wang-uk** [comment]
Hi Lucas,

`series` isn't a property in the`common` object in the latest version of AG Charts. It wasn't documented in version 9 API docs either so there might have been some confusion. 

Please take a look at the API documentation for more details. 

https://charts.ag-grid.com/themes-api/#reference-AgChartTheme-overrides-common

Regards,
Adam
