### ISSUE TITLE
Undocumented breaking change in v32: overlayNoRowsTemplate now MUST be parseable HTML

### ISSUE THREAD

**Issue by timheilman** [ag-grid/ag-grid#8373]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Mainly reporting because this was not listed in the breaking changes for v32, but upgrading from v31 to v32 broke my app. Just trying to be a good netizen.
Regarding this example:
https://www.ag-grid.com/javascript-data-grid/overlays/#custom-no-rows-overlay
For "overlayNoRowsTemplate", although the doc does say "Provide a HTML string", I had been providing a text string.
In v30 and v31 this functioned.
In v32.0.1 and v32.0.2 this causes this error and crashes the app:
`TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.` 

**Expected behavior**

Simply that the breaking changes for v32 at https://www.ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-32/ mentioned this breaking change.

**Please tell us about your environment:**

MacOS, VS Code, npm, vite

* **AG Grid version:** X.X.X

Undocumented breaking change in v32.

* **Browser:**

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 5.4.2

**Comment by StephenCooper** [comment]
Hi @timheilman,

This sounds like the bug we fixed in 32.0.1. Here is an example using 32.0.1 that provides a simple string to the `overlayNoRowsTemplate`.

https://plnkr.co/edit/JSNrtxiM2b0GBtYH?open=main.ts

**Comment by timheilman** [comment]
Thank you for your response @StephenCooper ! It encouraged me to dig further.  It turns out my app crash breakage upgrading to v32 was because the string I passed was sometimes empty.  This forked plunker shows the exception:

https://plnkr.co/edit/oWvyj1qZWrc6yPf7?open=main.ts

**Comment by AG-Zoheil** [comment]
Hello @timheilman,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12359**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by StephenCooper** [comment]
> Thank you for your response @StephenCooper ! It encouraged me to dig further. It turns out my app crash breakage upgrading to v32 was because the string I passed was sometimes empty. This forked plunker shows the exception:
> 
> https://plnkr.co/edit/oWvyj1qZWrc6yPf7?open=main.ts

Out of interest, are you trying to achieve a specific behaviour with the no rows overlay and an empty string? Or was this just something that happens with your app?

**Comment by timheilman** [comment]
> Out of interest, are you trying to achieve a specific behaviour with the no rows overlay and an empty string? Or was this just something that happens with your app?

I was just moving too fast.  There was no reason to use `""` rather than `undefined`; I just happened to use the former instead of the latter without thinking.

Here was the actual code block before upgrading to v32 (I was on v30):

```
<AgGridReact
          getRowId={agGridRowId}
          rowData={tableRows}
          columnDefs={columnDefs}
          defaultColDef={{ resizable: true }}
          overlayNoRowsTemplate={
            unassignTableStatus === "inFlight" ? t("clubDevices.loading") : ""
          }
        />
```

`t` is provided by `react-i18next`; it is a translation function.  Here's what is working with v32.0.2:

```
        <AgGridReact
          getRowId={agGridRowId}
          rowData={tableRows}
          columnDefs={columnDefs}
          defaultColDef={{ resizable: true }}
          overlayNoRowsTemplate={
            unassignTableStatus === "inFlight"
              ? `<span>${t("clubDevices.loading")}</span>`
              : "<span/>"
          }
        />
```

Now that we've narrowed down the issue, this is working too, and is what I should have done from the start.  I was just surprised v32 broke things, is all:

```
<AgGridReact
          getRowId={agGridRowId}
          rowData={tableRows}
          columnDefs={columnDefs}
          defaultColDef={{ resizable: true }}
          overlayNoRowsTemplate={
            unassignTableStatus === "inFlight"
              ? t("clubDevices.loading")
              : undefined
          }
        />
```

**Comment by StephenCooper** [comment]
I am able to reproduce the issue with v30, if passing an empty string directly. We have made improvements to the overlays in v32 which may have changed the ordering, resulting in this new case being possible. 

Either way we can make the grid more robust against empty strings for these values.
