### ISSUE TITLE
Large Text Cell Editor is only resizable on y-axis, how can I fix this

### ISSUE THREAD

**Issue by chanceDira** [ag-grid/ag-grid#8380]
**I'm submitting a support request...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

I have a table(ag-grid) with large editor cell, When I try to resize the large cell it only allowing to resize on y-axis only in other words am only able to resize downwards or upwards

**Expected behavior**

I should be able to resize even on x-axis in other words resize by moving to left or right. I think this bug is in the new release.
On you official doc it shows that it can be resizable but in the actual codes it doesn't

**Please tell us about your environment:**

* **AG Grid version:** ^31.3.2

* **Browser:** Chrome

* **Language:** [TypeScript 5

**Comment by AG-Zoheil** [comment]
Hi @chanceDira,

Our documentation is in sync with the latest code release.

Please use the example here to address your issue: https://ag-grid.com/javascript-data-grid/provided-cell-editors-large-text/#enabling-large-text-cell-editor

Kind regards,
Zoheil

**Comment by chanceDira** [comment]
Hi @AG-Zoheil 

Thanks for replying back, 
I am using the exact code as on that link you shared, but still not working !!
Please help me out I need this to work

**Comment by chanceDira** [comment]
@AG-Zoheil 
Kindly find the attached image

![WhatsApp Image 2024-07-24 at 6 05 33 PM](https://github.com/user-attachments/assets/c741e7ff-e849-4c2e-b57e-1fa906611e44)

**Comment by AG-Zoheil** [comment]
Thanks - I will reply in the other thread you've opened.
