### ISSUE TITLE
Error compiling new version 30.0.2 with webpack

### ISSUE THREAD

**Issue by RickyLeRoi** [ag-grid/ag-grid#8383]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

* **AG Grid version:** 30.0.2

* **Browser:**
* Google Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* JavaScript ES6 with React 17

Hi all,
I'm trying to update AgGrid from 31.3.2 to 32.0.2 but I receive these issues:

`webpack built c4e84e4fcdd89dfa81a9 in 30080ms
× ｢wdm｣: 
ERROR in ./node_modules/ag-grid-react/dist/package/index.cjs.js 284:49
Module parse failed: Unexpected token (284:49)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       className,
|       ref: setRef2,
>       ...!props.colDef ? { role: ctrlRef.current?.getCellAriaRole() } : {}
|     },
|     /* @__PURE__ */ import_react2.default.createElement("span", { className: expandedClassName, ref: eExpandedRef }),
 @ ./app/components/ClientSideGrid/index.js 9:0-44 216:38-49
 @ ./app/components/ClientSideGridTabPanels/index.js
 @ ./app/redux/subSagas/gridSaga.js
 @ ./app/redux/saga.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js webpack-hot-middleware/client?reload=true ./app/app.js

ERROR in ./node_modules/ag-charts-react/dist/package/index.cjs.js 50:30
Module parse failed: Unexpected token (50:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     (0, import_react.useEffect)(() => {
|       if (!unsafeIsInitialMount) {
>         void chartRef.current?.update(getOptions(options, containerRef));
|       }
|     }, [options]);
 @ ./app/components/Chart/index.js 16:0-48 244:45-58
 @ ./app/components/BulkOperation/TargetStockLevel/index.js
 @ ./app/components/ModalBulk/index.js
 @ ./app/components/Pager/index.js
 @ ./app/containers/Replenishment/index.js
 @ ./app/containers/Replenishment/Loadable.js
 @ ./app/components/Menu/MainMenu/index.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js webpack-hot-middleware/client?reload=true ./app/app.js`

below my package.json, I tried to make a plunker but with only aggrid and react it seems to work but using systemjs, instead I am using webpack.

```json
{
  "name": "planning",
  "version": "2024.6.0",
  "description": "WebClient",
  "engines": {
    "npm": ">=10.2.4",
    "node": ">=20.11.0"
  },
  "config": {
    "build_dev": "webpack --config internals/webpack/webpack.dev.babel.js --color -p --progress --display-optimization-bailout",
    "build_prod": "webpack --mode production --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout"
  },
  "scripts": {
[...]
    "version": "node ./internals/scripts/version.js",
    "do_build": "cross-env-shell NODE_OPTIONS=--openssl-legacy-provider $npm_package_config_build_prod",
    "build": "npm run build:clean && npm run do_build && npm run version",
    "start": "cross-env NODE_OPTIONS=--openssl-legacy-provider node server",
[...]
  },
  "dependencies": {
    "@babel/polyfill": "7.12.1",
    "@elastic/apm-rum": "^5.16.0",
    "@emotion/react": "^11.13.0",
    "@emotion/styled": "^11.13.0",
    "@microsoft/signalr": "8.0.7",
    "@mui/icons-material": "^5.16.4",
    "@mui/material": "^5.16.4",
    "@mui/lab": "^5.0.0-alpha.172",
    "@mui/styles": "^5.16.4",
    "@ronchalant/react-loading-overlay": "^1.1.0",
    "ag-charts-react": "^10.0.2",
    "ag-grid-react": "^32.0.2",
[...]
    "react": "^17.0.2",
    "react-beautiful-dnd": "^13.1.1",
    "react-dom": "^17.0.2",
    "react-draggable": "^4.4.6",
    "react-elastic-carousel": "0.11.5",
    "react-helmet": "6.1.0",
    "react-intl": "^6.6.5",
    "react-measure": "^2.5.2",
    "react-redux": "^7.1.0",
    "react-router": "^5.0.0",
    "react-router-dom": "5.2.0",
    "react-scripts": "5.0.1",
    "react-slideshow-image": "^3.5.0",
    "react-split-pane": "^2.0.3",
    "react-toastify": "^5.5.0",
    "react-virtualized": "^9.22.5",
[...]
    "sass": "^1.75.0",
    "sass-loader": "^10.5.2"
  },
  "devDependencies": {
[...]
    "compression-webpack-plugin": "^6.1.2",
    "copy-webpack-plugin": "4.5.0",
    "css-loader": "2.1.1",
    "depcheck": "1.4.7",
    "env-cmd": "^9.0.3",
[...]
    "file-loader": "3.0.1",
    "glob": "10.3.10",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "3.2.0",
[...]
    "svg-url-loader": "2.3.2",
    "terser-webpack-plugin": "^2.3.5",
    "webpack": "4.44.2",
    "webpack-cli": "^3.3.11",
    "webpack-dev-middleware": "3.7.2",
    "webpack-hot-middleware": "^2.26.1",
    "webpack-bundle-analyzer": "^4.10.2"
  }
}
```

**Comment by StephenCooper** [comment]
Hi @RickyLeRoi,

In v32 we are now publishing the grid code as ES2020. I suspect that is what is causing the build issue based on the line failing that has the optional chaining syntax in it.

You may have to update part of your build chain to support this syntax.

**Comment by RickyLeRoi** [comment]
I did, thank you.
Now I can compile but I cannot accesso to api.gos.gridOptions anymore.
I read that much methods where deleted ma I thought that object could always be used...
