### ISSUE TITLE
Move column with `suppress-drag-leave-hides-columns` does not trigger `column-moved` event when finished

### ISSUE THREAD

**Issue by danielmalaton** [ag-grid/ag-grid#8386]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

### Providing a Reproducible Scenario
**Link plunker**: https://plnkr.co/edit/k6O908AaM3qZfZEu?open=main.js
**Context**:
- Add `suppress-drag-leave-hides-columns` options to AG-Grid
- Add `column-moved`, it logs the event when the moving is finished

**Reproduce**:
- Drag the second column to the left side

### Current behaviour
- The second is moved to the first position
- AG **does not log** the moved event

### Expected behavior
- The second is moved to the first position
- AG **logs** the moved event

**Please tell us about your environment:**

* **AG Grid version:** 32.0.2

* **Browser:** Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @danielmalaton,

I am assuming you are dropping the column whilst your cursor is outside of the grid? The grid currently can not fire events if the dropzone is outside of it. You would need to handle this yourself.

However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-3967**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by danielmalaton** [comment]
It happens when pining a column by dragging. Should the grid fire `column-moved` event with `finished = true` too?
