### ISSUE TITLE
suppressHeaderContextMenu not working on pivotColumns v32.x

### ISSUE THREAD

**Issue by SietsevTilburg** [ag-grid/ag-grid#8387]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Here is a plunker of the issue https://plnkr.co/edit/u1G7bZkMbIxVbWqe?open=main.js&preview

To reproduce just simple right click on all column headers. Column menu will be shown for pivot columns not for the aggregates and rowGroups

**Current behavior**
Currently when adding suppressHeaderContextMenu: true (Set to true to not display the column menu when the column header is right-clicked) on either the defaultColdef or on individual column colDefs the right click on pivot:true columns still shows the column menu's. On all other columns the right click is suppressed as expected.

**Expected behavior**
I expect suppressHeaderContextMenu: true to suppress all column header menu's so right clicking a pivot:true column should also not show a column menu.

**Please tell us about your environment:**

* **AG Grid version:** 32.0.0 - 32.0.1 - 32.0.2

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

* **Language:** [all | Javascript | vue2/3]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12425**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
