### ISSUE TITLE
[search] Highlight searched text

### ISSUE THREAD

**Issue by AmitMY** [ag-grid/ag-grid#839]
I suggest that when one searches (in a quick search), the data found should be highlighted.
For example:

col1    col2
123    47329487
874    98712389

Now when I search "123", both lines should be shown (as they are now), but the numbers "123" should be highlighted (like ctrl+f does), so I can know where it found the match result.

col1    col2
**123**    47329487
874    987**123**89

I think also that this should be the default, and have a supress option.

What do you think?
(I implemented it myself, replacing the results found strings with a `<strong>` tag,. but than the clipboard copy feature got messed up, so I just stopped)

**Comment by shivekundefined** [comment]
@AmitMY what is your approach to do this?
Please add plnkr or give and example of your approach.

**Comment by AmitMY** [comment]
My solution is quite simple, and very stupid.
On every filter change:
```
$.each(data, function (k, v) {
    $.each(v, function (k2, v2) {
        if(v2 != null)
            data[k][k2] = v2.toString().replace(new RegExp("("+$scope.textSearch+")", 'gi'), "<strong>$1</strong>" );
    });
});
```
Then I just set the rows to data.

And this is the css:
```
.ag-fresh strong {
    background-color: yellow;
}
```

Again, this works, and does show the text highlighted, but because I actually change the row value, and not the cell rendering itself, when I try to copy, it copies the text with `<strong>`, as for my example:
987<strong>123</strong>89

Which is plain awful.

**Comment by shivekundefined** [comment]
@AmitMY , I am amazed of your work but my approach is little different. You can also follow this if you are using AngularJs as well  and my approach is not messing up with Clipboard copy feature.
Here is my approach..

**Angular Filter**
```
 app.filter('highlight', function ($filter, $sce) {
         return function (text, search, caseSensitive) {
              if (search == undefined)
                 search = searchDataBrowser;

            if (text && (search || angular.isNumber(search))) {
                text = text.toString();
                search = search.toString();
                if (caseSensitive) {
                    var text = text.split(search).join('<span class="highlight">' + search + '</span>');
                    return $sce.trustAsHtml(text);
                } else {
                    var text = text.replace(new RegExp(search, 'gi'), '<span class="highlight">$&</span>');
                    return $sce.trustAsHtml(text);
                }
            } else {
                return text;
            }
        };
    });

```

```
defaultCol = {
		headerClass:'DbheaderClass',
		field: 'FIELD_NAME',
		headerName: 'ANYTHING YOU LIKE',
		template: "<span ng-bind-html='data.FIELD_NAME | highlight:searchtext ' ></span>"
		}
							
		$scope.columns.push(defaultCol);
							 
		$scope.gridOptions.api.setColumnDefs($scope.columns);			 
							 
		// Make sure to use following otherwise template will not be compiled and will not generate expected result
		 $scope.gridOptions.angularCompileRows = true; 		
				 
		 //make sure to bind 'searchtext' with Textbox of search

```

**Comment by AmitMY** [comment]
This is absolutely beautiful! A much netter approach than mine.
I do use Angular, and am embarrassed to say I never thought to use filters in this fashion, Only for filtering.

I am also embarrassed to say I did not know about "angularCompileRows", and used to write whenever I need a button a cellRenderer which returned an html button with data-some-id attribute, and then using jQuery document on click to detect clicks.
*To be fair, my boss told me he tried to write ng-click, and could not find a solution, so I was just following his steps :)

I do however have two questions about your code I'd like you to address -

1. How do you make this is the large scale? I have 50 columns, does that mean ill template all 50 of them to be like this? or is there a global cell renderer template thing that I can use instead?
2. I have about 50K rows, with about 50 columns. if I use angular to compile my rows, does that mean Ill have like 250K watchers, or just the visible rows and columns? (which is 30*15 at most)

BTW
I'm using this table for several (~10) tables, and want to improve on my predecessor code, and it seems like you are familiar with the table and angular. Do you mind if I ask you a couple of questions about it? (ag-table using angular)
(Please dont feel obligated to help, but if you can answer some short questions, this is my email amitmoryossef@gmail.com)

**Comment by ceolter** [comment]
be mindful of using angular, it will slow your grid down!

**Comment by ceolter** [comment]
highlighting selected text is something that would be cool. when i've time i'll come back and soak in the above.

**Comment by mikeerickson** [comment]
@ceolter et al

This feature is the exact thing I have to implement today.

Further, I need to add a feature whereby users can use the native Ctrl-F (in Chrome) to find text on the page.  The issue I have is if the result is offscreen, the user cant see it?  Is there a way to scroll grid to display result in current view port?

**Comment by ceolter** [comment]
```The issue I have is if the result is offscreen, the user cant see it? Is there a way to scroll grid to display result in current view port?```
-> not possible, as the grid doesn't render everything into the dom. so when your searching what's rendered (ctrl+f) it isn't actually searching the entire dataset.

**Comment by AmitMY** [comment]
You can use the default search option of the grid. When someone presses Ctrl+f, just focus on the filter input.

How did you implement the highlight? Angular or plain JS?

**Comment by ceolter** [comment]
please say Plain JS! surely people know at this stage not to use Angular in complex stuff if you want it fast!!!

**Comment by AmitMY** [comment]
@mikeerickson I would too really like to know. If it is just JS, can you please share your code?

@ceolter BTW, it can also be done with a cellrenderer function, but same issue - copy will not work in its normal way. There is an (awful) workaround.

**Comment by Ruud-cb** [comment]
Any updates on this? It sure is an awesome feature I'm looking for as well. I use angular but I won't compile the rows by angular due performance.

**Comment by shivekundefined** [comment]
@Ruud-cb, Even If you want to use "cell-renderer" , you still need "angularCompileRows" to be set. Otherwise It wouldn't work exactly the way you want.

**Comment by Ruud-cb** [comment]
@shivekundefined Well that depends how the filtering is implemented, if it re-renders the cells on each keypress than it should be possible without angular. But I guess it is not implemented that way... @ceolter  thoughts?

**Comment by AmitMY** [comment]
@ceolter I think this should be resolved inside the grid, in a pure JS manner, in the cell evaluation functions (didn't look at the source code, but I guess there are functions to evaluate cells)

**Comment by ceolter** [comment]
yea i agree, i want this feature in. just a matter of prioritising.

**Comment by AmitMY** [comment]
@seanlandsman Can you please add this to the pipeline?

**Comment by seanlandsman** [comment]
Hi @AmitMY 

I've added AG-385 for this to the pipeline

thanks

**Comment by jakeboone02** [comment]
@seanlandsman - [looks like](https://www.ag-grid.com/ag-grid-pipeline/) this is AG-119, is that right?

**Comment by seanlandsman** [comment]
Hi - yes, it is now. I've taken a look and can see that they were duplicates. 385 was closed and referenced 119 instead.

thanks for pointing this out!

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by DominicTobias** [comment]
The whole universe is still eagerly awaiting this feature

**Comment by AmitMY** [comment]
@DominicTobias I just got an email notification for your comment, and was like: "DID THEY FINALLY DO IT????", but unfortunately, opened the mail to disappointment.

**Comment by JabbyPanda** [comment]
@AmitMY in the meanwhile, just throw in your renderer this Regexp and it will do a job

```

**Comment by AmitMY** [comment]
Thanks, @JabbyPanda ! Are you sure this won't affect the copying mechanism?
Anyway, I heard from good authority that this feature is coming SOON!

**Comment by JabbyPanda** [comment]
>Are you sure this won't affect the copying mechanism?

Cannot promise that, because I do not use this feature of `ag-grid`

If you are React user, you can try out https://github.com/bvaughn/react-highlight-words in your renderer too

**Comment by janhesters** [comment]
@AmitMY Still nothing 😢

**Comment by janhesters** [comment]
@seanlandsman Any news on ag119?

**Comment by janhesters** [comment]
Found a even better and but still hacky way to achieve this in React:

1. Enable `reactNext` and give a `frameWorkComponents` value:

```js
<AgGridReact
  animateRows={true}
  columnDefs={columnDefs}
  defaultColDef={defaultColDef}
  frameworkComponents={frameworkComponents}
  multiSortKey="ctrl"
  onFirstDataRendered={onFirstDataRendered}
  onGridReady={onGridReady}
  quickFilterText={searchValue}
  reactNext={true}
  rowData={contacts}
/>
```

2. Define `frameWorkComponents`:

```js
const frameworkComponents = {
  highlightCellRenderer: HighlightCellRenderer,
};
```

3. In your `colDefs` add the `cellRenderer`:

```js
cellRenderer: 'highlightCellRenderer',
```

Lastly, create your custom component:

```js
import React from 'react';
import { useSelector } from 'react-redux';

import { getSearchValue } from '../../layout/header/search-value-reducer';

function HighlightCellRenderer({ value }) {
  const searchValue = useSelector(getSearchValue);
  if (searchValue && value.toLowerCase().includes(searchValue)) {
    return <strong>{value}</strong>;
  }
  return <span>{value}</span>;
}

export default HighlightCellRenderer;
```

In my case I'm getting the `searchValue` using Redux.

**Comment by AmitMY** [comment]
@janhesters If you look in the ag-grid pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

You can see this feature request under "Next Release" (in the bottom).
It does not seem to have been worked on yet, still in the backlog, but at least it is planned for next release :)

**Comment by seanlandsman** [comment]
This is on the roadmap for this year for sure - I cannot say when however.

Our current focus is on our new charting component, but once that has stabilised I believe this item will be high on the agenda for subsequent releases

**Comment by janhesters** [comment]
@AmitMY @seanlandsman Thank you to both of you 😊

**Comment by impshum** [comment]
I really would like this feature.

**Comment by pitops** [comment]
any update on this?

**Comment by henus** [comment]
any update on this?

**Comment by ayushkushwah** [comment]
any update on this?

**Comment by metaljelly** [comment]
any update on this?

**Comment by kiril-matev** [comment]
Hello!

Thank you for following up on this! 

We have this feature request logged in our product backlog as:
**AG-119 Add Find feature to highlight searched text**

We have no specific timeline for implementing this feature at the moment. In order to get the maximum output from our product team, we very rarely work on feature requests from different areas in isolation. Instead, for a specific release we focus on an entire area of the grid and we tackle a number of issues/feature requests logged against that area. If this functionality falls within the area we'll be working on, there's a chance it will get picked up. 

You can follow the status of feature requests, bugs and releases using our pipeline (just search for AG-119):
https://www.ag-grid.com/ag-grid-pipeline/

The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by CosmoFruit** [comment]
@kiril-matev any update? how to update prority for this feature?

**Comment by kiril-matev** [comment]
@CosmoFruit,

We don't have an update on the timeline of this feature at this point. We hope to add it soon as it's an important part of the filtering experience we'd like to provide.

The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks for following up on this and for using AG Grid - we're keen to deliver this feature so we can improve the filtering experience.

**Comment by uncaught** [comment]
Would be cool if aggrid could use the [Highlight API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Custom_Highlight_API) for this. That way we could define the highlight styles from outside.

**Comment by KrashLeviathan** [comment]
For what it's worth, here's a working solution for Angular 17 and ag-grid 31: https://stackoverflow.com/a/78524410/10393763
