### ISSUE TITLE
Column Groups are not collapsable when removePivotHeaderRowWhenSingleValueColumn is true

### ISSUE THREAD

**Issue by igorvukic** [ag-grid/ag-grid#8391]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
If `removePivotHeaderRowWhenSingleValueColumn` is set to `true` and there are column groups, it is not possible to collapse top level column group

![Screenshot 2024-07-24 at 13 16 59](https://github.com/user-attachments/assets/f17c479e-d908-4cc4-a4f3-fb9efed9de23)

**Expected behavior**
I would expect the top level column group to be collapsable

**Steps to reproduce:**
I have followed your example from [Docs Hiding Repeated Value Column Labels ](https://www.ag-grid.com/vue-data-grid/pivoting/#hiding-repeated-value-column-labels) and on [Code Sandbox example](https://codesandbox.io/s/ct62rd) in UI I have only pulled the `Sports` to be on top of `Year` in `Column labels` section of the sidebar:

![Screenshot 2024-07-24 at 13 25 06](https://github.com/user-attachments/assets/15a21715-99f8-41cf-a7cd-a5e8c9172e48)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-7248**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
