### ISSUE TITLE
detailRowAutoHeight doesn't work for short tables

### ISSUE THREAD

**Issue by Eugeno** [ag-grid/ag-grid#8404]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/r8shdKQBDld8v2a3?open=main.ts

**Current behavior**
![image](https://github.com/user-attachments/assets/9b563633-9b9d-4db5-bcea-a7144d588a51)

**Expected behavior**
![image](https://github.com/user-attachments/assets/56deb43b-63b8-435d-8391-c2b1ff6b4ed3)

* **AG Grid version:** 32.0.2

**Comment by sabahang** [comment]
Hi,

The Grid has a min height set by default to avoid it looking weird when too few data. This applies to detail grids as well. 
You can override this behavior though. See here:

https://ag-grid.com/javascript-data-grid/grid-size/#min-height-with-auto-height
