### ISSUE TITLE
[component - status panel] allow customising of status panel

### ISSUE THREAD

**Issue by AmitMY** [ag-grid/ag-grid#841]
I would like to have a feature to add some HTML to my footer (where it shows average, min, max, sum) to add some more things, that I think should be parsed.

For example, I would like to add a rows amount, to say how many rows are in the table, or a custom variable, for total rows, that my datasource returns, to show for example:
Rows: 200 / 5000

And then every time the table loads another page, so for example it would be
Rows: 400 / 5000

Or as a custom footer template:

```
function (params) {
   return "Rows: " + params.rows_count + " / " + params.custom_params.total_rows;
}

```

This example will also require some option for custom_params, but can be done without anything built in to the grid, just a custom variable I create.

EDIT:
Another thing important for me for example is number of selected rows.

EDIT 2:
Here is an example why this is important:
![image](https://cloud.githubusercontent.com/assets/5757359/15782444/06129e84-29b3-11e6-9390-9349d1c61904.png)
This example shows custom table icon indicators, that I created by adding a div, making a duplicate footer just to have more info

**Comment by ceolter** [comment]
sounds fair - however the name overlayFooterRenderer i'm not liking.

an overlay in ag-Grid is what gets display when grid is loading, i don't think that's what you mean. this is a duplicate btw, but i don't have the time right now to look for the other one!

**Comment by AmitMY** [comment]
Yeah I don't know how to name stuff.. thanks!

**Comment by seanlandsman** [comment]
tracked by AG-120
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
