### ISSUE TITLE
If i select date range from 1 to 30 it filter from 2 to 29 date in aggrid i want exact dates i.e.; 1 to 30.

### ISSUE THREAD

**Issue by Ali-Waseer** [ag-grid/ag-grid#8411]
![Screenshot 2024-07-26 120701](https://github.com/user-attachments/assets/892342ec-d792-40cf-be90-222cf4caa137)

In this case, I select 24 to 27, but it excludes the 24 and 27 and filters in between dates 25 and 26

**Comment by sabahang** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by Ali-Waseer** [comment]
> Hi
> 
> @Ali-Waseer you might have to use `inRangeInclusive` property in your filter options https://ag-grid.com/javascript-data-grid/filter-date/#reference-IDateFilterParams-inRangeInclusive
> 
> Does this help?

Yes, it was resolved.
