### ISSUE TITLE
Funnel filter is missing when upgrading from 30.2.0 -> 32.0.1

### ISSUE THREAD

**Issue by fsereno** [ag-grid/ag-grid#8415]
After updating to version 32.0.1 we no longer see the funnel filter above each column on a data grid. I have been unable to determine what the breaking change might be from documentation on:

https://www.ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-32/

![image](https://github.com/user-attachments/assets/3ff82e7a-0b45-491d-9706-d74a7382840c)

Please see more details below.

Many thanks

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
The funnel filter above a data column are missing.

**Expected behavior**
There is a funnel filter above each column in a data table. I am able to click the funnel and open a filter with checkboxes to filter on.

**Please tell us about your environment:**
Windows 11 Enterprise, Visual Studio Code. NodeJs v20.9.0

* **AG Grid version:** 32.0.1

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'

* **Language:** [TypeScript]

**Comment by AG-Zoheil** [comment]
Hi @fsereno,

This is due to our new and improved column menu.

This has been noted in the migration guide for `v32` here: https://www.ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-32/#column-menu.

You can set the legacy column menu in the `gridOptions` as described here: https://ag-grid.com/javascript-data-grid/column-menu/#legacy-tabbed-column-menu

Also please note that the default theme for AG Grid is now **Quartz**. The filter icon looks slightly different, if you'd like to use the filter icon that is displayed in your comment above please change the theme to **Alpine**.

I hope this helps.

Kind regards,

**Comment by fsereno** [comment]
Great thank you very much for your help, this resolved the issue. We will look to updating to Quartz in the near future.
