### ISSUE TITLE
Custom editor test fails after upgrading to version 31.0.3+

### ISSUE THREAD

**Issue by wein2011** [ag-grid/ag-grid#8417]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
Added minmal reproducible test case in attached zip file
[ag-grid custom editor test.zip](https://github.com/user-attachments/files/16400886/ag-grid.custom.editor.test.zip)

To see the issue:
1. Extract the zip file
2. Run npm install
3. Run npm run test

**Current behavior**
The single test fails with:
Error: Timeout - Async function did not complete within 10000ms (custom timeout)

The issue occured after upgrading to AG Grid: 31.0.3 or beyond (including 32).

The application is a simple 1 row & 1 column grid (see app.component.ts). It is important to note that the domLayout is 'autoHeight'.

The custom editor is a simple Material input (see editor.component.ts). It is important to note that ngAfterViewInit calls nativeElement.focus after a timeout. This is required in the full program due to transition from the renderer to the editor while maintaining the caret position.

The test (Text: a) will fail (see app.component.spec.ts).
The promise to loader.getHarness(MatInputHarness) on line 81 of app.component.spec.ts will never resolve. Additional fixture.detectChanges, fixture.whenStable, or time delays did not provide a work-around. whenStable might also not resolve. This behavior is independent of Angular (tested v17 and 18).

It indicates but does not prove that autoHeight prevents Angular from stabilizing.

**Expected behavior**
The single test passes.

The test passes when downgrading the version to AG Grid: 31.0.2.

**Please tell us about your environment:**
* **Windows:** 11
* **Visual Studio Code:** 1.91.1
* **NPM:** 10.7.0
* **Angular:** 18.1.2 (also tested with V17 with same result)

* **AG Grid version:** 31.0.3 and later (issue did not exist with 31.0.2 and prior)

* **Browser:** Karma v 6.4.3 uses Google Chrome v 126.0.6478.185
- 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

* **Language:** TypeScript 5.5.4

**Comment by sabahang** [comment]
Hi @wein2011 

Thanks for reporting this. Please update to the latest version (currently 32.1.0). We have done some internal improvements that seem to have fixed this issue

Thanks

**Comment by wein2011** [comment]
Hi [@sabhang,](https://github.com/sabahang),

I originally found the issue with 32.0.2 and have now also tested the newest 32.1.0.

Unfortunately, 32.1.0 still fails the test.

Thanks
