### ISSUE TITLE
agSelectCellEditor needs 3 clicks to open dropdown 

### ISSUE THREAD

**Issue by thebadking** [ag-grid/ag-grid#8418]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

using **agSelectCellEditor** requires minimum of 3 clicks to display the drop-down, I can provide my code to reproduce but it seems to be even on your example page:
https://www.ag-grid.com/javascript-data-grid/provided-cell-editors-select/

the expected behavior is to drop-down with one click, I cant stress this enough for large tables to fill this becomes cumbersome and unusable, also the arrow for the drop-down should always be present indicating that it is a drop-down or at least make a flag for this.

* **AG Grid version:** 32.0.2

**Comment by jotting** [comment]
I believe this is related to: https://github.com/ag-grid/ag-grid/issues/8382

**Comment by thebadking** [comment]
Ok, I posted my solution there, thanks @jotting
