### ISSUE TITLE
Paste value into focus cell will clear cell value in next row

### ISSUE THREAD

**Issue by Manon103** [ag-grid/ag-grid#8430]
**Problem 1:**
- I copied a cell value from Excel, then selected a grid cell to make it focused. Then I used ctrl+v to paste the copied value from Excel into the focused value, and the cell value in the same column of the next row was cleared.

![image](https://github.com/user-attachments/assets/40d3193c-b2d3-4c3c-98d5-2cc6f5df9fec)
![image](https://github.com/user-attachments/assets/cec4d2bd-3b86-467c-ace6-87f2ec1bd46b)

**Problem2**
- Copy the values ​​of two cells from Excel, then select 6 cells in a column. Then paste the values ​​into these cells, the pasted values ​​will not be repeated. Only the first three cells use the latest pasted value.

![image](https://github.com/user-attachments/assets/d796074e-80f8-45fc-a045-21faa3b1bc47)
![image](https://github.com/user-attachments/assets/de10b9f9-6163-4a90-8b90-59cd2b68013d)

- AG Grid version: 30.0.2

**Comment by sabahang** [comment]
Hi @Manon103 

The first issue is a behaviour specific to Windows that we have a property for:
https://ag-grid.com/javascript-data-grid/grid-options/#reference--suppressLastEmptyLineOnPaste

Regarding the second issue please try it with the above property, hopefully should solve it. If not we can investigate further
