### ISSUE TITLE
[Question] How to update the columndefs without trigger data re-fetch?

### ISSUE THREAD

**Issue by lssbq** [ag-grid/ag-grid#8435]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

We are using ag-grid-community in Angular migrated from ag-grid-angular. With `infinite` rowModelType I found that after set columnDefs it triggers another `getRows()` function call which lead to the data retrieve deplication. 
The data fetched from server as well as the column defination, so it's not possible to preset the column defination before getting first page of data records.

**Providing a Reproducible Scenario**

Set the datasource in grid ready callback:
```
    onGridReady(e: GridReadyEvent): void {
        // ...
        this.gridApi.setGridOption('datasource', this.gridDataSource);
    }
```

`getRows` in `IDatasource` will triggered and fetch the first page of records with column defs:
```
async getRows(params: IGetRowsParams): Promise<void> {
     // 1. fetch data from server
     // ......
     // 2. update column defs to ag-grid
            if (!this.columnDefs || !_.isEqual(this.currentHeaders, data.headers)) {
                this.columnDefs = buildAgGridColumns(data.headers, this.lookupOption);
            }
     // ......
     // 3. update row records to ag-grid
     const rowData = buildGridData(data.rows, this.columnDic);
     params.successCallback(rowData, data.totalCount);
}
```

**Current behavior**

After the `columnDefs` update, `getRows()` will be triggered to fetch data from the first page.
A workaround is that we have to cache the first page of data in datasource service to avoid duplicate server query.

**Expected behavior**

Is this a usage error or is there a way to change this behaviour to allow update columnDefs without data reload?

* **AG Grid version:** X.X.X

ag-grid-community@32.0.2

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
