### ISSUE TITLE
ag grid css error with angular 17 

### ISSUE THREAD

**Issue by Shady-BAGHDADI** [ag-grid/ag-grid#8438]
![Capture d’écran de 2024-07-30 10-06-43](https://github.com/user-attachments/assets/83e26c1b-7e23-4afc-a776-e5e4f5c73b7c)

i update my angular 14 to  angular 17 ,
in my styles.scss i have that :
@import "assets/shared_styles/colors-light.scss";
@import "assets/shared_styles/colors-dark.scss";

when i do the comand npm start i have that error in 
✘ [ERROR] Can't find stylesheet to import.
  ╷
1 │ @use "node_modules/ag-grid-community/styles" as ag;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/rgo-library/rgo-styles/vendors/ag-grid/_ag-grid.scss 1:1  @forward
  rgo-library/_index.scss 25:1                                           @import
  src/styles.scss 3:9                                                    root stylesheet [plugin angular-sass]

    angular:styles/global:styles:2:8:
      2 │ @import 'src/styles.scss';

i have that as package version :   
    "ag-grid-angular": "^28.1.1",
    "ag-grid-community": "^28.1.0",
    "ag-grid-enterprise": "^28.1.2",

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
