### ISSUE TITLE
Adding `isDestroyed()` guard against all the grid API methods internally

### ISSUE THREAD

**Issue by weilinzung** [ag-grid/ag-grid#8450]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
  
**Providing a Reproducible Scenario**
## It is very hard to replicate locally

 
**Current behavior**

## Error Stacktrace
![Screenshot 2024-08-01 at 9 52 42 AM](https://github.com/user-attachments/assets/19aa7b1a-a07a-4a70-ad5e-ea6f01255e99)

## Breadcrumbs
![Screenshot 2024-08-01 at 9 51 48 AM](https://github.com/user-attachments/assets/6387b749-adce-4022-8dd2-f454389cafde)

## After these errors are shown then the error `Virtual list has not been created` occurs in the next
```
AG Grid: Grid API function getRowGroupColumns() cannot be called as the grid has been destroyed.     It is recommended to remove local references to the grid api. Alternatively, check gridApi.isDestroyed() to avoid calling methods against a destroyed grid.     To run logic when the grid is about to be destroyed use the gridPreDestroy event. See: See https://www.ag-grid.com/angular-data-grid/grid-lifecycle/#grid-pre-destroyed
```

## Workaround

As an example below, we have to go over the entire app(multiple AG Grids) and guard against all of the related grid API methods:
```
  const currentGridSettings = !this.gridReady.api.isDestroyed() && {
        columnState: this.gridReady.api.getColumnState(),
        filterState: this.gridReady.api.getFilterModel()
      };
```

**Expected behavior**

- The library should guard against all the grid API methods internally with `isDestroyed()`
- Provide a better debug log from the `Virtual list has not been created` error throwing that attach with what API method is causing the error

**Please tell us about your environment:**
Node: v20.9.0
@angular/cli: v18.1.0

* **AG Grid version:** X.X.X
    "ag-grid-angular": "^31.1.1",
    "ag-grid-community": "^31.1.1",
    "ag-grid-enterprise": "^31.1.1",
    "@ag-grid-community/styles": "^31.1.1",

* **Browser:**
 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
    "typescript": "5.5.3"

**Comment by AG-Zoheil** [comment]
Hi @weilinzung,

We can see you've raised this request directly with our enterprise team on ZenDesk as well. We will respond on there. 

Kind regards,
Zoheil
