### ISSUE TITLE
Pinned columns are automatically swapped as you narrow the window

### ISSUE THREAD

**Issue by tk2153** [ag-grid/ag-grid#8454]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

The problem occurred in my environment and it is also reproduced in the sample code below.

url：https://codesandbox.io/s/2tk2jh

Case1
When opening in a narrow window, the column pinned to the left moves freely.
(as below, the column of # moved)

![image](https://github.com/user-attachments/assets/3a6feab9-fdb6-4449-b31c-1a37e3bd3e68)

Case2
Initially the column is not moving,

![image](https://github.com/user-attachments/assets/70202291-e858-4b84-acb4-73a664645b4f)

As gradually narrowing the window, the columns move.

![image](https://github.com/user-attachments/assets/cf6c6dea-fefb-488c-9264-6ee0b7e2fbed)

**Please tell us about your environment:**

* **AG Grid version:** 32.0.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0

* **Language:** typescript 5.5.4

**Comment by AG-Zoheil** [comment]
Hi @tk2153,

This is an intended behaviour that was implemented via **AG-3915**. Please note this section of our documentation: https://ag-grid.com/javascript-data-grid/column-pinning/#resizing-pinned-sections.

Kind regards,
Zoheil

**Comment by stevendarby** [comment]
@AG-Zoheil Is it intended behaviour that the columns aren't re-pinned when space is given back?

**Comment by AG-Zoheil** [comment]
We have a feature request to allow your desired behaviour: **AG-9852**
