### ISSUE TITLE
Background Loader Issue with Multiple Popups After Upgrading to 31.2.1 Version

### ISSUE THREAD

**Issue by santoshkumar-maddela** [ag-grid/ag-grid#8460]
**Description**: After upgrading to the 31.2.1 version of AgGrid, we have encountered an issue with the background loader styles. The loader styles have changed, causing unexpected behavior specifically when two popups are present in AgGrid. This issue affects the display of the loader, and we are unable to fix it for this particular scenario without impacting all other instances where the loader is used.

**Steps to Reproduce**:

Upgrade to the 31.2.1 version of AgGrid.
Implement a scenario where two popups are displayed within AgGrid.
Observe the behavior of the background loader.
Expected Behavior: The background loader should display correctly without any style issues, even when multiple popups are present.

**Actual Behavior**: The background loader styles are incorrect when two popups are displayed, causing visual inconsistencies.

**Environment**:

AgGrid Version: [31.2.1]
Browser: [any]
Operating System: [any]
Additional Context: This issue only occurs when two popups are present in AgGrid. Fixing the loader for this specific scenario would affect all other instances where the loader is displayed, making it a challenging issue to resolve.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
