### ISSUE TITLE
Custom Filter Flyout Not Moving with Column When Grid is Scrolled Horizontally

### ISSUE THREAD

**Issue by santoshkumar-maddela** [ag-grid/ag-grid#8461]
**Description:** After upgrading to the 31.2.1 version of AgGrid, we have encountered an issue with the custom filter flyout. When the custom filter flyout is open and the grid is scrolled horizontally to the right, the flyout does not move along with the column. This causes the flyout to become misaligned with the column it is associated with.

**Steps to Reproduce:**

Upgrade to the 31.2.1 version of AgGrid.
Implement a custom filter flyout for a column.
Open the custom filter flyout.
Scroll the grid horizontally to the right.
Observe the position of the custom filter flyout.
Expected Behavior: The custom filter flyout should move along with the column when the grid is scrolled horizontally, maintaining its alignment with the column.

**Actual Behavior**: The custom filter flyout remains in its original position and does not move with the column, causing misalignment.

**Environment:**

AgGrid Version: [31.2.1]
Browser: [any]
Operating System: [any]
Additional Context: This issue specifically occurs when the custom filter flyout is open and the grid is scrolled horizontally. Fixing this issue is crucial for maintaining the usability and visual consistency of the grid.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
