### ISSUE TITLE
pagination with cache

### ISSUE THREAD

**Issue by pingbaohua** [ag-grid/ag-grid#8463]
I'm using rowModelType: 'infinite', and after pagination={true},paginationPageSize = 50 and I created a custom pagination.  a further page-forward operation does not trigger getRows to re-request the interface, but uses the cache. Calling api.paginationGoToPage(3) does not jump to when page3

` 
<AgGridReact
  rowModelType = 'infinite',
 pagination={true},
datasource={datasource}
paginationPageSize = 50 
 />
//customer pagination
<CustomerPagination />
`

Version ag-grid: 25.0.1

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
