### ISSUE TITLE
Add pagination to scrolling loads

### ISSUE THREAD

**Issue by pingbaohua** [ag-grid/ag-grid#8465]
One of the effects you want to implement is: 
when rowModelType: 'infinite', you can scroll load data, you can also load data through a custom paging component, and you can also support jumping to a page, including requested data, allowing direct jumping to the page; 

At present, the problem is api.paginationGoToPage(n). If n is not loaded data, it cannot trigger the request data of getRows. How to deal with it
ag-grid: v25.0.1

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
