### ISSUE TITLE
agDateColumnFilter: filterPlaceholder not applied

### ISSUE THREAD

**Issue by relaiskiste** [ag-grid/ag-grid#8501]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

The placeholder for date column filter is not applied. 
Property  "browserDatePicker" is false.
Placeholder is working for 'agTextColumnFilter' but not for 'agDateColumnFilter'.

**Current behavior**
![image](https://github.com/user-attachments/assets/691d07eb-bed4-4db3-9345-4d280af583f2)

**Expected behavior**
![image](https://github.com/user-attachments/assets/e0e32172-52ca-4367-a61c-23aa8052fbaf)

```
const columnDefs: ColDef[] = [
  {
    field: "athlete",
    filter: "agTextColumnFilter",
    filterParams: {
      filterPlaceholder: "My Text" // <<<<<<<<<<<<<<<<<<<<< working
    }
  },
  {
    field: "date",
    filter: "agDateColumnFilter",
    filterParams: {
      browserDatePicker: false,
      filterPlaceholder: "My Text", // <<<<<<<<<<<<<<<<<<<<< not working
    }
  },
  { field: "total", filter: false }
];
```

Code: [plnkr](https://plnkr.co/edit/OPUrNseZtInHNoPN?open=main.ts)

**Please tell us about your environment:**

* **OS:** Win10

* **AG Grid version:** 32.0.2

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

* **Language:** [TypeScript 4.9]

**Comment by AG-Zoheil** [comment]
Hi @relaiskiste,

Thank you for submitting this on GitHub. We are using the browser's native html input for the date filter and setting a placeholder is not supported by the browser.

Kind regards,
Zoheil
