### ISSUE TITLE
Flex property not inherited from column defs when using initialState

### ISSUE THREAD

**Issue by dragansavevski** [ag-grid/ag-grid#8503]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Look at this plunker: https://plnkr.co/edit/CXVdteoiUJtQlUNe?open=index.tsx&preview

I have set the initial state and hid some columns. Note that there is still available space in the table. If you click print state and look at the console in the column sizing property the flex is undefined even though every column has as a defaultColDef option flex:1. 

**Expected behavior**
If not provided in the initial state the flex property should be inherited from the original column defs.

**Please tell us about your environment:**
React usage of AG Grid

**AG Grid version**: 32.0.2

**Browser**: Chrome Version 127.0.6533.89

**Language**: all | TypeScript X.X | ES6/7 | ES5

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. If you set any column property in `initialState` all column properties of the `defaultColDef` will get overwritten/ignored. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12275**. In the meantime you would have to set your desired column property (e.g. `flex`) in your `initialState`.

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by robdodson** [comment]
@AG-Zoheil Can you provide an example of how to work around this issue? Setting an initial sort state using the parameters in the page URL is a pretty common pattern for tables, but if it breaks the table's layout that seems like a big issue!

**Comment by robdodson** [comment]
If anyone else comes across this issue, I found that I could work around it by applying a helper to my column definitions. In my case, I was trying to use `sort` on initialState and it was breaking flex. So I am doing this instead:

```tsx
function getInitialSort() {
  const q = new URLSearchParams(window.location.search)
  const colId = q.get('order_by') // e.g. "name"
  const dir = q.get('order_dir') ?? 'asc' // default to ASC

  // Hard-guard: unsupported column or direction? -> no initial sort
  if (!colId || !['asc', 'desc'].includes(dir)) {
    return null
  }

  return { colId: camelize(colId), sort: dir as 'asc' | 'desc' }
}

export const MyTable = () => {
  // Then inside of my component I get the initial sort value and my colDefs use it within a helper
  const initialSort = React.useMemo(() => getInitialSort(), [])
  
  const createColumn = (config: Omit<ColDef, 'sort'>): ColDef => ({
      ...config,
      sort: initialSort?.colId === config.field ? initialSort!.sort : undefined,
    })
  
  const [colDefs] = React.useState<Array<ColDef>>([
    createColumn({
      field: 'name',
      headerName: 'Name',
      // ...
    }),
  // ...

  const defaultColDef = React.useMemo<ColDef>(() => {
    return {
      flex: 1,
    }
  }, [])
}
```

**Comment by dragansavevski** [comment]
@robdodson this was fixed with AG-12275

**Comment by robdodson** [comment]
@dragansavevski I think I was missing the `partialColumnState` property, but adding it leads to [this issue](https://github.com/ag-grid/ag-grid/issues/9959) where the flex columns seem to flicker/shift into place when the grid is initialized.

The version I posted above with the columnHelper seems to avoid this issue.
