### ISSUE TITLE
Tree data cannot edit parent level！v32.0.2

### ISSUE THREAD

**Issue by haoranz-bridger** [ag-grid/ag-grid#8516]
When using the tree data example provided on the official website, I found that even when setting columnDefs to editable: true, only the leaf nodes are editable.
https://codesandbox.io/s/org-hierarchy-forked-lngplc
![MicrosoftTeams-image](https://github.com/user-attachments/assets/3eabb5bc-81da-4ef5-8150-3ba757a9e87c)

![MicrosoftTeams-image (1)](https://github.com/user-attachments/assets/25340da7-825c-48e7-be13-220e6b30c831)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12263**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by haoranz-bridger** [comment]
Hello

I will continue to monitor this issue. Our company uses the enterprise version of AG-Grid, and we rely on editable tree grids for our business needs. Downgrading to version 31.3.4 resolved the issue, but I personally prefer using the latest version of AG-Grid.

Kind regards，
haoranz

**Comment by Anecho** [comment]
Hello,

Is there any way around this? Parent element and a child element are still elements just on a different levels.

**Comment by ghost** [comment]
@Anecho  I resolved the issue by downgrading AG Grid to version 31.2.1, as every version after this one has the same problem.
