### ISSUE TITLE
Nested data for Tree data

### ISSUE THREAD

**Issue by praveenkumar91** [ag-grid/ag-grid#8523]
hi team,

I have a similar requirement as mentioned in the 

[](https://github.com/ag-grid/ag-grid/issues/7969 |)

I don't find any solution of it anywhere. 

Could you please confirm is this possible or not?

I am using

"ag-grid-enterprise": "^32.0.2",
"ag-grid-react": "^32.0.2",

**Comment by AG-Zoheil** [comment]
Hi @praveenkumar91,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

You can read about getting started with both community or enterprise versions of our grid on [this page](https://ag-grid.com/javascript-data-grid/getting-started/). Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

Do let us know if you have any other questions.

Kind regards,
Zoheil

**Comment by praveenkumar91** [comment]
As you can see I m using and i m not able to to do it.
"ag-grid-enterprise": "^32.0.2",

**Comment by AG-Zoheil** [comment]
As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.
