### ISSUE TITLE
Vite/Rollup build warning for ag-grid-vue3 version 32.x

### ISSUE THREAD

**Issue by NoahStahl** [ag-grid/ag-grid#8526]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

After upgrading `ag-grid-vue3` to version `32` from `31`, a Vite build warning has appeared via Rollup, indicating invalid comment content:

```
A comment

"/*! Bundled license information:

@vue/shared/dist/shared.esm-bundler.js:
  (**
  * @vue/shared v3.4.26
  * (c) 2018-present Yuxi (Evan) You and Vue contributors
  * @license MIT
  **)
  (*! #__NO_SIDE_EFFECTS__ *)

@vue/reactivity/dist/reactivity.esm-bundler.js:
  (**
  * @vue/reactivity v3.4.26
  * (c) 2018-present Yuxi (Evan) You and Vue contributors
  * @license MIT
  **)
*/"

in "node_modules/.pnpm/ag-grid-vue3@32.1.0_typescript@5.5.4/node_modules/ag-grid-vue3/dist/package/main.esm.mjs" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
```

**Expected behavior**

In version 31 and below, there is no such warning or invalid comment content.

** Reproducing **

- Open this [StackBlitz](https://stackblitz.com/edit/vue3-script-setup-with-vite-asngco?file=src%2FApp.vue)
- In Terminal, cancel running Vite process, then run `npm run build`
- Observe the Rollup warning about the license comment

** Observation **

If you compare the `main.esm.mjs` file from 31 -> 32, you see this in version 31:

```
/*! Bundled license information:

@vue/shared/dist/shared.esm-bundler.js:
  (**
  * @vue/shared v3.4.21
  * (c) 2018-present Yuxi (Evan) You and Vue contributors
  * @license MIT
  **)

@vue/reactivity/dist/reactivity.esm-bundler.js:
  (**
  * @vue/reactivity v3.4.21
  * (c) 2018-present Yuxi (Evan) You and Vue contributors
  * @license MIT
  **)
*/
```

And in version 32:

```
/*! Bundled license information:

@vue/shared/dist/shared.esm-bundler.js:
  (**
  * @vue/shared v3.4.26
  * (c) 2018-present Yuxi (Evan) You and Vue contributors
  * @license MIT
  **)
  (*! #__NO_SIDE_EFFECTS__ *)

@vue/reactivity/dist/reactivity.esm-bundler.js:
  (**
  * @vue/reactivity v3.4.26
  * (c) 2018-present Yuxi (Evan) You and Vue contributors
  * @license MIT
  **)
*/
```

Note the appearance of ` (*! #__NO_SIDE_EFFECTS__ *)` on line 1231. This is likely what Rollup doesn't like, and presumably shouldn't be part of the comment. Maybe a side-effect of some recent change to build?

**Comment by vaibs30** [comment]
Hi, Is there any update here?

**Comment by ventralnet** [comment]
I am seeing this as well after upgrading

**Comment by kiril-matev** [comment]
Hi @NoahStahl,

Thank you for reporting this - much appreciated.

This issue will be addressed and you'll get no more warnings in our next version  - AG Grid 33 which will be released by mid-December.

Thanks for using AG Grid!
