### ISSUE TITLE
Initialising a license key in safari <16.5 throws a regexp error 

### ISSUE THREAD

**Issue by danLDev** [ag-grid/ag-grid#8527]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Calling `LicenseManager.setLicenseKey(import.meta.env.VITE_AG_GRID_LICENSE_KEY);` on a safari env <16.5 triggers a regexp error:
```
SyntaxError: Invalid regular expression: invalid group specifier name
```

**Expected behavior**
The method should function without crashing.

 
**Please tell us about your environment:**
MacOs, Safari versions 15-16.4 (tested via browserstack), yarn, vite

* **AG Grid version:** 32.0.1

* **Browser:**
Safari 15

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 5.X

**Comment by AG-Zoheil** [comment]
Hi @danLDev,

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered. Especially as this is a licensing issue, our enterprise support team will be best placed to answer your query.

Kind regards,
Zoheil
