### ISSUE TITLE
Event.stopPropagation stops working after ag-grid upgrade

### ISSUE THREAD

**Issue by elhamzaouiaymen** [ag-grid/ag-grid#8528]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible Scenario**
- In my ag-grid instance I am defining a custom cell renderer component. The cell renders a button and it has an onClick handler which uses event.stopPropagation() to avoid event bubbling towards parent elements. On the other hand, I do have a logic that triggers when the row is clicked, I am using `onRowClicked` callback. This results, clicking on the custom cell renderer button would also fires the row click event. 
- Here is a [codesandbox](https://codesandbox.io/p/sandbox/ag-grid-cell-click-stop-propagation-is-not-working-h5ryr6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzmr2zmg00073b6iuuc49vn4%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzmr2zmg00033b6iuh269vl5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzmr2zmg00043b6iegvf22ep%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzmr2zmg00063b6ihbtzj3zu%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzmr2zmg00033b6iuh269vl5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzmr2zmg00023b6iw1tlnchj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzmr2zmg00033b6iuh269vl5%2522%252C%2522activeTabId%2522%253A%2522clzmr2zmg00023b6iw1tlnchj%2522%257D%252C%2522clzmr2zmg00063b6ihbtzj3zu%2522%253A%257B%2522id%2522%253A%2522clzmr2zmg00063b6ihbtzj3zu%2522%252C%2522activeTabId%2522%253A%2522clzms3gl2001w3b6idmvkfnfl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzmr2zmg00053b6in51fq563%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzms3gl2001w3b6idmvkfnfl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzmr2zmg00043b6iegvf22ep%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzmr2zmg00043b6iegvf22ep%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 
- This starts happening after upgrading from AG-GRID 26 to AG-GRID 31

**Current behavior**
Clicking on a cell inner button would fire row click events. Stoping the propagation is not working.

**Expected behavior**
Clicking on the cell inner button would just fire the button click handler and none of the parent elements event handlers. 

**Please tell us about your environment:**

* **AG Grid version:** 
31.0.0
* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
* **Language:**
"typescript": "^4.5.5",
 "react": "^17.0.0",

**Comment by nathanhannig** [comment]
did AG Grid move onRowClicked to the capture phase to cause this?

**Comment by jasonlibio** [comment]
Same ask as Nathan, what caused this change?
