### ISSUE TITLE
 Columns Tool Panel

### ISSUE THREAD

**Issue by MohammadBoushi** [ag-grid/ag-grid#8529]
### Problem Description
AG Grid currently does not provide a built-in method to directly modify the column header text in the Columns Tool Panel independently of the main grid column headers. This limitation restricts developers from customizing the display of column headers within the Columns Tool Panel, such as appending or altering text specifically for the tool panel without affecting the main grid column headers.

### Expected Behavior
It would be beneficial to have an option or API that allows the column header text in the Columns Tool Panel to be customized independently from the main grid column headers. This would enable greater flexibility in customizing the user interface and improve the ability to convey different information in the Columns Tool Panel compared to the main grid.

### Use Case
For example, a developer might want to append specific identifiers or labels (such as "_customLabel") to column headers in the Columns Tool Panel for clarity or organizational purposes, without altering the headers displayed in the main grid and without needing to create a custom Columns Tool Panel solely for this purpose.

### Question
Is this functionality already implemented, and I am simply unaware of it?

**Comment by AG-Zoheil** [comment]
Hi 

Thanks for getting in touch via GitHub.

We are currently not considering feature requests via GitHub and we do not believe there is an underlying issue with this feature from a UX perspective.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
