### ISSUE TITLE
[column - fix] statically fixed columns, cannot reorder

### ISSUE THREAD

**Issue by dsln** [ag-grid/ag-grid#853]
I would like to request a feature to fix column positions (not pin) on the left or right of the data grid. 

Expected functionality would be that a columnDef would ensure that the placement of columns before (if fixed left) or after (if fixed right) including when dragging columns to new positions would not be allowed.

I believe there is some similar functionality in Example 1 of Grouping With Aggregation as seen [here](https://www.ag-grid.com/angular-grid-grouping/index.php).

**Comment by ceolter** [comment]
thanks for input, will stick on list, but no promises on if or when it gets in, as we are busy :)

**Comment by seanlandsman** [comment]
tracked by AG-121
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by britvik** [comment]
What's the status on this? I can't seem to find AG-121 in the pipeline anymore. I swear I saw it as a candidate for next release like a month ago. Now it's gone :(. I'm waiting for this feature.

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by priyankaviswan** [comment]
is there a solution for this issue
