### ISSUE TITLE
How to scroll and paginate together

### ISSUE THREAD

**Issue by pingbaohua** [ag-grid/ag-grid#8540]
Can ag-grid scrolling be combined with custom paging, updating the current page number of the pager in real time during scrolling, then how do you know the current page number during scrolling up, by starRow calculation like scrolling down triggers getRows, or some other method

v25.0.1

**Comment by pingbaohua** [comment]
What I use is rowModelType: 'infinite'

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
