### ISSUE TITLE
Custom getRows params request for server side datasource

### ISSUE THREAD

**Issue by evericks** [ag-grid/ag-grid#8556]
As far as I know, QuickFilter only supports the client side, so I want to customize params.request when I call getRows to get the datasource from the server side to perform filtering on many different columns.

```
            params.api.setFilterModel({
                quickFilter: { type: 'contains', filter: 'searchString' },
            })
```
Can i do the same thing?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
