### ISSUE TITLE
Uncaught type error in GrandTotalRow while filtering our all data 

### ISSUE THREAD

**Issue by bellmaxx** [ag-grid/ag-grid#8557]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
In ag-grid instance that has: 
 - quick filters
 - filters enabled,
 - pagination set to true
 - grandTotalRow set to ether top or bottom

When all data is filtered out ether via quick filter or with filters by deselecting (Select All), data is still visible until user tries to scroll or interact with grid instance

https://plnkr.co/edit/wy1BlrdiJvk21Oum?open=main.ts

**Current behavior**
When all data is filtered out from the grid via filters or quick filter while granTotalRow active, ag-grid throws uncaught type error: 

TypeError: Cannot read properties of undefined (reading 'footer')
    at ClientSideRowModel.getTopLevelRowDisplayedIndex (main.esm.mjs:44282:31)
    at PaginationService.calculatePagesMasterRowsOnly (main.esm.mjs:39430:47)
    at PaginationService.calculatePages (main.esm.mjs:39353:14)
    at PageBoundsListener.calculatePages (main.esm.mjs:41087:30)
    at PageBoundsListener.onModelUpdated (main.esm.mjs:41075:10)
    at callback (main.esm.mjs:71:124)
    at main.esm.mjs:75:9
    at Set.forEach (<anonymous>)
    at processEventListeners (main.esm.mjs:67:82)
    at LocalEventService.dispatchToListeners (main.esm.mjs:81:7)

**Expected behavior**
All data is filtered out resulting in empty ag-grid and total row is empty, or displays values according to value formatter function 

* **AG Grid version:** X.X.X
32.1.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript / Angular

**Comment by ava-utting** [comment]
Hi

Thank you for reporting this.

We have attempted to replicate the issue you have described, unfortunately we were unable to do so.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Ava

**Comment by bellmaxx** [comment]
> Hi
> 
> Thank you for reporting this.
> 
> We have attempted to replicate the issue you have described, unfortunately we were unable to do so.
> 
> We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.
> 
> Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.
> 
> We're looking forward to your response.
> 
> Kind regards, Ava

I have updated the replication steps, ag-grid needs to have pagination set to true to reproduce this error.

**Comment by bellmaxx** [comment]
Please see reproducible plunker example:
https://plnkr.co/edit/wy1BlrdiJvk21Oum?open=main.ts

**Comment by tommyho-kkr** [comment]
I am experiencing this error too (TypeError: Cannot read properties of undefined (reading 'footer')) when using the number filter, with GrandTotalRow enabled and searching for a non-existent value

**Comment by ava-utting** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-12621 [Regression] When all data is filtered out and grandTotalRow and pagination are set, TypeError is shown

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Ava

**Comment by bkondrat** [comment]
Hello, I am also facing this issue with the following error:
```
TypeError: Cannot read properties of undefined (reading 'footer')
    at ClientSideRowModel.getTopLevelRowDisplayedIndex (main.esm.mjs:44282:31)
    at PaginationService.calculatePagesMasterRowsOnly (main.esm.mjs:39430:47)
    at PaginationService.calculatePages (main.esm.mjs:39353:14)
    at PageBoundsListener.calculatePages (main.esm.mjs:41087:30)
    at PageBoundsListener.onModelUpdated (main.esm.mjs:41075:10)
    at callback (main.esm.mjs:71:124)
    at main.esm.mjs:75:9
    at Set.forEach (<anonymous>)
    at processEventListeners (main.esm.mjs:67:82)
    at LocalEventService.dispatchToListeners (main.esm.mjs:81:7)
```
This error occurs when I use GrandTotalRow and then try to clear rowData using applyTransaction or even by assigning rowData to an empty array.
Any insights or updates on this issue would be greatly appreciated.

**Comment by brunoravizzinidev** [comment]
Same problem, when we add GrandTotalRow and in a filter, we leave no results, empty rows, gets the error 
Cannot read properties of undefined (reading 'footer')
TypeError: Cannot read properties of undefined (reading 'footer')
    at ClientSideRowModel.getTopLevelRowDisplayedIndex (http://localhost:3005/static/js/bundle.js:445712:31)

Please if someone finds a way to solve it until is resolved in a fix.

Thanks

**Comment by bellmaxx** [comment]
> Hello, I am also facing this issue with the following error:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'footer')
>     at ClientSideRowModel.getTopLevelRowDisplayedIndex (main.esm.mjs:44282:31)
>     at PaginationService.calculatePagesMasterRowsOnly (main.esm.mjs:39430:47)
>     at PaginationService.calculatePages (main.esm.mjs:39353:14)
>     at PageBoundsListener.calculatePages (main.esm.mjs:41087:30)
>     at PageBoundsListener.onModelUpdated (main.esm.mjs:41075:10)
>     at callback (main.esm.mjs:71:124)
>     at main.esm.mjs:75:9
>     at Set.forEach (<anonymous>)
>     at processEventListeners (main.esm.mjs:67:82)
>     at LocalEventService.dispatchToListeners (main.esm.mjs:81:7)
> ```
> 
> This error occurs when I use GrandTotalRow and then try to clear rowData using applyTransaction or even by assigning rowData to an empty array. Any insights or updates on this issue would be great


@brunoravizzinidev this is the pagination issue rather then total row. For the time being if you disable pagination, you should be good.
