### ISSUE TITLE
Row height not adjusting automatically despite using autoRowHeight in ag-Grid Community

### ISSUE THREAD

**Issue by jiajing21387177** [ag-grid/ag-grid#8563]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I'm experiencing an issue with row height not adjusting automatically as expected when using the autoRowHeight feature in ag-Grid Community. I followed the official documentation for configuring the autoRowHeight as mentioned [here](https://www.ag-grid.com/javascript-data-grid/row-height/#auto-row-height). However, the rows in my grid are not resizing to fit the content correctly.

Steps to Reproduce:

- Set up ag-Grid Community with row data containing multi-line text.
- Apply the autoRowHeight setting according to the official documentation.
- Observe that the rows do not adjust their height to fit the content properly.

gridOptions:
```
const gridOptions = {
    localeText: AG_GRID_LOCALE_TW,
    columnDefs: [
        {
            headerName: 'Order Items',
            field: 'items',
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains']
            },
            valueFormatter: (p) => {
                console.log(p)
                return JSON.parse(p?.data?.items_json || null)?.join('\n')
            },
            cellClass: ['whitespace-pre-line'],
            cellStyle: { "white-space": "pre-line" },
            wrapText: true,
            autoHeight: true,
        },
        // More columns
    ],
    defaultColDef: {
        minWidth: 150,
        flex: 1,
    },
    domLayout: 'autoHeight',
    rowModelType: 'infinite',
    cacheBlockSize: 100,
    cacheOverflowSize: 2,
    maxConcurrentDatasourceRequests: 2,
    infiniteInitialRowCount: 1,
    maxBlocksInCache: 2,
    pagination: true,
    paginationPageSize: 100,
    paginationPageSizeSelector: [100, 200, 300],
    getRowId: (params) => {
        return params.data.id;
    },
    onGridReady: getOrders
};
```

**Current behavior**
Row height not adjusted correctly.
![image](https://github.com/user-attachments/assets/33b91ca0-a33a-448f-8940-ad1b3ddb022d)

**Expected behavior**
[This](https://codesandbox.io/s/6gpft2?file=/main.js) is what I looking for.

**Please tell us about your environment:**
* **OS**
Windows 10

* **IDE**
VS Code

* **Browser: Edge**

* **AG Grid version:**
Latest AG Grid version: 
- https://cdn.jsdelivr.net/npm/ag-grid-community/dist/ag-grid-community.min.js
- https://cdn.jsdelivr.net/npm/ag-grid-community@32.0.1/styles/ag-grid.min.css
- https://cdn.jsdelivr.net/npm/ag-grid-community@32.0.1/styles/ag-theme-quartz.min.css

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0

* **Language:** [all | ES6/7 | ES5]

**Comment by sabahang** [comment]
@jiajing21387177 are you still facing this issue?
