### ISSUE TITLE
Bug Report - Vertical borders have notches in them

### ISSUE THREAD

**Issue by RaphyRaph** [ag-grid/ag-grid#8567]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
![screenshot-Arc-001058@2x](https://github.com/user-attachments/assets/9223a7de-5800-4145-bc4f-524c2339cf33)

you can reproduce this by going to the theme builder https://www.ag-grid.com/theme-builder/
![screenshot-Arc-001060@2x](https://github.com/user-attachments/assets/71b571be-5aa6-452b-a07b-49ab3654dbe4)

**Expected behavior**
![image](https://github.com/user-attachments/assets/119a7448-4b40-4ac4-b7dc-fea27bb35c63)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12665**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
