### ISSUE TITLE
CSS variable --ag-row-vertical-padding-scale doesn't work

### ISSUE THREAD

**Issue by bbeas** [ag-grid/ag-grid#8581]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1. defined a custom CSS class
```
.ag-theme-custom {
  --ag-foreground-color: #000000D9;
  --ag-font-family: inherit;
  --ag-accent-color: #087AD1;
  --ag-border-color: #D7E2E6;
  --ag-wrapper-border: false;
  --ag-header-font-weight: 400;
  --ag-header-font-size: 13px;
  --ag-header-text-color: #000000D9;
  --ag-border-radius: 2px;
  --ag-wrapper-border-radius: 2px;
  --ag-inherited-row-vertical-padding-scale: 0.6;
  --ag-font-size: 13px;
  --ag-cell-horizontal-padding-scale: 0.7;
  --ag-row-vertical-padding-scale: 0.6;
}
```
2. applied the custom CSS class to the AGGridReact component
```
<div className="ag-theme-quartz ag-theme-custom">
  <AgGridReact
    key={tableId}
    ref={gridRef}
    ...
  />
</div>
```

**Current behavior**
The --ag-row-vertical-padding-scale variable did not take effect as expected, unlike in the official ag-Grid theme builder demo (https://ag-grid.com/theme-builder/). The row height in my grid did not change accordingly.
I inspected the elements and styles from the Console and didn't find the variable --ag-row-vertical-padding-scale in my page.

**Expected behavior**
The row height changes as what I set.

**Please tell us about your environment:**
* **Node.js version:** v14.17.0

* **AG Grid version:** v32.1.0

* **Browser:** Chrome: 127.0.6533.89 (arm64)

* **Language:** TypeScript

**Comment by sabahang** [comment]
Hi @bbeas 

I can see that you have also reached out on Zendesk. It seems you are using the default themes but trying to modify them using theme builder. Theme builder is designed to work independently from our built in themes.

Please use the Zendesk thread you created to let us know if you need any help with this. I'm going to close this ticket for now as we have provided you an answer on Zendesk already

Best
