### ISSUE TITLE
Missing values in Set filter

### ISSUE THREAD

**Issue by SlavikSurminskiy** [ag-grid/ag-grid#8586]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Providing a Reproducible Scenario**
You can reproduce this [here](https://codesandbox.io/p/sandbox/provided-filters-forked-rqcg3g?workspaceId=ec95b739-f4ef-424c-98e7-2504594b45ef&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm014ouq60006356jmj68fzri%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm014ouq60002356j5ck3oyqb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm014ouq60003356j0btulv8b%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm014ouq60005356j5v9c8ygv%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm014ouq60002356j5ck3oyqb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm014ouq50001356jww23uem4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fmain.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm014vttf001j356isux62fe4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A90%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A90%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp.component.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm014ouq60002356j5ck3oyqb%2522%252C%2522activeTabId%2522%253A%2522cm014vttf001j356isux62fe4%2522%257D%252C%2522cm014ouq60005356j5v9c8ygv%2522%253A%257B%2522id%2522%253A%2522cm014ouq60005356j5v9c8ygv%2522%252C%2522activeTabId%2522%253A%2522cm02bm9p6000s356i1j3sqph1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm014ouq60004356jgdqq6lud%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm02bm9p6000s356i1j3sqph1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm014ouq60003356j0btulv8b%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm014ouq60003356j0btulv8b%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 
- Open filter for 'Sport' column
- Verify a result.

![image](https://github.com/user-attachments/assets/6fb59751-d20e-41d1-ba2c-ae0b1941e13f)

**Current behavior**
The list of values in the Set filter is incorrect. The filter doesn't differentiate between lowercase and uppercase strings. Using refData, we can display the correct values, but only one value is shown in the Set filter.

**Expected behavior**
All unique values are presented in the Set filter. In the example provided above, there should be two items in the filter list ('Sport a' and 'Sport A').

**Please tell us about your environment:**
Window 11, npm

* **AG Grid version:** 32.1.0

* **Browser:** All brousers

* **Language:** all

**Comment by sabahang** [comment]
Hi @SlavikSurminskiy have you tried the caseSensitive Property? 
https://www.ag-grid.com/javascript-data-grid/filter-set/#reference-ISetFilterParams-caseSensitive

**Comment by SlavikSurminskiy** [comment]
> Hi @SlavikSurminskiy have you tried the caseSensitive Property? https://www.ag-grid.com/javascript-data-grid/filter-set/#reference-ISetFilterParams-caseSensitive

Hi @sabahang. Thanks to you, I noticed that I was using 'agMultiColumnFilter' instead of 'agSetColumnFilter'. The caseSensitive property solves the issue. The following code works as expected:
```
filter: "agSetColumnFilter",
filterParams: {
  caseSensitive: true,
}
```
However, there’s still an issue with case sensitive when using 'agMultiColumnFilter'. The following approach doesn’t work. I don't think this should be considered a bug, but it could be seen as an improvement.
```
filter: "agMultiColumnFilter",
filterParams: {
  caseSensitive: true,
}
```

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-1755**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
