### ISSUE TITLE
https://www.ag-grid.com/example/

### ISSUE THREAD

**Issue by ArjunVS2** [ag-grid/ag-grid#8589]
can u give an example of large data rendering in aggrid without having large jsheap in memory and minimal cpu usage in browser and the scroll has to work fast like ur demo example

**Comment by ArjunVS2** [comment]
Can anyone please take a look on this . i were scrolling through the grid and turned on virtualization its scrolling smoothly but blank white space coming first then only data loading but in your example even its 10000 rows with out any blank screen its scrolling . Can anyone help me on this

**Comment by ArjunVS2** [comment]
Can anyone please take a look on it

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
