### ISSUE TITLE
Will Advanced Filter be able to compare two column values?

### ISSUE THREAD

**Issue by cseickel** [ag-grid/ag-grid#8597]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

This is somewhere in between a feature request and a question. I am hoping you can tell if this feature is in the works so I now if I should wait for you or just build it out myself.

Your advanced filter is great, but I don't see any way to compare the value of one column to the value of another column. Right now the left hand side has to be a column, and the right hand side has to be a primitive value. Is it now possible, or will it be, to have both sides be a column reference?

Thank you for your time.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12934**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
