### ISSUE TITLE
SetFilterModel doesn't set filter values if they don't exist in data while setting filter

### ISSUE THREAD

**Issue by kaizukuluffy** [ag-grid/ag-grid#8602]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
I'm saving filter model using gridApi.getFilterModel(). On page refresh/render,  I'm getting these values and setting them on onFirstDataRendered using gridApi.setFilterModel. 
If I have values ['a', 'b', 'c'] in filter for column colA and if my first data contains only ['b'], then ['a', 'c'] filters are not applied and ignored. 

If I get a new row with colA = 'a' or 'c', they are not displayed as filter is set to 'b'

If my first data only contains colA= 'd', then all three filter values are not applied and filter is set to blank. If more rows appear with 'a' or 'c', page has to be refreshed for them to appear on screen 

**Expected behavior**
all filters should be applied even if the values are not in the first data rendered 

* **AG Grid version:** 32.0

* **Browser:**

**Comment by ava-utting** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Ava

**Comment by kaizukuluffy** [comment]
Hi @ava-utting 
Thanks for looking into it. 

Here is an example. 

https://plnkr.co/plunk/MQO20bUoZUvRLoUP

As you can see, on initial load, I have two types of sports being loaded into the grid (Volleyball & Cycling)
OnFirstDataRendered, I'm setting a filter on (Volleyball & Swimming)
A few seconds later, I'm loading more rows into the grid with (volleyball, Swimming, Cycling, Cross Country Skiing)

Expectation:
Filter should only display Volleyball & Swimming as filtermodel is applied 

Current:
Filter is only applied on Volleyball and Swimming is ignored 

Usecase:

Swimming might not be in the initial data, but can appear later as new rows are added to the grid. Since this filter is ignored, only subset of filtered values are displayed

![Screenshot from 2024-08-27 13-44-59](https://github.com/user-attachments/assets/da45ae89-a676-40ac-a754-fff2d555c1e3)

**Comment by ava-utting** [comment]
Hi,

Thanks for reaching out.

Here is your example altered to fit the expected behaviour: [https://plnkr.co/edit/10Ged1D8a3xO68C6](url)

Initially the data is only filtered by volleyball, once the rest of the data is loaded it filters by volleyball and swimming. 

I have changed the event you are using to **onModelUpdated** event instead of **onFirstDataRendered** as this was only firing when the data first enters the grid.

Kind regards,
Ava

**Comment by kaizukuluffy** [comment]
@ava-utting 
Wouldn't it break the filter ? Since we're re-setting filter on model update, every time I select any other filter, it overrides with my old filter. 
In the above plunker, I can't change the filter once it's set
