### ISSUE TITLE
Number format for Excel export is exported in 4 digit

### ISSUE THREAD

**Issue by san22230165** [ag-grid/ag-grid#8605]
I am using ag-grid-community, version: 29.0.0

in Export-To-Excel functionality, we need a number to export as %, which is formatted incorrectly.
We are using, [excelStyles]="excelStyles" for formatting.

  public excelStyles: any = [
    {
      id: 'percentageFormat',
      numberFormat: {
          format: "#,##0.00 %"
      },
    },
   ];

example if number was 12.34,in excel it is 1234.00%
expected: 12.34%
Please help us, what formatting we need to use.

Please do the needful.

**Comment by gportela85** [comment]
Hi @san22230165 , since Excel Export is an enterprise feature can you please you our Zendesk support channel for this issue?
Thanks
