### ISSUE TITLE
How to comply with AG Grid's licensing from a technical point of view in the case of web browser extensions?

### ISSUE THREAD

**Issue by hydravion** [ag-grid/ag-grid#8607]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

Hello,

I am about to release a tabs and bookmarks management Chrome browser extension built with AG Grid and I have reached out to `info@ag-grid.com` for clarification with regard to the number of Deployment licenses needed.

I was told that if my SaaS was hosted e.g. on AWS, I would need a single Deployment license. However, since I have built a browser extension running locally on the customers' computers, I was told that I would need one Deployment license _per customer_, and even if obtaining an Unlimited Deployment license (assuming for instance dozens of thousands of customers), I would have to pay around $60'000.

I would like to know from a technical point of view at which point I would be complying with AG Grid's licensing when transitioning to a hosted model. I suspect that the sensitive part is where the license key code is stored.

Instead of storing the key in the extension, can I simply have the browser extension run locally on the users' personal computers and have a validation mechanism checking with a remote server storing the license key that the key is valid?

Would that be enough or do I need to do more? If so, at which point would I be compliant? Do I need to turn my extension into a fully-fledged web app and if so, could you clarify the specific requirements?

I have asked this question to `info@ag-grid.com`, but they did not address it unfortunately.

I would appreciate any advice on how to move forward in my situation.

**Edit.**
Since AG Grid's validation logic runs locally and the key must be provided in that local execution environment, isn't the license key exposed regardless of how my SaaS is built?
Even if I was deploying to AWS, wouldn't AG Grid still validate the license in the browser with an exposed license key?

What should I do? Should I move to a server-based model if AG Grid will expose the key regardless?

What do I need to do so that a single Deployment license is required?

Thank you in advance for your help.

Kind regards,
Idris

**Comment by AG-Zoheil** [comment]
Hi Idris,

Thank you for reaching out about this.

I have read the email thread between yourself and our team including the final email which was a response from our team to yourself.

Our GitHub issues platform serves as a community forum and a place to report any potential bugs.

Therefore if I could please ask you to forward the questions you have posted above - in a similarly direct manner of asking them - and any other queries you may have to `info@ag-grid.com` and you would certainly receive an appropriate response to them.

Kind regards,
Zoheil
