### ISSUE TITLE
Custom filter options placeholder

### ISSUE THREAD

**Issue by abhi747** [ag-grid/ag-grid#8609]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

There is a column receiving a timestamp value in the format of YYYY-MM-DD, hh:mm:ss AM/PM. An example of this format is 2024-01-01, 02:04:05 AM. I need to add a custom filter option to filter out range values for such data, which can take from and to timestamp values and return the filtered result.

I am trying with `filterOptions` in filterParams` as per below, which seem to work. Is there a way to specify placeholder text for the to custom filter inputs?

  ```
{
    field: 'timestampColumn',
    filter: 'agTextColumnFilter',
    filterParams: {
      filterOptions: [
        {
          displayKey: 'between',
          displayName: 'Between',
          predicate: ([filterFromDate, filterToDate], cellValue) => {
            const cellDate = new Date(cellValue); 
            const startDate = new Date(filterFromDate);
            const endDate = new Date(filterToDate);
            return cellDate > startDate && cellDate < endDate;
          },
          numberOfInputs: 2,
        },
      ],
    },
  },
```

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
