### ISSUE TITLE
An empty text is pasted instead of the clipboard content (Chrome, Edge only)

### ISSUE THREAD

**Issue by stophi-dev** [ag-grid/ag-grid#8610]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Precondition: Pasting from clipboard is _not allowed_ for ag-grid.com (browser settings)

1. Load example page https://www.ag-grid.com/react-data-grid/clipboard/
2. Copy "Michael Phelps" (ctrl+c) from first row.
3. Paste (ctrl+v) it to the forth row (replace "Natalie Coughlin").

Result: An empty text is pasted instead of "Michael Phelps".

It however works with a second and all subsequent pastes. After reloading the page, it again fails for the first paste.
Everything works correctly if the user allowed paste for ag-grid.com.

**Expected behavior**
The text "Michael Phelps" should be pasted. 

**Please tell us about your environment:**
Microsoft Windows 10 Pro, 10.0.19045 Build 19045

* **AG Grid version:**
31.2.1
(Issue still exists on current example page)

* **Browser:**

  - **Chrome:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
  - **Edge:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0'
  - Not reproducable with Firefox.

* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hi @stophi-dev,

Thank you for raising this. You can see why this happens by checking the console log of this plunker when copying: https://plnkr.co/edit/tMzPJ4OTVGPdmYzy?open=main.js.

Please see the following property to overcome this: https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-clipboard-suppressClipboardApi.

Kind regards,
Zoheil
