### ISSUE TITLE
The Date Editor does not work correctly with UTC dates

### ISSUE THREAD

**Issue by kaciakmaciak** [ag-grid/ag-grid#8611]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'
```

**Current behavior**

When using dates in UTC, once the date cell is edited the resulting date is in the local timezone, which means, it might be different date than what intended. There is no way how to intercept the returned value from the date picker to convert time zones.

**Expected behavior**

The date is the same as the one selected in the date picker.

Please run [Plunker](https://plnkr.co/edit/4dRxF4dOg4lbhKCO?open=index.tsx&preview) in any timezone other than UTC to see the issue.

I understand that while having the date times in local timezone might be correct, the fact that this behaviour cannot be modified makes it extremely impractical. For example, we are using SSRM and the dates returned from the data source are in UTC. I think, this behaviour could be easily modified by either adding the `utc` flag to the params or exposing a parsing function.

**Please tell us about your environment:**

* **AG Grid version:** 32.0.2

* **Browser:** N/A

* **Language:** all

**Comment by StefanStanic95** [comment]
Doesn't seem to be easily modifiable according to docs. I had to write my own valueSetter to keep the dates in UTC:

My dates are in string format so I used:
```ts
        cellEditor: 'agDateStringCellEditor',
```

Added a generic valueSetter to all my date field ColDefs:
```ts
import { zonedTimeToUtc } from 'date-fns-tz';

        valueSetter: (params: ValueSetterParams) => {
          const fieldName = params.colDef.field;
          if (!fieldName) return false;
          const newValueDate: Date = params.newValue;
          const newValueDateUtc = zonedTimeToUtc(newValueDate, 'UTC');
          params.data[fieldName] = newValueDateUtc.toISOString();
          return true;
        },
```
This example uses `date-fns-tz` to perform the conversionyou can look up its source to figure out how to do the same without a library.

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
