### ISSUE TITLE
Facing issue when programatically moving a node from source node to target node when target node is not loaded in ag grid viewport.

### ISSUE THREAD

**Issue by hem1232** [ag-grid/ag-grid#8612]
**Facing issue when programatically moving a node from source node to target node when target node is not loaded in ag grid viewport.**

We are using Ag Grid SSRM with tree data and programatically trying to move node from one heirarchy to another heirarchy.

We tried few approaches like calling ensureIndexVisible,getRows methods etc but it is not working.

Has anyone encountered the similar issue and got any solution for above scenario?

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
