### ISSUE TITLE
Can we add the no-font styles into the exports list?

### ISSUE THREAD

**Issue by ramseyfeng** [ag-grid/ag-grid#8613]
**Version Info:**

```
{
"ag-grid-community": "^32.1.0",
...
"vite": "^5.3.1",
}
```

We want to use the `no-font` styles for the material theme, and we will run into issues with the below import in styles.scss:

`@import 'ag-grid-community/styles/ag-theme-material-no-font.css';`

if we change the import to ag-theme-material.css, it works well: 

`@import 'ag-grid-community/styles/ag-theme-material-no-font.css';`

We notice the reason is that the `ag-theme-material-no-font.css` has been declared in the package.json exports list, and vite seems will check the exports and throw an error if the import style is not defined in the exports list.

<img width="737" alt="image" src="https://github.com/user-attachments/assets/3694014d-16f3-46b3-9a11-3be3df71af41">

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Please upgrade to `32.2.0` where this has been rectified.

Kind regards,
Zoheil
