### ISSUE TITLE
Blocked aria-hidden on a <div> element because the element that just received focus (on horizontal scroll element)

### ISSUE THREAD

**Issue by svihpinc** [ag-grid/ag-grid#8618]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
Also logged on zendesk

**Current behavior**
On using the horizontal scroll using mouse, I got this error in chrome:

Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.

![image](https://github.com/user-attachments/assets/ebd31960-0207-49a9-924d-c45ea9b2842c)

**Expected behavior**
No error

**Please tell us about your environment:**
Windows 10

* **AG Grid version:** 32.0.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

* **Language:** [ES6/7]

**Comment by akphi** [comment]
I also got this error when toggling hide/show field in columns tool panel

**Comment by AG-Zoheil** [comment]
Hi,

Thanks for raising this but please refrain from raising the same issue in several places as it causes inefficiencies for both of us.
As an enterprise user please always used ZD to raise issues or ask for support.

I will close this issue here and would kindly request you to continue the conversation in the ZD thread.

Thank you!
