### ISSUE TITLE
Some documentation parts are not updated to Vue 3

### ISSUE THREAD

**Issue by lucaspmarra** [ag-grid/ag-grid#8620]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**
Some of the more “unknown” pages are out of date, showing code from Vue 2, such as “methods”, “filters” (deprecated) and so on.
Could you check these points?
Example: [Vue Data Grid - Custom Components](https://www.ag-grid.com/vue-data-grid/components/)

Current behaviour.
Receive updated code from Vue 3.

**Comment by AG-Zoheil** [comment]
Hello @lucaspmarra,

Thank you for the suggestion.

We have added the requirement to update this to our backlog and we are tracking it with the following reference: **AG-12939**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
