### ISSUE TITLE
Assistance Required: Activating "Expand All" and "Collapse All" Buttons Based on Row Node State in ag-Grid for Angular

### ISSUE THREAD

**Issue by Pratik38237** [ag-grid/ag-grid#8621]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- I need assistance with a specific requirement. The project involves implementing row grouping, and part of the requirement is to determine whether all row nodes in the grid are expanded or collapsed at any given time.
- **Current Implementation:**
Buttons: I have two buttons: "Expand All" and "Collapse All."
Goal: These buttons should be active or inactive depending on whether the row nodes in the grid are expanded or collapsed.
Approach Tried: I’ve already attempted using the GridApi.forEachNode function to check the expanded or collapsed state of the groups, but it doesn’t fully meet the requirement.
- [Plunker Link](https://plnkr.co/edit/MNdVeF3srpyJkOmq?open=app.component.ts)
- Identify Expanded/Collapsed State: I need to check if all row nodes within the grid are either fully expanded or collapsed.
- **Request:**
Alternative Solution: Could you please provide guidance on any other approach or API within ag-Grid that could help achieve this functionality?

**Please tell us about your environment:**
OS: Windows
IDE: VSCode
Package Manager: NPM

* **AG Grid version:** 
  31.1.1

* **Browser:**
 Chrome, Firefox, Edge.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 5.2.2

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
