### ISSUE TITLE
Filter popup is hidden inside the grid but not appending to the body when the size of the grid is less 

### ISSUE THREAD

**Issue by kapil2209** [ag-grid/ag-grid#8626]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
 When the size of the grid is less when I tried to filter from the menu If there is not matching record. The filter popup is hiding inside the agrid.

![image](https://github.com/user-attachments/assets/603f3e92-0af4-4595-88da-eb3604cebfa8)

**Expected behavior**
 The Filter Popup should appended to the body make filter fully visible instead of scrolling.

AG Grid version: 32.0

**Comment by AG-Zoheil** [comment]
Hi @kapil2209,

can you please provide more information. You are describing the filter pop up but your screenshot shows the column menu.

Please provide a plunker including steps to follow to reproduce the behaviour you are trying to report.

Many thanks!

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
