### ISSUE TITLE
How do I update table data so that the scroll bar does not move?

### ISSUE THREAD

**Issue by afr751116** [ag-grid/ag-grid#8628]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```
I updated the table data using the following code, and then pulled the scroll bar back to its original position. Is there a way to replace setRowData to keep the scrollbar in place without human intervention

`     
        const verticalScrollPosition = this.gridApi.getVerticalPixelRange().top;    
        this.gridApi.setRowData(this.data);
        setTimeout(() => {
          const gridBody = document.querySelector('.ag-body-viewport');
          if (gridBody) {
            gridBody.scrollTop = verticalScrollPosition;
          }
        }, 0);   `

**Please tell us about your environment:**
* **AG Grid version:** 30.2.0

* **Browser: Google Chrome 128.0

* **Language:[ TypeScript 4.3.5 | ES5]

**Comment by ava-utting** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Ava

**Comment by afr751116** [comment]
Hello, link here
https://plnkr.co/edit/f4JvrAmQMfmNsXTU?open=app.component.ts&preview
Because setRowData has been deprecated and I am not familiar with the new API, what was created is an explanatory link, as shown in the following figure. Before using setRowData, the position of the scrollbar was here. If the top 500, after using setRowData, the position of the scrollbar returns to the top 0, the result I want is that after setRowData, the scrollbar remains unchanged
![image](https://github.com/user-attachments/assets/0ae70b7a-ee0d-44bd-a2ba-1803d24317eb)
![image](https://github.com/user-attachments/assets/1352c347-ca48-4504-960c-87747f87c583)

**Comment by afr751116** [comment]
> 你好
> 
> 感谢您报告此事。
> 
> 我们很乐意调查此事，但对我们来说最有效的方法是让您提供一个重现该问题的实例。
> 
> 请向我们发送一个显示该问题的实时 Plunker 示例。您可以使用我们网站上的一个示例作为起点。如果您需要进一步的指导，请告诉我们。
> 
> 我们期待您的回复。
> 
> 问候， Ava

Hello, link here
https://plnkr.co/edit/yZTDPG5PBjvdEMMz?open=app.component.ts&preview

For example, I'm going to drag the scroll bar here
![image](https://github.com/user-attachments/assets/a5b92673-f662-414c-9ae0-115a178ffb27)

Then use 《this.gridApi.setRowData(this.newRowData)》
The scroll bar is back at top 0, I want the scroll bar to stay the same, how do I assign it?
![image](https://github.com/user-attachments/assets/fea40736-36de-41fc-8b88-7ca701e2aea9)

**Comment by afr751116** [comment]
> Hi
> 
> Thank you for reporting this.
> 
> We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.
> 
> Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.
> 
> We're looking forward to your response.
> 
> Kind regards, Ava
Hello, link here
https://plnkr.co/edit/yZTDPG5PBjvdEMMz?open=app.component.ts&preview
For example, I'm going to drag the scroll bar here
![image](https://github.com/user-attachments/assets/9208c4e4-24fe-4c80-b5c4-1b0d5fd3562d)
Then use 《this.gridApi.setRowData(this.newRowData)》
The scroll bar is back at top 0, I want the scroll bar to stay the same, how do I assign it?
![image](https://github.com/user-attachments/assets/2471bbb6-a953-470b-b008-f1cd3984c89a)

**Comment by afr751116** [comment]
Already updated link

**Comment by AG-Zoheil** [comment]
Hi @afr751116,

we do not provide support via GitHub.

Please have a look at our documentation - you can start by exploring this: https://www.ag-grid.com/javascript-data-grid/grid-api/#reference-scrolling-ensureIndexVisible

Kind regards,
Zoheil
