### ISSUE TITLE
getModel is deprecated and getRowIndexAtPixel have no replacement

### ISSUE THREAD

**Issue by nicolashenry** [ag-grid/ag-grid#8630]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Not really needed I think

**Current behavior**

Using `api.getModel().getRowIndexAtPixel(api.getVerticalPixelRange().top)` complains that `getModel` is deprecated but no equivalent seems to exists for `getRowIndexAtPixel` in the API (and it is not documented).

**Expected behavior**
Having `getRowIndexAtPixel` available and documented in the API to be able to do something like `api.getRowIndexAtPixel(api.getVerticalPixelRange().top)`.

* **AG Grid version:** 32.1.0

**Comment by AG-Zoheil** [comment]
Hi @nicolashenry,

Thanks for getting in touch about this.

We are looking to replace it with API that allows to get the the first/last row, rather than index based on pixels. This seems to be a more robust approach. E.g.

`api.getFirstNodeInViewport()
api.getLastNodeInViewport()`

Would this meet your expectations?

Kind regards,
Zoheil

**Comment by nicolashenry** [comment]
@AG-Zoheil Yes, it would meet our expectations if we can get the index from the node (with sourceRowIndex or rowIndex I guess).

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the quick reply.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12964**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
