### ISSUE TITLE
Docs how to run ag-grid-angular locally

### ISSUE THREAD

**Issue by Althain** [ag-grid/ag-grid#8641]
**I'm submitting a ...**  (check one with "x")
```
[x] support request => see 'Requesting Community Support'
```

Hello, as I didn't receive any help regarding my issue (no blame, I still don't know how to fix it) [https://github.com/ag-grid/ag-grid/issues/8246](https://github.com/ag-grid/ag-grid/issues/8246) I decided to dive deeper and connect the library locally hoping for some more error details or maybe find a way to fix the error, but it shows up it's not documented anywhere how to set up the project locally.

What I figured so far is that I need yarn and nx, but I don't know how to further build the project and link it to angular application. 
Can someone share the knowledge please?

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
