### ISSUE TITLE
Hiding built-in message 

### ISSUE THREAD

**Issue by Girisuta-Mohanty** [ag-grid/ag-grid#8643]
I am using server side aggrid version 31. When I am selecting or deselection or clicking on row one message is getting displayed automatically on the top of aggrid.this is built-in inside aggrid.how to hide that message.

**Comment by AG-Zoheil** [comment]
Hi @Girisuta-Mohanty,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

You can read about getting started with both community or enterprise versions of our grid on [this page](https://ag-grid.com/javascript-data-grid/getting-started/). Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

Do let us know if you have any other questions.

Kind regards,
Zoheil
