### ISSUE TITLE
Column valueFormatter overwrites provided filter valueFormatter

### ISSUE THREAD

**Issue by gioiafueter** [ag-grid/ag-grid#8649]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have set valueFormatter and filterParams.valueFormatter for a column with an array value. I have set each with a different function, one that expects an array for the cell, and one that expects a string for the column filter. When I click on the filter title, the values are not displayed and I get an error, because the cell formatter is called instead of the filter one.

**Expected behavior**
The cell and the filters use each its correspondent formatters when both are provided as stated in the documentation:

"In the code above, the same value formatter is supplied to the Column and Filter params, however separate Value Formatters can be used."

* **AG Grid version:** 31.2.0

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
