### ISSUE TITLE
Row group pinning does not pin column group

### ISSUE THREAD

**Issue by san22230165** [ag-grid/ag-grid#8660]
in angular ag-grid, when pinning a column(pinned: true) (where pinned column is part of a group), shows only the pinned column other columns are not shown, where its visible previously.
Basically, in a column group , is it possible to pin only a particular column(Where other column are still visible).

**I tried applying following ways:**
1.pinned: true only for a column in a group
2.pinned: true for all columns in a group
3.pinned: true to group header
4. the below code:
   this.autoGroupColumnDef = {
  headerName: 'Currency',
  pinned: true
};

I tried all ways. Also see the previous post: https://github.com/ag-grid/ag-grid/issues/1890
Please check if this can be done.

**Comment by SrikanthP0548** [comment]
Did you try this one? 

https://github.com/ag-grid/ag-grid/issues/2152

**Comment by san22230165** [comment]
Hi, 
I tried with the above stuff. but no luck, its not working.

Following are my ag-grid versions:
"ag-grid-angular": "29.0.0",
    "ag-grid-community": "29.0.0",
    "ag-grid-enterprise": "29.0.0",
    
    Do we have any limitation of ag-grid for above stuff?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
