### ISSUE TITLE
Restrict pivot grid autoupdate on adding rowGroup or pivotGroup

### ISSUE THREAD

**Issue by devendra526** [ag-grid/ag-grid#8667]
I am working on a react application and there I have a below requirement. In aggrid pivot, when i add or checked a checkbox of column then the pivot grid should not get updated immediately. I have a button to update that one. Also when checking a checkbox i want to store the values in a object, similar way for removing or adding rowgroup and pivotgroup as well, i did lot of research but did not get a solution on this. Can someone please help me with this.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
