### ISSUE TITLE
AG Grid: Looking for component [] but it wasn't found.

### ISSUE THREAD

**Issue by theonlineaid** [ag-grid/ag-grid#8670]
---

**I'm submitting a ...** (check one with "x")
- [] bug report
- [x] feature request
- [x] support request

**Customers of AG Grid**
I am not a customer of AG Grid, so I am reporting this issue as community support.

**Providing a Reproducible Scenario**
- **AG Grid version**: 28.1.1 (community), 28.1.3 (enterprise), 28.1.1 (react)
- **Framework**: React with TypeScript
- **Scenario**: I have implemented an AG Grid table, but I am facing issues with cell styles and event handling when certain actions (e.g., right-click context menu) occur. Here is a simplified version of the code:

```jsx
<AgGridReact
  ref={gridRef}
  defaultColDef={defaultColDef}
  suppressRowClickSelection
  onDragStarted={onDragStarted}
  onDragStopped={onDragStopped}
  onGridReady={onGridReady}
  onCellClicked={onCellClicked}
  rowData={rowData}
  pagination={true}
  paginationPageSize={rowSize}
  cacheQuickFilter={true}
  animateRows={true}
  getRowHeight={getRowHeight}
  getRowStyle={getRowStyle}
>
  {tableColumns &&
    tableColumns.map((data) => {
      if (data.hide) return null;
      return (
        <AgGridColumn
          key={data.field}
          filter='agTextColumnFilter'
          headerName={!data.hide ? data.headerName : ''}
          field={!data.hide ? data.field : ''}
          headerTooltip={data.headerName}
          width={data.width}
          valueFormatter={data?.valueFormatter}
          valueParser={data?.valueParser}
          cellRenderer={data?.cellRenderer}
          cellStyle={() => {
            return { fontSize: `${fontSize}px`, fontWeight: 'bold' };
          }}
          onCellContextMenu={(e) => {
            toggleMenu(true);
            setSelectedRow(e.data);
          }}
        />
      );
    })}
</AgGridReact>
```

**Current behavior**
- The right-click context menu does not behave as expected when the user interacts with a cell. Additionally, custom `cellStyle` is not being applied consistently across cells.

**Expected behavior**
- The context menu should open properly on right-click, and the styles (font size, font weight) should be applied to cells as defined.

**Please tell us about your environment:**
- **Operating system**: Windows 10
- **IDE**: VS Code
- **Package manager**: npm
- **HTTP server**: local server using `webpack-dev-server`

* **AG Grid version**: 28.1.1 (community), 28.1.3 (enterprise), 28.1.1 (react)
* **Browser**: Chrome (Version 116.0), Firefox (Version 117.0)
* **Language**: TypeScript 4.8.2, ES6

---
![Screenshot from 2024-09-09 17-55-39](https://github.com/user-attachments/assets/059df2aa-7db7-4694-b566-61552edaa616)

![Screenshot from 2024-09-09 17-06-26](https://github.com/user-attachments/assets/ef006cf5-9c33-4558-8769-194907d05170)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
