### ISSUE TITLE
Ag-Grid can't customlized dragEvent

### ISSUE THREAD

**Issue by yshh1234** [ag-grid/ag-grid#8685]
**I'm submitting a ...**  (check one with "x")
```
[] feature request => I'm now typing code for a electron application with Ag-Grid-enterprise.We need to drag a row into other Ag-Grid in other window.So I need to customlized a new dragEvent for it. Where can i get the solution or interface to customlized my dragEvent
```

**Customers of AG Grid**

I'm a enterprise user for ag-grid

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- I'm now typing code for a electron application with Ag-Grid-enterprise.We need to drag a row into other Ag-Grid in other window.So I need to customlized a new dragEvent for it. Where can i get the solution or interface to customlized my dragEvent
- My AgGridVertion is 30.2.1
- All framework contains React & electron & antd

**Please tell us about your environment:**
win11 webstorm yarn vite

* **AG Grid version:** 30.2.1

* **Browser:**
chromium

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
es6  typescript 5.3.3

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Kind regards,
Zoheil
