### ISSUE TITLE
valueFormatter not applied to numeric text with excel export

### ISSUE THREAD

**Issue by leey0818** [ag-grid/ag-grid#8693]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://plnkr.co/edit/BbcnJyA4O9jP5Q3z?open=main.ts&preview

When using the `Excel Export` feature, the valueFormatter is not applied to text formatted as numbers.
Even when cellDataType=text, it is not applied.

**Expected behavior**
The valueFormatter should be applied regardless of the input text.

**Please tell us about your environment:**

* **AG Grid version:** 32.1.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

* **Language:** all

**Comment by JoelWaechter** [comment]
This is a problem that I also struggled with for a long time. I don't know why “useValueFormatterForExport: true” is not applied to numeric values in the default column definitions. I also find it very unfortunate that I could not find a single reference to this in the Ag-Grid documentation. In the meantime, I have at least found a way around the problem:

```ts
  gridOptions: GridOptions = {
    defaultExcelExportParams: {
      author: 'YOUR_AUTHOR,
      fileName: 'YOUR_FILENAME',
      processCellCallback: ({ value, formatValue }: ProcessCellForExportParams<YOURDATATYPE>): string =>
        formatValue(value)
    }
  };
```

**Comment by AG-Zoheil** [comment]
Hi,

Please see the last bullet point on this page: https://www.ag-grid.com/javascript-data-grid/value-formatters/#formatting-for-export

Thank you!
