### ISSUE TITLE
pinnedBottomRow has scrollbar

### ISSUE THREAD

**Issue by bviebahn** [ag-grid/ag-grid#8695]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Please have a look at this codesandbox: https://codesandbox.io/p/sandbox/quick-start-example-forked-kftnf9
If you resize the window, so the grid becomes scrollable, the pinnedBottomRow also gets a scrollbar.

https://codesandbox.io/p/sandbox/quick-start-example-forked-kftnf9

![Screenshot 2024-09-13 at 09 26 06](https://github.com/user-attachments/assets/524a5335-042e-4d5d-b720-a8db89e69c89)

This is how I fixed it for now:
```css
.ag-floating-bottom {
  overflow-y: auto !important;
}
```

**Comment by bviebahn** [comment]
Something strange seems to be going on here. I can't reproduce this on my mac (Chrome) anymore, where I originally encountered this. I don't see a permanent scrollbar anymore, now it only appears when I scroll. On Windows (both Chrome and Firefox) I can still reproduce it, when I resize the window so there is scrollable content, a permanent scrollbar appears (in both the main grid, and the pinnedBottomRow).

![Screenshot 2024-09-16 184753](https://github.com/user-attachments/assets/0dea29e0-6f19-415c-af22-5f626f66bb2f)

**Comment by bviebahn** [comment]
And now I can reproduce it again on Mac 🤨  Very weird...

**Comment by AG-Zoheil** [comment]
Hi @bviebahn,

Thanks for reporting this.

Could you confirm your OS scrollbar settings as these will always override AG Grid's?

E.g. on Windows you would check these by opening `Settings -> Accessibility -> Visual Effects -> Always Show Scrollbars`.

Looking forward to hearing back from you.

**Comment by bviebahn** [comment]
Hi @AG-Zoheil 
By permanent scrollbar I mean the scrollbar is permanently there when there is scrollable content, so when the window is small. I think that's the normal behaviour on Windows, but on Mac usually the scrollbar only appears when you scroll (as it sometimes does, and sometimes doesn't in my testing). But yes, I checked, and this setting is disabled on both Mac and Windows.

I just tested it again on Mac, and it's very strange, sometimes I get the scrollbar that stays there permanently, and sometimes I get the one that disappears when I stop scrolling. That's a little strange, but I wouldn't be bothered by it if the pinnedBottomRow wouldn't also get this scrollbar. I'm not sure if these are two separate issues or if they are related.
Can you not reproduce this? I'm always testing with the codesandbox I linked btw, so you should see it there.

**Comment by AG-Zoheil** [comment]
Hi @bviebahn,

Thanks for clarifying.

We've had a look and this seems to be dependant on your Mac scrolling settings. Please have a look at the screenshot below. We can only reproduce this when setting it to `Always`.

![image](https://github.com/user-attachments/assets/d8b370a0-ca0b-4658-a373-a7924b446e76)

If you change it to `When scrolling` it should resolve it to you.

Kind regards,
Zoheil

**Comment by bviebahn** [comment]
Hi @AG-Zoheil Sorry, maybe I wasn't very clear, the issue isn't really the scrollbar, I was just confused why I sometimes I saw the "always" scrollbar, and sometimes the "When scrolling" (when I didn't change that setting). But anyway, that's not the real issue.

The actual problem is that there also appears a scrollbar in the pinnedBottomRow when there is an "always" scrollbar. 

![367850474-0dea29e0-6f19-415c-af22-5f626f66bb2f](https://github.com/user-attachments/assets/aa1d05f0-3602-4f6b-8202-d92c768ed247)

**Comment by AG-Zoheil** [comment]
Right, thanks for clarifying @bviebahn.

When "always" scrollbar, this is to be expected right now. However we have a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-2856**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AFatNiBBa** [comment]
I also stumbled upon this isssue, but the **AG-2856** issue on the pipeline page seems to be unrelated.
The provided fix doesn't work and it is applied horizontally, rather than vertically.
The problem is that the elements with `.ag-floating-top` and `.ag-floating-bottom` have `overflow-y: scroll` on them instead of `overflow-y: auto`, which makes the scroll-bar always visible even when it is not needed.
This is the fix I'm using
```css
.ag-floating-top, .ag-floating-bottom {
  overflow-y: auto !important;
}
```
