### ISSUE TITLE
Pinned columns are unpinned after moving other columns

### ISSUE THREAD

**Issue by Vagizova** [ag-grid/ag-grid#8699]
**I'm submitting a bug ** 

**Providing a Reproducible Scenario**

[Plunker](https://plnkr.co/edit/9cctrDQuhGjhkceV?open=index.jsx)

**Current behavior**

I have several columns that are pinned to the left and cannot be moved. However, after moving some other columns, the pinned columns no longer really pinned

Steps to reproduce:

1. Move the Price column to the left (pinned) group.
2. move the "Electric" column there too.
3. and here we are. the MAKE column was automatically moved to the right, despite the fact that it is pinned and cannot be moved.

https://github.com/user-attachments/assets/5d777086-c9af-4608-865f-7ea51d9a4ac6

https://github.com/user-attachments/assets/569b5202-980d-4a50-9713-a85a037141fe

**Expected behavior**

I expect the column marked `lockPinned` + `lockPosition` + `pinned` not to move

> The column property lockPosition locks columns to one side of the grid. When lockPosition is set as either "left" or "right", the column will always be locked to that position, cannot be dragged by the user, and cannot be moved out of position by dragging other columns. [src: https://www.ag-grid.com/react-data-grid/column-moving/#lock-position](https://www.ag-grid.com/react-data-grid/column-moving/#lock-position)

I understand that this is due to lack of space, but expect that in this case it will simply be impossible to pin new columns until the old ones are unpinned. And I don't expect that the column with checkboxes will be moved to the center part and there will be no way to get it back (it remains "unmovable")

* **AG Grid version:** 32.1.0

* **Browser:** Chrome Version 128.0.6613.119 

* **Language:** [TypeScript]

**Comment by binerdy** [comment]
I get the same behaviour when resizing the preview window of the plunker mentioned above. When I slowly reduce the width of the preview window, pinned column suddenly jumps and is out of order.

And I get the Model column before the Make column.

I found an explanation to my issue: #8015

**Comment by AG-Zoheil** [comment]
Thank you for the comments. 

Yes, @binerdy is correct - please see the response that was posted below:

When the total width of the pinned columns reaches the the grid viewport width, the user is unable to see any of the unpinned columns. This is why in such cases by default, AG Grid unpins pinned columns starting from the left to the right.

You can override this behavior using the processUnpinnedColumns callback:
https://www.ag-grid.com/javascript-data-grid/grid-options/#reference-columnPinning-processUnpinnedColumns

**Comment by Vagizova** [comment]
Is there way to prevent pinning columns if there is not enough space? like I try to drag it, but it would return to its original place? with `ProcessUnpinnedColumnsParams` I can't get the list of dragged columns? otherwise I would just return this list to `ProcessUnpinnedColumnsParams`. any ideas?

**Comment by AG-Zoheil** [comment]
Hi @Vagizova,

That should be the default behaviour. See our example here: https://plnkr.co/edit/0cHv1BmYlbGvO5dv?open=main.js.

If you reduce the width of the viewport and try to pin COUNTRY the grid will not respond to the command.

**Comment by Vagizova** [comment]
hmmm it will respond.. country was pinned 

https://github.com/user-attachments/assets/d01d8ab8-daef-448c-8703-36955e478e16

**Comment by AG-Zoheil** [comment]
At this width the column is not unpinned. Once you reach the width at which columns are unpinned, you will not be able to pin new columns.
