### ISSUE TITLE
Flickering of Grid without any error

### ISSUE THREAD

**Issue by NAPL214** [ag-grid/ag-grid#8706]
I am using react version 32.1.0 the grid flickers continously after load of data. For the same code the fliker does not occur in version 30.2.1

**Comment by StephenCooper** [comment]
Please add the `debug` flag which will log if a property is being continuously updated that is missing from memorization.

 Please make sure you are following our best practices as outlined here. 

https://www.ag-grid.com/react-data-grid/react-hooks/

**Comment by NAPL214** [comment]
[console-export-2024-9-16_20-23-30.txt](https://github.com/user-attachments/files/17015197/console-export-2024-9-16_20-23-30.txt)

Sir
This is the debug log file if you could kindly analyze and let me know the problem Regards
