### ISSUE TITLE
Angular - Export to PDF(Current Page) - Section header text loses the proper spacing

### ISSUE THREAD

**Issue by san22230165** [ag-grid/ag-grid#8707]
in angular, we are trying to export current-page to PDF.
Basically we use html2canvas , jsPDF (like below) 
  import html2canvas from 'html2canvas';
  import jsPDF from 'jspdf';

**Issue we face:** The text in mat-panel-title, is shown in PDF, without space

**for example:** if mat-panel-title has text called Dashboard Summary, in PDF it renders as DashboardSummary
if mat-panel-title has Net Investment Detail, in PDF it renders as NetInvestment Detail

**Following is the code:**

downloadPDF() {
    html2canvas(this.container.nativeElement, {
      height: 3500, //2200
      allowTaint: false,
      removeContainer: true,
      logging: false,
      y:100,
      scrollY: 0, 
      scale: 1
    }).then(
      (canvas) => {
        var pdf = new jsPDF('p', 'mm', "a4");

        var imgData = canvas.toDataURL('image/jpeg', 1.0);
        const bufferX = 4;
        const bufferY = 4;
        const imgProps = (pdf as any).getImageProperties(imgData);
        const pdfWidth = pdf.internal.pageSize.getWidth() - 2 * bufferX;
        const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
        pdf.addImage(
          imgData,
          bufferX,
          bufferY,
          pdfWidth,
          pdfHeight,
          undefined,
          'FAST'
        );
        pdf.setFont('Roboto, sans-serif', '', 'normal');
        pdf.save('Net_Document.pdf');
      },
      (rejected) => {
        console.log(
          'An error occurred while processing');
      }
    );
  }

Please help us to fix this issue.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
