### ISSUE TITLE
[angular1] angularCompileFilters lack of digest cycle

### ISSUE THREAD

**Issue by dzonatan** [ag-grid/ag-grid#873]
Custom filter is not immediately compiled after filter opening.
The filter gets compiled after first digest cycle which was caused by other factors of the page.

**Comment by seanlandsman** [comment]
tracked by AG-123
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, This should be fixed in the next release
