### ISSUE TITLE
Bug Report: GridOptions.dataTypeDefinitions value formatter being overwritten and replaced by groupSafeValueFormatter generated in DataTypeService.processDataTypeDefinition()

### ISSUE THREAD

**Issue by ENGLISH87** [ag-grid/ag-grid#8753]
I'm submitting a bug report

**Current behavior**
We're currently migrating to the latest version of AG-Grid. We're using `GridOptions` to define valueFormatters and override the default data type value formatters, like so:

```
const opts: GridOptions = {
  ...,
  dataTypeDefinitions: {
    number: {
        baseDataType: 'number',
        extendsDataType: 'number',
        valueFormatter: someValueFormatter,
      },
  },
  ...
}
```

We have a long list of defined column definitions, we didn't want to defined the valueFormatter on every single colDef so used dataTypeDefinitions. Our grid has a large data set with rows grouped by a common attribute. At row cell level the value formatter is used to format and return a string value.

In the file `dataTypeService.ts` => `updateColDefAndGetColumnType()` line 355, the valueFormatter is being overwitten and replaced by the `groupSafeValueFormatter` created by AGGrid in the method `processDataTypeDefinition()` on line 246.

```
return {
  ...mergedDataTypeDefinition,
  groupSafeValueFormatter: this.createGroupSafeValueFormatter(mergedDataTypeDefinition),
};
```
and
```
if (dataTypeDefinition.groupSafeValueFormatter) {
  colDef.valueFormatter = dataTypeDefinition.groupSafeValueFormatter;
}
```

This results in our valueFormatter being overwritten.

**Expected behavior**
The expected behavior would be the that the valueFormatter defined in the `dataTypeDefinitions` applied within GridOptions would work for all cells (group or not).

* **AG Grid version:** 32.1.0
* **Language:** [all]

**Comment by ENGLISH87** [comment]
Arguably, the issue is in the `createGroupSafeValueFormatter()` method. When params.node.group is `true`, and no AggFunction provided.

```
return (params: ValueFormatterParams) => {
    if (params.node?.group) {
        const aggFunc = params.column.getAggFunc();
        if (aggFunc) {
            ...
        }

        // we don't want to double format the value
        // as this is already formatted by using the valueFormatter as the keyCreator
        if (!this.gos.get('suppressGroupMaintainValueType')) {
            return undefined as any;     <///==== Always falls in to this statement
        }
    } else if (this.groupHideOpenParents && params.column.isRowGroupActive()) {
        ...
    }
    return dataTypeDefinition.valueFormatter!(params);
};
```

**Comment by AG-Zoheil** [comment]
Hello,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
