### ISSUE TITLE
IServerSideDataSource getRows does not trigger subsequent call if rowdata is empty in previous call

### ISSUE THREAD

**Issue by akslaa3-2** [ag-grid/ag-grid#8762]
Ag Grid version: 31.3.2
Platform: React

I had usee AG grid server side IServerSideDatasource in order to retrieve data from the DB. 

Issue:
When i give call to the server side and lets say it returns an empty array and in the params.success i set the rowdata as [] count as 0. I am seeing an issue where getRows is not getting triggered on subsequent request

scenario:
we unselect all the options from set filter, and a call is triggered to api which returns an empty set, params.Success({rowData:[], rowCount:0}). Now when i select all again it does not even trigger the getRows to perform the subsequent call.

What i tried?

setting refreshServerSide did not work
RefreshServerSide and setting purge did not work
Calling using event listner and triggering again did not work.

Expected result:

if the Api returns an empty array which is set to params.Success the subsequent call should trigger getRows.

**Comment by jdfouse-equifax** [comment]
I am seeing an issue that could be related. I am only seeing `getRows()` being called sometimes. 

On clear/cancel of a filter we run this code:

```
    this.gridApi.deselectAll()
    this.gridApi.showLoadingOverlay()
    this.gridApi.refreshServerSide() //{ purge: true }
```

With or without `{ purge: true }` option the result is the same behavior. Only sometimes will the code above call `getRows()` and reload the grid. 

This current issue is resulting in the loading overlay showing and no request to get records takes place. Is there a way to force `refreshServerSide()` to always call `getRows()`?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
