### ISSUE TITLE
Single-row deselection in v32.2.0

### ISSUE THREAD

**Issue by charlie-roosen** [ag-grid/ag-grid#8766]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

In v32.1.0 and earlier, it is possible to set single-row selection with deselection allowed using these grid options:

`rowSelection: 'single',` 
`rowMultiSelectWithClick: true,`

In v32.2.0 the selection API has changed and it isn't clear how to get deselection.  I tried the following but the row does not deselect on click:

`selection: {mode: 'singleRow', checkboxes: false, enableClickSelection: true},`

This is using the vanilla JavaScript version.

Deselection not working can also be seen in the documentation example for "Enable Click Selection & Deselection" here:

https://www.ag-grid.com/javascript-data-grid/row-selection-single-row/

None of the "Enable Click Selection" choices deselect on row click.  That is, clicking the row rather than the check box control.

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hello @charlie-roosen,

Thank you for the suggestion.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12902**

This feature will be added into the new selection implementation in **our next release**.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
