### ISSUE TITLE
Angular Quickstart & no support for the theme builder? 

### ISSUE THREAD

**Issue by konstantinkrassmann** [ag-grid/ag-grid#8769]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Setup the project from the angular quick start
- try to integrate a theme build by the theme builder
```
import { themeQuartz } from 'ag-grid-community/theming';

 const myTheme = themeQuartz
    .withPart(iconSetMaterial)
    .withParams({
        accentColor: "#3F8FCA",
        backgroundColor: "#FFFFFF",
        browserColorScheme: "light",
        checkboxUncheckedBackgroundColor: "#DEDEDE",
        checkboxUncheckedBorderColor: "#DEDEDE"
});
```

The error: 

Cannot find module 'ag-grid-community/theming'

It seems like the theme style is not supported or is a module missing? 

* **ag-grid-angular** 32
* **angular** 18

* **Browser:**
current chrome

* **Language:** [TypeScript 5.X]

**Comment by r2musings** [comment]
Did you `npm install "@ag-grid-community/theming"`?  It is a separate package.

**Comment by Vagizova** [comment]
it is separate module, right? 

it seems @konstantinkrassmann uses Packages (not modules) so documentation says: 

> Themes are imported from @ag-grid-community/theming and provided to grid instances using the theme grid option. Users of our all-in-one packages such as ag-grid-community and import themes from there too.

_("from there too" from where? from package? there is no such member.... from module? this contradicts the documentation)_

so I guess we need to have something like this: 

`import { themeQuartz } from 'ag-grid-community';`

right? or im wrong?

And it doesn't work unfortunately 

any ideas why? 

I guess we should not mix packages and modules (docs: https://www.ag-grid.com/javascript-data-grid/modules/#mixing-packages-and-modules). so is there some chance to use themes in package "mode"?

**Comment by r2musings** [comment]
Here is what I did. I created custom theme using Theme builder and I put in a file named my-theme.ts.

```
import { themeQuartz } from '@ag-grid-community/theming';
const myTheme = themeQuartz.withParams({
  accentColor: '#7797BF',
//.... other props
});
export default myTheme;
```

Then, in my ComponentThatUsesTheGridComponent I import that:  
 `  import myTheme from './my-theme';`
   
Then, I make it a prop so I can use in the template:
   
`myTheme = myTheme;`

Then, in template I have:

```
<ag-grid-angular
            [theme]="myTheme"
            [rowData]="myData"
            [columnDefs]="columnDefs"
            style="height: 90%; width: 100%"
          />
```

This is what is in my package.json:

    "ag-grid-angular": "^32.2.0",
    "ag-grid-community": "^32.2.0",
    "@ag-grid-community/theming": "^32.2.0",


This is working for me. Have you tried something similar or am I misunderstanding your issue?

**Comment by Vagizova** [comment]
@r2musings did you read this https://www.ag-grid.com/javascript-data-grid/modules/#mixing-packages-and-modules ? 

seems you mix modules and packages, and they said: 

> Do not mix packages and modules! This will result in a large bundle size!

**Comment by r2musings** [comment]
Seems you are correct after looking at my bundles. Sorry I can't help then (yet). I created a work item for next week for myself to address the issue in our codebase. Once I get it working, will circle back and post solution.

**Comment by Vagizova** [comment]
hello, any updates on it?

**Comment by AG-Zoheil** [comment]
Hi all,

Thank you for reporting this and your comments!

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12924**

This will be fixed in our next release.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

In the meantime, please use the module `npm install "@ag-grid-community/theming"`. Although this is not something we usually recommend for packages, it will be an adequate workaround until this is fixed.

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by konstantinkrassmann** [comment]
> Did you `npm install "@ag-grid-community/theming"`? It is a separate package.
> Do not mix packages and modules! This will result in a large bundle size!

@ag-grid-community/theming is simply not found. 




> Hi all,
> 
> Thank you for reporting this and your comments!
> 
> We have added this bug to our backlog and we are tracking it with the following reference: **AG-12924**
> 
> This will be fixed in our next release.
> 
> The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).
> 
> In the meantime, please use the module `npm install "@ag-grid-community/theming"`. Although this is not something we usually recommend for packages, it will be an adequate workaround until this is fixed.
> 
> Thanks again for bringing this up with us.
> 
> Kind regards, Zoheil

Im glad to point this out!

**Comment by Vagizova** [comment]
@AG-Zoheil Hi! we got new version `"ag-grid-enterprise": "^32.2.1",` but... there still is no way to import themeQuartz from it :)


<img width="525" alt="Screenshot 2024-09-27 at 15 54 56" src="https://github.com/user-attachments/assets/ce820271-d516-49a3-937c-3f15c1f82c47">

any ideas?

**Comment by AG-Zoheil** [comment]
Hi @Vagizova,

`32.2.1` was a patch specifically addressing our selection functionality. There will be another patch later this week to address theming.

Thank you for understanding!
