### ISSUE TITLE
[filter] One floating row to show mini filters for each column

### ISSUE THREAD

**Issue by mikeerickson** [ag-grid/ag-grid#881]
Has anybody out there created an alternate filtering interface, one which provides a separate filter for each column, displayed in first row (before all other rows)?

Trying to reproduce an existing interface we have for a simple react table we created

**Comment by ceolter** [comment]
something i intend to do at some point, but so much to do i can't estimate when it will be done.

**Comment by seanlandsman** [comment]
tracked by AG-124
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
