### ISSUE TITLE
[component] allow ghost icon to be a component, so can look similar to cusom headers

### ISSUE THREAD

**Issue by pbr1111** [ag-grid/ag-grid#884]
Hi, 

When I tried to use a custom header cell (using headerCellRenderer in the column definition), the createGhost method in DragAndDropService doesn't use this custom header. 

Additionally, it must check if angularCompileHeader is active or not.

**Comment by ceolter** [comment]
low priority, as the dnd still works.

**Comment by seanlandsman** [comment]
tracked by AG-125
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
