### ISSUE TITLE
[pagination api] GridOption should accept predefined pagination

### ISSUE THREAD

**Issue by drawyan** [ag-grid/ag-grid#947]
Currently in `paginationController`, there are no options to pass initial pagination settings, and also no options to set the currentPage from external control.

But when using ag-grid as grid view and other custom views, switch between the views will keep the pagination synced, currently there are no way to preset the `startRows` or `currentPage` for ag-grid, or even after the grid has rendered, there are no API could be used to set the current page.

Would be perfect to have the `reset()` function take params of initial pagination settings, such as `startRow` or `currentPage`, and expose `startRow/currentPage` for external changes.

Thank you!

**Comment by onlywei** [comment]
I would love to be able to set the initial start page on the DataSource object that I pass to `gridOptions`.

**Comment by ceolter** [comment]
it's on my plan to provide an API for pagination.

**Comment by mosleywm** [comment]
@ceolter, I'm looking to implement this as well.  Would you happen to have a release date scheduled for pagination API updates? Thanks!

**Comment by ceolter** [comment]
i'm hoping later this month, but can't guarantee, work stack very full.

**Comment by drawyan** [comment]
We really would love this to happen as soon as possible. If anything we could do to speed this up, would love to help out. Thank you!

**Comment by seanlandsman** [comment]
tracked by AG-127
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by Bhawna14** [comment]
Hi..

Is there any update on this?? is this enhancement done?

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
