### ISSUE TITLE
[column] suppress pinning

### ISSUE THREAD

**Issue by killyosaur** [ag-grid/ag-grid#976]
Would love it if there was a way to prevent a column or columns from being pinned or pinnable.

The use case would be something like this: I have a set of columns that I don't want to be moved and I want to always be visible, so I pin those. The rest of the columns I want to be able to move but I don't want them to be pinnable (so if a user moves a column to the pinned section, that column should drop into the start of the unpinned columns).

**Comment by ceolter** [comment]
noted.

**Comment by cc1000** [comment]
As a workaround I'm doing the following (to prevent pinning completely):

```
gridOptions.onColumnPinned = (params: any) => {
    if (params.pinned) {
        this._gridOptions.columnApi.setColumnPinned(params.column, null);
    }
};
```

It would be great to have an explicit suppress option for it though, as with `suppressDragLeaveHidesColumns`. 

Would there be any way to hide the pin icon while dragging as well (this also goes for `suppressDragLeaveHidesColumns`, as asked in https://github.com/ceolter/ag-grid/issues/829)?

**Comment by seanlandsman** [comment]
tracked by AG-128
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by light049** [comment]
Get an error when drag column into pinned group

`moveColumnController.js:199 Uncaught TypeError: Cannot read property 'getActualWidth' of undefined
    at MoveColumnController.getNewIndexForColMovingRight (moveColumnController.js:199)
    at MoveColumnController.workOutNewIndex (moveColumnController.js:76)
    at MoveColumnController.attemptMoveColumns (moveColumnController.js:146)
    at MoveColumnController.onDragging (moveColumnController.js:117)
    at BodyDropTarget.onDragging (bodyDropTarget.js:85)
    at DragAndDropService.onDragging (dragAndDropService.js:128)
    at DragService.onCommonMove (dragService.js:164)
    at DragService.onMouseMove (dragService.js:177)`

**Comment by wrabbit23** [comment]
Is this released?  I don't see it in the pipeline

**Comment by makinggoodsoftware** [comment]
Hi, 

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub, but you might find that yours has already been raised in our pipeline.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by JohnMasterson** [comment]
AG-128 was included in Version 16.

Regards, 

John
